### ISSUE TITLE
System.Data.SqlClient connection issue on OS X

### ISSUE THREAD

**Issue by hitched-simon-williams** [dotnet/corefx#10031]
Attempting to open a connection to a SQL Server 2008R2 database from OS X results in a timeout during the login process:

```
System.Data.SqlClient.SqlException: Connection Timeout Expired.  The timeout period elapsed during the post-login phase.  The connection could have timed out while waiting for server to complete the login process and respond; Or it could have timed out while attempting to create multiple active connections.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=1232; handshake=2559; [Login] initialization=5; authentication=18; [Post-Login] complete=56058;  ---> System.ComponentModel.Win32Exception: Unknown error: 258
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
```

Initially found in an ASP.NET Core MVC Controller, I have recreated the issue with the following console program:

``` c#
using System;
using System.Data.SqlClient;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Attempting to open connection...");
            try {
                SqlConnection conn = new SqlConnection("Data Source=server;Initial Catalog=database;User ID=user;Password=password;Connection Timeout=60;Application Name=dotnetcore");
                conn.Open();
                Console.WriteLine("...Success");
                conn.Close();
            } catch (Exception ex) {
                Console.WriteLine(string.Format("...{0}",ex));
            }
        }
    }
}
```

Both the original ASP.NET MVC Controller and the console program work on Windows.  I have not been able to test on Linux as I currently don't have an environment available.  The OS X machine that the issue was found on can connect to the database using SQLPro for MSSQL.

**Comment by saurabh500** [comment]
@hitched-simon-williams Is this 2008 R2 without SP3 ?

**Comment by hitched-simon-williams** [comment]
I must admit that I hadn't checked that.  I don't maintain the server.  I have just checked and it is 10.50.1600.1. which according to the support site is the original RTM build!  Having read other issues, this may be the issue.  I will arrange to  have the server upgraded to the latest 2008R2 build and retest.

**Comment by saurabh500** [comment]
@hitched-simon-williams Thanks. You can check the version of the server using "SELECT @@VERSION;" query while logged into the server.

**Comment by CalebMacdonaldBlack** [comment]
@hitched-simon-williams What solved this issue? Updating the database?

**Comment by hitched-simon-williams** [comment]
Yes, it turned out that the server our database was hosted on had not been kept up to date.  We installed all the available updates (which included SP3) and the problem went away.
