### ISSUE TITLE
System.IO.IOException: Invalid argument  at System.IO.UnixFileStream.<>c.<FlushAsync>b__47_0(Object state)

### ISSUE THREAD

**Issue by agoretsky** [dotnet/corefx#10084]
Hello!
I am using the following code with .net core rtm:

         var bytes = Convert.FromBase64String(base64string);
         const string arg = @"-format ""%m %w %h %Q"" -";
         var result = await ExecuteCommandAsync("identify", arg, bytes);

        public async Task<string> ExecuteCommandAsync(string command, string arguments, byte[] imageData)
        {
            var executablePath = @"path to imagemagick";

            var processStartInfo = new ProcessStartInfo(Path.Combine(executablePath, command), arguments)
            {
                UseShellExecute = false,
                RedirectStandardError = true,
                RedirectStandardOutput = true,
                RedirectStandardInput = true
            };

            using (var process = Process.Start(processStartInfo))
            {
                if (imageData != null)
                {
                    await process.StandardInput.BaseStream.WriteAsync(imageData, 0, imageData.Length);
                    await process.StandardInput.BaseStream.FlushAsync();
                    process.StandardInput.Dispose();
                }

                process.WaitForExit();

                if (process.ExitCode != 0)
                {
                    var errorOutput = process.StandardError.ReadToEnd();
                    var message =
                        $"Image Magick {command} exited with code {process.ExitCode}. Error message {errorOutput}";

                    throw new Exception(message);
                }

                return await process.StandardOutput.ReadToEndAsync();
            }
        }`
On windows machine everything is ok, but when I use it on ubuntu I get:
```
System.IO.IOException: Invalid argument
   at System.IO.UnixFileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
   at System.IO.UnixFileStream.<>c.<FlushAsync>b__47_0(Object state)
   at System.Threading.Tasks.Task.Execute()
```

**Comment by agoretsky** [comment]
If I remove await process.StandardInput.BaseStream.FlushAsync() it works on ubuntu too, but I guess it should be equal behaviour both on windows and linux
