### ISSUE TITLE
Two ValueTuple tests started failing on Unix when updating to new CoreCLR

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#10207]
```
     ValueTupleTests.TestEquals_GetHashCode [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
              at ValueTupleTests.ValueTupleTestDriver`10.TestEquals_GetHashCode(ValueTupleTestDriver`10 other, Boolean expectEqual, Boolean expectStructuallyEqual)
              at ValueTupleTests.TestEquals_GetHashCode()
     ValueTupleTests.TestCompareTo [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   1
        Stack Trace:
              at ValueTupleTests.ValueTupleTestDriver`10.TestCompareTo(ValueTupleTestDriver`10 other, Int32 expectedResult, Int32 expectedStructuralResult)
              at ValueTupleTests.TestCompareTo()
```

e.g. http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/ubuntu14.04_release_prtest/113/consoleText
cc: @jkotas, @jcouv

**Comment by AlexGhiondea** [comment]
@jcouv is this something you are still working on?

**Comment by jcouv** [comment]
@AlexGhiondea I was not able to find the thread I thought I remembered. I'll try to re-enable the test and see if it passes or needs to be updated.
