### ISSUE TITLE
SslStream fails validating CRL on Linux

### ISSUE THREAD

**Issue by Flavien** [dotnet/corefx#10211]
I am using the `MailKit` NuGet package to send emails on .NET Core 1.0. I am connecting to an Amazon SES endpoint (`email-smtp.eu-west-1.amazonaws.com:587`) using TLS.

On Windows, it works fine, however on Linux, I get an error:

```
System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.<>c__DisplayClass41_0.<ConnectAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyApp.Web.Models.MailClient.<SendEmail>d__7.MoveNext()
```

Drilling down into why the certificate validation fails, I found that the chain has `RevocationStatusUnknown` errors (`unable to get certificate CRL`).

It looks like `SslStream` is not able to access CRL on Linux.

**Comment by bartonjs** [comment]
Using my private PrintChain tool (which just builds an X509Chain object and pretty prints the answer) this seems to work fine... I'll have to see if I can get it to behave differently under SslStream, I suppose.

I started by using `openssl s_client -connect email-smtp.eu-west-1.amazonaws.com:587` and capturing the cert to `testsmtp.cer`

```
jbarton@jsb-ubuntu2:~/coreclr$ ls ~/.dotnet/corefx/cryptography/crls/
7d9c641e.crl  b204d74a.crl
jbarton@jsb-ubuntu2:~/coreclr$ rm ~/.dotnet/corefx/cryptography/crls/*.crl
jbarton@jsb-ubuntu2:~/coreclr$ ./corerun PrintChain.exe testsmtp.cer -mode Online
Validating Certificate: email-smtp.eu-west-1.amazonaws.com

Chain is valid

Chain Element Status:
  CN=email-smtp.eu-west-1.amazonaws.com, O="Amazon.com, Inc.", L=Seattle, S=Washington, C=US

  CN=Symantec Class 3 Secure Server CA - G4, OU=Symantec Trust Network, O=Symantec Corporation, C=US

  CN=VeriSign Class 3 Public Primary Certification Authority - G5, OU="(c) 2006 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US

Chain Summary:
jbarton@jsb-ubuntu2:~/coreclr$ ls ~/.dotnet/corefx/cryptography/crls/
7d9c641e.crl  b204d74a.crl
```

So it downloaded the target from the email-smtp.eu-west-1.amazonaws.com CDP (published by Symantec Class 3 Secure Server CA - G4) and from the Symantec Class 3 Secure Server CA - G4 CDP (published by VeriSign Class 3 Public Primary Certification Authority - G5) and found both the EE and intermediate certificates not expired and not revoked.

When you encounter this error, which `X509ChainElement` has the "unable to get certificate CRL" error?  (X509Chain.ChainStatus is an aggregation of each of the X509ChainElement.ChainStatus items; it'd be useful to know which cert(s) are giving you trouble since I'm not seeing it in a small-scale test.

**Comment by Flavien** [comment]
If I remember correctly, all the certificates in the chain were presenting that error.

The process is run by a non-privileged user, could that be part of the problem?

**Comment by bartonjs** [comment]
@Flavien I seem to have missed your reply, sorry.  Things should definitely work with a non-privileged user, but if you have a network filter in place you could have had your access to those CDPs blocked.

So, a couple of questions:
* Are you still experiencing the problem?
* If you issue a web request to `http://ss.symcb.com/ss.crl` in your failing process does it succeed?
* Have you tried running tcpdump to see what the network traffic during failure looks like?
* Does the problem reproduce if you manually build an X509Chain?

```C#
// The default policy is Online revocation and ExcludeRoot, which is what we want.
X509Chain chain = new X509Chain();
bool happy = chain.Build(cert);
X509ChainElementCollection elements = chain.ChainElements;
Console.WriteLine($"Chain built with {elements.Count} elements, happy={happy}");
for (int i = 0; i < elements.Count; i++)
{
    X509ChainElement element = elements[i];
    Console.WriteLine($"Element {i}: {element.Certificate.GetNameInfo(X509NameType.SimpleName, false)}");
    Console.WriteLine("  Status:");

    foreach (X509ChainStatus status in element.ChainElementStatus)
    {
        Console.WriteLine($"  {status.Status}: {status.StatusInformation}");
    }
}
```

**Comment by bartonjs** [comment]
Since we haven't heard an answer to this question and it's been a while, closing. If there's more information we can reopen it.

**Comment by gugray** [comment]
I am getting a variation of this error when running an ASP.NET Core app on Debian 8. My entry point is also MailKit.MailService.Connect (MailKit 1.8.1; see error details below). The error occurs when the process runs as a non-privileged user. The call succeeds when I run the process as root.

```
System.UnauthorizedAccessException: Access to the path '/root/.dotnet/corefx/cryptography/crls' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.UnixFileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Internal.Cryptography.Pal.CrlCache.GetCachedCrlPath(X509Certificate2 cert, Boolean mkDir)
   at Internal.Cryptography.Pal.CrlCache.DownloadAndAddCrl(X509Certificate2 cert, SafeX509StoreHandle store, TimeSpan& remainingDownloadTime)
   at Internal.Cryptography.Pal.CrlCache.AddCrlForCertificate(X509Certificate2 cert, SafeX509StoreHandle store, X509RevocationMode revocationMode, DateTime verificationTime, TimeSpan& remainingDownloadTime)
   at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.BuildChain(X509Certificate2 leaf, HashSet`1 candidates, HashSet`1 downloaded, HashSet`1 systemTrusted, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan& remainingDownloadTime)
   at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
   at System.Net.Security.CertificateValidation.BuildChainAndVerifyProperties(X509Chain chain, X509Certificate2 remoteCertificate, Boolean checkCertName, String hostName)
   at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback)
   at System.Net.Security.SslState.CompleteHandshake()
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken cancellationToken)
```

**Comment by bartonjs** [comment]
@gugray Whatever process context your user is running under, it's reporting that their home directory (or the $HOME variable) is /root/.

**Comment by gugray** [comment]
I created the user in question (intentionally) with "adduser --system --no-create-home". The process is launched by start-stop-daemon. I can imagine $HOME then ends up pointing to /root/ in my scenario.

Is it intentional that the user that accesses the certificate validation functions must have a home directory? It is _somewhat_ counter-intuitive to me, but admittedly I'm not coming from the Linux world soooo...

Thanks!

**Comment by bartonjs** [comment]
@gugray Downloading CRLs is somewhat expensive (and a complicated performance lag when it happens) so the CRL is cached for future lookup.  However, it does look like we ignore IO failures, but not UnauthorizedAccessException; so that's probably worth changing for future versions.  Since your issue is different than the original, please open a new issue for it.

**Comment by PeteX** [comment]
I've just had a similar problem to the original poster.  I'm okay with the Amazon endpoints, but I get failures with a self-signed certificate, and also when connecting to a server whose certificate was issued by letsencrypt.  In the case of the self-signed certificate, there are two errors: "unable to get certificate CRL" and "certificate not trusted".  In the case of the letsencrypt certificate, there is just one: "unable to get certificate CRL".

The framework is right to say that a self-signed certificate is not trusted, but as far as I can see, there is no reason for it to be trying to download a CRL.

I think the problem may be with certificates that don't include a CRL download location.  (The letsencrypt ones don't, perhaps because you're expected to use OCSP instead.)

This is with ASP.NET Core 1.1, by the way.

**Comment by bartonjs** [comment]
@PeteX OCSP support isn't present on Linux, so OCSP-only CAs won't work with revocation checks.  https://github.com/dotnet/corefx/issues/3034
