### ISSUE TITLE
PR CI builds are all failing in Windows Release builds

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1043]
Started by upstream project "dotnet_corefx_prtest" build number 258
originally caused by:
 GitHub pull request #1042 of commit f7b4faa781834be59c12de304a2301902a48b0d5 automatically merged.
Building remotely on dci-win-fbld-12 (windows-fast windows) in workspace d:\j\workspace\dotnet_corefx_windows_release_prtest
Wiping out workspace first.
java.io.IOException: remote file operation failed: d:\j\workspace\dotnet_corefx_windows_release_prtest at hudson.remoting.Channel@4c40db3a:dci-win-fbld-12: java.nio.file.AccessDeniedException: d:\j\workspace\dotnet_corefx_windows_release_prtest\bin\tests\Windows_NT.AnyCPU.Release\System.Linq.Parallel.Tests\aspnetcore50\coreclr.dll
	at hudson.FilePath.act(FilePath.java:985)
	at hudson.FilePath.act(FilePath.java:967)
	at hudson.FilePath.deleteContents(FilePath.java:1182)
	at hudson.plugins.git.extensions.impl.WipeWorkspace.beforeCheckout(WipeWorkspace.java:28)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1013)
	at hudson.scm.SCM.checkout(SCM.java:484)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
	at hudson.model.Run.execute(Run.java:1718)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Caused by: java.nio.file.AccessDeniedException: d:\j\workspace\dotnet_corefx_windows_release_prtest\bin\tests\Windows_NT.AnyCPU.Release\System.Linq.Parallel.Tests\aspnetcore50\coreclr.dll
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
	at java.nio.file.Files.delete(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at hudson.Util.deleteFile(Util.java:247)
	at hudson.FilePath.deleteRecursive(FilePath.java:1202)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1211)
	at hudson.FilePath.deleteRecursive(FilePath.java:1193)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1211)
	at hudson.FilePath.deleteRecursive(FilePath.java:1193)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1211)
	at hudson.FilePath.deleteRecursive(FilePath.java:1193)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1211)
	at hudson.FilePath.deleteRecursive(FilePath.java:1193)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1211)
	at hudson.FilePath.deleteRecursive(FilePath.java:1193)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1211)
	at hudson.FilePath.access$1100(FilePath.java:191)
	at hudson.FilePath$15.invoke(FilePath.java:1185)
	at hudson.FilePath$15.invoke(FilePath.java:1182)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2685)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:324)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1$1.run(Engine.java:63)
	at java.lang.Thread.run(Unknown Source)
	at ......remote call to dci-win-fbld-12(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1356)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
	at hudson.remoting.Channel.call(Channel.java:752)
	at hudson.FilePath.act(FilePath.java:978)
	... 13 more

**Comment by mmitche** [comment]
Looks like it was just one machine with an orphaned process.  Restarted.

**Comment by mmitche** [comment]
@stephentoub @ellismg Filed dotnet/dotnet-ci/#8 to provide an automated way to reboot machines.

**Comment by stephentoub** [comment]
Thanks, Matt.
