### ISSUE TITLE
GuidConverter.ConvertTo throwing exception to convert valid guid string to Guid object.

### ISSUE THREAD

**Issue by navingh** [dotnet/corefx#10487]
If using the API `GuidConverter.ConvertTo(null, CultureInfo.CurrentCulture, guidStr, typeof(Guid));` we are getting an exception saying.

Error Message:
{"'GuidConverter' is unable to convert 'System.String' to 'System.Guid'."}
Stack Strace : 
```
   at System.ComponentModel.TypeConverter.GetConvertToException(Object value, Type destinationType)
   at System.ComponentModel.TypeConverter.ConvertTo(ITypeDescriptorContext context, CultureInfo culture, Object value, Type destinationType)
   at System.ComponentModel.GuidConverter.ConvertTo(ITypeDescriptorContext context, CultureInfo culture, Object value, Type destinationType)
   at GuidConverterRepoClassic.Program.Main(String[] args)
```

It's a consistent repro with valid Guid Strings.

**Comment by ianhays** [comment]
What your code is saying is that you have a guid and want to convert it TO `typeof(Guid)`, so when you  pass a `string` as the value it understandably complains.

If you want to get a Guid from a string, you should use ConvertFrom: ```(Guid)(new GuidConverter().ConvertFrom(guidStr))```
