### ISSUE TITLE
Metadata reader CanReadFromSameMemoryMappedPEReaderInParallel test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1050]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/257/

```
System.Reflection.Metadata.Tests.MetadataReaderTests.CanReadFromSameMemoryMappedPEReaderInParallel [FAIL]
        System.AggregateException : One or more errors occurred.
        ---- System.BadImageFormatException : Invalid COR20 header signature.
        ---- System.BadImageFormatException : Invalid COR20 header signature.
        Stack Trace:
  Discovered:  System.ComponentModel.Primitives.Tests
              at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
              at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
              at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
              at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Reflection.Metadata\tests\Metadata\MetadataReaderTests.cs(2457,0): at System.Reflection.Metadata.Tests.MetadataReaderTests.CanReadFromSameMemoryMappedPEReaderInParallel()
           ----- Inner Stack Trace #1 (System.BadImageFormatException) -----
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Reflection.Metadata\src\System\Reflection\Metadata\MetadataReader.cs(173,0): at System.Reflection.Metadata.MetadataReader.ReadMetadataHeader(BlobReader& memReader)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Reflection.Metadata\src\System\Reflection\Metadata\MetadataReader.cs(97,0): at System.Reflection.Metadata.MetadataReader..ctor(Byte* metadata, Int32 length, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Reflection.Metadata\src\System\Reflection\Metadata\PEReaderExtensions.cs(71,0): at System.Reflection.Metadata.PEReaderExtensions.GetMetadataReader(PEReader peReader, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Reflection.Metadata\src\System\Reflection\Metadata\PEReaderExtensions.cs(47,0): at System.Reflection.Metadata.PEReaderExtensions.GetMetadataReader(PEReader peReader)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Reflection.Metadata\tests\Metadata\MetadataReaderTests.cs(2457,0): at System.Reflection.Metadata.Tests.MetadataReaderTests.<>c__DisplayClass2c.<CanReadFromSameMemoryMappedPEReaderInParallel>b__2a(Int32 _)
              at System.Threading.Tasks.Parallel.<>c__DisplayClass9`1.<ForWorker>b__12(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Threading.Tasks.Parallel.<>c__DisplayClass9`1.<ForWorker>b__12(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
              at System.Threading.Tasks.TaskReplicator.Replica.Execute()
           ----- Inner Stack Trace #2 (System.BadImageFormatException) -----
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Reflection.Metadata\src\System\Reflection\Metadata\MetadataReader.cs(173,0): at System.Reflection.Metadata.MetadataReader.ReadMetadataHeader(BlobReader& memReader)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Reflection.Metadata\src\System\Reflection\Metadata\MetadataReader.cs(97,0): at System.Reflection.Metadata.MetadataReader..ctor(Byte* metadata, Int32 length, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Reflection.Metadata\src\System\Reflection\Metadata\PEReaderExtensions.cs(71,0): at System.Reflection.Metadata.PEReaderExtensions.GetMetadataReader(PEReader peReader, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Reflection.Metadata\src\System\Reflection\Metadata\PEReaderExtensions.cs(47,0): at System.Reflection.Metadata.PEReaderExtensions.GetMetadataReader(PEReader peReader)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Reflection.Metadata\tests\Metadata\MetadataReaderTests.cs(2457,0): at System.Reflection.Metadata.Tests.MetadataReaderTests.<>c__DisplayClass2c.<CanReadFromSameMemoryMappedPEReaderInParallel>b__2a(Int32 _)
              at System.Threading.Tasks.Parallel.<>c__DisplayClass9`1.<ForWorker>b__12(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Threading.Tasks.Parallel.<>c__DisplayClass9`1.<ForWorker>b__12(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
              at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

**Comment by stephentoub** [comment]
This failed again at http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/555/console:
```
 Discovering: System.Reflection.Metadata.Tests
  Discovered:  System.Reflection.Metadata.Tests
  Starting:    System.Reflection.Metadata.Tests
  xUnit.net console test runner (32-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.
  
System.Reflection.Metadata.Tests.MetadataReaderTests.CanReadFromSameMemoryMappedPEReaderInParallel [FAIL]
        System.AggregateException : One or more errors occurred.
        ---- System.BadImageFormatException : Invalid COR20 header signature.
        Stack Trace:
              at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
              at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
              at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
              at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Reflection.Metadata\tests\Metadata\MetadataReaderTests.cs(2457,0): at System.Reflection.Metadata.Tests.MetadataReaderTests.CanReadFromSameMemoryMappedPEReaderInParallel()
           ----- Inner Stack Trace -----
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Reflection.Metadata\src\System\Reflection\Metadata\MetadataReader.cs(170,0): at System.Reflection.Metadata.MetadataReader.ReadMetadataHeader(BlobReader& memReader)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Reflection.Metadata\src\System\Reflection\Metadata\MetadataReader.cs(97,0): at System.Reflection.Metadata.MetadataReader..ctor(Byte* metadata, Int32 length, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Reflection.Metadata\src\System\Reflection\Metadata\PEReaderExtensions.cs(70,0): at System.Reflection.Metadata.PEReaderExtensions.GetMetadataReader(PEReader peReader, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Reflection.Metadata\tests\Metadata\MetadataReaderTests.cs(2457,0): at System.Reflection.Metadata.Tests.MetadataReaderTests.<>c__DisplayClass2c.<CanReadFromSameMemoryMappedPEReaderInParallel>b__2a(Int32 _)
              at System.Threading.Tasks.Parallel.<>c__DisplayClass8`1.<ForWorker>b__10(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Threading.Tasks.Parallel.<>c__DisplayClass8`1.<ForWorker>b__10(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
              at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
              at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

**Comment by stephentoub** [comment]
And again! http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/557/console
```
System.Reflection.Metadata.Tests.MetadataReaderTests.CanReadFromSameMemoryMappedPEReaderInParallel [FAIL]
        System.AggregateException : One or more errors occurred.
        ---- System.BadImageFormatException : Invalid COR20 header signature.
        Stack Trace:
  Discovered:  System.Collections.Concurrent.Tests
              at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
              at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
              at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
              at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Reflection.Metadata\tests\Metadata\MetadataReaderTests.cs(2457,0): at System.Reflection.Metadata.Tests.MetadataReaderTests.CanReadFromSameMemoryMappedPEReaderInParallel()
           ----- Inner Stack Trace -----
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Reflection.Metadata\src\System\Reflection\Metadata\MetadataReader.cs(170,0): at System.Reflection.Metadata.MetadataReader.ReadMetadataHeader(BlobReader& memReader)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Reflection.Metadata\src\System\Reflection\Metadata\MetadataReader.cs(97,0): at System.Reflection.Metadata.MetadataReader..ctor(Byte* metadata, Int32 length, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Reflection.Metadata\src\System\Reflection\Metadata\PEReaderExtensions.cs(71,0): at System.Reflection.Metadata.PEReaderExtensions.GetMetadataReader(PEReader peReader, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Reflection.Metadata\src\System\Reflection\Metadata\PEReaderExtensions.cs(47,0): at System.Reflection.Metadata.PEReaderExtensions.GetMetadataReader(PEReader peReader)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Reflection.Metadata\tests\Metadata\MetadataReaderTests.cs(2457,0): at System.Reflection.Metadata.Tests.MetadataReaderTests.<>c__DisplayClass2c.<CanReadFromSameMemoryMappedPEReaderInParallel>b__2a(Int32 _)
              at System.Threading.Tasks.Parallel.<>c__DisplayClass8`1.<ForWorker>b__10(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Threading.Tasks.Parallel.<>c__DisplayClass8`1.<ForWorker>b__10(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
              at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
              at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

**Comment by axel-habermaier** [comment]
Possibly related: I get a similar error when trying to compile C# code with Roslyn in the context of the Jetbrains Reshaper test runner. That has never happend before, but now happens almost always when executing the entire test suite. It doesn't happen when I only execute a small amount of tests. It seems to be random which test fails, but its usually at the end of the test run.

``
error CS0009: Metadata file 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll' could not be opened -- Invalid COR20 header signature.
``

I've also seen other (non-GAC) assemblies that fail with an invalid COR20 header signature randomly.

**Comment by stephentoub** [comment]
I don't believe we've seen this issue in almost a year.  I'm going to close it.  If it happens again, we can reopen.

**Comment by stephentoub** [comment]
> I don't believe we've seen this issue in almost a year. I'm going to close it. If it happens again, we can reopen.

This was silly... we haven't seen it happen because the test has been deactivated.  If we believe the issue is fixed, we should remove the [ActiveIssue].

**Comment by joshfree** [comment]
This is failing left and right in the Windows Nano Server outerloop in the /release/1.0.0 branch.  Tagging as blocking-clean-ci and moving up to 1.0.0-rtm to track

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_winnano16_release_tst/7/consoleFull

> 19:07:31 Unhandled Exception: System.BadImageFormatException: Invalid COR20 header signature.
19:07:31    at System.Reflection.Metadata.MetadataReader.ReadMetadataHeader(BlobReader& memReader, String& versionString)
19:07:31    at System.Reflection.Metadata.MetadataReader..ctor(Byte* metadata, Int32 length, MetadataReaderOptions options, MetadataStringDecoder 

/cc @Priya91

**Comment by nguerrera** [comment]
@joshfree That looks like a completely separate issue. As Xunit is creating an exception, the stack trace population is triggering and invalid PDB image. I suspect something there's an issue causing a Windows pdb to be opened as a portable PDB. I would open a separate issue to track it.

cc @mikem8361

**Comment by nguerrera** [comment]
See additional stack frames:

```
19:07:31 Unhandled Exception: System.BadImageFormatException: Invalid COR20 header signature.
19:07:31    at System.Reflection.Metadata.MetadataReader.ReadMetadataHeader(BlobReader& memReader, String& versionString)
19:07:31    at System.Reflection.Metadata.MetadataReader..ctor(Byte* metadata, Int32 length, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
19:07:31    at System.Reflection.Metadata.MetadataReaderProvider.GetMetadataReader(MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
19:07:31    at System.Diagnostics.StackTraceSymbols.GetReader(String assemblyPath, IntPtr loadedPeAddress, Int32 loadedPeSize, IntPtr inMemoryPdbAddress, Int32 inMemoryPdbSize)
19:07:31    at System.Diagnostics.StackTraceSymbols.GetSourceLineInfo(String assemblyPath, IntPtr loadedPeAddress, Int32 loadedPeSize, IntPtr inMemoryPdbAddress, Int32 inMemoryPdbSize, Int32 methodToken, Int32 ilOffset, String& sourceFile, Int32& sourceLine, Int32& sourceColumn)
19:07:31    at System.Diagnostics.StackFrameHelper.InitializeSourceInfo(Int32 iSkip, Boolean fNeedFileInfo, Exception exception)
19:07:31    at System.Diagnostics.StackTrace.CaptureStackTrace(Int32 iSkip, Boolean fNeedFileInfo, Thread targetThread, Exception e)
19:07:31    at System.Diagnostics.StackTrace..ctor(Exception e, Boolean fNeedFileInfo)
19:07:31    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
19:07:31    at System.Exception.GetStackTrace(Boolean needFileInfo)
19:07:31    at Xunit.Sdk.ExceptionUtility.ConvertExceptionToFailureInformation(Exception ex, Int32 parentIndex, List`1 exceptionTypes, List`1 messages, List`1 stackTraces, List`1 indices)
19:07:31    at Xunit.Sdk.ExceptionUtility.ConvertExceptionToFailureInformation(Exception ex)
19:07:31    at Xunit.Sdk.TestFailed..ctor(ITest test, Decimal executionTime, String output, Exception ex)
```

**Comment by mikem8361** [comment]
This has been fixed with corefx commit # 014d16cd98 and coreclr commit # 3a1eb3e7ae1

**Comment by mikem8361** [comment]
Issue #5265

**Comment by tmat** [comment]
Seems like the bug was actually in System.Diagnostics.StackTrace and been fixed.
@mikem8361 could you confirm this issue can be closed?

**Comment by mikem8361** [comment]
Yes, this has been fixed.

**Comment by Jiayili1** [comment]
Disabled test, reopen it.

**Comment by Jiayili1** [comment]
https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/tests/Metadata/MetadataReaderTests.cs#L2639

**Comment by mikem8361** [comment]
What do I need to do? Enable the test? Can't you @Jiayili1 do that?

**Comment by nguerrera** [comment]
There were two distinct issues on this thread. The one @mikem8361 fixed is not the same as the root issue.

**Comment by stephentoub** [comment]
Do we believe the root issue is still around, or should we try re-enabling it?

**Comment by nguerrera** [comment]
I don't recall there being a deliberate fix. I suppose we could try re-enabling, though.

**Comment by mikem8361** [comment]
Yes, there was a fix.  See above.

**Comment by mikem8361** [comment]
Sorry, I guess my fix for #8866 has nothing to do with the original problem in what looks like the System.Reflection.Metadata portable PDB tests.  

I guess the test needs to be re-enabled to see.

**Comment by danmosemsft** [comment]
@Jiayili1 can you please enable this test: remove `        [ActiveIssue(1050)]`. Please then run the test locally some number of times using a script. If it works please submit the PR to remove the ActiveIssue.

**Comment by Jiayili1** [comment]
#18372 Leave a comment

**Comment by danmosemsft** [comment]
Fixed until we get evidence otherwise
