### ISSUE TITLE
RespectParentCancellation Parallel test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1057]
Microsoft.Test.PCP.TestMethods.RespectParentCancellation1 [FAIL]
        Should not be completed.
        Stack Trace:
      d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Threading.Tasks.Parallel\tests\RespectParentCancellationTest.cs(0,0): at Microsoft.Test.PCP.RespectParentCancellationTest.RealRun()

**Comment by stephentoub** [comment]
cc: @AlfredoMS 

Failed again:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/282/console

```
Discovering: System.Threading.Tasks.Parallel.Tests
  Discovered:  System.Threading.Tasks.Parallel.Tests
  Starting:    System.Threading.Tasks.Parallel.Tests
     Microsoft.Test.PCP.TestMethods.RespectParentCancellation1 [FAIL]
        Should not be completed.
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Threading.Tasks.Parallel\tests\RespectParentCancellationTest.cs(0,0): at Microsoft.Test.PCP.RespectParentCancellationTest.RealRun()
  Finished:    System.Threading.Tasks.Parallel.Tests
  
  === TEST EXECUTION SUMMARY ===
     System.Threading.Tasks.Parallel.Tests  Total: 125, Errors: 0, Failed: 1, Skipped: 0, Time: 16.795s
```
