### ISSUE TITLE
Test failure for System.Reflection.Metadata on ARM.

### ISSUE THREAD

**Issue by YongseopKim** [dotnet/corefx#10603]
Three tests fail.

```
Starting:    System.Reflection.Metadata.Tests
  
   System.Reflection.Metadata.Ecma335.Tests.InstructionEncoderTests.LoadConstantR8 [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Reflection.BlobUtilities.WriteDouble(Byte[] buffer, Int32 start, Double value)
            at System.Reflection.Metadata.Ecma335.Tests.InstructionEncoderTests.LoadConstantR8()
  
   System.Reflection.Metadata.Ecma335.Tests.InstructionEncoderTests.LoadConstantR4 [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Reflection.BlobUtilities.WriteSingle(Byte[] buffer, Int32 start, Single value)
            at System.Reflection.Metadata.Ecma335.Tests.InstructionEncoderTests.LoadConstantR4()
  
   System.Reflection.Metadata.Decoding.Tests.CustomAttributeDecoderTests.TestCustomAttributeDecoder [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1.DecodeArgument(BlobReader& valueReader, ArgumentTypeInfo info)
            at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1.DecodeFixedArguments(BlobReader& signatureReader, BlobReader& valueReader, Int32 count)
            at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1.DecodeValue(EntityHandle constructor, BlobHandle value)
            at System.Reflection.Metadata.Decoding.Tests.CustomAttributeDecoderTests.TestCustomAttributeDecoder()
  
Finished:    System.Reflection.Metadata.Tests
=== TEST EXECUTION SUMMARY ===
   System.Reflection.Metadata.Tests  Total: 421, Errors: 0, Failed: 3, Skipped: 0, Time: 14.782s
Finished running tests. End time=13:54:35. Return value was 3
```

Target: RASP3, Ubuntu Mate 16.04, ARM

CoreCLR
- Debug & Release
- Commit: 2b191fa038802f22451640b3eac13cf87355e643

CoreFx
- Debug & Release 
- Commit: 79a924855514877f5b8e8379e553e8b98293a30f

**Comment by jkotas** [comment]
On ARM, misaligned floats and doubles has to be read as int/long and then converted to float/double.

cc @tmat

**Comment by jkotas** [comment]
Example https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/BitConverter.cs#L137

**Comment by YongseopKim** [comment]
Hello, @jkotas @tmat .
I'm doing PR (https://github.com/dotnet/corefx/pull/10638) about modifying two tests - LoadConstantR4, LoadConstantR8 in InstructionEncoderTests.cs .
Could you review the PR?
