### ISSUE TITLE
TimeZoneInfoTests.IsDaylightSavingTime test failures

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#10671]
```
Discovering: System.Runtime.Tests
Discovered:  System.Runtime.Tests
Starting:    System.Runtime.Tests
   System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: "1940-02-25T00:00:00.0000000Z", expectedDST: True, expectedOffsetString: "1:00:00") [FAIL]
      Test with the zone Morocco Standard Time and date 25/02/1940 00:00:00 failed
      Expected: True
      Actual:   False
      Stack Trace:
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1972,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1714,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
   System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: "1940-11-20T00:00:00.0000000Z", expectedDST: True, expectedOffsetString: "1:00:00") [FAIL]
      Test with the zone Morocco Standard Time and date 20/11/1940 00:00:00 failed
      Expected: True
      Actual:   False
      Stack Trace:
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1972,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1714,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
   System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: "1940-12-31T23:59:59.0000000Z", expectedDST: True, expectedOffsetString: "1:00:00") [FAIL]
      Test with the zone Morocco Standard Time and date 31/12/1940 23:59:59 failed
      Expected: True
      Actual:   False
      Stack Trace:
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1972,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1714,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
   System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: "1941-01-01T00:00:00.0000000Z", expectedDST: True, expectedOffsetString: "1:00:00") [FAIL]
      Test with the zone Morocco Standard Time and date 01/01/1941 00:00:00 failed
      Expected: True
      Actual:   False
      Stack Trace:
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1972,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1714,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
   System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: "1945-02-24T12:00:00.0000000Z", expectedDST: True, expectedOffsetString: "1:00:00") [FAIL]
      Test with the zone Morocco Standard Time and date 24/02/1945 12:00:00 failed
      Expected: True
      Actual:   False
      Stack Trace:
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1972,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1714,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
   System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: "1945-11-17T01:00:00.0000000Z", expectedDST: True, expectedOffsetString: "1:00:00") [FAIL]
      Test with the zone Morocco Standard Time and date 17/11/1945 01:00:00 failed
      Expected: True
      Actual:   False
      Stack Trace:
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1972,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1714,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
   System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: "1945-11-17T22:59:59.0000000Z", expectedDST: True, expectedOffsetString: "1:00:00") [FAIL]
      Test with the zone Morocco Standard Time and date 17/11/1945 22:59:59 failed
      Expected: True
      Actual:   False
      Stack Trace:
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1972,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1714,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
   System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CatamarcaMultiYearDaylightSavings [FAIL]
      Test with the zone Argentina Standard Time and date 01/10/1946 04:00:00 failed
      Expected: True
      Actual:   False
      Stack Trace:
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1972,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1684,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CatamarcaMultiYearDaylightSavings()
   System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_LisbonDaylightSavingsWithNoOffsetChange(dateTimeString: "1995-09-30T17:00:00.0000000Z", expectedDST: False, expectedOffsetString: "1:00:00") [FAIL]
      Test with the zone GMT Standard Time and date 30/09/1995 17:00:00 failed
      Expected: True
      Actual:   False
      Stack Trace:
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1972,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1738,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_LisbonDaylightSavingsWithNoOffsetChange(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
   System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_LisbonDaylightSavingsWithNoOffsetChange(dateTimeString: "1996-03-31T00:59:59.0000000Z", expectedDST: False, expectedOffsetString: "1:00:00") [FAIL]
      Assert.Equal() Failure
      Expected: 01:00:00
      Actual:   00:00:00
      Stack Trace:
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1741,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_LisbonDaylightSavingsWithNoOffsetChange(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
   System.Tests.TimeZoneInfoTests.DaylightTransitionsExactTime_Johannesburg [FAIL]
      Assert.Equal() Failure
      Expected: 03:00:00
      Actual:   02:00:00
      Stack Trace:
         I:\Work\GitHub\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1843,0): at System.Tests.TimeZoneInfoTests.DaylightTransitionsExactTime_Johannesburg()
```
Windows 10 x64 1607 (OS Build 14393.10) - Locale UK BST

**Comment by hughbe** [comment]
How are you running these tests? I see from the test file that they are PlatformSpecific to AnyUnix

**Comment by benaadams** [comment]
\corefx\bin\tests\AnyOS.AnyCPU.Debug\System.Runtime.Tests\netcoreapp1.0>`CoreRun.exe xunit.console.netcore.exe System.Runtime.Tests.dll`

Running them to test the Enum test coverage

**Comment by hughbe** [comment]
Add this to your xunit.console.netcore.exe arguments: ` -notrait category=nonwindowstests`
