### ISSUE TITLE
Unhandled Exception while running unittest 'System.Diagnostics.Process.Tests'

### ISSUE THREAD

**Issue by parjong** [dotnet/corefx#10809]
In ARM/Linux, ``System.Diagnostics.Process.Tests`` crashes with the following message:
```
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.
Discovering: System.Diagnostics.Process.Tests
Discovered:  System.Diagnostics.Process.Tests
Starting:    System.Diagnostics.Process.Tests
   System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncHalfCharacterAtATime [STARTING]
Unhandled Exception:    System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncHalfCharacterAtATime [FAIL]
      Assert+WrapperXunitException : File path: /home/parjong/projects/toolchains/corefx/src/System.Diagnostics.Process/tests/ProcessStreamReadTests.cs. Line: 158
      ---- Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
Assert+WrapperXunitException: File path: /home/parjong/projects/toolchains/corefx/src/System.Diagnostics.Process/tests/ProcessStreamReadTests.cs. Line: 148 ---> Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: (null)
Actual:   a
   at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences)
   at Assert.Equal(String expected, String actual, String path, Int32 line) in /home/parjong/projects/toolchains/corefx/src/Common/tests/System/Diagnostics/AssertWithCallerAttributes.cs:line 143
   --- End of inner exception stack trace ---
   at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber) in /home/parjong/projects/toolchains/corefx/src/Common/tests/System/Diagnostics/AssertWithCallerAttributes.cs:line 583
   at Assert.Equal(String expected, String actual, String path, Int32 line) in /home/parjong/projects/toolchains/corefx/src/Common/tests/System/Diagnostics/AssertWithCallerAttributes.cs:line 144
   at System.Diagnostics.Tests.ProcessStreamReadTests.<>c__DisplayClass7_0.<TestAsyncHalfCharacterAtATime>b__1(Object s, DataReceivedEventArgs e) in /home/parjong/projects/toolchains/corefx/src/System.Diagnostics.Process/tests/ProcessStreamReadTests.cs:line 148
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
  --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__17_0(Object edi)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

It seems that CoreCLR has some issue in ARM/Linux, but it is still strange that unittest crashes instead of reporting failure.

**Comment by parjong** [comment]
While analyzing this issuse, I found that the following code shows the same behavior even in ubuntu 14.04 (x86_64):
```
    [Fact]
    public void TestAsyncHalfCharacterAtATime()
    {
      bool receivedOutput = false;

      Process p = CreateProcess(() =>
      {
        var stdout = Console.OpenStandardOutput();
        var bytes = new byte[] { 97, 0 }; //Encoding.Unicode.GetBytes("a");

        for (int i = 0; i != bytes.Length; ++i)
        {
          stdout.WriteByte(bytes[i]);
          stdout.Flush();
          Thread.Sleep(100);
        }

        return SuccessExitCode;
     });

     p.StartInfo.RedirectStandardOutput = true;
     p.StartInfo.StandardOutputEncoding = Encoding.Unicode;
     p.OutputDataReceived += (s, e) =>
     {
         Thread.Sleep(100);
         if (!receivedOutput)
         {
           throw new System.ArgumentException();
         }
     };

     p.Start();
     p.BeginOutputReadLine();
     p.WaitForExit(WaitInMS);
     p.WaitForExit(WaitInMS);
     p.WaitForExit(); // This ensures async event handlers are finished processing.
     Assert.True(receivedOutput);
    }
```

It seems that any exception in OuputDataReceived event handler will break the whole unittest.
