### ISSUE TITLE
Three JSON serialization tests failing on Linux

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#10852]
```
DataContractJsonSerializerTests.DCJS_ArrayOfDateTime [FAIL]
        strings differ at index 12
                             ↓
        [expected]:\/Date(946811045000-0800)\/","
        [actual  ]:\/Date(946782245000+0000)\/","
                             ↑
        [Expected (with length=62)]:
        ["\/Date(946811045000-0800)\/","\/Date(1296734706000-0800)\/"]
        [Actual (with length=62)]:
        ["\/Date(946782245000+0000)\/","\/Date(1296705906000+0000)\/"]
        Test failed for input: System.DateTime[]
        Expected: ["\/Date(946811045000-0800)\/","\/Date(1296734706000-0800)\/"]
        Actual: ["\/Date(946782245000+0000)\/","\/Date(1296705906000+0000)\/"]
        Expected: True
        Actual:   False
        Stack Trace:
              at DataContractJsonSerializerTests.SerializeAndDeserialize[T](T value, String baseline, DataContractJsonSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare)
              at DataContractJsonSerializerTests.DCJS_ArrayOfDateTime()
     DataContractJsonSerializerTests.DCJS_TypeWithAllPrimitiveProperties [FAIL]
        strings differ at index 69
                             ↓
        [expected]:Date(1467994211000-0700)\/","D
        [actual  ]:Date(1467969011000+0000)\/","D
                             ↑
        [Expected (with length=262)]:
        {"BooleanMember":true,"CharMember":"C","DateTimeMember":"\/Date(1467994211000-0700)\/","DecimalMember":-14554481076115341312123,"DoubleMember":123.456,"FloatMember":456.789,"GuidMember":"2054fd3e-e118-476a-9962-1a882be51860","IntMember":123,"StringMember":"abc"}
        [Actual (with length=262)]:
        {"BooleanMember":true,"CharMember":"C","DateTimeMember":"\/Date(1467969011000+0000)\/","DecimalMember":-14554481076115341312123,"DoubleMember":123.456,"FloatMember":456.789,"GuidMember":"2054fd3e-e118-476a-9962-1a882be51860","IntMember":123,"StringMember":"abc"}
        Test failed for input: SerializationTypes.TypeWithAllPrimitiveProperties
        Expected: {"BooleanMember":true,"CharMember":"C","DateTimeMember":"\/Date(1467994211000-0700)\/","DecimalMember":-14554481076115341312123,"DoubleMember":123.456,"FloatMember":456.789,"GuidMember":"2054fd3e-e118-476a-9962-1a882be51860","IntMember":123,"StringMember":"abc"}
        Actual: {"BooleanMember":true,"CharMember":"C","DateTimeMember":"\/Date(1467969011000+0000)\/","DecimalMember":-14554481076115341312123,"DoubleMember":123.456,"FloatMember":456.789,"GuidMember":"2054fd3e-e118-476a-9962-1a882be51860","IntMember":123,"StringMember":"abc"}
        Expected: True
        Actual:   False
        Stack Trace:
              at DataContractJsonSerializerTests.SerializeAndDeserialize[T](T value, String baseline, DataContractJsonSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare)
              at DataContractJsonSerializerTests.DCJS_TypeWithAllPrimitiveProperties()

     DataContractSerializerTests.DCS_ArrayOfDateTime [FAIL]
        XML comparison is also failing
        Test failed for input: System.DateTime[]
        Expected: <ArrayOfdateTime xmlns="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><dateTime>2000-01-02T03:04:05-08:00</dateTime><dateTime>2011-02-03T04:05:06-08:00</dateTime></ArrayOfdateTime>
        Actual: <ArrayOfdateTime xmlns="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><dateTime>2000-01-02T03:04:05Z</dateTime><dateTime>2011-02-03T04:05:06Z</dateTime></ArrayOfdateTime>
        Expected: True
        Actual:   False
        Stack Trace:
              at DataContractSerializerTests.SerializeAndDeserialize[T](T value, String baseline, DataContractSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare)
              at DataContractSerializerTests.DCS_ArrayOfDateTime()
```

**Comment by shmao** [comment]
The root cause of the issue is that the expected payloads contain hard-coded DateTime time zone info. The CI machines were in a different time zone so the tests failed. I will fix the test cases.
