### ISSUE TITLE
Exception message for AmbiguousMatchException should include the name

### ISSUE THREAD

**Issue by bradwilson** [dotnet/corefx#11048]
Fundamentally, this is an indication of a bad argument, without telling you what the bad value is, which usually demands that you fire up the debugger to figure it out. It would be helpful to know what the ambiguous name actually was.

```
System.Reflection.AmbiguousMatchException : Ambiguous match found.
Stack Trace:
    at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
    at System.Type.GetMethod(String name)
```

**Comment by terrajobst** [comment]
That makes sense to me.

@weshaggard @jkotas, any thoughts on this?

**Comment by jkotas** [comment]
> indication of a bad argument, without telling you what the bad value is

This is true for majority of the exception messages. It is pretty rare for exception messages to include the bad argument value ... you have to pretty much always fire up the debugger if you need it (or get it in some other way).

If there is something particular about this one to make it really worth it to include the bad argument value, I do not see a problem with it. But we need to think about where reasonable balance is - I do not think we want to be adding the bad argument values to exception messages everywhere.

**Comment by bradwilson** [comment]
> I do not think we want to be adding the bad argument values to exception messages everywhere.

Not to be simplistic, but: why not?

Allow me to draw the equivalent to a unit testing framework (since that's something [I know a little bit about](https://github.com/xunit)): You're argument would be the equivalent of saying "You don't need to add expected and actual values into your unit test messages, because they could find that out in a debugger". While that's true, it also diminishes the value, and at what cost?

**Comment by jkotas** [comment]
> Allow me to draw the equivalent to a unit testing framework

The difference is in cost/benefit. Adding actual/expected values in unit test messages can be done in central place. It is worth it to add a few more lines in central place for this.

Adding bad argument values to exception messages everywhere would change like 10000's places just for corefx, bloat the code quite a bit. I do not think it is worth it.

**Comment by svick** [comment]
A similar change to `ArgumentException` thrown from `Dictionary<K, V>.Add()` was proposed in https://github.com/dotnet/corefx/issues/1187 and merged in https://github.com/dotnet/coreclr/pull/1452. Is this any different?

Personally, I think clearer exceptions messages are worth some code bloat.

**Comment by justinvp** [comment]
It doesn't look like `AmbiguousMatchException` is created in too many places:
 - [CoreCLR](https://github.com/dotnet/coreclr/search?q=%22new+AmbiguousMatchException%22+-path%3Atests&type=Code)
 - [CoreRT](https://github.com/dotnet/corert/search?q=%22new+AmbiguousMatchException%22&type=Code)
 - [CoreFX](https://github.com/dotnet/corefx/search?q=%22new+AmbiguousMatchException%22&type=Code)

**Comment by MichalStrehovsky** [comment]
`GetMethodImpl` is just one of the places where the exception gets thrown. In order to get a consistent behavior, you would also need to pipe it through to `Binder` because that's what `GetMethodImpl` [calls](https://github.com/dotnet/coreclr/blob/00c85b302a078d5d13cfe9ff8cb453cd8296d6aa/src/mscorlib/src/System/RtType.cs#L3015). But `Binder.SelectMethod` is not name based. So now you need to also do breaking API changes to the binder, or have a `GetMethodImpl` that only sometimes gives you the name in the exception message...

**Comment by karelz** [comment]
Next steps: Find the places which throw it - try to implement it consistently.
Complexity: Medium
