### ISSUE TITLE
BaseAddress is a negative value in System.Diagnostics.Tests

### ISSUE THREAD

**Issue by jyoungyun** [dotnet/corefx#11085]
This issue is related to `System.Diagnostics.Tests.ProcessModuleTests.TestModuleProperties` TC.

Test details:
```
   System.Diagnostics.Tests.ProcessModuleTests.TestModuleProperties [STARTING]
   System.Diagnostics.Tests.ProcessModuleTests.TestModuleProperties [FAIL]
      Assert+WrapperXunitException : File path: /home/jyoung/git/dotnet/corefx_upstream/src/System.Diagnostics.Process/tests/ProcessModuleTests.cs. Line: 25
      ---- Assert.InRange() Failure
      Range:  (0 - 9223372036854775807)
      Actual: -1403310080
      Stack Trace:
            at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
            at Assert.InRange[T](T actual, T low, T high, String path, Int32 line)
            at System.Diagnostics.Tests.ProcessModuleTests.TestModuleProperties()
         ----- Inner Stack Trace -----
            at Assert.InRange[T](T actual, T low, T high, String path, Int32 line)
```

In 32bit machine, the address can be a negative value. I mean the address can use the signed bit too.
But IntPtr currently is interpreted in negative value in IntPtr::ToInt64() function.

Here is the related code:
```
in tests/ProcessModuleTests.cs
Assert.InRange(module.BaseAddress.ToInt64(), 0, long.MaxValue);

in src/System/Diagnostics/ProcessModule.cs
        public IntPtr BaseAddress                                               
        {                                                                       
            get                                                                 
            {                                                                   
                return _moduleInfo._baseOfDll;                                  
            }                                                                   
        }  

in src/System/Diagnostics/ModuleInfo.cs
    internal sealed class ModuleInfo                                            
    {                                                                           
#pragma warning disable 0649 // unused fields on some platforms                 
        internal string _baseName;                                              
        internal string _fileName;                                              
        internal IntPtr _baseOfDll;                                             
        internal IntPtr _entryPoint;                                            
        internal int _sizeOfImage;                                              
#pragma warning restore 0649                                                    
    }
```
CoreCLR IntPtr.cs
```
    public struct IntPtr : ISerializable                                        
    { 
        unsafe private void* m_value;
        ...
        public unsafe long ToInt64() {                                          
#if BIT64                                                                       
                return (long)m_value;                                           
#else // !BIT64 (32)                                                            
                return (long)(int)m_value;                                      
#endif                                                                          
        }  
        ...
}
```

In this case, ToInt64() function always returns a signed value because it casts `int` type.
If the `BaseAddress` means the memory address, it should be a UIntPtr instead of IntPtr, I think.
Can I change BaseAddress type to UIntPtr?

I think it can't because UIntPtr is not a CLS-compliant and besides changing IntPtr to UIntPtr makes incompatibility issues of ProcessModules behavior.

@jkotas suggests to change the check range like below.
(related issue https://github.com/dotnet/coreclr/issues/6854)
```
 Assert.InRange(module.BaseAddress.ToInt64(), long.MinValue, long.MaxValue); 
```

I will update the PR soon. But if there is better idea to fix it, please share me.
Thanks.

**Comment by jkotas** [comment]
> Can I change BaseAddress type to UIntPtr?

This would be a breaking change. It is not possible to make change like this in a shipped type.

**Comment by stephentoub** [comment]
> @jkotas suggests to change the check range like below.

Yes, that's the right fix.
