### ISSUE TITLE
NetworkInterface.GetAllNetworkInterfaces() on Ubuntu 14.04 raises unhandled exception FileNotFoundException in the presence of network interface alias.

### ISSUE THREAD

**Issue by parjong** [dotnet/corefx#11217]
The following example raises an unhandled exception on ubuntu 14.04 if there is an alias on any network interface:
```
using System.Net.Sockets;

namespace Sample
{
    public class Runner
    {
      public static void Main()
      {
        try
        {
          System.Console.WriteLine("Before");
          System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces();
          System.Console.WriteLine("After");
        }
        catch (System.Exception ex)
        {
          System.Console.WriteLine("Caught");
          System.Console.WriteLine(ex);
        }
      }
    }
}
```

The crash can be reproduced via the following step:
```
$ sudo ifconfig lo:virtual 192.168.222.1
$ corerun workspace-host/Failing.System.Net.NetworkInformation.Functional.Tests.dll
Before

Unhandled Exception: System.IO.FileNotFoundException: Could not find file '/proc/sys/net/ipv4/conf/lo:virtual/forwarding'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.FileStream.InternalOpen(String path, Int32 bufferSize, Boolean useAsync)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetIsForwardingEnabled()
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
   at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
   at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__0(String name, IpAddressInfo* ipAddr, IpAddressInfo* maskAddr)
   at Interop.Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback ipv4Found, IPv6AddressDiscoveredCallback ipv6Found, LinkLayerAddressDiscoveredCallback linkLayerFound)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterfacePal.GetAllNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces()
   at Sample.Runner.Main()
Aborted (core dumped)
```

**Comment by parjong** [comment]
#9761 seems to be related with this issue (although it is not exactly same).

**Comment by mellinoe** [comment]
The high-level problem is that aliased interface names are considered distinct interfaces when returned from the [`SystemNative_EnumerateInterfaceAddresses`](https://github.com/dotnet/corefx/blob/master/src/Native/Unix/System.Native/pal_interfaceaddresses.cpp#L34) function in the shim. When enumerating with `getifaddrs`, each node in the list has an `ifa_name` field, which may actually be an aliased name, of which several may refer to the same actual network interface. This can be seen when multiple name values map to the same interface index (we call `if_nametoindex` in the first line of the loop).

I think the simple fix for this is to call `if_indextoname` on the returned index from `if_nametoindex` to get back the "canonical" interface name. Then, in the managed code, all of the addresses from aliased devices will map back to the original network interface. I've verified that this works on my machine, at the very least.

If anyone familiar with Linux network interface aliasing, does the above sound reasonable?

https://github.com/mellinoe/corefx/commit/440d840dc574f62e75469bc0858121b0af8fc17d
