### ISSUE TITLE
[Linux/ARM] System.Runtime.Tests fail

### ISSUE THREAD

**Issue by hseok-oh** [dotnet/corefx#11243]
Environment: Linux / ARM 32bit (hardfp)
CoreCLR: Release build
CoreFX: Release build

```
Discovering: System.Runtime.Tests
Discovered:  System.Runtime.Tests
Starting:    System.Runtime.Tests
   System.Tests.IntPtrTests.ImplicitCast [SKIP]
      Condition(s) not met: "Is64Bit"
   System.Tests.IntPtrTests.Ctor_Long [SKIP]
      Condition(s) not met: "Is64Bit"
   System.Tests.IntPtrTests.Ctor_Int [FAIL]
      Assert.Equal() Failure
                        ↓ (pos 8)
      Expected: ffffffffffffffff
      Actual:   ffffffff
                        ↑ (pos 8)
      Stack Trace:
            at System.Tests.IntPtrTests.VerifyPointer(IntPtr ptr, Int64 expected)
            at System.Tests.IntPtrTests.Ctor_Int()

```

test code 
```
        [Fact]
        public static void Ctor_Int()
        {
            int i = 42;
            VerifyPointer(new IntPtr(i), i);
            VerifyPointer((IntPtr)i, i);

            i = -1;
            VerifyPointer(new IntPtr(i), i);
            VerifyPointer((IntPtr)i, i);
        }

        private static void VerifyPointer(IntPtr ptr, long expected)
        {   
            Assert.Equal(expected, ptr.ToInt64());

            int expected32 = (int)expected;
            if (expected32 != expected)
            {   
                Assert.Throws<OverflowException>(() => ptr.ToInt32());
                return;
            }

            int i = ptr.ToInt32();
            Assert.Equal(expected32, ptr.ToInt32());

            Assert.Equal(expected.ToString(), ptr.ToString());
            Assert.Equal(expected.ToString("x"), ptr.ToString("x"));

            Assert.Equal(ptr, new IntPtr(expected));
            Assert.True(ptr == new IntPtr(expected));
            Assert.False(ptr != new IntPtr(expected));

            Assert.NotEqual(ptr, new IntPtr(expected + 1));
            Assert.False(ptr == new IntPtr(expected + 1));
            Assert.True(ptr != new IntPtr(expected + 1));
        }

```

**Comment by hseok-oh** [comment]
This fail is related to `Assert.Equal(expected.ToString("x"), ptr.ToString("x"))`.
In 32bit ARM, it seems that IntPtr has 32bit value, the result of ToString("x") is `ffffffff`.
And the result of  `long type -1`'s ToString("x")  is `fffffffffffffffff`.
