### ISSUE TITLE
AV from coreclr in immutable collections tests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11260]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/3893/consoleText
```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
     at System.Collections.Immutable.ImmutableList`1.Enumerator.PushNext(Node node) in D:\j\workspace\windows_nt_re---37265eab\src\System.Collections.Immutable\src\System\Collections\Immutable\ImmutableList_1.cs:line 1784
     at System.Collections.Immutable.ImmutableList`1.Enumerator.MoveNext() in D:\j\workspace\windows_nt_re---37265eab\src\System.Collections.Immutable\src\System\Collections\Immutable\ImmutableList_1.cs:line 1660
     at System.Collections.Immutable.ImmutableExtensions.ToArray[T](IEnumerable`1 sequence, Int32 count) in D:\j\workspace\windows_nt_re---37265eab\src\System.Collections.Immutable\src\System\Collections\Immutable\ImmutableExtensions.cs:line 108
     at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items) in D:\j\workspace\windows_nt_re---37265eab\src\System.Collections.Immutable\src\System\Collections\Immutable\ImmutableArray.cs:line 139
     at System.Collections.Immutable.Tests.IndexOfTests.LastIndexOfTest[TCollection](Func`2 factory, Func`3 lastIndexOfItem, Func`4 lastIndexOfItemEQ, Func`4 lastIndexOfItemIndex, Func`5 lastIndexOfItemIndexCount, Func`6 lastIndexOfItemIndexCountEQ) in D:\j\workspace\windows_nt_re---37265eab\src\System.Collections.Immutable\tests\IndexOfTests.cs:line 120
     at System.Collections.Immutable.Tests.ImmutableArrayTest.LastIndexOf() in D:\j\workspace\windows_nt_re---37265eab\src\System.Collections.Immutable\tests\ImmutableArrayTest.cs:line 473
```
cc: @jkotas, @AArnott

**Comment by AArnott** [comment]
I presume this is due to a CLR bug and not anything wrong with the library?

**Comment by stephentoub** [comment]
That's my assumption as well.

**Comment by stephentoub** [comment]
Hmm, there was just a null reference exception here with a similar stack:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/3773/consoleText

**Comment by jkotas** [comment]
With debug coreclr build and GCStress set, I can pretty reliably hit following assert:

```
---------------------------
CoreRun.exe - Assert Failure (PID 30352, Thread 24276/0x5ed4)
---------------------------
returnKind == GetReturnKindFromMethodTable(pThread, codeInfo)

CORECLR! GetReturnKind + 0xD6 (0x00007ff9`bcd9be36)
CORECLR! GetHijackAddr + 0x1D (0x00007ff9`bcd9bd1d)
CORECLR! Thread::HandledJITCase + 0x3F2 (0x00007ff9`bcd9d222)
CORECLR! ThreadSuspend::SuspendRuntime + 0x600 (0x00007ff9`bcda6100)
CORECLR! ThreadSuspend::SuspendEE + 0x316 (0x00007ff9`bcda5786)
CORECLR! GCToEEInterface::SuspendEE + 0x3D (0x00007ff9`bd3be77d)
CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x3EA (0x00007ff9`bd53a45a)
CORECLR! WKS::gc_heap::try_allocate_more_space + 0x339 (0x00007ff9`bd5ac879)
CORECLR! WKS::gc_heap::allocate_more_space + 0x27 (0x00007ff9`bd54a147)
CORECLR! WKS::gc_heap::allocate + 0xEE (0x00007ff9`bd543d6e)

d:\coreclr\src\vm\threadsuspend.cpp, Line: 7299
```

**Comment by jkotas** [comment]
@swaroop-sridhar Could you please take a look? Looks related to your recent GCInfo changes.

**Comment by swaroop-sridhar** [comment]
@jkotas: I'll take a look now. Did you hit the assertion on OSX or Windows?

**Comment by stephentoub** [comment]
Another hit: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/3808/consoleText

**Comment by stephentoub** [comment]
Another: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/3815/

**Comment by stephentoub** [comment]
Another, this time on Linux:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/centos7.1_debug_prtest/579/consoleText

**Comment by swaroop-sridhar** [comment]
I know what the problem is. The GCInfo is wrong for structs containing a single GC-reference returned in a single register. I'm working on a fix.

**Comment by stephentoub** [comment]
Thanks, @swaroop-sridhar.  The sooner the better.  I've stopped commenting on this issue with examples, but this is taking out a bunch of our CI legs in PR.
