### ISSUE TITLE
[dev/api] Some new TimeZoneInfo tests are failing in non-Windows netcoreapp1.1 runs

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#11307]
cc: @hann013 @stephentoub @danmosemsft 

```
./corerun xunit.console.netcore.exe System.Runtime.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonosxtests
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Runtime.Tests
Discovered:  System.Runtime.Tests
Starting:    System.Runtime.Tests
   System.Tests.TimeZoneInfoTests.ConvertTime_DateTimeOffset_Invalid_TimeZoneNotFoundException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.TimeZoneNotFoundException)
      Actual:   typeof(System.Security.SecurityException): The time zone ID 'Pacific' was found on the local computer, but the application does not have permission to read the file.
      Stack Trace:
            at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
            at System.Tests.TimeZoneInfoTests.<>c__DisplayClass70_0`1.<VerifyConvertException>b__0()
   System.Tests.TimeZoneInfoTests.ClearCachedData [FAIL]
      System.TimeZoneNotFoundException : The time zone ID 'Central Standard Time' was not found on the local computer.
      ---- System.IO.FileNotFoundException : Could not find file '/usr/share/zoneinfo/Central Standard Time'.
      Stack Trace:
            at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
            at System.Tests.TimeZoneInfoTests.ClearCachedData()
         ----- Inner Stack Trace -----
            at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
            at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
            at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
            at System.TimeZoneInfo.TryGetTimeZoneByFile(String id, TimeZoneInfo& value, Exception& e)
Finished:    System.Runtime.Tests

=== TEST EXECUTION SUMMARY ===
   System.Runtime.Tests  Total: 6185, Errors: 0, Failed: 2, Skipped: 0, Time: 1.136s
Finished running tests. End time=17:19:51. Return value was 2
```

**Comment by stephentoub** [comment]
Fixed by #11346
