### ISSUE TITLE
[dev/api] System.IO.Tests.FileStream_WriteAsync.ManyConcurrentWriteAsyncs failing in netcoreapp1.1 non-Windows runs

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#11303]
cc: @stephentoub 
Test run output:
```
./corerun xunit.console.netcore.exe System.IO.FileSystem.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonosxtests
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.IO.FileSystem.Tests
Discovered:  System.IO.FileSystem.Tests
Starting:    System.IO.FileSystem.Tests
   System.IO.Tests.FileStream_ctor_str_fm_fa_fs_buffer_fo.ValidFileOptions [SKIP]
      Condition(s) not met: "IsNotWindowsNanoServer"
   System.IO.Tests.FileStream_WriteAsync.ManyConcurrentWriteAsyncs [FAIL]
      Assert.Equal() Failure
      Expected: 10240
      Actual:   8192
      Stack Trace:
            at System.IO.Tests.FileStream_WriteAsync.<ManyConcurrentWriteAsyncs>d__14.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Finished:    System.IO.FileSystem.Tests

=== TEST EXECUTION SUMMARY ===
   System.IO.FileSystem.Tests  Total: 2131, Errors: 0, Failed: 1, Skipped: 1, Time: 11.415s
Finished running tests. End time=17:11:08. Return value was 1
```

**Comment by stephentoub** [comment]
Fixed by #11375
