### ISSUE TITLE
[dev/api] New System.Security.Cryptography.Algorithms tests are failing in netcoreapp1.1 runs

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#11315]
cc: @steveharter 
Looks like some new tests that you added are broken in netcoreapp1.1. I'll comment them out for now, but this issue is to track the work of readding them back when fixed.
This are the errors that I'm seeing:
```
./corerun xunit.console.netcore.exe System.Security.Cryptography.Algorithms.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonosxtests
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Security.Cryptography.Algorithms.Tests
Discovered:  System.Security.Cryptography.Algorithms.Tests
Starting:    System.Security.Cryptography.Algorithms.Tests
   System.Security.Cryptography.Dsa.Tests.DSAImportExport.MultiExport [FAIL]
      System.EntryPointNotFoundException : Unable to find an entry point named 'CryptoNative_DsaKeyCreateByExplicitParameters' in DLL 'System.Security.Cryptography.Native'.
      Stack Trace:
            at Interop.Crypto.DsaKeyCreateByExplicitParameters(SafeDsaHandle& dsa, Byte[] p, Int32 pLength, Byte[] q, Int32 qLength, Byte[] g, Int32 gLength, Byte[] y, Int32 yLength, Byte[] x, Int32 xLength)
            at System.Security.Cryptography.DSAImplementation.DSAOpenSsl.ImportParameters(DSAParameters parameters)
            at System.Security.Cryptography.Dsa.Tests.DSAImportExport.MultiExport()
   System.Security.Cryptography.Dsa.Tests.DSAImportExport.ExportAutoKey [FAIL]
      System.EntryPointNotFoundException : Unable to find an entry point named 'CryptoNative_DsaGenerateKey' in DLL 'System.Security.Cryptography.Native'.
      Stack Trace:
            at Interop.Crypto.DsaGenerateKey(SafeDsaHandle& dsa, Int32 bits)
            at System.Security.Cryptography.DSAImplementation.DSAOpenSsl.GenerateKey()
            at System.Lazy`1.CreateValue()
            at System.Lazy`1.LazyInitValue()
            at System.Security.Cryptography.DSAImplementation.DSAOpenSsl.ExportParameters(Boolean includePrivateParameters)
            at System.Security.Cryptography.Dsa.Tests.DSAImportExport.ExportAutoKey()
   System.Security.Cryptography.Dsa.Tests.DSAKeyGeneration.GenerateKey_1024 [FAIL]
      System.EntryPointNotFoundException : Unable to find an entry point named 'CryptoNative_DsaGenerateKey' in DLL 'System.Security.Cryptography.Native'.
      Stack Trace:
            at Interop.Crypto.DsaGenerateKey(SafeDsaHandle& dsa, Int32 bits)
            at System.Security.Cryptography.DSAImplementation.DSAOpenSsl.GenerateKey()
            at System.Lazy`1.CreateValue()
            at System.Lazy`1.LazyInitValue()
            at System.Security.Cryptography.DSAImplementation.DSAOpenSsl.ExportParameters(Boolean includePrivateParameters)
            at System.Security.Cryptography.Dsa.Tests.DSAKeyGeneration.GenerateKey(Func`2 getSize)
            at System.Security.Cryptography.Dsa.Tests.DSAKeyGeneration.GenerateKey(Int32 size)
            at System.Security.Cryptography.Dsa.Tests.DSAKeyGeneration.GenerateKey_1024()
   System.Security.Cryptography.Dsa.Tests.DSAKeyGeneration.GenerateSecondMinKey [FAIL]
      System.EntryPointNotFoundException : Unable to find an entry point named 'CryptoNative_DsaGenerateKey' in DLL 'System.Security.Cryptography.Native'.
      Stack Trace:
            at Interop.Crypto.DsaGenerateKey(SafeDsaHandle& dsa, Int32 bits)
            at System.Security.Cryptography.DSAImplementation.DSAOpenSsl.GenerateKey()
            at System.Lazy`1.CreateValue()
            at System.Lazy`1.LazyInitValue()
            at System.Security.Cryptography.DSAImplementation.DSAOpenSsl.ExportParameters(Boolean includePrivateParameters)
            at System.Security.Cryptography.Dsa.Tests.DSAKeyGeneration.GenerateKey(Func`2 getSize)
            at System.Security.Cryptography.Dsa.Tests.DSAKeyGeneration.GenerateSecondMinKey()
   System.Security.Cryptography.Dsa.Tests.DSAKeyGeneration.GenerateMinKey [FAIL]
      System.EntryPointNotFoundException : Unable to find an entry point named 'CryptoNative_DsaGenerateKey' in DLL 'System.Security.Cryptography.Native'.
      Stack Trace:
            at Interop.Crypto.DsaGenerateKey(SafeDsaHandle& dsa, Int32 bits)
            at System.Security.Cryptography.DSAImplementation.DSAOpenSsl.GenerateKey()
            at System.Lazy`1.CreateValue()
            at System.Lazy`1.LazyInitValue()
            at System.Security.Cryptography.DSAImplementation.DSAOpenSsl.ExportParameters(Boolean includePrivateParameters)
            at System.Security.Cryptography.Dsa.Tests.DSAKeyGeneration.GenerateKey(Func`2 getSize)
            at System.Security.Cryptography.Dsa.Tests.DSAKeyGeneration.GenerateMinKey()
   System.Security.Cryptography.Dsa.Tests.DSASignVerify.SignAndVerifyDataNew1024 [FAIL]
      System.EntryPointNotFoundException : Unable to find an entry point named 'CryptoNative_DsaGenerateKey' in DLL 'System.Security.Cryptography.Native'.
      Stack Trace:
            at Interop.Crypto.DsaGenerateKey(SafeDsaHandle& dsa, Int32 bits)
            at System.Security.Cryptography.DSAImplementation.DSAOpenSsl.GenerateKey()
            at System.Lazy`1.CreateValue()
            at System.Lazy`1.LazyInitValue()
            at System.Security.Cryptography.DSAImplementation.DSAOpenSsl.CreateSignature(Byte[] hash)
            at System.Security.Cryptography.DSA.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm)
            at System.Security.Cryptography.DSA.SignData(Byte[] data, HashAlgorithmName hashAlgorithm)
            at System.Security.Cryptography.Dsa.Tests.DSASignVerify.SignAndVerifyDataNew1024()
   System.Security.Cryptography.Dsa.Tests.DSASignVerify.InvalidKeySize_DoesNotInvalidateKey [FAIL]
      System.EntryPointNotFoundException : Unable to find an entry point named 'CryptoNative_DsaGenerateKey' in DLL 'System.Security.Cryptography.Native'.
      Stack Trace:
            at Interop.Crypto.DsaGenerateKey(SafeDsaHandle& dsa, Int32 bits)
            at System.Security.Cryptography.DSAImplementation.DSAOpenSsl.GenerateKey()
            at System.Lazy`1.CreateValue()
            at System.Lazy`1.LazyInitValue()
            at System.Security.Cryptography.DSAImplementation.DSAOpenSsl.CreateSignature(Byte[] hash)
            at System.Security.Cryptography.DSA.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm)
            at System.Security.Cryptography.DSA.SignData(Byte[] data, HashAlgorithmName hashAlgorithm)
            at System.Security.Cryptography.Dsa.Tests.DSASignVerify.InvalidKeySize_DoesNotInvalidateKey()
   System.Security.Cryptography.Dsa.Tests.DSASignVerify.VerifyKnownSignature [FAIL]
      System.EntryPointNotFoundException : Unable to find an entry point named 'CryptoNative_DsaKeyCreateByExplicitParameters' in DLL 'System.Security.Cryptography.Native'.
      Stack Trace:
            at Interop.Crypto.DsaKeyCreateByExplicitParameters(SafeDsaHandle& dsa, Byte[] p, Int32 pLength, Byte[] q, Int32 qLength, Byte[] g, Int32 gLength, Byte[] y, Int32 yLength, Byte[] x, Int32 xLength)
            at System.Security.Cryptography.DSAImplementation.DSAOpenSsl.ImportParameters(DSAParameters parameters)
            at System.Security.Cryptography.Dsa.Tests.DSASignVerify.VerifyKnownSignature()
   System.Security.Cryptography.Dsa.Tests.DSASignVerify.SignAndVerifyDataExplicit2048 [FAIL]
      System.EntryPointNotFoundException : Unable to find an entry point named 'CryptoNative_DsaKeyCreateByExplicitParameters' in DLL 'System.Security.Cryptography.Native'.
      Stack Trace:
            at Interop.Crypto.DsaKeyCreateByExplicitParameters(SafeDsaHandle& dsa, Byte[] p, Int32 pLength, Byte[] q, Int32 qLength, Byte[] g, Int32 gLength, Byte[] y, Int32 yLength, Byte[] x, Int32 xLength)
            at System.Security.Cryptography.DSAImplementation.DSAOpenSsl.ImportParameters(DSAParameters parameters)
            at System.Security.Cryptography.Dsa.Tests.DSASignVerify.SignAndVerify(Byte[] data, String hashAlgorithmName, DSAParameters dsaParameters)
            at System.Security.Cryptography.Dsa.Tests.DSASignVerify.SignAndVerifyDataExplicit2048()
   System.Security.Cryptography.Dsa.Tests.DSASignVerify.SignAndVerifyDataExplicit1024 [FAIL]
      System.EntryPointNotFoundException : Unable to find an entry point named 'CryptoNative_DsaKeyCreateByExplicitParameters' in DLL 'System.Security.Cryptography.Native'.
      Stack Trace:
            at Interop.Crypto.DsaKeyCreateByExplicitParameters(SafeDsaHandle& dsa, Byte[] p, Int32 pLength, Byte[] q, Int32 qLength, Byte[] g, Int32 gLength, Byte[] y, Int32 yLength, Byte[] x, Int32 xLength)
            at System.Security.Cryptography.DSAImplementation.DSAOpenSsl.ImportParameters(DSAParameters parameters)
            at System.Security.Cryptography.Dsa.Tests.DSASignVerify.SignAndVerify(Byte[] data, String hashAlgorithmName, DSAParameters dsaParameters)
            at System.Security.Cryptography.Dsa.Tests.DSASignVerify.SignAndVerifyDataExplicit1024()
Finished:    System.Security.Cryptography.Algorithms.Tests

=== TEST EXECUTION SUMMARY ===
   System.Security.Cryptography.Algorithms.Tests  Total: 395, Errors: 0, Failed: 10, Skipped: 0, Time: 1.138s
Finished running tests. End time=16:43:47. Return value was 10
```

**Comment by steveharter** [comment]
@joperezr I no longer see these commented out tests in master; I assume those changes weren't ported from dev\api->master?

**Comment by joperezr** [comment]
I don't think they are commented out either... not sure what happened here.

**Comment by steveharter** [comment]
Closing this; no tests are (were?) commented out
