### ISSUE TITLE
Test failure in Microsoft.Framework.WebEncoders.TextEncoderSettingsTests.Clear

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#11335]
PR https://github.com/dotnet/corefx/pull/11329 failed with the following stack trace:
```
20:27:25      Microsoft.Framework.WebEncoders.TextEncoderSettingsTests.Clear [FAIL]
20:27:25         System.IndexOutOfRangeException : Index was outside the bounds of the array.
20:27:25         Stack Trace:
20:27:25               at System.Text.Internal.AllowedCharactersBitmap.IsCharacterAllowed(Char character)
20:27:25               at Microsoft.Framework.WebEncoders.TextEncoderSettingsExtensions.IsCharacterAllowed(TextEncoderSettings settings, Char character)
20:27:25               at Microsoft.Framework.WebEncoders.TextEncoderSettingsTests.Clear()
```
See http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/3793.

**Comment by stephentoub** [comment]
Another case:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/3846/consoleText

**Comment by KrzysztofCwalina** [comment]
this turned out to be not specific to encoders.
