### ISSUE TITLE
Some Globalization Tests failing on Unix based platforms

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#11381]
```
./corerun xunit.console.netcore.exe System.Globalization.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.0tests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
10:41:53   xUnit.net console test runner (64-bit .NET Core)
10:41:53   Copyright (C) 2014 Outercurve Foundation.
10:41:53   
10:41:53   Discovering: System.Globalization.Tests
10:41:54   Discovered:  System.Globalization.Tests
10:41:54   Starting:    System.Globalization.Tests
10:41:55   RemoteExecutorConsoleApp -> /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/bin/Unix.AnyCPU.Debug/RemoteExecutorConsoleApp/RemoteExecutorConsoleApp.exe
10:41:56   System.Globalization.Performance.Tests -> /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/bin/AnyOS.AnyCPU.Debug/System.Globalization.Performance.Tests/System.Globalization.Performance.Tests.dll
10:41:56   Exception from RemoteExecutorConsoleApp(System.Globalization.Tests, Version=4.0.12.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb, System.Globalization.Tests.CurrentCultureTests+<>c, <CurrentUICulture>b__2_0):
10:41:56   Assembly: System.Globalization.Tests, Version=4.0.12.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
10:41:56   Type: System.Globalization.Tests.CurrentCultureTests+<>c
10:41:56   Method: Int32 <CurrentUICulture>b__2_0()
10:41:56   Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.EqualException: Assert.Equal() Failure
10:41:56                  ↓ (pos 5)
10:41:56   Expected: de-DE_phoneb
10:41:56   Actual:   de-DE@collation=phoneb
10:41:56                  ↑ (pos 5)
10:41:56      at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences)
10:41:56      at System.Globalization.Tests.CurrentCultureTests.<>c.<CurrentUICulture>b__2_0()
10:41:56      --- End of inner exception stack trace ---
10:41:56      at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
10:41:56      at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
10:41:56      at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
10:41:56      at RemoteExecutorConsoleApp.Program.Main(String[] args)
10:41:56      System.Globalization.Tests.CurrentCultureTests.CurrentUICulture [FAIL]
10:41:56         Assert.Equal() Failure
10:41:56         Expected: 42
10:41:56         Actual:   254
10:41:56         Stack Trace:
10:41:57   Using /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/packages/ as folder for resolving package dependencies.
10:41:57   Executing in /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/bin/tests/AnyOS.AnyCPU.Debug/System.Globalization.Performance.Tests/netcoreapp1.0
10:41:57   Hard linking dependent files...
10:41:57   Exception from RemoteExecutorConsoleApp(System.Globalization.Tests, Version=4.0.12.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb, System.Globalization.Tests.CurrentCultureTests+<>c, <CurrentCulture>b__0_0):
10:41:57   Assembly: System.Globalization.Tests, Version=4.0.12.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
10:41:57   Type: System.Globalization.Tests.CurrentCultureTests+<>c
10:41:57   Method: Int32 <CurrentCulture>b__0_0()
10:41:57   Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.EqualException: Assert.Equal() Failure
10:41:57                  ↓ (pos 5)
10:41:57   Expected: de-DE_phoneb
10:41:57   Actual:   de-DE@collation=phoneb
10:41:57                  ↑ (pos 5)
10:41:57      at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences)
10:41:57      at System.Globalization.Tests.CurrentCultureTests.<>c.<CurrentCulture>b__0_0()
10:41:57      --- End of inner exception stack trace ---
10:41:57      at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
10:41:57      at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
10:41:57      at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
10:41:57      at RemoteExecutorConsoleApp.Program.Main(String[] args)
10:41:57               at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
10:41:57               at System.Globalization.Tests.CurrentCultureTests.CurrentUICulture()
10:41:57      System.Globalization.Tests.CurrentCultureTests.CurrentCulture [FAIL]
10:41:57         Assert.Equal() Failure
10:41:57         Expected: 42
10:41:57         Actual:   254
10:41:57         Stack Trace:
10:41:57               at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
10:41:57               at System.Globalization.Tests.CurrentCultureTests.CurrentCulture()
10:41:57   Finished linking needed files, moving to running tests.
10:41:57   Running tests... Start time: 17:42:41
10:41:57   Commands:
10:41:57   ./corerun xunit.console.netcore.exe System.Globalization.Performance.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.0tests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
10:41:57   xUnit.net console test runner (64-bit .NET Core)
10:41:57   Copyright (C) 2014 Outercurve Foundation.
10:41:57   
```
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_debug_prtest/1989/consoleFull#-43753631679fe3b83-f408-404c-b9e7-9207d232e5fc

**Comment by tarekgh** [comment]
https://github.com/dotnet/corefx/pull/11382

**Comment by tarekgh** [comment]
although this is a regression, I moved the issue to 1.2 as the regression scope is really small and not real breaking. it just return mangled names for CompareInfo only with the cultures having alternative sort (like de-DE_phoneb)
