### ISSUE TITLE
TestKeyAgreeKeyEncryptionAlgorithm_RoundTrip failure in CI on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11583]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/26/
```
System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.KeyAgreeRecipientInfoTests.TestKeyAgreeKeyEncryptionAlgorithm_RoundTrip [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : An internal error occurred
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Security.Cryptography.Pkcs\src\Internal\Cryptography\Pal\Windows\PkcsPalWindows.Encrypt.cs(78,0): at Internal.Cryptography.Pal.Windows.PkcsPalWindows.EncodeHelpers.CreateCryptMsgHandleToEncode(CmsRecipientCollection recipients, Oid innerContentType, AlgorithmIdentifier contentEncryptionAlgorithm, X509Certificate2Collection originatorCerts, CryptographicAttributeObjectCollection unprotectedAttributes)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Security.Cryptography.Pkcs\src\Internal\Cryptography\Pal\Windows\PkcsPalWindows.Encrypt.cs(25,0): at Internal.Cryptography.Pal.Windows.PkcsPalWindows.Encrypt(CmsRecipientCollection recipients, ContentInfo contentInfo, AlgorithmIdentifier contentEncryptionAlgorithm, X509Certificate2Collection originatorCerts, CryptographicAttributeObjectCollection unprotectedAttributes)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Security.Cryptography.Pkcs\src\System\Security\Cryptography\Pkcs\EnvelopedCms.cs(107,0): at System.Security.Cryptography.Pkcs.EnvelopedCms.Encrypt(CmsRecipientCollection recipients)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Security.Cryptography.Pkcs\tests\EnvelopedCms\KeyAgreeRecipientInfoTests.cs(290,0): at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.KeyAgreeRecipientInfoTests.EncodeKeyAgreel(SubjectIdentifierType type)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Security.Cryptography.Pkcs\tests\EnvelopedCms\KeyAgreeRecipientInfoTests.cs(134,0): at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.KeyAgreeRecipientInfoTests.TestKeyAgreeKeyEncryptionAlgorithm_RoundTrip()
```

**Comment by bartonjs** [comment]
Since this seems to have been a one-off error and it's replaying a CAPI error code; I'm going to go ahead and close this.
