### ISSUE TITLE
DirectoryLongerThanMaxLongPath_ThrowsPathTooLongException test is failing

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#11687]
cc: @JeremyKuhne 

After merging from dev/api in PR #11679 this test started failing. Here is the test run output:

```
 System.IO.Tests.DirectoryInfo_Create.DirectoryLongerThanMaxLongPath_ThrowsPathTooLongException [FAIL]
      Assert.All() Failure: 1 out of 2 items in the collection did not pass.
      [0]: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
           Expected: typeof(System.IO.PathTooLongException)
           Actual:   typeof(System.IO.DirectoryNotFoundException): Could not find a part of the path 'C:\Users\joperezr\AppData\Local\Temp\DirectoryInfo_Create_1bkmtugy.zy3\DirectoryLongerThanMaxLongPath_ThrowsPathTooLongException_254\23099ea0-f7ac-4547-9eb5-c3f9d7cf6855\9087[...]444b-b3df-e06db775e9db'.
              at System.IO.Win32FileSystem.CreateDirectory(String fullPath) in F:\git\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 154
              at System.IO.DirectoryInfo.Create() in F:\git\corefx\src\System.IO.FileSystem\src\System\IO\DirectoryInfo.cs:line 102
              at System.IO.Tests.DirectoryInfo_Create.Create(String path) in F:\git\corefx\src\System.IO.FileSystem\tests\DirectoryInfo\Create.cs:line 17
              at System.IO.Tests.Directory_CreateDirectory.<>c__DisplayClass20_0.<DirectoryLongerThanMaxLongPath_ThrowsPathTooLongException>b__1() in F:\git\corefx\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs:line 257
              at Xunit.Assert.RecordException(Func`1 testCode) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\Record.cs:line 45
      Stack Trace:
         F:\git\corefx\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs(255,0): at System.IO.Tests.Directory_CreateDirectory.DirectoryLongerThanMaxLongPath_ThrowsPathTooLongException()
Finished:    System.IO.FileSystem.Tests

=== TEST EXECUTION SUMMARY ===
   System.IO.FileSystem.Tests  Total: 2262, Errors: 0, Failed: 1, Skipped: 26, Time: 56.245s
Finished running tests.  End time=13:49:46.47, Exit code = 1
```

**Comment by joperezr** [comment]
@JeremyKuhne could you please check why is this test failing in both netcoreapp1.0 and 1.1 runs after the merge to master?

**Comment by ViktorHofer** [comment]
DirectoryLongerThanMaxLongPath_ThrowsPathTooLongException test (System.IO.FileSystem\tests\Directory\CreateDirectory.cs) is still annotated with Issue. Removing it an testing with both default TFM and net46 TFM succeeds.

Is there any reason why it is still marked as a failing test?

**Comment by stephentoub** [comment]
@ViktorHofer, if it's passing, great. Please feel free to submit a PR to remove the ActiveIssue; if it passes CI, we can merge it and close this issue.

**Comment by stephentoub** [comment]
Closed by #17343

**Comment by JeremyKuhne** [comment]
@ViktorHofer As per #17536, this issue is in the test algorithm that is generating the long paths.

**Comment by Jiayili1** [comment]
This issue is repro on UWP F5 Tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20170427.01/workItem/System.IO.FileSystem.Tests/analysis/xunit/System.IO.Tests.DirectoryInfo_Create~2FCDriveCase

Message :
System.IO.DirectoryNotFoundException : Could not find a part of the path 'c:\\'.

Stack Trace :
   at System.IO.Win32FileSystem.CreateDirectory(String fullPath)
   at System.IO.Tests.DirectoryInfo_Create.Create(String path)
   at System.IO.Tests.Directory_CreateDirectory.CDriveCase()

**Comment by danmosemsft** [comment]
@ViktorHofer I guess the System.IO.DirectoryNotFoundException : Could not find a part of the path 'c:\'. error immediately above should go into a new different issue

**Comment by ViktorHofer** [comment]
Good catch! I will create a new one for it. Seems also interesting 👍
