### ISSUE TITLE
SqlClient stress test TestSqlAsyncNonBlockingWrite

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#11683]
Environment: Windows Server 2012 R2, OSX
SqlClient: Managed SNI enabled.

While executing the test `TestSqlAsyncNonBlockingWrite` the following unexpected exception is detected in SqlClient.

```
Test: TestSqlAsyncNonBlockingWrite
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Diagn
ostics.Debug+DebugAssertException: _pendingCallbacks values is invalid after decrementing: -2

   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at System.Data.SqlClient.TdsParserStateObject.DecrementPendingCallbacks(Boolean release) in e:\work\gitclone\corefx\s
rc\System.Data.SqlClient\src\System\Data\SqlClient\TdsParserStateObject.cs:line 910
   at System.Data.SqlClient.TdsParserSessionPool.Dispose() in e:\work\gitclone\corefx\src\System.Data.SqlClient\src\Syst
em\Data\SqlClient\TdsParserSessionPool.cs:line 128
   at System.Data.SqlClient.TdsParser.Disconnect() in e:\work\gitclone\corefx\src\System.Data.SqlClient\src\System\Data\
SqlClient\TdsParser.cs:line 1012
   at System.Data.SqlClient.SqlInternalConnectionTds.Dispose() in e:\work\gitclone\corefx\src\System.Data.SqlClient\src\
System\Data\SqlClient\SqlInternalConnectionTds.cs:line 544
   at System.Data.ProviderBase.DbConnectionPool.DestroyObject(DbConnectionInternal obj) in e:\work\gitclone\corefx\src\S
ystem.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs:line 574
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObject
sTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& co
nnection) in e:\work\gitclone\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs:line 831

   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry
, DbConnectionOptions userOptions, DbConnectionInternal& connection) in e:\work\gitclone\corefx\src\System.Data.SqlClien
t\src\System\Data\ProviderBase\DbConnectionPool.cs:line 712
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`
1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection) in e:\wo
rk\gitclone\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionFactory.cs:line 281
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnection
Factory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in e:\work\gitclone\corefx\src
\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionInternal.cs:line 443
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory co
nnectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in e:\work\gitclone\corefx\src\System.Da
ta.SqlClient\src\System\Data\ProviderBase\DbConnectionClosed.cs:line 64
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry) in e:\work\gitclone\corefx\src\System.Da
ta.SqlClient\src\System\Data\SqlClient\SqlConnection.cs:line 992
   at System.Data.SqlClient.SqlConnection.Open() in e:\work\gitclone\corefx\src\System.Data.SqlClient\src\System\Data\Sq
lClient\SqlConnection.cs:line 577
   at Stress.Data.DataStressConnection.OpenSync() in e:\work\gitclone\corefx\src\System.Data.SqlClient\tests\StressTests
\System.Data.StressFramework\DataStressConnection.cs:line 87
   at Stress.Data.DataStressConnection.Open() in e:\work\gitclone\corefx\src\System.Data.SqlClient\tests\StressTests\Sys
tem.Data.StressFramework\DataStressConnection.cs:line 49
   at Stress.Data.DataStressFactory.GetRandomPK(Random rnd, TableMetadata table) in e:\work\gitclone\corefx\src\System.D
ata.SqlClient\tests\StressTests\System.Data.StressFramework\DataStressFactory.cs:line 333
   at Stress.Data.DataStressFactory.GetUpdateCommand(Random rnd, TableMetadata table, DataStressConnection conn) in e:\w
ork\gitclone\corefx\src\System.Data.SqlClient\tests\StressTests\System.Data.StressFramework\DataStressFactory.cs:line 41
6
   at Stress.Data.DataStressFactory.GetCommand(Random rnd, TableMetadata table, DataStressConnection conn, Boolean query
, Boolean isXml) in e:\work\gitclone\corefx\src\System.Data.SqlClient\tests\StressTests\System.Data.StressFramework\Data
StressFactory.cs:line 204
   at Stress.Data.SqlClient.SqlClientTestGroup.TestSqlAsync(Random rnd, Boolean read, Boolean poll, Boolean handle, Bool
ean xml) in e:\work\gitclone\corefx\src\System.Data.SqlClient\tests\StressTests\System.Data.SqlClient.Stress.Tests\SqlCl
ientTestGroup.cs:line 284
   at Stress.Data.SqlClient.SqlClientTestGroup.TestSqlAsyncNonBlockingWrite() in e:\work\gitclone\corefx\src\System.Data
.SqlClient\tests\StressTests\System.Data.SqlClient.Stress.Tests\SqlClientTestGroup.cs:line 347
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters
, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at DPStressHarness.TestBase.<CreateTestMethodDelegate>b__21_0(Object instance) in e:\work\gitclone\corefx\src\System.
Data.SqlClient\tests\StressTests\System.Data.StressRunner\TestBase.cs:line 138
   at DPStressHarness.StressTest.Run() in e:\work\gitclone\corefx\src\System.Data.SqlClient\tests\StressTests\System.Dat
a.StressRunner\StressTest.cs:line 116
   at DPStressHarness.StressEngine.RunStressThread() in e:\work\gitclone\corefx\src\System.Data.SqlClient\tests\StressTe
sts\System.Data.StressRunner\StressEngine.cs:line 172
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Diagnostics.Debug.WindowsDebugLogger.ShowAssertDialog(String stackTrace, String message, String detailMessa
ge)
   at System.Data.SqlClient.TdsParserStateObject.DecrementPendingCallbacks(Boolean release) in e:\work\gitclone\corefx\s
rc\System.Data.SqlClient\src\System\Data\SqlClient\TdsParserStateObject.cs:line 910
   at System.Data.SqlClient.TdsParserSessionPool.Dispose() in e:\work\gitclone\corefx\src\System.Data.SqlClient\src\Syst
em\Data\SqlClient\TdsParserSessionPool.cs:line 128
   at System.Data.SqlClient.TdsParser.Disconnect() in e:\work\gitclone\corefx\src\System.Data.SqlClient\src\System\Data\
SqlClient\TdsParser.cs:line 1012
   at System.Data.SqlClient.SqlInternalConnectionTds.Dispose() in e:\work\gitclone\corefx\src\System.Data.SqlClient\src\
System\Data\SqlClient\SqlInternalConnectionTds.cs:line 544
   at System.Data.ProviderBase.DbConnectionPool.DestroyObject(DbConnectionInternal obj) in e:\work\gitclone\corefx\src\S
ystem.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs:line 574
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObject
sTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& co
nnection) in e:\work\gitclone\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs:line 831

   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry
, DbConnectionOptions userOptions, DbConnectionInternal& connection) in e:\work\gitclone\corefx\src\System.Data.SqlClien
t\src\System\Data\ProviderBase\DbConnectionPool.cs:line 712
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`
1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection) in e:\wo
rk\gitclone\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionFactory.cs:line 281
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnection
Factory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in e:\work\gitclone\corefx\src
\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionInternal.cs:line 452
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory co
nnectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in e:\work\gitclone\corefx\src\System.Da
ta.SqlClient\src\System\Data\ProviderBase\DbConnectionClosed.cs:line 64
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry) in e:\work\gitclone\corefx\src\System.Da
ta.SqlClient\src\System\Data\SqlClient\SqlConnection.cs:line 992
   at System.Data.SqlClient.SqlConnection.Open() in e:\work\gitclone\corefx\src\System.Data.SqlClient\src\System\Data\Sq
lClient\SqlConnection.cs:line 585
   at Stress.Data.DataStressConnection.OpenSync() in e:\work\gitclone\corefx\src\System.Data.SqlClient\tests\StressTests
\System.Data.StressFramework\DataStressConnection.cs:line 87
   at Stress.Data.DataStressConnection.Open() in e:\work\gitclone\corefx\src\System.Data.SqlClient\tests\StressTests\Sys
tem.Data.StressFramework\DataStressConnection.cs:line 49
   at Stress.Data.DataStressFactory.GetRandomPK(Random rnd, TableMetadata table) in e:\work\gitclone\corefx\src\System.D
ata.SqlClient\tests\StressTests\System.Data.StressFramework\DataStressFactory.cs:line 333
   at Stress.Data.DataStressFactory.GetUpdateCommand(Random rnd, TableMetadata table, DataStressConnection conn) in e:\w
ork\gitclone\corefx\src\System.Data.SqlClient\tests\StressTests\System.Data.StressFramework\DataStressFactory.cs:line 41
6
   at Stress.Data.DataStressFactory.GetCommand(Random rnd, TableMetadata table, DataStressConnection conn, Boolean query
, Boolean isXml) in e:\work\gitclone\corefx\src\System.Data.SqlClient\tests\StressTests\System.Data.StressFramework\Data
StressFactory.cs:line 204
   at Stress.Data.SqlClient.SqlClientTestGroup.TestSqlAsync(Random rnd, Boolean read, Boolean poll, Boolean handle, Bool
ean xml) in e:\work\gitclone\corefx\src\System.Data.SqlClient\tests\StressTests\System.Data.SqlClient.Stress.Tests\SqlCl
ientTestGroup.cs:line 284
   at Stress.Data.SqlClient.SqlClientTestGroup.TestSqlAsyncNonBlockingWrite() in e:\work\gitclone\corefx\src\System.Data
.SqlClient\tests\StressTests\System.Data.SqlClient.Stress.Tests\SqlClientTestGroup.cs:line 347
```

Execution command `CoreRun.exe System.Data.StressRunner.exe -a System.Data.SqlClient.Stress.Tests  -duration 10 -test TestSqlAsyncNonBlockingWrite`

**Comment by saurabh500** [comment]
cc @corivera

**Comment by saurabh500** [comment]
Unable to repro
