### ISSUE TITLE
After merge from dev/api, 2 System.IO.Compression tests started failing

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#11685]
cc: @ianhays 

after PR #11679 two System.IO.Compression tests started failing. Here is the test run output:
```
call CoreRun.exe xunit.console.netcore.exe System.IO.Compression.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.0tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.IO.Compression.Tests
Discovered:  System.IO.Compression.Tests
Starting:    System.IO.Compression.Tests
   System.IO.Compression.Tests.zip_InvalidParametersAndStrangeFiles.ZipWithLargeSparseFile [FAIL]
      Assert.Equal() Failure
      Expected: 14917
      Actual:   14779
      Stack Trace:
         F:\git\corefx\src\System.IO.Compression\tests\ZipArchive\zip_InvalidParametersAndStrangeFiles.cs(239,0): at System.IO.Compression.Tests.zip_InvalidParametersAndStrangeFiles.ZipWithLargeSparseFile()
   System.IO.Compression.Tests.zip_ManualAndCompatabilityTests.CompatibilityTests(zipFile: "deflate64.zip", zipFolder: "normal", requireExplicit: True, checkTimes: True) [FAIL]
      Assert.All() Failure: 1 out of 6 items in the collection did not pass.
      [0]: System.IO.InvalidDataException: The archive entry was compressed using an unsupported compression method.
              at System.IO.Compression.ZipArchiveEntry.OpenInUpdateMode()
              at System.IO.Compression.Tests.ZipFileTestBase.<>c__DisplayClass15_2.<IsZipSameAsDir>b__0(FileData file) in F:\git\corefx\src\Common\tests\System\IO\Compression\ZipTestHelper.cs:line 170
              at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\CollectionAsserts.cs:line 31
      Stack Trace:
         F:\git\corefx\src\Common\tests\System\IO\Compression\ZipTestHelper.cs(153,0): at System.IO.Compression.Tests.ZipFileTestBase.IsZipSameAsDir(Stream archiveFile, String directory, ZipArchiveMode mode, Boolean requireExplicit, Boolean checkTimes)
         F:\git\corefx\src\System.IO.Compression\tests\ZipArchive\zip_ManualAndCompatibilityTests.cs(21,0): at System.IO.Compression.Tests.zip_ManualAndCompatabilityTests.<CompatibilityTests>d__0.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Finished:    System.IO.Compression.Tests

=== TEST EXECUTION SUMMARY ===
   System.IO.Compression.Tests  Total: 163, Errors: 0, Failed: 2, Skipped: 0, Time: 2.331s
Finished running tests.  End time=13:12:39.13, Exit code = 2
```

**Comment by joperezr** [comment]
@ianhays do you mind taking a look? it would be nice to know if this is a regression.

**Comment by ianhays** [comment]
I'm having trouble running most test projects since the merge; do I need to pass a TFM, TargetGroup, or TestTFM when building a test csproj with msbuild?

Also:
```
D:\git\corefx\src\Common\src\System\IO\StreamHelpers.cs(5,14): error CS0234: The type or namespace name 'Buffers' does not exist in
 the namespace 'System' (are you missing an assembly reference?) [D:\git\corefx\src\System.IO.Compression\src\System.IO.Compression.c
sproj]
```

But yes, to answer your question, these tests failing is a regression.

**Comment by joperezr** [comment]
> do I need to pass a TFM, TargetGroup, or TestTFM when building a test csproj with msbuild?

No. The easiest way to repro would be to re-add those tests back by locally removing the [Active issue property](https://github.com/dotnet/corefx/blob/9348997920c1ba782b45adb5e8ee9754149ab1e2/src/System.IO.Compression/tests/ZipArchive/zip_InvalidParametersAndStrangeFiles.cs#L219) in each of them, and then building the .builds file like:
```
msbuild src\System.IO.Collections\tests\System.IO.Collections.Tests.builds
```
That should automatically run the tests. Let me know if you still are having problems running them.

**Comment by ianhays** [comment]
I tried building the builds files but I'm still getting errors for every project I've tried: System.IO.Compression, System.IO.Filesystem, and System.IO.Filesystem.Watcher. The errors are either missing namespaces, functions missing from implementation but defined in contract, or couldn't locate compile assets.

**Comment by jiangzeng** [comment]
Re-open this issue as it is happening in build 20161026.02.
Log:
Unhandled Exception of Type Xunit.Sdk.AllException
Message :
Assert.All() Failure: 1 out of 6 items in the collection did not pass.\r\n[0]: System.IO.InvalidDataException: The archive entry was compressed using an unsupported compression method.\r\n        at System.IO.Compression.ZipArchiveEntry.ThrowIfNotOpenable(Boolean needToUncompress, Boolean needToLoadIntoMemory)\r\n        at System.IO.Compression.ZipArchiveEntry.OpenInUpdateMode()\r\n        at System.IO.Compression.Tests.ZipFileTestBase.<>c__DisplayClass15_2.<IsZipSameAsDir>b__0(FileData file) in D:\\A\\_work\\43\\s\\corefx\\src\\Common\\tests\\System\\IO\\Compression\\ZipTestHelper.cs:line 166\r\n        at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\BuildAgent\\work\\cb37e9acf085d108\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 31

Stack Trace :
   at System.IO.Compression.Tests.ZipFileTestBase.IsZipSameAsDir(Stream archiveFile, String directory, ZipArchiveMode mode, Boolean requireExplicit, Boolean checkTimes) in D:\A\_work\43\s\corefx\src\Common\tests\System\IO\Compression\ZipTestHelper.cs:line 232
   at System.IO.Compression.Tests.zip_ManualAndCompatabilityTests.<CompatibilityTests>d__0.MoveNext() in D:\A\_work\43\s\corefx\src\System.IO.Compression\tests\ZipArchive\zip_ManualAndCompatibilityTests.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20161026.02/workItem/System.IO.Compression.Tests/analysis/xunit/System.IO.Compression.Tests.zip_ManualAndCompatabilityTests~2FCompatibilityTests(zipFile:%20%5C%22deflate64.zip%5C%22,%20zipFolder:%20%5C%22normal%5C%22,%20requireExplicit:%20True,%20checkTimes:%20True)

**Comment by karelz** [comment]
Just one of lots of UWP test failures - no point to track it in bugs at this moment, more general effort has to happen.
