### ISSUE TITLE
Two globalization tests failed on Windows in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11736]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/172/consoleText
```
System.Globalization.Tests.NumberFormatInfoGetInstance.GetInstance(formatProvider: InvalidFormatProvider { }, expected: NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = ".", CurrencyGroupSeparator = ",", CurrencyGroupSizes = [3], CurrencyNegativePattern = 0, ... }) [FAIL]
        Assert.Equal() Failure
        Expected: NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = ".", CurrencyGroupSeparator = ",", CurrencyGroupSizes = [3], CurrencyNegativePattern = 0, ... }
        Actual:   NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = ".", CurrencyGroupSeparator = ",", CurrencyGroupSizes = [3], CurrencyNegativePattern = 0, ... }
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Globalization\tests\NumberFormatInfo\NumberFormatInfoGetInstance.cs(28,0): at System.Globalization.Tests.NumberFormatInfoGetInstance.GetInstance(IFormatProvider formatProvider, NumberFormatInfo expected)
     System.Globalization.Tests.NumberFormatInfoGetInstance.GetInstance(formatProvider: null, expected: NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = ".", CurrencyGroupSeparator = ",", CurrencyGroupSizes = [3], CurrencyNegativePattern = 0, ... }) [FAIL]
        Assert.Equal() Failure
        Expected: NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = ".", CurrencyGroupSeparator = ",", CurrencyGroupSizes = [3], CurrencyNegativePattern = 0, ... }
        Actual:   NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = ".", CurrencyGroupSeparator = ",", CurrencyGroupSizes = [3], CurrencyNegativePattern = 0, ... }
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Globalization\tests\NumberFormatInfo\NumberFormatInfoGetInstance.cs(28,0): at System.Globalization.Tests.NumberFormatInfoGetInstance.GetInstance(IFormatProvider 
```

**Comment by stephentoub** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/628/consoleText
Failed again here:
```
     System.Globalization.Tests.NumberFormatInfoGetInstance.GetInstance(formatProvider: InvalidFormatProvider { }, expected: NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = ".", CurrencyGroupSeparator = ",", CurrencyGroupSizes = [3], CurrencyNegativePattern = 0, ... }) [FAIL]
        Assert.Equal() Failure
        Expected: NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = ".", CurrencyGroupSeparator = ",", CurrencyGroupSizes = [3], CurrencyNegativePattern = 0, ... }
        Actual:   NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = ".", CurrencyGroupSeparator = ",", CurrencyGroupSizes = [3], CurrencyNegativePattern = 0, ... }
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Globalization\tests\NumberFormatInfo\NumberFormatInfoGetInstance.cs(27,0): at System.Globalization.Tests.NumberFormatInfoGetInstance.GetInstance(IFormatProvider formatProvider, NumberFormatInfo expected)
     System.Globalization.Tests.NumberFormatInfoGetInstance.GetInstance(formatProvider: null, expected: NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = ".", CurrencyGroupSeparator = ",", CurrencyGroupSizes = [3], CurrencyNegativePattern = 0, ... }) [FAIL]
        Assert.Equal() Failure
        Expected: NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = ".", CurrencyGroupSeparator = ",", CurrencyGroupSizes = [3], CurrencyNegativePattern = 0, ... }
        Actual:   NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = ".", CurrencyGroupSeparator = ",", CurrencyGroupSizes = [3], CurrencyNegativePattern = 0, ... }
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Globalization\tests\NumberFormatInfo\NumberFormatInfoGetInstance.cs(27,0): at System.Globalization.Tests.NumberFormatInfoGetInstance.GetInstance(IFormatProvider formatProvider, NumberFormatInfo expected)
```
cc: @tarekgh

**Comment by tarekgh** [comment]
@stephentoub I'll take a look.

**Comment by tarekgh** [comment]
fixed with the linked PR.
