### ISSUE TITLE
System.Transactions PSPENonMsdtcTimeout test failed in CI on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11737]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug_prtest/12/consoleText
```
System.Transactions.Tests.NonMsdtcPromoterTests.PSPENonMsdtcTimeout(promote: False) [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   1
        Stack Trace:
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Transactions\tests\NonMsdtcPromoterTests.cs(2626,0): at System.Transactions.Tests.NonMsdtcPromoterTests.PSPENonMsdtcTimeout(Boolean promote)
```

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/6/consoleText

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug_prtest/14/

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug_prtest/51/consoleText
```
System.Transactions.Tests.NonMsdtcPromoterTests.PSPENonMsdtcTimeout(promote: False) [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Transactions\tests\NonMsdtcPromoterTests.cs(1479,0): at System.Transactions.Tests.NonMsdtcPromoterTests.TestCase_TransactionTimeout(Boolean promote)
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Transactions\tests\NonMsdtcPromoterTests.cs(2184,0): at System.Transactions.Tests.NonMsdtcPromoterTests.PSPENonMsdtcTimeout(Boolean promote)
```

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug_prtest/55/consoleText
```
System.Transactions.Tests.NonMsdtcPromoterTests.PSPENonMsdtcTimeout(promote: False) [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Transactions\tests\NonMsdtcPromoterTests.cs(1479,0): at System.Transactions.Tests.NonMsdtcPromoterTests.TestCase_TransactionTimeout(Boolean promote)
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Transactions\tests\NonMsdtcPromoterTests.cs(2184,0): at System.Transactions.Tests.NonMsdtcPromoterTests.PSPENonMsdtcTimeout(Boolean promote)
```

**Comment by jimcarley** [comment]
Thanks for these.

The most recent modifications help to narrow down where the failure is happening, but we will need to make further modifications and probably enable tracing to narrow down further. More changes to the test coming.

Jim

**Comment by jimcarley** [comment]
I was just given a dump of a CloneTxTests failure which indicates that the transaction did not timeout when expected. But it is very intermittent. The same thing (transaction not timing out) would explain this intermittent failure, too. I currently have no explanation as to why the transaction isn't timing out.

**Comment by stephentoub** [comment]
Thanks, @jimcarley.

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug_prtest/59/consoleText
```
System.Transactions.Tests.NonMsdtcPromoterTests.PSPENonMsdtcTimeout(promote: False) [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Transactions\tests\NonMsdtcPromoterTests.cs(1479,0): at System.Transactions.Tests.NonMsdtcPromoterTests.TestCase_TransactionTimeout(Boolean promote)
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Transactions\tests\NonMsdtcPromoterTests.cs(2184,0): at System.Transactions.Tests.NonMsdtcPromoterTests.PSPENonMsdtcTimeout(Boolean promote)
     System.Transactions.Tests.NonMsdtcPromoterTests.PSPENonMsdtcTimeout(promote: True) [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Transactions\tests\NonMsdtcPromoterTests.cs(1479,0): at System.Transactions.Tests.NonMsdtcPromoterTests.TestCase_TransactionTimeout(Boolean promote)
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Transactions\tests\NonMsdtcPromoterTests.cs(2184,0): at System.Transactions.Tests.NonMsdtcPromoterTests.PSPENonMsdtcTimeout(Boolean promote)
```

**Comment by jimcarley** [comment]
There has been one failure since the commit for early transaction timeout issues was done. While this issue is opposite - transactions don't timeout when expected to, I thought the timeout fix might affect this one. Apparently not.

The infrequency of failures makes figuring this one out difficult.

**Comment by danmosemsft** [comment]
@sokket I wanted to see when if ever this failed (at least in Helix right?). I manually constructed the link below, and it says no failures. Right?

https://mc.int-dot.net/#/testResultHistory/corefx/System.Transactions.Tests.NonMsdtcPromoterTests/PSPENonMsdtcTimeout?failureCount=10&onlyPullRequests=false&timeFrame=OneMonth

@jimcarley do you plan to work on this further, or are we waiting for another failure? I'll move to future meantime since I don't see failures in a long time.

**Comment by sokket** [comment]
@danmosemsft By our data, this test has not failed in the last 5 days (max length of our current data). As we accrue more information, we should be able to see when this test fails in our long-term trend analysis

**Comment by ViktorHofer** [comment]
Happened again here: https://github.com/dotnet/corefx/pull/19613

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug_prtest/11/

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug_prtest/14/consoleText
```
System.Transactions.Tests.NonMsdtcPromoterTests.PSPENonMsdtcTimeout(promote: False) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.Transactions.TransactionAbortedException)
        Actual:   (No exception was thrown)
        Stack Trace:
          D:\j\workspace\outerloop_net---e1aa0946\src\System.Transactions.Local\tests\NonMsdtcPromoterTests.cs(1437,0): at System.Transactions.Tests.NonMsdtcPromoterTests.TestCase_TransactionTimeout(Boolean promote)
          D:\j\workspace\outerloop_net---e1aa0946\src\System.Transactions.Local\tests\NonMsdtcPromoterTests.cs(2180,0): at System.Transactions.Tests.NonMsdtcPromoterTests.PSPENonMsdtcTimeout(Boolean promote)
```

**Comment by stephentoub** [comment]
Failed again here on desktop:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/58/consoleText

**Comment by Jiayili1** [comment]
This test failed with "Xunit.Sdk.ThrowsException" on desktop, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/59/testReport/System.Transactions.Tests/NonMsdtcPromoterTests/PSPENonMsdtcTimeout_promote__False_/

**Comment by stephentoub** [comment]
Failed again here on desktop:
https://ci.dot.net/job/dotnet_corefx/job/release_2.0.0/job/outerloop_netfx_windows_nt_debug_prtest/2/consoleText
```
      System.Transactions.Tests.NonMsdtcPromoterTests.PSPENonMsdtcTimeout(promote: False) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.Transactions.TransactionAbortedException)
        Actual:   (No exception was thrown)
        Stack Trace:
          D:\j\workspace\outerloop_net---f52760ab\src\System.Transactions.Local\tests\NonMsdtcPromoterTests.cs(1437,0): at System.Transactions.Tests.NonMsdtcPromoterTests.TestCase_TransactionTimeout(Boolean promote)
          D:\j\workspace\outerloop_net---f52760ab\src\System.Transactions.Local\tests\NonMsdtcPromoterTests.cs(2180,0): at System.Transactions.Tests.NonMsdtcPromoterTests.PSPENonMsdtcTimeout(Boolean promote)
```

**Comment by Jiayili1** [comment]
Failed again: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_release/lastCompletedBuild/testReport/System.Transactions.Tests/NonMsdtcPromoterTests/PSPENonMsdtcTimeout_promote__True_/

MESSAGE:
~~~
Assert.Throws() Failure
  Expected: typeof(System.Transactions.TransactionAbortedException)
  Actual: typeof(System.Transactions.TransactionException): The operation is not valid for the state of the transaction.
~~~
STACK TRACE:
~~~
at System.Transactions.TransactionState.EnlistDurable(InternalTransaction tx, Guid resourceManagerIdentifier, ISinglePhaseNotification enlistmentNotification, EnlistmentOptions enlistmentOptions, Transaction atomicTransaction) 
at System.Transactions.Transaction.EnlistDurable(Guid resourceManagerIdentifier, ISinglePhaseNotification singlePhaseNotification, EnlistmentOptions enlistmentOptions) 
at System.Transactions.Tests.NonMsdtcPromoterTests.TryProhibitedOperations(Transaction tx, Guid expectedPromoterType) 
in D:\j\workspace\outerloop_net---71bc9469\src\System.Transactions.Local\tests\NonMsdtcPromoterTests.cs:line 283 
at System.Transactions.Tests.NonMsdtcPromoterTests.CreatePSPEEnlistment(Guid promoterType, Byte[] promotedToken, AutoResetEvent outcomeReceived, Boolean nonMSDTC, Transaction tx, TransactionStatus spcResponse, Boolean expectRejection, Boolean comparePromotedToken, Boolean failInitialize, Boolean failPromote, Boolean failSPC, Boolean failGetPromoterType, Boolean failGetId, Boolean incorrectNotificationObjectToSetDistributedTransactionId) 
in D:\j\workspace\outerloop_net---71bc9469\src\System.Transactions.Local\tests\NonMsdtcPromoterTests.cs:line 194 
at System.Transactions.Tests.NonMsdtcPromoterTests.<>c__DisplayClass41_0.<TestCase_TransactionTimeout>b__0() 
in D:\j\workspace\outerloop_net---71bc9469\src\System.Transactions.Local\tests\NonMsdtcPromoterTests.cs:line 1439
~~~

**Comment by qizhanMS** [comment]
Is this run on desktop too?

**Comment by Sunny-pu** [comment]
Failed again:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_release/292/testReport/System.Transactions.Tests/NonMsdtcPromoterTests/PSPENonMsdtcTimeout_promote__True_/
