### ISSUE TITLE
XmlSerializer to Support XmlSchemaTest in ReflectionOnly Mode

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#11918]
Steps to repro the issue:

1. Remove [ActiveIssue] on the test.
2. cd into `src\System.Private.Xml\tests\XmlSerializer\ReflectionOnly`
3. `msbuild System.Xml.XmlSerializer.ReflectionOnly.Tests.csproj /t:buildandtest`

The test failed with the following error,

```
XmlSerializerTests.XmlSchemaTest [FAIL]
        System.InvalidOperationException : There was an error generating the XML document.
        ---- System.PlatformNotSupportedException : System.Xml.Schema.XmlSchemaObject
        Stack Trace:
           D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializer.cs(504,0): at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSeri
  alizerNamespaces namespaces, String encodingStyle, String id)
           D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializer.cs(407,0): at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSeri
  alizerNamespaces namespaces, String encodingStyle)
           D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializer.cs(402,0): at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSeri
  alizerNamespaces namespaces)
           D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Schema\XmlSchema.cs(235,0): at System.Xml.Schema.XmlSchema.Write(XmlWriter writer, XmlNamespaceManager namespaceManager)
           D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Schema\XmlSchema.cs(155,0): at System.Xml.Schema.XmlSchema.Write(Stream stream, XmlNamespaceManager namespaceManager)
           D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Schema\XmlSchema.cs(144,0): at System.Xml.Schema.XmlSchema.Write(Stream stream)
           D:\OSS\corefx-1\corefx\src\System.Private.Xml\tests\XmlSerializer\XmlSerializerTests.cs(2348,0): at XmlSerializerTests.XmlSchemaTest()
           ----- Inner Stack Trace -----
           D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\ReflectionXmlSerializationWriter.cs(483,0): at System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteStruc
  tMethod(StructMapping mapping, String n, String ns, Object o, Boolean isNullable, Boolean needType, XmlMapping parentMapping)
           D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\ReflectionXmlSerializationWriter.cs(390,0): at System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteEleme
  nt(Object o, ElementAccessor element, String arrayName, Boolean writeAccessor, XmlMapping parentMapping)
           D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\ReflectionXmlSerializationWriter.cs(163,0): at System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteEleme
  nts(Object o, Object enumSource, ElementAccessor[] elements, TextAccessor text, ChoiceIdentifierAccessor choice, String arrayName, Boolean writeAccessors, Boolean isNullable, XmlMapping parentMapping
  )
           D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\ReflectionXmlSerializationWriter.cs(110,0): at System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteMembe
  r(Object o, Object choiceSource, ElementAccessor[] elements, TextAccessor text, ChoiceIdentifierAccessor choice, TypeDesc memberTypeDesc, Boolean writeAccessors, XmlMapping parentMapping)
           D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\ReflectionXmlSerializationWriter.cs(93,0): at System.Xml.Serialization.ReflectionXmlSerializationWriter.GenerateTyp
  eElement(Object o, XmlTypeMapping xmlMapping)
           D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\ReflectionXmlSerializationWriter.cs(58,0): at System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteObject
  OfTypeElement(Object o, XmlTypeMapping mapping)
           D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\ReflectionXmlSerializationWriter.cs(48,0): at System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteObject
  (Object o)
           D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializer.cs(438,0): at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSeri
  alizerNamespaces namespaces, String encodingStyle, String id)
```

**Comment by karelz** [comment]
Next step: Get it under debugger and find out what's wrong.
