### ISSUE TITLE
File.Open mangles path ending in ~.SS

### ISSUE THREAD

**Issue by smbecker** [dotnet/corefx#11965]
I have a file accessible through \\\localhost\Test\test.txt.~SS. If I attempt to access that file using `File.Open`, I get an exception:

```
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'o\t\Test\test.txt.~SS'.
   at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.Open(String path, FileMode mode)
   at ConsoleApplication.Program.Main(String[] args)
```

Notice that the path that it is complaining about is mangled from the requested path. I have a repro available [here](https://github.com/smbecker/filepath-repro). This works as expected using desktop framework but fails when targeting .NET CoreCLR. It also works as expected if I rename the file to test.txt.~sstmp. 

Thoughts?

**Comment by smbecker** [comment]
After doing a bit of digging, I found that FileStream [resolves the path](https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/FileStream.cs#L98) using `Path.GetFullPath`. If I pass the in above file name into `Path.GetFullPath`, it returns the mangled name that is referenced in the above exception.

**Comment by smbecker** [comment]
After looking a bit into `Path.GetFullName`, I would guess that the issue is that the file is incorrectly being handled as a short file name [here](https://github.com/dotnet/coreclr/blob/d3b3410eb8323a0286cd9c85441d962b3e7053cc/src/mscorlib/src/System/IO/Path.cs#L449). Should I close this bug and reopen in that repo?

**Comment by stephentoub** [comment]
cc: @JeremyKuhne

**Comment by JeremyKuhne** [comment]
Looking into it. We don't utilize the code in CoreCLR from CoreFX, but I'll follow up with that copy as well.
