### ISSUE TITLE
The serialization constructor for System.Reflection.Pointer cannot be found.

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#11980]
Attempting to deserialize an object of type `System.Reflection.Pointer` results in a `SerializationException`

> System.Runtime.Serialization.SerializationException : The constructor to deserialize an object of type 'System.Reflection.Pointer' was not found.
Stack Trace:
      at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
      at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
      at System.Runtime.Serialization.ObjectManager.DoFixups()
      at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, BinaryParser serParser, Boolean fCheck)
      at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean check)
      at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   E:\corefx\src\Common\tests\System\Runtime\Serialization\Formatters\BinaryFormatterHelpers.cs(20,0): at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterHelpers.Clone[T](T obj)
   E:\corefx\src\System.Runtime\tests\System\Reflection\PointerTests.cs(192,0): at System.Reflection.Tests.PointerTests.PointerSerializes(Int32 value)
   ----- Inner Stack Trace -----
      at System.Runtime.Serialization.ObjectManager.GetDeserializationConstructor(Type t)

A repro is in PR #11981

**Comment by stephentoub** [comment]
I believe the problem is the model.xml file doesn't include the private ctor as a root, and it's getting trimmed out.
