### ISSUE TITLE
DnsObsoleteGetHostByAddress_LoopbackString_ReturnsSameAsLoopbackIP test failed on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11987]
```
System.Net.NameResolution.Tests.GetHostByAddressTest.DnsObsoleteGetHostByAddress_LoopbackString_ReturnsSameAsLoopbackIP [FAIL]
        System.Net.Sockets.SocketException : Either the application has not called WSAStartup, or WSAStartup failed
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.NameResolution\src\System\Net\DNS.cs(186,0): at System.Net.Dns.InternalGetHostByAddress(IPAddress address, Boolean includeIPv6)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.NameResolution\src\System\Net\DNS.cs(109,0): at System.Net.Dns.GetHostByAddress(String address)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.NameResolution\tests\FunctionalTests\GetHostByAddressTest.cs(24,0): at System.Net.NameResolution.Tests.GetHostByAddressTest.DnsObsoleteGetHostByAddress_LoopbackString_ReturnsSameAsLoopbackIP()
```
cc: @ericeil

**Comment by davidsh** [comment]
cc: @CIPop

**Comment by CIPop** [comment]
/cc: @ericeil 

Looks like one of the newly introduced APIs isn't calling the socket init.

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/576/consoleText
```
System.Net.NameResolution.Tests.GetHostByAddressTest.DnsObsoleteGetHostByAddress_LoopbackString_ReturnsSameAsLoopbackIP [FAIL]
        System.Diagnostics.Debug+DebugAssertException : Failed to detect InterNetwork protocol: NotInitialized
        
           at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
           at System.Environment.get_StackTrace()
           at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
           at System.Net.SocketProtocolSupportPal.IsProtocolSupported(AddressFamily af) in D:\j\workspace\windows_nt_de---4526f5ff\src\Common\src\System\Net\SocketProtocolSupportPal.Windows.cs:line 59
           at System.Net.SocketProtocolSupportPal.EnsureInitialized() in D:\j\workspace\windows_nt_de---4526f5ff\src\Common\src\System\Net\SocketProtocolSupportPal.Windows.cs:line 49
           at System.Net.SocketProtocolSupportPal.get_OSSupportsIPv6() in D:\j\workspace\windows_nt_de---4526f5ff\src\Common\src\System\Net\SocketProtocolSupportPal.Windows.cs:line 27
           at System.Net.Dns.InternalGetHostByAddress(IPAddress address, Boolean includeIPv6) in D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.NameResolution\src\System\Net\DNS.cs:line 145
           at System.Net.Dns.GetHostByAddress(String address) in D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.NameResolution\src\System\Net\DNS.cs:line 112
           at System.Net.NameResolution.Tests.GetHostByAddressTest.DnsObsoleteGetHostByAddress_LoopbackString_ReturnsSameAsLoopbackIP() in D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.NameResolution\tests\FunctionalTests\GetHostByAddressTest.cs:line 24
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_release/137/consoleText
```     System.Net.NameResolution.Tests.GetHostEntryTest.DnsBeginGetHostEntry_MachineName_MatchesGetHostEntry [FAIL]
        System.Net.Sockets.SocketException : Either the application has not called WSAStartup, or WSAStartup failed
        Stack Trace:
  xUnit.net console test runner (64-bit .NET Core)
           D:\j\workspace\windows_nt_re---5f4597f5\src\System.Net.NameResolution\src\System\Net\DNS.cs(445,0): at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
           D:\j\workspace\windows_nt_re---5f4597f5\src\System.Net.NameResolution\src\System\Net\DNS.cs(575,0): at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult)
           D:\j\workspace\windows_nt_re---5f4597f5\src\System.Net.NameResolution\tests\FunctionalTests\GetHostEntryTest.cs(117,0): at System.Net.NameResolution.Tests.GetHostEntryTest.DnsBeginGetHostEntry_MachineName_MatchesGetHostEntry()
     System.Net.NameResolution.Tests.GetHostByAddressTest.DnsObsoleteGetHostByAddress_LoopbackString_ReturnsSameAsLoopbackIP [FAIL]
        System.Net.Sockets.SocketException : Either the application has not called WSAStartup, or WSAStartup failed
        Stack Trace:
           D:\j\workspace\windows_nt_re---5f4597f5\src\System.Net.NameResolution\src\System\Net\DNS.cs(186,0): at System.Net.Dns.InternalGetHostByAddress(IPAddress address, Boolean includeIPv6)
           D:\j\workspace\windows_nt_re---5f4597f5\src\System.Net.NameResolution\src\System\Net\DNS.cs(109,0): at System.Net.Dns.GetHostByAddress(String address)
           D:\j\workspace\windows_nt_re---5f4597f5\src\System.Net.NameResolution\tests\FunctionalTests\GetHostByAddressTest.cs(24,0): at System.Net.NameResolution.Tests.GetHostByAddressTest.DnsObsoleteGetHostByAddress_LoopbackString_ReturnsSameAsLoopbackIP()
```

**Comment by danmosemsft** [comment]
These three all failed with `Failed to detect InterNetwork protocol: NotInitialized` 

```
System.Net.NameResolution.Tests.ResolveTest.DnsObsoleteBeginResolve_BadName_Throws
System.Net.NameResolution.Tests.GetHostByAddressTest.DnsObsoleteGetHostByAddress_LoopbackString_ReturnsSameAsLoopbackIP
System.Net.NameResolution.Tests.GetHostByAddressTest.DnsObsoleteGetHostByAddress_UnknownIP_Throws
```

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/596/

```
 at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
 at System.Net.SocketProtocolSupportPal.IsProtocolSupported(AddressFamily af) in D:\j\workspace\windows_nt_de---4526f5ff\src\Common\src\System\Net\SocketProtocolSupportPal.Windows.cs:line 59
 at System.Net.SocketProtocolSupportPal.EnsureInitialized() in D:\j\workspace\windows_nt_de---4526f5ff\src\Common\src\System\Net\SocketProtocolSupportPal.Windows.cs:line 49
 at System.Net.SocketProtocolSupportPal.get_OSSupportsIPv6() in D:\j\workspace\windows_nt_de---4526f5ff\src\Common\src\System\Net\SocketProtocolSupportPal.Windows.cs:line 27
 at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6) in D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.NameResolution\src\System\Net\DNS.cs:line 76
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/628/consoleText
