### ISSUE TITLE
SameInstanceXslTransformReader and TC_SchemaSet_AllowXmlAttributes tests failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12024]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/573/consoleText

```
System.Xml.Tests.SameInstanceXslTransformReader.proc2 [SKIP]
        Resolving of External URIs is no longer allowed
     System.Xml.Tests.SameInstanceXslTransformWriter.proc2 [SKIP]
        Resolving of External URIs is no longer allowed
  System.Xml.XPath.Tests -> D:\j\workspace\windows_nt_de---4526f5ff\bin\Windows_NT.AnyCPU.Debug\System.Xml.XPath.Tests\System.Xml.XPath.Tests.dll
     System.Xml.Tests.TC_SchemaSet_AllowXmlAttributes.v1(xmlFile: "v1-1.xml", xsdFile: "v1.xsd", allowXmlAttributes: True, expectedWarningCount: 0, expectedErrorCount: 0, expectedSchemaSetCount: 2) [FAIL]
        Assert.Equal() Failure
        Expected: 2
        Actual:   0
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Private.Xml\tests\XmlSchema\XmlSchemaSet\TC_SchemaSet_AllowXmlAttributes.cs(282,0): at System.Xml.Tests.TC_SchemaSet_AllowXmlAttributes.v1(String xmlFile, String xsdFile, Boolean allowXmlAttributes, Int32 expectedWarningCount, Int32 expectedErrorCount, Int32 expectedSchemaSetCount)
     System.Xml.Tests.TC_SchemaSet_AllowXmlAttributes.v1(xmlFile: "v1-1.xml", xsdFile: "v1.xsd", allowXmlAttributes: False, expectedWarningCount: 0, expectedErrorCount: 1, expectedSchemaSetCount: 2) [FAIL]
        Assert.Equal() Failure
        Expected: 2
        Actual:   1
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Private.Xml\tests\XmlSchema\XmlSchemaSet\TC_SchemaSet_AllowXmlAttributes.cs(282,0): at System.Xml.Tests.TC_SchemaSet_AllowXmlAttributes.v1(String xmlFile, String xsdFile, Boolean allowXmlAttributes, Int32 expectedWarningCount, Int32 expectedErrorCount, Int32 expectedSchemaSetCount)
```

**Comment by sepidehMS** [comment]
Could not repro these failures and the tests have been modified since this fail happened. Closing. Please re-open if it happens again.
