### ISSUE TITLE
Four DSA tests failing on Windows 7

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12052]
```
     System.Security.Cryptography.Dsa.Tests.DSAImportExport.ExportAutoKey [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : The requested operation is not supported
  VoidMainWithExitCodeApp -> d:\j\workspace\outerloop_win---b88c6526\bin\Windows_NT.AnyCPU.Debug\VoidMainWithExitCodeApp\netcoreapp1.1\VoidMainWithExitCodeApp.exe
        Stack Trace:
              at System.Security.Cryptography.CngKey.InitializeKeyProperties(SafeNCryptKeyHandle keyHandle, CngKeyCreationParameters creationParameters)
              at System.Security.Cryptography.CngKey.Create(CngAlgorithm algorithm, String keyName, CngKeyCreationParameters creationParameters)
              at Internal.Cryptography.CngAlgorithmCore.GetOrGenerateKey(Int32 keySize, CngAlgorithm algorithm)
              at System.Security.Cryptography.DSACng.get_Key()
              at System.Security.Cryptography.DSACng.ExportKeyBlob(Boolean includePrivateParameters)
              at System.Security.Cryptography.DSACng.ExportParameters(Boolean includePrivateParameters)
              at System.Security.Cryptography.Dsa.Tests.DSAImportExport.ExportAutoKey()
     System.Security.Cryptography.EcDsa.Tests.ECDsaImportExportTests.TestExplicitCurvesSignVerify [SKIP]
System.Security.Cryptography.Dsa.Tests.DSAImportExport.ExportAutoKey [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : The requested operation is not supported
        Stack Trace:
              at System.Security.Cryptography.CngKeyLite.SetKeyLength(SafeNCryptKeyHandle keyHandle, Int32 keySize)
              at System.Security.Cryptography.CngKeyLite.GenerateNewExportableKey(String algorithm, Int32 keySize)
              at System.Security.Cryptography.DSAImplementation.DSACng.GetDuplicatedKeyHandle()
              at System.Security.Cryptography.DSAImplementation.DSACng.ExportKeyBlob(Boolean includePrivateParameters)
              at System.Security.Cryptography.DSAImplementation.DSACng.ExportParameters(Boolean includePrivateParameters)
              at System.Security.Cryptography.Dsa.Tests.DSAImportExport.ExportAutoKey()
     System.Security.Cryptography.Dsa.Tests.DSASignVerify.SignAndVerifyDataExplicit2048 [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : The parameter is incorrect
        Stack Trace:
              at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, Byte[] keyBlob)
              at System.Security.Cryptography.DSAImplementation.DSACng.ImportKeyBlob(Byte[] rsaBlob, Boolean includePrivate)
              at System.Security.Cryptography.DSAImplementation.DSACng.ImportParameters(DSAParameters parameters)
              at System.Security.Cryptography.Dsa.Tests.DSASignVerify.SignAndVerify(Byte[] data, String hashAlgorithmName, DSAParameters dsaParameters, Int32 expectedSignatureLength)
              at System.Security.Cryptography.Dsa.Tests.DSASignVerify.SignAndVerifyDataExplicit2048()
     System.Security.Cryptography.Dsa.Tests.DSASignVerify.InvalidKeySize_DoesNotInvalidateKey [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : The requested operation is not supported
        Stack Trace:
              at System.Security.Cryptography.CngKeyLite.SetKeyLength(SafeNCryptKeyHandle keyHandle, Int32 keySize)
              at System.Security.Cryptography.CngKeyLite.GenerateNewExportableKey(String algorithm, Int32 keySize)
              at System.Security.Cryptography.DSAImplementation.DSACng.GetDuplicatedKeyHandle()
              at System.Security.Cryptography.DSAImplementation.DSACng.ComputeQLength()
              at System.Security.Cryptography.DSAImplementation.DSACng.AdjustHashSizeIfNecessary(Byte[] hash)
              at System.Security.Cryptography.DSAImplementation.DSACng.CreateSignature(Byte[] hash)
              at System.Security.Cryptography.DSA.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm)
              at System.Security.Cryptography.DSA.SignData(Byte[] data, HashAlgorithmName hashAlgorithm)
              at System.Security.Cryptography.Dsa.Tests.DSASignVerify.InvalidKeySize_DoesNotInvalidateKey()
```

**Comment by bartonjs** [comment]
@steveharter I'm guessing that Windows 7 doesn't have 186-3 support.  We might need to make the default 1024 bit, or make an OS version check so it can be 2048 everywhere but 7.

(And if that's actually the case we'll probably need to backport that to NetFx; where apparently we don't run the default ctor of DSACng on Win7)

**Comment by steveharter** [comment]
@bartonjs how is it possible the DSACng default ctor doesn't run on windows 7? Hack of some sort?

**Comment by steveharter** [comment]
Fixed. @bartonjs considering whether the legal key sizes should also be adjusted
