### ISSUE TITLE
WebSockets.Client tests fail on UWP

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#12088]
Running the innerloop System.Net.WebSockets.Client.Tests fails on UWP (netcore50). 2 of the 3 innerloop tests fail:

```
<?xml version="1.0" encoding="utf-8"?>
<assemblies>
  <assembly name="System.Net.WebSockets.Client.Tests.dll" environment="64-bit .NET (unknown version) [collection-per-class, non-parallel]" test-framework="xUnit.net 2.2.0.3300" run-date="2016-09-26" run-time="15:38:24" total="3" passed="1" failed="2" skipped="0" time="0.162" errors="0">
    <errors />
    <collection total="3" passed="1" failed="2" skipped="0" name="Test collection for System.Net.WebSockets.Client.Tests.ClientWebSocketOptionsTests" time="0.061">
      <test name="System.Net.WebSockets.Client.Tests.ClientWebSocketOptionsTests.KeepAliveInterval_Roundtrips" type="System.Net.WebSockets.Client.Tests.ClientWebSocketOptionsTests" method="KeepAliveInterval_Roundtrips" time="0.0569163" result="Fail">
        <failure exception-type="Xunit.Sdk.ThrowsException">
          <message><![CDATA[Assert.Throws() Failure\r\nExpected: typeof(System.ArgumentOutOfRangeException)\r\nActual:   typeof(System.ArgumentNullException): Value cannot be null.\r\nParameter name: format]]></message>
          <stack-trace><![CDATA[   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0)
   at System.SR.Format(String resourceFormat, Object p1) in S:\github\corefx\src\Common\src\System\SR.cs:line 71
   at System.Net.WebSockets.ClientWebSocketOptions.set_KeepAliveInterval(TimeSpan value) in S:\github\corefx\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\ClientWebSocketOptions.cs:line 155
   at System.Net.WebSockets.Client.Tests.ClientWebSocketOptionsTests.<>c__DisplayClass3_0.<KeepAliveInterval_Roundtrips>b__0() in s:\GitHub\corefx\src\System.Net.WebSockets.Client\tests\ClientWebSocketOptionsTests.cs:line 59]]></stack-trace>
        </failure>
      </test>
      <test name="System.Net.WebSockets.Client.Tests.ClientWebSocketOptionsTests.UseDefaultCredentials_Roundtrips" type="System.Net.WebSockets.Client.Tests.ClientWebSocketOptionsTests" method="UseDefaultCredentials_Roundtrips" time="0.0015327" result="Pass" />
      <test name="System.Net.WebSockets.Client.Tests.ClientWebSocketOptionsTests.SetBuffer_InvalidArgs_Throws" type="System.Net.WebSockets.Client.Tests.ClientWebSocketOptionsTests" method="SetBuffer_InvalidArgs_Throws" time="0.0022493" result="Fail">
        <failure exception-type="Xunit.Sdk.ThrowsException">
          <message><![CDATA[Assert.Throws() Failure\r\nExpected: typeof(System.ArgumentOutOfRangeException)\r\nActual:   typeof(System.ArgumentNullException): Value cannot be null.\r\nParameter name: format]]></message>
          <stack-trace><![CDATA[   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0)
   at System.SR.Format(String resourceFormat, Object p1) in S:\github\corefx\src\Common\src\System\SR.cs:line 71
   at System.Net.WebSockets.ClientWebSocketOptions.SetBuffer(Int32 receiveBufferSize, Int32 sendBufferSize) in S:\github\corefx\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\ClientWebSocketOptions.cs:line 173
   at System.Net.WebSockets.Client.Tests.ClientWebSocketOptionsTests.<>c__DisplayClass2_0.<SetBuffer_InvalidArgs_Throws>b__0() in s:\GitHub\corefx\src\System.Net.WebSockets.Client\tests\ClientWebSocketOptionsTests.cs:line 34]]></stack-trace>
        </failure>
      </test>
    </collection>
  </assembly>
</assemblies>
```

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by davidsh** [comment]
This is a problem with the UWP TestRunner not having all the string resources (error messages in this case) in the appx package for the test runner.

**Comment by davidsh** [comment]
Closing this issue since the UWP TestRunner appears to be fixed. The tests are passing.
