### ISSUE TITLE
FileSystemWatcher_StopCalledOnBackgroundThreadDoesNotDeadlock failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12205]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/802/consoleText

```
System.IO.Tests.FileSystemWatcherTests.FileSystemWatcher_StopCalledOnBackgroundThreadDoesNotDeadlock [FAIL]
        Didn't observe a deleted event within 3000ms
        Expected: True
        Actual:   False
        Stack Trace:
              at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(WaitHandle eventOccurred, String eventName_NoRetry)
              at System.IO.Tests.FileSystemWatcherTests.FileSystemWatcher_StopCalledOnBackgroundThreadDoesNotDeadlock()
```

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/14894
