### ISSUE TITLE
System.Xml.Tests.CTransformStrStrTest.TransformStrStr9 test failed

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12273]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/925/consoleText

```
System.Xml.Tests.CTransformStrStrTest.TransformStrStr9() [FAIL]
        System.IO.IOException : The process cannot access the file 'D:\j\workspace\windows_nt_de---4526f5ff\bin\tests\Windows_NT.AnyCPU.Debug\System.Xml.Xsl.XslTransformApi.Tests\netstandard1.7\netcoreapp1.1\testfiles\testdata\xsltapi\fruits.xml' because it is being used by another process.
        Stack Trace:
              at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
              at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
              at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
              at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
              at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
              at System.Xml.XmlTextReaderImpl.OpenUrl()
              at System.Xml.XmlTextReaderImpl.Read()
              at System.Xml.XPath.XPathDocument.LoadFromReader(XmlReader reader, XmlSpace space)
              at System.Xml.XPath.XPathDocument..ctor(String uri, XmlSpace space)
              at System.Xml.Xsl.XslTransform.Transform(String inputfile, String outputfile, XmlResolver resolver)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Private.Xml\tests\Xslt\XslTransformApi\CXslTransform.cs(2226,0): at System.Xml.Tests.CTransformStrStrTest.TransformStrStr9()
```

**Comment by sepidehMS** [comment]
Closing as could not repro the failure. Seems like it's either be gone or happens very rarely. Please re-open if seen again.
