### ISSUE TITLE
SslStreamAlertsTest failure in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12683]
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/1647/consoleText

```
System.Net.Security.Tests.SslStreamAlertsTest.SslStream_StreamToStream_ServerInitiatedCloseNotify_Ok [FAIL]
        System.ComponentModel.Win32Exception : The credentials supplied to the package were not recognized
        Stack Trace:
              at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)
  Finished running tests.  End time= 1:45:19.12, Exit code = 0
  Finished:    System.Reflection.TypeExtensions.Tests
              at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential)
              at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)

              at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
              at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
              at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
              at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
              at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
              at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           D:\j\workspace\windows_nt_re---37265eab\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(19,0): at System.Threading.Tasks.TaskTimeoutExtensions.<TimeoutAfter>d__0.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\SslStreamAlertsTest.cs(76,0): at System.Net.Security.Tests.SslStreamAlertsTest.<SslStream_StreamToStream_ServerInitiatedCloseNotify_Ok>d__3.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/1674/consoleText
```
System.Net.Security.Tests.SslStreamAlertsTest.SslStream_StreamToStream_ServerInitiatedCloseNotify_Ok [FAIL]
        System.ComponentModel.Win32Exception : The credentials supplied to the package were not recognized
        Stack Trace:
  System.Reflection.Emit.Lightweight.Tests -> D:\j\workspace\windows_nt_de---4526f5ff\bin\AnyOS.AnyCPU.Debug\System.Reflection.Emit.Lightweight.Tests\System.Reflection.Emit.Lightweight.Tests.dll
              at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)
              at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential)
              at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
              at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
              at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
              at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
              at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
              at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
              at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
              at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
              at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           D:\j\workspace\windows_nt_de---4526f5ff\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(19,0): at System.Threading.Tasks.TaskTimeoutExtensions.<TimeoutAfter>d__0.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\tests\FunctionalTests\SslStreamAlertsTest.cs(76,0): at System.Net.Security.Tests.SslStreamAlertsTest.<SslStream_StreamToStream_ServerInitiatedCloseNotify_Ok>d__3.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by CIPop** [comment]
/cc: @karelz 
Thanks @stephentoub. I'll look into this.

I presume there's still no way to enable ETW in CI (#4152) and so I'll need to repro this locally.

**Comment by danmosemsft** [comment]
This was hit again in CI this time by `System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success(serverProtocol: Tls11)`

@CIPop

**Comment by CIPop** [comment]
Tracking with #14519.

**Comment by ianhays** [comment]
Tracking this failure in https://github.com/dotnet/corefx/issues/16516. Please comment there with any failure reports instead of re-opening this issue.
