### ISSUE TITLE
[1.0.0] TestUserCredentialsPropertiesOnWindows failing on Windows (v1.0 only)

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12696]
```
System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows [FAIL]
        System.InvalidOperationException : No process is associated with this object.
        Stack Trace:
           D:\j\workspace\outerloop_win---2155886e\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(779,0): at System.Diagnostics.Process.EnsureState(State state)
           D:\j\workspace\outerloop_win---2155886e\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(189,0): at System.Diagnostics.Process.get_HasExited()
           D:\j\workspace\outerloop_win---2155886e\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(393,0): at System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows()
```

Examples:
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_windows_nt_release/13/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_windows_nt_debug/12/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_win10_release/12/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_win10_debug/12/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_windows_nt_release/12/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_windows_nt_debug/11/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_win10_release/11/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_win10_debug/11/
http://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_windows_nt_release/11/
...

**Comment by karelz** [comment]
@Priya91 is it a regression? Or flaky test?

**Comment by stephentoub** [comment]
This continues to fail, e.g.
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_win10_release/14/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_windows_nt_debug/14/

**Comment by Priya91** [comment]
Oh just noticed this is failing in release/1.0.0 branch, the test was fixed in master, will port the change to release.

**Comment by karelz** [comment]
Ah, I didn't notice it either. Given the number of failures, I think we should fix it in 1.0.x - @leecow is that ok?

**Comment by danmosemsft** [comment]
@Priya91 please sync with Lee, port if they are accepting changes of this sort, otherwise please close this

**Comment by karelz** [comment]
I spoke with @leecow and he mentioned it is ok. We just need to send info to shiproom "hey, FYI we ported this one - test only change".

**Comment by danmosemsft** [comment]
@Priya91 can you please go ahead and do the port, and close this issue? NB: it perhaps need a fix in 1.1

**Comment by Priya91** [comment]
> @Priya91 can you please go ahead and do the port, and close this issue? NB: it perhaps need a fix in 1.1

There's a PR up here #13732, waiting for release branches to be open for merge.

**Comment by karelz** [comment]
@Priya91 please merge it if you sent shiproom the heads up I mentioned above ...

**Comment by stephentoub** [comment]
@karelz, there's still a test disabled against this issue:
https://github.com/dotnet/runtime/blob/ccf6aedb63c37ea8e10e4f5b5d9d23a69bdd9489/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs#L353-L355
