### ISSUE TITLE
AppDomainTests.UnhandledException_Called failing in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12716]
This has been failing frequently but intermittently.  The problem appears to be that the test waits for the process to exit, and it doesn't exit within 30 seconds:
https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs#L170
```
 System.Tests.AppDomainTests.UnhandledException_Called [FAIL]
        Assert+WrapperXunitException : File path: /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs. Line: 170
        ---- Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/src/Common/tests/System/Diagnostics/AssertWithCallerAttributes.cs(583,0): at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
           /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/src/Common/tests/System/Diagnostics/AssertWithCallerAttributes.cs(578,0): at Assert.True(Boolean condition, String userMessage, String path, Int32 line)
           /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs(170,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
           /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/src/System.Runtime.Extensions/tests/System/AppDomainTests.cs(69,0): at System.Tests.AppDomainTests.UnhandledException_Called()
           ----- Inner Stack Trace -----
           /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/src/Common/tests/System/Diagnostics/AssertWithCallerAttributes.cs(571,0): at Assert.True(Boolean condition, String userMessage, String path, Int32 line)
```
Examples:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_release/38/consoleText
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/38/consoleText
https://ci.dot.net/job/dotnet_corefx/job/master/job/rhel7.2_debug/334/consoleText
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu16.10_release/27/consoleText

cc: @ramarag, @jkotas

**Comment by karelz** [comment]
@ramarag can you please take a look now? We want to drive flaky test failures to 0.

**Comment by ramarag** [comment]
cc @rahku  is this something you are already looking into ?

**Comment by AlexGhiondea** [comment]
@rahku is this something you are still looking at?

**Comment by krwq** [comment]
Failing test will also need to use System.IO.TempFile from src\Common\tests\System\IO\TempFile.cs since this is running in AppContainer
