### ISSUE TITLE
TcpClient.BeginConnect doesn't handle socket exception for host name with multiple ip addresses.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#12740]
```
        ---- System.PlatformNotSupportedException : This platform does not support connecting sockets to DNS endpoints via the instance Connect and ConnectAsync methods, due to the potential for a host name to map to multiple IP addresses and sockets becoming invalid for use after a failed connect attempt. Use the static ConnectAsync method, or provide to the instance methods the specific IPAddress desired.
        Stack Trace:
           /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/src/System.Net.Mail/src/System/Net/Mail/SmtpTransport.cs(166,0): at System.Net.Mail.SmtpTransport.BeginGetConnection(ContextAwareResult outerResult, AsyncCallback callback, Object state, String host, Int32 port)
           /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/src/System.Net.Mail/src/System/Net/Mail/SmtpClient.cs(753,0): at System.Net.Mail.SmtpClient.SendAsync(MailMessage message, Object userToken)
           /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/src/System.Net.Mail/src/System/Net/Mail/SmtpClient.cs(837,0): at System.Net.Mail.SmtpClient.SendMailAsync(MailMessage message)
           /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/src/System.Net.Mail/tests/Functional/SmtpClientTest.cs(228,0): at System.Net.Mail.Tests.SmtpClientTest.TestMailDeliveryAsync()
           ----- Inner Stack Trace -----
              at System.Net.Sockets.Socket.ThrowIfNotSupportsMultipleConnectAttempts()
              at System.Net.Sockets.Socket.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
              at System.Net.Sockets.TcpClient.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
           /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/src/System.Net.Mail/src/System/Net/Mail/SmtpConnection.cs(108,0): at System.Net.Mail.SmtpConnection.BeginInitializeConnection(String host, Int32 port, AsyncCallback callback, Object state)
           /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/src/System.Net.Mail/src/System/Net/Mail/SmtpConnection.cs(488,0): at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnection()
           /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/src/System.Net.Mail/src/System/Net/Mail/SmtpConnection.cs(483,0): at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.GetConnection()
           /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/src/System.Net.Mail/src/System/Net/Mail/SmtpConnection.cs(120,0): at System.Net.Mail.SmtpConnection.BeginGetConnection(ContextAwareResult outerResult, AsyncCallback callback, Object state, String host, Int32 port)
           /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/src/System.Net.Mail/src/System/Net/Mail/SmtpTransport.cs(162,0): at System.Net.Mail.SmtpTransport.BeginGetConnection(ContextAwareResult outerResult, AsyncCallback callback, Object state, String host, Int32 port)
```

**Comment by Priya91** [comment]
cc @ericeil
