### ISSUE TITLE
OSX System.EntryPointNotFoundException for Console.WriteLine()

### ISSUE THREAD

**Issue by ChrisEelmaa** [dotnet/corefx#1281]
Here is the error I am getting (latest yosemite), running very simple HelloWorld program:
```
Chriss-MBP:demo chriseelmaa$ ./corerun -c . tere.exe

Resource string id=0x17FC System.EntryPointNotFoundException: Resource string id=0x170C
   at Interop.open64(String filename, Int32 flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, Int32 flags, Int32 mode)
   at System.ConsolePal.UnixConsoleStream..ctor(String devPath, FileAccess access)
   at System.ConsolePal.OpenStandardOutput()
   at System.Console.OpenStandardOutput()
   at System.Console.<get_Out>b__3()
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at System.Console.get_Out()
   at System.Console.WriteLine(String value)
   at Program.Main(String[] args)
```
The problem is that libc does not have open64/lseek64, only open/lseek. I verified it by changing Interop.CoreFileIO.Unix.cs, and it worked. I'd send PR, but I am not 100% sure how to solve this problem or if this is being solved by someone - as of right now, no System.FileSystem.dll is produced when you compile for osx. 

I assume creating new Interop.CoreFileIO.OSX.cs, and then creating new configuration for System.FileSystem project (osx) is okay?

**Comment by kangaroo** [comment]
Are you on an old revision?

https://github.com/dotnet/corefx/issues/715

**Comment by ChrisEelmaa** [comment]
Huhhh, you're right. I forked corefx today, but apparently I had already an old fork of this, which has not been updated. Did not notice I was working with old one :/

Thanks.
