### ISSUE TITLE
Recent changes in coreclr broke System.Runtime tests since Assembly.Load implementation changed

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#12818]
Console output is:
```cmd
Command(s):
call CoreRun.exe xunit.console.netcore.exe System.Runtime.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Runtime.Tests
Discovered:  System.Runtime.Tests
Starting:    System.Runtime.Tests
   System.Reflection.Tests.AssemblyTests.AssemblyLoadFromBytesNeg [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.BadImageFormatException)
      Actual:   typeof(System.ArgumentNullException): Buffer cannot be null.
      Parameter name: buffer
      Stack Trace:
            at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
            at System.Reflection.Assembly.Load(Byte[] rawAssembly, Byte[] rawSymbolStore)
            at System.Reflection.Assembly.Load(Byte[] rawAssembly)
         F:\git\corefxCopy\corefx\src\System.Runtime\tests\System\Reflection\AssemblyTests.cs(128,0): at System.Reflection.Tests.AssemblyTests.<>c.<AssemblyLoadFromBytesNeg>b__12_1()
   System.Reflection.Tests.AssemblyTests.AssemblyLoadFromBytes [FAIL]
      System.ArgumentNullException : Buffer cannot be null.
      Parameter name: buffer
      Stack Trace:
            at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
            at System.Reflection.Assembly.Load(Byte[] rawAssembly, Byte[] rawSymbolStore)
            at System.Reflection.Assembly.Load(Byte[] rawAssembly)
         F:\git\corefxCopy\corefx\src\System.Runtime\tests\System\Reflection\AssemblyTests.cs(119,0): at System.Reflection.Tests.AssemblyTests.AssemblyLoadFromBytes()
Finished:    System.Runtime.Tests

=== TEST EXECUTION SUMMARY ===
   System.Runtime.Tests  Total: 10522, Errors: 0, Failed: 2, Skipped: 0, Time: 1.480s
Finished running tests.  End time=14:51:37.88, Exit code = 2
```

**Comment by karelz** [comment]
@rahku can you please take a look?
