### ISSUE TITLE
Linux: System.Diagnostics.Process.GetProcesses can throw if reading from /proc for any process fails

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/corefx#12834]
## Source
This issue was initially reported by @robvanpamel on https://github.com/OmniSharp/omnisharp-vscode/issues/808.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
```

## Description
This issue came @robvanpamel having problems with `dotnet test` when invoked by OmniSharp. From inspecting the code, this looks to be the problem:

1. `dotnet test` is calling System.Diagnostics.Process.GetProcesses(), and then it is going to filter that to a process that it care about
2. System.Diagnostics.Process.GetProcesses finds a process, and it tries to read its stat file
3. This throws (because the process is exiting???) and that breaks the process listing completely

## Call stack
dotnet-test Error: 0 : System.IO.InvalidDataException: Found invalid data while decoding.
at System.IO.StringParser.ParseNextChar()
at Interop.procfs.TryParseStatFile(String statFilePath, ParsedStat& result, ReusableTextReader reusableReader)
at System.Diagnostics.ProcessManager.CreateProcessInfo(ParsedStat procFsStat, ReusableTextReader reusableReader)
at System.Diagnostics.ProcessManager.CreateProcessInfo(Int32 pid, ReusableTextReader reusableReader)
at System.Diagnostics.ProcessManager.GetProcessInfos(String machineName)
at System.Diagnostics.Process.GetProcesses(String machineName)
at System.Diagnostics.Process.GetProcesses()
at Microsoft.DotNet.Tools.Test.TestCommand.RegisterForParentProcessExit(Int32 id)
at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)

**Comment by svick** [comment]
This sounds very similar to https://github.com/dotnet/corefx/issues/12755.

**Comment by stephentoub** [comment]
I believe this is the same as https://github.com/dotnet/corefx/issues/12755, for which a fix was already merged.
