### ISSUE TITLE
Failure in System.Net.Sockets.Tests.DualModeConnectionlessReceiveMessageFrom.ReceiveMessageFromV6BoundToSpecificV6_Success

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#12908]
https://ci.dot.net/job/dotnet_corefx/job/release_1.1.0/job/centos7.1_debug_prtest/114/console

```
14:43:58      System.Net.Sockets.Tests.DualModeConnectionlessReceiveMessageFrom.ReceiveMessageFromV6BoundToSpecificV6_Success [FAIL]
14:43:58         Assert.Throws() Failure
14:43:58         Expected: typeof(System.Exception)
14:43:58         Actual:   (No exception was thrown)
14:43:58         Stack Trace:
14:43:58               at System.Net.Sockets.Tests.DualModeConnectionlessReceiveMessageFrom.ReceiveMessageFrom_Helper(IPAddress listenOn, IPAddress connectTo, Boolean expectedToTimeout)
14:43:58               at System.Net.Sockets.Tests.DualModeConnectionlessReceiveMessageFrom.ReceiveMessageFromV6BoundToSpecificV6_Success()
14:44:00   Finished:    System.Net.Sockets.Tests
14:44:00   
14:44:00   === TEST EXECUTION SUMMARY ===
14:44:00 /mnt/resource/j/workspace/dotnet_corefx/release_1.1.0/centos7.1_debug_prtest/Tools/tests.targets(261,5): warning :    System.Net.Sockets.Tests  Total: 471, Errors: 0, Failed: 1, Skipped: 0, Time: 3.677s 
```

**Comment by danmosemsft** [comment]
@CIPop who should look at this..?

**Comment by CIPop** [comment]
Looks like one of the dual-mode socket tests fails on Centos. I believe that would be @ericeil, @stephentoub /cc: @karelz

**Comment by Priya91** [comment]
Not seeing this failure in release/1.1.0 branch 25 builds.. Closing as not repro, please reopen if issue found again.
