### ISSUE TITLE
RC2CipherTests failing on Win7 with "unknown error"

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12926]
e.g. https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/42/consoleText

```
System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2ReuseEncryptorDecryptor [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc10000bb)
        Stack Trace:
              at Internal.NativeCrypto.Cng.SetEffectiveKeyLength(SafeKeyHandle hAlg, Int32 effectiveKeyLength)
              at Internal.Cryptography.BasicSymmetricCipherBCrypt..ctor(SafeAlgorithmHandle algorithm, CipherMode cipherMode, Int32 blockSizeInBytes, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransformCore(CipherMode cipherMode, PaddingMode paddingMode, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Int32 blockSize, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateEncryptor()
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\RC2\RC2CipherTests.cs(176,0): at System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2ReuseEncryptorDecryptor()
     System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2ExplicitEncryptorDecryptor_WithIV [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc10000bb)
        Stack Trace:
              at Internal.NativeCrypto.Cng.SetEffectiveKeyLength(SafeKeyHandle hAlg, Int32 effectiveKeyLength)
              at Internal.Cryptography.BasicSymmetricCipherBCrypt..ctor(SafeAlgorithmHandle algorithm, CipherMode cipherMode, Int32 blockSizeInBytes, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransformCore(CipherMode cipherMode, PaddingMode paddingMode, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Int32 blockSize, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateEncryptor(Byte[] rgbKey, Byte[] rgbIV)
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\RC2\RC2CipherTests.cs(214,0): at System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2ExplicitEncryptorDecryptor_WithIV()
     System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2RoundTrip(cipherMode: ECB, paddingMode: None, key: \"3000000000000000\", iv: null, textHex: \"1000000000000001\", expectedDecrypted: null, expectedEncrypted: \"30649EDF9BE7D2C2\") [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc10000bb)
        Stack Trace:
              at Internal.NativeCrypto.Cng.SetEffectiveKeyLength(SafeKeyHandle hAlg, Int32 effectiveKeyLength)
              at Internal.Cryptography.BasicSymmetricCipherBCrypt..ctor(SafeAlgorithmHandle algorithm, CipherMode cipherMode, Int32 blockSizeInBytes, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransformCore(CipherMode cipherMode, PaddingMode paddingMode, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Int32 blockSize, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateEncryptor()
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\CryptoUtils.cs(16,0): at Test.Cryptography.CryptoUtils.Encrypt(SymmetricAlgorithm alg, Byte[] plainText, Int32 blockSizeMultipler)
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\RC2\RC2CipherTests.cs(158,0): at System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2RoundTrip(CipherMode cipherMode, PaddingMode paddingMode, String key, String iv, String textHex, String expectedDecrypted, String expectedEncrypted)
     System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2RoundTrip(cipherMode: ECB, paddingMode: None, key: \"FFFFFFFFFFFFFFFF\", iv: null, textHex: \"FFFFFFFFFFFFFFFF\", expectedDecrypted: null, expectedEncrypted: \"278B27E42E2F0D49\") [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc10000bb)
        Stack Trace:
              at Internal.NativeCrypto.Cng.SetEffectiveKeyLength(SafeKeyHandle hAlg, Int32 effectiveKeyLength)
              at Internal.Cryptography.BasicSymmetricCipherBCrypt..ctor(SafeAlgorithmHandle algorithm, CipherMode cipherMode, Int32 blockSizeInBytes, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransformCore(CipherMode cipherMode, PaddingMode paddingMode, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Int32 blockSize, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateEncryptor()
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\CryptoUtils.cs(16,0): at Test.Cryptography.CryptoUtils.Encrypt(SymmetricAlgorithm alg, Byte[] plainText, Int32 blockSizeMultipler)
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\RC2\RC2CipherTests.cs(158,0): at System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2RoundTrip(CipherMode cipherMode, PaddingMode paddingMode, String key, String iv, String textHex, String expectedDecrypted, String expectedEncrypted)
     System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2RoundTrip(cipherMode: ECB, paddingMode: None, key: \"88bca90e90875a7f0f79c384627bafb2\", iv: null, textHex: \"0000000000000000\", expectedDecrypted: null, expectedEncrypted: \"2269552ab0f85ca6\") [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc10000bb)
        Stack Trace:
              at Internal.NativeCrypto.Cng.SetEffectiveKeyLength(SafeKeyHandle hAlg, Int32 effectiveKeyLength)
              at Internal.Cryptography.BasicSymmetricCipherBCrypt..ctor(SafeAlgorithmHandle algorithm, CipherMode cipherMode, Int32 blockSizeInBytes, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransformCore(CipherMode cipherMode, PaddingMode paddingMode, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Int32 blockSize, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateEncryptor()
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\CryptoUtils.cs(16,0): at Test.Cryptography.CryptoUtils.Encrypt(SymmetricAlgorithm alg, Byte[] plainText, Int32 blockSizeMultipler)
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\RC2\RC2CipherTests.cs(158,0): at System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2RoundTrip(CipherMode cipherMode, PaddingMode paddingMode, String key, String iv, String textHex, String expectedDecrypted, String expectedEncrypted)
     System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2RoundTrip(cipherMode: ECB, paddingMode: None, key: \"87FF0737F868378F\", iv: null, textHex: \"5468697320697320612073656E74656E636520746861742069\"..., expectedDecrypted: null, expectedEncrypted: \"F6DF2E83811D6CB0C8A5830069D16F6A51C985D70038525390\"...) [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc10000bb)
        Stack Trace:
              at Internal.NativeCrypto.Cng.SetEffectiveKeyLength(SafeKeyHandle hAlg, Int32 effectiveKeyLength)
              at Internal.Cryptography.BasicSymmetricCipherBCrypt..ctor(SafeAlgorithmHandle algorithm, CipherMode cipherMode, Int32 blockSizeInBytes, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransformCore(CipherMode cipherMode, PaddingMode paddingMode, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Int32 blockSize, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateEncryptor()
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\CryptoUtils.cs(16,0): at Test.Cryptography.CryptoUtils.Encrypt(SymmetricAlgorithm alg, Byte[] plainText, Int32 blockSizeMultipler)
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\RC2\RC2CipherTests.cs(158,0): at System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2RoundTrip(CipherMode cipherMode, PaddingMode paddingMode, String key, String iv, String textHex, String expectedDecrypted, String expectedEncrypted)
     System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2RoundTrip(cipherMode: ECB, paddingMode: PKCS7, key: \"87FF0737F868378F\", iv: null, textHex: \"5468697320697320612073656E74656E636520746861742069\"..., expectedDecrypted: null, expectedEncrypted: \"F6DF2E83811D6CB0C8A5830069D16F6A51C985D70038525390\"...) [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc10000bb)
        Stack Trace:
              at Internal.NativeCrypto.Cng.SetEffectiveKeyLength(SafeKeyHandle hAlg, Int32 effectiveKeyLength)
              at Internal.Cryptography.BasicSymmetricCipherBCrypt..ctor(SafeAlgorithmHandle algorithm, CipherMode cipherMode, Int32 blockSizeInBytes, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransformCore(CipherMode cipherMode, PaddingMode paddingMode, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Int32 blockSize, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateEncryptor()
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\CryptoUtils.cs(16,0): at Test.Cryptography.CryptoUtils.Encrypt(SymmetricAlgorithm alg, Byte[] plainText, Int32 blockSizeMultipler)
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\RC2\RC2CipherTests.cs(158,0): at System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2RoundTrip(CipherMode cipherMode, PaddingMode paddingMode, String key, String iv, String textHex, String expectedDecrypted, String expectedEncrypted)
     System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2RoundTrip(cipherMode: ECB, paddingMode: Zeros, key: \"87FF0737F868378F\", iv: null, textHex: \"5468697320697320612073656E74656E636520746861742069\"..., expectedDecrypted: \"5468697320697320612073656E74656E636520746861742069\"..., expectedEncrypted: \"F6DF2E83811D6CB0C8A5830069D16F6A51C985D70038525390\"...) [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc10000bb)
        Stack Trace:
              at Internal.NativeCrypto.Cng.SetEffectiveKeyLength(SafeKeyHandle hAlg, Int32 effectiveKeyLength)
              at Internal.Cryptography.BasicSymmetricCipherBCrypt..ctor(SafeAlgorithmHandle algorithm, CipherMode cipherMode, Int32 blockSizeInBytes, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransformCore(CipherMode cipherMode, PaddingMode paddingMode, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Int32 blockSize, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateEncryptor()
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\CryptoUtils.cs(16,0): at Test.Cryptography.CryptoUtils.Encrypt(SymmetricAlgorithm alg, Byte[] plainText, Int32 blockSizeMultipler)
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\RC2\RC2CipherTests.cs(158,0): at System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2RoundTrip(CipherMode cipherMode, PaddingMode paddingMode, String key, String iv, String textHex, String expectedDecrypted, String expectedEncrypted)
     System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2RoundTrip(cipherMode: CBC, paddingMode: None, key: \"87FF0737F868378F\", iv: \"E531E789E3E1BB6F\", textHex: \"5468697320697320612073656E74656E636520746861742069\"..., expectedDecrypted: null, expectedEncrypted: \"85B5D998F35ECD98DB886798170F64BA2DBA4FE902791CDE90\"...) [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc10000bb)
        Stack Trace:
              at Internal.NativeCrypto.Cng.SetEffectiveKeyLength(SafeKeyHandle hAlg, Int32 effectiveKeyLength)
              at Internal.Cryptography.BasicSymmetricCipherBCrypt..ctor(SafeAlgorithmHandle algorithm, CipherMode cipherMode, Int32 blockSizeInBytes, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransformCore(CipherMode cipherMode, PaddingMode paddingMode, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Int32 blockSize, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateEncryptor()
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\CryptoUtils.cs(16,0): at Test.Cryptography.CryptoUtils.Encrypt(SymmetricAlgorithm alg, Byte[] plainText, Int32 blockSizeMultipler)
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\RC2\RC2CipherTests.cs(158,0): at System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2RoundTrip(CipherMode cipherMode, PaddingMode paddingMode, String key, String iv, String textHex, String expectedDecrypted, String expectedEncrypted)
     System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2RoundTrip(cipherMode: CBC, paddingMode: PKCS7, key: \"87FF0737F868378F\", iv: \"E531E789E3E1BB6F\", textHex: \"5468697320697320612073656E74656E636520746861742069\"..., expectedDecrypted: null, expectedEncrypted: \"85B5D998F35ECD98DB886798170F64BA2DBA4FE902791CDE90\"...) [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc10000bb)
        Stack Trace:
              at Internal.NativeCrypto.Cng.SetEffectiveKeyLength(SafeKeyHandle hAlg, Int32 effectiveKeyLength)
              at Internal.Cryptography.BasicSymmetricCipherBCrypt..ctor(SafeAlgorithmHandle algorithm, CipherMode cipherMode, Int32 blockSizeInBytes, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransformCore(CipherMode cipherMode, PaddingMode paddingMode, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Int32 blockSize, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateEncryptor()
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\CryptoUtils.cs(16,0): at Test.Cryptography.CryptoUtils.Encrypt(SymmetricAlgorithm alg, Byte[] plainText, Int32 blockSizeMultipler)
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\RC2\RC2CipherTests.cs(158,0): at System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2RoundTrip(CipherMode cipherMode, PaddingMode paddingMode, String key, String iv, String textHex, String expectedDecrypted, String expectedEncrypted)
     System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2RoundTrip(cipherMode: CBC, paddingMode: Zeros, key: \"87FF0737F868378F\", iv: \"E531E789E3E1BB6F\", textHex: \"5468697320697320612073656E74656E636520746861742069\"..., expectedDecrypted: \"5468697320697320612073656E74656E636520746861742069\"..., expectedEncrypted: \"85B5D998F35ECD98DB886798170F64BA2DBA4FE902791CDE90\"...) [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc10000bb)
        Stack Trace:
              at Internal.NativeCrypto.Cng.SetEffectiveKeyLength(SafeKeyHandle hAlg, Int32 effectiveKeyLength)
              at Internal.Cryptography.BasicSymmetricCipherBCrypt..ctor(SafeAlgorithmHandle algorithm, CipherMode cipherMode, Int32 blockSizeInBytes, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransformCore(CipherMode cipherMode, PaddingMode paddingMode, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Int32 blockSize, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateEncryptor()
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\CryptoUtils.cs(16,0): at Test.Cryptography.CryptoUtils.Encrypt(SymmetricAlgorithm alg, Byte[] plainText, Int32 blockSizeMultipler)
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\RC2\RC2CipherTests.cs(158,0): at System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2RoundTrip(CipherMode cipherMode, PaddingMode paddingMode, String key, String iv, String textHex, String expectedDecrypted, String expectedEncrypted)
     System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2ExplicitEncryptorDecryptor_NoIV [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc10000bb)
        Stack Trace:
              at Internal.NativeCrypto.Cng.SetEffectiveKeyLength(SafeKeyHandle hAlg, Int32 effectiveKeyLength)
              at Internal.Cryptography.BasicSymmetricCipherBCrypt..ctor(SafeAlgorithmHandle algorithm, CipherMode cipherMode, Int32 blockSizeInBytes, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransformCore(CipherMode cipherMode, PaddingMode paddingMode, Byte[] key, Int32 effectiveKeyLength, Byte[] iv, Int32 blockSize, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)
              at Internal.Cryptography.RC2Implementation.CreateEncryptor(Byte[] rgbKey, Byte[] rgbIV)
           d:\j\workspace\outerloop_win---b280fd23\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\RC2\RC2CipherTests.cs(233,0): at System.Security.Cryptography.Encryption.RC2.Tests.RC2CipherTests.RC2ExplicitEncryptorDecryptor_NoIV()
```

cc: @steveharter, @bartonjs

**Comment by steveharter** [comment]
Removing blocking (since tests disabled)
