### ISSUE TITLE
Unhandled exception in System.Net.Security tests on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12939]
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug_prtest/64/consoleText

```
Unhandled Exception: System.InvalidOperationException: This operation is only allowed using a successfully authenticated context.
     at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
     at System.Net.Security.SslState.get_SecureStream()
     at System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult)
     at System.Net.Security.Tests.DummyTcpServer.OnReceive(IAsyncResult result) in D:\j\workspace\outerloop_win---7ad0ce03\src\System.Net.Security\tests\FunctionalTests\DummyTcpServer.cs:line 202
     at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
     at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
     at System.Net.LazyAsyncResult.InvokeCallback(Object result)
     at System.Net.AsyncProtocolRequest.CompleteUser(Object userResult)
     at System.Net.Security.SslStreamInternal.StartFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
     at System.Net.Security.SslStreamInternal.ReadHeaderCallback(AsyncProtocolRequest asyncRequest)
     at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
     at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
     at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
     at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Net.ContextAwareResult.Complete(IntPtr userToken)
     at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
     at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
     at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

cc: @davidsh, @cipop

**Comment by CIPop** [comment]
Thanks for opening the issue @stephentoub. I saw more of these happening lately.
There is no indication on what test was running (the issue happened on an IOCP completion thread) and no dump or ETW traces (enhancement tracked by #4152).

The only way to further investigate is to repro on a dev box.

**Comment by stephentoub** [comment]
> There is no indication on what test was running (the issue happened

Suggestion: modify DummyTcpServer's ctor to either take and store a stack trace which it then includes in any exceptions it allows to go unhandled (e.g. from OnReceive), or do the same but with a [CallerMemberName] in the DummyTcpServer's ctor.  that should help us to understand at least which test it is the next time it happens.

**Comment by stephentoub** [comment]
Happened again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_win10_debug/48/consoleText

**Comment by stephentoub** [comment]
I hit this locally after adding the additional diagnostics in #13168.  Here's the stack where the server was created:
```
Unhandled Exception: System.InvalidOperationException: Exception in DummyTcpServer created with stack:    at System.Environment.GetStackTrace(Exception e, Bo
  olean needFileInfo)
     at System.Environment.get_StackTrace()
     at System.Net.Security.Tests.DummyTcpServer..ctor(IPEndPoint endPoint, Nullable`1 sslEncryptionPolicy) in c:\Users\stoub\Source\repos\corefx\src\System.Ne
  t.Security\tests\FunctionalTests\DummyTcpServer.cs:line 25
     at System.Net.Security.Tests.ClientAsyncAuthenticateTest.<ClientAsyncSslHelper>d__14.MoveNext() in c:\Users\stoub\Source\repos\corefx\src\System.Net.Secur
  ity\tests\FunctionalTests\ClientAsyncAuthenticateTest.cs:line 143
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
     at System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncSslHelper(EncryptionPolicy encryptionPolicy, SslProtocols clientSslProtocols, SslProto
  cols serverSslProtocols)
     at System.Net.Security.Tests.ClientAsyncAuthenticateTest.<ClientAsyncAuthenticate_ServerRequireEncryption_ConnectWithEncryption>d__2.MoveNext() in c:\User
  s\stoub\Source\repos\corefx\src\System.Net.Security\tests\FunctionalTests\ClientAsyncAuthenticateTest.cs:line 31
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
     at System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_ServerRequireEncryption_ConnectWithEncryption()
```
so it's coming from the ClientAsyncAuthenticate_ServerRequireEncryption_ConnectWithEncryption test.

**Comment by stephentoub** [comment]
Another failure here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug_prtest/92/consoleText
This time in the ClientAsyncAuthenticate_IndividualServerVsAllClientSupportedProtocols_Success test.

**Comment by stephentoub** [comment]
Another failure here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug_prtest/96/consoleText
This time in ServerAllowNoEncryption_ClientNoEncryption_ConnectWithNoEncryption.

**Comment by stephentoub** [comment]
Another failure here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/55/consoleText
Again in ServerAllowNoEncryption_ClientNoEncryption_ConnectWithNoEncryption
```
Unhandled Exception: System.InvalidOperationException: Exception in DummyTcpServer created with stack:    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
     at System.Environment.get_StackTrace()
     at System.Environment.get_StackTrace()
     at System.Net.Security.Tests.DummyTcpServer..ctor(IPEndPoint endPoint, Nullable`1 sslEncryptionPolicy) in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Net.Security\tests\FunctionalTests\DummyTcpServer.cs:line 25
     at System.Net.Security.Tests.ServerAllowNoEncryptionTest.<ServerAllowNoEncryption_ClientNoEncryption_ConnectWithNoEncryption>d__5.MoveNext() in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Net.Security\tests\FunctionalTests\ServerAllowNoEncryptionTest.cs:line 81
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
     at System.Net.Security.Tests.ServerAllowNoEncryptionTest.ServerAllowNoEncryption_ClientNoEncryption_ConnectWithNoEncryption()
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 147
     at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 224
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<InvokeTestMethodAsync>b__1()
     at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction)
     at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code)
     at Xunit.Sdk.TestInvoker`1.<InvokeTestMethodAsync>d__46.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 208
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance)
     at Xunit.Sdk.TestInvoker`1.<<RunAsync>b__45_0>d.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 173
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.TestInvoker`1.<RunAsync>b__45_0()
     at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.core\Sdk\ExceptionAggregator.cs:line 107
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
     at Xunit.Sdk.XunitTestRunner.<InvokeTestAsync>d__4.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestRunner.cs:line 67
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator)
     at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.core\Sdk\ExceptionAggregator.cs:line 0
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
     at Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestRunner.cs:line 0
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.TestRunner`1.RunAsync()
     at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestCaseRunner.cs:line 82
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.TestCaseRunner`1.RunAsync()
     at Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestMethodRunner.cs:line 45
     at Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestMethodRunner.cs:line 136
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()
     at Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestMethodRunner.cs:line 106
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.TestMethodRunner`1.RunAsync()
     at Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__38.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestClassRunner.cs:line 205
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.RunWithDefaultContext()
     at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestMethodRunner.cs:line 124
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.RunWithDefaultContext()
     at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestMethodRunner.cs:line 142
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.RunWithDefaultContext()
     at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestCaseRunner.cs:line 99
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.RunWithDefaultContext()
     at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestRunner.cs:line 182
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.RunWithDefaultContext()
     at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.core\Sdk\ExceptionAggregator.cs:line 114
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.RunWithDefaultContext()
     at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at Xunit.Sdk.XunitTestRunner.<InvokeTestAsync>d__4.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestRunner.cs:line 76
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.RunWithDefaultContext()
     at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.core\Sdk\ExceptionAggregator.cs:line 114
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.RunWithDefaultContext()
     at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at Xunit.Sdk.TestInvoker`1.<<RunAsync>b__45_0>d.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 188
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.RunWithDefaultContext()
     at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at Xunit.Sdk.TestInvoker`1.<InvokeTestMethodAsync>d__46.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 245
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.RunWithDefaultContext()
     at Xunit.Sdk.AsyncTestSyncContext.<>c__DisplayClass7_0.<Post>b__1(Object _) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\AsyncTestSyncContext.cs:line 75
     at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs:line 107
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs:line 89
     at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _) in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitWorkerThread.cs:line 37
     at System.Threading.Tasks.Task.Execute()
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
     at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) ---> System.InvalidOperationException: This operation is only allowed using a successfully authenticated context.
     at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
     at System.Net.Security.SslState.get_SecureStream()
     at System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult)
     at System.Net.Security.Tests.DummyTcpServer.OnReceive(IAsyncResult result) in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Net.Security\tests\FunctionalTests\DummyTcpServer.cs:line 203
     --- End of inner exception stack trace ---
     at System.Net.Security.Tests.DummyTcpServer.OnReceive(IAsyncResult result) in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Net.Security\tests\FunctionalTests\DummyTcpServer.cs:line 240
     at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
     at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
     at System.Net.LazyAsyncResult.InvokeCallback(Object result)
     at System.Net.AsyncProtocolRequest.CompleteUser(Int32 userResult)
     at System.Net.Security.SslStreamInternal.StartFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
     at System.Net.Security.SslStreamInternal.ReadHeaderCallback(AsyncProtocolRequest asyncRequest)
     at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
     at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
     at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
     at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Net.ContextAwareResult.Complete(IntPtr userToken)
     at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
     at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```
