### ISSUE TITLE
TestFailure: System.Net.Mail.Functional.Tests

### ISSUE THREAD

**Issue by parjong** [dotnet/corefx#12944]
I encountered the following test failure while running ``System.Net.Mail.Functional.Tests`` unittest:
```
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.
Discovering: System.Net.Mail.Functional.Tests
Discovered:  System.Net.Mail.Functional.Tests
Starting:    System.Net.Mail.Functional.Tests
   System.Net.Mime.Tests.ContentDispositionTest.GetViaDateTimeProperty_WithUniversalTime_ShouldSetDateTimeKindAppropriately [FAIL]
      System.ArgumentOutOfRangeException : Hour, Minute, and Second parameters describe an un-representable DateTime.
      Stack Trace:
            at System.DateTime.TimeToTicks(Int32 hour, Int32 minute, Int32 second)
         /home/parjong/projects/dotnet/corefx/src/System.Net.Mail/tests/Functional/ContentDispositionTest.cs(255,0): at System.Net.Mime.Tests.ContentDispositionTest.GetViaDateTimeProperty_WithUniversalTime_ShouldSetDateTimeKindAppropriately()
   System.Net.Mime.Tests.ContentDispositionTest.SetDispositionViaConstructor_ShouldSetCorrectly_AndRespectCustomValues [FAIL]
      System.ArgumentOutOfRangeException : Hour, Minute, and Second parameters describe an un-representable DateTime.
      Stack Trace:
            at System.DateTime.TimeToTicks(Int32 hour, Int32 minute, Int32 second)
         /home/parjong/projects/dotnet/corefx/src/System.Net.Mail/tests/Functional/ContentDispositionTest.cs(323,0): at System.Net.Mime.Tests.ContentDispositionTest.SetDispositionViaConstructor_ShouldSetCorrectly_AndRespectCustomValues()
   System.Net.Mime.Tests.ContentDispositionTest.SetDateViaConstructor_ShouldPersistToPropertyAndPersistToParametersCollection [FAIL]
      System.ArgumentOutOfRangeException : Hour, Minute, and Second parameters describe an un-representable DateTime.
      Stack Trace:
            at System.DateTime.TimeToTicks(Int32 hour, Int32 minute, Int32 second)
         /home/parjong/projects/dotnet/corefx/src/System.Net.Mail/tests/Functional/ContentDispositionTest.cs(230,0): at System.Net.Mime.Tests.ContentDispositionTest.SetDateViaConstructor_ShouldPersistToPropertyAndPersistToParametersCollection()
Finished:    System.Net.Mail.Functional.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Mail.Functional.Tests  Total: 158, Errors: 0, Failed: 3, Skipped: 0, Time: 6.288s
```

**Comment by karelz** [comment]
@Priya91 it looks related to your Mail work ...

**Comment by stephentoub** [comment]
Closed by https://github.com/dotnet/corefx/pull/12945
