### ISSUE TITLE
Deserialization callback order in System.Runtime.Serialization.ObjectManager

### ISSUE THREAD

**Issue by unshorn** [dotnet/corefx#12941]
The  object listed here throws a Null reference exception on deserialization because the deserialization callbacks are raised from the outer object and then works its way in (causing an outer object to access an inner object that's not initialized yet.)

Is this by design or a bug?

`
var d = new Dictionary<HashSet<string>,string>(HashSet<string>.CreateSetComparer());
d.Add(new HashSet<string>() {"a"}, "a" );
d.Add(new HashSet<string>() {"b"}, "b");
`

See possible change to fix this in ObjectManager below:

```
        internal virtual void AddOnDeserialization(DeserializationEventHandler handler) {

// delete           m_onDeserializationHandler = (DeserializationEventHandler)Delegate.Combine(m_onDeserializationHandler, handler);
// add
           m_onDeserializationHandler = (DeserializationEventHandler)Delegate.Combine(handler, m_onDeserializationHandler);
        }
```

**Comment by karelz** [comment]
@shmao @huanwu can you please take a look?

**Comment by shmao** [comment]
@unshorn , thanks for opening the issue. What serializer did you use to serialize the object? Can you please provide a simple repro code for the issue? Thanks!

/cc: @stephentoub

**Comment by unshorn** [comment]
@shmao 
binary formatter
here's the sample code.

The exception thrown is:
Run-time exception (line 24): Object reference not set to an instance of an object.

Stack Trace:

[System.NullReferenceException: Object reference not set to an instance of an object.]
  at Program.Main(): line 24

```
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;
					
public class Program
{
	public static void Main()
	{
		// dictionary object to serialize
		var d = new Dictionary<HashSet<string>,string>(HashSet<string>.CreateSetComparer());
		d.Add(new HashSet<string>() {"a"}, "a" );
		d.Add(new HashSet<string>() {"b"}, "b");

		//serialize
		var outStream = new MemoryStream();
		var bf = new BinaryFormatter();
		bf.Serialize(outStream, d);
		Console.WriteLine("Serialized {0}", d);
		
		//deserialize
		var inStream = new MemoryStream(outStream.ToArray());
		var deserializedObject = bf.Deserialize(inStream);
		Console.WriteLine("Deserialized {0}", deserializedObject);
}
}
```

**Comment by pjanotti** [comment]
The exception is actually because `HashSet<string>.CreateSetComparer()` is not marked as serializable. If that parameter is removed and the default comparer is used, it worksboth in .Net Fx (4.7.2) and .NET Core 2.1. The error message in .Net Fx is really a null exception but in .NET CoreFx 2.1 you get the proper message:

```
Unhandled Exception: System.Runtime.Serialization.SerializationException: Type 'System.Collections.Generic.HashSetEqualityComparer`1[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' in Assembly 'System.Collections, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(Type type)
   at System.Runtime.Serialization.FormatterServices.<>c.<GetSerializableMembers>b__5_0(MemberHolder mh)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, BinaryFormatterWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Boolean check)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at Program.Main() in C:\s\tmp\BinSerializer\Program.cs:line 19
```

This doesn't meet the bar to be fixed in Fx (especially that is happening with the BinaryFormatter that shouldn't be used anymore).
