### ISSUE TITLE
FileInfo_OpenSpecial.FileShareOpen failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12993]
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug_prtest/73/consoleText

```
System.IO.Tests.FileInfo_OpenSpecial.FileShareOpen [FAIL]
        System.IO.IOException : The process cannot access the file 'C:\Users\dotnet-bot\AppData\Local\Temp\FileInfo_OpenSpecial_jdg4yjdx.tso\FileShareOpen_43' because it is being used by another process.
        Stack Trace:
              at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
              at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
              at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
              at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
              at System.IO.FileInfo.Open(FileMode mode, FileAccess access, FileShare share)
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.IO.FileSystem\tests\FileInfo\Open.cs(67,0): at System.IO.Tests.FileInfo_OpenSpecial.CreateFileStream(String path, FileMode mode, FileAccess access, FileShare share)
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.IO.FileSystem\tests\FileStream\ctor_str_fm_fa_fs.cs(56,0): at System.IO.Tests.FileStream_ctor_str_fm_fa_fs.FileShareOpen()
```

**Comment by karelz** [comment]
@JeremyKuhne @ianhays can you please take a look?

**Comment by alexperovich** [comment]
@stephentoub has this happened in CI again? I can't find any runs that are still around on Jenkins that failed with this error.

**Comment by stephentoub** [comment]
I haven't seen it again.  We can close it and reopen if we see it again.

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/7589/consoleText
```
System.IO.Tests.File_OpenSpecial.FileShareOpen [FAIL]
        System.IO.IOException : The process cannot access the file 'C:\Users\dotnet-bot\AppData\Local\Temp\File_OpenSpecial_ie1zdj3c.f4v\FileShareOpen_43' because it is being used by another process.
        Stack Trace:
              at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
              at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
              at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.IO.FileSystem\src\System\IO\File.cs(230,0): at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.IO.FileSystem\tests\File\Open.cs(68,0): at System.IO.Tests.File_OpenSpecial.CreateFileStream(String path, FileMode mode, FileAccess access, FileShare share)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.IO.FileSystem\tests\FileStream\ctor_str_fm_fa_fs.cs(53,0): at System.IO.Tests.FileStream_ctor_str_fm_fa_fs.FileShareOpen()
```

**Comment by karelz** [comment]
Given the low frequency, I'm fine with moving it to Future.
@JeremyKuhne @ianhays thoughts?

**Comment by stephentoub** [comment]
Happened again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug_prtest/60/
but after investigating further I believe I've got it nailed...

**Comment by karelz** [comment]
Moving to Future due to low frequency

**Comment by stephentoub** [comment]
> Moving to Future due to low frequency

I already have a PR out to fix it:
https://github.com/dotnet/corefx/issues/19529

**Comment by karelz** [comment]
Ah, I missed that, sorry.
