### ISSUE TITLE
GCNotifiicationTests failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12991]
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug_prtest/73/consoleText

```
Error - WaitForFullGCApproach result not Cancelled
  Exception from RemoteExecutorConsoleApp(System.Runtime.Tests, Version=4.2.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb, System.Tests.GCExtendedTests+<>c, <GCNotifiicationTests>b__3_0):
  Assembly: System.Runtime.Tests, Version=4.2.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
  Type: System.Tests.GCExtendedTests+<>c
  Method: Int32 <GCNotifiicationTests>b__3_0()
  Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.TrueException: Assert.True() Failure
  Expected: True
  Actual:   False
     at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\BooleanAsserts.cs:line 90
     at System.Tests.GCExtendedTests.<>c.<GCNotifiicationTests>b__3_0() in D:\j\workspace\outerloop_win---7ad0ce03\src\System.Runtime\tests\System\GCTests.netstandard1.7.cs:line 78
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
     at RemoteExecutorConsoleApp.Program.Main(String[] args)

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.TrueException: Assert.True() Failure
  Expected: True
  Actual:   False
     at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\BooleanAsserts.cs:line 90
     at System.Tests.GCExtendedTests.<>c.<GCNotifiicationTests>b__3_0() in D:\j\workspace\outerloop_win---7ad0ce03\src\System.Runtime\tests\System\GCTests.netstandard1.7.cs:line 78
     --- End of inner exception stack trace ---
     at RemoteExecutorConsoleApp.Program.Main(String[] args)

 System.Tests.GCExtendedTests.GCNotifiicationTests [FAIL]
        Assert.Equal() Failure
        Expected: 42
        Actual:   -532462766
        Stack Trace:
           D:\j\workspace\outerloop_win---7ad0ce03\src\Common\tests\System\Diagnostics\RemoteExecutorTestBase.cs(172,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Runtime\tests\System\GCTests.netstandard1.7.cs(76,0): at System.Tests.GCExtendedTests.GCNotifiicationTests()
```

**Comment by karelz** [comment]
@swgillespie can you please take a look? cc: @Maoni0 @sergiy-k

**Comment by swgillespie** [comment]
will do!

**Comment by swgillespie** [comment]
@karelz I haven't been able to repro this locally so I'm adding some additional logging for the next time this occurs.

**Comment by karelz** [comment]
Sounds goof, thanks!

**Comment by AlexGhiondea** [comment]
@swgillespie I am going to close this issue. If we see the test failing again we can either re-open it or file a new issue.
