### ISSUE TITLE
CI failure in DateTimeFormatInfoGetInstance.GetInstance_ExpectedCurrent

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#13003]
See https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/2074

```
MESSAGE:
Assert.Same() Failure\r\nExpected: DateTimeFormatInfo { AbbreviatedDayNames = [\"Sun\", \"Mon\", \"Tue\", \"Wed\", \"Thu\", ...], AbbreviatedMonthGenitiveNames = [\"Jan\", \"Feb\", \"Mar\", \"Apr\", \"May\", ...], AbbreviatedMonthNames = [\"Jan\", \"Feb\", \"Mar\", \"Apr\", \"May\", ...], AMDesignator = \"AM\", Calendar = GregorianCalendar { AlgorithmType = SolarCalendar, CalendarType = Localized, Eras = [...], IsReadOnly = True, MaxSupportedDateTime = 9999-12-31T23:59:59.9999999, ... }, ... }\r\nActual: DateTimeFormatInfo { AbbreviatedDayNames = [\"Sun\", \"Mon\", \"Tue\", \"Wed\", \"Thu\", ...], AbbreviatedMonthGenitiveNames = [\"Jan\", \"Feb\", \"Mar\", \"Apr\", \"May\", ...], AbbreviatedMonthNames = [\"Jan\", \"Feb\", \"Mar\", \"Apr\", \"May\", ...], AMDesignator = \"AM\", Calendar = GregorianCalendar { AlgorithmType = SolarCalendar, CalendarType = Localized, Eras = [...], IsReadOnly = True, MaxSupportedDateTime = 9999-12-31T23:59:59.9999999, ... }, ... }
+++++++++++++++++++
STACK TRACE:
at System.Globalization.Tests.DateTimeFormatInfoGetInstance.GetInstance_ExpectedCurrent() in D:\j\workspace\windows_nt_re---37265eab\src\System.Globalization\tests\DateTimeFormatInfo\DateTimeFormatInfoGetInstance.cs:line 46
```

**Comment by karelz** [comment]
cc @tarekgh

**Comment by tarekgh** [comment]
@bartdesmet I couldn't repro this issue and I am seeing the subsequent CI runs not failing with it. do you get this failure regularly?

**Comment by bartdesmet** [comment]
Just saw it once for a PR.

**Comment by tarekgh** [comment]
Thanks @bartdesmet. this failure looks so weird and this is first time I am seeing it. I am going to close this issue for now and if we got it again I'll spend more time digging deeper on it.

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu16.04_release/638/
```
System.Globalization.Tests.DateTimeFormatInfoGetInstance.GetInstance_ExpectedCurrent [FAIL]
        Assert.Same() Failure
        Expected: DateTimeFormatInfo { AbbreviatedDayNames = ["Sun", "Mon", "Tue", "Wed", "Thu", ...], AbbreviatedMonthGenitiveNames = ["Jan", "Feb", "Mar", "Apr", "May", ...], AbbreviatedMonthNames = ["Jan", "Feb", "Mar", "Apr", "May", ...], AMDesignator = "AM", Calendar = GregorianCalendar { AlgorithmType = SolarCalendar, CalendarType = Localized, Eras = [...], IsReadOnly = True, MaxSupportedDateTime = 9999-12-31T23:59:59.9999999, ... }, ... }
        Actual:   DateTimeFormatInfo { AbbreviatedDayNames = ["Sun", "Mon", "Tue", "Wed", "Thu", ...], AbbreviatedMonthGenitiveNames = ["Jan", "Feb", "Mar", "Apr", "May", ...], AbbreviatedMonthNames = ["Jan", "Feb", "Mar", "Apr", "May", ...], AMDesignator = "AM", Calendar = GregorianCalendar { AlgorithmType = SolarCalendar, CalendarType = Localized, Eras = [...], IsReadOnly = True, MaxSupportedDateTime = 9999-12-31T23:59:59.9999999, ... }, ... }
        Stack Trace:
           /mnt/j/workspace/dotnet_corefx/master/ubuntu16.04_release/src/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoGetInstance.cs(46,0): at System.Globalization.Tests.DateTimeFormatInfoGetInstance.GetInstance_ExpectedCurrent()
```

**Comment by danmosemsft** [comment]
@tarekgh if you believe your commit should have fixed this, please close. We will reopen if we see it again.
