### ISSUE TITLE
AccessViolationException in BigInteger tests

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#13063]
Possibly related to https://github.com/dotnet/corefx/issues/11771, but an AccessViolationException. Even when running out of memory, we shouldn't do that. Seems it needs a fix of its own. @mellinoe 

```
2016-10-26 14:02:46,792: INFO: proc(55): run_and_log_output: Output: Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
2016-10-26 14:02:46,792: INFO: proc(55): run_and_log_output: Output:    at System.Numerics.BigInteger.op_LeftShift(BigInteger value, Int32 shift)
2016-10-26 14:02:46,792: INFO: proc(55): run_and_log_output: Output:    at System.Numerics.Tests.logTest.LargeValueLogTests(Int32 startShift, Int32 bigShiftLoopLimit, Int32 smallShift, Int32 smallShiftLoopLimit)
```

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161026.02/workItem/System.Runtime.Numerics.Tests/details/736c97ed-fa83-4822-b30f-9350e3876764

**Comment by danmosemsft** [comment]
@mellinoe any update on this one? It fails in the full run so it's important to investigate (plus the fact random AV's are bad)

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161103.04/workItem/System.Runtime.Numerics.Tests/details/deb59c05-cbaf-4834-b929-6a1114c6d726

**Comment by danmosemsft** [comment]
This is not just Ubuntu. I have also seen it on Centos at least.

Unless it reproes locally, we need a way to get a dump from these machines.

**Comment by mellinoe** [comment]
Yeah, this most likely will not repro outside of those lab machines, so without access to them, I won't be able to get any more information most likely. This problem has never occurred in any of our runs in Jenkins, and I've never seen it locally.

**Comment by danmosemsft** [comment]
This text suggests to me that a dump was written -- @schaabs ?

```
2016-11-03 22:13:48,145: INFO: proc(55): run_and_log_output: Output: GDB was not found. Unable to print core file.
2016-11-03 22:13:48,147: INFO: proc(55): run_and_log_output: Output: Copying core file core to /tmp/coredumps
```

In which case the next step is @sepidehMS change to get dumps to upload to the Dumpling service.

**Comment by mellinoe** [comment]
I'm inclined to think there's nothing wrong here other than running out of memory.

From @janvorli:
>I have seen OOM manifestating itself as an access violation in the past. It was always due to a bug of not correctly handling failed allocation and instead using the pointer.

If we do have access to the dumps we might be able to get more information. But, I'm pretty sure the root cause is running out of memory, which should no longer happen since I changed the test to use less memory.

**Comment by danmosemsft** [comment]
Doh - you're right, of course that could cause an AV.
