### ISSUE TITLE
ProcessThreadTests.TestStartTimeProperty test failure in CI on Ubuntu

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#13210]
https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug/654/consoleText
```
System.Diagnostics.Tests.ProcessThreadTests.TestStartTimeProperty [FAIL]
        System.ComponentModel.Win32Exception : Unable to retrieve the specified information about the process or thread.  It may have exited or may be privileged.
        Stack Trace:
              at System.Diagnostics.ProcessThread.GetStat()
              at System.Diagnostics.ProcessThread.get_StartTime()
           /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug/src/System.Diagnostics.Process/tests/ProcessThreadTests.cs(106,0): at System.Diagnostics.Tests.ProcessThreadTests.<TestStartTimeProperty>d__3.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by joshfree** [comment]
reactivating and setting the milestone to 1.1 as this is failing in CI for the 1.1 servicing branch

**Comment by benaadams** [comment]
```
Ubuntu.1604.Amd64.Open-x64-Release
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.ContainsException
Message :
Assert.Contains() Failure
Not found: (filter expression)
In value:  <CastIterator>d__34<ProcessThread> [System.Diagnostics.ProcessThread, System.Diagnostics.ProcessThread, System.Diagnostics.ProcessThread, System.Diagnostics.ProcessThread, System.Diagnostics.ProcessThread, ...]
Stack Trace :
   at System.Diagnostics.Tests.ProcessThreadTests.<>c__DisplayClass3_2.<TestStartTimeProperty>b__0() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Diagnostics.Process/tests/ProcessThreadTests.cs:line 129
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /root/coreclr/src/mscorlib/shared/System/Threading/ExecutionContext.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) in /root/coreclr/src/mscorlib/src/System/Threading/Tasks/Task.cs:line 2440
--- End of stack trace from previous location where exception was thrown ---
   at System.Diagnostics.Tests.ProcessThreadTests.TestStartTimeProperty() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Diagnostics.Process/tests/ProcessThreadTests.cs:line 127
--- End of stack trace from previous location where exception was thrown --
```
in https://github.com/dotnet/corefx/pull/28688#issuecomment-377732880

**Comment by danmosemsft** [comment]
@joshfree we aren't energetically porting test fixes to 1.x as there's quite a few failures there. You can port #28852 if you want, or close this...

**Comment by joshfree** [comment]
We can won't fix it if you feel strongly; but anytime something fails in CI, we should open or reactivate an issue instead of ignoring it (like this).  Else we're going to drown under flaky tests.
