### ISSUE TITLE
Either ErrorMessageString or ErrorMessageResourceName must be set, but not both - provide hint which property

### ISSUE THREAD

**Issue by danroth27** [dotnet/corefx#13280]
_From @stefanhendriks on November 1, 2016 9:28_

This is happening on an API call (JSON serialization). From my perspective this problem 'suddendly' appears and I have no way of backtracking which property is causing this error message. 

Some background info:
- we have a filter that validates models before they enter the controller action
- when a validation error is found, we throw an exception and send a nice generic error response with per-field a validation message.

The stack trace is also not helpful:
```
System.InvalidOperationException: Either ErrorMessageString or ErrorMessageResourceName must be set, but not both.
   at System.ComponentModel.DataAnnotations.ValidationAttribute.SetupResourceAccessor()
   at System.ComponentModel.DataAnnotations.ValidationAttribute.get_ErrorMessageString()
   at System.ComponentModel.DataAnnotations.RegularExpressionAttribute.FormatErrorMessage(String name)
   at System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid(Object value, ValidationContext validationContext)
   at System.ComponentModel.DataAnnotations.ValidationAttribute.GetValidationResult(Object value, ValidationContext validationContext)
   at Microsoft.AspNetCore.Mvc.DataAnnotations.Internal.DataAnnotationsModelValidator.Validate(ModelValidationContext validationContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.ValidateNode()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultControllerArgumentBinder.<BindModelAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultControllerArgumentBinder.<BindArgumentsCoreAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAllActionFiltersAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeExceptionFilterAsync>d__25.MoveNext()
```

The only 'clue' we can derive is that ```Either ErrorMessageString or ErrorMessageResourceName must be set, but not both.```

Perhaps the exception / message can be expanded with the property name (and validator)?

_Copied from original issue: aspnet/Mvc#5478_

**Comment by danroth27** [comment]
_From @stefanhendriks on November 1, 2016 9:59_

I have found the property that was the culprit. Here is how I did it:
- I had a test that could reproduce this problem (hence it was the start of this journey ;-) )
- I turned off all validators (commented out)
- I re-ran the test to see it did not fail due the above error (it did fail for other reasons, because it checked if any validation was going on)
- I turned on validators per for a property 
- I Reran the test 
- I repeated above 2 steps until the test failed again due above error

Cumbersome yes. I noticed in the stack trace that a `ValidationVisitor` is in play, I suppose that one has enough context to provide more information when this error is thrown?

**Comment by danroth27** [comment]
It would be great if the validation attribute exception messages could give more context on the source of the validation error.

**Comment by stefanhendriks** [comment]
Thx for moving to the correct place @danroth27 . Mind it is not a validation error, but an exception thrown by the validator because of `Either ErrorMessageString or ErrorMessageResourceName must be set` - but it is impossible to derive from the stack trace which property/validator was the culprit. In that sense it is not a validation error (as in , property is invalid). Just wanted to make that a bit more clear.

**Comment by ajcvickers** [comment]
As stated above, this is not a validation error, but rather an application logic error (at some level) that is setting both properties. We are not planning to work on this, but we would consider a PR that makes the message better--for example, by including the ErrorMessageResourceName in the message. (We would not want to include the ErrorMessageString in the message just on the off-chance that it could contain sensitive data.) We would also consider changes that made the message better in some other way.

**Comment by ajcvickers** [comment]
Closing per previous message since we don't plan to implement this.
