### ISSUE TITLE
Queue_SynchronizedTests.SynchronizedEnqueue test failed

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#13356]
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_opensuse13.2_release/55/consoleText
```
System.Collections.Tests.Queue_SynchronizedTests.SynchronizedEnqueue [FAIL]
        System.AggregateException : One or more errors occurred. (Queue empty.)
        ---- System.InvalidOperationException : Queue empty.
        Stack Trace:
              at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
              at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
  Discovered:  System.Data.Common.Tests
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_opensuse13.2_release/src/System.Collections.NonGeneric/tests/QueueTests.cs(879,0): at System.Collections.Tests.Queue_SynchronizedTests.PerformTest(Action action, Int32 expected)
           ----- Inner Stack Trace -----
              at System.Collections.Queue.Dequeue()
              at System.Collections.Queue.SynchronizedQueue.Dequeue()
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_opensuse13.2_release/src/System.Collections.NonGeneric/tests/QueueTests.cs(932,0): at System.Collections.Tests.Queue_SynchronizedTests.StartDequeueEnqueueThread()
              at System.Threading.Tasks.Task.Execute()
```

**Comment by danmosemsft** [comment]
@ianhays @Priya91 could one of you please look. If this code hasn't changed recently, then this is a flaky repro as I haven't seen the failure before. In which case if you can't repro locally then you might want to add logging.

**Comment by stephentoub** [comment]
>  then this is a flaky repro

The test itself is simply bad, with race conditions that can lead to such failures.  I'm actually quite surprised we haven't seen it fail before.

**Comment by danmosemsft** [comment]
@Priya91 in the interests of keeping clean CI it would be great to fix this this week. Worst case disable with this issue #.
