### ISSUE TITLE
TimeZoneInfoTests.ConvertTime_DateTime_MiscUtc failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#13402]
Looks like a DST problem.
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/2686/consoleText
```
System.Tests.TimeZoneInfoTests.ConvertTime_DateTime_MiscUtc [FAIL]
        11/6/2016 8:01:17 AM failed to round trip using source 'UTC' and 'Pacific Standard Time' zones. wrong result 11/6/2016 9:01:17 AM
        Expected: True
        Actual:   False
        Stack Trace:
  Discovered:  System.Runtime.Performance.Tests
  Info:        System.Runtime.Performance.Tests has no tests to run
  Finished running tests.  End time= 1:01:17.51, Exit code = 0
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1930,0): at System.Tests.TimeZoneInfoTests.VerifyRoundTrip(DateTime dt1, String sourceTimeZoneId, String destinationTimeZoneId)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(799,0): at System.Tests.TimeZoneInfoTests.ConvertTime_DateTime_MiscUtc()
     System.Tests.TimeZoneInfoTests.ConvertTime_DateTime_MiscUtc [FAIL]
        11/6/2016 8:01:19 AM failed to round trip using source 'UTC' and 'Pacific Standard Time' zones. wrong result 11/6/2016 9:01:19 AM
        Expected: True
        Actual:   False
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(1930,0): at System.Tests.TimeZoneInfoTests.VerifyRoundTrip(DateTime dt1, String sourceTimeZoneId, String destinationTimeZoneId)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(799,0): at System.Tests.TimeZoneInfoTests.ConvertTime_DateTime_MiscUtc()
```

**Comment by karelz** [comment]
Could it be related to today's time change?

**Comment by JonHanna** [comment]
Almost certainly. It could be worse, spare a thought for those of us that live in places where local time and UTC are the same for half the year.

**Comment by stephentoub** [comment]
> Could it be related to today's time change?

Yes, that's why I said "Looks like a DST problem." ;)

**Comment by tarekgh** [comment]
I'll take a look
