### ISSUE TITLE
System.Net.Sockets.Tests threw Xunit.Sdk.EqualException

### ISSUE THREAD

**Issue by jiangzeng** [dotnet/corefx#13417]
No results generated.

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161104.503/workItem/System.Net.Sockets.Tests/details/c55351a7-8db1-4f95-9aba-4ccce51d4f64

```
2016-11-05 00:00:21,092: INFO: proc(55): run_and_log_output: Output: Unhandled Exception: Xunit.Sdk.EqualException: Assert.Equal() Failure
2016-11-05 00:00:21,092: INFO: proc(55): run_and_log_output: Output: Expected: Success
2016-11-05 00:00:21,092: INFO: proc(55): run_and_log_output: Output: Actual:   ConnectionReset
2016-11-05 00:00:21,092: INFO: proc(55): run_and_log_output: Output:    at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
2016-11-05 00:00:21,092: INFO: proc(55): run_and_log_output: Output:    at System.Net.Sockets.Tests.SocketAsyncExtensions.<>c__DisplayClass11_0.<ReceiveAsync>b__0(Object _, SocketAsyncEventArgs args)
2016-11-05 00:00:21,092: INFO: proc(55): run_and_log_output: Output:    at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
2016-11-05 00:00:21,092: INFO: proc(55): run_and_log_output: Output:    at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
2016-11-05 00:00:21,092: INFO: proc(55): run_and_log_output: Output:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2016-11-05 00:00:21,092: INFO: proc(55): run_and_log_output: Output:    at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
2016-11-05 00:00:21,092: INFO: proc(55): run_and_log_output: Output:    at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
2016-11-05 00:00:21,092: INFO: proc(55): run_and_log_output: Output:    at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
2016-11-05 00:00:21,092: INFO: proc(55): run_and_log_output: Output:    at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
2016-11-05 00:00:22,607: INFO: proc(55): run_and_log_output: Output: Finished running tests.  End time= 0:00:22.60, Exit code = -532462766
2016-11-05 00:00:22,607: INFO: proc(58): run_and_log_output: Exit Code: -532462766
2016-11-05 00:00:22,607: ERROR: scriptrunner(82): _main: Error: No exception thrown, but XUnit results not created
2016-11-05 00:00:22,607: ERROR: helix_test_execution(125): report_error: Error running xunit None

```

Build : Master - 20161104.503 (Core Tests)
Failing configurations: Windows.7.Amd64:AnyCPU-Debug

**Comment by Priya91** [comment]
Closing as old test result failure, not enough info in the bug to take action.
