### ISSUE TITLE
System.Net.Primitives.Performance.Tests threw System.MissingMethodException

### ISSUE THREAD

**Issue by jiangzeng** [dotnet/corefx#13416]
No results generated.

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161104.503/workItem/System.Net.Primitives.Performance.Test

```
2016-11-04 23:52:42,651: INFO: proc(55): run_and_log_output: Output: Unhandled Exception: System.MissingMethodException: Method not found: 'Void System.IO.FileStream..ctor(System.String, System.IO.FileMode)'.
2016-11-04 23:52:42,651: INFO: proc(55): run_and_log_output: Output:    at Xunit.ConsoleClient.Program.Main(String[] args)
2016-11-04 23:52:43,838: INFO: proc(55): run_and_log_output: Output: Finished running tests.  End time=23:52:43.83, Exit code = -532462766
2016-11-04 23:52:43,841: INFO: proc(58): run_and_log_output: Exit Code: -532462766
2016-11-04 23:52:43,842: ERROR: scriptrunner(82): _main: Error: No exception thrown, but XUnit results not created
2016-11-04 23:52:43,842: ERROR: helix_test_execution(125): report_error: Error running xunit None
```

Build : Master - 20161104.503 (Core Tests)
Failing configurations: Failing on all platforms.

**Comment by stephentoub** [comment]
This looks like there was something wrong with the build.  The error isn't coming from the networking tests, it's coming from xunit itself.  And it's an error about not being able to find the FileStream ctor:
```
2016-11-04 23:52:42,651: INFO: proc(55): run_and_log_output: Output: Unhandled Exception: System.MissingMethodException: Method not found: 'Void System.IO.FileStream..ctor(System.String, System.IO.FileMode)'.
2016-11-04 23:52:42,651: INFO: proc(55): run_and_log_output: Output:    at Xunit.ConsoleClient.Program.Main(String[] args)
```

**Comment by danmosemsft** [comment]
@JeremyKuhne could this be related to your filestream work?

**Comment by mellinoe** [comment]
@danmosemsft Are you guys still seeing this in the helix runs or was this a sort of one-off thing?

**Comment by danmosemsft** [comment]
I've asked @jiangzeng to close this if he doesn't see it repro for a couple of builds.

**Comment by jiangzeng** [comment]
Close. Checked in recent builds from 20161107.502, it's not happening.
