### ISSUE TITLE
System.Runtime.Numerics.Tests threw OutOfMemoryException

### ISSUE THREAD

**Issue by jiangzeng** [dotnet/corefx#13455]
No test results generated.
Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161107.502/workItem/System.Runtime.Numerics.Tests/details/21670e64-2ea5-45bb-ab05-6865c589e68b

```
2016-11-08 01:16:59,881: INFO: proc(55): run_and_log_output: Output: Unhandled Exception: OutOfMemoryException.
2016-11-08 01:17:47,127: INFO: proc(55): run_and_log_output: Output: /home/helixbot/dotnetbuild/work/21670e64-2ea5-45bb-ab05-6865c589e68b/Work/613149c7-69a9-42ca-9740-de748dc06a08/Unzip/RunTests.sh: line 285:  7148 Aborted                 (core dumped) ./corerun xunit.console.netcore.exe System.Runtime.Numerics.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests -notrait category=requireselevation -notrait category=failing -notrait category=nonlinuxtests
2016-11-08 01:17:47,128: INFO: proc(55): run_and_log_output: Output: Finished running tests. End time=01:17:47. Return value was 134

```

Build : Master - 20161107.502 (Core Tests)
 Failing configurations: Centos.71.Amd64:AnyCPU-Release

**Comment by danmosemsft** [comment]
Hopefully this build didn't have @mellinoe's fix 998a0227. Eric is there a trick to know which commit a build synced to?

**Comment by mellinoe** [comment]
I don't know, I'm not familiar with how these test runs work. I guess if we knew the start time we could figure out what commit was latest at that point.

**Comment by danmosemsft** [comment]
I assumed what mattered was the build number 20161107.502..

**Comment by jiangzeng** [comment]
Close. Checked in recent builds from 20161108.502, it's not happening.

**Comment by jiangzeng** [comment]
Reopen as happening again on build 20161204.02.
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161204.02/workItem/System.Runtime.Numerics.Tests/details/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2
```
2016-12-04 15:30:36,600: INFO: proc(55): run_and_log_output: Output: Unhandled Exception: OutOfMemoryException.
2016-12-04 15:31:09,729: INFO: proc(55): run_and_log_output: Output: /home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip/RunTests.sh: line 287: 14366 Aborted                 (core dumped) ./corerun xunit.console.netcore.exe System.Runtime.Numerics.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests -notrait category=requireselevation -notrait category=failing -notrait category=nonlinuxtests
2016-12-04 15:31:09,729: INFO: proc(55): run_and_log_output: Output: Finished running tests. End time=15:31:09. Return value was 134
```

**Comment by danmosemsft** [comment]
@mellinoe ...

**Comment by mellinoe** [comment]
Hm, I wonder which test case it was on this time? I'd have to do some more digging to figure that out.

**Comment by AlexGhiondea** [comment]
@mellinoe I am assigning this to you -- could you take a look?

**Comment by mellinoe** [comment]
I'll need to find some time to investigate this. It would help if we could tell which test case was allocating too much, otherwise it's hard to tell what to fix.

**Comment by danmosemsft** [comment]
@jiangzeng whenever this fails, please take a look at the log to see whether there is any clue which individual test failed. How often is it failing?

**Comment by jiangzeng** [comment]
@danmosemsft I did not see it in recent runs.
@Jiayili1 Please help to double check.

**Comment by jiangzeng** [comment]
The latest build we can see it should be 20161204.02. For logs, please check:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161204.02/workItem/System.Runtime.Numerics.Tests/details/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2

```
2016-12-04 15:30:11,072: INFO: scriptrunner(28): _main: BuildTools Helix Script Runner v0.1 starting
2016-12-04 15:30:11,072: INFO: helix_test_execution(24): __init__: Copying execution payload files from /home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip to /home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Exec/execution
2016-12-04 15:30:11,073: INFO: io(27): copy_tree_to: Copying '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip/System.Runtime.Numerics.Tests.pdb' to '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Exec/execution/System.Runtime.Numerics.Tests.pdb'
2016-12-04 15:30:11,073: INFO: io(27): copy_tree_to: Copying '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip/project.lock.json' to '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Exec/execution/project.lock.json'
2016-12-04 15:30:11,083: INFO: io(27): copy_tree_to: Copying '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip/RunTests.sh' to '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Exec/execution/RunTests.sh'
2016-12-04 15:30:11,084: INFO: io(27): copy_tree_to: Copying '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip/project.json' to '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Exec/execution/project.json'
2016-12-04 15:30:11,084: INFO: io(27): copy_tree_to: Copying '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip/System.Runtime.Numerics.Tests.dll' to '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Exec/execution/System.Runtime.Numerics.Tests.dll'
2016-12-04 15:30:11,085: INFO: io(27): copy_tree_to: Copying '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip/test-runtime/project.json' to '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Exec/execution/test-runtime/project.json'
2016-12-04 15:30:11,086: INFO: proc(23): run_and_log_output: Running: /home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip/RunTests.sh /home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Payload
2016-12-04 15:30:11,086: INFO: proc(26): run_and_log_output: CWD: /home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip
2016-12-04 15:30:11,089: INFO: proc(55): run_and_log_output: Output: Using /home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Payload as folder for resolving package dependencies.
2016-12-04 15:30:11,090: INFO: proc(55): run_and_log_output: Output: Executing in /home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip
2016-12-04 15:30:11,090: INFO: proc(55): run_and_log_output: Output: Hard linking dependent files...
2016-12-04 15:30:11,383: INFO: proc(55): run_and_log_output: Output: Finished linking needed files, moving to running tests.
2016-12-04 15:30:11,385: INFO: proc(55): run_and_log_output: Output: Running tests... Start time: 15:30:11
2016-12-04 15:30:11,385: INFO: proc(55): run_and_log_output: Output: Commands:
2016-12-04 15:30:11,386: INFO: proc(55): run_and_log_output: Output: ./corerun xunit.console.netcore.exe System.Runtime.Numerics.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests -notrait category=requireselevation -notrait category=failing -notrait category=nonlinuxtests
2016-12-04 15:30:11,461: INFO: proc(55): run_and_log_output: Output: xUnit.net console test runner (64-bit .NET Core)
2016-12-04 15:30:11,461: INFO: proc(55): run_and_log_output: Output: Copyright (C) 2014 Outercurve Foundation.
2016-12-04 15:30:11,461: INFO: proc(55): run_and_log_output: Output: 
2016-12-04 15:30:11,576: INFO: proc(55): run_and_log_output: Output: Discovering: System.Runtime.Numerics.Tests
2016-12-04 15:30:11,825: INFO: proc(55): run_and_log_output: Output: Discovered:  System.Runtime.Numerics.Tests
2016-12-04 15:30:11,934: INFO: proc(55): run_and_log_output: Output: Starting:    System.Runtime.Numerics.Tests
2016-12-04 15:30:36,600: INFO: proc(55): run_and_log_output: Output: 
2016-12-04 15:30:36,600: INFO: proc(55): run_and_log_output: Output: Unhandled Exception: OutOfMemoryException.
2016-12-04 15:31:09,729: INFO: proc(55): run_and_log_output: Output: /home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip/RunTests.sh: line 287: 14366 Aborted                 (core dumped) ./corerun xunit.console.netcore.exe System.Runtime.Numerics.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests -notrait category=requireselevation -notrait category=failing -notrait category=nonlinuxtests
2016-12-04 15:31:09,729: INFO: proc(55): run_and_log_output: Output: Finished running tests. End time=15:31:09. Return value was 134
2016-12-04 15:31:09,731: INFO: proc(55): run_and_log_output: Output: GDB was not found. Unable to print core file.
2016-12-04 15:31:09,733: INFO: proc(55): run_and_log_output: Output: Copying core file core to /tmp/coredumps
2016-12-04 15:31:31,253: INFO: proc(58): run_and_log_output: Exit Code: 134
2016-12-04 15:31:31,253: ERROR: scriptrunner(82): _main: Error: No exception thrown, but XUnit results not created
2016-12-04 15:31:31,254: ERROR: helix_test_execution(125): report_error: Error running xunit None
```

**Comment by Jiayili1** [comment]
@danmosemsft On build 20161222.03, this issue is repro, please check: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161222.03/workItem/System.Runtime.Numerics.Tests/details/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2

```
2016-12-04 15:30:11,072: INFO: scriptrunner(28): _main: BuildTools Helix Script Runner v0.1 starting
2016-12-04 15:30:11,072: INFO: helix_test_execution(24): __init__: Copying execution payload files from /home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip to /home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Exec/execution
2016-12-04 15:30:11,073: INFO: io(27): copy_tree_to: Copying '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip/System.Runtime.Numerics.Tests.pdb' to '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Exec/execution/System.Runtime.Numerics.Tests.pdb'
2016-12-04 15:30:11,073: INFO: io(27): copy_tree_to: Copying '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip/project.lock.json' to '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Exec/execution/project.lock.json'
2016-12-04 15:30:11,083: INFO: io(27): copy_tree_to: Copying '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip/RunTests.sh' to '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Exec/execution/RunTests.sh'
2016-12-04 15:30:11,084: INFO: io(27): copy_tree_to: Copying '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip/project.json' to '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Exec/execution/project.json'
2016-12-04 15:30:11,084: INFO: io(27): copy_tree_to: Copying '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip/System.Runtime.Numerics.Tests.dll' to '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Exec/execution/System.Runtime.Numerics.Tests.dll'
2016-12-04 15:30:11,085: INFO: io(27): copy_tree_to: Copying '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip/test-runtime/project.json' to '/home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Exec/execution/test-runtime/project.json'
2016-12-04 15:30:11,086: INFO: proc(23): run_and_log_output: Running: /home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip/RunTests.sh /home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Payload
2016-12-04 15:30:11,086: INFO: proc(26): run_and_log_output: CWD: /home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip
2016-12-04 15:30:11,089: INFO: proc(55): run_and_log_output: Output: Using /home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Payload as folder for resolving package dependencies.
2016-12-04 15:30:11,090: INFO: proc(55): run_and_log_output: Output: Executing in /home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip
2016-12-04 15:30:11,090: INFO: proc(55): run_and_log_output: Output: Hard linking dependent files...
2016-12-04 15:30:11,383: INFO: proc(55): run_and_log_output: Output: Finished linking needed files, moving to running tests.
2016-12-04 15:30:11,385: INFO: proc(55): run_and_log_output: Output: Running tests... Start time: 15:30:11
2016-12-04 15:30:11,385: INFO: proc(55): run_and_log_output: Output: Commands:
2016-12-04 15:30:11,386: INFO: proc(55): run_and_log_output: Output: ./corerun xunit.console.netcore.exe System.Runtime.Numerics.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests -notrait category=requireselevation -notrait category=failing -notrait category=nonlinuxtests
2016-12-04 15:30:11,461: INFO: proc(55): run_and_log_output: Output: xUnit.net console test runner (64-bit .NET Core)
2016-12-04 15:30:11,461: INFO: proc(55): run_and_log_output: Output: Copyright (C) 2014 Outercurve Foundation.
2016-12-04 15:30:11,461: INFO: proc(55): run_and_log_output: Output: 
2016-12-04 15:30:11,576: INFO: proc(55): run_and_log_output: Output: Discovering: System.Runtime.Numerics.Tests
2016-12-04 15:30:11,825: INFO: proc(55): run_and_log_output: Output: Discovered:  System.Runtime.Numerics.Tests
2016-12-04 15:30:11,934: INFO: proc(55): run_and_log_output: Output: Starting:    System.Runtime.Numerics.Tests
2016-12-04 15:30:36,600: INFO: proc(55): run_and_log_output: Output: 
2016-12-04 15:30:36,600: INFO: proc(55): run_and_log_output: Output: Unhandled Exception: OutOfMemoryException.
2016-12-04 15:31:09,729: INFO: proc(55): run_and_log_output: Output: /home/helixbot/dotnetbuild/work/db65a0ea-d46d-4ffb-8a3b-19f86890f1a2/Work/809f420b-3ecb-4d0e-af13-301ba99cc69c/Unzip/RunTests.sh: line 287: 14366 Aborted                 (core dumped) ./corerun xunit.console.netcore.exe System.Runtime.Numerics.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests -notrait category=requireselevation -notrait category=failing -notrait category=nonlinuxtests
2016-12-04 15:31:09,729: INFO: proc(55): run_and_log_output: Output: Finished running tests. End time=15:31:09. Return value was 134
2016-12-04 15:31:09,731: INFO: proc(55): run_and_log_output: Output: GDB was not found. Unable to print core file.
2016-12-04 15:31:09,733: INFO: proc(55): run_and_log_output: Output: Copying core file core to /tmp/coredumps
2016-12-04 15:31:31,253: INFO: proc(58): run_and_log_output: Exit Code: 134
2016-12-04 15:31:31,253: ERROR: scriptrunner(82): _main: Error: No exception thrown, but XUnit results not created
2016-12-04 15:31:31,254: ERROR: helix_test_execution(125): report_error: Error running xunit None
```

**Comment by danmosemsft** [comment]
@sepidehMS we need core dumps ..

**Comment by Jiayili1** [comment]
In build 20161228.03, this issue is repro, test System.Numerics.Tests.cast_fromTest/RunDoubleExplicitCastFromLargeBigIntegerTests failed with System.OutOfMemoryException

Details: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161228.03/workItem/System.Runtime.Numerics.Tests/analysis/xunit/System.Numerics.Tests.cast_fromTest~2FRunDoubleExplicitCastFromLargeBigIntegerTests

Message:
~~~
System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
~~~

Stack Trace:
~~~
at System.Numerics.BigInteger..ctor(UInt32[] value, Boolean negative)
   at System.Numerics.BigInteger.op_LeftShift(BigInteger value, Int32 shift)
   at System.Numerics.Tests.cast_fromTest.DoubleExplicitCastFromLargeBigIntegerTests(Int32 startShift, Int32 bigShiftLoopLimit, Int32 smallShift, Int32 smallShiftLoopLimit)
   at System.Numerics.Tests.cast_fromTest.RunDoubleExplicitCastFromLargeBigIntegerTests()
~~~

**Comment by danmosemsft** [comment]
@sepidehMS can you please enable core dumps and get one to Eric?

**Comment by mellinoe** [comment]
I don't think we should be seeing any more OOM's.

**Comment by karelz** [comment]
@mellinoe just curious why you don't think we will see them? Did you change the tests? Or some infra changed?

**Comment by mellinoe** [comment]
I did make some fixes, although I'm not positive that it's all fixed. I was assuming I'd get more "pings" if this kept happening, but maybe we just started ignoring them since this issue is open.

@Jiayili1 Are we still hitting these?

**Comment by karelz** [comment]
@mellinoe if you did some fixes, we can close it and wait for new occurrences to reopen the issue/file a new one - or we can wait for reply from @Jiayili1 ... up to you ;-)
Thanks! (I was truly just curious, no push back meant)

**Comment by Jiayili1** [comment]
@mellinoe @karelz This issue doesn't occur on recent builds, I will check it on 20170309.03 if the build is finished.

**Comment by karelz** [comment]
@Jiayili1 thanks for confirmation! Closing. Let's reopen if it happens again.
I assume no tests are disabled against it.
