### ISSUE TITLE
Some isolated storage tests failed with UnauthorizedAccessException 

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#13474]
20 of the isolated storage tests failed when running with a clean repo, build from root. All are failing because they can't access the path below. The path doesn't exist after the tests are done but if I try to create it myself with CreateDirectory, there is no problem. After cleaning the isolated storage folder the tests pass.

```            System.IO.IsolatedStorage.MoveFileTests.MoveFile_MoveOver(scope: UserStoreForAssembly) [FAIL]
               System.UnauthorizedAccessException : Access to the path 'C:\Users\danmose\AppData\Local\IsolatedStorage\onb3nvpa.ama\a3ve4vgl.zmh\StrongName.523eyfdtenor3l0btjpf240vsoo5jc3i\AssemFiles\' is denied.
               Stack Trace:
                     at System.IO.Win32FileSystem.CreateDirectory(String fullPath)
                     at System.IO.Directory.CreateDirectory(String path)
                     at System.IO.IsolatedStorage.Helper.CreateDirectory(String path, IsolatedStorageScope scope)
                     at System.IO.IsolatedStorage.IsolatedStorageFile.Initialize(IsolatedStorageScope scope)
                     at System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(IsolatedStorageScope scope)
                     at System.IO.IsolatedStorage.IsolatedStorageFile.GetUserStoreForAssembly()
                  C:\git\corefx.dan\src\System.IO.IsolatedStorage\tests\System\IO\IsolatedStorage\IsoStorageTest.cs(52,0): at System.IO.IsolatedStorage.IsoStorageTest.GetPresetScope(PresetScopes scope)
                  C:\git\corefx.dan\src\System.IO.IsolatedStorage\tests\System\IO\IsolatedStorage\MoveFileTests.cs(86,0): at System.IO.IsolatedStorage.MoveFileTests.MoveFile_MoveOver(PresetScopes scope)
```

@JeremyKuhne

**Comment by JeremyKuhne** [comment]
@danmosemsft Something is probably holding an exclusive handle. Have you reproduced this anywhere else or seen it from a CI? If you can get it to fail consistently you might be able to catch who has the open handle to C:\Users\danmose\AppData\Local\IsolatedStorage or lower.

**Comment by danmosemsft** [comment]
i've only seen it once, locally. i'll close this until I can get that info in a future repro.

**Comment by danmosemsft** [comment]
Hit again with MoveFileOver and RemoveStoreWithContent tests

**Comment by danmosemsft** [comment]
This needs running in a loop locally with ProcMon running.

**Comment by danmosemsft** [comment]
Again
```

    System.IO.IsolatedStorage.OpenFileTests.OpenFile_ThrowsIsolatedStorageException [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.IO.IsolatedStorage.IsolatedStorageException)
        Actual:   typeof(System.InvalidOperationException): Store must be open for this operation.
        Stack Trace:

  === TEST EXECUTION SUMMARY ===
           C:\git\corefx.dan\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\IsolatedStorageFile.cs(665,0): at System.IO.IsolatedStorage.IsolatedStorageFi
  le.EnsureStoreIsValid()
           C:\git\corefx.dan\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\IsolatedStorageFile.cs(238,0): at System.IO.IsolatedStorage.IsolatedStorageFi
  le.OpenFile(String path, FileMode mode)
           C:\git\corefx.dan\src\System.IO.IsolatedStorage\tests\System\IO\IsolatedStorage\OpenFileTests.cs(28,0): at System.IO.IsolatedStorage.OpenFileTests.<>c__Dis
  playClass1_0.<OpenFile_ThrowsIsolatedStorageException>b__0()
     System.IO.IsolatedStorage.OpenFileTests.OpenFile_Existence(scope: MachineStoreForAssembly) [FAIL]
        System.UnauthorizedAccessException : Access to the path 'C:\usr\local\share\IsolatedStorage\qzfnebsg.bpn\bydytht5.hfg\StrongName.523eyfdtenor3l0btjpf240vsoo5j
  c3i\AssemFiles\' is denied.
        Stack Trace:
  Finished running tests.  End time=10:17:21.80, Exit code = 0
              at System.IO.Win32FileSystem.CreateDirectory(String fullPath)
              at System.IO.Directory.CreateDirectory(String path)
           C:\git\corefx.dan\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\Helper.Win32.Unix.cs(50,0): at System.IO.IsolatedStorage.Helper.CreateDirecto
  ry(String path, IsolatedStorageScope scope)
           C:\git\corefx.dan\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\IsolatedStorageFile.cs(629,0): at System.IO.IsolatedStorage.IsolatedStorageFi
  le.Initialize(IsolatedStorageScope scope)
           C:\git\corefx.dan\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\IsolatedStorageFile.cs(546,0): at System.IO.IsolatedStorage.IsolatedStorageFi
  le.GetStore(IsolatedStorageScope scope)
           C:\git\corefx.dan\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\IsolatedStorageFile.cs(535,0): at System.IO.IsolatedStorage.IsolatedStorageFi
  le.GetMachineStoreForAssembly()
           C:\git\corefx.dan\src\System.IO.IsolatedStorage\tests\System\IO\IsolatedStorage\IsoStorageTest.cs(58,0): at System.IO.IsolatedStorage.IsoStorageTest.GetPre
  setScope(PresetScopes scope)
           C:\git\corefx.dan\src\System.IO.IsolatedStorage\tests\System\IO\IsolatedStorage\OpenFileTests.cs(135,0): at System.IO.IsolatedStorage.OpenFileTests.OpenFil
  e_Existence(PresetScopes scope)
```

I'm surprised it's trying to access this path on my Windows box; `'C:\usr\local\share\IsolatedStorage\qzfnebsg.bpn\bydytht5.hfg\StrongName.523eyfdtenor3l0btjpf240vsoo5j
  c3i\AssemFiles\'` @JeremyKuhne is that right?

**Comment by JeremyKuhne** [comment]
@danmosemsft Ugh, a line got left in. Removing it. Orthogonal to your other issue I think.

**Comment by danmosemsft** [comment]
I'll close this until I have a chance to verify it still happens. Doesn't hit CI

**Comment by danmosemsft** [comment]
AGain
```
      <test name="System.IO.IsolatedStorage.MoveFileTests.MoveFile_MovesFile(scope: MachineStoreForDomain)" type="System.IO.IsolatedStorage.MoveFileTests" method="MoveFile_MovesFile" time="0.0024432" result="Fail">
        <failure exception-type="System.UnauthorizedAccessException">
          <message><![CDATA[System.UnauthorizedAccessException : Access to the path 'C:\\ProgramData\\IsolatedStorage\\2s1ponqi.naj\\zibepoq1.x3z\\StrongName.523eyfdtenor3l0btjpf240vsoo5jc3i\\StrongName.523eyfdtenor3l0btjpf240vsoo5jc3i\\Files\\' is denied.]]></message>
          <stack-trace><![CDATA[   at System.IO.Win32FileSystem.CreateDirectory(String fullPath) in C:\git\corefx.dan\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 170
   at System.IO.Directory.CreateDirectory(String path) in C:\git\corefx.dan\src\System.IO.FileSystem\src\System\IO\Directory.cs:line 51
   at System.IO.IsolatedStorage.Helper.CreateDirectory(String path, IsolatedStorageScope scope) in C:\git\corefx.dan\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\Helper.Win32.Unix.cs:line 50
   at System.IO.IsolatedStorage.IsolatedStorageFile.Initialize(IsolatedStorageScope scope) in C:\git\corefx.dan\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\IsolatedStorageFile.cs:line 629
   at System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(IsolatedStorageScope scope) in C:\git\corefx.dan\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\IsolatedStorageFile.cs:line 546
   at System.IO.IsolatedStorage.IsolatedStorageFile.GetMachineStoreForDomain() in C:\git\corefx.dan\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\IsolatedStorageFile.cs:line 540
   at System.IO.IsolatedStorage.IsoStorageTest.GetPresetScope(PresetScopes scope) in C:\git\corefx.dan\src\System.IO.IsolatedStorage\tests\System\IO\IsolatedStorage\IsoStorageTest.cs:line 60
   at System.IO.IsolatedStorage.MoveFileTests.MoveFile_MovesFile(PresetScopes scope) in C:\git\corefx.dan\src\System.IO.IsolatedStorage\tests\System\IO\IsolatedStorage\MoveFileTests.cs:line 99]]></stack-trace>
        </failure>
```

**Comment by danmosemsft** [comment]
Are tests in different classes using the same folder and running concurrently? Eg this failed also

```
      <test name="System.IO.IsolatedStorage.MoveDirectoryTests.MoveDirectory_MoveOver(scope: MachineStoreForDomain)" type="System.IO.IsolatedStorage.MoveDirectoryTests" method="MoveDirectory_MoveOver" time="0.002476" result="Fail">
        <failure exception-type="System.UnauthorizedAccessException">
          <message><![CDATA[System.UnauthorizedAccessException : Access to the path 'C:\\ProgramData\\IsolatedStorage\\2s1ponqi.naj\\zibepoq1.x3z\\StrongName.523eyfdtenor3l0btjpf240vsoo5jc3i\\StrongName.523eyfdtenor3l0btjpf240vsoo5jc3i\\Files\\' is denied.]]></message>
          <stack-trace><![CDATA[   at System.IO.Win32FileSystem.CreateDirectory(String fullPath) in C:\git\corefx.dan\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 170
   at System.IO.Directory.CreateDirectory(String path) in C:\git\corefx.dan\src\System.IO.FileSystem\src\System\IO\Directory.cs:line 51
   at System.IO.IsolatedStorage.Helper.CreateDirectory(String path, IsolatedStorageScope scope) in C:\git\corefx.dan\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\Helper.Win32.Unix.cs:line 50
   at System.IO.IsolatedStorage.IsolatedStorageFile.Initialize(IsolatedStorageScope scope) in C:\git\corefx.dan\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\IsolatedStorageFile.cs:line 629
   at System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(IsolatedStorageScope scope) in C:\git\corefx.dan\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\IsolatedStorageFile.cs:line 546
   at System.IO.IsolatedStorage.IsolatedStorageFile.GetMachineStoreForDomain() in C:\git\corefx.dan\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\IsolatedStorageFile.cs:line 540
   at System.IO.IsolatedStorage.IsoStorageTest.GetPresetScope(PresetScopes scope) in C:\git\corefx.dan\src\System.IO.IsolatedStorage\tests\System\IO\IsolatedStorage\IsoStorageTest.cs:line 60
   at System.IO.IsolatedStorage.MoveDirectoryTests.MoveDirectory_MoveOver(PresetScopes scope) in C:\git\corefx.dan\src\System.IO.IsolatedStorage\tests\System\IO\IsolatedStorage\MoveDirectoryTests.cs:line 88]]></stack-trace>
        </failure>
      </test>
```

@JeremyKuhne

**Comment by danmosemsft** [comment]
6 failed this way -- it seems unlikely all of them ran at once. Perhaps virus checking? I'll disable Forefrunt for `C:\\ProgramData\\IsolatedStorage`.

Question remains though about why the tests are apparently all using the same folder.

**Comment by JeremyKuhne** [comment]
They're supposed to use the same folder- it isn't configurable (not without Evidence, which we don't have). The tests are set to not run in parallel because of this. (The assembly is attributed.)

**Comment by danmosemsft** [comment]
OK, I"ll see if it reproes now I've e3xcluded the folder.
