### ISSUE TITLE
Three X509Certificates / SecureString tests failing

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#13471]
```
System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestConstructor_SecureString(keyStorageFlags: DefaultKeySet) [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : The specified network password is not correct
        Stack Trace:
              at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
              at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
              at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
              at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, SecureString password, X509KeyStorageFlags keyStorageFlags)
              at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, SecureString password, X509KeyStorageFlags keyStorageFlags)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Security.Cryptography.X509Certificates\tests\PfxTests.cs(48,0): at System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestConstructor_SecureString(X509KeyStorageFlags keyStorageFlags)
     System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestConstructor_SecureString(keyStorageFlags: EphemeralKeySet) [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : The specified network password is not correct
        Stack Trace:
              at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
              at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
              at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
              at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, SecureString password, X509KeyStorageFlags keyStorageFlags)
              at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, SecureString password, X509KeyStorageFlags keyStorageFlags)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Security.Cryptography.X509Certificates\tests\PfxTests.cs(48,0): at System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestConstructor_SecureString(X509KeyStorageFlags keyStorageFlags)
     System.Security.Cryptography.X509Certificates.Tests.CollectionTests.ExportCert_SecureString [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : The specified network password is not correct
        Stack Trace:
              at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
              at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
              at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
              at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, SecureString password, X509KeyStorageFlags keyStorageFlags)
              at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, SecureString password, X509KeyStorageFlags keyStorageFlags)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Security.Cryptography.X509Certificates\tests\CollectionTests.cs(1393,0): at System.Security.Cryptography.X509Certificates.Tests.CollectionTests.TestExportSingleCert_SecureStringPassword(X509ContentType ct)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Security.Cryptography.X509Certificates\tests\CollectionTests.cs(647,0): at System.Security.Cryptography.X509Certificates.Tests.CollectionTests.ExportCert_SecureString()
```

**Comment by danmosemsft** [comment]
@steveharter

**Comment by danmosemsft** [comment]
SecureString again.

**Comment by steveharter** [comment]
@AlexGhiondea looks like the marshal methods return null now (and I'm assuming should just be removed since implemented in core now):
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.InteropServices/src/System/Security/SecureStringMarshal.CoreCLR.cs#L10-L13

**Comment by stephentoub** [comment]
Already fixed:
#13473

**Comment by danmosemsft** [comment]
is there more to this or is it fixed by the above?

**Comment by stephentoub** [comment]
> is there more to this or is it fixed by the above?

We need updated packages to then re-enable the tests.
