### ISSUE TITLE
TestCopyConstructor_Lifetime_Cloned failed in ci - OpenCSP failed with error code 2148073494.

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#13501]
this code seems to be [keyset does not exist](http://index/?query=0x80090016&rightProject=mscorlib&file=system%5Csecurity%5Ccryptography%5Cutils.cs&line=54)

```
14:49:38      System.Security.Cryptography.X509Certificates.Tests.CtorTests.TestCopyConstructor_Lifetime_Cloned [FAIL]
14:49:38         System.Security.Cryptography.CryptographicException : OpenCSP failed with error code 2148073494.
14:49:38         Stack Trace:
14:49:38               at Internal.NativeCrypto.CapiHelper.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
14:49:38               at System.Security.Cryptography.RSACryptoServiceProvider.get_SafeProvHandle()
14:49:38               at System.Security.Cryptography.RSACryptoServiceProvider.get_SafeKeyHandle()
14:49:38               at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 keySize, CspParameters parameters, Boolean useDefaultKeySize)
14:49:38            D:\j\workspace\windows_nt_re---37265eab\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.PrivateKey.cs(52,0): at Internal.Cryptography.Pal.CertificatePal.<>c.<GetRSAPrivateKey>b__62_0(CspParameters csp)
14:49:38            D:\j\workspace\windows_nt_re---37265eab\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.PrivateKey.cs(134,0): at Internal.Cryptography.Pal.CertificatePal.GetPrivateKey[T](Func`2 createCsp, Func`2 createCng)
14:49:38            D:\j\workspace\windows_nt_re---37265eab\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\CertificateExtensionsCommon.cs(52,0): at Internal.Cryptography.Pal.CertificateExtensionsCommon.GetPrivateKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
14:49:38            D:\j\workspace\windows_nt_re---37265eab\src\System.Security.Cryptography.X509Certificates\tests\CtorTests.cs(266,0): at System.Security.Cryptography.X509Certificates.Tests.CtorTests.TestPrivateKey(X509Certificate2 c, Boolean expectSuccess)
14:49:38            D:\j\workspace\windows_nt_re---37265eab\src\System.Security.Cryptography.X509Certificates\tests\CtorTests.cs(242,0): at System.Security.Cryptography.X509Certificates.Tests.CtorTests.TestCopyConstructor_Lifetime_Cloned()
```

https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/2797/consoleFull#184376521779fe3b83-f408-404c-b9e7-9207d232e5fc

@steveharter

**Comment by danmosemsft** [comment]
@bartonjs

**Comment by danmosemsft** [comment]
@steveharter @bartonjs any ideas, have you seen this error code before?

**Comment by danmosemsft** [comment]
ping @bartonjs .. this was a CI failure

**Comment by bartonjs** [comment]
@steveharter Looks like the new copy ctor has an intermittent failure.  I wonder if you can make it deterministic by adding a GC.Collect(); and GC.WaitForPendingFinalizers(); between `TestPrivateKey(c1, false)` and `TestPrivateKey(c2, true)`.  Something somewhere probably isn't ref-counting correctly, which is bad.

**Comment by stephentoub** [comment]
> Something somewhere probably isn't ref-counting correctly, which is bad.

May be totally unrelated, but there were a few seg faults in System.Security.Cryptography.X509Certificates.Tests in last night's runs:
https://ci.dot.net/job/dotnet_corefx/job/master/job/debian8.4_release/35/consoleText
https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release/36/consoleText

**Comment by steveharter** [comment]
This could be a regression, as I haven't seen any of these before, and it's been several weeks since the copy ctor was added. Will attempt to repro locally, and will likely add the GC.Collect and WaitForPendingFinalizers per suggestion.

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/327/consoleText
```
System.Security.Cryptography.CryptographicException : OpenCSP failed with error code 2148073494.
        Stack Trace:
  xUnit.net console test runner (64-bit .NET Core)
              at Internal.NativeCrypto.CapiHelper.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
  Copyright (C) 2014 Outercurve Foundation.
  
  Discovering: System.Security.Cryptography.X509Certificates.Tests
              at System.Security.Cryptography.RSACryptoServiceProvider.get_SafeProvHandle()
              at System.Security.Cryptography.RSACryptoServiceProvider.get_SafeKeyHandle()
              at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 keySize, CspParameters parameters, Boolean useDefaultKeySize)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.PrivateKey.cs(52,0): at Internal.Cryptography.Pal.CertificatePal.<>c.<GetRSAPrivateKey>b__62_0(CspParameters csp)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.PrivateKey.cs(134,0): at Internal.Cryptography.Pal.CertificatePal.GetPrivateKey[T](Func`2 createCsp, Func`2 createCng)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\CertificateExtensionsCommon.cs(52,0): at Internal.Cryptography.Pal.CertificateExtensionsCommon.GetPrivateKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Security.Cryptography.X509Certificates\tests\CtorTests.cs(266,0): at System.Security.Cryptography.X509Certificates.Tests.CtorTests.TestPrivateKey(X509Certificate2 c, Boolean expectSuccess)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Security.Cryptography.X509Certificates\tests\CtorTests.cs(242,0): at System.Security.Cryptography.X509Certificates.Tests.CtorTests.TestCopyConstructor_Lifetime_Cloned()
```
