### ISSUE TITLE
Validate_ConversionOverflows_ThrowsOverflowException fails on cs-CZ culture

### ISSUE THREAD

**Issue by svick** [dotnet/corefx#13604]
When running the tests for `System.ComponentModel.Annotations` on a machine with the cs-CZ culture (which uses `,` as the decimal separator), the `Validate_ConversionOverflows_ThrowsOverflowException` test fails:

```
     System.ComponentModel.DataAnnotations.Tests.RangeAttributeTests.Validate_ConversionOverflows_ThrowsOverflowExcepti
  on(type: typeof(double), minimum: \"1.0\", maximum: \"2.0\", value: \"2E+308\") [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.OverflowException)
        Actual:   typeof(System.FormatException): Input string was not in a correct format.
        Stack Trace:
              at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
              at System.String.System.IConvertible.ToDouble(IFormatProvider provider)
              at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
  Finished:    System.ComponentModel.Annotations.Tests
           E:\Users\Svick\git\corefx\src\System.ComponentModel.Annotations\src\System\ComponentModel\DataAnnotations\Ra
  ngeAttribute.cs(202,0): at System.ComponentModel.DataAnnotations.RangeAttribute.<>c__DisplayClass22_0.<SetupConversio
  n>b__2(Object value)
           E:\Users\Svick\git\corefx\src\System.ComponentModel.Annotations\src\System\ComponentModel\DataAnnotations\Ra
  ngeAttribute.cs(205,0): at System.ComponentModel.DataAnnotations.RangeAttribute.SetupConversion()
           E:\Users\Svick\git\corefx\src\System.ComponentModel.Annotations\src\System\ComponentModel\DataAnnotations\Ra
  ngeAttribute.cs(99,0): at System.ComponentModel.DataAnnotations.RangeAttribute.IsValid(Object value)
           E:\Users\Svick\git\corefx\src\System.ComponentModel.Annotations\src\System\ComponentModel\DataAnnotations\Va
  lidationAttribute.cs(389,0): at System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid(Object value, Valid
  ationContext validationContext)
           E:\Users\Svick\git\corefx\src\System.ComponentModel.Annotations\src\System\ComponentModel\DataAnnotations\Va
  lidationAttribute.cs(433,0): at System.ComponentModel.DataAnnotations.ValidationAttribute.GetValidationResult(Object
  value, ValidationContext validationContext)
           E:\Users\Svick\git\corefx\src\System.ComponentModel.Annotations\src\System\ComponentModel\DataAnnotations\Va
  lidationAttribute.cs(503,0): at System.ComponentModel.DataAnnotations.ValidationAttribute.Validate(Object value, Vali
  dationContext validationContext)
           E:\Users\Svick\git\corefx\src\System.ComponentModel.Annotations\tests\RangeAttributeTests.cs(177,0): at Syst
  em.ComponentModel.DataAnnotations.Tests.RangeAttributeTests.<>c__DisplayClass9_0.<Validate_ConversionOverflows_Throws
  OverflowException>b__0()
     System.ComponentModel.DataAnnotations.Tests.RangeAttributeTests.Validate_ConversionOverflows_ThrowsOverflowExcepti
  on(type: typeof(double), minimum: \"1.0\", maximum: \"2.0\", value: \"-2E+308\") [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.OverflowException)
        Actual:   typeof(System.FormatException): Input string was not in a correct format.
        Stack Trace:
              at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
              at System.String.System.IConvertible.ToDouble(IFormatProvider provider)
              at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
           E:\Users\Svick\git\corefx\src\System.ComponentModel.Annotations\src\System\ComponentModel\DataAnnotations\Ra
  ngeAttribute.cs(202,0): at System.ComponentModel.DataAnnotations.RangeAttribute.<>c__DisplayClass22_0.<SetupConversio
  n>b__2(Object value)
           E:\Users\Svick\git\corefx\src\System.ComponentModel.Annotations\src\System\ComponentModel\DataAnnotations\Ra
  ngeAttribute.cs(205,0): at System.ComponentModel.DataAnnotations.RangeAttribute.SetupConversion()
           E:\Users\Svick\git\corefx\src\System.ComponentModel.Annotations\src\System\ComponentModel\DataAnnotations\Ra
  ngeAttribute.cs(99,0): at System.ComponentModel.DataAnnotations.RangeAttribute.IsValid(Object value)
           E:\Users\Svick\git\corefx\src\System.ComponentModel.Annotations\src\System\ComponentModel\DataAnnotations\Va
  lidationAttribute.cs(389,0): at System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid(Object value, Valid
  ationContext validationContext)
           E:\Users\Svick\git\corefx\src\System.ComponentModel.Annotations\src\System\ComponentModel\DataAnnotations\Va
  lidationAttribute.cs(433,0): at System.ComponentModel.DataAnnotations.ValidationAttribute.GetValidationResult(Object
  value, ValidationContext validationContext)
           E:\Users\Svick\git\corefx\src\System.ComponentModel.Annotations\src\System\ComponentModel\DataAnnotations\Va
  lidationAttribute.cs(503,0): at System.ComponentModel.DataAnnotations.ValidationAttribute.Validate(Object value, Vali
  dationContext validationContext)
           E:\Users\Svick\git\corefx\src\System.ComponentModel.Annotations\tests\RangeAttributeTests.cs(177,0): at Syst
  em.ComponentModel.DataAnnotations.Tests.RangeAttributeTests.<>c__DisplayClass9_0.<Validate_ConversionOverflows_Throws
  OverflowException>b__0()

  === TEST EXECUTION SUMMARY ===
E:\Users\Svick\git\corefx\Tools\tests.targets(243,5): warning :    System.ComponentModel.Annotations.Tests  Total: 455,
 Errors: 0, Failed: 2, Skipped: 0, Time: 1,357s [E:\Users\Svick\git\corefx\src\System.ComponentModel.Annotations\tests\
System.ComponentModel.Annotations.Tests.csproj]
  Finished running tests.  End time=23:26:52,61, Exit code = 1
```

**Comment by tarekgh** [comment]
This is Component model tests issue and not Globalization issue.
