### ISSUE TITLE
System.Net.Ping.Functional.Tests hangs on a 1 Core Ubuntu 16.04 VM

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#13649]
This issue was originally reported by the WSL team. I'm able to repro if I switch my Ubuntu VM to 1 core. 
I don't have more info available (my host machine has perf issues and is now unusable).

/cc @stephentoub @mellinoe

**Comment by stephentoub** [comment]
@cipop, which test?  Can you pass ```/p:XunitOptions="-showProgress -parallel none"``` to the command-line and see which test it stops in?

**Comment by CIPop** [comment]
@stephentoub I had some odd issues with my _host_ (and VM as well) machine freezing up and couldn't do anything. Hard rebooted and will try again now.

**Comment by CIPop** [comment]
Running `~/corefx/Tools/msbuild.sh /t:rebuild,test "/p:XunitOptions=-showprogress -parallel none" /p:Configuration=Unix_Debug` or adding \" for the XunitOptions gives me an error.

Running without -parallel none:

```
  Discovering: System.Net.Ping.Functional.Tests
  Discovered:  System.Net.Ping.Functional.Tests
  Starting:    System.Net.Ping.Functional.Tests
     System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithIPAddressAndTimeoutAndBufferAndPingOptions [STARTING]
     System.Net.NetworkInformation.Tests.LoggingTest.EventSource_ExistsWithCorrectId [STARTING]
     System.Net.NetworkInformation.Tests.LoggingTest.EventSource_ExistsWithCorrectId [FINISHED] Time: 0.0071107s
     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 0) [STARTING]
     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 0) [FINISHED] Time: 0.1513561s
     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 1) [STARTING]
     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 1) [FINISHED] Time: 0.1011816s
     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 50) [STARTING]
     System.Net.NetworkInformation.Tests.PingOptionsTest.DontFragment_SetGetValidValues_Success(dontFragment: False) [STARTING]
     System.Net.NetworkInformation.Tests.PingOptionsTest.DontFragment_SetGetValidValues_Success(dontFragment: False) [FINISHED] Time: 0.0021608s
     System.Net.NetworkInformation.Tests.PingOptionsTest.DontFragment_SetGetValidValues_Success(dontFragment: True) [STARTING]
     System.Net.NetworkInformation.Tests.PingOptionsTest.DontFragment_SetGetValidValues_Success(dontFragment: True) [FINISHED] Time: 0.000014s
     System.Net.NetworkInformation.Tests.PingOptionsTest.DefaultProperties [STARTING]
     System.Net.NetworkInformation.Tests.PingOptionsTest.DefaultProperties [FINISHED] Time: 0.0005666s
     System.Net.NetworkInformation.Tests.PingOptionsTest.Ttl_InvalidValues_ThrowsException(ttl: 0) [STARTING]
     System.Net.NetworkInformation.Tests.PingOptionsTest.Ttl_InvalidValues_ThrowsException(ttl: 0) [FINISHED] Time: 0.0013113s
     System.Net.NetworkInformation.Tests.PingOptionsTest.Ttl_InvalidValues_ThrowsException(ttl: -1) [STARTING]
     System.Net.NetworkInformation.Tests.PingOptionsTest.Ttl_InvalidValues_ThrowsException(ttl: -1) [FINISHED] Time: 0.0000576s
     System.Net.NetworkInformation.Tests.PingOptionsTest.CtorValuesPassedToProperties [STARTING]
     System.Net.NetworkInformation.Tests.PingOptionsTest.CtorValuesPassedToProperties [FINISHED] Time: 0.0002409s
     System.Net.NetworkInformation.Tests.PingOptionsTest.Ttl_SetGetValidValues_Success(ttl: 1) [STARTING]
     System.Net.NetworkInformation.Tests.PingOptionsTest.Ttl_SetGetValidValues_Success(ttl: 1) [FINISHED] Time: 0.0001056s
     System.Net.NetworkInformation.Tests.PingOptionsTest.Ttl_SetGetValidValues_Success(ttl: 2147483647) [STARTING]
     System.Net.NetworkInformation.Tests.PingOptionsTest.Ttl_SetGetValidValues_Success(ttl: 2147483647) [FINISHED] Time: 0.0000069s
     System.Net.NetworkInformation.Tests.PingExceptionTest.CtorValuesPassedToProperties [STARTING]
     System.Net.NetworkInformation.Tests.PingExceptionTest.CtorValuesPassedToProperties [FINISHED] Time: 0.0005389s
     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 50) [FINISHED] Time: 0.1954399s
     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 1000) [STARTING]
     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 1000) [FINISHED] Time: 0.1010829s
     System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithIPAddressAndTimeoutAndBufferAndPingOptions [FAIL]
        Assert.Equal() Failure
        Expected: Byte[] [39, 80, 111, 115, 116, ...]
        Actual:   Byte[] []
        Stack Trace:
           /home/crispop/corefx/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs(183,0): at System.Net.NetworkInformation.Tests.PingTest.<>c__DisplayClass7_0.<SendPingAsyncWithIPAddressAndTimeoutAndBufferAndPingOptions>b__1(PingReply pingReply)
           /home/crispop/corefx/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs(443,0): at System.Net.NetworkInformation.Tests.PingTest.<SendPingAsync>d__23.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           /home/crispop/corefx/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs(177,0): at System.Net.NetworkInformation.Tests.PingTest.<SendPingAsyncWithIPAddressAndTimeoutAndBufferAndPingOptions>d__7.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithIPAddressAndTimeoutAndBufferAndPingOptions [FINISHED] Time: 0.5589386s
     System.Net.NetworkInformation.Tests.PingTest.Sends_ReuseInstance_Hostname [STARTING]
     System.Net.NetworkInformation.Tests.PingTest.Sends_ReuseInstance_Hostname [FINISHED] Time: 0.3134941s
     System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithHostAndTimeoutAndBuffer_Unix [STARTING]
     System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithHostAndTimeoutAndBuffer_Unix [FINISHED] Time: 0.1067852s
     System.Net.NetworkInformation.Tests.PingTest.Ping_SendAfterDispose_ThrowsSynchronously [STARTING]
     System.Net.NetworkInformation.Tests.PingTest.Ping_SendAfterDispose_ThrowsSynchronously [FINISHED] Time: 0.0013452s
     System.Net.NetworkInformation.Tests.PingTest.SendPings_ReuseInstance_Hostname [STARTING]
     System.Net.NetworkInformation.Tests.PingTest.SendPings_ReuseInstance_Hostname [FINISHED] Time: 0.3052759s
     System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithHostAndTimeoutAndBufferAndPingOptions [STARTING]
     System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithHostAndTimeoutAndBufferAndPingOptions [FAIL]
        Assert.Equal() Failure
        Expected: Byte[] [39, 80, 111, 115, 116, ...]
        Actual:   Byte[] []
        Stack Trace:
           /home/crispop/corefx/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs(300,0): at System.Net.NetworkInformation.Tests.PingTest.<>c__DisplayClass13_0.<SendPingAsyncWithHostAndTimeoutAndBufferAndPingOptions>b__1(PingReply pingReply)
           /home/crispop/corefx/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs(443,0): at System.Net.NetworkInformation.Tests.PingTest.<SendPingAsync>d__23.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           /home/crispop/corefx/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs(293,0): at System.Net.NetworkInformation.Tests.PingTest.<SendPingAsyncWithHostAndTimeoutAndBufferAndPingOptions>d__13.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithHostAndTimeoutAndBufferAndPingOptions [FINISHED] Time: 0.1169844s
     System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithIPAddressAndTimeoutAndBuffer [STARTING]
     System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithIPAddressAndTimeoutAndBuffer [FAIL]
        Assert.Equal() Failure
        Expected: Byte[] [39, 80, 111, 115, 116, ...]
        Actual:   Byte[] []
        Stack Trace:
           /home/crispop/corefx/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs(139,0): at System.Net.NetworkInformation.Tests.PingTest.<>c__DisplayClass5_0.<SendPingAsyncWithIPAddressAndTimeoutAndBuffer>b__1(PingReply pingReply)
           /home/crispop/corefx/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs(443,0): at System.Net.NetworkInformation.Tests.PingTest.<SendPingAsync>d__23.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           /home/crispop/corefx/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs(132,0): at System.Net.NetworkInformation.Tests.PingTest.<SendPingAsyncWithIPAddressAndTimeoutAndBuffer>d__5.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithIPAddressAndTimeoutAndBuffer [FINISHED] Time: 0.1240992s
     System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithHostAndTimeout [STARTING]
     System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithHostAndTimeout [FINISHED] Time: 0.1113627s
     System.Net.NetworkInformation.Tests.PingTest.SendAsyncs_ReuseInstance_Hostname [STARTING]
```

**Comment by CIPop** [comment]
Offline: The correct form for Ubuntu 16.04 is:

`~/corefx/Tools/msbuild.sh /t:rebuild,test "/p:XunitOptions=-showprogress" /p:Configuration=Unix_Debug /p:OSGroup=Linux /p:TestNugetRuntimeId=ubuntu.16.04-x64`

Output shows the same test hanging but nothing else fails:
```
  /home/crispop/corefx/bin/tests/Linux.AnyCPU.Debug/System.Net.Ping.Functional.Tests/default.netcoreapp1.1/RunTests.sh /home/crispop/corefx/packages/
  Using /home/crispop/corefx/packages/ as folder for resolving package dependencies.
  Executing in /home/crispop/corefx/bin/tests/Linux.AnyCPU.Debug/System.Net.Ping.Functional.Tests/default.netcoreapp1.1
  Hard linking dependent files...
  Finished linking needed files, moving to running tests.
  Running tests... Start time: 14:35:03
  Commands:
  ./corerun xunit.console.netcore.exe System.Net.Ping.Functional.Tests.dll -showprogress -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.

  Discovering: System.Net.Ping.Functional.Tests
  Discovered:  System.Net.Ping.Functional.Tests
  Starting:    System.Net.Ping.Functional.Tests
     System.Net.NetworkInformation.Tests.PingTest.Sends_ReuseInstance_Hostname [STARTING]
     System.Net.NetworkInformation.Tests.LoggingTest.EventSource_ExistsWithCorrectId [STARTING]
     System.Net.NetworkInformation.Tests.LoggingTest.EventSource_ExistsWithCorrectId [FINISHED] Time: 0.0054214s
     System.Net.NetworkInformation.Tests.PingOptionsTest.DontFragment_SetGetValidValues_Success(dontFragment: False) [STARTING]
     System.Net.NetworkInformation.Tests.PingOptionsTest.DontFragment_SetGetValidValues_Success(dontFragment: False) [FINISHED] Time: 0.0018876s
     System.Net.NetworkInformation.Tests.PingOptionsTest.DontFragment_SetGetValidValues_Success(dontFragment: True) [STARTING]
     System.Net.NetworkInformation.Tests.PingOptionsTest.DontFragment_SetGetValidValues_Success(dontFragment: True) [FINISHED] Time: 0.0000146s
     System.Net.NetworkInformation.Tests.PingOptionsTest.DefaultProperties [STARTING]
     System.Net.NetworkInformation.Tests.PingOptionsTest.DefaultProperties [FINISHED] Time: 0.0017625s
     System.Net.NetworkInformation.Tests.PingOptionsTest.Ttl_InvalidValues_ThrowsException(ttl: 0) [STARTING]
     System.Net.NetworkInformation.Tests.PingOptionsTest.Ttl_InvalidValues_ThrowsException(ttl: 0) [FINISHED] Time: 0.001611s
     System.Net.NetworkInformation.Tests.PingOptionsTest.Ttl_InvalidValues_ThrowsException(ttl: -1) [STARTING]
     System.Net.NetworkInformation.Tests.PingOptionsTest.Ttl_InvalidValues_ThrowsException(ttl: -1) [FINISHED] Time: 0.0001265s
     System.Net.NetworkInformation.Tests.PingOptionsTest.CtorValuesPassedToProperties [STARTING]
     System.Net.NetworkInformation.Tests.PingOptionsTest.CtorValuesPassedToProperties [FINISHED] Time: 0.00067s
     System.Net.NetworkInformation.Tests.PingOptionsTest.Ttl_SetGetValidValues_Success(ttl: 1) [STARTING]
     System.Net.NetworkInformation.Tests.PingOptionsTest.Ttl_SetGetValidValues_Success(ttl: 1) [FINISHED] Time: 0.0002932s
     System.Net.NetworkInformation.Tests.PingOptionsTest.Ttl_SetGetValidValues_Success(ttl: 2147483647) [STARTING]
     System.Net.NetworkInformation.Tests.PingOptionsTest.Ttl_SetGetValidValues_Success(ttl: 2147483647) [FINISHED] Time: 0.0000086s
     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 0) [STARTING]
     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 0) [FINISHED] Time: 0.0268824s
     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 1) [STARTING]
     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 1) [FINISHED] Time: 0.1016256s
     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 50) [STARTING]
     System.Net.NetworkInformation.Tests.PingExceptionTest.CtorValuesPassedToProperties [STARTING]
     System.Net.NetworkInformation.Tests.PingExceptionTest.CtorValuesPassedToProperties [FINISHED] Time: 0.0005676s
     System.Net.NetworkInformation.Tests.PingTest.Sends_ReuseInstance_Hostname [FINISHED] Time: 0.6683116s
     System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithHostAndTimeoutAndBuffer_Unix [STARTING]
     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 50) [FINISHED] Time: 0.4423062s
     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 1000) [STARTING]
     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 1000) [FINISHED] Time: 0.1156222s
     System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithHostAndTimeoutAndBuffer_Unix [FINISHED] Time: 0.1201997s
     System.Net.NetworkInformation.Tests.PingTest.Ping_SendAfterDispose_ThrowsSynchronously [STARTING]
     System.Net.NetworkInformation.Tests.PingTest.Ping_SendAfterDispose_ThrowsSynchronously [FINISHED] Time: 0.0007977s
     System.Net.NetworkInformation.Tests.PingTest.SendPings_ReuseInstance_Hostname [STARTING]
     System.Net.NetworkInformation.Tests.PingTest.SendPings_ReuseInstance_Hostname [FINISHED] Time: 0.3047731s
     System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithHostAndTimeout [STARTING]
     System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithHostAndTimeout [FINISHED] Time: 0.1115087s
     System.Net.NetworkInformation.Tests.PingTest.SendAsyncs_ReuseInstance_Hostname [STARTING]
```

**Comment by mellinoe** [comment]
I'm not able to reproduce this, but I'm only using `taskset -c 0 <testcommand>` on my existing machine, which has 4 cores.

Also, you should be able to run the tests simply via `msbuild /t:rebuildandtest <project>` now. The other stuff should be auto-detected.

**Comment by stephentoub** [comment]
I can repro it... including on Windows.  There's at least a test bug, if not a product issue as well.  I'll take it...
