### ISSUE TITLE
System.Xml.Xsl.XslTransformApi.Tests threw "System.Xml.Tests.VerifyException"

### ISSUE THREAD

**Issue by jiangzeng** [dotnet/corefx#13706]
No results generated.

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161115.01/workItem/System.Xml.Xsl.XslTransformApi.Tests/details/4944a05a-b748-44ab-b117-f6714bb60568

```
2016-11-14 19:23:44,771: INFO: proc(65): run_and_log_output: Output:    System.Xml.Tests.CTransformStrStrTest.TransformStrStr9() [FAIL]
2016-11-14 19:23:44,772: INFO: proc(65): run_and_log_output: Output:       System.Xml.Tests.VerifyException : Error while loading assembly
2016-11-14 19:23:44,772: INFO: proc(65): run_and_log_output: Output:       Stack Trace:
2016-11-14 19:23:44,772: INFO: proc(65): run_and_log_output: Output:             at System.Xml.Tests.ExceptionVerifier..ctor(String assemblyName, ExceptionVerificationFlags flags, ITestOutputHelper output)
2016-11-14 19:23:44,772: INFO: proc(65): run_and_log_output: Output:             at System.Xml.Tests.CExceptionHandler..ctor(String strXmlFile, String ns, ITestOutputHelper output)
2016-11-14 19:23:44,772: INFO: proc(65): run_and_log_output: Output:             at System.Xml.Tests.XsltApiTestCaseBase.CheckExpectedError(Exception ex, String assembly, String res, String[] strParams)
2016-11-14 19:23:44,772: INFO: proc(65): run_and_log_output: Output:             at System.Xml.Tests.CTransformStrStrTest.TransformStrStr9()
2016-11-14 19:23:44,773: INFO: proc(65): run_and_log_output: Output:    System.Xml.Tests.CTransformStrStrResolverTest.TransformStrStrResolver3 [SKIP]
2016-11-14 19:23:44,773: INFO: proc(65): run_and_log_output: Output:       SQLBU Defect Tracking Bug 430834: Skipping when input type is URI, see bug for more details.
2016-11-14 19:23:44,773: INFO: proc(65): run_and_log_output: Output:    System.Xml.Tests.CTransformStrStrResolverTest.TransformStrStrResolver1 [SKIP]
2016-11-14 19:23:44,773: INFO: proc(65): run_and_log_output: Output:       Resolving of External URIs is no longer allowed
2016-11-14 19:23:44,773: INFO: proc(65): run_and_log_output: Output:    System.Xml.Tests.CNDP1_1SP1Test.var3 [SKIP]
2016-11-14 19:23:44,773: INFO: proc(65): run_and_log_output: Output:       SQLBU Defect Tracking Bug 430834: Skipping when input type is URI, see bug for more details.

```

Build : Master - 20161115.01 (Core Tests)
 Failing configurations: OSX.1011.Amd64:AnyCPU-Debug

**Comment by jiangzeng** [comment]
Results are generated in build 20161116.04, and the following tests are still throwing "System.Xml.Tests.VerifyException".
System.Xml.Xsl.XslCompiledTransformApi.Tests/System.Xml.Tests.CLoadReaderTest/LoadXmlReader2
System.Xml.Xsl.XslCompiledTransformApi.Tests/System.Xml.Tests.CLoadReaderTest/LoadXmlReader5
System.Xml.Xsl.XslCompiledTransformApi.Tests/System.Xml.Tests.CLoadTest/LoadGeneric2
System.Xml.Xsl.XslCompiledTransformApi.Tests/System.Xml.Tests.CLoadXmlResolverTest/LoadGeneric7
System.Xml.Xsl.XslCompiledTransformApi.Tests/System.Xml.Tests.CLoadXmlResolverTest/LoadGeneric8
System.Xml.Xsl.XslCompiledTransformApi.Tests/System.Xml.Tests.CTransformStrStrTest/TransformStrStr9
System.Xml.Xsl.XslCompiledTransformApi.Tests/System.Xml.Tests.CTransformTestGeneric/TransformGeneric11
System.Xml.Xsl.XslCompiledTransformApi.Tests/System.Xml.Tests.CTransformTestGeneric/TransformGeneric4
System.Xml.Xsl.XslCompiledTransformApi.Tests/System.Xml.Tests.CTransformTestGeneric/TransformGeneric7
System.Xml.Xsl.XslCompiledTransformApi.Tests/System.Xml.Tests.CTransformTestGeneric/TransformGeneric9
System.Xml.Xsl.XslTransformApi.Tests/System.Xml.Tests.CLoadReaderTest/LoadXmlReader2
System.Xml.Xsl.XslTransformApi.Tests/System.Xml.Tests.CLoadReaderTest/LoadXmlReader5
System.Xml.Xsl.XslTransformApi.Tests/System.Xml.Tests.CLoadTest/LoadGeneric2
System.Xml.Xsl.XslTransformApi.Tests/System.Xml.Tests.CLoadXmlResolverTest/LoadGeneric12
System.Xml.Xsl.XslTransformApi.Tests/System.Xml.Tests.CLoadXmlResolverTest/LoadGeneric4
System.Xml.Xsl.XslTransformApi.Tests/System.Xml.Tests.CTransformStrStrTest/TransformStrStr9
System.Xml.Xsl.XslTransformApi.Tests/System.Xml.Tests.CTransformTestGeneric/TransformGeneric4

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161116.04/workItem/System.Xml.Xsl.XslCompiledTransformApi.Tests

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161116.04/workItem/System.Xml.Xsl.XslTransformApi.Tests
