### ISSUE TITLE
System.Xml.Xsl.XslCompiledTransformApi.Tests threw "System.NullReferenceException"

### ISSUE THREAD

**Issue by jiangzeng** [dotnet/corefx#13705]
No results generated.

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161115.01/workItem/System.Xml.Xsl.XslCompiledTransformApi.Tests/details/4944a05a-b748-44ab-b117-f6714bb60568

```
2016-11-14 19:23:48,940: INFO: proc(65): run_and_log_output: Output:    System.Xml.Tests.CLoadTest.LoadGeneric2() [FAIL]
2016-11-14 19:23:48,941: INFO: proc(65): run_and_log_output: Output:       System.NullReferenceException : Object reference not set to an instance of an object.
2016-11-14 19:23:48,945: INFO: proc(65): run_and_log_output: Output:       Stack Trace:
2016-11-14 19:23:49,054: INFO: proc(65): run_and_log_output: Output:             at System.Xml.Tests.ExceptionVerifier..ctor(String assemblyName, ExceptionVerificationFlags flags, ITestOutputHelper output)
2016-11-14 19:23:49,054: INFO: proc(65): run_and_log_output: Output:             at System.Xml.Tests.CExceptionHandler..ctor(String strXmlFile, String ns, ITestOutputHelper output)
2016-11-14 19:23:49,054: INFO: proc(65): run_and_log_output: Output:             at System.Xml.Tests.XsltApiTestCaseBase2.CheckExpectedError(Exception ex, String assembly, String res, String[] strParams)
2016-11-14 19:23:49,054: INFO: proc(65): run_and_log_output: Output:             at System.Xml.Tests.CLoadTest.LoadGeneric2()

```

Build : Master - 20161115.01 (Core Tests)
Failing configurations: OSX.1011.Amd64:AnyCPU-Debug

**Comment by parjong** [comment]
I encountered the same issue before on some Linux system. 

While digging this issue, I found that there are root issues:
 - There was a bug in the test code (discussed in #13669)
 - The current implementation of those tests works only for en_US locale.

I could fix this issue by applying #13669 first (then you will encounter the issue discussed in #13706), and setting LANG=en_US.UTF-8.

**Comment by sepidehMS** [comment]
Thanks @parjong for the fix.

**Comment by sepidehMS** [comment]
Fixed by https://github.com/dotnet/corefx/pull/13669
