### ISSUE TITLE
Provide an API for traversing/reasoning about async call stacks

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#1370]
Any tool that shows exceptions today also shows the callstack. With the introduction of the async keyword (yield was the same I guess), it's becoming increasingly harder to show reasonable call stacks because of the async state machine. It would be nice if there was an API somewhere that could be used to clean up the async state machine and pretty print a call stack with readable method names (tools like reflector do this). 

Here's an example of a typical error page in an MVC 6 application:

![image](https://cloud.githubusercontent.com/assets/95136/7085404/4e19da18-df2b-11e4-8fa7-28a0799854f0.png)

**Comment by Maxwe11** [comment]
:+1: :clap:

**Comment by HaloFour** [comment]
Check out this article from MSDN Magazine:

[Async Programming: Async Causality Chain Tracking](https://msdn.microsoft.com/en-us/magazine/jj891052.aspx)

It would have something like that built-in.  However if it would have to capture the stack trace at the point of awaiting it would probably add a non-trivial amount of overhead, as the article mentions.

**Comment by AlfredoMS** [comment]
@HaloFour @davidfowl   Async Causality tracking existsin mscorlib, see https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/Tasks/AsyncCausalityTracer.cs
VS2013 uses it to populate some of the information in the Task window.
Although I would agree it needs to be improved for xplat and there could be more tools taking advantage of its output.

**Comment by HaloFour** [comment]
Hrm, doesn't look like something you can use programmatically from within
your own program?  I used the tricks from that MSDN Magazine article to
implement better exception messages in my web app as it was heavily async.

**Comment by noahfalk** [comment]
Adding @tmat 
@davidfowl Have you talked to the Roslyn guys about this at all? Ostensibly the abstraction you are trying to restore comes in two parts:
1) The framework provides the Task libraries. The fact that TaskAwaiter.GetResult() has calls to TaskAwaiter.HandleNonSuccessAndDebuggerNotification is a framework detail, so it would seem reasonable that any algorithm to clean up that part of the stack trace is owned by the framework.
2) The C# compiler provides the implementation of async and code-rewriting that creates the async state machines. Once we hit runtime the only information that could tie d__43.MoveNext() to a source location is contained inside custom debug information records in the PDB.

I'd assume the Roslyn Expression Evaluator, which runs within Visual Studio Debugger, has the algorithms you are looking for to sanitize these stack traces. Given that ASP.NET is already loading the compiler portion of Roslyn to runtime compilation, maybe we should also have you guys load the debugger portions of Roslyn for diagnostics such as this? I'm hoping @tmat can shed a little more light on how this is factored, or give us bad news that some key component is inside VS debugger itself rather than in the EE.

**Comment by davidfowl** [comment]
@tmat @gregg-miskelly Any ideas for this one?

**Comment by RichiCoder1** [comment]
Wanted say this would be a big win. Async stack traces are a serious pain to diagnose, and adding a mechanism to erase implementation details (TaskAwaiter, GetResult, ThrowForNonSuccess), and unify the generated state machines into something comprehensible would be amazing.

**Comment by gregg-miskelly** [comment]
The code that the VS debugger uses for walking the async stack isn't open, but I am happy to point Microsoft employees to it. The only role that the EE has in this is to give the 'MoveNext' method a better name.

**Comment by gregg-miskelly** [comment]
Though I should say that if the problem we are trying to solve is the stack trace for an exception object (and not some sort of new 'Environment.GetAsyncStack()') then I am not sure that any of the code that the debugger has will be all that useful. We likely need enhancements/enlightenments between the stack trace code and the task implementation code to make that story good.

**Comment by noahfalk** [comment]
The debugger has code that understands the C# async state machine and how it relates back to the source the user originally authored right? Presumably that is the key bit that is missing. 

I agree the solution would look a bit different if we were modifying Exception.StackTrace vs. creating a new API, but I think both solutions would require reversing the C# compiler's state machine construction.

**Comment by gregg-miskelly** [comment]
If we are only concerned with fixing Exception.StackTrace, I actually think we don't need to decode the state machine because the method in the state machine class (<compiler-generated-class-name>.MoveNext) is on the stack already. What we need to do is clean up the task goo. It might also be nice to use method/class names that the user understands rather than the metadata names.

**Comment by noahfalk** [comment]
Folks in this issue might find @aelij's work interesting: https://github.com/dotnet/coreclr/issues/2813

**Comment by aelij** [comment]
> I think both solutions would require reversing the C# compiler's state machine construction.

That's what I do in order to get the original method name. The downside is that it's compiler- and language-specific. Perhaps a long-term solution could be to have the compiler emit an attribute for the async state machine class that includes a string with the original method's signature. That way we could also print the full parameter list.

**Comment by tmat** [comment]
We emit Async/IteratorStateMachineAttribute on the kickoff method that points to the state machine type.

We will the emit reverse mapping to Portable PDBs (I don't think we do that right now, but certainly will do so for ```dotnet cli``` release): https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PortablePdb-Metadata.md#StateMachineMethodTable

We do this stack cleanup for the REPL as well: 
http://source.roslyn.io/#Microsoft.CodeAnalysis.Scripting/Hosting/ObjectFormatter/CommonObjectFormatter.cs,d92226e92a7dee26,references

there is a few hacks that I want to get cleaned up at some point, but it generally works.

**Comment by tmat** [comment]
BTW, scripting has a dependency on the entire Roslyn compiler, which for most apps is overkill. I wonder if we should split the parts that don't actually need the compiler into a separate assembly that doesn't depend on anything other than SRM and immutable collections.

**Comment by davidfowl** [comment]
Just catching back up on this thread and it seems like we might have enough pieces to throw something together.

**Comment by gdoron** [comment]
Is this issue related to the fact that many times though we have pdb files on the servers, we get stacktrace of line 0?


>System.NullReferenceException: Object reference not set to an instance of an object.
   at Yooocan.Web.Controllers.VendorController.<MyProducts>d__16.MoveNext() in **C:\git\Yooocan\src\Yooocan.Web\Controllers\VendorController.cs:line 0**
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<CastToObject>d__40`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()

**Comment by karelz** [comment]
@joperezr please work with @noahfalk and @tmat to work on high-level idea. Let's mark the issue appropriately then.

**Comment by mattzink** [comment]
Is this being actively worked? Many large .NET projects are adding hacks to reverse the async leaky abstraction in stack traces. This should be handled by the platform, as is done in Go and Python

**Comment by noahfalk** [comment]
I'm not aware of any active work, though its possible something is happening outside my view.

**Comment by benaadams** [comment]
Had a go at changing the StackTrace by changing the stack :) 

Has some outstanding issues/questions though https://github.com/dotnet/coreclr/pull/14564

**Comment by benaadams** [comment]
Tool that produces clean `ResolvedStackTrace`s https://github.com/benaadams/Ben.Demystifier
