### ISSUE TITLE
Failure in AppDomainTests.GetAssemblies due to FileNotFoundException

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#13748]
This failed in CI, on CentOS
https://ci.dot.net/job/dotnet_corefx/job/master/job/centos7.1_debug_prtest/280/consoleText
```
     System.Tests.AppDomainTests.GetAssemblies [FAIL]
        System.IO.FileNotFoundException : Could not load file or assembly 'TestAppOutsideOfTPA, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
        
        Stack Trace:
              at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
              at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
              at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
              at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
              at System.Reflection.Assembly.Load(String assemblyString)
              at System.AppDomain.Load(String assemblyString)
           /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/src/System.Runtime.Extensions/tests/System/AppDomainTests.cs(405,0): at System.Tests.AppDomainTests.GetAssemblies()
  ```

**Comment by danmosemsft** [comment]
@rahku
