### ISSUE TITLE
XsltCompiler.Tests project fails many tests when UI language is not ENU

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#13827]
I have many failed tests in next projects.  

msbuild.err
```
 541:5>C:\Users\Alex\Documents\Home\corefx\Tools\tests.targets(254,5): error : One or more tests failed while running tests from 'System.Collections.Tests' please check log for details! [C:\Users\Alex\Documents\Home\corefx\src\System.Collections\tests\System.Collections.Tests.csproj]
 541:6>C:\Users\Alex\Documents\Home\corefx\Tools\tests.targets(254,5): error : One or more tests failed while running tests from 'System.Collections.Tests' please check log for details! [C:\Users\Alex\Documents\Home\corefx\src\System.Collections\tests\System.Collections.Tests.csproj]
 629:4>C:\Users\Alex\Documents\Home\corefx\Tools\tests.targets(254,5): error : One or more tests failed while running tests from 'System.Globalization.Extensions.Tests' please check log for details! [C:\Users\Alex\Documents\Home\corefx\src\System.Globalization.Extensions\tests\System.Globalization.Extensions.Tests.csproj]
 780:3>C:\Users\Alex\Documents\Home\corefx\Tools\tests.targets(254,5): error : One or more tests failed while running tests from 'System.Private.Uri.Functional.Tests' please check log for details! [C:\Users\Alex\Documents\Home\corefx\src\System.Private.Uri\tests\FunctionalTests\System.Private.Uri.Functional.Tests.csproj]
 822:2>C:\Users\Alex\Documents\Home\corefx\Tools\tests.targets(254,5): error : One or more tests failed while running tests from 'XsltCompiler.Tests' please check log for details! [C:\Users\Alex\Documents\Home\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\XsltCompiler.Tests.csproj]
 923:5>C:\Users\Alex\Documents\Home\corefx\Tools\tests.targets(254,5): error : One or more tests failed while running tests from 'System.Runtime.Tests' please check log for details! [C:\Users\Alex\Documents\Home\corefx\src\System.Runtime\tests\System.Runtime.Tests.csproj]
 1017:5>C:\Users\Alex\Documents\Home\corefx\Tools\tests.targets(254,5): error : One or more tests failed while running tests from 'System.Threading.Tests' please check log for details! [C:\Users\Alex\Documents\Home\corefx\src\System.Threading\tests\System.Threading.Tests.csproj]
 923:6>C:\Users\Alex\Documents\Home\corefx\Tools\tests.targets(254,5): error : One or more tests failed while running tests from 'System.Runtime.Tests' please check log for details! [C:\Users\Alex\Documents\Home\corefx\src\System.Runtime\tests\System.Runtime.Tests.csproj]
```

Is it normal?

**Comment by svick** [comment]
Why did the tests fail? You should be able to find out in msbuild.log or if you build `.builds` for one of the failing tests, e.g.:

```bat
cd src\System.Runtime\tests
msbuild /v:m /m System.Runtime.Tests.builds
```

 Does the same thing happen if you do a clean rebuild?

**Comment by AlexRadch** [comment]
After clean rebuild only `corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\XsltCompiler.Tests.csproj`  project have failed tests.
Like next 

```
System.Xml.Tests.XsltcTestFile.Var1(param0: \"@infft14.txt\", param1: \"fft14.dll\", param2: \"no\", param3: \"fft14\", param4: \"fft14.pdb\", param5: \"no\", param6: \"fft14.txt\") [FAIL]
               OLEDB.Test.ModuleCore.CTestFailedException : Output was not as expected.
               Stack Trace:
                  C:\mount\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs(100,0): at System.Xml.Tests.XsltcTestCaseBase.CompareOutput(Stream expectedStream, Stream actualStream, Int32 count)
                  C:\mount\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs(184,0): at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean runAssemblyVerification, Boolean loadFromFile)
                  C:\mount\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs(143,0): at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean loadFromFile)
                  C:\mount\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestFile.cs(74,0): at System.Xml.Tests.XsltcTestFile.Var1(Object param0, Object param1, Object param2, Object param3, Object param4, Object param5, Object param6)
```

I think that TryCreatePersistedTransformAssembly method start new "xsltc.exe" process and "xsltc.exe" process produce different output with different language settings in windows. I cannot check it because I did not find how to change new process language settings. 

How to log "xsltc.exe" output?

**Comment by AlexRadch** [comment]
I changed Windows language to English (USA). Now my Windows UI interface uses english language. But `corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\XsltCompiler.Tests.csproj`  project failed the same tests.

In addition `System.Globalization.Tests.CultureInfoMiscTests.InstalledUICultureTest` [FAIL] in `corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\XsltCompiler.Tests.csproj` project also.

**Comment by danmosemsft** [comment]
@AlexRadch you say these still fail when OS language is English -- is xsltc.exe output English in this case? I'm wondering how we repro this.

I've removed the label as this does not impact most folks/runs.

**Comment by danmosemsft** [comment]
Moving to future as it doesn't seem to be hitting anyone else right now

**Comment by krwq** [comment]
Considering almost 2 years have passed and no new complains/upvotes - closing. Please comment/reopen if this is still an issue.
