### ISSUE TITLE
Unable to cast object of type 'System.Numerics.BigInteger' to type 'System.Decimal'.

### ISSUE THREAD

**Issue by composite** [dotnet/corefx#13881]
While unit test my project, I got a weird exception.

Referenced source
```cs
BigInteger bi = new BigInteger(123);
decimal d = (decimal)bi; // boooo
```

But in according to [MSDN](https://msdn.microsoft.com/en-us/library/dd268232(v=vs.110).aspx), `System.Numerics.BigInteger` have a explicit cast to `System.Decimal`.
but I got `TypeCastException`. why?

`project.json` - .NET Standard 1.1
```json
{
  "supports": {},
  "dependencies": {
    "Microsoft.NETCore.Portable.Compatibility": "1.0.1",
    "NETStandard.Library": "1.6.1",
    "Newtonsoft.Json": "9.0.1",
    "System.Reflection.Emit": "4.3.0-preview1-24530-04",
    "System.Reflection.Emit.ILGeneration": "4.3.0-preview1-24530-04",
    "System.Reflection.Emit.Lightweight": "4.3.0-preview1-24530-04"
  },
  "frameworks": {
    "netstandard1.1": {}
  }
}
```

Reference project is a unit test in [here](https://github.com/composite/ArangoDB.Net).

```
Test name:	ArangoDB.Net.Tests.VelocityPack.VPackBuilderTest.AddBigIntegerAsInt
Full test name:	ArangoDB.Net.Tests.VelocityPack.VPackBuilderTest.AddBigIntegerAsInt
Test source:	D:\Projects\Github\ArangoDB.Net\Tests\VelocityPack\VPackBuilderTest.cs : 줄 184
Test result:	실패
Test eleapsed time:	0:00:00.098

Result StackTrace:	
at VelocyPack.Internal.Value.GetNumber() in D:\Projects\Github\ArangoDB.Net\VelocyPack\Internal\Value.cs:line 101
   at VelocyPack.VPackBuilder.Set(Value item) in D:\Projects\Github\ArangoDB.Net\VelocyPack\VPackBuilder.cs:line 733
   at VelocyPack.VPackBuilder._Appender_74.Append(VPackBuilder builder, Value value) in D:\Projects\Github\ArangoDB.Net\VelocyPack\VPackBuilder.cs:line 63
   at VelocyPack.VPackBuilder.AddInternal[T](IAppender`1 appender, T value) in D:\Projects\Github\ArangoDB.Net\VelocyPack\VPackBuilder.cs:line 576
   at VelocyPack.VPackBuilder.Add(BigInteger value, ValueType type) in D:\Projects\Github\ArangoDB.Net\VelocyPack\VPackBuilder.cs:line 483
   at ArangoDB.Net.Tests.VelocityPack.VPackBuilderTest.AddBigIntegerAsInt() in D:\Projects\Github\ArangoDB.Net\Tests\VelocityPack\VPackBuilderTest.cs:line 187
Result message:	Unable to cast object of type 'System.Numerics.BigInteger' to type 'System.Decimal'.

```

**Additional note: `System.Int32` and `System.Int64` too.**

**Comment by AlexRadch** [comment]
Now BigInteger is not part of Standard library, so Decimal class can not have explicit operator to convert from BigInteger value, because Standard library knows nothing about BigInteger.

Now BigInteger should have something like ToDecimal method.

**Comment by svick** [comment]
@AlexRadch `Decimal` never had explicit operator from `BigInteger`. Instead, [`BigInteger` has explicit operator to `Decimal`](https://apisof.net/catalog/M%3ASystem.Numerics.BigInteger.op_Explicit(System.Numerics.BigInteger)~System.Decimal). And that operator is part of `netstandard1.1`.

**Comment by composite** [comment]
This issue might be nonsense.
why I tried cast boxed BigInteger to decimal like `(decimal)(object)new BigInteger(long.MaxValue)`.
I'll close this issue.
