### ISSUE TITLE
CI failures in WinHttpHandlerUnitTests

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#13951]
See https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/733/
```
System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefDisposeDispose_HandleIsNotClosed
System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefDispose_HandleIsNotClosed
System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.SetParentHandle_CreateParentCreateChildDisposeParent_ParentNotClosed
System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefReleaseDispose_HandleIsClosed
System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefRelease_HandleIsNotClosed
System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefDisposeRelease_HandleIsClosed
```
with errors like:
```
21:28:12      System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefDisposeDispose_HandleIsNotClosed [FAIL]
21:28:12         Assert.Equal() Failure
21:28:12         Expected: 1
21:28:12         Actual:   3
21:28:12         Stack Trace:
21:28:12            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http.WinHttpHandler\tests\UnitTests\SafeWinHttpHandleTest.cs(41,0): at System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefDisposeDispose_HandleIsNotClosed()
21:28:12      System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefDispose_HandleIsNotClosed [FAIL]
21:28:12         Assert.Equal() Failure
21:28:12         Expected: 1
21:28:12         Actual:   2
21:28:12         Stack Trace:
21:28:12            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http.WinHttpHandler\tests\UnitTests\SafeWinHttpHandleTest.cs(24,0): at System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefDispose_HandleIsNotClosed()
21:28:12      System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.SetParentHandle_CreateParentCreateChildDisposeParent_ParentNotClosed [FAIL]
21:28:12         Assert.Equal() Failure
21:28:12         Expected: 2
21:28:12         Actual:   4
21:28:12         Stack Trace:
21:28:12            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http.WinHttpHandler\tests\UnitTests\SafeWinHttpHandleTest.cs(135,0): at System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.SetParentHandle_CreateParentCreateChildDisposeParent_ParentNotClosed()
21:28:12      System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefReleaseDispose_HandleIsClosed [FAIL]
21:28:12         Assert.Equal() Failure
21:28:12         Expected: 0
21:28:12         Actual:   4
21:28:12         Stack Trace:
21:28:12            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http.WinHttpHandler\tests\UnitTests\SafeWinHttpHandleTest.cs(88,0): at System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefReleaseDispose_HandleIsClosed()
21:28:12      System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefRelease_HandleIsNotClosed [FAIL]
21:28:12         Assert.Equal() Failure
21:28:12         Expected: 1
21:28:12         Actual:   5
21:28:12         Stack Trace:
21:28:12            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http.WinHttpHandler\tests\UnitTests\SafeWinHttpHandleTest.cs(71,0): at System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefRelease_HandleIsNotClosed()
21:28:12      System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefDisposeRelease_HandleIsClosed [FAIL]
21:28:12         Assert.Equal() Failure
21:28:12         Expected: 0
21:28:12         Actual:   5
21:28:12         Stack Trace:
21:28:12            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http.WinHttpHandler\tests\UnitTests\SafeWinHttpHandleTest.cs(58,0): at System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefDisposeRelease_HandleIsClosed()
```
Seems different from other WinHttpHandler test failures reported earlier.

**Comment by bartdesmet** [comment]
Again @ https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/825/

**Comment by bartdesmet** [comment]
Again @ https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/913/

**Comment by danmosemsft** [comment]
@davidsh @CIPop generally I'm ignoring the system.net test failures as we know they are fundamentally fragile and you have work planned to address the root cause. This one isn't so clearly due to fragility though and I haven't seen it before. Worth a look?

**Comment by davidsh** [comment]
>This one isn't so clearly due to fragility though and I haven't seen it before. Worth a look?
Yes, we discussed this with KarelZ already.  This test should never fail especially since it doesn't use the real network.  I suspect changes in CoreCLR have broken this test...maybe something to do with SafeHandles, etc.

**Comment by jkotas** [comment]
This is bug in WinHttpHandler tests.

The tests are stomping on the FakeSafeWinHttpHandle.HandlesOpen global state because of they do not cleanup after itself. They depend on the GC and finalizers to cleanup that happens later, in parallel with other tests running.

E.g. add Assert.Equal(0, FakeSafeWinHttpHandle.HandlesOpen); at the end of tests in https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/tests/UnitTests/WinHttpResponseStreamTest.cs to see the problem.

**Comment by jkotas** [comment]
https://github.com/dotnet/corefx/pull/14132#issuecomment-264281354 is my suggestion on how to fix the tests.
