### ISSUE TITLE
CI failure in System.Security.Cryptography.Encryption.Tests.Asymmetric.CryptoStreamTests.FlushAsync

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#13966]
See https://ci.dot.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/731/.
```
MESSAGE:
System.OverflowException : Arithmetic operation resulted in an overflow.
+++++++++++++++++++
STACK TRACE:
at System.Security.Cryptography.Encryption.Tests.Asymmetric.CryptoStreamTests.IdentityTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Security.Cryptography.Primitives/tests/CryptoStream.cs:line 302 at System.Security.Cryptography.CryptoStream.FlushFinalBlock() at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing) at System.IO.Stream.Close() at System.Security.Cryptography.Encryption.Tests.Asymmetric.CryptoStreamTests.FlushAsync() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Security.Cryptography.Primitives/tests/CryptoStream.cs:line 189
```

**Comment by danmosemsft** [comment]
I'm guessing this is actually line 303:
`                    int numWholeReadBlocksInBytes = (amountRead / _inputBlockSize) * _inputBlockSize;`

I thought OverflowException only happened when compiling with checked, but I don't see that (either on the command line or as a checked statement)

@bartonjs @steveharter CI failure.

**Comment by danmosemsft** [comment]
@bartonjs @steveharter which one of you should take a look?

**Comment by steveharter** [comment]
Note the exception is actually from the test project (not the S.S.C.Primitives assembly); same file name for test and impl so easily mixed up.
```
/tests/CryptoStream.cs:line 302 (probably len > Int32.MaxValue)
                long len = _stream.Length - _stream.Position;
>>              byte[] outputBuffer = new byte[len];
                _stream.Read(outputBuffer, 0, outputBuffer.Length);
```

at System.Security.Cryptography.Encryption.Tests.Asymmetric.CryptoStreamTests.IdentityTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Security.Cryptography.Primitives/tests/CryptoStream.cs:line 302
at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
at System.IO.Stream.Close()
at System.Security.Cryptography.Encryption.Tests.Asymmetric.CryptoStreamTests.FlushAsync() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Security.Cryptography.Primitives/tests/CryptoStream.cs:line 189

**Comment by steveharter** [comment]
Assuming test bug until proven otherwise

**Comment by steveharter** [comment]
Fixed multithreading test bug
