### ISSUE TITLE
CertTests.TestVerify test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#13979]
https://ci.dot.net/job/dotnet_corefx/job/master/job/centos7.1_debug_prtest/760/consoleText
```
System.Security.Cryptography.X509Certificates.Tests.CertTests.TestVerify [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/src/System.Security.Cryptography.X509Certificates/tests/CertTests.cs(99,0): at System.Security.Cryptography.X509Certificates.Tests.CertTests.TestVerify()
```

**Comment by bartdesmet** [comment]
Another occurrence here: https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/785/
```
MESSAGE:
Assert.True() Failure\nExpected: True\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.Security.Cryptography.X509Certificates.Tests.CertTests.TestVerify() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Security.Cryptography.X509Certificates/tests/CertTests.cs:line 99
```

**Comment by danmosemsft** [comment]
@steveharter you added this test recently in 2e8bfa2. It's this assert that's failing. Can you take a look?

```
            using (var microsoftDotComRoot = new X509Certificate2(TestData.MicrosoftDotComRootBytes))
            {
                Assert.True(microsoftDotComRoot.Verify()); // NotAfter=7/17/2036
            }
```

**Comment by steveharter** [comment]
The Verify() method is subject to online certificate validation; I'll see if I can add some diagnostic information and perhaps move to outer loop.
