### ISSUE TITLE
SafeWinHttpHandleTest failed in CI

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#14135]
```
     System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefDisposeDispose_HandleIsNotClosed [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   3
        Stack Trace:
  Starting:    System.ComponentModel.EventBasedAsync.Tests
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Http.WinHttpHandler\tests\UnitTests\SafeWinHttpHandleTest.cs(44,0): at System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefDisposeDispose_HandleIsNotClosed()
     System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefDispose_HandleIsNotClosed [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   4
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Http.WinHttpHandler\tests\UnitTests\SafeWinHttpHandleTest.cs(27,0): at System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefDispose_HandleIsNotClosed()
     System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.SetParentHandle_CreateParentCreateChildDisposeParent_ParentNotClosed [FAIL]
        Assert.Equal() Failure
        Expected: 2
        Actual:   6
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Http.WinHttpHandler\tests\UnitTests\SafeWinHttpHandleTest.cs(138,0): at System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.SetParentHandle_CreateParentCreateChildDisposeParent_ParentNotClosed()
     System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefReleaseDispose_HandleIsClosed [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   6
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Http.WinHttpHandler\tests\UnitTests\SafeWinHttpHandleTest.cs(89,0): at System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefReleaseDispose_HandleIsClosed()
     System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefRelease_HandleIsNotClosed [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   7
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Http.WinHttpHandler\tests\UnitTests\SafeWinHttpHandleTest.cs(74,0): at System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefRelease_HandleIsNotClosed()
     System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefDisposeRelease_HandleIsClosed [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   5
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Http.WinHttpHandler\tests\UnitTests\SafeWinHttpHandleTest.cs(59,0): at System.Net.Http.WinHttpHandlerUnitTests.SafeWinHttpHandleTest.CreateAddRefDisposeRelease_HandleIsClosed()
  
```

**Comment by danmosemsft** [comment]
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/962/consoleText

**Comment by danmosemsft** [comment]
@CIPop @davidsh

**Comment by davidsh** [comment]
Isn't this a dupe of https://github.com/dotnet/corefx/issues/13951

**Comment by danmosemsft** [comment]
You're right. I searched and somehow didn't find that.
