### ISSUE TITLE
Lots of failing asserts in X509Certificate tests on Ubuntu 16.04

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#14166]
e.g.
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu16.04_debug/30/consoleText
```
     at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
     at System.Environment.get_StackTrace()
     at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
     at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.EnsureFilePermissions(FileStream stream, UInt32 userId) in /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.04_debug/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/DirectoryBasedStoreProvider.cs:line 384
     at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal) in /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.04_debug/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/DirectoryBasedStoreProvider.cs:line 189
     at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate) in /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.04_debug/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Store.cs:line 135
     at Internal.Cryptography.Pal.ChainPal.SaveIntermediateCertificates(X509ChainElement[] chainElements, HashSet`1 downloaded) in /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.04_debug/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/ChainPal.cs:line 158
     at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout) in /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.04_debug/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/ChainPal.cs:line 90
     at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException) in /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.04_debug/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Chain.cs:line 118
     at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate) in /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.04_debug/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Chain.cs:line 105
     at System.Security.Cryptography.X509Certificates.Tests.ChainTests.get_TrustsMicrosoftDotComRoot() in /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.04_debug/src/System.Security.Cryptography.X509Certificates/tests/ChainTests.cs:line 27
```

**Comment by bartonjs** [comment]
Sounds like our Ubuntu 16.04 is now contaminated with NTFS.

**Comment by steveharter** [comment]
Line 384 is verifying there are no forbiddenPermissions
```
                Debug.Assert(Interop.Sys.FStat(stream.SafeFileHandle, out stat) == 0);
                Debug.Assert((stat.Mode & (int)requiredPermissions) == (int)requiredPermissions);
>>              Debug.Assert((stat.Mode & (int)forbiddenPermissions) == 0);
```
which were supposedly just cleared via successful FChMod

**Comment by bartonjs** [comment]
That code should be moved from an assert to an exception since we know of cases where it fails.  But the real bug is https://github.com/dotnet/corefx/issues/9293, where our images get $HOME mounted on NTFS (where chmod doesn't work)

**Comment by bartonjs** [comment]
(And to clear the test problem, Ubuntu 16.04 should be added to the list of OSes that are not "IsReliableInCI", or whatever the conditional property is for those tests)

**Comment by steveharter** [comment]
Update: we need to throw instead of asserting in the three cases above

**Comment by karelz** [comment]
@steveharter are you working on it? It's assigned to you for quite a while ...
