### ISSUE TITLE
Failure in ClientAsyncAuthenticate_AllServerAllClient_Success in CI

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#14177]
```
     System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_AllServerAllClient_Success [FAIL]
        System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
        Stack Trace:
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Net.Security\src\System\Net\Security\SslState.cs(884,0): at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Net.Security\src\System\Net\Security\SslState.cs(1094,0): at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Net.Security\src\System\Net\Security\SslState.cs(752,0): at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Net.Security\src\System\Net\Security\SslState.cs(722,0): at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Net.Security\src\System\Net\Security\SslStream.cs(132,0): at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           D:\j\workspace\outerloop_win---7ad0ce03\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(19,0): at System.Threading.Tasks.TaskTimeoutExtensions.<TimeoutAfter>d__0.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Net.Security\tests\FunctionalTests\ClientAsyncAuthenticateTest.cs(151,0): at System.Net.Security.Tests.ClientAsyncAuthenticateTest.<ClientAsyncSslHelper>d__14.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           D:\j\workspace\outerloop_win---7ad0ce03\src\System.Net.Security\tests\FunctionalTests\ClientAsyncAuthenticateTest.cs(75,0): at System.Net.Security.Tests.ClientAsyncAuthenticateTest.<ClientAsyncAuthenticate_AllServerAllClient_Success>d__7.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Using D:\j\workspace\outerloop_win---7ad0ce03\packages\ as folder for resolving package dependencies.
  Executing in D:\j\workspace\outerloop_win---7ad0ce03\bin\tests\AnyOS.AnyCPU.Debug\System.Threading.Performance.Tests\default.netcoreapp1.1\ 
  Hard linking dependent files... 
  Finished:    System.Net.Security.Tests
```
Does not seem related to the PR https://github.com/dotnet/corefx/pull/14158 
Similar to https://github.com/dotnet/corefx/issues/10909

@davidsh @CIPop

**Comment by ianhays** [comment]
Tracking this failure in #16534. Please comment there with any failure reports instead of re-opening this issue.
