### ISSUE TITLE
standardNumericalFunctions_PowTest failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1432]
```
ErRoR!!! Actual Complex (-Infinity, -6.19524038874532E+307) imaginary part to be equal to Double:-Infinity
  Error pOw-Err2534! Pow ((-1.28872245606257E+308, 2.39662253395911E+307), (0.999164775479196, -0.335819169569676))
     System.Numerics.Tests.standardNumericalFunctions_PowTest.RunTests_RandomValidValues [FAIL]
        Verification Failed
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Runtime.Numerics\tests\Complex\standardNumericalFunctions_Pow.cs(34,0): at System.Numerics.Tests.standardNumericalFunctions_PowTest.VerifyPow(Double a, Double b, Double c, Double d)
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Runtime.Numerics\tests\Complex\standardNumericalFunctions_Pow.cs(110,0): at System.Numerics.Tests.standardNumericalFunctions_PowTest.RunTests_PowComplex(Double a, Double b)
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Runtime.Numerics\tests\Complex\standardNumericalFunctions_Pow.cs(149,0): at System.Numerics.Tests.standardNumericalFunctions_PowTest.RunTests_RandomValidValues()
```

**Comment by stephentoub** [comment]
This failed again:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release/744/console 
```
System.Numerics.Tests.standardNumericalFunctions_PowTest.RunTests_RandomValidValues [FAIL]
        Pow ((-1.47312966505531E+308, 1.08130045515798E+307), (0.999750766903046, -0.309201333815791))
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Runtime.Numerics\tests\Complex\ComplexTestSupport.cs(170,0): at ComplexTestSupport.Support.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, String message)
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Runtime.Numerics\tests\Complex\standardNumericalFunctions_Pow.cs(29,0): at System.Numerics.Tests.standardNumericalFunctions_PowTest.VerifyPow(Double a, Double b, Double c, Double d)
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Runtime.Numerics\tests\Complex\standardNumericalFunctions_Pow.cs(93,0): at System.Numerics.Tests.standardNumericalFunctions_PowTest.RunTests_PowComplex(Double a, Double b)
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Runtime.Numerics\tests\Complex\standardNumericalFunctions_Pow.cs(132,0): at System.Numerics.Tests.standardNumericalFunctions_PowTest.RunTests_RandomValidValues()
```

**Comment by stephentoub** [comment]
This just failed again:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/2913/console
```
System.Numerics.Tests.standardNumericalFunctions_PowTest.RunTests_RandomValidValues [FAIL]
        Pow ((-1.47312966505531E+308, 1.08130045515798E+307), (0.999750766903046, -0.309201333815791))
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Runtime.Numerics\tests\Complex\ComplexTestSupport.cs(181,0): at ComplexTestSupport.Support.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, String message)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Runtime.Numerics\tests\Complex\standardNumericalFunctions_Pow.cs(29,0): at System.Numerics.Tests.standardNumericalFunctions_PowTest.VerifyPow(Double a, Double b, Double c, Double d)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Runtime.Numerics\tests\Complex\standardNumericalFunctions_Pow.cs(93,0): at System.Numerics.Tests.standardNumericalFunctions_PowTest.RunTests_PowComplex(Double a, Double b)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Runtime.Numerics\tests\Complex\standardNumericalFunctions_Pow.cs(132,0): at System.Numerics.Tests.standardNumericalFunctions_PowTest.RunTests_RandomValidValues()
```
Investigating...
