### ISSUE TITLE
System.IO.FileSystem.Tests fails on my Dev box

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#14576]
```XML
    <collection total="38" passed="37" failed="1" skipped="0" name="Test collection for System.IO.Tests.FileInfo_Open_fm_fa_fs" time="0.237">
      <test name="System.IO.Tests.FileInfo_Open_fm_fa_fs.FileModeTruncateExisting" type="System.IO.Tests.FileInfo_Open_fm_fa_fs" method="FileModeTruncateExisting" time="0.0045111" result="Pass" />
      <test name="System.IO.Tests.FileInfo_Open_fm_fa_fs.FileShareDeleteExisting" type="System.IO.Tests.FileInfo_Open_fm_fa_fs" method="FileShareDeleteExisting" time="0.0037783" result="Pass" />
      <test name="System.IO.Tests.FileInfo_Open_fm_fa_fs.FileShareOpen" type="System.IO.Tests.FileInfo_Open_fm_fa_fs" method="FileShareOpen" time="0.0040571" result="Fail">
        <failure exception-type="System.IO.IOException">
          <message><![CDATA[System.IO.IOException : The process cannot access the file 'C:\\Users\\crispop\\AppData\\Local\\Temp\\FileInfo_Open_fm_fa_fs_af1cc3bz.wbf\\FileShareOpen_43' because it is being used by another process.]]></message>
          <stack-trace><![CDATA[   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.FileInfo.Open(FileMode mode, FileAccess access, FileShare share)
   at System.IO.Tests.FileInfo_Open_fm_fa_fs.CreateFileStream(String path, FileMode mode, FileAccess access, FileShare share) in S:\c1\src\System.IO.FileSystem\tests\FileInfo\Open.cs:line 44
   at System.IO.Tests.FileStream_ctor_str_fm_fa_fs.FileShareOpen() in S:\c1\src\System.IO.FileSystem\tests\FileStream\ctor_str_fm_fa_fs.cs:line 56]]></stack-trace>
        </failure>
      </test>

```

After the test ran (and failed):

```
C:\WINDOWS\system32>\sysint\handle.exe C:\\Users\\crispop\\AppData\\Local\\Temp\\FileInfo_Open_fm_fa_fs_af1cc3bz.wbf\\FileShareOpen_43

Nthandle v4.1 - Handle viewer
Copyright (C) 1997-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

No matching handles found.
```

Flighted Windows Build: 14994

**Comment by CIPop** [comment]
@JeremyKhune, @ianhays PTAL

**Comment by CIPop** [comment]
@JeremyKuhne , @ianhays PTAL

**Comment by CIPop** [comment]
PS: @JeremyKuhne your name/alias are misspelled in https://github.com/dotnet/corefx/blob/af424759ba2b86e24f110a418a9112f0c5d8107d/Documentation/project-docs/issue-guide.md (causing my copy/paste to fail):

System.IO	@JeremyKhune, @ianhays

**Comment by JeremyKuhne** [comment]
Thanks for letting me know about the alias. @karelz Can you fix the doc?

I'm unaware of any issues. I would assume you've got some other service touching them while the tests are in progress. You should be able to catch the culprit using [ProcessMonitor](https://technet.microsoft.com/en-us/sysinternals/processmonitor).

**Comment by karelz** [comment]
@JeremyKuhne updated, sorry for the typo! BTW: It was right in Configuration line & in the link to your profile in the IO line, just wrong text in IO line.

**Comment by danmosemsft** [comment]
@CIPop have you seen this since? If not let's close it.

**Comment by CIPop** [comment]
I haven't seen this in a while: closing.
