### ISSUE TITLE
UnauthorizedAccessException type incompatible between netstandard1.4 and netcore50 

### ISSUE THREAD

**Issue by tomkuijsten** [dotnet/corefx#14601]
I created a **netstandard1.4** project which generates a nuget package. There is a piece of code in this project:

```cs
string baseDir = "";
try
{
    // this will throw an UnauthorizedAccessException on the pi
    baseDir = AppContext.BaseDirectory;
}
catch (UnauthorizedAccessException)
{
    baseDir = Directory.GetCurrentDirectory();
}
```

When I install this package in a UWP (**netcore50**) project and (in my case) debug it on a Raspberry Pi, the catch statement is never called. When I put a `try...catch...` in the UWP project itself, it does catch the error. The only explanation I can think of is that the `UnauthorizedAccessException` during compile time in a netstandard project is not compatible with the runtime one used for UWP.

Relevant packages used:
 - System.Runtime 4.3.0

Am I correct, or am I doing something totally wrong?

**Comment by AlexGhiondea** [comment]
@tomkuijsten that is a possibility. Can you print the type of the exception (fully qualified) at the moment it is caught in the app?

/cc @SedarG

**Comment by tomkuijsten** [comment]
Will probably be after Christmas, but yes, I'll post the exception.

**Comment by tomkuijsten** [comment]
This is the exception that is caught in th app:

```
System.UnauthorizedAccessException: Access to the path 'C:\windows\system32\config' is denied.
   at System.IO.Win32FileSystemEnumerableIterator`1.AddSearchableDirsToList(PathPair localSearchData)
   at System.IO.Win32FileSystemEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Bronkhorst.Composition.CompositionContainer.GetFilesInCurrentDirectory()
   at Bronkhorst.Composition.CompositionContainer.GetAssemblyNamesToLoad()
   at Bronkhorst.Composition.CompositionContainer.<GetAssemblies>d__12.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Bronkhorst.Composition.CompositionContainer.InitializeContainer()
   at Bronkhorst.Composition.CompositionContainer.Resolve(Object target)
   at Bronkhorst.Logging.LogAdapterResolver.<>c.<.cctor>b__5_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Bronkhorst.Logging.Logger.ShouldLogInfo()
   at Bronkhorst.Logging.Logger.Info(Func`1 messageBuilder)
   at Bronkhorst.Logging.Logger.Info(String message)
   at Bronkhorst.Logging.LogManager.EnableInfoLogging(TimeSpan duration)
   at Bronkhorst.InstrumentCommunication.App.StartupTask.<Run>d__2.MoveNext()
```

**Comment by AlexGhiondea** [comment]
@tomkuijsten sorry for taking this long to get back to you and thanks for posting the exception!

Could you share the project you are using (or a simplified repro)?

**Comment by tomkuijsten** [comment]
I'm sorry, but I can't reproduce the problem anymore. I tried creating a simplified reproduction scenario, but it just works, every time. I could imagine that some package update fixed the problem,. I suggest to close the issue, if I somehow experience it again, I'll create a repro project first before adding an issue again.

**Comment by AlexGhiondea** [comment]
@tomkuijsten I am glad to hear it works now! I will close this and if you see this again, feel free to file a new issue!
