### ISSUE TITLE
The System.IO.FileSystem.Watcher.Tests assemble threw 'System.Diagnostics.Debug+DebugAssertException' when building 

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#14701]
No results generated.

2016-12-22 15:30:03,398: INFO: proc(55): run_and_log_output: Output: Unhandled Exception: System.Diagnostics.Debug+DebugAssertException: FILE_ACTION_RENAMED_NEW_NAME with no old name! [ 3jmpqvmh.m5t]
2016-12-22 15:30:03,398: INFO: proc(55): run_and_log_output: Output: 
2016-12-22 15:30:03,398: INFO: proc(55): run_and_log_output: Output:    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
2016-12-22 15:30:03,398: INFO: proc(55): run_and_log_output: Output:    at System.Environment.get_StackTrace()
2016-12-22 15:30:03,398: INFO: proc(55): run_and_log_output: Output:    at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
2016-12-22 15:30:03,398: INFO: proc(55): run_and_log_output: Output:    at System.Diagnostics.Debug.Fail(String message)
2016-12-22 15:30:03,398: INFO: proc(55): run_and_log_output: Output:    at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer)
2016-12-22 15:30:03,400: INFO: proc(55): run_and_log_output: Output:    at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
2016-12-22 15:30:03,400: INFO: proc(55): run_and_log_output: Output:    at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
2016-12-22 15:30:03,400: INFO: proc(55): run_and_log_output: Output:    at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
2016-12-22 15:30:03,400: INFO: proc(55): run_and_log_output: Output:    at System.Diagnostics.Debug.WindowsDebugLogger.ShowAssertDialog(String stackTrace, String message, String detailMessage)
2016-12-22 15:30:03,400: INFO: proc(55): run_and_log_output: Output:    at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
2016-12-22 15:30:03,400: INFO: proc(55): run_and_log_output: Output:    at System.Diagnostics.Debug.Fail(String message)
2016-12-22 15:30:03,400: INFO: proc(55): run_and_log_output: Output:    at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer)
2016-12-22 15:30:03,400: INFO: proc(55): run_and_log_output: Output:    at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
2016-12-22 15:30:03,400: INFO: proc(55): run_and_log_output: Output:    at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
2016-12-22 15:30:03,400: INFO: proc(55): run_and_log_output: Output:    at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

Details: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161222.03/workItem/System.IO.FileSystem.Watcher.Tests/details/859862c0-e711-46dd-9d09-30d6df458644

Build: 20161222.03 - Core Tests
Failing configurations: Windows.10.Core.AMD64

**Comment by danmosemsft** [comment]
Seems a broken [assumption about OS behavior](https://github.com/dotnet/corefx/blob/d8fc81080723d58ca569c891ac1ebd86119b6f88/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs#L294) that FILE_ACTION_RENAMED_OLD_NAME would precede FILE_ACTION_RENAMED_NEW_NAME

I see this code has not changed in a long time. If it's the OS, perhaps the right change is just to remove this assert, because the code recovers:

```
                   If a NEW_NAME action comes in with no previous OLD_NAME, we assert and fire
                   a rename event with the OldName field null.
```

Although RenameEventArgs don't document that OldName can be null, this appears to be what Desktop does also. @ianhays @JeremyKuhne do you agree we should remove the assert? If this turns up in Desktop runs also, the test might have to just catch it.

Aside for my education: OSX and Linux renames seem to be IN_MOVEDTO followed by IN_MOVEDFROM and there is some attempt to pair those but if that doesn't work it's clearly correct to turn them into create/delete events instead.
[OSX](https://github.com/dotnet/corefx/blob/d8fc81080723d58ca569c891ac1ebd86119b6f88/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs#L391) 
[Linux](https://github.com/dotnet/corefx/blob/d8fc81080723d58ca569c891ac1ebd86119b6f88/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Linux.cs#L710)

**Comment by ianhays** [comment]
> @ianhays @JeremyKuhne do you agree we should remove the assert? If this turns up in Desktop runs also, the test might have to just catch it.

I'd say so, yeah.

>Aside for my education: OSX and Linux renames seem to be IN_MOVEDTO followed by IN_MOVEDFROM and there is some attempt to pair those but if that doesn't work it's clearly correct to turn them into create/delete events instead.

Correct. Getting an improperly paired rename is far more commonplace on OSX/Linux than it is on Windows. 

This is particularly true for any CoreFX File/Directory `Move`s which are implemented in such a way that `Create`/`Delete` is triggered by the OS instead of `Rename`. It doesn't touch the code you linked, but it's a similar case where Create/Delete occur instead of Rename on a Unix system.

**Comment by ianhays** [comment]
Work item here is to remove the Debug statement from [FileSystemWatcher[(https://github.com/dotnet/corefx/blob/d8fc81080723d58ca569c891ac1ebd86119b6f88/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs#L294)
