### ISSUE TITLE
System.Globalization.Calendars.Tests threw "System.ArgumentOutOfRangeException"

### ISSUE THREAD

**Issue by jiangzeng** [dotnet/corefx#14984]
No results generated.

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170108.02/workItem/System.Globalization.Calendars.Tests/details/c9ef7300-4763-45b3-8e8a-886180e6bb61

Log:
```
2017-01-08 15:21:42,927: INFO: proc(55): run_and_log_output: Output:   Discovering: System.Globalization.Calendars.Tests
2017-01-08 15:21:43,270: INFO: proc(55): run_and_log_output: Output:   Discovered:  System.Globalization.Calendars.Tests
2017-01-08 15:21:43,270: INFO: proc(55): run_and_log_output: Output:   Starting:    System.Globalization.Calendars.Tests
2017-01-08 15:22:03,395: INFO: proc(55): run_and_log_output: Output:     System.Globalization.Tests.CalendarHelpers.GetDaysInMonth_Invalid [FAIL]
2017-01-08 15:22:03,395: INFO: proc(55): run_and_log_output: Output:       System.ArgumentOutOfRangeException : Non-negative number required.
2017-01-08 15:22:03,395: INFO: proc(55): run_and_log_output: Output:       Parameter name: year
2017-01-08 15:22:03,395: INFO: proc(55): run_and_log_output: Output:       Stack Trace:
2017-01-08 15:22:03,395: INFO: proc(55): run_and_log_output: Output:            at System.Globalization.GregorianCalendarHelper.GetGregorianYear(Int32 year, Int32 era)
2017-01-08 15:22:03,395: INFO: proc(55): run_and_log_output: Output:            at System.Globalization.EastAsianLunisolarCalendar.CheckYearRange(Int32 year, Int32 era)
2017-01-08 15:22:03,395: INFO: proc(55): run_and_log_output: Output:            at System.Globalization.EastAsianLunisolarCalendar.GetMonthsInYear(Int32 year, Int32 era)
2017-01-08 15:22:03,395: INFO: proc(55): run_and_log_output: Output:         D:\A\_work\64\s\corefx\src\System.Globalization.Calendars\tests\CalendarHelpers.cs(126,0): at System.Globalization.Tests.CalendarHelpers.<Year_Month_Day_Era_TestData>d__9.MoveNext()
2017-01-08 15:22:03,395: INFO: proc(55): run_and_log_output: Output:            at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
2017-01-08 15:22:03,411: INFO: proc(55): run_and_log_output: Output:     System.Globalization.Tests.CalendarHelpers.IsLeapDay_Invalid [FAIL]
2017-01-08 15:22:03,411: INFO: proc(55): run_and_log_output: Output:       System.ArgumentOutOfRangeException : Non-negative number required.
2017-01-08 15:22:03,411: INFO: proc(55): run_and_log_output: Output:       Parameter name: year
2017-01-08 15:22:03,411: INFO: proc(55): run_and_log_output: Output:       Stack Trace:
2017-01-08 15:22:03,411: INFO: proc(55): run_and_log_output: Output:            at System.Globalization.GregorianCalendarHelper.GetGregorianYear(Int32 year, Int32 era)
2017-01-08 15:22:03,411: INFO: proc(55): run_and_log_output: Output:            at System.Globalization.EastAsianLunisolarCalendar.CheckYearRange(Int32 year, Int32 era)
2017-01-08 15:22:03,411: INFO: proc(55): run_and_log_output: Output:            at System.Globalization.EastAsianLunisolarCalendar.GetMonthsInYear(Int32 year, Int32 era)
2017-01-08 15:22:03,411: INFO: proc(55): run_and_log_output: Output:         D:\A\_work\64\s\corefx\src\System.Globalization.Calendars\tests\CalendarHelpers.cs(126,0): at System.Globalization.Tests.CalendarHelpers.<Year_Month_Day_Era_TestData>d__9.MoveNext()
2017-01-08 15:22:03,411: INFO: proc(55): run_and_log_output: Output:            at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
2017-01-08 15:22:04,006: INFO: proc(55): run_and_log_output: Output:     System.Globalization.Tests.CalendarHelpers.IsLeapMonth_Invalid [FAIL]
2017-01-08 15:22:04,006: INFO: proc(55): run_and_log_output: Output:       System.ArgumentOutOfRangeException : Non-negative number required.
2017-01-08 15:22:04,006: INFO: proc(55): run_and_log_output: Output:       Parameter name: year
2017-01-08 15:22:04,006: INFO: proc(55): run_and_log_output: Output:       Stack Trace:
2017-01-08 15:22:04,006: INFO: proc(55): run_and_log_output: Output:            at System.Globalization.GregorianCalendarHelper.GetGregorianYear(Int32 year, Int32 era)
2017-01-08 15:22:04,006: INFO: proc(55): run_and_log_output: Output:            at System.Globalization.EastAsianLunisolarCalendar.CheckYearRange(Int32 year, Int32 era)
2017-01-08 15:22:04,006: INFO: proc(55): run_and_log_output: Output:            at System.Globalization.EastAsianLunisolarCalendar.GetMonthsInYear(Int32 year, Int32 era)
2017-01-08 15:22:04,006: INFO: proc(55): run_and_log_output: Output:         D:\A\_work\64\s\corefx\src\System.Globalization.Calendars\tests\CalendarHelpers.cs(126,0): at System.Globalization.Tests.CalendarHelpers.<Year_Month_Day_Era_TestData>d__9.MoveNext()
2017-01-08 15:22:04,006: INFO: proc(55): run_and_log_output: Output:            at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
2017-01-08 15:22:04,022: INFO: proc(55): run_and_log_output: Output:   Finished:    System.Globalization.Calendars.Tests
2017-01-08 15:22:04,036: INFO: proc(55): run_and_log_output: Output: === TEST EXECUTION SUMMARY ===
2017-01-08 15:22:04,036: INFO: proc(55): run_and_log_output: Output:    System.Globalization.Calendars.Tests  Total: 1435, Errors: 0, Failed: 3, Skipped: 0, Time: 0.849s
```

Build: 20170108.02
Configuration: Windows.10.Amd64

**Comment by jiangzeng** [comment]
Should be the same issue with #10785, but no results generated.

**Comment by jiangzeng** [comment]
In build 20170109.02, result generated, but the issue is the same:
System.Globalization.Tests.CalendarHelpers/GetDaysInMonth_Invalid
System.Globalization.Tests.CalendarHelpers/IsLeapDay_Invalid
System.Globalization.Tests.CalendarHelpers/IsLeapMonth_Invalid

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170109.02/workItem/System.Globalization.Calendars.Tests
