### ISSUE TITLE
Looks like we have never run the System.Security.AccessControl tests

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#15041]
While investigating why these tests were failing on dev/eng branch, I found out that they are also failing in master just that we haven't been running them. The reason why is because the target that selects which projects to run the tests from (`FilterProjectsToTest`) has a condition into making sure that the test .builds file ends with a `.Tests.builds` and it looks like for System.Security.AccessControl, we have always had it like: `System.Security.AccessControl.builds` making it never to run tests.

cc: @ianhays (who added the .builds file in the first place)

**Comment by ianhays** [comment]
I ran them before I checked them in so at least we know they passed at *some* point :) This is my bad though, looks like I missed that condition.

**Comment by ianhays** [comment]
Looks the failures on Release are all of this form:

```
System.Security.AccessControl.Tests.CommonSecurityDescriptor_SetDiscretionaryAclProtection.TestSetDiscretionaryAclProtection(isContainer: True, isDS: False, sddl: \"O:LAG:SYD:PAI(D;OI;WO;;;BG)(OD;;CCDC;6da8a4ff-0e52\"..., isProtected: False, preserveInheritance: Tr
 ue, verifierSddl: \"O:LAG:SYD:AI(D;OI;WO;;;BG)(OD;;CCDC;6da8a4ff-0e52-\"...) [FAIL]
       System.InvalidOperationException : Operation is not valid due to the current state of the object.
       Stack Trace:
          D:\git\corefx\src\system.security.accesscontrol\src\System\Security\AccessControl\SecurityDescriptor.cs(250,0): at System.Security.AccessControl.GenericSecurityDescriptor.GetSddlForm(AccessControlSections includeSections)
          D:\git\corefx\src\system.security.accesscontrol\tests\CommonSecurityDescriptor\CommonSecurityDescriptor_SetDiscretionaryAclProtection.cs(32,0): at System.Security.AccessControl.Tests.CommonSecurityDescriptor_SetDiscretionaryAclProtection.TestSetDiscretionaryA
 clProtection(Boolean isContainer, Boolean isDS, String sddl, Boolean isProtected, Boolean preserveInheritance, String verifierSddl)
```

and on Debug they fail a **bunch** of Debug assertions:
```
     System.Security.AccessControl.Tests.CommonSecurityDescriptor_GetBinaryForm.TestGetBinaryForm(isContainer: True, isDS: False, sddl: \"O:LAG:SYD:(A;;KA;;;SY)(A;;KA;;;S-1-5-19-1)(OA;;CCD\"..., verifierSddl: \"O:LAG:SYD:(A;;KA;;;SY)(A;;KA;;;S-1-5-19-1)(A;;LCRP\"..., of
  fset: 0) [FAIL]
        System.Diagnostics.Debug+DebugAssertException : binaryForm produced invalid output

           at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
           at System.Environment.get_StackTrace()
           at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
           at System.Security.AccessControl.GenericSecurityDescriptor.GetSddlForm(AccessControlSections includeSections) in D:\git\corefx\src\system.security.accesscontrol\src\System\Security\AccessControl\SecurityDescriptor.cs:line 244
           at System.Security.AccessControl.Tests.CommonSecurityDescriptor_GetBinaryForm.TestGetBinaryForm(Boolean isContainer, Boolean isDS, String sddl, String verifierSddl, Int32 offset) in D:\git\corefx\src\system.security.accesscontrol\tests\CommonSecurityDescripto
  r\CommonSecurityDescriptor_GetBinaryForm.cs:line 96
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
           at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
           at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 147
           at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 224
           at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
           at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<InvokeTestMethodAsync>b__1()
           at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
           at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
           at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction)
           at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
           at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
           at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code)
           at Xunit.Sdk.TestInvoker`1.<InvokeTestMethodAsync>d__46.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 208
           at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
           at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance)
           at Xunit.Sdk.TestInvoker`1.<<RunAsync>b__45_0>d.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 173
           at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
           at Xunit.Sdk.TestInvoker`1.<RunAsync>b__45_0()
           at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.core\Sdk\ExceptionAggregator.cs:line 107
           at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
           at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
           at Xunit.Sdk.XunitTestRunner.<InvokeTestAsync>d__4.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestRunner.cs:line 67
           at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
           at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator)
           at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.core\Sdk\ExceptionAggregator.cs:line 0
           at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
           at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
           at Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestRunner.cs:line 0
           at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
           at Xunit.Sdk.TestRunner`1.RunAsync()
           at Xunit.Sdk.XunitTheoryTestCaseRunner.<RunTestAsync>d__9.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\XunitTheoryTestCaseRunner.cs:line 108
           at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
           at Xunit.Sdk.XunitTheoryTestCaseRunner.RunTestAsync()
           at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestCaseRunner.cs:line 82
           at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
           at Xunit.Sdk.TestCaseRunner`1.RunAsync()
           at Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestMethodRunner.cs:line 45
```

**Comment by joperezr** [comment]
yup, that is what I was seeing as well, I tried to do a bit of debugging into the issue using windbg, but didn't get to any big conclusion.

**Comment by Jiayili1** [comment]
This issue is repro on build 20170125.02, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170125.02/workItem/System.Security.AccessControl.Tests/analysis/xunit/System.Security.AccessControl.Tests.CommonSecurityDescriptor_CreateFromSddlForm~2FTestCreateFromSddlForm(isContainer:%20False,%20isDS:%20False,%20sddl:%20%5C%22O:LAG:SYD:AI(A;ID;FA;;;BA)(A;ID;FA;;;BO)(A;ID;FA...

**Comment by danmosemsft** [comment]
@ianhays it's seems above the tests in the assembly are indeed enabled? if not would be good to get them enabled in bulk now and disable failing tests with specific issues so we know how much debt there is and see any regressions.

**Comment by ianhays** [comment]
@danmosemsft huh yeah they must be enabled if we're getting failure reports now. I imagine it's from the engineering changes that modified how we chose test projects to run. In any case, you're right that there's still a good amount of debt here to run the tests and get them passing without these kinds of failures.

**Comment by danmosemsft** [comment]
Can you confirm they're all enabled? If so, we can close this issue.

**Comment by ianhays** [comment]
Well I don't know why they're failing the MC runs, but they're not running on my local machine because of [this line in the csproj](https://github.com/dotnet/corefx/blob/master/src/System.Security.AccessControl/tests/System.Security.AccessControl.Tests.csproj#L8). When I take that out, they all fail.

**Comment by ianhays** [comment]
I'm just going to take this.
