### ISSUE TITLE
System.Runtime.Loader tests don't work when running with shared framework.

### ISSUE THREAD

**Issue by karajas** [dotnet/corefx#15101]
As a part of https://github.com/dotnet/corefx/pull/14823, the following two tests fail.
System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadFromAssemblyName_ValidTrustedPlatformAssembly
```
System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadFromAssemblyName_ValidTrustedPlatformAssembly [FAIL]
        System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime.dll'. The system cannot find the file specified.
        ---- System.IO.FileNotFoundException : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
        Stack Trace:
              at System.Runtime.Loader.AssemblyLoadContext.nGetFileInformation(String s)
              at System.Runtime.Loader.AssemblyLoadContext.GetAssemblyName(String assemblyPath)
           D:\git\corefx\src\System.Runtime.Loader\tests\AssemblyLoadContextTest.cs(99,0): at System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadFromAssemblyName_ValidTrustedPlatformAssembly()
  ----- Inner Stack Trace -----

     System.Runtime.Loader.Tests.AssemblyLoadContextTest.GetAssemblyNameTest_ValidAssembly [FAIL]
        System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime.dll'. The system cannot find the file specified.
        ---- System.IO.FileNotFoundException : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
        Stack Trace:
              at System.Runtime.Loader.AssemblyLoadContext.nGetFileInformation(String s)
              at System.Runtime.Loader.AssemblyLoadContext.GetAssemblyName(String assemblyPath)
           D:\git\corefx\src\System.Runtime.Loader\tests\AssemblyLoadContextTest.cs(27,0): at System.Runtime.Loader.Tests.AssemblyLoadContextTest.GetAssemblyNameTest_ValidAssembly()
           ----- Inner Stack Trace -----`
```
and 
System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext
```
System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext [FAIL]
        System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
        ---- System.IO.FileNotFoundException : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
        Stack Trace:
              at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive)
              at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
              at System.Reflection.Assembly.GetType(String name, Boolean throwOnError)
           D:\git\corefx\src\System.Runtime.Loader\tests\DefaultContext\DefaultLoadContextTest.cs(290,0): at System.Runtime.Loader.Tests.DefaultLoadContextTests.DefaultContextOverrideTPA()
           D:\git\corefx\src\System.Runtime.Loader\tests\DefaultContext\DefaultLoadContextTest.cs(207,0): at System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext()
           ----- Inner Stack Trace -----
              at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
              at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
           D:\git\corefx\src\System.Runtime.Loader\tests\DefaultContext\DefaultLoadContextTest.cs(41,0): at System.Runtime.Loader.Tests.OverrideDefaultLoadContext.Load(AssemblyName assemblyName)
              at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
              at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
```

**Comment by joperezr** [comment]
cc: @rahku do you mind taking a look?

**Comment by rahku** [comment]
These tests depend on framework assemblies to be present in AppContext.BaseDirectory. This is no longer the case now. 
For the second test fix would be to replace AppContext.BaseDirectory with the path to FX dir at this code    https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Loader/tests/DefaultContext/DefaultLoadContextTest.cs#L40

Fix for the first test would be to either pass full path to System.Runtime.dll or change Environment.CurrentDirectory to path to FX at this code 
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Loader/tests/AssemblyLoadContextTest.cs#L98. Setting full path to  System.Runtime.dll is better than changing Environment.CurrentDirectory.

**Comment by joperezr** [comment]
I see, I know that @mellinoe had some similar problems when moving into the new scheme of only having one shared test runtime folder. I doublt we want to pass full path for System.Runtime.dll. Do you mind syncing up with Eric to try to find the best solution for both tests?

**Comment by Jiayili1** [comment]
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Loader/tests/AssemblyLoadContextTest.cs#L19

**Comment by AlexGhiondea** [comment]
@rahku could you take a look at this and figure out what we should do?
