### ISSUE TITLE
TryStartNoGCRegionNegTest test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#15158]
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_release_prtest/23/consoleText
```
Expected: typeof(System.InvalidOperationException)
  Actual:   (No exception was thrown)
     at Xunit.Assert.Throws(Type exceptionType, Exception exception) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 143
     at Xunit.Assert.Throws[T](Func`1 testCode) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 36
     at System.Tests.GCExtendedTests.<>c.<TryStartNoGCRegionNegTest>b__4_0() in D:\j\workspace\outerloop_win---da4c0a7a\src\System.Runtime\tests\System\GCTests.netstandard1.7.cs:line 114
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at RemoteExecutorConsoleApp.Program.Main(String[] args)

```

**Comment by karelz** [comment]
cc @swgillespie

**Comment by danmosemsft** [comment]
@swgillespie ?

**Comment by swgillespie** [comment]
@danmosemsft No update, sorry - haven't had a chance to look yet. Will take a look today or tomorrow.

**Comment by AlexGhiondea** [comment]
@swgillespie do you have an estimate on when you will take a look at this?

**Comment by swgillespie** [comment]
Took a look yesterday - I wasn't able to repro this on my own machine or the DTL machine I obtained. It would be a lot easier to understand what happened if this particular negative test was split into separate negative tests for every case being checked - but at any rate, this code hasn't changed recently.

**Comment by AlexGhiondea** [comment]
@swgillespie should we split the tests then?

**Comment by swgillespie** [comment]
Sure, we can do that - I can do that today.

**Comment by danmosemsft** [comment]
@swgillespie is it ok for you to go ahead and close this now then?

**Comment by danmosemsft** [comment]
folks will reopen if
