### ISSUE TITLE
System.Net.Http.HttpRequestException: Error while copying content to a stream.

### ISSUE THREAD

**Issue by aliveli186** [dotnet/corefx#15206]
The application is a ClickOnce application. When I run it from it's ClickOnce installer the one which checks for updates first and then starts the application I receive "Error while copying content to a stream." error.

But, when I run the application manually from it's installed folder it runs without any error.

Referenced DLL: System.Net.Http\4.3.0\lib\net46\System.Net.Http.dll

```
System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.InternalRegister(Action`1 callback, Object stateForCallback, SynchronizationContext targetSyncContext, ExecutionContext executionContext)
   at System.Threading.CancellationToken.Register(Action`1 callback, Object state, Boolean useSynchronizationContext, Boolean useExecutionContext)
   at System.Threading.CancellationToken.Register(Action`1 callback, Object state)
   at System.Net.Http.WinHttpResponseStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token)
   at System.Net.Http.StreamToStreamCopy.<CopyAsyncAnyStreamToAnyStreamCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__48.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<WaitAndReturnAsync>d__62`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.HttpResponseMessageExtensions.<ReadAsObjectAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Finally`1._.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Do`1._.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2._.Iter.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Throw`1._.Invoke()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.ScheduledItem`2.InvokeCore()
   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue)
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2._.SubscribeInner(IObservable`1 inner)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Defer`1._.OnNext(TValue value)
   at System.Reactive.Linq.ObservableImpl.Using`2._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.TimeInterval`1._.OnNext(TSource value)
   at System.Reactive.SafeObserver`1.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Catch`2._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
   at System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
   at System.Reactive.ObserverBase`1.OnNext(T value)
   at System.Reactive.SafeObserver`1.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.AsObservable`1._.OnNext(TSource value)
   at System.Reactive.Subjects.AsyncSubject`1.OnCompleted()
   at System.Reactive.Threading.Tasks.TaskObservableExtensions.ToObservableDone[TResult](Task`1 task, IObserver`1 subject)
   at System.Reactive.Threading.Tasks.TaskObservableExtensions.<>c__DisplayClass8_0`1.<ToObservableSlow>b__0(Task`1 t)
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by davidsh** [comment]
Since the question is about a ClickOnce application, I'm assuming this issue is about .NET Framework and not .NET Core.

.NET Framework bugs are not generally tracked in this repo.  They are usually tracked in Connect:
https://connect.microsoft.com/visualstudio

Looking at the call stack, it will be difficult to diagnose this without a repro application.  The exception being generated looks like something we have seen before and usually occurs during an HTTP POST operation with a request body.

One way to diagnose this further would be to collect Fiddler traces of both the success and failure cases and compare them.

**Comment by aliveli186** [comment]
On Fiddler there is no error.
The request is sent and received perfectly fine without error.

The application itself is ClickOnce but the code where the exception is thrown is a .net core dll referenced by the ClickOnce application.

**Comment by davidsh** [comment]
If the repro changes due to adding Fiddler to the mix, it means that using a proxy (which is what Fiddler is really) changes the repro scenario.

Since Fiddler interferes with the repro scenario, you should probably use WireShark to capture traces.  Looking at the success and failures traces would help narrow down the problem.

**Comment by aliveli186** [comment]
No fiddler doesn't change anything.
Without fiddler I get the exception, with fiddler I still get the exception but from Fiddler I see the data is sent and received perfectly.
Something causes a CancellationToken to be disposed somewhere while ReadStringAsync is working. (CancellationTokenSource.ThrowObjectDisposedException())

**Comment by davidsh** [comment]
The latest STABLE version of System.Net.Http library, NuGet version 4.3.1, no longer uses WinHTTP/WinHttpHandler as the HTTP stack when running on .NET Framework (Desktop). Instead, it goes back to the same HTTP stack as normal .NET Framework.

So, this bug would not repro anymore with the latest package of System.Net.Http.

Closing this issue for now.  Please try the repro again using the latest System.Net.Http package.
