### ISSUE TITLE
System.Security.Principal.Windows.Tests failing

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#15226]
Result from my dev machine:

```xml
<?xml version="1.0" encoding="utf-8"?>
<assemblies>
  <assembly name="System.Security.Principal.Windows.Tests.dll" environment="64-bit .NET (unknown version) [collection-per-class, parallel (8 threads)]" test-framework="xUnit.net 2.2.0.3300" run-date="2017-01-16" run-time="16:47:05" total="6" passed="3" failed="3" skipped="0" time="0.341" errors="0">
    <errors />
    <collection total="1" passed="0" failed="1" skipped="0" name="Test collection for WindowsPrincipalTests" time="0.031">
      <test name="WindowsPrincipalTests.WindowsPrincipalIsInRoleNeg" type="WindowsPrincipalTests" method="WindowsPrincipalIsInRoleNeg" time="0.0309018" result="Fail">
        <failure exception-type="System.ComponentModel.Win32Exception">
          <message><![CDATA[System.ComponentModel.Win32Exception : The trust relationship between this workstation and the primary domain failed]]></message>
          <stack-trace><![CDATA[   at System.Security.Principal.NTAccount.TranslateToSids(IdentityReferenceCollection sourceAccounts, Boolean& someFailed)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean& someFailed)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.WindowsPrincipal.IsInRole(String role)
   at WindowsPrincipalTests.WindowsPrincipalIsInRoleNeg() in C:\github\geoffkizer\corefx\src\System.Security.Principal.Windows\tests\WindowsPrincipalTests.cs:line 15]]></stack-trace>
        </failure>
      </test>
    </collection>
    <collection total="5" passed="3" failed="2" skipped="0" name="Test collection for WindowsIdentityTests" time="0.125">
      <test name="WindowsIdentityTests.CloneAndProperties(cloneViaSerialization: False)" type="WindowsIdentityTests" method="CloneAndProperties" time="0.0338343" result="Fail">
        <failure exception-type="System.ObjectDisposedException">
          <message><![CDATA[System.ObjectDisposedException : Safe handle has been closed]]></message>
          <stack-trace><![CDATA[   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Advapi32.LsaLookupSids(SafeLsaPolicyHandle handle, Int32 count, IntPtr[] sids, SafeLsaMemoryHandle& referencedDomains, SafeLsaMemoryHandle& names)
   at System.Security.Principal.SecurityIdentifier.TranslateToNTAccounts(IdentityReferenceCollection sourceSids, Boolean& someFailed)
   at System.Security.Principal.SecurityIdentifier.Translate(IdentityReferenceCollection sourceSids, Type targetType, Boolean& someFailed)
   at System.Security.Principal.SecurityIdentifier.Translate(IdentityReferenceCollection sourceSids, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.SecurityIdentifier.Translate(Type targetType)
   at System.Security.Principal.WindowsIdentity.<GetName>b__45_0()
   at System.Security.Principal.WindowsIdentity.<>c__DisplayClass61_0.<RunImpersonatedInternal>b__0(Object <state>)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Security.Principal.WindowsIdentity.RunImpersonatedInternal(SafeAccessTokenHandle token, Action action)
   at System.Security.Principal.WindowsIdentity.RunImpersonated(SafeAccessTokenHandle safeAccessTokenHandle, Action action)
   at System.Security.Principal.WindowsIdentity.GetName()
   at System.Security.Principal.WindowsIdentity.get_Name()
   at WindowsIdentityTests.CloneAndProperties(Boolean cloneViaSerialization) in C:\github\geoffkizer\corefx\src\System.Security.Principal.Windows\tests\WindowsIdentityTests.cs:line 57]]></stack-trace>
        </failure>
      </test>
      <test name="WindowsIdentityTests.CloneAndProperties(cloneViaSerialization: True)" type="WindowsIdentityTests" method="CloneAndProperties" time="0.0817014" result="Fail">
        <failure exception-type="System.ObjectDisposedException">
          <message><![CDATA[System.ObjectDisposedException : Safe handle has been closed]]></message>
          <stack-trace><![CDATA[   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Advapi32.LsaLookupSids(SafeLsaPolicyHandle handle, Int32 count, IntPtr[] sids, SafeLsaMemoryHandle& referencedDomains, SafeLsaMemoryHandle& names)
   at System.Security.Principal.SecurityIdentifier.TranslateToNTAccounts(IdentityReferenceCollection sourceSids, Boolean& someFailed)
   at System.Security.Principal.SecurityIdentifier.Translate(IdentityReferenceCollection sourceSids, Type targetType, Boolean& someFailed)
   at System.Security.Principal.SecurityIdentifier.Translate(IdentityReferenceCollection sourceSids, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.SecurityIdentifier.Translate(Type targetType)
   at System.Security.Principal.WindowsIdentity.<GetName>b__45_0()
   at System.Security.Principal.WindowsIdentity.<>c__DisplayClass61_0.<RunImpersonatedInternal>b__0(Object <state>)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Security.Principal.WindowsIdentity.RunImpersonatedInternal(SafeAccessTokenHandle token, Action action)
   at System.Security.Principal.WindowsIdentity.RunImpersonated(SafeAccessTokenHandle safeAccessTokenHandle, Action action)
   at System.Security.Principal.WindowsIdentity.GetName()
   at System.Security.Principal.WindowsIdentity.get_Name()
   at WindowsIdentityTests.CloneAndProperties(Boolean cloneViaSerialization) in C:\github\geoffkizer\corefx\src\System.Security.Principal.Windows\tests\WindowsIdentityTests.cs:line 57]]></stack-trace>
        </failure>
      </test>
      <test name="WindowsIdentityTests.GetTokenHandle" type="WindowsIdentityTests" method="GetTokenHandle" time="0.0034167" result="Pass" />
      <test name="WindowsIdentityTests.ConstructorsAndProperties" type="WindowsIdentityTests" method="ConstructorsAndProperties" time="0.0052869" result="Pass" />
      <test name="WindowsIdentityTests.GetAnonymousUserTest" type="WindowsIdentityTests" method="GetAnonymousUserTest" time="0.0003863" result="Pass" />
    </collection>
  </assembly>
</assemblies>
```

**Comment by geoffkizer** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<assemblies>
  <assembly name="System.Security.Principal.Windows.Tests.dll" environment="64-bit .NET (unknown version) [collection-per-class, parallel (8 threads)]" test-framework="xUnit.net 2.2.0.3300" run-date="2017-01-16" run-time="16:47:05" total="6" passed="3" failed="3" skipped="0" time="0.341" errors="0">
    <errors />
    <collection total="1" passed="0" failed="1" skipped="0" name="Test collection for WindowsPrincipalTests" time="0.031">
      <test name="WindowsPrincipalTests.WindowsPrincipalIsInRoleNeg" type="WindowsPrincipalTests" method="WindowsPrincipalIsInRoleNeg" time="0.0309018" result="Fail">
        <failure exception-type="System.ComponentModel.Win32Exception">
          <message><![CDATA[System.ComponentModel.Win32Exception : The trust relationship between this workstation and the primary domain failed]]></message>
          <stack-trace><![CDATA[   at System.Security.Principal.NTAccount.TranslateToSids(IdentityReferenceCollection sourceAccounts, Boolean& someFailed)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean& someFailed)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.WindowsPrincipal.IsInRole(String role)
   at WindowsPrincipalTests.WindowsPrincipalIsInRoleNeg() in C:\github\geoffkizer\corefx\src\System.Security.Principal.Windows\tests\WindowsPrincipalTests.cs:line 15]]></stack-trace>
        </failure>
      </test>
    </collection>
    <collection total="5" passed="3" failed="2" skipped="0" name="Test collection for WindowsIdentityTests" time="0.125">
      <test name="WindowsIdentityTests.CloneAndProperties(cloneViaSerialization: False)" type="WindowsIdentityTests" method="CloneAndProperties" time="0.0338343" result="Fail">
        <failure exception-type="System.ObjectDisposedException">
          <message><![CDATA[System.ObjectDisposedException : Safe handle has been closed]]></message>
          <stack-trace><![CDATA[   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Advapi32.LsaLookupSids(SafeLsaPolicyHandle handle, Int32 count, IntPtr[] sids, SafeLsaMemoryHandle& referencedDomains, SafeLsaMemoryHandle& names)
   at System.Security.Principal.SecurityIdentifier.TranslateToNTAccounts(IdentityReferenceCollection sourceSids, Boolean& someFailed)
   at System.Security.Principal.SecurityIdentifier.Translate(IdentityReferenceCollection sourceSids, Type targetType, Boolean& someFailed)
   at System.Security.Principal.SecurityIdentifier.Translate(IdentityReferenceCollection sourceSids, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.SecurityIdentifier.Translate(Type targetType)
   at System.Security.Principal.WindowsIdentity.<GetName>b__45_0()
   at System.Security.Principal.WindowsIdentity.<>c__DisplayClass61_0.<RunImpersonatedInternal>b__0(Object <state>)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Security.Principal.WindowsIdentity.RunImpersonatedInternal(SafeAccessTokenHandle token, Action action)
   at System.Security.Principal.WindowsIdentity.RunImpersonated(SafeAccessTokenHandle safeAccessTokenHandle, Action action)
   at System.Security.Principal.WindowsIdentity.GetName()
   at System.Security.Principal.WindowsIdentity.get_Name()
   at WindowsIdentityTests.CloneAndProperties(Boolean cloneViaSerialization) in C:\github\geoffkizer\corefx\src\System.Security.Principal.Windows\tests\WindowsIdentityTests.cs:line 57]]></stack-trace>
        </failure>
      </test>
      <test name="WindowsIdentityTests.CloneAndProperties(cloneViaSerialization: True)" type="WindowsIdentityTests" method="CloneAndProperties" time="0.0817014" result="Fail">
        <failure exception-type="System.ObjectDisposedException">
          <message><![CDATA[System.ObjectDisposedException : Safe handle has been closed]]></message>
          <stack-trace><![CDATA[   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Advapi32.LsaLookupSids(SafeLsaPolicyHandle handle, Int32 count, IntPtr[] sids, SafeLsaMemoryHandle& referencedDomains, SafeLsaMemoryHandle& names)
   at System.Security.Principal.SecurityIdentifier.TranslateToNTAccounts(IdentityReferenceCollection sourceSids, Boolean& someFailed)
   at System.Security.Principal.SecurityIdentifier.Translate(IdentityReferenceCollection sourceSids, Type targetType, Boolean& someFailed)
   at System.Security.Principal.SecurityIdentifier.Translate(IdentityReferenceCollection sourceSids, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.SecurityIdentifier.Translate(Type targetType)
   at System.Security.Principal.WindowsIdentity.<GetName>b__45_0()
   at System.Security.Principal.WindowsIdentity.<>c__DisplayClass61_0.<RunImpersonatedInternal>b__0(Object <state>)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Security.Principal.WindowsIdentity.RunImpersonatedInternal(SafeAccessTokenHandle token, Action action)
   at System.Security.Principal.WindowsIdentity.RunImpersonated(SafeAccessTokenHandle safeAccessTokenHandle, Action action)
   at System.Security.Principal.WindowsIdentity.GetName()
   at System.Security.Principal.WindowsIdentity.get_Name()
   at WindowsIdentityTests.CloneAndProperties(Boolean cloneViaSerialization) in C:\github\geoffkizer\corefx\src\System.Security.Principal.Windows\tests\WindowsIdentityTests.cs:line 57]]></stack-trace>
        </failure>
      </test>
      <test name="WindowsIdentityTests.GetTokenHandle" type="WindowsIdentityTests" method="GetTokenHandle" time="0.0034167" result="Pass" />
      <test name="WindowsIdentityTests.ConstructorsAndProperties" type="WindowsIdentityTests" method="ConstructorsAndProperties" time="0.0052869" result="Pass" />
      <test name="WindowsIdentityTests.GetAnonymousUserTest" type="WindowsIdentityTests" method="GetAnonymousUserTest" time="0.0003863" result="Pass" />
    </collection>
  </assembly>
</assemblies>`

**Comment by karelz** [comment]
How's the second report different from the first one? They look the same.

Could the first failure be as well bad machine state? "*The trust relationship between this workstation and the primary domain failed*"
Was it one time error or repeating failure of the tests on your machine?

**Comment by geoffkizer** [comment]
Second report is the same, sorry.  When I pasted the first report in, it looked garbled, but now it looks fine.

I get this issue consistently when I am not VPN-ed in.  Is that by design?

**Comment by karelz** [comment]
> When I pasted the first report in, it looked garbled, but now it looks fine.

I edited it -- see the [markup](https://guides.github.com/features/mastering-markdown/) I added (triple backtick with xml as language name as the first line and triple backtick as the last line).

**Comment by danmosemsft** [comment]
@bartonjs , @steveharter any suggestions for the next step?

**Comment by bartonjs** [comment]
Possibly needs to be marked as OuterLoop.  I think what happens is the local workstation says "I don't know what FAKEDOMAIN is, but I'm domain joined, so I'll ask the DC if it's a forest trust thing...", so it reports that the remote lookup failed.

So it depends on the network (unless you're a workgroup machine) => outerloop.  (Alternatively, let it fail for that one error)

**Comment by karelz** [comment]
Ideally we would have a precondition for the test - if it is not satisfied, the test wouldn't run at all.
The next best thing IMO is to burn it into the test - let it detect bad condition proactively and pass the test instead.
The next next best thing is to guess from error code that it was likely the bad condition, so let it pass reactively.

I don't like moving tests into OuterLoop, because they are not hardened. The noise from the test is the same. It just leads people to not trust OuterLoop. We should have nearly same high-bar on OuterLoop as on InnerLoop - the only difference is time to need to run the tests.
That's ideal of course, in practice we do move tests with external dependencies to OuterLoop as they are - with the idea that one day we will harden them. For things which are not-too-costly, let's just do it right away ...

Thoughts?

**Comment by bartonjs** [comment]
> a precondition for the test

I don't know a good precondition for "will an AD trust relationship lookup complete?".  It'd be something like `if domain_joined && has_network && AD_answers`.  That last part can't be preconditioned since a lookup in the precondition doesn't mean it'll still work later.

>  let it detect bad condition proactively and pass the test instead

Same as the precondition.  The test asks AD a question, gets an answer.  Then the test asks the product to ask AD a question, but the network went down, or the remote server got unroutable/died.

Granted, it's pretty rare for that sort of a temporal condition.  So now you just need someone to know how to ask essentially the same question the product would... without using the thing that we want to be testing.

> The next next best thing is to guess from error code that it was likely the bad condition, so let it pass reactively

That is the best that I can think of.  The test passes if the answer is `no` or "I don't know for this specific reason".

**Comment by karelz** [comment]
My suggestion targeted more permanent machine setup / situation - like when you don't have VPN enabled. Not flaky network. Failing in such situation is fine IMO.

If there is no easy precondition like "is DC available" (I assume we ping it with VPN enabled), which would not execute the code we're about to test, then the 3rd option is the best we are left with ...

**Comment by ianhays** [comment]
closing as a duplicate of https://github.com/dotnet/corefx/issues/16511

**Comment by pjanotti** [comment]
@karelz, @bartonjs Is it acceptable to workaround it with something like the code below? I am leveraging ```WellKnownSidTypeTests.AccountIsDomainJoined``` added in April by @ianhays - although the method is small I prefer to reference it here so if we ever need to change it, it is in a single location. 

```c#
    public static bool NotDomainJoined => !WellKnownSidTypeTests.AccountIsDomainJoined();

    [ConditionalFact(nameof(NotDomainJoined))]
    public static void WindowsPrincipalIsInRoleNeg()
    {
        WindowsIdentity windowsIdentity = WindowsIdentity.GetAnonymous();
        WindowsPrincipal windowsPrincipal = new WindowsPrincipal(windowsIdentity);
        var ret = windowsPrincipal.IsInRole("FAKEDOMAIN\\nonexist");
        Assert.False(ret);
    }
```
