### ISSUE TITLE
Fast creating and removing files and directories causes UnauthorizedAccessException or DirectoryNotFoundException

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#15330]
When quickly creating and removing files exceptions are being thrown

Repro:
```csharp
using System;
using System.IO;

namespace ConsoleApplication
{
    class Program
    {
        static void Main(string[] args)
        {
            for (int i = 0; i < 5000; i++)
            {
                string dirName = "dfoo";
                string fileName = "foo.txt";
                DirectoryInfo di = new DirectoryInfo(dirName);
                FileInfo fi = new FileInfo(Path.Combine(di.FullName, fileName));
                di.Create();
                File.WriteAllText(fi.FullName, "foo");

                File.Delete(Path.Combine(di.FullName, fileName));
                Directory.Delete(di.FullName);

                Console.WriteLine(i);
            }
        }
    }
}
```

This has reproed both on coreclr and Desktop - usually between 100-500 iterations (Ocassionally couple thousand)
OS: Windows 10

**Comment by danmosemsft** [comment]
```
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'c:\PLAy\55\dfoo\foo.txt'.
   at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding)
   at System.IO.File.WriteAllText(String path, String contents)
   at ConsoleApplication.Program.Main(String[] args)
```

**Comment by danmosemsft** [comment]
```
Unhandled Exception: System.UnauthorizedAccessException: Access to the path 'c:\PLAy\55\dfoo\foo.txt' is denied.
   at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding)
   at System.IO.File.WriteAllText(String path, String contents)
   at ConsoleApplication.Program.Main(String[] args)

```

**Comment by danmosemsft** [comment]
A 10ms sleep before WriteAllText does not cure it, it just takes more itereations. @JeremyKuhne @ianhays is this kind of race unexpected? Or is it a known OS quirk? I only tried on Windows.

**Comment by JeremyKuhne** [comment]
Deleting a file or removing a directory cannot happen until all file handles are closed- that includes things like anti-virus scanners and the index service. Deleting marks the file/directory for deletion- it doesn't actually delete it. This is expected, and happens with 4.6 as well. (And would if you did this directly with C++ and Win32.)

@krwq I'm going to close this- if you have any other questions about this or any other behavior don't hesitate to ask.

**Comment by krwq** [comment]
@JeremyKuhne Isn't File.WriteAllText and File.Delete etc. waiting for handle to be closed? I fully understand UnauthorizedAccessException - that is fully reasonable that anti-virus starts scanning the file and locking it - the DirectoryNotFoundException is something I wouldn't ever expect here.

If they are not waiting then how do you make sure the file is being created?

**Comment by JeremyKuhne** [comment]
> Isn't File.WriteAllText and File.Delete etc. waiting for handle to be closed?

Yes and no. The [DeleteFile](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363915(v=vs.85).aspx) API is specifically "async" in that it just marks for deletion. There is no easy way to tell when a delete is "committed". File.WriteAllText does close it's handle as soon as it is done.

> DirectoryNotFoundException is something I wouldn't ever expect here

You can imagine how this might happen if the directory that is "pending" delete gets removed in the middle of opening the file handle.

I don't know how to create a good repro of the DirectoryNotFound, but you can see some of the "odd" behavior of Delete in the following:

``` C#
        static void Main(string[] args)
        {
            string tempDirectory = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
            Directory.CreateDirectory(tempDirectory);
            var directoryHandle = CreateFileW(
                tempDirectory,
                (uint)GenericAccessRights.GENERIC_READ,
                FileShare.ReadWrite | FileShare.Delete,
                IntPtr.Zero,
                FileMode.Open,
                (uint)FileFlags.FILE_FLAG_BACKUP_SEMANTICS,
                IntPtr.Zero);

            // The directory will not be removed due to the open handle
            Directory.Delete(tempDirectory);

            // This will succeed
            Directory.CreateDirectory(tempDirectory);

            // This will cause the directory to finally be removed
            directoryHandle.Dispose();
        }

        // https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858.aspx
        [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true, ExactSpelling = true)]
        public static extern SafeFileHandle CreateFileW(
            string lpFileName,
            uint dwDesiredAccess,
            [MarshalAs(UnmanagedType.U4)] System.IO.FileShare dwShareMode,
            IntPtr lpSecurityAttributes,
            [MarshalAs(UnmanagedType.U4)] System.IO.FileMode dwCreationDisposition,
            uint dwFlagsAndAttributes,
            IntPtr hTemplateFile);

        [Flags]
        public enum GenericAccessRights : uint
        {
            GENERIC_READ = 0x80000000,
            GENERIC_WRITE = 0x40000000,
            GENERIC_EXECUTE = 0x20000000,
            GENERIC_ALL = 0x10000000
        }

        [Flags]
        public enum FileFlags : uint
        {
            FILE_FLAG_FIRST_PIPE_INSTANCE = 0x00080000,
            FILE_FLAG_OPEN_NO_RECALL = 0x00100000,
            FILE_FLAG_OPEN_REPARSE_POINT = 0x00200000,
            FILE_FLAG_SESSION_AWARE = 0x00800000,
            FILE_FLAG_POSIX_SEMANTICS = 0x01000000,
            FILE_FLAG_BACKUP_SEMANTICS = 0x02000000,
            FILE_FLAG_DELETE_ON_CLOSE = 0x04000000,
            FILE_FLAG_SEQUENTIAL_SCAN = 0x08000000,
            FILE_FLAG_RANDOM_ACCESS = 0x10000000,
            FILE_FLAG_NO_BUFFERING = 0x20000000,
            FILE_FLAG_OVERLAPPED = 0x40000000,
            FILE_FLAG_WRITE_THROUGH = 0x80000000
        }
```
