### ISSUE TITLE
Win7 outer loop test 'System.Net.Tests.WebSocketTests.AcceptWebSocketAsync_NullSubProtocol_Succeeds' failed with 'System.PlatformNotSupportedException'

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#15380]
Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/lastFailedBuild/consoleText

Message:
~~~
System.Net.Tests.WebSocketTests.AcceptWebSocketAsync_NullSubProtocol_Succeeds [FAIL]
        System.PlatformNotSupportedException : The WebSocket protocol is not supported on this platform.
~~~

Stack Trace:
~~~
D:\j\workspace\outerloop_win---b280fd23\src\Common\src\System\Net\WebSockets\WebSocketValidate.cs(121,0): at System.Net.WebSockets.WebSocketValidate.ThrowPlatformNotSupportedException()
           D:\j\workspace\outerloop_win---b280fd23\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WebSocketHandle.Win32.cs(41,0): at System.Net.WebSockets.WebSocketHandle.CheckPlatformSupport()
           D:\j\workspace\outerloop_win---b280fd23\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\ClientWebSocket.cs(31,0): at System.Net.WebSockets.ClientWebSocket..ctor()
           D:\j\workspace\outerloop_win---b280fd23\src\System.Net.HttpListener\tests\WebSocketTests.cs(35,0): at System.Net.Tests.WebSocketTests.<AcceptWebSocketAsync_NullSubProtocol_Succeeds>d__5.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

Configuration:
OuterLoop_Windows7_debug (build#73)

**Comment by Priya91** [comment]
WinHttpWebSocketCompleteUpgrade is supported only from Win8+ Winhttp 5.1.. This failure is expected, will modify the test to not run on win7.
