### ISSUE TITLE
[CI Failure] System.Data.SqlClient.TdsParser.TryProcessError: "class and token don't match!"

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#15419]
An assert seems to be getting hit here: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/2356/consoleFull

```
17:57:15   Discovering: System.Runtime.Loader.DefaultContext.Tests
17:57:16   class and token don't match!
17:57:16   
17:57:16      at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
17:57:16      at System.Environment.get_StackTrace()
17:57:16      at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
17:57:16      at System.Diagnostics.Debug.Assert(Boolean condition, String message)
17:57:16      at System.Data.SqlClient.TdsParser.TryProcessError(Byte token, TdsParserStateObject stateObj, SqlError& error) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParser.cs:line 3035
17:57:16      at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParser.cs:line 1716
17:57:16      at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs:line 1913
17:57:16      at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs:line 1104
17:57:16      at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs:line 821
17:57:16      at System.Data.SqlClient.Tests.DiagnosticTest.<ExecuteNonQueryErrorTest>b__9_0() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 101
17:57:16      at System.Data.SqlClient.Tests.DiagnosticTest.CollectStatisticsDiagnostics(Action sqlOperation) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 585
17:57:16      at System.Data.SqlClient.Tests.DiagnosticTest.ExecuteNonQueryErrorTest() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 92
```

**Comment by jamesqo** [comment]
There is another assert being hit here: https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/2434/consoleFull

```
18:02:03      at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
18:02:03      at System.Environment.get_StackTrace()
18:02:03      at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
18:02:03      at System.Diagnostics.Debug.Assert(Boolean condition, String message)
18:02:03      at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParser.cs:line 1693
18:02:03      at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParser.cs:line 1589
18:02:03      at System.Data.SqlClient.TdsParser.DrainData(TdsParserStateObject stateObj) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParser.cs:line 3518
18:02:03      at System.Data.SqlClient.TdsParser.Deactivate(Boolean connectionIsDoomed) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParser.cs:line 978
18:02:03      at System.Data.SqlClient.SqlInternalConnectionTds.InternalDeactivate() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlInternalConnectionTds.cs:line 634
18:02:03      at System.Data.SqlClient.SqlInternalConnection.Deactivate() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlInternalConnection.cs:line 178
18:02:03      at System.Data.ProviderBase.DbConnectionInternal.DeactivateConnection() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionInternal.cs:line 361
18:02:03      at System.Data.ProviderBase.DbConnectionPool.DeactivateObject(DbConnectionInternal obj) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs:line 483
18:02:03      at System.Data.ProviderBase.DbConnectionPool.PutObject(DbConnectionInternal obj, Object owningObject) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs:line 1071
18:02:03      at System.Data.ProviderBase.DbConnectionInternal.CloseConnection(DbConnection owningObject, DbConnectionFactory connectionFactory) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionInternal.cs:line 280
18:02:03      at System.Data.SqlClient.SqlConnection.CloseInnerConnection() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnection.cs:line 460
18:02:03      at System.Data.SqlClient.SqlConnection.Close() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnection.cs:line 506
18:02:03      at System.Data.SqlClient.SqlConnection.Dispose(Boolean disposing) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnectionHelper.cs:line 149
18:02:03      at System.ComponentModel.Component.Dispose() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.ComponentModel.Primitives/src/System/ComponentModel/Component.cs:line 121
18:02:03      at System.Data.SqlClient.Tests.DiagnosticTest.<ExecuteNonQueryErrorTest>b__9_0() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 93
18:02:03      at System.Data.SqlClient.Tests.DiagnosticTest.CollectStatisticsDiagnostics(Action sqlOperation) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 585
18:02:03      at System.Data.SqlClient.Tests.DiagnosticTest.ExecuteNonQueryErrorTest() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 92
```

**Comment by jamesqo** [comment]
Here's a different one from the last job:

```
18:02:04      at System.Environment.get_StackTrace()
18:02:04      at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
18:02:04      at System.Diagnostics.Debug.Assert(Boolean condition, String message)
18:02:04      at System.Data.SqlClient.SqlDataReader.TryCloseInternal(Boolean closeReader) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlDataReader.cs:line 634
18:02:04      at System.Data.SqlClient.SqlDataReader.Close() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlDataReader.cs:line 572
18:02:04      at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs:line 2280
18:02:04      at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs:line 2168
18:02:04      at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs:line 1976
18:02:04      at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs:line 1937
18:02:04      at System.Data.SqlClient.SqlCommand.ExecuteScalar() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs:line 754
18:02:04      at System.Data.SqlClient.Tests.DiagnosticTest.<ExecuteScalarErrorTest>b__7_0() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 66
18:02:04      at System.Data.SqlClient.Tests.DiagnosticTest.CollectStatisticsDiagnostics(Action sqlOperation) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 585
18:02:04   Using as the test runtime folder.
18:02:04      at System.Data.SqlClient.Tests.DiagnosticTest.ExecuteScalarErrorTest() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 56
```

**Comment by jamesqo** [comment]
Going to reference https://github.com/dotnet/corefx/pull/15416 so this shows up there

**Comment by danmosemsft** [comment]
@saurabh500 what is the next action on this one? trying to keep test failures not getting too high..

**Comment by saurabh500** [comment]
@danmosemsft PR https://github.com/dotnet/corefx/pull/15780 with the fix
