### ISSUE TITLE
System.Dynamic.Runtime failure in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1544]
```
MESSAGE:
Assert.Equal() Failure Expected: 0 Actual: 1
+++++++++++++++++++
STACK TRACE:
at ManagedTests.DynamicCSharp.Conformance.dynamic.context.indexer.genclass.genclass003.genclass003.Test.DynamicCSharpRunTest() in d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Dynamic.Runtime\tests\Dynamic.Context\Conformance.dynamic.context.indexer.genclass.cs:line 517
```
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/1026/

**Comment by stephentoub** [comment]
Another one of these dynamic tests failed:
```
ManagedTests.DynamicCSharp.Conformance.dynamic.context.indexer.genclass.genclass014.genclass014.Test.DynamicCSharpRunTest [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   1
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Dynamic.Runtime\tests\Dynamic.Context\Conformance.dynamic.context.indexer.genclass.cs(872,0): at ManagedTests.DynamicCSharp.Conformance.dynamic.context.indexer.genclass.genclass014.genclass014.Test.DynamicCSharpRunTest()
```
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/1542/console

I've not investigated to see whether it's the same issue or not.

**Comment by stephentoub** [comment]
This failed again:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release/628/console
```
MESSAGE:
Assert.Equal() Failure Expected: 0 Actual: 1
+++++++++++++++++++
STACK TRACE:
at ManagedTests.DynamicCSharp.Conformance.dynamic.context.indexer.genclass.genclass014.genclass014.Test.DynamicCSharpRunTest() in d:\j\workspace\dotnet_corefx_windows_release\src\System.Dynamic.Runtime\tests\Dynamic.Context\Conformance.dynamic.context.indexer.genclass.cs:line 872
```

**Comment by stephentoub** [comment]
cc: @AlekseyTs, @VSadov

**Comment by VSadov** [comment]
I will take a look. Possibly some ordering dependency.
