### ISSUE TITLE
build.cmd throws null ref exception trying to get help with -?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#15609]
Trying to get help:
```
C:\Users\stoub\Source\Repos\corefx>build.cmd -?

There are new changes on how we build. Use this script only for generic
build instructions that apply for both build native and build managed.
Otherwise:

Before                Now
build.cmd native      build-native.cmd
build.cmd managed     build-managed.cmd

For more information: "https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md"
----------------------------------------------------------------------------


Tools are already initialized.
Error: Object reference not set to an instance of an object.    at Microsoft.DotNet.Execute.Setup.FormatSetting(String option, String value, String type, String toolName)
   at Microsoft.DotNet.Execute.Setup.BuildParametersForCommand(Dictionary`2 commandParameters, String toolName)
   at Microsoft.DotNet.Execute.Setup.BuildCommand(String commandSelectedByUser, List`1 parametersSelectedByUser, Dictionary`2 parameters)
   at Microsoft.DotNet.Execute.Setup.GetHelpCommand(String commandName, String alias)
   at Microsoft.Fx.CommandLine.CommandLineParser.GetHelp(Int32 maxLineWidth, String parameterSetName, Boolean displayGlobalQualifiers)
   at Microsoft.Fx.CommandLine.CommandLineParser.<>c.<ParseForConsoleApplication>b__0_0(CommandLineParser parser)
   at Microsoft.Fx.CommandLine.CommandLineParser.Parse(Action`1 parseBody, Action`1 helpHandler, Action`2 errorHandler, Setup setupContent, String[] args)
   at Microsoft.Fx.CommandLine.CommandLineParser.ParseForConsoleApplication(Action`1 parseBody, String[] args, Setup setupContent)
   at Microsoft.DotNet.Execute.Executor.DefineParameters(String[] args, Setup setupInformation)
```

**Comment by jamesqo** [comment]
I just ran into this exact same issue just now! Was just about to raise an issue.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/buildtools/issues/1305
