### ISSUE TITLE
Failed assert in ProcFsStateToThreadState on Linux and PortableLinux

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#15689]
https://ci.dot.net/job/dotnet_corefx/job/master/job/portablelinux_debug_prtest/6/
```
Unexpected status character
  
     at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
     at System.Environment.get_StackTrace()
     at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
     at System.Diagnostics.Debug.Fail(String message)
     at System.Diagnostics.ProcessManager.ProcFsStateToThreadState(Char c) in /mnt/resource/j/workspace/dotnet_corefx/master/portablelinux_debug_prtest/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessManager.Linux.cs:line 207
     at System.Diagnostics.ProcessManager.CreateProcessInfo(ParsedStat procFsStat, ReusableTextReader reusableReader) in /mnt/resource/j/workspace/dotnet_corefx/master/portablelinux_debug_prtest/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessManager.Linux.cs:line 144
     at System.Diagnostics.Process.GetProcessesByName(String processName, String machineName) in /mnt/resource/j/workspace/dotnet_corefx/master/portablelinux_debug_prtest/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Linux.cs:line 34
     at System.Diagnostics.Tests.ProcessTests.TestGetProcessesByName() in /mnt/resource/j/workspace/dotnet_corefx/master/portablelinux_debug_prtest/src/System.Diagnostics.Process/tests/ProcessTests.cs:line 584
```
cc: @gkhanna79, @mellinoe, @Priya91

**Comment by gkhanna79** [comment]
This test run was clean on https://github.com/dotnet/corefx/pull/15678.

**Comment by gkhanna79** [comment]
@karelz can help route this to appropriate folks to look into.

**Comment by karelz** [comment]
Just setting the area is sufficient - [area owners](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#areas) will get notification.
cc: @Priya91

**Comment by Priya91** [comment]
@gkhanna79 Can you provide instructions on reproing this locally? Just by looking at CI build definition, will executing this on a linux box be sufficient repro, or any additional configuration required?

```
./build.sh -debug -framework:netcoreapp -os:Linux -portableLinux
```

**Comment by gkhanna79** [comment]
The above command is fine (-portableLinux is what triggers the portable build infrastructure). however, you need to execute it on RHEL image (which is what is used for these builds).

**Comment by mellinoe** [comment]
We hit this on a regular CentOS run: https://ci.dot.net/job/dotnet_corefx/job/master/job/centos7.1_debug_prtest/4507/consoleText

**Comment by Priya91** [comment]
It would be nice, if the link points to the test failure instead of entire console text.
