### ISSUE TITLE
'dotnet new' command throws error on OS X 10.9.5

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/corefx#15842]
Moved from https://github.com/dotnet/cli/issues/5588 on behalf of @ebetron
-----

## Steps to reproduce
Follow the install instructions for .NET Core for Mac OS X on https://www.microsoft.com/net/core#macos

## Expected  behavior
A new .NET project created 

## Actual behavior
$ mkdir -p /usr/local/lib
$ ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln: /usr/local/lib//libcrypto.1.0.0.dylib: File exists
$ ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
ln: /usr/local/lib//libssl.1.0.0.dylib: File exists

$ dotnet new

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'CCRandomGenerateBytes' in DLL '/usr/lib/system/libcommonCrypto'.
at Interop.CommonCrypto.CCRandomGenerateBytes(Byte* bytes, Int32 byteCount)
at System.IO.Path.GetCryptoRandomBytesApple(Byte* bytes, Int32 byteCount)
at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
at System.IO.Path.GetRandomFileName()
at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
at Microsoft.DotNet.Cli.Program.Main(String[] args)
Abort trap: 6

## Environment data
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.9
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by bartonjs** [comment]
10.9 isn't supported, 10.10 (Yosemite) was the oldest supported version for 1.0, 10.11 (El Capitan) is probably the best tested.

https://www.microsoft.com/net/core#macos (and the chosen RID) suggests that 10.11 is our lowest supported build for 1.1

**Comment by bartonjs** [comment]
And the error is corroborated by https://opensource.apple.com/source/CommonCrypto/CommonCrypto-60061/include/CommonRandom.h.auto.html:

```C
CCRNGStatus CCRandomGenerateBytes(void *bytes, size_t count)
__OSX_AVAILABLE_STARTING(__MAC_10_10, __IPHONE_8_0);
```

**Comment by karelz** [comment]
Should we close the bug as by design = won't fix then?

**Comment by blackdwarf** [comment]
@karelz I would say so, yes.
