### ISSUE TITLE
Test issue: System.IO.MemoryMappedFiles.Tests.CrossProcessTests.DataShared crashes

### ISSUE THREAD

**Issue by dennisdietrich** [dotnet/corefx#15891]
The cross-process memory-mapped file test below consistently crashes on my machine on Windows 10 Pro even on first build of a freshly cloned repo. Command line:
```
R:\corefx_ref\Tools\testdotnetcli\dotnet.exe xunit.console.netcore.exe System.IO.MemoryMappedFiles.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
```
Test output:
```
Exception from RemoteExecutorConsoleApp(System.IO.MemoryMappedFiles.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb, System.IO.MemoryMappedFiles.Tests.CrossProcessTests, DataShared_OtherProcess, C:\Users\Dennis, Dietrich\AppData\Local\Temp\CrossProcessTests_xbfm5c1q.o5d\DataShared_16):
Assembly: System.IO.MemoryMappedFiles.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
Type: System.IO.MemoryMappedFiles.Tests.CrossProcessTests
Method: Int32 DataShared_OtherProcess(System.String)
Exception: System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at RemoteExecutorConsoleApp.Program.Main(String[] args) in R:\corefx_ref\src\Common\tests\System\Diagnostics\RemoteExecutorConsoleApp\RemoteExecutorConsoleApp.cs:line 48

Unhandled Exception: System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at RemoteExecutorConsoleApp.Program.Main(String[] args) in R:\corefx_ref\src\Common\tests\System\Diagnostics\RemoteExecutorConsoleApp\RemoteExecutorConsoleApp.cs:line 60
   System.IO.MemoryMappedFiles.Tests.CrossProcessTests.DataShared [FAIL]
      Assert.Equal() Failure
      Expected: 42
      Actual:   -532462766
      Stack Trace:
         R:\corefx_ref\src\Common\tests\System\Diagnostics\RemoteExecutorTestBase.cs(167,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
         R:\corefx_ref\src\System.IO.MemoryMappedFiles\tests\MemoryMappedFile.CrossProcess.cs(30,0): at System.IO.MemoryMappedFiles.Tests.CrossProcessTests.DataShared()
```

**Comment by stephentoub** [comment]
I'm unable to repro this.  The error suggests that the test is handing off to itself an unexpected number of arguments.  @dennisdietrich, could you try modifying the RemoteExecutorConsoleApp to print out its arguments?
https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Diagnostics/RemoteExecutorConsoleApp/RemoteExecutorConsoleApp.cs#L17
e.g. make the beginning of the program something like:
```C#
static int Main(string[] args)
{
    for (int i = 0; i < args.Length; i++) Console.WriteLine($"Arg{i} (length={args[i].Length}): {args[i]}");
```
and share the results you get from it when running this test?

**Comment by dennisdietrich** [comment]
Well, well. Looks like it chokes on the space character in the path to my profile.
```
Arg0 (length=100): System.IO.MemoryMappedFiles.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
Arg1 (length=51): System.IO.MemoryMappedFiles.Tests.CrossProcessTests
Arg2 (length=23): DataShared_OtherProcess
Arg3 (length=15): C:\Users\Dennis
Arg4 (length=72): Dietrich\AppData\Local\Temp\CrossProcessTests_m4ji03fq.odl\DataShared_16
```

**Comment by stephentoub** [comment]
Thanks, @dennisdietrich.  If you change the line at:
https://github.com/dotnet/corefx/blob/master/src/System.IO.MemoryMappedFiles/tests/MemoryMappedFile.CrossProcess.cs#L30
from:
```C#
RemoteInvoke(DataShared_OtherProcess, file.Path).Dispose();
```
to:
```C#
RemoteInvoke(DataShared_OtherProcess, $"\"{file.Path}\"").Dispose();
```
does that fix the problem?  If so, mind submitting a PR to make that change?

**Comment by dennisdietrich** [comment]
@stephentoub Thanks! Yeah, it does, but I found some more instances of that issue so I'm fixing them too. I'll submit an PR when I'm done.

**Comment by stephentoub** [comment]
Thanks.
