### ISSUE TITLE
OuterLoop_CentOS7.1_release: Test 'System.Xml.Tests.CReaderTestModule.RunTestCase' failed with 'Xunit.Sdk.EqualException'

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16024]
Failed Test: System.Xml.Tests.CReaderTestModule.TCMaxSettings 
Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_centos7.1_release/89/consoleText

Message:
~~~
System.Xml.Tests.CReaderTestModule.TCMaxSettings [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   38
~~~

Stack Trace:
~~~
/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/src/System.Private.Xml/tests/Readers/ReaderSettings/CReaderTestModule.cs(21,0): at System.Xml.Tests.CReaderTestModule.RunTestCase(Func`1 testCaseGenerator)
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/src/System.Private.Xml/tests/Readers/ReaderSettings/CReaderTestModule.cs(27,0): at System.Xml.Tests.CReaderTestModule.RunTest(Func`1 testCaseGenerator)
~~~

Configuration: 
OuterLoop_Centos7.1_release (build#89)

**Comment by Jiayili1** [comment]
On OuterLoop_OpenSUSE42.1_release ([build#90](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_opensuse42.1_release/90/consoleText)), the test System.Xml.Tests.CReaderTestModule.TCMaxSettings failed with Xunit.Sdk.EqualException

Message:
~~~
System.Xml.Tests.CReaderTestModule.TCMaxSettings [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   38
~~~

Stack Trace: 
~~~
/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_opensuse42.1_release/src/System.Private.Xml/tests/Readers/ReaderSettings/CReaderTestModule.cs(21,0): at System.Xml.Tests.CReaderTestModule.RunTestCase(Func`1 testCaseGenerator)
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_opensuse42.1_release/src/System.Private.Xml/tests/Readers/ReaderSettings/CReaderTestModule.cs(27,0): at System.Xml.Tests.CReaderTestModule.RunTest(Func`1 testCaseGenerator)
~~~

**Comment by Jiayili1** [comment]
This test also failed on following configurations:
OuterLoop_OSX10.11_release ([build#77](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_osx_release/77/consoleText))
OuterLoop_RedHat7.2_debug ([build#96](
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_rhel7.2_debug/96/consoleText))
OuterLoop_Ubuntu14.04_debug ([build#98](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu14.04_debug/98/consoleText))
OuterLoop_Ubuntu14.04_release ([build#98](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu14.04_release/98/consoleText))
OuterLoop_Ubuntu16.04_debug ([build#96](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu16.04_debug/96/consoleText))
OuterLoop_Ubuntu16.04_release ([build#96](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu16.04_release/96/consoleText))
OuterLoop_Ubuntu16.10_debug ([build#89](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu16.10_debug/89/consoleText))
OuterLoop_Ubuntu16.10_release ([build#97](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu16.10_release/97/consoleText))
OuterLoop_PortableLinux_release ([build#8](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_portablelinux_release/8/consoleText))
OuterLoop_Windows7_debug ([build#91](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/91/consoleText))
OuterLoop_Windows8.1_debug ([build#94](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/94/consoleText))
OuterLoop_Windows8.1_release ([build#92](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_release/92/consoleText))
OuterLoop_Windows10_debug ([build#88](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_debug/88/consoleText))
OuterLoop_Windows10_release ([build#94](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_release/94/consoleText))
