### ISSUE TITLE
The binary operator Add is not defined for the types 'System.Nullable`1[System.Byte]' and 'System.Nullable`1[System.Byte]'.

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#16028]
```csharp
    enum MyEnum : byte
    {
        Value_1 = 1,
        Value_2 = 2
    }

    class Program
    {
        static void Main(string[] args)
        {
            dynamic d = MyEnum.Value_1;
            var x = d + null;
        }
    }
```

fails with following error (works as expected without dynamic)

```
Unhandled Exception: System.InvalidOperationException: The binary operator Add is not defined for the types 'System.Nullable`1[System.Byte]' and 'System.Nullable`1[System.Byte]'.
   at System.Linq.Expressions.Expression.GetUserDefinedBinaryOperatorOrThrow(ExpressionType binaryType, String name, Expression left, Expression right, Boolean liftToNull)
   at System.Linq.Expressions.Expression.Add(Expression left, Expression right, MethodInfo method)
   at Microsoft.CSharp.RuntimeBinder.ExpressionTreeCallRewriter.GenerateBinaryOperator(EXPRCALL pExpr)
   at Microsoft.CSharp.RuntimeBinder.ExpressionTreeCallRewriter.GetExpression(EXPR pExpr)
   at Microsoft.CSharp.RuntimeBinder.ExpressionTreeCallRewriter.GenerateConvert(EXPRCALL pExpr)
   at Microsoft.CSharp.RuntimeBinder.ExpressionTreeCallRewriter.VisitCALL(EXPRCALL pExpr)
   at Microsoft.CSharp.RuntimeBinder.Semantics.ExprVisitorBase.Dispatch(EXPR pExpr)
   at Microsoft.CSharp.RuntimeBinder.Semantics.ExprVisitorBase.Visit(EXPR pExpr)
   at Microsoft.CSharp.RuntimeBinder.ExpressionTreeCallRewriter.GenerateLambda(EXPRCALL pExpr)
   at Microsoft.CSharp.RuntimeBinder.ExpressionTreeCallRewriter.VisitCALL(EXPRCALL pExpr)
   at Microsoft.CSharp.RuntimeBinder.Semantics.ExprVisitorBase.Dispatch(EXPR pExpr)
   at Microsoft.CSharp.RuntimeBinder.Semantics.ExprVisitorBase.Visit(EXPR pExpr)
   at Microsoft.CSharp.RuntimeBinder.ExpressionTreeCallRewriter.Rewrite(TypeManager typeManager, EXPR pExpr, IEnumerable`1 listOfParameters)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateExpressionTreeFromResult(IEnumerable`1 parameters, ArgumentObject[] arguments, Scope pScope, EXPR pResult)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore(DynamicMetaObjectBinder payload, IEnumerable`1 parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(DynamicMetaObjectBinder payload, IEnumerable`1 parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
   at Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(DynamicMetaObjectBinder action, RuntimeBinder binder, IEnumerable`1 args, IEnumerable`1 arginfos, DynamicMetaObject onBindingError)
   at Microsoft.CSharp.RuntimeBinder.CSharpBinaryOperationBinder.FallbackBinaryOperation(DynamicMetaObject target, DynamicMetaObject arg, DynamicMetaObject errorSuggestion)
   at System.Dynamic.DynamicMetaObject.BindBinaryOperation(BinaryOperationBinder binder, DynamicMetaObject arg)
   at System.Dynamic.BinaryOperationBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
```

**Comment by JonHanna** [comment]
Interesting. The compiler is treating the rule that for any `T`, `x` adding a literal null results in a null of type `T` if `T` can be null and type `T?` otherwise, as coming before anything else, including the rule that there's no `+` for enum types (note that `d + MyEnum.Value_1` fails both dynamically and statically).

I'm not completely sure it isn't the static case that's incorrect here, but even if it is, it's probably worth having the binder match it.

**Comment by JonHanna** [comment]
Since whether an argument is a literal isn't reflected in dynamic calls the closest we can do is detect if the argument is `const`. That may end up allowing more than it should, though there's already strangeness there as in:

```C#
dynamic d = null;
const object o = null;
object r = d + o;
Console.WriteLine(r.Equals(""));
```

Where it's taken that the only sensible `+` between some `object` and constant null is that with strings and concatenating null strings results in the empty string.

Will have to ensure that behaviour remains as it is, but I'll see if I can fix this.

**Comment by marek-safar** [comment]
I think const should have CSharpArgumentInfoFlags.UseCompileTimeType set whereas null literal shouldn't

**Comment by JonHanna** [comment]
Yeah, that seems to be the case, which makes this a lot easier. #15537 fixes a few other issues around handling of constants, so I might update that to cover this, though I think the checks need to come in earlier since it covers cases where only one argument is constant.

**Comment by JonHanna** [comment]
It's not the constant handling, it's the conversions that are wrong.

It should be producing the expression:

```C#
Expression.Convert(
	Expression.Add(
		Expression.Convert(
			Expression.Convert(
				Expression.Parameter(typeof(object)),
				typeof(MyEnum)
			),
			typeof(int?)
		),
		Expression.Constant(null, typeof(int?))
	),
	typeof(MyEnum?)
)
```
Instead it's producing:
```C#
Expression.Convert(
	Expression.Add(
		Expression.Convert(
			Expression.Convert(
				Expression.Parameter(typeof(object)),
				typeof(MyEnum)
			),
			typeof(byte?)
		),
		Expression.Constant(null, typeof(byte?))
	),
	typeof(MyEnum?)
)
```

**Comment by karelz** [comment]
@marek-safar is it blocking Xamarin usage of CoreFX?

**Comment by JonHanna** [comment]
More Microsoft.CSharp than Expressions, @karelz. It's correct for expressions to throw that exception, incorrect for MS.CSharp to try to build it.

**Comment by karelz** [comment]
Thanks for correcting me!

**Comment by marek-safar** [comment]
@karelz it's blocking Microsoft.CSharp switch to corefx because this is a regression compare to our existing implementation

**Comment by JonHanna** [comment]
Really? I can reproduce it against the version in the GAC.

**Comment by marek-safar** [comment]
Which GAC, .net or Mono ?

**Comment by JonHanna** [comment]
.NET. If Mono's correct it might be worth seeing if this already came up and was fixed there.

**Comment by karelz** [comment]
@JonHanna @VSadov @OmarTawfik can you please prioritize the fix? It blocks our partner's attempt to use CoreFX on Mono (something everyone would like to see).

**Comment by JonHanna** [comment]
I'm looking at it, but I still have gaps in my knowledge of this project and the automatic conversions logic is one of them, so someone else would likely find the problem a lot faster.

**Comment by JonHanna** [comment]
Or not. PTAL @ #16085

**Comment by karelz** [comment]
Very cool, thanks @JonHanna! :)

**Comment by JonHanna** [comment]
NP. Incidentally, the copy I have of the published ECMA-334 and the unofficial draft at https://github.com/ljw1004/csharpspec/blob/gh-pages/README.md both suggest that `underlyingTypeValue - enumTypeValue` isn't valid, and it makes logical sense to prohibit it, but both static and dynamic non-lifted behaviour allows it, so I allowed it in the fix; however logical banning it might be, it would be a serious breaking change to ban it now, but it may be a gap in not being specifically noted as allowed.

**Comment by VSadov** [comment]
I agree, allowing this operation in dynamic scenarios, considering that it was throwing, seems unlikely to be breaking. Especially since it worked in Xamarin implementation.

**Comment by JonHanna** [comment]
The operation covered by the original post should definitely be allowed.
I mean the situation of e.g. `2 - StringComparison.InvariantCulture` which was also working for .NET Core too, except in the lifted byte-base case covered by this issue. The spec seems to say that isn't allowed and since the lifted equivalent of that expression now goes through the code I added, if I'd followed the spec to the letter I would have introduced a breaking change. The spec should perhaps be updated to explicitly allow that case too.
