### ISSUE TITLE
Test failure System.Net.Tests.HttpWebRequestTest/GetResponseAsync_GetResponseStream_ContainsHost(remoteServer: https://corefx-net.cloudapp.net/Echo.ashx)

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#16046]
release/1.1.0 branch:
Same 2 test failures in 2 runs, each time on different platform
* [20170208.02 - Redhat.72.amd64-Release](https://mc.dot.net/#/product/netcore/110/source/official~2Fcorefx~2Frelease~2F1.1.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170208.02/workItem/System.Net.Requests.Tests/analysis/xunit/System.Net.Tests.HttpWebRequestTest~2FGetResponseAsync_GetResponseStream_ContainsHost(remoteServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx))
* [20170209.02 - Centos.71.amd64.Debug](https://mc.dot.net/#/product/netcore/110/source/official~2Fcorefx~2Frelease~2F1.1.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170209.02/workItem/System.Net.Requests.Tests/analysis/xunit/System.Net.Tests.HttpWebRequestTest~2FGetResponseAsync_GetResponseStream_ContainsHost(remoteServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx))

### Message:
System.Net.WebException : An error occurred while sending the request. Problem with the SSL CA cert (path? access rights?)\n
---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\n
-------- System.Net.Http.CurlException : Problem with the SSL CA cert (path? access rights?)

### Stack trace:
```
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Net.Tests.HttpWebRequestTest.<GetResponseAsync_GetResponseStream_ContainsHost>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.HttpWebRequest.<SendRequest>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
----- Inner Stack Trace -----
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
```

**Comment by karelz** [comment]
@Priya91 can you please take a look? It's making our 1.1.1 release sign off difficult ...

**Comment by karelz** [comment]
cc @ianhays @steveharter (1.1 test failure)

**Comment by Priya91** [comment]
> @Priya91 can you please take a look? It's making our 1.1.1 release sign off difficult ...
If you can confirm that it is just test issue, that would be great.

I think so, we have had same kind of bug in other branches as well, it's more likely to do with machine configuration. Will prioritize to investigate this first, it causing quite a lot of noise.

other similar bugs: #12637 #13300

**Comment by Priya91** [comment]
Not able to repro this using the helix repro environment from the centos VM with jenkins image. This is mostly a machine issue. The problem could be that the openssl cert location /etc/pki/tls/certs on centos is not there, incorrect permissions, etc. Need access to the failure machine to investigate.

cc @MattGal How do i access the helix machine where the job is failing?

**Comment by karelz** [comment]
Unmarking as blocking - as we believe it is just test issue.

**Comment by MattGal** [comment]
I can get you limited access to a local VM, but they are created and destroyed randomly.  If you give me specifics of what you'd like to investigate I'm happy to help you get onto one or investigate machine state for you.

**Comment by Priya91** [comment]
@MattGal On the centos box where this fails, can you check if you're able to access this location with same user rights as the test:

```
/etc/pki/tls/certs
```

If, not what is the following outputting,
```
openssl version -d
```

**Comment by MattGal** [comment]
```
[helixbot@dnblc0701000DV0 ~]$ openssl version -d
OPENSSLDIR: "/etc/pki/tls"
[helixbot@dnblc0701000DV0 ~]$ openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
```
the user used in test runs definitely has access to /etc/pki/tls/certs, but I did note that I had to sudo to create new files in this path.  

Let me know if you'd like me to check anything else out.

**Comment by Priya91** [comment]
Got a centos image similar to what helix uses, and running, sudo update-ca-trust on the machine fixed the SSL CA cert path issue. 

@MattGal is updating the machine script to run this after imaging, will wait for confirmation on if this fixes the build break.

cc @karelz @steveharter @ianhays

**Comment by steveharter** [comment]
These are likely related to recent failures in System.Net.Tests  regarding the "SSL CA cert" message. It does appear to be random, however.

Here's some release1.1 failures:
http://jdash.azurewebsites.net/builds/test?name=System.Net.Tests.HttpWebRequestTest.GetResponseAsync_GetResponseStream_ContainsHost%28remoteServer%3A%20https%3A%2F%2Fcorefx-net.cloudapp.net%2FEcho.ashx%29&viewName=dotnet_corefx&pr=False&limit=1000&startDate=2017-02-01

Here's some failures in master, and some test output below
http://jdash.azurewebsites.net/builds/test?name=System.Net.Tests.HttpWebRequestHeaderTest.GetResponse_UseDefaultCredentials_ExpectSuccess%28remoteServer%3A%20https%3A%2F%2Fcorefx-net.cloudapp.net%2FEcho.ashx%29&viewName=dotnet_corefx&pr=False&limit=1000&startDate=2017-02-01
http://jdash.azurewebsites.net/builds/test?name=System.Net.Tests.TaskWebClientTest.UploadFile_Success%28echoServer%3A%20https%3A%2F%2Fcorefx-net.cloudapp.net%2FEcho.ashx%29&viewName=dotnet_corefx&pr=False&limit=1000&startDate=2017-02-01
http://jdash.azurewebsites.net/builds/test?name=System.Net.Tests.HttpWebRequestTest.GetResponseAsync_UseDefaultCredentials_ExpectSuccess%28remoteServer%3A%20https%3A%2F%2Fcorefx-net.cloudapp.net%2FEcho.ashx%29&viewName=dotnet_corefx&pr=False&limit=1000&startDate=2017-02-01

````
System.Net.Tests.HttpWebRequestHeaderTest.GetResponse_UseDefaultCredentials_ExpectSuccess(remoteServer: https://corefx-net.cloudapp.net/Echo.ashx) (from (empty)) 
GetResponse_UseDefaultCredentials_ExpectSuccessnet.cloudapp.net/Echo.ashx) [FAIL]

MESSAGE:
System.Net.WebException : An error occurred while sending the request. Problem with the SSL CA cert (path? access rights?)\n---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\n-------- System.Net.Http.CurlException : Problem with the SSL CA cert (path? access rights?)
+++++++++++++++++++
STACK TRACE:
at System.Net.HttpWebRequest.GetResponse() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_portablelinux_debug/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 989
at System.Net.Tests.HttpWebRequestHeaderTest.GetResponse_UseDefaultCredentials_ExpectSuccess(Uri remoteServer) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_portablelinux_debug/src/System.Net.Requests/tests/HttpWebRequestHeaderTest.cs:line 46 ----- Inner Stack Trace ----- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() 
at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_portablelinux_debug/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 487 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at System.Net.HttpWebRequest.<SendRequest>d__188.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_portablelinux_debug/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1192 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
at System.Net.HttpWebRequest.GetResponse() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_portablelinux_debug/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 985 ----- Inner Stack Trace ----- 
at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_portablelinux_debug/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.cs:line 646 
at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_portablelinux_debug/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.MultiAgent.cs:line 852

System.Net.Tests.TaskWebClientTest.UploadFile_Success(echoServer: https://corefx-net.cloudapp.net/Echo.ashx
MESSAGE:
System.Net.WebException : An error occurred while sending the request. Problem with the SSL CA cert (path? access rights?)\n---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\n-------- System.Net.Http.CurlException : Problem with the SSL CA cert (path? access rights?)
+++++++++++++++++++
STACK TRACE:
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_rhel7.2_debug/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1246
at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_rhel7.2_debug/src/System.Net.WebClient/src/System/Net/WebClient.cs:line 256 
at System.Net.WebClient.<GetWebResponseTaskAsync>d__112.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_rhel7.2_debug/src/System.Net.WebClient/src/System/Net/WebClient.cs:line 269 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() 
at System.Net.WebClient.<DownloadBitsAsync>d__150.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_rhel7.2_debug/src/System.Net.WebClient/src/System/Net/WebClient.cs:line 865 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
at System.Net.Tests.WebClientTestBase.<UploadFile_Success>d__22.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_rhel7.2_debug/src/System.Net.WebClient/tests/WebClientTest.cs:line 642 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) ----- Inner Stack Trace ----- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() 
at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_rhel7.2_debug/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 487 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() 
at System.Net.HttpWebRequest.<SendRequest>d__188.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_rhel7.2_debug/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1192 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_rhel7.2_debug/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1242 ----- Inner Stack Trace ----- 
at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_rhel7.2_debug/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.cs:line 646 
at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_rhel7.2_debug/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.MultiAgent.cs:line 852

System.Net.Tests.HttpWebRequestTest.GetResponseAsync_UseDefaultCredentials_ExpectSuccess(remoteServer: https://corefx-net.cloudapp.net/Echo.ashx) (from (empty)) 
Failing for the past 1 build (Since #4 ) 
Took 0.1 sec.
Stacktrace
MESSAGE:
System.Net.WebException : An error occurred while sending the request. Problem with the SSL CA cert (path? access rights?)\n---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\n-------- System.Net.Http.CurlException : Problem with the SSL CA cert (path? access rights?)
+++++++++++++++++++
STACK TRACE:
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_portablelinux_debug/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1246 
at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_portablelinux_debug/src/System.Net.Requests/src/System/Net/WebRequest.cs:line 552 
at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
at System.Net.Tests.HttpWebRequestTest.<GetResponseAsync_UseDefaultCredentials_ExpectSuccess>d__43.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_portablelinux_debug/src/System.Net.Requests/tests/HttpWebRequestTest.cs:line 365 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) ----- Inner Stack Trace ----- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() 
at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_portablelinux_debug/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 487 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() 
at System.Net.HttpWebRequest.<SendRequest>d__188.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_portablelinux_debug/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1192 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_portablelinux_debug/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1242 ----- Inner Stack Trace ----- 
at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_portablelinux_debug/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.cs:line 646 
at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_portablelinux_debug/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.MultiAgent.cs:line 852
````

**Comment by MattGal** [comment]
The change is up on our Centos execution VMs now, but there wasn't a 1.1.0 run overnight, so we won't know if it's fixed for a bit.  
That said, JDash having the same call stack makes it sound like a real bug;  if random other folks hit it with entirely different machine setups, our workaround may not be sufficient.

**Comment by Jiayili1** [comment]
This issue is repro on OuterLoop_Centos7.1_release (build#95), detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_centos7.1_release/95/consoleText

Message:
~~~
System.Net.Tests.HttpWebRequestTest.GetResponseAsync_UseDefaultCredentials_ExpectSuccess(remoteServer: https://corefx-net.cloudapp.net/Echo.ashx) [FAIL]
        System.Net.WebException : An error occurred while sending the request. Problem with the SSL CA cert (path? access rights?)
        ---- System.Net.Http.HttpRequestException : An error occurred while sending the request.
        -------- System.Net.Http.CurlException : Problem with the SSL CA cert (path? access rights?)
~~~

Stack Trace:
~~~
/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/bin/testhost/netcoreapp-Linux-Release-x64//dotnet xunit.console.netcore.exe System.Security.Claims.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=IgnoreForCI -notrait category=failing -notrait category=nonlinuxtests
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs(1246,0): at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
  /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/bin/AnyOS.AnyCPU.Release/System.Security.Claims.Tests/netstandard /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/src/System.Security.Claims/tests
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/src/System.Net.Requests/tests/HttpWebRequestTest.cs(365,0): at System.Net.Tests.HttpWebRequestTest.<GetResponseAsync_UseDefaultCredentials_ExpectSuccess>d__43.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           ----- Inner Stack Trace -----
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/src/System.Net.Http/src/System/Net/Http/HttpClient.cs(487,0): at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs(1192,0): at System.Net.HttpWebRequest.<SendRequest>d__188.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs(1227,0): at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
           ----- Inner Stack Trace -----
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.cs(637,0): at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.MultiAgent.cs(857,0): at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
~~~

So added "blocking-clean-ci".

**Comment by Jiayili1** [comment]
This issue is repro on build OuterLoop_Centos7.1_debug (build#97), detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_centos7.1_debug/97/testReport/System.Net.Tests/HttpWebRequestTest/GetResponseAsync_UseDefaultCredentials_ExpectSuccess_remoteServer__https___corefx_net_cloudapp_net_Echo_ashx_/

**Comment by Priya91** [comment]
This is fixed on helix by running update-ca-trust on the machines. Updating the jenkins images to do the same.
