### ISSUE TITLE
Security test failures - Unable to load DLL 'System.Security.Cryptography.Native'

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#16047]
5 tests failed on all Linux & Mac OSX platforms (release & debug) in two 1.1 servicing builds:
* [20170208.02](https://mc.dot.net/#/product/netcore/110/source/official~2Fcorefx~2Frelease~2F1.1.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170208.02/workItem/System.Security.Cryptography.Algorithms.Tests)
* [20170209.02](https://mc.dot.net/#/product/netcore/110/source/official~2Fcorefx~2Frelease~2F1.1.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170209.02/workItem/System.Security.Cryptography.Algorithms.Tests)

Failed tests:
* System.Security.Cryptography.EcDsa.Tests.ECDsaImportExportTests
  * TestExplicitCurves
  * TestExplicitCurvesSignVerify
  * TestNamedCurves
  * TestNamedCurvesNegative
* System.Security.Cryptography.EcDsa.Tests.ECDsaTests
  * TestChangeFromNamedCurveToKeySize

### Message:
System.DllNotFoundException : Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.\n (Exception from HRESULT: 0x8007007E)

### Stack trace (example):
```
   at System.Security.Cryptography.EcDsa.Tests.Interop.Crypto.EcKeyCreateByOid(String oid)
   at System.Security.Cryptography.EcDsa.Tests.ECDsaProvider.IsValueOrFriendlyNameValid(String friendlyNameOrValue)
   at System.Security.Cryptography.EcDsa.Tests.ECDsaProvider.IsCurveValid(Oid oid)
   at System.Security.Cryptography.EcDsa.Tests.ECDsaFactory.IsCurveValid(Oid oid)
   at System.Security.Cryptography.EcDsa.Tests.CurveDef.get_IsCurveValidOnPlatform()
   at System.Security.Cryptography.EcDsa.Tests.ECDsaTestsBase.<>c.<get_TestCurvesFull>b__6_0(CurveDef curveDef)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Security.Cryptography.EcDsa.Tests.ECDsaTestsBase.<get_TestCurvesFull>d__6.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
```

**Comment by karelz** [comment]
@bartonjs can you please take a look?

**Comment by bartonjs** [comment]
This is a test bug.  It was fixed in master by https://github.com/dotnet/corefx/pull/13123.

(The native file was renamed, but the test had its own copy of the P/Invoke, and didn't get the memo)

**Comment by karelz** [comment]
Good to know. Can you please fix the tests in release branch(es)? So that we avoid noise in servicing branches ...

**Comment by bartonjs** [comment]
Don't know why this didn't tag closed, but it's done.

**Comment by karelz** [comment]
@bartonjs GitHub hiccups, I have seen it quite a few times :(

**Comment by karelz** [comment]
GH support email sent ...

**Comment by karelz** [comment]
To close the loop: The reason is that it was non-master branch - they do not trigger auto-close from non-master branches. (sounds reasonable to me).
