### ISSUE TITLE
Tests failing in new SerialStream tests

### ISSUE THREAD

**Issue by willdean** [dotnet/corefx#16055]
Placeholder for ActiveIssue - there's an intermittent CI test failure caused by something in the new SerialStream tests

**Comment by karelz** [comment]
Assigning to you @willdean - I think you are working through those. Let me know if I am wrong.

**Comment by willdean** [comment]
Turns out this is easily repro'd here with an appropriately tight loop - it's intermittent but not terribly so.

A similar test elsewhere in the suite contains code like this, with an interesting comment

```
   com.Close();
   Thread.Sleep(200);
   // Give the port time to finish closing since we have an unclosed BeginWrite - see  - see Dev10 #591344
```

I guess this is a reference to a bug in an internal MS database.  Would it be possible to get access the content of this bug, or at least some kind of redacted summary?

It's fairly well known that people sometimes have close-then-quickly-reopen problems with SerialPort, and it would be good to have any info that's available on this.

I can apply the same work around to the tests which are causing CI problems at the moment, but blindly stuffing the test suite full of workarounds for SerialPort problems (if that's what it is) doesn't really seem like the road to enlightenment...

**Comment by JeremyKuhne** [comment]
@willdean I'll try and find the issue.

**Comment by JeremyKuhne** [comment]
So many databases over the years... :)

The issue was opened on the test being unstable in the lab (back in 2009):

```
The test Desktop\coremanglib\BCL\System_IO_Ports\SerialStream\EndWrite.exe  is failing consistently, but only on a few machines.

The scenario is:  Call BeginRead on a SerialStream, then attempt to call EndWrite with that AsyncResult.  Get the expected ArgumentException, close the stream.  Then attempt to open the stream to start the next scenario, and the Open fails with:

Unhandled Exception: System.UnauthorizedAccessException: Access to the port 'COM1' is denied.
   at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   at System.IO.Ports.SerialPort.Open()
   at Test.Main() in c:\Tests\V4\BVT\Desktop\CoreMangLib\BCL\System_IO_Ports\SerialStream\katyk\SerialRepro.cs:line 46

Is this because the BeginRead was not terminated with an EndRead?  Or something else?  Is the test case incorrect?  I have also attached the original test case (csc EndWrite.cs Support.cs) if you want to look at it.
```

The dev responded:

```
The problem is the unfinished async writes and reads; there's a slight delay before you can access the com port again. Note we can't simply add EndX calls with COM1; adding these will cause the app to hang. 

I attached a repro for COM3 (assuming USB/SP adapter is attached) showing that adding EndWrites and EndReads causes the problem to go away (doesn't hang with COM3). However, if you comment out the EndX calls (I indicated these lines with comments), the problem repros again.

This is a known "issue" with our async I/O. If a BeginX isn't followed by an EndX, then the necessarily cleanup of internal structures (wait handles, etc) can't be finished. We're not able to clean these up when closing SerialPort because we don't hold references. Because of that, nondeterministic problems can happen if BeginXs aren't followed by an EndX. 

Since the async reads and writes won't terminate with COM1, you don't want to add EndX calls to fix up this test case. Instead, you could insert a slight wait before the second open. For example, a 500 ms delay caused the problem not to repro. Inserting a wait isn't ideal, but it's probably the best we can do for this test case, given that we can't assume the lab machines will have a COM3 connection (or some other live connection).

Note that this also repros in v2, so this isn't a new issue.
```

And, finally, the tester:

```
The test has been updated accordingly:

One problem scenario was moved to the end of the test, where it could not cause problems for any other scenario.

For the other problem scenario, I added a 200ms delay at the end of the scenario, to give the port time to close out before the next scenario (since they can't both be at the end) in the same test exe.

I ran the test 50 times on a machine that repro'd the issue frequently, and these updates appeared to fix it.
```

**Comment by willdean** [comment]
That's great,thanks.  Clearly games with test order are not available to us, so i'll put the delay back in.  Ultimately it would be good at some point to get this fixed properly in SerialPort, so I'll file an issue on that, add a breaking test and ActiveRecord it for now.

**Comment by Jiayili1** [comment]
InnerLoop_Windows8.1_release ([build#1067](https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release/1067/consoleText)), Following tests failed with "System.UnauthorizedAccessException : Access to the port 'COM1' is denied":

Message:
~~~
Legacy.SerialStream.Write_byte_int_int.Offset_NEG1 [FAIL]
        System.UnauthorizedAccessException : Access to the port 'COM1' is denied."
~~~

Stack Trace:
~~~
D:\j\workspace\windows_nt_re---5f4597f5\src\System.IO.Ports\src\System\IO\Ports\InternalResources.cs(77,0): at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
           D:\j\workspace\windows_nt_re---5f4597f5\src\System.IO.Ports\src\System\IO\Ports\SerialStream.cs(607,0): at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
           D:\j\workspace\windows_nt_re---5f4597f5\src\System.IO.Ports\src\System\IO\Ports\SerialPort.cs(609,0): at System.IO.Ports.SerialPort.Open()
           D:\j\workspace\windows_nt_re---5f4597f5\src\System.IO.Ports\tests\Legacy\SerialStream\Write_byte_int_int.cs(269,0): at Legacy.SerialStream.Write_byte_int_int.VerifyWriteException(Byte[] buffer, Int32 offset, Int32 count, Type expectedException)
           D:\j\workspace\windows_nt_re---5f4597f5\src\System.IO.Ports\tests\Legacy\SerialStream\Write_byte_int_int.cs(49,0): at Legacy.SerialStream.Write_byte_int_int.Offset_NEG1()
~~~

Failed tests:
Write_byte_int_int/Offset_NEG1 
Write_byte_int_int/Count_MinInt 
Write_byte_int_int/Count_GT_Length 
Write_byte_int_int/Offset_NEGRND 
Write_byte_int_int/InBreak
Write_byte_int_int/Count_EQ_Zero 
Write_byte_int_int/Count_NEGRND 
Write_byte_int_int/Buffer_Null 
Write_byte_int_int_Generic/WriteAfterClose
Write_byte_int_int_Generic/Handshake_None

**Comment by Jiayili1** [comment]
This issue doesn't repro on today's build, so remove label "blocking-clean-ci".

**Comment by willdean** [comment]
Closing this - #16261 is better focused
