### ISSUE TITLE
EnumerateEnvironmentVariables(target: Machine) test failing with SecurityException

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#16156]
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/96/
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/95/
```
     System.Tests.GetEnvironmentVariable.EnumerateEnvironmentVariables(target: Machine) [FAIL]
        System.Security.SecurityException : Requested registry access is not allowed.
        Stack Trace:
              at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
              at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
              at System.Environment.SetEnvironmentVariableCore(String variable, String value, EnvironmentVariableTarget target)
              at System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
              at Internal.Runtime.Augments.EnvironmentAugments.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
           D:\j\workspace\code_coverage---b14a30e5\src\System.Runtime.Extensions\src\System\Environment.cs(49,0): at System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
           D:\j\workspace\code_coverage---b14a30e5\src\System.Runtime.Extensions\tests\System\Environment.GetEnvironmentVariable.cs(209,0): at System.Tests.GetEnvironmentVariable.EnumerateEnvironmentVariables(EnvironmentVariableTarget target)
```
cc: @JeremyKuhne

**Comment by stephentoub** [comment]
This test no longer tries to set arbitrary environment variables.
