### ISSUE TITLE
Failure in System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.Manual_CertificateSentMatchesCertificateReceived_Success(numberOfRequests: 6, reuseClient: False) 

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16200]
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_release/lastCompletedBuild/testReport/

System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.Manual_CertificateSentMatchesCertificateReceived_Success(numberOfRequests: 6, reuseClient: False) (from (empty))

```
Failing for the past 2 builds (Since Failed#97 )
Took 0.97 sec.
Stacktrace

MESSAGE:
System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n---- System.Net.Http.WinHttpException : The client certificate credentials were not recognized
+++++++++++++++++++
STACK TRACE:
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext() in D:\j\workspace\outerloop_win---65ef7d78\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 487 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Net.Http.HttpClient.<GetStringAsyncCore>d__27.MoveNext() in D:\j\workspace\outerloop_win---65ef7d78\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 139 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<>c__DisplayClass5_1.<<Manual_CertificateSentMatchesCertificateReceived_Success>b__2>d.MoveNext() in D:\j\workspace\outerloop_win---65ef7d78\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ClientCertificates.cs:line 92 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<>c__DisplayClass5_1.<<Manual_CertificateSentMatchesCertificateReceived_Success>b__4>d.MoveNext() in D:\j\workspace\outerloop_win---65ef7d78\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ClientCertificates.cs:line 129 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass3_0.<CreateServerAsync>b__0(Task t) in D:\j\workspace\outerloop_win---65ef7d78\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 58 at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<Manual_CertificateSentMatchesCertificateReceived_Success>d__5.MoveNext() in D:\j\workspace\outerloop_win---65ef7d78\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ClientCertificates.cs:line 103 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) ----- Inner Stack Trace ----- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in D:\j\workspace\outerloop_win---65ef7d78\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs:line 62 at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext() in D:\j\workspace\outerloop_win---65ef7d78\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 851
```

@steveharter @Priya91 could you please fix or disable this today to get our badge green?

**Comment by Priya91** [comment]
@steveharter Assigning to you, since you mentioned you are looking at this yesterday.

**Comment by Jiayili1** [comment]
This test failed on OuterLoop_Ubuntu14.04_debug ([build#104](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu14.04_debug/104/consoleText)).

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu14.04_debug/104/consoleText

Message:
~~~
System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.Manual_CertificateSentMatchesCertificateReceived_Success(numberOfRequests: 6, reuseClient: False) [FAIL]
        System.Threading.Tasks.TaskCanceledException : A task was canceled.
~~~

Stack Trace:
~~~
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu14.04_debug/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ClientCertificates.cs(93,0): at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<>c__DisplayClass5_1.<<Manual_CertificateSentMatchesCertificateReceived_Success>b__2>d.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu14.04_debug/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ClientCertificates.cs(130,0): at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<>c__DisplayClass5_1.<<Manual_CertificateSentMatchesCertificateReceived_Success>b__4>d.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu14.04_debug/src/Common/tests/System/Net/Http/LoopbackServer.cs(57,0): at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass3_0.<CreateServerAsync>b__0(Task t)
              at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
              at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu14.04_debug/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ClientCertificates.cs(104,0): at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<Manual_CertificateSentMatchesCertificateReceived_Success>d__5.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

**Comment by Jiayili1** [comment]
This test failed on OuterLoop_Ubuntu16.10_debug (build#101), detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu16.10_debug/101/testReport/System.Net.Http.Functional.Tests/HttpClientHandler_ClientCertificates_Test/Manual_CertificateSentMatchesCertificateReceived_Success_numberOfRequests__6__reuseClient__False_/

**Comment by Priya91** [comment]
@steveharter This has started failing on Linux now. #16277 should handle this? Or we should disable this for all OSes.

**Comment by steveharter** [comment]
This was re-flagged as an ActiveIssue a few days ago. https://github.com/dotnet/corefx/blob/7df0cd05c67c28f869a997dfc4423813c2bd9f2a/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ClientCertificates.cs#L74

However that link to build #101 is from yesterday (2/20), so something is amiss

**Comment by Priya91** [comment]
removing blocing-clean-ci, with test disabled by @steveharter

**Comment by steveharter** [comment]
The root issue is #9543, so closing this one now as it shouldn't affect CI anymore. Please reopen if the issue occurs again.
