### ISSUE TITLE
System.Security.Cryptography.X509Certificates.Tests.ChainTests.VerifyChainFromHandle_Unix  failed

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16225]
@steveharter could you please fix or disable today? Red badge.
/cc @bartonjs 

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora23_debug/lastCompletedBuild/testReport/System.Security.Cryptography.X509Certificates.Tests/ChainTests/VerifyChainFromHandle_Unix/

```
MESSAGE:
System.Diagnostics.Debug+DebugAssertException : \n\n at System.Environment.get_StackTrace()\n at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)\n at System.Diagnostics.Debug.Assert(Boolean condition)\n at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.EnsureFilePermissions(FileStream stream, UInt32 userId) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/DirectoryBasedStoreProvider.cs:line 384\n at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/DirectoryBasedStoreProvider.cs:line 189\n at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Store.cs:line 135\n at Internal.Cryptography.Pal.ChainPal.SaveIntermediateCertificates(X509ChainElement[] chainElements, HashSet`1 downloaded) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/ChainPal.cs:line 158\n at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/ChainPal.cs:line 90\n at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Chain.cs:line 118\n at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Chain.cs:line 105\n at System.Security.Cryptography.X509Certificates.Tests.ChainTests.VerifyChainFromHandle_Unix() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Security.Cryptography.X509Certificates/tests/ChainTests.cs:line 134\n at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\n at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\n at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<<InvokeTestMethodAsync>b__1>d.MoveNext()\n at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)\n at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<InvokeTestMethodAsync>b__1()\n at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext()\n at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)\n at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction)\n at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext()\n at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)\n at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code)\n at Xunit.Sdk.TestInvoker`1.<InvokeTestMethodAsync>d__46.MoveNext()\n at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\n at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance)\n at Xunit.Sdk.TestInvoker`1.<<RunAsync>b__45_0>d.MoveNext()\n at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\n at Xunit.Sdk.TestInvoker`1.<RunAsync>b__45_0()\n at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()\n at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\n at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)\n at Xunit.Sdk.XunitTestRunner.<InvokeTestAsync>d__4.MoveNext()\n at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\n at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator)\n at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()\n at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\n at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)\n at Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext()\n at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\n at Xunit.Sdk.TestRunner`1.RunAsync()\n at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext()\n at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\n at Xunit.Sdk.TestCaseRunner`1.RunAsync()\n at Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32.MoveNext()\n at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\n at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()\n at Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31.MoveNext()\n at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\n at Xunit.Sdk.TestMethodRunner`1.RunAsync()\n at Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__38.MoveNext()\n at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\n at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()\n at Xunit.Sdk.TestClassRunner`1.<RunAsync>d__37.MoveNext()\n at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\n at Xunit.Sdk.TestClassRunner`1.RunAsync()\n at Xunit.Sdk.TestCollectionRunner`1.<RunTestClassesAsync>d__28.MoveNext()\n at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\n at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()\n at Xunit.Sdk.TestCollectionRunner`1.<RunAsync>d__27.MoveNext()\n at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\n at Xunit.Sdk.TestCollectionRunner`1.RunAsync()\n at System.Threading.Tasks.Task`1.InnerInvoke()\n at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\n at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n at System.Threading.Tasks.Task.ExecuteEntry()\n at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state)\n at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\n at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc()\n at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _)\n at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\n at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
+++++++++++++++++++
STACK TRACE:
at System.Diagnostics.Debug.UnixDebugLogger.ShowAssertDialog(String stackTrace, String message, String detailMessage) at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage) at System.Diagnostics.Debug.Assert(Boolean condition) at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.EnsureFilePermissions(FileStream stream, UInt32 userId) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/DirectoryBasedStoreProvider.cs:line 384 at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/DirectoryBasedStoreProvider.cs:line 189 at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Store.cs:line 135 at Internal.Cryptography.Pal.ChainPal.SaveIntermediateCertificates(X509ChainElement[] chainElements, HashSet`1 downloaded) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/ChainPal.cs:line 158 at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/ChainPal.cs:line 90 at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Chain.cs:line 118 at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Chain.cs:line 105 at System.Security.Cryptography.X509Certificates.Tests.ChainTests.VerifyChainFromHandle_Unix() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Security.Cryptography.X509Certificates/tests/ChainTests.cs:line 134
```

**Comment by danmosemsft** [comment]
Maybe some logging useful in `private static void EnsureFilePermissions(FileStream stream, uint userId)`? 

I don't know why there's no line numbers.

**Comment by steveharter** [comment]
Sure by EOD will disable and add some logging if appropriate.

**Comment by bartonjs** [comment]
It means that the fedora23 machines have their temp directory (which gets mapped as a temporary $HOME) on NTFS.  (Infrastructure bug https://github.com/dotnet/corefx/issues/9293, and a bug to change this assert to a texted exception).

Fedora23 should have been turned off for these in CI with https://github.com/dotnet/corefx/pull/9309... don't know why it's back.

And one of the other versions of this bug calls for changing that assert to a full throw (with a message), so it's more obvious.  I'm not finding that specific issue, but it's been open for a while.

**Comment by danmosemsft** [comment]
Oh I know why #9309 isn't working -- it's Fedora 24 now!

You might want to change this
` private static bool IsReliableInCI { get; } = !PlatformDetection.IsFedora23;`
Note Fedora 25 is coming soon.

Should we be concerned we aren't getting coverage on Fedora..

**Comment by stephentoub** [comment]
> Should we be concerned we aren't getting coverage on Fedora..

Yes

**Comment by danmosemsft** [comment]
It was  rhetorical :)

**Comment by steveharter** [comment]
Tests disabled

**Comment by stephentoub** [comment]
We don't actually want to close this, do we?  Or are we deleting the tests rather than disabling them?

**Comment by steveharter** [comment]
We close so it gets re-opened if the test fails again.

The root issue is https://github.com/dotnet/corefx/issues/9293
