### ISSUE TITLE
JwtBearerAuthentication fails on AWS Lambda

### ISSUE THREAD

**Issue by rture** [dotnet/corefx#16227]
JTW authentication works on local windows development but fails on Linux
Getting following error

[Information] Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware: Bearer was not authenticated. Failure message: IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey , KeyId: ****************************
'.
Exceptions caught:
'System.PlatformNotSupportedException: Operation is not supported on this platform.
at Internal.Cryptography.Pal.OpenSslX509Encoder.BuildRsaPublicKey(Byte[] encodedData)
at Internal.Cryptography.Pal.CertificateExtensionsCommon.GetPublicKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
at Microsoft.IdentityModel.Tokens.X509SecurityKey.get_PublicKey()
at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.IsSupportedAlgorithm(String algorithm, SecurityKey key)
at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm, TokenValidationParameters validationParameters)
at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)

**Comment by karelz** [comment]
'Microsoft.IdentityModel` does not seem to be part of CoreFX. Do you know which NuGet package it comes from and where the code lives?

cc: @bartonjs

**Comment by bartonjs** [comment]
`BuildRsaPublicKey` doesn't have the ability to throw that exception.  `git blame` says it hasn't changed since 2015-10-16:

https://github.com/dotnet/corefx/blame/e981ddf3e4174f2aeb9469f8b8c9c9db65fc6c90/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/OpenSslX509Encoder.cs#L410-L421

So... I'm a bit confused by the callstack.

**Comment by bartonjs** [comment]
@rture Are you still having problems? If so, do you have a reproducible example so we can investigate?

**Comment by rture** [comment]
@bartonjs problem was only happing on Linux, it is working fine on my local windows environment. I am not sure which version of Linux AWS Lambdas running on. I was simple trying to validate jwt in my service.
It was a small app so decided to convert into node.js express.

**Comment by karelz** [comment]
I guess that without repro or more details, there is nothing we can do. If you find more information, please let us know, we will be happy to dig deeper.
