### ISSUE TITLE
Failure in MonoTests.System.Configuration.ConfigurationSaveTest.ModifyListElement 

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16270]
@JeremyKuhne this gave us a redbadge today. Any ideas?

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_release/lastCompletedBuild/

```
MonoTests.System.Configuration.ConfigurationSaveTest.ModifyListElement (from (empty))

Failing for the past 1 build (Since Failed#101 )
Took 2 ms.
Stacktrace

MESSAGE:
System.Configuration.ConfigurationErrorsException : Root element is missing. (C:\\Users\\dotnet-bot\\AppData\\Local\\Temp\\tmp7E47.tmp)\r\n---- System.Xml.XmlException : Root element is missing.
+++++++++++++++++++
STACK TRACE:
 at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal) in D:\j\workspace\outerloop_win---65ef7d78\src\System.Configuration.ConfigurationManager\src\System\Configuration\ConfigurationSchemaErrors.cs:line 76
 at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors) in D:\j\workspace\outerloop_win---65ef7d78\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 3656
 at System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams) in D:\j\workspace\outerloop_win---65ef7d78\src\System.Configuration.ConfigurationManager\src\System\Configuration\Configuration.cs:line 77
 at System.Configuration.ClientConfigurationHost.OpenExeConfiguration(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath) in D:\j\workspace\outerloop_win---65ef7d78\src\System.Configuration.ConfigurationManager\src\System\Configuration\ClientConfigurationHost.cs:line 489
 at System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad) in D:\j\workspace\outerloop_win---65ef7d78\src\System.Configuration.ConfigurationManager\src\System\Configuration\ConfigurationManager.cs:line 221
 at MonoTests.System.Configuration.ConfigurationSaveTest.ConfigProvider.OpenConfig(String parentFile, String configFile) in D:\j\workspace\outerloop_win---65ef7d78\src\System.Configuration.ConfigurationManager\tests\Mono\ConfigurationSaveTest.cs:line 95
 at MonoTests.System.Configuration.ConfigurationSaveTest.<>c__DisplayClass12_0`1.<Run>b__0(String parent, String filename) in D:\j\workspace\outerloop_win---65ef7d78\src\System.Configuration.ConfigurationManager\tests\Mono\ConfigurationSaveTest.cs:line 251
 at MonoTests.System.Configuration.Util.TestUtil.RunWithTempFiles(MyAction`2 action) in D:\j\workspace\outerloop_win---65ef7d78\src\System.Configuration.ConfigurationManager\tests\Mono\TestUtil.cs:line 67
 ----- Inner Stack Trace -----
 at System.Xml.XmlTextReaderImpl.Throw(Exception e) in D:\j\workspace\outerloop_win---65ef7d78\src\System.Private.Xml\src\System\Xml\Core\XmlTextReaderImpl.cs:line 2744
 at ystem.Xml.XmlTextReaderImpl.ParseDocumentContent() in D:\j\workspace\outerloop_win---65ef7d78\src\System.Private.Xml\src\System\Xml\Core\XmlTextReaderImpl.cs:line 4142
 at System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors) in D:\j\workspace\outerloop_win---65ef7d78\src\System.Configuration.ConfigurationManager\src\System\Configuration\XmlUtil.cs:line 99
 at System.Configuration.BaseConfigurationRecord.InitConfigFromFile() in D:\j\workspace\outerloop_win---65ef7d78\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 565)
```

**Comment by danmosemsft** [comment]
That error can appear if the file is entirely empty.

**Comment by JeremyKuhne** [comment]
Timing I assume. For one the RunWithTempFiles is using Path.GetTempFileName(), which creates a 0 byte file. The helper then deletes the created file and continues with the test, which will serialize to that file location. As delete isn't synchronous I imagine bad luck is inevitable here, but hard to replicate and fully understand the side effects.

I'm also unsure of the exact algorithm the OS uses to create the files- it certainly doesn't guarantee session uniqueness. It could, in theory, return the same name multiple times- it actually creates the file as a way to guarantee that your temp file *is* unique.

I'll tweak the utility code here to not delete-before-write.
