### ISSUE TITLE
Failure in ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#16346]
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/3698/consoleFull#-12002141512d31e50d-1517-49fc-92b3-2ca637122019

```
System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success(serverProtocol: Tls11) [FAIL]
06:59:06         System.ComponentModel.Win32Exception : The credentials supplied to the package were not recognized
06:59:06         Stack Trace:
06:59:06            D:\j\workspace\windows_nt_re---37265eab\src\Common\src\Interop\Windows\sspicli\SSPIWrapper.cs(167,0): at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)
06:59:06            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslStreamPal.Windows.cs(407,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential)
06:59:06            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslStreamPal.Windows.cs(131,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
06:59:06            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs(676,0): at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
06:59:06            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs(783,0): at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
06:59:06            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs(706,0): at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
06:59:06            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslState.cs(767,0): at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
06:59:06            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslState.cs(983,0): at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
06:59:06            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslState.cs(886,0): at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
06:59:06            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslState.cs(697,0): at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
06:59:06            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslState.cs(614,0): at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
06:59:06            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslStream.cs(161,0): at System.Net.Security.SslStream.BeginAuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
06:59:06            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslStream.cs(257,0): at System.Net.Security.SslStream.<>c__DisplayClass35_0.<AuthenticateAsServerAsync>b__0(AsyncCallback callback, Object state)
06:59:06               at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
06:59:06            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\ServerAsyncAuthenticateTest.cs(152,0): at System.Net.Security.Tests.ServerAsyncAuthenticateTest.<ServerAsyncSslHelper>d__11.MoveNext()
06:59:06            --- End of stack trace from previous location where exception was thrown ---
06:59:06               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
06:59:06               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
06:59:06            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\ServerAsyncAuthenticateTest.cs(93,0): at System.Net.Security.Tests.ServerAsyncAuthenticateTest.<ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success>d__9.MoveNext()
06:59:06            --- End of stack trace from previous location where exception was thrown ---
06:59:06               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
06:59:06               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
06:59:06            --- End of stack trace from previous location where exception was thrown ---
06:59:06               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
06:59:06               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
06:59:06            --- End of stack trace from previous location where exception was thrown ---
06:59:06               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
06:59:06               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by Priya91** [comment]
cc @davidsh @CIPop

**Comment by Priya91** [comment]
Dupe of #16338 ?

**Comment by jkotas** [comment]
Another one: https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/3863/testReport/junit/System.Net.Security.Tests/ServerAsyncAuthenticateTest/ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success_serverProtocol__Tls11_/

**Comment by ianhays** [comment]
Tracking this failure in https://github.com/dotnet/corefx/issues/16516. Please comment there with any failure reports instead of re-opening this issue.
