### ISSUE TITLE
Test "System.Net.NetworkInformation.Tests.PingTest.SendAsyncs_ReuseInstance_Hostname" failed with "Xunit.Sdk.EqualException" in OuterLoop_Ubuntu16.04_debug

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16401]
Configuration: OuterLoop_Ubuntu16.04_debug ([build#109](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu16.04_debug/109/testReport/)).

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu16.04_debug/109/testReport/

Message:
~~~
Assert.True() Failure\nExpected: True\nActual: False
~~~

Stack trace:
~~~
at System.Net.NetworkInformation.Tests.PingTest.<SendAsyncs_ReuseInstance_Hostname>d__17.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.04_debug/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs:line 402 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

**Comment by Priya91** [comment]
@steveharter @ianhays Is this tracked in the list of NetworkInformation failures?

**Comment by ianhays** [comment]
> Is this tracked in the list of NetworkInformation failures?

Yeah, it is. It only failed once in the December query though so it wasn't marked as high priority.

**Comment by ianhays** [comment]
The failure is occurring in the code where multiple pings are sent async then immediately cancelled.
```
for (int i = 0; i < 3; i++)
{
    reset();
    p.SendAsync(TestSettings.LocalHost, null);
    p.SendAsyncCancel(); // will block until operation can be started again
```

 An assertion is made

```
Assert.True(ea.Cancelled ^ (ea.Error != null) ^ (ea.Reply != null));
```
afterwards that fails, but we don't know why it's failing or which conditions are true/false.

The test looks ripe for a race condition to me.

**Comment by ianhays** [comment]
> afterwards that fails, but we don't know why it's failing or which conditions are true/false.

I added some logging so we know why exactly it's failing so we can modify the test if necessary.

**Comment by stephentoub** [comment]
Failed here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu14.04_debug_prtest/121/consoleText
```
System.Net.NetworkInformation.Tests.PingTest.SendAsyncs_ReuseInstance_Hostname [FAIL]
        Cancelled: False
        Reply Address: 127.0.0.1
        Reply Status: Success
        Expected: True
        Actual:   False
        Stack Trace:
           /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu14.04_debug_prtest/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs(402,0): at System.Net.NetworkInformation.Tests.PingTest.<SendAsyncs_ReuseInstance_Hostname>d__17.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
