### ISSUE TITLE
Null ref exception in Abort_CloseAndAbort_Success test on Windows in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#16419]
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/112/consoleText
```
System.Net.WebSockets.Client.Tests.AbortTest.Abort_CloseAndAbort_Success(server: wss://corefx-net.cloudapp.net/WebSocket/EchoWebSocket.ashx) [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
           D:\j\workspace\code_coverage---b14a30e5\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WinHttpWebSocketState.cs(275,0): at System.Net.WebSockets.WinHttpWebSocketState.Dispose(Boolean disposing)
           D:\j\workspace\code_coverage---b14a30e5\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WinHttpWebSocketState.cs(288,0): at System.Net.WebSockets.WinHttpWebSocketState.Dispose()
           D:\j\workspace\code_coverage---b14a30e5\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WinHttpWebSocket.cs(740,0): at System.Net.WebSockets.WinHttpWebSocket.Dispose()
           D:\j\workspace\code_coverage---b14a30e5\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WinHttpWebSocket.cs(764,0): at System.Net.WebSockets.WinHttpWebSocket.Abort()
           D:\j\workspace\code_coverage---b14a30e5\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WebSocketHandle.Windows.cs(116,0): at System.Net.WebSockets.WebSocketHandle.Abort()
           D:\j\workspace\code_coverage---b14a30e5\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\ClientWebSocket.cs(197,0): at System.Net.WebSockets.ClientWebSocket.Abort()
           D:\j\workspace\code_coverage---b14a30e5\src\System.Net.WebSockets.Client\tests\AbortTest.cs(103,0): at System.Net.WebSockets.Client.Tests.AbortTest.<>c.<<Abort_CloseAndAbort_Success>b__4_0>d.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           D:\j\workspace\code_coverage---b14a30e5\src\System.Net.WebSockets.Client\tests\ClientWebSocketTestBase.cs(60,0): at System.Net.WebSockets.Client.Tests.ClientWebSocketTestBase.<TestCancellation>d__8.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           D:\j\workspace\code_coverage---b14a30e5\src\System.Net.WebSockets.Client\tests\AbortTest.cs(89,0): at System.Net.WebSockets.Client.Tests.AbortTest.<Abort_CloseAndAbort_Success>d__4.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

**Comment by Priya91** [comment]
Requires investigation.

**Comment by steveharter** [comment]
Appears to be race condition. Per WinHttpWebSocketState.cs(275,0): at System.Net.WebSockets.WinHttpWebSocketState.Dispose(Boolean disposing):
```c#
        private void Dispose(bool disposing)
        {
            if (_webSocketHandle != null)
            {
                _webSocketHandle.Dispose();
                // Will be set to null in the callback.
            }

            if (_requestHandle != null)
            {
>>              _requestHandle.Dispose();
                // Will be set to null in the callback.
            }

            Interop.WinHttp.SafeWinHttpHandle.DisposeAndClearHandle(ref _connectionHandle);
            Interop.WinHttp.SafeWinHttpHandle.DisposeAndClearHandle(ref _sessionHandle);
        }
```

**Comment by stephentoub** [comment]
If it's true that those fields can be set to null concurrently, then these lines should be changed to:
```C#
_webSocketHandle?.Dispose();
_requestHandle?.Dispose();
```
regardless of whether it fixes this issue (but it seems like it should).

**Comment by davidsh** [comment]
I don't see how these lines help:

```c#
_webSocketHandle?.Dispose();
_requestHandle?.Dispose();
```

There is already a check for null.  Adding the "?" operator is just syntax sugar.  If ends up being another "if null" check.  And that operation isn't atomic, so it would be subject to race conditions.  We either need a lock or a re-design.  FWIW, This particular derivation of SafeHandle is not correct and needs to be merged with WinHttpSafeHandle which is used in WinHttpHandler.

**Comment by stephentoub** [comment]
> Adding the "?" operator is just syntax sugar. It ends up being another "if null" check.

The code:
```C#
_webSocketHandle?.Dispose();
```
compiles to the equivalent of:
```C#
var local = _webSocketHandle;
if (local != null) local.Dispose();
```

If the problem is that `_webSocketHandle` is getting null'd out between the check for whether it's null and then the Dispose call, storing the reference into a local and then doing the check on the local avoids the problem.

**Comment by davidsh** [comment]
ok.  In that case, it appears to avoid the ObjectDisposedException.  Calling Dispose() on a SafeHandle multiple times is supposed to be safe.

**Comment by stephentoub** [comment]
> In that case, it appears to avoid the ObjectDisposedException

It would avoid the NullReferenceException noted in the reported issue.
