### ISSUE TITLE
System.Data.SqlClient.Tests.DiagnosticTest.ConnectionOpenTest fails on some CI runs

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#16421]
example: https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/3795/

```
     System.Data.SqlClient.Tests.DiagnosticTest.ConnectionOpenTest [FAIL]
        Timed out after 60000ms waiting for remote process 4644
        Expected: True
        Actual:   False
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\Common\tests\System\Diagnostics\RemoteExecutorTestBase.cs(170,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
```

**Comment by stephentoub** [comment]
This has been happening a few times a day, seemingly only on Windows (or at least that's the only place I've seen it).  I've been unable to repro locally so far.  Most likely this isn't actually a problem with RemoteInvoke: more likely is that the SqlClient work happening in that remote process is hung in a call like SqlConnection.Open(), but at the moment it's difficult to tell without being able to attach to the process.  I have some ideas for how to get more data, but haven't yet been able to put them into practice.

**Comment by joperezr** [comment]
I see, sounds good, well we can use this issue to get the hit count, and if it is to high then we can decide to turn fix/turn off the test. So far, it's happened twice for me.

**Comment by saurabh500** [comment]
I could turn on the logging on the server side in this case so that we know that the server completed the login and add a console statement after Connection Open to see if the connection open call succeeded. That could help eliminate these issues. 
How does that sound @stephentoub  ?

**Comment by danmosemsft** [comment]
I'm not Stephen, but I think that would be great.

**Comment by stephentoub** [comment]
Sounds good.  When you say turn on logging, would that cover cases like this?
https://github.com/dotnet/corefx/blob/77f844f3f05bb85d9f6d6b9ae1c1a7d3cef327aa/src/System.Data.SqlClient/tests/Tools/TDS/TDS.EndPoint/TDSServerEndPoint.cs#L198
I'm wondering if maybe the server is somehow throwing an exception while starting to listen, that exception is getting eaten, and the client times out trying to connect.  Just a random guess...

**Comment by saurabh500** [comment]
Yes. 
https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/tests/FunctionalTests/TestTdsServer.cs#L25

I had turned off the server side logging because it emits a lot of code. 
There are three variables at play here
1. The server
2. The Client
3. The remote executor 

Looking at the history of the tests, these tests should execute in < 1 second and the Remote Executor is timing out waiting for 6 seconds for the process to complete.

The connection timeout that the server returns is 30 seconds. So the client could be waiting for the server response for 30 seconds. In case the server is dead and it has eaten up an exception, the logging should let us know. 
It would still be interesting to find out what caused the change in behavior with RemoteExecutor vs the earlier state of the Connection Open Test. 

I am preparing a PR.

**Comment by saurabh500** [comment]
PR adding logs at https://github.com/dotnet/corefx/pull/16457

**Comment by stephentoub** [comment]
@saurabh500, a related test failed here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu14.04_debug_prtest/84/consoleText
```
  Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: Unknown error 258
     --- End of inner exception stack trace ---
     at System.Data.SqlClient.SqlCommand.EndExecuteReader(IAsyncResult asyncResult) in /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu14.04_debug_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs:line 1386
     at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
     at System.Data.SqlClient.Tests.DiagnosticTest.<>c.<<ExecuteScalarAsyncTest>b__12_1>d.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu14.04_debug_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 244
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Data.SqlClient.Tests.DiagnosticTest.<CollectStatisticsDiagnosticsAsync>d__25.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu14.04_debug_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 840
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Data.SqlClient.Tests.DiagnosticTest.<>c.<ExecuteScalarAsyncTest>b__12_0() in /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu14.04_debug_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 235
     --- End of inner exception stack trace ---
     at RemoteExecutorConsoleApp.Program.Main(String[] args) in /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu14.04_debug_prtest/src/Common/tests/System/Diagnostics/RemoteExecutorConsoleApp/RemoteExecutorConsoleApp.cs:line 60
```

**Comment by saurabh500** [comment]
This is a TCP timeout while communicating with the server. 

I could turn on logging on the server for all the instances of the server, but this could lead to 100s of lines of logs being emitted for each test leg.

**Comment by saurabh500** [comment]
From #16430 

This issue also repro here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_release/115/testReport/System.Data.SqlClient.Tests/DiagnosticTest/ConnectionOpenTest/

@stephentoub @danmosemsft The logs show that the server did not crash and it responded to the login request on time. Also the SqlConnection Open happened successfully.

**Comment by stephentoub** [comment]
> Also the SqlConnection Open happened successfully.

Maybe, but not necessarily.  The log only shows the server side of things, right?  Do we know that the Open call actually successfully returned?  Could we add similar tracing to the client side of the test to see where it gets to, i.e. it starts to open, it finishes the open, it starts to close the connection, it finishes closing the connection, it's about to return from the main function, etc.?

**Comment by saurabh500** [comment]
There was a log statement added after the Connection.Open() statement on the client side. 

Tail end of logs

```
15:50:37   [3/1/2017 3:50:35 PM] Response.TDSFeatureExtAckToken.Options[0].TDSFeatureExtAckSessionStateOption.Options[3].TDSSessionStateLockTimeoutOption.StateID: 5
15:50:37   [3/1/2017 3:50:35 PM] Response.TDSFeatureExtAckToken.Options[0].TDSFeatureExtAckSessionStateOption.Options[4].TDSSessionStateISOFipsOption.TransactionIsolationLevel: ReadCommited
15:50:37   [3/1/2017 3:50:35 PM] Response.TDSFeatureExtAckToken.Options[0].TDSFeatureExtAckSessionStateOption.Options[4].TDSSessionStateISOFipsOption.StateID: 7
15:50:37   [3/1/2017 3:50:35 PM] Response.TDSFeatureExtAckToken.Options[0].TDSFeatureExtAckSessionStateOption.Options[5].TDSSessionStateTextSizeOption.Value: -1
15:50:37   [3/1/2017 3:50:35 PM] Response.TDSFeatureExtAckToken.Options[0].TDSFeatureExtAckSessionStateOption.Options[5].TDSSessionStateTextSizeOption.StateID: 9
15:50:37   [3/1/2017 3:50:35 PM] Response.TDSFeatureExtAckToken.Options[0].TDSFeatureExtAckSessionStateOption.FeatureID: SessionRecovery
15:50:37   [3/1/2017 3:50:35 PM] Response.TDSDoneToken.Status: Final
15:50:37   [3/1/2017 3:50:35 PM] Response.TDSDoneToken.Command: 0
15:50:37   [3/1/2017 3:50:35 PM] Response.TDSDoneToken.RowCount: 0
15:50:37   SqlClient.DiagnosticsTest.ConnectionOpenTest:: Connection Opened 
```

The last line is printed after the client opened the connection successfully

Line of code 
https://github.com/saurabh500/corefx/blob/c10a66dfdec97a94eda18656ac768e0865153012/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs#L421

**Comment by stephentoub** [comment]
> The last line is printed after the client opened the connection successfully

Great.  Can we do something similar for after the connection is closed and also after CollectStatisticsDiagnostics returns?

**Comment by saurabh500** [comment]
Connection Close happens due to the use of using statement for connection open. 

I will add more logs to the `CollectStatisticsDiagnostics` and see what is going on there. 

I think we should also start looking at this from Remote Executor's perspective as well. However, I don't have a theory about it right now.

**Comment by stephentoub** [comment]
> I think we should also start looking at this from Remote Executor's perspective as well. However, I don't have a theory about it right now.

We can.  The reason why I don't think that's likely is we use the remote executor functionality to launch hundreds of tests per test run, and we're only seeing these hangs in these specific SqlClient diagnostic tests.  There could of course be something special about these tests that's triggering a bad behavior in the remote executor stuff.

**Comment by saurabh500** [comment]
I understand your point. 
The Diagnostics test, though had failures in the CI in the past, were due to the way they were being executed and the failures had been due to Guid mismatch. 
It's definitely the combinations of the RemoteExecutor and the Diagnostics test. 

One of the discrepancies is that the process is imposing a timeout of 6000 ms. 
If there are any problems with the underlying tests, and they end up taking more time than expected, they are probably being surfaced here. 

Looking into it.

**Comment by stephentoub** [comment]
https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release_prtest/4093/consoleText
```
Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: Unknown error 258
     --- End of inner exception stack trace ---
     at System.Data.SqlClient.SqlCommand.EndExecuteReader(IAsyncResult asyncResult) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_release_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs:line 1382
     at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Data.SqlClient.Tests.DiagnosticTest.<>c.<<ExecuteScalarAsyncTest>b__12_1>d.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_release_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 244
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  Discovering: System.Linq.Performance.Tests
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Data.SqlClient.Tests.DiagnosticTest.<CollectStatisticsDiagnosticsAsync>d__25.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_release_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 840
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Data.SqlClient.Tests.DiagnosticTest.<>c.<ExecuteScalarAsyncTest>b__12_0() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_release_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 247
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at RemoteExecutorConsoleApp.Program.Main(String[] args) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_release_prtest/src/Common/tests/System/Diagnostics/RemoteExecutorConsoleApp/RemoteExecutorConsoleApp.cs:line 46
  
  Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: Unknown error 258
     --- End of inner exception stack trace ---
     at System.Data.SqlClient.SqlCommand.EndExecuteReader(IAsyncResult asyncResult) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_release_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs:line 1382
     at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Data.SqlClient.Tests.DiagnosticTest.<>c.<<ExecuteScalarAsyncTest>b__12_1>d.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_release_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 244
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Data.SqlClient.Tests.DiagnosticTest.<CollectStatisticsDiagnosticsAsync>d__25.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_release_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 840
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Data.SqlClient.Tests.DiagnosticTest.<>c.<ExecuteScalarAsyncTest>b__12_0() in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_release_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 247
     --- End of inner exception stack trace ---
     at RemoteExecutorConsoleApp.Program.Main(String[] args) in /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_release_prtest/src/Common/tests/System/Diagnostics/RemoteExecutorConsoleApp/RemoteExecutorConsoleApp.cs:line 60
```

**Comment by stephentoub** [comment]
https://ci.dot.net/job/dotnet_corefx/job/master/job/opensuse42.1_release/1197/consoleText
```
Exception from RemoteExecutorConsoleApp(System.Data.SqlClient.Tests, Version=4.1.2.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb, System.Data.SqlClient.Tests.DiagnosticTest+<>c, <ExecuteNonQueryAsyncTest>b__14_0):
  Assembly: System.Data.SqlClient.Tests, Version=4.1.2.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
  Type: System.Data.SqlClient.Tests.DiagnosticTest+<>c
  Method: Int32 <ExecuteNonQueryAsyncTest>b__14_0()
  Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: Unknown error 258
     --- End of inner exception stack trace ---
     at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult) in /mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs:line 988
     at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Data.SqlClient.Tests.DiagnosticTest.<>c.<<ExecuteNonQueryAsyncTest>b__14_1>d.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 288
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Data.SqlClient.Tests.DiagnosticTest.<CollectStatisticsDiagnosticsAsync>d__25.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 840
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Data.SqlClient.Tests.DiagnosticTest.<>c.<ExecuteNonQueryAsyncTest>b__14_0() in /mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 291
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at RemoteExecutorConsoleApp.Program.Main(String[] args) in /mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/src/Common/tests/System/Diagnostics/RemoteExecutorConsoleApp/RemoteExecutorConsoleApp.cs:line 46
  
  Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: Unknown error 258
     --- End of inner exception stack trace ---
     at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult) in /mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs:line 988
     at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Data.SqlClient.Tests.DiagnosticTest.<>c.<<ExecuteNonQueryAsyncTest>b__14_1>d.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 288
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Data.SqlClient.Tests.DiagnosticTest.<CollectStatisticsDiagnosticsAsync>d__25.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 840
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Data.SqlClient.Tests.DiagnosticTest.<>c.<ExecuteNonQueryAsyncTest>b__14_0() in /mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 291
     --- End of inner exception stack trace ---
     at RemoteExecutorConsoleApp.Program.Main(String[] args) in /mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/src/Common/tests/System/Diagnostics/RemoteExecutorConsoleApp/RemoteExecutorConsoleApp.cs:line 60
```

**Comment by Jiayili1** [comment]
Failed again: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_release/116/testReport/System.Data.SqlClient.Tests/DiagnosticTest/ConnectionOpenTest/

**Comment by stephentoub** [comment]
@saurabh500, this failed here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug_prtest/123/consoleText
and you're correct, it does look like the diagnostics are completing:
```
  SqlClient.DiagnosticsTest.ConnectionOpenTest:: Connection Opened 
  SqlClient.DiagnosticsTest.ConnectionOpenTest:: Connection Should Be Disposed
  Test: ConnectionOpenTest SqlOperation Successful
  Test: ConnectionOpenTest Listeners Disabled
  Test: ConnectionOpenTest Server Disposed
  Test: ConnectionOpenTest Listeners Disposed Successfully
  SqlClient.DiagnosticsTest.ConnectionOpenTest:: Done with Diagnostics collection
```
but I have a new theory.  It looks like the server is creating threads, but not background threads (the default is foreground)... and a foreground thread will prevent an app from exiting, so if the remote executor app's main method returns but one of these foreground threads is still running, that'll prevent the process from shutting down and thus cause the remote invoke to hang waiting for the process to exit.  Is it possible these threads aren't being shutdown appropriately?  If so, an easy fix would simply be to mark them as background threads.

**Comment by saurabh500** [comment]
>> Is it possible these threads aren't being shutdown appropriately?

I will inspect the code to figure this out. Perhaps more logging in the shutdown code path of the server could be useful.

**Comment by saurabh500** [comment]
@stephentoub can the remote executor invoke a dump when it times out? Is it a possibility? 
That may give us a better idea of what was going on when Remote Executor timed out.

**Comment by stephentoub** [comment]
> can the remote executor invoke a dump when it times out? Is it a possibility?

I have a local branch that implements effectively that, using ClrMD.  But I can't put it out for PR yet as the ClrMD NuGet package doesn't yet support use from .NET Core.  @leculver is working on that, and once that's fixed, we'll be able to do some cool stuff.

**Comment by saurabh500** [comment]
That would be great. :)

**Comment by saurabh500** [comment]
Linking https://github.com/dotnet/corefx/pull/16906 here for reference

**Comment by saurabh500** [comment]
@danmosemsft Can we assume that it's safe to close this issue as well?

**Comment by stephentoub** [comment]
We haven't seen it again since the relevant fixes went in. Let's close it. We can reopen if we see it again.
