### ISSUE TITLE
Failure in  System.Data.Tests.SqlTypes.SqlXmlTest.Constructor2_Stream_Null - SEHException

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16452]
Not much to go on here. The function at the top of the stack just sets some fields.

https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/114/consoleText

```
  Starting:    System.Data.Common.Tests
     System.Data.Tests.SqlTypes.SqlXmlTest.Constructor2_Stream_Null [FAIL]
        System.Runtime.InteropServices.SEHException : External component has thrown an exception.
        Stack Trace:
           D:\j\workspace\code_coverage---b14a30e5\src\System.Data.Common\src\System\Data\SQLTypes\SqlXml.cs(56,0): at System.Data.SqlTypes.SqlXml..ctor(Stream value)
           D:\j\workspace\code_coverage---b14a30e5\src\System.Data.Common\tests\System\Data\SqlTypes\SqlXmlTest.cs(73,0): at System.Data.Tests.SqlTypes.SqlXmlTest.Constructor2_Stream_Null()
  Finished:    System.Data.Common.Tests
```

**Comment by saurabh500** [comment]
@danmosemsft  I don't see any more failures for this test since this issue was opened. This could have been an intermittent issue. 
Closing this issue. It can be reopened in case we have any other hits.

**Comment by danmosemsft** [comment]
OK
