### ISSUE TITLE
Test "System.Numerics.Vectors.Tests " failed with System.Reflection.TargetInvocationException & System.AccessViolationException

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16555]
Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170228.02/workItem/System.Numerics.Vectors.Tests/wilogs

Failed test: System.Numerics.Vectors.Tests
 
Failed to generate the test result.

Message: 
~~~
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
~~~

Stack Trace: 
~~~
2017-02-28 14:31:52,440: INFO: proc(54): run_and_log_output: Output: Discovering: System.Numerics.Vectors.Tests
2017-02-28 14:31:52,878: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Numerics.Vectors.Tests
2017-02-28 14:31:53,221: INFO: proc(54): run_and_log_output: Output: Starting:    System.Numerics.Vectors.Tests
2017-02-28 14:31:55,035: INFO: proc(54): run_and_log_output: Output: 
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output: Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Numerics.Vector.Narrow(Vector`1 low, Vector`1 high)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Numerics.Tests.GenericVectorTests.NarrowDouble()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    --- End of inner exception stack trace ---
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<<InvokeTestMethodAsync>b__1>d.MoveNext()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<InvokeTestMethodAsync>b__1()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<InvokeTestMethodAsync>b__0()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestInvoker`1.<InvokeTestMethodAsync>d__46.MoveNext()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestInvoker`1.<<RunAsync>b__45_0>d.MoveNext()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestInvoker`1.<RunAsync>b__45_0()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestInvoker`1.RunAsync()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.XunitTestRunner.InvokeTestMethodAsync(ExceptionAggregator aggregator)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.XunitTestRunner.<InvokeTestAsync>d__4.MoveNext()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestRunner`1.<>c__DisplayClass43_0.<RunAsync>b__0()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestRunner`1.RunAsync()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.XunitTestCaseRunner.RunTestAsync()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestCaseRunner`1.RunAsync()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.XunitTestCase.RunAsync(IMessageSink diagnosticMessageSink, IMessageBus messageBus, Object[] constructorArguments, ExceptionAggregator aggregator, CancellationTokenSource cancellationTokenSource)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32.MoveNext()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31.MoveNext()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestMethodRunner`1.RunAsync()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.XunitTestClassRunner.RunTestMethodAsync(ITestMethod testMethod, IReflectionMethodInfo method, IEnumerable`1 testCases, Object[] constructorArguments)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__38.MoveNext()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestClassRunner`1.<RunAsync>d__37.MoveNext()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestClassRunner`1.RunAsync()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.XunitTestCollectionRunner.RunTestClassAsync(ITestClass testClass, IReflectionTypeInfo class, IEnumerable`1 testCases)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestCollectionRunner`1.<RunTestClassesAsync>d__28.MoveNext()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestCollectionRunner`1.<RunAsync>d__27.MoveNext()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestCollectionRunner`1.RunAsync()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.XunitTestAssemblyRunner.RunTestCollectionAsync(IMessageBus messageBus, ITestCollection testCollection, IEnumerable`1 testCases, CancellationTokenSource cancellationTokenSource)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.XunitTestAssemblyRunner.<>c__DisplayClass14_2.<RunTestCollectionsAsync>b__3()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task`1.InnerInvoke()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.<>c.<.cctor>b__276_1(Object obj)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.ExecuteEntry()
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.SynchronizationContextTaskScheduler.<>c.<.cctor>b__8_0(Object s)
2017-02-28 14:31:55,112: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state)
2017-02-28 14:31:55,128: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.MaxConcurrencySyncContext.<>c__DisplayClass11_0.<WorkerThreadProc>b__0(Object _)
2017-02-28 14:31:55,128: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2017-02-28 14:31:55,128: INFO: proc(54): run_and_log_output: Output:    at lambda_method(Closure , Object , Object )
2017-02-28 14:31:55,128: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.ExecutionContextHelper.Run(Object context, Action`1 action)
2017-02-28 14:31:55,128: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc()
2017-02-28 14:31:55,128: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _)
2017-02-28 14:31:55,128: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.InnerInvoke()
2017-02-28 14:31:55,128: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.<>c.<.cctor>b__276_1(Object obj)
2017-02-28 14:31:55,128: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2017-02-28 14:31:55,128: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2017-02-28 14:31:55,128: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.ExecuteEntryUnsafe()
2017-02-28 14:31:55,128: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.ThreadPoolTaskScheduler.<>c.<.cctor>b__10_0(Object s)
2017-02-28 14:31:55,128: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
2017-02-28 14:31:55,128: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2017-02-28 14:31:55,128: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ThreadHelper.ThreadStart(Object obj)
2017-02-28 14:31:57,816: INFO: proc(54): run_and_log_output: Output: Finished running tests.  End time=14:31:57.81, Exit code = -532462766
2017-02-28 14:31:57,816: INFO: proc(58): run_and_log_output: Exit Code: -532462766
2017-02-28 14:31:57,832: ERROR: scriptrunner(82): _main: Error: No exception thrown, but XUnit results not created
2017-02-28 14:31:57,832: ERROR: helix_test_execution(125): report_error: Error running xunit None
~~~

**Comment by mellinoe** [comment]
@pgavlin Here's another occurrence of (I think) the same `Narrow` issue.

**Comment by pgavlin** [comment]
This has now been fixed in CoreCLR with PR https://github.com/dotnet/coreclr/pull/9871; the fix should be picked up here the next time the CoreCLR package is updated.

**Comment by mellinoe** [comment]
@pgavlin Great, thanks! I'll keep an eye on these failures and make sure they go away.
