### ISSUE TITLE
Test "System.Security.Cryptography.Xml.Tests.XmlDsigC14NWithCommentsTransformTest.C14NSpecExample1_WithoutResolver" failed in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16658]
Configuration: OuterLoop_Windows10_release ([build#116](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_release/116/testReport/))

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_release/116/consoleText

Message:
~~~
System.Security.Cryptography.Xml.Tests.XmlDsigC14NWithCommentsTransformTest.C14NSpecExample1_WithoutResolver [FAIL]
        System.AggregateException : One or more errors occurred. (The process cannot access the file 'D:\j\workspace\outerloop_win---6835b088\bin\AnyOS.AnyCPU.Release\System.Security.Cryptography.Xml.Tests\netcoreapp\doc.dtd' because it is being used by another process.) (File.Delete() is not working.)
        ---- System.IO.IOException : The process cannot access the file 'D:\j\workspace\outerloop_win---6835b088\bin\AnyOS.AnyCPU.Release\System.Security.Cryptography.Xml.Tests\netcoreapp\doc.dtd' because it is being used by another process.
        ---- System.Exception : File.Delete() is not working.
~~~

Stack Trace:
~~~
----- Inner Stack Trace #1 (System.IO.IOException) -----
              at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
              at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
           D:\j\workspace\outerloop_win---6835b088\src\System.Runtime.Extensions\src\System\IO\FileStreamHelpers.CoreClr.cs(10,0): at System.IO.FileStreamHelpers.CreateFileStream(String path, Boolean write, Boolean append)
           D:\j\workspace\outerloop_win---6835b088\src\System.Runtime.Extensions\src\System\IO\StreamWriter.cs(137,0): at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
           D:\j\workspace\outerloop_win---6835b088\src\System.Security.Cryptography.Xml\tests\XmlDsigC14NWithCommentsTransformTest.cs(133,0): at System.Security.Cryptography.Xml.Tests.XmlDsigC14NWithCommentsTransformTest.C14NSpecExample1_WithoutResolver()
           ----- Inner Stack Trace #2 (System.Exception) -----
           D:\j\workspace\outerloop_win---6835b088\src\System.Security.Cryptography.Xml\tests\XmlDsigC14NWithCommentsTransformTest.cs(56,0): at System.Security.Cryptography.Xml.Tests.XmlDsigC14NWithCommentsTransformTest.Dispose()
           C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs(76,0): at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
~~~

**Comment by karelz** [comment]
Dupe of #16654
