### ISSUE TITLE
[CI Failure] ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_MismatchProtocols_Fails: "The credentials supplied to the package were not recognized"

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#16651]
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/4083/consoleFull#-126103689779fe3b83-f408-404c-b9e7-9207d232e5fc

```
     System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_MismatchProtocols_Fails(serverProtocol: Tls, clientProtocol: Tls11, expectedException: typeof(System.Security.Authentication.AuthenticationException)) [FAIL]
15:48:14         Assert.Throws() Failure
15:48:14         Expected: typeof(System.Security.Authentication.AuthenticationException)
15:48:14         Actual:   typeof(System.ComponentModel.Win32Exception): The credentials supplied to the package were not recognized
15:48:14         Stack Trace:
15:48:14            D:\j\workspace\windows_nt_de---4526f5ff\src\Common\src\Interop\Windows\sspicli\SSPIWrapper.cs(167,0): at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)
15:48:14            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslStreamPal.Windows.cs(407,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential)
15:48:14            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslStreamPal.Windows.cs(131,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
15:48:14            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs(680,0): at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
15:48:14            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs(783,0): at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
15:48:14            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs(704,0): at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
15:48:14            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslState.cs(767,0): at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
15:48:14            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslState.cs(982,0): at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
15:48:14            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslState.cs(937,0): at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
15:48:14            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslState.cs(885,0): at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
15:48:14            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslState.cs(693,0): at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
15:48:14            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslState.cs(614,0): at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
15:48:14            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslStream.cs(160,0): at System.Net.Security.SslStream.BeginAuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
15:48:14            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslStream.cs(257,0): at System.Net.Security.SslStream.<>c__DisplayClass35_0.<AuthenticateAsServerAsync>b__0(AsyncCallback callback, Object state)
15:48:14               at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
15:48:14               at System.Threading.Tasks.TaskFactory.FromAsync(Func`3 beginMethod, Action`1 endMethod, Object state)
15:48:14            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslStream.cs(257,0): at System.Net.Security.SslStream.AuthenticateAsServerAsync(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
15:48:14            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\tests\FunctionalTests\ServerAsyncAuthenticateTest.cs(154,0): at System.Net.Security.Tests.ServerAsyncAuthenticateTest.<ServerAsyncSslHelper>d__11.MoveNext()
15:48:14            --- End of stack trace from previous location where exception was thrown ---
15:48:14               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
15:48:14               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
15:48:14               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by Priya91** [comment]
cc @ianhays Should this be dupe of #16516

**Comment by ianhays** [comment]
>Should this be dupe of #16516

It should be, yes. This particular test failing is a new thing though; I'll push a PR disabling it and the other recent new failure.
