### ISSUE TITLE
System.Security.Cryptography.Xml failing tests

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#16665]
These two tests are failing outerloop (apparently multi-use problems with dtd file)
System.Security.Cryptography.Xml.Tests.XmlDsigC14NWithCommentsTransformTest.C14NSpecExample1_WithoutResolver (from (empty))
```
Failing for the past 1 build (Since Failed#116 )
Took 4 ms.
Stacktrace

MESSAGE:
System.AggregateException : One or more errors occurred. (The process cannot access the file 'D:\\j\\workspace\\outerloop_win---6835b088\\bin\\AnyOS.AnyCPU.Release\\System.Security.Cryptography.Xml.Tests\\netcoreapp\\doc.dtd' because it is being used by another process.) (File.Delete() is not working.)\r\n---- System.IO.IOException : The process cannot access the file 'D:\\j\\workspace\\outerloop_win---6835b088\\bin\\AnyOS.AnyCPU.Release\\System.Security.Cryptography.Xml.Tests\\netcoreapp\\doc.dtd' because it is being used by another process.\r\n---- System.Exception : File.Delete() is not working.
+++++++++++++++++++
STACK TRACE:
----- Inner Stack Trace #1 (System.IO.IOException) ----- at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) at System.IO.FileStreamHelpers.CreateFileStream(String path, Boolean write, Boolean append) in D:\j\workspace\outerloop_win---6835b088\src\System.Runtime.Extensions\src\System\IO\FileStreamHelpers.CoreClr.cs:line 10 at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize) in D:\j\workspace\outerloop_win---6835b088\src\System.Runtime.Extensions\src\System\IO\StreamWriter.cs:line 137 at System.Security.Cryptography.Xml.Tests.XmlDsigC14NWithCommentsTransformTest.C14NSpecExample1_WithoutResolver() in D:\j\workspace\outerloop_win---6835b088\src\System.Security.Cryptography.Xml\tests\XmlDsigC14NWithCommentsTransformTest.cs:line 133 ----- Inner Stack Trace #2 (System.Exception) ----- at System.Security.Cryptography.Xml.Tests.XmlDsigC14NWithCommentsTransformTest.Dispose() in D:\j\workspace\outerloop_win---6835b088\src\System.Security.Cryptography.Xml\tests\XmlDsigC14NWithCommentsTransformTest.cs:line 56 at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 76
```

System.Security.Cryptography.Xml.Tests.XmlDsigC14NTransformTest.C14NSpecExample1 (from (empty))
```
Failing for the past 1 build (Since Failed#119 )
Took 5 ms.
Stacktrace

MESSAGE:
System.IO.IOException : The process cannot access the file 'D:\\j\\workspace\\outerloop_win---bf7c4efa\\bin\\AnyOS.AnyCPU.Debug\\System.Security.Cryptography.Xml.Tests\\netcoreapp\\doc.dtd' because it is being used by another process.
+++++++++++++++++++
STACK TRACE:
at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) at System.IO.FileStreamHelpers.CreateFileStream(String path, Boolean write, Boolean append) in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Runtime.Extensions\src\System\IO\FileStreamHelpers.CoreClr.cs:line 10 at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize) in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Runtime.Extensions\src\System\IO\StreamWriter.cs:line 140 at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding) in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Runtime.Extensions\src\System\IO\StreamWriter.cs:line 125 at System.Security.Cryptography.Xml.Tests.XmlDsigC14NTransformTest.C14NSpecExample1() in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Security.Cryptography.Xml\tests\XmlDsigC14NTransformTest.cs:line 217
```

**Comment by karelz** [comment]
Dupe of #16654
