### ISSUE TITLE
Add 32-bit version of some MathF tests

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#16674]
broken down from #13592

PR #13572 marked a few tests to be 64-bit only, given that the assumptions they make were only meant for 64-bit runs.

Tests: MathF.Atan2 and MathF.Pow

**Comment by tannergooding** [comment]
@joperezr, what was failing for Atan2 and Pow that caused them to be disabled? That sounds like a bug in the implementation that needs to be fixed. The tests are covering explicit corner cases where a specific output is expected on all platforms.

**Comment by joperezr** [comment]
```
  Discovering: System.Runtime.Extensions.Tests
  Discovered:  System.Runtime.Extensions.Tests
  Starting:    System.Runtime.Extensions.Tests
     System.Tests.MathFTests.Atan2 [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   3.141593
        Stack Trace:
           F:\git\corefx\src\System.Runtime.Extensions\tests\System\MathF.netcoreapp.cs(99,0): at System.Tests.MathFTests.Atan2()
     System.Tests.MathFTests.Pow [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   0
        Stack Trace:
           F:\git\corefx\src\System.Runtime.Extensions\tests\System\MathF.netcoreapp.cs(247,0): at System.Tests.MathFTests.Pow()
  Finished:    System.Runtime.Extensions.Tests
```
