### ISSUE TITLE
ServerAsyncAuthenticate_MismatchProtocols_Fails test fails in some builds

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#16673]
Sample of build where it failed: https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/4121

```
System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_MismatchProtocols_Fails(serverProtocol: Tls, clientProtocol: Tls11, expectedException: typeof(System.Security.Authentication.AuthenticationException)) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.Security.Authentication.AuthenticationException)
        Actual:   typeof(System.ComponentModel.Win32Exception): The credentials supplied to the package were not recognized
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\Common\src\Interop\Windows\sspicli\SSPIWrapper.cs(167,0): at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslStreamPal.Windows.cs(407,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslStreamPal.Windows.cs(131,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs(680,0): at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs(783,0): at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs(704,0): at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslState.cs(767,0): at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslState.cs(982,0): at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslState.cs(937,0): at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslState.cs(885,0): at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslState.cs(693,0): at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslState.cs(614,0): at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslStream.cs(160,0): at System.Net.Security.SslStream.BeginAuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslStream.cs(257,0): at System.Net.Security.SslStream.<>c__DisplayClass35_0.<AuthenticateAsServerAsync>b__0(AsyncCallback callback, Object state)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
              at System.Threading.Tasks.TaskFactory.FromAsync(Func`3 beginMethod, Action`1 endMethod, Object state)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\src\System\Net\Security\SslStream.cs(257,0): at System.Net.Security.SslStream.AuthenticateAsServerAsync(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Security\tests\FunctionalTests\ServerAsyncAuthenticateTest.cs(154,0): at System.Net.Security.Tests.ServerAsyncAuthenticateTest.<ServerAsyncSslHelper>d__11.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

cc: @davidsh, @CIPop, @Priya91

**Comment by Priya91** [comment]
cc @ianhays Is this dupe of #16516

**Comment by joperezr** [comment]
Closing this as it is a dupe of #16651
