### ISSUE TITLE
Failure in System.Data.SqlClient.Tests.DiagnosticTest.ExecuteNonQueryAsyncTest

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16670]
```
MESSAGE:
Assert.Equal() Failure\nExpected: 42\nActual: 134
+++++++++++++++++++
STACK TRACE:
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in /mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs:line 170
```

@saurabh500 not sure whether this is a dupe.

https://ci.dot.net/job/dotnet_corefx/job/master/job/opensuse42.1_release/lastCompletedBuild/testReport/System.Data.SqlClient.Tests/DiagnosticTest/ExecuteNonQueryAsyncTest/

**Comment by danmosemsft** [comment]
If the correct procedure is to subtract 128 then this is Errno 6: No such device or address

**Comment by stephentoub** [comment]
> If the correct procedure is to subtract 128 then this is Errno 6: No such device or address

If the value is higher than 128, then you subtract 128 to get the signal number, not errno value.  This is SIGABRT, which typically means unhandled exception, which you can see earlier in the log (another example of why I don't use the test view ;)

```
  Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: Unknown error 258
     --- End of inner exception stack trace ---
     at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult) in /mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs:line 988
     at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Data.SqlClient.Tests.DiagnosticTest.<>c.<<ExecuteNonQueryAsyncTest>b__14_1>d.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 288
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Data.SqlClient.Tests.DiagnosticTest.<CollectStatisticsDiagnosticsAsync>d__25.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 840
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Data.SqlClient.Tests.DiagnosticTest.<>c.<ExecuteNonQueryAsyncTest>b__14_0() in /mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 291
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at RemoteExecutorConsoleApp.Program.Main(String[] args) in /mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/src/Common/tests/System/Diagnostics/RemoteExecutorConsoleApp/RemoteExecutorConsoleApp.cs:line 46
```

**Comment by danmosemsft** [comment]
Ah...

**Comment by stephentoub** [comment]
(I need to find some time to make the remote executor better, e.g. to capture exceptions and propagate them to the host, to better highlight why / when things have hung, etc.  Just haven't gotten to it yet.)

**Comment by Jiayili1** [comment]
This issue is repro on 20170310.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170310.01/workItem/System.Data.SqlClient.Tests/analysis/xunit/System.Data.SqlClient.Tests.DiagnosticTest~2FConnectionOpenAsyncTest

Message: 
~~~
Assert.Equal() Failure\r\nExpected: 42\r\nActual:   -532462766
~~~

Stack Trace:
~~~
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
   at System.Data.SqlClient.Tests.DiagnosticTest.ConnectionOpenAsyncTest()
~~~

**Comment by saurabh500** [comment]
All the Diagnostics Test failed in the above execution.

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170310.01/workItem/System.Data.SqlClient.Tests

There was a failure to load SNI.dll 

```

2017-03-10 02:35:38,391: INFO: proc(54): run_and_log_output: Output:    System.Data.SqlClient.Tests.SqlConnectionBasicTests.ConnectionTest [FAIL]
2017-03-10 02:35:38,391: INFO: proc(54): run_and_log_output: Output:       Assert.Null() Failure
2017-03-10 02:35:38,391: INFO: proc(54): run_and_log_output: Output:       Expected: (null)
2017-03-10 02:35:38,391: INFO: proc(54): run_and_log_output: Output:       Actual:   System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
2017-03-10 02:35:38,391: INFO: proc(54): run_and_log_output: Output:          at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize(IntPtr pmo)
2017-03-10 02:35:38,391: INFO: proc(54): run_and_log_output: Output:          at System.Data.SqlClient.SNILoadHandle..ctor()
2017-03-10 02:35:38,391: INFO: proc(54): run_and_log_output: Output:          at System.Data.SqlClient.SNILoadHandle..cctor()
2017-03-10 02:35:38,391: INFO: proc(54): run_and_log_output: Output:          --- End of inner exception stack trace ---
2017-03-10 02:35:38,391: INFO: proc(54): run_and_log_output: Output:          at System.Data.SqlClient.TdsParserStateObjectFactory.get_EncryptionOptions()
2017-03-10 02:35:38,391: INFO: proc(54): run_and_log_output: Output:          at System.Data.SqlClient.TdsParser..cctor()
2017-03-10 02:35:38,391: INFO: proc(54): run_and_log_output: Output:          --- End of inner exception stack trace ---
2017-03-10 02:35:38,391: INFO: proc(54): run_and_log_output: Output:          at System.Data.SqlClient.TdsParser..ctor(Boolean MARS, Boolean fAsynchronous)
2

```

**Comment by saurabh500** [comment]
There is an issue I filed where the older sni.dll is being packaged for CoreFx. 
https://github.com/dotnet/corefx/issues/16918

@Jiayili1 what is the Windows OS version of the machine these test is failing on?

**Comment by Jiayili1** [comment]
@saurabh500 It is failed on windows_nt.x86 and windows_nt.amd64

**Comment by saurabh500** [comment]
This should be fixed with https://github.com/dotnet/corefx/issues/16918
