### ISSUE TITLE
SendBufferSize set to 0 results in an exception on macOS

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#16716]
I'm not sure if this should be considered by design or worked around, but setting Socket.SendBufferSize to 0 on macOS is resulting in an exception:
```
        System.Net.Sockets.SocketException : Invalid argument
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(5332,0): at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(4835,0): at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(1827,0): at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(455,0): at System.Net.Sockets.Socket.set_SendBufferSize(Int32 value)
```

**Comment by geoffkizer** [comment]
Is there an existing test for this?

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/blob/899a6d9ac28f77bef369546263af648df453c86c/src/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs#L683

**Comment by Priya91** [comment]
Verified with native app, on OS X, i get -1 from setsockopt when using 0 for so_sndbuf option.

```c
#include <sys/socket.h>
#include <stdio.h>
#include <errno.h>

int main(int argc, char **argv)
{
 int sockfd, sendbuff;
 sockfd = socket(AF_INET, SOCK_DGRAM, 0);
 if(sockfd == -1)
     printf("Error");

 int res = 0;

 // Set buffer size
 sendbuff = 0;

 printf("sets the send buffer to %d\n", sendbuff);
 res = setsockopt(sockfd, SOL_SOCKET, SO_SNDBUF, &sendbuff, sizeof(sendbuff));

 if(res == -1)
     printf("Error setsockopt: %d\n", errno);

 return 0;
}
```

gives,

```
lasekar-osx:myprograms lakshmipriya$ ./a.out 
sets the send buffer to 0
Error setsockopt: 22
```

**Comment by karelz** [comment]
Do we plan to compensate for it in CoreFX? Or are we fine with exposing OS behavior?

If it is the former, we need a product change and then re-enable the test.
If it is the latter, we should add Mac specific test, testing the exception.

Currently #17506 just disables the test on Mac and marks this issue as 'fixed'.

**Comment by safern** [comment]
Python also throws an error when trying to set socket size to 0 on Mac but in Windows it doesn't. So I think we should add Mac specific test expecting the exception. 

Assigning myself.
