### ISSUE TITLE
Missing Method Exceptions from Kestrel when trying to run Web API on Raspberry Pi

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/corefx#16778]
@challe commented on [Sat Mar 04 2017](https://github.com/dotnet/core-setup/issues/1632)

## Steps to reproduce
`dotnet new webapi`

Change the `csproj`-file so that it looks like this:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
 <PropertyGroup>
   <TargetFramework>netcoreapp2.0</TargetFramework>
   <RuntimeFrameworkVersion>2.0.0-beta-001663-00</RuntimeFrameworkVersion>
 </PropertyGroup>

 <ItemGroup>
   <PackageReference Include="Microsoft.AspNetCore" Version="1.2.0-preview1-23656" />
   <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.2.0-preview1-23656" />
   <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.2.0-preview1-23656" />
 </ItemGroup>
</Project>
```
Followed by
```
dotnet restore
dotnet publish
```

Now take all of the files that were created in the `bin/Debug/netcoreapp2.0/publish` and copy these files to the Raspberry Pi. Try to run the application by doing:
`usr/bin/dotnet /home/challe/dev/test/test.dll`.

It says that the application has started and that it is listening on port 5000!
Visit http://localhost:5000/api/values in the browser, locally on your Raspberry Pi.

## Expected  behavior
I expected to see the JSON values in the browser.

## Actual behavior
In the terminal, I see:
```
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

## Environment data
I am currently using the `2.0.0-beta-001663-00` runtime on my Raspberry Pi.

`dotnet --info` output:
.NET Command Line Tools (2.0.0-alpha-004853)

Product Information:
 Version:            2.0.0-alpha-004853
 Commit SHA-1 hash:  e7689a3116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-alpha-004853\

---

@Petermarcu commented on [Sat Mar 04 2017](https://github.com/dotnet/core-setup/issues/1632#issuecomment-284159339)

Interesting, there is an effort going on right now to move ASP.NET on top of Span. @KrzysztofCwalina , does there need to be an explicit reference to the Span package at this point?

I think its in this package: https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Memory

ASP.NET versions that use that type should be referencing that package.

---

@Petermarcu commented on [Sat Mar 04 2017](https://github.com/dotnet/core-setup/issues/1632#issuecomment-284159409)

I'm guessing this happens everywhere. Not just on your Pi.

---

@gkhanna79 commented on [Sat Mar 04 2017](https://github.com/dotnet/core-setup/issues/1632#issuecomment-284178854)

CC @jkotas 

---

@jkotas commented on [Sat Mar 04 2017](https://github.com/dotnet/core-setup/issues/1632#issuecomment-284179698)

This is caused by breaking change in System.Memory public surface that @ahsonkhan made to fix https://github.com/dotnet/corefx/issues/13681.

ASP.NET needs to pick up latest version of System.Memory packages to be compatible with latest Microsoft.NETCore.App.

---

@jkotas commented on [Sat Mar 04 2017](https://github.com/dotnet/core-setup/issues/1632#issuecomment-284181133)

@davidfowl What does need to happen for ASP.NET to pick up latest System.Memory?

---

@davidfowl commented on [Sat Mar 04 2017](https://github.com/dotnet/core-setup/issues/1632#issuecomment-284191517)

I'm surprised we're even binding to that method. We need to wait until the corefxlab packages get mirrored into asp.net's feed. That's being worked on...No eta yet /cc @pranavkm

---

@Petermarcu commented on [Sat Mar 04 2017](https://github.com/dotnet/core-setup/issues/1632#issuecomment-284191648)

In the meantime, can @challe reference the package directly or will that break other things?

---

@davidfowl commented on [Sat Mar 04 2017](https://github.com/dotnet/core-setup/issues/1632#issuecomment-284192891)

Referencing the package won't help. You'd need to downgrade your runtime back to netcoreapp1.1 or use an earlier version of 2.0 that doesn't have this change.

---

@Petermarcu commented on [Sat Mar 04 2017](https://github.com/dotnet/core-setup/issues/1632#issuecomment-284200233)

Can't, this is an architecture we don't have in 1.X. we need to get 2.0 working.

---

@Petermarcu commented on [Sat Mar 04 2017](https://github.com/dotnet/core-setup/issues/1632#issuecomment-284200264)

Should we undo the breaking change until this is properly coordinated?

---

@davidfowl commented on [Sat Mar 04 2017](https://github.com/dotnet/core-setup/issues/1632#issuecomment-284202802)

> Should we undo the breaking change until this is properly coordinated?

We *could* but I like using it as a forcing function to get our mirror fixed.

/cc @Eilon 

---

@Petermarcu commented on [Sat Mar 04 2017](https://github.com/dotnet/core-setup/issues/1632#issuecomment-284203975)

It would be great to understand how long this will be broken and back out the change if its going to be more than a day or so. We have a lot of people using 2.0 pre-release builds that will quickly discover this break.

---

@jkotas commented on [Sat Mar 04 2017](https://github.com/dotnet/core-setup/issues/1632#issuecomment-284205909)

https://github.com/aspnet/kestrelHttpServer is the last part that requires updating to get the change absorbed. Revering it would need to propagate through coreclr, corefx and corefxlab - definitely longer path.

---

@Petermarcu commented on [Sun Mar 05 2017](https://github.com/dotnet/core-setup/issues/1632#issuecomment-284269486)

Looks like ASP.NET was able to get a build out with all the updated references.  If you get the latest from the MyGet feed this should be fixed. Here is the feed to add to your NuGet.config (I assume you already had it).

https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json

Make sure you have at least : Microsoft.AspNetCore.Server.Kestrel 1.2.0-preview1-23736

**Comment by mellinoe** [comment]
> If you get the latest from the MyGet feed this should be fixed.

Is this fixed, then? What's left to do?

**Comment by davidfowl** [comment]
Close
