### ISSUE TITLE
Dumping error   ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16843]
@mellinoe is this behaving normally?

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/lastCompletedBuild/consoleText 
```
bf7c4efa\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
  Trying to find crash dumps for project: System.Data.SqlClient.Tests
  Traceback (most recent call last):
    File "DumplingHelper.py", line 75, in <module>
      main(sys.argv)
    File "DumplingHelper.py", line 67, in main
      collect_dump(argv[2], argv[3], argv[4], argv[5])
    File "DumplingHelper.py", line 33, in collect_dump
      file = find_latest_dump(folder, startTimeStr)
    File "DumplingHelper.py", line 22, in find_latest_dump
      latestFile = max(allFiles, key=os.path.getctime)
  ValueError: max() arg is an empty sequence
  Finished running tests.  End time=10:55:32.45, Exit code = 1
```

**Comment by mellinoe** [comment]
Gah, that's probably because there are no files in the dump folder at all. It shouldn't have any negative effects other than printing unnecessary stuff out when tests fail. I will submit a fix to buildtools.
