### ISSUE TITLE
Try running tests that use pinning under GCStress 

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16926]
As suggested in https://github.com/dotnet/corefx/pull/16922#issuecomment-285491684

There have been several bugs found through missing pinning in Crypto or Networking.

We should try running at least those tests under `set COMPLUS_GCStress=3`

It may be it's too slow -- but we could just let it run if it's merely slow.

**Comment by danmosemsft** [comment]
Of course if it is slow -- tests with timeouts may fail for those -- which would need filtering out/modifying to get past

**Comment by danmosemsft** [comment]
Trying this on S.Net.Sockets initially. After 5 mins I got this

```
nhandled Exception: System.ArgumentException: The AddressFamily 257 is not valid for the System.Net.IPEndPoint end point, use InterNetwork instead.
Parameter name: socketAddress
   at System.Net.Sockets.IPEndPointExtensions.Create(EndPoint thisObj, SocketAddress socketAddress) in C:\git\corefx\src\Common\src\System\Net\Internals\IPEndPointExtensions.cs:line 33
   at System.Net.Sockets.AcceptOverlappedAsyncResult.PostCompletion(Int32 numBytes) in C:\git\corefx\src\System.Net.Sockets\src\System\Net\Sockets\AcceptOverlappedAsyncResult.Windows.cs:line 79
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError socketError) in C:\git\corefx\src\System.Net.Sockets\src\System\Net\Sockets\BaseOverlappedAsyncResult.Windows.cs:line 139
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in C:\git\corefx\src\System.Net.Sockets\src\System\Net\Sockets\BaseOverlappedAsyncResult.Windows.cs:line 127
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

@stephentoub  famliiar?

**Comment by danmosemsft** [comment]
Oh - it found https://github.com/dotnet/corefx/issues/16953. I assume you found that without stress, so maybe it's unrelated to the stress flag. I'll try again with the fix for that.

**Comment by stephentoub** [comment]
> famliiar? bug newly exposed here?

It was introduced by https://github.com/dotnet/corefx/pull/15141

**Comment by danmosemsft** [comment]
This is in progress

**Comment by danmosemsft** [comment]
This was done for Windows and Unix (without result) but I'm not convinced it actually did anything on Unix.

I would like to do this for 2.0 but I can't say it's vital.

**Comment by danmosemsft** [comment]
In progress for Unix

**Comment by danmosemsft** [comment]
This is happening but may not be done by ZBB.

**Comment by danmosemsft** [comment]
Almost complete.

**Comment by tarekgh** [comment]
@danmosemsft are you going to finish this before the end of the week?

**Comment by danmosemsft** [comment]
I've pinged for an update but probably it will continue on.

**Comment by stephentoub** [comment]
@danmosemsft, can this issue be closed now?

**Comment by danmosemsft** [comment]
Let's call this done.
