### ISSUE TITLE
Unhandled exception from IPEndPointExtensions.Create in Socket tests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#16953]
```
Unhandled Exception: System.ArgumentException: The AddressFamily Unspecified is not valid for the System.Net.IPEndPoint end point, use InterNetwork instead.
Parameter name: socketAddress
   at System.Net.Sockets.IPEndPointExtensions.Create(EndPoint thisObj, SocketAddress socketAddress) in C:\users\stoub\Source\repos\corefx\src\Common\src\System\Net\Internals\IPEndPointExtensions.cs:line 33
   at System.Net.Sockets.AcceptOverlappedAsyncResult.PostCompletion(Int32 numBytes) in C:\users\stoub\Source\repos\corefx\src\System.Net.Sockets\src\System\Net\Sockets\AcceptOverlappedAsyncResult.Windows.cs:line 79
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError socketError) in C:\users\stoub\Source\repos\corefx\src\System.Net.Sockets\src\System\Net\Sockets\BaseOverlappedAsyncResult.Windows.cs:line 139
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in C:\users\stoub\Source\repos\corefx\src\System.Net.Sockets\src\System\Net\Sockets\BaseOverlappedAsyncResult.Windows.cs:line 127
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

**Comment by stephentoub** [comment]
Failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug_prtest/131/consoleText
