### ISSUE TITLE
Failure in System.Diagnostics.Tests.ProcessTests.TestRootGetProcessById in CI

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16958]
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/4347/consoleFull#-6109453532d31e50d-1517-49fc-92b3-2ca637122019
.
```
     System.Diagnostics.Tests.ProcessTests.TestRootGetProcessById [FAIL]
19:19:29         Assert.True() Failure
19:19:29         Expected: True
19:19:29         Actual:   False
19:19:29         Stack Trace:
19:19:29            /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Diagnostics.Process/tests/ProcessTestBase.cs(33,0): at System.Diagnostics.Tests.ProcessTestBase.Dispose(Boolean disposing)
19:19:29            /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/Common/tests/System/IO/FileCleanupTestBase.cs(41,0): at System.IO.FileCleanupTestBase.Dispose()
19:19:29               at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
19:19:43   Finished:    System.Diagnostics.Process.Tests
19:19:43   
19:19:43   === TEST EXECUTION SUMMARY ===
19:19:43 /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/Tools/tests.targets(247,5): warning :    System.Diagnostics.Process.Tests  Total: 108, Errors: 0, Failed: 1, Skipped: 0, Time: 625.446s [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Diagnostics.Process/tests/System.Diagnostics.Process.Tests.csproj]
```

XUnit creates the test fixture (class) for each test invoked. After the test completes, it disposes the class: 
https://github.com/xunit/xunit/blob/master/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs#L216

This test doesn't make any processes but its base class makes one that sleeps 5 minutes (for no obvious reason)
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/tests/ProcessTestBase.cs#L19

In dispose of the base class it kills the process if necessary then waits 5 minutes if necessary
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/tests/ProcessTestBase.cs#L33

This seems pretty random. Is the machine so overloaded that it takes over 5 minutes to kill the process?

@Priya91

**Comment by danmosemsft** [comment]
Actually for this to fail two things would both have to fail, seemingly (1) the sleep not complete in less than 2x5 minutes (2) the kill not succeed or take over 5 minutes.

Whatever the reason perhaps ProcessTestBase could stop making this default process in its constructor. Then this test at least would have nothign to wait on.
