### ISSUE TITLE
Test: System.Xml.Tests.XmlConvertTests.ToTypeTests failed in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#17036]
Configuration: OuterLoop_Fedora24_debug ([build#115](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora24_debug/115/testReport/))

Failed test: System.Xml.Tests.XmlConvertTests.ToTypeTests

Message:
~~~
System.Xml.Tests.XmlConvertTests.ToTypeTests [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   3
~~~

Stack trace:
~~~
at System.Xml.Tests.XmlConvertTests.RunTestCase(CTestBase testCase) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_debug/src/System.Private.Xml/tests/XmlConvert/XmlConvertTests.cs:line 209 at System.Xml.Tests.XmlConvertTests.ToTypeTests() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_debug/src/System.Private.Xml/tests/XmlConvert/XmlConvertTests.cs:line 58
~~~

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora24_debug/115/consoleText

**Comment by danmosemsft** [comment]
@sepidehMS

**Comment by danmosemsft** [comment]
Is this one of those cases where xnuit wraps something else? Asj ust above this in the log I see the real output:
```
  TestCase:XmlConvert type conversion functions - XmlConvert
  ERROR: 23:15:55 Object Compare
  Expected: 3/12/17 11:15:55 PM -08:00
  Actual  : 3/12/17 11:15:55 PM -07:00
  	ToDateTimeOffset(String s, String[] formats) - valid cases
  unexpected exception happened:23:15:55 Object Compare
     at OLEDB.Test.ModuleCore.CError.Compare(Object actual, Object expected, String message) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_debug/src/Common/tests/System/Xml/ModuleCore/cerror.cs:line 224
     at System.Xml.Tests.ToTypeTests.TestValid(Object[] array0, Object[] array1, String type, String[] format) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_debug/src/System.Private.Xml/tests/XmlConvert/ToTypeTests.cs:line 288
     at System.Xml.Tests.ToTypeTests.ToType52() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_debug/src/System.Private.Xml/tests/XmlConvert/ToTypeTests.cs:line 841
     at OLEDB.Test.ModuleCore.CVariation.Execute() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_debug/src/Common/tests/System/Xml/ModuleCore/cvariation.cs:line 75
     at OLEDB.Test.ModuleCore.CTestCase.Execute() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_debug/src/Common/tests/System/Xml/ModuleCore/ctestcase.cs:line 70
  	 FAILED
  ERROR: 23:15:55 Object Compare
  Expected: 3/12/17 11:15:55 PM -08:00
  Actual  : 3/12/17 11:15:55 PM -07:00
  	ToDateTimeOffset(String s, String format) - valid cases
  unexpected exception happened:23:15:55 Object Compare
     at OLEDB.Test.ModuleCore.CError.Compare(Object actual, Object expected, String message) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_debug/src/Common/tests/System/Xml/ModuleCore/cerror.cs:line 224
     at System.Xml.Tests.ToTypeTests.TestValid(Object[] array0, Object[] array1, String type, String[] format) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_debug/src/System.Private.Xml/tests/XmlConvert/ToTypeTests.cs:line 288
     at System.Xml.Tests.ToTypeTests.ToType52() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_debug/src/System.Private.Xml/tests/XmlConvert/ToTypeTests.cs:line 841
     at OLEDB.Test.ModuleCore.CVariation.Execute() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_debug/src/Common/tests/System/Xml/ModuleCore/cvariation.cs:line 75
     at OLEDB.Test.ModuleCore.CTestCase.Execute() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_debug/src/Common/tests/System/Xml/ModuleCore/ctestcase.cs:line 70
  	 FAILED
  ERROR: 23:15:55 Object Compare
  Expected: 3/12/17 11:15:55 PM -08:00
  Actual  : 3/12/17 11:15:55 PM -07:00
  	ToDateTimeOffset(String s) - valid cases
  unexpected exception happened:23:15:55 Object Compare
     at OLEDB.Test.ModuleCore.CError.Compare(Object actual, Object expected, String message) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_debug/src/Common/tests/System/Xml/ModuleCore/cerror.cs:line 224
     at System.Xml.Tests.ToTypeTests.TestValid(Object[] array0, Object[] array1, String type, String[] format) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_debug/src/System.Private.Xml/tests/XmlConvert/ToTypeTests.cs:line 288
     at System.Xml.Tests.ToTypeTests.ToType52() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_debug/src/System.Private.Xml/tests/XmlConvert/ToTypeTests.cs:line 841
     at OLEDB.Test.ModuleCore.CVariation.Execute() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_debug/src/Common/tests/System/Xml/ModuleCore/cvariation.cs:line 75
     at OLEDB.Test.ModuleCore.CTestCase.Execute() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_debug/src/Common/tests/System/Xml/ModuleCore/ctestcase.cs:line 70
  	 FAILED
  Pass:58, Fail:3, Skip:0
```

It's a daylight savings time issue!

**Comment by danmosemsft** [comment]
@tarekgh what would be the appropriate change to make this sequence safe?
1) serialize a DateTimeOffset
2) daylight savings time changes
3) deseriallize a DateTimeOffset
4) check (1) and (2) are equal.

**Comment by sepidehMS** [comment]
@danmosemsft Yes, these tests are wrapped in a single runner.

**Comment by tarekgh** [comment]
@danmosemsft using TimeZoneInfo.IsAmbiguousTime should help but I am seeing other failure using it and still failing so I'll need to take a look why the other cases are failing first.

**Comment by tarekgh** [comment]
talked offline with @sepidehMS and showed here where is the problem. it is test bug.
