### ISSUE TITLE
"No more data is available" error in EnumerateEnvironmentVariables test

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#17044]
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_release/126/consoleText
```
     System.Tests.GetEnvironmentVariable.EnumerateEnvironmentVariables(target: User) [FAIL]
        System.IO.IOException : No more data is available.
        
        Stack Trace:
              at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
              at Microsoft.Win32.RegistryKey.GetValueNames()
              at System.Environment.GetEnvironmentVariablesCore(EnvironmentVariableTarget target)
           D:\j\workspace\outerloop_win---6835b088\src\System.Runtime.Extensions\tests\System\Environment.GetEnvironmentVariable.cs(243,0): at System.Tests.GetEnvironmentVariable.EnumerateEnvironmentVariables(EnvironmentVariableTarget target)
```

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/17037
