### ISSUE TITLE
Compression tests are writing their test files to their install directory

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#17072]
Compression tests are writing their test files to their install directory. In appcontainer, they apparently can't do that.

In the example below, `ZipTestData\StrangeZipFiles\largetrailingwhitespacedeflation.zip` comes from the test and it's just suffixed onto the folder of the dll, which I guess is the current directory.

```
2017-03-13 22:45:49,839: INFO: proc(54): run_and_log_output: Output: Hello + ' C:\dotnetbuild\work\22eb33a7-3458-4f94-b2f1-56522dd4cb26\Work\7db140f3-b2ca-4270-b359-7fce63d78e6b\Unzip\\System.IO.Compression.Tests.dll'
2017-03-13 22:45:49,839: INFO: proc(54): run_and_log_output: Output:   Discovering: System.IO.Compression.Tests
2017-03-13 22:45:49,839: INFO: proc(54): run_and_log_output: Output:   Discovered:  System.IO.Compression.Tests
2017-03-13 22:45:49,839: INFO: proc(54): run_and_log_output: Output:   Starting:    System.IO.Compression.Tests
2017-03-13 22:45:49,839: INFO: proc(54): run_and_log_output: Output: ERROR:    System.IO.Compression.Tests.zip_InvalidParametersAndStrangeFiles.ZipWithLargeSparseFile [FAIL]
2017-03-13 22:45:49,839: INFO: proc(54): run_and_log_output: Output:       System.UnauthorizedAccessException : Access to the path 'C:\dotnetbuild\work\22eb33a7-3458-4f94-b2f1-56522dd4cb26\Work\7db140f3-b2ca-4270-b359-7fce63d78e6b\Unzip\ZipTestData\StrangeZipFiles\largetrailingwhitespacedeflation.zip' is denied.
2017-03-13 22:45:49,839: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-03-13 22:45:49,839: INFO: proc(54): run_and_log_output: Output:            at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
2017-03-13 22:45:49,839: INFO: proc(54): run_and_log_output: Output:            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2017-03-13 22:45:49,839: INFO: proc(54): run_and_log_output: Output:            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
2017-03-13 22:45:49,839: INFO: proc(54): run_and_log_output: Output:            at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
2017-03-13 22:45:49,839: INFO: proc(54): run_and_log_output: Output:            at System.IO.File.Open(String path, FileMode mode, FileAccess access)
2017-03-13 22:45:49,839: INFO: proc(54): run_and_log_output: Output:            at System.IO.Compression.Tests.zip_InvalidParametersAndStrangeFiles.ZipWithLargeSparseFile()
2017-03-13 22:45:49,839: INFO: proc(54): run_and_log_output: Output:   Finished:    System.IO.Compression.Tests
```

@AlexGhiondea this was in your private run.

**Comment by danmosemsft** [comment]
@StanislavUshakov as requested here you are!

**Comment by StanislavUshakov** [comment]
@danmosemsft Thank you, already done!

**Comment by danmosemsft** [comment]
Great -- pick your next issue and I'll assign it! 
https://github.com/dotnet/corefx/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.0+label%3A%22up+for+grabs%22
