### ISSUE TITLE
UnloadingEventMustHappenBeforeProcessExitEvent failed in CI

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#17080]
This is the first use of the folder for this test -- it's upstream of the remote process. It appears that FileCleanupTestBase failed to make the directory. Need to add logging.

``` c#
        protected FileCleanupTestBase()
        {
            TestDirectory = Path.Combine(Path.GetTempPath(), GetType().Name + "_" + Path.GetRandomFileName());
            try
            {
                Directory.CreateDirectory(TestDirectory);
            }
            catch
            {
            }
```

Perhaps we should log (Console.WriteLine if necessary)

```
     System.Tests.UnloadingAndProcessExitTests.UnloadingEventMustHappenBeforeProcessExitEvent [FAIL]
        System.IO.DirectoryNotFoundException : Could not find a part of the path '/home/someuser/some tempdir/UnloadingAndProcessExitTests_b0ejqce4.zgv/UnloadingEventMustHappenBeforeProcessExitEvent_13'.
        Stack Trace:
              at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
              at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
              at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
              at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
              at System.IO.FileStreamHelpers.CreateFileStream(String path, Boolean write, Boolean append)
              at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
              at System.IO.StreamWriter..ctor(String path)
              at System.IO.File.WriteAllText(String path, String contents)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Runtime.Extensions/tests/System/UnloadingAndProcessExitTests.netcoreapp.cs(15,0): at System.Tests.UnloadingAndProcessExitTests.UnloadingEventMustHappenBeforeProcessExitEvent()
  Using as the test runtime folder.
```

**Comment by danmosemsft** [comment]
@Jiayili1 please help grab the logging if this fails again.

**Comment by Jiayili1** [comment]
@danmosemsft I will update the comment here if this fails again.

**Comment by danmosemsft** [comment]
Added retries in 3112c62
