### ISSUE TITLE
Test: System.Data.SqlClient.Tests.SqlConnectionBasicTests.ConnectionTest  failed in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#17088]
Failed test: System.Data.SqlClient.Tests.SqlConnectionBasicTests.ConnectionTest 

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora24_debug/1369/consoleText

Configuration: InnerLoop_Fedora24_debug (build#1369)

Message:
~~~
 System.Data.SqlClient.Tests.SqlConnectionBasicTests.ConnectionTest [FAIL]
        Assert.Null() Failure
        Expected: (null)
        Actual:   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
~~~

Stack Trace:
~~~
at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling) in /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlInternalConnectionTds.cs:line 372
           at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions) in /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnectionFactory.cs:line 133
           at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions) in /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionFactory.cs:line 114
           at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection) in /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs:line 476
           at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection) in /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs:line 1187
           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection) in /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs:line 792
           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection) in /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs:line 712
           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection) in /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionFactory.cs:line 281
           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionInternal.cs:line 452
           at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionClosed.cs:line 64
           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry) in /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnection.cs:line 992
           at System.Data.SqlClient.SqlConnection.Open() in /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnection.cs:line 585
           at System.Data.SqlClient.Tests.SqlConnectionBasicTests.ConnectionTest() in /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Data.SqlClient/tests/FunctionalTests/SqlConnectionTest.cs:line 23
~~~

**Comment by Jiayili1** [comment]
This test failed again on full framework tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170411.01/workItem/System.Data.SqlClient.Tests/analysis/xunit/System.Data.SqlClient.Tests.SqlConnectionBasicTests~2FConnectionTest

**Comment by safern** [comment]
I don't see this one failing on desktop anymore. Removing label.

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170413.04/workItem/System.Data.SqlClient.Tests

**Comment by Jiayili1** [comment]
This issue is repro, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_fedora24_debug/28/testReport/System.Data.SqlClient.Tests/SqlConnectionBasicTests/ConnectionTest/

**Comment by ViktorHofer** [comment]
@corivera this is one of the last issues for ZBB. Are you working on it?

**Comment by corivera** [comment]
Likely an issue with SQL tests' proxy server code. Moving to Future

**Comment by v-haren** [comment]
failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_fedora24_debug/65/testReport/System.Data.SqlClient.Tests/SqlConnectionBasicTests/ConnectionTest/
