### ISSUE TITLE
EventSource_EventsRaisedAsExpected in System.Net.Security tests failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#17103]
This test turns on events and then calls a few other tests, so the actual failure ("The credentials supplied to the package were not recognized") is coming from System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Authentication_Success.
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/4621/consoleText
```
  Exception from RemoteExecutorConsoleApp(System.Net.Security.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb, System.Net.Security.Tests.LoggingTest+<>c, <EventSource_EventsRaisedAsExpected>b__1_0):
  Assembly: System.Net.Security.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
  Type: System.Net.Security.Tests.LoggingTest+<>c
  Method: Int32 <EventSource_EventsRaisedAsExpected>b__1_0()
  Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.) (The credentials supplied to the package were not recognized) ---> System.TimeoutException: VirtualNetwork: Timeout reading the next frame.
     at System.Net.Test.Common.VirtualNetwork.ReadFrame(Boolean server, Byte[]& buffer) in D:\j\workspace\windows_nt_re---37265eab\src\Common\tests\System\Net\VirtualNetwork\VirtualNetwork.cs:line 39
     at System.Net.Test.Common.VirtualNetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count) in D:\j\workspace\windows_nt_re---37265eab\src\Common\tests\System\Net\VirtualNetwork\VirtualNetworkStream.cs:line 119
     at System.Threading.Tasks.Task`1.InnerInvoke()
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Threading.Tasks.TaskToApm.End[TResult](IAsyncResult asyncResult) in D:\j\workspace\windows_nt_re---37265eab\src\Common\src\System\Threading\Tasks\TaskToApm.cs:line 115
     at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult) in D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\FixedSizeReader.cs:line 143
     System.IO.Tests.Directory_Delete_Tests.FileSystemWatcher_Directory_Delete_SymLink [SKIP]
        Condition(s) not met: \"CanCreateSymbolicLinks\"
     System.IO.Tests.Directory_Changed_Tests.FileSystemWatcher_Directory_Changed_SymLink [SKIP]
        Condition(s) not met: \"CanCreateSymbolicLinks\"
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result) in D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslState.cs:line 731
     at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
     --- End of inner exception stack trace ---
     at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
     at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
     at System.Net.Security.Tests.SslStreamStreamToStreamTest_Async.DoHandshake(SslStream clientSslStream, SslStream serverSslStream) in D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\SslStreamStreamToStreamTest.cs:line 391
     at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Authentication_Success() in D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\SslStreamStreamToStreamTest.cs:line 36
     at System.Net.Security.Tests.LoggingTest.<>c.<EventSource_EventsRaisedAsExpected>b__1_1() in D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\LoggingTest.cs:line 39
     at System.Diagnostics.Tracing.TestEventListener.RunWithCallback(Action`1 handler, Action body) in D:\j\workspace\windows_nt_re---37265eab\src\Common\tests\System\Diagnostics\Tracing\TestEventListener.cs:line 91
     at System.Net.Security.Tests.LoggingTest.<>c.<EventSource_EventsRaisedAsExpected>b__1_0() in D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\LoggingTest.cs:line 41
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at RemoteExecutorConsoleApp.Program.Main(String[] args) in D:\j\workspace\windows_nt_re---37265eab\src\Common\tests\System\Diagnostics\RemoteExecutorConsoleApp\RemoteExecutorConsoleApp.cs:line 49
  
  Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.) (The credentials supplied to the package were not recognized) ---> System.TimeoutException: VirtualNetwork: Timeout reading the next frame.
     at System.Net.Test.Common.VirtualNetwork.ReadFrame(Boolean server, Byte[]& buffer) in D:\j\workspace\windows_nt_re---37265eab\src\Common\tests\System\Net\VirtualNetwork\VirtualNetwork.cs:line 39
     at System.Net.Test.Common.VirtualNetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count) in D:\j\workspace\windows_nt_re---37265eab\src\Common\tests\System\Net\VirtualNetwork\VirtualNetworkStream.cs:line 119
     at System.Threading.Tasks.Task`1.InnerInvoke()
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Threading.Tasks.TaskToApm.End[TResult](IAsyncResult asyncResult) in D:\j\workspace\windows_nt_re---37265eab\src\Common\src\System\Threading\Tasks\TaskToApm.cs:line 115
     at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult) in D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\FixedSizeReader.cs:line 143
  --- End of stack trace from previous location where exception was thrown ---
     System.IO.Tests.File_Create_Tests.FileSystemWatcher_File_Create_SymLink [SKIP]
        Condition(s) not met: \"CanCreateSymbolicLinks\"
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result) in D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslState.cs:line 731
     at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
     --- End of inner exception stack trace ---
     at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
     at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
     at System.Net.Security.Tests.SslStreamStreamToStreamTest_Async.DoHandshake(SslStream clientSslStream, SslStream serverSslStream) in D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\SslStreamStreamToStreamTest.cs:line 391
     at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Authentication_Success() in D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\SslStreamStreamToStreamTest.cs:line 36
     at System.Net.Security.Tests.LoggingTest.<>c.<EventSource_EventsRaisedAsExpected>b__1_1() in D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\LoggingTest.cs:line 39
     at System.Diagnostics.Tracing.TestEventListener.RunWithCallback(Action`1 handler, Action body) in D:\j\workspace\windows_nt_re---37265eab\src\Common\tests\System\Diagnostics\Tracing\TestEventListener.cs:line 91
     at System.Net.Security.Tests.LoggingTest.<>c.<EventSource_EventsRaisedAsExpected>b__1_0() in D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\LoggingTest.cs:line 41
     --- End of inner exception stack trace ---
     at RemoteExecutorConsoleApp.Program.Main(String[] args) in D:\j\workspace\windows_nt_re---37265eab\src\Common\tests\System\Diagnostics\RemoteExecutorConsoleApp\RemoteExecutorConsoleApp.cs:line 65
```

**Comment by karelz** [comment]
Is it a new test case by a chance?

**Comment by stephentoub** [comment]
No

**Comment by karelz** [comment]
cc @Priya91 @ianhays @steveharter

**Comment by karelz** [comment]
@stephentoub thanks, I was more interested in recent changes to DiagnosticSource in Networking ... if it is unrelated, let's keep it here.

**Comment by stephentoub** [comment]
It's unrelated. This is enabling an EventSource and then running some other tests while it's enabled.

**Comment by ianhays** [comment]
This is another https://github.com/dotnet/corefx/issues/16516 failure. I'll disable it and add it to the list.
