### ISSUE TITLE
DSAImportExport.ExportAutoKey test failed in CI on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#17104]
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/4626/consoleText
```
System.Security.Cryptography.Dsa.Tests.DSAImportExport.ExportAutoKey [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : An internal consistency check failed
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Security.Cryptography.Cng\src\System\Security\Cryptography\CngKey.Create.cs(55,0): at System.Security.Cryptography.CngKey.Create(CngAlgorithm algorithm, String keyName, CngKeyCreationParameters creationParameters)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Security.Cryptography.Cng\src\Internal\Cryptography\CngAlgorithmCore.cs(68,0): at Internal.Cryptography.CngAlgorithmCore.GetOrGenerateKey(Int32 keySize, CngAlgorithm algorithm)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Security.Cryptography.Cng\src\System\Security\Cryptography\DSACng.Key.cs(25,0): at System.Security.Cryptography.DSACng.get_Key()
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Security.Cryptography.Cng\src\System\Security\Cryptography\DSACng.ImportExport.cs(16,0): at System.Security.Cryptography.DSACng.ExportKeyBlob(Boolean includePrivateParameters)
           D:\j\workspace\windows_nt_de---4526f5ff\src\Common\src\System\Security\Cryptography\DSACng.ImportExport.cs(232,0): at System.Security.Cryptography.DSACng.ExportParameters(Boolean includePrivateParameters)
           D:\j\workspace\windows_nt_de---4526f5ff\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\DSA\DSAImportExport.cs(26,0): at System.Security.Cryptography.Dsa.Tests.DSAImportExport.ExportAutoKey()
```

**Comment by bartonjs** [comment]
Since the error reported is not exactly a happy state (NTE_INTERNAL_ERROR) and this hasn't reproduced leads me to believe that investigating it isn't going to be very fruitful.  CNG seems to have just been having a bad day.

If it happens again, then a new evaluation can be made.
