### ISSUE TITLE
System.UnauthorizedAccessException in System.Tests.EnvironmentTests.OSVersion_ValidVersion

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#17112]
Test failure in System.Tests.EnvironmentTests.

https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/4636/consoleFull#-8467542952d31e50d-1517-49fc-92b3-2ca637122019

On Windows x86

```
System.Tests.EnvironmentTests.OSVersion_ValidVersion [FAIL]
11:58:43         FileCleanupTestBase failed to create C:\Users\someuser\AppData\Local\Temp\EnvironmentTests_oxkp0ze3.kca due to System.UnauthorizedAccessException: Access to the path 'C:\Users\someuser\AppData\Local\Temp\EnvironmentTests_oxkp0ze3.kca' is denied.
11:58:43            at System.IO.Win32FileSystem.CreateDirectory(String fullPath) in D:\j\workspace\windows_nt_de---4526f5ff\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 169
11:58:43            at System.IO.Directory.CreateDirectory(String path) in D:\j\workspace\windows_nt_de---4526f5ff\src\System.IO.FileSystem\src\System\IO\Directory.cs:line 51
11:58:43            at System.IO.FileCleanupTestBase..ctor() in D:\j\workspace\windows_nt_de---4526f5ff\src\Common\tests\System\IO\FileCleanupTestBase.cs:line 24
11:58:43         Expected: True
11:58:43         Actual:   False
11:58:43         Stack Trace:
11:58:43            D:\j\workspace\windows_nt_de---4526f5ff\src\Common\tests\System\IO\FileCleanupTestBase.cs(28,0): at System.IO.FileCleanupTestBase..ctor()
11:58:43               at System.Diagnostics.RemoteExecutorTestBase..ctor()
11:58:43               at System.Tests.EnvironmentTests..ctor()
11:58:43               at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
11:58:46   Finished:    System.Runtime.Extensions.Tests
```

**Comment by karelz** [comment]
@AlexGhiondea why is it up-for-grabs? It does not seem very actionable for community ...

**Comment by danmosemsft** [comment]
fixed by https://github.com/dotnet/corefx/pull/17610 i hope.
