### ISSUE TITLE
Integrated Auth On SqlClient is completely broken

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#17139]
The integrated auth in SqlClient is completely broken. 

Opening this issue to track the progress.

**Comment by saurabh500** [comment]
cc @geleems

**Comment by stephentoub** [comment]
On all OSes?

**Comment by saurabh500** [comment]
I made managed SNI the default network impl on Windows. 
So now its broken on all platforms.

**Comment by saurabh500** [comment]
@geleems is investigating. I am assuming this has to do with changes to the NegotiateStreamPal. We need to beef up the integrated auth tests with the test server.

**Comment by rynowak** [comment]
@saurabh500 

Could a failure like this be related?

Connection string:
```
Server=(localdb)\\MSSQLLocalDB;Database=MusicStore;Trusted_Connection=True;MultipleActiveResultSets=true;Connect Timeout=30;
```

Exception:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 25 - Connection string is not valid)) ---> System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 25 - Connection string is not valid) ---> System.Net.Sockets.SocketException: No such host is known
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6) in E:\A\_work\118\s\corefx\src\System.Net.NameResolution\src\System\Net\DNS.cs:line 81
   at System.Net.Dns.ResolveCallback(Object context) in E:\A\_work\118\s\corefx\src\System.Net.NameResolution\src\System\Net\DNS.cs:line 290
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\244\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionServicesCommon.cs:line 130
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) in E:\A\_work\118\s\corefx\src\System.Net.NameResolution\src\System\Net\DNS.cs:line 423
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult) in E:\A\_work\118\s\corefx\src\System.Net.NameResolution\src\System\Net\DNS.cs:line 582
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult) in E:\A\_work\118\s\corefx\src\System.Net.NameResolution\src\System\Net\DNS.cs:line 632
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) in E:\A\_work\244\s\src\mscorlib\src\System\Threading\Tasks\FutureFactory.cs:line 530
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\244\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionServicesCommon.cs:line 130
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\A\_work\244\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 150
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() in E:\A\_work\244\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 339
   at System.Net.Sockets.UdpClient.BeginSend(Byte[] datagram, Int32 bytes, String hostname, Int32 port, AsyncCallback requestCallback, Object state) in E:\A\_work\118\s\corefx\src\System.Net.Sockets\src\System\Net\Sockets\UDPClient.cs:line 314
   at System.Net.Sockets.UdpClient.<>c.<SendAsync>b__55_0(Tuple`2 targetPackedArguments, Int32 targetBytes, Int32 targetPort, AsyncCallback callback, Object state) in E:\A\_work\118\s\corefx\src\System.Net.Sockets\src\System\Net\Sockets\UDPClient.cs:line 640
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions) in E:\A\_work\244\s\src\mscorlib\src\System\Threading\Tasks\FutureFactory.cs:line 1220
   at System.Threading.Tasks.TaskFactory`1.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state) in E:\A\_work\244\s\src\mscorlib\src\System\Threading\Tasks\FutureFactory.cs:line 1123
   at System.Net.Sockets.UdpClient.SendAsync(Byte[] datagram, Int32 bytes, String hostname, Int32 port) in E:\A\_work\118\s\corefx\src\System.Net.Sockets\src\System\Net\Sockets\UDPClient.cs:line 633
   at System.Data.SqlClient.SNI.SNIProxy.SendUDPRequest(String browserHostname, Int32 port, Byte[] requestPacket) in E:\A\_work\118\s\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SNI\SNIProxy.cs:line 570
   at System.Data.SqlClient.SNI.SNIProxy.SendInstanceInfoRequest(String browserHostName, String instanceName) in E:\A\_work\118\s\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SNI\SNIProxy.cs:line 479
   at System.Data.SqlClient.SNI.SNIProxy.GetPortByInstanceName(String browserHostname, String instanceName) in E:\A\_work\118\s\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SNI\SNIProxy.cs:line 502
   at System.Data.SqlClient.SNI.SNIProxy.CreateTcpHandle(String fullServerName, Int64 timerExpire, Object callbackObject, Boolean parallel, Byte[]& spnBuffer, Boolean isIntegratedSecurity) in E:\A\_work\118\s\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SNI\SNIProxy.cs:line 425
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling) in E:\A\_work\118\s\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlInternalConnectionTds.cs:line 373
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions) in E:\A\_work\118\s\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlConnectionFactory.cs:line 134
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions) in E:\A\_work\118\s\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionFactory.cs:line 114
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection) in E:\A\_work\118\s\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs:line 476
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection) in E:\A\_work\118\s\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs:line 1187
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection) in E:\A\_work\118\s\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs:line 792
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen() in E:\A\_work\118\s\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs:line 651
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\244\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionServicesCommon.cs:line 130
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\A\_work\244\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 150
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\244\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionServicesCommon.cs:line 130
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\A\_work\244\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 150
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass12_0.<<ExistsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\244\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionServicesCommon.cs:line 130
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass12_0.<<ExistsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\244\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionServicesCommon.cs:line 130
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\A\_work\244\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 150
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__6`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\244\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionServicesCommon.cs:line 130
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\A\_work\244\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 150
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.<EnsureCreatedAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\244\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionServicesCommon.cs:line 130
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\A\_work\244\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 150
   at MusicStore.Models.SampleData.<InitializeMusicStoreDatabaseAsync>d__3.MoveNext() in D:\k\JitBench\src\MusicStore\Models\SampleData.cs:line 26
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) in E:\A\_work\244\s\src\mscorlib\src\System\Threading\Tasks\Task.cs:line 1984
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) in E:\A\_work\244\s\src\mscorlib\src\System\Threading\Tasks\Task.cs:line 2805
   at MusicStore.Startup.Configure(IApplicationBuilder app) in D:\k\JitBench\src\MusicStore\Startup.cs:line 213
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\244\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionServicesCommon.cs:line 130
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at MusicStore.Program.Main(String[] args) in D:\k\JitBench\src\MusicStore\Program.cs:line 53
```

**Comment by saurabh500** [comment]
@rynowak What is the SqlClient build that you are trying this on? 
Looks like you are connecting to LocalDB using Managed SNI. This is not supported in Managed SNI.
Issue here : https://github.com/dotnet/corefx/issues/17166 
Workaround: set the app context flag to get LocalDB features.  AppContext.SetSwitch(“System.Data.SqlClient.UseLegacyNetworkingOnWindows”, true);

**Comment by lt72** [comment]
@davmason FYI

**Comment by davmason** [comment]
@saurabh500 I am trying on NETStandard.Library 2.0.0-beta-25115-01. We are using the nightly builds of the standard library so it changes every day. It was working with this exact setup last week, I don't know the build number for the last working build.

**Comment by saurabh500** [comment]
@davmason Localdb connectivity is expected to be broken right now. If your tests only use LocalDB, you can incorporate the work around I have mentioned above. 
I am looking into enabling LocalDB with Sqlclient's current networking interface.

**Comment by davmason** [comment]
@saurabh500 I tried the workaround and it still failed. Is there anywhere in particular that the set context call needs to go? I put it in Main before any calls to asp.net.

**Comment by saurabh500** [comment]
I tried this in a test case. 
`AppContext.SetSwitch("System.Data.SqlClient.UseLegacyNetworkingOnWindows", true);` should be done before any single SqlConnection Open.
On SqlConnection.Open, the appcontext value is cached for the process. Setting this AppContext value after any single connection would result in not honoring the appcontext.

I am using this code to verify 

```
[Fact]
        public void IntegratedauthConnectionTest()
        {
            AppContext.SetSwitch("System.Data.SqlClient.UseLegacyNetworkingOnWindows", true);

            Exception e = null;

            
            SqlConnectionStringBuilder builder = new SqlConnectionStringBuilder();
            builder.DataSource = @"(localdb)\MSSQLLocalDB";
            builder.ConnectTimeout = 2;
            builder.IntegratedSecurity = true;

            try
            {
                SqlConnection connection = new SqlConnection(builder.ConnectionString);
                connection.Open();
            }
            catch (Exception ce)
            {
                e = ce;
            }
            
            Assert.Null(e);
        }
```

**Comment by davmason** [comment]
@saurabh500 I figured it out, the workaround does work for me. I had messed with the connection string trying to figure out why it didn't work and forgot to change it back. Thanks for your help.

**Comment by geleems** [comment]
This issue was resolve by fix https://github.com/dotnet/corefx/pull/17197#event-1003342960
I tested both Windows and Unix environment, and it all worked after this fix.
