### ISSUE TITLE
SecurityNegotiationException not found in Core

### ISSUE THREAD

**Issue by linflux** [dotnet/corefx#17211]
Hi,
I have an issue with a WCF Soap Service that throws me an SecurityNegotiationException:

`
System.ServiceModel.Security.SecurityNegotiationException: Could not establish trust relationship for the SSL/TLS secure channel with authority 'foobar.com'. 
---> System.Net.Http.HttpRequestException: An error occurred while sending the request. 
---> System.Net.Http.CurlException: Peer certificate cannot be authenticated with given CA certificates
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference 1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.ServiceModelHttpMessageHandler.<SendAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable 1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.HttpChannelFactory1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext()
`

So I tried to catch then but this class cannot be found on .NET Core.
I had to catch [System.ServiceModel.CommunicationException](https://msdn.microsoft.com/pt-br/library/system.servicemodel.security.securitynegotiationexception(v=vs.110).aspx) instead. 

Is this right?

PS: Sorry if already has an issue with this, i try to search but with no success.

**Comment by davidsh** [comment]
System.ServiceModel is part of WCF.  You should enter your issues here:

https://github.com/dotnet/wcf

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/wcf #1811](https://github.com/dotnet/wcf/issues/1811) via [**ZenHub**](https://www.zenhub.com/)
