### ISSUE TITLE
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException on ubuntu 16.4

### ISSUE THREAD

**Issue by asperheim** [dotnet/corefx#17434]
I am getting the System.Net.Internals.SocketExceptionFactory exception while using a console app with **AMQP.Net Lite**. It can send houndreds or sometimes thousands of messages to **Azure Servicebus** instance. But it allways fails after a while with this exception:

```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Unknown error -1
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__14_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amqp.TcpTransport.<ConnectAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amqp.TcpTransport.Connect(Connection connection, Address address, Boolean noVerification)
   at Amqp.Connection.Connect(SaslProfile saslProfile, Open open)
   at Amqp.Connection..ctor(Address address, SaslProfile saslProfile, Open open, OnOpened onOpened)
   at TheMOON.Extensions.ServiceBus.ServiceBusMessageSenderClient.<SendMessageAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at TheMOON.Extensions.ServiceBus.ServiceBusMessageSenderClient.<SendMessageAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TheMoon.EcomDbSyncer.Services.Handlers.ChangeHandlerCommons.<SendToQueue>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TheMoon.EcomDbSyncer.Services.Handlers.ProductChangeHandler.<Handle>d__7.MoveNext()

```

The system is a **Ubuntu 16.4** instance running in **Azure**.

```
Microsoft .NET Core Shared Framework Host

  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86
```

I  have not yet tried to feed the queueclient with the IP instead of the servicebus instance DNS name. Disregarding the certificate trouble this will induce, i am assuming this would be a workaround.

**Comment by stephentoub** [comment]
@asperheim, would it be possible for you to catch the SocketException and share some more of the properties from it, e.g. HResult?  The "Unknown error -1" suggests that we're getting back from gethostbyname something unexpected, and I believe that should be in the HResult field.

**Comment by asperheim** [comment]
@stephentoub of course, will get back to you when this is done.

**Comment by danmosemsft** [comment]
@asperheim did you get a chance to look?

**Comment by asperheim** [comment]
I have not yet put my changes into production. Will get a chance to do that right after easter.

**Comment by karelz** [comment]
Closing for now. Feel free to reopen if/when you have more details. Thank you!

**Comment by EncoderPtd** [comment]
I've met the same trouble these days i think.
We have a console app which deal with so many TCP connections runs on about 5 `CentOS7.2` machines. And three of them run very well. But the other two always give me this:

> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Resource temporarily unavailable
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__14_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at NSNetAccessCommon.TcpAccess.GetResponse(Uri uri, String reDir& reDir, Boolean autoRedir, Encoding enc, Stream post, Dictionary`2 headers)

I've checked `lsof`, no `TIME_WAIT` or `CLOSE_WAIT`.
I've tried set `ulimit`, not work.
I've checked `free -m`, it shows there still enough virtual memory and physical memory.

Is it the problem of `obstruction` of the serial port on linux? I'm not sure:)

**Comment by stephentoub** [comment]
Hmm.  "Resource temporarily unavailable" suggests that the getaddrinfo call failed with EAGAIN.  I don't see any mention of that as a possible error in the man page.  @tmds, are you aware of any reasons why on CentOS getaddrinfo would return EAGAIN, and what we're supposed to do in such cases?  Retry after some period of time?  Simply fail as we are today and leave it up to the caller?

**Comment by stephentoub** [comment]
Ah, actually, I do see this in the man page:
```
EAI_AGAIN 
The name server returned a temporary failure indication. Try again later. 
```
Still unclear what if anything we can do about this.  Not sure how much later "later" is... are we talking immediately?  If not, then I don't think we can really address this in the .NET layer, and it would be up to the app code to decide to retry.

**Comment by tmds** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms738519(v=vs.85).aspx says `EAI_AGAIN` is equivalent to `WSATRY_AGAIN`, which gets mapped to SocketError.TryAgain on Windows. And on Unix it does the same mapping: https://github.com/dotnet/corefx/blob/bfac45af5dddcbd70b6935fcf92b4b8755f3cd1c/src/System.Net.NameResolution/src/System/Net/NameResolutionPal.Unix.cs#L42-L43.

This is DNS resolution timeout and it is the app that should handle this.

**Comment by stephentoub** [comment]
> This is DNS resolution timeout and it is the app that should handle this.

Ok, we'll leave it as is.

**Comment by EncoderPtd** [comment]
Yes, thanks a lot. However, after saw the information you provided, i find that it was the firewall restriction and dns config mistake. Embarrasing `-.-|| ` I shouldn't be that certain about the basic configs of the system.

**Comment by ljani** [comment]
I got the `Resource temporarily unavailable` error as well:

```
2018-02-22T08:17:39.4576610Z [xUnit.net 00:00:02.2493444]       System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Resource temporarily unavailable
2018-02-22T08:17:39.4613190Z [xUnit.net 00:00:02.2528838]       Stack Trace:
2018-02-22T08:17:39.4642540Z [xUnit.net 00:00:02.2560454]            at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
2018-02-22T08:17:39.4660470Z [xUnit.net 00:00:02.2563287]            at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
2018-02-22T08:17:39.4676390Z [xUnit.net 00:00:02.2565183]            at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
2018-02-22T08:17:39.4694860Z [xUnit.net 00:00:02.2567027]            at Npgsql.NpgsqlConnector.<RawOpen>d__146.MoveNext()
2018-02-22T08:17:39.4709780Z [xUnit.net 00:00:02.2585948]         --- End of stack trace from previous location where exception was thrown ---
```

However, my problem was that the TFS build agent did not expand the variables I specified in the web ui as I thought. So, in the end the connection string was something like `Server=$(POSTGRES_HOST)`, literally including a dollar sign and parentheses.

**Comment by danmosemsft** [comment]
Happening in CI

https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/3c8c2333347c91d296ac4ddd26985888520b8914/workItem/System.Net.NameResolution.Functional.Tests/analysis/xunit/System.Net.NameResolution.Tests.GetHostByNameTest~2FDnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName

https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/3c8c2333347c91d296ac4ddd26985888520b8914/workItem/System.Net.NameResolution.Functional.Tests

**Comment by karelz** [comment]
@rmkerr @wfurt can you please check frequency of these new failures and file a new bug if necessary? Thanks!

**Comment by saixiaohui** [comment]
I am running Azure Kubernetes container (VM ScaleSet with Public IP address) and it will create lots of connections between container and Azure IoT hub. I am getting following error message when trying to open connection to IoT Hub.

```
Microsoft.Azure.IoT.Simulation.Common.Exceptions.WrapperSimulationException: Error connecting device car.000143949 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Resource temporarily unavailable

 at System.Net.Dns.InternalGetHostByName(String hostName)

 at System.Net.Dns.ResolveCallback(Object context)

--- End of stack trace from previous location where exception was thrown ---

 at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)

 at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)

 at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)

 at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

--- End of stack trace from previous location where exception was thrown ---

 at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken)

 at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)

 at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)

 at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

 at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)

 at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass32_0.<<OpenAsyncInternal>b__0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

 at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)

 at Microsoft.Azure.IoT.Simulation.DeviceClients.IoTHubSimulatedDeviceClient.ConnectAsync(CancellationToken cancellationToken) in /src/DeviceClients/IoTHub/IoTHubSimulatedDevice.cs:line 105

 --- End of inner exception stack trace ---

 at Microsoft.Azure.IoT.Simulation.DeviceClients.IoTHubSimulatedDeviceClient.ConnectAsync(CancellationToken cancellationToken) in /src/DeviceClients/IoTHub/IoTHubSimulatedDevice.cs:line 137

 at Microsoft.Azure.IoT.Simulation.Runner.DeviceConnection.DeviceConnectionActor.ConnectAsync(CancellationToken cancellationToken) in /src/Runner/DeviceConnection/DeviceConnectionActor.cs:line 123
```
