### ISSUE TITLE
NullReferenceException from DiagnosticListener in HttpClient

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#17492]
I get the following when I register an EventListener and use HttpClient:
```
System.NullReferenceException: Object reference not set to an instance of an object.
     at System.Diagnostics.DiagnosticListener.<>c__DisplayClass2_0.<Subscribe>b__0(String name, Object arg1, Object arg2) in /home/stoub/source/corefx/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticListener.cs:line 60
     at System.Diagnostics.DiagnosticListener.IsEnabled(String name, Object arg1, Object arg2) in /home/stoub/source/corefx/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticListener.cs:line 211
     at System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext() in /home/stoub/source/corefx/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs:line 45
```
cc: @vancem, @lmolkova

**Comment by lmolkova** [comment]
I'll have a look

**Comment by vancem** [comment]
public IDisposable Subscribe(IObserver<KeyValuePair<string, object>> observer)
        {
            return SubscribeInternal(observer, null, **null**);
        }

This is what is causing it.   we are passing null as 'isenabled' and call the delegate here 

        public virtual IDisposable Subscribe(IObserver<KeyValuePair<string, object>> observer, Predicate<string> isEnabled)
        {
            return SubscribeInternal(observer, isEnabled, (name, arg1, arg2) => **isEnabled(name)**);
        }

Which of course null refs.   We should check for null in the code above

**Comment by lmolkova** [comment]
#17502 should fix the problem

**Comment by vancem** [comment]
#17502 was merged.   Reopen if the problem continues
