### ISSUE TITLE
Version_MatchesFixedVersion test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#17576]
```
     System.Tests.EnvironmentTests.Version_MatchesFixedVersion [FAIL]
        FileCleanupTestBase failed to create C:\Users\someuser\AppData\Local\Temp\EnvironmentTests_k3c3hzza.ga3 due to System.UnauthorizedAccessException: Access to the path 'C:\Users\someuser\AppData\Local\Temp\EnvironmentTests_k3c3hzza.ga3' is denied.
           at System.IO.Win32FileSystem.CreateDirectory(String fullPath) in D:\j\workspace\windows_nt_de---4526f5ff\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 169
           at System.IO.Directory.CreateDirectory(String path) in D:\j\workspace\windows_nt_de---4526f5ff\src\System.IO.FileSystem\src\System\IO\Directory.cs:line 51
           at System.IO.FileCleanupTestBase..ctor() in D:\j\workspace\windows_nt_de---4526f5ff\src\Common\tests\System\IO\FileCleanupTestBase.cs:line 24
        Expected: True
        Actual:   False
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\Common\tests\System\IO\FileCleanupTestBase.cs(28,0): at System.IO.FileCleanupTestBase..ctor()
              at System.Diagnostics.RemoteExecutorTestBase..ctor()
              at System.Tests.EnvironmentTests..ctor()
              at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
```

**Comment by danmosemsft** [comment]
Well my logging gave us more information but I'm not sure it helps us. Surely `k3c3hzza.ga` wasn't independently generated and used concurrently.

**Comment by danmosemsft** [comment]
Perhaps we should do retries with either the same name or a different one.

**Comment by danmosemsft** [comment]
@Jiayili1 could you please change src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 169 so tht if there's an exception creating the directory, it tries again with a new name.

**Comment by Jiayili1** [comment]
@danmosemsft I don't known how to change the code, do you mean we need to call this method CreateDirectory() with a new parameter if there is an exception?

**Comment by danmosemsft** [comment]
My bad, I pointed to the wrong place so you coudn't make sense of this. :) I did a PR
