### ISSUE TITLE
Unix: System.IO.Pipes; NamePipeServerStream throwing exception when reading TransmissionMode Property when not connected

### ISSUE THREAD

**Issue by bpschoch** [dotnet/corefx#1764]
```C#
 [Fact]
        public static void ServerNotConnectedThrows()
        {
            using (NamedPipeServerStream server = new NamedPipeServerStream("tempnotconnected", PipeDirection.InOut, 1))
            {
                // doesn't throw execeptions
                PipeTransmissionMode transmitMode = server.TransmissionMode;
                Assert.Throws<ArgumentOutOfRangeException>(() => server.ReadMode = (PipeTransmissionMode)999);

                if (Interop.IsWindows)
                {
                    int inbuffersize = server.InBufferSize;
                    int outbuffersize = server.OutBufferSize;
                }
                else
                {
                    Assert.Throws<PlatformNotSupportedException>(() => server.InBufferSize);
                    Assert.Throws<PlatformNotSupportedException>(() => server.OutBufferSize);
                }
                PipeTransmissionMode readMode = server.ReadMode;
                server.ReadMode = PipeTransmissionMode.Byte;

                Assert.Throws<InvalidOperationException>(() => server.WriteByte(5));
                Assert.Throws<InvalidOperationException>(() => server.ReadByte());
                Assert.Throws<InvalidOperationException>(() => server.Disconnect());    // disconnect when not connected 
                Assert.Throws<InvalidOperationException>(() => server.IsMessageComplete);
            }
        }
```

13:30:03 �[31m   System.IO.Pipes.Tests.NamedPipesThrowsTests.ServerNotConnectedThrows [FAIL]
13:30:03 �[37m      System.InvalidOperationException : Pipe handle has not been set.  Did your PipeStream implementation call InitializeHandle?
13:30:03 �[30m      Stack Trace:
13:30:03 �[37m            at System.IO.Pipes.PipeStream.CheckPipePropertyOperations()
13:30:03             at System.IO.Pipes.PipeStream.get_TransmissionMode()
13:30:03             at System.IO.Pipes.Tests.NamedPipesThrowsTests.ServerNotConnectedThrows()

**Comment by stephentoub** [comment]
Fixed by #1884
