### ISSUE TITLE
System.IO.Compression.ZipFile.Tests failing in microbuild of dev/metadata branch

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#1787]
Disabling these tests in dev/metadata branch until these issues are resolved.

```
System.IO.Compression.Test.ZipTest.CreateFromDirectoryNormal
System.IO.Compression.Test.ZipTest.CreateEntryFromFileTest
System.IO.Compression.Test.ZipTest.UpdateReadTwice
System.IO.Compression.Test.ZipTest.UpdateAddFile
```

Stack trace is the same for all failures:
```
               System.IO.Compression.ZLibException : The underlying compression routine could not be loaded correctly.
               ---- System.DllNotFoundException : Unable to load DLL 'clrcompression.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
               Stack Trace:
                     at System.IO.Compression.DeflaterZLib.DeflateInit(CompressionLevel compressionLevel, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
                     at System.IO.Compression.DeflaterZLib..ctor(CompressionLevel compressionLevel)
                     at System.IO.Compression.DeflateStream.CreateDeflater(Nullable`1 compressionLevel)
                     at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen)
                     at System.IO.Compression.ZipArchiveEntry.GetDataCompressor(Stream backingStream, Boolean leaveBackingStreamOpen, EventHandler onClose)
                     at System.IO.Compression.ZipArchiveEntry.OpenInWriteMode()
                     at System.IO.Compression.ZipArchiveEntry.Open()
```

**Comment by joshfree** [comment]
@FiveTimesTheFun could you take a look please?

**Comment by ianhays** [comment]
This issue appears to be stale. The first two tests in the OP no longer exist, and the latter two are currently enabled in dev/metadata as well as master. @tmat is this still relevant? Closing for now.
