### ISSUE TITLE
Can't join IPv6 multicast group on Linux

### ISSUE THREAD

**Issue by PawelGerr** [dotnet/corefx#17870]
I'm getting an error when trying to join a multicast group with an IPv6 address on ubuntu 16.04.
I get no errors when using IPv4 address or when executing the same code on windows 7 and 10.

The issue https://github.com/dotnet/corefx/issues/14684 is similar but not the same because I have no problems getting udp multicast packages using IPv4.

dotnet version: 1.0.1
OS: ubuntu 16.04 x64

Error occurs for all NICs
```
System.Net.Sockets.SocketException: Invalid argument
  at System.Net.Sockets.Socket.SetIPv6MulticastOption(SocketOptionName optionName, IPv6MulticastOption MR)
  at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Object optionValue)
```

Repro: https://github.com/PawelGerr/DotnetCoreUdpMulticast
Executable: https://github.com/PawelGerr/DotnetCoreUdpMulticast/tree/master/published/ubuntu.16.04-x64

.csproj-File
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  <RuntimeIdentifiers>win7-x64;win10-x64;ubuntu.16.04-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Net.NetworkInformation" Version="4.3.0" />
  </ItemGroup>

</Project>
```

Program.cs
```c#
using System;
using System.Linq;
using System.Net;
using System.Net.NetworkInformation;
using System.Net.Sockets;
using System.Text;
using System.Threading;

namespace UdpMulticastTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var socket = new Socket(AddressFamily.InterNetworkV6, SocketType.Dgram, ProtocolType.Udp);
            socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, 1);
            socket.Bind(new IPEndPoint(IPAddress.IPv6Any, 2222));

            foreach (var nic in NetworkInterface.GetAllNetworkInterfaces())
            {
                try
                {
                    var props = nic.GetIPProperties().GetIPv6Properties();
                    socket.SetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.AddMembership, new IPv6MulticastOption(IPAddress.Parse("ff08::ef00:de"), props.Index));
                    Console.WriteLine("Joined multicast group: NIC = " + nic.Name);
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Exception while joining multicast group: NIC = " + nic.Name + "; Exception: " + ex);
                }
            }

            Console.WriteLine("Press ENTER to exit.");
            Console.ReadLine();
        }
    }
}
```

**Comment by stephentoub** [comment]
@PawelGerr, have you tried just writing a little C program that tries to set the equivalent option and running it on the same machine?  Does that work?

**Comment by PawelGerr** [comment]
No, I haven't. C and C++ are not my strengths.
The code in my first post has been executed on 2 totally different machines and the result has been the same.

**Comment by stephentoub** [comment]
Ok, thanks, @PawelGerr.  This does look like a bug in the .NET lib.
