### ISSUE TITLE
NullReferenceException thrown getting InputStream from HttpListener

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#17980]
```cs
class Program
{
    static async Task Test()
    {
        string uri = "http://localhost:9200/";
        HttpListener listener = new HttpListener();
        listener.Prefixes.Add(uri);
        listener.Start();

        using (ClientWebSocket client = new ClientWebSocket())
        {
            UriBuilder uriBuilder = new UriBuilder(uri) { Scheme = "ws" };
            Task<HttpListenerContext> serverContextTask = listener.GetContextAsync();

            Task clientConnectTask = client.ConnectAsync(uriBuilder.Uri, CancellationToken.None);

            HttpListenerContext listenerContext = await serverContextTask;
            HttpListenerWebSocketContext wsContext = await listenerContext.AcceptWebSocketAsync(null);
            await clientConnectTask;

            HttpListenerRequest request = listenerContext.Request;
            Stream stream = request.InputStream;
        }

        listener.Stop();
    }

    static void Main()
    {
        Test().Wait();
    }
}
```
Stack trace:
```
     System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
            at System.Net.HttpListenerRequest.get_ContentLength64()
            at System.Net.HttpListenerRequest.get_HasEntityBody()
            at System.Net.HttpListenerRequest.get_InputStream()
```

I think this is a pretty serious bug - it makes reading any input from HttpListener's tream broken. Netfx works, obviously.

I've got a fix for this, and adding tests (as per #13618)

The reference source is:
```
 if (HttpWebRequest.ChunkedHeader.Equals(GetKnownHeader(HttpRequestHeader.TransferEncoding)
```

However, the .NET core is
```
 if (GetKnownHeader(HttpRequestHeader.TransferEncoding).Equals(HttpWebRequest.ChunkedHeader))
```

This is *not* the same!

**Comment by karelz** [comment]
@Priya91 @davidsh @CIPop can you please comment on the bug? If @hughbe has a fix, would we take it?

**Comment by hughbe** [comment]
I've sent in a fix and tests for HttpListenerResponseStream and HttpListenerRequestStream. Without the fix, HttpListenerRequestStream is entirely unusable - every test fails with a NRE in the product code.

**Comment by karelz** [comment]
Sounds like a great catch, thank you @hughbe. Truly appreciate your help here!
I let area experts to comment on technical direction, etc.
