### ISSUE TITLE
Desktop: Tests under "System.ComponentModel.DataAnnotations.Tests" failed with "Xunit.Sdk.AllException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18145]
Failed tests:
System.ComponentModel.DataAnnotations.Tests.PhoneAttributeTests.Validate_Valid
System.ComponentModel.DataAnnotations.Tests.MaxLengthAttributeTests.Validate_Invalid
System.ComponentModel.DataAnnotations.Tests.MaxLengthAttributeTests.Validate_Valid
System.ComponentModel.DataAnnotations.Tests.MinLengthAttributeTests.Validate_Valid
System.ComponentModel.DataAnnotations.Tests.MinLengthAttributeTests.Validate_Invalid
System.ComponentModel.DataAnnotations.Tests.RangeAttributeTests.Validate_Invalid 

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/13/testReport/System.ComponentModel.DataAnnotations.Tests/PhoneAttributeTests/Validate_Valid/

Message:
~~~
Assert.All() Failure: 6 out of 19 items in the collection did not pass.\r\n[18]: System.ComponentModel.DataAnnotations.ValidationException: The Object field is not a valid phone number.\r\n at System.ComponentModel.DataAnnotations.ValidationAttribute.Validate(Object value, ValidationContext validationContext)\r\n at System.ComponentModel.DataAnnotations.Tests.ValidationAttributeTestBase.Validate(ValidationAttribute attribute, Object value, ValidationContext validationContext, Boolean isValid) in D:\\j\\workspace\\outerloop_net---903ddde6\\src\\System.ComponentModel.Annotations\\tests\\ValidationAttributeTestBase.cs:line 35\r\n at System.ComponentModel.DataAnnotations.Tests.ValidationAttributeTestBase.<Validate_Valid>b__6_0(TestCase test) in D:\\j\\workspace\\outerloop_net---903ddde6\\src\\System.ComponentModel.Annotations\\tests\\ValidationAttributeTestBase.cs:line 22\r\n at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\BuildAgent\\work\\cb37e9acf085d108\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 31\r\n[17]: System.ComponentModel.DataAnnotations.ValidationException: The Object field is not a valid phone number.\r\n at System.ComponentModel.DataAnnotations.ValidationAttribute.Validate(Object value, ValidationContext validationContext)\r\n at System.ComponentModel.DataAnnotations.Tests.ValidationAttributeTestBase.Validate(ValidationAttribute attribute, Object value, ValidationContext validationContext, Boolean isValid) in D:\\j\\workspace\\outerloop_net---903ddde6\\src\\System.ComponentModel.Annotations\\tests\\ValidationAttributeTestBase.cs:line 35\r\n at System.ComponentModel.DataAnnotations.Tests.ValidationAttributeTestBase.<Validate_Valid>b__6_0(TestCase test) in D:\\j\\workspace\\outerloop_net---903ddde6\\src\\System.ComponentModel.Annotations\\tests\\ValidationAttributeTestBase.cs:line 22\r\n at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\BuildAgent\\work\\cb37e9acf085d108\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 31\r\n[16]: System.ComponentModel.DataAnnotations.ValidationException: The Object field is not a valid phone number.\r\n at System.ComponentModel.DataAnnotations.ValidationAttribute.Validate(Object value, ValidationContext validationContext)\r\n at System.ComponentModel.DataAnnotations.Tests.ValidationAttributeTestBase.Validate(ValidationAttribute attribute, Object value, ValidationContext validationContext, Boolean isValid) in D:\\j\\workspace\\outerloop_net---903ddde6\\src\\System.ComponentModel.Annotations\\tests\\ValidationAttributeTestBase.cs:line 35\r\n at System.ComponentModel.DataAnnotations.Tests.ValidationAttributeTestBase.<Validate_Valid>b__6_0(TestCase test) in D:\\j\\workspace\\outerloop_net---903ddde6\\src\\System.ComponentModel.Annotations\\tests\\ValidationAttributeTestBase.cs:line 22\r\n at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\BuildAgent\\work\\cb37e9acf085d108\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 31\r\n[15]: System.ComponentModel.DataAnnotations.ValidationException: The Object field is not a valid phone number.\r\n at System.ComponentModel.DataAnnotations.ValidationAttribute.Validate(Object value, ValidationContext validationContext)\r\n at System.ComponentModel.DataAnnotations.Tests.ValidationAttributeTestBase.Validate(ValidationAttribute attribute, Object value, ValidationContext validationContext, Boolean isValid) in D:\\j\\workspace\\outerloop_net---903ddde6\\src\\System.ComponentModel.Annotations\\tests\\ValidationAttributeTestBase.cs:line 35\r\n at System.ComponentModel.DataAnnotations.Tests.ValidationAttributeTestBase.<Validate_Valid>b__6_0(TestCase test) in D:\\j\\workspace\\outerloop_net---903ddde6\\src\\System.ComponentModel.Annotations\\tests\\ValidationAttributeTestBase.cs:line 22\r\n at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\BuildAgent\\work\\cb37e9acf085d108\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 31\r\n[14]: System.ComponentModel.DataAnnotations.ValidationException: The Object field is not a valid phone number.\r\n at System.ComponentModel.DataAnnotations.ValidationAttribute.Validate(Object value, ValidationContext validationContext)\r\n at System.ComponentModel.DataAnnotations.Tests.ValidationAttributeTestBase.Validate(ValidationAttribute attribute, Object value, ValidationContext validationContext, Boolean isValid) in D:\\j\\workspace\\outerloop_net---903ddde6\\src\\System.ComponentModel.Annotations\\tests\\ValidationAttributeTestBase.cs:line 35\r\n at System.ComponentModel.DataAnnotations.Tests.ValidationAttributeTestBase.<Validate_Valid>b__6_0(TestCase test) in D:\\j\\workspace\\outerloop_net---903ddde6\\src\\System.ComponentModel.Annotations\\tests\\ValidationAttributeTestBase.cs:line 22\r\n at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\BuildAgent\\work\\cb37e9acf085d108\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 31\r\n[13]: System.ComponentModel.DataAnnotations.ValidationException: The Object field is not a valid phone number.\r\n at System.ComponentModel.DataAnnotations.ValidationAttribute.Validate(Object value, ValidationContext validationContext)\r\n at System.ComponentModel.DataAnnotations.Tests.ValidationAttributeTestBase.Validate(ValidationAttribute attribute, Object value, ValidationContext validationContext, Boolean isValid) in D:\\j\\workspace\\outerloop_net---903ddde6\\src\\System.ComponentModel.Annotations\\tests\\ValidationAttributeTestBase.cs:line 35\r\n at System.ComponentModel.DataAnnotations.Tests.ValidationAttributeTestBase.<Validate_Valid>b__6_0(TestCase test) in D:\\j\\workspace\\outerloop_net---903ddde6\\src\\System.ComponentModel.Annotations\\tests\\ValidationAttributeTestBase.cs:line 22\r\n at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\BuildAgent\\work\\cb37e9acf085d108\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 31
~~~
Stack Trace:
~~~
at System.ComponentModel.DataAnnotations.Tests.ValidationAttributeTestBase.Validate_Valid() in D:\j\workspace\outerloop_net---903ddde6\src\System.ComponentModel.Annotations\tests\ValidationAttributeTestBase.cs:line 22
~~~

**Comment by safern** [comment]
I think this will be fixed with:

https://github.com/dotnet/corefx/pull/17874
