### ISSUE TITLE
Desktop: System.IO.Pipes.Tests.ReadFromPipeWithClosedPartner_ReadNoBytes failed with "System.ArgumentException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18147]
Failed tests:
System.IO.Pipes.Tests.AnonymousPipeTest_Read_ServerIn_ClientOut.ReadFromPipeWithClosedPartner_ReadNoBytes
System.IO.Pipes.Tests.AnonymousPipeTest_Read_ServerOut_ClientIn.ReadFromPipeWithClosedPartner_ReadNoBytes 

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/13/testReport/System.IO.Pipes.Tests/AnonymousPipeTest_Read_ServerIn_ClientOut/ReadFromPipeWithClosedPartner_ReadNoBytes/

~~~
MESSAGE:
System.ArgumentException : Either the IAsyncResult object did not come from the corresponding async method on this type, or EndRead was called multiple times with the same IAsyncResult.
+++++++++++++++++++
STACK TRACE:
at System.IO.Stream.EndRead(IAsyncResult asyncResult) at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.IO.Pipes.Tests.PipeTest_Read.<ReadFromPipeWithClosedPartner_ReadNoBytes>d__9.MoveNext() in D:\j\workspace\outerloop_net---903ddde6\src\System.IO.Pipes\tests\PipeTest.Read.cs:line 225 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

**Comment by Jiayili1** [comment]
This issue is repro on Full framework tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170418.01/workItem/System.IO.Pipes.Tests/analysis/xunit/System.IO.Pipes.Tests.AnonymousPipeTest_Read_ServerIn_ClientOut~2FReadFromPipeWithClosedPartner_ReadNoBytes

**Comment by Jiayili1** [comment]
This issue is repro on desktop([build#30](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/30/testReport/)), detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/lastCompletedBuild/testReport/System.IO.Pipes.Tests/AnonymousPipeTest_Read_ServerIn_ClientOut/ReadFromPipeWithClosedPartner_ReadNoBytes/

MESSAGE:
~~~
System.ArgumentException : Either the IAsyncResult object did not come from the corresponding async method on this type, or EndRead was called multiple times with the same IAsyncResult.
~~~
STACK TRACE:
~~~
at System.IO.Stream.EndRead(IAsyncResult asyncResult) 
at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
at System.IO.Pipes.Tests.PipeTest_Read.<ReadFromPipeWithClosedPartner_ReadNoBytes>d__9.MoveNext() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.IO.Pipes\tests\PipeTest.Read.cs:line 225 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~
