### ISSUE TITLE
Failure in Write_HeadersToClosedConnectionSynchronously_ThrowsHttpListenerException

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18188]
```
MESSAGE:
Assert.Throws() Failure\r\nExpected: typeof(System.Net.HttpListenerException)\r\nActual: (No exception was thrown)
+++++++++++++++++++
STACK TRACE:
at System.Net.Tests.HttpResponseStreamTests.<Write_HeadersToClosedConnectionSynchronously_ThrowsHttpListenerException>d__21.MoveNext() in D:\j\workspace\windows_nt_re---37265eab\src\System.Net.HttpListener\tests\HttpResponseStreamTests.cs:line 460 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/6067/testReport/junit/System.Net.Tests/HttpResponseStreamTests/Write_HeadersToClosedConnectionSynchronously_ThrowsHttpListenerException_ignoreWriteExceptions__True_/

**Comment by danmosemsft** [comment]
```
                // Writing to, a closed connection should fail.
                Assert.Throws<HttpListenerException>(() => context.Response.OutputStream.Write(buffer, 0, buffer.Length));
```

**Comment by hughbe** [comment]
I caused this... Submitting a PR to disable them now.

**Comment by Jiayili1** [comment]
Failed again on build 20170411.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170411.01/workItem/System.Net.HttpListener.Tests/analysis/xunit/System.Net.Tests.HttpResponseStreamTests~2FWrite_HeadersToClosedConnectionSynchronously_ThrowsHttpListenerException(ignoreWriteExceptions:%20False)

**Comment by Jiayili1** [comment]
This issue is repro on OuterLoop_netcoreapp_win10_debug, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win10_debug/13/testReport/System.Net.Tests/HttpResponseStreamTests/Write_HeadersToClosedConnectionSynchronously_ThrowsHttpListenerException_ignoreWriteExceptions__False_/

**Comment by steveharter** [comment]
Closing as apparently fixed on 4/11. No repros since 4/11 (in which there were 5 that day, and several the previous days starting on 4/6)

**Comment by hughbe** [comment]
The tests were disabled, I'm looking at the best way to re-enable them but am treading carefully as I don't want to break the CI again

**Comment by caesar1995** [comment]
>The tests were disabled..

I enabled the tests and tested on my machine. Didn't observe any failures. 

I will remove the [ActiveIssue] label. We can reopen the issue if there are any failures.

@davidsh

**Comment by CIPop** [comment]
@steveharter there is an ActiveIssue label on these tests so they couldn't run. Please don't close issues that are referenced in code.

[ActiveIssue(18188, platforms: TestPlatforms.Windows)] // Indeterminate failure - socket not always fully disconnected.

**Comment by AriNuer** [comment]
Test `System.Net.Tests.HttpResponseStreamTests.Write_ContentToClosedConnectionAsynchronously_ThrowsHttpListenerException` failed with same failure.

**Build:**
[20191106.64](https://dnceng.visualstudio.com/public/_build/results?buildId=418593)(Master)

**Details:**
https://dnceng.visualstudio.com/public/_build/results?buildId=418593&view=ms.vss-test-web.build-test-results-tab&runId=13158060&resultId=176647&paneView=debug

**Log:**
```
Error message
Assert.Throws() Failure
Expected: typeof(System.Net.HttpListenerException)
Actual: (No exception was thrown)

Stack trace
   at System.Net.Tests.HttpResponseStreamTests.Write_ContentToClosedConnectionAsynchronously_ThrowsHttpListenerException(Boolean ignoreWriteExceptions) in /_/src/System.Net.HttpListener/tests/HttpResponseStreamTests.cs:line 495
--- End of stack trace from previous location ---
```
