### ISSUE TITLE
Test cases in XsPerformanceTest do not work

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#18249]
I get errors like the following when I run the tests in [this file](https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/tests/XmlSerializer/Performance/XsPerformanceTest.cs).

```
System.Xml.XmlSerializer.Tests.Performance.XsPerformanceTest.XsDeSerializationTest(numberOfRuns: 100, testType: DictionaryOfSimpleType, testSize: 1024) [FAIL]
        System.NotSupportedException : The type System.Collections.Generic.Dictionary`2[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[SerializationTypes.SimpleType, System.Xml
  .XmlSerializer.ReflectionOnly.Tests, Version=4.0.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb]] is not supported because it implements IDictionary.
        Stack Trace:
           D:\OSS\corefx\src\System.Private.Xml\src\System\Xml\Serialization\Types.cs(1312,0): at System.Xml.Serialization.TypeScope.GetDefaultIndexer(Type type, String memberInfo)
           D:\OSS\corefx\src\System.Private.Xml\src\System\Xml\Serialization\Types.cs(829,0): at System.Xml.Serialization.TypeScope.ImportTypeDesc(Type type, MemberInfo memberInfo, Boolean directReference)
           D:\OSS\corefx\src\System.Private.Xml\src\System\Xml\Serialization\Types.cs(714,0): at System.Xml.Serialization.TypeScope.GetTypeDesc(Type type, MemberInfo source, Boolean directReference, Boolean throwOnError)
           D:\OSS\corefx\src\System.Private.Xml\src\System\Xml\Serialization\Models.cs(48,0): at System.Xml.Serialization.ModelScope.GetTypeModel(Type type, Boolean directReference)
           D:\OSS\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlReflectionImporter.cs(170,0): at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(Type type, XmlRootAttribute root, String defaultNamespace)
           D:\OSS\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializer.cs(274,0): at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
           D:\OSS\corefx\src\System.Private.Xml\tests\XmlSerializer\Performance\XsPerformanceTest.cs(75,0): at System.Xml.XmlSerializer.Tests.Performance.XsSerializer.Init(Object obj)
           D:\OSS\corefx\src\System.Runtime.Serialization.Xml\tests\Performance\PerformanceTestsCommon.cs(326,0): at System.Runtime.Serialization.PerformanceTestCommon.RunDeserializationPerformanceTest(Int32 numberOfRuns, TestType testT
  ype, Int32 testSize, ISerializerFactory serializerFactory)
```

**Comment by shmao** [comment]
@mellinoe what was the command you used to run the perf tests? I added the following section in `System.Xml.XmlSerializer.Tests.csproj`,

```xml
<ItemGroup>
  <ProjectReference Include="$(CommonPath)\..\perf\PerfRunner\PerfRunner.csproj">
    <Project>{69e46a6f-9966-45a5-8945-2559fe337827}</Project>
    <Name>PerfRunner</Name>
  </ProjectReference>
</ItemGroup>
```

And build and run the tests using the following command, 
```
msbuild /t:BuildAndTest /p:Performance=true /p:ConfigurationGroup=Release /p:TargetOS=Windows_NT
```

The build succeeded, but the tests didn't seem really running. What was the command you used to run the tests?

**Comment by mellinoe** [comment]
After my recent change, you can run performance tests using `/t:rebuildandtest /p:outerloop=true`. The way they are run is slightly different than if you use `/p:performance=true`, so it'd be interesting to know if that's causing the problem.

**Comment by shmao** [comment]
@mellinoe Thanks for the information. I was able to repro the issue. `/p:outerloop=true` worked for me. The failure was due to a bug in the test.
