### ISSUE TITLE
Tests under "System.Diagnostics.Tests.ProcessStartInfoTests" failed

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18262]
Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170412.01/workItem/System.Diagnostics.Process.Tests/wilogs

Result:
~~~
2017-04-12 01:49:31,403: INFO: proc(54): run_and_log_output: Output:   Discovering: System.Diagnostics.Process.Tests
2017-04-12 01:49:31,653: INFO: proc(54): run_and_log_output: Output:   Discovered:  System.Diagnostics.Process.Tests
2017-04-12 01:49:31,653: INFO: proc(54): run_and_log_output: Output:   Starting:    System.Diagnostics.Process.Tests
2017-04-12 01:49:32,355: INFO: proc(54): run_and_log_output: Output:     System.Diagnostics.Tests.ProcessStartInfoTests.TestUseShellExecuteProperty_SetAndGet_Windows [FAIL]
2017-04-12 01:49:32,355: INFO: proc(54): run_and_log_output: Output:       Assert.False() Failure
2017-04-12 01:49:32,355: INFO: proc(54): run_and_log_output: Output:       Expected: False
2017-04-12 01:49:32,355: INFO: proc(54): run_and_log_output: Output:       Actual:   True
2017-04-12 01:49:32,355: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-04-12 01:49:32,355: INFO: proc(54): run_and_log_output: Output:         E:\A\_work\60\s\corefx\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(243,0): at System.Diagnostics.Tests.ProcessStartInfoTests.TestUseShellExecuteProperty_SetAndGet_Windows()
2017-04-12 01:49:32,403: INFO: proc(54): run_and_log_output: Output:     System.Diagnostics.Tests.ProcessStartInfoTests.TestEnvironmentVariables_Environment_DataRoundTrips [FAIL]
2017-04-12 01:49:32,403: INFO: proc(54): run_and_log_output: Output:       Assert.Throws() Failure
2017-04-12 01:49:32,403: INFO: proc(54): run_and_log_output: Output:       Expected: typeof(System.ArgumentException)
2017-04-12 01:49:32,403: INFO: proc(54): run_and_log_output: Output:       Actual:   (No exception was thrown)
2017-04-12 01:49:32,403: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-04-12 01:49:32,403: INFO: proc(54): run_and_log_output: Output:         E:\A\_work\60\s\corefx\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(460,0): at System.Diagnostics.Tests.ProcessStartInfoTests.TestEnvironmentVariables_Environment_DataRoundTrips()
2017-04-12 01:49:32,418: INFO: proc(54): run_and_log_output: Output:     System.Diagnostics.Tests.ProcessStartInfoTests.TestEnvironmentProperty [FAIL]
2017-04-12 01:49:32,418: INFO: proc(54): run_and_log_output: Output:       Assert.Throws() Failure
2017-04-12 01:49:32,418: INFO: proc(54): run_and_log_output: Output:       Expected: typeof(System.ArgumentException)
2017-04-12 01:49:32,418: INFO: proc(54): run_and_log_output: Output:       Actual:   (No exception was thrown)
2017-04-12 01:49:32,418: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-04-12 01:49:32,418: INFO: proc(54): run_and_log_output: Output:         E:\A\_work\60\s\corefx\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(48,0): at System.Diagnostics.Tests.ProcessStartInfoTests.TestEnvironmentProperty()
2017-04-12 01:49:34,918: INFO: proc(54): run_and_log_output: Output: System.IndexOutOfRangeException: Index was outside the bounds of the array.
2017-04-12 01:49:34,918: INFO: proc(54): run_and_log_output: Output:    at System.Text.StringBuilder.get_Chars(Int32 index)
2017-04-12 01:49:34,918: INFO: proc(54): run_and_log_output: Output:    at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
2017-04-12 01:49:34,918: INFO: proc(54): run_and_log_output: Output:    at System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
2017-04-12 01:49:34,918: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
2017-04-12 01:49:34,918: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
2017-04-12 01:49:34,918: INFO: proc(54): run_and_log_output: Output:    at System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
2017-04-12 01:49:34,918: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.FinishContinuations()
2017-04-12 01:49:34,918: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
2017-04-12 01:49:34,918: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2017-04-12 01:49:34,918: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
2017-04-12 01:49:34,918: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
2017-04-12 01:49:34,934: INFO: proc(54): run_and_log_output: Output: Finished running tests.  End time= 1:49:34.93, Exit code = 1
2017-04-12 01:49:34,934: INFO: proc(58): run_and_log_output: Exit Code: 1
2017-04-12 01:49:34,934: ERROR: scriptrunner(82): _main: Error: No exception thrown, but XUnit results not created
2017-04-12 01:49:34,934: ERROR: helix_test_execution(83): report_error: Error running xunit None
~~~

**Comment by safern** [comment]
Grabbing this one.

**Comment by danmosemsft** [comment]
@hughbe who was look at these.

**Comment by safern** [comment]
I was planning on doing this one, did you get a chance to fix it @hughbe?

**Comment by danmosemsft** [comment]
Let's at least figure out the exception so we get detail on the failing tests.

**Comment by hughbe** [comment]
I'm investigating this. I get some similar exceptions, but also others.

**Comment by safern** [comment]
@hughbe I've already investigated and figured out the exception. Also we already disabled the test. https://github.com/dotnet/corefx/pull/18438 and opened 2 issues: #18437 and #18436 

I forgot to update this issue. I will update it to cover all the failing tests under S.D.Process, which from a quick look I believe most of them are a difference in behavior. I was planning on doing this, but if you want to take over feel free, just let know :)

**Comment by hughbe** [comment]
Up to you really, I can take over if you'd like.
Also, what's the convention for actual differences in the product code, e.g. ArgumentException vs InvalidEnumArgumentException. Do i need to create an issue for that and then submit a PR, or just fix it.

**Comment by safern** [comment]
All yours. 

It depends on how breaking the difference is. Usually if it is an exception or a minor thing you could submit a PR to fix it and we can have the discussion there. Either way if you open the issue and then submit the PR, the PR would close the issue. 

For this case I would just open a PR.

**Comment by Jiayili1** [comment]
The following tests failed again on outerloop_netfx_windows_nt_debug:
 System.Diagnostics.Tests.ProcessStartInfoTests.TestEnvironmentVariables_Environment_DataRoundTrips
 System.Diagnostics.Tests.ProcessStartInfoTests.TestEnvironmentProperty

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/21/testReport/System.Diagnostics.Tests/ProcessStartInfoTests/TestEnvironmentVariables_Environment_DataRoundTrips/
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/21/testReport/System.Diagnostics.Tests/ProcessStartInfoTests/TestEnvironmentProperty/

**Comment by Jiayili1** [comment]
This issue is repro on build#30, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/30/testReport/System.Diagnostics.Tests/ProcessStartInfoTests/TestEnvironmentVariables_Environment_DataRoundTrips/ 

Need to verify on next build, since the commit is not in this build

**Comment by safern** [comment]
I don't see any failures anymore in the latest netfx official build:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170425.01/workItem/System.Diagnostics.Process.Tests/wilogs

The PR was merged at around 1pm and the latest jenkins build was at 11:45 am, before the merge so that is why we still see it on our latest jenkins build.
