### ISSUE TITLE
System.Net.Security.Tests.SslStreamStreamToStreamTest_Sync.SslStream_StreamToStream_WriteAsync_ReadAsync_Pending_Success [FAIL]

### ISSUE THREAD

**Issue by shimingsg** [dotnet/corefx#18318]
**This test fails on Windows 10 Pro amd64:**
System.Net.Security.Tests.SslStreamStreamToStreamTest_Sync.SslStream_StreamToStream_WriteAsync_ReadAsync_Pending_Success [FAIL]
      System.IO.IOException : The read operation failed, see inner exception.
      ---- System.TimeoutException : VirtualNetwork: Timeout reading the next frame.
      Stack Trace:
         F:\repos\corefx\src\System.Net.Security\src\System\Net\Security\SslStreamInternal.cs(171,0): at System.Net.Security.SslStreamInternal.EndRead(IAsyncResult asyncResult)
         F:\repos\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.cs(537,0): at System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult)
            at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         F:\repos\corefx\src\System.Net.Security\tests\FunctionalTests\SslStreamStreamToStreamTest.cs(318,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.<SslStream_StreamToStream_WriteAsync_ReadAsync_Pending_Success>d__10.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         ----- Inner Stack Trace -----
         F:\repos\corefx\src\Common\tests\System\Net\VirtualNetwork\VirtualNetwork.cs(42,0): at System.Net.Test.Common.VirtualNetwork.ReadFrame(Boolean server, Byte[]& buffer)
         F:\repos\corefx\src\Common\tests\System\Net\VirtualNetwork\VirtualNetworkStream.cs(118,0): at System.Net.Test.Common.VirtualNetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
         F:\repos\corefx\src\System.Net.Security\tests\FunctionalTests\NotifyReadVirtualNetworkStream.cs(22,0): at System.Net.Security.Tests.NotifyReadVirtualNetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
         F:\repos\corefx\src\Common\tests\System\Net\VirtualNetwork\VirtualNetworkStream.cs(138,0): at System.Net.Test.Common.VirtualNetworkStream.<>c__DisplayClass27_0.<ReadAsync>b__0()
            at System.Threading.Tasks.Task`1.InnerInvoke()
            at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
            at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
         F:\repos\corefx\src\System.Net.Security\src\System\Net\FixedSizeReader.cs(56,0): at System.Net.FixedSizeReader.<ReadPacketAsync>d__1.MoveNext()

**Comment by stephentoub** [comment]
The VirtualNetwork test class has a 30 second timeout:
https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs#L13
and GCStress makes things run much, much, much slower.  I expect doing so just cause the test to bump up against the 30 second limit.

**Comment by danmosemsft** [comment]
I agree- seems we could close this as gcstress fallout.

**Comment by danmosemsft** [comment]
I'm going to be bold and close this.

**Comment by karelz** [comment]
cc @steveharter as he might run into this as well

**Comment by Jiayili1** [comment]
This issue is repro on full framework tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170420.01/workItem/System.Net.Security.Tests/analysis/xunit/System.Net.Security.Tests.SslStreamStreamToStreamTest_Async~2FSslStream_StreamToStream_WriteAsync_ReadAsync_Pending_Success

Message:
~~~
System.IO.IOException : The read operation failed, see inner exception.
     ---- System.TimeoutException : VirtualNetwork: Timeout reading the next frame.
~~~

Stack Trace:
~~~
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at System.Net.Security.Tests.SslStreamStreamToStreamTest.<SslStream_StreamToStream_WriteAsync_ReadAsync_Pending_Success>d__10.MoveNext() in E:\A\_work\83\s\corefx\src\System.Net.Security\tests\FunctionalTests\SslStreamStreamToStreamTest.cs:line 318
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Net.Test.Common.VirtualNetwork.ReadFrame(Boolean server, Byte[]& buffer) in E:\A\_work\83\s\corefx\src\Common\tests\System\Net\VirtualNetwork\VirtualNetwork.cs:line 42
   at System.Net.Test.Common.VirtualNetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count) in E:\A\_work\83\s\corefx\src\Common\tests\System\Net\VirtualNetwork\VirtualNetworkStream.cs:line 118
   at System.Net.Security.Tests.NotifyReadVirtualNetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count) in E:\A\_work\83\s\corefx\src\System.Net.Security\tests\FunctionalTests\NotifyReadVirtualNetworkStream.cs:line 22
   at System.IO.Stream.<>c.<BeginReadInternal>b__39_0(Object )
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.Stream.EndRead(IAsyncResult asyncResult)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
~~~

**Comment by karelz** [comment]
I don't think we had GCStress truly enabled with this run, right? (updated title)

@steveharter did it pop in your runs?

Moving to Future as it happens also on Desktop - i.e. it is not regression / new failure in .NET Core.

**Comment by stephentoub** [comment]
I have a fix for the SslStream_StreamToStream_WriteAsync_ReadAsync_Pending_Success test hang (the timeout) on desktop... is that what this issue is about now?  Will be putting up a PR for that momentarily.

**Comment by steveharter** [comment]
I did not see this in any of my windows runs (win10\win2008)

No jdash history for this either.
