### ISSUE TITLE
Remote machine process tests failing in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#18324]
```
     System.Diagnostics.Tests.ProcessTests.TestProcessOnRemoteMachineWindows [FAIL]
        System.InvalidOperationException : Couldn't connect to remote machine.
        ---- System.InvalidOperationException : Process performance counter is disabled, so the requested operation cannot be performed.
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(521,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(265,0): at System.Diagnostics.NtProcessManager.GetProcessIds(String machineName, Boolean isRemoteMachine)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(33,0): at System.Diagnostics.ProcessManager.IsProcessRunning(Int32 processId, String machineName)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(1055,0): at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\tests\ProcessTests.cs(868,0): at System.Diagnostics.Tests.ProcessTests.<GetTestProcess>d__76.MoveNext()
           D:\j\workspace\windows_nt_re---37265eab\src\System.Linq\src\System\Linq\Select.cs(133,0): at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
           ----- Inner Stack Trace -----
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(550,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(PerformanceCounterLib library)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(511,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
     System.Diagnostics.Tests.ProcessTests.GetProcessesByName_RemoteMachineNameWindows_ReturnsExpected(machineName: \"machine\") [FAIL]
        System.InvalidOperationException : Couldn't connect to remote machine.
        ---- System.InvalidOperationException : Process performance counter is disabled, so the requested operation cannot be performed.
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(521,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(1107,0): at System.Diagnostics.Process.GetProcesses(String machineName)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Windows.cs(27,0): at System.Diagnostics.Process.GetProcessesByName(String processName, String machineName)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\tests\ProcessTests.cs(821,0): at System.Diagnostics.Tests.ProcessTests.GetProcessesByName_ProcessNameMachineName_ReturnsExpected(String machineName)
           ----- Inner Stack Trace -----
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(550,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(PerformanceCounterLib library)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(511,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
     System.Diagnostics.Tests.ProcessTests.GetProcessesByName_RemoteMachineNameWindows_ReturnsExpected(machineName: \"\\\\machine\") [FAIL]
        System.InvalidOperationException : Couldn't connect to remote machine.
        ---- System.InvalidOperationException : Process performance counter is disabled, so the requested operation cannot be performed.
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(521,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(1107,0): at System.Diagnostics.Process.GetProcesses(String machineName)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Windows.cs(27,0): at System.Diagnostics.Process.GetProcessesByName(String processName, String machineName)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\tests\ProcessTests.cs(821,0): at System.Diagnostics.Tests.ProcessTests.GetProcessesByName_ProcessNameMachineName_ReturnsExpected(String machineName)
           ----- Inner Stack Trace -----
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(550,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(PerformanceCounterLib library)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(511,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
```

**Comment by hughbe** [comment]
I seem to be breaking the CI a bunch recently, so sorry for that. These guys pass CI but 

The errors are "Process performance counter is disabled, so the requested operation cannot be performed."

This could be a difference in configuration on various CI machines?

The only .NET framework reference I can find is https://weblogs.asp.net/nunitaddin/267559 and https://social.msdn.microsoft.com/Forums/vstudio/en-US/482b5994-32a4-4c95-a73f-3c05ca2aaf93/systeminvalidoperationexception-process-performance-counter-is-disabled-so-the-requested?forum=netfxbcl


I'm not sure the best way to check in the tests if the machine has the process performance counter disabled.

**Comment by danmosemsft** [comment]
Does this mean `Process.GetProcessesByName()` simply doesn't work on CI machines? Surely we were testing that before @hughbe 's changes

**Comment by stephentoub** [comment]
> Surely we were testing that before @hughbe 's changes

Not with a remote machine name.

**Comment by danmosemsft** [comment]
I'm confused why the CI part matters since \\machinename doesn't exist outside of CI either. Maybe the "disabled performance counters" refers to the local box.

**Comment by stephentoub** [comment]
> I'm confused why the CI part matters 

CI part matters for being able to test the success path.  My point was that we haven't been testing with remote names; the only thing we could have reasonably tested in CI was the failure path, which this PR apparently tried to do.

(When the test is fixed, the machine name should also be changed to something like `Guid.NewGuid().ToString("N")`... it's quite possible that somewhere the test gets executed there could be a box on the network named `machine`.)

> Maybe the "disabled performance counters" refers to the local box

It does.

**Comment by danmosemsft** [comment]
@hughbe do you want to see whether you can repro this lcally by switching off the perf counters? (Seems stuff on web about how to do that). That would make it possible to try to find a way to determine whether they're off, then, we can keep the test.

**Comment by hughbe** [comment]
I took a look at this. I just realised that I didn't add the first `TestProcessOnRemoteMachineWindows`. Really not sure why it's triggering now and not before. 

Moreover, there is actually code in the tests to check this. The problem is that it's registry specific, so I guess this doesn't work in non-admin PCs.
```cs
private static bool ProcessPeformanceCounterEnabled()
{
    try
    {
        using (Microsoft.Win32.RegistryKey perfKey = Microsoft.Win32.Registry.LocalMachine.OpenSubKey(@"SYSTEM\CurrentControlSet\Services\PerfProc\Performance"))
        {
            if (perfKey == null)
                return false;
            int? value = (int?)perfKey.GetValue("Disable Performance Counters", null);
            return !value.HasValue || value.Value == 0;
        }
    }
    catch (Exception)
    {
        // Ignore exceptions, and just assume the counter is enabled.
    }

    return true;
}

[ActiveIssue(18324)]
[PlatformSpecific(TestPlatforms.Windows)]  // Behavior differs on Windows and Unix
[ConditionalTheory(nameof(ProcessPeformanceCounterEnabled))]
[SkipOnTargetFramework(TargetFrameworkMonikers.UapAot, "https://github.com/dotnet/corefx/issues/18212")]
[MemberData(nameof(GetTestProcess))]
public void TestProcessOnRemoteMachineWindows(Process currentProcess, Process remoteProcess)
{
    Assert.Equal(currentProcess.Id, remoteProcess.Id);
    Assert.Equal(currentProcess.BasePriority, remoteProcess.BasePriority);
    Assert.Equal(currentProcess.EnableRaisingEvents, remoteProcess.EnableRaisingEvents);
    Assert.Equal("127.0.0.1", remoteProcess.MachineName);
    // This property throws exception only on remote processes.
    Assert.Throws<NotSupportedException>(() => remoteProcess.MainModule);
}

```

**Comment by hughbe** [comment]
I think what I'll do is conditionally enable `GetProcessesByName_RemoteMachineNameWindows_ReturnsExpected` and `GetProcessesByName_RemoteMachineNameWindows_ReturnsExpected`, then use `Guid.NewGuid().ToString()`

Next, maybe these tests should only be run in outerloop, or we can perform a bit of extra validation in ProcessPerformanceCounterEnabled

**Comment by hughbe** [comment]
I can repro this by turning off "HKLM/SYSTEM/CurrentControlSet/Services/PerfProc/Performance".

There are a couple of issues with the current approach. My understanding is that you need to reboot the machine after setting this key. Thus the key may be true but the machine hasn't rebooted yet so performance counters are still disabled.

One solution could be to do
```cs
try
{
    Process.GetProcesses(Guid.NewGuid().ToString("N"));
}
catch (InvalidOperationException ex)
{
    return !ex.Message.Contains("Process performance counter is disabled");
 }
```

but this could be a chicken-egg problem: we're conditionally testing something based on what we're testing etc.
