### ISSUE TITLE
IOException in System.IO.Tests.Directory_NotifyFilter_Tests.FileSystemWatcher_Directory_NotifyFilter_Security

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18381]
```
Unhandled Exception of Type System.IO.IOException
Message :
System.IO.IOException : Access to the path '\\\\?\\C:\\Users\\DotNetTestRunner\\AppData\\Local\\Packages\\5cd54353-3ed7-4a6e-a72f-db349f28867c_v52bfwc2c21ha\\AC\\Temp\\Directory_NotifyFilter_Tests_dkl4gx0n.z4r\\FileSystemWatcher_Directory_NotifyFilter_Security_148\\dir' is denied.
Stack Trace :
   at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path)
   at System.IO.Tests.Directory_NotifyFilter_Tests.<>c__DisplayClass9_0.<FileSystemWatcher_Directory_NotifyFilter_Security>b__1()
   at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String[] expectedPaths, Int32 attempts, Int32 timeout)
   at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String expectedPath, Int32 attempts, Int32 timeout)
   at System.IO.Tests.Directory_NotifyFilter_Tests.FileSystemWatcher_Directory_NotifyFilter_Security(NotifyFilters filter)
```

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20170414.01/workItem/System.IO.FileSystem.Watcher.Tests/analysis/xunit/System.IO.Tests.Directory_NotifyFilter_Tests~2FFileSystemWatcher_Directory_NotifyFilter_Security(filter:%20Attributes)

**Comment by danmosemsft** [comment]
This may be another case where we need to do a more robust directory delete. In this case we need to create it again so usign retries instead of just ignoring the result
```
                Action cleanup = () =>
                {
                    // Recreate the Directory.
                    Directory.Delete(dir.Path);
                    Directory.CreateDirectory(dir.Path);
                };

```

Of course depending on the file watcher test is trying to do, retries could throw it off.

**Comment by Jiayili1** [comment]
This issue is repro on UWP F5 Tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20170427.01/workItem/System.IO.FileSystem.Watcher.Tests/analysis/xunit/System.IO.Tests.Directory_NotifyFilter_Tests~2FFileSystemWatcher_Directory_NotifyFilter_Security(filter:%20Attributes)

**Comment by JeremyKuhne** [comment]
@ianhays I think #21109 is a dupe of this

cc: @joperezr

**Comment by safern** [comment]
Yes it is a dupe, they reference the same test, #21109 has a more detailed description and the test is disabled with activeIssue against it, so perhaps we should close this one.

**Comment by joperezr** [comment]
Agreed with @safern. Closing this one.
