### ISSUE TITLE
System.IO.Pipes.Tests fail with EntryPointNotFoundException on Win10

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#1840]
I have disabled the following tests in dev/metadata branch until they are fixed.

```
   AnonymousPipesSimpleTest.ClientPInvokeChecks [FAIL]
      System.EntryPointNotFoundException : Unable to find an entry point named 'GetNamedPipeHandleStateW' in DLL 'api-ms-win-core-namedpipe-l1-2-1.dll'.
      Stack Trace:
            at Interop.mincore.GetNamedPipeHandleState(SafePipeHandle hNamedPipe, Int32& lpState, IntPtr lpCurInstances, IntPtr lpMaxCollectionCount, IntPtr lpCollectDataTimeout, IntPtr lpUserName, Int32 nMaxUserNameSize)
         C:\FX0\src\System.IO.Pipes\src\System\IO\Pipes\PipeStream.Windows.cs(983,0): at System.IO.Pipes.PipeStream.UpdateReadMode()
         C:\FX0\src\System.IO.Pipes\src\System\IO\Pipes\PipeStream.Windows.cs(236,0): at System.IO.Pipes.PipeStream.get_ReadMode()
         C:\FX0\src\System.IO.Pipes\tests\AnonymousPipesSimpleTest.cs(221,0): at AnonymousPipesSimpleTest.ClientPInvokeChecks()
   NamedPipesSimpleTest.ClientServerMessages [FAIL]
      System.EntryPointNotFoundException : Unable to find an entry point named 'GetNamedPipeHandleStateW' in DLL 'api-ms-win-core-namedpipe-l1-2-1.dll'.
      Stack Trace:
            at Interop.mincore.GetNamedPipeHandleState(SafePipeHandle hNamedPipe, IntPtr lpState, IntPtr lpCurInstances, IntPtr lpMaxCollectionCount, IntPtr lpCollectDataTimeout, StringBuilder lpUserName, Int32 nMaxUserNameSize)
         C:\FX0\src\System.IO.Pipes\src\System\IO\Pipes\NamedPipeServerStream.Windows.cs(149,0): at System.IO.Pipes.NamedPipeServerStream.GetImpersonationUserName()
         C:\FX0\src\System.IO.Pipes\tests\NamedPipesSimpleTest.cs(389,0): at NamedPipesSimpleTest.ClientServerMessages()
Finished:    System.IO.Pipes.Tests
```

**Comment by pallavit** [comment]
Can you tell which windows build are you seeing this?

**Comment by tmat** [comment]
@pallavit Win10 10074

**Comment by tmat** [comment]
And Jenkins is failing as well for some reason (which may or may not be the same): http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/1427/console

**Comment by pallavit** [comment]
@tmat  These tests are failing because they depend on an APISet which has been recently added to TH and most likely your build does not have it. Can you share the build location?

**Comment by pallavit** [comment]
#1687 was closed due to the same issue.

**Comment by nguerrera** [comment]
I'm hitting this on 10074 too and nearly filed a triplicate. Can we mark the test with ActiveIssue until the masses on Enterprise Preview get a new build?

**Comment by pallavit** [comment]
I was under the impression that @tmat disabled this test already against this Active Issue.

**Comment by nguerrera** [comment]
That doesn't appear to be the case. I've submitted #2123 to do so.

**Comment by pallavit** [comment]
This should be fixed now on most images in use and so opportunistically closing it.

**Comment by nguerrera** [comment]
@pallavit Did you remove the ActiveIssue attributes?

**Comment by pallavit** [comment]
@nguerrera Thanks for reminding, I totally forgot!. I am on it right now :)
