### ISSUE TITLE
Visual Studio tests also running Unix tests

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#18469]
E.g.
```
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Diagnostics.Process.Tests
Discovered:  System.Diagnostics.Process.Tests
Starting:    System.Diagnostics.Process.Tests
   System.Diagnostics.Tests.ProcessModuleTests.TestModulesContainsUnixNativeLibs [FAIL]
      Assert.Contains() Failure
      Not found: (filter expression)
      In value:  <CastIterator>d__34<ProcessModule> [System.Diagnostics.ProcessModule (dotnet.exe), System.Diagnostics.ProcessModule (ntdll.dll), System.Diagnostics.ProcessModule (KERNEL32.DLL), System.Diagnostics.ProcessModule (KERNELBASE.dll), System.Diagnostics.ProcessModule (ucrtbase.dll), ...]
      Stack Trace:
            at System.Diagnostics.Tests.ProcessModuleTests.TestModulesContainsUnixNativeLibs()
TestUserCredentialsPropertiesOnWindows: NetUserAdd failed: Access is denied
   System.Diagnostics.Tests.ProcessStartInfoTests.TestUseShellExecuteProperty_Redirects_NotSupported(std: 0) [FAIL]
      System.PlatformNotSupportedException : UseShellExecute must always be set to false.
      Stack Trace:
            at System.Diagnostics.ProcessStartInfo.set_UseShellExecute(Boolean value)
            at System.Diagnostics.Tests.ProcessStartInfoTests.TestUseShellExecuteProperty_Redirects_NotSupported(Int32 std)
   System.Diagnostics.Tests.ProcessStartInfoTests.TestUseShellExecuteProperty_Redirects_NotSupported(std: 1) [FAIL]
      System.PlatformNotSupportedException : UseShellExecute must always be set to false.
      Stack Trace:
            at System.Diagnostics.ProcessStartInfo.set_UseShellExecute(Boolean value)
            at System.Diagnostics.Tests.ProcessStartInfoTests.TestUseShellExecuteProperty_Redirects_NotSupported(Int32 std)
   System.Diagnostics.Tests.ProcessStartInfoTests.TestUseShellExecuteProperty_Redirects_NotSupported(std: 2) [FAIL]
      System.PlatformNotSupportedException : UseShellExecute must always be set to false.
      Stack Trace:
            at System.Diagnostics.ProcessStartInfo.set_UseShellExecute(Boolean value)
            at System.Diagnostics.Tests.ProcessStartInfoTests.TestUseShellExecuteProperty_Redirects_NotSupported(Int32 std)
   System.Diagnostics.Tests.ProcessStartInfoTests.Password_GetSetUnix_ThrowsPlatformNotSupportedException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.PlatformNotSupportedException)
      Actual:   (No exception was thrown)
      Stack Trace:
            at System.Diagnostics.Tests.ProcessStartInfoTests.Password_GetSetUnix_ThrowsPlatformNotSupportedException()
   System.Diagnostics.Tests.ProcessStartInfoTests.Domain_GetSetUnix_ThrowsPlatformNotSupportedException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.PlatformNotSupportedException)
      Actual:   (No exception was thrown)
      Stack Trace:
            at System.Diagnostics.Tests.ProcessStartInfoTests.Domain_GetSetUnix_ThrowsPlatformNotSupportedException()
   System.Diagnostics.Tests.ProcessStartInfoTests.PasswordInClearText_GetSetUnix_ThrowsPlatformNotSupportedException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.PlatformNotSupportedException)
      Actual:   (No exception was thrown)
      Stack Trace:
            at System.Diagnostics.Tests.ProcessStartInfoTests.PasswordInClearText_GetSetUnix_ThrowsPlatformNotSupportedException()
   System.Diagnostics.Tests.ProcessStartInfoTests.UserName_GetSetUnix_ThrowsPlatformNotSupportedException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.PlatformNotSupportedException)
      Actual:   (No exception was thrown)
      Stack Trace:
            at System.Diagnostics.Tests.ProcessStartInfoTests.UserName_GetSetUnix_ThrowsPlatformNotSupportedException()
   System.Diagnostics.Tests.ProcessStartInfoTests.TestUseShellExecuteProperty_SetAndGet_Unix [FAIL]
      System.PlatformNotSupportedException : UseShellExecute must always be set to false.
      Stack Trace:
            at System.Diagnostics.ProcessStartInfo.set_UseShellExecute(Boolean value)
            at System.Diagnostics.Tests.ProcessStartInfoTests.TestUseShellExecuteProperty_SetAndGet_Unix()
   System.Diagnostics.Tests.ProcessStartInfoTests.TestEnvironmentVariablesPropertyUnix [FAIL]
      System.ArgumentException : An item with the same key has already been added. Key: newkey2
      Stack Trace:
            at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
            at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
            at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
            at System.Collections.Specialized.StringDictionaryWrapper.Add(String key, String value)
            at System.Diagnostics.Tests.ProcessStartInfoTests.TestEnvironmentVariablesPropertyUnix()
   System.Diagnostics.Tests.ProcessStartInfoTests.LoadUserProfile_GetSetUnix_ThrowsPlatformNotSupportedException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.PlatformNotSupportedException)
      Actual:   (No exception was thrown)
      Stack Trace:
            at System.Diagnostics.Tests.ProcessStartInfoTests.LoadUserProfile_GetSetUnix_ThrowsPlatformNotSupportedException()
   System.Diagnostics.Tests.ProcessStartInfoTests.TestEnvironmentProperty [FAIL]
      Assert.Equal() Failure
                       (pos 6)
      Expected: NewKey
      Actual:   NewKey4
                       (pos 6)
      Stack Trace:
            at System.Diagnostics.Tests.ProcessStartInfoTests.TestEnvironmentProperty()
   System.Diagnostics.Tests.ProcessTests.MinWorkingSet_GetMacos_ThrowsPlatformSupportedException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.PlatformNotSupportedException)
      Actual:   typeof(System.InvalidOperationException): No process is associated with this object.
      Stack Trace:
            at System.Diagnostics.Process.EnsureState(State state)
            at System.Diagnostics.Process.EnsureState(State state)
            at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
            at System.Diagnostics.Process.GetProcessHandle(Int32 access)
            at System.Diagnostics.Process.GetWorkingSetLimits(IntPtr& minWorkingSet, IntPtr& maxWorkingSet)
            at System.Diagnostics.Process.EnsureWorkingSetLimits()
            at System.Diagnostics.Process.get_MinWorkingSet()
            at System.Diagnostics.Tests.ProcessTests.<>c__DisplayClass22_0.<MinWorkingSet_GetMacos_ThrowsPlatformSupportedException>b__0()
   System.Diagnostics.Tests.ProcessTests.TestRootGetProcessById [FAIL]
      System.ArgumentException : Process with an Id of 1 is not running.
      Stack Trace:
            at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
            at System.Diagnostics.Process.GetProcessById(Int32 processId)
            at System.Diagnostics.Tests.ProcessTests.TestRootGetProcessById()
   System.Diagnostics.Tests.ProcessTests.TestProcessOnRemoteMachineWindows [SKIP]
      Condition(s) not met: \"ProcessPeformanceCounterEnabled\"
   System.Diagnostics.Tests.ProcessTests.GetProcessesByName_RemoteMachineNameWindows_ReturnsExpected(machineName: \"machine\") [FAIL]
      System.InvalidOperationException : Couldn't connect to remote machine.
      ---- System.InvalidOperationException : Process performance counter is disabled, so the requested operation cannot be performed.
      Stack Trace:
            at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
            at System.Diagnostics.ProcessManager.GetProcessInfos(String machineName)
            at System.Diagnostics.Process.GetProcesses(String machineName)
            at System.Diagnostics.Process.GetProcessesByName(String processName, String machineName)
            at System.Diagnostics.Tests.ProcessTests.GetProcessesByName_ProcessNameMachineName_ReturnsExpected(String machineName)
            at System.Diagnostics.Tests.ProcessTests.GetProcessesByName_RemoteMachineNameWindows_ReturnsExpected(String machineName)
         ----- Inner Stack Trace -----
            at System.Diagnostics.NtProcessManager.GetProcessInfos(PerformanceCounterLib library)
            at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
   System.Diagnostics.Tests.ProcessTests.GetProcessesByName_RemoteMachineNameWindows_ReturnsExpected(machineName: \"\\\\machine\") [FAIL]
      System.InvalidOperationException : Couldn't connect to remote machine.
      ---- System.InvalidOperationException : Process performance counter is disabled, so the requested operation cannot be performed.
      Stack Trace:
            at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
            at System.Diagnostics.ProcessManager.GetProcessInfos(String machineName)
            at System.Diagnostics.Process.GetProcesses(String machineName)
            at System.Diagnostics.Process.GetProcessesByName(String processName, String machineName)
            at System.Diagnostics.Tests.ProcessTests.GetProcessesByName_ProcessNameMachineName_ReturnsExpected(String machineName)
            at System.Diagnostics.Tests.ProcessTests.GetProcessesByName_RemoteMachineNameWindows_ReturnsExpected(String machineName)
         ----- Inner Stack Trace -----
            at System.Diagnostics.NtProcessManager.GetProcessInfos(PerformanceCounterLib library)
            at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
   System.Diagnostics.Tests.ProcessTests.MainWindowHandle_GetUnix_ThrowsPlatformNotSupportedException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.PlatformNotSupportedException)
      Actual:   (No exception was thrown)
      Stack Trace:
            at System.Diagnostics.Tests.ProcessTests.MainWindowHandle_GetUnix_ThrowsPlatformNotSupportedException()
   System.Diagnostics.Tests.ProcessTests.MaxValueWorkingSet_GetSetMacos_ThrowsPlatformSupportedException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.PlatformNotSupportedException)
      Actual:   typeof(System.InvalidOperationException): No process is associated with this object.
      Stack Trace:
            at System.Diagnostics.Process.EnsureState(State state)
            at System.Diagnostics.Process.EnsureState(State state)
            at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
            at System.Diagnostics.Process.GetProcessHandle(Int32 access)
            at System.Diagnostics.Process.GetWorkingSetLimits(IntPtr& minWorkingSet, IntPtr& maxWorkingSet)
            at System.Diagnostics.Process.EnsureWorkingSetLimits()
            at System.Diagnostics.Process.get_MaxWorkingSet()
            at System.Diagnostics.Tests.ProcessTests.<>c__DisplayClass19_0.<MaxValueWorkingSet_GetSetMacos_ThrowsPlatformSupportedException>b__0()
   System.Diagnostics.Tests.ProcessTests.TestWindowApisUnix [FAIL]
      Assert.Equal() Failure
                 (pos 0)
      Expected:
      Actual:   C
                 (pos 0)
      Stack Trace:
            at System.Diagnostics.Tests.ProcessTests.TestWindowApisUnix()
   System.Diagnostics.Tests.ProcessTests.TestProcessOnRemoteMachineUnix [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.PlatformNotSupportedException)
      Actual:   typeof(System.InvalidOperationException): Couldn't connect to remote machine.
      Stack Trace:
            at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
            at System.Diagnostics.ProcessManager.GetProcessInfos(String machineName)
            at System.Diagnostics.Process.GetProcesses(String machineName)
            at System.Diagnostics.Process.GetProcessesByName(String processName, String machineName)
            at System.Diagnostics.Tests.ProcessTests.<>c__DisplayClass79_0.<TestProcessOnRemoteMachineUnix>b__0()
   System.Diagnostics.Tests.ProcessTests.GetProcessesByName_RemoteMachineNameUnix_ThrowsPlatformNotSupportedException(machineName: \"machine\") [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.PlatformNotSupportedException)
      Actual:   typeof(System.InvalidOperationException): Couldn't connect to remote machine.
      Stack Trace:
            at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
            at System.Diagnostics.ProcessManager.GetProcessInfos(String machineName)
            at System.Diagnostics.Process.GetProcesses(String machineName)
            at System.Diagnostics.Process.GetProcessesByName(String processName, String machineName)
            at System.Diagnostics.Tests.ProcessTests.<>c__DisplayClass72_0.<GetProcessesByName_RemoteMachineNameUnix_ThrowsPlatformNotSupportedException>b__0()
   System.Diagnostics.Tests.ProcessTests.GetProcessesByName_RemoteMachineNameUnix_ThrowsPlatformNotSupportedException(machineName: \"\\\\machine\") [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.PlatformNotSupportedException)
      Actual:   typeof(System.InvalidOperationException): Couldn't connect to remote machine.
      Stack Trace:
            at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
            at System.Diagnostics.ProcessManager.GetProcessInfos(String machineName)
            at System.Diagnostics.Process.GetProcesses(String machineName)
            at System.Diagnostics.Process.GetProcessesByName(String processName, String machineName)
            at System.Diagnostics.Tests.ProcessTests.<>c__DisplayClass72_0.<GetProcessesByName_RemoteMachineNameUnix_ThrowsPlatformNotSupportedException>b__0()
   System.Diagnostics.Tests.ProcessTests.TestBasePriorityOnUnix [FAIL]
      Assert.Equal() Failure
      Expected: -11
      Actual:   13
      Stack Trace:
            at System.Diagnostics.Tests.ProcessTests.SetAndCheckBasePriority(ProcessPriorityClass exPriorityClass, Int32 priority)
            at System.Diagnostics.Tests.ProcessTests.TestBasePriorityOnUnix()
   System.Diagnostics.Tests.ProcessTests.TestHandleCount_OSX [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   418
      Stack Trace:
            at System.Diagnostics.Tests.ProcessTests.TestHandleCount_OSX()
   System.Diagnostics.Tests.ProcessTests.TestUseShellExecute_Unix_Succeeds [FAIL]
      System.PlatformNotSupportedException : UseShellExecute must always be set to false.
      Stack Trace:
            at System.Diagnostics.ProcessStartInfo.set_UseShellExecute(Boolean value)
            at System.Diagnostics.Tests.ProcessTests.TestUseShellExecute_Unix_Succeeds()
   System.Diagnostics.Tests.ProcessThreadTests.TestStartTimeProperty_OSX [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.PlatformNotSupportedException)
      Actual:   (No exception was thrown)
      Stack Trace:
            at System.Diagnostics.Tests.ProcessThreadTests.TestStartTimeProperty_OSX()
Finished:    System.Diagnostics.Process.Tests

=== TEST EXECUTION SUMMARY ===
   System.Diagnostics.Process.Tests  Total: 241, Errors: 0, Failed: 26, Skipped: 1, Time: 21.964s

Press enter key to continue.../
```

**Comment by karelz** [comment]
@hughbe do you mean that when you execute tests from VS, the tests don't properly filter out Linux-only tests?

**Comment by hughbe** [comment]
Correct

**Comment by hughbe** [comment]
It also looks like VS tests are ignoring ActiveIssue tests

**Comment by karelz** [comment]
@weshaggard @mellinoe can we get this funded right after 2.0 madness? I see more and more contributors using VS. We should make it first-class experience, or discourage people to use it.

**Comment by hughbe** [comment]
>We should make it first-class experience, or discourage people to use it.

I'm curious: are corefx devs not using VS for development?

**Comment by karelz** [comment]
> I'm curious: are corefx devs not using VS for development?

I don't know. Given the number of problems in VS, it seems the answer is 'no' ...

**Comment by hughbe** [comment]
I find that surprising

**Comment by karelz** [comment]
If you think it through it is not so surprising - VS support is more complicated than command line scripts. Command line scripts are necessary for CI, etc. Command line is also super-simple on VMs and brand new machines - you don't need to install VS. Therefore command line scripts have to be brought up first and with high-quality.
At the time we can start using VS (things are stable), everyone on the team already memorized command line, so there is not huge pressure.

External contributors are more likely to start with VS though ... that's why we should make it first-class citizen and try to use it a bit more on the team as well (to catch breakages early on).

**Comment by hughbe** [comment]
Fair enough, it does make sense, And the obvious non-Xplat nature of VS gets in the way.
The way I interact with VS and the command line is a bit random: I use VS to edit and build product code, to edit test code but use the command line to run the tests.
However, I use VS to debug tests so it's a pain when these kinds of things get in the way of identifying and debugging failing tests.

**Comment by karelz** [comment]
Point taken. We will try to look into the VS / VSCode usage with CoreFX for contributors. It will be helpful also for us.

**Comment by weshaggard** [comment]
Yes our VS support comes and goes, we try to keep it working but we are always on the bleeding edge of what the tools can support and in a lot of times we are building things the tools need to run which makes it kind of difficult. However it is definitely a goal to try and keep them working and we appreciate folks filling bugs when something isn't working.

As for the test project running non-windows tests that shouldn't be the case. Did you make any changes to the command line it runs under the Debug options? I'm testing this locally to see if I hit this.

**Comment by karelz** [comment]
cc @FransBouma

**Comment by weshaggard** [comment]
I was able to reproduce this issue locally. Thanks for pointing it out @hughbe. PR https://github.com/dotnet/buildtools/pull/1513 should address this issue.

**Comment by danmosemsft** [comment]
This should be fixed then. @hughbe please reopen if not.
