### ISSUE TITLE
Tests under "System.Console.Performance.Tests" failed with "System.IO.IOException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18462]
There is no test results generated under "System.Console.Performance.Tests"

Configuration: OSX.1012.Amd64

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170415.01/workItem/System.Console.Performance.Tests/wilogs

~~~
2017-04-14 18:29:49,928: INFO: proc(54): run_and_log_output: Output: xUnit.net console test runner (64-bit .NET Core)
2017-04-14 18:29:49,928: INFO: proc(54): run_and_log_output: Output: Copyright (C) 2014 Outercurve Foundation.
2017-04-14 18:29:49,929: INFO: proc(54): run_and_log_output: Output: 
2017-04-14 18:29:50,018: INFO: proc(54): run_and_log_output: Output: Discovering: System.Console.Performance.Tests
2017-04-14 18:29:50,133: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Console.Performance.Tests
2017-04-14 18:29:50,169: INFO: proc(54): run_and_log_output: Output: Starting:    System.Console.Performance.Tests
2017-04-14 18:29:50,411: INFO: proc(54): run_and_log_output: Output:    [FATAL] System.IO.IOException
2017-04-14 18:29:50,412: INFO: proc(54): run_and_log_output: Output:       System.IO.IOException : Too many open files
2017-04-14 18:29:50,416: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-04-14 18:29:50,511: INFO: proc(54): run_and_log_output: Output:             at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
2017-04-14 18:29:50,512: INFO: proc(54): run_and_log_output: Output:             at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
2017-04-14 18:29:50,512: INFO: proc(54): run_and_log_output: Output:             at Microsoft.Win32.SafeHandles.SafeFileHandleHelper.Open(Func`1 fdFunc)
2017-04-14 18:29:50,512: INFO: proc(54): run_and_log_output: Output:             at System.ConsolePal.OpenStandardError()
2017-04-14 18:29:50,512: INFO: proc(54): run_and_log_output: Output:             at System.Console.<>c.<get_Error>b__27_0()
2017-04-14 18:29:50,512: INFO: proc(54): run_and_log_output: Output:             at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Object& syncLock, Func`1 valueFactory)
2017-04-14 18:29:50,520: INFO: proc(54): run_and_log_output: Output:    System.ConsoleTests.Perf_Console.OpenStandardOutput [FAIL]
2017-04-14 18:29:50,520: INFO: proc(54): run_and_log_output: Output:       System.IO.IOException : Too many open files
2017-04-14 18:29:50,520: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-04-14 18:29:50,520: INFO: proc(54): run_and_log_output: Output:             at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
2017-04-14 18:29:50,521: INFO: proc(54): run_and_log_output: Output:             at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
2017-04-14 18:29:50,521: INFO: proc(54): run_and_log_output: Output:             at Microsoft.Win32.SafeHandles.SafeFileHandleHelper.Open(Func`1 fdFunc)
2017-04-14 18:29:50,521: INFO: proc(54): run_and_log_output: Output:             at System.ConsolePal.OpenStandardOutput()
2017-04-14 18:29:50,521: INFO: proc(54): run_and_log_output: Output:             at System.ConsoleTests.Perf_Console.OpenStandardOutput()
~~~

**Comment by Jiayili1** [comment]
This issue is repro on portable core tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170415.01/workItem/System.Console.Performance.Tests/wilogs

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/pull/18503
