### ISSUE TITLE
Desktop: Tests under "System.Diagnostics.Tests.ProcessTests" failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18473]
Configuration: outerloop_netfx_windows_nt_debug

~~~
System.Diagnostics.Tests.ProcessTests.TestProcessName [FAIL]
Assert.Equal() Failure
        Expected: RemoteExecutorConsoleApp
        Actual:   xunit.console
        Stack Trace:
          at System.Diagnostics.Tests.ProcessTests.TestProcessName()
in D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.Process\tests\ProcessTests.cs(685,0)

System.Diagnostics.Tests.ProcessTests.TestMainModuleOnNonOSX [FAIL]
        Assert.Equal() Failure
                   (pos 0)
        Expected: dotnet.exe
        Actual:   xunit.console.exe
                   (pos 0)
        Stack Trace:
         at System.Diagnostics.Tests.ProcessTests.TestMainModuleOnNonOSX()
in  D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.Process\tests\ProcessTests.cs(271,0)

System.Diagnostics.Tests.ProcessTests.TestStartInfo [FAIL]
Assert.Equal() Failure
                   (pos 0)
        Expected: D:\\j\\workspace\\outerloop_net---903ddde6\\b···
        Actual:   RemoteExecutorConsoleApp.exe
                   (pos 0)
        Stack Trace:
         at System.Diagnostics.Tests.ProcessTests.TestStartInfo()
in  D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.Process\tests\ProcessTests.cs(924,0)
~~~

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/21/consoleText

**Comment by Jiayili1** [comment]
This issue is repro on build 20170418.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170418.01/workItem/System.Diagnostics.Process.Tests
