### ISSUE TITLE
SslStream.AuthenticateAsClientAsync() fails with "The buffers supplied to a function was too small"

### ISSUE THREAD

**Issue by MattAfflek** [dotnet/corefx#1854]
From time to time I receive this error message.
```
System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The buffers supplied to a function was too small
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.<>c__DisplayClass3.<ConnectAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at DownloadAndUpdatePrices.Email.EmailService.<DownloadFileAsync>d__0.MoveNext() in d:\ProjectIS-3\WebProjectAutosouz\DownloadAndUpdatePrices\DownloadAndUpdatePrices\Email\EmailService.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DownloadAndUpdatePrices.BLL.DownloadService.<DownloadFileAsync>d__0.MoveNext() in d:\ProjectIS-3\WebProjectAutosouz\DownloadAndUpdatePrices\DownloadAndUpdatePrices\BLL\DownloadService.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DownloadAndUpdatePrices.Program.<Process>d__d.MoveNext() in d:\ProjectIS-3\WebProjectAutosouz\DownloadAndUpdatePrices\DownloadAndUpdatePrices\Program.cs:line 48
```

https://github.com/jstedfast/MailKit/issues/197

**Comment by migig** [comment]
Same here.

**Comment by SidharthNabar** [comment]
Hi @MattAfflek , is this issue separate from the issue #1894 that you have opened? The exception stack trace seems to be the same.

**Comment by MattAfflek** [comment]
Hi @SidharthNabar , I'm getting this errors from one application.
Message header is different, "The buffers supplied to a function was too small" and "The message or signature supplied for verification has been altered".

**Comment by migig** [comment]
@SidharthNabar Not sure if for same reason, but I get the same exceptions exactly.

**Comment by NathanBaulch** [comment]
I started getting this error on a regular basis after moving an app that uses [S22.Imap](https://github.com/smiley22/S22.Imap) to [AppHarbor](https://appharbor.com/).

**Comment by migig** [comment]
@NathanBaulch Don't know if it will help you, but what I found is that if you retry immediately, it almost always works the second time. Don't know why it works, but I'm using this approach until the framework is patched. You [can read more here](https://github.com/jstedfast/MailKit/issues/197#issuecomment-156051801).

**Comment by NathanBaulch** [comment]
Thanks @migig, that appears to be working. For anyone else who stumbles on this issue, here's my updated code which does a single retry on authentication failure:

```csharp
ImapClient client;
try
{
	client = new ImapClient(host, port, true);
}
catch (AuthenticationException ex)
{
	if (ex.InnerException is Win32Exception)
	{
		Trace.TraceInformation("IMAP connect failed, retrying");
		client = new ImapClient(host, port, true);
	}
	else
	{
		throw;
	}
}
using (client)
{
	client.Login(UserName, Password, AuthMethod.Auto);
	try
	{
		//...
	}
	finally
	{
		client.Logout();
	}
}
```

**Comment by CIPop** [comment]
@MattAfflek @NathanBaulch Could you please share a minimal repro project? Also, were you able to repro this in .Net Desktop?

**Comment by MattAfflek** [comment]
@CIPop I can't get this error in public mail servers.
You can see this error in my test project. https://github.com/MattAfflek/EmailTest/
Our administrator said that We use mail server based on postfix + dovecot.

**Comment by CIPop** [comment]
@MattAfflek Thanks for the details!

We'll try to repro this locally. Meanwhile, please collect all SystemNet ETW logs by following guidance I've just submitted for PR (#5532), available [here](https://github.com/CIPop/corefx/blob/logDocs/Documentation/debugging/windows-instructions.md).

Please include the following (all System.Net* production traces) in your providers.txt file:

```
"{99e4576b-9d7e-585f-8b32-0ac3082f2282}"
"{501a994a-eb63-5415-9af1-1b031260f16c}"
"{e03c0352-f9c9-56ff-0ea7-b94ba8cabc6b}"
"{066c0e27-a02d-5a98-9a4d-078cc3b1a896}"
"{bdd9a83e-1929-5482-0d73-2fe5e1c0e16d}"
```

**Comment by MattAfflek** [comment]
@CIPop 
I placed this values in providers.txt file.
I collected log using "Trace multiple providers" guidance.
But this log seems like useless.
[sn.zip](https://github.com/dotnet/corefx/files/98855/sn.zip)

**Comment by CIPop** [comment]
@MattAfflek Opening the ETL file I see no traces recorded.
Which builds of CoreFX binaries are you using? (Only CoreFX latest supports ETW tracing.)

**Comment by CIPop** [comment]
@MattAfflek Looking at the code, the failure originated from one of the previous calls that created the `ProtocolToken` object. There are 4 possibilities and unfortunately the call is not on the stack.
I'm closing this for now given that the API in question isn't supported by the contract. If you can submit a PR or a [Git Gist](https://gist.github.com/) with sample code, I can try to repro again.
