### ISSUE TITLE
Desktop: Tests under "System.Threading.Tasks.Tests.UnwrapTests" failed with "Xunit.Sdk.SameException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18550]
Failed tests: 
 System.Threading.Tasks.Tests.UnwrapTests.NonGeneric_Completed_Completed
 System.Threading.Tasks.Tests.UnwrapTests.Generic_Completed_Completed

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/lastCompletedBuild/consoleText

~~~
System.Threading.Tasks.Tests.UnwrapTests.NonGeneric_Completed_Completed(inner: Task { Status = RanToCompletion }) [FAIL]
        Assert.Same() Failure
        Expected: Task { Status = RanToCompletion }
        Actual:   Task<System.Threading.Tasks.TaskExtensions+VoidResult> { Status = RanToCompletion }
        Stack Trace:
          D:\j\workspace\outerloop_net---903ddde6\src\System.Threading.Tasks\tests\UnwrapTests.cs(33,0): 
at System.Threading.Tasks.Tests.UnwrapTests.NonGeneric_Completed_Completed(Task inner)

System.Threading.Tasks.Tests.UnwrapTests.Generic_Completed_Completed(inner: Task<string> { Status = RanToCompletion }) [FAIL]
        Assert.Same() Failure
        Expected: Task<string> { Status = RanToCompletion } (System.Threading.Tasks.Task`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]])
        Actual:   Task<string> { Status = RanToCompletion } (System.Threading.Tasks.UnwrapPromise`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]])
        Stack Trace:
          D:\j\workspace\outerloop_net---903ddde6\src\System.Threading.Tasks\tests\UnwrapTests.cs(48,0): 
at System.Threading.Tasks.Tests.UnwrapTests.Generic_Completed_Completed(Task`1 inner)
~~~

**Comment by stephentoub** [comment]
This was an improvement in .NET Core, an added optimization that the test is checking for.  The test can be disabled on .NET Framework.
