### ISSUE TITLE
System.Tests.GCTests.LatencyRoundtrips_LowLatency(value: SustainedLowLatency) failed

### ISSUE THREAD

**Issue by shimingsg** [dotnet/corefx#18606]
this test failed when **set TestGCStressLevel=2**,  error message in testresult.xml as following

<test name="System.Tests.GCTests.LatencyRoundtrips_LowLatency(value: SustainedLowLatency)" type="System.Tests.GCTests" method="LatencyRoundtrips_LowLatency" time="0.2391149" result="Fail">
        <traits>
          <trait name="category" value="nonlinuxtests" />
          <trait name="category" value="nonosxtests" />
          <trait name="category" value="nonfreebsdtests" />
          <trait name="category" value="nonnetbsdtests" />
        </traits>
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: SustainedLowLatency\r\nActual:   Batch]]></message>
          <stack-trace><![CDATA[   at System.Tests.GCTests.LatencyRoundtrips(GCLatencyMode value) in F:\repos\corefx\src\System.Runtime\tests\System\GCTests.cs:line 406
   at System.Tests.GCTests.LatencyRoundtrips_LowLatency(GCLatencyMode value) in F:\repos\corefx\src\System.Runtime\tests\System\GCTests.cs:line 419]]></stack-trace>
        </failure>
      </test>

**Comment by danmosemsft** [comment]
```
      <test name="System.Tests.GCTests.LatencyRoundtrips_LowLatency(value: SustainedLowLatency)" type="System.Tests.GCTests" method="LatencyRoundtrips_LowLatency" time="0.2391149" result="Fail">
        <traits>
          <trait name="category" value="nonlinuxtests" />
          <trait name="category" value="nonosxtests" />
          <trait name="category" value="nonfreebsdtests" />
          <trait name="category" value="nonnetbsdtests" />
        </traits>
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: SustainedLowLatency\r\nActual:   Batch]]></message>
          <stack-trace><![CDATA[   at System.Tests.GCTests.LatencyRoundtrips(GCLatencyMode value) in F:\repos\corefx\src\System.Runtime\tests\System\GCTests.cs:line 406
   at System.Tests.GCTests.LatencyRoundtrips_LowLatency(GCLatencyMode value) in F:\repos\corefx\src\System.Runtime\tests\System\GCTests.cs:line 419]]></stack-trace>
        </failure>
      </test>
```

**Comment by danmosemsft** [comment]
@swgillespie I'm guessing this test is expected to fail when gcstress is 2? If so is there some check we can do in the test so it doesn't? Worst case, check whether COMPLUS_GCStress is set, I guess.

**Comment by swgillespie** [comment]
@danmosemsft Yeah, i'd imagine that this test would fail if GCStress is inducing GCs. We don't have anything like [this](https://github.com/dotnet/coreclr/blob/master/tests/src/GC/Scenarios/FinalizeTimeout/FinalizeTimeout.csproj#L10) for CoreFX, do we?

**Comment by danmosemsft** [comment]
We don't. Also that would assume they're in their own assembly. OK, I'll just ignore the error for now.
