### ISSUE TITLE
System.Net.HttpListenerException : An operation was attempted on a nonexistent network connection with GCStress

### ISSUE THREAD

**Issue by shimingsg** [dotnet/corefx#18664]
Test failed in System.Net.HttpListener.Tests.dll, the test output log as following:

set COMPlus_GCStress=3
set XUNIT_PERFORMANCE_MIN_ITERATION=1
set XUNIT_PERFORMANCE_MAX_ITERATION=1
call F:\repos\corefx\bin\testhost\netcoreapp-Windows_NT-Debug-x64\\dotnet.exe xunit.console.netcore.exe System.Net.HttpListener.Tests.dll  -xml testResults.xml -notrait category=nonnetcoreapptests  -notrait category=failing -notrait category=nonwindowstests
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Net.HttpListener.Tests
Discovered:  System.Net.HttpListener.Tests
Starting:    System.Net.HttpListener.Tests
   **System.Net.Tests.HttpRequestStreamTests.Read_LargeLengthAsynchronous_Success(transferEncodingChunked: True) [FAIL]**
      System.Net.HttpListenerException : An operation was attempted on a nonexistent network connection
      Stack Trace:
         F:\repos\corefx\src\System.Net.HttpListener\src\System\Net\Windows\HttpRequestStream.Windows.cs(318,0): at System.Net.HttpRequestStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
            at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
            at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
            at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
            at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
            at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
         F:\repos\corefx\src\System.Net.HttpListener\tests\HttpRequestStreamTests.cs(149,0): at System.Net.Tests.HttpRequestStreamTests.<Read_LargeLengthAsynchronous_Success>d__7.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   **System.Net.Tests.HttpRequestStreamTests.Read_LargeLengthAsynchronous_Success(transferEncodingChunked: False) [FAIL]**
      System.Net.HttpListenerException : An operation was attempted on a nonexistent network connection
      Stack Trace:
         F:\repos\corefx\src\System.Net.HttpListener\src\System\Net\Windows\HttpRequestStream.Windows.cs(318,0): at System.Net.HttpRequestStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
            at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
            at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
            at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
            at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
            at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
         F:\repos\corefx\src\System.Net.HttpListener\tests\HttpRequestStreamTests.cs(149,0): at System.Net.Tests.HttpRequestStreamTests.<Read_LargeLengthAsynchronous_Success>d__7.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   **System.Net.Tests.HttpRequestStreamTests.Read_LargeLengthSynchronous_Success(transferEncodingChunked: True) [FAIL]**
      System.Net.HttpListenerException : An operation was attempted on a nonexistent network connection
      Stack Trace:
         F:\repos\corefx\src\System.Net.HttpListener\src\System\Net\Windows\HttpRequestStream.Windows.cs(195,0): at System.Net.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 size)
         F:\repos\corefx\src\System.Net.HttpListener\tests\HttpRequestStreamTests.cs(193,0): at System.Net.Tests.HttpRequestStreamTests.<Read_LargeLengthSynchronous_Success>d__8.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   **System.Net.Tests.HttpRequestStreamTests.Read_LargeLengthSynchronous_Success(transferEncodingChunked: False) [FAIL]**
      System.Net.HttpListenerException : An operation was attempted on a nonexistent network connection
      Stack Trace:
         F:\repos\corefx\src\System.Net.HttpListener\src\System\Net\Windows\HttpRequestStream.Windows.cs(195,0): at System.Net.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 size)
         F:\repos\corefx\src\System.Net.HttpListener\tests\HttpRequestStreamTests.cs(193,0): at System.Net.Tests.HttpRequestStreamTests.<Read_LargeLengthSynchronous_Success>d__8.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   **System.Net.Tests.HttpRequestStreamTests.Read_FullLengthSynchronous_Success(transferEncodingChunked: True, text: \"\") [FAIL]**
      System.Net.Http.HttpRequestException : An error occurred while sending the request.
      ---- System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response
      Stack Trace:
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
         F:\repos\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(462,0): at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         F:\repos\corefx\src\System.Net.HttpListener\tests\HttpRequestStreamTests.cs(116,0): at System.Net.Tests.HttpRequestStreamTests.<Read_FullLengthSynchronous_Success>d__6.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         ----- Inner Stack Trace -----
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         F:\repos\corefx\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs(62,0): at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
         F:\repos\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(863,0): at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
Finished:    System.Net.HttpListener.Tests

=== TEST EXECUTION SUMMARY ===
   System.Net.HttpListener.Tests  Total: 104, Errors: 0, Failed: 5, Skipped: 0, Time: 1055.777s
Finished running tests.  End time= 0:33:32.67, Exit code = 1

**Comment by danmosemsft** [comment]
This seems unlikely to be GC related but either due to the extreme slowness of the tests in this mode or some unrelated flaky problem.

**Comment by karelz** [comment]
Legacy APIs, potentially reliability, but most likely same on Desktop.

**Comment by karelz** [comment]
Triage: Old issue. We have plans to do brand new stress for .NET Core -- @eiriktsarpalis please add these kind of runs on your backlog.

Closing as non-actionable. If it is a real problem, we will discover it in the new stress runs.
