### ISSUE TITLE
IsolatedStorage.MaximumSize throws when it doesn't on 4.6

### ISSUE THREAD

**Issue by billwert** [dotnet/corefx#18705]
The .NET Core implementation of IsolatedStorage does not initialize m_Quota as the desktop implementation does, resulting in code like this throwing instead of working:

```csharp
var store = System.IO.IsolatedStorage.IsolatedStorageFile.GetUserStoreForAssembly();
ulong size = store.MaximumSize;
```

**Comment by sepidehMS** [comment]
@billwert What kind of exception are you getting? I don't hit any issues with this piece of code.

**Comment by billwert** [comment]
```console
PS E:\work\scratch\downloadall>dotnet run

Unhandled Exception: System.InvalidOperationException: MaximumSize is not defined for this store. An operation was performed that requires access to MaximumSize. Stores obtained using enumeration APIs do not have a well-defined MaximumSize, since partial evidence is used to open the store.
   at System.IO.IsolatedStorage.IsolatedStorage.get_MaximumSize()
   at downloadall.Program.Main(String[] args) in E:\work\scratch\downloadall\Program.cs:line 10
```

**Comment by ianhays** [comment]
@billwert are you running on the latest binaries? MaximumSize was overridden 20 days ago by @AtsushiKan in https://github.com/dotnet/corefx/pull/17965 to always return long.MaxValue.

**Comment by billwert** [comment]
@ianhays ah, I'm not. Cool.
