### ISSUE TITLE
SqlClient fails to conenct to Sql Server 2014 on Ubuntu 16.04 LTS and CentOS

### ISSUE THREAD

**Issue by apoorvmalhotra** [dotnet/corefx#18793]
When my DotNetCore app running on Dotnet core 1.0.1 tries to connect to Sql Server 2014 (SP2 with Cumulative Update 3 installed), I get the following exception

_System.Data.SqlClient.SqlException: A connection was successfully established with the server, but then an error occurred during the login process. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.IO.IOException: Unable to write data to the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Data.SqlClient.SNI.SslOverTdsStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslStreamInternal.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStreamInternal.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Data.SqlClient.SNI.SNITCPHandle.Send(SNIPacket packet)
   --- End of inner exception stack trace ---_

The same app can connect to the Sql Server when running on a Mac. 
The app can also connect when running inside a docker container on Mac. I used _microsoft/aspnetcore:1.1.1_ as the base image for the docker container. 
However, on Ubuntu on CentOS based host systems, the same app running within docker fails to connect to the Sql Server.

**Comment by venkatmarella** [comment]
We have the same probelm, did you resolve this @apoorvmalhotra ?

**Comment by danmosemsft** [comment]
Dupe of https://github.com/dotnet/corefx/issues/29620?
