### ISSUE TITLE
ConcurrentDictionary OnDeserialized exception

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#18893]
With .NET Core 2.0 preview, `ConcurrentDictionary` is throwing an error when `OnDeserialized` is called.

I would expect `ConcurrentDictionary` either to not throw an error, or throw a better error than `NullReferenceException`.

See https://github.com/JamesNK/Newtonsoft.Json/issues/1294 for more details.

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Concurrent.ConcurrentDictionary`2.InitializeFromCollection(IEnumerable`1 collection)
   at System.Collections.Concurrent.ConcurrentDictionary`2.OnDeserialized(StreamingContext context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at Newtonsoft.Json.Serialization.JsonContract.InvokeOnDeserialized(Object o, StreamingContext context)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at test.Program.Main()
```

**Comment by danmosemsft** [comment]
I didn't try it but it seems deserializing will allways throw NRE since `_serializationArray` is not assigned when deserializing.
``` c#
        /// <summary>Construct the dictionary from a previously serialized one</summary>
        [OnDeserialized]
        private void OnDeserialized(StreamingContext context)
        {
            KeyValuePair<TKey, TValue>[] array = _serializationArray;
...            
InitializeFromCollection(array);
        }
```

**Comment by stephentoub** [comment]
@JamesNK, did your serialization code call OnSerializing when serializing the dictionary?  The OnSerializing/OnSerialized/OnDeserializing/OnDeserialized methods need to be used in tandem, and ConcurrentDictionary's OnDeserialized during deserialization expects that OnSerializing was used during serialization.

**Comment by JamesNK** [comment]
I'm pretty sure OnSerializing is being called when the JSON is written but that has no effect on the JSON that Json.NET produces.

**Comment by stephentoub** [comment]
>  but that has no effect on the JSON that Json.NET produces.

The OnSerializing method configures the state of the dictionary to prepare it to be serialized, namely by initializing the _serializationArray to an array containing all of the data from the dictionary; then when a formatter (e.g. BinaryFormatter) serializes it, that _serializationArray gets serialized out as part of the data structure.  Upon deserialization, OnDeserialized looks at that _serializationArray that was then deserialized by the formatter as an array, and rehydrates the rest of the dictionary from it and nulls it out.  So OnSerializing should absolutely have an effect on the JSON produced, because it's what sets the array that contains all of the data to be serialized, and if it's coming back during deserialization as null, that suggests this roundtrip isn't appropriately happening.

**Comment by JamesNK** [comment]
> that suggests this roundtrip isn't appropriately happening

OnSerializing/OnDeserialized are assuming that every serializer will serialize and populate the internal fields, and anyone who doesn't should get a null reference error.

Are these methods well designed and should be changed?

**Comment by stephentoub** [comment]
> Are you telling me these methods well designed and shouldn't be changed?

I didn't design the protocol nor am I defending it.  I'm saying that there's a strict requirement about how such methods are used, and that any time code attempts to access private members via reflection, it better either a) expect things to blow up, or b) exactly follow the convention for how those members are to be used.  In this case it looks like Json.NET is doing neither of those things.

**Comment by JamesNK** [comment]
Json.NET isn't seeking out a private method and calling it for fun. It is being called because it OnDeserializedAttribute on it which I assumed was a generic way of signaling that this method should be called during serialization/deserialization. There is no flag on the attribute saying that you should only call this if you're BinarySerializer, and there is no indication to outside observers that you must follow this secret contract.

Are you happy with other serializers that aren't BinarySerializer erroring on ConcurrentDictionary?

**Comment by stephentoub** [comment]
> which I assumed was a generic way of signaling that this method should be called during serialization/deserialization

It is, just as OnSerializing is a way of signaling that method should be called during serialization, OnSerialized after serialization, and OnDeserializing during deserialization.  They all go together and are not intended to be used piecemeal: if a type that is [Serializable] uses these attributes, they are part and parcel of its serialization implementation and must be used.  Same goes for IDeserializationCallback, ISerializable, etc.

> Are you happy with other serializers that aren't BinarySerializer erroring on ConcurrentDictionary?

In general the runtime serialization support in .NET isn't great.  That's a large part of why it wasn't included in .NET Core 1.x, and why we only brought it back to .NET Core 2.0 to help with moving .NET code to core.  We do not expect lots of custom serializers to be written, and those that do must implement it wholesale if they expect it to work correctly.

I'm not sure what you're hoping for here.  ConcurrentDictionary relies on this serialization scheme.  The best that could be done within that scheme is throwing a different exception, which still isn't going to help your situation but which I already said I'd be fine with if someone wanted to submit a PR that at least made the exception message more helpful so that library authors like yourself can more easily understand the problem and fix it to use the types correctly.  If Json.NET wants to be able to serialize arbitrary [Serializable] types, it needs factor in the full set of possibilities.  I agree that's hard, not well documented, etc., but nevertheless, the system doesn't work piecemeal.

**Comment by JamesNK** [comment]
Check whether `_serializationArray` is null, and if it is then skip the logic in OnDeserialized. Then other serializers could call it without an error.

Putting in a hack to avoid ConcurrentDictionary erroring isn't so simple now that it lives in its own NuGet package. I don't want to reference an NuGet package just to test the type, and testing the type via the name makes it a hack on another hack.

**Comment by stephentoub** [comment]
> Check whether _serializationArray is null, and if it is then skip the logic in OnDeserialized. Then other serializers could call it without an error.

They would experience an error, it just wouldn't be an exception: the data would be invalid.

**Comment by stephentoub** [comment]
> The data is being deserialized via IDictionary

Serialized you mean?  If it's just being written out via enumerating the contents of the IDictionary and serializing out the results, then it's not using the dictionary's serialization implementation, and OnDeserialized shouldn't be used for deserialization either since OnSerializing wasn't used for serialization.
