### ISSUE TITLE
SqlClient: Exception is thrown with connection pooling with latest package (4.4.0-preview1)

### ISSUE THREAD

**Issue by smitpatel** [dotnet/corefx#19057]
Working on a repro project.

https://github.com/aspnet/EntityFramework/tree/sqlclient
Clone the branch, run `build.cmd /t:Compile`
Run test\EFCore.SqlServer.FunctionalTests on netcoreapp2.0

Stack traces
Exception 1 happens when calling 'ClearAllPools`
```
Failed   Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.SqlServerDatabaseCreatorEnsureCreatedTest.EnsureCreated_can_create_physical_database_with_filename_and_s
chema
Error Message:
 System.IO.IOException : Pipe is broken.
Stack Trace:
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.Flush()
   at System.Net.Security.AuthenticatedStream.Dispose(Boolean disposing)
   at System.Net.Security.SslStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.Data.SqlClient.SNI.SNINpHandle.Dispose()
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.Dispose()
   at System.Data.SqlClient.TdsParser.Disconnect()
   at System.Data.SqlClient.SqlInternalConnectionTds.Dispose()
   at System.Data.ProviderBase.DbConnectionPool.DestroyObject(DbConnectionInternal obj)
   at System.Data.ProviderBase.DbConnectionPool.Clear()
   at System.Data.ProviderBase.DbConnectionFactory.QueuePoolForRelease(DbConnectionPool pool, Boolean clearing)
   at System.Data.ProviderBase.DbConnectionPoolGroup.Clear()
   at System.Data.ProviderBase.DbConnectionFactory.ClearAllPools()
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.Utilities.SqlServerTestStore.DeleteDatabase(String name) in D:\MergeBranch\EntityFramework\test\EFCore.SqlS
erver.FunctionalTests\Utilities\SqlServerTestStore.cs:line 267
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.Utilities.SqlServerTestStore.Dispose() in D:\MergeBranch\EntityFramework\test\EFCore.SqlServer.FunctionalTe
sts\Utilities\SqlServerTestStore.cs:line 445
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.SqlServerDatabaseCreatorEnsureCreatedTest.<>c.<<EnsureCreated_can_create_physical_database_and_schema_test>
b__9_0>d.MoveNext() in D:\MergeBranch\EntityFramework\test\EFCore.SqlServer.FunctionalTests\SqlServerDatabaseCreatorTest.cs:line 320
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__7`1.<<ExecuteAsync>b__7_0>d.MoveNext() in D:\MergeBranch\EntityFramework\src\EFCore\Extensions\Execu
tionStrategyExtensions.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.SqlServerDatabaseCreatorEnsureCreatedTest.<EnsureCreated_can_create_physical_database_with_filename_and_sch
ema>d__6.MoveNext() in D:\MergeBranch\EntityFramework\test\EFCore.SqlServer.FunctionalTests\SqlServerDatabaseCreatorTest.cs:line 294
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
Another one with same exception happens when calling `OpenAsync`
```
Failed   Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.SqlServerDatabaseCreatorEnsureCreatedTest.EnsureCreatedAsync_can_create_physical_database_and_schema
Error Message:
 System.IO.IOException : Pipe is broken.
Stack Trace:
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.Flush()
   at System.Net.Security.AuthenticatedStream.Dispose(Boolean disposing)
   at System.Net.Security.SslStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.Data.SqlClient.SNI.SNINpHandle.Dispose()
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.Dispose()
   at System.Data.SqlClient.TdsParser.Disconnect()
   at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, Boolean redirectedUserInstance)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirec
tedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPoo
l pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPool
Key poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneChe
ckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__36.MoveNext() in D:\MergeBranch\EntityFramework\src\EFCore.Relational\Storage\RelationalCo
nnection.cs:line 410
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext() in D:\MergeBranch\EntityFramework\src
\EFCore.SqlServer\Storage\Internal\SqlServerDatabaseCreator.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.<EnsureCreatedAsync>d__18.MoveNext() in D:\MergeBranch\EntityFramework\src\EFCore.Relational\Storag
e\RelationalDatabaseCreator.cs:line 244
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.SqlServerDatabaseCreatorEnsureCreatedTest.<RunDatabaseCreationTest>d__10.MoveNext() in D:\MergeBranch\Entit
yFramework\test\EFCore.SqlServer.FunctionalTests\SqlServerDatabaseCreatorTest.cs:line 334
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.SqlServerDatabaseCreatorEnsureCreatedTest.<>c.<<EnsureCreated_can_create_physical_database_and_schema_test>
b__9_0>d.MoveNext() in D:\MergeBranch\EntityFramework\test\EFCore.SqlServer.FunctionalTests\SqlServerDatabaseCreatorTest.cs:line 319
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__7`1.<<ExecuteAsync>b__7_0>d.MoveNext() in D:\MergeBranch\EntityFramework\src\EFCore\Extensions\Execu
tionStrategyExtensions.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.SqlServerDatabaseCreatorEnsureCreatedTest.<EnsureCreatedAsync_can_create_physical_database_and_schema>d__7.
MoveNext() in D:\MergeBranch\EntityFramework\test\EFCore.SqlServer.FunctionalTests\SqlServerDatabaseCreatorTest.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:01:36.8622906]     Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.SqlServerDatabaseCreatorEnsureDeletedTest.EnsureDeletedAsync_will_delete_databas
e_with_opened_connections [FAIL]
```

MARS = true in both cases.
Using package System.Data.SqlClient 4.4.0-preview1-25227-04
Dotnet 
```
Product Information:
 Version:            2.0.0-preview1-005861
 Commit SHA-1 hash:  e0c0075ccd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\smpatel\.dotnet\x64\sdk\2.0.0-preview1-005861\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002088-00
  Build    : e264d929481c1713687bc79e862bae275861981c
```

**Comment by smitpatel** [comment]
@corivera @saurabh500

**Comment by smitpatel** [comment]
Exception happens with MARS true/false either.
It works fine when using native code via app context switch.

**Comment by smitpatel** [comment]
Another stack trace from diagnostic repo. This test is async but it uses sync code path in SqlClient
```
Failed   Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.Tests.DatabaseErrorPageMiddlewareTest.Customize_migrations_end_point
Error Message:
 System.IO.IOException : Pipe is broken.
Stack Trace:
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, TState state)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureDeleted()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.Tests.SqlServerTestStore.EnsureDeleted()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.Tests.SqlServerTestStore.Dispose()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.Tests.DatabaseErrorPageMiddlewareTest.<Customize_migrations_end_point>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Point to mention, all these happen only when running tests in parallel (which is default in asp.net)

**Comment by Eilon** [comment]
Is this bug good to be closed now?

**Comment by saurabh500** [comment]
@corivera my understanding is that you have ported the fix to relevant branches. Please close this bug if that's the case

**Comment by corivera** [comment]
Ported to release/2.0.0 with https://github.com/dotnet/corefx/commit/cd0ba32c82870e95ae67112580c8e98749fd450b
