### ISSUE TITLE
Desktop: System.Diagnostics.Tests.ProcessTests.HandleCountChanges failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19076]
Failed test: System.Diagnostics.Tests.ProcessTests.HandleCountChanges

Configuration: outerloop_netfx_windows_nt_debug

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/34/testReport/System.Diagnostics.Tests/ProcessTests/HandleCountChanges/

MESSAGE:
~~~
Assert.Equal() Failure
    Expected: 42
    Actual: -532462766
~~~
STACK TRACE:
~~~
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() 
in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Diagnostics\RemoteExecutorTestBase.cs:line 188 
at System.Diagnostics.Tests.ProcessTests.HandleCountChanges() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.Process\tests\ProcessTests.cs:line 1199
~~~

**Comment by danmosemsft** [comment]
```
  Exception from RemoteExecutorConsoleApp(System.Diagnostics.Process.Tests, Version=4.2.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb, System.Diagnostics.Tests.ProcessTests, <HandleCountChanges>b__99_0):
  Assembly: System.Diagnostics.Process.Tests, Version=4.2.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
  Type: System.Diagnostics.Tests.ProcessTests
  Method: Int32 <HandleCountChanges>b__99_0()
  Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.TrueException: Assert.True() Failure
  Expected: True
  Actual:   False
     at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\BooleanAsserts.cs:line 90
     at System.Diagnostics.Tests.ProcessTests.<HandleCountChanges>b__99_0() in D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.Process\tests\ProcessTests.cs:line 1214
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
     at RemoteExecutorConsoleApp.Program.Main(String[] args) in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Diagnostics\RemoteExecutorConsoleApp\RemoteExecutorConsoleApp.cs:line 55
  
  Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.TrueException: Assert.True() Failure
  Expected: True
  Actual:   False
     at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\BooleanAsserts.cs:line 90
     at System.Diagnostics.Tests.ProcessTests.<HandleCountChanges>b__99_0() in D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.Process\tests\ProcessTests.cs:line 1214
     --- End of inner exception stack trace ---
     at RemoteExecutorConsoleApp.Program.Main(String[] args) in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Diagnostics\RemoteExecutorConsoleApp\RemoteExecutorConsoleApp.cs:line 67
      System.Diagnostics.Tests.ProcessTests.HandleCountChanges [FAIL]
        Assert.Equal() Failure
        Expected: 42
        Actual:   -532462766
        Stack Trace:
          D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Diagnostics\RemoteExecutorTestBase.cs(188,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
          D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.Process\tests\ProcessTests.cs(1199,0): at System.Diagnostics.Tests.ProcessTests.HandleCountChanges()
```

**Comment by danmosemsft** [comment]
This does not repro for me when I run the code standalone. It consistently drops handlecount by 3.

**Comment by stephentoub** [comment]
The test isn't particularly robust.  It's expecting that the only handles that are created/closed are the ones coming from the test itself, but something else in the runtime may happen to do so at just the wrong time.

**Comment by danmosemsft** [comment]
I'll disable for desktop as it doesn't seem particularly important to robustify for that. If it start being unreliable on Corewe can fiddle with creating/disposing 100 handles instead.
