### ISSUE TITLE
GetFolderPath_Windows tests ~all fail on Nano

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#19110]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170428.02/workItem/System.Runtime.Extensions.Tests 

eg 
```
Assert.Equal() Failure\r\n                                 ? (pos 40)\r\nExpected: ···config\\systemprofile\r\nActual:   ···config\\systemprofile\\AppData\\Local\\Microsoft\\Windows\\History\r\n                                 ? (pos 40)
Stack Trace :
   at System.Tests.EnvironmentTests.GetFolderPath_Windows(SpecialFolder folder)
```
need fixing.

**Comment by danmosemsft** [comment]
What we return is apparenlty not matching what SHGetFolderPathW returns on Nano

**Comment by danmosemsft** [comment]
Same as https://github.com/dotnet/corefx/issues/19221,`SHGetKnownFolderPath` doesn't work on Nano.

**Comment by danmosemsft** [comment]
Here's what I get for each folder. Environment.GetFolderPath (from ShGetKnownFolderPath) is mostly blank, sometimes reasonable. ShGetFolderPath (what the test checks) is either blank or just the user profile folder. Desktop for both of these is the 3rd column

```
|                           |                                                         |                      |                                                                                            | 
|---------------------------|---------------------------------------------------------|----------------------|--------------------------------------------------------------------------------------------| 
| Environment.SpecialFolder | NANO Environment.GetFolderPath  | NANO SHGetFolderPath | DESKTOP                                                                                    | 
| Desktop                   |                                                         |                      | C:\Users\myuser\Desktop                                                                    | 
| Programs                  |                                                         |                      | C:\Users\myuser\AppData\Roaming\Microsoft\Windows\Start Menu\Programs                      | 
| MyDocuments               |                                                         |                      | C:\Users\myuser\Documents                                                                  | 
| MyDocuments               |                                                         |                      | C:\Users\myuser\Documents                                                                  | 
| Favorites                 |                                                         |                      | C:\Users\myuser\Favorites                                                                  | 
| Startup                   |                                                         |                      | C:\Users\myuser\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup              | 
| Recent                    |                                                         | C:\Users\myuser      | C:\Users\myuser\AppData\Roaming\Microsoft\Windows\Recent                                   | 
| SendTo                    |                                                         | C:\Users\myuser      | C:\Users\myuser\AppData\Roaming\Microsoft\Windows\SendTo                                   | 
| StartMenu                 |                                                         | C:\Users\myuser      | C:\Users\myuser\AppData\Roaming\Microsoft\Windows\Start Menu                               | 
| MyMusic                   |                                                         | C:\Users\myuser      | C:\Users\myuser\Music                                                                      | 
| MyVideos                  |                                                         | C:\Users\myuser      | C:\Users\myuser\Videos                                                                     | 
| DesktopDirectory          |                                                         |                      | C:\Users\myuser\Desktop                                                                    | 
| MyComputer                |                                                         |                      |                                                                                            | 
| NetworkShortcuts          |                                                         |                      | C:\Users\myuser\AppData\Roaming\Microsoft\Windows\Network Shortcuts                        | 
| Fonts                     |                                                         |                      | C:\WINDOWS\Fonts                                                                           | 
| Templates                 |                                                         |                      | C:\Users\myuser\AppData\Roaming\Microsoft\Windows\Templates                                | 
| CommonStartMenu           |                                                         |                      | C:\ProgramData\Microsoft\Windows\Start Menu                                                | 
| CommonPrograms            |                                                         |                      | C:\ProgramData\Microsoft\Windows\Start Menu\Programs                                       | 
| CommonStartup             |                                                         | C:\Users\myuser      | C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup                               | 
| CommonDesktopDirectory    |                                                         | C:\Users\myuser      | C:\Users\Public\Desktop                                                                    | 
| ApplicationData           |                                                         | C:\Users\myuser      | C:\Users\myuser\AppData\Roaming                                                            | 
| PrinterShortcuts          |                                                         | C:\Users\myuser      |                                                                                            | 
| LocalApplicationData      | C:\Users\myuser\AppData\Local                           | C:\Users\myuser      | C:\Users\myuser\AppData\Local                                                              | 
| InternetCache             | C:\Users\myuser\AppData\Local\Temporary Internet Files  | C:\Users\myuser      | C:\Users\myuser\AppData\Local\Microsoft\Windows\INetCache                                  | 
| Cookies                   | C:\Users\myuser\Cookies                                 | C:\Users\myuser      | C:\Users\myuser\AppData\Local\Microsoft\Windows\INetCookies                                | 
| History                   | C:\Users\myuser\AppData\Local\Microsoft\Windows\History | C:\Users\myuser      | C:\Users\myuser\AppData\Local\Microsoft\Windows\History                                    | 
| CommonApplicationData     | C:\ProgramData                                          | C:\Users\myuser      | C:\ProgramData                                                                             | 
| Windows                   |                                                         | C:\Users\myuser      | C:\WINDOWS                                                                                 | 
| System                    |                                                         | C:\Users\myuser      | C:\WINDOWS\system32                                                                        | 
| ProgramFiles              | C:\Program Files                                        | C:\Users\myuser      | C:\Program Files                                                                           | 
| MyPictures                |                                                         | C:\Users\myuser      | D:\Users\myuser\Pictures                                                                   | 
| UserProfile               | C:\Users\myuser                                         | C:\Users\myuser      | C:\Users\myuser                                                                            | 
| SystemX86                 |                                                         | C:\Users\myuser      | C:\WINDOWS\SysWOW64                                                                        | 
| ProgramFilesX86           |                                                         | C:\Users\myuser      | C:\Program Files (x86)                                                                     | 
| CommonProgramFiles        |                                                         | C:\Users\myuser      | C:\Program Files\Common Files                                                              | 
| CommonProgramFilesX86     |                                                         | C:\Users\myuser      | C:\Program Files (x86)\Common Files                                                        | 
| CommonTemplates           |                                                         | C:\Users\myuser      | C:\ProgramData\Microsoft\Windows\Templates                                                 | 
| CommonDocuments           |                                                         | C:\Users\myuser      | C:\Users\Public\Documents                                                                  | 
| CommonAdminTools          |                                                         | C:\Users\myuser      | C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools                  | 
| AdminTools                |                                                         | C:\Users\myuser      | C:\Users\myuser\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Administrative Tools | 
| CommonMusic               |                                                         | C:\Users\myuser      | C:\Users\Public\Music                                                                      | 
| CommonPictures            |                                                         | C:\Users\myuser      | C:\Users\Public\Pictures                                                                   | 
| CommonVideos              |                                                         | C:\Users\myuser      | C:\Users\Public\Videos                                                                     | 
| Resources                 |                                                         | C:\Users\myuser      | C:\WINDOWS\resources                                                                       | 
| LocalizedResources        |                                                         | C:\Users\myuser      |                                                                                            | 
| CommonOemLinks            |                                                         | C:\Users\myuser      |                                                                                            | 
| CDBurning                 |                                                         | C:\Users\myuser      | C:\Users\myuser\AppData\Local\Microsoft\Windows\Burn\Burn                                  | 
```

**Comment by danmosemsft** [comment]
@JeremyKuhne fyi.

**Comment by danmosemsft** [comment]
https://gist.github.com/danmosemsft/2317eac85ba0006add7a41ea73bb35ac

**Comment by danmosemsft** [comment]
It's not fixed, apparently.

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170517.01/workItem/System.Runtime.Extensions.Tests

**Comment by karelz** [comment]
Do we want to fix it in 2.0?

**Comment by Jiayili1** [comment]
This issue failed again, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170519.01/workItem/System.Runtime.Extensions.Tests/analysis/xunit/System.Tests.EnvironmentTests~2FGetFolderPath_Windows(folder:%20CommonStartMenu)

Message:
Assert.NotEqual() Failure
  Expected: Not \"\"
  Actual:   \"\"

Stack Trace:
  at System.Tests.EnvironmentTests.GetFolderPath_Windows(SpecialFolder folder)

**Comment by danmosemsft** [comment]
Likely have to use Environment variables - they cover all the major ones: documents, appdata, etc.

**Comment by danmosemsft** [comment]
It seems to be fixed on IoT and latest nano.
https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20171030.01/workItem/System.Runtime.Extensions.Tests/analysis/xunit/System.Tests.EnvironmentTests~2FGetSystemDirectory

**Comment by TravisEz13** [comment]
@ViktorHofer  This is broken again in the 1709 nanoserver image 

```
 [System.Environment+SpecialFolder]::GetNames([System.Environment+SpecialFolder]) | %{ [System.Environment]::Get
olderPath($_)}

**Comment by ViktorHofer** [comment]
cc @danmosemsft

**Comment by danmosemsft** [comment]
@TravisEz13  are you saying this worked before? As based on my experiments at the top of the page, it never produced anything useful. 

I am not sure why I noted "seems to be fixed" as I see the test is still disabled for Nano. We should probably keep this open to try to find another method (env vars) since clearly folks need it.

I will check with Nano folks about the API.

**Comment by TravisEz13** [comment]
@danmosemsft I'm not saying it worked before.  I was basing the "again" part on the "seems to be fixed" statement.

**Comment by danmosemsft** [comment]
@TravisEz13 ah right. I have an email out...

**Comment by krwq** [comment]
Please reenable when fixing it or leave so comment why it is ok to be disabled when fixing/closing this:
```
System.Runtime.Extensions/tests/System/EnvironmentTests.cs:229:                // https://github.com/dotnet/corefx/issues/19110
```

Reopening it while investigation is pending

**Comment by OnurGumus** [comment]
Any updates on this?

**Comment by danmosemsft** [comment]
@OnurGumus nobody has looked at it. We would welcome a PR 😄
