### ISSUE TITLE
Tests failed: System.Net.Requests.Tests / System.Net.Tests.HttpWebRequestHeaderTest

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19225]
Tests under "System.Net.Requests.Tests" failed to generate the test result.

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170502.01/workItem/System.Net.Requests.Tests/wilogs

~~~
2017-05-02 01:17:30,513: INFO: proc(54): run_and_log_output: Output:   Discovering: System.Net.Requests.Tests
2017-05-02 01:17:30,779: INFO: proc(54): run_and_log_output: Output:   Discovered:  System.Net.Requests.Tests
2017-05-02 01:17:30,795: INFO: proc(54): run_and_log_output: Output:   Starting:    System.Net.Requests.Tests
2017-05-02 01:19:12,552: INFO: proc(54): run_and_log_output: Output:     System.Net.Tests.HttpWebRequestHeaderTest.HttpWebRequest_KeepAlive_CorrectConnectionHeaderSent(keepAlive: null) [FAIL]
2017-05-02 01:19:12,552: INFO: proc(54): run_and_log_output: Output:       System.Net.WebException : The operation has timed out
2017-05-02 01:19:12,552: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-02 01:19:12,569: INFO: proc(54): run_and_log_output: Output:            at System.Net.HttpWebRequest.GetResponse()
2017-05-02 01:19:12,569: INFO: proc(54): run_and_log_output: Output:         E:\A\_work\211\s\corefx\src\System.Net.Requests\tests\HttpWebRequestHeaderTest.cs(253,0): at System.Net.Tests.HttpWebRequestHeaderTest.HttpWebRequest_KeepAlive_CorrectConnectionHeaderSent(Nullable`1 keepAlive)
2017-05-02 01:20:52,540: INFO: proc(54): run_and_log_output: Output:     System.Net.Tests.HttpWebRequestHeaderTest.HttpWebRequest_KeepAlive_CorrectConnectionHeaderSent(keepAlive: False) [FAIL]
2017-05-02 01:20:52,540: INFO: proc(54): run_and_log_output: Output:       System.Net.WebException : The operation has timed out
2017-05-02 01:20:52,540: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-02 01:20:52,540: INFO: proc(54): run_and_log_output: Output:            at System.Net.HttpWebRequest.GetResponse()
2017-05-02 01:20:52,540: INFO: proc(54): run_and_log_output: Output:         E:\A\_work\211\s\corefx\src\System.Net.Requests\tests\HttpWebRequestHeaderTest.cs(253,0): at System.Net.Tests.HttpWebRequestHeaderTest.HttpWebRequest_KeepAlive_CorrectConnectionHeaderSent(Nullable`1 keepAlive)
2017-05-02 01:22:32,558: INFO: proc(54): run_and_log_output: Output:     System.Net.Tests.HttpWebRequestHeaderTest.HttpWebRequest_KeepAlive_CorrectConnectionHeaderSent(keepAlive: True) [FAIL]
2017-05-02 01:22:32,558: INFO: proc(54): run_and_log_output: Output:       System.Net.WebException : The operation has timed out
2017-05-02 01:22:32,558: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-02 01:22:32,558: INFO: proc(54): run_and_log_output: Output:            at System.Net.HttpWebRequest.GetResponse()
2017-05-02 01:22:32,558: INFO: proc(54): run_and_log_output: Output:         E:\A\_work\211\s\corefx\src\System.Net.Requests\tests\HttpWebRequestHeaderTest.cs(253,0): at System.Net.Tests.HttpWebRequestHeaderTest.HttpWebRequest_KeepAlive_CorrectConnectionHeaderSent(Nullable`1 keepAlive)
2017-05-02 01:24:12,622: INFO: proc(54): run_and_log_output: Output:     System.Net.Tests.HttpWebRequestHeaderTest.HttpWebRequest_PreAuthenticateGetSet_Ok [FAIL]
2017-05-02 01:24:12,622: INFO: proc(54): run_and_log_output: Output:       System.Net.WebException : The operation has timed out
2017-05-02 01:24:12,622: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-02 01:24:12,622: INFO: proc(54): run_and_log_output: Output:            at System.Net.HttpWebRequest.GetResponse()
2017-05-02 01:24:12,622: INFO: proc(54): run_and_log_output: Output:         E:\A\_work\211\s\corefx\src\System.Net.Requests\tests\HttpWebRequestHeaderTest.cs(234,0): at System.Net.Tests.HttpWebRequestHeaderTest.HttpWebRequest_PreAuthenticateGetSet_Ok()
~~~

**Comment by Jiayili1** [comment]
Closed issue: https://github.com/dotnet/corefx/issues/18199

**Comment by ViktorHofer** [comment]
> System.Net.WebException: The operation has timed out

Likely a networking issue

**Comment by karelz** [comment]
Why is the test disabled for Desktop?
@stephentoub @danmosemsft

**Comment by stephentoub** [comment]
> Why is the test disabled for Desktop?

I assume because it was failing on desktop and folks are trying to quickly get to a point where we can get a clean desktop run and then work on re-enabling tests?

**Comment by danmosemsft** [comment]
@safern is working to have all remaining desktop failures fixed or disabled before next week so that we can switch on CI protection for it before 2.0 leaves master. It's orthogonal to whether we fix specific failures for 2.0

**Comment by karelz** [comment]
I see, I wasn't aware of the fact that we plan to do regular runs (maybe I just forgot). I like the plan though :)

**Comment by danmosemsft** [comment]
We do runs daily and have for a while. We want to protect a clean state with CI so we never again have to spend a month getting failure rate down.
