### ISSUE TITLE
System.Net.NameResolution.Pal.Tests.GetHostByName_HostName failed with No such device or address

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#19236]
This broke CI
https://ci.dot.net/job/dotnet_corefx/job/master/job/portablelinux_debug_prtest/4495/consoleText
```
  Discovering: System.Net.NameResolution.Pal.Tests
  Discovered:  System.Net.NameResolution.Pal.Tests
  Starting:    System.Net.NameResolution.Pal.Tests
     System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_HostName [FAIL]
        System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address
        Stack Trace:
              at System.Net.NameResolutionPal.GetHostByName(String hostName)
              at System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_HostName()
     System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName [FAIL]
        Assert.Equal() Failure
        Expected: Success
        Actual:   HostNotFound
        Stack Trace:
              at System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName()
  Finished:    System.Net.NameResol
```

**Comment by danmosemsft** [comment]
Note what CI calls Portable Linux is actually RHEL7.2.

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/17878
