### ISSUE TITLE
Tests under "System.Security.Cryptography.Xml.Tests.SignedXmlTest" failed with "Xunit.Sdk.TrueException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19267]
Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/39/consoleText

Failed test:
 System.Security.Cryptography.Xml.Tests.SignedXmlTest.VerifyHMAC_SHA256 
 System.Security.Cryptography.Xml.Tests.SignedXmlTest.VerifyHMAC_MD5
 System.Security.Cryptography.Xml.Tests.SignedXmlTest.VerifyHMAC_SHA512 
 System.Security.Cryptography.Xml.Tests.SignedXmlTest.VerifyHMAC_SHA384

~~~
 System.Security.Cryptography.Xml.Tests.SignedXmlTest.VerifyHMAC_SHA256 [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Xml\tests\SignedXmlTest.cs(1261,0): 
at System.Security.Cryptography.Xml.Tests.SignedXmlTest.VerifyHMAC_SHA256()

System.Security.Cryptography.Xml.Tests.SignedXmlTest.VerifyHMAC_MD5 [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Xml\tests\SignedXmlTest.cs(1363,0): 
at System.Security.Cryptography.Xml.Tests.SignedXmlTest.VerifyHMAC_MD5()

System.Security.Cryptography.Xml.Tests.SignedXmlTest.VerifyHMAC_SHA512 [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Xml\tests\SignedXmlTest.cs(1293,0): 
at System.Security.Cryptography.Xml.Tests.SignedXmlTest.VerifyHMAC_SHA512()

System.Security.Cryptography.Xml.Tests.SignedXmlTest.VerifyHMAC_SHA384 [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Xml\tests\SignedXmlTest.cs(1328,0): 
at System.Security.Cryptography.Xml.Tests.SignedXmlTest.VerifyHMAC_SHA384()
~~~

**Comment by karelz** [comment]
Fixed in #19376
