### ISSUE TITLE
Desktop: System.Security.Cryptography.Xml.Tests.EncryptedXmlTest.DecryptData_CipherReference_InvalidUri failed with "System.ArgumentNullException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19272]
Failed test: System.Security.Cryptography.Xml.Tests.EncryptedXmlTest.DecryptData_CipherReference_InvalidUri

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/39/testReport/System.Security.Cryptography.Xml.Tests/EncryptedXmlTest/DecryptData_CipherReference_InvalidUri/

MESSAGE:
~~~
Assert.Throws() Failure
  Expected: typeof(System.Security.Cryptography.CryptographicException)
  Actual: typeof(System.ArgumentNullException): Value cannot be null.
  Parameter name: evidence
~~~
STACK TRACE:
~~~
at System.Security.SecurityManager.GetStandardSandbox(Evidence evidence) 
at System.Security.Cryptography.Xml.EncryptedXml.DownloadCipherValue(CipherData cipherData, Stream& inputStream, Stream& decInputStream, WebResponse& response) 
at System.Security.Cryptography.Xml.EncryptedXml.GetCipherValue(CipherData cipherData) 
at System.Security.Cryptography.Xml.EncryptedXml.DecryptData(EncryptedData encryptedData, SymmetricAlgorithm symmetricAlgorithm) 
at System.Security.Cryptography.Xml.Tests.EncryptedXmlTest.<>c__DisplayClass48_0.<DecryptData_CipherReference_InvalidUri>b__0() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Xml\tests\EncryptedXmlTest.cs:line 636
~~~

**Comment by krwq** [comment]
need to investigate this one a little deeper.

repro (DecryptData_CipherReference_InvalidUri)
```csharp
            XmlDocument doc = new XmlDocument();
            doc.PreserveWhitespace = true;
            string xml = "<root>  <child>sample</child>   </root>";
            doc.LoadXml(xml);

            using (Aes aes = Aes.Create())
            {
                EncryptedXml exml = new EncryptedXml();
                exml.AddKeyNameMapping("aes", aes);
                EncryptedData ed = exml.Encrypt(doc.DocumentElement, "aes");
                ed.CipherData = new CipherData();
                ed.CipherData.CipherReference = new CipherReference("invaliduri");

                Assert.Throws<CryptographicException>(() => exml.DecryptData(ed, aes));
            }
```

Desktop stack:
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: evidence
   at System.Security.SecurityManager.GetStandardSandbox(Evidence evidence)
   at System.Security.Cryptography.Xml.EncryptedXml.DownloadCipherValue(CipherData cipherData, Stream& inputStream, Stream& decInputStream, WebResponse& response)
   at System.Security.Cryptography.Xml.EncryptedXml.GetCipherValue(CipherData cipherData)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptData(EncryptedData encryptedData, SymmetricAlgorithm symmetricAlgorithm)
```

Corefx stack:
```
        System.Security.Cryptography.CryptographicException : Unable to resolve Uri invaliduri.
        Stack Trace:
           d:\corefx\src\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\EncryptedXml.cs(213,0): at System.Security.Cryptography.Xml.EncryptedXml.GetCipherValue(CipherData cipherData)
           d:\corefx\src\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\EncryptedXml.cs(682,0): at System.Security.Cryptography.Xml.EncryptedXml.DecryptData(EncryptedData encryptedData, SymmetricAlgorithm symmetri
  cAlgorithm)
           d:\corefx\src\System.Security.Cryptography.Xml\tests\EncryptedXmlTest.cs(635,0): at System.Security.Cryptography.Xml.Tests.EncryptedXmlTest.DecryptData_CipherReference_InvalidUri()
```

**Comment by krwq** [comment]
The difference is caused by removing method which would always throw on CoreFx and handling the error correctly (because CAS related constructor `EncryptedXml..ctor(XmlDocument, Evidence)` is missing). Desktop is incorrectly handling the exception as it should check if evidence is not null and throw CryptographicException instead of letting underlying code throw because of null value.

Removed code path:
http://referencesource.microsoft.com/#System.Security/system/security/cryptography/xml/encryptedxml.cs,232 (DownloadCipherValue)
Implementation of removed call: http://referencesource.microsoft.com/#System.Security/system/security/cryptography/xml/encryptedxml.cs,256

Change was introduced by: https://github.com/dotnet/corefx/commit/ac17228d823a07a15fe53069a49fb5e5f35835b7
