### ISSUE TITLE
Fire Issue: System.Net.Socket.Tests failed to generate the test result

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19285]
Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170503.01/workItem/System.Net.Sockets.Tests/wilogs

~~~
2017-05-03 01:44:25,237: INFO: proc(54): run_and_log_output: Output: xUnit.net console test runner (64-bit .NET Core)
2017-05-03 01:44:25,237: INFO: proc(54): run_and_log_output: Output: Copyright (C) 2014 Outercurve Foundation.
2017-05-03 01:44:25,237: INFO: proc(54): run_and_log_output: Output: 
2017-05-03 01:44:25,315: INFO: proc(54): run_and_log_output: Output: Discovering: System.Net.Sockets.Tests
2017-05-03 01:44:25,628: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Net.Sockets.Tests
2017-05-03 01:44:25,957: INFO: proc(54): run_and_log_output: Output: Starting:    System.Net.Sockets.Tests
2017-05-03 01:44:32,112: INFO: proc(54): run_and_log_output: Output: 
2017-05-03 01:44:32,112: INFO: proc(54): run_and_log_output: Output: Unhandled Exception: System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
2017-05-03 01:44:32,112: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
2017-05-03 01:44:32,112: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.Tests.SocketAsyncExtensions.<>c__DisplayClass2_0.<ReceiveAPM>b__0(IAsyncResult asyncResult)
2017-05-03 01:44:32,112: INFO: proc(54): run_and_log_output: Output:    at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
2017-05-03 01:44:32,112: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2017-05-03 01:44:32,112: INFO: proc(54): run_and_log_output: Output:    at System.Net.ContextAwareResult.Complete(IntPtr userToken)
2017-05-03 01:44:32,112: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
2017-05-03 01:44:32,112: INFO: proc(54): run_and_log_output: Output:    at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
2017-05-03 01:44:32,726: INFO: proc(54): run_and_log_output: Output: Finished running tests.  End time= 1:44:32.72, Exit code = -532462766
2017-05-03 01:44:32,726: INFO: proc(58): run_and_log_output: Exit Code: -532462766
2017-05-03 01:44:32,726: ERROR: scriptrunner(82): _main: Error: No exception thrown, but XUnit results not created
2017-05-03 01:44:32,726: ERROR: helix_test_execution(83): report_error: Error running xunit None
~~~

**Comment by karelz** [comment]
@Jiayili1 please let us know if it happens again. This looks like infra issue ...

**Comment by Jiayili1** [comment]
@karelz I will reopen it is it happens again.

**Comment by Jiayili1** [comment]
This issue is repro again, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170523.02/workItem/System.Net.Sockets.Tests/wilogs

~~~
2017-05-22 20:33:16,781: INFO: proc(54): run_and_log_output: Output: xUnit.net console test runner (64-bit .NET Core)
2017-05-22 20:33:16,781: INFO: proc(54): run_and_log_output: Output: Copyright (C) 2014 Outercurve Foundation.
2017-05-22 20:33:16,782: INFO: proc(54): run_and_log_output: Output: 
2017-05-22 20:33:16,870: INFO: proc(54): run_and_log_output: Output: Discovering: System.Net.Sockets.Tests
2017-05-22 20:33:17,145: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Net.Sockets.Tests
2017-05-22 20:33:17,388: INFO: proc(54): run_and_log_output: Output: Starting:    System.Net.Sockets.Tests
2017-05-22 20:33:48,361: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.SendReceiveListener.SendRecvAsync_TcpListener_TcpClient(listenAt: 127.0.0.1) [FAIL]
2017-05-22 20:33:48,362: INFO: proc(54): run_and_log_output: Output:       Time out waiting for serverTask (WaitingForActivation) and clientTask (WaitingForActivation)
2017-05-22 20:33:48,362: INFO: proc(54): run_and_log_output: Output:       Expected: True
2017-05-22 20:33:48,362: INFO: proc(54): run_and_log_output: Output:       Actual:   False
2017-05-22 20:33:48,365: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-22 20:33:48,461: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/29/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs(983,0): at System.Net.Sockets.Tests.SendReceiveListener.SendRecvAsync_TcpListener_TcpClient(IPAddress listenAt)
2017-05-22 20:33:53,010: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.SendReceiveSync.SendRecvPollSync_TcpListener_Socket(listenAt: ::1, pollBeforeOperation: True) [FAIL]
2017-05-22 20:33:53,010: INFO: proc(54): run_and_log_output: Output:       Wait timed out
2017-05-22 20:33:53,010: INFO: proc(54): run_and_log_output: Output:       Expected: True
2017-05-22 20:33:53,010: INFO: proc(54): run_and_log_output: Output:       Actual:   False
2017-05-22 20:33:53,010: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-22 20:33:53,010: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/29/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs(650,0): at System.Net.Sockets.Tests.SendReceive.SendRecvPollSync_TcpListener_Socket(IPAddress listenAt, Boolean pollBeforeOperation)
2017-05-22 20:34:18,513: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.SendReceiveListener.SendRecvAsync_TcpListener_TcpClient(listenAt: ::1) [FAIL]
2017-05-22 20:34:18,514: INFO: proc(54): run_and_log_output: Output:       Time out waiting for serverTask (WaitingForActivation) and clientTask (WaitingForActivation)
2017-05-22 20:34:18,514: INFO: proc(54): run_and_log_output: Output:       Expected: True
2017-05-22 20:34:18,514: INFO: proc(54): run_and_log_output: Output:       Actual:   False
2017-05-22 20:34:18,514: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-22 20:34:18,514: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/29/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs(983,0): at System.Net.Sockets.Tests.SendReceiveListener.SendRecvAsync_TcpListener_TcpClient(IPAddress listenAt)
2017-05-22 20:34:23,164: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.SendReceiveSync.SendRecvPollSync_TcpListener_Socket(listenAt: ::1, pollBeforeOperation: False) [FAIL]
2017-05-22 20:34:23,164: INFO: proc(54): run_and_log_output: Output:       Wait timed out
2017-05-22 20:34:23,164: INFO: proc(54): run_and_log_output: Output:       Expected: True
2017-05-22 20:34:23,164: INFO: proc(54): run_and_log_output: Output:       Actual:   False
2017-05-22 20:34:23,164: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-22 20:34:23,164: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/29/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs(650,0): at System.Net.Sockets.Tests.SendReceive.SendRecvPollSync_TcpListener_Socket(IPAddress listenAt, Boolean pollBeforeOperation)
2017-05-22 20:34:53,228: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.SendReceiveSync.SendRecvPollSync_TcpListener_Socket(listenAt: 127.0.0.1, pollBeforeOperation: True) [FAIL]
2017-05-22 20:34:53,229: INFO: proc(54): run_and_log_output: Output:       Wait timed out
2017-05-22 20:34:53,229: INFO: proc(54): run_and_log_output: Output:       Expected: True
2017-05-22 20:34:53,229: INFO: proc(54): run_and_log_output: Output:       Actual:   False
2017-05-22 20:34:53,229: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-22 20:34:53,229: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/29/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs(650,0): at System.Net.Sockets.Tests.SendReceive.SendRecvPollSync_TcpListener_Socket(IPAddress listenAt, Boolean pollBeforeOperation)
2017-05-22 20:35:23,287: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.SendReceiveSync.SendRecvPollSync_TcpListener_Socket(listenAt: 127.0.0.1, pollBeforeOperation: False) [FAIL]
2017-05-22 20:35:23,288: INFO: proc(54): run_and_log_output: Output:       Wait timed out
2017-05-22 20:35:23,288: INFO: proc(54): run_and_log_output: Output:       Expected: True
2017-05-22 20:35:23,288: INFO: proc(54): run_and_log_output: Output:       Actual:   False
2017-05-22 20:35:23,288: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-22 20:35:23,288: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/29/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs(650,0): at System.Net.Sockets.Tests.SendReceive.SendRecvPollSync_TcpListener_Socket(IPAddress listenAt, Boolean pollBeforeOperation)
2017-05-22 20:35:28,497: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.SelectAndPollTests.SelectRead_Single_Success [FAIL]
2017-05-22 20:35:28,498: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2017-05-22 20:35:28,498: INFO: proc(54): run_and_log_output: Output:       Expected: 1
2017-05-22 20:35:28,498: INFO: proc(54): run_and_log_output: Output:       Actual:   0
2017-05-22 20:35:28,498: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-22 20:35:28,498: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/29/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/SelectAndPollTests.cs(49,0): at System.Net.Sockets.Tests.SelectAndPollTests.SelectRead_Single_Success()
2017-05-22 20:35:33,652: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.SelectAndPollTests.PollRead_Single_Success [FAIL]
2017-05-22 20:35:33,652: INFO: proc(54): run_and_log_output: Output:       Assert.True() Failure
2017-05-22 20:35:33,652: INFO: proc(54): run_and_log_output: Output:       Expected: True
2017-05-22 20:35:33,652: INFO: proc(54): run_and_log_output: Output:       Actual:   False
2017-05-22 20:35:33,652: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-22 20:35:33,652: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/29/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/SelectAndPollTests.cs(285,0): at System.Net.Sockets.Tests.SelectAndPollTests.PollRead_Single_Success()
2017-05-22 20:35:38,809: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.SelectAndPollTests.SelectRead_Multiple_Success [FAIL]
2017-05-22 20:35:38,809: INFO: proc(54): run_and_log_output: Output:       Failed to select both items within allotted time
2017-05-22 20:35:38,809: INFO: proc(54): run_and_log_output: Output:       Expected: True
2017-05-22 20:35:38,809: INFO: proc(54): run_and_log_output: Output:       Actual:   False
2017-05-22 20:35:38,809: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-22 20:35:38,810: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/29/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/SelectAndPollTests.cs(87,0): at System.Net.Sockets.Tests.SelectAndPollTests.SelectRead_Multiple_Success()
2017-05-22 20:35:43,898: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.SelectAndPollTests.SelectRead_Multiple_Mixed [FAIL]
2017-05-22 20:35:43,898: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2017-05-22 20:35:43,898: INFO: proc(54): run_and_log_output: Output:       Expected: 1
2017-05-22 20:35:43,898: INFO: proc(54): run_and_log_output: Output:       Actual:   0
2017-05-22 20:35:43,898: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-22 20:35:43,898: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/29/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/SelectAndPollTests.cs(140,0): at System.Net.Sockets.Tests.SelectAndPollTests.SelectRead_Multiple_Mixed()
2017-05-22 20:35:49,029: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.ConnectExTest.ConnectEx_Success(type: APM) [FAIL]
2017-05-22 20:35:49,030: INFO: proc(54): run_and_log_output: Output:       IPv4: Timed out while waiting for connection
2017-05-22 20:35:49,030: INFO: proc(54): run_and_log_output: Output:       Expected: True
2017-05-22 20:35:49,030: INFO: proc(54): run_and_log_output: Output:       Actual:   False
2017-05-22 20:35:49,030: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-22 20:35:49,030: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/29/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/ConnectExTest.cs(55,0): at System.Net.Sockets.Tests.ConnectExTest.ConnectEx_Success(SocketImplementationType type)
2017-05-22 20:35:54,099: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.ConnectExTest.ConnectEx_Success(type: Async) [FAIL]
2017-05-22 20:35:54,099: INFO: proc(54): run_and_log_output: Output:       IPv4: Timed out while waiting for connection
2017-05-22 20:35:54,099: INFO: proc(54): run_and_log_output: Output:       Expected: True
2017-05-22 20:35:54,099: INFO: proc(54): run_and_log_output: Output:       Actual:   False
2017-05-22 20:35:54,099: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-22 20:35:54,099: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/29/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/ConnectExTest.cs(55,0): at System.Net.Sockets.Tests.ConnectExTest.ConnectEx_Success(SocketImplementationType type)
~~~

**Comment by Jiayili1** [comment]
Failed again: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170614.01/workItem/System.Net.Sockets.Tests/wilogs

**Comment by Jiayili1** [comment]
This issue is still repro, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170616.01/workItem/System.Net.Sockets.Tests/wilogs

**Comment by Jiayili1** [comment]
Failed again: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170621.01/workItem/System.Net.Sockets.Tests/wilogs

OSX and Fedora OS

**Comment by karelz** [comment]
Next time it happens, we need to jump right on it to find out what is happening - @wfurt @Priya91 

Closing.

**Comment by wfurt** [comment]
I think now dumpling should kick in on hang tests @karelz 
That should give us more insight.

**Comment by karelz** [comment]
Yes, that as well.
