### ISSUE TITLE
Desktop: System.Runtime.Extensions.Tests test failed "System.IO.Tests.PathTests.GetDirectoryName"

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#19334]
`System.IO.Tests.PathTests.GetDirectoryName` failed with error: 

```
System.IO.Tests.PathTests.GetDirectoryName(path: "", expected: null) [FAIL]
     System.ArgumentException : The path is not of a legal form.
     Stack Trace:
           at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
         at System.IO.Path.InternalGetDirectoryName(String path)
     D:\repos\corefx\src\System.Runtime.Extensions\tests\System\IO\PathTests.cs(45,0): at System.IO.Tests.PathTests.GetDirectoryName(String path, String expected)
```

There is a difference in behavior here as .Net Core returns null when `Path.GetDirectoryName(string.Empty)` and Desktop throws and `ArgumentException`. 

I've tried it in a ConsoleApp targeting 4.6.2 and it still throws, did this behavior changed in 4.7 or do we have to change .Net Core to throw? 

cc: @JeremyKuhne @ianhays

**Comment by safern** [comment]
So this is a difference in behavior, I've tried with a ConsoleApp targeting 4.7 and it throws the exception.
