### ISSUE TITLE
FirstOrDefault_AggregateException fails

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#19414]
Test failure (two instances) running on my secondary dev box (intermittent):

```
<test name="System.Linq.Parallel.Tests.ParallelQueryCombinationTests.FirstOrDefault_AggregateException(source: ThrowOnFirstEnumeration, operation: Concat-Left:Default)" type="System.Linq.Parallel.Tests.ParallelQueryCombinationTests" method="FirstOrDefault_AggregateException" time="0.0017648" result="Fail">
        <traits>
          <trait name="category" value="outerloop" />
        </traits>
        <failure exception-type="System.AggregateException">
          <message><![CDATA[System.AggregateException : One or more errors occurred. (One or more errors occurred. (Exception of type 'System.Linq.Parallel.Tests.DeliberateTestException' was thrown.)) (Exception of type 'System.Linq.Parallel.Tests.DeliberateTestException' was thrown.)\r\n---- System.Linq.Parallel.Tests.DeliberateTestException : Exception of type 'System.Linq.Parallel.Tests.DeliberateTestException' was thrown.]]></message>
          <stack-trace><![CDATA[   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Scheduling\QueryTaskGroupState.cs:line 133
   at System.Linq.Parallel.SpoolingTask.SpoolStopAndGo[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, SynchronousChannel`1[] channels, TaskScheduler taskScheduler) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Scheduling\SpoolingTask.cs:line 73
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute() in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Merging\DefaultMergeHelper.cs:line 107
   at System.Linq.Parallel.MergeExecutor`1.Execute() in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Merging\MergeExecutor.cs:line 103
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Merging\MergeExecutor.cs:line 92
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\PartitionedStreamMerger.cs:line 61
   at System.Linq.Parallel.FirstQueryOperator`1.WrapHelper[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, QuerySettings settings) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Unary\FirstQueryOperator.cs:line 91
   at System.Linq.Parallel.FirstQueryOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Unary\FirstQueryOperator.cs:line 68
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\UnaryQueryOperator.cs:line 161
   at System.Linq.Parallel.ConcatQueryOperator`1.WrapHelper2[TLeftKey,TRightKey](PartitionedStream`2 leftStreamInc, PartitionedStream`2 rightStreamInc, IPartitionedStreamRecipient`1 outputRecipient) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Binary\ConcatQueryOperator.cs:line 130
   at System.Linq.Parallel.ConcatQueryOperator`1.WrapHelper[TLeftKey,TRightKey](PartitionedStream`2 leftStreamInc, PartitionedStream`2 rightStream, IPartitionedStreamRecipient`1 outputRecipient, QuerySettings settings, Boolean preferStriping) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Binary\ConcatQueryOperator.cs:line 110
   at System.Linq.Parallel.ConcatQueryOperator`1.WrapPartitionedStream[TLeftKey,TRightKey](PartitionedStream`2 leftStream, PartitionedStream`2 rightStream, IPartitionedStreamRecipient`1 outputRecipient, Boolean preferStriping, QuerySettings settings) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Binary\ConcatQueryOperator.cs:line 91
   at System.Linq.Parallel.BinaryQueryOperator`3.BinaryQueryOperatorResults.RightChildResultsRecipient`1.Receive[TRightKey](PartitionedStream`2 rightPartitionedStream) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\BinaryQueryOperator.cs:line 189
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\ScanQueryOperator.cs:line 137
   at System.Linq.Parallel.BinaryQueryOperator`3.BinaryQueryOperatorResults.LeftChildResultsRecipient.Receive[TLeftKey](PartitionedStream`2 source) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\BinaryQueryOperator.cs:line 155
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\ScanQueryOperator.cs:line 137
   at System.Linq.Parallel.BinaryQueryOperator`3.BinaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\BinaryQueryOperator.cs:line 125
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\UnaryQueryOperator.cs:line 130
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\QueryOperator.cs:line 164
   at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery() in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\QueryOpeningEnumerator.cs:line 164
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext() in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\QueryOpeningEnumerator.cs:line 108
   at System.Linq.ParallelEnumerable.GetOneWithPossibleDefault[TSource](QueryOperator`1 queryOp, Boolean throwIfTwo, Boolean defaultIfEmpty) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\ParallelEnumerable.cs:line 5349
   at System.Linq.ParallelEnumerable.FirstOrDefault[TSource](ParallelQuery`1 source) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\ParallelEnumerable.cs:line 5508
   at System.Linq.Parallel.Tests.ParallelQueryCombinationTests.FirstOrDefault_AggregateException(Labeled`1 source, Labeled`1 operation) in R:\corefx\src\System.Linq.Parallel\tests\Combinatorial\FailingParallelQueryCombinationTests.cs:line 122
----- Inner Stack Trace -----
   at System.Linq.Parallel.Tests.Enumerables`1.<>c__DisplayClass2_0.<ThrowOnEnumeration>b__0(Int32 i) in R:\corefx\src\System.Linq.Parallel\tests\Helpers\Enumerables.cs:line 41
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext() in R:\corefx\src\System.Linq\src\System\Linq\Select.cs:line 670
   at System.Linq.Parallel.PartitionedDataSource`1.ContiguousChunkLazyEnumerator.MoveNext(T& currentElement, Int32& currentKey) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Partitioning\PartitionedDataSource.cs:line 682
   at System.Linq.Parallel.ConcatQueryOperator`1.ConcatQueryOperatorEnumerator`2.MoveNext(TSource& currentElement, ConcatKey`2& currentKey) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Binary\ConcatQueryOperator.cs:line 207
   at System.Linq.Parallel.FirstQueryOperator`1.FirstQueryOperatorEnumerator`1.MoveNext(TSource& currentElement, Int32& currentKey) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Unary\FirstQueryOperator.cs:line 177
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork() in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Scheduling\SpoolingTask.cs:line 227
   at System.Linq.Parallel.SpoolingTaskBase.Work() in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Scheduling\SpoolingTaskBase.cs:line 68
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Scheduling\QueryTask.cs:line 100
   at System.Linq.Parallel.QueryTask.RunTaskSynchronously(Object o) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Scheduling\QueryTask.cs:line 47
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)]]></stack-trace>
        </failure>
      </test>


      <test name="System.Linq.Parallel.Tests.ParallelQueryCombinationTests.First_AggregateException(source: ThrowOnFirstEnumeration, operation: Concat-Left:Default)" type="System.Linq.Parallel.Tests.ParallelQueryCombinationTests" method="First_AggregateException" time="0.0118297" result="Fail">
        <traits>
          <trait name="category" value="outerloop" />
        </traits>
        <failure exception-type="System.AggregateException">
          <message><![CDATA[System.AggregateException : One or more errors occurred. (One or more errors occurred. (Exception of type 'System.Linq.Parallel.Tests.DeliberateTestException' was thrown.)) (Exception of type 'System.Linq.Parallel.Tests.DeliberateTestException' was thrown.)\r\n---- System.Linq.Parallel.Tests.DeliberateTestException : Exception of type 'System.Linq.Parallel.Tests.DeliberateTestException' was thrown.]]></message>
          <stack-trace><![CDATA[   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Scheduling\QueryTaskGroupState.cs:line 133
   at System.Linq.Parallel.SpoolingTask.SpoolStopAndGo[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, SynchronousChannel`1[] channels, TaskScheduler taskScheduler) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Scheduling\SpoolingTask.cs:line 73
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute() in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Merging\DefaultMergeHelper.cs:line 107
   at System.Linq.Parallel.MergeExecutor`1.Execute() in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Merging\MergeExecutor.cs:line 103
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Merging\MergeExecutor.cs:line 92
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\PartitionedStreamMerger.cs:line 61
   at System.Linq.Parallel.FirstQueryOperator`1.WrapHelper[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, QuerySettings settings) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Unary\FirstQueryOperator.cs:line 91
   at System.Linq.Parallel.FirstQueryOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Unary\FirstQueryOperator.cs:line 68
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\UnaryQueryOperator.cs:line 161
   at System.Linq.Parallel.ConcatQueryOperator`1.WrapHelper2[TLeftKey,TRightKey](PartitionedStream`2 leftStreamInc, PartitionedStream`2 rightStreamInc, IPartitionedStreamRecipient`1 outputRecipient) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Binary\ConcatQueryOperator.cs:line 130
   at System.Linq.Parallel.ConcatQueryOperator`1.WrapHelper[TLeftKey,TRightKey](PartitionedStream`2 leftStreamInc, PartitionedStream`2 rightStream, IPartitionedStreamRecipient`1 outputRecipient, QuerySettings settings, Boolean preferStriping) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Binary\ConcatQueryOperator.cs:line 110
   at System.Linq.Parallel.ConcatQueryOperator`1.WrapPartitionedStream[TLeftKey,TRightKey](PartitionedStream`2 leftStream, PartitionedStream`2 rightStream, IPartitionedStreamRecipient`1 outputRecipient, Boolean preferStriping, QuerySettings settings) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Binary\ConcatQueryOperator.cs:line 91
   at System.Linq.Parallel.BinaryQueryOperator`3.BinaryQueryOperatorResults.RightChildResultsRecipient`1.Receive[TRightKey](PartitionedStream`2 rightPartitionedStream) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\BinaryQueryOperator.cs:line 189
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\ScanQueryOperator.cs:line 137
   at System.Linq.Parallel.BinaryQueryOperator`3.BinaryQueryOperatorResults.LeftChildResultsRecipient.Receive[TLeftKey](PartitionedStream`2 source) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\BinaryQueryOperator.cs:line 155
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\ScanQueryOperator.cs:line 137
   at System.Linq.Parallel.BinaryQueryOperator`3.BinaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\BinaryQueryOperator.cs:line 125
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\UnaryQueryOperator.cs:line 130
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\QueryOperator.cs:line 164
   at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery() in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\QueryOpeningEnumerator.cs:line 164
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext() in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\QueryOpeningEnumerator.cs:line 108
   at System.Linq.ParallelEnumerable.GetOneWithPossibleDefault[TSource](QueryOperator`1 queryOp, Boolean throwIfTwo, Boolean defaultIfEmpty) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\ParallelEnumerable.cs:line 5349
   at System.Linq.ParallelEnumerable.First[TSource](ParallelQuery`1 source) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\ParallelEnumerable.cs:line 5425
   at System.Linq.Parallel.Tests.ParallelQueryCombinationTests.First_AggregateException(Labeled`1 source, Labeled`1 operation) in R:\corefx\src\System.Linq.Parallel\tests\Combinatorial\FailingParallelQueryCombinationTests.cs:line 102
----- Inner Stack Trace -----
   at System.Linq.Parallel.Tests.Enumerables`1.<>c__DisplayClass2_0.<ThrowOnEnumeration>b__0(Int32 i) in R:\corefx\src\System.Linq.Parallel\tests\Helpers\Enumerables.cs:line 41
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext() in R:\corefx\src\System.Linq\src\System\Linq\Select.cs:line 670
   at System.Linq.Parallel.PartitionedDataSource`1.ContiguousChunkLazyEnumerator.MoveNext(T& currentElement, Int32& currentKey) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Partitioning\PartitionedDataSource.cs:line 682
   at System.Linq.Parallel.ConcatQueryOperator`1.ConcatQueryOperatorEnumerator`2.MoveNext(TSource& currentElement, ConcatKey`2& currentKey) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Binary\ConcatQueryOperator.cs:line 207
   at System.Linq.Parallel.FirstQueryOperator`1.FirstQueryOperatorEnumerator`1.MoveNext(TSource& currentElement, Int32& currentKey) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Unary\FirstQueryOperator.cs:line 177
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork() in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Scheduling\SpoolingTask.cs:line 227
   at System.Linq.Parallel.SpoolingTaskBase.Work() in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Scheduling\SpoolingTaskBase.cs:line 68
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Scheduling\QueryTask.cs:line 100
   at System.Linq.Parallel.QueryTask.RunTaskSynchronously(Object o) in R:\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Scheduling\QueryTask.cs:line 47
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)]]></stack-trace>
        </failure>
      </test>
```

**Comment by stephentoub** [comment]
cc: @Clockwork-Muse

**Comment by Clockwork-Muse** [comment]
As the comments predicted, [test turned out to be flaky](https://github.com/dotnet/corefx/blob/master/src/System.Linq.Parallel/tests/Combinatorial/FailingParallelQueryCombinationTests.cs#L118-L119):

 > // Concat seems able to return the first element when the left query does not fail ("first" query).
> // This test might be flaky in the case that it decides to run the right query too...

The way the tests are setup, it's checking that things are ('correctly') wrapped in terms of `AggregateException` in various failing scenarios.  The problem is that the combination of `First` and `Concat`, and where the left side returns results, will _almost_ (it turns out) always actually return an element, and in all those cases before even looking at the other operand (this test case being set to fail on first enumeration).  All the other binary operations fail in this scenario because they're guaranteed to access at least one element.

That it's failing means that the optimizer decided it did actually have an extra thread to throw at the problem, thankyouverymuch.

@CIPop - How's your secondary box set for cores?
@stephentoub - Disable test for that operand, or have it check for either possibility?

**Comment by CIPop** [comment]
> How's your secondary box set for cores?

It's a 6 core / 12 logical. The main one has 4 / 8.

**Comment by Clockwork-Muse** [comment]
So yeah, extra cores, since the PLINQ tests were set to be serialized (given the multithreading nature of the library).  Although that assumes the main test run is serialized, which it isn't/wasn't for submitted PRs.

**Comment by stephentoub** [comment]
> Disable test for that operand, or have it check for either possibility?

Thanks, @Clockwork-Muse.  If we believe we know the complete set of possibilities and it's easy to modify the test to do so, let's have it check for them all.  Otherwise let's disable the test in this situation.
