### ISSUE TITLE
Can't extend class from .net 3.5 dll

### ISSUE THREAD

**Issue by strigonLeader** [dotnet/corefx#19439]
I have one class library project built on dot net framework 3.5. I want to have a new dot net core application reference the dll produced by the first project and extend classes from that library.

I have had to add a nuget reference to Microsoft.NETCore.Portable.Compatibility to make fix some basic issues with doing this, but now when I extend a class with an abstract method I can't override the method. I get a paradoxical situation where the class is raising an error that the method is not implemented and the method is raising an error that there is nothing to override.

base class:

``` C#
public abstract class Server {
	public event Action<Connection> ConnectionEstablished;

	private TcpListener m_listenSocket;
	private Task m_awaitConnectionTask;
	readonly private List<Action> m_serverStoppedCallbacks = new List<Action>();

	protected Server(int port) {
		m_listenSocket = new TcpListener(IPAddress.Parse("localhost"), port);
	}

	public void Listen() {
		m_listenSocket.Start();
		m_awaitConnectionTask = new Task(AwaitConnection);
	}

	public void WhenStopped(Action callback) {
		lock(m_serverStoppedCallbacks)
			m_serverStoppedCallbacks.Add(callback);
	}

	protected abstract Connection CreateConnection(TcpClient tcpClient);

	private void AwaitConnection() {
		try {
			while (true) 
				ConnectionEstablished?.Invoke(CreateConnection(m_listenSocket.AcceptTcpClient()));
		} catch (SocketException e) {

		} finally {
			m_listenSocket.Stop();
			List<Action> callbacks;
			lock (m_serverStoppedCallbacks) {
				callbacks = m_serverStoppedCallbacks.ToList();
				m_serverStoppedCallbacks.Clear();
			}
			foreach (var callback in callbacks)
				callback();
		}
	}
}
```

Inherited class:
``` C#
public class Server : Communism.Network.Server {
	public Server(int port) : base(port) {
	}

	public static void Main() {}

	protected override Connection CreateConnection(TcpClient tcpClient) {
		throw new NotImplementedException();
	}
}
```

**Comment by strigonLeader** [comment]
After more investigation the problem is being caused by the TcpClient type. If I make the signature of CreateConnection take no parameters or build in types I can extend fine. It might be because the Compatibility package resolves the TcpClient class as different from the TcpClient class which the library was compiled against. I don't know enough about how the Compatibility package works to figure out a solution for this.

**Comment by karelz** [comment]
@weshaggard @ericstj can you please advise/route?

**Comment by strigonLeader** [comment]
https://github.com/strigonLeader/dotnetcoreexample
Here's an example of how I reproduce the issue.

**Comment by strigonLeader** [comment]
You also get an error CS7069 when you try to implement an interface with TcpClient as a method parameter or when you try to call a method that returns TcpClient on an instance of a class from the library.

**Comment by weshaggard** [comment]
Unfortunately I think there are a number of things missing from the compatibility package as it wasn't really intended for this purpose. We should have much better support for this sort of thing with .NET Core 2.0 (inbox without the compatibility package). 

Can you try out your scenario with the dogfooding instructions for 2.0 tools?  https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md

**Comment by strigonLeader** [comment]
Dogfooding worked for compiling but I have difficulty during runtime when my dll tries to link against System.Threading.Tasks, since I have a port back of that dll for net 3.5. But I think that's just a separate problem.

**Comment by karelz** [comment]
@strigonLeader it would be great to see the error anyway (at minimum for future reference), can you please paste the error here?

**Comment by strigonLeader** [comment]
I get the following error:

```
System.TypeLoadException произошло
  HResult=0x80131522
  Сообщение = Could not load type 'System.Threading.Tasks.Task' from assembly 'System.Threading, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
  Источник = <Не удается определить источник исключения>
  Трассировка стека:
   at WeirdConsumer.Consumer..ctor() in C:\Users\hierarch\Desktop\netcoreexample\dotnetcoreexample\ThreadingReferenceIssue\WeirdConsumer\Consumer.cs:line 11
   at LibraryUser.Program.Main(String[] args) in C:\Users\hierarch\Desktop\netcoreexample\dotnetcoreexample\ThreadingReferenceIssue\LibraryUser\Program.cs:line 9
```

I added an additional example in https://github.com/strigonLeader/dotnetcoreexample callet ThreadingReferenceIssue which encapsulates this issue for me. Just open the LibraryUser.sln in visual studio and it should work so long as you have the sdk location specified. You just need to build and run for the error to happen.
