### ISSUE TITLE
Failure of .UnixPingUtilityTests.PacketSizeIsRespected on OSX

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#19435]
```
System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 50) [FAIL]
        System.Exception : Ping output was <PING6(98=40+8+50 bytes) ::1 --> ::1
        >
        ---- System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection.
        Parameter name: startIndex
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/System.Net.Ping/tests/FunctionalTests/UnixPingUtilityTests.cs(60,0): at System.Net.NetworkInformation.Tests.UnixPingUtilityTests.<PacketSizeIsRespected>d__1.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           ----- Inner Stack Trace -----
              at System.String.LastIndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/System.Net.Ping/tests/FunctionalTests/UnixPingUtilityTests.cs(67,0): at System.Net.NetworkInformation.Tests.UnixPingUtilityTests.ParseReturnedPacketSize(String pingOutput)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/System.Net.Ping/tests/FunctionalTests/UnixPingUtilityTests.cs(47,0): at System.Net.NetworkInformation.Tests.UnixPingUtilityTests.<PacketSizeIsRespected>d__1.MoveNext()
  Finished:    System.Net.Ping.Functional.Tests
  ```

https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug_prtest/3051/consoleText

Compare https://github.com/dotnet/corefx/issues/15018

**Comment by danmosemsft** [comment]
It seems https://github.com/dotnet/corefx/issues/15018 did not attempt to make this test more robust wrt ping6 issues. In product, we should already catch and throw PingException, which is better than ArgumentOutOfRangeException or similar. I'm not sure what coudl be done to the test except possibly retries (other issue hypothesized too many pings at once). It's apparently a ping6 bug.

**Comment by ViktorHofer** [comment]
Happened again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release_prtest/3663/

**Comment by stephentoub** [comment]
Again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug_prtest/3581/consoleText
```
System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 50) [FAIL]
        System.Exception : Ping output was <PING6(98=40+8+50 bytes) ::1 --> ::1
        >
        ---- System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection.
        Parameter name: startIndex
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/System.Net.Ping/tests/FunctionalTests/UnixPingUtilityTests.cs(60,0): at System.Net.NetworkInformation.Tests.UnixPingUtilityTests.<PacketSizeIsRespected>d__1.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           ----- Inner Stack Trace -----
              at System.String.LastIndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/System.Net.Ping/tests/FunctionalTests/UnixPingUtilityTests.cs(67,0): at System.Net.NetworkInformation.Tests.UnixPingUtilityTests.ParseReturnedPacketSize(String pingOutput)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/System.Net.Ping/tests/FunctionalTests/UnixPingUtilityTests.cs(47,0): at System.Net.NetworkInformation.Tests.UnixPingUtilityTests.<PacketSizeIsRespected>d__1.MoveNext()
```

**Comment by Jiayili1** [comment]
This issue is repro on Core Tests (Master), detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170712.01/workItem/System.Net.Ping.Functional.Tests/analysis/xunit/System.Net.NetworkInformation.Tests.UnixPingUtilityTests~2FPacketSizeIsRespected(payloadSize:%200)

**Comment by Jiayili1** [comment]
failed again in master branch, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170821.01/workItem/System.Net.Ping.Functional.Tests/analysis/xunit/System.Net.NetworkInformation.Tests.UnixPingUtilityTests~2FPacketSizeIsRespected(payloadSize:%200)

**Comment by danmosemsft** [comment]
Again 
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170912.02/workItem/System.Net.Ping.Functional.Tests/analysis/xunit/System.Net.NetworkInformation.Tests.UnixPingUtilityTests~2FPacketSizeIsRespected(payloadSize:%200)

**Comment by danmosemsft** [comment]
@Priya91 can you make the tests stop failing (retries or disable on OSX if you don't have time to investigate) ? 
https://github.com/dotnet/corefx/issues/15018
https://github.com/dotnet/corefx/issues/23876
