### ISSUE TITLE
Several Process tests on Windows failing with "Couldn't connect to remote machine"

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#19474]
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/7565/consoleText
```
     System.Diagnostics.Tests.ProcessTests.TestProcessOnRemoteMachineWindows [FAIL]
        System.InvalidOperationException : Couldn't connect to remote machine.
        ---- System.InvalidOperationException : Process performance counter is disabled, so the requested operation cannot be performed.
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(521,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(265,0): at System.Diagnostics.NtProcessManager.GetProcessIds(String machineName, Boolean isRemoteMachine)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(33,0): at System.Diagnostics.ProcessManager.IsProcessRunning(Int32 processId, String machineName)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(1055,0): at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\tests\ProcessTests.cs(917,0): at System.Diagnostics.Tests.ProcessTests.<GetTestProcess>d__76.MoveNext()
           D:\j\workspace\windows_nt_re---37265eab\src\System.Linq\src\System\Linq\Select.cs(133,0): at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
           ----- Inner Stack Trace -----
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(550,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(PerformanceCounterLib library)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(511,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
     System.Diagnostics.Tests.ProcessTests.GetProcessesByName_RemoteMachineNameWindows_ReturnsExpected(machineName: \"8363c42cc7434644b263584fc831a4bb\") [FAIL]
        System.InvalidOperationException : Couldn't connect to remote machine.
        ---- System.InvalidOperationException : Process performance counter is disabled, so the requested operation cannot be performed.
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(521,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(1107,0): at System.Diagnostics.Process.GetProcesses(String machineName)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Windows.cs(27,0): at System.Diagnostics.Process.GetProcessesByName(String processName, String machineName)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\tests\ProcessTests.cs(870,0): at System.Diagnostics.Tests.ProcessTests.GetProcessesByName_ProcessNameMachineName_ReturnsExpected(String machineName)
           ----- Inner Stack Trace -----
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(550,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(PerformanceCounterLib library)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(511,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
     System.Diagnostics.Tests.ProcessTests.GetProcessesByName_RemoteMachineNameWindows_ReturnsExpected(machineName: \"\\\\e41070783511438199c628aa28bd8d16\") [FAIL]
        System.InvalidOperationException : Couldn't connect to remote machine.
        ---- System.InvalidOperationException : Process performance counter is disabled, so the requested operation cannot be performed.
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(521,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(1107,0): at System.Diagnostics.Process.GetProcesses(String machineName)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Windows.cs(27,0): at System.Diagnostics.Process.GetProcessesByName(String processName, String machineName)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\tests\ProcessTests.cs(870,0): at System.Diagnostics.Tests.ProcessTests.GetProcessesByName_ProcessNameMachineName_ReturnsExpected(String machineName)
           ----- Inner Stack Trace -----
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(550,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(PerformanceCounterLib library)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(511,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
```
cc: @danmosemsft, @hughbe

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/7566/

**Comment by danmosemsft** [comment]
@ViktorHofer want to take a look? 49e936e should have protected against this.

**Comment by ViktorHofer** [comment]
Yeah, investigating...

**Comment by danmosemsft** [comment]
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/7592/

**Comment by ViktorHofer** [comment]
The check if PerfProc counters are disabled is implemented correctly. See here: https://support.microsoft.com/en-us/help/2554336/how-to-manually-rebuild-performance-counters-for-windows-server-2008-64bit-or-windows-server-2008-r2-systems

The problem is that the Registry check say they are enabled but in fact when running the code they aren't enabled. We can't really change anything about that. In this case I would let the tests just silently pass...

**Comment by danmosemsft** [comment]
If that's the best we can do, I guess it's what you have to do.

**Comment by safern** [comment]
Failed again: 

https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/7609/
