### ISSUE TITLE
Linux: cannot decrypt EncryptedXml document that uses X509Certificate as the key

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#19489]
#### Repro
Create a test certificate, such as https://github.com/aspnet/DataProtection/blob/dev/test/Microsoft.AspNetCore.DataProtection.Extensions.Test/TestFiles/TestCert.pfx
```c#
using System;
using System.Security.Cryptography.X509Certificates;
using System.Security.Cryptography.Xml;
using System.Xml;
using System.Xml.Linq;

namespace decrypt
{
    class Program
    {
        static void Main(string[] args)
        {
            var cert = new X509Certificate2("TestCert.pfx", "password");
            var store = new X509Store(StoreName.Root);
            store.Open(OpenFlags.ReadWrite);
            store.Add(cert);
            store.Close();

            try
            {
                var xmlDoc = new XmlDocument();
                xmlDoc.Load(new XElement("test", new XElement("item")).CreateReader());
                var elementToEncrypt = (XmlElement)xmlDoc.DocumentElement.FirstChild;
                var encryptedDoc = new EncryptedXml(xmlDoc);
                var encryptedElement = encryptedDoc.Encrypt(elementToEncrypt, cert);
                EncryptedXml.ReplaceElement(elementToEncrypt, encryptedElement, false);
                xmlDoc.Save("sample.xml");
                Console.WriteLine(xmlDoc.OuterXml);

                var xmlDocument = new XmlDocument();
                xmlDocument.Load("sample.xml");
                var encryptedXml = new EncryptedXml(xmlDocument);
                // this line always throws
                encryptedXml.DecryptDocument();
            }
            finally
            {
                store.Open(OpenFlags.ReadWrite);
                store.Remove(cert);
                store.Close();
            }
        }
    }
}
```

#### Error:
```
Unhandled Exception: System.PlatformNotSupportedException: Unix LocalMachine X509Store is limited to the Root and CertificateAuthority stores.
   at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
   at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
   at System.Security.Cryptography.Xml.Utils.BuildBagOfCerts(KeyInfoX509Data keyInfoX509Data, CertUsageType certUsageType)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptEncryptedKey(EncryptedKey encryptedKey)
   at System.Security.Cryptography.Xml.EncryptedXml.GetDecryptionKey(EncryptedData encryptedData, String symmetricAlgorithmUri)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument()
```

#### Details
Using: Microsoft.NETCore.App: 2.0.0-preview1-002101-00
OS: Ubuntu 16.04

**Comment by bartonjs** [comment]
Why are you adding the certificate to the machine root store?  I don't think there's anything in the EncryptedXml flow which does chain trust, it just uses the certificate as an indirection to get at the private (or public) key.

**Comment by bartonjs** [comment]
But the problem here seems to be that the `catch` in EncryptedXml (http://source.dot.net/#System.Security.Cryptography.Xml/System/Security/Cryptography/Xml/Utils.cs,683) caught just CryptographicException, and we threw PNSE.  So we should catch the PNSE.

**Comment by natemcmaster** [comment]
@bartonjs using root store just for the sake of reproducing the issue. I'd rather use 'My' or 'LocalMachine', but they are not supported.

FWIW EncryptedXml.DecryptDocument fails no matter what store the cert is in.
