### ISSUE TITLE
Exceptions from RemoteExecutorHost should get into XML log

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#19518]
We should try to `tee` the console from RemoteExecutorHost so it gets into the XML test log and thus into the correct test result in Helix. As it is you just get eg
```
Assert.Equal() Failure\r
    Expected: 42\r
    Actual:   -532462766

        Stack Trace:

           at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
```
but if you look at the full console output, aggregated for all the tests in this library, you see the actual exception --
```
2017-05-09 01:33:05,362: INFO: proc(54): run_and_log_output: Output: Hello World
2017-05-09 01:33:05,440: INFO: proc(54): run_and_log_output: Output: Exception from RemoteExecutorConsoleApp(System.Console.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb, ConsoleEncoding+<>c, <OutputEncoding_SetWithErrorAndOutputInitialized_ResetsErrorAndOutput>b__6_0):
2017-05-09 01:33:05,440: INFO: proc(54): run_and_log_output: Output: Assembly: System.Console.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
2017-05-09 01:33:05,440: INFO: proc(54): run_and_log_output: Output: Type: ConsoleEncoding+<>c
2017-05-09 01:33:05,440: INFO: proc(54): run_and_log_output: Output: Method: Int32 <OutputEncoding_SetWithErrorAndOutputInitialized_ResetsErrorAndOutput>b__6_0()
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output: Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.IOException: The request is not supported
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at System.ConsolePal.SetConsoleOutputEncoding(Encoding enc)
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at System.Console.set_OutputEncoding(Encoding value)
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at ConsoleEncoding.<>c.<OutputEncoding_SetWithErrorAndOutputInitialized_ResetsErrorAndOutput>b__6_0()
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    --- End of inner exception stack trace ---
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at RemoteExecutorConsoleApp.Program.Main(String[] args)
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output: 
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output: Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.IOException: The request is not supported
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at System.ConsolePal.SetConsoleOutputEncoding(Encoding enc)
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at System.Console.set_OutputEncoding(Encoding value)
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at ConsoleEncoding.<>c.<OutputEncoding_SetWithErrorAndOutputInitialized_ResetsErrorAndOutput>b__6_0()
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    --- End of inner exception stack trace ---
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at RemoteExecutorConsoleApp.Program.Main(String[] args)
2017-05-09 01:33:05,596: INFO: proc(54): run_and_log_output: Output:    ConsoleEncoding.OutputEncoding_SetWithErrorAndOutputInitialized_ResetsErrorAndOutput [FAIL]
2017-05-09 01:33:05,596: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2017-05-09 01:33:05,596: INFO: proc(54): run_and_log_output: Output:       Expected: 42
2017-05-09 01:33:05,596: INFO: proc(54): run_and_log_output: Output:       Actual:   -532462766
2017-05-09 01:33:05,596: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-09 01:33:05,721: INFO: proc(54): run_and_log_output: Output:             at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
2017-05-09 01:33:05,957: INFO: proc(54): run_and_log_output: Output: Exception from RemoteExecutorConsoleApp(System.Console.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb, ConsoleEncoding+<>c, <InputEncoding_SetWithInInitialized_ResetsIn>b__3_0):
2017-05-09 01:33:05,957: INFO: proc(54): run_and_log_output: Output: Assembly: System.Console.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
```

**Comment by safern** [comment]
Maybe throwinfg XunitException(message) with the message being the actual exception?

**Comment by danmosemsft** [comment]
@safern that would terminate the test but tests can expect exceptions from the remote process (https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/tests/System/AppDomainTests.cs#L94) so they wouldn't want that

I think what needs to be done is 
1. capture the console output from the spawned process 
1. write it to `XUnit.ITestOutputHelper` so it goes to the XML log (generally we don't use this interface because we want it to write ot the console also, but in this case we are already getting that)
1. rely on the test setting `RemoteInvokeOptions.CheckExitCode = true` or otherwise determining by itself that the child process died unexpectedly.

**Comment by ViktorHofer** [comment]
I'm not sure how feasible this is with the official xunit runner.
