### ISSUE TITLE
Write_HeadersToClosedConnectionSynchronously_ThrowsHttpListenerException test fails on macOS

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#19534]
```
System.Net.Tests.HttpResponseStreamTests.Write_HeadersToClosedConnectionSynchronously_ThrowsHttpListenerException(ignoreWriteExceptions: False) [FAIL]
10:29:33         Assert.Throws() Failure
10:29:33         Expected: typeof(System.Net.HttpListenerException)
10:29:33         Actual:   (No exception was thrown)
10:29:33         Stack Trace:
10:29:33            /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Net.HttpListener/tests/HttpResponseStreamTests.cs(453,0): at System.Net.Tests.HttpResponseStreamTests.<Write_HeadersToClosedConnectionSynchronously_ThrowsHttpListenerException>d__21.MoveNext()
10:29:33            --- End of stack trace from previous location where exception was thrown ---
10:29:33               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
10:29:33               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
10:29:33            --- End of stack trace from previous location where exception was thrown ---
10:29:33               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
10:29:33               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
10:29:33            --- End of stack trace from previous location where exception was thrown ---
10:29:33               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
10:29:33               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by Priya91** [comment]
This test is disabled [here] with #18128

**Comment by Priya91** [comment]
Closing as dupe.

**Comment by stephentoub** [comment]
Several tests are [ActiveIssue(...)]'d against this, e.g. 
https://github.com/dotnet/runtime/blob/04f22268efb4434b7cd81e8ae2c3354be99fd4a7/src/libraries/System.Net.HttpListener/tests/HttpResponseStreamTests.cs#L499-L504
