### ISSUE TITLE
Why have a 302 Exception when i put a request

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#19611]
@Circlecirclecircle commented on [Wed May 10 2017](https://github.com/dotnet/standard/issues/336)

Url:https://xxxx.xxxxx.xxxxxx.com/

Exception.Message:The remote server returned an error: (302) Moved Temporarily.

Exception.StackTrace:
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__37_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

```
private static HttpWebResponse _Request(string url)
{
    HttpWebRequest request = WebRequest.CreateHttp(url);
    HttpWebResponse response =(HttpWebResponse)request.GetResponseAsync().Result;
    return response;
}
```

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/19596
