### ISSUE TITLE
Desktop: "System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.PingPong" failed

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#19618]
```
MESSAGE:
Assert.Equal() Failure\r\nExpected: 42\r\nActual: -532462766
+++++++++++++++++++
STACK TRACE:
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Diagnostics\RemoteExecutorTestBase.cs:line 188 at System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.PingPong() in D:\j\workspace\outerloop_net---903ddde6\src\System.IO.Pipes\tests\AnonymousPipeTests\AnonymousPipeTest.CrossProcess.cs:line 32
```

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/lastCompletedBuild/testReport/System.IO.Pipes.Tests/AnonymousPipeTest_CrossProcess/PingPong/

cc: @ianhays

**Comment by stephentoub** [comment]
The actual failure here was:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/51/consoleText
```
Exception from RemoteExecutorConsoleApp(System.IO.Pipes.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb, System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess, PingPong_OtherProcess, 1180, 1236):
  Assembly: System.IO.Pipes.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
  Type: System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess
  Method: Int32 PingPong_OtherProcess(System.String, System.String)
  Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.IOException: Pipe is broken.
     at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
     at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
     at System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.PingPong_OtherProcess(String inHandle, String outHandle) in D:\j\workspace\outerloop_net---903ddde6\src\System.IO.Pipes\tests\AnonymousPipeTests\AnonymousPipeTest.CrossProcess.cs:line 45
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
     at RemoteExecutorConsoleApp.Program.Main(String[] args) in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Diagnostics\RemoteExecutorConsoleApp\RemoteExecutorConsoleApp.cs:line 55
```
I believe this is a dup of #19656, with the same root cause as identified in #19656 (comment).
