### ISSUE TITLE
DCS_ResolveNameReturnsEmptyNamespace Failed on UWP

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#19629]
`DataContractSerializerTests.DCS_ResolveNameReturnsEmptyNamespace` failed on UWP.

```xml
<test name="DataContractSerializerTests.DCS_ResolveNameReturnsEmptyNamespace" type="DataContractSerializerTests" method="DCS_ResolveNameReturnsEmptyNamespace" time="0.0007143" result="Fail">
        <failure exception-type="System.NullReferenceException">
          <message><![CDATA[System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
          <stack-trace><![CDATA[   at System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.SetIfMembersHaveConflict(List$1<$DataMember> members) in d:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\ClassDataContract.cs:line 1121
   at System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ImportDataMembers() in d:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\ClassDataContract.cs:line 1084
   at System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper..ctor(Type type) in d:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\ClassDataContract.cs:line 809
   at System.Runtime.Serialization.ClassDataContract..ctor(Type type) in d:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\ClassDataContract.cs:line 46
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, RuntimeTypeHandle typeHandle, Type type) in d:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\DataContract.cs:line 570
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type) in d:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\DataContract.cs:line 424
   at System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContract(RuntimeTypeHandle typeHandle, Type type) in d:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerContext.cs:line 140
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType($XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle objectTypeHandle, Type objectType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, Type declaredType) in d:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs:line 219
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerialize($XmlWriterDelegator xmlWriter, Object obj, Boolean isDeclaredType, Boolean writeXsiType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle) in d:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs:line 138
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerializeReference($XmlWriterDelegator xmlWriter, Object obj, Boolean isDeclaredType, Boolean writeXsiType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle) in d:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs:line 106
   at Type538.WriteEmptyNsContainerToXml($XmlWriterDelegator A_0, Object A_1, $XmlObjectSerializerWriteContext A_2, $ClassDataContract A_3)
   at System.Runtime.Serialization.Json.JsonFormatCollectionWriterDelegate.InvokeOpenStaticThunk($XmlWriterDelegator xmlWriter, Object obj, $XmlObjectSerializerWriteContextComplexJson context, $CollectionDataContract dataContract) in InvokeOpenStaticThunk:line 16707566
   at System.Runtime.Serialization.Json.JsonFormatCollectionWriterDelegate.Invoke($XmlWriterDelegator xmlWriter, Object obj, $XmlObjectSerializerWriteContextComplexJson context, $CollectionDataContract dataContract) in Invoke:line 16707566
   at System.Runtime.Serialization.ClassDataContract.WriteXmlValue($XmlWriterDelegator xmlWriter, Object obj, $XmlObjectSerializerWriteContext context) in d:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\ClassDataContract.cs:line 508
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteDataContractValue($DataContract dataContract, $XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle) in d:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs:line 651
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithoutXsiType($DataContract dataContract, $XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle) in d:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs:line 150
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent($XmlWriterDelegator writer, Object graph, $DataContractResolver dataContractResolver) in d:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\DataContractSerializer.cs:line 364
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject($XmlWriterDelegator writer, Object graph, $DataContractResolver dataContractResolver) in d:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\DataContractSerializer.cs:line 247
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions($XmlWriterDelegator writer, Object graph, $DataContractResolver dataContractResolver) in d:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializer.cs:line 71
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObject($XmlDictionaryWriter writer, Object graph) in d:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializer.cs:line 57
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(Stream stream, Object graph) in d:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializer.cs:line 27
   at DataContractSerializerTests.SerializeAndDeserialize<System.__Canon>(__Canon value, String baseline, $DataContractSerializerSettings settings, Func$1<$DataContractSerializer> serializerFactory, Boolean skipStringCompare) in d:\OSS\corefx-1\corefx\src\System.Runtime.Serialization.Xml\tests\DataContractSerializer.cs:line 3180
   at DataContractSerializerTests.DCS_ResolveNameReturnsEmptyNamespace() in d:\OSS\corefx-1\corefx\src\System.Runtime.Serialization.Xml\tests\DataContractSerializer.cs:line 2795
   at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean targetIsThisCall)
   at System.InvokeUtils.CalliIntrinsics.Call(IntPtr dynamicInvokeHelperMethod, Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean isTargetThisCall)
   at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, IntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object targetMethodOrDelegate, Object[] parameters, BinderBundle binderBundle, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\InvokeUtils.cs:line 400]]></stack-trace>
        </failure>
</test>
```

**Comment by shmao** [comment]
I understood the root cause of the bug. The issue occurred with the types like shown below, 

```c#
public class BaseType

public class TypeNotDetected : BaseType
```

Here's what happened.

In the test scenario, UWP toolchain didn't detect `TypeNotDetected `, so it didn't generate serializer for the type. But the toolchain found BaseType, and thus generate serializer for it. 

The issue happened at runtime when the test serialized the instance of `TypeNotDetected`.  Even though the toolchain didn't generate serializer, the reflection-based serialization would serialize `TypeNotDetected` using reflection.

The reflection-base method requires information from  `TypeNotDetected`'s DataContract and `BaseType`'s DataContract. But since `BaseType`'s DataContract was pre-generated by toolchain, it has only partial information, i.e. some of its members were null, including the "Members" property. Therefore, the reflection-base method also failed.

We probably can fix the issue by enforcing the serializer to generate DataContract at runtime when doing reflection based serialization.
