### ISSUE TITLE
Desktop test failure: System.IO.Pipes.Tests.AnonymousPipeTest_Specific.ClonedServer_ActsAsOriginalServer

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#19678]
```
      System.IO.Pipes.Tests.AnonymousPipeTest_Specific.ClonedServer_ActsAsOriginalServer [FAIL]
        System.IO.IOException : Pipe is broken.
        Stack Trace:
             at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
             at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
          C:\Users\vikto\Documents\src\corefx\src\System.IO.Pipes\tests\AnonymousPipeTests\AnonymousPipeTest.Specific.cs(49,0): at System.IO.Pipes.Tests.AnonymousPipeTest_Specific.ClonedServer_Act
  sAsOriginalServer()
```

Fails on my local looped test runs in System.IO.Pipes like 1/50 runs.

**Comment by ViktorHofer** [comment]
cc: @JeremyKuhne @ianhays

**Comment by stephentoub** [comment]
I believe this is a dup of #19656, with the same root cause as identified in #19656 (comment).
