### ISSUE TITLE
Desktop test failure: System.IO.Pipes.Tests.AnonymousPipeTest_Specific.Windows_BufferSizeRoundtripping

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#19680]
```
      System.IO.Pipes.Tests.AnonymousPipeTest_Specific.Windows_BufferSizeRoundtripping [FAIL]
        System.IO.IOException : The handle is invalid.

        Stack Trace:
             at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
             at System.IO.Pipes.PipeStream.get_InBufferSize()
          C:\Users\vikto\Documents\src\corefx\src\System.IO.Pipes\tests\AnonymousPipeTests\AnonymousPipeTest.Specific.cs(137,0): at System.IO.Pipes.Tests.AnonymousPipeTest_Specific.Windows_BufferS
  izeRoundtripping()
```

Fails on my local looped test runs in System.IO.Pipes like 1/35 times.

cc @ianhays @JeremyKuhne

**Comment by stephentoub** [comment]
I believe this is a dup of #19656, with the same root cause as identified in #19656 (comment).
