### ISSUE TITLE
Desktop test failure: System.IO.Pipes.Tests.AnonymousPipeTest_Specific.InvalidReadMode_Throws_ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#19681]
```
System.IO.Pipes.Tests.AnonymousPipeTest_Specific.InvalidReadMode_Throws_ArgumentOutOfRangeException [FAIL]
        System.IO.IOException : Invalid pipe handle.
        Stack Trace:
             at System.IO.Pipes.AnonymousPipeClientStream.Init(PipeDirection direction, SafePipeHandle safePipeHandle)
             at System.IO.Pipes.AnonymousPipeClientStream..ctor(PipeDirection direction, String pipeHandleAsString)
          C:\Users\vikto\Documents\src\corefx\src\System.IO.Pipes\tests\AnonymousPipeTests\AnonymousPipeTest.Specific.cs(189,0): at System.IO.Pipes.Tests.AnonymousPipeTest_Specific.InvalidReadMode
  _Throws_ArgumentOutOfRangeException()
```

Fails on my local test looped runs in System.IO.Pipes like 1/30 times.

cc: @JeremyKuhne @ianhays

**Comment by stephentoub** [comment]
I believe this is a dup of https://github.com/dotnet/corefx/issues/19656, with the same root cause as identified in https://github.com/dotnet/corefx/issues/19656#issuecomment-301063220.
