### ISSUE TITLE
System.Net.Http.WinHttpException: %1

### ISSUE THREAD

**Issue by luoxy123** [dotnet/corefx#19768]
I use httpclient to send http request,When I use this method ReadAsStringAsync to read content , this 
exception occurs.

the netstandard version is netstandard1.3;
My system is window 10 Professional;

this is the code:
 `Var responseMessage = await HttpClient.SendAsync (Request, HttpCompletionOption.ResponseHeadersRead,
                    CancellationToken) .ConfigureAwait (false);

 var content = await responseMessage.Content.ReadAsStringAsync();
`

- The following is the exception stack information
`

System.IO.IOException : The read operation failed, see inner exception.

   at FeiniuBus.Runtime.HttpWebRequestMessage.<GetResponseAsync>d__21.MoveNext() in D:\work\feiniubus-sdk-net\src\FeiniuBusSDK.Core\Runtime\HttpRequestMessageFactory.cs:line 230
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at FeiniuBus.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__3`1.MoveNext() in D:\work\feiniubus-sdk-net\src\FeiniuBusSDK.Core\Runtime\Internal\HttpHandler.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at FeiniuBus.Runtime.Internal.Unmarshaller.<InvokeAsync>d__2`1.MoveNext() in D:\work\feiniubus-sdk-net\src\FeiniuBusSDK.Core\Runtime\Internal\Unmarshaller.cs:line 18
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at FeiniuBus.Runtime.Internal.ErrorHandler.<InvokeAsync>d__4`1.MoveNext() in D:\work\feiniubus-sdk-net\src\FeiniuBusSDK.Core\Runtime\Internal\ErrorHandler.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at FeiniuBus.Runtime.Internal.ErrorHandler.<InvokeAsync>d__4`1.MoveNext() in D:\work\feiniubus-sdk-net\src\FeiniuBusSDK.Core\Runtime\Internal\ErrorHandler.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at FeiniuBusSDK.Core.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__4`1.MoveNext() in D:\work\feiniubus-sdk-net\src\FeiniuBusSDK.Core\Runtime\Internal\CredentialsRetriever.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at FeiniuBusSDK.Tests.DispatchTests.<GetBusManagment>d__5.MoveNext() in D:\work\feiniubus-sdk-net\test\FeiniuBusSDK.Tests\DispatchTests.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----

`

**Comment by danmosemsft** [comment]
Can you create a small repro case?
Also I don't see WinHttpException in the output above.
