### ISSUE TITLE
UseCallback_BadCertificate_ExpectedPolicyErrors failing in CI with "a security error occurred"

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#19793]
I thought we had an issue for this but I can't find it, so I'm opening a new one.  Please consolidate as necessary...

e.g.
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug_prtest/72/consoleText
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug_prtest/7/consoleText
```
System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(url: \"https://wrong.host.badssl.com/\", expectedErrors: RemoteCertificateNameMismatch) [FAIL]
        System.Net.Http.HttpRequestException : An error occurred while sending the request.
        ---- System.Net.Http.WinHttpException : A security error occurred
        Stack Trace:
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
           D:\j\workspace\outerloop_net---92aeb271\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(462,0): at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           D:\j\workspace\outerloop_net---92aeb271\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ServerCertificates.cs(234,0): at System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.<UseCallback_BadCertificate_ExpectedPolicyErrors>d__12.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           ----- Inner Stack Trace -----
           D:\j\workspace\outerloop_net---92aeb271\src\System.Runtime.Extensions\src\System\Environment.cs(163,0): at System.Environment.get_StackTrace()
           D:\j\workspace\outerloop_net---92aeb271\src\Common\src\System\Runtime\ExceptionServices\ExceptionStackTrace.cs(23,0): at System.Runtime.ExceptionServices.ExceptionStackTrace.AddCurrentStack(Exception exception)
           D:\j\workspace\outerloop_net---92aeb271\src\Common\src\System\Net\Http\WinHttpException.cs(51,0): at System.Net.Http.WinHttpException.CreateExceptionUsingError(Int32 error)
           D:\j\workspace\outerloop_net---92aeb271\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs(308,0): at System.Net.Http.WinHttpRequestCallback.OnRequestError(WinHttpRequestState state, WINHTTP_ASYNC_RESULT asyncResult)
           D:\j\workspace\outerloop_net---92aeb271\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs(104,0): at System.Net.Http.WinHttpRequestCallback.RequestCallback(IntPtr handle, WinHttpRequestState state, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
           D:\j\workspace\outerloop_net---92aeb271\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs(47,0): at System.Net.Http.WinHttpRequestCallback.WinHttpCallback(IntPtr handle, IntPtr context, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
           --- End of stack trace from AddCurrentStack ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           D:\j\workspace\outerloop_net---92aeb271\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs(62,0): at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
           D:\j\workspace\outerloop_net---92aeb271\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(856,0): at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
```

**Comment by schen381** [comment]
It's same one as #7812. https://github.com/dotnet/corefx/issues/7812#issuecomment-297161505 I'm investigating this issue

**Comment by stephentoub** [comment]
Ok, will close as a dup of #7812.
