### ISSUE TITLE
XmlSerializerTests.XmlSchemaTest failed on UWP

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#19830]
Test `XmlSerializerTests.XmlSchemaTest` failed on UWP.

```
      <test name="XmlSerializerTests.XmlSchemaTest" type="XmlSerializerTests" method="XmlSchemaTest" time="0.0015794" result="Fail">
        <failure exception-type="System.InvalidOperationException">
          <message><![CDATA[System.InvalidOperationException : There was an error generating the XML document.\r\n---- System.InvalidOperationException : There was an error reflecting type 'System.Xml.Schema.XmlSchema'.\r\n-------- System.InvalidOperationException : You must implement a default accessor on System.Xml.Schema.XmlSchemaObjectCollection because it inherits from ICollection.]]></message>
          <stack-trace><![CDATA[   at System.Xml.Serialization.XmlSerializer.Serialize$catch$1() in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializer.cs:line 527
   at System.Xml.Schema.XmlSchema.Write($XmlWriter writer, $XmlNamespaceManager namespaceManager) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Schema\XmlSchema.cs:line 212
   at System.Xml.Schema.XmlSchema.Write(Stream stream, $XmlNamespaceManager namespaceManager) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Schema\XmlSchema.cs:line 137
   at XmlSerializerTests.XmlSchemaTest() in d:\OSS\corefx-1\corefx\src\System.Private.Xml\tests\XmlSerializer\XmlSerializerTests.cs:line 2409
   at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean targetIsThisCall)
   at System.InvokeUtils.CalliIntrinsics.Call(IntPtr dynamicInvokeHelperMethod, Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean isTargetThisCall)
   at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, IntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object targetMethodOrDelegate, Object[] parameters, BinderBundle binderBundle, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\InvokeUtils.cs:line 400
----- Inner Stack Trace -----
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping$catch$0() in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlReflectionImporter.cs:line 467
   at System.Xml.Serialization.XmlReflectionImporter.ImportElement($TypeModel model, $XmlRootAttribute root, String defaultNamespace, $RecursionLimiter limiter) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlReflectionImporter.cs:line 266
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(Type type, $XmlRootAttribute root, String defaultNamespace) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlReflectionImporter.cs:line 171
   at System.Xml.Serialization.XmlSerializer.Serialize($XmlWriter xmlWriter, Object o, $XmlSerializerNamespaces namespaces, String encodingStyle, String id) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializer.cs:line 510
----- Inner Stack Trace -----
   at System.Xml.Serialization.TypeScope.GetDefaultIndexer(Type type, String memberInfo) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\Types.cs:line 1348
   at System.Xml.Serialization.TypeScope.GetCollectionElementType(Type type, String memberInfo) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\Types.cs:line 1359
   at System.Xml.Serialization.TypeScope.ImportTypeDesc(Type type, MemberInfo memberInfo, Boolean directReference) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\Types.cs:line 830
   at System.Xml.Serialization.TypeScope.GetTypeDesc(Type type, MemberInfo source, Boolean directReference, Boolean throwOnError) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\Types.cs:line 715
   at System.Xml.Serialization.StructModel.GetPropertyModel(PropertyInfo propertyInfo) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\Models.cs:line 225
   at System.Xml.Serialization.StructModel.GetFieldModel(MemberInfo memberInfo) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\Models.cs:line 182
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers($StructMapping mapping, $StructModel model, Boolean openModel, String typeName, $RecursionLimiter limiter) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlReflectionImporter.cs:line 845
   at System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping($StructModel model, String ns, Boolean openModel, $XmlAttributes a, $RecursionLimiter limiter) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlReflectionImporter.cs:line 756
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping($TypeModel model, String ns, $ImportContext context, String dataType, $XmlAttributes a, Boolean repeats, Boolean openModel, $RecursionLimiter limiter) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlReflectionImporter.cs:line 441]]></stack-trace>
        </failure>
      </test>
```

The issue is likely due to missing metadata,

```
      SG0001 : Cannot generate serialization code for type 'System.Xml.Schema.XmlSchema'.
      There was an error reflecting type 'System.Xml.Schema.XmlSchema'.
      There was an error reflecting property 'Includes'.
      There was an error reflecting type 'System.Xml.Schema.XmlSchemaRedefine'.
      There was an error reflecting property 'Items'.
      There was an error reflecting type 'System.Xml.Schema.XmlSchemaAttributeGroup'.
      There was an error reflecting property 'Attributes'.
      There was an error reflecting type 'System.Xml.Schema.XmlSchemaAttribute'.
      Ambiguous match found.
```

**Comment by shmao** [comment]
The test failed in ReflectionOnly mode because the necessary metadata for XmlSchema was not kept.

The test failed with sg.exe because of a bug in sg. I will send a CodeFlow for fixing that bug.
