### ISSUE TITLE
BeginSendToV4IPEndPointToV6Host_NotReceived failed for desktop in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#19848]
https://ci.dot.net/job/dotnet_corefx/job/master/job/netfx_windows_nt_debug_prtest/327/consoleText
```     System.Net.Sockets.Tests.DualModeConnectionlessBeginSendTo.BeginSendToV4IPEndPointToV6Host_NotReceived [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.TimeoutException)
        Actual:   typeof(System.Net.Sockets.SocketException): An address incompatible with the requested protocol was used
        Stack Trace:
             at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
             at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
          D:\j\workspace\netfx_windows---8c0e8fba\src\System.Net.Sockets\tests\FunctionalTests\DualModeSocketTest.cs(1243,0): at System.Net.Sockets.Tests.DualModeConnectionlessBeginSendTo.DualModeBeginSendTo_EndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout)
          D:\j\workspace\netfx_windows---8c0e8fba\src\System.Net.Sockets\tests\FunctionalTests\DualModeSocketTest.cs(1209,0): at System.Net.Sockets.Tests.DualModeConnectionlessBeginSendTo.<BeginSendToV4IPEndPointToV6Host_NotReceived>b__4_0()
```

**Comment by stephentoub** [comment]
Again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/netfx_windows_nt_release_prtest/351/
```
 System.Net.Sockets.Tests.DualModeConnectionlessBeginSendTo.BeginSendToV4IPEndPointToV6Host_NotReceived [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.TimeoutException)
        Actual:   typeof(System.Net.Sockets.SocketException): An address incompatible with the requested protocol was used
        Stack Trace:
             at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
             at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
          D:\j\workspace\netfx_windows---50c21bdb\src\System.Net.Sockets\tests\FunctionalTests\DualModeSocketTest.cs(1243,0): at System.Net.Sockets.Tests.DualModeConnectionlessBeginSendTo.DualModeBeginSendTo_EndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout)
          D:\j\workspace\netfx_windows---50c21bdb\src\System.Net.Sockets\tests\FunctionalTests\DualModeSocketTest.cs(1210,0): at System.Net.Sockets.Tests.DualModeConnectionlessBeginSendTo.<BeginSendToV4IPEndPointToV6Host_NotReceived>b__4_0()
```

**Comment by karelz** [comment]
Moving to 2.1 based on the frequency of the failure ...

**Comment by karelz** [comment]
No failure in Helix history since 2017/5. No PR failure in last month.
Closing. Please reopen if it happens again.
