### ISSUE TITLE
XmlSerializerTests.Xml_TypeWithTwoDimensionalArrayProperty1 Failed on UWP

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#19897]
Test `XmlSerializerTests.Xml_TypeWithTwoDimensionalArrayProperty1` failed on UWP when using SG.

```
      <test name="XmlSerializerTests.Xml_TypeWithTwoDimensionalArrayProperty1" type="XmlSerializerTests" method="Xml_TypeWithTwoDimensionalArrayProperty1" time="0.0001856" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[XML comparison is also failing\r\nTest failed for input: SerializationTypes.TypeWith2DArrayProperty1\r\n
Expected: <?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<TypeWith2DArrayProperty1 xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <TwoDArrayOfSimpleType>\r\n    <ArrayOfSimpleType>\r\n      <SimpleType>\r\n        <P1>0 0 value</P1>\r\n        <P2>1</P2>\r\n      </SimpleType>\r\n      <SimpleType>\r\n        <P1>0 1 value</P1>\r\n        <P2>2</P2>\r\n      </SimpleType>\r\n    </ArrayOfSimpleType>\r\n    <ArrayOfSimpleType>\r\n      <SimpleType>\r\n        <P1>1 0 value</P1>\r\n        <P2>3</P2>\r\n      </SimpleType>\r\n      <SimpleType>\r\n        <P1>1 1 value</P1>\r\n        <P2>4</P2>\r\n      </SimpleType>\r\n    </ArrayOfSimpleType>\r\n  </TwoDArrayOfSimpleType>\r\n</TypeWith2DArrayProperty1>\r\n
Actual:   <?xml version=\"1.0\"?>\r\n<TypeWith2DArrayProperty1 xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <TwoDArrayOfSimpleType>\r\n    <ArrayOfSimpleType1>\r\n      <SimpleType>\r\n        <P1>0 0 value</P1>\r\n        <P2>1</P2>\r\n      </SimpleType>\r\n      <SimpleType>\r\n        <P1>0 1 value</P1>\r\n        <P2>2</P2>\r\n      </SimpleType>\r\n    </ArrayOfSimpleType1>\r\n    <ArrayOfSimpleType1>\r\n      <SimpleType>\r\n        <P1>1 0 value</P1>\r\n        <P2>3</P2>\r\n      </SimpleType>\r\n      <SimpleType>\r\n        <P1>1 1 value</P1>\r\n        <P2>4</P2>\r\n      </SimpleType>\r\n    </ArrayOfSimpleType1>\r\n  </TwoDArrayOfSimpleType>\r\n</TypeWith2DArrayProperty1>\r\n
Expected: True\r\nActual:   False]]>
          </message>
          <stack-trace><![CDATA[   at XmlSerializerTests.SerializeAndDeserialize<System.__Canon>(__Canon value, String baseline, Func$1<$XmlSerializer> serializerFactory, Boolean skipStringCompare, $XmlSerializerNamespaces xns) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\tests\XmlSerializer\XmlSerializerTests.cs:line 4466
   at XmlSerializerTests.Xml_TypeWithTwoDimensionalArrayProperty1() in d:\OSS\corefx-1\corefx\src\System.Private.Xml\tests\XmlSerializer\XmlSerializerTests.cs:line 1830
   at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean targetIsThisCall)
   at System.InvokeUtils.CalliIntrinsics.Call(IntPtr dynamicInvokeHelperMethod, Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean isTargetThisCall)
   at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, IntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object targetMethodOrDelegate, Object[] parameters, BinderBundle binderBundle, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\InvokeUtils.cs:line 400]]></stack-trace>
        </failure>
      </test>
```

**Comment by shmao** [comment]
The bug occurred when SG generated serializers for array types having the same name. For example, SG failed to generate correct serializers for both SimpleType[] and SimpleType[][].

     The root cause of the issue is that we used the same XmlReflectionImporter instance to import types for all serializers, which caused the mapping for ArrayOfSinpleType exist while importing SimpleType[][] and the mapping name for the latter would be named to ArrayOfSimpleType1. 

     The fix is to create new XmlReflectionImporter instance when importing each Type. 

I've made changes in UWP toolchain to fix the issue.

**Comment by shmao** [comment]
Reopen the issue. The fix in UWP toolchain caused a regression. The fix created new XmlReflectionImporter instance when importing each Type, which caused the size of the generated file increased dramatically because the importer needed to import some types multiple times. I'm going to revert the fix in UWP toolchain to unblock integration.
