### ISSUE TITLE
XmlSerializerTests.Xml_TypeWithXmlQualifiedName Failed on UWP

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#19899]
XmlSerializerTests.Xml_TypeWithXmlQualifiedName failed on UWP when using Sg.

```
      <test name="XmlSerializerTests.Xml_TypeWithXmlQualifiedName" type="XmlSerializerTests" method="Xml_TypeWithXmlQualifiedName" time="0.0001731" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[XML comparison is also failing\r\nTest failed for input: SerializationTypes.TypeWithXmlQualifiedName\r\n
Expected: <?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<TypeWithXmlQualifiedName xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <Value xmlns=\"\">FooName</Value>\r\n</TypeWithXmlQualifiedName>\r\n
Actual:   <?xml version=\"1.0\"?>\r\n<TypeWithXmlQualifiedName xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <Value>FooName</Value>\r\n</TypeWithXmlQualifiedName>\r\n
Expected: True\r\nActual:   False]]>
          </message>
          <stack-trace><![CDATA[   at XmlSerializerTests.SerializeAndDeserialize<System.__Canon>(__Canon value, String baseline, Func$1<$XmlSerializer> serializerFactory, Boolean skipStringCompare, $XmlSerializerNamespaces xns) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\tests\XmlSerializer\XmlSerializerTests.cs:line 4466
   at XmlSerializerTests.Xml_TypeWithXmlQualifiedName() in d:\OSS\corefx-1\corefx\src\System.Private.Xml\tests\XmlSerializer\XmlSerializerTests.cs:line 2033
   at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean targetIsThisCall)
   at System.InvokeUtils.CalliIntrinsics.Call(IntPtr dynamicInvokeHelperMethod, Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean isTargetThisCall)
   at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, IntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object targetMethodOrDelegate, Object[] parameters, BinderBundle binderBundle, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\InvokeUtils.cs:line 400]]></stack-trace>
        </failure>
      </test>
```

**Comment by shmao** [comment]
I made a fix in SG.exe for the issue. The CodeFlow is under review.

**Comment by shmao** [comment]
The fix had been checked in.
