### ISSUE TITLE
XmlSerializerTests.XmlUnknownElementAndEventHandlerTest Failed on UWP

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#19898]
`XmlSerializerTests.XmlUnknownElementAndEventHandlerTest` failed on UWP when using Sg.

```
      <test name="XmlSerializerTests.XmlUnknownElementAndEventHandlerTest" type="XmlSerializerTests" method="XmlUnknownElementAndEventHandlerTest" time="0.0001383" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 3\r\nActual:   0]]></message>
          <stack-trace><![CDATA[   at XmlSerializerTests.XmlUnknownElementAndEventHandlerTest() in d:\OSS\corefx-1\corefx\src\System.Private.Xml\tests\XmlSerializer\XmlSerializerTests.cs:line 2469
   at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean targetIsThisCall)
   at System.InvokeUtils.CalliIntrinsics.Call(IntPtr dynamicInvokeHelperMethod, Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean isTargetThisCall)
   at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, IntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object targetMethodOrDelegate, Object[] parameters, BinderBundle binderBundle, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\InvokeUtils.cs:line 400]]></stack-trace>
        </failure>
      </test>
```

Test `XmlSerializerTests.XmlUnknownNodeAndEventHandlerTest` also failed.

**Comment by shmao** [comment]
This is a duplicate of  #19903.
