### ISSUE TITLE
XmlSerializerTests.XML_TypeWithQNameArrayAsXmlAttribute Failed on UWP

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#19902]
Test `XmlSerializerTests.XML_TypeWithQNameArrayAsXmlAttribute` failed on UWP when using Sg.

```
      <test name="XmlSerializerTests.XML_TypeWithQNameArrayAsXmlAttribute" type="XmlSerializerTests" method="XML_TypeWithQNameArrayAsXmlAttribute" time="0.0000808" result="Fail">
        <failure exception-type="System.InvalidOperationException">
          <message><![CDATA[System.InvalidOperationException : There was an error generating the XML document.\r\n---- System.InvalidOperationException : Token StartAttribute in state Content would result in an invalid XML document.]]></message>
          <stack-trace><![CDATA[   at System.Xml.Serialization.XmlSerializer.Serialize$catch$1() in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializer.cs:line 508
   at System.Xml.Serialization.XmlSerializer.Serialize(Stream stream, Object o, $XmlSerializerNamespaces namespaces) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializer.cs:line 413
   at XmlSerializerTests.SerializeAndDeserialize<System.__Canon>(__Canon value, String baseline, Func$1<$XmlSerializer> serializerFactory, Boolean skipStringCompare, $XmlSerializerNamespaces xns) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\tests\XmlSerializer\XmlSerializerTests.cs:line 4466
   at XmlSerializerTests.XML_TypeWithQNameArrayAsXmlAttribute() in d:\OSS\corefx-1\corefx\src\System.Private.Xml\tests\XmlSerializer\XmlSerializerTests.cs:line 2356
   at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean targetIsThisCall)
   at System.InvokeUtils.CalliIntrinsics.Call(IntPtr dynamicInvokeHelperMethod, Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean isTargetThisCall)
   at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, IntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object targetMethodOrDelegate, Object[] parameters, BinderBundle binderBundle, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\InvokeUtils.cs:line 400
----- Inner Stack Trace -----
   at System.Xml.XmlTextWriter.AutoComplete($Token token) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Core\XmlTextWriter.cs:line 1176
   at System.Xml.XmlTextWriter.WriteStartAttribute$catch$0() in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Core\XmlTextWriter.cs:line 676
   at System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(String prefix, String localName, String ns, String value) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationWriter.cs:line 999
   at System.Xml.Serialization.XmlSerializationWriter.GetQualifiedName(String name, String ns) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationWriter.cs:line 415
   at System.Xml.Serialization.XmlSerializationWriter.FromXmlQualifiedName($XmlQualifiedName xmlQualifiedName, Boolean ignoreEmpty) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationWriter.cs:line 434
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriter1.Write103_Item(String n, String ns, $TypeWithQNameArrayAsXmlAttribute o, Boolean isNullable, Boolean needType, String parentRuntimeNs, String parentCompileTimeNs) in C:\Users\shmao\AppData\Local\Temp\Ilc991344503\xunit.console.netcore.Sg\System.Xml.XmlSerializer.Generated.cs:line 6024
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriter1.Write235_MyXmlType(Object o, String parentRuntimeNs, String parentCompileTimeNs) in C:\Users\shmao\AppData\Local\Temp\Ilc991344503\xunit.console.netcore.Sg\System.Xml.XmlSerializer.Generated.cs:line 1560
   at Microsoft.Xml.Serialization.GeneratedAssembly.TypeWithQNameArrayAsXmlAttributeSerializer.Serialize(Object objectToSerialize, $XmlSerializationWriter writer) in C:\Users\shmao\AppData\Local\Temp\Ilc991344503\xunit.console.netcore.Sg\System.Xml.XmlSerializer.Generated.cs:line 21757
   at System.Xml.Serialization.XmlSerializer.Serialize($XmlWriter xmlWriter, Object o, $XmlSerializerNamespaces namespaces, String encodingStyle, String id) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializer.cs:line 486]]></stack-trace>
        </failure>
      </test>
```

**Comment by shmao** [comment]
This is a duplicate of #19899.
