### ISSUE TITLE
XmlSerializerTests.Xml_TypeWithDefaultTimeSpanProperty Failed on UWP

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#19901]
`XmlSerializerTests.Xml_TypeWithDefaultTimeSpanProperty`  failed on UWP when using Sg.

```
      <test name="XmlSerializerTests.Xml_TypeWithDefaultTimeSpanProperty" type="XmlSerializerTests" method="Xml_TypeWithDefaultTimeSpanProperty" time="0.0002535" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[XML comparison is also failing\r\nTest failed for input: TypeWithDefaultTimeSpanProperty\r\n
Expected: <?xml version=\"1.0\"?>\r\n<TypeWithDefaultTimeSpanProperty xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"><TimeSpanProperty2>PT1M</TimeSpanProperty2></TypeWithDefaultTimeSpanProperty>\r\n
Actual:   <?xml version=\"1.0\"?>\r\n<TypeWithDefaultTimeSpanProperty xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <TimeSpanProperty>PT1M</TimeSpanProperty>\r\n  <TimeSpanProperty2>PT1M</TimeSpanProperty2>\r\n</TypeWithDefaultTimeSpanProperty>\r\n
Expected: True\r\nActual:   False]]>
          </message>
          <stack-trace><![CDATA[   at XmlSerializerTests.SerializeAndDeserialize<System.__Canon>(__Canon value, String baseline, Func$1<$XmlSerializer> serializerFactory, Boolean skipStringCompare, $XmlSerializerNamespaces xns) in d:\OSS\corefx-1\corefx\src\System.Private.Xml\tests\XmlSerializer\XmlSerializerTests.cs:line 4466
   at XmlSerializerTests.Xml_TypeWithDefaultTimeSpanProperty() in d:\OSS\corefx-1\corefx\src\System.Private.Xml\tests\XmlSerializer\XmlSerializerTests.cs:line 1670
   at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean targetIsThisCall)
   at System.InvokeUtils.CalliIntrinsics.Call(IntPtr dynamicInvokeHelperMethod, Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean isTargetThisCall)
   at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, IntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object targetMethodOrDelegate, Object[] parameters, BinderBundle binderBundle, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\InvokeUtils.cs:line 400]]></stack-trace>
        </failure>
      </test>
```

**Comment by shmao** [comment]
We need to port the fix for `Xml_TypeWithDefaultTimeSpanProperty` to sg.exe.

**Comment by shmao** [comment]
Closing the issue as @huanwu had checked in the fix to UWP toolchain.
