### ISSUE TITLE
Desktop: System.Data.SqlClient.Tests.TcpDefaultForAzureTest.NonAzureNoProtocolConnectionTest failed with "System.TypeInitializationException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19918]
Failed test: System.Data.SqlClient.Tests.TcpDefaultForAzureTest.NonAzureNoProtocolConnectionTest

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/59/testReport/System.Data.SqlClient.Tests/TcpDefaultForAzureTest/NonAzureNoProtocolConnectionTest/

Configuration: outerloop_netfx_windows_nt_debug

MESSAGE:
~~~
System.TypeInitializationException : The type initializer for 'System.Data.SqlClient.ManualTesting.Tests.DataTestUtility' threw an exception.
    ---- System.NullReferenceException : Object reference not set to an instance of an object.
~~~
STACK TRACE:
~~~
at System.Data.SqlClient.ManualTesting.Tests.DataTestUtility.IsUsingManagedSNI() 
at System.Data.SqlClient.Tests.TcpDefaultForAzureTest.NonAzureNoProtocolConnectionTest() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Data.SqlClient\tests\FunctionalTests\TcpDefaultForAzureTest.cs:line 39 
----- Inner Stack Trace ----- 
at System.Data.SqlClient.ManualTesting.Tests.DataTestUtility..cctor() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Data.SqlClient\tests\ManualTests\DataCommon\DataTestUtility.cs:line 18
~~~

**Comment by stephentoub** [comment]
@corivera, this is due to https://github.com/dotnet/corefx/pull/19807; the checks are written to expect the implementation in core and blow up with desktop.  That said, why are types in a "ManualTesting" namespace being used in CI... is that just a naming mistake?

**Comment by danmosemsft** [comment]
Also are any of these tests suitable for promoting to innerloop, so CI can protect?

**Comment by CIPop** [comment]
Reopening (please close if expected). This failed again in 2.0.0 Outerloop:

https://ci.dot.net/job/dotnet_corefx/job/release_2.0.0/job/outerloop_netfx_windows_nt_release_prtest/1/consoleFull#19959462502d31e50d-1517-49fc-92b3-2ca637122019
https://ci.dot.net/job/dotnet_corefx/job/release_2.0.0/job/outerloop_netfx_windows_nt_debug_prtest/6/consoleFull#19959462502d31e50d-1517-49fc-92b3-2ca637122019

```
13:45:33     Discovering: System.Globalization.Tests
13:45:34 
      System.Data.SqlClient.Tests.TcpDefaultForAzureTest.NonAzureNoProtocolConnectionTest [FAIL]
13:45:34         System.TypeInitializationException : The type initializer for 'System.Data.SqlClient.ManualTesting.Tests.DataTestUtility' threw an exception.
13:45:34         ---- System.NullReferenceException : Object reference not set to an instance of an object.
13:45:34         Stack Trace:
13:45:34              at System.Data.SqlClient.ManualTesting.Tests.DataTestUtility.IsUsingManagedSNI()
13:45:34           D:\j\workspace\outerloop_net---f52760ab\src\System.Data.SqlClient\tests\FunctionalTests\TcpDefaultForAzureTest.cs(39,0): at System.Data.SqlClient.Tests.TcpDefaultForAzureTest.NonAzureNoProtocolConnectionTest()
13:45:34           ----- Inner Stack Trace -----
13:45:34           D:\j\workspace\outerloop_net---f52760ab\src\System.Data.SqlClient\tests\ManualTests\DataCommon\DataTestUtility.cs(18,0): at System.Data.SqlClient.ManualTesting.Tests.DataTestUtility..cctor()
13:45:34     Discovered:  System.Globalization.Tests
13:45:34     Starting:    System.Globalization.Tests
13:45:38     Finished:    System.Globalization.Tests
13:45:38   === TEST EXECUTION SUMMARY ===
13:45:38      System.Globalization.Tests  Total: 1622, Errors: 0, Failed: 0, Skipped: 0, Time: 4.355s
13:45:38   Finished running tests.  End time=13:45:37.95, Exit code = 0
13:45:38   Using D:\j\workspace\outerloop_net---f52760ab\bin\testhost\netfx-Windows_NT-Debug-x64\ as the test runtime folder.
13:45:38   Executing in D:\j\workspace\outerloop_net---f52760ab\bin\Windows_NT.AnyCPU.Debug\System.IO.FileSystem.AccessControl.Tests\netfx\ 
13:45:38   Running tests... Start time: 13:45:37.99
13:45:38     Finished:    System.Data.SqlClient.Tests
13:45:38   === TEST EXECUTION SUMMARY ===
13:45:39 D:\j\workspace\outerloop_net---f52760ab\Tools\tests.targets(345,5): warning :    System.Data.SqlClient.Tests  Total: 102, Errors: 0, Failed: 1, Skipped: 0, Time: 12.576s [D:\j\workspace\outerloop_net---f52760ab\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
13:45:39   Trying to find crash dumps for project: System.Data.SqlClient.Tests
13:45:39   No new dump file was found in C:\Users\DOTNET~1\AppData\Local\Temp\CoreRunCrashDumps
13:45:39   Finished running tests.  End time=13:45:38.50, Exit code = 0
13:45:39 D:\j\workspace\outerloop_net---f52760ab\Tools\tests.targets(345,5): warning MSB3073: The command "D:\j\workspace\outerloop_net---f52760ab\bin/Windows_NT.AnyCPU.Debug/System.Data.SqlClient.Tests/netstandard//RunTests.cmd D:\j\workspace\outerloop_net---f52760ab\bin/testhost/netfx-Windows_NT-Debug-x64/" exited with code -1. [D:\j\workspace\outerloop_net---f52760ab\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
13:45:39 
D:\j\workspace\outerloop_net---f52760ab\Tools\tests.targets(353,5): error : One or more tests failed while running tests from 'System.Data.SqlClient.Tests' please check D:\j\workspace\outerloop_net---f52760ab\bin/Windows_NT.AnyCPU.Debug/System.Data.SqlClient.Tests/netstandard/testResults.xml for details! [D:\j\workspace\outerloop_net---f52760ab\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
```

**Comment by danmosemsft** [comment]
I see no more reports and no tests disabled for 19918. So closing. cc @saurabh500
