### ISSUE TITLE
AcceptWebSocketAsync_InvalidSubProtocol_ThrowsArgumentException failed with ExtendedSocketException : Device not configured

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#19939]
Only visible in infrastructure log as a later test timed out
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170518.01/workItem/System.Net.HttpListener.Tests/wilogs

```
2017-05-17 17:38:38,891: INFO: proc(54): run_and_log_output: Output:    System.Net.Tests.HttpListenerContextTests.AcceptWebSocketAsync_InvalidSubProtocol_ThrowsArgumentException(subProtocol: \"random:text\") [FAIL]
2017-05-17 17:38:38,891: INFO: proc(54): run_and_log_output: Output:       System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
2017-05-17 17:38:38,891: INFO: proc(54): run_and_log_output: Output:       ---- System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Device not configured
2017-05-17 17:38:38,892: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-17 17:38:38,892: INFO: proc(54): run_and_log_output: Output:             at System.Net.WebSockets.WebSocketHandle.<ConnectAsyncCore>d__24.MoveNext()
2017-05-17 17:38:38,892: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-17 17:38:38,892: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-17 17:38:38,892: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-17 17:38:38,892: INFO: proc(54): run_and_log_output: Output:             at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__16.MoveNext()
2017-05-17 17:38:38,892: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-17 17:38:38,892: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-17 17:38:38,893: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-17 17:38:38,893: INFO: proc(54): run_and_log_output: Output:             at System.Net.Tests.HttpListenerContextTests.<GetWebSocketContext>d__24.MoveNext()
2017-05-17 17:38:38,893: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-17 17:38:38,893: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-17 17:38:38,893: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-17 17:38:38,893: INFO: proc(54): run_and_log_output: Output:             at System.Net.Tests.HttpListenerContextTests.<AcceptWebSocketAsync_InvalidSubProtocol_ThrowsArgumentException>d__16.MoveNext()
2017-05-17 17:38:38,893: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-17 17:38:38,894: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-17 17:38:38,894: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-17 17:38:38,894: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-17 17:38:38,894: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-17 17:38:38,894: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-17 17:38:38,894: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-17 17:38:38,895: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-17 17:38:38,895: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-17 17:38:38,895: INFO: proc(54): run_and_log_output: Output:          ----- Inner Stack Trace -----
2017-05-17 17:38:38,895: INFO: proc(54): run_and_log_output: Output:             at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
2017-05-17 17:38:38,895: INFO: proc(54): run_and_log_output: Output:             at System.Net.Dns.ResolveCallback(Object context)
2017-05-17 17:38:38,895: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-17 17:38:38,896: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-17 17:38:38,896: INFO: proc(54): run_and_log_output: Output:             at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
2017-05-17 17:38:38,896: INFO: proc(54): run_and_log_output: Output:             at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
2017-05-17 17:38:38,896: INFO: proc(54): run_and_log_output: Output:             at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
2017-05-17 17:38:38,896: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-17 17:38:38,896: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-17 17:38:38,897: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-17 17:38:38,897: INFO: proc(54): run_and_log_output: Output:             at System.Net.WebSockets.WebSocketHandle.<ConnectSocketAsync>d__25.MoveNext()
2017-05-17 17:38:38,897: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-17 17:38:38,897: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-17 17:38:38,897: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-17 17:38:38,897: INFO: proc(54): run_and_log_output: Output:             at System.Net.WebSockets.WebSocketHandle.<ConnectAsyncCore>d__24.MoveNext()
```

**Comment by Jiayili1** [comment]
Another test: AcceptWebSocketAsync_InvalidReceiveBufferSize_ThrowsWebSocketException failed with same issue in 2.0.0, detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170523.01/workItem/System.Net.HttpListener.Tests/analysis/xunit/System.Net.Tests.HttpListenerContextTests~2FAcceptWebSocketAsync_InvalidReceiveBufferSize_ThrowsWebSocketException(receiveBufferSize:%20-1)

**Comment by Jiayili1** [comment]
Failed again, detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170525.01/workItem/System.Net.HttpListener.Tests/wilogs

~~~
2017-05-24 17:50:35,836: INFO: proc(54): run_and_log_output: Output:       System.AggregateException : One or more errors occurred. (Unable to connect to the remote server) (Too many open files in system)
2017-05-24 17:50:35,836: INFO: proc(54): run_and_log_output: Output:       ---- System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
2017-05-24 17:50:35,836: INFO: proc(54): run_and_log_output: Output:       -------- System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Device not configured
2017-05-24 17:50:35,836: INFO: proc(54): run_and_log_output: Output:       ---- System.Net.HttpListenerException : Too many open files in system
2017-05-24 17:50:35,836: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-24 17:50:35,836: INFO: proc(54): run_and_log_output: Output:          
2017-05-24 17:50:35,837: INFO: proc(54): run_and_log_output: Output:          ----- Inner Stack Trace #1 (System.Net.WebSockets.WebSocketException) -----
2017-05-24 17:50:35,837: INFO: proc(54): run_and_log_output: Output:             at System.Net.WebSockets.WebSocketHandle.<ConnectAsyncCore>d__24.MoveNext()
2017-05-24 17:50:35,837: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-24 17:50:35,837: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-24 17:50:35,837: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-24 17:50:35,837: INFO: proc(54): run_and_log_output: Output:             at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__16.MoveNext()
2017-05-24 17:50:35,837: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-24 17:50:35,838: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-24 17:50:35,838: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-24 17:50:35,838: INFO: proc(54): run_and_log_output: Output:             at System.Net.Tests.HttpListenerContextTests.<GetWebSocketContext>d__24.MoveNext()
2017-05-24 17:50:35,838: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-24 17:50:35,838: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-24 17:50:35,838: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-24 17:50:35,839: INFO: proc(54): run_and_log_output: Output:             at System.Net.Tests.HttpListenerContextTests.<AcceptWebSocketAsync_InvalidSubProtocol_ThrowsArgumentException>d__16.MoveNext()
2017-05-24 17:50:35,839: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-24 17:50:35,839: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-24 17:50:35,839: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-24 17:50:35,839: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-24 17:50:35,839: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-24 17:50:35,839: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-24 17:50:35,839: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-24 17:50:35,839: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-24 17:50:35,839: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-24 17:50:35,839: INFO: proc(54): run_and_log_output: Output:          ----- Inner Stack Trace -----
2017-05-24 17:50:35,840: INFO: proc(54): run_and_log_output: Output:             at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
2017-05-24 17:50:35,840: INFO: proc(54): run_and_log_output: Output:             at System.Net.Dns.ResolveCallback(Object context)
2017-05-24 17:50:35,840: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-24 17:50:35,840: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-24 17:50:35,840: INFO: proc(54): run_and_log_output: Output:             at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
2017-05-24 17:50:35,840: INFO: proc(54): run_and_log_output: Output:             at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
2017-05-24 17:50:35,840: INFO: proc(54): run_and_log_output: Output:             at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
2017-05-24 17:50:35,840: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-24 17:50:35,840: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-24 17:50:35,841: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-24 17:50:35,841: INFO: proc(54): run_and_log_output: Output:             at System.Net.WebSockets.WebSocketHandle.<ConnectSocketAsync>d__25.MoveNext()
2017-05-24 17:50:35,841: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-24 17:50:35,841: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-24 17:50:35,841: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-24 17:50:35,841: INFO: proc(54): run_and_log_output: Output:             at System.Net.WebSockets.WebSocketHandle.<ConnectAsyncCore>d__24.MoveNext()
2017-05-24 17:50:35,842: INFO: proc(54): run_and_log_output: Output:          ----- Inner Stack Trace #2 (System.Net.HttpListenerException) -----
2017-05-24 17:50:35,842: INFO: proc(54): run_and_log_output: Output:             at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure, Boolean& alreadyExists)
2017-05-24 17:50:35,842: INFO: proc(54): run_and_log_output: Output:             at System.Net.HttpEndPointManager.RemovePrefixInternal(String prefix, HttpListener listener)
2017-05-24 17:50:35,842: INFO: proc(54): run_and_log_output: Output:             at System.Net.HttpEndPointManager.RemoveListener(HttpListener listener)
2017-05-24 17:50:35,842: INFO: proc(54): run_and_log_output: Output:             at System.Net.HttpListener.Close(Boolean force)
2017-05-24 17:50:35,842: INFO: proc(54): run_and_log_output: Output:             at System.Net.HttpListener.Dispose()
2017-05-24 17:50:35,842: INFO: proc(54): run_and_log_output: Output:             at System.Net.HttpListener.Close()
2017-05-24 17:50:35,843: INFO: proc(54): run_and_log_output: Output:             at System.Net.Tests.HttpListenerContextTests.Dispose()
2017-05-24 17:50:35,843: INFO: proc(54): run_and_log_output: Output:             at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
~~~

**Comment by Jiayili1** [comment]
Failed again on 2.0.0 Portable Core Tests, detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170527.02/workItem/System.Net.HttpListener.Tests/wilogs

**Comment by karelz** [comment]
No failure of the test `AcceptWebSocketAsync_InvalidSubProtocol_ThrowsArgumentException` in official Helix runs.

Closing.
