### ISSUE TITLE
AcceptWebSocketAsync_ValidSubProtocol_Success failed with System.Net.HttpListenerException : Address already in use

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#19938]
Only visible in infrastructure log as a later test timed out
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170518.01/workItem/System.Net.HttpListener.Tests/wilogs 
```
2017-05-17 17:38:39,340: INFO: proc(54): run_and_log_output: Output:    System.Net.Tests.HttpListenerContextTests.AcceptWebSocketAsync_ValidSubProtocol_Success(clientProtocols: [\"MyProtocol1\", \"MyProtocol2\"], serverProtocol: \"MyProtocol2\") [FAIL]
2017-05-17 17:38:39,341: INFO: proc(54): run_and_log_output: Output:       System.Net.HttpListenerException : Address already in use
2017-05-17 17:38:39,341: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-17 17:38:39,341: INFO: proc(54): run_and_log_output: Output:             at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure, Boolean& alreadyExists)
2017-05-17 17:38:39,341: INFO: proc(54): run_and_log_output: Output:             at System.Net.HttpEndPointManager.RemovePrefixInternal(String prefix, HttpListener listener)
2017-05-17 17:38:39,342: INFO: proc(54): run_and_log_output: Output:             at System.Net.HttpEndPointManager.RemoveListener(HttpListener listener)
2017-05-17 17:38:39,342: INFO: proc(54): run_and_log_output: Output:             at System.Net.HttpListener.Close(Boolean force)
2017-05-17 17:38:39,342: INFO: proc(54): run_and_log_output: Output:             at System.Net.HttpListener.Dispose()
2017-05-17 17:38:39,342: INFO: proc(54): run_and_log_output: Output:             at System.Net.HttpListener.Close()
2017-05-17 17:38:39,342: INFO: proc(54): run_and_log_output: Output:             at System.Net.Tests.HttpListenerContextTests.Dispose()
2017-05-17 17:38:39,342: INFO: proc(54): run_and_log_output: Output:             at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
```

**Comment by karelz** [comment]
No failure in official Helix runs since 2017/5 and CI runs since 2017/12/6. Closing
