### ISSUE TITLE
EndGetClientCertificate_NullAsyncResult_ThrowsArgumentException failed with ExtendedSocketException : Connection refused 

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#19940]
Only visible in infrastructure log as a later test timed out
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170518.01/workItem/System.Net.HttpListener.Tests/wilogs

```
2017-05-17 17:38:37,926: INFO: proc(54): run_and_log_output: Output:    System.Net.Tests.HttpListenerRequestTests.EndGetClientCertificate_NullAsyncResult_ThrowsArgumentException [FAIL]
2017-05-17 17:38:37,928: INFO: proc(54): run_and_log_output: Output:       System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Connection refused 127.0.0.1:1037
2017-05-17 17:38:37,933: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-17 17:38:38,076: INFO: proc(54): run_and_log_output: Output:             at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
2017-05-17 17:38:38,076: INFO: proc(54): run_and_log_output: Output:             at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
2017-05-17 17:38:38,076: INFO: proc(54): run_and_log_output: Output:             at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
2017-05-17 17:38:38,076: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-17 17:38:38,077: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-17 17:38:38,077: INFO: proc(54): run_and_log_output: Output:             at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
2017-05-17 17:38:38,077: INFO: proc(54): run_and_log_output: Output:             at System.Net.Sockets.Socket.Connect(String host, Int32 port)
2017-05-17 17:38:38,077: INFO: proc(54): run_and_log_output: Output:             at System.Net.Tests.HttpListenerFactory.GetConnectedSocket()
2017-05-17 17:38:38,077: INFO: proc(54): run_and_log_output: Output:             at System.Net.Tests.HttpListenerRequestTests.<GetRequest>d__31.MoveNext()
2017-05-17 17:38:38,077: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-17 17:38:38,078: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-17 17:38:38,078: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-17 17:38:38,078: INFO: proc(54): run_and_log_output: Output:             at System.Net.Tests.HttpListenerRequestTests.<EndGetClientCertificate_NullAsyncResult_ThrowsArgumentException>d__18.MoveNext()
2017-05-17 17:38:38,078: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-17 17:38:38,078: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-17 17:38:38,079: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-17 17:38:38,079: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-17 17:38:38,079: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-17 17:38:38,079: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-17 17:38:38,079: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-17 17:38:38,079: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-17 17:38:38,079: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by karelz** [comment]
Closing as there is not repro + we have a few similar tracking bugs.
