### ISSUE TITLE
KeyInfoX509DataTest.Complex failed with "Invalid handle" on macOS in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#19996]
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release_prtest/3761/consoleText
```
System.Security.Cryptography.Xml.Tests.KeyInfoX509DataTest.Complex [FAIL]
        System.ArgumentException : Invalid handle.
        Parameter name: handle
        Stack Trace:
  Discovering: System.Xml.XmlDocument.Tests
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/CertificatePal.cs(52,0): at Internal.Cryptography.Pal.CertificatePal.FromHandle(IntPtr handle, Boolean throwOnFail)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Certificate.cs(160,0): at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(X509Certificate cert)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/KeyInfoX509Data.cs(117,0): at System.Security.Cryptography.Xml.KeyInfoX509Data.AddCertificate(X509Certificate certificate)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Security.Cryptography.Xml/tests/KeyInfoX509DataTest.cs(224,0): at System.Security.Cryptography.Xml.Tests.KeyInfoX509DataTest.Complex()
```
cc: @krwq, @bartonjs

**Comment by bartonjs** [comment]
Probably a GC.KeepAlive problem in that ctor (pure speculation).

@danmosemsft do we have GCStress runs running anywhere yet?

**Comment by danmosemsft** [comment]
We have completed GCStress mode 3 in Windows and Unix on both release and debug for Crypto and nothing was found. 

It's easy to try yourself locally - set an environment variable TestGCStressLevel=3 and run the tests as normal. It wraps xunit with the COMPLUS variable. You could loop it, maybe over just this test.

**Comment by karelz** [comment]
@ianhays can you please take a look?

**Comment by stephentoub** [comment]
I'll take it; I believe I see the problem.

**Comment by karelz** [comment]
Reopening to track port to rel/2.0.0 branch

**Comment by karelz** [comment]
Ported to 2.0 in PR #20065.
