### ISSUE TITLE
Tests under "System.Net.Sockets.Tests.DualModeConnectionlessBeginSendTo" failed with "System.TimeoutException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19992]
Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170519.01/workItem/System.Net.Sockets.Tests/wilogs

~~~
2017-05-18 17:34:57,141: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.DualModeConnectionlessBeginSendTo.BeginSendToV4IPEndPointToV4Host_Success [FAIL]
2017-05-18 17:34:57,141: INFO: proc(54): run_and_log_output: Output:       System.TimeoutException : The operation has timed out.
2017-05-18 17:34:57,141: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-18 17:34:57,141: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/24/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(1252,0): at System.Net.Sockets.Tests.DualModeConnectionlessBeginSendTo.DualModeBeginSendTo_EndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout)
2017-05-18 17:35:02,218: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.DualModeConnectionlessBeginSendTo.BeginSendToV4IPEndPointToDualHost_Success [FAIL]
2017-05-18 17:35:02,218: INFO: proc(54): run_and_log_output: Output:       System.TimeoutException : The operation has timed out.
2017-05-18 17:35:02,219: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-18 17:35:02,219: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/24/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(1252,0): at System.Net.Sockets.Tests.DualModeConnectionlessBeginSendTo.DualModeBeginSendTo_EndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout)
2017-05-18 17:35:07,265: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.DualModeConnectionlessBeginSendTo.BeginSendToV6IPEndPointToDualHost_Success [FAIL]
2017-05-18 17:35:07,265: INFO: proc(54): run_and_log_output: Output:       System.TimeoutException : The operation has timed out.
2017-05-18 17:35:07,265: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-18 17:35:07,265: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/24/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(1252,0): at System.Net.Sockets.Tests.DualModeConnectionlessBeginSendTo.DualModeBeginSendTo_EndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout)
2017-05-18 17:35:12,650: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.DualModeConnectionlessBeginSendTo.BeginSendToV6IPEndPointToV6Host_Success [FAIL]
2017-05-18 17:35:12,650: INFO: proc(54): run_and_log_output: Output:       System.TimeoutException : The operation has timed out.
2017-05-18 17:35:12,650: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-18 17:35:12,650: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/24/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(1252,0): at System.Net.Sockets.Tests.DualModeConnectionlessBeginSendTo.DualModeBeginSendTo_EndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout)
~~~

**Comment by karelz** [comment]
No failure in Helix history since 2017/5. Closing.
The original failure was on 20170519.01 **portable** - probably some hiccup in that build/run - see #19990.
