### ISSUE TITLE
System.Net.Sockets.Tests.SocketOptionNameTest.FailedConnect_GetSocketOption_SocketOptionNameError failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19990]
Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170519.01/workItem/System.Net.Sockets.Tests/wilogs

~~~
2017-05-18 17:34:01,833: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.SocketOptionNameTest.FailedConnect_GetSocketOption_SocketOptionNameError(simpleGet: False) [FAIL]
2017-05-18 17:34:01,834: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2017-05-18 17:34:01,834: INFO: proc(54): run_and_log_output: Output:       Expected: 1
2017-05-18 17:34:01,834: INFO: proc(54): run_and_log_output: Output:       Actual:   0
2017-05-18 17:34:01,837: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-18 17:34:01,929: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/24/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/SocketOptionNameTest.cs(173,0): at System.Net.Sockets.Tests.SocketOptionNameTest.FailedConnect_GetSocketOption_SocketOptionNameError(Boolean simpleGet)
2017-05-18 17:34:11,952: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.SocketOptionNameTest.FailedConnect_GetSocketOption_SocketOptionNameError(simpleGet: True) [FAIL]
2017-05-18 17:34:11,952: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2017-05-18 17:34:11,952: INFO: proc(54): run_and_log_output: Output:       Expected: 1
2017-05-18 17:34:11,952: INFO: proc(54): run_and_log_output: Output:       Actual:   0
2017-05-18 17:34:11,952: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-18 17:34:11,952: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/24/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/SocketOptionNameTest.cs(173,0): at System.Net.Sockets.Tests.SocketOptionNameTest.FailedConnect_GetSocketOption_SocketOptionNameError(Boolean simpleGet)
~~~

**Comment by karelz** [comment]
No failure of the test in Helix history since 2017/5. Closing.

**Comment by karelz** [comment]
The original failure was on 20170519.01 portable - probably some hiccup in that build/run - see #19992.
