### ISSUE TITLE
Several HttpListener tests with "+" host failing on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#20050]
e.g.
```
System.Net.Tests.HttpListenerPrefixCollectionTests.Add_SamePortDifferentPathDifferentListenerStarted_Works(host: \"+\") [FAIL]
        System.Exception : Could not reserve a port for HttpListener
        ---- System.Net.HttpListenerException : The request is not supported.
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/System.Net.HttpListener/tests/HttpListenerFactory.cs(101,0): at System.Net.Tests.HttpListenerFactory.get_ListeningUrl()
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/System.Net.HttpListener/tests/HttpListenerPrefixCollectionTests.cs(299,0): at System.Net.Tests.HttpListenerPrefixCollectionTests.Add_SamePortDifferentPathDifferentListenerStarted_Works(String host)
           ----- Inner Stack Trace -----
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/System.Net.HttpListener/src/System/Net/Managed/HttpEndPointManager.cs(128,0): at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/System.Net.HttpListener/src/System/Net/Managed/HttpEndPointManager.cs(105,0): at System.Net.HttpEndPointManager.AddPrefixInternal(String p, HttpListener listener)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/System.Net.HttpListener/src/System/Net/Managed/HttpEndPointManager.cs(65,0): at System.Net.HttpEndPointManager.AddListener(HttpListener listener)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/System.Net.HttpListener/src/System/Net/Managed/HttpListener.Managed.cs(53,0): at System.Net.HttpListener.Start()
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/System.Net.HttpListener/tests/HttpListenerFactory.cs(40,0): at System.Net.Tests.HttpListenerFactory..ctor(String hostname, String path)
```

**Comment by stephentoub** [comment]
@Priya91, this looks like a regression caused by https://github.com/dotnet/corefx/pull/19955.
