### ISSUE TITLE
DualModeConnectAsync_DnsEndPointToHost_Helper failed on OSX with Timed out waiting for Connection

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20069]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170521.02/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.DualModeConnectAsync~2FDualModeConnectAsync_DnsEndPointToHost_Helper(listenOn:%20::,%20dualModeServer:%20True)

```
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Timed out while waiting for connection\nExpected: True\nActual:   False
Stack Trace :
   at System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_DnsEndPointToHost_Helper(IPAddress listenOn, Boolean dualModeServer) in /Users/buildagent/agent/_work/29/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 630
```

**Comment by karelz** [comment]
Helix run history:

Day | Build | OS | Error message
-- | -- | -- | --
8/14 | 20170814.02 | OSX 10.12 | Timed out assert

Closing for now (it is rare enough to not be worth tracking with an open issue at this point). Please reopen if it happens again.

**Comment by ViktorHofer** [comment]
Happened again: https://dnceng.visualstudio.com/public/_build/results?buildId=366911&view=ms.vss-test-web.build-test-results-tab&runId=11102492&resultId=178391&paneView=debug

Configuration: `netcoreapp-Windows_NT-Release-x86-Windows.10.Amd64.Client19H1.Open`

**Comment by safern** [comment]
Happened again: https://dev.azure.com/dnceng/public/_build/results?buildId=433228&view=ms.vss-test-web.build-test-results-tab&runId=13729494&resultId=176879&paneView=debug

Configuration: `netcoreapp-Windows_NT-Debug-x64-Windows.10.Amd64.Server19H1.ES.Open`

**Comment by ahsonkhan** [comment]
Happened again (here https://github.com/dotnet/runtime/pull/842 - CI leg: Libraries Build Windows_NT x86 Release):

https://dev.azure.com/dnceng/public/_build/results?buildId=456647&view=logs&j=e701e140-d474-5d33-bf81-51d0b6392301&t=55314c6c-0934-5e06-598c-32fe2a2b27df

https://helix.dot.net/api/2019-06-17/jobs/03b4a925-c34f-4d56-820e-02443bc9d502/workitems/System.Net.Sockets.Tests/console

```text
Starting:    System.Net.Sockets.Tests (parallel test collections = on, max threads = 2)
    System.Net.Sockets.Tests.KeepAliveTest.Socket_KeepAlive_RetryCount_Failure [SKIP]
      Condition(s) not met: "IsWindowsBelow1703"
    System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_DnsEndPointToHost_Helper(listenOn: 127.0.0.1, dualModeServer: False) [FAIL]
      Timed out while waiting for connection
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(588,0): at System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_DnsEndPointToHost_Helper(IPAddress listenOn, Boolean dualModeServer)
```
