### ISSUE TITLE
GetAsync_TrailingHeaders_Ignored failed with System.Net.Http.WinHttpException : The operation has been canceled

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20068]
This is the only 1 failure out of 5367832 tests in today's windows run. @karelz I wish I could say fixing tihs would give us our first green run in years, but there are a number of tests flakily producing errors like this.

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170521.02

```
Unhandled Exception of Type System.Net.Http.HttpRequestException
Message :
System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n----
 System.Net.Http.WinHttpException : The operation has been canceled
Stack Trace :
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass57_0.<<GetAsync_TrailingHeaders_Ignored>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass3_0.<CreateServerAsync>b__0(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__276_1(Object obj)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<GetAsync_TrailingHeaders_Ignored>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
```

**Comment by karelz** [comment]
I think we should start push on tests cleanup after we are in 2.0 Escrow. We need to keep cleaning up our tests which are in the way of doing business efficiently, they also hurt contributors and make it less likely for us to get community contributions. Something we do not want.

We need to have access to good tests failure history across Jenkins and Helix, incl. data which OS, etc. Last few months we had to do it manually and it is incomplete information and HUGE overhead. @Chrisboh is it something we can get somehow from your team? Even weekly-ish XLSX data dumps would be very helpful for analysis of trends and for prioritization.

cc @DavidGoll as I think most of the test failures will be in Networking area.

**Comment by karelz** [comment]
@danmosemsft we should also bulk-edit all test failures in Future into 2.1 milestone. Thoughts?

**Comment by danmosemsft** [comment]
sure

**Comment by Chrisboh** [comment]
@karelz so I can better understand.  Is your goal to identify flaky tests or is your goal to just see when the last time the test failed?

**Comment by karelz** [comment]
My goal is to identify flaky tests - understand where they are failing (which OS combos), and how often (history), so that we can sort them out from the most impactful ones to the least impactful ones.

Of course, we need the ability to associate test failures with issues / with same symptom-issues as some issues are wide-spread, and not just a problem of a set of tests.

Happy to chat more if it helps ...

**Comment by davidsh** [comment]
This test uses the loopback server and yet it had this error:

>System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n----
 System.Net.Http.WinHttpException : The operation has been canceled

which usually happens only when trying to connect the test server over the Internet in Azure.

We haven't seen this failure in a long time, since, so I closing this issue for now.
