### ISSUE TITLE
[HttpListener] [Managed] HttpListener should not hang when missing NTLM/Negotiate authentication is used

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#20101]
Following tests are disabled with this issue:

- NtlmAuthentication_Conversation_ReturnsExpectedType2Message
- NtlmAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode

- NegotiateAuthentication_Conversation_ReturnsExpectedType2Message
- NegotiateAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode

```

   
      System.Net.Tests.AuthenticationTests.NtlmAuthentication_Conversation_ReturnsExpectedType2Message [FAIL]
      Assert.Same() Failure
      Expected: Task<System.Net.Http.HttpResponseMessage> { Status = WaitingForActivation }
      Actual:   Task<System.Net.HttpListenerContext> { Status = RanToCompletion }
      Stack Trace:
            at System.Net.Tests.AuthenticationTests.<AuthenticationFailure>d__35.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at System.Net.Tests.AuthenticationTests.<NtlmAuthentication_Conversation_ReturnsExpectedType2Message>d__15.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   System.Net.Tests.AuthenticationTests.NtlmAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode(header: null, statusCode: Unauthorized) [FAIL]
      Assert.Same() Failure
      Expected: Task<System.Net.Http.HttpResponseMessage> { Status = WaitingForActivation }
      Actual:   Task<System.Net.HttpListenerContext> { Status = RanToCompletion }
      Stack Trace:
            at System.Net.Tests.AuthenticationTests.<AuthenticationFailure>d__35.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at System.Net.Tests.AuthenticationTests.<NtlmAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode>d__17.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   System.Net.Tests.AuthenticationTests.NtlmAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode(header: \"\", statusCode: Unauthorized) [FAIL]
      Assert.Same() Failure
      Expected: Task<System.Net.Http.HttpResponseMessage> { Status = WaitingForActivation }
      Actual:   Task<System.Net.HttpListenerContext> { Status = RanToCompletion }
      Stack Trace:
            at System.Net.Tests.AuthenticationTests.<AuthenticationFailure>d__35.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at System.Net.Tests.AuthenticationTests.<NtlmAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode>d__17.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   System.Net.Tests.AuthenticationTests.NtlmAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode(header: \"abc\", statusCode: BadRequest) [FAIL]
      Assert.Same() Failure
      Expected: Task<System.Net.Http.HttpResponseMessage> { Status = WaitingForActivation }
      Actual:   Task<System.Net.HttpListenerContext> { Status = RanToCompletion }
      Stack Trace:
            at System.Net.Tests.AuthenticationTests.<AuthenticationFailure>d__35.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at System.Net.Tests.AuthenticationTests.<NtlmAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode>d__17.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   System.Net.Tests.AuthenticationTests.NtlmAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode(header: \"abcd\", statusCode: BadRequest) [FAIL]
      Assert.Same() Failure
      Expected: Task<System.Net.Http.HttpResponseMessage> { Status = WaitingForActivation }
      Actual:   Task<System.Net.HttpListenerContext> { Status = RanToCompletion }
      Stack Trace:
            at System.Net.Tests.AuthenticationTests.<AuthenticationFailure>d__35.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at System.Net.Tests.AuthenticationTests.<NtlmAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode>d__17.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   System.Net.Tests.AuthenticationTests.NegotiateAuthentication_Conversation_ReturnsExpectedType2Message [FAIL]
      Assert.Same() Failure
      Expected: Task<System.Net.Http.HttpResponseMessage> { Status = WaitingForActivation }
      Actual:   Task<System.Net.HttpListenerContext> { Status = RanToCompletion }
      Stack Trace:
            at System.Net.Tests.AuthenticationTests.<AuthenticationFailure>d__35.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at System.Net.Tests.AuthenticationTests.<NegotiateAuthentication_Conversation_ReturnsExpectedType2Message>d__18.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   System.Net.Tests.AuthenticationTests.NegotiateAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode(header: null, statusCode: Unauthorized) [FAIL]
      Assert.Same() Failure
      Expected: Task<System.Net.Http.HttpResponseMessage> { Status = WaitingForActivation }
      Actual:   Task<System.Net.HttpListenerContext> { Status = RanToCompletion }
      Stack Trace:
            at System.Net.Tests.AuthenticationTests.<AuthenticationFailure>d__35.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at System.Net.Tests.AuthenticationTests.<NegotiateAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode>d__19.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   System.Net.Tests.AuthenticationTests.NegotiateAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode(header: \"\", statusCode: Unauthorized) [FAIL]
      Assert.Same() Failure
      Expected: Task<System.Net.Http.HttpResponseMessage> { Status = WaitingForActivation }
      Actual:   Task<System.Net.HttpListenerContext> { Status = RanToCompletion }
      Stack Trace:
            at System.Net.Tests.AuthenticationTests.<AuthenticationFailure>d__35.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at System.Net.Tests.AuthenticationTests.<NegotiateAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode>d__19.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   System.Net.Tests.AuthenticationTests.NegotiateAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode(header: \"abc\", statusCode: BadRequest) [FAIL]
      Assert.Same() Failure
      Expected: Task<System.Net.Http.HttpResponseMessage> { Status = WaitingForActivation }
      Actual:   Task<System.Net.HttpListenerContext> { Status = RanToCompletion }
      Stack Trace:
            at System.Net.Tests.AuthenticationTests.<AuthenticationFailure>d__35.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at System.Net.Tests.AuthenticationTests.<NegotiateAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode>d__19.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   System.Net.Tests.AuthenticationTests.NegotiateAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode(header: \"abcd\", statusCode: BadRequest) [FAIL]
      Assert.Same() Failure
      Expected: Task<System.Net.Http.HttpResponseMessage> { Status = WaitingForActivation }
      Actual:   Task<System.Net.HttpListenerContext> { Status = RanToCompletion }
      Stack Trace:
            at System.Net.Tests.AuthenticationTests.<AuthenticationFailure>d__35.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at System.Net.Tests.AuthenticationTests.<NegotiateAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode>d__19.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by axelheer** [comment]
Does that mean the current version of `System.Net.Http` does not properly support NTLM?

We had an issue with a .NET Core application because of some change (.NET Core 1.1.2?). That application could not access SQL Server Reporting Services using NTLM. It just didn't send the "2nd request" and quit with "unauthorized"...

That said problem affects only one server I've not quite access to, and we solved it using basic authentication. Thus, I cannot really provide more details - I'm just curious.

**Comment by hughbe** [comment]
@axelheer this issue is specific to System.Net.HttpListener on Unix - it doesn't seem to be related to your issue. Maybe @davidsh/@stephentoub could comment?

**Comment by stephentoub** [comment]
> That application could not access SQL Server Reporting Services using NTLM

Via what client type on what OS?

**Comment by axelheer** [comment]
Okay, thanks, doesn't matter since the ops staff already switched from Ntlm to Basic.

If you're still interested: it's an environment of windows servers without any windows domain.  It's an ASP.NET Core web application running on .NET Core, which uses `HttpClient` with `NetworkCredential` to get some rendered reports from SSRS 2016. The web application runs on a Windows Server 2012 R2 machine within an IIS web site. The problem: the web requests from web app to SSRS didn't follow the usual 401/401/200 pattern, the app somehow gave up before sending the final "authentication message".

I wasn't able to reproduce this on my Windows 7 (yay) dev box, so they just switched protocol. "On my machine" I've got nice 401/401/200 messages running the same code / configuration.

Since it's "fixed" and I'm not able to do further testing, there's no need to bother you on my account.

**Comment by stephentoub** [comment]
Back to the original issue...
For 2.0 we should ensure HttpListener doesn't hang when such schemes are used.  If or when that's the case, actually supporting such auth schemes is post-2.0.

**Comment by hughbe** [comment]
Adding:
- UnsafeConnectionNtlmAuthentication_Unix_ThrowsPlatformNotSupportedException
- UnsafeConnectionNtlmAuthentication_SetGet_ReturnsExpected
- UnsafeConnectionNtlmAuthentication_SetDisposed_ThrowsObjectDisposedException

under this issue
