### ISSUE TITLE
X509Certificates.Tests.PfxTests.TestSetPrivateKey failure in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2010]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/1718/console
```
System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestSetPrivateKey [FAIL]
        System.Security.Cryptography.CryptographicException : OpenCSP failed with Error code 
        Stack Trace:
              at Internal.NativeCrypto.CapiHelper.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
              at Internal.NativeCrypto.CapiHelper.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 keySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
              at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
              at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 keySize, CspParameters parameters, Boolean useDefaultKeySize)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.PrivateKey.cs(49,0): at Internal.Cryptography.Pal.CertificatePal.get_PrivateKey()
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2.cs(164,0): at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Security.Cryptography.X509Certificates\tests\PfxTests.cs(104,0): at System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestSetPrivateKey()
```

**Comment by bartonjs** [comment]
On the one hand, nothing was done to resolve the intermittency.  On the other hand, the TestSetPrivateKey test was removed, because set_PrivateKey was removed from the contract.
