### ISSUE TITLE
Various tests now failing on Windows with  Unexpected async error in WinHttpRequestCallback: 12007, WinHttp API: 5

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20163]
example (affects various libraries) https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170523.02/workItem/System.Xml.XmlSchemaSet.Tests/wilogs

```c#
            Debug.Assert((unchecked((uint)asyncResult.dwResult.ToInt32()) != Interop.WinHttp.API_SEND_REQUEST &&
                ((unchecked((uint)asyncResult.dwResult.ToInt32()) != Interop.WinHttp.API_RECEIVE_RESPONSE) ||
                (asyncResult.dwError == Interop.WinHttp.ERROR_WINHTTP_RESEND_REQUEST) ||
                (asyncResult.dwError == Interop.WinHttp.ERROR_WINHTTP_CLIENT_AUTH_CERT_NEEDED) ||
                (asyncResult.dwError == Interop.WinHttp.ERROR_WINHTTP_OPERATION_CANCELLED))),
                $"Unexpected async error in WinHttpRequestCallback: {unchecked((int)asyncResult.dwError)}, WinHttp API: {unchecked((uint)asyncResult.dwResult.ToInt32())}"
            );
```
12007 = ERROR_WINHTTP_NAME_NOT_RESOLVED        
5 = API_SEND_REQUEST

```
2017-05-23 03:31:19,641: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Xml.XmlSchemaSet.Tests
2017-05-23 03:31:19,766: INFO: proc(54): run_and_log_output: Output: Starting:    System.Xml.XmlSchemaSet.Tests
2017-05-23 03:31:21,963: INFO: proc(54): run_and_log_output: Output: FailFast: Unexpected async error in WinHttpRequestCallback: 12007, WinHttp API: 5
2017-05-23 03:31:21,963: INFO: proc(54): run_and_log_output: Output: 
2017-05-23 03:31:21,963: INFO: proc(54): run_and_log_output: Output:    at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
2017-05-23 03:31:21,963: INFO: proc(54): run_and_log_output: Output:    at System.Net.Http.WinHttpRequestCallback.OnRequestError(WinHttpRequestState state, WINHTTP_ASYNC_RESULT asyncResult)
2017-05-23 03:31:21,963: INFO: proc(54): run_and_log_output: Output:    at System.Net.Http.WinHttpRequestCallback.RequestCallback(IntPtr handle, WinHttpRequestState state, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
2017-05-23 03:31:21,963: INFO: proc(54): run_and_log_output: Output:    at System.Net.Http.WinHttpRequestCallback.WinHttpCallback(IntPtr handle, IntPtr context, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
2017-05-23 03:31:21,963: INFO: proc(54): run_and_log_output: Output: 
2017-05-23 03:31:21,963: INFO: proc(54): run_and_log_output: Output:    at System.Environment.FailFast(System.String, System.Exception)
2017-05-23 03:31:21,963: INFO: proc(54): run_and_log_output: Output:    at System.Net.Http.WinHttpRequestCallback.OnRequestError(System.Net.Http.WinHttpRequestState, WINHTTP_ASYNC_RESULT)
2017-05-23 03:31:21,963: INFO: proc(54): run_and_log_output: Output:    at System.Net.Http.WinHttpRequestCallback.RequestCallback(IntPtr, System.Net.Http.WinHttpRequestState, UInt32, IntPtr, UInt32)
2017-05-23 03:31:21,963: INFO: proc(54): run_and_log_output: Output:    at System.Net.Http.WinHttpRequestCallback.WinHttpCallback(IntPtr, IntPtr, UInt32, IntPtr, UInt32)
2017-05-23 03:31:22,040: INFO: proc(54): run_and_log_output: Output: Finished running tests.  End time= 3:31:22.04, Exit code = -2146232797
```

@stephentoub  this appears to be your recently added assert. Not sure whether assert is the problem though

**Comment by danmosemsft** [comment]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170523.02/workItem/System.Net.WebClient.Tests/wilogs

another variation
`2017-05-23 03:33:15,591: INFO: proc(54): run_and_log_output: Output: FailFast: Unexpected async error in WinHttpRequestCallback: 12030, WinHttp API: 1`

12030 = ERROR_WINHTTP_CONNECTION_ERROR         
1= API_RECEIVE_RESPONSE

**Comment by stephentoub** [comment]
> @stephentoub this appears to be your recently added assert. Not sure whether assert is the problem though

No, this is from @schen381's change in https://github.com/dotnet/corefx/pull/20011

**Comment by danmosemsft** [comment]
You're quite right. I misread blame.
 @davidsh

**Comment by danmosemsft** [comment]
Not just Nano. Eg
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170523.02/workItem/System.Net.Http.Functional.Tests/wilogs
I see
`FailFast: Unexpected async error in WinHttpRequestCallback: 12182, WinHttp API: 1`
and
`FailFast: Unexpected async error in WinHttpRequestCallback: 12029, WinHttp API: 5`
for example
