### ISSUE TITLE
Tooling: msbuild /t:UpdateVSConfigurations fails with empty sequence exception

### ISSUE THREAD

**Issue by FransBouma** [dotnet/corefx#20225]
To update the solutions in the CoreFX repo after a configuration change in a props file, e.g. a platform was added for a given csproj, the command `msbuild /t:UpdateVSConfigurations` can be used (see: https://github.com/dotnet/corefx/pull/19885#issuecomment-303162997). However when I do that (as I needed to), I get the following exception:

```
C:\Myprojects\corefx>msbuild /t:UpdateVSConfigurations
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 23-5-2017 11:32:23.
Project "C:\Myprojects\corefx\build.proj" on node 1 (UpdateVSConfigurations target(s)).
UpdateVSConfigurations:
  Updating configurations for projects ...
C:\Myprojects\corefx\build.proj(66,5): error MSB4018: The "UpdateVSConfigurations" task failed unexpectedly.\r
C:\Myprojects\corefx\build.proj(66,5): error MSB4018: System.InvalidOperationException: Sequence contains no elements\r
C:\Myprojects\corefx\build.proj(66,5): error MSB4018:    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)\r
C:\Myprojects\corefx\build.proj(66,5): error MSB4018:    at Microsoft.DotNet.Build.Tasks.UpdateVSConfigurations.EnsureProjectGuid(ProjectRootElement project)\r
C:\Myprojects\corefx\build.proj(66,5): error MSB4018:    at Microsoft.DotNet.Build.Tasks.UpdateVSConfigurations.Execute()\r
C:\Myprojects\corefx\build.proj(66,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\r
C:\Myprojects\corefx\build.proj(66,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
Done Building Project "C:\Myprojects\corefx\build.proj" (UpdateVSConfigurations target(s)) -- FAILED.


Build FAILED.

"C:\Myprojects\corefx\build.proj" (UpdateVSConfigurations target) (1) ->(UpdateVSConfigurations target) ->
  C:\Myprojects\corefx\build.proj(66,5): error MSB4018: The "UpdateVSConfigurations" task failed unexpectedly.\r
C:\Myprojects\corefx\build.proj(66,5): error MSB4018: System.InvalidOperationException: Sequence contains no elements\r
C:\Myprojects\corefx\build.proj(66,5): error MSB4018:    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)\r
C:\Myprojects\corefx\build.proj(66,5): error MSB4018:    at Microsoft.DotNet.Build.Tasks.UpdateVSConfigurations.EnsureProjectGuid(ProjectRootElement project)\r
C:\Myprojects\corefx\build.proj(66,5): error MSB4018:    at Microsoft.DotNet.Build.Tasks.UpdateVSConfigurations.Execute()\r
C:\Myprojects\corefx\build.proj(66,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\r
C:\Myprojects\corefx\build.proj(66,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.54
```

This is on the latest CoreFX master as of yesterday. 

TIA

**Comment by karelz** [comment]
@mellinoe @weshaggard any idea?

**Comment by danmosemsft** [comment]
Need a buildtools update. Was fixed in https://github.com/dotnet/buildtools/pull/1509 it looks like

**Comment by FransBouma** [comment]
@danmosemsft You're absolutely right! I completely overlooked the line in Ericstj's post where he even says it is broken. Will close this one.

**Comment by weshaggard** [comment]
A version of BuildTools with this fix just merged into master this morning.
