### ISSUE TITLE
Various System.Net.HttpListener tests fail with "IOException : Too many open files" on OSX

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#20226]
Failed test: System.Net.Tests.SimpleHttpTests.UnknownHeaders_Success(numHeaders: 100)

Mac OSX failure:

Detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170524.01/workItem/System.Net.HttpListener.Tests/wilogs

~~~
2017-05-23 17:43:44,222: INFO: proc(54): run_and_log_output: Output:    System.Net.Tests.SimpleHttpTests.UnknownHeaders_Success(numHeaders: 100) [FAIL]
2017-05-23 17:43:44,224: INFO: proc(54): run_and_log_output: Output:       System.Net.Http.HttpRequestException : An error occurred while sending the request.
2017-05-23 17:43:44,224: INFO: proc(54): run_and_log_output: Output:       ---- System.IO.IOException : Too many open files
2017-05-23 17:43:44,229: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-23 17:43:44,381: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-23 17:43:44,381: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-23 17:43:44,386: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/31/s/corefx/src/System.Net.Http/src/System/Net/Http/HttpClient.cs(462,0): at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
2017-05-23 17:43:44,387: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-23 17:43:44,387: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-23 17:43:44,387: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-23 17:43:44,387: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/31/s/corefx/src/System.Net.HttpListener/tests/SimpleHttpTests.cs(145,0): at System.Net.Tests.SimpleHttpTests.<UnknownHeaders_Success>d__13.MoveNext()
2017-05-23 17:43:44,387: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-23 17:43:44,387: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-23 17:43:44,388: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-23 17:43:44,388: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-23 17:43:44,388: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-23 17:43:44,388: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-23 17:43:44,388: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-05-23 17:43:44,388: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-05-23 17:43:44,389: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-23 17:43:44,389: INFO: proc(54): run_and_log_output: Output:          ----- Inner Stack Trace -----
2017-05-23 17:43:44,389: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/31/s/corefx/src/Common/src/Interop/Unix/Interop.IOErrors.cs(23,0): at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
2017-05-23 17:43:44,389: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/31/s/corefx/src/Common/src/Interop/Unix/Interop.IOErrors.cs(50,0): at Interop.CheckIo(Int64 result, String path, Boolean isDirectory, Func`2 errorRewriter)
2017-05-23 17:43:44,389: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/31/s/corefx/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.MultiAgent.cs(151,0): at System.Net.Http.CurlHandler.MultiAgent.EnsureWorkerIsRunning()
2017-05-23 17:43:44,390: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/31/s/corefx/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.MultiAgent.cs(105,0): at System.Net.Http.CurlHandler.MultiAgent.Queue(IncomingRequest request)
2017-05-23 17:43:44,390: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/31/s/corefx/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.cs(471,0): at System.Net.Http.CurlHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
~~~

**Comment by karelz** [comment]
cc @hughbe @stephentoub - one time Mac OS failure, moving to 2.1.
If you know what's wrong from top of your head, we could fix it in 2.0, because these are new tests ...

**Comment by stephentoub** [comment]
I expect it's related to https://github.com/dotnet/corefx/issues/19754.  2.1 is ok.

**Comment by karelz** [comment]
Should we close it as dupe, or is it "just" related?

**Comment by stephentoub** [comment]
Don't know without investigating both.

**Comment by karelz** [comment]
OK, let's see if the failures are more common ... then we can invest ...

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/20176

**Comment by danmosemsft** [comment]
```
2017-05-29 17:37:57,049: INFO: proc(54): run_and_log_output: Output:    System.Net.Tests.HttpListenerResponseCookiesTests.Cookies_SetAndSend_ClientReceivesExpectedHeaders(cookies: [name=value], expectedBytes: 144, expectedSetCookie: \"Set-Cookie: name=value\", expectedSetCookie2: null) [FAIL]
2017-05-29 17:37:57,050: INFO: proc(54): run_and_log_output: Output:       System.Net.Sockets.SocketException : Too many open files in system
2017-05-29 17:37:57,055: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-29 17:37:57,178: INFO: proc(54): run_and_log_output: Output:             at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
2017-05-29 17:37:57,178: INFO: proc(54): run_and_log_output: Output:             at System.Net.Tests.HttpListenerFactory.GetConnectedSocket()
2017-05-29 17:37:57,178: INFO: proc(54): run_and_log_output: Output:             at System.Net.Tests.HttpListenerResponseTestBase..ctor()
2017-05-29 17:37:57,179: INFO: proc(54): run_and_log_output: Output:             at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
```

**Comment by stephentoub** [comment]
@mmitche, are we no longer upping the ulimit on open files on macOS?

**Comment by mmitche** [comment]
@stephentoub Different set of machines (Helix).  @MattGal do you know how those were set up?

**Comment by danmosemsft** [comment]
I'm going to close issues of this type based on the assumption they are fixed by @janvorli in https://github.com/dotnet/coreclr/pull/14054. Please reopen if not.
