### ISSUE TITLE
Tests under "System.Diagnostics.Tests.ProcessStartInfoTests" failed with "Xunit.Sdk.StartWithException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#20286]
Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170525.01/workItem/System.Diagnostics.Process.Tests/wilogs

~~~
2017-05-25 00:34:23,901: INFO: proc(54): run_and_log_output: Output: Discovering: System.Diagnostics.Process.Tests
2017-05-25 00:34:24,151: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Diagnostics.Process.Tests
2017-05-25 00:34:24,260: INFO: proc(54): run_and_log_output: Output: Starting:    System.Diagnostics.Process.Tests
2017-05-25 00:34:24,838: INFO: proc(54): run_and_log_output: Output:    System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_WebPage [SKIP]
2017-05-25 00:34:24,838: INFO: proc(54): run_and_log_output: Output:       Manual test
2017-05-25 00:34:25,622: INFO: proc(54): run_and_log_output: Output:    System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent(useShellExecute: False) [FAIL]
2017-05-25 00:34:25,622: INFO: proc(54): run_and_log_output: Output:       Assert.StartsWith() Failure:
2017-05-25 00:34:25,622: INFO: proc(54): run_and_log_output: Output:       Expected: StartInfo_NotepadWithContent_956_ad11a149.txt
2017-05-25 00:34:25,622: INFO: proc(54): run_and_log_output: Output:       Actual:   StartInfo_NotepadWithContent_956_ad11a149 - N...
2017-05-25 00:34:25,638: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-25 00:34:25,763: INFO: proc(54): run_and_log_output: Output:             at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent(Boolean useShellExecute)
2017-05-25 00:34:25,763: INFO: proc(54): run_and_log_output: Output:    System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent(useShellExecute: True) [FAIL]
2017-05-25 00:34:25,763: INFO: proc(54): run_and_log_output: Output:       Assert.StartsWith() Failure:
2017-05-25 00:34:25,763: INFO: proc(54): run_and_log_output: Output:       Expected: StartInfo_NotepadWithContent_956_7922b544.txt
2017-05-25 00:34:25,763: INFO: proc(54): run_and_log_output: Output:       Actual:   StartInfo_NotepadWithContent_956_7922b544 - N...
2017-05-25 00:34:25,763: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-25 00:34:25,763: INFO: proc(54): run_and_log_output: Output:             at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent(Boolean useShellExecute)
2017-05-25 00:34:25,809: INFO: proc(54): run_and_log_output: Output:    System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute [FAIL]
2017-05-25 00:34:25,809: INFO: proc(54): run_and_log_output: Output:       Assert.StartsWith() Failure:
2017-05-25 00:34:25,809: INFO: proc(54): run_and_log_output: Output:       Expected: StartInfo_TextFile_ShellExecute_982_8f4d0e14.txt
2017-05-25 00:34:25,809: INFO: proc(54): run_and_log_output: Output:       Actual:   StartInfo_TextFile_ShellExecute_982_8f4d0e14 - N...
2017-05-25 00:34:25,809: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-25 00:34:25,809: INFO: proc(54): run_and_log_output: Output:             at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute()

~~~

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/pull/20293
