### ISSUE TITLE
SSLStream Issue in Docker

### ISSUE THREAD

**Issue by chrismcv** [dotnet/corefx#20311]
Hi, I'm getting some strange behaviour.

I'm running my CoreCLR App in a docker container on recent docker on ubuntu16. using the dotnet/runtime:1.1 container, and nothing unusual in the setup.

I have a rest endpoint that fires an email off. I hit it once, and it fails. I hit it again, and it succeeds.

Here are the logs
```
root@u-dev-test-3:/home/chris# docker logs my-api -f
Hosting environment: Production
Content root path: /app
Now listening on: https://*:4907
Application started. Press Ctrl+C to shut down.
RevocationStatus - Unknown unable to get certificate CRL
Exception caught whilst sending an email: System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at Services.System.CustomEmailService.Post(CustomEmailRequest req) in C:\code\app\api\Services\Customers\CustomEmailService.cs:line 393
Error getting recent file
Connected to smtps://smtp.sendgrid.net:465/
S: 220 SG ESMTP service ready at ismtpd0004p1lon1.sendgrid.net
C: EHLO [172.17.0.2]
S: 250-smtp.sendgrid.net
S: 250-8BITMIME
S: 250-PIPELINING
S: 250-SIZE 31457280
S: 250-AUTH PLAIN LOGIN
S: 250 AUTH=PLAIN LOGIN
C: AUTH PLAIN AGJsdWV6aW5jMzMzMzMzAGJsdTN6MW5j
S: 235 Authentication successful
C: MAIL FROM:<chris@not-real-address.com>
C: RCPT TO:<chris@not-real-address.com>
S: 250 Sender address accepted
S: 250 Recipient address accepted
C: DATA
S: 354 Continue
C: From: chris@not-real-address.com
C: Date: Thu, 25 May 2017 13:49:22 +0000
C: Subject:
C: Message-Id: <MPI8LMY6E1U4.IZX4K9GQFKUP2@localhost.localdomain>
C: To: chris@not-real-address.com
C: MIME-Version: 1.0
C: Content-Type: text/html; charset=utf-8
C: Content-Id: <8TN8LMY6E1U4.B6BKSR2FKAG73@localhost.localdomain>
C:
C: <!DOCTYPE html><html><head><link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Alegreya|Alegreya+Sans|Anonymous+Pro|Archivo+Narrow|Arvo|Bitter|Cardo|Chivo|Crimson+Text|Domine|Fira+Sans|Inconsolata|Karla|Lato|Libre+Baskerville|Lora|Merriweather|Montserrat|Neuton|Old+Standard TT|Open+Sans|Playfair+Display|Poppins|PT+Serif|Roboto|Roboto+Slab|Source+Sans Pro|Source+Serif Pro|Varela+Round|Work+Sans"></head><body><p></p></body></html>
C:
C: .
S: 250 Ok: queued as IoQqdt0uRHSF591FrLzi9A
C: QUIT
S: 221 See you later
```
```c#
using (var client = new SmtpClient(new ProtocolLogger(Console.OpenStandardOutput())))
{
    client.ServerCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) =>
    {
        if (sslPolicyErrors == SslPolicyErrors.None)
            return true;

        // if there are errors in the certificate chain, look at each error to determine the cause.
        if ((sslPolicyErrors & SslPolicyErrors.RemoteCertificateChainErrors) != 0)
        {
            if (chain != null && chain.ChainStatus != null)
            {

                foreach (var status in chain.ChainStatus)
                {
                    Console.WriteLine(status.Status + " - " + status.StatusInformation);
                    if (status.StatusInformation.Contains("Unknown unable to get certificate CRL"))
                    {
                        continue;
                    }
                    if ((certificate.Subject == certificate.Issuer) && (status.Status == X509ChainStatusFlags.UntrustedRoot))
                    {
                        // self-signed certificates with an untrusted root are valid. 
                        continue;
                    }
                    else if (status.Status != X509ChainStatusFlags.NoError)
                    {
                        // if there are any other errors in the certificate chain, the certificate is invalid,
                        // so the method returns false.
                        return false;
                    }
                }
            }

            // When processing reaches this line, the only errors in the certificate chain are 
            // untrusted root errors for self-signed certificates. These certificates are valid
            // for default Exchange server installations, so return true.
            return true;

        }

        return false;
    };

    client.AuthenticationMechanisms.Remove("XOAUTH2");
    client.Connect(appSettings.Get("SMTP:Server", ""), appSettings.Get("SMTP:Port", 25));
    client.Authenticate(appSettings.Get("SMTP:User", ""), appSettings.Get("SMTP:Password", ""));
    client.Send(msg);
    client.Disconnect(true);
    return msg;
}
```
I'm using smtp.sendgrid.net:465 in my config.

I put a connection to the SmtpClient in my app startup, and the email works if I send fairly soon, but if I leave it idle for a while < 2 hours, then it fails again.

Any advice on what might be the issue?

**Comment by wfurt** [comment]
The ssl will need trusted CAs. Do you have that in your container @chrismcv 
Could you possibly isolate this to simple repro app?

**Comment by karelz** [comment]
No response for a week, closing. If you have more info, please let us know and we can reopen.
