### ISSUE TITLE
System.IO.Tests.FileStream_ctor_sfh_fa_buffer_async.InvalidBufferSizeThrows can fail with ODE

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20368]
I can't see why this should fail, it's in a `using`. @ianhays ? Note this is desktop impl

```
      System.IO.Tests.FileStream_ctor_sfh_fa_buffer_async.InvalidBufferSizeThrows [FAIL]
10:47:06         Assert.Throws() Failure
10:47:06         Expected: typeof(System.ArgumentOutOfRangeException)
10:47:06         Actual:   typeof(System.ObjectDisposedException): Cannot access a closed file.
10:47:06         Stack Trace:
10:47:06              at System.IO.__Error.FileNotOpen()
10:47:06              at System.IO.FileStream.Flush(Boolean flushToDisk)
10:47:06              at System.IO.FileStream.get_SafeFileHandle()
10:47:06           D:\j\workspace\netfx_windows---50c21bdb\src\System.IO.FileSystem\tests\FileStream\ctor_sfh_fa_buffer.cs(30,0): at System.IO.Tests.FileStream_ctor_sfh_fa_buffer.<>c__DisplayClass2_0.<InvalidBufferSizeThrows>b__1()
```

**Comment by ianhays** [comment]
That's odd. [The only place we would have closed that handle](http://referencesource.microsoft.com/?#mscorlib/system/io/filestream.cs,920) is only on async streams. Since the handle isn't exposed elsewhere, i don't see any other place we would have closed it between the constructor and the subsequent call to the `SafeFileHandle` getter.

**Comment by danmosemsft** [comment]
Not seen since...
