### ISSUE TITLE
Could not find file 'C:\Program Files\dotnet\sdk\1.0.4\minimumMSBuildVersion'

### ISSUE THREAD

**Issue by vsccarl** [dotnet/corefx#20386]
In the latest d15prerel (26526.3001) I'm getting the below error when trying to build any .net Core project. The logs are the same for both C# and VB. The folder exists, but as the logs say, the file is missing.

```
1>------ Build started: Project: ConsoleApp3, Configuration: Debug Any CPU ------
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014: The build stopped unexpectedly because of an internal failure.
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014: System.IO.FileNotFoundException: Could not find file 'C:\Program Files\dotnet\sdk\1.0.4\minimumMSBuildVersion'.
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014: File name: 'C:\Program Files\dotnet\sdk\1.0.4\minimumMSBuildVersion'
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014:    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014:    at System.IO.StreamReader..ctor(String path, Encoding encoding)
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014:    at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014:    at System.IO.File.ReadAllLines(String path)
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014:    at Microsoft.DotNet.MSBuildSdkResolver.DotNetMSBuildSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext context, SdkResultFactory factory)
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014:    at Microsoft.Build.BackEnd.SdkResolution.GetSdkPath(SdkReference sdk, ILoggingService logger, BuildEventContext buildEventContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath)
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014: The build stopped unexpectedly because of an internal failure.
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014: System.IO.FileNotFoundException: Could not find file 'C:\Program Files\dotnet\sdk\1.0.4\minimumMSBuildVersion'.
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014: File name: 'C:\Program Files\dotnet\sdk\1.0.4\minimumMSBuildVersion'
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014:    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014:    at System.IO.StreamReader..ctor(String path, Encoding encoding)
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014:    at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014:    at System.IO.File.ReadAllLines(String path)
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014:    at Microsoft.DotNet.MSBuildSdkResolver.DotNetMSBuildSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext context, SdkResultFactory factory)
1>C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.vbproj : error MSB4014:    at Microsoft.Build.BackEnd.SdkResolution.GetSdkPath(SdkReference sdk, ILoggingService logger, BuildEventContext buildEventContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath)
1>vbc : warning BC40057: Namespace or type specified in the project-level Imports 'System.Data' doesn't contain any public member or cannot be found. Make sure the namespace or the type is defined and contains at least one public member. Make sure the imported element name doesn't use any aliases.
1>ConsoleApp3 -> C:\Users\v-sccarl\Source\Repos\ConsoleApp3\ConsoleApp3\bin\Debug\netcoreapp1.1\ConsoleApp3.dll
1>Done building project "ConsoleApp3.vbproj".
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========

```

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/cli #6702](https://github.com/dotnet/cli/issues/6702) via [**ZenHub**](https://www.zenhub.com/)
