### ISSUE TITLE
Desktop: System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute fails occasionally on NETFX

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#20388]
Failed test: System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute (from System.Diagnostics.Process.Tests) 

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/67/testReport/System.Diagnostics.Tests/ProcessStartInfoTests/StartInfo_TextFile_ShellExecute/

Configuration: outerloop_netfx_windows_nt_debug

MESSAGE:
~~~
System.NullReferenceException : Object reference not set to an instance of an object.
~~~
STACK TRACE:
~~~
at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs:line 1013
~~~

**Comment by v-haren** [comment]
failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug/56/testReport/System.Diagnostics.Tests/ProcessStartInfoTests/StartInfo_TextFile_ShellExecute/

**Comment by stephentoub** [comment]
This has been failing a lot, on both netfx and netcoreapp.

**Comment by danmosemsft** [comment]
I can't see the issue, I'll disable it. Hopefully you can figure this ot Jeremy as it's the only shell execute test we have.

**Comment by danmosemsft** [comment]
Leaving this in 2.0 as it's important we re-enable this test for 2.0 as its' the only coverage of shell execute.

**Comment by danmosemsft** [comment]
@JeremyKuhne can you figure this out? I'm not comfortable shipping 2.0 with this test disabled, both because we might miss a regression, and because we'll be servicing 2.0 for a while.

**Comment by JeremyKuhne** [comment]
@danmosemsft I can look. We do have the test that uses shell execute with the app name. I presume there is something with the machines that doesn't have the file association in a known state. Fair warning- this will probably take a while to investigate.

**Comment by JeremyKuhne** [comment]
Note that we need to update the UAP exclusion in any case. They shouldn't be skipped for UAP, just the title verification should be modified.

**Comment by danmosemsft** [comment]
@JeremyKuhne as it's only a sporadic failure, you could reenable for outerloop with some dumping of appropriate registry keys, then leave it until it fails again.

**Comment by JeremyKuhne** [comment]
@danmosemsft  This test was already OuterLoop

**Comment by danmosemsft** [comment]
Ah you're right.

**Comment by danmosemsft** [comment]
@jeremykuhne you caught a fish - on both Windows 8 jenkins runs
```
     System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute [FAIL]
  downloaded dumpling.py
        Could not start C:\Users\dotnet-bot\AppData\Local\Temp\ProcessStartInfoTests_o1533hky.bcw\StartInfo_TextFile_ShellExecute_1010_ffb06b13.txt UseShellExecute=True
        Association details for '.txt'
        ------------------------------
        Open command: C:\Windows\system32\OpenWith.exe "%1"
        ProgID: Didn't get expected HRESULT (1) when getting char count. HRESULT was 0x80070057
        
        Expected: True
        Actual:   False
        Stack Trace:
           D:\j\workspace\outerloop_net---7a39cc82\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(1010,0): at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute()
  total elapsed time 0:00:00.370000
```
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_release/lastCompletedBuild/consoleText

I believe these machines are actually Server 2012 R2 .. from the console output
` OS=Microsoft Windows 6.3.9600 OSVer=Microsoft Windows NT 6.2.9200.0 OSArch=X64 Arch=X64 Framework=.NET Core 4.6.00001.0`

OSVer/Environment.OSVersion comes from GetVersionExW
OS comes from RtlGetVersion, which doesn't "lie" -> so I think this is Windows 8.1 or Server 2012 R2 and I believe we use the latter.

**Comment by danmosemsft** [comment]
Incidentally if i change the code to look for ".foo" instead of ".txt" I don't get E_INVALIDARG like that.
```
Association details for '.foo'
        ------------------------------
        Open command: C:\WINDOWS\system32\OpenWith.exe "%1"
        ProgID: Unknown
```

Guess: it needs the "Desktop Experience" feature installed to work. If so, we could just make E_INVALIDARG here a "pass".

**Comment by Jiayili1** [comment]
Failed with Cannot start ..., detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/90/testReport/System.Diagnostics.Tests/ProcessStartInfoTests/StartInfo_TextFile_ShellExecute/

**Comment by v-haren** [comment]
failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug/80/testReport/System.Diagnostics.Tests/ProcessStartInfoTests/StartInfo_TextFile_ShellExecute/

**Comment by danmosemsft** [comment]
Here's what we get on a vanilla Server 2012 R2 machine (not from the run) without desktop experience
```
C:\Users\danmose>test.exe
Association details for '.txt'
------------------------------
Open command: C:\Windows\system32\NOTEPAD.EXE %1
ProgID: Didn't get expected HRESULT (1) when getting char count. HRESULT was 0x8
0070057

C:\Users\danmose>test.exe
Association details for '.foo'
------------------------------
Open command: C:\Windows\system32\OpenWith.exe "%1"
ProgID: Didn't get expected HRESULT (1) when getting char count. HRESULT was 0x8
0070057
```

So .txt is properly associated here - the behavior we're getting is as if it was .foo or some other unrecognized one.

For now, let's make the test not run on Server 2012 or by some means make it pass when this happens. We'l lstill get the coverage on other OS's.

**Comment by v-haren** [comment]
failed again: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug/82/testReport/System.Diagnostics.Tests/ProcessStartInfoTests/StartInfo_TextFile_ShellExecute/

**Comment by v-haren** [comment]
failed again: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug/83/testReport/System.Diagnostics.Tests/ProcessStartInfoTests/StartInfo_TextFile_ShellExecute/

**Comment by caesar1995** [comment]
Please see here... #21328

**Comment by danmosemsft** [comment]
Oops @caesar1995 I'll disable it.

**Comment by v-haren** [comment]
failed again: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug/84/testReport/System.Diagnostics.Tests/ProcessStartInfoTests/StartInfo_TextFile_ShellExecute/
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_release/83/testReport/System.Diagnostics.Tests/ProcessStartInfoTests/StartInfo_TextFile_ShellExecute/

**Comment by danmosemsft** [comment]
should be disabled for win8

**Comment by danmosemsft** [comment]
Fails occasionally on NETFX
Windows.10.Amd64.ClientRS2-x86-Release
```
Could not start C:\\Users\\runner\\AppData\\Local\\Temp\\ProcessStartInfoTests_dayyekaz.3lw\\StartInfo_TextFile_ShellExecute_997_0d0f3b34.txt UseShellExecute=True
Association details for '.txt'
------------------------------
Open command: C:\\Windows\\system32\\NOTEPAD.EXE %1
ProgID: txtfile

Expected: True
Actual:   False
Stack Trace :
   at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute() in E:\A\_work\2\s\corefx\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs:line 994
```

**Comment by danmosemsft** [comment]
We don't care if this doesn't run on NETFX

**Comment by stephentoub** [comment]
But we do care if there are [ActiveIssue]s in the code linked against closed issues :smile:
https://github.com/dotnet/corefx/blob/8818a22e116abe547e49046bc5b61466401003f3/src/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs#L1007

**Comment by stephentoub** [comment]
> We don't care if this doesn't run on NETFX

@danmosemsft, it looks like this is disabled for netcoreapp as well on Windows 8.

**Comment by danmosemsft** [comment]
@stephentoub despite the commenting in the test, I figured that is tracked by https://github.com/dotnet/corefx/issues/29815.

This poor test has had all kinds of issues, and would be long deleted if we could afford to lose the coverage. In a quick look, ProcessStart_UseShellExecute_OnWindows_DoesNotThrow looks like it does the same thing but for some reason hasn't been so flaky.

**Comment by danmosemsft** [comment]
Ah yes, yo'ure right, that ActiveIssue should become a SkipOnTargetFramework.
