### ISSUE TITLE
[HttpListener][Managed] HttpListenerWebSocketContext.WebSocket.Receive/Close should throw ObjectDisposedException after disposal

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#20395]
Following tests are disabled with this issue:

- SendAsync_Disposed_ThrowsObjectDisposedException
- ReceiveAsync_Disposed_ThrowsObjectDisposedException

```

   System.Net.Tests.HttpListenerWebSocketTests.SendAsync_Disposed_ThrowsObjectDisposedException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.ObjectDisposedException)
      Actual:   typeof(System.Net.WebSockets.WebSocketException): The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: 'Open, CloseReceived'
      Stack Trace:
            at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
            at System.Net.WebSockets.ManagedWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

System.Net.Tests.HttpListenerWebSocketTests.ReceiveAsync_Disposed_ThrowsObjectDisposedException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.ObjectDisposedException)
      Actual:   typeof(System.Net.WebSockets.WebSocketException): The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: 'Open, CloseSent'
      Stack Trace:
            at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
            at System.Net.WebSockets.ManagedWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by karelz** [comment]
Is it difference against Desktop?

**Comment by hughbe** [comment]
This is a difference of the managed implementation from Desktop, yes. However, the Windows netcoreapp implementation has the same  behaviour as desktop, so this issue tracks aligning the managed implementation with Windows netcoreapp and Desktop.

**Comment by karelz** [comment]
@stephentoub did you set Future milestone based on impact?

**Comment by karelz** [comment]
Got it, that makes sense, thanks!

**Comment by caesar1995** [comment]
We should add a check `ThrowIfDisposed()` before checking for InvalidState in managed implementation.

Something like [this](https://github.com/dotnet/corefx/blob/f81984bcd0843e05e51a9280573ec67a28fc41f4/src/System.Net.HttpListener/src/System/Net/Windows/WebSockets/WebSocketBase.cs#L307)

**Comment by stephentoub** [comment]
Reverted #22977, so reopening.

**Comment by caesar1995** [comment]
The problem here is HttpListenerWebSocketContext has direct access to the ManagedWebSocket's `SendAsync` method.

```c#
        public async Task SendAsync_Disposed_ThrowsObjectDisposedException()
        {
            HttpListenerWebSocketContext context = await GetWebSocketContext();
            context.WebSocket.Dispose();

            await Assert.ThrowsAsync<ObjectDisposedException>(() => context.WebSocket.SendAsync(new ArraySegment<byte>(new byte[10]), WebSocketMessageType.Text, false, new CancellationToken()));
        }
```

Inside the method, we has a `ThrowIfInvalidState()`, which does:
1. If current state is valid && the websocket has been disposed, throw `ObjectDisposedException`.
2. If current state is not valid, throw `WebSocketException`.

For Windows non-uap implementation, we has a [dispose check](https://github.com/dotnet/corefx/blob/f81984bcd0843e05e51a9280573ec67a28fc41f4/src/System.Net.HttpListener/src/System/Net/Windows/WebSockets/WebSocketBase.cs#L307) before `ThrowOnInvalidState`. However, add the dispose check in the ManagedWebSocket implementation is not the correct way to solve this problem, because the state for the websocket will be incorrectly treated.

For example, we use ClientWebSocket as a wrapper for ManagedWebSocket. The dispose check is performed at ClientWebSocket  before we call into the method within the ManagedWebSocket (like `SendAsync`, `ReceiveAsync`). 

```c#
        private void ThrowIfNotConnected()
        {
            if ((InternalState)_state == InternalState.Disposed)
            {
                throw new ObjectDisposedException(GetType().FullName);
            }
            else if ((InternalState)_state != InternalState.Connected)
            {
                throw new InvalidOperationException(SR.net_WebSockets_NotConnected);
            }
        }
```

If the **internal state for the websocket is `Disposed`**, we will throw ObjectDisposedException. (Which is exactly what we should do for these failing test cases, since we directly call into the ManagedWebSocket's `SendAsync` method, the check has been skipped).

Add check inside the ManagedWebSocket implementation, like we did [here](https://github.com/dotnet/corefx/blob/f81984bcd0843e05e51a9280573ec67a28fc41f4/src/System.Net.HttpListener/src/System/Net/Windows/WebSockets/WebSocketBase.cs#L307) is not feasible (causes test failure #23038) because we should check if the **internal state for the websocket is `Disposed`**, not if the websocket has been disposed or not. 

```c#
         private void ThrowIfDisposed()
         {
             if (_disposed) // not correct here
             {
                 throw new ObjectDisposedException(GetType().ToString());
             }
         }
```

This can cause problem like #23038 because after we do `CancellationTokenSource.Cancel()`, the websocket state will be turn into `Aborted` (not `Disposed`). Since we do perform the dispose() operation (after `ThrowIfNotConnected()` check in `ClientWebSocket `), which causes the `_disposed` = true. If we add the `ThrowIfDisposed()` method in ManagedWebSocket, the `ObjectDisposedException` will be incorrectly thrown.

The correct approach to solve this issue is described here: #23027

@davidsh @DavidGoll @rmkerr
