### ISSUE TITLE
[HttpListener][Managed] HttpListenerWebSocketContext.WebSocket.Dispose should abort, not close the socket

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#20397]
Following tests are disabled with this issue:
- Dispose_CallAfterDisposed_Nop

```
System.Net.Tests.HttpListenerWebSocketTests.Dispose_CallAfterDisposed_Nop [FAIL]
      Assert.Equal() Failure
      Expected: Aborted
      Actual:   Closed
      Stack Trace:
            at System.Net.Tests.HttpListenerWebSocketTests.<Dispose_CallAfterDisposed_Nop>d__35.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

```

**Comment by karelz** [comment]
Is it difference against Desktop?

**Comment by hughbe** [comment]
This is a difference of the managed implementation from Desktop, yes. However, the Windows netcoreapp implementation has the same  behaviour as desktop, so this issue tracks aligning the managed implementation with Windows netcoreapp and Desktop.

**Comment by stephentoub** [comment]
This isn't just a difference in the managed implementation.  If you change the test to instead dispose the client web socket (again referring to my comment at https://github.com/dotnet/corefx/issues/20394#issuecomment-304744772 about the managed implementation being used for both client and server, and run the test on Windows, you'll see that it also doesn't use Aborted.  If we want consistency here, we should really make WebSocket behave consistently on both client and server.

**Comment by karelz** [comment]
@stephentoub what would you suggest as next step? Fix any part? Or just close the issue as "won't fix" for now?

**Comment by stephentoub** [comment]
For 2.0, do nothing.  Post that, re-evaluate the behavior all up, regardless of client vs server or platform.  If we care about consistency, we should address it everywhere to make it consistent in core.

**Comment by Priya91** [comment]
The windows 10 rs2 returns closed state instead of abort. So we should consider the behavior as closed, since recent version of windows also changed the behavior to the managed implementation.
