### ISSUE TITLE
[HttpListener][Managed] HttpListenerWebSocketContext.WebSocket.Close should nop after Abort()

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#20394]
Following tests are disabled with this issue:
- CloseAsync_AfterAborted_Nop

```
   System.Net.Tests.HttpListenerWebSocketTests.CloseAsync_AfterAborted_Nop [FAIL]
      System.Net.WebSockets.WebSocketException : The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'
      Stack Trace:
            at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
            at System.Net.WebSockets.ManagedWebSocket.CloseOutputAsync(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Net.Tests.HttpListenerWebSocketTests.<CloseAsync_AfterAborted_Nop>d__31.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by karelz** [comment]
Is it difference against Desktop?

**Comment by hughbe** [comment]
This is a difference of the managed implementation from Desktop, yes. However, the Windows netcoreapp implementation has the same  behaviour as desktop, so this issue tracks aligning the managed implementation with Windows netcoreapp and Desktop.

**Comment by stephentoub** [comment]
The Windows HttpListener implementation is using the same one as desktop's HttpListener,, but the Windows client-side implementation is using a different implementation than desktop, one based on WinHttp.  That implementation has this same "the only valid states for Close/CloseOutput are Open/CloseReceived":
https://github.com/dotnet/corefx/blob/d6b11250b5113664dd3701c25bdf9addfacae9cc/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WinHttpWebSocket.cs#L525
and the managed implementation, which is used for both ClientWebSocket and HttpListener (and ASP.NET) uses that same semantic:
https://github.com/dotnet/corefx/blob/d6b11250b5113664dd3701c25bdf9addfacae9cc/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L59
So the managed implementation isn't broken here.  That there's an inconsistency is bad, but it's not just with the managed implementation: it shouldn't matter whether we're holding client- or server- end of the websocket, and the client behavior on Windows is differing from the server behavior on Windows; the managed implementation has the same behavior for client and server, with that behavior matching the client behavior on Windows.  There are tests in the System.Net.WebSockets.Client project verifying that behavior, too.
