### ISSUE TITLE
DCS/DCJS Failed to Serialize System Types in ReflectionOnly Mode

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#20478]
DCS/DCJS failed to serialize System types in ReflectionOnly mode due to the reflection on the types being blocked.

The following tests failed.

```
DataContractSerializerTests.DCS_ReadOnlyDictionary
DataContractSerializerTests.DCS_GenericStack
DataContractSerializerTests.DCS_Stack
DataContractSerializerTests.DCS_SystemVersion
DataContractSerializerTests.DCS_ListMembers
DataContractSerializerTests.DCS_BasicRoundtripDCRDefaultCollections
DataContractSerializerTests.DCS_SortedList
DataContractSerializerTests.DCS_GenericQueue
DataContractSerializerTests.DCS_Queue
DataContractSerializerTests.DCS_ReadOnlyCollection

DataContractJsonSerializerTests.DCJS_Queue
DataContractJsonSerializerTests.DCJS_GetOonlyDictionary_UseSimpleDictionaryFormat
DataContractJsonSerializerTests.DCJS_Stack
DataContractJsonSerializerTests.DCJS_ReadOnlyDictionary
DataContractJsonSerializerTests.DCJS_GenericQueue
DataContractJsonSerializerTests.DCJS_ReadOnlyCollection
DataContractJsonSerializerTests.DCJS_GenericStack
DataContractJsonSerializerTests.DCJS_SortedList
DataContractJsonSerializerTests.DCJS_SystemVersion
```

Example call stack:

```
      <test name="DataContractSerializerTests.DCS_ReadOnlyCollection" type="DataContractSerializerTests" method="DCS_ReadOnlyCollection" time="0.0003206" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[XML comparison is also failing\r\nTest failed for input: System.Collections.ObjectModel.ReadOnlyCollection`1[System.String]\r\n
Expected: <ReadOnlyCollectionOfstring xmlns=\"http://schemas.datacontract.org/2004/07/System.Collections.ObjectModel\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><list xmlns:a=\"http://schemas.microsoft.com/2003/10/Serialization/Arrays\"><a:string>Foo</a:string><a:string>Bar</a:string></list></ReadOnlyCollectionOfstring>\r\n
Actual:   <ReadOnlyCollectionOfstring xmlns=\"http://schemas.datacontract.org/2004/07/System.Collections.ObjectModel\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"/>\r\n
Expected: True\r\n
Actual:   False]]>
          </message>
          <stack-trace><![CDATA[   at DataContractSerializerTests.SerializeAndDeserialize<System.__Canon>(__Canon value, String baseline, $DataContractSerializerSettings settings, Func$1<$DataContractSerializer> serializerFactory, Boolean skipStringCompare) in d:\OSS\corefx-1\corefx\src\System.Runtime.Serialization.Xml\tests\DataContractSerializer.cs:line 3163
   at DataContractSerializerTests.DCS_ReadOnlyCollection() in d:\OSS\corefx-1\corefx\src\System.Runtime.Serialization.Xml\tests\DataContractSerializer.cs:line 1885
   at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean targetIsThisCall)
   at System.InvokeUtils.CalliIntrinsics.Call(IntPtr dynamicInvokeHelperMethod, Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean isTargetThisCall)
   at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, IntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object targetMethodOrDelegate, Object[] parameters, BinderBundle binderBundle, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\InvokeUtils.cs:line 400]]></stack-trace>
        </failure>
      </test>
```

**Comment by shmao** [comment]
@morganbr can you please help re-assign the issue? The root cause of the test failures is that reflection is blocked on System types.

**Comment by morganbr** [comment]
@shmao , are they reflection blocked (reflection appears to work, but returns fake answers) or just not given metadata? I wouldn't expect those to be blocked. If they're just missing metadata, your test needs an rd.xml file.

**Comment by shmao** [comment]
@morganbr These types are `[Serializable]` types. DCS needs to serialize their private fields. The reflection is blocked on those private members.

**Comment by shmao** [comment]
@morganbr I just re-ran all these tests and they all passed now. I will send a PR to remove the [ActiveIssue] attributes.

Thanks for fixing the issue, @morganbr !

**Comment by shmao** [comment]
> @morganbr I just re-ran all these tests and they all passed now. I will send a PR to remove the [ActiveIssue] attributes.

I was wrong. I didn't run the tests in ReflectionOnly mode. The tests are still failing. I'm investigating the issue.

**Comment by shmao** [comment]
@morganbr You were right. The reflection on the internal members of [Serializable] types are not blocked. The tests failed due to missing metadata. After I added the following entries in the rd.xml, the tests for collections passed ,

```
<Namespace Name="System.Collections" Dynamic="Required All" />
<Namespace Name="System.Collections.Generic" Dynamic="Required All" />
```

Do we expect developers to add entries like this or entries for specific system types? Can we just keep metadata for types that requires serialization so that we don't need to change rd.xml?

**Comment by morganbr** [comment]
@shmao, this test is a non-customer case that we've discussed in the past. Essentially, analysis figures out that these types need to be serialized, so it tells SG about them, which would generate working serialization code. However, this test case doesn't run SG. 

For customers, their own types are likely already reflectable by default. Any framework types may or may not need rd.xml, but if we knew they needed reflection for the serializer, we would have just made SG work.
