### ISSUE TITLE
MissingManifestResourceException from ResourceManager in System.Composition tests

### ISSUE THREAD

**Issue by tijoytom** [dotnet/corefx#20519]
Seems to be a bug / missing feature from resource embedding 

```
 Actual:   typeof(System.Resources.MissingManifestResourceException): Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "System.Composition.Properties.Resources.resources" was correctly embedded or linked into assembly "System.Private.CoreLib" at compile time, or that all the satellite assemblies required are loadable and fully signed.
      Stack Trace:
         F:\ProjectN\src\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Resources\ManifestBasedResourceGroveler.cs(507,0): at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
         F:\ProjectN\src\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Resources\ManifestBasedResourceGroveler.cs(125,0): at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary$2<String,ResourceSet> localResourceSets, Boolean tryParents, Boolean createIfNotExists)
         F:\ProjectN\src\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Resources\ResourceManager.cs(709,0): at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
         F:\ProjectN\src\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Resources\ResourceManager.cs(1155,0): at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
            at _$ILCT$.$ILT$ThrowHelper$.ThrowHelperNoParamCompositionFailedException()
         E:\REPRO\corefx\src\System.Composition.Hosting\src\System\Composition\Hosting\Providers\Metadata\MetadataViewProvider.cs(74,0): at System.Composition.Hosting.Providers.Metadata.MetadataViewProvider.GetMetadataViewProvider<System.__UniversalCanon>()
         E:\REPRO\corefx\src\System.Composition.Hosting\src\System\Composition\Hosting\Providers\Lazy\LazyWithMetadataExportDescriptorProvider.cs(31,0): at System.Composition.Hosting.Providers.Lazy.LazyWithMetadataExportDescriptorProvider.GetLazyDefinitions<System.__UniversalCanon, System.__UniversalCanon>($CompositionContract lazyContract, $DependencyAccessor definitionAccessor)
         InvokeOpenStaticThunk(16707566,0): at System.Func$3<System.__Canon,System.__Canon,System.__Canon>.InvokeOpenStaticThunk(__Canon arg1, __Canon arg2)
         Invoke(16707566,0): at Newtonsoft.Json.Utilities.MethodCall$2<System.__Canon,System.__Canon>.Invoke(__Canon target, Object[] args)
         E:\REPRO\corefx\src\System.Composition.Hosting\src\System\Composition\Hosting\Providers\Lazy\LazyWithMetadataExportDescriptorProvider.cs(26,0): at System.Composition.Hosting.Providers.Lazy.LazyWithMetadataExportDescriptorProvider.GetExportDescriptors($CompositionContract exportKey, $DependencyAccessor definitionAccessor)
         E:\REPRO\corefx\src\System.Composition.Hosting\src\System\Composition\Hosting\Core\ExportDescriptorRegistryUpdate.cs(147,0): at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.GetPromises($CompositionContract contract)
         E:\REPRO\corefx\src\System.Composition.Hosting\src\System\Composition\Hosting\Core\DependencyAccessor.cs(64,0): at System.Composition.Hosting.Core.DependencyAccessor.TryResolveOptionalDependency(Object site, $CompositionContract contract, Boolean isPrerequisite, $CompositionDependency& dependency)
         E:\REPRO\corefx\src\System.Composition.Hosting\src\System\Composition\Hosting\Core\ExportDescriptorRegistryUpdate.cs(38,0): at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.Execute($CompositionContract contract)
         E:\REPRO\corefx\src\System.Compositio
```

**Comment by karelz** [comment]
@tijoytom note that you can mark exceptions, logs and code in \`\`\` area - see my edit above.

**Comment by tijoytom** [comment]
that's good to know

**Comment by tijoytom** [comment]
This is fixed by @zamont resource manager changes , can be closed once verified.

**Comment by karelz** [comment]
@tijoytom please link the changes and make sure the PR has auto-close "Fixes #abc". That way it will be closed upon merge.
If @zamont works on it, he should assign the issue to himself.

**Comment by tijoytom** [comment]
closed upon merge
  -> The change is in ProjectN , so we have to manually close this one.I will close once i verify.

**Comment by karelz** [comment]
Got it, that makes sense.

**Comment by Jiayili1** [comment]
This issue is repro on UWP F5 tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20170612.01/workItem/System.Composition.Tests/analysis/xunit/System.Composition.Lightweight.UnitTests.MetadataViewGenerationTests~2FAConcreteTypeWithUnsupportedConstructorsCannotBeUsedAsAMetadataView

**Comment by danmosemsft** [comment]
@tijoytom was this on ILC or F5? The issue immediately above is probably just another of the F5 resource load issues, which was fixed since. I'll delete it.

**Comment by tijoytom** [comment]
@danmosemsft It was ILC , zach merged his changes a while back.
