### ISSUE TITLE
System.MissingMethodException: Method 'RegisteredWaitHandle.Unregister(WaitHandle)' was not included in compilation, but was referenced

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#20528]
Was discovered in UWP ILC test runs. 15 failures in `System.Net.Ping.Functional.Tests.csproj`.

The same is true for ThreadPool.RegisterWaitForSingleObject(WaitHandle, WaitOrTimerCallback, object, int, bool) :
```
Method 'ThreadPool.RegisterWaitForSingleObject(WaitHandle, WaitOrTimerCallback, object, int, bool)' was not included in compilation, but was referenced in Ping.SendPingAsyncCore(IPAddress, by
  te[], int, PingOptions)
```

Sample failure:

```
<test name="System.Net.NetworkInformation.Tests.PingTest.SendAsyncs_ReuseInstance_Hostname" type="System.Net.NetworkInformation.Tests.PingTest" method="SendAsyncs_ReuseInstance_Hostname" time="0.0013137" result="Fail">
        <failure exception-type="System.MissingMethodException">
          <message><![CDATA[System.MissingMethodException : Method 'RegisteredWaitHandle.Unregister(WaitHandle)' was not included in compilation, but was referenced in Ping.UnregisterWaitHandle(). There may have been a missing assembly.]]></message>
          <stack-trace><![CDATA[   at System.Net.NetworkInformation.Ping.InternalDisposeCore() in F:\corefx\src\System.Net.Ping\src\System\Net\NetworkInformation\Ping.Windows.cs:line 158
   at System.Net.NetworkInformation.Ping.InternalDispose() in F:\corefx\src\System.Net.Ping\src\System\Net\NetworkInformation\Ping.cs:line 105
   at System.Net.NetworkInformation.Ping.Dispose(Boolean disposing) in F:\corefx\src\System.Net.Ping\src\System\Net\NetworkInformation\Ping.cs:line 113
   at System.ComponentModel.Component.Dispose() in F:\corefx\src\System.Runtime.Extensions\src\System\IO\TextReader.cs:line 35
   at System.Net.NetworkInformation.Tests.PingTest.<SendAsyncs_ReuseInstance_Hostname>d__17.MoveNext$fin$0() in F:\corefx\src\System.Net.Ping\tests\FunctionalTests\PingTest.cs:line 16707566
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 61
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 178
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 61
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 178
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 61
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 178
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 147]]></stack-trace>
        </failure>
      </test>
```

**Comment by schen381** [comment]
I am not able to repro this issue. I deleted all labels which have [ActiveIssue 20528] in PingTest, and they passed on UWP ILC runs. However, they failed in UAP run, with a different error:  System.ComponentModel.Win32Exception : Access is denied.(This error seems related to SendPingAsyncCore()) Has this issue already been fixed? Could you please confirm the behavior?

cc: @davidsh

**Comment by caesar1995** [comment]
I think this issue has been fixed. Please re-open it if it happens again. Thanks.
