### ISSUE TITLE
System.Diagnostics.Tests.ProcessThreadTests~2FTestStartTimeProperty failed with Assert.InRange() 

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20545]
https://mc.dot.net/#/user/shmao/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/82a719f503a18103d9f896336237989f8d630486/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessThreadTests~2FTestStartTimeProperty

```
Assert.InRange() Failure\r\nRange:  (5/31/2017 9:34:50 PM - 5/31/2017 9:34:55 PM)\r\nActual: 5/31/2017 9:34:49 PM
Stack Trace :
   at System.Diagnostics.Tests.ProcessThreadTests.<TestStartTimeProperty>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

last time https://github.com/dotnet/corefx/issues/5805 https://github.com/dotnet/corefx/pull/7223

**Comment by danmosemsft** [comment]
Apparently a thread in the process StartTime was ~2 seconds before the process StartTime.

**Comment by joperezr** [comment]
test hasn't failed again, so I'm closing this for now. Please do re-open if it fails again so that we can fix the test or disable.
