### ISSUE TITLE
System.Net.Security.Tests.dll FailFast on Debian

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20550]
This comes just after "starting KDC" from `src\System.Net.Security\tests\Scripts\Unix\setup-kdc.sh`

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170601.02/workItem/System.Net.Security.Tests/wilogs 

```
Starting KDC..
FailFast: Invalid context passed to SafeDeleteNegoContext

   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at System.Net.Security.SafeDeleteNegoContext.SetGssContext(SafeGssContextHandle context) in /root/corefx/src/Common/src/System/Net/Security/Unix/SafeDeleteNegoContext.cs:line 52
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags) in /root/corefx/src/Common/src/System/Net/Security/NegotiateStreamPal.Unix.cs:line 197
   at System.Net.Security.NegotiateStreamPal.InitializeSecurityContext(SafeFreeCredentials credentialsHandle, SafeDeleteContext& securityContext, String spn, ContextFlagsPal requestedContextFlags, SecurityBuffer[] inSecurityBufferArray, SecurityBuffer outSecurityBuffer, ContextFlagsPal& contextFlags) in /root/corefx/src/Common/src/System/Net/Security/NegotiateStreamPal.Unix.cs:line 240
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode) in /root/corefx/src/Common/src/System/Net/NTAuthentication.Common.cs:line 243
   at System.Net.Security.NegoState.GetOutgoingBlob(Byte[] incomingBlob, Exception& e) in /root/corefx/src/System.Net.Security/src/System/Net/Security/NegoState.cs:line 778
   at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult) in /root/corefx/src/System.Net.Security/src/System/Net/Security/NegoState.cs:line 444
   at System.Net.Security.NegoState.CheckCompletionBeforeNextSend(Byte[] message, LazyAsyncResult lazyResult) in /root/corefx/src/System.Net.Security/src/System/Net/Security/NegoState.cs:line 648
   at System.Net.Security.NegoState.ProcessReceivedBlob(Byte[] message, LazyAsyncResult lazyResult) in /root/corefx/src/System.Net.Security/src/System/Net/Security/NegoState.cs:line 624
   at System.Net.Security.NegoState.ReadCallback(IAsyncResult transportResult) in /root/corefx/src/System.Net.Security/src/System/Net/Security/NegoState.cs:line 756
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken) in /root/corefx/src/Common/src/System/Net/LazyAsyncResult.cs:line 428
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken) in /root/corefx/src/Common/src/System/Net/LazyAsyncResult.cs:line 382
   at System.Net.LazyAsyncResult.InvokeCallback(Object result) in /root/corefx/src/Common/src/System/Net/LazyAsyncResult.cs:line 389
   at System.Net.StreamFramer.ReadFrameComplete(IAsyncResult transportResult) in /root/corefx/src/System.Net.Security/src/System/Net/StreamFramer.cs:line 270
   at System.Net.StreamFramer.ReadFrameCallback(IAsyncResult transportResult) in /root/corefx/src/System.Net.Security/src/System/Net/StreamFramer.cs:line 168
   at System.Threading.Tasks.TaskToApm.<>c__DisplayClass3_0.<InvokeCallbackWhenTaskCompletes>b__0() in /root/corefx/src/Common/src/System/Threading/Tasks/TaskToApm.cs:line 133
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Environment.FailFast(System.String, System.Exception)
   at System.Net.Security.SafeDeleteNegoContext.SetGssContext(Microsoft.Win32.SafeHandles.SafeGssContextHandle)
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(System.Net.Security.SafeFreeNegoCredentials, System.Net.Security.SafeDeleteContext ByRef, System.String, System.Net.ContextFlagsPal, System.Net.Security.SecurityBuffer, System.Net.Security.SecurityBuffer, System.Net.ContextFlagsPal ByRef)
   at System.Net.Security.NegotiateStreamPal.InitializeSecurityContext(System.Net.Security.SafeFreeCredentials, System.Net.Security.SafeDeleteContext ByRef, System.String, System.Net.ContextFlagsPal, System.Net.Security.SecurityBuffer[], System.Net.Security.SecurityBuffer, System.Net.ContextFlagsPal ByRef)
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[], Boolean, System.Net.SecurityStatusPal ByRef)
   at System.Net.Security.NegoState.GetOutgoingBlob(Byte[], System.Exception ByRef)
   at System.Net.Security.NegoState.StartSendBlob(Byte[], System.Net.LazyAsyncResult)
   at System.Net.Security.NegoState.CheckCompletionBeforeNextSend(Byte[], System.Net.LazyAsyncResult)
   at System.Net.Security.NegoState.ProcessReceivedBlob(Byte[], System.Net.LazyAsyncResult)
   at System.Net.Security.NegoState.ReadCallback(System.IAsyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
   at System.Net.LazyAsyncResult.InvokeCallback(System.Object)
   at System.Net.StreamFramer.ReadFrameComplete(System.IAsyncResult)
   at System.Net.StreamFramer.ReadFrameCallback(System.IAsyncResult)
   at System.Threading.Tasks.TaskToApm+<>c__DisplayClass3_0.<InvokeCallbackWhenTaskCompletes>b__0()
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback, System.Object, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
/home/helixbot/dotnetbuild/work/a3f18f62-593d-45f2-985d-8cbdf5c68e39/Work/e26112cb-e993-41f5-aa16-81e08426a81c/Unzip/RunTests.sh: line 89:  4484 Aborted                 (core dumped) $RUNTIME_PATH/dotnet xunit.console.netcore.exe System.Net.Security.Tests.dll -xml testResults.xml -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests -notrait category=failing
command exited with ExitCode: 134
```

**Comment by danmosemsft** [comment]
@karelz this is a failfast in debug only. In release it will continue and just maybe fail later.

**Comment by Jiayili1** [comment]
This issue is repro on Core Tests (2.0.0) in build20170616.01, detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170616.01/workItem/System.Net.Security.Tests/wilogs

**Comment by Jiayili1** [comment]
Failed again: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170619.01/workItem/System.Net.Security.Tests/wilogs

**Comment by karelz** [comment]
Seems to be gone. Please reopen if it happens/happened after June.
