### ISSUE TITLE
Dumpling fails due to locked file

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20602]
Is dumpling.py getting downloaded even when it already exists? I see lots of 
```
  downloaded dumpling.py
  downloaded analysis.py
  downloaded triage.ini
```
issue:
```
  Running tests... Start time: 15:30:51.12
  Traceback (most recent call last):
    File "C:\Users\dotnet-bot/.dumpling/dumpling.py", line 1128, in <module>
      main(sys.argv)
    File "C:\Users\dotnet-bot/.dumpling/dumpling.py", line 1123, in main
      cmdProc.Process(config)
    File "C:\Users\dotnet-bot/.dumpling/dumpling.py", line 537, in Process
      self.Install(config)
    File "C:\Users\dotnet-bot/.dumpling/dumpling.py", line 545, in Install
      self._dumpSvc.DownloadClientFile('dumpling.py', config.installpath) 
    File "C:\Users\dotnet-bot/.dumpling/dumpling.py", line 213, in DownloadClientFile
      DumplingService._stream_file_from_response(response, os.path.join(downdir, filename))  
    File "C:\Users\dotnet-bot/.dumpling/dumpling.py", line 384, in _stream_file_from_response
      os.remove(path)
  WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:\\Users\\dotnet-bot\\.dumpling\\dumpling.py'
```

**Comment by mellinoe** [comment]
See this issue: https://github.com/dotnet/buildtools/issues/1360

We need to add a step that downloads the script and intsalls it once up front -- I just haven't had the time to get to that yet.

**Comment by mellinoe** [comment]
Let's track it over there.
