### ISSUE TITLE
System.IO.Tests.FileInfo_GetSetTimes~2FTimesStillSetAfterDelete failed on Debian

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20818]
@JeremyKuhne the file system on this OS may have coarser granularity? Perhaps the test should get the time from the item itself then check that didn't change, rather than get the wall clock time then create the item?

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170608.02/workItem/System.IO.FileSystem.Tests/analysis/xunit/System.IO.Tests.FileInfo_GetSetTimes~2FTimesStillSetAfterDelete

```
Debian.87.Amd64-x64-Release
Unhandled Exception of Type Xunit.Sdk.AllException
Message :
Assert.All() Failure: 6 out of 6 items in the collection did not pass.\n[5]: Xunit.Sdk.InRangeException: Assert.InRange() Failure\r\n     Range:  (636325222250050043 - 636325222270050575)\r\n     Actual: 636325222250000000\n        at Xunit.Assert.InRange[T](T actual, T low, T high, IComparer`1 comparer)\n        at System.IO.Tests.BaseGetSetTimes`1.<>c__DisplayClass8_0.<ValidateSetTimes>b__0(TimeFunction function) in /root/corefx/src/System.IO.FileSystem/tests/Base/BaseGetSetTimes.cs:line 75\n        at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action)\n[4]: Xunit.Sdk.InRangeException: Assert.InRange() Failure\r\n     Range:  (636325222250050043 - 636325222270050575)\r\n     Actual: 636325222250000000\n        at Xunit.Assert.InRange[T](T actual, T low, T high, IComparer`1 comparer)\n        at System.IO.Tests.BaseGetSetTimes`1.<>c__DisplayClass8_0.<ValidateSetTimes>b__0(TimeFunction function) in /root/corefx/src/System.IO.FileSystem/tests/Base/BaseGetSetTimes.cs:line 75\n        at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action)\n[3]: Xunit.Sdk.InRangeException: Assert.InRange() Failure\r\n     Range:  (636325222250050043 - 636325222270050575)\r\n     Actual: 636325222250000000\n        at Xunit.Assert.InRange[T](T actual, T low, T high, IComparer`1 comparer)\n        at System.IO.Tests.BaseGetSetTimes`1.<>c__DisplayClass8_0.<ValidateSetTimes>b__0(TimeFunction function) in /root/corefx/src/System.IO.FileSystem/tests/Base/BaseGetSetTimes.cs:line 75\n        at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action)\n[2]: Xunit.Sdk.InRangeException: Assert.InRange() Failure\r\n     Range:  (636325222250050043 - 636325222270050575)\r\n     Actual: 636325222250000000\n        at Xunit.Assert.InRange[T](T actual, T low, T high, IComparer`1 comparer)\n        at System.IO.Tests.BaseGetSetTimes`1.<>c__DisplayClass8_0.<ValidateSetTimes>b__0(TimeFunction function) in /root/corefx/src/System.IO.FileSystem/tests/Base/BaseGetSetTimes.cs:line 75\n        at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action)\n[1]: Xunit.Sdk.InRangeException: Assert.InRange() Failure\r\n     Range:  (636325222250050043 - 636325222270050575)\r\n     Actual: 636325222250000000\n        at Xunit.Assert.InRange[T](T actual, T low, T high, IComparer`1 comparer)\n        at System.IO.Tests.BaseGetSetTimes`1.<>c__DisplayClass8_0.<ValidateSetTimes>b__0(TimeFunction function) in /root/corefx/src/System.IO.FileSystem/tests/Base/BaseGetSetTimes.cs:line 75\n        at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action)\n[0]: Xunit.Sdk.InRangeException: Assert.InRange() Failure\r\n     Range:  (636325222250050043 - 636325222270050575)\r\n     Actual: 636325222250000000\n        at Xunit.Assert.InRange[T](T actual, T low, T high, IComparer`1 comparer)\n        at System.IO.Tests.BaseGetSetTimes`1.<>c__DisplayClass8_0.<ValidateSetTimes>b__0(TimeFunction function) in /root/corefx/src/System.IO.FileSystem/tests/Base/BaseGetSetTimes.cs:line 75\n        at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action)
Stack Trace :
   at System.IO.Tests.BaseGetSetTimes`1.ValidateSetTimes(T item, DateTime beforeTime, DateTime afterTime) in /root/corefx/src/System.IO.FileSystem/tests/Base/BaseGetSetTimes.cs:line 82
   at System.IO.Tests.InfoGetSetTimes`1.TimesStillSetAfterDelete() in /root/corefx/src/System.IO.FileSystem/tests/Base/InfoGetSetTimes.cs:line 59
```

**Comment by JeremyKuhne** [comment]
I was over aggressive with this one, I'll dial back.

**Comment by JeremyKuhne** [comment]
Fix is in PR.

**Comment by karelz** [comment]
So was it "test bug"?

**Comment by JeremyKuhne** [comment]
> So was it "test bug"?
Yes
