### ISSUE TITLE
Dumpling hitting server error, breaking runs

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20817]
As far as I can tell the runs are breaking as a consequence.

https://ci.dot.net/job/dotnet_corefx/job/master/job/debian8.4_debug/2722/consoleFull#136046166483554902-aff0-4799-9e92-0ada24ce2a06
https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora24_release/2737/consoleFull#136046166483554902-aff0-4799-9e92-0ada24ce2a06
https://ci.dot.net/job/dotnet_corefx/job/master/job/opensuse42.1_release/2756/consoleFull#136046166483554902-aff0-4799-9e92-0ada24ce2a06

@mellinoe can you look first thing pls?

```
21:14:46   downloaded dumpling.py
21:14:46   total elapsed time 0:00:00.155554
21:14:47   downloaded dumpling.py
21:14:47   downloading debugger for client linux-suse
21:14:47   Traceback (most recent call last):
21:14:47     File "/mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/tempHome/.dumpling/dumpling.py", line 1128, in <module>
21:14:47       main(sys.argv)
21:14:47     File "/mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/tempHome/.dumpling/dumpling.py", line 1123, in main
21:14:47       cmdProc.Process(config)
21:14:47     File "/mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/tempHome/.dumpling/dumpling.py", line 537, in Process
21:14:47       self.Install(config)
21:14:47     File "/mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/tempHome/.dumpling/dumpling.py", line 566, in Install
21:14:47       dbgPath = self._dumpSvc.DownloadDebugger(dbgdir)
21:14:47     File "/mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/tempHome/.dumpling/dumpling.py", line 184, in DownloadDebugger
21:14:47       response.raise_for_status()
21:14:47     File "/usr/lib/python2.7/site-packages/requests/models.py", line 893, in raise_for_status
21:14:47       raise HTTPError(http_error_msg, response=self)
21:14:47 requests.exceptions.HTTPError : 500 Server error : Internal Server Error for url: https://dumpling.azurewebsites.net/api/tools/debug?os=linux&distro=suse [/mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/src/tests.builds]
21:14:47 
/mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/Tools/Dumpling.targets(11,5): error MSB3073: The command "python /mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/Tools/DumplingHelper.py install_dumpling" exited with code -1. [/mnt/resource/j/workspace/dotnet_corefx/master/opensuse42.1_release/src/tests.builds]
```

**Comment by mellinoe** [comment]
Should be fixed by #20824 .

**Comment by v-haren** [comment]
failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/debian8.4_debug/2742/consoleFull#136046166483554902-aff0-4799-9e92-0ada24ce2a06
https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora24_debug/2792/consoleFull#136046166483554902-aff0-4799-9e92-0ada24ce2a06
https://ci.dot.net/job/dotnet_corefx/job/master/job/opensuse42.1_debug/2778/consoleFull#136046166483554902-aff0-4799-9e92-0ada24ce2a06

**Comment by danmosemsft** [comment]
May have missed the change. Please reopen if it happens again.
