### ISSUE TITLE
NullReferenceException in System.Globalization.NumberFormatInfo.get_CurrentInfo()

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20835]
https://mc.dot.net/#/user/marek-safar/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/b62758a03e8410f2f523ec0a297dc139423cbe75/workItem/System.Globalization.Tests/analysis/xunit/System.Globalization.Tests.CharUnicodeInfoGetUnicodeCategoryTests~2FGetNumericValue

```
 System.NullReferenceException
Ubuntu.1604.Amd64.Open-Debug-x64
Unhandled Exception of Type System.NullReferenceException
Message :
System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace :
   at System.Globalization.NumberFormatInfo.get_CurrentInfo()
   at System.Double.ToString(String format, IFormatProvider provider)
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0, Object arg1, Object arg2)
   at System.Globalization.Tests.CharUnicodeInfoGetUnicodeCategoryTests.ErrorMessage(Char ch, Object expected, Object actual) in /mnt/j/workspace/dotnet_corefx/master/portable-linux-Config_Debug+OuterLoop_false_prtest/src/System.Globalization/tests/CharUnicodeInfo/CharUnicodeInfoTests.cs:line 123
   at System.Globalization.Tests.CharUnicodeInfoGetUnicodeCategoryTests.GetNumericValue(Char ch, Double expected) in /mnt/j/workspace/dotnet_corefx/master/portable-linux-Config_Debug+OuterLoop_false_prtest/src/System.Globalization/tests/CharUnicodeInfo/CharUnicodeInfoTests.cs:line 88
   at System.Globalization.Tests.CharUnicodeInfoGetUnicodeCategoryTests.GetNumericValue() in /mnt/j/workspace/dotnet_corefx/master/portable-linux-Config_Debug+OuterLoop_false_prtest/src/System.Globalization/tests/CharUnicodeInfo/CharUnicodeInfoTests.cs:line 76
```

@tarekgh fyi.

**Comment by danmosemsft** [comment]
@ChadNedzlek @MattGal can you shed light on why this exception does not appear in the work item logs for this configuration https://mc.dot.net/#/user/marek-safar/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/b62758a03e8410f2f523ec0a297dc139423cbe75/workItem/System.Globalization.Tests/wilogs
nor does it appear in the XML file you download there
https://dotnetjobresults.blob.core.windows.net/build-c7784806e2e745a093085a9142ddcafd/Ubuntu.1604.Amd64.Open/System.Globalization.Tests/testResults.xml?sv=2015-04-05&sr=c&sig=T7Fpmc%2BUThwZzJUitIOgUfCUZgULiYfnEJz7uOHzrhQ%3D&st=2017-06-08T21%3A51%3A44.8968654Z&se=2017-07-08T21%3A51%3A44.8968678Z&sp=r

? 

That might help us understand how this seemingly impossible callstack can occur

**Comment by tarekgh** [comment]
Marked it for UWP6.0 for now till we have more info to help investigating it.

**Comment by ChadNedzlek** [comment]
The run appears to have been run 3 times. The second of those 3 re-runs had the failure, but the most recent did not.

Essentially the first link is an outdated link.

**Comment by danmosemsft** [comment]
@ChadNedzlek that would be a MC bug wouldn't it? Why isn't it resetting this failure, but resetting the other logs?

Besides that - is it possible to retrieve the console log  for this failure?

**Comment by ChadNedzlek** [comment]
It might be, but it's probably one that will never manage to bubble up in priority, because you can't actually reach that point anymore... the links that lead there are all removed... because the most recent runs don't have failures, and it only happens for re-runs of the same build hash.

As for getting the logs, yes, I can fetch a specific log for this run... give me a bit to poke through the database to "un-de-duplicate" the failure and get the specific failing logs... and I'll email them.

**Comment by ChadNedzlek** [comment]
I believe this is the log for that specific failure:
https://dotnetjobresults.blob.core.windows.net/build-c79c707f5e064ca592d45462b2631fa3/Ubuntu.1604.Amd64.Open/System.Globalization.Tests/e7760b0e6d244b11838a8a69a37a8ac6.log?sv=2015-04-05&sr=c&sig=m8ApMjcPFV%2FJOZupADWIHDNoixo7SfJYKStu3CdPiLg%3D&st=2017-06-08T13%3A29%3A45.1566948Z&se=2017-07-08T13%3A29%3A45.1566980Z&sp=r

**Comment by danmosemsft** [comment]
Thanks. @tarekgh this output doesn't seem to help.

**Comment by tarekgh** [comment]
@danmosemsft I'll try to look more at the code to see to if there is anyway we can get into this state. if not find any clue I'll close the issue and watch if we'll run into the same problem again.

**Comment by tarekgh** [comment]
This should be fixed as soon as we get the new coreclr package to corefx. closing it from now to just see how likely we can hit same failure before getting the fix here.
