### ISSUE TITLE
System.Collections.Tests fail with Serialization issue in UAPAOT and UAP

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#20888]
There are two different tests failing here: 

### [EqualityComparer_SerializationRoundtrip](https://github.com/dotnet/corefx/blob/master/src/System.Collections/tests/Generic/Comparers/EqualityComparer.Generic.Serialization.Tests.cs#L16-L29)

This test is failing for all the Test class that inherit from this base class:

```
System.Collections.Generic.Tests.UInt64ComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.DecimalComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.ByteComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.UInt32EnumComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.StringComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.DoubleComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.UInt16EnumComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.IntPtrComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.NullableIntPtrComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.SByteComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.Int16EnumComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.ByteEnumComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.UInt64EnumComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.Int32ComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.NullableInt32ComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.SByteEnumComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.NullableUInt32ComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.EquatableComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.UIntPtrComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.Int16ComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.SingleComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.Int32EnumComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.NullableUIntPtrComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.Int64ComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.UInt16ComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.Int64EnumComparersTests.EqualityComparer_SerializationRoundtrip [FAIL]
System.Collections.Generic.Tests.UInt32ComparersTests.EqualityComparer_SerializationRoundtrip [FAIL
```

The failing error is: 

```
System.Reflection.MissingMetadataException : 'System.Collections.Generic.GenericEqualityComparer<>' is missing metadata. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=392859
```

### [IGenericSharedAPI_SerializeDeserialize](https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Collections/IEnumerable.Generic.Serialization.Tests.cs#L15-L39)

This test is failing for two test classes that implement this base class:

* SortedDictionary_Generic_Tests
* SortedList_Generic_Tests

With error:
```
System.Reflection.MissingMetadataException : This operation cannot be carried out because metadata for the following object was removed for performance reasons:\n\n  EETypeRva:0x00001EA0\n\nNo further information is available. Rebuild in debug mode for better information.\n\n
```

**Comment by safern** [comment]
Other tests failing with this issue: 

* [System.Collections.Tests.Dictionary_Tests.CopyConstructorInt32Comparer](https://github.com/dotnet/corefx/blob/master/src/System.Collections/tests/Generic/Dictionary/Dictionary.Tests.cs#L201-L204)
* [System.Collections.Tests.Dictionary_Tests.CopyConstructorStringComparer](https://github.com/dotnet/corefx/blob/master/src/System.Collections/tests/Generic/Dictionary/Dictionary.Tests.cs#L222-L225)

**Comment by safern** [comment]
### [EqualityComparer_SerializationRoundtrip](https://github.com/dotnet/corefx/blob/master/src/System.Collections/tests/Generic/Comparers/EqualityComparer.Generic.Serialization.Tests.cs#L16-L29) test fails in UAP as well with error:

```
System.Runtime.Serialization.SerializationException : Unable to load type System.Collections.Generic.GenericEqualityComparer`1[[System.Collections.Tests.Equatable, System.Collections.Tests, Version=4.1.1.0, Culture=neutral, Publ
  icKeyToken=9d77cc7ad39b68eb]] required for deserialization.
        Stack Trace:
             at System.Runtime.Serialization.ObjectManager.DoFixups()
             at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
             at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
             at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
             at System.Collections.Generic.Tests.ComparersGenericTests`1.EqualityComparer_SerializationRoundtrip()
```

**Comment by Jiayili1** [comment]
This issue is also repro on UWP F5 Tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20170614.01/workItem/System.Collections.Tests/analysis/xunit/System.Collections.Generic.Tests.BadlyBehavingComparableComparersTests~2FEqualityComparer_SerializationRoundtrip

**Comment by morganbr** [comment]
@ViktorHofer , any guesses on the UWP F5 failure? That's not related to the original MissingMetadataException.

**Comment by ViktorHofer** [comment]
I will look into it after I've finished my work today

**Comment by ViktorHofer** [comment]
Is still happening? It seems this issue contains multiple issues, right?

**Comment by safern** [comment]
Yes this is still happening, the tests are disabled. Yes the issue contains multiple failures that are all related to serialization stuff. The tests are disabled against this issue, so if you search for the issue number in the test src code you will find all the tests easily.

**Comment by ViktorHofer** [comment]
Okay I will take a look. I found these matching tests:
```
Common\tests\System\Collections\IEnumerable.Generic.Serialization.Tests.cs:        [ActiveIssue(20888, TargetFrameworkMonikers.UapAot)]
System.Collections\tests\Generic\Comparers\EqualityComparer.Generic.Serialization.Tests.cs:        [ActiveIssue(20888, TargetFrameworkMonikers.Uap)]
System.Collections\tests\Generic\Dictionary\Dictionary.Tests.cs:        [ActiveIssue(20888, TargetFrameworkMonikers.UapAot)]
System.Collections\tests\Generic\Dictionary\Dictionary.Tests.cs:        [ActiveIssue(20888, TargetFrameworkMonikers.UapAot)]
```

**Comment by DnlHarvey** [comment]
Viktor did you find anything? Most of these tests pass for me, the ones that don't have a test bug where they don't have reflection metadata for these types:
KeyCollection
KeyList
ValueCollection
ValueList

**Comment by morganbr** [comment]
@DnlHarvey, as you look at the MissingMetadataExceptions, please let us know if there are patterns the tests use that analysis should pick up automatically. If you do need to add rd.xml, there's now a BinaryFormatter degree, so it would look like:
```
<Type Name="Namespace.Of.KeyCollection" BinaryFormatter="Required All" />
```
