### ISSUE TITLE
Test failure: System.Net.Sockets.Tests.DualModeConnectAsync / DualModeConnectAsync_Static_DnsEndPointToHost_Helper

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20893]
## Types of failures

```
Timed out while waiting for connection
Expected: True
Actual:   False
at System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_Static_DnsEndPointToHost_Helper(IPAddress listenOn, Boolean dualModeServer) in /root/corefx-1213655/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 610
```

## History of failures

Day | Build | OS
-- | -- | --
2017/9/14 | 20170914.01 | OSX10.12
2017/10/29 | 20171029.01 | OSX10.12
2017/12/11 | 20171211.05 | Fedora25
3/31 | 20180331.05 | OSX10.12

# Original report

https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release_prtest/4505/consoleFull#18036880242d31e50d-1517-49fc-92b3-2ca637122019

```     System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_Static_DnsEndPointToHost_Helper(listenOn: 127.0.0.1, dualModeServer: False) [FAIL]
19:07:03         Timed out while waiting for connection
19:07:03         Expected: True
19:07:03         Actual:   False
19:07:03         Stack Trace:
19:07:03   Using as the test runtime folder.
19:07:03   ls: /cores: No such file or directory
19:07:03   Running tests... Start time: 19:07:03
19:07:03   Commands:
19:07:03   python DumplingHelper.py install_dumpling
19:07:03   __TIMESTAMP=`python DumplingHelper.py get_timestamp`
19:07:03   chmod +x /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/bin/testhost/netcoreapp-OSX-Release-x64//dotnet
19:07:03   /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/bin/testhost/netcoreapp-OSX-Release-x64//dotnet xunit.console.netcore.exe System.Text.Encoding.CodePages.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonosxtests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
19:07:03   python DumplingHelper.py collect_dump $\ `pwd`  System.Text.Encoding.CodePages.Tests /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/bin/runtime/netcoreapp-OSX-Release-x64/,/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/bin/AnyOS.AnyCPU.Release/System.Text.Encoding.CodePages.Tests/netstandard/
19:07:03   /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/bin/AnyOS.AnyCPU.Release/System.Text.Encoding.CodePages.Tests/netstandard /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Text.Encoding.CodePages/tests
19:07:03            /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(654,0): at System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_Static_DnsEndPointToHost_Helper(IPAddress listenOn, Boolean dualModeServer)
19:07:03      System.Net.Sockets.Tests.DualModeConnectionlessSendTo.SendToV4IPEndPointToV4Host_Success [FAIL]
19:07:03         System.TimeoutException : The operation has timed out.
19:07:03         Stack Trace:
19:07:03            /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(1151,0): at System.Net.Sockets.Tests.DualModeConnectionlessSendTo.DualModeSendTo_IPEndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout)
19:07:03      System.Net.Sockets.Tests.DualModeConnectionlessBeginSendTo.BeginSendToV6IPEndPointToV6Host_Success [FAIL]
19:07:03         System.TimeoutException : The operation has timed out.
19:07:03         Stack Trace:
19:07:03            /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(1252,0): at System.Net.Sockets.Tests.DualModeConnectionlessBeginSendTo.DualModeBeginSendTo_EndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout)
19:07:03   Using as the test runtime fold
```

**Comment by Jiayili1** [comment]
failed again in CI: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/180/testReport/System.Net.Sockets.Tests/DualModeConnectAsync/DualModeConnectAsync_DnsEndPointToHost_Helper_listenOn____1__dualModeServer__False_/

**Comment by Sunny-pu** [comment]
failed again in CI:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_release/271/testReport/System.Net.Sockets.Tests/DualModeConnectAsync/DualModeConnectAsync_DnsEndPointToHost_Helper_listenOn____1__dualModeServer__False_/

**Comment by wfurt** [comment]
This failed once in last four month (5/17) I'm not sure if it is worth of keeping it open @karelz

**Comment by wfurt** [comment]
it did not fail in last three months. It seems like old intermittent infrastructure problem.

**Comment by danmosemsft** [comment]
Failed again, now flaky on UWP (or at least, failed once)
```

Error message
Timed out while waiting for connection\r\nExpected: True\r\nActual: False

Stack trace
   at System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_Static_DnsEndPointToHost_Helper(IPAddress listenOn, Boolean dualModeServer) in /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 613
```

**Comment by ahsonkhan** [comment]
Failed again here https://github.com/dotnet/corefx/pull/40303 for `Windows Build UWP_CoreCLR_x64_Debug`:
https://helix.dot.net/api/2019-06-17/jobs/21c7efa2-5a7f-49bf-9c9b-9f3d793613e3/workitems/System.Net.Sockets.Tests/console
```text
Starting:    System.Net.Sockets.Tests (parallel test collections = on, max threads = 2)
    System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_DnsEndPointToHost_Helper(listenOn: 127.0.0.1, dualModeServer: False) [FAIL]
      Timed out while waiting for connection
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(588,0): at System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_DnsEndPointToHost_Helper(IPAddress listenOn, Boolean dualModeServer)
  Finished:    System.Net.Sockets.Tests
```

**Comment by AriNuer** [comment]
Test `System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_Static_DnsEndPointToHost_Helper` failed again:
```

Error message
Timed out while waiting for connection\r\nExpected: True\r\nActual: False

Stack trace
   at System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_Static_DnsEndPointToHost_Helper(IPAddress listenOn, Boolean dualModeServer) in /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 613
```
Details:
https://dnceng.visualstudio.com/public/_build/results?buildId=316080&view=ms.vss-test-web.build-test-results-tab&runId=9143850&resultId=148005&paneView=debug

**Comment by ViktorHofer** [comment]
Failed again but this time on netcoreapp: https://dnceng.visualstudio.com/public/_build/results?buildId=334906&view=ms.vss-test-web.build-test-results-tab&runId=9862974&resultId=177921&paneView=debug

Configuration: `netcoreapp-Windows_NT-Release-x86-Windows.10.Amd64.Client19H1.Open`

```
Timed out while waiting for connection\r\nExpected: True\r\nActual: False

   at System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_Static_DnsEndPointToHost_Helper(IPAddress listenOn, Boolean dualModeServer) in /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 614
```

**Comment by ViktorHofer** [comment]
Happened again: https://dnceng.visualstudio.com/public/_build/results?buildId=358741&view=ms.vss-test-web.build-test-results-tab&runId=10867932&resultId=176327&paneView=debug

@davidsh any recommendation? seems to feel frequently enough to take a look.

**Comment by davidsh** [comment]
@ViktorHofer 

>Happened again: https://dnceng.visualstudio.com/public/_build/results?buildId=358741&view=ms.vss-test-web.build-test-results-tab&runId=10867932&resultId=176327&paneView=debug

This is a disabled-test.  How can it happen again?

**Comment by wfurt** [comment]
It is disabled on UWP but I'm not sure if the run was. It seems like 32bit windows from brief look.

**Comment by davidsh** [comment]
@wfurt Can you take a look?

**Comment by wfurt** [comment]
I can check if I can reproduce it locally. If not, we will need some way how to re-create CI environment.

**Comment by ViktorHofer** [comment]
This happened again on `netcoreapp-Windows_NT-Release-x86-Windows.10.Amd64.Client19H1.Open`: https://dnceng.visualstudio.com/public/_build/results?buildId=367004&view=ms.vss-test-web.build-test-results-tab&runId=11106936&paneView=debug

Can somebody please take another look? RetryHelper / LoopbackServer might help here?

**Comment by ViktorHofer** [comment]
cc @davidsh @wfurt @eiriktsarpalis happened again in master: https://dnceng.visualstudio.com/public/_build/results?buildId=371143&view=ms.vss-test-web.build-test-results-tab&runId=11295054&resultId=176777&paneView=debug

Configuration: `netcoreapp-Windows_NT-Release-x86-Windows.10.Amd64.Client19H1.Open`

```
Timed out while waiting for connection\r\nExpected: True\r\nActual: False

   at System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_Static_DnsEndPointToHost_Helper(IPAddress listenOn, Boolean dualModeServer) in /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 614
```

**Comment by ViktorHofer** [comment]
Any idea why `DualModeConnectAsync_Static_DnsEndPointToHost_Helper` is timing out so often?

**Comment by davidsh** [comment]
This issue was specific to the UAP implementation of the networking stack which had a different implementation for things like HTTP and WebSockets.

As of PR #41759, we no longer build the separate implementation for the UAP platform. So, this issue can't occur anymore with .NET 5 because we now will be using the same .NET Core implementation as on Windows, Linux, Mac.

**Comment by ViktorHofer** [comment]
David this was failing on netcoreapp: https://dnceng.visualstudio.com/public/_build/results?buildId=390088&view=ms.vss-test-web.build-test-results-tab&runId=12095578&resultId=178765&paneView=debug

**Comment by davidsh** [comment]
@wfurt Another test failure in Sockets to investigate.
