### ISSUE TITLE
Desktop: System.Tests.GCExtendedTests.GCNotificationTests failed with "Xunit.Sdk.AllException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#20955]
Failed test: System.Tests.GCExtendedTests.GCNotificationTests

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/84/consoleText

~~~
System.Tests.GCExtendedTests.GCNotificationTests(approach: True, timeout: -1) [FAIL]
        Assert.All() Failure: 2 out of 2 items in the collection did not pass.
        [1]: Xunit.Sdk.TrueException: Field marshaling is not supported by RemoteInvoke: timeout
             Expected: True
             Actual:   False
                at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\BooleanAsserts.cs:line 90
                at System.Diagnostics.RemoteExecutorTestBase.<>c.<GetMethodInfo>b__20_0(FieldInfo fi) in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Diagnostics\RemoteExecutorTestBase.cs:line 275
                at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\CollectionAsserts.cs:line 31
        [0]: Xunit.Sdk.TrueException: Field marshaling is not supported by RemoteInvoke: approach
             Expected: True
             Actual:   False
                at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\BooleanAsserts.cs:line 90
                at System.Diagnostics.RemoteExecutorTestBase.<>c.<GetMethodInfo>b__20_0(FieldInfo fi) in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Diagnostics\RemoteExecutorTestBase.cs:line 275
                at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\CollectionAsserts.cs:line 31
        Stack Trace:
          D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Diagnostics\RemoteExecutorTestBase.cs(273,0): at System.Diagnostics.RemoteExecutorTestBase.GetMethodInfo(Delegate d)
          D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Diagnostics\RemoteExecutorTestBase.cs(48,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvoke(Func`1 method, RemoteInvokeOptions options)
          D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime\tests\System\GCTests.cs(491,0): at System.Tests.GCExtendedTests.GCNotificationTests(Boolean approach, Int32 timeout)
~~~

**Comment by Jiayili1** [comment]
This issue is also repro on Core Tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170613.01/workItem/System.Runtime.Tests/analysis/xunit/System.Tests.GCExtendedTests~2FGCNotificationTests(approach:%20False,%20timeout:%20-1)

**Comment by danmosemsft** [comment]
Thanks @Jiayili1 , I fixed it: https://github.com/dotnet/corefx/pull/20953
