### ISSUE TITLE
System.Net.Http.Functional.Tests.HttpClientHandlerTest Fail on ARM/Linux

### ISSUE THREAD

**Issue by seanshpark** [dotnet/corefx#20965]
I get this error with release/2.0.0 and master branch running with RPi3/Ubuntu16.04
```
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Net.Http.Functional.Tests
Discovered:  System.Net.Http.Functional.Tests
Starting:    System.Net.Http.Functional.Tests
  System.Net.Http.Functional.Tests.HttpClientHandlerTest.Dispose_DisposingHandlerCancelsActiveOperationsWithoutResponses [FAIL]
      System.Threading.Tasks.TaskCanceledException : A task was canceled.
```
works with x64/Linux.

I get some timeout related answers when I search `A task was canceled` message, but doesn't seem to be the timeout issue for this case.

Could someone help me what `Dispose_DisposingHandlerCancelsActiveOperationsWithoutResponses` is trying to test and what may be the problem? Could it be my Linux environmental problem?

**Comment by Priya91** [comment]
@karelz Is Arm/Linux a supported scenario?

**Comment by Priya91** [comment]
@seanshpark The reported error doesn't have much information to provide help further, task canceled just means the operation might have timed out. Requires debugging for further investigation.

**Comment by seanshpark** [comment]
@karelz , @Priya91 , Thank you :) 
OK, I'll trace inside of CoreFX/CoreCLR and find out the cause.

**Comment by seanshpark** [comment]
Does this message point to something?
```
   System.Net.Http.Functional.Tests.HttpClientHandlerTest.Dispose_DisposingHandlerCancelsActiveOperationsWithoutResponses [FAIL]
      System.Threading.Tasks.TaskCanceledException : A task was canceled.
      Stack Trace:
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         /home/maxwell/netcore/corefx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs(1042,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass61_1.<<Dispose_DisposingHandlerCancelsActiveOperationsWithoutResponses>b__2>d.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         /home/maxwell/netcore/corefx/src/Common/tests/System/Net/Http/LoopbackServer.cs(57,0): at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass3_0.<CreateServerAsync>b__0(Task t)
            at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
            at System.Threading.Tasks.Task.<>c.<.cctor>b__276_1(Object obj)
            at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
            at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         /home/maxwell/netcore/corefx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs(999,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass61_0.<<Dispose_DisposingHandlerCancelsActiveOperationsWithoutResponses>b__1>d.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         /home/maxwell/netcore/corefx/src/Common/tests/System/Net/Http/LoopbackServer.cs(57,0): at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass3_0.<CreateServerAsync>b__0(Task t)
            at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
            at System.Threading.Tasks.Task.<>c.<.cctor>b__276_1(Object obj)
            at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
            at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         /home/maxwell/netcore/corefx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs(997,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c.<<Dispose_DisposingHandlerCancelsActiveOperationsWithoutResponses>b__61_0>d.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         /home/maxwell/netcore/corefx/src/Common/tests/System/Net/Http/LoopbackServer.cs(57,0): at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass3_0.<CreateServerAsync>b__0(Task t)
            at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
            at System.Threading.Tasks.Task.<>c.<.cctor>b__276_1(Object obj)
            at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
            at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         /home/maxwell/netcore/corefx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs(995,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<Dispose_DisposingHandlerCancelsActiveOperationsWithoutResponses>d__61.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Finished:    System.Net.Http.Functional.Tests
```

**Comment by seanshpark** [comment]
Reason was that my RPi3 had proxy configuration and HttpClient tried to connect through the proxy server. Removing the environment variable `http_proxy` and `https_proxy` made `Dispose_DisposingHandlerCancelsActiveOperationsWithoutResponses`  pass.

I'm not sure why URL is `http://127.0.0.1/` and it was trying to connect through proxy server.

**Comment by seanshpark** [comment]
> I'm not sure why URL is http://127.0.0.1/ and it was trying to connect through proxy server.

Seems related. #13464
