### ISSUE TITLE
Utils.AddObject for incompatible types throws ArgumentNullException for missing string resource

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#21088]
Example test code fails with ArgumentNullException in .NET Core. Neftx throws InvalidCastException:
```
using Microsoft.VisualBasic.CompilerServices;
Assert.Throws<InvalidCastException>(() => Operators.AddObject(1, '2'));
```

Stack trace:
```
 System.ArgumentNullException : Value cannot be null.
        Parameter name: format
        Stack Trace:
              at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
              at System.String.Format(String format, Object[] args)
              at System.SR.Format(String resourceFormat, Object[] args)
              at Microsoft.VisualBasic.CompilerServices.Utils.GetResourceString(String resourceKey, String[] args)
              at Microsoft.VisualBasic.CompilerServices.Operators.GetNoValidOperatorException(UserDefinedOperator op, O
  bject left, Object right)
              at Microsoft.VisualBasic.CompilerServices.Operators.AddObject(Object left, Object right)
              at Microsoft.VisualBasic.CompilerServices.Tests.OperatorsTests.AddObject_Incompatible_Throws(Object left,
   Object right)
```

**Comment by danmosemsft** [comment]
I think this is a bug... :)
