### ISSUE TITLE
Uri(String, UriKind) throws IndexOutOfRangeException for certain inputs

### ISSUE THREAD

**Issue by davkean** [dotnet/corefx#21202]
We're relying on `Uri` in the http://github.com/dotnet/project-system, to represent paths. Testing our path handling code, I found that Uri throws IndexOutOfRangeException (instead of UriFormatException) in the following situations:

``` C#
new Uri("/\\‎//", UriKind.Absolute);
new Uri("/\\\\-Ā\r", UriKind.Absolute);
new Uri("\\\\\\\\\\‎", UriKind.Absolute);
```

**Comment by danmosemsft** [comment]
@davkean none of these throw anything (including UFE) on Desktop for me..?

Clearly this isa bug though as they throw IOORE on Core.
```
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Uri.CreateUriInfo(Flags cF)
   at System.Uri.EnsureUriInfo()
   at System.Uri.ParseRemaining()
   at System.Uri.EnsureParseRemaining()
   at System.Uri.InitializeUri(ParsingError err, UriKind uriKind, UriFormatException& e)
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at ConsoleApp1.Program.Main(String[] args) in C:\dotnet\1\Program.cs:line 13
```

@karelz is this the right label for Uri? Please consider whether this is a 2.0 issue.

**Comment by danmosemsft** [comment]
@Priya91 fyi

**Comment by danmosemsft** [comment]
My guess: these are not mainstream enough cases to churn Uri further for 2.0.

**Comment by karelz** [comment]
It's a good label. @Priya91 can you please help with this one?

**Comment by Priya91** [comment]
@davkean These are invalid URIs?  Will look into this.

**Comment by davkean** [comment]
@danmosemsft Are you testing under 4.5+? Uri was changed in 4.5. I just verified and they all repro for me under desktop. 

@Priya91 TBH, I've not done the legwork to figure out if they are invalid according to spec - they were generated for me by Pex. I don't need them for 2.0.

**Comment by danmosemsft** [comment]
@davkean ah, no I used csc out of the v4.0 folder...

**Comment by davkean** [comment]
Yeah, you'll go down the 4.0 path.

**Comment by karelz** [comment]
Does not look like 2.0 bug, moving to Future for further consideration.

**Comment by rmkerr** [comment]
It looks like all of these are failing because they contain the Unicode LTR control character. Historically we have stripped control characters out of URIs, and that behavior is causing the issue here. We calculate the index of the end of the path and then strip out the control character, shortening the string and causing the index to fall beyond the end of the string.

I'm not sure exactly what the fix will look like here, but it should be fairly straightforward. I'll try to get a PR out by eod today.
