### ISSUE TITLE
Dumpling fails with  AttributeError: DumplingConfig instance has no attribute 'dbgpath'

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#21225]
```
21:18:56   python DumplingHelper.py install_dumpling
21:18:56   __TIMESTAMP=`python DumplingHelper.py get_timestamp`
21:18:56   chmod +x /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/bin/testhost/netcoreapp-Linux-Debug-x64//dotnet
21:18:56   /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/bin/testhost/netcoreapp-Linux-Debug-x64//dotnet xunit.console.netcore.exe System.IO.FileSystem.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
21:18:56   python DumplingHelper.py collect_dump $\ `pwd`  System.IO.FileSystem.Tests /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/bin/runtime/netcoreapp-Linux-Debug-x64/,/mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/bin/Unix.AnyCPU.Debug/System.IO.FileSystem.Tests/netcoreapp/
21:18:56   /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/bin/Unix.AnyCPU.Debug/System.IO.FileSystem.Tests/netcoreapp /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/src/System.IO.FileSystem/tests
21:18:56   downloaded dumpling.py
21:18:56   total elapsed time 0:00:00.178800
21:18:56   xUnit.net console test runner (64-bit .NET Core)
21:18:56   Copyright (C) 2014 Outercurve Foundation.
21:18:56   
21:18:56   Discovering: System.IO.FileSystem.Tests
21:18:57   Discovered:  System.IO.FileSystem.Tests
21:18:58   Traceback (most recent call last):
21:18:58     File "/mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/tempHome/.dumpling/dumpling.py", line 1128, in <module>
21:18:58       main(sys.argv)
21:18:58     File "/mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/tempHome/.dumpling/dumpling.py", line 1123, in main
21:18:58       cmdProc.Process(config)
21:18:58     File 
"/mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/tempHome/.dumpling/dumpling.py", line 529, in Process
21:18:58       self.Upload(config)
21:18:58     File "/mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/tempHome/.dumpling/dumpling.py", line 624, in Upload
21:18:58       self.UploadDump(config)
21:18:58     File "/mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/tempHome/.dumpling/dumpling.py", line 644, in UploadDump
21:18:58       self._triage_dump(dumpid, config.dumppath, config)
21:18:58     File "/mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/tempHome/.dumpling/dumpling.py", line 812, in _triage_dump
21:18:58       if config.dbgpath is None:
21:18:58   AttributeError: DumplingConfig instance has no attribute 'dbgpath'
```
https://ci.dot.net/job/dotnet_corefx/job/master/job/rhel7.2_debug/2971/consoleFull#32536873579fe3b83-f408-404c-b9e7-9207d232e5fc

@mellinoe

**Comment by mellinoe** [comment]
Moved over to https://github.com/Microsoft/dumpling/issues/30.

FWIW, it looks like the crash dumps are still being uploaded successfully.
