### ISSUE TITLE
Can't set SqlParameter.DbType to Date

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/corefx#21279]
Executing `parameter.DbType = DbType.Date;` sets `SqlParameter.DbType` to `DbType.DateTime`

This results in an exception:

```C#
System.Data.SqlTypes.SqlTypeException occurred
  HResult=0x80131930
  Message=SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Data.SqlClient.TdsParser.TdsExecuteRPC(_SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DateParameterBug.Program.Main(String[] args) in C:\Users\ansvyryd\source\repos\DateParameterBug\DateParameterBug\Program.cs:line 44
```
when executing the following code
```C#
using System;
using System.Data;
using System.Data.SqlClient;

namespace DateParameterBug
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var conn = new SqlConnection("Server=(localdb)\\mssqllocaldb;Database=master;Trusted_Connection=True"))
            {
                conn.Open();
                using (var command = conn.CreateCommand())
                {
                    command.CommandText = "CREATE DATABASE DateParameterBug";
                    command.ExecuteNonQuery();
                }
            }

            using (var conn = new SqlConnection("Server=(localdb)\\mssqllocaldb;Database=DateParameterBug;Trusted_Connection=True"))
            {
                conn.Open();
                using (var command = conn.CreateCommand())
                {
                    command.CommandText = @"CREATE TABLE [Item] (
    [Id] int NOT NULL IDENTITY,
    [Date] date NOT NULL,
    CONSTRAINT [PK_Item] PRIMARY KEY([Id])
);";
                    command.ExecuteNonQuery();
                }

                using (var command = conn.CreateCommand())
                {
                    command.CommandText = @"INSERT [dbo].[Item] ([Date]) VALUES (@date)";
                    var parameter = new SqlParameter();
                    parameter.ParameterName = "@date";
                    parameter.DbType = DbType.Date;
                    parameter.Value = new DateTime(1605, 1, 15);
                    command.Parameters.Add(parameter);
                    command.ExecuteNonQuery();
                }
            }
        }
    }
}
```
Targeting `netcoreapp2.0`
Referencing `System.Data.SqlClient 4.4.0-preview2-25405-01`

**Comment by saurabh500** [comment]
@AndriySvyryd Why is this a bug? The value in `parameter.Value = new DateTime(1605, 1, 15);` is out of bounds as explained in the error message.

**Comment by saurabh500** [comment]
I get the context after reading the EF issue. The implicit conversion from DbType.Date to DbType.DateTime is the problem leading to this issue.

**Comment by AndriySvyryd** [comment]
I see that this wasn't fixed for back compat https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlParameter.cs#L249
But it's unfortunate that it was carried over to Core

**Comment by saurabh500** [comment]
In principle `the back compat bugs` will have to stay in .Net Core because we need to have the behavior compat as close as possible to .Net Framework.

**Comment by saurabh500** [comment]
Closing this as the bug was carried over from framework, and in framework it was not fixed for back compat reasons
