### ISSUE TITLE
RemoteInvoke + Both reading/writing to a file does not seem to work

### ISSUE THREAD

**Issue by kouvel** [dotnet/corefx#21276]
The test is using FileCleanupTestBase.GetTestFilePath(), but it's getting the following exception from the remote process:

```
  ERROR:    System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic(prefix: "dd63f96fc81d41239d884790ad70bd6c") [FAIL]
        System.AggregateException : One or more errors occurred. (RemoteExecuter: System.Threading.Tests, Version=4.1.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb <CrossProcess_NamedMutex_ProtectedFileAccessAtomic>b__15_1 dd63f96fc81d41239d884790ad70bd6ca4c011e6fad843faa29b09c69631e03f, "C:\Users\<user>\AppData\Local\Packages\5cd54353-3ed7-4a6e-a72f-db349f28867c_v52bfwc2c21ha\AC\Temp\MutexTests_s5jxc3bf.q23\CrossProcess_NamedMutex_ProtectedFileAccessAtomic_228_e009ac76"
        System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotSupportedException: The format of the path '"C:\Users\<user>\AppData\Local\Packages\5cd54353-3ed7-4a6e-a72f-db349f28867c_v52bfwc2c21ha\AC\Temp\MutexTests_s5jxc3bf.q23\CrossProcess_NamedMutex_ProtectedFileAccessAtomic_228_e009ac76"' is not supported.
           at System.IO.Path.GetFullPath(String path)
           at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
           at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
           at System.IO.StreamWriter..ctor(String path)
           at System.IO.File.WriteAllText(String path, String contents)
           at System.Threading.Tests.MutexTests.<>c.<CrossProcess_NamedMutex_ProtectedFileAccessAtomic>b__15_1(String m, String f)
           --- End of inner exception stack trace ---
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
           at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
           at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
           at RunnerRemoteExecutionService.RemoteExecutor.HandleTheRequest(ValueSet message, ValueSet returnData)
        Returned Error code: -4
        Expected: True
        Actual:   False)
        ---- RemoteExecuter: System.Threading.Tests, Version=4.1.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb <CrossProcess_NamedMutex_ProtectedFileAccessAtomic>b__15_1 dd63f96fc81d41239d884790ad70bd6ca4c011e6fad843faa29b09c69631e03f, "C:\Users\<user>\AppData\Local\Packages\5cd54353-3ed7-4a6e-a72f-db349f28867c_v52bfwc2c21ha\AC\Temp\MutexTests_s5jxc3bf.q23\CrossProcess_NamedMutex_ProtectedFileAccessAtomic_228_e009ac76"
        System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotSupportedException: The format of the path '"C:\Users\<user>\AppData\Local\Packages\5cd54353-3ed7-4a6e-a72f-db349f28867c_v52bfwc2c21ha\AC\Temp\MutexTests_s5jxc3bf.q23\CrossProcess_NamedMutex_ProtectedFileAccessAtomic_228_e009ac76"' is not supported.
           at System.IO.Path.GetFullPath(String path)
           at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
           at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
           at System.IO.StreamWriter..ctor(String path)
           at System.IO.File.WriteAllText(String path, String contents)
           at System.Threading.Tests.MutexTests.<>c.<CrossProcess_NamedMutex_ProtectedFileAccessAtomic>b__15_1(String m, String f)
           --- End of inner exception stack trace ---
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
           at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
           at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
           at RunnerRemoteExecutionService.RemoteExecutor.HandleTheRequest(ValueSet message, ValueSet returnData)
        Returned Error code: -4
        Expected: True
        Actual:   False
        Stack Trace:
             at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass3_0.<CreateGuardedThread>b__1()
             at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass3_0.<CreateGuardedThread>b__2()
             at System.Threading.Tests.ThreadTestHelpers.RunTestInBackgroundThread(Action test)
             at System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic(String prefix)
          ----- Inner Stack Trace -----
             at System.Diagnostics.RemoteExecutorTestBase.RemoteInvoke(MethodInfo method, String[] args, RemoteInvokeOptions options)
             at System.Diagnostics.RemoteExecutorTestBase.RemoteInvoke(Func`3 method, String arg1, String arg2, RemoteInvokeOptions options)
             at System.Threading.Tests.MutexTests.<>c__DisplayClass15_0.<CrossProcess_NamedMutex_ProtectedFileAccessAtomic>b__0()
             at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass3_0.<CreateGuardedThread>b__0()
```

Disabled tests:
- https://github.com/dotnet/corefx/blob/master/src/System.Threading/tests/MutexTests.cs#L176

**Comment by danmosemsft** [comment]
@kouvel the issue is in the exception string-- the path is surrounded by double quotes

**Comment by Jiayili1** [comment]
Following test: System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess/PingPong 
still failed with:

RemoteExecuter: System.IO.Pipes.Tests, Version=4.1.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb PingPong_OtherProcess 2136, 2144

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20170626.01/workItem/System.IO.Pipes.Tests/analysis/xunit/System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess~2FPingPong

**Comment by danmosemsft** [comment]
Pingpong is covered by https://github.com/dotnet/corefx/issues/21275

**Comment by danmosemsft** [comment]
There is still an issue disabled for this. @safern if it passes can yo uremove the attribute?
        [ActiveIssue(21276, TargetFrameworkMonikers.Uap)]

**Comment by safern** [comment]
Sure

**Comment by safern** [comment]
The test passes locally for me. Opening PR.
