### ISSUE TITLE
[porting] SystemIcons.ShieldIcon fails with `Resource 'ShieldIcon.ico' cannot be found in class 'System.Drawing.SystemIcons'`

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#21310]
The code for `SystemIcons.Shield` is as follows

```c#
Contract.Ensures(Contract.Result<Icon>() != null);

if (s_shield == null)
{
    try
    {
        // IDI_SHIELD is defined in OS Vista and above
        if (Environment.OSVersion.Version.Major >= 6)
        {
            // we hard-code size here, to prevent breaking change
            // the size of _shield before this change is always 32 * 32  
            IntPtr hIcon = IntPtr.Zero;
            int result = SafeNativeMethods.LoadIconWithScaleDown(NativeMethods.NullHandleRef, SafeNativeMethods.IDI_SHIELD, 32, 32, ref hIcon);

            if (result == 0)
                s_shield = new Icon(hIcon);
        }
    }
    catch (Exception)
    {
        // we don't want to throw exception here.
        // If there is an exception, we will load an icon from file ShieldIcon.ico
    }
}
if (s_shield == null)
{
    s_shield = new Icon(typeof(SystemIcons), "ShieldIcon.ico");
}
return s_shield;
```

The first error we get is an `EntrypointNotFoundException`  for `LoadIconWithScaleDown` which is likely a bug

The second error we get is constructing the icon:
```c#
 System.Drawing.Tests.SystemIconsTests.SystemIcons_Get_ReturnsExpected(iconThunk: Func`1 { Method = System.Drawing.
  Icon <SystemIcons_TestData>b__0_7(), Target = <>c { } }) [FAIL]
        System.ArgumentException : Resource 'ShieldIcon.ico' cannot be found in class 'System.Drawing.SystemIcons'.
        Stack Trace:
              at System.Drawing.Icon..ctor(Type type, String resource)
              at System.Drawing.SystemIcons.get_Shield()
              at System.Drawing.Tests.SystemIconsTests.<>c.<SystemIcons_TestData>b__0_7()
              at System.Drawing.Tests.SystemIconsTests.SystemIcons_Get_ReturnsExpected(Func`1 iconThunk)
```

This is likely because the logical name of the embedded resource icon is incorrect .

I'll submit a fix for the first part

**Comment by hughbe** [comment]
The fix for this exception is easy: changing the csproj of the product code from
```xml
<EmbeddedResource Include="Resources\System\Drawing\ShieldIcon.ico" />
```

to 

```xml
<EmbeddedResource Include="Resources\System\Drawing\ShieldIcon.ico">
    <LogicalName>System.Drawing.ShieldIcon.ico</LogicalName>
</EmbeddedResource>
```

However, this silences the fact that we throw an `EntryPointNotFoundException` before

**Comment by hughbe** [comment]
Okay, so it's expected that `LoadIconWithScaleDown` as it has been removed in later versions of Windows. This means that the catch block is expected.

@mellinoe do you know when LoadIconWithScaleDown was removed from the Win32 API? If the API is not available in Windows 7, let's delete it and return the `ShieldIcon.ico` all the time.

I'd like to submit a PR with at least the fix about when '21177 is merged

**Comment by hughbe** [comment]
The [documentation](https://msdn.microsoft.com/en-us/windows/bb775703) doesn't seem to mention anything about this entry point being removed 

The only reference I can find about ShieldIcon's removal is [here](http://huseyint.com/2014/01/Setting-UAC-shield-icon-on-buttons/):

> Even though I am on Windows 8.1, I am getting Windows Vista's 4 color UAC shield icon. If you dig down the SystemIcons.Shield code with Reflector, you will see that the getter of this property first tries to load the system UAC shield icon using a P/Invoke code to LoadIconWithScaleDown function of comctl32.dll. This call fails, you can see that on your Visual Studio output pane reporting a first chance exception of type EntryPointNotFoundException thrown. The reason is, LoadIconWithScaleDown seems to be removed on a later version of comctl32.dll. Fortunately, the getter has a backup method which gets the icon loaded from the System.Drawing.dll embedded resources, which unfortunately is the old UAC shield icon:

So Windows 8 doesn't have this API, but does Windows 7?
