### ISSUE TITLE
CommandCancelTest.TimeoutCancel fails when using managed SNI

### ISSUE THREAD

**Issue by corivera** [dotnet/corefx#21324]
Test results:
FAILURE: - unexpected non-open state after Execute!
Expected: True
Actual:   False

Stack Trace:
System.Data.SqlClient\tests\ManualTests\SQL\CommandCancelTest\CommandCancelTest.cs(198,0): at System.Data.SqlClient.ManualTesting.Tests.CommandCancelTest.VerifyConnection(SqlCommand cmd)
System.Data.SqlClient\tests\ManualTests\SQL\CommandCancelTest\CommandCancelTest.cs(154,0): at System.Data.SqlClient.ManualTesting.Tests.CommandCancelTest.TimeoutCancel(String constr)

CC @saurabh500

**Comment by corivera** [comment]
Failures observed on Windows. Haven't tested Linux yet.

**Comment by corivera** [comment]
Only happens when using TCP with Encrypt=true. Seems to be related to SslStream being unable to recover after a timeout. In fact, the recommendation for SslStream is to dispose the stream after encountering fatal IOExceptions
