### ISSUE TITLE
Several Environment_Exit tests fail on UAP

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#21415]
Crashing at remote end but currently we don't get console output.
```
 <collection total="15" passed="6" failed="9" skipped="0" name="Test collection for System.Tests.Environment_Exit" time="0.421">
      <test name="System.Tests.Environment_Exit.ExitCode_VoidMainAppReturnsSetValue(mode: 1)" type="System.Tests.Environment_Exit" method="ExitCode_VoidMainAppReturnsSetValue" time="0.0758323" result="Fail">
        <traits>
          <trait name="category" value="nonuapaottests" />
          <trait name="activeissue" value="https://github.com/dotnet/corefx/issues/20387 - ILC test pipeline does not accomodate tests in child processes built into custom assemblies." />
        </traits>
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 123\r\nActual:   -2146234294]]></message>
          <stack-trace><![CDATA[   at System.Tests.Environment_Exit.ExitCode_VoidMainAppReturnsSetValue(Int32 mode)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Tests.Environment_Exit.ExitCode_VoidMainAppReturnsSetValue(mode: 2)" type="System.Tests.Environment_Exit" method="ExitCode_VoidMainAppReturnsSetValue" time="0.0562022" result="Fail">
        <traits>
          <trait name="category" value="nonuapaottests" />
          <trait name="activeissue" value="https://github.com/dotnet/corefx/issues/20387 - ILC test pipeline does not accomodate tests in child processes built into custom assemblies." />
        </traits>
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 123\r\nActual:   -2146234294]]></message>
          <stack-trace><![CDATA[   at System.Tests.Environment_Exit.ExitCode_VoidMainAppReturnsSetValue(Int32 mode)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Tests.Environment_Exit.ExitCode_VoidMainAppReturnsSetValue(mode: 3)" type="System.Tests.Environment_Exit" method="ExitCode_VoidMainAppReturnsSetValue" time="0.0571893" result="Fail">
        <traits>
          <trait name="category" value="nonuapaottests" />
          <trait name="activeissue" value="https://github.com/dotnet/corefx/issues/20387 - ILC test pipeline does not accomodate tests in child processes built into custom assemblies." />
        </traits>
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 123\r\nActual:   -2146234294]]></message>
          <stack-trace><![CDATA[   at System.Tests.Environment_Exit.ExitCode_VoidMainAppReturnsSetValue(Int32 mode)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Tests.Environment_Exit.CheckExitCode(expectedExitCode: 0)" type="System.Tests.Environment_Exit" method="CheckExitCode" time="0.0354077" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[RemoteExecuter: System.Runtime.Extensions.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb <CheckExitCode>b__1_0 0\r\n\r\nReturned Error code: 0\r\nExpected: True\r\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Diagnostics.RemoteExecutorTestBase.RemoteInvoke(MethodInfo method, String[] args, RemoteInvokeOptions options)
   at System.Diagnostics.RemoteExecutorTestBase.RemoteInvoke(Func`2 method, String arg, RemoteInvokeOptions options)
   at System.Tests.Environment_Exit.CheckExitCode(Int32 expectedExitCode)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Tests.Environment_Exit.CheckExitCode(expectedExitCode: 1)" type="System.Tests.Environment_Exit" method="CheckExitCode" time="0.041603" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[RemoteExecuter: System.Runtime.Extensions.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb <CheckExitCode>b__1_0 1\r\n\r\nReturned Error code: 1\r\nExpected: True\r\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Diagnostics.RemoteExecutorTestBase.RemoteInvoke(MethodInfo method, String[] args, RemoteInvokeOptions options)
   at System.Diagnostics.RemoteExecutorTestBase.RemoteInvoke(Func`2 method, String arg, RemoteInvokeOptions options)
   at System.Tests.Environment_Exit.CheckExitCode(Int32 expectedExitCode)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Tests.Environment_Exit.CheckExitCode(expectedExitCode: 42)" type="System.Tests.Environment_Exit" method="CheckExitCode" time="0.0392276" result="Fail">
        <failure exception-type="System.NullReferenceException">
          <message><![CDATA[System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
          <stack-trace><![CDATA[   at System.Tests.Environment_Exit.CheckExitCode(Int32 expectedExitCode)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Tests.Environment_Exit.CheckExitCode(expectedExitCode: -1)" type="System.Tests.Environment_Exit" method="CheckExitCode" time="0.0376077" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[RemoteExecuter: System.Runtime.Extensions.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb <CheckExitCode>b__1_0 -1\r\n\r\nReturned Error code: -1\r\nExpected: True\r\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Diagnostics.RemoteExecutorTestBase.RemoteInvoke(MethodInfo method, String[] args, RemoteInvokeOptions options)
   at System.Diagnostics.RemoteExecutorTestBase.RemoteInvoke(Func`2 method, String arg, RemoteInvokeOptions options)
   at System.Tests.Environment_Exit.CheckExitCode(Int32 expectedExitCode)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Tests.Environment_Exit.CheckExitCode(expectedExitCode: -45)" type="System.Tests.Environment_Exit" method="CheckExitCode" time="0.0385324" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[RemoteExecuter: System.Runtime.Extensions.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb <CheckExitCode>b__1_0 -45\r\n\r\nReturned Error code: -45\r\nExpected: True\r\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Diagnostics.RemoteExecutorTestBase.RemoteInvoke(MethodInfo method, String[] args, RemoteInvokeOptions options)
   at System.Diagnostics.RemoteExecutorTestBase.RemoteInvoke(Func`2 method, String arg, RemoteInvokeOptions options)
   at System.Tests.Environment_Exit.CheckExitCode(Int32 expectedExitCode)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Tests.Environment_Exit.CheckExitCode(expectedExitCode: 255)" type="System.Tests.Environment_Exit" method="CheckExitCode" time="0.0395036" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[RemoteExecuter: System.Runtime.Extensions.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb <CheckExitCode>b__1_0 255\r\n\r\nReturned Error code: 255\r\nExpected: True\r\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Diagnostics.RemoteExecutorTestBase.RemoteInvoke(MethodInfo method, String[] args, RemoteInvokeOptions options)
   at System.Diagnostics.RemoteExecutorTestBase.RemoteInvoke(Func`2 method, String arg, RemoteInvokeOptions options)
   at System.Tests.Environment_Exit.CheckExitCode(Int32 expectedExitCode)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Tests.Environment_Exit.ExitCode_Roundtrips(exitCode: 0)" type="System.Tests.Environment_Exit" method="ExitCode_Roundtrips" time="0.0003053" result="Pass" />
      <test name="System.Tests.Environment_Exit.ExitCode_Roundtrips(exitCode: 1)" type="System.Tests.Environment_Exit" method="ExitCode_Roundtrips" time="0.0000054" result="Pass" />
      <test name="System.Tests.Environment_Exit.ExitCode_Roundtrips(exitCode: 42)" type="System.Tests.Environment_Exit" method="ExitCode_Roundtrips" time="0.0000017" result="Pass" />
      <test name="System.Tests.Environment_Exit.ExitCode_Roundtrips(exitCode: -1)" type="System.Tests.Environment_Exit" method="ExitCode_Roundtrips" time="0.0000014" result="Pass" />
      <test name="System.Tests.Environment_Exit.ExitCode_Roundtrips(exitCode: -45)" type="System.Tests.Environment_Exit" method="ExitCode_Roundtrips" time="0.0000014" result="Pass" />
      <test name="System.Tests.Environment_Exit.ExitCode_Roundtrips(exitCode: 255)" type="System.Tests.Environment_Exit" method="ExitCode_Roundtrips" time="0.0000014" result="Pass" />
    </collection>

```

**Comment by danmosemsft** [comment]
This needs some local investigation, it's not obvious esp without callstacks on the remote site.

**Comment by safern** [comment]
@krwq I've fixed CheckExitCode test here: https://github.com/dotnet/corefx/pull/21758

The remaining failing test is: System.Tests.Environment_Exit.ExitCode_VoidMainAppReturnsSetValue

**Comment by krwq** [comment]
Moving the remaining test to UWP.6.0.after - I have manually confirmed that this scenario is working but actual fix is more complex (buildtools + remote invoke change) - I have it mostly working locally but currently deprioritizing this test issue in favor of other product issues.

**Comment by krwq** [comment]
Unassigning this since I'm not working on it right now

**Comment by krwq** [comment]
@ViktorHofer is this not issue anymore? Are the related test cases re-enabled?

**Comment by ViktorHofer** [comment]
We don't run Uap on master anymore.
