### ISSUE TITLE
CheckCommandLineArgs_xx tests do not work on UAP

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#21413]
eg
```
      <test name="System.Tests.GetCommandLineArgs.CheckCommandLineArgs_MultipleArgs" type="System.Tests.GetCommandLineArgs" method="CheckCommandLineArgs_MultipleArgs" time="0.0460534" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[RemoteExecuter: System.Runtime.Extensions.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb <RemoteInvoke>b__6_1 Arg1, Arg2
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.InRangeException: Assert.InRange() Failure
Range:  (4 - 2147483647)
Actual: 2
   at Xunit.Assert.InRange[T](T actual, T low, T high, IComparer`1 comparer)
   at System.Tests.GetCommandLineArgs.CheckCommandLineArgs(String[] args)
   at System.Tests.GetCommandLineArgs.<>c.<RemoteInvoke>b__6_1(String arg1, String arg2)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at RunnerRemoteExecutionService.RemoteExecutor.HandleTheRequest(ValueSet message, ValueSet returnData)
Returned Error code: -4
Expected: True
Actual:   False]]></message>
```

**Comment by danmosemsft** [comment]
Probably can be passed on for UWP6.0

**Comment by danmosemsft** [comment]
dupe https://github.com/dotnet/corefx/issues/21122

**Comment by krwq** [comment]
This was closed as a dupe and dupe was closed because test case was gone. Here is the test case:

```
System.Runtime.Extensions/tests/System/Environment.GetCommandLineArgs.cs:12:    [ActiveIssue("https://github.com/dotnet/corefx/issues/21413", TargetFrameworkMonikers.Uap)]
```
