### ISSUE TITLE
Some Xml OuterLoop tests are failing because files are not found

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#21474]
<details>

```
  Discovering: System.Xml.XmlSchemaSet.Tests
  Discovered:  System.Xml.XmlSchemaSet.Tests
  Starting:    System.Xml.XmlSchemaSet.Tests
     System.Xml.Tests.TC_SchemaSet_Add_URL.bug298991Sequence(size: 1000, xsdFileName: \"1000s.xsd\") [FAIL]
        System.IO.FileNotFoundException : Could not find file 'd:\corefx4\bin\Windows_NT.AnyCPU.Debug\System.Xml.XmlSch
  emaSet.Tests\netcoreapp\1000s.xsd'.
        Stack Trace:
              at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
              at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 buffe
  rSize, FileOptions options)
              at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 buffe
  rSize)
           d:\corefx4\src\System.Private.Xml\src\System\Xml\XmlDownloadManager.cs(26,0): at System.Xml.XmlDownloadManag
  er.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
           d:\corefx4\src\System.Private.Xml\src\System\Xml\XmlUrlResolver.cs(62,0): at System.Xml.XmlUrlResolver.GetEn
  tity(Uri absoluteUri, String role, Type ofObjectToReturn)
           d:\corefx4\src\System.Private.Xml\src\System\Xml\Core\XmlTextReaderImpl.cs(633,0): at System.Xml.XmlTextRead
  erImpl.FinishInitUriString()
           d:\corefx4\src\System.Private.Xml\src\System\Xml\Core\XmlTextReaderImpl.cs(611,0): at System.Xml.XmlTextRead
  erImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
           d:\corefx4\src\System.Private.Xml\src\System\Xml\Core\XmlReaderSettings.cs(422,0): at System.Xml.XmlReaderSe
  ttings.CreateReader(String inputUri, XmlParserContext inputContext)
           d:\corefx4\src\System.Private.Xml\src\System\Xml\Core\XmlReader.cs(1771,0): at System.Xml.XmlReader.Create(S
  tring inputUri, XmlReaderSettings settings, XmlParserContext inputContext)
           d:\corefx4\src\System.Private.Xml\src\System\Xml\Core\XmlReader.cs(1761,0): at System.Xml.XmlReader.Create(S
  tring inputUri, XmlReaderSettings settings)
           d:\corefx4\src\System.Private.Xml\src\System\Xml\Schema\XmlSchemaSet.cs(333,0): at System.Xml.Schema.XmlSche
  maSet.Add(String targetNamespace, String schemaUri)
           d:\corefx4\src\System.Private.Xml\tests\XmlSchema\XmlSchemaSet\TC_SchemaSet_Add_URL.cs(377,0): at System.Xml
  .Tests.TC_SchemaSet_Add_URL.verifyXsd(String file)
           d:\corefx4\src\System.Private.Xml\tests\XmlSchema\XmlSchemaSet\TC_SchemaSet_Add_URL.cs(395,0): at System.Xml
  .Tests.TC_SchemaSet_Add_URL.bug298991Sequence(Int32 size, String xsdFileName)
     System.Xml.Tests.TC_SchemaSet_Add_URL.bug298991Choice(size: 5000, xsdFileName: \"5000c.xsd\") [FAIL]
        System.IO.FileNotFoundException : Could not find file 'd:\corefx4\bin\Windows_NT.AnyCPU.Debug\System.Xml.XmlSch
  emaSet.Tests\netcoreapp\5000c.xsd'.
        Stack Trace:
              at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
              at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 buffe
  rSize, FileOptions options)
              at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 buffe
  rSize)
           d:\corefx4\src\System.Private.Xml\src\System\Xml\XmlDownloadManager.cs(26,0): at System.Xml.XmlDownloadManag
  er.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
           d:\corefx4\src\System.Private.Xml\src\System\Xml\XmlUrlResolver.cs(62,0): at System.Xml.XmlUrlResolver.GetEn
  tity(Uri absoluteUri, String role, Type ofObjectToReturn)
           d:\corefx4\src\System.Private.Xml\src\System\Xml\Core\XmlTextReaderImpl.cs(633,0): at System.Xml.XmlTextRead
  erImpl.FinishInitUriString()
           d:\corefx4\src\System.Private.Xml\src\System\Xml\Core\XmlTextReaderImpl.cs(611,0): at System.Xml.XmlTextRead
  erImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
           d:\corefx4\src\System.Private.Xml\src\System\Xml\Core\XmlReaderSettings.cs(422,0): at System.Xml.XmlReaderSe
  ttings.CreateReader(String inputUri, XmlParserContext inputContext)
           d:\corefx4\src\System.Private.Xml\src\System\Xml\Core\XmlReader.cs(1771,0): at System.Xml.XmlReader.Create(S
  tring inputUri, XmlReaderSettings settings, XmlParserContext inputContext)
           d:\corefx4\src\System.Private.Xml\src\System\Xml\Core\XmlReader.cs(1761,0): at System.Xml.XmlReader.Create(S
  tring inputUri, XmlReaderSettings settings)
           d:\corefx4\src\System.Private.Xml\src\System\Xml\Schema\XmlSchemaSet.cs(333,0): at System.Xml.Schema.XmlSche
  maSet.Add(String targetNamespace, String schemaUri)
           d:\corefx4\src\System.Private.Xml\tests\XmlSchema\XmlSchemaSet\TC_SchemaSet_Add_URL.cs(377,0): at System.Xml
  .Tests.TC_SchemaSet_Add_URL.verifyXsd(String file)
  Finished:    System.Xml.XmlSchemaSet.Tests
           d:\corefx4\src\System.Private.Xml\tests\XmlSchema\XmlSchemaSet\TC_SchemaSet_Add_URL.cs(408,0): at System.Xml
  .Tests.TC_SchemaSet_Add_URL.bug298991Choice(Int32 size, String xsdFileName)
```

</details>

cc: @sepidehMS

**Comment by danmosemsft** [comment]
#21424
