### ISSUE TITLE
AttributeError: DumplingConfig instance has no attribute 'dbgpath'

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#21520]
https://mc.dot.net/#/user/hughbe/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/a808e4f4bb61ed8002200c969d132a54769b2328/workItem/System.Runtime.InteropServices.Tests/wilogs
```

2017-06-25 06:28:18,063: INFO: proc(54): run_and_log_output: Output: /home/helixbot/dotnetbuild/work/dd100005-e671-46fb-892b-4e743335ba82/Work/10f58f6f-862f-44af-9628-ca1652b6bf2e/Unzip/RunTests.sh: line 87:  2365 Segmentation fault      (core dumped) $RUNTIME_PATH/dotnet xunit.console.netcore.exe System.Runtime.InteropServices.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests -notrait category=OuterLoop -notrait category=failing
2017-06-25 06:28:47,204: INFO: proc(54): run_and_log_output: Output: processing dump file /home/helixbot/dotnetbuild/work/dd100005-e671-46fb-892b-4e743335ba82/Work/10f58f6f-862f-44af-9628-ca1652b6bf2e/Unzip/core
2017-06-25 06:28:47,204: INFO: proc(54): run_and_log_output: Output: creating dumpling dump cf4c07f3f46a55e83f477e7c7164bcf510fa4343
2017-06-25 06:28:47,204: INFO: proc(54): run_and_log_output: Output: uploading artifact cf4c07f3f46a55e83f477e7c7164bcf510fa4343 core
2017-06-25 06:28:47,204: INFO: proc(54): run_and_log_output: Output: Traceback (most recent call last):
2017-06-25 06:28:47,204: INFO: proc(54): run_and_log_output: Output:   File "/home/helixbot/.dumpling/dumpling.py", line 1128, in <module>
2017-06-25 06:28:47,205: INFO: proc(54): run_and_log_output: Output:     main(sys.argv)
2017-06-25 06:28:47,205: INFO: proc(54): run_and_log_output: Output:   File "/home/helixbot/.dumpling/dumpling.py", line 1123, in main
2017-06-25 06:28:47,205: INFO: proc(54): run_and_log_output: Output:     cmdProc.Process(config)
2017-06-25 06:28:47,205: INFO: proc(54): run_and_log_output: Output:   File "/home/helixbot/.dumpling/dumpling.py", line 529, in Process
2017-06-25 06:28:47,205: INFO: proc(54): run_and_log_output: Output:     self.Upload(config)
2017-06-25 06:28:47,206: INFO: proc(54): run_and_log_output: Output:   File "/home/helixbot/.dumpling/dumpling.py", line 624, in Upload
2017-06-25 06:28:47,206: INFO: proc(54): run_and_log_output: Output:     self.UploadDump(config)
2017-06-25 06:28:47,206: INFO: proc(54): run_and_log_output: Output:   File "/home/helixbot/.dumpling/dumpling.py", line 644, in UploadDump
2017-06-25 06:28:47,206: INFO: proc(54): run_and_log_output: Output:     self._triage_dump(dumpid, config.dumppath, config)
2017-06-25 06:28:47,206: INFO: proc(54): run_and_log_output: Output:   File "/home/helixbot/.dumpling/dumpling.py", line 812, in _triage_dump
2017-06-25 06:28:47,206: INFO: proc(54): run_and_log_output: Output:     if config.dbgpath is None:
2017-06-25 06:28:47,207: INFO: proc(54): run_and_log_output: Output: AttributeError: DumplingConfig instance has no attribute 'dbgpath'
2017-06-25 06:28:47,219: INFO: proc(54): run_and_log_output: Output: Trying to find crash dumps for project: System.Runtime.InteropServices.Tests
2017-06-25 06:28:47,219: INFO: proc(54): run_and_log_output: Output: Uploading dump file: /home/helixbot/dotnetbuild/work/dd100005-e671-46fb-892b-4e743335ba82/Work/10f58f6f-862f-44af-9628-ca1652b6bf2e/Unzip/core
2017-06-25 06:28:47,224: INFO: proc(54): run_and_log_output: Output: ~/dotnetbuild/work/dd100005-e671-46fb-892b-4e743335ba82/Work/10f58f6f-862f-44af-9628-ca1652b6bf2e/Unzip
```

@mellinoe

**Comment by mellinoe** [comment]
@danmosemsft Is this different from https://github.com/dotnet/corefx/issues/21225?

**Comment by danmosemsft** [comment]
Oops, no it's not.
