### ISSUE TITLE
.net 4.6.2  signedXml.CheckSignature(); problem with rsa2

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#21539]
_From @zchpit on June 21, 2017 12:24_

After upgrade to .net 4.6.2 I have problem with signedXml.CheckSignature(); with RSA2

For signing I use
CryptoConfig.AddAlgorithm(typeof(RSAPKCS1SHA256SignatureDescription), "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256");

It works on my machine but don't work on test serwer. Error:

System.Security.Cryptography.CryptographicException SignatureDescription could not be created for the signature algorithm supplied.
at System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm key)
at System.Security.Cryptography.Xml.SignedXml.CheckSignature(AsymmetricAlgorithm key)
at System.Security.Cryptography.Xml.SignedXml.CheckSignatureReturningKey(AsymmetricAlgorithm& signingKey)
at ePR.Biz.Security.Signature.Veryfier.EprDsigSimpleVerifier.VerifyXml(XmlDocument doc, X509Certificate2& cert)
at ePR.Biz.Security.Signature.Veryfier.EprDsigSimpleVerifier.Verify(FileContentInfo fci, X509Certificate2& cert, String& stringSignature)
at ePR.Biz.Security.Signature.SignatureManager.ValidateSignatureCore(ISignatureVeryfier veryfier, FileContentInfo fci)
at ePR.Biz.Security.Signature.SignatureManager.ValidateSignature(XmlDocument doc)

P.S. In my comuper I work as administator and run as Console App., in test serwer there is custom profile created and run as a Windows Service

_Copied from original issue: Microsoft/dotnet#430_

**Comment by karelz** [comment]
_From @zchpit on June 21, 2017 12:25_

Before 4.6.2 it was working in .net 4.5
Now I have 4.6.2 on my machine and .net 4.6.2 on serwer and on serwer I get exception.

**Comment by karelz** [comment]
_From @richlander on June 26, 2017 0:19_

@karelz who should look at this?

/cc @preetikr

**Comment by karelz** [comment]
@bartonjs @ianhays do we have similar problem in .NET Core?
If not, we should route it to proper .NET Framework channel.

**Comment by ianhays** [comment]
@zchpit were you able to look into Jeremy's investigation?
