### ISSUE TITLE
Test failure: System.Tests.StringTests/IndexOf_TurkishI on UAP

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#21541]
Opened on behalf of @danmosemsft
```
The test `System.Tests.StringTests/IndexOf_TurkishI` has failed.

RemoteExecuter: System.Runtime.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb <IndexOf_TurkishI>b__45_0 \r
    System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.EqualException: Assert.Equal() Failure\r
    Expected: 19\r
    Actual:   4\r
       at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)\r
       at System.Tests.StringTests.<>c.<IndexOf_TurkishI>b__45_0()\r
       --- End of inner exception stack trace ---\r
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\r
       at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\r
       at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)\r
       at RunnerRemoteExecutionService.RemoteExecutor.HandleTheRequest(ValueSet message, ValueSet returnData)\r
    Returned Error code: -4\r
    Expected: True\r
    Actual:   False

        Stack Trace:

           at System.Diagnostics.RemoteExecutorTestBase.RemoteInvoke(MethodInfo method, String[] args, RemoteInvokeOptions options)
       at System.Diagnostics.RemoteExecutorTestBase.RemoteInvoke(Func`1 method, RemoteInvokeOptions options)
       at System.Tests.StringTests.IndexOf_TurkishI()
Build : Master - 20170626.01 (UWP F5 Tests)
Failing configurations:
- Windows.10.Amd64.ClientRS3-x64
  - Debug
```

**Comment by danmosemsft** [comment]
@tarekgh @sepidehMS it seems this did have @sepidehMS change https://github.com/dotnet/corefx/pull/21471

I know that in the UAP case, the remote invoke is not a process start. Does it have its own distinct server process though? If not it could still have the problem of "leaking" the culture setting. 

I can't repro this locally which is what makes me wonder.

**Comment by danmosemsft** [comment]
Another culture one

**Comment by krwq** [comment]
got local repro after running in a loop for a while, investigating
