### ISSUE TITLE
[porting] PrivateFontCollection has different argument validation in netfx and netcoreapp

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#21558]
```cs
[ConditionalFact(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotWindowsNanoServer))]
public void AddFontFile_NullFileName_ThrowsArgumentNullException()
{
    using (var fontCollection = new PrivateFontCollection())
    {
        AssertExtensions.Throws<ArgumentNullException>("path", () => fontCollection.AddFontFile(null));
    }
}

[ConditionalFact(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotWindowsNanoServer))]
public void AddFontFile_InvalidPath_ThrowsArgumentException()
{
    using (var fontCollection = new PrivateFontCollection())
    {
        AssertExtensions.Throws<ArgumentException>(null, () => fontCollection.AddFontFile(string.Empty));
    }
}

[ConditionalFact(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotWindowsNanoServer))]
public void AddFontFile_NoSuchFilePath_ThrowsArgumentException()
{
    using (var fontCollection = new PrivateFontCollection())
    {
        Assert.Throws<FileNotFoundException>(() => fontCollection.AddFontFile("fileName"));
    }
}

[ConditionalFact(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotWindowsNanoServer))]
public void AddFontFile_LongFilePath_ThrowsPathTooLongException()
{
    using (var fontCollection = new PrivateFontCollection())
    {
        Assert.Throws<PathTooLongException>(() => fontCollection.AddFontFile(new string('a', 261)));
    }
}
```

These tests pass with netfx. On .NET core, they fail with:
```
  Discovering: System.Drawing.Common.Tests
  Discovered:  System.Drawing.Common.Tests
  Starting:    System.Drawing.Common.Tests
     System.Drawing.Tests.BrushTests.Dispose_NoSuchEntryPoint_SilentyCatchesException [SKIP]
        Condition(s) not met: \"IsWindowsNanoServer\"
     System.Drawing.Text.Tests.PrivateFontCollectionTests.AddFontFile_InvalidPath_ThrowsArgumentException [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentException)
        Actual:   typeof(System.IO.FileNotFoundException): File not found.
        Stack Trace:
              at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
              at System.Drawing.Text.PrivateFontCollection.AddFontFile(String filename)
              at System.Drawing.Text.Tests.PrivateFontCollectionTests.<>c__DisplayClass3_0.<AddFontFile_InvalidPath_Thr
  owsArgumentException>b__0()
     System.Drawing.Text.Tests.PrivateFontCollectionTests.AddFontFile_LongFilePath_ThrowsPathTooLongException [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.IO.PathTooLongException)
        Actual:   typeof(System.IO.FileNotFoundException): File not found.
        Stack Trace:
              at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
              at System.Drawing.Text.PrivateFontCollection.AddFontFile(String filename)
              at System.Drawing.Text.Tests.PrivateFontCollectionTests.<>c__DisplayClass5_0.<AddFontFile_LongFilePath_Th
  rowsPathTooLongException>b__0()
     System.Drawing.Text.Tests.PrivateFontCollectionTests.AddFontFile_NullFileName_ThrowsArgumentNullException [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentNullException)
        Actual:   typeof(System.ArgumentException): Parameter is not valid.
        Stack Trace:
              at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
              at System.Drawing.Text.PrivateFontCollection.AddFontFile(String filename)
              at System.Drawing.Text.Tests.PrivateFontCollectionTests.<>c__DisplayClass2_0.<AddFontFile_NullFileName_Th
  rowsArgumentNullException>b__0()
     System.Drawing.Printing.Tests.PageSettingsTests.Clone_Success [SKIP]
        Condition(s) not met: \"AnyInstalledPrinters\"
  Finished:    System.Drawing.Common.Tests
```

**Comment by hughbe** [comment]
I'll grab the fix when #21552 is merged
