### ISSUE TITLE
[UWP6.0] Rect and Size in System.Runtime.WindowsRuntime has different exception thrown for size validation

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#21704]
As suggested in #21658 - disabling tests against this issue.

```
Windows.Foundation.Tests.SizeTests.Ctor_NegativeHeight_ThrowsArgumentOutOfRangeException(height: -1) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   typeof(System.ArgumentException): Value does not fall within the expected range.
        Stack Trace:
           D:\repos\corefxCopy\corefx\src\System.Runtime.WindowsRuntime\tests\Windows\Foundation\SizeTests.cs(51,0): at Windows.Foundation.Tests.SizeTests.<>c__DisplayClass3_0.<Ctor_NegativeHeight_ThrowsArgumentOutOfRangeException>b__0()
     Windows.Foundation.Tests.SizeTests.Ctor_NegativeHeight_ThrowsArgumentOutOfRangeException(height: -ì) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   typeof(System.ArgumentException): Value does not fall within the expected range.
        Stack Trace:
           D:\repos\corefxCopy\corefx\src\System.Runtime.WindowsRuntime\tests\Windows\Foundation\SizeTests.cs(51,0): at Windows.Foundation.Tests.SizeTests.<>c__DisplayClass3_0.<Ctor_NegativeHeight_ThrowsArgumentOutOfRangeException>b__0()
     Windows.Foundation.Tests.SizeTests.Height_SetNegative_ThrowsArgumentOutOfRangeException(height: -1) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   typeof(System.ArgumentException): Value does not fall within the expected range.
        Stack Trace:
           D:\repos\corefxCopy\corefx\src\System.Runtime.WindowsRuntime\tests\Windows\Foundation\SizeTests.cs(91,0): at Windows.Foundation.Tests.SizeTests.<>c__DisplayClass7_0.<Height_SetNegative_ThrowsArgumentOutOfRangeException>b__0()
     Windows.Foundation.Tests.SizeTests.Height_SetNegative_ThrowsArgumentOutOfRangeException(height: -ì) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   typeof(System.ArgumentException): Value does not fall within the expected range.
        Stack Trace:
           D:\repos\corefxCopy\corefx\src\System.Runtime.WindowsRuntime\tests\Windows\Foundation\SizeTests.cs(91,0): at Windows.Foundation.Tests.SizeTests.<>c__DisplayClass7_0.<Height_SetNegative_ThrowsArgumentOutOfRangeException>b__0()
     Windows.Foundation.Tests.SizeTests.Ctor_NegativeWidth_ThrowsArgumentOutOfRangeException(width: -1) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   typeof(System.ArgumentException): Value does not fall within the expected range.
        Stack Trace:
           D:\repos\corefxCopy\corefx\src\System.Runtime.WindowsRuntime\tests\Windows\Foundation\SizeTests.cs(43,0): at Windows.Foundation.Tests.SizeTests.<>c__DisplayClass2_0.<Ctor_NegativeWidth_ThrowsArgumentOutOfRangeException>b__0()
     Windows.Foundation.Tests.SizeTests.Ctor_NegativeWidth_ThrowsArgumentOutOfRangeException(width: -ì) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   typeof(System.ArgumentException): Value does not fall within the expected range.
        Stack Trace:
           D:\repos\corefxCopy\corefx\src\System.Runtime.WindowsRuntime\tests\Windows\Foundation\SizeTests.cs(43,0): at Windows.Foundation.Tests.SizeTests.<>c__DisplayClass2_0.<Ctor_NegativeWidth_ThrowsArgumentOutOfRangeException>b__0()
     Windows.Foundation.Tests.SizeTests.Width_SetNegative_ThrowsArgumentOutOfRangeException(width: -1) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   typeof(System.ArgumentException): Value does not fall within the expected range.
        Stack Trace:
           D:\repos\corefxCopy\corefx\src\System.Runtime.WindowsRuntime\tests\Windows\Foundation\SizeTests.cs(71,0): at Windows.Foundation.Tests.SizeTests.<>c__DisplayClass5_0.<Width_SetNegative_ThrowsArgumentOutOfRangeException>b__0()
     Windows.Foundation.Tests.SizeTests.Width_SetNegative_ThrowsArgumentOutOfRangeException(width: -ì) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   typeof(System.ArgumentException): Value does not fall within the expected range.
        Stack Trace:
           D:\repos\corefxCopy\corefx\src\System.Runtime.WindowsRuntime\tests\Windows\Foundation\SizeTests.cs(71,0): at Windows.Foundation.Tests.SizeTests.<>c__DisplayClass5_0.<Width_SetNegative_ThrowsArgumentOutOfRangeException>b__0()
     Windows.Foundation.Tests.RectTests.Ctor_NegativeHeight_ThrowsArgumentOutOfRangeException(height: -1) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   typeof(System.ArgumentException): Value does not fall within the expected range.
        Stack Trace:
           D:\repos\corefxCopy\corefx\src\System.Runtime.WindowsRuntime\tests\Windows\Foundation\RectTests.cs(66,0): at Windows.Foundation.Tests.RectTests.<>c__DisplayClass3_0.<Ctor_NegativeHeight_ThrowsArgumentOutOfRangeException>b__0()
     Windows.Foundation.Tests.RectTests.Ctor_NegativeHeight_ThrowsArgumentOutOfRangeException(height: -ì) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   typeof(System.ArgumentException): Value does not fall within the expected range.
        Stack Trace:
           D:\repos\corefxCopy\corefx\src\System.Runtime.WindowsRuntime\tests\Windows\Foundation\RectTests.cs(66,0): at Windows.Foundation.Tests.RectTests.<>c__DisplayClass3_0.<Ctor_NegativeHeight_ThrowsArgumentOutOfRangeException>b__0()
     Windows.Foundation.Tests.RectTests.Height_SetNegative_ThrowsArgumentOutOfRangeException(height: -1) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   typeof(System.ArgumentException): Value does not fall within the expected range.
        Stack Trace:
           D:\repos\corefxCopy\corefx\src\System.Runtime.WindowsRuntime\tests\Windows\Foundation\RectTests.cs(188,0): at Windows.Foundation.Tests.RectTests.<>c__DisplayClass16_0.<Height_SetNegative_ThrowsArgumentOutOfRangeException>b__0()
     Windows.Foundation.Tests.RectTests.Height_SetNegative_ThrowsArgumentOutOfRangeException(height: -ì) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   typeof(System.ArgumentException): Value does not fall within the expected range.
        Stack Trace:
           D:\repos\corefxCopy\corefx\src\System.Runtime.WindowsRuntime\tests\Windows\Foundation\RectTests.cs(188,0): at Windows.Foundation.Tests.RectTests.<>c__DisplayClass16_0.<Height_SetNegative_ThrowsArgumentOutOfRangeException>b__0()
     Windows.Foundation.Tests.RectTests.Ctor_NegativeWidth_ThrowsArgumentOutOfRangeException(width: -1) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   typeof(System.ArgumentException): Value does not fall within the expected range.
        Stack Trace:
           D:\repos\corefxCopy\corefx\src\System.Runtime.WindowsRuntime\tests\Windows\Foundation\RectTests.cs(58,0): at Windows.Foundation.Tests.RectTests.<>c__DisplayClass2_0.<Ctor_NegativeWidth_ThrowsArgumentOutOfRangeException>b__0()
     Windows.Foundation.Tests.RectTests.Ctor_NegativeWidth_ThrowsArgumentOutOfRangeException(width: -ì) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   typeof(System.ArgumentException): Value does not fall within the expected range.
        Stack Trace:
           D:\repos\corefxCopy\corefx\src\System.Runtime.WindowsRuntime\tests\Windows\Foundation\RectTests.cs(58,0): at Windows.Foundation.Tests.RectTests.<>c__DisplayClass2_0.<Ctor_NegativeWidth_ThrowsArgumentOutOfRangeException>b__0()
     Windows.Foundation.Tests.RectTests.Width_SetNegative_ThrowsArgumentOutOfRangeException(width: -1) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   typeof(System.ArgumentException): Value does not fall within the expected range.
        Stack Trace:
           D:\repos\corefxCopy\corefx\src\System.Runtime.WindowsRuntime\tests\Windows\Foundation\RectTests.cs(171,0): at Windows.Foundation.Tests.RectTests.<>c__DisplayClass14_0.<Width_SetNegative_ThrowsArgumentOutOfRangeException>b__0()
     Windows.Foundation.Tests.RectTests.Width_SetNegative_ThrowsArgumentOutOfRangeException(width: -ì) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   typeof(System.ArgumentException): Value does not fall within the expected range.
        Stack Trace:
           D:\repos\corefxCopy\corefx\src\System.Runtime.WindowsRuntime\tests\Windows\Foundation\RectTests.cs(171,0): at Windows.Foundation.Tests.RectTests.<>c__DisplayClass14_0.<Width_SetNegative_ThrowsArgumentOutOfRangeException>b__0()
``

**Comment by ViktorHofer** [comment]
As this is UWP specific I moved it to UWP6.1 and will check if this is still accurate locally.
