### ISSUE TITLE
Test failed: System.Net.Sockets.Tests.TcpListenerTest / Accept_AcceptsPendingSocketOrClient

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#21702]
failed test: System.Net.Sockets.Tests.TcpListenerTest.Accept_AcceptsPendingSocketOrClient 

detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu16.04_release/92/testReport/System.Net.Sockets.Tests/TcpListenerTest/Accept_AcceptsPendingSocketOrClient/

MESSAGE:
~~~
Assert.False() Failure
Expected: False
Actual: True
~~~
STACK TRACE:
~~~
at System.Net.Sockets.Tests.TcpListenerTest.<Accept_AcceptsPendingSocketOrClient>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

**Comment by stephentoub** [comment]
Failed again here:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/13ac05a21616a4973d21f57ab51902e47fa118fc/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.TcpListenerTest~2FAccept_AcceptsPendingSocketOrClient

```
Ubuntu.1604.Amd64.Open-Release-x64
Unhandled Exception of Type Xunit.Sdk.FalseException
Message :
Assert.False() Failure
Expected: False
Actual:   True
Stack Trace :
   at System.Net.Sockets.Tests.TcpListenerTest.<Accept_AcceptsPendingSocketOrClient>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /root/coreclr/src/mscorlib/src/System/Runtime/ExceptionServices/ExceptionServicesCommon.cs:line 130
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 152
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /root/coreclr/src/mscorlib/src/System/Runtime/ExceptionServices/ExceptionServicesCommon.cs:line 130
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 152
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /root/coreclr/src/mscorlib/src/System/Runtime/ExceptionServices/ExceptionServicesCommon.cs:line 130
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 152
```

**Comment by wfurt** [comment]
I did not find any failures in Helix database. It seems like both failures did come from Ubuntu 16.04
It did failed once for me on Ubuntu 14 in run on my local machine.

**Comment by karelz** [comment]
Only 3 known failures in half year, moving to Future.

**Comment by wfurt** [comment]
No failure in last 180 days. closing for now.
