### ISSUE TITLE
SslStream bug on Linux/OSX: Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error

### ISSUE THREAD

**Issue by nopara73** [dotnet/corefx#21761]
**`dotnet --version` output:** 1.0.1  
  
The bug is present on Ubuntu, but not on Windows 7. I suspect it is an **issue on both Linux and OSX, but not an issue on Windows**, because it doesn't use OpenSSL.  
  
I created a project where **I reproduce the issue**, you can find it here: https://github.com/nopara73/SslStreamBug/  
It only consists of a `Program.cs` file.  
  
The **place** where the exceptions are thrown is at `AuthenticateAsClientAsync`:
  
```
Console.WriteLine("Ssl authenticating as client...");
using (var stream = new NetworkStream(socket, ownsSocket: false))
using (SslStream httpsStream = new SslStream(stream, leaveInnerStreamOpen: true))
{ 
	httpsStream
		.AuthenticateAsClientAsync(
			uri.DnsSafeHost,
			new X509CertificateCollection(),
			SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12,
			checkCertificateRevocation: true)
			.Wait();
}
```

**And the exception:**
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (A call to SSPI failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, Boolean isServer, Boolean remoteCertRequired)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at SslStreamBug.Program.Main(String[] args) in /home/user/SslStreamBug/SslStreamBug/Program.cs:line 56
```

**Might be related:**  
https://github.com/dotnet/corefx/issues/10858  
https://stackoverflow.com/questions/38960081/asp-net-core-linux-ssl-ssl-read-bio-failed-with-openssl-error

**Comment by nopara73** [comment]
I tested it with **`dotnet --version` output:** 2.0.0-preview2-006497  
  
The exact same behavior is experienced, except that it has slightly differen, insignificant stack trace:  
Instead of  `ReadFrameCallback˙ it has `StartReadFrame` and `PartialFrameCallback` as you can see below:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (A call to SSPI failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, Boolean isServer, Boolean remoteCertRequired)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at SslStreamBug.Program.Main(String[] args) in /home/user/dotnet2/SslStreamBug/Program.cs:line 56
```

**Comment by nopara73** [comment]
Pinging @bartonjs , since you fixed a similar issue before: https://github.com/dotnet/corefx/pull/13095

**Comment by nopara73** [comment]
There is a trick that selectively bypasses the issue.  
If you add `userCertificateValidationCallback` to the `SslStream` the exception is not thrown, depending on the host.  
  
Normally one would do this, where the issue is always present on Linux and OSX:
```
var httpsStream = new SslStream(stream, leaveInnerStreamOpen: true);
```  
But if one does this:
```
var httpsStream = new SslStream(
						stream,
						leaveInnerStreamOpen: true,
						userCertificateValidationCallback: (a, b, c, d) => true);
```
Then the issue is bypassed depending on the host, which of course leaves a security hole.  
  
An example of successful issue bypassing: https://api.qbit.ninja/  
An example of unsuccessful issue bypassing: https://httpbin.org/

**Comment by karelz** [comment]
@Priya91 @geoffkizer can you please take a look?
cc @Drawaes

**Comment by Drawaes** [comment]
Suspect it's a bug in the version of OpenSSL provided by your platform.... occurs in the version check and isn't an issue directly related to .net. can you try changing the version to one of the ones mentioned below and see if the issue disappears?

https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/861137

**Comment by nopara73** [comment]
@Drawaes I am failing to build any openssl version under `1.0.0`.  
In the link OP says the error happens at `1.0.0e` version and they say the error doesn't happen for example in `0.9.8k`, which I am unable to test.  
I tested with `1.0.2g` and `1.1.0f`, the same error comes up.  
  
However I noticed something else. There might be multiple issue here. As I said I can bypass the issue at `https://api.qbit.ninja/`, but I cannot bypass the issue at `https://httpbin.org/`.  
  
Now I noticed the issue is not the same at the two sites, the stack trace is slightly different. The above stack traces  I inserted were for `https://httpbin.org/`. However the stack trace for `https://api.qbit.ninja/` is:
  
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (The remote certificate is invalid according to the validation procedure.) ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at SslStreamBug.Program.Main(String[] args) in /home/user/SslStreamBug/SslStreamBug/Program.cs:line 58
```
(Before you ask, yes I just made sure that both sites works flawlessly in Windows.)

**Comment by nopara73** [comment]
cc @NicolasDorier

**Comment by Drawaes** [comment]
My Ubuntu machines are being rebuilt by my admin (read wife) but if I get them going today I will try to reproduce, the fact it happens on multiple versions is interesting. I am also interested that 1.1.0 even works for anything considering the number of breaking changes.

**Comment by Drawaes** [comment]
@nopara73 I just ran the qbit.nija using openssl's client with
openssl s_client -connect api.qbit.ninja:443 -debug -msg

I get the following chain
```
Certificate chain
 0 s:/CN=*.azurewebsites.net
   i:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2  1 s:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
   i:/C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
```

Then the following problem with the issuer
Verification error: unable to get local issuer certificate

Now it could be because my openssl is a bit stuffed because I have been hacking about today, but it might be that the default Root CA's are missing that one, can you check the above command? If it works straight through then it's most likely a bug in .net

**Comment by NicolasDorier** [comment]
@Drawaes it is using SNI (if you browse to https://api.qbit.ninja/ you can see a different certificate) I think openssl s_client do not support it.

**Comment by Drawaes** [comment]
Problem solved then. SslStream doesn't support SNI.... it is an outstanding requested feature.

**Comment by Priya91** [comment]
We have the SNI feature tracked in #9608. Closing this as dupe.

**Comment by nopara73** [comment]
@Priya91 @Drawaes As I figured in my previous comment there are two issues here. While the SNI feature would solve the qbitninja issue, would it also solve the httpbin issue, too?
