### ISSUE TITLE
Unix_NonExistentPath_ReadOnlyVolume failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#21857]
Failed on Debian 8.7 CI machine:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/be0145cb201f0154f7d5b2f878f9e495bdd29a83/workItem/System.IO.FileSystem.Tests/analysis/xunit/System.IO.Tests.FileInfo_Delete~2FUnix_NonExistentPath_ReadOnlyVolume
```
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Assert.True() Failure\nExpected: True\nActual:   False
Stack Trace :
   at System.IO.Tests.FileSystemTest.RunAsSudo(String commandLine) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/System.IO.FileSystem/tests/FileSystemTest.cs:line 70
   at System.IO.Tests.FileSystemTest.ReadOnly_FileSystemHelper(Action`1 testAction, String subDirectoryName) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/System.IO.FileSystem/tests/FileSystemTest.cs:line 102
```

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/21823

@MaggieTsang

**Comment by stephentoub** [comment]
Seems to be failing fairly consistently on Debian, e.g.
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/d5a56dea4a20a3e1bdecc38b01e9ac4993a4563f/workItem/System.IO.FileSystem.Tests/analysis/xunit/System.IO.Tests.FileInfo_Delete~2FUnix_ExistingDirectory_ReadOnlyVolume

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/corefx/issues/21823

**Comment by Jiayili1** [comment]
This issue is repro on Core Tests (2.0.0), detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170718.01/workItem/System.IO.FileSystem.Tests/analysis/xunit/System.IO.Tests.File_Delete~2FUnix_NonExistentPath_ReadOnlyVolume

**Comment by Jiayili1** [comment]
This issue is repro in 2.0.0 branch, detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170927.01/workItem/System.IO.FileSystem.Tests/analysis/xunit/System.IO.Tests.FileInfo_Delete~2FUnix_ExistingDirectory_ReadOnlyVolume

The test `System.IO.Tests.FileInfo_Delete/Unix_ExistingDirectory_ReadOnlyVolume` has failed.

Assert.True() Failure
    Expected: True
    Actual:   False

        Stack Trace:

           at System.IO.Tests.FileSystemTest.RunAsSudo(String commandLine) in /root/corefx/src/System.IO.FileSystem/tests/FileSystemTest.cs:line 72
       at System.IO.Tests.FileSystemTest.ReadOnly_FileSystemHelper(Action`1 testAction, String subDirectoryName) in /root/corefx/src/System.IO.FileSystem/tests/FileSystemTest.cs:line 100
Build : 2.0.0 - 20170927.01 (Core Tests)
Failing configurations:
- RedHat.69.Amd64-x64
  - Release
  - Debug

**Comment by Sunny-pu** [comment]
This issue is repro in 2.0.0 branch, detail:
https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20171011.01/workItem/System.IO.FileSystem.Tests/analysis/xunit/System.IO.Tests.FileInfo_Delete~2FUnix_NonExistentPath_ReadOnlyVolume

**Comment by Sunny-pu** [comment]
This issue is repro in 2.0.0 branch, detail:
https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20171108.02/workItem/System.IO.FileSystem.Tests/analysis/xunit/System.IO.Tests.FileInfo_Delete~2FUnix_ExistingDirectory_ReadOnlyVolume

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/21920

**Comment by JeremyKuhne** [comment]
Push comes to shove we can move this out of 2.1.

**Comment by danmosemsft** [comment]
@Anipik can you please disable this test for Alpine, using this issue #, since if we're not fixing it right now it should be disabled.

**Comment by Anipik** [comment]
@danmosemsft its been done a long time ago https://github.com/dotnet/corefx/pull/28401

**Comment by Anipik** [comment]
Done !
