### ISSUE TITLE
System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected failed

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#21854]
Detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170704.01/workItem/System.Net.Mail.Functional.Tests/wilogs

Configuration: 
OSX.1012.Amd64-x64

~~~
2017-07-03 17:51:35,990: INFO: proc(54): run_and_log_output: Output: Discovering: System.Net.Mail.Functional.Tests
2017-07-03 17:51:36,121: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Net.Mail.Functional.Tests
2017-07-03 17:51:36,184: INFO: proc(54): run_and_log_output: Output: Starting:    System.Net.Mail.Functional.Tests
2017-07-03 17:52:36,718: INFO: proc(54): run_and_log_output: Output:    System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected [FAIL]
2017-07-03 17:52:36,719: INFO: proc(54): run_and_log_output: Output:       Timed out after 60000ms waiting for remote process 19702
2017-07-03 17:52:36,719: INFO: proc(54): run_and_log_output: Output:       Expected: True
2017-07-03 17:52:36,719: INFO: proc(54): run_and_log_output: Output:       Actual:   False
2017-07-03 17:52:36,722: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-07-03 17:52:36,813: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/28/s/corefx/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs(208,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
~~~

**Comment by karelz** [comment]
One occurrence only, moving to 2.1

**Comment by Jiayili1** [comment]
This issue is repro in Master branch, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170821.01/workItem/System.Net.Mail.Functional.Tests/wilogs

~~~
2017-08-20 19:32:26,195: INFO: proc(54): run_and_log_output: Output:       Timed out after 60000ms waiting for remote process 22714
2017-08-20 19:32:26,195: INFO: proc(54): run_and_log_output: Output:       Expected: True
2017-08-20 19:32:26,195: INFO: proc(54): run_and_log_output: Output:       Actual:   False
2017-08-20 19:32:26,198: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-08-20 19:32:26,284: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/30/s/corefx/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs(161,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
~~~

**Comment by karelz** [comment]
Only one occurrence in Helix official runs history since 2017/5 -- on 8/21 - build 20170821.03

Closing.
Please reopen if it happens again.
