### ISSUE TITLE
System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandler_SslProtocols_Test.GetAsync_AllowedSSLVersion_Succeeds failed in CI

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#21917]
failed test: System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandler_SslProtocols_Test.GetAsync_AllowedSSLVersion_Succeeds

detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_opensuse42.1_debug/99/testReport/System.Net.Http.Functional.Tests/ManagedHandler_HttpClientHandler_SslProtocols_Test/GetAsync_AllowedSSLVersion_Succeeds_acceptedProtocol__Tls11__requestOnlyThisProtocol__False_/

MESSAGE:
~~~
System.Net.Http.HttpRequestException : could not establish SSL connection
---- System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
~~~
STACK TRACE:
~~~
at System.Net.Http.HttpConnectionHandler.<EstablishSslConnection>d__9.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnectionHandler.cs:line 89 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/src/System.Threading.Tasks.Extensions/src/System/Runtime/CompilerServices/ConfiguredValueTaskAwaitable.cs:line 61 
at System.Net.Http.HttpConnectionHandler.<CreateConnection>d__10.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnectionHandler.cs:line 105 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/src/System.Threading.Tasks.Extensions/src/System/Runtime/CompilerServices/ConfiguredValueTaskAwaitable.cs:line 61 
at System.Net.Http.HttpConnectionHandler.<SendAsyncWithNewConnection>d__8.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnectionHandler.cs:line 59 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() 
at System.Net.Http.CookieHandler.<SendAsync>d__3.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/src/System.Net.Http/src/System/Net/Http/Managed/CookieHandler.cs:line 31 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() 
at System.Net.Http.AutoRedirectHandler.<SendAsync>d__3.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/src/System.Net.Http/src/System/Net/Http/Managed/AutoRedirectHandler.cs:line 28 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() 
at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 464 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.<>c__DisplayClass4_0.<<GetAsync_AllowedSSLVersion_Succeeds>b__0>d.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.SslProtocols.cs:line 104 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass3_0.<CreateServerAsync>b__0(Task t) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 66 
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) 
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.<GetAsync_AllowedSSLVersion_Succeeds>d__4.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.SslProtocols.cs:line 102 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) ----- Inner Stack Trace ----- 
at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 884 
at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 1102 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 745 
at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 717 
at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 132 
at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Net.Http.HttpConnectionHandler.<EstablishSslConnection>d__9.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnectionHandler.cs:line 79
~~~

**Comment by stephentoub** [comment]
This appears to be due to https://github.com/dotnet/corefx/issues/21991.
