### ISSUE TITLE
XmlSerializer works inconsistently with XmlTextAttribute on derived classes

### ISSUE THREAD

**Issue by poizan42** [dotnet/corefx#21942]
For some reason XmlText only works on string properties on derived classes, while it can properly convert other types if the class is not derived. This seems weird and inconsistent.

```CSharp
using System;
using System.Xml.Serialization;

namespace CoreXmlTextTest
{
  public enum TestEnum { Off, On, Both }

  public class EnumTestUnderived
  {
    [XmlText]
    public TestEnum Test { get; set; }
  }

  public class EnumTestBase { }
  public class EnumTestDerived : EnumTestBase
  {
    [XmlText]
    public TestEnum Test { get; set; }
  }

  public class Program
  {
    public static void Main(string[] args)
    {
      var ser = new XmlSerializer(typeof(EnumTestUnderived));
      var sw = new System.IO.StringWriter();
      ser.Serialize(sw, new EnumTestUnderived() { Test = TestEnum.On });
      Console.WriteLine(sw.ToString());
      try
      {
        new XmlSerializer(typeof(EnumTestDerived));
      }
      catch (Exception e)
      {
        Console.WriteLine(e);
        return;
      }
    }
  }
}
```

The code above outputs: 
```
<?xml version="1.0" encoding="utf-16"?>
<EnumTestUnderived xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">On</EnumTestUnderived>
System.InvalidOperationException: There was an error reflecting type 'CoreXmlTextTest.EnumTestDerived'. ---> System.InvalidOperationException: Cannot serialize object of type 'CoreXmlTextTest.EnumTestDerived'. Consider changing type of XmlText member 'CoreXmlTextTest.EnumTestDerived.Test' from CoreXmlTextTest.TestEnum to string or string array.
   at System.Xml.Serialization.StructMapping.SetContentModel(TextAccessor text, Boolean hasElements)
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(StructModel model, String ns, Boolean openModel, XmlAttributes a, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportElement(TypeModel model, XmlRootAttribute root, String defaultNamespace, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(Type type, XmlRootAttribute root, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type)
   at CoreXmlTextTest.Program.Main(String[] args) in c:\Users\kb\Documents\Visual Studio 2015\Projects\Test\CoreXmlTextTest\Program.cs:line 31

```

Note that the only difference whether it succeeds or not is whether the class derives from Object or from another class.

.net Core version: 2.0.0-preview2-25407-01

NB: This issue is also present in the full .NET Framework.

**Comment by shmao** [comment]
Thanks for submitting the issue, @poizan42 . The issue does seem to be a bug to me. We would consider to make a fix for the issue

Here're two workarounds for the issue,
1. Change the return type of the `Test` property to `string`
2. or move the property into the base class.

**Comment by shmao** [comment]
We decided to not fix the issue in .Net Core for now because there's some simple workarounds for the issue. One of the workarounds is to modify the derived class as shown below,

```c#
    public class EnumTestDerived : EnumTestBase
    {
        private TestEnum _test;

        [XmlText]
        public string TestString
        {
            get
            {
                return _test.ToString();
            }
            set
            {
                _test = (TestEnum)Enum.Parse(typeof(TestEnum), value);
            }
        }

        [XmlIgnore]
        public TestEnum Test
        {
            get
            {
                return _test;
            }
            set
            {
                _test = value;
            }
        }
    }
```

**Comment by poizan42** [comment]
@shmao yes there are simple workarounds, but thats a code smell. Would you accept a PR for this?

**Comment by shmao** [comment]
@poizan42 Yes, we accepts PRs as long as they are good. Please feel free to submit a PR for this. The fix probably can be made at this [line](https://github.com/dotnet/corefx/blob/befefc6d398f8e41184091453162b518f4793953/src/System.Private.Xml/src/System/Xml/Serialization/Mappings.cs#L653). The fix might be simple, but it might cause other regressions. Given that there're simple workarounds for the issue, we thought it'd be better to just leave it as-is and share the workaround here. If we see more hits on the issue, we would definitely consider to fix it.

**Comment by MrGadget1024** [comment]
@shmao This is not something to ignore, as the workaround is nonsense.  Imagine a class library with LOTS of classes, e.g. generated from a massive XSD, that all inherit from a common base class that provides common methods and/or properties that all those classes need to share.  That XmlText decorated property ONLY applies to that one class so we CANNOT just move it to the base class because all other classes that derive from that base class would suddenly get that extra property.  Intellisense would be wrong, and XML serialized from those other classes would include it, and it wouldn't validated against the original XSD.  Changing the data type is no good either, as intellisense would be wrong for data type, leading to developers putting in text values where a certain type is required and the compiler won't catch it but a validation of serialized XML referencing the XSD would fail.  This has been broken for a decade, and should be fixed in 4.x as well as Core.

**Comment by shmao** [comment]
cc: @huanwu @zhenlan

**Comment by MrGadget1024** [comment]
The work around we've been using all these years is to take out the inheritance, declare all of the classes as Partial when they have an XmlText decorated property that isn't a string (e.g. numeric types, dates, etc.), and make umpteen copies of the base class as Partial with the same names as these problem classes.  This is not fun to maintain when generated classes are regenerated, because all these special cases have to be touched again to take out the inheritance.  The compiler points them all out, thankfully, but it's still a time sink.

**Comment by huanwu** [comment]
@MrGadget1024 we will take a look.

**Comment by Lxiamail** [comment]
@MrGadget1024 unfortunately, this fix doesn't meet .NET Framework 4.8 release bar. We won't be able to port it to full framework.

**Comment by MrGadget1024** [comment]
> 
> 
> @MrGadget1024 unfortunately, this fix doesn't meet .NET Framework 4.8 release bar. We won't be able to port it to full framework.

Not soon or not ever?

**Comment by 3bagorion33** [comment]
I have same error
This is my class
```c#
    [XmlRoot]
    public class Coffer : NotifyHashChanged, IParse<Coffer>
    {
        [Browsable(false)]
        public string InternalName { get; set; } = string.Empty;
        [Browsable(false)]
        public string DisplayName { get; set; } = string.Empty;
        [DisplayName(nameof(Coffer)), XmlIgnore]
        public string FullName => ...;
        [HashInclude]
        public List<Item> Items { get; set; } = new List<Item>();
    
        [XmlRoot]
        public class Item : IParse<Item>
        {
            [XmlAttribute, Browsable(false)]
            public string InternalName { get; set; } = string.Empty;
            [XmlIgnore, Browsable(false)]
            public string DisplayName { get; set; } = string.Empty;
            [DisplayName(nameof(Item)), XmlIgnore]
            public string FullName => ...;
            [XmlAttribute, Browsable(false)]
            public ItemType Type { get; set; }
            [XmlText]
            public int Donate { get; set; }
        }
     }
```
which has been serialized to this code
```xml
            <Coffer>
              <InternalName>Coffer_Influence</InternalName>
              <DisplayName>Influence</DisplayName>
              <Items>
                <Item InternalName="Contribution_Influence" Type="Mission">-1</Item>
                <Item InternalName="Voucher_Influence_Large" Type="Generic">-1</Item>
                <Item InternalName="Voucher_Influence_Large_Mt" Type="Generic">-1</Item>
                <Item InternalName="Voucher_Influence_Siege" Type="Generic">-1</Item>
                <Item InternalName="Voucher_Influence_Small" Type="Generic">-1</Item>
              </Items>
            </Coffer>
```
But when I inherit this class from a dummy
```c#
public class Item : Dummy, IParse<Item>
{ ... }
public class Dummy { }
```
I get such error
```System.InvalidOperationException: Возникла ошибка при отражении свойства "Coffer". --->
System.InvalidOperationException: Возникла ошибка при отражении типа "Classes.Coffer". --->
System.InvalidOperationException: Возникла ошибка при отражении свойства "Items". --->
System.InvalidOperationException: Возникла ошибка при отражении типа "Classes.Coffer.Item". --->
System.InvalidOperationException: Невозможно сериализовать объект типа "Classes.Coffer.Item".
Consider changing type of XmlText member "Classes.Coffer.Item.Donate" from System.Int32 to string or string array.```
Why?

**Comment by laeus** [comment]
Agree with some of the comments that this is a bug worthy of fixing because the workaround stated above is quite frankly untenable (and borderline ridiculous, as pointed out by MrGadget two years ago).

**Comment by MrGadget1024** [comment]
Changing assignments doesn't do much unless you reopen it @huanwu @HongGit
