### ISSUE TITLE
Unexpected KeyNotFoundException in XmlSerializerNamespaces.Namespaces

### ISSUE THREAD

**Issue by remcoros** [dotnet/corefx#21961]
I'm converting a project to netstandard2.0 and run into a KeyNotFoundException from the internals of XmlSerializer (full stack trace below).

I tracked it down from:

https://github.com/dotnet/corefx/blob/release/2.0.0/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializationWriter.cs#L1405

to:

https://github.com/dotnet/corefx/blob/release/2.0.0/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializerNamespaces.cs#L108

When looking at the reference source at: https://referencesource.microsoft.com/#System.Xml/System/Xml/Serialization/XmlSerializerNamespaces.cs,99

'Namespaces' changed from a Hashtable to a Dictionary, which now causes a KeyNotFoundException on non-existing namespaces.

XmlSerializer relies on the fact it can return null.

This could be problematic in other places as well if they rely on a Hashtable. Probably, all references of 'Namespaces' should be checked and corrected with TryGetValue, or go back to using a Hashtable.

Full stack trace:

```
Failed   UblSharp.Tests.SampleTests.UBLInvoice20ExampleNS2Test
Error Message:
 System.InvalidOperationException : There was an error generating the XML document.
---- System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
Stack Trace:
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces)
   at UblSharp.BaseDocumentExtensions.Save[T](T document, XmlWriter writer) in C:\Projects\UblSharp2\src\UblSharp\BaseDocumentExtensions.cs:line 65
   at UblSharp.BaseDocumentExtensions.Save[T](T document, Stream stream) in C:\Projects\UblSharp2\src\UblSharp\BaseDocumentExtensions.cs:line 34
   at UblSharp.Tests.SampleTests.ToXDocument[T](T document) in C:\Projects\UblSharp2\src\UblSharp.Tests\SampleTests.cs:line 96
   at UblSharp.Tests.SampleTests.TestDocument[T](String documentFilename, Func`1 factory) in C:\Projects\UblSharp2\src\UblSharp.Tests\SampleTests.cs:line 47
   at UblSharp.Tests.SampleTests.UBLInvoice20ExampleNS2Test() in C:\Projects\UblSharp2\src\UblSharp.Tests\Samples\SampleTests.partial.cs:line 157
```
```
----- Inner Stack Trace -----

   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at System.Xml.Serialization.XmlSerializationWriter.WriteNamespaceDeclarations(XmlSerializerNamespaces xmlns)
   at System.Xml.Serialization.XmlSerializationWriter.WriteStartElement(String name, String ns, Object o, Boolean writePrefixed, XmlSerializerNamespaces xmlns)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterInvoiceType.Write330_InvoiceType(String n, String ns, InvoiceType o, Boolean isNullable
, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterInvoiceType.Write331_Invoice(Object o)
Skipped  UblSharp.Tests.SampleTests.UBLInvoice20EnvelopedTest
Standard Output Messages:
```

**Comment by danmosemsft** [comment]
@zhenlan

**Comment by remcoros** [comment]
@danmosemsft I think the label should be area-System.Xml 

Also, this was part of a Hashtable to Dictionary conversion by @sepidehMS here: https://github.com/dotnet/corefx/commit/517449e0f4a15ec106c64528645e90bb6434895e

Because 'Namespaces' is internal, it could be that a few other places where missed converting to use TryGetValue.

**Comment by sepidehMS** [comment]
I will take a look at this soon.

**Comment by remcoros** [comment]
It's not just on 2.0.0

Looks like one of the cases is hit when using 'XmlNamespaceDeclarationsAttribute'. I just tested this on netcoreapp1.1 with System.Xml.XmlSerializer 4.0.11 and 4.3.0

I'm actually a bit surprised this hasn't been caught by others earlier in netcore 1, it's a simple use-case.

```csharp
    public class NamespacedTypeSerializationTests
    {
        private readonly ITestOutputHelper _output;

        public NamespacedTypeSerializationTests(ITestOutputHelper output)
        {
            this._output = output;
        }

        [Fact]
        public void CanSerializeTypeWithXmlNamespaceDeclarations()
        {
            var serializer = new XmlSerializer(typeof(TypeWithXmlNamespaceDeclarations));
            var sb = new StringBuilder();
            using (var xmlWriter = XmlWriter.Create(sb))
            {
                var obj = new TypeWithXmlNamespaceDeclarations();
                serializer.Serialize(xmlWriter, obj);
            }

            var xml = sb.ToString();

            _output.WriteLine(xml);
        }

        public class TypeWithXmlNamespaceDeclarations
        {
            [XmlNamespaceDeclarations]
            public XmlSerializerNamespaces Xmlns { get; set; } = new XmlSerializerNamespaces(new[]
            {
                new XmlQualifiedName("somens", "urn:somenamespace")
            });
        }
    }
```

```

System.InvalidOperationException : There was an error generating the XML document.
---- System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at UblSharp.Tests.NamespacedTypeSerializationTests.CanSerializeTypeWithXmlNamespaceDeclarations() in C:\Projects\UblSharp2\src\UblSharp.Tests\NamespacedTypeSerializationTests.cs:line 27
----- Inner Stack Trace -----
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at System.Xml.Serialization.XmlSerializationWriter.WriteNamespaceDeclarations(XmlSerializerNamespaces xmlns)
   at System.Xml.Serialization.XmlSerializationWriter.WriteStartElement(String name, String ns, Object o, Boolean writePrefixed, XmlSerializerNamespaces xmlns)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterTypeWithXmlNamespaceDeclarations.Write2_Item(String n, String ns, TypeWithXmlNamespaceDeclarations o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterTypeWithXmlNamespaceDeclarations.Write3_Item(Object o)


```

**Comment by giltendezm** [comment]
Hello is fix for this issue downloadable via nuget? I'm using System.Xml.XmlSerializer v4.3.0 in a .net standard project targeting v1.1. I still can reproduce this issue.

**Comment by danmosemsft** [comment]
@giltendezm this fix is in 2.0. It is unlikely that you could use the 2.0 binary on a 1.1 runtime. Is updating to 2.0 feasible for you?

**Comment by giltendezm** [comment]
hello @danmosemsft, we plan to target v1.1 because we will still be supporting windows 8.0. 😔😔😔

**Comment by remcoros** [comment]
@giltendezm If you hit the case where using XmlNamespaceDeclarations gives you this exception, you can work around it.

You can remove the 'XmlNamespaceDeclarations' attribute or use a conditional compile statement like this:
https://github.com/UblSharp/UblSharp/blob/master/src/UblSharp/BaseDocument.cs#L21

Then, when using the XmlSerializer, use the 'Serialize' overload which takes a XmlSerializerNamespaces object like this:

https://github.com/UblSharp/UblSharp/blob/master/src/UblSharp/UblDocument.cs#L184

I defined the conditional compile constant in the project files for netstandard1.0/1.3 here:

https://github.com/UblSharp/UblSharp/blob/master/src/UblSharp/UblSharp.csproj#L66

Hope this helps

**Comment by giltendezm** [comment]
@danmosemsft i am referring to .net standard 1.1 instead of .net core :) but really, thank you for your response. :)

@remcoros The workaround solved the XmlNamespaceDeclarations issue! Thank you so much for the detailed steps! :) More power to you! ;)
