### ISSUE TITLE
RemoteExecutorTestBase can't be used with Theory tests

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#21999]
While working on a PR, I needed to use RemoteInvoke to isolate some tests to run in their process. The tests were using ConditionalTheory.

After modifying the test with RemoteInvoke, it threw exceptions:

```
  Assert.All() Failure: 2 out of 3 items in the collection did not pass.
        [1]: Xunit.Sdk.TrueException: Field marshaling is not supported by RemoteInvoke: expectedErrors
             Expected: True
             Actual:   False
                at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                at System.Diagnostics.RemoteExecutorTestBase.<>c.<GetMethodInfo>b__11_0(FieldInfo fi)
                at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action)
        [0]: Xunit.Sdk.TrueException: Field marshaling is not supported by RemoteInvoke: url
             Expected: True
             Actual:   False
                at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                at System.Diagnostics.RemoteExecutorTestBase.<>c.<GetMethodInfo>b__11_0(FieldInfo fi)
                at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action)
        Stack Trace:
             at System.Diagnostics.RemoteExecutorTestBase.GetMethodInfo(Delegate d)
             at System.Diagnostics.RemoteExecutorTestBase.RemoteInvoke(Func`1 method, RemoteInvokeOptions options)
             at System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.<UseCallback_BadCertificate_ExpectedPolicyErrors>d__19.MoveNext()
```

**Comment by davidsh** [comment]
cc: @tarekgh @stephentoub @danmosemsft

**Comment by stephentoub** [comment]
@davidsh, this has nothing to do with [Theory].  The lambda passed to RemoteInvoke can't capture anything, and this error is telling you that you were capturing two locals/fields, expectedErrors and url.  You need to pass them as string arguments to RemoteInvoke, and they'll be passed in as string arguments to the lambdas, e.g. https://github.com/dotnet/corefx/blob/232f48884efed22d228ae4a9450b37fbfa92b861/src/System.Runtime.Serialization.Formatters/tests/BinaryFormatterTests.cs#L448

**Comment by davidsh** [comment]
Ok. Thanks. I will try that out and revise my PR.

**Comment by davidsh** [comment]
@stephentoub 
Dumb question:  why are the parameter orderings reversed? I.e. the 'input' and 'output' parameters are swapped in ordering?

```c#
RemoteInvoke((remoteInput, remoteOutput) =>
  | {
  | Assert.False(File.Exists(remoteOutput));
  | using (FileStream input = File.OpenRead(remoteInput))
  | using (FileStream output = File.OpenWrite(remoteOutput))
  | {
  | var b = new BinaryFormatter();
  | b.Serialize(output, b.Deserialize(input));
  | return SuccessExitCode;
  | }
  | }, outputPath, inputPath).Dispose();
```

**Comment by stephentoub** [comment]
> why are the parameter orderings reversed? I.e. the 'input' and 'output' parameters are swapped in ordering?

They're not actually reversed... the first arg maps to the first arg, the second to the second.  This particular example though swaps the names because from the perspective of the remote process, what's the output of the first process is the input to the second process, and what's the input to the first process is the output from the second process.
