### ISSUE TITLE
System.Drawing.Tests.FontTests failing locally on master

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#22019]
These tests are failing locally on my machine (Windows 10 Fall Creators Update, 16232.1004):

```
<test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Bold, weight: -2147483648, charSet: 0)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.0096335" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 859
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 611]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Bold, weight: -2147483099, charSet: 0)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.0046571" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 859
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 611]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Regular, weight: -2147483098, charSet: 0)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.0013444" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 859
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 611]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Regular, weight: -1, charSet: 0)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.0007927" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 859
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 611]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Regular, weight: 0, charSet: 0)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.000757" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 859
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 611]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Regular, weight: 300, charSet: 0)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.0006089" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 859
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 611]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Regular, weight: 400, charSet: 0)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.000579" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 859
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 611]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Italic, Underline, Strikeout, weight: 549, charSet: 1)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.0031397" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 859
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 611]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Bold, Italic, Underline, Strikeout, weight: 550, charSet: 1)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.0059634" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 859
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 611]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Bold, Italic, Underline, Strikeout, weight: 2147483647, charSet: 1)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.0007085" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 859
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in C:\Users\vikto\Documents\src\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 611]]></stack-trace>
        </failure>
      </test>
```

**Comment by ViktorHofer** [comment]
cc @mellinoe @hughbe

**Comment by mellinoe** [comment]
@hughbe Do you have any time to look at this?

**Comment by mellinoe** [comment]
@ViktorHofer Is this still happening for you?

**Comment by ViktorHofer** [comment]
```csharp
<test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Bold, weight: -2147483648, charSet: 0)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.0087404" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 901
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 641]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Bold, weight: -2147483099, charSet: 0)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.0005338" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 901
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 641]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Regular, weight: -2147483098, charSet: 0)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.001599" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 901
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 641]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Regular, weight: -1, charSet: 0)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.0004922" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 901
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 641]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Regular, weight: 0, charSet: 0)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.0004488" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 901
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 641]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Regular, weight: 300, charSet: 0)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.000471" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 901
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 641]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Regular, weight: 400, charSet: 0)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.0004411" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 901
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 641]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Italic, Underline, Strikeout, weight: 549, charSet: 1)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.0024666" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 901
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 641]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Bold, Italic, Underline, Strikeout, weight: 550, charSet: 1)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.0023929" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 901
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 641]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(fontStyle: Bold, Italic, Underline, Strikeout, weight: 2147483647, charSet: 1)" type="System.Drawing.Tests.FontTests" method="FromLogFont_ValidLogFont_ReturnsExpected" time="0.0004535" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 16\r\nActual:   20]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.VerifyFont(Font font, String expectedName, Single expectedEmSize, FontStyle expectedStyle, GraphicsUnit expectedUnit, Byte expectedGdiCharset, Boolean expectedGdiVerticalFont) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 901
   at System.Drawing.Tests.FontTests.FromLogFont_ValidLogFont_ReturnsExpected(FontStyle fontStyle, Int32 weight, Byte charSet) in D:\git\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 641]]></stack-trace>
        </failure>
      </test>
```

**Comment by mellinoe** [comment]
@ViktorHofer Could you quickly test whether they also fail against `netfx`? Just as a sanity check.

**Comment by mellinoe** [comment]
It seems like using a hardcoded `16` font size is probably invalid here. That value is most likely dependent on some other system state and not a constant. That would explain why your system hits failures here but other folks don't.

**Comment by ViktorHofer** [comment]
Sorry @mellinoe, do you still need your ask?

**Comment by mellinoe** [comment]
Fixed by https://github.com/dotnet/corefx/pull/24009
