### ISSUE TITLE
Crash in loopback server using ssl and client certificates during HttpClient testing

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#22021]
While working on a PR to implement HttpClientHandler.ClientCertificates for UAP, I discovered a crash in the loopback server. It doesn't seem to crash for non-UAP scenarios.

```c#
ERROR:    System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.Manual_CertificateSentMatchesCertificateReceived_Success(numberOfRequest
  s: 6, reuseClient: False) [FAIL]
        System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
        Stack Trace:
             at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
             at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
             at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
             at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
             at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, ```

**Comment by DavidGoll** [comment]
Not blocking UWP6.0... just something we want to dig into before too long.

**Comment by davidsh** [comment]
Can't repro this since the tests have changed a lot.
