### ISSUE TITLE
ComponentResourceManager seems to have different behaviour than netfx

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#22145]
From #22138 

```cs

[Fact]
public void ApplyResources_IComponentWithDesignModeSite_Success()
{
    var resourceManager = new ComponentResourceManager(typeof(global::Resources.TestResx))
    {
        IgnoreCase = true
    };

    var value = new TestComponent { Site = new TestSite { DesignMode = true } };
    resourceManager.ApplyResources(value, "Object");
    Assert.Equal("One", value.GetSetProperty);
}

private class TestSite : ISite
{
    public bool DesignMode { get; set; }

    public IComponent Component => throw new NotImplementedException();
    public IContainer Container => throw new NotImplementedException();
    public string Name { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
    public object GetService(Type serviceType) => null;
}
```

This test passes with `netcoreapp`, but throws with `netfx`:

```
 System.ComponentModel.Tests.ComponentResourceManagerTests.ApplyResources_IComponentWithDesignModeSite_Success [FA
  IL]
        System.NotImplementedException : The method or operation is not implemented.
        Stack Trace:
          C:\Users\hugh\Documents\GitHub\corefx\src\System.ComponentModel.TypeConverter\tests\ComponentResourceManagerT
  ests.cs(154,0): at System.ComponentModel.Tests.ComponentResourceManagerTests.TestSite.get_Container()
             at System.ComponentModel.ReflectTypeDescriptionProvider.GetExtenderProviders(Object instance)
             at System.ComponentModel.ReflectTypeDescriptionProvider.GetExtendedProperties(Object instance)
             at System.ComponentModel.TypeDescriptor.GetPropertiesImpl(Object component, Attribute[] attributes, Boolea
  n noCustomTypeDesc, Boolean noAttributes)
             at System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureI
  nfo culture)
          C:\Users\hugh\Documents\GitHub\corefx\src\System.ComponentModel.TypeConverter\tests\ComponentResourceManagerT
  ests.cs(145,0): at System.ComponentModel.Tests.ComponentResourceManagerTests.ApplyResources_IComponentWithDesignModeS
  ite_Success()
```

**Comment by safern** [comment]
Closing as this is in netfx.
