### ISSUE TITLE
System.Runtime.Serialization.Formatters.Tests failing in UapAot

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#22348]
Tests are failing with error: 

```
The stored blob for type System.TimeZoneInfo+AdjustmentRule is outdated and needs to be updated.\r\nStored blob: AAEAAAD/////AQAAAAAAAAAEAQAAACJTeXN0ZW0uVGltZVpvbmVJbmZvK0FkanVzdG1lbnRSdWxlBwAAAAlEYXRlU3RhcnQHRGF0ZUVuZA1EYXlsaWdodERlbHRhF0RheWxpZ2h0VHJhbnNpdGlvblN0YXJ0FURheWxpZ2h0VHJhbnNpdGlvbkVuZBJCYXNlVXRjT2Zmc2V0RGVsdGEVTm9EYXlsaWdodFRyYW5zaXRpb25zAAAAAwMAAA0NDCJTeXN0ZW0uVGltZVpvbmVJbmZvK1RyYW5zaXRpb25UaW1lIlN5c3RlbS5UaW1lWm9uZUluZm8rVHJhbnNpdGlvblRpbWUMAQBAVyBTBVEIAEDGiJPMjwgA0IjDEAAAAAT+////IlN5c3RlbS5UaW1lWm9uZUluZm8rVHJhbnNpdGlvblRpbWUGAAAACVRpbWVPZkRheQVNb250aARXZWVrA0RheQlEYXlPZldlZWsPSXNGaXhlZERhdGVSdWxlAAAAAAMADQICAhBTeXN0ZW0uRGF5T2ZXZWVrAQDQiMMQAAAAAgEDBP3///8QU3lzdGVtLkRheU9mV2VlawEAAAAHdmFsdWVfXwAIAAAAAAEB/P////7///8A0IjDEAAAAAMBBAH7/////f///wAAAAABAAAAAAAAAAAACw==\r\nGenerated runtime blob: AAEAAAD/////AQAAAAAAAAAEAQAAACJTeXN0ZW0uVGltZVpvbmVJbmZvK0FkanVzdG1lbnRSdWxlBgAAAAlEYXRlU3RhcnQHRGF0ZUVuZA1EYXlsaWdodERlbHRhF0RheWxpZ2h0VHJhbnNpdGlvblN0YXJ0FURheWxpZ2h0VHJhbnNpdGlvbkVuZBJCYXNlVXRjT2Zmc2V0RGVsdGEAAAADAwANDQwiU3lzdGVtLlRpbWVab25lSW5mbytUcmFuc2l0aW9uVGltZSJTeXN0ZW0uVGltZVpvbmVJbmZvK1RyYW5zaXRpb25UaW1lDABAVyBTBVEIAEDGiJPMjwgA0IjDEAAAAAT+////IlN5c3RlbS5UaW1lWm9uZUluZm8rVHJhbnNpdGlvblRpbWUGAAAACVRpbWVPZkRheQVNb250aARXZWVrA0RheQlEYXlPZldlZWsPSXNGaXhlZERhdGVSdWxlAAAAAAMADQICAhBTeXN0ZW0uRGF5T2ZXZWVrAQDQiMMQAAAAAgEDBP3///8QU3lzdGVtLkRheU9mV2VlawEAAAAHdmFsdWVfXwAIAAAAAAEB/P////7///8A0IjDEAAAAAMBBAH7/////f///wAAAAABAAAAAAAAAAAL\r\nExpected: True\r\nActual:   False
```

Stack Trace:
```
at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.SanityCheckBlob(Object obj, String[] blobs)
   at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs(Object obj, String[] blobs)
   at Object _$ILCT$+$ILT$ReflectionDynamicInvoke$.InvokeRetVII[T0, T1](Object, IntPtr, InvokeUtils+ArgSetupState&, Boolean) + 0x6f
   at Object System.InvokeUtils+CalliIntrinsics.Call(IntPtr, IntPtr, Object, IntPtr, InvokeUtils+ArgSetupState&, Boolean) + 0x55
   at Object System.InvokeUtils.CallDynamicInvokeMethod(Object, IntPtr, Object, IntPtr, IntPtr, Object, Object[], BinderBundle, Boolean, Boolean) + 0x171
```

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170717.02/workItem/System.Runtime.Serialization.Formatters.Tests/analysis/xunit/System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests~2FValidateAgainstBlobs(obj:%20AdjustmentRule%20%7B%20DateEnd%20=%201955-12-31T00:00:00.0000000,%20DateStart%20=%201900-01-01T00:00:00.0000000,%20Da...

**Comment by safern** [comment]
This is related to: https://github.com/dotnet/corefx/issues/21720

But I wanted to open this individual bug in order to track the ilc failure as that falls into the UWP milestone.

**Comment by danmosemsft** [comment]
@ViktorHofer is out until Monday. Perhaps @tarekgh can look sooner, if he frees up.

**Comment by ViktorHofer** [comment]
Josh was asking Morgen if he could take a look

**Comment by ViktorHofer** [comment]
For this precise issue I have already done like 80% of the work required (merging coreclr and corert TimeZoneInfo code). I will submit a PR in coreclr and ask @tarekgh if he can finish the work (Unix code not converged yet).

**Comment by ViktorHofer** [comment]
Done. See https://github.com/dotnet/coreclr/pull/12899
