### ISSUE TITLE
System.Threading.Tasks.Tests are failing in UapAot

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#22350]
- System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.FaultedTaskExceptions
-  System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.TaskMethodBuilderT_ValidateFaultedTask
- System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.TaskMethodBuilder_ValidateFaultedTask
- System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.Tcs_ValidateFaultedTask
- System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.TrackedSyncContext_ValidateException

This tests are failing with error:

```
Assert.Contains() Failure\r\nNot found: End of stack trace\r\nIn value:     at System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.TrackedSyncContext_ValidateException()\r\n   at xunit.console.netcore!<BaseAddress>+0x1\r\n   at Void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21\r\n   at Void System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0(Object) + 0x1e\r\n   at System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.TrackOperationsSynchronizationContext.Post(Threading.SendOrPostCallback callback, Object state)\r\n
```

Stack Trace:
```
   at System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.ValidateException(Exception e)
   at System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.TrackedSyncContext_ValidateException()
   at Object _$ILCT$+$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object, IntPtr, InvokeUtils+ArgSetupState&, Boolean) + 0x50
   at Object System.InvokeUtils+CalliIntrinsics.Call(IntPtr, Object, IntPtr, InvokeUtils+ArgSetupState&, Boolean) + 0x43
   at Object System.InvokeUtils.CallDynamicInvokeMethod(Object, IntPtr, Object, IntPtr, IntPtr, Object, Object[], BinderBundle, Boolean, Boolean) + 0x183
```

cc: @joshfree

**Comment by AntonLapounov** [comment]
These tests call `Assert.Contains("End of stack trace", e.StackTrace)`.  After ProjectN change 1666008, `e.StackTrace` no longer contains this substring.  Before:
```
   at System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.TrackedSyncContext_ValidateException()
--- End of stack trace from previous location where exception was thrown ---
   at Void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x1c
   at Void System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0(Object) + 0x19
   at Void System.Action`1.Invoke(T) + 0x1e
   at System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.TrackOperationsSynchronizationContext.Post(Threading.SendOrPostCallback callback, Object state)
```
After:
```
   at System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.TrackedSyncContext_ValidateException()
   at xunit.console.netcore!<BaseAddress>+0x1
   at Void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at Void System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0(Object) + 0x1e
   at System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.TrackOperationsSynchronizationContext.Post(Threading.SendOrPostCallback callback, Object state)
```

**Comment by safern** [comment]
Is this expected? If so should we skip that Assert.Contains for UapAot?

**Comment by trylek** [comment]
I think it's just a bug I made in my recent refactoring related to NS2.0 API implementation, I'm looking into that right now.

**Comment by danmosemsft** [comment]
Also https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170717.02/workItem/System.Runtime.Tests/analysis/xunit/System.Runtime.ExceptionServices.Tests.ExceptionDispatchInfoTests~2FStaticThrow_UpdatesStackTraceAppropriately

**Comment by safern** [comment]
Not failing anymore. Thanks @trylek for fixing it.
