### ISSUE TITLE
Diff between Core 2.0 and legacy Fx: XslTransform fails on custom function

### ISSUE THREAD

**Issue by pjanotti** [dotnet/corefx#22373]
This came about when working on #21201. The test for `XslTransform` using `XsltArgumentList` with a custom implementation crashes with the following stack on Core 2.0:

```
Unhandled Exception: System.Xml.XPath.XPathException: Function 'ext:distinct()' has failed. ---> System.InvalidCastException: Invalid cast from 'System.Double' to 'System.Xml.XPath.XPathNodeIterator'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.Xml.Xsl.XsltOld.XsltCompileContext.XsltFunctionImpl.ToNumeric(Object argument, Type type)
   at System.Xml.Xsl.XsltOld.XsltCompileContext.XsltFunctionImpl.ConvertToXPathType(Object val, XPathResultType xt, Type type)
   at System.Xml.Xsl.XsltOld.XsltCompileContext.FuncExtension.Invoke(XsltContext xsltContext, Object[] args, XPathNavigator docContext)
   at MS.Internal.Xml.XPath.FunctionQuery.Evaluate(XPathNodeIterator nodeIterator)
   --- End of inner exception stack trace ---
   at MS.Internal.Xml.XPath.FunctionQuery.Evaluate(XPathNodeIterator nodeIterator)
   at System.Xml.Xsl.XsltOld.Processor.StartQuery(XPathNodeIterator context, Int32 key)
   at System.Xml.Xsl.XsltOld.ForEachAction.Execute(Processor processor, ActionFrame frame)
   at System.Xml.Xsl.XsltOld.ActionFrame.Execute(Processor processor)
   at System.Xml.Xsl.XsltOld.Processor.Execute()
   at System.Xml.Xsl.XsltOld.Processor.Execute(TextWriter writer)
   at System.Xml.Xsl.XslTransform.Transform(XPathNavigator input, XsltArgumentList args, TextWriter output)
   at Legacy_ExtObjDistinctFunction.Program.Main(String[] args) in C:\projects\XmlDistinctInvestigation\repro\Program.cs:line 31
```

On legacy Fx v2.0.50727 and v4.7.2046.0 the same code produces the expected results. For convenience the code with the isolated repro is below but the respective test is going to be marked with the # of this issue too.

Note: the order of elements returned in the transformed xml between different versions of the Fx is different, the test perhaps should sort the elements to avoid issues with that.

```c#
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Xml;
using System.Xml.XPath;
using System.Xml.Xsl;

#pragma warning disable 0618

namespace Legacy_ExtObjDistinctFunction
{
    class Program
    {
        static void Main(string[] args)
        {
            XsltArgumentList xsltArg = new XsltArgumentList();
            xsltArg.AddExtensionObject("http://foo.com", new MyXsltExtension());

            XslTransform xslTransform = new XslTransform();
            using (StringReader streamReader = new StringReader(c_xsl))
            using (XmlTextReader xmlReader = new XmlTextReader(streamReader))
                xslTransform.Load(xmlReader);

            using (StringWriter streamWriter = new StringWriter())
            using (StringReader streamReader = new StringReader(c_xml))
            using (XmlTextReader xmlReader = new XmlTextReader(streamReader))
            {
                XPathDocument xpathDoc = new XPathDocument(xmlReader);
                xslTransform.Transform(xpathDoc.CreateNavigator(), xsltArg, streamWriter);
                streamWriter.Flush();
                Console.WriteLine(streamWriter.GetStringBuilder());
            }

            Console.WriteLine("It read the doc without issues!!!");
        }

        #region Files
        const string c_xsl = @"
<xsl:stylesheet
xmlns:xsl=""http://www.w3.org/1999/XSL/Transform"" version=""1.0""
xmlns:ext=""http://foo.com"" extension-element-prefixes=""ext"">
    <xsl:template match = ""/"" >
        <distinct-countries >
            <xsl:for-each select = ""ext:distinct(//@country)"" >
                 <xsl:value-of select = ""."" />
                  <xsl:if test=""position() != last()"">, </xsl:if>
            </xsl:for-each>
        </distinct-countries>
    </xsl:template>
</xsl:stylesheet>
";
        const string c_xml = @"
<doc>
   <city name=""Paris""
         country=""France""/>
   <city name = ""Madrid""
         country=""Spain""/>
   <city name = ""Vienna""
         country=""Austria""/>
   <city name = ""Barcelona""
         country=""Spain""/>
   <city name = ""Salzburg""
         country=""Austria""/>
   <city name = ""Bonn""
         country=""Germany""/>
   <city name = ""Lyon""
         country=""France""/>
   <city name = ""Hannover""
         country=""Germany""/>
   <city name = ""Calais""
         country=""France""/>
   <city name = ""Berlin""
         country=""Germany""/>
</doc>";
        #endregion
    }
    internal class MyXsltExtension
    {
        public XPathNodeIterator distinct(XPathNodeIterator nodeset)
        {
            Hashtable nodelist = new Hashtable();
            while (nodeset.MoveNext())
            {
                if (!nodelist.Contains(nodeset.Current.Value))
                {
                    nodelist.Add(nodeset.Current.Value, nodeset.Current.Clone());
                }
            }
            return new MyArrayIterator(new ArrayList(nodelist.Values));
        }
    }

    internal class MyArrayIterator : XPathNodeIterator
    {
        protected ArrayList array;
        protected int index;

        public MyArrayIterator(ArrayList array)
        {
            this.array = array;
            this.index = 0;
        }

        public MyArrayIterator(MyArrayIterator it)
        {
            this.array = it.array;
            this.index = it.index;
        }

        public override XPathNodeIterator Clone()
        {
            return new MyArrayIterator(this);
        }

        public override bool MoveNext()
        {
            if (index < array.Count)
            {
                index++;
                return true;
            }
            return false;
        }

        public override XPathNavigator Current
        {
            get
            {
                return (index > 0) ? (XPathNavigator)array[index - 1] : null;
            }
        }

        public override int CurrentPosition
        {
            get
            {
                return index;
            }
        }

        public override int Count
        {
            get
            {
                return array.Count;
            }
        }

        public void Reset()
        {
            index = 0;
        }

        // BUGBUG: DCR 104760
        public override IEnumerator GetEnumerator()
        {
            MyArrayIterator it = (MyArrayIterator)this.Clone();
            it.Reset();
            return (IEnumerator)it;
        }
    }
}
```

**Comment by danmosemsft** [comment]
@sepidehMS could you please evaluate the impact.
