### ISSUE TITLE
SqlConnection.Open fails with SSL error on macOS High Sierra (10.13)

### ISSUE THREAD

**Issue by kevcunnane** [dotnet/corefx#22453]
SqlClient connections to any SQL Server instance fails on macOS High Sierra. The repro for this is below. This is impacting users of the MSSQL extension for VSCode - see https://github.com/Microsoft/vscode-mssql/issues/954 for the original bug report. I've created a .Net only repo below that's very simple. 

@saurabh500 @corivera @karelz could you please take a look and let us know if you need anything more? We naturally would like to get this into the next Preview of .Net Core 2.0 and we'll update our MSSQL release to include that as otherwise when High Sierra goes GA, users will start to run into this problem more often.

**Repro steps**
1. Ensure you have a SQL Server instance running. In this example I'm using [localhost in Docker per MSSQL Docs](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker)
2. install dotnet core 2.0 SDK on a mac
3. Create a new console application and add SqlClient dependency:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
	<Reference Include="System.Data.SqlClient" />
  </ItemGroup>
  <ItemGroup>
	  <PackageReference Include="System.Data.SqlClient" Version="4.4.0-preview1-25305-02" />
	</ItemGroup>
</Project>
```

4. Update the `Program.cs` file to call `SqlConnection.Open`
```
using System;
using System.Data.SqlClient; 

namespace hwapp
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                using (SqlConnection con = 
                    new SqlConnection("Data Source=localhost;Initial Catalog=master;User=sa;Password=Yukon900"))
                {
                    con.Open();
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }
    }
}
```

**Expected**
Connection is opened successfully
**Actual**
SSL handshake error occurs:
```
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 31 - Encryption(ssl/tls) handshake failed) ---> System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
   at Internal.Cryptography.Pal.SecTrustChainPal.ParseResults(SafeX509ChainHandle chainHandle, X509RevocationMode revocationMode)
   at Internal.Cryptography.Pal.SecTrustChainPal.Execute(DateTime verificationTime, Boolean allowNetwork, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationFlag revocationFlag)
   at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
   at System.Net.CertificateValidationPal.VerifyCertificateProperties(SafeDeleteContext securityContext, X509Chain chain, X509Certificate2 remoteCertificate,Boolean checkCertName, Boolean isServer, String hostName)
   at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback, ProtocolToken& alertToken)
   at System.Net.Security.SslState.CompleteHandshake(ProtocolToken& alertToken)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.SqlClient.SNI.SNITCPHandle.EnableSsl(UInt32 options)
   at System.Data.SqlClient.SNI.SNIProxy.EnableSsl(SNIHandle handle, UInt32 options)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at hwapp.Program.Main(String[] args) in /Users/kevincunnane/hwapp/Program.cs:line 15
ClientConnectionId:85d1abe2-b84a-4773-8205-c3bb87312975
```

**Comment by kevcunnane** [comment]
One more thing - I see looking more closely at your [announcement page ](https://github.com/dotnet/announcements/issues/22) there are a number of SSL issues you reported to Apple. It's quite likely this is then a known issue / duplicate of these.

**Comment by danmosemsft** [comment]
@bartonjs

**Comment by bartonjs** [comment]
The one we reported has to do with SecureTransport being the server; but maybe they have a related client bug.  It'd be interesting to see the TLS handshake series as captured by tcpdump/Wireshark/etc.

**Comment by geleems** [comment]
@kevcunnane Hi, I was trying to repro the issue you were experiencing, and the issue did not happen in my repro steps on macOS 10.12.

Here is my environment info:
* SQL Server 2016 running on different VM
* .NET Core 2.0.0-preview2-25401-01 on macOS ***10.12***
* csproj file
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.4.0-preview1-25305-02" />
  </ItemGroup>
</Project>
```
* Program.cs
```
using System;
using System.Data.SqlClient;

namespace hwapp
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                using (SqlConnection con = new SqlConnection("Data Source=other-vm-hostname;User ID=testuser;Password=test1234"))
                {
                    con.Open();
                    Console.WriteLine("Connection opened successfully");
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }
    }
}
```
* Console output:
```
➜  hwapp  dotnet restore && dotnet run
  Restore completed in 20.58 ms for /Users/admin/Documents/hwapp/hwapp.csproj.
Connection opened successfully
➜  hwapp 
```

**Comment by kevcunnane** [comment]
@geleems exactly, this does not occur on Sierra (10.12). As mentioned it is a high Sierra (10.13) issue only. SqlClient is completely broken on this. I understand High Sierra is in preview but it'll be released in a few months. That's why I linked this bug in https://github.com/dotnet/core/issues/677 which is tracking all High Sierra-specific issues

**Comment by danmosemsft** [comment]
@bartonjs who is best placed to investigate this? It isn't in SQL code.

**Comment by bartonjs** [comment]
@kevcunnane Have you tried with the latest builds?  Looking at the callstack again this looks like one of the first High Sierra bugs we fixed.

@danmosemsft Dunno.  I don't have, or know how to obtain, SQL resources; so I can't test it.

**Comment by kevcunnane** [comment]
@bartonjs I've just tested using the official [.Net Core 2.0 Preview 2](https://www.microsoft.com/net/core/preview#macos) bits. I'd be happy to test if there is a new build I can install on my mac? Note that I'm not set up to build corefx and integrate it locally but if there's an installable SDK I can do so.

It'd be great if this was already fixed and will be in the next update.

By the way testing against SQL is pretty easy with Docker + SQL on Linux. Steps are [here](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker), it's basically install docker and do a `docker pull microsoft/mssql-server-linux` to get a localhost instance available.

**Comment by anfomin** [comment]
I've the same issue on macOS 10.13 High Sierra while connecting to the SQL Server 2014. However encryption is not enabled in the connection string.

It's strange but connection to the SQL Azure via SqlClient works. Is there any workaround for connection to the SQL Server?

**Comment by bartonjs** [comment]
@kevcunnane Here's the saga of the links you need to have noticed.  (Not casting aspersions at you, you can just skip to the end if you like :smile:)

* The landing page (https://github.com/dotnet/corefx/).
* That has a section called "How to Engage, Contribute and Provide Feedback"
* In there there's a link "Dogfooding daily builds" (https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md)
  * Not to be confused with, at the bottom, the "Daily Builds"/MyGet section.
* This page has some nice, simple links.  Of course, if you look at them they say "master", but we're wanting 2.0.
  * Changing to the release/2.0.0 version of this page doesn't change the links.
  * Let's follow "Others" (https://github.com/dotnet/cli/blob/master/README.md#installers-and-binaries)
* Okay, this page also says "master".  Change to release/2.0.0 (https://github.com/dotnet/cli/blob/release/2.0.0/README.md)
* Ooh, this has links that say 2.0.0 in them, they're probably real.
* Grabbing https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/2.0.0/dotnet-sdk-latest-osx-x64.tar.gz and hitting it with `tar -tzvf` shows that it contains (as of this writing) `./shared/Microsoft.NETCore.App/2.0.0-preview3-25518-01/`, making it the 25518-01 build, and I think "25516-01" contained the last fix we've done specifically for HIgh Sierra.

So, https://github.com/dotnet/cli/blob/release/2.0.0/README.md.  And grab whichever asset matches how you do things (the .pkg or the .tar.gz).

**Comment by kevcunnane** [comment]
Great news! I verified this is fixed in the Preview 3 daily builds. So I'll close this out. Thank you for the pointers - I would have really struggled to figure out where the builds are / how to get this tested.

**Comment by kevcunnane** [comment]
One more question - is there a public ETA for Preview 3? We'll want to take that as soon as it's available. Thanks!

**Comment by danmosemsft** [comment]
@kevcunnane thanks for verifying. For dates -- we don't have anything more concrete right now than what's [on our roadmap](https://github.com/dotnet/core/blob/master/roadmap.md). Not long now though.

**Comment by danmosemsft** [comment]
I should also add we expect CoreFX to ship essentially in the state you just got.. so it'd be great if you'd flag any other issues you hit.

**Comment by amerzafar** [comment]
yes this is back on High Sierra 10.13.4, is there any work around?

**Comment by bartonjs** [comment]
@amerzafar See #28652.  The fix is in master, and in the release branch.  You can locally build the shim library, grab the latest runtime, rollback the update, or wait a week or two for the update to drop.

**Comment by derk2689** [comment]
Any word on when this might be fixed?

**Comment by amerzafar** [comment]
@bartonjs is this fixed released. I am still having this.

**Comment by bartonjs** [comment]
@amerzafar Yes, release 2.0.7.  A fair amount of troubleshooting / success stories are in #28652.
