### ISSUE TITLE
SqlClient FunctionalTests fail due to missing System.Private.Interop.dll

### ISSUE THREAD

**Issue by corivera** [dotnet/corefx#22458]
The SqlClient functional tests are failing on a clean build of the latest master branch. SqlClient ManualTests are fine.

Test output:
Running tests... Start time: 16:41:07.42

  Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Private.Interop, Ver
  sion=999.999.999.999, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified
  .
     at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
     at System.ConsolePal.set_ForegroundColor(ConsoleColor value) in C:\SqlProjects\CoreFx\src\System.Console\src\Sy
  stem\ConsolePal.Windows.cs:line 504
     at System.Console.set_ForegroundColor(ConsoleColor value) in C:\SqlProjects\CoreFx\src\System.Console\src\Syste
  m\Console.cs:line 181
     at Xunit.ConsoleClient.Program.Main(String[] args)
  Finished running tests.  End time=16:41:41.72, Exit code = -532462766

Seems like the failures happen before the tests even get run.

**Comment by corivera** [comment]
Correction, this issue does not repro on a clean build. I built uap before I started seeing these failures. Maybe it's related

**Comment by corivera** [comment]
Actually can't repro the bug at all now. Maybe it was a transient issue with myget or something. Closing this bug.
