### ISSUE TITLE
AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection failing

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#22707]
AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection(statusCode: 300, oldMethod: \"POST\", newMethod: \"GET\")

PR #22702 and the added tests has exposed that CurlHandler is not changing HTTP method verbs appropriately for certain redirect status codes.

Ref: https://mc.dot.net/#/user/davidsh/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/2621566904aabc833bf3515748c9c6253f5d37bc/workItem/System.Net.Http.Functional.Tests

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by stephentoub** [comment]
What are you defining as the correct behavior here? We rely on curl's default semantics, described in https://curl.haxx.se/libcurl/c/CURLOPT_POSTREDIR.html.

**Comment by davidsh** [comment]
>What are you defining as the correct behavior here? We rely on curl's default semantics, described in https://curl.haxx.se/libcurl/c/CURLOPT_POSTREDIR.html.

The RFC itself.  Also, the test work on .NET Framework, .NET Core (Windows, i.e. using WinHTTP) and UWP (Wininet).

**Comment by stephentoub** [comment]
> The RFC itself.

I'm missing it somehow. Can you point me to the relevant part of the RFC that discusses this for status code 300?

**Comment by davidsh** [comment]
The 300 status code (multiple choice) behaves in a similar fashion to 301, 302.  The RFC isn't very crisp on the 300 response code. 

https://tools.ietf.org/html/rfc7231#page-55

It isn't really used much in practice since the default Location: response header is used by all browers and stacks today.  In addition, we should have the behavior be aligned among .NET Framework and the rest of .NET Core.

**Comment by stephentoub** [comment]
May be a different issue, but the test also failed on Windows here:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/f047e951e42c234a576d8bb9765bd0e6235084bf/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandlerTest~2FAllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection(statusCode:%20300,%20oldMethod:%20%5C%22HEAD%5C%22,%20newMethod:%20%5C%22HEAD%5C%22)
```
017-08-12 15:01:12,625: INFO: proc(54): run_and_log_output: Output:    System.Net.Http.Functional.Tests.HttpClientHandlerTest.AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection(statusCode: 300, oldMethod: \"HEAD\", newMethod: \"HEAD\") [FAIL]
2017-08-12 15:01:12,627: INFO: proc(54): run_and_log_output: Output:       Faulted: System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
2017-08-12 15:01:12,627: INFO: proc(54): run_and_log_output: Output:          at System.Environment.get_StackTrace()
2017-08-12 15:01:12,627: INFO: proc(54): run_and_log_output: Output:          at System.Runtime.ExceptionServices.ExceptionStackTrace.AddCurrentStack(Exception exception)
2017-08-12 15:01:12,628: INFO: proc(54): run_and_log_output: Output:          at System.Net.Http.WinHttpException.CreateExceptionUsingError(Int32 error)
2017-08-12 15:01:12,628: INFO: proc(54): run_and_log_output: Output:          at System.Net.Http.WinHttpRequestCallback.OnRequestError(WinHttpRequestState state, WINHTTP_ASYNC_RESULT asyncResult)
2017-08-12 15:01:12,628: INFO: proc(54): run_and_log_output: Output:          at System.Net.Http.WinHttpRequestCallback.RequestCallback(IntPtr handle, WinHttpRequestState state, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
2017-08-12 15:01:12,628: INFO: proc(54): run_and_log_output: Output:          at System.Net.Http.WinHttpRequestCallback.WinHttpCallback(IntPtr handle, IntPtr context, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
2017-08-12 15:01:12,628: INFO: proc(54): run_and_log_output: Output:       --- End of stack trace from AddCurrentStack ---
2017-08-12 15:01:12,628: INFO: proc(54): run_and_log_output: Output:          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-08-12 15:01:12,628: INFO: proc(54): run_and_log_output: Output:          at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
2017-08-12 15:01:12,628: INFO: proc(54): run_and_log_output: Output:          at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
2017-08-12 15:01:12,628: INFO: proc(54): run_and_log_output: Output:          --- End of inner exception stack trace ---
2017-08-12 15:01:12,628: INFO: proc(54): run_and_log_output: Output:          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-08-12 15:01:12,628: INFO: proc(54): run_and_log_output: Output:          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-08-12 15:01:12,628: INFO: proc(54): run_and_log_output: Output:          at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
2017-08-12 15:01:12,628: INFO: proc(54): run_and_log_output: Output:          at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
2017-08-12 15:01:12,630: INFO: proc(54): run_and_log_output: Output:          --- End of inner exception stack trace ---
2017-08-12 15:01:12,630: INFO: proc(54): run_and_log_output: Output:       ---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
2017-08-12 15:01:12,630: INFO: proc(54): run_and_log_output: Output:          at System.Environment.get_StackTrace()
2017-08-12 15:01:12,630: INFO: proc(54): run_and_log_output: Output:          at System.Runtime.ExceptionServices.ExceptionStackTrace.AddCurrentStack(Exception exception)
2017-08-12 15:01:12,630: INFO: proc(54): run_and_log_output: Output:          at System.Net.Http.WinHttpException.CreateExceptionUsingError(Int32 error)
2017-08-12 15:01:12,630: INFO: proc(54): run_and_log_output: Output:          at System.Net.Http.WinHttpRequestCallback.OnRequestError(WinHttpRequestState state, WINHTTP_ASYNC_RESULT asyncResult)
2017-08-12 15:01:12,630: INFO: proc(54): run_and_log_output: Output:          at System.Net.Http.WinHttpRequestCallback.RequestCallback(IntPtr handle, WinHttpRequestState state, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
2017-08-12 15:01:12,630: INFO: proc(54): run_and_log_output: Output:          at System.Net.Http.WinHttpRequestCallback.WinHttpCallback(IntPtr handle, IntPtr context, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
2017-08-12 15:01:12,630: INFO: proc(54): run_and_log_output: Output:       --- End of stack trace from AddCurrentStack ---
2017-08-12 15:01:12,631: INFO: proc(54): run_and_log_output: Output:          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-08-12 15:01:12,631: INFO: proc(54): run_and_log_output: Output:          at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
2017-08-12 15:01:12,631: INFO: proc(54): run_and_log_output: Output:          at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
2017-08-12 15:01:12,631: INFO: proc(54): run_and_log_output: Output:          --- End of inner exception stack trace ---
2017-08-12 15:01:12,631: INFO: proc(54): run_and_log_output: Output:          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-08-12 15:01:12,631: INFO: proc(54): run_and_log_output: Output:          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-08-12 15:01:12,631: INFO: proc(54): run_and_log_output: Output:          at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
2017-08-12 15:01:12,631: INFO: proc(54): run_and_log_output: Output:          at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()<---
2017-08-12 15:01:12,631: INFO: proc(54): run_and_log_output: Output:       
2017-08-12 15:01:12,631: INFO: proc(54): run_and_log_output: Output:       Expected: False
2017-08-12 15:01:12,631: INFO: proc(54): run_and_log_output: Output:       Actual:   True
2017-08-12 15:01:12,634: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-08-12 15:01:12,703: INFO: proc(54): run_and_log_output: Output:             at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass46_1.<<AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection>b__0>d.MoveNext()
2017-08-12 15:01:12,703: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-08-12 15:01:12,703: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-08-12 15:01:12,703: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-08-12 15:01:12,703: INFO: proc(54): run_and_log_output: Output:             at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass3_0.<CreateServerAsync>b__0(Task t)
2017-08-12 15:01:12,703: INFO: proc(54): run_and_log_output: Output:             at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2017-08-12 15:01:12,703: INFO: proc(54): run_and_log_output: Output:             at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2017-08-12 15:01:12,703: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-08-12 15:01:12,703: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-08-12 15:01:12,703: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-08-12 15:01:12,703: INFO: proc(54): run_and_log_output: Output:             at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection>d__46.MoveNext()
2017-08-12 15:01:12,704: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-08-12 15:01:12,704: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-08-12 15:01:12,704: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-08-12 15:01:12,704: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-08-12 15:01:12,704: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-08-12 15:01:12,704: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-08-12 15:01:12,704: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-08-12 15:01:12,704: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-08-12 15:01:12,704: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by davidsh** [comment]
Probably an intermittent connection issue w/ Azure.  

>The connection with the server was terminated abnormally

**Comment by Jiayili1** [comment]
Failed again: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170817.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandlerTest~2FAllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection(statusCode:%20300,%20oldMethod:%20%5C%22HEAD%5C%22,%20newMethod:%20%5C%22HEAD%5C%22)

**Comment by davidsh** [comment]
Duplicate of #9228.  Azure internet issues causing requests to be canceled.

>System.Net.Http.WinHttpException : The connection with the server was terminated abnormally
