### ISSUE TITLE
System.Data.SqlClient.Tests.AmbientTransactionFailureTest.TestSqlException failed with "System.InvalidOperationException" in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#22719]
Failed Test: System.Data.SqlClient.Tests.AmbientTransactionFailureTest.TestSqlException

Configuration: outerloop_netcoreapp_rhel7.2_release

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_rhel7.2_release/122/testReport/System.Data.SqlClient.Tests/AmbientTransactionFailureTest/TestSqlException_connectAction__Action_1___Method___Void___cctor_b__13_0_System_String___Target_____c________connectionString____Data_Source_605a0eb5_7c51_414a_b735_afb0f076140d________/

MESSAGE:
~~~
Assert.Throws() Failure
Expected: typeof(System.Data.SqlClient.SqlException)
Actual: typeof(System.InvalidOperationException): Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use and max pool size was reached.
~~~
STACK TRACE:
~~~
at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection) 
in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_rhel7.2_release/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionFactory.cs:line 318 
at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) 
in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_rhel7.2_release/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionInternal.cs:line 700 
at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry) 
in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_rhel7.2_release/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnection.cs:line 1062 
at System.Data.SqlClient.SqlConnection.Open() 
in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_rhel7.2_release/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnection.cs:line 606 
at System.Data.SqlClient.Tests.AmbientTransactionFailureTest.<>c.<.cctor>b__13_0(String connectionString) 
in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_rhel7.2_release/src/System.Data.SqlClient/tests/FunctionalTests/AmbientTransactionFailureTest.cs:line 22
~~~

**Comment by geleems** [comment]
@Jiayili1 It failed to get connection from connection pool due to timeout. The timeout was set to ***1ms*** in the test, and the cause seems to be system performance rather than connection pool problem. Did you try again after facing the failure?

**Comment by geleems** [comment]
No response from user. Closing the issue.

**Comment by Jiayili1** [comment]
This issue failed again in Master branch, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170830.01/workItem/System.Data.SqlClient.Tests/analysis/xunit/System.Data.SqlClient.Tests.AmbientTransactionFailureTest~2FTestSqlException(connectAction:%20Action%601%20%7B%20Method%20=%20Void%20%3C.cctor%3Eb__13_0(System.String),%20Target%20=%20%3C%3Ec%20%7B%20%7D%20%7D,%20connectionString:%20%5C%22Data%20...

The test `System.Data.SqlClient.Tests.AmbientTransactionFailureTest/TestSqlException(connectAction: Action`1 { Method = Void <.cctor>b__13_0(System.String), Target = <>c { } }, connectionString: \"Data ...` has failed.

Assert.Throws() Failure
    Expected: typeof(System.Data.SqlClient.SqlException)
    Actual:   typeof(System.InvalidOperationException): Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.

        Stack Trace:

           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection) in /root/corefx-958109/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionFactory.cs:line 318
       at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in /root/corefx-958109/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionInternal.cs:line 700
       at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry) in /root/corefx-958109/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnection.cs:line 1062
       at System.Data.SqlClient.SqlConnection.Open() in /root/corefx-958109/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnection.cs:line 606
       at System.Data.SqlClient.Tests.AmbientTransactionFailureTest.<>c.<.cctor>b__13_0(String connectionString) in /root/corefx-958109/src/System.Data.SqlClient/tests/FunctionalTests/AmbientTransactionFailureTest.cs:line 22
Build : Master - 20170830.01 (Core Tests)
Failing configurations:
- Ubuntu.1710.Amd64-x64
  - Release

**Comment by saurabh500** [comment]
The tests were most likely failing because of thread pool exhaustion while trying to get a connection for SqlConnection. These tests should now work fine after the fix for https://github.com/dotnet/corefx/issues/25620
