### ISSUE TITLE
Cannot connect to SQL Server from UWP: HResult=0x80131904

### ISSUE THREAD

**Issue by mahoekst** [dotnet/corefx#22725]
When trying to connect to SQL from UWP I get an exception. Same code works from a console. Tried local database and 1 in azure.

System.Data.SqlClient.SqlException occurred
  HResult=0x80131904
  Message=A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)
  Source=Core .Net SqlClient Data Provider
  StackTrace:
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at SQLTest.MainPage..ctor() in C:\Users\mahoekst\source\repos\SQLTest\SQLTest\MainPage.xaml.cs:line 34
   at SQLTest.SQLTest_XamlTypeInfo.XamlTypeInfoProvider.Activate_0_MainPage() in C:\Users\mahoekst\source\repos\SQLTest\SQLTest\obj\x86\Debug\XamlTypeInfo.g.cs:line 226
   at SQLTest.SQLTest_XamlTypeInfo.XamlUserType.ActivateInstance() in C:\Users\mahoekst\source\repos\SQLTest\SQLTest\obj\x86\Debug\XamlTypeInfo.g.cs:line 382
 
Inner Exception 1:
TypeLoadException: Could not load type 'System.Runtime.CompilerServices.IAsyncStateMachine' from assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
 
This is the code:
~~~~
           using (SqlConnection conn = new SqlConnection())
            {
 
                conn.ConnectionString = "Server=tcp:XXXX.database.windows.net,1433;Initial Catalog=AdventureWorks;Persist Security Info=False;User ID=XXXX;Password=XXX;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";
 
                conn.Open();
 
                SqlCommand command = new SqlCommand("SELECT * FROM SalesLT.Customer", conn);
 
                using (SqlDataReader reader = command.ExecuteReader())
                {
                    Console.WriteLine("FirstColumn\tSecond Column\t\tThird Column\t\tForth Column\t");
                    while (reader.Read())
                    {
                        Console.WriteLine(String.Format("{0} \t | {1} \t | {2} \t | {3}",
                            reader[0], reader[1], reader[2], reader[3]));
                    }
                }
                Console.WriteLine("Data displayed!");
 
            }
            Console.ReadLine();
~~~~

VS version: Version 15.4.0 Preview 1.0 [30319.200.d15prstg3]
UWP: 6.0.0-preview2-25512-03 or 6.0.0-preview2-25527-02
System.Data.SqlClient: 4.5.0-preview2-25527-02

**Comment by corivera** [comment]
@mahoekst This issue doesn't repro for me on the latest builds. Does it still repro for you?

I'm also not seeing the IAsyncStateMachine type being used anywhere in SqlClient. This is likely an issue in some underlying dependency.

**Comment by mahoekst** [comment]
Works for me on now
Microsoft.NETCore.UniversalWindowsPlatform 6.0.0-preview2-25601-02
System.Data.SqlClient 4.5.0-preview2-25602-01

**Comment by diverdan92** [comment]
+ @zamont FYI who I'm currently talking to

**Comment by zamont** [comment]
@corivera do you understand what changes in master could have enabled this scenario?

**Comment by corivera** [comment]
@zamont No idea. The TypeLoadException is coming from a type that is not used in any System.Data library.

**Comment by diverdan92** [comment]
+ @Josh<mailto:jfree@microsoft.com> FYI. This also appears to block SQLClient in UWP. It works in -preview2 package and not -preview1 package.

**Comment by zamont** [comment]
@diverdan92 and I found success with the following NuGet dependencies:

- Microsoft.NETCore.UniversalWindowsPlatform 6.0.0-preview1-25601-02 (This version contains SqlClient dependencies introduced by https://github.com/dotnet/corefx/commit/72adadb4b88ae9bfa5c149ceef17501aa48ae037)
- ~System.Data.SqlClient 4.5.0-preview2-25602-01~

According to https://github.com/dotnet/corefx/pull/22732, this change has not been applied to corefx:master, so soon there will be a breaking change where you may need to remove your System.Data.SqlClient NuGet dependency when using Microsoft.NETCore.UniversalWindowsPlatform 6.0.0-**preview2**-*

**Comment by hannespreishuber** [comment]
running on 25609-2, without SqlClient reference, SQL Server on local machine
Exception SQLClientException .. a network related... server not found....could not open connection
same code on same machine WPF works.
integrated Security=true

**Comment by hannespreishuber** [comment]
OK, runs now- you have to open tcp as protocol, firewall as app and restart SQL server service  (crosscheck telnet form a remote machine on 1433)
so my guess is, the network layer works kind a diffrent

**Comment by corivera** [comment]
@hannespreishuber SqlClient on UWP uses TCP by default when no protocol is specified in the connection string. Framework SqlClient also tries named pipes if TCP fails in that case, but we've found that named pipes isn't always supported on the platforms Core SqlClient runs on.

**Comment by hannespreishuber** [comment]
it seems Shared Memory lcp:(local) is not implemented?
