### ISSUE TITLE
System.Net.Tests.HttpWebRequestTest.GetResponseAsync_PostRequestStream_ContainsData failed with "System.Net.Http.WinHttpException : The operation timed out" in CI

### ISSUE THREAD

**Issue by KristinXie1** [dotnet/corefx#22849]
Failed test: System.Net.Tests.HttpWebRequestTest.GetResponseAsync_PostRequestStream_ContainsData

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug/124/testReport/System.Net.Tests/HttpWebRequestTest/GetResponseAsync_PostRequestStream_ContainsData_remoteServer__http___corefx_net_cloudapp_net_Echo_ashx_/

MESSAGE:
~~~
System.Net.WebException : An error occurred while sending the request. The operation timed out
  ---- System.Net.Http.HttpRequestException : An error occurred while sending the request.
  -------- System.Net.Http.WinHttpException : The operation timed out
~~~
STACK TRACE:
~~~
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) in D:\j\workspace\outerloop_net---dbe8fad8\src\System.Net.Requests\src\System\Net\HttpWebRequest.cs:line 1261 
at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar) in D:\j\workspace\outerloop_net---dbe8fad8\src\System.Net.Requests\src\System\Net\WebRequest.cs:line 550 
at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
at System.Net.Tests.HttpWebRequestTest.<GetResponseAsync_PostRequestStream_ContainsData>d__95.MoveNext() in D:\j\workspace\outerloop_net---dbe8fad8\src\System.Net.Requests\tests\HttpWebRequestTest.cs:line 995 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
----- Inner Stack Trace ----- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() 
at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext() in D:\j\workspace\outerloop_net---dbe8fad8\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 489 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() 
at System.Net.HttpWebRequest.<SendRequest>d__194.MoveNext() in D:\j\workspace\outerloop_net---dbe8fad8\src\System.Net.Requests\src\System\Net\HttpWebRequest.cs:line 1207 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) in D:\j\workspace\outerloop_net---dbe8fad8\src\System.Net.Requests\src\System\Net\HttpWebRequest.cs:line 1257 
----- Inner Stack Trace ----- 
at System.Environment.get_StackTrace() in D:\j\workspace\outerloop_net---dbe8fad8\src\System.Runtime.Extensions\src\System\Environment.cs:line 174 
at System.Runtime.ExceptionServices.ExceptionStackTrace.AddCurrentStack(Exception exception) in D:\j\workspace\outerloop_net---dbe8fad8\src\Common\src\System\Runtime\ExceptionServices\ExceptionStackTrace.cs:line 23 
at System.Net.Http.WinHttpException.CreateExceptionUsingError(Int32 error) in D:\j\workspace\outerloop_net---dbe8fad8\src\Common\src\System\Net\Http\WinHttpException.cs:line 51 
at System.Net.Http.WinHttpRequestCallback.OnRequestError(WinHttpRequestState state, WINHTTP_ASYNC_RESULT asyncResult) in D:\j\workspace\outerloop_net---dbe8fad8\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs:line 312 
at System.Net.Http.WinHttpRequestCallback.RequestCallback(IntPtr handle, WinHttpRequestState state, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength) in D:\j\workspace\outerloop_net---dbe8fad8\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs:line 104 
at System.Net.Http.WinHttpRequestCallback.WinHttpCallback(IntPtr handle, IntPtr context, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength) in D:\j\workspace\outerloop_net---dbe8fad8\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs:line 47 
--- End of stack trace from AddCurrentStack --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in D:\j\workspace\outerloop_net---dbe8fad8\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs:line 62 
at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext() in D:\j\workspace\outerloop_net---dbe8fad8\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 856
~~~

**Comment by davidsh** [comment]
Most likely an Azure Internet networking glitch.

**Comment by ViktorHofer** [comment]
Reopening, happens again: https://dev.azure.com/dnceng/public/_build/results?buildId=180050&view=ms.vss-test-web.build-test-results-tab&runId=4346600&resultId=252381

```
netcoreapp-Windows_NT-Debug-x64-Windows.10.Nano.Amd64.Open

System.Net.Tests.HttpWebRequestTest.GetResponseAsync_PostRequestStream_ContainsData(remoteServer: https://corefx-net-http2.azurewebsites.net/Echo.ashx)

System.Net.WebException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\r\n---- System.Net.Http.HttpRequestException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\r\n-------- System.Net.Sockets.SocketException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

 at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) in D:\a\1\s\src\System.Net.Requests\src\System\Net\HttpWebRequest.cs:line 1276
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar) in D:\a\1\s\src\System.Net.Requests\src\System\Net\WebRequest.cs:line 550
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\FutureFactory.cs:line 510
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Tests.HttpWebRequestTest.GetResponseAsync_PostRequestStream_ContainsData(Uri remoteServer) in D:\a\1\s\src\System.Net.Requests\tests\HttpWebRequestTest.cs:line 1223
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in D:\a\1\s\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\ConnectHelper.cs:line 84
   at System.Threading.Tasks.ValueTask`1.get_Result() in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs:line 759
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken) in D:\a\1\s\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 610
   at System.Threading.Tasks.ValueTask`1.get_Result() in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs:line 759
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\1\s\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 650
   at System.Threading.Tasks.ValueTask`1.get_Result() in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs:line 759
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\1\s\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 316
   at System.Threading.Tasks.ValueTask`1.get_Result() in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs:line 759
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in D:\a\1\s\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 508
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\1\s\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\RedirectHandler.cs:line 33
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in D:\a\1\s\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 528
   at System.Net.HttpWebRequest.SendRequest() in D:\a\1\s\src\System.Net.Requests\src\System\Net\HttpWebRequest.cs:line 1222
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) in D:\a\1\s\src\System.Net.Requests\src\System\Net\HttpWebRequest.cs:line 1272
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in D:\a\1\s\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\ConnectHelper.cs:line 65
```
