### ISSUE TITLE
System.Net.Http.Functional.Tests.ManagedHandler_DiagnosticsTest.SendAsync_ExpectedDiagnosticCancelledLogging failed with "System.Diagnostics.RemoteExecutorTestBase+RemoteInvokeHandle+RemoteExecutionException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#23209]
Failed test: System.Net.Http.Functional.Tests.ManagedHandler_DiagnosticsTest.SendAsync_ExpectedDiagnosticCancelledLogging 

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_release/134/testReport/System.Net.Http.Functional.Tests/ManagedHandler_DiagnosticsTest/SendAsync_ExpectedDiagnosticCancelledLogging/

Configuration: outerloop_netcoreapp_windows_nt_release

MESSAGE:
~~~
System.Diagnostics.RemoteExecutorTestBase+RemoteInvokeHandle+RemoteExecutionException : Remote process failed with an unhandled exception.
~~~
STACK TRACE:
~~~
Child exception: Xunit.Sdk.TrueException: Cancellation was not logged within 1 second timeout. Expected: True Actual: False 
at System.Net.Http.Functional.Tests.DiagnosticsTest.<>c.<SendAsync_ExpectedDiagnosticCancelledLogging>b__5_0() 
in D:\j\workspace\outerloop_net---7a39cc82\src\System.Net.Http\tests\FunctionalTests\DiagnosticsTests.cs:line 300 Child process: System.Net.Http.Functional.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb System.Net.Http.Functional.Tests.DiagnosticsTest+<>c Int32 <SendAsync_ExpectedDiagnosticCancelledLogging>b__5_0()
~~~

**Comment by davidsh** [comment]
>MESSAGE:
System.Diagnostics.RemoteExecutorTestBase+RemoteInvokeHandle+RemoteExecutionException : Remote process failed with an unhandled exception.
+++++++++++++++++++
STACK TRACE:
Child exception: Xunit.Sdk.TrueException: Cancellation was not logged within 1 second timeout. Expected: True Actual: False at System.Net.Http.Functional.Tests.DiagnosticsTest.<>c.<SendAsync_ExpectedDiagnosticCancelledLogging>b__5_0() in D:\j\workspace\outerloop_net---7a39cc82\src\System.Net.Http\tests\FunctionalTests\DiagnosticsTests.cs:line 300 Child process: System.Net.Http.Functional.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb System.Net.Http.Functional.Tests.DiagnosticsTest+<>c Int32 <SendAsync_ExpectedDiagnosticCancelledLogging>b__5_0()

**Comment by Jiayili1** [comment]
failed again: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170829.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.DiagnosticsTest~2FSendAsync_ExpectedDiagnosticCancelledActivityLogging

The test `System.Net.Http.Functional.Tests.DiagnosticsTest/SendAsync_ExpectedDiagnosticCancelledActivityLogging` has failed.

System.Diagnostics.RemoteExecutorTestBase+RemoteInvokeHandle+RemoteExecutionException : Remote process failed with an unhandled exception.

        Stack Trace:

        
    Child exception:
      System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module or one of its dependencies could not be found.
     (Exception from HRESULT: 0x8007007E)
       at Interop.Http.GetSslVersionDescription()
       at Interop.HttpInitializer..cctor() in /root/corefx-954865/src/Common/src/Interop/Unix/System.Net.Http.Native/Interop.Initialization.cs:line 27
       --- End of inner exception stack trace ---
       at Interop.HttpInitializer.Initialize() in /root/corefx-954865/src/Common/src/Interop/Unix/System.Net.Http.Native/Interop.Initialization.cs:line 47
       at Interop.Http..cctor() in /root/corefx-954865/src/Common/src/Interop/Unix/System.Net.Http.Native/Interop.Initialization.cs:line 19
       --- End of inner exception stack trace ---
       at Interop.Http.GetSupportedFeatures()
       at System.Net.Http.CurlHandler..cctor() in /root/corefx-954865/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.cs:line 164
       --- End of inner exception stack trace ---
       at System.Net.Http.CurlHandler..ctor() in /root/corefx-954865/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.cs:line 136
       at System.Net.Http.HttpClientHandler..ctor() in /root/corefx-954865/src/System.Net.Http/src/System/Net/Http/HttpClientHandler.Unix.cs:line 30
       at System.Net.Http.Functional.Tests.DiagnosticsTest.<>c.<SendAsync_ExpectedDiagnosticCancelledActivityLogging>b__12_0() in /root/corefx-954865/src/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs:line 606
    
    Child process:
      System.Net.Http.Functional.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb System.Net.Http.Functional.Tests.DiagnosticsTest+<>c Int32 <SendAsync_ExpectedDiagnosticCancelledActivityLogging>b__12_0()
    
    
Build : Master - 20170829.01 (Core Tests)
Failing configurations:
- RedHat.69.Amd64-x64
  - Release
  - Debug

**Comment by Jiayili1** [comment]
failed again: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170911.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_DiagnosticsTest~2FSendAsync_ExpectedDiagnosticCancelledLogging

**Comment by davidsh** [comment]
I am going to disable this test until it can be made more robust.  It is not a reliable test because cancellation cannot be guaranteed to occur with a certain time especially on a busy machine.

**Comment by Jiayili1** [comment]
failed again in CI: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/268/testReport/System.Net.Http.Functional.Tests/ManagedHandler_DiagnosticsTest/SendAsync_ExpectedDiagnosticCancelledActivityLogging/

**Comment by Jiayili1** [comment]
Following test failed again in 2.0.0 branch, detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170927.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.DiagnosticsTest~2FSendAsync_ExpectedDiagnosticCancelledLogging

The test `System.Net.Http.Functional.Tests.DiagnosticsTest/SendAsync_ExpectedDiagnosticCancelledLogging` has failed.

Assert.Equal() Failure
    Expected: 42
    Actual:   127

        Stack Trace:

           at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in /root/corefx/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs:line 208
Build : 2.0.0 - 20170927.01 (Core Tests)
Failing configurations:
- SLES.12.Amd64-x64
  - Release

**Comment by Jiayili1** [comment]
failed again in Master branch, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170928.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandler_DefaultProxyCredentials_Test~2FProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed(useProxy:%20True)

**Comment by Jiayili1** [comment]
failed again in master branch: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171023.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_DiagnosticsTest~2FSendAsync_ExpectedDiagnosticCancelledActivityLogging

**Comment by Jiayili1** [comment]
Now it failed with:

The test `System.Net.Http.Functional.Tests.DiagnosticsTest/SendAsync_ExpectedDiagnosticCancelledActivityLogging` has failed.

Exit code was 134 but it should have been 42
    Expected: True
    Actual:   False

        Stack Trace:

           at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in /root/corefx-1088759/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 191
       at System.Net.Http.Functional.Tests.DiagnosticsTest.SendAsync_ExpectedDiagnosticCancelledActivityLogging() in /root/corefx-1088759/src/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs:line 589
Build : Master - 20171026.01 (Core Tests)
Failing configurations:
- RedHat.73.Amd64-x64
  - Debug

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171026.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.DiagnosticsTest~2FSendAsync_ExpectedDiagnosticCancelledActivityLogging

**Comment by Sunny-pu** [comment]
failed again in master branch: 
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171108.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandler_DefaultProxyCredentials_Test~2FProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed(useProxy:%20True)

**Comment by karelz** [comment]
Deleting comments with ManagedHandler test failures to remove clutter.

**Comment by karelz** [comment]
History of failures updated in top post from official Helix runs

**Comment by Sunny-pu** [comment]
Following test failed again in Master branch, detail: 
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20180129.01/workItem/System.Data.SqlClient.Tests

The test System.Data.SqlClient.Tests/System.Data.SqlClient.Tests.DiagnosticTest has failed.
~~~
Message:
System.Diagnostics.RemoteExecutorTestBase+RemoteInvokeHandle+RemoteExecutionException : Remote process failed with an unhandled exception.

Stack Trace :
Child exception:
  Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at System.Data.SqlClient.Tests.DiagnosticTest.CollectStatisticsDiagnostics(Action`1 sqlOperation, Boolean enableServerLogging, String methodName)
   at System.Data.SqlClient.Tests.DiagnosticTest.<>c.<ConnectionOpenErrorTest>b__21_0()

Child process:
  System.Data.SqlClient.Tests, Version=4.3.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb System.Data.SqlClient.Tests.DiagnosticTest+<>c Int32 <ConnectionOpenErrorTest>b__21_0()

~~~

**Comment by karelz** [comment]
Related/dupe of #23771
