### ISSUE TITLE
FileLoadException when referencing log4net on Linux in netcoreapp2.0

### ISSUE THREAD

**Issue by markmcdowell** [dotnet/corefx#23283]
Looking at https://github.com/dotnet/corefx/issues/18088 I would expect to be able to reference log4net but I get downgrade warnings. So I updated the project as below:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeIdentifiers>win7-x64;centos.7-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.8" />
    <PackageReference Include="System.IO.FileSystem" Version="4.3.0" />    
    <PackageReference Include="System.Threading" Version="4.3.0" />    
    <PackageReference Include="System.Diagnostics.Debug" Version="4.3.0" />    
    <PackageReference Include="System.Runtime.Extensions" Version="4.3.0" />    
    <PackageReference Include="System.Runtime.InteropServices" Version="4.3.0" />    
    <PackageReference Include="System.Net.NameResolution" Version="4.3.0" />    
    <PackageReference Include="System.Net.Primitives" Version="4.3.0" />    
  </ItemGroup>

</Project>
```

Code is as simple as it could be.
```
using log4net;

namespace ConsoleApp2
{
    class Program
    {
        private static readonly ILog Log = LogManager.GetLogger(typeof(Program));

        static void Main(string[] args)
        {
            Log.Info("Hello World");
        }
    }
}
```

Publish to win7-x64 and run and I get a working app.

Publish to centos.7-x64 and I get the below exception.

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.IO.FileSystem, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Aborted
```

**Comment by davidfowl** [comment]
```
ConsoleApp28 (>= 1.0.0) -> log4net (>= 2.0.8) -> System.Net.Sockets (>= 4.1.0) -> System.Net.Primitives (>= 4.0.11) -> runtime.win.System.Net.Primitives (>= 4.3.0) -> System.Threading (>= 4.3.0) 
ConsoleApp28 (>= 1.0.0) -> log4net (>= 2.0.8) -> System.Threading (>= 4.0.11)	ConsoleApp28
```

@ericstj I thought we fixed the RID issues in 2.0?

**Comment by markmcdowell** [comment]
Ah I see, yes If I don't specify any `RuntimeIdentifier` it builds and runs.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>    
    <PackageReference Include="log4net" Version="2.0.8" />
  </ItemGroup>
  
</Project>
```

**Comment by ericstj** [comment]
@davidfowl we did fix them in the 2.0 packages.

In this case the library (log4Net) is referencing 1.0 packages.  Someone else brought in a 1.1 MS.NETCore.Targets package (which isn't in this log snippet).

This issue is exactly: https://github.com/dotnet/corefx/issues/18088

We fixed it by shipping a new version of Microsoft.NETCore.Targets that would strip out all the runtime.* RID-specific package references.

Unfortunately the workaround [didn't make it in](https://github.com/dotnet/core-setup/issues/2716) to the Microsoft.NETCore.App package, so you have to manually reference "Microsoft.NETCore.Targets": "2.0.0" package.

**Comment by markmcdowell** [comment]
Would this be the correct settings?

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeIdentifiers>centos.7-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.8" />
    <PackageReference Include="Microsoft.NETCore.Targets" Version="2.0.0" />
  </ItemGroup>

</Project>
```

With this the compiler doesn't complain anymore but at runtime I still have similar issues on linux.

This simple code:
```cs
using System;
using log4net;

namespace ConsoleApp1
{
    class Program
    {
        private static readonly ILog Log = LogManager.GetLogger(typeof(Program));

        static void Main(string[] args)
        {
            Console.WriteLine("Hellow");

            Log.Info("Hello World");
        }
    }
}
```

Results in:
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Console.get_Out()
   at System.Console.WriteLine(String value)
   at ConsoleApp1.Program.Main(String[] args)
Aborted
```

**Comment by ericstj** [comment]
Hmm, it works for me.  Did you re-restore after making your project changes?  What does dotnet --version say?  Can you make sure to delete your bin/publish folders?

**Comment by markmcdowell** [comment]
I created a brand new project just to be sure then built via Visual Studio and msbuild with the same results.

```
@ECHO off

SET BUILD_VERSION=1.0.0.0

SET MSBUILD="c:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/msbuild.exe"
SET VERSION=%BUILD_VERSION%
SET CONFIGURATION=Release
SET MSBUILD_FLAGS=/nologo /maxcpucount:1 /verbosity:minimal

@ECHO Cleaning...
%MSBUILD% ConsoleApp1.sln /verbosity:minimal /target:Clean 

@ECHO Restoring NuGet packages...
%MSBUILD% ConsoleApp1.sln /verbosity:minimal /target:Restore

@ECHO Building...
%MSBUILD% ConsoleApp1.sln /verbosity:minimal /target:Build

@ECHO Building...
%MSBUILD% ConsoleApp1.sln /verbosity:minimal /target:Publish /p:RuntimeIdentifier=centos.7-x64 /p:TargetFramework=netcoreapp2.0 /p:PublishDir="bin\Release\dist\centos7-x64"

PAUSE
```
I then zip and upload to the centos 7 box.

On my dev machine:
```bash
d:\dev\ConsoleApp1\bin\Release\dist>dotnet --version
2.0.0
```

```
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework
```

**Comment by ericstj** [comment]
Ok, I can repro it with that commandline but not with dotnet publish... Looking into what is different...

**Comment by markmcdowell** [comment]
yes! i just tried dotnet publish and that did work.

```
dotnet build -c Release
dotnet publish -c Release --self-contained -r centos.7-x64
```

**Comment by ericstj** [comment]
Yeah, I found the same.  Looking into the reason for the discrepancy.    Suspect some target execution order bug in the SDK /cc @dsplaisted @eerhardt

**Comment by ericstj** [comment]
It appears to actually be a bug in conflict resolution when run on desktop and examining a cross-gen'ed linux binary.  I'm looking into it some more and will file an issue on the SDK.

**Comment by markmcdowell** [comment]
Thanks v. much. I'll try updating my build server to run the dotnet publish instead of the msbuild one.
