### ISSUE TITLE
Could not load type 'Microsoft.SqlServer.Server.SqlContext' from assembly 'System.Data, Version=4.0.0.0

### ISSUE THREAD

**Issue by PraisyA** [dotnet/corefx#23292]
I am getting this exception when  i tried to restore the Data base using **c# , .Net core2 and VS2017 preview2 ,**
 here is the sample code 
SqlConnection sqlConnection = new SqlConnection(ConnectionString);
    // Error on the line below
    Microsoft.SqlServer.Management.Common.ServerConnection conn = new Microsoft.SqlServer.Management.Common.ServerConnection(sqlConnection);

but this is working in console application .  Did i miss anything ...

Thanks
Victor.A

**Comment by pjanotti** [comment]
@PraisyA what is the error? Can you get the callstack?

**Comment by PraisyA** [comment]
Hello @pjanotti 

 Here is the stack message 
`   at Microsoft.SqlServer.Management.Common.ConnectionManager.CallerHavePermissionToUseSQLCLR()
   at Microsoft.SqlServer.Management.Common.ConnectionManager..ctor(SqlConnection sqlConnectionObject)
   at Microsoft.SqlServer.Management.Common.ServerConnection..ctor(SqlConnection sqlConnection)
   `



Thanks
Victor.A

**Comment by weshaggard** [comment]
Can you tell us which library you are referencing? Where are the Microsoft.SqlServer.Management APIs coming from?

**Comment by weshaggard** [comment]
SqlContext doesn't look like a type that is ported to .NET Core yet and I'm guessing that the Microsoft.SqlServer.Management library is a .NET Framework compiled library which is why it is hitting this issue.

**Comment by PraisyA** [comment]
@weshaggard 
 when start working on this task  it does not find the Microsoft.SqlServer.Management library then 
I just install Microsoft.Sqlserver.Scripting using nuget packages (some one suggest me install this) , then it was added .  
![microsoftsqlserver2](https://user-images.githubusercontent.com/30825040/29376777-4d62fe04-82d7-11e7-97ce-7b05f7e85e58.PNG)


Thanks

**Comment by weshaggard** [comment]
Yes that is a library built against .NET Framework which is referencing types that don't exist in .NET Core. While we have done a lot of porting in .NET Core 2.0 the types this library needs aren't all present yet. So unfortunately this library will not run on .NET Core.

**Comment by danmosemsft** [comment]
@corivera perhaps it would be interesting to see how much it would take to get Microsoft.SqlServer.Scripting to run .. whether SqlContext is the tip of the iceberg.

**Comment by PraisyA** [comment]
@weshaggard 
So, can we expect this in  next release..?  if you not please suggest me is there any better way to do.

Thanks

**Comment by danmosemsft** [comment]
@PraisyA there is no plan to port this API although it may be the feature owners would welcome it should you wish to provide a port. That is @corivera 
As I mentioned there are likely other types the package needs that are missing. Possibly those could be added to.
As for what package you could use instead meantime, I cannot say.

**Comment by weshaggard** [comment]
I also don't know enough about this library to suggest a better way to do it on .NET Core.

**Comment by danmosemsft** [comment]
SqlContext port is in https://github.com/dotnet/corefx/issues/17126 
After that is done we can see whether tha'ts enough for Microsoft.SqlServer.Management.

**Comment by shueybubbles** [comment]
The NuGet package Microsoft.SqlServer.SqlManagementObjects has versions of the SMO binaries that target NetStandard 2.0.
