### ISSUE TITLE
Array bounds error with CryptoStream.Write using DESCryptoServiceProvider

### ISSUE THREAD

**Issue by DaveSlinn** [dotnet/corefx#23311]
We have a simple text decryption function that uses classes in System.Security.Cryptography that works fine when targeting the full framework but throws an ArgumentException `Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.` on the `CryptoStream.Write` method.

Here is the full extent of a console app recreating the error:

```c#
using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var textToDecrypt = "oZYdrxMbPKav5xewuT1PUw=="; // an encrypted form of "test string 1"
            var key = "Test Encryption Key";

            byte[] initializationVector = {
                0x12,
                0x34,
                0x56,
                0x78,
                0x90,
                0xab,
                0xcd,
                0xef
            };

            byte[] byKey = Encoding.UTF8.GetBytes(key.Substring(0, 8));
            DESCryptoServiceProvider des = new DESCryptoServiceProvider();
            inputByteArray = Convert.FromBase64String(textToDecrypt);
            MemoryStream ms = new MemoryStream();
            CryptoStream cs = new CryptoStream(ms, des.CreateDecryptor(byKey, initializationVector), CryptoStreamMode.Write);
            cs.Write(inputByteArray, 0, inputByteArray.Length); // <---  ERROR IS THROWN HERE
            cs.FlushFinalBlock();
            Encoding encoding = Encoding.UTF8;
            Console.WriteLine(encoding.GetString(ms.ToArray())); // <--- Expected to see "test string 1" in the console.
        }
    }
}
```

The inputByteArray contains 16 elements (0-15), the offset is 0 and the length is 16.  Not sure why I would get an index error here.

Here is the stack trace from the error:

```
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at Internal.NativeCrypto.CapiHelper.DecryptData(SafeKeyHandle hKey, Byte[] input, Int32 inputOffset, Int32 inputCount, Byte[] output, Int32 outputOffset, Int32 outputCount)
   at Internal.Cryptography.BasicSymmetricCipherCsp.Transform(Byte[] input, Int32 inputOffset, Int32 count, Byte[] output, Int32 outputOffset, Boolean isFinal)
   at Internal.Cryptography.BasicSymmetricCipherCsp.Transform(Byte[] input, Int32 inputOffset, Int32 count, Byte[] output, Int32 outputOffset)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[] outputBuffer, Int32 outputOffset)
   at Internal.Cryptography.UniversalCryptoTransform.TransformBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[] outputBuffer, Int32 outputOffset)
   at System.Security.Cryptography.CryptoStream.<WriteAsyncCore>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Security.Cryptography.CryptoStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\dslinn\Desktop\ConsoleApp1\ConsoleApp1\Program.cs:line 32
```

[EDIT] Add C# syntax highlight by @karelz

**Comment by danmosemsft** [comment]
Marking 2.0 speculatively since this soudns like a compat issue.

**Comment by karelz** [comment]
@bartonjs can you please check importance?

**Comment by bartonjs** [comment]
Looks like the problem happens via CryptoStream when a CAPI ICryptoTransform is used with a multiple-block input and a removable padding type.

Somewhere in the middle it decides it needs a buffer to hold two blocks of output, then the transform chain decides that only one block will be processed, but the CAPI transform expects to completely fill the output buffer.

That should be easy enough to come up with a test (output buffer being too big) and feel comfortable with the fix (which I think I understand where it's broken, and why).  We may want to port to 2.0.x/servicing for compat mitigation.

@DaveSlinn There are probably a couple of workaround here:

* Only write one block at a time to cs.Write when decrypting
* Wrap the ICryptoTransform in another ICryptoTransform which reports false for CanTransformMultipleBlocks
* Switch from `new DESCryptoServiceProvider()` to `DES.Create()`

Personally, I'd recommend the last option.

**Comment by bartonjs** [comment]
```C#
        [Fact]
        public static void MultipleBlockDecryptTransform()
        {
            const string expectedOutput = "This is a test";

            byte[] iv = "0123456789ABCDEF".HexToByteArray();
            byte[] outputBytes = new byte[iv.Length * 2];
            byte[] input = "CB67F70BA8B50EED2C0691298988865F".HexToByteArray();
            int outputOffset = 0;

            using (DES des = DESFactory.Create())
            using (ICryptoTransform xform = des.CreateDecryptor(KnownGoodKey, iv))
            {
                outputOffset += xform.TransformBlock(input, 0, input.Length, outputBytes, outputOffset);
                byte[] overflow = xform.TransformFinalBlock(Array.Empty<byte>(), 0, 0);
                Buffer.BlockCopy(overflow, 0, outputBytes, outputOffset, overflow.Length);
                outputOffset += overflow.Length;
            }

            string decrypted = Encoding.ASCII.GetString(outputBytes, 0, outputOffset);
            Assert.Equal(expectedOutput, decrypted);
        }
```

Same exception when DESFactory.Create() returns a DESCryptoServiceProvider.  Found and fixed.  (Now to repeat it for the other symmetric algorithms)

**Comment by DaveSlinn** [comment]
@bartonjs Thanks very much, I will take your advice and go with option 3 (extra kudos for updating the sample with that approach).

**Comment by bartonjs** [comment]
Reopening so it's tracked as a 2.0.x porting item.

**Comment by Petermarcu** [comment]
Are we aiming to get this into a servicing release? If so, which one? I haven't seen the approval process started on this one.

**Comment by bartonjs** [comment]
Closing this since it has merged into the release branch.
