### ISSUE TITLE
Microsoft.CSharp bug when dynamically invoking a property of a F# Record with generic union input

### ISSUE THREAD

**Issue by Zaid-Ajaj** [dotnet/corefx#23387]
### Short description

Microsoft.CSharp bug when dynamically invoking a property (as a function) of a F# Record with generic union input. This used to work in "classic" .NET (net45)

### Details
While porting [my library](https://github.com/Zaid-Ajaj/Fable.Remoting) from full classic .NET (net45) to .NET Core 2.0 I have come across a weird bug that occurs in Microsoft.CSharp when trying to invoke properties of a F# record dynamically from C# at runtime. 

I wrote [this static class](https://github.com/Zaid-Ajaj/Fable.Remoting/blob/master/Fable.Remoting.Reflection/FSharpRecord.cs) in C# to do this task and it worked just fine for all kinds of inputs.
```cs
using System.Reflection;
using Microsoft.CSharp; 
// etc...

public static class FSharpRecord
{
    static B Pipe<A, B>(this A x, Func<A, B> f) => f(x);

    public static dynamic Invoke(string methodName, object implementation, object arg, bool hasArg)
    {
        return implementation
                     .GetType()
                     .GetProperty(methodName)
                     .GetValue(implementation, null)
                     .Pipe((dynamic fsFunc) => hasArg ? fsFunc.Invoke((dynamic)arg) : fsFunc.Invoke(null));
    }
}
```
This class works very well with F# records and I have tested it before with net45 but the tests fail when the input is a generic union type from F# such as:
```fs
type Maybe<'t> = 
    | Just 't
    | Nothing
```
Here is my test suite from [this file](https://github.com/Zaid-Ajaj/Fable.Remoting/blob/master/Fable.Remoting.Server.Tests/ServerDynamicInvokeTests.fs#L18):

Given the record type:
```fs
type TestRec = { 
    simpleMethod : string -> int
    listsMethod : int list -> int
    genericUnion: Maybe<int> -> int
}
```
And these tests (written with Expecto)
```fs
let fsharpRecordTests = 
    let invoke (methodName: string) (record: obj) (input: obj) (hasArg: bool) =
        FSharpRecord.Invoke(methodName, record, input, hasArg) 

    let testRec = { 
        genericUnion = function Just x -> x | _ -> 0 
        simpleMethod = fun input -> input.Length
        listsMethod = fun xs -> Seq.sum xs
    }

    testList "FSharpRecord tests" [
        testCase "Invoking listsMethod" <| fun () ->
            let input = [1 .. 10]
            let output = invoke "listsMethod" testRec (box input) true
            equal 55 (unbox<int> output)

        testCase "Invoking simpleMethod" <| fun () ->
            let input = "hello"
            let output = invoke "simpleMethod" testRec (box input) true
            equal 5 (unbox<int> output)

        testCase "Invkoing genericUnion on record dynamically works" <| fun () ->
            let input = Just 5
            let output = invoke "genericUnion" testRec (box input) true
            equal 5 (unbox<int> output)
    ]
```
The test cases "Invoking simpleMethod" and "Invoking listsMethod" do pass but the last test case with the generic union input fails, here is the test log:
```
cmd /C dotnet Fable.Remoting.Server.Tests\bin\MCD\Release\netcoreapp2.\Fable.Remoting.Server.Tests.dll
[08:02:18 INF] EXPECTO? Running tests... <Expecto>
[08:02:18 DBG] FSharpRecord tests/Invoking listsMethod starting... <Expecto>
[08:02:19 DBG] FSharpRecord tests/Invoking listsMethod passed in 00:00:00.6730000. <Expecto>
[08:02:19 DBG] FSharpRecord tests/Invoking simpleMethod starting... <Expecto>
[08:02:19 DBG] FSharpRecord tests/Invoking simpleMethod passed in 00:00:00.0100000. <Expecto>
[08:02:19 DBG] FSharpRecord tests/Invkoing genericUnion on record dynamically works starting... <Expecto>
[08:02:19 ERR] FSharpRecord tests/Invkoing genericUnion on record dynamically works errored in 00:00:00.0190000 <Expecto>
System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.CSharp.RuntimeBinder.Syntax.NameTable.Add(String key, Int32 length)
   at Microsoft.CSharp.RuntimeBinder.Syntax.NameManager.Add(String key, Int32 length)
   at Microsoft.CSharp.RuntimeBinder.SymbolTable.GetName(Type type)
   at Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(Type originalType)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.GetArgumentType(ICSharpBinder p, CSharpArgumentInfo argInfo, Expression param, DynamicMetaObject arg, Int32 index)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateArgumentArray(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(DynamicMetaObjectBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
   at Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(DynamicMetaObjectBinder action, RuntimeBinder binder, DynamicMetaObject[] args, IEnumerable`1 arginfos, DynamicMetaObject onBindingError)
   at Microsoft.CSharp.RuntimeBinder.CSharpInvokeMemberBinder.FallbackInvokeMember(DynamicMetaObject target, DynamicMetaObject[] args, DynamicMetaObject errorSuggestion)
   at System.Dynamic.DynamicMetaObject.BindInvokeMember(InvokeMemberBinder binder, DynamicMetaObject[] args)
   at System.Dynamic.InvokeMemberBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at ServerDynamicInvokeTests.fsharpRecordTests@40-2.Invoke(Unit unitVar0) in C:\Projects\Fable.Remoting\Fable.Remoting.Server.Tests\ServerDynamicInvokeTests.fs:line 41
   at Expecto.Impl.execTestAsync@859-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
[08:02:20 INF] EXPECTO! 3 tests run in 00:00:01.5915904 - 2 passed, 0 ignored, 0 failed, 1 errored.  <Expecto>
```
### To reproduce the issue
```
git clone https://github.com/Zaid-Ajaj/Fable.Remoting.git RemotingRepo
cd RemotingRepo
.paket/paket.exe install
# if windows
build RestoreBuildRunServerTests
# if linux
packages/FAKE/tools/Fake.exe build.fsx RestoreBuildRunServerTests
```

**Comment by JonHanna** [comment]
Could you build corefx from the repository, and try it against that? This looks like a duplicate of  #21689 which is fixed in the repo.

**Comment by Zaid-Ajaj** [comment]
Will try that ASAP and report back, thanks for quick response!

**Comment by karelz** [comment]
Or you can just dogfood daily build: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md

**Comment by jbtule** [comment]
@karelz I tried to follow those instructions and the "latest download" zip file was pre-2.0.0 RTM.

**Comment by JonHanna** [comment]
@Zaid-Ajaj the fix for what I suspect was the cause of this shipped with 2.0.3. Can you confirm that it fixes your issue?

**Comment by JonHanna** [comment]
@Zaid-Ajaj ping?

**Comment by Zaid-Ajaj** [comment]
@JonHanna Sorry for late answer! Yes I have checked and it seems that the issue is fixed. Thanks a lot for your time :smile:
