### ISSUE TITLE
Argument out of range exception on bind with `dynamic` keyword in coreapp2.0

### ISSUE THREAD

**Issue by jbtule** [dotnet/corefx#23399]
This is a regression and it does not occur in .net 4.6.2 or .net core 1.0 & 1.1

I've been able to replicate this error when there is a nested type inside of a generic type. 
```
    public class GenericType<T>
    {
        public class InnerClass
        {
            public string Go() => "Should Work!";
        }
    }
```
And you try to use dynamic invocation on a member or on the object itself of the nested type.
```
     dynamic keyword = new GenericType<String>.InnerClass();
     string result = keyword.Go();
     Assert.Equal("Should Work!", result);
```
It throws a `System.ArgumentOutOfRangeException : Length cannot be less than zero.
Parameter name: length`

```
at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.CSharp.RuntimeBinder.Syntax.NameTable.Add(String key, Int32 length)
   at Microsoft.CSharp.RuntimeBinder.Syntax.NameManager.Add(String key, Int32 length)
   at Microsoft.CSharp.RuntimeBinder.SymbolTable.GetName(Type type)
   at Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(Type originalType)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.GetArgumentType(ICSharpBinder p, CSharpArgumentInfo argInfo, Expression param, DynamicMetaObject arg, Int32 index)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateArgumentArray(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(DynamicMetaObjectBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
   at Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(DynamicMetaObjectBinder action, RuntimeBinder binder, DynamicMetaObject[] args, IEnumerable`1 arginfos, DynamicMetaObject onBindingError)
   at Microsoft.CSharp.RuntimeBinder.CSharpInvokeMemberBinder.FallbackInvokeMember(DynamicMetaObject target, DynamicMetaObject[] args, DynamicMetaObject errorSuggestion)
   at System.Dynamic.DynamicMetaObject.BindInvokeMember(InvokeMemberBinder binder, DynamicMetaObject[] args)
   at System.Dynamic.InvokeMemberBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at DynamicKeywordComplexTypesBugCore2_0.UnitTest1.Test1_NETCOREAPP2_0() in C:\projects\dynamickeywordcomplextypesbugcore2-0\DynamicKeywordComplexTypesBugCore2_0\UnitTest1.cs:line 30
```

Sample Project
https://github.com/jbtule/DynamicKeywordComplexTypesBugCore2_0
Demonstration of Tests Passing on older core and failing on 2.0
https://ci.appveyor.com/project/jbtule/dynamickeywordcomplextypesbugcore2-0/build/1.0.2

**Comment by stephentoub** [comment]
cc: @VSadov, @JonHanna

**Comment by jbtule** [comment]
Whoops this is a duplicate of #21689
