### ISSUE TITLE
 System.Net.Tests.WebProxyTest/WebProxy_BypassOnLocal_MatchesExpected failure on SUSE

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#23441]
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Frelease~2Fuwp6.0~2F/test~2Ffunctional~2Fcli~2F/f902382494decbafaa7eefe4935d2a074f926d15/workItem/System.Net.WebProxy.Tests/analysis/xunit/System.Net.Tests.WebProxyTest~2FWebProxy_BypassOnLocal_MatchesExpected

Unhandled Exception of Type System.Net.Internals.SocketExceptionFactory+ExtendedSocketException
Message :
`System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address`

Stack Trace:
```
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6) in /mnt/j/workspace/dotnet_corefx/release_uwp6.0/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 46
   at System.Net.Dns.ResolveCallback(Object context) in /mnt/j/workspace/dotnet_corefx/release_uwp6.0/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 290
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) in /mnt/j/workspace/dotnet_corefx/release_uwp6.0/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 420
   at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) in /mnt/j/workspace/dotnet_corefx/release_uwp6.0/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 562
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Tests.WebProxyTest.<BypassOnLocal_MemberData>d__10.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext() in /mnt/j/workspace/dotnet_corefx/release_uwp6.0/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Linq/src/System/Linq/Select.cs:line 129
```

**Comment by davidsh** [comment]
This on linux.  Assigning to @Priya91

**Comment by Priya91** [comment]
This test is similar to an already failing test case in Dns, where Dns.GetHostName() on unix sometimes returns host not found error, if all the machine discovery settings on the local network is turned off. So doing Dns.GetHostEntry*(Dns.GetHostName()) is sometimes expected to have this failure, and WebProxy is using the same pattern. This was already investigated in this commit [here](https://github.com/dotnet/corefx/commit/d06134f84bd45d2e503b8e0cd4e4ffb8fa04770a)

**Comment by davidsh** [comment]
> if all the machine discovery settings on the local network is turned off.

Does this mean this is a test bug and the test needs to be fixed? Or is this a product bug that needs to be fixed?  

Why would "machine discovery settings" be turned off?  Is that a normal *Nix thing to do on a machine? How can we ensure that test machines (especially CI machines) are properly configured and don't "turn off" those settings?

cc: @karelz

**Comment by karelz** [comment]
I am also worried about external contributors. Unless we have this step in "how to setup your Linux machine", we need to make our tests resilient to the failure - .e.g somehow detect the situation and ignore error / rerun.
@Priya91 does it sound reasonable or did I miss some point?
