### ISSUE TITLE
Merge_Ordered_Pipelining tests fail on 16 proc machine?

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#2345]
Four of the PLINQ tests fail for me, on Windows, in a deterministic fashion.  The test cases in question are all of the iterations of Merge_Ordered_Pipelining for the "ThrowOnEnumeration 16" case.  I get the following error (from the xUnit log):

```
        <failure exception-type="System.AggregateException">
          <message><![CDATA[System.AggregateException : One or more errors occurred.
---- Test.DeliberateTestException : Exception of type 'Test.DeliberateTestException' was thrown.]]></message>
          <stack-trace><![CDATA[   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Scheduling\QueryTaskGroupState.cs:line 131
   at System.Linq.Parallel.OrderPreservingSpoolingTask`2.Spool(QueryTaskGroupState groupState, PartitionedStream`2 partitions, Shared`1 results, TaskScheduler taskScheduler) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Scheduling\OrderPreservingSpoolingTask.cs:line 122
   at System.Linq.Parallel.OrderPreservingMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute() in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Merging\OrderPreservingMergeHelper.cs:line 60
   at System.Linq.Parallel.MergeExecutor`1.Execute() in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Merging\MergeExecutor.cs:line 102
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Merging\MergeExecutor.cs:line 91
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\PartitionedStreamMerger.cs:line 60
   at System.Linq.Parallel.FirstQueryOperator`1.WrapHelper[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, QuerySettings settings) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Unary\FirstQueryOperator.cs:line 89
   at System.Linq.Parallel.FirstQueryOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Unary\FirstQueryOperator.cs:line 66
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\UnaryQueryOperator.cs:line 160
   at System.Linq.Parallel.SelectQueryOperator`2.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Unary\SelectQueryOperator.cs:line 58
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\UnaryQueryOperator.cs:line 160
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\ScanQueryOperator.cs:line 136
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\UnaryQueryOperator.cs:line 129
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\UnaryQueryOperator.cs:line 129
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\QueryOperator.cs:line 163
   at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery() in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\QueryOpeningEnumerator.cs:line 163
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext() in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\QueryOpeningEnumerator.cs:line 107
   at System.Linq.ParallelEnumerable.GetOneWithPossibleDefault[TSource](QueryOperator`1 queryOp, Boolean throwIfTwo, Boolean defaultIfEmpty) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\ParallelEnumerable.cs:line 5393
   at System.Linq.ParallelEnumerable.First[TSource](ParallelQuery`1 source) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\ParallelEnumerable.cs:line 5469
   at Test.ExchangeTests.Merge_Ordered_Pipelining(Labeled`1 labeled, Int32 count, ParallelMergeOptions options) in d:\git\corefx\src\System.Linq.Parallel\tests\ExchangeTests.cs:line 140
----- Inner Stack Trace -----
   at Test.Enumerables`1.<>c__DisplayClass1.<ThrowOnEnumeration>b__0(Int32 i) in d:\git\corefx\src\System.Linq.Parallel\tests\Helpers\Enumerables.cs:line 29
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Parallel.PartitionedDataSource`1.ContiguousChunkLazyEnumerator.MoveNext(T& currentElement, Int32& currentKey) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Partitioning\PartitionedDataSource.cs:line 681
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Unary\SelectQueryOperator.cs:line 117
   at System.Linq.Parallel.FirstQueryOperator`1.FirstQueryOperatorEnumerator`1.MoveNext(TSource& currentElement, Int32& currentKey) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Unary\FirstQueryOperator.cs:line 174
   at System.Linq.Parallel.SortHelper`2.BuildKeysFromSource(GrowingArray`1& keys, List`1& values) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Utils\Sorting.cs:line 233
   at System.Linq.Parallel.SortHelper`2.Sort() in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Utils\Sorting.cs:line 196
   at System.Linq.Parallel.OrderPreservingSpoolingTask`2.SpoolingWork() in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Scheduling\OrderPreservingSpoolingTask.cs:line 136
   at System.Linq.Parallel.SpoolingTaskBase.Work() in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Scheduling\SpoolingTaskBase.cs:line 66
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Scheduling\QueryTask.cs:line 99
   at System.Linq.Parallel.QueryTask.<.cctor>b__0(Object o) in d:\git\corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\Scheduling\QueryTask.cs:line 74
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()]]></stack-trace>
        </failure>
```

@stephentoub thinks this may be due to the fact that I have 16 cores:
> I think the issue is that it's expecting that First() won't execute up to the iteration that'll throw an exception, but it's testing with 16 elements, so if you have a box with 16 cores, it's very likely each core will process an element concurrently, one of them will throw, and that'll cause the whole query to fail.

What do you think @clockwork-muse?

**Comment by Clockwork-Muse** [comment]
... Yeah, that's my bad.  The test originally had it out to 1mil elements or something, which seemed extreme (and somewhat missing the point), so I shortened it.  Of course this worked fine on my machine, which is only 4 core (-_-)...

The real problem is it's supposed to be about internal behavior which we can't observe externally.  I waffled a bit about removing most of those types of tests, but felt it was important to leave the assumptions documented.

@stephentoub - any other comments here?  I can certainly increase the count, but that feels wrong.  Maybe increasing the count based on `Environment.ProcessorCount`?

**Comment by stephentoub** [comment]
Can you remind me what this test is trying to verify? Is the goal to verify that we don't iterate through more of the source than we need to? Rather than increasing the count, how about keeping the count low and just setting the DOP > count?

**Comment by Clockwork-Muse** [comment]
@stephentoub -  probably you mean less-than?
I think that's what it was going for, yes.  I initially didn't add the DOP as I felt it might have been changing the test too much...
However, I just looked back at the original, and for whatever reason it's calling `Enumerable.First`, and not the parallel version.  Not sure how I missed that.  Doesn't seem to affect the results, though.

I can certainly add the DOP, at the moment the plan is for my open PR.

**Comment by stephentoub** [comment]
> probably you mean less-than

Oops, yes, typo.
