### ISSUE TITLE
CopyFromScreen_ValidRange_AffectsGraphics failed in netfx CI

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#23650]
```
System.Drawing.Tests.GraphicsTests.CopyFromScreen_ValidRange_AffectsGraphics(sourceX: 1, sourceY: 1, destinationX: 2, destinationY: 2, width: 3, height: 3) [FAIL]
20:39:03         System.ComponentModel.Win32Exception : The handle is invalid
20:39:03         Stack Trace:
20:39:03              at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize, CopyPixelOperation copyPixelOperation)
20:39:03              at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize)
```

I believe these tests are invalid, given that they are failing against the .NET Framework. We should give them some scrutiny, and potentially remove them.

**Comment by danmosemsft** [comment]
@mellinoe @safern can one of you please go ahead and dsiable these also? It's breaking CI -- 

https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/2738/consoleText

**Comment by mellinoe** [comment]
This one also failed in a PR of mine, also in netfx: CopyFromScreen_OutOfRange_DoesNotAffectGraphics

We should probably disable all of these CopyFromScreen tests.
