### ISSUE TITLE
BasicEventSourceTests.TestEventCounter.Test_Write_Metric_EventListener fails on NetFx when running on netstandard support libs.

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#23661]
Sync to eade3b36725c8d463a40589ff749af5bb0cab8f4

build -targetGroup:netfx
cd src\System.Diagnostics.Tracing\tests
msbuild /p:TargetGroup=netfx /t:BuildAndTest

Expect: pass 
Actual: failure with following
```
        FAILURE IN SUBTEST: "EventCounter: Log 1 event, explicit poll at end"
        ************* EXCEPTION INFO ***************
        Xunit.Sdk.EqualException: Assert.Equal() Failure
        Expected: 4
        Actual:   0
           at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:line 35
           at BasicEventSourceTests.TestEventCounter.<>c.<Test_Write_Metric>b__2_1(List`1 evts) in D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestEventCounter.cs:line 84
           at BasicEventSourceTests.EventTestHarness.<>c__DisplayClass2_0.<RunTests>b__0(Event data) in D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\EventTestHarness.cs:line 72
           at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
        *********** END EXCEPTION INFO *************
        ************* LOGGING MESSAGES ***************
        38:55.738 : STARTING Sub-Test EventCounter: Log 1 event, explicit poll at end
        38:55.738 : Sending command MyEventSource to EventSource Enable Options <Options Keywords='ffffffffffffffff' Level'Verbose' ArgsCount='1'
        38:55.739 : Sending command MyEventSource to EventSource Enable Options <Options Keywords='ffffffffffffffff' Level'Verbose' ArgsCount='1'
        38:55.857 : Exception thrown: Assert.Equal() Failure
        Expected: 4
        Actual:   0
        
        *********** END LOGGING MESSAGES *************
        Version of Runtime 4.0.30319.42000
        Version of OS Microsoft Windows NT 6.2.9200.0
        **********************************************
        
        ---- Assert.Equal() Failure
        Expected: 4
        Actual:   0
        Stack Trace:
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\EventTestHarness.cs(163,0): at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestEventCounter.cs(266,0): at BasicEventSourceTests.TestEventCounter.Test_Write_Metric(Listener listener)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestEventCounter.cs(50,0): at BasicEventSourceTests.TestEventCounter.Test_Write_Metric_EventListener()
          ----- Inner Stack Trace -----
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestEventCounter.cs(84,0): at BasicEventSourceTests.TestEventCounter.<>c.<Test_Write_Metric>b__2_1(List`1 evts)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\EventTestHarness.cs(72,0): at BasicEventSourceTests.EventTestHarness.<>c__DisplayClass2_0.<RunTests>b__0(Event data)
             at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
```

I suspect that this is due to the test expecting behavior post fixes made in master after the release/2.0.0 fork.  Any fixes made to the netfx build here were actually dead-ends since we don't intend to ship any of the dlls that make up netstandard.dll as out of band after release/2.0.0.

Please evaluate this issue to determine if we need to either a) fix the test, or b) port changes to servicing/desktop.

Related, but likely wrong issue: https://github.com/dotnet/corefx/issues/22791

/cc @brianrob @vancem

**Comment by brianrob** [comment]
This is a desktop bug, moving to future.

**Comment by stephentoub** [comment]
Test depends on newer behavior than in netfx, and the test is annotated to be skipped on netfx.  Closing.
