### ISSUE TITLE
System.Transactions.Tests.CloneTxTests.Run failed in netfx CI

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#23760]
```
    Starting:    System.Transactions.Local.Tests
      System.Transactions.Tests.CloneTxTests.Run(cloneType: RollbackDependent, isoLevel: Chaos, forcePromote: False, completeClone: False, expectedStatus: Aborted) [FAIL]
        Assert.Null() Failure
        Expected: (null)
        Actual:   System.TimeoutException: Transaction Timeout
        Stack Trace:
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Transactions.Local\tests\CloneTxTests.cs(147,0): at System.Transactions.Tests.CloneTxTests.Run(CloneType cloneType, IsolationLevel isoLevel, Boolean forcePromote, Boolean completeClone, TransactionStatus expectedStatus)
```

https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/2876/consoleText

**Comment by stephentoub** [comment]
Failed again here:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/3574/consoleText
```
Discovering: System.Transactions.Local.Tests
    Discovered:  System.Transactions.Local.Tests
    Starting:    System.Transactions.Local.Tests
      System.Transactions.Tests.CloneTxTests.Run(cloneType: RollbackDependent, isoLevel: Chaos, forcePromote: False, completeClone: False, expectedStatus: Aborted) [FAIL]
        Assert.Null() Failure
        Expected: (null)
        Actual:   System.TimeoutException: Transaction Timeout
        Stack Trace:
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Transactions.Local\tests\CloneTxTests.cs(147,0): at System.Transactions.Tests.CloneTxTests.Run(CloneType cloneType, IsolationLevel isoLevel, Boolean forcePromote, Boolean completeClone, TransactionStatus expectedStatus)
```

**Comment by stephentoub** [comment]
Failed again here:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/5931/consoleText

**Comment by stephentoub** [comment]
Failed again here:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/8116/consoleText

**Comment by StephenBonikowsky** [comment]
The test seems to be running fine now.
