### ISSUE TITLE
Add_ReachedMaxCountWithExpiredCookies_Added failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23799]
```
Unhandled Exception of Type Xunit.Sdk.EqualException
Message :
Assert.Equal() Failure
Expected: 0
Actual:   1
Stack Trace :
   at System.Net.Primitives.Unit.Tests.CookieContainerTest.<Add_ReachedMaxCountWithExpiredCookies_Added>d__38.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.Primitives/tests/UnitTests/CookieContainerTest.cs:line 423
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/86ca19c92fccec47994700d09738fc4051fd18ab/workItem/System.Net.Primitives.UnitTests.Tests/analysis/xunit/System.Net.Primitives.Unit.Tests.CookieContainerTest~2FAdd_ReachedMaxCountWithExpiredCookies_Added

**Comment by stephentoub** [comment]
Failed again here:
```
Unhandled Exception of Type Xunit.Sdk.EqualException
Message :
Assert.Equal() Failure
Expected: 0
Actual:   1
Stack Trace :
   at System.Net.Primitives.Unit.Tests.CookieContainerTest.<Add_ReachedMaxCountWithExpiredCookies_Added>d__38.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Primitives/tests/UnitTests/CookieContainerTest.cs:line 422
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by Priya91** [comment]
Failed here again,

https://mc.dot.net/#/user/Priya91/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/9406156a2d4305c8006d3cbda88e85351bd2c385/workItem/System.Net.Primitives.UnitTests.Tests

in PR #25261

**Comment by caesar1995** [comment]
It's a dup of #19994: set the cookie.Expires to 1 second, wait for 2 seconds to let it expires. Then find out the cookie not removed from CookieContainer yet, which causes the Assertion failure.

Only fails on Unix distro.
