### ISSUE TITLE
Several StackFrameTests now failing with line number differences on netfx

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23796]
```
System.Diagnostics.Tests.StackFrameTests.Ctor_FNeedFileInfo(fNeedFileInfo: True) [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   7
        Stack Trace:
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(166,0): at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(34,0): at System.Diagnostics.Tests.StackFrameTests.Ctor_FNeedFileInfo(Boolean fNeedFileInfo)
      System.Diagnostics.Tests.StackFrameTests.Ctor_FNeedFileInfo(fNeedFileInfo: False) [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   7
        Stack Trace:
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(166,0): at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(34,0): at System.Diagnostics.Tests.StackFrameTests.Ctor_FNeedFileInfo(Boolean fNeedFileInfo)
      System.Diagnostics.Tests.StackFrameTests.Ctor_SkipFrames_FNeedFileInfo(skipFrames: 0, fNeedFileInfo: True) [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   8
        Stack Trace:
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(166,0): at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(57,0): at System.Diagnostics.Tests.StackFrameTests.Ctor_SkipFrames_FNeedFileInfo(Int32 skipFrames, Boolean fNeedFileInfo)
      System.Diagnostics.Tests.StackFrameTests.Ctor_SkipFrames_FNeedFileInfo(skipFrames: 0, fNeedFileInfo: False) [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   8
        Stack Trace:
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(166,0): at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(57,0): at System.Diagnostics.Tests.StackFrameTests.Ctor_SkipFrames_FNeedFileInfo(Int32 skipFrames, Boolean fNeedFileInfo)
```

**Comment by danmosemsft** [comment]
@mikem8361 this has begun failing possibly due to a desktop framework update:
``` C#
#if !DEBUG
            else if ((!PlatformDetection.IsFullFramework && isFileConstructor) || (PlatformDetection.IsFullFramework && !isFileConstructor && !isCurrentFrame && skipFrames == 0))
            {
                Assert.Equal(0, stackFrame.GetILOffset());
            }
#endif
```

**Comment by mikem8361** [comment]
@noahfalk, @lt72 Adding Noah and Lorenzo since I don't know about any changes or work on the desktop framework.

**Comment by lt72** [comment]
@mikem8361: can you please sync with Stephen to clarify whether this is a .Net Core issue only? I also do not understand how the desktop changes affect the baseline of the test or the correctness. Maybe just verifying that the current behavior is OK would enable Stephen to reset the baseline, if that is the issue...
@stephentoub FYI

**Comment by danmosemsft** [comment]
@lt72 these are tests stored in CoreFX that run against Desktop as well as CoreFX. (We do this to help catch breaking changes)

https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.StackTrace/tests/StackFrameTests.cs#L166

The only moving part here should be Desktop, eg., it got serviced. Tests have not changed, and the tests pass on Core. If you can suggest the correct fix, we can reenable the tests...

**Comment by stephentoub** [comment]
> can you please sync with Stephen to clarify whether this is a .Net Core issue only?

As @danmosemsft points out, the test in question already was verifying different behaviors for desktop and core.  For the same situation, the test was verifying that stackFrame.GetILOffset() would return 0 on desktop and > 0 on core, and it appears desktop is now returning > 0.

**Comment by joperezr** [comment]
As @stephentoub and @danmosemsft point out, this is a test issue.
Next steps:

- Modify tests so that newer netfx behavior expectations match netcoreapp.
- Run tests and make sure they pass against different versions of netfx.

**Comment by danmosemsft** [comment]
New failure modes
```
  Executing in D:\j\workspace\windows-TGrou---2a8f9c29\bin\tests\System.ComponentModel.TypeConverter.Performance.Tests\netfx-Windows_NT-Release-x86\ 
  Running tests... Start time: 17:13:14.55
        Assert.Null() Failure
  xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
        Expected: (null)
        Actual:   StackFrame[] [InvokeException at offset 19 in file:line:column <filename unknown>:0:0
        ]
        Stack Trace:
      System.Diagnostics.Tests.StackTraceTests.Ctor_Exception_SkipFrames(skipFrames: 1) [FAIL]
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.StackTrace\tests\StackTraceTests.cs(150,0): at System.Diagnostics.Tests.StackTraceTests.Ctor_Exception_SkipFrames(Int32 skipFrames)
      System.Diagnostics.Tests.StackTraceTests.Ctor_Exception_SkipFrames_FNeedFileInfo(skipFrames: 1, fNeedFileInfo: True) [FAIL]
        Assert.Null() Failure
        Expected: (null)
        Actual:   StackFrame[] [InvokeException at offset 19 in file:line:column D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.StackTrace\tests\StackTraceTests.cs:339:17
        ]
        Stack Trace:
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.StackTrace\tests\StackTraceTests.cs(201,0): at System.Diagnostics.Tests.StackTraceTests.Ctor_Exception_SkipFrames_FNeedFileInfo(Int32 skipFrames, Boolean fNeedFileInfo)
      System.Diagnostics.Tests.StackTraceTests.Ctor_Exception_SkipFrames_FNeedFileInfo(skipFrames: 1, fNeedFileInfo: False) [FAIL]
        Assert.Null() Failure
        Expected: (null)
        Actual:   StackFrame[] [InvokeException at offset 19 in file:line:column <filename unknown>:0:0
        ]
        Stack Trace:
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.StackTrace\tests\StackTraceTests.cs(201,0): at System.Diagnostics.Tests.StackTraceTests.Ctor_Exception_SkipFrames_FNeedFileInfo(Int32 skipFrames, Boolean fNeedFileInfo)
    Finished:    System.Diagnostics.StackTrace.Tests
```

**Comment by stephentoub** [comment]
netfx-specific test issue.
