### ISSUE TITLE
Several Name Resolution tests failed with `No such device or address`

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#23811]
Dns_GetHostEntry_HostString_Ok(hostName: \"\")
Dns_GetHostEntryAsync_HostString_Ok(hostName: \"\")	
DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName	
DnsObsoleteGetHostByName_EmptyString_ReturnsHostName	
failed on Ubuntu 1604

@davidsh part of the networking test infra issues you're tracking?

```
Unhandled Exception of Type System.Net.Internals.SocketExceptionFactory+ExtendedSocketException
Message :
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address
Stack Trace :
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 46
   at System.Net.Dns.ResolveCallback(Object context) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 290
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 420
   at System.Net.Dns.EndGetHostByName(IAsyncResult asyncResult) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 445
   at System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/tests/FunctionalTests/GetHostByNameTest.cs:line 115
```
https://mc.dot.net/#/user/tarekgh/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/4fbf6654aa3b3d22c4d9f6688f26c99a0f60f234/workItem/System.Net.NameResolution.Functional.Tests

**Comment by stephentoub** [comment]
@danmosemsft, I just added these tests in https://github.com/dotnet/corefx/pull/23794.  Is it possible the PR you're quoting picked up the tests but not the src fixes to go with it?  Do they happen if you re-run?

**Comment by danmosemsft** [comment]
@stephentoub I'm not sure how that could happen. I kicked off again: #23775

**Comment by davidsh** [comment]
I don't think this is related to what I am looking into.  This requires a Linux expert to diagnose.

**Comment by stephentoub** [comment]
I'm going to close this under the assumption that it's a fluke where somehow tests from a concurrently merged PR ran without the associated src changes from that same PR.  If it happens again, we can reopen, in which case there's a bigger issue to address, that `Dns.GetHostEntry(Dns.GetHostName())` and `Dns.GetHostByName(Dns.GetHostName())` fail on that platform.
