### ISSUE TITLE
[uapaot] Unsafe RefAreSame test fails for uapaot

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#23953]
Test disabled in: https://github.com/dotnet/corefx/pull/23905

**The Unsafe.RefAreSame test fails on uapaot:**
```C#
public static void RefAreSame()
{
    long[] a = new long[2];
    Assert.True(Unsafe.AreSame(ref a[0], ref a[0])); // successful
    Assert.False(Unsafe.AreSame(ref a[0], ref a[1])); // fails
}
```

```xml
<test name="System.Runtime.CompilerServices.UnsafeTests.RefAreSame" type="System.Runtime.CompilerServices.UnsafeTests" method="RefAreSame" time="0.0003107" result="Fail">
    <failure exception-type="Xunit.Sdk.FalseException">
        <message><![CDATA[Assert.False() Failure\r\nExpected: False\r\nActual:   True]]></message>
        <stack-trace><![CDATA[   at System.Runtime.CompilerServices.UnsafeTests.RefAreSame(Int64[] a) in D:\GitHub\Fork\corefx\src\System.Runtime.CompilerServices.Unsafe\tests\UnsafeTests.cs:line 593
            at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean targetIsThisCall)
            at System.InvokeUtils.CalliIntrinsics.Call(IntPtr dynamicInvokeHelperMethod, Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean isTargetThisCall)
            at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, IntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object targetMethodOrDelegate, Object[] parameters, BinderBundle binderBundle, Boolean wrapInTargetInvocationException, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall, Boolean parametersNeedCopyBack, ArgSetupState argSetupState, Object[] parametersOld, Object[] nullableCopyBackObjectsOld, Int32 curIndexOld, Object targetMethodOrDelegateOld, BinderBundle binderBundleOld, Object[] customBinderProvidedParametersOld, Object result, Exception e, Int32 i) in CallDynamicInvokeMethod:line 16707566
        ]]></stack-trace>
    </failure>
```

**Comment by ahsonkhan** [comment]
This issue has been resolved.

**Comment by ahsonkhan** [comment]
Tests fixed and re-enabled in https://github.com/dotnet/corefx/pull/24385
