### ISSUE TITLE
[uapaot] Span indexer fails with IndexOutOfRangeException for reference types

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#23952]
Test disabled in: https://github.com/dotnet/corefx/pull/23905

**The Span tests fail for uapaot when we try to access the elements of a Span of a reference type like string using the provided indexer:**
```C#
public static void TestingSpanReferenceTypeForUAPAOT()
{
    ReadOnlySpan<byte> span1 = new byte[] { 1 };
    byte temp1 = span1[0];  // successful

    ReadOnlySpan<string> span2 = new string[] { "1" };
    string temp2 = span2[0];    // fails with IndexOutOfRangeException
}
```
```xml
<test name="System.SpanTests.ReadOnlySpanTests.TestingSpanReferenceTypeForUAPAOT" type="System.SpanTests.ReadOnlySpanTests" method="TestingSpanReferenceTypeForUAPAOT" time="0.0000441" result="Fail">
    <failure exception-type="System.IndexOutOfRangeException">
        <message><![CDATA[System.IndexOutOfRangeException : Index was outside the bounds of the array.]]></message>
        <stack-trace><![CDATA[   at Internal.Runtime.CompilerHelpers.ThrowHelpers.ThrowIndexOutOfRangeException() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\Internal\Runtime\CompilerHelpers\ThrowHelpers.cs:line 25
            at System.SpanTests.ReadOnlySpanTests.TestingSpanReferenceTypeForUAPAOT(ReadOnlySpan$1<Byte> span1) in D:\GitHub\Fork\corefx\src\System.Memory\tests\ReadOnlySpan\CtorArray.cs:line 66
            at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean targetIsThisCall)
            at System.InvokeUtils.CalliIntrinsics.Call(IntPtr dynamicInvokeHelperMethod, Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean isTargetThisCall)
            at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, IntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object targetMethodOrDelegate, Object[] parameters, BinderBundle binderBundle, Boolean wrapInTargetInvocationException, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall, Boolean parametersNeedCopyBack, ArgSetupState argSetupState, Object[] parametersOld, Object[] nullableCopyBackObjectsOld, Int32 curIndexOld, Object targetMethodOrDelegateOld, BinderBundle binderBundleOld, Object[] customBinderProvidedParametersOld, Object result, Exception e, Int32 i) in CallDynamicInvokeMethod:line 16707566
        ]]></stack-trace>
    </failure>
```

**Comment by ahsonkhan** [comment]
This issue has been resolved.

**Comment by ahsonkhan** [comment]
Tests fixed and re-enabled in https://github.com/dotnet/corefx/pull/24385
