### ISSUE TITLE
System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestPrivateKey failed

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2396]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release/788/
```
Discovering: System.Security.Cryptography.X509Certificates.Tests
  Discovered:  System.Security.Cryptography.X509Certificates.Tests
  Starting:    System.Security.Cryptography.X509Certificates.Tests
     System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestPrivateKey [FAIL]
        System.Security.Cryptography.CryptographicException : CryptGetUserKey failed with error code  
        Stack Trace:
              at Internal.NativeCrypto.CapiHelper.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 keySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
              at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
              at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 keySize, CspParameters parameters, Boolean useDefaultKeySize)
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.PrivateKey.cs(49,0): at Internal.Cryptography.Pal.CertificatePal.get_PrivateKey()
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2.cs(169,0): at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Security.Cryptography.X509Certificates\tests\PfxTests.cs(64,0): at System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestPrivateKey()
  Finished:    System.Security.Cryptography.X509Certificates.Tests
```

**Comment by stephentoub** [comment]
A different but related test just failed as well:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/2378/console
```
 Discovering: System.Security.Cryptography.X509Certificates.Tests
  Discovered:  System.Security.Cryptography.X509Certificates.Tests
  Starting:    System.Security.Cryptography.X509Certificates.Tests
     System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestSetPrivateKey [FAIL]
        System.Security.Cryptography.CryptographicException : OpenCSP failed with Error code 
        Stack Trace:
              at Internal.NativeCrypto.CapiHelper.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
              at Internal.NativeCrypto.CapiHelper.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 keySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
              at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
              at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 keySize, CspParameters parameters, Boolean useDefaultKeySize)
              at System.Security.Cryptography.RSACryptoServiceProvider..ctor(CspParameters parameters)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.PrivateKey.cs(49,0): at Internal.Cryptography.Pal.CertificatePal.get_PrivateKey()
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2.cs(170,0): at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\tests\PfxTests.cs(109,0): at System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestSetPrivateKey()
  Finished:    System.Security.Cryptography.X509Certificates.Tests
```

**Comment by bartonjs** [comment]
Intermittent failures interacting with a native library, what fun\</sarcasm>.

Since we're going to be replacing all of the Windows RSA code soon (see the [.NET Framework 4.6 announcement](http://blogs.msdn.com/b/dotnet/archive/2015/07/20/announcing-net-framework-4-6.aspx) (the Cryptography Updates section)), I don't know that it's very valuable to track down the underlying cause here.

OTOH, just turning the tests off doesn't feel like a happy path, either.

A compromise might be to push things off to the outer loop; but that _also_ feels dirty.

"Soon" doesn't mean "tomorrow", but "incorporating 4.6 surface area changes is important, and we're working on it"

**Comment by bartonjs** [comment]
#2583 has so far the best of the stack traces, indicating what the underlying error code is.so letting that issue track this ongoing problem.
