### ISSUE TITLE
Error trying to deserialize TimeZoneInfo on OS X

### ISSUE THREAD

**Issue by pblasucci** [dotnet/corefx#23985]
#### Details

+ .NET Core 2.0
+ macOS 10.12.6

#### Minimal Reproduction

```
let anyZone = TimeZoneInfo.FindSystemTimeZoneById("America/New_York")
let deflated = anyZone.ToSerializedString()
Zone.FromSerializedString deflated = anyZone
```

#### Expected Behavior

No error. Last expression returns `true`.

#### Actual Behavior

```
Error:
  System.Runtime.Serialization.SerializationException : An error occurred while deserializing the object.  The serialized data is corrupt.
---- System.InvalidTimeZoneException : The elements of the AdjustmentRule array must be in chronological order and must not overlap.
Stack Trace:
   at System.TimeZoneInfo.StringSerializer.GetDeserializedTimeZoneInfo(String source)
   at quickpbt.Teaser.days should equal hours() in /Users/pblasucci/Developer/quickpbt/quickpbt_fs/Teaser.fs:line 25
----- Inner Stack Trace -----
   at System.TimeZoneInfo.ValidateTimeZoneInfo(String id, TimeSpan baseUtcOffset, AdjustmentRule[] adjustmentRules, Boolean& adjustmentRulesSupportDst)
   at System.TimeZoneInfo..ctor(String id, TimeSpan baseUtcOffset, String displayName, String standardDisplayName, String daylightDisplayName, AdjustmentRule[] adjustmentRules, Boolean disableDaylightSavingTime)
   at System.TimeZoneInfo.StringSerializer.GetDeserializedTimeZoneInfo(String source)
```

#### Additional Notes

On a recent build of Windows 10, everything behaves correctly. And I've not tested this on _any_ build of Linux.

**Comment by danmosemsft** [comment]
@ViktorHofer

**Comment by justinvp** [comment]
Related: #14797

**Comment by danmosemsft** [comment]
Oops, this is some globalization specific serialization, not binary serialization.

**Comment by ViktorHofer** [comment]
cc @tarekgh

**Comment by tarekgh** [comment]
This is known issue and as @justinvp mentioned it is similar to #14797 (actually it is a duplicate). This need to redesign how we use the AdjustmentRule on Linux in general.

**Comment by tarekgh** [comment]
@pblasucci just wondering why you are serializing the TZ this way in your scenario?

**Comment by mj1856** [comment]
cc @eerhardt

Also, is this a dup of #14797?

**Comment by pblasucci** [comment]
@tarekgh sorry for the delayed reply (and sorry for posting a duplicate issue). 

As to my use case, I picked the class somewhat randomly as part of a presentation on property-based testing (but was still surprised by the error).

**Comment by pblasucci** [comment]
Closing as duplicate of #14797.
