### ISSUE TITLE
Incorrectly closed websockets are throwing unobserved task exceptions

### ISSUE THREAD

**Issue by JustArchi** [dotnet/corefx#24002]
Hello.

We've stumbled upon unobserved task exceptions caused specifically by incorrectly closed websockets by the other side. The recorded stacktrace is:

```
2017-09-12 20:06:55|dotnet-3673|FATAL|ASF|OnUnobservedTaskException() System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The remote party closed the WebSocket connection without completing the close handshake.) ---> System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: Unable to transfer data on the transport connection: Broken pipe. ---> System.Net.Sockets.SocketException: Broken pipe
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Security.SslStreamInternal.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStreamInternal.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, LazyAsyncResult asyncResult)
   at System.Net.Security.SslStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync(MessageOpcode opcode, Boolean endOfMessage, ArraySegment`1 payloadBuffer)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: Unable to transfer data on the transport connection: Broken pipe. ---> System.Net.Sockets.SocketException: Broken pipe
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Security.SslStreamInternal.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStreamInternal.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, LazyAsyncResult asyncResult)
   at System.Net.Security.SslStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync(MessageOpcode opcode, Boolean endOfMessage, ArraySegment`1 payloadBuffer)<---
```

The original issue was reproduced on **[Arch Linux](https://aur.archlinux.org/packages/dotnet/)**, but I believe that the OS doesn't have any say in this. We're trying to reproduce the issue also on one of the official builds, perhaps Windows.

Based on my discussion with the library devs that are utilizing websockets, it looks like the issue might be connected with **[this](https://github.com/SteamRE/SteamKit/issues/452#issuecomment-329069703)**:

> This might actually be a bug in .NET Core itself. [This function](https://source.dot.net/#System.Net.WebSockets/Common/System/Net/WebSockets/ManagedWebSocket.cs,519) is invoked by a timer and the task is not observed. All other code paths appear to be properly awaited.

Thank you in advance.

```
Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

References:

https://github.com/JustArchi/ArchiSteamFarm/issues/612#issuecomment-329015761
https://github.com/SteamRE/SteamKit/issues/452

**Comment by davidsh** [comment]
cc: @stephentoub @karelz 

This is ManagedWebSocket currently being used on Linux.

**Comment by stephentoub** [comment]
@JustArchi, would you have a standalone repro you could share?

**Comment by JustArchi** [comment]
Sadly not for this one. Firstly because I'm just a consumer of a netstandard library that is making use of websockets. Secondly because those issues are happening with connections being forcefully closed, so reproducing it in clean testing environment can be challenging.

Perhaps @yaakov-h could help you with repro. I completely lack skills to make one for this case.

**Comment by yaakov-h** [comment]
I think the repro should be fairly simple. If I have some time tomorrow I can try build one.

HLD:
1. Create a websocket server.
2. Connect to the websocket server.
3. Forcibly terminate the underlying TCP connection.

It's worth mentioning that this isn't an unhandled exception blowing up the application (I think), but a result of subscribing to the `TaskScheduler.UnobservedTaskException` event.

**Comment by JustArchi** [comment]
Yes, this is not unhandled exception, this is unobserved task exception. In my case it's repeated unobserved task exception that is occuring each `X` seconds, so it's becoming a very problematic issue in long-run, as it's spamming my listener with unobserved task exceptions all the time.

**Comment by JustArchi** [comment]
We managed to reproduce this issue also on CentOS 7 x64, so this is not Arch Linux-specific. It seems to affect all unix/linux implementations.

**Comment by stephentoub** [comment]
If you disable keep alive by setting the keep alive to be infinite, do you still see this issue?  From the stack trace, the exception is originating within the try block of SendFrameLockAcquiredNonCancelableAsync; that exception will be stored into a task and returned to the caller.  Most of the callers of this method end up just returning the task back out to the code consuming the library, but one does drop the returned task: https://github.com/dotnet/corefx/blob/afcbd9a5b9e4ecde2db3a69afd093631f1db91c5/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L519.  So if disabling keep alive "fixes" the issue, then this is the likely culprit.  If it doesn't, most likely it's your own code consuming the WebSocket that's allowing the returned task to be dropped.

**Comment by yaakov-h** [comment]
That would be through `WebSocket.DefaultKeepAliveInterval = TimeSpan.Zero`, correct?

**Comment by stephentoub** [comment]
e.g.
var cws = new ClientWebSocket();
cws.Options.KeepAliveInterval = Timeout.InfiniteTimeSpan;
...
