### ISSUE TITLE
Dispose_IconData_DestroysHandle failed in CI

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#24089]
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/3360/consoleText

```
      System.Drawing.Tests.IconTests.Dispose_IconData_DestroysHandle [FAIL]
        System.IO.IOException : The process cannot access the file 'D:\j\workspace\windows-TGrou---2a8f9c29\bin\tests\System.Drawing.Common.Tests\netfx-Windows_NT-Release-x86\bitmaps\48x48_multiple_entries_4bit.ico' because it is being used by another process.
        Stack Trace:
             at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
             at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
             at System.Drawing.Icon..ctor(String fileName, Int32 width, Int32 height)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Drawing.Common\tests\IconTests.cs(327,0): at System.Drawing.Tests.IconTests.Dispose_IconData_DestroysHandle()
```

It looks like one of the tests isn't properly disposing of the Icon, or holding onto the FileStream or something like that. Should be pretty straightforward to diagnose.

**Comment by safern** [comment]
Long time since a failure has not been reported and the test doesn't seem to be disabled: 

https://github.com/dotnet/corefx/blob/2c73b4aef4f1feb47f73b3ab80b0ae3e63f7485b/src/System.Drawing.Common/tests/IconTests.cs#L325
