### ISSUE TITLE
System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandler_ServerCertificates_Test.NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds failed with "System.Net.Internals.SocketExceptionFactory+ExtendedSocketException" in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#24133]
Failed test: System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandler_ServerCertificates_Test.NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds 

Configuration: OuterLoop_netcoreapp_fedora24_release

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_fedora24_release/173/testReport/System.Net.Http.Functional.Tests/ManagedHandler_HttpClientHandler_ServerCertificates_Test/NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds/

MESSAGE:
~~~
System.Net.Http.HttpRequestException : Connection refused [::ffff:4.79.142.205]:443
---- System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Connection refused [::ffff:4.79.142.205]:443
~~~
STACK TRACE:
~~~
at System.Net.Http.ConnectHelper.<ConnectAsync>d__0.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_release/src/System.Net.Http/src/System/Net/Http/Managed/ConnectHelper.cs:line 25 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult() 
at System.Net.Http.HttpConnectionHandler.<CreateConnection>d__6.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_release/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnectionHandler.cs:line 88 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult() 
at System.Net.Http.HttpConnectionPool.<WaitForCreatedConnectionAsync>d__11.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_release/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnectionPool.cs:line 121 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult() 
at System.Net.Http.HttpConnectionHandler.<SendAsyncWithAwaitedConnection>d__4.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_release/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnectionHandler.cs:line 42 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Net.Http.CookieHandler.<SendAsync>d__3.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_release/src/System.Net.Http/src/System/Net/Http/Managed/CookieHandler.cs:line 31 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Net.Http.AutoRedirectHandler.<SendAsync>d__5.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_release/src/System.Net.Http/src/System/Net/Http/Managed/AutoRedirectHandler.cs:line 65 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_release/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 464 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.<NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds>d__15.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_release/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ServerCertificates.cs:line 265 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
----- Inner Stack Trace ----- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_release/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 2494 
at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_release/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 5218 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_release/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 5237 
at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_release/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 5193 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_release/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 2494 
at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__275_0(IAsyncResult iar) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_release/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 171 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Net.Http.ConnectHelper.<ConnectAsync>d__0.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_release/src/System.Net.Http/src/System/Net/Http/Managed/ConnectHelper.cs:line 18
~~~

**Comment by Sunny-pu** [comment]
failed again in 2.0.0 branch:
https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20171108.03/workItem/System.Net.HttpListener.Tests/analysis/xunit/System.Net.Tests.HttpListenerResponseHeadersTests~2FStatusDescription_SetInvalid_ThrowsArgumentException(statusDescription:%20%5C%22%5C%5Cr%5C%22)

**Comment by Priya91** [comment]
@wfurt Can you look at the log for this test history? Does it repro?

**Comment by wfurt** [comment]
I only see failures from August in Helix database. It seems like this one is of the tests connecting to external service (4.79.142.205). They are inherently unreliable. 
I think the last link by @Sunny-pu here is incorrect. It is different test as well as it was attempt to connect to loopback server.

**Comment by Priya91** [comment]
Since it was a one time failure, closing the issue with no-repro. Please reopen if new reports available.

**Comment by Priya91** [comment]
This failed in CI in #26250 

```
Ubuntu.1404.Amd64.Open-Debug-x64
Get Repro environment
Unhandled Exception of Type System.Net.Http.HttpRequestException
Message :
System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception.
---- System.IO.IOException : Unable to transfer data on the transport connection: Connection reset by peer.
-------- System.Net.Sockets.SocketException : Connection reset by peer
Stack Trace :
   at System.Net.Http.HttpConnectionHandler.<EstablishSslConnection>d__5.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnectionHandler.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.HttpConnectionHandler.<CreateConnection>d__6.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnectionHandler.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.HttpConnectionPool.<WaitForCreatedConnectionAsync>d__15.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnectionPool.cs:line 226
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.HttpConnectionHandler.<SendAsyncWithAwaitedConnection>d__4.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnectionHandler.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.CookieHandler.<SendAsync>d__3.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Http/src/System/Net/Http/Managed/CookieHandler.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.AuthenticateAndRedirectHandler.<SendAsync>d__6.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Http/src/System/Net/Http/Managed/AuthenticateAndRedirectHandler.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__62.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 488
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.<NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds>d__15.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ServerCertificates.cs:line 269
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.FixedSizeReader.<ReadPacketAsync>d__1.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/src/System/Net/FixedSizeReader.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 737
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 708
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 194
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__44_1(IAsyncResult iar) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 381
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) in /root/coreclr/src/mscorlib/src/System/Threading/Tasks/FutureFactory.cs:line 533
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.HttpConnectionHandler.<EstablishSslConnection>d__5.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnectionHandler.cs:line 68
----- Inner Stack Trace -----
```

**Comment by karelz** [comment]
It seems to be different failure. I will look at CI history and reopen if there is evidence it is happening more than one off.
