### ISSUE TITLE
Abort_BeginGetRequestStreamThenAbort_RequestStreamCallbackCalledBeforeAbortReturns failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2416]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug/813/consoleFull
```
System.Net.Requests.Test.HttpWebRequestTest.Abort_BeginGetRequestStreamThenAbort_RequestStreamCallbackCalledBeforeAbortReturns(remoteServer: Uri { AbsolutePath = "/post", AbsoluteUri = "http://httpbin.org/post", Authority = "httpbin.org", DnsSafeHost = "httpbin.org", Fragment = "", ... }) [FAIL]
19:58:58         Assert.Equal() Failure
19:58:58         Expected: 1
19:58:58         Actual:   0
19:58:58         Stack Trace:
d:\j\workspace\dotnet_corefx_windows_debug\src\System.Net.Requests\tests\HttpWebRequestTest.cs(548,0): at System.Net.Requests.Test.HttpWebRequestTest.Abort_BeginGetRequestStreamThenAbort_RequestStreamCallbackCalledBeforeAbortReturns(Uri remoteServer)
```

**Comment by stephentoub** [comment]
cc: @davidsh, @pgavlin, @CIPop

**Comment by davidsh** [comment]
This is a problematic testcase which I thought I disabled/removed already before the code was placed onto GitHub.

**Comment by stephentoub** [comment]
@davidsh, should it be deleted or should it be disabled?  And just this one test case, all of the ```Abort_BeginGetRequestStreamThenAbort_*``` cases, or more than that?

**Comment by davidsh** [comment]
@stephentoub Not all of them.  I will look at this within 24 hours and submit a PR to take care of this.

**Comment by stephentoub** [comment]
Ok, thanks.

**Comment by stephentoub** [comment]
FYI, failed again here: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/2373/console
```
Discovering: System.Net.Requests.Tests
  Discovered:  System.Net.Requests.Tests
  Starting:    System.Net.Requests.Tests
     System.Net.Requests.Test.HttpWebRequestTest.Abort_BeginGetRequestStreamThenAbort_RequestStreamCallbackCalledBeforeAbortReturns(remoteServer: Uri { AbsolutePath = "/post", AbsoluteUri = "http://httpbin.org/post", Authority = "httpbin.org", DnsSafeHost = "httpbin.org", Fragment = "", ... }) [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   0
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Requests\tests\HttpWebRequestTest.cs(548,0): at System.Net.Requests.Test.HttpWebRequestTest.Abort_BeginGetRequestStreamThenAbort_RequestStreamCallbackCalledBeforeAbortReturns(Uri remoteServer)
  Finished:    System.Net.Requests.Tests
```

**Comment by stephentoub** [comment]
Removed by #2424.
