### ISSUE TITLE
X509Chain under heavy load causes System.IO.IOException: Too many open files

### ISSUE THREAD

**Issue by hmvs** [dotnet/corefx#24209]
Having a lot of connections to the web api. API by itself doesn't open any files. 
From time to time we are having container restarted because of exception. 
Microsoft.AspNetCore.Mvc  **1.1.4**
Docker image: **aspnetcore-build:1.1.2**
```
Unhandled Exception: System.IO.IOException: Too many open files
at System.IO.UnixFileSystem.FileSystemEnumerable`1.OpenDirectory(String fullPath)
at System.IO.UnixFileSystem.FileSystemEnumerable`1.Enumerate()
at System.IO.UnixFileSystem.FileSystemEnumerable`1..ctor(String userPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget, Func`3 translateResult)
at System.IO.UnixFileSystem.EnumerateFileSystemInfos(String fullPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget)
at System.IO.DirectoryInfo.InternalEnumerateFiles(String searchPattern, SearchOption searchOption)
at System.IO.DirectoryInfo.EnumerateFiles()
at Internal.Cryptography.Pal.StorePal.LoadMachineStores()
at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.FindCandidates(X509Certificate2 leaf, X509Certificate2Collection extraStore, HashSet`1 downloaded, HashSet`1 systemTrusted, TimeSpan& remainingDownloadTime)
at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout)
at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
at System.Net.Security.CertificateValidation.BuildChainAndVerifyProperties(X509Chain chain, X509Certificate2 remoteCertificate, Boolean checkCertName, String hostName)
at System.Net.Http.CurlHandler.SslProvider.VerifyCertChain(IntPtr storeCtxPtr, IntPtr curlPtr)
at Interop.Http.MultiPerform(SafeCurlMultiHandle multiHandle)
at System.Net.Http.CurlHandler.MultiAgent.WorkerBodyLoop()
```

**Comment by stephentoub** [comment]
cc: @JeremyKuhne, @bartonjs in case there's something that can be done to reduce the number of file descriptors currently in use.

But... you may just want/need to increase the ulimit on your system. What is the ulimit -n value? Try setting it to something larger.

**Comment by hmvs** [comment]
@stephentoub Now we are trying it under **aspnetcore-build:1.1.4** so we are looking into results.
If it not help we will try to increase ulimit. 
Now it's 1024.

**Comment by danmosemsft** [comment]
What distro is this?

**Comment by hmvs** [comment]
Host: Amazon Linux  **amzn-ami-2016.09.f-amazon-ecs-optimized (ami-b2df2ca4)**
Docker image: **aspnetcore-build:1.1.4**
Update to **aspnetcore-build:1.1.4** didn't help. Still having issues. Will try bumping ulimit.

**Comment by hmvs** [comment]
Seems to be Increasing ulimit helped. But from my point of view it's workaround.

**Comment by stephentoub** [comment]
> Seems to be Increasing ulimit helped

What was it before you increased it?

**Comment by hmvs** [comment]
Same exceptions as in first post.

**Comment by stephentoub** [comment]
I missed that you listed it in the third post above.  1024 is a fairly low limit for a server; if every connection had a single file descriptor open and you have "lots of connections to web api", you're going to overflow that, and most likely you've got more than a single file descriptor per connection (the inbound socket, the outbound socket, a descriptor related to a directory scan, etc.)  While it's possible there are places we could more aggressively limit the number of file descriptors open at a time, you're almost certainly going to want to increase that limit regardless; that's just the nature of ulimit.

**Comment by hmvs** [comment]
Agree with you. But would be nice to reduce handles related to a directory scan. Is it possible to cache certificates?

**Comment by stephentoub** [comment]
> But would be nice to reduce handles related to a directory scan.

How many file descriptors do you see open from the directory enumeration?  At any given time during the enumeration I would expect there to be just one file descriptor open associated with it... are you seeing otherwise?

> Is it possible to cache certificates?

@bartonjs can comment best here.

**Comment by hmvs** [comment]
I haven't looked into it. Just thinking that listing a directory for each connection is an overkill. I might be wrong here.

**Comment by bartonjs** [comment]
No, we effectively can't cache things.  The problem is that if you add a certificate in one process you want it to show up in another... because it would in Windows.  This means that we either always do live reads, or we maintain a cache until FileSystemWatcher fires.  But FileSystemWatcher isn't 100% guaranteed, and failures there would introduce trust skew.

So what we ended up with was caching the LocalMachine root (because it's read-only in .NET and lots of Linux programs have issues with the root trust list changing after they start) and making all of the CurrentUser stores always do live reads off of the directory.

There are some performance changes that I have in mind which will probably come with #16364; like that if enough data has been provided via `ExtraStore` and the new pinned root collection that it shouldn't need to open any `X509Store`s at all.  (And therefore, maybe, if it can be trusted via just the cached LM\Root and ExtraStore that also could avoid more disk access)

**Comment by hmvs** [comment]
So as for me we shouldn't end up with 'Too many open files' exceptions. As far as we not opening files we just opening connections. So if I want to limit my service via 'ulimit' to not get a lot of incoming and outgoing connections I will get  'Too many open files' exception on filesystem, instead of just having this limitation.
