### ISSUE TITLE
System.Net.Http.Functional.Tests.CancellationTest.ReadAsStreamAsync_ReadAsync_Cancel_BodyNeverStarted_TaskCanceledQuickly failed in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#24277]
Failed test: System.Net.Http.Functional.Tests.CancellationTest.ReadAsStreamAsync_ReadAsync_Cancel_BodyNeverStarted_TaskCanceledQuickly 

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/268/testReport/System.Net.Http.Functional.Tests/CancellationTest/ReadAsStreamAsync_ReadAsync_Cancel_BodyNeverStarted_TaskCanceledQuickly/

Configuration: OuterLoop_netcoreapp_win7_release

MESSAGE:
~~~
Elapsed time 00:00:59.8682196 should be less than 30 seconds, was 59.8682196\r\nExpected: True\r\nActual: False
~~~
STACK TRACE:
~~~
at System.Net.Http.Functional.Tests.CancellationTest.<>c__DisplayClass4_1.<<ReadAsStreamAsync_ReadAsync_Cancel_TaskCanceledQuickly>b__0>d.MoveNext() in D:\j\workspace\outerloop_net---15cfbbd5\src\System.Net.Http\tests\FunctionalTests\CancellationTest.cs:line 157 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass3_0.<CreateServerAsync>b__0(Task t) in D:\j\workspace\outerloop_net---15cfbbd5\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 67 
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Net.Http.Functional.Tests.CancellationTest.<ReadAsStreamAsync_ReadAsync_Cancel_TaskCanceledQuickly>d__4.MoveNext() in D:\j\workspace\outerloop_net---15cfbbd5\src\System.Net.Http\tests\FunctionalTests\CancellationTest.cs:line 114 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

**Comment by Jiayili1** [comment]
Closed issue: https://github.com/dotnet/corefx/issues/17591

**Comment by karelz** [comment]
No hit in official Helix runs since 2017/5
Closing. Please reopen if it happens again.
