### ISSUE TITLE
UWP: 2 System.IO.Pipes failing after enabling other tests on same project

### ISSUE THREAD

**Issue by pjanotti** [dotnet/corefx#24318]
```
     System.IO.Pipes.Tests.NamedPipeTest_Specific.Windows_GetImpersonationUserName_Succeed [FAIL]
        GetNamedPipeHandleState failed
        Expected: True
        Actual:   False
        Stack Trace:
              at System.IO.Pipes.Tests.NamedPipeTest_Specific.<Windows_GetImpersonationUserName_Succeed>d__8.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at Void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
              at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x7e
              at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x53
              at Void Xunit.Sdk.TestInvoker`1+<>c__DisplayClass46_1+<<InvokeTestMethodAsync>b__1>d.MoveNext() + 0x2ea
           --- End of stack trace from previous location where exception was thrown ---
              at Void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
              at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x7e
              at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x53
           --- End of stack trace from previous location where exception was thrown ---
              at Void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
              at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x7e
              at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x53

     System.IO.Pipes.Tests.NamedPipeTest_RunAsClient.RunAsClient_Windows [FAIL]
        Expected delegate to have been invoked
        Expected: True
        Actual:   False
        Stack Trace:
              at System.IO.Pipes.Tests.NamedPipeTest_RunAsClient.<RunAsClient_Windows>d__2.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at Void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
              at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x7e
              at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x53
              at Void Xunit.Sdk.TestInvoker`1+<>c__DisplayClass46_1+<<InvokeTestMethodAsync>b__1>d.MoveNext() + 0x2ea
           --- End of stack trace from previous location where exception was thrown ---
              at Void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
              at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x7e
              at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x53
           --- End of stack trace from previous location where exception was thrown ---
              at Void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
              at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x7e
              at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x53

  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.
```

**Comment by Jiayili1** [comment]
These two tests failed on UWP ILC Tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170929.01/workItem/System.IO.Pipes.Tests/analysis/xunit/System.IO.Pipes.Tests.NamedPipeTest_RunAsClient~2FRunAsClient_Windows

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170929.01/workItem/System.IO.Pipes.Tests/analysis/xunit/System.IO.Pipes.Tests.NamedPipeTest_Specific~2FWindows_GetImpersonationUserName_Succeed

**Comment by pjanotti** [comment]
Thanks @Jiayili1 we already investigate some we will revert the change that enabled it.

/cc @joperezr @danmosemsft

**Comment by pjanotti** [comment]
Actually, these two were related to switching to the CreateFile2 API and are still failing, the revert affected other tests.

**Comment by joperezr** [comment]
@pjanotti can you add a bit more info like if this is a uap vs uapaot issue?

**Comment by pjanotti** [comment]
@joperezr 
* uap: no named pipe client can be created, there is no API to do that in the app container
* uapaot: is using the same API as uap but not running in the app container in this case it can create the named pipe client but it has a small bug when dealing with impersonation
