### ISSUE TITLE
TakeLast on empty list throws InvalidOperationException (Empty Queue)

### ISSUE THREAD

**Issue by bfcamara** [dotnet/corefx#24327]
**Repro steps**

```csharp
var x = new List<string>();
var y = x.TakeLast(100);
Console.WriteLine("Any()=" + y.Any());
````
**Expected Result**
The same as the `Take()`, i.e, the Any() returns false

**Actual Result**
An exception is thrown

```
Unhandled Exception: System.InvalidOperationException: Queue empty.
   at System.Collections.Generic.Queue`1.ThrowForEmptyQueue()
   at System.Collections.Generic.Queue`1.Dequeue()
   at System.Linq.Enumerable.<TakeLastIterator>d__208`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
```

**Comment by danmosemsft** [comment]
Fixed
