### ISSUE TITLE
INstalling application using clickonce

### ISSUE THREAD

**Issue by shilpa1986** [dotnet/corefx#24334]
Hi, we have a application built with clcikonce deployment. Whe we are trying to install using https:// it is returning the below error. Please suggest.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of https://imastest.testweb.bp.com/iMASApplication/iMAS-TEST.application resulted in exception. Following failure messages were detected:
		+ Downloading https://imastest.testweb.bp.com/iMASApplication/iMAS-TEST.application did not succeed.
		+ The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
		+ The remote certificate is invalid according to the validation procedure.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [9/29/2017 5:20:16 PM] : Activation of https://imastest.testweb.bp.com/iMASApplication/iMAS-TEST.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [9/29/2017 5:20:17 PM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading https://imastest.testweb.bp.com/iMASApplication/iMAS-TEST.application did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
		--- Inner Exception ---
		System.Security.Authentication.AuthenticationException
		- The remote certificate is invalid according to the validation procedure.
		- Source: System
		- Stack trace:
			at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)

**Comment by karelz** [comment]
This is not related to .NET Core, closing.
For troubleshooting .NET Framework issues, please refer to info on our [home page](https://github.com/dotnet/corefx#how-to-engage-contribute-and-provide-feedback).
