### ISSUE TITLE
GenerateDepsJson task failed with ArgumentException

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#24366]
I did a clean, sync, build locally and hit this (it succeeded on a subsequent attempt):
```
c:\Users\stoub\Source\Repos\corefx\src\src.builds(30,5): error MSB4018: The "GenerateDepsJson" task failed unexpectedly.
c:\Users\stoub\Source\Repos\corefx\src\src.builds(30,5): error MSB4018: System.ArgumentException: Can not add property runtimes/win-x64/lib/netcoreapp2.0/mscorlib.dll
to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
c:\Users\stoub\Source\Repos\corefx\src\src.builds(30,5): error MSB4018:    at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
c:\Users\stoub\Source\Repos\corefx\src\src.builds(30,5): error MSB4018:    at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCh
eck)
c:\Users\stoub\Source\Repos\corefx\src\src.builds(30,5): error MSB4018:    at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck
)
c:\Users\stoub\Source\Repos\corefx\src\src.builds(30,5): error MSB4018:    at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipPare
ntCheck)
c:\Users\stoub\Source\Repos\corefx\src\src.builds(30,5): error MSB4018:    at Newtonsoft.Json.Linq.JContainer.Add(Object content)
c:\Users\stoub\Source\Repos\corefx\src\src.builds(30,5): error MSB4018:    at Newtonsoft.Json.Linq.JObject.Add(String propertyName, JToken value)
c:\Users\stoub\Source\Repos\corefx\src\src.builds(30,5): error MSB4018:    at Microsoft.DotNet.Build.Tasks.GenerateDepsJson.Execute()
c:\Users\stoub\Source\Repos\corefx\src\src.builds(30,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Exec
ute()
c:\Users\stoub\Source\Repos\corefx\src\src.builds(30,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```
cc: @ericstj

**Comment by danmosemsft** [comment]
I can't find the dupe but I know he's already aware of it.

**Comment by stephentoub** [comment]
I continue to hit this locally with fair frequency.  Do we know the cause?

**Comment by stephentoub** [comment]
This has been fixed.
