### ISSUE TITLE
Data.SqlClient : Intermittent Kerberos issues on Linux

### ISSUE THREAD

**Issue by roederja2** [dotnet/corefx#24371]
Hi,
I'm using the new IntegratedAuthentication feature in the SqlClient (version 4.4 of the Data.SqlClient package and dotnetcore 2.0) on RHEL7 in a docker image. It usually works, but I do get intermittent failures of

```
Wcm.ServiceModel.Net.InterServiceException: One or more errors occurred. (Cannot access Kerberos ticket. Ensure Kerberos has been initialized with 'kinit'.
ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (SPNEGO cannot find mechanisms to negotiate).
at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)
at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)
at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)
at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)
at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength))
```

It then starts working again after a while. No restart of the program is required. And yes, I did run kinit before starting the application.

Due to the intermittent nature of this failure I'm not really sure what's wrong and I was hoping someone here might have an idea.

[EDIT] Fix callstack formatting by @karelz

**Comment by roederja2** [comment]
I now put in a retry in case of this exception and it seems to "fix" my problem. My program is running a lot of SQL queries in parallel, so maybe it is some kind of file locking issue?

**Comment by roederja2** [comment]
Also I have seen dotnet segfault shortly after renewing the kerberos token (using kinit -R) when there was a SQL query going on at the time. Unfortunately the only feedback I got was " Segmentation fault".

**Comment by karelz** [comment]
Do you have the dump? Can you get call stack of the segfault?

**Comment by saurabh500** [comment]
@roederja2 How long is the token valid until, in this case? Do you have auto-renewal setup for when the Kerberos token obtained through kinit expires?

**Comment by karelz** [comment]
Nor response in 3 weeks, closing.
