### ISSUE TITLE
UWP HttpListener Read_Disposed_ReturnsZero test failed with "The text associated with this error code could not be found."

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#24394]
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/ead0778f7763f6852cd3f7124a9838950a39033b/workItem/System.Net.HttpListener.Tests/analysis/xunit/System.Net.Tests.HttpRequestStreamTests~2FRead_Disposed_ReturnsZero(transferEncodingChunked:%20True)
```
Unhandled Exception of Type System.Net.Http.HttpRequestException
Message :
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Exception : The text associated with this error code could not be found.

The connection with the server was reset
Stack Trace :
   at System.Net.Http.HttpClientHandler.<SendAsync>d__113.MoveNext() in D:\j\workspace\windows-TGrou---33cbf18b\src\System.Net.Http\src\uap\System\Net\HttpClientHandler.cs:line 616
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext() in D:\j\workspace\windows-TGrou---33cbf18b\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 464
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Net.Tests.HttpRequestStreamTests.<Read_Disposed_ReturnsZero>d__13.MoveNext() in D:\j\workspace\windows-TGrou---33cbf18b\src\System.Net.HttpListener\tests\HttpRequestStreamTests.cs:line 351
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpHandlerToFilter.<SendAsync>d__15.MoveNext() in D:\j\workspace\windows-TGrou---33cbf18b\src\System.Net.Http\src\uap\System\Net\HttpHandlerToFilter.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClientHandler.<SendAsync>d__113.MoveNext() in D:\j\workspace\windows-TGrou---33cbf18b\src\System.Net.Http\src\uap\System\Net\HttpClientHandler.cs:line 607
```

**Comment by Sunny-pu** [comment]
failed in master branch:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20171113.01/workItem/System.Net.HttpListener.Tests.Execution/analysis/xunit/System.Net.Tests.HttpRequestStreamTests~2FRead_InvalidOffsetSize_ThrowsArgumentOutOfRangeException(offset:%200,%20size:%203,%20chunked:%20True)

**Comment by Sunny-pu** [comment]
failed in Master branch:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20180611.01/workItem/System.Net.HttpListener.Tests/analysis/xunit/System.Net.Tests.HttpRequestStreamTests~2FRead_Disposed_ReturnsZero(transferEncodingChunked:%20True)

**Comment by davidsh** [comment]
Closing due to age. We can revisit potential UWP test failures if they occur again during CI testing.
