### ISSUE TITLE
cannot import X509Certificate from file in .net core 2.0

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#24484]
@xingzhougmu commented on [Sat Sep 02 2017](https://github.com/dotnet/core/issues/932)

# Issue Title

cannot import X509Certificate from file in .net core 2.0

# General

The following code works perfectly in .net core 1.0, however, does not in .net core 2.0.
`X509Certificate clientCert = new X509Certificate(Directory.GetCurrentDirectory() + "/Certs/Production/CN_Certificate.crt");`

Under .net core 2.0, the exception is as below:

> {Interop+AppleCrypto+AppleCommonCryptoCryptographicException: Unknown format in import.
>    at Interop.AppleCrypto.X509ImportCertificate(Byte[] bytes, X509ContentType contentType, SafePasswordHandle importPassword, SafeKeychainHandle keychain, Boolean exportable, SafeSecIdentityHandle& identityHandle)
>    at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
>    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
>    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName)
>    at Test.Program.Main(String[] args) in /Users/xzhou/Projects/Test/Program.cs:line 40}

> For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by bartonjs** [comment]
@xingzhougmu can you share a file which produces that behavior?

**Comment by chrishoffman** [comment]
I created a reproducible case that demonstrates the error. I don't have a Windows machine available to me right now but I have used similar code on Windows without issue.  

https://gist.github.com/chrishoffman/4917a03870d2e3e8489af714495de537

**Comment by chrishoffman** [comment]
Actually, I was able to get the above code to work by base64 decoding.  This code was previously developed on .NET core 1.1 and worked there.  Maybe something changed in how the bytes were interpreted between the versions?

**Comment by bartonjs** [comment]
@chrishoffman For best results use either the DER-binary or the PEM (Base64 with the header and footer).  Plain base64 isn't anything I had any idea Windows would load until recently :).

> Maybe something changed in how the bytes were interpreted between the versions?

Yep, all of certificates and TLS and asymmetric cryptography was rewritten on macOS for 2.0 (Security.framework instead of OpenSSL)

**Comment by chrishoffman** [comment]
Using the native stack sounds to great to me.  I am curious what the compatibility break was introduced in 2.0 but it seems easy enough to work around.  It is possible that 1.1 allowed for base64 encoded DER as input while 2.0 does not.  Thanks for the continued advancement.

**Comment by davemurphysf** [comment]
Hi,
I'm facing a similar issue; I have code that was working on framework, but it's not working on core/standard.  I have a Azure Functions project I'm converting from 1.x to 2.0.  I'm [validating an Outlook add-in Identity token](https://docs.microsoft.com/en-us/outlook/add-ins/validate-an-identity-token#validate-the-identity-token-signature), and I'm using [this code from another sample to create certs from the metadata URL.](https://github.com/OfficeDev/Outlook-Add-In-Token-Viewer/blob/535ceafdd9ab3e78f03e317a96d261655bff6878/TokenValidationService/Models/ExchangeIdToken.cs#L134).

I get a `Interop+AppleCrypto+AppleCommonCryptoCryptographicException: Unknown format in import.` exception.

Any ideas?

**Comment by davemurphysf** [comment]
You are 100% correct!  Thank you sir.

**Comment by murugaratham** [comment]
I'm trying to load this [cert](https://github.com/ndi-trusted-data/sg-verify-demo-app/blob/master/webhook/cert/stg-myinfo-2018.pem) but i'm also getting

`[23:27:03 ERR] Unknown format in import.
Interop+AppleCrypto+AppleCommonCryptoCryptographicException: Unknown format in import.`

``` c#
var certByte = System.IO.File.ReadAllBytes("./stg-myinfo-2018.pem");
var x509Cert = new X509Certificate2(certByte);
```
I've cloned that repo and it seems to be able to load the certificate just fine using nodejs.

I've also tried using 
```c#
var certString = <omitted for brevity>;
var certByte = Convert.FromBase64String(certString);
var cert = new X509Certificate2(certByte);
```
and also `Encoding.UTF8.GetBytes`, none of them seems to work, is it something wrong with the cert or am i missing something :frowning_face:

**Comment by bartonjs** [comment]
@murugaratham That's an RSA private key in PKCS#8 format, not a certificate. 

```C#
RSA rsa = RSA.Create();
rsa.ImportPkcs8PrivateKey(thatFileAfterBase64Decode);
```

**Comment by murugaratham** [comment]
@bartonjs which namespace/extension does ImportPkcs8PrivateKey belong to? i'm getting 

```c#
'RSA' does not contain a definition for 'ImportPkcs8PrivateKey' and no accessible extension method 'ImportPkcs8PrivateKey' accepting a first argument of type 'RSA' could be found (are you missing a using directive or an assembly reference?) (CS1061) 
```

**Comment by bartonjs** [comment]
If you're on Windows, you can use the Cng package, and do

```C#
using (CngKey key = CngKey.Import(blob, CngKeyBlobFormat.Pkcs8PrivateBlob))
using (RSA rsa = new RSACng(key))
{
    ...
}
```

If you're on Linux or macOS then there's no other built-in solution; but you could try something like https://stackoverflow.com/questions/50227580/create-x509certificate2-from-pem-file-in-net-core/50236577#50236577.

**Comment by murugaratham** [comment]
Thanks for your input @bartonjs, I've used pem-utils, https://github.com/huysentruitw/pem-utils
For dotnetcore on Mac it's serving my use case.

**Comment by EltonAlvess** [comment]
I'm trying to import a .cert file but i get the same error describled in this issue.

Any news?

**Comment by bartonjs** [comment]
@EltonAlvess what sort of format is your certificate file in?
