### ISSUE TITLE
Consuming types in System.Security.Permissions fails for test projects targeting netfx

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#24517]
System.Security.Permissions only has a netstandard ref configuration and as such will bin-place that into the ref/netfx folder when building the netfx vertical. This library seems to be the last one that is still using PackageAsRefAndLib https://github.com/dotnet/corefx/blob/1a8531aa3c511d78a1520c40f4595334a8ba3ada/src/System.Security.Permissions/src/System.Security.Permissions.csproj#L9. 

We should remove that and instead add a netfx configurations for the ref so that our own projects can correctly consume this library.

As a temp workaround test projects can add the:
```
 <ItemGroup Condition="'$(TargetGroup)' == 'netfx'">
    <!-- Work-around issue where we are bin-placing the netstandard ref for System.Security.Permissions for netfx -->
    <TargetingPackExclusions Include="System.Security.Permissions" />
  </ItemGroup> 
```

**Comment by weshaggard** [comment]
@safern could you update this with your work for netfx builds.

**Comment by safern** [comment]
> @safern could you update this with your work for netfx builds.

Yes I will.

**Comment by ViktorHofer** [comment]
Just a reminder for myself: https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Serialization.Formatters/tests/System.Runtime.Serialization.Formatters.Tests.csproj#L34

**Comment by weshaggard** [comment]
Part of #23889

**Comment by safern** [comment]
I was able to run the tests for System.Security.Permissions against netfx by disabling the obsolete warnings and I get 34 failures out of 131 that we will want to investigate as it seems like a difference in behavior. It could be a fix in .NET Core that hasn't been ported to netfx.

```
System.Security.Permissions.Tests.EvidenceBaseTests.ApplicationTrustCallMethods [FAIL]
        System.ArgumentException : Invalid Xml.
        Stack Trace:
             at System.Security.Policy.ApplicationTrust.FromXml(SecurityElement element)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\EvidenceBaseTests.cs(27,0): at System.Securi
  ty.Permissions.Tests.EvidenceBaseTests.ApplicationTrustCallMethods()
      System.Security.Permissions.Tests.PermissionSetTests.PermissionSetCallMethods [FAIL]
        System.ArgumentException : Invalid XML. Missing required tag <PermissionSet> for type 'System.Security.Permissi
  onSet'.
        Stack Trace:
             at System.Security.PermissionSet.FromXml(SecurityElement et, Boolean allowInternalOnly, Boolean ignoreType
  LoadFailures)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PermissionSetTests.cs(30,0): at System.Secur
  ity.Permissions.Tests.PermissionSetTests.PermissionSetCallMethods()
      System.Security.Permissions.Tests.HostSecurityManagerTests.CallMethods [FAIL]
        System.ArgumentException : The application evidence does not contain a Fusion activation context.
        Stack Trace:
             at System.Security.HostSecurityManager.DetermineApplicationTrust(Evidence applicationEvidence, Evidence ac
  tivatorEvidence, TrustManagerContext context)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\HostSecurityManagerTests.cs(16,0): at System
  .Security.Permissions.Tests.HostSecurityManagerTests.CallMethods()
        System.ArgumentException : Element must be a <IMembershipCondition> element.
        Stack Trace:
             at System.Security.Policy.GacMembershipCondition.FromXml(SecurityElement e, PolicyLevel level)
      System.Security.Permissions.Tests.MembershipConditionTests.GacMembershipConditionCallMethods [FAIL]
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\MembershipConditionTests.cs(58,0): at System
  .Security.Permissions.Tests.MembershipConditionTests.GacMembershipConditionCallMethods()
      System.Security.Permissions.Tests.PolicyTests.PolicyStatementCallMethods [FAIL]
        System.ArgumentException : Invalid XML. Missing required tag <PolicyStatement> for type 'System.Security.Policy
  .PolicyStatement'.
        Stack Trace:
             at System.Security.Policy.PolicyStatement.FromXml(SecurityElement et, PolicyLevel level, Boolean allowInte
  rnalOnly)
             at System.Security.Policy.PolicyStatement.FromXml(SecurityElement et)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PolicyTests.cs(52,0): at System.Security.Per
  missions.Tests.PolicyTests.PolicyStatementCallMethods()
      System.Security.Permissions.Tests.PermissionTests.FileIOPermissionCallMethods [FAIL]
        System.ArgumentException : Absolute path information is required.
        Stack Trace:
             at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
             at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlAc
  tions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
             at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PermissionTests.cs(57,0): at System.Security
  .Permissions.Tests.PermissionTests.FileIOPermissionCallMethods()
      System.Security.Permissions.Tests.EvidenceBaseTests.PermissionRequestEvidenceCallMethods [FAIL]
        System.ArgumentException : Invalid XML. Missing required tag <PermissionSet> for type 'System.Security.Permissi
  onSet'.
        Stack Trace:
             at System.Security.PermissionSet.FromXml(SecurityElement et, Boolean allowInternalOnly, Boolean ignoreType
  LoadFailures)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\EvidenceBaseTests.cs(62,0): at System.Securi
  ty.Permissions.Tests.EvidenceBaseTests.PermissionRequestEvidenceCallMethods()
      System.Security.Permissions.Tests.PermissionTests.ReflectionPermissionCallMethods [FAIL]
        System.ArgumentException : 'elem' was not a permission element.
        Stack Trace:
             at System.Security.CodeAccessPermission.ValidateElement(SecurityElement elem, IPermission perm)
             at System.Security.Permissions.ReflectionPermission.FromXml(SecurityElement esd)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PermissionTests.cs(152,0): at System.Securit
  y.Permissions.Tests.PermissionTests.ReflectionPermissionCallMethods()
      System.Security.Permissions.Tests.PermissionSetTests.NamedPermissionSetCallMethods [FAIL]
        System.ArgumentException : Invalid XML. Missing required tag <PermissionSet> for type 'System.Security.NamedPer
  missionSet'.
        Stack Trace:
             at System.Security.PermissionSet.FromXml(SecurityElement et, Boolean allowInternalOnly, Boolean ignoreType
  LoadFailures)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PermissionSetTests.cs(51,0): at System.Secur
  ity.Permissions.Tests.PermissionSetTests.NamedPermissionSetCallMethods()
      System.Security.Permissions.Tests.ApplicationTrustTests.ApplicationTrustCollectionCallMethods [FAIL]
        System.ArgumentException : An ApplicationTrust must have an application identity before it can be persisted.
        Stack Trace:
             at System.Security.Policy.ApplicationTrustCollection.Add(ApplicationTrust trust)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\ApplicationTrustTests.cs(18,0): at System.Se
  curity.Permissions.Tests.ApplicationTrustTests.ApplicationTrustCollectionCallMethods()
      System.Security.Permissions.Tests.MembershipConditionTests.HashMembershipConditionCallMethods [FAIL]
        System.ArgumentException : Element must be a <IMembershipCondition> element.
        Stack Trace:
             at System.Security.Policy.HashMembershipCondition.FromXml(SecurityElement e, PolicyLevel level)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\MembershipConditionTests.cs(75,0): at System
  .Security.Permissions.Tests.MembershipConditionTests.HashMembershipConditionCallMethods()
      System.Security.Permissions.Tests.PermissionTests.EnvironmentPermissionCallMethods [FAIL]
        System.ArgumentException : Must set exactly one flag.
        Stack Trace:
             at System.Security.Permissions.EnvironmentPermission.ExclusiveFlag(EnvironmentPermissionAccess flag)
             at System.Security.Permissions.EnvironmentPermission.GetPathList(EnvironmentPermissionAccess flag)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PermissionTests.cs(17,0): at System.Security
  .Permissions.Tests.PermissionTests.EnvironmentPermissionCallMethods()
      System.Security.Permissions.Tests.ApplicationTrustTests.ApplicationTrustEnumeratorCallMethods [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
             at System.Security.Policy.ApplicationTrustEnumerator.MoveNext()
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\ApplicationTrustTests.cs(34,0): at System.Se
  curity.Permissions.Tests.ApplicationTrustTests.ApplicationTrustEnumeratorCallMethods()
      System.Security.Permissions.Tests.MembershipConditionTests.ApplicationDirectoryMembershipConditionCallMethods [FA
  IL]
        System.ArgumentException : Element must be a <IMembershipCondition> element.
        Stack Trace:
             at System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml(SecurityElement e, PolicyLevel l
  evel)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\MembershipConditionTests.cs(41,0): at System
  .Security.Permissions.Tests.MembershipConditionTests.ApplicationDirectoryMembershipConditionCallMethods()
        System.ArgumentException : 'elem' was not a permission element.
        Stack Trace:
             at System.Security.CodeAccessPermission.ValidateElement(SecurityElement elem, IPermission perm)
             at System.Security.Permissions.StrongNameIdentityPermission.FromXml(SecurityElement e)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PermissionTests.cs(243,0): at System.Securit
  y.Permissions.Tests.PermissionTests.StrongNameIdentityPermissionCallMethods()
      System.Security.Permissions.Tests.PermissionTests.StrongNameIdentityPermissionCallMethods [FAIL]
      System.Security.Permissions.Tests.MembershipConditionTests.SiteMembershipConditionCallMethods [FAIL]
        System.ArgumentException : Element must be a <IMembershipCondition> element.
        Stack Trace:
             at System.Security.Policy.SiteMembershipCondition.FromXml(SecurityElement e, PolicyLevel level)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\MembershipConditionTests.cs(109,0): at Syste
  m.Security.Permissions.Tests.MembershipConditionTests.SiteMembershipConditionCallMethods()
      System.Security.Permissions.Tests.MembershipConditionTests.AllMembershipConditionCallMethods [FAIL]
        System.ArgumentException : Element must be a <IMembershipCondition> element.
        Stack Trace:
             at System.Security.Policy.AllMembershipCondition.FromXml(SecurityElement e, PolicyLevel level)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\MembershipConditionTests.cs(24,0): at System
  .Security.Permissions.Tests.MembershipConditionTests.AllMembershipConditionCallMethods()
      System.Security.Permissions.Tests.PolicyTests.PolicyLevelCallMethods [FAIL]
        System.Security.Policy.PolicyException : PolicyLevel object not based on a file cannot be recovered.
        Stack Trace:
             at System.Security.Policy.PolicyLevel.Recover()
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PolicyTests.cs(31,0): at System.Security.Per
  missions.Tests.PolicyTests.PolicyLevelCallMethods()
      System.Security.Permissions.Tests.MembershipConditionTests.PublisherMembershipConditionCallMethods [FAIL]
        System.Security.Cryptography.CryptographicException : m_safeCertContext is an invalid handle.
        Stack Trace:
             at System.Security.Cryptography.X509Certificates.X509Certificate.ThrowIfContextInvalid()
             at System.Security.Cryptography.X509Certificates.X509Certificate.get_Subject()
             at System.Security.Policy.PublisherMembershipCondition.ToString()
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\MembershipConditionTests.cs(89,0): at System
  .Security.Permissions.Tests.MembershipConditionTests.PublisherMembershipConditionCallMethods()
      System.Security.Permissions.Tests.MembershipConditionTests.StrongNameMembershipConditionCallMethods [FAIL]
        System.ArgumentException : Element must be a <IMembershipCondition> element.
        Stack Trace:
             at System.Security.Policy.StrongNameMembershipCondition.FromXml(SecurityElement e, PolicyLevel level)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\MembershipConditionTests.cs(126,0): at Syste
  m.Security.Permissions.Tests.MembershipConditionTests.StrongNameMembershipConditionCallMethods()
      System.Security.Permissions.Tests.PermissionTests.TypeDescriptorPermissionCallMethods [FAIL]
        System.ArgumentException : The value of "class" attribute is invalid.
        Parameter name: securityElement
        Stack Trace:
             at System.Security.Permissions.TypeDescriptorPermission.FromXml(SecurityElement securityElement)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PermissionTests.cs(274,0): at System.Securit
  y.Permissions.Tests.PermissionTests.TypeDescriptorPermissionCallMethods()
      System.Security.Permissions.Tests.PermissionTests.RegistryPermissionCallMethods [FAIL]
        System.ArgumentException : Must set exactly one flag.
        Stack Trace:
             at System.Security.Permissions.RegistryPermission.ExclusiveAccess(RegistryPermissionAccess access)
             at System.Security.Permissions.RegistryPermission.GetPathList(RegistryPermissionAccess access)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PermissionTests.cs(172,0): at System.Securit
  y.Permissions.Tests.PermissionTests.RegistryPermissionCallMethods()
      System.Security.Permissions.Tests.PermissionTests.PublisherIdentityPermissionCallMethods [FAIL]
        System.Security.Cryptography.CryptographicException : m_safeCertContext is an invalid handle.
        Stack Trace:
             at System.Security.Cryptography.X509Certificates.X509Certificate.ThrowIfContextInvalid()
             at System.Security.Cryptography.X509Certificates.X509Certificate.get_RawData()
             at System.Security.Permissions.PublisherIdentityPermission.CheckCertificate(X509Certificate certificate)
             at System.Security.Permissions.PublisherIdentityPermission.set_Certificate(X509Certificate value)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PermissionTests.cs(123,0): at System.Securit
  y.Permissions.Tests.PermissionTests.PublisherIdentityPermissionCallMethods()
      System.Security.Permissions.Tests.PermissionTests.UrlIdentityPermissionCallMethods [FAIL]
        System.ArgumentException : 'elem' was not a permission element.
        Stack Trace:
             at System.Security.CodeAccessPermission.ValidateElement(SecurityElement elem, IPermission perm)
             at System.Security.Permissions.UrlIdentityPermission.FromXml(SecurityElement esd)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PermissionTests.cs(312,0): at System.Securit
  y.Permissions.Tests.PermissionTests.UrlIdentityPermissionCallMethods()
      System.Security.Permissions.Tests.PermissionTests.ZoneIdentityPermissionCallMethods [FAIL]
        System.ArgumentException : 'elem' was not a permission element.
        Stack Trace:
             at System.Security.CodeAccessPermission.ValidateElement(SecurityElement elem, IPermission perm)
             at System.Security.Permissions.ZoneIdentityPermission.FromXml(SecurityElement esd)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PermissionTests.cs(332,0): at System.Securit
  y.Permissions.Tests.PermissionTests.ZoneIdentityPermissionCallMethods()
      System.Security.Permissions.Tests.PermissionTests.FileDialogPermissionCallMethods [FAIL]
        System.ArgumentException : 'elem' was not a permission element.
        Stack Trace:
             at System.Security.CodeAccessPermission.ValidateElement(SecurityElement elem, IPermission perm)
             at System.Security.Permissions.FileDialogPermission.FromXml(SecurityElement esd)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PermissionTests.cs(42,0): at System.Security
  .Permissions.Tests.PermissionTests.FileDialogPermissionCallMethods()
      System.Security.Permissions.Tests.PermissionTests.GacIdentityPermissionCallMethods [FAIL]
        System.ArgumentException : 'elem' was not a permission element.
        Stack Trace:
             at System.Security.CodeAccessPermission.ValidateElement(SecurityElement elem, IPermission perm)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PermissionTests.cs(85,0): at System.Security
  .Permissions.Tests.PermissionTests.GacIdentityPermissionCallMethods()
      System.Security.Permissions.Tests.PermissionTests.SiteIdentityPermissionCallMethods [FAIL]
        System.ArgumentException : 'elem' was not a permission element.
        Stack Trace:
             at System.Security.CodeAccessPermission.ValidateElement(SecurityElement elem, IPermission perm)
             at System.Security.Permissions.SiteIdentityPermission.FromXml(SecurityElement esd)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PermissionTests.cs(222,0): at System.Securit
  y.Permissions.Tests.PermissionTests.SiteIdentityPermissionCallMethods()
      System.Security.Permissions.Tests.PermissionTests.SecurityPermissionCallMethods [FAIL]
        System.ArgumentException : 'elem' was not a permission element.
        Stack Trace:
             at System.Security.CodeAccessPermission.ValidateElement(SecurityElement elem, IPermission perm)
             at System.Security.Permissions.SecurityPermission.FromXml(SecurityElement esd)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PermissionTests.cs(201,0): at System.Securit
  y.Permissions.Tests.PermissionTests.SecurityPermissionCallMethods()
      System.Security.Permissions.Tests.PermissionTests.UIPermissionCallMethods [FAIL]
        System.ArgumentException : 'elem' was not a permission element.
        Stack Trace:
             at System.Security.CodeAccessPermission.ValidateElement(SecurityElement elem, IPermission perm)
             at System.Security.Permissions.UIPermission.FromXml(SecurityElement esd)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PermissionTests.cs(291,0): at System.Securit
  y.Permissions.Tests.PermissionTests.UIPermissionCallMethods()
      System.Security.Permissions.Tests.SecurityElementTest.Attributes_Name_Invalid_MS [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentException)
        Actual:   typeof(System.InvalidCastException): Unable to cast object of type 'System.Collections.DictionaryEntr
  y' to type 'System.String'.
        Stack Trace:
             at System.Security.SecurityElement.set_Attributes(Hashtable value)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\SecurityElementTests.cs(319,0): at System.Se
  curity.Permissions.Tests.SecurityElementTest.<>c__DisplayClass19_0.<Attributes_Name_Invalid_MS>b__0()
      System.Security.Permissions.Tests.PrincipalPermissionTest.IntersectWithBadPermission [FAIL]
        Assert.Equal() Failure
        Expected: System.Security.Permissions.PrincipalPermission
        Actual:   (null)
        Stack Trace:
          E:\repos\corefxCopy\corefx\src\CoreFx.Private.TestUtilities\src\System\AssertExtensions.cs(67,0): at System.A
  ssertExtensions.Throws[T](String paramName, Func`1 testCode)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PrincipalPermissionTests.cs(289,0): at Syste
  m.Security.Permissions.Tests.PrincipalPermissionTest.IntersectWithBadPermission()
      System.Security.Permissions.Tests.PrincipalPermissionTest.UnionWithBadPermission [FAIL]
        Assert.Equal() Failure
        Expected: System.Security.Permissions.PrincipalPermission
        Actual:   (null)
        Stack Trace:
          E:\repos\corefxCopy\corefx\src\CoreFx.Private.TestUtilities\src\System\AssertExtensions.cs(67,0): at System.A
  ssertExtensions.Throws[T](String paramName, Func`1 testCode)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PrincipalPermissionTests.cs(204,0): at Syste
  m.Security.Permissions.Tests.PrincipalPermissionTest.UnionWithBadPermission()
      System.Security.Permissions.Tests.PrincipalPermissionTest.IsSubsetOfBadPermission [FAIL]
        Assert.Equal() Failure
        Expected: System.Security.Permissions.PrincipalPermission
        Actual:   (null)
        Stack Trace:
          E:\repos\corefxCopy\corefx\src\CoreFx.Private.TestUtilities\src\System\AssertExtensions.cs(67,0): at System.A
  ssertExtensions.Throws[T](String paramName, Func`1 testCode)
          E:\repos\corefxCopy\corefx\src\System.Security.Permissions\tests\PrincipalPermissionTests.cs(354,0): at Syste
  m.Security.Permissions.Tests.PrincipalPermissionTest.IsSubsetOfBadPermission()
```

**Comment by danmosemsft** [comment]
That assembly is all just stubs isnt it? I'm surprised any tests pass.
