### ISSUE TITLE
FreeBSD: System.Drawing.Printing tests are failing

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#24538]
=== TEST EXECUTION SUMMARY ===
   System.Drawing.Common.Tests  Total: 1731, Errors: 0, Failed: 31, Skipped: 1327, Time: 1.415s
~/git/corefx/bin/tests/System.Drawing.Common.Tests/netcoreapp-FreeBSD-Debug-x64
 
     ---- System.TypeInitializationException : The type initializer for 'System.Drawing.Printing.LibcupsNative' threw an exception.
      -------- System.DllNotFoundException : Unable to load DLL 'libdl': The specified module or one of its dependencies could not be found.
       (Exception from HRESULT: 0x8007007E)
      Stack Trace:
         /home/furt/git/wfurt2-corefx/src/System.Drawing.Common/src/System/Drawing/Printing/PrintingServices.Unix.cs(88,0): at System.Drawing.Printing.PrintingServices.get_DefaultPrinter()
         /home/furt/git/wfurt2-corefx/src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.Unix.cs(70,0): at System.Drawing.Printing.PrinterSettings..ctor()
         /home/furt/git/wfurt2-corefx/src/System.Drawing.Common/tests/Printing/PrinterSettingsTests.cs(224,0): at System.Drawing.Printing.Tests.PrinterSettingsTests.MaximumPage_SetValue_ReturnsExpected(Int32 maximumPage)
         ----- Inner Stack Trace -----
         /home/furt/git/wfurt2-corefx/src/System.Drawing.Common/src/System/Drawing/Printing/LibcupsNative.cs(44,0): at System.Drawing.Printing.LibcupsNative.cupsGetDefault()
         /home/furt/git/wfurt2-corefx/src/System.Drawing.Common/src/System/Drawing/Printing/PrintingServices.Unix.cs(107,0): at System.Drawing.Printing.PrintingServices.CheckCupsInstalled()
         /home/furt/git/wfurt2-corefx/src/System.Drawing.Common/src/System/Drawing/Printing/PrintingServices.Unix.cs(64,0): at System.Drawing.Printing.PrintingServices..cctor()
         ----- Inner Stack Trace -----
            at Interop.Libdl.dlopen(String fileName, Int32 flag)
         /home/furt/git/wfurt2-corefx/src/System.Drawing.Common/src/System/Drawing/Printing/LibcupsNative.cs(17,0): at System.Drawing.Printing.LibcupsNative.LoadLibcups()
         /home/furt/git/wfurt2-corefx/src/System.Drawing.Common/src/System/Drawing/Printing/LibcupsNative.cs(12,0): at System.Drawing.Printing.LibcupsNative..cctor()

This is because FreeBSD has dlopen in libc instead of libdl. 
This may be simple as updating src/Common/src/Interop/Unix/Interop.Libraries.cs
libcups.so seems to exit but no testing has been done.

This is part of https://github.com/dotnet/corefx/issues/1626

**Comment by wfurt** [comment]
fixing dlopen makes the test not fail.
=== TEST EXECUTION SUMMARY ===
   System.Drawing.Common.Tests  Total: 1731, Errors: 0, Failed: 0, Skipped: 1327, Time: 0.641s
~/git/corefx/bin/tests/System.Drawing.Common.Tests/netcoreapp-FreeBSD-Debug-x64
Finished running tests. End time=05:16:26. Return value was 0


Most of the skipped tests comes from libgdiplus. That is separate issues. 
Also note that the test has embedded dlopn() code in it self. (Helpers.cs)

**Comment by safern** [comment]
Similar to: https://github.com/dotnet/corefx/issues/25102 which should be taken care of soon once we get the desired API added into the product. https://github.com/dotnet/corefx/issues/17135

**Comment by am11** [comment]
Some library loading APIs have been recently checked in [System.Runtime.InteropServices.netcoreapp.cs](https://github.com/dotnet/corefx/blob/24ecf91/src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.netcoreapp.cs). Is it too early to update [LibcupsNative.cs#L18-L22](https://github.com/dotnet/corefx/blob/24ecf91/src/System.Drawing.Common/src/System/Drawing/Printing/LibcupsNative.cs#L18-L22) to resolve this issue; something like:

```diff
-            IntPtr lib = Interop.Libdl.dlopen("libcups.so", Interop.Libdl.RTLD_NOW);
+            IntPtr lib = Marshal.LoadLibrary("libcups.so");
            if (lib == IntPtr.Zero)
            {
-                lib = Interop.Libdl.dlopen("libcups.so.2", Interop.Libdl.RTLD_NOW);
+                lib = Marshal.LoadLibrary("libcups.so.2");
            }
```

**Comment by wfurt** [comment]
I'll take a look. Many other parts of netcore would put the actual library name to Interop/Library.cs instead of embedding names inside of the specific code.

**Comment by am11** [comment]
@wfurt, this one was updated in Feb #35548. I think we just need to build and test it (once FreeBSD builds are restored). :)

**Comment by wfurt** [comment]
probably. I think this was mostly about loading, not even test execution.
