### ISSUE TITLE
XmlWriterWrapper.CreateFromWriter(XmlWriter writer) return instance with null settings cause test failed

### ISSUE THREAD

**Issue by JimboWei** [dotnet/corefx#24604]
When using following test code : 
```
writer = XmlWriter.Create(serializeFilePath, new XmlWriterSettings());
Atom10ItemFormatter f = new Atom10ItemFormatter(item1);
await f.WriteToAsync(writer);
```
**will throw System.NullReferenceException** : 
System.NullReferenceException : Object reference not set to an instance of an object.
```
      Stack Trace:
            at System.ServiceModel.Syndication.XmlWriterWrapper.CreateFromWriter(XmlWriter writer)
            at System.ServiceModel.Syndication.ExtensibleSyndicationObject.<WriteAttributeExtensionsAsync>d__10.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.ServiceModel.Syndication.Atom10FeedFormatter.<WriteItemContentsAsync>d__79.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.ServiceModel.Syndication.Atom10ItemFormatter.<WriteToAsync>d__19.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.ServiceModel.Syndication.Tests.BasicScenarioTests.<AtomEntryPositiveTest_writeAsync>d__24.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
related product code : 
![image](https://user-images.githubusercontent.com/26701300/31497060-932a3d5a-af12-11e7-847e-6e7033b733ad.png)
 The method `XmlWriterWrapper.CreateFromWriter(XmlWriter writer)` make writer's `settings` property become null and then throw Exception in below code:
![image](https://user-images.githubusercontent.com/26701300/31497405-d87c6206-af13-11e7-8792-53eb2d36aa52.png)

**Comment by danmosemsft** [comment]
@JimboWei does this work the same on .NET FrameworK?

**Comment by JimboWei** [comment]
@danmosemsft  .NET Framework does not have calss `XmlWriterWrapper`

**Comment by JimboWei** [comment]
The method `XmlWriterWrapper.CreateFromWriter(XmlWriter writer)` is to check and make sure that the type of `writer` is {System.ServiceModel.Syndication.XmlWriter**Wrapper**} or `{System.Xml.XmlAsyncCheckWriter}` .
![image](https://user-images.githubusercontent.com/26701300/31530139-facab2d4-af92-11e7-9445-ef1d1a57279d.png)
At **line 144** the code `XmlDictionaryWriter w = XmlDictionaryWriter.CreateDictionaryWriter(writer);` return an instance which type is {System.Xml.XmlDictionaryWriter.Xml**Wrapped**Writer}. it is different with {System.ServiceModel.Syndication.XmlWriter**Wrapper**}.
the code in method at `line 145` also call method `XmlWriterWrapper.CreateFromWriter(XmlWriter writer)` and then throw the exception.
@danmosemsft , @shmao ,I think code at **line 120** and **line 144** have some conflict.

**Comment by shmao** [comment]
@mconnew does your PR fix this?

**Comment by mconnew** [comment]
@shmao, I would expect my RP to fix the WrappedWriter issue.
