### ISSUE TITLE
[Api] StackTraceFormatting{Options} 

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#24796]
## Motivation
Stack traces are very noisy as they *post*-exception stacks (and ones used to produce the exception, like `ThrowHelper`s); that are the same for every exception:
```
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) 
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
   at Program.<DelayedAsync>d__2.MoveNext()
```
When only 
```
   at Program.<DelayedAsync>d__2.MoveNext()
```
Is useful in diagnosing the exception.

A way is needed to discard these post-error helper stacks; to make the stack-trace more useful and less noise.

## Proposed Api

Adds extra .ctor overload + param to `DebuggerNonUserCodeAttribute`

```csharp
[Flags]
public enum StackTraceFormattingOptions
{
    None                   = 0,
    StackTraceHidden       = 1 << 0
    ...
}
```
```csharp
public partial class DebuggerNonUserCodeAttribute
{
    /// <summary>Initializes the <see cref="DebuggerNonUserCodeAttribute"/>.</summary>
    /// <param name="stackTraceOptions">The <see cref="StackTraceFormattingOptions"/> hint.</param>
    public DebuggerNonUserCodeAttribute(StackTraceFormattingOptions stackTraceOptions)
    {
        StackTraceOptions = stackTraceOptions;
    }

    /// <summary>Gets the <see cref="StackTraceFormattingOptions"/>.</summary>
    internal StackTraceFormattingOptions StackTraceOptions { get; }
}
```
Adds StackTrace formatting configuration (which can be switched at runtime; if more detailed traces are needed)
```csharp
[Flags]
public enum StackTraceFormatting
{
    None = 0,
    ExcludeStackTraceHidden   = 1 << 0, // DebuggerNonUserCode /w StackTraceHidden
    ExcludeDispatchBoundaries = 1 << 1,
    ExcludeNonUserCode        = 1 << 2  // DebuggerNonUserCode
    ...
}
```
```csharp
public partial class StackTrace
{
    public static StackTraceFormatting FormattingOptions { get; set; }
}
```

**Related:**
* "Make stack traces readable" https://github.com/dotnet/corefx/issues/24627
* "Improved formatting for async stack traces" https://github.com/dotnet/coreclr/issues/2813
* "Provide an API for traversing/reasoning about async call stacks" https://github.com/dotnet/corefx/issues/1370
* "BuilderMethodAttribute" https://github.com/dotnet/corefx/issues/24795

**Comment by benaadams** [comment]
Superseded by discussion at https://github.com/dotnet/roslyn/issues/22857
