### ISSUE TITLE
ALPN No matching protocol tests fail

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefx#24853]
On Windows they seem to hang and timeout
On Linux they don't throw an exception but return an empty protocol

**Comment by Priya91** [comment]
I debugged the non-matching protocol test failure on windows, it is throwing authenticationexception as expected, but the exception gets thrown as timeout aggregrate exception.

```
System.Net.Security.Tests.SslStreamAlpnTests.SslStream_StreamToStream_Alpn_NonMatchingProtocols_Fail [FAIL]
        System.AggregateException : One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.) (A call to SSPI failed, see inner exception.)
        ---- System.TimeoutException : VirtualNetwork: Timeout reading the next frame.
        ---- System.Security.Authentication.AuthenticationException : A call to SSPI failed, see inner exception.
        -------- System.ComponentModel.Win32Exception : No common application protocol exists between the client and the server. Application protocol negotiation failed
        Stack Trace:
           E:\A\_work\1111\s\src\mscorlib\src\System\ThrowHelper.cs(224,0): at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
           E:\A\_work\1111\s\src\mscorlib\src\System\Threading\Tasks\Task.cs(4651,0): at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
           E:\A\_work\1111\s\src\mscorlib\src\System\Threading\Tasks\Task.cs(4502,0): at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
           E:\corefx\src\System.Net.Security\tests\FunctionalTests\SslStreamAlpnTests.cs(201,0): at System.Net.Security.Tests.SslStreamAlpnTests.SslStream_StreamToStream_Alpn_NonMatchingProtocols_Fail()
           ----- Inner Stack Trace #1 (System.TimeoutException) -----
           E:\corefx\src\Common\tests\System\Net\VirtualNetwork\VirtualNetwork.cs(42,0): at System.Net.Test.Common.VirtualNetwork.ReadFrame(Boolean server, Byte[]& buffer)
           E:\corefx\src\Common\tests\System\Net\VirtualNetwork\VirtualNetworkStream.cs(118,0): at System.Net.Test.Common.VirtualNetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
           E:\corefx\src\Common\tests\System\Net\VirtualNetwork\VirtualNetworkStream.cs(138,0): at System.Net.Test.Common.VirtualNetworkStream.<>c__DisplayClass27_0.<ReadAsync>b__0()
           E:\A\_work\1111\s\src\mscorlib\src\System\Threading\Tasks\future.cs(610,0): at System.Threading.Tasks.Task`1.InnerInvoke()
           E:\A\_work\1111\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs(151,0): at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
           E:\A\_work\1111\s\src\mscorlib\src\System\Threading\Tasks\Task.cs(2440,0): at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
           --- End of stack trace from previous location where exception was thrown ---
           E:\A\_work\1111\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionServicesCommon.cs(130,0): at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           E:\A\_work\1111\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs(152,0): at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           E:\A\_work\1111\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs(563,0): at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
           E:\corefx\src\System.Net.Security\src\System\Net\FixedSizeReader.cs(56,0): at System.Net.FixedSizeReader.<ReadPacketAsync>d__1.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
           E:\A\_work\1111\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionServicesCommon.cs(130,0): at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           E:\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs(768,0): at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
           E:\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs(739,0): at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
           E:\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.cs(194,0): at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
           E:\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.cs(381,0): at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__44_1(IAsyncResult iar)
           E:\A\_work\1111\s\src\mscorlib\src\System\Threading\Tasks\FutureFactory.cs(533,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
           ----- Inner Stack Trace #2 (System.Security.Authentication.AuthenticationException) -----
           E:\A\_work\1111\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionServicesCommon.cs(130,0): at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           E:\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs(1030,0): at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception, CancellationToken cancellationToken)
           E:\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs(841,0): at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest, CancellationToken cancellationToken)
           E:\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs(826,0): at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest, CancellationToken cancellationToken)
           E:\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs(1011,0): at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest, CancellationToken cancellationToken)
           E:\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs(1185,0): at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
           --- End of stack trace from previous location where exception was thrown ---
           E:\A\_work\1111\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionServicesCommon.cs(130,0): at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           E:\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs(768,0): at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
           E:\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs(739,0): at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
           E:\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.cs(248,0): at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
           E:\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.cs(416,0): at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__48_1(IAsyncResult iar)
           E:\A\_work\1111\s\src\mscorlib\src\System\Threading\Tasks\FutureFactory.cs(533,0): at System.Threading.Ta
```

**Comment by Drawaes** [comment]
As mentioned this error is showing as a timeout because of the Virtual Network timing out when it hangs, you can see this when you step through, it seems to be hanging waiting for a packet

**Comment by Priya91** [comment]
@stephentoub Why this issue is reopened? Oh i see that entire PR was reverted, this was in a separate commit.

**Comment by stephentoub** [comment]
> Why this issue is reopened?

1) The PR was squashed when merged; there was only one commit to revert.
2) We should not be closing issues when there are still tests ActiveIssue'd against that issue number, as there is here: https://github.com/dotnet/corefx/blob/94688adc0ea82cdea19d7b6963c00fe9f98c86e3/src/System.Net.Security/tests/FunctionalTests/SslStreamAlpnTests.cs#L119
3) I'm not convinced that was the right fix; AuthenticateAsClientAsync should not be resulting in a TimeoutException unless there's a valid reason for it to timeout, which I'm not seeing here.  More likely is that the test was hitting the same deadlock that was causing the other test to fail, and that was manifesting as a timeout.

**Comment by Priya91** [comment]
Yeah, the activeissue is there because the code got reverted, so issue is also open. So if the commits are getting squashed, is it best practice to have separate PRs for distinct work items, since separate commits are not actually making reverts or separating work any easier.

Point 3 maybe true, with fixing other test, will have more info.

**Comment by stephentoub** [comment]
> Yeah, the activeissue is there because the code got reverted,

No, the ActiveIssue was there before it was reverted.  Your change https://github.com/dotnet/corefx/pull/24857 didn't remove the ActiveIssue.

> So if the commits are getting squashed, is it best practice to have separate PRs for distinct work items, since separate commits are not actually making reverts or separating work any easier.

In general a PR should be for one purpose, and its commits should be squashed.  If for some reason it needs to be for multiple distinct, purposes, then there should be a commit for each, and it shouldn't be squashed.
