### ISSUE TITLE
IndexOutOfRangeException from Socket.MultipleAddressConnectAsyncResult.get_RemoteEndPoint

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#24869]
https://mc.dot.net/#/user/Drawaes/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/3cac46b196961558ff0ddf1858e8a3429a7d643e/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.DnsEndPointTest~2FSocket_BeginConnectDnsEndPoint_Failure
```
Unhandled Exception of Type Xunit.Sdk.ThrowsException
Message :
Assert.Throws() Failure
Expected: typeof(System.Net.Sockets.SocketException)
Actual:   typeof(System.IndexOutOfRangeException): Index was outside the bounds of the array.
Stack Trace :
   at System.Net.Sockets.Socket.MultipleAddressConnectAsyncResult.get_RemoteEndPoint() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 5127
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 2458
   at System.Net.Sockets.Tests.DnsEndPointTest.<>c__DisplayClass8_0.<Socket_BeginConnectDnsEndPoint_Failure>b__1() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Sockets/tests/FunctionalTests/DnsEndPointTest.cs:line 164
```

**Comment by stephentoub** [comment]
This looks like a bug in Socket.EndConnect, on all platforms (we just happened to hit the race condition in a Linux run).  EndConnect is accessing the MultipleAddressConnectAsyncResult.RemoteEndPoint property before it's guaranteed that the operation has completed, i.e. before castedAsyncResult.InternalWaitForCompletion(); is called.  If EndConnect is called before the IAsyncResult has completed (e.g. if there's no callback and someone just does BeginConnect followed synchronously by EndConnect, as this test is doing), it's thus going to access the RemoteEndPoint before the information is fully available or published.  And in the case of this failure, if it happens to access it while it's being published, it could do multiple reads on the addresses and find that the length has changed between accesses, invalidating the checks.

**Comment by stephentoub** [comment]
(It also appears to be a bug in .NET Framework.)
