### ISSUE TITLE
EventLogEntryCollectionTests.CheckingEntryEqualityAndIndex failed with ArgumentException

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#24874]
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/94474b7e9325802a019eace4ffce5cb6add96b0b/workItem/System.Diagnostics.EventLog.Tests/analysis/xunit/System.Diagnostics.Tests.EventLogEntryCollectionTests~2FCheckingEntryEqualityAndIndex
```
Unhandled Exception of Type System.ArgumentException
Message :
System.ArgumentException : Index -1 is out of bounds.
Stack Trace :
   at System.Diagnostics.EventLogInternal.GetEntryAt(Int32 index)
   at System.Diagnostics.EventLogEntryCollection.get_Item(Int32 index)
   at System.Diagnostics.Tests.EventLogEntryCollectionTests.CheckingEntryEqualityAndIndex()
```

**Comment by stephentoub** [comment]
Failed again here:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/94474b7e9325802a019eace4ffce5cb6add96b0b/workItem/System.Diagnostics.EventLog.Tests/analysis/xunit/System.Diagnostics.Tests.EventLogEntryCollectionTests~2FCheckingEntryEqualityAndIndex
```
Unhandled Exception of Type System.ArgumentException
Message :
System.ArgumentException : Index -1 is out of bounds.
Stack Trace :
   at System.Diagnostics.EventLogInternal.GetEntryAt(Int32 index)
   at System.Diagnostics.EventLogEntryCollection.get_Item(Int32 index)
   at System.Diagnostics.Tests.EventLogEntryCollectionTests.CheckingEntryEqualityAndIndex()
```

**Comment by danmosemsft** [comment]
@Anipik apparently `eventLog.Entries.Count` is returning 0 when called directly after `eventLog.WriteEntry(message)` .. that's a bit worrying

**Comment by danmosemsft** [comment]
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/b9542d9623434115786bd83d607168072830bf19/workItem/System.Diagnostics.EventLog.Tests/analysis/xunit/System.Diagnostics.Tests.EventLogEntryCollectionTests~2FCheckingEntryInEquality

again
```
System.ArgumentException : Index -1 is out of bounds.
Stack Trace :
   at System.Diagnostics.EventLogInternal.GetEntryAt(Int32 index)
   at System.Diagnostics.EventLogEntryCollection.get_Item(Int32 index)
   at System.Diagnostics.Tests.EventLogEntryCollectionTests.CheckingEntryInEquality()
```

**Comment by danmosemsft** [comment]
Assuming it's some kind of latency issue the best I can think of is to have some wrapper like 
```c#
private void WaitForEventLog(EventLog eventLog, int entriesExpected)
{
        int tries = 0;
       while (eventLog.Entries.Count < entriesExpected && tries < 20)
       {
                Thread.Sleep(100);
                tries++;
      }

      Assert.NotEqual(eventLog.Entries.Count == entriesExpected);             
  }
```
then put this between WriteEntry and reading the entries?

**Comment by Jiayili1** [comment]
failed again in Master branch, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171030.01/workItem/System.Diagnostics.EventLog.Tests/analysis/xunit/System.Diagnostics.Tests.EventLogEntryCollectionTests~2FCheckingEntryInEquality

**Comment by stephentoub** [comment]
Failed again here:
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/0a16ce865e5921d9c9351bf912f0293b4a3a80fe/workItem/System.Diagnostics.EventLog.Tests/analysis/xunit/System.Diagnostics.Tests.EventLogEntryCollectionTests~2FCheckingEntryEqualityAndIndex
```
Unhandled Exception of Type System.ArgumentException
Message :
System.ArgumentException : Index -1 is out of bounds.
Stack Trace :
   at System.Diagnostics.EventLogInternal.GetEntryAt(Int32 index) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.EventLog\src\System\Diagnostics\EventLogInternal.cs:line 881
   at System.Diagnostics.EventLogEntryCollection.get_Item(Int32 index) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.EventLog\src\System\Diagnostics\EventLogEntryCollection.cs:line 30
   at System.Diagnostics.Tests.EventLogEntryCollectionTests.<>c__DisplayClass3_1.<CheckingEntryEqualityAndIndex>b__2() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.EventLog\tests\EventLogEntryCollectionTests.cs:line 84
   at System.Diagnostics.Tests.Helpers.RetryOnWin7[T](Func`1 func) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.EventLog\tests\Helpers.cs:line 36
   at System.Diagnostics.Tests.EventLogEntryCollectionTests.CheckingEntryEqualityAndIndex() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.EventLog\tests\EventLogEntryCollectionTests.cs:line 84
```

**Comment by stephentoub** [comment]
Failed again here:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/0582579451b6d6c5701f9fa2a407b060a03e8925/workItem/System.Diagnostics.EventLog.Tests/analysis/xunit/System.Diagnostics.Tests.EventLogEntryCollectionTests~2FCheckingEntryInEquality
```
Unhandled Exception of Type System.ArgumentException
Message :
System.ArgumentException : Index -1 is out of bounds.
Stack Trace :
   at System.Diagnostics.EventLogInternal.GetEntryAt(Int32 index) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.EventLog\src\System\Diagnostics\EventLogInternal.cs:line 881
   at System.Diagnostics.EventLogEntryCollection.get_Item(Int32 index) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.EventLog\src\System\Diagnostics\EventLogEntryCollection.cs:line 30
   at System.Diagnostics.Tests.EventLogEntryCollectionTests.<>c__DisplayClass4_1.<CheckingEntryInEquality>b__3() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.EventLog\tests\EventLogEntryCollectionTests.cs:line 113
   at System.Diagnostics.Tests.Helpers.RetryOnWin7[T](Func`1 func) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.EventLog\tests\Helpers.cs:line 26
   at System.Diagnostics.Tests.EventLogEntryCollectionTests.CheckingEntryInEquality() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.EventLog\tests\EventLogEntryCollectionTests.cs:line 113
```

**Comment by danmosemsft** [comment]
Again
https://mc.dot.net/#/user/KKhurin/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/05e96931232ee754fe1438edecaec45e1aecbdfa/workItem/System.Diagnostics.EventLog.Tests/analysis/xunit/System.Diagnostics.Tests.EventLogEntryCollectionTests~2FCheckingEntryEqualityAndIndex

**Comment by danmosemsft** [comment]
Was CheckingEntryEqualityAndIndex

**Comment by stephentoub** [comment]
Failed again here:
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/354af156af0a279d8fc1000885eee19f94ef06fc/workItem/System.Diagnostics.EventLog.Tests/analysis/xunit/System.Diagnostics.Tests.EventLogEntryCollectionTests~2FCheckingEntryInEquality
```
Unhandled Exception of Type Xunit.Sdk.EqualException
Message :
Assert.Equal() Failure
Expected: 2
Actual:   0
Stack Trace :
   at System.Diagnostics.Tests.Helpers.WaitForEventLog(EventLog eventLog, Int32 entriesExpected) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.EventLog\tests\Helpers.cs:line 69
   at System.Diagnostics.Tests.EventLogEntryCollectionTests.CheckingEntryInEquality() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.EventLog\tests\EventLogEntryCollectionTests.cs:line 116
```

**Comment by danmosemsft** [comment]
@Anipik as noted in the other issue I think sadly the first thing to try is more retries and/or backoffs on the delays. I suggest making it try for 30 seconds or something super large like that.

**Comment by stephentoub** [comment]
Failed again here:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/5226/
```
Message :
Assert.Equal() Failure
Expected: 2
Actual:   0
Stack Trace :
   at System.Diagnostics.Tests.Helpers.WaitForEventLog(EventLog eventLog, Int32 entriesExpected) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.EventLog\tests\Helpers.cs:line 80
   at System.Diagnostics.Tests.EventLogEntryCollectionTests.CheckingEntryInEquality() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.EventLog\tests\EventLogEntryCollectionTests.cs:line 116
```

**Comment by Anipik** [comment]
@stephentoub  can you check the link once ...as i am not able to see the failed eventlog test here .
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/31f6c1ec570f5508f26bcf2cb210df4df9c9554c

**Comment by stephentoub** [comment]
> as i am not able to see the failed eventlog test here

I re-ran the tests; it likely got overwritten.

**Comment by Anipik** [comment]
can i access the console output of that run somehow ...as we added debugging info last time to check the reason of the failure.

**Comment by stephentoub** [comment]
@dotnet/dnceng, is there a way to see the old log for a run where it was then re-run?

**Comment by maririos** [comment]
Not easily. Mission Control shows the logs of the latest runs.
We could get the logs from the DB directly though, so if you have the commit and the name of the job you want the log for, we could give you the information

**Comment by stephentoub** [comment]
Failed again here:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/da55d79ba3809ded4091a9c2cb6636754ccca070/workItem/System.Diagnostics.EventLog.Tests/wilogs
```
2017-11-13 23:55:39,144: INFO: proc(54): run_and_log_output: Output: Discovering: System.Diagnostics.EventLog.Tests
2017-11-13 23:55:39,380: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Diagnostics.EventLog.Tests
2017-11-13 23:55:39,441: INFO: proc(54): run_and_log_output: Output: Starting:    System.Diagnostics.EventLog.Tests
2017-11-13 23:58:18,380: INFO: proc(54): run_and_log_output: Output: 152 seconds
2017-11-13 23:58:18,489: INFO: proc(54): run_and_log_output: Output:    System.Diagnostics.Tests.EventLogEntryCollectionTests.CheckingEntryInEquality [FAIL]
2017-11-13 23:58:18,489: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2017-11-13 23:58:18,489: INFO: proc(54): run_and_log_output: Output:       Expected: 2
2017-11-13 23:58:18,489: INFO: proc(54): run_and_log_output: Output:       Actual:   0
2017-11-13 23:58:18,505: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-11-13 23:58:18,566: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.EventLog\tests\Helpers.cs(80,0): at System.Diagnostics.Tests.Helpers.WaitForEventLog(EventLog eventLog, Int32 entriesExpected)
2017-11-13 23:58:18,566: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.EventLog\tests\EventLogEntryCollectionTests.cs(116,0): at System.Diagnostics.Tests.EventLogEntryCollectionTests.CheckingEntryInEquality()
2017-11-13 23:58:18,802: INFO: proc(54): run_and_log_output: Output: Finished:    System.Diagnostics.EventLog.Tests
2017-11-13 23:58:18,816: INFO: proc(54): run_and_log_output: Output: 
2017-11-13 23:58:18,816: INFO: proc(54): run_and_log_output: Output: === TEST EXECUTION SUMMARY ===
2017-11-13 23:58:18,816: INFO: proc(54): run_and_log_output: Output:    System.Diagnostics.EventLog.Tests  Total: 62, Errors: 0, Failed: 1, Skipped: 0, Time: 159.344s
```

**Comment by danmosemsft** [comment]
If it didn't happen after 152 seconds then it never will... Maybe this is limited to old OS? Or the whole test could try again? Or make them manual tests only?

**Comment by stephentoub** [comment]
Let's please disable the test.  It's failing frequently.

Failed again here:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/72808f373001bce73a3253275d5491d4e96a08a5/workItem/System.Diagnostics.EventLog.Tests/wilogs
```
2017-11-14 15:32:23,766: INFO: proc(54): run_and_log_output: Output: Discovering: System.Diagnostics.EventLog.Tests
2017-11-14 15:32:24,266: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Diagnostics.EventLog.Tests
2017-11-14 15:32:24,312: INFO: proc(54): run_and_log_output: Output: Starting:    System.Diagnostics.EventLog.Tests
2017-11-14 15:34:57,875: INFO: proc(54): run_and_log_output: Output: 152 seconds
2017-11-14 15:34:57,984: INFO: proc(54): run_and_log_output: Output:    System.Diagnostics.Tests.EventLogEntryCollectionTests.CheckingEntryInEquality [FAIL]
2017-11-14 15:34:57,984: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2017-11-14 15:34:57,984: INFO: proc(54): run_and_log_output: Output:       Expected: 2
2017-11-14 15:34:57,984: INFO: proc(54): run_and_log_output: Output:       Actual:   0
2017-11-14 15:34:58,000: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-11-14 15:34:58,078: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.EventLog\tests\Helpers.cs(80,0): at System.Diagnostics.Tests.Helpers.WaitForEventLog(EventLog eventLog, Int32 entriesExpected)
2017-11-14 15:34:58,078: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.EventLog\tests\EventLogEntryCollectionTests.cs(116,0): at System.Diagnostics.Tests.EventLogEntryCollectionTests.CheckingEntryInEquality()
2017-11-14 15:34:58,250: INFO: proc(54): run_and_log_output: Output: Finished:    System.Diagnostics.EventLog.Tests
```

**Comment by stephentoub** [comment]
Failed again here, on Windows 8:
https://mc.dot.net/#/user/tmds/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/953d7e638fe93fb04b77f57d9c4ef37fb5a7d624/workItem/System.Diagnostics.EventLog.Tests/wilogs
```
2017-11-14 15:41:26,361: INFO: proc(54): run_and_log_output: Output: Discovering: System.Diagnostics.EventLog.Tests
2017-11-14 15:41:26,706: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Diagnostics.EventLog.Tests
2017-11-14 15:41:26,753: INFO: proc(54): run_and_log_output: Output: Starting:    System.Diagnostics.EventLog.Tests
2017-11-14 15:44:01,585: INFO: proc(54): run_and_log_output: Output: 153 seconds
2017-11-14 15:44:01,710: INFO: proc(54): run_and_log_output: Output:    System.Diagnostics.Tests.EventLogEntryCollectionTests.CheckingEntryInEquality [FAIL]
2017-11-14 15:44:01,710: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2017-11-14 15:44:01,710: INFO: proc(54): run_and_log_output: Output:       Expected: 2
2017-11-14 15:44:01,710: INFO: proc(54): run_and_log_output: Output:       Actual:   0
2017-11-14 15:44:01,726: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-11-14 15:44:01,819: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.EventLog\tests\Helpers.cs(80,0): at System.Diagnostics.Tests.Helpers.WaitForEventLog(EventLog eventLog, Int32 entriesExpected)
2017-11-14 15:44:01,819: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.EventLog\tests\EventLogEntryCollectionTests.cs(116,0): at System.Diagnostics.Tests.EventLogEntryCollectionTests.CheckingEntryInEquality()
2017-11-14 15:44:02,161: INFO: proc(54): run_and_log_output: Output: Finished:    System.Diagnostics.EventLog.Tests
```

**Comment by wtgodbe** [comment]
@stephentoub what should be done with this issue now that the test is disabled?

**Comment by stephentoub** [comment]
> what should be done with this issue now that the test is disabled?

It should remain open until the issue is fixed.

**Comment by wtgodbe** [comment]
@Anipik @danmosemsft closing this as resolved by https://github.com/dotnet/corefx/pull/25695, re-open if that's not the case
