### ISSUE TITLE
System.Net.Http.CurlException: SSL connect error

### ISSUE THREAD

**Issue by rohan-buchner** [dotnet/corefx#24952]
I have an n-tier dynamic-ish application that currently builds its elastic indexes I'm app startup, while this was ok to get things going, I'd prefer to have a small CLI application/util that I can later re-use in some scripts and or run ad hoc if i need to do things like, creating a new instance, seeding mock data etc.

When I use the exact same code that worked in my dotnetcore web apps startup, in my console app. I get the following issue.

    Invalid NEST response built from a unsuccessful low level call on PUT: /jobs-ng
    # Audit trail of this API call:
     - [1] BadRequest: Node: https://localhost:9200/ Took: 00:00:01.3948230
    # OriginalException: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL connect error
       at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
       at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
       --- End of inner exception stack trace ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
       at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:line 78
    # Request:
    <Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
    # Response:
    <Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>

So far my best guess is that the native console app is missing something that the default AspNetCore web app projects provide, but as to what, I dont know? 

I have set `DisableDirectStreaming()` as per the error log, but still no change.

I believe this might be a bug within dotnetcore, but I'm hoping someone knows of a work around, or way around this issue for the time being (other that having this code be part of the we apps startup?)

**Comment by bassebaba** [comment]
I have the same problem.
However, If i try/catch and resend the same request in the catch, it works the second time...

**Comment by Priya91** [comment]
@rohan-buchner It's not clear what you are trying to do from the description. Can you provide the repro code?

Also what version of libcurl do you have, what is the crypto backend, openssl/nss/gnutls? Which linux distro and version you are running on?

Did you compare what request is being sent out on the wire in both cases? Since the error says ssl connect error, maybe wrong certs are being used?

**Comment by rohan-buchner** [comment]
@Priya91 I've managed to get past the issue by not using https. I have however pinpointed that my issue pertains to [this](https://github.com/dotnet/corefx/issues/19718) current open bug. Also please see [my question on StackOverflow](https://stackoverflow.com/questions/47015634/net-core-console-application-ssl-connect-error/47114694#47114694) with comments by Russ Cam who is an engineer at Elastic.
