### ISSUE TITLE
System.Json: JsonPrimitive.ToString() throws unexpectedly

### ISSUE THREAD

**Issue by grant-d** [dotnet/corefx#25020]
The following throws; I would expect to return the `Guid` in `string` form. Note that this is _not_ one of the expected errors that are explicitly `thrown` for some types (see notes on stack trace).

I see that the units support this behavior, but it seems to be an inconsistent design.

```C#
  var p = new JsonPrimitive(Guid.NewGuid());
  var t = p.JsonType;
  var s = p.ToString(); // FormatException

  // Note that GetFormattedString explicitly throws for some types
  // But that's not happening here, since it's making it all the way to Guid.ToString()
  System.FormatException
    Message=Format String can be only "D", "d", "N", "n", "P", "p", "B", "b", "X" or "x".
    Source=System.Private.CoreLib
    StackTrace:
     at System.Guid.ToString(String format, IFormatProvider provider)
     at System.Json.JsonPrimitive.GetFormattedString()
     at System.Json.JsonValue.SaveInternal(TextWriter w)
     at System.Json.JsonValue.ToString()
```

_See original issue summary [here](https://github.com/dotnet/corefx/issues/25005), @karelz suggested I submit separately_

**Comment by grant-d** [comment]
@danmosemsft, @karelz, I am going to cut short my losses and move to a different json lib.
I don't want to waste your or my time on fixing this - it requires a complete overhaul in some places.
I did not realize it was a port, so expected it to be well-designed and performant.

Feel free to open again if you want to fix the issues anyway.
