### ISSUE TITLE
Unrecognized configuration section system.net in .net core 2

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#25127]
@techaimail commented on [Wed Nov 08 2017](https://github.com/dotnet/core/issues/1067)

When include system.net section in the application configuration file on .net core 2 throw the following exception. In the API reference mailsettings is supported for SmtpClient.
```
Application startup exception: System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section system.net. (E:\WEBSITES\pysesf-webapps\FileExporter\Service\ESF.FileExporter.QueryWebService.dll.config line 13)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.get_ConnectionStrings()

```

**Comment by maryamariyan** [comment]
@techaimail this is a documentation issue- we don't support these sections on Core. You need to set the relevant properties on `SmtpClient` directly.  I'll get an issue open on the docs
