### ISSUE TITLE
Implementation of SecureChannel.cs in .NET Core does not verify client cert issuers

### ISSUE THREAD

**Issue by softwaretecture** [dotnet/corefx#25135]
Problem description:

A Web Api (.NET Core 2.0) is hosted via Kestrel on Windows 10, MobiLinux and Docker. 
It's configured in the code to request a client certificate.
Kestrel is configured with a CA issued server certificate and exposes port 443.

Testing
1. A client application written in .NET 4.5-6 uses a self-signed client certificate (using makecert)
2. A client application written in .NET Core 1.1 and 2.0 uses the same self-signed client certificate (using makecert).

In a case of .NET 4.5X, the code seems to verify the list of cert issuers from the server against the client certificate it's trying to send. It finds no matching CA and fails to send the cert to the server and closes the connection as expected by TLS spec.

In a case of .NET Core, the code seems to not perform the same comparison and just sends the client cert to the server and allows the connection to remain open.
A potential security vulnerability is seems.
A support case  [REG:117102516555348] with Microsoft has been opened previously to explore this issue.

**Comment by davidsh** [comment]
Can you confirm what .NET Core / .NET Framework APIs are being used on the client side?  Is this an HTTP API being used (HttpWebRequest, HttpClient)?  Or, is this SslStream?

In terms of HTTP APIs, on .NET Core, HttpWebRequest and HttpClient are using native WinHTTP underneath.  And we have an active issue about issuing the trusted issuers list if sent by the server.

https://github.com/dotnet/corefx/issues/3891

**Comment by davidsh** [comment]
Also, please confirm what OS is being used for the client.  Is it Windows or Linux?  You mentioned that the server is running on Linux.  But what about the client?  I was assuming it was running on Windows since you are comparing the behavior of .NET Framework.

**Comment by softwaretecture** [comment]
.NET 4.52 client
=================       
 public static string GetSecureApiResults()
        {
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            using (var handler = new WebRequestHandler())
            {
                                                                var clientCert = GetCertFromStore();
                handler.ClientCertificates.Add(clientCert);
                using (var httpClient = new HttpClient(handler))
                {
                                                                                httpClient.BaseAddress = new Uri(@"https://localhost:32768");
                                                                                return httpClient.GetStringAsync(@"api/test").Result;
                }
            }


.NET Core 1.1 code
================================
          using (var handler = new HttpClientHandler())
            {
                handler.ClientCertificateOptions = ClientCertificateOption.Manual;

                handler.ClientCertificates.Add(clientCertificate);


                using (var httpClient = new HttpClient(handler))
                {

                        var response = await httpClient.GetAsync(url);
                    return response;
                }
            }

**Comment by softwaretecture** [comment]
The test set up can be reproduced on a single Windows 10 machine as follows:
Server:
Windows 10 -> MobiLinux ->Docker (latest) -> container -> Kestrel (Web Api .NET Core 2.0)
Client:
Windows 10 -> Console App (.NET 4.52/.NET Core 1.1/2.0)

**Comment by davidsh** [comment]
>Client: Windows 10 -> Console App (.NET 4.52/.NET Core 1.1/2.0)

Ok.  Thx.  So the behavior difference for Windows client between .NET Framework and .NET Core regarding use (or non-use) of Trusted Issuers List from server is due to #3891.

**Comment by softwaretecture** [comment]
Interestingly enough, if the server Web API is hosted on the  same Windows machine (not in Docker), both .NET 4.5 and .NET Core clients work. On Linux .NET 4.5 does not, which prompted us to open an issue with Microsoft about .NET 4.5. Turns out it, it works as expected.

**Comment by davidsh** [comment]
>if the server Web API is hosted on the same Windows machine (not in Docker), both .NET 4.5 and .NET Core clients work.

The default for modern Windows OS (I think starting in Windows Server 2008 R2, not sure) is by default not to send any Trusted Issuers List at all.  If so, there is no paring down based on that.  Since the Trusted Issuers List could be large, it tends to overflow TLS/SSL packet limits.  So, the tendency is for many servers to not send any such list.

**Comment by davidsh** [comment]
See: http://netsekure.org/2011/04/tls-client-authentication-and-trusted-issuers-list/

**Comment by davidsh** [comment]
cc: @bartonjs

**Comment by softwaretecture** [comment]
Below is some tracing from .NET 4.5

System.Net Information: 0 : [17444] InitializeSecurityContext(In-Buffers count=2, Out-Buffer length=0, returned code=CredentialsNeeded).
    ProcessId=17080
    ThreadId=7
    DateTime=2017-10-27T20:58:10.5900945Z
    Timestamp=18642633601
    Callstack=   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Diagnostics.TraceEventCache.get_Callstack()
   at System.Diagnostics.TraceListener.WriteFooter(TraceEventCache eventCache)
   at System.Diagnostics.TraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at System.Net.Logging.PrintLine(TraceSource traceSource, TraceEventType eventType, Int32 id, String msg)
   at System.Net.SSPIWrapper.InitializeSecurityContext(SSPIInterface SecModule, SafeFreeCredentials credential, SafeDeleteContext& context, String targetName, ContextFlags inFlags, Endianness datarep, SecurityBuffer[] inputBuffers, SecurityBuffer outputBuffer, ContextFlags& outFlags)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
   at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
   at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
System.Net Information: 0 : [17444] SecureChannel#41622463 - **We have user-provided certificates. The server has specified 165 issuer(s). Looking for certificates that match any of the issuers.**

**Comment by softwaretecture** [comment]
"The default for modern Windows OS (I think starting in Windows Server 2008 R2, not sure) is by default not to send any Trusted Issuers List at all. If so, there is no paring down based on that. Since the Trusted Issuers List could be large, it tends to overflow TLS/SSL packet limits. So, the tendency is for many servers to not send any such list."

Does this mean that Windows 10 doesn't send the list of issuers and MobiLinux does therefore .NET 4.5 client fails since it receives the list and can't find the matching issuer from Linux where as it receives no issuers from Windows so it proceeds?

**Comment by davidsh** [comment]
>Does this mean that Windows 10 doesn't send the list of issuers and MobiLinux does therefore .NET 4.5 client fails since it receives the list and can't find the matching issuer from Linux where as it receives no issuers from Windows so it proceeds?

The DEFAULT for current Windows OS is not send a Trusted Issuers List.  You can change the default, though, using the registry.

See: https://technet.microsoft.com/en-us/library/dn786429(v=ws.11).aspx

**Comment by softwaretecture** [comment]
@davidsh That's exactly the answer I was looking for to explain the behavior differences on Windows vs Linux. Thank you for that. I guess issue still remains regarding .NET Core not reacting to the list of issuers on either OS.

**Comment by davidsh** [comment]
>I guess issue still remains regarding .NET Core not reacting to the list of issuers on either OS.

Yes, Once #3891 is addressed (.NET Core/Windows), it will look at the Trusted Issuers List, if present.

**Comment by davidsh** [comment]
Closing this as a duplicate of #3891.
