### ISSUE TITLE
PipeTransmissionMode.Message is not supported on macOS

### ISSUE THREAD

**Issue by rianjs** [dotnet/corefx#25161]
Is it on the roadmap?

```
Exception has occurred: CLR/System.PlatformNotSupportedException
An unhandled exception of type 'System.PlatformNotSupportedException' occurred in System.IO.Pipes.dll: 'Message transmission mode is not supported on this platform.'
   at System.IO.Pipes.NamedPipeServerStream.Create(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability)
   at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability)
   at SpellerCore.UniversalPipeServer..ctor(String pipeName, Guid serverId, Int32 maxNumberOfServerInstances, ILog logger)
   at SpellerCore.NamedPipeSpellerController.StartNamedPipeServer()
   at SpellerDaemon.ServiceLauncher.Main(String[] args) in /Users/rianjs/dev/...
```

**Comment by stephentoub** [comment]
How would it be implemented?

**Comment by rianjs** [comment]
Yeah, someone else has just pointed out that *nix systems don't have a concept of messages, which I didn't know. I guess my question now is [why it's in Netstandard](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipes.pipetransmissionmode?view=netstandard-2.0)? Should it be?

**Comment by stephentoub** [comment]
> Should it be?

We try not to subset types, putting some of a type into the standard and some not, as for the not part there's then no way to use that functionality on platforms where it is implemented.  In such cases we've generally opted to include it, try hard to make it work everywhere, and where we can't fall back to either partial implementations or throwing PlatformNotSupportedExceptions; you can then do platform detection to use the functionality on platforms where it's available and fall back to something else on those where it isn't.  The analyzer described at https://blogs.msdn.microsoft.com/dotnet/2017/10/31/introducing-api-analyzer/ is also evolving to make it easier to help, though I don't believe it's functionality/data is up-to-date for this particular case.
cc: @terrajobst

**Comment by stephentoub** [comment]
I don't know of a way to properly implement this on Unix.  If you have suggestions or we discover a way, this can be re-opened.  In the meantime, though, it's not actionable so I'm going to close it.  Thanks.
