### ISSUE TITLE
PerformanceCounterCategory_Create_Obsolete test failed with InvalidOperationException

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#25228]
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/3eb7408de3fa474f21e4107091731f7d412ef9f2/workItem/System.Diagnostics.PerformanceCounter.Tests/analysis/xunit/System.Diagnostics.Tests.PerformanceCounterCategoryTests~2FPerformanceCounterCategory_Create_Obsolete
```
Unhandled Exception of Type System.InvalidOperationException
Message :
System.InvalidOperationException : Cannot load Counter Name data because an invalid index '' was read from the registry.
Stack Trace :
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterLib.cs:line 1097
   at System.Diagnostics.PerformanceCounterLib.get_NameTable() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterLib.cs:line 235
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterLib.cs:line 167
   at System.Diagnostics.PerformanceCounterLib.CategoryExists(String machine, String category) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterLib.cs:line 275
   at System.Diagnostics.PerformanceCounterCategory.Exists(String categoryName, String machineName) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterCategory.cs:line 432
   at System.Diagnostics.PerformanceCounterCategory.Exists(String categoryName) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterCategory.cs:line 414
   at System.Diagnostics.Tests.Helpers.DeleteCategory(String name) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\tests\Helpers.cs:line 40
   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterCategoryTests.cs:line 115
```

**Comment by tarekgh** [comment]
https://mc.dot.net/#/user/adriangodong/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/df8d80943850d79ac38ac0c0ab921486b0c2b4fa/workItem/System.Diagnostics.PerformanceCounter.Tests/analysis/xunit/System.Diagnostics.Tests.PerformanceCounterCategoryTests~2FPerformanceCounterCategory_Create_Obsolete
