### ISSUE TITLE
XmlSerializer.CreateWriter Throws NotImplementedException

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#25298]
The tests being added by https://github.com/dotnet/wcf/compare/master...imcarolwang:SFxTest?expand=1 got the following exceptions. We need to investigate if it's issue in serialization or in WCF.

```
Exception details: System.ServiceModel.CommunicationException: There was an error in serializing body of message :   'There was an error generating the XML document.'.  Please see InnerException for more details. 
---> System.InvalidOperationException: There was an error generating the XML document. 
---> System.NotImplementedException: The method or  operation is not implemented.
               at System.Xml.Serialization.XmlSerializer.CreateWriter() in E:\A\_work\1360\s\corefx\src\System.Private.Xml\src\Sy  stem\Xml\Serialization\XmlSerializer.cs:line 1039
at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespa  ces, String encodingStyle, String id) in E:\A\_work\1360\s\corefx\src\System.Private.Xml\src\System\Xml\Serialization  \XmlSerializer.cs:line 465
     --- End of inner exception stack trace ---
     at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespa  ces, String encodingStyle, String id) in E:\A\_work\1360\s\corefx\src\System.Private.Xml\src\System\Xml\Serialization  \XmlSerializer.cs:line 514
     at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespa  ces) in E:\A\_work\1360\s\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializer.cs:line 437
     at System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.SerializeBody(XmlDictionaryWriter writer, Messag  eVersion version, XmlSerializer serializer, MessagePartDescription returnPart, MessagePartDescriptionCollection bodyP  arts, Object returnValue, Object[] parameters) in E:\OSS\carol\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\XmlSerializerOperationFormatter.cs:line 324
     at System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.SerializeBody(XmlDictionaryWriter writer, Messag  eVersion version, String action, MessageDescription messageDescription, Object returnValue, Object[] parameters, Boolean isRequest) in E:\OSS\carol\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\XmlSerializerOperationFormatter.cs:line 276
     --- End of inner exception stack trace ---
```

**Comment by imcarolwang** [comment]
Test result shows that different `style `and `use `properties of `XmlSerializerFormatAttribute ` couldn't be mixed used in different operations in same service contract.

For example, if one service operation has this attribute specified:
`[OperationContract, XmlSerializerFormat(Style = OperationFormatStyle.Rpc, Use = OperationFormatUse.Literal)]`

Then for any other operation in the service, explicitly added either `XmlSerializerFormat(Style = OperationFormatStyle.Document) `or `XmlSerializerFormat(Use = OperationFormatUse.Encoded) `will throw exception in issue.

**Comment by shmao** [comment]
According to @imcarolwang 

> Test result shows that different styleand useproperties of XmlSerializerFormatAttribute couldn't be mixed used in different operations in same service contract.

>For example, if one service operation has this attribute specified:
[OperationContract, XmlSerializerFormat(Style = OperationFormatStyle.Rpc, Use = OperationFormatUse.Literal)]

>Then for any other operation in the service, explicitly added either XmlSerializerFormat(Style = OperationFormatStyle.Document)or XmlSerializerFormat(Use = OperationFormatUse.Encoded)will throw exception in issue.

**Comment by imcarolwang** [comment]
@shmao ,  after more testing, I found the comment is not always true for all cases , I am confused about the mixed using scenario, maybe knowing the default `Style `and `Use `  value if not specifying any would help diagnose issue but still the test result is confusing.

**Comment by imcarolwang** [comment]
Apply different `XmlSerializerFormatAttribute Style ` (`Rpc `or `Document`) and `Use ` (`Encoded `or `Literal`) for different operations explicitly:
	

1. All Rpc+Encoded : work
2. 	All Rpc+Literal : work
3. 	All Doc+Literal : work
4. 	Rpc+Literal <-> Doc+Literal : work
5. 	Rpc+Encoded <-> Rpc+Literal : not work
6. 	Rpc+Encoded <-> Doc+Literal : not work

**Comment by huanwu** [comment]
This is because some mappings are soap mapping and some are xml mapping. If there're soap mapping, it will use ReflectionBasedSerializers and won't generate the serializer. However, during the serialization, it will check if the mapping is soap or not, if it is not soap, it will still try to use the serializer, which was not generated.
