### ISSUE TITLE
PerformanceCounter_IncrementBy_IncrementByReadOnly Failure for Windows 8.1

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefx#25349]
The failure on Windows is only on Windows.81.Amd64.Open (the test is skipped on a number of the win10 versions)
System.Diagnostics.Tests.PerformanceCounterTests/PerformanceCounter_IncrementBy_IncrementByReadOnly

Assert.NotEqual() Failure
Expected: Not 0
Actual: 0

https://mc.dot.net/#/user/Drawaes/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/95937940636258caa156046fa21fca91a45682d3/workItem/System.Diagnostics.PerformanceCounter.Tests/analysis/xunit/System.Diagnostics.Tests.PerformanceCounterTests~2FPerformanceCounter_IncrementBy_IncrementByReadOnly

Trace

```
at System.Diagnostics.Tests.Helpers.RetryOnAllPlatforms[T](Func`1 func) in D:\j\workspace\windows-TGrou---6368dffa\src\System.Diagnostics.PerformanceCounter\tests\Helpers.cs:line 71
   at System.Diagnostics.Tests.PerformanceCounterTests.CreateCounterWithCategory(String name, Boolean readOnly, PerformanceCounterCategoryType categoryType) in D:\j\workspace\windows-TGrou---6368dffa\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs:line 297
   at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_IncrementBy_IncrementByReadOnly() in D:\j\workspace\windows-TGrou---6368dffa\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs:line 228
```

**Comment by stephentoub** [comment]
Failed again here:
https://mc.dot.net/#/user/Drawaes/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/37fa65588ea04cc8ab194512810269723d837cfe/workItem/System.Diagnostics.PerformanceCounter.Tests/analysis/xunit/System.Diagnostics.Tests.PerformanceCounterTests~2FPerformanceCounter_IncrementBy_IncrementByReadOnly
```
Unhandled Exception of Type Xunit.Sdk.NotEqualException
Message :
Assert.NotEqual() Failure
Expected: Not 0
Actual:   0
Stack Trace :
   at System.Diagnostics.Tests.Helpers.RetryOnAllPlatforms[T](Func`1 func) in D:\j\workspace\windows-TGrou---6368dffa\src\System.Diagnostics.PerformanceCounter\tests\Helpers.cs:line 71
   at System.Diagnostics.Tests.PerformanceCounterTests.CreateCounterWithCategory(String name, Boolean readOnly, PerformanceCounterCategoryType categoryType) in D:\j\workspace\windows-TGrou---6368dffa\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs:line 297
   at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_IncrementBy_IncrementByReadOnly() in D:\j\workspace\windows-TGrou---6368dffa\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs:line 228
```

**Comment by Sunny-pu** [comment]
failed again in Master branch:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171211.01/workItem/System.Diagnostics.PerformanceCounter.Tests/analysis/xunit/System.Diagnostics.Tests.PerformanceCounterCategoryTests~2FPerformanceCounterCategory_CategoryType_MultiInstance
