### ISSUE TITLE
FromHandle_BitmapHandleOneTime_Success failed in CI on Linux

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#25367]
https://mc.dot.net/#/user/tmds/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/cfe7984c51ef3590fed2e50ddfb38619dda9f89d/workItem/System.Drawing.Common.Tests/analysis/xunit/System.Drawing.Tests.IconTests~2FFromHandle_BitmapHandleOneTime_Success
```
Unhandled Exception of Type System.ArgumentException
Message :
System.ArgumentException : handle
Stack Trace :
   at System.Drawing.Icon.FromHandle(IntPtr handle) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Drawing.Common/src/System/Drawing/Icon.Unix.cs:line 335
   at System.Drawing.Tests.IconTests.FromHandle_BitmapHandleOneTime_Success() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Drawing.Common/tests/IconTests.cs:line 688
```

**Comment by stephentoub** [comment]
Failed again here:
https://mc.dot.net/#/user/Drawaes/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/5b36549045ac184a4016873369c91e08288502ef/workItem/System.Drawing.Common.Tests/analysis/xunit/System.Drawing.Tests.IconTests~2FFromHandle_BitmapHandleOneTime_Success
```
Unhandled Exception of Type System.ArgumentException
Message :
System.ArgumentException : handle
Stack Trace :
   at System.Drawing.Icon.FromHandle(IntPtr handle) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Drawing.Common/src/System/Drawing/Icon.Unix.cs:line 335
   at System.Drawing.Tests.IconTests.FromHandle_BitmapHandleOneTime_Success() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Drawing.Common/tests/IconTests.cs:line 688
```

**Comment by safern** [comment]
@stephentoub have we seen this one failing lately? Can we close it? I know libgdiplus has gotten some fixes at least in December last year.
