### ISSUE TITLE
"Category does not exist." errors in PerformanceCounter tests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#25400]
https://mc.dot.net/#/user/Drawaes/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/ab1336f6c46534d55ac9b1fce42111c05ca65f94/workItem/System.Diagnostics.PerformanceCounter.Tests/wilogs
```
2017-11-20 16:11:23,493: INFO: proc(54): run_and_log_output: Output: Discovering: System.Diagnostics.PerformanceCounter.Tests
2017-11-20 16:11:23,697: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Diagnostics.PerformanceCounter.Tests
2017-11-20 16:11:23,775: INFO: proc(54): run_and_log_output: Output: Starting:    System.Diagnostics.PerformanceCounter.Tests
2017-11-20 16:11:25,900: INFO: proc(54): run_and_log_output: Output:    System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCounters [FAIL]
2017-11-20 16:11:25,900: INFO: proc(54): run_and_log_output: Output:       System.InvalidOperationException : Could not Read Category Index: 10170.
2017-11-20 16:11:25,900: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-11-20 16:11:26,009: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterLib.cs(1424,0): at System.Diagnostics.CategorySample..ctor(Byte[] data, CategoryEntry entry, PerformanceCounterLib library)
2017-11-20 16:11:26,009: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterLib.cs(822,0): at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String category)
2017-11-20 16:11:26,009: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterLib.cs(791,0): at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String machine, String category)
2017-11-20 16:11:26,009: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterCategory.cs(443,0): at System.Diagnostics.PerformanceCounterCategory.GetCounterInstances(String categoryName, String machineName)
2017-11-20 16:11:26,009: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterCategory.cs(517,0): at System.Diagnostics.PerformanceCounterCategory.GetInstanceNames()
2017-11-20 16:11:26,009: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterCategory.cs(460,0): at System.Diagnostics.PerformanceCounterCategory.GetCounters()
2017-11-20 16:11:26,009: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterCategoryTests.cs(234,0): at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCounters()
2017-11-20 16:11:28,973: INFO: proc(54): run_and_log_output: Output:    System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_BeginInitEndInit_ProcessorCounter [FAIL]
2017-11-20 16:11:28,973: INFO: proc(54): run_and_log_output: Output:       System.InvalidOperationException : Category does not exist.
2017-11-20 16:11:28,973: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-11-20 16:11:28,973: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterLib.cs(360,0): at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
2017-11-20 16:11:28,973: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounter.cs(478,0): at System.Diagnostics.PerformanceCounter.InitializeImpl()
2017-11-20 16:11:28,973: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs(177,0): at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_BeginInitEndInit_ProcessorCounter()
2017-11-20 16:11:28,973: INFO: proc(54): run_and_log_output: Output:    System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_CounterExists_StaticInterruptsPerSec [FAIL]
2017-11-20 16:11:28,973: INFO: proc(54): run_and_log_output: Output:       System.InvalidOperationException : Category does not exist.
2017-11-20 16:11:28,973: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-11-20 16:11:28,973: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterLib.cs(360,0): at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
2017-11-20 16:11:28,973: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterCategory.cs(188,0): at System.Diagnostics.PerformanceCounterCategory.CounterExists(String counterName, String categoryName, String machineName)
2017-11-20 16:11:28,973: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterCategory.cs(168,0): at System.Diagnostics.PerformanceCounterCategory.CounterExists(String counterName, String categoryName)
2017-11-20 16:11:28,973: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterCategoryTests.cs(191,0): at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_CounterExists_StaticInterruptsPerSec()
```

**Comment by danmosemsft** [comment]
@adiaaida thoughts? I can't tell what OS this was - that info is lost.

**Comment by danmosemsft** [comment]
This smells like the code is not safe against categories getting added or deleted concurrent with counters being read. Let's disable parallelizatoin.
