### ISSUE TITLE
Test failure: System.Data.Tests.AppDomainsAndFormatInfo.Bug55978

### ISSUE THREAD

**Issue by Cronan** [dotnet/corefx#25409]
The test `System.Data.Tests.AppDomainsAndFormatInfo.Bug55978` has failed.

```
Stack trace:
System.Data.EvaluateException : Cannot perform '>=' operation on System.DateTime and System.String.
at System.Data.BinaryNode.SetTypeMismatchError(Int32 op, Type left, Type right) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\Filter\BinaryNode.cs:line 135
   at System.Data.BinaryNode.BinaryCompare(Object vLeft, Object vRight, StorageType resultType, Int32 op, CompareInfo comparer) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\Filter\BinaryNode.cs:line 267
   at System.Data.BinaryNode.BinaryCompare(Object vLeft, Object vRight, StorageType resultType, Int32 op) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\Filter\BinaryNode.cs:line 152
   at System.Data.BinaryNode.EvalBinaryOp(Int32 op, ExpressionNode left, ExpressionNode right, DataRow row, DataRowVersion version, Int32[] recordNos) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\Filter\BinaryNode.cs:line 871
   at System.Data.BinaryNode.Eval(DataRow row, DataRowVersion version) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\Filter\BinaryNode.cs:line 41
   at System.Data.BinaryNode.Eval(ExpressionNode expr, DataRow row, DataRowVersion version, Int32[] recordNos) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\Filter\BinaryNode.cs:line 142
   at System.Data.BinaryNode.EvalBinaryOp(Int32 op, ExpressionNode left, ExpressionNode right, DataRow row, DataRowVersion version, Int32[] recordNos) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\Filter\BinaryNode.cs:line 908
   at System.Data.BinaryNode.Eval(DataRow row, DataRowVersion version) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\Filter\BinaryNode.cs:line 41
   at System.Data.DataExpression.Invoke(DataRow row, DataRowVersion version) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\Filter\DataExpression.cs:line 195
   at System.Data.Index.AcceptRecord(Int32 record, IFilter filter) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\Selection.cs:line 217
   at System.Data.Index.InitRecords(IFilter filter) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\Selection.cs:line 745
   at System.Data.Index..ctor(DataTable table, IndexField[] indexFields, Comparison`1 comparison, DataViewRowState recordStates, IFilter rowFilter) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\Selection.cs:line 138
   at System.Data.Index..ctor(DataTable table, IndexField[] indexFields, DataViewRowState recordStates, IFilter rowFilter) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\Selection.cs:line 89
   at System.Data.DataTable.GetIndex(IndexField[] indexDesc, DataViewRowState recordStates, IFilter rowFilter) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\DataTable.cs:line 3184
   at System.Data.DataTable.GetIndex(String sort, DataViewRowState recordStates, IFilter rowFilter) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\DataTable.cs:line 3161
   at System.Data.DataView.UpdateIndex(Boolean force, Boolean fireEvent) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\DataView.cs:line 1557
   at System.Data.DataView.UpdateIndex(Boolean force) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\DataView.cs:line 1531
   at System.Data.DataView.SetIndex2(String newSort, DataViewRowState newRowStates, IFilter newRowFilter, Boolean fireEvent) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\DataView.cs:line 1508
   at System.Data.DataView.SetIndex(String newSort, DataViewRowState newRowStates, IFilter newRowFilter) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\DataView.cs:line 1486
   at System.Data.DataView.set_RowFilter(String value) in D:\git\dotnetfix\corefx\src\System.Data.Common\src\System\Data\DataView.cs:line 301
   at System.Data.Tests.AppDomainsAndFormatInfo.Bug55978() in D:\git\dotnetfix\corefx\src\System.Data.Common\tests\System\Data\DataTableTest.cs:line 4043
```

- Config:  netcoreapp-Windows_NT-Debug-x64
- OS: Microsoft Windows [Version 6.1.7601]

**Comment by Cronan** [comment]
Seems to pass if I change the RowFilter string from:
StartDate >= '{0}' and StartDate <= '{1}'
to 
StartDate >= #{0}# and StartDate <= #{1}#

**Comment by Cronan** [comment]
Perhaps related to the locale issue in #25268 ?

**Comment by danmosemsft** [comment]
@Cronan if you temporarily change your culture to en-US does it pass? Might be enough to just set the thread culture at the start of the test.

**Comment by Cronan** [comment]
I’ll try that this morning

**Comment by Cronan** [comment]
Quick question @danmosemsft , is changing the locale the right thing to do, unless the test targets a specific locale? Isn't it better to change the test so it doesn't require a specific locale to run?

**Comment by danmosemsft** [comment]
@Cronan yes probably that would be better.

**Comment by danmosemsft** [comment]
I just wanted to confirm it was a culture issue. Perhaps you'd like to offer that change as a PR?

**Comment by Cronan** [comment]
I'll test both, and do a PR later today ...

**Comment by Cronan** [comment]
Changing the locale worked, but I believe the change I've made will work in *~~all~~* more locales.
