### ISSUE TITLE
InterProcessCommunication.Tests.MemoryMappedFilesTests.DataShared failed in CI

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#2544]
```
InterProcessCommunication.Tests.MemoryMappedFilesTests.DataShared [FAIL]
14:59:19       System.IO.IOException : The process cannot access the file '/tmp/MemoryMappedFilesTests_3049ac97ccfec979735d76d4e90f0e91/DataShared_16' because it is being used by another process.
14:59:19       Stack Trace:
14:59:19 Starting:    System.Collections.Immutable.Tests
14:59:19             at System.IO.UnixFileStream.SysCall[TArg1,TArg2](Func`4 sysCall, TArg1 arg1, TArg2 arg2, Boolean throwOnError)
14:59:19             at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
14:59:19             at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
14:59:19             at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
14:59:19             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
14:59:19             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
14:59:19             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
14:59:19             at InterProcessCommunication.Tests.MemoryMappedFilesTests.DataShared()
14:59:19 Finished:    InterProcessCommunication.Tests
14:59:19 
14:59:19 === TEST EXECUTION SUMMARY ===
14:59:19    InterProcessCommunication.Tests  Total: 3, Errors: 0, Failed: 1, Skipped: 0, Time: 1.322s
```

**Comment by Priya91** [comment]
@stephentoub

**Comment by stephentoub** [comment]
Dup of #2498
