### ISSUE TITLE
DataTable serialization incorrectly depends on the Current Culture's Number Format Info

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#25575]
Ported manually from here https://github.com/Microsoft/dotnet/issues/471 (Zenhub doesn't allow moving issues between organizations)

@logiclrd commented on Sep 1:

We have a client reporting problems with our application because they have configured the Windows Region & Language settings to use the string "()" as the negative sign for number formatting. This seems to be traceable back to the fact that the DataTable in question has a custom schema that specifies negative values for the autoincrement seed & step. When DataTable is trying to deserialize the schema, it assumes that the quantity negative one should look like "()1" and therefore does not recognize the "-1" in the XML data. Some quick testing reveals that a DataTable serialized under these conditions produces correct XML representing "-1" as "-1"; this issue affects only deserialization.

This issue only comes up when properties in the table's schema have negative values. Negative values in the row data do not trigger the problem.

Our client has informed us that this configuration is deliberate and desired. The only control we have over DataTable deserialization seems to be to override the entire process's CultureInfo.CurrentCulture, which in turn means that reports produced by our software will not use the "()1" format the client desires. There does not appear to be a way to work around this issue only for DataTable serialization/deserialization and without affecting other number formatting in the application.
The following code reproduces the issue:

```csharp
   var serializer = new BinaryFormatter();

            var table = new DataTable();

            table.Columns.Add(
                new DataColumn("RowID", typeof(int))
                {
                    AutoIncrement = true,
                    AutoIncrementSeed = -1, // These lines produce attributes within the schema portion of the underlying XML representation of the DataTable with the value "-1".
                    AutoIncrementStep = -1,
                });

            table.Columns.Add("Value", typeof(string));

            table.Rows.Add(1, "Test");
            table.Rows.Add(2, "Data");

            var buffer = new MemoryStream();

            serializer.Serialize(buffer, table);

            CultureInfo.CurrentCulture =
                new CultureInfo("en-US")
                {
                    NumberFormat =
                        new NumberFormatInfo()
                        {
                            NegativeSign = "()" // DataTable's deserialization incorrectly uses this to ascertain the number format for deserializing the schema properties.
                        }
                };

            buffer.Position = 0;

            var table2 = (DataTable)serializer.Deserialize(buffer); // System.Exception: "-1 is not a valid value for Int64."
```

cc @weshaggard @danmosemsft @richlander

**Comment by danmosemsft** [comment]
This reproduces on full .NET Framework as well:
```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: -1 is not a valid value for Int64. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.ComponentModel.Int64Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Data.XSDSchema.SetProperties(Object instance, XmlAttribute[] attrs)
   at System.Data.XSDSchema.HandleElementColumn(XmlSchemaElement elem, DataTable table, Boolean isBase)
   at System.Data.XSDSchema.HandleParticle(XmlSchemaParticle pt, DataTable table, ArrayList tableChildren, Boolean isBase)
   at System.Data.XSDSchema.HandleComplexType(XmlSchemaComplexType ct, DataTable table, ArrayList tableChildren, Boolean isNillable)
   at System.Data.XSDSchema.InstantiateTable(XmlSchemaElement node, XmlSchemaComplexType typeNode, Boolean isRef)
   at System.Data.XSDSchema.HandleTable(XmlSchemaElement node)
   at System.Data.XSDSchema.LoadSchema(XmlSchemaSet schemaSet, DataSet ds)
   at System.Data.DataSet.ReadXmlSchema(XmlReader reader, Boolean denyResolving)
   at System.Data.DataTable.DeserializeDataTable(SerializationInfo info, StreamingContext context, Boolean isSingleTable, SerializationFormat remotingFormat)
   at System.Data.DataTable..ctor(SerializationInfo info, StreamingContext context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at Fasta.Main(String[] args)
```

This repo is for issues specific to .NET Core. @logiclrd what we typically recommend for .NET Framework issues is to open a support ticket through the usual channels. That would be better than the more ad-hoc Github issue system. Does that work?

**Comment by logiclrd** [comment]
I have no idea what those channels are. Can you point me in the right direction? Thanks!

**Comment by logiclrd** [comment]
Note that this issue was originally reported in the `Microsoft/dotnet` repo, which is described as "the official home of .NET on GitHub", and not .NET Core-specific. The issue got moved from there to here today. There is a link to the original report at the top of the description of this issue.

**Comment by danmosemsft** [comment]
@logiclrd yes, maybe we shouldn't have moved it. :)

First thing -- @saurabh500 is this issue famliiar to you, is there a workaround you know of?

**Comment by saurabh500** [comment]
I am not aware of this issue and don't know of a workaround right now. This will need further investigation

**Comment by ViktorHofer** [comment]
As it also repros on Core I believed it belongs here. IF we submit a fix to adjust the behavior, we could just mark it with the "netfx-port-consider" label.

**Comment by logiclrd** [comment]
Do you think it might fix this issue to change this line:

    if (converter.CanConvertFrom(typeof(string)))
    {

https://github.com/dotnet/corefx/blob/f0ccd9742065ee2aa296448fe3dd38ef6ff77af9/src/System.Data.Common/src/System/Data/XMLSchema.cs#L50

    }

...to this instead?:

             propValue = converter.ConvertFromInvariantString(value);

**Comment by ViktorHofer** [comment]
yes, that should fix the issue. As you described, it only occurs during deserialization. Do you want to try fixing the issue by yourself and add a few tests that test the correct behavior?

**Comment by logiclrd** [comment]
I suppose I could have a go at it. :-)

**Comment by ViktorHofer** [comment]
Perfect, I'll assign you to the issue. Feel free to shout out if you need any help.

**Comment by saurabh500** [comment]
With the proposed change, will a DataTable serialized with earlier code be de-serializable using the new code and yield the same output as before the change?
I am simply putting this question out to address any compatibility issues if they can arise due to the proposed change.

**Comment by ViktorHofer** [comment]
> With the proposed change, will a DataTable serialized with earlier code be de-serializable using the new code and yield the same output as before the change?

I wouldn't expect any compatibility issues as the serialization logic is culture neutral, only the deserialization logic uses the current culture.

**Comment by logiclrd** [comment]
That aspect should also be covered by the unit tests. I'll make one that specifically embeds a DataTable serialized with the current-released code and deserializes it with the new code.

**Comment by logiclrd** [comment]
Hmm, curious. I'm in the habit of using Visual Studio 2017 Preview (Version 15.6.0 Preview 1.0), but when I use that on the `System.Data.Common.sln` solution, opening any C# source code file immediately crashes the development environment. However, when I instead use the stable branch of Visual Studio 2017, this problem does not occur. :-)

**Comment by ViktorHofer** [comment]
That happens from time to time depending on the machine configuration, the state of the current preview version and your OS version (Windows stable vs Fast Ring).

**Comment by danmosemsft** [comment]
@logiclrd you might hit the send feedback button in VS to report that crash.

**Comment by logiclrd** [comment]
https://github.com/dotnet/corefx/pull/26298
