### ISSUE TITLE
Process.TestEnableRaiseEvents fails on Linux build

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#2562]
This test failed once in Linux build. EnableRaisingEvents was set to true on Process, and on exiting the specifed callback method was not called. 

```
System.Diagnostics.ProcessTests.ProcessTests.TestEnableRaiseEvents [FAIL]
08:42:31       Assert+WrapperXunitException : File path: d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Diagnostics.Process\tests\System.Diagnostics.Process.Tests\ProcessTests.cs. Line: 88
08:42:31       ---- TestCanRaiseEvents0001: isExited Event not called when EnableRaisingEvent is set to true.
08:42:31       Stack Trace:
08:42:31             at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
08:42:31             at Assert.True(Boolean condition, String userMessage, String path, Int32 line)
08:42:31             at System.Diagnostics.ProcessTests.ProcessTests.TestEnableRaiseEvents()
08:42:31          ----- Inner Stack Trace -----
08:42:31             at Assert.True(Boolean condition, String userMessage, String path, Int32 line)
```

Build [1378](http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/1378/console)

**Comment by stephentoub** [comment]
This just failed again:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst/735/console
```
20:21:32    System.Diagnostics.ProcessTests.ProcessTests.TestEnableRaiseEvents [FAIL]
20:21:32       Assert+WrapperXunitException : File path: d:\j\workspace\dotnet_corefx_windows_debug\src\System.Diagnostics.Process\tests\ProcessTests.cs. Line: 89
20:21:32       ---- TestCanRaiseEvents0001: isExited Event not called when EnableRaisingEvent is set to true.
20:21:32       Expected: True
20:21:32       Actual:   False
20:21:32       Stack Trace:
20:21:33             at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
20:21:33             at Assert.True(Boolean condition, String userMessage, String path, Int32 line)
20:21:33             at System.Diagnostics.ProcessTests.ProcessTests.TestEnableRaiseEvents()
20:21:33          ----- Inner Stack Trace -----
20:21:33             at Assert.True(Boolean condition, String userMessage, String path, Int32 line)
20:21:48 Finished:    System.Diagnostics.Process.Tests
```
