### ISSUE TITLE
Failing code with forward slashes as path separators with paths containing umlauts

### ISSUE THREAD

**Issue by beyon** [dotnet/corefx#25632]
As mentioned in this issue( https://github.com/dotnet/corefx/issues/25519 ) there is a problem for me with paths using forward slashes as path separators and umlauts (probably all characters outside the 0000-007F range?). Found using System.Xml.Linq.XDocument.Load(), can't reproduce with just System.IO.Path.GetFullPath() so my guess is the path gets malformed somewhere along the call stack between those calls but I am not setup to debug the .net core code so unsure where.

Tested with .Net Core 2.0.3 on Windows 10 64-bit (dotnet-sdk-2.0.3-win-x64.exe installer)

Simple test code (project created with ```dotnet new console```):

```c#
using System;
using System.Xml.Linq;

namespace forwardslashwithumlaut
{
    class Program
    {
        static void Main(string[] args)
        {
            var xmlDoc1 = XDocument.Load(@"c:/elmish/dotnetcoreissue/o/test.xml");
            Console.WriteLine("Nonumlaut forward slash path passed"); //passes on .Net core and .Net Framework 4.6.1
            var xmlDoc2 = XDocument.Load(@"c:/elmish/dotnetcoreissue/ö/test.xml");
            Console.WriteLine("Umlaut forward slash path passed"); // failson .Net core and passes on.Net Framework 4.6.1
        }
    }
}
```
Console output:
```
dotnet run
Nonumlaut forward slash path passed

Unhandled Exception: System.NotSupportedException: The given path's format is not supported.
   at System.IO.Path.GetFullPath(String path)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri)
   at backslashpathwithumlaut.Program.Main(String[] args) in C:\elmish\backslashpathwithumlaut\Program.cs:line 12
```

[EDIT] Add C# syntax highlighting by @karelz

**Comment by karelz** [comment]
Hidden in the repro text is the fact it passes on .NET 4.6.1 - compat issue between Core and Desktop.

**Comment by krwq** [comment]
@beyon It seems to me that the Uri which is causing a failure is one of the Uris inside the Xml itself and not the path to the xml file (search for external dtds inside your doc).
Could you test Uri code with that? (or share the xml doc)

I believe the narrowed down scenario will be something along the lines of:
```csharp
Uri uri = new Uri("<uri found in your xml doc>");
// this is exactly what xml calls:
new FileStream(uri.LocalPath, FileMode.Open, FileAccess.Read, FileShare.Read, 1);
```

**Comment by beyon** [comment]
Oh, sorry I forgot contents of test.xml since this issue was spun off my other.

The contents of test.xml is the same for both paths and is just:
```
<test>
</test>
```
I'm confident it's just the path used and not the contents of the xml file both from this test setup and from the scenario where I first ran into the issue.

**Comment by krwq** [comment]
@beyon this is passing on my box with your file inside a folder with umlaut character.

This part of the stack you have added:
```
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
```

says that xml parser saw an external entity in the xml file and failed when trying to process it.

Could you possibly attach your project with the repro? i.e. you could create xml file with the umlaut path on the fly.

**Comment by beyon** [comment]
I can see what I can do when I get the time.

Still same code, paths, xml  different results same machine .Net core vs. .Net framework.
Seems very strange that the xml parser would pick up an external entity with the given xml (unless it's trying to pick up some default dtd from somewhere in the sytem when non is provided?)

**Comment by beyon** [comment]
Do you mean something like this?

```c#
using System;
using System.IO;
using System.Xml.Linq;

namespace forwardslashpathwithumlaut
{
    class Program
    {
        const string basePath = @"c:/forwardSlashWithUmlautIssueTestPath";
        const string nonUmlautRelativePath = @"/o";
        const string umlautRelativePath = @"/ö";
        const string relativeFilePath = @"/test.xml";
        const string xmlFileContents = @"<test></test>";
        
        static int Main(string[] args)
        {
            string nonUmlautPath = basePath + nonUmlautRelativePath;
            string umlautPath = basePath + umlautRelativePath;
            string fileWithNonUmlautPath = nonUmlautPath + relativeFilePath;
            string fileWithUmlautPath = umlautPath + relativeFilePath;

            try {
                if( !Directory.Exists(basePath) ) {
                    Console.WriteLine("{0} not found - creating directory", basePath);
                    Directory.CreateDirectory(basePath);
                }
                if( !Directory.Exists( nonUmlautPath )) {
                    Console.WriteLine("{0} not found - creating directory", nonUmlautPath);
                    Directory.CreateDirectory( nonUmlautPath );
                }
                if( !Directory.Exists( umlautPath )) {
                    Console.WriteLine("{0} not found - creating directory", umlautPath);
                    Directory.CreateDirectory( umlautPath );
                }
                if( !File.Exists( fileWithNonUmlautPath ) ) {
                    File.WriteAllText(fileWithNonUmlautPath, xmlFileContents);
                }
                if( !File.Exists( fileWithUmlautPath ) ) {
                    File.WriteAllText(fileWithUmlautPath, xmlFileContents);
                }
            } catch (Exception e) {
                Console.WriteLine("Error creating necessary test directories and files!");
                Console.WriteLine("Aborting test");
                Console.WriteLine( e.Message );
                return 1;
            }
            var xmlDoc1 = XDocument.Load( fileWithNonUmlautPath );
            Console.WriteLine("Nonumlaut forward slash path passed");
            var xmlDoc2 = XDocument.Load( fileWithUmlautPath);
            Console.WriteLine("Umlaut forward slash path passed");
            return 0;
        }
    }
}
```
This still fails for the umlaut path for me (```XDocument.Load( fileWithUmlautPath)```)

**Comment by danmosemsft** [comment]
Does this simply have the same cause as  #25519  mentioned? Would be surprising if there was a bug in Uri and in Xml.

**Comment by svick** [comment]
I can reproduce this. In my case, the file doesn't actually exist, so this can't possibly be related to its contents. Interestingly, on .Net Core 2.1 Preview, the exception message is more informative:

```
System.NotSupportedException: The format of the path 'file:c:\elmish\dotnetcoreissue\ö\test.xml' is not supported.
   at System.IO.Path.GetFullPath(String path)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri)
   at Program.Main(String[] args) in C:\code\tmp\coreapp\Program.cs:line 15
```

**Comment by pjanotti** [comment]
I took a quick look and this is related to `Uri` generating incorrect `LocalPath` when the umlaut is present:

```
            var uri = new Uri(@"c:/elmish/dotnetcoreissue/ö/test.xml");
            Console.WriteLine($"====> uri.Scheme:[{uri.Scheme}] uri.LocalPath:[{uri.LocalPath}]");
            uri = new Uri(@"c:/elmish/dotnetcoreissue/o/test.xml");
            Console.WriteLine($"====> uri.Scheme:[{uri.Scheme}] uri.LocalPath:[{uri.LocalPath}]");
```

produces:

```
====> uri.Scheme:[file] uri.LocalPath:[file:c:\elmish\dotnetcoreissue\ö\test.xml]
====> uri.Scheme:[file] uri.LocalPath:[c:\elmish\dotnetcoreissue\o\test.xml]
```

The prefix "file:" on the `LocalPath` makes it an invalid path.

/cc krwq

**Comment by pjanotti** [comment]
@JeremyKuhne the exception pointed [above](https://github.com/dotnet/corefx/issues/25632#issuecomment-348695293) was slightly better than the one that I got, see below. I suspect that it is due of `GetFullPath` not being called anymore. Perhaps opportunistically when fixing something else could you add the file name to the exception? 

```
Unhandled Exception: System.IO.IOException: The filename, directory name, or volume label syntax is incorrect
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle) in E:\A\_work\2046\s\src\mscorlib\shared\System\IO\FileStream.Windows.cs:line 1656
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options) in E:\A\_work\2046\s\src\mscorlib\shared\System\IO\FileStream.Win32.cs:line 42
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) in E:\A\_work\2046\s\src\mscorlib\shared\System\IO\FileStream.cs:line 230
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize) in E:\A\_work\2046\s\src\mscorlib\shared\System\IO\FileStream.cs:line 176
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy) in C:\s\github\pjanotti\corefx\src\System.Private.Xml\src\System\Xml\XmlDownloadManager.cs:line 27
```

**Comment by karelz** [comment]
@pjanotti is there difference in Uri parsing between .NET Core and .NET Framework? Or is it difference in IO not handling well file: repfix?

**Comment by pjanotti** [comment]
Yes, it is correct in 4.7.1. For the same short repro from above the output is:

```
====> uri.Scheme:[file] uri.LocalPath:[c:\elmish\dotnetcoreissue\ö\test.xml]
====> uri.Scheme:[file] uri.LocalPath:[c:\elmish\dotnetcoreissue\o\test.xml]
```

**Comment by karelz** [comment]
@rmkerr can you please take a look? is it expected difference in UriParser between .NET Core and .NET Framework?

**Comment by rmkerr** [comment]
I don't think that behavior is expected. I'm able to repro on the latest version of .NET Core. It doesn't repro in 4.7.2, so I don't think it's related to any of the recent updates to URI. That leaves a fairly small number of possible differences between the Core and Framework implementations that could be causing this.

**Comment by rmkerr** [comment]
The issue was introduced by the changes to `Uri.ParseRemaining` in PR #9542. I'm looking into a fix in between work on other issues, but I don't expect it to be too complicated.
