### ISSUE TITLE
ALPN tests failing on RedHat

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#25661]
https://mc.dot.net/#/user/Drawaes/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/5e70fee9f1339db71f723caac7a85d55346c9a09/workItem/System.Net.Security.Tests/wilogs
```
2017-12-02 23:41:32,500: INFO: proc(54): run_and_log_output: Output:    System.Net.Security.Tests.SslStreamAlpnTests.SslStream_StreamToStream_Alpn_NonMatchingProtocols_Fail [FAIL]
2017-12-02 23:41:32,500: INFO: proc(54): run_and_log_output: Output:       AuthenticationException was not thrown.
2017-12-02 23:41:32,500: INFO: proc(54): run_and_log_output: Output:       Expected: True
2017-12-02 23:41:32,501: INFO: proc(54): run_and_log_output: Output:       Actual:   False
2017-12-02 23:41:32,513: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-12-02 23:41:32,870: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.Security/tests/FunctionalTests/SslStreamAlpnTests.cs(157,0): at System.Net.Security.Tests.SslStreamAlpnTests.<SslStream_StreamToStream_Alpn_NonMatchingProtocols_Fail>d__4.MoveNext()
2017-12-02 23:41:32,870: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-12-02 23:41:32,870: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-12-02 23:41:32,870: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-12-02 23:41:32,870: INFO: proc(54): run_and_log_output: Output:    System.Net.Security.Tests.SslStreamAlpnTests.SslStream_StreamToStream_Alpn_Success(clientProtocols: [http/1.1, h2], serverProtocols: [h2], expected: h2) [FAIL]
2017-12-02 23:41:32,870: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2017-12-02 23:41:32,870: INFO: proc(54): run_and_log_output: Output:       Expected: h2
2017-12-02 23:41:32,870: INFO: proc(54): run_and_log_output: Output:       Actual:   (null)
2017-12-02 23:41:32,870: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-12-02 23:41:32,871: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.Security/tests/FunctionalTests/SslStreamAlpnTests.cs(116,0): at System.Net.Security.Tests.SslStreamAlpnTests.<SslStream_StreamToStream_Alpn_Success>d__3.MoveNext()
2017-12-02 23:41:32,871: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-12-02 23:41:32,871: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-12-02 23:41:32,871: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-12-02 23:41:33,124: INFO: proc(54): run_and_log_output: Output:    System.Net.Security.Tests.SslStreamAlpnTests.SslStream_StreamToStream_Alpn_Success(clientProtocols: [http/1.1], serverProtocols: [http/1.1, h2], expected: http/1.1) [FAIL]
2017-12-02 23:41:33,124: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2017-12-02 23:41:33,124: INFO: proc(54): run_and_log_output: Output:       Expected: http/1.1
2017-12-02 23:41:33,124: INFO: proc(54): run_and_log_output: Output:       Actual:   (null)
2017-12-02 23:41:33,124: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-12-02 23:41:33,125: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.Security/tests/FunctionalTests/SslStreamAlpnTests.cs(116,0): at System.Net.Security.Tests.SslStreamAlpnTests.<SslStream_StreamToStream_Alpn_Success>d__3.MoveNext()
2017-12-02 23:41:33,125: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-12-02 23:41:33,125: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-12-02 23:41:33,125: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-12-02 23:41:33,214: INFO: proc(54): run_and_log_output: Output:    System.Net.Security.Tests.SslStreamAlpnTests.SslStream_StreamToStream_Alpn_Success(clientProtocols: [http/1.1, h2], serverProtocols: [http/1.1, h2], expected: http/1.1) [FAIL]
2017-12-02 23:41:33,214: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2017-12-02 23:41:33,214: INFO: proc(54): run_and_log_output: Output:       Expected: http/1.1
2017-12-02 23:41:33,214: INFO: proc(54): run_and_log_output: Output:       Actual:   (null)
2017-12-02 23:41:33,214: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-12-02 23:41:33,215: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.Security/tests/FunctionalTests/SslStreamAlpnTests.cs(116,0): at System.Net.Security.Tests.SslStreamAlpnTests.<SslStream_StreamToStream_Alpn_Success>d__3.MoveNext()
2017-12-02 23:41:33,215: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-12-02 23:41:33,215: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-12-02 23:41:33,215: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
```

**Comment by karelz** [comment]
Fixed by PR #25637
