### ISSUE TITLE
System.Reflection.Metadata intermittent failures on RHEL

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#25739]
https://mc.dot.net/#/user/krwq/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/e7eb637d18b531e46e64997fe9de55ae1d52521e/workItem/System.Reflection.Metadata.Tests

All of the errors look more or less like:

```
System.BadImageFormatException : Invalid COR20 header signature.

   at System.Reflection.Metadata.MetadataReader.ReadMetadataHeader(BlobReader& memReader, String& versionString) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Reflection.Metadata/src/System/Reflection/Metadata/MetadataReader.cs:line 185
   at System.Reflection.Metadata.MetadataReader..ctor(Byte* metadata, Int32 length, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Reflection.Metadata/src/System/Reflection/Metadata/MetadataReader.cs:line 97
   at System.Reflection.Metadata.Tests.MetadataReaderTests.GetMetadataReader(Byte[] peImage, Int32& metadataStartOffset, Boolean isModule, MetadataReaderOptions options, MetadataStringDecoder decoder) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Reflection.Metadata/tests/Metadata/MetadataReaderTests.cs:line 81
   at System.Reflection.Metadata.Tests.AssemblyDefinitionTests.ValidateAssemblyNameForAssemblyDefinition() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Reflection.Metadata/tests/Metadata/TypeSystem/AssemblyDefinitionTests.cs:line 84
```

**Comment by kumpera** [comment]
I'm having this issue with the 1.5.0 nuget on mono 5.8 on OSX.

**Comment by kumpera** [comment]
This is the assembly I compiler with csc `2.3.2.61928 (ec1cde8b)` as provided by mono 5.8:

 ```class Driver {
	static int Main (string[] args) {
		int a = Times2(args.Length);

		return a;
	}

	static int Times2(int x) {
		return x * 2;
	}
}```

**Comment by stephentoub** [comment]
Failed again here on OpenSuse:
https://github.com/dotnet/corefx/pull/27538#issuecomment-369125314
```
System.BadImageFormatException : Invalid COR20 header signature.

   at System.Reflection.Metadata.MetadataReader.ReadMetadataHeader(BlobReader& memReader, String& versionString) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Reflection.Metadata/src/System/Reflection/Metadata/MetadataReader.cs:line 182
   at System.Reflection.Metadata.MetadataReader..ctor(Byte* metadata, Int32 length, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Reflection.Metadata/src/System/Reflection/Metadata/MetadataReader.cs:line 97
   at System.Reflection.Metadata.Tests.MetadataReaderTests.GetMetadataReader(Byte[] peImage, Int32& metadataStartOffset, Boolean isModule, MetadataReaderOptions options, MetadataStringDecoder decoder) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Reflection.Metadata/tests/Metadata/MetadataReaderTests.cs:line 81
   at System.Reflection.Metadata.Tests.AssemblyReferenceTests.ValidateAssemblyNameForSingleAssemblyReference() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Reflection.Metadata/tests/Metadata/TypeSystem/AssemblyReferenceTests.cs:line 15
```

**Comment by tmat** [comment]
Looking at the code that creates the `MetadataReader`, I do not see anything wrong: http://source.dot.net/#System.Reflection.Metadata.Tests/Metadata/MetadataReaderTests.cs,4d74f82424784329.
The tests create a pinned GCHandles for all PE images and the handles are never freed, so all the pointers should stay valid until the process terminates.

**Comment by masonwheeler** [comment]
I'm seeing the same problem on Windows, opening mscorlib 4.0 with the Nuget package for .NET Framework (not Core).

In `MetadataReader.ReadMetadataHeader`, it's failing the check:

```
if ((int) memReader.ReadUInt32() != 1112167234)
  throw new BadImageFormatException(System.Reflection.Strings.MetadataSignature);
```

This is not intermittent for me; it happens consistently.

**Comment by tmat** [comment]
Can you share the exact binary?

**Comment by masonwheeler** [comment]
@tmat Nevermind, please disregard the above.  I was using an unofficial version from Nuget, and it turns out it works as expected in the proper version.

**Comment by tmat** [comment]
@masonwheeler Good. What is the unofficial version?

**Comment by kumpera** [comment]
@tmat this program fails on OSX:
```
using System;
using System.IO;
using System.Reflection.Metadata;

namespace srm_repro
{
    class Program
    {
        static void Main(string[] args)
        {
			var s = MetadataReaderProvider.FromMetadataStream (
				File.OpenRead ("/Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/4.5/mscorlib.dll"));
			var r = s.GetMetadataReader ();
        }
    }
}
```

**Comment by tmat** [comment]
@kumpera Fails how? `System.BadImageFormatException : Invalid COR20 header signature.`?

BTW, note that `MetadataReaderProvider` is `IDisposable` so you should really use it like so:

```C#
using (var s = MetadataReaderProvider.FromMetadataStream (File.OpenRead ("/Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/4.5/mscorlib.dll")){
{
			var r = s.GetMetadataReader ();

}
```

We have a workitem to keep the metadata image alive even if you let the provider go, but it's not implemented yet.

**Comment by kumpera** [comment]
@tmat yes, it gives that error.

I'm aware that it implements IDisposable, just wanted to make the repro as simple as possible. I believe the possible memory leak here is not the issue.

**Comment by kumpera** [comment]
In case versions matter, I'm using the latest one from Nuget.

**Comment by tmat** [comment]
@kumpera This one? https://www.nuget.org/packages/System.Reflection.Metadata/1.6.0-preview1-26216-02

**Comment by tmat** [comment]
Where can I find `/Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/4.5/mscorlib.dll`?

**Comment by tmat** [comment]
Wait a sec... you're using the wrong API. `FromMetadataStream` does not accept PE files. PE file is not a metadata stream. Use `new PEReader(stream)` to open PE files.

**Comment by kumpera** [comment]
@tmat you're absolutely right. 🤦‍♂️ 
Would you agree this to a be a common source of confusion when using this API?
It would be great if FromMetadataStream would check for the PE signature and provide a more actionable error message.

**Comment by masonwheeler** [comment]
@tmat The version I was using was https://www.nuget.org/packages/Net40.Reflection.Metadata/ because it had support for pre-4.6 .NET Framework.  It appears that the official version now supports .Net Standard 1.1 (Framework 4.5, which is what I need,) but it didn't when I looked at it before.

**Comment by tmat** [comment]
I believe the test failures have been fixed by https://github.com/dotnet/corefx/pull/28185.
