### ISSUE TITLE
Failing connections after multiple requests 

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/corefx#25761]
Originally filed by @sebastianroesch as https://github.com/aspnet/EntityFrameworkCore/issues/10494

I have an ASP.NET Core Web application using EF Core 2.0. When performing a bunch of requests that retrieve data from the database, EF Core throws an error after approx. 100 requests. The database is an Azure SQL database and firewall settings are correct. Retrieving data works 80-90% of the times.

This issue has occurred on MacOS and Linux, we did not see it on Windows yet. It happens both on my development machine (Mac) as well as online (Linux). Since our production services are running in Docker, this creates a problem for us.

This is the stack trace of the error:

```
fail: Microsoft.EntityFrameworkCore.Database.Connection[20004]
      An error occurred using the connection to database 'databasename' on server 'azure-database'.
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
ClientConnectionId:00000000-0000-0000-0000-000000000000
```

After a couple of these exceptions, the application crashes with the following error:

```
dotnet(66933,0x700003cf5000) malloc: *** error for object 0x7fd47fac86d0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

The queries that are being performed before the error occurs look like this:

```
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (27ms) [Parameters=[@___teamId_0='XXX' , @__p_1='X', @__p_2='X'], CommandType='Text', CommandTimeout='30']
SELECT [e.ProjectMembers].[Id], [e.ProjectMembers].[CreatedBy], [e.ProjectMembers].[CreatedOn], [e.ProjectMembers].[DeletedBy], [e.ProjectMembers].[DeletedOn], [e.ProjectMembers].[IsResponsible], [e.ProjectMembers].[ProjectId], [e.ProjectMembers].[ProjectRoleId], [e.ProjectMembers].[TeamId], [e.ProjectMembers].[UpdatedBy], [e.ProjectMembers].[UpdatedOn], [e.ProjectMembers].[UserId]
FROM [projects].[ProjectMembers] AS [e.ProjectMembers]
INNER JOIN (
    SELECT DISTINCT [t1].*
    FROM (
        SELECT [e1].[Id]
        FROM [projects].[Projects] AS [e1]
        LEFT JOIN [projects].[ProjectTypes] AS [e.ProjectType1] ON [e1].[ProjectTypeId] = [e.ProjectType1].[Id]
        LEFT JOIN [projects].[ProjectTypes] AS [e.SalesType1] ON [e1].[SalesTypeId] = [e.SalesType1].[Id]
        LEFT JOIN [projects].[ProjectStatuses] AS [e.ProjectStatus1] ON [e1].[ProjectStatusId] = [e.ProjectStatus1].[Id]
        WHERE ([e1].[TeamId] = @___teamId_0) AND [e1].[DeletedOn] IS NULL
        ORDER BY [e1].[Id]
        OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY
    ) AS [t1]
) AS [t2] ON [e.ProjectMembers].[ProjectId] = [t2].[Id]
ORDER BY [t2].[Id]
```

### Steps to reproduce
We use the new Context Pooling like this:

```c#
services.AddDbContextPool<TDbContext>(
                options => options.UseSqlServer(connectionString,
                    sqlOptions =>
                    {
                        sqlOptions.EnableRetryOnFailure(maxRetryCount: 5,
                        maxRetryDelay: TimeSpan.FromSeconds(3),
                        errorNumbersToAdd: null);
                    })
                    .EnableSensitiveDataLogging()
                );
```

The connection string looks like this (everything else is default):

```
Data Source=azure-database;Initial Catalog=databasename;Integrated Security=False;User ID=XXX;Password=XXX
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer, Azure SQL
Operating system: MacOS
IDE: VS Code 1.18.1

**Comment by ajcvickers** [comment]
@saurabh500 This was filed on EF Core, but it looks like a Sqlclient (or below) issue. Also, in triage we thought it might be related to #25620.
/cc @divega

**Comment by sebastianroesch** [comment]
We are still experiencing that quite often. There are multiple errors that we see in our logs:

`"Win32Exception: Unknown error 258: "`

```
"SqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.:    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at System.Data.SqlClient.TdsParserStateObject.TryProcessHeader()
   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers, Boolean throwOnNullResult)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_0`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
```

```
"An exception occurred in the database while iterating the results of a query for context type 'UsersService.DAL.UsersContext'.
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): Unknown error 258
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at System.Data.SqlClient.TdsParserStateObject.TryProcessHeader()
   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers, Boolean throwOnNullResult)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_0`1.<CompileQueryCore>b__0(QueryContext qc)
ClientConnectionId:312d6b67-3322-4d5d-9b97-5218cccd1134
Error Number:-2,State:0,Class:11"
```

```
"SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server):    at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
```

I found issues like this https://github.com/aspnet/EntityFrameworkCore/issues/5989
where people seem to have resolved it by using a newer SQL Server version. However, since we're using Azure SQL, I think we're using a much later version than this.

This is what Azure SQL version reports: Microsoft SQL Azure (RTM) - 12.0.2000.8 Nov 29 2017 09:37:51

All reports we can get from the database look good, there is no high amount of traffic and other systems working on the same databases and Azure SQL Server work fine throughout all of this.

Any ideas what we can do? Is this somehow related to dotnet core on Linux?

**Comment by saurabh500** [comment]
@ajvickers this issue should have been resolved with https://github.com/dotnet/corefx/issues/25620 
The call stack shows SqlConnection.Open() is timing out after 100 connections. 
Looks like the same issue with concurrent requests. 

@sebastianroesch `Win32Exception: Unknown error 258:` Is this coming from Windows? Or from Linux? 

Also are you using MARS in your connections ?

**Comment by sebastianroesch** [comment]
@saurabh500 The exception must be coming from Linux. No, we're not using MARS.

If I see it correctly, the fix will only be available in runtime version 2.1, correct?

**Comment by saurabh500** [comment]
@sebastianroesch the issue has been ported to the 2.0.x release as well and should be available in the next servicing update.

**Comment by saurabh500** [comment]
@sebastianroesch I am closing this issue since the fix has been delivered into the code base. 
Would it be possible for you to verify if a version of SqlCLient from our nightly feed, solves the problem for you ? https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Data.SqlClient 
You could try `4.5.0-preview2-26225-02`

Please comment in case you still see the problem.

**Comment by sebastianroesch** [comment]
@saurabh500 We are using a nightly preview Docker image and the issue seems to be resolved. Thanks!
