### ISSUE TITLE
IsolatedStorage random test failures UnauthorizedAccessException / DirectoryNotFoundException on Win 10 RS4 Insider Preview

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#25765]
**repro**
./clean.cmd --all
./build.cmd
./build-tests.cmd

**output snippet:**

UnauthorizedAccessException
```[Microsoft (R) .NET Core Xml Serialization Generation Utility, Version 1.0.0-preview1]
  Copyright (C) Microsoft Corporation. All rights reserved.
  Using D:\dd\corefx\bin\testhost\netcoreapp-Windows_NT-Debug-x64\ as the test runtime folder.
  Executing in D:\dd\corefx\bin\tests\System.IO.IsolatedStorage.Tests\netcoreapp-Windows_NT-Debug-x64\
  Running tests... Start time: 13:32:08.18
  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.

  Discovering: System.IO.IsolatedStorage.Tests
  Serialization Code File Name: D:\dd\corefx\bin\tests\Microsoft.XmlSerializer.Generator.Tests\netcoreapp-Windows_NT-Debug-x64\Microsoft.XmlSerializer.Generator.Tests.XmlSerializers.cs.
  Generated serialization code for assembly D:\dd\corefx\bin\tests\Microsoft.XmlSerializer.Generator.Tests\netcoreapp-Windows_NT-Debug-x64\Microsoft.XmlSerializer.Generator.Tests.dll --> 'D:\dd\corefx\bin\tests\Microsoft.XmlSerializer.Generator.Tests\netcoreapp-Windows_NT-Debug-x64\Microsoft.XmlSerializer.Generator.Tests.XmlSerializers.cs'.
  Discovered:  System.IO.IsolatedStorage.Tests
  Starting:    System.IO.IsolatedStorage.Tests
  Finished:    Microsoft.XmlSerializer.Generator.Tests

  === TEST EXECUTION SUMMARY ===
     Microsoft.XmlSerializer.Generator.Tests  Total: 73, Errors: 0, Failed: 0, Skipped: 0, Time: 1.634s
     System.IO.IsolatedStorage.ContainsUnknownFilesTests.ContainsUnknownFiles_CleanStore(scope: MachineStoreForDomain) [FAIL]
        System.UnauthorizedAccessException : Access to the path 'C:\ProgramData\IsolatedStorage\jdnr2up3.r5o\tzo0ywlm.ejr\StrongName.523eyfdtenor3l0btjpf240vsoo5jc3i\StrongName.523eyfdtenor3l0btjpf240vsoo5jc3i\Files\' is denied.
        Stack Trace:
  Finished running tests.  End time=13:32:09.26, Exit code = 0
           D:\dd\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs(157,0): at System.IO.Win32FileSystem.CreateDirectory(String fullPath)
           D:\dd\corefx\src\System.IO.FileSystem\src\System\IO\Directory.cs(41,0): at System.IO.Directory.CreateDirectory(String path)
           D:\dd\corefx\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\Helper.Win32.cs(17,0): at System.IO.IsolatedStorage.Helper.CreateDirectory(String path, IsolatedStorageScope scope)
           D:\dd\corefx\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\IsolatedStorageFile.cs(665,0): at System.IO.IsolatedStorage.IsolatedStorageFile.Initialize(IsolatedStorageScope scope)
           D:\dd\corefx\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\IsolatedStorageFile.cs(590,0): at System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(IsolatedStorageScope scope)
           D:\dd\corefx\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\IsolatedStorageFile.cs(584,0): at System.IO.IsolatedStorage.IsolatedStorageFile.GetMachineStoreForDomain()
           D:\dd\corefx\src\System.IO.IsolatedStorage\tests\System\IO\IsolatedStorage\IsoStorageTest.cs(61,0): at System.IO.IsolatedStorage.IsoStorageTest.GetPresetScope(PresetScopes scope)
           D:\dd\corefx\src\System.IO.IsolatedStorage\tests\System\IO\IsolatedStorage\ContainsUnknownFilesTests.cs(22,0): at System.IO.IsolatedStorage.ContainsUnknownFilesTests.ContainsUnknownFiles_CleanStore(PresetScopes scope)
  Finished:    System.IO.IsolatedStorage.Tests

  === TEST EXECUTION SUMMARY ===
D:\dd\corefx\Tools\tests.targets(484,5): warning :    System.IO.IsolatedStorage.Tests  Total: 237, Errors: 0, Failed: 1, Skipped: 0, Time: 1.211s [D:\dd\corefx\src\System.IO.IsolatedStorage\tests\System.IO.IsolatedStorage.Tests.csproj]
  Finished running tests.  End time=13:32:10.07, Exit code = 1
```

DirectoryNotFoundException 
```
  Discovering: System.IO.IsolatedStorage.Tests
  Discovered:  System.IO.IsolatedStorage.Tests
  Serialization Code File Name: D:\dd\corefx\bin\tests\Microsoft.XmlSerializer.Generator.Tests\netcoreapp-Windows_NT-Debug-x64\Microsoft.XmlSerializer.Generator.Tests.XmlSerializers.cs.
  Generated serialization code for assembly D:\dd\corefx\bin\tests\Microsoft.XmlSerializer.Generator.Tests\netcoreapp-Windows_NT-Debug-x64\Microsoft.XmlSerializer.Generator.Tests.dll --> 'D:\dd\corefx\bin\tests\Microsoft.XmlSerializer.Generator.Tests\netcoreapp-Windows_NT-Debug-x64\Microsoft.XmlSerializer.Generator.Tests.XmlSerializers.cs'.
  Starting:    System.IO.IsolatedStorage.Tests
     System.IO.IsolatedStorage.ContainsUnknownFilesTests.ContainsUnknownFiles_NotOkDirectory(scope: MachineStoreForAssembly) [FAIL]
        System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\ProgramData\IsolatedStorage\rd4lgwfs.xdt\f0v0e01q.wwi\StrongName.523eyfdtenor3l0btjpf240vsoo5jc3i\AssemFiles\'.
        Stack Trace:
           D:\dd\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs(157,0): at System.IO.Win32FileSystem.CreateDirectory(String fullPath)
           D:\dd\corefx\src\System.IO.FileSystem\src\System\IO\Directory.cs(41,0): at System.IO.Directory.CreateDirectory(String path)
           D:\dd\corefx\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\Helper.Win32.cs(17,0): at System.IO.IsolatedStorage.Helper.CreateDirectory(String path, IsolatedStorageScope scope)
           D:\dd\corefx\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\IsolatedStorageFile.cs(665,0): at System.IO.IsolatedStorage.IsolatedStorageFile.Initialize(IsolatedStorageScope scope)
           D:\dd\corefx\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\IsolatedStorageFile.cs(590,0): at System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(IsolatedStorageScope scope)
           D:\dd\corefx\src\System.IO.IsolatedStorage\src\System\IO\IsolatedStorage\IsolatedStorageFile.cs(579,0): at System.IO.IsolatedStorage.IsolatedStorageFile.GetMachineStoreForAssembly()
           D:\dd\corefx\src\System.IO.IsolatedStorage\tests\System\IO\IsolatedStorage\IsoStorageTest.cs(59,0): at System.IO.IsolatedStorage.IsoStorageTest.GetPresetScope(PresetScopes scope)
           D:\dd\corefx\src\System.IO.IsolatedStorage\tests\System\IO\IsolatedStorage\ContainsUnknownFilesTests.cs(77,0): at System.IO.IsolatedStorage.ContainsUnknownFilesTests.ContainsUnknownFiles_NotOkDirectory(PresetScopes scope)
  Finished:    Microsoft.XmlSerializer.Generator.Tests

  === TEST EXECUTION SUMMARY ===
     Microsoft.XmlSerializer.Generator.Tests  Total: 73, Errors: 0, Failed: 0, Skipped: 0, Time: 1.339s
  Finished running tests.  End time=13:53:49.03, Exit code = 0
  Finished:    System.IO.IsolatedStorage.Tests

  === TEST EXECUTION SUMMARY ===
D:\dd\corefx\Tools\tests.targets(484,5): warning :    System.IO.IsolatedStorage.Tests  Total: 237, Errors: 0, Failed: 1, Skipped: 0, Time: 1.306s [D:\dd\corefx\src\System.IO.IsolatedStorage\tests\System.IO.IsolatedStorage.Tests.csproj]
```

**Comment by JeremyKuhne** [comment]
Closing as we haven't had any other reports of this test failure.
