### ISSUE TITLE
PfxTests.TestPrivateKey intermittent failure

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#2583]
I can't repro it, but I got the following once:

```
 System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestPrivateKey [FAIL]
               System.Security.Cryptography.CryptographicException : OpenCSP failed with error code 2148073494.
               Stack Trace:                  D:\Src\corefx\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\CapiHelper.cs(306,0): at Internal.NativeCrypto.CapiHelper.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
                  D:\Src\corefx\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\CapiHelper.cs(698,0): at Internal.NativeCrypto.CapiHelper.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 keySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
                  D:\Src\corefx\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\RSACryptoServiceProvider.cs(89,0): at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
                  D:\Src\corefx\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\RSACryptoServiceProvider.cs(69,0): at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 keySize, CspParameters parameters, Boolean useDefaultKeySize)
                  D:\Src\corefx\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\RSACryptoServiceProvider.cs(50,0): at System.Security.Cryptography.RSACryptoServiceProvider..ctor(CspParameters parameters)
                  D:\Src\corefx\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.PrivateKey.cs(49,0): at Internal.Cryptography.Pal.CertificatePal.get_PrivateKey()
                  D:\Src\corefx\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\RSACertificateExtensions.cs(55,0): at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.GetRSAPrivateKey(X509Certificate2 certificate)
                  D:\Src\corefx\src\System.Security.Cryptography.X509Certificates\tests\PfxTests.cs(70,0): at System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestPrivateKey()
         Finished:    System.Security.Cryptography.X509Certificates.Tests
         
         === TEST EXECUTION SUMMARY ===
            System.Security.Cryptography.X509Certificates.Tests  Total: 157, Errors: 0, Failed: 1, Skipped: 0, Time: 0.854s
```

**Comment by stephentoub** [comment]
Looks like #2396

**Comment by stephentoub** [comment]
(but it's worth noting that this error message now includes an error number after #2429)

**Comment by bartonjs** [comment]
NTE_BAD_KEYSET.

Windows told us where the key lived, then told us there was nothing at that address?  Huh...

**Comment by stephentoub** [comment]
Another:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/3305/console
```
 Discovering: System.Security.Cryptography.X509Certificates.Tests
  Discovered:  System.Security.Cryptography.X509Certificates.Tests
  Starting:    System.Security.Cryptography.X509Certificates.Tests
     System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestPrivateKey [FAIL]
        System.Security.Cryptography.CryptographicException : OpenCSP failed with error code 2148073494.
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\CapiHelper.cs(309,0): at Internal.NativeCrypto.CapiHelper.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\CapiHelper.cs(687,0): at Internal.NativeCrypto.CapiHelper.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 keySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\RSACryptoServiceProvider.cs(89,0): at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\RSACryptoServiceProvider.cs(69,0): at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 keySize, CspParameters parameters, Boolean useDefaultKeySize)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\RSACryptoServiceProvider.cs(49,0): at System.Security.Cryptography.RSACryptoServiceProvider..ctor(CspParameters parameters)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.PrivateKey.cs(30,0): at Internal.Cryptography.Pal.CertificatePal.GetRSAPrivateKey()
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\RSACertificateExtensions.cs(55,0): at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.GetRSAPrivateKey(X509Certificate2 certificate)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\tests\PfxTests.cs(67,0): at System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestPrivateKey()
  Finished:    System.Security.Cryptography.X509Certificates.Tests
```

**Comment by bartonjs** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/3305/testReport/junit/System.Security.Cryptography.X509Certificates.Tests/PfxTests/TestPrivateKey/history/ (which is really slow to load) shows that of the last 25 runs, two have failed this test.

92% reliable is still 8% annoying; but I wanted to record the stats.

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/3376/console
```
Discovering: System.Security.Cryptography.X509Certificates.Tests
  Discovered:  System.Security.Cryptography.X509Certificates.Tests
  Starting:    System.Security.Cryptography.X509Certificates.Tests
     System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestPrivateKey [FAIL]
        System.Security.Cryptography.CryptographicException : OpenCSP failed with error code 2148073494.
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\CapiHelper.cs(309,0): at Internal.NativeCrypto.CapiHelper.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\CapiHelper.cs(687,0): at Internal.NativeCrypto.CapiHelper.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 keySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\RSACryptoServiceProvider.cs(89,0): at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\RSACryptoServiceProvider.cs(69,0): at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 keySize, CspParameters parameters, Boolean useDefaultKeySize)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\RSACryptoServiceProvider.cs(49,0): at System.Security.Cryptography.RSACryptoServiceProvider..ctor(CspParameters parameters)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.PrivateKey.cs(30,0): at Internal.Cryptography.Pal.CertificatePal.GetRSAPrivateKey()
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\RSACertificateExtensions.cs(55,0): at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.GetRSAPrivateKey(X509Certificate2 certificate)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\tests\PfxTests.cs(67,0): at System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestPrivateKey()
  Finished:    System.Security.Cryptography.X509Certificates.Tests
```
Jeremy, can we disable this test until you get to the bottom of the failure?

**Comment by bartonjs** [comment]
Yeah, I can go ahead and disable both of the intermittent ones on Windows.  (I'm wondering if I need to make all of the PFX tests which use the same information bundles be parallelization-exempt... but since I've never been able to reproduce the error it's hard to say when it's fixed).

**Comment by bartonjs** [comment]
The answer might be to use a [collection fixture](http://xunit.github.io/docs/shared-context.html#collection-fixture) to ensure that the PFX data blobs are being limited to one concurrent method, since each method causes the keyfile to be written and deleted.

**Comment by AtsushiKan** [comment]
Closed inadvertently.

Suggested fix is to rebuild the PFX's without the embedded key name so Windows is forced to gen up a random GUID name each time.

**Comment by AtsushiKan** [comment]
Assigning to you so you can try out your new pfx debagger tool.

**Comment by bartonjs** [comment]
Okay, I've written two tools, and am reasonably sure they both work.
Tool 1) Using OpenSsl, read the PFX, remove the one attribute (private key friendly name), repack the PFX.
Tool 2) Using Crypt32, read the PFX with PKCS12_NO_PERSIST_KEY, re-export the PFX (which now doesn't have the private key friendly name attribute).

The OpenSsl way means that any data that was part of the original export is still there, we've just removed some.  I sort of like the simplicity of the Crypt32 tool, but it means Windows is doing semantic interpretation of the data, which means there could be some hard-to-see metadata changes (Windows will use new IV/salt values when packing the PFX, so it's not as simple as saying the encrypted segments should still be the same).

So, unless anyone wants to chime in with the Windows tool being better, I'll probably rebuild all of our PFX files/hexblobs with my private key attribute removing tool on Unix.

Before walking the PFX parse in the debugger I thought that the cert "friendly name" and private key friendly name were the same, so there'd be an easy test for this... but they aren't, and there isn't.  So it'll be a faith-based change, unfortunately.

**Comment by AtsushiKan** [comment]
One question: does that mean that PFX’s that used to request a CNG key now opens with CAPI keys.

The Pkcs tests are mostly built with CNG Pfx’s except the one that says “Capi”. I don’t think it’s a big problem if those PFX’s revert to CAPI (the tests should still pass), but it is going against the original intent and may bite us in the future if we need to write a test that’s testing a CNG/CAPI-specific edge case.

**Comment by bartonjs** [comment]
Whether the key opens with CAPI or CNG is a separate attribute in the PFX.  That's part of why I'm going with the libcrypto approach, it leaves all other metadata intact.

**Comment by AtsushiKan** [comment]
Cool.
