### ISSUE TITLE
System.Text.RegularExpressions.Tests.RegexReplaceTests/Replace OutOfMemoryException on two Regex tests on 64 bit Windows

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#25847]
These two regex tests have recently started failing consistently
```
            yield return new object[] { "([a-z]([a-z]([a-z]([a-z]([a-z]([a-z]([a-z]([a-z]([a-z]([a-z]([a-z]([a-z]([a-z]([a-z]([a-z])))))))))))))))", "abcdefghiklmnop", "$15", RegexOptions.None, 15, 0, "p" };
            yield return new object[] { "([a-z]([a-z]([a-z]([a-z]([a-z]([a-z]([a-z]([a-z]([a-z]([a-z]([a-z]([a-z]([a-z]([a-z]([a-z])))))))))))))))", "abcdefghiklmnop", "$3", RegexOptions.None, 15, 0, "cdefghiklmnop" };
```
on 64 bit Windows runs
```
Unhandled Exception of Type System.OutOfMemoryException
Message :
System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
Stack Trace :
   at Go18(RegexRunner )
   at System.Text.RegularExpressions.RegexRunner.Scan(Regex regex, String text, Int32 textbeg, Int32 textend, Int32 textstart, Int32 prevlen, Boolean quick, TimeSpan timeout)
   at System.Text.RegularExpressions.Regex.Run(Boolean quick, Int32 prevlen, String input, Int32 beginning, Int32 length, Int32 startat)
   at System.Text.RegularExpressions.Regex.Match(String input, Int32 startat)
   at System.Text.RegularExpressions.RegexReplacement.Replace(Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at System.Text.RegularExpressions.Tests.RegexReplaceTests.Replace(String pattern, String input, String replacement, RegexOptions options, Int32 count, Int32 start, String expected)
```

Nothing has changed in regex code/tests. It's also odd that the OOM is 64 bit only.

@maririos is the repro system ready and working for such a case?

**Comment by danmosemsft** [comment]
@ViktorHofer this is consistent. Any thoughts? If not can you please simplify the test or disable it for Windows 64 bit so it's not failing in daily runs.

**Comment by danmosemsft** [comment]
One hand-wavy possibility is that it was always near to the limit, and something has changed (maybe on the 64 bit images we use) that pushed it over. I don't repro locally? I suggest simplifying.

**Comment by danmosemsft** [comment]
Seems gone

**Comment by ViktorHofer** [comment]
The allocation size of these patterns seems very high because of that many capturing groups. We might want to measure what happens allocation-wise during the pattern construction.
