### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.HttpClientHandlerTest / PostAsync_CallMethod_StreamContent

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#25902]
### The operation has been canceled

Failure [20171209.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171209.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandlerTest~2FPostAsync_CallMethod_StreamContent\(remoteServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FVerifyUpload.ashx,%20content:%20StreamContentWithSyncAsyncCo...):
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : The operation has been canceled
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext() in E:\A\_work\772\s\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 464
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<PostAsync_CallMethod_StreamContent>d__80.MoveNext() in E:\A\_work\772\s\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 1463
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in E:\A\_work\772\s\corefx\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs:line 62
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext() in E:\A\_work\772\s\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 856
```

### The handle is in the wrong state for the requested operation

Failure [20171106.02](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171106.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandlerTest~2FPostAsync_CallMethod_StreamContent\(remoteServer:%20http:~2F~2Fcorefx-net.cloudapp.net~2FVerifyUpload.ashx,%20content:%20StreamContentWithSyncAsyncCop...):
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : The handle is in the wrong state for the requested operation
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext() in E:\A\_work\1586\s\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 464
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<PostAsync_CallMethod_StreamContent>d__79.MoveNext() in E:\A\_work\1586\s\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 1435
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in E:\A\_work\1586\s\corefx\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs:line 62
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext() in E:\A\_work\1586\s\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 856
```

### The handle is invalid

Failure [20171025.08](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171025.08/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandlerTest~2FPostAsync_CallMethod_StreamContent\(remoteServer:%20http:~2F~2Fcorefx-net.cloudapp.net~2FVerifyUpload.ashx,%20content:%20StreamContentWithSyncAsyncCop...):
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : The handle is invalid
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<PostAsync_CallMethod_StreamContent>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.WinHttpException.ThrowExceptionUsingLastError()
   at System.Net.Http.WinHttpHandler.SetRequestHandleRedirectionOptions(SafeWinHttpHandle requestHandle)
   at System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
```

### The operation timed out

Failure [20180226.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180226.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandlerTest~2FPostAsync_CallMethod_StreamContent(remoteServer:%20http:~2F~2Fcorefx-net.cloudapp.net~2FVerifyUpload.ashx,%20content:%20FormUrlEncodedContent%20%7B%20Hea))
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : The operation timed out

at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in E:\A\_work\14\s\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 469
at System.Net.Http.Functional.Tests.HttpClientHandlerTest.PostAsync_CallMethod_StreamContent(Uri remoteServer, HttpContent content, Byte[] expectedData) in E:\A\_work\14\s\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 2099
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in E:\A\_work\14\s\corefx\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs:line 62
at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state) in E:\A\_work\14\s\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 856
```

### A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

Failure [20180226.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180226.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest~2FPostAsync_CallMethod_StreamContent(remoteServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FVerifyUpload.ashx,%20content:%20StreamContentWithSyncAsync))
```
System.Net.Http.HttpRequestException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
---- System.Net.Sockets.SocketException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in E:\A\_work\14\s\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\ConnectHelper.cs:line 98
at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in E:\A\_work\14\s\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 221
at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask) in E:\A\_work\14\s\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 350
at System.Net.Http.HttpConnectionPool.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in E:\A\_work\14\s\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 189
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in E:\A\_work\14\s\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\RedirectHandler.cs:line 30
at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in E:\A\_work\14\s\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 469
at System.Net.Http.Functional.Tests.HttpClientHandlerTest.PostAsync_CallMethod_StreamContent(Uri remoteServer, HttpContent content, Byte[] expectedData) in E:\A\_work\14\s\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 2099
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in E:\A\_work\14\s\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\ConnectHelper.cs:line 78
```

## History of failures

Day | Build | OS | Error message
-- | -- | -- | --
5/19 | 20170519.01 | Win8.1 | The operation has been canceled
5/19 | 20170519.04 | Win7 | The handle is invalid
5/30 | 20170530.01 | Win10 | The operation has been canceled
6/1 | 20170601.03 | Win10 | The operation has been canceled
6/4 | 20170604.02 | Win7 | The operation has been canceled
6/14 | 20170614.01 | Win7 | The handle is invalid
10/9 | 20171009.03 | Win10 | The operation has been canceled
10/11 | 20171011.02 | Win7 | The handle is invalid
10/13 | 20171013.01 | Win10 | The operation has been canceled
10/17 | 20171017.02 | Win8.1 | The operation has been canceled
10/22 | 20171022.01 | Win8.1 | The operation has been canceled
10/25 | 20171025.08 | Win7 | The handle is invalid
11/5 | 20171105.01 | Win8.1 | The operation has been canceled
11/6 | 20171106.02 | Win7 | The handle is in the wrong state for the requested operation
11/13 | 20171112.01 | Win7 | The handle is in the wrong state for the requested operation
11/14 | 20171114.02 | Win7 | The operation has been canceled
11/16 | 20171116.54 | Win7 | The operation has been canceled
11/21 | 20171121.02 | Win7 | The operation has been canceled
11/27 | 20171127.02 | Win10 | The operation has been canceled
12/9 | 20171209.01 | Win10 | The operation has been canceled
12/18 | 20171218.01 | Win10 | The operation has been canceled - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171218.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandlerTest~2FPostAsync_CallMethod_StreamContent\(remoteServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FVerifyUpload.ashx,%20content:%20FormUrlEncodedContent%20%7B%20Head...)
12/31 | 20171231.01 | Win8.1 | The operation has been canceled - only in [full logs](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171231.01/workItem/System.Net.Http.Functional.Tests/wilogs)
1/11 | 20180111.01 | Win7 | The operation has been canceled - only in [full logs](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180111.01/workItem/System.Net.Http.Functional.Tests/wilogs)
1/19 | 20180119.02 | Win10 | The operation has been canceled - only in [full logs](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180119.02/workItem/System.Net.Http.Functional.Tests/wilogs)
2/26 | 20180226.01 | Win8.1 | A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180226.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest~2FPostAsync_CallMethod_StreamContent(remoteServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FVerifyUpload.ashx,%20content:%20StreamContentWithSyncAsync))
2/26 | 20180226.01 | Win8.1 | The operation timed out - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180226.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandlerTest~2FPostAsync_CallMethod_StreamContent(remoteServer:%20http:~2F~2Fcorefx-net.cloudapp.net~2FVerifyUpload.ashx,%20content:%20FormUrlEncodedContent%20%7B%20Hea))

Similar exceptions / errors as in #25896

**Comment by rmkerr** [comment]
Closing as this issue has not occurred since March 2nd.
