### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.ResponseStreamTest / GetStreamAsync_ReadToEnd_Success

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#25981]
### The handle is invalid

Failure [20171215.09](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171215.09/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FGetStreamAsync_ReadToEnd_Success(readMode:%202)):
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : The handle is invalid
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext() in E:\A\_work\1212\s\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 489
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.HttpClient.<FinishGetStreamAsync>d__33.MoveNext() in E:\A\_work\1212\s\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 252
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.ResponseStreamTest.<GetStreamAsync_ReadToEnd_Success>d__2.MoveNext() in E:\A\_work\1212\s\corefx\src\System.Net.Http\tests\FunctionalTests\ResponseStreamTest.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.WinHttpHandler.InternalReceiveResponseHeadersAsync(WinHttpRequestState state) in E:\A\_work\1212\s\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 1369
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext() in E:\A\_work\1212\s\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 863
```

### The operation has been canceled

Failure [20171201.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171201.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FGetStreamAsync_ReadToEnd_Success(readMode:%204)):
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : The operation has been canceled
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext() in E:\A\_work\327\s\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 489
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.HttpClient.<FinishGetStreamAsync>d__33.MoveNext() in E:\A\_work\327\s\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 252
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.ResponseStreamTest.<GetStreamAsync_ReadToEnd_Success>d__2.MoveNext() in E:\A\_work\327\s\corefx\src\System.Net.Http\tests\FunctionalTests\ResponseStreamTest.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in E:\A\_work\327\s\corefx\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs:line 62
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext() in E:\A\_work\327\s\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 858
```

## History of failures

Day | Build | OS | Error message
-- | -- | -- | --
9/27 | 20170927.01 | Win7 | The operation has been canceled
10/10 | 20171010.03 | Win7 | The handle is invalid
11/7 | 20171107.04 | Win8.1 | The operation has been canceled
11/13 | 20171112.01 | Win7 | The operation has been canceled
11/16 | 20171116.54 | Win7 | The operation has been canceled
12/1 | 20171201.01 | Win7 | The operation has been canceled - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171201.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FGetStreamAsync_ReadToEnd_Success(readMode:%204))
12/12 | 20171212.02 | Win7 | The handle is invalid
12/15 | 20171215.09 | Win7 | The handle is invalid - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171215.09/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FGetStreamAsync_ReadToEnd_Success(readMode:%202))
2/6 | 20180206.04 | Win7 | The operation has been canceled - only in [catastrophic failure logs](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180206.04/workItem/System.Net.Http.Functional.Tests/wilogs)
2/7 | 20180207.02 | Win7 | The operation has been canceled - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180207.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FGetStreamAsync_ReadToEnd_Success(readMode:%202))
2/26 | 20180226.02 | Win10 | The operation has been canceled - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180226.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FGetStreamAsync_ReadToEnd_Success(readMode:%201))
3/1 | 20180301.06 | Win10 | The operation has been canceled
3/6 | 20180306.02 | Win10 | The operation has been canceled
3/8 | 20180308.06 | Win8.1 | The operation has been canceled

Similar exceptions / errors as in #25896 and #25902 and #25912

**Comment by rmkerr** [comment]
Closing as this issue has not occurred since April 12th.
