### ISSUE TITLE
Test failures in System.Drawing.Common

### ISSUE THREAD

**Issue by artkpv** [dotnet/corefx#25998]
Machine:
```
OS Name:                   Майкрософт Windows 10 Pro
OS Version:                10.0.16299 N/A Build 16299
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
System Type:               x64-based PC
System Locale:             ru;Russian
Input Locale:              en-us;English (United States)
```

**IsDirectPrintingSupported_ImageFormatSupported_ReturnsExpected(imageFormat: Png)**
```
      <test name="System.Drawing.Printing.Tests.PrinterSettingsTests.IsDirectPrintingSupported_ImageFormatSupported_ReturnsExpected(imageFormat: Png)" type="System.Drawing.Printing.Tests.PrinterSettingsTests" method="IsDirectPrintingSupported_ImageFormatSupported_ReturnsExpected" time="0.0627535" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: True\r\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Printing.Tests.PrinterSettingsTests.IsDirectPrintingSupported_ImageFormatSupported_ReturnsExpected(ImageFormat imageFormat) in C:\Users\art\dev\corefx\src\System.Drawing.Common\tests\Printing\PrinterSettingsTests.cs:line 399]]></stack-trace>
        </failure>
      </test>
```

**PrinterSettingsTests.SupportsColor_ReturnsExpected**
```
      <test name="System.Drawing.Printing.Tests.PrinterSettingsTests.SupportsColor_ReturnsExpected" type="System.Drawing.Printing.Tests.PrinterSettingsTests" method="SupportsColor_ReturnsExpected" time="0.0724562" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: True\r\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Printing.Tests.PrinterSettingsTests.SupportsColor_ReturnsExpected() in C:\Users\art\dev\corefx\src\System.Drawing.Common\tests\Printing\PrinterSettingsTests.cs:line 439]]></stack-trace>
        </failure>
      </test>
```

**ToLogFont_Invoke_ReturnsExpected**
```
      <test name="System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Bold, Italic, Strikeout, gdiCharSet: 1, gdiVerticalFont: True, expectedNamePrefix: \&quot;@\&quot;, expectedWeight: 700)" type="System.Drawing.Tests.FontTests" method="ToLogFont_Invoke_ReturnsExpected" time="0.0122065" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 1\r\nActual:   204]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight) in C:\Users\art\dev\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 733]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Regular, gdiCharSet: 0, gdiVerticalFont: False, expectedNamePrefix: \&quot;\&quot;, expectedWeight: 400)" type="System.Drawing.Tests.FontTests" method="ToLogFont_Invoke_ReturnsExpected" time="0.0014526" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 0\r\nActual:   204]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight) in C:\Users\art\dev\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 733]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Regular, gdiCharSet: 10, gdiVerticalFont: False, expectedNamePrefix: \&quot;\&quot;, expectedWeight: 400)" type="System.Drawing.Tests.FontTests" method="ToLogFont_Invoke_ReturnsExpected" time="0.0013763" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 10\r\nActual:   204]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight) in C:\Users\art\dev\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 733]]></stack-trace>
        </failure>
      </test>
```

**ToLogFont_InvokeGraphics_ReturnsExpected**
```
      <test name="System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SystemDefault, expectedQuality: 0)" type="System.Drawing.Tests.FontTests" method="ToLogFont_InvokeGraphics_ReturnsExpected" time="0.0028333" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 1\r\nActual:   204]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint, Int32 expectedQuality) in C:\Users\art\dev\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 770]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: AntiAlias, expectedQuality: 3)" type="System.Drawing.Tests.FontTests" method="ToLogFont_InvokeGraphics_ReturnsExpected" time="0.0015959" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 1\r\nActual:   204]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint, Int32 expectedQuality) in C:\Users\art\dev\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 770]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: AntiAliasGridFit, expectedQuality: 3)" type="System.Drawing.Tests.FontTests" method="ToLogFont_InvokeGraphics_ReturnsExpected" time="0.001564" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 1\r\nActual:   204]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint, Int32 expectedQuality) in C:\Users\art\dev\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 770]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SingleBitPerPixel, expectedQuality: 3)" type="System.Drawing.Tests.FontTests" method="ToLogFont_InvokeGraphics_ReturnsExpected" time="0.0016513" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 1\r\nActual:   204]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint, Int32 expectedQuality) in C:\Users\art\dev\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 770]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SingleBitPerPixelGridFit, expectedQuality: 3)" type="System.Drawing.Tests.FontTests" method="ToLogFont_InvokeGraphics_ReturnsExpected" time="0.0022802" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 1\r\nActual:   204]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint, Int32 expectedQuality) in C:\Users\art\dev\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 770]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: ClearTypeGridFit, expectedQuality: 5)" type="System.Drawing.Tests.FontTests" method="ToLogFont_InvokeGraphics_ReturnsExpected" time="0.0018962" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 1\r\nActual:   204]]></message>
          <stack-trace><![CDATA[   at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint, Int32 expectedQuality) in C:\Users\art\dev\corefx\src\System.Drawing.Common\tests\FontTests.cs:line 770]]></stack-trace>
        </failure>
      </test>

```
[testResults.zip](https://github.com/dotnet/corefx/files/1576175/testResults.zip)

**Comment by artkpv** [comment]
Under **System.DirectoryServices.ActiveDirectory**

**GetDomainController_InvalidIPV6_ThrowsActiveDirectoryObjectNotFoundException**
```
      <test name="System.DirectoryServices.ActiveDirectory.Tests.DomainControllerTests.GetDomainController_InvalidIPV6_ThrowsActiveDirectoryObjectNotFoundException" type="System.DirectoryServices.ActiveDirectory.Tests.DomainControllerTests" method="GetDomainController_InvalidIPV6_ThrowsActiveDirectoryObjectNotFoundException" time="60.1207075" result="Fail">
        <traits>
          <trait name="category" value="nonuaptests" />
          <trait name="category" value="nonuapaottests" />
        </traits>
        <failure exception-type="Xunit.Sdk.ThrowsException">
          <message><![CDATA[Assert.Throws() Failure\r\nExpected: typeof(System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException)\r\nActual:   typeof(System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException): The network address is invalid.\r\n]]></message>
          <stack-trace><![CDATA[   at System.DirectoryServices.ActiveDirectory.DirectoryContext.IsContextValid(DirectoryContext context, DirectoryContextType contextType) in C:\Users\art\dev\corefx\src\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\DirectoryContext.cs:line 370
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.isServer() in C:\Users\art\dev\corefx\src\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\DirectoryContext.cs:line 431
   at System.DirectoryServices.ActiveDirectory.DomainController.GetDomainController(DirectoryContext context) in C:\Users\art\dev\corefx\src\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\DomainController.cs:line 138
   at System.DirectoryServices.ActiveDirectory.Tests.DomainControllerTests.<>c__DisplayClass3_0.<GetDomainController_InvalidIPV6_ThrowsActiveDirectoryObjectNotFoundException>b__0() in C:\Users\art\dev\corefx\src\System.DirectoryServices\tests\System\DirectoryServices\ActiveDirectory\DomainControllerTests.cs:line 46]]></stack-trace>
        </failure>
      </test>
```

[testResults.zip](https://github.com/dotnet/corefx/files/1576186/testResults.zip)

**Comment by artkpv** [comment]
Under **System.IO.FileSystem.AccessControl**

**AddAuditRule_Succeeds** 
**SetAccessRule_IgnoreExistingRule_Succeeds**
**AddAccessRule_Succeeds**
```
      <test name="System.IO.FileSystemSecurityTests.AddAuditRule_Succeeds" type="System.IO.FileSystemSecurityTests" method="AddAuditRule_Succeeds" time="0.0671332" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: NT AUTHORITY\\SYSTEM\r\nActual:   NT AUTHORITY\\СИСТЕМА]]></message>
          <stack-trace><![CDATA[   at System.IO.FileSystemSecurityTests.AddAuditRule_Succeeds() in C:\Users\art\dev\corefx\src\System.IO.FileSystem.AccessControl\tests\FileSystemSecurityTests.cs:line 288]]></stack-trace>
        </failure>
      </test>
      <test name="System.IO.FileSystemSecurityTests.SetAccessRule_IgnoreExistingRule_Succeeds" type="System.IO.FileSystemSecurityTests" method="SetAccessRule_IgnoreExistingRule_Succeeds" time="0.0169007" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: NT AUTHORITY\\SYSTEM\r\nActual:   NT AUTHORITY\\СИСТЕМА]]></message>
          <stack-trace><![CDATA[   at System.IO.FileSystemSecurityTests.SetAccessRule_IgnoreExistingRule_Succeeds() in C:\Users\art\dev\corefx\src\System.IO.FileSystem.AccessControl\tests\FileSystemSecurityTests.cs:line 83]]></stack-trace>
        </failure>
      </test>
      <test name="System.IO.FileSystemSecurityTests.AddAccessRule_Succeeds" type="System.IO.FileSystemSecurityTests" method="AddAccessRule_Succeeds" time="0.0017422" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: NT AUTHORITY\\SYSTEM\r\nActual:   NT AUTHORITY\\СИСТЕМА]]></message>
          <stack-trace><![CDATA[   at System.IO.FileSystemSecurityTests.AddAccessRule_Succeeds() in C:\Users\art\dev\corefx\src\System.IO.FileSystem.AccessControl\tests\FileSystemSecurityTests.cs:line 35]]></stack-trace>
        </failure>
      </test>
```

**RemoveAccessRule_IdenticalRule_Succeeds**
**RemoveAccessRuleAll_Succeeds**
**RemoveAuditRule_Succeeds**
```      <test name="System.IO.FileSystemSecurityTests.RemoveAccessRule_IdenticalRule_Succeeds" type="System.IO.FileSystemSecurityTests" method="RemoveAccessRule_IdenticalRule_Succeeds" time="0.0015695" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 0\r\nActual:   1]]></message>
          <stack-trace><![CDATA[   at System.IO.FileSystemSecurityTests.RemoveAccessRule_IdenticalRule_Succeeds() in C:\Users\art\dev\corefx\src\System.IO.FileSystem.AccessControl\tests\FileSystemSecurityTests.cs:line 160]]></stack-trace>
        </failure>
      </test>
      <test name="System.IO.FileSystemSecurityTests.RemoveAccessRuleAll_Succeeds" type="System.IO.FileSystemSecurityTests" method="RemoveAccessRuleAll_Succeeds" time="0.0100273" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: NT AUTHORITY\\SYSTEM\r\nActual:   NT AUTHORITY\\СИСТЕМА]]></message>
          <stack-trace><![CDATA[   at System.IO.FileSystemSecurityTests.RemoveAccessRuleAll_Succeeds() in C:\Users\art\dev\corefx\src\System.IO.FileSystem.AccessControl\tests\FileSystemSecurityTests.cs:line 258]]></stack-trace>
        </failure>
      </test>
      <test name="System.IO.FileSystemSecurityTests.RemoveAuditRule_Succeeds" type="System.IO.FileSystemSecurityTests" method="RemoveAuditRule_Succeeds" time="0.0041414" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: NT AUTHORITY\\SYSTEM\r\nActual:   NT AUTHORITY\\СИСТЕМА]]></message>
          <stack-trace><![CDATA[   at System.IO.FileSystemSecurityTests.RemoveAuditRule_Succeeds() in C:\Users\art\dev\corefx\src\System.IO.FileSystem.AccessControl\tests\FileSystemSecurityTests.cs:line 339]]></stack-trace>
        </failure>
      </test>

```

**RemoveAccessRuleSpecific_Succeeds**
**SetAuditRule_Succeeds**
```
      <test name="System.IO.FileSystemSecurityTests.RemoveAccessRuleSpecific_Succeeds" type="System.IO.FileSystemSecurityTests" method="RemoveAccessRuleSpecific_Succeeds" time="0.0023387" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 0\r\nActual:   1]]></message>
          <stack-trace><![CDATA[   at System.IO.FileSystemSecurityTests.RemoveAccessRuleSpecific_Succeeds() in C:\Users\art\dev\corefx\src\System.IO.FileSystem.AccessControl\tests\FileSystemSecurityTests.cs:line 222]]></stack-trace>
        </failure>
      </test>
      <test name="System.IO.FileSystemSecurityTests.SetAuditRule_Succeeds" type="System.IO.FileSystemSecurityTests" method="SetAuditRule_Succeeds" time="0.0027879" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: NT AUTHORITY\\SYSTEM\r\nActual:   NT AUTHORITY\\СИСТЕМА]]></message>
          <stack-trace><![CDATA[   at System.IO.FileSystemSecurityTests.SetAuditRule_Succeeds() in C:\Users\art\dev\corefx\src\System.IO.FileSystem.AccessControl\tests\FileSystemSecurityTests.cs:line 311]]></stack-trace>
        </failure>
      </test>
```

**RemoveAuditRuleSpecific_NoMatchableRuleFound**
```
      <test name="System.Security.AccessControl.DirectoryObjectSecurityTests.RemoveAuditRuleSpecific_NoMatchableRuleFound" type="System.Security.AccessControl.DirectoryObjectSecurityTests" method="RemoveAuditRuleSpecific_NoMatchableRuleFound" time="0.1170768" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[Assert.True() Failure\r\nExpected: True\r\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Security.AccessControl.DirectoryObjectSecurityTests.RemoveAuditRuleSpecific_NoMatchableRuleFound() in C:\Users\art\dev\corefx\src\System.IO.FileSystem.AccessControl\tests\DirectoryObjectSecurityTests.cs:line 194]]></stack-trace>
        </failure>
      </test>
```

**SetAccessRule_AccessControlType_Deny_Succeeds**
**RemoveAuditRule_Succeeds**
**SetAuditRule_Succeeds**
**RemoveAccessRuleSpecific_AccessControlType_Deny_NoMatchableRules_Succeeds**
```
      <test name="System.Security.AccessControl.DirectoryObjectSecurityTests.SetAccessRule_AccessControlType_Deny_Succeeds" type="System.Security.AccessControl.DirectoryObjectSecurityTests" method="SetAccessRule_AccessControlType_Deny_Succeeds" time="0.0181317" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[Assert.True() Failure\r\nExpected: True\r\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Security.AccessControl.DirectoryObjectSecurityTests.SetAccessRule_AccessControlType_Deny_Succeeds() in C:\Users\art\dev\corefx\src\System.IO.FileSystem.AccessControl\tests\DirectoryObjectSecurityTests.cs:line 674]]></stack-trace>
        </failure>
      </test>
      <test name="System.Security.AccessControl.DirectoryObjectSecurityTests.RemoveAuditRule_Succeeds" type="System.Security.AccessControl.DirectoryObjectSecurityTests" method="RemoveAuditRule_Succeeds" time="0.0137331" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[Assert.True() Failure\r\nExpected: True\r\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Security.AccessControl.DirectoryObjectSecurityTests.RemoveAuditRule_Succeeds() in C:\Users\art\dev\corefx\src\System.IO.FileSystem.AccessControl\tests\DirectoryObjectSecurityTests.cs:line 231]]></stack-trace>
        </failure>
      </test>
      <test name="System.Security.AccessControl.DirectoryObjectSecurityTests.SetAuditRule_Succeeds" type="System.Security.AccessControl.DirectoryObjectSecurityTests" method="SetAuditRule_Succeeds" time="0.0032205" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[Assert.True() Failure\r\nExpected: True\r\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Security.AccessControl.DirectoryObjectSecurityTests.SetAuditRule_Succeeds() in C:\Users\art\dev\corefx\src\System.IO.FileSystem.AccessControl\tests\DirectoryObjectSecurityTests.cs:line 274]]></stack-trace>
        </failure>
      </test>
      <test name="System.Security.AccessControl.DirectoryObjectSecurityTests.RemoveAccessRuleSpecific_AccessControlType_Deny_NoMatchableRules_Succeeds" type="System.Security.AccessControl.DirectoryObjectSecurityTests" method="RemoveAccessRuleSpecific_AccessControlType_Deny_NoMatchableRules_Succeeds" time="0.009831" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[Assert.True() Failure\r\nExpected: True\r\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Security.AccessControl.DirectoryObjectSecurityTests.RemoveAccessRuleSpecific_AccessControlType_Deny_NoMatchableRules_Succeeds() in C:\Users\art\dev\corefx\src\System.IO.FileSystem.AccessControl\tests\DirectoryObjectSecurityTests.cs:line 454]]></stack-trace>
        </failure>
      </test>
```

And more. See the attached zip.
[testResults.zip](https://github.com/dotnet/corefx/files/1576206/testResults.zip)

**Comment by artkpv** [comment]
Under **System.Net.Security**

**NegotiateStream_StreamToStream_Authentication_EmptyCredentials_Fails**
```
      <test name="System.Net.Security.Tests.NegotiateStreamStreamToStreamTest_Sync.NegotiateStream_StreamToStream_Authentication_EmptyCredentials_Fails" type="System.Net.Security.Tests.NegotiateStreamStreamToStreamTest_Sync" method="NegotiateStream_StreamToStream_Authentication_EmptyCredentials_Fails" time="0.0615663" result="Fail">
        <traits>
          <trait name="category" value="nonnetfxtests" />
          <trait name="category" value="nonlinuxtests" />
          <trait name="category" value="nonosxtests" />
          <trait name="category" value="nonfreebsdtests" />
          <trait name="category" value="nonnetbsdtests" />
        </traits>
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\n                       ↓ (pos 13)\r\nExpected: NT AUTHORITY\\ANONYMOUS LOGON\r\nActual:   NT AUTHORITY\\АНОНИМНЫЙ ВХОД\r\n                       ↑ (pos 13)]]></message>
          <stack-trace><![CDATA[   at System.Net.Security.Tests.IdentityValidator.AssertHasName(IIdentity identity, String expectedName) in C:\Users\art\dev\corefx\src\System.Net.Security\tests\FunctionalTests\IdentityValidator.Windows.cs:line 20
   at System.Net.Security.Tests.NegotiateStreamStreamToStreamTest.<NegotiateStream_StreamToStream_Authentication_EmptyCredentials_Fails>d__5.MoveNext() in C:\Users\art\dev\corefx\src\System.Net.Security\tests\FunctionalTests\NegotiateStreamStreamToStreamTest.cs:line 187
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---]]></stack-trace>
        </failure>
      </test>
```

**NegotiateStream_StreamToStream_Authentication_EmptyCredentials_Fails**
```
      <test name="System.Net.Security.Tests.NegotiateStreamStreamToStreamTest_BeginEnd.NegotiateStream_StreamToStream_Authentication_EmptyCredentials_Fails" type="System.Net.Security.Tests.NegotiateStreamStreamToStreamTest_BeginEnd" method="NegotiateStream_StreamToStream_Authentication_EmptyCredentials_Fails" time="0.0433484" result="Fail">
        <traits>
          <trait name="category" value="nonnetfxtests" />
          <trait name="category" value="nonlinuxtests" />
          <trait name="category" value="nonosxtests" />
          <trait name="category" value="nonfreebsdtests" />
          <trait name="category" value="nonnetbsdtests" />
        </traits>
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\n                       ↓ (pos 13)\r\nExpected: NT AUTHORITY\\ANONYMOUS LOGON\r\nActual:   NT AUTHORITY\\АНОНИМНЫЙ ВХОД\r\n                       ↑ (pos 13)]]></message>
          <stack-trace><![CDATA[   at System.Net.Security.Tests.IdentityValidator.AssertHasName(IIdentity identity, String expectedName) in C:\Users\art\dev\corefx\src\System.Net.Security\tests\FunctionalTests\IdentityValidator.Windows.cs:line 20
   at System.Net.Security.Tests.NegotiateStreamStreamToStreamTest.<NegotiateStream_StreamToStream_Authentication_EmptyCredentials_Fails>d__5.MoveNext() in C:\Users\art\dev\corefx\src\System.Net.Security\tests\FunctionalTests\NegotiateStreamStreamToStreamTest.cs:line 187
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---]]></stack-trace>
        </failure>
      </test>
```

And other similar. Please see the attached zip
[testResults.zip](https://github.com/dotnet/corefx/files/1576210/testResults.zip)

**Comment by danmosemsft** [comment]
Some are fixed already, some we will track separately.
