### ISSUE TITLE
Compression Dispose_WithUnfinishedWriteAsync Fail

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#26089]
`Windows.7.Amd64.Open-Release-x86`

https://github.com/dotnet/corefx/pull/26086#issuecomment-354316908 System.IO.Compression.DeflateStreamUnitTests/Dispose_WithUnfinishedWriteAsync [FAIL] 
```
System.IO.Compression.DeflateStreamUnitTests/Dispose_WithUnfinishedWriteAsync

Assert.Throws() Failure
Expected: typeof(System.AggregateException)
Actual:   (No exception was thrown)

   at System.IO.Compression.CompressionStreamUnitTestBase.<Dispose_WithUnfinishedWriteAsync>d__5.MoveNext() in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\IO\Compression\CompressionStreamUnitTestBase.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
```

https://github.com/dotnet/corefx/pull/26068#issuecomment-354036924 System.IO.Compression.GzipStreamUnitTests.Dispose_WithUnfinishedWriteAsync [FAIL]
```
17:19:30   xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
17:19:31     Discovering: System.IO.Compression.Tests
17:19:31     Discovered:  System.IO.Compression.Tests
17:19:31     Starting:    System.IO.Compression.Tests
17:19:34       System.IO.Compression.GzipStreamUnitTests.Dispose_WithUnfinishedWriteAsync [FAIL]
17:19:34         Assert.False() Failure
17:19:34         Expected: False
17:19:34         Actual:   True
17:19:34         Stack Trace:
17:19:34              at System.IO.Compression.CompressionStreamUnitTestBase.<Dispose_WithUnfinishedWriteAsync>d__5.MoveNext()
17:19:34           --- End of stack trace from previous location where exception was thrown ---
17:19:34              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
17:19:34              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
17:19:34           --- End of stack trace from previous location where exception was thrown ---
17:19:34              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
17:19:34              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
17:19:34           --- End of stack trace from previous location where exception was thrown ---
17:19:34              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
17:19:34              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
17:19:36     Finished:    System.Collections.Concurrent.Tests
```

**Comment by danmosemsft** [comment]
The 2nd one was on NETFX

**Comment by benaadams** [comment]
Also intermittent :(

**Comment by Sunny-pu** [comment]
failed again:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20180115.01/workItem/System.IO.Compression.Tests/analysis/xunit/System.IO.Compression.DeflateStreamUnitTests~2FDispose_WithUnfinishedWriteAsync

**Comment by stephentoub** [comment]
Just failed again:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/20b481acdf8e4146f359dc8b388f823c22a8541b/workItem/System.IO.Compression.Tests/analysis/xunit/System.IO.Compression.DeflateStreamUnitTests~2FDispose_WithUnfinishedWriteAsync
```
Unhandled Exception of Type Xunit.Sdk.ThrowsException
Message :
Assert.Throws() Failure
Expected: typeof(System.AggregateException)
Actual:   (No exception was thrown)
Stack Trace :
   at System.IO.Compression.CompressionStreamUnitTestBase.Dispose_WithUnfinishedWriteAsync() in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\IO\Compression\CompressionStreamUnitTestBase.cs:line 183
```

**Comment by stephentoub** [comment]
Just failed again on netfx:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/7847/consoleText
```
      System.IO.Compression.GzipStreamUnitTests.Dispose_WithUnfinishedWriteAsync [FAIL]
        Assert.False() Failure
        Expected: False
        Actual:   True
        Stack Trace:
             at System.IO.Compression.CompressionStreamUnitTestBase.Dispose_WithUnfinishedWriteAsync()
```

**Comment by stephentoub** [comment]
Failed again:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/8123/consoleText

**Comment by stephentoub** [comment]
Failed again:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/8405/consoleText
```
      System.IO.Compression.GzipStreamUnitTests.Dispose_WithUnfinishedWriteAsync [FAIL]
        Assert.False() Failure
        Expected: False
        Actual:   True
        Stack Trace:
             at System.IO.Compression.CompressionStreamUnitTestBase.Dispose_WithUnfinishedWriteAsync()
```
