### ISSUE TITLE
[ManagedHandler] Test failure: System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandler_ServerCertificates_Test / UseCallback_ValidCertificate_ExpectedValuesDuringCallback

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#26091]
## Types of failures

```
System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception.
---- Expected None, got RemoteCertificateChainErrors with chain status RevocationStatusUnknown
Expected: True
Actual:   False
at System.Net.Http.HttpConnectionHandler.<>c__DisplayClass5_0.<EstablishSslConnection>b__0(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) in /root/corefx-1245305/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnectionHandler.cs:line 59
at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback, ProtocolToken& alertToken) in /root/corefx-1245305/src/System.Net.Security/src/System/Net/Security/SecureChannel.cs:line 1026
at System.Net.Security.SslState.CompleteHandshake(ProtocolToken& alertToken) in /root/corefx-1245305/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 1015
at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) in /root/corefx-1245305/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 809
at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) in /root/corefx-1245305/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 793
at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) in /root/corefx-1245305/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 962
at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) in /root/corefx-1245305/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 865
at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) in /root/corefx-1245305/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 822
at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) in /root/corefx-1245305/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 793
at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) in /root/corefx-1245305/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 962
at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest) in /root/corefx-1245305/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 1096
--- End of stack trace from previous location where exception was thrown ---
```

## History of failures

Date | Build | OS | Details
-- | -- | -- | --
12/17 | 20171217.01 | Centos73 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171217.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandler_ServerCertificates_Test~2FUseCallback_ValidCertificate_ExpectedValuesDuringCallback(url:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx,%20checkRevocation:%20True))
12/23 | 20171223.01 | Centos73 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171223.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandler_ServerCertificates_Test~2FUseCallback_ValidCertificate_ExpectedValuesDuringCallback(url:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx,%20checkRevocation:%20True))

Similar failure to old one (from 2017/7) on Mac: #21922

**Comment by caesar1995** [comment]
Not able to repro locally in VM. Checked the history, no failure since 12/23.

I'm not super sure about the query I used:

```
where Result == 'Fail' and Method == 'UseCallback_ValidCertificate_ExpectedValuesDuringCallback' and Type == 'System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandler_ServerCertificates_Test') on JobId
```

And the only results are the above two in problem description. Does this look right?

/cc: @davidsh @wfurt

**Comment by caesar1995** [comment]
If the query is correct, I think we can close the issue.

**Comment by davidsh** [comment]
I would suggest re-activating the test and watching for new failures.

**Comment by caesar1995** [comment]
This is not disabled test. I think we can close the issue.

**Comment by karelz** [comment]
Agreed. I also don't see any failure after 12/23.
