### ISSUE TITLE
Test failed: System.Net.Http.Functional.Tests.CancellationTest / GetAsync_ResponseContentRead_CancelUsingTimeoutOrToken_TaskCanceledQuickly

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#26117]
## Types of failures

20171231.01 build:
```
Assert.Throws() Failure
Expected: typeof(System.OperationCanceledException)
Actual:   typeof(System.Net.Http.HttpRequestException): An error occurred while sending the request.

at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext() in E:\A\_work\1594\s\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 464
--- End of stack trace from previous location where exception was thrown ---
at System.Net.Http.Functional.Tests.CancellationTest.<>c__DisplayClass2_3.<<GetAsync_ResponseContentRead_CancelUsingTimeoutOrToken_TaskCanceledQuickly>b__3>d.MoveNext() in E:\A\_work\1594\s\corefx\src\System.Net.Http\tests\FunctionalTests\CancellationTest.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
```

## History of failures

Day | Build | OS | Details
--- | --- | --- | ---
12/8 | 20171208.01 | Win7 |
12/31 | 20171231.01 | Win7 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171231.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.CancellationTest~2FGetAsync_ResponseContentRead_CancelUsingTimeoutOrToken_TaskCanceledQuickly(useTimeout:%20False,%20startResponseBody:%20True))

**Comment by karelz** [comment]
@wfurt how often does it happen now?

**Comment by wfurt** [comment]
This test seems is gone. closing.
