### ISSUE TITLE
ProcessThreadTests.TestStartTimeProperty failed on Linux in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2613]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/1488/console
```
20:32:15    System.Diagnostics.ProcessTests.ProcessThreadTests.TestStartTimeProperty [FAIL]
20:32:15       Assert+WrapperXunitException : File path: d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Diagnostics.Process\tests\System.Diagnostics.Process.Tests\ProcessThreadTests.cs. Line: 85
20:32:15       ---- Assert.InRange() Failure
20:32:15       Range:  (635742559171500970 - 635742559171722530)
20:32:15       Actual: 635742559171972800
20:32:15       Stack Trace:
20:32:16             at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
20:32:16             at Assert.InRange[T](T actual, T low, T high, String path, Int32 line)
20:32:16             at System.Diagnostics.ProcessTests.ProcessThreadTests.TestStartTimeProperty()
20:32:16          ----- Inner Stack Trace -----
20:32:16             at Assert.InRange[T](T actual, T low, T high, String path, Int32 line)
20:32:20 Finished:    System.Diagnostics.Process.Tests
20:32:20 
20:32:20 === TEST EXECUTION SUMMARY ===
20:32:20    System.Diagnostics.Process.Tests  Total: 55, Errors: 0, Failed: 1, Skipped: 0, Time: 6.307s
```

**Comment by stephentoub** [comment]
@Priya91, this also failed for me locally on Windows:
```
   System.Diagnostics.ProcessTests.ProcessTests.TestProcessStartTime [FAIL]
      Assert+WrapperXunitException : File path: \corefx\src\System.Diagnostics.Process\tests\System.Diagnostics.Process.Tests\ProcessTests.cs. Line: 380
      ---- Assert.InRange() Failure
      Range:  (635743862811612729 - 635743862811812729)
      Actual: 635743862811847819
      Stack Trace:
         \corefx\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(603,0): at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
         \corefx\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(225,0): at Assert.InRange[T](T actual, T low, T high, String path, Int32 line)
         \corefx\src\System.Diagnostics.Process\tests\System.Diagnostics.Process.Tests\ProcessTests.cs(380,0): at System.Diagnostics.ProcessTests.ProcessTests.TestProcessStartTime()
         ----- Inner Stack Trace -----
         \corefx\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(224,0): at Assert.InRange[T](T actual, T low, T high, String path, Int32 line)
Finished:    System.Diagnostics.Process.Tests
```

**Comment by stephentoub** [comment]
This failed again:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/1581/console
```
System.Diagnostics.ProcessTests.ProcessThreadTests.TestStartTimeProperty [FAIL]
19:22:30       Assert+WrapperXunitException : File path: d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Diagnostics.Process\tests\ProcessThreadTests.cs. Line: 87
19:22:30       ---- Assert.InRange() Failure
19:22:30       Range:  (635745109270447290 - 635745109270668780)
19:22:30       Actual: 635745109270786640
19:22:30       Stack Trace:
19:22:30             at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
19:22:30             at Assert.InRange[T](T actual, T low, T high, String path, Int32 line)
19:22:30             at System.Diagnostics.ProcessTests.ProcessThreadTests.TestStartTimeProperty()
19:22:30          ----- Inner Stack Trace -----
19:22:30             at Assert.InRange[T](T actual, T low, T high, String path, Int32 line)
19:22:45 Finished:    System.Diagnostics.Process.Tests
19:22:45 
19:22:45 === TEST EXECUTION SUMMARY ===
19:22:45    System.Diagnostics.Process.Tests  Total: 70, Errors: 0, Failed: 1, Skipped: 0, Time: 16.393s
```

**Comment by stephentoub** [comment]
Failed again:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/1634/console
```
17:55:46    System.Diagnostics.ProcessTests.ProcessThreadTests.TestStartTimeProperty [FAIL]
17:55:46       Assert+WrapperXunitException : File path: d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Diagnostics.Process\tests\ProcessThreadTests.cs. Line: 87
17:55:46       ---- Assert.InRange() Failure
17:55:46       Range:  (635746785199998070 - 635746785200264310)
17:55:46       Actual: 635746785200281740
17:55:46       Stack Trace:
17:55:47             at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
17:55:47             at Assert.InRange[T](T actual, T low, T high, String path, Int32 line)
17:55:47             at System.Diagnostics.ProcessTests.ProcessThreadTests.TestStartTimeProperty()
17:55:47          ----- Inner Stack Trace -----
17:55:47             at Assert.InRange[T](T actual, T low, T high, String path, Int32 line)
17:56:01 Finished:    System.Diagnostics.Process.Tests
```
