### ISSUE TITLE
IsolatedStorage tests can use too long Mutex name on Unix

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#26132]
This failure is because the name is too long.

It is using
`@"Global\" + **IdentityHelper.GetStrongHashSuitableForObjectName(pathName))`

apparently this is producing something longer than Unix's GetMaximumPath

It starts with "rootdirectory" which originates in one of the applicationdata folder equivalents
GetStrongHashSuitableForObjectName does a SHA1 hash which is 20 bytes
then ToBase32StringSuitableForDirName which creates 8 chars for each 5 input so 32 chars
so with Global\ prepended I would expect 39 chars which does not seem very long. I wonder what max path was on this system.

```
  Starting:    System.IO.IsolatedStorage.Tests
  FailFast: 
  
     at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline_prtest/src/mscorlib/shared/System/Diagnostics/Debug.cs:line 97
     at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline_prtest/src/mscorlib/src/System/Threading/Mutex.cs:line 108
     at System.IO.IsolatedStorage.Helper.CreateMutexNotOwned(String pathName) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline_prtest/_/fx/src/System.IO.IsolatedStorage/src/System/IO/IsolatedStorage/Helper.Win32Unix.cs:line 146
     at System.IO.IsolatedStorage.Helper.GetRandomDirectory(String rootDirectory, IsolatedStorageScope scope) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline_prtest/_/fx/src/System.IO.IsolatedStorage/src/System/IO/IsolatedStorage/Helper.Win32Unix.cs:line 86
     at System.IO.IsolatedStorage.TestHelper..cctor() in /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline_prtest/_/fx/src/System.IO.IsolatedStorage/tests/System/IO/IsolatedStorage/TestHelper.cs:line 29
     at System.IO.IsolatedStorage.TestHelper.WipeStores() in /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline_prtest/_/fx/src/System.IO.IsolatedStorage/tests/System/IO/IsolatedStorage/TestHelper.cs:line 107
     at System.IO.IsolatedStorage.ContainsUnknownFilesTests.ContainsUnknownFiles_NotOkDirectory(PresetScopes scope) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline_prtest/_/fx/src/System.IO.IsolatedStorage/tests/System/IO/IsolatedStorage/ContainsUnknownFilesTests.cs:line 75
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
```

**Comment by danmosemsft** [comment]
Fixing https://github.com/dotnet/corefx/issues/26130 should log the max and the actual making this actionable.
