### ISSUE TITLE
[Regression] Tests failed in System.ServiceProcess - FileNotFoundException

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#26157]
Failure is on all Windows OS versions (not Linux/Mac).
Likely regression from #26136 (@danmosemsft) - see @weshaggard's comment. I wonder why CI didn't catch it. I thought we use the same Helix infrastructure ...

## Types of failures

Affected tests:
* System.ServiceProcess.Tests.ServiceBaseTests /
  * TestOnContinueBeforePause
  * TestOnExecuteCustomCommand
  * TestOnPauseAndContinueThenStop
  * TestOnPauseThenStop
  * TestOnStartThenStop
  * TestOnStartWithArgsThenStop
* System.ServiceProcess.Tests.ServiceControllerTests / StartWithArguments

Failure:
```
System.IO.FileNotFoundException : Could not find file 'C:\\dotnetbuild\\work\\0488636f-ecff-467c-b6ef-343e05f4beae\\Work\\a8a48bf5-b649-4f63-999b-f9895293cdbd\\Unzip\\xunit.console.netcore.exe.9c0ebd24-e19c-43b3-97f7-3164daf3f557.log'.
at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle) in E:\A\_work\1709\s\src\mscorlib\shared\System\IO\FileStream.Windows.cs:line 1661
at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options) in E:\A\_work\1709\s\src\mscorlib\shared\System\IO\FileStream.Win32.cs:line 42
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) in E:\A\_work\1709\s\src\mscorlib\shared\System\IO\FileStream.cs:line 229
at System.ServiceProcess.Tests.TestServiceProvider.GetServiceOutput() in E:\A\_work\1410\s\corefx\src\System.ServiceProcess.ServiceController\tests\TestServiceProvider.cs:line 126
at System.ServiceProcess.Tests.ServiceBaseTests.TestOnContinueBeforePause() in E:\A\_work\1410\s\corefx\src\System.ServiceProcess.ServiceController\tests\ServiceBaseTests.cs:line 174
```

## History of failures

Builds:
* [20180104.02](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180104.02/workItem/System.ServiceProcess.ServiceController.Tests) - 63 failures (7 tests, 9 platforms each)
* [20180104.04](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180104.04/workItem/System.ServiceProcess.ServiceController.Tests) - 63 failures (7 tests, 9 platforms each)

**Comment by danmosemsft** [comment]
@karelz CI does not run as admin, so the tests would not run there (if it did I would have to request outerloop as well). Also unfortunately the tests will not run locally - for some reason new services started as LocalService won't start on my machine.

@weshaggard before I go just revert the AppendAllText part, can you explain how it caused this? File.AppendAllText disposes its StreamWriter causing it to flush before it returns. Do you suspect that simply the opening and closing of the file is causing "file system unreliability" which opening and closing once would not do? Would you mind pushing whatever fix you think, since apparently you can actually run the tests locally successfully?

**Comment by danmosemsft** [comment]
Ah, it has the `xunit.console.netcore.exe.` prefix...
