### ISSUE TITLE
Debian SSLStream Exception

### ISSUE THREAD

**Issue by zokiad** [dotnet/corefx#26178]
Hi,

I have SSL exception when call AuthenticateAsClient on several web site on Debian 9. Work fine on windows 10.

Follow the test case (VS 2017  15.5.2):
[TestSSLStream.zip](https://github.com/dotnet/corefx/files/1606593/TestSSLStream.zip)
```c#
using System;
using System.IO;
using System.Net;
using System.Net.Security;
using System.Net.Sockets;

namespace TestSSLStream
{
    class Program
    {
        static void Main(string[] args)
        {
            Uri uri = new Uri(args[0]);
            IPHostEntry dns = Dns.Resolve(uri.Host);

            using (TcpClient client = new TcpClient())
            {
                client.Connect(/*dns.AddressList[0]*/uri.Host, uri.Port);
                client.ReceiveTimeout = 10000;

                using (SslStream sslStream = new SslStream(client.GetStream(), false))
                {
                    sslStream.AuthenticateAsClient(uri.Host);

                    // Check certificate
                    string expirationDate = sslStream.RemoteCertificate.GetExpirationDateString();

                    StreamWriter writer = new StreamWriter(sslStream);
                    writer.Write("GET " + uri.AbsolutePath + " HTTP/1.1\r\n");
                    writer.Write("Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\n");
                    writer.Write("Accept-Encoding: gzip, deflate\r\n");
                    writer.Write("Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3\r\n");
                    writer.Write("User-Agent: Mozilla/5.0 (compatible; TestBot; TEST)\r\n");
                    writer.Write("Connection: close\r\n");
                    writer.Write("Host: " + uri.Host + "\r\n\r\n");
                    writer.Flush();

                    StreamReader reader = new StreamReader(sslStream);
                    string response = reader.ReadToEnd();
                }
            }
        }
    }
}
```

On debian:
> dotnet --info

> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.4
>   Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff

On debian, Exception when execute:
> dotnet TestSSLStream.dll https://korben.info/
> dotnet TestSSLStream.dll https://www.toutvendre.fr

work fine with certificate of github:
> dotnet TestSSLStream.dll https://github.com

All certificate are not managed on debian 9  with ssl stream?

[EDIT] Added C# code from the zip file

**Comment by Clockwork-Muse** [comment]
What's the exception?  The stack trace?  Especially as there may be environment settings not included in your test case.

It's possible that those certificates don't have the root of their chain inside the certificate store?

**Comment by zokiad** [comment]
On **Windows 10**, it is work fine.

but on **debian 9**:

>  dotnet TestSSLStream.dll https://toutvendre.fr
> 
> Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
>    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>    --- End of inner exception stack trace ---
>    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>    at System.Net.FixedSizeReader.ReadPacket(Stream transport, Byte[] buffer, Int32 offset, Int32 count)
>    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
>    at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
>    at TestSSLStream.Program.Main(String[] args) in c:\users\christophe\documents\visual studio 2017\Projects\TestSSLStream\TestSSLStream\Program.cs:line 21
> Aborted
> 
> 

> 
>  dotnet TestSSLStream.dll https://korben.info
> 
> Unhandled Exception: System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
>    at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
>    at TestSSLStream.Program.Main(String[] args) in c:\users\christophe\documents\visual studio 2017\Projects\TestSSLStream\TestSSLStream\Program.cs:line 21
>

**Comment by Clockwork-Muse** [comment]
> Unhandled Exception: System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.

....which was my first guess.  [Set the `SSL_CERT_FILE`/`SSL_CERT_DIR`](https://github.com/dotnet/corefx/issues/24281#issuecomment-332930027) environment variables with an appropriate chain file, does that help?

**Comment by zokiad** [comment]
The command curl works fine with these 2 url. Thus, I think the certificate are installed.

But i try:

> SSL_CERT_DIR=/etc/ssl/certs/

I have the same result.

**Comment by Clockwork-Muse** [comment]
I believe you have to supply both parameters, and quite possibly quoted (use an empty string for the one you don't specify otherwise).

Otherwise, try specifying the `SslStream` [constructor that takes a validation callback](https://msdn.microsoft.com/en-us/library/ms145056(v=vs.110).aspx) - why does it think the remote cert is invalid?

**Comment by zokiad** [comment]
When I try with:

```
using (SslStream sslStream = new SslStream(client.GetStream(), false, new RemoteCertificateValidationCallback(ValidateServerCertificate), null))

        public static bool ValidateServerCertificate(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
        {
            if (sslPolicyErrors == SslPolicyErrors.None)
                return true;

            Console.WriteLine("Certificate error: {0}", sslPolicyErrors);

            // Do not allow this client to communicate with unauthenticated servers.
            return true;
        }
```

On linux, for web site korben, i obtain the SSL policy error: RemoteCertificateNameMismatch
On linux, for web site toutvendre, i obtain no SSL policy error.
On windows, all work fine.

Also I try this code:
```
            try
            {
                System.Net.HttpWebRequest request = HttpWebRequest.CreateHttp(args[0]);
                request.UserAgent = "User - Agent: Mozilla / 5.0(compatible; TestBot; TEST)";
                HttpWebResponse response = request.GetResponse() as HttpWebResponse;

                StreamReader readStream = new StreamReader(response.GetResponseStream());
                string body = readStream.ReadToEnd();
                Console.WriteLine(body);

                response.Close();
                Console.Out.WriteLine("HttpWebRequest OK");
            }
            catch(Exception ex)
            {
                Console.Out.WriteLine(args[0]);
            }
```
**This code work fine on Linux and windows and on these 2 websites.**

Thus, the issue is with usage of TcpClient and sslStream.

I cannot use HttpRequest because I want to check ssl certificate and try several web site on web farm (use IP with different Host). HttpRequest don't allow us to do that.

**Comment by Clockwork-Muse** [comment]
...of course the issue is with `SslStream` - you're getting certificate validation errors (well, in at least one case).  An exception for toutvendre makes no sense, since there were 0 policy errors.  korben has a wildcard certificate, so I'm wondering if that's the problem...?

**Comment by karelz** [comment]
Looks like the question was answered + no activity for 16 days, closing.
