### ISSUE TITLE
[New Tests] Failed: System.ServiceProcess.Tests.ServiceBaseTests / LogWritten & LogWritten_AutoLog_False

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#26333]
Affected tests (introduced in PR #26260 - @Anipik):
* LogWritten
* LogWritten_AutoLog_False

Failure of `LogWritten` test:
```
System.InvalidOperationException : Cannot open log Application on computer '.'. This function is not supported on this system

at System.Diagnostics.EventLogInternal.OpenForRead(String currentMachineName) in E:\A\_work\1554\s\corefx\src\System.Diagnostics.EventLog\src\System\Diagnostics\EventLogInternal.cs:line 1112
at System.Diagnostics.EventLogInternal.get_EntryCount() in E:\A\_work\1554\s\corefx\src\System.Diagnostics.EventLog\src\System\Diagnostics\EventLogInternal.cs:line 155
at System.ServiceProcess.Tests.ServiceBaseTests.LogWritten() in E:\A\_work\1554\s\corefx\src\System.ServiceProcess.ServiceController\tests\ServiceBaseTests.cs:line 180
```

## History of failures

Day | Build | OS | Details
--- | --- | --- | --- 
1/13 | 20180113.03 | Win10.Nano | LogWritten & LogWritten_AutoLog_False
1/14 | 20180114.01 | Win10.Nano | LogWritten & LogWritten_AutoLog_False
1/14 | 20180114.03 | Win10.Nano | LogWritten & LogWritten_AutoLog_False

**Comment by Anipik** [comment]
I will disable the tests for Nano-Server.
