### ISSUE TITLE
DbConnectionPool.TryGetConnection is blocking call

### ISSUE THREAD

**Issue by mattwoberts** [dotnet/corefx#26348]
As discovered here: https://github.com/benaadams/Ben.BlockingDetector/issues/4

Dapper exposes a `QueryAsync` method, which uses this code to async open a db connection:

    await ((DbConnection) cnn).OpenAsync(cancel).ConfigureAwait(false)

That in turn calls through to [TryGetConnection](https://github.com/dotnet/corefx/blob/d75610efce77c2f2562c4f35de901ea38b6d43b7/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs#L1074-L1107) which is a blocking call.

@benaadams has a suggestion to use something like `SemphoreSlim.WaitAsync` for the async path, would that be possible?

**Comment by benaadams** [comment]
`System.Data.SqlClient.SqlConnection.OpenAsync`
Calling through to
`System.Data.ProviderBase.DbConnectionPool.TryGetConnection`

```
[16:44:31 WRN] Blocking method has been invoked and blocked, this can lead to threadpool starvation.
   at System.Threading.WaitHandle.WaitAny(WaitHandle[] waitHandles, Int32 millisecondsTimeout, Boolean exitContext)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
```

**Comment by divega** [comment]
The namespace and type names are misleading. This is code is internal to the SqlClient implementation, so moving to the right area. 

cc @saurabh500

**Comment by saurabh500** [comment]
This is not a blocking call. The WaitHandle.WaitAny is called with a 0 timeout in case of an async connection open. 
In case there is an available connection, then that is returned, else a request to create a connection is queued up which then signals the TaskCompletionSource whose task is returned in OpenAsync().

**Comment by benaadams** [comment]
The timeout used defaults to `ConnectTimeout = 15` if not specified in the connection string?

**Comment by benaadams** [comment]
Though will add a skip to the detector if the wait == 0

**Comment by saurabh500** [comment]
At this [line](https://github.com/dotnet/corefx/blob/d75610efce77c2f2562c4f35de901ea38b6d43b7/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs#L1026) the timeout is set to 0 and it is set to the connection string timeout (whether default or explicit) when the call is sync i.e. [retry==null](https://github.com/dotnet/corefx/blob/d75610efce77c2f2562c4f35de901ea38b6d43b7/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs#L1026)

**Comment by saurabh500** [comment]
@benaadams how does the Configuration plugin that you have created, work? What specific cases does it check for?

**Comment by benaadams** [comment]
Ah, you are correct. Have [changed it to skip waits of 0](https://github.com/benaadams/Ben.BlockingDetector/commit/f81ef3ee90cc41cd1e9da41c33ee28c76702bfdd) and not report them.

> how does the Configuration plugin that you have created, work?

Reports Waits issued on the SynchronisationContext (Wait, lock, Monitor etc when they become Waits) and synchronous waits against the TPL via ETW - it doesn't pick up Waits that occur only at OS level so Thread.Sleep or a synchronous .Read/.Write; or non-TPL Waits if you've moved off the Sync Context

**Comment by benaadams** [comment]
Planning to use EventPipe to catch more instances that currently slip through the net https://github.com/dotnet/coreclr/issues/15675
