### ISSUE TITLE
XsltCompiler.Tests Failure

### ISSUE THREAD

**Issue by SemperPeritus** [dotnet/corefx#26424]
I am using Windows 10 x64 and VS 2017.

*testResults.xml* snippet:
```
      <test name="System.Xml.Tests.XsltcTestFile.Var1(param0: \&quot;@*.txt\&quot;, param1: \&quot;fft19.dll\&quot;, param2: \&quot;no\&quot;, param3: \&quot;fft19\&quot;, param4: \&quot;fft19.pdb\&quot;, param5: \&quot;no\&quot;, param6: \&quot;fft19.txt\&quot;)" type="System.Xml.Tests.XsltcTestFile" method="Var1" time="0.1938606" result="Fail">
        <traits>
          <trait name="category" value="XsltcExeRequired" />
        </traits>
        <failure exception-type="OLEDB.Test.ModuleCore.CTestFailedException">
          <message><![CDATA[OLEDB.Test.ModuleCore.CTestFailedException : Output was not as expected.]]></message>
          <stack-trace><![CDATA[   at System.Xml.Tests.XsltcTestCaseBase.CompareOutput(Stream expectedStream, Stream actualStream, Int32 count) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 102
   at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean runAssemblyVerification, Boolean loadFromFile) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 186
   at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean loadFromFile) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 145
   at System.Xml.Tests.XsltcTestFile.Var1(Object param0, Object param1, Object param2, Object param3, Object param4, Object param5, Object param6) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestFile.cs:line 74]]></stack-trace>
        </failure>
      </test>
```

*testResults.xml* snippet:
```
      <test name="System.Xml.Tests.XsltcTestSettings.Var1(param0: \&quot;/SETTİNGS:SCRİPT+ sft14.xsl\&quot;, param1: \&quot;sft14.dll\&quot;, param2: \&quot;no\&quot;, param3: \&quot;sft14\&quot;, param4: \&quot;sft14.pdb\&quot;, param5: \&quot;no\&quot;, param6: \&quot;sft14.txt\&quot;)" type="System.Xml.Tests.XsltcTestSettings" method="Var1" time="0.1789098" result="Fail">
        <traits>
          <trait name="category" value="XsltcExeRequired" />
        </traits>
        <failure exception-type="OLEDB.Test.ModuleCore.CTestFailedException">
          <message><![CDATA[OLEDB.Test.ModuleCore.CTestFailedException : Output was not as expected.]]></message>
          <stack-trace><![CDATA[   at System.Xml.Tests.XsltcTestCaseBase.CompareOutput(Stream expectedStream, Stream actualStream, Int32 count) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 102
   at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean runAssemblyVerification, Boolean loadFromFile) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 186
   at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean loadFromFile) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 145
   at System.Xml.Tests.XsltcTestSettings.Var1(Object param0, Object param1, Object param2, Object param3, Object param4, Object param5, Object param6) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestSettings.cs:line 67]]></stack-trace>
        </failure>
      </test>
```

*testResults.xml* snippet:
```
<test name="System.Xml.Tests.XsltcTestBasicFunctionality.Var2(param0: \&quot;bft15a.xsl bft15b.xsl\&quot;, param1: \&quot;bft15.txt\&quot;)" type="System.Xml.Tests.XsltcTestBasicFunctionality" method="Var2" time="0.2665357" result="Fail">
        <traits>
          <trait name="category" value="XsltcExeRequired" />
        </traits>
        <failure exception-type="OLEDB.Test.ModuleCore.CTestFailedException">
          <message><![CDATA[OLEDB.Test.ModuleCore.CTestFailedException : Output was not as expected.]]></message>
          <stack-trace><![CDATA[   at System.Xml.Tests.XsltcTestCaseBase.CompareOutput(Stream expectedStream, Stream actualStream, Int32 count) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 102
   at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean runAssemblyVerification, Boolean loadFromFile) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 186
   at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean loadFromFile) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 145
   at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String baselineFile, Boolean loadFromFile) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 140
   at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String baselineFile, Boolean loadFromFile) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 135
   at System.Xml.Tests.XsltcTestBasicFunctionality.Var2(Object param0, Object param1) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestBasicFunctionality.cs:line 43]]></stack-trace>
        </failure>
      </test>
```

**Comment by danmosemsft** [comment]
@SemperPeritus perhaps you can grab https://github.com/dotnet/corefx/pull/26445 and try again see what  output you get when you run `msbuild /t:buildandtest` in `src\System.Private.Xml\tests\Xslt\XsltCompiler`

**Comment by SemperPeritus** [comment]
@danmosemsft, I grabbed your branch. The same 3 errors in `danmosemsft:xslttests` w/o and with `clean --all`.

**Comment by danmosemsft** [comment]
Right, I didn't fix anything, I was just hoping for better output.

**Comment by SemperPeritus** [comment]
First snippet:
```
 <test name="System.Xml.Tests.XsltcTestFile.Var1(param0: \&quot;@*.txt\&quot;, param1: \&quot;fft19.dll\&quot;, param2: \&quot;no\&quot;, param3: \&quot;fft19\&quot;, param4: \&quot;fft19.pdb\&quot;, param5: \&quot;no\&quot;, param6: \&quot;fft19.txt\&quot;)" type="System.Xml.Tests.XsltcTestFile" method="Var1" time="0.2696992" result="Fail">
        <traits>
          <trait name="category" value="XsltcExeRequired" />
        </traits>
        <failure exception-type="OLEDB.Test.ModuleCore.CTestFailedException">
          <message><![CDATA[OLEDB.Test.ModuleCore.CTestFailedException : Output was not as expected.\r\nExpected: `fatal error : Response file '*.txt' could not be found. ---> Illegal characters in path.\n`\r\nActual: `fatal error : Response file '*.txt' could not be found. ---> パスに無効な文字が含まれています。\n`\r\nResult: 0\r\n]]></message>
          <stack-trace><![CDATA[   at System.Xml.Tests.XsltcTestCaseBase.CompareOutput(Stream expectedStream, Stream actualStream, Int32 count) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 102
   at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean runAssemblyVerification, Boolean loadFromFile) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 186
   at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean loadFromFile) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 145
   at System.Xml.Tests.XsltcTestFile.Var1(Object param0, Object param1, Object param2, Object param3, Object param4, Object param5, Object param6) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestFile.cs:line 74]]></stack-trace>
        </failure>
      </test>
```

Second snippet:
```
<test name="System.Xml.Tests.XsltcTestSettings.Var1(param0: \&quot;/SETTİNGS:SCRİPT+ sft14.xsl\&quot;, param1: \&quot;sft14.dll\&quot;, param2: \&quot;no\&quot;, param3: \&quot;sft14\&quot;, param4: \&quot;sft14.pdb\&quot;, param5: \&quot;no\&quot;, param6: \&quot;sft14.txt\&quot;)" type="System.Xml.Tests.XsltcTestSettings" method="Var1" time="0.2911985" result="Fail">
        <traits>
          <trait name="category" value="XsltcExeRequired" />
        </traits>
        <failure exception-type="OLEDB.Test.ModuleCore.CTestFailedException">
          <message><![CDATA[OLEDB.Test.ModuleCore.CTestFailedException : Output was not as expected.\r\nExpected: `fatal error : Unrecognized option: '/SETTINGS:SCRIPT+'.\n`\r\nActual: `fatal error : Unrecognized option: '/SETT?NGS:SCR?PT+'.\n`\r\nResult: 0\r\n]]></message>
          <stack-trace><![CDATA[   at System.Xml.Tests.XsltcTestCaseBase.CompareOutput(Stream expectedStream, Stream actualStream, Int32 count) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 102
   at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean runAssemblyVerification, Boolean loadFromFile) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 186
   at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean loadFromFile) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 145
   at System.Xml.Tests.XsltcTestSettings.Var1(Object param0, Object param1, Object param2, Object param3, Object param4, Object param5, Object param6) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestSettings.cs:line 67]]></stack-trace>
        </failure>
      </test>
```

Third snippet:
```
<test name="System.Xml.Tests.XsltcTestBasicFunctionality.Var2(param0: \&quot;bft15a.xsl bft15b.xsl\&quot;, param1: \&quot;bft15.txt\&quot;)" type="System.Xml.Tests.XsltcTestBasicFunctionality" method="Var2" time="0.3741741" result="Fail">
        <traits>
          <trait name="category" value="XsltcExeRequired" />
        </traits>
        <failure exception-type="OLEDB.Test.ModuleCore.CTestFailedException">
          <message><![CDATA[OLEDB.Test.ModuleCore.CTestFailedException : Output was not as expected.\r\nExpected: `bft15b.xsl(3,18) : error : Stylesheet 'bft15a.xsl' cannot directly or indirectly include or import itself.\nbft15a.xsl(3,18) : error : Stylesheet 'bft15b.xsl' cannot directly or indirectly include or import itself.\n`\r\nActual: `bft15b.xsl(3,18) : error : 直接的、間接的を問わず、スタイルシート 'bft15a.xsl' を含めることはできません。また、それ自身をインポートすることもできません。\nbft15a.xsl(3,18) : error : 直接的、間接的を問わず、スタイルシート 'bft15b.xsl' を含めることはできません。また、それ自身をインポートすることもできません。\n`\r\nResult: 0\r\n]]></message>
          <stack-trace><![CDATA[   at System.Xml.Tests.XsltcTestCaseBase.CompareOutput(Stream expectedStream, Stream actualStream, Int32 count) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 102
   at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean runAssemblyVerification, Boolean loadFromFile) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 186
   at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean loadFromFile) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 145
   at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String baselineFile, Boolean loadFromFile) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 140
   at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String baselineFile, Boolean loadFromFile) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 135
   at System.Xml.Tests.XsltcTestBasicFunctionality.Var2(Object param0, Object param1) in C:\Users\plato\source\repos\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestBasicFunctionality.cs:line 43]]></stack-trace>
        </failure>
      </test>
```

**Comment by danmosemsft** [comment]
Ah it's imply that it's expecting English (as .NET Core is not currently localized) and the output contains Japanese (as .NET Framework is localized)

It needs to either do "Contains" since the first half is English -- or possibly skip on non English (less than ideal)

**Comment by danmosemsft** [comment]
I see some are 100% non English. If there was a way to launch xsltc.exe with ENU culture this would probably work (those resources are always installed) but I don't know a way. I think for non ENU we should simply do something like verify that if `: error :` appears in the expected output, it's in the actual output.. that's marginally better than disabling.

If you want to have a go @SemperPeritus you could make that change here https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/tests/Xslt/XsltCompiler/CommonScenarios/XsltcTestCaseBase.cs#L97

**Comment by tarekgh** [comment]
https://mc.dot.net/#/user/tarekgh/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/6a8c730f376ab6f5d975be53704b2f96cbdc0a81/workItem/XsltCompiler.Tests
