### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.SchSendAuxRecordHttpTest / HttpClient_ClientUsesAuxRecord_Ok

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#26539]
## Type of failures

```
System.TimeoutException : Task timed out after 15000
at System.Threading.Tasks.TaskTimeoutExtensions.<TimeoutAfter>d__0.MoveNext()
at System.Net.Http.Functional.Tests.SchSendAuxRecordHttpTest.<HttpClient_ClientUsesAuxRecord_Ok>d__2.MoveNext() in E:\A\_work\2359\s\corefx\src\System.Net.Http\tests\FunctionalTests\SchSendAuxRecordHttpTest.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
```

## History of failures

Day | Build | OS | Details
-- | -- | -- | -- 
1/3 | 20180103.03 | Win7 |
1/20 | 20180120.02 | Win7 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180120.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SchSendAuxRecordHttpTest~2FHttpClient_ClientUsesAuxRecord_Ok)
1/20 | 20180120.02 | Win7 | [ManagedHandler] [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180120.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_SchSendAuxRecordHttpTest~2FHttpClient_ClientUsesAuxRecord_Ok)

**Comment by pjanotti** [comment]
Notice that this test uses localhost, likely something related to how the test tear-down the connection.

**Comment by stephentoub** [comment]
Failed again here:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/155361ca207ff26ad91a6bc7f03765367b4a2cba/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandler_SchSendAuxRecordHttpTest~2FHttpClient_ClientUsesAuxRecord_Ok
System.Net.Http.Functional.Tests.SocketsHttpHandler_SchSendAuxRecordHttpTest/HttpClient_ClientUsesAuxRecord_Ok
```
Windows.81.Amd64.Open-x64-Debug
Unhandled Exception of Type System.Net.Http.HttpRequestException
Message :
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.IO.IOException : Unable to read data from the transport connection: An established connection was aborted by the software in your host machine.
-------- System.Net.Sockets.SocketException : An established connection was aborted by the software in your host machine
Stack Trace :
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 649
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 270
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\RedirectHandler.cs:line 30
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 511
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 139
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, Int32 millisecondsTimeout) in D:\j\workspace\windows-TGrou---db113413\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 19
   at System.Net.Http.Functional.Tests.SchSendAuxRecordHttpTest.HttpClient_ClientUsesAuxRecord_Ok() in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\tests\FunctionalTests\SchSendAuxRecordHttpTest.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Security.SslStreamInternal.<WriteSingleChunk>g__CompleteAsync|36_1[TWriteAdapter](ValueTask writeTask, Byte[] bufferToReturn) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Security\src\System\Net\Security\SslStreamInternal.cs:line 438
   at System.Net.Security.SslStreamInternal.<WriteAsyncInternal>g__ExitWriteAsync|35_0[TWriteAdapter](ValueTask task) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Security\src\System\Net\Security\SslStreamInternal.cs:line 372
   at System.Net.Http.HttpConnection.WriteBytesSlowAsync(Byte[] bytes) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 1032
   at System.Net.Http.HttpConnection.WriteHostHeaderAsync(Uri uri) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 292
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 419
----- Inner Stack Trace -----
```

**Comment by geoffkizer** [comment]
I see this occasionally in local runs.

The problem with this test is that the server doesn't necessarily read to the end of the request. When that happens, it will close the connection and cause a failure in the client, as seen above.

We need to modify the test to either read to the end of the request, or ignore the error. Reading to the end isn't trivial because we will need to process chunked encoding to know where the request ends. On the other hand, ignoring the error isn't ideal either because it could mask a real error here, or potentially cause the test to hang.

This test uses a custom loopback server -- HttpsTestServer -- to implement the test. We probably want to change this to use the standard test loopback server, if possible. This should allow us to just automatically handle chunked encoding properly. 

In the meantime, we should consider disabling this test.

**Comment by ahsonkhan** [comment]
Failed again in https://github.com/dotnet/corefx/pull/39668 on netcoreapp-Windows_NT-Release-x86-Windows.7.Amd64.Open
https://helix.dot.net/api/2019-06-17/jobs/a010b131-cd81-4199-95e5-467864b427aa/workitems/System.Net.Http.Functional.Tests/console

```text
 System.Net.Http.Functional.Tests.PlatformHandler_SchSendAuxRecordHttpTest.HttpClient_ClientUsesAuxRecord_Ok [FAIL]
      System.TimeoutException : WhenAllOrAnyFailed timed out after 15000ms
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(75,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/System.Net.Http/tests/FunctionalTests/SchSendAuxRecordHttpTest.cs(72,0): at System.Net.Http.Functional.Tests.SchSendAuxRecordHttpTest.HttpClient_ClientUsesAuxRecord_Ok()
        --- End of stack trace from previous location ---
```
