### ISSUE TITLE
[Regression] DirectoryServices tests failing - The Workstation service has not been started

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#26531]
GetDomainController_InvalidIPV6_ThrowsActiveDirectoryObjectNotFoundException test is failing on all PRs with:

```
Message :
Assert.Throws() Failure
Expected: typeof(System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException)
Actual:   typeof(System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException): The Workstation service has not been started.
Stack Trace :
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.IsContextValid(DirectoryContext context, DirectoryContextType contextType) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\DirectoryContext.cs:line 368
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.isServer() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\DirectoryContext.cs:line 431
   at System.DirectoryServices.ActiveDirectory.DomainController.GetDomainController(DirectoryContext context) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\DomainController.cs:line 128
 ```

**Comment by jkotas** [comment]
Failed in: #26530 #26529 #26524 #26521 #26511

**Comment by danmosemsft** [comment]
@dotnet/dnceng did anything change with respect to the setup of the Windows CI machines? 

Although, I didn't think this was possible: ` The Workstation service has not been started.`

@tarekgh

**Comment by karelz** [comment]
Same happened in 20180123.01 build: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180123.01/workItem/System.DirectoryServices.Tests

**Comment by weitzhandler** [comment]
#26482 too.

**Comment by tarekgh** [comment]
This looks Win7 machine environment issue. nothing changed in DirectoryServices anyway. I'll fix the test to avoid failing in such case.

**Comment by MattGal** [comment]
This is likely caused by me, but not something I can easily roll back.  We updated our version of Server 2K8 R2 (Windows 7 server) image to the most recent to pick up the most recent security patches.  Identical setup procedures are followed, and validation that the machines provision successfully and take work was done, but it would seem that the default configuration may have changed for this configuration.

@tarekgh please sync with me and let me know how the machine's configuration could be different to prevent this issue, if applicable.

**Comment by tarekgh** [comment]
@MattGal no worries. I have submitted a PR to fix the test to be more resilient. The test fix should be reliable and catch things can go wrong in the test cases. we should be fine after fixing the test.

**Comment by tarekgh** [comment]
CC @tquerec
