### ISSUE TITLE
Handling WinHttpException / Replacing it

### ISSUE THREAD

**Issue by shravan2x** [dotnet/corefx#26556]
I encountered this exception recently from a `WebSocket` instance:

```c#
System.AggregateException: One or more errors occurred. (The connection with the server was terminated abnormally) ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WinHttpWebSocket.<ReceiveAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at X.<ReceiveStringAsync>d__29.MoveNext() in C:\X.cs:line 228
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at X.<Run>d__25.MoveNext() in C:\X.cs:line 83
---> (Inner Exception #0) System.Net.Http.WinHttpException (0x80072EFF): The connection with the server was terminated abnormally
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WinHttpWebSocket.<ReceiveAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at X.<ReceiveStringAsync>d__29.MoveNext() in C:\X.cs:line 228<---
```

A `WebSocket` was closed incorrectly by the server and an `AggregateException` was thrown, which wrapped a `WinHttpException`. `WinHttpException` inherits from `Win32Exception`. I'm hesitant to handle either of these in the fear that it may not work on other platforms. I could possibly parse the exception message for "The connection with the server was terminated abnormally", but that is ugly and susceptible to framework changes.

Could this `WinHttpException` be replaced with a platform agnostic version that can be handled easily?

**Comment by davidsh** [comment]
And as of this PR https://github.com/dotnet/corefx/pull/26429, the client WebSocket implementation has been changed and is no longer built on WInHttp:

So, this issue is basically a no-op now since you will never get an WinHttpExceptions anymore

**Comment by shravan2x** [comment]
The timing is perfect!

**Comment by Davilink** [comment]
We use SignalR (the .Net Framework version because in dotnet core version isn't ready) with dotnet core 2.0, and when the Connection is drop, a WinHttpException is rise.

In the Error Event Handler i try to filter the exception using the « is » operator, but VS cannot find the assembly. 

This exception seem to be in System.Net.Http, but in the « C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5 », but when i add « Using System.Net.Http », i think the compiler look in the System.Net.Http of the dotnet runtime, not in the Net Framework runtime.

What i'm missing ?
