### ISSUE TITLE
System.Environment.GetFolderPath fails with ArgumentException

### ISSUE THREAD

**Issue by iftahbe** [dotnet/corefx#26677]
In Ubuntu 16.04 the following console app fails in case the special folder doesn't exist (e.g. in a new Docker container) even though SpecialFolderOption.Create is specified:

```
using System;

namespace Test
{
   class Program
   {
       static void Main(string[] args)
       {
            var path = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData, Environment.SpecialFolderOption.Create);
       }
   }
}
```

Exception:
```
Unhandled Exception: System.ArgumentException: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.
  at System.Reflection.RuntimeMethodInfo.CreateDelegateInternal(Type delegateType, Object firstArgument, DelegateBindingFlags bindingFlags, StackCrawlMark& stackMark)
  at System.Reflection.RuntimeMethodInfo.CreateDelegate(Type delegateType)
  at System.Environment.<>c.<GetFolderPathCore>b__52_0()
  at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Func`1 valueFactory)
  at System.Environment.GetFolderPathCore(SpecialFolder folder, SpecialFolderOption option)
  at System.Environment.GetFolderPath(SpecialFolder folder, SpecialFolderOption option)
  at Test.Program.Main(String[] args) in /home/crow/Test/Program.cs:line 9
Aborted (core dumped)
```

If the folder exists in advance there is no problem.
Also, this workaround works:

```
using System;

namespace Test
{
   class Program
   {
       static void Main(string[] args)
       {
            var path = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData, Environment.SpecialFolderOption.DoNotVerify);

            if (System.IO.Directory.Exists(path) == false)
                System.IO.Directory.CreateDirectory(path);
       }
   }
}
```

**Comment by danmosemsft** [comment]
Good find. This is because this hack is wrong (and apparently doesn't have a test)
https://github.com/dotnet/corefx/blob/17be4bc9b3fd9443026d2bf7d11a043b940bbcf4/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L83

instead of 
```c#
return (Action<string>)mi.CreateDelegate(typeof(Action<string>));
```

it should be 
```c#
return (Func<string, object>)mi.CreateDelegate(typeof(Func<string, object>));
```

Since CreateDirectory returns a DirectoryInfo, not void.

@iftahbe any interest in submitting a PR for this? Get your feet wet in the CoreFX code?

**Comment by danmosemsft** [comment]
@weshaggard is it still problematic for S.R.Extensions to reference S.IO.FileSystem?

**Comment by stephentoub** [comment]
> is it still problematic for S.R.Extensions to reference S.IO.FileSystem

S.IO.FileSystem references S.R.Extensions

**Comment by danmosemsft** [comment]
@stephentoub that's a good reason.

**Comment by iftahbe** [comment]
@danmosemsft not really, you can go ahead and fix it.

**Comment by danmosemsft** [comment]
@maryamariyan could you please fix this and add a test. As usual please make sure the test fails before your fix.

**Comment by maryamariyan** [comment]
@danmosemsft ok
