### ISSUE TITLE
TestLoadSignedFile failure in CI

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#2667]
See: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/2796/testReport/junit/System.Security.Cryptography.X509Certificates.Tests/LoadFromFileTests/TestLoadSignedFile/

```
MESSAGE:
System.Security.Cryptography.CryptographicException : Error occurred during a cryptographic operation.
+++++++++++++++++++
STACK TRACE:
at Internal.Cryptography.Pal.CertificatePal.GetSignerInPKCS7Store(SafeCertStoreHandle hCertStore, SafeCryptMsgHandle hCryptMsg) in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 142
at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, String password, X509KeyStorageFlags keyStorageFlags) in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 84
at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, String password, X509KeyStorageFlags keyStorageFlags) in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 29
at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags) in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs:line 72
at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName) in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs:line 55
at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName) in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2.cs:line 48
at System.Security.Cryptography.X509Certificates.Tests.LoadFromFileTests.TestLoadSignedFile() in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\tests\LoadFromFileTests.cs:line 127
```

**Comment by nguerrera** [comment]
++hitCount #2606

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/2967/console
```
Discovering: System.Security.Cryptography.X509Certificates.Tests
  Discovered:  System.Security.Cryptography.X509Certificates.Tests
  Starting:    System.Security.Cryptography.X509Certificates.Tests
     System.Security.Cryptography.X509Certificates.Tests.LoadFromFileTests.TestLoadSignedFile [FAIL]
        System.Security.Cryptography.CryptographicException : Error occurred during a cryptographic operation.
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest@2\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs(142,0): at Internal.Cryptography.Pal.CertificatePal.GetSignerInPKCS7Store(SafeCertStoreHandle hCertStore, SafeCryptMsgHandle hCryptMsg)
           d:\j\workspace\dotnet_corefx_windows_release_prtest@2\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs(84,0): at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, String password, X509KeyStorageFlags keyStorageFlags)
           d:\j\workspace\dotnet_corefx_windows_release_prtest@2\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs(69,0): at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
           d:\j\workspace\dotnet_corefx_windows_release_prtest@2\src\System.Security.Cryptography.X509Certificates\tests\LoadFromFileTests.cs(127,0): at System.Security.Cryptography.X509Certificates.Tests.LoadFromFileTests.TestLoadSignedFile()
  Finished:    System.Security.Cryptography.X509Certificates.Tests
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/3419/console
```
 Discovering: System.Security.Cryptography.X509Certificates.Tests
  Discovered:  System.Security.Cryptography.X509Certificates.Tests
  Starting:    System.Security.Cryptography.X509Certificates.Tests
     System.Security.Cryptography.X509Certificates.Tests.LoadFromFileTests.TestLoadSignedFile [FAIL]
        System.Security.Cryptography.CryptographicException : Error occurred during a cryptographic operation.
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs(144,0): at Internal.Cryptography.Pal.CertificatePal.GetSignerInPKCS7Store(SafeCertStoreHandle hCertStore, SafeCryptMsgHandle hCryptMsg)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs(84,0): at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, String password, X509KeyStorageFlags keyStorageFlags)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs(29,0): at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs(72,0): at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs(55,0): at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2.cs(48,0): at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\tests\LoadFromFileTests.cs(127,0): at System.Security.Cryptography.X509Certificates.Tests.LoadFromFileTests.TestLoadSignedFile()
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/3613/console
```
Discovering: System.Security.Cryptography.X509Certificates.Tests
  Discovered:  System.Security.Cryptography.X509Certificates.Tests
  Starting:    System.Security.Cryptography.X509Certificates.Tests
     System.Security.Cryptography.X509Certificates.Tests.LoadFromFileTests.TestLoadSignedFile [FAIL]
        System.Security.Cryptography.CryptographicException : Error occurred during a cryptographic operation.
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs(113,0): at Internal.Cryptography.Pal.CertificatePal.GetSignerInPKCS7Store(SafeCertStoreHandle hCertStore, SafeCryptMsgHandle hCryptMsg)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs(84,0): at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, String password, X509KeyStorageFlags keyStorageFlags)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs(69,0): at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Security.Cryptography.X509Certificates\tests\LoadFromFileTests.cs(127,0): at System.Security.Cryptography.X509Certificates.Tests.LoadFromFileTests.TestLoadSignedFile()
  Finished:    System.Security.Cryptography.X509Certificates.Tests
```

**Comment by bartonjs** [comment]
I added a note in #3062 to print the HR value in Message for debug builds; that should help to track down this problem.

We could disable this test, or move it to OuterLoop; but we'd want to re-enable it again once we get the improved error reporting so that we could hopefully track it down for real.  And, unless there're just a lot of failures for it that I don't hear about, it doesn't seem like it's a crippling level of intermittent failures (any intermittency is bad, I agree; but this isn't anything I've been able to reproduce locally)

**Comment by nguerrera** [comment]
Hit again by #3169: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/3769/console

**Comment by stephentoub** [comment]
Again here.... I believe 0xc0000005 is an access violation...
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/4007/console
```
System.Security.Cryptography.X509Certificates.Tests.LoadFromFileTests.TestLoadSignedFile [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc0000005)
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs(113,0): at Internal.Cryptography.Pal.CertificatePal.GetSignerInPKCS7Store(SafeCertStoreHandle hCertStore, SafeCryptMsgHandle hCryptMsg)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs(84,0): at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, String password, X509KeyStorageFlags keyStorageFlags)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs(69,0): at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Security.Cryptography.X509Certificates\tests\LoadFromFileTests.cs(127,0): at System.Security.Cryptography.X509Certificates.Tests.LoadFromFileTests.TestLoadSignedFile()
```

**Comment by stephentoub** [comment]
I'm going to disable the test for now, since we now have the error code (0xc0000005).

Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/4146/console
```
System.Security.Cryptography.X509Certificates.Tests.LoadFromFileTests.TestLoadSignedFile [FAIL]
        Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc0000005)
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs(144,0): at Internal.Cryptography.Pal.CertificatePal.GetSignerInPKCS7Store(SafeCertStoreHandle hCertStore, SafeCryptMsgHandle hCryptMsg)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs(84,0): at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, String password, X509KeyStorageFlags keyStorageFlags)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs(29,0): at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs(72,0): at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs(55,0): at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2.cs(48,0): at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\tests\LoadFromFileTests.cs(127,0): at System.Security.Cryptography.X509Certificates.Tests.LoadFromFileTests.TestLoadSignedFile()
```

**Comment by stephentoub** [comment]
@bartonjs, this is marked as test bug.  Do we know that to be the case?  If it's potentially a product issue, I think the milestone should be changed to 1.0.0-rtm.

**Comment by karelz** [comment]
It is likely OS bug - we should report it and make the test resilient when it is hit.
@bartonjs ran it 100,000x in a loop, but it didn't fail. It might be caused by parallel tests running.
