### ISSUE TITLE
Lots of System.Net.Http "dribble" tests have started failing

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#26729]
These tests are failing randomly on a bunch of PRs, e.g.
![image](https://user-images.githubusercontent.com/2642209/35660592-f7a82240-06da-11e8-9906-cdabf98e93a8.png)
https://mc.dot.net/#/user/caesar1995/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/811599f6d8f636fd0b43089acd4d5d4a338d8259/workItem/System.Net.Http.Functional.Tests
They look like:
```
2018-02-01 03:12:02,305: INFO: proc(54): run_and_log_output: Output:    System.Net.Http.Functional.Tests.ManagedHandler_HttpProtocolTests_Dribble.GetAsync_ResponseVersion0X_ThrowsOr10(responseMinorVersion: 9) [FAIL]
2018-02-01 03:12:02,321: INFO: proc(54): run_and_log_output: Output:       Assert.Throws() Failure
2018-02-01 03:12:02,321: INFO: proc(54): run_and_log_output: Output:       Expected: typeof(System.Net.Http.HttpRequestException)
2018-02-01 03:12:02,321: INFO: proc(54): run_and_log_output: Output:       Actual:   typeof(System.IO.IOException): Unable to transfer data on the transport connection: An existing connection was forcibly closed by the remote host.
2018-02-01 03:12:02,321: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-01 03:12:02,414: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\tests\FunctionalTests\HttpProtocolTests.cs(496,0): at System.Net.Http.Functional.Tests.HttpProtocolTests_Dribble.DribbleStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
2018-02-01 03:12:02,414: INFO: proc(54): run_and_log_output: Output:          E:\A\_work\1661\s\src\mscorlib\shared\System\IO\StreamWriter.cs(979,0): at System.IO.StreamWriter.FlushAsyncInternal(StreamWriter _this, Boolean flushStream, Boolean flushEncoder, Char[] charBuffer, Int32 charPos, Boolean haveWrittenPreamble, Encoding encoding, Encoder encoder, Byte[] byteBuffer, Stream stream, CancellationToken cancellationToken)
2018-02-01 03:12:02,414: INFO: proc(54): run_and_log_output: Output:          E:\A\_work\1661\s\src\mscorlib\shared\System\IO\StreamWriter.cs(624,0): at System.IO.StreamWriter.WriteAsyncInternal(StreamWriter _this, String value, Char[] charBuffer, Int32 charPos, Int32 charLen, Char[] coreNewLine, Boolean autoFlush, Boolean appendNewLine)
2018-02-01 03:12:02,414: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\Common\tests\System\Net\Http\LoopbackServer.cs(102,0): at System.Net.Test.Common.LoopbackServer.ReadWriteAcceptedAsync(Socket s, StreamReader reader, StreamWriter writer, String response)
2018-02-01 03:12:02,414: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\Common\tests\System\Net\Http\LoopbackServer.cs(177,0): at System.Net.Test.Common.LoopbackServer.AcceptSocketAsync(Socket server, Func`5 funcAsync, Options options)
2018-02-01 03:12:02,414: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\tests\FunctionalTests\HttpProtocolTests.cs(261,0): at System.Net.Http.Functional.Tests.HttpProtocolTests.<>c__DisplayClass7_1.<<GetAsync_ResponseVersion0X_ThrowsOr10>b__1>d.MoveNext()
2018-02-01 03:12:02,414: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
```

**Comment by stephentoub** [comment]
@geoffkizer, it looks like these are the tests in https://github.com/dotnet/corefx/pull/26585 that were just merged earlier today?

**Comment by geoffkizer** [comment]
Yes.  I don't know why these didn't show up previously.

The issue here is that the client is parsing an invalid response from the server and (correctly) disconnecting before the server finishes sending (because of the dribble logic).  So, we need to eat the exception when this happens.

I'll code up the fix and submit shortly.
