### ISSUE TITLE
[New Test] Test failure: System.Net.Http.Functional.Tests.ManagedHandler_HttpRetryProtocolTests / PostAsyncExpect100Continue_RetryOnConnectionClosed_Success

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#26760]
### An existing connection was forcibly closed by the remote host

Failure [20180202.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180202.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_HttpRetryProtocolTests~2FPostAsyncExpect100Continue_RetryOnConnectionClosed_Success):
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.IO.IOException : Unable to transfer data on the transport connection: An existing connection was forcibly closed by the remote host.
-------- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host

at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in E:\A\_work\1581\s\corefx\src\System.Net.Http\src\System\Net\Http\Managed\HttpConnection.cs:line 508
at System.Net.Http.HttpConnectionPool.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in E:\A\_work\1581\s\corefx\src\System.Net.Http\src\System\Net\Http\Managed\HttpConnectionPool.cs:line 178
at System.Net.Http.CookieHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in E:\A\_work\1581\s\corefx\src\System.Net.Http\src\System\Net\Http\Managed\CookieHandler.cs:line 31
at System.Net.Http.AuthenticateAndRedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in E:\A\_work\1581\s\corefx\src\System.Net.Http\src\System\Net\Http\Managed\AuthenticateAndRedirectHandler.cs:line 53
at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in E:\A\_work\1581\s\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 488
at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.<PostAsyncExpect100Continue_RetryOnConnectionClosed_Success>b__6_0(Uri url) in E:\A\_work\1581\s\corefx\src\System.Net.Http\tests\FunctionalTests\HttpRetryProtocolTests.cs:line 109
at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.<>c__DisplayClass4_0.<<CreateServerAndClientAsync>b__0>d.MoveNext() in E:\A\_work\1581\s\corefx\src\System.Net.Http\tests\FunctionalTests\HttpRetryProtocolTests.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass3_0.<CreateServerAsync>b__0(Task t) in E:\A\_work\1581\s\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 68
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\2298\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) in E:\A\_work\2298\s\src\mscorlib\src\System\Threading\Tasks\Task.cs:line 2440
--- End of stack trace from previous location where exception was thrown ---
at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.PostAsyncExpect100Continue_RetryOnConnectionClosed_Success() in E:\A\_work\1581\s\corefx\src\System.Net.Http\tests\FunctionalTests\HttpRetryProtocolTests.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in E:\A\_work\1581\s\corefx\src\System.Net.Http\src\System\Net\Http\Managed\HttpConnection.cs:line 365
----- Inner Stack Trace -----
```

### The server returned an invalid or unrecognized response

Failure [CI on 2/1](https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/ca709efa277ed1849d2584dd8ffcb8d97254d7e3/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_HttpRetryProtocolTests~2FPostAsyncExpect100Continue_RetryOnConnectionClosed_Success)
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.IO.IOException : The server returned an invalid or unrecognized response.

at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\Managed\HttpConnection.cs:line 508
at System.Net.Http.HttpConnectionPool.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\Managed\HttpConnectionPool.cs:line 178
at System.Net.Http.CookieHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\Managed\CookieHandler.cs:line 31
at System.Net.Http.AuthenticateAndRedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\Managed\AuthenticateAndRedirectHandler.cs:line 53
at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 488
at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.<PostAsyncExpect100Continue_RetryOnConnectionClosed_Success>b__6_0(Uri url) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\tests\FunctionalTests\HttpRetryProtocolTests.cs:line 109
at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.<>c__DisplayClass4_0.<<CreateServerAndClientAsync>b__0>d.MoveNext() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\tests\FunctionalTests\HttpRetryProtocolTests.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass3_0.<CreateServerAsync>b__0(Task t) in D:\j\workspace\windows-TGrou---74aa877a\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 67
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\2298\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) in E:\A\_work\2298\s\src\mscorlib\src\System\Threading\Tasks\Task.cs:line 2440
--- End of stack trace from previous location where exception was thrown ---
at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.PostAsyncExpect100Continue_RetryOnConnectionClosed_Success() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\tests\FunctionalTests\HttpRetryProtocolTests.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\Managed\HttpConnection.cs:line 373
```

## History of test failure

Day | Build | OS | Details
-- | -- | -- | -- 
2/1 | ca709efa277ed1849d2584dd8ffcb8d97254d7e3 | Win10 | The server returned an invalid or unrecognized response - [link](https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/ca709efa277ed1849d2584dd8ffcb8d97254d7e3/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_HttpRetryProtocolTests~2FPostAsyncExpect100Continue_RetryOnConnectionClosed_Success)
2/2 | 20180202.01 | Win7 | An existing connection was forcibly closed by the remote host - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180202.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_HttpRetryProtocolTests~2FPostAsyncExpect100Continue_RetryOnConnectionClosed_Success)

**Comment by stephentoub** [comment]
Just failed for me locally as well.
```
System.Net.Http.Functional.Tests.ManagedHandler_HttpRetryProtocolTests.PostAsyncExpect100Continue_RetryOnConnectionClosed_Success [FAIL]
        System.Net.Http.HttpRequestException : An error occurred while sending the request.
        ---- System.IO.IOException : Unable to transfer data on the transport connection: An existing connection was forcibly closed by the remote host.
        -------- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host
        Stack Trace:
           d:\repos\corefx\src\System.Net.Http\src\System\Net\Http\Managed\HttpConnection.cs(508,0): at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, CancellationToken cancella
  tionToken)
           d:\repos\corefx\src\System.Net.Http\src\System\Net\Http\Managed\HttpConnectionPool.cs(178,0): at System.Net.Http.HttpConnectionPool.SendAsync(HttpRequestMessage request, CancellationToken
  cancellationToken)
           d:\repos\corefx\src\System.Net.Http\src\System\Net\Http\Managed\CookieHandler.cs(31,0): at System.Net.Http.CookieHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellatio
  nToken)
           d:\repos\corefx\src\System.Net.Http\src\System\Net\Http\Managed\AuthenticateAndRedirectHandler.cs(53,0): at System.Net.Http.AuthenticateAndRedirectHandler.SendAsync(HttpRequestMessage requ
  est, CancellationToken cancellationToken)
           d:\repos\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(488,0): at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, Cancellatio
  nTokenSource cts, Boolean disposeCts)
           d:\repos\corefx\src\System.Net.Http\tests\FunctionalTests\HttpRetryProtocolTests.cs(109,0): at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.<PostAsyncExpect100Continue_RetryOnCo
  nnectionClosed_Success>b__6_0(Uri url)
           d:\repos\corefx\src\System.Net.Http\tests\FunctionalTests\HttpRetryProtocolTests.cs(37,0): at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.<>c__DisplayClass4_0.<<CreateServerAnd
  ClientAsync>b__0>d.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
           d:\repos\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs(67,0): at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass3_0.<CreateServerAsync>b__0(Task t)
           E:\A\_work\2298\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs(166,0): at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callb
  ack, Object state)
           --- End of stack trace from previous location where exception was thrown ---
           E:\A\_work\2298\s\src\mscorlib\src\System\Threading\Tasks\Task.cs(2440,0): at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
           --- End of stack trace from previous location where exception was thrown ---
           d:\repos\corefx\src\System.Net.Http\tests\FunctionalTests\HttpRetryProtocolTests.cs(93,0): at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.PostAsyncExpect100Continue_RetryOnConn
  ectionClosed_Success()
           --- End of stack trace from previous location where exception was thrown ---
           ----- Inner Stack Trace -----
           d:\repos\corefx\src\System.Net.Http\src\System\Net\Http\Managed\HttpConnection.cs(365,0): at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, CancellationToken cancella
  tionToken)
           ----- Inner Stack Trace -----
```

**Comment by geoffkizer** [comment]
Those are two different errors; one looks like the connection was disconnected, the other like the server sent something bad...

There must a timing issue in the test, I will take a look.

**Comment by geoffkizer** [comment]
It's possible, perhaps likely, that this is just due to the 100-continue timeout expiring.  Not sure what to do about that, though...

**Comment by geoffkizer** [comment]
The 100-continue timeout is just 1 second, so yeah, it could well be that.

@stephentoub If you can repro semi-consistently, then can you try changing the timeout here to something large and see if that fixes it?

For a real fix, we could make the timeout configurable and set it to something large for this test.

**Comment by geoffkizer** [comment]
I saw this once locally today, but that's the only time I've seen it.

**Comment by stephentoub** [comment]
It is Expect: 100-continue.  If the timing works out so that the send starts before we've got to consume the read ahead task, then when the read ahead returns 0 due to the connection having been closed, we don't retry.  As a result, the test is inherently racy, and if we change the timeout to be long (which we could do with some hacky reflection on SocketsHttpHandler but not on the handlers), then it ends up being not really a different test from GetAsync_RetryOnConnectionClosed_Success, as we've effectively forced the sending of the content to be delayed until after the connection is closed.

We could just delete the test, or we could change it to effectively test the opposite, that the connection is not reused once the content has started sending.  That ordering we can force to happen using explicit synchronization in the test.  That's my plan unless I hear otherwise.

**Comment by geoffkizer** [comment]
I guess I'm fine removing this test, but what's your objection to adding a public setting for the expect100continue timeout, and then using it here?  Exposing the timeout as a setting seems like something we should consider anyway.

I agree re adding the opposite test.

**Comment by geoffkizer** [comment]
Also agree we shouldn't do hacky reflection.

**Comment by stephentoub** [comment]
> what's your objection to adding a public setting for the expect100continue timeout

I don't have an objection to adding a public property to SocketsHttpHandler for this.  We shouldn't add such a thing to HttpClientHandler, though, if for no other reason than WinHttpHandler doesn't support Expect: 100-continue at all.  If you do want to expose a public knob on SocketsHttpHandler, can you please open an API review issue for it with the signature?

> and then using it here

We would be setting it to something sufficiently large so that the content would never send, at which point I'm not sure how the test would be sufficiently different from the GetAsync_RetryOnConnectionClosed_Success test that's already there.  The test would also no longer apply to all handlers; we'd be adding it to somewhere that's SocketsHttpHandler, and so still deleting it from here.

**Comment by geoffkizer** [comment]
> If you do want to expose a public knob on SocketsHttpHandler, can you please open an API review issue for it with the signature?

I added #27145.

I'm fine with deleting the test.
