### ISSUE TITLE
Test Failure: System.Net.Http.Functional.Tests.HttpRetryProtocolTests / GetAsync_RetryOnConnectionClosed_Success

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#26770]
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/7716/consoleFull

Test added ~3 days ago by @geoffkizer .  Test is part of innerloop CI, so should be fixed or disabled ASAP.

```
14:55:29       System.Net.Http.Functional.Tests.HttpRetryProtocolTests.GetAsync_RetryOnConnectionClosed_Success [FAIL]
14:55:29         System.Net.Http.HttpRequestException : An error occurred while sending the request.
14:55:29         ---- System.Net.WebException : The request was aborted: The request was canceled.
```

**Comment by stephentoub** [comment]
Failed again here:
https://github.com/dotnet/corefx/pull/26598#issuecomment-362475142

**Comment by stephentoub** [comment]
Again here on netfx:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/7742/consoleText
```
      System.Net.Http.Functional.Tests.HttpRetryProtocolTests.GetAsync_RetryOnConnectionClosed_Success [FAIL]
        System.Net.Http.HttpRequestException : An error occurred while sending the request.
        ---- System.Net.WebException : The request was aborted: The request was canceled.
        Stack Trace:
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.<<GetAsync_RetryOnConnectionClosed_Success>b__5_0>d.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.<>c__DisplayClass4_0.<<CreateServerAndClientAsync>b__0>d.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass3_0.<CreateServerAsync>b__0(Task t)
             at System.Threading.Tasks.Task.Execute()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.<GetAsync_RetryOnConnectionClosed_Success>d__5.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          ----- Inner Stack Trace -----
             at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
             at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
```

**Comment by stephentoub** [comment]
Seems like this is either a test bug, a misconception about how netfx behaves, or a netfx bug.
cc: @geoffkizer

**Comment by geoffkizer** [comment]
If we're only seeing this on netfx (and so far it looks that way), then we should just disable the test on netfx.

If we see it somewhere else, it's probably a test issue.

We should probably disable the test for netfx regardless, and then if we see it elsewhere we can revisit.

**Comment by danmosemsft** [comment]
AGain on NETFX... can we disable there @geoffkizer ?
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/7717/consoleText

**Comment by danmosemsft** [comment]
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/7845/consoleText

**Comment by ViktorHofer** [comment]
Failed again on `Alpine.38.Amd64.Open`: https://dev.azure.com/dnceng/public/_build/results?buildId=193290&view=ms.vss-test-web.build-test-results-tab&runId=4665596&resultId=385163

```
System.IO.IOException : Unexpected EOF trying to read request header

   at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAsync()
   at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.<>c.<<GetAsync_RetryOnConnectionClosed_Success>b__4_2>d.MoveNext() in /__w/1/s/src/System.Net.Http/tests/FunctionalTests/HttpRetryProtocolTests.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in /__w/1/s/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 116
   at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.<>c.<<GetAsync_RetryOnConnectionClosed_Success>b__4_1>d.MoveNext() in /__w/1/s/src/System.Net.Http/tests/FunctionalTests/HttpRetryProtocolTests.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /__w/1/s/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /__w/1/s/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass11_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /__w/1/s/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /__w/1/s/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 66
   at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.GetAsync_RetryOnConnectionClosed_Success() in /__w/1/s/src/System.Net.Http/tests/FunctionalTests/HttpRetryProtocolTests.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by karelz** [comment]
Triage: No `ActiveIssue` in code, netfx has been removed from the code anyway. Closing.
