### ISSUE TITLE
More DNS tests failing on macOS

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#26789]
I've seen these failures now in a good number of PRs:

DnsObsoleteGetHostByName_EmptyString_ReturnsHostName
```
Unhandled Exception of Type System.Net.Internals.SocketExceptionFactory+ExtendedSocketException
Message :
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Device not configured
Stack Trace :
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 83
   at System.Net.Dns.GetHostByName(String hostName) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 41
   at System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteGetHostByName_EmptyString_ReturnsHostName() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/tests/FunctionalTests/GetHostByNameTest.cs:line 108
```

Dns_GetHostEntryAsync_HostString_Ok
```
Unhandled Exception of Type System.Net.Internals.SocketExceptionFactory+ExtendedSocketException
Message :
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Device not configured
Stack Trace :
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 83
   at System.Net.Dns.ResolveCallback(Object context) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 290
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 420
   at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 562
   at System.Net.Dns.<>c.<GetHostEntryAsync>b__27_1(IAsyncResult asyncResult) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 652
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) in /Users/buildagent/agent/_work/382/s/src/mscorlib/src/System/Threading/Tasks/FutureFactory.cs:line 529
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 49
   at System.Net.NameResolution.Tests.GetHostEntryTest.TestGetHostEntryAsync(Func`1 getHostEntryFunc) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
```

Dns_GetHostEntry_HostString_Ok
```
Unhandled Exception of Type System.Net.Internals.SocketExceptionFactory+ExtendedSocketException
Message :
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Device not configured
Stack Trace :
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 83
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 475
   at System.Net.NameResolution.Tests.GetHostEntryTest.<>c__DisplayClass1_0.<Dns_GetHostEntry_HostString_Ok>b__0() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs:line 26
   at System.Net.NameResolution.Tests.GetHostEntryTest.TestGetHostEntryAsync(Func`1 getHostEntryFunc) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by stephentoub** [comment]
Another case of this:
https://mc.dot.net/#/user/ahsonkhan/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/dbc1fc2da27849acee9a80476a20f86603a36548/workItem/System.Net.NameResolution.Functional.Tests

**Comment by stephentoub** [comment]
@dotnet/dnceng, do you know of anything that may have changed in CI infrastructure recently that would cause DNS-related issues (slowdowns / disconnects / any such thing) recently on macOS in particular?

**Comment by MattGal** [comment]
@stephentoub sort of, earlier this week we had a bunch of machines in the OSX.1012.Amd64.Open queue go weird (just sort of quit python, didn't log anything) and they seemed OK after reboot.  025 (one implicated in this log) looked to be the same.

From the machine logs, we're having trouble sending our telemetry via python networking APIs so it's definitely a machine issue:
```
2018-02-02 07:57:25,247: WARNING: saferequests(70): request_with_retry: Request failed with exception: ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='helixtelemetry.servicebus.windows.net', port=443): Read timed out. (read timeout=10)",),)
2018-02-02 07:57:35,293: WARNING: saferequests(70): request_with_retry: Request failed with exception: ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='helixtelemetry.servicebus.windows.net', port=443): Read timed out. (read timeout=10)",),)
```

I'll first try rebooting 025, please keep adding any incidences of this you see to this thread (or ping me directly) and we can hopefully identify a messed up piece in the network.

**Comment by wfurt** [comment]
Ping me next time this happens @MattGal We may do some more deeper scan.
For example, I find stray donet processes once in a while eating lot of cpu. 
We may also examine open file and system limits.

**Comment by MattGal** [comment]
I can get you on DCI-MAC-BUILD-025 any time you like, I've only disabled it from being used for now (until @JpratherMS  or someone reimages it...).

For the network issues, given that this also happened on Windows 8 Azure VMs I'm suspecting there was an EventHub outage that messed things up briefly and exposed a bug (which I am urgently reproing/fixing) in our client python scripts.

**Comment by karelz** [comment]
@rmkerr can you try to re-enable the tests and see if the infra issue is gone? Thanks!
