### ISSUE TITLE
[Regression] [x64 Windows] Test failure: System.Collections.Immutable.Tests.ImmutableListTest / IndexOf & LastIndexOf

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#26821]
## Type of failures

Affected OS: Win7 & Win8.1 & Win10 & Win10.Core & Win10.Nano - only x64 (x86 runs are fine)

```
Assert.Equal() Failure
Expected: 2
Actual:   -1

at System.Collections.Immutable.Tests.IndexOfTests.IndexOfTest[TCollection](Func`2 factory, Func`3 indexOfItem, Func`4 indexOfItemIndex, Func`5 indexOfItemIndexCount, Func`6 indexOfItemIndexCountEQ) in E:\A\_work\484\s\corefx\src\System.Collections.Immutable\tests\IndexOfTests.cs:line 45
at System.Collections.Immutable.Tests.ImmutableListTest.IndexOf() in E:\A\_work\484\s\corefx\src\System.Collections.Immutable\tests\ImmutableListTest.cs:line 505
```

## History of failures

Day | Build | Details
-- | -- | --
2/3 | 20180203.03 | 10x failures - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180203.03/workItem/System.Collections.Immutable.Tests)
2/4 | 20180204.01 | 10x failures - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180204.01/workItem/System.Collections.Immutable.Tests)

**Comment by karelz** [comment]
@safern @ianhays can you please take a look?

**Comment by jkotas** [comment]
This issue was moved to dotnet/coreclr#16202

**Comment by jkotas** [comment]
Looks like a codegen bug.
