### ISSUE TITLE
[ManagedHandler] HTTP Status line contains CR has parsing behavior difference

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#26946]
When ManagedHandler get a Http status line contains CR character, like "HTTP/1.1 200 O\rK", it throws `System.FormatException : The reason phrase must not contain new-line characters`

```
   at System.Net.Http.HttpResponseMessage.set_ReasonPhrase(String value) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\HttpResponseMessage.cs:line 94
   at System.Net.Http.HttpConnection.ParseStatusLine(Span`1 line, HttpResponseMessage response) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\Managed\HttpConnection.cs:line 586
   at System.Net.Http.HttpConnection.ParseStatusLine(ArraySegment`1 line, HttpResponseMessage response) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\Managed\HttpConnection.cs:line 533
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\Managed\HttpConnection.cs:line 473
   at System.Net.Http.HttpConnectionPool.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\Managed\HttpConnectionPool.cs:line 176
   at System.Net.Http.CookieHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\Managed\CookieHandler.cs:line 31
   at System.Net.Http.AuthenticateAndRedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\Managed\AuthenticateAndRedirectHandler.cs:line 53
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 488
```

On WinHttpHandler and Framework, they throw `HttpRequestException`; on UAP and CurlHandler, no Exception will be thrown.

We should consider match at least one of the above behavior.

**Comment by davidsh** [comment]
>When ManagedHandler get a Http status line contains CR character, like "HTTP/1.1 200 O\rK", it throws System.FormatException : The reason phrase must not contain new-line characters

I the only bug here is that ManagedHandler is not wrapping this exception into a top-level HttpRequestException.  Currently, ManagedHandler is throwing a FormatException directly as the top-level exception.  And that breaks the expected behavior of HttpClient APIs where normally runtime errors surface as top-level HttpRequestException's.
