### ISSUE TITLE
System.Console fails with ncurses 6.1

### ISSUE THREAD

**Issue by kasper3** [dotnet/corefx#26966]
Released on Jan 27, 2018 - Announcement https://www.gnu.org/software/ncurses/

Original report: https://bugs.archlinux.org/task/57260

```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.InvalidOperationException: The terminfo database is invalid.
at System.TermInfo.Database..ctor(String term, Byte[] data)
at System.TermInfo.Database.ReadDatabase(String term, String directoryPath)
at System.TermInfo.Database.ReadDatabase(String term)
at System.TermInfo.Database.ReadActiveDatabase()
at System.ConsolePal.TerminalFormatStrings.<>c.<.cctor>b__27_0()
at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
at System.Lazy`1.CreateValue()
at System.ConsolePal.EnsureInitializedCore()
at System.ConsolePal.ControlCHandlerRegistrar.Register()
at System.Console.add_CancelKeyPress(ConsoleCancelEventHandler value)
at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine) in E:\A\_work\17\s\src\MSBuild\XMake.cs:line 526

Unhandled Exception: System.InvalidOperationException: The terminfo database is invalid.
at System.TermInfo.Database..ctor(String term, Byte[] data)
at System.TermInfo.Database.ReadDatabase(String term, String directoryPath)
at System.TermInfo.Database.ReadDatabase(String term)
at System.TermInfo.Database.ReadActiveDatabase()
at System.ConsolePal.TerminalFormatStrings.<>c.<.cctor>b__27_0()
at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
at System.Lazy`1.CreateValue()
at System.ConsolePal.EnsureInitializedCore()
at System.ConsolePal.ControlCHandlerRegistrar.Register()
at System.Console.add_CancelKeyPress(ConsoleCancelEventHandler value)
at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine) in E:\A\_work\17\s\src\MSBuild\XMake.cs:line 748
at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args) in E:\A\_work\17\s\src\MSBuild\XMake.cs:line 215
```

**Comment by stephentoub** [comment]
Based on following the discussion in the link and browsing from there, it looks like System.Console will need a change similar to https://github.com/hankem/S-Lang/commit/6dd5ade9a97b52ace4ac033779a6d3c1c51db4d1 in order to support the format additions.

cc: @joperezr, @ianhays

**Comment by joshfree** [comment]
@joperezr @stephentoub could one of you pick this up?  @ianhays has his hands full with linux distro stuff for a while

**Comment by danmosemsft** [comment]
Is there likely to be broad uptake of this ncurses update? If so we may need to fix this promptly, and service for it also.

**Comment by kasper3** [comment]
Related to https://github.com/mono/mono/issues/6752, maybe joining forces would help?

**Comment by stephentoub** [comment]
We should fix this in the existing code, but then also take another look at changing System.Console to p/invoke into the curses lib.

**Comment by wfurt** [comment]
Would you do that for every console operation - like changing colors and cursor moves @stephentoub ? That would also fix #24259  
Some packages - like busybox - may have very small set build and and fallback to "dumb" terminal for everything else. It may be better to loose color than failing fatally.

**Comment by stephentoub** [comment]
> Would you do that for every console operation

That would be the ideal, so we could stop parsing this terminfo stuff ourselves, as it's apparently an implementation detail that's free to change whenever.

If we can't, then getting off it to whatever extent is possible is probably a good thing.

But worst case, we should at least fix this known issue.

**Comment by kasper3** [comment]
Is it going to be `icushim`, `opensslshim` and other kinds of shims in corefx and coreclr? i.e. even build machine had ncurses lib available, at runtime it will load (dlopen/dlclose) the lib if available (`runtime if condition`), if not, treat as TERM=="dumb" (node.js example -> https://github.com/nodejs/node/blob/e5f101fe7beba0/lib/internal/repl.js#L37-L42).

**Comment by joperezr** [comment]
Taking a look...

**Comment by kasper3** [comment]
@joperezr, the original poster is @redni, who raised this issue at: https://github.com/dotnet/sdk/issues/1916. Do you have ncurses 6.1 on Unix?

` dpkg -l '*ncurses*' | grep '^ii'`
or
`rpm -qa | grep ncurse`

to print the version.

**Comment by SebastianPfliegel** [comment]
@joperezr, I also had this issue. I can confirm, that I had ncurses 6.1 and was able to reproduce the error with several 2.* releases of the sdk.

**Comment by wfurt** [comment]
What is your base OS @SebastianPfliegel ? Did you simply run msbuild or do you have different repro?

**Comment by SebastianPfliegel** [comment]
@wfurt, see dotnet/cli#8576. Exception gets thrown with `dotnet run` and `dotnet restore` (though `dotnet new ...` runs fine).

**Comment by wfurt** [comment]
oh Tumbleweed -> building sand castle in swamp. I could only find Leap 42.x images on Azure. 
I'll try to upgrade tomorrow and get repro.

**Comment by SebastianPfliegel** [comment]
I wasn't able to reproduce it on a tumbleweed docker machine. Even though it also runs ncurses 6.1.

**Comment by lewurm** [comment]
@SebastianPfliegel what is your `$TERM` set to? It needs to point to some configuration where the terminfo file is using the new file format, e.g. `screen-256color`.

**Comment by stephentoub** [comment]
Could someone experiencing the issue attach a copy of the problematic terminfo file?  While folks are working on getting a repro on a machine, that would make it a lot easier I think for someone to quickly code up a fix.

Assuming "screen-256color" is in the new format, it would likely be at one of these locations:
/etc/terminfo/s/screen-256color
/lib/terminfo/s/screen-256color
/usr/share/terminfo/s/screen-256color

**Comment by SebastianPfliegel** [comment]
@stephentoub, @lewurm: I'll give you an update in a couple of hours.

**Comment by lewurm** [comment]
[copy of `screen-256color` and `xterm`](https://gist.github.com/lewurm/448c6b5506d8adb427513ad260515560)  from a system with the following version of ncurses installed:
```
$ pacman -Q | grep ncurses
ncurses 6.1-3
```

quick look with a hex editor:
```$ xxd screen-256color| head -n 1
00000000: 1e02 2b00 2b00 0f00 6901 0403 7363 7265  ..+.+...i...scre

$ xxd xterm| head -n 1
00000000: 1a01 3000 2600 0f00 9d01 b805 7874 6572  ..0.&.......xter
```

`0x02e1` and `0x011a` (little endian) correspond with the magic values defined in ncurses. Specifically, this is the relevant commit: https://github.com/mirror/ncurses/commit/1501ae2a13db0ffd2db8404c24aa5010a88ea91b#diff-2c0786db969084ba9e087d82f8275e0b

**Comment by stephentoub** [comment]
Thanks, @lewurm!

**Comment by b0wter** [comment]
@lewurm 
I am running Tumbleweed on my laptop with ncurses 6.1-1.1 and dotnet 2.1.4.
Tried several terminals:

- Kitty: $TERM = xterm-kitty, runs "refresh" and "run" fine
- Terminator: $TERM = xterm-256color, crashes on "restore" and "run"
- xterm: $TERM = xterm, runs fine
- xfce4-terminal: $TERM = xterm-256color, crashes on "restore" and "run"

**Comment by SebastianPfliegel** [comment]
$TERM is xterm-256color for me.

**Comment by rainerklier** [comment]
I am running Tumbleweed on my laptop and with ncurses 6.1 and dotnet 2.1.4 powershell  6.0.1 fails to run/start with the error message "The terminfo database is invalid."
dotnet 2.1.4 and powershell 6.0.1 are both installed from repo https://packages.microsoft.com/rhel/7/prod/

**Comment by welkie** [comment]
I'm experiencing this issue too. I installed a fresh dotnet-sdk package (Arch Linux) and at that point I could no longer run builds for ASP.NET Core in VS Code. My `$TERM` is `xterm-256color`.

**Comment by lewurm** [comment]
@welkie as a workaround this should work:

```sh
$ TERM=xterm dotnet build
```

**Comment by welkie** [comment]
I can confirm that workaround works to build over the command line. However, I can't find a way to integrate that into Visual Studio Code. I tried both adding the environment variable `"TERM": "xterm"` to the build task, and launching the editor with the environment variable (`TERM=xterm code`) but it still produced that error message. This means I can't build and ctrl-click on the errors to properly fix them.

I'd like the follow the GitHub issue for this so that I know when I can continue using VS Code for ASP.NET Core. Is this is the issue it will be tracked in?

**Comment by joperezr** [comment]
That workaround will work, but we are working on adding support for ncurses 6.1 on Console so that this workaround isn't required. I have a PR up right (#27109) now which we will merge as soon as I fix one last issue I'm seeing and we will then merge that change into release branch so that it makes it to the 2.1 release.

**Comment by welkie** [comment]
Awesome. :) Thanks for your work on this.

**Comment by jogleasonjr** [comment]
@welkie I noted a workaround for Visual Studio Code [here](https://github.com/Microsoft/vscode/issues/43539#issuecomment-369651904). That may work for you as well.

**Comment by Meai1** [comment]
none of the workarounds worked for me, I had to write an extra script with the same name called 'dotnet' and the contents are: 

`#!/bin/sh

TERM=xterm
set -m
exec -a mydotnet /home/pc/software/dotnet/dotnet $1 $2 `

Then make sure only this script is on the PATH, *not* the real dotnet executable so that vscode can only call this script. The exec line replaces the process in place so that everything keeps working properly even in debug.

**Comment by kasper3** [comment]
Backport pull requests are in progress:

https://github.com/dotnet/corefx/pull/27614 - v2.0.0
https://github.com/dotnet/corefx/pull/27632 - v1.1.0
https://github.com/dotnet/corefx/pull/27634 - v1.0.0

@joperezr, when it will be backported to 2.0, 1.1 and 1.0 branches, how it will be shipped? Would there be a minor/patch version update and we will have to wait for a release that will be announced on .NET Blog at some point. Or do the releases after backport immediately available for consumption? Not asking for ETA etc. but trying to understand usually on what grounds team decides to release the next minor/patch version?

**Comment by jogleasonjr** [comment]
@Meai1 have you tried this in your `tasks.json`:


    "tasks": [
     {
        "label": "build",
        "command": "dotnet build",
        "linux": {
            "command": "env TERM=rxvt-unicode-256color dotnet build"
        },
       ...
      }
    ]


Of course substitute your term of choice. If that doesn't work, you could try putting in a bogus command such as `"command": "fo0bar720"` to make sure everything is set up right in vscode tasks and your build breaks as expected.

**Comment by TheForgetTime** [comment]
You can download old versions of ncurses from https://archive.archlinux.org/repos/2018/02/17/core/os/x86_64/ and then use pacman -U to roll back this one (note: this may cause serious consequences)

**Comment by danmosemsft** [comment]
> @joperezr, when it will be backported to 2.0, 1.1 and 1.0 branches, how it will be shipped? Would there be a minor/patch version update and we will have to wait for a release that will be announced on .NET Blog at some point.

There will be a patch version update which we will announce on the blog. In general we are servicing at roughly monthly intervals: these would not be in this month's, but potentially next month.

**Comment by himejisyana** [comment]
none of the workarounds worked for me, I had to write an extra script with the same name called dotnet and the contents are:

```
#!/bin/sh

TERM=xterm
set -m
exec -a mydotnet /home/pc/software/dotnet/dotnet $1 $2
```

Then make sure only this script is on the PATH, not the real dotnet executable so that vscode can only call this script. The exec line replaces the process in place so that everything keeps working properly even in debug.

**Comment by welkie** [comment]
Yeah, it is crazy how much this bug affects .NET Core on Linux. I ended up giving up on using Linux for it and just use Windows for now. But I don't know if that's going to be an option for me in the future, so I'm hoping something like this doesn't happen again.

**Comment by kasper3** [comment]
>  so I'm hoping something like this doesn't happen again

It sounds to me like dotnet package in AUR repository should require max supported version specified for ncurses and other native dependencies so the package manager informs the user that "hey, updating ncurses will break such and such dependent packages". The way dependency handling stuff usually works in distro packages.

**Comment by jogleasonjr** [comment]
@himejisyana are you building from the integrated terminal in VSCode, or using the debugger? If the former, you can just set `TERM=xterm` once in the integrated terminal. If the latter, what you're doing is possible in `tasks.json`. See what I wrote above for an example of that. 

In both case you wouldn't need to hijack your PATH or the dotnet executable.

Side note - if you use `xterm-256color` in place of `xterm`, you'll get colored output for warnings and errors in the integrated terminal.

**Comment by welkie** [comment]
> It sounds to me like dotnet package in AUR repository should require max supported version specified for ncurses and other native dependencies so the package manager could inform the user that "hey, updating ncurses will break such and such dependent packages". The way dependency handling stuff usually works in distro packages and elsewhere.

That's very true. I should make it clear that I don't expect the maintainers of these packages to foresee how the various distros will use them. The onus is on me to handle my own software installs. I chose to use a rolling distro without fully understanding the ramifications of that.

**Comment by welkie** [comment]
@kasper3 I just realized what you meant by your comment after revisiting this issue. The dotnet-sdk package has actually made it's way into Arch's official repos now (community), it no longer lives in the AUR. The package's dependency list makes no mention of ncurses at all. Do you think adding it to the dependency lost would help this situation? If so, should we be proposing the Arch package maintainer to do this?

**Comment by kasper3** [comment]
@welkie, I believe so. The next patch version of 2.0 will be released few days from now with the fix (17th April perhaps?). After that the package can require ncurses 6.1 as a run-time dependency (as opposed to build-time). Whenever ncurses 6.2 is released, and if we have breakage in dotnet with it, dotnet package on Arch will continue to work as ncurses 6.1 will be installed as part of dotnet package installation.

**Comment by kasper3** [comment]
@welkie, or maybe 2.0.x next patch is coming up with with more crucial bug fixes along with this one, which the package mantainers across the distros should just update mid-arpil anyway for multiple reasons..

**Comment by welkie** [comment]
@kasper3 That's what I was referring to I think. I don't know much about creating and maintaining packages for distros, so I may not know the terminology 100%, but I'm just suggesting that the next release our particular distro has (which you say will be a patch release soon), they should explicitly list the ncurses dependency.

**Comment by kasper3** [comment]
>  In general we are servicing at roughly monthly intervals: these would not be in this month's, but potentially not too long.

@danmosemsft, frankly based on the impact of this issue, this should had been prioritized and shipped by now (the merge in release/2.0 branch happened 31 days ago) and folks are still waiting and opening duplicate issues all over the place.

**Comment by ShalokShalom** [comment]
One more case, where a global AppImage/Linuxbrew is the solution.

**Comment by SebastianPfliegel** [comment]
Few hours ago 2.1.0 Preview2 was released. I can confirm that the fix works :+1:

**Comment by welkie** [comment]
`2.1.300-preview2-008530` confirmed working on Antergos. Able to build without changing `XTERM` etc.

**Comment by kasper3** [comment]
v2.0.7 is out https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0.7.md with the fix for .Net Core 2.0. We can release Arch Linux package. @welkie, do you know who maintains the package?

**Comment by instalab** [comment]
Here is PKGBUILD for people in need.
https://raw.githubusercontent.com/instalab/DotNetArch/master/PKGBUILD

**Comment by instalab** [comment]
And here is PKGBUILD of dotnet-runtime, for people in need:
https://raw.githubusercontent.com/instalab/DotNetCoreArch/master/PKGBUILD

**Comment by kasper3** [comment]
@instalab, could you please send your patches to upstream https://wiki.archlinux.org/index.php/git? cc @alucryd

**Comment by kasper3** [comment]
Gentoo package updated with 2.0.7 https://github.com/gentoo/dotnet/pull/389

**Comment by welkie** [comment]
@instalab Those worked great for me, thank you! I've finally got my VS Code dev environment working again. No more switching into Windows. :penguin:

**Comment by welkie** [comment]
@instalab Was wondering if you could help me with those PKGBUILD files. They worked on one of my PCs but not the other. On the problem PC, I can install the dotnet-sdk but not the dotnet-runtime. I get the following message:

```
==> Starting package_dotnet-host()...
install: missing file operand
Try 'install --help' for more information.
==> ERROR: A failure occurred in package_dotnet-host().
    Aborting...
```

Do you think waiting for the package to be updated in Arch's package manager would be better?

**Comment by codywd** [comment]
I'm on Arch Linux, with dotnet-sdk-2.1.105-1, and dotnet-runtime-2.0.7-1. This issue is still occuring for me, is a later version the one with the fix? I installed this from AUR using https://aur.archlinux.org/packages/powershell/, and I modified the pkgbuild to remove TERM=xterm before build.sh

**Comment by Dargmuesli** [comment]
I guess you need to wait for the runtime 2.1 release within the next two months.

**Comment by kasper3** [comment]
> next two months

I thought it's supposed to be released in next two days?

But anyways, https://www.archlinux.org/packages/community/any/dotnet-sdk/ has the updated 2.0 now. @codywd, do you get this issue in powershell only or any project?

before:

```sh
dotnet new console --name someApp
dotnet build -p someApp
```

was failing with

> MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
> System.InvalidOperationException: The terminfo database is invalid.

if that is working now, then PowerShell is somehow picking up old SDK. Otherwise, it is it still failing then something is wrong with package update. This was confirmed to be fixed in Arch and other distros previously. But please test a lil bit more to figure out the rootcause.

**Comment by codywd** [comment]
@kasper3 When using the -p command, it tells me to specify a property and it's value. I simply dropped the -p, and it seems to build correctly. I'll follow up with the PowerShell git. Thanks!

**Comment by Dargmuesli** [comment]
>> I thought it's supposed to be released in next two days?

That would be great. Afaik the release schedule said Q2 2018, but maybe I confuse something here.

**Comment by codywd** [comment]
@Dargmuesli Is there a PKGBUILD ready for the preview?

**Comment by Dargmuesli** [comment]
See @instalab's comment above. I don't have a working PKGBUILD right now, I'll just wait ;)

**Comment by codywd** [comment]
@Dargmuesli Unfortunately, building Powershell-Git fails with the following error:
"/opt/dotnet/sdk/2.1.300-preview2-008530/Roslyn/Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code 131. [/home/XXX/.cache/yay/powershell-git/src/powershell/src/ResGen/ResGen.csproj]


These are the PKGBUILDS I made (modifying @instalab's):
dotnet-runtime: https://gist.github.com/codywd/745b6861848c4dafec996de0432bddfd
dotnet-sdk: https://gist.github.com/codywd/c0c7dd458704f3f79b3efb5cdd94c24e

Then ran the following PKGBUILD: https://aur.archlinux.org/packages/powershell-git/ (And I removed TERM=xterm from the build() block)

Finally tried running the following PKGBUILD for powershell (6.0.2): https://aur.archlinux.org/packages/powershell (Removing TERM=xterm from build() block again) with the same error

**Comment by kasper3** [comment]
my mistake; `-p` is a shorthand for `--project` option on `dotnet-run` command.

**Comment by codywd** [comment]
@kasper3 With that info, `dotnet run -p someApp` sucessfully returns `Hello World`

Seems to be something with PowerShell for sure.

**Comment by fedeantuna** [comment]
for those wanting to use F5 on Visual Studio Code and not being able to, as a workaround I solved it adding "TERM=xterm" in the "args" section of the task.json:
"tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "TERM=xterm",
                "build",
                "${workspaceFolder}/src/Georgica.Web.Main/Georgica.Web.Main.csproj"
            ],
            "problemMatcher": "$msCompile"
        }
    ]

**Comment by FaithLV** [comment]
Getting this error while trying to execute [config.sh from VSTS agent setup guide](https://gist.github.com/FaithLV/82e7f70f3b91a92cef5168cad0bac761) on Arch. 

Full stacktrace [here](https://gist.github.com/FaithLV/8d6d39efad01e1561972f90075c1af4a).
Running `dotnet --version` shows that I'm running `2.1.302`.
