### ISSUE TITLE
ServiceBase tests failing on NETFX

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#27027]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20180210.03/workItem/System.ServiceProcess.ServiceController.Tests/wilogs

```
2018-02-10 14:06:57,283: INFO: proc(54): run_and_log_output: Output:       System.ServiceProcess.TimeoutException : Time out has expired and the operation has not been completed.
2018-02-10 14:06:57,283: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-10 14:06:57,283: INFO: proc(54): run_and_log_output: Output:            at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
2018-02-10 14:06:57,283: INFO: proc(54): run_and_log_output: Output:            at System.ServiceProcess.Tests.TestServiceInstaller.RemoveService()
2018-02-10 14:06:57,283: INFO: proc(54): run_and_log_output: Output:            at System.ServiceProcess.Tests.TestServiceProvider.DeleteTestServices()
2018-02-10 14:06:57,283: INFO: proc(54): run_and_log_output: Output:            at System.ServiceProcess.Tests.TestServiceProvider.DeleteTestServices()
2018-02-10 14:06:57,283: INFO: proc(54): run_and_log_output: Output:            at System.ServiceProcess.Tests.ServiceBaseTests.Dispose()
2018-02-10 14:06:57,283: INFO: proc(54): run_and_log_output: Output:         C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs(76,0): at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)

```

**Comment by Anipik** [comment]
ServiceBase Tests are fixed for both .netCore and .netDesktop. so closing this issue
