### ISSUE TITLE
Test failure: MaxConnectionsPerServer_WaitingConnectionsAreCancelable

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#27064]
The MaxConnectionsPerServer_WaitingConnectionsAreCancelable test fails on WinHttpHandler in a strange manner.  It throws a "The server returned an invalid or unrecognized response" WinHttpException while receiving/parsing the response headers. This happens while handling the response from the first request, but doesn't happen if the last request is removed.  It almost as if there's some state that bleeds between the requests.

**Comment by danmosemsft** [comment]
Perhaps the failure below is the same issue.

```
OSX.1013.Amd64.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type System.Exception
Message :
System.Exception : Unexpected EOF trying to read request header
Stack Trace :
   at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAsync() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 378
   at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAndSendResponseAsync(HttpStatusCode statusCode, String additionalHeaders, String content) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 395
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass14_0.<<AcceptConnectionSendResponseAndCloseAsync>b__0>d.MoveNext() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 117
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionSendResponseAndCloseAsync(HttpStatusCode statusCode, String additionalHeaders, String content) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 142
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 64
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 92
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.<>c__DisplayClass5_0.<<MaxConnectionsPerServer_WaitingConnectionsAreCancelable>b__0>d.MoveNext() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 345
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 67
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.MaxConnectionsPerServer_WaitingConnectionsAreCancelable() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 313
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by ViktorHofer** [comment]
Happening again: https://mc.dot.net/#/user/ViktorHofer/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/cbcd432a8a1683a6e01bb0c51beb8570f121b860/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Cancellation_Test~2FMaxConnectionsPerServer_WaitingConnectionsAreCancelable

**Comment by davidsh** [comment]
Tracking against #32000 which disabled the test for now.
