### ISSUE TITLE
ServiceProcess test failures, including PauseAndContinue 

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#27071]
This has failed the last three builds (2/11 - 2/12) - [MC test results link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180212.05/workItem/System.ServiceProcess.ServiceController.Tests/analysis/xunit/System.ServiceProcess.Tests.ServiceControllerTests~2FPauseAndContinue)

The test `System.ServiceProcess.Tests.ServiceControllerTests/PauseAndContinue` has failed.

System.ComponentModel.Win32Exception : Could not find service 

        Stack Trace:

           at System.ServiceProcess.Tests.TestServiceInstaller.DeleteService() in E:\A\_work\1424\s\corefx\src\System.ServiceProcess.ServiceController\tests\System.ServiceProcess.ServiceController.TestService\TestServiceInstaller.cs:line 186
       at System.ServiceProcess.Tests.TestServiceInstaller.RemoveService() in E:\A\_work\1424\s\corefx\src\System.ServiceProcess.ServiceController\tests\System.ServiceProcess.ServiceController.TestService\TestServiceInstaller.cs:line 133
       at System.ServiceProcess.Tests.TestServiceProvider.DeleteTestServices() in E:\A\_work\1424\s\corefx\src\System.ServiceProcess.ServiceController\tests\TestServiceProvider.cs:line 139
       at System.ServiceProcess.Tests.TestServiceProvider.DeleteTestServices() in E:\A\_work\1424\s\corefx\src\System.ServiceProcess.ServiceController\tests\TestServiceProvider.cs:line 149
       at System.ServiceProcess.Tests.ServiceControllerTests.Dispose() in E:\A\_work\1424\s\corefx\src\System.ServiceProcess.ServiceController\tests\ServiceControllerTests.cs:line 184
       at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 76
Build : Master - 20180212.05 (Core Tests)
Failing configurations:
- Windows.10.Amd64-x64
  - Release

**Comment by danmosemsft** [comment]
Yeah investigating...

**Comment by joshfree** [comment]
Since 2/11 this has failed 11 times out of the last 20 runs on Win10.

[link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180220.07/workItem/System.ServiceProcess.ServiceController.Tests/analysis/xunit/System.ServiceProcess.Tests.ServiceControllerTests~2FPauseAndContinue)



```

Unhandled Exception of Type System.ServiceProcess.TimeoutException
Message :
System.ServiceProcess.TimeoutException : Time out has expired and the operation has not been completed.

   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout) in E:\A\_work\13\s\corefx\src\System.ServiceProcess.ServiceController\src\System\ServiceProcess\ServiceController.cs:line 923
   at System.ServiceProcess.Tests.TestServiceInstaller.StopService() in E:\A\_work\13\s\corefx\src\System.ServiceProcess.ServiceController\tests\System.ServiceProcess.ServiceController.TestService\TestServiceInstaller.cs:line 151
   at System.ServiceProcess.Tests.TestServiceInstaller.RemoveService() in E:\A\_work\13\s\corefx\src\System.ServiceProcess.ServiceController\tests\System.ServiceProcess.ServiceController.TestService\TestServiceInstaller.cs:line 133
   at System.ServiceProcess.Tests.TestServiceProvider.DeleteTestServices() in E:\A\_work\13\s\corefx\src\System.ServiceProcess.ServiceController\tests\TestServiceProvider.cs:line 139
   at System.ServiceProcess.Tests.ServiceControllerTests.Dispose() in E:\A\_work\13\s\corefx\src\System.ServiceProcess.ServiceController\tests\ServiceControllerTests.cs:line 184
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 76
```

**Comment by danmosemsft** [comment]
Not fixed. And not always this test.
