### ISSUE TITLE
The RSA implementation fails to encrypt an empty byte array

### ISSUE THREAD

**Issue by atanasa** [dotnet/corefx#27120]
- Steps to reproduce: run the following code on **Windows 10 or Mac OS X on .Net Core 2.0**:
```C#
          var key = RSA.Create();
          var encrypted = key.Encrypt(new byte[0], RSAEncryptionPadding.Pkcs1);
```
- Expected result:
A byte array that would be decrypted to an empty byte array.

- Actual result:
Exception on Windows 10:
```
Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException
  HResult=0x80090027
  Message=The parameter is incorrect
  Source=System.Security.Cryptography.Algorithms
  StackTrace:
   at System.Security.Cryptography.RSAImplementation.RSACng.EncryptOrDecrypt(SafeNCryptKeyHandle key, Byte[] input, AsymmetricPaddingMode paddingMode, Void* paddingInfo, EncryptOrDecryptAction encryptOrDecrypt)
   at System.Security.Cryptography.RSAImplementation.RSACng.EncryptOrDecrypt(Byte[] data, RSAEncryptionPadding padding, EncryptOrDecryptAction encryptOrDecrypt)
   at System.Security.Cryptography.RSAImplementation.RSACng.Encrypt(Byte[] data, RSAEncryptionPadding padding)
   at ConsoleApp3.Program.Main(String[] args)
```

On Mac OS X the exception is:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Runtime.InteropServices.Marshal.CopyToManaged(IntPtr source, Object destination, Int32 startIndex, Int32 length)
   at Interop.CoreFoundation.CFGetData(SafeCFDataHandle cfData)
   at Interop.AppleCrypto.ExecuteTransform(SecKeyTransform transform)
   at Interop.AppleCrypto.RsaEncrypt(SafeSecKeyRefHandle publicKey, Byte[] data, RSAEncryptionPadding padding)
   at System.Security.Cryptography.RSAImplementation.RSASecurityTransforms.Encrypt(Byte[] data, RSAEncryptionPadding padding)
   at ConsoleApp3.Program.Main(String[] args)
```

**Running the same code on .Net Framework 4.6.1 and on Core on Ubuntu returns the expected result.**

**Comment by bartonjs** [comment]
Strangely, I ran across this today, too.

In .NET Framework RSA is provided by Windows Cryptographic API (CAPI).  On .NET Core it's provided by Windows Cryptography: Next Generation (CNG), and it looks like CNG rejects the zero byte input.

But maybe something can be done about it.
