### ISSUE TITLE
Unable to create Bitmap from disk file on Linux

### ISSUE THREAD

**Issue by tudorserbanconnatix** [dotnet/corefx#27121]
Hi, I'm referencing CoreCompat.System.Drawing.v2 from a .NET Core project and doing the following:

Bitmap frame = new Bitmap($"{Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)}\\images\\image_0.bmp")

I've checked that the path is correct at runtime. On Windows this works fine, but on Debian I am getting:

Unable to update the static FcBlanks: 0x0600
Unable to update the static FcBlanks: 0x0601
Unable to update the static FcBlanks: 0x0602
Unable to update the static FcBlanks: 0x0603
Unable to update the static FcBlanks: 0x06dd
Unable to update the static FcBlanks: 0x070f
Unable to update the static FcBlanks: 0x2028
Unable to update the static FcBlanks: 0x2029
Unable to update the static FcBlanks: 0xfff9
Unable to update the static FcBlanks: 0xfffa
Unable to update the static FcBlanks: 0xfffb

Unhandled Exception: System.ArgumentException: A null reference or invalid value was found [GDI+ status: InvalidParameter]
at System.Drawing.GDIPlus.CheckStatus(Status status)
at System.Drawing.Bitmap..ctor(String filename, Boolean useIcm)
at TestVideoConvert.TestVideoConvert.Create() in /home/osboxes/Downloads/Test2/TestVideoConvert/TestVideoConvert.cs:line 44
at ImageResizeNetCore.Program.Main(String[] args) in /home/osboxes/Downloads/Test2/ImageResizeNetCore/Program.cs:line 15

I've installed libgdiplus, but no luck.

Using System.Drawing.Common gives the following error:

Unhandled Exception: System.ArgumentException: Parameter is not valid.
at System.Drawing.Bitmap..ctor(String filename, Boolean useIcm)
at TestVideoConvert.TestVideoConvert.Create() in /home/osboxes/Downloads/Test2/TestVideoConvert/TestVideoConvert.cs:line 44
at ImageResizeNetCore.Program.Main(String[] args) in /home/osboxes/Downloads/Test2/ImageResizeNetCore/Program.cs:line 15

I've read somewhere that this could be due to the image size being too large, but in my case it's a 1920x1080 bmp so not out of the ordinary.

Here is a sample image to repro the issue: https://wallpaperscraft.com/image/stars_sky_shore_84534_1920x1080.jpg

**Comment by danmosemsft** [comment]
cc @qmfrederik

**Comment by tudorserbanconnatix** [comment]
I'm such an idiot. I switched to using ImageSharp and it immediately revealed the problem: path not found, because I'm using Windows forward slashes '\\' instead of '/'.
