### ISSUE TITLE
Four failures in new System.Threading.Timer tests in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2717]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release/946/console
```
TimerFiringTests.Timer_CanDisposeSelfInCallback [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Threading.Timer\tests\TimerFiringTests.cs(126,0): at TimerFiringTests.Timer_CanDisposeSelfInCallback()
     TimerFiringTests.NonRepeatingTimer_ThatHasAlreadyFired_CanChangeAndFireAgain [FAIL]
        Should have received a second timer event after changing it
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Threading.Timer\tests\TimerFiringTests.cs(150,0): at TimerFiringTests.NonRepeatingTimer_ThatHasAlreadyFired_CanChangeAndFireAgain()
     TimerFiringTests.Running_Timer_CanBeFinalizedAndStopsFiring [FAIL]
        Failed to get first timer fire
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Threading.Timer\tests\TimerFiringTests.cs(160,0): at TimerFiringTests.Running_Timer_CanBeFinalizedAndStopsFiring()
     TimerFiringTests.MultpleTimers_PeriodicTimerIsntBlockedByABlockedTimer [FAIL]
        Blocking callback prevented a second timer from firing
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Threading.Timer\tests\TimerFiringTests.cs(184,0): at TimerFiringTests.MultpleTimers_PeriodicTimerIsntBlockedByABlockedTimer()
  
  Unhandled Exception: Xunit.Sdk.TrueException: Should have received a second callback while blocked
  Expected: True
  Actual:   False
     at Xunit.Assert.True(Nullable`1 condition, String userMessage)
     at TimerFiringTests.<>c__DisplayClass22.<MultpleTimers_PeriodicTimerIsntBlockedByABlockedTimer>b__20(Object o)
     at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.TimerQueueTimer.CallCallback()
     at System.Threading.TimerQueueTimer.Fire()
     at System.Threading.TimerQueue.FireNextTimers()
     at System.Threading.TimerQueue.AppDomainTimerCallback()
  Finished:    System.Threading.Timer.Tests
```

**Comment by stephentoub** [comment]
These just failed here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/2941/console 
```
TimerFiringTests.Timer_CanDisposeSelfInCallback [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Threading.Timer\tests\TimerFiringTests.cs(126,0): at TimerFiringTests.Timer_CanDisposeSelfInCallback()
     TimerFiringTests.NonRepeatingTimer_ThatHasAlreadyFired_CanChangeAndFireAgain [FAIL]
        Should have received a second timer event after changing it
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Threading.Timer\tests\TimerFiringTests.cs(150,0): at TimerFiringTests.NonRepeatingTimer_ThatHasAlreadyFired_CanChangeAndFireAgain()
```

**Comment by sokket** [comment]
Weird...the CI passed for my PR and locally. Will take a look

**Comment by stephentoub** [comment]
Any test that depends on timing is going to be subject to random failures... that's why we try hard not to have any such tests, and when we do, to make the timing such that it's very unlikely the test will randomly fail.

**Comment by sokket** [comment]
Yeah, I'm guessing my timeout values are too specific. I'll adjust them and put out a PR

**Comment by stephentoub** [comment]
Just FYI, another occurrence:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release/953/console
```
TimerFiringTests.NonRepeatingTimer_ThatHasAlreadyFired_CanChangeAndFireAgain [FAIL]
        Should have received a second timer event after changing it
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Threading.Timer\tests\TimerFiringTests.cs(150,0): at TimerFiringTests.NonRepeatingTimer_ThatHasAlreadyFired_CanChangeAndFireAgain()
```

**Comment by stephentoub** [comment]
And again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/2960/console
```
TimerFiringTests.NonRepeatingTimer_ThatHasAlreadyFired_CanChangeAndFireAgain [FAIL]
        Should have received first timer event
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Threading.Timer\tests\TimerFiringTests.cs(147,0): at TimerFiringTests.NonRepeatingTimer_ThatHasAlreadyFired_CanChangeAndFireAgain()
```
