### ISSUE TITLE
NullReferenceException in SNITCPHandle.Send

### ISSUE THREAD

**Issue by domisterwoozy** [dotnet/corefx#27177]
While attempting to write to a table using a table valued parameters with MARS on I am getting a `NullReferenceException` and the following stack trace.

```	
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.SqlClient.SNI.SNITCPHandle.Send(SNIPacket packet)
   at System.Data.SqlClient.SNI.SNIMarsConnection.Send(SNIPacket packet)
   at System.Data.SqlClient.SNI.SNIMarsHandle.SendControlPacket(SNISMUXFlags flags)
   at System.Data.SqlClient.SNI.SNIMarsHandle.Dispose()
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.Dispose()
   at System.Data.SqlClient.TdsParserSessionPool.PutSession(TdsParserStateObject session)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<ExecuteImplAsync>d__37.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 646
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Company.Integration.<Persist>d__3.MoveNext() in /app/src/Company.Integration/.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Company.Services.<>c__DisplayClass6_0.<<Persist>b__0>d.MoveNext() in /app/src/Company.Calculation/Services/PayrollRunner.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNetHelpers.Metrics.Instrumentation.<>c__DisplayClass8_0.<<Time>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNetHelpers.Metrics.Instrumentation.<Time>d__10`1.MoveNext()
```

I am on running dotnet-runtime-2.0.5-linux-x64.

**Comment by saurabh500** [comment]
@domisterwoozy What is the version of SqlClient that you are using? 
Can you post a repro application?

**Comment by AfsanehR** [comment]
Hello @domisterwoozy. I wasn't able to repro the issue. Please see the attached file for a sample application that I ran with tvp and MARS enabled. 
https://gist.github.com/AfsanehR/a841749664520918035f6f42c5869351

If you can post a repro, it would be useful to better investigate the issue you are facing.

**Comment by saurabh500** [comment]
Moving to Future as there is not enough actionable information available. @domisterwoozy a repro would really help us tackle the issue.

**Comment by danielearwicker** [comment]
Since upgrading to 2.1 I've started getting this, also using TVPs, via `ExecuteSqlCommand` to do inserts and updates. I've noticed it when our system is under fairly large load e.g. when making 20 of these calls at the same time, and a successful call takes 20 secs (updates a lot of records in one hit), and often the other calls are either also throwing this `NullReferenceException` or else they're throwing timeout.

So I guess this happens when you're recovering from another exception by unwinding the stack, and disposing something that isn't in an expected state?

Stack trace comes at the problem from a slightly different route:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.SqlClient.SNI.SNITCPHandle.Send(SNIPacket packet)
   at System.Data.SqlClient.SNI.SNIMarsConnection.Send(SNIPacket packet)
   at System.Data.SqlClient.SNI.SNIMarsHandle.SendControlPacket(SNISMUXFlags flags)
   at System.Data.SqlClient.SNI.SNIMarsHandle.Dispose()
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.Dispose()
   at System.Data.SqlClient.TdsParserSessionPool.PutSession(TdsParserStateObject session)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters)
```

**Comment by AfsanehR** [comment]
Do you also have the MARS ON in your setting? Would you be able to give us a repro, that would help us track down issue easier.

**Comment by zentron** [comment]
I have hit the same issue with `2.2.101` running on ubuntu (WSL). I will try and put together a simple repro and report back.

```
Error Message:
 System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
   at System.Data.SqlClient.SNI.SNITCPHandle.Send(SNIPacket packet)
   at System.Data.SqlClient.SNI.SNIMarsConnection.Send(SNIPacket packet)
   at System.Data.SqlClient.SNI.SNIMarsHandle.SendControlPacket(SNISMUXFlags flags)
   at System.Data.SqlClient.SNI.SNIMarsHandle.Dispose()
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.Dispose()
   at System.Data.SqlClient.TdsParserSessionPool.PutSession(TdsParserStateObject session)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
```

**Comment by Spaceman1861** [comment]
I have also hit the same issue.
Don't have much to add tho.

I'm running dotnetcore 2.1.5

`System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.SqlClient.SNI.SNITCPHandle.Send(SNIPacket packet)
   at System.Data.SqlClient.SNI.SNIMarsConnection.Send(SNIPacket packet)
   at System.Data.SqlClient.SNI.SNIMarsHandle.SendControlPacket(SNISMUXFlags flags)
   at System.Data.SqlClient.SNI.SNIMarsHandle.Dispose()
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.Dispose()
   at System.Data.SqlClient.TdsParserSessionPool.PutSession(TdsParserStateObject session)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
`

**Comment by iwanttodie** [comment]
It frequently reporducalbe with MARS enabled and high rate of concurrent queris.

We are using latest images from
`microsoft/dotnet:2.2-runtime-deps-alpine`
and 
`microsoft/dotnet:2.1-runtime-deps-alpine`

We are runing them on CentOS, and trying to conntect to AWS RDS instance, if it somehow helpful.

Object reference not set to an instance of an object.
--
at System.Data.SqlClient.SNI.SNITCPHandle.Send(SNIPacket packet)    at System.Data.SqlClient.SNI.SNIMarsConnection.Send(SNIPacket packet)    at System.Data.SqlClient.SNI.SNIMarsHandle.SendControlPacket(SNISMUXFlags flags)    at System.Data.SqlClient.SNI.SNIMarsHandle.Dispose()    at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.Dispose()    at System.Data.SqlClient.TdsParserSessionPool.PutSession(TdsParserStateObject session)    at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()

**Comment by AfsanehR** [comment]
@iwanttodie  @Spaceman1861 @zentron if the issue is occurring often, do you think you can manage to provide a repro? This would help us with investigating the issue :) Thanks!
