### ISSUE TITLE
[Regresion] Test Failure: System.Net.WebSockets.Client.Tests.CancelTest / CloseAsync_Cancel_Success

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#27211]
[System.Net.WebSockets.Client.Tests.CancelTest/CloseAsync_Cancel_Success(server: ws://corefx-net.cloudapp.net/WebSocket/EchoWebSocket.ashx)](https://mc.dot.net/#/user/caesar1995/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/8345c5e744278e6274af556e5bfd3957d7ab7a41/workItem/System.Net.WebSockets.Client.Tests/analysis/xunit/System.Net.WebSockets.Client.Tests.CancelTest~2FCloseAsync_Cancel_Success(server:%20ws:~2F~2Fcorefx-net.cloudapp.net~2FWebSocket~2FEchoWebSocket.ashx))

```
Assert.Equal() Failure
              ↓ (pos 4)
Expected: The 'System.Net.WebSockets.InternalClientWebS···
Actual:   The remote party closed the WebSocket connect···
              ↑ (pos 4)
```

```
at System.Net.WebSockets.Client.Tests.ClientWebSocketTestBase.TestCancellation(Func`2 action, Uri server) in D:\j\workspace\windows-TGrou---6368dffa\src\System.Net.WebSockets.Client\tests\ClientWebSocketTestBase.cs:line 81
   at System.Net.WebSockets.Client.Tests.CancelTest.CloseAsync_Cancel_Success(Uri server) in D:\j\workspace\windows-TGrou---6368dffa\src\System.Net.WebSockets.Client\tests\CancelTest.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
```

Consistent repro on Windows.

Different from: #22904

## Failure history

Build | OS
-- | --
20180214.01 | 2x OSX10.12 & 2x OSX10.13
20180214.02 | 4x Win10 & 2x Win7 & 2x OSX10.12 & 2x OSX10.13
20180215.01 | 10x Win10 & 4x Win8.1 & 2x OSX10.12 & 2x OSX10.13
20180215.04 | 10x Win10 & 2x Win8.1 & 4x Win7 & 2x OSX10.12 & 2x OSX10.13
20180216.01 | 5x Win10 & Win8.1 & OSX10.12 & OSX10.13
20180216.03 | 4x Win10 & 2x Win7 & Win8.1 & OSX10.12 & OSX10.13

**Comment by caesar1995** [comment]
I disable the test because I saw consistent failure in CI.

> Should we look deeper into them for 2.1?

I'll take a look.

**Comment by caesar1995** [comment]
Have run the test 500 times locally, no failure. The test didn't fail in CI in my test PR #28481.

The test is that, a ClientWebSocket connects to a external server, send some data, then close the connection. We expect client side initiates the close or transfers into the invalid state first (since we explicitly calls `cws.CloseAsync`); however, we get the "remote party close the WebSocket connection" (server closes the connection). 

Don't understand root cause yet, probably some network race condition. Since a remote server is used, and no failure before 20180214, likely a external server problem. Will enable the test.
