### ISSUE TITLE
Test Failure: System.Net.Http.Functional.Tests.HttpClientHandlerTest/GetAsync_AllowAutoRedirectTrue_RetainsOriginalFragmentIfAppropriate "Unhandled Exception"

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#27217]
[System.Net.Http.Functional.Tests.HttpClientHandlerTest/GetAsync_AllowAutoRedirectTrue_RetainsOriginalFragmentIfAppropriate(origFragment: \"#origFragment\", redirFragment: \"\", expectedFragment: \"#origFragment\", useRelati)](https://mc.dot.net/#/user/caesar1995/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/c4522d10d10a1b622b3f2b0cf919ede239e636a6/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandlerTest~2FGetAsync_AllowAutoRedirectTrue_RetainsOriginalFragmentIfAppropriate(origFragment:%20%5C%22%23origFragment%5C%22,%20redirFragment:%20%5C%22%5C%22,%20expectedFragment:%20%5C%22%23origFragment%5C%22,%20useRelati))

Unhandled Exception of Type System.Net.Http.HttpRequestException
Message :
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response
```

Stack Trace
```
at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in D:\j\workspace\windows-TGrou---6368dffa\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 488
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass60_1.<<GetAsync_AllowAutoRedirectTrue_RetainsOriginalFragmentIfAppropriate>b__0>d.MoveNext() in D:\j\workspace\windows-TGrou---6368dffa\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 891
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in D:\j\workspace\windows-TGrou---6368dffa\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 64
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_AllowAutoRedirectTrue_RetainsOriginalFragmentIfAppropriate(String origFragment, String redirFragment, String expectedFragment, Boolean useRelativeRedirect) in D:\j\workspace\windows-TGrou---6368dffa\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 876
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in D:\j\workspace\windows-TGrou---6368dffa\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs:line 62
   at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state) in D:\j\workspace\windows-TGrou---6368dffa\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 863
```

**Comment by davidsh** [comment]
This test is using the loopback server.  So, this is not a problem with Azure connectivity to remote test endpoints.  How often does this test failure occur?

**Comment by caesar1995** [comment]
> How often does this test failure occur?

This issue is the first failure report after disabling it against Win7 (#16272).

Seems it's fixed in #27360.

**Comment by karelz** [comment]
The test was disabled in #27181

**Comment by karelz** [comment]
And it was re-enabled in #27360. Closing.
