### ISSUE TITLE
Issue connecting to MS SQL Server running on non default port 1433

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#27307]
@mahesji commented on [Fri Feb 09 2018](https://github.com/dotnet/core/issues/1264)

# Issue Title

Issue connecting to MS SQL Server running on non default port 1433 from Linux environment 

**OS Version**
Linux 4.4.0-109-generic #132~14.04.1-Ubuntu SMP Tue Jan 9 21:46:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

dotnet core project settings 
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.5</RuntimeFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
    <PackageReference Include="System.Data.SqlClient" Version="4.4.2" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
  </ItemGroup>

</Project>

```
# General
Using System.Data.SqlClient to connect to Sql server database. Following the sample in this post https://blogs.msdn.microsoft.com/dotnet/2016/11/09/net-core-data-access/

It works fine if the sql server is listening on port 1433 but fails when connecting to sql servers listening on port 1434. Confirmed that there is no network / firewall issues that that is blocking the ports. Able to connect to the same sql server on port 1434 using java code.
This connection string works >
Server=myhostname,1433;Database=mydatabase;User Id=myuser;Password=mypassword;
This connection string does not work in above linux environment.  Works fine on windows
Server=myhostname,1434;Database=mydatabase;User Id=myuser;Password=mypassword;

Both connect strings work fine in Windows environment.

Record Fetch Error: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)

---

@usergiga commented on [Fri Feb 09 2018](https://github.com/dotnet/core/issues/1264#issuecomment-364605423)

If an instance of SQL Server is listening on any other port, than 1433. You have to specify a server-alias or change the standard port globally. 
You can have SQL Server listening on multiple ports. 

---

@mahesji commented on [Mon Feb 12 2018](https://github.com/dotnet/core/issues/1264#issuecomment-364967845)

@usergiga , Thank you for the reply.  I have the alias created and that doesn't seem to help. The connection works fine in Windows runtime.  Have this issue only in the Linux (Ubuntu) runtime.

**Comment by saurabh500** [comment]
@mahesji have you confirmed that the TCP connectivity from Linux to the port is working fine? 
Also have you tried specifying the IP address of the server instead of the host name in the connection string. 
To find out if the TCP port on the Windows server can be connected to, from linux or not, use
`nc -vz hostname port` (assuming you have netcat installed on the linux host)

**Comment by mahesji** [comment]
@saurabh500 I am able to connect to the same database using JDBC from the linux machine. So I am confident it is not related to network connectivity / security.

**Comment by saurabh500** [comment]
@mahesji 
There have been scenarios where IP address being specified allows connectivity where we have sometimes seen issues with hostname resolution in SqlClient. Can you try using the IP address instead of the hostname?

**Comment by saurabh500** [comment]
Also you have mentioned that you cannot connect on non-default port. Does this mean that from the same linux host you can reach a Sql Server on the same server host on 1433 using SqlClient ?

**Comment by saurabh500** [comment]
@mahesji IN case the IP address connectivity doesn't work can you clone https://github.com/saurabh500/sqlclientnetworkutils and execute the code using `dotnet run hostname port` on the linux machine so that we can have a better idea of where the connectivity is breaking?

**Comment by mahesji** [comment]
@saurabh500 Find below the output, (IP address masked)
Resolving DNS addresses
IP Addresses resolved
xxx.xx.xxx.xxx
2002:bb37:b3ef::bb37:b3ef
Connecting to xxx.xx.xxx.xxx on port 1434
Connecting to 2002:bb37:b3ef::bb37:b3ef on port 1434
Received Last Operation Connect for xxx.xx.xxx.xxx:1434

To your earlier questions
Not able to connect using IP address as well. 
I have a different sqlserver db running on a separate windows server on 1433 and it works fine.

**Comment by saurabh500** [comment]
@mahesji Thanks for the information.
I tested out an application which tries to connect to sql server on a Windows OS running on port 1437 and another on port 1434. 
I also tried connecting to Sql Server on port 1433 by explicitly specifying the port 1433 in the connection string `server,1433` to see if the parsing logic for port has any issues, but the connection passed. 

I further changed Sql Server network config to bind to only IPv4 address. All these configurations for connectivity are working with SqlClient v 4.4.2 and I haven't faced any issues with SqlClient. 

Also do you have the complete exception stack trace? 

At this point, I believe that it is something specific to your environment and .Net Core. I don't quite know what it is right now. 

There are a few ways this can be taken forth.
1. Setup a network packet capture on the client machine to send over for an analysis. This is a bit of an intrusive step, but we can try it only if you are comfortable. You could send the data on the MS email address mentioned on my Github profile.

2. Try changing the port of the Sql Server to 1433 on the Sql Server to see if that works for you.

**Comment by mahesji** [comment]
@saurabh500 just to confirm. Do you use Windows client or Linux client ? 
The issue is only with Linux.  The same program runs fine in Windows.

**Comment by saurabh500** [comment]
Linux client with Sql server on Windows

**Comment by saurabh500** [comment]
@mahesji 
```Record Fetch Error: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)

```

What did the rest of stack trace look like?

**Comment by akasparas** [comment]
Had similar situation yesterday. Found following facts:
1) when SQL server runs several SQL services on the same host, it **stops listening** on tcp/1433 port
2) if no port is specified in connection string in the form "server,port" SqlClient tries to connect only on port 1433 and connection fails;
3) if connection string is of the form "server/service", sql management studio and other clients first sends packet to **udp/1434** and get tcp port on which that service runs, then tries to connect to that port
4) SqlClient class does not send packet to **udp/1434**; it does not have any mention of udp in source, instead in some situation it tries to connect to **tcp/1434**.

Therefore if you run sql service on non-standard port, specify connection string in the format "server,port".

**Comment by arthurvaverko** [comment]
hi, im running on the default port 1433.
when i execute a simple query against the DB all works well.
but when i try to run a stored procedure .. like this:

```
using (SqlConnection con = new SqlConnection(sConn))
            {
                try
                {
                    con.Open();
                    SetLockTimeOut(con);
                    command.Connection = con;

                    SqlQueryInfo queryInfo = Utils.GetSqlDataMonitor(command);
                    using (KMonitor km = new KMonitor(KLogMonitor.Events.eEvent.EVENT_DATABASE, null, null, null, null) { Database = queryInfo.Database, QueryType = queryInfo.QueryType, Table = queryInfo.Table, IsWritable = (m_bIsWritable || Utils.UseWritable).ToString() })
                    {
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            if (reader.HasRows)
                            {
                                result = new DataTable();
                                result.Load(reader);
                            }
                        }
                    }

                    con.Close();
                }
                catch (Exception ex)
                {
                    string sMes = "While running : '" + procedureNameWithDbVersionPrefix + "'\r\n Exception occurred: " + ex.Message;
                    log.Error(sMes, ex);
                    return null;
                }
            }
```
im getting this exception only on linux system. running on windows all works well..
actually event running inside a linux based docker on windows all works well .. :\

```
ERROR 2019-04-23 06:49:53,933 (33) class:ODBCWrapper.StoredProcedure topic:null method:UpdateBulkUpload server:c931619e64e0 ip:null reqid:35a07e86-933a-4f0c-93ec-3428e4d92687 partner:203 action:null uid:770357 msg:While running : '__522v0__UpdateBulkUpload'
 Exception occurred: A transport-level error has occurred when sending the request to the server. (provider: TCP Provider, error: 35 - An internal exception was caught)
System.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when sending the request to the server. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.IO.IOException: Unable to write data to the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Data.SqlClient.SNI.SNITCPHandle.Send(SNIPacket packet)
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.SNIWritePacket(Object packet, UInt32& sniError, Boolean canAccumulate, Boolean callerHasConnectionLock)
   at System.Data.SqlClient.TdsParserStateObject.WriteSni(Boolean canAccumulate)
   at System.Data.SqlClient.TdsParserStateObject.WritePacket(Byte flushMode, Boolean canAccumulate)
   at System.Data.SqlClient.TdsParserStateObject.ExecuteFlush()
   at System.Data.SqlClient.TdsParser.TdsExecuteRPC(_SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteReader()
   at ODBCWrapper.StoredProcedure.Execute(Boolean shouldGoToSlave) in /src/Core/ODBCWrapper/StoredProcedure.cs:line 130

```
