### ISSUE TITLE
AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection test failed on Windows

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#27363]
https://mc.dot.net/#/user/ahsonkhan/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/e0a26daab80419c10a37646444d5155d5495d241/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandlerTest~2FAllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection(statusCode:%20307,%20oldMethod:%20%5C%22POST%5C%22,%20newMethod:%20%5C%22POST%5C%22,%20useTE:%20False)

```text
System.Net.Http.HttpRequestException : Error while copying content to a stream.
---- System.IO.IOException : The write operation failed, see inner exception.
-------- System.Net.Http.WinHttpException : The connection with the server was terminated abnormally
```

```text
   at System.Net.Http.HttpContent.CopyToAsyncCore(Task copyTask) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\HttpContent.cs:line 351
   at System.Net.Http.WinHttpHandler.InternalSendRequestBodyAsync(WinHttpRequestState state, Boolean chunkedModeForSend) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 1361
   at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 860
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 488
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass51_2.<<AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection>b__1>d.MoveNext() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 654
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in D:\j\workspace\windows-TGrou---74aa877a\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 66
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass51_1.<<AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection>b__0>d.MoveNext() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 628
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in D:\j\workspace\windows-TGrou---74aa877a\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 66
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection(Int32 statusCode, String oldMethod, String newMethod, Boolean useTE) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 612
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.HttpContent.CopyToAsyncCore(Task copyTask) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\HttpContent.cs:line 347
----- Inner Stack Trace -----
   at System.Environment.get_StackTrace() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\src\System\Environment.cs:line 146
   at System.Runtime.ExceptionServices.ExceptionStackTrace.AddCurrentStack(Exception exception) in D:\j\workspace\windows-TGrou---74aa877a\src\Common\src\System\Runtime\ExceptionServices\ExceptionStackTrace.cs:line 23
   at System.Net.Http.WinHttpException.CreateExceptionUsingError(Int32 error) in D:\j\workspace\windows-TGrou---74aa877a\src\Common\src\System\Net\Http\WinHttpException.cs:line 56
   at System.Net.Http.WinHttpRequestCallback.OnRequestError(WinHttpRequestState state, WINHTTP_ASYNC_RESULT asyncResult) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs:line 324
   at System.Net.Http.WinHttpRequestCallback.RequestCallback(IntPtr handle, WinHttpRequestState state, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs:line 104
   at System.Net.Http.WinHttpRequestCallback.WinHttpCallback(IntPtr handle, IntPtr context, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs:line 47
   at Interop.WinHttp.WinHttpWriteData(SafeWinHttpHandle requestHandle, IntPtr buffer, UInt32 bufferSize, IntPtr parameterIgnoredAndShouldBeNullForAsync)
   at Interop.WinHttp.WinHttpWriteData(SafeWinHttpHandle requestHandle, IntPtr buffer, UInt32 bufferSize, IntPtr parameterIgnoredAndShouldBeNullForAsync)
   at System.Net.Http.WinHttpRequestStream.InternalWriteDataAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestStream.cs:line 245
   at System.Net.Http.WinHttpRequestStream.InternalWriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestStream.cs:line 203
   at System.Net.Http.WinHttpRequestStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestStream.cs:line 131
   at System.Net.Http.HttpContent.CopyToAsync(Stream stream, TransportContext context, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\HttpContent.cs:line 327
   at System.Net.Http.HttpContent.CopyToAsync(Stream stream, TransportContext context) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\HttpContent.cs:line 310
   at System.Net.Http.WinHttpHandler.InternalSendRequestBodyAsync(WinHttpRequestState state, Boolean chunkedModeForSend) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 1361
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in E:\A\_work\1994\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 922
   at System.Net.Http.WinHttpHandler.InternalSendRequestBodyAsync(WinHttpRequestState state, Boolean chunkedModeForSend)
   at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 860
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\1994\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs:line 166
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in E:\A\_work\1994\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 546
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\1994\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs:line 166
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) in E:\A\_work\1994\s\src\mscorlib\src\System\Threading\Tasks\Task.cs:line 2440
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in E:\A\_work\1994\s\src\mscorlib\src\System\Threading\ThreadPool.cs:line 588
--- End of stack trace from AddCurrentStack ---
```

**Comment by stephentoub** [comment]
Failed again here:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/c8c00b2c5d4aadb4f4d075e26a8762804fd09bc2/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandlerTest~2FAllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection(statusCode:%20301,%20oldMethod:%20%5C%22POST%5C%22,%20newMethod:%20%5C%22GET%5C%22,%20useTE:%20False)
```
Unhandled Exception of Type Xunit.Sdk.FalseException
Message :
Faulted: System.AggregateException: One or more errors occurred. (Error while copying content to a stream.) ---> System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The write operation failed, see inner exception. ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.CopyToAsyncCore(Task copyTask) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http\\src\\System\\Net\\Http\\HttpContent.cs:line 347
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.CopyToAsyncCore(Task copyTask) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http\\src\\System\\Net\\Http\\HttpContent.cs:line 351
   at System.Net.Http.WinHttpHandler.InternalSendRequestBodyAsync(WinHttpRequestState state, Boolean chunkedModeForSend) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http.WinHttpHandler\\src\\System\\Net\\Http\\WinHttpHandler.cs:line 1361
   at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http.WinHttpHandler\\src\\System\\Net\\Http\\WinHttpHandler.cs:line 860
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http\\src\\System\\Net\\Http\\HttpClient.cs:line 488
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The write operation failed, see inner exception. ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.CopyToAsyncCore(Task copyTask) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http\\src\\System\\Net\\Http\\HttpContent.cs:line 347
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.CopyToAsyncCore(Task copyTask) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http\\src\\System\\Net\\Http\\HttpContent.cs:line 351
   at System.Net.Http.WinHttpHandler.InternalSendRequestBodyAsync(WinHttpRequestState state, Boolean chunkedModeForSend) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http.WinHttpHandler\\src\\System\\Net\\Http\\WinHttpHandler.cs:line 1361
   at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http.WinHttpHandler\\src\\System\\Net\\Http\\WinHttpHandler.cs:line 860
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http\\src\\System\\Net\\Http\\HttpClient.cs:line 488<---

Expected: False
Actual:   True
Stack Trace :
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass51_2.<<AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection>b__1>d.MoveNext() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 640
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 66
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass51_1.<<AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection>b__0>d.MoveNext() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 628
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 66
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection(Int32 statusCode, String oldMethod, String newMethod, Boolean useTE) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 612
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by stephentoub** [comment]
@geoffkizer, it looks like this test has now failed several times since it was modified in https://github.com/dotnet/corefx/pull/27266.  Mind taking a look?

**Comment by geoffkizer** [comment]
My best guess is that the Connection: close I added is confusing things.

**Comment by geoffkizer** [comment]
Unfortunately it's not trivial to just take out the Connection: close logic.

I'm tempted to just revert the test additions I made, and file a separate issue to improve the tests.  That's probably the best way to make this reliable again in the short term.

**Comment by geoffkizer** [comment]
Let me try something simple that might fix it.  If not, I'll need to do something more involved.

**Comment by stephentoub** [comment]
Just for reference, failed again here: https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/201009d077e71fcadbc44ddad6995a9b7fc37d7a/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandlerTest~2FAllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection(statusCode:%20301,%20oldMethod:%20%5C%22POST%5C%22,%20newMethod:%20%5C%22GET%5C%22,%20useTE:%20False)

> Let me try something simple that might fix it. If not, I'll need to do something more involved.

Thanks.

**Comment by ahsonkhan** [comment]
We still see test failures:
System.Net.Http.Functional.Tests.HttpClientHandlerTest/AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection(statusCode: 301, oldMethod: \"POST\", newMethod: \"GET\", useTE: False)

https://mc.dot.net/#/user/RemiBou/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/d7680bb69055ec516af57860125fc44b89576e31/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandlerTest~2FAllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection(statusCode:%20301,%20oldMethod:%20%5C%22POST%5C%22,%20newMethod:%20%5C%22GET%5C%22,%20useTE:%20False)

Windows.81.Amd64.Open-Release-x86
```text
Faulted: System.AggregateException: One or more errors occurred. (Error while copying content to a stream.) ---> System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The write operation failed, see inner exception. ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.CopyToAsyncCore(Task copyTask) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http\\src\\System\\Net\\Http\\HttpContent.cs:line 347
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.CopyToAsyncCore(Task copyTask) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http\\src\\System\\Net\\Http\\HttpContent.cs:line 351
   at System.Net.Http.WinHttpHandler.InternalSendRequestBodyAsync(WinHttpRequestState state, Boolean chunkedModeForSend) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http.WinHttpHandler\\src\\System\\Net\\Http\\WinHttpHandler.cs:line 1361
   at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http.WinHttpHandler\\src\\System\\Net\\Http\\WinHttpHandler.cs:line 860
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http\\src\\System\\Net\\Http\\HttpClient.cs:line 469
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The write operation failed, see inner exception. ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.CopyToAsyncCore(Task copyTask) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http\\src\\System\\Net\\Http\\HttpContent.cs:line 347
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.CopyToAsyncCore(Task copyTask) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http\\src\\System\\Net\\Http\\HttpContent.cs:line 351
   at System.Net.Http.WinHttpHandler.InternalSendRequestBodyAsync(WinHttpRequestState state, Boolean chunkedModeForSend) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http.WinHttpHandler\\src\\System\\Net\\Http\\WinHttpHandler.cs:line 1361
   at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http.WinHttpHandler\\src\\System\\Net\\Http\\WinHttpHandler.cs:line 860
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in D:\\j\\workspace\\windows-TGrou---f8ac6754\\src\\System.Net.Http\\src\\System\\Net\\Http\\HttpClient.cs:line 469<---

Expected: False
Actual:   True
```

**Comment by geoffkizer** [comment]
Yeah, I'll need to dig into this in more detail.

I think for now I'll just back out the test change.
