### ISSUE TITLE
"TestStartWithUserName forgot to Dispose() the result of RemoteInvoke()"

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#27365]
```
2018-02-22 11:54:49,269: INFO: proc(54): run_and_log_output: Output: Unhandled Exception: Xunit.Sdk.TrueException: A test System.Diagnostics.Process.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb!System.Diagnostics.Tests.ProcessTests.TestStartWithUserName forgot to Dispose() the result of RemoteInvoke()
2018-02-22 11:54:49,269: INFO: proc(54): run_and_log_output: Output: Expected: True
2018-02-22 11:54:49,269: INFO: proc(54): run_and_log_output: Output: Actual:   False
2018-02-22 11:54:49,269: INFO: proc(54): run_and_log_output: Output:    at Xunit.Assert.True(Nullable`1 condition, String userMessage)
2018-02-22 11:54:49,270: INFO: proc(54): run_and_log_output: Output:    at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose(Boolean disposing) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 212
2018-02-22 11:54:49,271: INFO: proc(54): run_and_log_output: Output:    at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Finalize() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 258
```
cc: @danmosemsft, @maryamariyan

**Comment by stephentoub** [comment]
Lots of similar failures here:
https://mc.dot.net/#/user/bartonjs/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/481f6f62c7f54058bd8e5d25ab175d3b77f711ea/workItem/System.Diagnostics.Process.Tests/wilogs
e.g.
```
2018-02-22 16:30:05,588: INFO: proc(54): run_and_log_output: Output: Unhandled Exception: Xunit.Sdk.TrueException: A test System.Diagnostics.Process.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb!System.Diagnostics.Tests.ProcessTests.TestStartWithUserName forgot to Dispose() the result of RemoteInvoke()
2018-02-22 16:30:05,588: INFO: proc(54): run_and_log_output: Output: Expected: True
2018-02-22 16:30:05,588: INFO: proc(54): run_and_log_output: Output: Actual:   False
2018-02-22 16:30:05,589: INFO: proc(54): run_and_log_output: Output:    at Xunit.Assert.True(Nullable`1 condition, String userMessage)
2018-02-22 16:30:05,590: INFO: proc(54): run_and_log_output: Output:    at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose(Boolean disposing) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 212
2018-02-22 16:30:05,590: INFO: proc(54): run_and_log_output: Output:    at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Finalize() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 258
2018-02-22 16:30:06,143: INFO: proc(54): run_and_log_output: Output: /home/helixbot/dotnetbuild/work/e8585d9d-2db1-4361-9bb9-0fdcc3167640/Work/1acc3dd0-ce54-4d79-90f8-9d7fbd467d3a/Unzip/RunTests.sh: line 94: 18090 Aborted                 (core dumped) $RUNTIME_PATH/dotnet xunit.console.netcore.exe System.Diagnostics.Process.Tests.dll -xml testResults.xml -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests -notrait category=failing
2018-02-22 16:30:06,196: INFO: proc(54): run_and_log_output: Output: Dumpling has not been installed yet. Please run "DumplingHelper.py install_dumpling" before collect_dumps.
2018-02-22 16:30:06,201: INFO: proc(54): run_and_log_output: Output: ~/dotnetbuild/work/e8585d9d-2db1-4361-9bb9-0fdcc3167640/Work/1acc3dd0-ce54-4d79-90f8-9d7fbd467d3a/Unzip
```
and
```
2018-02-22 16:28:21,790: INFO: proc(54): run_and_log_output: Output: Unhandled Exception: Xunit.Sdk.TrueException: A test System.Diagnostics.Process.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb!System.Diagnostics.Tests.ProcessTests.TestStartWithUserName forgot to Dispose() the result of RemoteInvoke()
2018-02-22 16:28:21,790: INFO: proc(54): run_and_log_output: Output: Expected: True
2018-02-22 16:28:21,790: INFO: proc(54): run_and_log_output: Output: Actual:   False
2018-02-22 16:28:21,790: INFO: proc(54): run_and_log_output: Output:    at Xunit.Assert.True(Nullable`1 condition, String userMessage)
2018-02-22 16:28:21,791: INFO: proc(54): run_and_log_output: Output:    at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose(Boolean disposing) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 212
2018-02-22 16:28:21,791: INFO: proc(54): run_and_log_output: Output:    at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Finalize() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 258
2018-02-22 16:28:23,886: INFO: proc(54): run_and_log_output: Output: /home/helixbot/dotnetbuild/work/48cd4795-99d7-43da-b0e5-24427b50d2db/Work/b5b8738a-2405-42e2-bc00-c41bbfe46a90/Unzip/RunTests.sh: line 94: 35054 Aborted                 (core dumped) $RUNTIME_PATH/dotnet xunit.console.netcore.exe System.Diagnostics.Process.Tests.dll -xml testResults.xml -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests -notrait category=failing
2018-02-22 16:28:23,946: INFO: proc(54): run_and_log_output: Output: Dumpling has not been installed yet. Please run "DumplingHelper.py install_dumpling" before collect_dumps.
2018-02-22 16:28:23,950: INFO: proc(54): run_and_log_output: Output: ~/dotnetbuild/work/48cd4795-99d7-43da-b0e5-24427b50d2db/Work/b5b8738a-2405-42e2-bc00-c41bbfe46a90/Unzip
```
etc.

**Comment by maryamariyan** [comment]
Closing this issue as of the submission of PR #27415
