### ISSUE TITLE
"EnvironmentTests+<>c.<FailFast_ExpectFailureExitCode>b__21_0 forgot to Dispose() the result of RemoteInvoke()"

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#27366]
https://mc.dot.net/#/user/bartonjs/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/481f6f62c7f54058bd8e5d25ab175d3b77f711ea/workItem/System.Runtime.Extensions.Tests/wilogs
```
2018-02-22 16:30:18,821: INFO: proc(54): run_and_log_output: Output: Unhandled Exception: Xunit.Sdk.TrueException: A test System.Runtime.Extensions.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb!System.Tests.EnvironmentTests+<>c.<FailFast_ExpectFailureExitCode>b__21_0 forgot to Dispose() the result of RemoteInvoke()
2018-02-22 16:30:18,821: INFO: proc(54): run_and_log_output: Output: Expected: True
2018-02-22 16:30:18,821: INFO: proc(54): run_and_log_output: Output: Actual:   False
2018-02-22 16:30:18,822: INFO: proc(54): run_and_log_output: Output:    at Xunit.Assert.True(Nullable`1 condition, String userMessage)
2018-02-22 16:30:18,823: INFO: proc(54): run_and_log_output: Output:    at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose(Boolean disposing) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 212
2018-02-22 16:30:18,823: INFO: proc(54): run_and_log_output: Output:    at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Finalize() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 258
2018-02-22 16:30:19,580: INFO: proc(54): run_and_log_output: Output: /home/helixbot/dotnetbuild/work/e8585d9d-2db1-4361-9bb9-0fdcc3167640/Work/3d6117c8-79c6-4d5b-bd1b-2fa612c7ac00/Unzip/RunTests.sh: line 94: 18070 Aborted                 (core dumped) $RUNTIME_PATH/dotnet xunit.console.netcore.exe System.Runtime.Extensions.Tests.dll -xml testResults.xml -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests -notrait category=failing
2018-02-22 16:30:19,728: INFO: proc(54): run_and_log_output: Output: Dumpling has not been installed yet. Please run "DumplingHelper.py install_dumpling" before collect_dumps.
2018-02-22 16:30:19,733: INFO: proc(54): run_and_log_output: Output: ~/dotnetbuild/work/e8585d9d-2db1-4361-9bb9-0fdcc3167640/Work/3d6117c8-79c6-4d5b-bd1b-2fa612c7ac00/Unzip
```
Many of the legs hit the same issue.
cc: @danmosemsft, @maryamariyan

**Comment by danmosemsft** [comment]
Yeah we missed outer loop in CI. My bad for not reminding. @maryamariyan  fixing it right now.

**Comment by danmosemsft** [comment]
the other library hitting it is 
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180222.04/workItem/System.Diagnostics.Process.Tests/wilogs

**Comment by stephentoub** [comment]
> fixing it right now.

Is a fix imminent?  If not, as it's taking out most outerloop runs, can we first disable the failfasting and then revisit?

**Comment by danmosemsft** [comment]
Looks like @maryamariyan had to step out. I'll do this as soon as my build completes.

**Comment by maryamariyan** [comment]
Closing this issue as of the submission of PR #27415
