### ISSUE TITLE
NRE in ManagedDecryptorPal.TryDecrypt

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#27372]
This test is failing on all OSes [mc link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180222.04/workItem/System.Security.Cryptography.Pkcs.Tests/analysis/xunit/System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.DecryptTests~2FDecrypt_512_CekDoesNotDecrypt_FixedValue)

EnvelopedCmsTests.Tests.DecryptTests/Decrypt_512_CekDoesNotDecrypt_FixedValue
```
Unhandled Exception of Type Xunit.Sdk.ThrowsException
Message :
Assert.Throws() Failure
Expected: typeof(System.Security.Cryptography.CryptographicException)
Actual:   typeof(System.NullReferenceException): Object reference not set to an instance of an object.
Stack Trace :
   at Internal.Cryptography.Pal.AnyOS.ManagedPkcsPal.ManagedDecryptorPal.TryDecrypt(RecipientInfo recipientInfo, X509Certificate2 cert, X509Certificate2Collection originatorCerts, X509Certificate2Collection extraStore, Exception& exception) in /Users/buildagent/agent/_work/381/s/corefx/src/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.Decrypt.cs:line 85
   at System.Security.Cryptography.Pkcs.EnvelopedCms.DecryptContent(RecipientInfoCollection recipientInfos, X509Certificate2Collection extraStore) in /Users/buildagent/agent/_work/381/s/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/EnvelopedCms.cs:line 230
   at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.DecryptTests.VerifySimpleDecrypt(Byte[] encodedMessage, CertLoader certLoader, ContentInfo expectedContent) in /Users/buildagent/agent/_work/381/s/corefx/src/System.Security.Cryptography.Pkcs/tests/EnvelopedCms/DecryptTests.cs:line 279
```

**Comment by stephentoub** [comment]
A fix for this was already merged.
https://github.com/dotnet/corefx/pull/27356
cc: @bartonjs
