### ISSUE TITLE
FileSystemWatcher_Changed_PreSeededNestedStructure failed again in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2740]
It's now failed several times today.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/2974/console
```
ChangedTests.FileSystemWatcher_Changed_PreSeededNestedStructure(includeSubdirectories: True) [FAIL]
        Didn't observe a second file change event within 500ms
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.IO.FileSystem.Watcher\tests\Utility\Utility.cs(103,0): at Utility.ExpectEvent(WaitHandle eventOccured, String eventName, Int32 timeout)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.IO.FileSystem.Watcher\tests\FileSystemWatcher.Changed.cs(188,0): at ChangedTests.FileSystemWatcher_Changed_PreSeededNestedStructure(Boolean includeSubdirectories)
```

**Comment by stephentoub** [comment]
Upping the timeouts didn't help; it's still failing to receive the event even with a very long timeout, which implies something else is going awry
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release/964/.
```
hangedTests.FileSystemWatcher_Changed_PreSeededNestedStructure(includeSubdirectories: True) [FAIL]
        Didn't observe a second file change event within 30000ms
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release@2\src\System.IO.FileSystem.Watcher\tests\Utility\Utility.cs(109,0): at Utility.ExpectEvent(WaitHandle eventOccured, String eventName, Int32 timeout)
           d:\j\workspace\dotnet_corefx_windows_release@2\src\System.IO.FileSystem.Watcher\tests\FileSystemWatcher.Changed.cs(188,0): at ChangedTests.FileSystemWatcher_Changed_PreSeededNestedStructure(Boolean includeSubdirectories)
```

**Comment by stephentoub** [comment]
I found the problem; product bug rather than test bug (but this test was the first time we stressed starting and stopping the same FSW, which exposed the problem).  Will submit a PR.
