### ISSUE TITLE
Ambigous error message for SSL validation error.

### ISSUE THREAD

**Issue by TsuyoshiUshio** [dotnet/corefx#27458]
When I use HttpClient, I've encounter the SSL validation error. However, the error message just said that "Security Error" (in Japanese) it is not user friendly message.  I might better if it is "SSL validation error" or something. 

The actual error message is 

```
System.Net.Http.HttpRequestException
  HResult=0x80072F8F
  Message=An error occurred while sending the request.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KubernetesRestSpike.Program.<RunAsync>d__7.MoveNext() in C:\Users\tsushi\Source\Repos\CustomBindingsSample\KubernetesRestSpike\Program.cs:line 42
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KubernetesRestSpike.Program.Main(String[] args) in C:\Users\tsushi\Source\Repos\CustomBindingsSample\KubernetesRestSpike\Program.cs:line 31

Inner Exception 1:
WinHttpException: セキュリティ エラーが発生しました
```

This error is thrown from here. 

https://github.com/dotnet/corefx/blob/7e6396b2bcb4d372b199cfb7b3b13e290c441124/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpRequestCallback.cs#L312-L313

**Comment by davidsh** [comment]
The error message comes directly from the native WinHTTP component.  So, it is not something that can be changed at the .NET layer.

**Comment by davidsh** [comment]
cc: @karelz

**Comment by davidsh** [comment]
@TsuyoshiUshio Please try out .NET Core 2.1 Preview 2 release. It uses a new HTTP stack by default (not WinHTTP).  So, the error message will be different upon getting an SSL error and should be more explanatory.

See:
https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/
