### ISSUE TITLE
HandleProcessCorruptedStateExceptionsTests.ProcessExit_Called test failing on Windows

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#27460]
```
MESSAGE:
Exit code was -1073741819 but it should have been 42
Expected: True
Actual: False
+++++++++++++++++++
STACK TRACE:
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose(Boolean disposing) in D:\j\workspace\x64_checked_w---d7295605\_\fx\src\CoreFx.Private.TestUtilities\src\System\Diagnostics\RemoteExecutorTestBase.cs:line 231
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in D:\j\workspace\x64_checked_w---d7295605\_\fx\src\CoreFx.Private.TestUtilities\src\System\Diagnostics\RemoteExecutorTestBase.cs:line 207
at System.Runtime.ExceptionServices.Tests.HandleProcessCorruptedStateExceptionsTests.ProcessExit_Called() in D:\j\workspace\x64_checked_w---d7295605\_\fx\src\System.Runtime\tests\System\Runtime\ExceptionServices\HandleProcessCorruptedStateExceptions.cs:line 51
```

This failure was masked by #27426

**Comment by danmosemsft** [comment]
AV.
