### ISSUE TITLE
WindowsPrincipalIsInRoleNeg test fails locally

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#27505]
I deterministically get this failure when I run the tests for the repo:
```
  Discovering: System.Security.Principal.Windows.Tests
  Discovered:  System.Security.Principal.Windows.Tests
  Starting:    System.Security.Principal.Windows.Tests
     WindowsPrincipalTests.WindowsPrincipalIsInRoleNeg [FAIL]
        System.ComponentModel.Win32Exception : The trust relationship between this workstation and the primary domain failed
        Stack Trace:
           d:\repos\corefx\src\System.Security.Principal.Windows\src\System\Security\Principal\NTAccount.cs(327,0): at System.Security.Principal.NTAccount.TranslateToSids(IdentityReferenceCollection sourceAccounts, Boolean& someFailed)
           d:\repos\corefx\src\System.Security.Principal.Windows\src\System\Security\Principal\NTAccount.cs(189,0): at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean& someFailed)
           d:\repos\corefx\src\System.Security.Principal.Windows\src\System\Security\Principal\NTAccount.cs(160,0): at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
           d:\repos\corefx\src\System.Security.Principal.Windows\src\System\Security\Principal\WindowsPrincipal.cs(68,0): at System.Security.Principal.WindowsPrincipal.IsInRole(String role)
           d:\repos\corefx\src\System.Security.Principal.Windows\tests\WindowsPrincipalTests.cs(15,0): at WindowsPrincipalTests.WindowsPrincipalIsInRoleNeg()

```

**Comment by joshfree** [comment]
removing `test bug` label as WindowsPrincipal.IsInRole shouldn't be leaking an exception

https://github.com/dotnet/corefx/blob/master/src/System.Security.Principal.Windows/tests/WindowsPrincipalTests.cs#L15

**Comment by bartonjs** [comment]
It seems pretty intentional that it throws in this situation (and matches NetFx).

Though, closing this as dupe of #16511.  (But I was going to look at fixing this this week anyways, if I get the chance)
