### ISSUE TITLE
[Fail] PostAsyncExpect100Continue_FailsAfterContentSendStarted_Throws

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#27519]
Windows.10.Amd64.Open-Release-x86

```
 System.Net.Http.Functional.Tests.HttpRetryProtocolTests/
PostAsyncExpect100Continue_FailsAfterContentSendStarted_Throws
```
```
System.Exception : Unexpected EOF trying to read request header
   at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAsync() in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 350
   at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.<>c__DisplayClass4_3.<<PostAsyncExpect100Continue_FailsAfterContentSendStarted_Throws>b__3>d.MoveNext() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Net.Http\tests\FunctionalTests\HttpRetryProtocolTests.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 117
   at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.<>c__DisplayClass4_0.<<PostAsyncExpect100Continue_FailsAfterContentSendStarted_Throws>b__1>d.MoveNext() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Net.Http\tests\FunctionalTests\HttpRetryProtocolTests.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass11_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 67
   at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.PostAsyncExpect100Continue_FailsAfterContentSendStarted_Throws() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Net.Http\tests\FunctionalTests\HttpRetryProtocolTests.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
```
Seen in https://github.com/dotnet/corefx/pull/27499

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by geoffkizer** [comment]
@stephentoub I don't think this test is valid on WinHttpHandler, since it doesn't support Expect: 100-continue.  My guess is that it's not flushing the request headers in some cases -- it doesn't need to since it doesn't support Expect: 100-continue.

I'll disable unless you have objections.

**Comment by stephentoub** [comment]
> My guess is that it's not flushing the request headers in some cases

Interesting. That makes sense.

No objection.  Please just also delete the comment here:
https://github.com/dotnet/corefx/blob/28799e8af0556efe1b9e5e98b700460951ae9eb2/src/System.Net.Http/tests/FunctionalTests/HttpRetryProtocolTests.cs#L84
