### ISSUE TITLE
[New test] Test failure: System.Net.Http.Functional.Tests.HttpClientHandler_ResponseDrain_Test / * - Unexpected EOF trying to read request header

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#27528]
## Failure type

The test was added on 2/23

```
System.Exception : Unexpected EOF trying to read request header

at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAsync() in E:\A\_work\14\s\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 350
at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAndSendCustomResponseAsync(String response) in E:\A\_work\14\s\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 363
at System.Net.Http.Functional.Tests.HttpClientHandler_ResponseDrain_Test.<>c__DisplayClass3_1.<<GetAsyncWithMaxConnections_DisposeBeforeReadingToEnd_DrainsRequestsAndReusesConnection>b__2>d.MoveNext() in E:\A\_work\14\s\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ResponseDrain.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in E:\A\_work\14\s\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 117
at System.Net.Http.Functional.Tests.HttpClientHandler_ResponseDrain_Test.<>c__DisplayClass3_0.<<GetAsyncWithMaxConnections_DisposeBeforeReadingToEnd_DrainsRequestsAndReusesConnection>b__1>d.MoveNext() in E:\A\_work\14\s\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ResponseDrain.cs:line 163
--- End of stack trace from previous location where exception was thrown ---
at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass11_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in E:\A\_work\14\s\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in E:\A\_work\14\s\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 67
at System.Net.Http.Functional.Tests.HttpClientHandler_ResponseDrain_Test.GetAsyncWithMaxConnections_DisposeBeforeReadingToEnd_DrainsRequestsAndReusesConnection(Int32 totalSize, Int32 readSize, ContentMode mode) in E:\A\_work\14\s\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ResponseDrain.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
```

## Failure history

Day | Build | OS | Details
-- | -- | -- | -- 
2/24 | 20180224.02 | OSX10.13 | GetAsync_DisposeBeforeReadingToEnd_DrainsRequestsAndReusesConnection - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180224.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandler_ResponseDrain_Test~2FGetAsync_DisposeBeforeReadingToEnd_DrainsRequestsAndReusesConnection(mode:%20BytePerChunk))
2/27 | 20180227.01 | Win7 | GetAsyncWithMaxConnections_DisposeBeforeReadingToEnd_DrainsRequestsAndReusesConnection - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180227.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandler_ResponseDrain_Test~2FGetAsyncWithMaxConnections_DisposeBeforeReadingToEnd_DrainsRequestsAndReusesConnection(totalSize:%201000,%20readSize:%20950,%20mode:%20SingleChunk))
2/27 | 20180227.01 | OSX10.13 | GetAsync_DisposeBeforeReadingToEnd_DrainsRequestsAndReusesConnection - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180227.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandler_ResponseDrain_Test~2FGetAsync_DisposeBeforeReadingToEnd_DrainsRequestsAndReusesConnection(mode:%20BytePerChunk))

**Comment by karelz** [comment]
@geoffkizer @stephentoub any idea if it is a test bug or product bug - it happened just once.

**Comment by stephentoub** [comment]
We were guessing at the draining behavior of WINHTTP.  I expect we guessed wrong, i.e. test bug.  Or there's an issue with the loopback server, i.e. test bug.

**Comment by karelz** [comment]
OK, it has more hits btw (3 + going through more results) - top post updated

**Comment by benaadams** [comment]
Another occurrence https://github.com/dotnet/corefx/issues/27519

**Comment by geoffkizer** [comment]
These all seem to happen with WinHttpHandler.

GetAsyncWithMaxConnections_DisposeBeforeReadingToEnd_DrainsRequestsAndReusesConnection was already disabled for WinHttpHandler in Stephen's PR from this morning.

We should probably just disable WinHttpHandler for GetAsync_DisposeBeforeReadingToEnd_DrainsRequestsAndReusesConnection as well.

I'll look at any other instances of this I can find (please add links if you know of any).

**Comment by geoffkizer** [comment]
Actually, the GetAsync_DisposeBeforeReadingToEnd_DrainsRequestsAndReusesConnection issue seems to be on OSX, so it's apparently a CurlHandler issue.
