### ISSUE TITLE
Test failed: System.Net.Tests.HttpListenerResponseTests / CopyFrom_AllValues_ReturnsClone

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#27546]
https://mc.dot.net/#/user/maryamariyan/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/103ec78a5875598ab5c876a9a7520615796dcbf4/workItem/System.Net.HttpListener.Tests/wilogs

```
2018-02-27 06:39:02,321: INFO: proc(54): run_and_log_output: Output:    System.Net.Tests.HttpListenerResponseTests.CopyFrom_AllValues_ReturnsClone [FAIL]
2018-02-27 06:39:02,321: INFO: proc(54): run_and_log_output: Output:       System.BadImageFormatException : Invalid access to memory location. (Exception from HRESULT: 0x800703E6)
2018-02-27 06:39:02,321: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-27 06:39:02,384: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
2018-02-27 06:39:02,384: INFO: proc(54): run_and_log_output: Output:          E:\A\_work\12\s\src\mscorlib\src\System\Runtime\InteropServices\Marshal.cs(1055,0): at System.Runtime.InteropServices.Marshal.FreeHGlobal(IntPtr hglobal)
2018-02-27 06:39:02,384: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---a11f5128\src\System.Net.HttpListener\src\System\Net\Windows\RequestContextBase.cs(57,0): at System.Net.RequestContextBase.Dispose(Boolean disposing)
2018-02-27 06:39:02,384: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---a11f5128\src\System.Net.HttpListener\src\System\Net\Windows\AsyncRequestContext.cs(97,0): at System.Net.AsyncRequestContext.Dispose(Boolean disposing)
2018-02-27 06:39:02,384: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---a11f5128\src\System.Net.HttpListener\src\System\Net\Windows\RequestContextBase.cs(50,0): at System.Net.RequestContextBase.Dispose()
2018-02-27 06:39:02,384: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---a11f5128\src\System.Net.HttpListener\src\System\Net\Windows\RequestContextBase.cs(44,0): at System.Net.RequestContextBase.Close()
2018-02-27 06:39:02,384: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---a11f5128\src\System.Net.HttpListener\src\System\Net\Windows\HttpListenerRequest.Windows.cs(334,0): at System.Net.HttpListenerRequest.Close()
2018-02-27 06:39:02,384: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---a11f5128\src\System.Net.HttpListener\src\System\Net\Windows\HttpListenerContext.Windows.cs(88,0): at System.Net.HttpListenerContext.Close()
2018-02-27 06:39:02,384: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---a11f5128\src\System.Net.HttpListener\src\System\Net\Windows\HttpListenerResponse.Windows.cs(185,0): at System.Net.HttpListenerResponse.Dispose()
2018-02-27 06:39:02,384: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---a11f5128\src\System.Net.HttpListener\src\System\Net\HttpListenerResponse.cs(297,0): at System.Net.HttpListenerResponse.System.IDisposable.Dispose()
2018-02-27 06:39:02,384: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---a11f5128\src\System.Net.HttpListener\tests\HttpListenerResponseTests.cs(96,0): at System.Net.Tests.HttpListenerResponseTests.CopyFrom_AllValues_ReturnsClone()
2018-02-27 06:39:02,384: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2018-02-27 06:39:03,821: INFO: proc(54): run_and_log_output: Output: ----- end  6:39:03.82 ----- exit code -1073741819 ----------------------------------------------------------

```

**Comment by stephentoub** [comment]
Hasn't failed in over a year.  Closing.
