### ISSUE TITLE
Several FileSystem and Path tests failing with latest coreclr

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#27552]
```
2018-02-28 13:24:45,135: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Span(value: \"C:\\\\\\\\\", expected: \"C:\\\\\") [FAIL]
2018-02-28 13:24:45,135: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,135: INFO: proc(54): run_and_log_output: Output:                    ↓ (pos 3)
2018-02-28 13:24:45,135: INFO: proc(54): run_and_log_output: Output:       Expected: C:\
2018-02-28 13:24:45,135: INFO: proc(54): run_and_log_output: Output:       Actual:   C:\\
2018-02-28 13:24:45,135: INFO: proc(54): run_and_log_output: Output:                    ↑ (pos 3)
2018-02-28 13:24:45,135: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.netcoreapp.cs(17,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Span(String value, String expected)
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Span(value: \"C:\\\\\\\\foo2\", expected: \"C:\\\\\") [FAIL]
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:                    ↓ (pos 3)
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:       Expected: C:\
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:       Actual:   C:\\
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:                    ↑ (pos 3)
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.netcoreapp.cs(17,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Span(String value, String expected)
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Span(value: \"\\\\\\\\test\\\\unc\\\\path\\\\to\\\\something\", expected: \"\\\\\\\\test\\\\unc\") [FAIL]
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:                           ↓ (pos 10)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Expected: \\test\unc
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Actual:   \\test\unc\
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:                           ↑ (pos 10)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.netcoreapp.cs(17,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Span(String value, String expected)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Span(value: \"\\\\\\\\a\\\\b\\\\c\\\\d\\\\e\", expected: \"\\\\\\\\a\\\\b\") [FAIL]
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:                      ↓ (pos 5)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Expected: \\a\b
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Actual:   \\a\b\
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:                      ↑ (pos 5)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.netcoreapp.cs(17,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Span(String value, String expected)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Span(value: \"\\\\\\\\a\\\\b\\\\\", expected: \"\\\\\\\\a\\\\b\") [FAIL]
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:                      ↓ (pos 5)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Expected: \\a\b
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Actual:   \\a\b\
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:                      ↑ (pos 5)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.netcoreapp.cs(17,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Span(String value, String expected)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Span(value: \"\\\\\\\\?\\\\UNC\\\\test\\\\unc\\\\path\\\\to\\\\something\", expected: \"\\\\\\\\?\\\\UNC\\\\test\\\\unc\") [FAIL]
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:                                 ↓ (pos 16)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Expected: \\?\UNC\test\unc
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Actual:   \\?\UNC\test\unc\
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:                                 ↑ (pos 16)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.netcoreapp.cs(17,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Span(String value, String expected)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Span(value: \"\\\\\\\\?\\\\UNC\\\\a\\\\b2\\\\\", expected: \"\\\\\\\\?\\\\UNC\\\\a\\\\b2\") [FAIL]
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                             ↓ (pos 12)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Expected: \\?\UNC\a\b2
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Actual:   \\?\UNC\a\b2\
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                             ↑ (pos 12)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.netcoreapp.cs(17,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Span(String value, String expected)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(value: \"\\\\\\\\test\\\\unc\\\\path\\\\to\\\\something\", expected: \"\\\\\\\\test\\\\unc\") [FAIL]
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                           ↓ (pos 10)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Expected: \\test\unc
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Actual:   \\test\unc\
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                           ↑ (pos 10)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.cs(48,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(String value, String expected)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(value: \"\\\\\\\\a\\\\b\\\\c\\\\d\\\\e\", expected: \"\\\\\\\\a\\\\b\") [FAIL]
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                      ↓ (pos 5)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Expected: \\a\b
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Actual:   \\a\b\
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                      ↑ (pos 5)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.cs(48,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(String value, String expected)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(value: \"\\\\\\\\a\\\\b\\\\\", expected: \"\\\\\\\\a\\\\b\") [FAIL]
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                      ↓ (pos 5)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Expected: \\a\b
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Actual:   \\a\b\
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                      ↑ (pos 5)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.cs(48,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(String value, String expected)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(value: \"\\\\\\\\?\\\\UNC\\\\test\\\\unc\\\\path\\\\to\\\\something\", expected: \"\\\\\\\\?\\\\UNC\\\\test\\\\unc\") [FAIL]
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                                 ↓ (pos 16)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Expected: \\?\UNC\test\unc
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Actual:   \\?\UNC\test\unc\
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                                 ↑ (pos 16)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.cs(48,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(String value, String expected)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(value: \"\\\\\\\\?\\\\UNC\\\\a\\\\b2\\\\\", expected: \"\\\\\\\\?\\\\UNC\\\\a\\\\b2\") [FAIL]
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                             ↓ (pos 12)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Expected: \\?\UNC\a\b2
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Actual:   \\?\UNC\a\b2\
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                             ↑ (pos 12)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,292: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.cs(48,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(String value, String expected)
```
and
```
2018-02-28 13:24:34,276: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.FileInfo_Directory.UNCShares [FAIL]
2018-02-28 13:24:34,276: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:34,276: INFO: proc(54): run_and_log_output: Output:                                    ↓ (pos 19)
2018-02-28 13:24:34,276: INFO: proc(54): run_and_log_output: Output:       Expected: \\Machine\Directory
2018-02-28 13:24:34,276: INFO: proc(54): run_and_log_output: Output:       Actual:   \\Machine\Directory\
2018-02-28 13:24:34,276: INFO: proc(54): run_and_log_output: Output:                                    ↑ (pos 19)
2018-02-28 13:24:34,292: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:34,401: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.FileSystem\tests\FileInfo\Directory.cs(55,0): at System.IO.Tests.FileInfo_Directory.UNCShares()
2018-02-28 13:24:38,369: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.FileInfo_DirectoryName.UNCShares [FAIL]
2018-02-28 13:24:38,369: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:38,369: INFO: proc(54): run_and_log_output: Output:                                    ↓ (pos 19)
2018-02-28 13:24:38,369: INFO: proc(54): run_and_log_output: Output:       Expected: \\Machine\Directory
2018-02-28 13:24:38,369: INFO: proc(54): run_and_log_output: Output:       Actual:   \\Machine\Directory\
2018-02-28 13:24:38,369: INFO: proc(54): run_and_log_output: Output:                                    ↑ (pos 19)
2018-02-28 13:24:38,369: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:38,369: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.FileSystem\tests\FileInfo\Directory.cs(55,0): at System.IO.Tests.FileInfo_Directory.UNCShares()
```

**Comment by JeremyKuhne** [comment]
cc: @Anipik

**Comment by JeremyKuhne** [comment]
https://github.com/dotnet/corefx/commit/303922a96cc14b3db2150c01f44ffe5dacb18fee

**Comment by JeremyKuhne** [comment]
@Anipik this needs to get mirrored into CoreCLR and we need to get an updated build back into CoreFX.

@danmosemsft, this is a must for Preview 2. Hopefully we can get it done before the fork.

**Comment by JeremyKuhne** [comment]
Note that I'm OOF until 3/6 and won't likely be able to respond.

**Comment by danmosemsft** [comment]
@Anipik please make sure this happens.

**Comment by Anipik** [comment]
@JeremyKuhne I guess its already in there https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/IO/PathInternal.Windows.cs#L216

**Comment by stephentoub** [comment]
@Anipik, there's still a test disabled against this issue:
https://github.com/dotnet/runtime/blob/caa2ed96988d89a080dc63edb7c7868daca1cabc/src/libraries/System.Runtime.Extensions/tests/System/IO/PathTests_Windows.cs#L45-L50
