### ISSUE TITLE
Unexpected status character: I in ProcessTests.TestGetProcesses

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#27578]
https://mc.dot.net/#/user/danmosemsft/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/01337d9cc1d615c0367d1625028ac2cc95cdb34f/workItem/System.Diagnostics.Process.Tests/wilogs

```
2018-02-28 21:54:38,644: INFO: proc(54): run_and_log_output: Output: None of the following programs were installed on this machine: xdg-open,gnome-open,kfmclient.
2018-02-28 21:54:39,611: INFO: proc(54): run_and_log_output: Output: Assertion Failed
2018-02-28 21:54:39,611: INFO: proc(54): run_and_log_output: Output: Unexpected status character: I
2018-02-28 21:54:39,612: INFO: proc(54): run_and_log_output: Output: 
2018-02-28 21:54:39,612: INFO: proc(54): run_and_log_output: Output:    at System.Diagnostics.Tests.ProcessTests.TestGetProcesses() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Diagnostics.Process/tests/ProcessTests.cs:line 899
2018-02-28 21:54:39,613: INFO: proc(54): run_and_log_output: Output:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
```

ProcFsStateToThreadState needs to be updated to include "I"

it seems this was added in 
https://github.com/torvalds/linux/commit/06eb61844d841d0032a9950ce7f8e783ee49c0d0

**Comment by danmosemsft** [comment]
This is showing up in Fedora.26 and Ubuntu18.04 which maybe the first distros with this in their kernel.
