### ISSUE TITLE
InstanceDataCollection_* failures in CI

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#27580]
https://mc.dot.net/#/user/danmosemsft/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/01337d9cc1d615c0367d1625028ac2cc95cdb34f/workItem/System.Diagnostics.PerformanceCounter.Tests/analysis/xunit/System.Diagnostics.Tests.InstanceDataTests~2FInstanceDataCollectionCollection_Contains_Valid
Windows.10.Amd64.Open-Release-x86

all failed the same way on this particular machine/config:
InstanceDataCollection_GetItem_ExistingCounter	
InstanceDataCollection_GetKeys	
InstanceDataCollection_GetValues	
InstanceDataCollection_NullTest
InstanceDataCollectionCollection_Contains_inValid	
InstanceDataCollectionCollection_Contains_Valid	
InstanceDataCollectionCollection_CopyTo	
InstanceDataCollectionCollection_GetItem_Invalid	
InstanceDataCollectionCollection_GetKeys	
InstanceDataCollectionCollection_GetValues	

```
Unhandled Exception of Type Xunit.Sdk.NotEqualException
Message :
Assert.NotEqual() Failure
Expected: Not 0
Actual:   0
Stack Trace :
   at System.Diagnostics.Tests.Helpers.RetryOnAllPlatforms[T](Func`1 func) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\tests\Helpers.cs:line 74
   at System.Diagnostics.Tests.InstanceDataTests.GetInstanceDataCollectionCollection() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\tests\InstanceDataTests.cs:line 130
   at System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_Contains_Valid() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.PerformanceCounter\tests\InstanceDataTests.cs:line 104
```

@brianrob

**Comment by danmosemsft** [comment]
This means despite 20 retries `ReadCategory` on `PerformanceCounterCategory("Processor")` failed.
```c#
            PerformanceCounterCategory pcc =  Helpers.RetryOnAllPlatforms(() => new PerformanceCounterCategory("Processor"));
            return Helpers.RetryOnAllPlatforms(() => pcc.ReadCategory()); /// <----
```

**Comment by brianrob** [comment]
Adding @adiaaida who will be owning performance counters going forward and can take a look at this failure.

**Comment by adiaaida** [comment]
Can you link to repro instructions for this so I can try to run it locally?

**Comment by danmosemsft** [comment]
Hmm, I should have kept the jenkins link. @maririos do you know if there's a way to get from the link below to the jenkins configuration so @adiaaida can request a repro box?
https://mc.dot.net/#/user/danmosemsft/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/01337d9cc1d615c0367d1625028ac2cc95cdb34f/workItem/System.Diagnostics.PerformanceCounter.Tests/analysis/xunit/System.Diagnostics.Tests.InstanceDataTests~2FInstanceDataCollectionCollection_Contains_Valid

**Comment by danmosemsft** [comment]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180313.01/workItem/System.Diagnostics.PerformanceCounter.Tests 

this time on win10 x64

**Comment by joperezr** [comment]
@brianrob PerformanceCounters are part of System.Diagnostics.Tracing as per https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#areas

**Comment by brianrob** [comment]
@joperezr did not realize that.  Thanks.

@adiaaida can you please take a look at this?

**Comment by adiaaida** [comment]
This is an intermittent failure. Per discussion with @danmosemsft, I'm waiting until #26475 is checked in to see if that fixes the issue.

**Comment by MarcoRossignoli** [comment]
@adiaaida @danmosemsft  #26475 after some discussion fix only a race. I don't expect resolve the issue of "registry delay". Read all thread to understand what i mean. Cross finger!

**Comment by ahsonkhan** [comment]
Failed again here: https://github.com/dotnet/corefx/pull/28389
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/8ed94f0eae5b9dcee1b8bc23b9adaae381c0c69a/workItem/System.Diagnostics.PerformanceCounter.Tests/analysis/xunit/System.Diagnostics.Tests.InstanceDataTests~2FInstanceDataCollectionCollection_Contains_Valid

**Comment by adiaaida** [comment]
@ahsonkhan I'm not seeing failures with that link, only skipped tests (we don't run on Nano)

**Comment by ahsonkhan** [comment]
> I'm not seeing failures with that link, only skipped tests (we don't run on Nano)

Ah yes, you are right. I must have linked to the wrong place. I can't seem to get the pass/fail data from that run anymore.
From https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netcoreapp+CGroup_Release+AGroup_x86+TestOuter_false_prtest/10498/

The following links no longer show any failures:
Failed Test Runs
[Windows.10.Amd64.Open](https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/8ed94f0eae5b9dcee1b8bc23b9adaae381c0c69a)
[Windows.7.Amd64.Open](https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/8ed94f0eae5b9dcee1b8bc23b9adaae381c0c69a)

![image](https://user-images.githubusercontent.com/6527137/37843680-e1800efe-2e82-11e8-8901-a9d2ed6d8845.png)

The [console output](https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netcoreapp+CGroup_Release+AGroup_x86+TestOuter_false_prtest/10498/console), however, does show a test failure:
17:59:39 [Windows.7.Amd64.Open] Info: Failed 1/314788 (1415 skipped)

Is there any way to see the test failures in mc.dot.net from that run?

**Comment by danmosemsft** [comment]
@dotnet/dnceng for @ahsonkhan question above.

**Comment by MattGal** [comment]
I took a quick look at this.  Everything behaved as expected, I'll try to explain and give some recommendations:

First I went and found the failing tests directly from the linked Jenkins log's console output:

17:44:35 [Windows.10.Amd64.Open] [{"Key":{"job.name":"ce9dc65d-60e6-4d06-807b-854c37d77eb2"},"Data":{"Analysis":[{"Name":"xunit","Status":{"pass":313686,"fail":10,"skip":1273}}],"WorkItemStatus":{"pass":252}}}]

This failure was: System.Diagnostics.PerformanceCounter.Tests
https://dotnetjobresults.blob.core.windows.net/build-22ffd4664ce147ceaf15e151fad8695b/Windows.10.Amd64.Open/System.Diagnostics.PerformanceCounter.Tests/console.e8703e28.log?sv=2015-04-05&sr=c&sig=xJ2%2BLNWSjNPTg07JCZiNRaaKf%2BlawnxTWU5E7PChwb8%3D&st=2018-03-23T00%3A28%3A40.4824142Z&se=2018-04-22T00%3A28%3A40.4824142Z&sp=r

**Jenkins:**
17:59:39 [Windows.7.Amd64.Open] [{"Key":{"job.name":"8177bddb-fc38-42bd-a982-a6255888cded"},"Data":{"Analysis":[{"Name":"xunit","Status":{"pass":313372,"fail":1,"skip":1415}}],"WorkItemStatus":{"pass":252}}}]

This failure was: System.Net.Security.Tests
https://dotnetjobresults.blob.core.windows.net/build-22ffd4664ce147ceaf15e151fad8695b/Windows.7.Amd64.Open/System.Net.Security.Tests/console.e6466630.log?sv=2015-04-05&sr=c&sig=xJ2%2BLNWSjNPTg07JCZiNRaaKf%2BlawnxTWU5E7PChwb8%3D&st=2018-03-23T00%3A28%3A40.4824142Z&se=2018-04-22T00%3A28%3A40.4824142Z&sp=r


Then I looked at all the jobs in Kusto, like so:
Jobs | where Source == "pr/jenkins/dotnet/corefx/master/" and Type == 'test/functional/cli/' and Build=='8ed94f0eae5b9dcee1b8bc23b9adaae381c0c69a'| order by QueueName asc

Win10 issue
--------------
What happened for Jenkins was:
Initially Windows 10 AMD64 passed and Windows 10 x86 had the failure above.  
The Jenkins plugin only uses Queue Id and not Architecture, so it looked like Win10 both passed and failed

So what happened for Mission Control was:
Windows 10 X86 run with failure (ce9dc65d-60e6-4d06-807b-854c37d77eb2) was superseded by a run with identical metadata (313f06ce-9eab-4bae-b668-a644016bef88), so renders all pass.

**Win 7 issue**
--------------
Identical but different flaky test failure.
Win7 x86 run from the initial jenkins run 8177bddb-fc38-42bd-a982-a6255888cded superseded in MC by b468ffe5-d9d7-4e75-83c6-89a33429a000

**Recommmendations:**  
Jenkins plugin should show Architecture adjacent to queue id like the PR UI can now do.

Users should look at their results before re-queueing work.  If requeuing before looking at results is common, we should make Mission control show ALL runs even with identical Type/Source/Build

If any of this is unclear, ping me :)
