### ISSUE TITLE
System.Data.Common.Tests fails some tests in non english locale

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#27626]
`System.Data.Common.Tests` fails some tests in non english locale with next log
```
  Starting:    System.Data.Common.Tests
     System.Data.Tests.SqlTypes.SqlSingleTest.Conversions [FAIL]
        Assert.Equal() Failure
                    (pos 1)
        Expected: 6.4E+17
        Actual:   6,4E+17
                    (pos 1)
        Stack Trace:
           C:\Code\corefx\src\System.Data.Common\tests\System\Data\SqlTypes\SqlSingleTest.cs(395,0): at System.Data.Tests.SqlTypes.SqlSingleTest.Conversions()
     System.Data.Tests.SqlTypes.SqlDoubleTest.Conversions [FAIL]
        Assert.Equal() Failure
                    (pos 1)
        Expected: 6.4E+65
        Actual:   6,4E+65
                    (pos 1)
        Stack Trace:
           C:\Code\corefx\src\System.Data.Common\tests\System\Data\SqlTypes\SqlDoubleTest.cs(408,0): at System.Data.Tests.SqlTypes.SqlDoubleTest.Conversions()
     System.Data.Tests.SqlTypes.SqlMoneyTest.Conversions [FAIL]
        Assert.Equal() Failure
                       (pos 4)
        Expected: 6464.6464
        Actual:   6464,6464
                       (pos 4)
        Stack Trace:
           C:\Code\corefx\src\System.Data.Common\tests\System\Data\SqlTypes\SqlMoneyTest.cs(357,0): at System.Data.Tests.SqlTypes.SqlMoneyTest.Conversions()
     System.Data.Tests.DataColumnTest2.Expression_Simple [FAIL]
        Assert.Equal() Failure
                      (pos 3)
        Expected: 7,6
        Actual:   7,60
                      (pos 3)
        Stack Trace:
           C:\Code\corefx\src\System.Data.Common\tests\System\Data\DataColumnTest2.cs(614,0): at System.Data.Tests.DataColumnTest2.Expression_Simple()
     System.Data.Tests.SqlTypes.SqlStringTest.SqlDoubleToSqlString [FAIL]
        Assert.Equal() Failure
                    (pos 1)
        Expected: 6.4E+65
        Actual:   6,4E+65
                    (pos 1)
        Stack Trace:
           C:\Code\corefx\src\System.Data.Common\tests\System\Data\SqlTypes\SqlStringTest.cs(665,0): at System.Data.Tests.SqlTypes.SqlStringTest.SqlDoubleToSqlString()
     System.Data.Tests.SqlTypes.SqlStringTest.SqlMoneyToSqlString [FAIL]
        Assert.Equal() Failure
                         (pos 6)
        Expected: 646464.6464
        Actual:   646464,6464
                         (pos 6)
        Stack Trace:
           C:\Code\corefx\src\System.Data.Common\tests\System\Data\SqlTypes\SqlStringTest.cs(731,0): at System.Data.Tests.SqlTypes.SqlStringTest.SqlMoneyToSqlString()
     System.Data.Tests.SqlTypes.SqlDecimalTest.AdjustScale [FAIL]
        Assert.Equal() Failure
                       (pos 4)
        Expected: 6464.646400
        Actual:   6464,646400
                       (pos 4)
        Stack Trace:
           C:\Code\corefx\src\System.Data.Common\tests\System\Data\SqlTypes\SqlDecimalTest.cs(256,0): at System.Data.Tests.SqlTypes.SqlDecimalTest.AdjustScale()
  Finished:    System.Data.Common.Tests
```
Is it error in tests or in functions?

**Comment by danmosemsft** [comment]
It looks like a test issue to me but @saurabh500 can confirm.

BTW, we are working to set up a non-ENU leg in our CI system.

**Comment by saurabh500** [comment]
Moving to future. The tests have been hardcoded with the strings to compare against.

**Comment by danmosemsft** [comment]
We have added a non en-US leg, all that remains to enable by default is this and https://github.com/dotnet/corefx/issues/28858 

https://mc.dot.net/#/user/MattGal/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/43268a17bdfff218828507b0f7a4faa2e4147c19/workItem/System.Data.Common.Tests

Perhaps @Anipik you can fix it? The test probably needs to do call culture-specific formatting API.
