### ISSUE TITLE
System.Drawing.Common.Tests fails 10 tests in non-English Windows

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#27647]
System.Drawing.Common.Tests fails 10 tests in non-English Windows with next log:
```
  Starting:    System.Drawing.Common.Tests
     System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Bold, Italic, Strikeout, gdiCharSet: 1, gdiVerticalFont: True, expectedNamePrefix: \"@\", expectedWeight: 700) [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   204
        Stack Trace:
           C:\Code\corefx\src\System.Drawing.Common\tests\FontTests.cs(719,0): at System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight)
     System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Regular, gdiCharSet: 0, gdiVerticalFont: False, expectedNamePrefix: \"\", expectedWeight: 400) [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   204
        Stack Trace:
           C:\Code\corefx\src\System.Drawing.Common\tests\FontTests.cs(719,0): at System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight)
     System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Regular, gdiCharSet: 10, gdiVerticalFont: False, expectedNamePrefix: \"\", expectedWeight: 400) [FAIL]
        Assert.Equal() Failure
        Expected: 10
        Actual:   204
        Stack Trace:
           C:\Code\corefx\src\System.Drawing.Common\tests\FontTests.cs(719,0): at System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight)
     System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SystemDefault, expectedQuality: 0) [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   204
        Stack Trace:
           C:\Code\corefx\src\System.Drawing.Common\tests\FontTests.cs(756,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint, Int32 expectedQuality)
     System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: AntiAlias, expectedQuality: 3) [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   204
        Stack Trace:
           C:\Code\corefx\src\System.Drawing.Common\tests\FontTests.cs(756,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint, Int32 expectedQuality)
     System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: AntiAliasGridFit, expectedQuality: 3) [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   204
        Stack Trace:
           C:\Code\corefx\src\System.Drawing.Common\tests\FontTests.cs(756,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint, Int32 expectedQuality)
     System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SingleBitPerPixel, expectedQuality: 3) [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   204
        Stack Trace:
           C:\Code\corefx\src\System.Drawing.Common\tests\FontTests.cs(756,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint, Int32 expectedQuality)
     System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SingleBitPerPixelGridFit, expectedQuality: 3) [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   204
        Stack Trace:
           C:\Code\corefx\src\System.Drawing.Common\tests\FontTests.cs(756,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint, Int32 expectedQuality)
     System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: ClearTypeGridFit, expectedQuality: 5) [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   204
        Stack Trace:
           C:\Code\corefx\src\System.Drawing.Common\tests\FontTests.cs(756,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint, Int32 expectedQuality)
     System.Drawing.Imaging.Tests.MetafileTests.Ctor_StringIntPtrEmfType_Success(emfType: EmfPlusDual) [FAIL]
        System.Runtime.InteropServices.ExternalException : A generic error occurred in GDI+.
        Stack Trace:
           C:\Code\corefx\src\System.Drawing.Common\src\System\Drawing\Imaging\Metafile.Windows.cs(264,0): at System.Drawing.Imaging.Metafile..ctor(String fileName, IntPtr referenceHdc, EmfType type, String description)
           C:\Code\corefx\src\System.Drawing.Common\src\System\Drawing\Imaging\Metafile.Windows.cs(241,0): at System.Drawing.Imaging.Metafile..ctor(String fileName, IntPtr referenceHdc, EmfType type)
           C:\Code\corefx\src\System.Drawing.Common\tests\Imaging\MetafileTests.cs(399,0): at System.Drawing.Imaging.Tests.MetafileTests.Ctor_StringIntPtrEmfType_Success(EmfType emfType)
  Finished:    System.Drawing.Common.Tests
```

On my computer `font.ToLogFont(logFont);` always set `logFont.lfCharSet` to 204. 

Is it error is test or implementation?

**Comment by safern** [comment]
@AlexRadch does this repro in .NET Framework? Cause from the stack trace and `System.Runtime.InteropServices.ExternalException : A generic error occurred in GDI+` sounds like an issue in GDI+ rather than in our implementation.

**Comment by AlexRadch** [comment]
> does this repro in .NET Framework (netfx)?

@safern I do not test netfx. I will try it later.

**Comment by AlexRadch** [comment]
@safern I did not find netfx repository https://github.com/dotnet?utf8=%E2%9C%93&q=netfx&type=&language=

**Comment by safern** [comment]
There is no specific repo for netfx, actually in corefx you just need to run:

build.cmd -framework:netfx
msbuild path/to/test/project /t:rebuildandtest /p:targetgroup=netfx

**Comment by AlexRadch** [comment]
> There is no specific repo for netfx, actually in corefx you just need to run:

Thank you, This is documented here https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md#debugging-netfx-tests-in-visual-studio

**Comment by AlexRadch** [comment]
> does this repro in .NET Framework (netfx)?

It seems the same fails except last: `..\..\..\build . -framework:netfx >test.log`
```
    Starting:    System.Drawing.Common.Tests
      System.Drawing.Tests.BitmapTests.Ctor_NullGraphics_ThrowsArgumentNullException [FAIL]
        Assert.Equal() Failure
                   (pos 0)
        Expected: Value of 'null' is not valid for 'g'.
        Actual:   Значение 'null' недопустимо для 'g'.
                   (pos 0)
        Stack Trace:
             в Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\StringAsserts.cs:строка 239
             в Xunit.Assert.Equal(String expected, String actual) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\StringAsserts.cs:строка 170
             в System.AssertExtensions.Throws[T](String netCoreParamName, String netFxParamName, Action action)
             в System.Drawing.Tests.BitmapTests.Ctor_NullGraphics_ThrowsArgumentNullException()
      System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Bold, Italic, Strikeout, gdiCharSet: 1, gdiVerticalFont: True, expectedNamePrefix: "@", expectedWeight: 700) [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   204
        Stack Trace:
             в Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:строка 35
             в System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight)
      System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Regular, gdiCharSet: 0, gdiVerticalFont: False, expectedNamePrefix: "", expectedWeight: 400) [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   204
        Stack Trace:
             в Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:строка 35
             в System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight)
      System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Regular, gdiCharSet: 10, gdiVerticalFont: False, expectedNamePrefix: "", expectedWeight: 400) [FAIL]
        Assert.Equal() Failure
        Expected: 10
        Actual:   204
        Stack Trace:
             в Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:строка 35
             в System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight)
      System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SystemDefault, expectedQuality: 0) [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   204
        Stack Trace:
             в Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:строка 35
             в System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint, Int32 expectedQuality)
      System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: AntiAlias, expectedQuality: 3) [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   204
        Stack Trace:
             в Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:строка 35
             в System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint, Int32 expectedQuality)
      System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: AntiAliasGridFit, expectedQuality: 3) [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   204
        Stack Trace:
             в Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:строка 35
             в System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint, Int32 expectedQuality)
      System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SingleBitPerPixel, expectedQuality: 3) [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   204
        Stack Trace:
             в Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:строка 35
             в System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint, Int32 expectedQuality)
      System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SingleBitPerPixelGridFit, expectedQuality: 3) [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   204
        Stack Trace:
             в Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:строка 35
             в System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint, Int32 expectedQuality)
      System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: ClearTypeGridFit, expectedQuality: 5) [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   204
        Stack Trace:
             в Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:строка 35
             в System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint, Int32 expectedQuality)
    Finished:    System.Drawing.Common.Tests
```

**Comment by AlexRadch** [comment]
And new `System.Drawing.Tests.BitmapTests.Ctor_NullGraphics_ThrowsArgumentNullException [FAIL]` fail added.

**Comment by safern** [comment]
So this sounds to me like the bug probably came from the pure port of netfx to .NET Core. I will debug and try to find the root cause. Thanks @AlexRadch for confirming that it repro. Also from the new error in netfx it is a bug in the test since we're asserting for the netfx paramName in the ArgumentNullException and we are trying to avoid doing that since this changes from version to version. 

See: https://github.com/dotnet/corefx/blob/master/src/CoreFx.Private.TestUtilities/src/System/AssertExtensions.cs#L28

The test is doing: 
https://github.com/dotnet/corefx/blob/ec22edc155aa13289770c9f49630cc7ab588fca4/src/System.Drawing.Common/tests/BitmapTests.cs#L325

We should change that test to pass null as the second argument so that it is ignored.

**Comment by AlexRadch** [comment]
> Also from the new error in netfx it is a bug in the test since we're asserting for the netfx paramName in the ArgumentNullException and we are trying to avoid doing that since this changes from version to version.

The test is correct, but Exception message is localized on my Windows from `Value of 'null' is not valid for 'g'.` to `Значение 'null' недопустимо для 'g'.`. Issue is that test expects english message but fails on equal localized message.

It suggest to test only exception class but not message.

**Comment by safern** [comment]
That is what I suggested. In netfx we don't test exception messages or parameters because they can be localized or change from version to version. If we change 

```
 AssertExtensions.Throws<ArgumentNullException>("g", "Value of 'null' is not valid for 'g'.", () => new Bitmap(1, 1, null)); 
```
to 
```
 AssertExtensions.Throws<ArgumentNullException>("g", null, () => new Bitmap(1, 1, null)); 
```

the paramName (message in this case) will not be tested because will hit this code path: https://github.com/dotnet/corefx/blob/master/src/CoreFx.Private.TestUtilities/src/System/AssertExtensions.cs#L28

Please feel free to submit a PR for it :)

**Comment by AlexRadch** [comment]
> That is what I suggested.

Ok. Now I understand you due my english. I will make PR.

**Comment by safern** [comment]
> Ok. Now I understand you due my english.

No worries :)

> I will make PR.

Thanks, really appreciate it.

**Comment by safern** [comment]
It is weird why `logFont.lfCharSet` is getting the value of 204 when in a Russian Windows, we are assigning `_gdiCharSet` value to it when calling `ToLongFont` and `_gdiCharSet` is either set to default: 1 or to what is passed in the constructor, which in this case should be the same value as what `new Font(...)` was passed to. I don't see any other place of `_gdiCharSet` being modified. 

@AlexRadch would you be able to debug in your OS? The culprit seems somewhere in: https://source.dot.net/#System.Drawing.Common/System/Drawing/Font.Windows.cs,554

I have tried to repro but wasn't able, maybe I need to install a non-english windows rather than just changing the default OS display language.
