### ISSUE TITLE
System.IO.Tests.DirectoryInfo Win10 UWP CI Failures

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#27653]
UWP CoreCLR x64 Debug Build
Windows.10.Amd64.ClientRS2.Open-Debug-x64
```
System.IO.Tests.DirectoryInfo_Create
  RootPath

Unhandled Exception of Type System.IO.DirectoryNotFoundException
Message :
System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\\'.
Stack Trace :
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.DirectoryInfo.Create()
   at System.IO.Tests.DirectoryInfo_Create.Create(String path) in D:\j\workspace\windows-TGrou---33cbf18b\src\System.IO.FileSystem\tests\DirectoryInfo\Create.cs:line 16
   at System.IO.Tests.Directory_CreateDirectory.RootPath() in D:\j\workspace\windows-TGrou---33cbf18b\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs:line 89
```
```
System.IO.Tests.DirectoryInfo_Exists
  Root
Assert.True() Failure
Expected: True
Actual:   False
Stack Trace :
   at System.IO.Tests.DirectoryInfo_Exists.Root() in D:\j\workspace\windows-TGrou---33cbf18b\src\System.IO.FileSystem\tests\DirectoryInfo\Exists.cs:line 43
```
```
System.IO.Tests.DirectoryInfo_ToString
  DriveOnlyReturnsPeriod_Windows_Desktop
Assert.Equal() Failure
          ↓ (pos 0)
Expected: .
Actual:   C:
          ↑ (pos 0)
Stack Trace :
   at System.IO.Tests.DirectoryInfo_ToString.DriveOnlyReturnsPeriod_Windows_Desktop() in D:\j\workspace\windows-TGrou---33cbf18b\src\System.IO.FileSystem\tests\DirectoryInfo\ToString.cs:line 47
```
```
System.IO.Tests.Directory_CreateDirectory
  RootPath
Unhandled Exception of Type System.IO.DirectoryNotFoundException
Message :
System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\\'.
Stack Trace :
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at System.IO.Tests.Directory_CreateDirectory.Create(String path) in D:\j\workspace\windows-TGrou---33cbf18b\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs:line 17
   at System.IO.Tests.Directory_CreateDirectory.RootPath() in D:\j\workspace\windows-TGrou---33cbf18b\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs:line 89
```
#27644
#27650
#27645

**Comment by ahsonkhan** [comment]
Is this on the "UWP CoreCLR x64 Debug Build" leg only? I think the build updates (from https://github.com/dotnet/corefx/pull/27640) will resolve this issue.

**Comment by benaadams** [comment]
Yes

**Comment by ahsonkhan** [comment]
In that case, I think this can be closed, but let's wait till build goes through to confirm.

cc @JeremyKuhne, @stephentoub

**Comment by danmosemsft** [comment]
Kicked the leg in https://github.com/dotnet/corefx/pull/27645 to see.
