### ISSUE TITLE
_preAllocatedOverlapped is null assert in Http tests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#27721]
This has been failing sporadically since my ValueTask changes. The issue is that we end up disposing a SocketAsyncEventArgs while it's in use and then hit this assert in cleanup code.
```
_preAllocatedOverlapped is null
2018-03-05 13:12:16,275: INFO: proc(54): run_and_log_output: Output: 
2018-03-05 13:12:16,275: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.SocketAsyncEventArgs.FreeNativeOverlapped(NativeOverlapped* overlapped) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.Windows.cs:line 76
2018-03-05 13:12:16,275: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.SocketAsyncEventArgs.FreeNativeOverlappedIfNotPending(NativeOverlapped* overlapped, SocketError error) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.Windows.cs:line 85
2018-03-05 13:12:16,275: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendSingleBuffer(SafeCloseSocket handle) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.Windows.cs:line 556
2018-03-05 13:12:16,275: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.SocketAsyncEventArgs.DoOperationSend(SafeCloseSocket handle) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.Windows.cs:line 551
2018-03-05 13:12:16,275: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.Socket.SendAsync(SocketAsyncEventArgs e) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs:line 4178
2018-03-05 13:12:16,275: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream(Socket socket) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs:line 921
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.Socket.SendAsyncForNetworkStream(ReadOnlyMemory`1 buffer, SocketFlags socketFlags, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs:line 377
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Sockets\src\System\Net\Sockets\NetworkStream.cs:line 846
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Net.Http.HttpConnection.WriteToStreamAsync(ReadOnlyMemory`1 source) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 1042
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Net.Http.HttpConnection.FlushAsync() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 1032
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 350
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in E:\A\_work\1986\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 938
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Net.Http.HttpConnection.SendWithNtProxyAuthAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 589
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 599
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 249
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\1986\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs:line 166
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in E:\A\_work\1986\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 559
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in E:\A\_work\1986\s\src\mscorlib\src\System\Threading\Tasks\Task.cs:line 3283
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in E:\A\_work\1986\s\src\mscorlib\src\System\Threading\Tasks\future.cs:line 421
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in E:\A\_work\1986\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 650
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result) in E:\A\_work\1986\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 640
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result) in E:\A\_work\1986\s\src\mscorlib\shared\System\Runtime\CompilerServices\AsyncValueTaskMethodBuilder.cs:line 169
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 456
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\1986\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs:line 166
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in E:\A\_work\1986\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 559
2018-03-05 13:12:16,290: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ThreadPoolWorkQueue.Dispatch() in E:\A\_work\1986\s\src\mscorlib\src\System\Threading\ThreadPool.cs:line 588
2018-03-05 13:12:18,809: INFO: proc(54): run_and_log_output: Output: ----- end 13:12:18.80 ----- exit code -2146232797 ----------------------------------------------------------
2018-03-05 13:12:18,809: INFO: proc(58): run_and_log_output: Exit Code: -2146232797
2018-03-05 13:12:18,809: ERROR: scriptrunner(91): _main: Error: No exception thrown, but XUnit results not created
2018-03-05 13:12:18,809: ERROR: helix_test_execution(83): report_error: Error running xunit None
```

**Comment by danmosemsft** [comment]
AGain https://mc.dot.net/#/user/jkotas/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/a5c6501fefa2926933ca78a48acc4f5c863dfa5e/workItem/System.Net.Http.Functional.Tests/wilogs
