### ISSUE TITLE
Assertion in channels using pooled object

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#27754]
```
Assertion Failed
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output: The continuation was the completion sentinel. State=CompletionSet.
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output: 
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Channels.ResettableValueTaskSource`1.InvokeContinuation() in D:\j\workspace\windows-TGrou---db113413\src\System.Threading.Channels\src\System\Threading\Channels\AsyncOperation.cs:line 261
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Channels.ResettableValueTaskSource`1.SignalCompletion() in D:\j\workspace\windows-TGrou---db113413\src\System.Threading.Channels\src\System\Threading\Channels\AsyncOperation.cs:line 254
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Channels.ResettableValueTaskSource`1.TrySetResult(T result) in D:\j\workspace\windows-TGrou---db113413\src\System.Threading.Channels\src\System\Threading\Channels\AsyncOperation.cs:line 211
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Channels.AsyncOperation`1.Success(TResult item) in D:\j\workspace\windows-TGrou---db113413\src\System.Threading.Channels\src\System\Threading\Channels\AsyncOperation.cs:line 336
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Channels.SingleConsumerUnboundedChannel`1.UnboundedChannelWriter.TryWrite(T item) in D:\j\workspace\windows-TGrou---db113413\src\System.Threading.Channels\src\System\Threading\Channels\SingleConsumerUnboundedChannel.cs:line 327
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Channels.SingleConsumerUnboundedChannel`1.UnboundedChannelWriter.WriteAsync(T item, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Threading.Channels\src\System\Threading\Channels\SingleConsumerUnboundedChannel.cs:line 347
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Channels.Tests.PerfTests.<>c__DisplayClass4_1.<<PingPong>b__1>d.MoveNext() in D:\j\workspace\windows-TGrou---db113413\src\System.Threading.Channels\tests\Performance\Perf.Channel.cs:line 122
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\1250\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs:line 166
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in E:\A\_work\1250\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 559
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Channels.ResettableValueTaskSource`1.<>c.<InvokeContinuation>b__30_0(Object s) in D:\j\workspace\windows-TGrou---db113413\src\System.Threading.Channels\src\System\Threading\Channels\AsyncOperation.cs:line 270
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\1250\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs:line 166
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) in E:\A\_work\1250\s\src\mscorlib\src\System\Threading\Tasks\Task.cs:line 2440
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ThreadPoolWorkQueue.Dispatch() in E:\A\_work\1250\s\src\mscorlib\src\System\Threading\ThreadPool.cs:line 588
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output: Expected IsCompleted, got Owned
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output: 
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Channels.ResettableValueTaskSource`1.OnCompleted(Action`1 continuation, Object state, Int16 token, ValueTaskSourceOnCompletedFlags flags) in D:\j\workspace\windows-TGrou---db113413\src\System.Threading.Channels\src\System\Threading\Channels\AsyncOperation.cs:line 190
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.ValueTaskAwaiter`1.System.Runtime.CompilerServices.IValueTaskAwaiter.AwaitUnsafeOnCompleted(IAsyncStateMachineBox box) in E:\A\_work\1250\s\src\mscorlib\shared\System\Runtime\CompilerServices\ValueTaskAwaiter.cs:line 183
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AwaitUnsafeOnCompleted[TAwaiter,TStateMachine](TAwaiter& awaiter, TStateMachine& stateMachine) in E:\A\_work\1250\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 377
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Channels.Tests.PerfTests.<>c__DisplayClass4_1.<<PingPong>b__0>d.MoveNext() in D:\j\workspace\windows-TGrou---db113413\src\System.Threading.Channels\tests\Performance\Perf.Channel.cs:line 112
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\1250\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs:line 166
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in E:\A\_work\1250\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 559
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Channels.ResettableValueTaskSource`1.<>c.<InvokeContinuation>b__30_0(Object s) in D:\j\workspace\windows-TGrou---db113413\src\System.Threading.Channels\src\System\Threading\Channels\AsyncOperation.cs:line 270
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\1250\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs:line 166
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) in E:\A\_work\1250\s\src\mscorlib\src\System\Threading\Tasks\Task.cs:line 2440
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ThreadPoolWorkQueue.Dispatch() in E:\A\_work\1250\s\src\mscorlib\src\System\Threading\ThreadPool.cs:line 588
2018-03-05 22:00:23,076: INFO: proc(54): run_and_log_output: Output: ----- end 22:00:23.07 ----- exit code -2146232797 ----------------------------------------------------------
2018-03-05 22:00:23,092: INFO: proc(58): run_and_log_output: Exit Code: -2146232797
2018-03-05 22:00:23,092: ERROR: scriptrunner(91): _main: Error: No exception thrown, but XUnit results not created
2018-03-05 22:00:23,092: ERROR: helix_test_execution(83): report_error: Error running xunit None

2018-03-05 22:00:23,092: INFO: azure_storage(205): _upload: Uploading single blob: 'error.log'
2018-03-05 22:00:23,124: INFO: saferequests(90): request_with_retry: Response complete with status code '201'
2018-03-05 22:00:23,124: INFO: helix_test_execution(93): report_error: Sending ToF test failure event
2018-03-05 22:00:23,124: INFO: event(43): send: Sending event type XUnitTestFailure
2018-03-05 22:00:23,358: INFO: saferequests(90): request_with_retry: Response complete with status code '201'
2018-03-05 22:00:23,374: INFO: azure_storage(205): _upload: Uploading single blob: '7b71c5bca82b4295bcadc5567fd2aa32.log'
2018-03-05 22:00:23,436: INFO: saferequests(90): request_with_retry: Response complete with status code '201'
2018-03-05 22:00:23,436: INFO: event(43): send: Sending event type Logs
2018-03-05 22:00:23,576: INFO: saferequests(90): request_with_retry: Response complete with status code '201'
scriptrunner.py 
```

**Comment by stephentoub** [comment]
I have a fix. Just need to test it and put up a PR.

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/27780.
