### ISSUE TITLE
System.Globalization.Extensions: Normalization

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#2777]
We need to implement [StringNormalizationExtensions.cs](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/StringNormalizationExtensions.Unix.cs) for Linux.

The major difference between ICU and Win32 is that Win32 throws an exception when the input is not a valid UTF-16 encoded string (e.g. mismatched surrogates) whereas ICU does not.

**Comment by dougbu** [comment]
Note this issue impacts `System.Uri` as well. That class calls `string.Normalize()` at https://github.com/dotnet/corefx/blob/41e203011152581a6c65bb81ac44ec037140c1bb/src/System.Private.Uri/src/System/Uri.cs#L4178 and 3 other places. If this issue can't be fixed fairly quickly, would like to see a workaround in `System.Uri`.

For example the hostname "pingüino" in a URI leads to the following stack trace
```
      System.NotImplementedException : The method or operation is not implemented.
      Stack Trace:
           at System.StringNormalizationExtensions.IsNormalized(String value, NormalizationForm normalizationForm)
           at System.StringNormalizationExtensions.Normalize(String value, NormalizationForm normalizationForm)
           at System.Uri.CheckAuthorityHelperHandleDnsIri(Char* pString, UInt16 start, Int32 end, Int32 startInput, Boolean iriParsing, Boolean hasUnicode, UriParser syntax, String userInfoString, Flags& flags, Boolean& justNormalized, String& newHost, ParsingError& err)
           at System.Uri.CheckAuthorityHelper(Char* pString, UInt16 idx, UInt16 length, ParsingError& err, Flags& flags, UriParser syntax, String& newHost)
           at System.Uri.PrivateParseMinimal()
           at System.Uri.InitializeUri(ParsingError err, UriKind uriKind, UriFormatException& e)
           at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)

```

**Comment by davidsh** [comment]
cc: @CIPop due to impact to System.Uri.

**Comment by ellismg** [comment]
The changes to enable normalization should land early next week.

**Comment by ellismg** [comment]
The changes are in master with 61adf16f201120d28affe35ac28696d0c3f85b7f.
