### ISSUE TITLE
LinkedList_Generic_Tests_int.RemoveLast_Tests failed on Windows in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#27817]
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/35efdbdc1e25f83f216064482479e555425ce3a0/workItem/System.Collections.Tests/analysis/xunit/System.Collections.Tests.LinkedList_Generic_Tests_int~2FRemoveLast_Tests
```
Windows.81.Amd64.Open-Debug-x64
Unhandled Exception of Type Xunit.Sdk.EqualException
Message :
Assert.Equal() Failure
Expected: LinkedListNode`1 { List = [718949278, 815265269, 911581260, 1007897251, 1104213242, ...], Next = LinkedListNode`1 { List = [...], Next = null, Previous = LinkedListNode`1 { ... }, Value = 1296845224 }, Previous = LinkedListNode`1 { List = [...], Next = LinkedListNode`1 { ... }, Previous = LinkedListNode`1 { ... }, Value = 1104213242 }, Value = 1200529233 }
Actual:   LinkedListNode`1 { List = [718949278, 815265269, 911581260, 1007897251, 1104213242, ...], Next = LinkedListNode`1 { List = [...], Next = null, Previous = LinkedListNode`1 { ... }, Value = 1296845224 }, Previous = LinkedListNode`1 { List = [...], Next = LinkedListNode`1 { ... }, Previous = LinkedListNode`1 { ... }, Value = 1104213242 }, Value = 1200529233 }
Stack Trace :
   at System.Collections.Tests.LinkedList_Generic_Tests`1.VerifyLinkedListNode(LinkedListNode`1 node, T expectedValue, LinkedList`1 expectedList, LinkedListNode`1 expectedPrevious, LinkedListNode`1 expectedNext) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Collections\tests\Generic\LinkedList\LinkedList.Generic.Tests.cs:line 141
   at System.Collections.Tests.LinkedList_Generic_Tests`1.VerifyState(LinkedList`1 linkedList, T[] expectedItems) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Collections\tests\Generic\LinkedList\LinkedList.Generic.Tests.cs:line 83
   at System.Collections.Tests.LinkedList_Generic_Tests`1.InitialItems_Tests(LinkedList`1 collection, T[] expectedItems) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Collections\tests\Generic\LinkedList\LinkedList.Generic.Tests.cs:line 38
   at System.Collections.Tests.LinkedList_Generic_Tests`1.RemoveLast_Tests() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Collections\tests\Generic\LinkedList\LinkedList.Generic.Tests.RemoveLast.cs:line 89
```

**Comment by danmosemsft** [comment]
That's a little worrying. The implementation and tests have not changed in some time, and there should be no concurrency involved.

Next steps might be more asserts in the test, and a better visualization of LinkedListNode in the failure case. See https://github.com/xunit/assert.xunit/blob/master/Sdk/ArgumentFormatter.cs#L148

**Comment by danmosemsft** [comment]
@jkotas would it be a reach to suspect a runtime issue? any other theory?

**Comment by jkotas** [comment]
Memory corruption or GC hole. Running the tests on checked runtime, with GCStress enabled, may be useful.

**Comment by jkotas** [comment]
This issue was moved to dotnet/coreclr#16892
