### ISSUE TITLE
Unobserved task exception thrown with new SocketsHttpHandler

### ISSUE THREAD

**Issue by JustArchi** [dotnet/corefx#27877]
```
OnUnobservedTaskException() System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Unable to read data from the transport connection: Operation canceled.) ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)<---
```

Not a fatal error but it should not be written to `TaskScheduler.UnobservedTaskException`. Thanks!

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview2-008318
 Commit:    f29118002c

Runtime Environment:
 OS Name:     debian
 OS Version:
 OS Platform: Linux
 RID:         debian-x64
 Base Path:   /opt/dotnet/sdk/2.1.300-preview2-008318/

Host (useful for support):
  Version: 2.1.0-preview2-26308-01
  Commit:  dd5407cc77

.NET Core SDKs installed:
  2.1.300-preview2-008318 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-30248 [/opt/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-30248 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26308-01 [/opt/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by JustArchi** [comment]
BTW I seem to receive this exception constantly, even when doing just a few https requests. I'm not entirely sure if all of that is appropriate, even though requests seem to finish properly without throwing any exceptions directly to the userspace, so it's probably harmless. Maybe it has something to do with sockets being closed due to idle time.

**Comment by JustArchi** [comment]
Thanks for the fix! 👍
