### ISSUE TITLE
Getting error on windows => System.PlatformNotSupportedException: 'System.IO.Ports is currently only supported on Windows.'

### ISSUE THREAD

**Issue by harvinders** [dotnet/corefx#27885]
I have a .net standard 2.0 dll (Drivers.CommunicationLocal) which is referencing SerialPort class. When I try to use this from a .Net 4.6.1 console app or a xUnit (.net core 2.0) on windows 10, I get the following exception. Using it from UWP app works fine.

System.PlatformNotSupportedException: System.IO.Ports is currently only supported on Windows.
   at System.IO.Ports.SerialPort..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits)
   at Drivers.CommunicationLocal.CommunicationLayerSerialPortLocal..ctor(SettingSerialPortLocal settings) in C:\Users\abc\Documents\Visual Studio 2017\Projects\experiment\senna\src\Drivers.CommunicationLocal\CommunicationLayerSerialPortLocal.cs:line 24

**Comment by stephentoub** [comment]
cc: @JeremyKuhne, @AlexGhiondea

**Comment by danmosemsft** [comment]
@harvinders is it possible to boil this down to a minimal repro (would be at least two projects and stub sources) and share for us? I suspect a reference isn't flowing correctly through the project references.

Meantime you may be able to work around this by adding a direct Nuget package reference from your app project to System.IO.Ports package.

**Comment by harvinders** [comment]
I believe the issue is within project.asset.json. I created a copy of the whole project and then removed stuff one by one. I removed the bin and obj and restored the packages. This resulted in a different project.asset.json. 

Unfortunately, I can't share it and still trying to have a meaningful minimal repo that reproduces the issue. Sorry about that.

**Comment by hillin** [comment]
Same here, using [4.6.0 on nuget](https://www.nuget.org/packages/System.IO.Ports/4.6.0).

Trying to decompile the System.IO.Ports.dll file (34 KB) copied to my app's directory revealed that it's actually a .NET Framework 4.7 assembly in which all methods in `System.IO.Ports.SerialPort` throw a `PlatformNotSupportedException`.

When dig into the nupkg, I can see the file `lib\netstandard2.0\System.IO.Ports.dll` (34 KB), which was copied to my app's directory, is the incorrect .NET Framework 4.7 assembly. I can find the correct file at `runtimes\win\lib\netstandard2.0\System.IO.Ports.dll` (71 KB). Replacing the wrong file with this one worked like a charm.

So a faulty packing I guess?

**Comment by hillin** [comment]
A slight bump: this issue persists in [4.7.0](https://www.nuget.org/packages/System.IO.Ports/4.7.0).

**Comment by JeremyKuhne** [comment]
Triage: @joperezr this appears to be packaging related, can you take a look?

**Comment by joperezr** [comment]
The package isn't correctly authored, my guess here is that the way that net461 project is consuming the package is via packages.config which won't produce an assets file so it's just bringing the same implementation picked by the netstandard assembly. It would really help if we could get a binlog to confirm my suspicions.

Here is a way to work around it:

1. Create your .NET Standard library project.
2. Add System.IO.Ports package version 4.7.0 and use it by for example referencing the SerialPort class.
3. Create a .NET Framework project that targets net461.
4. Add the following code to your .NET Framework .csproj:
```xml
<PropertyGroup>
  <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
  <RuntimeIdentifier>win</RuntimeIdentifier>
</PropertyGroup>
```
5. Add reference from .NET Framework project to your .NET Standard library project.
6. Using msbuild, restore packages for the .NET Framework project (either via developer command prompt or via Visual Studio).
7. Use the netstandard library

After running the above steps, I'm getting the right System.IO.Ports placed in the binfolder and I'm able to run correctly. Please give that a try and if it doesn't work let me know so I can investigate.
