### ISSUE TITLE
GetResponseAsync_ServerNameNotInDns_ThrowsWebException() test fails with SocketsHttpHandler 

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#27906]
Expecting `WebExceptionStatus.NameResolutionFailure` get `UnknownError` instead.

Call stack for WinHttpHandler:
```

+		ex	{System.Net.WebException: An error occurred while sending the request. The server name or address could not be resolved ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The server name or address could not be resolved
   at System.Environment.get_StackTrace() in D:\corefx\src\System.Runtime.Extensions\src\System\Environment.cs:line 146
   at System.Runtime.ExceptionServices.ExceptionStackTrace.AddCurrentStack(Exception exception) in D:\corefx\src\Common\src\System\Runtime\ExceptionServices\ExceptionStackTrace.cs:line 23
   at System.Net.Http.WinHttpException.CreateExceptionUsingError(Int32 error) in D:\corefx\src\Common\src\System\Net\Http\WinHttpException.cs:line 56
   at System.Net.Http.WinHttpRequestCallback.OnRequestError(WinHttpRequestState state, WINHTTP_ASYNC_RESULT asyncResult) in D:\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs:line 324
   at System.Net.Http.WinHttpRequestCallback.RequestCallback(IntPtr handle, WinHttpRequestState state, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength) in D:\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs:line 104
   at System.Net.Http.WinHttpRequestCallback.WinHttpCallback(IntPtr handle, IntPtr context, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength) in D:\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs:line 47
--- End of stack trace from AddCurrentStack ---
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in D:\corefx\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs:line 62
   at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state) in D:\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 856
   --- End of inner exception stack trace ---
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\corefx\src\System.Net.Http\src\System\Net\Http\DiagnosticsHandler.cs:line 98
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in D:\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 501
   at System.Net.HttpWebRequest.SendRequest() in D:\corefx\src\System.Net.Requests\src\System\Net\HttpWebRequest.cs:line 1209
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) in D:\corefx\src\System.Net.Requests\src\System\Net\HttpWebRequest.cs:line 1259
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) in D:\corefx\src\System.Net.Requests\src\System\Net\HttpWebRequest.cs:line 1263
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar) in D:\corefx\src\System.Net.Requests\src\System\Net\WebRequest.cs:line 550
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) in E:\A\_work\1045\s\src\mscorlib\src\System\Threading\Tasks\FutureFactory.cs:line 529
--- End of stack trace from previous location where exception was thrown ---
   at Xunit.Assert.RecordExceptionAsync(Func`1 testCode) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\Record.cs:line 76}	System.Net.WebException



		ex.Status	NameResolutionFailure	System.Net.WebExceptionStatus
```

Call stack for SocketsHttpHandler:
```
+		ex	{System.Net.WebException: No such host is known No such host is known ---> System.Net.Http.HttpRequestException: No such host is known ---> System.Net.Sockets.SocketException: No such host is known
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in D:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\ConnectHelper.cs:line 78
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in D:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\ConnectHelper.cs:line 98
   at System.Threading.Tasks.ValueTask`1.get_Result() in E:\A\_work\1045\s\src\mscorlib\shared\System\Threading\Tasks\ValueTask.cs:line 713
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 309
   at System.Threading.Tasks.ValueTask`1.get_Result() in E:\A\_work\1045\s\src\mscorlib\shared\System\Threading\Tasks\ValueTask.cs:line 713
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask) in D:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 450
   at System.Threading.Tasks.ValueTask`1.get_Result() in E:\A\_work\1045\s\src\mscorlib\shared\System\Threading\Tasks\ValueTask.cs:line 713
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in D:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 243
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\RedirectHandler.cs:line 30
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\corefx\src\System.Net.Http\src\System\Net\Http\DiagnosticsHandler.cs:line 98
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in D:\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 501
   at System.Net.HttpWebRequest.SendRequest() in D:\corefx\src\System.Net.Requests\src\System\Net\HttpWebRequest.cs:line 1209
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) in D:\corefx\src\System.Net.Requests\src\System\Net\HttpWebRequest.cs:line 1259
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) in D:\corefx\src\System.Net.Requests\src\System\Net\HttpWebRequest.cs:line 1263
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar) in D:\corefx\src\System.Net.Requests\src\System\Net\WebRequest.cs:line 550
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) in E:\A\_work\1045\s\src\mscorlib\src\System\Threading\Tasks\FutureFactory.cs:line 529
--- End of stack trace from previous location where exception was thrown ---
   at Xunit.Assert.RecordExceptionAsync(Func`1 testCode) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\Record.cs:line 76}	System.Net.WebException


		ex.Status	UnknownError	System.Net.WebExceptionStatus
```

**Comment by davidsh** [comment]
Since .NET Core builds HttpWebRequest on top of HttpClient, it has more difficulty getting the enum value of WebExceptionStatus set to one of the known values.  In order to fix this, it would have to be able to dive into the inner exceptions to handle the variations of the different implementations of HttpClient itself.  So, the `WebException.GetStatusFromException` will have to be enhanced.

See: https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/src/System/Net/WebExceptionPal.Windows.cs#L12
