### ISSUE TITLE
AD0001: CSharpAsAndNullCheckDiagnosticAnalyzer throws NRE

### ISSUE THREAD

**Issue by pjanotti** [dotnet/corefx#27969]
This is likely something brought by VS but I didn't investigate to be 100% sure.

```
Analyzer 'Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	System.IO.Pipes.Tests		1	Active	Analyzer 'Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: System.IO.Pipes.Tests
SyntaxTree: C:\s\github\pjanotti\corefx\src\System.IO.Pipes\tests\NamedPipeTests\NamedPipeTest.CurrentUserOnly.netcoreapp.Windows.cs
SyntaxNode: return; [ReturnStatementSyntax]@[3603..3610) (80,16)-(80,23)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer.GetLeftmostCondition(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer.SyntaxNodeAction(SyntaxNodeAnalysisContext syntaxContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

**Comment by weshaggard** [comment]
Looks like a dogfooding issue https://github.com/dotnet/roslyn/issues/25237.
