### ISSUE TITLE
ArgumentNullException with StringComparer.CurrentCultureIgnoreCase when GlobalizationMode.Invariant=true

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/corefx#28021]
When GlobalizationMode.Invariant=true is in effect (such as on Alpine in the `microsoft/dotnet:2.1-runtime-deps-alpine` image), attempts to use `StringComparer.CurrentCultureIgnoreCase` cause crashes.

This appears to have changed between runtime 2.0 and current builds of 2.1.

Simple repro:

```c#
using System;
using System.Collections;

namespace hashtable
{
    class Program
    {
        static void Main(string[] args)
        {
            Hashtable h = new Hashtable(StringComparer.CurrentCultureIgnoreCase);

            h["Foo"] = "bar";

            Console.WriteLine(h.ContainsKey("foo"));
            Console.WriteLine("Hello World!");
        }
    }
}
```

Working:

```sh-session
raines@raines-z220u:~/src/hashtable$ dotnet --info
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.10
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.101/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

raines@raines-z220u:~/src/hashtable$ DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true dotnet exec /home/raines/src/hashtable/bin/Debug/netcoreapp2.0/hashtable.dll
True
Hello World!
```

Failing:

```sh-session
$ dotnet --info
.NET Comma$ DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true dotnet exec bin/Debug/netcoreapp2.0/hashtable.dll 

Unhandled Exception: System.ArgumentNullException: SafeHandle cannot be null.
Parameter name: pHandle
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Globalization.GetSortKey(SafeSortHandle sortHandle, String str, Int32 strLength, Byte* sortKey, Int32 sortKeyLength, CompareOptions options)
   at System.Globalization.CompareInfo.GetHashCodeOfStringCore(String source, CompareOptions options)
   at System.Collections.Hashtable.GetHash(Object key)
   at System.Collections.Hashtable.InitHash(Object key, Int32 hashsize, UInt32& seed, UInt32& incr)
   at System.Collections.Hashtable.ContainsKey(Object key)
   at hashtable.Program.Main(String[] args) in /home/raines/src/hashtable/Program.cs:line 12
Aborted (core dumped)nd Line Tools (2.1.300-preview2-008251)

Product Information:
 Version:            2.1.300-preview2-008251
 Commit SHA-1 hash:  94fd3fd392

Runtime Environment:
 OS Name:     alpine
 OS Version:  3.6
 OS Platform: Linux
 RID:         alpine.3.6-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300-preview2-008251/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview2-26131-06
  Build    : b13a0d5c331f374afd35ded57b9a4b4ab128864c

$DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true dotnet exec bin/Debug/netcoreapp2.0/hashta
ble.dll 

Unhandled Exception: System.ArgumentNullException: SafeHandle cannot be null.
Parameter name: pHandle
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Globalization.GetSortKey(SafeSortHandle sortHandle, String str, Int32 strLength, Byte* sortKey, Int32 sortKeyLength, CompareOptions options)
   at System.Globalization.CompareInfo.GetHashCodeOfStringCore(String source, CompareOptions options)
   at System.Collections.Hashtable.GetHash(Object key)
   at System.Collections.Hashtable.InitHash(Object key, Int32 hashsize, UInt32& seed, UInt32& incr)
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.set_Item(Object key, Object value)
   at hashtable.Program.Main(String[] args) in /home/raines/src/hashtable/Program.cs:line 12
Aborted (core dumped)
```

**Comment by jkotas** [comment]
cc @tarekgh

**Comment by janvorli** [comment]
@kasper3 this is not Alpine specific, but rather specific to the usage of the invariant globalization mode. Alpine docker image just happens to have it set by default to save space (the ICU libraries are really large), but the globalization should work on Alpine just fine if enabled and ICU is installed.

**Comment by tarekgh** [comment]
I'll take a look.

**Comment by kasper3** [comment]
You are right, i just tested on Alpine and Debian

Alpine: `docker run -it microsoft/dotnet:2.1-sdk-alpine`
Debian: `docker run -it microsoft/dotnet:2.1-sdk`

both have exactly the same result

Setup:

```sh

# in container
dotnet new console -n test
cat > test/Program.cs <<-"EOF"
using System;
using System.Collections;

namespace hashtable
{
    class Program
    {
        static void Main(string[] args)
        {
            Hashtable h = new Hashtable(StringComparer.CurrentCultureIgnoreCase);

            h["Foo"] = "bar";

            Console.WriteLine(h.ContainsKey("foo"));
            Console.WriteLine("Hello World!");
        }
    }
}
EOF
```

Test:

```sh
dotnet run -p test
# works
```

but

```sh
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true dotnet run -p test
# throws
```
