### ISSUE TITLE
A callback was made on a garbage collected delegate of type 'System.Reflection.Emit.ILGeneration.Tests!System.Reflection.Emit.Tests.ILGeneratorEmit4+StringReverseCdecl::Invoke'.

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#28063]
OSX10.12
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180314.02/workItem/System.Reflection.Emit.ILGeneration.Tests/wilogs

```
2018-03-14 06:18:11,331: INFO: proc(54): run_and_log_output: Output: Discovering: System.Reflection.Emit.ILGeneration.Tests
2018-03-14 06:18:11,481: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Reflection.Emit.ILGeneration.Tests
2018-03-14 06:18:11,545: INFO: proc(54): run_and_log_output: Output: Starting:    System.Reflection.Emit.ILGeneration.Tests
2018-03-14 06:18:11,759: INFO: proc(54): run_and_log_output: Output: FailFast:
2018-03-14 06:18:11,760: INFO: proc(54): run_and_log_output: Output: A callback was made on a garbage collected delegate of type 'System.Reflection.Emit.ILGeneration.Tests!System.Reflection.Emit.Tests.ILGeneratorEmit4+StringReverseCdecl::Invoke'.
2018-03-14 06:18:11,760: INFO: proc(54): run_and_log_output: Output: 
2018-03-14 06:18:11,760: INFO: proc(54): run_and_log_output: Output:    at T.F(IntPtr, System.String)
2018-03-14 06:18:11,760: INFO: proc(54): run_and_log_output: Output:    at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean, Boolean)
2018-03-14 06:18:11,761: INFO: proc(54): run_and_log_output: Output:    at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
2018-03-14 06:18:11,761: INFO: proc(54): run_and_log_output: Output:    at System.Reflection.Emit.Tests.ILGeneratorEmit4.TestEmitCalliNonBlittable()
2018-03-14 06:18:11,761: INFO: proc(54): run_and_log_output: Output:    at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean, Boolean)
2018-03-14 06:18:11,761: INFO: proc(54): run_and_log_output: Output:    at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
2018-03-14 06:18:11,761: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestInvoker`1+<>c__DisplayClass46_1+<<InvokeTestMethodAsync>b__1>d[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
2018-03-14 06:18:11,762: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.TestInvoker`1+<>c__DisplayClass46_1+<<InvokeTestMethodAsync>b__1>d[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.2.0.3300, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<<InvokeTestMethodAsync>b__1>d<System.__Canon> ByRef)
2018-03-14 06:18:11,762: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.TestInvoker`1+<>c__DisplayClass46_1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<InvokeTestMethodAsync>b__1()
2018-03-14 06:18:11,762: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.ExecutionTimer+<AggregateAsync>d__4.MoveNext()
2018-03-14 06:18:11,763: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.ExecutionTimer+<AggregateAsync>d__4, xunit.execution.dotnet, Version=2.2.0.3300, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<AggregateAsync>d__4 ByRef)
2018-03-14 06:18:11,763: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.ExecutionTimer.AggregateAsync(System.Func`1<System.Threading.Tasks.Task>)
2018-03-14 06:18:11,763: INFO: proc(54): run_and_log_output: Output:    at Xunit.Sdk.ExceptionAggregator+<RunAsync>d__9.MoveNext()
```

**Comment by danmosemsft** [comment]
cc @petarpetrovt

**Comment by jkotas** [comment]
Need to add `GC.KeepAlive(...)` to keep the delegate alive during the call to dynamic method.

**Comment by jkotas** [comment]
#28092
