### ISSUE TITLE
Enumeration.ExampleTests.TestGetFilesWithExtensions failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#28096]
https://mc.dot.net/#/user/jkotas/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/a327a1bfaf988ecb8a45dc6b61462ada4f1af52d/workItem/System.IO.FileSystem.Tests/analysis/xunit/System.IO.Tests.Enumeration.ExampleTests~2FTestGetFilesWithExtensions
```
OSX.1012.Amd64.Open-Debug-x64
Unhandled Exception of Type Xunit.Sdk.EqualException
Message :
Assert.Equal() Failure
Expected: SelectIPartitionIterator<String, String> [\"file.one\", \"file.three\"]
Actual:   SelectIPartitionIterator<String, String> [\"file.one\", \"file.three\"]
Stack Trace :
   at System.IO.Tests.FSAssert.EqualWhenOrdered[T](IEnumerable`1 expected, IEnumerable`1 actual) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.IO.FileSystem/tests/FSAssert.cs:line 70
   at System.IO.Tests.Enumeration.ExampleTests.TestGetFilesWithExtensions() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.IO.FileSystem/tests/Enumeration/ExampleTests.netcoreapp.cs:line 70
```
cc: @JeremyKuhne

**Comment by danmosemsft** [comment]
Curious as they look rather equal. BTW what does the SElect() here achieve?
```
        public static void EqualWhenOrdered<T>(IEnumerable<T> expected, IEnumerable<T> actual)
        {
            Assert.Equal(expected.OrderBy(e => e).Select(o => o), actual.OrderBy(a => a).Select(o => o));
        }
```

**Comment by JeremyKuhne** [comment]
Couldn't get a repro for this. Closing.
