### ISSUE TITLE
CI fail in System.Net.Http.Functional.Tests.HttpClientHandler_Authentication_Test.PreAuthenticate_FirstRequestNoHeader_SecondRequestVariousStatusCodes_ThirdRequestPreauthenticates

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#28122]
## Failure details

```
Unhandled Exception of Type System.Net.Http.HttpRequestException
Message :
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response

 at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 479
   at System.Net.Http.Functional.Tests.HttpClientHandler_Authentication_Test.<>c__DisplayClass12_0.<<PreAuthenticate_FirstRequestNoHeader_SecondRequestVariousStatusCodes_ThirdRequestPreauthenticates>b__0>d.MoveNext() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Authentication.cs:line 307
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass11_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in D:\j\workspace\windows-TGrou---74aa877a\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in D:\j\workspace\windows-TGrou---74aa877a\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 67
   at System.Net.Http.Functional.Tests.HttpClientHandler_Authentication_Test.PreAuthenticate_FirstRequestNoHeader_SecondRequestVariousStatusCodes_ThirdRequestPreauthenticates(HttpStatusCode statusCode) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Authentication.cs:line 297
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Environment.get_StackTrace() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\src\System\Environment.cs:line 146
   at System.Runtime.ExceptionServices.ExceptionStackTrace.AddCurrentStack(Exception exception) in D:\j\workspace\windows-TGrou---74aa877a\src\Common\src\System\Runtime\ExceptionServices\ExceptionStackTrace.cs:line 23
   at System.Net.Http.WinHttpException.CreateExceptionUsingError(Int32 error) in D:\j\workspace\windows-TGrou---74aa877a\src\Common\src\System\Net\Http\WinHttpException.cs:line 56
   at System.Net.Http.WinHttpRequestCallback.OnRequestError(WinHttpRequestState state, WINHTTP_ASYNC_RESULT asyncResult) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs:line 324
   at System.Net.Http.WinHttpRequestCallback.RequestCallback(IntPtr handle, WinHttpRequestState state, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs:line 104
   at System.Net.Http.WinHttpRequestCallback.WinHttpCallback(IntPtr handle, IntPtr context, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs:line 47
--- End of stack trace from AddCurrentStack ---
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in D:\j\workspace\windows-TGrou---74aa877a\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs:line 62
   at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 856
```

## History of failures

Date | Build | Details
-- | -- | --
2018/3/15 | de2b82fe34b19d1faa8eb45f0a180f80d932bd3a | [link](https://mc.dot.net/#/user/tarekgh/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/de2b82fe34b19d1faa8eb45f0a180f80d932bd3a/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Authentication_Test~2FPreAuthenticate_FirstRequestNoHeader_SecondRequestVariousStatusCodes_ThirdRequestPreauthenticates(statusCode:%20ResetContent))
2018/3/17 | b0e34ea8071b37ab68b244c977e0882ed291a821 | [link](https://mc.dot.net/#/user/matekm/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/b0e34ea8071b37ab68b244c977e0882ed291a821/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Authentication_Test~2FPreAuthenticate_FirstRequestNoHeader_SecondRequestVariousStatusCodes_ThirdRequestPreauthenticates(statusCode:%20NoContent))

**Comment by davidsh** [comment]
This test is using the loopback server.  And this test is a recently new test.

I suspect there is a bug in the test loopback server.

cc: @karelz @stephentoub

**Comment by stephentoub** [comment]
David, most (though not all) of these kinds of errors I've seen recently have come from WinHttpHandler, very frequently on Win7 (though this one was Win10). Is there something that makes that implementation more sensitive?

**Comment by davidsh** [comment]
Probably because Windows 7 WinHTTP has more bugs in it that were fixed in later versions.

If we wanted to diagnose this error:

```
---- System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response
```

then we would need to get low-level traces to send to the WinHTTP team. In the past when we have done that, it usually was a bug in that Windows OS version but fixed in a later version.

**Comment by stephentoub** [comment]
> I suspect there is a bug in the test loopback server.

Has it failed anywhere other than with WinHttpHandler?  Seems more likely it's an issue with WinHttpHandler.

**Comment by davidsh** [comment]
>Has it failed anywhere other than with WinHttpHandler? Seems more likely it's an issue with WinHttpHandler.

Could be. Based on the latest conversations and with #28213 perhaps it is an issue again with connection re-use logic in WinHTTP.

**Comment by stephentoub** [comment]
This particular failure is a combination of what appears to be a race condition in winhttp as well as the test doing something that the RFC says it shouldn't.  Putting up a fix.
