### ISSUE TITLE
System.Net.Http.Functional.Tests Assertion Failed - We should only be here if cancellation was requested

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#28133]
From https://github.com/dotnet/corefx/pull/28080 on OSX.1013.Amd64.Open:Debug-x64
https://mc.dot.net/#/user/ahsonkhan/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/be5aaa6aafd5a19086974af807cb66588586e825/workItem/System.Net.Http.Functional.Tests/wilogs

```text
2018-03-15 20:58:52,865: INFO: proc(54): run_and_log_output: Output:    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandlerTest.Ctor_ExpectedDefaultPropertyValues_UapPlatform [SKIP]
2018-03-15 20:58:52,865: INFO: proc(54): run_and_log_output: Output:       Condition(s) not met: \"IsUap\"
2018-03-15 20:58:53,369: INFO: proc(54): run_and_log_output: Output: Assertion Failed
2018-03-15 20:58:53,369: INFO: proc(54): run_and_log_output: Output: We should only be here if cancellation was requested.
2018-03-15 20:58:53,369: INFO: proc(54): run_and_log_output: Output: 
2018-03-15 20:58:53,370: INFO: proc(54): run_and_log_output: Output:    at System.Net.Http.CurlHandler.CurlResponseStream.<>c.<ReadAsync>b__30_1(Object s2) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Http/src/System/Net/Http/CurlHandler/CurlHandler.CurlResponseMessage.cs:line 344
2018-03-15 20:58:53,370: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /Users/buildagent/agent/_work/147/s/src/mscorlib/shared/System/Threading/ExecutionContext.cs:line 166
2018-03-15 20:58:53,371: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Threading/Tasks/Task.cs:line 2440
2018-03-15 20:58:53,371: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ThreadPoolWorkQueue.Dispatch() in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Threading/ThreadPool.cs:line 588
2018-03-15 20:58:56,769: INFO: proc(54): run_and_log_output: Output: /Users/dotnet-bot/dotnetbuild/work/9bbf5ba5-b5a1-4f68-9dea-4a703567af54/Work/cb238724-1a11-4068-a19a-892967c9bc11/Unzip/RunTests.sh: line 87: 67860 Abort trap: 6           (core dumped) $RUNTIME_PATH/dotnet xunit.console.netcore.exe System.Net.Http.Functional.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonosxtests -notrait category=OuterLoop -notrait category=failing
2018-03-15 21:01:35,012: INFO: proc(54): run_and_log_output: Output: processing dump file /Users/dotnet-bot/dotnetbuild/work/9bbf5ba5-b5a1-4f68-9dea-4a703567af54/Work/cb238724-1a11-4068-a19a-892967c9bc11/Unzip/core.67860
2018-03-15 21:01:35,013: INFO: proc(54): run_and_log_output: Output: creating dumpling dump f8701e01613c9f7a2232ed89cd62ac0334dce3fa
```

@davidsh, @wfurt, @stephentoub

**Comment by stephentoub** [comment]
This has been happening a fair amount, especially on macOS for some reason, e.g.
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/4a293fce894b2511ea4d66022936146a33157ffa/workItem/System.Net.Http.Functional.Tests/wilogs
https://mc.dot.net/#/user/AlexRadch/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/b4628a601cd8a421e04486e64979579e7ea54fc2/workItem/System.Net.Http.Functional.Tests/wilogs
