### ISSUE TITLE
Microsoft.Win32.Registry.Tests fail if machine is dirty

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#2819]
I hit this failure after breaking into the tests. 
```
Starting:    Microsoft.Win32.Registry.Tests
     Microsoft.Win32.RegistryTests.RegistryKey_CreateSubKey_str.NegativeTests [  FAIL]
        Assert.Null() Failure
        Expected: (null)
        Actual:   HKEY_CURRENT_USER\REG_TEST_1
        Stack Trace:
           E:\dotnet-bot\corefx\src\Microsoft.Win32.Registry\tests\TestSubKey.cs(19,0): at Microsoft.Win32.RegistryTests.TestSubKey..ctor(String testKeyName)
           E:\dotnet-bot\corefx\src\Microsoft.Win32.Registry\tests\RegistryKey\RegistryKey_CreateSubKey_str.cs(16,0): at Microsoft.Win32.RegistryTests.RegistryKey_CreateSubKey_str..ctor()
```
The only way to workaround was to manually clean up the key the tests left behind.
The tests should ensure a clean state before running.

**Comment by stephentoub** [comment]
This is causing a large number of failures now in CI.  I'm working on a fix.
