### ISSUE TITLE
System.Net.Sockets tests cause exception on threadpool thread

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#28202]
The assert on src/.System.Net.Sockets/tests/FunctionalTests/Shutdown.cs:line 22 will cause an exception to be thrown on a threadpool thread. When it fires it will take down the whole test library.

Consider either marshaling somehow back to the test, or using RemoteInvoke for all tests that lead to this codepath.

```c#
        private static void OnOperationCompleted(object sender, SocketAsyncEventArgs args)
        {
            Assert.Equal(SocketError.Success, args.SocketError);
```
```
2018-03-19 13:18:57,213: INFO: proc(54): run_and_log_output: Output: Unhandled Exception: Xunit.Sdk.EqualException: Assert.Equal() Failure
2018-03-19 13:18:57,213: INFO: proc(54): run_and_log_output: Output: Expected: Success
2018-03-19 13:18:57,213: INFO: proc(54): run_and_log_output: Output: Actual:   OperationAborted
2018-03-19 13:18:57,214: INFO: proc(54): run_and_log_output: Output:    at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
2018-03-19 13:18:57,214: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.Tests.Shutdown.OnOperationCompleted(Object sender, SocketAsyncEventArgs args) in /root/corefx-1491859/src/System.Net.Sockets/tests/FunctionalTests/Shutdown.cs:line 22
2018-03-19 13:18:57,214: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /root/coreclr/src/mscorlib/shared/System/Threading/ExecutionContext.cs:line 166
2018-03-19 13:18:57,214: INFO: proc(54): run_and_log_output: Output: --- End of stack trace from previous location where exception was thrown ---
2018-03-19 13:18:57,215: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /root/coreclr/src/mscorlib/shared/System/Threading/ExecutionContext.cs:line 166
2018-03-19 13:18:57,215: INFO: proc(54): run_and_log_output: Output: --- End of stack trace from previous location where exception was thrown ---
2018-03-19 13:18:57,215: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ThreadPoolWorkQueue.Dispatch() in /root/coreclr/src/mscorlib/src/System/Threading/ThreadPool.cs:line 588
```

Example - this took out all S.Net.Sockets tests on Alpine.

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180319.04/workItem/System.Net.Sockets.Tests/wilogs

**Comment by danmosemsft** [comment]
@karelz we need to fix this first to get any actual results for sockets tests on Alpine. Could someone look?

**Comment by stephentoub** [comment]
@danmosemsft, this always fails on Alpine?

**Comment by karelz** [comment]
How often does it fail this way? How many runs did we have on Alpine?

**Comment by danmosemsft** [comment]
It is consistently happening

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180319.01/workItem/System.Net.Sockets.Tests/wilogs
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180319.04/workItem/System.Net.Sockets.Tests/wilogs

Note some tests are running (upstream of this crash) but no test results are shown. Looks like they are broken by https://github.com/dotnet/corefx/issues/28203

**Comment by wfurt** [comment]
I'll take a look @danmosemsft

**Comment by wfurt** [comment]
all sockets tests passed after #28203 was fixed. There are still failing HTTP tests and that should be investigated separately.
