### ISSUE TITLE
UnauthorizedAccessException in System.ServiceModel.Syndication tests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#28302]
https://mc.dot.net/#/user/jkotas/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/bd6027746f2fd0c5515fdf8abb2fcecf3c25286a/workItem/System.ServiceModel.Syndication.Tests/analysis/xunit/System.ServiceModel.Syndication.Tests.BasicScenarioTests~2FRssFeedPositiveTest
```
Windows.7.Amd64.Open-x64-Debug
Unhandled Exception of Type System.UnauthorizedAccessException
Message :
System.UnauthorizedAccessException : Access to the path 'C:\\Users' is denied.
Stack Trace :
   at System.IO.FileSystem.DeleteFile(String fullPath) in D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.FileSystem\src\System\IO\FileSystem.Windows.cs:line 170
   at System.IO.File.Delete(String path) in D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.FileSystem\src\System\IO\File.cs:line 102
   at System.ServiceModel.Syndication.Tests.BasicScenarioTests.ReadWriteSyndicationFeed(String file, Func`2 feedFormatter, List`1 allowableDifferences, Action`1 verifySyndicationFeedRead) in D:\j\workspace\windows-TGrou---74aa877a\src\System.ServiceModel.Syndication\tests\BasicScenarioTests.cs:line 550
   at System.ServiceModel.Syndication.Tests.BasicScenarioTests.RssFeedPositiveTest() in D:\j\workspace\windows-TGrou---74aa877a\src\System.ServiceModel.Syndication\tests\BasicScenarioTests.cs:line 398
```

**Comment by danmosemsft** [comment]
Presumably #28240
