### ISSUE TITLE
PEReaderTests.GetSectionData_Loaded failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#28309]
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/ee4cab88df3d975a6f9cee26cd2c7b916d3b450e/workItem/System.Reflection.Metadata.Tests/analysis/xunit/System.Reflection.PortableExecutable.Tests.PEReaderTests~2FGetSectionData_Loaded
```
Windows.7.Amd64.Open-x86-Release
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Assert.True() Failure
Expected: True
Actual:   False
Stack Trace :
   at System.Reflection.Metadata.Tests.LoaderUtilities.LoadPEAndValidate(Byte[] peImage, Action`1 validator, Boolean useStream) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Reflection.Metadata\tests\TestUtilities\LoaderUtilities.cs:line 25
   at System.Reflection.PortableExecutable.Tests.PEReaderTests.GetSectionData_Loaded() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Reflection.Metadata\tests\PortableExecutable\PEReaderTests.cs:line 237
```

**Comment by stephentoub** [comment]
Haven't seen this fail in a year.  Closing.
