### ISSUE TITLE
TimesIncludeMillisecondPart_Linux test failing in CI on Ubuntu

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#28342]
From https://github.com/dotnet/corefx/pull/28294
System.IO.Tests.FileInfo_GetSetTimes/TimesIncludeMillisecondPart_Linux
https://mc.dot.net/#/user/ahsonkhan/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/a319af0f981c27fd4bd680b6a545d44dc42fbbbc/workItem/System.IO.FileSystem.Tests/analysis/xunit/System.IO.Tests.FileInfo_GetSetTimes~2FTimesIncludeMillisecondPart_Linux

Ubuntu.1404.Amd64.Open-x64-Release
```text
Unhandled Exception of Type Xunit.Sdk.AllException
Message :
Assert.All() Failure: 1 out of 6 items in the collection did not pass.
[1]: Xunit.Sdk.NotEqualException: Assert.NotEqual() Failure
     Expected: Not 0
     Actual:   0
        at Xunit.Assert.NotEqual[T](T expected, T actual, IEqualityComparer`1 comparer)
        at System.IO.Tests.BaseGetSetTimes`1.<>c__DisplayClass9_0.<TimesIncludeMillisecondPart_Linux>b__0(TimeFunction function) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.IO.FileSystem/tests/Base/BaseGetSetTimes.cs:line 108
        at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action)
```

cc @JeremyKuhne

**Comment by ahsonkhan** [comment]
cc @jkotas, related to https://github.com/dotnet/corefx/pull/28242?

**Comment by jkotas** [comment]
cc @danmosemsft

**Comment by danmosemsft** [comment]
#27662
