### ISSUE TITLE
System.Data.Tests.DataTableTest3/XmlSchemaTest3 failing in CI with UnauthorizedAccessException

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#28354]
From https://github.com/dotnet/corefx/pull/28350
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/f1982993db81bc168e62e059516816b78af59bb7/workItem/System.Data.Common.Tests/analysis/xunit/System.Data.Tests.DataTableTest3~2FXmlSchemaTest3

Windows.10.Amd64.Open-x64-Debug
```text
Unhandled Exception of Type System.AggregateException
Message :
System.AggregateException : One or more errors occurred. (Could not find a part of the path 'C:\\Users\\'.) (Access to the path 'C:\\Users\\' is denied.)
---- System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\\Users\\'.
---- System.UnauthorizedAccessException : Access to the path 'C:\\Users\\' is denied.
Stack Trace :

----- Inner Stack Trace #1 (System.IO.DirectoryNotFoundException) -----
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle) in E:\A\_work\942\s\src\mscorlib\shared\System\IO\FileStream.Windows.cs:line 1650
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options) in E:\A\_work\942\s\src\mscorlib\shared\System\IO\FileStream.Win32.cs:line 42
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) in E:\A\_work\942\s\src\mscorlib\shared\System\IO\FileStream.cs:line 230
   at System.IO.FileStream..ctor(String path, FileMode mode) in E:\A\_work\942\s\src\mscorlib\shared\System\IO\FileStream.cs:line 164
   at System.Data.Tests.DataTableTest3.XmlSchemaTest3() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Data.Common\tests\System\Data\DataTableTest3.cs:line 512
----- Inner Stack Trace #2 (System.UnauthorizedAccessException) -----
   at System.IO.FileSystem.DeleteFile(String fullPath) in D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.FileSystem\src\System\IO\FileSystem.Windows.cs:line 170
   at System.IO.File.Delete(String path) in D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.FileSystem\src\System\IO\File.cs:line 102
   at System.Data.Tests.DataTableTest3.Dispose() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Data.Common\tests\System\Data\DataTableTest3.cs:line 48
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 76
```

Also System.Data.Tests.DataTableTest3/XmlSchemaTest7
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/f1982993db81bc168e62e059516816b78af59bb7/workItem/System.Data.Common.Tests/analysis/xunit/System.Data.Tests.DataTableTest3~2FXmlSchemaTest7

```text
Unhandled Exception of Type System.UnauthorizedAccessException
Message :
System.UnauthorizedAccessException : Access to the path 'C:\\Users\\DotNetTestRunner\\AppData\\' is denied.
Stack Trace :
   at System.IO.FileSystem.DeleteFile(String fullPath) in D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.FileSystem\src\System\IO\FileSystem.Windows.cs:line 170
   at System.IO.File.Delete(String path) in D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.FileSystem\src\System\IO\File.cs:line 102
   at System.Data.Tests.DataTableTest3.Dispose() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Data.Common\tests\System\Data\DataTableTest3.cs:line 48
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 76
```

cc @divega, @saurabh500, @stephentoub

**Comment by stephentoub** [comment]
I don't believe this is specific to these tests.  We've seen the same "Access to path ..." errors in other unrelated tests recently, e.g.
https://github.com/dotnet/corefx/issues/28338
https://github.com/dotnet/corefx/issues/28240
https://github.com/dotnet/corefx/issues/28191

@dotnet/dnceng, are you aware of issues here?
