### ISSUE TITLE
When the System.Reflection.DispathProxy subclass's access modifier is not public it throw Access is denied

### ISSUE THREAD

**Issue by Mutuduxf** [dotnet/corefx#28403]
The repo is [here](https://github.com/Mutuduxf/DispatchProxyDemo)
>    at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
   at System.Reflection.DispatchProxyGenerator.ProxyBuilder.CreateType()
   at System.Reflection.DispatchProxyGenerator.GenerateProxyType(Type baseType, Type interfaceType)
   at System.Reflection.DispatchProxyGenerator.GetProxyType(Type baseType, Type interfaceType)
   at System.Reflection.DispatchProxyGenerator.CreateProxyInstance(Type baseType, Type interfaceType)
   at System.Reflection.DispatchProxy.Create[T,TProxy]()
   at DispatchProxyDemo.DynamicProxy.<>c__1`1.<Proxy>b__1_0(Type key) in C:\Users\aeond\Desktop\GitHub\DispatchProxyDemo\DispatchProxyDemo\DynamicProxy.cs:line 15
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at DispatchProxyDemo.DynamicProxy.Proxy[T]() in C:\Users\aeond\Desktop\GitHub\DispatchProxyDemo\DispatchProxyDemo\DynamicProxy.cs:line 15
   at DispatchProxyDemo.Program.Main(String[] args) in C:\Users\aeond\Desktop\GitHub\DispatchProxyDemo\DispatchProxyDemo\Program.cs:line 11

**Comment by karelz** [comment]
Simplified repro - it repros on .NET Core 2.0. I wonder if it is by design.

```c#
using System.Reflection;

public class DynamicProxy
{
    public static T Proxy<T>() => DispatchProxy.Create<T, InvokeProxy<T>>();

    // If the access modifier is private/protected/internal it will throw the exception unless public.
    private class InvokeProxy<T> : DispatchProxy
    {
        protected override object Invoke(MethodInfo targetMethod, object[] args) => null;
    }
}

public interface IService { }

class Program
{
    static void Main()
    {
        DynamicProxy.Proxy<IService>();
    }
}
```

**Comment by ggeurts** [comment]
I just ran into the same issue this week.

**Comment by ElderJames** [comment]
I have this issue too.

**Comment by AtsushiKan** [comment]
@joshfree any chance we could get DispatchProxy its own owner? This feature has nothing to do with Reflection - it just got thrown into the Sytem.Reflection for some reason.

**Comment by steveharter** [comment]
Proposing to move the to future.

**Comment by ltrzesniewski** [comment]
Here's a workaround for `internal` types; 

```C#
[assembly: InternalsVisibleTo("ProxyBuilder")]
```

This will fail if the implementation ever changes the `ProxyBuilder` assembly name.
