### ISSUE TITLE
[Arm64] System.Globalization.Tests.InvariantModeTests 79 tests are failing

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/corefx#28435]
```
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: Invariant.Tests
Discovered:  Invariant.Tests
Starting:    Invariant.Tests
```
7 x
```
   System.Globalization.Tests.InvariantModeTests.TestIndexOf(source: \"Hi\", value: \"I\", startIndex: 0, count: 2, options: IgnoreCase, result: 1) [FAIL]
      Assert.Equal() Failure
      Expected: 1
      Actual:   -1
      Stack Trace:
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Globalization/tests/Invariant/InvariantMode.cs(656,0): at System.Globalization.Tests.InvariantModeTests.TestIndexOf(String source, String value, Int32 startIndex, Int32 count, CompareOptions options, Int32
 result)
```
1x
```
   System.Globalization.Tests.InvariantModeTests.TestEnum [FAIL]
      Assert.Equal() Failure
      Expected: CultureInfo[] []
      Actual:   CultureInfo[] [, af, af-NA, af-ZA, agq, ...]
```
5x
```
   System.Globalization.Tests.InvariantModeTests.TestCultureData(cultureName: \"en-US\") [FAIL]
      Assert.Equal() Failure
                 ↓ (pos 1)
      Expected: AD
      Actual:   A
                 ↑ (pos 1)
      Stack Trace:
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Globalization/tests/Invariant/InvariantMode.cs(492,0): at System.Globalization.Tests.InvariantModeTests.TestCultureData(String cultureName)
```
5x
```
   System.Globalization.Tests.InvariantModeTests.TestSortVersion(cultureName: \"en-US\") [FAIL]
      Assert.Equal() Failure
      Expected: SortVersion { FullVersion = 0, SortId = 00000000-0000-0000-0000-00000000007f }
      Actual:   SortVersion { FullVersion = 14489, SortId = 00003899-0000-0000-0000-000000000409 }
```
8x
```
   System.Globalization.Tests.InvariantModeTests.TestNormalization(s: \"ﬁ\", form: FormKC) [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Globalization/tests/Invariant/InvariantMode.cs(753,0): at System.Globalization.Tests.InvariantModeTests.TestNormalization(String s, NormalizationForm form)
```
5x
```
   System.Globalization.Tests.InvariantModeTests.TestToLower(upper: \"THIS IS A LONGER TEST CASE\", lower: \"this is a longer test case\", result: True) [FAIL]
      Assert.Equal() Failure
      Expected: True
      Actual:   False
      Stack Trace:
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Globalization/tests/Invariant/InvariantMode.cs(719,0): at System.Globalization.Tests.InvariantModeTests.TestToLower(String upper, String lower, Boolean result)
```
5x
```
   System.Globalization.Tests.InvariantModeTests.TestToUpper(lower: \"this is a longer test case\", upper: \"THIS IS A LONGER TEST CASE\", result: True) [FAIL]
      Assert.Equal() Failure
      Expected: True
      Actual:   False
      Stack Trace:
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Globalization/tests/Invariant/InvariantMode.cs(730,0): at System.Globalization.Tests.InvariantModeTests.TestToUpper(String lower, String upper, Boolean result)
```
...

**Comment by tarekgh** [comment]
Issue moved to [dotnet/coreclr #17210](https://github.com/dotnet/coreclr/issues/17210) via [**ZenHub**](https://www.zenhub.com/)
