### ISSUE TITLE
NamedPipeServerStream.EndWaitForConnection throws SocketException on x86/Linux

### ISSUE THREAD

**Issue by liserdarts** [dotnet/corefx#28448]
I've been running the same code one multiple platforms (amd64/Win 10, amd64/Debian 9, arm64/Rasbian, and x86/Debian 9). In every case making a call to NamedPipeServerStream.Dispose will cause EndWaitForConnection to throw ObjectDisposedException. However when I move the same dll to x86/Debian 9 it throws System.Net.Sockets.SocketException.

Unexpected exception in background thread caused a crash.

> Unhandled Exception: System.Net.Sockets.SocketException: Operation canceled
>    at System.IO.Pipes.NamedPipeServerStream.<<WaitForConnectionAsync>g__WaitForConnectionAsyncCore|23_0>d.MoveNext() in /home/nick/Documents/builds/branches/corefx/src/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.Unix.cs:line 80
>    at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult) in /home/nick/Documents/builds/branches/corefx/src/Common/src/System/Threading/Tasks/TaskToApm.cs:line 87
>    at System.IO.Pipes.NamedPipeServerStream.EndWaitForConnection(IAsyncResult asyncResult) in /home/nick/Documents/builds/branches/corefx/src/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.cs:line 155

I built from the v2.1-preview1 branch for x86/Linux using the process outlined here.
https://github.com/liserdarts/dotnetcore-build-x86-Linux

**Comment by liserdarts** [comment]
After having time to think about this more, I realised that I was running the v2.1-preview1 code on x86/Linux and 2.0.5 everywhere else. So I made a build of the v2.0.5 branch and installed that on my x86/Linux machine. Then the exception went back to an ObjectDisposedException and was caught by my original code.

So it turns out this has nothing to do with the platform but is a difference between the v2.0.5 branch and v2.1-preview. I don't know where v2.0.6 falls.

So I don't know if this should even be classified as an issue anymore. It did cause an unhandled exception for me but you could reasonably argue that was my own fault. At this point I would have no objection if this issue was just closed. I'll leave it up to a contributor to decide.

**Comment by stephentoub** [comment]
I don't know that we consistently threw ODE for this case previously (disposing while in use is generally considered bad, and as such there are likely race conditions), but if we did and now we're throwing something else, that's something to investigate.

**Comment by liserdarts** [comment]
>disposing while in use is generally considered bad

Agreed, but in this case the call to EndWaitForConnection is made before a call to Dispose. EndWaitForConnection is a blocking call made by a background thread. The only other way I know of to cancel the call is with the Close function, which includes this bit of information.

>Instead of calling this method, ensure that the stream is properly disposed.

I don't know what other options there are. I started doing this after seeking advice on how to properly shutdown NamedPipeServerStream. And I found [What is a good way to shutdown Threads blocked on NamedPipeServer#WaitForConnection?](https://stackoverflow.com/questions/607872/what-is-a-good-way-to-shutdown-threads-blocked-on-namedpipeserverwaitforconnect)

>This is what I received as a response from Kim Hamilton (BCL team)
>>The "right" way to do an interruptible WaitForConnection is to call BeginWaitForConnection, handle the new connection in the callback, and close the pipe stream to stop waiting for connections. If the pipe is closed, EndWaitForConnection will throw ObjectDisposedException which the callback thread can catch, clean up any loose ends, and exit cleanly.
>>We realize this must be a common question, so someone on my team is planning to blog about this soon

I can't find that blog post but I think I'm doing this correctly. Also I've been running automated tests  several times a day of my code doing this on different platforms, for about 60 days. It's been consistent up until this point.

And just to find out as much as I could I built the v2.0.6 branches for clr and fx to test with. It also throws ObjectDisposedException. So as much as I can tell SocketException begins at v2.1-preview1.

**Comment by karelz** [comment]
Can you post a minimal repro reproducing the exception change in 2.1 vs. 2.0?

**Comment by liserdarts** [comment]
>Can you post a minimal repro 
Sure will, as soon as I have time. Will probably get it done tonight.

**Comment by liserdarts** [comment]
Sorry for the delay. Had a family pet emergency with a sad ending.

Anyway I created [NamedPipeServerStreamTest](https://github.com/liserdarts/NamedPipeServerStreamTest). Check out [Output.md](https://github.com/liserdarts/NamedPipeServerStreamTest/blob/master/Output.md) for the output I get on different versions.

It turns out I was wrong again about the exceptions. I wasn't actually getting an ObjectDesposedException in 2.0.5, even though I had a try catch for it. However in 2.1 you can see in the output I am getting an ObjectDesposedException on one thread and SocketException on another. Both from EndWaitForConnection. I'm also occasionally getting a NullReferenceException from SocketAsyncContext.AsyncOperation called by the thread pool. I wasn't seeing that before creating this test program, but maybe I just hadn't been using named pipes on 2.1 long enough yet.

Let me know if there is anything else I can provide. I'm working on running this on some different platforms and I'll update [Output.md](https://github.com/liserdarts/NamedPipeServerStreamTest/blob/master/Output.md) when I do.

**Comment by karelz** [comment]
I would be curious in 2.1 behavior on supported OS (Windows or Linux amd64). If it is a regression on supported OS< we should look into it.

**Comment by liserdarts** [comment]
Is there an easy way to install 2.1 on either? Or would I have to build it myself?

**Comment by karelz** [comment]
You can use [2.1-Preview1](https://blogs.msdn.microsoft.com/dotnet/2018/02/27/announcing-net-core-2-1-preview-1/) (ideally with SocketsHttpHandler - see the env vars section for details) or [nightly builds](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md) (SocketsHttpHandler is default there).

**Comment by liserdarts** [comment]
The plot thickens.

I ran the program with 2.1-Preview1 on some of the same machines. On v2.1-preview1/Debian9/Amd64 I got a SocketException and a ObjectDisposedException. On v2.1-preview1/**Win10**/Amd64 it was just one ObjectDisposedException.

I updated [Output.md](https://github.com/liserdarts/NamedPipeServerStreamTest/blob/master/Output.md) whth the exact output.

I tried every combination of the COMPlus_UseManagedHttpClientHandler environment variable and System.Net.Http.UseManagedHttpClientHandler AppContext and it didn't ever make any differences. I even tried it on v2.1-preview1/Debian9/**x86**. Got the same result as before. (SocketException, ObjectDisposedException, then unhandled NullReferenceException and crash)

**Comment by karelz** [comment]
I am curious if the repro above: https://github.com/liserdarts/NamedPipeServerStreamTest is still a problem on latest (now released) 2.1 bits.

**Comment by liserdarts** [comment]
I just updated my Debian9/Amd64 machine to version 2.1.5 and ran the sample project again. And I got the same results that I did with v2.1-preview1.

I've updated the output file in that repository to include this information.
https://github.com/liserdarts/NamedPipeServerStreamTest/blob/master/Output.md#v21-preview1debian9amd64
