### ISSUE TITLE
CI Failure: System.Reflection.PortableExecutable.Tests.DebugDirectoryTests/EmbeddedPortablePdb_Loaded

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#28453]
Windows.7.Amd64.Open-x86-Release
```
Unhandled Exception of Type System.UnauthorizedAccessException
```
```
Message :
System.UnauthorizedAccessException : Access to the path
 'C:\\dotnetbuild\\work\\9e7c5e49-dfc1-4d7e-8b8d-35ba897ba718\\Work
 \\2cf7a7de-c1c5-4727-ad70-660d052b0b9e\\Unzip' is denied.
```
```
Stack Trace :
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
    in E:\A\_work\70\s\src\mscorlib\shared\System\IO\FileStream.Windows.cs:line 1650
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
    in E:\A\_work\70\s\src\mscorlib\shared\System\IO\FileStream.Win32.cs:line 42
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
    in E:\A\_work\70\s\src\mscorlib\shared\System\IO\FileStream.cs:line 230
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.IO.FileSystem\src\System\IO\File.cs:line 415
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
    in D:\j\workspace\windows-TGrou---f8ac6754\src\System.IO.FileSystem\src\System\IO\File.cs:line 406
   at System.IO.TempFile..ctor(String path, Int64 length)
    in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\IO\TempFile.cs:line 19
   at System.Reflection.Metadata.Tests.LoaderUtilities.LoadPEAndValidate(Byte[] peImage, Action`1 validator, Boolean useStream)
    in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Reflection.Metadata\tests\TestUtilities\LoaderUtilities.cs:line 17
   at System.Reflection.PortableExecutable.Tests.DebugDirectoryTests.EmbeddedPortablePdb_Loaded()
    in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Reflection.Metadata\tests\PortableExecutable\DebugDirectoryTests.cs:line 140
```

**Comment by benaadams** [comment]
Seen in https://github.com/dotnet/corefx/pull/25510#issuecomment-375945813

 https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netcoreapp+CGroup_Release+AGroup_x86+TestOuter_false_prtest/10601/

**Comment by danmosemsft** [comment]
I have seen the same symptom with unrelated tests...

**Comment by stephentoub** [comment]
https://github.com/dotnet/coreclr/pull/17148
