### ISSUE TITLE
[Desktop] FileStream.ReadAsync() fails with System.IO.IOException: The media is write protected.

### ISSUE THREAD

**Issue by twest820** [dotnet/corefx#28466]
This occurs sporadically when copying files from an SD card whose write protect tab is not engaged. The FileStream is the only handle opened on the file and is created using

    new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.Read, 1024 * 1024, FileOptions.Asynchronous | FileOptions.SequentialScan)

.NET 4.7.1, Windows 10 Fall Creators Update, Lenovo T440s built in Realtek PCI-E SD card reader with driver version 10.0.10125.21277. Some investigation shows the SD card is mounted read only in these cases, which is not expected and may signal an issue in Realtek's driver, but this doesn't explain why operations on a read only handle are failing because write permission is unavailable. There is a second concurrent task writing the data read to another file on an SSD but, for both tasks, the FileStreams are local.

    new FileStream(filePath, FileMode.Create, FileAccess.Write, FileShare.None, 1024 * 1024, FileOptions.Asynchronous | FileOptions.SequentialScan | FileOptions.WriteThrough);

The underlying native API is [SetFilePointerEx()](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365542.aspx). Since the two handles in use are distinct and used single threaded I don't see any obvious races in code review. It's possible the issue may be in native code under .NET and therefore external, but filing this for a look anyway.

Workaround: Copy files manually using FileExplorer. This issue also fails to reproduce with File.Copy().

    System.IO.IOException: The media is write protected.
    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
    at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
    at System.IO.FileStream.BeginReadCore(Byte[] bytes, Int32 offset, Int32 numBytes, AsyncCallback userCallback, Object stateObject, Int32 numBufferedBytesRead)
    at System.IO.FileStream.BeginReadAsync(Byte[] array, Int32 offset, Int32 numBytes, AsyncCallback userCallback, Object stateObject)
    at System.IO.FileStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
    at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
    at CritterShell.Images.FileCopy.<>c__DisplayClass7_0.<<StreamAsync>b__0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at CritterShell.Images.FileCopy.<StreamAsync>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at CritterShell.CopyCameraFiles.<>c__DisplayClass26_0.<ProcessRecord>b__1(String inputSubdirectoryPath, ParallelLoopState loopState)
    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
    --- End of inner exception stack trace ---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
    at CritterShell.CopyCameraFiles.<>c__DisplayClass26_0.<ProcessRecord>b__0()
    at System.Threading.Tasks.Task.Execute()
    ---> (Inner Exception #0) System.IO.IOException: The media is write protected.

    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
    at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
    at System.IO.FileStream.BeginReadCore(Byte[] bytes, Int32 offset, Int32 numBytes, AsyncCallback userCallback, Object stateObject, Int32 numBufferedBytesRead)
    at System.IO.FileStream.BeginReadAsync(Byte[] array, Int32 offset, Int32 numBytes, AsyncCallback userCallback, Object stateObject)
    at System.IO.FileStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
    at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
    at CritterShell.Images.FileCopy.<>c__DisplayClass7_0.<<StreamAsync>b__0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at CritterShell.Images.FileCopy.<StreamAsync>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at CritterShell.CopyCameraFiles.<>c__DisplayClass26_0.<ProcessRecord>b__1(String inputSubdirectoryPath, ParallelLoopState loopState)

**Comment by danmosemsft** [comment]
> the SD card is mounted read only in these cases, which is not expected and may signal an issue in Realtek's driver, but this doesn't explain why operations on a read only handle are failing because write permission is unavailable

IO isn't my area, but if the driver is buggy such that it mounts as read only, Occam's Razor might suggest it's somehow causing the read failures as well? Can you try a different driver?

**Comment by twest820** [comment]
10.0.10125.21277 is the most recent version signed by Microsoft hardware quality and is also the version available from Lenovo. Realtek's [driver package](www.realtek.com/Downloads/downloadsView.aspx?Langid=1&PNid=15&PFid=25&Level=4&Conn=3&DownTypeID=3&GetDown=false) may offer an update but, even if it resolves the issue on my test machine, asking customers to change out a driver isn't realistically something we can do (too complex, don't have admin, _etc_.). One action under the "it's the driver" hypothesis would be to check for a test hole in driver certification, which is presumably something someone internal to Microsoft would need to do.

On the .NET side I find it curious there's a call to seek the stream during sequential scan. It's possible there's an interop issue here raising a less than ideal error code.

**Comment by karelz** [comment]
Triage: Affects Desktop only. We don't do Desktop runs anymore. We do not track .NET Framework bugs on GitHub.
