### ISSUE TITLE
Uri.LocalPath in Unix when path contains '#'

### ISSUE THREAD

**Issue by pjanotti** [dotnet/corefx#28486]
During #28475 2 failures on Unix were detected: 

```
     System.Xml.Tests.XmlUriResolverTests.Resolving_LocalPath_Ok(baseUri: file:///home/pc/s/corefx/bin/tests/System.Xml.Misc.Tests/netcoreapp-Linux-Debug-x64/, path: \"/f#/t/ë/t#st.xml\") [FAIL]
        Assert.Equal() Failure
                    ↓ (pos 2)
        Expected: /f#/t/ë/t#st.xml
        Actual:   /f
                    ↑ (pos 2)
        Stack Trace:
           /home/pc/s/corefx/src/System.Private.Xml/tests/Misc/XmlUrlResolverTests.cs(29,0): at System.Xml.Tests.XmlUriResolverTests.Resolving_LocalPath_Ok(Uri baseUri, String path)
     System.Xml.Tests.XmlUriResolverTests.Resolving_LocalPath_Ok(baseUri: file:///home/pc/s/corefx/bin/tests/System.Xml.Misc.Tests/netcoreapp-Linux-Debug-x64/, path: \"/f#/ã/ë/tëst.xml\") [FAIL]
        Assert.Equal() Failure
                    ↓ (pos 2)
        Expected: /f#/ã/ë/tëst.xml
        Actual:   /f
                    ↑ (pos 2)
        Stack Trace:
           /home/pc/s/corefx/src/System.Private.Xml/tests/Misc/XmlUrlResolverTests.cs(29,0): at System.Xml.Tests.XmlUriResolverTests.Resolving_LocalPath_Ok(Uri baseUri, String path)
  Finished:    System.Xml.Misc.Tests
```

See https://github.com/dotnet/corefx/pull/28475/files#r177095732 for more info

**Comment by rmkerr** [comment]
Moving this to future since it isn't a regression and we have no customer reports. I'm looking forward to diving into the wonderful world of OS specific path parsing at some point in the future, but today is not the day.

**Comment by rmkerr** [comment]
This is happening because of the Unix specific case for local path:
https://github.com/dotnet/corefx/blob/9e8d443ff78c4f0a9a6bedf7f95961cf96ceff0a/src/System.Private.Uri/src/System/Uri.cs#L1032-L1037
I'm going to investigate this more, but I think that the fix will likely just be to add UriComponents.Query and UriComponents.Fragment to that line.

**Comment by rmkerr** [comment]
The actual bug here is in the test itself. When you create an explicit file URI (ie, starting with "file://"), we expect special characters to be encoded. As seen in the traces, both failures are for explicit file paths:
```
baseUri: file:///home/pc/s/corefx/bin/tests/System.Xml.Misc.Tests/netcoreapp-Linux-Debug-x64/
```
The actual fix here is going to be to URL encode the special characters in the relative paths.

**Comment by pjanotti** [comment]
@rmkerr it isn't clear to me why it works on Windows, it seems that in this case the relative path is automatically encoded, see below (f# in net472).

```f#
> let cwd = System.Environment.CurrentDirectory;;
val cwd : string = "C:\Users\pauloja\AppData\Local\Temp"

> let b = new Uri(cwd, UriKind.Absolute);;
val b : Uri = file:///C:/Users/pauloja/AppData/Local/Temp

> let uri = new Uri(b, "f#/t/\u00eb/test.xml");;
val uri : Uri = file:///C:/Users/pauloja/AppData/Local/f%23/t/ë/test.xml
```

**Comment by pjanotti** [comment]
Hum interesting... on Linux it also encodes, but notice the last line "file://file:/"
```
cwd = "/home/pc/s/tmp/UriCheck"
b = file:///home/pc/s/tmp/UriCheck
uri = file://file:/home/pc/s/tmp/f%23/t/ë/test.xml
```

**Comment by rmkerr** [comment]
That is interesting, and warrants more investigation.

**Comment by krwq** [comment]
@rmkerr, ping on this 😄 Please unassign yourself if this is still an issue and you're not working on it

**Comment by rmkerr** [comment]
I'll unassign myself for now. It's an interesting issue, but I don't think it's pressing currently.

**Comment by krwq** [comment]
Thanks 😄
