### ISSUE TITLE
ProxyExplicitlyProvided_DefaultCredentials_Ignored failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#28537]
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/11a515405be4fbf1cfe81c881b2ed702594ed40c/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DefaultProxyCredentials_Test~2FProxyExplicitlyProvided_DefaultCredentials_Ignored
```
Windows.10.Amd64.Open-x64-Debug
Unhandled Exception of Type System.Exception
Message :
System.Exception : Unexpected EOF trying to read request header
Stack Trace :
   at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAsync() in D:\j\workspace\windows-TGrou---74aa877a\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 378
   at System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test.<>c__DisplayClass2_1.<<ProxyExplicitlyProvided_DefaultCredentials_Ignored>b__1>d.MoveNext() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.DefaultProxyCredentials.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in D:\j\workspace\windows-TGrou---74aa877a\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 117
   at System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test.<>c__DisplayClass2_0.<<ProxyExplicitlyProvided_DefaultCredentials_Ignored>b__0>d.MoveNext() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.DefaultProxyCredentials.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in D:\j\workspace\windows-TGrou---74aa877a\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 67
   at System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test.ProxyExplicitlyProvided_DefaultCredentials_Ignored() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.DefaultProxyCredentials.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
```
cc: @wfurt

**Comment by stephentoub** [comment]
Failed again here:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/68ada12d84ac2fe26b9fe46955506525a61b8a40/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DefaultProxyCredentials_Test~2FProxyExplicitlyProvided_DefaultCredentials_Ignored
```
Windows.10.Amd64.Open-x86-Release
Get Repro environment
Unhandled Exception of Type System.Exception
Message :
System.Exception : Unexpected EOF trying to read request header
Stack Trace :
   at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAsync() in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 375
   at System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test.<>c__DisplayClass2_1.<<ProxyExplicitlyProvided_DefaultCredentials_Ignored>b__1>d.MoveNext() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.DefaultProxyCredentials.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 117
   at System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test.<>c__DisplayClass2_0.<<ProxyExplicitlyProvided_DefaultCredentials_Ignored>b__0>d.MoveNext() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.DefaultProxyCredentials.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 67
   at System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test.ProxyExplicitlyProvided_DefaultCredentials_Ignored() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.DefaultProxyCredentials.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by stephentoub** [comment]
Again here:
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/78a4f426d6ef91aecd3da83efd8b5edb87d86667/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DefaultProxyCredentials_Test~2FProxyExplicitlyProvided_DefaultCredentials_Ignored

It looks like the test is written to expect that the client will always attempt to use the same connection again for subsequent authentication attempts.  If it doesn't, though, as is apparently happening once in a while with WinHttpHandler at least, the test fails because the server is trying to read data for the second request, but the client has closed that connection.  This could also manifest as a hang, if the client didn't close the first connection but tried to make the request on a second.
