### ISSUE TITLE
System.Net.Mail.Tests.SmtpClientTest.Send_SpecifiedPickupDirectory path issue

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/corefx#28558]
The failing test case below creates a directory in the /tmp filesystem with a hard coded name.  If the directory is owned by another user, the test will fails as shown in the log below.

```
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Net.Mail.Functional.Tests
Discovered:  System.Net.Mail.Functional.Tests
Starting:    System.Net.Mail.Functional.Tests
   System.Net.Mail.Tests.SmtpClientTest.Send_SpecifiedPickupDirectory [FAIL]
      System.UnauthorizedAccessException : Access to the path '/tmp/System.Net.Mail.Tests.SmtpClientTest/865ed06b-19de-41fe-a054-3c7f23bbbb1b' is denied.
      ---- System.IO.IOException : Permission denied
      Stack Trace:
            at System.IO.FileSystem.CreateDirectory(String fullPath)
            at System.IO.Directory.CreateDirectory(String path)
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Net.Mail/tests/Functional/SmtpClientTest.cs(41,0): at System.Net.Mail.Tests.SmtpClientTest.get_TempFolder()
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Net.Mail/tests/Functional/SmtpClientTest.cs(235,0): at System.Net.Mail.Tests.SmtpClientTest.Send_SpecifiedPickupDirectory()
         ----- Inner Stack Trace -----
         
Finished:    System.Net.Mail.Functional.Tests

=== TEST EXECUTION SUMMARY ===
   System.Net.Mail.Functional.Tests  Total: 170, Errors: 0, Failed: 1, Skipped: 0, Time: 20.193s
```

**Comment by danmosemsft** [comment]
@sdmaclea you mean you prevoiusly ran the test once as a different user, and that created and owned the folder?

Anyway this test should use FileCleanupTestBase's TestDirectory.

@Anipik could you please fix this? The line to change is `   _tempFolder = Path.Combine(Path.GetTempPath(), GetType().FullName, Guid.NewGuid().ToString());`

**Comment by sdmaclea** [comment]
> you mean you prevoiusly ran the test once as a different user, and that created and owned the folder?

Yes I ran as myself, then when CI ran the test failed
