### ISSUE TITLE
System.Xml.Xsl.XslTransformApi.Tests UnauthorizedAccessException

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/corefx#28559]
System.Xml.Xsl.XslTransformApi.Tests uses the hardcoded path `/tmp/XslTransformApi`

After the test has been run in an account with different privilege, the test will fail with UnauthorizedAccessException.

For example see partial log below.
```
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Xml.Xsl.XslTransformApi.Tests
Discovered:  System.Xml.Xsl.XslTransformApi.Tests
Starting:    System.Xml.Xsl.XslTransformApi.Tests
   System.Xml.Tests.CXmlResolverTest.TC_AbsolutePath_Transform(inputType: Reader, readerType: XmlValidatingReader, transformType: Reader, docType: XPathDocument) [FAIL]
      System.UnauthorizedAccessException : Access to the path '/tmp/XslTransformApi/xmlResolver_document_function.xml' is denied.
      ---- System.IO.IOException : Permission denied
      Stack Trace:
         /home/vmjenkins/workspace/Dotnet/build_and_test/src/mscorlib/shared/Interop/Unix/Interop.IOErrors.cs(23,0): at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
         /home/vmjenkins/workspace/Dotnet/build_and_test/src/mscorlib/shared/Microsoft/Win32/SafeHandles/SafeFileHandle.Unix.cs(41,0): at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
         /home/vmjenkins/workspace/Dotnet/build_and_test/src/mscorlib/shared/System/IO/FileStream.cs(230,0): at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
            at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Private.Xml/tests/Xslt/XslTransformApi/XSLTransform.cs(113,0): at System.Xml.Tests.XsltApiTestCaseBase.TestUsingTemporaryCopyOfResolverDocument(Action testAction)
         ----- Inner Stack Trace -----
         
   System.Xml.Tests.CXmlResolverTest.TC_AbsolutePath_Transform(inputType: Reader, readerType: XmlValidatingReader, transformType: Stream, docType: XPathDocument) [FAIL]
      System.UnauthorizedAccessException : Access to the path '/tmp/XslTransformApi/xmlResolver_document_function.xml' is denied.
      ---- System.IO.IOException : Permission denied
      Stack Trace:
         /home/vmjenkins/workspace/Dotnet/build_and_test/src/mscorlib/shared/Interop/Unix/Interop.IOErrors.cs(23,0): at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
         /home/vmjenkins/workspace/Dotnet/build_and_test/src/mscorlib/shared/Microsoft/Win32/SafeHandles/SafeFileHandle.Unix.cs(41,0): at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
         /home/vmjenkins/workspace/Dotnet/build_and_test/src/mscorlib/shared/System/IO/FileStream.cs(230,0): at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
            at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Private.Xml/tests/Xslt/XslTransformApi/XSLTransform.cs(113,0): at System.Xml.Tests.XsltApiTestCaseBase.TestUsingTemporaryCopyOfResolverDocument(Action testAction)
         ----- Inner Stack Trace -----
         
   System.Xml.Tests.CXmlResolverTest.TC_AbsolutePath_Transform(inputType: Reader, readerType: XmlValidatingReader, transformType: Writer, docType: XPathDocument) [FAIL]
      System.UnauthorizedAccessException : Access to the path '/tmp/XslTransformApi/xmlResolver_document_function.xml' is denied.
      ---- System.IO.IOException : Permission denied
      Stack Trace:
         /home/vmjenkins/workspace/Dotnet/build_and_test/src/mscorlib/shared/Interop/Unix/Interop.IOErrors.cs(23,0): at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
         /home/vmjenkins/workspace/Dotnet/build_and_test/src/mscorlib/shared/Microsoft/Win32/SafeHandles/SafeFileHandle.Unix.cs(41,0): at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
         /home/vmjenkins/workspace/Dotnet/build_and_test/src/mscorlib/shared/System/IO/FileStream.cs(230,0): at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
            at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Private.Xml/tests/Xslt/XslTransformApi/XSLTransform.cs(113,0): at System.Xml.Tests.XsltApiTestCaseBase.TestUsingTemporaryCopyOfResolverDocument(Action testAction)
         ----- Inner Stack Trace -----
         
```

**Comment by danmosemsft** [comment]
@Anipik same issue as #28558. However changing these crufty tests to derive from FileCleanupTestBase might be too much at the moment.

I suggest just changing the lines below so where it's currently using GetTempPath() + some hard coded string, it instead uses `Path.Combine(Path.GetTempPath(), GetType().Name + "_" + Path.GetRandomFileName());` which is what FileCleanupTestBase does.

```c#
C:\git\OTHER_COREFX\src\System.Private.Xml\tests\Xslt\XslCompiledTransformApi\XslCompiledTransform.cs:
  616:                 string tempPath = Path.GetTempPath();
  617                  string testFile = Path.Combine(tempPath, "xmlResolver_document_function.xml");
  ...
 2529:                 string tempPath = Path.GetTempPath();
 2530                  string testFile = Path.Combine(tempPath, "xmlResolver_document_function.xml");

C:\git\OTHER_COREFX\src\System.Private.Xml\tests\Xslt\XslCompiledTransformApi\XsltApiV2.cs:
   79:             string targetFile = Path.Combine(Path.GetTempPath(), "xmlResolver_document_function.xml");
   
src\System.Private.Xml\tests\Xslt\XslTransformApi\XSLTransform.cs:
   52:         private static readonly string s_temporaryResolverDocumentFullName = Path.Combine(Path.GetTempPath(), "XslTransformApi", XmlResolverDocumentName);
```
