### ISSUE TITLE
Test failure: System.Net.Security.Tests / ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#28556]
From https://github.com/dotnet/corefx/pull/28536

OSX.1012.Amd64.Open-x64-Debug
ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success

https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/ba6b4d98a37a5a76991d7f3a27320924081a7b24/workItem/System.Net.Security.Tests/analysis/xunit/System.Net.Security.Tests.ServerAsyncAuthenticateTest~2FServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success(serverProtocol:%20Tls11)
```text
Unhandled Exception of Type System.TimeoutException
Message :
System.TimeoutException : Task timed out after 240000
Stack Trace :
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, Int32 millisecondsTimeout) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 23
   at System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncSslHelper(SslProtocols clientSslProtocols, SslProtocols serverSslProtocols, Boolean expectedToFail) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Security/tests/FunctionalTests/ServerAsyncAuthenticateTest.cs:line 134
   at System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success(SslProtocols serverProtocol) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Security/tests/FunctionalTests/ServerAsyncAuthenticateTest.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
```

cc @davidsh

**Comment by davidsh** [comment]
Haven't seen this test failure since. Closing.
