### ISSUE TITLE
TestKeyAgreesRecipientIdType_RoundTrip failing in CI with WindowsCryptographicException on Win7

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#28584]
From https://github.com/dotnet/corefx/pull/28582
Windows.7.Amd64.Open-x64-Debug
https://mc.dot.net/#/user/benaadams/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/55bf1b5b0f691c9d6f223c60cbeb2fc46bf746cc/workItem/System.Security.Cryptography.Pkcs.Tests/analysis/xunit/System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.KeyAgreeRecipientInfoTests~2FTestKeyAgreesRecipientIdType_RoundTrip
```text
Unhandled Exception of Type Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException
Message :
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : An internal error occurred
Stack Trace :
   at Internal.Cryptography.Pal.Windows.PkcsPalWindows.EncodeHelpers.CreateCryptMsgHandleToEncode(CmsRecipientCollection recipients, Oid innerContentType, AlgorithmIdentifier contentEncryptionAlgorithm, X509Certificate2Collection originatorCerts, CryptographicAttributeObjectCollection unprotectedAttributes) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.Pkcs\src\Internal\Cryptography\Pal\Windows\PkcsPalWindows.Encrypt.cs:line 80
   at Internal.Cryptography.Pal.Windows.PkcsPalWindows.Encrypt(CmsRecipientCollection recipients, ContentInfo contentInfo, AlgorithmIdentifier contentEncryptionAlgorithm, X509Certificate2Collection originatorCerts, CryptographicAttributeObjectCollection unprotectedAttributes) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.Pkcs\src\Internal\Cryptography\Pal\Windows\PkcsPalWindows.Encrypt.cs:line 25
   at System.Security.Cryptography.Pkcs.EnvelopedCms.Encrypt(CmsRecipientCollection recipients) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.Pkcs\src\System\Security\Cryptography\Pkcs\EnvelopedCms.cs:line 109
   at System.Security.Cryptography.Pkcs.EnvelopedCms.Encrypt(CmsRecipient recipient) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.Pkcs\src\System\Security\Cryptography\Pkcs\EnvelopedCms.cs:line 92
   at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.KeyAgreeRecipientInfoTests.EncodeKeyAgreel(SubjectIdentifierType type) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.Pkcs\tests\EnvelopedCms\KeyAgreeRecipientInfoTests.cs:line 361
   at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.KeyAgreeRecipientInfoTests.TestKeyAgreesRecipientIdType_RoundTrip() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.Pkcs\tests\EnvelopedCms\KeyAgreeRecipientInfoTests.cs:line 66
```

cc @bartonjs

**Comment by bartonjs** [comment]
Without a repro it'll be really hard to tell why our call to Windows CMS returned "internal error" (probably NTE_FAIL).  I did some digging but didn't turn anything up.

I'm going to close this until a) it becomes habitual or b) someone lucks into a semi-stable repro.
