### ISSUE TITLE
CI tests failing with WindowsCryptographicException on Windows10

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#28631]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/a9913ea9b9bd68f11ca8707204b7d20a6ab98cf9/workItem/System.Net.Http.WinHttpHandler.Unit.Tests

Windows.10.Amd64.Open-x64-Debug
```text
Unhandled Exception of Type Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException
Message :
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : The profile for the user is a temporary profile
Stack Trace :
   at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 153
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 88
   at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 21
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs:line 81
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs:line 62
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2.cs:line 51
   at System.Net.Http.WinHttpHandlerUnitTests.ClientCertificateHelper..ctor() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http.WinHttpHandler\tests\UnitTests\ClientCertificateHelper.cs:line 14
   at System.Net.Http.WinHttpHandlerUnitTests.ClientCertificateScenarioTest.get_ValidClientCertificates() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Http.WinHttpHandler\tests\UnitTests\ClientCertificateScenarioTest.cs:line 18
```

cc @davidsh, @wfurt, @karelz, @danmosemsft

**Comment by davidsh** [comment]
cc: @bartonjs 

This looks like a regression in the X509Certificates component.  I think it should be investigated before by that team before moving it to Future.

**Comment by bartonjs** [comment]
Actually, that sounds like the hosting model for the test has changed.  But the results won't load right now, so it's hard to ask an intelligent question about what has changed.

**Comment by ahsonkhan** [comment]
> But the results won't load right now

The link to MC no longer points to the test failure. I captured the stack trace while filing the issue (there were a few failing tests), but it seems like an intermittent failure.

cc @dotnet/dnceng, @MattGal

**Comment by jonfortescue** [comment]
@ahsonkhan There's currently a Kusto outage that is affecting MC. The Kusto team is actively working to restore service and the issue should be resolved by tomorrow (Friday).

**Comment by stephentoub** [comment]
This is failing across a variety of tests, e.g. all of the SQL tests here:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/68ada12d84ac2fe26b9fe46955506525a61b8a40/workItem/System.Data.SqlClient.Tests

**Comment by stephentoub** [comment]
@dotnet/dnceng, has something changed in the image used for Windows.10.Amd64.Open-x86?  We're seeing this failure across lots of different tests and lots of different runs.  Maybe one or more machines got into a bad state?

**Comment by danmosemsft** [comment]
@safern

**Comment by MattGal** [comment]
@stephentoub the machines used on that queue have not changed in any way since 1/22, when we moved to the Azure Gallery image "2016-Datacenter", version "2016.127.20171217" .  

Machines are regularly, but not always, recycled and redeployed using identical scripts and images, but it's possible for either malformed work items to make stateful changes on machines (which could live a while before recycling) or other stuff to change.

I'll make an FR issue on myself, and do a quick investigation

**Comment by joshfree** [comment]
apparently we don't have the blocking-clean-ci label any longer, else I would have used that instead of blocking-release.

@bartonjs can you PTAL?

**Comment by danmosemsft** [comment]
"temporary profile" suggests that the profile of the user got corrupted.

**Comment by MattGal** [comment]
@danmosemsft , Maybe.  Or the context in which the process being started got affected.  I'll be investigating shortly, it should be pretty clear if user profile is the issue as it will form a pattern on the machines running these work items.

**Comment by bartonjs** [comment]
That error is issued when creating persisted keys (aka opening a PFX) and [GetProfileType](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762279(v=vs.85).aspx) reports PT_TEMPORARY (without PT_ROAMING).

Maybe there's a test somewhere that's changing the user profile mode?  Maybe it's just one bad machine?

**Comment by MattGal** [comment]
After some queries, this always fails on wuw10o7mi000DSG.  I'm deleting that VM now, it shouldn't do this again. I'll review the machine's history in case there's something to be learned from it.

This problem may happen relatively often, we simply would have recycled the machine sooner if there were not so much work in the queue.

**Comment by MattGal** [comment]
I added some notes in the linked issue in core-eng, but I don't think there's any evidence that a test work item caused this issue.  Having never seen it before, it's hopefully just a flaky VM.

**Comment by stephentoub** [comment]
Thanks for addressing it, @MattGal.

**Comment by stephentoub** [comment]
@MattGal, @bartonjs, this is happening again, e.g.
https://mc.dot.net/#/user/jkotas/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/efe4ea624c7893ac08aefc39b1308fe21db7bf8d/workItem/System.Security.Cryptography.Pkcs.Tests

**Comment by ahsonkhan** [comment]
Closed the duplicate issue: https://github.com/dotnet/corefx/issues/29045

**Comment by stephentoub** [comment]
@dotnet/dnceng, this is taking out a bunch of our PRs... could someone take a look? Thanks!

**Comment by joshfree** [comment]
@Chrisboh @mmitche @MattGal PTAL

**Comment by MattGal** [comment]
I'm finding the messed up machine now.  I'll try to preserve it and investigate it; @bartonjs  if you can come check it out that may be cool.

**Comment by stephentoub** [comment]
This is happening again, e.g.
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/3a27e2aed614a94dea6deb843f4f5ef68353092c

**Comment by stephentoub** [comment]
Thanks, @MattGal.  I will close this for now, and we can re-open if (when?) it becomes a blocker again.

**Comment by MattGal** [comment]
Sounds good;  until we find the underlying issue causing this, you can always ping me to delete a rogue machine manually as well (just only expect quick service during normal work hours :) )

**Comment by stephentoub** [comment]
Thanks.
