### ISSUE TITLE
[CentOS] Failure to load Microsoft.Win32.Primitives causes restore failing frequently

### ISSUE THREAD

**Issue by wli3** [dotnet/corefx#28662]
This is blocking CLI PR

https://github.com/dotnet/cli/pull/8893

https://ci.dot.net/job/dotnet_cli/job/release_2.1.3xx/job/debug_centos7.1_x64_prtest/181/testReport/(root)/(empty)/Microsoft_DotNet_New_Tests_GivenThatIWantANewAppWithSpecifiedType_TemplateRestoresAndBuildsWithoutWarnings_language___C____projectType___mvc___skipSpaWebpackSteps__False_/

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
 (Exception from HRESULT: 0x80070004)
   at System.Net.Sockets.MultipleConnectAsync.InternalConnectCallback(Object sender, SocketAsyncEventArgs args)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketFlags flags, SocketError socketError)
   at System.Net.Sockets.SocketAsyncEventArgs.ConnectCompletionCallback(SocketError socketError)
   at System.Net.Sockets.SocketAsyncContext.ConnectOperation.InvokeCallback(Boolean allowPooling)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessQueue(SocketAsyncContext context)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.<>c.<.cctor>b__15_1(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

Full:
```
    MESSAGE:
                                        Expected command to pass but it did not.
File Name: /mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/dotnet
Arguments: restore
WorkingDir:: /mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp
Exit Code: 134
StdOut:
  Restoring packages for /mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj...
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/nuget-build/nuget/v3/flatcontainer/microsoft.extensions.hosting/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/aspnetcore-release/nuget/v3/flatcontainer/microsoft.extensions.caching.sqlserver/index.json'.
  Too many open files
  Retrying 'FindPackagesByIdAsync' for source 'https://www.myget.org/F/container-tools-for-visual-studio/api/v3/flatcontainer/microsoft.extensions.hosting/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://www.myget.org/F/container-tools-for-visual-studio/api/v3/flatcontainer/microsoft.extensions.hosting/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.hosting.abstractions/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.buffers/index.json'.
  Too many open files
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/nuget-build/nuget/v3/flatcontainer/microsoft.extensions.identity.core/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/nuget-build/nuget/v3/flatcontainer/microsoft.extensions.identity.core/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://www.myget.org/F/container-tools-for-visual-studio/api/v3/flatcontainer/microsoft.extensions.identity.core/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://www.myget.org/F/container-tools-for-visual-studio/api/v3/flatcontainer/microsoft.extensions.identity.core/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/msbuild/nuget/v3/flatcontainer/microsoft.extensions.identity.core/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/msbuild/nuget/v3/flatcontainer/microsoft.extensions.identity.core/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnet.myget.org/F/templating/api/v3/flatcontainer/microsoft.extensions.logging/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/msbuild/nuget/v3/flatcontainer/newtonsoft.json.bson/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/msbuild/nuget/v3/flatcontainer/newtonsoft.json.bson/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnet.myget.org/F/templating/api/v3/flatcontainer/microsoft.extensions.logging/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/microsoft.extensions.logging/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/microsoft.extensions.logging/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/msbuild/nuget/v3/flatcontainer/microsoft.extensions.logging/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/msbuild/nuget/v3/flatcontainer/microsoft.extensions.logging/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.aspnetcore.authentication/index.json'.
  Too many open files
  Failed to download package 'Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.2.1.0-preview2-30475' from 'https://dotnetmyget.blob.core.windows.net/artifacts/aspnetcore-release/nuget/v3/flatcontainer/microsoft.aspnetcore.server.kestrel.transport.abstractions/2.1.0-preview2-30475/microsoft.aspnetcore.server.kestrel.transport.abstractions.2.1.0-preview2-30475.nupkg'.
  Too many open files
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/aspnetcore-release/nuget/v3/flatcontainer/microsoft.extensions.configuration.environmentvariables/index.json'.
  Too many open files
  Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/microsoft.extensions.options.configurationextensions/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/microsoft.extensions.options.configurationextensions/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Failed to download package 'Microsoft.EntityFrameworkCore.2.1.0-preview2-30475' from 'https://dotnetmyget.blob.core.windows.net/artifacts/aspnetcore-release/nuget/v3/flatcontainer/microsoft.entityframeworkcore/2.1.0-preview2-30475/microsoft.entityframeworkcore.2.1.0-preview2-30475.nupkg'.
  Too many open files
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.extensions.configuration.commandline/index.json'.
  Too many open files
  Retrying 'FindPackagesByIdAsync' for source 'https://www.myget.org/F/container-tools-for-visual-studio/api/v3/flatcontainer/microsoft.extensions.options.configurationextensions/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.net.http.headers/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error : Too many open files [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/msbuild/nuget/v3/flatcontainer/microsoft.net.http.headers/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/msbuild/nuget/v3/flatcontainer/microsoft.net.http.headers/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018: The "RestoreTask" task failed unexpectedly. [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.Debug, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file. [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018:  (Exception from HRESULT: 0x80070004) [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018: File name: 'System.Diagnostics.Debug, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018:    at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type) [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018:    at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext) [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018:    at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018:    at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg) [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018:    at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable) [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018:    at System.Reflection.CustomAttribute.IsDefined(RuntimeType type, RuntimeType caType, Boolean inherit) [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018:    at System.Diagnostics.StackTrace.ShowInStackTrace(MethodBase mb) [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018:    at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat) [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018:    at System.Exception.GetStackTrace(Boolean needFileInfo) [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018:    at System.Exception.ToString(Boolean needFileLineInfo, Boolean needMessage) [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018:    at NuGet.Common.ExceptionUtilities.LogException(Exception ex, ILogger logger, Boolean logStackAsError) [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018:    at NuGet.Common.ExceptionUtilities.LogException(Exception ex, ILogger logger) [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018:    at NuGet.Build.Tasks.RestoreTask.Execute() [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018:  [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error MSB4018:  [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj]
StdErr:

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
 (Exception from HRESULT: 0x80070004)
   at System.Net.Sockets.MultipleConnectAsync.InternalConnectCallback(Object sender, SocketAsyncEventArgs args)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketFlags flags, SocketError socketError)
   at System.Net.Sockets.SocketAsyncEventArgs.ConnectCompletionCallback(SocketError socketError)
   at System.Net.Sockets.SocketAsyncContext.ConnectOperation.InvokeCallback(Boolean allowPooling)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessQueue(SocketAsyncContext context)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.<>c.<.cctor>b__15_1(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

                                        +++++++++++++++++++
                                        STACK TRACE:
                                           at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at Microsoft.DotNet.Tools.Test.Utilities.CommandResultAssertions.Pass() in /mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/test/Microsoft.DotNet.Tools.Tests.Utilities/Assertions/CommandResultAssertions.cs:line 30
   at Microsoft.DotNet.New.Tests.GivenThatIWantANewAppWithSpecifiedType.TemplateRestoresAndBuildsWithoutWarnings(String language, String projectType, Boolean skipSpaWebpackSteps) in /mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/test/dotnet-new.Tests/GivenThatIWantANewAppWithSpecifiedType.cs:line 60

```

**Comment by karelz** [comment]
@wli3 what is different in this PR? Did you update CoreFX or CoreCLR bits you're running on? Or is it just unrelated change?
Does it happen reliably? Which OS versions does it affect?

**Comment by livarcocc** [comment]
@karelz we don't update corefx and coreclr separately, we just pick up bits from core-setup. Our current build came out of ProdCon.

This is happening consistently on CentOS.

**Comment by karelz** [comment]
@livarcocc ProdCon uses release/2.1 branch, right?
How do we repro it then on the bits? Do you have a repro machine handy?

**Comment by livarcocc** [comment]
Yes, this is from release/2.1.

No, we don't have a repro machine handy. Our CI caught this. You can see the failing PR here: https://github.com/dotnet/cli/pull/8893.

**Comment by karelz** [comment]
OK, so if I want to ask someone to take a look. What do I tell them to run to get the error under debugger / play with it?

**Comment by karelz** [comment]
cc @stephentoub @geoffkizer

**Comment by livarcocc** [comment]
getting a CentOS docker machine and build the CLI inside of it would be my first attempt.

**Comment by karelz** [comment]
@livarcocc @wli3 Does it fail without the PR as well? Or only on the PR? ... the information here is a bit sparse.
Who understands the CLI build and can help us isolate the repro? Given that it is blocking you, I assume it will be easier than ramping up someone on CLI build system from scratch.

**Comment by danmosemsft** [comment]
@livarcocc is this impacting preview 2 or just master?

@safern are you available to set this up first thing today?

**Comment by safern** [comment]
> @safern are you available to set this up first thing today?

Yes, I don't have anything "urgent" on my plate now that we hit ZBB. Taking a look

**Comment by wli3** [comment]
This impacting preview 2

**Comment by safern** [comment]
> Who understands the CLI build and can help us isolate the repro? Given that it is blocking you, I assume it will be easier than ramping up someone on CLI build system from scratch.

Agree. @livarcocc who would be the right person to help me understand the issue and have an easier repro?

> This impacting preview 2

This would be release/2.1.3xx branch?

**Comment by wli3** [comment]
The latest build from Saturday 2.1.0-preview2-26330-03 resolved the issue. Thank you!

**Comment by karelz** [comment]
FYI: CI log showed a failure during restore with “Too Many Files” open which is what I would guess is causing the missing file.

https://ci.dot.net/job/dotnet_cli/job/release_2.1.3xx/job/debug_centos7.1_x64_prtest/181/consoleFull
```
15>/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.1.300-preview2-008509/NuGet.targets(114,5): error : Too many open files [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-new.Tests/TemplateRestoresAndBuildsWithoutWarningsC#_mvc/temp/temp.csproj] [/mnt/resource/j/workspace/dotnet_cli/release_2.1.3xx/debug_centos7.1_x64_prtest/build/test/RunTest.proj]
```
