### ISSUE TITLE
Confusing message when block padding did not conform to the specified mode

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#28682]
_From @coderfox on March 31, 2018 9:28_

With the following code:

```csharp
using System;
using System.IO;
using System.Text;

namespace Bang.CustomClient
{
    public static class ApiCipher
    {
        public static byte[] key = Encoding.ASCII.GetBytes("1234123412341234");
        public static byte[] iv = Encoding.ASCII.GetBytes("1234123412341234");
        public static byte[] decrypt(byte[] ciphertext)
        {
            using (var aes = Aes.Create())
            {
                Debug.Assert(aes != null, nameof(aes) + " != null");
                aes.Key = key;
                aes.IV = iv;
                aes.Padding = PaddingMode.None;

                using (var decryptor = aes.CreateDecryptor(aes.Key, aes.IV))
                {
                    var result = decryptor.TransformFinalBlock(ciphertext, 0, ciphertext.Length);
                    return result;
                }
            }
        }
    }
    class Program
    {
        static void Main(string[] args)
        {
            var bin = File.ReadAllBytes("http");
            var dec = ApiCipher.decrypt(bin);
            Console.Write(Encoding.ASCII.GetString(dec));
        }
    }
}

```

If I comment `aes.Padding = PaddingMode.None;` (i.e. use PKCS7 padding), the program will throw:

```
Unhandled Exception: System.Security.Cryptography.CryptographicException: Specified padding mode is not valid for this algorithm.
   at Internal.Cryptography.UniversalCryptoDecryptor.DepadBlock(Byte[] block, Int32 offset, Int32 count)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Bang.CustomClient.ApiCipher.decrypt(Byte[] ciphertext) in /Users/coderfox/Dev/Projects/BanGDreamHack/Bang.CustomClient/ApiCipher.cs:line 36
   at Bang.CustomClient.Program.Main(String[] args) in /Users/coderfox/Dev/Projects/BanGDreamHack/Bang.CustomClient/Program.cs:line 12
```

But if I uncomment the line, the program works.

Besides, I have validated the input file with python, and it successfully decrypts.

I am using dotnet-sdk `2.1.103` on macOS `10.13.1 (17B48)`.

File `http` in `base64` is:

```
aeqsmc3eMswgJkz34BACmqZSo96E61H43Q5oK9NqXzM=
```

_Copied from original issue: dotnet/coreclr#17373_

**Comment by jkotas** [comment]
_From @coderfox on March 31, 2018 9:55_

OK, I found actually the source is padded with `ISO10126`. Sorry for disturbing, but I think the exception message is quite misunderstanding, an exception with message `ciphertext padding mismatch` may be better.

**Comment by bartonjs** [comment]
Hmm, I wonder if we copied the wrong string over from netfx.  `Cryptography_InvalidPadding` and `Cryptography_InvalidPaddingMode` both say "Specified padding mode is not valid for this algorithm.".  The error people complain about on StackOverflow is usually "Padding is invalid and cannot be removed.", which (theoretically) is what `Cryptography_InvalidPadding` should say.
