### ISSUE TITLE
CurlHandler: catastrophic failure with GetAsync_SecureAndNonSecureIPBasedUri_CorrectlyFormatted test 

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#28703]
The test consistently cause catastrophic failure on Centos, Fedora, RedHat, and Ubuntu 1804, while passing on other distros. 

It could be different CurlHandler version causing the issue. (Since Windows run is green every time).

**Comment by stephentoub** [comment]
> The test consistently cause catastrophic failure on Centos, Fedora, RedHat, and Ubuntu 1804, while passing on other distros.

I assume by catastrophic failure you just mean the test hangs?  All that fireball means in the mission control UI is that the test process failed, which either means it crashed or it hung.

**Comment by caesar1995** [comment]
> I assume by catastrophic failure you just mean the test hangs?

Based on  the [execution log](https://mc.dot.net/#/user/caesar1995/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/7db9f75494d245795a018e7c76652085703488bc/workItem/System.Net.Http.Functional.Tests/wilogs) I think it's test hang. (No failure or crash logged).

**Comment by caesar1995** [comment]
Change to `HttpClientHandler.DangerousAcceptAnyServerCertificateValidator` resolved the issue. (Related #19709)

**Comment by danmosemsft** [comment]
@caesar1995 is this what is fixed? not sure whether it contains your referenced change

https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/1757a49ea3d9101aeae462298cd03f9fca2bfc47

```
      System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandlerTest.GetAsync_SecureAndNonSecureIPBasedUri_CorrectlyFormatted(address: 127.0.0.1, useSsl: True) [FAIL]
        System.Exception : Unexpected EOF trying to read request header
        Stack Trace:
    Starting:    System.Reflection.TypeExtensions.CoreCLR.Tests
             at System.Net.Test.Common.LoopbackServer.Connection.<ReadRequestHeaderAsync>d__14.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Net.Test.Common.LoopbackServer.Connection.<ReadRequestHeaderAndSendResponseAsync>d__17.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass43_0.<<GetAsync_SecureAndNonSecureIPBasedUri_CorrectlyFormatted>b__2>d.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Net.Test.Common.LoopbackServer.<AcceptConnectionAsync>d__12.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass11_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Net.Test.Common.LoopbackServer.<CreateServerAsync>d__9.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<GetAsync_SecureAndNonSecureIPBasedUri_CorrectlyFormatted>d__43.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Finished:    System.Net.Http.Functional.Tests
```

**Comment by caesar1995** [comment]
It's a new issue, this one throws Exception instead of crash/hang (catastrophic failure). We will need to disable the test/open a new issue, and investigate when it happens next time.
