### ISSUE TITLE
SslStream with CRL checking enabled throws CryptographicException on Linux upon upgrade of server certificates

### ISSUE THREAD

**Issue by vincentkam** [dotnet/corefx#28724]
**Overview**
A Linux application speaking to a server using SslStream will no longer be able to connect if the server upgrades its certificates such that it contains a new CRL distribution point (e.g. a different URL). After this upgrade, SslStream will throw a CryptographicException (error code 44) from Internal.Cryptography.Pal.OpenSslX509ChainProcessor.MapVerifyErrorToChainStatus.  Error code 44 maps to X509_V_ERR_DIFFERENT_CRL_SCOPE (see https://github.com/openssl/openssl/blob/3bb0f989b53c59c6d4527a0b5077dbb7fabe14b7/include/openssl/x509_vfy.h).

**Workaround**
Clearing the cached CRL at ~/.dotnet/corefx/cryptography/crls prior to the certificate upgrade will allow the application to connect without any downtime, assuming that the application doesn't reacquire another copy of the old CRL (e.g. due to a disconnect/reconnect). The filename will be the hashed issuer's name.
(see https://github.com/dotnet/corefx/blob/722d50c8957297009dbce771f3ea317cccf457be/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/CrlCache.cs#L139-L162)
 
**Hypothesis**
The exception is likely thrown because even though the new certificate specifies a new CRL distribution point, the issuer name has not changed, so the cache thinks it contains a valid CRL for the new certificate and does not download the new CRL even though the distribution point has changed.

However, when the interop library calls OpenSSL to verify the certificate stores, the error code 44 is generated and an exception is later thrown from Internal.Cryptography.Pal.OpenSslX509ChainProcessor.MapVerifyErrorToChainStatus.
I believe this error code is generated due to the mismatch between the cached CRL's distribution point and the distribution point specified in the new certificate.
 
**Possible fix**
Using the hash of the CRL distribution point string as the filename for the cached CRL should prevent this problem. However, I am uncertain if there are OpenSSL interop implications if a different filename is used for the cached CRL. There does seem to be prescedent in OpenSSL for using the hash of the issuer name as the file name for cached copy of CRL (see https://www.openssl.org/docs/manmaster/man3/X509_LOOKUP_file.html)
 
**Reproduction**
Create a chain of certificates that mimics certificates issued by DigiCert SHA2 Secure Server CA. The final server certificates "A" and "B" should be issued for the same FQDN but with different distribution points (simulating an upgrade of the server certificate).
 
My apologies if these steps are already self-evident for those with more SSL experience, but these are the steps I used:
 
1. Create a self signed root CA such that "X509v3 Key Usage: Digital Signature, Certificate Sign, CRL Sign".
2. Generate a CRL for the root CA, taking care that the CRL does _not_ have a X509v3 Issuing Distribution Point (IDP).
3. Create an intermediate certificate authority with the same key usage as the root CA and with an X509v3 IDP pointing to the CRL generated in step 2.
4. Generate a CRL for the intermediate CA. This CRL should contain an X509v3 IDP.
5. Create the server certificate "A" signed by the intermediate CA. This certificate should have an X509v3 IDP that matches the IDP for the CRL generated in step 4.
6. Generate another CRL for the intermediate CA with a different filename from the one in (4). This CRL also should have an X509v3 IDP.
7. Create the server certificate "B", signed by the intermediate CA.  This certificate should have an X509v3 IDP that matches the IDP of the CRL generated in step 6.
8. Install the root CA by copying the certificate to its own directory under /usr/local/share/ca-certificates/, setting the permissions to 644, and running update-ca-certificates. 
9. Host a test server using openssl s_server "openssl s_server -port 44330 -key keyA.pem -cert certA.pem -CAfile intermediatecert.pem"
10. Create a test app that connects to the OpenSSL s_server using SslStream, calling AuthenticateAsClient with checkCertificateRevocation: true. After it connects successfully, bring down the test server and re-host it using B's certs and key. The test app should now throw the CryptographicException. 

I’ve included my test app (targeting netcoreapp2.0) and stack trace. I’ve successfully reproduced this in a Debian Stretch Docker container (.NET Core SDK 2.1.101, .NET Core runtime: 2.0.5, OpenSSL 1.0.2k-fips) as well as in an Ubuntu 16.04.4 LTS instance (.NET Core SDK 2.1.300-preview1-008174, .NET Core runtime:  2.1.0-preview1-26216-03, OpenSSL 1.0.2g).

```
Unhandled Exception: System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
   at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.MapVerifyErrorToChainStatus(X509VerifyStatusCode code)
   at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.AddElementStatus(X509VerifyStatusCode errorCode, List`1 elementStatus, List`1 overallStatus)
   at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.AddElementStatus(List`1 errorCodes, List`1 elementStatus, List`1 overallStatus)
   at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.BuildChain(X509Certificate2 leaf, HashSet`1 candidates, HashSet`1 systemTrusted, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan& remainingDownloadTime)
   at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
   at System.Net.Security.CertificateValidation.BuildChainAndVerifyProperties(X509Chain chain, X509Certificate2 remoteCertificate, Boolean checkCertName, String hostName)
   at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback, ProtocolToken& alertToken)
   at System.Net.Security.SslState.CompleteHandshake(ProtocolToken& alertToken)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ssl.SslTcpClient.RunClient(String machineName, String serverName) in /home/vincent/cached-crl-test-app/Ssl/SslTcpClient.cs:line 51
   at cached_crl_test_app.Program.Main(String[] args) in /home/vincent/cached-crl-test-app/cached-crl-test-app/Program.cs:line 42
 ```

 
 
```
// Program.cs
using System;
namespace cached_crl_test_app {
    class Program {
        static void Main(string[] args) {
        	string serverCertificateName = "tyche";
        	string machineName = "tyche";
        	while (true) {
        	    Console.WriteLine("Press enter to connect and send a message.");
            	Console.ReadLine();
                Console.WriteLine("Attempting to connect...");
                SslTcpClient.RunClient(machineName, serverCertificateName);
       	 }
        }
    }
}

// Ssl.cs  
using System;
using System.IO;
using System.Linq;
using System.Net.Security;
using System.Net.Sockets;
using System.Security.Authentication;
using System.Security.Cryptography.X509Certificates;
using System.Text;

namespace Ssl {
	public class SslTcpClient {
 
    	// Purely for debugging purposes, not needed
    	public static bool ValidateServerCertificate(
            	object sender,X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) {
 	    var errors = chain.ChainStatus.Aggregate("", (str, x) => str + "," + x.Status);
            Console.WriteLine($"SslPolicyError: {sslPolicyErrors} {errors}");
 
            foreach (var item in chain.ChainElements) foreach (var elemStatus in item.ChainElementStatus)
               Console.WriteLine(item.Certificate.Subject + "->" + elemStatus.StatusInformation);
            return true;
    	}
 
    	public static void RunClient(string machineName, string serverName)  {
        	var socket = new Socket(SocketType.Stream, ProtocolType.Tcp);
            socket.Connect(serverName, 44330);
            Console.WriteLine("Client connected.");
        	using (var stream = new NetworkStream(socket)) {            	
            	var sslStream = new SslStream(innerStream: stream, leaveInnerStreamOpen: false,
                    userCertificateValidationCallback: ValidateServerCertificate);
     	
            	try {
                    sslStream.AuthenticateAsClientAsync(serverName, new X509Certificate2Collection(),
                        SslProtocols.Tls12, checkCertificateRevocation: true).GetAwaiter().GetResult();
            	} catch (AuthenticationException e) {
                    Console.WriteLine("Exception: {0}", e.Message);
                	if (e.InnerException != null)
                        Console.WriteLine("Inner exception: {0}", e.InnerException.Message);
 
                    Console.WriteLine("Authentication failed - closing the connection.");
                	return;
            	}
 
            	var w = new StreamWriter(sslStream);
                w.WriteLine("Hello from the client.");
            	w.Flush();  
            	
                var serverMessage = ReadLine(new StreamReader(sslStream));
                Console.WriteLine("Server says: {0}", serverMessage);
                Console.WriteLine("Press enter to close the connection.");
                Console.ReadLine();	            
        	}
 
        	socket.Dispose();
            Console.WriteLine("Client closed.");
    	}
 
    	static string ReadLine(StreamReader reader) => reader.ReadLine();
 
    	static void SendMessage(SslStream sslStream, string s="Hello from the client.") =>
            sslStream.Write(Encoding.UTF8.GetBytes(s));
	}
}
```

**Comment by bartonjs** [comment]
The fix I have in mind is to change the processing loop so that the failure code and the file reference are closer together (so that "oh, maybe I should delete this file..." makes sense).  That's a bit too risky to do for 2.1 at this point, but this is definitely a "+1" on "tidy up chain processing".

**Comment by bartonjs** [comment]
> So just to be clear, the fix that you have in mind would change the error message to include the failure code and the file reference?

No, when we get the "this CRL doesn't seem to match" error we'd just delete the cached entry and try again.

>  I'm curious as to why upgrading a server's certificate isn't a problem on Windows

The Windows certificate chain APIs apparently handled this case.  And the macOS version may also be fine (also a black box) but on Linux we have a bit more of an active role in making the system behave the same way it did for .NET Framework (aka the Windows API).  The code you spotted was in `Pal.Unix`, so only Unix systems (and then we also have a special one for macOS).

And usually when a new issuing CA is stood up it's given a disambiguator in the name, e.g. the G3 in "Symantec Class 3 EV SSL CA - G3"; so this isn't a super common problem.

**Comment by vincentkam** [comment]
Thank you for the clarification! (My apologies, I had misinterpreted "failure code" as "error code" e.g. error code 44).  Deleting the cached entry and trying again sounds fantastic to me.

I agree that this won't be a super common problem when a new issuing CA is stood up because it's usually given a disambiguator in the name. However, as you already know, I think the problem can also occur if a new distribution point is specified when a certificate is renewed. 

Additionally, thank you for the extended explanation! It's interesting to note that the Windows certificate chain APIs already handle this case (👍 ) while on Linux a more active role is need.
