### ISSUE TITLE
[Regression] Test failure: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest / GetAsync_IPv6LinkLocalAddressUri_Success

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/corefx#28749]
## Types of failure

`System.Net.Http.Functional.Tests` / `SocketsHttpHandler_HttpClientHandlerTest.GetAsync_IPv6LinkLocalAddressUri_Success`

Linux:
```
System.Net.Http.HttpRequestException : Invalid argument
---- System.Net.Sockets.SocketException : Invalid argument
```

OSX - [details](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_osx_debug/390/testReport/System.Net.Http.Functional.Tests/SocketsHttpHandler_HttpClientHandlerTest/GetAsync_IPv6LinkLocalAddressUri_Success/
)
```
System.Net.Http.HttpRequestException : No route to host
---- System.Net.Sockets.SocketException : No route to host

at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_debug/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 86
at System.Threading.Tasks.ValueTask`1.get_Result() in /Users/buildagent/agent/_work/482/s/src/mscorlib/shared/System/Threading/Tasks/ValueTask.cs:line 723
at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_debug/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 325
at System.Threading.Tasks.ValueTask`1.get_Result() in /Users/buildagent/agent/_work/482/s/src/mscorlib/shared/System/Threading/Tasks/ValueTask.cs:line 723
at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_debug/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 467
at System.Threading.Tasks.ValueTask`1.get_Result() in /Users/buildagent/agent/_work/482/s/src/mscorlib/shared/System/Threading/Tasks/ValueTask.cs:line 723
at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_debug/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 258
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_debug/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 30
at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_debug/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 479
at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass34_0.<<GetAsync_IPv6LinkLocalAddressUri_Success>b__0>d.MoveNext() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_debug/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs:line 365
--- End of stack trace from previous location where exception was thrown ---
at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_debug/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 67
at System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_IPv6LinkLocalAddressUri_Success() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_debug/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs:line 362
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_debug/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 76
```

## History of failures

Day | Build | Details
-- | -- | --
4/3 | 20180403.01 | 2x OSX & 15x Linux
4/3 | 20180403.04 | 2x OSX & 14x Linux

**Comment by danmosemsft** [comment]
Actually GetAsync_IPv6LinkLocalAddressUri_Success is failing on all Unixes right now.

https://mc.dot.net/#/product/netcore/prodconmaster/source/prodcon~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180403.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest~2FGetAsync_IPv6LinkLocalAddressUri_Success

On Linuxes it's 
```
System.Net.Http.HttpRequestException : Invalid argument
---- System.Net.Sockets.SocketException : Invalid argument
Stack Trace :
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in /root/corefx-1549791/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 86
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /root/corefx-1549791/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 325
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask) in /root/corefx-1549791/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 467
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /root/corefx-1549791/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 258
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /root/corefx-1549791/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 30
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in /root/corefx-1549791/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 479
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass34_0.<<GetAsync_IPv6LinkLocalAddressUri_Success>b__0>d.MoveNext() in /root/corefx-1549791/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs:line 365
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /root/corefx-1549791/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 67
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_IPv6LinkLocalAddressUri_Success() in /root/corefx-1549791/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs:line 362
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
```

@karelz Is a test server down?

**Comment by wfurt** [comment]
This is loopback test:
        public static IPAddress GetIPv6LinkLocalAddress() =>
            NetworkInterface
                .GetAllNetworkInterfaces()
                .SelectMany(i => i.GetIPProperties().UnicastAddresses)
                .Select(a => a.Address)
                .Where(a => a.IsIPv6LinkLocal)
                .FirstOrDefault();
    }

**Comment by wfurt** [comment]
This seems to be regression caused by #28578
It seems like the change changed what we store in _host. 
In my local case is is is fe80::6651:6ff:fe5b:6bb6 instead of fe80::6651:6ff:fe5b:6bb%2
Note that the scope is mandatory for LLA.

cc: @caesar1995

**Comment by davidsh** [comment]
>This seems to be regression caused by #28578

Why wasn't this caught during the PR for #28578?

**Comment by caesar1995** [comment]
I have run [Outerloop] test with product change (https://github.com/dotnet/corefx/pull/28578#issuecomment-377674456, I deleted some comments like this).

I will investigate.

**Comment by caesar1995** [comment]
The root cause for this issue is as @wfurt mentioned, [this line of code](https://github.com/dotnet/corefx/pull/28578/files#diff-2675d24b3a3482c87ea2b9a41e2bdfb7R200) caused trouble. 

Uri.IdnHost will return `fe80::e077:c9a3:eeba:b8e9%18`.
Uri.Host will return `[fe80::e077:c9a3:eeba:b8e9]`.

After we change to `isIPv6Address ? uri.Host : uri.IdnHost`, the `uri.Host` will be returned if IPv6 address (no matter it's LLA or not).

Note:
1. It only fails on Linux distros. To be more specific, `Socket.ConnectAsync(SocketType.Stream, ProtocolType.Tcp, saea)` will complain `Invalid argument` (for `saea`'s `RemoteEndPoint`).
2. On Windows, using `uri.Host` for LLA will success and doesn't throw exception.
3. Change to `"[" + uri.IdnHost + "]"` will resolve the issue.


> It seems like the change changed what we store in _host.

Yes, `_host` will be `uri.Host` instead of `uri.IdnHost` if it's IPv6 address.

> Note that the scope is mandatory for LLA.

Is that for Linux OS specifically? On Windows it works fine.

> Why wasn't this caught during the PR for #28578?

The previous product change is using `"[" + uri.IdnHost + "]"` instead of `uri.Host`, and I have run Outerloop test for that. After changing to `uri.Host`, I didn't run Outerloop test, thus the regression was not caught. I will pay attention to critical change like this next time, and make sure nothing is regressed.

**Comment by karelz** [comment]
BTW: The test is failing in nightly runs massively - see updated top post.
If we can't have proper fix right away, please disable the test first to avoid the noise, thanks!

**Comment by davidsh** [comment]
Also, regarding IPv6 link-local addresses (LLA), these are problematic for UWP.  For example, we disabled some tests for UWP because while System.Uri can handle scope-id's in LLA's, Windows.Foundation.Uri cannot.  So, you might want to try these tests against outerloop UWP as well and disable if needed.

See: #22158 which is tracking against Windows internal bug as well.

**Comment by caesar1995** [comment]
Test disabled here: https://github.com/dotnet/corefx/pull/28789

To reduce the noise.
