### ISSUE TITLE
[Desktop] Test failure: PlatformHandler_HttpClientHandlerTest/ AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#28772]
Failed on NETFX CI leg:
```
      System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandlerTest.AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection(statusCode: 307, oldMethod: "GET", newMethod: "GET") [FAIL]
        Canceled: 
        Expected: False
        Actual:   True
        Stack Trace:
             at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass50_2.<<AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection>b__1>d.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Net.Test.Common.LoopbackServer.<CreateServerAsync>d__9.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass50_1.<<AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection>b__0>d.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Net.Test.Common.LoopbackServer.<CreateServerAsync>d__9.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection>d__50.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by davidsh** [comment]
The test is failing here:
https://github.com/dotnet/corefx/blob/344c31c7ba9bc171bbab31167acdd279e9f6027c/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs#L777

The request seems to have been canceled.  This is all using the loopback server. It's likely that some delay is happening starting these async tasks and HttpClient cancelled the request after the default 100 seconds.

**Comment by davidsh** [comment]
We haven't seen this failure lately.  So, I'm closing this issue.
