### ISSUE TITLE
[Regression] System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ResponseDrain_Test / GetAsync_DisposeBeforeReadingToEnd_DrainsRequestsAndReusesConnection

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#28793]
## Type of failures

OSX failures:
```
System.Exception : Unexpected EOF trying to read request header

at   System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAsync()
at   System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAndSendCustomResponseAsync(String   response) in   /Users/buildagent/agent/_work/391/s/corefx/src/Common/tests/System/Net/Http/LoopbackServer.cs:line   388
at   System.Net.Http.Functional.Tests.HttpClientHandler_ResponseDrain_Test.<>c__DisplayClass3_0.<<GetAsync_DisposeBeforeReadingToEnd_DrainsRequestsAndReusesConnection>b__2>d.MoveNext()   in   /Users/buildagent/agent/_work/391/s/corefx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ResponseDrain.cs:line   87
--- End of stack trace from previous location where exception was thrown   ---
at   System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync)   in /Users/buildagent/agent/_work/391/s/corefx/src/Common/tests/System/Net/Http/LoopbackServer.cs:line   117
at   System.Net.Http.Functional.Tests.HttpClientHandler_ResponseDrain_Test.<>c__DisplayClass3_0.<<GetAsync_DisposeBeforeReadingToEnd_DrainsRequestsAndReusesConnection>b__1>d.MoveNext()   in   /Users/buildagent/agent/_work/391/s/corefx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ResponseDrain.cs:line   83
--- End of stack trace from previous location where exception was thrown   ---
at   System.Net.Test.Common.LoopbackServer.<>c__DisplayClass11_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()   in /Users/buildagent/agent/_work/391/s/corefx/src/Common/tests/System/Net/Http/LoopbackServer.cs:line   84
--- End of stack trace from previous location where exception was thrown   ---
at   System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync,   Options options) in   /Users/buildagent/agent/_work/391/s/corefx/src/Common/tests/System/Net/Http/LoopbackServer.cs:line   67
at   System.Net.Http.Functional.Tests.HttpClientHandler_ResponseDrain_Test.GetAsync_DisposeBeforeReadingToEnd_DrainsRequestsAndReusesConnection(ContentMode   mode) in   /Users/buildagent/agent/_work/391/s/corefx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ResponseDrain.cs:line   56
--- End of stack trace from previous location where exception was thrown   ---
```

## History of failures

Day | Build | OS
-- | -- | --
3/14 | 20180314.05 | OSX10.13
3/14 | 20180314.07 | OSX10.13
3/23 | 20180323.01 | OSX10.13
3/24 | 20180324.03 | OSX10.13
3/26 | 20180326.01 | OSX10.13
3/27 | 20180327.01 | OSX10.13
3/27 | 20180327.04 | OSX10.13
3/29 | 20180329.05 | OSX10.13
3/30 | 20180330.01 | OSX10.13
3/30 | 20180330.06 | OSX10.13
3/31 | 20180331.02 | OSX10.13
3/31 | 20180331.03 | OSX10.13
3/31 | 20180331.05 | OSX10.13

**Comment by karelz** [comment]
It looks very similar to #27528 - @geoffkizer any ideas?

**Comment by caesar1995** [comment]
Similar callstack here: https://github.com/dotnet/corefx/issues/28703#issuecomment-378117161

**Comment by stephentoub** [comment]
We were guessing at the draining behavior of WinHttpHandler and CurlHandler; seems like we just guessed wrong and should simply disable the test for them, e.g. by removing the `&& mode == ContentMode.BytePerChunk` at https://github.com/dotnet/corefx/blob/4a549f7fe7e8ea19f4fea8a233e525ebe0df7abb/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ResponseDrain.cs#L48.

**Comment by ahsonkhan** [comment]
I still see this failure, from https://github.com/dotnet/corefx/pull/29135, on a different test.
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Cancellation_Test/MaxConnectionsPerServer_WaitingConnectionsAreCancelable
OSX.1013.Amd64.Open-x64-Debug
https://mc.dot.net/#/user/ahsonkhan/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/b4d8770fd1e6d5f849cb907664d835dcad1c401a/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Cancellation_Test~2FMaxConnectionsPerServer_WaitingConnectionsAreCancelable

```text
System.Exception : Unexpected EOF trying to read request header
Stack Trace :
   at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAsync() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 378
   at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAndSendResponseAsync(HttpStatusCode statusCode, String additionalHeaders, String content) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 395
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass14_0.<<AcceptConnectionSendResponseAndCloseAsync>b__0>d.MoveNext() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 117
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionSendResponseAndCloseAsync(HttpStatusCode statusCode, String additionalHeaders, String content) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 142
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 64
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 92
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.<>c__DisplayClass5_0.<<MaxConnectionsPerServer_WaitingConnectionsAreCancelable>b__0>d.MoveNext() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 345
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 67
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.MaxConnectionsPerServer_WaitingConnectionsAreCancelable() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 313
--- End of stack trace from previous location where exception was thrown ---
```
