### ISSUE TITLE
Test failure in System.Security.Principal.Windows

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/corefx#28798]
WindowsPrincipalTests.CheckUserClaims [FAIL]
        System.ObjectDisposedException : Safe handle has been closed
        Stack Trace:
              at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
           E:\A\_work\10\s\src\mscorlib\src\System\StubHelpers.cs(1639,0): at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
              at Interop.Advapi32.LsaLookupSids(SafeLsaPolicyHandle handle, Int32 count, IntPtr[] sids, SafeLsaMemoryHandle& referencedDomains, SafeLsaMemoryHandle& names)
           d:\Repos\corefx\src\System.Security.Principal.Windows\src\System\Security\Principal\SID.cs(1075,0): at System.Security.Principal.SecurityIdentifier.TranslateToNTAccounts(IdentityReferenceCollection sourceSids, Boolean& someFailed)
           d:\Repos\corefx\src\System.Security.Principal.Windows\src\System\Security\Principal\SID.cs(1218,0): at System.Security.Principal.SecurityIdentifier.Translate(IdentityReferenceCollection sourceSids, Type targetType, Boolean& someFailed)
           d:\Repos\corefx\src\System.Security.Principal.Windows\src\System\Security\Principal\SID.cs(1188,0): at System.Security.Principal.SecurityIdentifier.Translate(IdentityReferenceCollection sourceSids, Type targetType, Boolean forceSuccess)
           d:\Repos\corefx\src\System.Security.Principal.Windows\src\System\Security\Principal\SID.cs(903,0): at System.Security.Principal.SecurityIdentifier.Translate(Type targetType)
           d:\Repos\corefx\src\System.Security.Principal.Windows\src\System\Security\Principal\WindowsIdentity.cs(490,0): at System.Security.Principal.WindowsIdentity.<GetName>b__46_0()
           d:\Repos\corefx\src\System.Security.Principal.Windows\src\System\Security\Principal\WindowsIdentity.cs(669,0): at System.Security.Principal.WindowsIdentity.<>c__DisplayClass62_0.<RunImpersonatedInternal>b__0(Object <p0>)
           E:\A\_work\10\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs(167,0): at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
           --- End of stack trace from previous location where exception was thrown ---
           d:\Repos\corefx\src\System.Security.Principal.Windows\src\System\Security\Principal\WindowsIdentity.cs(655,0): at System.Security.Principal.WindowsIdentity.RunImpersonatedInternal(SafeAccessTokenHandle token, Action action)
           d:\Repos\corefx\src\System.Security.Principal.Windows\src\System\Security\Principal\WindowsIdentity.cs(603,0): at System.Security.Principal.WindowsIdentity.RunImpersonated(SafeAccessTokenHandle safeAccessTokenHandle, Action action)
           d:\Repos\corefx\src\System.Security.Principal.Windows\src\System\Security\Principal\WindowsIdentity.cs(488,0): at System.Security.Principal.WindowsIdentity.GetName()
           d:\Repos\corefx\src\System.Security.Principal.Windows\src\System\Security\Principal\WindowsIdentity.cs(475,0): at System.Security.Principal.WindowsIdentity.get_Name()
           d:\Repos\corefx\src\System.Security.Principal.Windows\src\System\Security\Principal\WindowsIdentity.cs(940,0): at System.Security.Principal.WindowsIdentity.InitializeClaims()
           d:\Repos\corefx\src\System.Security.Principal.Windows\src\System\Security\Principal\WindowsIdentity.cs(911,0): at System.Security.Principal.WindowsIdentity.get_Claims()+MoveNext()
           d:\Repos\corefx\src\System.Security.Claims\src\System\Security\Claims\ClaimsPrincipal.cs(234,0): at System.Security.Claims.ClaimsPrincipal.get_Claims()+MoveNext()
           d:\Repos\corefx\src\Common\src\System\Collections\Generic\LargeArrayBuilder.cs(172,0): at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
           d:\Repos\corefx\src\Common\src\System\Collections\Generic\EnumerableHelpers.cs(84,0): at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
           d:\Repos\corefx\src\System.Linq\src\System\Linq\ToCollection.cs(18,0): at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
           d:\Repos\corefx\src\System.Security.Principal.Windows\tests\WindowsPrincipalTests.cs(59,0): at WindowsPrincipalTests.CheckUserClaims()

**Comment by danmosemsft** [comment]
Is this https://github.com/dotnet/corefx/issues/16511 ... if so maybe it needs a change like https://github.com/dotnet/corefx/pull/28317/files ?

**Comment by MisinformedDNA** [comment]
It may be related. Indeed, my computer is not domain joined. But based on other builds I've done, I would think something changed over the last few days.

I'm at commit e43901d03a3183c62dba9f354e51130a5c514a30, and I have verified that the referenced commit is included in my code. I synced up today.

**Comment by bartonjs** [comment]
@Tratcher The Internet suggests you've seen (effectively) this callstack before.  I don't suppose you know what the actual problem is? :smile:

**Comment by Tratcher** [comment]
Seen it, yes, understood it, no. https://github.com/aspnet/HttpSysServer/issues/426

**Comment by bartonjs** [comment]
@MisinformedDNA Is this a recurring failure for you, or is it intermittent?

**Comment by MisinformedDNA** [comment]
I saw it once (maybe twice), and then it wouldn't repro anymore.

**Comment by smbecker** [comment]
I am seeing this error in a production scenario when attempting to retrieve access rules on a customer's file server. Is there any tips on trying to diagnose the issue? The relevant stack trace is

```
System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Advapi32.LsaLookupSids(SafeLsaPolicyHandle handle, Int32 count, IntPtr[] sids, SafeLsaMemoryHandle& referencedDomains, SafeLsaMemoryHandle& names)
   at System.Security.Principal.SecurityIdentifier.TranslateToNTAccounts(IdentityReferenceCollection sourceSids, Boolean& someFailed)
   at System.Security.Principal.SecurityIdentifier.Translate(IdentityReferenceCollection sourceSids, Type targetType, Boolean& someFailed)
   at System.Security.Principal.IdentityReferenceCollection.Translate(Type targetType, Boolean forceSuccess)
   at System.Security.Principal.IdentityReferenceCollection.Translate(Type targetType)
   at System.Security.AccessControl.CommonObjectSecurity.GetRules(Boolean access, Boolean includeExplicit, Boolean includeInherited, Type targetType)
```
