### ISSUE TITLE
SslStream.AuthenticateAsClientAsync sometimes throws an UnauthorizedAccessException on Linux

### ISSUE THREAD

**Issue by halter73** [dotnet/corefx#28819]
SslStream.AuthenticateAsClientAsync sometimes throws an UnauthorizedAccessException on Linux. See aspnet/KestrelHttpServer#2456.

```
System.UnauthorizedAccessException : Access to the path '/home/aspnetagent/.dotnet/corefx/cryptography/x509stores/my' is denied.
---- System.IO.IOException : Bad file descriptor
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.CloneTo(X509Certificate2Collection collection)
   at System.Security.Cryptography.X509Certificates.X509Store.get_Certificates()
   at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.FindCandidates(X509Certificate2 leaf, X509Certificate2Collection extraStore, HashSet`1 downloaded, HashSet`1 systemTrusted, TimeSpan& remainingDownloadTime)
   at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
   at System.Net.Security.CertificateValidation.BuildChainAndVerifyProperties(X509Chain chain, X509Certificate2 remoteCertificate, Boolean checkCertName, String hostName)
   at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback, ProtocolToken& alertToken)
   at System.Net.Security.SslState.CompleteHandshake(ProtocolToken& alertToken)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__43_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.HttpsConnectionAdapterTests.ValidationFailureRejectsConnection(ClientCertificateMode mode) in /_/test/Kestrel.FunctionalTests/HttpsConnectionAdapterTests.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
```

This is the call that sometimes fails:

https://github.com/aspnet/KestrelHttpServer/blob/70ce0447781bfca57f6945e6a5f056045073e6ec/test/Kestrel.FunctionalTests/HttpsConnectionAdapterTests.cs#L303

At first I thought this might be caused by concurrent access to our testCert.pfx file, but it access to `~/.dotnet/corefx/cryptography/x509stores/my` that's being denied. I suspect there are other tests using SslStream running in parallel though.

**Comment by bartonjs** [comment]
`Bad file descriptor`?  Does that mean someone/something created `my` as a file instead of a directory?

I'm not sure what we'd do here.  If you want to open a store and it's corrupt I can't just do nothing.  But if we had more data on how we got into this state (whatever it is) then maybe there'd be something more actionable.  (I could wrap it in a CryptographicException, I guess; but I feel like the complaint is the existence of an Exception, not the type of it)

**Comment by stephentoub** [comment]
> Bad file descriptor? Does that mean someone/something created my as a file instead of a directory?

Presumably that's an errno value coming from a readdir call, in which case EBADF means "Invalid directory stream descriptor dirp."  In other variants of the man pages, I see slightly more descriptive text, e.g. "Indicates that the DirectoryPointer parameter argument does not refer to an open directory stream", "The file descriptor determined by the DIR stream is no longer valid. This results if the DIR stream has been closed.", etc.  Sounds like maybe the file descriptor got closed somehow, which is why I looped in @JeremyKuhne... had this still been a safe handle, we might have had more info (https://github.com/dotnet/corefx/commit/c9100ffc2988a0faf0e92898762a445ccb3c0e13#diff-cbe887baa737b69109146305bbf6ca30)

**Comment by stephentoub** [comment]
It looks like we enumerate some directory paths and push them onto a queue, and then later when we go to open the next directory in the traversal:
https://github.com/dotnet/corefx/blob/b96c29aedf9b2f4197d161f632b4387a17be72f8/src/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerator.Unix.cs#L200-L204
we might get IntPtr.Zero if we fail to open the directory:
https://github.com/dotnet/corefx/blob/b96c29aedf9b2f4197d161f632b4387a17be72f8/src/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerator.Unix.cs#L84
I'm guessing we're then passing that IntPtr.Zero into readdir and it's failing with EBADF. Is it possible in this scenario that a directory here got removed after it was enumerated in the parent folder but before it was opened?  Just speculating.

**Comment by bartonjs** [comment]
@halter73 This one is weird since it's having trouble accessing /usr/lib/ssl/certs.

It looks like we should just wrap these exceptions with CryptographicException, but failure to read the system stores is definitely an irrecoverable event.

**Comment by JeremyKuhne** [comment]
> had this still been a safe handle, we might have had more info

What info specifically?

>  Is it possible in this scenario that a directory here got removed after it was enumerated in the parent folder but before it was opened? 

Hmm. I'll look to see that we have a good test for this.

**Comment by stephentoub** [comment]
> What info specifically?

e.g. whether the SafeHandle was invalid / closed.

**Comment by halter73** [comment]
I haven't seen this in the last several months.
