### ISSUE TITLE
GetILOffset() returning 0 on NETFX

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#28853]
```
 System.Diagnostics.Tests.StackFrameTests/Ctor_Filename_LineNumber(fileName: \"FileName\", lineNumber: 1)   ubwAnalysisIndex
  Xunit.Sdk.TrueException
Windows.10.Amd64.ClientRS2.Open-x86-Release
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Expected GetILOffset() 0 for Ctor_Filename_LineNumber at offset 46 in file:line:column FileName:1:0
 to be greater than zero.
Expected: True
Actual:   False
Stack Trace :
   at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame) in D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs:line 177
   at System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber(String fileName, Int32 lineNumber) in D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs:line 96
```

All these are failing
```
Ctor_Filename_LineNumber(fileName: \"\", lineNumber: 0)	
Ctor_Filename_LineNumber(fileName: \"FileName\", lineNumber: 1)	
Ctor_Filename_LineNumber(fileName: null, lineNumber: -1)	
Ctor_Filename_LineNumber_ColNumber(fileName: \"\", lineNumber: 0, columnNumber: -1)	
Ctor_Filename_LineNumber_ColNumber(fileName: \"FileName\", lineNumber: 1, columnNumber: 2)	
Ctor_Filename_LineNumber_ColNumber(fileName: null, lineNumber: -1, columnNumber: 0)
‐

**Comment by danmosemsft** [comment]
Actually NETFX

**Comment by safern** [comment]
Do you have a link to the failure? Was this on CI?

**Comment by danmosemsft** [comment]
It was on CI, but now i see it in official runs and clearly it's NETFX:

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20180405.01/workItem/System.Diagnostics.StackTrace.Tests

**Comment by safern** [comment]
Yes, it is failing on one of my PRs now: https://mc.dot.net/#/user/safern/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/2def00456d2fb9d1162bd2934eb6423c60585a88/workItem/System.Diagnostics.StackTrace.Tests/analysis/xunit/System.Diagnostics.Tests.StackFrameTests~2FCtor_Filename_LineNumber(fileName:%20%5C%22FileName%5C%22,%20lineNumber:%201)

I'm trying to find why it is happening (seems to be the release pdbs by 1 shift in the offset that @ateoi hit on his PR)

Could the OS version affect this? I.e: running in RS2 rather than RS1?

**Comment by safern** [comment]
Weird, I couldn't get a local repro... I wonder now why this is happening. I want to see if after we build using the .nET 4.7.1 targeting pack this is still happening

**Comment by danmosemsft** [comment]
Could you disable the tests for netfx while you figure it out so CI is clean?

**Comment by safern** [comment]
Done: https://github.com/dotnet/corefx/pull/28869

**Comment by BruceForstall** [comment]
@danmosemsft @safern These tests all fail -- in CoreCLR -- when run under under our JIT MinOpts testing, or a subset fail when run with our JIT Stress mode testing. It appears they might depend on a particular set of inlining, which would make the tests invalid -- you can't depend on what the JIT inlines or not.

Can we get these disabled?

Failure examples:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_corefx_minopts/509/#showFailuresLink
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_corefx_jitstress1/510/#showFailuresLink

When I run it locally (Release x64 Windows corefx, overlaid with Checked x64 Windows coreclr):
```
F:\gh\corefx\bin\tests\System.Diagnostics.StackTrace.Tests\netcoreapp-Windows_NT-Release-x64>set complus_JitMinOpts=1

F:\gh\corefx\bin\tests\System.Diagnostics.StackTrace.Tests\netcoreapp-Windows_NT-Release-x64>call F:\gh\corefx\bin\testhost\netcoreapp-Windows_NT-Release-x64\dotnet.exe xunit.console.netcore.exe System.Diagnostics.StackTrace.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Diagnostics.StackTrace.Tests
Discovered:  System.Diagnostics.StackTrace.Tests
Starting:    System.Diagnostics.StackTrace.Tests
   System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: null, lineNumber: -1, columnNumber: 0) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   8
      Stack Trace:
         F:\gh\corefx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(170,0): at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
         F:\gh\corefx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(112,0): at System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(String fileName, Int32 lineNumber, Int32 columnNumber)
   System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: \"\", lineNumber: 0, columnNumber: -1) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   8
      Stack Trace:
         F:\gh\corefx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(170,0): at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
         F:\gh\corefx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(112,0): at System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(String fileName, Int32 lineNumber, Int32 columnNumber)
   System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: \"FileName\", lineNumber: 1, columnNumber: 2) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   8
      Stack Trace:
         F:\gh\corefx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(170,0): at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
         F:\gh\corefx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(112,0): at System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(String fileName, Int32 lineNumber, Int32 columnNumber)
   System.Diagnostics.Tests.StackFrameTests.SkipFrames_CallMethod_ReturnsExpected [FAIL]
      Assert.NotEqual() Failure
      Expected: Not Void SkipFrames_CallMethod_ReturnsExpected()
      Actual:   Void SkipFrames_CallMethod_ReturnsExpected()
      Stack Trace:
         F:\gh\corefx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(71,0): at System.Diagnostics.Tests.StackFrameTests.SkipFrames_CallMethod_ReturnsExpected()
   System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber(fileName: null, lineNumber: -1) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   7
      Stack Trace:
         F:\gh\corefx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(170,0): at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
         F:\gh\corefx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(97,0): at System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber(String fileName, Int32 lineNumber)
   System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber(fileName: \"\", lineNumber: 0) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   7
      Stack Trace:
         F:\gh\corefx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(170,0): at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
         F:\gh\corefx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(97,0): at System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber(String fileName, Int32 lineNumber)
   System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber(fileName: \"FileName\", lineNumber: 1) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   7
      Stack Trace:
         F:\gh\corefx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(170,0): at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
         F:\gh\corefx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(97,0): at System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber(String fileName, Int32 lineNumber)
Finished:    System.Diagnostics.StackTrace.Tests

=== TEST EXECUTION SUMMARY ===
   System.Diagnostics.StackTrace.Tests  Total: 103, Errors: 0, Failed: 7, Skipped: 0, Time: 6.087s
----- end 13:46:25.92 ----- exit code 1 ----------------------------------------------------------
```

There is another test there that is failing and also looks invalid for the same reason:
System.Diagnostics.Tests.StackFrameTests.SkipFrames_CallMethod_ReturnsExpected

https://github.com/dotnet/coreclr/issues/17557

**Comment by danmosemsft** [comment]
https://github.com/dotnet/coreclr/issues/17558

@BruceForstall these provide valuable coverage. Can we make them more robust by using inlining attributes? Or skip them in jit stress runs? I realize there is no cast iron guarantee.

**Comment by BruceForstall** [comment]
A test that depends on JIT optimization behavior is fragile and, IMO, invalid.

SkipFrames_CallMethod_ReturnsExpected seems particularly bad, e.g.:
```
#if DEBUG
            Assert.Equal(expectedMethod, stackFrame.GetMethod());
#else
            Assert.NotEqual(expectedMethod, stackFrame.GetMethod());
#endif
```
So the code is apparently already, statically, trying to anticipate C# compiler (?) inlining? This test should just be deleted, or fixed to allow any amount of inlining by JIT and/or C# compiler.

Can you explain what this part of VerifyStackFrameSkipFrames() is verifying?
https://github.com/dotnet/corefx/blob/c5525733b5f822b91ce00ef1e6502a2e1a6720e7/src/System.Diagnostics.StackTrace/tests/StackFrameTests.cs#L167-L172
```
#if !DEBUG
            else if ((!PlatformDetection.IsFullFramework && isFileConstructor) || (PlatformDetection.IsFullFramework && !isFileConstructor && !isCurrentFrame && skipFrames == 0))
            {
                Assert.Equal(0, stackFrame.GetILOffset());
            }
#endif
```
I don't understand why this should be guaranteed to be true. It seems particularly problematic, given that there are so many conditions guarding it -- I can only imagine they were added just to make the assert work, not because they guarantee any real underlying invariant.

**Comment by danmosemsft** [comment]
@BruceForstall - my mistake I was thinking of the tests recently added to make sure that "throw;" didn't reset the line number of the throwing frame. These ones, the line number doesn't seem too important. It seems sufficient to check that there is a number present.

**Comment by BruceForstall** [comment]
I think this is no longer an issue, after https://github.com/jkotas/corefx/commit/b8d99dd3cf9b1803f5b4a6b05f9d7fd32106b10d
