### ISSUE TITLE
X509 ExportMultiplePrivateKeys test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2885]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/3248/console
```
Discovering: System.Security.Cryptography.X509Certificates.Tests
  Discovered:  System.Security.Cryptography.X509Certificates.Tests
  Starting:    System.Security.Cryptography.X509Certificates.Tests
     System.Security.Cryptography.X509Certificates.Tests.CollectionTests.ExportMultiplePrivateKeys [FAIL]
        System.Security.Cryptography.CryptographicException : Error occurred during a cryptographic operation.
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\StorePal.Export.cs(82,0): at Internal.Cryptography.Pal.StorePal.Export(X509ContentType contentType, String password)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2Collection.cs(123,0): at System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Export(X509ContentType contentType, String password)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2Collection.cs(116,0): at System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Export(X509ContentType contentType)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\tests\CollectionTests.cs(482,0): at System.Security.Cryptography.X509Certificates.Tests.CollectionTests.ExportMultiplePrivateKeys()
  Finished:    System.Security.Cryptography.X509Certificates.Tests
```

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/3304/console
```
System.Security.Cryptography.X509Certificates.Tests.PfxTests.ExportWithPrivateKey [FAIL]
        System.Security.Cryptography.CryptographicException : Error occurred during a cryptographic operation.
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\StorePal.Export.cs(82,0): at Internal.Cryptography.Pal.StorePal.Export(X509ContentType contentType, String password)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs(176,0): at System.Security.Cryptography.X509Certificates.X509Certificate.Export(X509ContentType contentType, String password)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\tests\PfxTests.cs(83,0): at System.Security.Cryptography.X509Certificates.Tests.PfxTests.ExportWithPrivateKey()
  Finished:    System.Security.Cryptography.X509Certificates.Tests
```

**Comment by stephentoub** [comment]
@bartonjs, it failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/3456/
```
System.Security.Cryptography.X509Certificates.Tests.PfxTests.ExportWithPrivateKey [FAIL]
        System.Security.Cryptography.CryptographicException : Error occurred during a cryptographic operation.
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\StorePal.Export.cs(82,0): at Internal.Cryptography.Pal.StorePal.Export(X509ContentType contentType, String password)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs(176,0): at System.Security.Cryptography.X509Certificates.X509Certificate.Export(X509ContentType contentType, String password)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\tests\PfxTests.cs(84,0): at System.Security.Cryptography.X509Certificates.Tests.PfxTests.ExportWithPrivateKey()
```

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug/1160/console
```
 Discovering: System.Security.Cryptography.X509Certificates.Tests
07:02:18   Discovered:  System.Security.Cryptography.X509Certificates.Tests
07:02:18   Starting:    System.Security.Cryptography.X509Certificates.Tests
07:02:19      System.Security.Cryptography.X509Certificates.Tests.PfxTests.ExportWithPrivateKey [FAIL]
07:02:19         Assert.True() Failure
07:02:19         Expected: True
07:02:19         Actual:   False
07:02:19         Stack Trace:
07:02:19            d:\j\workspace\dotnet_corefx_windows_debug\src\System.Security.Cryptography.X509Certificates\tests\PfxTests.cs(88,0): at System.Security.Cryptography.X509Certificates.Tests.PfxTests.ExportWithPrivateKey()
07:02:19   Finished:    System.Security.Cryptography.X509Certificates.Tests
```

**Comment by stephentoub** [comment]
And again:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/3679/console
```
Discovering: System.Security.Cryptography.X509Certificates.Tests
  Discovered:  System.Security.Cryptography.X509Certificates.Tests
  Starting:    System.Security.Cryptography.X509Certificates.Tests
     System.Security.Cryptography.X509Certificates.Tests.PfxTests.ExportWithPrivateKey [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Security.Cryptography.X509Certificates\tests\PfxTests.cs(89,0): at System.Security.Cryptography.X509Certificates.Tests.PfxTests.ExportWithPrivateKey()
  Finished:    System.Security.Cryptography.X509Certificates.Tests
```

**Comment by stephentoub** [comment]
And again:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/3874/
```
Discovering: System.Security.Cryptography.X509Certificates.Tests
  Discovered:  System.Security.Cryptography.X509Certificates.Tests
  Starting:    System.Security.Cryptography.X509Certificates.Tests
     System.Security.Cryptography.X509Certificates.Tests.PfxTests.ExportWithPrivateKey [FAIL]
        System.Security.Cryptography.CryptographicException : Error occurred during a cryptographic operation.
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\StorePal.Export.cs(82,0): at Internal.Cryptography.Pal.StorePal.Export(X509ContentType contentType, String password)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs(176,0): at System.Security.Cryptography.X509Certificates.X509Certificate.Export(X509ContentType contentType, String password)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\tests\PfxTests.cs(84,0): at System.Security.Cryptography.X509Certificates.Tests.PfxTests.ExportWithPrivateKey()
  Finished:    System.Security.Cryptography.X509Certificates.Tests
```
