### ISSUE TITLE
[arm32] corefx Microsoft.Win32.Registry.Tests failure in CI

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#28856]
@BruceForstall commented on [Wed Apr 04 2018](https://github.com/dotnet/coreclr/issues/17423)

All arm32 corefx test jobs are failing Microsoft.Win32.Registry.Tests with:
```
C:\Users\robox\j\workspace\arm_cross_che---eb7b805d\_\fx\bin\tests\Microsoft.Win32.Registry.Tests\netcoreapp-Windows_NT-Release-arm>call C:\Users\robox\j\workspace\arm_cross_che---eb7b805d\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm\dotnet.exe xunit.console.netcore.exe Microsoft.Win32.Registry.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: Microsoft.Win32.Registry.Tests
Discovered:  Microsoft.Win32.Registry.Tests
Starting:    Microsoft.Win32.Registry.Tests
   Microsoft.Win32.RegistryTests.Registry_SetValue_str_str_obj.SetValueWithEnvironmentVariable(valueName: \"ExpandedTest_45\", envVariableName: \"ProgramFiles\", expectedVariableValue: \"C:\\\\Program Files (Arm)\") [FAIL]
      Assert.Equal() Failure
                                   (pos 18)
      Expected: C:\Program Files (Arm)
      Actual:   C:\Program Files (x86)
                                   (pos 18)
      Stack Trace:
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\Microsoft.Win32.Registry\tests\Registry\Registry_SetValue_str_str_obj.cs(119,0): at Microsoft.Win32.RegistryTests.Registry_SetValue_str_str_obj.SetValueWithEnvironmentVariable(String valueName, String envVariableName, String expectedVariableValue)
   Microsoft.Win32.RegistryTests.RegistryKey_SetValue_str_obj.SetValueWithEnvironmentVariable(valueName: \"ExpandedTest_45\", envVariableName: \"ProgramFiles\", expectedVariableValue: \"C:\\\\Program Files (Arm)\") [FAIL]
      Assert.Equal() Failure
                                   (pos 18)
      Expected: C:\Program Files (Arm)
      Actual:   C:\Program Files (x86)
                                   (pos 18)
      Stack Trace:
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\Microsoft.Win32.Registry\tests\RegistryKey\RegistryKey_SetValue_str_obj.cs(117,0): at Microsoft.Win32.RegistryTests.RegistryKey_SetValue_str_obj.SetValueWithEnvironmentVariable(String valueName, String envVariableName, String expectedVariableValue)
Finished:    Microsoft.Win32.Registry.Tests

=== TEST EXECUTION SUMMARY ===
   Microsoft.Win32.Registry.Tests  Total: 4925, Errors: 0, Failed: 2, Skipped: 0, Time: 18.351s
----- end 22:27:42.93 ----- exit code 1 ----------------------------------------------------------
COREFX TEST FAILED
```

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_corefx_baseline_tst/8/consoleText

---

@RussKeldorph commented on [Thu Apr 05 2018](https://github.com/dotnet/coreclr/issues/17423#issuecomment-379004058)

@danmosemsft Wanna take this to corefx?  It looks like a test issue.

**Comment by danmosemsft** [comment]
Suspect a Windows bug? %ProgramFiles% is apparently "C:\Program Files (Arm)" but if you feed it to ::ExpandEnvironmentStrings you get "C:\Program Files (x86)". 
@RussKeldorph @jfree is there a way to access an ARM32 machine so we can confirm this and file an OS bug?

**Comment by RussKeldorph** [comment]
@danmosemsft Yes, will reach out through email.

**Comment by danmosemsft** [comment]
The older builds we have seem to not repro this. So we have to ignore for now. 

@Anipik could you please cause these tests to skip when envVariableName=ProgramFiles and RuntimeInformation.OSArchitecture=Architecture.Arm?

**Comment by BruceForstall** [comment]
@Anipik Is this now fixed (and can be closed)?

**Comment by Anipik** [comment]
@BruceForstall ywah the tests are disabled for now

**Comment by danmosemsft** [comment]
@Anipik missed a test. I will fix this.
