### ISSUE TITLE
Performance Counter tests failing on spanish CI

### ISSUE THREAD

**Issue by Anipik** [dotnet/corefx#29007]
A couple of the tests are failing
```
System.ComponentModel.Win32Exception : No se puede encontrar el módulo especificado(The specified module can not be found)
Stack Trace :
   at System.Diagnostics.CounterSampleCalculator.LoadPerfCounterDll() in D:\j\workspace\windows-TGrou---db113413\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\CounterSampleCalculator.cs:line 245
   at System.Diagnostics.CounterSampleCalculator.ComputeCounterValue(CounterSample oldSample, CounterSample newSample) in D:\j\workspace\windows-TGrou---db113413\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\CounterSampleCalculator.cs:line 93
   at System.Diagnostics.CounterSampleCalculator.ComputeCounterValue(CounterSample newSample) in D:\j\workspace\windows-TGrou---db113413\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\CounterSampleCalculator.cs:line 56
   at System.Diagnostics.CounterSample.Calculate(CounterSample counterSample) in D:\j\workspace\windows-TGrou---db113413\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\CounterSample.cs:line 148
   at System.Diagnostics.Tests.CounterSampleTests.CounterSample_Calculate_CalculateCounterSample() in D:\j\workspace\windows-TGrou---db113413\src\System.Diagnostics.PerformanceCounter\tests\CounterSampleTests.cs:line 49
```
CounterSample_Calculate_CalculateCounterSample
CounterSample_Calculate_CalculateCounterSampleCounterSample

**Comment by Anipik** [comment]
These tests were not reproducible through repro tool but was reproducible through local Spanish machine

**Comment by brianrob** [comment]
@adiaaida, PTAL.

**Comment by Anipik** [comment]
@brianrob I debugged more into it and found 
```
      System.IO.IOException : No se ha encontrado la ruta de acceso de la red (Network path doesnoot exist)
      Stack Trace:
         c:\git\corefx\src\Microsoft.Win32.Registry\src\Microsoft\Win32\RegistryKey.Windows.cs(979,0): at Microsoft.Win32.RegistryKey.Win32ErrorStatic(Int32 errorCode, String str)
         c:\git\corefx\src\Microsoft.Win32.Registry\src\Microsoft\Win32\RegistryKey.Windows.cs(238,0): at Microsoft.Win32.RegistryKey.OpenRemoteBaseKeyCore(RegistryHive hKey, String machineName, RegistryView view)
         c:\git\corefx\src\Microsoft.Win32.Registry\src\Microsoft\Win32\RegistryKey.cs(347,0): at Microsoft.Win32.RegistryKey.OpenRemoteBaseKey(RegistryHive hKey, String machineName, RegistryView view)
         c:\git\corefx\src\Microsoft.Win32.Registry\src\Microsoft\Win32\RegistryKey.cs(336,0): at Microsoft.Win32.RegistryKey.OpenRemoteBaseKey(RegistryHive hKey, String machineName)
         c:\git\corefx\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\SharedUtils.cs(166,0): at System.Diagnostics.SharedUtils.GetLatestBuildDllDirectory(String machineName)
         c:\git\corefx\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\CounterSampleCalculator.cs(237,0): at System.Diagnostics.CounterSampleCalculator.LoadPerfCounterDll()
         c:\git\corefx\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\CounterSampleCalculator.cs(93,0): at System.Diagnostics.CounterSampleCalculator.ComputeCounterValue(
```

**Comment by Anipik** [comment]
@brianrob I have corrected this. Can you take a look at https://github.com/dotnet/corefx/pull/29009
