### ISSUE TITLE
Unobserved websocket task exceptions when attempting to read/write on non-existent connections

### ISSUE THREAD

**Issue by JustArchi** [dotnet/corefx#29005]
Valid repro: [WebSocketRepro.zip](https://github.com/dotnet/corefx/files/1896745/WebSocketRepro.zip)

Firstly start server with `dotnet run -c Release`, then keep starting client with `dotnet run -c Release` until server app prints the exception we're looking for. Reproducing it might require a few tries, but I've never needed more than 3.

I reproduced it on both latest stable `2.1.103` SDK, as well as `2.1.300-preview1-008174`. This issue seems to be reproducible **only on Windows**, I had no luck running into this issue on linux.

As you can see in the source, we have generic try-catch all across entire flow, which should catch any potential exceptions (and does, we intentionally ignore them since this is working as intended). However, under special circumstances it's possible that we can receive unobserved exception instead, which isn't caught but instead thrown back on `TaskScheduler.UnobservedTaskException`. This doesn't influence the app in any significant way (it doesn't crash or stop working), but if this is expected then it should be observed, similar how it was done in other case I reported: https://github.com/dotnet/corefx/issues/24002 (that has nothing to do with this one).

The exception we're looking for is:

```
Reproduced! This should not happen: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Próbowano wykonać operację na nieistniejącym połączeniu sieciowym) ---> System.Net.HttpListenerException: Próbowano wykonać operację na nieistniejącym połączeniu sieciowym (translation: an attempt was made to perform an operation on a non-existent network connection)
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.ReadAsyncFast(HttpListenerAsyncEventArgs eventArgs)
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.<ReadAsyncCore>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__44.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.HttpListenerException (0x80004005): Próbowano wykonać operację na nieistniejącym połączeniu sieciowym (translation: an attempt was made to perform an operation on a non-existent network connection)
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.ReadAsyncFast(HttpListenerAsyncEventArgs eventArgs)
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.<ReadAsyncCore>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__44.MoveNext()<---
```

![image](https://user-images.githubusercontent.com/1069029/38588663-6436c3a8-3d27-11e8-89ab-1aa99775b4d8.png)

```
Product Information:
 Version:            2.1.300-preview1-008174
 Commit SHA-1 hash:  b8df89a54f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153
```

*Initial issue reported in: https://github.com/mono/linker/issues/295*

Thank you in advance.

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by karelz** [comment]
@caesar1995 can you please try to reproduce this issue? Is it regression against 2.0? Thanks!

**Comment by stephentoub** [comment]
It is not a regression.

**Comment by karelz** [comment]
Thanks @stephentoub!

**Comment by davidsh** [comment]
I took a look at this issue.  I was able to determine what Task was keeping an unobserved exception.

This code originally came from .NET Framework.  It is specific to Windows only and uses the HttpListener as the server for the WebSocket.

I was able to reproduce the problem on .NET Framework as well.

```
C:\Users\davidsh\Downloads\WebSocketRepro\WebSocketServer>dotnet run -f net47
(Framework: C:\Windows\Microsoft.NET\Framework64\v4.0.30319)
Listening...
Reproduced! This should not happen: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Net.HttpListenerException: An operation was attempted on a nonexistent network connection
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.ReadAsyncFast(HttpListenerAsyncEventArgs eventArgs)
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.<ReadAsyncCore>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.HttpListenerException (0x80004005): An operation was attempted on a nonexistent network connection
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.ReadAsyncFast(HttpListenerAsyncEventArgs eventArgs)
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.<ReadAsyncCore>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()<---
```
