### ISSUE TITLE
Several tests failing on Windows with WindowsCryptographicException

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#29045]
From https://github.com/dotnet/corefx/pull/29039
https://mc.dot.net/#/user/ahsonkhan/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/ea9a71a9aadc8553dd482a156893a53e58554707/workItem/System.Data.SqlClient.Tests/analysis/xunit/System.Data.SqlClient.Tests.DiagnosticTest~2FConnectionOpenAsyncErrorTest
Windows.10.Amd64.Open-x64-Debug
```text
Unhandled Exception of Type System.Diagnostics.RemoteExecutorTestBase+RemoteInvokeHandle+RemoteExecutionException
Message :
System.Diagnostics.RemoteExecutorTestBase+RemoteInvokeHandle+RemoteExecutionException : Remote process failed with an unhandled exception.
Stack Trace :

Child exception:
  Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The profile for the user is a temporary profile
   at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 153
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 88
   at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 26
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs:line 135
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs:line 116
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2.cs:line 88
   at Microsoft.SqlServer.TDS.Servers.TDSServerArguments..ctor() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Data.SqlClient\tests\Tools\TDS\TDS.Servers\TDSServerArguments.cs:line 91
   at System.Data.SqlClient.Tests.DiagnosticsQueryEngine..ctor() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Data.SqlClient\tests\FunctionalTests\DiagnosticTest.cs:line 923
   at System.Data.SqlClient.Tests.DiagnosticTest.CollectStatisticsDiagnosticsAsync(Func`2 sqlOperation, String methodName) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Data.SqlClient\tests\FunctionalTests\DiagnosticTest.cs:line 892
   at System.Data.SqlClient.Tests.DiagnosticTest.<>c.<ConnectionOpenAsyncErrorTest>b__23_0() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Data.SqlClient\tests\FunctionalTests\DiagnosticTest.cs:line 505

Child process:
  System.Data.SqlClient.Tests, Version=4.4.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb System.Data.SqlClient.Tests.DiagnosticTest+<>c Int32 <ConnectionOpenAsyncErrorTest>b__23_0()
```

cc @bartonjs

**Comment by ahsonkhan** [comment]
System.Net.Http.Functional.Tests GetAsync_SecureAndNonSecureIPBasedUri_CorrectlyFormatted
Windows.10.Amd64.Open-x86-Release
https://mc.dot.net/#/user/ahsonkhan/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/ea9a71a9aadc8553dd482a156893a53e58554707/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandlerTest~2FGetAsync_SecureAndNonSecureIPBasedUri_CorrectlyFormatted(address:%20127.0.0.1,%20useSsl:%20True)
```text
Unhandled Exception of Type Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException
Message :
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : The profile for the user is a temporary profile
Stack Trace :
   at Internal.Cryptography.Pal.StorePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\StorePal.Import.cs:line 77
   at System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(String fileName, String password, X509KeyStorageFlags keyStorageFlags) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2Collection.cs:line 164
   at System.Net.Test.Common.Configuration.Certificates.GetCertificateCollection(String certificateFileName) in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\Net\Configuration.Certificates.cs:line 65
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 99
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 64
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 92
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass11_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 67
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_SecureAndNonSecureIPBasedUri_CorrectlyFormatted(IPAddress address, Boolean useSsl) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 605
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by ahsonkhan** [comment]
System.Security.Cryptography.Xml.Tests
Windows.10.Amd64.Open-x86-Release
https://mc.dot.net/#/user/ahsonkhan/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/ea9a71a9aadc8553dd482a156893a53e58554707/workItem/System.Security.Cryptography.Xml.Tests/analysis/xunit/System.Security.Cryptography.Xml.Tests.EncryptedXmlTest~2FRsaDecryption(resourceName:%20%5C%22System.Security.Cryptography.Xml.Tests.EncryptedXm%5C%22...)

```text
Unhandled Exception of Type Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException
Message :
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : The profile for the user is a temporary profile
Stack Trace :
   at System.Security.Cryptography.CngKey.Open(String keyName, CngProvider provider, CngKeyOpenOptions openOptions) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Security.Cryptography.Cng\src\System\Security\Cryptography\CngKey.Open.cs:line 43
   at Internal.Cryptography.Pal.CertificatePal.GetPrivateKey[T](Func`2 createCsp, Func`2 createCng) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.PrivateKey.cs:line 196
   at Internal.Cryptography.Pal.CertificatePal.GetRSAPrivateKey() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.PrivateKey.cs:line 29
   at Internal.Cryptography.Pal.CertificateExtensionsCommon.GetPrivateKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\CertificateExtensionsCommon.cs:line 52
   at System.Security.Cryptography.Xml.Tests.EncryptedXmlTest.RsaDecryption(String resourceName) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Security.Cryptography.Xml\tests\EncryptedXmlTest.cs:line 109
```

**Comment by ahsonkhan** [comment]
Duplicate of https://github.com/dotnet/corefx/issues/28631
