### ISSUE TITLE
Microsoft.Windows.Compatibility breaks Dictionary binary deserialization

### ISSUE THREAD

**Issue by martin-frydl** [dotnet/corefx#29089]
I have .NET Core 2.0 project with following code:
```csharp
    public class Program {
        static void Main(string[] args) {
            using (var stream = new MemoryStream()) {
                var formatter = new BinaryFormatter();
                formatter.Serialize(stream, new Dictionary<string, string>());
                stream.Seek(0, SeekOrigin.Begin);
                formatter.Deserialize(stream);
            }
        }
    }
```
When run, it works fine. But when I add Microsoft.Windows.Compatibility as dependency, deserialization fails with exception:
```
Unhandled Exception: System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Runtime.Serialization.FormatterConverter.Convert(Object value, Type type)
   at System.Runtime.Serialization.SerializationInfo.GetValue(String name, Type type)
   at System.Collections.Generic.Dictionary`2.OnDeserialization(Object sender)
   at System.Runtime.Serialization.ObjectManager.RaiseDeserializationEvent()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at ConsoleApp1.Program.Main(String[] args) in C:\devel\core\ConsoleApp1\Program.cs:line 13
```
Just added as dependency, not used for anything (yet). And breaks the deserialization of Dictionary<string,string>.

I was able to narrow the package to Microsoft.Windows.Compatibility.Shims - add just this one as dependency and it breaks.

**Comment by karelz** [comment]
@ViktorHofer can you help? cc @danmosemsft

**Comment by danmosemsft** [comment]
That's not good.

**Comment by kasper3** [comment]
seems to be fixed in 2.1.

download and extract https://dotnetcli.azureedge.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.zip to a directory `c:\dotnet21\`

create a project by hand, `mkdir test` and `test\notepad test.csproj`
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.0;netcoreapp2.1</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="2.0.0-preview2-26406-04" />
  </ItemGroup>
</Project>
```

`test.cs`

```c#
using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;
public class Program {
    static void Main(string[] args) {
        using (var stream = new MemoryStream()) {
            var formatter = new BinaryFormatter();
            formatter.Serialize(stream, new Dictionary<string, string>());
            stream.Seek(0, SeekOrigin.Begin);
            formatter.Deserialize(stream);
        }
    }
}
```

`c:\dotnet21\dotnet run -f netcoreapp2.0` fails with exception.
`c:\dotnet21\dotnet run -f netcoreapp2.1` throws no exception.

**Comment by karelz** [comment]
Closing as fixed then.

**Comment by karelz** [comment]
Thanks @kasper3 for verification!
