### ISSUE TITLE
Failed SslStream assert in new HttpClient perf tests on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#29127]
This appears to be happening consistently across all distros/versions, Linux and macOS.
```
2018-04-15 12:54:25,475: INFO: proc(54): run_and_log_output: Output: Assertion Failed
2018-04-15 12:54:25,475: INFO: proc(54): run_and_log_output: Output: 
2018-04-15 12:54:25,476: INFO: proc(54): run_and_log_output: Output:    at System.Net.Security.SslStreamInternal.ResetReadBuffer() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/src/System/Net/Security/SslStreamInternal.cs:line 185
2018-04-15 12:54:25,476: INFO: proc(54): run_and_log_output: Output:    at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/src/System/Net/Security/SslStreamInternal.cs:line 256
2018-04-15 12:54:25,476: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 930
2018-04-15 12:54:25,476: INFO: proc(54): run_and_log_output: Output:    at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
2018-04-15 12:54:25,477: INFO: proc(54): run_and_log_output: Output:    at System.Net.Security.SslStreamInternal.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/src/System/Net/Security/SslStreamInternal.cs:line 158
2018-04-15 12:54:25,477: INFO: proc(54): run_and_log_output: Output:    at System.Net.Security.SslStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 739
2018-04-15 12:54:25,477: INFO: proc(54): run_and_log_output: Output:    at System.IO.StreamReader.ReadBufferAsync() in /Users/buildagent/agent/_work/147/s/src/mscorlib/shared/System/IO/StreamReader.cs:line 1328
2018-04-15 12:54:25,478: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 930
2018-04-15 12:54:25,478: INFO: proc(54): run_and_log_output: Output:    at System.IO.StreamReader.ReadBufferAsync()
2018-04-15 12:54:25,478: INFO: proc(54): run_and_log_output: Output:    at System.IO.StreamReader.ReadLineAsyncInternal() in /Users/buildagent/agent/_work/147/s/src/mscorlib/shared/System/IO/StreamReader.cs:line 888
2018-04-15 12:54:25,478: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 930
2018-04-15 12:54:25,479: INFO: proc(54): run_and_log_output: Output:    at System.IO.StreamReader.ReadLineAsyncInternal()
2018-04-15 12:54:25,479: INFO: proc(54): run_and_log_output: Output:    at System.IO.StreamReader.ReadLineAsync() in /Users/buildagent/agent/_work/147/s/src/mscorlib/shared/System/IO/StreamReader.cs:line 878
2018-04-15 12:54:25,479: INFO: proc(54): run_and_log_output: Output:    at System.Net.Http.Tests.SocketsHttpHandlerPerfTest.<>c__DisplayClass2_3.<<Get>b__0>d.MoveNext() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Http/tests/Performance/Perf.SocketsHttpHandler.cs:line 68
2018-04-15 12:54:25,479: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /Users/buildagent/agent/_work/147/s/src/mscorlib/shared/System/Threading/ExecutionContext.cs:line 167
2018-04-15 12:54:25,480: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 559
2018-04-15 12:54:25,480: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Threading/Tasks/TaskContinuation.cs:line 798
2018-04-15 12:54:25,480: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Threading/Tasks/Task.cs:line 3275
2018-04-15 12:54:25,481: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Threading/Tasks/future.cs:line 421
2018-04-15 12:54:25,481: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 639
2018-04-15 12:54:25,481: INFO: proc(54): run_and_log_output: Output:    at System.IO.StreamReader.ReadLineAsyncInternal() in /Users/buildagent/agent/_work/147/s/src/mscorlib/shared/System/IO/StreamReader.cs:line 948
2018-04-15 12:54:25,481: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /Users/buildagent/agent/_work/147/s/src/mscorlib/shared/System/Threading/ExecutionContext.cs:line 167
2018-04-15 12:54:25,482: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 559
2018-04-15 12:54:25,482: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Threading/Tasks/TaskContinuation.cs:line 798
2018-04-15 12:54:25,482: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Threading/Tasks/Task.cs:line 3275
2018-04-15 12:54:25,482: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Threading/Tasks/future.cs:line 421
2018-04-15 12:54:25,483: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 639
2018-04-15 12:54:25,483: INFO: proc(54): run_and_log_output: Output:    at System.IO.StreamReader.ReadBufferAsync() in /Users/buildagent/agent/_work/147/s/src/mscorlib/shared/System/IO/StreamReader.cs:line 1361
2018-04-15 12:54:25,483: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /Users/buildagent/agent/_work/147/s/src/mscorlib/shared/System/Threading/ExecutionContext.cs:line 167
2018-04-15 12:54:25,483: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 559
2018-04-15 12:54:25,484: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Threading/Tasks/TaskContinuation.cs:line 798
2018-04-15 12:54:25,484: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Threading/Tasks/Task.cs:line 3275
2018-04-15 12:54:25,484: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Threading/Tasks/future.cs:line 421
2018-04-15 12:54:25,485: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 639
2018-04-15 12:54:25,485: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result) in /Users/buildagent/agent/_work/147/s/src/mscorlib/shared/System/Runtime/CompilerServices/AsyncValueTaskMethodBuilder.cs:line 169
2018-04-15 12:54:25,485: INFO: proc(54): run_and_log_output: Output:    at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/src/System/Net/Security/SslStreamInternal.cs:line 339
2018-04-15 12:54:25,486: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /Users/buildagent/agent/_work/147/s/src/mscorlib/shared/System/Threading/ExecutionContext.cs:line 167
2018-04-15 12:54:25,486: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 559
2018-04-15 12:54:25,486: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Threading/Tasks/TaskContinuation.cs:line 798
2018-04-15 12:54:25,487: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Threading/Tasks/Task.cs:line 3275
2018-04-15 12:54:25,487: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Threading/Tasks/future.cs:line 421
2018-04-15 12:54:25,487: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 639
2018-04-15 12:54:25,487: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 629
2018-04-15 12:54:25,488: INFO: proc(54): run_and_log_output: Output:    at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/src/System/Net/Security/SslStreamInternal.cs:line 516
2018-04-15 12:54:25,488: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /Users/buildagent/agent/_work/147/s/src/mscorlib/shared/System/Threading/ExecutionContext.cs:line 167
2018-04-15 12:54:25,488: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 559
2018-04-15 12:54:25,489: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1038
2018-04-15 12:54:25,489: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 869
2018-04-15 12:54:25,490: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs:line 780
2018-04-15 12:54:25,490: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketFlags flags, SocketError socketError) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs:line 402
2018-04-15 12:54:25,491: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallbackCore(Int32 bytesTransferred, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError socketError) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs:line 121
2018-04-15 12:54:25,491: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.InvokeCallback(Boolean allowPooling) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 463
2018-04-15 12:54:25,491: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 853
2018-04-15 12:54:25,492: INFO: proc(54): run_and_log_output: Output:    at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.<>c.<.cctor>b__18_0(Object op) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 697
2018-04-15 12:54:25,492: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ThreadPoolWorkQueue.Dispatch() in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/Threading/ThreadPool.cs:line 588
```

**Comment by stephentoub** [comment]
It happens every time for me with the:
```
System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(ssl: True, connectionPerRequest: False, chunkedResponse: False, responseLength: 1)
```
test.
