### ISSUE TITLE
System.Threading.Tasks.Tests.CancelWait.TaskCancelWaitTestCases.TaskCancelWait1 failed in CI

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#2914]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/1989/testReport/junit/System.Threading.Tasks.Tests.CancelWait/TaskCancelWaitTestCases/TaskCancelWait1/

MESSAGE:
Expected Result to lie between 1.63 and 1.65 for completed task. Actual Result -42. Using n=Light IsCanceled=False Expected: True Actual: False
+++++++++++++++++++
STACK TRACE:
at System.Threading.Tasks.Tests.CancelWait.TaskCancelWaitTest.VerifyResult(TaskInfo current) at System.Threading.Tasks.Tests.CancelWait.TaskCancelWaitTest.<Verify>b__3(TaskInfo current) at System.Threading.Tasks.Tests.CancelWait.TaskInfo.Traversal(Action`1 predicate) at System.Threading.Tasks.Tests.CancelWait.TaskCancelWaitTest.Verify() at System.Threading.Tasks.Tests.CancelWait.TaskCancelWaitTest.RealRun() at System.Threading.Tasks.Tests.CancelWait.TaskCancelWaitTestCases.TaskCancelWait1()

**Comment by Priya91** [comment]
failed again here

```
MESSAGE:
Task which has been explicitly cancel-requested either by parent must have CancellationRequested set as true\nExpected: True\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.Threading.Tasks.Tests.CancelWait.TaskCancelWaitTest.VerifyCancel(TaskInfo current) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug_prtest/src/System.Threading.Tasks/tests/Task/TaskCancelWaitTest.cs:line 262 at System.Threading.Tasks.Tests.CancelWait.TaskCancelWaitTest.<Verify>b__12_0(TaskInfo current) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug_prtest/src/System.Threading.Tasks/tests/Task/TaskCancelWaitTest.cs:line 208 at System.Threading.Tasks.Tests.CancelWait.TaskInfo.Traversal(Action`1 predicate) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug_prtest/src/System.Threading.Tasks/tests/Task/TaskCancelWaitTest.cs:line 584 at System.Threading.Tasks.Tests.CancelWait.TaskCancelWaitTest.Verify() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug_prtest/src/System.Threading.Tasks/tests/Task/TaskCancelWaitTest.cs:line 203 at System.Threading.Tasks.Tests.CancelWait.TaskCancelWaitTest.RealRun() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug_prtest/src/System.Threading.Tasks/tests/Task/TaskCancelWaitTest.cs:line 118 at System.Threading.Tasks.Tests.CancelWait.TaskCancelWaitTestCases.TaskCancelWait1() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug_prtest/src/System.Threading.Tasks/tests/Task/TaskCancelWaitTests.cs:line 25
```

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_fedora24_debug_prtest/11/testReport/junit/System.Threading.Tasks.Tests.CancelWait/TaskCancelWaitTestCases/TaskCancelWait1/

**Comment by danmosemsft** [comment]
Moved @Priya91 's issue above to https://github.com/dotnet/corefx/issues/20457 as it's different.
