### ISSUE TITLE
File.OpenRead () calls Win32 apis when running on Linux.

### ISSUE THREAD

**Issue by danwalmsley** [dotnet/corefx#29157]
This is an issue @jmacato has come across on Kubuntu and Ubuntu.

(I cant reproduce on my system, so must be something confusing .net runtime. specific to his system.)

to repro make a console application and call File.OpenRead()

the exception:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Could not find file '/mscorlib.dll'.) ---> System.IO.FileNotFoundException: Could not find file '/mscorlib.dll'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptionsoptions)
   at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)
```

here is the affected systems environment incase it helps:

```
KDE_MULTIHEAD=false
CLUTTER_IM_MODULE=xim
GS_LIB=/home/<redacted>/.fonts
KDE_FULL_SESSION=true
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LESSCLOSE=/usr/bin/lesspipe %s %s
LANG=en_PH.UTF-8
DISPLAY=:0
COLORTERM=truecolor
XDG_VTNR=7
PAM_KWALLET5_LOGIN=
QT_QUICK_CONTROLS_STYLE=org.kde.desktop
SSH_AUTH_SOCK=
MANDATORY_PATH=/usr/share/gconf//usr/share/xsessions/plasma.mandatory.path
XDG_SESSION_ID=3
USER=<redacted>
DESKTOP_SESSION=/usr/share/xsessions/plasma
QT4_IM_MODULE=xim
TEXTDOMAINDIR=/usr/share/locale/
GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/<redacted>/.gtkrc-2.0:/home/<redacted>/.config/gtkrc-2.0
DEFAULTS_PATH=/usr/share/gconf//usr/share/xsessions/plasma.default.path
PWD=/home/<redacted>/Desktop
HOME=/home/<redacted>
TEXTDOMAIN=im-config
SSH_AGENT_PID=1202
QT_ACCESSIBILITY=1
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/usr/share//usr/share/xsessions/plasma:/usr/local/share:/usr/share:/var/lib/snapd/desktop
XDG_SESSION_DESKTOP=KDE
TERM=xterm-termite
SHELL=/bin/bash
VTE_VERSION=4802
XDG_SESSION_CLASS=user
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
QT_IM_MODULE=xim
XMODIFIERS=@im=fcitx
IM_CONFIG_PHASE=2
XCURSOR_THEME=breeze_cursors
XDG_CURRENT_DESKTOP=KDE
DOTNET_CLI_TELEMETRY_OPTOUT=1
XDG_SEAT=seat0
SHLVL=1
LANGUAGE=en_US:en_GB
GTK_RC_FILES=/etc/gtk/gtkrc:/home/<redacted>/.gtkrc:/home/<redacted>/.config/gtkrc
WINDOWID=96468995
LOGNAME=<redacted>
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-oLdDcAMVfg,guid=89c25e66de149eef77c1405a5ad5b765
XDG_RUNTIME_DIR=/run/user/1000
PAM_KWALLET_LOGIN=/run/user/1000/kwallet.socket
XAUTHORITY=/tmp/xauth-1000-_0
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
QT_AUTO_SCREEN_SCALE_FACTOR=0
XDG_CONFIG_DIRS=/etc/xdg/xdg-/usr/share/xsessions/plasma:/etc/xdg:/usr/share/kubuntu-default-settings/kf5-settings
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
KDE_SESSION_UID=1000
KDE_SESSION_VERSION=5
SESSION_MANAGER=local/n550jk:@/tmp/.ICE-unix/1257,unix/n550jk:/tmp/.ICE-unix/1257
LESSOPEN=| /usr/bin/lesspipe %s
GTK_IM_MODULE=xim
OLDPWD=/home/<redacted>/Desktop/AvalonStudio/AvalonStudio/AvalonStudio/bin/Debug/netcoreapp2.0/debian.8-x64/publish
_=/usr/bin/printenv
```

Any further information we can get to help debug the issue?

**Comment by karelz** [comment]
Which version of .NET Core did you use? (`dotnet --info`) Are you able to reproduce it on more than one VM/machine?
Did you use command line to build your app?

**Comment by jmacato** [comment]
@karelz yes, i've tried it on two linux machines, one has this dotnet --info

```
.NET Command Line Tools (2.1.4)

Product Information:
Version: 2.1.4
Commit SHA-1 hash: 5e8add2190

Runtime Environment:
OS Name: ubuntu
OS Version: 17.10
OS Platform: Linux
RID: linux-x64
Base Path: /usr/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

Version : 2.0.5
Build : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

and other one:

```
.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.10
 OS Platform: Linux
 RID:         ubuntu.17.10-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```

The app in questions was @danwalmsley 's VitalElement/AvalonStudio (fixes/csharp-symbol-query-polish) branch and ran `dotnet run -f netcoreapp2.0 `. Then i tried opening AvaloniaUI/Avalonia 's repo on it and that specific exception was thrown.

**Comment by danwalmsley** [comment]
You can repro with just File.OpenRead call. Iv tried on similar systems and can't reproduce.

**Comment by danwalmsley** [comment]
[Repro.zip](https://github.com/dotnet/corefx/files/1921115/Repro.zip)

@karelz ok there is the repro.

It will crash on 2x machines that @jmacato  has (with dotnet info provided above)

**Comment by jmacato** [comment]
Trying out the repro, and it didn't throw an exception unless the file is non-existent (from "file.txt", i changed it to "/file.txt" because it's similar to the "/mscorlib.dll" error that i encountered

```
Exception has occurred: CLR/System.IO.FileNotFoundException
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in System.Private.CoreLib.dll: 'Could not find file '/file.txt'.'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at Repro.Program.Main(String[] args) in /home/hikarisei23/Desktop/Repro/Program.cs:line 10
```

**Comment by danwalmsley** [comment]
ok the repro hasnt worked. I will get back with a working repro in the morning.

**Comment by danwalmsley** [comment]
I think my title for this issue might not be correct. The exception:

System.IO.FileNotFoundException: Could not find file '/mscorlib.dll'.

looks like its trying to locate mscorlib in root directory for some reason.

**Comment by danwalmsley** [comment]
after a clean install of the OS this issue went away. I'll close the issue, and come back if we encounter again.
