### ISSUE TITLE
TraceInternal fails with null reference exception

### ISSUE THREAD

**Issue by shueybubbles** [dotnet/corefx#29196]
We publish Microsoft.SqlServer.SqlManagementObjects to Nuget.Org with NetStandard2.0 binaries. One of our customers built an app and runs it on Ubuntu with netcore-hosting and the app crashes:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Diagnostics.TraceInternal.get_AppName()
   at System.Diagnostics.TraceInternal.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args)
   at Microsoft.SqlServer.Management.Smo.ExecutionManager.GetEnumeratorData(Request req)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.GetDbCollation(String dbname)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.GetDbComparer(Boolean inServer)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitializeStringComparer()
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.get_StringComparer()
   at Microsoft.SqlServer.Management.Smo.SimpleObjectCollectionBase.InitInnerCollection()
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.InitializeChildCollection(Boolean refresh, ScriptingPreferences sp, String filterQuery, IEnumerable`1 extraFields)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.GetEnumerator(ScriptingPreferences sp)
   at SMOLib.GetDatabases() in C:\temp\demo_SMOLib\SMOLib\SMOLib\Program.cs:line 42
```

Looking at the code for TraceInternal, it appears to use `GetEntryAssembly().GetName().Name`, but from looking around the repo it appears GetEntryAssembly() can return null in some cases. 
Is there a workaround the customer could put in his app to make this work? It seems like TraceInternal.AppName should be checking for null and using something else for its value.

**Comment by stephentoub** [comment]
Reopening for 2.1

**Comment by karelz** [comment]
Ported in PR #29228 to release/2.1 branch
