### ISSUE TITLE
System.Data.SqlClient .NET Core 2.1.3 Preview 2 - Unable to open connection to the database

### ISSUE THREAD

**Issue by brettkc** [dotnet/corefx#29193]
Unable to use System.Data.SqlClient to open a connection in .NET Core 2.1.3 Preview 2. I also tried previous versions of .NET Core 2 and encountered the same issue. I also manually updated to use the latest preview version of System.Data.SqlClient and same outcome. 

**DB in question is SQL Server 2008 R2 running in 2000 compatibility mode, though this has never been an issue previously**

**UPDATE: Querying the 2008 instance as a linked server through a SQL Server 2016 instance DOES work.**

# **Code**
```c#
public IEnumerable<string> Get()
{
    using (var db = new SqlConnection(@"valid conn string"))
    {
        try
        {
            db.Open();
            db.Close();
        }
        catch (Exception e)
        {
            var trace = e.StackTrace;
        }
    }
    return new string[] { };
}
```

# **Environment**

- Running locally on Win 10 when this happens

# **Exception**
```
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at MyDumbAPI.Controllers.ValuesController.Get() in C:\dev\MyDumbAPI\Controllers\ValuesController.cs:line 19
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:-1,State:0,Class:20
```

# **Reproduce**

- Create new .NET Core console or web application
- Try and use SqlClient API to open a connection to a SQL Server database

# **dotnet --info**
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview2-008530
 Commit:    822ae6d43a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview2-008530\

Host (useful for support):
  Version: 2.1.0-preview2-26406-04
  Commit:  6833f3026b

.NET Core SDKs installed:
  1.0.0-preview2-003121 [C:\Program Files\dotnet\sdk]
  1.0.0-preview2.1-003155 [C:\Program Files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.300-preview2-008530 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0-preview1-001100-00 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by karelz** [comment]
@David-Engel this looks similar to the known Preview2 issue, but according to the report the same behavior is on .NET Core 2., so maybe it is different problem?

**Comment by David-Engel** [comment]
@brettkc Can you include the full exception from e.ToString()? I was able to connect fine to a SQL Server 2008 R2 instance with a DB running in SQL Server 2000 compatibility mode using .NET Core 2.0 and System.Data.SqlClient (4.4.3).

**Comment by David-Engel** [comment]
@brettkc The error simply indicates the instance specified in the connection string cannot be accessed or found. Are you sure you can access the host referenced in the SERVER value of your connection string from the machine you are running from? Are you escaping the backslash between the host name and the instance name in the SERVER value?

**Comment by brettkc** [comment]
@David-Engel Yes, I spent quite a bit of time completely bewildered. I just copied the controller verbatim in a .NET Framework 4.6.1 project and had no issues at all.

**Comment by David-Engel** [comment]
@brettkc I've not been able to reproduce the issue. Can you add the output from `dotnet --info` to make sure we try using the same versions?

**Comment by brettkc** [comment]
@David-Engel update issue with output.

**Comment by keeratsingh** [comment]
Hi @brettkc ,

I ran the code on Windows 10 `Version 10.0.16299 Build 16299` with SqlClient version `4.5.0-rc1-26424-04` and dotnet runtime version `Microsoft.NETCore.App 2.1.0-preview2-26406-04`, which is exactly the same runtime you are using and I don't see any issues with SQLServer2008 R2 DB with Compatibility mode `SQLServer2000(80)` set.
It seems like a setup issue in your environment, could you kindly share the connection string and the contents of your csproj file you are using.

### Code
```cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;

namespace adhoc
{
    class gh_29193_sqlserver2008
    {
        static void Main(string[] args)
        {
            try
            {
                Get();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }
        public static IEnumerable<string> Get()
        {
            string strConn = "Data Source=localhost,1408;Initial Catalog=master;Integrated Security=True;";
            using (SqlConnection Conn = new SqlConnection(strConn))
            {
                try
                {
                    Conn.Open();
                    Console.WriteLine("Connection Open\n");
                    SqlCommand sqlCommand1 = new SqlCommand("SELECT @@VERSION,compatibility_level FROM sys.databases WHERE name = 'master';", Conn);
                    SqlDataReader dataReader = sqlCommand1.ExecuteReader();
                    while (dataReader.Read())
                        Console.WriteLine("Compatibility Level = {0}\nSQLServer Version = {1}", dataReader.GetByte(1), dataReader.GetString(0));
                    
                    Conn.Close();
                    Console.WriteLine("Connection Close");
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.StackTrace);
                }
            }
            return new string[] { };
        }

    }
}


```
### Dotnet --info and Shell logs.
```cmd
PS C:\adhoc> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview2-008533
 Commit:    996eb6c92c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview2-008533\

Host (useful for support):
  Version: 2.1.0-preview2-26406-04
  Commit:  6833f3026b

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.300-preview2-008533 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
PS C:\adhoc> dotnet run
Connection Open

Compatibility Level = 80
SQLServer Version = Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (X64)
        Apr  2 2010 15:48:46
        Copyright (c) Microsoft Corporation
        Developer Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: )

Connection Close
PS C:\adhoc>

```

**Comment by brettkc** [comment]
@keeratsingh thanks for investigating

connection string is in this shape:
```c#
using (var db = new SqlConnection(@"data source=DNSName\sqlstaging;initial catalog=DB;persist security info=True;user id=MYUSER;password=MYPASSWORD;multipleactiveresultsets=True"))
```

.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="1.50.4" />
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-preview2-final" />
    <PackageReference Include="System.Data.SqlClient" Version="4.5.0-preview2-26406-04" />
  </ItemGroup>
</Project>
```

**Comment by keeratsingh** [comment]
Closing due to inactivity. Please feel free to reopen if you face the issue again.
