### ISSUE TITLE
Invalid HttpListener.Stop() behaviour

### ISSUE THREAD

**Issue by maincoon** [dotnet/corefx#29236]
SDK
 Version:   2.1.300-preview2-008533
 Commit:    996eb6c92c

Runtime
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64

Host (useful for support):
  Version: 2.1.0-preview2-26406-04
  Commit:  6833f3026b

Method description says "Causes this instance to stop receiving incoming requests." 

In fact after this call all client connections created with specified HttpListener being closed with error.
```
Error System.Net.WebSockets.WebSocketException (0x80004005): An internal WebSocket error occurred. Please see the innerException, if present, for more details.  ---> System.Net.HttpListenerException (995): Операция ввода/вывода была прервана из-за завершения потока команд или по запросу приложения
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.ReadAsyncCore(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.Process(Nullable`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketBase.ReceiveAsyncCore(ArraySegment`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boolean aborted)
   at System.Net.WebSockets.WebSocketBase.ReceiveAsyncCore(ArraySegment`1 buffer, CancellationToken cancellationToken)
   at WSTest.Program.Reader(WebSocket webSocket) in C:\Projects\Globo\skillgames\BRANCH\dev\UpDAU\tests\WSTest\Program.cs:line 49
```

In addition after HttpListener.Stop() call opened ClientWebSocket connection has "Open" state but if ClientWebSocket .Close() call performed exception being thrown.

```
Close failed System.IO.IOException: Unable to read data from the transport connection: Удаленный хост принудительно разорвал существующее подключение. ---> System.Net.Sockets.SocketException: Удаленный хост принудительно разорвал существующее подключение
   --- End of inner exception stack trace ---
   at System.Net.WebSockets.ManagedWebSocket.SendCloseFrameAsync(WebSocketCloseStatus closeStatus, String closeStatusDescription, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.CloseAsyncPrivate(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)
   at WSTest.Program.Test() in C:\Projects\Globo\skillgames\BRANCH\dev\UpDAU\tests\WSTest\Program.cs:line 94
```

Here is code I've used to test this case. 

```c#
using System;
using System.Net;
using System.Net.WebSockets;
using System.Threading;
using System.Threading.Tasks;

namespace WSTest {
	class Program {
		static HttpListener listener = new HttpListener();

		static void RunLiStenerAsync(string enpoint) {
			TaskCompletionSource<bool> tcs = new TaskCompletionSource<bool>();
			Task.Run(async () => {
				try {
					listener.Prefixes.Add($"http://{enpoint}/");
					listener.Start();
					tcs.SetResult(true);
					while (listener.IsListening) {
						HttpListenerContext context = listener.GetContext();
						if (!context.Request.IsWebSocketRequest) {
							context.Response.Close();
						} else {
							WebSocket ws = (await context.AcceptWebSocketAsync(null)).WebSocket;
							Console.WriteLine("Got client connection");
							// start reader async
							StartReaderAsync(ws);

						}
					}
					Console.WriteLine($"Stop listen at ws://{enpoint}");
				} catch (Exception ex) {
					Console.WriteLine($"Server failed {ex.ToString()}");
				}
			});
			tcs.Task.Wait();
			Console.WriteLine($"Listen at ws://{enpoint}");
		}

		static void StartReaderAsync(WebSocket webSocket) {
			Task.Run(async () => {
				await Reader(webSocket);
			});
		}

		static async Task Reader(WebSocket webSocket) {
			int received = 0;
			while (true) {
				try {
					WebSocketReceiveResult result = await webSocket.ReceiveAsync(new ArraySegment<byte>(new byte[1024]), CancellationToken.None);
					switch (result.MessageType) {
						case WebSocketMessageType.Text:
						case WebSocketMessageType.Binary:
							// chunked packets assembling here
							received += result.Count;
							if (result.EndOfMessage == true) {
								Console.WriteLine($"Received packet {received} bytes");
								received = 0;
							} else {
								Console.WriteLine($"Received chunk {result.Count} bytes");
							}
							break;
						case WebSocketMessageType.Close:
							Console.WriteLine($"Client disconected");
							await webSocket.CloseAsync(WebSocketCloseStatus.Empty, null, CancellationToken.None);
							return;
					}
				} catch (Exception ex) {
					Console.WriteLine($"Error {ex.ToString()}");
					return;
				}
			}
		}

		static async Task Test() {
			string enpoint = "localhost:9002";
			// listening
			RunLiStenerAsync(enpoint);
			// create large buffer to send
			byte[] buf = new byte[4096];
			// connecting
			ClientWebSocket cws = new ClientWebSocket();
			await cws.ConnectAsync(new Uri($"ws://{enpoint}/"), CancellationToken.None);
			// sending
			await cws.SendAsync(new ArraySegment<byte>(buf), WebSocketMessageType.Binary, true, CancellationToken.None);
			// wait for data
			await Task.Delay(500);
			// dispose listener
			listener.Stop();
			// wait for stop
			await Task.Delay(500);
			try {
				// closing
				if (cws.State == WebSocketState.Open) {
					await cws.CloseAsync(WebSocketCloseStatus.Empty, null, CancellationToken.None);
					Console.WriteLine("Closed");
				} else {
					Console.WriteLine("Already closed");
				}
			} catch (Exception ex) {
				// pokemon exception handling
				Console.WriteLine($"Close failed {ex.ToString()}");
			}
		}

		static void Main(string[] args) {
			Test().Wait();
		}
	}
}
```

Perhaps this is also linked to #28169

[EDIT] Add C# syntax highlighting by @karelz

**Comment by maincoon** [comment]
Oh! Сherry on the cake! 
HttpListener.Stop() does not stop HttpListener.GetContext() call so it just hangs forever. Source code above also shows this.

**Comment by karelz** [comment]
@maincoon is it a regression against .NET Core 2.0? Or is the behavior on 2.1 Preview2 the same?

**Comment by maincoon** [comment]
2.0 has same HttpListener.Stop() and ClientWebSocket.Close()/State behaviour. After HttpListener.Stop() call:

```
Error System.Net.WebSockets.WebSocketException (0x80004005): An internal WebSocket error occurred. Please see the innerException, if present, for more details.  ---> System.Net.HttpListenerException (0x80004005): Операция ввода/вывода была прервана из-за завершения потока команд или по запросу приложения
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.<ReadAsyncCore>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__44.MoveNext()
   at System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boolean aborted)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WSTest.Program.<Reader>d__3.MoveNext() in C:\Projects\Globo\skillgames\BRANCH\dev\UpDAU\tests\WSTest\Program.cs:line 49
```

After ClientWebSocket.State == Open and ClientWebSocket.Close() call:

```
Close failed System.Net.Http.WinHttpException (0x80072EFF): Соединение с сервером было неожиданно прервано
   at System.Net.WebSockets.WinHttpWebSocket.InternalCloseAsync(WebSocketCloseStatus closeStatus, String statusDescription)
   at System.Net.WebSockets.WinHttpWebSocket.<CloseAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WSTest.Program.<Test>d__4.MoveNext() in C:\Projects\Globo\skillgames\BRANCH\dev\UpDAU\tests\WSTest\Program.cs:line 94
```

**Comment by karelz** [comment]
@scalablecory can you please check it out?

**Comment by alnikola** [comment]
The observed behavior to abruptly terminate processing of ongoing requests is implemented in Stop method **by design**. The current documentation is misleading about this because the statement

> Causes this instance to stop receiving incoming requests

leads to believe that it affects only new request whereas it actually terminates all ongoing ones as well. I will update the documentation to make it clearer.

**Comment by davidsh** [comment]
>I will update the documentation to make it clearer.

Please link the dotnet/dotnet-api-docs PR to this issue. Thanks.

**Comment by alnikola** [comment]
Documentation PR dotnet/dotnet-api-docs#3674
