### ISSUE TITLE
configSource with relative path does not work on Linux

### ISSUE THREAD

**Issue by JJoe2** [dotnet/corefx#29279]
I am using System.Configuration.ConfigurationManager 4.4.1 and have a configuration file which references external files as follows:

```xml
    <appSettings file="Config\appSettings.config>
    </appSettings>
    <connectionStrings configSource="Config\connectionStrings.config" />
```

I've tried running the application on both Windows and in a Linux docker container, and observed the following behavior.

1. On Windows, both external files are read successfully.
2. In a Linux docker container, the external appSettings file is read successfully
3. In a Linux docker container, when I attempt to access `System.Configuration.ConfigurationManager.ConnectionStrings` I get the following exception:

```
System.Configuration.ConfigurationErrorsException
  HResult=0x80131902
  Message=Unable to open configSource file 'Config\connectionStrings.config'. (/app/bin/Debug/netcoreapp2.0/DockerExample.dll.config line 6)
  Source=System.Configuration.ConfigurationManager
  StackTrace:
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
... etc ...
```

I tried replacing the \ separator in the configuration file by a forward slash /, this being the default path separator on Linux.  This time I get the following exception.

```
System.Configuration.ConfigurationErrorsException
  HResult=0x80131902
  Message=Configuration system failed to initialize
  Source=System.Configuration.ConfigurationManager
  StackTrace:
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.get_AppSettings()
```

Inner Exception 1:
```
ConfigurationErrorsException: The configSource attribute must be a relative physical path, so the '/' character is not allowed. (/app/bin/Debug/netcoreapp2.0/DockerExample.dll.config line 6)
... etc ...
```

This error message is nonsensical, as / or \ should be treated as being interchangeable.  The same error happens with the .NET Framework.

[EDIT] Add formatting by @karelz

**Comment by JJoe2** [comment]
The internal helper class `UrlPath` has code that looks suspicious for non-Windows, e.g. 
- IsDirectorySeparatorChar uses hardwired / and \ rather than Path.DirectorySeparatorChar and Path.AltDirectorySeparatorChar.
- IsAbsoluteLocalPhysicalPath expects a drive letter for an absolute path (second character = ":")
- IsEqualOrSubdirectory uses hardwired \ as directory separator
- IsEqualOrSubpathImpl uses hardwired / as directory separator.

**Comment by JJoe2** [comment]
I suspect a fix for this could be to remove the check in `ClientConfigurationSystem.EnsureInit` that checks if configSource contains a forward slash character (or replace it by a proper check for a relative path).

Then we could use / as a separator in configSource, which should work on both Windows as Linux.
