### ISSUE TITLE
[arm32] corefx System.Net.NameResolution.Pal.Tests fails

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/corefx#29293]
_From @BruceForstall on April 23, 2018 21:46_

https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/jitstress/job/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/3/consoleText

```
Running tests in /ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/tests/System.Net.NameResolution.Pal.Tests/netcoreapp-Linux-Release-arm
./RunTests.sh /ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/testhost/netcoreapp-Linux-Release-arm

----- start 04:53:57 =============== To repro directly: =====================================================
pushd .
#!/usr/bin/env bash
chmod +x /ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/testhost/netcoreapp-Linux-Release-arm/dotnet
/ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/testhost/netcoreapp-Linux-Release-arm/dotnet xunit.console.netcore.exe System.Net.NameResolution.Pal.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
popd
===========================================================================================================
/ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/tests/System.Net.NameResolution.Pal.Tests/netcoreapp-Linux-Release-arm /ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/tests/System.Net.NameResolution.Pal.Tests/netcoreapp-Linux-Release-arm
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Net.NameResolution.Pal.Tests
Discovered:  System.Net.NameResolution.Pal.Tests
Starting:    System.Net.NameResolution.Pal.Tests
   System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetNameInfo_LocalHost_IPv6_TryGetAddrInfo [FAIL]
      Assert.Equal() Failure
      Expected: Success
      Actual:   HostNotFound
      Stack Trace:
         /mnt/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_prtest/_/fx/src/System.Net.NameResolution/tests/PalTests/NameResolutionPalTests.cs(161,0): at System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetNameInfo_LocalHost_IPv6_TryGetAddrInfo()
   System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetNameInfo_LocalHost_IPv6 [FAIL]
      Assert.Equal() Failure
      Expected: Success
      Actual:   HostNotFound
      Stack Trace:
         /mnt/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_prtest/_/fx/src/System.Net.NameResolution/tests/PalTests/NameResolutionPalTests.cs(77,0): at System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetNameInfo_LocalHost_IPv6()
Finished:    System.Net.NameResolution.Pal.Tests

=== TEST EXECUTION SUMMARY ===
   System.Net.NameResolution.Pal.Tests  Total: 10, Errors: 0, Failed: 2, Skipped: 0, Time: 4.381s
/ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/tests/System.Net.NameResolution.Pal.Tests/netcoreapp-Linux-Release-arm
----- end 04:54:07 ----- exit code 1 ----------------------------------------------------------
```

_Copied from original issue: dotnet/coreclr#17740_

**Comment by wfurt** [comment]
This seems to be test bug.
I was able to reproduce it on my system. 
However nslookup did not resolve the ::1 address either. 

adding following line to /etc/hosts fixes the failures.
::1     localhost ip6-localhost ip6-loopback

**Comment by danmosemsft** [comment]
Is it worth logging `/etc/hosts` when it fails?

**Comment by wfurt** [comment]
my current thinking is updating the test. I think test which makes assumption generally not true are pain to run IMHO.

**Comment by karelz** [comment]
Maybe related to #32797?

**Comment by sandreenko** [comment]
The same tests fail on arm64 ([ci example](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_jitstress2_tst/109/)).

**Comment by wfurt** [comment]
The arm64 failure is different @sandreenko and it is tracked by #32797. It may be that underlying issue is same e.g. unreliable environment.

**Comment by sandreenko** [comment]
@wfurt thank you, have not noticed that issue.
