### ISSUE TITLE
Exception.ToString() throws an exception when it encounters a frame that requires opening a regular PDB

### ISSUE THREAD

**Issue by mjsabby** [dotnet/corefx#29375]
I seem to recall this (or something close to this) was reported for .NET 2.0. I did a quick search on the repo, but didn't find a duplicate. 

The callstack below is for code that called `ToString()` on an Exception. It fails on a frame where the method debug information is in a regular PDB.

I'm also interested in just fixing the whole conundrum of not being able to open a regular PDB on CoreCLR (any platform) to give line number information.

```
coreclr!WinMDInternalImportRO::Release
coreclr!ExceptionTracker::ProcessManagedCallFrame
coreclr!ExceptionTracker::ProcessOSExceptionNotification
coreclr!ProcessCLRException
ntdll!RtlpExecuteHandlerForException
ntdll!RtlDispatchException
ntdll!RtlRaiseException
KERNELBASE!RaiseException
coreclr!RaiseTheExceptionInternalOnly
coreclr!IL_Throw
System.Reflection.Metadata!System.Reflection.Throw.OutOfBounds()$##60000A8
System.Reflection.Metadata!System.Reflection.Metadata.Ecma335.MethodDebugInformationTableReader.GetSequencePoints(System.Reflection.Metadata.MethodDebugInformationHandle)$##6000C23
System.Reflection.Metadata!System.Reflection.Metadata.MethodDebugInformation.get_SequencePointsBlob()$##600083E
System.Diagnostics.StackTrace!System.Diagnostics.StackTraceSymbols.GetSourceLineInfo(System.String, IntPtr, Int32, IntPtr, Int32, Int32, Int32, System.String ByRef, Int32 ByRef, Int32 ByRef)$##6000003
System.Private.CoreLib!System.Diagnostics.StackFrameHelper.InitializeSourceInfo(Int32, Boolean, System.Exception)$##60018CA
System.Private.CoreLib!System.Diagnostics.StackTrace.CaptureStackTrace(Int32, Boolean, System.Threading.Thread, System.Exception)$##60018E3
System.Private.CoreLib!System.Diagnostics.StackTrace..ctor(System.Exception, Boolean)$##60018DD
System.Private.CoreLib!System.Environment.GetStackTrace(System.Exception, Boolean)$##6000711
System.Private.CoreLib!System.Exception.GetStackTrace(Boolean)$##6000399
System.Private.CoreLib!System.Exception.ToString(Boolean, Boolean)$##60003A0
System.Private.CoreLib!System.Text.StringBuilder.AppendFormatHelper(System.IFormatProvider, System.String, System.ParamsArray)$##60034BA
System.Private.CoreLib!System.String.FormatHelper(System.IFormatProvider, System.String, System.ParamsArray)$##600032D```

**Comment by danmosemsft** [comment]
Seems like we should at least have a more helpful exception than "Read out of bounds" if we read a regular PDB.

**Comment by mjsabby** [comment]
We should probably not throw an exception at all. All we have to do is check if the PDB file is at least 4 bytes, and that the first 4 bytes are `BSJB`.

I think this is an easy fix for 2.1, would we take it?

I'll open a separate issue for fixing the problem of regular PDBs working cross platform for the basic case of show casing line number information when formatting an Exception.

**Comment by jkotas** [comment]
>  regular PDBs working cross platform 

There have been number of issues opened on that. It is not something we have plans to do https://github.com/dotnet/coreclr/issues/8175#issuecomment-261748193

**Comment by mjsabby** [comment]
Why not? It's just a change in the StackTrace class to read the lines stream? It will improve so much existing built code that runs on CoreCLR cross platform but is missing this information

**Comment by mjsabby** [comment]
I'm asking why not, because we have this code in CCI (https://github.com/Microsoft/cci/tree/master/PDBReaderAndWriter/PdbReader) that I think will just work. Is isn't it just a PR away? Or is there something more fundamental I'm missing.

**Comment by jkotas** [comment]
If we wanted to support it, it needs to work everywhere and not just for Exception stack trace. It is hard to explain otherwise.

**Comment by mjsabby** [comment]
But certain scenarios are much more likely to be useful vs others. It is about compromise.

Being able to get stack traces with line numbers for code that you depend on is pretty useful when an exception occurs in production where the debug information was encoded in a regular pdb.

It is likely you will never need to debug that code which has the regular pdb, but will immensely benefit from that line number information on any platform.

I would categorize this improvement in the strictly better category - no scenario regresses but at least one scenario improves.

**Comment by jkotas** [comment]
Right. It is about compromise. The compromise that we have settled on is to have Windows PDB to portable PDB converter: https://github.com/dotnet/symreader-converter . You can use that if you want to have line numbers on Unix, but you have Windows PDB for your binary for some reason.

**Comment by mjsabby** [comment]
And I'm saying that the compromise can be strictly better for this scenario which is much more common than debugging a PDB.

**Comment by jkotas** [comment]
> I couldn't find any place in the runtime (i.e. not the DAC) that reads PDBs

Visual Studio/Code debugger and other diagnostic tooling is not open source...

I disagree that it is strictly better. It is strictly more confusing to explain what will work vs. what will not work with it.

We want the cross-plat diagnostic tools (debuggers, profilers) to worry about portable PDB only.

Also, Windows PDBs are many times larger than portable PDBs. Your binary footprint will be much smaller if you deploy portable PDBs with your app to get line numbers.

**Comment by mjsabby** [comment]
I'm confused about your reticence because we have many places in the CoreFX/CoreCLR where compromises are made to benefit the user not make it harder for them.

Your counter proposal requires every person who discovers this to generate portable pdbs from their windows pdbs, and either make it a build process or repackage it themselves. Maybe this component is used in multiple places so now the technical debt is acquired by the consumer multiple places rather than the publisher.

And in this issue I'm proposing that the experience be the same on .NET Core cross plat which can be easily achieved with a library change, it's not even part of the runtime.

Maybe I'm isolated in my thinking that this is a good thing that we're able to reduce the pain for developers who are still stuck in the dual world of .NET/.NET Core.

What do others in the team and community think?

**Comment by jkotas** [comment]
> Your counter proposal requires every person who discovers this to generate portable pdbs from their windows pdbs

If you use the regular .NET Core tooling, you should never run into this. .NET Core tooling will always generate the portable .PDBs for .NET Core apps. If there are corner cases where it is not the case, it is something to fix in the .NET Core tooling.

You will only run into this when you manually stitch together things using something completely custom. Very few people do that and there many thing they have to discover to figure this out. I do not feel bad about converting Windows pdbs to portable pdbs as one thing in the list.

**Comment by danmosemsft** [comment]
@jkotas would this not potentially occur when consuming libraries? Many were built using desktop tooling, or if you build locally, expect to be built by desktop tooling. We generally expect them to work on .NET Core.

@vancem since he is usually interested in PDB discussions.

**Comment by danmosemsft** [comment]
@jkotas I was thinking more of the case where a Core app is consuming libraries built for NETFX, and wish to debug: generally that would mean cloning their repo, and building binary/PDB for yourself, which would generally make Windows PDB unless you re-work their build process. Perhaps that's not a concern?

**Comment by vancem** [comment]
The original complaint was avoiding an error (exception) when doing ToString() on an exception (which walks its stack.    I am assuming there is no pushback on at least no failing.    There is an interesting question on exactly what it does do to give the user a hint that their PDB is 'wrong'.   Just giving up on line numbers is not as good as giving a parenthetical diagnostic that the PDB is not a portable PDB).

Of course @mjsabby  wants it to 'just work'.    I think we should at least understand the cost-benefit of that.    Presumably the idea would be to make it work on Windows only.   Note that this is what we do with perfCounters and I am sure other things that are hard to port to Linux.    I think the ability to 'just work' on windows with Microsoft PDBs is useful (I think @danmosemsft  scenario of using windows libraries without recompiling seems interesting, and we should understand how common it is likely to be).  

My main concern is that line numbers in the exception trace really does 'drag' in a bunch of PDB reading stuff that otherwise the runtime is agnostic to.     Ideally the runtime only has the hook, and it is up to other things (like an SDK installer), to wire into the hook (that is install the necessary DLLs).  

So, I think it is reasonably to fix the error, and we should gather some data on who is likely to benefit from this (can we describe the scenario where people naturally generated Windows PDBs but want to run on .NET Core?).   It seems like our desire to 'converge' .NET Core and desktop scenarios suggests that this will be important, but I don't really have a feel for what we are expecting people to do at build time (if we force them to use new tools (which is sad), then I suppose forcing them to use portable PDBs it not much worse.

But my main suggestion is to fix the uncontroversial part first.

**Comment by svick** [comment]
I am confused by this issue. Do I understand it correctly that:

1. If I run a .Net Core application with non-portable PDB on Unix, `Exception.ToString()` internally throws an exception, which is then caught [here](https://github.com/dotnet/coreclr/blob/76ba8d518eb5830988878fca01e4a6096c1b0b2a/src/mscorlib/src/System/Diagnostics/Stacktrace.cs#L145-L147). As a consequence, the result of `Exception.ToString()` doesn't have line numbers.
2. If I run a .Net Core application with non-portable PDB on Windows, line numbers are included in `Exception.ToString()`.

To me, this sounds like a reasonable state to be in, especially if adding support for reading non-portable PDBs on Unix would take a lot of effort.

Adding some indication to the output that an exception was thrown seems reasonable to me, assuming it wasn't too noisy.

---

What I did to see that my understanding is right:

1. Start on Windows.
2. `dotnet new console`
3. Specify `<DebugType>Full</DebugType>` in csproj to force non-portable PDB and add the following code to Program.cs:

    ```c#
    try { throw new Exception(); } catch (Exception ex) { Console.WriteLine(ex); }
    ```

4. `dotnet publish`
5. Verify that the PDB does *not* start with `BSJB` (it starts with `Microsoft C/C++ MSF 7.00`).
5. `dotnet .\bin\Debug\netcoreapp2.0\publish\hwapp.dll` prints the line number:

    ```
    PS C:\code\tmp\hwapp> dotnet .\bin\Debug\netcoreapp2.0\publish\hwapp.dll
    System.Exception: Exception of type 'System.Exception' was thrown.
       at hwapp.Program.Main(String[] args) in C:\code\tmp\hwapp\Program.cs:line 9
    ```
6. Switch to Linux (in my case, WSL Ubuntu), copy the `publish` directory over or use some shared file system.
7. `dotnet bin/Debug/netcoreapp2.0/publish/hwapp.dll` doesn't print the line number:

    ```
    svick@Svick:/mnt/c/code/tmp/hwapp$ dotnet bin/Debug/netcoreapp2.0/publish/hwapp.dll
    System.Exception: Exception of type 'System.Exception' was thrown.
       at hwapp.Program.Main(String[] args)
    ```

**Comment by tmat** [comment]
This issue belongs to System.Diagnostics.StackTrace not to SRM.
