### ISSUE TITLE
System.Diagnostics.PerformanceCounter.Tests failure

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/corefx#29377]
_From @BruceForstall on April 26, 2018 23:8_

arm32/Windows corefx test System.Diagnostics.PerformanceCounter.Tests fails:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_corefx_baseline_tst/14/consoleText

```
Running: C:\Users\robox\j\workspace\arm_cross_che---eb7b805d\_\fx\bin\tests\System.Diagnostics.PerformanceCounter.Tests\netcoreapp-Windows_NT-Release-arm\RunTests.cmd C:\Users\robox\j\workspace\arm_cross_che---eb7b805d\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm
Using C:\Users\robox\j\workspace\arm_cross_che---eb7b805d\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm as the test runtime folder.
Executing in C:\Users\robox\j\workspace\arm_cross_che---eb7b805d\_\fx\bin\tests\System.Diagnostics.PerformanceCounter.Tests\netcoreapp-Windows_NT-Release-arm\ 
----- start  4:55:44.36 ===============  To repro directly: ===================================================== 
pushd C:\Users\robox\j\workspace\arm_cross_che---eb7b805d\_\fx\bin\tests\System.Diagnostics.PerformanceCounter.Tests\netcoreapp-Windows_NT-Release-arm\
call C:\Users\robox\j\workspace\arm_cross_che---eb7b805d\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm\dotnet.exe xunit.console.netcore.exe System.Diagnostics.PerformanceCounter.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
popd
===========================================================================================================

C:\Users\robox\j\workspace\arm_cross_che---eb7b805d\_\fx\bin\tests\System.Diagnostics.PerformanceCounter.Tests\netcoreapp-Windows_NT-Release-arm>call C:\Users\robox\j\workspace\arm_cross_che---eb7b805d\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm\dotnet.exe xunit.console.netcore.exe System.Diagnostics.PerformanceCounter.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Diagnostics.PerformanceCounter.Tests
Discovered:  System.Diagnostics.PerformanceCounter.Tests
Starting:    System.Diagnostics.PerformanceCounter.Tests
   System.Diagnostics.Tests.CounterSampleCalculatorTests.CounterSampleCalculator_ElapsedTime [FAIL]
      Assert.NotEqual() Failure
      Expected: Not 0
      Actual:   0
      Stack Trace:
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\Helpers.cs(74,0): at System.Diagnostics.Tests.Helpers.RetryOnAllPlatforms[T](Func`1 func)
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\CounterSampleCalculatorTests.cs(24,0): at System.Diagnostics.Tests.CounterSampleCalculatorTests.CounterSampleCalculator_ElapsedTime()
   System.Diagnostics.Tests.CounterSampleTests.CounterSample_Calculate_CalculateCounterSampleCounterSample [FAIL]
      System.ComponentModel.Win32Exception : The specified module could not be found
      Stack Trace:
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\CounterSampleCalculator.cs(242,0): at System.Diagnostics.CounterSampleCalculator.LoadPerfCounterDll()
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\CounterSampleCalculator.cs(93,0): at System.Diagnostics.CounterSampleCalculator.ComputeCounterValue(CounterSample oldSample, CounterSample newSample)
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\CounterSampleTests.cs(58,0): at System.Diagnostics.Tests.CounterSampleTests.CounterSample_Calculate_CalculateCounterSampleCounterSample()
   System.Diagnostics.Tests.CounterSampleTests.CounterSample_Calculate_CalculateCounterSample [FAIL]
      System.ComponentModel.Win32Exception : The specified module could not be found
      Stack Trace:
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\CounterSampleCalculator.cs(242,0): at System.Diagnostics.CounterSampleCalculator.LoadPerfCounterDll()
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\CounterSampleCalculator.cs(93,0): at System.Diagnostics.CounterSampleCalculator.ComputeCounterValue(CounterSample oldSample, CounterSample newSample)
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\CounterSampleCalculator.cs(56,0): at System.Diagnostics.CounterSampleCalculator.ComputeCounterValue(CounterSample newSample)
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\CounterSampleTests.cs(49,0): at System.Diagnostics.Tests.CounterSampleTests.CounterSample_Calculate_CalculateCounterSample()
   System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_CategoryType_MultiInstance [FAIL]
      Assert.NotEqual() Failure
      Expected: Not 0
      Actual:   0
      Stack Trace:
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\Helpers.cs(74,0): at System.Diagnostics.Tests.Helpers.RetryOnAllPlatforms[T](Func`1 func)
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterCategoryTests.cs(91,0): at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_CategoryType_MultiInstance()
   System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCounters [FAIL]
      System.InvalidOperationException : Category does not exist.
      Stack Trace:
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterLib.cs(820,0): at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String machine, String category)
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterCategory.cs(443,0): at System.Diagnostics.PerformanceCounterCategory.GetCounterInstances(String categoryName, String machineName)
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterCategory.cs(517,0): at System.Diagnostics.PerformanceCounterCategory.GetInstanceNames()
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounterCategory.cs(460,0): at System.Diagnostics.PerformanceCounterCategory.GetCounters()
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterCategoryTests.cs(234,0): at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCounters()
   System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_CategoryType_SingleInstance [FAIL]
      Assert.NotEqual() Failure
      Expected: Not 0
      Actual:   0
      Stack Trace:
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\Helpers.cs(74,0): at System.Diagnostics.Tests.Helpers.RetryOnAllPlatforms[T](Func`1 func)
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterCategoryTests.cs(104,0): at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_CategoryType_SingleInstance()
   System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_Decrement_DecrementReadOnly [FAIL]
      Assert.NotEqual() Failure
      Expected: Not 0
      Actual:   0
      Stack Trace:
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\Helpers.cs(74,0): at System.Diagnostics.Tests.Helpers.RetryOnAllPlatforms[T](Func`1 func)
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs(296,0): at System.Diagnostics.Tests.PerformanceCounterTests.CreateCounterWithCategory(String name, Boolean readOnly, PerformanceCounterCategoryType categoryType)
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs(251,0): at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_Decrement_DecrementReadOnly()
   System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_NextValue_ProcessorCounter [FAIL]
      System.ComponentModel.Win32Exception : The specified module could not be found
      Stack Trace:
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\CounterSampleCalculator.cs(242,0): at System.Diagnostics.CounterSampleCalculator.LoadPerfCounterDll()
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\CounterSampleCalculator.cs(93,0): at System.Diagnostics.CounterSampleCalculator.ComputeCounterValue(CounterSample oldSample, CounterSample newSample)
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\src\System\Diagnostics\PerformanceCounter.cs(575,0): at System.Diagnostics.PerformanceCounter.NextValue()
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs(156,0): at System.Diagnostics.Tests.PerformanceCounterTests.<>c__DisplayClass10_0.<PerformanceCounter_NextValue_ProcessorCounter>b__1()
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\Helpers.cs(59,0): at System.Diagnostics.Tests.Helpers.RetryOnAllPlatforms[T](Func`1 func)
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs(156,0): at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_NextValue_ProcessorCounter()
   System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_Increment [FAIL]
      Assert.NotEqual() Failure
      Expected: Not 0
      Actual:   0
      Stack Trace:
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\Helpers.cs(74,0): at System.Diagnostics.Tests.Helpers.RetryOnAllPlatforms[T](Func`1 func)
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs(206,0): at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_Increment()
   System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_Increment_IncrementReadOnly [FAIL]
      Assert.NotEqual() Failure
      Expected: Not 0
      Actual:   0
      Stack Trace:
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\Helpers.cs(74,0): at System.Diagnostics.Tests.Helpers.RetryOnAllPlatforms[T](Func`1 func)
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs(296,0): at System.Diagnostics.Tests.PerformanceCounterTests.CreateCounterWithCategory(String name, Boolean readOnly, PerformanceCounterCategoryType categoryType)
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs(240,0): at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_Increment_IncrementReadOnly()
   System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_CreateCounter_SetReadOnly [FAIL]
      Assert.NotEqual() Failure
      Expected: Not 0
      Actual:   0
      Stack Trace:
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\Helpers.cs(74,0): at System.Diagnostics.Tests.Helpers.RetryOnAllPlatforms[T](Func`1 func)
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs(78,0): at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_CreateCounter_SetReadOnly()
   System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_CreateCounter_MultiInstanceReadOnly [FAIL]
      Assert.NotEqual() Failure
      Expected: Not 0
      Actual:   0
      Stack Trace:
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\Helpers.cs(74,0): at System.Diagnostics.Tests.Helpers.RetryOnAllPlatforms[T](Func`1 func)
         D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs(60,0): at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_CreateCounter_MultiInstanceReadOnly()
Finished:    System.Diagnostics.PerformanceCounter.Tests

=== TEST EXECUTION SUMMARY ===
   System.Diagnostics.PerformanceCounter.Tests  Total: 81, Errors: 0, Failed: 12, Skipped: 0, Time: 35.242s
----- end  4:56:24.56 ----- exit code 1 ----------------------------------------------------------
COREFX TEST FAILED
```

_Copied from original issue: dotnet/coreclr#17799_

**Comment by ViktorHofer** [comment]
Just happend on Windows81: https://dev.azure.com/dnceng/public/_build/results?buildId=184475&view=ms.vss-test-web.build-test-results-tab&runId=4445294&resultId=360055&paneView=debug

```
Assert.True() Failure\r\nExpected: True\r\nActual: False

   at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_NextValue_ProcessorCounter() in D:\a\1\s\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs:line 156
```

**Comment by ericstj** [comment]
You both beat me to this.  I marked it flaky.  The problem is the test is retrying, but it missed a sleep in the retry.  As a result the retries aren't likely to get a better answer.  Lambda under the retry should be changed to include the sleep:
https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterTests.cs#L154-L156

Haven't looked at the others, but they may need similar attention.

**Comment by ViktorHofer** [comment]
>  I marked it flaky

No, no, no! We don't use the flaky feature. If we have a flaky test we disable it by putting an ActiveIssue on it or by trying to fix it. Using the flaky flag doesn't help locally and on different CI providers. Will undo that and send a PR to fix the test.

**Comment by ericstj** [comment]
I see, I thought we were OK to use flaky if we had a Github issue on it.  That's my misunderstanding.

**Comment by ViktorHofer** [comment]
No prob :)

**Comment by ViktorHofer** [comment]
> Lambda under the retry should be changed to include the sleep:

Helpers.RetryOnAllPlatforms does a retry but it seems not a sufficient one. I will replace this with the @stephentoub's retry helper which by default increases the sleep per iteration.

**Comment by JeremyKuhne** [comment]
This is still failing [quite a bit](https://dev.azure.com/dnceng/public/_build/results?buildId=192857&view=ms.vss-test-web.build-test-results-tab&runId=4656146&resultId=378962&paneView=history).

```
Assert.True() Failure\r\nExpected: True\r\nActual: False

   at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_NextValue_ProcessorCounter() in D:\a\1\s\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs:line 156
```

**Comment by JeremyKuhne** [comment]
Another hit:

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38124~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190531.63/workItem/System.Diagnostics.PerformanceCounter.Tests/analysis/xunit/System.Diagnostics.Tests.PerformanceCounterTests~2FPerformanceCounter_NextValue_ProcessorCounter
