### ISSUE TITLE
Got "Specified parameter name 'Parameter1' is not valid." when doing batch update with SqlDataAdapter

### ISSUE THREAD

**Issue by xiaoyumu** [dotnet/corefx#29391]
Hi guys,

I have recently using the ```System.Data.SqlClient``` of version ```4.5.0-preview2-26406-04``` to test if the batch update is supported in the latest build (Accoding to (https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdataadapter.updatebatchsize?view=netcore-2.1#System_Data_Common_DbDataAdapter_UpdateBatchSize)) But if I set the ```UpdateBatchSize``` property of the ```SqlDataAdapter``` to a value lager than 1, like 2 or 10, an exception will throw with following message and stack trace.

Exception: ```Specified parameter name 'Parameter1' is not valid.```
StackTrace:
```
   at System.Data.Common.DbDataAdapter.UpdatedRowStatusErrors(RowUpdatedEventArgs rowUpdatedEvent, BatchCommandInfo[] batchCommands, Int32 commandCount)
   at System.Data.Common.DbDataAdapter.UpdatedRowStatus(RowUpdatedEventArgs rowUpdatedEvent, BatchCommandInfo[] batchCommands, Int32 commandCount)
   at System.Data.Common.DbDataAdapter.Update(DataRow[] dataRows, DataTableMapping tableMapping)
   at System.Data.Common.DbDataAdapter.UpdateFromDataTable(DataTable dataTable, DataTableMapping tableMapping)
   at System.Data.Common.DbDataAdapter.Update(DataTable dataTable)
```

The program is running at a Win10Pro box with Visual Studio 2017 Community Edition.

Microsoft Visual Studio Community 2017 
Version 15.5.6
VisualStudio.15.Release/15.5.6+27130.2027
SDK: Microsoft.NETCore.App  Version: 2.1.0-preview2-26406-04

Project Target Framework
```xml
<PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
</PropertyGroup>
```

Here is the code fragment that generates this exception, it basically trying to insert multiple entities into a table which I want to do it in batch.
```csharp
private void ExecuteNonQueries(string connectionString, string sql, List<EventInfo> entities)
{ 
    using (var connection = new SqlConnection(connectionString))
    {
        var adapter = new SqlDataAdapter();
        var cmd = new SqlCommand(sql, connection);
        cmd.Parameters.Add(new SqlParameter("@Level", SqlDbType.NVarChar, 50, "Level"));
        cmd.Parameters.Add(new SqlParameter("@Message", SqlDbType.NVarChar, 500, "Message"));
        cmd.Parameters.Add(new SqlParameter("@EventTime", SqlDbType.DateTime, 0, "EventTime"));
        cmd.UpdatedRowSource = UpdateRowSource.None;

        adapter.InsertCommand = cmd;
        // If I 
        adapter.UpdateBatchSize = 2; 

        adapter.Update(ConvertToTable(entities));
    }
}

private DataTable ConvertToTable<TEntity>(List<TEntity> entities)
{
    var table = new DataTable(typeof(TEntity).Name);
    foreach (var p in PropertyCache.GetPropertyInfoList(typeof(TEntity)))
    {
        table.Columns.Add(p.Name, p.PropertyType);
    }

    foreach (var entity in entities)
    {
        var row = table.NewRow();
        foreach (var p in PropertyCache.GetPropertyInfoList(typeof(TEntity)))
        {
            row[p.Name] = p.GetValue(entity);
        }
        table.Rows.Add(row);
    }

    return table;
}
```

**Comment by karelz** [comment]
@xiaoyumu did it work ok on .NET Core 2.0? Can you please post minimal repro code? (to avoid confusion)
Also, I assume it fails always for you, it is not an intermittent failure. Is that correct?

**Comment by danmosemsft** [comment]
@keeratsingh, @afsanehr, @david-engel could you please evaluate whether this is needed for 2.1?

**Comment by David-Engel** [comment]
Batch update was not promised for 2.1. The feature/customer request which brought this code over was satisfied and the customer who requested it is happy with the functionality (they are not using batch update) so this issue does not need to delay 2.1.

**Comment by wengxk** [comment]
Today i got the same problem. It does not seem to be resolve.

**Comment by David-Engel** [comment]
@wengxk The fix only went into the master branch and was not ported to 2.x. The next scheduled release out of master is 3.0 which appears to be scheduled for Q1 2019: https://github.com/dotnet/core/blob/master/roadmap.md#upcoming-ship-dates

**Comment by sdrapkin** [comment]
Thx for fixing this one. The "[4.7.0-preview](https://www.nuget.org/packages/System.Data.SqlClient/)" on Nuget includes these fixes.

[TinyORM](https://github.com/sdrapkin/SecurityDriven.TinyORM) will be coming to NetStandard2.0 with full batching support now.

**Comment by dbarwikowski** [comment]
It's not working in .net framework 4.6.1
