### ISSUE TITLE
CngKey.Export The requested operation is not supported [Windows]

### ISSUE THREAD

**Issue by kitsor** [dotnet/corefx#29404]
Can't get RSAParameters on Windows.

Code to reproduce:
```C#
using System;
using System.Linq;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;

namespace TestRSA
{
  class Program
  {
    static void Main(string[] args)
    {
      try
      {
        X509Certificate2 cert = new X509Certificate2("certificate.pfx", "password");
        RSAParameters rsaKey = cert.GetRSAPrivateKey().ExportParameters(true);
        Console.WriteLine(string.Join("", rsaKey.P.Select(x => string.Format("{0:x2}", x))));
      }
      catch (Exception ex)
      {
        Console.WriteLine(ex.Message);
        Console.WriteLine(ex.StackTrace);
      }
    }
  }
}

```

on Windows 10/8.1 returns:

```
> dotnet TestRSA.dll
The requested operation is not supported
   at System.Security.Cryptography.CngKey.Export(CngKeyBlobFormat format)
   at System.Security.Cryptography.RSACng.ExportKeyBlob(Boolean includePrivateParameters)
   at System.Security.Cryptography.RSACng.ExportParameters(Boolean includePrivateParameters)
   at TestRSA.Program.Main(String[] args) in D:\VS\TestRSA\TestRSA\Program.cs:line 15
```
on Ubuntu 16.04
```
$ dotnet TestRSA.dll
da32f2af4800f9f945bd0c8185e9a78b0e0.....
```

Additional info:
```
> dotnet --info
.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.105\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```
```
$ dotnet --info

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by bartonjs** [comment]
When you opened the cert from a PFX you didn't specify X509KeyStorageFlags.Exportable.  On Linux keys are always exportable, but on Windows and macOS they aren't always.

**Comment by kitsor** [comment]
Thanks!
Now it works!
```C#
X509Certificate2 cert = new X509Certificate2("certificate.pfx", "password", X509KeyStorageFlags.Exportable);
```
I searched everywhere, but didn't find where the issue is. Error message isn't informative and I decided that isn't implemented on windows.
