### ISSUE TITLE
Classes inheriting TcpClient or Sockets don't function using correct IP by default.

### ISSUE THREAD

**Issue by FlyingWraptor** [dotnet/corefx#29414]
Duplicate from the .net core base-project issue # 1469.

# Sockets not listening right Internet Protocol in Net classes

Currently the (tested) sockets wrappers won't use IPv6 alongside IPv4 in dual-stack.
Meaning out of the box connections on SmtpClient, TcpClient and MySql connector require modifications at the Socket for functioning on IPv6. 

In .NET Framework this isn't the issue at all because it determines the right protocol by the given input string already.
Source:
https://blogs.msdn.microsoft.com/webdev/2013/01/08/dual-mode-sockets-never-create-an-ipv4-socket-again/

This SHOULD be in .NET core aswell as this might prevent starting or even experienced developers from using IPv6 over all as IPv4 'Just works'.

# Environment

Version: .NET-Core v2.1.105
Project: WebAPI
Platform: Windows 10 Pro x86-x64
      Build: 16299.371

# Testing
## SmtpClient
Code:
```c#
SmtpClient smtpClient= new SmtpClient();
smtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;

smtpClient.Port = 587;
smtpClient.Host = "fd00::8:23";
smtpClient.EnableSsl = true;

smtpClient.UseDefaultCredentials = false;
smtpClient.Credentials = new NetworkCredential("username", "password");

MailMessage mmMail = new MailMessage("valid_sender", "valid_receiver");
mmMail.Subject = "Subject";
mmMail.Body = "Message";

smtpClient.SendMailAsync(Mail);
```
Resulting in:
```
System.Net.Mail.SmtpException: Failure sending mail. ---> System.ArgumentException: None of the discovered or specified addresses match the socket address family.
Parameter name: context
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.DoDnsCallback(IAsyncResult result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.DnsCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
   at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
```
Doing this synchronically using:
```c#
smtpClient.Send(Mail);
```
Results:
```
System.Net.Sockets.SocketException (0x80004005): A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
   at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port)
   at System.Net.Mail.SmtpConnection.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpTransport.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
```

## MySQL
Using a simple custom (working wrapper) with the following querystring
```c#
this.connectionString = "Server=fd00::8:21;Port=3306;Uid=Username;Pwd=password;Allow User Variables=True;Connection Timeout=1;";
```
I get the following error:
```
System.NotSupportedException: This protocol version is not supported.
   at System.Net.Sockets.Socket.BeginConnect(IPAddress address, Int32 port, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.Socket.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.TcpClient.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_0(String targetHost, Int32 targetPort, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Sockets.TcpClient.ConnectAsync(String host, Int32 port)
   at MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.NativeDriver.Open()
```

## Plain TcpClient
Leading me to do some testing using a TcpClient:
```c#
TcpClient tcpClient = new TcpClient();
IPAddress ipaAddress = IPAddress.Parse("fd00::8:23");
tcpClient.Connect(ipaAddress, 587);
```
Result:
```
System.Net.Internals.SocketExceptionFactory.ExtendedSocketException
  HResult=0x80004005
  Message=An address incompatible with the requested protocol was used [fd00::8:23]:587
  Source=System.Net.Sockets
  StackTrace:
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
```

If I set the AddressFamily however the code works:
```c#
TcpClient tcpClient = new TcpClient(AddressFamily.InterNetworkV6);
tcpClient.Client.DualMode = true;
```

[EDIT] Fix .NET Standard -> .NET Framework by @karelz

**Comment by rmkerr** [comment]
Thanks for the report and the thorough set of repros. Do you know what the behavior is on on the latest version of .NET Framework (4.7.2)?

**Comment by davidsh** [comment]
cc: @Tratcher

**Comment by davidsh** [comment]
@FlyingWraptor All of the examples you posted are for client-side connections (TcpClient, SmtpClient, etc.). But the bug title is about "listening sockets".

The concept of dual-mode is for listening sockets only. Do you have any repro that shows how you created a listener using sockets that isn't listening on both IPv4 and IPv6 ports?

**Comment by Tratcher** [comment]
Dual mode is not just for listening, it can also be used for outbound connections.

**Comment by davidsh** [comment]
>Dual mode is not just for listening, it can also be used for outbound connections.

Yes.  But dual-mode for listening is when you specify a port (say "80" for a webserver) and then you can listen on both IPv4 and IPv6 addresses bound to a network adapter.

Dual-mode for client-side is when you specify a DNS name (say "www.microsoft.com") and a port (i.e. 80). Then the client will try to connect to EITHER IPv6 or IPv4 addresses based on what DNS returns for A/AAAA records.

But this issue talks about a client trying to connect to an IPv6 literal.  So, how can they be "dual-mode"? I.e. from above example:

```c#
TcpClient tcpClient = new TcpClient();
IPAddress ipaAddress = IPAddress.Parse("fd00::8:23");
tcpClient.Connect(ipaAddress, 587);
```

Dual-mode connections only work when specifying a DNS name.  And then there is only one connection made, either IPv4 or IPv6.

**Comment by FlyingWraptor** [comment]
The title is misleading and should be replaced to Sockets not determining correct Internet Protocol by default.

As written in the source: "With .NET 4.5 the entire Socket API has been updated so that Dual Mode is easy to configure, use, and it just works!".
Meaning out of the box a dual-sockets work.
I've tested this with the following result in .NET Standard 4.7.2:
```
Listener started
Socket IPv4 connected
Socket IPv6 connected
TcpClient IPv4 connected
TcpClient IPv6 failed
TcpClient DualSocket IPv4 connected
TcpClient DualSocket IPv6 connected
```
Code:
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using System.Net;
using System.Net.Sockets;

namespace Testing
{
	class Program
	{
		static void Main(string[] args)
		{
			// Server
			TcpListener listener = TcpListener.Create(3218);
			listener.Start();
			Console.WriteLine("Listener started");

			// Client
			Socket socket = new Socket(SocketType.Stream, ProtocolType.Tcp);

			Console.Write("Socket IPv4 ");
			try
			{
				socket.Connect(IPAddress.Loopback, 3218);
				Console.WriteLine("connected");
			}
			catch
			{
				Console.WriteLine("failed");
			}
			socket.Dispose();
			socket = new Socket(SocketType.Stream, ProtocolType.Tcp);

			Console.Write("Socket IPv6 ");
			try
			{
				socket.Connect(IPAddress.IPv6Loopback, 3218);
				Console.WriteLine("connected");
			}
			catch
			{
				Console.WriteLine("failed");
			}
			socket.Dispose();



			TcpClient client = new TcpClient();

			Console.Write("TcpClient IPv4 ");
			try
			{
				client.Connect(IPAddress.Loopback, 3218);
				Console.WriteLine("connected");
			}
			catch
			{
				Console.WriteLine("failed");
			}
			client.Dispose();
			client = new TcpClient();

			Console.Write("TcpClient IPv6 ");
			try
			{
				client.Connect(IPAddress.IPv6Loopback, 3218);
				Console.WriteLine("connected");
			}
			catch
			{
				Console.WriteLine("failed");
			}
			client.Dispose();



			TcpClient dClient = new TcpClient(AddressFamily.InterNetworkV6);
			dClient.Client.DualMode = true;

			Console.Write("TcpClient DualSocket IPv4 ");
			try
			{
				dClient.Connect(IPAddress.Loopback, 3218);
				Console.WriteLine("connected");
			}
			catch
			{
				Console.WriteLine("failed");
			}
			dClient.Dispose();
			dClient = new TcpClient(AddressFamily.InterNetworkV6);
			dClient.Client.DualMode = true;

			Console.Write("TcpClient DualSocket IPv6 ");
			try
			{
				dClient.Connect(IPAddress.IPv6Loopback, 3218);
				Console.WriteLine("connected");
			}
			catch
			{
				Console.WriteLine("failed");
			}
			dClient.Dispose();

			Console.ReadLine();
		}
	}
}
```
This already was an issue in .NET Standard for default sockets and TcpClients.
Though classes inheriting the TcpClient or a Socket (Like: SmtpClient) do this automatically in C# .NET Standard, tested in 4.5, 4.6.1 and 4.7.2.

```c#
using System;

using System.Net;
using System.Net.Mail;

namespace Testing
{
	class Program
	{
		static void Main(string[] args)
		{
			try
			{

				SmtpClient smtpClient = new SmtpClient();
				smtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;
				smtpClient.EnableSsl = true;
				smtpClient.Host = "<mailserver ipv6>";
				smtpClient.Port = 587;
				smtpClient.UseDefaultCredentials = false;
				smtpClient.Credentials = new NetworkCredential("<username>", "<password>");

				MailMessage mMessage = new MailMessage("<sender>", "<receiver>");
				mMessage.Subject = "Test";
				mMessage.Body = "Testmessage";

				smtpClient.SendMailAsync(mMessage);

				Console.WriteLine("Mail send");
			}
			catch
			{
				Console.WriteLine("Mail failed");
			}

			Console.ReadLine();
		}
	}
}
```
 
This succeeds, running the same SmtpClient in .NET Core 2 will result in the errors provided above.

**Comment by Tratcher** [comment]
@karelz failing with IPv6 addresses is definitely a bug...

**Comment by FlyingWraptor** [comment]
It just means it doesn't correctly set the required Internet Protocol for the classes that inherit the TcpClient and the Socket class, which .NET Standard does since 4.5.

**Comment by karelz** [comment]
FYI: Fixed references .NET Standard -> .NET Framework (it was a bit confusing)

Marked as compat bug

**Comment by FlyingWraptor** [comment]
My apologies for any use of the wrong terms/names which may have caused some misunderstandings.

**Comment by karelz** [comment]
No worries, now we are all on the same page and that's what matters :)

**Comment by watfordgnf** [comment]
@karelz Was this ever considered for porting to 2.1 or 2.2? [The workaround code we're considering in the C# client for NATS isn't pretty](https://github.com/nats-io/nats.net/issues/272).
