### ISSUE TITLE
CmsSigner.ComputeSignature() throws CryptographicException

### ISSUE THREAD

**Issue by AlexMAS** [dotnet/corefx#29461]
Hello!

I try to use `CmsSigner` from `System.Security.Cryptography.Pkcs` with an X.509 certificate which uses GOST algorithms (Russian Cryptographic Standards). And when I call `ComputeSignature()` it throws `CryptographicException` like below.

```
System.Security.Cryptography.CryptographicException : '1.2.643.2.2.9' is not a known hash algorithm.
   at Internal.Cryptography.Helpers.GetDigestAlgorithm(String oidValue)
   at System.Security.Cryptography.Pkcs.CmsSigner.Sign(ReadOnlyMemory`1 data, String contentTypeOid, Boolean silent, X509Certificate2Collection& chainCerts)
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer, Boolean silent)
```

To eliminate this exception in .NET Framework 4.5 I used [CryptoConfig](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.cryptoconfig?view=netframework-4.5) class to register specific OIDs, algorithms and their implementations. In .NET Core we also have [CryptoConfig](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.cryptoconfig?view=netcore-2.0) class but the above mentioned method does not work. And it is clear because [Internal.Cryptography.Helpers.GetDigestAlgorithm()](https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Helpers.cs#L41) is hardcoded:

```cs
internal static HashAlgorithmName GetDigestAlgorithm(string oidValue)
{
    switch (oidValue)
    {
        case Oids.Md5:
            return HashAlgorithmName.MD5;
        case Oids.Sha1:
            return HashAlgorithmName.SHA1;
        case Oids.Sha256:
            return HashAlgorithmName.SHA256;
        case Oids.Sha384:
            return HashAlgorithmName.SHA384;
        case Oids.Sha512:
            return HashAlgorithmName.SHA512;
        default:
            throw new CryptographicException(SR.Cryptography_UnknownHashAlgorithm, oidValue);
    }
}
```

As I understand there is no way now to register custom algorithms like in .NET Framework.

P.s. I hope we will see more flexible and convenient way to extend Crypto API in .NET Core because currently it is one of the weaknesses.

**Comment by bartonjs** [comment]
In .NET Framework the SignedCms work is done by the OS, so registering additional algorithms with CAPI or CNG enables these scenarios.

We need a very different registration system than what we had in .NET Framework to enable being the primary extension point.  For a simple hash/digest algorithm it's probably always the case that the ASN AlgorithmIdentifier value is either `{ oid, NULL }` or ` { oid, (omitted) }` (and with a comment of how the OPTIONAL got lost during the transcription of the structure from ASN.1-1988 to ASN.1-1997), but isn't necessarily.

For signature algorithms, there's the X.509 signature format (e.g. "sha256WithRsaEncryption" as a combined identifier) and the CMS signature format (e.g. "rsaEncryption" in one field, and "sha256" in another).  DSA, DH, and ECC all use the parameters values, and each of the three has different structure for the parameters.

For encryption algorithms sometimes the oid is `{ algorithm, keysize, block chaining mode }` all in one, sometimes it's just an algorithm and other data is in the parameters.

---

All that meant is "it's not simple".  For X.509 certificate creation we modelled extensibility via the X509SignatureGenerator class.  For CMS we could add a similar concept (for signature algorithms).  Figuring out how to work in a hash algorithm factory is a smidgen trickier, unless we just kick the can by assuming hash algorithms always use "nullish" parameters (and then which "ish" we pick).

So, we need to design the extensibility API.

**Comment by AlexMAS** [comment]
@bartonjs Thank you for your comprehensive reply. 

Yes, I understand what you are talking about and suspected that there are many reasons for it. Currently I try to port on .NET Core my cryptographic library which works with GOST CSPs. Most of the unit tests are green except ones with signatures. :)

Hope you will have progress with the extensibility API in the nearest future. :)

**Comment by vitawin** [comment]
@AlexMAS здравствуйте.
удалось ли вам найти решение вашей проблемы?
столкнулся с аналогичной проблемой. приложение на core, при попытке проверки подпись System.Security.Cryptography.Pkcs.SignedCms(Boolean) возвращает ошибку "''1.2.643.2.2.9' is not a known hash algorithm.'

**Comment by AlexMAS** [comment]
@vitawin No, as mentioned above this part hasn't implemented yet.

**Comment by jaiminsoni2017** [comment]
@bartonjs,
We are facing this issue : **Unknown encryption algorithm System.Security.Cryptography.RSACng**
Code : 

> var signature = new X509Certificate2Signature(cert, "SHA-256");

Is there any update for this open ticket in .net core 2.2 version? or is it still open.

**Comment by bartonjs** [comment]
@jaiminsoni2017 There's no type in .NET called `X509Certificate2Signature`, it must come from some library built on top of us.  You'll have to work with whoever provides it.
