### ISSUE TITLE
BeginConnect_EndPoint_AddressFamily_Throws_NotSupported test fails deterministically on netfx on RS4

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#29481]
```
System.Net.Sockets.Tests.ArgumentValidation.BeginConnect_EndPoint_AddressFamily_Throws_NotSupported [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.NotSupportedException)
        Actual:   typeof(System.InvalidOperationException): BeginConnect cannot be called while another asynchronous operation is in progress on the same Socket.
        Stack Trace:
             at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
             at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1](Func`4 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, Object state, TaskCreationOptions cr
  eationOptions)
             at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, EndPoint remoteEndPoint)
             at System.Net.Sockets.Tests.ArgumentValidation.<>c.<BeginConnect_EndPoint_AddressFamily_Throws_NotSupported>b__106_1()
```

**Comment by davidsh** [comment]
RS4 (Windows 10 April 2018 Update) contains .NET Framework 4.7.2. There was an explicit bug fix for 4.7.2 that made this exception happen when concurrent I/O (a form of misuse) happens with those APIs.

**Comment by stephentoub** [comment]
There's no concurrent use in this test.  Seems like the fix may have been broken.

**Comment by davidsh** [comment]
See internal bug: 188428

cc: @caesar1995

**Comment by stephentoub** [comment]
In any event, I'll fix up the test to not depend on this.
