### ISSUE TITLE
[Test] SendAsync_ExpectedDiagnosticSynchronousExceptionActivityLogging is not testing synchronous exception

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#29482]
The purpose for this test is to verify if synchronous exception activity will be logged for `DiagnosticsHandler` SendAsync/GetAsync.
https://github.com/dotnet/corefx/blob/cebcf436358600a4808656b142a74f57d1e8f6f0/src/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs#L505-L519

However, it's not forcing a synchronous exception for SocketsHttpHandler: https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/SocketsHttpHandler.cs#L339-L343
And for PlatformHandler, because of #29337, HttpClientHandler will intercept the Exception in CookieContainer setter, before passing the value to SendAsync.

We do have synchronous exception in the SendAsync path, and we need to rework this test (by using Reflection, for example).

**Comment by caesar1995** [comment]
The correct way to verify synchronous exception in async operation would be:

`Assert.Throws<NotSupportedException>(() => { client.SendAsync(request); });`

This pattern `Assert.ThrowsAsync<Exception>(() => operation).Wait();` is not correct. It will verify async exception as well.

**Comment by caesar1995** [comment]
Hmm, after lots of testing, I found `Assert.Throws<NotSupportedException>(() => { client.SendAsync(request); });` is not able to capture the synchronous exception in async operation.

We may need to manually use

``` c#
                try
                {
                    client.GetAsync($"http://{Guid.NewGuid()}.com");
                    Assert.False(true, "Exception was expected but none was thrown.");
                }
                catch (Exception e)
                {
                    // Verify Exception type
                }
```

**Comment by caesar1995** [comment]
I also found `Reflection` doesn't work well with async operation: when using Reflection to invoke a async method, which returns a Task object, if we don't explicitly call Task.Wait(), the async method will never be invoked.

So we need to modify above try catch example to make Reflection work:

```c#
                try
                {
                    Task t = (Task)handler.GetType()
                                    .GetTypeInfo()
                                    .GetDeclaredMethod("SendAsync")
                                    .Invoke(handler, new object[] { null, CancellationToken.None } );
                    
                    // The t.Wait() is must have. Otherwise, the above Reflection invoke will be skipped (optimized away?), and the synchronous exception will never be caught. (No exception is thrown at all).
                    t.Wait();
                    Assert.False(true, "Exception was expected but none was thrown.");
                }
                catch (Exception e)
                {
                    // Verify Exception type here.
                }
```

**Comment by stephentoub** [comment]
> Hmm, after lots of testing, I found Assert.Throws<NotSupportedException>(() => { client.SendAsync(request); }); is not able to capture the synchronous exception in async operation.

This does not make sense.  Can you please clarify?

**Comment by stephentoub** [comment]
>  if we don't explicitly call Task.Wait(), the async method will never be invoked.

This is also not true.

What is the method you're invoking that's synchronously propagating an exception?

**Comment by davidsh** [comment]
You don't need to use reflection to hit that unique sync code path.

Just do something like this:

```c#
using System;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace ConsoleApp3
{
    public class MyHandler : HttpClientHandler
    {
        public Task<HttpResponseMessage> SendAsync(HttpRequestMessage request)
        {
            return SendAsync(request, CancellationToken.None);
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                var handler = new MyHandler();
                Task t = handler.SendAsync(null);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            Console.ReadLine();
        }
    }
}
```

This will allow you to call the HttpClientHandler.SendAsync() method directly without the HttpClient or HttpMessageInvoker intercepting the null check for the HttpRequestMessage parameter.  Using a pattern like this will let you test the code path here:

https://github.com/dotnet/corefx/blob/3ecf563f751f1817a6e0f60c9e7ee8d044e28951/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs#L98

which could generate a sync exception (i.e. an exception before the task is even returned).

**Comment by davidsh** [comment]
You can see with this example that the ArgumentNullException is generated directly from the HttpClientHandler code (which is the codepath that you need to hit to make this test actually test the path we want to test.

>System.ArgumentNullException: A request message must be provided. It cannot be null.
Parameter name: request
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at ConsoleApp3.MyHandler.SendAsync(HttpRequestMessage request) in C:\Users\davidsh\Documents\Visual Studio 2017\Projects\ConsoleApp3\ConsoleApp3\Program.cs:line 12
   at ConsoleApp3.Program.Main(String[] args) in C:\Users\davidsh\Documents\Visual Studio 2017\Projects\ConsoleApp3\ConsoleApp3\Program.cs:line 23

**Comment by davidsh** [comment]
The example above was with .NET Framework.  But if you use the code pattern above you will be able to hit the right code paths in CurlHandler, WinHttpHandler, and SocketsHttpHandler.

I.e.

https://github.com/dotnet/corefx/blob/3ecf563f751f1817a6e0f60c9e7ee8d044e28951/src/System.Net.Http/src/System/Net/Http/CurlHandler/CurlHandler.cs#L446
