### ISSUE TITLE
Dns.GetHostAddressesAsync and HttpClient can't run on Linux

### ISSUE THREAD

**Issue by loqix** [dotnet/corefx#2965]
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: The AddressFamily Unspecified is not valid for the System.Net.IPEndPoint end point, use InterNetwork instead.
Parameter name: socketAddress
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp1.Program.<Test>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ConsoleApp1.Program.Main(String[] args)

**Comment by stephentoub** [comment]
cc: @pgavlin, @davidsh, @CIPop

**Comment by ellismg** [comment]
@loqix To speed the investigation up on our end, can you share the source for your repo program?

**Comment by davidsh** [comment]
Are we sure this is actually CoreFx code?  The HttpClient in CoreFx doesn't use managed sockets nor System.Net.Dns class.

**Comment by pgavlin** [comment]
It would also be helpful to know what platform you're on, how your network is configured (e.g. does your system support IPv6, or is it only IPv4).

**Comment by loqix** [comment]
This is because the System.Net.NameResolution package depends on System.Private.Networking, but Linux is not implemented

**Comment by CIPop** [comment]
@loqix We are aware of this issue: none of the packages have been updated to include code that is on GitHub at this moment. 

System.Private.Networking is the current, monolithic implementation for all the following contracts for corefx:
* System.Net.Primitives
* System.Net.NameResolution
* System.Net.Sockets
* System.Net.Utilities
* System.Net.NetworkInformation
* System.Net.Security

Until we split out _all_ the implementations into separate assemblies, we cannot remove System.Private.Networking to avoid blocking app development on Windows. This is true, even if we do already have code available on GitHub.

I'm actively working on fixing this issue and tracking with issues like #2492 and #894.
