### ISSUE TITLE
Test 'Manual_CertificateSentMatchesCertificateReceived_Success' fails with WinHttpHandler

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#29725]
Similar to #9543 but only seems to be happening with WinHttpHandler.  And this failure occurs even after PR #29724 which fixed the PFX parallel import problem (which corrupted private keys).

>System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ClientCertificates_Test.Manual_CertificateSentMatchesCertificateReceived_Success(numberOfRequests: 3, reuseClient: True) [FAIL]

```
        System.AggregateException : One or more errors occurred. (One or more errors occurred. (An error occurred while sending the request.)) (One or more err
  ors occurred. (Authentication failed because the remote party has closed the transport stream.))
        ---- System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)
        -------- System.Net.Http.HttpRequestException : An error occurred while sending the request.
        ------------ System.Net.Http.WinHttpException : Error 12186 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The client certificate credentials were not
   recognized.'.
        ---- System.AggregateException : One or more errors occurred. (Authentication failed because the remote party has closed the transport stream.)
        -------- System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
        Stack Trace:
           s:\GitHub\corefx\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(92,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAn
  yFailed(Task[] tasks)
           s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ClientCertificates.cs(231,0): at System.Net.Http.Functional.Tests.H
  ttpClientHandler_ClientCertificates_Test.<>c.<<Manual_CertificateSentMatchesCertificateReceived_Success>b__15_1>d.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
           s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ClientCertificates.cs(251,0): at System.Net.Http.Functional.Tests.H
  ttpClientHandler_ClientCertificates_Test.<>c__DisplayClass15_0.<<Manual_CertificateSentMatchesCertificateReceived_Success>b__2>d.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
           s:\GitHub\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs(66,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsy
  nc, Options options)
           s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ClientCertificates.cs(241,0): at System.Net.Http.Functional.Tests.H
  ttpClientHandler_ClientCertificates_Test.Manual_CertificateSentMatchesCertificateReceived_Success(Int32 numberOfRequests, Boolean reuseClient)
           --- End of stack trace from previous location where exception was thrown ---
           ----- Inner Stack Trace #1 (System.AggregateException) -----

           ----- Inner Stack Trace -----
           s:\GitHub\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(507,0): at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTa
  sk, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
           s:\GitHub\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(135,0): at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
           s:\GitHub\corefx\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(64,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAn
  yFailed(Task[] tasks)
           ----- Inner Stack Trace -----
           s:\GitHub\corefx\src\System.Runtime.Extensions\src\System\Environment.cs(146,0): at System.Environment.get_StackTrace()
           s:\GitHub\corefx\src\Common\src\System\Runtime\ExceptionServices\ExceptionStackTrace.cs(23,0): at System.Runtime.ExceptionServices.ExceptionStackTra
  ce.AddCurrentStack(Exception exception)
           s:\GitHub\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpException.cs(57,0): at System.Net.Http.WinHttpException.CreateExcepti
  onUsingError(Int32 error, String nameOfCalledFunction)
           s:\GitHub\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs(333,0): at System.Net.Http.WinHttpRequestCallback.
  OnRequestError(WinHttpRequestState state, WINHTTP_ASYNC_RESULT asyncResult)
           s:\GitHub\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs(104,0): at System.Net.Http.WinHttpRequestCallback.
  RequestCallback(IntPtr handle, WinHttpRequestState state, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
           s:\GitHub\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs(47,0): at System.Net.Http.WinHttpRequestCallback.W
  inHttpCallback(IntPtr handle, IntPtr context, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
           --- End of stack trace from AddCurrentStack ---
           s:\GitHub\corefx\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs(62,0): at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
           s:\GitHub\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(852,0): at System.Net.Http.WinHttpHandler.StartRequest(Win
  HttpRequestState state)
           ----- Inner Stack Trace #2 (System.AggregateException) -----

           ----- Inner Stack Trace -----
           s:\GitHub\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs(874,0): at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, I
  nt32 readBytes, AsyncProtocolRequest asyncRequest)
           s:\GitHub\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs(862,0): at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer,
   AsyncProtocolRequest asyncRequest)
           s:\GitHub\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs(656,0): at System.Net.Security.SslState.ForceAuthentication(Boolean rec
  eiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
           s:\GitHub\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs(572,0): at System.Net.Security.SslState.ProcessAuthentication(LazyAsync
  Result lazyResult)
           s:\GitHub\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.cs(265,0): at System.Net.Security.SslStream.BeginAuthenticateAsServer(Ssl
  ServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
           s:\GitHub\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.cs(255,0): at System.Net.Security.SslStream.BeginAuthenticateAsServer(X50
  9Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncC
  allback, Object asyncState)
           s:\GitHub\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.cs(418,0): at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsyn
  c>b__50_1(X509Certificate arg1, Boolean arg2, SslProtocols arg3, AsyncCallback callback, Object state)
           E:\A\_work\104\s\src\System.Private.CoreLib\src\System\Threading\Tasks\FutureFactory.cs(1195,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncIm
  pl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creat
  ionOptions)
           E:\A\_work\104\s\src\System.Private.CoreLib\src\System\Threading\Tasks\TaskFactory.cs(1092,0): at System.Threading.Tasks.TaskFactory.FromAsync[TArg1
  ,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
           s:\GitHub\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.cs(419,0): at System.Net.Security.SslStream.AuthenticateAsServerAsync(X50
  9Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
           s:\GitHub\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs(100,0): at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 fu
  ncAsync)
```

**Comment by davidsh** [comment]
Closing in favor of #29728.
