### ISSUE TITLE
UnixDomainSocket test is timing out

### ISSUE THREAD

**Issue by rmkerr** [dotnet/corefx#29742]
The recently added test ConcurrentSendReceive has failed in official runs with the following error 1-2 times a day for the last three days:
```
System.TimeoutException : WhenAllOrAnyFailed timed out after 10000
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
   at System.Net.Sockets.Tests.UnixDomainSocketTest.ConcurrentSendReceive(Boolean forceNonBlocking) in E:\A\_work\2\s\corefx\src\System.Net.Sockets\tests\FunctionalTests\UnixDomainSocketTest.netcoreapp.cs:line 284
--- End of stack trace from previous location where exception was thrown ---
```
The failures occur for both the blocking and non-blocking case, and has occurred exclusively on the Windows.10.Amd64.ClientRS4 leg.

I'm not sure if that means Unix domain sockets are not enabled in RS4, if there is some config that needs to happen on that machine, or if there is a real bug here.

**Comment by stephentoub** [comment]
@rmkerr, you said it's failing 1-2 times a day, but it's not clear to me: is that all of the RS4 runs, or are there runs where it succeeds and it's just failing sporadically?

> I'm not sure if that means Unix domain sockets are not enabled in RS4

RS4 is the first released version of Windows where they _are_ supported.

**Comment by rmkerr** [comment]
It's failing sporadically. The test has been run 24 times over the last four days, with six failures. It doesn't look like a configuration issue, since sometimes only one of the two cases will fail.

**Comment by stephentoub** [comment]
And you mentioned "official runs"... what about PRs?  It's an inner loop test, so it should be running now as part of every PR.  Has it failed there?

**Comment by rmkerr** [comment]
Looking into it now. It looks like ConcurrentSendRecieveAsync has one failure on the 15th. I'll check PRs as well.

**Comment by stephentoub** [comment]
@sunilmut, are there any known issues in RS4 with having multiple threads issuing sends/recvs on the same unix domain socket at the same time?

**Comment by rmkerr** [comment]
It looks like we're only running RS3 in PRs. So this test is always being skipped.

**Comment by rmkerr** [comment]
@stephentoub I talked to Sunil about this -- there are not any known issues around multiple sends/receives. I'll try to see if I can reproduce this locally.

**Comment by rmkerr** [comment]
My setup for checking in on the tests was just broken by the move away from ci.dot.net, so I'm not sure. I'll try to get it running again today though.

**Comment by rmkerr** [comment]
Based on [this recent test run](https://dnceng.visualstudio.com/internal/_build/results?buildId=72013&view=ms.vss-test-web.test-result-details), it looks like this is still happening.

**Comment by wfurt** [comment]
failed 20x in last 30 days in official runs.  all in Windows.10.Amd64.ClientRS4 queue.

```
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in F:\vsagent\11\s\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 69
   at System.Net.Sockets.Tests.UnixDomainSocketTest.ConcurrentSendReceiveAsync() in F:\vsagent\11\s\src\System.Net.Sockets\tests\FunctionalTests\UnixDomainSocketTest.netcoreapp.cs:line 322
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by wfurt** [comment]
This seems specific to RS4. Another 26 failures in last 20 days.

Should we disable this test on that OS? 
Perhaps push it to Feature? 
Any recommendation for instrumentation?

cc: @davidsh

**Comment by stephentoub** [comment]
> This seems specific to RS4.

Is it running and passing on RS5?

**Comment by davidsh** [comment]
>Should we disable this test on that OS?
Perhaps push it to Feature?
Any recommendation for instrumentation?
cc: @davidsh 

This is another case of asking ourselves are we adding value by testing this in CI with our .NET layer. I don't know which version of Windows 10 the UnixDomainSocket became operational. Maybe there are some bugs in it. We would have to ask the Windows TCP team.

Unless we want to spend a lot of time investigating a Windows native feature, we should either disable this test on Windows or at least restrict it to RS5 and above. That would give us some test coverage on Windows and reduce in our test results.

**Comment by wfurt** [comment]
It seems like we only do RS5 for UWP. There is another Windows.10.Amd64.Core queue, but this test does not run there. So RS4 is only Windows platform where this test runs. I don't see any failures on Unix.

**Comment by karelz** [comment]
If we don't believe this is .NET bug, I suggest to disable it on RS4 and below for now and move the issue to Future. Thoughts?

**Comment by wfurt** [comment]
Got another failure on Window.

```
  System.Net.Sockets.Tests: [Long Running Test] 'System.Net.Sockets.Tests.UnixDomainSocketTest.Socket_SendReceiveAsync_PropagateToStream_Success', Elapsed: 00:12:15
  System.Net.Sockets.Tests: [Long Running Test] 'System.Net.Sockets.Tests.UnixDomainSocketTest.Socket_SendReceiveAsync_PropagateToStream_Success', Elapsed: 00:14:15

```
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F37505~2Fmerge/test~2Ffunctional~2Fcli~2F/20190508.15/workItem/System.Net.Sockets.Tests/wilogs

**Comment by karelz** [comment]
Next steps: Re-enable the test and disable it only for RS4.

**Comment by ViktorHofer** [comment]
The test that was originally reported in the top post is still failing: https://dev.azure.com/dnceng/public/_build/results?buildId=381275&view=ms.vss-test-web.build-test-results-tab&runId=11789792&resultId=174544&paneView=debug

Configuration: `netcoreapp-Windows_NT-Debug-x64-Windows.10.Amd64.Client19H1.ES.Open`

```
System.Net.Sockets.Tests.UnixDomainSocketTest.ConcurrentSendReceive

System.TimeoutException : WhenAllOrAnyFailed timed out after 10000ms
  at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 75
   at System.Net.Sockets.Tests.UnixDomainSocketTest.ConcurrentSendReceive(Boolean forceNonBlocking) in /_/src/System.Net.Sockets/tests/FunctionalTests/UnixDomainSocketTest.netcoreapp.cs:line 283
--- End of stack trace from previous location ---
```

@stephentoub I see that you are tracking a different disabled test than the one reported initially.
