### ISSUE TITLE
SslStream.AuthenticateAsServerAsync sometimes throws an AuthenticationException on Linux

### ISSUE THREAD

**Issue by halter73** [dotnet/corefx#29746]
This might have the same root cause as #28819, but I observed this on the server side instead of the client side, and now instead of an UnauthorizedAccessException it's raised as a AuthenticationException. I observed this exception during [this kestrel test](https://github.com/aspnet/KestrelHttpServer/blob/aaaff4475a68132dbb03932869964609031915af/test/Kestrel.FunctionalTests/HttpsTests.cs#L315).

```
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.IO.IOException: Not a directory
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at Internal.Cryptography.Pal.StorePal.LoadMachineStores()
   at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
   at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
   at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.FindCandidates(X509Certificate2 leaf, X509Certificate2Collection extraStore, HashSet`1 downloaded, HashSet`1 systemTrusted, TimeSpan& remainingDownloadTime)
   at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
   at System.Net.Http.TLSCertificateExtensions.BuildNewChain(X509Certificate2 certificate, Boolean includeClientApplicationPolicy)
   at Interop.OpenSsl.AllocateSslContext(SslProtocols protocols, SafeX509Handle certHandle, SafeEvpPKeyHandle certKeyHandle, EncryptionPolicy policy, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SafeDeleteSslContext..ctor(SafeFreeSslCredentials credential, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__51_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync(ConnectionAdapterContext context) in /home/shalter/aspnet/KestrelHttpServer/src/Kestrel.Core/Internal/HttpsConnectionAdapter.cs:line 167
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.ApplyConnectionAdaptersAsync() in /home/shalter/aspnet/KestrelHttpServer/src/Kestrel.Core/Internal/HttpConnection.cs:line 313
```

**Comment by bartonjs** [comment]
That's in `LoadMachineStores`, so something must have deleted the /etc/ssl/certs (or whatever it is on your distro) directory while that was running.

**Comment by halter73** [comment]
I don't think /etc/ssl/certs is a directory that just randomly gets deleted or moved outside of perhaps a system update, and I doubt it's actually being deleted during our test runs. We've seen this issue on multiple different linux agents.

I think it is more likely that the "Not a directory" message is based on an imprecise or mistranslated error code. I have a theory that this might be caused by us hitting a file descriptor limit. If that's the case, I'll close this issue. It would be odd because AFAIK we've only hit FD limits in our macOS tests previously, but we didn't add a bunch of file logging a few weeks ago.

**Comment by stephentoub** [comment]
> I have a theory that this might be caused by us hitting a file descriptor limit. If that's the case, I'll close this issue.

If it's due to ASP.NET opening and keeping open too many file descriptors, then yeah.  But there's always the possibility that coreclr/corefx aren't being aggressive enough about closing things, leaving stuff accidentally for finalization, etc., in which case we'd want to fix that and could use this issue to track doing so.  Let us know what you find :)

**Comment by stephentoub** [comment]
> I think it is more likely that the "Not a directory" message is based on an imprecise or mistranslated error code

FWIW, that error message is coming from the OS. "Not a directory" is the Linux error message for ENOTDIR 20.  And it's coming from ReadDir:
https://github.com/dotnet/corefx/blob/b96c29aedf9b2f4197d161f632b4387a17be72f8/src/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerator.Unix.cs#L176

My guess is still that something has caused `_directoryHandle` to be closed and the file descriptor recycled for something else.  With `_directoryHandle` as an `IntPtr` rather than a `SafeHandle`, that's possible.
cc: @JeremyKuhne

**Comment by stephentoub** [comment]
> My guess is still that something has caused _directoryHandle to be closed and the file descriptor recycled for something else.

Actually, I think it's more likely this is just an extension of #28819, e.g. https://github.com/dotnet/corefx/issues/28819#issuecomment-378820810

**Comment by GrabYourPitchforks** [comment]
@halter73 Is this still affecting you?

**Comment by halter73** [comment]
I forgot all about this. I don't think I've seen this in the past 6 months or so.

**Comment by GrabYourPitchforks** [comment]
All I needed to hear. :)

**Comment by halter73** [comment]
You can probably also close #28819.
