### ISSUE TITLE
System.Net.HttpListener tests failing in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#29757]
@MattGal updated the Nano containers used in CI to v1709, and now (all) tests are failing, e.g.
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/8b94440c48148e20822d2cafebad29fed0f30f76/workItem/System.Net.HttpListener.Tests/wilogs
It looks like httpapi.dll simply isn't there.
```
2018-05-17 00:09:13,927: INFO: proc(54): run_and_log_output: Output:    System.Net.Tests.HttpListenerAuthenticationTests.AuthenticationSchemeSelectorDelegate_ThrowsOutOfMemoryException_RethrowsException [FAIL]
2018-05-17 00:09:13,928: INFO: proc(54): run_and_log_output: Output:       System.Exception : Could not reserve a port for HttpListener
2018-05-17 00:09:13,928: INFO: proc(54): run_and_log_output: Output:       ---- System.TypeInitializationException : The type initializer for 'HttpApi' threw an exception.
2018-05-17 00:09:13,928: INFO: proc(54): run_and_log_output: Output:       -------- System.DllNotFoundException : Unable to load DLL 'httpapi.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
2018-05-17 00:09:13,934: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-05-17 00:09:14,040: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.HttpListener\tests\HttpListenerFactory.cs(138,0): at System.Net.Tests.HttpListenerFactory.GetListener()
2018-05-17 00:09:14,040: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.HttpListener\tests\HttpListenerAuthenticationTests.cs(28,0): at System.Net.Tests.HttpListenerAuthenticationTests..ctor()
2018-05-17 00:09:14,040: INFO: proc(54): run_and_log_output: Output:          ----- Inner Stack Trace -----
2018-05-17 00:09:14,042: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.HttpListener\src\System\Net\Windows\HttpListener.Windows.cs(209,0): at System.Net.HttpListener.SetupV2Config()
2018-05-17 00:09:14,042: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.HttpListener\src\System\Net\Windows\HttpListener.Windows.cs(274,0): at System.Net.HttpListener.Start()
2018-05-17 00:09:14,042: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.HttpListener\tests\HttpListenerFactory.cs(46,0): at System.Net.Tests.HttpListenerFactory..ctor(String hostname, String path)
2018-05-17 00:09:14,042: INFO: proc(54): run_and_log_output: Output:          ----- Inner Stack Trace -----
2018-05-17 00:09:14,042: INFO: proc(54): run_and_log_output: Output:             at Interop.HttpApi.HttpInitialize(HTTPAPI_VERSION version, UInt32 flags, Void* pReserved)
2018-05-17 00:09:14,042: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\Common\src\Interop\Windows\HttpApi\Interop.HttpApi.cs(27,0): at Interop.HttpApi.InitHttpApi(HTTPAPI_VERSION version)
2018-05-17 00:09:14,042: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\Common\src\Interop\Windows\HttpApi\Interop.HttpApi.cs(19,0): at Interop.HttpApi..cctor()
2018-05-17 00:09:14,053: INFO: proc(54): run_and_log_output: Output:    System.Net.Tests.HttpListenerAuthenticationTests.NoAuthentication_AuthenticationProvided_ReturnsForbiddenStatusCode(headerType: \"Basic\") [FAIL]
2018-05-17 00:09:14,053: INFO: proc(54): run_and_log_output: Output:       System.Exception : Could not reserve a port for HttpListener
2018-05-17 00:09:14,055: INFO: proc(54): run_and_log_output: Output:       ---- System.TypeInitializationException : The type initializer for 'HttpApi' threw an exception.
2018-05-17 00:09:14,055: INFO: proc(54): run_and_log_output: Output:       -------- System.DllNotFoundException : Unable to load DLL 'httpapi.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
2018-05-17 00:09:14,055: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-05-17 00:09:14,055: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.HttpListener\tests\HttpListenerFactory.cs(138,0): at System.Net.Tests.HttpListenerFactory.GetListener()
2018-05-17 00:09:14,055: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.HttpListener\tests\HttpListenerAuthenticationTests.cs(28,0): at System.Net.Tests.HttpListenerAuthenticationTests..ctor()
2018-05-17 00:09:14,055: INFO: proc(54): run_and_log_output: Output:          ----- Inner Stack Trace -----
2018-05-17 00:09:14,055: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.HttpListener\src\System\Net\Windows\HttpListener.Windows.cs(209,0): at System.Net.HttpListener.SetupV2Config()
2018-05-17 00:09:14,055: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.HttpListener\src\System\Net\Windows\HttpListener.Windows.cs(274,0): at System.Net.HttpListener.Start()
2018-05-17 00:09:14,055: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.HttpListener\tests\HttpListenerFactory.cs(46,0): at System.Net.Tests.HttpListenerFactory..ctor(String hostname, String path)
2018-05-17 00:09:14,055: INFO: proc(54): run_and_log_output: Output:          ----- Inner Stack Trace -----
2018-05-17 00:09:14,056: INFO: proc(54): run_and_log_output: Output:             at Interop.HttpApi.HttpInitialize(HTTPAPI_VERSION version, UInt32 flags, Void* pReserved)
2018-05-17 00:09:14,056: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\Common\src\Interop\Windows\HttpApi\Interop.HttpApi.cs(27,0): at Interop.HttpApi.InitHttpApi(HTTPAPI_VERSION version)
...
```

**Comment by davidsh** [comment]
>It looks like httpapi.dll simply isn't there.

Yes.  Nano Container has been optimized a lot to reduce its disk size.  And part of that was to remove this.  However, I don't remember whether there is an optional component you could add to put it back.

**Comment by davidsh** [comment]
fyi: https://github.com/aspnet/aspnet-docker/issues/398

>@HeathJared @tabinnorway @acorkery We heard back from the NanoServer team. The Http.Sys stack is no longer supported in NanoServer from RS3 onwards. It was one of the components that got the cut to allow us to the shrink the size of NanoServer. As such, our recommendation now would be to use Kestrel on Nano or move to ServerCore if you require HttpSysServer.
Unfortunately, there's nothing we can do about this. If you care strongly about this, I would recommend creating an issue on the Windows Server User Voice to convince them to change their minds.

**Comment by davidsh** [comment]
We should disable all HttpListener (that uses http.sys) tests against Nano.  However, the managed HttpListener in .NET Core (used on Linux) should be ok.

**Comment by davidsh** [comment]
>Should we use the managed implementation when http.sys isn't available?

We could.  But that would be tricky. We'll have to compile both implementations into the binary and then use runtime logic to switch.  We currently only compile the managed HttpListener for non-Windows binaries.

**Comment by karelz** [comment]
I would like to switch to managed HttpListener on Windows as well as soon as we have HTTPS support (#14691). It will be needed for UWP, so I hope we will be able to switch soon.
We may expose native HttpListener as separate package in Microsoft namespace as it apparently has some additional features.

Let's disable the tests on Nano for now.

**Comment by karelz** [comment]
Drop http.sys and always use managed implementation everywhere. Offer http.sys implementation as specific opt-in.

**Comment by stephentoub** [comment]
I'm not sure the managed implementation is good enough for that yet.

**Comment by karelz** [comment]
Because of bugs? Or are there other missing features you are aware of?

**Comment by caesar1995** [comment]
https://github.com/dotnet/buildtools/pull/2040 is merged. Will submit a PR to disable the HttpListener tests on Nano soon.
