### ISSUE TITLE
System.Diagnostics.Process tests failing in CI on Nano

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#29753]
@MattGal updated the Nano containers used in CI to v1709, and now tests are failing, e.g.
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/8b94440c48148e20822d2cafebad29fed0f30f76/workItem/System.Diagnostics.Process.Tests/wilogs
```
2018-05-17 00:01:58,158: INFO: proc(54): run_and_log_output: Output:    System.Diagnostics.Tests.ProcessStartInfoTests.Verbs_GetWithExeExtension_ReturnsExpected [FAIL]
2018-05-17 00:01:58,161: INFO: proc(54): run_and_log_output: Output:       Assert.Contains() Failure
2018-05-17 00:01:58,161: INFO: proc(54): run_and_log_output: Output:       Not found: open
2018-05-17 00:01:58,161: INFO: proc(54): run_and_log_output: Output:       In value:  String[] []
2018-05-17 00:01:58,165: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-05-17 00:01:58,275: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(511,0): at System.Diagnostics.Tests.ProcessStartInfoTests.Verbs_GetWithExeExtension_ReturnsExpected()
2018-05-17 00:01:58,278: INFO: proc(54): run_and_log_output: Output:    System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_WebPage [SKIP]
2018-05-17 00:01:58,278: INFO: proc(54): run_and_log_output: Output:       Manual test
2018-05-17 00:02:01,875: INFO: proc(54): run_and_log_output: Output:    System.Diagnostics.Tests.ProcessTests.GetProcesses_RemoteMachinePath_ReturnsExpected [FAIL]
2018-05-17 00:02:01,875: INFO: proc(54): run_and_log_output: Output:       System.TypeInitializationException : The type initializer for 'System.DirectoryServices.ActiveDirectory.DirectoryContext' threw an exception.
2018-05-17 00:02:01,875: INFO: proc(54): run_and_log_output: Output:       ---- System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException : The specified module could not be found.
2018-05-17 00:02:01,875: INFO: proc(54): run_and_log_output: Output:       
2018-05-17 00:02:01,875: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-05-17 00:02:01,877: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\DirectoryContext.cs(653,0): at System.DirectoryServices.ActiveDirectory.DirectoryContext.GetDnsDomainName(String domainName)
2018-05-17 00:02:01,877: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\Domain.cs(139,0): at System.DirectoryServices.ActiveDirectory.Domain.GetComputerDomain()
2018-05-17 00:02:01,877: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.Process\tests\ProcessTests.cs(950,0): at System.Diagnostics.Tests.ProcessTests.GetProcesses_RemoteMachinePath_ReturnsExpected()
2018-05-17 00:02:01,878: INFO: proc(54): run_and_log_output: Output:          ----- Inner Stack Trace -----
2018-05-17 00:02:01,878: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\DirectoryContext.cs(695,0): at System.DirectoryServices.ActiveDirectory.DirectoryContext.GetLibraryHandle()
2018-05-17 00:02:01,878: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\DirectoryContext.cs(43,0): at System.DirectoryServices.ActiveDirectory.DirectoryContext..cctor()
2018-05-17 00:02:02,049: INFO: proc(54): run_and_log_output: Output: Invalid number of parameters
2018-05-17 00:02:02,051: INFO: proc(54): run_and_log_output: Output: 0 File(s) copied
2018-05-17 00:02:04,092: INFO: proc(54): run_and_log_output: Output: Program powershell.exe is not installed on this machine.
2018-05-17 00:02:06,474: INFO: proc(54): run_and_log_output: Output:    System.Diagnostics.Tests.ProcessTests.TestBasePriorityOnWindows [FAIL]
2018-05-17 00:02:06,474: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-05-17 00:02:06,476: INFO: proc(54): run_and_log_output: Output:       Expected: BelowNormal
2018-05-17 00:02:06,476: INFO: proc(54): run_and_log_output: Output:       Actual:   Normal
2018-05-17 00:02:06,476: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-05-17 00:02:06,476: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Diagnostics.Process\tests\ProcessTests.cs(70,0): at System.Diagnostics.Tests.ProcessTests.TestBasePriorityOnWindows()
```

**Comment by danmosemsft** [comment]
Ended up calling this by design
https://github.com/dotnet/corefx/pull/29789/files#diff-3b9989a6be55cdb6f928d6ca33ef86f5
