### ISSUE TITLE
System.IO.Ports tests failing in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#29756]
@MattGal updated the Nano containers used in CI to v1709, and now tests are failing and crashing, e.g.
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/8b94440c48148e20822d2cafebad29fed0f30f76/workItem/System.IO.Ports.Tests/wilogs
```
2018-05-17 00:09:11,585: INFO: proc(54): run_and_log_output: Output:    System.IO.Ports.Tests.OpenDevices.OpenDevices01 [FAIL]
2018-05-17 00:09:11,585: INFO: proc(54): run_and_log_output: Output:       System.Exception : Unknown Win32 Error: 6
2018-05-17 00:09:11,585: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-05-17 00:09:11,585: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Ports\tests\SerialPort\DosDevices.cs(135,0): at System.IO.Ports.Tests.DosDevices.CallQueryDosDevice(String name, Int32& dataSize)
2018-05-17 00:09:11,585: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Ports\tests\SerialPort\DosDevices.cs(83,0): at System.IO.Ports.Tests.DosDevices.Initialize()
2018-05-17 00:09:11,585: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Ports\tests\SerialPort\DosDevices.cs(18,0): at System.IO.Ports.Tests.DosDevices..ctor()
2018-05-17 00:09:11,585: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Ports\tests\SerialPort\OpenDevices.cs(19,0): at System.IO.Ports.Tests.OpenDevices.OpenDevices01()
```

**Comment by danmosemsft** [comment]
QueryDosDevice is returning "The handle is invalid" on Nano server. Apparently it wasn't previously. Probably we just want to skip this for Nano.

**Comment by stephentoub** [comment]
Other failures:
```
2018-05-18 19:13:13,845: INFO: proc(54): run_and_log_output: Output:    System.IO.Ports.Tests.GetPortNames.AllGetPortNamesAreInHelperPorts [FAIL]
2018-05-18 19:13:13,846: INFO: proc(54): run_and_log_output: Output:       COM2 is not present in PortHelper.GetPorts result
2018-05-18 19:13:13,846: INFO: proc(54): run_and_log_output: Output:       PortHelper Ports: 
2018-05-18 19:13:13,848: INFO: proc(54): run_and_log_output: Output:       SerialPort Ports: COM2
2018-05-18 19:13:13,848: INFO: proc(54): run_and_log_output: Output:       
2018-05-18 19:13:13,848: INFO: proc(54): run_and_log_output: Output:       Expected: True
2018-05-18 19:13:13,848: INFO: proc(54): run_and_log_output: Output:       Actual:   False
2018-05-18 19:13:13,854: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-05-18 19:13:13,891: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Ports\tests\SerialPort\GetPortNames.cs(64,0): at System.IO.Ports.Tests.GetPortNames.AllGetPortNamesAreInHelperPorts()
2018-05-18 19:13:13,892: INFO: proc(54): run_and_log_output: Output:    System.IO.Ports.Tests.GetPortNames.OpenEveryPortName [FAIL]
2018-05-18 19:13:13,894: INFO: proc(54): run_and_log_output: Output:       System.IO.IOException : The port 'COM2' does not exist.
2018-05-18 19:13:13,894: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-05-18 19:13:13,894: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Ports\src\System\IO\Ports\InternalResources.cs(74,0): at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
2018-05-18 19:13:13,894: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Ports\src\System\IO\Ports\InternalResources.cs(54,0): at System.IO.Ports.InternalResources.WinIOError(String str)
2018-05-18 19:13:13,894: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Ports\src\System\IO\Ports\SerialStream.cs(606,0): at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
2018-05-18 19:13:13,894: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Ports\src\System\IO\Ports\SerialPort.cs(567,0): at System.IO.Ports.SerialPort.Open()
2018-05-18 19:13:13,895: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Ports\tests\SerialPort\GetPortNames.cs(32,0): at System.IO.Ports.Tests.GetPortNames.OpenEveryPortName()
```

**Comment by danmosemsft** [comment]
@pjanotti could you please find out whether serial ports should be working on Nano? Let me know if you need a contact. Then we can either log a bug but either way the test should be disabled.

**Comment by danmosemsft** [comment]
Fair enough. I guess they just made QueryDosDevice more truthful. @pjanotti if you can't get to this today let me know and I will do it.

**Comment by pjanotti** [comment]
I probably only can do it in the evening... so if you can thanks, if not I will pick it up later.

**Comment by pjanotti** [comment]
BTW, currently no serial ports for docker Windows containers https://github.com/docker/for-win/issues/1018

**Comment by danmosemsft** [comment]
Thanks @pjanotti
