### ISSUE TITLE
ClientWebSocket.CloseAsync call causes ServerWebSocket.ReceiveAsync call fail

### ISSUE THREAD

**Issue by maincoon** [dotnet/corefx#29768]
[WSTest.zip](https://github.com/dotnet/corefx/files/2014387/WSTest.zip)

Attached sample produces different errors on windows and linux.
Windows build fails both ClientWebSocket.CloseAsync() and ServerWebSocket.ReadAsync() calls :

```Listen at ws://localhost:9002
Got client connection
reader failed System.Net.WebSockets.WebSocketException (0x83760002): Недопустимый формат данных для определенной операции протокола
   at System.Net.WebSockets.WebSocketProtocolComponent.WebSocketGetAction(WebSocketBase webSocket, ActionQueue actionQueue, Buffer[] dataBuffers, UInt32& dataBufferCount, Action& action, BufferType&
 bufferType, IntPtr& actionContext)
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.Process(Nullable`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketBase.ReceiveAsyncCore(ArraySegment`1 buffer, CancellationToken cancellationToken)
   at WSTest.Program.Reader(WebSocket webSocket) in C:\Projects\WSTest\Program.cs:line 46

test failed System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: Unable to read
 data from the transport connection: Удаленный хост принудительно разорвал существующее подключение. ---> System.Net.Sockets.SocketException: Удаленный хост принудительно разорвал существующее подкл
ючение
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceive
ResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceive
ResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.CloseAsyncPrivate(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)
   at WSTest.Program.ConnectDisconnect(String enpoint) in C:\Projects\WSTest\Program.cs:line 73
   at WSTest.Program.Test() in C:\Projects\WSTest\Program.cs:line 81
```

dotnet -info output

```Пакет SDK для .NET Core (отражающий любой global.json):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\

Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051

.NET Core SDKs installed:
  1.0.2 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

Same sample on Linux build fails ServerWebSocket.ReceiveAsync() call

```[root@ud-dev06-lxc-test-v test]# dotnet run
Listen at ws://localhost:9002
Got client connection
reader failed System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): An exception caused the WebSocket to enter the Aborted state. Please see the InnerException, if present, for more details.
   at System.Net.WebSockets.ManagedWebSocket.CloseWithReceiveErrorAndThrowAsync(WebSocketCloseStatus closeStatus, WebSocketError error, Exception innerException)
   at System.Net.WebSockets.ManagedWebSocket.HandleReceivedCloseAsync(MessageHeader header)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at WSTest.Program.Reader(WebSocket webSocket) in /root/test/Program.cs:line 46
```
dotnet --info output:

```[root@ud-dev06-lxc-test-v test]# dotnet --info
Пакет SDK для .NET Core (отражающий любой global.json):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73

Среда выполнения:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300-rc1-008673/

Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051

.NET Core SDKs installed:
  2.1.300-rc1-008673 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
Despite on this errors same sample works fine from browser (Chrome) javascript connections on both systems.

I found this accidentally while researching another issue and trying to create proper test. On linux (windows is ok) any attempt to close webcosket (ServerWebSocket.CloseOutputAsync, ServerWebSocket.CloseAsync,ServerWebSocket.Abort, ServerWebSocket..Dispose - whatever) leaves socket descriptor in CLOSE_WAIT state so it causes to resource and memory leak. Should I post another issue on this?

**Comment by stephentoub** [comment]
The test program you're running is invalid: WebSocketCloseStatus.Empty is not a valid close status to actually send.  If you change both occurrences of WebSocketCloseStatus.Empty to instead be WebSocketCloseStatus.NormalClosure, everything runs fine.

**Comment by davidsh** [comment]
The exception being returned by the client-side API also concurs with the use of an invalid websocket close frame status:

>Invalid data format for a specific protocol operation

Closing this issue since it appears to be a test bug.
