### ISSUE TITLE
StartInfo_TextFile_ShellExecute failing consistently on RS4

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#29815]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180521.01/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessStartInfoTests~2FStartInfo_TextFile_ShellExecute

Apparently Process.Start on foo.txt with UseShellExecute=true is returning a null process object. 

```
Could not start C:\\Users\\runner\\AppData\\Local\\Temp\\ProcessStartInfoTests_x1e54hcw.eri\\StartInfo_TextFile_ShellExecute_993_88c6de27.txt UseShellExecute=True
Association details for '.txt'
------------------------------
Open command: C:\\Windows\\system32\\NOTEPAD.EXE %1
ProgID: txtfile

Expected: True
Actual:   False
Stack Trace :
   at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute() in E:\A\_work\63\s\corefx\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs:line 990
```

**Comment by stephentoub** [comment]
FWIW, I'm on RS4 and this isn't failing for me locally.
```
d:\repos\corefx\src\System.Diagnostics.Process\tests>msbuild /t:rebuildandtest /p:Outerloop=true /v:m /p:XunitOptions="-method System.Diagnostics.Tests.ProcessstartInfoTests.StartInfo_TextFile_ShellExecute"
Microsoft (R) Build Engine version 15.8.59.53024 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  RemoteExecutorConsoleApp -> d:\repos\corefx\bin\AnyOS.AnyCPU.Debug\RemoteExecutorConsoleApp\netstandard\RemoteExecutorConsoleApp.exe
  System.Diagnostics.Process.Tests -> d:\repos\corefx\bin\Windows_NT.AnyCPU.Debug\System.Diagnostics.Process.Tests\netcoreapp\System.Diagnostics.Process.Tests.dll
  Using d:\repos\corefx\bin\testhost\netcoreapp-Windows_NT-Debug-x64\ as the test runtime folder.
  Executing in d:\repos\corefx\bin\tests\System.Diagnostics.Process.Tests\netcoreapp-Windows_NT-Debug-x64\
  ----- start  9:39:34.33 ===============  To repro directly: =====================================================
  pushd d:\repos\corefx\bin\tests\System.Diagnostics.Process.Tests\netcoreapp-Windows_NT-Debug-x64\
  set XUNIT_PERFORMANCE_MIN_ITERATION=1
  set XUNIT_PERFORMANCE_MAX_ITERATION=1
  set XUNIT_PERFORMANCE_MAX_ITERATION_INNER_SPECIFIED=1
  call d:\repos\corefx\bin\testhost\netcoreapp-Windows_NT-Debug-x64\\dotnet.exe xunit.console.netcore.exe System.Diagnostics.Process.Tests.dll  -xml testResults.xml -notrait category=nonnetc
  oreapptests -notrait category=nonwindowstests -method System.Diagnostics.Tests.ProcessstartInfoTests.StartInfo_TextFile_ShellExecute  -notrait category=failing
  popd
  ===========================================================================================================
  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.

  Discovering: System.Diagnostics.Process.Tests
  Discovered:  System.Diagnostics.Process.Tests
  Starting:    System.Diagnostics.Process.Tests
  Finished:    System.Diagnostics.Process.Tests

  === TEST EXECUTION SUMMARY ===
     System.Diagnostics.Process.Tests  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.309s
  ----- end  9:39:34.97 ----- exit code 0 ----------------------------------------------------------
```

**Comment by danmosemsft** [comment]
For what its worth this is what this configuration reports in the official runs
```
2018-05-29 03:11:35,765: INFO: proc(54): run_and_log_output: Output: ### CONFIGURATION: WindowsProductType=4 WindowsInstallationType=Client OS=Microsoft Windows 10.0.17134 OSVer=Microsoft Windows NT 6.2.9200.0 OSArch=X64 Arch=X64 Framework=.NET Core 4.6.26528.04 LibcRelease=glibc_not_found LibcVersion=glibc_not_found
```
it's 1803/17134.

Since this test relies on file associations which are stored in the registry, perhaps a fresh install of RS4 does not get some key that is already set if you upgrade.

**Comment by danmosemsft** [comment]
It doesn't fail on an official repro box. These do, though:
```
   System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadVerb(useShellExecute: False) [FAIL]
      Assert.Equal() Failure
      Expected: 2  //ERROR_FILE_NOT_FOUND
      Actual:   193 // ERROR_BAD_EXE_FORMAT 
      Stack Trace:
         E:\A\_work\6\s\corefx\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(1139,0): at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadVerb(Boolean useShellExecute)
   System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadVerb(useShellExecute: True) [FAIL]
      Assert.Equal() Failure
      Expected: 2 //ERROR_FILE_NOT_FOUND
      Actual:   1155 // ERROR_NO_ASSOCIATION 

      Stack Trace:
         E:\A\_work\6\s\corefx\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(1139,0): at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadVerb(Boolean useShellExecute)```
```

**Comment by danmosemsft** [comment]
If I clear the ftype association it does fail, but differntly:
```
>ftype txtfile
txtfile=%SystemRoot%\system32\NOTEPAD.EXE %1
>ftype txtfile=
>ftype txtfile
File type 'txtfile' not found or no open command associated with it.


   System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute [FAIL]
      Could not start C:\Users\dotnet-bot\AppData\Local\Temp\ProcessStartInfoTests_dnhs3zpb.qe4\StartInfo_TextFile_ShellExecute_1014_3ef1ad94.txt UseShellExecute=True
      Association details for '.txt'
      ------------------------------
      Open command: Didn't get expected HRESULT (1) when getting char count. HRESULT was 0x80070483 /// ERROR_NO_ASSOCIATION
      ProgID: txtfile

      Expected: True
      Actual:   False
      Stack Trace:
         E:\A\_work\6\s\corefx\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(1011,0): at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute()
```

**Comment by JeremyKuhne** [comment]
Are we grabbing the registry info when it fails? I presume that would help.

What we might have to ultimately do is create our own dummy association for notepad.exe. Like *.shellextest. I'm hesitant to drop an association down to some exe we place.

**Comment by danmosemsft** [comment]
https://dnceng.visualstudio.com/internal/_build/results?buildId=68168&view=ms.vss-test-web.test-result-details
```

Could not start C:\\Users\\runner\\AppData\\Local\\Temp\\ProcessStartInfoTests_03i0xdnw.xq4\\StartInfo_TextFile_ShellExecute_1015_e7889829.txt UseShellExecute=True\r\nAssociation details for '.txt'\r\n------------------------------\r\nOpen command: C:\\Windows\\system32\\NOTEPAD.EXE %1\r\nProgID: txtfile\r\n\r\nExpected: True\r\nActual: False
Stack trace
   at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute() in F:\vsagent\-containerSas\32\s\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs:line 1027
```
netcoreapp-Windows_NT-Release-x64-Windows.10.Amd64.ClientRS4
