### ISSUE TITLE
Test System.Net.Sockets.Tests.SendReceiveMemoryNativeTask.SendRecvPollSync_TcpListener_Socket(listenAt: ::1, pollBeforeOperation: True) failed in CI.

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/corefx#29862]
Test: System.Net.Sockets.Tests.SendReceiveMemoryNativeTask.SendRecvPollSync_TcpListener_Socket(listenAt: ::1, pollBeforeOperation: True) has failed.

MESSAGE:
Assert.Equal() Failure\nExpected: 123456\nActual: 123455
+++++++++++++++++++
STACK TRACE:
at System.Net.Sockets.Tests.SendReceive`1.SendRecvPollSync_TcpListener_Socket(IPAddress listenAt, Boolean pollBeforeOperation) in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu16.04_debug/src/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:line 630 --- End of stack trace from previous location where exception was thrown ---

Details:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu16.04_debug/403/testReport/System.Net.Sockets.Tests/SendReceiveMemoryNativeTask/SendRecvPollSync_TcpListener_Socket_listenAt____1__pollBeforeOperation__True_/

**Comment by wfurt** [comment]
This test is still failing on Windows10RS4 and Nano. 


https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190423.6/workItem/System.Net.Sockets.Tests/wilogs

```
    System.Net.Sockets.Tests.SendReceiveSync.SendRecvPollSync_TcpListener_Socket(listenAt: 127.0.0.1, pollBeforeOperation: False) [FAIL]
      Read poll after completion should have succeeded
      Expected: True
      Actual:   False
      Stack Trace:
        F:\workspace\_work\1\s\src\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs(598,0): at System.Net.Sockets.Tests.SendReceive`1.<>c__DisplayClass8_1.<<SendRecvPollSync_TcpListener_Socket>b__0>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        F:\workspace\_work\1\s\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(83,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        F:\workspace\_work\1\s\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(111,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        F:\workspace\_work\1\s\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(71,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        F:\workspace\_work\1\s\src\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs(645,0): at System.Net.Sockets.Tests.SendReceive`1.SendRecvPollSync_TcpListener_Socket(IPAddress listenAt, Boolean pollBeforeOperation)
        --- End of stack trace from previous location where exception was thrown ---
      Output:
        4/23/2019 5:08:32 PM Starting listener at 127.0.0.1:53456

```
Documentation onn Poll() says: 
> true if Listen(Int32) has been called and a connection is pending; -or- true if data is available for reading; -or- true if the connection has been closed, reset, or terminated; otherwise, returns false.

Do you have any recommendation @davidsh what additional instrumentation should we add?

**Comment by davidsh** [comment]
All the tests in this [file](https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs) are historically flaky.  You'll notice that many of them are Outerloop and yet don't contact external servers. That's because they were so unstable at the time that we moved them to Outerloop.

poll() operations of sockets in Windows especially loopback can be problematic because of interesting optimizations for fastpath I/O that Windows does in the loopback adapter.

Unless we want to spend a lot of time making these tests more stable, I would disable this particular test with an ActiveIssue for now.
