### ISSUE TITLE
System.Data.SqlClient 4.5.0-rc1 in an UWP application can not connect to local MSSQL-DB

### ISSUE THREAD

**Issue by Martin-Stein** [dotnet/corefx#29870]
Hello,
I am using the System.Data.SqlClient 4.5.0-rc1 in an UWP application. It works so far, but I am not able to connect to a local MSSQL Database, only Azure, or DBs on a different Server can be connected. When I try to connect my local server a network-related error occurs . (Provider TCP Provider, error 40 - Could not open a connection to SQL ServerTCPIP is enabled in the SQL Management console.

Kind regards,
Martin Stein

**Comment by weshaggard** [comment]
Yes there are some UWP assets that are in the new SqlClient package.

**Comment by karelz** [comment]
OK, then it may be real regression in the 4.5.0 package - looks like @keeratsingh is already investigating ...

**Comment by keeratsingh** [comment]
@Martin-Stein 
- Along with Karel's request, could you also share the Connection String being used to connect to the SQL Server. I will try to repro the issue in-house and let you know once I have questions/comments.
- Also, can you confirm if you are able to connect to this local SQL Server using SQL Server Management Studio

**Comment by keeratsingh** [comment]
@Martin-Stein 

I tried the connection strings above and `System.Data.SqlClient` version `4.4.3` connects as expected, however version `4.5.0-rc1` gives the following exception on `SqlConnection.Open()`, bear in mind the error is different from what your are seeing. I will investigate further as to why I am seeing this error.
`SDK Target Version Windows 10, version 1803(10.0; Build 17134)`

```cs
Exception: Method not found: 'Boolean System.String.Contains(Char)'.
Stack Trace:
   at System.Data.SqlClient.SNI.DataSource.InferNamedPipesInformation()
   at System.Data.SqlClient.SNI.DataSource.ParseServerName(String dataSource)
   at System.Data.SqlClient.SNI.SNIProxy.CreateConnectionHandle(Object callbackObject, String fullServerName, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Byte[]& instanceName, Byte[]& spnBuffer, Boolean flushCache, Boolean async, Boolean parallel, Boolean isIntegratedSecurity)
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.CreatePhysicalSNIHandle(String serverName, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Byte[]& instanceName, Byte[]& spnBuffer, Boolean flushCache, Boolean async, Boolean parallel, Boolean isIntegratedSecurity)
   at System.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover)
   at System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at gh_29870_UWP.MainPage.btnConnect_Click(Object sender, RoutedEventArgs e)
```
[Here](https://www.mssqltips.com/sqlservertip/2340/resolving-could-not-open-a-connection-to-sql-server-errors/) are a couple of more suggestions you could try if it resolves your issue. 
Also could you try this simple connection repro and share the output (complete error and stack trace)
```cs
private void Connect()
{
  string connectionString = "Data Source=localhost;Initial Catalog=Master;Integrated Security=False;User ID=sa;Password=*****";
  using (SqlConnection Conn = new SqlConnection(connectionString))
  {
    try
    {
        Conn.Open();
        // tbConnectionInfo is a textbox.
        tbConnectionInfo.Text += "Connection Open\n";
        Conn.Close();
        tbConnectionInfo.Text += "Connection Closed";
    }
    catch (Exception ex)
    {
        tbConnectionInfo.Text += ex.Message + "\n";
        tbConnectionInfo.Text += ex.StackTrace;
    }
  }
}

```

**Comment by Martin-Stein** [comment]
Hi keeratsingh,

Your provided suggestions in your link have not helped :-(

Here is the result of your code above:

A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at SQLDBDiagrammGenerator.UWP.MainPage.<cboDbs_DropDownOpened>d__24.MoveNext()



Thanks,

Martin

**Comment by keeratsingh** [comment]
@Martin-Stein 
Could you kindly share the output for the following command `netstat -ano | find "1433"`
You can execute this from the command prompt. 
Here is what the output looks like for me.
```cmd
D:\>netstat -ano | find "1433"
  TCP    0.0.0.0:1433           0.0.0.0:0              LISTENING       5196
  TCP    [::]:1433              [::]:0                 LISTENING       5196
```

**Comment by Martin-Stein** [comment]
Hi keeratsingh,
here is the result

C:\WINDOWS\system32>netstat -ano | find "1433"
  TCP    0.0.0.0:1433           0.0.0.0:0              LISTENING         17052
  TCP    [::]:1433                 [::]:0                     LISTENING         17052

**Comment by keeratsingh** [comment]
@Martin-Stein 
I was able to successfully connect to a local MSSQL-DB using **UWP** app with both SqlClient versions **`4.5.0-rc1 and 4.5.0 stable`**.  
As confirmed, no exception was seen for `System.Data.SqlClient` versions **`4.5.0-rc1/4.5.0 stable`** with `Microsoft.NETCore.UniversalWindowsPlatform` versions **`6.1.4/6.15/6.2.0-Preview1-26502-02`** while using the Min Target Version: **`Windows 10 Fall Creators Update (10.0; Build 16299)`**

The exception `Exception: Method not found: 'Boolean System.String.Contains(Char)'` is only seen when the Min Target Version is updated to **`Windows 10, version 1803(10; Build 17134)`**


To confirm the local SQLServer at your end is setup properly could you kindly try the following steps:
- [Download](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.0-download.md) and install the .NET Core SDK 2.1.300
- Execute command `dotnet --info` and paste the output here, similar to the one shown below.
- Run the [netcore_adhoc_minimal.zip](https://github.com/dotnet/corefx/files/2091503/netcore_adhoc_minimal.zip) app with command `dotnet run` and paste the output here.



### dotnet --info output
```cmd
PS D:\netcore_adhoc_minimal> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### adhoc output
```cmd
D:\netcore_adhoc_minimal> dotnet run
Connection Open

Compatibility Level = 140
SQLServer Version = Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)
        Aug 22 2017 17:04:49
        Copyright (C) 2017 Microsoft Corporation
        Enterprise Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 17134: )

Connection Close
```

**Comment by keeratsingh** [comment]
@Martin-Stein Did you get a chance to try the steps listed above ?

**Comment by Martin-Stein** [comment]
Hi keeratsingh,
Sorry for the late response. On my developer machine it is working with 4.5.0 stable version. But on two different non developer-machines it is not working!  Here are the requested results for one of them:

**dotNet --info:**

C:\WINDOWS\system32>dotnet --info
.NET Core SDK (gemäß "global.json"):
 Version:   2.1.300
 Commit:    adab45bf0c

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download


**adHoc output:**

Connection Open

Compatibility Level = 130
SQLServer Version = Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)
        Mar 18 2018 09:11:49
        Copyright (c) Microsoft Corporation
        Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 17134: )

Connection Close


Kind regards,

Martin

**Comment by Martin-Stein** [comment]
Hi keeratsingh,
I made some more investigations. My App is not working with local SQL-Servers, when I run the released version, available from the store. But when I compile it and deploy it from VS locally it works!

Kind regards,

Martin
