### ISSUE TITLE
byte.Parse doesn't respect span length

### ISSUE THREAD

**Issue by carlreinke** [dotnet/corefx#29947]
### Test case
```C#
using System;
using System.Globalization;

namespace Test
{
    internal class Program
    {
        static void Main()
        {
            {   // Pass
                string str = "ff";
                var span = str.AsSpan(0, 2);
                byte.Parse(span, NumberStyles.AllowHexSpecifier, CultureInfo.InvariantCulture);
            }
            {   // Pass
                string str = "fff";
                var span = str.AsSpan(1, 2);
                byte.Parse(span, NumberStyles.AllowHexSpecifier, CultureInfo.InvariantCulture);
            }
            {   // Pass
                string str = "ffX";
                var span = str.AsSpan(0, 2);
                byte.Parse(span, NumberStyles.AllowHexSpecifier, CultureInfo.InvariantCulture);
            }
            {   // Fail
                string str = "fff";
                var span = str.AsSpan(0, 2);
                byte.Parse(span, NumberStyles.AllowHexSpecifier, CultureInfo.InvariantCulture);
            }
        }
    }
}
```
### Exception
```
System.OverflowException: Value was either too large or too small for an unsigned byte.
   at System.Byte.Parse(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.Byte.Parse(ReadOnlySpan`1 s, NumberStyles style, IFormatProvider provider)
   at Test.Program.Main() in ...\Program.cs:line 28
```

**Comment by kasper3** [comment]
`fff` is 4095, byte can only hold value up to 255, hence OverflowException.
note that the second argument of `AsSpan` is length, so you can do `str.AsSpan(1,1)`

**Comment by carlreinke** [comment]
Okay, here's a simpler example:
```C#
using System;
using System.Globalization;

namespace Test
{
    internal class Program
    {
        static void Main()
        {
            string str = "ff";
            var span = str.AsSpan(0, 1);
            var value = byte.Parse(span, NumberStyles.AllowHexSpecifier);
            Console.WriteLine($"{span.ToString()} => {value:x}");
        }
    }
}
```
Output:
```
f => ff
```

**Comment by stephentoub** [comment]
What version are you using? This sounds like the issue fixed in https://github.com/dotnet/coreclr/pull/17808.

**Comment by danmosemsft** [comment]
@carlreinke you can verify the version you are using by adding `Console.WriteLine(typeof(string).Assembly.CodeBase);`

On my machine I get
```
f => f
file:///C:/Program Files/dotnet/shared/Microsoft.NETCore.App/2.1.0-rtm-26515-03/System.Private.CoreLib.dll
```

Thanks for reporting. Please reopen if you have any issues upgrading to a newer version (eg., from links at https://github.com/dotnet/cli or, in not long, from the official release page)

**Comment by carlreinke** [comment]
file:///C:/Program Files/dotnet/shared/Microsoft.NETCore.App/2.1.0-rc1/System.Private.CoreLib.dll

If it's fixed in RTM then I guess I'll just wait a bit.
