### ISSUE TITLE
System.Xml.Tests.XsltcTestSettings tests failing on ES leg

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#30017]
A bunch of these tests have started failing on all PRs.  I don't know what's changed, but the errors are due to the code comparing an expected English string against the actual Spanish string.

e.g.
https://mc.dot.net/#/user/brianrob/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/71f64b25cd53371ac8cec514d6bb0644bdc232a1/workItem/XsltCompiler.Tests
```
2018-05-31 15:32:12,029: INFO: proc(54): run_and_log_output: Output:    System.Xml.Tests.XsltcTestSettings.Var1(param0: \"/settings:DTD- sft28.xsl\", param1: \"sft28.dll\", param2: \"no\", param3: \"sft28\", param4: \"sft28.pdb\", param5: \"no\", param6: \"sft28.txt\") [FAIL]
2018-05-31 15:32:12,029: INFO: proc(54): run_and_log_output: Output:       OLEDB.Test.ModuleCore.CTestFailedException : Output was not as expected.
2018-05-31 15:32:12,029: INFO: proc(54): run_and_log_output: Output:       Expected: `sft28a.xsl(0,0) : fatal error : Processing DTDs is prohibited. For trusted stylesheets use /settings:dtd option to enable this feature.
2018-05-31 15:32:12,029: INFO: proc(54): run_and_log_output: Output: `
2018-05-31 15:32:12,029: INFO: proc(54): run_and_log_output: Output:       Actual: `sft28a.xsl(0,0) : fatal error : El procesamiento de DTD est� prohibido. Con las hojas de estilos de confianza, use la opci�n /settings:dtd para habilitar esta caracter�stica.
2018-05-31 15:32:12,029: INFO: proc(54): run_and_log_output: Output: `
2018-05-31 15:32:12,029: INFO: proc(54): run_and_log_output: Output:       Result: 0
2018-05-31 15:32:12,029: INFO: proc(54): run_and_log_output: Output:       
2018-05-31 15:32:12,029: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-05-31 15:32:12,029: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs(102,0): at System.Xml.Tests.XsltcTestCaseBase.CompareOutput(Stream expectedStream, Stream actualStream, Int32 count)
2018-05-31 15:32:12,029: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs(186,0): at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean runAssemblyVerification, Boolean loadFromFile)
2018-05-31 15:32:12,029: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs(145,0): at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean loadFromFile)
2018-05-31 15:32:12,029: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestSettings.cs(67,0): at System.Xml.Tests.XsltcTestSettings.Var1(Object param0, Object param1, Object param2, Object param3, Object param4, Object param5, Object param6)
```

**Comment by karelz** [comment]
@krwq @pjanotti can you please take a look at it?

**Comment by danmosemsft** [comment]
It's no surprise these were flagged if they're looking for English strings. They should not. If it's not easy to replace the validation, I suggest wrapping this assert in a check that the thread culture is en-US. We do still run tests on that, so the message will get validated there.

**Comment by stephentoub** [comment]
Yes.  What I'm not clear on is why they only just started failing.  And why they didn't fail in the PRs to move us to Spanish OS installs.

**Comment by safern** [comment]
It is supposed to be skipped in non-English cultures: https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/tests/Xslt/XsltCompiler/CommonScenarios/XsltcTestCaseBase.cs#L124
