### ISSUE TITLE
AV in X509Certificate.LoadCertificateFromFile on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#30028]
```
2018-05-31 21:03:06,148: INFO: proc(54): run_and_log_output: Output: C:\dotnetbuild\work\cdac3230-f9d9-4003-b8d4-fe2afbe9188f\Work\d2b3f142-08d1-4e04-ae67-61bea0fc5170\Unzip>call xunit.console.exe System.Net.Security.Tests.dll  -noshadow -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetfxtests -notrait category=nonwindowstests  -notrait category=OuterLoop -notrait category=failing 
2018-05-31 21:03:06,381: INFO: proc(54): run_and_log_output: Output: xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
2018-05-31 21:03:06,742: INFO: proc(54): run_and_log_output: Output:   Discovering: System.Net.Security.Tests
2018-05-31 21:03:07,256: INFO: proc(54): run_and_log_output: Output:   Discovered:  System.Net.Security.Tests
2018-05-31 21:03:07,256: INFO: proc(54): run_and_log_output: Output:   Starting:    System.Net.Security.Tests
2018-05-31 21:03:12,476: INFO: proc(54): run_and_log_output: Output: 
2018-05-31 21:03:12,615: INFO: proc(54): run_and_log_output: Output: Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
2018-05-31 21:03:12,615: INFO: proc(54): run_and_log_output: Output:    at System.Security.Cryptography.X509Certificates.X509Utils._LoadCertFromFile(String fileName, IntPtr password, UInt32 dwFlags, Boolean persistKeySet, SafeCertContextHandle& pCertCtx)
2018-05-31 21:03:12,615: INFO: proc(54): run_and_log_output: Output:    at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags)
2018-05-31 21:03:12,615: INFO: proc(54): run_and_log_output: Output:    at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
2018-05-31 21:03:12,615: INFO: proc(54): run_and_log_output: Output:    at System.Net.Test.Common.Configuration.Certificates.GetCertificate(String certificateFileName)
2018-05-31 21:03:12,615: INFO: proc(54): run_and_log_output: Output:    at System.Net.Security.Tests.DummyTcpServer.OnAccept(Task`1 result)
2018-05-31 21:03:12,615: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.Execute()
2018-05-31 21:03:12,615: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
2018-05-31 21:03:12,615: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
2018-05-31 21:03:12,615: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2018-05-31 21:03:12,615: INFO: proc(54): run_and_log_output: Output:    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
2018-05-31 21:03:12,615: INFO: proc(54): run_and_log_output: Output:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by stephentoub** [comment]
Again here:
https://github.com/dotnet/corefx/pull/29903#issuecomment-391901074

**Comment by davidsh** [comment]
@stephentoub I noticed you labeled this "System.Net.Security".  I would think it a bug in System.Security, X509* since it is an AV.

**Comment by davidsh** [comment]
I have a theory about this failure.  I think it started to happen after my PR #29758.

Perhaps removing the Mutex is a problem for .NET Framework.  Maybe there is some other bug about loading the same PFX file from concurrent threads (tests in our case).  

We thought the Mutex was only needed to deal with the "friendlyname on private key" problem (which we fixed by removing that friendlyname via @bartonjs pfxedit tool).

See:  https://github.com/dotnet/corefx/pull/29758#discussion_r188925040

cc: @bartonjs

**Comment by davidsh** [comment]
>Perhaps removing the Mutex is a problem for .NET Framework.

Currently CI runs on .NET 4.6.x.  Once PR #28883 is merged, it will run against 4.7.2. I wonder whether this possible .NET Framework bug might be fixed on 4.7.2.

**Comment by stephentoub** [comment]
Leaving this open for a few days to see if it happens again now that #30090 was merged...

**Comment by stephentoub** [comment]
Not fixed, e.g.
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/40440addd79355041e07acd3c48f56cafa10f79e/workItem/System.Net.Security.Tests/wilogs
```
2018-06-04 20:20:17,173: INFO: proc(54): run_and_log_output: Output: Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
2018-06-04 20:20:17,173: INFO: proc(54): run_and_log_output: Output:    at System.Security.Cryptography.X509Certificates.X509Utils._LoadCertFromBlob(Byte[] rawData, IntPtr password, UInt32 dwFlags, Boolean persistKeySet, SafeCertContextHandle& pCertCtx)
2018-06-04 20:20:17,173: INFO: proc(54): run_and_log_output: Output:    at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromBlob(Byte[] rawData, Object password, X509KeyStorageFlags keyStorageFlags)
2018-06-04 20:20:17,173: INFO: proc(54): run_and_log_output: Output:    at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
2018-06-04 20:20:17,173: INFO: proc(54): run_and_log_output: Output:    at System.Net.Test.Common.Configuration.Certificates.GetCertificate(String certificateFileName)
2018-06-04 20:20:17,173: INFO: proc(54): run_and_log_output: Output:    at System.Net.Security.Tests.ServerAsyncAuthenticateTest..ctor()
```
cc: @bartonjs

**Comment by bartonjs** [comment]
I've started a thread with Windows people.  It seems like the problem doesn't have to do with "from file" or "same file" or "same contents", just that there's a race condition with a global deep within PFXImportCertStore in the latest release.

Not sure why the X509Certificates tests don't hit it, they must just do enough other work that the race never hits.

Putting the mutex back would ameliorate the problem, which hopefully gets fixed relatively soon.

**Comment by davidsh** [comment]
The crash is still occuring on .NET Core CI runs and not just Desktop (.NET Framework).  So, we should probably put back the mutex in the test code.

**Comment by davidsh** [comment]
>So, we should probably put back the mutex in the test code.

I will put up a PR for adding back the mutex.

**Comment by davidsh** [comment]
Ref: Internal bug 16598407
