### ISSUE TITLE
ConnectTimeout_TimesOutSSLAuth_Throws fails with unexpected exception type

### ISSUE THREAD

**Issue by rmkerr** [dotnet/corefx#30032]
`ConnectTimeout_TimesOutSSLAuth_Throws` expects an exception of type `TaskCancelledException` to be thrown. However, this test occasionally fails when `HttpRequestException` is thrown instead. 

Stack Trace:
```
Assert.Throws() Failure\nExpected: typeof(System.Threading.Tasks.TaskCanceledException)\nActual:   typeof(System.Net.Http.HttpRequestException): The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in /root/corefx-1719184/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 84
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /root/corefx-1719184/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 342
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask) in /root/corefx-1719184/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 484
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /root/corefx-1719184/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 275
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /root/corefx-1719184/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 33
```

The test itself:
https://github.com/dotnet/corefx/blob/31f7b653fe62317c7edd5c3fc59430462197934d/src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs#L485-L505

The test appears to have failed primarily May 5th, with all recent failures on Unix. There is one outlier that failed on March 21st on Win10. The failure is intermittent, occurring in fewer than half of the official runs.

**Comment by davidsh** [comment]
Although we should figure out why the test sometimes fails, I don't think a TaskCanceledException is correct when setting the .ConnectTimeout property.  TaskCanceledException is more appropriate when a CancellationToken is being set to Canceled.  It would be better if this behavior was HttpRequestException with an inner exception of TimeoutException.

There is already a related issue about this topic in general: #20296

**Comment by wfurt** [comment]
I have reasonable repro on my local Linux machine. (and occasional OSX)
It seems like if we cancel while negotiating SSL, we get expected exception. When test run is slow (perhaps because of other test) and we cancel while trying to connect, we get HttpRequestException exception. There is function trying to determine if wrap or not but the behavior is certainly inconsistent. 

do you have more thoughts on this and linked #20296 @geoffkizer ???

It would be easy enough to update the test to expect one ot the other cancelation exception. 
But I'm not sure if we want to change the product as well.

**Comment by karelz** [comment]
If there is some easy way to turn the TaskCanceledException in such case into HttpRequestException with inner TimeoutException, I would prefer to change the product.
Are we able to distinguish timeouts from user-induced task cancellations in this case?

**Comment by wfurt** [comment]
There is already logic to wrap or not. 

https://github.com/dotnet/corefx/blob/09e413092dbde9ac573c7c53cd9c104b525e0468/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs#L82-L86

I assume it was added for a reason. 
On the failed cases, CancelationRequested is set to false on cancelation token.

**Comment by rmkerr** [comment]
It looks like we're enforcing the timeout by cancelling the connect with a cancellation token:

https://github.com/dotnet/corefx/blob/5bff639f1afd949852bc098fed27c002d5916036/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L504-L512

Since we choose to wrap the final exception based on the cancellation token status, we don't currently have a way to distinguish between a user cancellation and a connect timeout:

https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/CancellationHelper.cs#L16-L21

We could probably improve this by caching the original cancellation token and passing it into `ShouldWrapInOperationCanceledException` instead.

**Comment by geoffkizer** [comment]
If we think it's important to re-enable the test, then sure, go for it.

**Comment by geoffkizer** [comment]
> I think that the expected exception is wrong though, and that the fix should be to (1) make sure that the same exception is always thrown and (2) change the expected exception to HttpRequestException rather than OperationCanceledException

I agree, but if I'm understanding properly, the tricky part here is distinguishing whether we are cancelling due to ConnectTimeout or due to an explicit CancellationToken from the user. Am I understanding correctly?

**Comment by rmkerr** [comment]
Yeah, that's correct.

I think we could probably do it by caching the original cancellationToken along with the linked token used for timeouts, and on cancellation checking the original token when calling `ShouldWrapInOperationCanceledException` rather than the linked token. Does that sound like a reasonable approach?

**Comment by wfurt** [comment]
In general yes. Based on my experience the cancelation is different depending if it happens during SSL handshake or before that.

**Comment by geoffkizer** [comment]
> Does that sound like a reasonable approach?

Yes.

**Comment by krwq** [comment]
This is failing fairly consistently on my win-10 box although the exception seems tiny bit different:

```
      Expected: typeof(System.Threading.Tasks.TaskCanceledException)
      Actual:   typeof(System.Net.Http.HttpRequestException): The SSL connection could not be established, see inner exception.
      ---- System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception.
      -------- System.OperationCanceledException : The operation was canceled.
      Stack Trace:
        F:\src\corefx3\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\ConnectHelper.cs(176,0): at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
        F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs(759,0): at System.Threading.Tasks.ValueTask`1.get_Result()
        F:\src\corefx3\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs(635,0): at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
        F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs(759,0): at System.Threading.Tasks.ValueTask`1.get_Result()
        F:\src\corefx3\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs(650,0): at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs(759,0): at System.Threading.Tasks.ValueTask`1.get_Result()
        F:\src\corefx3\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs(316,0): at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs(759,0): at System.Threading.Tasks.ValueTask`1.get_Result()
        F:\src\corefx3\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs(508,0): at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
        F:\src\corefx3\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\RedirectHandler.cs(33,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        ----- Inner Stack Trace -----
        F:\src\corefx3\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\ConnectHelper.cs(176,0): at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
        F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs(759,0): at System.Threading.Tasks.ValueTask`1.get_Result()
        F:\src\corefx3\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs(635,0): at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
        F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs(759,0): at System.Threading.Tasks.ValueTask`1.get_Result()
        F:\src\corefx3\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs(650,0): at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs(759,0): at System.Threading.Tasks.ValueTask`1.get_Result()
        F:\src\corefx3\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs(316,0): at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs(759,0): at System.Threading.Tasks.ValueTask`1.get_Result()
        F:\src\corefx3\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs(508,0): at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
        F:\src\corefx3\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\RedirectHandler.cs(33,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        ----- Inner Stack Trace -----
        F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\CancellationToken.cs(352,0): at System.Threading.CancellationToken.ThrowOperationCanceledException()
        F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\CancellationToken.cs(348,0): at System.Threading.CancellationToken.ThrowIfCancellationRequested()
        F:\src\corefx3\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs(1104,0): at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
        F:\src\corefx3\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs(1073,0): at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
        F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs(762,0): at System.Threading.Tasks.ValueTask`1.get_Result()
        F:\src\corefx3\src\System.Net.Security\src\System\Net\FixedSizeReader.cs(57,0): at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
        F:\src\corefx3\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs(82,0): at System.Net.Security.SslStream.ThrowIfExceptional()
        F:\src\corefx3\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs(472,0): at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
        F:\src\corefx3\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs(442,0): at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
        F:\src\corefx3\src\System.Net.Security\src\System\Net\Security\SslStream.cs(237,0): at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
        F:\src\corefx3\src\System.Net.Security\src\System\Net\Security\SslStream.cs(404,0): at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
        F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\FutureFactory.cs(513,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
        --- End of stack trace from previous location where exception was thrown ---
        F:\src\corefx3\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\ConnectHelper.cs(165,0): at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
```

**Comment by krwq** [comment]
Seems like https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs#L167-L177

should instead be something like:

```csharp
            catch (Exception e) when (!(e is TaskCanceledException))
            {
                if (cancellationToken.IsCancellationRequested)
                {
                    throw CancellationHelper.CreateOperationCanceledException(e, cancellationToken);
                }

                sslStream.Dispose();

                throw new HttpRequestException(SR.net_http_ssl_connection_failed, e);
            }
```

Currently it seems the exception is OperationCancelledException which is then wrapped above because it's not TaskCancelledException (only opposite being true) - alternatively we should throw TaskCancelledException directly. Also given https://github.com/dotnet/corefx/issues/20296 this requires more design before doing any fixes so un-assigning myself
