### ISSUE TITLE
ResponseHeadersRead_SynchronizationContextNotUsedByHandler test fails on UAP

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#30052]
https://github.com/dotnet/corefx/blob/2eb5d34e6d12c4a6897776a03c115bd6183b8a57/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Asynchrony.cs#L25

```
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Asynchrony_Test.ResponseHeadersRead_SynchronizationContextNotUsedByHandler(responseHead
  ersRead: False, contentMode: ContentLength) [FAIL]
        System.AggregateException : One or more errors occurred. (One or more errors occurred. (The handle is invalid. (Exception from HRESULT: 0x80070006 (E_H
  ANDLE)))) (One or more errors occurred. (Unable to read data from the transport connection: An established connection was aborted by the software in your hos
  t machine..))
        ---- System.AggregateException : One or more errors occurred. (The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE)))
        -------- System.IO.IOException : The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))
        ------------ System.Exception : The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))
        ---- System.AggregateException : One or more errors occurred. (Unable to read data from the transport connection: An established connection was aborted
   by the software in your host machine..)
        -------- System.IO.IOException : Unable to read data from the transport connection: An established connection was aborted by the software in your host
  machine..
        ------------ System.Net.Sockets.SocketException : An established connection was aborted by the software in your host machine.
        Stack Trace:
           s:\GitHub\corefx\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(92,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAn
  yFailed(Task[] tasks)
           s:\GitHub\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs(83,0): at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass11_0.<<CreateCl
  ientAndServerAsync>b__0>d.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
           s:\GitHub\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs(66,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsy
  nc, Options options)
           s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Asynchrony.cs(29,0): at System.Net.Http.Functional.Tests.HttpClient
  Handler_Asynchrony_Test.<>c__DisplayClass1_0.<<ResponseHeadersRead_SynchronizationContextNotUsedByHandler>b__0>d.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
           s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Asynchrony.cs(27,0): at System.Net.Http.Functional.Tests.HttpClient
  Handler_Asynchrony_Test.ResponseHeadersRead_SynchronizationContextNotUsedByHandler(Boolean responseHeadersRead, ContentMode contentMode)
           --- End of stack trace from previous location where exception was thrown ---
           ----- Inner Stack Trace #1 (System.AggregateException) -----

           ----- Inner Stack Trace -----
           s:\GitHub\corefx\src\System.Runtime.WindowsRuntime\src\System\IO\WinRtToNetFxStreamAdapter.cs(842,0): at System.IO.WinRtToNetFxStreamAdapter.ReadAsy
  ncInternal(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
              at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
              at System.IO.BufferedStream.CopyToAsyncCore(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
           s:\GitHub\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(154,0): at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
           s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Asynchrony.cs(49,0): at System.Net.Http.Functional.Tests.HttpClient
  Handler_Asynchrony_Test.<>c__DisplayClass1_1.<ResponseHeadersRead_SynchronizationContextNotUsedByHandler>b__3()
              at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
           --- End of stack trace from previous location where exception was thrown ---
           s:\GitHub\corefx\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(64,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAn
  yFailed(Task[] tasks)
           ----- Inner Stack Trace -----
              at Windows.Storage.Streams.IInputStream.ReadAsync(IBuffer buffer, UInt32 count, InputStreamOptions options)
           s:\GitHub\corefx\src\System.Runtime.WindowsRuntime\src\System\IO\WinRtToNetFxStreamAdapter.cs(819,0): at System.IO.WinRtToNetFxStreamAdapter.ReadAsy
  ncInternal(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
           ----- Inner Stack Trace #2 (System.AggregateException) -----

           ----- Inner Stack Trace -----
           s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\DribbleStream.cs(28,0): at System.Net.Http.Functional.Tests.DribbleStream.WriteAsync(Byte
  [] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
              at System.IO.StreamWriter.FlushAsyncInternal(StreamWriter _this, Boolean flushStream, Boolean flushEncoder, Char[] charBuffer, Int32 charPos, Boo
  lean haveWrittenPreamble, Encoding encoding, Encoder encoder, Byte[] byteBuffer, Stream stream, CancellationToken cancellationToken)
              at System.IO.StreamWriter.WriteAsyncInternal(StreamWriter _this, String value, Char[] charBuffer, Int32 charPos, Int32 charLen, Char[] coreNewLin
  e, Boolean autoFlush, Boolean appendNewLine)
           s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Asynchrony.cs(60,0): at System.Net.Http.Functional.Tests.HttpClient
  Handler_Asynchrony_Test.<>c__DisplayClass1_0.<<ResponseHeadersRead_SynchronizationContextNotUsedByHandler>b__4>d.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
           s:\GitHub\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs(116,0): at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 fu
  ncAsync)
           s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Asynchrony.cs(57,0): at System.Net.Http.Functional.Tests.HttpClient
  Handler_Asynchrony_Test.<>c__DisplayClass1_0.<<ResponseHeadersRead_SynchronizationContextNotUsedByHandler>b__2>d.MoveNext()
           ----- Inner Stack Trace -----
```

**Comment by davidsh** [comment]
Getting this error:

>------------ System.Exception : The handle is invalid.
(Exception from HRESULT: 0x80070006 (E_HANDLE))

is likely a bug in the WinRT Windows.Web.Http APIs.
