### ISSUE TITLE
Http tests using loopback server and TLS failing on UAP

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#30056]
These tests are failing on UAP:

https://github.com/dotnet/corefx/blob/7749ab1b3dce86b5f96743737c82c3103291931f/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ClientCertificates.cs#L208

https://github.com/dotnet/corefx/blob/7749ab1b3dce86b5f96743737c82c3103291931f/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ClientCertificates.cs#L288

https://github.com/dotnet/corefx/blob/7749ab1b3dce86b5f96743737c82c3103291931f/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs#L612

The error is similar:

>System.IO.IOException : Authentication failed because the remote party has closed the transport stream.

It seems that the client-side is closing the connection unexpectedly. It's possible that UAP needs different test ssl certificates.  Needs to be investigated.

=================
```
        System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
        Stack Trace:
           s:\GitHub\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs(874,0): at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
           s:\GitHub\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs(1094,0): at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
           --- End of stack trace from previous location where exception was thrown ---
           s:\GitHub\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs(96,0): at System.Net.Security.SslState.ThrowIfExceptional()
           s:\GitHub\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs(735,0): at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
           s:\GitHub\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs(705,0): at System.Net.Security.SslState.EndProcessAuthentication(IAsync Result result)
           s:\GitHub\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.cs(271,0): at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
           s:\GitHub\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.cs(421,0): at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__50_2(IAsyncResult iar)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
```

**Comment by davidsh** [comment]
This issue was specific to the UAP implementation of the networking stack which had a different implementation for things like HTTP and WebSockets.

As of PR #41759, we no longer build the separate implementation for the UAP platform. So, this issue can't occur anymore with .NET 5 because we now will be using the same .NET Core implementation as on Windows, Linux, Mac.
