### ISSUE TITLE
[UAP] RemoteInvoke throws MissingMethodException: Cannot create an abstract class

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#30054]
The Http test is failing when running on UAP:

https://github.com/dotnet/corefx/blob/2eb5d34e6d12c4a6897776a03c115bd6183b8a57/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ServerCertificates.cs#L397

It seems that the RemoteInvoke can't handle having a test method in an abstract class.  Many of the Http tests are in an abstract class and then there are explicit derived classes which cause different Http handlers (PlatformHandler vs. SocketsHttpHandler) to be used etc.

Error:

```
     System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(url: \"https://
  expired.badssl.com/\", expectedErrors: RemoteCertificateChainErrors) [FAIL]
        RemoteExecuter: System.Net.Http.Functional.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb <UseCallback_BadCertificate_Expecte
  dPolicyErrors>b__21_0 https://expired.badssl.com/, RemoteCertificateChainErrors, False
        System.MissingMethodException: Cannot create an abstract class.
           at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleIn
  ternal& ctor)
           at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
           at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
           at RunnerRemoteExecutionService.RemoteExecutor.HandleTheRequest(ValueSet message, ValueSet returnData)
        Returned Error code: -4
        Expected: True
        Actual:   False
        Stack Trace:
           s:\GitHub\corefx\src\CoreFx.Private.TestUtilities\src\System\Diagnostics\RemoteExecutorTestBase.uap.cs(70,0): at System.Diagnostics.RemoteExecutorTe
  stBase.RemoteInvoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments)
           s:\GitHub\corefx\src\CoreFx.Private.TestUtilities\src\System\Diagnostics\RemoteExecutorTestBase.cs(120,0): at System.Diagnostics.RemoteExecutorTestB
  ase.RemoteInvoke(Func`4 method, String arg1, String arg2, String arg3, RemoteInvokeOptions options)
           s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ServerCertificates.cs(413,0): at System.Net.Http.Functional.Tests.H
  ttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(String url, SslPolicyErrors expectedErrors)
           --- End of stack trace from previous location where exception was thrown ---
     System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(url: \"https://
  self-signed.badssl.com/\", expectedErrors: RemoteCertificateChainErrors) [FAIL]
        RemoteExecuter: System.Net.Http.Functional.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb <UseCallback_BadCertificate_Expecte
  dPolicyErrors>b__21_0 https://self-signed.badssl.com/, RemoteCertificateChainErrors, False
        System.MissingMethodException: Cannot create an abstract class.
           at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleIn
  ternal& ctor)
           at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
           at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
           at RunnerRemoteExecutionService.RemoteExecutor.HandleTheRequest(ValueSet message, ValueSet returnData)
        Returned Error code: -4
        Expected: True
        Actual:   False
        Stack Trace:
           s:\GitHub\corefx\src\CoreFx.Private.TestUtilities\src\System\Diagnostics\RemoteExecutorTestBase.uap.cs(70,0): at System.Diagnostics.RemoteExecutorTe
  stBase.RemoteInvoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments)
           s:\GitHub\corefx\src\CoreFx.Private.TestUtilities\src\System\Diagnostics\RemoteExecutorTestBase.cs(120,0): at System.Diagnostics.RemoteExecutorTestB
  ase.RemoteInvoke(Func`4 method, String arg1, String arg2, String arg3, RemoteInvokeOptions options)
           s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ServerCertificates.cs(413,0): at System.Net.Http.Functional.Tests.H
  ttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(String url, SslPolicyErrors expectedErrors)
           --- End of stack trace from previous location where exception was thrown ---
```

**Comment by davidsh** [comment]
cc: @safern

**Comment by davidsh** [comment]
This issue was specific to the UAP implementation of the networking stack which had a different implementation for things like HTTP and WebSockets.

As of PR #41759, we no longer build the separate implementation for the UAP platform. So, this issue can't occur anymore with .NET 5 because we now will be using the same .NET Core implementation as on Windows, Linux, Mac.
