### ISSUE TITLE
PostAsync_ThrowFromContentCopy_RequestFails fails on UAP

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#30061]
https://github.com/dotnet/corefx/blob/7749ab1b3dce86b5f96743737c82c3103291931f/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs#L2606

Error:

```
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandlerTest.PostAsync_ThrowFromContentCopy_RequestFails(syncFailure: False) [FAIL]
        Assert.Same() Failure
        Expected: System.FormatException: One of the identified items was in an invalid format.
           at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass100_3.<PostAsync_ThrowFromContentCopy_RequestFails>b__8(Task _) in s:\Git
  Hub\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 2630
           at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
           at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
        --- End of stack trace from previous location where exception was thrown ---
           at System.IO.StreamOperationsImplementation.<>c__DisplayClass1_0.<<ReadAsync_AbstractStream>b__0>d.MoveNext() in s:\GitHub\corefx\src\System.Runtime
  .WindowsRuntime\src\System\IO\StreamOperationsImplementation.cs:line 117
        Actual:   System.FormatException: One of the identified items was in an invalid format.
           at System.Net.Http.HttpHandlerToFilter.SendAsync(HttpRequestMessage request, CancellationToken cancel) in s:\GitHub\corefx\src\System.Net.Http\src\u
  ap\System\Net\HttpHandlerToFilter.cs:line 90
           at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in s:\GitHub\corefx\src\System.Net.H
  ttp\src\uap\System\Net\HttpClientHandler.cs:line 607
        Stack Trace:
           s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs(2635,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTe
  st.<>c__DisplayClass100_0.<<PostAsync_ThrowFromContentCopy_RequestFails>b__0>d.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
           s:\GitHub\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs(66,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsy
  nc, Options options)
           s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs(2614,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTe
  st.PostAsync_ThrowFromContentCopy_RequestFails(Boolean syncFailure)
           --- End of stack trace from previous location where exception was thrown ---
     System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandlerTest.PostAsync_ThrowFromContentCopy_RequestFails(syncFailure: True) [FAIL]
        Assert.Same() Failure
        Expected: System.FormatException: One of the identified items was in an invalid format.
           at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass100_3.<PostAsync_ThrowFromContentCopy_RequestFails>b__6(Byte[] buffer, In
  t32 offset, Int32 count, CancellationToken cancellationToken) in s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 263
  0
           at System.IO.DelegateStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in s:\GitHub\corefx\src\Common\
  tests\System\IO\DelegateStream.cs:line 76
           at System.Net.Http.DelegatingStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in s:\GitHub\corefx\src
  \Common\src\System\IO\DelegatingStream.cs:line 103
           at System.IO.StreamOperationsImplementation.<>c__DisplayClass1_0.<<ReadAsync_AbstractStream>b__0>d.MoveNext() in s:\GitHub\corefx\src\System.Runtime
  .WindowsRuntime\src\System\IO\StreamOperationsImplementation.cs:line 117
        Actual:   System.FormatException: One of the identified items was in an invalid format.
           at System.Net.Http.HttpHandlerToFilter.SendAsync(HttpRequestMessage request, CancellationToken cancel) in s:\GitHub\corefx\src\System.Net.Http\src\u
  ap\System\Net\HttpHandlerToFilter.cs:line 90
           at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in s:\GitHub\corefx\src\System.Net.Http\src\uap\System\Net\HttpClientHandler.cs:line 607
        Stack Trace:
           s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs(2635,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTe
  st.<>c__DisplayClass100_0.<<PostAsync_ThrowFromContentCopy_RequestFails>b__0>d.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
           s:\GitHub\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs(66,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsy
  nc, Options options)
           s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs(2614,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTe
  st.PostAsync_ThrowFromContentCopy_RequestFails(Boolean syncFailure)
           --- End of stack trace from previous location where exception was thrown ---
```

**Comment by davidsh** [comment]
This issue was specific to the UAP implementation of the networking stack which had a different implementation for things like HTTP and WebSockets.

As of PR #41759, we no longer build the separate implementation for the UAP platform. So, this issue can't occur anymore with .NET 5 because we now will be using the same .NET Core implementation as on Windows, Linux, Mac.
