### ISSUE TITLE
NegotiateStream Kerberos tests failing after async fix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#30150]
These tests were incorrectly ignoring an assert that was firing.  Now that these assert was fixed by https://github.com/dotnet/corefx/pull/30145, several tests are failing, e.g.
```
2018-06-05 14:30:51,094: INFO: proc(54): run_and_log_output: Output:    System.Net.Security.Tests.NegotiateStreamTest.NegotiateStream_StreamToStream_KerberosAuthInvalidUser_Failure [FAIL]
2018-06-05 14:30:51,095: INFO: proc(54): run_and_log_output: Output:       Assert.Throws() Failure
2018-06-05 14:30:51,095: INFO: proc(54): run_and_log_output: Output:       Expected: typeof(System.Security.Authentication.AuthenticationException)
2018-06-05 14:30:51,095: INFO: proc(54): run_and_log_output: Output:       Actual:   typeof(System.TimeoutException): VirtualNetwork: Timeout reading the next frame.
2018-06-05 14:30:51,105: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-06-05 14:30:51,177: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs(55,0): at System.Net.Test.Common.VirtualNetwork.ReadFrame(Boolean server, Byte[]& buffer)
2018-06-05 14:30:51,177: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs(118,0): at System.Net.Test.Common.VirtualNetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
2018-06-05 14:30:51,178: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/tests/FunctionalTests/UnixGssFakeStreamFramer.cs(69,0): at System.Net.Security.Tests.UnixGssFakeStreamFramer.ReadHandshakeFrame()
2018-06-05 14:30:51,179: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/tests/FunctionalTests/UnixGssFakeNegotiateStream.cs(53,0): at System.Net.Security.Tests.UnixGssFakeNegotiateStream.ServerLoop(Object state)
2018-06-05 14:30:51,179: INFO: proc(54): run_and_log_output: Output:          /root/coreclr/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs(166,0): at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2018-06-05 14:30:51,179: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2018-06-05 14:30:51,180: INFO: proc(54): run_and_log_output: Output:          /root/coreclr/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2439,0): at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2018-06-05 14:30:51,180: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2018-06-05 14:31:42,556: INFO: proc(54): run_and_log_output: Output:    System.Net.Security.Tests.NegotiateStreamTest.NegotiateStream_StreamToStream_KerberosAuthDefaultCredentialsNoSeed_Failure [FAIL]
2018-06-05 14:31:42,556: INFO: proc(54): run_and_log_output: Output:       Assert.Throws() Failure
2018-06-05 14:31:42,557: INFO: proc(54): run_and_log_output: Output:       Expected: typeof(System.Security.Authentication.AuthenticationException)
2018-06-05 14:31:42,557: INFO: proc(54): run_and_log_output: Output:       Actual:   typeof(System.IO.IOException): Unable to read data from the transport connection: VirtualNetwork: Timeout reading the next frame..
2018-06-05 14:31:42,557: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-06-05 14:31:42,558: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/src/System/Net/StreamFramer.cs(308,0): at System.Net.StreamFramer.EndReadMessage(IAsyncResult asyncResult)
2018-06-05 14:31:42,558: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/src/System/Net/Security/NegoState.cs(755,0): at System.Net.Security.NegoState.ReadCallback(IAsyncResult transportResult)
2018-06-05 14:31:42,559: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2018-06-05 14:31:42,559: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/src/System/Net/Security/NegoState.cs(402,0): at System.Net.Security.NegoState.EndProcessAuthentication(IAsyncResult result)
2018-06-05 14:31:42,560: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/src/System/Net/Security/NegotiateStream.cs(116,0): at System.Net.Security.NegotiateStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
2018-06-05 14:31:42,560: INFO: proc(54): run_and_log_output: Output:          /root/coreclr/src/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs(533,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
2018-06-05 14:31:42,561: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2018-06-05 14:32:42,629: INFO: proc(54): run_and_log_output: Output:    System.Net.Security.Tests.NegotiateStreamTest.NegotiateStream_StreamToStream_KerberosAuthInvalidPassword_Failure [FAIL]
2018-06-05 14:32:42,629: INFO: proc(54): run_and_log_output: Output:       Assert.Throws() Failure
2018-06-05 14:32:42,629: INFO: proc(54): run_and_log_output: Output:       Expected: typeof(System.Security.Authentication.AuthenticationException)
2018-06-05 14:32:42,630: INFO: proc(54): run_and_log_output: Output:       Actual:   typeof(System.TimeoutException): VirtualNetwork: Timeout reading the next frame.
2018-06-05 14:32:42,630: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-06-05 14:32:42,630: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs(55,0): at System.Net.Test.Common.VirtualNetwork.ReadFrame(Boolean server, Byte[]& buffer)
2018-06-05 14:32:42,632: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs(118,0): at System.Net.Test.Common.VirtualNetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
2018-06-05 14:32:42,633: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/tests/FunctionalTests/UnixGssFakeStreamFramer.cs(69,0): at System.Net.Security.Tests.UnixGssFakeStreamFramer.ReadHandshakeFrame()
2018-06-05 14:32:42,633: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/tests/FunctionalTests/UnixGssFakeNegotiateStream.cs(53,0): at System.Net.Security.Tests.UnixGssFakeNegotiateStream.ServerLoop(Object state)
2018-06-05 14:32:42,634: INFO: proc(54): run_and_log_output: Output:          /root/coreclr/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs(166,0): at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2018-06-05 14:32:42,634: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2018-06-05 14:32:42,634: INFO: proc(54): run_and_log_output: Output:          /root/coreclr/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2439,0): at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2018-06-05 14:32:42,635: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
```

**Comment by karelz** [comment]
Part of larger effort to test Kerberos via containers in CI.
