### ISSUE TITLE
SUSE dotnet 2.0.3 Description: Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: ArgumentNull_Generic

### ISSUE THREAD

**Issue by iga1976** [dotnet/corefx#30208]
Same issue with SLES 12.2 x86_64. I am attaching the out file with the exception.
If i get right from this issue thread, they say it is fixed in dotnet sdk 2.0.3 (?!) That is why I try to set the project target framework to 2.0.3 but when i run "dotnet clean" in the project dir i get error as follows:
dotnet clean
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/2.0.3/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK does not support targeting .NET Core 2.0.3.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.0.3. [/home/tony/sandbox/tsm/tdp/agents/sqlonlinux/mssqlsmoapp/mssqlsmoapp.csproj]
Please clarify and let know if it is fixed or not, and, in any case, what to do.
I am attaching the files with details. THANKS
[github_dotnet_clean.txt](https://github.com/dotnet/corefx/files/2083843/github_dotnet_clean.txt)
[github_exception.txt](https://github.com/dotnet/corefx/files/2083844/github_exception.txt)

**Comment by iga1976** [comment]
anyway how do you target app for 2.0.3 since dotnet new accepts only 2.0
This is from https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new?tabs=netcore20

classlib

-f|--framework - Specifies the framework to target.
Values:
netcoreapp2.0 to create a .NET Core Class Library or
netstandard2.0 to create a .NET Standard Class Library. The default value is netstandard2.0.

**Comment by iga1976** [comment]
i post same comments on the closed ticket since it looks the same trouble.
https://github.com/dotnet/corefx/issues/24832

**Comment by danmosemsft** [comment]
@tarekgh can you help @iga1976 get updated (either to 2.0.x or 2.1 even)

**Comment by tarekgh** [comment]
@steveharter @joperezr would be the best to help here as they are familiar with this issue according to #24832

**Comment by tarekgh** [comment]
CC @kouvel too as I guess he ran into similar issues before.

**Comment by danmosemsft** [comment]
Another: https://github.com/dotnet/corefx/issues/30593

**Comment by tarekgh** [comment]
@danmosemsft this is not related to #30593

**Comment by tarekgh** [comment]
https://github.com/dotnet/coreclr/issues/12668

**Comment by tarekgh** [comment]
@kouvel @jeffschwMSFT @tommcdon 

could you please help with this issue? this is the issue that @kouvel fixed dotnet/coreclr#12668 for 2.0.3 but people running into it. Although they have installed dotnet 2.0.3, but it hey may not targeting this version which has the fix. would be nice if you can help narrow down the problem. 

```
   at System.SR.InternalGetResourceString(String key)
   at System.SR.GetResourceString(String resourceKey, String defaultString)
   at System.ArgumentNullException..ctor(String paramName)
   at System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(Assembly assembly)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at System.SR.InternalGetResourceString(String key)
```

**Comment by kouvel** [comment]
@iga1976, could you please try changing the `PropertyGroup` section in the `.csproj` file to the following:

```xml
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.9</RuntimeFrameworkVersion>
    <AssemblyName>mssqlsmoapp</AssemblyName>
  </PropertyGroup>
```

Then rebuild and/or republish the app, and try again.

In some cases for the 2.0.* frameworks, dotnet defaults to using 2.0.0 instead of higher versions even if a higher version is installed. Setting `RuntimeFrameworkVersion` overrides that. `TargetFramework` should be `netcoreapp2.0`, that indicates that it's targeting 2.0.*.
