### ISSUE TITLE
"The server returned an invalid or unrecognized response" on BasicHttpBinding with authentication using SocketsHttpHanlder 

### ISSUE THREAD

**Issue by gl2483** [dotnet/corefx#30214]
We just updated our application to Net Core 2.1 and one of the web service calls we are using starts failing 

The binding used is BasicHttpBinding
```C#
                var binding = new BasicHttpBinding();
                binding.Security.Mode = BasicHttpSecurityMode.Transport;
                binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;

                client.ClientCredentials.UserName.UserName = "someusername";
                client.ClientCredentials.UserName.Password = "somepassword";
                client.Endpoint.Binding =  binding;
```

But when I disable SocketsHttpHandler, it is working fine
```C#
AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
```

```
--------- Stack Trace -------------
{System.Net.Http.HttpRequestException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.ThrowInvalidHttpResponse()
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.SendRequestAsync(Message message, TimeoutHelper timeoutHelper)}
```

**Comment by karelz** [comment]
@gl2483 can you please share a repro we can run locally to reproduce the problem?

**Comment by davidsh** [comment]
Does this scenario use a proxy?

Can you also share Wireshark traces?  That would help us to see what network requests/responses are being used.

**Comment by karelz** [comment]
Not actionable without additional details. Feel free to reopen once there is a repro a traces to help us investigate. Thanks!
