### ISSUE TITLE
EndPrint_SetValue_ReturnsExpected  and PrintPage_SetValue_ReturnsExpected throws excpetion

### ISSUE THREAD

**Issue by Anipik** [dotnet/corefx#30223]
Unhandled Exception of Type System.ComponentModel.Win32Exception
Error in remote procedure call

```
   at System.Drawing.Printing.PrinterSettings.GetHdevmodeInternal(String printer) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Drawing.Common\src\System\Drawing\Printing\PrinterSettings.Windows.cs:line 896
   at System.Drawing.Printing.PageSettings.get_ExtraBytes() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Drawing.Common\src\System\Drawing\Printing\PageSettings.Windows.cs:line 384
   at System.Drawing.Printing.PageSettings.CopyToHdevmode(IntPtr hdevmode) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Drawing.Common\src\System\Drawing\Printing\PageSettings.Windows.cs:line 368
   at System.Drawing.Printing.PrintController.OnStartPrint(PrintDocument document, PrintEventArgs e) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Drawing.Common\src\System\Drawing\Printing\PrintController.Windows.cs:line 276
   at System.Drawing.Printing.Tests.PrintDocumentTests.TestPrintController.OnStartPrint(PrintDocument document, PrintEventArgs e) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Drawing.Common\tests\Printing\PrintDocumentTests.cs:line 274
   at System.Drawing.Printing.PrintController.Print(PrintDocument document) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Drawing.Common\src\System\Drawing\Printing\PrintController.Windows.cs:line 117
   at System.Drawing.Printing.Tests.PrintDocumentTests.EndPrint_SetValue_ReturnsExpected() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Drawing.Common\tests\Printing\PrintDocumentTests.cs:line 182
```

Link https://mc.dot.net/#/user/Anipik/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/928be92417ee8f200df812e3dfc002abcf80f787/workItem/System.Drawing.Common.Tests/analysis/xunit/System.Drawing.Printing.Tests.PrintDocumentTests~2FEndPrint_SetValue_ReturnsExpected

cc @danmosemsft @safern @JeremyKuhne

**Comment by ViktorHofer** [comment]
Just happened again: https://dev.azure.com/dnceng/public/_build/results?buildId=174978&view=ms.vss-test-web.build-test-results-tab

**Comment by ViktorHofer** [comment]
Happened again: https://dev.azure.com/dnceng/public/_build/results?buildId=180234&view=ms.vss-test-web.build-test-results-tab&runId=4352094&resultId=150061&paneView=debug

```
System.NullReferenceException : Object reference not set to an instance of an object.

 at System.Drawing.Printing.PageSettings.get_ExtraBytes() in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PageSettings.Windows.cs:line 388
   at System.Drawing.Printing.PageSettings.CopyToHdevmode(IntPtr hdevmode) in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PageSettings.Windows.cs:line 368
   at System.Drawing.Printing.PrintController.OnStartPrint(PrintDocument document, PrintEventArgs e) in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PrintController.Windows.cs:line 275
   at System.Drawing.Printing.Tests.PrintDocumentTests.TestPrintController.OnStartPrint(PrintDocument document, PrintEventArgs e) in D:\a\1\s\src\System.Drawing.Common\tests\Printing\PrintDocumentTests.cs:line 275
   at System.Drawing.Printing.PrintController.Print(PrintDocument document) in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PrintController.Windows.cs:line 116
   at System.Drawing.Printing.Tests.PrintDocumentTests.PrintPage_SetValue_ReturnsExpected() in D:\a\1\s\src\System.Drawing.Common\tests\Printing\PrintDocumentTests.cs:line 204
```

**Comment by danmosemsft** [comment]
We should disable this test. Low importance scenario

**Comment by ViktorHofer** [comment]
Don't you think we should at least fix the NRE and throw the most appropriate exception?

**Comment by danmosemsft** [comment]
Sure if there's  an obvious quick fix.

**Comment by ViktorHofer** [comment]
Just happened again: https://dev.azure.com/dnceng/public/_build/results?buildId=225212&view=ms.vss-test-web.build-test-results-tab&runId=5561424&resultId=189187&paneView=debug

**Comment by stephentoub** [comment]
That link doesn't appear to work, unfortunately:
![image](https://user-images.githubusercontent.com/2642209/59516437-5344dc00-8e8f-11e9-90b8-5a60b1d70be2.png)

**Comment by ViktorHofer** [comment]
Grrr. Queuing a new build by pushing a commit (without the force flag) seems to delete the old one

**Comment by ViktorHofer** [comment]
Happened again, disabling the test... https://dev.azure.com/dnceng/public/_build/results?buildId=332783&view=ms.vss-test-web.build-test-results-tab&runId=9763156&resultId=124221&paneView=debug

System.Drawing.Printing.Tests.PrintDocumentTests.PrintPage_SetValue_ReturnsExpected

netcoreapp-Windows_NT-Release-x86-Windows.10.Amd64.ClientRS4.Open

```
System.ComponentModel.Win32Exception : The remote procedure call failed.

 at System.Drawing.Printing.PrinterSettings.GetHdevmodeInternal(String printer) in /_/src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.Windows.cs:line 896
   at System.Drawing.Printing.PrinterSettings.GetHdevmodeInternal() in /_/src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.Windows.cs:line 872
   at System.Drawing.Printing.PageSettings.get_ExtraBytes() in /_/src/System.Drawing.Common/src/System/Drawing/Printing/PageSettings.Windows.cs:line 384
   at System.Drawing.Printing.PageSettings.CopyToHdevmode(IntPtr hdevmode) in /_/src/System.Drawing.Common/src/System/Drawing/Printing/PageSettings.Windows.cs:line 368
   at System.Drawing.Printing.PrinterSettings.GetHdevmode(PageSettings pageSettings) in /_/src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.Windows.cs:line 955
   at System.Drawing.Printing.PrintController.OnStartPrint(PrintDocument document, PrintEventArgs e) in /_/src/System.Drawing.Common/src/System/Drawing/Printing/PrintController.Windows.cs:line 275
   at System.Drawing.Printing.Tests.PrintDocumentTests.TestPrintController.OnStartPrint(PrintDocument document, PrintEventArgs e) in /_/src/System.Drawing.Common/tests/Printing/PrintDocumentTests.cs:line 277
   at System.Drawing.Printing.PrintController.Print(PrintDocument document) in /_/src/System.Drawing.Common/src/System/Drawing/Printing/PrintController.Windows.cs:line 116
   at System.Drawing.Printing.PrintDocument.Print() in /_/src/System.Drawing.Common/src/System/Drawing/Printing/PrintDocument.Windows.cs:line 270
   at System.Drawing.Printing.Tests.PrintDocumentTests.PrintPage_SetValue_ReturnsExpected() in /_/src/System.Drawing.Common/tests/Printing/PrintDocumentTests.cs:line 211
```
