### ISSUE TITLE
Test failure on macOS System.Drawing.Tests.Graphics_DrawBezierTests~2FDrawBezier_PointFs

### ISSUE THREAD

**Issue by ghost** [dotnet/corefx#30230]
https://mc.dot.net/#/user/kasper3/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/509af4b53826277ba34322022679af3daee060b4/workItem/System.Drawing.Common.Tests/analysis/xunit/System.Drawing.Tests.Graphics_DrawBezierTests~2FDrawBezier_PointFs

Unhandled Exception of Type `Xunit.Sdk.EqualException`
Message :

```
Assert.Equal() Failure
Expected: Byte[] [157, 36, 159, 145, 163, ...]
Actual:   Byte[] [122, 255, 234, 158, 115, ...]
```

Stack Trace :

```
   at System.Drawing.Tests.DrawingTest.ValidateImageContent(Image image, Byte[] expectedHash) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Drawing.Common/tests/DrawingTest.cs:line 21
   at System.Drawing.Tests.Graphics_DrawBezierTests.DrawBezier_PointFs() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Drawing.Common/tests/Graphics_DrawBezierTests.cs:line 60
```

@hughbe fyi

**Comment by wfurt** [comment]
we have not seen this one for very long time. closing for now.
