### ISSUE TITLE
Several DrawLineTests failing on SLES in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#30321]
https://mc.dot.net/#/user/wfurt/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/bef2242a3551558bbd513bd80acb5ab960156b20/workItem/System.Drawing.Common.Tests/wilogs
```
2018-06-12 04:59:09,078: INFO: proc(54): run_and_log_output: Output:    System.Drawing.Tests.Graphics_DrawLineTests.DrawLines_PointFs [FAIL]
2018-06-12 04:59:09,080: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-06-12 04:59:09,081: INFO: proc(54): run_and_log_output: Output:       Expected: Byte[] [85, 64, 216, 170, 199, ...]
2018-06-12 04:59:09,081: INFO: proc(54): run_and_log_output: Output:       Actual:   Byte[] [142, 194, 251, 180, 222, ...]
2018-06-12 04:59:09,087: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-06-12 04:59:09,090: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Drawing.Common/tests/DrawingTest.cs(21,0): at System.Drawing.Tests.DrawingTest.ValidateImageContent(Image image, Byte[] expectedHash)
2018-06-12 04:59:09,091: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Drawing.Common/tests/Graphics_DrawLineTests.cs(33,0): at System.Drawing.Tests.Graphics_DrawLineTests.DrawLines_PointFs()
2018-06-12 04:59:09,093: INFO: proc(54): run_and_log_output: Output:    System.Drawing.Tests.Graphics_DrawLineTests.DrawLines_Points [FAIL]
2018-06-12 04:59:09,093: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-06-12 04:59:09,093: INFO: proc(54): run_and_log_output: Output:       Expected: Byte[] [85, 64, 216, 170, 199, ...]
2018-06-12 04:59:09,093: INFO: proc(54): run_and_log_output: Output:       Actual:   Byte[] [142, 194, 251, 180, 222, ...]
2018-06-12 04:59:09,093: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-06-12 04:59:09,094: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Drawing.Common/tests/DrawingTest.cs(21,0): at System.Drawing.Tests.DrawingTest.ValidateImageContent(Image image, Byte[] expectedHash)
2018-06-12 04:59:09,094: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Drawing.Common/tests/Graphics_DrawLineTests.cs(18,0): at System.Drawing.Tests.Graphics_DrawLineTests.DrawLines_Points()
```
cc: @safern

**Comment by wfurt** [comment]
this seems like very old failure. We did not see it recently. Closing for now.
