### ISSUE TITLE
Drawing tests failing on Nano in CI loading gdiplus.dll

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#30320]
https://mc.dot.net/#/user/wfurt/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/bef2242a3551558bbd513bd80acb5ab960156b20/workItem/System.Drawing.Common.Performance.Tests/wilogs
```
2018-06-12 05:30:56,036: INFO: proc(54): run_and_log_output: Output: Discovering: System.Drawing.Common.Performance.Tests
2018-06-12 05:30:56,154: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Drawing.Common.Performance.Tests
2018-06-12 05:30:56,193: INFO: proc(54): run_and_log_output: Output: Starting:    System.Drawing.Common.Performance.Tests
2018-06-12 05:30:56,479: INFO: proc(54): run_and_log_output: Output:    System.Drawing.Tests.Perf_Graphics_Transforms.TransformPoints [FAIL]
2018-06-12 05:30:56,480: INFO: proc(54): run_and_log_output: Output:       System.TypeInitializationException : The type initializer for 'Gdip' threw an exception.
2018-06-12 05:30:56,482: INFO: proc(54): run_and_log_output: Output:       ---- System.DllNotFoundException : Unable to load DLL 'gdiplus.dll': The specified module could not be found.
2018-06-12 05:30:56,486: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-06-12 05:30:56,555: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\System.Drawing.Common\src\System\Drawing\GdiplusNative.cs(1644,0): at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, Int32 format, HandleRef scan0, IntPtr& bitmap)
2018-06-12 05:30:56,555: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\System.Drawing.Common\src\System\Drawing\Bitmap.cs(81,0): at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
2018-06-12 05:30:56,555: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\System.Drawing.Common\src\System\Drawing\Bitmap.cs(51,0): at System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
2018-06-12 05:30:56,555: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\System.Drawing.Common\tests\Performance\Perf_Graphics_Transforms.cs(22,0): at System.Drawing.Tests.Perf_Graphics_Transforms.TransformPoints()
2018-06-12 05:30:56,555: INFO: proc(54): run_and_log_output: Output:          ----- Inner Stack Trace -----
2018-06-12 05:30:56,555: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\Common\src\System\Runtime\InteropServices\FunctionWrapper.cs(39,0): at System.Runtime.InteropServices.FunctionWrapper`1.get_Delegate()
2018-06-12 05:30:56,556: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\System.Drawing.Common\src\System\Drawing\GdiplusNative.Windows.cs(273,0): at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
2018-06-12 05:30:56,556: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\System.Drawing.Common\src\System\Drawing\Gdiplus.cs(87,0): at System.Drawing.SafeNativeMethods.Gdip..cctor()
2018-06-12 05:30:56,565: INFO: proc(54): run_and_log_output: Output:    System.Drawing.Tests.Perf_Graphics_DrawBeziers.DrawBezier_Points [FAIL]
2018-06-12 05:30:56,565: INFO: proc(54): run_and_log_output: Output:       System.TypeInitializationException : The type initializer for 'Gdip' threw an exception.
2018-06-12 05:30:56,565: INFO: proc(54): run_and_log_output: Output:       ---- System.DllNotFoundException : Unable to load DLL 'gdiplus.dll': The specified module could not be found.
2018-06-12 05:30:56,565: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-06-12 05:30:56,565: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\System.Drawing.Common\src\System\Drawing\GdiplusNative.cs(1644,0): at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, Int32 format, HandleRef scan0, IntPtr& bitmap)
2018-06-12 05:30:56,565: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\System.Drawing.Common\src\System\Drawing\Bitmap.cs(81,0): at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
2018-06-12 05:30:56,565: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\System.Drawing.Common\src\System\Drawing\Bitmap.cs(51,0): at System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
2018-06-12 05:30:56,566: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\System.Drawing.Common\tests\Performance\Perf_Graphics_DrawBeziers.cs(43,0): at System.Drawing.Tests.Perf_Graphics_DrawBeziers.DrawBezier_Points()
2018-06-12 05:30:56,566: INFO: proc(54): run_and_log_output: Output:          ----- Inner Stack Trace -----
2018-06-12 05:30:56,566: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\Common\src\System\Runtime\InteropServices\FunctionWrapper.cs(39,0): at System.Runtime.InteropServices.FunctionWrapper`1.get_Delegate()
2018-06-12 05:30:56,566: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\System.Drawing.Common\src\System\Drawing\GdiplusNative.Windows.cs(273,0): at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
2018-06-12 05:30:56,566: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\System.Drawing.Common\src\System\Drawing\Gdiplus.cs(87,0): at System.Drawing.SafeNativeMethods.Gdip..cctor()
2018-06-12 05:30:56,568: INFO: proc(54): run_and_log_output: Output:    System.Drawing.Tests.Perf_Graphics_DrawBeziers.DrawBezier_Point [FAIL]
2018-06-12 05:30:56,568: INFO: proc(54): run_and_log_output: Output:       System.TypeInitializationException : The type initializer for 'Gdip' threw an exception.
2018-06-12 05:30:56,568: INFO: proc(54): run_and_log_output: Output:       ---- System.DllNotFoundException : Unable to load DLL 'gdiplus.dll': The specified module could not be found.
2018-06-12 05:30:56,568: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-06-12 05:30:56,568: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\System.Drawing.Common\src\System\Drawing\GdiplusNative.cs(1644,0): at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, Int32 format, HandleRef scan0, IntPtr& bitmap)
2018-06-12 05:30:56,569: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\System.Drawing.Common\src\System\Drawing\Bitmap.cs(81,0): at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
2018-06-12 05:30:56,569: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\System.Drawing.Common\src\System\Drawing\Bitmap.cs(51,0): at System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
2018-06-12 05:30:56,569: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\System.Drawing.Common\tests\Performance\Perf_Graphics_DrawBeziers.cs(17,0): at System.Drawing.Tests.Perf_Graphics_DrawBeziers.DrawBezier_Point()
2018-06-12 05:30:56,569: INFO: proc(54): run_and_log_output: Output:          ----- Inner Stack Trace -----
2018-06-12 05:30:56,569: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\Common\src\System\Runtime\InteropServices\FunctionWrapper.cs(39,0): at System.Runtime.InteropServices.FunctionWrapper`1.get_Delegate()
2018-06-12 05:30:56,569: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\System.Drawing.Common\src\System\Drawing\GdiplusNative.Windows.cs(273,0): at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
2018-06-12 05:30:56,569: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---db113413\src\System.Drawing.Common\src\System\Drawing\Gdiplus.cs(87,0): at System.Drawing.SafeNativeMethods.Gdip..cctor()
```
cc: @safern

**Comment by stephentoub** [comment]
cc: @JeremyKuhne

**Comment by JeremyKuhne** [comment]
@danmosemsft You've done a lot with nano tests- do you know if we can attribute perf tests to not run on nano?

**Comment by davidsh** [comment]
See examples here (both using 'if' and attributes):

https://github.com/dotnet/corefx/blob/9bdc5f52fad134d12cb64d116d671aa145871288/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Authentication.cs#L39-L43

https://github.com/dotnet/corefx/blob/4012621d77ded2a61f3164ad2e995be5dfb9d342/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs#L3257

**Comment by danmosemsft** [comment]
For some reason I thought ConditionalFact etc were not respected by xunit.performance - although I can't find the issue right now. So you have to use "if". 

@ViktorHofer @adamsitnik do you happen to have context, and whether our usual test conditional test attributes (and active issue attributes) will be respected after moving to benchview.net? I am not sure how the components fit together.

**Comment by adamsitnik** [comment]
> I am not sure how the components fit together.

@danmosemsft  We are going to make it work, thanks for pointing this out. I will add it to my requirements list.

Most probably it will be a combination of categories and filters. Sth like:

```cs
[Benchmark]
[BenchmarkCategory("DontRunOnNano")]
public void SomeBenchmark() { } 

public class NanoFilter : IFilter
{
    public bool Predicate(Benchmark benchmark)
        => !(benchmark.Target.HasCategory("DontRunOnNano") && OS.IsNano);
}
```

**Comment by danmosemsft** [comment]
@adamsitnik here are some of our needs for declarative behaviors
* skip based on arbitrary condition in code (ConditionalXXX),  possibly platform/runtime/arch specific
* skip based on active issue, with message, possibly platform/runtime/arch specific
* we also have SkipOnTargetFramework as sugar over the above.

These we created as extensions over XUnit, using its namespace
https://github.com/dotnet/buildtools/tree/master/src/xunit.netcore.extensions/Attributes
You could have similar ones possibly with the same names but in your namespace. That would make it easier for folks to transition between working on XUnit functional tests, and our Perf tests. This could perhaps be defined in an extension to Benchmark.NET if they are not generally useful - just as we did for XUnit.

**Comment by safern** [comment]
Fixed on: https://github.com/dotnet/corefx/pull/30329/files in the meantime using and if statement at the beginning of the tests.
