### ISSUE TITLE
TestProcessStartTime test is failing on OS X

### ISSUE THREAD

**Issue by sokket** [dotnet/corefx#3037]
The TestProcessStartTime test in System.Diagnostic.Process.ProcessTests class is failing with the following error:

 System.Diagnostics.ProcessTests.ProcessTests.TestProcessStartTime [FAIL]
      Assert+WrapperXunitException : File path: Y:\Repositories\personal\dotnet\corefx\src\System.Diagnostics.Process\tests\ProcessTests.cs. Line: 387
      ---- Assert.InRange() Failure
      Range:  (635766571991261530 - 635766571991772530)
      Actual: 635766571650984930
      Stack Trace:
            at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
            at Assert.InRange[T](T actual, T low, T high, String path, Int32 line)
            at System.Diagnostics.ProcessTests.ProcessTests.TestProcessStartTime()
         ----- Inner Stack Trace -----
            at Assert.InRange[T](T actual, T low, T high, String path, Int32 line)

**Comment by stephentoub** [comment]
cc: @Priya91

**Comment by Priya91** [comment]
fixed by #5752
