### ISSUE TITLE
System.Buffers.dll has an incorrect format

### ISSUE THREAD

**Issue by iyhammad** [dotnet/corefx#30422]
I'm creating Windows Workflow Foundation Nuget Library. When I build the project I got the below **warning**.
```Could not compile workflow expressions because file 'file:///C:\Users\iyhammad\.nuget\packages\system.buffers\4.5.0\ref\net45\System.Buffers.dll' has an incorrect format. Workflows in this project may still run, if they do not require expression compilation. If the file is a platform-specific library or executable, consider building the project using MSBuild.exe from a command prompt of the targeted platform.```
If I ignore this warning and use the Nuget library in a Windows Workflow Foundation Service application, I can't open the Workflow designer once I use any component from the library. I always get the below exception in design time.
```
System.Xaml.XamlObjectWriterException: 'The invocation of the constructor on type 'KanooIT.Bpm.WorkflowLibrary.InitiateHumanWorkflow' that matches the specified binding constraints threw an exception.' Line number '116' and line position '32'. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Buffers, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at XamlStaticHelperNamespace._XamlStaticHelper.Load(String assemblyNameVal)
   at XamlStaticHelperNamespace._XamlStaticHelper.LoadAssemblies()
   at XamlStaticHelperNamespace._XamlStaticHelper.get_AssemblyList()
   at XamlStaticHelperNamespace._XamlStaticHelper.get_SchemaContext()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Activities.XamlIntegration.ActivityXamlServices.GetXamlSchemaContext(Assembly assembly, String helperClassName)
   at System.Activities.XamlIntegration.ActivityXamlServices.InitializeComponent(Type componentType, Object componentInstance)
   at KanooIT.Bpm.WorkflowLibrary.InitiateHumanWorkflow.BeforeInitializeComponent(Boolean& isInitialized)
   at KanooIT.Bpm.WorkflowLibrary.InitiateHumanWorkflow.InitializeComponent()
   at KanooIT.Bpm.WorkflowLibrary.InitiateHumanWorkflow..ctor()
   --- End of inner exception stack trace ---
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
   at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Activities.Presentation.Xaml.ErrorTolerantObjectWriter.XamlFragment.WriteTo(XamlWriter writer, Boolean parentHasError)
   at System.Activities.Presentation.Xaml.ErrorTolerantObjectWriter.ActivityFragment.WriteTo(XamlWriter writer, Boolean parentHasError)
   at System.Activities.Presentation.Xaml.ErrorTolerantObjectWriter.XamlFragment.WriteTo(XamlWriter writer, Boolean parentHasError)
   at System.Activities.Presentation.Xaml.ErrorTolerantObjectWriter.ActivityFragment.WriteTo(XamlWriter writer, Boolean parentHasError)
   at System.Activities.Presentation.Xaml.ErrorTolerantObjectWriter.XamlFragment.WriteTo(XamlWriter writer, Boolean parentHasError)
   at System.Activities.Presentation.Xaml.ErrorTolerantObjectWriter.CompleteLoad()
   at System.Activities.Presentation.Xaml.ErrorTolerantObjectWriter.WriteEndObject()
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at Microsoft.Activities.Presentation.Xaml.WorkflowDesignerXamlHelper.DeserializeString(String text, DeserializationMode mode, IList`1& loadErrors, Dictionary`2& sourceLocations)
   at Microsoft.Activities.Presentation.Xaml.WorkflowDesignerXamlHelper.DeserializeString(String text, IList`1& loadErrors, Dictionary`2& sourceLocations)
   at System.Activities.Presentation.WorkflowDesigner.Load()
```
After build, I found the file System.Buffers.dll with file version 4.6.26515.6 in bin of the NuGet package and the application as well.
I've added the below auto generated binding redirect in the web.config of the Workflow Service Application
```
<dependentAssembly>
	<assemblyIdentity name="System.Buffers" publicKeyToken="CC7B13FFCD2DDD51" culture="neutral"/>
	<bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0"/>
</dependentAssembly>
```
**More information:**
The NuGet Package and the solution is build against 4.7.2
Windows 10 Build: 17134.112
Visual Studio 2017. 15.7.3
.NET SDK: 2.1.300

**Comment by iyhammad** [comment]
This is a minimal repo that showcase the warning
https://github.com/iyhammad/WorkflowSample

**Comment by karelz** [comment]
How do I create it from scratch in VS? Are there easy steps to follow?

**Comment by iyhammad** [comment]
This workaround resolved the issue 
https://github.com/dotnet/sdk/issues/1522#issuecomment-324141767
I will keep this issue updated with my test results.

**Comment by joshfree** [comment]
@joperezr @ericstj could you comment on this issue given your involvement in the related linked issues?

**Comment by ericstj** [comment]
The workflow compiler attempts to load assembly references for execution (in the desktop msbuild process on whatever framework installed on the build machine).  It will fail whenever it sees a reference assembly.  We modified some of our packages to avoid using reference assemblies for desktop and instead let users compile against the implementation, but System.Buffers doesn't have such a change.  FWIW System.Buffers doesn't build in 3.0 so if you want to change it you'd need to make a fix in servicing.

**Comment by danmosemsft** [comment]
Servicing-consider means it's ready for shiproom. We'd need a template filled out.

**Comment by joperezr** [comment]
That is weird, I wonder how we missed this one if the target that made sure we cover all cases is also in release/2.1 branch where this package is built:

https://github.com/dotnet/corefx/blob/c6d9138def9be7c92f33a2f44897841142058a96/src/dir.targets#L22-L31

I would have expected that the first dry run we made to have caught this, that said, I'm not sure if I rebuilt all pkgprojs with the target, and given that this one hasn't been serviced then it wasn't turned on.

**Comment by ericstj** [comment]
This doesn't violate the Exclude=Compile rule, it's just that it has a reference assembly which some desktop tools don't tolerate.

**Comment by joperezr** [comment]
@layomia do you plan on taking this? If so, let me know so that I can help you out on how to fix it.

**Comment by ericstj** [comment]
Closing as this doesn't meet the bar for servicing as it has a viable workaround (use a target that references the lib and not the ref).  If folks still want to see this for servicing we need to open a support request with MS Support: https://support.microsoft.com.
