### ISSUE TITLE
System.ServiceModel.Http Exceptions when using version 4.5.0 or higher

### ISSUE THREAD

**Issue by smartcodinghub** [dotnet/corefx#30517]
Hi all,

I was using the version 4.5.0-preview1-26228-01 of the System.ServiceModel.Http Nuget. After upgrading to 4.5.0 or 4.5.1 I'm getting some exceptions. I paste the message below. From th preview or .Net Framework I can use correctly the WebService.

Thanks in advance,
Óscar

### Exception
```
System.ServiceModel.CommunicationException
  HResult=0x80131500
  Mensaje = An error occurred while sending the request.
  Origen = System.Private.ServiceModel
  Seguimiento de la pila:
   at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(HttpRequestException requestException, HttpRequestMessage request, HttpAbortReason abortReason)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.RequestChannel.<RequestAsync>d__33.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.RequestChannel.<RequestAsyncInternal>d__32.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
   at generatedProxy_1.GetProfiles(GetProfilesRequest )
   at VigilanciaInteligente.Infraestructure.Cameras.OnvifMedia.MediaClient.VigilanciaInteligente.Infraestructure.Cameras.OnvifMedia.OnvifMedia.GetProfiles(GetProfilesRequest request) in D:\GIT\VigilanciaInteligente\VigilanciaInteligente.Infraestructure.Cameras\OnvifMedia.cs:line 17998
   at VigilanciaInteligente.Infraestructure.Cameras.OnvifMedia.MediaClient.GetProfiles() in D:\GIT\VigilanciaInteligente\VigilanciaInteligente.Infraestructure.Cameras\OnvifMedia.cs:line 18004
   at VigilanciaInteligente.Infraestructure.Cameras.OnvifController..ctor(CameraSettings settings) in D:\GIT\VigilanciaInteligente\VigilanciaInteligente.Infraestructure.Cameras\OnvifController.cs:line 91
   at VigilanciaInteligente.Playground.Program.<Run>d__1.MoveNext() in D:\GIT\VigilanciaInteligente\VigilanciaInteligente.Playground\Program.cs:line 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VigilanciaInteligente.Playground.Program.<Main>d__0.MoveNext() in D:\GIT\VigilanciaInteligente\VigilanciaInteligente.Playground\Program.cs:line 11
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VigilanciaInteligente.Playground.Program.<Main>()

Excepción interna 1:
HttpRequestException: An error occurred while sending the request.

Excepción interna 2:
IOException: The server returned an invalid or unrecognized response.

```

**Comment by davidsh** [comment]
System.ServiceModel.Http.* is part of the WCF APIs.  They are in the https://github.com/dotnet/wcf repo.  So, this bug should be moved there.

**Comment by karelz** [comment]
This issue was moved to dotnet/wcf#2960
