### ISSUE TITLE
The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.: TypeInitializationException

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/corefx#30518]
Originally posted as https://github.com/aspnet/EntityFrameworkCore/issues/12386 by 	@hounddog22030

Moved here because stack trace indicates it is a problem loading sni.dll from SqlClient package and csproj indicates that package references are correct.

---

We have been using EF Core 1.0 and 2.0 on AWS Lambda

With no other code changes, updating to EF Core 2.1 is throwing the exception "The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.: TypeInitializationException"

Exception message: "The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.: TypeInitializationException"
Stack trace:

The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.: TypeInitializationException
at System.Data.SqlClient.TdsParser..ctor(Boolean MARS, Boolean fAsynchronous)
at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
at System.Data.SqlClient.SqlConnection.Open()
at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
at Functions.EfCoreAwsLambdaReproduce.MyFunction(ILambdaContext lambdaContext) in /codebuild/output/src963058259/src/Functions/EFCoreAWSLambdaReproduce.cs:line 41

at System.Data.SqlClient.TdsParserStateObjectFactory.get_EncryptionOptions()
at System.Data.SqlClient.TdsParser..cctor()
Unable to load DLL 'sni.dll': The specified module or one of its dependencies could not be found.
(Exception from HRESULT: 0x8007007E): DllNotFoundException
at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize(IntPtr pmo)
at System.Data.SqlClient.SNILoadHandle..ctor()
at System.Data.SqlClient.SNILoadHandle..cctor()

### Steps to reproduce
I created the simplest example
1. Create the following function with embedded classes
2. Update server/database/password
3. Deploy to AWS Lambda
4. Execute function

```c#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using Amazon.Lambda.Core;
using Bisque.Lambda;
using Bisque.Serverless;
using Microsoft.EntityFrameworkCore;

namespace Functions
{
    public class EfCoreAwsLambdaReproduce
    {
        public class MyEntity
        {
            [Key]
            public Guid MyId { get; set; }
            public string MyValue { get; set; }
        }
        public class MyContext : DbContext
        {
            public DbSet<MyEntity> MyEntities { get; set; }
            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                base.OnConfiguring(optionsBuilder);
                if (!optionsBuilder.IsConfigured)
                {
                    optionsBuilder.UseSqlServer($"Server=myserver;Database=MyDatabase;MultipleActiveResultSets=True;User Id=masterusername;Password=mypassword;Trusted_Connection=false");
                }
            }
        }

        [FunctionType(typeof(Function))]
        [ServerlessFunction.PolicyAttribute("AWSLambdaVPCAccessExecutionRole")]
        public void MyFunction(ILambdaContext lambdaContext)
        {
            using (var dataContext = new MyContext())
            {
                lambdaContext.Logger.LogLine("foreach (MyEntity dataContextMyEntity in dataContext.MyEntities.Where(x=>x.MyValue.ToString().Contains(4)))");
                foreach (MyEntity dataContextMyEntity in dataContext.MyEntities.Where(x=>x.MyValue.ToString().Contains("4")))
                {
                    lambdaContext.Logger.LogLine(dataContextMyEntity.MyId.ToString());
                }
                lambdaContext.Logger.LogLine("lambdaContext.Logger.LogLine(dataContext.MyEntities.Max(d => d.MyValue));");
                lambdaContext.Logger.LogLine(dataContext.MyEntities.Max(d => d.MyValue));


            }
        }


    }
}
```

### Further technical details
EF Core version: 2.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system:  AWS Lambda (Ubuntu?)

**Comment by ajcvickers** [comment]
Comment moved from https://github.com/aspnet/EntityFrameworkCore/issues/12386#issuecomment-398457874

Here it is below.  There are some additional NuGet packages that are not publicly available, but they make no references to any EntityFramework or System.Data

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <RuntimeIdentifiers>win10-x64;osx.10.11-x64;ubuntu.16.04-x64</RuntimeIdentifiers>
    <AssemblyName>BubbleBoy.Functions</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migrations\20180616021129_MyMigration.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="1.1.2" />
    <PackageReference Include="Amazon.Lambda.Core" Version="1.0.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.2.0" />
    <PackageReference Include="Amazon.Lambda.S3Events" Version="1.0.2" />
    <PackageReference Include="AWSSDK.S3" Version="3.3.17" />
    <PackageReference Include="Bisque.Aws" Version="18.130.4109-prune-lambda-execution-role" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
    <PackageReference Include="System.Runtime.Serialization.Primitives" Version="4.3.0" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data\Data.csproj" />
    <ProjectReference Include="..\Entity.ShippingEasy\Entity.ShippingEasy.csproj" />
    <ProjectReference Include="..\Utility\Utility.csproj" />
  </ItemGroup>
</Project>

**Comment by keeratsingh** [comment]
@hounddog22030 As per a couple of related issues it seems like adding an explicit reference to a newer version of SqlClient package like `4.4.0` resolves the issue, could you try the same and revert back.
```xml
<PackageReference Include="System.Data.SqlClient" Version="4.4.0" /> 
```
- https://github.com/dotnet/corefx/issues/23545#issuecomment-325017094
- https://github.com/Azure/app-service-announcements-discussions/issues/9#issuecomment-322922859

**Comment by hounddog22030** [comment]
I did.  I get the following Nuget exception:

error NU1605: Detected package downgrade: System.Data.SqlClient from 4.5.1 to 4.4.0. Reference the package directly from the project to select a different version.

I can't even add it via VS IDE.  I added the 4.5.1 and then edited the csproj file to read 4.4.0 and get the above error.

**Comment by keeratsingh** [comment]
In that case you can add the `4.5.1` package reference explicitly in the csproj file and see if that helps.
```xml
<PackageReference Include="System.Data.SqlClient" Version="4.5.1" />
```

**Comment by hounddog22030** [comment]
Yes.  Same error.  I notice in VS that the dependencies of it are only windows based.   How do we get it to pick up the linux versions?

**Comment by keeratsingh** [comment]
@hounddog22030 
>I notice in VS that the dependencies of it are only windows based. How do we get it to pick up the linux versions?

I am not sure I completely understand that, could you please elaborate it further in detail.
Also, could you kindly share the repro in a zipped file with updated csproj file and connection string being used.

**Comment by keeratsingh** [comment]
@hounddog22030 Could you kindly share the information requested above.

**Comment by hounddog22030** [comment]
That's a pretty hefty lift;  give me a few days to do it.  I will start with an AWS Serverless Project template.  (https://aws.amazon.com/blogs/developer/serverless-asp-net-core-2-0-applications/)  Will that work?

**Comment by keeratsingh** [comment]
@hounddog22030 As long as the issue in reproable in an Environment that is accessible to me, it should be good, I will ping you again next week if I don't hear from you in that time frame.

**Comment by keeratsingh** [comment]
@hounddog22030 Any progress on the repro for this issue ?
