### ISSUE TITLE
NameValueHeaderValue throws FormatException if header value contains a colon

### ISSUE THREAD

**Issue by lmolkova** [dotnet/corefx#30653]
According to RFC 7231 colon (':') seems to be valid character in header *value*.
Examples of known headers with the colon are `Date: Tue, 15 Nov 1994 08:12:31 GMT` or `Host: server.example.com:80`

However when I try to create a new `NameValueHeaderValue` with the value containing a colon 
```csharp
var header = new NameValueHeaderValue("host", "server.example.com:80");
```

I get `FormatException`. 

```
Unhandled Exception: System.FormatException: The format of value 'server.example.com:80' is invalid.
   at System.Net.Http.Headers.NameValueHeaderValue.CheckValueFormat(String value)
   at System.Net.Http.Headers.NameValueHeaderValue.CheckNameValueFormat(String name, String value)
   at System.Net.Http.Headers.NameValueHeaderValue..ctor(String name, String value)
```

Expected: `host=server.example.com:80`

**Comment by karelz** [comment]
Same behavior on .NET 4.7.2.

**Comment by wfurt** [comment]
cc: @rmkerr @caesar1995

**Comment by rmkerr** [comment]
Yeah, this definitely looks like something we should fix. The http 1.1 spec definitely allows for ":" in header values, and we should support that usage for custom headers.

@lmolkova is this a blocking issue for you? There are other ways to set known headers like `Host` that will hopefully allow you to bypass this, like setting the value of `request.Headers.Host` on a request.

**Comment by lmolkova** [comment]
@rmkerr it's not blocking. I work on the Application Insights and we allow customers to pass arbitrary context in the headers so it might affect them, but we have not got any tickets related to it so far.

**Comment by lmolkova** [comment]
fixed in #35906

**Comment by karelz** [comment]
Triage: This should be fairly straightforward
