### ISSUE TITLE
DrawLines_PointFs and DrawBezier_PointFs failing sporadically in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#30683]
I've seen these fail multiple times in CI now.
```
2018-06-26 22:47:39,723: INFO: proc(54): run_and_log_output: Output:    System.Drawing.Tests.Graphics_DrawBezierTests.DrawBezier_PointFs [FAIL]
2018-06-26 22:47:39,723: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-06-26 22:47:39,723: INFO: proc(54): run_and_log_output: Output:       Expected: Byte[] [208, 0, 8, 33, 6, ...]
2018-06-26 22:47:39,723: INFO: proc(54): run_and_log_output: Output:       Actual:   Byte[] [27, 206, 219, 21, 255, ...]
2018-06-26 22:47:39,737: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-06-26 22:47:39,987: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Drawing.Common\tests\DrawingTest.cs(21,0): at System.Drawing.Tests.DrawingTest.ValidateImageContent(Image image, Byte[] expectedHash)
2018-06-26 22:47:39,987: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Drawing.Common\tests\Graphics_DrawBezierTests.cs(59,0): at System.Drawing.Tests.Graphics_DrawBezierTests.DrawBezier_PointFs()
2018-06-26 22:47:39,987: INFO: proc(54): run_and_log_output: Output:    System.Drawing.Tests.Graphics_DrawLineTests.DrawLines_PointFs [FAIL]
2018-06-26 22:47:39,987: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-06-26 22:47:39,987: INFO: proc(54): run_and_log_output: Output:       Expected: Byte[] [142, 194, 251, 180, 222, ...]
2018-06-26 22:47:39,987: INFO: proc(54): run_and_log_output: Output:       Actual:   Byte[] [89, 188, 96, 22, 200, ...]
2018-06-26 22:47:39,987: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-06-26 22:47:39,987: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Drawing.Common\tests\DrawingTest.cs(21,0): at System.Drawing.Tests.DrawingTest.ValidateImageContent(Image image, Byte[] expectedHash)
2018-06-26 22:47:39,987: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---f8ac6754\src\System.Drawing.Common\tests\Graphics_DrawLineTests.cs(32,0): at System.Drawing.Tests.Graphics_DrawLineTests.DrawLines_PointFs()
```
I could be wrong, but I believe I only started seeing it after https://github.com/dotnet/corefx/pull/30099.
cc: @safern, @JeremyKuhne

**Comment by JeremyKuhne** [comment]
We can disable these pending further investigation. I assumed that drawing wouldn't change, but I'm likely missing some key environmental input.

**Comment by safern** [comment]
I've opened: https://github.com/dotnet/corefx/pull/30684 to disable. 

@JeremyKuhne I've assigned the issue to you so that you can investigate what changed.

Fyi: @eerhardt

**Comment by jkotas** [comment]
Failed on https://github.com/dotnet/coreclr/pull/20532
