### ISSUE TITLE
Running Microsoft/Mobius with .NetCore 2.1.301 occurs SerializationException: "Serializing delegates is not supported on this platform"

### ISSUE THREAD

**Issue by nomadsoar** [dotnet/corefx#30685]
I tried to run [Microsoft/Mobius](https://github.com/Microsoft/Mobius) with .NetCore v2.1.301 instead of mono because .NetCore has better performance than mono.

However, for some action functions such as first(), take(), fold() and etc. in Mobius will occur below exception:

 ```
Unhandled Exception: System.Runtime.Serialization.SerializationException: Serializing delegates is not supported on this platform.
   at System.MulticastDelegate.GetObjectData(SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, BinaryFormatterWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Boolean check)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at Microsoft.Spark.CSharp.Core.SparkContext.BuildCommand(CSharpWorkerFunc workerFunc, SerializedMode deserializerMode, SerializedMode serializerMode) in /home/neil/CathayLia/CathayLia_v5.0-NetCoreSpark/Adapter/Core/SparkContext.cs:line 607
   at Microsoft.Spark.CSharp.Core.PipelinedRDD`1.get_RddProxy() in /home/neil/CathayLia/CathayLia_v5.0-NetCoreSpark/Adapter/Core/PipelinedRDD.cs:line 97
   at Microsoft.Spark.CSharp.Core.RDD`1.GetNumPartitions() in /home/neil/CathayLia/CathayLia_v5.0-NetCoreSpark/Adapter/Core/RDD.cs:line 197
   at Microsoft.Spark.CSharp.Core.RDD`1.Take(Int32 num) in /home/neil/CathayLia/CathayLia_v5.0-NetCoreSpark/Adapter/Core/RDD.cs:line 803
   at Microsoft.Spark.CSharp.Core.RDD`1.First() in /home/neil/CathayLia/CathayLia_v5.0-NetCoreSpark/Adapter/Core/RDD.cs:line 854
   at Cathaylife.CathayLiability.Main(String[] args) in /home/neil/CathayLia/CathayLia_v5.0-NetCoreSpark/NetCoreSparkLiability/Program.cs:line 122
```

This exception will not occur if I run Microsoft/Mobius with mono.

Below is my environment information:
OS: CentOS 7.5
NetCore: 2.1.301
Mono: 5.12
Microsoft/Mobius: 2.0.200
Referred Nuget package:
- log4net: 2.0.8
- Microsoft.Extensions.Configuration.Xml: 2.1.1
- Newtonsoft.Json: 11.0.2
- Razorvine.Pyrolite.NetCore: 1.0.0
- Razorvine.Serpent.NetCore: 1.18.0

Is there any solution for it ? 

Thank you.

**Comment by nomadsoar** [comment]
Note that there is no any error or warning in build time and only exception in runtime.

The related codes are below:

```
namespace Microsoft.Spark.CSharp.Core
{
    public class SparkContext
    {
        internal static byte[] BuildCommand(CSharpWorkerFunc workerFunc, SerializedMode deserializerMode = SerializedMode.Byte, SerializedMode serializerMode = SerializedMode.Byte)
        {
            var formatter = new BinaryFormatter();
            var stream = new MemoryStream();
            formatter.Serialize(stream, workerFunc);
            List<byte[]> commandPayloadBytesList = new List<byte[]>();

            ...

            // add func
            var funcBytes = stream.ToArray();
            var funcBytesLengthAsBytes = BitConverter.GetBytes(funcBytes.Length);
            Array.Reverse(funcBytesLengthAsBytes);
            commandPayloadBytesList.Add(funcBytesLengthAsBytes);
            commandPayloadBytesList.Add(funcBytes);
            return commandPayloadBytesList.SelectMany(byteArray => byteArray).ToArray();
        }
    }



    [Serializable]
    internal class CSharpWorkerFunc
    {
        // using dynamic types to keep deserialization simple in worker side
        private readonly Func<int, IEnumerable<dynamic>, IEnumerable<dynamic>> func;

        // stackTrace of this func, for debug purpose
        private readonly string stackTrace;

        public CSharpWorkerFunc(Func<int, IEnumerable<dynamic>, IEnumerable<dynamic>> func)
        {
            this.func = func;
            stackTrace = new StackTrace(true).ToString().Replace("   at ", "   [STACK] ");
        }

        public CSharpWorkerFunc(Func<int, IEnumerable<dynamic>, IEnumerable<dynamic>> func, string innerStackTrace)
            : this(func)
        {
            stackTrace += string.Format("   [STACK] --- Inner stack trace: ---{0}{1}",
                Environment.NewLine, innerStackTrace.Replace("   at ", "   [STACK] "));
        }

        public Func<int, IEnumerable<dynamic>, IEnumerable<dynamic>> Func
        {
            get
            {
                return func;
            }
        }

        public string StackTrace
        {
            get
            {
                return stackTrace;
            }
        }

        /// <summary>
        /// Used to chain functions
        /// </summary>
        public static CSharpWorkerFunc Chain(CSharpWorkerFunc innerCSharpWorkerFunc, CSharpWorkerFunc outCSharpWorkerFunc)
        {
            return new CSharpWorkerFunc(new CSharpWrokerFuncChainHelper(innerCSharpWorkerFunc.Func, outCSharpWorkerFunc.Func).Execute);
        }

        [Serializable]
        private class CSharpWrokerFuncChainHelper
        {
            private readonly Func<int, IEnumerable<dynamic>, IEnumerable<dynamic>> outerFunc;
            private readonly Func<int, IEnumerable<dynamic>, IEnumerable<dynamic>> innerFunc;

            internal CSharpWrokerFuncChainHelper(Func<int, IEnumerable<dynamic>, IEnumerable<dynamic>> iFunc,
                Func<int, IEnumerable<dynamic>, IEnumerable<dynamic>> oFunc)
            {
                innerFunc = iFunc;
                outerFunc = oFunc;
            }

            internal IEnumerable<dynamic> Execute(int split, IEnumerable<dynamic> input)
            {
                return outerFunc(split, innerFunc(split, input));
            }
        }
    }
}
```

**Comment by nomadsoar** [comment]
Thanks @jkotas  for your information.

I am trying to modify Mobius using customized serialize delegate. Referring to #23213 and https://github.com/CXuesong/BotBuilder.Standard/blob/netcore20%2Bnet45/CSharp/Library/Microsoft.Bot.Builder/Fibers/NetStandardSerialization.cs
