### ISSUE TITLE
DiagnosticSourceEventSource throws "System.InvalidCastException: Unable to cast object of type" under load

### ISSUE THREAD

**Issue by mynkov** [dotnet/corefx#30697]
I get exception, when I run load tests on my application. Application was hosted inside docker. This error very rare and I dot't know how to reproduce this behavior.

```
`System.InvalidCastException: Unable to cast object of type '<>f__AnonymousType3`3[Microsoft.AspNetCore.Mvc.Abstractions.ActionDescriptor,Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext,Microsoft.AspNetCore.Mvc.Filters.IResourceFilter]' to type '<>f__AnonymousType6`3[Microsoft.AspNetCore.Mvc.Abstractions.ActionDescriptor,Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext,Microsoft.AspNetCore.Mvc.Filters.IActionFilter]'.
   at System.Diagnostics.DiagnosticSourceEventSource.TransformSpec.PropertySpec.PropertyFetch.TypedFetchProperty`2.Fetch(Object obj)
   at System.Diagnostics.DiagnosticSourceEventSource.TransformSpec.PropertySpec.Fetch(Object obj)
   at System.Diagnostics.DiagnosticSourceEventSource.TransformSpec.Morph(Object obj)
   at System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.Morph(Object args)
   at System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.<>c__DisplayClass2_1.<.ctor>b__2(KeyValuePair`2 evnt)
   at System.Diagnostics.DiagnosticSourceEventSource.CallbackObserver`1.OnNext(T value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.AspNetCore.Mvc.Internal.MvcCoreDiagnosticSourceExtensions.AfterOnResourceExecuted(DiagnosticSource diagnosticSource, ResourceExecutedContext resourceExecutedContext, IResourceFilter filter)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at ProductApplicationStorage.Web.Application.Middlewares.ResponseLoggingMiddleware.<>c__DisplayClass0_0.<<UseResponseLogging>b__0>d.MoveNext() in /src/ProductApplicationStorage.Web/Application/Middlewares/ResponseLoggingMiddleware.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at ProductApplicationStorage.Web.Application.Middlewares.RequestLoggingMiddleware.<>c__DisplayClass0_0.<<UseRequestLogging>b__0>d.MoveNext() in /src/ProductApplicationStorage.Web/Application/Middlewares/RequestLoggingMiddleware.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at WOF.Infrastructure.Logging.LogContextMiddleware.LogContextMiddleware.<>c__DisplayClass0_0.<<UseLogContext>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)`
```

```
OS: Ubuntu 16.04.3 LTS
Server: Kestrel
Assembly: System.Diagnostics.DiagnosticSource, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
Core version: 2.1.0
```

**Comment by karelz** [comment]
Is it a regression against 2.0? Did you try to look at the dumps what is passed to DiagnosticListener.Write?

**Comment by mynkov** [comment]
Is it a regression against 2.0? 
- no, regression against net462 on Windows Server 2012 R2 Standard. 

Did you try to look at the dumps what is passed to DiagnosticListener.Write? 
- no, because the error appears in random time.

**Comment by karelz** [comment]
> because the error appears in random time.

Did you try to capture dumps with the failure and look at them?
Does it happen for you on Windows .NET Core as well?
