### ISSUE TITLE
System.Collections.Concurrent.Tests.EtwTests.TestEtw failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3070]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/3588/consoleFull
```
System.Collections.Concurrent.Tests.EtwTests.TestEtw [FAIL]
        System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
        Stack Trace:
              at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
              at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\Common\tests\System\Diagnostics\Tracing\TestEventListener.cs(47,0): at System.Diagnostics.Tracing.TestEventListener.LoadSourceList()
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Collections.Concurrent\tests\EtwTests.cs(15,0): at System.Collections.Concurrent.Tests.EtwTests.TestEtw()
```

**Comment by stephentoub** [comment]
Another:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst/824/console
```
12:44:41    System.Collections.Concurrent.Tests.EtwTests.TestEtw [FAIL]
12:44:41       System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
12:44:41       Stack Trace:
12:44:42             at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
12:44:42             at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
12:44:42             at System.Diagnostics.Tracing.TestEventListener.LoadSourceList()
12:44:42             at System.Diagnostics.Tracing.TestEventListener..ctor(String taretSourceName, EventLevel level)
12:44:42             at System.Collections.Concurrent.Tests.EtwTests.TestEtw()
```
