### ISSUE TITLE
Fatal error in IL Linker: InvalidOperationException: Operation is not valid due to the current state of the object

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#30714]
```
Fatal error in IL Linker
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Mono.Collections.Generic.Collection`1.Enumerator.CheckState()
   at Mono.Collections.Generic.Collection`1.Enumerator.MoveNext()
   at Mono.Linker.TypeReferenceExtensions.GetMethods(TypeReference type)+MoveNext()
   at Mono.Linker.Steps.TypeMapStep.TryMatchMethod(TypeReference type, MethodDefinition method)
   at Mono.Linker.Steps.TypeMapStep.GetBaseMethodInTypeHierarchy(TypeDefinition type, MethodDefinition method)
   at Mono.Linker.Steps.TypeMapStep.GetBaseMethodInTypeHierarchy(MethodDefinition method)
   at Mono.Linker.Steps.TypeMapStep.MapVirtualBaseMethod(MethodDefinition method)
   at Mono.Linker.Steps.TypeMapStep.MapVirtualMethod(MethodDefinition method)
   at Mono.Linker.Steps.TypeMapStep.MapVirtualMethods(TypeDefinition type)
   at Mono.Linker.Steps.TypeMapStep.MapType(TypeDefinition type)
   at Mono.Linker.Steps.TypeMapStep.ProcessAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
```

**Comment by jkotas** [comment]
Failed in:

https://github.com/dotnet/corefx/pull/30688#issuecomment-400811957
https://github.com/dotnet/corefx/pull/30390#issuecomment-397328498

cc @sbomer @jeffschwMSFT ILLinker crashing in CoreFX CI builds

**Comment by danmosemsft** [comment]
@sbomer if we don't have a repro and code inspection doesn't reveal the problem (it's not obvious to me either, but I don't know the code) then would you consider adding logging? 

Eg catch InvalidOperationException in GetMethods and log the type and method?

It is only a rare break, but we have to fix even those to reliably get a build out, so we can't ignore it unfortuantely.

**Comment by danmosemsft** [comment]
@sbomer is it possible for you to take a look? This broke CI again.

**Comment by stephentoub** [comment]
Failed again several times here: https://github.com/dotnet/corefx/pull/34171

**Comment by wtgodbe** [comment]
@sbomer did you get a chance to take a look at this?

**Comment by ViktorHofer** [comment]
ping @sbomer

**Comment by danmosemsft** [comment]
Looks like https://github.com/mono/linker/issues/445

**Comment by ericstj** [comment]
I had a chat with @jbevain about this.  Since we haven't seen a new failure here since January and we cannot imagine anything that might have caused this due to the way that the linker loads metadata, we're going to close as no-repro.  One can imagine that this could have been caused by a GC hole that hosed the Collection, thus version is garbage, or various other runtime / environment issues that may have caused this problem.  None of which are particularly actionable without a repro or a dump.

If we hit this again we'll reactivate and add instrumentation that would help us root cause the problem.
