### ISSUE TITLE
[netfx] System.Security.Principal.Windows.Tests: The handle is invalid.

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#30713]
```
 Finished:    System.Security.Principal.Windows.Tests
  System.ApplicationException: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))
    at System.Threading.TimerQueue.DeleteAppDomainTimer(IntPtr handle)
    at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
    at System.Runtime.InteropServices.SafeHandle.Finalize()
```

**Comment by jkotas** [comment]
Failed in: 
https://github.com/dotnet/corefx/pull/30297#issuecomment-400888072
https://github.com/dotnet/corefx/pull/30688#issuecomment-400651118

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/1841 suggests this was fixed in Core by #1871 so we can simply disable these for NETFX which does not have that fix.

**Comment by jkotas** [comment]
That fix was in System.IO.Pipes. This is in System.Security.Principal...

**Comment by danmosemsft** [comment]
Doh - you're right

**Comment by stephentoub** [comment]
Failed again here:
https://mc.dot.net/#/user/safern/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/dcf396e51c78627c8bd73d4e6f0c4d0b1581f6a9/workItem/System.Security.Principal.Windows.Tests/wilogs
```
2018-06-28 15:49:43,132: INFO: proc(54): run_and_log_output: Output: System.ApplicationException: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))
2018-06-28 15:49:43,132: INFO: proc(54): run_and_log_output: Output:    at System.Threading.TimerQueue.DeleteAppDomainTimer(IntPtr handle)
2018-06-28 15:49:43,132: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
2018-06-28 15:49:43,148: INFO: proc(54): run_and_log_output: Output:    at System.Runtime.InteropServices.SafeHandle.Finalize()
```
