### ISSUE TITLE
PoolBlockPeriodTest/TestNonAzureBlockingPeriod test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#30732]
https://mc.dot.net/#/user/baulig/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/ee2ee9a8190e80c62219d0f138f031c966085b60/workItem/System.Data.SqlClient.ManualTesting.Tests/analysis/xunit/System.Data.SqlClient.ManualTesting.Tests.PoolBlockPeriodTest~2FTestNonAzureBlockingPeriod(description:%20%5C%22NonAzure%20with%20Always%20Policy%20must%20Enable%20Blocking%5C%22,%20Params:%20%5B%5C%22nonexistanceserver%5C%22,%20)
```
Unhandled Exception of Type Xunit.Sdk.InRangeException
Message :
Assert.InRange() Failure
Range:  (0 - 16)
Actual: 17
Stack Trace :
   at System.Data.SqlClient.ManualTesting.Tests.PoolBlockPeriodTest.PoolBlockingPeriodNonAzureTest(String connStr, Nullable`1 policy) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Data.SqlClient\tests\ManualTests\SQL\ConnectionPoolTest\PoolBlockPeriodTest.netcoreapp.cs:line 100
   at System.Data.SqlClient.ManualTesting.Tests.PoolBlockPeriodTest.TestNonAzureBlockingPeriod(String description, Object[] Params) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Data.SqlClient\tests\ManualTests\SQL\ConnectionPoolTest\PoolBlockPeriodTest.netcoreapp.cs:line 59
```

But... in addition to this failing, why is a "Manual" test running in CI?  Seems like either it should be attributed to not be run in CI as with the other connection tests, or it's in the wrong project.

cc: @AfsanehR

**Comment by AfsanehR** [comment]
@stephentoub I have modified the `System.Data.SqlClient.ManualTesting.Tests.csproj` and `src/System.Data.SqlClient/tests/ManualTests/Configurations.props` to run that specific test targetting netcoreapp only. But on the page you mentioned here, I am seeing the test is ran under  test/functional/cli/. Will be looking into this now.
