### ISSUE TITLE
SqlConnection error when executing query after SQL server killed connections (on linux)

### ISSUE THREAD

**Issue by Rora** [dotnet/corefx#30738]
When running integration tests we kill all sql connections by setting the DB to single_user mode and then back to multi_user mode. This works well on windows, but throws an error on linux. We've currently fixed this issue by calling 'SqlConnection.ClearAllPools();' after killing all connections. Repro steps:

1. create DB & table
2. set db to single user mode
3. set db to multi user mode
4. run a SELECT .... query -> EXCEPTION

The error thrown:

```
System.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - Success)
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at SqlIssueOnLinux.Program.Main(String[] args) in C:\Repos\tmp\SqlIssueOnLinux\SqlIssueOnLinux\Program.cs:line 74
```

Windows config: `windows 7` -> sql server container running on the default docker linux vm (no errors in this config)
Linux config: `Linux version 4.15.0-1013-azure (buildd@lcy01-amd64-006) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9))` sql server container running on the host (errors in this config)

Repro solution: [SqlIssueOnLinux.zip](https://github.com/dotnet/corefx/files/2146798/SqlIssueOnLinux.zip)

dot version 2.1.301 installed on linux

**Comment by keeratsingh** [comment]
Issue fixed by PR #31631
