### ISSUE TITLE
TimesIncludeMillisecondPart_OSX test fails locally on macOS

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#30742]
This test is not failing on CI but does fail on locally on mac OS. 

We need to either remove or disable the test.

Here's the callstack:
```
     System.IO.Tests.DirectoryInfo_GetSetTimes.TimesIncludeMillisecondPart_OSX [FAIL]
        Assert.All() Failure: 9 out of 9 items in the collection did not pass.
        [8]: Xunit.Sdk.EqualException: Assert.Equal() Failure
             Expected: 0
             Actual:   796
                at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
                at System.IO.Tests.BaseGetSetTimes`1.<>c__DisplayClass11_0.<TimesIncludeMillisecondPart_OSX>b__0(TimeFunction function) in /Users/maryam/CodeHub/corefx/src/System.IO.FileSystem/tests/Base/BaseGetSetTimes.cs:line 149
                at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action)
...
```

cc: @danmosemsft

**Comment by danmosemsft** [comment]
BTW by split the test, presuambly you have one test with an "if"

**Comment by danmosemsft** [comment]
@maryamariyan can this be closed as done

**Comment by maryamariyan** [comment]
@danmosemsft this can be closed when https://github.com/dotnet/corefx/pull/31046 gets merged into release/2.1

(A fix is already in master and release/2.2)

**Comment by karelz** [comment]
Fixed in 3.0 (master): PR #30763
Fixed in 2.2: PR #31657
Fix in 2.1: TBD [maryamariyan please update it inline when the PR is created & merged]

**Comment by danmosemsft** [comment]
@maryamariyan can this be closed now

**Comment by maryamariyan** [comment]
yes closing as https://github.com/dotnet/corefx/pull/31046 is merged now.
