### ISSUE TITLE
ProcessStartInfoTests.TestEnvironmentOfChildProcess failed on Windows in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3075]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/3613/console
```
Discovering: System.Diagnostics.Process.Tests
  Discovered:  System.Diagnostics.Process.Tests
  Starting:    System.Diagnostics.Process.Tests
     System.Diagnostics.ProcessTests.ProcessStartInfoTests.TestEnvironmentOfChildProcess [FAIL]
        Assert+WrapperXunitException : File path: d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs. Line: 220
        ---- Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(582,0): at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(577,0): at Assert.True(Boolean condition, String userMessage, String path, Int32 line)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(220,0): at System.Diagnostics.ProcessTests.ProcessStartInfoTests.TestEnvironmentOfChildProcess()
           ----- Inner Stack Trace -----
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(570,0): at Assert.True(Boolean condition, String userMessage, String path, Int32 line)
  Finished:    System.Diagnostics.Process.Tests
```

cc: @Maxwe11, @Priya91, @pallavit

**Comment by stephentoub** [comment]
Failed again:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/3607/console
```
Discovering: System.Diagnostics.Process.Tests
  Discovered:  System.Diagnostics.Process.Tests
  Starting:    System.Diagnostics.Process.Tests
     System.Diagnostics.ProcessTests.ProcessStartInfoTests.TestEnvironmentOfChildProcess [FAIL]
        Assert+WrapperXunitException : File path: d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs. Line: 220
        ---- Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(582,0): at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(577,0): at Assert.True(Boolean condition, String userMessage, String path, Int32 line)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(223,0): at System.Diagnostics.ProcessTests.ProcessStartInfoTests.TestEnvironmentOfChildProcess()
           ----- Inner Stack Trace -----
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(570,0): at Assert.True(Boolean condition, String userMessage, String path, Int32 line)
  Finished:    System.Diagnostics.Process.Tests
```

**Comment by Maxwe11** [comment]
interesting...I think it's unrelated but if fails only with #3042

**Comment by JonHanna** [comment]
Changing `f2` to `f` flipped the switch from "more magic" to "magic"?

**Comment by Maxwe11** [comment]
and again http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/3618/console
I have triggered CI to build own PRs and they pass.

**Comment by stephentoub** [comment]
Maybe it's a machine thing?  Are the tests that are failing all running on the same build machine, and the ones passing running on a different machine?

**Comment by Maxwe11** [comment]
>Maybe it's a machine thing?

No, #3080 was successfully built on same machine (at least windows-debug on which it failed originally)

**Comment by stephentoub** [comment]
Right now all we get is a true/false if it fails.  In case it fails again in CI, maybe we should update those asserts to include information on what was in the collections that caused them to differ?

**Comment by Maxwe11** [comment]
agree, will do.

**Comment by stephentoub** [comment]
This failed again:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/3629/console
```
Discovering: System.Diagnostics.Process.Tests
  Discovered:  System.Diagnostics.Process.Tests
  Starting:    System.Diagnostics.Process.Tests
     System.Diagnostics.ProcessTests.ProcessStartInfoTests.TestEnvironmentOfChildProcess [FAIL]
        Assert+WrapperXunitException : File path: d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs. Line: 225
        ---- Expected: ghprbActualCommitAuthor=Alexander Kâ”œâ•¢plinger
        Actual: ghprbActualCommitAuthor=Alexander KÃ¶plinger
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(582,0): at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(577,0): at Assert.True(Boolean condition, String userMessage, String path, Int32 line)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(229,0): at System.Diagnostics.ProcessTests.ProcessStartInfoTests.TestEnvironmentOfChildProcess()
           ----- Inner Stack Trace -----
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(574,0): at Assert.True(Boolean condition, String userMessage, String path, Int32 line)
  Finished:    System.Diagnostics.Process.Tests
```

And again:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/3638/console
```
Discovering: System.Diagnostics.Process.Tests
  Discovered:  System.Diagnostics.Process.Tests
  Starting:    System.Diagnostics.Process.Tests
     System.Diagnostics.ProcessTests.ProcessStartInfoTests.TestEnvironmentOfChildProcess [FAIL]
        Assert+WrapperXunitException : File path: d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs. Line: 225
        ---- Expected: ghprbActualCommitAuthor=Alexander Kâ”œâ•¢plinger
        Actual: ghprbActualCommitAuthor=Alexander KÃ¶plinger
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(582,0): at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(577,0): at Assert.True(Boolean condition, String userMessage, String path, Int32 line)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(225,0): at System.Diagnostics.ProcessTests.ProcessStartInfoTests.TestEnvironmentOfChildProcess()
           ----- Inner Stack Trace -----
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(574,0): at Assert.True(Boolean condition, String userMessage, String path, Int32 line)
  Finished:    System.Diagnostics.Process.Tests
```

**Comment by akoeplinger** [comment]
>        Expected: ghprbActualCommitAuthor=Alexander Kâ”œâ•¢plinger
>        Actual: ghprbActualCommitAuthor=Alexander KÃ¶plinger

Looks like it can't decide how to properly mess up my last name :smile:

**Comment by Maxwe11** [comment]
I have submitted fix #3090 but couldn't verify it.
@akoeplinger could you cherry-pick my commit into your PR please? We will see if it fixes issue.

**Comment by akoeplinger** [comment]
@stephentoub Interesting, looks like the console output is misleading. If I look at the actual test result page (which comes from the XML the test runner outputs) it has the correct encoding for the "actual" value: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/3638/testReport/System.Diagnostics.ProcessTests/ProcessStartInfoTests/TestEnvironmentOfChildProcess/

@Maxwe11 I cherry-picked, let's see what happens.

**Comment by Maxwe11** [comment]
@akoeplinger failed as expected http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/3647/
Thanks for the help :smile:

**Comment by JonHanna** [comment]
> Expected: ghprbActualCommitAuthor=Alexander Kâ”œâ•¢plinger
> Actual: ghprbActualCommitAuthor=Alexander KÃ¶plinger

`Ã¶` for `ö` isn't that surprising; UTF-8 encoded `ó` interpreted as CP-1252 or most of the ISO 8859 family. How do you get from `ö` to `â”œâ•¢` though?
