### ISSUE TITLE
SendRecvPollSync_TcpListener_Socket failed on Nano

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#30804]
https://mc.dot.net/#/product/netcore/prodconmaster/source/prodcon~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180627.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendReceiveSyncForceNonBlocking~2FSendRecvPollSync_TcpListener_Socket(listenAt:%20127.0.0.1,%20pollBeforeOperation:%20False)

Flaky?

```
Windows.10.Nano.Amd64-x64-Release
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Read poll after completion should have succeeded
Expected: True
Actual:   False
Stack Trace :
   at System.Net.Sockets.Tests.SendReceive`1.<>c__DisplayClass7_1.<<SendRecvPollSync_TcpListener_Socket>b__0>d.MoveNext() in E:\A\_work\5\s\corefx\src\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs:line 583
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in E:\A\_work\5\s\corefx\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 64
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in E:\A\_work\5\s\corefx\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 92
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in E:\A\_work\5\s\corefx\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 52
   at System.Net.Sockets.Tests.SendReceive`1.SendRecvPollSync_TcpListener_Socket(IPAddress listenAt, Boolean pollBeforeOperation) in E:\A\_work\5\s\corefx\src\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs:line 630
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/issues/29862
https://github.com/dotnet/corefx/issues/25894

**Comment by karelz** [comment]
@wfurt please take a look at Kusto and close it if it didn't happen recently.

**Comment by wfurt** [comment]
I did not see any recent Nano failures. I'll leave #25894 to track general instability on Windows.
