### ISSUE TITLE
Regression: "Length cannot be less than zero" when executing somewhat complicated LINQ query projecting a DTO

### ISSUE THREAD

**Issue by maumar** [dotnet/corefx#30955]
Some of EFCore tests started failing after recent package upgrade.

The queries that fail look as follows:

```cs
orders.GroupBy(
                    o => new
                    {
                        o.CustomerID,
                        o.EmployeeID
                    }).Select(
                    g =>
                        new CompositeDto
                        {
                            Sum = g.Sum(o => o.OrderID),
                            Min = g.Min(o => o.OrderID),
                            CustomerId = g.Key.CustomerID,
                            EmployeeId = g.Key.EmployeeID,
                            Max = g.Max(o => o.OrderID),
                            Avg = g.Average(o => o.OrderID)
                        }
```

and

```cs
squads.Select(
                    s => new
                    {
                        s.Name,
                        Gear = s.Members.Where(g => g.HasSoulPatch).Select(g => new MyDTO()).FirstOrDefault()
                    })
```

Exception is as follows:

```
System.ArgumentOutOfRangeException : Length cannot be less than zero.
  Parameter name: length
  Stack Trace:
     at System.String.Substring(Int32 startIndex, Int32 length)
     at Microsoft.CSharp.RuntimeBinder.Syntax.NameTable.Add(String key, Int32 length)
     at Microsoft.CSharp.RuntimeBinder.Syntax.NameManager.Add(String key, Int32 length)
     at Microsoft.CSharp.RuntimeBinder.SymbolTable.GetName(Type type)
     at Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(Type originalType)
     at Microsoft.CSharp.RuntimeBinder.SymbolTable.GetConstructedType(Type type, AggregateSymbol agg)
     at Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(Type originalType)
     at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.GetArgumentType(ICSharpBinder p, CSharpArgumentInfo argInfo, Expression param, DynamicMetaObject arg, Int32 index)
     at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateArgumentArray(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args)
     at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
     at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(DynamicMetaObjectBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
     at Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(DynamicMetaObjectBinder action, RuntimeBinder binder, DynamicMetaObject[] args, IEnumerable`1 arginfos, DynamicMetaObject onBindingError)
     at Microsoft.CSharp.RuntimeBinder.CSharpGetMemberBinder.FallbackGetMember(DynamicMetaObject target, DynamicMetaObject errorSuggestion)
     at System.Dynamic.DynamicMetaObject.BindGetMember(GetMemberBinder binder)
     at System.Dynamic.GetMemberBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args)
     at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
     at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
     at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
     at Microsoft.EntityFrameworkCore.Query.GearsOfWarQueryTestBase`1.<>c.<Select_subquery_projecting_single_constant_of_non_mapped_type>b__356_1(Object e) in D:\git\EntityFrameworkCore\src\EFCore.Specification.Tests\Query\GearsOfWarQueryTestBase.cs:line 6081
     at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
     at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
     at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
     at System.Linq.OrderedEnumerable`1.ToList()
     at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
     at Microsoft.EntityFrameworkCore.TestUtilities.TestHelpers.AssertResults[T](IList`1 expected, IList`1 actual, Func`2 elementSorter, Action`2 elementAsserter, Boolean verifyOrdered) in D:\git\EntityFrameworkCore\src\EFCore.Specification.Tests\TestUtilities\TestHelpers.cs:line 278
     at Microsoft.EntityFrameworkCore.TestUtilities.QueryAsserter`1.<AssertQuery>d__11`1.MoveNext() in D:\git\EntityFrameworkCore\src\EFCore.Specification.Tests\TestUtilities\QueryAsserter.cs:line 327
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.EntityFrameworkCore.Query.GearsOfWarQuerySqlServerTest.<Select_subquery_projecting_single_constant_of_non_mapped_type>d__348.MoveNext() in D:\git\EntityFrameworkCore\test\EFCore.SqlServer.FunctionalTests\Query\GearsOfWarQuerySqlServerTest.cs:line 6892
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Failed   Microsoft.EntityFrameworkCore.Query.GearsOfWarQuerySqlServerTest.Select_subquery_projecting_single_constant_of_non_mapped_type(isAsync: True)
```

Let me know if you guys need a better repro - I can try to unpack our test infrastructure

**Comment by maumar** [comment]
this seems to be the package upgrade that caused the problem to appear: https://github.com/aspnet/EntityFrameworkCore/commit/e9653479d11476141187527b3599757371356086

**Comment by maumar** [comment]
@Eilon fyi

**Comment by stephentoub** [comment]
What OS is this happening on?

**Comment by maumar** [comment]
Windows, MacOS and Linux (Ubuntu)

**Comment by stephentoub** [comment]
And what version of .NET Core?

I'm particularly confused by the top of the stack trace:
```
     at System.String.Substring(Int32 startIndex, Int32 length)
     at Microsoft.CSharp.RuntimeBinder.Syntax.NameTable.Add(String key, Int32 length)
     at Microsoft.CSharp.RuntimeBinder.Syntax.NameManager.Add(String key, Int32 length)
     at Microsoft.CSharp.RuntimeBinder.SymbolTable.GetName(Type type)
```
That `SymbolTable.GetName` method is only calling `NameManager.Add(string, int)` if the int is >= 0:
https://github.com/dotnet/corefx/blob/ff31acd8c64ddcc69c70ae09aacbf2e15d97ceec/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/SymbolTable.cs#L301-L314
That length is then passed through unmodified to `NameTable.Add`:
https://github.com/dotnet/corefx/blob/ff31acd8c64ddcc69c70ae09aacbf2e15d97ceec/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Syntax/NameManager.cs#L160-L165
and `NameTable.Add` is calling `key.Substring(0, length)` with that unmodified value, which had previously been validated to be >= 0:
https://github.com/dotnet/corefx/blob/ff31acd8c64ddcc69c70ae09aacbf2e15d97ceec/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Syntax/NameTable.cs#L50-L62
so I don't understand how with that stack a negative value could be finding its way into `String.Substring`:
https://github.com/dotnet/coreclr/blob/f39809b6e560450daa299d7566ca6d861cb2c270/src/System.Private.CoreLib/shared/System/String.Manipulation.cs#L1602-L1605
unless there's some kind of memory corruption, JIT bug, etc.

**Comment by maumar** [comment]
We are running `2.2.0-preview1-26618-02` version of netcoreapp

**Comment by maumar** [comment]
Here is the `dotnet --info` dump:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\maumar\.dotnet\x64\sdk\2.1.301\

Host (useful for support):
  Version: 3.0.0-preview1-26629-04
  Commit:  fa49ae3f4a

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Users\maumar\.dotnet\x64\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Users\maumar\.dotnet\x64\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Users\maumar\.dotnet\x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Users\maumar\.dotnet\x64\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Users\maumar\.dotnet\x64\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Users\maumar\.dotnet\x64\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Users\maumar\.dotnet\x64\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview1-26618-02 [C:\Users\maumar\.dotnet\x64\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview1-26629-04 [C:\Users\maumar\.dotnet\x64\shared\Microsoft.NETCore.App]
```

**Comment by maumar** [comment]
Ok, I've been trying to simplify the repro somewhat but now the issue is gone from our 2.2 CI runs (seemingly without any code change on our side) and only shows up in 3.0. Maybe there is some sort of issue with corrupted packages? 

Currently the issue can be reproduced by cloning EFCore repo: https://github.com/aspnet/EntityFrameworkCore.git

```
git checkout repro30955
.\build.cmd
```

I will report back tomorrow, once our CI catches up, perhaps this is only temporary. Otherwise will try to strip some of the EF code so it's easier for you to debug. Running only the affected query, or only the affected test suite doesn't seem to produce this issue.

**Comment by natemcmaster** [comment]
FYI, this failure also appeared when we updated EF tests to Microsoft.NETCore.App 2.1.2. Were there changes either in corefx or EF Core between 2.1.0 and 2.1.2 which may have led to this?

**Comment by divega** [comment]
FYI, the failure is coming from the part of the test that does *not* use EF Core. @maumar is trying to create a smaller repro.

**Comment by maumar** [comment]
**Update:** I was able to simplify the solution significantly, although still there is some junk remaining. It can be found here: https://github.com/aspnet/EntityFrameworkCore/tree/repro30955_213 (EFCore repo, branch: repo30955_213). 

Steps to reproduce is to run build.cmd from the main directory. It still builds EF and there are some references yet to be removed. Takes a few minutes to build EF for the first time on a clean machine. Test themselves take a second and reproduce the bug 100% of the time.

**Comment by maumar** [comment]
I simplified the repro further, down to about 10 code files, and completely removed references to EF Core. Repro still resides in branch repro30955_213 on EFCore github.

**Comment by divega** [comment]
Hey @natemcmaster, @stephentoub, @maumar, is my understanding correct that this issue broke our 2.1.3 patch build and that should be investigated as a possible regression in .NET Core? Just trying to make sure it doesn’t fall through the cracks because it is missing some label.

**Comment by natemcmaster** [comment]
Yes, it appears this issue was regressed sometime between 2.1.0 and 2.1.2.

**Comment by Eilon** [comment]
@Petermarcu / @stephentoub - can we get an update on this? We are concerned that something may have regressed in a 2.1.x patch and is at least affecting EF Core scenarios.

**Comment by Petermarcu** [comment]
@danmosemsft can you take a look at this?

**Comment by danmosemsft** [comment]
Looking.

**Comment by danmosemsft** [comment]
This was determined to be 2.0 only (not 2.1) and as @stephentoub suggested, not easily debugged (the codepath should be impossible). Given 2.0 is nearly out of support, I recommend close.

**Comment by maumar** [comment]
agree with @danmosemsft. We will disable the affected tests in our branches when running against 2.0
