### ISSUE TITLE
Unable to receive HTTP responses from www.nasdaq.com

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#30979]
.NET Core is unable to handle HTTP responses from www.nasdaq.com.  It seems there is some non-standard HTTP response formatting from this website.

Repro:

Program.cs
```c#
using System;
using System.IO;
using System.Net;
using System.Net.Http;

namespace httptest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine($"(Framework: {Path.GetDirectoryName(typeof(object).Assembly.Location)})");

            try
            {
                var client = new HttpClient();
                HttpResponseMessage response = client.GetAsync("https://www.nasdaq.com").GetAwaiter().GetResult();
                Console.WriteLine($"{(int)response.StatusCode} {response.ReasonPhrase}");

                string body = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();
                Console.WriteLine(body);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
    }
}
```

httptest.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net47;netcoreapp2.0;netcoreapp2.1</TargetFrameworks>
    <RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <!-- Conditionally obtain references for the .NET Framework 4.7 target -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'net47' ">
    <Reference Include="System.Net.Http" />
  </ItemGroup>

</Project>
```

.NET Core 2.1 (Windows - uses SocketsHttpHandler):

```
D:\dotnet\httptest>dotnet run netcoreapp2.1
(Framework: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.1)
System.Net.Http.HttpRequestException: An error occurred while sending the request.
---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at httptest.Program.Main(String[] args) in D:\dotnet\httptest\Program.cs:line 14
```

.NET Core 2.0 (Windows - use WinHttpHandler):
```
D:\dotnet\httptest>dotnet run -f netcoreapp2.0
(Framework: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.9)
System.Net.Http.HttpRequestException: An error occurred while sending the request.
---> System.Net.Http.WinHttpException: The server returned an invalid or unrecognized response
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at httptest.Program.Main(String[] args) in D:\dotnet\httptest\Program.cs:line 14
```

Even .NET Framework has problems.

.NET Framework 4.7:
```
D:\dotnet\httptest>dotnet run -f net47
(Framework: C:\Windows\Microsoft.NET\Framework64\v4.0.30319)
System.Net.Http.HttpRequestException: An error occurred while sending the request.
---> System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at httptest.Program.Main(String[] args)
```

However, if you add this to the app.config:

```xml
  <system.net>
    <settings>
      <httpWebRequest useUnsafeHeaderParsing="true"/>
    </settings>
  </system.net>
```

and run under .NET Framework, it will work.

See: [httpWebRequest useUnsafeHeaderParsing](https://docs.microsoft.com/en-us/dotnet/api/system.net.configuration.httpwebrequestelement.useunsafeheaderparsing?view=netframework-4.7.2#System_Net_Configuration_HttpWebRequestElement_UseUnsafeHeaderParsing)

UWP .NET Core (which uses WinRT Windows.Web.Http and native WinINet) work ok.  The browsers (Chrome, IE, Edge) also work ok.

**Comment by mayconbeserra** [comment]
Hi @davidsh I'm having the same issue using .NET Core 2.1 inside a container, it doesn't happen on MAC.

Is this problem only going to be fixed on .NET Core 3?

```
Exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
```

**Comment by stephentoub** [comment]
I don't believe this is a bug in HttpClient.  Rather, the nasdaq site appears to be filtering requests based on request headers and refusing to handle requests without specific headers set.  If I modify the request in the repro to include a few additional headers (like are sent by browsers), the code passes successfully:
```C#
client.DefaultRequestHeaders.TryAddWithoutValidation("Accept", "text/html, application/xhtml+xml, application/xml; q=0.9, */*; q=0.8");
client.DefaultRequestHeaders.TryAddWithoutValidation("Accept-Language", "en-US");
```

**Comment by mayconbeserra** [comment]
Hi @stephentoub I have created another issue with my example: 

https://github.com/dotnet/corefx/issues/30989

**Comment by davidsh** [comment]
Closing this issue as by-design.
