### ISSUE TITLE
HttpClient unsupported compression method

### ISSUE THREAD

**Issue by Eilon** [dotnet/corefx#30992]
_From @moliveto on July 3, 2018 0:39_

I have a problem with HttpClient post.

System.IO.InvalidDataException
  HResult=0x80131501
  Message=The archive entry was compressed using an unsupported compression method.
  Source=System.IO.Compression
  StackTrace:
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.CopyToAsyncStream.<WriteAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpConnection.<CopyFromBufferAsync>d__98.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpConnection.<CopyToExactLengthAsync>d__101.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.<CompleteCopyToAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.Compression.DeflateStream.CopyToAsyncStream.<CopyFromSourceToDestination>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.DecompressionHandler.DecompressedContent.<SerializeToStreamAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__52.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__62.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

_Copied from original issue: aspnet/Home#3291_

**Comment by Eilon** [comment]
_From @Tratcher on July 3, 2018 5:17_

Doesn't this belong in dotnet/corefx?
What were the request and response headers? What server were you connecting to?

**Comment by Eilon** [comment]
_From @dhruval208 on July 7, 2018 18:10_

Have you used chilkat library to compress ?

**Comment by wfurt** [comment]
do you have repro code and instructions?

**Comment by karelz** [comment]
Is it on .NET Framework or on .NET Core? Which version? Which OS?

**Comment by davidsh** [comment]
@moliveto - We don't have any information to repro your issue.  We'll close this for now. But if you have a repro for this, we can re-open.  Thx.
