### ISSUE TITLE
Setting SendTimeout on CustomBinding on MacOS triggers NullReferenceException

### ISSUE THREAD

**Issue by AdamFrisby** [dotnet/corefx#31022]
Performing a WCF submission using a CustomBinding fails when SendTimeout is left uncommented on macOS in the following code:

Environment: .NET Core 2.0, (whatever is in Visual Studio 15.5.7); execution environment is OSX 10.14 latest beta. Using System.ServiceModel.NetTcp 4.5.2 via NuGet.

```
  var customBinding = new CustomBinding(new NetTcpBinding
              {
                  MaxReceivedMessageSize = maxMessageSize,
                  MaxBufferSize = Int32.MaxValue,
                  MaxBufferPoolSize = maxMessageSize,
                  ReceiveTimeout = TimeSpan.MaxValue,
                  //OpenTimeout = timeout,
                  SendTimeout = TimeSpan.MaxValue,
                  //CloseTimeout = timeout,
                  ReaderQuotas = XmlDictionaryReaderQuotas.Max,
                  Security =
                  {
                      Mode = SecurityMode.None,
                      Transport = {ClientCredentialType = TcpClientCredentialType.None}
                  },
                  TransferMode = TransferMode.Streamed
              });
```

Failure occurs as soon as you attempt to call a WCF method. Same code works on Windows (albeit that environment is using the standard .NET framework.)

Stack trace:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.ServiceModel.Channels.CoreClrSocketConnection.SetWriteTimeout(TimeSpan timeout, Boolean synchronous)
   at System.ServiceModel.Channels.CoreClrSocketConnection.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout, Action`1 callback, Object state)
   at System.ServiceModel.Channels.SocketConnection.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout, Action`1 callback, Object state)
   at System.ServiceModel.Channels.BufferedConnection.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout, Action`1 callback, Object state)
   at System.ServiceModel.Channels.ConnectionHelpers.IConnectionExtensions.<WriteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.StreamedFramingRequestChannel.<SendPreambleAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.ConnectionPoolHelper.<EstablishConnectionAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.StreamedFramingRequestChannel.StreamedConnectionPoolHelper.StreamedFramingAsyncRequest.<SendRequestAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.RequestChannel.<RequestAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.RequestChannel.<RequestAsyncInternal>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
   at generatedProxy_1.SendFile(SendProcessingRequest )
```

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/wcf #3017](https://github.com/dotnet/wcf/issues/3017) via [**ZenHub**](https://www.zenhub.com/)
