### ISSUE TITLE
Marshal.GetStartComSlot throws in .NET Core for int/string/int*

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#31068]
```cs
namespace System.Runtime.InteropServices.Tests
{
    public partial class GetStartComSlotTests
    {
        [Theory]
        [InlineData(typeof(int), -1)]
        [InlineData(typeof(string), -1)]
        [InlineData(typeof(NonGenericClass), -1)]
        [InlineData(typeof(NonGenericStruct), -1)]
        [InlineData(typeof(NonGenericInterface), 7)]
        [InlineData(typeof(int*), -1)]
        [PlatformSpecific(TestPlatforms.Windows)]
        public void GetStartComSlot_ValidType_ReturnsExpected(Type type, int expected)
        {
            Assert.Equal(expected, Marshal.GetStartComSlot(type));
        }
    }
}
```

> msbuild /T:BuildAndTest /P:TargetGroup=netfx

```
  ===========================================================================================================
  xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
    Discovering: System.Runtime.InteropServices.Tests
    Discovered:  System.Runtime.InteropServices.Tests
    Starting:    System.Runtime.InteropServices.Tests
    Finished:    System.Runtime.InteropServices.Tests
  === TEST EXECUTION SUMMARY ===
     System.Runtime.InteropServices.Tests  Total: 864, Errors: 0, Failed: 0, Skipped: 0, Time: 1.514s
  ----- end 10:04:14.54 ----- exit code 0 ----------------------------------------------------------
```

> msbuild /T:BuildAndTest /P:TargetGroup=netcoreapp

```
  ===========================================================================================================
  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.

  Discovering: System.Runtime.InteropServices.Tests
  Discovered:  System.Runtime.InteropServices.Tests
  Starting:    System.Runtime.InteropServices.Tests
     System.Runtime.InteropServices.Tests.GetStartComSlotTests.GetStartComSlot_ValidType_ReturnsExpected(type: typeof(i
  nt), expected: -1) [FAIL]
        System.ArgumentException : The specified type must be visible from COM.
        Parameter name: t
        Stack Trace:
              at System.Runtime.InteropServices.Marshal.GetStartComSlot(Type t)
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\GetStartComSlotTests.cs(25,0): at System.Runtime.InteropServices.Tests.GetStartComSlotTests.GetStartComSlo
  t_ValidType_ReturnsExpected(Type type, Int32 expected)
     System.Runtime.InteropServices.Tests.GetStartComSlotTests.GetStartComSlot_ValidType_ReturnsExpected(type: typeof(s
  tring), expected: -1) [FAIL]
        System.ArgumentException : The specified type must be visible from COM.
        Parameter name: t
        Stack Trace:
              at System.Runtime.InteropServices.Marshal.GetStartComSlot(Type t)
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\GetStartComSlotTests.cs(25,0): at System.Runtime.InteropServices.Tests.GetStartComSlotTests.GetStartComSlo
  t_ValidType_ReturnsExpected(Type type, Int32 expected)
     System.Runtime.InteropServices.Tests.GetStartComSlotTests.GetStartComSlot_ValidType_ReturnsExpected(type: typeof(S
  ystem.Int32*), expected: -1) [FAIL]
        System.ArgumentException : The specified type must be visible from COM.
        Parameter name: t
        Stack Trace:
              at System.Runtime.InteropServices.Marshal.GetStartComSlot(Type t)
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\GetStartComSlotTests.cs(25,0): at System.Runtime.InteropServices.Tests.GetStartComSlotTests.GetStartComSlo
  t_ValidType_ReturnsExpected(Type type, Int32 expected)
  Finished:    System.Runtime.InteropServices.Tests

  === TEST EXECUTION SUMMARY ===
C:\Users\hughb\Documents\GitHub\corefx\Tools\tests.targets(514,5): warning :    System.Runtime.InteropServices.Tests  T
otal: 883, Errors: 0, Failed: 3, Skipped: 0, Time: 1.614s [C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.In
teropServices\tests\System.Runtime.InteropServices.Tests.csproj]
  The previous error was converted to a warning because the task was called with ContinueOnError=true.
  ----- end 10:04:49.86 ----- exit code 1 ----------------------------------------------------------
```

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
The issue here is the removal of `[ComVisible(true)]` from various runtime types - see 55fe7d685a88bf837ac29fcf33375f285f7c8136. The check for this is in the depths of `srv/vm/interoputil.cpp` in my least favorite function: `SpecialIsGenericTypeVisibleFromCom()`.

The short answer here is that this is by-design since that is how the function is documented - even though it is different from .NET Framework.

@hughbe Can you special case these checks for coreclr vs .NET Framework?

**Comment by AaronRobinsonMSFT** [comment]
Closing this since the split behavior is desired.
