### ISSUE TITLE
Ansi marshalling for non-ansii chars on Unix is incorrect and does not match Windows/.NET Framework

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#31069]
```cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Linq;
using Xunit;

namespace System.Runtime.InteropServices.Tests
{
    public class StringToHGlobalAnsiTests
    {
        [Theory]
        [InlineData("")]
        [InlineData("pizza")]
        [InlineData("pepperoni")]
        [InlineData("password")]
        [InlineData("P4ssw0rdAa1")]
        [InlineData("\u1234")]
        [InlineData("\uD800")]
        [InlineData("\uD800\uDC00")]
        [InlineData("\0")]
        [InlineData("abc\0def")]
        public void StringToHGlobalAnsi_InvokePtrToStringAnsi_Roundtrips(string s)
        {
            string expectedFullString = new string(s.ToCharArray().Select(c => c > 0xFF ? '?' : c).ToArray());
            int nullIndex = expectedFullString.IndexOf('\0');
            string expectedParameterlessString = nullIndex == -1 ? expectedFullString : expectedFullString.Substring(0, nullIndex);

            IntPtr ptr = Marshal.StringToHGlobalAnsi(s);
            try
            {
                Assert.NotEqual(IntPtr.Zero, ptr);

                // Unix is incorrect with unicode chars.
                bool containsNonAnsiChars = s.Any(c => c > 0xFF);
                if (true)
                {
                    // Make sure the native memory is correctly laid out.
                    for (int i = 0; i < s.Length; i++)
                    {
                        Assert.Equal(expectedFullString[i], (char)Marshal.ReadByte(IntPtr.Add(ptr, i)));
                    }

                    // Make sure the native memory roundtrips.
                    Assert.Equal(expectedParameterlessString, Marshal.PtrToStringAnsi(ptr));
                    Assert.Equal(expectedFullString, Marshal.PtrToStringAnsi(ptr, s.Length));
                }
            }
            finally
            {
                Marshal.ZeroFreeGlobalAllocAnsi(ptr);
            }
        }
    }
}
```

```
  ----- start 10:08:39 =============== To repro directly: =====================================================
  pushd /Users/hugh/Documents/GitHub/corefx/bin/tests/System.Runtime.InteropServices.Tests/netcoreapp-OSX-Debug-x64
  chmod +x /Users/hugh/Documents/GitHub/corefx/bin/testhost/netcoreapp-OSX-Debug-x64//dotnet
  /Users/hugh/Documents/GitHub/corefx/bin/testhost/netcoreapp-OSX-Debug-x64//dotnet xunit.console.netcore.exe System.Runtime.InteropServices.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonosxtests  -notrait category=OuterLoop -notrait category=failing
  popd
  ===========================================================================================================
  ~/Documents/GitHub/corefx/bin/tests/System.Runtime.InteropServices.Tests/netcoreapp-OSX-Debug-x64 ~/Documents/GitHub/corefx/src/System.Runtime.InteropServices/tests
  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.

  Discovering: System.Runtime.InteropServices.Tests
  Discovered:  System.Runtime.InteropServices.Tests
  Starting:    System.Runtime.InteropServices.Tests
     System.Runtime.InteropServices.Tests.StringToHGlobalAnsiTests.StringToHGlobalAnsi_InvokePtrToStringAnsi_Roundtrips(s: \"ሴ\") [FAIL]
        Assert.Equal() Failure
        Expected: '?'
        Actual:   'á'
        Stack Trace:
           /Users/hugh/Documents/GitHub/corefx/src/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/Marshal/StringToHGlobalAnsiTests.cs(41,0): at System.Runtime.InteropServices.Tests.StringToHGlobalAnsiTests.StringToHGlobalAnsi_InvokePtrToStringAnsi_Roundtrips(String s)
     System.Runtime.InteropServices.Tests.StringToHGlobalAnsiTests.StringToHGlobalAnsi_InvokePtrToStringAnsi_Roundtrips(s: \"��\") [FAIL]
        Assert.Equal() Failure
        Expected: '?'
        Actual:   'ï'
        Stack Trace:
           /Users/hugh/Documents/GitHub/corefx/src/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/Marshal/StringToHGlobalAnsiTests.cs(41,0): at System.Runtime.InteropServices.Tests.StringToHGlobalAnsiTests.StringToHGlobalAnsi_InvokePtrToStringAnsi_Roundtrips(String s)
     System.Runtime.InteropServices.Tests.StringToHGlobalAnsiTests.StringToHGlobalAnsi_InvokePtrToStringAnsi_Roundtrips(s: \"𐀀\") [FAIL]
        Assert.Equal() Failure
        Expected: '?'
        Actual:   'ð'
        Stack Trace:
           /Users/hugh/Documents/GitHub/corefx/src/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/Marshal/StringToHGlobalAnsiTests.cs(41,0): at System.Runtime.InteropServices.Tests.StringToHGlobalAnsiTests.StringToHGlobalAnsi_InvokePtrToStringAnsi_Roundtrips(String s)
  Finished:    System.Runtime.InteropServices.Tests

  === TEST EXECUTION SUMMARY ===
/Users/hugh/Documents/GitHub/corefx/Tools/tests.targets(514,5): warning :    System.Runtime.InteropServices.Tests  Total: 737, Errors:0, Failed: 3, Skipped: 0, Time: 0.698s [/Users/hugh/Documents/GitHub/corefx/src/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.Tests.csproj]
  ~/Documents/GitHub/corefx/src/System.Runtime.InteropServices/tests
  ----- end 10:08:42 ----- exit code 1 ----------------------------------------------------------
/Users/hugh/Documents/GitHub/corefx/Tools/tests.targets(514,5): warning MSB3073: The command "/Users/hugh/Documents/GitHub/corefx/bin/tests/System.Runtime.InteropServices.Tests/netcoreapp-OSX-Debug-x64/RunTests.sh /Users/hugh/Documents/GitHub/corefx/bin/testhost/netcoreapp-OSX-Debug-x64/" exited with code 1. [/Users/hugh/Documents/GitHub/corefx/src/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.Tests.csproj]
/Users/hugh/Documents/GitHub/corefx/Tools/tests.targets(522,5): error : One or more tests failed while running tests from 'System.Runtime.InteropServices.Tests' please check /Users/hugh/Documents/GitHub/corefx/bin/tests/System.Runtime.InteropServices.Tests/netcoreapp-OSX-Debug-x64/testResults.xml for details! [/Users/hugh/Documents/GitHub/corefx/src/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.Tests.csproj]
```

**Comment by stephentoub** [comment]
By design. Ansi on Unix is UTF8.
