### ISSUE TITLE
Marshal.GetNativeVariantForObject throws ComException for various objects

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#31077]
```
 System.Runtime.InteropServices.Tests.GetNativeVariantForObjectTests.GetNativeVariantForObject_ValidObject_Success
  [FAIL]
        System.PlatformNotSupportedException : Operation is not supported on this platform.
        Stack Trace:
           E:\A\_work\104\s\src\System.Private.CoreLib\src\System\Runtime\InteropServices\Marshal.cs(1210,0): at System
  .Runtime.InteropServices.Marshal.GetIDispatchForObject(Object o)
           E:\A\_work\104\s\src\System.Private.CoreLib\src\System\Runtime\InteropServices\DispatchWrapper.cs(24,0): at
  System.Runtime.InteropServices.DispatchWrapper..ctor(Object obj)
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\GetNativeVariantForObjectTests.cs(121,0): at System.Runtime.InteropServices.Tests.GetNativeVariantForObjec
  tTests.GetNativeVariantForObject_NonRoundtrippingPrimitives_TestData()+MoveNext()
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Linq\src\System\Linq\Select.cs(129,0): at System.Linq.Enum
  erable.SelectEnumerableIterator`2.MoveNext()
     System.Runtime.InteropServices.Tests.GetNativeVariantForObjectTests.GetNativeVariantForObject_RoundtrippingPrimiti
  ves_Success(primitive: [00:00:00.0000010], expectedVarType: 8228, expectedValue: -1) [FAIL]
        System.Runtime.InteropServices.COMException : Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))
        Stack Trace:
              at System.Runtime.InteropServices.Marshal.GetNativeVariantForObject(Object obj, IntPtr pDstNativeVariant)
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\GetNativeVariantForObjectTests.cs(182,0): at System.Runtime.InteropServices.Tests.GetNativeVariantForObjec
  tTests.GetNativeVariantForObject_ValidObject_Success(Object primitive, VarEnum expectedVarType, IntPtr expectedValue,
   Object expectedRoundtripValue)
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\GetNativeVariantForObjectTests.cs(87,0): at System.Runtime.InteropServices.Tests.GetNativeVariantForObject
  Tests.GetNativeVariantForObject_RoundtrippingPrimitives_Success(Object primitive, VarEnum expectedVarType, IntPtr exp
  ectedValue)
     System.Runtime.InteropServices.Tests.GetNativeVariantForObjectTests.GetNativeVariantForObject_RoundtrippingPrimiti
  ves_Success(primitive: System.Runtime.InteropServices.Tests.GetNativeVariantForObjectTests+StructWithValue, expectedV
  arType: VT_RECORD, expectedValue: -1) [FAIL]
        System.Runtime.InteropServices.COMException : Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))
        Stack Trace:
              at System.Runtime.InteropServices.Marshal.GetNativeVariantForObject(Object obj, IntPtr pDstNativeVariant)
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\GetNativeVariantForObjectTests.cs(182,0): at System.Runtime.InteropServices.Tests.GetNativeVariantForObjec
  tTests.GetNativeVariantForObject_ValidObject_Success(Object primitive, VarEnum expectedVarType, IntPtr expectedValue,
   Object expectedRoundtripValue)
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\GetNativeVariantForObjectTests.cs(87,0): at System.Runtime.InteropServices.Tests.GetNativeVariantForObject
  Tests.GetNativeVariantForObject_RoundtrippingPrimitives_Success(Object primitive, VarEnum expectedVarType, IntPtr exp
  ectedValue)
     System.Runtime.InteropServices.Tests.GetNativeVariantForObjectTests.GetNativeVariantForObject_RoundtrippingPrimiti
  ves_Success(primitive: [System.Runtime.InteropServices.Tests.GetNativeVariantForObjectTests+StructWithValue, null], e
  xpectedVarType: 8204, expectedValue: -1) [FAIL]
        System.Runtime.InteropServices.COMException : Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))
        Stack Trace:
              at System.Runtime.InteropServices.Marshal.GetNativeVariantForObject(Object obj, IntPtr pDstNativeVariant)
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\GetNativeVariantForObjectTests.cs(182,0): at System.Runtime.InteropServices.Tests.GetNativeVariantForObjec
  tTests.GetNativeVariantForObject_ValidObject_Success(Object primitive, VarEnum expectedVarType, IntPtr expectedValue,
   Object expectedRoundtripValue)
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\GetNativeVariantForObjectTests.cs(87,0): at System.Runtime.InteropServices.Tests.GetNativeVariantForObject
  Tests.GetNativeVariantForObject_RoundtrippingPrimitives_Success(Object primitive, VarEnum expectedVarType, IntPtr exp
  ectedValue)
     System.Runtime.InteropServices.Tests.GetNativeVariantForObjectTests.GetNativeVariant_NotInteropCompatible_ThrowsAr
  gumentException(obj: [System.Runtime.InteropServices.Tests.Common.GenericStruct`1[System.String]]) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentException)
        Actual:   typeof(System.Runtime.InteropServices.COMException): Unspecified error (Exception from HRESULT: 0x800
  04005 (E_FAIL))
        Stack Trace:
              at System.Runtime.InteropServices.Marshal.GetNativeVariantForObject(Object obj, IntPtr pDstNativeVariant)
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\GetNativeVariantForObjectTests.cs(331,0): at System.Runtime.InteropServices.Tests.GetNativeVariantForObjec
  tTests.<>c__DisplayClass21_0.<GetNativeVariant_NotInteropCompatible_ThrowsArgumentException>b__0()
     System.Runtime.InteropServices.Tests.GetNativeVariantForObjectTests.GetNativeVariant_NotInteropCompatible_ThrowsAr
  gumentException(obj: []) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentException)
        Actual:   typeof(System.Runtime.InteropServices.COMException): Unspecified error (Exception from HRESULT: 0x800
  04005 (E_FAIL))
        Stack Trace:
              at System.Runtime.InteropServices.Marshal.GetNativeVariantForObject(Object obj, IntPtr pDstNativeVariant)
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\GetNativeVariantForObjectTests.cs(331,0): at System.Runtime.InteropServices.Tests.GetNativeVariantForObjec
  tTests.<>c__DisplayClass21_0.<GetNativeVariant_NotInteropCompatible_ThrowsArgumentException>b__0()
     System.Runtime.InteropServices.Tests.GetNativeVariantForObjectTests.GetNativeVariant_NotInteropCompatible_ThrowsAr
  gumentException(obj: [System.Runtime.InteropServices.Tests.Common.GenericStruct`1[System.String]]) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentException)
        Actual:   typeof(System.Runtime.InteropServices.COMException): Unspecified error (Exception from HRESULT: 0x800
  04005 (E_FAIL))
        Stack Trace:
              at System.Runtime.InteropServices.Marshal.GetNativeVariantForObject(Object obj, IntPtr pDstNativeVariant)
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\GetNativeVariantForObjectTests.cs(331,0): at System.Runtime.InteropServices.Tests.GetNativeVariantForObjec
  tTests.<>c__DisplayClass21_0.<GetNativeVariant_NotInteropCompatible_ThrowsArgumentException>b__0()
     System.Runtime.InteropServices.Tests.GetNativeVariantForObjectTests.GetNativeVariant_NotInteropCompatible_ThrowsAr
  gumentException(obj: []) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentException)
        Actual:   typeof(System.Runtime.InteropServices.COMException): Unspecified error (Exception from HRESULT: 0x800
  04005 (E_FAIL))
        Stack Trace:
              at System.Runtime.InteropServices.Marshal.GetNativeVariantForObject(Object obj, IntPtr pDstNativeVariant)
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\GetNativeVariantForObjectTests.cs(331,0): at System.Runtime.InteropServices.Tests.GetNativeVariantForObjec
  tTests.<>c__DisplayClass21_0.<GetNativeVariant_NotInteropCompatible_ThrowsArgumentException>b__0()
     System.Runtime.InteropServices.Tests.GetNativeVariantForObjectTests.GetNativeVariant_NotInteropCompatible_ThrowsAr
  gumentException(obj: [Color [A=0, R=0, G=0, B=10]]) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentException)
        Actual:   typeof(System.Runtime.InteropServices.COMException): Unspecified error (Exception from HRESULT: 0x800
  04005 (E_FAIL))
        Stack Trace:
              at System.Runtime.InteropServices.Marshal.GetNativeVariantForObject(Object obj, IntPtr pDstNativeVariant)
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\GetNativeVariantForObjectTests.cs(331,0): at System.Runtime.InteropServices.Tests.GetNativeVariantForObjec
  tTests.<>c__DisplayClass21_0.<GetNativeVariant_NotInteropCompatible_ThrowsArgumentException>b__0()
     System.Runtime.InteropServices.Tests.GetNativeVariantForObjectTests.GetNativeVariantForObject_WrappedComObject_Suc
  cess [FAIL]
        System.PlatformNotSupportedException : Operation is not supported on this platform.
        Stack Trace:
           E:\A\_work\104\s\src\System.Private.CoreLib\src\System\Runtime\InteropServices\Marshal.cs(1210,0): at System
  .Runtime.InteropServices.Marshal.GetIDispatchForObject(Object o)
           E:\A\_work\104\s\src\System.Private.CoreLib\src\System\Runtime\InteropServices\DispatchWrapper.cs(24,0): at
  System.Runtime.InteropServices.DispatchWrapper..ctor(Object obj)
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\GetNativeVariantForObjectTests.Windows.cs(83,0): at System.Runtime.InteropServices.Tests.GetNativeVariantF
  orObjectTests.GetNativeVariantForObject_WrappedComObject_TestData()+MoveNext()
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Linq\src\System\Linq\Select.cs(129,0): at System.Linq.Enum
  erable.SelectEnumerableIterator`2.MoveNext()
  Finished:    System.Runtime.InteropServices.Tests

  === TEST EXECUTION SUMMARY ===
C:\Users\hughb\Documents\GitHub\corefx\Tools\tests.targets(514,5): warning :    System.Runtime.InteropServices.Tests  T
otal: 1078, Errors: 0, Failed: 10, Skipped: 0, Time: 4.000s [C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.
InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
  The previous error was converted to a warning because the task was called with ContinueOnError=true.
  ----- end 21:33:02.53 ----- exit code 1 ----------------------------------------------------------
C:\Users\hughb\Documents\GitHub\corefx\Tools\tests.targets(514,5): warning MSB3073: The command "C:\Users\hughb\Documen
ts\GitHub\corefx\bin/tests/System.Runtime.InteropServices.Tests/netcoreapp-Windows_NT-Debug-x64//RunTests.cmd C:\Users\
hughb\Documents\GitHub\corefx\bin/testhost/netcoreapp-Windows_NT-Debug-x64/" exited with code 1. [C:\Users\hughb\Docume
nts\GitHub\corefx\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
  The previous error was converted to a warning because the task was called with ContinueOnError=true.
  Build continuing because "ContinueOnError" on the task "Exec" is set to "true".
C:\Users\hughb\Documents\GitHub\corefx\Tools\tests.targets(522,5): error : One or more tests failed while running tests
 from 'System.Runtime.InteropServices.Tests' please check C:\Users\hughb\Documents\GitHub\corefx\bin/tests/System.Runti
me.InteropServices.Tests/netcoreapp-Windows_NT-Debug-x64/testResults.xml for details! [C:\Users\hughb\Documents\GitHub\
corefx\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
Done Building Project "C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System.Runtime.I
nteropServices.Tests.csproj" (BuildAndTest target(s)) -- FAILED.


Build FAILED.

"C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.c
sproj" (BuildAndTest target) (1) ->
(RunTestsForProject target) ->
  C:\Users\hughb\Documents\GitHub\corefx\Tools\tests.targets(514,5): warning :    System.Runtime.InteropServices.Tests
 Total: 1078, Errors: 0, Failed: 10, Skipped: 0, Time: 4.000s [C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtim
e.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
  C:\Users\hughb\Documents\GitHub\corefx\Tools\tests.targets(514,5): warning MSB3073: The command "C:\Users\hughb\Docum
ents\GitHub\corefx\bin/tests/System.Runtime.InteropServices.Tests/netcoreapp-Windows_NT-Debug-x64//RunTests.cmd C:\User
s\hughb\Documents\GitHub\corefx\bin/testhost/netcoreapp-Windows_NT-Debug-x64/" exited with code 1. [C:\Users\hughb\Docu
ments\GitHub\corefx\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]


"C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.c
sproj" (BuildAndTest target) (1) ->
(RunTestsForProject target) ->
  C:\Users\hughb\Documents\GitHub\corefx\Tools\tests.targets(522,5): error : One or more tests failed while running tes
ts from 'System.Runtime.InteropServices.Tests' please check C:\Users\hughb\Documents\GitHub\corefx\bin/tests/System.Run
time.InteropServices.Tests/netcoreapp-Windows_NT-Debug-x64/testResults.xml for details! [C:\Users\hughb\Documents\GitHu
b\corefx\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]

    2 Warning(s)
    1 Error(s)

Time Elapsed 00:00:15.06
```

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT

**Comment by hughbe** [comment]
0x80004005 | E_FAIL | Unspecified failure
-- | -- | --

**Comment by AaronRobinsonMSFT** [comment]
@hughbe These are failing on corefx or some other flavor? How are you running the tests to cause the failure?

Thanks.

**Comment by hughbe** [comment]
In this PR: https://github.com/dotnet/corefx/pull/31057 I added a bunch of `GetNativeVariantForObject` tests. They pass with netfx but fail with netcoreapp.
