### ISSUE TITLE
System.Drawing.Printing.InvalidPrinterException : No printers are installed.

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#31221]
System.Drawing.Printing.Tests.PrintDocumentTests/EndPrint_SetValue_ReturnsExpected test failed in https://github.com/dotnet/corefx/pull/31218 on Windows.10.Amd64.ClientRS4.ES.Open-x86-Release

```
Unhandled Exception of Type System.Drawing.Printing.InvalidPrinterException`

Message :
System.Drawing.Printing.InvalidPrinterException : No printers are installed.
Stack Trace :
   at System.Drawing.Printing.PrinterSettings.GetHdevmodeInternal(String printer) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Drawing.Common\src\System\Drawing\Printing\PrinterSettings.Windows.cs:line 881
   at System.Drawing.Printing.PrintController.OnStartPrint(PrintDocument document, PrintEventArgs e) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Drawing.Common\src\System\Drawing\Printing\PrintController.Windows.cs:line 275
   at System.Drawing.Printing.Tests.PrintDocumentTests.TestPrintController.OnStartPrint(PrintDocument document, PrintEventArgs e) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Drawing.Common\tests\Printing\PrintDocumentTests.cs:line 274
   at System.Drawing.Printing.PrintController.Print(PrintDocument document) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Drawing.Common\src\System\Drawing\Printing\PrintController.Windows.cs:line 116
   at System.Drawing.Printing.Tests.PrintDocumentTests.EndPrint_SetValue_ReturnsExpected() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Drawing.Common\tests\Printing\PrintDocumentTests.cs:line 187
```

**Comment by danmosemsft** [comment]
Yes I saw that but the fix is not obvious because this test is already conditionalized on
```c#
        public static bool IsAnyInstalledPrinters()
        {
            return PrinterSettings.InstalledPrinters.Count > 0;
        }
```

So EnumPrinters says there's a printer but DocumentProperties later fails. This would need debugging, or some tracing added.

**Comment by ViktorHofer** [comment]
Maybe someone plugged in a printer between both calls 😂 sorry I couldn't resist.

**Comment by wfurt** [comment]
Should we close this one? It is pretty old and I have not seen recent failures.
