### ISSUE TITLE
[Question] Loading the correct runtime libraries with AssemblyLoadContext

### ISSUE THREAD

**Issue by Cyberboss** [dotnet/corefx#31369]
### Figured out it was the incorrect runtime library being loaded. Skip to third post

What it says on the tin basically. If you try to access Registry.LocalMachine from an assembly loaded from a custom AssemblyLoadContext it will be null.

Here's a quick demo repository: https://github.com/Cyberboss/RegistryAlcBugDemo2

Note in order to run the `AlcReference` project, which demonstrates the bug, you need to `dotnet publish` the `BaseClass` project to a folder called `lib` in the output directory of `AlcReference`

Here's step by step instructions in case that isn't clear
```
git clone https://github.com/Cyberboss/RegistryAlcBugDemo2
cd RegistryAlcBugDemo2
dotnet build
cd BaseClass
dotnet publish -o ../AlcReference/bin/Debug/netcoreapp2.0/lib
cd ../AlcReference/bin/Debug/netcoreapp2.0
dotnet AlcReference.dll
cd ../../../../DirectReference/bin/Debug/netcoreapp2.0
dotnet DirectReference.dll
```

Registry.LocalMachine will be null in the `AlcReference` project (which loads `BaseClass` dynamically via an `AssemblyLoadContext`. It will work fine for the DirectReference project which uses a project reference to BaseClass

This was discovered while attempting to run an AspNetCore.Mvc project in a near identical custom assembly load context which spits out the following:

```
info: Tgstation.Server.Host.Watchdog.Watchdog[0]
      Host watchdog starting...
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[3]
      Hosting starting
Application startup exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.DataProtection.RegistryPolicyResolver.<>c.<.ctor>b__2_0()
   at Microsoft.AspNetCore.DataProtection.RegistryPolicyResolver.ResolvePolicy()
   at Microsoft.AspNetCore.DataProtection.Internal.KeyManagementOptionsSetup.Configure(KeyManagementOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager..ctor(IOptions`1 keyManagementOptions, IActivator activator, ILoggerFactory loggerFactory)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.DataProtection.RegistryPolicyResolver.<>c.<.ctor>b__2_0()
   at Microsoft.AspNetCore.DataProtection.RegistryPolicyResolver.ResolvePolicy()
   at Microsoft.AspNetCore.DataProtection.Internal.KeyManagementOptionsSetup.Configure(KeyManagementOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager..ctor(IOptions`1 keyManagementOptions, IActivator activator, ILoggerFactory loggerFactory)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[5]
      Hosting shutdown
```

Discovered while trying to implement dynamic updates for this project: https://github.com/tgstation/tgstation-server/commit/944970d796e34bcb076145c4cda0bda87d75efff

If you care to try and debug that you have to do the same manual `dotnet publish`ing I outlined above where:
AlcReference = Tgstation.Server.Host.Console (Startup project)
BaseClass = Tgstation.Server.Host

And instead of publishing to `lib` it must be published to `lib/Default`

The exception is thrown on this line: https://github.com/aspnet/DataProtection/blob/2.1.1/src/Microsoft.AspNetCore.DataProtection/RegistryPolicyResolver.cs#L27
The call in my project that triggers it is on this line: https://github.com/tgstation/tgstation-server/blob/944970d796e34bcb076145c4cda0bda87d75efff/src/Tgstation.Server.Host/Server.cs#L65
And the exception is caught here: https://github.com/tgstation/tgstation-server/blob/944970d796e34bcb076145c4cda0bda87d75efff/src/Tgstation.Server.Host.Watchdog/Watchdog.cs#L87

dotnet 2.1.201
Windows 10 1803 17134.165 x64

**Comment by Cyberboss** [comment]
Further tinkering: I updated the test project to dump assembly info and try to load the key manually. Here are the results:

DirectReference:
```
Using Microsoft.Win32.Registry, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a at C:\Users\jordan\.nuget\packages\microsoft.win32.registry\4.5.0\runtimes\win\lib\netstandard2.0\Microsoft.Win32.Registry.dll
LocalMachine is not null!
Successfully opened registry key manually!
```
AlcReference:
```
Using Microsoft.Win32.Registry, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a at C:\Users\<--->\Source\Repos\AlcReference\bin\Debug\netcoreapp2.0\lib\Microsoft.Win32.Registry.dll
LocalMachine is null!
System.PlatformNotSupportedException: Registry is not supported on this platform.
   at Microsoft.Win32.RegistryKey.OpenBaseKey(RegistryHive hKey, RegistryView view)
   at BaseClass.BaseClass.Test() in C:\Users\<--->\Source\Repos\BaseClass\BaseClass.cs:line 21
```

**Comment by Cyberboss** [comment]
More tinkering shows the correct results for `AlcReference` iff I copy the assembly at `AlcReference\bin\Debug\netcoreapp2.0\lib\runtimes\win\lib\netstandard2.0` and overwrite the one at `AlcReference\bin\Debug\netcoreapp2.0\lib`

Could I get some suggestions for how to do the equivalent of this inside my assembly load context?

**Comment by Cyberboss** [comment]
Closely related to https://github.com/dotnet/coreclr/issues/7812
