### ISSUE TITLE
ExceptionDispatchInfo.Throw mutates stack trace every time it's called

### ISSUE THREAD

**Issue by pakrym** [dotnet/corefx#31371]
If `ExceptionDispatchInfo.Throw` is used instead of the usual pattern of `Capture-Throw` and it gets rethrown multiple times stack trace would get appended for every `Throw` call.

Repro:

```
try
{
    throw new Exception();
}
catch (Exception ex)
{
    exception = ex;
}

while (true)
{
    try
    {
        ExceptionDispatchInfo.Throw(exception);
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.ToString());
    }
}

```

cc @stephentoub

**Comment by stephentoub** [comment]
This is by design.

**Comment by benaadams** [comment]
The stack trace doesn't get duplicated, it only appends the `Throw` line to the exception; as that is a new location:

```csharp
void Main()
{
	Exception exception;
	try
	{
		throw new Exception();
	}
	catch (Exception ex)
	{
		exception = ex;
	}
	
	var throwCount = 1;
	while (true)
	{
		try
		{
			var edi = ExceptionDispatchInfo.Capture(exception);
			throwCount++;
			edi.Throw();
		}
		catch (Exception ex)
		{
			Console.WriteLine($"*** Throw count: {throwCount}");
			Console.WriteLine(ex.ToString());
		}
	}
}
```
outputs
```
*** Throw count: 2
System.Exception: Exception of type 'System.Exception' was thrown.
   at UserQuery.Main() in C:\Users\thund\AppData\Local\Temp\LINQPad5\_pmnrhntn\query_yeavta.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at UserQuery.Main() in C:\Users\thund\AppData\Local\Temp\LINQPad5\_pmnrhntn\query_yeavta.cs:line 49
*** Throw count: 3
System.Exception: Exception of type 'System.Exception' was thrown.
   at UserQuery.Main() in C:\Users\thund\AppData\Local\Temp\LINQPad5\_pmnrhntn\query_yeavta.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at UserQuery.Main() in C:\Users\thund\AppData\Local\Temp\LINQPad5\_pmnrhntn\query_yeavta.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at UserQuery.Main() in C:\Users\thund\AppData\Local\Temp\LINQPad5\_pmnrhntn\query_yeavta.cs:line 49
*** Throw count: 4
System.Exception: Exception of type 'System.Exception' was thrown.
   at UserQuery.Main() in C:\Users\thund\AppData\Local\Temp\LINQPad5\_pmnrhntn\query_yeavta.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at UserQuery.Main() in C:\Users\thund\AppData\Local\Temp\LINQPad5\_pmnrhntn\query_yeavta.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at UserQuery.Main() in C:\Users\thund\AppData\Local\Temp\LINQPad5\_pmnrhntn\query_yeavta.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at UserQuery.Main() in C:\Users\thund\AppData\Local\Temp\LINQPad5\_pmnrhntn\query_yeavta.cs:line 49
*** Throw count: 5
System.Exception: Exception of type 'System.Exception' was thrown.
   at UserQuery.Main() in C:\Users\thund\AppData\Local\Temp\LINQPad5\_pmnrhntn\query_yeavta.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at UserQuery.Main() in C:\Users\thund\AppData\Local\Temp\LINQPad5\_pmnrhntn\query_yeavta.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at UserQuery.Main() in C:\Users\thund\AppData\Local\Temp\LINQPad5\_pmnrhntn\query_yeavta.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at UserQuery.Main() in C:\Users\thund\AppData\Local\Temp\LINQPad5\_pmnrhntn\query_yeavta.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at UserQuery.Main() in C:\Users\thund\AppData\Local\Temp\LINQPad5\_pmnrhntn\query_yeavta.cs:line 49
```

**Comment by pakrym** [comment]
@stephentoub is calling `Throw()` on the same `Exception` object using different instances `ExceptionDispatchInfo` thread safe?

**Comment by stephentoub** [comment]
Yes. But of course the resulting stack trace could be confusing, with frames from diffetent locations appended to the same instance.
