### ISSUE TITLE
HTTP2: Assert failures when disallowed frame types are send on stream 0

### ISSUE THREAD

**Issue by rmkerr** [dotnet/corefx#31394]
The HTTP/2 spec explicitly forbids data frames to be sent on stream 0. From [section 6.1](https://tools.ietf.org/html/rfc7540#section-6.1) of the spec:
```
DATA frames MUST be associated with a stream.  If a DATA frame is
   received whose stream identifier field is 0x0, the recipient MUST
   respond with a connection error (Section 5.4.1) of type
   PROTOCOL_ERROR.
``` 

The current HTTP/2 implementation does not respond with PROTOCOL_ERROR when a data frame is sent on stream 0, and instead fails an assert in HttpConnectionPool.cs without sending a response:
https://github.com/dotnet/corefx/blob/f391820c4808bcb02c7b3dd88b684f36a0a98b6a/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L861-L865

<details>
<summary>Full stack trace of the assert:</summary>

     Assertion Failed
     at System.Net.Http.HttpConnectionPool.InvalidateHttp2Connection(Http2Connection connection) in C:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 863
     at System.Net.Http.Http2Connection.AbortStreams(Int32 lastValidStream) in C:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 503
     at System.Net.Http.Http2Connection.ProcessIncomingFrames() in C:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 155
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 930
     at System.Net.Http.Http2Connection.ProcessIncomingFrames()
     at System.Net.Http.Http2Connection.SetupAsync() in C:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 98
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\41\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 166
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 559
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\TaskContinuation.cs:line 798
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\Task.cs:line 3272
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\future.cs:line 421
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 639
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 629
     at System.Net.Http.Http2Connection.ReadFrameAsync() in C:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 138
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\41\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 166
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 559
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\TaskContinuation.cs:line 798
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\Task.cs:line 3272
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\future.cs:line 421
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 639
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult() in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 254
     at System.Net.Http.Http2Connection.EnsureIncomingBytesAsync(Int32 minReadBytes) in C:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 112
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\41\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 166
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 559
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\TaskContinuation.cs:line 798
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\Task.cs:line 3272
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\future.cs:line 421
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 639
     at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncValueTaskMethodBuilder.cs:line 169
     at System.Net.Http.Http2Connection.ReadAtLeastAsync(Stream stream, Memory`1 buffer, Int32 minReadBytes) in C:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 1278
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\41\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 166
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 559
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\TaskContinuation.cs:line 798
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\Task.cs:line 3272
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\future.cs:line 421
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 639
     at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncValueTaskMethodBuilder.cs:line 169
     at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer) in C:\corefx\src\System.Net.Security\src\System\Net\Security\SslStreamInternal.cs:line 338
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\41\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 166
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 559
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\TaskContinuation.cs:line 798
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\Task.cs:line 3272
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\future.cs:line 421
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 639
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 629
     at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial) in C:\corefx\src\System.Net.Security\src\System\Net\Security\SslStreamInternal.cs:line 515
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\41\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 166
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 559
     at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync) in C:\corefx\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs:line 1038
     at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _) in C:\corefx\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs:line 869
     at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags) in C:\corefx\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.cs:line 770
     at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__174_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in C:\corefx\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.Windows.cs:line 1195
     at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Overlapped.cs:line 65
</details>

cc: @geoffkizer

**Comment by geoffkizer** [comment]
InvalidateHttp2Connection must be getting called more than once, not sure why.  We should ensure it only gets called once.

**Comment by rmkerr** [comment]
This issue is actually more complex than I initially thought. When I initially hit this assert, there was also a bug in the HTTP2 loopback server causing the HTTP2 connection preface to be sent incorrectly. When the preface is sent correctly, we don't hit the assert. Before you spend more time on this, let me isolate the exact conditions that caused this assert.
