### ISSUE TITLE
Error try to publish a newly created ASP Core 2.1 app

### ISSUE THREAD

**Issue by MikeHowellTransferenceLtdCoUk** [dotnet/corefx#31417]
Hi there,

I have a technically simple Core 2.1 App which uses MVC and currently SQL .Express via EF Core.

I have followed the create app service wizard but part way through deployment I receive the following error:

System.Net.Http.HttpRequestException
   at Microsoft.VisualStudio.Web.WindowsAzure.Provisioning.DeploymentManager.<ThrowOnUnexpectedStatusCode>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Client.ARMCaller.HttpResponseExtensions.<DeserializeEntityJsonAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Client.ARMCaller.EntityExtensions.<ReloadAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.Web.WindowsAzure.Provisioning.DeploymentManager.<BeginDeployment>d__14.MoveNext()

Since this refers to internal calls at Azure, I can't make neither head-nor=tail of it

Oh, if I try advanced settings, self contain and x64 bit it seems to begin publishing but I then receive

C:\Program Files\dotnet\sdk\2.1.302\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): Warning : Retrying the sync because a socket error (10054) occurred.  

Kind regards
Mike Howell

**Comment by karelz** [comment]
It does not seem to be related to CoreFX. Looks like a problem in VS.
Create a small repro you can share, test it on another machine/VM, then file a report via VS feedback: [VS Developer Community Portal](https://developercommunity.visualstudio.com)
