### ISSUE TITLE
Seemingly nothing can stop Webclient.DownloadAsync()

### ISSUE THREAD

**Issue by Cyberboss** [dotnet/corefx#31484]
Take this sample
```c#
byte[] data;
using (var wc = new WebClient())
using (var cts = new CancellationTokenSource())
try
{
        var cancellationToken = cts.Token;
        cts.Cancel();
	var tcs = new TaskCompletionSource<byte[]>();
	wc.DownloadDataCompleted += (a, b) =>
	{
		if (b.Error != null)
			tcs.TrySetException(b.Error);
		else if (b.Cancelled)
			tcs.TrySetCanceled();
		else
			tcs.TrySetResult(b.Result);
	};
	wc.DownloadDataAsync(url);
	using (cancellationToken.Register(() =>
	{
		wc.CancelAsync();
		tcs.SetCanceled();  //optionally comment out this line
	}))
		data = await tcs.Task.ConfigureAwait(false);
} //wc disposed!
catch(OperationCancelledException) { }
await Task.Delay(9999).ConfigureAwait(false);
```

Set url to [some big file](http://ipv4.download.thinkbroadband.com/50MB.zip) and run the program. Open performance monitor quick enough and sure enough you can see that dotnet.exe is still eating network usage despite webclient being both cancelled disposed! If you comment out the `tcs.SetCanceled();` line you can see that it will always block until the download is complete (or the connection breaks) and then and only the run the event handler with `b.Cancelled` set

**Comment by stephentoub** [comment]
@Cyberboss, I tried your repro, commenting out the `tcs.SetCanceled();` line, and I get:
```
Unhandled Exception: System.Net.WebException: The request was aborted: The request was canceled.
   at System.Net.HttpWebRequest.CheckAbort()
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.GetWebResponseTaskAsync(WebRequest request)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   at ConsoleApp3.Program.Main(String[] args)
   at ConsoleApp3.Program.<Main>(String[] args)
```

**Comment by Cyberboss** [comment]
Yeah I recently upgraded from 2.0 to 2.1 and the problem seems to be gone

**Comment by stephentoub** [comment]
Excellent.  Thanks for confirming.
