### ISSUE TITLE
msbuild /T:BuildAndTest /P:TargetGroup=netfx throws PNSE with Ref-Emit

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#31485]
Running `msbuild /T:BuildAndTest /P:TargetGroup=netfx` causes a PNSE to be thrown in the following example:
```cs
public static IEnumerable<object[]> InvalidBool_TestData()
{
    if (PlatformDetection.IsReflectionEmitSupported)
    {
        object floatEnum = null;
        try
        {
            floatEnum = FloatEnum;
        }
        catch (PlatformNotSupportedException)
        {
            yield break;
        }

        yield return new object[] { floatEnum };
        yield return new object[] { DoubleEnum };
        yield return new object[] { BoolEnum };
        yield return new object[] { CharEnum };
        yield return new object[] { IntPtrEnum };
        yield return new object[] { UIntPtrEnum };
    }
}
private static object s_floatEnum;

public static object FloatEnum
{
    get
    {
        if (s_floatEnum == null)
        {
            AssemblyBuilder assembly = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("Name"), AssemblyBuilderAccess.RunAndCollect);
            ModuleBuilder module = assembly.DefineDynamicModule("Name");

            EnumBuilder eb = module.DefineEnum("CharEnumType", TypeAttributes.Public, typeof(float));
            eb.DefineLiteral("A", 1.0f);
            eb.DefineLiteral("B", 2.0f);
            eb.DefineLiteral("C", 3.0f);

            s_floatEnum = Activator.CreateInstance(eb.CreateTypeInfo());
        }

        return s_floatEnum;
    }
}

private static object s_doubleEnum;

public static object DoubleEnum
{
    get
    {
        if (s_doubleEnum == null)
        {
            AssemblyBuilder assembly = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("Name"), AssemblyBuilderAccess.RunAndCollect);
            ModuleBuilder module = assembly.DefineDynamicModule("Name");

            EnumBuilder eb = module.DefineEnum("CharEnumType", TypeAttributes.Public, typeof(double));
            eb.DefineLiteral("A", 1.0);
            eb.DefineLiteral("B", 2.0);
            eb.DefineLiteral("C", 3.0);

            s_doubleEnum = Activator.CreateInstance(eb.CreateTypeInfo());
        }

        return s_doubleEnum;
    }
}

private static object s_boolEnum;

public static object BoolEnum
{
    get
    {
        if (s_boolEnum == null)
        {
            AssemblyBuilder assembly = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("Name"), AssemblyBuilderAccess.RunAndCollect);
            ModuleBuilder module = assembly.DefineDynamicModule("Name");

            EnumBuilder eb = module.DefineEnum("BoolEnumType", TypeAttributes.Public, typeof(bool));
            eb.DefineLiteral("False", false);
            eb.DefineLiteral("True", true);

            s_boolEnum = Activator.CreateInstance(eb.CreateTypeInfo());
        }

        return s_boolEnum;
    }
}

private static object s_charEnum;

public static object CharEnum
{
    get
    {
        if (s_charEnum == null)
        {
            AssemblyBuilder assembly = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("Name"), AssemblyBuilderAccess.RunAndCollect);
            ModuleBuilder module = assembly.DefineDynamicModule("Name");

            EnumBuilder eb = module.DefineEnum("CharEnumType", TypeAttributes.Public, typeof(char));
            eb.DefineLiteral("A", 'A');
            eb.DefineLiteral("B", 'B');
            eb.DefineLiteral("C", 'C');

            s_charEnum = Activator.CreateInstance(eb.CreateTypeInfo());
        }

        return s_charEnum;
    }
}

private static object s_intPtrEnum;

public static object IntPtrEnum
{
    get
    {
        if (s_intPtrEnum == null)
        {
            AssemblyBuilder assembly = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("Name"), AssemblyBuilderAccess.RunAndCollect);
            ModuleBuilder module = assembly.DefineDynamicModule("Name");

            EnumBuilder eb = module.DefineEnum("CharEnumType", TypeAttributes.Public, typeof(IntPtr));

            s_intPtrEnum = Activator.CreateInstance(eb.CreateTypeInfo());
        }

        return s_intPtrEnum;
    }
}

private static object s_uintPtrEnum;

public static object UIntPtrEnum
{
    get
    {
        if (s_uintPtrEnum == null)
        {
            AssemblyBuilder assembly = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("Name"), AssemblyBuilderAccess.RunAndCollect);
            ModuleBuilder module = assembly.DefineDynamicModule("Name");

            EnumBuilder eb = module.DefineEnum("CharEnumType", TypeAttributes.Public, typeof(UIntPtr));

            s_uintPtrEnum = Activator.CreateInstance(eb.CreateTypeInfo());
        }

        return s_uintPtrEnum;
    }
}
```

**Comment by danmosemsft** [comment]
What is the callstack?

**Comment by hughbe** [comment]
Sure
```
RunTestsForProject:
  C:\Users\hughb\Documents\GitHub\corefx\bin/tests/Microsoft.VisualBasic.Tests/netfx-Windows_NT-Debug-x64//RunTests.cmd
   C:\Users\hughb\Documents\GitHub\corefx\bin/testhost/netfx-Windows_NT-Debug-x64/
  Using C:\Users\hughb\Documents\GitHub\corefx\bin\testhost\netfx-Windows_NT-Debug-x64\ as the test runtime folder.
  Executing in C:\Users\hughb\Documents\GitHub\corefx\bin\tests\Microsoft.VisualBasic.Tests\netfx-Windows_NT-Debug-x64\

  ----- start  0:03:19.55 ===============  To repro directly: =====================================================
  pushd C:\Users\hughb\Documents\GitHub\corefx\bin\tests\Microsoft.VisualBasic.Tests\netfx-Windows_NT-Debug-x64\
  set DEVPATH=C:\Users\hughb\Documents\GitHub\corefx\bin\testhost\netfx-Windows_NT-Debug-x64\
  call xunit.console.exe Microsoft.VisualBasic.Tests.dll  -noshadow -xml testResults.xml -notrait Benchmark=true -notra
  it category=nonnetfxtests -notrait category=nonwindowstests  -notrait category=OuterLoop -notrait category=failing
  popd
  ===========================================================================================================
  xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
    Discovering: Microsoft.VisualBasic.Tests
    Discovered:  Microsoft.VisualBasic.Tests
    Starting:    Microsoft.VisualBasic.Tests
      Microsoft.VisualBasic.Tests.ConversionsTests.ToSingle_InvalidObject_ThrowsInvalidCastException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_CharEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidNumberObject_TestData>d__5.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToShort_Object_ReturnsExpected [FAIL]
      Microsoft.VisualBasic.Tests.ConversionsTests.ToSByte_InvalidBool_ThrowsInvalidOperationException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_BoolEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<ToShort_Object_TestData>d__44.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_FloatEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidBool_TestData>d__4.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToSingle_InvalidBool_ThrowsInvalidOperationException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_FloatEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidBool_TestData>d__4.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToBoolean_InvalidObject_ThrowsInvalidCastException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_CharEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidNumberObject_TestData>d__5.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToSByte_InvalidObject_ThrowsInvalidCastException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_CharEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidNumberObject_TestData>d__5.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToInteger_InvalidBool_ThrowsInvalidOperationException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_FloatEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidBool_TestData>d__4.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToSingle_Object_ReturnsExpected [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_BoolEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<ToSingle_Object_TestData>d__102.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToBoolean_Object_ReturnsExpected [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_BoolEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<ToBoolean_Object_TestData>d__133.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToDouble_Object_ReturnsExpected [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_BoolEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<ToDouble_Object_TestData>d__111.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToUShort_InvalidBool_ThrowsInvalidOperationException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_FloatEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidBool_TestData>d__4.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToLong_InvalidBool_ThrowsInvalidOperationException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_FloatEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidBool_TestData>d__4.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToUInteger_InvalidBool_ThrowsInvalidOperationException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_FloatEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidBool_TestData>d__4.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToUInteger_Object_ReturnsExpected [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_BoolEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<ToUInteger_Object_TestData>d__55.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToUShort_Object_ReturnsExpected [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_BoolEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<ToUShort_Object_TestData>d__33.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToByte_InvalidObject_ThrowsInvalidCastException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_CharEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidNumberObject_TestData>d__5.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToShort_InvalidBool_ThrowsInvalidOperationException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_FloatEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidBool_TestData>d__4.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToDecimal_Object_ReturnsExpected [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_BoolEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<ToDecimal_Object_TestData>d__122.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToBoolean_InvalidBool_ThrowsInvalidOperationException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_FloatEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidBool_TestData>d__4.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToLong_InvalidObject_ThrowsInvalidCastException [FAIL]
      Microsoft.VisualBasic.Tests.ConversionsTests.ToByte_InvalidBool_ThrowsInvalidOperationException [FAIL]
      Microsoft.VisualBasic.Tests.ConversionsTests.ToUShort_InvalidObject_ThrowsInvalidCastException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_CharEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidNumberObject_TestData>d__5.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_FloatEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidBool_TestData>d__4.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_CharEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidNumberObject_TestData>d__5.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_FloatEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidBool_TestData>d__4.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToDecimal_InvalidBool_ThrowsInvalidOperationException [FAIL]
      Microsoft.VisualBasic.Tests.ConversionsTests.ToULong_InvalidBool_ThrowsInvalidOperationException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_FloatEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidBool_TestData>d__4.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToUInteger_InvalidObject_ThrowsInvalidCastException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_CharEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidNumberObject_TestData>d__5.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToInteger_InvalidObject_ThrowsInvalidCastException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_CharEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidNumberObject_TestData>d__5.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToInteger_Object_ReturnsExpected [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_BoolEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<ToInteger_Object_TestData>d__66.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToByte_Object_ReturnsExpected [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_BoolEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<ToByte_Object_TestData>d__11.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToSByte_Object_ReturnsExpected [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_BoolEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<ToSByte_Object_TestData>d__22.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToULong_Object_ReturnsExpected [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_BoolEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<ToULong_Object_TestData>d__78.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToChar_InvalidBool_ThrowsInvalidOperationException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_FloatEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidBool_TestData>d__4.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToShort_InvalidObject_ThrowsInvalidCastException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_CharEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidNumberObject_TestData>d__5.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_FloatEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidBool_TestData>d__4.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToDouble_InvalidBool_ThrowsInvalidOperationException [FAIL]
      Microsoft.VisualBasic.Tests.ConversionsTests.ToULong_InvalidObject_ThrowsInvalidCastException [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_CharEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<InvalidNumberObject_TestData>d__5.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
      Microsoft.VisualBasic.Tests.ConversionsTests.ToLong_Object_ReturnsExpected [FAIL]
        System.PlatformNotSupportedException : System.Reflection.Emit is not supported on this platform.
        Stack Trace:
             at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess a
  ccess)
             at Microsoft.VisualBasic.Tests.ConversionsTests.get_BoolEnum()
             at Microsoft.VisualBasic.Tests.ConversionsTests.<ToLong_Object_TestData>d__90.MoveNext()
             at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
    Finished:    Microsoft.VisualBasic.Tests
  === TEST EXECUTION SUMMARY ===
C:\Users\hughb\Documents\GitHub\corefx\Tools\tests.targets(514,5): warning :    Microsoft.VisualBasic.Tests  Total: 116
3, Errors: 0, Failed: 35, Skipped: 0, Time: 2.415s [C:\Users\hughb\Documents\GitHub\corefx\src\Microsoft.VisualBasic\te
sts\Microsoft.VisualBasic.Tests.csproj]
  The previous error was converted to a warning because the task was called with ContinueOnError=true.
  ----- end  0:03:25.15 ----- exit code 1 ----------------------------------------------------------
C:\Users\hughb\Documents\GitHub\corefx\Tools\tests.targets(514,5): warning MSB3073: The command "C:\Users\hughb\Documen
ts\GitHub\corefx\bin/tests/Microsoft.VisualBasic.Tests/netfx-Windows_NT-Debug-x64//RunTests.cmd C:\Users\hughb\Document
s\GitHub\corefx\bin/testhost/netfx-Windows_NT-Debug-x64/" exited with code 1. [C:\Users\hughb\Documents\GitHub\corefx\s
rc\Microsoft.VisualBasic\tests\Microsoft.VisualBasic.Tests.csproj]
  The previous error was converted to a warning because the task was called with ContinueOnError=true.
  Build continuing because "ContinueOnError" on the task "Exec" is set to "true".
C:\Users\hughb\Documents\GitHub\corefx\Tools\tests.targets(522,5): error : One or more tests failed while running tests
 from 'Microsoft.VisualBasic.Tests' please check C:\Users\hughb\Documents\GitHub\corefx\bin/tests/Microsoft.VisualBasic
.Tests/netfx-Windows_NT-Debug-x64/testResults.xml for details! [C:\Users\hughb\Documents\GitHub\corefx\src\Microsoft.Vi
sualBasic\tests\Microsoft.VisualBasic.Tests.csproj]
Done Building Project "C:\Users\hughb\Documents\GitHub\corefx\src\Microsoft.VisualBasic\tests\Microsoft.VisualBasic.Tes
ts.csproj" (BuildAndTest target(s)) -- FAILED.


Build FAILED.

"C:\Users\hughb\Documents\GitHub\corefx\src\Microsoft.VisualBasic\tests\Microsoft.VisualBasic.Tests.csproj" (BuildAndTe
st target) (1) ->
(RunTestsForProject target) ->
  C:\Users\hughb\Documents\GitHub\corefx\Tools\tests.targets(514,5): warning :    Microsoft.VisualBasic.Tests  Total: 1
163, Errors: 0, Failed: 35, Skipped: 0, Time: 2.415s [C:\Users\hughb\Documents\GitHub\corefx\src\Microsoft.VisualBasic\
tests\Microsoft.VisualBasic.Tests.csproj]
  C:\Users\hughb\Documents\GitHub\corefx\Tools\tests.targets(514,5): warning MSB3073: The command "C:\Users\hughb\Docum
ents\GitHub\corefx\bin/tests/Microsoft.VisualBasic.Tests/netfx-Windows_NT-Debug-x64//RunTests.cmd C:\Users\hughb\Docume
nts\GitHub\corefx\bin/testhost/netfx-Windows_NT-Debug-x64/" exited with code 1. [C:\Users\hughb\Documents\GitHub\corefx
\src\Microsoft.VisualBasic\tests\Microsoft.VisualBasic.Tests.csproj]


"C:\Users\hughb\Documents\GitHub\corefx\src\Microsoft.VisualBasic\tests\Microsoft.VisualBasic.Tests.csproj" (BuildAndTe
st target) (1) ->
(RunTestsForProject target) ->
  C:\Users\hughb\Documents\GitHub\corefx\Tools\tests.targets(522,5): error : One or more tests failed while running tes
ts from 'Microsoft.VisualBasic.Tests' please check C:\Users\hughb\Documents\GitHub\corefx\bin/tests/Microsoft.VisualBas
ic.Tests/netfx-Windows_NT-Debug-x64/testResults.xml for details! [C:\Users\hughb\Documents\GitHub\corefx\src\Microsoft.
VisualBasic\tests\Microsoft.VisualBasic.Tests.csproj]

    2 Warning(s)
    1 Error(s)

Time Elapsed 00:00:09.36

C:\Users\hughb\Documents\GitHub\corefx\src\Microsoft.VisualBasic\tests>
```

**Comment by joshfree** [comment]
@steveharter

**Comment by steveharter** [comment]
@hughbe is this still occurring?

Reflection emit is supported on netfx, so perhaps you have an AOT System.Reflection assembly (which throws PNSE in release mode).

Moving to future; likely not a product issue.
