### ISSUE TITLE
hexBinary type not supported

### ISSUE THREAD

**Issue by mconnew** [dotnet/corefx#31499]
@EricStG commented on [Fri Jul 13 2018](https://github.com/dotnet/wcf/issues/3025)

When calling a method that returns a type with a field of `type="xsd:hexBinary"`, we get the following exception when targeting netcoreapp2.1:

```
System.ServiceModel.CommunicationException
  HResult=0x80131500
  Message=Error in deserializing body of reply message for operation 'getTravelDetails'.
  Source=System.Private.ServiceModel
  StackTrace:
   at System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.DeserializeBody(XmlDictionaryReader reader, MessageVersion version, XmlSerializer serializer, MessagePartDescription returnPart, MessagePartDescriptionCollection bodyParts, Object[] parameters, Boolean isRequest)
   at System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.DeserializeBody(XmlDictionaryReader reader, MessageVersion version, String action, MessageDescription messageDescription, Object[] parameters, Boolean isRequest)
   at System.ServiceModel.Dispatcher.OperationFormatter.DeserializeBodyContents(Message message, Object[] parameters, Boolean isRequest)
   at System.ServiceModel.Dispatcher.OperationFormatter.DeserializeReply(Message message, Object[] parameters)
   at System.ServiceModel.Dispatcher.ProxyOperationRuntime.AfterReply(ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WcfHexBinaryBreak.Program.<Main>d__0.MoveNext() in c:\Code\WcfHexBinaryBreak\Client\Program.cs:line 25
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerN
[wsdl.zip](https://github.com/dotnet/wcf/files/2192622/wsdl.zip)
otification(Task task)
   at WcfHexBinaryBreak.Program.<Main>(String[] args)

Inner Exception 1:
InvalidOperationException: There is an error in XML document (214, 25).

Inner Exception 2:
NotSupportedException: ReadElementContentAsBinHex method is not supported on this XmlReader. Use CanReadBinaryContent property to find out if a reader implements it.
```

Targeting net461, this operation succeeds.

Steps to reproduce:
- Create a new console application project
- Import the wsdl via connected services: [wsdl.zip](https://github.com/dotnet/wcf/files/2192639/wsdl.zip)
- Mock the wsdl using Soap UI. Response should look like this:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://Service/">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:getResponse>
         <getResponse>
            <!--Optional:-->
            <breakme>FFE2</breakme>
         </getResponse>
      </ser:getResponse>
   </soapenv:Body>
</soapenv:Envelope>
```
- Execute the following:
```
var endpointAddress = new EndpointAddress(new Uri("http://localhost:8080/MockService"));
var binding = new BasicHttpBinding
{
    MaxBufferSize = int.MaxValue,
    ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max,
    MaxReceivedMessageSize = int.MaxValue
};

var client = new MyService.ServiceClient(binding, endpointAddress);
var result = await client.getAsync(null);

```

---

@StephenBonikowsky commented on [Fri Jul 13 2018](https://github.com/dotnet/wcf/issues/3025#issuecomment-404962280)

Thanks @EricStG there is quite a bit in desktop WCF that is not supported in .NETCore. We'll have someone take a look next week to better understand why this particular type is not supported.

---

@Lxiamail commented on [Fri Jul 27 2018](https://github.com/dotnet/wcf/issues/3025#issuecomment-408506613)

@EricStG from initial investigation, we don't see an obvious reason that this is not supported. Looks like this may be a bug either in connected service or serialization. We will do further investigation.

---

@mconnew commented on [Mon Jul 30 2018](https://github.com/dotnet/wcf/issues/3025#issuecomment-409037760)

There is some code missing in the class `System.Xml.XmlBaseReader`. Specifically:

[`ReadContentAsBinHex()`](https://github.com/Microsoft/referencesource/blob/83ea7be723be0d4454317291e2f9f467d35d0b7e/System.Runtime.Serialization/System/Xml/XmlBaseReader.cs#L1481-L1484)  
 
[`ReadContentAsBinHex(byte[] buffer, int offset, int count)`](https://github.com/Microsoft/referencesource/blob/83ea7be723be0d4454317291e2f9f467d35d0b7e/System.Runtime.Serialization/System/Xml/XmlBaseReader.cs#L1511-L1526)  

[`ReadElementContentAsBinHex(byte[] buffer, int offset, int count)`](https://github.com/Microsoft/referencesource/blob/83ea7be723be0d4454317291e2f9f467d35d0b7e/System.Runtime.Serialization/System/Xml/XmlBaseReader.cs#L1486-L1509).

**Comment by EricStG** [comment]
This might be a silly question, but is adding those lines an option? Is that something I could do and send a PR for?

**Comment by yujayee** [comment]
Hi @EricStG, I'm on it and I'll send out a pr. Thanks for being willing to help!

**Comment by norachuga** [comment]
Would it be possible to get this into a release sooner than 3.0? My team is currently running into this issue and have not been able to figure out a workaround.

**Comment by Lxiamail** [comment]
@norachuga 3.0 preview1 will be released soon
