### ISSUE TITLE
asp.net core 2.1 System.Net.Sockets.SocketException when proxy is used

### ISSUE THREAD

**Issue by sarzijan** [dotnet/corefx#31504]
Hello,

I have got following exception when we use proxy in httpclient

`System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
  --- End of inner exception stack trace ---
  at at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
  at at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
  at at System.Threading.Tasks.ValueTask`1.get_Result()
  at at System.Net.Http.HttpConnection.FillAsync()
  at at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
  at at System.Threading.Tasks.ValueTask`1.get_Result()
  at at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
  --- End of inner exception stack trace ---
  at at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
  at at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
  at at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
  at at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(CancellationToken cancellationToken)
  at at System.Threading.Tasks.ValueTask`1.get_Result()
  at at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at at System.Threading.Tasks.ValueTask`1.get_Result()
  at at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
  at at System.Threading.Tasks.ValueTask`1.get_Result()
  at at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
  at at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)`

our proxy is not secured and works (with same configuration) on net core 2.0

our HttpClient with proxy is set by following code

`var proxy = new System.Net.WebProxy("proxyAddress");
using (HttpClientHandler httpClientHandler = new HttpClientHandler()
            {
                Proxy = proxy
            })
            {
                using (var client = new HttpClient(httpClientHandler) {BaseAddress = new Uri(baseUri)})
                {
.
.
.
`

we have tried to use also `{ UseDefaultCredentials = true }` for the Proxy configuration and got same exception

Do we need to add some additional configuration?

Thanks

**Comment by davidsh** [comment]
There are several bugs in proxy handling in HttpClient in .NET Core 2.1.  Please see #30327 #30330 etc.

Does your proxy use authentication?  You said "our proxy is not secured" so that implies it doesn't.  But then you mention you use `UseDefaultCredentials = true` which doesn't affect the proxy but only the server credentials.

**Comment by wfurt** [comment]
What OS is this on? You can try to make packet capture to see what is happening on the wire.
