### ISSUE TITLE
HTTP2: Assert failure when data frames are larger than the maximum allowed size

### ISSUE THREAD

**Issue by rmkerr** [dotnet/corefx#31520]
When SocketsHttpHandler receives a frame that is larger than the SETTINGS_MAX_FRAME_SIZE (default is 16,384 octets), it should cause the connection to fail with a protocol error:
```
SETTINGS_MAX_FRAME_SIZE (0x5):
Indicates the size of the largest frame payload that the sender is willing to receive, in octets.

The initial value is 214 (16,384) octets. The value advertised by an endpoint MUST be between 
this initial value and the maximum allowed frame size (224-1 or 16,777,215 octets), inclusive. 
Values outside this range MUST be treated as a connection error (Section 5.4.1) of type 
PROTOCOL_ERROR.
```

Instead, the current implementation fails an assert in the FrameHeader constructor.
<details>
<summary>Full stack trace of the assert:</summary>
```
  Assertion Failed

     at System.Net.Http.Http2Connection.FrameHeader..ctor(Int32 length, FrameType type, FrameFlags flags, Int32 streamId) in C:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 602
     at System.Net.Http.Http2Connection.FrameHeader.ReadFrom(ReadOnlySpan`1 buffer) in C:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 621
     at System.Net.Http.Http2Connection.ReadFrameAsync() in C:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 126
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\41\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 166
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 559
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\TaskContinuation.cs:line 798
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\Task.cs:line 3272
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\future.cs:line 421
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 639
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult() in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 254
     at System.Net.Http.Http2Connection.EnsureIncomingBytesAsync(Int32 minReadBytes) in C:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 112
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\41\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 166
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 559
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\TaskContinuation.cs:line 798
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\Task.cs:line 3272
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\future.cs:line 421
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 639
     at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncValueTaskMethodBuilder.cs:line 169
     at System.Net.Http.Http2Connection.ReadAtLeastAsync(Stream stream, Memory`1 buffer, Int32 minReadBytes) in C:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 1278
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\41\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 166
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 559
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\TaskContinuation.cs:line 798
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\Task.cs:line 3272
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\future.cs:line 421
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 639
     at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncValueTaskMethodBuilder.cs:line 169
     at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer) in C:\corefx\src\System.Net.Security\src\System\Net\Security\SslStreamInternal.cs:line 338
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\41\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 166
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 559
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\TaskContinuation.cs:line 798
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\Task.cs:line 3272
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Tasks\future.cs:line 421
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 639
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 629
     at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial) in C:\corefx\src\System.Net.Security\src\System\Net\Security\SslStreamInternal.cs:line 515
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\41\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 166
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 559
     at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync) in C:\corefx\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs:line 1038
     at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _) in C:\corefx\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs:line 869
     at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags) in C:\corefx\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.cs:line 770
     at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__174_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in C:\corefx\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.Windows.cs:line 1195
     at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped) in E:\A\_work\41\s\src\System.Private.CoreLib\src\System\Threading\Overlapped.cs:line 65
``` 
</details>

**Comment by geoffkizer** [comment]
Yeah, this assert is broken. We should change this to validate the received frame size and cause a connection error if it's too large.
