### ISSUE TITLE
Process RedirectStandartOutput isn't work on Mac. 

### ISSUE THREAD

**Issue by mfilippov** [dotnet/corefx#3162]
I have test program:
```
        public void Main(string[] args)
        {
            var proc = new Process {StartInfo = new ProcessStartInfo("/bin/ls")};
            proc.StartInfo.RedirectStandardOutput = true;
            
            proc.Start();
            var rdr = proc.StandardOutput;
            proc.WaitForExit(5000);
            Console.WriteLine("OUT:");
            Console.WriteLine(rdr.ReadToEnd());
            Console.WriteLine("OK");
            Console.Read();
        }
```
With dependency: "System.Diagnostics.Process": "4.0.0-beta-23109",
$dnvm list
```
Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
  *    1.0.0-beta7          coreclr x64          darwin          default
```
I got error:
$ dmx run

```
System.IO.IOException: Broken pipe
   at System.IO.UnixFileStream.SysCall[TArg1,TArg2](Func`4 sysCall, TArg1 arg1, TArg2 arg2, Boolean throwOnError)
   at System.IO.UnixFileStream.WriteCore(Byte[] array, Int32 offset, Int32 count)
   at System.IO.UnixFileStream.FlushWriteBuffer()
   at System.IO.UnixFileStream.Flush(Boolean flushToDisk)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at DnxDemo.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)

Unhandled Exception: System.IO.IOException: Broken pipe
   at System.IO.UnixFileStream.SysCall[TArg1,TArg2](Func`4 sysCall, TArg1 arg1, TArg2 arg2, Boolean throwOnError)
   at System.IO.UnixFileStream.WriteCore(Byte[] array, Int32 offset, Int32 count)
   at System.IO.UnixFileStream.FlushWriteBuffer()
   at System.IO.UnixFileStream.Dispose(Boolean disposing)
   at System.IO.UnixFileStream.Finalize()
libc++abi.dylib: terminating with uncaught exception of type PAL_SEHException
Abort trap: 6
```
It code is work on windows and linux but not on Mac.

**Comment by sokket** [comment]
Interesting, I'll take a look. Thanks for finding this @mfilippov!

**Comment by sokket** [comment]
This doesn't repro on the latest from dnvm; version 1.0.0-rc1-15779. Please re-open if you see this repro again :)

**Comment by mfilippov** [comment]
@sokket Yes on rc1 it worked. Thanks.
