### ISSUE TITLE
Code coverage: macOS: tests using RemoteExecutorConsoleApp are failing

### ISSUE THREAD

**Issue by pjanotti** [dotnet/corefx#31652]
The same doesn't happen on Ubuntu, here is an example from System.Net.Http\tests\FunctionalTests:
```
mcb:FunctionalTests pc$ dotnet msbuild /t:Test /p:ForceRunTests=True /p:Coverage=True
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  RemoteExecutorConsoleApp -> /Users/pc/s/fx/bin/AnyOS.AnyCPU.Debug/RemoteExecutorConsoleApp/netstandard/RemoteExecutorConsoleApp.exe
  ----- start 08:34:37 =============== To repro directly: =====================================================
  pushd /Users/pc/s/fx/bin/tests/System.Net.Http.Functional.Tests/netcoreapp-OSX-Debug-x64
  chmod +x /Users/pc/s/fx/bin/testhost/netcoreapp-OSX-Debug-x64//dotnet
  /Users/pc/s/fx/bin/testhost/netcoreapp-OSX-Debug-x64//dotnet xunit.console.netcore.exe System.Net.Http.Functional.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonosxtests  -notrait category=OuterLoop -notrait category=failing
  popd
  ===========================================================================================================
  ~/s/fx/bin/tests/System.Net.Http.Functional.Tests/netcoreapp-OSX-Debug-x64 ~/s/fx/src/System.Net.Http/tests/FunctionalTests
  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.
  
  Discovering: System.Net.Http.Functional.Tests
  Discovered:  System.Net.Http.Functional.Tests
  Starting:    System.Net.Http.Functional.Tests
     System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClient_SelectedSites_Test.RetrieveSite_Succeeds [SKIP]
        Condition(s) not met: \"IsSelectedSitesTestEnabled\"
     System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClient_SelectedSites_Test.RetrieveSite_Debug_Helper [SKIP]
        Condition(s) not met: \"IsSelectedSitesTestEnabled\"
  A fatal error occurred, the folder [/Users/pc/s/fx/bin/runtime/netcoreapp-OSX-Debug-x64/host/fxr] does not exist
     System.Net.Http.Functional.Tests.PlatformHandler_DiagnosticsTest.SendAsync_NullRequest_ThrowsArgumentNullException [FAIL]
        Exit code was 131 but it should have been 42
        Expected: True
        Actual:   False
        Stack Trace:
  A fatal error occurred, the folder [/Users/pc/s/fx/bin/runtime/netcoreapp-OSX-Debug-x64/host/fxr] does not exist
  A fatal error occurred, the folder [/Users/pc/s/fx/bin/runtime/netcoreapp-OSX-Debug-x64/host/fxr] does not exist
  A fatal error occurred, the folder [/Users/pc/s/fx/bin/runtime/netcoreapp-OSX-Debug-x64/host/fxr] does not exist
           /Users/pc/s/fx/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs(321,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose(Boolean disposing)
           /Users/pc/s/fx/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs(295,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
           /Users/pc/s/fx/src/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs(722,0): at System.Net.Http.Functional.Tests.DiagnosticsTest.SendAsync_NullRequest_ThrowsArgumentNullException()
```

**Comment by pjanotti** [comment]
As expected the perf work done in coverlet 2.3.0 has the added benefit of removing the need for coverlet.tracker.dll and fixes this issue.
