### ISSUE TITLE
System.InvalidOperationException: 'Nullable object must have a value.' on projection

### ISSUE THREAD

**Issue by NetTecture** [dotnet/corefx#31673]
with 2.1.1 (which incientally is the last published version, no trace of 2.1.2 on nuget).

The following is the LAMBDA executed:

```
.Call System.Linq.Queryable.Select(
    .Constant<Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Data.Core.OBTActionLog]>(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Data.Core.OBTActionLog]),
    '(.Lambda #Lambda1<System.Func`2[Data.Core.OBTActionLog,Api.Odata.ActionLog]>))

.Lambda #Lambda1<System.Func`2[Data.Core.OBTActionLog,Api.Odata.ActionLog]>(Data.Core.OBTActionLog $dtoOBTActionLog) {
    .New Api.Odata.ActionLog(){
        Created = $dtoOBTActionLog.DCreateDate,
        Element = (Api.Odata.ActionLogElements)$dtoOBTActionLog.IElement,
        Equipment = .If ($dtoOBTActionLog.OBTInstallEquipment == null) {
            null
        } .Else {
            .New Api.Odata.Equipment(){
                Id = ($dtoOBTActionLog.OBTInstallEquipment).PkInstallEquipmentID,
                Identity = .Call (($dtoOBTActionLog.OBTInstallEquipment).GIdentity).ToString(),
                Comment = ($dtoOBTActionLog.OBTInstallEquipment).SComment,

            }
        },
        Id = $dtoOBTActionLog.PkActionLogId,
        IsAnynomous = $dtoOBTActionLog.BIsAnonymous,
    }
}
```

This is a relatively easy projection. I have removed the actual filling of a number of properties, but the gist is here. Equipment is working perfectly when asked for and projected to it's own DTO.

There is a null check in place, so no, there is no reason for it to fail like this.

The corresponding stack trace is:

```
   at lambda_method(Closure , QueryContext , TransparentIdentifier`2 )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Api.Odata.Web.Code.ODataEntityController`2.Query(ODataQueryOptions`1 options) in C:\Work\OBB\Source.Backend\Api.Odata.Web\Code\ODataEntityController.cs:line 127
   at Api.Odata.Web.Code.ODataEntityController`2.Get(ODataQueryOptions`1 options) in C:\Work\OBB\Source.Backend\Api.Odata.Web\Code\ODataEntityController.cs:line 105
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
```

This should work without any issues. Any null condition (in this case that OBTActionLog.OBTInstallEquipment is null - is already checked

Sidenote: it is possible that this is a "broken relationship" - i.e. there isa value in the foreign key field, but no corresponding entry exists in the database. While this NORMALLY indicates missing relational integrity, this is not a bug in this place. Actually the foreign eky relationships are in place (for code generation) but disbled. The ActionLog table in this case is supposed to survive when referenced objects get deleted and the last entry in it will be "deleted" (i.e. you can see an entry then for the not more existing equipment 33344 and it says in a field that this item was deleted). While this is disputable from a db point of view, it is not from an ORM view and should defeinitely be supported. No problems with EF6.

**Comment by NetTecture** [comment]
Wrong Project, sorry.
