### ISSUE TITLE
System.Net.Http.DiagnosticsHandler.SendAsync throws if Activity.Current.Baggage contains values that can't be parsed by NameValueHeaderValue

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#31687]
See this line https://github.com/dotnet/corefx/blob/1a9aa57627a7d173adc1c7ccff6a9471aecc7235/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs#L92

Running a basic github oauth authentication flow on netcoreapp2.1 causes the following exception
```
System.FormatException: The format of value '/signin/github' is invalid.
   at System.Net.Http.Headers.NameValueHeaderValue.CheckValueFormat(String value)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.Authentication.OAuth.OAuthHandler`1.ExchangeCodeAsync(String code, String redirectUri)
   at Microsoft.AspNetCore.Authentication.OAuth.OAuthHandler`1.HandleRemoteAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
```
This happens when the baggage item "RequestPath" with value "/signin/github" is processed.

This issue does not happen on net461.

**Comment by davidsh** [comment]
cc: @lmolkova
