### ISSUE TITLE
SQL Server 2008 R2 (SP3) X86 can not open on linux 7.4 with dotnet 2.0.5

### ISSUE THREAD

**Issue by Zhujinyong** [dotnet/corefx#31690]
I have updated to sp3,but I still can not open database.Is x86 not supported,how can I fix it??? Waiting for answer online ,thanks a lot!(It works fine on windows ,but bad in linux centos 7.4,dontet version 2.0.5 )

my database version is :
Microsoft SQL Server 2008 R2 (SP3) - 10.50.6000.34 (Intel X86)
Aug 19 2014 12:21:07
Copyright (c) Microsoft Corporation
Enterprise Edition on Windows NT 5.2 (Build : )
Error message is:
System.InvalidOperationException: Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use and max pool size was reached.
at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection) at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource1 retry, DbConnectionOptions userOptions)
at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
at System.Data.SqlClient.SqlConnection.Open()

**Comment by Zhujinyong** [comment]
dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

**Comment by keeratsingh** [comment]
Closing due to inactivity, kindly reopen the issue if it still exists after updating to the latest SDK version.
