### ISSUE TITLE
Could not load file or assembly 'System.Buffers, Version=4.0.2.0' on self hosting .Net Core API

### ISSUE THREAD

**Issue by ircaxn** [dotnet/corefx#31718]
I am trying to self host a .Net Core API from my application which targets to both 4.7.2 full framework and .Net Core 2.1. In my local development environment the API is running fine on both frameworks and when we tried to deploy the same in our Windows server and to run on framework 4.7.2, it throws the below error:

Exception: Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Source: Microsoft.AspNetCore.Mvc.Core
Void AddMvcCoreServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCoreServices(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Trane.OWS.Apps.WebAPI.TWebAPIApplication.DoStartup()
   at Trane.Tracer.Apps.Framework.ApplicationManagement.TApplicationBase.Startup()
   at Trane.Tracer.Apps.Framework.ApplicationManagement.TApplicationManager.StartApplications()
   at Trane.Tracer.Apps.Framework.ApplicationManagement.TApplicationManager.Startup()

Both my local and server bin folder has same version(4.6.2) of System.Buffers library, however my local works fine and in server it throws the above error!

**Comment by karelz** [comment]
@joperezr can you please take a look? Is it one of the known issues?

**Comment by ircaxn** [comment]
I found that the nuget packager has added dependent assembly configuration in my app.config file which points to specific version of System.Buffers. Thanks for your response.

**Comment by opr** [comment]
Sorry to bump an old thread but I'm running into this while using the GraphQL nuget package - adding this to my web.config fixed it

```
<dependentAssembly>
        <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="4.0.2.0" newVersion="4.0.3.0" />
</dependentAssembly>
```
