### ISSUE TITLE
Very intermittent NotSupportedException from HttpClient.SendAsync

### ISSUE THREAD

**Issue by anurse** [dotnet/corefx#31748]
We encountered a strange error during one of our test runs. It failed with the following call stack:

```
System.NotSupportedException: Stream does not support reading.
   at System.IO.Stream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingStream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.StreamToStreamCopy.CopyAsync(Stream source, Stream destination, Int32 bufferSize, Boolean disposeSource, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport.<Poll>d_
```

The relevant code ([`LongPollingTransport.Poll`](https://github.com/aspnet/SignalR/blob/1874368a5caa4f562d1d693e58ae5b68a24d6166/src/Microsoft.AspNetCore.Http.Connections.Client/Internal/LongPollingTransport.cs#L149-L170) referenced in the stack trace) is making a simple GET request with no body:

```csharp
var request = new HttpRequestMessage(HttpMethod.Get, pollUrl);

HttpResponseMessage response;

try
{
    response = await _httpClient.SendAsync(request, cancellationToken);
}
catch (OperationCanceledException)
{
    // ...
}
catch (WebException ex) when (ex.Status == WebExceptionStatus.RequestCanceled)
{
    // ...
}
```

The code in question is issuing a long-running request (the server is likely to take a long time to respond, if it responds at all). From our test logs, it looks like the `cancellationToken` has just been triggered, which may be causing this issue.

We've only seen this once among many test runs hitting this code so it seems to be extremely difficult to reproduce.

The test that triggered this failure was built for **.NET Framework 4.6.1**, and it looks like the machine is running **.NET Framework 4.7.2** according to [the docs](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#to-find-net-framework-versions-by-querying-the-registry-in-code-net-framework-45-and-later):

```
PS C:\Users\anurse> Get-ChildItem "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\"


    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full


Name                           Property
----                           --------
1033                           Version       : 4.7.03062
                               CBS           : 1
                               TargetVersion : 4.0.0
                               Install       : 1
                               Servicing     : 0
                               Release       : 461814
```

See https://github.com/aspnet/SignalR/issues/2746 for history.

cc @geoffkizer

**Comment by caesar1995** [comment]
This sounds familiar. We have discovered the issue during crossed-streams investigation, and I think our conclusion that time is the exception should be wrapped in WebException.

cc: @davidsh

**Comment by davidsh** [comment]
We'll move this to our internal bug database since it is .NET Framework related.

**Comment by benaadams** [comment]
>  since it is .NET Framework related.

Can tell by the more verbose exception traces these days 😎
