### ISSUE TITLE
Does System.DirectoryServices.AccountManagement supports LDAP?

### ISSUE THREAD

**Issue by DSakura1987** [dotnet/corefx#31809]
Server info: [forumsys](https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/)

Environment: .Net Core 2.1, .Net Framework 4.7.2

Nuget Package: System.DirectoryServices.AccountManagement, 4.5.0

The question is from [Stackoverflow](https://stackoverflow.com/questions/51624868/trying-to-test-ldap-based-authentication-from-forumsys/51756583).

I have tried to use the code below to create a `PrincipalContext` to validate user credential. However, I ran into `NullReferenceException`. Does this package support non-AD LDAP servers?

Code:
```
using System;
using System.DirectoryServices.AccountManagement;

namespace LDAPTest
{
    class Program
    {
        static void Main(string[] args)
        {
            string userName = "cn=read-only-admin,dc=example,dc=com";
            string password = "password";
            string sDomain = "ldap.forumsys.com:389";
            string sDefaultOU = userName;
            string sServiceUser = @"read-only-admin";
            string sServicePassword = password;

            PrincipalContext oPrincipalContext = new PrincipalContext
            (ContextType.Domain, sDomain, sDefaultOU, sServiceUser, sServicePassword);
            oPrincipalContext.ValidateCredentials(userName,password);
        }
    }
}
```

Stacktrace:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, ServerProperties& properties)
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval()
   at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name, String container, ContextOptions options, String userName, String password)
   at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name, String container, String userName, String password)
   at LDAPTest.Program.Main(String[] args) in D:\VisualStudioCode\Projects\LDAPTest\Program.cs:line 17
```

**Comment by DSakura1987** [comment]
Hi @wjk ,
Thank you for your explanation. Yes it is what I thought but I cannot find a PDB to get the line numbers. I have to compile the source from the commit, right?
If a task can be added to make it more general it is the best.

**Comment by yuessir** [comment]
install Microsoft.Windows.Compatibility 2.0.1
on .net core 2.2
and System.DirectoryServices.AccountManagement is not supported on this platform.

**Comment by tjmoore** [comment]
The same error occurs on .NET Framework 4.6 (not tried newer).
