### ISSUE TITLE
Intermittent connection failure after multiple requests

### ISSUE THREAD

**Issue by ivankaurov** [dotnet/corefx#31865]
Very similar to #25761, Linux only

We've got a long running service in k8s container.
After some time we're seeing the following exception:
```text
Quartz.JobPersistenceException: Failure updating scheduler state when checking-in: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.Data.SqlClient.SqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: Unknown error 258
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at Quartz.Impl.AdoJobStore.StdAdoDelegate.UpdateSchedulerState(ConnectionAndTransactionHolder conn, String instanceName, DateTimeOffset checkInTime, CancellationToken cancellationToken)
   at Hosting.Scheduler.Quartz.Process.TraceSqlServerDelegate.UpdateSchedulerState(ConnectionAndTransactionHolder conn, String instanceName, DateTimeOffset checkInTime, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ClusterCheckIn(ConnectionAndTransactionHolder conn, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ClusterCheckIn(ConnectionAndTransactionHolder conn, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.DoCheckin(Guid requestorId, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.DoCheckin(Guid requestorId, CancellationToken cancellationToken)
   at Hosting.Scheduler.Quartz.Process.ConfigurableJobStoreTX.DoCheckin(Guid requestorId, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.ClusterManager.Manage() [See nested exception: System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (258): Unknown error 258
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at Quartz.Impl.AdoJobStore.StdAdoDelegate.UpdateSchedulerState(ConnectionAndTransactionHolder conn, String instanceName, DateTimeOffset checkInTime, CancellationToken cancellationToken)
   at Hosting.Scheduler.Quartz.Process.TraceSqlServerDelegate.UpdateSchedulerState(ConnectionAndTransactionHolder conn, String instanceName, DateTimeOffset checkInTime, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ClusterCheckIn(ConnectionAndTransactionHolder conn, CancellationToken cancellationToken)
ClientConnectionId:5aeb1e6c-8442-41ee-a2ab-4f7282f1b7be
Error Number:-2,State:0,Class:11]
```

and then quite strange behavior of SqlClient can be seen. No results are returned from SqlCommand's methods
a simple update command like 
```sql
UPDATE QRTZ_SCHEDULER_STATE SET LAST_CHECKIN_TIME = @lastCheckinTime WHERE SCHED_NAME = 'foo' AND INSTANCE_NAME = @instanceName
```
is performed successfully at SQL Server but the return value of ExecuteNonQueryAsync is **-1**
```cs
using (var cmd = PrepareCommand(conn, ReplaceTablePrefix(SqlUpdateSchedulerState)))
{
    AddCommandParameter(cmd, "lastCheckinTime", GetDbDateTimeValue(checkInTime));
    AddCommandParameter(cmd, "instanceName", instanceName);
    return await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
}
```
and the SQL profiler shows that SELECT command of
```
SELECT * FROM QRTZ_SCHEDULER_STATE WHERE SCHED_NAME = 'foo'
```
should return 4 rows but ReadAsync returns nothing
```cs
using (var rs = await cmd.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false))
{
    while (await rs.ReadAsync(cancellationToken).ConfigureAwait(false))
    {
        SchedulerStateRecord rec = new SchedulerStateRecord();
        rec.SchedulerInstanceId = rs.GetString(ColumnInstanceName);
        rec.CheckinTimestamp = GetDateTimeFromDbValue(rs[ColumnLastCheckinTime]) ?? DateTimeOffset.MinValue;
        rec.CheckinInterval = GetTimeSpanFromDbValue(rs[ColumnCheckinInterval]) ?? TimeSpan.Zero;
        list.Add(rec);
    }
}
```

**Environment**
SqlClient version 4.5.1
Base image: microsoft/dotnet:2.1-runtime
SQL Server: Microsoft SQL Server 2017 (RTM-CU9) (KB4341265) - 14.0.3030.27 (X64) (run in Docker)
ConnectionString: Data Source=<sql_server_name>;Initial Catalog=<database_name>;MultipleActiveResultSets=True;User=sa;Password=123;Connection Timeout=15;Max Pool Size=1000;

**Comment by azzlack** [comment]
Any news on this issue?
