### ISSUE TITLE
FileVersionInfo.GetVersionInfo(*.cs) Internal name should return the name with extension .dll rather than.exe on Unix

### ISSUE THREAD

**Issue by Anipik** [dotnet/corefx#31886]
Failing tests 
```
       System.Diagnostics.Tests.FileVersionInfoTest.Symlink_ValidFile_Succeeds [FAIL]
        Assert.Equal() Failure
                                         ↓ (pos 48)
        Expected: ···onInfo.TestAssembly.dll
        Actual:   ···onInfo.TestAssembly.exe
                                         ↑ (pos 48)
        Stack Trace:
          /Users/ani/git/viktor_corefx/src/System.Diagnostics.FileVersionInfo/tests/System.Diagnostics.FileVersionInfo.Tests/FileVersionInfoTest.cs(142,0): at System.Diagnostics.Tests.FileVersionInfoTest.VerifyVersionInfo(String filePath, MyFVI expected)
          /Users/ani/git/viktor_corefx/src/System.Diagnostics.FileVersionInfo/tests/System.Diagnostics.FileVersionInfo.Tests/FileVersionInfoTest.Unix.cs(32,0): at System.Diagnostics.Tests.FileVersionInfoTest.Symlink_ValidFile_Succeeds()
      System.Diagnostics.Tests.FileVersionInfoTest.FileVersionInfo_CustomManagedAssembly [FAIL]
        Assert.Equal() Failure
                                         ↓ (pos 48)
        Expected: ···onInfo.TestAssembly.dll
        Actual:   ···onInfo.TestAssembly.exe
                                         ↑ (pos 48)
        Stack Trace:
          /Users/ani/git/viktor_corefx/src/System.Diagnostics.FileVersionInfo/tests/System.Diagnostics.FileVersionInfo.Tests/FileVersionInfoTest.cs(142,0): at System.Diagnostics.Tests.FileVersionInfoTest.VerifyVersionInfo(String filePath, MyFVI expected)
          /Users/ani/git/viktor_corefx/src/System.Diagnostics.FileVersionInfo/tests/System.Diagnostics.FileVersionInfo.Tests/FileVersionInfoTest.cs(23,0): at System.Diagnostics.Tests.FileVersionInfoTest.FileVersionInfo_CustomManagedAssembly()
```
Related PR https://github.com/dotnet/corefx/pull/31260
Related CI Failure https://mc.dot.net/#/user/ViktorHofer/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/0b41c3c39359022b90fd141ba2b00e8c92094708/workItem/System.Diagnostics.FileVersionInfo.Tests

**Comment by danmosemsft** [comment]
This is because `peReader.PEHeaders.IsExe` is true (and `peReader.PEHeaders.IsDll` is false) for `corefx\bin\obj\AnyOS.AnyCPU.Debug\System.Diagnostics.FileVersionInfo.TestAssembly\netstandard\System.Diagnostics.FileVersionInfo.TestAssembly.dll`

**Comment by danmosemsft** [comment]
Which Roslyn emitted because System.Diagnostics.FileVersionInfo.TestAssembly has `<OutputType>Exe</OutputType>` instead of `<OutputType>Library</OutputType>`

@Anipik I guess you can change that if you want and close this.

**Comment by danmosemsft** [comment]
@ViktorHofer

**Comment by ViktorHofer** [comment]
The easiest and safest change would be to set `<TargetExt>dll</TargetExt>`.

**Comment by ViktorHofer** [comment]
With that it is guaranteed to have the same behavior between netfx and others.

**Comment by Anipik** [comment]
I can  change that

**Comment by ViktorHofer** [comment]
would be great! thanks. please also make sure next time that you cc me for the issues that you created related to my PR.

**Comment by danmosemsft** [comment]
Note this works around #31900
