### ISSUE TITLE
System.Runtime.Serialization.Formatters tests failing on UAP

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#31912]
Blobs need to be updated for:
- ReadOnlyCollection<>
- Collection

Would be nice if you could also do the last two which are not related to your changes but still need to be updated. Thanks!

**Comment by ViktorHofer** [comment]
Log for the collection ones:

```
Discovering: System.Runtime.Serialization.Formatters.Tests
  Discovered:  System.Runtime.Serialization.Formatters.Tests
  Starting:    System.Runtime.Serialization.Formatters.Tests
     System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs(obj: [1, 2, 3, 4, 5, ...], blobs: [System.Runtime.Serialization.Formatters.Tests.TypeSerializableValue, System.Runtime.Serialization.Formatters.Tests.TypeSerializableValue]) [FAIL]
        The stored blob for type System.Collections.ObjectModel.ReadOnlyCollection`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] is outdated and needs to be updated.

        -------------------- Stored blob ---------------------
        Encoded: AAEAAAD/////AQAAAAAAAAAEAQAAAJABU3lzdGVtLkNvbGxlY3Rpb25zLk9iamVjdE1vZGVsLlJlYWRPbmx5Q29sbGVjdGlvbmAxW1tTeXN0ZW0uSW50MzIsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OV1dAQAAAARsaXN0A35TeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYy5MaXN0YDFbW1N5c3RlbS5JbnQzMiwgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XV0JAgAAAAQCAAAAflN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3RgMVtbU3lzdGVtLkludDMyLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldXQMAAAAGX2l0ZW1zBV9zaXplCF92ZXJzaW9uBwAACAgICQMAAAAPAAAADwAAAA8DAAAADwAAAAgBAAAAAgAAAAMAAAAEAAAABQAAAAYAAAAHAAAACAAAAAkAAAAKAAAACwAAAAwAAAANAAAADgAAAA8AAAAL
        Decoded:     ????          ?System.Collections.ObjectModel.ReadOnlyCollection`1[[System.Int32, mscorlib, Version=0.0.0.0 Culture=neutral, PublicKeyToken=b77a5c561934e089]]   list~System.Collections.Generic.List`1[[System.Int32, mscorlib, Version=0.0.0.0 Culture=neutral, PublicKeyToken=b77a5c561934e089]]           ~System.Collections.Generic.List`1[[System.Int32, mscorlib, Version=0.0.0.0 Culture=neutral, PublicKeyToken=b77a5c561934e089]]   _items_siz_ver                                                           

        --------------- Runtime generated blob ---------------
        Encoded: AAEAAAD/////AQAAAAAAAAAEAQAAAJABU3lzdGVtLkNvbGxlY3Rpb25zLk9iamVjdE1vZGVsLlJlYWRPbmx5Q29sbGVjdGlvbmAxW1tTeXN0ZW0uSW50MzIsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OV1dAQAAAARsaXN0A35TeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYy5MaXN0YDFbW1N5c3RlbS5JbnQzMiwgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XV0JAgAAAAQCAAAAflN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3RgMVtbU3lzdGVtLkludDMyLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldXQMAAAAGX2l0ZW1zBV9zaXplCF92ZXJzaW9uBwAACAgICQMAAAAPAAAAAQAAAA8DAAAAEAAAAAgBAAAAAgAAAAMAAAAEAAAABQAAAAYAAAAHAAAACAAAAAkAAAAKAAAACwAAAAwAAAANAAAADgAAAA8AAAAAAAAACw==
        Decoded:     ????          ?System.Collections.ObjectModel.ReadOnlyCollection`1[[System.Int32, mscorlib, Version=0.0.0.0 Culture=neutral, PublicKeyToken=b77a5c561934e089]]   list~System.Collections.Generic.List`1[[System.Int32, mscorlib, Version=0.0.0.0 Culture=neutral, PublicKeyToken=b77a5c561934e089]]           ~System.Collections.Generic.List`1[[System.Int32, mscorlib, Version=0.0.0.0 Culture=neutral, PublicKeyToken=b77a5c561934e089]]   _items_siz_ver                                                               
        Expected: True
        Actual:   False
        Stack Trace:
           C:\git\corefx2\src\System.Runtime.Serialization.Formatters\tests\BinaryFormatterTests.cs(586,0): at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.SanityCheckBlob(Object obj, TypeSerializableValue[] blobs)
           C:\git\corefx2\src\System.Runtime.Serialization.Formatters\tests\BinaryFormatterTests.cs(105,0): at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAndRoundtrip(Object obj, TypeSerializableValue[] blobs, Boolean isEqualityComparer)
           C:\git\corefx2\src\System.Runtime.Serialization.Formatters\tests\BinaryFormatterTests.cs(79,0): at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs(Object obj, TypeSerializableValue[] blobs)
     System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs(obj: [1, 2, 3, 4, 5, ...], blobs: [System.Runtime.Serialization.Formatters.Tests.TypeSerializableValue, System.Runtime.Serialization.Formatters.Tests.TypeSerializableValue]) [FAIL]
        The stored blob for type System.Collections.ObjectModel.Collection`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] is outdated and needs to be updated.

        -------------------- Stored blob ---------------------
        Encoded: AAEAAAD/////AQAAAAAAAAAEAQAAAIgBU3lzdGVtLkNvbGxlY3Rpb25zLk9iamVjdE1vZGVsLkNvbGxlY3Rpb25gMVtbU3lzdGVtLkludDMyLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldXQEAAAAFaXRlbXMDflN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3RgMVtbU3lzdGVtLkludDMyLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldXQkCAAAABAIAAAB+U3lzdGVtLkNvbGxlY3Rpb25zLkdlbmVyaWMuTGlzdGAxW1tTeXN0ZW0uSW50MzIsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OV1dAwAAAAZfaXRlbXMFX3NpemUIX3ZlcnNpb24HAAAICAgJAwAAABQAAAAUAAAADwMAAAAUAAAACAEAAAACAAAAAwAAAAQAAAAFAAAABgAAAAcAAAAIAAAACQAAAAoAAAALAAAADAAAAA0AAAAOAAAADwAAABAAAAARAAAAEgAAABMAAAAUAAAACw==
        Decoded:     ????          ?System.Collections.ObjectModel.Collection`1[[System.Int32, mscorlib, Version=0.0.0.0 Culture=neutral, PublicKeyToken=b77a5c561934e089]]   items~System.Collections.Generic.List`1[[System.Int32, mscorlib, Version=0.0.0.0 Culture=neutral, PublicKeyToken=b77a5c561934e089]]          ~System.Collections.Generic.List`1[[System.Int32, mscorlib, Version=0.0.0.0 Culture=neutral, PublicKeyToken=b77a5c561934e089]]   _items_siz_ver                                                                          

        --------------- Runtime generated blob ---------------
        Encoded: AAEAAAD/////AQAAAAAAAAAEAQAAAIgBU3lzdGVtLkNvbGxlY3Rpb25zLk9iamVjdE1vZGVsLkNvbGxlY3Rpb25gMVtbU3lzdGVtLkludDMyLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldXQEAAAAFaXRlbXMDflN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3RgMVtbU3lzdGVtLkludDMyLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldXQkCAAAABAIAAAB+U3lzdGVtLkNvbGxlY3Rpb25zLkdlbmVyaWMuTGlzdGAxW1tTeXN0ZW0uSW50MzIsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OV1dAwAAAAZfaXRlbXMFX3NpemUIX3ZlcnNpb24HAAAICAgJAwAAABQAAAABAAAADwMAAAAgAAAACAEAAAACAAAAAwAAAAQAAAAFAAAABgAAAAcAAAAIAAAACQAAAAoAAAALAAAADAAAAA0AAAAOAAAADwAAABAAAAARAAAAEgAAABMAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACw==
        Decoded:     ????          ?System.Collections.ObjectModel.Collection`1[[System.Int32, mscorlib, Version=0.0.0.0 Culture=neutral, PublicKeyToken=b77a5c561934e089]]   items~System.Collections.Generic.List`1[[System.Int32, mscorlib, Version=0.0.0.0 Culture=neutral, PublicKeyToken=b77a5c561934e089]]          ~System.Collections.Generic.List`1[[System.Int32, mscorlib, Version=0.0.0.0 Culture=neutral, PublicKeyToken=b77a5c561934e089]]   _items_siz_ver                                                                                                                           
        Expected: True
        Actual:   False
        Stack Trace:
           C:\git\corefx2\src\System.Runtime.Serialization.Formatters\tests\BinaryFormatterTests.cs(586,0): at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.SanityCheckBlob(Object obj, TypeSerializableValue[] blobs)
           C:\git\corefx2\src\System.Runtime.Serialization.Formatters\tests\BinaryFormatterTests.cs(105,0): at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAndRoundtrip(Object obj, TypeSerializableValue[] blobs, Boolean isEqualityComparer)
           C:\git\corefx2\src\System.Runtime.Serialization.Formatters\tests\BinaryFormatterTests.cs(79,0): at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs(Object obj, TypeSerializableValue[] blobs)
```
