### ISSUE TITLE
System.Transactions.Local tests failing on UAP only in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#31913]
Only failing for me in CI. Disabling to enable clean UAP leg:

https://mc.dot.net/#/user/ViktorHofer/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/c75c6ac8f97f60a4c3d8d06aba22b8c56501dee2/workItem/System.Transactions.Local.Tests

```
Assert.Equal() Failure
Expected: (null)
Actual:   CommittableTransaction { IsolationLevel = Serializable, PromoterType = 00000000-0000-0000-0000-000000000000, TransactionInformation = TransactionInformation { CreationTime = 2018-08-23T15:20:29.0764495, DistributedIdentifier = 00000000-0000-0000-0000-000000000000, LocalIdentifier = \"c85a68ef-5ad7-409a-bc8e-6b4a3336eb4c:283\", Status = Committed } }

   at System.Transactions.Tests.AsyncTransactionScopeTests.AssertTransactionNull() in D:\j\workspace\windows-TGrou---33cbf18b\src\System.Transactions.Local\tests\AsyncTransactionScopeTests.cs:line 1676
   at System.Transactions.Tests.AsyncTransactionScopeTests.HandleException(Boolean exceptionDefaultOrBeforeAwait, Boolean exceptionAfterAwait, Action action) in D:\j\workspace\windows-TGrou---33cbf18b\src\System.Transactions.Local\tests\AsyncTransactionScopeTests.cs:line 1745
   at System.Transactions.Tests.AsyncTransactionScopeTests.<>c__DisplayClass7_0.<AsyncTSTest>b__1() in D:\j\workspace\windows-TGrou---33cbf18b\src\System.Transactions.Local\tests\AsyncTransactionScopeTests.cs:line 118
   at System.Transactions.Tests.TestEventListener.RunWithCallback(Action`1 handler, Action body) in D:\j\workspace\windows-TGrou---33cbf18b\src\System.Transactions.Local\tests\TransactionTracingEventListener.cs:line 108
   at System.Transactions.Tests.AsyncTransactionScopeTests.<>c__DisplayClass7_0.<AsyncTSTest>b__0() in D:\j\workspace\windows-TGrou---33cbf18b\src\System.Transactions.Local\tests\AsyncTransactionScopeTests.cs:line 111
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Transactions.Tests.AsyncTransactionScopeTests.AsyncTSTest(Int32 variation) in D:\j\workspace\windows-TGrou---33cbf18b\src\System.Transactions.Local\tests\AsyncTransactionScopeTests.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by StephenBonikowsky** [comment]
Test passed in CI, re-enabling it with PR #38554.
