### ISSUE TITLE
MacOS 10.13.6 Console.SetWindowSize() exception

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#31915]
I'm opening this on behalf of a user from VS Feedback. https://developercommunity.visualstudio.com/content/problem/318400/macos-10136-consolesetwindowsize-exception.html

dotnet core 2.1 document say support macos

Unhandled Exception: System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowSize(Int32 width, Int32 height)
   at System.Console.SetWindowSize(Int32 width, Int32 height)
   at ColorConsoleDemo.Program.Main(String[] args) in /Users/zhm/OneDrive/CodeStudy/dotnetcore/ColorConsoleDemo/Program.cs:line 26

code:

using System;
using System.Collections.Generic;

namespace ColorConsoleDemo {
    class Program {
        static void Main (string[] args) {
            List<ConsoleColor> colors = new List<ConsoleColor> ();
            // 遍历枚举的写法，高级用法，把各种颜色保存到List里
            foreach (ConsoleColor color in Enum.GetValues (typeof (ConsoleColor))) {
                colors.Add (color);
            }

            int i = 0;

            // 清楚屏幕，屏幕会被刷为空的背景色
            Console.Clear ();
            // 指定前景色
            Console.ForegroundColor = colors[i % colors.Count];
            // 指定背景色
            Console.BackgroundColor = colors[(i + 1) % colors.Count];
            Console.Write ("Hello");
            Console.ForegroundColor = colors[(i + 2) % colors.Count];
            int origWidth = Console.WindowWidth;
            int origHeight = Console.WindowHeight;
            Console.SetWindowSize (origWidth / 2, origHeight / 2);
            Console.Write (" world!", Console.WindowWidth, Console.WindowHeight);
            Console.SetCursorPosition (80, 15);
            Console.Write ("test");
            Console.SetCursorPosition (81, 16);
            Console.Write ("test");
            Console.SetCursorPosition (82, 17);
            Console.Write ("test");
            Console.SetCursorPosition (83, 18);
            Console.Write ("test");
            Console.SetCursorPosition (84, 19);
            Console.Write ("test");
            System.Threading.Thread.Sleep (1000);
            i++;
        }
    }
}

**Comment by stephentoub** [comment]
.NET Core 2.1 is supported on macOS, but there are a limited number of APIs that don't work because of platform limitations, and Console.SetWindowSize is one of them, hence the exception.

@terrajobst or @mairaw can probably comment on the best way tooling or docs could be updated to reflect this, but at present there's no bug here in the implementation; it's by design that it throws PlatformNotSupportedException.

**Comment by wfurt** [comment]
note that I get same result on Linux. there is ioctl(TIOCSWINSZ) but that is generally informational.
It is up to the application to handle it. Also note, that there may not be window at all - at least not local managed by OS. (ssh or serial port access)
