### ISSUE TITLE
System.Runtime.InteropServices tests fail on UAP

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#31910]
Disabling the tests to get clean CI.

```
Discovering: System.Runtime.InteropServices.Tests
  Discovered:  System.Runtime.InteropServices.Tests
  Starting:    System.Runtime.InteropServices.Tests
     System.Runtime.InteropServices.Tests.SetComObjectDataTests.SetComObjectData_NonNullValue_Sucesss [FAIL]
        System.Runtime.InteropServices.COMException : Creating an instance of the COM component with CLSID {927971F5-0939-11D1-8BE1-00C04FD8D503} using CoCreateInstanceFromApp failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)). Please make sure your COM object is in the allowed list of CoCreateInstanceFromApp.
        Stack Trace:
           C:\git\corefx2\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServices\Marshal\SetComObjectDataTests.Windows.cs(16,0): at System.Runtime.InteropServices.Tests.SetComObjectDataTests.SetComObjectData_NonNullValue_Sucesss()
     System.Runtime.InteropServices.Tests.SetComObjectDataTests.SetComObjectData_NullValue_Sucesss [FAIL]
        System.Runtime.InteropServices.COMException : Creating an instance of the COM component with CLSID {927971F5-0939-11D1-8BE1-00C04FD8D503} using CoCreateInstanceFromApp failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)). Please make sure your COM object is in the allowed list of CoCreateInstanceFromApp.
        Stack Trace:
           C:\git\corefx2\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServices\Marshal\SetComObjectDataTests.Windows.cs(32,0): at System.Runtime.InteropServices.Tests.SetComObjectDataTests.SetComObjectData_NullValue_Sucesss()
     System.Runtime.InteropServices.Tests.GetComObjectDataTests.GetComObjectData_ValidObject_ReturnsExpected [FAIL]
        System.Runtime.InteropServices.COMException : Creating an instance of the COM component with CLSID {927971F5-0939-11D1-8BE1-00C04FD8D503} using CoCreateInstanceFromApp failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)). Please make sure your COM object is in the allowed list of CoCreateInstanceFromApp.
        Stack Trace:
           C:\git\corefx2\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServices\Marshal\GetComObjectDataTests.Windows.cs(16,0): at System.Runtime.InteropServices.Tests.GetComObjectDataTests.GetComObjectData_ValidObject_ReturnsExpected()
  Finished:    System.Runtime.InteropServices.Tests
C:\git\corefx2\Tools\tests.targets(588,5): warning : System.Runtime.InteropServices.Tests  Total: 723, Errors: 0, Failed: 3, Skipped: 0, Time: 0.8110998 [C:\git\corefx2\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
```

**Comment by AaronRobinsonMSFT** [comment]
Boo.. this is a simple fix.. just sad that we need another PR since the fix is to suppress the class from running on UAP.

**Comment by AaronRobinsonMSFT** [comment]
cc @luqunl

**Comment by karelz** [comment]
Fixing milestone - the change went into master (3.0) branch.
