### ISSUE TITLE
Segfault running System.Net.Http.Functional.Tests on release 1.1.x

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#32009]
branch: release/1.1.0
segfault on: 
- (mission control shows catastrophic failure on `Redhat.72.Amd64-AnyCPU` and `OSX.1013.Amd64-AnyCPU` and just failure on the rest)
**Note:** The catastrophic failure seen from mission control for Redhat.72.Amd64-AnyCPU is unrelated to this issue. (refer to this comment)
- macOS High Sierra and Mojave (10.13+) call stack from core dump:

```
(lldb) t 27
* thread #27, stop reason = signal SIGSTOP
    frame #0: 0x00007fff6ad3332b libcrypto.42.dylib`BN_copy + 219
libcrypto.42.dylib`BN_copy:
->  0x7fff6ad3332b <+219>: movq   -0x28(%rbp), %rcx
    0x7fff6ad3332f <+223>: movq   %rax, (%rcx)
    0x7fff6ad33332 <+226>: movq   -0x40(%rbp), %rax
    0x7fff6ad33336 <+230>: movq   -0x28(%rbp), %rcx

(lldb) bt
* thread #27, stop reason = signal SIGSTOP
  * frame #0: 0x00007fff6ad3332b libcrypto.42.dylib`BN_copy + 219
    frame #1: 0x00007fff6ad390c0 libcrypto.42.dylib`BN_mul + 1232
    frame #2: 0x00007fff6ad81efe libcrypto.42.dylib`ec_GFp_nist_field_mul + 190
    frame #3: 0x00007fff6ad84fd6 libcrypto.42.dylib`ec_GFp_simple_add + 2022
    frame #4: 0x00007fff6ad7c6bb libcrypto.42.dylib`EC_POINT_add + 235
    frame #5: 0x00007fff6ad7e07a libcrypto.42.dylib`ec_wNAF_mul + 4490
    frame #6: 0x00007fff6ad7cc12 libcrypto.42.dylib`EC_POINTs_mul + 98
    frame #7: 0x00007fff6ad7cd0f libcrypto.42.dylib`EC_POINT_mul + 175
    frame #8: 0x00007fff6ad86e30 libcrypto.42.dylib`ecdh_compute_key + 400
    frame #9: 0x00007fff6ad86c92 libcrypto.42.dylib`ECDH_compute_key + 98
    frame #10: 0x00007fff6c87cc70 libssl.44.dylib`ssl3_send_client_kex_ecdhe_ecp + 464
    frame #11: 0x00007fff6c87bfcd libssl.44.dylib`ssl3_send_client_kex_ecdhe + 109
    frame #12: 0x00007fff6c87a37d libssl.44.dylib`ssl3_send_client_key_exchange + 381
    frame #13: 0x00007fff6c87679d libssl.44.dylib`ssl3_connect + 2301
    frame #14: 0x00007fff6c87ffa1 libssl.44.dylib`SSL_connect + 65
    frame #15: 0x00007fff6af43998 libcurl.4.dylib`ossl_connect_common + 419
    frame #16: 0x00007fff6af4834b libcurl.4.dylib`Curl_ssl_connect_nonblocking + 93
    frame #17: 0x00007fff6af08f46 libcurl.4.dylib`https_connecting + 23
    frame #18: 0x00007fff6af2c4bc libcurl.4.dylib`multi_runsingle + 2608
    frame #19: 0x00007fff6af2b992 libcurl.4.dylib`curl_multi_perform + 114
    frame #20: 0x000000010a048bd1 System.Net.Http.Native.dylib`___lldb_unnamed_symbol28$$System.Net.Http.Native.dylib + 17
```

cc: @karelz

**Comment by maryamariyan** [comment]
```
(lldb) thread list
Process 0 stopped
  thread #1: tid = 0x0000, 0x00007fff6ce598b6 libsystem_kernel.dylib`__psynch_cvwait + 10, stop reason = signal SIGSTOP
  thread #2: tid = 0x0001, 0x00007fff6ce4fa86 libsystem_kernel.dylib`mach_msg_trap + 10, stop reason = signal SIGSTOP
  thread #3: tid = 0x0002, 0x00007fff6ce5aa8a libsystem_kernel.dylib`kevent + 10, stop reason = signal SIGSTOP
  thread #4: tid = 0x0003, 0x00007fff6ce59702 libsystem_kernel.dylib`__open + 10, stop reason = signal SIGSTOP
  thread #5: tid = 0x0004, 0x00007fff6ce598b6 libsystem_kernel.dylib`__psynch_cvwait + 10, stop reason = signal SIGSTOP
  thread #6: tid = 0x0005, 0x00007fff6ce598b6 libsystem_kernel.dylib`__psynch_cvwait + 10, stop reason = signal SIGSTOP
  thread #7: tid = 0x0006, 0x00007fff6ce4fa86 libsystem_kernel.dylib`mach_msg_trap + 10, stop reason = signal SIGSTOP
  thread #8: tid = 0x0007, 0x00007fff6ce5afe2 libsystem_kernel.dylib`read + 10, stop reason = signal SIGSTOP
  thread #9: tid = 0x0008, 0x00007fff6ce598b6 libsystem_kernel.dylib`__psynch_cvwait + 10, stop reason = signal SIGSTOP
  thread #10: tid = 0x0009, 0x00007fff6ce598b6 libsystem_kernel.dylib`__psynch_cvwait + 10, stop reason = signal SIGSTOP
* thread #11: tid = 0x000a, 0x00007fff6af2a4a4 libcurl.4.dylib`Curl_hash_str + 30, stop reason = signal SIGSTOP
  thread #12: tid = 0x000b, 0x00007fff6ce598b6 libsystem_kernel.dylib`__psynch_cvwait + 10, stop reason = signal SIGSTOP
  thread #13: tid = 0x000c, 0x00007fff6ce598b6 libsystem_kernel.dylib`__psynch_cvwait + 10, stop reason = signal SIGSTOP
  thread #14: tid = 0x000d, 0x00007fff6ce598b6 libsystem_kernel.dylib`__psynch_cvwait + 10, stop reason = signal SIGSTOP
  thread #15: tid = 0x000e, 0x00007fff6ce598b6 libsystem_kernel.dylib`__psynch_cvwait + 10, stop reason = signal SIGSTOP
  thread #16: tid = 0x000f, 0x00007fff6ce4fb8e libsystem_kernel.dylib`swtch_pri + 10, stop reason = signal SIGSTOP
  thread #17: tid = 0x0010, 0x00007fff6ce598b6 libsystem_kernel.dylib`__psynch_cvwait + 10, stop reason = signal SIGSTOP
  thread #18: tid = 0x0011, 0x00007fff6ce5af3a libsystem_kernel.dylib`poll + 10, stop reason = signal SIGSTOP
  thread #19: tid = 0x0012, 0x00007fff6ce598b6 libsystem_kernel.dylib`__psynch_cvwait + 10, stop reason = signal SIGSTOP
  thread #20: tid = 0x0013, 0x00007fff6ce598b6 libsystem_kernel.dylib`__psynch_cvwait + 10, stop reason = signal SIGSTOP
  thread #21: tid = 0x0014, 0x00007fff6ce5aa8a libsystem_kernel.dylib`kevent + 10, stop reason = signal SIGSTOP
  thread #22: tid = 0x0015, 0x00007fff6ce59b92 libsystem_kernel.dylib`__select + 10, stop reason = signal SIGSTOP
  thread #23: tid = 0x0016, 0x00007fff6ce5a12a libsystem_kernel.dylib`__workq_kernreturn + 10, stop reason = signal SIGSTOP
  thread #24: tid = 0x0017, 0x00007fff6cef528c libsystem_pthread.dylib`start_wqthread, stop reason = signal SIGSTOP
  thread #25: tid = 0x0018, 0x00007fff6ce59b92 libsystem_kernel.dylib`__select + 10, stop reason = signal SIGSTOP
  thread #26: tid = 0x0019, 0x00007fff6ce598b6 libsystem_kernel.dylib`__psynch_cvwait + 10, stop reason = signal SIGSTOP
  thread #27: tid = 0x001a, 0x00007fff6ad3332b libcrypto.42.dylib`BN_copy + 219, stop reason = signal SIGSTOP
  thread #28: tid = 0x001b, 0x00007fff6ae12c2d libcrypto.42.dylib`x509_object_cmp + 29, stop reason = signal SIGSTOP
  thread #29: tid = 0x001c, 0x00007fff6ce59b92 libsystem_kernel.dylib`__select + 10, stop reason = signal SIGSTOP
  thread #30: tid = 0x001d, 0x00007fff6ce59b92 libsystem_kernel.dylib`__select + 10, stop reason = signal SIGSTOP
  thread #31: tid = 0x001e, 0x00007fff6ce4fb8e libsystem_kernel.dylib`swtch_pri + 10, stop reason = signal SIGSTOP
```

**Comment by maryamariyan** [comment]
More on System.Net.Http.Functional.Tests
```

	./RunTests.sh: line 210: 73682 Segmentation fault: 11  (core dumped) ./corerun xunit.console.netcore.exe System.Net.Http.Functional.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.0tests -notrait category=requireselevation -notrait category=failing -notrait category=nonosxtests
	Finished running tests. End time=09:17:32. Return value was 139
	dci-mac-build-109:System.Net.Http.Functional.Tests dotnet-bot$ Exception from RemoteExecutorConsoleApp(System.Net.Http.Functional.Tests, Version=4.1.1.2, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb, System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test+<>c, <ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed>b__3_0):
	Assembly: System.Net.Http.Functional.Tests, Version=4.1.1.2, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
	Type: System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test+<>c
	Method: Int32 <ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed>b__3_0()
	Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more errors occurred. (A task was canceled.) (One or more errors occurred. (A task was canceled.)) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
	   --- End of inner exception stack trace ---
	   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
	   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
	   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
	   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
	   at System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test.<>c.<ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed>b__3_0()
	   --- End of inner exception stack trace ---
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
	   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
	   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at RemoteExecutorConsoleApp.Program.Main(String[] args)
	
	Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more errors occurred. (A task was canceled.) (One or more errors occurred. (A task was canceled.)) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
	   --- End of inner exception stack trace ---
	   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
	   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
	   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
	   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
	   at System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test.<>c.<ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed>b__3_0()
	   --- End of inner exception stack trace ---
	   at RemoteExecutorConsoleApp.Program.Main(String[] args)
```

**Comment by maryamariyan** [comment]
The catastrophic failure for Redhat.72.Amd64-AnyCPU is unrelated to this issue

**Comment by davidsh** [comment]
I don't think this is actionable at this point.  Please let us know if this is still blocking something in the release/1.1.x branch.
