### ISSUE TITLE
Test failure:  System.Net.Http.Functional.Tests.HttpClientHandlerTest/SendAsync_RequestVersion20_ResponseVersion20IfHttp2Supported(server: https://http2.akamai.com/)

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#32012]
The test `System.Net.Http.Functional.Tests.HttpClientHandlerTest/SendAsync_RequestVersion20_ResponseVersion20IfHttp2Supported(server: https://http2.akamai.com/)` has failed.

System.Net.Http.HttpRequestException : The server returned an invalid or unrecognized response.

Failing in:
- Check [CI failures](https://mc.dot.net/#/product/netcore/100/source/official~2Fcorefx~2Frelease~2F1.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20180801.01/workItem/System.Net.Http.Functional.Tests).
- Also failed locally on both `macOS High Sierra (10.13)` and `macOS Mojave (10.14)` with stack trace below:

Stack Trace: 
```
	at System.Net.Http.CurlResponseHeaderReader.CheckResponseMsgFormat(Boolean condition)
	at System.Net.Http.CurlResponseHeaderReader.ReadStatusLine(HttpResponseMessage response)
	at System.Net.Http.CurlHandler.MultiAgent.CurlReceiveHeadersCallback(IntPtr buffer, UInt64 size, UInt64 nitems, IntPtr context)
 --- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
	at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<SendAsync_RequestVersion20_ResponseVersion20IfHttp2Supported>d__71.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 --- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 --- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

branch: release/1.0.0

cc: @karelz

**Comment by karelz** [comment]
@maryamariyan is it 100% failure?

**Comment by davidsh** [comment]
Closing since this was most likely infrastructure issue.
