### ISSUE TITLE
ProcessTests's TestCommonPriorityAndTimeProperties frequently failing on OS X

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3202]
```
System.Diagnostics.ProcessTests.ProcessThreadTests.TestCommonPriorityAndTimeProperties [FAIL]
09:21:11       System.ComponentModel.Win32Exception : No such process
09:21:11       Stack Trace:
09:21:11             at System.Diagnostics.ProcessThread.get_UserProcessorTime()
09:21:11             at System.Diagnostics.ProcessTests.ProcessThreadTests.TestCommonPriorityAndTimeProperties()
```

**Comment by stephentoub** [comment]
Fixed by #5752
