### ISSUE TITLE
AuthenticateAsClientAsync expections

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/corefx#32065]
when attempting to connect to a Windows 10 IIS FTPS site on localhost the `AuthenticateAsClientAsync` exceptions `AuthenticateAsClientAsync("localhost",null,Tls|Tls11|Tls12)`

`new SslStream(NetworkStream, true).AuthenticateAsClientAsync("localhost",null,Tls|Tls11|Tls12);`

with or without the `RemoteCertificateValidationCallback`

```
System.IO.IOException: The handshake failed due to an unexpected packet format.
at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__46_0(String arg1, X509CertificateCollection arg2, SslProtocols arg3, AsyncCallback callback, Object state)
at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
```

**Comment by grahamehorner** [comment]
@karelz I'm going to create a git repo for this soon, a little busy at present with a azure functions deployment going live

**Comment by grahamehorner** [comment]
@karelz doing some additional investigation as this looks as if I connect to the FTPS using the wrong mode implicit when explicit is needed or explicit when implicit is needed I can create the issue

**Comment by karelz** [comment]
No response, not enough info, closing.
If/when there is a repro (or something actionable), we can reopen it again.

**Comment by grahamehorner** [comment]
Apologies this looks to have be caused by a default configuration settings in FileZiller FTPS when reestablishing a session.
