### ISSUE TITLE
SaaS应用资源有限的情况下如何自动回收内存使用量

### ISSUE THREAD

**Issue by qibunext** [dotnet/corefx#32073]
```c#
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.1",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "2.1.2"
    },
    "configProperties": {
      "System.GC.Concurrent": false,
      "System.GC.Server": false
    }
  }
}
```
SaaS应用资源有限的情况下如何自动回收内存使用量
数据访问使用的是 Entity framework + Pomelo.EntityFrameworkCore.MySql 
服务器配置
2核4G内存
当应用程序运行在.net core 2.0上时内存使用量会缓存增加，但使用量最大化时会自动重启应用程序，会停止一会，（目前只能先用.net core 2.0）
应用程序运行在.net core 2.1上时内存使用量也会缓存增加，使用量最大化时不会自动重启，一直停留在最大的使用量。导致静态文件访问不了，mysql数据库访问也会超时

**Comment by danmosemsft** [comment]
Translation:
"How to automatically reclaim memory usage when SaaS application resources are limited
Data access using Entity framework + Pomelo.EntityFrameworkCore.MySql
server configuration
2 core 4G memory
When the application runs on .net core 2.0, the memory usage will increase, but when the usage is maximized, the application will be restarted automatically and will stop for a while. (At present, only .net core 2.0 can be used first)
When the application runs on .net core 2.1, the memory usage will also increase. When the usage is maximized, it will not restart automatically, and it will stay at the maximum usage. Resulting in static file access, mysql database access will also time out"

**Comment by karelz** [comment]
It seems that there is a memory leak - please use memory profiler for memory leak detection first.
It is not clear where the memory leak is - it can be in your code, in Pomelo or Entity Framework. Does not seem to be related to CoreFX repo, so closing.

**Comment by karelz** [comment]
Here are links to some articles and tools you can consider to use: [query](https://www.bing.com/search?q=how+to+investigate+memory+leak+in+.NET&qs=n&form=QBRE&sp=-1&pq=how+to+investigate+memory+leak+in+.net&sc=0-38&sk=&cvid=88AE7C8547DF42059309B64032D8D1C5)

**Comment by qibunext** [comment]
@karelz 
```c#
Thread 53 (Thread 0x7f4b5b9e3700 (LWP 28690)):
#0  0x00007f4b5e2b1f9d in open64 () from /lib64/libpthread.so.0
#1  0x00007f4b5ce0895f in TwoWayPipe::WaitForConnection() () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#2  0x00007f4b5ce01431 in DbgTransportSession::TransportWorker() () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#3  0x00007f4b5ce00149 in DbgTransportSession::TransportWorkerStatic(void*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#4  0x00007f4b5cf10ce2 in CorUnix::CPalThread::ThreadEntry(void*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#5  0x00007f4b5e2aae25 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6
```
```c#
Thread 3 (Thread 0x7f4a67ff7700 (LWP 25685)):
#0  0x00007f4b5e2aed42 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f4b5cf05f95 in CorUnix::CPalSynchronizationManager::ThreadNativeWait(CorUnix::_ThreadNativeWaitData*, unsigned int, CorUnix::ThreadWakeupReason*, unsigned int*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#2  0x00007f4b5cf05bf4 in CorUnix::CPalSynchronizationManager::BlockThread(CorUnix::CPalThread*, unsigned int, bool, bool, CorUnix::ThreadWakeupReason*, unsigned int*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#3  0x00007f4b5cf0aa11 in CorUnix::InternalWaitForMultipleObjectsEx(CorUnix::CPalThread*, unsigned int, void* const*, int, unsigned int, int) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#4  0x00007f4b5cf0ac32 in WaitForSingleObjectEx () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#5  0x00007f4b5cc4ae31 in CLRSemaphore::Wait(unsigned int, int) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#6  0x00007f4b5cb8800a in ThreadpoolMgr::UnfairSemaphore::Wait(unsigned int) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#7  0x00007f4b5cb8406c in ThreadpoolMgr::WorkerThreadStart(void*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#8  0x00007f4b5cf10ce2 in CorUnix::CPalThread::ThreadEntry(void*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#9  0x00007f4b5e2aae25 in start_thread () from /lib64/libpthread.so.0
#10 0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6
```
```c#
Thread 23 (Thread 0x7f4a5f001700 (LWP 13674)):
#0  0x00007f4b5e2ae995 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f4b5cf05fb2 in CorUnix::CPalSynchronizationManager::ThreadNativeWait(CorUnix::_ThreadNativeWaitData*, unsigned int, CorUnix::ThreadWakeupReason*, unsigned int*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#2  0x00007f4b5cf05bf4 in CorUnix::CPalSynchronizationManager::BlockThread(CorUnix::CPalThread*, unsigned int, bool, bool, CorUnix::ThreadWakeupReason*, unsigned int*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#3  0x00007f4b5cf0aa11 in CorUnix::InternalWaitForMultipleObjectsEx(CorUnix::CPalThread*, unsigned int, void* const*, int, unsigned int, int) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#4  0x00007f4b5cb5e92c in Thread::DoAppropriateWaitWorker(int, void**, int, unsigned int, WaitMode) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#5  0x00007f4b5cb595b0 in Thread::DoAppropriateWait(int, void**, int, unsigned int, WaitMode, PendingSync*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#6  0x00007f4b5cc4abbf in CLREventBase::WaitEx(unsigned int, WaitMode, PendingSync*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#7  0x00007f4b5cb5f600 in Thread::Block(int, PendingSync*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#8  0x00007f4b5cb57f36 in SyncBlock::Wait(int, int) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#9  0x00007f4b5ce8bfbb in ObjectNative::WaitTimeout(bool, int, Object*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#10 0x00007f4ae66ab81a in ?? ()
#11 0x00007f4a5f000840 in ?? ()
#12 0x00007f4ae417af58 in ?? ()
#13 0x00007f4acb253ee8 in ?? ()
#14 0x00007f4acb253ee8 in ?? ()
#15 0x00007f4acb253ec0 in ?? ()
#16 0x0000000000000000 in ?? ()
```
```c#
Thread 22 (Thread 0x7f4a6d001700 (LWP 14820)):
#0  0x00007f4b5e2ae995 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f4b5cf05fb2 in CorUnix::CPalSynchronizationManager::ThreadNativeWait(CorUnix::_ThreadNativeWaitData*, unsigned int, CorUnix::ThreadWakeupReason*, unsigned int*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#2  0x00007f4b5cf05bf4 in CorUnix::CPalSynchronizationManager::BlockThread(CorUnix::CPalThread*, unsigned int, bool, bool, CorUnix::ThreadWakeupReason*, unsigned int*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#3  0x00007f4b5cf0aa11 in CorUnix::InternalWaitForMultipleObjectsEx(CorUnix::CPalThread*, unsigned int, void* const*, int, unsigned int, int) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#4  0x00007f4b5cb5e92c in Thread::DoAppropriateWaitWorker(int, void**, int, unsigned int, WaitMode) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#5  0x00007f4b5cb595b0 in Thread::DoAppropriateWait(int, void**, int, unsigned int, WaitMode, PendingSync*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#6  0x00007f4b5cc4abbf in CLREventBase::WaitEx(unsigned int, WaitMode, PendingSync*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#7  0x00007f4b5cb5f600 in Thread::Block(int, PendingSync*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#8  0x00007f4b5cb57f36 in SyncBlock::Wait(int, int) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#9  0x00007f4b5ce8bfbb in ObjectNative::WaitTimeout(bool, int, Object*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#10 0x00007f4ae66ab81a in ?? ()
#11 0x00007f4a6d000840 in ?? ()
#12 0x00007f4ae417af58 in ?? ()
#13 0x00007f4acaf289b0 in ?? ()
#14 0x00007f4acaf289b0 in ?? ()
#15 0x00007f4acaf28988 in ?? ()
#16 0x0000000000000000 in ?? ()
```
```c#
Thread 41 (Thread 0x7f4a6f806700 (LWP 1774)):
#0  0x00007f4b5e2b17fd in read () from /lib64/libpthread.so.0
#1  0x00007f4b5818bbbe in SystemNative_Read () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/System.Native.so
#2  0x00007f4ae3af799e in ?? ()
#3  0x00007f4a6f805610 in ?? ()
#4  0x00007f4ae2e93020 in ?? ()
#5  0x000000009d202510 in ?? ()
#6  0x00007f4b5d0f14a8 in vtable for InlinedCallFrame () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#7  0x00007f4a6f805c58 in ?? ()
#8  0x00007f4ae4170f78 in ?? ()
#9  0x00007f4ae4170f78 in ?? ()
#10 0x00007f4a6f805610 in ?? ()
#11 0x00007f4ae3af799e in ?? ()
#12 0x00007f4a6f8056a0 in ?? ()
#13 0x00007f4ae4170f78 in ?? ()
#14 0x00007f4ac583e898 in ?? ()
#15 0x00007f4a00000001 in ?? ()
#16 0x00007f4acc005278 in ?? ()
#17 0x0000000000000002 in ?? ()
#18 0x00007f4a6f8d1c10 in ?? ()
#19 0x00007f4a6f805788 in ?? ()
#20 0x00007f4a6f8da198 in ?? ()
#21 0x00007f4a6f8056f0 in ?? ()
#22 0x00007f4ae3fcd9e3 in ?? ()
#23 0x00007f4a6f8056b0 in ?? ()
#24 0x00007f4a6f805768 in ?? ()
#25 0x00007f4ac583e900 in ?? ()
#26 0x00007f4a6f8d53d8 in ?? ()
#27 0x00007f4acc005278 in ?? ()
#28 0x0000000000000002 in ?? ()
#29 0x00007f4a6f805788 in ?? ()
#30 0x00007f4a6f8da198 in ?? ()
#31 0x00007f4a6f8057d0 in ?? ()
#32 0x00007f4ae3fcd7be in ?? ()
#33 0x00007f4a6f805700 in ?? ()
#34 0x00007f4b5cbdc6a7 in JIT_GetGCThreadStaticBase_Helper(MethodTable*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
```
```c#
25402  Thread 9 S  1.6%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
24244  Thread 13 S  1.2%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
25683  Thread 6 S  0.8%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
24249  Thread 11 S  0.4%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
25404  Thread 8 S  0.4%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
25684  Thread 5 R  0.4%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
28690  Thread 53 S  0.0%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
18641  Thread 19 S  0.0%  0x0000000000000000 in ?? () detail>>
19087  Thread 18 S  0.0%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
19172  Thread 17 S  0.0%  0x0000000000000000 in ?? () detail>>
19662  Thread 16 S  0.0%  0x0000000000000000 in ?? () detail>>
19781  Thread 15 S  0.0%  0x0000000000000000 in ?? () detail>>
20115  Thread 14 S  0.0%  0x0000000000000000 in ?? () detail>>
11199  Thread 25 S  0.0%  0x0000000000000000 in ?? () detail>>
24245  Thread 12 S  0.0%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
13674  Thread 23 S  0.0%  0x0000000000000000 in ?? () detail>>
25401  Thread 10 S  0.0%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
14820  Thread 22 S  0.0%  0x0000000000000000 in ?? () detail>>
15560  Thread 21 S  0.0%  0x0000000000000000 in ?? () detail>>
25629  Thread 7 S  0.0%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
1774  Thread 41 S  0.0%  0x00007f4b5cbdc6a7 in JIT_GetGCThreadStaticBase_Helper(MethodTable*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so detail>>
18493  Thread 20 S  0.0%  0x0000000000000000 in ?? () detail>>
25685  Thread 4 S  0.0%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
25686  Thread 3 S  0.0%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
28049  Thread 2 S  0.0%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
28689  Thread 54 S  0.0%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
13120  Thread 24 S  0.0%  0x0000000000000000 in ?? () detail>>
28691  Thread 52 S  0.0%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
28692  Thread 51 S  0.0%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
28759  Thread 50 S  0.0%  0x0000000000000000 in ?? () detail>>
28762  Thread 49 S  0.0%  0x0000000000000000 in ?? () detail>>
28763  Thread 48 S  0.0%  0x0000000000000000 in ?? () detail>>
28765  Thread 47 S  0.0%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
28766  Thread 46 S  0.0%  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6 detail>>
28767  Thread 45 S  0.0%  0x0000000000000000 in ?? () detail>>
28768  Thread 44 S  0.0%  0x0000000000000000 in ?? () detail>>
28775  Thread 43 S  0.0%  0x00007f4b5cb46a11 in MetaSig::SkipArg() () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so detail>>
28776  Thread 42 S  0.0%  0x0000000000000000 in ?? () detail>>
4672  Thread 40 S  0.0%  0x0000000000000000 in ?? () detail>>
5044  Thread 39 S  0.0%  0x0000000000000000 in ?? () detail>>
5102  Thread 38 S  0.0%  0x0000000000000000 in ?? () detail>>
5290  Thread 37 S  0.0%  0x0000000000000000 in ?? () detail>>
6880  Thread 36 S  0.0%  0x0000000000000000 in ?? () detail>>
7482  Thread 35 S  0.0%  0x0000000000000000 in ?? () detail>>
7612  Thread 34 S  0.0%  0x0000000000000000 in ?? () detail>>
7665  Thread 33 S  0.0%  0x0000000000000000 in ?? () detail>>
7691  Thread 32 S  0.0%  0x0000000000000000 in ?? () detail>>
7864  Thread 31 S  0.0%  0x0000000000000000 in ?? () detail>>
7870  Thread 30 S  0.0%  0x0000000000000000 in ?? () detail>>
7888  Thread 29 S  0.0%  0x0000000000000000 in ?? () detail>>
8018  Thread 28 S  0.0%  0x00007f4b5cb46a11 in MetaSig::SkipArg() () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so detail>>
8183  Thread 27 S  0.0%  0x0000000000000000 in ?? () detail>>
9452  Thread 26 S  0.0%  0x0000000000000000 in ?? () detail>>
```
