### ISSUE TITLE
Test failure UWP: System.Net.HttpListener.Tests, Read_NullBuffer_ThrowsArgumentNullException

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#32083]
```
Unhandled Exception of Type System.Net.Http.HttpRequestException
Message :
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Exception : Exception from HRESULT: 0x80072EFE
Stack Trace :
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---33cbf18b\src\System.Net.Http\src\uap\System\Net\HttpClientHandler.cs:line 616
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in D:\j\workspace\windows-TGrou---33cbf18b\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 475
   at System.Net.Tests.HttpRequestStreamTests.Read_NullBuffer_ThrowsArgumentNullException(Boolean chunked) in D:\j\workspace\windows-TGrou---33cbf18b\src\System.Net.HttpListener\tests\HttpRequestStreamTests.cs:line 512
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.HttpHandlerToFilter.SendAsync(HttpRequestMessage request, CancellationToken cancel) in D:\j\workspace\windows-TGrou---33cbf18b\src\System.Net.Http\src\uap\System\Net\HttpHandlerToFilter.cs:line 90
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---33cbf18b\src\System.Net.Http\src\uap\System\Net\HttpClientHandler.cs:line 607
```

**Comment by benaadams** [comment]
See in https://github.com/dotnet/corefx/pull/32069

**Comment by danmosemsft** [comment]
ERROR_WINHTTP_CONNECTION_ERROR/WININET_E_CONNECTION_ABORTED  0x80072EFE

**Comment by davidsh** [comment]
This issue was specific to the UAP implementation of the networking stack which had a different implementation for things like HTTP and WebSockets.

As of PR #41759, we no longer build the separate implementation for the UAP platform. So, this issue can't occur anymore with .NET 5 because we now will be using the same .NET Core implementation as on Windows, Linux, Mac.
