### ISSUE TITLE
Process.Kill ArgumentNullException

### ISSUE THREAD

**Issue by brettshearer** [dotnet/corefx#32080]
Receiving exception during Process.Kill as below.

   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.NativeMethods.TerminateProcess(SafeProcessHandle processHandle, Int32 exitCode)
   at System.Diagnostics.Process.Kill()

ReferenceSource shows code differently to CoreFX code on GitHub.

 using (SafeProcessHandle handle = GetProcessHandle(Interop.Advapi32.ProcessOptions.PROCESS_TERMINATE))
            {
                if (!Interop.Kernel32.TerminateProcess(handle, -1))

 handle = GetProcessHandle(NativeMethods.PROCESS_TERMINATE);
                if (!NativeMethods.TerminateProcess(handle, -1))

Both seem to suffer from no null check on handle

**Comment by danmosemsft** [comment]
What version of .NET Core are you using? 

This seems to mean the SafeHandle itself is null
```
        internal static IntPtr SafeHandleAddRef(SafeHandle pHandle, ref bool success)
        {
            if (pHandle == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.pHandle, ExceptionResource.ArgumentNull_SafeHandle);
            }
```

I'm not sure why that is, but there's interop magic around SafeHandles. From the C#, I can't see how the handle could be invalid, either.

Do you have a way to repro? Or can you get under the debugger?

**Comment by brettshearer** [comment]
Sorry, this is .Net Winforms running 4.6 - I presume I am posting to the wrong location?
If so, what is the new location. Unfortunately with Connect disappearing and Microsoft content still pointing to Connect it makes finding it a bit hard.

https://www.microsoft.com/net/support/report-a-bug
points to 
https://docs.microsoft.com/en-us/collaborate/connect-redirect

**Comment by danmosemsft** [comment]
@brettshearer bugs in .NET Framework can be reported [here](https://developercommunity.visualstudio.com/spaces/61/index.html).

If the bug reproes in .NET Core, this is the place. 

>  it looks pretty cut/dried that Process is returning a null ProcessHandle.

Yep, but why did `GetProcessHandle` return this handle. A repro would help.

**Comment by brettshearer** [comment]
Thanks - we are anticipating it may be a cross thread issue where two threads access Process.
Docs neither confirm nor deny thread safety on Process class.
We will try and force a repro separate to our implementation, but I expect it may simply turn into a documentation omission (although the reality is if not specifically mentioned thread safe, it's not).

**Comment by brettshearer** [comment]
I knocked together a repro to show the issue.
Run the following code a few times (I dropped it into a button click on a winform to create it).

```c#
var process = Process.Start("notepad.exe");
var t1 = new Task(() =>
{
	process.Dispose();
});
var t2 = new Task(() =>
{
	try
	{
		process.Kill();
	}
	catch (ObjectDisposedException ex)
	{

	}
	catch (InvalidOperationException ex)
	{

	}
	catch (ArgumentNullException ex)
	{
		MessageBox.Show(ex.ToString());
	}
}
);
t1.Start();
t2.Start();
t1.Wait();
t2.Wait();
```

**Comment by danmosemsft** [comment]
Thanks @brettshearer the repro is super helpful. I see the failure on both .NET Framework and .NET Core. Couple variations:
```
System.ArgumentNullException: SafeHandle cannot be null.
Parameter name: pHandle
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Kernel32.DuplicateHandle(SafeProcessHandle hSourceProcessHandle, SafeHandle hSourceHandle, SafeProcessHandle hTargetProcess, SafeWaitHandle& targetHandle, Int32 dwDesiredAccess, Boolean bInheritHandle, Int32 dwOptions)
   at Interop.Kernel32.ProcessWaitHandle..ctor(SafeProcessHandle processHandle)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at ConsoleApp1_Core.Program.<>c__DisplayClass0_0.<Main>b__1() in c:\users\danmose\source\repos\ConsoleApp4\ConsoleApp1\Program.cs:line 27

   Unhandled Exception: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at ConsoleApp1_Core.Program.<>c__DisplayClass0_0.<Main>b__1() in c:\users\danmose\source\repos\ConsoleApp4\ConsoleApp1\Program.cs:line 27
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ConsoleApp1_Core.Program.Main(String[] args) in c:\users\danmose\source\repos\ConsoleApp4\ConsoleApp1\Program.cs:line 48
```
This needs investigation.

**Comment by danmosemsft** [comment]
BTW I get a hit about 1/30 times when I run in a loop.

**Comment by danmosemsft** [comment]
Oh, hold on. You're accessing a Process object on concurrent threads. That's not safe and it's why it's failing. Do you see an issue without concucrrent access?

**Comment by brettshearer** [comment]
The issue occurred recently in our internal test framework - we agree it is cross thread access causing the issue. I guess the big 'not thread safe by default' disclaimer on page #1 of the .Net manual covers this.
