### ISSUE TITLE
.NET Core Only: CryptographicException: Unable to set field EncapContentInfo on type SignedDataAsn

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/corefx#32092]
I'm using the `SignedCms` class to read a file which has an Authenticode signature.

When calling `SignedCms.Decode`,  I get a `CryptographicException` on .NET Core; but the code completes successfully on NET 4.x.

Here's the full stack trace:

```
Unhandled Exception: System.Security.Cryptography.CryptographicException: Unable to set field EncapContentInfo on type System.Security.Cryptography.Pkcs.Asn1.SignedDataAsn. ---> System.Security.Cryptography.CryptographicException: Unable to set field Content on type System.Security.Cryptography.Pkcs.Asn1.EncapsulatedContentInfoAsn. ---> System.Security.Cryptography.CryptographicException: ASN1 corrupted data.
   at System.Security.Cryptography.Asn1.AsnReader.CheckExpectedTag(Asn1Tag tag, Asn1Tag expectedTag, UniversalTagNumber tagNumber)
   at System.Security.Cryptography.Asn1.AsnReader.TryGetPrimitiveOctetStringBytes(Asn1Tag expectedTag, Asn1Tag& actualTag, Nullable`1& contentLength, Int32& headerLength, ReadOnlyMemory`1& contents, UniversalTagNumber universalTagNumber)
   at System.Security.Cryptography.Asn1.AsnSerializer.<>c__DisplayClass21_0.<GetSimpleDeserializer>b__6(AsnReader reader)
   at System.Security.Cryptography.Asn1.AsnSerializer.ExplicitValueDeserializer(AsnReader reader, Deserializer valueDeserializer, Asn1Tag expectedTag)
   at System.Security.Cryptography.Asn1.AsnSerializer.DefaultValueDeserializer(AsnReader reader, Nullable`1 expectedTag, Deserializer valueDeserializer, Byte[] defaultContents, Boolean isOptional)
   at System.Security.Cryptography.Asn1.AsnSerializer.<>c__DisplayClass16_0.<DefaultValueDeserializer>b__0(AsnReader reader)
   at System.Security.Cryptography.Asn1.AsnSerializer.DeserializeCustomType(AsnReader reader, Type typeT, Asn1Tag expectedTag)
   --- End of inner exception stack trace ---
   at System.Security.Cryptography.Asn1.AsnSerializer.DeserializeCustomType(AsnReader reader, Type typeT, Asn1Tag expectedTag)
   at System.Security.Cryptography.Asn1.AsnSerializer.DeserializeCustomType(AsnReader reader, Type typeT, Asn1Tag expectedTag)
   --- End of inner exception stack trace ---
   at System.Security.Cryptography.Asn1.AsnSerializer.DeserializeCustomType(AsnReader reader, Type typeT, Asn1Tag expectedTag)
   at System.Security.Cryptography.Asn1.AsnSerializer.Deserialize[T](ReadOnlyMemory`1 source, AsnEncodingRules ruleSet)
   at System.Security.Cryptography.Pkcs.SignedCms.Decode(ReadOnlyMemory`1 encodedMessage)
   at System.Security.Cryptography.Pkcs.SignedCms.Decode(Byte[] encodedMessage)
```

You should be able to reproduce this issue with any driver catalog on Windows. For example, let's take the driver for an iPhone:

```csharp
var systemDir = Environment.GetFolderPath(Environment.SpecialFolder.System);
var driverDir = Path.Combine(systemDir, @"DriverStore\FileRepository");

var appleDriverDir = Directory.GetDirectories(driverDir, "usbaapl64.inf*").Single();
var appleDriverCat = Path.Combine(appleDriverDir, "USBAAPL64.cat");

var cert = new X509Certificate2(appleDriverCat);

var signedCms = new SignedCms();
signedCms.Decode(File.ReadAllBytes(appleDriverCat));
```

I'm testing this with `Microsoft.NETCore.App 2.1.3-servicing-26724-03`. SDK `2.1.401`.

**Comment by filipnavara** [comment]
I don't think the code currently handles Authenticode, but it's one of the things on my todo list.

**Comment by bartonjs** [comment]
I'm like 99% sure this is/was fixed by https://github.com/dotnet/corefx/pull/30432.

But the 2.1.3 release doesn't seem to have that fix in it.  Maybe it somehow missed a cutoff and will be in 2.1.4.

It definitely worked from building master this morning.

```C#
        [Fact]
        [PlatformSpecific(TestPlatforms.Windows)]
        public static void ReadDriverCat()
        {
            string systemDir = Environment.GetFolderPath(Environment.SpecialFolder.System);
            string catsDir = Path.Combine(systemDir, @"catroot\{F750E6C3-38EE-11D1-85E5-00C04FC295EE}");
            string someCat = Directory.GetFiles(catsDir, "*.cat").First();

            Console.WriteLine(someCat);
            byte[] cat = File.ReadAllBytes(someCat);
            SignedCms cms = new SignedCms();
            cms.Decode(cat);

            SignerInfoCollection signerInfos = cms.SignerInfos;
            Assert.InRange(signerInfos.Count, 1, int.MaxValue);

            for (int i = 0; i < signerInfos.Count; i++)
            {
                SignerInfo info = signerInfos[i];

                Assert.NotNull(info.Certificate);
                Console.WriteLine(info.Certificate);
            }
        }
```

Worked fine.  (I don't have the Apple driver you referenced).

https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Security.Cryptography.Pkcs/4.6.0-preview1-26904-01 is probably the build before switching from the serializer to the generator; but it should, ideally, work.  And I'm following up on why that change wasn't part of 2.1.3, like I thought it was.

**Comment by filipnavara** [comment]
@bartonjs is right. I tested it on "USBAAPL64.cat" from my machine and it's the PKCS#7 vs. CMS incompatibility that was fixed by the referenced PR.

**Comment by qmfrederik** [comment]
@bartonjs FWIW, the 4.6.0-preview1-26905-03 version of the NuGet package doesn't seem to have the fix. I'll try to build from master and let you know how that goes.

**Comment by qmfrederik** [comment]
Yup, master fixes this. Any rough guess about when we can expect an updated package on MyGet?

**Comment by bartonjs** [comment]
> FWIW, the 4.6.0-preview1-26905-03 version of the NuGet package doesn't seem to have the fix

It sort of does, sort of doesn't.  The netcoreapp3.0 version has the fix.  But the netcoreapp2.1 version just extracts the DLL off of the latest stable package, which is the 4.5.0 version without the fix.  

> Any rough guess about when we can expect an updated package on MyGet?

https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Security.Cryptography.Pkcs/4.6.0-preview1-26830-01 happens to be a balancing point where you should see the fix (before we started building for netcoreapp3.0).

The netcoreapp2.1 versions will be lacking the fix in all new packages until we get the released package updated.

**Comment by qmfrederik** [comment]
Awesome! That version seems to work on netcoreapp2.1, thanks!

**Comment by bartonjs** [comment]
@qmfrederik This should now be working with the 4.5.1 package (and, I assume, any 4.6.0-preview packages published in the last two weeks).

**Comment by bartonjs** [comment]
The packaging problem was fixed back in September, so presumably the problem is now completely addressed.
