### ISSUE TITLE
Two FileSystemWatcher tests failing on OS X

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3215]
```
09:22:39    CreatedTests.FileSystemWatcher_Created_WatcherDoesntFollowSymLinkToFile [FAIL]
09:22:39       Didn't observe a symlink created event within 30000ms
09:22:39       Expected: True
09:22:39       Actual:   False
09:22:39       Stack Trace:
09:22:39             at Utility.ExpectEvent(WaitHandle eventOccured, String eventName, Int32 timeout)
09:22:39             at CreatedTests.FileSystemWatcher_Created_WatcherDoesntFollowSymLinkToFile()
09:22:44    MoveFileTests.Unix_File_Move_In_Nested_Directory_Triggers_Event(eventType: Changed, moveRaisesEvent: False) [FAIL]
09:22:44       Should not observe a Changed event within 500ms
09:22:44       Expected: False
09:22:44       Actual:   True
09:22:44       Stack Trace:
09:22:44             at Utility.ExpectNoEvent(WaitHandle eventOccured, String eventName, Int32 timeout)
09:22:44             at MoveFileTests.<>c__DisplayClass1.<MoveAndCheck_NestedDirectory>b__0(AutoResetEvent eventOccured, TemporaryTestDirectory ttd)
09:22:44             at Utility.TestNestedDirectoriesHelper(WatcherChangeTypes change, Action`2 action, NotifyFilters changeFilers)
09:22:44             at MoveFileTests.MoveAndCheck_NestedDirectory(WatcherChangeTypes eventType, Boolean moveRaisesEvent)
09:22:44             at MoveFileTests.Unix_File_Move_In_Nested_Directory_Triggers_Event(WatcherChangeTypes eventType, Boolean moveRaisesEvent)
```
cc: @sokket

**Comment by sokket** [comment]
Moving out to RTM with the rest of the flaky FSW tests

**Comment by stephentoub** [comment]
Several tests are deactivated with this issue number.  If they're fixed, the [ActiveIssue] should be removed, otherwise they should be investigated.
