### ISSUE TITLE
SignedCms.ComputeSignature doesn't implement SubjectIdentifierType.NoSignature correctly

### ISSUE THREAD

**Issue by filipnavara** [dotnet/corefx#32187]
References: #32171, #32186

The following code crashes with `NullReferenceException`:

```c#
ContentInfo ci = new ContentInfo(new byte[1]);
SignedCms cms = new SignedCms(ci);
cms.ComputeSignature(new CmsSigner(SubjectIdentifierType.NoSignature));
```

The code path is not properly implemented and still tries to access `CmsSigner.Certificate` which is not available. Unit test coverage for this scenario is also missing.

**Comment by filipnavara** [comment]
Apparently the code crashes on NetFX as well, but for different reasons:
```
   at System.Security.Cryptography.Pkcs.PkcsUtils.CreateSignerEncodeInfo(CmsSigner signer, Boolean silent, SafeCryptProvHandle& hProv)
   at System.Security.Cryptography.Pkcs.SignedCms.Sign(CmsSigner signer, Boolean silent)
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer, Boolean silent)
   at System.Security.Cryptography.Pkcs.Tests.SignedCmsTests.CannotSignWithNoCertificate() in D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Security.Cryptography.Pkcs\tests\SignedCms\SignedCmsTests.cs:line 699
```

**Comment by krwq** [comment]
I think I'm slightly confused about the idea of computing signature without signature... Should we perhaps throw an exception for this combination of options instead?

**Comment by filipnavara** [comment]
It's kinda funny mode, it computes the data hash and doesn't sign it.

**Comment by krwq** [comment]
I think we'd rather not support it to be honest but do not feel strongly either way :) I'd rather have people use hashing directly for such cases

**Comment by filipnavara** [comment]
It's already supported for decoding, so I feel like it should be supported for encoding too. Then again it was broken in NetFX for years without anyone noticing, so it probably is not widely used.
