### ISSUE TITLE
NameResolutionPalTests.GetHostByName_HostName test failing on OS X in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3218]
The failure didn't repro for me locally, but it's happening consistently in the CI build:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_mac_debug_tst/25/console
```
System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_HostName [FAIL]
22:46:36       System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
22:46:36       Parameter name: newAddress
22:46:36       Stack Trace:
22:46:36             at System.Net.IPAddress..ctor(Int64 newAddress)
22:46:36             at System.Net.NameResolutionPal.CreateHostEntry(hostent* hostent)
22:46:36             at System.Net.NameResolutionPal.GetHostByName(String hostName)
22:46:36             at System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_HostName()
```

**Comment by pgavlin** [comment]
Closed by #3998.
