### ISSUE TITLE
 System.IO.Ports.Tests.GetPortNames/OpenEveryPortName failing on Unix

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#32204]
https://mc.dot.net/#/product/netcore/30/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180910.04/workItem/System.IO.Ports.Tests/analysis/xunit/System.IO.Ports.Tests.GetPortNames~2FOpenEveryPortName

```
System.ArgumentException : The given port name does not start with COM/com or does not resolve to a valid serial port.
Parameter name: portName
Stack Trace :
   at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace) in /root/corefx-2016895/src/System.IO.Ports/src/System/IO/Ports/SerialStream.Unix.cs:line 513
   at System.IO.Ports.SerialPort.Open() in /root/corefx-2016895/src/System.IO.Ports/src/System/IO/Ports/SerialPort.Windows.cs:line 567
   at System.IO.Ports.Tests.GetPortNames.OpenEveryPortName() in /root/corefx-2016895/src/System.IO.Ports/tests/SerialPort/GetPortNames.cs:line 32
```

(ideally the exception would include the bad value)

@wfurt I guess this part of your ongoing unix work.

**Comment by pjanotti** [comment]
@danmosemsft @wfurt I just set up a physical Linux box and can investigate this tomorrow.

**Comment by danmosemsft** [comment]
This is fixed now for everything except Alpine. Perhaps it's returning a different code, not EACCES ? 

https://mc.dot.net/#/product/netcore/30/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180913.04/workItem/System.IO.Ports.Tests/analysis/xunit/System.IO.Ports.Tests.GetPortNames~2FOpenEveryPortName
