### ISSUE TITLE
Using System.Management classes causes runtime assert

### ISSUE THREAD

**Issue by filipnavara** [dotnet/corefx#32316]
Using the following code:
```c#
new ManagementClass("Win32_BIOS");
```

crashes CoreCLR on Windows:
```
Assertion Failed
BSTR localloc'ed buffer is too small

   at System.StubHelpers.BSTRMarshaler.ConvertToNative(String strManaged, IntPtr pNativeBuffer)
   at System.Management.SecuredConnectHandler.ConnectNSecureIWbemServices(String path, IWbemServices& pServices)
   at System.Management.ManagementScope.InitializeGuts(Object o)
   at System.Management.ThreadDispatch.ThreadEntryPointMethodWithParam()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

I am not sure whether this is something that is broken on the CoreFX side or CoreCLR side, so please move if this is inappropriate repository (/cc @jkotas).

**Comment by jkotas** [comment]
This looks like a bug in CoreCLR.

**Comment by jkotas** [comment]
This issue was moved to dotnet/coreclr#20001
