### ISSUE TITLE
TestEnvironmentOfChildProcess fails (intermittently?)

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#3237]
It looks like it's pulling in the PR description and something is going wrong with the roundtripping thereof:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/4024/

```
Assert+WrapperXunitException : File path: d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs. Line: 231
----
Expected: ghprbPullLongDescription=Since CryptographicException has no constructor that takes both an HResult and a Message this is being achieved by a private derived type which can set both properties., , Fixes #3232.
Actual: ghprbPullLongDescription=Since CryptographicException has no constructor that takes both an HResult and a Message this is being achieved by a private derived type which can set both properties. Fixes #3232.
Expected: True
Actual: False
+++++++++++++++++++
STACK TRACE:
at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
  in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs:line 582
at Assert.True(Boolean condition, String userMessage, String path, Int32 line)
  in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs:line 577
at System.Diagnostics.ProcessTests.ProcessStartInfoTests.TestEnvironmentOfChildProcess()
  in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs:line 231
----- Inner Stack Trace -----
at Assert.True(Boolean condition, String userMessage, String path, Int32 line)
  in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs:line 574
```

**Comment by AtsushiKan** [comment]
The test assumes that environment variable values don't contain newlines. Well who would do that? Oh, our CI process :-(

**Comment by stephentoub** [comment]
I'll take a look

**Comment by CIPop** [comment]
This is failing and _blocking_ PRs. I'll disable it within my PR (#3113).
It's very odd that a test took dependencies on environment variables that are not under its control.
