### ISSUE TITLE
The SSL connection could not be established on ARM with Linux Mate

### ISSUE THREAD

**Issue by nicolasr75** [dotnet/corefx#32400]
I have an application that wants to send data from a Raspberry PI to a web application via HttpClient. If the web app is reachable via HTTP, everything works fine. If I switch the web app to HTTPS I get the following exception:

	[16:15:31 ERR] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file
	   at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
	   at Internal.Cryptography.Pal.StorePal.LoadMachineStores()
	   at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
	   at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
	   at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.FindCandidates(X509Certificate2 leaf, X509Certificate2Collection extraStore, HashSet`1 downloaded, HashSet`1 systemTrusted, TimeSpan& remainingDownloadTime)
	   at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout)
	   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException)
	   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
	   at System.Net.Security.CertificateValidation.BuildChainAndVerifyProperties(X509Chain chain, X509Certificate2 remoteCertificate, Boolean checkCertName, String hostName)
	   at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback, ProtocolToken& alertToken)
	   at System.Net.Security.SslState.CompleteHandshake(ProtocolToken& alertToken)
	   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Net.Security.SslState.ThrowIfExceptional()
	   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
	   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
	   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
	   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_1(IAsyncResult iar)
	   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
	   --- End of inner exception stack trace ---
	   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
	   at System.Threading.Tasks.ValueTask`1.get_Result()
	   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Threading.Tasks.ValueTask`1.get_Result()
	   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
	   at System.Threading.Tasks.ValueTask`1.get_Result()
	   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
	   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
	   at MyApp.MyClass.SendData(Data data) in ...

This seems to be related to https://github.com/dotnet/corefx/issues/32300 because defining 

    export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
    export SSL_CERT_DIR=/dev/null

resolves the error. Notice however, that the inner exception is different from the mentioned issue **Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file**

Since I don't understand the details here, I would like to know whether we need to fulfill any prerequisites on the target system or whether this is something that will be taken care of by newer versions of .NET Core?

My app runs on .NET Core 2.1.400
The target system is Ubuntu 16.04.5 with Linux Mate desktop.
The TLS certificate is (as far as I know) from Let's Encrypt.

**Comment by wfurt** [comment]
you can try to run the application under `strace -r -f -s 200 -e trace=file dotnet foo.dll`
That should show what file is failing to be opened. If you have symbolic links in the directory, make sure they link to a valid file.

**Comment by bartonjs** [comment]
SDK 2.1.400 has runtime 2.1.2 (per https://www.microsoft.com/net/download/dotnet-core/2.1).  This looks like #29942, which was fixed for 2.1.3.

The current runtime is 2.1.5.  Depending on how you obtained things, you should either upgrade your runtime component, or upgrade to SDK 2.1.403.

**Comment by nicolasr75** [comment]
@wfurt Thanks, very helpful.
