### ISSUE TITLE
TypeConverter isn't working for ModifierKeys

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#32600]
Reported by @onovotny, /cc @vatsan-madhavan-msft

Create a WPF application with a combination used in KeyBinding.Modifiers.  For example:
```xaml
    <Window.InputBindings>
        <KeyBinding Modifiers="Control+Shift" Key="H" Command="ApplicationCommands.Help"/>
    </Window.InputBindings>
```

Run that application.

Expect: runs correctly
Actual: crashes on startup with callstack:
```Unhandled Exception: System.Windows.Markup.XamlParseException: 'Provide value on 'System.Windows.Baml2006.TypeConverterMarkupExtension' threw an exception.' Line number '20' and line position '10'. ---> System.FormatException: Control+Shift is not a valid value for ModifierKeys. ---> System.ArgumentException: Requested value 'Control+Shift' was not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Windows.Baml2006.TypeConverterMarkupExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\System.Xaml\System\Xaml\Runtime\ClrObjectRuntime.cs:line 486
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\WindowsBase\MS\Internal\Threading\ExceptionWrapper.cs:line 104
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\WindowsBase\MS\Internal\Threading\ExceptionWrapper.cs:line 37
   at System.Windows.Threading.Dispatcher.WrappedInvoke(Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\WindowsBase\System\Windows\Threading\Dispatcher.cs:line 3119
   at System.Windows.Threading.DispatcherOperation.InvokeImpl() in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\WindowsBase\System\Windows\Threading\DispatcherOperation.cs:line 583
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\WindowsBase\System\Windows\Threading\DispatcherOperation.cs:line 527
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\Shared\MS\Internal\CulturePreservingExecutionContext.cs:line 234
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\Shared\MS\Internal\CulturePreservingExecutionContext.cs:line 185
   at System.Windows.Threading.DispatcherOperation.Invoke() in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\WindowsBase\System\Windows\Threading\DispatcherOperation.cs:line 438
   at System.Windows.Threading.Dispatcher.ProcessQueue() in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\WindowsBase\System\Windows\Threading\Dispatcher.cs:line 2269
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\WindowsBase\System\Windows\Threading\Dispatcher.cs:line 2507
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\Shared\MS\Win32\HwndWrapper.cs:line 345
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\Shared\MS\Win32\HwndSubclass.cs:line 494
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\WindowsBase\MS\Internal\Threading\ExceptionWrapper.cs:line 104
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\WindowsBase\MS\Internal\Threading\ExceptionWrapper.cs:line 37
   at System.Windows.Threading.Dispatcher.WrappedInvoke(Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\WindowsBase\System\Windows\Threading\Dispatcher.cs:line 3119
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\WindowsBase\System\Windows\Threading\Dispatcher.cs:line 1447
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\WindowsBase\System\Windows\Threading\Dispatcher.cs:line 1159
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\Shared\MS\Win32\HwndSubclass.cs:line 392
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(MSG& msg) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\WindowsBase\System\Windows\Threading\Dispatcher.cs:line 2480
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\WindowsBase\System\Windows\Threading\Dispatcher.cs:line 2330
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame) in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\WindowsBase\System\Windows\Threading\Dispatcher.cs:line 368
   at System.Windows.Threading.Dispatcher.Run() in F:\devdiv.dotnet\DotNet-Trusted\src\WPF\src\WindowsBase\System\Windows\Threading\Dispatcher.cs:line 327
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at keyBinding.App.Main()
```

It would appear that the [typeconverter](https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.modifierkeysconverter?redirectedfrom=MSDN&view=netframework-4.7.2) for handling these enum combinations isn't being honored.

We need to look into how that converter is actually hooked up and find out why it isn't working on .NETCore.

Repro app: [keyBinding.zip](https://github.com/dotnet/corefx/files/2442958/keyBinding.zip)

**Comment by ericstj** [comment]
I debugged this a bit and found that the Baml itself appears to have the wrong TypeConverter ID.  On desktop we get FE66=-410, on core we're getting FF3D=-195.

Need to see how the XAML compiler determines these converter IDs.  It's possible we're missing typeforwards,typeforwardedfrom, or the ability to understand such attributes in the tooling.

**Comment by vatsan-madhavan** [comment]
System.Xaml should really be using `System.Windows.Input.ModifierKeysConverter` here instead of `EnumConverter`.  EnumConverter will fail if we supply a string like `"Control+Shift"` to it. 

@rladuca - I think we need to spend some time on bringing up the Commanding DRT's for .NET Core. 

Thanks for the report - we are on it. That said, this could take a little time depending on how difficult it turns out to be to solve it. It could be a runtime fix, or it might end up being a compiler fix. 

I'll follow up with Ryland who is working on PresentationBuildTasks bring-up to see if he can spend some time debugging this, and ask him validate it against his new prototype to see if the problem reproes there. [I can't tag him here yet. ]

**Comment by ericstj** [comment]
Found it!  We're missing TypeConverter attributes from reference assemblies.  We'll need to fix this both in WPF and CoreFx.  I'll take this and start by fixing the tooling in buildtools.

**Comment by ericstj** [comment]
@vatsan-madhavan the [issue](https://github.com/dotnet/corefx/issues/32600#issuecomment-427145067) was that the [XamlCompiler](https://referencesource.microsoft.com/#PresentationBuildTasks/Base/System/Windows/Markup/TypeConverterHelper.cs,128) was reading trying to read the TypeConverter attribute from the reference assemblies.  Since all reference assemblies omit most attributes it wasn't finding it.

I plan on adding these back to unblock the scenario.

It's interesting that the XAML compiler cares about these in *reference* assembly.  As a side effect it means you can't really service those attributes since the mapping is burned-in to the BAML.  Then again, it may be saving some reflection usage at runtime so that might have been the trade-off the original developers were aiming for.  

We may consider adding other attributes back but we'd want to see the exact use case for those.  /cc @weshaggard @safern

**Comment by vatsan-madhavan** [comment]
@ryalalnms If PBT is reading the *reference* netcore assemblies, we should understand why and whether this is the behavior we want. 
cc rladuca

**Comment by ericstj** [comment]
This should be fixed in builds post 10/10/2018.
