### ISSUE TITLE
 System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by phatcher** [dotnet/corefx#32616]
Migrated from [#3575](https://github.com/aspnet/Home/issues/3575)...

The call from my Asp.NET Core app is just a standard http get to retrieve OData metadata, e.g. `GET /api/odata/asset/$metadata `- this works 99.9% of the time but occasionally it fails and I get a HttpRequestException reported in Application Insights..

```
System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions
---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```
There are webjobs in the same app service plan and [#1876](https://github.com/Azure/azure-webjobs-sdk/issues/1876)  seems to be similar (see last two comments), what I'm not sure is whether this error gets raised per endpoint you talk to, or across all outbound requests.

There are no warnings at the app service plan level regarding port exhaustion and the endpoint I'm trying to talk to is in the same app service plan and is actually a virtual application within the same web site.

**Comment by karelz** [comment]
@geoffkizer @stephentoub any idea how to track it down?

@phatcher which OS?
Can you please try to reproduce it locally? Would you be able to share such a repro? (ideally minimized if possible) Thanks!

**Comment by phatcher** [comment]
@karelz This is on a Windows App Service Plan, problem doesn't happen locally only on Azure

Is there anyway from Kudu to see if this is port exhaustion?

**Comment by karelz** [comment]
Never heard of Kudu, so I don't know.
If it happens only in Windows App Service Plan, then try to create minimal repro to hit it there, or follow up with them to see what is happening (to rule out some throttling or other environmental thing interfering).

**Comment by phatcher** [comment]
@karelz Ok, I'll raise an issue with Azure support and see how it goes, BTW Kudu is the command line control panel inside an App Service

**Comment by karelz** [comment]
OK, let us know if there is something we should take a look from .NET Core perspective. Thanks!
