### ISSUE TITLE
Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies

### ISSUE THREAD

**Issue by sandersaares** [dotnet/corefx#32610]
1. Create a new .NET Framework 4.7.1 console app project.
1. Install BenchmarkDotNet NuGet package.
1. Observe that above resulted in `<package id="System.ValueTuple" version="4.3.0" targetFramework="net471" />` in `packages.config` due to some dependency.
1. Paste the following code into Program.cs and excute the app.

```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace ConsoleApp3
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            BenchmarkRunner.Run<Foo>();
        }
    }

    [ClrJob]
    internal class Foo
    {
        [Benchmark]
        public void Bar()
        {

        }
    }
}
```

Expected result: app executes and performs some no-op benchmarks.

Actual result:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   --- End of inner exception stack trace ---
   at BenchmarkDotNet.Running.BenchmarkConverter.GetParameterDefinitions(Type type)
   at BenchmarkDotNet.Running.BenchmarkConverter.MethodsToBenchmarksWithFullConfig(Type containingType, MethodInfo[] benchmarkMethods, ReadOnlyConfig fullConfig)
   at BenchmarkDotNet.Running.BenchmarkConverter.TypeToBenchmarks(Type type, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config)
   at ConsoleApp3.Program.Main(String[] args) in C:\Source\ConsoleApp3\ConsoleApp3\Program.cs:line 15
```

**Comment by sandersaares** [comment]
If I upgrade NuGet packages to recent versions, it looks like the error goes away. Does this mean that 4.3.0 is not actually compatible with net471, despite getting installed? Does it mean the BenchmarkDotNet package owner should require a later one to work around this? What is the right way forward here, so installing the package will result in a successful runtime experience?

**Comment by karelz** [comment]
@joperezr is it a known issue?

**Comment by ViktorHofer** [comment]
cc @adamsitnik

**Comment by sandersaares** [comment]
I am using VS 15.8.6.

[binlog.zip](https://github.com/dotnet/corefx/files/2458869/binlog.zip)

**Comment by GSPP** [comment]
I'm tracking related issues and information in a list. They are related to System.Net.Http, System.Runtime, System.IO, System.ValueTuple and others.

https://github.com/dotnet/corefx/issues/32587
https://github.com/dotnet/corefx/issues/32561
https://github.com/dotnet/standard/issues/481
https://github.com/dotnet/standard/issues/567
https://github.com/dotnet/standard/issues/558
https://github.com/dotnet/standard/issues/887
https://github.com/dotnet/standard/issues/891
https://github.com/dotnet/corefx/issues/32610

.NET 4.7.2 helps with some but not all of these. You can look at my comments there for some ideas on how to work around the issues.

**Comment by joperezr** [comment]
Oh I see, this is a known issue with packages.config. What I think is going on here is that when you add one of your nuget package dependnecies, then the NuGet package manager is adding the binding redirect into your app.config. This is a bug since the NuGet package manager should never be emitting binding redirects as it doesn't have the full picture of all your references.

Can you try the exact same steps, but instead of adding the package depenendencies with VS, add them using `<PackageReference` ? Basically add the package reference by adding to your project the following:
```xml
<ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.11.1" />
</ItemGroup>
```

I would expect that doing that should get rid of the error.

**Comment by pavel-agarkov** [comment]
I had to manually put `System.ValueTuple.dll` into
> C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.ValueTuple\v4.0_0.0.0.0__cc7b13ffcd2ddd51

in order for it to be automatically found in .Net 4.6.1 console app. No other recommendations helped.
