### ISSUE TITLE
System.IO.IOException: Unable to write data to the transport connection: Broken pipe.

### ISSUE THREAD

**Issue by kieronlanning** [dotnet/corefx#32634]
When running a .NET Core 2.1 app in Docker, after a few minutes, the app exists with the following exception:

```identity-api         |    Unhandled Exception: System.AggregateException: One or more errors occurred. (Unable to write data to the transport connection: Broken pipe.) ---> System.IO.IOException: Unable to write data to the transport connection: Broken pipe. ---> System.Net.Sockets.SocketException: Broken pipe
identity-api         |    at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
identity-api         |    --- End of inner exception stack trace ---
identity-api         |    at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
identity-api         |    at System.Data.SqlClient.SNI.SslOverTdsStream.WriteInternal(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token, Boolean async)
identity-api         |    --- End of inner exception stack trace ---
identity-api         |    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
identity-api         |    at System.Threading.Tasks.Task.Wait()
identity-api         |    at System.Data.SqlClient.SNI.SslOverTdsStream.Write(Byte[] buffer, Int32 offset, Int32 count)
identity-api         |    at System.Net.Security.SslStreamInternal.WriteSingleChunk[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
identity-api         |    at System.Net.Security.SslStreamInternal.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
identity-api         |    at System.Net.Security.SslStreamInternal.Write(Byte[] buffer, Int32 offset, Int32 count)
identity-api         |    at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
identity-api         |    at System.Data.SqlClient.SNI.SNITCPHandle.Send(SNIPacket packet)
identity-api         |    at System.Data.SqlClient.SNI.SNIMarsConnection.Send(SNIPacket packet)
identity-api         |    at System.Data.SqlClient.SNI.SNIMarsHandle.SendControlPacket(SNISMUXFlags flags)
identity-api         |    at System.Data.SqlClient.SNI.SNIMarsHandle.Dispose()
identity-api         |    at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.Dispose()
identity-api         |    at System.Data.SqlClient.TdsParserSessionPool.Dispose()
identity-api         |    at System.Data.SqlClient.TdsParser.Disconnect()
identity-api         |    at System.Data.SqlClient.SqlInternalConnectionTds.Dispose()
identity-api         |    at System.Data.ProviderBase.DbConnectionPool.DestroyObject(DbConnectionInternal obj)
identity-api         |    at System.Data.ProviderBase.DbConnectionPool.CleanupCallback(Object state)
identity-api         |    at System.Threading.TimerQueueTimer.CallCallback()
identity-api         |    at System.Threading.TimerQueueTimer.Fire()
identity-api         |    at System.Threading.TimerQueue.FireNextTimers()```

There are two containers that access SQL, they both exit around the same time.

This happens consistently. I've tried Alpine and non-Alpine images.  The apps are both MVC and the DataContexts have been unused other than running the migrations.

**Comment by tmds** [comment]
From the stacktrace it seems the issue occurs when the connection to the sql server is removed from the pool.
The IOException is thrown because the server has already closed the connection. Because no-one catches it, it crashes your app.

**Comment by kieronlanning** [comment]
@tmds What I don't understand I guess is, well, why.

I'm not explicity catching is because I don't explicity do anything with it.

In-fact, it's an MVC app that catches and logs pretty much everything to prevent downtime and bad requests. But this, only in Docker, takes the app out completey.

**Comment by tmds** [comment]
Your not supposed to catch this one, corefx is.

**Comment by SeymourRu** [comment]
Same here!
2.0 runs without error
2.1 runs with error

**Comment by AfsanehR** [comment]
@kieronlanning  Would you be able to provide a repro?

**Comment by kieronlanning** [comment]
@AfsanehR I'm afraid not. We had to re-engineer (and re-host) the solution because we couldn't get past that problem.

**Comment by Hartdrooz** [comment]
Same issue here, running .Net Core 2.2 on Linux Container and this happen frequently, we are using SQL Server Azure don't know if this is a factor.  Any update on this ?

**Comment by stephentoub** [comment]
@AfsanehR, this seems fairly problematic if it's actually happening frequently for multiple apps.  I realize it could be challenging to address without a repro, but I've moved it from Future to 3.0 for now so that it doesn't slip through the cracks.
cc: @karelz

**Comment by karelz** [comment]
cc @David-Engel @tarikulsabbir @Gary-Zh

**Comment by tmds** [comment]
The stack trace is saying a lot:

A timeout occurs:
```
identity-api         |    at System.Threading.TimerQueue.FireNextTimers()
```
It cleans up a connection from the connection pool:
```
identity-api         |    at System.Data.ProviderBase.DbConnectionPool.CleanupCallback(Object state)
```
The connection gets disposed:
```
identity-api         |    at System.Data.SqlClient.SqlInternalConnectionTds.Dispose()
```
A control packet is sent through the connection:
```
identity-api         |    at System.Data.SqlClient.SNI.SNIMarsHandle.SendControlPacket(SNISMUXFlags flags)
```
But the connection was already closed:
```
identity-api         |    Unhandled Exception: System.AggregateException: One or more errors occurred. (Unable to write data to the transport connection: Broken pipe.) ---> System.IO.IOException: Unable to write data to the transport connection: Broken pipe. ---> System.Net.Sockets.SocketException: Broken pipe
```

**Comment by TerryAspen** [comment]
I'm also encountering this exact same error including the stack trace running .Net Core 2.2.
Linux docker container accessing Azure SQL server.

Has there been any resolution to this?

**Comment by DenKn** [comment]
I have similar problem. _Unable to read data from the transport connection: An established connection was aborted by the software in your host machine_
But I don't use SQL server.
This error sometimes happens on console app (.net core 2.2) which works with server app (.net core 2.2, run as docker container in Azure on Linux).

**Comment by mifurm** [comment]
Same in here. Can give repo if required by all has been said already!

**Comment by DaEkstrim** [comment]
I don't know if my stack trace will help. I'm running a DotNet Core 2.1.2 app in Linux docker container on Kubernetes accessing Azure SQL. If this is noise, feel free to delete my comment.

```
System.AggregateException: One or more errors occurred. (Unable to write data to the transport connection: Broken pipe.) ---> System.IO.IOException: Unable to write data to the transport connection: Broken pipe. ---> System.Net.Sockets.SocketException: Broken pipe
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Data.SqlClient.SNI.SslOverTdsStream.WriteInternal(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token, Boolean async)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Data.SqlClient.SNI.SslOverTdsStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslStreamInternal.WriteSingleChunk[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Security.SslStreamInternal.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Security.SslStreamInternal.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Data.SqlClient.SNI.SNITCPHandle.Send(SNIPacket packet)
   at System.Data.SqlClient.SNI.SNIMarsConnection.Send(SNIPacket packet)
   at System.Data.SqlClient.SNI.SNIMarsHandle.SendControlPacket(SNISMUXFlags flags)
   at System.Data.SqlClient.SNI.SNIMarsHandle.Dispose()
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.Dispose()
   at System.Data.SqlClient.TdsParserSessionPool.Dispose()
   at System.Data.SqlClient.TdsParser.Disconnect()
   at System.Data.SqlClient.SqlInternalConnectionTds.Dispose()
   at System.Data.ProviderBase.DbConnectionPool.DestroyObject(DbConnectionInternal obj)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Geode.Services.Cache.SQLMemoryOLTP.SQLMemoryCacheManager.OpenSqlConnection() in /src/Geode.Services.Cache.SQLMemoryOLTP/SQLMemoryCacheManager.cs:line 301
   at Geode.Services.Cache.SQLMemoryOLTP.SQLMemoryCacheManager.ExecuteNonQueryCommandAsync(SqlCommand command) in /src/Geode.Services.Cache.SQLMemoryOLTP/SQLMemoryCacheManager.cs:line 223
---> (Inner Exception #0) System.IO.IOException: Unable to write data to the transport connection: Broken pipe. ---> System.Net.Sockets.SocketException: Broken pipe
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Data.SqlClient.SNI.SslOverTdsStream.WriteInternal(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token, Boolean async)<---
```

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.
