### ISSUE TITLE
NTAccount.Translate fails with ObjectDisposedException

### ISSUE THREAD

**Issue by sajagi** [dotnet/corefx#32636]
## Synopsis

After calling NTAccount.Translate with invalid (non-existing) user the NTAccount.Translate method becomes unusable and throws System.ObjectDisposedException: Safe handle has been closed on any query (even for existing user). 

## Code to reproduce

Code to reproduce:

```csharp
// foobar should not exist
var nta = new NTAccount("foobar");
try
{
  nta.Translate(typeof(SecurityIdentifier));
}
catch
{
}
nta.Translate(typeof(SecurityIdentifier));
```

## Expected behavior

Method should throw `System.ComponentModel.Win32Exception (0x80004005): The trust relationship between this workstation and the primary domain failed` on both calls.

## Suggestion

The problem seems to be in re-using SafeLsaPolicyHandle.InvalidHandle and disposing of in NTAccount.TranslateToSids finally block.

## Environment
.NET Core 2.1, Windows 10

**Comment by MarcoRossignoli** [comment]
I get different exception:
```
Unhandled Exception: System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
```
My csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Principal.Windows" Version="4.5.1" />
  </ItemGroup>

</Project>

```
I'm in a domain.

**Comment by sajagi** [comment]
Hi, here are both stacktraces (1st and 2nd exception):

```
System.ComponentModel.Win32Exception (1789): The trust relationship between this workstation and the primary domain failed
   at System.Security.Principal.NTAccount.TranslateToSids(IdentityReferenceCollection sourceAccounts, Boolean& someFailed)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at CoreApp.Program.Main(String[] args) in C:\Users\lupa\Source\Repos\ConsoleApp3\CoreApp\Program.cs:line 16


System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Advapi32.LsaLookupNames2(SafeLsaPolicyHandle handle, Int32 flags, Int32 count, UNICODE_STRING[] names, SafeLsaMemoryHandle& referencedDomains, SafeLsaMemoryHandle& sids)
   at System.Security.Principal.NTAccount.TranslateToSids(IdentityReferenceCollection sourceAccounts, Boolean& someFailed)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at CoreApp.Program.Main(String[] args) in C:\Users\lupa\Source\Repos\ConsoleApp3\CoreApp\Program.cs:line 28
```

Btw. it should be noted that the 2nd exception is always thrown, even when a valid user is supplied.

**Comment by MarcoRossignoli** [comment]
I'm able to repro...machine in domain but off line.
```
Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Advapi32.LsaLookupNames2(SafeLsaPolicyHandle handle, Int32 flags, Int32 count, UNICODE_STRING[] names, SafeLsaMemoryHandle& referencedDomains, SafeLsaMemoryHandle& sids)
   at System.Security.Principal.NTAccount.TranslateToSids(IdentityReferenceCollection sourceAccounts, Boolean& someFailed)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean& someFailed)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
```

**Comment by MarcoRossignoli** [comment]
@sajagi we fixed bug, the issue is on "static" object, so you cannot recovery without restart app...if you need temporary fix you can try something like this(carefully):
```cs
    internal class Program
    {
        private static void Main(string[] args)
        {
            // foobar should not exist
            NTAccount nta = new NTAccount("foobar");
            try
            {
                nta.Translate(typeof(SecurityIdentifier));
            }
            catch
            {
                TmpFixIssue_32636();
            }
            nta.Translate(typeof(SecurityIdentifier));
        }

        private static void TmpFixIssue_32636()
        {
            Type slmh = typeof(NTAccount).Assembly.GetType("Microsoft.Win32.SafeHandles.SafeLsaMemoryHandle");
            FieldInfo fi = slmh.GetField("_invalidHandle", BindingFlags.Static | BindingFlags.NonPublic);
            foreach (ConstructorInfo ctor in fi.DeclaringType.GetConstructors(BindingFlags.NonPublic | BindingFlags.Instance))
            {
                ParameterInfo[] param = ctor.GetParameters();
                if (param.Length == 1 && param[0].ParameterType == typeof(IntPtr))
                {
                    fi.SetValue(null, ctor.Invoke(new object[] { IntPtr.Zero }));
                }
            }
        }
    }
```
We re-create disposed object.
@jkotas @stephentoub @bartonjs can you confirm that my idea is doable?

**Comment by jkotas** [comment]
The NuGet package with the fix is going to be published within a day to the preview feed at https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Security.Principal.Windows . If you are running into this bug, the best way to deal with it is to pick preview version of System.Security.Principal.Windows with the fix.

**Comment by MarcoRossignoli** [comment]
@jkotas thanks! @sajagi sajagi forgot my idea.

**Comment by sajagi** [comment]
Thanks everyone for quick fix! You guys are awesome.

**Comment by jrance** [comment]
Do you have an ETA of when this fix will be out of preview? I have a production app authenticating a large number of users and this bug has hit us a few dozen times since we upgrade our code to .NET Core 2.1. We had a fairly large scale impact when the AD team did a rolling reboot of the domain controllers which triggered this Win32Exception on most of our servers. I am implementing the temporary fix mentioned above but would like to know when the full fix will be ready for production.

**Comment by danmosemsft** [comment]
@jrance we haven't announced a release date for 3.0 yet.

**Comment by jrance** [comment]
Will this fix be require moving to 3.0 or will it be compatible with 2.1 once 3.0 is released?

**Comment by danmosemsft** [comment]
It is only in the 3.0 branches. If the impact is significant we could look at a back port. Are you able to use 2.2 or must it be 2.1?

**Comment by danmosemsft** [comment]
Also, we'd want to understand that the temporary "fix" wasn't sufficient.

**Comment by jrance** [comment]
This is a large enterprise application so we are more than likely going to want to stick with 2.1 for a while since it is an LTS release. I am testing the temporary fix right now and it seems to be working nicely, but using reflection to re-call the constructor of a static internal object seems less than ideal for a long term solution.

**Comment by danmosemsft** [comment]
@jrance it's not an ideal solution, but given 2.1 is very stable it's probably fairly safe to use this reflection as long as you remove it when you move to 3.0 (or whatever the next LTS is if you need that). Similarly, because we want to minimize change to 2.1 we would probably need a large impact (more users or no workaround) to justify a backport.

**Comment by jrance** [comment]
Thanks a lot for your quick responses. It makes sense that you would not want to backport this if it's not impacting a large number of users. The fix seems to be working well in our UAT environment so we will stick with that until we move to a new version of .NET Core.
