### ISSUE TITLE
"ASN1 corrupted data" on SignedCms in netcoreapp2.1 but not net472

### ISSUE THREAD

**Issue by vcsjones** [dotnet/corefx#32679]
A thought-related but different issue from #32639 is an issue with round-tripping a CMS that was made from bouncy castle. Given this code:

```csharp
var hex = File.ReadAllText("bc.txt");
var bytes = new byte[hex.Length / 2];
for (int i = 0, j = 0; j < hex.Length - 1; i++, j+=2)
{
    bytes[i] = byte.Parse(hex.Substring(j, 2), System.Globalization.NumberStyles.HexNumber);
}
var cms = new SignedCms();
cms.Decode(bytes);
var encoded = cms.Encode();
cms.Decode(encoded);
cms.CheckSignature(false);
```

File is available here: [bc.txt](https://github.com/dotnet/corefx/files/2454301/bc.txt)

This will fail in netcoreapp2.1 from 2.1.5 and System.Security.Cryptography.Pkcs with Version="4.5.1". However, this not raise any exceptions and work as-expected when run from net472:

<details>
<summary>Unhandled Exception: System.Security.Cryptography.CryptographicException: ASN1 corrupted data.</summary>
<pre>
   at System.Security.Cryptography.Asn1.AsnReader.ReadTagAndLength(Nullable`1& contentsLength, Int32& bytesRead)
   at System.Security.Cryptography.Asn1.AsnReader.PeekEncodedValue()
   at System.Security.Cryptography.Asn1.AsnReader.GetEncodedValue()
   at System.Security.Cryptography.Asn1.AsnWriter.WriteEncodedValue(ReadOnlyMemory`1 preEncodedValue)
   at System.Security.Cryptography.Asn1.AsnSerializer.<>c.<GetSimpleSerializer>b__19_5(Object value, AsnWriter writer)
   at System.Security.Cryptography.Asn1.AsnSerializer.<>c__DisplayClass18_0.<GetSerializer>b__2(Object obj, AsnWriter writer)
   at System.Security.Cryptography.Asn1.AsnSerializer.SerializeCustomType(Type typeT, Object value, AsnWriter writer, Asn1Tag tag)
   at System.Security.Cryptography.Asn1.AsnSerializer.SerializeCustomType(Type typeT, Object value, AsnWriter writer, Asn1Tag tag)
   at System.Security.Cryptography.Asn1.AsnSerializer.Serialize[T](T value, AsnEncodingRules ruleSet)
   at Internal.Cryptography.Helpers.EncodeContentInfo[T](T value, String contentType, AsnEncodingRules ruleSet)
   at System.Security.Cryptography.Pkcs.SignedCms.Encode()
</pre>
</details>

I've yet to dig deep in to the issue to understand what may be going wrong, but it is unlikely to be related to #32639. Even with a fix in for that issue, this still occurs.

**Comment by vcsjones** [comment]
It looks like the issue here is that the ASN.1 data for the ContentInfo contains a constructed octet string, which has an indefinite length. I don't believe this is acceptable under the DER encoding rules, only finite length constructed elements are permitted. The culprit are these octets:

```
24 80 04 55 56 65
72 73 69 6F 6E 3A 31 0A  0A 32 2E 31 36 2E 38 34
30 2E 31 2E 31 30 31 2E  33 2E 34 2E 32 2E 31 2D
48 61 73 68 3A 49 41 31  34 46 70 74 34 4A 36 5A
50 4F 5A 47 50 62 75 36  4A 67 6A 52 4B 69 69 30
66 4E 58 4A 36 5A 6B 78  74 6F 74 4B 66 57 33 38
3D 0A 0A 00 00
```

I've leave this issue open for @bartonjs and team to decide if this is "working as designed" or if there is action worth taking.

**Comment by vcsjones** [comment]
After looking through various RFCs - I don't think BER encoding rules should be allowed. From RFC2315:


>When a ContentInfo value is the inner content of signed-data, signed-and-enveloped-data, or digested-data content, a message-digest algorithm is applied to the contents octets of the DER encoding of the content field.

This CMS object is a signed data according to the OID in the message (1.2.840.113549.1.7.2). Thus in my opinion I think everything is working correctly.

**Comment by onovotny** [comment]
I will say the following

- there are signatures in the wild already that have this.
- Bouncy Castle creates the signature like this: https://github.com/onovotny/NuGetKeyVaultSignTool/blob/master/NuGetKeyVaultSignTool.Core/KeyVaultSignatureProvider.cs#L79-L116

**Comment by vcsjones** [comment]
>Bouncy Castle creates the signature like this

I'm far from an expert in BC, but it looks like BC will stick with BER encoding unless you use something like `DEROutputStream`. when calling `var encoded = data.GetEncoded();`. I think it's just a matter of telling BC to do the right thing.

**Comment by vcsjones** [comment]
@bartonjs If I am not mistaken, that PR is #30432, which went out in 2.1.3 (or 4?), so this broke very recently. Would it be fair then, to say that a servicing release to fix a regressing in a serving release is a good idea, and this might be worth fixing for 2.1.next?

**Comment by bartonjs** [comment]
It'd probably qualify for two reasons.  1) It was a servicing regression.  2) The user scenario that's broken is existing signed NuGet packages (as opposed to the more generic item in the description in the other issue of "compatibility with Bouncy Castle").

Looks like I have paperwork to fill out after they're both in.
