### ISSUE TITLE
FileInfo_GetSetTimes.CreationSetsAllTimes failure locally

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3272]
I get these failures locally every time I try to run the System.IO.FileSystem tests.  I'm on Windows 10 with VS2015.
```
System.IO.FileSystem.Tests.FileInfo_GetSetTimes.CreationSetsAllTimes [FAIL]
        Assert.All() Failure: 3 out of 6 items in the collection did not pass.
        [4]: Xunit.Sdk.InRangeException: Assert.InRange() Failure
             Range:  (635780099988667322 - 635780100048677127)
             Actual: 635779956018667322
                at Xunit.Assert.InRange[T](T actual, T low, T high, IComparer`1 comparer)
                at System.IO.FileSystem.Tests.FileInfo_GetSetTimes.<>c__DisplayClass4_0.<CreationSetsAllTimes>b__0(Tuple`3 tuple) in \corefx\src\System.IO.FileSystem\tests\FileInfo\GetSetTimes.cs:line 76
                at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action)
        [2]: Xunit.Sdk.InRangeException: Assert.InRange() Failure
             Range:  (635780099988667322 - 635780100048677127)
             Actual: 635779956018667322
                at Xunit.Assert.InRange[T](T actual, T low, T high, IComparer`1 comparer)
                at System.IO.FileSystem.Tests.FileInfo_GetSetTimes.<>c__DisplayClass4_0.<CreationSetsAllTimes>b__0(Tuple`3 tuple) in \corefx\src\System.IO.FileSystem\tests\FileInfo\GetSetTimes.cs:line 76
                at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action)
        [0]: Xunit.Sdk.InRangeException: Assert.InRange() Failure
             Range:  (635780099988667322 - 635780100048677127)
             Actual: 635779956018667322
                at Xunit.Assert.InRange[T](T actual, T low, T high, IComparer`1 comparer)
                at System.IO.FileSystem.Tests.FileInfo_GetSetTimes.<>c__DisplayClass4_0.<CreationSetsAllTimes>b__0(Tuple`3 tuple) in \corefx\src\System.IO.FileSystem\tests\FileInfo\GetSetTimes.cs:line 76
                at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action)
        Stack Trace:
           \corefx\src\System.IO.FileSystem\tests\FileInfo\GetSetTimes.cs(74,0): at System.IO.FileSystem.Tests.FileInfo_GetSetTimes.
  CreationSetsAllTimes()
```

**Comment by stephentoub** [comment]
It's also failing in OS X CI:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_mac_debug_tst/30/testReport/junit/System.IO.FileSystem.Tests/FileInfo_GetSetTimes/CreationSetsAllTimes/

**Comment by nguerrera** [comment]
I saw this last night on Linux locally too.

**Comment by ianhays** [comment]
Working on it now.

**Comment by ianhays** [comment]
Not sure how this passed the PR build check - it's failing on Windows too. I've got a fix coming in a minute, just want to test it some more before submission.

**Comment by ianhays** [comment]
It for some reason passes when I run build.cmd from src\ but not when I run just the FileSystem tests using corerun from the dnxcore50 folder.

**Comment by stephentoub** [comment]
Sounds like a timing issue.  When running build.cmd from src, you're likely going to end up with many test suites running concurrently.
