### ISSUE TITLE
UseCallback_HaveCredsAndUseAuthenticatedCustomProxyAndPostToSecureServer_Success failing in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#32808]
This test is failing a lot of outerloop runs in CI, e.g.
```
Windows.10.Nano.Amd64.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type System.Net.Http.HttpRequestException
Message :
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
-------- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
Stack Trace :
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 683
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\AuthenticationHelper.NtAuth.cs:line 43
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 496
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 467
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\AuthenticationHelper.cs:line 220
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 620
   at System.Threading.Tasks.ValueTask`1.get_Result() in E:\A\_work\164\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs:line 849
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 567
   at System.Threading.Tasks.ValueTask`1.get_Result() in E:\A\_work\164\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs:line 849
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 595
   at System.Threading.Tasks.ValueTask`1.get_Result() in E:\A\_work\164\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs:line 849
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 671
   at System.Threading.Tasks.ValueTask`1.get_Result() in E:\A\_work\164\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs:line 849
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 454
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\RedirectHandler.cs:line 33
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 475
   at System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.UseCallback_HaveCredsAndUseAuthenticatedCustomProxyAndPostToSecureServer_Success() in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ServerCertificates.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.HttpConnection.FillAsync() in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 1293
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 1245
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 512
----- Inner Stack Trace -----
```

**Comment by geoffkizer** [comment]
I see this periodically locally. Would be nice to get this addressed.

**Comment by karelz** [comment]
cc @wfurt if you are interested in tackling it ...

**Comment by scalablecory** [comment]
Have narrowed this down a little bit, is an interesting issue.

- CONNECT tunnel and authenticated proxy appear to be code exhibiting the issue. @geoffkizer does this jive with where you're seeing it?
- `LocalProxyServer` used in test does not close its client sockets. When altered to close properly the issue in `HttpClient` is hidden. So, issue may be related to connections being held open for longer than needed, but from what I can see `HttpClient` does not hang on to them even if server does.
- Connection reset is seen in client before proxy server socket is finalized/closed.
- Concurrency is needed to trigger reliably (16 concurrent runs per physical core seems to do it).
