### ISSUE TITLE
System.Diagnostics.Process brings down asp.net core app

### ISSUE THREAD

**Issue by kumpera** [dotnet/corefx#32832]
I'm spawning a process as part of an asp.net app and using the Process API brings down the whole thing down with this: 
```
Unhandled Exception: System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at WsProxy.Startup.<>c__DisplayClass8_1.<Configure>b__4(Object sender, DataReceivedEventArgs e) in /Users/kumpera/src/mono/sdks/wasm/ProxyDriver/Startup.cs:line 152
   at System.Diagnostics.Process.ErrorReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location where exception was thrown ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__17_0(Object edi)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

I'm using `BeginErrorReadLine` and `BeginOutputReadLine` and this reliably happens every time.

I'm using 2.1.302

**Comment by stephentoub** [comment]
Can you share a repro?  What is the code in /Users/kumpera/src/mono/sdks/wasm/ProxyDriver/Startup.cs:line 152 doing?  It appears to be trying to create a TaskCompletionSource that's specific to your code and that's already been completed, so it's throwing.

**Comment by kumpera** [comment]
ugg, I need coffee. 🤦‍♂️
