### ISSUE TITLE
IndexOutOfRangeException in NumberFormatInfo

### ISSUE THREAD

**Issue by Tratcher** [dotnet/corefx#32870]
_From @bmpcon on Friday, 17 August 2018 08:49:05_

Hello,

when deploying a vanilla ASP.NET Core (2.1.1) WebApi application to our enterprise server (Windows 2016) we get the following exception when doing a request from localhost:

```
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLG41UURV0D2", Request id "0HLG41UURV0D2:00000001": An unhandled exception was thrown by the application.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Globalization.CultureData.GetNFIValues(NumberFormatInfo nfi)
   at System.Globalization.NumberFormatInfo..ctor(CultureData cultureData)
   at System.Globalization.CultureInfo.get_NumberFormat()
   at System.Globalization.NumberFormatInfo.get_CurrentInfo()
   at System.Int32.TryParse(String s, Int32& result)
   at Microsoft.AspNetCore.HttpOverrides.Internal.IPEndPointParser.TryParse(String addressWithPort, IPEndPoint& endpoint)
   at Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware.ApplyForwarders(HttpContext context)
   at Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware.Invoke(HttpContext context)
  at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```

As a workaround we were able to solve the problem with changing the thread culture to en-us:
```
private static void SetCultureToUs()
{
    var cultureInfo = new CultureInfo("en-US");
    CultureInfo.DefaultThreadCurrentCulture = cultureInfo;
    CultureInfo.DefaultThreadCurrentUICulture = cultureInfo;
}
```

_Copied from original issue: aspnet/BasicMiddleware#356_

**Comment by davidsh** [comment]
@Tratcher 

Isn't this a bug in ASP.NET code?

>https://github.com/aspnet/BasicMiddleware/blob/1203bcf63dc793ae3f7c9217bb2a46727bae9348/src/Microsoft.AspNetCore.HttpOverrides/Internal/IPEndPointParser.cs#L65

**Comment by Tratcher** [comment]
We've dealt with the ASP.NET issue, but there's still a corefx issue here:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Globalization.CultureData.GetNFIValues(NumberFormatInfo nfi)
   at System.Globalization.NumberFormatInfo..ctor(CultureData cultureData)
   at System.Globalization.CultureInfo.get_NumberFormat()
   at System.Globalization.NumberFormatInfo.get_CurrentInfo()
   at System.Int32.TryParse(String s, Int32& result)
```

**Comment by davidsh** [comment]
>We've dealt with the ASP.NET issue, but there's still a corefx issue here:

What is the corefx issue?  A problem in `Int32.Parse` ?

**Comment by Tratcher** [comment]
Why is the NumberFormatInfo.CurrentInfo property throwing an IndexOutOfRangeException?

**Comment by stephentoub** [comment]
What was the culture that caused the exception to be thrown?

**Comment by Tratcher** [comment]
@bmpcon?

**Comment by tarekgh** [comment]
@Tratcher  is there a way to print the CultureInfo.CurrentCulture.Name in your repro?

**Comment by Tratcher** [comment]
I don't have a repro. This was externally reported by @bmpcon

**Comment by tarekgh** [comment]
@bmpcon could you please print the CultureInfo.CurrentCulture.Name in your repro and it to us?

**Comment by tarekgh** [comment]
I have installed Server 2016 and tried all cultures on system and couldn't repro the issue. 

@bmpcon  please provide what current culture used in your case or better if you provide a repro. I'll close this issue for now till you get us the needed information and we can re-open.

**Comment by bmpcon** [comment]
Hello,

we are still facing this issues and even when trying to run .NET Core based VSTS Agent on local server we get the same error:

```
[2019-01-23 01:44:09Z INFO AgentProcess] Agent is built for Windows (X64) - win-x64.
[2019-01-23 01:44:09Z INFO AgentProcess] RuntimeInformation: Microsoft Windows 10.0.14393 .
[2019-01-23 01:44:09Z INFO AgentProcess] Version: 2.141.1
[2019-01-23 01:44:09Z INFO AgentProcess] Commit: 8c0163e534b3740f4959826c54b099d679a64458
**[2019-01-23 01:44:09Z INFO AgentProcess] Culture: sv-SE
[2019-01-23 01:44:09Z INFO AgentProcess] UI Culture: en-US**
[2019-01-23 01:44:15Z INFO AgentCapabilitiesProvider] Adding 'Agent.HomeDirectory': 'D:\Programme\Microsoft vsts agent\vsts-agent-win-x64-2.141.1'
[2019-01-23 01:44:15Z INFO MessageListener] Loading Credentials
[2019-01-23 01:44:15Z INFO ConfigurationStore] HasCredentials()
[2019-01-23 01:44:15Z INFO ConfigurationStore] stored True
[2019-01-23 01:44:15Z INFO CredentialManager] GetCredentialProvider
[2019-01-23 01:44:15Z INFO CredentialManager] Creating type OAuth
[2019-01-23 01:44:15Z INFO CredentialManager] Creating credential type: OAuth
[2019-01-23 01:44:15Z INFO HostContext] Well known directory 'Bin': 'D:\Programme\Microsoft vsts agent\vsts-agent-win-x64-2.141.1\bin'
[2019-01-23 01:44:15Z INFO HostContext] Well known directory 'Root': 'D:\Programme\Microsoft vsts agent\vsts-agent-win-x64-2.141.1'
[2019-01-23 01:44:15Z INFO HostContext] Well known config file 'RSACredentials': 'D:\Programme\Microsoft vsts agent\vsts-agent-win-x64-2.141.1\.credentials_rsaparams'
[2019-01-23 01:44:15Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file D:\Programme\Microsoft vsts agent\vsts-agent-win-x64-2.141.1\.credentials_rsaparams
[2019-01-23 01:44:15Z ERR  Terminal] WRITE ERROR: An error occurred: Index was outside the bounds of the array.
[2019-01-23 01:44:15Z ERR  AgentProcess] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Globalization.CultureData.GetNFIValues(NumberFormatInfo nfi)
   at System.Globalization.NumberFormatInfo..ctor(CultureData cultureData)
   at System.Globalization.CultureInfo.get_NumberFormat()
   at System.Globalization.NumberFormatInfo.get_CurrentInfo()
   at Microsoft.VisualStudio.Services.Agent.Util.VssUtil.CreateConnection(Uri serverUri, VssCredentials credentials, IEnumerable`1 additionalDelegatingHandler)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.CreateSessionAsync(CancellationToken token)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.MainAsync(IHostContext context, String[] args)
```

**Comment by tarekgh** [comment]
Thanks @bmpcon for the more info. I'll try to take a look and get back to you in few days.

**Comment by stephentoub** [comment]
Do you have any custom culture data installed for the sv-SE culture?

From a cursory inspection of the method, it would seem this could only come from:
https://github.com/dotnet/coreclr/blob/e0d680101a93797c9e1a049bf582a874e2cb4113/src/System.Private.CoreLib/shared/System/Globalization/CultureData.cs#L2364
which assumes we'll get back exactly ten characters from the call to Windows (one for each digit 0 to 9).

Could you try running this and sharing the output:
```C#
using System;
using System.Runtime.InteropServices;

unsafe class Program
{
    static void Main()
    {
        string withOverride = GetDigits("sv-SE", true);
        string withoutOverride = GetDigits("sv-SE", false);
        Console.WriteLine("With:    " + withOverride);
        Console.WriteLine("Without: " + withoutOverride);
    }

    private static string GetDigits(string localeName, bool useUserOverride)
    {
        uint lctype = 0x00000013; // DIGITS
        if (useUserOverride) lctype |= 0x80000000; // NOUSEROVERRIDE

        const int BUFFER_SIZE = 1024;
        char* pBuffer = stackalloc char[BUFFER_SIZE];
        int resultCode = GetLocaleInfoEx(localeName, lctype, pBuffer, BUFFER_SIZE);
        return resultCode > 0 ? new string(pBuffer) : null;
    }

    [DllImport("kernel32.dll", CharSet = CharSet.Unicode)]
    internal static extern int GetLocaleInfoEx(string lpLocaleName, uint LCType, void* lpLCData, int cchData);
}
```
?

**Comment by tarekgh** [comment]
nit: 
the line 

```C#
if (useUserOverride) lctype |= 0x80000000;
```

should be 

```C#
if (!useUserOverride) lctype |= 0x80000000;
```

**Comment by tarekgh** [comment]
@bmpcon did you have a chance to try what @stephentoub suggested?

**Comment by tarekgh** [comment]
@bmpcon I am closing this one and we can reopen when we have more information. Thanks.

**Comment by nblumhardt** [comment]
Adding a report in case it helps; unfortunately not first-hand: a user with Dutch regional settings has encountered this - https://docs.datalust.co/discuss/5cd584b1e49ab70023d99d93 - also worked around by switching to en-US.

(`Int32.TryParse()` must have been inlined and is missing from the stack trace, but that's what we're calling.)

The code in question is running at application startup, so hopefully before any of our unsafe code would have a chance to clobber the number format's `Digits` array :-)

If we surface any more info I'll pass it along.

**Comment by tarekgh** [comment]
It would be a good idea if you can collect the registry contents on the failing machine of the following registry paths:

```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls
HKEY_CURRENT_USER\Control Panel\International
```

Maybe this can give any clue.
