### ISSUE TITLE
XmlWriterTestModule.TCCloseOutput failing in outer loop

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3290]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_outerloop_windows_release/703/console
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_outerloop_windows_debug/705/console
```
TestCase:XmlWriterSettings: CloseOutput - 
  File Not Found: writer.out
  	Check that underlying stream is NOT CLOSED when CloseOutput = FALSE and Create(TextWriter)
  unexpected exception happend:Object reference not set to an instance of an object.
     at XmlCoreTest.Common.FilePathUtil.getStream(String filename) in d:\j\workspace\dotnet_corefx_outerloop_windows_debug\src\Common\tests\SystemXml\XmlCoreTest\FilePathUtil.cs:line 173
     at XmlWriterAPI.Test.TCCloseOutput.CloseOutput_1() in d:\j\workspace\dotnet_corefx_outerloop_windows_debug\src\System.Xml.ReaderWriter\tests\Writers\XmlWriterApi\XmlFactoryWriterTests.cs:line 2258
     at OLEDB.Test.ModuleCore.CVariation.Execute() in d:\j\workspace\dotnet_corefx_outerloop_windows_debug\src\Common\tests\SystemXml\ModuleCore\cvariation.cs:line 74
     at OLEDB.Test.ModuleCore.CTestCase.Execute() in d:\j\workspace\dotnet_corefx_outerloop_windows_debug\src\Common\tests\SystemXml\ModuleCore\ctestcase.cs:line 69
  	 FAILED
  File Not Found: writer.out
  	Check that underlying stream is NOT CLOSED when CloseOutput = FALSE and Create(Stream)
  unexpected exception happend:Object reference not set to an instance of an object.
     at XmlCoreTest.Common.FilePathUtil.getStream(String filename) in d:\j\workspace\dotnet_corefx_outerloop_windows_debug\src\Common\tests\SystemXml\XmlCoreTest\FilePathUtil.cs:line 173
     at XmlWriterAPI.Test.TCCloseOutput.CloseOutput_1() in d:\j\workspace\dotnet_corefx_outerloop_windows_debug\src\System.Xml.ReaderWriter\tests\Writers\XmlWriterApi\XmlFactoryWriterTests.cs:line 2258
     at OLEDB.Test.ModuleCore.CVariation.Execute() in d:\j\workspace\dotnet_corefx_outerloop_windows_debug\src\Common\tests\SystemXml\ModuleCore\cvariation.cs:line 74
     at OLEDB.Test.ModuleCore.CTestCase.Execute() in d:\j\workspace\dotnet_corefx_outerloop_windows_debug\src\Common\tests\SystemXml\ModuleCore\ctestcase.cs:line 69
  	 FAILED
```

**Comment by stephentoub** [comment]
@krwq, this is failing consistently, both in the lab and locally for me.  It looks like a real regression.  Can you take a look?
