### ISSUE TITLE
An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#32971]
```
PlatformName/Darwin 18.0.0
```

First make a httprequest that fails with the following error:

```
[2018-10-11 17:07:40.005 Agent.Proxy W] Connecting to <https://insiders.liveshare.vsengsaas.visualstudio.com/19c7d07f> via proxy failed with exception System.Net.Http.HttpRequestException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address.
Parameter name: hostName ---> System.ArgumentException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address.
Parameter name: hostName
   at System.Net.Dns.HostResolutionBeginHelper(String hostName, Boolean justReturnParsedIp, Boolean throwOnIIPAny, AsyncCallback requestCallback, Object state)
   at System.Net.Dns.BeginGetHostAddresses(String hostNameOrAddress, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.MultipleConnectAsync.StartConnectAsync(SocketAsyncEventArgs args, DnsEndPoint endPoint)
   at System.Net.Sockets.Socket.ConnectAsync(SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e)
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
```

other subsequent httprequests fail with this error,

```
[2018-10-11 17:08:12.389 Agent.Rpc.Auth E] HTTP exception in auth.login request handler: System.Net.Http.HttpRequestException: An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance. ---> System.InvalidOperationException: An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.
   at System.Net.Sockets.SocketAsyncEventArgs.ThrowForNonFreeStatus(Int32 status)
   at System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(Socket socket, SocketAsyncOperation operation)
   at System.Net.Sockets.Socket.ConnectAsync(SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e)
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Cascade.Tracing.TracingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in E:\A\_work\64\s\src\Common\Tracing\TracingHttpMessageHandler.cs:line 64
   at Microsoft.Cascade.Agent.ForwardResponseMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in E:\A\_work\64\s\src\Agent\ForwardResponseMessageHandler.cs:line 50
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
```

Using different instances of httpclient and httpclienthandler for both requests.

**Comment by stephentoub** [comment]
This looks like a long-standing bug in Socket.ConnectAsync that exists in both .NET Framework and .NET Core.  It just so happens to show up when using SocketsHttpHandler because it uses Socket.ConnectAsync.

**Comment by stephentoub** [comment]
(I'm specifically referring to the second failure, which I assume is what this issue is about.  The first exception is expected if you try to connect to an address like "http://0.0.0.0" or "http://[::0]".)

**Comment by davidalbertonogueira** [comment]
> (I'm specifically referring to the second failure, which I assume is what this issue is about. The first exception is expected if you try to connect to an address like "http://0.0.0.0" or "http://[::0]".)

So @stephentoub , how to overcome this and be able to connect to other services running in the same local host?

**Comment by stephentoub** [comment]
> how to overcome this and be able to connect to other services running in the same local host?

The issue was fixed.  What is the remaining concern?
