### ISSUE TITLE
SqlClient CryptographicException is back again on Mojave 10.14

### ISSUE THREAD

**Issue by facundofarias** [dotnet/corefx#33087]
Hey guys, this seems related to #28652.

I was on OSX 10.13.* and it was all good. Then I've updated to Mojave (my mistake) and I am getting the following exception while trying to connect to MySQL:

```
System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
   at Internal.Cryptography.Pal.SecTrustChainPal.ParseResults(SafeX509ChainHandle chainHandle, X509RevocationMode revocationMode)
   at Internal.Cryptography.Pal.SecTrustChainPal.Execute(DateTime verificationTime, Boolean allowNetwork, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationFlag revocationFlag)
   at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
   at System.Net.CertificateValidationPal.VerifyCertificateProperties(SafeDeleteContext securityContext, X509Chain chain, X509Certificate2 remoteCertificate, Boolean checkCertName, Boolean isServer, String hostName)
   at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback, ProtocolToken& alertToken)
   at System.Net.Security.SslState.CompleteHandshake(ProtocolToken& alertToken)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
```

I've already tried updating my dotnet installation as explained [here](https://www.microsoft.com/net/learn/dotnet/hello-world-tutorial), and I've also updated xcode to the latest release, not none of them worked.

Any ideas?

**Comment by karelz** [comment]
@bartonjs can you please check it out?

**Comment by bartonjs** [comment]
I've tried building chains with a variety of success and failure conditions and haven't hit this (10.41.1 Beta 18B73a).  @facundofarias have you seen this against a host that I could connect to (I don't need credentials, just a host that's Internet-exposed)?

**Comment by facundofarias** [comment]
@bartonjs In my case, it's a MySQL database running inside a docker container (that we use for mainly for development). 

The **docker-compose.yml** looks like this:
```
version: '3'

services:

  sample-mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=SampleDatabase
      - MYSQL_USER=root
      - MYSQL_PASSWORD=toor
```
Thanks!

**Comment by bartonjs** [comment]
@facundofarias Can you "pretend" that I've never actually used Docker and help me understand what to do with that? :smile:

**Comment by facundofarias** [comment]
Haha, yes, sorry @bartonjs.

So, I've created a docker container with a MySQL instance, using the docker-compose file that I've attached, and then I am trying to connect to that database using EntityFramework (2.0.3) and Pomelo SQL Client (2.0.1).

And this is my `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.101 [/usr/local/share/dotnet/sdk]
  2.1.301 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.403 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by facundofarias** [comment]
Hey @bartonjs 

I've just updated Visual Studio for Mac, version 7.6.11 (build 9), and magically, the problem seems to be solved. Any ideas?

Thanks anyway!

**Comment by bobRafat** [comment]
Hey guys, any update on this? I'm having the same issue and I upgraded my Visual studio to version 7.6.11 and it didn't help.

**Comment by facundofarias** [comment]
Hey @bobRafat, which `dotnet` are you using?

**Comment by bobRafat** [comment]
Here is my environment info,

```
17:24 $ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.500/

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8
```

My solution was using dotnet 2.0.1, so I had to update it to 2.1 and now it works fine.

**Comment by bartonjs** [comment]
Since everyone involved has described their problem as mitigated, and there hasn't been anything new since November, closing.
