### ISSUE TITLE
An item with the same key has already been added. Key: System.Net.Http.Headers.HeaderDescriptor

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#33109]
Run the following repro

```c#
using System.Threading.Tasks;
using System.Net.Http;
using System.Net.Http.Headers;

class X {

	private HttpClient _httpClient;

	void Foo ()
	{
		_httpClient = new HttpClient ();
		_httpClient.DefaultRequestHeaders.UserAgent.Add (new ProductInfoHeaderValue ("name", "version"));
		_httpClient.DefaultRequestHeaders.UserAgent.Add (new ProductInfoHeaderValue ("(comment)"));
	}

	private async Task DoIt () => await Task.Run (DoThat);

	private async Task DoThat ()
	{
		//
		// This does not always throw exception but should, someone is modifying default headers while other requests are in flight
		//
		_httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue ("ping", "pong");

		await _httpClient.GetAsync ("http://neverssl.com");
	}

	public static void Main ()
	{
		while (true) {
			var x = new X ();
			x.Foo ();
			Task.WhenAll (x.DoIt (), x.DoIt ()).Wait ();
		}
	}
}
```

When it hits race when setting up the request if terminates with the following exception
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (An item with the same key has already been added. Key: System.Net.Http.Headers.HeaderDescriptor) ---> System.ArgumentException: An item with the same key has already been added. Key: System.Net.Http.Headers.HeaderDescriptor
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Net.Http.Headers.HttpHeaders.GetOrCreateHeaderInfo(HeaderDescriptor descriptor, Boolean parseRawValues)
   at System.Net.Http.Headers.HttpHeaders.SetParsedValue(HeaderDescriptor descriptor, Object value)
   at System.Net.Http.Headers.HttpRequestHeaders.set_Authorization(AuthenticationHeaderValue value)
   at X.DoThat() in /Users/marek/git/mono/mono/mcs/class/System.Core/temp/Program.cs:line 23
   at X.DoIt() in /Users/marek/git/mono/mono/mcs/class/System.Core/temp/Program.cs:line 16
```

The code is racy but I think we should do better job by making the failure more obvious

**Comment by karelz** [comment]
Looks like we need to use `TryAdd` here instead:
https://github.com/dotnet/corefx/blob/9302749dae5ee81e859c22a75623c06e7bbb95f2/src/System.Net.Http/src/System/Net/Http/Headers/HttpHeaders.cs#L745

Should be fairly straightforward.

**Comment by marek-safar** [comment]
I am not sure that's the right fix, it'd just hide the exception and you'd still have problems in other methods (instead of Add you can call Clear, etc). 

One solution would be to always throw when DefaultRequestHeaders is modified when there is a request in flight.

**Comment by stephentoub** [comment]
DefaultRequestHeaders, like the rest of the properties on HttpClient, is not meant to be modified once any request has been issued; doing so is a bug in the user code (there are many other ways that failure could manifest, including other exceptions or just unannounced corruption of the data structures).  This doesn't appear to be documented, but should be.  The other properties all throw if used after any request has been issued, but because of the (arguably flawed) design of DefaultRequestHeaders, there isn't a great way to achieve that; it just has a getter that returns the HttpRequestHeaders collection, which is sealed, and thus the HttpClient can't inject a check into operations on the HttpRequestHeaders that mutate it.

If we actually want to address this (I'm not sure it's worth the resulting breaks), I think we would need to do something like augment the HttpRequestHeaders with an internal constructor that takes a `StrongBox<bool>`, have the HttpRequestHeaders check and throw if on any mutation that box is non-null and contains `true`, and have the HttpClient construct this default headers collection using a box it also holds a reference to and uses for tracking whether the operation has started instead of its own private bool field.

**Comment by marek-safar** [comment]
I agree it's a bug in user code but we should make it easier for the developers to find it. The way it manifests today is quite random even if we know the behaviour is not allowed by design.

Another solution how to actually make it work is to copy all default headers in thread safe way at beginning of each request to the request headers.

**Comment by stephentoub** [comment]
> Another solution how to actually make it work is to copy all default headers in thread safe way at beginning of each request to the request headers.

That's likely technically possible, but would also likely mean that not only would every mutation require taking a lock, but worse every request would need to hold a lock while copying all header data from the source collection to the destination collection.  We've tried to minimize such locking as we've seen it quickly become a scalability bottleneck, e.g. https://github.com/dotnet/corefx/pull/32495.

**Comment by marek-safar** [comment]
That's correct but only if you are using shared HttpClient for multiple concurrent requests which I am not sure it's the recommended setup for highly scalable workloads.

**Comment by stephentoub** [comment]
> but only if you are using shared HttpClient for multiple concurrent requests which I am not sure it's the recommended setup for highly scalable workloads.

That's exactly the recommended setup for highly-scalable workloads :)

**Comment by johmills** [comment]
FYI, it also blows up on HttpHeaders.ToString or even just get_ContentLength since they both force a calculation.

**Comment by karelz** [comment]
Triage:
`DefaultRequestHeaders` is not thread safe, the recommended pattern is to set it before first request. No manipulation later is expected.

Technically it is hard for us to check the additions here (although we check other properties on `HttpClientHandler`).

The best next step is to clarify this behavior and guidance in documentation.
