### ISSUE TITLE
Error loading System.Buffers, Version=4.0.2.0 when using AspNet Core SignalR C# client in a .NET Framework 4.7.1 Web test

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/corefx#33148]
1. clone to get the signalr chat sample at https://github.com/aspnet/SignalR-samples/tree/master/ChatSample
2. open the solution, restore nuget package and Ctrl+F5 to run the service
3. clone the webtest repro project at https://github.com/jeremymeng/WebTestRepro
4. open `WebAndLoadTestProject2.sln`, restore then build the project. You will need the web test payload for your visual studio installation to support this type of project.
![image](https://user-images.githubusercontent.com/7583839/47753663-94b4ae00-dc55-11e8-81c5-8f5dbda8f31f.png)
5. notice that the `bin\Debug` directory has 41 files
6. now open the webtest.webtest file in visual studio. select Debug Test, pause before starting from the drop down

![image](https://user-images.githubusercontent.com/7583839/47753754-dcd3d080-dc55-11e8-9198-8af3ecd1ee42.png)

7. under web test solution folder, check the most recent `TestResults\<user_machineName timestamp>\Out` folder. This is where the test is actually running. The folder only has 25 files under it. (This could be a bug in Web Test framework. I already logged a separate internal bug against VSTT team)
8. copy all files from bin\Debug folder into the Out folder (skip existing)
9. click Run button (the first button) to continue the web test
![image](https://user-images.githubusercontent.com/7583839/47753925-77ccaa80-dc56-11e8-8da4-d5de06723800.png)

**Actual:**
```
System.IO.InvalidDataException
  HResult=0x80131501
  Message=Invalid negotiation response received.
  Source=Microsoft.AspNetCore.Http.Connections.Common
  StackTrace:
   at Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(Stream content)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<NegotiateAsync>d__45.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<GetNegotiationResponseAsync>d__52.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<SelectAndStartTransport>d__44.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<StartAsyncCore>d__41.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<StartAsync>d__40.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.<ConnectAsync>d__3.MoveNext()
   at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.<ConnectAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__31.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsync>d__24.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at iRel8.Service.WebTests.WebtestPlugins.SignalRJoinRoomPlugin.<PreRequest>d__0.MoveNext() in C:\github\jeremymeng\WebTestRepro\WebAndLoadTestProject2\SignalRJoinRoomPlugin.cs:line 16

Inner Exception 1:
TypeInitializationException: The type initializer for 'JsonArrayPool`1' threw an exception.

Inner Exception 2:
FileNotFoundException: Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
```

**Comment by jeremymeng** [comment]
I've shared a msbuild.binlog at `\\scratch2\scratch\yumeng\WebTestRepro\msbuild.binlog`

**Comment by jeremymeng** [comment]
same test code runs find in a 4.7.1 WPF app
```csharp
            var baseUrl = "http://localhost:15935";

            var connection = new HubConnectionBuilder()
                .WithUrl($"{baseUrl}/chat")
                .Build();

            await connection.StartAsync();
```

**Comment by karelz** [comment]
cc @joperezr @wtgodbe

**Comment by GSPP** [comment]
@jeremymeng this could be related to https://github.com/dotnet/corefx/issues/30642. There's currently a lot of trouble with wrong binding redirects being added by NuGet. I have made a list of related issues: https://github.com/dotnet/standard/issues/481#issuecomment-429643615

**Comment by joperezr** [comment]
I believe that what might be happening here is that the right binding redirects are not being added as System.Buffers might be an implementation-only dependency. In order to check if this is the case, @jeremymeng do you mind running fuslogvw when the error happens so that we can check who is trying to load System.Buffers? Also, do you have any binding redirects present in your App.config?

**Comment by joperezr** [comment]
Actually now that I have tried to repro this, I do have a binding redirect created for me for System.Buffers so I can't really repro this. I've also just checked in your binlog and it looks like there was a binding redirect suggested as well for System.Buffers that would have fixed this. Do you have auto binding redirects turned on?

**Comment by jeremymeng** [comment]
I have tried with auto binding redirects on/off but didn't see any difference.  Where did you see the binding redirect created? In my webtest project I don't see any app.config or web.config.

**Comment by jeremymeng** [comment]
fusion logs are shared at \\scratch2\scratch\yumeng\fuslogs.  The error for System.Buffers

```
LOG: Attempting download of new URL file:///C:/github/jeremymeng/WebTestRepro/TestResults/yumeng_YU-Z230 2018-10-31 10_03_52/Out/System.Buffers.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\github\jeremymeng\WebTestRepro\TestResults\yumeng_YU-Z230 2018-10-31 10_03_52\Out\System.Buffers.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: The assembly reference did not match the assembly definition found.
ERR: Run-from-source setup phase failed with hr = 0x80131040.
```

**Comment by joperezr** [comment]
> Where did you see the bidning redirect created?

If you check the ResolveAssemblyReferences target, RAR noticed there was a conflict with the versions of System.Buffers so it suggested a binding redirect that will force the 4.0.3 version to be loaded (which is the one that you found according to the fuslog). If you have auto binding redirects turned on, then we should be adding these binding redirects that RAR suggested into your resulting config file (meaning the one located at bin/Debug. If this is a web project, then when turning auto generate binding redirects on you should get a warning when building telling you you need some redirects, which when double clicking the warning should add them to your web.config.

**Comment by jeremymeng** [comment]
My project is a **WebTest** project (Output Type of Class Library).  I don't get any warnings or errors when building the project in Visual Studio. There are no *.config files under `bin\Debug` even I have auto generate binding redirects on

![image](https://user-images.githubusercontent.com/7583839/47806920-10ffcd80-dcf8-11e8-8f25-930d20603563.png)

```
1>CopyFilesToOutputDirectory:
1>  Copying file from "obj\Debug\WebAndLoadTestProject2.dll" to "bin\Debug\WebAndLoadTestProject2.dll".
1>  WebAndLoadTestProject2 -> C:\github\jeremymeng\WebTestRepro\WebAndLoadTestProject2\bin\Debug\WebAndLoadTestProject2.dll
1>  Copying file from "obj\Debug\WebAndLoadTestProject2.pdb" to "bin\Debug\WebAndLoadTestProject2.pdb".
1>
1>Build succeeded.
1>    0 Warning(s)
1>    0 Error(s)
1>
1>Time Elapsed 00:00:00.41
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```
The config files I saw from fuslog are
```
LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\QTAgent32_40.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
```

**Comment by mgoldhgb** [comment]
I am having this exact same problem.  I am running the ASP.NET Core Client code in a Standard 2.0 Library and referencing it from a framework application (4.7.2).  I have tried everything from adding binding redirects to removing all references.

When calling SendAsync using ASPNetCore signalr
I'm getting "Invalid negotiation response received."
Inner exception:
"Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

Here is the stack trace:

"   at Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(Stream content)\r\n   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<NegotiateAsync>d__44.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<GetNegotiationResponseAsync>d__51.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<SelectAndStartTransport>d__43.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<StartAsyncCore>d__40.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<StartAsync>d__39.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.<ConnectAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.<ConnectAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__47.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsync>d__39.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at GTA.PushNotifications.SignalRCore.Helpers.SignalRPushNotificationHelper.<Notify>d__4`2.MoveNext()"

**Comment by ashuthinks** [comment]
any solution you have got for this? 
I'm also facing the same issue.

**Comment by joperezr** [comment]
@ashuthinks do you mind sharing your msbuild.binlog so that we can better analyze what is going on? to generate one, please run `msbuild yourProject.csproj /t:rebuild /bl` and I'll take a look. If you could also share the contents of your App.config file in case you have one, that would be valuable.

**Comment by AleXr64** [comment]
@ashuthinks try to update all nuget packets in client poject. This worked for me.

**Comment by StanislavChankov** [comment]
I am encountering exactly the same issue with Unity3d client.

**Comment by Rakiah** [comment]
I have the exact same problem, I tried everything I could find on the internet i'm completely clueless now..
