### ISSUE TITLE
Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by Mogikan** [dotnet/corefx#33188]
I created .NET Core console app and added reference to System.Drawing.Common nuget. I'm trying to run the following code from [docs](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-determine-the-parameters-supported-by-an-encoder), but it fails on bitmap1.GetEncoderParameterList with System.OverflowException:

'Arithmetic operation resulted in an overflow.'

What is wrong with this code? Do I make something illegal?

```
class Program
{

   public static void Main(string[] args)
   {
      new Program().GetSupportedParameters();
   }
   private void GetSupportedParameters()
   {
       Bitmap bitmap1 = new Bitmap(1, 1);
       ImageCodecInfo jpgEncoder = GetEncoder(ImageFormat.Jpeg);
       //this one also does not work:
       //Bitmap bitmap1 = new Bitmap(Image.FromFile(@"C:\temp\0\2.png"));
       //ImageCodecInfo jpgEncoder = GetEncoder(ImageFormat.Png);
       EncoderParameters paramList = bitmap1.GetEncoderParameterList(jpgEncoder.Clsid);
       EncoderParameter[] encParams = paramList.Param;
       StringBuilder paramInfo = new StringBuilder();

       for (int i = 0; i < encParams.Length; i++)
       {
           paramInfo.Append("Param " + i + " holds " + encParams[i].NumberOfValues +
                    " items of type " +
                encParams[i].ValueType + "\r\n" + "Guid category: " + encParams[i].Encoder.Guid + "\r\n");

       }            
   }

   private ImageCodecInfo GetEncoder(ImageFormat format)
   {
       ImageCodecInfo[] codecs = ImageCodecInfo.GetImageDecoders();

       foreach (ImageCodecInfo codec in codecs)
       {
          if (codec.FormatID == format.Guid)
          {
               return codec;
          }
       }
       return null;
    }
 }
```
StackTrace:

```
at System.Drawing.Imaging.EncoderParameters.ConvertFromMemory(IntPtr memory)
at System.Drawing.Image.GetEncoderParameterList(Guid encoder)
at ConsoleApp16.Program.GetSupportedParameters() in Program.cs:line 19
at ConsoleApp16.Program.Main(String[] args)
in Program.cs:line 13
```

This one also crashes:

```
Bitmap bitmap1 = new Bitmap(Image.FromFile(@"C:\temp\0\2.png"));
ImageCodecInfo jpgEncoder = GetEncoder(ImageFormat.Png);
```

**Comment by danmosemsft** [comment]
Same on .NEt Framework (with built in System.Drawing.*) ?

**Comment by danmosemsft** [comment]
Thanks for the information. It's a little surprising that Desktop behaves differently, since the code was ported mostly verbatim.
Just to set expectations it may be a while before we can look at this so if you wish to look at a fix that would be welcomed.
