### ISSUE TITLE
CurlHandler throwing NotImplementedException for non-http/https schemes

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3322]
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.cs#L276-L279

Even if we're supposed to throw here, it shouldn't be NotImplemented.ByDesignWithMessage, more likely PlatformNotSupportedException.

That said, this might be dead code: it looks like checks for the sheme happen before we even get to this point:
```
Unhandled Exception: System.ArgumentException: Only 'http' and 'https' schemes are allowed.
Parameter name: requestUri
   at System.Net.Http.HttpRequestMessage.InitializeValues(HttpMethod method, Uri requestUri)
   at System.Net.Http.HttpRequestMessage..ctor(HttpMethod method, Uri requestUri)
   at System.Net.Http.HttpClient.GetAsync(Uri requestUri, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetContentAsync[T](Uri requestUri, HttpCompletionOption completionOption, T defaultValue, Func`2 readAs)
   at System.Net.Http.HttpClient.GetStringAsync(Uri requestUri)
   at System.Net.Http.HttpClient.GetStringAsync(String requestUri)
```

So potentially this might just need to be changed to an assert.

**Comment by SidharthNabar** [comment]
Just FYI - if I try this on Windows implementation, I get the exception with the stack trace that Stephen has pasted above. And it does come from the HttpClient layer, even before getting to WinHttpHandler.
