### ISSUE TITLE
ReadOnlySequence.Slice which accepts a SequencePosition throws ArgumentOutOfRangeException unexpectedly.

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#33291]
```C#
[Fact]
public static void ReadOnlySequenceTest()
{
    string jsonString = "a";

    ReadOnlyMemory<byte> dataMemory = Encoding.UTF8.GetBytes(jsonString);

    var firstSegment = new BufferSegment<byte>(dataMemory.Slice(0, 1));
    ReadOnlyMemory<byte> secondMem = dataMemory.Slice(0, 0);
    BufferSegment<byte> secondSegment = firstSegment.Append(secondMem);

    // A two segment sequence where the second one is empty: [a]-> []
    var sequence = new ReadOnlySequence<byte>(firstSegment, 0, secondSegment, secondMem.Length);

    SequencePosition expectedPosition = sequence.GetPosition(1);
    Console.WriteLine(expectedPosition.GetInteger());   // 0
    Console.WriteLine(expectedPosition.GetObject());    // System.Text.Json.Tests.BufferSegment`1[System.Byte]
    Assert.True(((ReadOnlySequenceSegment<byte>)expectedPosition.GetObject()).Memory.IsEmpty);

    SequencePosition actualPosition = sequence.Slice(1).Start;
    Console.WriteLine(actualPosition.GetInteger()); // 0
    Console.WriteLine(actualPosition.GetObject());  // System.Text.Json.Tests.BufferSegment`1[System.Byte]
    Assert.True(((ReadOnlySequenceSegment<byte>)actualPosition.GetObject()).Memory.IsEmpty);
    Assert.Equal(expectedPosition, actualPosition); // True

    // System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.

    /*
        System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
        Parameter name: start
        Stack Trace:
        E:\GitHub\Fork\corefx\src\System.Memory\src\System\ThrowHelper.cs(31,0): at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
        E:\GitHub\Fork\corefx\src\System.Memory\src\System\Buffers\ReadOnlySequence.cs(281,0): at System.Buffers.ReadOnlySequence`1.Slice(Int64 start, SequencePosition end)
        E:\GitHub\Fork\corefx\src\System.Memory\src\System\Buffers\ReadOnlySequence.cs(388,0): at System.Buffers.ReadOnlySequence`1.Slice(Int32 start, SequencePosition end)
        E:\GitHub\Fork\corefx\src\System.Text.Json\tests\Utf8JsonReaderTests.TryGet.cs(357,0): at System.Text.Json.Tests.Utf8JsonReaderTests.ReadOnlySequenceTest()
    */
    sequence = sequence.Slice(1, sequence.Start);
}
```

We need to use the Slice overload that takes a `SequencePosition` for performance to avoid having to scan the segments from the beginning every time. Using `GetPosition` with `long` is too slow:
https://github.com/dotnet/corefxlab/blob/63ef1a5db4fdbfcf9822b8cd2cbc3921b3d3cb9e/src/System.Text.JsonLab/System/Text/Json/JsonUtf8Reader.cs#L112

cc @pakrym, @davidfowl

**Comment by devsko** [comment]
@ahsonkhan is this still a problem? Utf8JsonReader seems to work…

**Comment by ahsonkhan** [comment]
There's still an issue with the ROSequence `.Slice` API. `GetPosition` works as expected which is why `Utf8JsonReader` can use it.

**Comment by devsko** [comment]
I'm asking because I think I just fixed #35254 (PR coming soon) and thought it might be related.

**Comment by devsko** [comment]
But I don't understand this issue. I would say the sample throws the exception as expected.

**Comment by ahsonkhan** [comment]
> But I don't understand this issue. I would say the sample throws the exception as expected.

```C#
// A two segment sequence where the second one is empty: [a]-> []
SequencePosition pos = sequence.GetPosition(1, sequence.Start); // success
sequence = sequence.Slice(1, sequence.Start); // throws
```

Why would you consider the exception when calling slice, expected?

**Comment by devsko** [comment]
As I understand the API this means a slice from position 1 back to position 0. The second parameter is the end of the resulting slice. The second param of .GetPosition() has a different meaning. What slice would you expect it to return?

**Comment by ahsonkhan** [comment]
> As I understand the API this means a slice from position 1 back to position 0. The second parameter is the end of the resulting slice.

Actually, you are totally right. I confused the parameters of `GetPosition` and `Slice` (end vs origin). Passing in `sequence.Start` as the **end** position should continue to throw.
```C#
public ReadOnlySequence<T> Slice(int start, SequencePosition end) { throw null; }
public ReadOnlySequence<T> Slice(long start, SequencePosition end) { throw null; }
public SequencePosition GetPosition(long offset, SequencePosition origin)
```

For now, it looks like this issue is non-actionable. Let me page back the scenario where I was seeing an issue and double check the expected behavior.  I'll either update the issue or close it based on my findings. Thanks for bringing up the clarification and correcting me :)

**Comment by devsko** [comment]
Sounds good. Other PR is ready.

**Comment by MarcoRossignoli** [comment]
@ahsonkhan should we close this?

**Comment by ahsonkhan** [comment]
I haven't gotten a chance to look again. Moving to future for now.
