### ISSUE TITLE
System.Security.Cryptography.Rsa.Tests.KeyGeneration/GenerateMinKey test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#33350]
https://mc.dot.net/#/user/wfurt/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/30f34b678d12913529ab6569d9fd66d7a62343dc/workItem/System.Security.Cryptography.Algorithms.Tests/analysis/xunit/System.Security.Cryptography.Rsa.Tests.KeyGeneration~2FGenerateMinKey
```
Unhandled Exception of Type Interop+Crypto+OpenSslCryptographicException
Message :
Interop+Crypto+OpenSslCryptographicException : error:04081078:rsa routines:rsa_builtin_keygen:key size too small
Stack Trace :
   at System.Security.Cryptography.RSAImplementation.RSAOpenSsl.CheckBoolReturn(Int32 returnValue) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/Common/src/System/Security/Cryptography/RSAOpenSsl.cs:line 502
   at System.Security.Cryptography.RSAImplementation.RSAOpenSsl.GenerateKey() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/Common/src/System/Security/Cryptography/RSAOpenSsl.cs:line 524
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode) in /root/coreclr/src/System.Private.CoreLib/shared/System/Lazy.cs:line 324
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor) in /root/coreclr/src/System.Private.CoreLib/shared/System/Lazy.cs:line 348
   at System.Lazy`1.CreateValue() in /root/coreclr/src/System.Private.CoreLib/shared/System/Lazy.cs:line 436
   at System.Security.Cryptography.RSAImplementation.RSAOpenSsl.ExportParameters(Boolean includePrivateParameters) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/Common/src/System/Security/Cryptography/RSAOpenSsl.cs:line 333
   at System.Security.Cryptography.Rsa.Tests.KeyGeneration.GenerateKey(Func`2 getSize) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/KeyGeneration.cs:line 62
   at System.Security.Cryptography.Rsa.Tests.KeyGeneration.GenerateMinKey() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/KeyGeneration.cs:line 15
```

Also:

- https://mc.dot.net/#/user/wfurt/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/30f34b678d12913529ab6569d9fd66d7a62343dc/workItem/System.Security.Cryptography.OpenSsl.Tests/analysis/xunit/System.Security.Cryptography.Rsa.Tests.KeyGeneration~2FGenerateSecondMinKey
- https://mc.dot.net/#/user/wfurt/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/30f34b678d12913529ab6569d9fd66d7a62343dc/workItem/System.Security.Cryptography.OpenSsl.Tests/analysis/xunit/System.Security.Cryptography.Rsa.Tests.KeyGeneration~2FGenerateMinKey
- https://mc.dot.net/#/user/wfurt/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/30f34b678d12913529ab6569d9fd66d7a62343dc/workItem/System.Security.Cryptography.Csp.Tests/analysis/xunit/System.Security.Cryptography.Rsa.Tests.KeyGeneration~2FGenerateSecondMinKey
- https://mc.dot.net/#/user/wfurt/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/30f34b678d12913529ab6569d9fd66d7a62343dc/workItem/System.Security.Cryptography.Csp.Tests/analysis/xunit/System.Security.Cryptography.Rsa.Tests.KeyGeneration~2FGenerateMinKey

cc: @bartonjs

**Comment by bartonjs** [comment]
Looks like OpenSSL 1.1.1 bumped some minima.

**Comment by bartonjs** [comment]
Confirmed: https://github.com/openssl/openssl/commit/cac19d19e7d6f252ff9aea60d85e0c0fd71a117f

Rather than detecting the minimum across the 1.1.1 boundary just restricting it to 512 seems fine (no one should really want to generate RSA384)
