### ISSUE TITLE
System.Net.Sockets aborting when executed on FreeBSD

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#33448]
I get this consistently when trying to execute socket tests on FreeBSD

```
[toweinfu@toweinfu-fbsd /mnt/resource/corefx/artifacts/bin/tests/System.Net.Sockets.Tests/netcoreapp-FreeBSD-Debug-x64]$ ../../../testhost/netcoreapp-FreeBSD-Debug-x64//dotnet xunit.console.dll System.Net.Sockets.Tests.dll -xml testResults.xml -notrait category=nonnetcoreapptests -notrait category=nonfreebsdtests -verbose -nocolor -method System.Net.Sockets.Tests.SelectTest.Select_ReadWrite_AllReady_ManySockets   -notrait category=OuterLoop -notrait category=failing
xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 4.6.27112.03)
  Discovering: System.Net.Sockets.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Sockets.Tests (found 1 of 1008 test case)
  Starting:    System.Net.Sockets.Tests (parallel test collections = on, max threads = 4)
    System.Net.Sockets.Tests.SelectTest.Select_ReadWrite_AllReady_ManySockets(reads: 90, writes: 0) [STARTING]
Assertion Failed
ReleaseHandle failed. handle:0x606
InnerSafeCloseSocket#45330878.ReleaseHandle

   at System.Net.NetEventSource.Fail(Object thisOrContextObject, FormattableString formattableString, String memberName) in /mnt/resource/corefx/src/Common/src/System/Net/Logging/NetEventSource.Common.cs:line 270
   at System.Net.Sockets.SafeSocketHandle.InnerSafeCloseSocket.ReleaseHandle() in /mnt/resource/corefx/src/System.Net.Sockets/src/System/Net/Sockets/SafeSocketHandle.cs:line 212
   at System.Runtime.InteropServices.SafeHandle.DangerousRelease()
   at System.Net.Sockets.SafeSocketHandle.InnerSafeCloseSocket.BlockingRelease() in /mnt/resource/corefx/src/System.Net.Sockets/src/System/Net/Sockets/SafeSocketHandle.cs:line 285
   at System.Net.Sockets.SafeSocketHandle.CloseAsIs() in /mnt/resource/corefx/src/System.Net.Sockets/src/System/Net/Sockets/SafeSocketHandle.cs:line 184
   at System.Net.Sockets.Socket.Dispose(Boolean disposing) in /mnt/resource/corefx/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 4514
   at System.Net.Sockets.Socket.Dispose() in /mnt/resource/corefx/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 4585
   at System.Net.Sockets.Tests.SelectTest.DisposeSockets(IEnumerable`1 sockets) in /mnt/resource/corefx/src/System.Net.Sockets/tests/FunctionalTests/SelectTest.cs:line 238
   at System.Net.Sockets.Tests.SelectTest.Select_ReadWrite_AllReady(Int32 reads, Int32 writes) in /mnt/resource/corefx/src/System.Net.Sockets/tests/FunctionalTests/SelectTest.cs:line 42
   at System.Net.Sockets.Tests.SelectTest.Select_ReadWrite_AllReady_ManySockets(Int32 reads, Int32 writes) in /mnt/resource/corefx/src/System.Net.Sockets/tests/FunctionalTests/SelectTest.cs:line 34
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /mnt/resource/azure-pipelines-agent/_work/1/s/src/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 466
   at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 150
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 257
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /mnt/resource/azure-pipelines-agent/_work/1/s/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 958
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine) in /mnt/resource/azure-pipelines-agent/_work/1/s/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 204
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<InvokeTestMethodAsync>b__1()
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /mnt/resource/azure-pipelines-agent/_work/1/s/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 958
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine) in /mnt/resource/azure-pipelines-agent/_work/1/s/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 204
```

I did little digging and the NetEventSource.Fail() will assert for debug builds.
This is time issue as when I run it with tracing `truss -f -o /dev/null dotnet XXX` I cannot reproduce it. I did some tests with instrumented build and system close() returns ECONNRESET. 
That means that other side closed when we still had data to sent.  

cc: @bartonjs

**Comment by stephentoub** [comment]
This looks like FreeBSD-specific behavior (that close on a socket can return ECONNRESET).  Looks like other frameworks have bumped up against this as well, e.g. https://bugs.python.org/issue30319.  Seems like we should follow suit and either remove this assert, or just special-case ECONNRESET to ignore it.
