### ISSUE TITLE
PlatformNotSupportedException thrown on code loaded via Assembly.LoadFrom (.net core 2.1)

### ISSUE THREAD

**Issue by czmotig** [dotnet/corefx#33457]
[Repository with example project](https://github.com/czmotig/CrashOn_S.DS.Protocols)

**My use case**: I'm building an authentication server which supports different authentication methods, these has to be implemented as external DLL libraries.

**Problem**:
Using ``Assembly.LoadFrom`` works fine, but creating ``LdapDirectoryIdentifier`` in my class ``LDAPAuthentication`` throws ``PlatformNotSupportedException`` although platform obviously hasn't changed. 

```
   at System.DirectoryServices.Protocols.DirectoryIdentifier..ctor()
   at System.DirectoryServices.Protocols.LdapDirectoryIdentifier..ctor(String server, Int32 portNumber)
   at AuthLibrary.LDAP.LDAPAuthentication.Authenticate(String userName, String password) in C:\Users\miros\Source\Repos\AssemblyLoadTest\AuthLibrary.LDAP\LDAPAuthentication.cs:line 10
   at AssemblyLoadTest.Program.Main(String[] args) in C:\Users\miros\Source\Repos\AssemblyLoadTest\AssemblyLoadTest\Program.cs:line 25
```

The code works normally if ``AuthLibrary.LDAP`` is normally referenced and ``LDAPAuthentication`` constructed using ``new LDAPAuthentication()`` and not reflection.

Looking at the exception stacktrace, I couldn't find where the exception is thrown so I deduced there must be some other framework magic involved. The stacktrace says the exception originated in the ctor of [DirectoryIdentifier](https://github.com/dotnet/corefx/blob/master/src/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/common/DirectoryIdentifier.cs) but that's just an abstract class and it's ctor is empty.

**Code**:

3 projects in the solution, all .net core 2.1

- **AssemblyLoadTest**: Console app that loads a class from AuthLibrary.LDAP via Assembly.LoadFrom and invokes a method.
- **AuthLibraryInterface**: just contains the interface by which the implementation in the DLL is found. References by both the console app and the LDAP library.
- **AuthLibrary.LDAP**: Authentication library for LDAP using latest nuget System.DirectoryServices.Protocols which is included in the build output using ``CopyLocalLockFileAssemblies`` in the csproj PropertyGroup.

**(AssemblyLoadTest) Program.cs**
```csharp
using AuthLibraryInterface;
using System;
using System.Linq;
using System.IO;
using System.Reflection;

namespace AssemblyLoadTest
{
    class Program
    {
        static void Main(string[] args)
        {
            //build solution before starting

            const string libPath = "../../../../AuthLibrary.LDAP/bin/Debug/netcoreapp2.1/AuthLibrary.LDAP.dll";
            var fi = new FileInfo(libPath);

            Assembly assembly = Assembly.LoadFrom(fi.FullName);
            Type type = assembly.GetTypes().Single(t => typeof(IAuthentication).IsAssignableFrom(t));


            IAuthentication auth = Activator.CreateInstance(type) as IAuthentication;

            //crashes on PlatformNotSupportedException
            auth.Authenticate("name", "password");


            Console.WriteLine("Success!");
            Console.ReadLine();
        }
    }
}

```

**(AuthLibrary.LDAP) LDAPAuthentication.cs**
```csharp
namespace AuthLibrary.LDAP
{
    using AuthLibraryInterface;
    using System.DirectoryServices.Protocols;

    public class LDAPAuthentication : IAuthentication
    {
        public bool Authenticate(string userName, string password)
        {
            var serverId = new LdapDirectoryIdentifier("localhost", 12001);
            /* ... */
            return true;
        }
    }
}
```
**(AuthLibraryInterface) IAuthentication.cs**
```csharp
namespace AuthLibraryInterface
{
    public interface IAuthentication
    {
        bool Authenticate(string userName, string password);
    }
}
```

**Comment by henning-krause** [comment]
Any news on this? Hitting the same bug when using DirectoryServices.Protocols in an Azure Function v2.

**Comment by scegg** [comment]
Hit this bug last year when I need to use Assembly.Load in dotnet standard 2.

Workaround (for Load and LoadFile, but not for LoadFrom directly):
Reference System.Runtime.Loader from nuget and use this code:

using (var ms = new MemoryStream(bytearray)) // or FileStream
                {
                    assembly = System.Runtime.Loader.AssemblyLoadContext.Default.LoadFromStream(ms);
                }

**Comment by danmosemsft** [comment]
@jeffschw in case this looks like a loader issue to him.
