### ISSUE TITLE
Font serialization tests failing on some CI machines

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#33513]
Looks like a missing dependency?
cc: @ViktorHofer 
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/55d371836258011530d0872a70d146f2f82d065a/workItem/System.Runtime.Serialization.Formatters.Tests
```
Unhandled Exception of Type System.TypeInitializationException
Message :
System.TypeInitializationException : The type initializer for 'Gdip' threw an exception.
---- System.DllNotFoundException : Unable to load DLL 'libgdiplus': The specified module could not be found.
Stack Trace :
   at System.Drawing.SafeNativeMethods.Gdip.GdipGetGenericFontFamilySansSerif(IntPtr& fontfamily) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Drawing.Common/src/System/Drawing/GdiplusNative.cs:line 967
   at System.Drawing.FontFamily.GetGdipGenericSansSerif() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Drawing.Common/src/System/Drawing/FontFamily.cs:line 210
   at System.Drawing.FontFamily.get_GenericSansSerif() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Drawing.Common/src/System/Drawing/FontFamily.cs:line 205
   at System.Drawing.Font.CreateFont(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte charSet, Boolean isVertical) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Drawing.Common/src/System/Drawing/Font.Unix.cs:line 65
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Drawing.Common/src/System/Drawing/Font.Unix.cs:line 304
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Drawing.Common/src/System/Drawing/Font.Unix.cs:line 292
   at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.SerializableObjects()+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.SerializableObjects_MemberData()
   at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.BasicObjectsRoundtrip_MemberData()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
----- Inner Stack Trace -----
   at System.Runtime.InteropServices.FunctionWrapper`1.get_Delegate() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/Common/src/System/Runtime/InteropServices/FunctionWrapper.cs:line 39
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Drawing.Common/src/System/Drawing/GdiplusNative.Unix.cs:line 287
   at System.Drawing.SafeNativeMethods.Gdip..cctor() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Drawing.Common/src/System/Drawing/Gdiplus.cs:line 85
```

**Comment by stephentoub** [comment]
Also https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/55d371836258011530d0872a70d146f2f82d065a/workItem/System.Resources.ResourceManager.Tests/analysis/xunit/System.Resources.Tests.ResourceManagerTests~2FGetObject_Images

**Comment by ahsonkhan** [comment]
Similar to https://github.com/dotnet/corefx/issues/33456

**Comment by ViktorHofer** [comment]
> Looks like a missing dependency?

Looks like it. I probably need to refine the if check to mimic what System.Drawing.Common.Tests does.

@safern are you aware of this? I expect more System.Drawing.Common tests to fail on SLES if a dependency is missing.

**Comment by safern** [comment]
Looks like you’re using PlatformDetection.IsDrawingSupported and that just checks to see if it is not Windows nano or IOT Core. 

https://github.com/dotnet/corefx/blob/e9d7a5f20120d77941b72763336f4455bd175ec7/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.cs#L35

You need to use IsGdiPlusAvailable like the other drawing tests I added for serialization. 

https://github.com/dotnet/corefx/pull/30817/files#diff-98aad8dfb9b9f1ce25acec673abb7490R1367

Or we can just add the IsGdiPlusAvailable into PlatformDetection.IsDrawingSupported

**Comment by danmosemsft** [comment]
> Or we can just add the IsGdiPlusAvailable into PlatformDetection.IsDrawingSupported

Seems a good idea to me
