### ISSUE TITLE
SslStream_StreamToStream_Alpn_NonMatchingProtocols_Fail failing on Ubuntu 18.10

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#33514]
We're expecting something to fail with an exception but it's not failing.
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/55d371836258011530d0872a70d146f2f82d065a/workItem/System.Net.Security.Tests/analysis/xunit/System.Net.Security.Tests.SslStreamAlpnTests~2FSslStream_StreamToStream_Alpn_NonMatchingProtocols_Fail
cc: @krwq, @davidsh, @bartonjs 
```
Unhandled Exception of Type Xunit.Sdk.ThrowsException
Message :
Assert.Throws() Failure
Expected: typeof(System.IO.IOException)
Actual:   (No exception was thrown)
Stack Trace :
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 77
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 105
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 65
   at System.Net.Security.Tests.SslStreamAlpnTests.SslStream_StreamToStream_Alpn_NonMatchingProtocols_Fail() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Security/tests/FunctionalTests/SslStreamAlpnTests.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by bartonjs** [comment]
I... thought that I'd been tagging when I saw these failures to https://github.com/dotnet/corefx/issues/32946, but it doesn't seem to have any other links to it.  So this seems fine.  (Fixed 18.04 -> 18.10 in the title)

**Comment by stephentoub** [comment]
Thanks.

**Comment by wfurt** [comment]
I did quick look and 18.10 has OpenSSL 1.1.1 (18.04 has 1.1.0)
AlpnServerSelectCallback() gets called and returns Ssl.SSL_TLSEXT_ERR_NOACK as expected. 
That however does not lead to expected exception.

**Comment by danmosemsft** [comment]
@wfurt if you don't expect to hvae time to investigate further soon, it would be ideal to disable the test meantime.

**Comment by krwq** [comment]
Seems like we returned wrong error code. The doc technically says that anything but 0 should mean error but it reacts only to SSL_TLSEXT_ERR_ALERT_FATAL. I've sent a patch
