### ISSUE TITLE
System.FormatException thrown when writing base64 string to a CryptoStream with FromBase64Transform applied

### ISSUE THREAD

**Issue by DanielVukelich** [dotnet/corefx#33558]
The following method is successful when I run it targeting .NET Framework 4.6.1, but when it targets .NET Standard 2.0, it throws an exception when flushing the stream writer.

> System.FormatException : The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

```c#
        public void Example()
        {
            byte[] original = new byte[] {0, 1, 2, 3, 4, 5};
            string base64String = Convert.ToBase64String(original);

            byte[] result;

            using (MemoryStream ms = new MemoryStream())
            using (CryptoStream cs = new CryptoStream(ms, new FromBase64Transform(), CryptoStreamMode.Write))
            using (StreamWriter sw = new StreamWriter(cs))
            {
                sw.Write(base64String);
                sw.Flush();
                cs.Flush();

                result = ms.ToArray();
            }
        }
```

**Comment by stephentoub** [comment]
This program:
```C#
using System;
using System.IO;
using System.Security.Cryptography;

class Program
{
    static void Main()
    {
        using (var ms = new MemoryStream())
        using (var cs = new CryptoStream(ms, new FromBase64Transform(), CryptoStreamMode.Write))
        using (var sw = new StreamWriter(cs))
        {
            sw.Write(Convert.ToBase64String(new byte[] { 0, 1, 2, 3, 4, 5 }));
            sw.Flush();
            cs.Flush();
            Console.WriteLine(ms.ToArray().Length);
        }
    }
}
```
fails for me on .NET Core 2.0 and 2.1:
```
Unhandled Exception: System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64CharArray(Char[] inArray, Int32 offset, Int32 length)
   at System.Security.Cryptography.FromBase64Transform.ConvertFromBase64(Byte[] temp, Int32 effectiveCount)
   at System.Security.Cryptography.FromBase64Transform.TransformBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[] outputBuffer, Int32 outputOffset)
   at System.Security.Cryptography.CryptoStream.WriteAsyncCore(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken, Boolean useAsync)
   at System.Security.Cryptography.CryptoStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at Program.Main() in C:\Users\stoub\Source\Repos\ConsoleApp95\ConsoleApp95\Program.cs:line 14
```
but succeeds on .NET Core 3.0:
```
6
Press any key to continue . . .
```
I'm not sure what commit/PR fixed it, but @bartonjs may know.

**Comment by bartonjs** [comment]
I think that this was fixed by https://github.com/dotnet/corefx/pull/29777; the StreamWriter buffered the write, then asked CryptoStream to write from 0 to not the end, and CryptoStream asked FromBase64Transform to write from 0 to not the end, and then it got confused.

Since it's already fixed for vNext, I'm hitting close... but if there's something else we can always reopen it.
