### ISSUE TITLE
"The system cannot find the file specified" in System.Security.Cryptography.X509Certificates

### ISSUE THREAD

**Issue by shimingsg** [dotnet/corefx#33829]
failed in job: 
https://ci2.dot.net/job/dotnet_corefx/job/perf/job/master/job/perf_windows_nt_release/7455

failed log: 
```
[12/4/2018 5:03:41 PM][INF]   System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(ssl: False, chunkedResponse: True, responseLength: 1)
  [12/4/2018 5:03:41 PM][ERR] System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(ssl: False, chunkedResponse: True, responseLength: 1): The system cannot find the file specified.
  [12/4/2018 5:03:41 PM][ERR]    at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags) in C:\J\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 152
     at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in C:\J\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 88
     at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in C:\J\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 21
     at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags) in C:\J\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs:line 81
     at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags) in C:\J\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2.cs:line 64
     at System.Net.Test.Common.Configuration.Certificates.GetCertificate(String certificateFileName) in C:\J\w\perf_windows_---356c2fc4\src\Common\tests\System\Net\Configuration.Certificates.cs:line 75
     at System.Net.Test.Common.Configuration.Certificates.GetServerCertificate() in C:\J\w\perf_windows_---356c2fc4\src\Common\tests\System\Net\Configuration.Certificates.cs:line 38
     at System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(Boolean ssl, Boolean chunkedResponse, Int32 responseLength) in C:\J\w\perf_windows_---356c2fc4\src\System.Net.Http\tests\Performance\Perf.SocketsHttpHandler.cs:line 33
     at Microsoft.Xunit.Performance.BenchmarkTestInvoker.<>c__DisplayClass1_0.<<CallTestMethod>b__0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at Microsoft.Xunit.Performance.Internal.BenchmarkIterator.RunAsync(Func`1 testMethod)
     at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
  --- End of stack trace from previous location where exception was thrown ---
     at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
     at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\projects\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
```

**Comment by davidsh** [comment]
@stephentoub 

This issue about the System.Net.Http/PerformanceTests.  How does one run these? "msbuild /t:rebuildandtest" doesn't work.

Also, isn't these tests obsolete now that performance tests have moved to dotnet/performance?

https://github.com/dotnet/performance/tree/master/src/benchmarks/micro/corefx/System.Net.Http

**Comment by stephentoub** [comment]
> Also, aren't these tests obsolete now that performance tests have moved to dotnet/performance?

They should be. @adamsitnik, can we delete perf tests from corefx now?

**Comment by adamsitnik** [comment]
> can we delete perf tests from corefx now?

@stephentoub I have a PR for that, it should be ready for review by EOD https://github.com/dotnet/corefx/pull/35781
