### ISSUE TITLE
ObjectDisposedException in FileStreamCompletionSource.CompleteCallback crashes the process

### ISSUE THREAD

**Issue by Tratcher** [dotnet/corefx#33844]
See https://github.com/aspnet/AspNetCore/issues/4422
```
Application: dotnet.exe
CoreCLR Version: 4.6.27110.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.IO.FileStream.FileStreamCompletionSource.CompleteCallback(UInt64 packedResult)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

In this situation the application is reading files, cancels the reads, and apparently disposing the CancellationTokenSource.

**Comment by Tratcher** [comment]
@stephentoub this looks like a regression introduced here:
https://github.com/dotnet/coreclr/commit/5fd50d8d7ab96dbb3868ab3e60d0e4fc10f44ca0#diff-742d93872313d38656fb88ad801f4d7bR174
_cancellationRegistration.Token can throw if the CTS was disposed.

**Comment by stephentoub** [comment]
> _cancellationRegistration.Token can throw if the CTS was disposed.

Ugh.  That's a bug in CTR.Token; it should never throw.

**Comment by stephentoub** [comment]
Re-opening to track potential ports.

**Comment by karelz** [comment]
Part of 2.2.1 release (via PR #21417)
