### ISSUE TITLE
HttpClient Unhandled Exception, Centos 7, .NET CORE 2.2

### ISSUE THREAD

**Issue by logwlogw** [dotnet/corefx#33857]
# HttpClient Unhandled Exception

An error even in try catch with 

1. ONLY with one site indianetzone.com
2. win10 - works 
3. AppContext.SetSwitch ("System.Net.Http.UseSocketsHttpHandler", false); - works

What could be a problem, thank you.

# Simple Code
------------
```c#
using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace ConsoleApp18
{
    class Program
    {
        static async Task Main(string[] args)
        {

            using (var http = new HttpClient())
            {
                try
                {
                    var data =await http.GetStringAsync("http://indianetzone.com");
                    Console.WriteLine(data.Length);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
            }

            Console.ReadLine();
        }
    }
}
```
-------------

```
[root@server publish]# dotnet ConsoleApp18.dll

Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException
                          : Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
   at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
   at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
   at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted
```

**For WebAPI, Example**

```c#
using System;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MyApi.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class CrachController : ControllerBase
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public CrachController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        [HttpGet]
        public async Task<ActionResult> Get()
        {
            var client = _httpClientFactory.CreateClient();

            try
            {
                string result = await client.GetStringAsync("http://indianetzone.com");
                return Ok(result);
            }
            catch (Exception e)
            {
                return Ok(e.Message);
            }

            
        }

    }
}
```

**Comment by wfurt** [comment]
I can reproduce it. Server sends redirect to https://indianetzone.com and than if fails during SSL handshake. The exception is correct as server sends TCP RST.

**Comment by logwlogw** [comment]
The exception is correct, But Unhandled Exception is impossible catch, web api crashed.

**Comment by logwlogw** [comment]
HttpClient not fully asynchronous?

May be for SSL or other things, use Threads, Task.Run, Task.Factory.Start ....  with internal unhadled exception? that i can't catch,

**Comment by wfurt** [comment]
Aside from the issue with catching exception the site it self seem problematic. On Centos7 I could connect when falling back to curl handler. However on Ubuntu 18 I cannot connect even using command line curl. And use of System.Net.Http.UseSocketsHttpHandler=false does not make any difference. At this point it seems like some openssl compatibility (Centos7 uses nss)

cc: @bartonjs in case he has some ideas.

**Comment by bartonjs** [comment]
That particular host only supports SSL2, SSL3, and TLS1.0.  Is HttpClient picking only newer protocols when redirecting HTTP to HTTPS?

**Comment by wfurt** [comment]
This can be reproduced without redirection @bartonjs 
The site seems finicky even with command line curl. 

At this point I'm not sure if this is actionable beyond already submitted fix. Any thoughts @logwlogw ?

**Comment by wfurt** [comment]
I modified the example code to use Tls1.0:
```c# 
using System;
using System.Net.Http;
using System.Security.Authentication;
using System.Threading.Tasks;

namespace ConsoleApp18
{
    class Program
    {
        static async Task Main2(string[] args)
        {
            HttpClientHandler handler = new HttpClientHandler();
            handler.SslProtocols  = SslProtocols.Tls;


            using (var http = new HttpClient(handler))
            {
                try
                {
                    var data = await http.GetStringAsync("https://indianetzone.com/");
                    Console.WriteLine(data.Length);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
            }
            Console.ReadLine();
        }

        static void Main(string[] args)
        {
            Main2(args).GetAwaiter().GetResult();
        }
    }
}
```

With that I can connect and get content.
