### ISSUE TITLE
SqlClient Integrated Security behaviour difference Core/Framework

### ISSUE THREAD

**Issue by chrarnoldus** [dotnet/corefx#33859]
We have a console app (running as UserA) on machine A (running Windows 10 Enterprise) trying to connect to a SQL Server 2017 instance on machine B (running Windows Server 2012 R2). The connection string is as follows:

```
Data Source=<ip address of B>;Integrated Security=True
```

We added the credentials of a local user on machine B (UserB) to the credential manager on machine A using the `cmdkey` command.

On .NET Framework 4.7.2 this setup works and the security log on machine B indicates that the app on machine A successfully logged on impersonating UserB.

On .NET Core 2.2, this fails with the following exception:

```
System.Data.SqlClient.SqlException (0x80131904): Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
```

The security log on machine B reveals that the app tried to login as UserA, which obviously fails because the user is unknown.

Apparently, the impersonation that happens when using Framework is not happening when using Core. Is this difference intentional and if so, is it documented somewhere?

**Comment by danmosemsft** [comment]
@chrarnoldus I am not a SqlClient person but I know that SqlClient bits were not automatically updated in 2.2 because of a packaging glitch. To get the newest SqlClient bits in your 2.2 project, you must add a direct package reference eg 
``<PackageReference Include="System.Data.SqlClient"/>`
I used 
`<PackageReference Include="System.Data.SqlClient" Version="4.6.0-preview3-27014-02" />`
I would try that first.
Some else will have to answer your question though.

**Comment by keeratsingh** [comment]
@chrarnoldus Unfortunately .Net Core does not support impersonation currently hence the difference in behavior, I'll go ahead and close this issue.
Related Issue: #2191: **Add Sql Impersonation Support**
