### ISSUE TITLE
[arm32/Linux] System.Console.Tests failures on arm32 linux

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#33888]
Running the arm32 tests on linux for System.Console.Tests produced the following results: passed 138/139 tests.

Test WindowAndCursorProps.NonRedirectedCursorVisible failed with the following message:
```
Assert.True() Failure\nExpected: True\nActual:   False
   at WindowAndCursorProps.<>c.<NonRedirectedCursorVisible>b__18_0(MemoryStream data) in /opt/corefx/src/System.Console/tests/WindowAndCursorProps.cs:line 181
   at Helpers.RunInNonRedirectedOutput(Action`1 command) in /opt/corefx/src/System.Console/tests/Helpers.cs:line 81
   at WindowAndCursorProps.NonRedirectedCursorVisible() in /opt/corefx/src/System.Console/tests/WindowAndCursorProps.cs:line 181
```

**Comment by joperezr** [comment]
Didn't repro the second time we ran these tests, so closing this for now.
