### ISSUE TITLE
[arm32/Linux] System.Runtime.Serialization.Formatters.Tests failures on arm32 linux

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#33896]
Running the arm32 tests on linux for System.Runtime.Serialization.Formatters.Tests produced the following results: passed 7071/7085 tests.

14 tests fail throwing an ArgumentException. Here is an example:
```
System.ArgumentException : Field 'value' in TypedReferences cannot be static or init only.
   at System.TypedReference.MakeTypedReference(Object target, FieldInfo[] flds)
   at System.Runtime.Serialization.ObjectManager.DoValueTypeFixup(FieldInfo memberToFix, ObjectHolder holder, Object value)
   at System.Runtime.Serialization.ObjectManager.CompleteObject(ObjectHolder holder, Boolean bObjectFullyComplete)
   at System.Runtime.Serialization.ObjectManager.DoNewlyRegisteredObjectFixups(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.RegisterObject(Object obj, Int64 objectID, SerializationInfo info, Int64 idOfContainingObj, MemberInfo member, Int32[] arrayIndex)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.RegisterObject(Object obj, ParseRecord pr, ParseRecord objectPr, Boolean bIsString)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObjectEnd(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterHelpers.Clone[T](T obj, ISerializationSurrogate surrogate, FormatterAssemblyStyle assemblyFormat, TypeFilterLevel filterLevel, FormatterTypeStyle typeFormat) in /opt/corefx/src/Common/tests/System/Runtime/Serialization/Formatters/BinaryFormatterHelpers.cs:line 44
   at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateBasicObjectsRoundtrip(Object obj, FormatterAssemblyStyle assemblyFormat, TypeFilterLevel filterLevel, FormatterTypeStyle typeFormat) in /opt/corefx/src/System.Runtime.Serialization.Formatters/tests/BinaryFormatterTests.cs:line 54
```

[testResults.zip](https://github.com/dotnet/corefx/files/2655235/testResults.zip)

**Comment by danmosemsft** [comment]
Tests from fix for https://github.com/dotnet/corefx/issues/33655 are present but not the fix.
