### ISSUE TITLE
[arm32/Linux] System.IO.FileSystem.Watcher.Tests failures on arm32 linux

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#33893]
Running the arm32 tests on linux for System.IO.FileSystem.Watcher.Tests produced the following results: passed 258/259 tests.

Test System.IO.Tests.FileSystemWatcherFilterListTests.FileSystemWatcher_ModifyFiltersConcurrentWithEvents threw an InvalidOperationException:
```
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.IO.Tests.FileSystemWatcherTest.RecreateWatcher(FileSystemWatcher watcher) in /opt/corefx/src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.netcoreapp.cs:line 22
   at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String[] expectedPaths, Int32 attempts, Int32 timeout) in /opt/corefx/src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 172
   at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String expectedPath, Int32 attempts, Int32 timeout) in /opt/corefx/src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 149
   at System.IO.Tests.FileSystemWatcherFilterListTests.FileSystemWatcher_ModifyFiltersConcurrentWithEvents() in /opt/corefx/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.unit.netcoreapp.cs:line 494
```

**Comment by danmosemsft** [comment]
Mismatched product.
