### ISSUE TITLE
[arm32/Linux] Microsoft.VisualBasic.Tests failures on arm32 linux

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#33898]
Running the arm32 tests on linux for Microsoft.VisualBasic.Tests produced the following results: passed 19046/19079 tests.

Most test failures are caused to an InvalidCastException:
```
System.InvalidCastException : Conversion from type 'DBNull' to type 'String' is not valid.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at Microsoft.VisualBasic.CompilerServices.Operators.ConcatenateObject(Object Left, Object Right)
   at Microsoft.VisualBasic.CompilerServices.Tests.OperatorsTests.ConcatenateObject_Invoke_ReturnsExpected(Object left, Object right, Object expected) in /opt/corefx/src/Microsoft.VisualBasic/tests/OperatorsTests.cs:line 1182
```

[testResults.zip](https://github.com/dotnet/corefx/files/2655256/testResults.zip)

**Comment by danmosemsft** [comment]
Probably because tests from 1c34aea1482cff4bdf59c9fffa4b3ec706f18536 were present but product from that change was not. Mismatch.
