### ISSUE TITLE
[arm32/Linux] System.Diagnostics.TraceSource.Tests failures on arm32 linux

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#33894]
Running the arm32 tests on linux for System.Diagnostics.TraceSource.Tests produced the following results: passed 272/273 tests.

Test System.Diagnostics.TraceSourceTests.DefaultTraceListenerClassTests.EntryAssemblyName_Null_NotIncludedInTrace threw an exception:
```
System.Diagnostics.RemoteExecutorTestBase+RemoteInvokeHandle+RemoteExecutionException : Remote process failed with an unhandled exception.

Child exception:
  System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Diagnostics.TraceSourceTests.DefaultTraceListenerClassTests.MakeAssemblyGetEntryAssemblyReturnNull() in /opt/corefx/src/System.Diagnostics.TraceSource/tests/DefaultTraceListenerClassTests.netcoreapp.cs:line 46
   at System.Diagnostics.TraceSourceTests.DefaultTraceListenerClassTests.<>c.<EntryAssemblyName_Null_NotIncludedInTrace>b__12_0() in /opt/corefx/src/System.Diagnostics.TraceSource/tests/DefaultTraceListenerClassTests.netcoreapp.cs:line 32

Child process:
  System.Diagnostics.TraceSource.Tests, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Diagnostics.TraceSourceTests.DefaultTraceListenerClassTests+<>c Void <EntryAssemblyName_Null_NotIncludedInTrace>b__12_0()
```

**Comment by danmosemsft** [comment]
Mismatched product - field was renamed at that time
