### ISSUE TITLE
System.IO.Pipelines.Tests.SchedulerFacts/ThreadPoolScheduler_SchedulesOnThreadPool test failure

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#33937]
`System.IO.Pipelines.Tests.SchedulerFacts/ThreadPoolScheduler_SchedulesOnThreadPool` test failed in https://github.com/dotnet/corefx/pull/33695#issuecomment-445530882 with:

```
Unhandled Exception of Type Xunit.Sdk.NotEqualException
Message :
Assert.NotEqual() Failure
Expected: Not 10
Actual:   10
Stack Trace :
   at System.IO.Pipelines.Tests.SchedulerFacts.<>c__DisplayClass11_0.<<ThreadPoolScheduler_SchedulesOnThreadPool>g__DoRead|0>d.MoveNext() in D:\j\workspace\windows-TGrou---2a8f9c29\src\System.IO.Pipelines\tests\SchedulerFacts.cs:line 518
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.Pipelines.Tests.SchedulerFacts.<ThreadPoolScheduler_SchedulesOnThreadPool>d__11.MoveNext() in D:\j\workspace\windows-TGrou---2a8f9c29\src\System.IO.Pipelines\tests\SchedulerFacts.cs:line 542
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by davidfowl** [comment]
cc @pakrym
