### ISSUE TITLE
[arm32/Linux] System.Text.RegularExpressions.Tests failures on arm32 linux

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#33964]
Running the arm32 tests on linux for System.Text.RegularExpressions.Tests produced the following results: passed 1498/1499 tests.

The test that failed was System.Text.RegularExpressions.Tests.RegexMatchTests.Match_ExcessPrefix and this is the output:
```
Timed out after 60000ms waiting for remote process 11744\nExpected: True\nActual:   False
   at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose(Boolean disposing) in /root/corefx-2261125/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 359
   at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in /root/corefx-2261125/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 346
   at System.Text.RegularExpressions.Tests.RegexMatchTests.Match_ExcessPrefix() in /root/corefx-2261125/src/System.Text.RegularExpressions/tests/Regex.Match.Tests.cs:line 795
```

**Comment by danmosemsft** [comment]
Test is too slow on this machine

**Comment by joperezr** [comment]
They are, so I guess we should either skip this test on arm or we should extend the timeout in order to have it pass on arm32. One other option would be to move it to Outerloop.

**Comment by danmosemsft** [comment]
This is a marginal test, not architecture specific, so I would skip it on ARM.
