### ISSUE TITLE
Unknown Exception when using HTTP/2 in .NET core 2.2 to connect to api.push.apple.com

### ISSUE THREAD

**Issue by niklasweimann** [dotnet/corefx#33976]
Using .NET Core 2.2 on Windows 10 1803 (build 17134) and .Net Core 2.2 on Debian 9 docker-image: microsoft/dotnet:2.2-runtime

When I try to connect via HTTP/2 to https://api.push.apple.com an exception occurs. The exception is not descriptive enough to troubleshoot. I will post my code without the certificate implementation, because I get the same exception with or without the certificate at the request. This Issue may be related to #14715 but since #14715 should be fixed with version 2.0 and I am using 2.2 I would like to bring this issue up again.

**The Code i am using:**
```c#
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
var url = "https://api.push.apple.com";
var request = new HttpRequestMessage(HttpMethod.Get, url);
request.Version = new Version(2, 0);
var client = new HttpClient();

var result2 = client.SendAsync(request);
var result = result2.Result;
Console.WriteLine("Response: " + result.StatusCode);
```

**Exception Stacktrace**
```
System.AggregateException: One or more errors occurred. (One or more errors occurred. (An error occurred while sending the request.)) ---> System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at iOsTestCore22.iOs.SendNotification(Message_IDs messageIDs) in C:\Users\niklas.weimann\source\repos\iOsTestCore22\iOsTestCore22\iOs.cs:line 37
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at iOsTestCore22.iOs.SendPush(List`1 messages) in C:\Users\niklas.weimann\source\repos\iOsTestCore22\iOsTestCore22\iOs.cs:line 22
   at iOsTestCore22.Program.Main(String[] args) in C:\Users\niklas.weimann\source\repos\iOsTestCore22\iOsTestCore22\Program.cs:line 13
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at iOsTestCore22.iOs.SendNotification(Message_IDs messageIDs) in C:\Users\niklas.weimann\source\repos\iOsTestCore22\iOsTestCore22\iOs.cs:line 37
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)<---
<---

System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at iOsTestCore22.iOs.SendNotification(Message_IDs messageIDs) in C:\Users\niklas.weimann\source\repos\iOsTestCore22\iOsTestCore22\iOs.cs:line 37
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)<---
```

**Curl Request which is working totally fine**
```
curl --http2  https://api.push.apple.com/ --cert cert2.pem
```

**Output of curl request**
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    29    0    29    0     0     30      0 --:--:-- --:--:-- --:--:--    30{"reason":"MethodNotAllowed"}
```

**Comment by davidsh** [comment]
Note:  ServicePointManager is a no-op on .NET Core.  So this code doesn't do anything:

```c#
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
```

**Comment by niklasweimann** [comment]
Can you name an alternative for SocketsHttpHandler that is implemented and serves a similar purpose?

**Comment by davidsh** [comment]
>Can you name an alternative for SocketsHttpHandler that is implemented and serves a similar purpose?

There is no CoreFx HttpClient handler that solves this issue yet.  Eventually the default HTTP stack in CoreFx (SocketsHttpHandler) will have HTTP/2 support and handle this scenario.

cc: @karelz

**Comment by wfurt** [comment]
I did some testing with 2.2 and Ubuntu 18.04. 
Since curl works that suggests that it was built with HTTP2. so you do do this:
```
export  DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0
furt@Ubuntu:~/http$ /home/furt/http/bin/Debug/netcoreapp2.2/linux-x64/publish/http
Response: OK
```

however,
```
export CURLHANDLER_DEBUG_VERBOSE=true
furt@Ubuntu:~/http$ /home/furt/http/bin/Debug/netcoreapp2.2/linux-x64/publish/http
Hello World!
*   Trying 17.188.158.31...
* TCP_NODELAY set
* Connected to api.push.apple.com (17.188.158.31) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
* 	 subject: CN=api.push.apple.com; OU=management:idms.group.533599; O=Apple Inc.; ST=California; C=US
* 	 start date: Jan  6 00:14:15 2018 GMT
* 	 expire date: Feb  5 00:14:15 2020 GMT
* 	 subjectAltName: api.push.apple.com matched
* 	 issuer: CN=Apple IST CA 2 - G1; OU=Certification Authority; O=Apple Inc.; C=US
* 	 SSL certificate verify ok.
> GET / HTTP/1.1
Host: api.push.apple.com
Accept: */*

* Connection #0 to host api.push.apple.com left intact
Response: OK
```
On my system falls back to HTTP/1.1 but it is able to talk to the server. 

I also did more testing with current 3.0 builds from master branch. SocketHttphandler is able to connect and talk to the server but it gets back error about unsupported method. It seems like it expects POST instead of GET. If you post more complete example, I can do more testing.

**Comment by davidsh** [comment]
With current .NET Core 3.0 master branch, I see similar results as @wfurt 

```c#
string url = "https://api.push.apple.com";
var request = new HttpRequestMessage(HttpMethod.Get, url);
request.Version = new Version(2, 0);
var client = new HttpClient();

HttpResponseMessage response = client.SendAsync(request).GetAwaiter().GetResult();
Console.WriteLine(response);
```

Results:
```
StatusCode: 405, ReasonPhrase: 'Method Not Allowed', Version: 2.0, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  apns-id: 24146FCD-3838-1162-4E34-7C24ECFC4F69
}
```

This means that we are successfully connecting with HTTP/2.0. 

I didn't test the full scenario since there is no client certificate available for us to try out.

I am going to close this issue since the "Unknown Exception" reported against .NET Core 2.2 doesn't occur w/ .NET Core 3.0 current code.

We enabled HTTP/2.0 now as of .NET Core 3.0 Preview 6 (not yet released).  You can try out our daily builds if you want to explore your scenario more. Let us know if you see other problems after you start using your client certificate.  If so, please open up a new issue. Thanks.
