### ISSUE TITLE
[arm32/Windows] System.Security.Principal.Windows.Tests failures on arm32 windows

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#33982]
Running the arm32 tests on windows for System.Security.Principal.Windows.Tests produced the following results: passed 22/23 tests.

The failing test was SecurityIdentifierTests.ValidateToStringUsingWhoami and failed with the following Win32Exception:
```
System.ComponentModel.Win32Exception : The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) in F:\git\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Windows.cs:line 598
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in F:\git\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Win32.cs:line 24
   at System.Diagnostics.Process.Start() in F:\git\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs:line 1216
   at SecurityIdentifierTests.ValidateToStringUsingWhoami() in F:\git\corefx\src\System.Security.Principal.Windows\tests\SecurityIdentifierTests.cs:line 61
```

**Comment by danmosemsft** [comment]
Tool is not in Windows IoT SKU. Need to disable it just like we already do for Nano:

```c#
    [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsNanoServer), nameof(PlatformDetection.IsNotWindowsServerCore))]
    public void ValidateToStringUsingWhoami()
```

**Comment by danmosemsft** [comment]
@pgovind this is a quick one
