### ISSUE TITLE
[arm32/Windows] System.Console.Tests failures on arm32 windows

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#33984]
Running the arm32 tests on windows for System.Console.Tests produced the following results: passed 126/127 tests.

The test that failed was ReadAndWrite.OutputEncodingPreamble and it failed with the following IOException:
```
System.IO.IOException : The parameter is incorrect.
   at System.ConsolePal.SetConsoleOutputEncoding(Encoding enc) in F:\git\corefx\src\System.Console\src\System\ConsolePal.Windows.cs:line 120
   at System.Console.set_OutputEncoding(Encoding value) in F:\git\corefx\src\System.Console\src\System\Console.cs:line 68
   at ReadAndWrite.OutputEncodingPreamble() in F:\git\corefx\src\System.Console\tests\ReadAndWrite.cs:line 281
```

**Comment by danmosemsft** [comment]
That's an odd one because line 281 is just setting on `Console.OutputEncoding` the exact value it got from `Console.OutputEncoding`. Some OS wierdness? Might be interesting to log what encoding it is. Probably another special casing for this SKU.
