### ISSUE TITLE
[arm32/Windows] System.Data.SqlClient.Tests failures on arm32 windows 

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#33999]
Running the arm32 tests on windows for System.Data.SqlClient.Tests produced the following results: passed 142/180 tests.

Most of the 38 failed tests fail with the following exception:
```
Assert.Throws() Failure\r\nExpected: typeof(System.Data.SqlClient.SqlException)\r\nActual:   typeof(System.TypeInitializationException): The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.\r\n---- System.TypeInitializationException : The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.\r\n-------- System.TypeInitializationException : The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception.\r\n------------ System.DllNotFoundException : Unable to load DLL 'sni.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Data.SqlClient.TdsParser..ctor(Boolean MARS, Boolean fAsynchronous) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\TdsParser.cs:line 56
   at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlInternalConnectionTds.cs:line 1331
   at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlInternalConnectionTds.cs:line 1225
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs:line 1622
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs:line 1130
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlInternalConnectionTds.cs:line 384
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlConnectionFactory.cs:line 135
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions) in F:\git\corefx\src\Common\src\System\Data\ProviderBase\DbConnectionFactory.cs:line 96
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionFactory.cs:line 140
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in F:\git\corefx\src\Common\src\System\Data\ProviderBase\DbConnectionInternal.cs:line 325
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs:line 1050
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionFactory.cs:line 151
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in F:\git\corefx\src\Common\src\System\Data\ProviderBase\DbConnectionInternal.cs:line 325
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in F:\git\corefx\src\Common\src\System\Data\ProviderBase\DbConnectionClosed.cs:line 37
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlConnection.cs:line 1190
   at System.Data.SqlClient.SqlConnection.Open() in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlConnection.cs:line 757
   at System.Data.SqlClient.Tests.SqlErrorCollectionTest.CreateCollection() in F:\git\corefx\src\System.Data.SqlClient\tests\FunctionalTests\SqlErrorCollectionTest.cs:line 143
   at System.Data.SqlClient.Tests.SqlErrorCollectionTest.GetEnumerator_Success() in F:\git\corefx\src\System.Data.SqlClient\tests\FunctionalTests\SqlErrorCollectionTest.cs:line 106
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in F:\git\corefx\src\Common\src\System\Data\ProviderBase\DbConnectionClosed.cs:line 37
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlConnection.cs:line 1190
   at System.Data.SqlClient.SqlConnection.Open() in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlConnection.cs:line 757
   at System.Data.SqlClient.Tests.ExceptionTest.<>c__DisplayClass9_0.<NamedPipeTest>b__0() in F:\git\corefx\src\System.Data.SqlClient\tests\FunctionalTests\ExceptionTest.cs:line 98
----- Inner Stack Trace -----

----- Inner Stack Trace -----
   at System.Data.SqlClient.TdsParserStateObjectFactory.get_EncryptionOptions() in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\TdsParserStateObjectFactory.Windows.cs:line 28
   at System.Data.SqlClient.TdsParser..cctor() in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\TdsParser.cs:line 69
----- Inner Stack Trace -----
   at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize(IntPtr pmo)
   at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize() in F:\git\corefx\src\System.Data.SqlClient\src\Interop\SNINativeMethodWrapper.Windows.cs:line 288
   at System.Data.SqlClient.SNILoadHandle..ctor() in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\TdsParserSafeHandles.cs:line 35
   at System.Data.SqlClient.SNILoadHandle..cctor() in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\TdsParserSafeHandles.cs:line 19
```

[testResults.zip](https://github.com/dotnet/corefx/files/2669833/testResults.zip)

**Comment by danmosemsft** [comment]
SqlClient depends on sni.dll. On customer machines it comes from the runtime.native.System.Data.SqlClient.sni package which itself references these
```
      <dependency id="runtime.win-arm64.runtime.native.System.Data.SqlClient.sni" version="4.4.0" />
      <dependency id="runtime.win-x64.runtime.native.System.Data.SqlClient.sni" version="4.4.0" />
      <dependency id="runtime.win-x86.runtime.native.System.Data.SqlClient.sni" version="4.4.0" />
```
I don't see ARM32 there. @AfsanehR is sni.dll offered for 32 bit Windows ARM?

**Comment by AfsanehR** [comment]
@danmosemsft No we don't offer sni.dll for arm32.

**Comment by joperezr** [comment]
I guess in that case we should probably have an arm32 implementation of the library that just throws PNSE?

**Comment by danmosemsft** [comment]
Yes, but I'm not sure which of the S.D.SC package itself, the S.D.SC.sni package, or the runtime...xxx..S.D.SC.sni package. I guess ideally them all, but if it's easiest to add toe the managed package then I would do that.

**Comment by divega** [comment]
@AfsanehR @joperezr @danmosemsft Wondering if this issue should be mirrored on the SqlClient repo, as it probably affects Microsoft.Data.SqlClient as well, or even if it would be ok to say we won't fix in System.Data.SqlClient but we can potentially fix it in Microsoft.Data.SqlClient.

Besides, in the long run we can consider using the managed implementation of SNI for any platforms that aren't supported by the native on. I understand that pivot only on Windows vs. non-Windows.

**Comment by danmosemsft** [comment]
@divega to me ARM32 support is a feature, it is up to the owners of this package whether they want new features in it but my understanding was that they would only go into M.D.SqlClient. In which case this issue should be fixed by disabling those tests for ARM32

**Comment by divega** [comment]
@danmosemsft ok, so my understanding is:

1. This issue can remain here in CoreFx to track disabling the tests. Should this be in the 3.0 milestone instead of Future? Can anyone handle it?
2. I created https://github.com/dotnet/SqlClient/issues/117 to track this on SqlClient

**Comment by danmosemsft** [comment]
Yes, anyone can disable the tests. EG `[ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotArmProcess))] ` if it's a single test, I think there are also conditions that can be applied on the fixture (test class). But there are plenty of ARM32 tests that need fixes or exclusions right now. It should not stop us shipping.
