### ISSUE TITLE
[arm32/Windows] System.Diagnostics.Process.Tests failures on arm32 windows

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#34004]
Running the arm32 tests on windows for System.Diagnostics.Process.Tests produced the following results: passed 257/261 tests.

4 tests failed the run for different reasons:
System.Diagnostics.Tests.ProcessStartInfoTests.Verbs_GetWithExeExtension_ReturnsExpected
```
Assert.Contains() Failure\r\nNot found: runas\r\nIn value:  String[] [\"open\"]
   at System.Diagnostics.Tests.ProcessStartInfoTests.Verbs_GetWithExeExtension_ReturnsExpected() in F:\git\corefx\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs:line 534
```
System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadVerb(useShellExecute: True) and System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadExe(useShellExecute: True)
```
Assert.Throws() Failure\r\nExpected: typeof(System.ComponentModel.Win32Exception)\r\nActual:   typeof(System.PlatformNotSupportedException): UseShellExecute is not supported on this platform.\r\n---- System.PlatformNotSupportedException : UseShellExecute is not supported on this platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo) in F:\git\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Win32.cs:line 113
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in F:\git\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Win32.cs:line 24
   at System.Diagnostics.Process.Start() in F:\git\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs:line 1216
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo) in F:\git\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs:line 1259
   at System.Diagnostics.Tests.ProcessStartInfoTests.<>c__DisplayClass50_0.<StartInfo_BadVerb>b__0() in F:\git\corefx\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs:line 1140
----- Inner Stack Trace -----
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo) in F:\git\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Win32.cs:line 113
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in F:\git\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Win32.cs:line 24
   at System.Diagnostics.Process.Start() in F:\git\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs:line 1216
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo) in F:\git\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs:line 1259
   at System.Diagnostics.Tests.ProcessStartInfoTests.<>c__DisplayClass50_0.<StartInfo_BadVerb>b__0() in F:\git\corefx\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs:line 1140
```

System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadExe(useShellExecute: False)
```
Assert.Equal() Failure\r\nExpected: 193\r\nActual:   120
   at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadExe(Boolean useShellExecute) in F:\git\corefx\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs:line 1163
```

[testResults.zip](https://github.com/dotnet/corefx/files/2669898/testResults.zip)

**Comment by danmosemsft** [comment]
`ShellExecuteExW` is not supported or only partially supported. Disable these tests for IoT. Note we already do for Nano:
```c#
        public static TheoryData<bool> UseShellExecute
        {
            get
            {
                TheoryData<bool> data = new TheoryData<bool> { false };

                if (   !PlatformDetection.IsUap // https://github.com/dotnet/corefx/issues/20204
                    && !PlatformDetection.IsWindowsNanoServer) // By design
                    data.Add(true);
                return data;
            }
        }
```
