### ISSUE TITLE
[arm32/Windows] System.Diagnostics.Tracing.Tests failures on arm32 windows

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#34005]
Running the arm32 tests on windows for System.Diagnostics.Tracing.Tests produced the following results: passed 28/36 tests.

Most of the 8 tests that fail did so with the following message:
```
Assert.NotNull() Failure
   at BasicEventSourceTests.EventTestHarness.<>c__DisplayClass2_0.<RunTests>b__0(Event data) in F:\git\corefx\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\EventTestHarness.cs:line 108
   at BasicEventSourceTests.EtwListener.OnEventHelper(TraceEvent data) in F:\git\corefx\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\EtwListener.cs:line 132
   at Microsoft.Diagnostics.Tracing.UnhandledTraceEvent.Dispatch()
   at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.DoDispatch(TraceEvent anEvent)
   at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.Dispatch(TraceEvent anEvent)
   at Microsoft.Diagnostics.Tracing.ETWTraceEventSource.RawDispatch(EVENT_RECORD* rawData)
   at Microsoft.Diagnostics.Tracing.ETWTraceEventSource.ProcessOneFile()
   at Microsoft.Diagnostics.Tracing.ETWTraceEventSource.Process()
   at BasicEventSourceTests.EtwListener.Dispose() in F:\git\corefx\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\EtwListener.cs:line 112
   at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options) in F:\git\corefx\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\EventTestHarness.cs:line 170
   at BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_ByteArray(Boolean useSelfDescribingEvents, Listener listener) in F:\git\corefx\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestsWriteEvent.cs:line 657
   at BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_ByteArray_Manifest_ETW() in F:\git\corefx\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestsWriteEvent.Etw.cs:line 69
```

[testResults.zip](https://github.com/dotnet/corefx/files/2669925/testResults.zip)

**Comment by danmosemsft** [comment]
This would need analysis. Possibly a timeout -- there are `Thread.Sleep`'s in these test files 😱 😢
