### ISSUE TITLE
[arm32/Windows] System.Diagnostics.PerformanceCounter.Tests failures on arm32 windows

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#34002]
Running the arm32 tests on windows for System.Diagnostics.PerformanceCounter.Tests produced the following results: passed 41/93 tests.

Most of the 52 failures are due to a Win32Exception happening like the following:
```
System.AggregateException : One or more errors occurred. (The system cannot find the file specified.) (The following constructor parameters did not have matching fixture data: PerformanceDataTestsFixture fixture)\r\n---- System.ComponentModel.Win32Exception : The system cannot find the file specified.\r\n---- The following constructor parameters did not have matching fixture data: PerformanceDataTestsFixture fixture
----- Inner Stack Trace #1 (System.ComponentModel.Win32Exception) -----
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) in F:\git\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Windows.cs:line 598
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in F:\git\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Win32.cs:line 24
   at System.Diagnostics.Process.Start() in F:\git\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs:line 1216
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo) in F:\git\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs:line 1259
   at System.Diagnostics.Tests.PerformanceDataTestsFixture.RegisterCounters() in F:\git\corefx\src\System.Diagnostics.PerformanceCounter\tests\PerformanceDataTests.cs:line 219
   at System.Diagnostics.Tests.PerformanceDataTestsFixture..ctor() in F:\git\corefx\src\System.Diagnostics.PerformanceCounter\tests\PerformanceDataTests.cs:line 244
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

[testResults.zip](https://github.com/dotnet/corefx/files/2669876/testResults.zip)

**Comment by danmosemsft** [comment]
The test is trying to invoke a Windows tool called `lodctr` to register new performance counters. That tool does not exist on Windows IoT apparently. We should disable all tests that need this.

All those tests are in PerformanceDataTests. That is already guarded by `[ConditionalFact(typeof(Helpers), nameof(Helpers.IsElevatedAndCanWriteToPerfCounters))]` but the PerformanceDataTestsFixture constructor, which is throwing here, is not guarded. We should 
1. update the implementation of `Helpers.IsElevatedAndCanWriteToPerfCounters` so that it returns false for IoT (as it does already for Nano)
2. make `PerformanceDataTestsFixture()` return immediately if `Helpers.IsElevatedAndCanWriteToPerfCounters` is not true.

**Comment by wtgodbe** [comment]
Looks like the first was done by https://github.com/dotnet/corefx/commit/229fad3002e6f986b3ae6eab08bc023abaf99bec#diff-290552751e0ce621017c8a655f3deec1, looking into the second.

**Comment by wtgodbe** [comment]
Closing as this looks to be fixed, if @joperezr sees another failure like this in the next arm32 run we can reopen.
