### ISSUE TITLE
[arm32/Windows] System.Diagnostics.EventLog.Tests failures on arm32 windows

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#34000]
Running the arm32 tests on windows for System.Diagnostics.EventLog.Tests produced the following results: passed 38/88 tests.

Most test fail with messages like the following:
```
System.InvalidOperationException : Cannot open log SourceExistenceLog on computer '.'. This function is not supported on this system.
   at System.Diagnostics.EventLogInternal.OpenForRead(String currentMachineName) in F:\git\corefx\src\System.Diagnostics.EventLog\src\System\Diagnostics\EventLogInternal.cs:line 1112
   at System.Diagnostics.EventLogInternal.Clear() in F:\git\corefx\src\System.Diagnostics.EventLog\src\System\Diagnostics\EventLogInternal.cs:line 481
   at System.Diagnostics.EventLog.Clear() in F:\git\corefx\src\System.Diagnostics.EventLog\src\System\Diagnostics\EventLog.cs:line 227
   at System.Diagnostics.EventLog.Delete(String logName, String machineName) in F:\git\corefx\src\System.Diagnostics.EventLog\src\System\Diagnostics\EventLog.cs:line 407
   at System.Diagnostics.EventLog.Delete(String logName) in F:\git\corefx\src\System.Diagnostics.EventLog\src\System\Diagnostics\EventLog.cs:line 371
   at System.Diagnostics.Tests.EventLogSourceCreationTests.<>c__DisplayClass0_0.<CheckSourceExistenceAndDeletion>b__0() in F:\git\corefx\src\System.Diagnostics.EventLog\tests\EventLogTests\EventLogSourceCreationTests.cs:line 24
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass4_0.<RetryOnWin7>b__0() in F:\git\corefx\src\System.Diagnostics.EventLog\tests\Helpers.cs:line 21
   at System.Diagnostics.Tests.Helpers.RetryOnWin7[T](Func`1 func) in F:\git\corefx\src\System.Diagnostics.EventLog\tests\Helpers.cs:line 28
   at System.Diagnostics.Tests.Helpers.RetryOnWin7(Action func) in F:\git\corefx\src\System.Diagnostics.EventLog\tests\Helpers.cs:line 21
   at System.Diagnostics.Tests.EventLogSourceCreationTests.CheckSourceExistenceAndDeletion() in F:\git\corefx\src\System.Diagnostics.EventLog\tests\EventLogTests\EventLogSourceCreationTests.cs:line 24
```
Perhaps all of these should just be skipped since it looks like it is not supported on Windows IoT core.

[testResults.zip](https://github.com/dotnet/corefx/files/2669846/testResults.zip)

**Comment by danmosemsft** [comment]
Windows is returning ERROR_CALL_NOT_IMPLEMENTED from OpenEventLog.

That API appears in https://raw.githubusercontent.com/ms-iot/iot-utilities/master/IoTAPIPortingTool/iotcore-apis.txt

It can't even open standard logs `     <message><![CDATA[System.InvalidOperationException : Cannot open log Application on computer '.'. This function is not supported on this system.]]></message>`

My guess is that event logs aren't fully supported on IoT.

**Comment by danmosemsft** [comment]
I have confirmed that we should disable EVentLog tests on Windows IoT.

**Comment by joperezr** [comment]
Do we also want to throw PNSE on win-arm? or just disable the tests for now?
