### ISSUE TITLE
.NET Core Binary Serialization: Object cannot be stored in an array of this type

### ISSUE THREAD

**Issue by fhchina** [dotnet/corefx#34018]
The Exception Stack is:

Object cannot be stored in an array of this type. ---> System.InvalidCastException: Object cannot be stored in an array of this type.
   at System.Array.InternalSetValue(Void* target, Object value)
   at System.Array.SetValue(Object value, Int32[] indices)
   at System.Runtime.Serialization.ObjectManager.CompleteObject(ObjectHolder holder, Boolean bObjectFullyComplete)
   at System.Runtime.Serialization.ObjectManager.DoNewlyRegisteredObjectFixups(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.RegisterObject(Object obj, Int64 objectID, SerializationInfo info, Int64 idOfContainingObj, MemberInfo member, Int32[] arrayIndex)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.RegisterObject(Object obj, ParseRecord pr, ParseRecord objectPr, Boolean bIsString)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObjectEnd(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)

**Comment by fhchina** [comment]
I use VSCode to debug into the CoreFX source code, and find here "value" argument is an object with type System.Runtime.Serialization.TypeLoadExceptionHolder. This is caused by .NET Fx, please fix this bug.

**Comment by vcsjones** [comment]
Can you provide a bit of sample code and serialized data that reproduces this exception?

**Comment by fhchina** [comment]
This is a complex Object Graph in a real application. I will try to use Unit Testing to replicate this case. The original application works well in .NET Framework.

**Comment by danmosemsft** [comment]
@fhchina what configuration do you have, is this .NET Core or .NET Framework and what version?

In the debugger, what is the type of obj here:
`at System.Runtime.Serialization.ObjectManager.RegisterObject(Object obj, Int64 objectID, SerializationInfo info, Int64 idOfContainingObj, MemberInfo member, Int32[] arrayIndex)`

**Comment by vcsjones** [comment]
@danmosemsft I assume core given:

> The original application works well in .NET Framework.

**Comment by fhchina** [comment]
@danmosemsft I am porting a complex .NET application from .NET Framework 4.0 to .NET Core 2.1. This application works well under .NET Framerwork 4.0.

**Comment by fhchina** [comment]
I use VSCode to debug into CoreFX, and found the TypeLoadExceptionHolder hold an TypeName with "System.ComponentModel.DesignerAttribute". Then I use a customized SurrogateSelector to treat all Attribute subclass as null, now I still got this exception, but this time TypeLoadExceptionHolder hold an TypeName with "System.Runtime.Versioning.NonVersionableAttribute".

**Comment by fhchina** [comment]
System.Runtime.Versioning.NonVersionableAttribute is internal! which class used this stuff and need to be serialized/deserialized? Is there any tool/method to identify which is the root class to cause TypeLoadExceptionHolder to be created?

**Comment by danmosemsft** [comment]
@viktorhofer

**Comment by ViktorHofer** [comment]
@fhchina can you please give me access to the serialization payload that you try to deserialize? I should be able to find the necessary information in it.

**Comment by fhchina** [comment]
@ViktorHofer payload? Code snippet or binary files?

**Comment by joshfree** [comment]
@fhchina @ViktorHofer is there any further progress on this issue?

**Comment by ViktorHofer** [comment]
@fhchina a sample code would be ideal to reproduce the issue.

**Comment by danmosemsft** [comment]
Moving to Future as this is not actionable right now.

**Comment by jkotas** [comment]
This needs a repro to be actionable.
