### ISSUE TITLE
[arm32/Windows] System.Windows.Extensions.Tests failures on arm32 windows

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#34051]
Running the arm32 tests on windows for System.Windows.Extensions.Tests produced the following results: passed 23/38 tests.

Most failing tests have to do with missing gdpi but there are few tests that are failing with this callstack:
```
System.EntryPointNotFoundException : Unable to find an entry point named 'CreateIconFromResourceEx' in DLL 'user32.dll'.
   at System.Drawing.SafeNativeMethods.IntCreateIconFromResourceEx(Byte* pbIconBits, Int32 cbIconBits, Boolean fIcon, Int32 dwVersion, Int32 csDesired, Int32 cyDesired, Int32 flags)
   at System.Drawing.SafeNativeMethods.CreateIconFromResourceEx(Byte* pbIconBits, Int32 cbIconBits, Boolean fIcon, Int32 dwVersion, Int32 csDesired, Int32 cyDesired, Int32 flags) in F:\git\corefx\src\System.Drawing.Common\src\System\Drawing\Gdiplus.cs:line 1064
   at System.Drawing.Icon.Initialize(Int32 width, Int32 height) in F:\git\corefx\src\System.Drawing.Common\src\System\Drawing\Icon.Windows.cs:line 634
   at System.Drawing.Icon..ctor(String fileName, Int32 width, Int32 height) in F:\git\corefx\src\System.Drawing.Common\src\System\Drawing\Icon.Windows.cs:line 77
   at System.Drawing.Icon..ctor(String fileName) in F:\git\corefx\src\System.Drawing.Common\src\System\Drawing\Icon.Windows.cs:line 60
   at System.ComponentModel.TypeConverterTests.IconConverterTest..ctor() in F:\git\corefx\src\System.Windows.Extensions\tests\System\Drawing\IconConverterTests.cs:line 23
```

[testResults.zip](https://github.com/dotnet/corefx/files/2673877/testResults.zip)

**Comment by joperezr** [comment]
@karelz is there an area for System.Windows.Extensions?

**Comment by danmosemsft** [comment]
Disable test for IOT SKU
