### ISSUE TITLE
TcpListener BeginAcceptTcpClient throws loop of SocketExceptions (10057) on WindowsServer 2012

### ISSUE THREAD

**Issue by LadislavLang** [dotnet/corefx#34063]
```c#
using System;
using System.Net.Sockets;

class Program
{
    private static TcpListener listener;

    private static void Main(string[] args)
    {
        try
        {
            listener = TcpListener.Create(12345);

            listener.Start();
            listener.BeginAcceptTcpClient(AcceptClient, null);

            using (var client = new TcpClient())
            {
                client.Connect("localhost", 12345);
            }

            Console.ReadLine();
        }
        catch (Exception exception)
        {
            Console.WriteLine(exception);
        }
    }

    private static void AcceptClient(IAsyncResult asyncResult)
    {
        try
        { 
            listener.BeginAcceptTcpClient(AcceptClient, null);

            using (var client = listener.EndAcceptTcpClient(asyncResult))
            {
                Console.WriteLine("OK");
            }
        }
        catch (Exception exception)
        {
            Console.WriteLine(exception);
            Console.WriteLine();
        }
    }
}
```

Windows 10 - net47: OK
Windows 10 - netcoreapp2.1: OK
Windows 10 - netcoreapp2.2: OK
Windows 10 - netcoreapp3.0 (preview): OK

Windows Server 2012 - net47: OK
Windows Server 2012 - netcoreapp2.1 & netcoreapp2.2 & netcoreapp3.0 (preview): 

**At first, there is loop of many SocketExceptions** 
System.Net.Sockets.SocketException (10057): A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram
 socket using a sendto call) no address was supplied
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.EndAccept(Byte[]& buffer, Int32& bytesTransferred, IAsyncResult asyncResult)
   at System.Net.Sockets.TcpListener.EndAcceptTcpClient(IAsyncResult asyncResult)
   at Program.AcceptClient(IAsyncResult asyncResult)

**And finaly it crashed with one of these unhandled exceptions:** 
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Threading.ThreadPoolBoundHandle.GetNativeOverlappedState(NativeOverlapped* overlapped)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

Or

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Threading.ThreadPoolBoundHandle.GetNativeOverlappedState(NativeOverlapped* overlapped)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

Or

System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Finalize()

Or

InvalidOperationException: NativeOverlapped cannot be reused for multiple operations.
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

**PS: Sometime it crash Windows completely!**

**Comment by LadislavLang** [comment]
I noticed the problem only on standard Windows Server 2012

Windows Server 2008: OK
Windows Server 2012 R2: OK

**Comment by LadislavLang** [comment]
The same problem with Socket:

```c#
using System;
using System.Net;
using System.Net.Sockets;
using System.Threading.Tasks;

class Program
{
    private static void Main(string[] args)
    {
        var listener = new Socket(SocketType.Stream, ProtocolType.Tcp);
        listener.Bind(new IPEndPoint(IPAddress.Any, 12345));
        listener.Listen(0);

        Task.Run(new Action(() =>
        {
            try
            {
                var asyncResult = listener.BeginAccept(delegate { }, null);
                using (var socket = listener.EndAccept(asyncResult))
                {
                    Console.WriteLine("OK");
                }
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception);
            }
        }));

        using (var client = new TcpClient())
        {
            client.Connect("localhost", 12345);
        }

        Console.ReadLine();
    }
}
```
