### ISSUE TITLE
Unable to load libgdiplus on Alpine

### ISSUE THREAD

**Issue by rmkerr** [dotnet/corefx#34075]
A significant number of System.Resources tests have been failing on Alpine Linux in the daily test runs. It looks like the failure occurs when we try to load libgdiplus:
```
Message
--
System.TypeInitializationException : The type initializer for 'Gdip' threw an exception.\n---- System.DllNotFoundException : Unable to load DLL 'libgdiplus': The specified module could not be found.
```

**Comment by safern** [comment]
This is weird because we actually condition all of our Drawing tests to run only when libgdiplus is available. So something to investigate. Do yo have a link to a failure item?

**Comment by rmkerr** [comment]
Actually, it looks like this is in System.Resources rather than System.Drawing. It may be that they aren't performing the same checks to see that libgdiplus is available when they run their image related tests. I'll re-tag this. [Here's an example of the failures](https://mc.dot.net/#/product/netcore/30/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20181213.03/workItem/System.Resources.ResourceManager.Tests).

@krwq

**Comment by krwq** [comment]
Here is the error before the log disappear:

```
System.TypeInitializationException : The type initializer for 'Gdip' threw an exception.
---- System.DllNotFoundException : Unable to load DLL 'libgdiplus': The specified module could not be found.
```

```
   at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromFile(String filename, IntPtr& bitmap) in /root/corefx-2274637/src/System.Drawing.Common/src/System/Drawing/GdiplusNative.cs:line 1781
   at System.Drawing.Bitmap..ctor(String filename, Boolean useIcm) in /root/corefx-2274637/src/System.Drawing.Common/src/System/Drawing/Bitmap.cs:line 41
   at System.Drawing.Bitmap..ctor(String filename) in /root/corefx-2274637/src/System.Drawing.Common/src/System/Drawing/Bitmap.cs:line 24
   at System.Resources.Tests.ResourceManagerTests.EnglishImageResourceData()+MoveNext() in /root/corefx-2274637/src/System.Resources.ResourceManager/tests/ResourceManagerTests.cs:line 266
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext() in /root/corefx-2274637/src/System.Linq/src/System/Linq/Select.cs:line 135
----- Inner Stack Trace -----
   at System.Runtime.InteropServices.FunctionWrapper`1.get_Delegate() in /root/corefx-2274637/src/Common/src/System/Runtime/InteropServices/FunctionWrapper.cs:line 39
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output) in /root/corefx-2274637/src/System.Drawing.Common/src/System/Drawing/GdiplusNative.Unix.cs:line 287
   at System.Drawing.SafeNativeMethods.Gdip..cctor() in /root/corefx-2274637/src/System.Drawing.Common/src/System/Drawing/Gdiplus.cs:line 85
```

@safern do you know if we perhaps have a way of testing that in the CI? I don't have any alpine available to check that. I'd just condition the test the same way we do in system.drawing

**Comment by safern** [comment]
> I'd just condition the test the same way we do in system.drawing:

Exactly. Maybe we should explore adding libgdiplus to our Helix alpine images: 
https://github.com/dotnet/dotnet-buildtools-prereqs-docker/tree/master/src/alpine

I think we do have a way to test that in CI and maybe we should enable alpine tests in CI. We do it in official builds already. I will do that as part of my move to the new CI system using Azure DevOps: 
https://github.com/dotnet/corefx/pull/33821

**Comment by safern** [comment]
cc: @danmosemsft opinions on running alpine tests on CI?

**Comment by danmosemsft** [comment]
@safern maybe it's a good chance to consider our CI matrix all up. Perhaps create an issue listing the matrix  we have , and what extra legs we have on official builds, and we can consider whether we want to change it around, such as removing an existing CI leg in favor of an Alpine one?

I think for example CI always does debug and release of each configuration -- instead we could mix it up so it's debug on distro X and release on distro Y.

**Comment by safern** [comment]
Alpine is the linux-musl leg. However currently we're not sending Helix jobs for that one, just making sure the vertical for sources and tests build successfully. So I guess just adding Helix testing to it wouldn't hurt our CI as long as it is green.

I'll open the issue.
