### ISSUE TITLE
XDocument.Load badly resolves path containing %2E and some other URL encoded characters

### ISSUE THREAD

**Issue by jeffhube** [dotnet/corefx#34102]
XDocument.Load is failing to properly resolve paths that contain %2E. Given a filename like "foo%2E.txt", it attempts to open "foo..txt". This seems kind of similar to #25820.

Version: 2.2.101

```csharp
class Program
{
    static void Main(string[] args)
    {
        string filename = "foo%2E.txt";
        File.WriteAllText(filename, "<?xml version='1.0' encoding='UTF-8'?><Foo/>");
        XDocument.Load(filename);
    }
}
```

```
Unhandled Exception: System.IO.FileNotFoundException: Could not find file '****\foo..txt'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri)
   at ****.Program.Main(String[] args) in ****\Program.cs:line 13
```

**Comment by jeffhube** [comment]
Apparently this fails for filenames containing a number of url encoded characters.

```
class Program
{
    static void Main(string[] args)
    {
        for (int i = 0; i < 256; i++)
        {
            string code = "%" + i.ToString("X2");
            string filename = "foo" + code + ".txt";
            File.WriteAllText(filename, "<?xml version='1.0' encoding='UTF-8'?><Foo/>");
            try
            {
                XDocument.Load(filename);
            }
            catch
            {
                Console.WriteLine(code);
            }
            File.Delete(filename);
        }
    }
}
```

Output:
```
%2D
%2E
%30
%31
%32
%33
%34
%35
%36
%37
%38
%39
%41
%42
%43
%44
%45
%46
%47
%48
%49
%4A
%4B
%4C
%4D
%4E
%4F
%50
%51
%52
%53
%54
%55
%56
%57
%58
%59
%5A
%5F
%61
%62
%63
%64
%65
%66
%67
%68
%69
%6A
%6B
%6C
%6D
%6E
%6F
%70
%71
%72
%73
%74
%75
%76
%77
%78
%79
%7A
%7E
```

Unencoded, that's the following characters:
`-.0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz~`

**Comment by rmkerr** [comment]
Those characters are all unreserved in URIs, and so will be decoded by System.Uri. If you try encoding the % sign, does that work? For example:
```csharp
string filename = "foo%252E.txt";
```

**Comment by jeffhube** [comment]
No, that fails with:
```
Unhandled Exception: System.IO.FileNotFoundException: Could not find file '****\foo%252E.txt'.
```

It seems to work if I encode the % AND specify an absolute file uri, like this:
```
string filename = "file:///" + Path.GetFullPath("foo%252E.txt");
```

But I haven't found a built-in way to convert from a filename to a file uri that properly handles these characters in the file name. This stackoverflow post provides a rather ugly method to do so: https://stackoverflow.com/a/35734486/471775.

At that point, using File.OpenRead() and then XDocument.Load(Stream) is an easier workaround. It seems that it may have been better to have Load(string path) and Load(Uri uri) rather than Load(string uri), but I'm guessing that can't be changed now? Maybe something like LoadFile(string path) could be introduced?

**Comment by krwq** [comment]
Closing as dup of https://github.com/dotnet/corefx/issues/24439
