### ISSUE TITLE
GetComObjectData throws PlatformNotSupportedException

### ISSUE THREAD

**Issue by KexyBiscuit** [dotnet/corefx#34236]
Exception details following.
```
System.PlatformNotSupportedException
  HResult=0x80131539
  Message=Operation is not supported on this platform.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.InteropServices.Marshal.GetComObjectData(Object obj, Object key)
   at System.Runtime.InteropServices.ComEventsInfo.Find(Object rcw)
   at System.Runtime.InteropServices.ComEventsInfo.FromObject(Object rcw)
   at System.Runtime.InteropServices.ComEventsHelper.Combine(Object rcw, Guid iid, Int32 dispid, Delegate d)
   at System.Runtime.InteropServices.ComAwareEventInfo.AddEventHandler(Object target, Delegate handler)
   at WAPIWrapperCSharp.WindAPI..ctor() in C:\Users\KexyBiscuit\Source\Repos\Azure DevOps\BTQuantSquare\WAPIWrapperCSharp\src\WAPIWrapperCSharp\WindAPI.cs:line 28
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\KexyBiscuit\Source\Repos\Azure DevOps\BTQuantSquare\WAPIWrapperCSharp\ConsoleApp1\Program.cs:line 9
```

**Comment by jkotas** [comment]
This was fixed by https://github.com/dotnet/corefx/issues/31015. Your app is probably targeting old runtime that does not have this fix yet. Could you please check that your .csproj file has `<TargetFramework>netcoreapp3.0</TargetFramework>`?

**Comment by KexyBiscuit** [comment]
@jkotas Yes, I'm on netcoreapp3.0.

**Comment by KexyBiscuit** [comment]
After restarting Windows, I get a new exception.

```
System.InvalidCastException
  HResult=0x80004002
  Message=Specified cast is not valid.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.InteropServices.ComTypes.IConnectionPoint.Advise(Object pUnkSink, Int32& pdwCookie)
   at System.Runtime.InteropServices.ComEventsSink.Advise(Object rcw)
   at System.Runtime.InteropServices.ComEventsInfo.AddSink(Guid& iid)
   at System.Runtime.InteropServices.ComEventsHelper.Combine(Object rcw, Guid iid, Int32 dispid, Delegate d)
   at System.Runtime.InteropServices.ComAwareEventInfo.AddEventHandler(Object target, Delegate handler)
   (further StackTrace are omitted)
```

The code runs perfectly on .NET Framework 4.7.2.

**Comment by KexyBiscuit** [comment]
Should this issue being transferred to CoreCLR repo?

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
@KexyBiscuit This is more than likely due to lack of support for COM Events. That is still an area we are exploring to add support. I am not confident that is the issue here, but it definitely could be. In either case, this bug should be moved to CoreCLR and closed in the CoreFX repo. Thanks.
