### ISSUE TITLE
Dotnet 2.1 & dotnet2.2 app crashing with duplicate key in environment variable

### ISSUE THREAD

**Issue by ashishnegi** [dotnet/corefx#34263]
In a particular setup, `Environment.GetEnvironmentVariables();` in dotnet 2.1 `Linux` apps is throwing :

```cs
System.ArgumentException: Item has already been added. Key in dictionary: 'LD_LIBRARY_PATH'  Key being added: 'LD_LIBRARY_PATH'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Environment.ToHashtable(IEnumerable`1 pairs)
   at Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at SInnovations.ServiceFabric.RegistrationMiddleware.AspNetCore.FabricContainer..ctor(ServiceCollection services) in C:\dev\ServiceFabricGateway\src\S-Innovations.ServiceFabric.RegistrationMiddleware.AspNetCore\FabricContainer.cs:line 172
   at SInnovations.ServiceFabric.GatewayService.Program.Main(String[] args) in C:\dev\ServiceFabricGateway\apps\S-Innovations.ServiceFabric.GatewayService\Program.cs:line 78adminuser@nt1vm000001:/mnt/sfroot/_App/S-Innovations.ServiceFabric.GatewayApplicationType_App6/S-InnoPkg.Code.1.0.0$ abric.GatewayServiceP
```

If I print command `env` from same bash script that starts `dotnet app.dll`, I see only one `LD_LIBRARY_PATH`.
When I use reflection to print the `KeyValuePair`s from `EnvironmentAugments.EnumerateEnvironmentVariables()`  (reference [here](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/Environment.cs#L34)), I see `2` values for `LD_LIBARRY_PATH`.

**Note** : The app works fine if I use dotnet 2.0 runtime.

This was handled gracefully in dotnet 2.0. Linux utilities like `env` also handle this.
This should be handled gracefully by dotnet >=  2.1 runtime as well.

I opened the bug here as implementation of `EnvironmentAugment.Unix` is [here](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/Internal/Runtime/Augments/EnvironmentAugments.Unix.cs#L28).

**Comment by jkotas** [comment]
Looks like variant of #30341

**Comment by ashishnegi** [comment]
@jkotas Excellent! it is same issu.e
In which version of dotnet 2.1.* and 2.2.* will the fix be available ?

**Comment by danmosemsft** [comment]
@ashishnegi it is not planned to backport that fix. Can you fix whatever is corrupting your environment block? Or (if not in production) use 3.0 preview 1?

**Comment by ashishnegi** [comment]
@danmosemsft we will fix our bug. However, since this was handled gracefully in dotnet 2.0, we did not find the bug sooner. So, there will be many installations of our environment.
Since, our new customers are facing this issue during development, let me redirect this question to them if they are willing to switch to dotnet 3.0.

**Comment by danmosemsft** [comment]
For reference this was regressed in 2.1 by https://github.com/dotnet/coreclr/commit/38528f6662f24c37e11bac67a56ff7269e8e4f6e . Previously duplicates were overwritten by accumulating them with `results[key] = value;`. Assuming environment blocks were non corrupted this was a reasonable change.

@ashishnegi I would try to find out why their environment blocks are corrupted. There was some suggestion that it could occur with environment variables set in the web.config.

**Comment by ashishnegi** [comment]
we have found the bug (It is in the host that starts dotnet process).
We found a workaround to work with dotnet 2.1 and 2.2.
`Environment.SetEnvironmentVariable("LD_LIBRARY_PATH", null);`
