### ISSUE TITLE
 X509ContentType.SerializedCert and X509ContentType.SerializedStore Unix Alternative?

### ISSUE THREAD

**Issue by Najsr** [dotnet/corefx#34340]
Hello, I have a problem with exporting X509Certificate2 to byte array via Export function. I am using .NET Core 2.1. The problem is that it works on Windows but when I compile my project for Debian.9-64 I get this error:

```
Unhandled Exception: System.PlatformNotSupportedException: X509ContentType.SerializedCert and X509ContentType.SerializedStore are not supported on Unix.
   at Internal.Cryptography.Pal.ExportProvider.Export(X509ContentType contentType, SafePasswordHandle password)
   at System.Security.Cryptography.X509Certificates.X509Certificate.Export(X509ContentType contentType, String password)
```
The lines it fails on:
```
serverCertificate.Export(X509ContentType.SerializedCert),
clientCertificate.Export(X509ContentType.Pkcs12)
```
Is there any workaround for this?

Thanks in advance.

**Comment by manuscrypt** [comment]
What was the workaround here?

**Comment by Najsr** [comment]
I loaded them via File.ReadAllBytes to byte array.
