### ISSUE TITLE
System.Private.CoreLib   at System.ReadOnlySpan`1..ctor(Void* pointer, Int32 length)

### ISSUE THREAD

**Issue by spushpendra2000** [dotnet/corefx#34359]
I have core 2.0 project as Target Framework  but the SDK is 2.1  amd i am getting this exception in Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc. 

I can see that it got something to do with System.Memory version which i am using. Please suggest the issue and the possible workaround.

  - Exception Message [Specified argument was out of the range of valid values.]
 ### ###  - Exception Source [System.Private.CoreLib]
 ### ###  - Exception StackTrace [   at System.ReadOnlySpan`1..ctor(Void* pointer, Int32 length)
   at Interop.Sys.DirectoryEntry.GetName(Span`1 buffer)
   at System.IO.Enumeration.FileSystemEntry.get_FileName()
   at System.IO.Enumeration.FileSystemEntry.get_FullPath()
   at System.IO.Enumeration.FileSystemEntry.Initialize(FileSystemEntry& entry, DirectoryEntry directoryEntry, ReadOnlySpan`1 directory, ReadOnlySpan`1 rootDirectory, ReadOnlySpan`1 originalRootDirectory, Span`1 pathBuffer)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance..ctor(FileSystemWatcher watcher, SafeFileHandle inotifyHandle, String directoryPath, Boolean includeSubdirectories, NotifyFilters notifyFilters, CancellationToken cancellationToken)
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionDescriptorChangeProvider.GetChangeToken()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider..ctor(IEnumerable`1 actionDescriptorProviders, IEnumerable`1 actionDescriptorChangeProviders)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)

**Comment by stephentoub** [comment]
cc: @JeremyKuhne

**Comment by stephentoub** [comment]
Presumably the failure is coming from:
https://github.com/dotnet/corefx/blob/f7539b726c4bc2385b7f49e5751c1cff2f2c7368/src/Common/src/Interop/Unix/System.Native/Interop.ReadDir.cs#L44
with the IndexOf call returning -1.
It's not clear to me where the 255 limit is coming from.

**Comment by spushpendra2000** [comment]
This is on linux platform. Do i need to update any System.Native binaries..

**Comment by stephentoub** [comment]
I suspect it's a bug in the implementation, not in how you're using it.

Do you have any really long directory or file names?

**Comment by spushpendra2000** [comment]
Which file it is referring to which is resulting in exception?. i dont think i have long file path installation directory. Some dependent dll might be residing on long path.. Also, i am not getting this issue on all linux machine.

**Comment by spushpendra2000** [comment]
I check the dependent dll path as well.. It is hardly 60 char long.. Please let me know the which file you are talking about so that i can check.. But i dont think i have long path...

**Comment by stephentoub** [comment]
A FileSystemWatcher is being used here to monitor some directory or file. I'm wondering about those files being monitored, as it would appear that getting the information for one of those is causing this issue.

**Comment by spushpendra2000** [comment]
All i am doing is using WebHostBuilder().
var host = new WebHostBuilder()
                                .UseKestrel()
                                .UseUrls(string.Format(url, port))
                                .UseContentRoot(Directory.GetCurrentDirectory())
                                .UseIISIntegration()
                                .UseStartup<Startup>()
                                .Build();
This Configure method implement in Startup class gets called at runtime.  This is more of internal implementation of "app.UseMvc();" which might be causing the issue.

 public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            const string function = "Configure";
            try
            {      

                app.UseResponseBuffering();


                app.UseStaticHttpContext();

                app.UseMvc();
            }
            catch (Exception e)
            {
                GlobalInitializer.getLogger().logException(function, e);
            }
        }

**Comment by danmosemsft** [comment]
> It's not clear to me where the 255 limit is coming from.

I believe Linux has a maximum filename length of 255 characters for most filesystems. limits.h has 
`#define NAME_MAX         255	/* # chars in a file name */`

**Comment by danmosemsft** [comment]
@spushpendra2000 what distro is this exactly?

@mikem8361 do we have instructions on how to get a dump on Linux at the point of a managed exception? Looking at [createdump](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/xplat-minidump-generation.md) it does not have a flag to do this? I'm wondering what the best approach is.

**Comment by danmosemsft** [comment]
According to [man readdir](https://linux.die.net/man/3/readdir) `The only fields in the dirent structure that are mandated by POSIX.1 are: d_name[], of unspecified size, with at most NAME_MAX characters preceding the terminating null byte;`

So that's 256. Should the 255 above be 256?

**Comment by mikem8361** [comment]
Setting the COMPlus_DbgEnableMiniDump env var to 1 will generate a core dump on a unhandled exception, but createdump has no way to catch a handled/caught exception.

**Comment by danmosemsft** [comment]
@mikem8361 where is the best place to get createdump (for 2.1 in this case)? it does not seem to be in the SDK?

**Comment by mikem8361** [comment]
Createdump is in the runtime directory i.e. /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.6/createdump.

**Comment by danmosemsft** [comment]
OK @spushpendra2000 please set the environment variable COMPlus_DbgEnableMiniDump to 1 then use createdump to get a dump. There is more info here:

https://github.com/dotnet/coreclr/blob/master/Documentation/botr/xplat-minidump-generation.md

**Comment by danmosemsft** [comment]
Never mind about the dump, I was correct:
```
dan@DESKTOP-CJJBOPC:~/2$ cat Program.cs
﻿using System;
using System.IO;

public class Program
{
    public static void Main(string[] args)
    {
        var files = Directory.GetFiles(args[0]);
        Console.WriteLine(String.Join("\n", files));
    }
}

dan@DESKTOP-CJJBOPC:~/2$ echo x > 1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890aaaaa
dan@DESKTOP-CJJBOPC:~/2$ dotnet run -- .
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.ReadOnlySpan`1..ctor(Void* pointer, Int32 length)
   at Interop.Sys.DirectoryEntry.GetName(Span`1 buffer)
   at System.IO.Enumeration.FileSystemEntry.get_FileName()
   at System.IO.Enumeration.FileSystemEnumerableFactory.<>c__DisplayClass3_0.<UserFiles>b__1(FileSystemEntry& entry)
   at System.IO.Enumeration.FileSystemEnumerable`1.DelegateEnumerator.ShouldIncludeEntry(FileSystemEntry& entry)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Microsoft.DotNet.Tools.Run.RunCommand.FindSingleProjectInDirectory(String directory)
   at Microsoft.DotNet.Tools.Run.RunCommand.Initialize()
   at Microsoft.DotNet.Tools.Run.RunCommand.Start()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by danmosemsft** [comment]
@spushpendra2000 you can do something like this to find the 255 character file or directory that is causing the problem: `strace -v dotnet run 2>&1 | grep 'd_name=\"[^"]\{255\}'`
eg
```
$ strace -v dotnet run 2>&1 | grep 'd_name=\"[^"]\{255\}'
getdents(106, [{d_ino=24769797950594414, d_off=1, d_reclen=24, d_name=".", d_type=DT_DIR}, {d_ino=24769797950594414, d_off=2, d_reclen=24, d_name="..", d_type=DT_DIR}, {d_ino=19421773393098317, d_off=3, d_reclen=280, d_name="1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890aaaa
", d_type=DT_REG}, {d_ino=7318349395540441, d_off=4, d_reclen=32, d_name="2.csproj", d_type=DT_REG}, {d_ino=45317471250430409, d_off=5, d_reclen=32, d_name="Program.cs", d_type=DT_REG}, {d_ino=5910974511987683, d_off=6, d_reclen=24, d_name="bin", d_type=DT_DIR}, {d_ino=2251799814814356, d_off=7, d_reclen=24, d_name="obj", d_type=DT_DIR}, {d_ino=63613344736656169, d_off=8, d_reclen=24, d_name="out", d_type=DT_REG}], 32768) = 464
```
Once you have that, delete or rename it to work around this bug.

**Comment by spushpendra2000** [comment]
I dont see any relevant file with big file path. Attaching strace response. Please let me know
[strace.log](https://github.com/dotnet/corefx/files/2733494/strace.log)

**Comment by danmosemsft** [comment]
@spushpendra2000 are you including the `-v` flag? That is necessary to see it.

**Comment by spushpendra2000** [comment]
Since the issue is closed and looks like fix is already made. Please let me know the the corresponding core dll to download for this fix.
