### ISSUE TITLE
System.IO.Tests.FileInfo_GetSetTimes/CopyToNanosecondsPresent

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#34364]
Related #20818 #31116 #3272

System.IO.Tests.FileInfo_GetSetTimes/CopyToNanosecondsPresent

[Helix / repro instructions](https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/5f009736e46746fb6aaef810dc2bb2f64ed6bf84/workItem/System.IO.FileSystem.Tests/analysis/xunit/System.IO.Tests.FileInfo_GetSetTimes~2FCopyToNanosecondsPresent
)
```
Windows.7.Amd64.Open-x86-Release
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Tests failed to create a file with non-zero nanoseconds.
Expected: True
Actual:   False
Stack Trace :
   at System.IO.Tests.FileInfo_GetSetTimes.GetNonZeroNanoseconds() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.IO.FileSystem\tests\FileInfo\GetSetTimes.cs:line 59
   at System.IO.Tests.FileInfo_GetSetTimes.CopyToNanosecondsPresent() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.IO.FileSystem\tests\FileInfo\GetSetTimes.cs:line 129
```

**Comment by danmosemsft** [comment]
@anipik fixed now?

**Comment by Anipik** [comment]
Yes it is fixed
