### ISSUE TITLE
FileSystemWatcher_File_Create_ForceLoopRestart failed on Unix

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#34361]
Seems rare/sporadic.
```
System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Create_ForceLoopRestart(useExistingWatchers: False)
Failed 5 hours ago
Duration0:00:03.310
Ownernot available

Debug

Work items

Attachments

History
Error message
Assert.True() Failure\nExpected: True\nActual: False
Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.<>c__DisplayClass3_0.<FileSystemWatcher_File_Create_ForceLoopRestart>b__0() in /__w/1/s/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 144
   at System.IO.Tests.FileSystemWatcherTest.ExecuteWithRetry(Action action, Int32 maxAttempts) in /__w/1/s/src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 198
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Create_ForceLoopRestart(Boolean useExistingWatchers) in /__w/1/s/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 189
```

**Comment by danmosemsft** [comment]
Similar but different callstack. Failing about every 5th build on eg Redhat 7
```
RedHat.7.Amd64-x64-Release
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Assert.True() Failure
Expected: True
Actual:   False
Stack Trace :
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.<>c__DisplayClass4_0.<FileSystemWatcher_File_Create_ForceLoopRestart>b__0() in /__w/1/s/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 214
   at System.IO.Tests.FileSystemWatcherTest.ExecuteWithRetry(Action action, Int32 maxAttempts) in /__w/1/s/src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 198
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Create_ForceLoopRestart(Boolean useExistingWatchers) in /__w/1/s/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 226
```

@JeremyKuhne

**Comment by danmosemsft** [comment]
If this is unavoidable OS vagaries, we could make the test retry a few times.

**Comment by stephentoub** [comment]
This test is failing a lot, e.g. on Ubuntu 18.04 at https://dev.azure.com/dnceng/public/_build/results?buildId=203907&view=ms.vss-test-web.build-test-results-tab&runId=4938070&paneView=debug&resultId=122690
```
Error message
Assert.True() Failure\nExpected: True\nActual: False

Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.<>c__DisplayClass4_0.<FileSystemWatcher_File_Create_ForceLoopRestart>b__0() in /_/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 179
   at System.IO.Tests.FileSystemWatcherTest.ExecuteWithRetry(Action action, Int32 maxAttempts) in /_/src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 198
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Create_ForceLoopRestart(Boolean useExistingWatchers) in /_/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 161
```

**Comment by danmosemsft** [comment]
@carlossanlop maybe add more sleep/retries?

**Comment by stephentoub** [comment]
Again:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38817~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190624.2/workItem/System.IO.FileSystem.Watcher.Tests/analysis/xunit/System.IO.Tests.FileSystemWatcher_Multiple_Test~2FFileSystemWatcher_File_Create_ForceLoopRestart(useExistingWatchers:%20True)
```
Centos.7.Amd64.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Assert.True() Failure
Expected: True
Actual:   False
Stack Trace :
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.<>c__DisplayClass4_0.<FileSystemWatcher_File_Create_ForceLoopRestart>b__0() in /_/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 198
   at System.IO.Tests.FileSystemWatcherTest.ExecuteWithRetry(Action action, Int32 maxAttempts) in /_/src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 198
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Create_ForceLoopRestart(Boolean useExistingWatchers) in /_/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 159
```

**Comment by stephentoub** [comment]
Again here on Ubuntu and RedHat:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38804~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190701.1/workItem/System.IO.FileSystem.Watcher.Tests/analysis/xunit/System.IO.Tests.FileSystemWatcher_Multiple_Test~2FFileSystemWatcher_File_Create_ForceLoopRestart(useExistingWatchers:%20True)

**Comment by stephentoub** [comment]
> we could make the test retry a few times.

FYI, it already retries three times, with half a second between attempts.

**Comment by ViktorHofer** [comment]
This is currently the failing test in Outerloop. We don't want to loose the coverage but I currently tend towards disabling the test.

**Comment by wfurt** [comment]
I have reasonable repro (on Ubuntu) . I'll take a look.

**Comment by stephentoub** [comment]
Failed again here on Ubuntu:
https://dev.azure.com/dnceng/public/_build/results?buildId=336495&view=ms.vss-test-web.build-test-results-tab&runId=9915528&resultId=100009&paneView=debug
```

Error message
Assert.True() Failure\nExpected: True\nActual: False

Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.<>c__DisplayClass4_0.<FileSystemWatcher_File_Create_ForceLoopRestart>b__0() in /_/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 177
   at System.IO.Tests.FileSystemWatcherTest.ExecuteWithRetry(Action action, Int32 maxAttempts) in /_/src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 198
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Create_ForceLoopRestart(Boolean useExistingWatchers) in /_/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 159
```

**Comment by wfurt** [comment]
Based on my investigation FileSystemWatcher_File_Create_ForceLoopRestart is victim of FileSystemWatcher_CreateManyConcurrentWatches. 

I don't know if you have more thoughts on #40543 @stephentoub besides XUnit issue. I did not get any traction on that so we also have option to serialize all tests instead of disabling individual tests broken by CreateManyConcurrentWatches.
