### ISSUE TITLE
SMTP send throws AuthenticationException on Linux

### ISSUE THREAD

**Issue by kspearrin** [dotnet/corefx#34407]
Certain SMTP mail servers (in this case, mailjet.com) will throw an `AuthenticationException` when trying to send mail from an .NET Core console applications (or asp.net web applications) that are running on Linux.

For example:

    class Program
    {
        static void Main(string[] args)
        {
            MainAsync().Wait();
        }

        public static async Task MainAsync()
        {
            try
            {
                var client = new SmtpClient("in-v3.mailjet.com", 587)
                {
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    Credentials = new NetworkCredential("user",
                        "password")
                };

                var message = new MailMessage
                {
                    From = new MailAddress("app@example.com"),
                    Subject = "Testing SMTP Email",
                    SubjectEncoding = Encoding.UTF8,
                    BodyEncoding = Encoding.UTF8,
                    BodyTransferEncoding = System.Net.Mime.TransferEncoding.QuotedPrintable,
                    Body = "<p>Hi, This is a test email.</p>",
                    IsBodyHtml = true
                };

                message.To.Add(new MailAddress("me@example.com"));
                client.SendCompleted += (sender, e) =>
                {
                    if(e.Error != null)
                    {
                        Console.WriteLine("SendCompleted Error: " + e.Error.Message + " : " + e.Error.ToString());
                    }

                    if(e.Cancelled)
                    {
                        Console.WriteLine("SendCompleted Cancelled");
                    }

                    message.Dispose();
                    client.Dispose();
                };

                client.SendAsync(message, null);
                Console.WriteLine("Mail sent.");
            }
            catch(Exception e)
            {
                Console.WriteLine("There was an exception. " + e.Message);
            }

            await Task.Delay(2000);
            Console.ReadLine();
            await Task.Delay(2000);
            Console.ReadLine();
        }
    }

Using my SMTP settings provided by mailjet.com (you can create a free account there to test), I can send email just fine from this application running locally (Windows 10) or when the application deployed to Azure as a Windows web app.

However, if I build this application into a Linux Docker image (asp.net or .net core runtime) or just run it on an Ubuntu desktop, it fails to send mail with an `AuthenticationException`.

> System.Net.Mail.SmtpException: Failure sending mail. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.

I can change my mail settings to another server, such as SendGrid, and it works fine both on my local Windows 10 machine, Azure, in the Docker container, and on the Ubuntu desktop.

It seems like this is a problem with a missing CA for mailjet's SSL cert or something, but I can see the DigiCert CA on all hosts and in the Linux docker container.

I don't understand why it works in other environments, but not a Docker container or on Ubuntu desktop.

**Comment by davidsh** [comment]
I see that the TLS/SSL certificate for X uses a wildcard certificate:
![image](https://user-images.githubusercontent.com/7684835/50804945-1acc2100-12a5-11e9-9104-dbdabe3a7a6d.png)

We have had some issues with validating wildcard certs on Linux.

What version of .NET Core are you using?  

@bartonjs

**Comment by davidsh** [comment]
@bartonjs Is this issue related to #34061 ?

**Comment by davidsh** [comment]
This is the TLS/SSL certificate that is being used during the SMTP "StartTLS" upgrade:

[server_cert.zip](https://github.com/dotnet/corefx/files/2738227/server_cert.zip)

**Comment by davidsh** [comment]
@bartonjs I was able to repro this problem using 2.1.6.  So, it's not fixed in that release.

```
root@8d7fe2277d27:/home/davidsh/test# dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.500/

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.500 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by davidsh** [comment]
And setting the environment variable doesn't seem to help either:

```
SSL_CERT_DIR=/dev/null
TERM=xterm
UID=0
_=SSL_CERT_DIR
root@8d7fe2277d27:/home/davidsh/test# dotnet run
Mail sent.
SendCompleted Error: Failure sending mail. : System.Net.Mail.SmtpException: Failure sending mail. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
```

**Comment by bartonjs** [comment]
@davidsh Weird.  My chain printing tool says it's valid using default options on the chain with the 2.1.7 build (sdk 2.1.503) on Ubuntu 16.04.  My 18.04 is taking a really, really long time to boot up; so I haven't been able to check it there.

The X509Chain object will report why it's not happy, I recommend seeing what it says is wrong.

**Comment by wfurt** [comment]
I tested this on 16.04 and 18.04 with current master and it worked in both cases. Since it is unlikely IMHO this would meet back-porting bar,  I suggest we close this.

**Comment by davidsh** [comment]
@wfurt 

>I tested this on 16.04 and 18.04 with current master and it worked in both cases. Since it is unlikely IMHO this would meet back-porting bar, I suggest we close this.

When I validated the repro, I was getting a failure in .NET Core 2.1.6.  Did you get a failure in 2.1.6?

We should understand 1) that we can repro the failure in 2.x, 2) we can show no failure in 3.0 (master), and 3) we understand why/how this is fixed.  Once we have those things understood, then we can close this.

**Comment by wfurt** [comment]
no, I did not test with 2.1. I wanted to see if we need to work on fix. I agree it would be nice to know specific reason/fix.

**Comment by wesley-pattison** [comment]
I'm currently facing this problem on AKS when trying to send emails through `in-v3.mailjet.com:587`

In my Docker File I use 
`FROM microsoft/dotnet:2.2-sdk AS build` and `FROM microsoft/dotnet:2.2-aspnetcore-runtime AS runtime`. Our images are built in Azure DevOps building on a hosted linux agent.

Exception thrown: `System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.`

**Comment by am11** [comment]
About v2.1 series of dotnet SDK Docker:

* 2.1.403 was released on October 2.
* 2.1.500 was released on Nov 13.
* the latest is 2.1.504 was released on Feb 12.

https://github.com/dotnet/dotnet-docker/commits/master/2.1/sdk/bionic/amd64/Dockerfile

We can delete/renew docker cache by using one of the methods:

* executing `docker system prune`
* executing `docker rm $(docker ps -aq) ;  docker rmi $(docker images -aq)`
* build with `docker build --tag myNetCoreApp --no-cache --rm=true .`

or if user has no control over system to execute either of aforementioned command (in FAAS, CAAS, CIAAS scenarios), one can fallback to extrating release archive in the existing docker script:

```sh
#!/usr/bin/env sh
PREFERRED_DOTNET_NAME="dotnet-sdk-2.1.504-linux-x64"
PREFERRED_DOTNET_DIR=~/"$PREFERRED_DOTNET_NAME"

if [ ! -d "$PREFERRED_DOTNET_DIR" ]; then
  # link taken from: https://github.com/dotnet/core/blob/8a34f5d/release-notes/2.1/2.1.8/2.1.8.md
  curl -O https://download.visualstudio.microsoft.com/download/pr/b35cf035-09d9-444a-8f62-c972fd6f2be0/4068a391164715232bbf4477b349643f/$PREFERRED_DOTNET_NAME.tar.gz

  mkdir $PREFERRED_DOTNET_DIR
  tar -xzvf $PREFERRED_DOTNET_NAME.tar.gz -C $PREFERRED_DOTNET_DIR

  PATH=$PREFERRED_DOTNET_DIR:$PATH
  export PATH
fi

dotnet --info

# run your app here
```

Similarly, latest in v2.2 line is `2.2.104`: `https://download.visualstudio.microsoft.com/download/pr/69937b49-a877-4ced-81e6-286620b390ab/8ab938cf6f5e83b2221630354160ef21/dotnet-sdk-2.2.104-linux-x64.tar.gz`.

**Comment by davidsh** [comment]
We've had several TLS certificate validation bugs fixed for .NET Core 3.0.

Can you please try out the .NET Core 3.0 Preview 3 release?  It probably has the fix for this scenario:

https://devblogs.microsoft.com/dotnet/announcing-net-core-3-preview-3/

**Comment by kspearrin** [comment]
@davidsh I haven’t tested this yet, but will these fixes also be coming to .net core 2.x? We don’t plan to upgrade to 3.x anytime soon.

**Comment by karelz** [comment]
We do need to get port bug fixes to 2.1, unless there is high impact on customers. Larger number of customers impacted or critical scenario blocked 
Even if we wanted to port it to 2.1, we would have to first validate on 3.0 and identify the specific fix which helped.

**Comment by akost** [comment]
Any updates on this bug?

**Comment by wfurt** [comment]
It seems like next step is to validate with 3.0 bits and possibly identify specific fix for backport.
It also seems like there may be environmental variations and that needs to be understood. I can try  2.x to see if I can reproduce same way as @davidsh

**Comment by osagga** [comment]
if anyone facing this problem on Linux (with `openssl 1.1`), this fix (https://github.com/NuGet/Home/issues/8169#issuecomment-497591809) worked for me

**Comment by wfurt** [comment]
What do you get as output of `openssl  version -d` @osagga?

**Comment by osagga** [comment]
I've updated my openssl manually to `OpenSSL 1.1.1a  20 Nov 2018` today (on `Ubuntu 19.04`) and then started noticing that all `SSL` connections in my `dotnet` app are failing. the certs mapping fix I linked above fixed it for me since the new certs folder created by the new `openssl` was just empty..

@wfurt
```
$ openssl version -d
OPENSSLDIR: "/usr/local/ssl"
```

**Comment by bartonjs** [comment]
@osagga That suggests to me that you manually built OpenSSL from source.  Ubuntu 19.04 should already come with 1.1.1, with paths that are correct for Ubuntu. https://launchpad.net/ubuntu/+source/openssl

**Comment by osagga** [comment]
@bartonjs That's correct, I had to build `OpenSSL` from source to fix a header mapping to compile another unrelated project. 

Before that `dotnet` was working just fine (I had to update to `2.2.301` to fix an `SSL` related issue, but that wasn't a problem)

**Comment by wfurt** [comment]
can somebody confirm reliable repro? I don't think custom build of openssl is unless it is built exactly same way as platform would. Itt seems like backport of 1.1.1 to 18.04 may be available now.  

All that seems unrelate to original report from @kspearrin

**Comment by wfurt** [comment]
I can reproduce this on my system with 2.1.12. (and 2.2)
I did port changes for #32224 and that did not make difference. I also do not see any  certificates with ''BEGIN TRUSTED CERTIFICATE" .  
Any suggestions how move this forward @bartonjs ?

**Comment by wfurt** [comment]
Connect to port 465 did not show any validation error. 
```
SslPolicyErrors: None

CN=in.mailjet.com, O=Mailjet SAS, L=Paris, C=FR

CN=DigiCert SHA2 Secure Server CA, O=DigiCert Inc, C=US

CN=DigiCert Global Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US

```

However, it is curious that if we negotiate TLS using STARTTLS, server would pick `Cipher Suite: TLS_DH_anon_WITH_AES_256_GCM_SHA384` and NOT send out any certificates. Packet capture attached for reference to both 587 and 465 ports.
[mailjet.pcapng.zip](https://github.com/dotnet/corefx/files/3582361/mailjet.pcapng.zip)

**Comment by wfurt** [comment]
porting #29893 to 2.1 fixes the problem. 
I don't know if we have better validation strategy for anonymous suites @bartonjs

**Comment by davidsh** [comment]
@wfurt 

>porting #29893 to 2.1 fixes the problem.

What "problem" does it fix?  The original problem reported in this issue?  Or something else?

This discussion thread has drifted from the original issue reported. It seems the theory is that the original issue is fixed already in .NET Core 3.0. Is that right?

**Comment by wfurt** [comment]
yes, it fixes originally reported issue e.g. failure to negotiate SSL with mailjet.com with 2.x. 

I could reproduce original issue with 2.1 and 2.2 and it works for me with 3.0. There was no feedback from @kspearrin if that is also true for him.

**Comment by akost** [comment]
Was it fixed in 3.0?

**Comment by davidsh** [comment]
>Was it fixed in 3.0?

Yes, the issue shouldn't occur anymore in .NET Core 3.0.
