### ISSUE TITLE
LoadFromAssemblyPath exception when assembly uses generic constraints from internally referenced assembly.

### ISSUE THREAD

**Issue by pottenger1010** [dotnet/corefx#34417]
As part of a dependency injection framework, I am performing a good deal of explicit assembly loading. I'm seeing a load failure if the assembly contains generics with a constraint which is defined in an internally referenced assembly. The `Assembly` object that is returned contains an error message from a silently thrown exception in its `Assembly.DefinedTypes`.
```
Unhandled Exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Referenced, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at SharedNamespace.Program.Main(String[] args) in C:\GenericsAssemblyIssue\Loader\Loader.cs:line 14
```

netcoreapp2.2 Loader.dll:
```
class Program
{
    static void Main(string[] args)
    {
        string assemblyPath = Path.GetFullPath("./Loadee.dll");
        Assembly assembly = AssemblyLoadContext.Default.LoadFromAssemblyPath(assemblyPath);
        Console.WriteLine(assembly.DefinedTypes);
    }
}
```
netstandard2.0 Loadee.dll:
```
public class Loadee
{
    public void DoSomething()
    {
        PrintObject(new ReferencedDerived());
    }
    public void PrintObject<T>(T baseObject) where T : ReferencedBase // <= Causes LoadFromAssemblyPath to throw ReflectionTypeLoadException
    //public void PrintObject(ReferencedBase baseObject) // <= Works
    {
        baseObject.PrintSomething();
    }
}
```
netstandard2.0 Referenced.dll (referenced by Loadee.dll):
```
public abstract class ReferencedBase
{
    public void PrintSomething()
    {
        Console.WriteLine("ReferencedBase Printing");
    }
}
public class ReferencedDerived : ReferencedBase { }
```

All projects are built to a common folder, and I run with `\Debug> dotnet Loader.dll`.

If the code is changed to remove the generics the assembly loads correctly.
Repository to show the issue: [https://github.com/pottenger1010/GenericsAssemblyIssue](https://github.com/pottenger1010/GenericsAssemblyIssue)

Is this an incorrect use of the language? or a valid problem within the loading process?
Thanks,
-Pottenger

**Comment by karelz** [comment]
@vitek-karas can you please help route it?

**Comment by vitek-karas** [comment]
This is currently a known limitation. .NET Core assembly binder by default does no probing - that includes not looking in the same directory as the assembly which is trying to resolve its reference.
The build system produces the `.deps.json` files which describe where to look for all the dependencies. Unfortunately as of .NET 2.2 the `.deps.json` is only read for the main application (so in the repro case the `loader.deps.json`). Loading assemblies dynamically at runtime doesn't consider the `.deps.json` files in any way.

In your case the code would eventually fail on the same error. The only difference between the "generics" case and "non-generics" is when the error happens. I don't know the particulars of the type loader well enough to tell the exact reason why the "generics" case tries to resolve the dependency when enumerating types and the "non-generics" one doesn't, but it's kind of moot. If you try to actually call the code it fails even in the "non-generics" case (I tried that in your repro - BTW: thanks a lot for providing that!)

There are multiple options depending on your needs:
* Implement custom resolution - for example by adding an event handler to the `AssemblyLoadContext.Default.Resolving` event and add logic which will look for the referenced assemblies in the particular folder. Pros: you have full control and can extend in the future, Cons: more code to write.
* Use `Assembly.LoadFrom` to load the `loadee`, this implements a custom resolution logic for all assemblies loaded through it which does look into the same directory. Pros: solves your immediate problem, Cons: sometimes a bit confusing behavior and can't be extended easily.
* We're working on the `.deps.json` consumption - in .NET Core 3.0 we're introducing the [`AssemblyDependencyResolver`](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyDependencyResolver.cs) class which implements the reading of the `.deps.json`. This in conjunction with the event handler above solves almost all issues. Pros: works out of the box for almost anything since it consumes the build output, Cons: 3.0 only and still requires some code (we're looking into that as well).

Side note: `AssemblyLoadCotext.LoadFromAssemblyPath` is the low-level API to load assembly from a file. It is intended to be "dumb" and only do that one thing. The resolution of dependencies is delegated to event handlers and custom `AssemblyLoadContext` instances.
