### ISSUE TITLE
System.Net.Security.Tests failed with System.ComponentModel.Win32Exception

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#34424]
**Job name:**
netcoreapp-Windows_NT-Release-x64-Windows.10.Amd64.Core

**Failed tests:**
System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_AllServerVsIndividualClientSupportedProtocols_Success
System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success
System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_EachSupportedProtocol_Success
System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_EachSupportedProtocol_Success

Error message:
```
System.ComponentModel.Win32Exception : The client and server cannot communicate, because they do not possess a common algorithm.
```
Stack trace:
```
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc) in F:\vsagent\-containerSas\33\s\src\Common\src\Interop\Windows\sspicli\SSPIWrapper.cs:line 141
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential) in F:\vsagent\-containerSas\33\s\src\System.Net.Security\src\System\Net\Security\SslStreamPal.Windows.cs:line 472
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer) in F:\vsagent\-containerSas\33\s\src\System.Net.Security\src\System\Net\Security\SslStreamPal.Windows.cs:line 177
   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint) in F:\vsagent\-containerSas\33\s\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs:line 607
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output) in F:\vsagent\-containerSas\33\s\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs:line 813
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count) in F:\vsagent\-containerSas\33\s\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs:line 731
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) in F:\vsagent\-containerSas\33\s\src\System.Net.Security\src\System\Net\Security\SslState.cs:line 749
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest) in F:\vsagent\-containerSas\33\s\src\System.Net.Security\src\System\Net\Security\SslState.cs:line 666
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult) in F:\vsagent\-containerSas\33\s\src\System.Net.Security\src\System\Net\Security\SslState.cs:line 580
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState) in F:\vsagent\-containerSas\33\s\src\System.Net.Security\src\System\Net\Security\SslStream.cs:line 216
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState) in F:\vsagent\-containerSas\33\s\src\System.Net.Security\src\System\Net\Security\SslStream.cs:line 204
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__46_1(String arg1, X509CertificateCollection arg2, SslProtocols arg3, AsyncCallback callback, Object state) in F:\vsagent\-containerSas\33\s\src\System.Net.Security\src\System\Net\Security\SslStream.cs:line 383
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions) in E:\A\_work\104\s\src\System.Private.CoreLib\src\System\Threading\Tasks\FutureFactory.cs:line 1195
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions) in E:\A\_work\104\s\src\System.Private.CoreLib\src\System\Threading\Tasks\TaskFactory.cs:line 1135
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state) in E:\A\_work\104\s\src\System.Private.CoreLib\src\System\Threading\Tasks\TaskFactory.cs:line 1092
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocatio
```
Details:
https://dnceng.visualstudio.com/internal/_build/results?buildId=67997&view=ms.vss-test-web.test-result-details

**Comment by davidsh** [comment]
Haven't seen this failure again.  Closing for now.
