### ISSUE TITLE
 System.Threading.ExecutionContext throws InvalidOperationException in 3.0 on macOS. "Cannot call Set on a null context"

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#34434]
Attempting to update https://github.com/aspnet/Extensions to the latest 3.0 builds is causing our macOS tests to fail.

See https://github.com/aspnet/Extensions/pull/914

```
2019-01-08T20:43:04.1382380Z   The active test run was aborted. Reason: Unhandled Exception: System.InvalidOperationException: Cannot call Set on a null context
2019-01-08T20:43:04.1383340Z      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2019-01-08T20:43:04.1384070Z      at System.IO.FileSystemWatcher.RunningInstance.FileSystemEventCallback(IntPtr streamRef, IntPtr clientCallBackInfo, IntPtr numEvents, Byte** eventPaths, FSEventStreamEventFlags[] eventFlags, UInt64[] eventIds)
2019-01-08T20:43:04.1384700Z      at Interop.RunLoop.CFRunLoopRun()
2019-01-08T20:43:04.1385230Z      at System.IO.FileSystemWatcher.RunningInstance.StaticWatcherRunLoopManager.WatchForFileSystemEventsThreadStart(Object args)
2019-01-08T20:43:04.1385780Z      at System.Threading.Thread.ThreadMain_ParameterizedThreadStart(Object parameter)
```

#### To reproduce

1. Clone https://github.com/aspnet/Extensions/tree/249bb27800d02610d787b8a01b233fca67aa4b99and
2. Run `build.sh` on macOS.

#### Details

Using corefx 3780052026bd1fe2e18469b216f20786b4ca20aa and https://github.com/dotnet/core-setup/tree/6daedc97324341d8d0e41602694fe6347a5b000e

**Comment by natemcmaster** [comment]
cc @Eilon  - I've marked this as partner-blocking because we cannot update aspnet/Extensions until this is resolved. Tests consistently fail with latest corefx builds.

**Comment by benaadams** [comment]
Suppressed flow case; should be easy enough to fix

**Comment by Eilon** [comment]
I pinged @MeiChin-Tsai by email.

**Comment by natemcmaster** [comment]
Wow, fast turnaround. Thanks!

**Comment by danmosemsft** [comment]
thanks for jumping on that  @benaadams

**Comment by benaadams** [comment]
@natemcmaster I'm keen to see those dependencies updated 😄
