### ISSUE TITLE
TimerFiringTests Failed in netcoreapp-Windows_NT-Release-x86-Windows.7.Amd64

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#34454]
**Job name:**
netcoreapp-Windows_NT-Release-x86-Windows.7.Amd64
**Failed tests:**
TimerFiringTests.Timer_ManyDifferentSerialSingleDueTimes_AllFireWithinAllowedRange(dueTimes: [200, 300, 400])
TimerFiringTests.Timer_ManyDifferentSerialSingleDueTimes_AllFireWithinAllowedRange(dueTimes: [332, 333, 334])
TimerFiringTests.Timer_ManyDifferentSerialSingleDueTimes_AllFireWithinAllowedRange(dueTimes: [333])
TimerFiringTests.Timer_ManyDifferentSerialSingleDueTimes_AllFireWithinAllowedRange(dueTimes: [1000])

**Failed log:**
TimerFiringTests.Timer_ManyDifferentSerialSingleDueTimes_AllFireWithinAllowedRange(dueTimes: [200, 300, 400])
```
Error message:
40% out of 200 timer firings were off by more than 100ms\r\nExpected: 200, Actuals: 463, 463, 463, 463, 463, 463, 463, 463, 463, 463, 463, 463, 463, 463, 463, 463, 463, 463, 463, 463, 367, 367, 367, 367, 367, 367, 367, 367, 367, 367, 367, 367, 367, 367, 367, 367, 367, 367, 367, 367\r\nExpected: 300, Actuals: 438, 438, 438, 438, 438, 438, 438, 438, 438, 438, 438, 438, 438, 438, 438, 438, 438, 438, 438, 438\r\nExpected: 400, Actuals: 664, 664, 664, 664, 664, 664, 664, 664, 664, 664, 664, 664, 664, 664, 664, 664, 664, 664, 664, 664\r\nExpected: True\r\nActual: False
Stack trace:
   at TimerFiringTests.Timer_ManyDifferentSerialSingleDueTimes_AllFireWithinAllowedRange(Int32[] dueTimes) in F:\vsagent\-containerSas\25\s\src\System.Threading.Timer\tests\TimerFiringTests.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
```
TimerFiringTests.Timer_ManyDifferentSerialSingleDueTimes_AllFireWithinAllowedRange(dueTimes: [332, 333, 334])
```
Error message:
37.5% out of 160 timer firings were off by more than 100ms\r\nExpected: 332, Actuals: 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597\r\nExpected: 333, Actuals: 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597\r\nExpected: 334, Actuals: 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597, 597\r\nExpected: True\r\nActual: False
Stack trace:
   at TimerFiringTests.Timer_ManyDifferentSerialSingleDueTimes_AllFireWithinAllowedRange(Int32[] dueTimes) in F:\vsagent\-containerSas\25\s\src\System.Threading.Timer\tests\TimerFiringTests.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
```
TimerFiringTests.Timer_ManyDifferentSerialSingleDueTimes_AllFireWithinAllowedRange(dueTimes: [333])
```
Error message:
33.3333333333333% out of 60 timer firings were off by more than 100ms\r\nExpected: 333, Actuals: 478, 478, 478, 478, 478, 478, 478, 478, 478, 478, 478, 478, 478, 478, 478, 478, 478, 478, 478, 478\r\nExpected: True\r\nActual: False
Stack trace:
   at TimerFiringTests.Timer_ManyDifferentSerialSingleDueTimes_AllFireWithinAllowedRange(Int32[] dueTimes) in F:\vsagent\-containerSas\25\s\src\System.Threading.Timer\tests\TimerFiringTests.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
```
TimerFiringTests.Timer_ManyDifferentSerialSingleDueTimes_AllFireWithinAllowedRange(dueTimes: [1000])
```
Error message:
100% out of 20 timer firings were off by more than 100ms\r\nExpected: 1000, Actuals: 1103, 1103, 1103, 1103, 1103, 1103, 1103, 1103, 1103, 1103, 1103, 1103, 1103, 1103, 1103, 1103, 1103, 1103, 1103, 1103\r\nExpected: True\r\nActual: False
Stack trace:
   at TimerFiringTests.Timer_ManyDifferentSerialSingleDueTimes_AllFireWithinAllowedRange(Int32[] dueTimes) in F:\vsagent\-containerSas\25\s\src\System.Threading.Timer\tests\TimerFiringTests.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
```

Details:
https://dnceng.visualstudio.com/internal/_build/results?buildId=68168&view=ms.vss-test-web.test-result-details

**Comment by danmosemsft** [comment]
Need to mine Kusto to see how this performed recently

**Comment by joshfree** [comment]
@tarekgh could you PTAL

**Comment by tarekgh** [comment]
I talked offline to @AriNuer and looks it is not clear if this is still repro. so, I tried to repro it locally on Win7 machine and I am not seeing it repo.

```
C:\test>systeminfo | findstr -i Windows
OS Name:                   Microsoft Windows 7 Ultimate
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32

C:\test>dotnet.exe xunit.console.dll System.Threading.Timer.Tests.dll -xml testResults.xml -nologo -notrait category=nonnetcoreapptests -notrait category=nonwindowstests
-notrait category=OuterLoop -notrait category=failing -method TimerFiringTests.Timer_ManyDifferentSerialSingleDueTimes_AllFireWithinAllowedRange
  Discovering: System.Threading.Timer.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Threading.Timer.Tests (found 1 of 45 test case)
  Starting:    System.Threading.Timer.Tests (parallel test collections = on, max threads = 1)
  Finished:    System.Threading.Timer.Tests
=== TEST EXECUTION SUMMARY ===
   System.Threading.Timer.Tests  Total: 7, Errors: 0, Failed: 0, Skipped: 0, Time: 8.861s
```

I am closing it and let's see if we'll get this failure again.
