### ISSUE TITLE
System.Net.Http.PerformanceTests failing with "The system cannot find the file specified."

### ISSUE THREAD

**Issue by adiaaida** [dotnet/corefx#34499]
failed again: https://ci2.dot.net/job/dotnet_corefx/job/perf/job/master/job/perf_windows_nt_release/7660/

failed log:
```
C:\j\w\perf_windows_---356c2fc4\.packages\microsoft.dotnet.corefxtesting\1.0.0-beta.19054.13\build\core\Core.targets(198,5): warning MSB3073: The command "C:\j\w\perf_windows_---356c2fc4\artifacts\bin\tests\System.Net.Http.PerformanceTests\netcoreapp-Windows_NT-Release-x64\RunTests.cmd C:\j\w\perf_windows_---356c2fc4\artifacts\bin\testhost/netcoreapp-Windows_NT-Release-x64/" exited with code 1. [C:\j\w\perf_windows_---356c2fc4\src\System.Net.Http\tests\Performance\System.Net.Http.PerformanceTests.csproj]
C:\j\w\perf_windows_---356c2fc4\.packages\microsoft.dotnet.corefxtesting\1.0.0-beta.19054.13\build\core\Core.targets(209,5): error : One or more tests failed while running tests from 'System.Net.Http.PerformanceTests'. [C:\j\w\perf_windows_---356c2fc4\src\System.Net.Http\tests\Performance\System.Net.Http.PerformanceTests.csproj]
C:\j\w\perf_windows_---356c2fc4\dir.traversal.targets(76,5): error : (No message specified) [C:\j\w\perf_windows_---356c2fc4\src\tests.builds]
```

_Originally posted by @v-haren in https://github.com/dotnet/corefx/issues/33622#issuecomment-452986425_

Full stack trace:

```
----- start 21:01:18.27 ===============  To repro directly: ===================================================== 
21:01:10   pushd C:\j\w\perf_windows_---356c2fc4\artifacts\bin\tests\System.Net.Http.PerformanceTests\netcoreapp-Windows_NT-Release-x64\
21:01:10   C:\j\w\perf_windows_---356c2fc4\artifacts\bin\testhost\netcoreapp-Windows_NT-Release-x64\dotnet.exe PerfRunner.exe --perf:runid Perf-Profile --perf:collect stopwatch 
21:01:10   if exist "Perf-Profile-System.Net.Http.PerformanceTests.xml" (
21:01:10   C:\Python35\python.exe "C:\j\w\perf_windows_---356c2fc4\artifacts\Microsoft.BenchView.JSONFormat\tools\measurement.py" xunit "Perf-Profile-System.Net.Http.PerformanceTests.xml" --better desc --drop-first-value --append -o "C:\j\w\perf_windows_---356c2fc4\measurement.json" 
21:01:10   )
21:01:10   popd
21:01:10   ===========================================================================================================
21:01:10   [1/9/2019 9:01:18 PM][INF] Running 8 [Benchmark]s
21:01:10   [1/9/2019 9:01:18 PM][INF]   System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(ssl: True, chunkedResponse: True, responseLength: 100000)
21:01:11   [1/9/2019 9:01:19 PM][ERR] System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(ssl: True, chunkedResponse: True, responseLength: 100000): The system cannot find the file specified.
21:01:11   [1/9/2019 9:01:19 PM][ERR]    at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 152
21:01:11      at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 88
21:01:11      at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 21
21:01:11      at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs:line 81
21:01:11      at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2.cs:line 64
21:01:11      at System.Net.Test.Common.Configuration.Certificates.GetCertificate(String certificateFileName) in C:\j\w\perf_windows_---356c2fc4\src\Common\tests\System\Net\Configuration.Certificates.cs:line 75
21:01:11      at System.Net.Test.Common.Configuration.Certificates.GetServerCertificate() in C:\j\w\perf_windows_---356c2fc4\src\Common\tests\System\Net\Configuration.Certificates.cs:line 38
21:01:11      at System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(Boolean ssl, Boolean chunkedResponse, Int32 responseLength) in C:\j\w\perf_windows_---356c2fc4\src\System.Net.Http\tests\Performance\Perf.SocketsHttpHandler.cs:line 33
21:01:11      at Microsoft.Xunit.Performance.BenchmarkTestInvoker.<>c__DisplayClass1_0.<<CallTestMethod>b__0>d.MoveNext()
21:01:11   --- End of stack trace from previous location where exception was thrown ---
21:01:11      at Microsoft.Xunit.Performance.Internal.BenchmarkIterator.RunAsync(Func`1 testMethod)
21:01:11      at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
21:01:11   --- End of stack trace from previous location where exception was thrown ---
21:01:11      at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
21:01:11      at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\projects\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
21:01:11   [1/9/2019 9:01:19 PM][INF]   System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(ssl: False, chunkedResponse: False, responseLength: 1)
21:01:11   [1/9/2019 9:01:19 PM][ERR] System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(ssl: False, chunkedResponse: False, responseLength: 1): The system cannot find the file specified.
21:01:11   [1/9/2019 9:01:19 PM][ERR]    at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 152
21:01:11      at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 88
21:01:11      at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 21
21:01:11      at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs:line 81
21:01:11      at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2.cs:line 64
21:01:11      at System.Net.Test.Common.Configuration.Certificates.GetCertificate(String certificateFileName) in C:\j\w\perf_windows_---356c2fc4\src\Common\tests\System\Net\Configuration.Certificates.cs:line 75
21:01:11      at System.Net.Test.Common.Configuration.Certificates.GetServerCertificate() in C:\j\w\perf_windows_---356c2fc4\src\Common\tests\System\Net\Configuration.Certificates.cs:line 38
21:01:11      at System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(Boolean ssl, Boolean chunkedResponse, Int32 responseLength) in C:\j\w\perf_windows_---356c2fc4\src\System.Net.Http\tests\Performance\Perf.SocketsHttpHandler.cs:line 33
21:01:11      at Microsoft.Xunit.Performance.BenchmarkTestInvoker.<>c__DisplayClass1_0.<<CallTestMethod>b__0>d.MoveNext()
21:01:11   --- End of stack trace from previous location where exception was thrown ---
21:01:11      at Microsoft.Xunit.Performance.Internal.BenchmarkIterator.RunAsync(Func`1 testMethod)
21:01:11      at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
21:01:11   --- End of stack trace from previous location where exception was thrown ---
21:01:11      at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
21:01:11      at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\projects\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
21:01:11   [1/9/2019 9:01:19 PM][INF]   System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(ssl: True, chunkedResponse: False, responseLength: 1)
21:01:11   [1/9/2019 9:01:19 PM][ERR] System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(ssl: True, chunkedResponse: False, responseLength: 1): The system cannot find the file specified.
21:01:11   [1/9/2019 9:01:19 PM][ERR]    at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 152
21:01:11      at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 88
21:01:11      at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 21
21:01:11      at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs:line 81
21:01:11      at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2.cs:line 64
21:01:11      at System.Net.Test.Common.Configuration.Certificates.GetCertificate(String certificateFileName) in C:\j\w\perf_windows_---356c2fc4\src\Common\tests\System\Net\Configuration.Certificates.cs:line 75
21:01:11      at System.Net.Test.Common.Configuration.Certificates.GetServerCertificate() in C:\j\w\perf_windows_---356c2fc4\src\Common\tests\System\Net\Configuration.Certificates.cs:line 38
21:01:11      at System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(Boolean ssl, Boolean chunkedResponse, Int32 responseLength) in C:\j\w\perf_windows_---356c2fc4\src\System.Net.Http\tests\Performance\Perf.SocketsHttpHandler.cs:line 33
21:01:11      at Microsoft.Xunit.Performance.BenchmarkTestInvoker.<>c__DisplayClass1_0.<<CallTestMethod>b__0>d.MoveNext()
21:01:11   --- End of stack trace from previous location where exception was thrown ---
21:01:11      at Microsoft.Xunit.Performance.Internal.BenchmarkIterator.RunAsync(Func`1 testMethod)
21:01:11      at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
21:01:11   --- End of stack trace from previous location where exception was thrown ---
21:01:11      at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
21:01:11      at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\projects\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
21:01:11   [1/9/2019 9:01:19 PM][INF]   System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(ssl: False, chunkedResponse: True, responseLength: 1)
21:01:11   [1/9/2019 9:01:19 PM][ERR] System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(ssl: False, chunkedResponse: True, responseLength: 1): The system cannot find the file specified.
21:01:11   [1/9/2019 9:01:19 PM][ERR]    at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 152
21:01:11      at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 88
21:01:11      at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 21
21:01:11      at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs:line 81
21:01:11      at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2.cs:line 64
21:01:11      at System.Net.Test.Common.Configuration.Certificates.GetCertificate(String certificateFileName) in C:\j\w\perf_windows_---356c2fc4\src\Common\tests\System\Net\Configuration.Certificates.cs:line 75
21:01:11      at System.Net.Test.Common.Configuration.Certificates.GetServerCertificate() in C:\j\w\perf_windows_---356c2fc4\src\Common\tests\System\Net\Configuration.Certificates.cs:line 38
21:01:11      at System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(Boolean ssl, Boolean chunkedResponse, Int32 responseLength) in C:\j\w\perf_windows_---356c2fc4\src\System.Net.Http\tests\Performance\Perf.SocketsHttpHandler.cs:line 33
21:01:11      at Microsoft.Xunit.Performance.BenchmarkTestInvoker.<>c__DisplayClass1_0.<<CallTestMethod>b__0>d.MoveNext()
21:01:11   --- End of stack trace from previous location where exception was thrown ---
21:01:11      at Microsoft.Xunit.Performance.Internal.BenchmarkIterator.RunAsync(Func`1 testMethod)
21:01:11      at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
21:01:11   --- End of stack trace from previous location where exception was thrown ---
21:01:11      at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
21:01:11      at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\projects\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
21:01:11   [1/9/2019 9:01:19 PM][INF]   System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(ssl: True, chunkedResponse: True, responseLength: 1)
21:01:11   [1/9/2019 9:01:19 PM][ERR] System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(ssl: True, chunkedResponse: True, responseLength: 1): The system cannot find the file specified.
21:01:11   [1/9/2019 9:01:19 PM][ERR]    at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 152
21:01:11      at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 88
21:01:11      at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 21
21:01:11      at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs:line 81
21:01:11      at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2.cs:line 64
21:01:11      at System.Net.Test.Common.Configuration.Certificates.GetCertificate(String certificateFileName) in C:\j\w\perf_windows_---356c2fc4\src\Common\tests\System\Net\Configuration.Certificates.cs:line 75
21:01:11      at System.Net.Test.Common.Configuration.Certificates.GetServerCertificate() in C:\j\w\perf_windows_---356c2fc4\src\Common\tests\System\Net\Configuration.Certificates.cs:line 38
21:01:11      at System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(Boolean ssl, Boolean chunkedResponse, Int32 responseLength) in C:\j\w\perf_windows_---356c2fc4\src\System.Net.Http\tests\Performance\Perf.SocketsHttpHandler.cs:line 33
21:01:11      at Microsoft.Xunit.Performance.BenchmarkTestInvoker.<>c__DisplayClass1_0.<<CallTestMethod>b__0>d.MoveNext()
21:01:11   --- End of stack trace from previous location where exception was thrown ---
21:01:11      at Microsoft.Xunit.Performance.Internal.BenchmarkIterator.RunAsync(Func`1 testMethod)
21:01:11      at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
21:01:11   --- End of stack trace from previous location where exception was thrown ---
21:01:11      at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
21:01:11      at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\projects\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
21:01:11   [1/9/2019 9:01:19 PM][INF]   System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(ssl: True, chunkedResponse: False, responseLength: 100000)
21:01:11   [1/9/2019 9:01:19 PM][ERR] System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(ssl: True, chunkedResponse: False, responseLength: 100000): The system cannot find the file specified.
21:01:11   [1/9/2019 9:01:19 PM][ERR]    at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 152
21:01:11      at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 88
21:01:11      at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 21
21:01:11      at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs:line 81
21:01:11      at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2.cs:line 64
21:01:11      at System.Net.Test.Common.Configuration.Certificates.GetCertificate(String certificateFileName) in C:\j\w\perf_windows_---356c2fc4\src\Common\tests\System\Net\Configuration.Certificates.cs:line 75
21:01:11      at System.Net.Test.Common.Configuration.Certificates.GetServerCertificate() in C:\j\w\perf_windows_---356c2fc4\src\Common\tests\System\Net\Configuration.Certificates.cs:line 38
21:01:11      at System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(Boolean ssl, Boolean chunkedResponse, Int32 responseLength) in C:\j\w\perf_windows_---356c2fc4\src\System.Net.Http\tests\Performance\Perf.SocketsHttpHandler.cs:line 33
21:01:11      at Microsoft.Xunit.Performance.BenchmarkTestInvoker.<>c__DisplayClass1_0.<<CallTestMethod>b__0>d.MoveNext()
21:01:11   --- End of stack trace from previous location where exception was thrown ---
21:01:11      at Microsoft.Xunit.Performance.Internal.BenchmarkIterator.RunAsync(Func`1 testMethod)
21:01:11      at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
21:01:11   --- End of stack trace from previous location where exception was thrown ---
21:01:11      at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
21:01:11      at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\projects\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
21:01:11   [1/9/2019 9:01:19 PM][INF]   System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(ssl: False, chunkedResponse: False, responseLength: 100000)
21:01:11   [1/9/2019 9:01:19 PM][ERR] System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(ssl: False, chunkedResponse: False, responseLength: 100000): The system cannot find the file specified.
21:01:11   [1/9/2019 9:01:19 PM][ERR]    at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 152
21:01:11      at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 88
21:01:11      at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs:line 21
21:01:11      at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs:line 81
21:01:11      at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags) in C:\j\w\perf_windows_---356c2fc4\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2.cs:line 64
21:01:11      at System.Net.Test.Common.Configuration.Certificates.GetCertificate(String certificateFileName) in C:\j\w\perf_windows_---356c2fc4\src\Common\tests\System\Net\Configuration.Certificates.cs:line 75
21:01:11      at System.Net.Test.Common.Configuration.Certificates.GetServerCertificate() in C:\j\w\perf_windows_---356c2fc4\src\Common\tests\System\Net\Configuration.Certificates.cs:line 38
21:01:11      at System.Net.Http.Tests.SocketsHttpHandlerPerfTest.Get(Boolean ssl, Boolean chunkedResponse, Int32 responseLength) in C:\j\w\perf_windows_---356c2fc4\src\System.Net.Http\tests\Performance\Perf.SocketsHttpHandler.cs:line 33
21:01:11      at Microsoft.Xunit.Performance.BenchmarkTestInvoker.<>c__DisplayClass1_0.<<CallTestMethod>b__0>d.MoveNext()
21:01:11   --- End of stack trace from previous location where exception was thrown ---
21:01:11      at Microsoft.Xunit.Performance.Internal.BenchmarkIterator.RunAsync(Func`1 testMethod)
21:01:11      at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
21:01:11   --- End of stack trace from previous location where exception was thrown ---
21:01:11      at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
21:01:11      at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\projects\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
```

**Comment by davidsh** [comment]
Performance tests have been moved to the [dotnet/performance](https://github.com/dotnet/performance) repo.
