### ISSUE TITLE
Test " System.ServiceProcess.Tests.ServiceBaseTests.LogWritten " failed in netfx-Windows_NT-Release-x64-Windows.10.Amd64.ClientRS4

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#34542]
**Job name:**
netfx-Windows_NT-Release-x64-Windows.10.Amd64.ClientRS4
**Failed test:**
System.ServiceProcess.Tests.ServiceBaseTests.LogWritten

Error message:
```
System.InvalidOperationException : Cannot start service 64e80cf8-de85-41eb-a01f-84ebaafcd499.Dependent on computer '.'.\r\n---- System.ComponentModel.Win32Exception : The service did not respond to the start or control request in a timely fashion
```
Stack trace:
```
at System.ServiceProcess.ServiceController.Start(String[] args)
   at System.ServiceProcess.Tests.TestServiceInstaller.Install() in F:\vsagent\-containerSas\52\s\src\System.ServiceProcess.ServiceController\tests\System.ServiceProcess.ServiceController.TestService\TestServiceInstaller.cs:line 106
   at System.ServiceProcess.Tests.TestServiceProvider..ctor() in F:\vsagent\-containerSas\52\s\src\System.ServiceProcess.ServiceController\tests\TestServiceProvider.cs:line 62
   at System.ServiceProcess.Tests.ServiceBaseTests..ctor() in F:\vsagent\-containerSas\52\s\src\System.ServiceProcess.ServiceController\tests\ServiceBaseTests.cs:line 27
----- Inner Stack Trace -----
```

Details:
https://dnceng.visualstudio.com/internal/_build/results?buildId=70436&view=ms.vss-test-web.test-result-details

**Comment by danmosemsft** [comment]
This is missing my change
96a13e8f Disable TestService tests on NETFX (#34365)
it appears to be not running against master, but against 
070b554c Consume core-setup using darc
which is older?

@AriNuer please only look at runs against the master branch. The branch is in the right hand column if you are looking Azure DevOps.

cc @safern
