### ISSUE TITLE
SqlClient gives wrong error with incorrect SQL Server credentials

### ISSUE THREAD

**Issue by albahari** [dotnet/corefx#34569]
Microsoft Windows [Version 10.0.17763.253]
Microsoft.NETCore.App 3.0.0-preview1-26929-01

To reproduce:

1. In SQL Server 2017, create a new SQL Server login with SQL Server authentication. Set the username to 'test' and the password to 'foo'. Leave the checkbox "User must change password at next login" ticked. (Note that the bug still occurs without that checkbox ticked, but the consequences are not as severe).

2. Create a .NET Core Console app that references nuget:System.Data.SqlClient and paste in the following code:

```
static void Main (string[] args)
{
    TestSql ();    // Fails - gives wrong error
    // Try again 6 seconds later
    Thread.Sleep (6000);
    TestSql ();   // Now it works correctly
}

static void TestSql()
{
    var cx = new SqlConnection ("Data Source=.;User ID=test;Password=foo");
    try
    {
        cx.Open ();
    }
    catch (SqlException ex)
    {
        Console.WriteLine (ex.Number);
        Console.WriteLine (ex.Message);
    }
}
```

Expected result:
```
18456
Login failed for user 'test'.

18456
Login failed for user 'test'.
```

Actual result:
```
233
A connection was successfully established with the server, but then an error occurred during the login process. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.)

18456
Login failed for user 'test'.
```

It's a bit of a showstopper if you're trying to catch the scenario of a user's login expiring, so you can prompt the user to change their password. The problem does not occur with .NET Framework. 

Here's the stack trace for the first exception:
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()

**Comment by v-shizha** [comment]
Issue is reproducible, we are currently looking into it.  :)
