### ISSUE TITLE
System.Threading.Tests.MutexTests tests failing on Linux

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#34666]
From https://github.com/dotnet/corefx/pull/34500

Debian.8.Amd64.Open-x64-Release
https://mc.dot.net/#/user/tkp1n/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/ecffe5046608086201c8716ae132ddacbd7182d8/workItem/System.Threading.Tests/analysis/xunit/System.Threading.Tests.MutexTests~2FCrossProcess_NamedMutex_ProtectedFileAccessAtomic(prefix:%20%5C%225e65042415ce448f872dae5fb40e7a74%5C%22)

 System.Threading.Tests.MutexTests/CrossProcess_NamedMutex_ProtectedFileAccessAtomic(prefix: \"5e65042415ce448f872dae5fb40e7a74\")

```text
Message :
Assert.True() Failure
Expected: True
Actual:   False
Stack Trace :
   at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass4_0.<CreateGuardedThread>b__2() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Threading/ThreadTestHelpers.cs:line 56
   at System.Threading.Tests.ThreadTestHelpers.RunTestInBackgroundThread(Action test) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Threading/ThreadTestHelpers.cs:line 108
   at System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic(String prefix) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Threading/tests/MutexTests.cs:line 262
```

Debian.8.Amd64.Open-x64-Release
https://mc.dot.net/#/user/tkp1n/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/ecffe5046608086201c8716ae132ddacbd7182d8/workItem/System.Threading.Tests/analysis/xunit/System.Threading.Tests.MutexTests~2FCrossProcess_NamedMutex_ProtectedFileAccessAtomic(prefix:%20%5C%22Local%5C%5C%5C%5C65f91a48792b41ba9b7e699108f7de52%5C%22)

 System.Threading.Tests.MutexTests/CrossProcess_NamedMutex_ProtectedFileAccessAtomic(prefix: \"Local\\\\65f91a48792b41ba9b7e699108f7de52\")

```text
Message :
System.AggregateException : One or more errors occurred. (Assert.True() Failure
Expected: True
Actual:   False)
---- Assert.True() Failure
Expected: True
Actual:   False
Stack Trace :
   at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass4_0.<CreateGuardedThread>b__1() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Threading/ThreadTestHelpers.cs:line 51
   at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass4_0.<CreateGuardedThread>b__2() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Threading/ThreadTestHelpers.cs:line 57
   at System.Threading.Tests.ThreadTestHelpers.RunTestInBackgroundThread(Action test) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Threading/ThreadTestHelpers.cs:line 108
   at System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic(String prefix) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Threading/tests/MutexTests.cs:line 262
----- Inner Stack Trace -----
   at System.Threading.Tests.ThreadTestHelpers.CheckedWait(WaitHandle wh) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Threading/ThreadTestHelpers.cs:line 133
   at System.Threading.Tests.MutexTests.IncrementValueInFileNTimes(Mutex mutex, String fileName, Int32 n) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Threading/tests/MutexTests.cs:line 268
   at System.Threading.Tests.MutexTests.<>c__DisplayClass15_0.<CrossProcess_NamedMutex_ProtectedFileAccessAtomic>b__0() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Threading/tests/MutexTests.cs:line 257
   at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass4_0.<CreateGuardedThread>b__0() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Threading/ThreadTestHelpers.cs:line 35
```

cc @kouvel

**Comment by ViktorHofer** [comment]
Happened again: https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190529.66/workItem/System.Threading.Tests/analysis/xunit/System.Threading.Tests.MutexTests~2FCrossProcess_NamedMutex_ProtectedFileAccessAtomic(prefix:%20%5C%22f66454e1782b48a3861d01e14c9e4330%5C%22)

cc @stephentoub

**Comment by stephentoub** [comment]
Again:
```
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.PostAsyncExpect100Continue_NonSuccessResponse_RequestBodyNotSent [FAIL]
      Assert.Null() Failure
      Expected: (null)
      Actual:   Byte[] [42, 42, 42, 42, 42, ...]
      Stack Trace:
        /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs(1926,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<>c__DisplayClass67_0.<<PostAsyncExpect100Continue_NonSuccessResponse_RequestBodyNotSent>b__1>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(83,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(111,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(71,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs(186,0): at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Int32 timeout)
        /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs(1898,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.PostAsyncExpect100Continue_NonSuccessResponse_RequestBodyNotSent()
        --- End of stack trace from previous location where exception was thrown ---
```

**Comment by stephentoub** [comment]
Again here:
https://helix.dot.net/api/2019-06-17/jobs/7bba480c-c69f-451e-82a8-6e837811c2b6/workitems/System.Threading.Tests/console
