### ISSUE TITLE
EndPrint_SetValue_ReturnsExpected failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#34676]
```
Unhandled Exception of Type System.Drawing.Printing.InvalidPrinterException
Message :
System.Drawing.Printing.InvalidPrinterException : No printers are installed.
Stack Trace :
   at System.Drawing.Printing.PrinterSettings.GetHdevmodeInternal(String printer) in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PrinterSettings.Windows.cs:line 881
   at System.Drawing.Printing.PrinterSettings.GetHdevmodeInternal() in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PrinterSettings.Windows.cs:line 872
   at System.Drawing.Printing.PageSettings.get_ExtraBytes() in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PageSettings.Windows.cs:line 384
   at System.Drawing.Printing.PageSettings.CopyToHdevmode(IntPtr hdevmode) in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PageSettings.Windows.cs:line 368
   at System.Drawing.Printing.PrinterSettings.GetHdevmode(PageSettings pageSettings) in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PrinterSettings.Windows.cs:line 955
   at System.Drawing.Printing.PrintController.OnStartPrint(PrintDocument document, PrintEventArgs e) in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PrintController.Windows.cs:line 275
   at System.Drawing.Printing.Tests.PrintDocumentTests.TestPrintController.OnStartPrint(PrintDocument document, PrintEventArgs e) in D:\a\1\s\src\System.Drawing.Common\tests\Printing\PrintDocumentTests.cs:line 274
   at System.Drawing.Printing.PrintController.Print(PrintDocument document) in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PrintController.Windows.cs:line 116
   at System.Drawing.Printing.PrintDocument.Print() in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PrintDocument.Windows.cs:line 270
   at System.Drawing.Printing.Tests.PrintDocumentTests.EndPrint_SetValue_ReturnsExpected() in D:\a\1\s\src\System.Drawing.Common\tests\Printing\PrintDocumentTests.cs:line 187
```
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F34660~2Fmerge/test~2Ffunctional~2Fcli~2F/20190118.1/workItem/System.Drawing.Common.Tests/analysis/xunit/System.Drawing.Printing.Tests.PrintDocumentTests~2FEndPrint_SetValue_ReturnsExpected

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/31221 again and https://github.com/dotnet/corefx/issues/23001

Since `PrinterSettings.InstalledPrinters.Count > 0` is not telling us the truth, I am not sure what to do. It can affect any number of tests. I would rather not simply disable them. Presumably ignoring InvalidPrinterException  defeats the purpose.

There are 22 tests that rely on printers.

@safern any idea how these machines even report printers - maybe the print to XPS or something?

I don't have a better idea than disable the tests, if we change this product code we have to run them man ually.

**Comment by ahsonkhan** [comment]
Failed again in https://github.com/dotnet/corefx/pull/37712

System.Drawing.Printing.Tests.PrintDocumentTests/PrintPage_SetValue_ReturnsExpected
Windows.10.Amd64.ClientRS4.ES.Open-x86-Release
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F37712~2Fmerge/test~2Ffunctional~2Fcli~2F/20190516.21/workItem/System.Drawing.Common.Tests/analysis/xunit/System.Drawing.Printing.Tests.PrintDocumentTests~2FPrintPage_SetValue_ReturnsExpected
```text
Message :
System.Drawing.Printing.InvalidPrinterException : No printers are installed.
Stack Trace :
   at System.Drawing.Printing.PrinterSettings.GetHdevmodeInternal(String printer) in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PrinterSettings.Windows.cs:line 881
   at System.Drawing.Printing.PrintController.OnStartPrint(PrintDocument document, PrintEventArgs e) in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PrintController.Windows.cs:line 275
   at System.Drawing.Printing.Tests.PrintDocumentTests.TestPrintController.OnStartPrint(PrintDocument document, PrintEventArgs e) in D:\a\1\s\src\System.Drawing.Common\tests\Printing\PrintDocumentTests.cs:line 275
   at System.Drawing.Printing.PrintController.Print(PrintDocument document) in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PrintController.Windows.cs:line 116
   at System.Drawing.Printing.Tests.PrintDocumentTests.PrintPage_SetValue_ReturnsExpected() in D:\a\1\s\src\System.Drawing.Common\tests\Printing\PrintDocumentTests.cs:line 209
```
