### ISSUE TITLE
ObjectDisposedException at System.Net.Security.SslState.ThrowIfExceptional() on .NET Core on Linux

### ISSUE THREAD

**Issue by amanbha** [dotnet/corefx#34746]
Unhandled Exception:
Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
at System.Net.Security.SslState.ThrowIfExceptional()
at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory1 buffer) at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest) at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState) at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result) at System.Net.LazyAsyncResult.Complete(IntPtr userToken) at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken) at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e) at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location where exception was thrown --- at System.Threading.ThreadPoolWorkQueue.Dispatch()System.ObjectDisposedException: Cannot access a disposed object. Object name: 'SslStream'. at System.Net.Security.SslState.ThrowIfExceptional() at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck) at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory1 buffer)
at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)

Reported here https://github.com/Microsoft/service-fabric-client-dotnet/issues/54

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/34033?

**Comment by davidsh** [comment]
Looks like the original bug () is based on .NET Core 2.1:
https://github.com/Microsoft/service-fabric-client-dotnet/issues/54

>When calling the UploadApplicationPackageAsync on Linux using .NET Core 2.1, I get:

So, I suspect this is a duplicate of #34033.  That bug is fixed in current master (3.0 branch).

**Comment by karelz** [comment]
Duplicate of #34033
