### ISSUE TITLE
HttpClient socket file descriptor leak 

### ISSUE THREAD

**Issue by wingrime** [dotnet/corefx#34804]
After days of work, on linux server dotnet process had ~16000 open TCP socket file descriptors (not open/established connections). After restart count slowly increments

This count does not hit process open descriptior limit, and does not hit ephemeral ports count (~32000).

Another indication of issue presence, frequent exception:
```
System.Net.Http.HttpRequestException: Cannot assign requested address
 ---> System.Net.Sockets.SocketException: Cannot assign requested address
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at offset 12
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) at offset 46
at System.Net.Http.ConnectHelper.<ConnectAsync>d__2.MoveNext() at offset 272
```
 
Same code deployed on WinServer+IIS seems does not give such exception

**UPDATE 1: Test Program**
```
using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace DoLeak
{
    class Program
    {
        static void Main(string[] args)
        {
            TestRun();
            Console.WriteLine("Done");
            Console.ReadKey();

        }

        private static void TestRun()
        {
            var httpClient = new HttpClient();

            //404 with body 
            //my server returns standard nginx 404 error page
            var url = "http://v.wingrime.cc/not";

            for (int i = 0; i < 33000; i++)
            {
                Console.WriteLine($"N = {i}");
                DoRequest(httpClient, url).Wait();
            }
        }

        private static async Task DoRequest(HttpClient httpClient, string url)
        {
            var request = new HttpRequestMessage(HttpMethod.Get, url);
            using (request)
            {
                await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead);
            }
           
        }
    }
}
```
Tested in docker using `microsoft/dotnet:2.2-aspnetcore-runtime` base image 
```
FROM microsoft/dotnet:2.2-sdk AS build-env

COPY . /DoLeak

WORKDIR /DoLeak

RUN dotnet restore -s https://api.nuget.org/v3/index.json 
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:2.2-aspnetcore-runtime
WORKDIR /DoLeak
COPY --from=build-env DoLeak/out .

ENTRYPOINT ["dotnet", "DoLeak.dll"]
```
Stable gives exception after 14116 success requests

```
...
N = 14113
N = 14114
N = 14115
N = 14116

Unhandled Exception: System.AggregateException: One or more errors occurred. (Cannot assign requested address) ---> System.Net.Http.HttpRequestException: Cannot assign requested address ---> System.Net.Sockets.SocketException: Cannot assign requested address
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at DoLeak.Program.DoRequest(HttpClient httpClient, String url) in /DoLeak/Program.cs:line 38
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at DoLeak.Program.TestRun() in /DoLeak/Program.cs:line 26
   at DoLeak.Program.Main(String[] args) in /DoLeak/Program.cs:line 12
```
- Runing this code on Windows does not give any error
- Removing  `async Task` make code works flawlessly
- Presence of `using` with `HttpRequestMessage` seems does not change anything
- 404 without body does not give error

os
```
CentOS 7
Linux  3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
Leak can be seen with `lsof`
```
# lsof  -p <dotnet PID> -a -f | grep TCP | wc -l
14116
```
witch means 14116 open socket file descriptiors not released

**Comment by davidsh** [comment]
Can you post a sample application that reproduces this problem?  We need a repro in order to diagnose.

**Comment by wingrime** [comment]
Updated

**Comment by stephentoub** [comment]
> await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead)

This is likely the problem.  This is asking HttpClient to return to you the response message having only read the response headers and not the response body, so it's giving back to you a response that's holding open a connection and everything along with it, expecting you to consume the remainder of the data.  Since you're not, and since you're not disposing of it, the only way it'll get cleaned up is eventually when everything becomes finalizable.

Try disposing the response message this returns.

**Comment by wingrime** [comment]
thanks! seems helps

I am not expected so much different behavior
Behavior is different between OSes
