### ISSUE TITLE
Play_InvalidFile_ThrowsInvalidOperationException throwing web exception for URL

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#34849]
See https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F34786~2Fmerge/test~2Ffunctional~2Fcli~2F/20190124.33/workItem/System.Windows.Extensions.Tests/analysis/xunit/System.Media.Test.SoundPlayerTests~2FPlay_InvalidFile_ThrowsInvalidOperationException(sourceLocation:%20%5C%22http:~2F~2Fgoogle.com%5C%22)

```
Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   typeof(System.Net.WebException): The operation has timed out.
---- System.Net.WebException : The operation has timed out.
Stack Trace :
   at System.Net.HttpWebRequest.GetResponse() in D:\a\1\s\src\System.Net.Requests\src\System\Net\HttpWebRequest.cs:line 1009
   at System.Media.SoundPlayer.LoadSync() in D:\a\1\s\src\System.Windows.Extensions\src\System\Media\SoundPlayer.cs:line 258
   at System.Media.SoundPlayer.LoadAndPlay(Int32 flags) in D:\a\1\s\src\System.Windows.Extensions\src\System\Media\SoundPlayer.cs:line 227
   at System.Media.SoundPlayer.Play() in D:\a\1\s\src\System.Windows.Extensions\src\System\Media\SoundPlayer.cs:line 318
   at System.Media.Test.SoundPlayerTests.<>c__DisplayClass17_0.<Play_InvalidFile_ThrowsInvalidOperationException>b__0() in D:\a\1\s\src\System.Windows.Extensions\tests\System\Media\SoundPlayerTests.cs:line 209
----- Inner Stack Trace -----
   at System.Net.HttpWebRequest.GetResponse() in D:\a\1\s\src\System.Net.Requests\src\System\Net\HttpWebRequest.cs:line 1009
   at System.Media.SoundPlayer.LoadSync() in D:\a\1\s\src\System.Windows.Extensions\src\System\Media\SoundPlayer.cs:line 258
   at System.Media.SoundPlayer.LoadAndPlay(Int32 flags) in D:\a\1\s\src\System.Windows.Extensions\src\System\Media\SoundPlayer.cs:line 227
   at System.Media.SoundPlayer.Play() in D:\a\1\s\src\System.Windows.Extensions\src\System\Media\SoundPlayer.cs:line 318
   at System.Media.Test.SoundPlayerTests.<>c__DisplayClass17_0.<Play_InvalidFile_ThrowsInvalidOperationException>b__0() in D:\a\1\s\src\System.Windows.Extensions\tests\System\Media\SoundPlayerTests.cs:line 209
```

We don't need to test the web here, can this be a local invalid sound file?

**Comment by maryamariyan** [comment]
Looking.

cc: @stephentoub
