### ISSUE TITLE
Some asserts during X-Plat Sockets Tests

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#3484]
See: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst/1021/console. The Debug.Assert here did not cause the test to fail.

```
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
SafeCloseSocket::ReleaseHandle(handle:0)
---- Assert Long Message ----
ReleaseHandle failed.
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at System.Diagnostics.Debug.Fail(String message, String detailMessage)
   at System.Net.GlobalLog.Assert(String message, String detailMessage)
   at System.Net.GlobalLog.Assert(Boolean condition, String messageFormat, Object[] data)
   at System.Net.Sockets.SafeCloseSocket.InnerSafeCloseSocket.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.DangerousRelease()
   at System.Net.Sockets.SafeCloseSocket.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
   at System.Runtime.InteropServices.SafeHandle.Finalize()
   at System.Net.DebugSafeHandleMinusOneIsInvalid.Finalize()
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
SafeCloseSocket::ReleaseHandle(handle:0)
---- Assert Long Message ----
ReleaseHandle failed.
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at System.Diagnostics.Debug.Fail(String message, String detailMessage)
   at System.Net.GlobalLog.Assert(String message, String detailMessage)
   at System.Net.GlobalLog.Assert(Boolean condition, String messageFormat, Object[] data)
   at System.Net.Sockets.SafeCloseSocket.InnerSafeCloseSocket.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.DangerousRelease()
   at System.Net.Sockets.SafeCloseSocket.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
   at System.Runtime.InteropServices.SafeHandle.Finalize()
   at System.Net.DebugSafeHandleMinusOneIsInvalid.Finalize()
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
SafeCloseSocket::ReleaseHandle(handle:0)
---- Assert Long Message ----
ReleaseHandle failed.
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at System.Diagnostics.Debug.Fail(String message, String detailMessage)
   at System.Net.GlobalLog.Assert(String message, String detailMessage)
   at System.Net.GlobalLog.Assert(Boolean condition, String messageFormat, Object[] data)
   at System.Net.Sockets.SafeCloseSocket.InnerSafeCloseSocket.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.DangerousRelease()
   at System.Net.Sockets.SafeCloseSocket.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
   at System.Runtime.InteropServices.SafeHandle.Finalize()
   at System.Net.DebugSafeHandleMinusOneIsInvalid.Finalize()
Finished:    System.Net.Sockets.APMServer.Tests

=== TEST EXECUTION SUMMARY ===
   System.Net.Sockets.APMServer.Tests  Total: 231, Errors: 0, Failed: 0, Skipped: 0, Time: 13.856s
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
SafeCloseSocket::ReleaseHandle(handle:0)
---- Assert Long Message ----
ReleaseHandle failed.
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at System.Diagnostics.Debug.Fail(String message, String detailMessage)
   at System.Net.GlobalLog.Assert(String message, String detailMessage)
   at System.Net.GlobalLog.Assert(Boolean condition, String messageFormat, Object[] data)
   at System.Net.Sockets.SafeCloseSocket.InnerSafeCloseSocket.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.DangerousRelease()
   at System.Net.Sockets.SafeCloseSocket.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
   at System.Runtime.InteropServices.SafeHandle.Finalize()
   at System.Net.DebugSafeHandleMinusOneIsInvalid.Finalize()
Finished:    System.Net.Sockets.AsyncServer.Tests

=== TEST EXECUTION SUMMARY ===
   System.Net.Sockets.AsyncServer.Tests  Total: 231, Errors: 0, Failed: 0, Skipped: 0, Time: 13.955s
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
SafeCloseSocket::ReleaseHandle(handle:0)
---- Assert Long Message ----
ReleaseHandle failed.
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at System.Diagnostics.Debug.Fail(String message, String detailMessage)
   at System.Net.GlobalLog.Assert(String message, String detailMessage)
   at System.Net.GlobalLog.Assert(Boolean condition, String messageFormat, Object[] data)
   at System.Net.Sockets.SafeCloseSocket.InnerSafeCloseSocket.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.DangerousRelease()
   at System.Net.Sockets.SafeCloseSocket.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
   at System.Runtime.InteropServices.SafeHandle.Finalize()
   at System.Net.DebugSafeHandleMinusOneIsInvalid.Finalize()
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
SafeCloseSocket::ReleaseHandle(handle:0)
---- Assert Long Message ----
ReleaseHandle failed.
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at System.Diagnostics.Debug.Fail(String message, String detailMessage)
   at System.Net.GlobalLog.Assert(String message, String detailMessage)
   at System.Net.GlobalLog.Assert(Boolean condition, String messageFormat, Object[] data)
   at System.Net.Sockets.SafeCloseSocket.InnerSafeCloseSocket.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.DangerousRelease()
   at System.Net.Sockets.SafeCloseSocket.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
   at System.Runtime.InteropServices.SafeHandle.Finalize()
   at System.Net.DebugSafeHandleMinusOneIsInvalid.Finalize()
```

**Comment by pgavlin** [comment]
These have been fixed.
