### ISSUE TITLE
Deserializing System.Security.Claims.Claim throws System.IO.EndOfStreamException

### ISSUE THREAD

**Issue by jannikbuschke** [dotnet/corefx#34840]
### problem description
Using **net461** the following code throws `System.IO.EndOfStreamException: 'Unable to read beyond the end of the stream.'` when **deserializing a Claim**. I think this is a bug.

```c#
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        [HttpGet]
        public ActionResult<object> Get()
        {

            foreach (var claim in User.Claims)
            {
                var memoryStream = new MemoryStream();
                var binaryWriter = new BinaryWriter(memoryStream, Encoding.UTF8, true);

                claim.WriteTo(binaryWriter);

                var deserializationStream = new MemoryStream(memoryStream.ToArray());
                
                // next line executes once and then throws in the second loop iteration
                new Claim(new BinaryReader(deserializationStream, Encoding.UTF8) );
            }

            return null;
        }
    }

```

Details
```

System.IO.EndOfStreamException
  HResult=0x80070026
  Message=Unable to read beyond the end of the stream.
  Source=System.Private.CoreLib
  StackTrace:
   at System.IO.MemoryStream.InternalReadInt32()
   at System.Security.Claims.Claim..ctor(BinaryReader reader, ClaimsIdentity subject)
   at System.Security.Claims.Claim..ctor(BinaryReader reader)
   at WebApplication3.ValuesController.Get() in C:\Users\jbuschke\source\repos\WebApplication3\WebApplication3\Startup.cs:line 31
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()


```

### related

#22818
https://developercommunity.visualstudio.com/content/problem/236195/claimsprincipal-deserialization-fails-on-net-frame.html

### to reproduce
**used VS 2017 api project with windows authentication on**
csproj:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
		<TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore" Version="2.1.6" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.3" />
  </ItemGroup>

</Project>

```

```c#
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using System.IO;
using System.Security.Claims;
using System.Text;

namespace WebApplication3
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        [HttpGet]
        public ActionResult<object> Get()
        {
            foreach (var claim in User.Claims)
            {
                var memoryStream = new MemoryStream();
                var binaryWriter = new BinaryWriter(memoryStream, Encoding.UTF8, true);

                claim.WriteTo(binaryWriter);

                var deserializationStream = new MemoryStream(memoryStream.ToArray());

                // next line throws executes once and then throws
                new Claim(new BinaryReader(deserializationStream, Encoding.UTF8));
            }

            return null;
        }
    }

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseMvc();
        }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            WebHost.CreateDefaultBuilder(args).UseStartup<Startup>().Build().Run();
        }
    }
}

```

**Comment by jannikbuschke** [comment]
I tried to isolate the issue further. Following examples works only if line 2 is commented. Uncommenting yields above mentioned Exception when deserializing. So having a Properties.Count > 0 causes issues.

```
                var claim = new Claim("test", "test");
                // claim.Properties.Add(new KeyValuePair<string, string>("asd", "asd"));
                var memoryStream = new MemoryStream();
                var binaryWriter = new BinaryWriter(memoryStream, Encoding.UTF8, true);
                claim.WriteTo(binaryWriter);
                var deserializationStream = new MemoryStream(memoryStream.ToArray());
                new Claim(new BinaryReader(deserializationStream, Encoding.UTF8));
```

**Comment by colathro** [comment]
Ahhh, I believe I'm understanding where the confusion is. .Net Core 2.1 and .Net Framework 4.6.2 are almost on identical .Net Standard Verisons: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

This means the Objects and Methods would generally be identical between the versions; but the actual foundation libraries will be different. I believe this bug was fixed a couple years ago in .Net Core 2.1 here: https://github.com/dotnet/corefx/commit/462da72b8409cd2ef8f6915ed92795231e8d0b95#diff-b47a74e2c06e04fe69c6278f5a178561

.Net Framework doesn't share this source, so this fix wouldn't have been introduced to Framework 4.6.2, and I was actually able to reproduce it all the way up to 4.7.2.

For .Net Framework I believe you'll have the ability to create this same type of issue report within: https://developercommunity.visualstudio.com/spaces/61/index.html

**Comment by karelz** [comment]
cc @ViktorHofer

**Comment by ViktorHofer** [comment]
Right I fixed that for netcoreapp2.1 upwards here: https://github.com/dotnet/corefx/commit/462da72b8409cd2ef8f6915ed92795231e8d0b95#diff-b47a74e2c06e04fe69c6278f5a178561. We have an internal issue tracking the port to .NET Framework (602744). Closing.
