### ISSUE TITLE
Lots of DateTime tests failing on Ubuntu ARM64 due to missing London timezone

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#34851]
All the ones I looked at seem the same.

https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190125.1/workItem/System.Runtime.Tests
```c#
        private static string s_strGMT = s_isWindows ? "GMT Standard Time" : "Europe/London";
...
        private static TimeZoneInfo s_GMTLondon = TimeZoneInfo.FindSystemTimeZoneById(s_strGMT);`

```
Ubuntu.1804.Arm64-arm64-Release
Get Repro environment
```
Unhandled Exception of Type System.TypeInitializationException
Message :
System.TypeInitializationException : The type initializer for 'System.Tests.TimeZoneInfoTests' threw an exception.
---- System.TimeZoneNotFoundException : The time zone ID 'Europe/London' was not found on the local computer.
-------- System.IO.DirectoryNotFoundException : Could not find a part of the path '/usr/share/zoneinfo/Europe/London'.
Stack Trace :
   at System.Tests.TimeZoneInfoTests.ConvertTime_DateTime_MiscUtc() in /__w/1/s/src/System.Runtime/tests/System/TimeZoneInfoTests.cs:line 836
----- Inner Stack Trace -----
   at System.TimeZoneInfo.FindSystemTimeZoneById(String id) in /__w/3/s/src/System.Private.CoreLib/shared/System/TimeZoneInfo.Unix.cs:line 724
   at System.Tests.TimeZoneInfoTests..cctor() in /__w/1/s/src/System.Runtime/tests/System/TimeZoneInfoTests.cs:line 42
----- Inner Stack Trace -----
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter) in /__w/3/s/src/System.Private.CoreLib/shared/Interop/Unix/Interop.IOErrors.cs:line 23
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode) in /__w/3/s/src/System.Private.CoreLib/shared/Microsoft/Win32/SafeHandles/SafeFileHandle.Unix.cs:line 39
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options) in /__w/3/s/src/System.Private.CoreLib/shared/System/IO/FileStream.Unix.cs:line 61
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) in /__w/3/s/src/System.Private.CoreLib/shared/System/IO/FileStream.cs:line 229
   at Internal.IO.File.ReadAllBytes(String path) in /__w/3/s/src/System.Private.CoreLib/shared/Internal/IO/File.cs:line 56
   at System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine(String id, TimeZoneInfo& value, Exception& e) in /__w/3/s/src/System.Private.CoreLib/shared/System/TimeZoneInfo.Unix.cs:line 215
```

@joperezr I think you own S.Runtime

**Comment by safern** [comment]
I will change official builds to run tests in Ubuntu16.04 either, because we're building in 16.04 and running in 18.04 and that causes some dependency issues because the build is not fully portable. After I update official build to run tests in 1604, we should see if tests keep failing.

**Comment by danmosemsft** [comment]
They're still failing this way. If we can fix this then System.Runtime.Tests will 100% pass. If you can dump that folder maybe I/we can figure out how to fix them

https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190130.2/workItem/System.Runtime.Tests/analysis/xunit/System.Tests.TimeZoneInfoTests~2FNewfoundlandTimeZone(dateTimeString:%20%5C%222015-03-08T01:59:59%5C%22,%20expectedDST:%20False,%20isInvalidTime:%20False,%20isAmbiguousTime:%20)

**Comment by ulisesh** [comment]
This has been fixed for Ubuntu 16.04 queue

**Comment by safern** [comment]
@ulisesh could you close this whenever it is done for 1804 as well and other ARM queues?

**Comment by safern** [comment]
@ulisesh what is the status of all ARM queues having `tzdata`?

**Comment by wfurt** [comment]
I don't see any more failures. Closing for now.
