### ISSUE TITLE
using reflection to get value of static field fails:

### ISSUE THREAD

**Issue by kennywangjin** [dotnet/corefx#3489]
while using reflection to get the value of static field:

fieldInfo.GetValue(null)

It always fails because of the null parameter.
Problem is that this field is static. In previous .net, it worked well, no instance was required for static memebers. Why has it different behavior now? Is it by design?

**Comment by svick** [comment]
Looking at [the source for `RtFieldInfo`](https://github.com/dotnet/coreclr/blob/4cf8a6b082d9bb1789facd996d8265d3908757b2/src/mscorlib/src/System/Reflection/FieldInfo.cs), I don't see any null checks.

Are you sure that it's not the `fieldInfo` that's `null`? Could you post full stack trace?

**Comment by nguerrera** [comment]
@svick is right -- this should not be the case. Full repro steps and/or full stack trace would definitely help.

**Comment by kennywangjin** [comment]
I am using fieldInfo.GetValue(null) to get enum member's value (I want to enumerate all the declared memebers in the enum):

here is the code:
enumType.GetTypeInfo().DeclaredFields.Select(item => new SelectListItem
            {
                Value = item.GetValue(null).ToString(),
                Text = item.Name
            });

errorinfo: {"Non-static field requires a target."}

stacktrace:
   at System.Reflection.RtFieldInfo.CheckConsistency(Object target)
   at System.Reflection.RtFieldInfo.InternalGetValue(Object obj, StackCrawlMark& stackMark)
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at WebApp.TagHelpers.EnumSelectTagHelper.<>c.<GetEnumSelections>b__20_0(FieldInfo item) in C:\Users\kenny\documents\visual studio 2015\Projects\OfficeAutomation\src\WebApp\TagHelpers\EnumSelectTagHelper.cs:line 67
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at Microsoft.AspNet.Mvc.Rendering.DefaultHtmlGenerator.UpdateSelectListItemsWithDefaultValue(ModelExplorer modelExplorer, IEnumerable`1 selectList, IReadOnlyCollection`1 currentValues)
   at Microsoft.AspNet.Mvc.Rendering.DefaultHtmlGenerator.GenerateSelect(ViewContext viewContext, ModelExplorer modelExplorer, String optionLabel, String expression, IEnumerable`1 selectList, IReadOnlyCollection`1 currentValues, Boolean allowMultiple, Object htmlAttributes)
   at Microsoft.AspNet.Mvc.Rendering.DefaultHtmlGenerator.GenerateSelect(ViewContext viewContext, ModelExplorer modelExplorer, String optionLabel, String expression, IEnumerable`1 selectList, Boolean allowMultiple, Object htmlAttributes)
   at WebApp.TagHelpers.EnumSelectTagHelper.Process(TagHelperContext context, TagHelperOutput output) in C:\Users\kenny\documents\visual studio 2015\Projects\OfficeAutomation\src\WebApp\TagHelpers\EnumSelectTagHelper.cs:line 43
   at Microsoft.AspNet.Razor.Runtime.TagHelpers.TagHelper.<ProcessAsync>d__4.MoveNext()

**Comment by nguerrera** [comment]
@kennywangjin That code will behave exactly the same way on full .NET Framework. One of the declared fields, `value__`, is actually non-static. 

You have a couple of options:

1. Add `.Where(f => f.IsLiteral)`
2. Use `Enum.GetNames()` and let it do the right thing.

It's also worth noting that both Text and Value get the same string since Enum.ToString() returns the FieldInfo.Name as well. I'd make that clearer to the reader:

```C#
Enum.GetNames(enumType).Select(name => new SelectListItem { Value = name, Text = name })
```

**Comment by kennywangjin** [comment]
@nguerrera Thanks. Got it!
