### ISSUE TITLE
HttpRequestHeaders unable to add malformed User-Agent header

### ISSUE THREAD

**Issue by doggy8088** [dotnet/corefx#34933]
The following code snippet will produce `IndexOutOfRangeException`.  Is this a bug?

```cs
using System.Net.Http;
using System.Net.Http.Headers;

HttpRequestHeaders headers = new HttpClient().DefaultRequestHeaders;
headers.Add("User-Agent", "Mozilla/4.0 (compatible (compatible; MSIE 8.0; Windows NT 6.1; Trident/7.0)");
```

**Comment by davidsh** [comment]
>The following code snippet will produce IndexOutOfRangeException. Is this a bug?

The header value you are adding is malformed.  So, you would expect an exception.

If you're trying to add malformed headers and don't want validation, you can do this:

```c#
using System.Net.Http;
using System.Net.Http.Headers;

HttpRequestHeaders headers = new HttpClient().DefaultRequestHeaders;
headers.TryAddWithoutValidation("User-Agent", "Mozilla/4.0 (compatible (compatible; MSIE 8.0; Windows NT 6.1; Trident/7.0)");
```

**Comment by davidsh** [comment]
>@davidsh Thanks! After I added to the headers, I can't read it out. It will produce IndexOutOfRangeException too. What can I do?

How are you actually accessing the header?  What is the code you're using?

Usually if you are using the strongly-typed properties such as `HttpRequestHeaders.UserAgent` then it will return `null` is there is no header value or the header value cannot be parsed into a valid value/strong type.  In that case (i.e. for malformed headers), you use methods like `GetValues` or `TryGetValues`.

**Comment by doggy8088** [comment]
My case is in a Proxy server.  I have to copy the context's Headers to forwarded Headers.  I also have to determine which headers have the required data to write conditions such as `User-Agent` header.  If I can't read it out, I can't check the header value.

I was just checking the following code in my LinqPad.  The `IndexOutOfRangeException` still happen:

```cs
void Main()
{
	HttpRequestHeaders headers = new HttpClient().DefaultRequestHeaders;

	headers.TryAddWithoutValidation("User-Agent", "Mozilla/4.0 (compatible (compatible; MSIE 8.0; Windows NT 6.1; Trident/7.0)");

	headers.GetValues("User-Agent").Dump();	
}
```

**Comment by doggy8088** [comment]
Due to many of the users use some weird Browsers who sent the malformed `User-Agent` header, that cause my ASP.NET Core app throw `IndexOutOfRangeException`.  I don't know how to workaround this.

How can I read the `headers` safely without any Exception happen?

**Comment by davidsh** [comment]
What is the version of .NET Core you are using?  Can you show output from "dotnet --info"?

**Comment by damianh** [comment]
`TryAddWithoutValidation()` allows the header to be added to the request, however it insufficient. It will still be validate when sending and throws. 

![image](https://user-images.githubusercontent.com/57436/52081232-045e7000-259a-11e9-981a-3a154d1b83a8.png)

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Net.Http.HttpRuleParser.GetExpressionLength(String input, Int32 startIndex, Char openChar, Char closeChar, Boolean supportsNesting, Int32& nestedCount, Int32& length)
   at System.Net.Http.Headers.ProductInfoHeaderValue.GetProductInfoLength(String input, Int32 startIndex, ProductInfoHeaderValue& parsedValue)
   at System.Net.Http.Headers.ProductInfoHeaderParser.TryParseValue(String value, Object storeValue, Int32& index, Object& parsedValue)
   at System.Net.Http.Headers.HttpHeaders.TryParseAndAddRawHeaderValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value, Boolean addWhenInvalid)
   at System.Net.Http.Headers.HttpHeaders.ParseSingleRawHeaderValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info)
   at System.Net.Http.Headers.HttpHeaders.ParseRawHeaderValues(HeaderDescriptor descriptor, HeaderStoreItemInfo info, Boolean removeEmptyHeader)
   at System.Net.Http.Headers.HttpHeaders.GetEnumeratorCore()+MoveNext()
   at Microsoft.AspNetCore.TestHost.ClientHandler.<>c__DisplayClass3_0.<SendAsync>b__0(HttpContext context)
   at Microsoft.AspNetCore.TestHost.ClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at ... 
```

**Comment by damianh** [comment]
This is a bit yucky alright. Not being able to read the header that was added without validation I would consider to be a bug.

Also HTTPClient not being able to send a request whose had a header added without validation is also a bug.

``` csharp
var request = new HttpRequestMessage(HttpMethod.Get, "https://example.com");
request.Headers.Add("User-Agent", "Mozilla/4.0 (compatible (compatible; MSIE 8.0; Windows NT 6.1; Trident/7.0)");
var client = new HttpClient();
await client.SendAsync(request); // IndexOutOfRangeException
```

**Comment by damianh** [comment]
I can confirm that `TryGetValues` throws on `IndexOutOfRangeException` occurs on .NET Framework (`net461`).

```charp
request.Headers.TryAddWithoutValidation("User-Agent", "Mozilla/4.0 (compatible (compatible; MSIE 8.0; Windows NT 6.1; Trident/7.0)");
request.Headers.TryGetValues("User-Agent", out var _); // IndexOutOfRangeException
```

**However**, `client.SendAsync(request)` does **not** throw on .NET Framework

**Comment by damianh** [comment]
Also shows up via in AspNet Core TestHost `ClientHandler`:

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Net.Http.HttpRuleParser.GetExpressionLength(String input, Int32 startIndex, Char openChar, Char closeChar, Boolean supportsNesting, Int32& nestedCount, Int32& length)
   at System.Net.Http.Headers.ProductInfoHeaderValue.GetProductInfoLength(String input, Int32 startIndex, ProductInfoHeaderValue& parsedValue)
   at System.Net.Http.Headers.ProductInfoHeaderParser.TryParseValue(String value, Object storeValue, Int32& index, Object& parsedValue)
   at System.Net.Http.Headers.HttpHeaders.TryParseAndAddRawHeaderValue(String name, HeaderStoreItemInfo info, String value, Boolean addWhenInvalid)
   at System.Net.Http.Headers.HttpHeaders.ParseSingleRawHeaderValue(String name, HeaderStoreItemInfo info)
   at System.Net.Http.Headers.HttpHeaders.ParseRawHeaderValues(String name, HeaderStoreItemInfo info, Boolean removeEmptyHeader)
   at System.Net.Http.Headers.HttpHeaders.<GetEnumeratorCore>d__21.MoveNext()
   at Microsoft.AspNetCore.TestHost.ClientHandler.<>c__DisplayClass3_0.<SendAsync>b__0(HttpContext context)
   at Microsoft.AspNetCore.TestHost.ClientHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
```
