### ISSUE TITLE
SocketPerformance_SingleSocketClientAPM_LocalHostServerAPM failed in CI on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3495]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug/1351/console
```
11:22:58      System.Net.Sockets.Performance.Tests.SocketPerformanceAPMTests.SocketPerformance_SingleSocketClientAPM_LocalHostServerAPM [FAIL]
11:22:58         Test execution is expected to be shorter than 5000 but was 7543
11:22:58         Expected: True
11:22:58         Actual:   False
11:22:58         Stack Trace:
11:22:58            d:\j\workspace\dotnet_corefx_windows_debug\src\Common\tests\System.Net\Sockets\Performance\SocketPerformanceTests.cs(53,0): at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.ClientServerTest(Int32 port, SocketImplementationType serverType, SocketImplementationType clientType, Int32 iterations, Int32 bufferSize, Int32 socket_instances, Int64 expectedMilliseconds)
11:22:58            d:\j\workspace\dotnet_corefx_windows_debug\src\System.Net.Sockets.Legacy\tests\PerformanceTests\SocketPerformanceAPMTests.cs(38,0): at System.Net.Sockets.Performance.Tests.SocketPerformanceAPMTests.SocketPerformance_SingleSocketClientAPM_LocalHostServerAPM()
```
cc: @davidsh, @cipop, @pgavlin

**Comment by stephentoub** [comment]
Related failure?:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/2808/
```
18:29:34    System.Net.Sockets.Performance.Tests.SocketPerformanceAPMTests.SocketPerformance_SingleSocketClientAPM_LocalHostServerAsync [FAIL]
18:29:34       System.AggregateException : One or more errors occurred.
18:29:34       ---- System.Net.Sockets.SocketException : Unknown error 10061
18:29:34       Stack Trace:
18:29:35             at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
18:29:35             at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
18:29:35          --- End of stack trace from previous location where exception was thrown ---
18:29:35             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
18:29:35             at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
18:29:35             at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
18:29:35             at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
18:29:35             at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.RunClient(SocketImplementationType testType, String server, Int32 port, Int32 iterations, Int32 bufferSize, Int32 socket_instances)
18:29:35             at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.ClientServerTest(Int32 port, SocketImplementationType serverType, SocketImplementationType clientType, Int32 iterations, Int32 bufferSize, Int32 socket_instances, Int64 expectedMilliseconds)
18:29:35             at System.Net.Sockets.Performance.Tests.SocketPerformanceAPMTests.SocketPerformance_SingleSocketClientAPM_LocalHostServerAsync()
18:29:35          ----- Inner Stack Trace -----
18:29:35             at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
18:29:35             at System.Net.Sockets.Socket.DoDnsCallback(IAsyncResult result, MultipleAddressConnectAsyncResult context)
18:29:35             at System.Net.Sockets.Socket.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
18:29:35             at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
18:29:35             at System.Net.Sockets.Performance.Tests.SocketTestClientAPM.Connect(Action`1 onConnectCallback)
18:29:35             at System.Net.Sockets.Performance.Tests.SocketTestClient.RunTest()
18:29:35             at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.<>c__DisplayClass1.<RunClient>b__0(Int32 i)
18:29:35             at System.Threading.Tasks.Parallel.<>c__DisplayClassd`1.<ForWorker>b__b(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
18:29:35          --- End of stack trace from previous location where exception was thrown ---
18:29:35             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
18:29:35             at System.Threading.Tasks.Parallel.<>c__DisplayClassd`1.<ForWorker>b__b(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
18:29:35             at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
18:29:35             at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

**Comment by CIPop** [comment]
@stephentoub These are not CI tests but Performance/outer loop. Why are they running on each check-in?

It appears that the CI machines are overwhelmed and can't keep up with the execution requirements that were tuned for the ToF execution machines.

10061 is No connection could be made because the target machine actively refused it. This usually means that the code didn't get to Accept() the connection and the Kernel refused since it wasn't handled in time.

**Comment by stephentoub** [comment]
> Why are they running on each check-in?

Because they're not marked as [OuterLoop] (or [Benchmark] for the new performance scheme being worked on).  Each PR runs tests with ```-notrait category=failing -notrait category=outerloop```.

**Comment by CIPop** [comment]
Summary of issues:
- [ ] `System.Net.Sockets.SocketException : Unknown error 10061` I believe this should be a known error code. Potential AppCompat bug.
- [ ] CI server can't keep up:
  * Connections refused
  * Performance test completes in 7.6sec (> 5sec which is a conservative expectation on a 8 logical core machine running the tests sequentially - usually the tests execute in <1sec)

**Comment by CIPop** [comment]
@pgavlin Thanks for moving the tests to OuterLoop!

Was this investigated as well:
>  System.Net.Sockets.SocketException : Unknown error 10061  I believe this should be a known error code. Potential AppCompat bug.

Only asking since we were tracking it with this issue although it isn't related. I could open another issue if it wasn't.
