### ISSUE TITLE
PLINQ GetEnumerator_CurrentBeforeMoveNext test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3496]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/2782/
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/2784/
```
09:11:48    System.Linq.Parallel.Tests.GetEnumeratorTests.GetEnumerator_CurrentBeforeMoveNext(labeled: Enumerable.Range, count: 16) [FAIL]
09:11:48       Assert.InRange() Failure
09:11:48       Range:  (0 - 16)
09:11:48       Actual: -1
09:11:48       Stack Trace:
09:11:48             at System.Linq.Parallel.Tests.GetEnumeratorTests.GetEnumerator_CurrentBeforeMoveNext(Labeled`1 labeled, Int32 count)
09:11:48    System.Linq.Parallel.Tests.GetEnumeratorTests.GetEnumerator_CurrentBeforeMoveNext(labeled: Enumerable.Range-Ordered, count: 16) [FAIL]
09:11:48       Assert.InRange() Failure
09:11:48       Range:  (0 - 16)
09:11:48       Actual: -1
09:11:48       Stack Trace:
09:11:48             at System.Linq.Parallel.Tests.GetEnumeratorTests.GetEnumerator_CurrentBeforeMoveNext(Labeled`1 labeled, Int32 count)
```
cc: @Clockwork-Muse

**Comment by JonHanna** [comment]
Not an issue. That was me, and it should indeed fail on that test (or arguably nothing should fail it, but that's for another discussion). I didn't see the failure before pushing because the change is in another project. The CI was doing its job.
