### ISSUE TITLE
SendPacketsElement_FilePart_Success failed in CI on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3497]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/4322/console
```
Starting:    System.Net.Sockets.AsyncServer.Tests
     System.Net.Sockets.Tests.SendPacketsAsync.SendPacketsElement_FilePart_Success [FAIL]
        Timed out
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets.Legacy\tests\FunctionalTests\SendPacketsAsync.cs(397,0): at System.Net.Sockets.Tests.SendPacketsAsync.SendPackets(SendPacketsElement[] elements, SocketError expectedResut, Int32 bytesExpected)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets.Legacy\tests\FunctionalTests\SendPacketsAsync.cs(317,0): at System.Net.Sockets.Tests.SendPacketsAsync.SendPacketsElement_FilePart_Success()
```
cc: @davidsh, @cipop, @pgavlin

**Comment by stephentoub** [comment]
Again here: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/4348/console

**Comment by CIPop** [comment]
These fail in a slow CI system. Timing was updated by 77fb5b23 (timeouts increased x10).

I will submit a PR to re-enable the tests. If they still fail please follow-up on this issue.
