### ISSUE TITLE
Ping tests don't work on Ubuntu 1604 ARM64 - ping is not available

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#34970]
https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190130.2/workItem/System.Net.Ping.Functional.Tests

```
Unhandled Exception of Type System.Net.NetworkInformation.PingException
Message :
System.Net.NetworkInformation.PingException : An exception occurred during a Ping request.
---- System.PlatformNotSupportedException : The system's ping utility could not be found.
Stack Trace :
   at System.Net.NetworkInformation.Ping.GetAddressAndSendAsync(String hostNameOrAddress, Int32 timeout, Byte[] buffer, PingOptions options) in /__w/1/s/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.cs:line 408
   at System.Net.NetworkInformation.Tests.PingTest.SendPingAsync(Func`2 sendPing, Action`1 pingResultValidator) in /__w/1/s/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs:line 750
   at System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithHostAndTimeout() in /__w/1/s/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs:line 427
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.NetworkInformation.Ping.GetPingProcess(IPAddress address, Byte[] buffer, PingOptions options) in /__w/1/s/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.Unix.cs:line 275
   at System.Net.NetworkInformation.Ping.SendWithPingUtilityAsync(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options) in /__w/1/s/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.Unix.cs:line 317
   at System.Net.NetworkInformation.Ping.SendPingAsyncCore(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options) in /__w/1/s/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.Unix.cs:line 48
   at System.Net.NetworkInformation.Ping.GetAddressAndSendAsync(String hostNameOrAddress, Int32 timeout, Byte[] buffer, PingOptions options) in /__w/1/s/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.cs:line 397
```

ping is not installed by default (it is gotten like `apt-get install iputils-ping`)

or tests need to be updated to skip on this platform -- or skip the tests if none of `/bin/ping` / `/sbin/ping` `/usr/bin/ping` exist.

@wfurt.

**Comment by wfurt** [comment]
I think it would be nice to add that package so we can run the tests. That should be easy IMHO as we own the images. 

cc: @safern

**Comment by safern** [comment]
@ulisesh could you also install ping in all the helix images?

**Comment by ulisesh** [comment]
Sure, I will add ping to out helix images

**Comment by wfurt** [comment]
BTW we had some dependencies for dumplinks to work.
Did we verify that it works and we can get stack traces? 
(depends on Python and lldb, maybe more)

**Comment by wfurt** [comment]
seems to be fixed now. closing.
