### ISSUE TITLE
SslStream.AuthenticateAsClient - RevocationStatusUnknown: unable to get certificate CRL for OCSP certificate (Let's Encrypt)

### ISSUE THREAD

**Issue by vadmyst** [dotnet/corefx#35035]
I stumbled on different behavior of SslStream.AuthenticateAsClient under Windows and Linux for the same server - https://www.videolan.org. On Linux(Raspberry Pi - Raspbian) SslStream.AuthenticateAsClient fails to open secure connection with the server. The same problem is not reproduced on Windows. I have also tried other servers that use Let's Encrypt.

On Linux my app is packaged as a self-contained and uses .Net Core 2.1.

The certificate validation callback indicates following error - _RemoteCertificateChainErrors_
When I dig into the chain: 
_Element 0: www.videolan.org - RevocationStatusUnknown: **unable to get certificate CRL**
Element 1: Let's Encrypt Authority X3 - OK
Element 2: DST Root CA X3 - OK_

Server certificate is a Let's Encrypt one that does not have CRL but instead uses OCSP.

From the same Raspberry Pi box, I have successfully validated the certificate along with its chain using openssl. I also verified certificate revocation status by using ocsp.

_Response verify OK
videolan.pem: good
        This Update: Jan 30 07:00:00 2019 GMT
        Next Update: Feb  6 07:00:00 2019 GMT_

I know that .Net Core uses external libraries for TLS
Is it the issue in .Net Core or underlying libraries it uses for TLS?

Here's what I have on that Linux box
_openssl version -v -p
OpenSSL 1.1.0f  25 May 2017
platform: debian-armhf_

_curl --version
curl 7.52.1 (arm-unknown-linux-gnueabihf) libcurl/7.52.1 **OpenSSL/1.0.2l** zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL_

Just in case, here's the log
The stacktrace of AuthenticateAsClient is as follows 
Inner System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)

**Comment by bartonjs** [comment]
Duplicate of #3034
