### ISSUE TITLE
CompositionExceptionTests.Message_ShouldFormatCountOfRootCausesUsingTheCurrentCulture test fails, but only in code coverage

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#35053]
Running `dotnet msbuild /T:BuildAndTest`, this test passes
Running `dotnet msbuild /T:BuildAndTest /P:Coverage=true` this test fails:

```
    Discovering: System.ComponentModel.Composition.Tests (method display = ClassAndMethod, method display options = None)
    Discovered:  System.ComponentModel.Composition.Tests (found 1428 of 1628 test cases)
    Starting:    System.ComponentModel.Composition.Tests (parallel test collections = on, max threads = 4)
        Exit code was 131 but it should have been 42
        Expected: True
        Actual:   False
        Stack Trace:
          /Users/hugh/Documents/GitHub/corefx/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs(371,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose(Boolean disposing)
          /Users/hugh/Documents/GitHub/corefx/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs(345,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
          /Users/hugh/Documents/GitHub/corefx/src/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/CompositionExceptionTests.cs(372,0): at System.ComponentModel.Composition.CompositionExceptionTests.Message_ShouldFormatCountOfRootCausesUsingTheCurrentCulture()
    Finished:    System.ComponentModel.Composition.Tests
```

**Comment by maryamariyan** [comment]
does not repro.
