### ISSUE TITLE
Parallelism of HTTP request is more reliable on WSL

### ISSUE THREAD

**Issue by joelverhagen** [dotnet/corefx#35066]
## Introduction

I have an application that does a lot of parallel HTTP requests. For the sake of this bug report, all of the HTTP requests are for small response bodies (<2kb). I am trying to increase throughput by using parallelism. Today, I only run my application on Windows but it cross targets `net462` and `netcoreapp2.2`. Also, I always set the connection limits to 64 and only ever try up to 32 parallel requests. 

I have noticed on my Windows desktop at home there is some strange behavior when I have more than 4 parallel HTTP requests going at the same time. Some requests are snappy fast. Others take a long time (more than 10 seconds) and succeed. Others take a long time then fail with connection timeout.

When I run the same code, same machine on WSL, Ubuntu 16.04 the code runs faster and does not throw timeout exceptions.

### My Windows 10 desktop - .NET Core SDK 2.2

For example, below are pictures of N worker tasks chewing through 100 URLs as fast as possible. The two green colors are alternating on successful requests. The red bars eventually throw connection timeout:

```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.240.159.111:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp2.Program.<>c__DisplayClass1_0.<<MainAsync>b__0>d.MoveNext()
```

#### 4 parallel

![data-windows-netcoreapp2 2-64-4 txt](https://user-images.githubusercontent.com/94054/52190955-dcb81380-27f6-11e9-9d58-fdff9c7987c3.png)

#### 8 parallel

![data-windows-netcoreapp2 2-64-8 txt](https://user-images.githubusercontent.com/94054/52190948-d3c74200-27f6-11e9-8630-cd5055d3d4f6.png)

#### 16 parallel

![data-windows-netcoreapp2 2-64-16 txt](https://user-images.githubusercontent.com/94054/52189985-f6eef300-27f0-11e9-91a1-f9a86ae0a122.png)

#### 32 parallel

![data-windows-netcoreapp2 2-64-32 txt](https://user-images.githubusercontent.com/94054/52190926-bdb98180-27f6-11e9-9f81-8ff47a2eb08b.png)

#### 16 parallel

![data-wsl-ubuntu-netcoreapp2 2-16 04 3-64-16 txt](https://user-images.githubusercontent.com/94054/52190007-23a30a80-27f1-11e9-959e-20da1c643c91.png)

#### 32 parallel

![data-wsl-ubuntu-netcoreapp2 2-16 04 3-64-32 txt](https://user-images.githubusercontent.com/94054/52190915-94005a80-27f6-11e9-924c-60996ff6e1d2.png)

### All Data (raw timings and pictures)

This has the results for 2, 4, 8, 16, and 32 degrees of parallelism for all runtimes mentioned above as well as on other PCs that have better networks. For example:

1. Work machine (no issues)
1. Work DTL (no issues)
1. Digital Ocean (no issues)
1. Work laptop at home (worse than my desktop at homel)

[http.zip](https://github.com/dotnet/corefx/files/2826593/http.zip)

## Repro

I put a repro here:
https://gist.github.com/joelverhagen/d400256f89d6631bede8a5705d3c7c79

Note that it is not quite minimal -- the output is compatible with [splot](http://jkff.info/software/timeplotters/splot.html), the tool I used to make those pictures. If you need a more minimal one, just ask me.

## Question

Why would WSL be more reliable and run faster with all other variables (hardware, network) the same? Or perhaps I am missing a crucial variable?

I noticed .NET Core and .NET Framework on the same machine behaved very similarly. I tried installing [System.Net.Http 4.3.4](https://www.nuget.org/packages/System.Net.Http/4.3.4) and this stayed the same. Is the key variable here Windows vs. Linux? If so, why is the Linux implementation better in this way?

Am I expecting too much out of my home network? 😄 Is there some rough "number" about my network that describes this general problem? Is it the bandwidth that my ISP is giving me? Is it my router's specifications? Perhaps this question is impossible to determine remotely but I figure I'd ask.

**Comment by Clockwork-Muse** [comment]
My system: [data](https://github.com/dotnet/corefx/files/2826951/data.zip)
No errors, runs faster than your data.

Linux actually runs longer for me, for whatever reason.

...As does [472](https://github.com/dotnet/corefx/files/2826988/472.zip)

**Comment by joelverhagen** [comment]
Thanks for the data @Clockwork-Muse:

#### data.zip

![data-windows-net462-64-16 txt](https://user-images.githubusercontent.com/94054/52216793-eddf3f80-284b-11e9-8ce7-38ac934f9b4e.png)

![data-windows-net462-64-32 txt](https://user-images.githubusercontent.com/94054/52216815-fcc5f200-284b-11e9-93dc-9229556730f8.png)


### 472.zip

![data-windows-net472-64-16 txt](https://user-images.githubusercontent.com/94054/52216759-db650600-284b-11e9-8b38-5d6b46c8f2e2.png)

![data-windows-net472-64-32 txt](https://user-images.githubusercontent.com/94054/52216715-c0929180-284b-11e9-92b5-1c27d68caf2f.png)

**Comment by Zenexer** [comment]
Since this is specific to your network, my money is on it being an IPv6 issue. DNS query returns AAAA records, but you don’t have IPv6 connectivity, so it times out and reattempts with IPv4. Test by disabling IPv6 on your network adapter.
