### ISSUE TITLE
Uri.TryCreate throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by Metalnem** [dotnet/corefx#35072]
**Uri.TryCreate** is a non-throwing method, but for some inputs it can throw **IndexOutOfRangeException**. Here's the full program that reproduces this:

```csharp
using System;
using System.Text;

namespace Test
{
  public class Program
  {
    public static void Main(string[] args)
    {
      var b = new byte[] {
        92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92,
        92, 226, 128, 174, 47, 255, 11, 117, 102, 112, 10
      };

      var s = Encoding.UTF8.GetString(b);
      Uri.TryCreate(s, UriKind.RelativeOrAbsolute, out _);
    }
  }
}
```

The stack trace:

```
Exception has occurred: CLR/System.IndexOutOfRangeException
An unhandled exception of type 'System.IndexOutOfRangeException' occurred in System.Private.Uri.dll: 'Index was outside the bounds of the array.'
   at System.Uri.CreateUriInfo(Flags cF)
   at System.Uri.EnsureUriInfo()
   at System.Uri.ParseRemaining()
   at System.Uri.EnsureParseRemaining()
   at System.Uri.InitializeUri(ParsingError err, UriKind uriKind, UriFormatException& e)
   at System.Uri.CreateHelper(String uriString, Boolean dontEscape, UriKind uriKind, UriFormatException& e)
   at System.Uri.TryCreate(String uriString, UriKind uriKind, Uri& result)
```

The environment:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.103/
```

Found via [SharpFuzz](https://github.com/Metalnem/sharpfuzz).

**Comment by davidsh** [comment]
@rmkerr

**Comment by rmkerr** [comment]
Hey @Metalnem, thanks for reporting this! The decoded version of that string is `\\\\\\\\\\\\\\‮/�ufp`
 which contains a Unicode bidirectional control character (and was incredibly difficult to get formatted correctly for this comment). With that in mind, I think this is a duplicate of #21202.

**Comment by danmosemsft** [comment]
> and was incredibly difficult to get formatted correctly for this comment

😃
