### ISSUE TITLE
Windows SignedCms fails signing when using an ephemerally constructed certificate

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#35120]
This fails:

```C#
using (RSA rsa = RSA.Create())
using (X509Certificate2 pubOnly = GetTheCert())
{
    rsa.ImportParameters(fromSomewhere);

    using (X509Certificate2 certWithKey = pubOnly.CopyWithPrivateKey(rsa))
    {
        ContentInfo content = new ContentInfo(new byte[] { 1, 2, 3 });
        SignedCms cms = new SignedCms(content, false);
        CmsSigner signer = new CmsSigner(certWithKey);
        cms.ComputeSignature(signer);
        ...
    }
}
```

```
Unhandled Exception: System.ArgumentException: The CNG key handle being opened was detected to be ephemeral, but the EphemeralKey open option was not specified.

Parameter name: keyHandleOpenOptions
   at System.Security.Cryptography.CngKey.Open(SafeNCryptKeyHandle keyHandle, CngKeyHandleOpenOptions keyHandleOpenOptions)
   at Internal.Cryptography.Pal.Windows.PkcsPalWindows.GetPrivateKey[T](X509Certificate2 certificate, Boolean silent, Boolean preferNCrypt)
   at Internal.Cryptography.Pal.Windows.PkcsPalWindows.GetPrivateKeyForSigning[T](X509Certificate2 certificate, Boolean silent)
   at System.Security.Cryptography.Pkcs.CmsSignature.RSAPkcs1CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, Boolean silent, Oid& signatureAlgorithm, Byte[]& signatureValue)
   at System.Security.Cryptography.Pkcs.CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, Boolean silent, Oid& oid, ReadOnlyMemory`1& signatureValue)
   at System.Security.Cryptography.Pkcs.CmsSigner.Sign(ReadOnlyMemory`1 data, String contentTypeOid, Boolean silent, X509Certificate2Collection& chainCerts)
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer, Boolean silent)
```

But indirecting through a PFX export/import works:

```C#
using (RSA rsa = RSA.Create())
using (X509Certificate2 pubOnly = GetTheCert())
{
    rsa.ImportParameters(fromSomewhere);

    using (X509Certificate2 temp = pubOnly.CopyWithPrivateKey(rsa))
    using (X509Certificate2 certWithKey = new X509Certificate2(temp.Export(X509ContentType.Pfx)))
    {
        ContentInfo content = new ContentInfo(new byte[] { 1, 2, 3 });
        SignedCms cms = new SignedCms(content, false);
        CmsSigner signer = new CmsSigner(temp);
        cms.ComputeSignature(signer);
        ...
    }
}
```

It seems that https://github.com/dotnet/corefx/blob/9007057ab6ba649c67dbca2a422d997075404e6c/src/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/Windows/PkcsPalWindows.cs#L218 asserts CngKeyHandleOptions.None, when it needs to proxy-detect the ephemeral state

**Comment by vcsjones** [comment]
@bartonjs I can take a stab at this if no one else is expected to work on it.

**Comment by bartonjs** [comment]
@vcsjones All yours :smile: (I had even thought of asking if you wanted it).

Should just require asking if the CLR Ephemeral property is defined on the key object, hopefully fairly straightforward (and hopefully my notes are enough for a useful test).

**Comment by vcsjones** [comment]
@bartonjs 

> I had even thought of asking if you wanted it

Feel free to any time, there's a firehose of stuff here, so sometimes I miss things that I would probably find interesting.

**Comment by forlayo** [comment]
I've detected that with proposal workaround it creates an issue while deploying into Azure App Service:

```
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified
   at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] data)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData)
```

At line
`using (X509Certificate2 certWithKey = new X509Certificate2(temp.Export(X509ContentType.Pfx)))`
