### ISSUE TITLE
 System.Security.Cryptography.X509Certificates.Tests crashing in OSX10.13

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#35233]
System.Security.Cryptography.X509Certificates.Tests are crashing in some PRs. These seems to not been happening consistently in all builds.

```
~/dotnetbuild/work/1dd5a8dc-1c76-47bb-a13f-0810b426d77f/Work/3c4bbd01-cc4c-4990-b04a-5ae606f0ecb5/Exec ~/dotnetbuild/work/1dd5a8dc-1c76-47bb-a13f-0810b426d77f/Work/3c4bbd01-cc4c-4990-b04a-5ae606f0ecb5/Exec
[37m  Discovering: System.Security.Cryptography.X509Certificates.Tests (method display = ClassAndMethod, method display options = None)
[mAssertion Failed
X509ChainGetStatusAtIndex returned unexpected error 2

   at Internal.Cryptography.Pal.SecTrustChainPal.ParseResults(SafeX509ChainHandle chainHandle, X509RevocationMode revocationMode) in /Users/vsts/agent/2.146.0/work/1/s/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/ChainPal.cs:line 247
   at Internal.Cryptography.Pal.SecTrustChainPal.Execute(DateTime verificationTime, Boolean allowNetwork, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationFlag revocationFlag) in /Users/vsts/agent/2.146.0/work/1/s/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/ChainPal.cs:line 210
   at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout) in /Users/vsts/agent/2.146.0/work/1/s/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/ChainPal.cs:line 571
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException) in /Users/vsts/agent/2.146.0/work/1/s/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Chain.cs:line 118
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate) in /Users/vsts/agent/2.146.0/work/1/s/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Chain.cs:line 105
   at System.Security.Cryptography.X509Certificates.Tests.ChainTests.get_TrustsMicrosoftDotComRoot() in /Users/vsts/agent/2.146.0/work/1/s/src/System.Security.Cryptography.X509Certificates/tests/ChainTests.cs:line 33
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/vsts/agent/2.144.2/work/1/s/src/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 472
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in /Users/vsts/agent/2.144.2/work/1/s/src/System.Private.CoreLib/shared/System/Reflection/MethodBase.cs:line 54
   at Microsoft.DotNet.XUnitExtensions.ConditionalTestDiscoverer.Discover(ITestFrameworkDiscoveryOptions discoveryOptions, IMessageSink diagnosticMessageSink, ITestMethod testMethod, IEnumerable`1 testCases, Object[] conditionArguments) in /_/src/Microsoft.DotNet.XUnitExtensions/src/Discoverers/ConditionalTestDiscoverer.cs:line 89
   at Microsoft.DotNet.XUnitExtensions.ConditionalFactDiscoverer.Discover(ITestFrameworkDiscoveryOptions discoveryOptions, ITestMethod testMethod, IAttributeInfo factAttribute) in /_/src/Microsoft.DotNet.XUnitExtensions/src/Discoverers/ConditionalFactDiscoverer.cs:line 27
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForMethod(ITestMethod testMethod, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkDiscoverer.cs:line 119
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForType(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkDiscoverer.cs:line 132
   at Xunit.Sdk.TestFrameworkDiscoverer.FindTestsForTypeAndWrapExceptions(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\TestFrameworkDiscoverer.cs:line 156
   at Xunit.Sdk.TestFrameworkDiscoverer.<>c__DisplayClass26_0.<Find>b__0() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\TestFrameworkDiscoverer.cs:line 101
   at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__4_0(Object _) in C:\projects\xunit\src\common\XunitWorkerThread.cs:line 92
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute() in /Users/vsts/agent/2.144.2/work/1/s/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 854
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /Users/vsts/agent/2.144.2/work/1/s/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 645
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() in /Users/vsts/agent/2.144.2/work/1/s/src/System.Private.CoreLib/src/System/Threading/ThreadPool.CoreCLR.cs:line 29
./RunTests.sh: line 124: 26407 Abort trap: 6           (core dumped) $RUNTIME_PATH/dotnet xunit.console.dll System.Security.Cryptography.X509Certificates.Tests.dll -xml testResults.xml -nologo -notrait category=nonnetcoreapptests -notrait category=nonosxtests -notrait category=IgnoreForCI -notrait category=failing -notrait category=Outerloop
~/dotnetbuild/work/1dd5a8dc-1c76-47bb-a13f-0810b426d77f/Work/3c4bbd01-cc4c-4990-b04a-5ae606f0ecb5/Exec
----- end 02:17:40 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
+ _commandExitCode=134
+ /usr/local/bin/python2 /Users/dotnet-bot/dotnetbuild/work/1dd5a8dc-1c76-47bb-a13f-0810b426d77f/Payload/xunit-reporter.py
2019-02-11 02:17:41,244: ERROR: xunit-reporter(70): main: Unable to report xunit results: no test results xml file found.
+ exit 134
```

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F35227~2Fmerge/test~2Ffunctional~2Fcli~2F/20190211.2/workItem/System.Security.Cryptography.X509Certificates.Tests/wilogs

cc: @stephentoub @bartonjs @danmosemsft

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/35224

**Comment by safern** [comment]
My search for System.Security.Cryptography.X509Certificates.Tests didn't find that issue 🤣
