### ISSUE TITLE
Process kill tree - No such process when killing firefox

### ISSUE THREAD

**Issue by SoerenBusse** [dotnet/corefx#35368]
Hey there,

we've started a new process and would like to use the new `Kill(true)` method for killing an entire process tree. However we encountered a special behaviour when trying to kill firefox or chrome. 

After calling the `Kill(true)` method of a process object starting firefox or chrome we get an `Win32Exception - No such process` exception.

```
Unhandled Exception: System.AggregateException: Not all processes in process tree could be terminated. (No such process) (No such process) (No such process) ---> System.ComponentModel.Win32Exception: No such process
  at System.Diagnostics.Process.Stop()
  at System.Diagnostics.Process.KillTree()
  --- End of inner exception stack trace ---
  at System.Diagnostics.Process.Kill(Boolean entireProcessTree)
  at MagicApplication.Daemon.ProcessManagement.ManagedProcess.StopAsync(CancellationToken cancellationToken) in /home/user/Repositories/MagicApplication/MagicApplication.Daemon/ProcessManagement/ManagedProcess.cs:line 249
  at MagicApplication.Daemon.Daemon.StopAsync() in /home/user/Repositories/MagicApplication/MagicApplication.Daemon/Daemon.cs:line 34
  at MagicApplication.Daemon.Program.Main(String[] args) in /home/user/Repositories/MagicApplication/MagicApplication.Daemon/Program.cs:line 39
  at MagicApplication.Daemon.Program.<Main>(String[] args)
```

When understanding the source code right it seems that first the child process list is retrieved and afterwards the main process is killed.
https://github.com/dotnet/corefx/blob/81bd671efda5db20fae1eb381aeff2cf8ea727ac/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L99
But firefox automatically clean's up it's children so that the `Stop()` call on the entries of the child process list fails with a non zero exit code: `ESRCH`. This fires a `Win32Exception` and not as handled an `InvalidOperationException` 

OS: Ubuntu 18.04

**Comment by danmosemsft** [comment]
@SoerenBusse it woudl be great if you could try this feature again, now this issue is fixed. The scenario is full of potential races and OS quirks that you could help us discover.
