### ISSUE TITLE
Remove "HRESULT" from default exception message

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#35456]
The below message (from Ubuntu) demonstrates that in some cases the runtime will set a non-HRESULT code on the HRESULT property of an exception it throws.

The assembly load codepath has many branches but I guess it comes from code like `EEFileLoadException::Throw(pSpec, hr);` where the `hr` is coming from the PAL. 

In this case `1C No space left on device` is not an emulated Win32 code from the PAL (which would be `ERROR_DISK_FULL 0n112`) but instead a Unix errorno (`ENOSPC 0n28 No space left on device`).  Either way it's not an HRESULT and perhaps never will be on Unix.

@stephentoub if the PAL aims to map to a Win32 code if applicable, perhaps this represents a missed path?

Either way, although we cannot rename the property on `Exception` we can certainly choose a more inclusive string. It's also redundant in this particular case as 28=1C. 

eg
```
Could not load file or assembly 'System.Runtime.Loader.Test.Assembly, Culture=neutral, PublicKeyToken=null'. Error 28
---- System.IO.IOException : No space left on device
``` 

and if the HRESULT was actually different to the code perhaps just remove `HRESULT`:

```
Could not load file or assembly 'System.Runtime.Loader.Test.Assembly, Culture=neutral, PublicKeyToken=null'. Error 123 (0x0000001C)
---- System.IO.IOException : No space left on device
```

This is all in CoreCLR (starting from `IDS_EE_EXCEPTION_FROM_HRESULT` in mscorrc.rc) but I see there is also a similar string in CoreFX for `ReaderWriterLockApplicationException` which possibly should also lose the `HRESULT` reference.

```
Message :
System.IO.FileLoadException : Could not load file or assembly 'System.Runtime.Loader.Test.Assembly, Culture=neutral, PublicKeyToken=null'. Error 28 (Exception from HRESULT: 0x0000001C)
---- System.IO.IOException : No space left on device
Stack Trace :
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadAssemblyByPath_ValidUserAssembly() in /mnt/j/workspace/dotnet_corefx/release_2.1/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Runtime.Loader/tests/AssemblyLoadContextTest.cs:line 57
----- Inner Stack Trace -----
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at System.Runtime.Loader.Tests.ResourceAssemblyLoadContext.Load(AssemblyName assemblyName) in /mnt/j/workspace/dotnet_corefx/release_2.1/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Runtime.Loader/tests/ResourceAssemblyLoadContext.cs:line 54
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
```

**Comment by danmosemsft** [comment]
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Frelease~2F2.1~2F/test~2Ffunctional~2Fcli~2F/135088093a447c3fee184500202691101e5d9f10/workItem/System.Runtime.Loader.Tests/analysis/xunit/System.Runtime.Loader.Tests.AssemblyLoadContextTest~2FLoadAssemblyByPath_ValidUserAssembly
