### ISSUE TITLE
HTTP2: Clean up shutdown behavior

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#35466]
We don't currently have a good handle on the lifetime semantics of various objects on Http2Connection. We should clean this up

See discussion on #35422

**Comment by geoffkizer** [comment]
Note there are several ways an HTTP2 connection can be shut down:

(1) Client-initiated shutdown with outstanding requests. This can happen when the HttpClientHandler is disposed, or when the connection lifetime is exceeded, or when we have exhausted stream IDs.
> We need to allow existing requests to complete, then close the connection.
(2) Client-initiated shutdown due to idle timeout (meaning no existing requests)
> Just close the connection
(3) Server-initiated graceful shutdown (i.e. we receive a GOAWAY)
> We need to allow any outstanding requests to complete as specified by the last stream ID in GOAWAY, then close the connection.
(4) Protocol error 
> Abort requests and close connection
(5) IO error (read or write failed)
> Abort requests and close connection

I think that covers all of the possible cases...

**Comment by wfurt** [comment]
I hit something very similar as original #35422

```
      System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest.SendAsync_RequestVersion20_HttpNotHttps_NoUpgradeRequest [FAIL]
        System.Net.Http.HttpRequestException : An error occurred while sending the request.
        ---- System.ObjectDisposedException : Cannot access a disposed object.
        Object name: 'CreditManager'.
        Stack Trace:
          /mnt/github/wfurt-corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs(1329,0): at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
          /mnt/github/wfurt-corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(522,0): at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
          /mnt/github/wfurt-corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs(33,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
          /mnt/github/wfurt-corefx/src/System.Net.Http/src/System/Net/Http/HttpClient.cs(475,0): at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
          /mnt/github/wfurt-corefx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs(2579,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<SendAsync_RequestVersion20_HttpNotHttps_NoUpgradeRequest>b__101_0(Uri uri)
          /mnt/github/wfurt-corefx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(77,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
          /mnt/github/wfurt-corefx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(105,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
          /mnt/github/wfurt-corefx/src/Common/tests/System/Net/Http/GenericLoopbackServer.cs(30,0): at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass5_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
          /mnt/github/wfurt-corefx/src/Common/tests/System/Net/Http/LoopbackServer.cs(66,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
          /mnt/github/wfurt-corefx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs(2574,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.SendAsync_RequestVersion20_HttpNotHttps_NoUpgradeRequest()
          --- End of stack trace from previous location where exception was thrown ---
```

I have some idea how to write test  and expose at least some of it. 
I think we should bring it back to 3.0 @karelz

**Comment by ViktorHofer** [comment]
Another HTTP2 test failed, probably becaues of this:

```
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_ServerSendsInvalidSettingsValue_Error(settingId: MaxFrameSize, value: 16383, expectedError: PROTOCOL_ERROR, skipForWinHttp: True)

Assert.Contains() Failure\nNot found: PROTOCOL_ERROR\nIn value: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.ObjectDisposedException: Cannot access a disposed object.\nObject name: 'CreditManager'.\n at System.Net.Http.CreditManager.RequestCreditAsync(Int32 amount, CancellationToken cancellationToken) in /__w/1/s/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/CreditManager.cs:line 43\n at System.Net.Http.Http2Connection.SendHeadersAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /__w/1/s/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 958\n at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /__w/1/s/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 1345\n --- End of inner exception stack trace ---\n at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /__w/1/s/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 1383\n at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /__w/1/s/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 525\n at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /__w/1/s/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 33\n at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in /__w/1/s/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 475\n at Xunit.Assert.RecordExceptionAsync(Func`1 testCode) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\Record.cs:line 82
```

**Comment by wfurt** [comment]
this should be fixed by #38226

**Comment by stephentoub** [comment]
@wfurt, there's still a test disabled against this:
https://github.com/dotnet/runtime/blob/ccf6aedb63c37ea8e10e4f5b5d9d23a69bdd9489/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs#L212-L217

**Comment by wfurt** [comment]
ok. i'll take a look.

**Comment by karelz** [comment]
We should then switch it back to 3.0 milestone to reflect where it was fixed (assuming it was fully fixed and the tests are addressed)

**Comment by wfurt** [comment]
this is a test bug. No need to worry about versions IMHO.

**Comment by karelz** [comment]
FYI @wfurt 3.0 milestone is in the "Closed" tab under Milestone ;)
