### ISSUE TITLE
Environment.GetEnvironmentVariable throws MethodAccessException when using local CoreFX build

### ISSUE THREAD

**Issue by Metalnem** [dotnet/corefx#35555]
I've been using local CoreFX build successfully with .NET Core 2.2 for some time using instructions from the [dogfooding.md](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#more-advanced-scenario---using-your-local-corefx-build) document. Now I'm trying to do the same with the .NET Core 3.0, but I'm running into problems. I'm using the latest .NET Core 3.0 preview on Mac OS:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010184
 Commit:    c57bde4593

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /Users/Metalnem/Temp/dotnet-sdk-3.0.100-preview-010184-osx-x64/sdk/3.0.100-preview-010184/
```

I have created a local CoreFX build in the DEBUG configuration from the latest master (it was 26b932e3c56702382d13ece010b300d3181d2891 when I was writing this). The build number was **4.6.0-dev.19125.1**, so I created the following project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Private.CoreFx.NETCoreApp" Version="4.6.0-dev.19125.1" />
  </ItemGroup>

  <PropertyGroup>
    <PackageConflictPreferredPackages>Microsoft.Private.CoreFx.NETCoreApp;runtime.osx-x64.Microsoft.Private.CoreFx.NETCoreApp;$(PackageConflictPreferredPackages)</PackageConflictPreferredPackages>
  </PropertyGroup>

</Project>
```

My NuGet.Config looks like this:

```xml
<configuration>
  <packageSources>
    <add key="local coreclr" value="/Users/Metalnem/Temp/corefx/artifacts/packages/Debug" />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
  </packageSources>
</configuration>
```

And this is the **Main** function of my project:

```csharp
public static void Main(string[] args)
{
  Console.WriteLine("Hello World!");
}
```

After publishing the project with the ```dotnet publish -r osx-x64``` command, running the binary results in the following exception:

```
Unhandled Exception: System.MethodAccessException: Attempt by method 'System.Text.EncodingHelper.GetCharset()' to access method 'System.Environment.GetEnvironmentVariable(System.String)' failed.
   at System.Text.EncodingHelper.GetCharset()
   at System.Text.EncodingHelper.GetEncodingFromCharset()
   at System.ConsolePal.GetConsoleEncoding()
   at System.ConsolePal.get_OutputEncoding()
   at System.Console.<>c.<get_OutputEncoding>b__18_0()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Object& syncLock, Func`1 valueFactory)
   at System.Threading.LazyInitializer.EnsureInitialized[T](T& target, Object& syncLock, Func`1 valueFactory)
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at System.Console.get_OutputEncoding()
   at System.Console.CreateOutputWriter(Stream outputStream)
   at System.Console.<>c.<get_Out>b__25_0()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Object& syncLock, Func`1 valueFactory)
   at System.Threading.LazyInitializer.EnsureInitialized[T](T& target, Object& syncLock, Func`1 valueFactory)
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at System.Console.get_Out()
   at System.Console.WriteLine(String value)
   at Test.Program.Main(String[] args)
```

But if I write my **Main** function like this, everything works fine:

```csharp
public static void Main(string[] args)
{
  File.WriteAllText("Out.txt", "Hello World!");
}
```

**Comment by danmosemsft** [comment]
Hmm, I wonder whether you are somehow straddling @stephentoub 's recent changes that moved Environment into corelib.

**Comment by Metalnem** [comment]
You are right, thanks! I'm now using daily .NET Core build, and everything works as expected.
