### ISSUE TITLE
Are BinaryFormatter Serialization dotnet core and framework compatible?

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#35629]
_From @bcbeatty on February 27, 2019 15:26_

# Are BinaryFormatter Serialization dotnet core and framework compatible?
I have 2 programs, one written in .Net Framework 4.7.x and another app that is dot net core 2.x

Program 1, written in .Net Framework. takes a Dataset and using BinaryFormatter writes it to a database field as a byte[].

Program 2, written in dot net core, then takes that record and attempts to Deserialize the field using BinaryFormatter. I'm getting an exception _"ArgumentException: Type 'System.Byte' is not deserializable."_

## Program 1 - Framework

```
static void Main(string[] args)
    {
        var connectionString = ConfigurationManager.ConnectionStrings["CDPMetadataModelContext"].ConnectionString;
        byte[] binaryFormattedDs;
        using (var connection = new SqlConnection(connectionString))
        {
            connection.Open();

            using (var da = new SqlDataAdapter("Select * from Code_Job_Status", connection))
            {
                var ds = new DataSet();
                da.Fill(ds);
                binaryFormattedDs = SerializeBinaryDataContract(ds);
            }
            string query = "INSERT INTO dbo.Result_Cache (Result_Binary_Data, Run_DateTime) output inserted.Result_Cache_ID VALUES";
            string insertQuery = "(@binaryValue, getdate())";
            using (SqlCommand cmd = new SqlCommand(query + insertQuery, connection))
            {
                cmd.Parameters.AddWithValue("@binaryValue", SqlDbType.VarBinary).Value = binaryFormattedDs;                   
                var newId = (int)cmd.ExecuteScalar();
                Console.WriteLine("New Id= "+ newId);
                Debug.WriteLine("New Id= " + newId);
            }
            connection.Close();
        }

        Console.ReadKey();
        var ds2 = DeSerialize<DataSet>(binaryFormattedDs);
        Console.WriteLine("Row Count=" + ds2.Tables[0].Rows.Count);
        Console.ReadKey();
    }

    public static T DeSerialize<T>(byte[] bytes)
    {
        var serializer = new BinaryFormatter();
        using (var ms = new MemoryStream())
        {
            ms.Write(bytes, 0, bytes.Length);
            ms.Seek(0, SeekOrigin.Begin);
            return (T)serializer.Deserialize(ms);
        }

    }

    public static byte[] SerializeBinaryDataContract(DataSet dataSet)
    {

            BinaryFormatter binaryFormatter = new BinaryFormatter();
            byte[] buffer;
            using (MemoryStream memoryStream = new MemoryStream())
            {
                dataSet.RemotingFormat = SerializationFormat.Binary;
                binaryFormatter.Serialize((Stream)memoryStream, (object)dataSet);
                buffer = new byte[memoryStream.Length];
                memoryStream.Seek(0L, SeekOrigin.Begin);
                memoryStream.Read(buffer, 0, buffer.Length);
            }
            return buffer;

    }
```

## Program 2 - Core
    static void Main(string[] args)
    {

        Console.WriteLine("Result_Cache_ID:");
        var reportIds = Console.ReadLine();
        if (int.TryParse(reportIds, out var resultCacheId))
        {

            GetDS(resultCacheId);
        }

        Console.ReadKey();
    }
    private static void GetDS(int resultCacheId)
    {

        using (var connection = new SqlConnection(ConnectionString))
        {
            connection.Open();

            using (var da = new SqlDataAdapter("Select * from Result_Cache where Result_Cache_ID="+ resultCacheId, connection))
            {
                var ds = new DataSet();
                da.Fill(ds);
                var binaryFormattedDs =(byte[]) ds.Tables[0].Rows[0]["Result_Binary_Data"];
                var ds2 = DeSerialize<DataSet>(binaryFormattedDs);
                Console.WriteLine("Row Count=" + ds2.Tables[0].Rows.Count);
            }

        }

    }

    public static T DeSerialize<T>(byte[] bytes)
    {
        var serializer = new BinaryFormatter();
        using (var ms = new MemoryStream())
        {
            ms.Write(bytes, 0, bytes.Length);
            ms.Seek(0, SeekOrigin.Begin);
            return (T)serializer.Deserialize(ms); //Exception ArgumentException: Type 'System.Byte' is not deserializable.
        }

    }

```



I get the same result if I use ADO or Entity Framework for data access in Core.

_Copied from original issue: dotnet/core#2344_

**Comment by joshfree** [comment]
@zhenlan @Lxiamail

**Comment by Lxiamail** [comment]
@joshfree BinaryFormatter in .NET Core is not owned by WCF team. I think it's owned by BCL.

**Comment by danmosemsft** [comment]
@viktorhofer owns it and can comment.

**Comment by ViktorHofer** [comment]
@bcbeatty can you please post the serialization payload that is generated with the .NET Core sample? More precisely speaking, this result. Please encode it as base64 (you can use this helper function: https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Runtime/Serialization/Formatters/BinaryFormatterHelpers.cs#L104):

```
var binaryFormattedDs =(byte[]) ds.Tables[0].Rows[0]["Result_Binary_Data"];
```

**Comment by bcbeatty** [comment]
It's pulling the payload created in Program 1, to populate a dataset. The actual content hasn't seemed to matter.

I changed this:
`using (var da = new SqlDataAdapter("Select * from Code_Job_Status", connection))`

to this, to remove any real database dependency on the source ,
`using (var da = new SqlDataAdapter("Select 1,2,3,'four' union select 4,5,6,'seven'", connection))`

and I get this exception:

> System.Reflection.TargetInvocationException
>   HResult=0x80131604
>   Message=Exception has been thrown by the target of an invocation.
>   Source=System.Private.CoreLib
>   StackTrace:
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
>    at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
>    at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
>    at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
>    at System.Runtime.Serialization.ObjectManager.DoFixups()
>    at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
>    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
>    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
>    at BSCore.Program.DeSerialize[T](Byte[] bytes) in C:\Source\Apps\Code\Source\BinarySerializer Solution\BSCore\Program.cs:line 57
>    at BSCore.Program.GetEF(Int32 resultCacheId) in C:\Source\Apps\Code\Source\BinarySerializer Solution\BSCore\Program.cs:line 67
>    at BSCore.Program.Main(String[] args) in C:\Source\Apps\Code\Source\BinarySerializer Solution\BSCore\Program.cs:line 22
> 
> Inner Exception 1:
> ArgumentException: Type 'System.Int32' is not deserializable.
>

**Comment by ViktorHofer** [comment]
Thanks, I will take a look.

**Comment by danmosemsft** [comment]
@ViktorHofer still planning to look here? should this remain 3.0

**Comment by danmosemsft** [comment]
Ping @viktorhofer, should this stay in 3.0

**Comment by tedekeroth** [comment]
It wasnt clear to me if BinaryFormatter is compatible with .NET Framework version? 'Type' objects cannot be serialized either, from what I understand. Can someone shed som light on this?

**Comment by ViktorHofer** [comment]
The list of cross-framework serializable types can be found here: https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization#binary-serialization-in-net-core

**Comment by DeneshPohar** [comment]
@ViktorHofer, what's the guidance when we have a lot of .NET Fx `BinaryFormatter` serialized content that contains types that are no longer `[Serializable]` (e.g., `ConcurrentDictionary` as per #28137), but we'd like to consume from a .NET Core 2.2 app?  Is there some way to upgrade these types on the .NET Core side, such that we can use all that legacy data generated from .NET Fx code?

**Comment by danmosemsft** [comment]
@DeneshPohar if it's only one or two types you might be able to make it work by defining your own surrogates (https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.surrogateselector?view=netframework-4.8)

However really what we would recommend is to use a different serialization mechanism. One thing to consider is whether you have cycles in your data - only some serializers support them. You may want to simplify what you serialize, in that case. In .NET Core 3.0+ we offer a serializer in the System.Text.Json namespace, which should work on .NET Framework and in 5.0 it will support cycles. That is one option.

**Comment by DeneshPohar** [comment]
Thanks @danmosemsft, `SurrogateSelector` works well for my narrow scenario.
