### ISSUE TITLE
Exception System.ObjectDisposedException: Safe handle has been closed  after unsuccessfully NTAccount.Translate 

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#35630]
_From @aboldarev on February 27, 2019 13:31_

# Exception System.ObjectDisposedException: Safe handle has been closed  after unsuccessfully unsuccessfully NTAccount.Translate 

An unsuccessfully  call  (new NTAccount("DOMAIN_NOT_EXISTS\Role").Translate(typeof(SecurityIdentifier));
 cause next calls to throw exception System.ObjectDisposedException: Safe handle has been closed  
# General

 I'm  using a System.Security.Principal.Windows (4.5.1), Microsoft.NETCore.App 2.2.0. 
 ```
  class Program
    {
        static string Translate(string gName)
        {
            try
            {
                var nt = new NTAccount(gName);
                if (nt.IsValidTargetType(typeof(SecurityIdentifier)))
                {
                    var si = (SecurityIdentifier)(nt).Translate(typeof(SecurityIdentifier));
                    return si.ToString();
                }
            }
            catch (Exception ex)
            { 
                Console.Write(ex.ToString()+"\n\n");                
            }
            return "";
        }
        static void Main(string[] args)
        {
            var si= new SecurityIdentifier(WellKnownSidType.BuiltinAdministratorsSid, null);
            var na = si.Translate(typeof(NTAccount));
            var knownName = na.ToString();
            foreach (var aName in new[] {  knownName,
                                           @"DOMAIN_NOT_ESISTS\Role",
                                           knownName  })
            {
                Console.WriteLine(aName);
                Console.WriteLine(Translate(aName));
            }
            Console.ReadKey();
        }
    }
```
I want to ask, is there some workaround, to fix this behavior. 

_Copied from original issue: dotnet/core#2343_

**Comment by bartonjs** [comment]
@aboldarev I just tried this on .NET Framework and on .NET Core 2.1 + System.Security.Principal.Windows (version) 4.6.0-preview.19073.11; and I don't see any ObjectDisposedExceptions.

What package version are you running, and what does `dotnet --info` say?

**Comment by bartonjs** [comment]
> What package version are you running

I see that I missed that: System.Security.Principal.Windows (4.5.1), Microsoft.NETCore.App 2.2.0.

I tried using the 4.5.1 version of the package and also don't get an exception.  Can you share your exception callstack?

**Comment by aboldarev** [comment]
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.104\

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by aboldarev** [comment]
a problem seems to appear only together with broken connection to domain controller. 
If a connection OK, the Program behaves as expected:

```
VORDEFINIERT\Administratoren
S-1-5-32-544
DOMAIN_NOT_ESISTS\Benutzer
System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at ConsoleApp2.Program.Translate(String gName) in C:\Users\oboldarev\source\delMe\ConsoleApp2\ConsoleApp2\Program.cs:line 16


ALEGRI\Mitarbeiter
S-1-5-21-1482476501-1580818891-854245398-3120
VORDEFINIERT\Administratoren
S-1-5-32-544
```


If I take off a computer from a net, I’ll get an exception for a valid account also and is still to throw exception until a restart of program. For an web application its critical, it couldn’t be restarted anytime. 
```
VORDEFINIERT\Administratoren
S-1-5-32-544
DOMAIN_NOT_ESISTS\Benutzer
System.ComponentModel.Win32Exception (1789): The trust relationship between this workstation and the primary domain failed
   at System.Security.Principal.NTAccount.TranslateToSids(IdentityReferenceCollection sourceAccounts, Boolean& someFailed)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean& someFailed)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at ConsoleApp2.Program.Translate(String gName) in C:\Users\oboldarev\source\delMe\ConsoleApp2\ConsoleApp2\Program.cs:line 16


ALEGRI\Mitarbeiter
System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Advapi32.LsaLookupNames2(SafeLsaPolicyHandle handle, Int32 flags, Int32 count, UNICODE_STRING[] names, SafeLsaMemoryHandle& referencedDomains, SafeLsaMemoryHandle& sids)
   at System.Security.Principal.NTAccount.TranslateToSids(IdentityReferenceCollection sourceAccounts, Boolean& someFailed)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean& someFailed)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at ConsoleApp2.Program.Translate(String gName) in C:\Users\oboldarev\source\delMe\ConsoleApp2\ConsoleApp2\Program.cs:line 16


VORDEFINIERT\Administratoren
System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Advapi32.LsaLookupNames2(SafeLsaPolicyHandle handle, Int32 flags, Int32 count, UNICODE_STRING[] names, SafeLsaMemoryHandle& referencedDomains, SafeLsaMemoryHandle& sids)
   at System.Security.Principal.NTAccount.TranslateToSids(IdentityReferenceCollection sourceAccounts, Boolean& someFailed)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean& someFailed)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at ConsoleApp2.Program.Translate(String gName) in C:\Users\oboldarev\source\delMe\ConsoleApp2\ConsoleApp2\Program.cs:line 16

```

**Comment by bartonjs** [comment]
I've just tested this again with 3.0 master, and on both Windows 7 and Windows 10 the ObjectDisposedException is no longer present.

It looks like got fixed in PR https://github.com/dotnet/corefx/pull/32786 for the bug variant https://github.com/dotnet/corefx/issues/32636.

You could try again with package version 4.6.0-preview5.19224.8, which should have the fix.
