### ISSUE TITLE
test nano

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#35668]
This issue tracks the Linux failures on `Save_SimpleSettings_Ok`, a test that is added in PR https://github.com/dotnet/corefx/pull/28894.
The Linux issue may be something weird about how our machines are configured on our CI machines.

Failing on Linux with:
```
2018-06-12 18:36:32,792: INFO: proc(54): run_and_log_output: Output:    System.ConfigurationTests.ApplicationSettingsBaseTests.Save_SimpleSettings_Ok(isSynchronized: True) [FAIL]
2018-06-12 18:36:32,794: INFO: proc(54): run_and_log_output: Output:       System.Configuration.ConfigurationErrorsException : Failed to save settings: An error occurred loading a configuration file: An unexpected error occurred in 'ClientConfigurationHost::OpenStreamForWrite '' '''.
2018-06-12 18:36:32,795: INFO: proc(54): run_and_log_output: Output:       ---- System.Configuration.ConfigurationErrorsException : An error occurred loading a configuration file: An unexpected error occurred in 'ClientConfigurationHost::OpenStreamForWrite '' '''.
2018-06-12 18:36:32,795: INFO: proc(54): run_and_log_output: Output:       -------- System.InvalidOperationException : An unexpected error occurred in 'ClientConfigurationHost::OpenStreamForWrite '' '''.
2018-06-12 18:36:32,803: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-06-12 18:36:32,836: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Configuration.ConfigurationManager/src/System/Configuration/ClientSettingsStore.cs(209,0): at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
2018-06-12 18:36:32,837: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Configuration.ConfigurationManager/src/System/Configuration/LocalFileSettingsProvider.cs(220,0): at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
2018-06-12 18:36:32,837: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Configuration.ConfigurationManager/src/System/Configuration/SettingsBase.cs(129,0): at System.Configuration.SettingsBase.SaveCore()
2018-06-12 18:36:32,838: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Configuration.ConfigurationManager/src/System/Configuration/SettingsBase.cs(115,0): at System.Configuration.SettingsBase.Save()
2018-06-12 18:36:32,838: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Configuration.ConfigurationManager/tests/System/Configuration/ApplicationSettingsBaseTests.cs(135,0): at System.ConfigurationTests.ApplicationSettingsBaseTests.Save_SimpleSettings_Ok(Boolean isSynchronized)
2018-06-12 18:36:32,838: INFO: proc(54): run_and_log_output: Output:          ----- Inner Stack Trace -----
2018-06-12 18:36:32,840: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Configuration.ConfigurationManager/src/System/Configuration/MgmtConfigurationRecord.cs(1098,0): at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
2018-06-12 18:36:32,840: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Configuration.ConfigurationManager/src/System/Configuration/ClientSettingsStore.cs(204,0): at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
2018-06-12 18:36:32,840: INFO: proc(54): run_and_log_output: Output:          ----- Inner Stack Trace -----
2018-06-12 18:36:32,840: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigurationHost.cs(312,0): at System.Configuration.ClientConfigurationHost.OpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext)
2018-06-12 18:36:32,841: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Configuration.ConfigurationManager/src/System/Configuration/MgmtConfigurationRecord.cs(1062,0): at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
2018-06-12 18:36:32,843: INFO: proc(54): run_and_log_output: Output:    System.ConfigurationTests.ApplicationSettingsBaseTests.Save_SimpleSettings_Ok(isSynchronized: False) [FAIL]
2018-06-12 18:36:32,843: INFO: proc(54): run_and_log_output: Output:       System.Configuration.ConfigurationErrorsException : Failed to save settings: An error occurred loading a configuration file: An unexpected error occurred in 'ClientConfigurationHost::OpenStreamForWrite '' '''.
2018-06-12 18:36:32,843: INFO: proc(54): run_and_log_output: Output:       ---- System.Configuration.ConfigurationErrorsException : An error occurred loading a configuration file: An unexpected error occurred in 'ClientConfigurationHost::OpenStreamForWrite '' '''.
2018-06-12 18:36:32,843: INFO: proc(54): run_and_log_output: Output:       -------- System.InvalidOperationException : An unexpected error occurred in 'ClientConfigurationHost::OpenStreamForWrite '' '''.
2018-06-12 18:36:32,844: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-06-12 18:36:32,844: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Configuration.ConfigurationManager/src/System/Configuration/ClientSettingsStore.cs(209,0): at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
2018-06-12 18:36:32,844: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Configuration.ConfigurationManager/src/System/Configuration/LocalFileSettingsProvider.cs(220,0): at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
2018-06-12 18:36:32,844: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Configuration.ConfigurationManager/src/System/Configuration/SettingsBase.cs(129,0): at System.Configuration.SettingsBase.SaveCore()
2018-06-12 18:36:32,849: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Configuration.ConfigurationManager/src/System/Configuration/SettingsBase.cs(122,0): at System.Configuration.SettingsBase.Save()
2018-06-12 18:36:32,849: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Configuration.ConfigurationManager/tests/System/Configuration/ApplicationSettingsBaseTests.cs(135,0): at System.ConfigurationTests.ApplicationSettingsBaseTests.Save_SimpleSettings_Ok(Boolean isSynchronized)
2018-06-12 18:36:32,849: INFO: proc(54): run_and_log_output: Output:          ----- Inner Stack Trace -----
2018-06-12 18:36:32,850: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Configuration.ConfigurationManager/src/System/Configuration/MgmtConfigurationRecord.cs(1098,0): at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
2018-06-12 18:36:32,850: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Configuration.ConfigurationManager/src/System/Configuration/ClientSettingsStore.cs(204,0): at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
2018-06-12 18:36:32,850: INFO: proc(54): run_and_log_output: Output:          ----- Inner Stack Trace -----
2018-06-12 18:36:32,851: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigurationHost.cs(312,0): at System.Configuration.ClientConfigurationHost.OpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext)
2018-06-12 18:36:32,851: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Configuration.ConfigurationManager/src/System/Configuration/MgmtConfigurationRecord.cs(1062,0): at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
```

(Taken from comment https://github.com/dotnet/corefx/pull/28894#issuecomment-396789297)

**Comment by ViktorHofer** [comment]
Failed again, this time on Windows 7: https://dev.azure.com/dnceng/public/_build/results?buildId=358032&view=ms.vss-test-web.build-test-results-tab&runId=10839480&resultId=105888&paneView=debug

Configuration: `netcoreapp-Windows_NT-Release-x86-Windows.7.Amd64.Open`

```
System.ConfigurationTests.ApplicationSettingsBaseTests.Save_SimpleSettings_Ok(isSynchronized: False)

System.Configuration.ConfigurationErrorsException : An error occurred creating the configuration section handler for userSettings/System.ConfigurationTests.ApplicationSettingsBaseTests_x002B_PersistedSimpleSettings: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified. (C:\\Users\\runner\\AppData\\Local\\Microsoft_Corporation\\xunit.console_StrongName_vmuqnj1rm2vzmtjlxpznjgrpuvgx0hav\\2.5.1.0\\user.config line 5)\r\n---- System.IO.FileNotFoundException : Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

   at System.Configuration.BaseConfigurationRecord.FindAndEnsureFactoryRecord(String configKey, Boolean& isRootDeclaredHere) in /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs:line 1740
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject) in /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs:line 875
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey, Boolean getLkg, Boolean checkPermission) in /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs:line 757
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey) in /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs:line 258
   at System.Configuration.Configuration.GetSection(String sectionName) in /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/Configuration.cs:line 168
   at System.Configuration.ClientSettingsStore.GetConfigSection(Configuration config, String sectionName, Boolean declare) in /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/ClientSettingsStore.cs:line 43
   at System.Configuration.ClientSettingsStore.RevertToParent(String sectionName, Boolean isRoaming) in /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/ClientSettingsStore.cs:line 163
   at System.Configuration.LocalFileSettingsProvider.Reset(SettingsContext context) in /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/LocalFileSettingsProvider.cs:line 232
   at System.Configuration.ApplicationSettingsBase.Reset() in /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/ApplicationSettingsBase.cs:line 371
   at System.ConfigurationTests.ApplicationSettingsBaseTests.Save_SimpleSettings_Ok(Boolean isSynchronized) in /_/src/System.Configuration.ConfigurationManager/tests/System/Configuration/ApplicationSettingsBaseTests.cs:line 113
----- Inner Stack Trace -----
   at System.Configuration.TypeUtil.GetType(IInternalConfigHost host, String typeString, Boolean throwOnError) in /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/TypeUtil.cs:line 132
   at System.Configuration.MgmtConfigurationRecord.CreateSectionFactory(FactoryRecord factoryRecord) in /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/MgmtConfigurationRecord.cs:line 128
   at System.Configuration.BaseConfigurationRecord.FindAndEnsureFactoryRecord(String configKey, Boolean& isRootDeclaredHere) in /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs:line 1735
```

**Comment by ViktorHofer** [comment]
@maryamariyan, @safern

**Comment by bartonjs** [comment]
Failed on Windows7 and Windows8.1 with perhaps a new kind of error.

https://dev.azure.com/dnceng/public/_build/results?buildId=368747&view=ms.vss-test-web.build-test-results-tab&runId=11204916&resultId=100515&paneView=debug

```
System.ConfigurationTests.ApplicationSettingsBaseTests.Save_SimpleSettings_Ok(isSynchronized: True) [FAIL]
      System.Configuration.ConfigurationErrorsException : An error occurred creating the configuration section handler for userSettings/System.ConfigurationTests.ApplicationSettingsBaseTests_x002B_PersistedSimpleSettings: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified. (C:\Users\runner\AppData\Local\Microsoft_Corporation\xunit.console_StrongName_vmuqnj1rm2vzmtjlxpznjgrpuvgx0hav\2.5.1.0\user.config line 5)
      ---- System.IO.FileNotFoundException : Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
      Stack Trace:
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs(1740,0): at System.Configuration.BaseConfigurationRecord.FindAndEnsureFactoryRecord(String configKey, Boolean& isRootDeclaredHere)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs(875,0): at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs(757,0): at System.Configuration.BaseConfigurationRecord.GetSection(String configKey, Boolean getLkg, Boolean checkPermission)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs(258,0): at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/Configuration.cs(168,0): at System.Configuration.Configuration.GetSection(String sectionName)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/ClientSettingsStore.cs(43,0): at System.Configuration.ClientSettingsStore.GetConfigSection(Configuration config, String sectionName, Boolean declare)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/ClientSettingsStore.cs(163,0): at System.Configuration.ClientSettingsStore.RevertToParent(String sectionName, Boolean isRoaming)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/LocalFileSettingsProvider.cs(232,0): at System.Configuration.LocalFileSettingsProvider.Reset(SettingsContext context)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/ApplicationSettingsBase.cs(371,0): at System.Configuration.ApplicationSettingsBase.Reset()
        /_/src/System.Configuration.ConfigurationManager/tests/System/Configuration/ApplicationSettingsBaseTests.cs(113,0): at System.ConfigurationTests.ApplicationSettingsBaseTests.Save_SimpleSettings_Ok(Boolean isSynchronized)
        ----- Inner Stack Trace -----
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/TypeUtil.cs(133,0): at System.Configuration.TypeUtil.GetType(IInternalConfigHost host, String typeString, Boolean throwOnError)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/MgmtConfigurationRecord.cs(128,0): at System.Configuration.MgmtConfigurationRecord.CreateSectionFactory(FactoryRecord factoryRecord)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs(1735,0): at System.Configuration.BaseConfigurationRecord.FindAndEnsureFactoryRecord(String configKey, Boolean& isRootDeclaredHere)
    System.ConfigurationTests.ApplicationSettingsBaseTests.Save_SimpleSettings_Ok(isSynchronized: False) [FAIL]
      System.Configuration.ConfigurationErrorsException : An error occurred creating the configuration section handler for userSettings/System.ConfigurationTests.ApplicationSettingsBaseTests_x002B_PersistedSimpleSettings: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified. (C:\Users\runner\AppData\Local\Microsoft_Corporation\xunit.console_StrongName_vmuqnj1rm2vzmtjlxpznjgrpuvgx0hav\2.5.1.0\user.config line 5)
      ---- System.IO.FileNotFoundException : Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
      Stack Trace:
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs(1740,0): at System.Configuration.BaseConfigurationRecord.FindAndEnsureFactoryRecord(String configKey, Boolean& isRootDeclaredHere)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs(875,0): at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs(757,0): at System.Configuration.BaseConfigurationRecord.GetSection(String configKey, Boolean getLkg, Boolean checkPermission)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs(258,0): at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/Configuration.cs(168,0): at System.Configuration.Configuration.GetSection(String sectionName)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/ClientSettingsStore.cs(43,0): at System.Configuration.ClientSettingsStore.GetConfigSection(Configuration config, String sectionName, Boolean declare)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/ClientSettingsStore.cs(163,0): at System.Configuration.ClientSettingsStore.RevertToParent(String sectionName, Boolean isRoaming)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/LocalFileSettingsProvider.cs(232,0): at System.Configuration.LocalFileSettingsProvider.Reset(SettingsContext context)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/ApplicationSettingsBase.cs(371,0): at System.Configuration.ApplicationSettingsBase.Reset()
        /_/src/System.Configuration.ConfigurationManager/tests/System/Configuration/ApplicationSettingsBaseTests.cs(113,0): at System.ConfigurationTests.ApplicationSettingsBaseTests.Save_SimpleSettings_Ok(Boolean isSynchronized)
        ----- Inner Stack Trace -----
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/TypeUtil.cs(133,0): at System.Configuration.TypeUtil.GetType(IInternalConfigHost host, String typeString, Boolean throwOnError)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/MgmtConfigurationRecord.cs(128,0): at System.Configuration.MgmtConfigurationRecord.CreateSectionFactory(FactoryRecord factoryRecord)
        /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs(1735,0): at System.Configuration.BaseConfigurationRecord.FindAndEnsureFactoryRecord(String configKey, Boolean& isRootDeclaredHere)
```
