### ISSUE TITLE
NullReferenceException in System.Net.Sockets.Tests.Disconnect.Success on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3580]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/4466/console
```C#
Discovering: System.Net.Sockets.AsyncServer.Tests
  Discovered:  System.Net.Sockets.AsyncServer.Tests
  Starting:    System.Net.Sockets.AsyncServer.Tests
     System.Net.Sockets.Tests.Disconnect.Success [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Windows.cs(86,0): at System.Net.Sockets.Socket.DisconnectExBlocking(IntPtr socketHandle, IntPtr overlapped, Int32 flags, Int32 reserved)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\SocketPal.Windows.cs(156,0): at System.Net.Sockets.SocketPal.Disconnect(Socket socket, SafeCloseSocket handle, Boolean reuseSocket)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(2600,0): at System.Net.Sockets.Socket.Disconnect(Boolean reuseSocket)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets.Legacy\tests\FunctionalTests\Disconnect.cs(42,0): at System.Net.Sockets.Tests.Disconnect.Success()
  Finished:    System.Net.Sockets.AsyncServer.Tests
```
cc: @davidsh, @cipop, @pgavlin

**Comment by stephentoub** [comment]
Failed again here: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/4552/console

**Comment by stephentoub** [comment]
Failed again here: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/4775/console
```
System.Net.Sockets.Tests.Disconnect.Success [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
  System.Threading.Tests -> d:\j\workspace\dotnet_corefx_windows_release_prtest\bin\Windows_NT.AnyCPU.Release\System.Threading.Tests\System.Threading.Tests.dll
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Windows.cs(86,0): at System.Net.Sockets.Socket.DisconnectExBlocking(IntPtr socketHandle, IntPtr overlapped, Int32 flags, Int32 reserved)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets\src\System\Net\Sockets\SocketPal.Windows.cs(147,0): at System.Net.Sockets.SocketPal.Disconnect(Socket socket, SafeCloseSocket handle, Boolean reuseSocket)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(2587,0): at System.Net.Sockets.Socket.Disconnect(Boolean reuseSocket)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets.Legacy\tests\FunctionalTests\Disconnect.cs(42,0): at System.Net.Sockets.Tests.Disconnect.Success()
```

**Comment by weshaggard** [comment]
Failed again:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/4839/console

```
 System.Net.Sockets.Tests.Disconnect.Success [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Windows.cs(86,0): at System.Net.Sockets.Socket.DisconnectExBlocking(IntPtr socketHandle, IntPtr overlapped, Int32 flags, Int32 reserved)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\SocketPal.Windows.cs(150,0): at System.Net.Sockets.SocketPal.Disconnect(Socket socket, SafeCloseSocket handle, Boolean reuseSocket)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(2603,0): at System.Net.Sockets.Socket.Disconnect(Boolean reuseSocket)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets.Legacy\tests\FunctionalTests\Disconnect.cs(42,0): at System.Net.Sockets.Tests.Disconnect.Success()
```

**Comment by CIPop** [comment]
`Disconnect` has been removed from the API surface and so this is not applicable anymore.
