### ISSUE TITLE
HttpWebRequest.Timeout is silently limited to 21 seconds when server does not respond

### ISSUE THREAD

**Issue by loop-evgeny** [dotnet/corefx#35889]
.NET Core 2.1.8 on Windows 7 x64

Similar to #35888, but for HttpWebRequest. In this case timeouts up to 21 seconds are honoured, but not beyond that - `HttpWebRequest.GetResponse()` throws an exception after at most 21 seconds.

C# code to reproduce:

```
            var request = (HttpWebRequest)WebRequest.Create("http://10.99.99.99/"); // A non-existent IP address

            request.Timeout = 30000; // This makes a difference up to 21 seconds, but not beyond that

            var stopwatch = Stopwatch.StartNew();
            WebResponse response;

            try
            {
                response = request.GetResponse();
                Console.WriteLine("HTTP response received after " + stopwatch.Elapsed);
            }
            catch (Exception ex)
            {
                Console.WriteLine("HTTP request failed after " + stopwatch.Elapsed);
                Console.WriteLine(ex);
            }
```

Output:

```
HTTP request failed after 00:00:21.0679283
System.Net.WebException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected
 host has failed to respond A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connec
ted host has failed to respond ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, o
r established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did no
t properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at CoreConsoleApp1.WebRequestTest.TestHttpTimeout() in C:\W ork\Play\CoreConsoleApp1\WebRequestTest.cs:line 28
```

**Comment by davidsh** [comment]
The 21 second timeout is a fixed timeout in Winsock on Windows.  There is a timeout for establishing the TCP 3-leg handshake (SYN, SYN-ACK, ACK).  There is no control over changing that.  Usually this timeout occurs when the server is very busy and can't even establish a TCP handshake.

There is a similar issue opened before in this repo about this already.

**Comment by davidsh** [comment]
See issues: #34095 #31951

**Comment by loop-evgeny** [comment]
OK, fair enough, but setting a timeout value that's not supported should throw an exception - it should not just be silently ignored. At minimum this needs to be documented.
