### ISSUE TITLE
DateTimeFormatInfo.AbbreviatedDayNames does not clone the `value` when set, causing problems

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#35942]
E.g. 
```cs
var value = new string[] { "1", "2", "3", "4", "5", "6", "7" };
var culture = new DateTimeFormatInfo
{
    AbbreviatedDayNames = value
};
value[0] = null;

Console.WriteLine(new DateTime(2014, 5, 28).ToString("ddd MMM dd, yyyy", format));
```

This throws a `NullReferenceException`:
```
      System.Globalization.Tests.DateTimeFormatInfoAbbreviatedDayNames.AbbreviatedDayNames_Format [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
          /Users/vsts/agent/2.147.1/work/1/s/src/System.Private.CoreLib/shared/System/Globalization/DateTimeFormatInfoScanner.cs(660,0): at System.Globalization.DateTimeFormatInfoScanner.ArrayElementsHaveSpace(String[] array)
          /Users/vsts/agent/2.147.1/work/1/s/src/System.Private.CoreLib/shared/System/Globalization/DateTimeFormatInfoScanner.cs(597,0): at System.Globalization.DateTimeFormatInfoScanner.GetFormatFlagUseSpaceInDayNames(String[] dayNames, String[] abbrevDayNames)
          /Users/vsts/agent/2.147.1/work/1/s/src/System.Private.CoreLib/shared/System/Globalization/DateTimeFormatInfo.cs(2110,0): at System.Globalization.DateTimeFormatInfo.InitializeFormatFlags()
          /Users/vsts/agent/2.147.1/work/1/s/src/System.Private.CoreLib/shared/System/Globalization/DateTimeFormat.cs(633,0): at System.DateTimeFormat.FormatCustomized(DateTime dateTime, ReadOnlySpan`1 format, DateTimeFormatInfo dtfi, TimeSpan offset, StringBuilder result)
          /Users/vsts/agent/2.147.1/work/1/s/src/System.Private.CoreLib/shared/System/Globalization/DateTimeFormat.cs(1134,0): at System.DateTimeFormat.FormatStringBuilder(DateTime dateTime, ReadOnlySpan`1 format, DateTimeFormatInfo dtfi, TimeSpan offset)
          /Users/vsts/agent/2.147.1/work/1/s/src/System.Private.CoreLib/shared/System/Globalization/DateTimeFormat.cs(1013,0): at System.DateTimeFormat.Format(DateTime dateTime, String format, IFormatProvider provider, TimeSpan offset)
          /Users/vsts/agent/2.147.1/work/1/s/src/System.Private.CoreLib/shared/System/Globalization/DateTimeFormat.cs(1008,0): at System.DateTimeFormat.Format(DateTime dateTime, String format, IFormatProvider provider)
          /Users/vsts/agent/2.147.1/work/1/s/src/System.Private.CoreLib/shared/System/DateTime.cs(1408,0): at System.DateTime.ToString(String format, IFormatProvider provider)
          /Users/hugh/Documents/GitHub/corefx/src/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoAbbreviatedDayNames.cs(93,0): at System.Globalization.Tests.DateTimeFormatInfoAbbreviatedDayNames.AbbreviatedDayNames_Format()
    Finished:    System.Globalization.Tests
  === TEST EXECUTION SUMMARY ===
     System.Globalization.Tests  Total: 1675, Errors: 0, Failed: 1, Skipped: 0, Time: 4.370s
```

**Comment by hughbe** [comment]
Same with `AbbreviatedMonthNames`:
```cs
[Fact]
public void AbbreviatedMonthNames_FormatWithNull_ThrowsNullReferenceException()
{
    var value = new string[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13" };
    var format = new DateTimeFormatInfo
    {
        AbbreviatedMonthNames = value
    };
    value[0] = null;

    var dateTime = new DateTime(2014, 1, 28);
    Assert.Throws<NullReferenceException>(() => dateTime.ToString("ddd MMM dd, yyyy", format));
}
```

**Comment by hughbe** [comment]
And `AbbreviatedMonthGenitiveNames`:
```cs
[Fact]
public void AbbreviatedMonthGenitiveNames_FormatWithNull_ThrowsNullReferenceException()
{
    var value = new string[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13" };
    var format = new DateTimeFormatInfo
    {
        AbbreviatedMonthGenitiveNames = value
    };
    value[0] = null;

    var dateTime = new DateTime(2014, 1, 28);
    Assert.Throws<NullReferenceException>(() => dateTime.ToString("dd MMM yy", format));
}
```

**Comment by hughbe** [comment]
And `DayNames`:
```cs
[Fact]
public void DayNames_FormatWithNull_ThrowsNullReferenceException()
{
    var value = new string[] { "1", "2", "3", "4", "5", "6", "7" };
    var format = new DateTimeFormatInfo
    {
        DayNames = value
    };
    value[0] = null;

    var dateTime = new DateTime(2014, 5, 28);
    Assert.Throws<NullReferenceException>(() => dateTime.ToString("dddd MMM yy", format));
}
```

**Comment by hughbe** [comment]
And `MonthGenitiveNames`:
```cs
[Fact]
public void MonthGenitiveNames_FormatWithNull_ThrowsNullReferenceException()
{
    var value = new string[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13" };
    var format = new DateTimeFormatInfo
    {
        MonthGenitiveNames = value
    };
    value[0] = null;

    var dateTime = new DateTime(2014, 1, 28);
    Assert.Throws<NullReferenceException>(() => dateTime.ToString("dd MMMM", format));
}
```

**Comment by hughbe** [comment]
And `MonthNames`

```cs
[Fact]
public void MonthNames_FormatWithNull_ThrowsNullReferenceException()
{
    var value = new string[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13" };
    var format = new DateTimeFormatInfo
    {
        MonthNames = value
    };
    value[0] = null;

    var dateTime = new DateTime(2014, 1, 28);
    Assert.Throws<NullReferenceException>(() => dateTime.ToString("MMMM", format));
}
```

**Comment by tarekgh** [comment]
I don't think we need to change that. this will have a perf impact but cloning such values. We can just clarify the behavior in the docs.

**Comment by tarekgh** [comment]
@hughbe I suggest to open a doc issue to clarify the behavior in the docs and not to change the current behavior. Thanks for reporting the issue.
