### ISSUE TITLE
System.Net.Sockets.Tests.SendFileTest.SendFile_APM test failed with strange error 

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#35965]
This happened to me once when running on Azure image of openSUSE 42.3, created by reprotool. 

I do see tests once in a while failing because they received less than expected bytes. 
In this case, test received MORE than expected.

```
 /mnt/resource/workspace/Work/68232d9a-1280-4ee4-99a6-a421449a593e/Exec /mnt/resource/workspace/Work/68232d9a-1280-4ee4-99a6-a421449a593e/Exec
  Discovering: System.Net.Sockets.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Sockets.Tests (found 969 of 1054 test cases)
  Starting:    System.Net.Sockets.Tests (parallel test collections = on, max threads = 4)
    System.Net.Sockets.Tests.KeepAliveTest.Socket_KeepAlive_RetryCount_Failure [SKIP]
      Condition(s) not met: "IsWindowsBelow1703"
    System.Net.Sockets.Tests.UnixDomainSocketTest.Socket_CreateUnixDomainSocket_Throws_OnWindows [SKIP]
      Condition(s) not met: "IsSubWindows10"
    System.Net.Sockets.Tests.CreateSocket.Ctor_Raw_Supported_Success [SKIP]
      Condition(s) not met: "SupportsRawSockets"
    System.Net.Sockets.Tests.SendFileTest.SendFile_APM(listenAt: 127.0.0.1, sendPreAndPostBuffers: False, bytesToSend: 12345678) [FAIL]
      Assert.Equal() Failure
      Expected: 12345678
      Actual:   12345679
      Stack Trace:
        /mnt/github/wfurt-corefx/src/System.Net.Sockets/tests/FunctionalTests/SendFile.cs(234,0): at System.Net.Sockets.Tests.SendFileTest.SendFile_APM(IPAddress listenAt, Boolean sendPreAndPostBuffers, Int32 bytesToSend)
        --- End of stack trace from previous location where exception was thrown ---
  Finished:    System.Net.Sockets.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Sockets.Tests  Total: 1434, Errors: 0, Failed: 1, Skipped: 3, Time: 42.608s
```

**Comment by karelz** [comment]
@wfurt can you please look at Kusto. If it didn't fail again, let's close it.

**Comment by wfurt** [comment]
I did not find any reoccurrence of this in CI. 
This test failed 4x with Timeout on windows.10.amd64.client19h1.open in last 90 days.

**Comment by karelz** [comment]
@wfurt what are the 4 failures? How do they relate to CI?

**Comment by wfurt** [comment]
They are simple timeouts. e.g. not "strange" error when  we receive more than we send. 
```
System.TimeoutException   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 75
   at System.Net.Sockets.Tests.SendFileTest.SendFile_APM(IPAddress listenAt, Boolean sendPreAndPostBuffers, Int32 bytesToSend) in /_/src/System.Net.Sockets/tests/FunctionalTests/SendFile.cs:line 234
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by karelz** [comment]
I don't follow. Either the test has to expect the timeout, or we have a problem somewhere, don't we?
What am I missing?

**Comment by wfurt** [comment]
generally yes, test should not timeout. I consider 4 failures as noice and the failure was quite different than this issue. If we see more frequent timeouts/failure we should open new issue with appropriate details. 
I hope this makes more sense.
