### ISSUE TITLE
JsonSerializer does not support parsing Dictionary<TKey, TValue>

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#36024]
**Runtime version:** 3.0.0-preview4-27513-05

Consider:

```C#
var content = "{ \"key\": \"value\" }";
var result = JsonSerializer.Parse(content, typeof(Dictionary<string, string>));
```

This results in the following exception:

```C#
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Text.Json.Serialization.JsonSerializer.HandleStartObject(JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializer.Parse(String json, Type returnType, JsonSerializerOptions options)
```

**Comment by ahsonkhan** [comment]
Dictionary is not currently supported with the WIP `JsonSerializer`.

**Comment by anurse** [comment]
For the initial version to unblock ASP.NET, `Dictionary<string, [some concrete type]>` is sufficient.

**Comment by layomia** [comment]
Working on this now.

**Comment by layomia** [comment]
We have added support for primitives: `Dictionary<string, TPrimitiveType>`.
It also includes support for `IDictionary<string, TPrimitiveType>` and `IReadOnlyDictionary<string, TPrimitiveType>` where an instance of Dictionary<string, TPrimitiveType> is created.

Support for non-primitives is being tracked here: https://github.com/dotnet/corefx/issues/37077.
