### ISSUE TITLE
CertificateValidationRemoteServer_EndToEnd_Ok failing on Windows 7

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#36028]
Found during CI test of PR #36018

Test:  System.Net.Security.Tests.CertificateValidationRemoteServer/CertificateValidationRemoteServer_EndToEnd_Ok

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F36018~2Fmerge/test~2Ffunctional~2Fcli~2F/20190313.35/workItem/System.Net.Security.Tests/analysis/xunit/System.Net.Security.Tests.CertificateValidationRemoteServer~2FCertificateValidationRemoteServer_EndToEnd_Ok

>System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
---- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.

>   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error) in D:\a\1\s\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs:line 1085
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token) in D:\a\1\s\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs:line 1059
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request) in D:\a\1\s\src\System.Net.Security\src\System\Net\FixedSizeReader.cs:line 57
   at System.Net.Security.SslState.ThrowIfExceptional() in D:\a\1\s\src\System.Net.Security\src\System\Net\Security\SslState.cs:line 96
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult) in D:\a\1\s\src\System.Net.Security\src\System\Net\Security\SslState.cs:line 735
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result) in D:\a\1\s\src\System.Net.Security\src\System\Net\Security\SslState.cs:line 705
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult) in D:\a\1\s\src\System.Net.Security\src\System\Net\Security\SslStream.cs:line 220
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__45_1(IAsyncResult iar) in D:\a\1\s\src\System.Net.Security\src\System\Net\Security\SslStream.cs:line 367
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) in F:\vsagent\44\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\FutureFactory.cs:line 520
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.Tests.CertificateValidationRemoteServer.CertificateValidationRemoteServer_EndToEnd_Ok() in D:\a\1\s\src\System.Net.Security\tests\FunctionalTests\CertificateValidationRemoteServer.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----

**Comment by davidsh** [comment]
Turns out this was caused by a mis-configuration of the new Azure endpoint. It was requiring TLS 1.2 and that is not supported by default on Windows 7.
