### ISSUE TITLE
Microsoft.VisualBasic.Tests.StringsTests.Chr_CharCodeOutOfRange_ThrowsNotSupportedException test failure

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/corefx#36070]
```xml
  <test name="Microsoft.VisualBasic.Tests.StringsTests.Chr_CharCodeOutOfRange_ThrowsNotSupportedException(charCode: -1)" type="Microsoft.VisualBasic.Tests.StringsTests" method="Chr_CharCodeOutOfRange_ThrowsNotSupportedException" time="0.0912179" result="Fail">
    <failure exception-type="Xunit.Sdk.ThrowsException">
      <message><![CDATA[Assert.Throws() Failure\r\nExpected: typeof(System.ArgumentException)\r\nActual:   (No exception was thrown)]]></message>
      <stack-trace><![CDATA[   at System.AssertExtensions.Throws[T](String paramName, Func`1 testCode) in C:\Users\gotos\source\repos\corefx2\src\CoreFx.Private.TestUtilities\src\System\AssertExtensions.cs:line 84
at Microsoft.VisualBasic.Tests.StringsTests.Chr_CharCodeOutOfRange_ThrowsNotSupportedException(Int32 charCode) in C:\Users\gotos\source\repos\corefx2\src\Microsoft.VisualBasic.Core\tests\StringsTests.cs:line 79]]></stack-trace>
    </failure>
  </test>
  <test name="Microsoft.VisualBasic.Tests.StringsTests.Chr_CharCodeOutOfRange_ThrowsNotSupportedException(charCode: 256)" type="Microsoft.VisualBasic.Tests.StringsTests" method="Chr_CharCodeOutOfRange_ThrowsNotSupportedException" time="0.0007974" result="Fail">
    <failure exception-type="Xunit.Sdk.ThrowsException">
      <message><![CDATA[Assert.Throws() Failure\r\nExpected: typeof(System.ArgumentException)\r\nActual:   (No exception was thrown)]]></message>
      <stack-trace><![CDATA[   at System.AssertExtensions.Throws[T](String paramName, Func`1 testCode) in C:\Users\gotos\source\repos\corefx2\src\CoreFx.Private.TestUtilities\src\System\AssertExtensions.cs:line 84
at Microsoft.VisualBasic.Tests.StringsTests.Chr_CharCodeOutOfRange_ThrowsNotSupportedException(Int32 charCode) in C:\Users\gotos\source\repos\corefx2\src\Microsoft.VisualBasic.Core\tests\StringsTests.cs:line 79]]></stack-trace>
    </failure>
  </test>
```
Korean Windows 10 1809 x64, with Visual Studio 2019 RC2 installed. Ran through Dev. Command prompt for VS2019 with command `build & build -buildtests -test`.

Was able to reproduce on three different Windows (two physical, one VM with Japanese Windows 10 installed).

**Comment by Gnbrkm41** [comment]
Just wondering, is it only me that can't open the `Microsoft.VisualBasic.Core.Tests.csproj` project properly? VS is showing me a bunch of CS0518 "Predefined type 'System.*' is not defined or imported" errors. Can't really debug it since it won't build with all these errors.

**Comment by Gnbrkm41** [comment]
It also is showing some NETSDK errors like "The TargetFramework value '' was not recognized" as one of the solution-wide errors sometimes (not showing up at the moment for some reason), I had it forked/cloned fresh from the latest commit.

**Comment by Gnbrkm41** [comment]
![image](https://user-images.githubusercontent.com/42944058/54478242-4f36fd00-4853-11e9-9580-37531f8185d8.png)
