### ISSUE TITLE
ReallyLargeLookup json tests consistently failing in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#36095]
ReallyLargeLookupUTF16 is failing every leg, and ReallyLargeLookupUTF8 is failing some.
![image](https://user-images.githubusercontent.com/2642209/54483311-5f38e780-4827-11e9-9157-220717cfca34.png)

The failures manifest in a few ways, e.g.
```
Windows.10.Amd64.ClientRS5.Open-x64-Debug 
Get Repro environment 
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Expected OverflowException was not thrown when calling TextEquals with large lookup string
Expected: True
Actual:   False
Stack Trace :
   at System.Text.Json.Tests.Utf8JsonReaderTests.ReallyLargeLookupUTF16() in D:\a\1\s\src\System.Text.Json\tests\Utf8JsonReaderTests.TextEquals.cs:line 553
```
and
```
Windows.10.Amd64.ClientRS4.ES.Open-x86-Release 
Get Repro environment 
Unhandled Exception of Type System.OutOfMemoryException
Message :
System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
Stack Trace :
   at System.String.Ctor(Char c, Int32 count) in F:\vsagent\44\s\src\System.Private.CoreLib\shared\System\String.cs:line 289
   at System.Text.Json.Tests.Utf8JsonReaderTests.ReallyLargeLookupUTF16() in D:\a\1\s\src\System.Text.Json\tests\Utf8JsonReaderTests.TextEquals.cs:line 538
```

Also, ReallyLargeLookupUTF8 should really be made outerloop, given that it allocates a 2GB string.

**Comment by stephentoub** [comment]
cc: @ahsonkhan

**Comment by ahsonkhan** [comment]
> Also, ReallyLargeLookupUTF8 should really be made outerloop, given that it allocates a 1GB string.

Agreed, especially x86.

Not sure about the other type of failure atm. Will investigate next week.
