### ISSUE TITLE
CI System.Security.Cryptography.X509Certificates.Tests failures

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#36124]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F35944~2Fmerge/test~2Ffunctional~2Fcli~2F/20190318.12/workItem/System.Security.Cryptography.X509Certificates.Tests/analysis/xunit/System.Security.Cryptography.X509Certificates.Tests.ChainTests~2FBuildInvalidSignatureTwice

**Comment by ahsonkhan** [comment]
Same here: https://github.com/dotnet/corefx/pull/36114
 System.Security.Cryptography.X509Certificates.Tests.ChainTests/BuildInvalidSignatureTwice
Windows.10.Nano.Amd64.Open-x64-Debug
Windows.10.Amd64.ClientRS4.ES.Open-x64-Debug
Windows.81.Amd64.Open-x64-Debug
Windows.7.Amd64.Open-x64-Debug
Windows.10.Amd64.ClientRS4.ES.Open-x86-Release
Windows.81.Amd64.Open-x86-Release
Windows.7.Amd64.Open-x86-Release
Windows.10.Amd64.ClientRS5.Open-x86-Release
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F36114~2Fmerge/test~2Ffunctional~2Fcli~2F/20190318.19/workItem/System.Security.Cryptography.X509Certificates.Tests/analysis/xunit/System.Security.Cryptography.X509Certificates.Tests.ChainTests~2FBuildInvalidSignatureTwice

```text
Unhandled Exception of Type Xunit.Sdk.FalseException
Message :
Chain is valid on execution 1
Expected: False
Actual:   True
Stack Trace :
   at System.Security.Cryptography.X509Certificates.Tests.ChainTests.<BuildInvalidSignatureTwice>g__CheckChain|24_0(<>c__DisplayClass24_0& , <>c__DisplayClass24_1& , <>c__DisplayClass24_2& ) in D:\a\1\s\src\System.Security.Cryptography.X509Certificates\tests\ChainTests.cs:line 856
   at System.Security.Cryptography.X509Certificates.Tests.ChainTests.BuildInvalidSignatureTwice() in D:\a\1\s\src\System.Security.Cryptography.X509Certificates\tests\ChainTests.cs:line 871
```

cc @bartonjs, @GrabYourPitchforks

**Comment by JeremyKuhne** [comment]
Failed again on Windows [here](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39468~2Fmerge/test~2Ffunctional~2Fcli~2F~2F/20190715.39/workItem/System.Security.Cryptography.X509Certificates.Tests/analysis/xunit/System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests~2FBuildInvalidSignatureTwice(endEntityErrors:%20NoError,%20intermediateErrors:%20NotSignatureValid,%20rootErrors:%20UntrustedRoot)):

```
Message :
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc0000001)
Stack Trace :
   at Internal.Cryptography.CngCommon.SignHash(SafeNCryptKeyHandle keyHandle, ReadOnlySpan`1 hash, AsymmetricPaddingMode paddingMode, Void* pPaddingInfo, Int32 estimatedSize) in /_/src/Common/src/Internal/Cryptography/CngCommon.SignVerify.cs:line 28
   at System.Security.Cryptography.RSAImplementation.RSACng.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) in /_/src/Common/src/System/Security/Cryptography/RSACng.SignVerify.cs:line 82
   at System.Security.Cryptography.RSA.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) in /_/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RSA.cs:line 175
   at System.Security.Cryptography.RSA.SignData(Byte[] data, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) in /_/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RSA.cs:line 153
   at System.Security.Cryptography.X509Certificates.RSAPkcs1X509SignatureGenerator.SignData(Byte[] data, HashAlgorithmName hashAlgorithm) in /_/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/RSAPkcs1X509SignatureGenerator.cs:line 24
   at System.Security.Cryptography.X509Certificates.CertificateRequest.Create(X500DistinguishedName issuerName, X509SignatureGenerator generator, DateTimeOffset notBefore, DateTimeOffset notAfter, Byte[] serialNumber) in /_/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/CertificateRequest.cs:line 595
   at System.Security.Cryptography.X509Certificates.CertificateRequest.CreateSelfSigned(DateTimeOffset notBefore, DateTimeOffset notAfter) in /_/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/CertificateRequest.cs:line 314
   at System.Security.Cryptography.X509Certificates.Tests.TestDataGenerator.MakeTestChain(ReadOnlySpan`1 keys, Span`1 certs, String eeName, OidCollection eeEku) in /_/src/System.Security.Cryptography.X509Certificates/tests/TestDataGenerator.cs:line 82
   at System.Security.Cryptography.X509Certificates.Tests.TestDataGenerator.MakeTestChain3(X509Certificate2& endEntityCert, X509Certificate2& intermediateCert, X509Certificate2& rootCert) in /_/src/System.Security.Cryptography.X509Certificates/tests/TestDataGenerator.cs:line 26
   at System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.BuildInvalidSignatureTwice(X509ChainStatusFlags endEntityErrors, X509ChainStatusFlags intermediateErrors, X509ChainStatusFlags rootErrors) in /_/src/System.Security.Cryptography.X509Certificates/tests/DynamicChainTests.cs
```

**Comment by bartonjs** [comment]
@JeremyKuhne Your callstack is #37994, not this.
