### ISSUE TITLE
Httpclient bug

### ISSUE THREAD

**Issue by lun3322** [dotnet/corefx#36135]
Describe the bug
Httpclient accesses part of the domain name in the dotnet core and throws an exception. Normally in freamwork 4.7

To Reproduce
https://github.com/lun3322/httpclient-bug

Expected behavior
System.AggregateException: One or more errors occurred.

**Comment by davidsh** [comment]
Your repro code is using .Result async Task pattern:

```c#
var result = client.GetByteArrayAsync("http://www.nmgp.gov.cn").Result;
```

It is expected that if there is an exception, it would be thrown as a System.AggregateException. The actual error would be an inner exception inside.

If you don't want the System.AggregateException, then you should use the following code instead:

```c#
var result = client.GetByteArrayAsync("http://www.nmgp.gov.cn").GetAwaiter().GetResult();
```

Using this pattern will show you the actual exception only and avoid getting the AggregateException being thrown.

**Comment by lun3322** [comment]
thanks for your reply

I mean, the method Class1.Get() will throw an exception when running in the dotnet core, and will not throw an exception when running in the freamwork 4.7.

**Comment by stephentoub** [comment]
> System.AggregateException: One or more errors occurred.

What are the InnerExceptions?

> the method Class1.Get() will throw an exception when running in the dotnet core

What version of .NET Core are you using?

I just tried this, on both .NET Core 2.2 and .NET Core 3.0:
```C#
using System;
using System.Net;
using System.Net.Http;
using System.Text;

class Test
{
    public static void Main() => Console.WriteLine(Get());

    public static string Get()
    {
        var client = new HttpClient();
        client.Timeout = TimeSpan.FromMinutes(5);
        client.DefaultRequestHeaders.UserAgent.Clear();
        client.DefaultRequestHeaders.UserAgent.ParseAdd("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36");
        client.DefaultRequestHeaders.Connection.ParseAdd("keep-alive");
        var result = client.GetByteArrayAsync("http://www.nmgp.gov.cn").GetAwaiter().GetResult();
        var html = Encoding.UTF8.GetString(result);
        return html;
    }
}
```
and I get this:
```
> dotnet run -c Release
Error: unknown command /.
usage: /jobinfo?cluster=<backend environment name>&jobid=<jobid>
        e.g. /jobinfo?cluster=cosmos09-prod-co3c&jobid=bd469929-42eb-46e3-b3a0-a2b4beb88e4b
```
no exception.

**Comment by MarcoRossignoli** [comment]
I'm investigating, I get exception
```cs
 class Program
    {
        static void Main(string[] args)
        {
            var client = new HttpClient();
            client.Timeout = TimeSpan.FromMinutes(5);
            client.DefaultRequestHeaders.UserAgent.Clear();
            client.DefaultRequestHeaders.UserAgent.ParseAdd("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36");
            client.DefaultRequestHeaders.Connection.ParseAdd("keep-alive");
            var result = client.GetByteArrayAsync("http://www.nmgp.gov.cn").GetAwaiter().GetResult();
            var html = Encoding.UTF8.GetString(result);
            Console.WriteLine(html);
        }
    }
```
```
C:\Users\Marco\Downloads\Tmp\T1
λ dotnet run -c Release

Unhandled Exception: System.Net.Http.HttpRequestException: No such host is known. ---> System.Net.Sockets.SocketException: No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(Task`1 getTask)
   at T1.Program.Main(String[] args) in C:\Users\Marco\Downloads\Tmp\T1\Program.cs:line 16

C:\Users\Marco\Downloads\Tmp\T1
λ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview3-010431
 Commit:    d72abce213

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview3-27504-2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
I tried to repro, with custom test under dev and I found that it raise only in "Release" and not in "Debug"
I added some log on https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs#L86 and seems that the issue is here in release url is changed in:
```
 ===========================================================================================================
    Discovering: System.Net.Http.Functional.Tests (method display = ClassAndMethod, method display options = None)
    Discovered:  System.Net.Http.Functional.Tests (found 1 of 945 test case)
    Starting:    System.Net.Http.Functional.Tests (parallel test collections = on, max threads = 8)
  ENTER http://www.nmgp.gov.cn/
  EXIT http://www.nmgp.gov.cn/?4DEF217E_C607
  ENTER http://www.nmgp.gov.cn/?4DEF217E_C607
  EXIT http://n/
      System.Net.Http.Functional.Tests.HttpClientTest.My [FAIL]
        System.Net.Http.HttpRequestException : No such host is known.
```
In debug 
```
 ===========================================================================================================
    Discovering: System.Net.Http.Functional.Tests (method display = ClassAndMethod, method display options = None)
    Discovered:  System.Net.Http.Functional.Tests (found 1 of 945 test case)
    Starting:    System.Net.Http.Functional.Tests (parallel test collections = on, max threads = 8)
  ENTER http://www.nmgp.gov.cn/
    Finished:    System.Net.Http.Functional.Tests
  === TEST EXECUTION SUMMARY ===
     System.Net.Http.Functional.Tests  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 4,276s
```
If you like I can go on with investigation.

**Comment by MarcoRossignoli** [comment]
At the moment I discovered that the difference is that for .net core call server returns invalid `Location` header that lead to unknow host, fiddler log:

.NET Core
```
GET http://www.nmgp.gov.cn/ HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Connection: Keep-Alive
Host: www.nmgp.gov.cn

HTTP/1.1 302 Redirect
Content-Length: 0
Location: http://www.nmgp.gov.cn/?4DEF217E_E3D8
Connection: keep-alive
Set-Cookie: RAYCC=4F0B0FF5; path=/

GET http://www.nmgp.gov.cn/?4DEF217E_E3D8 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Connection: Keep-Alive <-- NOT ON NETFX
Cookie: RAYCC=4F0B0FF5
Host: www.nmgp.gov.cn

HTTP/1.1 302 Redirect
Content-Length: 0
Location: http://n

mgp.gov.cn/
Connection: keep-alive


```

.NET Full
```
GET http://www.nmgp.gov.cn/ HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Host: www.nmgp.gov.cn
Connection: Keep-Alive

HTTP/1.1 302 Redirect
Content-Length: 0
Location: http://www.nmgp.gov.cn/?4DEF217E_D606
Connection: keep-alive
Set-Cookie: RAYCC=4F0B0F32; path=/

GET http://www.nmgp.gov.cn/?4DEF217E_D606 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Host: www.nmgp.gov.cn
Cookie: RAYCC=4F0B0F32

HTTP/1.1 302 Redirect
Content-Length: 0
Location: http://www.nmgp.gov.cn/
Connection: keep-alive

```

**Comment by lun3322** [comment]
As @MarcoRossignoli said, the exception I caught is also System.Net.Http.HttpRequestException: No such host is known.

```
 Version:   2.2.101
 Commit:    236713b0b7

 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed
```

**Comment by wfurt** [comment]
That does not seems like a bug. Since the `Location: http://n` is not right it fails to do DNS lookup. 
You may try to inject `Connection: Close` to your request to avoid server bug sending invalid location header.

**Comment by MarcoRossignoli** [comment]
@wfurt I don't find a reason for difference between core e full...I don't know if is visibile with fiddler or it there Is some difference on encoding(speculating) etc...

**Comment by wfurt** [comment]
I did take close look and here is whole sequence @MarcoRossignoli 

```
GET / HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Connection: keep-alive
Host: www.nmgp.gov.cn

HTTP/1.1 302 Redirect
Content-Length: 0
Location: http://www.nmgp.gov.cn/?814E258A_35E3
Connection: keep-alive
Set-Cookie: RAYCC=8365BB09; path=/

GET /?814E258A_35E3 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Connection: keep-alive
Cookie: RAYCC=8365BB09
Host: www.nmgp.gov.cn

HTTP/1.1 302 Redirect
Content-Length: 0
Location: http://n

mgp.gov.cn/
Connection: keep-alive
```

The 'n' in location is real letter followed by CRLFCRLF sequence. After that everything goes south. When I was playing with this I was trying to figure out exact difference between OK and bad option. This is when it worked:

```
GET /?814E258A_88E1 HTTP/1.1
Host: www.nmgp.gov.cn
Accept: */*
Cookie: RAYCC=8365BB81
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Connection: keep-alive

HTTP/1.1 302 Redirect
Content-Length: 0
Location: http://www.nmgp.gov.cn/
Connection: keep-alive
```

I added "Accept: */*" and that did nothing. Than I modified your code to look like 
``` c# 
       var client = new HttpClient();
        client.Timeout = TimeSpan.FromMinutes(5);
        client.DefaultRequestHeaders.Add("Host", "www.nmgp.gov.cn");
        //client.DefaultRequestHeaders.Add("Accept", "*/*");
        client.DefaultRequestHeaders.UserAgent.Clear();
        client.DefaultRequestHeaders.UserAgent.ParseAdd("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36");
        client.DefaultRequestHeaders.Connection.ParseAdd("keep-alive");
```

and that made it work and gives HTML back. All this does is changing order of headers. 
That really suggests that that is server bug. It should be OK to have Host header last but the server does not like it.

As far as the exception: I think that make depend on how resolver or servers are configured. 
We will lookup crap and that _should_ fail. In my case (and probably for @stephentoub ) I see lookup for `n.corp.microsoft.com` and that resolves to valid IP address.

**Comment by MarcoRossignoli** [comment]
> hat really suggests that that is server bug. It should be OK to have Host header last but the server does not like it.

I guess so, compatible with difference between full and core, @lun3322 you can you try @wfurt solution?

**Comment by davidsh** [comment]
>It should be OK to have Host header last but the server does not like it.

According to the HTTP [RFC 7230](https://www.ietf.org/rfc/rfc7230.txt) there is some discussion about the order of the request header fields:

```
3.2.2.  Field Order

   The order in which header fields with differing field names are
   received is not significant.  However, it is good practice to send
   header fields that contain control data first, such as Host on
   requests and Date on responses, so that implementations can decide
   when not to handle a message as early as possible.  A server MUST NOT
   apply a request to the target resource until the entire request
   header section is received, since later header fields might include
   conditionals, authentication credentials, or deliberately misleading
   duplicate header fields that would impact request processing.
```

It suggests that "control data" request headers (such as 'Host') be sent "first".  But a server *must not* assume that.

**Comment by lun3322** [comment]
Thank all
I tried add Host header, httpclient No longer throws an exception.
But I also tried java apache httpclient package and python requests package, you can get the html code without this operation.

Maybe this solution can be inside dotnet core
