### ISSUE TITLE
Problems with a .Net Core test project and a full .Net Framework base project

### ISSUE THREAD

**Issue by jons-aura** [dotnet/corefx#36157]
Reproduction case here https://jons_aura@bitbucket.org/jons_aura/temporaryfortestcaseproduction

When I run the tests locally they run and all pass. When they are run in Azure Devops with a "Hosted VS 2017" instance the tests error out loading.

@ericstj tagging as requested in https://github.com/dotnet/corefx/issues/22142#issuecomment-473399926

**Comment by ericstj** [comment]
I pulled your repository down and tried building (had to remove a CarrierSettings package reference).  I believe this will fail when run on machines that have older versions of .NET that don't include netstandard.dll inbox.  The tests are not generating bindingRedirects so they won't be unifying assembly dependencies.  Your local machine likely has .NET 4.7.1 or later which includes these assemblies inbox and unifies them, ignoring the dlls next to the test.

Try setting the following in the test project file.
```xml
<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
```

If that doesn't help can you grab a [binlog](http://msbuildlog.com/#usingbl) from the failure and share it?

**Comment by jons-aura** [comment]
I've attached the logs from the Azure build agent. If that's not sufficient which step or steps do you need me to try to get binlogs for (as build and test are separate steps)?
[logs_288.zip](https://github.com/dotnet/corefx/files/2984875/logs_288.zip)

**Comment by ericstj** [comment]
The log helps, this is unusual.  I've got a local repro.  Investigating.

**Comment by ericstj** [comment]
Here's the full exception:
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  Source=NUnit3.TestAdapter
  StackTrace:
   at NUnit.VisualStudio.TestAdapter.EmbeddedAssemblyResolution.EnsureInitialized() in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\EmbeddedAssemblyResolution.cs:line 32
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor..ctor() in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 46
```

This is coming from the following module on my machine:
c:\scratch\temporaryfortestcaseproduction\NUnitTestProject1\bin\Debug\\**netcoreapp2.1**\NUnit3.TestAdapter.dll

Here's why it's happening.
```
2019-03-19T18:08:15.3684982Z Running tests using vstest.console.exe runner.
...
2019-03-19T18:08:15.4506678Z Test selector : Test assemblies
2019-03-19T18:08:15.4511592Z Test assemblies : **\release\*test*.dll,!**\obj\**
2019-03-19T18:08:15.4512555Z Test filter criteria : null
2019-03-19T18:08:15.4516299Z Search folder : D:\a\1\s
2019-03-19T18:08:15.4526178Z Run settings file : D:\a\1\s
...
2019-03-19T18:08:21.8133996Z vstest.console.exe 
2019-03-19T18:08:21.8134183Z "D:\a\1\s\WebApplication1.Tests\bin\Release\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll"
2019-03-19T18:08:21.8134283Z "D:\a\1\s\WebApplication1.Tests\bin\Release\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll"
2019-03-19T18:08:21.8134419Z "D:\a\1\s\WebApplication1.Tests\bin\Release\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll"
2019-03-19T18:08:21.8136049Z "D:\a\1\s\WebApplication1.Tests\bin\Release\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll"
2019-03-19T18:08:21.8136306Z "D:\a\1\s\WebApplication1.Tests\bin\Release\Microsoft.VisualStudio.TestPlatform.TestFramework.dll"
2019-03-19T18:08:21.8136375Z "D:\a\1\s\WebApplication1.Tests\bin\Release\NUnit3.TestAdapter.dll"
2019-03-19T18:08:21.8136454Z "D:\a\1\s\WebApplication1.Tests\bin\Release\WebApplication1.Tests.dll"
2019-03-19T18:08:21.8136512Z /logger:"trx"
2019-03-19T18:08:21.8136581Z /TestAdapterPath:"D:\a\1\s"
```

The problem appears to be that /TestAdapterPath:"D:\a\1\s" parameter.  That's causing the test executor to look under the entire source tree for test adapters.  It finds the one in the output directory of `NUnitTestProject1` which is a netcoreapp2.1 project and tries to load it on desktop.

@navin22 I see you added a warning to vstest.console when it tries to run test assemblies on the wrong framework.  It'd be good if you did the same for test adapters (or even skip them).

@jons-aura do you think you can workaround this by controlling the settings to your build definition?  You should be able to change where it searches for adapters, or partition your output paths by TFM.

**Comment by jons-aura** [comment]
So the issue is that there are .Net Framework and .Net Core test projects in the same solution, it finds the Core test adapter first, and tries to run Framework tests with it? If making all the test projects Core or all Framework would fix it that seems like the easiest option in my scenario as none of the test projects are all that large.

**Comment by ericstj** [comment]
> So the issue is that there are .Net Framework and .Net Core test projects in the same solution, it finds the Core test adapter first, and tries to run Framework tests with it

Yes.  That appears to be what's happening. 

>If making all the test projects Core or all Framework would fix it 

Yeah, seems like it.  You might be able to even avoid having to do that if you could control the paths that were passed in to the test runner (EG: don't pass TestAdapterPath or make sure that its a path that only contains adapters for your target framework).

There may be other bugs lurking here, not sure if the folks designing this test infra have a "golden path" for doing one test run that handles multiple frameworks.

**Comment by jons-aura** [comment]
Making all the test projects full Framework resolved the issue for me. I was hoping to get them all on Core but we use EF 6 in this solution still.
