### ISSUE TITLE
Unable to cast object of type 'Enumerator[System.Security.Cryptography.X509Certificates.X509Certificate2]' to type 'Internal.Cryptography.Pal.OpenSslX509CertificateReader'

### ISSUE THREAD

**Issue by NicolasDorier** [dotnet/corefx#36173]
I made thousands of deployment of my server along the years, but only one customer reported me this error:

```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.InvalidCastException: Unable to cast object of type 'Enumerator[System.Security.Cryptography.X509Certificates.X509Certificate2]' to type 'Internal.Cryptography.Pal.OpenSslX509CertificateReader'.
   at Internal.Cryptography.Pal.CollectionBackedStoreProvider.CloneTo(X509Certificate2Collection collection)
   at System.Security.Cryptography.X509Certificates.X509Store.get_Certificates()
   at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.FindCandidates(X509Certificate2 leaf, X509Certificate2Collection extraStore, HashSet`1 downloaded, HashSet`1 systemTrusted, TimeSpan& remainingDownloadTime)
   at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
   at System.Net.Security.CertificateValidation.BuildChainAndVerifyProperties(X509Chain chain, X509Certificate2 remoteCertificate, Boolean checkCertName, String hostName)
   at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback, ProtocolToken& alertToken)
   at System.Net.Security.SslState.CompleteHandshake(ProtocolToken& alertToken)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at BTCPayServer.Services.Rates.CoinAverageRateProvider.GetExchangeTickersAsync() in /source/Services/Rates/CoinAverageRateProvider.cs:line 212
```
This error is not limited to a single website, it seems that all HTTPS called started failing after this.

The running environment is [this docker image](https://github.com/btcpayserver/btcpayserver/blob/master/Dockerfile.linuxamd64). (dotnet:2.1.6-aspnetcore-runtime-alpine3.7 built with dotnet:2.1.500-sdk-alpine3.7)

I think it is a bug of a corner case of a corner case as in all those years I never saw that happening once. But I am at loss debugging this.

**Comment by Janaka-Steph** [comment]
Thank for opening this issue. As additional info I am on Odroid xu4 with this image https://wiki.odroid.com/odroid-xu4/os_images/linux/ubuntu_4.14/20181203-minimal 
I installed btcpay following exactly https://github.com/btcpayserver/btcpayserver-doc/blob/master/RaspberryPiDeployment.md, except without swapfile and without fast sync (which is corrupting my datadir).

**Comment by Janaka-Steph** [comment]
I have updated btcpay and I don't see the error anymore. I will report if it reappears.

**Comment by NicolasDorier** [comment]
@Janaka-Steph I updated .NET Core to 2.1.9 today. So this might be why.

**Comment by stephentoub** [comment]
From the source, I don't see how this could happen.  The cast in question would be this line:
https://github.com/dotnet/corefx/blob/39fcb4b73c1a7dfca721d5f727603ffd35a428d8/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/CollectionBackedStoreProvider.cs#L37
but there's no way that cert.Pal is an `Enumerator[X509Certificate2]`.

However, there is an `Enumerator[X509Certificate2]` on the stack here, as `_certs` is a `List<X509Certificate2>`, and so the enumerator created by the foreach is a `Enumerator[X509Certificate2]`.  To me that suggests that there's some kind of codegen problem where the generated code is incorrectly attempting to cast that `Enumerator[X509Certificate2]` rather than its `Current.Pal`.

@AndyAyersMS, are you aware of any JIT-related issues that could have contributed to this, maybe something that was present in 2.1 but was fixed in a servicing release? e.g. could this be an effect of https://github.com/dotnet/coreclr/pull/21215?

cc: @bartonjs

**Comment by AndyAyersMS** [comment]
dotnet/coreclr#21215 was related to casts of literal constants -- doesn't seem like it would be related. And I don't see any other relevant 2.1 fixes.

Is this something that happened just one time, or is it reproducible? 
And so far, it happens in 2.1.6 but not in 2.1.9?

**Comment by Janaka-Steph** [comment]
Happened just one time. Maybe reproducible, but now I don't have the error, I don't really want to setup everything again just to test the bug.

**Comment by NicolasDorier** [comment]
This error happened only on @Janaka-Steph on docker environment. 

The code on which it is based is used by lot's of people (between 1000 and 2000  users deployed my server) and that's the first time I saw something like this.

In doubt I updated to `2.1.9`. If you want to close, feel free to do so as it does not block me, just wanted to keep you posted about it.

**Comment by NicolasDorier** [comment]
The deployment target though was Odroid xu4, which is not common so the docker image should have been arm32v7 based ([this one](https://github.com/btcpayserver/btcpayserver/blob/bf5a624209c71fb365c21a1184b143ee8f661d35/Dockerfile.linuxarm32v7))

**Comment by NicolasDorier** [comment]
Ok so today, @Janaka-Steph  reported me another interesting error.

```
warn: PayServer:      Error while contacting binance: The SSL connection could not be established, see inner exception. Bad IL format.
```

I don't have a stacktrace for now, will share when I can (on 2.1.9) but something seems fishy on the IL generation.
