### ISSUE TITLE
Test failure: PostAsync_RedirectWith307_LargePayload

### ISSUE THREAD

**Issue by rmkerr** [dotnet/corefx#36220]
The test failed ~200 times today. It doesn't appear to have been flaky before this point, so I think this is either an infrastructure issue (it touches a remote server) or a recent regression.

Here's a link to the test itself:
https://github.com/dotnet/corefx/blob/67482220ab7cd18092ccf62749355d280ece4cea/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs#L2242-L2248

The test started failing today with the error:
>Assert.Equal() Failure\nExpected: OK\nActual:   InternalServerError

Since the error is being surfaced by a failed assert, we're not getting any useful information from the stack trace.

**Comment by davidsh** [comment]
>Since the error is being surfaced by a failed assert, we're not getting any useful information from the stack trace.

I suggest we change the test to collect information.  'InternalServerError' is a 500 status code.  We recently change the Azure endpoint from a Cloud Service to an Azure Web App.  Maybe something is different due to that.

As part of the remote server, I catch any exceptions on the server side and return a 500 status code if there was an exception on the server side (unlikely unless the request header data from the client is corrupt for example).  But the HttpResponseMessage.ReasonPhrase contains the exception message from the server.

So, we should modify this test accordingly from something like:

```c#
Assert.Equal(HttpStatus.OK, response.StatusCode);
```

to

```c#
if (response.StatusCode != HttpStatus.OK)
{
    _output.WriteLine($"{(int)response.StatusCode} {response.ReasonPhrase}");
}

Assert.Equal(HttpStatus.OK, response.StatusCode);
```

Doing this will capture the information into the Xunit ITestOutput and end up in the testresults.xml file.  And we already know that the testresults.xml file is saved for each test run and can be retrieved and examined.

**Comment by davidsh** [comment]
@wfurt

**Comment by davidsh** [comment]
It's also possible that the 500 HTTP status code is coming from the front-end of the Azure App Service before it actually gets to our website endpoint.  So, we'll need to track this.  Perhaps it is a scalability issue and I need to scale out the endpoint to handle the larger load from CI/PR jobs.

**Comment by wfurt** [comment]
I had test loop running on windows10 and I did not see the failure. I’ll get azure vm tomorrow via repro tool and I’ll colect more info.

**Comment by wfurt** [comment]
This is back: https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190327.7/workItem/System.Net.Http.Functional.Tests

```
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest.PostAsync_RedirectWith307_LargePayload [FAIL]
      Assert.Equal() Failure
      Expected: OK
      Actual:   InternalServerError
      Stack Trace:
        /__w/1/s/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs(2274,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.PostAsync_Redirect_LargePayload_Helper(Int32 statusCode, Boolean expectRedirectToPost)
        /__w/1/s/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs(2247,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.PostAsync_RedirectWith307_LargePayload()
        --- End of stack trace from previous location where exception was thrown ---
      Output:
        500 Internal Server Error

```

**Comment by davidsh** [comment]
>This is back: 

@wfurt Can you download the testresults.xml file from Kusto and grab the extra logging we did?  It might give us more clues.

**Comment by wfurt** [comment]
it does not have much. I think The "ouput" is dumped to console as well on failure.
```
      <test name="System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest.PostAsync_RedirectWith307_LargePayload" type="System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest" method="PostAsync_RedirectWith307_LargePayload" time="1.1003832" result="Fail">
        <output><![CDATA[500 Internal Server Error
]]></output>
        <traits>
          <trait name="category" value="nonuaptests" />
          <trait name="category" value="nonuapaottests" />
          <trait name="category" value="outerloop" />
          <trait name="activeissue" value="22191" />
        </traits>
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\nExpected: OK\nActual:   InternalServerError]]></message>
          <stack-trace><![CDATA[   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.PostAsync_Redirect_LargePayload_Helper(Int32 statusCode, Boolean expectRedirectToPost) in /__w/1/s/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs:line 2274
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.PostAsync_RedirectWith307_LargePayload() in /__w/1/s/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs:line 2247
--- End of stack trace from previous location where exception was thrown ---]]></stack-trace>
        </failure>
      </test>
```

**Comment by wfurt** [comment]
[testResults-3.xml.zip](https://github.com/dotnet/corefx/files/3016007/testResults-3.xml.zip)

**Comment by wfurt** [comment]
System.Net.Tests.SyncWebClientTest/UploadData_LargeData_Success(echoServer: http://corefx-net-http11.azurewebsites.net/Echo.ashx) has similar failure:

```
System.Net.WebException : The remote server returned an error: (500) Internal Server Error.

at System.Net.HttpWebRequest.GetResponse() in /__w/1/s/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1009
   at System.Net.WebClient.GetWebResponse(WebRequest request) in /__w/1/s/src/System.Net.WebClient/src/System/Net/WebClient.cs:line 249
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream) in /__w/1/s/src/System.Net.WebClient/src/System/Net/WebClient.cs:line 818
   at System.Net.WebClient.UploadBits(WebRequest request, Stream readStream, Byte[] buffer, Int32 chunkSize, Byte[] header, Byte[] footer) in /__w/1/s/src/System.Net.WebClient/src/System/Net/WebClient.cs:line 982
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request) in /__w/1/s/src/System.Net.WebClient/src/System/Net/WebClient.cs:line 451

```

**Comment by wfurt** [comment]
500 is back: https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190402.8

Many tests failing HTTP + Web* test sets.

**Comment by davidsh** [comment]
>500 is back: https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190402.8
Many tests failing HTTP + Web* test sets.

I think this is an infrastructure issue in Azure App Service (which hosts the endpoints).  Do our tests show the diagnostics at all?  We added `_output.WriteLine(response.ReasonPhrase)` to the testresults.xml file.

 But the overall Azure diagnostics do show a spike in the last 48 hours for 500 errors:
![image](https://user-images.githubusercontent.com/7684835/55482844-357b1100-55da-11e9-8b4a-9fc57f54ff0b.png)

**Comment by wfurt** [comment]
added testResults.xml from two failed runs. 
[testResults-5.xml.zip](https://github.com/dotnet/corefx/files/3041024/testResults-5.xml.zip)
[testResults-6.xml.zip](https://github.com/dotnet/corefx/files/3041025/testResults-6.xml.zip)

cc: @karelz

**Comment by wfurt** [comment]
```
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest.PostAsync_RedirectWith307_LargePayload [FAIL]
      Assert.Equal() Failure
      Expected: OK
      Actual:   InternalServerError
      Stack Trace:
        /__w/1/s/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs(2293,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.PostAsync_Redirect_LargePayload_Helper(Int32 statusCode, Boolean expectRedirectToPost)
        /__w/1/s/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs(2266,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.PostAsync_RedirectWith307_LargePayload()
        --- End of stack trace from previous location where exception was thrown ---
      Output:
        500 Internal Server Error
```

[console.0a567ade.log](https://github.com/dotnet/corefx/files/3041037/console.0a567ade.log)

**Comment by davidsh** [comment]
@wfurt The diagnostics don't tell us anything useful.  It's not clear yet where the 500 status code is coming from.

Can you submit a PR to disable this test for now?  There is no value is leaving it running if it's failing a lot right now. I'd like to see if the test failures are localized to just this test or other problematic tests.

**Comment by wfurt** [comment]
If you look at the last line, we had ~200 tests failing. I don't think disabling this particular test will resolve that.

**Comment by davidsh** [comment]
>If you look at the last line, we had ~200 tests failing. I don't think disabling this particular test will resolve that.

Ok.  Leave as-is for now.  I've configured Application Insights for the endpoint which should start collecting very detailed diagnostics for these HTTP server errors.  I'll review any logs tomorrow to see if something interesting shows up.

**Comment by davidsh** [comment]
We already have interesting data on failures!!

Looks like there might be a bug in ASP.NET Core.  We use ASP.NET Core 2.2 as the implementation for the endpoint running in App Service.  Need to diagnose why this exception is happening.

![image](https://user-images.githubusercontent.com/7684835/55522237-ec0dde80-5638-11e9-8313-95f47f6f86a9.png)

**Comment by davidsh** [comment]
@Tratcher We now use ASP.NET Core 2.2 as the implementation of our Azure endpoint (we used to use Azure Classic Cloud Service with .NET Framework and ASP.NET).

Endpoint: https://corefx-net-http11.azurewebsites.net

We are seeing some interesting NullReferenceExceptions being generated (and unhandled) in ASP.NET Core.  Do you know what might cause that?

**Comment by davidsh** [comment]
Exception call stack from ASP.NET Core:

>System.NullReferenceException:
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.GetOriginalPath (Microsoft.AspNetCore.Server.IIS, Version=2.2.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.InitializeContext (Microsoft.AspNetCore.Server.IIS, Version=2.2.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1+<ProcessRequestAsync>d__2.MoveNext (Microsoft.AspNetCore.Server.IIS, Version=2.2.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer+<HandleRequest>d__27.MoveNext (Microsoft.AspNetCore.Server.IIS, Version=2.2.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)

**Comment by davidsh** [comment]
Even more interesting unhandled exceptions being generated. 

>System.InvalidOperationException:
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ThrowResponseAlreadyStartedException (Microsoft.AspNetCore.Server.IIS, Version=2.2.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.set_StatusCode (Microsoft.AspNetCore.Server.IIS, Version=2.2.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.set_StatusCode (Microsoft.AspNetCore.Server.IIS, Version=2.2.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse.set_StatusCode (Microsoft.AspNetCore.Http, Version=2.2.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at NetCoreServer.EchoWebSocketHandler+<InvokeAsync>d__1.MoveNext (NetCoreServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullNetCoreServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\home\site\repository\NetCoreServer\Handlers\EchoWebSocketHandler.csNetCoreServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 55)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at NetCoreServer.GenericHandler+<Invoke>d__1.MoveNext (NetCoreServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullNetCoreServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\home\site\repository\NetCoreServer\GenericHandler.csNetCoreServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 63)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1+<ProcessRequestAsync>d__2.MoveNext (Microsoft.AspNetCore.Server.IIS, Version=2.2.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)

**Comment by davidsh** [comment]
I've scaled up the endpoint to 4 instances and we see failures across them.  I don't think this is a capacity of load issue.  I think it is potentially some undiscovered bugs in ASP.NET Core or perhaps there is something we need to add our own try/catch for.

![image](https://user-images.githubusercontent.com/7684835/55523666-0945ab80-563f-11e9-8600-a77aee6c938e.png)

**Comment by Tratcher** [comment]
Can you share your server side code?

@jkotalik

**Comment by jkotalik** [comment]
Thanks for looping me in, yeah it seems like it could be a but with IIS Inproc. When was this service upgrade to 2.2?

The null references you are seeing is the following issue: https://github.com/aspnet/AspNetCore/issues/6075

**Comment by davidsh** [comment]
>When was this service upgrade to 2.2?

We used to use an Azure endpoint hosted in a Class Cloud Service using .NET Framework and ASP.NET.  A few weeks ago, we converted our endpoint to use Azure App Service and reworked the server-side code to use ASP.NET Core.  We used 2.2 of ASP.NET Core because it was the latest RTM.

@Tratcher 
>Can you share your server side code?

The server-side code is currently here:
https://github.com/davidsh/corefx-net-endpoint

**Comment by davidsh** [comment]
@jkotalik 

>Thanks for looping me in, yeah it seems like it could be a but with IIS Inproc. When was this service upgrade to 2.2?

Is there a workaround to this?

**Comment by jkotalik** [comment]
After reading your code, setting the status code in the exception handler isn't guaranteed to work as the call to WriteAsync may or may not write data. I think you should just remove the try catch in this method: https://github.com/davidsh/corefx-net-endpoint/blob/master/NetCoreServer/Handlers/EchoWebSocketHeadersHandler.cs#L33. So the status code issue doesn't seem like a bug there.

My next question is do you expect this test to throw an exception?

The NullReference you are seeing is due to the Azure app warmup module, which sends a fake HTTP Request to the server. This fake request is malformed and doesn't have every field set correctly, which causes null reference. The request you get should never show up when a client sends a request.

**Comment by davidsh** [comment]
>After reading your code, setting the status code in the exception handler isn't guaranteed to work as the call to WriteAsync may or may not write data. I think you should just remove the try catch in this method: https://github.com/davidsh/corefx-net-endpoint/blob/master/NetCoreServer/Handlers/EchoWebSocketHeadersHandler.cs#L33. So the status code issue doesn't seem like a bug there.

Thanks.  I noticed that setting the StatusCode in the WebSocket handler isn't good because the HTTP response has already been sent (i.e. the 101 status code).  So, I recently (this morning) changed the catch block to just ignore the exception.  We might get an exception because the client might disconnect (either a real test running or just anyone connecting).  So, this part of the code should be more robust code.  And I don't expect to see the StatusCode exception from ASP.NET Core anymore.

**Comment by davidsh** [comment]
>My next question is do you expect this test to throw an exception?

Also, this code is not the test itself.  It is an endpoint that our tests running CI access.  So, this endpoint needs to be very robust against all sorts of issues (like client disconnects).  So, I don't want unhandled exceptions coming from the `ProcessWebSocketRequest` method (which I should be renamed to `ProcessWebSocketRequestAsync`)

**Comment by Tratcher** [comment]
Any exception thrown from here would be handled by the server, logged, and then it will terminate the response in the most graceful way possible (500 error if it can, disconnect if it can't).

**Comment by davidsh** [comment]
Turns out we still have some infrastructure problems.  These tests are POST'ing large amounts of data to the echo server.  And we try serialize JSON responses back.  We are hitting OutOfMemoryException's on the server.  I'll need to investigate how to mitigate this.  We may need to revise the tests as well.

![image](https://user-images.githubusercontent.com/7684835/55974620-ecac0380-5c3c-11e9-9696-a9e6e8b0cfd0.png)

**Comment by davidsh** [comment]
The best fix is to change the test to use the [VerifyUpload](http://corefx-net-http11.azurewebsites.net/verifyupload.ashx) endpoint and not the [Echo](http://corefx-net-http11.azurewebsites.net/echo.ashx) endpoint.  The Echo endpoint ends up serializing the entire request body and sending it back.  The Upload endpoint simply verifies the request body is correct by checking the MD5 checksum. It doesn't echo back the request body.
