### ISSUE TITLE
RenamedTests.FileSystemWatcher_Moved_NestedDirectoryRoot failed in CI

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#3630]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/4559/console

```     
RenamedTests.FileSystemWatcher_Moved_NestedDirectoryRoot [FAIL]
        System.UnauthorizedAccessException : Access to the path '\\?\d:\j\workspace\dotnet_corefx_windows_release_prtest\bin\tests\Windows_NT.AnyCPU.Release\System.IO.FileSystem.Watcher.Tests\dnxcore50\FileSystemWatcher_Moved_NestedDirectoryRoot\test_root' is denied.
        Stack Trace:
              at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
              at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.IO.FileSystem.Watcher\tests\Utility\TemporaryTestDirectory.cs(32,0): at TemporaryTestDirectory.Dispose()
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.IO.FileSystem.Watcher\tests\FileSystemWatcher.Renamed.cs(122,0): at RenamedTests.FileSystemWatcher_Moved_NestedDirectoryRoot()
```

**Comment by stephentoub** [comment]
@JeremyKuhne, separate from the failure, should the path in the exception be using extended syntax like this, or should it be the path the developer specified?  I would have assumed the latter, but it's showing the former.

**Comment by JeremyKuhne** [comment]
We probably should give back the original syntax. Need to update the helper to keep the context to know to pull the prefix if we throw.

**Comment by sokket** [comment]
Pushing to RTM with the rest of these since they are based on the underlying (flaky) OS APIs

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_windows_nt_debug_prtest/35/consoleFull
