### ISSUE TITLE
Enable the SocketPerformance tests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3635]
```
System.Net.Sockets.Performance.Tests.SocketPerformanceAsyncTests.SocketPerformance_MultipleSocketClientAsync_LocalHostServerAsync [FAIL]
04:31:37         Test execution is expected to be shorter than 10000 but was 27753
04:31:37         Expected: True
04:31:37         Actual:   False
04:31:37         Stack Trace:
04:31:37            d:\j\workspace\dotnet_corefx_outerloop_windows_win10_debug\src\Common\tests\System.Net\Sockets\Performance\SocketPerformanceTests.cs(63,0): at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.ClientServerTest(Int32 port, SocketImplementationType serverType, SocketImplementationType clientType, Int32 iterations, Int32 bufferSize, Int32 socketInstances, Int64 expectedMilliseconds)
04:31:37            d:\j\workspace\dotnet_corefx_outerloop_windows_win10_debug\src\Common\tests\System.Net\Sockets\Performance\SocketPerformanceTests.cs(77,0): at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.ClientServerTest(SocketImplementationType serverType, SocketImplementationType clientType, Int32 iterations, Int32 bufferSize, Int32 socketInstances, Int64 expectedMilliseconds)
04:31:37            d:\j\workspace\dotnet_corefx_outerloop_windows_win10_debug\src\System.Net.Sockets\tests\PerformanceTests\SocketPerformanceAsyncTests.cs(60,0): at System.Net.Sockets.Performance.Tests.SocketPerformanceAsyncTests.SocketPerformance_MultipleSocketClientAsync_LocalHostServerAsync()
```
cc: @davidsh, @cipop, @pgavlin

**Comment by CIPop** [comment]
Performance tests were excluded from CI. The original expectations were tuned to the internal test machines.

**Comment by CIPop** [comment]
This was incorrectly closed: we have several ActiveIssue pointing to it.
Reopening & changing the title.

**Comment by CIPop** [comment]
Looks like the SocketsPerf APM tests were not brought back with the APM changes to the Sockets APIs. Using this item to bring them back.

@stephentoub @ericeil Outside of #7196, do you remember if any other System.Net tests were removed?

**Comment by CIPop** [comment]
Limiting this bug to track only enabling the perf tests. 
@himadrisarkar @stephentoub @ericeil We should track adding back APIs and their corresponding tests separately for vNext. Reverting part of the changes in #7196 should be included in that work.
