### ISSUE TITLE
Unobserved task exception 

### ISSUE THREAD

**Issue by onovotny** [dotnet/corefx#36364]
I'm not 100% sure where the offending code is, but I've seen many instances of these in my telemetry. This is with .NET Core 3

https://github.com/dotnet/coreclr/tree/5ec1eeaa95362be9e76f9f79c9b44162

My code calls `Read()` on a contained `Stream` instance, the rest is BCL code:

```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..) ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.. ---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request.
   at Bugsnag.UnhandledException.HandleEvent(Exception exception, bool runtimeEnding)
   at Bugsnag.UnhandledException.TaskScheduler_UnobservedTaskException(object sender, UnobservedTaskExceptionEventArgs e)
   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(object sender, UnobservedTaskExceptionEventArgs ueea)
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult(short token)
   at System.Net.Security.SslStreamInternal+<<FillBufferAsync>g__InternalFillBufferAsync|38_0>d<TReadAdapter>.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Net.Security.SslStreamInternal+<ReadAsyncInternal>d__34<TReadAdapter>.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpConnection+<ReadAsync>d__85.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpConnection+ContentLengthReadStream+<ReadAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.BaseAsyncStream.Read(byte[] buffer, int offset, int count)
   at PackageExplorer.ProgressStream.Read(byte[] buffer, int offset, int count) in PackageExplorer\MefServices\PackageDownloader.cs:line 275
   at System.IO.Stream+<>c.<BeginReadInternal>b__43_0(object <p0>)
   at System.Threading.Tasks.Task<TResult>.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__277_0(object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref Task currentTaskSlot, Thread threadPoolThread)   --- End of inner exception stack trace ---
   at Bugsnag.UnhandledException.HandleEvent(Exception exception, bool runtimeEnding)
   at Bugsnag.UnhandledException.TaskScheduler_UnobservedTaskException(object sender, UnobservedTaskExceptionEventArgs e)
   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(object sender, UnobservedTaskExceptionEventArgs ueea)
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()
```

**Comment by stephentoub** [comment]
Why do you think it's in bcl code rather than in the code calling Read? It seems like an exception is bubbling up through your code, and whatever code is using yours is in a task that catches the exception and is never observed.

**Comment by kevingosse** [comment]
I'd venture that the issue comes from the `ReadWriteTask` created by `Stream.BeginReadInternal`. Since it's created when using `Stream.BeginRead` and never actually exposed to the caller, I don't think it's possible to observe it when faulted: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/IO/Stream.cs#L529

Knowing that, maybe it'd make sense to add a catch block in the delegate given to the ReadWriteTask?

**Comment by stephentoub** [comment]
> and never actually exposed to the caller

It is, via EndWrite, no? If the End corresponding to the Begin isn't called that's a bug in the using code.

**Comment by benaadams** [comment]
Some async over sync over async going on?
```
System.IO.Stream+<>c.<BeginReadInternal>b__43_0
->
PackageExplorer.ProgressStream.Read
-> 
... 
->
HttpConnection+ContentLengthReadStream+<ReadAsync>d__2.MoveNext()
```

**Comment by benaadams** [comment]
As aside might want to override the XxxAsync methods of `ProgressStream` to call through to the `Stream _inner` async methods; otherwise it will go via the sync overrides.

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer/MefServices/PackageDownloader.cs#L248-L302

**Comment by onovotny** [comment]
@stephentoub The reason I don't think it's user code is that I'm not using tasks anywhere directly, so there's nothing for me to observe, or not:

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/f863b9fd3f00e9a9ccb109a5ce303c42728be778/PackageExplorer/MefServices/PackageDownloader.cs#L273

**Comment by stephentoub** [comment]
> The reason I don't think it's user code is that I'm not using tasks anywhere directly, so there's nothing for me to observe, or not:

The exception is coming from some task higher in the stack, someone calling your Read method.  Who's reading from your stream, where, and how?  It would appear someone is calling into your stream via BeginRead and then not calling EndRead.

**Comment by onovotny** [comment]
The `ProgressStream` is being used as the Stream in `StreamContent`: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/18889b263b9b7025b547cb28cbed8550e45400a9/PackageExplorer/MefServices/PackageDownloader.cs#L235

**Comment by stephentoub** [comment]
> The ProgressStream is being used as the Stream in StreamContent

Ok, and where is that response content being consumed / read from?

**Comment by onovotny** [comment]
> Ok, and where is that response content being consumed / read from?

It's in the `SendAsync` of a `DelegatingHandler` implementation for `HttpClient`. It's wrapping the response stream with this one so we can get progress callbacks.

**Comment by benaadams** [comment]
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/f863b9fd3f00e9a9ccb109a5ce303c42728be778/PackageExplorer/MefServices/PackageDownloader.cs#L150-L153

`await result.PackageStream.CopyToAsync(fileStream).ConfigureAwait(false);`

As `ProgressStream` doesn't override `ReadAsync` it will call into Stream's `ReadAsync` which will call `Stream.BeginEndReadAsync` and as it doesn't override Begin/EndRead either that will call into Stream `BeginReadInternal`; which is the call higher up in the stack

**Comment by onovotny** [comment]
@benaadams I just implemented the ReadAsync method in my wrapper class. That said, this scenario seems very confusing to diagnose given the messages about tasks. I would expect an exception within my Read code, not something unobserved somewhere.

**Comment by stephentoub** [comment]
> I would expect an exception within my Read code

You have the exception within your Read code... you're just not catching it:
```
at PackageExplorer.ProgressStream.Read(byte[] buffer, int offset, int count) in PackageExplorer\MefServices\PackageDownloader.cs:line 275
```
So it's flowing through your read out into whoever is calling you.

**Comment by stephentoub** [comment]
> await result.PackageStream.CopyToAsync(fileStream).ConfigureAwait(false);
> As ProgressStream

I'm having trouble browsing the sources across the various repos.  What is "PackageStream" here?  It seems like it's not actually the ProgressStream.

**Comment by onovotny** [comment]
PackageStream comes from the NuGet Client API's.

**Comment by stephentoub** [comment]
> PackageStream comes from the NuGet Client API's.

Ok, where?  Help me out here :)

**Comment by onovotny** [comment]
Sorry, 
https://github.com/NuGet/NuGet.Client/blob/3803820961f4d61c06d07b179dab1d0439ec0d91/src/NuGet.Core/NuGet.Protocol/Resources/DownloadResource.cs

I have to dig more, since it's abstracted within Nuget's code

**Comment by onovotny** [comment]
Looks like PackageStream originates here https://github.com/NuGet/NuGet.Client/blob/d8b872af0ae231686dfe7ac62868dfe154d7f565/src/NuGet.Core/NuGet.Protocol/Utility/GetDownloadResultUtility.cs#L72

**Comment by stephentoub** [comment]
Based purely on browsing around NuGet, it is possible one of these Streams has found its way into the hierarchy?
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Utility/DownloadTimeoutStream.cs
If so, I would wager the issue stems from here:
https://github.com/NuGet/NuGet.Client/blob/914978cb75e33cea36a8addcc6d91bc9f1c00ad3/src/NuGet.Core/NuGet.Protocol/Utility/TimeoutUtility.cs#L40-L47

**Comment by benaadams** [comment]
Hmm... it might not be that CopyToAsync; but it is definitely an async on a Stream that then calls the sync Read (due to ProgressStream not implementing any form of async)  which then calls the [async via BaseAsyncStream](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/BaseAsyncStream.cs#L81-L85).

So it would probably still be unobserved if ProgressStream did implement async as its the higher level caller that's dropping the Task? (though at least it wouldn't be async-over-sync-over-async :wink:)

**Comment by stephentoub** [comment]
Based on the data this far, this is not an issue in coreclr or corefx. Some code somewhere, potentially the code I linked to above, is calling ReadAsync and then never awaiting it.
