### ISSUE TITLE
ToolsError build failures in 'official/dotnet/corefx/refs/heads/master' - '20190325.8'

### ISSUE THREAD

**Issue by robertborr** [dotnet/corefx#36382]
@dotnet-mc-bot commented on [Mon Mar 25 2019](https://github.com/dotnet/core-eng/issues/5659)

There were a set of failures during this build. Here is a summary of these:
* https://dnceng.visualstudio.com/internal/_build/results?buildId=133280
  - **Agent:** a0000T1
  - **Error log:** ##[error]The nuget command failed with exit code(1) and error(Failed to retrieve information about 'TestILC.armret' from remote source 'https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/...

@robertborr

---

@robertborr commented on [Tue Mar 26 2019](https://github.com/dotnet/core-eng/issues/5659#issuecomment-476709649)

WARNING: The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.armret/index.json 277ms
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.armret/index.json 277ms
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/microsoft.dotnet.ibcmerge/index.json 377ms
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.amd64ret/index.json 376ms
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/microsoft.dotnet.ibcmerge/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.armret/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.armret/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.amd64ret/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
  GET https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.armret/index.json
  GET https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/microsoft.dotnet.ibcmerge/index.json
  GET https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.amd64ret/index.json
  GET https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.armret/index.json
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.x86ret/index.json 392ms
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.amd64ret/index.json 264ms
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.amd64ret/index.json 292ms
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.x86ret/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.amd64ret/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
  GET https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.x86ret/index.json
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.amd64ret/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.armret/index.json 353ms
  GET https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.amd64ret/index.json
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.armret/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
  GET https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.amd64ret/index.json
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.x86ret/index.json 394ms
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.x86ret/index.json 395ms
  GET https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.armret/index.json
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.x86ret/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.x86ret/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
  GET https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.x86ret/index.json
  GET https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.x86ret/index.json
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.armret/index.json 39ms
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.armret/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.amd64ret/index.json 39ms
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/microsoft.dotnet.ibcmerge/index.json 40ms
  GET https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.armret/index.json
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.amd64ret/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.armret/index.json 40ms
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/microsoft.dotnet.ibcmerge/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.armret/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.x86ret/index.json 39ms
  GET https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.amd64ret/index.json
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.x86ret/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.amd64ret/index.json 39ms
  GET https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.armret/index.json
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.amd64ret/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.amd64ret/index.json 40ms
  GET https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/microsoft.dotnet.ibcmerge/index.json
  GET https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.x86ret/index.json
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.amd64ret/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.armret/index.json 40ms
  GET https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.amd64ret/index.json
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.armret/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.x86ret/index.json 39ms
  GET https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.amd64ret/index.json
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.x86ret/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.x86ret/index.json 40ms
  GET https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.armret/index.json
Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.x86ret/index.json'.
Response status code does not indicate success: 401 (Unauthorized).
  GET https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.x86ret/index.json
  GET https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.x86ret/index.json
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.armret/index.json 40ms
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.amd64ret/index.json 40ms
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/microsoft.dotnet.ibcmerge/index.json 40ms
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.armret/index.json 40ms
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/97a41293-2972-4f48-8c0e-05493ae82010/nuget/v3/flat2/testilc.x86ret/index.json 40ms
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.amd64ret/index.json 40ms
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.amd64ret/index.json 40ms
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.armret/index.json 39ms
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.x86ret/index.json 40ms
  Unauthorized https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.x86ret/index.json 40ms
NuGet.Protocol.Core.Types.FatalProtocolException: Failed to retrieve information about 'TestILC.armret' from remote source 'https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.armret/index.json'. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass14_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<GetAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResource.<FindPackagesByIdAsync>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResource.<FindPackagesByIdAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResource.<EnsurePackagesAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResource.<GetAllVersionsAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.SourceRepositoryDependencyProvider.<GetAllVersionsAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.SourceRepositoryDependencyProvider.<FindLibraryCoreAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.SourceRepositoryDependencyProvider.<>c__DisplayClass19_0.<<FindLibraryAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.SourceRepositoryDependencyProvider.<FindLibraryAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.DependencyResolver.ResolverUtility.<>c__DisplayClass7_1.<<FindLibraryFromSourcesAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.DependencyResolver.ResolverUtility.<FindLibraryFromSourcesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.DependencyResolver.ResolverUtility.<FindLibraryByVersionAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.DependencyResolver.ResolverUtility.<FindLibraryMatchAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.DependencyResolver.ResolverUtility.<FindLibraryEntryAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.ProjectRestoreCommand.<WalkDependenciesAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.ProjectRestoreCommand.<TryRestoreAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreCommand.<ExecuteRestoreAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<ExecuteAndCommitAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<CompleteTaskAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<RunAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<RunAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__36.MoveNext()
##[error]The nuget command failed with exit code(1) and error(Failed to retrieve information about 'TestILC.armret' from remote source 'https://devdiv.pkgs.visualstudio.com/_packaging/8f470c7e-ac49-4afe-a6ee-cf784e438b93/nuget/v3/flat2/testilc.armret/index.json'.
  Response status code does not indicate success: 401 (Unauthorized).)
##[error]Packages failed to restore
##[section]Finishing: Restore internal tools

---

@safern commented on [Tue Mar 26 2019](https://github.com/dotnet/core-eng/issues/5659#issuecomment-476866020)

At least one leg has failed restoring internal tools in the past 5 builds, @ViktorHofer do you know what is going on, you have more context on this.

---

@ViktorHofer commented on [Tue Mar 26 2019](https://github.com/dotnet/core-eng/issues/5659#issuecomment-476866708)

That's a known issue with nuget restore and the credentials provider. It's witty sometimes. We should get the TestILC package to dnceng asap.

cc @ericstj

---

@robertborr commented on [Tue Mar 26 2019](https://github.com/dotnet/core-eng/issues/5659#issuecomment-476869730)

moving to corefx

**Comment by robertborr** [comment]
cc: @ViktorHofer , @safern , @ericstj
