### ISSUE TITLE
UdpClientTest.BeginSend_Success failed in CI on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3641]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/4595/console
```
System.Net.Sockets.Tests.UdpClientTest.BeginSend_Success [FAIL]
        System.Net.Sockets.SocketException : An address incompatible with the requested protocol was used
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(3217,0): at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(3162,0): at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\UDPClient.cs(598,0): at System.Net.Sockets.UdpClient.BeginSend(Byte[] datagram, Int32 bytes, IPEndPoint endPoint, AsyncCallback requestCallback, Object state)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\tests\FunctionalTests\UdpClientTest.cs(59,0): at System.Net.Sockets.Tests.UdpClientTest.BeginSend_Success()
```
cc: @cipop, @pgavlin, @davidsh

**Comment by CIPop** [comment]
Improved/fixed by 2d6de874008b0ba74c877c5895847421f3adf1af.
