### ISSUE TITLE
SslStream_ConcurrentBidirectionalReadsWrites failing often on Alpine.39 (OpenSSL 1.1.1)

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#36426]
Failing with unusual errors. Alpine 3.9 uses OpenSSL/1.1.1a. - newer than other distros we use.

cc : @bartonjs @janvorli 
 
```
System.AggregateException : One or more errors occurred. (One or more errors occurred. (The encryption operation failed, see inner exception.)) (One or more errors occurred. (The decryption operation failed, see inner exception.))
---- System.AggregateException : One or more errors occurred. (The encryption operation failed, see inner exception.)
-------- System.IO.IOException : The encryption operation failed, see inner exception.
------------ Interop+OpenSsl+SslException : Encrypt failed with OpenSSL error - SSL_ERROR_SSL.
---------------- Interop+Crypto+OpenSslCryptographicException : error:141A10F4:SSL routines:ossl_statem_client_read_transition:unexpected message
---- System.AggregateException : One or more errors occurred. (The decryption operation failed, see inner exception.)
-------- System.IO.IOException : The decryption operation failed, see inner exception.
------------ Interop+OpenSsl+SslException : Decrypt failed with OpenSSL error - SSL_ERROR_SYSCALL.
```
```
  at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /__w/1/s/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 105
   at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_ConcurrentBidirectionalReadsWrites_Success() in /__w/1/s/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs:line 446
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace #1 (System.AggregateException) -----

----- Inner Stack Trace -----
   at System.Net.Security.SslStream.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer) in /__w/1/s/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 1521
   at System.Net.Security.Tests.SslStreamStreamToStreamTest.<>c__DisplayClass17_2.<<SslStream_ConcurrentBidirectionalReadsWrites_Success>b__0>d.MoveNext() in /__w/1/s/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs:line 423
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /__w/1/s/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 77
----- Inner Stack Trace -----
   at Interop.OpenSsl.Encrypt(SafeSslHandle context, ReadOnlyMemory`1 input, Byte[]& output, SslErrorCode& errorCode) in /__w/1/s/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs:line 305
   at System.Net.Security.SslStreamPal.EncryptDecryptHelper(SafeDeleteContext securityContext, ReadOnlyMemory`1 input, Int32 offset, Int32 size, Boolean encrypt, Byte[]& output, Int32& resultSize) in /__w/1/s/src/System.Net.Security/src/System/Net/Security/SslStreamPal.Unix.cs:line 168
----- Inner Stack Trace -----

----- Inner Stack Trace #2 (System.AggregateException) -----

----- Inner Stack Trace -----
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer) in /__w/1/s/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 1420
   at System.Net.Security.Tests.SslStreamStreamToStreamTest.<>c__DisplayClass17_2.<<SslStream_ConcurrentBidirectionalReadsWrites_Success>b__1>d.MoveNext() in /__w/1/s/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs:line 438
----- Inner Stack Trace -----
   at Interop.OpenSsl.Decrypt(SafeSslHandle context, Byte[] outBuffer, Int32 offset, Int32 count, SslErrorCode& errorCode) in /__w/1/s/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs:line 373
   at System.Net.Security.SslStreamPal.EncryptDecryptHelper(SafeDeleteContext securityContext, ReadOnlyMemory`1 input, Int32 offset, Int32 size, Boolean encrypt, Byte[]& output, Int32& resultSize) in /__w/1/s/src/System.Net.Security/src/System/Net/Security/SslStreamPal.Unix.cs:line 172
```

**Comment by wfurt** [comment]
Seems like  1.1.1 can be big deal as well it is claimed as LTS:
https://www.openssl.org/blog/blog/2018/09/11/release111/

**Comment by bartonjs** [comment]
1.1.1 is also used by Ubuntu 18.04.

**Comment by wfurt** [comment]
```furt@net-dale:~/Repro$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
furt@net-dale:~/Repro$ openssl version
OpenSSL 1.1.0g  2 Nov 2017
```

I'll check what version we have on CI machines.

**Comment by wfurt** [comment]
It seems like we have occasional failures there as well. Here is failed official run on 18.10

https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190327.6/workItem/System.Net.Security.Tests

```
System.IO.IOException : The encryption operation failed, see inner exception.
---- Interop+OpenSsl+SslException : SSL Read BIO failed with OpenSSL error - .


   at System.Net.Security.SslStream.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer) in /__w/1/s/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 1521
   at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult) in /__w/1/s/src/Common/src/CoreLib/System/Threading/Tasks/TaskToApm.cs:line 88
   at System.Net.Security.SslStream.EndWrite(IAsyncResult asyncResult) in /__w/1/s/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 779
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) in /__w/5/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/FutureFactory.cs:line 520
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.Tests.SslStreamStreamToStreamTest.<>c__DisplayClass17_2.<<SslStream_ConcurrentBidirectionalReadsWrites_Success>b__0>d.MoveNext() in /__w/1/s/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs:line 423
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /__w/1/s/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 77
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /__w/1/s/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 105
   at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_ConcurrentBidirectionalReadsWrites_Success() in /__w/1/s/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs:line 446
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Interop.OpenSsl.BioRead(SafeBioHandle bio, Byte[] buffer, Int32 count) in /__w/1/s/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs:line 473
   at Interop.OpenSsl.Encrypt(SafeSslHandle context, ReadOnlyMemory`1 input, Byte[]& output, SslErrorCode& errorCode) in /__w/1/s/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs:line 312
   at System.Net.Security.SslStreamPal.EncryptDecryptHelper(SafeDeleteContext securityContext, ReadOnlyMemory`1 input, Int32 offset, Int32 size, Boolean encrypt, Byte[]& output, Int32& resultSize) in /__w/1/s/src/System.Net.Security/src/System/Net/Security/SslStreamPal.Unix.cs:line 168
```

**Comment by tmds** [comment]
@wfurt @bartonjs these tests are failing often on my Fedora 30 machine.

Failing tests have:
```
---- Interop+OpenSsl+SslException : SSL Read BIO failed with OpenSSL error - .
```

In runs I typically see 2 or 3 of these tests fail: `System.Net.Security.Tests.SslStreamStreamToStreamTest_MemoryAsync.SslStream_ConcurrentBidirectionalReadsWrites_Success`, `System.Net.Security.Tests.SslStreamStreamToStreamTest_Async.SslStream_ConcurrentBidirectionalReadsWrites_Success`, `System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.SslStream_ConcurrentBidirectionalReadsWrites_Success`.

When running the tests separately, they don't fail.

Full test run:
```
  Discovering: System.Net.Security.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Security.Tests (found 178 of 275 test cases)
  Starting:    System.Net.Security.Tests (parallel test collections = on, max threads = 16)
    System.Net.Security.Tests.SslStreamEKUTest.SslStream_SelfSignedClientEKUClientAuth_Ok [SKIP]
      Condition(s) not met: "IsRootCertificateInstalled"
    System.Net.Security.Tests.SslStreamEKUTest.SslStream_ServerEKUClientAuth_Fails [SKIP]
      Condition(s) not met: "IsRootCertificateInstalled"
    System.Net.Security.Tests.SslStreamEKUTest.SslStream_ClientEKUServerAuth_Fails [SKIP]
      Condition(s) not met: "IsRootCertificateInstalled"
    System.Net.Security.Tests.SslStreamEKUTest.SslStream_NoEKUServerAuth_Ok [SKIP]
      Condition(s) not met: "IsRootCertificateInstalled"
    System.Net.Security.Tests.SslStreamEKUTest.SslStream_NoEKUClientAuth_Ok [SKIP]
      Condition(s) not met: "IsRootCertificateInstalled"
    System.Net.Security.Tests.SslStreamStreamToStreamTest_Async.SslStream_ConcurrentBidirectionalReadsWrites_Success [FAIL]
      System.IO.IOException : The encryption operation failed, see inner exception.
      ---- Interop+OpenSsl+SslException : SSL Read BIO failed with OpenSSL error - .
      Stack Trace:
        /home/tmds/repos/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(1521,0): at System.Net.Security.SslStream.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
        /home/tmds/repos/corefx/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(422,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.<>c__DisplayClass17_2.<<SslStream_ConcurrentBidirectionalReadsWrites_Success>b__0>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        /home/tmds/repos/corefx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(83,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /home/tmds/repos/corefx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(111,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /home/tmds/repos/corefx/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(415,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_ConcurrentBidirectionalReadsWrites_Success()
        --- End of stack trace from previous location where exception was thrown ---
        ----- Inner Stack Trace -----
        /home/tmds/repos/corefx/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs(514,0): at Interop.OpenSsl.BioRead(SafeBioHandle bio, Byte[] buffer, Int32 count)
        /home/tmds/repos/corefx/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs(353,0): at Interop.OpenSsl.Encrypt(SafeSslHandle context, ReadOnlyMemory`1 input, Byte[]& output, SslErrorCode& errorCode)
        /home/tmds/repos/corefx/src/System.Net.Security/src/System/Net/Security/SslStreamPal.Unix.cs(168,0): at System.Net.Security.SslStreamPal.EncryptDecryptHelper(SafeDeleteContext securityContext, ReadOnlyMemory`1 input, Int32 offset, Int32 size, Boolean encrypt, Byte[]& output, Int32& resultSize)
    System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.SslStream_ConcurrentBidirectionalReadsWrites_Success [FAIL]
      System.IO.IOException : The encryption operation failed, see inner exception.
      ---- Interop+OpenSsl+SslException : SSL Read BIO failed with OpenSSL error - .
      Stack Trace:
        /home/tmds/repos/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(1521,0): at System.Net.Security.SslStream.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
        /home/tmds/repos/corefx/src/Common/src/CoreLib/System/Threading/Tasks/TaskToApm.cs(88,0): at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult)
        /home/tmds/repos/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.cs(788,0): at System.Net.Security.SslStream.EndWrite(IAsyncResult asyncResult)
        /__w/1/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/FutureFactory.cs(514,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
        --- End of stack trace from previous location where exception was thrown ---
        /home/tmds/repos/corefx/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(422,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.<>c__DisplayClass17_2.<<SslStream_ConcurrentBidirectionalReadsWrites_Success>b__0>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        /home/tmds/repos/corefx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(83,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /home/tmds/repos/corefx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(111,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /home/tmds/repos/corefx/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(415,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_ConcurrentBidirectionalReadsWrites_Success()
        --- End of stack trace from previous location where exception was thrown ---
        ----- Inner Stack Trace -----
        /home/tmds/repos/corefx/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs(514,0): at Interop.OpenSsl.BioRead(SafeBioHandle bio, Byte[] buffer, Int32 count)
        /home/tmds/repos/corefx/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs(353,0): at Interop.OpenSsl.Encrypt(SafeSslHandle context, ReadOnlyMemory`1 input, Byte[]& output, SslErrorCode& errorCode)
        /home/tmds/repos/corefx/src/System.Net.Security/src/System/Net/Security/SslStreamPal.Unix.cs(168,0): at System.Net.Security.SslStreamPal.EncryptDecryptHelper(SafeDeleteContext securityContext, ReadOnlyMemory`1 input, Int32 offset, Int32 size, Boolean encrypt, Byte[]& output, Int32& resultSize)
  Finished:    System.Net.Security.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Security.Tests  Total: 4299, Errors: 0, Failed: 2, Skipped: 5, Time: 12.948s
```

**Comment by tmds** [comment]
The issue occurs when BioRead is called with count zero.
Probably something needs to be added here to handle capacityNeeded being zero:

https://github.com/dotnet/corefx/blob/f5be0283c5e00dd823a41f671f9c9a41170f0a85/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs#L346-L353

**Comment by wfurt** [comment]
yes, I was looking at it last week. Interestingly, when I modified test to use TLS1.2 it does not happen. 
I did talk to @bartonjs  and if we read full TLS frame or when we encrypting data, we _should_ get something out. 
I think we need to understand what is going on before  choosing fix. I'm testing on Ubuntu 18.10 but I wold expect Fedora to have similar behavior.

Do you want to take it @tmds ?

**Comment by krwq** [comment]
I got local repro, I can take a look

**Comment by krwq** [comment]
I'll likely not start until tomorrow, @tmds let me know if you want to take a look or if you've already started

**Comment by tmds** [comment]
@krwq go ahead. Other than observe the issue occurs when BioRead is called with count zero, I have not worked on this.

**Comment by krwq** [comment]
Ok, I found the root cause - SSL_read/SSL_write on the same context are run in parallel and that API does not seem to work (when I lock all read/writes this issue does not occur anymore) - I haven't had time to figure out if this is an OpenSSL issue or if this is by design and we should be locking on our side. I will send PR with a fix tomorrow morning regardless if this is by design but need to determine if we should open an issue against OpenSSL and have corresponding corefx issue to remove the workaround or not

**Comment by janvorli** [comment]
There is some discussion on simultaneous SSL_read / write on stackoverflow:
https://stackoverflow.com/questions/21527206/ssl-read-and-ssl-write-simultaneously

**Comment by bartonjs** [comment]
https://www.openssl.org/docs/faq.html#PROG1 seems to sum it up:

> Is OpenSSL thread-safe?

> Yes but with some limitations; for example, an SSL connection cannot be used concurrently by multiple threads.

I guess we've just been lucky for the last few years.

**Comment by stephentoub** [comment]
What is the fix here?  The potential perf impact of adding locking around ssl_read/write makes me scared.

**Comment by krwq** [comment]
@stephentoub so far the only fix I found (I did go through various SO threads) is to lock per SslContext on every call to SSL_read - there are two places in the code which need that:
https://github.com/dotnet/corefx/blob/c3981ca2455f8a6593301bac1adb363d02934954/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs#L324
https://github.com/dotnet/corefx/blob/c3981ca2455f8a6593301bac1adb363d02934954/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs#L380

ideally (assuming we want the fix) we probably would want to fix it directly in the interop layer (i.e. shim to the native call).

The reason I've been delaying the fix is because I wanted to first check what perf imapct this change will have and if it is worth to justify it - it feels to me that in the most common scenario no one will do full duplex communication and rather do request/response but we need more data to confirm this.

Also I'm wondering if it actually will have significant impact as encrypt/decrypt seem much heavier than the actual lock so perhaps this will be very cheap - if we are talking very small difference (i.e. less than 2-5% in the end to end scenario) then it might be worth to take the fix otherwise we might want to collect more data on how frequently this issue is being hit and if there are some other ways to fix this problem without introducing the lock.

**Comment by wfurt** [comment]
That article is 3 years old and we were consistently passing and now we somewhat consistently failing. That seems more than luck. I also don't know what using TLS12  would change anything around lock, but it does. This does not fail during handshake but later when we try to encrypt data.

**Comment by krwq** [comment]
I've been running the code with the fix for some time and I seem to be getting some more issues (with different stack than mentioned above) - when I add a lock on the outer call (SecureChannel.Encrypt/DecryptMessage) I haven't seen any issues so far but left it running for some time.

Here is the stack I'm seeing:

```
      System.Net.Security.Tests.SslStreamStreamToStreamTest_Async.SslStream_ConcurrentBidirectionalReadsWrites_Success [FAIL]
        System.IO.IOException : The decryption operation failed, see inner exception.
        ---- Interop+OpenSsl+SslException : Decrypt failed with OpenSSL error - SSL_ERROR_SYSCALL.
        Stack Trace:
          /home/krwq/src/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(1422,0): at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
          /home/krwq/src/corefx/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(438,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.<>c__DisplayClass17_2.<<SslStream_ConcurrentBidirectionalReadsWrites_Success>b__1>d.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
          /home/krwq/src/corefx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(83,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
          /home/krwq/src/corefx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(111,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
          /home/krwq/src/corefx/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(415,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_ConcurrentBidirectionalReadsWrites_Success()
          --- End of stack trace from previous location where exception was thrown ---
          ----- Inner Stack Trace -----
          /home/krwq/src/corefx/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs(419,0): at Interop.OpenSsl.Decrypt(SafeSslHandle context, Byte[] outBuffer, Int32 offset, Int32 count, SslErrorCode& errorCode)
          /home/krwq/src/corefx/src/System.Net.Security/src/System/Net/Security/SslStreamPal.Unix.cs(172,0): at System.Net.Security.SslStreamPal.EncryptDecryptHelper(SafeDeleteContext securityContext, ReadOnlyMemory`1 input, Int32 offset, Int32 size, Boolean encrypt, Byte[]& output, Int32& resultSize)
```

I suspect it might be something else which also must be locked as well (I suspect SslGetError - currently testing if locking whole Decrypt/Encrypt subroutine actually fixes the issue - I will leave this running in a loop for some time)

**Comment by krwq** [comment]
after extending the lock still no issues (running for around 2h) - I'll do some perf testing and investigate open ssl code to try to understand why we haven't hit this before

**Comment by krwq** [comment]
@wfurt my initial look it seems that openssl implements read and write differently based on protocol and other settings - possibly TLS 1.2 it was more unlikely for something bad to happen - I will be digging a bit more into that

**Comment by ViktorHofer** [comment]
Failed again: https://dnceng.visualstudio.com/public/_build/results?buildId=193446&view=ms.vss-test-web.build-test-results-tab&runId=4669392&resultId=392541
