### ISSUE TITLE
Operation not supported on socket on Console.CancelKeyPress on MacOSX

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#36561]
Copying from here: https://github.com/aspnet/BuildTools/pull/948#issuecomment-479320606 so it's tracked

When attempting to pick up the SDK v3.0.100-preview4-011024, I see this build error on the Mac agents:

```C#
System.ComponentModel.Win32Exception (102): Operation not supported on socket
   at System.ConsolePal.EnsureInitializedCore()
   at System.ConsolePal.ControlCHandlerRegistrar.Register()
   at System.Console.add_CancelKeyPress(ConsoleCancelEventHandler value)
   at Microsoft.DotNet.Cli.Utils.ProcessReaper..ctor(Process process)
   at Microsoft.DotNet.Cli.Utils.ProcessStartInfoExtensions.Execute(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Tools.RestoringCommand.Execute()
   at Microsoft.DotNet.Tools.Publish.PublishCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

It's from a vanilla `dotnet publish` operation on a csproj. Could it be related to https://github.com/dotnet/corefx/pull/35621? 

The build log with the failure: https://dev.azure.com/dnceng/public/_build/results?buildId=141479&view=logs&lineStart=38&jobId=fe4e408a-5576-5fa1-f2ab-61ac24819df6&taskId=961b5bee-1b38-582a-dfd3-29c4c6c56ff0

**Comment by pranavkm** [comment]
cc @stephentoub

**Comment by stephentoub** [comment]
@tmds, this looks like it's related to your recent changes.  Can you take a look please?

**Comment by tmds** [comment]
Probably this will be fixed also if we ignore all errors in https://github.com/dotnet/corefx/pull/36551.

**Comment by wfurt** [comment]
#36551 was merged @pranavkm Give it try with new daily build and let me know.

**Comment by pranavkm** [comment]
This is resolved. Closing
