### ISSUE TITLE
System.Text.Json.Serialization.Tests.CacheTests/MultipleThreads failing on Linux

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#36618]
New test introduced in https://github.com/dotnet/corefx/pull/36549 is failing.

https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190404.4/workItem/System.Text.Json.Tests/analysis/xunit/System.Text.Json.Serialization.Tests.CacheTests~2FMultipleThreads
Fedora.28.Amd64-x64-Release
```text
Unhandled Exception of Type System.AggregateException
Message :
System.AggregateException : One or more errors occurred. (Assert.Equal() Failure
Expected: 1
Actual:   0) (Assert.Equal() Failure
Expected: 1
Actual:   0) (Assert.Equal() Failure
Expected: 1
Actual:   0)
---- Assert.Equal() Failure
Expected: 1
Actual:   0
---- Assert.Equal() Failure
Expected: 1
Actual:   0
---- Assert.Equal() Failure
Expected: 1
Actual:   0
Stack Trace :
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken) in /__w/5/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 4811
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks) in /__w/5/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 4548
   at System.Text.Json.Serialization.Tests.CacheTests.MultipleThreads() in /__w/1/s/src/System.Text.Json/tests/Serialization/CacheTests.cs:line 50
----- Inner Stack Trace #1 (Xunit.Sdk.EqualException) -----
   at System.Text.Json.Serialization.Tests.SimpleTestClass.Verify() in /__w/1/s/src/System.Text.Json/tests/Serialization/TestClasses.cs:line 147
   at System.Text.Json.Serialization.Tests.CacheTests.<MultipleThreads>g__SerializeAndDeserializeObject|0_0(Boolean useEmptyJson) in /__w/1/s/src/System.Text.Json/tests/Serialization/CacheTests.cs:line 39
   at System.Text.Json.Serialization.Tests.CacheTests.<>c__DisplayClass0_0.<MultipleThreads>b__1() in /__w/1/s/src/System.Text.Json/tests/Serialization/CacheTests.cs:line 45
   at System.Threading.Tasks.Task.InnerInvoke() in /__w/5/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2460
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj) in /__w/5/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2439
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /__w/5/s/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 288
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /__w/5/s/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 313
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /__w/5/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2400
----- Inner Stack Trace #2 (Xunit.Sdk.EqualException) -----
   at System.Text.Json.Serialization.Tests.SimpleTestClass.Verify() in /__w/1/s/src/System.Text.Json/tests/Serialization/TestClasses.cs:line 147
   at System.Text.Json.Serialization.Tests.CacheTests.<MultipleThreads>g__SerializeAndDeserializeObject|0_0(Boolean useEmptyJson) in /__w/1/s/src/System.Text.Json/tests/Serialization/CacheTests.cs:line 39
   at System.Text.Json.Serialization.Tests.CacheTests.<>c__DisplayClass0_0.<MultipleThreads>b__1() in /__w/1/s/src/System.Text.Json/tests/Serialization/CacheTests.cs:line 45
   at System.Threading.Tasks.Task.InnerInvoke() in /__w/5/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2460
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj) in /__w/5/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2439
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /__w/5/s/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 288
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /__w/5/s/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 313
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /__w/5/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2400
----- Inner Stack Trace #3 (Xunit.Sdk.EqualException) -----
   at System.Text.Json.Serialization.Tests.SimpleTestClass.Verify() in /__w/1/s/src/System.Text.Json/tests/Serialization/TestClasses.cs:line 147
   at System.Text.Json.Serialization.Tests.CacheTests.<MultipleThreads>g__SerializeAndDeserializeObject|0_0(Boolean useEmptyJson) in /__w/1/s/src/System.Text.Json/tests/Serialization/CacheTests.cs:line 39
   at System.Text.Json.Serialization.Tests.CacheTests.<>c__DisplayClass0_0.<MultipleThreads>b__1() in /__w/1/s/src/System.Text.Json/tests/Serialization/CacheTests.cs:line 45
   at System.Threading.Tasks.Task.InnerInvoke() in /__w/5/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2460
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj) in /__w/5/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2439
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /__w/5/s/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 288
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /__w/5/s/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 313
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /__w/5/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2400
```

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F33520~2Fmerge/test~2Ffunctional~2Fcli~2F/20190404.42/workItem/System.Text.Json.Tests/analysis/xunit/System.Text.Json.Serialization.Tests.CacheTests~2FMultipleThreads
Ubuntu.1604.Arm64-arm64-Release
Ubuntu.1804.Amd64-x64-Release
```text
Message :
System.AggregateException : One or more errors occurred. (Assert.Equal() Failure
Expected: 1
Actual:   0)
---- Assert.Equal() Failure
Expected: 1
Actual:   0
Stack Trace :
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken) in /__w/8/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 4811
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks) in /__w/8/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 4543
   at System.Text.Json.Serialization.Tests.CacheTests.MultipleThreads() in /__w/1/s/src/System.Text.Json/tests/Serialization/CacheTests.cs:line 49
----- Inner Stack Trace -----
   at System.Text.Json.Serialization.Tests.SimpleTestClass.Verify() in /__w/1/s/src/System.Text.Json/tests/Serialization/TestClasses.cs:line 146
   at System.Text.Json.Serialization.Tests.CacheTests.<MultipleThreads>g__SerializeAndDeserializeObject|0_0(Boolean useEmptyJson) in /__w/1/s/src/System.Text.Json/tests/Serialization/CacheTests.cs:line 38
   at System.Text.Json.Serialization.Tests.CacheTests.<>c__DisplayClass0_0.<MultipleThreads>b__1() in /__w/1/s/src/System.Text.Json/tests/Serialization/CacheTests.cs:line 45
   at System.Threading.Tasks.Task.InnerInvoke() in /__w/8/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2450
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj) in /__w/8/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2438
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /__w/8/s/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 288
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /__w/8/s/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 313
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /__w/8/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2400
```

Test disabled in https://github.com/dotnet/corefx/pull/36619

**Comment by safern** [comment]
Note that it is failing on Fedora28 which now runs inside a docker container.
