### ISSUE TITLE
.NET Core ODBC Bridge issue - Unable to load libraries

### ISSUE THREAD

**Issue by deokershesh** [dotnet/corefx#36692]
I have been able to migrate/change .NET Core ODBC code to compile with my own abcOdbc.dll ODBC driver binary successfully. However at runtime, it complains abcOdbc.dll not found (during trying to open the database connection Conn.Open() call). I have this abcOdbc.dll and all dependent binaries are part of PATH environment variable.

Do I need any more environment variable setting? I am using VS2017 for compilation.

Thanks a lot...

**Comment by wfurt** [comment]
Your description does not have enough info @deokershesh You will probably need to share your project files and more specific error you getting.

**Comment by deokershesh** [comment]
@wfurt,
Thanks for response. Kindly find more details below.

I made changes in D:\corefx\src\Common\src\Interop\Windows\Interop.Libraries.cs file by adding below line.

internal const string Abc32 = "abcOdbc.dll";

Accordingly changed the System.Data.Odbc code to make sure compilation of System.Data.Odbc module is successful. Later I compiled below sample program successfully and tried to run, it reports below error "unable to load abcOdbc.dll". However abcOdbc.dll is part of the PATH environment variable.

namespace FirstODBCSamp
{
    class Class1
    {
        static void Main(string[] args)
        {
            // Build a connection and SQL strings
            string connectionString = "Driver={ABC ODBC DRIVER (64-bit)};Database=mydb;server=myserv;UID=abc;PWD=xxxx;";
            string SQL = "SELECT * FROM t1;";
            // Create connection object
            AbcConnection conn = new AbcConnection(connectionString);
            // Create command object
            AbcCommand cmd = new AbcCommand(SQL);
            cmd.Connection = conn;
            // Open connection
            conn.Open();
            // Call command's ExecuteReader
            AbcDataReader reader = cmd.ExecuteReader();
            // Read the reader and display results on the console
            while (reader.Read())
            {
                Console.Write("OrderID:" + reader.GetInt32(0).ToString());
                Console.Write(" ,");
                Console.WriteLine("Customer:" + reader.GetString(1).ToString());
            }
            // close reader and connection
            reader.Close();
            conn.Close();
        }
    }
}

C:\>"D:\corefx\.dotnet\dotnet.exe" exec "c:\users\abc\source\repos\ConsoleApp1\ConsoleApp1\bin\x64\Debug\netcoreapp2.2\ConsoleApp1.dll"

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'abcOdbc.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Interop.Odbc.SQLAllocHandle(Int16 HandleType, IntPtr InputHandle, IntPtr& OutputHandle)
   at System.Data.Odbc.OdbcHandle..ctor(SQL_HANDLE handleType, IntPtr parentHandle) in D:\corefx\src\System.Data.Odbc\src\System\Data\Odbc\OdbcHandle.cs:line 36
   at System.Data.Odbc.OdbcEnvironmentHandle..ctor() in D:\corefx\src\System.Data.Odbc\src\System\Data\Odbc\OdbcEnvironmentHandle.cs:line 13
   at System.Data.Odbc.OdbcEnvironment.GetGlobalEnvironmentHandle() in D:\corefx\src\System.Data.Odbc\src\System\Data\Odbc\OdbcEnvironment.cs:line 26
   at System.Data.Odbc.AbcConnectionOpen..ctor(AbcConnection outerConnection, AbcConnectionString connectionOptions) in D:\corefx\src\System.Data.Odbc\src\System\Data\Odbc\OdbcConnectionOpen.cs:line 15
   at System.Data.Odbc.AbcConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject) in D:\corefx\src\System.Data.Odbc\src\System\Data\Odbc\OdbcConnectionFactory.cs:line 32
   at System.Data.ProviderBase.DbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions) in D:\corefx\src\Common\src\System\Data\ProviderBase\DbConnectionFactory.cs:line 374
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions) in D:\corefx\src\Common\src\System\Data\ProviderBase\DbConnectionFactory.cs:line 96
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection) in D:\corefx\src\System.Data.Odbc\src\Common\System\Data\ProviderBase\DbConnectionFactory.cs:line 130
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in D:\corefx\src\Common\src\System\Data\ProviderBase\DbConnectionInternal.cs:line 325
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in D:\corefx\src\Common\src\System\Data\ProviderBase\DbConnectionClosed.cs:line 37
   at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory) in D:\corefx\src\Common\src\System\Data\ProviderBase\DbConnectionInternal.cs:line 295
   at System.Data.Odbc.AbcConnection.Open() in D:\corefx\src\System.Data.Odbc\src\System\Data\Odbc\OdbcConnection.cs:line 573
   at FirstODBCSamp.Class1.Main(String[] args) in C:\Users\abc\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 19

**Comment by deokershesh** [comment]
Any help/input please? We are stuck, any help/pointers would be highly appreciated.
Thanks

**Comment by ericstj** [comment]
> it reports below error "unable to load abcOdbc.dll". However abcOdbc.dll is part of the PATH environment variable.

This is due to the library-loading behavior in .NETCore.  CoreCLR only probes native binaries that appear in the deps file.  @vitek-karas is there any workaround to build a .NETCore app and get it to pinvoke to a native library that doesn't come from a nuget package / appear in the deps file?

**Comment by AaronRobinsonMSFT** [comment]
@deokershesh As @ericstj mentioned updating the corresponding `.deps.json` would work or supplying a callback (https://docs.microsoft.com/dotnet/api/system.runtime.loader.assemblyloadcontext.resolvingunmanageddll) on the [default ALC](https://docs.microsoft.com/dotnet/api/system.runtime.loader.assemblyloadcontext.default) will also give you a chance to discover the native library.

**Comment by jeffschwMSFT** [comment]
There are 4 ways that we find native binaries:
1. Via a relative path that is part of the deps.json
2. If the native binary is next to the .NET assembly
3. Via callbacks on AssemblyLoadContext
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.loadunmanageddllfrompath?view=netcore-3.0
(new in .NET Core 3.0) https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.resolvingunmanageddll?view=netcore-3.0
4. Via NativeLibrary resolution (new in .NET Core 3.0)
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.setdllimportresolver?view=netcore-3.0#System_Runtime_InteropServices_NativeLibrary_SetDllImportResolver_System_Reflection_Assembly_System_Runtime_InteropServices_DllImportResolver_
5. Default search path of dlopen/LoadLibrary.

So as the library developer it is possible on .NET Core 3.0 to resolve arbitrary native dlls.  

@deokershesh are you looking to target just .NET Core 3.0+ or was this going to be a .NET Standard library?

**Comment by deokershesh** [comment]
Thanks @jeffschwMSFT, I will try above steps and update the forum.

Primarily, we are looking ".NET Core Database Provider(native using our own ODBC Driver)" for our Database. Currently I am using .NET Core 2.2. I cloned corefx as follows and that cloned .NET Core 2.2. How do I get the .NET Core 3.0? Is it stable enough?

git clone https://github.com/dotnet/corefx.git

**Comment by wfurt** [comment]
Unless I'm mistaken, the Odbc.dll is just dispatcher redirecting requests to actual database driver, right?  
Could you register your database with ODBC instead of modifying .Net? That was the whole point of ODBC that applications would not need to deal  details of specific databases.

**Comment by deokershesh** [comment]
@wfurt, Original .NET ODBC Bridge code uses odbc32.dll. This odbc32.dll provides implementation of all the ODBC API calls from the .NET Layer (C#). We replaced odbc32.dll with abcOdbc.dll and compiled (System.Data.Odbc.dll) the .NET ODBC Bridge code successfully. As far as, set of APIs are concerned both odbc32.dll and abcOdbc.dll are exactly same, as it follows Standard ODBC specification. Now at runtime, somehow odbc32.dll (looks like its known to .NET Core Runtime!) is loaded appropriately, however .NET Core runtime seems to be complaining to load abcOdbc.dll (since its external to .NET Core library??). Hence, how do we let .NET Core runtime know that abcOdbc.dll should be loaded successfully??

**Comment by deokershesh** [comment]
Just to add, Yes, I could use the .NET ODBC Bridge code directly with my ODBC Driver and it connects to my database successfully. Now, we have few "Native" supports to be done in the .NET ODBC Bridge and make/call it ".NET Core Provider for our Database", however we will continue to use our ODBC Driver "directly/natively" in the .NET ODBC Bridge code, hence need to modify the .NET ODBC Bridge code to make it suitable for our ".NET Core Provider".

**Comment by AaronRobinsonMSFT** [comment]
@deokershesh .NET Core 3.0 is in Preview 4 and quickly approaching GA. For right now, you can try local nightly builds [here](https://github.com/dotnet/core-sdk#installers-and-binaries). We do not recommend putting .NET Core 3.0 into production, but it is stable enough to try out scenarios. If you get a chance to try it, please provide feedback here with your experience and feel free to offer suggestions on found issues.

**Comment by deokershesh** [comment]
The unable to load library issue seems to have resolved by making changes in following file.

D:\corefx\eng\versioning.targets ==> The dependency has been changed to "LegacyBehavior".

**Comment by deokershesh** [comment]
I continue to use .NET Core 2.2
