### ISSUE TITLE
System.Globalizations.Extensions unit tests fail on Win10 1903 (19H1) builds

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/corefx#36758]
The test project helper method `GetIdnaTestTxt()` special-cases the current OS version to select the appropriate Idna test data file. It looks like the underlying OS behavior changed in 1903 (19H1) and the test data needs to be updated.

I've copied one such failure below.

```txt
      System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Invalid [FAIL]
        Assert.All() Failure: 8 out of 2375 items in the collection did not pass.
        [2106]: Item: System.Globalization.Tests.Unicode_9_0_IdnaTest
                System.Exception: Expected IdnMapping.GetAscii("\uD803\uDE71\u0842\uD836\uDEA8\uFF61\uD873\uDF16\u2D11\u200D") to throw an ArgumentException.
                   at System.Globalization.Tests.IdnMappingIdnaConformanceTests.<>c.<GetAscii_Invalid>b__2_1(IConformanceIdnaTest entry) in C:\corefx\src\System.Globalization.Extensions\tests\IdnMapping\IdnMappingIdnaConformanceTests.cs:line 96
                   at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\projects\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 36
```

(My machine is 18362.53.)

**Comment by GrabYourPitchforks** [comment]
Looks like Win10 19H1 uses the Unicode 11.0 IDNA tables (still tracking down changes in the OS repo to confirm this). We might have to refactor how the tests work on our side since the format of the IdnaTest.txt file changed between Unicode 9.0 and Unicode 11.0.

**Comment by ViktorHofer** [comment]
Yeah I was hitting that too and that's expected. I did the update the last time but hadn't had time yet to update the IDNA table for 19H1.

**Comment by tarekgh** [comment]
I confirmed with Windows team they are using Unicode 11.0.
