### ISSUE TITLE
FtpWebRequest Making Slow Requests and Throws WebExceptions

### ISSUE THREAD

**Issue by jdhawley** [dotnet/corefx#36818]
Hi all,

I've been working in .NET Framework to do some data retrieval and aggregation from different sources. However, project requirements have recently changed and I'm migrating a lot of the code from .NET Framework to .NET Core. Some of the data I'm pulling is accessed through an FTP site. It seems to work fine using .NET Framework but .NET Core is too slow for my project requirements and frequently throws WebExceptions while executing.

Below you will find the code I'm running, a "good" result (using .NET Framework), and a "bad" result (using .NET Core). I tried to upload a zip file containing the solution so somebody else could run the code themselves, but I couldn't get it to upload here for some reason. Instead, I just created a [repo with the source code](https://github.com/jdhawley/NetCoreFtpWebRequestIssue) so you can view the solution.

# Code and Results
<details>
  <summary>Code</summary>
  
```C#
public static void TestRtlmpRequests()
{
    DateTime operatingDay = DateTime.Today.AddDays(-1);
    for (DateTime intervalEnd = operatingDay.Date.AddMinutes(5); intervalEnd <= operatingDay.AddDays(1); intervalEnd = intervalEnd.AddMinutes(5))
    {
        string year = intervalEnd.AddMinutes(-5).ToString("yyyy");
        string month = intervalEnd.AddMinutes(-5).ToString("MM");
        string day = intervalEnd.AddMinutes(-5).ToString("dd");
        string filename = "RTBM-LMP-SL-" + intervalEnd.ToString("yyyyMMddHHmm") + ".csv";
        string url = $"ftp://pubftp.spp.org/Markets/RTBM/LMP_By_SETTLEMENT_LOC/{year}/{month}/By_Interval/{day}/{filename}";

        var watch = new System.Diagnostics.Stopwatch();
        try
        {
            watch.Start();
            string response = GetRtlmp(url);
            watch.Stop();
            Console.WriteLine($"SUCCESS ({watch.ElapsedMilliseconds}ms): {filename}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"FAILED ({watch.ElapsedMilliseconds}ms): {filename}");
            Console.WriteLine($"   {ex.ToString()}");
        }
    }
}

private static string GetRtlmp(string url)
{
    FtpWebRequest downloadRequest = (FtpWebRequest)WebRequest.Create(url);
    downloadRequest.Method = WebRequestMethods.Ftp.DownloadFile;
    var response = downloadRequest.GetResponse();
    var responseStream = response.GetResponseStream();

    using (StreamReader reader = new StreamReader(responseStream))
    {
        return reader.ReadToEnd();
    }
}
```
</details>

<details>
<summary>"Good" Results (.NET Framework)</summary>

SUCCESS (9718ms): RTBM-LMP-SL-201904100005.csv
SUCCESS (412ms): RTBM-LMP-SL-201904100010.csv
SUCCESS (420ms): RTBM-LMP-SL-201904100015.csv
SUCCESS (423ms): RTBM-LMP-SL-201904100020.csv
SUCCESS (405ms): RTBM-LMP-SL-201904100025.csv
SUCCESS (426ms): RTBM-LMP-SL-201904100030.csv
SUCCESS (564ms): RTBM-LMP-SL-201904100035.csv
SUCCESS (421ms): RTBM-LMP-SL-201904100040.csv
SUCCESS (417ms): RTBM-LMP-SL-201904100045.csv
SUCCESS (437ms): RTBM-LMP-SL-201904100050.csv
SUCCESS (410ms): RTBM-LMP-SL-201904100055.csv
SUCCESS (515ms): RTBM-LMP-SL-201904100100.csv
SUCCESS (416ms): RTBM-LMP-SL-201904100105.csv
SUCCESS (427ms): RTBM-LMP-SL-201904100110.csv
SUCCESS (420ms): RTBM-LMP-SL-201904100115.csv
SUCCESS (412ms): RTBM-LMP-SL-201904100120.csv
SUCCESS (413ms): RTBM-LMP-SL-201904100125.csv
SUCCESS (412ms): RTBM-LMP-SL-201904100130.csv
SUCCESS (413ms): RTBM-LMP-SL-201904100135.csv
SUCCESS (419ms): RTBM-LMP-SL-201904100140.csv
SUCCESS (461ms): RTBM-LMP-SL-201904100145.csv
SUCCESS (418ms): RTBM-LMP-SL-201904100150.csv
SUCCESS (403ms): RTBM-LMP-SL-201904100155.csv
SUCCESS (425ms): RTBM-LMP-SL-201904100200.csv
SUCCESS (408ms): RTBM-LMP-SL-201904100205.csv
SUCCESS (422ms): RTBM-LMP-SL-201904100210.csv
SUCCESS (438ms): RTBM-LMP-SL-201904100215.csv
SUCCESS (420ms): RTBM-LMP-SL-201904100220.csv
SUCCESS (413ms): RTBM-LMP-SL-201904100225.csv
SUCCESS (409ms): RTBM-LMP-SL-201904100230.csv
SUCCESS (406ms): RTBM-LMP-SL-201904100235.csv
SUCCESS (420ms): RTBM-LMP-SL-201904100240.csv
SUCCESS (421ms): RTBM-LMP-SL-201904100245.csv
SUCCESS (399ms): RTBM-LMP-SL-201904100250.csv
SUCCESS (420ms): RTBM-LMP-SL-201904100255.csv
SUCCESS (412ms): RTBM-LMP-SL-201904100300.csv
SUCCESS (404ms): RTBM-LMP-SL-201904100305.csv
SUCCESS (430ms): RTBM-LMP-SL-201904100310.csv
SUCCESS (434ms): RTBM-LMP-SL-201904100315.csv
SUCCESS (418ms): RTBM-LMP-SL-201904100320.csv
SUCCESS (416ms): RTBM-LMP-SL-201904100325.csv
SUCCESS (428ms): RTBM-LMP-SL-201904100330.csv
SUCCESS (414ms): RTBM-LMP-SL-201904100335.csv
SUCCESS (411ms): RTBM-LMP-SL-201904100340.csv
SUCCESS (406ms): RTBM-LMP-SL-201904100345.csv
SUCCESS (397ms): RTBM-LMP-SL-201904100350.csv
SUCCESS (405ms): RTBM-LMP-SL-201904100355.csv
SUCCESS (449ms): RTBM-LMP-SL-201904100400.csv
SUCCESS (392ms): RTBM-LMP-SL-201904100405.csv
SUCCESS (404ms): RTBM-LMP-SL-201904100410.csv
SUCCESS (388ms): RTBM-LMP-SL-201904100415.csv
SUCCESS (406ms): RTBM-LMP-SL-201904100420.csv
SUCCESS (407ms): RTBM-LMP-SL-201904100425.csv
SUCCESS (385ms): RTBM-LMP-SL-201904100430.csv
SUCCESS (406ms): RTBM-LMP-SL-201904100435.csv
SUCCESS (396ms): RTBM-LMP-SL-201904100440.csv
SUCCESS (400ms): RTBM-LMP-SL-201904100445.csv
SUCCESS (403ms): RTBM-LMP-SL-201904100450.csv
SUCCESS (400ms): RTBM-LMP-SL-201904100455.csv
SUCCESS (394ms): RTBM-LMP-SL-201904100500.csv
SUCCESS (390ms): RTBM-LMP-SL-201904100505.csv
SUCCESS (388ms): RTBM-LMP-SL-201904100510.csv
SUCCESS (404ms): RTBM-LMP-SL-201904100515.csv
SUCCESS (417ms): RTBM-LMP-SL-201904100520.csv
SUCCESS (410ms): RTBM-LMP-SL-201904100525.csv
SUCCESS (461ms): RTBM-LMP-SL-201904100530.csv
SUCCESS (386ms): RTBM-LMP-SL-201904100535.csv
SUCCESS (411ms): RTBM-LMP-SL-201904100540.csv
SUCCESS (587ms): RTBM-LMP-SL-201904100545.csv
SUCCESS (415ms): RTBM-LMP-SL-201904100550.csv
SUCCESS (401ms): RTBM-LMP-SL-201904100555.csv
SUCCESS (461ms): RTBM-LMP-SL-201904100600.csv
</details>

<details>
<summary>"Bad" Results (.NET Core)</summary>

SUCCESS (9310ms): RTBM-LMP-SL-201904100005.csv
SUCCESS (10990ms): RTBM-LMP-SL-201904100010.csv
FAILED (277ms): RTBM-LMP-SL-201904100015.csv
   System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive
   at System.Net.FtpWebRequest.SyncRequestCallback(Object obj)
   at System.Net.CommandStream.InvokeRequestCallback(Object obj)
   at System.Net.CommandStream.Abort(Exception e)
   at System.Net.FtpWebRequest.FinishRequestStage(RequestStage stage)
   at System.Net.FtpWebRequest.GetResponse()
   at EnelDataRetrievalLibrary.SppRtlmp.GetRtlmp(String url) in C:\Users\x2jdhawl\source\repos\EnelDataRetrievalFramework\EnelDataRetrievalLibrary\SppRtlmp.cs:line 49
   at EnelDataRetrievalLibrary.SppRtlmp.TestRtlmpRequests() in C:\Users\x2jdhawl\source\repos\EnelDataRetrievalFramework\EnelDataRetrievalLibrary\SppRtlmp.cs:line 28
FAILED (128ms): RTBM-LMP-SL-201904100020.csv
   System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive
   at System.Net.FtpWebRequest.SyncRequestCallback(Object obj)
   at System.Net.CommandStream.InvokeRequestCallback(Object obj)
   at System.Net.CommandStream.Abort(Exception e)
   at System.Net.FtpWebRequest.FinishRequestStage(RequestStage stage)
   at System.Net.FtpWebRequest.GetResponse()
   at EnelDataRetrievalLibrary.SppRtlmp.GetRtlmp(String url) in C:\Users\x2jdhawl\source\repos\EnelDataRetrievalFramework\EnelDataRetrievalLibrary\SppRtlmp.cs:line 49
   at EnelDataRetrievalLibrary.SppRtlmp.TestRtlmpRequests() in C:\Users\x2jdhawl\source\repos\EnelDataRetrievalFramework\EnelDataRetrievalLibrary\SppRtlmp.cs:line 28
SUCCESS (9296ms): RTBM-LMP-SL-201904100025.csv
SUCCESS (15964ms): RTBM-LMP-SL-201904100030.csv
SUCCESS (9914ms): RTBM-LMP-SL-201904100035.csv
FAILED (124ms): RTBM-LMP-SL-201904100040.csv
   System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive
   at System.Net.FtpWebRequest.SyncRequestCallback(Object obj)
   at System.Net.CommandStream.InvokeRequestCallback(Object obj)
   at System.Net.CommandStream.Abort(Exception e)
   at System.Net.FtpWebRequest.FinishRequestStage(RequestStage stage)
   at System.Net.FtpWebRequest.GetResponse()
   at EnelDataRetrievalLibrary.SppRtlmp.GetRtlmp(String url) in C:\Users\x2jdhawl\source\repos\EnelDataRetrievalFramework\EnelDataRetrievalLibrary\SppRtlmp.cs:line 49
   at EnelDataRetrievalLibrary.SppRtlmp.TestRtlmpRequests() in C:\Users\x2jdhawl\source\repos\EnelDataRetrievalFramework\EnelDataRetrievalLibrary\SppRtlmp.cs:line 28
FAILED (127ms): RTBM-LMP-SL-201904100045.csv
   System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive
   at System.Net.FtpWebRequest.SyncRequestCallback(Object obj)
   at System.Net.CommandStream.InvokeRequestCallback(Object obj)
   at System.Net.CommandStream.Abort(Exception e)
   at System.Net.FtpWebRequest.FinishRequestStage(RequestStage stage)
   at System.Net.FtpWebRequest.GetResponse()
   at EnelDataRetrievalLibrary.SppRtlmp.GetRtlmp(String url) in C:\Users\x2jdhawl\source\repos\EnelDataRetrievalFramework\EnelDataRetrievalLibrary\SppRtlmp.cs:line 49
   at EnelDataRetrievalLibrary.SppRtlmp.TestRtlmpRequests() in C:\Users\x2jdhawl\source\repos\EnelDataRetrievalFramework\EnelDataRetrievalLibrary\SppRtlmp.cs:line 28
FAILED (119ms): RTBM-LMP-SL-201904100050.csv
   System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive
   at System.Net.FtpWebRequest.SyncRequestCallback(Object obj)
   at System.Net.CommandStream.InvokeRequestCallback(Object obj)
   at System.Net.CommandStream.Abort(Exception e)
   at System.Net.FtpWebRequest.FinishRequestStage(RequestStage stage)
   at System.Net.FtpWebRequest.GetResponse()
   at EnelDataRetrievalLibrary.SppRtlmp.GetRtlmp(String url) in C:\Users\x2jdhawl\source\repos\EnelDataRetrievalFramework\EnelDataRetrievalLibrary\SppRtlmp.cs:line 49
   at EnelDataRetrievalLibrary.SppRtlmp.TestRtlmpRequests() in C:\Users\x2jdhawl\source\repos\EnelDataRetrievalFramework\EnelDataRetrievalLibrary\SppRtlmp.cs:line 28
FAILED (116ms): RTBM-LMP-SL-201904100055.csv
   System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive
   at System.Net.FtpWebRequest.SyncRequestCallback(Object obj)
   at System.Net.CommandStream.InvokeRequestCallback(Object obj)
   at System.Net.CommandStream.Abort(Exception e)
   at System.Net.FtpWebRequest.FinishRequestStage(RequestStage stage)
   at System.Net.FtpWebRequest.GetResponse()
   at EnelDataRetrievalLibrary.SppRtlmp.GetRtlmp(String url) in C:\Users\x2jdhawl\source\repos\EnelDataRetrievalFramework\EnelDataRetrievalLibrary\SppRtlmp.cs:line 49
   at EnelDataRetrievalLibrary.SppRtlmp.TestRtlmpRequests() in C:\Users\x2jdhawl\source\repos\EnelDataRetrievalFramework\EnelDataRetrievalLibrary\SppRtlmp.cs:line 28
SUCCESS (9175ms): RTBM-LMP-SL-201904100100.csv
SUCCESS (9541ms): RTBM-LMP-SL-201904100105.csv
FAILED (144ms): RTBM-LMP-SL-201904100110.csv
   System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive
   at System.Net.FtpWebRequest.SyncRequestCallback(Object obj)
   at System.Net.CommandStream.InvokeRequestCallback(Object obj)
   at System.Net.CommandStream.Abort(Exception e)
   at System.Net.FtpWebRequest.FinishRequestStage(RequestStage stage)
   at System.Net.FtpWebRequest.GetResponse()
   at EnelDataRetrievalLibrary.SppRtlmp.GetRtlmp(String url) in C:\Users\x2jdhawl\source\repos\EnelDataRetrievalFramework\EnelDataRetrievalLibrary\SppRtlmp.cs:line 49
   at EnelDataRetrievalLibrary.SppRtlmp.TestRtlmpRequests() in C:\Users\x2jdhawl\source\repos\EnelDataRetrievalFramework\EnelDataRetrievalLibrary\SppRtlmp.cs:line 28
FAILED (125ms): RTBM-LMP-SL-201904100115.csv
   System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive
   at System.Net.FtpWebRequest.SyncRequestCallback(Object obj)
   at System.Net.CommandStream.InvokeRequestCallback(Object obj)
   at System.Net.CommandStream.Abort(Exception e)
   at System.Net.FtpWebRequest.FinishRequestStage(RequestStage stage)
   at System.Net.FtpWebRequest.GetResponse()
   at EnelDataRetrievalLibrary.SppRtlmp.GetRtlmp(String url) in C:\Users\x2jdhawl\source\repos\EnelDataRetrievalFramework\EnelDataRetrievalLibrary\SppRtlmp.cs:line 49
   at EnelDataRetrievalLibrary.SppRtlmp.TestRtlmpRequests() in C:\Users\x2jdhawl\source\repos\EnelDataRetrievalFramework\EnelDataRetrievalLibrary\SppRtlmp.cs:line 28
FAILED (151ms): RTBM-LMP-SL-201904100120.csv
   System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive
   at System.Net.FtpWebRequest.SyncRequestCallback(Object obj)
   at System.Net.CommandStream.InvokeRequestCallback(Object obj)
   at System.Net.CommandStream.Abort(Exception e)
   at System.Net.FtpWebRequest.FinishRequestStage(RequestStage stage)
   at System.Net.FtpWebRequest.GetResponse()
   at EnelDataRetrievalLibrary.SppRtlmp.GetRtlmp(String url) in C:\Users\x2jdhawl\source\repos\EnelDataRetrievalFramework\EnelDataRetrievalLibrary\SppRtlmp.cs:line 49
   at EnelDataRetrievalLibrary.SppRtlmp.TestRtlmpRequests() in C:\Users\x2jdhawl\source\repos\EnelDataRetrievalFramework\EnelDataRetrievalLibrary\SppRtlmp.cs:line 28
</details>

**Comment by davidsh** [comment]
Thank you for the bug report and the easy-to-run repro solution.  I was able to run the solution.  I haven't yet gotten WebException from the .NET Core version of it, but it is definitely much slower.  We'll investigate.

**Comment by davidsh** [comment]
One other thing to keep in mind is that FtpWebRequest in .NET Core is consider a "legacy" API. It is there to help developers port .NET Framework code to .NET Core. But it's performance is less than the .NET Framework.  It doesn't have connection pooling, for example.  We recommend developers look to other open-source libraries which have more features and more performance for FTP transport needs.

cc: @karelz

**Comment by jdhawley** [comment]
I see. I didn't realize that FtpWebRequest was considered to be a "legacy" API. A quick Google search for .NET Core FTP came back with results for [FluentFTP](https://github.com/robinrodricks/FluentFTP) and [CoreFTP](https://github.com/sparkeh9/CoreFTP), but I have no experience with either one of them. Are there any specific libraries that are recommended as a successor to FtpWebRequest?

**Comment by jdhawley** [comment]
I just tried executing the same solution again today. Oddly enough, the .NET Core version is working now. Definitely slower and the response times vary anywhere from 600ms to over 10 seconds, but there are no exceptions being thrown and the average response time is ~1.3 seconds. 

Last week, the WebExceptions were unpredictable but consistent. Every execution on my machine or my coworker's machine produced many WebExceptions and most successful requests took 9-10 seconds. Today, we both ran the exact same code and it produced no errors and successful requests only took about 1/6 of the time they did last week. 

I can't explain why the errors were happening last week and I can't explain why it's working now. I'm going to give FluentFTP a shot just in case the errors come back, but I wanted to post an update to say they are not happening at this time.

<details>
<summary>.NET Core Results</summary>

SUCCESS (818ms, AVG:818ms): RTBM-LMP-SL-201904180005.csv
SUCCESS (1082ms, AVG:950ms): RTBM-LMP-SL-201904180010.csv
SUCCESS (1225ms, AVG:1041ms): RTBM-LMP-SL-201904180015.csv
SUCCESS (1701ms, AVG:1206ms): RTBM-LMP-SL-201904180020.csv
SUCCESS (1997ms, AVG:1364ms): RTBM-LMP-SL-201904180025.csv
SUCCESS (907ms, AVG:1288ms): RTBM-LMP-SL-201904180030.csv
SUCCESS (760ms, AVG:1212ms): RTBM-LMP-SL-201904180035.csv
SUCCESS (986ms, AVG:1184ms): RTBM-LMP-SL-201904180040.csv
SUCCESS (1044ms, AVG:1168ms): RTBM-LMP-SL-201904180045.csv
SUCCESS (891ms, AVG:1141ms): RTBM-LMP-SL-201904180050.csv
SUCCESS (822ms, AVG:1112ms): RTBM-LMP-SL-201904180055.csv
SUCCESS (1030ms, AVG:1105ms): RTBM-LMP-SL-201904180100.csv
SUCCESS (2261ms, AVG:1194ms): RTBM-LMP-SL-201904180105.csv
SUCCESS (1873ms, AVG:1242ms): RTBM-LMP-SL-201904180110.csv
SUCCESS (1655ms, AVG:1270ms): RTBM-LMP-SL-201904180115.csv
SUCCESS (1057ms, AVG:1256ms): RTBM-LMP-SL-201904180120.csv
SUCCESS (1029ms, AVG:1243ms): RTBM-LMP-SL-201904180125.csv
SUCCESS (645ms, AVG:1210ms): RTBM-LMP-SL-201904180130.csv
SUCCESS (648ms, AVG:1180ms): RTBM-LMP-SL-201904180135.csv
SUCCESS (636ms, AVG:1153ms): RTBM-LMP-SL-201904180140.csv
SUCCESS (1045ms, AVG:1148ms): RTBM-LMP-SL-201904180145.csv
SUCCESS (1049ms, AVG:1143ms): RTBM-LMP-SL-201904180150.csv
SUCCESS (1260ms, AVG:1148ms): RTBM-LMP-SL-201904180155.csv
SUCCESS (671ms, AVG:1128ms): RTBM-LMP-SL-201904180200.csv
SUCCESS (654ms, AVG:1109ms): RTBM-LMP-SL-201904180205.csv
SUCCESS (648ms, AVG:1092ms): RTBM-LMP-SL-201904180210.csv
SUCCESS (688ms, AVG:1077ms): RTBM-LMP-SL-201904180215.csv
SUCCESS (639ms, AVG:1061ms): RTBM-LMP-SL-201904180220.csv
SUCCESS (842ms, AVG:1053ms): RTBM-LMP-SL-201904180225.csv
SUCCESS (891ms, AVG:1048ms): RTBM-LMP-SL-201904180230.csv
SUCCESS (1435ms, AVG:1060ms): RTBM-LMP-SL-201904180235.csv
SUCCESS (2480ms, AVG:1105ms): RTBM-LMP-SL-201904180240.csv
SUCCESS (2618ms, AVG:1151ms): RTBM-LMP-SL-201904180245.csv
SUCCESS (9577ms, AVG:1398ms): RTBM-LMP-SL-201904180250.csv
SUCCESS (9200ms, AVG:1621ms): RTBM-LMP-SL-201904180255.csv
SUCCESS (8327ms, AVG:1808ms): RTBM-LMP-SL-201904180300.csv
SUCCESS (8278ms, AVG:1982ms): RTBM-LMP-SL-201904180305.csv
SUCCESS (3626ms, AVG:2026ms): RTBM-LMP-SL-201904180310.csv
SUCCESS (2462ms, AVG:2037ms): RTBM-LMP-SL-201904180315.csv
SUCCESS (4586ms, AVG:2101ms): RTBM-LMP-SL-201904180320.csv
SUCCESS (2697ms, AVG:2115ms): RTBM-LMP-SL-201904180325.csv
SUCCESS (2473ms, AVG:2124ms): RTBM-LMP-SL-201904180330.csv
SUCCESS (1460ms, AVG:2108ms): RTBM-LMP-SL-201904180335.csv
SUCCESS (1026ms, AVG:2084ms): RTBM-LMP-SL-201904180340.csv
SUCCESS (1488ms, AVG:2070ms): RTBM-LMP-SL-201904180345.csv
SUCCESS (4580ms, AVG:2125ms): RTBM-LMP-SL-201904180350.csv
SUCCESS (5175ms, AVG:2190ms): RTBM-LMP-SL-201904180355.csv
SUCCESS (677ms, AVG:2158ms): RTBM-LMP-SL-201904180400.csv
SUCCESS (678ms, AVG:2128ms): RTBM-LMP-SL-201904180405.csv
SUCCESS (783ms, AVG:2101ms): RTBM-LMP-SL-201904180410.csv
SUCCESS (1227ms, AVG:2084ms): RTBM-LMP-SL-201904180415.csv
SUCCESS (705ms, AVG:2057ms): RTBM-LMP-SL-201904180420.csv
SUCCESS (660ms, AVG:2031ms): RTBM-LMP-SL-201904180425.csv
SUCCESS (1019ms, AVG:2012ms): RTBM-LMP-SL-201904180430.csv
SUCCESS (1203ms, AVG:1998ms): RTBM-LMP-SL-201904180435.csv
SUCCESS (707ms, AVG:1975ms): RTBM-LMP-SL-201904180440.csv
SUCCESS (795ms, AVG:1954ms): RTBM-LMP-SL-201904180445.csv
SUCCESS (701ms, AVG:1932ms): RTBM-LMP-SL-201904180450.csv
SUCCESS (827ms, AVG:1913ms): RTBM-LMP-SL-201904180455.csv
SUCCESS (764ms, AVG:1894ms): RTBM-LMP-SL-201904180500.csv
SUCCESS (819ms, AVG:1877ms): RTBM-LMP-SL-201904180505.csv
SUCCESS (1071ms, AVG:1864ms): RTBM-LMP-SL-201904180510.csv
SUCCESS (1029ms, AVG:1850ms): RTBM-LMP-SL-201904180515.csv
SUCCESS (825ms, AVG:1834ms): RTBM-LMP-SL-201904180520.csv
SUCCESS (842ms, AVG:1819ms): RTBM-LMP-SL-201904180525.csv
SUCCESS (774ms, AVG:1803ms): RTBM-LMP-SL-201904180530.csv
SUCCESS (1029ms, AVG:1792ms): RTBM-LMP-SL-201904180535.csv
SUCCESS (719ms, AVG:1776ms): RTBM-LMP-SL-201904180540.csv
SUCCESS (792ms, AVG:1762ms): RTBM-LMP-SL-201904180545.csv
SUCCESS (1248ms, AVG:1754ms): RTBM-LMP-SL-201904180550.csv
SUCCESS (981ms, AVG:1743ms): RTBM-LMP-SL-201904180555.csv
SUCCESS (825ms, AVG:1731ms): RTBM-LMP-SL-201904180600.csv
SUCCESS (1070ms, AVG:1722ms): RTBM-LMP-SL-201904180605.csv
SUCCESS (1455ms, AVG:1718ms): RTBM-LMP-SL-201904180610.csv
SUCCESS (812ms, AVG:1706ms): RTBM-LMP-SL-201904180615.csv
SUCCESS (1028ms, AVG:1697ms): RTBM-LMP-SL-201904180620.csv
SUCCESS (803ms, AVG:1685ms): RTBM-LMP-SL-201904180625.csv
SUCCESS (1038ms, AVG:1677ms): RTBM-LMP-SL-201904180630.csv
SUCCESS (1013ms, AVG:1669ms): RTBM-LMP-SL-201904180635.csv
SUCCESS (1838ms, AVG:1671ms): RTBM-LMP-SL-201904180640.csv
SUCCESS (2528ms, AVG:1681ms): RTBM-LMP-SL-201904180645.csv
SUCCESS (1837ms, AVG:1683ms): RTBM-LMP-SL-201904180650.csv
SUCCESS (1820ms, AVG:1685ms): RTBM-LMP-SL-201904180655.csv
SUCCESS (2170ms, AVG:1691ms): RTBM-LMP-SL-201904180700.csv
SUCCESS (1653ms, AVG:1690ms): RTBM-LMP-SL-201904180705.csv
SUCCESS (1237ms, AVG:1685ms): RTBM-LMP-SL-201904180710.csv
SUCCESS (1612ms, AVG:1684ms): RTBM-LMP-SL-201904180715.csv
SUCCESS (1063ms, AVG:1677ms): RTBM-LMP-SL-201904180720.csv
SUCCESS (1249ms, AVG:1672ms): RTBM-LMP-SL-201904180725.csv
SUCCESS (1055ms, AVG:1665ms): RTBM-LMP-SL-201904180730.csv
SUCCESS (836ms, AVG:1656ms): RTBM-LMP-SL-201904180735.csv
SUCCESS (823ms, AVG:1647ms): RTBM-LMP-SL-201904180740.csv
SUCCESS (1442ms, AVG:1645ms): RTBM-LMP-SL-201904180745.csv
SUCCESS (2328ms, AVG:1652ms): RTBM-LMP-SL-201904180750.csv
SUCCESS (3361ms, AVG:1670ms): RTBM-LMP-SL-201904180755.csv
SUCCESS (2211ms, AVG:1676ms): RTBM-LMP-SL-201904180800.csv
</details>

**Comment by davidsh** [comment]
>I just tried executing the same solution again today. Oddly enough, the .NET Core version is working now. 

As you mentioned, it seems to be working for you now. It could have been issues in your networking environment that was causing timeouts.

There isn't anything actionable for us based on this current report. So, we'll close this for now.
