### ISSUE TITLE
SecureStringTests.ThreadSafe_Stress recently started failing on most platforms

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#36870]
https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190414.9/workItem/System.Security.SecureString.Tests

started on 4/13

https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190414.9/workItem/System.Security.SecureString.Tests/analysis/xunit/System.Security.Tests.SecureStringTests~2FThreadSafe_Stress(executionTimeSeconds:%205)

```
System.AggregateException : One or more errors occurred. (The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallback'.
Parameter name: bytes) (The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallback'.
Parameter name: bytes)
---- System.ArgumentException : The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallback'.
Parameter name: bytes
---- System.ArgumentException : The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallback'.
Parameter name: bytes
Stack Trace :
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken) in /__w/1/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 4815
   at System.Security.Tests.SecureStringTests.ThreadSafe_Stress(Int32 executionTimeSeconds)
----- Inner Stack Trace #1 (System.ArgumentException) -----
   at System.Text.Encoding.ThrowBytesOverflow() in /__w/1/s/src/System.Private.CoreLib/shared/System/Text/Encoding.cs:line 1188
   at System.Text.Encoding.ThrowBytesOverflow(EncoderNLS encoder, Boolean nothingEncoded) in /__w/1/s/src/System.Private.CoreLib/shared/System/Text/Encoding.cs:line 1204
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder) in /__w/1/s/src/System.Private.CoreLib/shared/System/Text/Encoding.Internal.cs:line 588
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar) in /__w/1/s/src/System.Private.CoreLib/shared/System/Text/Encoding.Internal.cs:line 499
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount) in /__w/1/s/src/System.Private.CoreLib/shared/System/Text/UTF8Encoding.cs:line 363
   at System.Security.SecureString.MarshalToStringCore(Boolean globalAlloc, Boolean unicode) in /__w/1/s/src/System.Private.CoreLib/shared/System/Security/SecureString.Unix.cs:line 230
```

@GrabYourPitchforks

**Comment by blowdart** [comment]
🎉

**Comment by danmosemsft** [comment]
Ah but @blowdart it's a random, sporadic failure.. 😃

**Comment by blowdart** [comment]
So we should take off and nuke it from orbit, it's the only way to be sure. 

![alien-the-movie-scary-close-up-animated-gif-image-4](https://user-images.githubusercontent.com/796298/56166250-f65da000-5f89-11e9-94a6-29e40dadfc83.gif)

**Comment by GrabYourPitchforks** [comment]
Root cause: I had a typo in `Encoding.UTF8.GetBytes` which was inadvertently causing some unpaired surrogates to be seen as valid. The code read `x = (a ^ b) & c)` when it should've instead read `x = (a ^ c) & b`.

**Comment by danmosemsft** [comment]
Hooray for the SecureString tests then.

**Comment by GrabYourPitchforks** [comment]
This item auto-resolved when the coreclr change was committed. These failures should cease when the coreclr changes make their way over to corefx.

**Comment by GrabYourPitchforks** [comment]
Also, new tests are being added to corefx to exercise these code paths more rigorously. So huzzah all around! :)

**Comment by GrabYourPitchforks** [comment]
Fixed as of https://github.com/dotnet/corefx/pull/36922.
