### ISSUE TITLE
Failing ManagedWebSocket assert breaking HttpListener tests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#36963]
Due to https://github.com/dotnet/corefx/pull/36928.

```
Assertion Failed
Unexpected state Closed.



   at System.Net.WebSockets.ManagedWebSocket.CloseAsyncPrivate(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken) in D:\a\1\s\src\Common\src\System\Net\WebSockets\ManagedWebSocket.cs:line 1069

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 581

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 172

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 617

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 596

   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\TaskContinuation.cs:line 794

   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\Task.cs:line 3335

   at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\Future.cs:line 418

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 727

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult() in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 272

   at System.Net.WebSockets.ManagedWebSocket.SendCloseFrameAsync(WebSocketCloseStatus closeStatus, String closeStatusDescription, CancellationToken cancellationToken) in D:\a\1\s\src\Common\src\System\Net\WebSockets\ManagedWebSocket.cs:line 1174

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 581

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 172

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 617

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 596

   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\TaskContinuation.cs:line 794

   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\Task.cs:line 3335

   at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\Future.cs:line 418

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 727

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult() in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 272

   at System.Net.WebSockets.ManagedWebSocket.WaitForServerToCloseConnectionAsync(CancellationToken cancellationToken) in D:\a\1\s\src\Common\src\System\Net\WebSockets\ManagedWebSocket.cs:line 871

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 581

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 172

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 617

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 596

   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\TaskContinuation.cs:line 794

   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\Task.cs:line 3335

   at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\Future.cs:line 418

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 727

   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncValueTaskMethodBuilder.cs:line 161

   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) in D:\a\1\s\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\RawConnectionStream.cs:line 68

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 172

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 617

   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\TaskContinuation.cs:line 794

   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\Task.cs:line 3335

   at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\Future.cs:line 418

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 727

   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncValueTaskMethodBuilder.cs:line 161

   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination) in D:\a\1\s\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 1396

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 172

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 617

   at System.Threading.ThreadPoolGlobals.<>c.<.cctor>b__5_0(Object state) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\ThreadPool.cs:line 46

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow) in D:\a\1\s\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs:line 1048

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _) in D:\a\1\s\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs:line 869

   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags) in D:\a\1\s\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.cs:line 781

   at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__177_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in D:\a\1\s\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.Windows.cs:line 1254

   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in F:\workspace\_work\1\s\src\System.Private.CoreLib\src\System\Threading\ClrThreadPoolBoundHandleOverlapped.cs:line 51

   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped) in F:\workspace\_work\1\s\src\System.Private.CoreLib\src\System\Threading\Overlapped.cs:line 65
```

**Comment by davidsh** [comment]
Which exact tests are breaking?  I can disable them quickly and then work to fix it.

**Comment by stephentoub** [comment]
> Which exact tests are breaking? I can disable them quickly and then work to fix it.

I don't know.  The assert causes the process to fail fast and the CI log doesn't say which test it was.

**Comment by stephentoub** [comment]
I'm building locally to see...

**Comment by davidsh** [comment]
Assert is coming from here:
>
     at System.Net.WebSockets.ManagedWebSocket.CloseAsyncPrivate(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToke
  n) in S:\GitHub\corefx\src\Common\src\System\Net\WebSockets\ManagedWebSocket.cs:line 1069
