### ISSUE TITLE
Add-Migration fail:System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

### ISSUE THREAD

**Issue by tierarzt24** [dotnet/corefx#36969]
If we want to run the add-Migration Task in the Package Manager console.  Unfortunatelly we got the error below. We use .net core 2.2. SDK.  I do not understand why the system looks for Version 4.0.3.0. 
Anyone know why this error occurs?

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.TryAddCoreServices()
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>b__2(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at PimStar.Data.PimStarDbContext..ctor() in C:\Users\d.roeming\Documents\Visual Studio 2017\vsts\PimStar\Libraries\PimStar.Data\PimStarDbContext.cs:line 22
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Exception has been thrown by the target of an invocation.
```

**Comment by karelz** [comment]
@tierarzt24 what is `Add-Migration`? Is that PowerShell?
If that's correct, then please create C# repro first, or work with PowerShell team on that.

**Comment by karelz** [comment]
cc @joperezr

**Comment by joperezr** [comment]
I don't think it is PowerShell, I believe he is refering to the package manager console in VS. If that's the case, some repro steps would help in this case, as we need to use some tools like fuslog in order to be able to analyze what is going on. In any case, this wouldn't be an issue with corefx, this would be more an issue with either NuGet or VS, but if we get repro steps, we can investigate first and then we'll be able to reroute appropriately.

**Comment by tierarzt24** [comment]
I' have found the problem. There was serveral versions of .net core installed. I removed all versions which I don't use and now it works.
