### ISSUE TITLE
Add retry pattern for tests that rely on TCP/UDP

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#3697]
> As a design change, we should extract a common config for Sockets tests and consolidate all configuration parameters there. We should include a retry pattern/internal API for tests that rely on TCP stack defaults (in case we see those fail).

See https://github.com/dotnet/corefx/issues/3504 for more details.

**Comment by CIPop** [comment]
I've already added the timeout configuration in 77fb5b23.

Keeping this for the retry pattern that would increase CI test reliability.

**Comment by stephentoub** [comment]
https://github.com/dotnet/buildtools/issues/654 tracks adding retry functionality

**Comment by CIPop** [comment]
> dotnet/buildtools#654 tracks adding retry functionality

That tracks adding the retry functionality to XUnit. This is tracking work that needs to be done for all tests that use TCP.

**Comment by CIPop** [comment]
@davidsh @stephentoub 

The following failures just occurred on my my box. Just wanted to point out that _everything_ that uses TCP/UDP must have proper retries in place, not only Sockets:

@davidsh My IE settings have the "Auto" flag disabled.

```
     System.Net.WebSockets.Client.Tests.ClientWebSocketTest.SendReceive_PartialMessage_Success(server: ws://corefx-net.cloudapp.
  net/WebSocket/EchoWebSocket.ashx) [FAIL]
        System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
        ---- System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
        -------- System.Net.Http.WinHttpException : The operation has been canceled
        Stack Trace:
           S:\c1\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WebSocketHandle.Win32.cs(63,0): at System.Net.WebSoc
  kets.WebSocketHandle.<ConnectAsyncCore>d__21.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\ClientWebSocket.cs(169,0): at System.Net.WebSockets.
  ClientWebSocket.<ConnectAsyncCore>d__17.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\tests\WebSocketHelper.cs(79,0): at System.Net.WebSockets.Client.Tests.WebSocke
  tHelper.<GetConnectedWebSocket>d__4.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\tests\ClientWebSocketTest.cs(174,0): at System.Net.WebSockets.Client.Tests.Cli
  entWebSocketTest.<SendReceive_PartialMessage_Success>d__16.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           ----- Inner Stack Trace -----
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WinHttpWebSocket.cs(167,0): at System.Net.WebSockets
  .WinHttpWebSocket.<ConnectAsync>d__18.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WebSocketHandle.Win32.cs(54,0): at System.Net.WebSoc
  kets.WebSocketHandle.<ConnectAsyncCore>d__21.MoveNext()
           ----- Inner Stack Trace -----

     System.Net.WebSockets.Client.Tests.ClientWebSocketTest.ConnectAsync_AddCustomHeaders_Success(server: ws://corefx-net.clouda
  pp.net/WebSocket/EchoWebSocketHeaders.ashx) [FAIL]
        System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
        ---- System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
        -------- System.Net.Http.WinHttpException : The operation has been canceled
        Stack Trace:
           S:\c1\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WebSocketHandle.Win32.cs(63,0): at System.Net.WebSoc
  kets.WebSocketHandle.<ConnectAsyncCore>d__21.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\ClientWebSocket.cs(169,0): at System.Net.WebSockets.
  ClientWebSocket.<ConnectAsyncCore>d__17.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\tests\ClientWebSocketTest.cs(99,0): at System.Net.WebSockets.Client.Tests.Clie
  ntWebSocketTest.<ConnectAsync_AddCustomHeaders_Success>d__13.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           ----- Inner Stack Trace -----
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WinHttpWebSocket.cs(167,0): at System.Net.WebSockets
  .WinHttpWebSocket.<ConnectAsync>d__18.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WebSocketHandle.Win32.cs(54,0): at System.Net.WebSoc
  kets.WebSocketHandle.<ConnectAsyncCore>d__21.MoveNext()
           ----- Inner Stack Trace -----

     System.Net.WebSockets.Client.Tests.ClientWebSocketTest.EchoBinaryMessage_Success(server: ws://corefx-net.cloudapp.net/WebSo
  cket/EchoWebSocket.ashx) [FAIL]
        System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
        ---- System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
        -------- System.Net.Http.WinHttpException : The operation has been canceled
        Stack Trace:
           S:\c1\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WebSocketHandle.Win32.cs(63,0): at System.Net.WebSoc
  kets.WebSocketHandle.<ConnectAsyncCore>d__21.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\ClientWebSocket.cs(169,0): at System.Net.WebSockets.
  ClientWebSocket.<ConnectAsyncCore>d__17.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\tests\WebSocketHelper.cs(79,0): at System.Net.WebSockets.Client.Tests.WebSocke
  tHelper.<GetConnectedWebSocket>d__4.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\tests\WebSocketHelper.cs(30,0): at System.Net.WebSockets.Client.Tests.WebSocke
  tHelper.<TestEcho>d__3.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\tests\ClientWebSocketTest.cs(75,0): at System.Net.WebSockets.Client.Tests.Clie
  ntWebSocketTest.<EchoBinaryMessage_Success>d__11.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           ----- Inner Stack Trace -----
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WinHttpWebSocket.cs(167,0): at System.Net.WebSockets
  .WinHttpWebSocket.<ConnectAsync>d__18.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WebSocketHandle.Win32.cs(54,0): at System.Net.WebSoc
  kets.WebSocketHandle.<ConnectAsyncCore>d__21.MoveNext()
           ----- Inner Stack Trace -----

     System.Net.WebSockets.Client.Tests.ClientWebSocketTest.CloseAsync_CloseDescriptionIsMaxLengthPlusOne_ThrowsArgumentExceptio
  n(server: ws://corefx-net.cloudapp.net/WebSocket/EchoWebSocket.ashx) [FAIL]
        System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
        ---- System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
        -------- System.Net.Http.WinHttpException : The operation has been canceled
        Stack Trace:
           S:\c1\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WebSocketHandle.Win32.cs(63,0): at System.Net.WebSoc
  kets.WebSocketHandle.<ConnectAsyncCore>d__21.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\ClientWebSocket.cs(169,0): at System.Net.WebSockets.
  ClientWebSocket.<ConnectAsyncCore>d__17.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\tests\WebSocketHelper.cs(79,0): at System.Net.WebSockets.Client.Tests.WebSocke
  tHelper.<GetConnectedWebSocket>d__4.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\tests\ClientWebSocketTest.cs(460,0): at System.Net.WebSockets.Client.Tests.Cli
  entWebSocketTest.<CloseAsync_CloseDescriptionIsMaxLengthPlusOne_ThrowsArgumentException>d__24.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           ----- Inner Stack Trace -----
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WinHttpWebSocket.cs(167,0): at System.Net.WebSockets
  .WinHttpWebSocket.<ConnectAsync>d__18.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
           S:\c1\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WebSocketHandle.Win32.cs(54,0): at System.Net.WebSoc
  kets.WebSocketHandle.<ConnectAsyncCore>d__21.MoveNext()
           ----- Inner Stack Trace -----

  Finished:    System.Net.WebSockets.Client.Tests
```

**Comment by karelz** [comment]
We are now focusing on improving Networking tests reliability. This is just one of the potential solutions, it doesn't make sense to track it separately.
