### ISSUE TITLE
HTTP2: accessing www.wired.com throws HPackDecodingException

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#37154]
```
ReadFrameAsync got Settings with 6 length
ReadFrameAsync got WindowUpdate with 4 length
ReadFrameAsync got Settings with 0 length
state = ExpectingHeaders
ReadFrameAsync got Headers with 845 length
System.Net.Http.HPack.HPackDecodingException: Exception of type 'System.Net.Http.HPack.HPackDecodingException' was thrown.
   at System.Net.Http.HPack.HPackDecoder.CompleteDecode() in /mnt/github/wfurt-corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HPack/HPackDecoder.cs:line 326
   at System.Net.Http.Http2Connection.ProcessHeadersFrame(FrameHeader frameHeader) in /mnt/github/wfurt-corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 330
   at System.Net.Http.Http2Connection.ProcessIncomingFrames() in /mnt/github/wfurt-corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 218
state = Aborted
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders() in /mnt/github/wfurt-corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs:line 309
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync() in /mnt/github/wfurt-corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs:line 335
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /mnt/github/wfurt-corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 1356
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /mnt/github/wfurt-corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 1366
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /mnt/github/wfurt-corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 525
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /mnt/github/wfurt-corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 33
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in /mnt/github/wfurt-corefx/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 475
```

**Comment by JamesNK** [comment]
I've updated to the latest nightly .NET Core SDK and I think I'm seeing this in a gRPC call.

```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync()
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
```

**Comment by JamesNK** [comment]
Confirmed that this is the issue. Removing the trailer when it is an empty string fixes it.

Not blocking for gRPC. The header is optional and not sending it is slightly more efficient.
