### ISSUE TITLE
HTTP2: access to twitter.com does not work

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#37166]
Simple GET fails with 
```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders() in /mnt/github/wfurt-corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs:line 306
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync() in /mnt/github/wfurt-corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs:line 332
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /mnt/github/wfurt-corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 1353

```

The underlying reason is that we fail to decode particular header.
 Content-Security-Policy comes in as 3311  long (and passes OnStringLength check) but after Huffman decoding it expands to 4658 bytes. (and our buffer is 4096)

I did quick verification and with ` _headerValueOctets = new byte[MaxStringOctets * 2];` request succeeds.  It seems like we need better strategy for large headers.

 

```
StatusCode: 200, ReasonPhrase: 'OK', Version: 2.0, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-store, must-revalidate, no-cache, pre-check=0, post-check=0
  Content-Security-Policy: script-src https://ssl.google-analytics.com https://twitter.com 'unsafe-eval' https://*.twimg.com https://api.twitter.com https://analytics.twitter.com https://publish.twitter.com https://ton.twitter.com https://syndication.twitter.com https://www.google.com https://platform.twitter.com https://www.google-analytics.com 'nonce-ea4YasmQArkRamAVwVg/jQ==' blob: 'self'; frame-ancestors 'self'; font-src https://twitter.com https://*.twimg.com data: https://ton.twitter.com 'self'; media-src https://rmpdhdsnappytv-vh.akamaihd.net https://prod-video-eu-central-1.pscp.tv https://prod-video-ap-south-1.pscp.tv https://v.cdn.vine.co https://dwo3ckksxlb0v.cloudfront.net https://twitter.com https://prod-video-us-east-2.pscp.tv https://prod-video-cn-north-1.pscp.tv https://amp.twimg.com https://smmdhdsnappytv-vh.akamaihd.net https://*.twimg.com https://prod-video-eu-west-1.pscp.tv https://*.video.pscp.tv https://rmmdhdsnappytv-vh.akamaihd.net https://clips-media-assets.twitch.tv https://prod-video-ap-northeast-2.pscp.tv https://prod-video-us-west-2.pscp.tv https://prod-video-us-west-1.pscp.tv https://prod-video-ap-northeast-1.pscp.tv https://smdhdsnappytv-vh.akamaihd.net https://ton.twitter.com https://prod-video-eu-west-3.pscp.tv https://rmdhdsnappytv-vh.akamaihd.net https://mmdhdsnappytv-vh.akamaihd.net https://prod-video-ca-central-1.pscp.tv https://smpdhdsnappytv-vh.akamaihd.net https://prod-video-sa-east-1.pscp.tv https://mdhdsnappytv-vh.akamaihd.net https://prod-video-ap-southeast-2.pscp.tv https://mtc.cdn.vine.co https://prod-video-cn-northwest-1.pscp.tv https://prod-video-eu-west-2.pscp.tv https://canary-video-us-east-1.pscp.tv https://dev-video-us-west-2.pscp.tv https://prod-video-us-east-1.pscp.tv blob: 'self' https://prod-video-ap-northeast-3.pscp.tv https://prod-video-ap-southeast-1.pscp.tv https://mpdhdsnappytv-vh.akamaihd.net https://dev-video-eu-west-1.pscp.tv; connect-src https://rmpdhdsnappytv-vh.akamaihd.net https://prod-video-eu-central-1.pscp.tv https://prod-video-ap-south-1.pscp.tv https://*.giphy.com https://dwo3ckksxlb0v.cloudfront.net https://prod-video-us-east-2.pscp.tv https://prod-video-cn-north-1.pscp.tv https://vmaprel.snappytv.com https://smmdhdsnappytv-vh.akamaihd.net https://*.twimg.com https://embed.pscp.tv https://api.twitter.com https://prod-video-eu-west-1.pscp.tv https://*.video.pscp.tv https://rmmdhdsnappytv-vh.akamaihd.net https://clips-media-assets.twitch.tv https://prod-video-ap-northeast-2.pscp.tv https://prod-video-us-west-2.pscp.tv https://pay.twitter.com https://prod-video-us-west-1.pscp.tv https://analytics.twitter.com https://vmap.snappytv.com https://*.twprobe.net https://prod-video-ap-northeast-1.pscp.tv https://smdhdsnappytv-vh.akamaihd.net https://prod-video-eu-west-3.pscp.tv https://syndication.twitter.com https://sentry.io https://rmdhdsnappytv-vh.akamaihd.net https://media.riffsy.com https://mmdhdsnappytv-vh.akamaihd.net https://prod-video-ca-central-1.pscp.tv https://embed.periscope.tv https://smpdhdsnappytv-vh.akamaihd.net https://prod-video-sa-east-1.pscp.tv https://vmapstage.snappytv.com https://upload.twitter.com https://proxsee.pscp.tv https://mdhdsnappytv-vh.akamaihd.net https://prod-video-ap-southeast-2.pscp.tv https://prod-video-cn-northwest-1.pscp.tv https://prod-video-eu-west-2.pscp.tv https://canary-video-us-east-1.pscp.tv https://dev-video-us-west-2.pscp.tv https://prod-video-us-east-1.pscp.tv blob: 'self' https://prod-video-ap-northeast-3.pscp.tv https://vmap.grabyo.com https://prod-video-ap-southeast-1.pscp.tv https://mpdhdsnappytv-vh.akamaihd.net https://dev-video-eu-west-1.pscp.tv; style-src https://fonts.googleapis.com https://twitter.com https://*.twimg.com https://translate.googleapis.com https://ton.twitter.com 'unsafe-inline' https://platform.twitter.com 'self'; object-src https://twitter.com https://pbs.twimg.com; default-src 'self' blob:; frame-src https://twitter.com https://*.twimg.com https://player.vimeo.com https://pay.twitter.com https://ton.twitter.com https://syndication.twitter.com https://vine.co twitter: https://www.youtube.com https://platform.twitter.com https://upload.twitter.com 'self'; img-src https://*.giphy.com https://*.pscp.tv https://twitter.com https://*.twimg.com data: https://clips-media-assets.twitch.tv https://lumiere-a.akamaihd.net https://ton.twitter.com https://syndication.twitter.com https://media.riffsy.com https://www.google.com https://platform.twitter.com https://api.mapbox.com https://www.google-analytics.com blob: https://*.periscope.tv 'self'; report-uri https://twitter.com/i/csp_report?a=NVQWGYLXFVZXO2LGOQ%3D%3D%3D%3D%3D%3D&ro=false;
  Date: Thu, 25 Apr 2019 03:03:13 GMT
  Pragma: no-cache
  Server: tsa_a
  Set-Cookie: fm=0; Max-Age=0; Expires=Thu, 25 Apr 2019 03:03:13 GMT; Path=/; Domain=.twitter.com; Secure; HTTPOnly
  Set-Cookie: _twitter_sess=BAh7CSIKZmxhc2hJQzonQWN0aW9uQ29udHJvbGxlcjo6Rmxhc2g6OkZsYXNo%250ASGFzaHsABjoKQHVzZWR7ADoPY3JlYXRlZF9hdGwrCBN0clJqAToMY3NyZl9p%250AZCIlOWM3N2Y2ZDBlOGI1OWJiNzQ1ZjYyMGE4NzQ3YTRmNTc6B2lkIiUzYjg3%250ANTFmZDQyMjhkNmQ3ZTQzYTk3ZTYwNzMzZDAyZg%253D%253D--c45dda81c2a080f9c03fe033924f3bd2b30d2417; Path=/; Domain=.twitter.com; Secure; HTTPOnly
  Set-Cookie: personalization_id="v1_njJYtIzKaeJopjeTbMjYxA=="; Max-Age=63072000; Expires=Sat, 24 Apr 2021 03:03:13 GMT; Path=/; Domain=.twitter.com
  Set-Cookie: guest_id=v1%3A155616139368175743; Max-Age=63072000; Expires=Sat, 24 Apr 2021 03:03:13 GMT; Path=/; Domain=.twitter.com
  Set-Cookie: ct0=22b46a79fd73cfc7c20aa6228d7753f0; Max-Age=21600; Expires=Thu, 25 Apr 2019 09:03:13 GMT; Path=/; Domain=.twitter.com; Secure
  status: 200 OK
  Strict-Transport-Security: max-age=631138519
  x-connection-hash: 612b0f995b228953b13bd07f33a3d55e
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  x-response-time: 33
  x-transaction: 00658cfa00dcc322
  x-twitter-response-tags: BouncerCompliant
  X-UA-Compatible: IE=edge,chrome=1
  x-xss-protection: 1; mode=block; report=https://twitter.com/i/xss_report
  Content-Encoding: gzip
  Content-Length: 45480
  Content-Type: text/html; charset=utf-8
  Expires: Tue, 31 Mar 1981 05:00:00 GMT
  Last-Modified: Thu, 25 Apr 2019 03:03:13 GMT
}
```

**Comment by davidsh** [comment]
>but after Huffman decoding it expands to 4658 bytes. (and our buffer is 4096)

Why is our buffer size 4096?  Can we just make it bigger?

**Comment by wfurt** [comment]
But how much bigger? Doubling the size fixed twitter. 
We have other places where we allocate bigger array if we need to. Maybe this can be done as part of #36906.

**Comment by davidsh** [comment]
>But how much bigger?

Clearly a fixed buffer of 4096 is the wrong choice. Why does this have to be a fixed size buffer in the first place?  I don't understand enough about HTTP/2 header deserialization to comment further. I don't know about #36906 either. But we need at least fix this for the common cases. And 4096 doesn't seem like the right choice for now.

**Comment by wfurt** [comment]
Correct link was  #35528 HTTP2: Implement MaxResponseHeadersLength setting.

It also seems like this is dup of  #35490 HTTP2: HPackDecoder has hard-coded max string size.
But it was pushed to future so it got off radar.

**Comment by stephentoub** [comment]
I'll take this one.
