### ISSUE TITLE
Cleanup some exceptions in Json parsing

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/corefx#37188]
Found a couple cases where weird exceptions are thrown:
```csharp
JsonSerializer.Parse("{}", typeof(string));
```
Throws
```
System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
```

-----

```csharp
JsonSerializer.Parse("\"headers\"", typeof(Dictionary<string, string>));
```
Throws
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Text.Json.Serialization.JsonSerializer.ApplyValueToEnumerable[TProperty](TProperty& value, JsonSerializerOptions options, ReadStackFrame& frame)
```

**Comment by ahsonkhan** [comment]
cc @steveharter

**Comment by watfordgnf** [comment]
As of 189766719a059512a515d488efc5c65c7abf0650:
```csharp
JsonSerializer.Parse("{}", typeof(string));
```
Produces:
```
System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: [System.String] | LineNumber: 0 | BytePositionInLine: 1.
```
Which could use some messaging love (re: Path).

And:
```csharp
JsonSerializer.Parse("\"headers\"", typeof(Dictionary<string, string>));
```
Produces a Debug.Assert:
```
at System.Text.Json.Serialization.JsonSerializer.ApplyValueToEnumerable[TProperty](TProperty& value, ReadStack& state, Utf8JsonReader& reader) in C:\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.HandleArray.cs:line 243
   at System.Text.Json.Serialization.JsonPropertyInfoNotNullable`3.ReadEnumerable(JsonTokenType tokenType, JsonSerializerOptions options, ReadStack& state, Utf8JsonReader& reader) in C:\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonPropertyInfoNotNullable.cs:line 61
   at System.Text.Json.Serialization.JsonPropertyInfoNotNullable`3.Read(JsonTokenType tokenType, JsonSerializerOptions options, ReadStack& state, Utf8JsonReader& reader) in C:\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonPropertyInfoNotNullable.cs:line 25
   at System.Text.Json.Serialization.JsonSerializer.HandleValue(JsonTokenType tokenType, JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state) in C:\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.HandleValue.cs:line 28
   at System.Text.Json.Serialization.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state) in C:\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.cs:line 32
   at System.Text.Json.Serialization.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader) in C:\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.Helpers.cs:line 22
   at System.Text.Json.Serialization.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options) in C:\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.String.cs:line 74
   at System.Text.Json.Serialization.JsonSerializer.Parse(String json, Type returnType, JsonSerializerOptions options) in C:\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.String.cs:line 60
```

**Comment by watfordgnf** [comment]
Adding a new test:
```csharp
        [Theory]
        [InlineData(typeof(int[]), @"""test""")]
        [InlineData(typeof(int[]), @"1")]
        [InlineData(typeof(int[]), @"false")]
        [InlineData(typeof(int[]), @"{}")]
        [InlineData(typeof(int[]), @"[""test""")]
        [InlineData(typeof(int[]), @"[true]")]
        [InlineData(typeof(int[]), @"[{}]")]
        [InlineData(typeof(int[]), @"[[]]")]
        [InlineData(typeof(Dictionary<string, int[]>), @"{""test"": {}}")]
        [InlineData(typeof(Dictionary<string, int[]>), @"{""test"": ""test""}")]
        [InlineData(typeof(Dictionary<string, int[]>), @"{""test"": 1}")]
        [InlineData(typeof(Dictionary<string, int[]>), @"{""test"": true}")]
        [InlineData(typeof(Dictionary<string, int[]>), @"{""test"": [""test""]}")]
        [InlineData(typeof(Dictionary<string, int[]>), @"{""test"": [[]]}")]
        [InlineData(typeof(Dictionary<string, int[]>), @"{""test"": [{}]}")]
        public static void InvalidJsonForArrayShouldFail(Type type, string json)
        {
            Assert.Throws<JsonException>(() => JsonSerializer.Parse(json, type));
        }
```
Finds the following failure cases:
```
    System.Text.Json.Serialization.Tests.ArrayTests.InvalidJsonForArrayShouldFail(type: typeof(int[]), json: "{}") [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Text.Json.JsonException)
      Actual:   typeof(System.NullReferenceException): Object reference not set to an instance of an object.
```

```
InvalidJsonForArrayShouldFail(type: typeof(int[]), json: "[{}]") [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Text.Json.JsonException)
      Actual:   (No exception was thrown)
```

```
InvalidJsonForArrayShouldFail(type: typeof(System.Collections.Generic.Dictionary<string, int[]>), json: "{\"test\": {}}") [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Text.Json.JsonException)
      Actual:   typeof(System.NullReferenceException): Object reference not set to an instance of an object.
```

```
InvalidJsonForArrayShouldFail(type: typeof(System.Collections.Generic.Dictionary<string, int[]>), json: "{\"test\": [[]]}") [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Text.Json.JsonException)
      Actual:   (No exception was thrown)
```

```
InvalidJsonForArrayShouldFail(type: typeof(System.Collections.Generic.Dictionary<string, int[]>), json: "{\"test\": [{}]}") [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Text.Json.JsonException)
      Actual:   (No exception was thrown)
```
