### ISSUE TITLE
ArgumentNullException from System.Data.SqlClient

### ISSUE THREAD

**Issue by kevingosse** [dotnet/corefx#37214]
I'm running into this exception with .net core 3.0 preview 4 and System.Data.SqlClient 4.7.0-preview4.19212.13

```
System.ArgumentNullException: Value cannot be null.
Parameter name: array
   at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Return(T[] array, Boolean clearArray)
   at System.Data.SqlClient.SqlEnvChange.Clear()
   at System.Data.SqlClient.SqlEnvChangePool.Release(SqlEnvChange item, String caller)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Criteo.DevKit.DataAccess.Sql.DbContext.SetIsolationLevel() in C:\mb\0\sdk\sdk-csharp\Criteo.DevKit\Criteo.DevKit\DataAccess\Sql\DbContext.cs:line 430
```

Environment: CentOS 7

I'm very surprised because `SqlEnvChange` does check for null. Also, I can't reproduce it consistently, so it seems to be a race condition of some sort. I don't think I'll be able to build a repro. I'd like to try and capture a memory dump when the first-chance exception is thrown, but I don't know how to do that on Linux.

If the `SqlEnvChange` object is expected to be manipulated by multiple threads, it could be worth adding Interlocked operations when clearing the `newBinValue` and `oldBinValue` fields.

**Comment by kevingosse** [comment]
Ok I'm very likely running into this: https://github.com/dotnet/corefx/pull/36735 
It looks like the fix hasn't been published to nuget yet. I'm going to try building the change locally and I'll close the issue if it works.

**Comment by kevingosse** [comment]
I confirm that the issue is gone when building from master.
