### ISSUE TITLE
Test failed: System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows

### ISSUE THREAD

**Issue by VincentBu** [dotnet/corefx#37239]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs0x1000_tst/177/

**Failed tests:**
System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows

**Log:**
```
System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs0x1000/_/fx/src/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.cs(288,0): at System.IO.Pipelines.Pipe.CommitUnsynchronized()
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs0x1000/_/fx/src/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.cs(337,0): at System.IO.Pipelines.Pipe.FlushAsync(CancellationToken cancellationToken)
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs0x1000/_/fx/src/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.cs(952,0): at System.IO.Pipelines.Pipe.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs0x1000/_/fx/src/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.DefaultPipeWriter.cs(47,0): at System.IO.Pipelines.Pipe.DefaultPipeWriter.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs0x1000/_/fx/src/System.IO.Pipelines/tests/PipeWriterTests.cs(253,0): at System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows()
```

**Comment by ViktorHofer** [comment]
Happened again on `netcoreapp-Windows_NT-Debug-x64-Windows.7.Amd64.Open`:

```
System.NullReferenceException : Object reference not set to an instance of an object.

   at System.IO.Pipelines.Pipe.CommitUnsynchronized() in D:\a\1\s\src\System.IO.Pipelines\src\System\IO\Pipelines\Pipe.cs:line 288
   at System.IO.Pipelines.Pipe.FlushAsync(CancellationToken cancellationToken) in D:\a\1\s\src\System.IO.Pipelines\src\System\IO\Pipelines\Pipe.cs:line 337
   at System.IO.Pipelines.Pipe.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken) in D:\a\1\s\src\System.IO.Pipelines\src\System\IO\Pipelines\Pipe.cs:line 952
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken) in D:\a\1\s\src\System.IO.Pipelines\src\System\IO\Pipelines\Pipe.DefaultPipeWriter.cs:line 47
   at System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows() in D:\a\1\s\src\System.IO.Pipelines\tests\PipeWriterTests.cs:line 253
--- End of stack trace from previous location where exception was thrown ---
```
