### ISSUE TITLE
HttpContent.SerializeToStreamAsync should throw ObjectDisposedException instead of NullReferenceException

### ISSUE THREAD

**Issue by Kuinox** [dotnet/corefx#37276]
Hello.  
If you dispose the stream provided by the method SerializeToStreamAsync, the httpClient throw a NullReferenceException when you send the request.  
I think it should be an ObjectDisposedException to point out the error to the dev.

**Comment by davidsh** [comment]
HttpContent.SerializeToStreamAysync is an abstract method.  It is implemented by several different derived classes of HttpContent.

https://github.com/dotnet/corefx/blob/a26fd9bb1b17510d51a9b5a2ce7aadc1a5b631ee/src/System.Net.Http/src/System/Net/Http/HttpContent.cs#L316

Can you post a repro for this?

**Comment by Kuinox** [comment]
```
   at System.Net.Http.HttpConnection.ChunkedEncodingWriteStream.FinishAsync()
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```
And there the reproduction: 
https://gist.github.com/Kuinox/96ba564e6c4c0aae7e716b26813b8738

**Comment by stephentoub** [comment]
It looks like there are several issues here.  I'll take a look.
