### ISSUE TITLE
Writes to /home/helixbot failing on Ubuntu1904

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#37321]
https://mc.dot.net/#/product/netcore/master/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190430.5/workItem/System.Security.Cryptography.X509Certificates.Tests

```
MicrosoftDotComRootBytes
Expected: True
Actual:   False
Stack Trace :
   at System.Security.Cryptography.X509Certificates.Tests.CertTests.TestVerify() in /__w/1/s/src/System.Security.Cryptography.X509Certificates/tests/CertTests.cs:line 142
```
possibly due to
```
System.Security.Cryptography.CryptographicException : The X509 certificate could not be added to the store.
---- System.UnauthorizedAccessException : Access to the path '/home/helixbot/.dotnet/corefx/cryptography/x509stores/teststorebbcee9ce66674e8caecfa1aefd9e801f' is denied.
-------- System.IO.IOException : Permission denied
Stack Trace :
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal) in /__w/1/s/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/DirectoryBasedStoreProvider.cs:line 129
   at System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.<>c.<X509Store_Add4_Remove1>b__20_0(X509Store store, String storeDirectory) in /__w/1/s/src/System.Security.Cryptography.X509Certificates/tests/X509FilesystemTests.Unix.cs:line 502
   at System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.RunX509StoreTest(Action`2 testAction) in /__w/1/s/src/System.Security.Cryptography.X509Certificates/tests/X509FilesystemTests.Unix.cs:line 654
----- Inner Stack Trace -----
   at System.IO.FileSystem.CreateDirectory(String fullPath) in /__w/1/s/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs:line 235
   at System.IO.Directory.CreateDirectory(String path) in /__w/1/s/src/System.IO.FileSystem/src/System/IO/Directory.cs:line 49
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.AddCertToStore(ICertificatePal certPal) in /__w/1/s/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/DirectoryBasedStoreProvider.cs:line 138
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal) in /__w/1/s/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/DirectoryBasedStoreProvider.cs:line 121
----- Inner Stack Trace -----
```

@bartonjs

**Comment by bartonjs** [comment]
@MattGal Did 19.04 get set up with a different permissions model (or perhaps isn't redirecting $HOME to a different location)?

**Comment by danmosemsft** [comment]
Similarly: https://github.com/dotnet/corefx/issues/37322

**Comment by danmosemsft** [comment]
Yeah it's clearly not @bartonjs's code at fault -- 

```
System.UnauthorizedAccessException : Access to the path '/home/helixbot/.local/share' is denied.
---- System.IO.IOException : Permission denied
Stack Trace :
   at System.IO.FileSystem.CreateDirectory(String fullPath) in /__w/1/s/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs:line 235
   at System.IO.Directory.CreateDirectory(String path) in /__w/1/s/src/System.IO.FileSystem/src/System/IO/Directory.cs:line 49
   at System.Environment.GetFolderPathCore(SpecialFolder folder, SpecialFolderOption option) in /__w/2/s/src/System.Private.CoreLib/shared/System/Environment.Unix.cs:line 88
   at System.Environment.GetFolderPath(SpecialFolder folder, SpecialFolderOption option) in /__w/2/s/src/System.Private.CoreLib/shared/System/Environment.cs:line 107
   at System.IO.IsolatedStorage.Helper.GetDataDirectory(IsolatedStorageScope scope) in /__w/1/s/src/System.IO.IsolatedStorage/src/System/IO/IsolatedStorage/Helper.Win32Unix.cs:line 25
   at System.IO.IsolatedStorage.Helper.GetRootDirectory(IsolatedStorageScope scope) in /__w/1/s/src/System.IO.IsolatedStorage/src/System/IO/IsolatedStorage/Helper.cs:line 48
   at System.IO.IsolatedStorage.IsolatedStorageFile.Initialize(IsolatedStorageScope scope) in /__w/1/s/src/System.IO.IsolatedStorage/src/System/IO/IsolatedStorage/IsolatedStorageFile.cs:line 645
   at System.IO.IsolatedStorage.FileExistsTests.FileExists_Closed_ThrowsInvalidOperationException() in /__w/1/s/src/System.IO.IsolatedStorage/tests/System/IO/IsolatedStorage/FileExistsTests.cs:line 45
----- Inner Stack Trace -----
```

**Comment by MattGal** [comment]
@bartonjs I copied what our other Dockerfiles did but I agree that's what this looks like.  I'm guessing either a difference in how the public dockerhub Ubuntu 19 base image behaves or one of the base images I took from in the mcr repository already did that. 

I'll look a bit more; if you figure it out either of us can make a PR to https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/src/ubuntu/19.04/helix/amd64/Dockerfile to get a new image.

**Comment by MattGal** [comment]
Ah.  UserAdd doesn't work the same on this linux as Fedora.  This should fix it: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/130

**Comment by MattGal** [comment]
This is fixed in mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-19.04-helix-amd64-b43bf34-20190503204407, I'll go make a PR.

**Comment by MattGal** [comment]
Will be fixed via https://github.com/dotnet/corefx/pull/37474 , I verified the helixbot user was created and has access in `mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-19.04-helix-amd64-b43bf34-20190503204407`

**Comment by MattGal** [comment]
PR merged, will keep this on myself until the next official corefx run to check it out.

**Comment by wfurt** [comment]
should be fixed now.

**Comment by MattGal** [comment]
Yup, example log: https://mc.dot.net/#/product/netcore/master/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190509.2/workItem/System.Security.Cryptography.X509Certificates.Tests/wilogs
