### ISSUE TITLE
Environment SpecialFolder tests failing on Ubuntu 1904

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#37322]
https://mc.dot.net/#/product/netcore/master/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190430.5/workItem/System.Runtime.Extensions.Tests/analysis/xunit/System.Tests.EnvironmentTests~2FGetFolderPath_Unix_NonEmptyFolderPaths(folder:%20MyDocuments,%20option:%20None)

it appears we can't find the Documents, etc folders on this distro.

eg GetFolderPath_Unix_NonEmptyFolderPaths(folder: UserProfile, option: None)
```
Assert.NotEmpty() Failure
Stack Trace :
   at System.Tests.EnvironmentTests.GetFolderPath_Unix_NonEmptyFolderPaths(SpecialFolder folder, SpecialFolderOption option) in /__w/1/s/src/System.Runtime.Extensions/tests/System/EnvironmentTests.cs:line 362
```

**Comment by danmosemsft** [comment]
also some like

GetFolderPath_Unix_SpecialFolderDoesNotExist_CreatesSuccessfully(folder: MyPictures)
```
System.UnauthorizedAccessException : Access to the path '/home/helixbot/Pictures' is denied.
---- System.IO.IOException : Permission denied
Stack Trace :
   at System.IO.FileSystem.CreateDirectory(String fullPath) in /__w/1/s/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs:line 235
   at System.IO.Directory.CreateDirectory(String path) in /__w/1/s/src/System.IO.FileSystem/src/System/IO/Directory.cs:line 49
   at System.Environment.GetFolderPathCore(SpecialFolder folder, SpecialFolderOption option) in /__w/2/s/src/System.Private.CoreLib/shared/System/Environment.Unix.cs:line 88
   at System.Environment.GetFolderPath(SpecialFolder folder, SpecialFolderOption option) in /__w/2/s/src/System.Private.CoreLib/shared/System/Environment.cs:line 107
   at System.Tests.EnvironmentTests.GetFolderPath_Unix_SpecialFolderDoesNotExist_CreatesSuccessfully(SpecialFolder folder) in /__w/1/s/src/System.Runtime.Extensions/tests/System/EnvironmentTests.cs:line 319
----- Inner Stack Trace -----
```

**Comment by danmosemsft** [comment]
dupe of https://github.com/dotnet/corefx/issues/37321
