### ISSUE TITLE
Test failure with "Provider could not perform the action since the context was acquired as silent"

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#37336]
I've been seeing this error not-infrequently in local System.Net.Http test runs.
"Error -2146893790 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'Provider could not perform the action since the context was acquired as silent.'"
```
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ClientCertificates_Test.AutomaticOrManual_DoesntFailRegardlessOfWhetherClientCertsAreAvailable(mode: Automatic) [FAIL]
        System.AggregateException : One or more errors occurred. (One or more errors occurred. (An error occurred while sending the request.)) (One or more errors occurred. (Authentication failed because the remote party has closed the transport stream.))
        ---- System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)
        -------- System.Net.Http.HttpRequestException : An error occurred while sending the request.
        ------------ System.Net.Http.WinHttpException : Error -2146893790 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'Provider could not perform the action since the context was acquired as silent.'.
        ---- System.AggregateException : One or more errors occurred. (Authentication failed because the remote party has closed the transport stream.)
        -------- System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
        Stack Trace:
          D:\repos\corefx\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(111,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
          D:\repos\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ClientCertificates.cs(286,0): at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<>c__DisplayClass14_0.<<AutomaticOrManual_DoesntFailRegardlessOfWhetherClientCertsAreAvailable>b__1>d.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
          D:\repos\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs(66,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
          D:\repos\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ClientCertificates.cs(277,0): at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.AutomaticOrManual_DoesntFailRegardlessOfWhetherClientCertsAreAvailable(ClientCertificateOption mode)
          --- End of stack trace from previous location where exception was thrown ---
          ----- Inner Stack Trace #1 (System.AggregateException) -----

          ----- Inner Stack Trace -----
          D:\repos\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(507,0): at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
          D:\repos\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(135,0): at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
          D:\repos\corefx\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(83,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
          ----- Inner Stack Trace -----
          F:\workspace\_work\1\s\src\System.Private.CoreLib\src\System\Environment.CoreCLR.cs(97,0): at System.Environment.get_StackTrace()
          D:\repos\corefx\src\Common\src\System\Runtime\ExceptionServices\ExceptionStackTrace.cs(23,0): at System.Runtime.ExceptionServices.ExceptionStackTrace.AddCurrentStack(Exception exception)
          D:\repos\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpException.cs(57,0): at System.Net.Http.WinHttpException.CreateExceptionUsingError(Int32 error, String nameOfCalledFunction)
          D:\repos\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs(333,0): at System.Net.Http.WinHttpRequestCallback.OnRequestError(WinHttpRequestState state, WINHTTP_ASYNC_RESULT asyncResult)
          D:\repos\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs(104,0): at System.Net.Http.WinHttpRequestCallback.RequestCallback(IntPtr handle, WinHttpRequestState state, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
          D:\repos\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestCallback.cs(47,0): at System.Net.Http.WinHttpRequestCallback.WinHttpCallback(IntPtr handle, IntPtr context, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
          --- End of stack trace from AddCurrentStack ---
          D:\repos\corefx\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs(62,0): at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
          D:\repos\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(878,0): at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state)
          ----- Inner Stack Trace #2 (System.AggregateException) -----

          ----- Inner Stack Trace -----
          D:\repos\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs(611,0): at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
          D:\repos\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs(831,0): at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
          --- End of stack trace from previous location where exception was thrown ---
          D:\repos\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs(82,0): at System.Net.Security.SslStream.ThrowIfExceptional()
          D:\repos\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs(472,0): at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
          D:\repos\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs(442,0): at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
          D:\repos\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.cs(284,0): at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
          D:\repos\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.cs(430,0): at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__68_2(IAsyncResult iar)
          F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\FutureFactory.cs(514,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
          --- End of stack trace from previous location where exception was thrown ---
          D:\repos\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs(100,0): at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync)
```

**Comment by davidsh** [comment]
![image](https://user-images.githubusercontent.com/7684835/57039018-5bfb8e80-6c10-11e9-9d2c-2884bd19f502.png)

I've never seen this error before.

**Comment by davidsh** [comment]
This is a test bug.  The problem is that the test is trying to use a client certificate via 'Automatic' selection.  That can have random effects on machine. It's probably picking a certificate on your machine in the PerUser/MY store that requires user consent, i.e. a smart-card PIN or something.

We probably should disable this test and try to fix it later.

**Comment by stephentoub** [comment]
Thanks, David.  I'll disable it.
