### ISSUE TITLE
TestPartialLargeJsonReader failure in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#37351]
```
System.Text.Json.Tests.Utf8JsonReaderTests.TestPartialLargeJsonReader(compactData: True, type: BroadTree, jsonString: \"[\\n {\\n \\\"_id\\\": \\\"5af4c006873ec87e12466553\\\",\"...)

Error message
System.Text.Json.JsonReaderException : 'i' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 0 | BytePositionInLine: 1820.

Stack trace
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes) in /__w/1/s/src/System.Text.Json/src/System/Text/Json/ThrowHelper.cs:line 222
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker) in /__w/1/s/src/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs:line 1644
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker) in /__w/1/s/src/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs:line 1519
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment() in /__w/1/s/src/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs:line 703
   at System.Text.Json.Utf8JsonReader.Read() in /__w/1/s/src/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs:line 251
   at System.Text.Json.Tests.JsonTestHelper.ReaderLoop(Int32 inpuDataLength, Int32& length, Utf8JsonReader& json) in /__w/1/s/src/System.Text.Json/tests/JsonTestHelper.cs:line 266
   at System.Text.Json.Tests.Utf8JsonReaderTests.TestPartialLargeJsonReader(Boolean compactData, TestCaseType type, String jsonString) in /__w/1/s/src/System.Text.Json/tests/Utf8JsonReaderTests.cs:line 272
```
cc: @ahsonkhan

**Comment by ahsonkhan** [comment]
Do you know which PR/CI leg this failed in? Presumably its an intermittent issue since not much has changed here so additional info will help me repro it.

**Comment by ahsonkhan** [comment]
I have not seen this test fail in CI recently. I will try to repro locally, and if not, will close.

**Comment by JeremyKuhne** [comment]
Can't get this to repro, closing.
