### ISSUE TITLE
JsonEncodedTextTests.InvalidLargeEncode failing with OOM in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#37353]
```
System.Text.Json.Tests.JsonEncodedTextTests.InvalidLargeEncode

Error message
System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.

Stack trace
   at System.String.Ctor(Char[] value) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\String.cs:line 50
   at System.Text.Json.Tests.JsonEncodedTextTests.InvalidLargeEncode() in D:\a\1\s\src\System.Text.Json\tests\JsonEncodedTextTests.cs:line 288
```
cc: @ahsonkhan

**Comment by ahsonkhan** [comment]
> failing with OOM in CI

I am assuming this was an **on-demand outerloop** CI run, correct?

**Comment by stephentoub** [comment]
Yes, why?

**Comment by ViktorHofer** [comment]
on x86 AFAIK
