### ISSUE TITLE
GetHostName is unreliable on OSX

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#37362]
Failing here: https://dev.azure.com/dnceng/public/_build/results?buildId=176435&view=ms.vss-test-web.build-test-results-tab

Seems like this call in the Unix PAL sometimes returns an error: https://github.com/dotnet/corefx/blob/master/src/System.Net.NameResolution/src/System/Net/NameResolutionPal.Unix.cs#L133

Failing tests which I will disable:

1. `System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteGetHostByName_EmptyString_ReturnsHostName`

```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : nodename nor servname provided, or not known

   at System.Net.Dns.InternalGetHostByName(String hostName) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 68
   at System.Net.Dns.GetHostByName(String hostName) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 41
   at System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteGetHostByName_EmptyString_ReturnsHostName() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/tests/FunctionalTests/GetHostByNameTest.cs:line 108
```

2. `System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntry_HostString_Ok(hostName: \"\")`

```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : nodename nor servname provided, or not known

 at System.Net.Dns.InternalGetHostByName(String hostName) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 68
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 413
   at System.Net.NameResolution.Tests.GetHostEntryTest.<>c__DisplayClass1_0.<Dns_GetHostEntry_HostString_Ok>b__0() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs:line 26
   at System.Net.NameResolution.Tests.GetHostEntryTest.TestGetHostEntryAsync(Func`1 getHostEntryFunc) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
```

3. `System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntryAsync_HostString_Ok(hostName: \"\")`

```
System.AggregateException : One or more errors occurred. (One or more errors occurred. (nodename nor servname provided, or not known)) (One or more errors occurred. (nodename nor servname provided, or not known))\n---- System.AggregateException : One or more errors occurred. (nodename nor servname provided, or not known)\n-------- System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : nodename nor servname provided, or not known\n---- System.AggregateException : One or more errors occurred. (nodename nor servname provided, or not known)\n-------- System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : nodename nor servname provided, or not known

 at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /Users/vsts/agent/2.150.3/work/1/s/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /Users/vsts/agent/2.150.3/work/1/s/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 71
   at System.Net.NameResolution.Tests.GetHostEntryTest.TestGetHostEntryAsync(Func`1 getHostEntryFunc) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace #1 (System.AggregateException) -----

----- Inner Stack Trace -----
   at System.Net.Dns.InternalGetHostByName(String hostName) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 68
   at System.Net.Dns.ResolveCallback(Object context) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 218
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 358
   at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 500
   at System.Net.Dns.<>c.<GetHostEntryAsync>b__27_1(IAsyncResult asyncResult) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 590
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) in /Users/vsts/agent/2.150.2/work/1/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/FutureFactory.cs:line 510
----- Inner Stack Trace #2 (System.AggregateException) -----

----- Inner Stack Trace -----
   at System.Net.Dns.InternalGetHostByName(String hostName) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 68
   at System.Net.Dns.ResolveCallback(Object context) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 218
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 358
   at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 500
   at System.Net.Dns.<>c.<GetHostEntryAsync>b__27_1(IAsyncResult asyncResult) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 590
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) in /Users/vsts/agent/2.150.2/work/1/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/FutureFactory.cs:line 510
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /Users/vsts/agent/2.150.3/work/1/s/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
```

4. `System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName`

```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : nodename nor servname provided, or not known

   at System.Net.Dns.InternalGetHostByName(String hostName) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 68
   at System.Net.Dns.ResolveCallback(Object context) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 218
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 358
   at System.Net.Dns.EndGetHostByName(IAsyncResult asyncResult) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 383
   at System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.NameResolution/tests/FunctionalTests/GetHostByNameTest.cs:line 117
```

cc @davish @wfurt @stephentoub

**Comment by wfurt** [comment]
This is generally infrastructure issue.

**Comment by ViktorHofer** [comment]
you mean the osx machines aren't configured correctly?

**Comment by wfurt** [comment]
not necessarily. There may be network outages or timing. Part of the problem is that this (and some other networking tests) depend on external services. I've seen cases when ping or nslookup on OS it self fails to resolve. With that, there is not much we can do at the test level.

**Comment by ViktorHofer** [comment]
And exactly for such cases @stephentoub added the RetryHelper feature: https://github.com/dotnet/corefx/blob/master/src/CoreFx.Private.TestUtilities/src/System/RetryHelper.cs. Still its usage should be as spare as possible, otherwise we will get back to the state where we don't capture actual product issues like races.

**Comment by stephentoub** [comment]
> And exactly for such cases

I'm not sure about that.  @wfurt, isn't this the case where when there's a failure it's a failure for a really long time, maybe even until the machine is restarted or something like that?

**Comment by wfurt** [comment]
I'm not sure but I can do some digging. I wanted to run caching name server locally on each machine but I was not able to convince infrastructure to do it.

**Comment by ahsonkhan** [comment]
Failing from https://github.com/dotnet/corefx/pull/38469:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38469~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190624.21/workItem/System.Net.NameResolution.Functional.Tests/analysis/xunit/System.Net.NameResolution.Tests.GetHostByNameTest~2FDnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName

RedHat.6.Amd64.Open-x64-Release
System.Net.NameResolution.Tests.GetHostByNameTest/DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName

```text
Unhandled Exception of Type System.Net.Internals.SocketExceptionFactory+ExtendedSocketException
Message :
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Name or service not known
Stack Trace :
   at System.Net.Dns.InternalGetHostByName(String hostName) in /_/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 68
   at System.Net.Dns.ResolveCallback(Object context) in /_/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 218
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 69
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) in /_/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 361
   at System.Net.Dns.EndGetHostByName(IAsyncResult asyncResult) in /_/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 383
   at System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName() in /_/src/System.Net.NameResolution/tests/FunctionalTests/GetHostByNameTest.cs:line 119
```

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/24355
