### ISSUE TITLE
System.Tests.GCTests.GetGCMemoryInfo test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#37378]
https://dev.azure.com/dnceng/public/_build/results?buildId=176754&view=ms.vss-test-web.build-test-results-tab&runId=4250734&resultId=463789&paneView=debug
netcoreapp-Linux-Release-x64-Ubuntu.1804.Amd64.Open
```
Error message
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.

Stack trace

Child exception:
  Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at System.Tests.GCTests.<>c.<GetGCMemoryInfo>b__29_0() in /__w/1/s/src/System.Runtime/tests/System/GCTests.netcoreapp.cs:line 56

Child process:
  System.Runtime.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.GCTests+<>c Void <GetGCMemoryInfo>b__29_0()
```
cc: @luhenry

**Comment by stephentoub** [comment]
Failed again here:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F36984~2Fmerge/test~2Ffunctional~2Fcli~2F/20190508.48/workItem/System.Runtime.Tests/analysis/xunit/System.Tests.GCTests~2FGetGCMemoryInfo
this time with the additional logging I added:
```
Child exception:
  Xunit.Sdk.InRangeException: Assert.InRange() Failure
Range:  (8174027653 - 9223372036854775807)
Actual: 7339943198
   at System.Tests.GCTests.<>c.<GetGCMemoryInfo>b__29_0() in /__w/1/s/src/System.Runtime/tests/System/GCTests.netcoreapp.cs:line 56

Child process:
  System.Runtime.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.GCTests+<>c Void <GetGCMemoryInfo>b__29_0()
```

**Comment by safern** [comment]
Failed again in OSX.10.12

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F37811~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190520.34/workItem/System.Runtime.Tests/analysis/xunit/System.Tests.GCTests~2FGetGCMemoryInfo

```
Timed out after 60000ms waiting for remote process 53348
Expected: True
Actual:   False
```

```
at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutor/RemoteInvokeHandle.cs:line 54
   at System.Tests.GCTests.GetGCMemoryInfo() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Runtime/tests/System/GCTests.netcoreapp.cs:line 32
```

**Comment by stephentoub** [comment]
Failed again here:
https://dev.azure.com/dnceng/public/_build/results?buildId=203470&view=ms.vss-test-web.build-test-results-tab&runId=4923924&resultId=476692&paneView=debug
netcoreapp-Linux-Release-x64-Ubuntu.1604.Amd64.Open
```
Child exception:
  Xunit.Sdk.InRangeException: Assert.InRange() Failure
Range:  (8174027653 - 9223372036854775807)
Actual: 8090619207
   at System.Tests.GCTests.<>c.<GetGCMemoryInfo>b__29_0() in /_/src/System.Runtime/tests/System/GCTests.netcoreapp.cs:line 56

Child process:
  System.Runtime.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.GCTests+<>c Void <GetGCMemoryInfo>b__29_0()
```

**Comment by jkotas** [comment]
cc @VSadov

**Comment by VSadov** [comment]
`Timed out after 60000ms waiting for remote process`   -  I think I have seen this before. I think it is related to some infrastructure to run a scenario as a separate process. In that other case the test did not even need to run as a separate process.

Will take a look.

**Comment by stephentoub** [comment]
> I think it is related to some infrastructure to run a scenario as a separate process.

I've opened https://github.com/dotnet/arcade/pull/2919 which should help make those issues easier to track down.

**Comment by danmosemsft** [comment]
@VSadov do you expect to be able to take a look before 7/1? We expect to ZBB on that day.

**Comment by VSadov** [comment]
Thanks, for a heads up. I thought it is tracked as a part of some bigger known infrastructure issue. 
I will take a look.

**Comment by joperezr** [comment]
@stephentoub do you want to keep this as 3.0? If this is just a test/infra bug, I believe it should be fine to move it to Future right? If there is a product bug then can @VSadov take a look at this today? ZBB is tomorrow at noon.

**Comment by stephentoub** [comment]
I don't know if it's a test or a product bug.  It's a new feature added in 3.0.  I suggest it stay 3.0 until it's demonstrated to be a test issue, at which point it should also be easy to fix the test.

**Comment by danmosemsft** [comment]
@VSadov have you had a chance to take a look at this one?

**Comment by VSadov** [comment]
I was OOF. Will take a look today.

**Comment by VSadov** [comment]
I am having troubles with reproducing this failure. 
- tried to repro locally
- created a PR with this test enabled (https://github.com/dotnet/corefx/pull/39131)
- modified the test in the PR to re-run the scenario 1000 times 

I see no failures.
I do not recall any changes in the area of collecting or reporting GC stats, but at this point we do not even know which one was off the expected range. 
(I am looking at the `InRange` failures, `Timed out after 60000ms` is definitely infra)

At this point I will try enabling the test (in master) with additional checks, so that when it fails we would at least know which scenario.

**Comment by stephentoub** [comment]
It was sporadic.  IIRC it was failing something like once a day or every other day in CI.

**Comment by VSadov** [comment]
The test takes GC stats, does some allocating/pinning/collecting and then takes the same stats, assuming that they should increase or stay the same.

At first glance the assumption seems correct, but there is a possibility that it is wrong for some metric in some rare case. It is hard to speculate, as we do not know which metric went down. - heap size, fragmentation, ...

The API basically just exposes internal numbers. It basically just checks that API does not crash and numbers returned are not completely random.

I think we should enable the test and get more hits.

**Comment by stephentoub** [comment]
@VSadov, it failed again here:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39176~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190703.51/workItem/System.Runtime.Tests/wilogs
```
/datadisks/disk1/work/a6179d41-f9a2-4ed1-9af4-35b53b47d545/Work/6ef54223-b1dc-41b7-ab2a-aad8d1234896/Exec /datadisks/disk1/work/a6179d41-f9a2-4ed1-9af4-35b53b47d545/Work/6ef54223-b1dc-41b7-ab2a-aad8d1234896/Exec
  Discovering: System.Runtime.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Tests (found 5358 of 5398 test cases)
  Starting:    System.Runtime.Tests (parallel test collections = on, max threads = 2)
    System.Tests.ArgIteratorTests.ArgIterator_GetNextArgType [SKIP]
      Condition(s) not met: "IsArgIteratorSupported"
    System.Tests.ArgIteratorTests.ArgIterator_GetRemainingCount_GetNextArg [SKIP]
      Condition(s) not met: "IsArgIteratorSupported"
FAILED: MemoryLoadBytes
Unhandled exception. Xunit.Sdk.InRangeException: Assert.InRange() Failure
Range:  (8174027653 - 9223372036854775807)
Actual: 7840393871
   at Xunit.Assert.InRange[T](T actual, T low, T high, IComparer`1 comparer) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\RangeAsserts.cs:line 42
   at Xunit.Assert.InRange[T](T actual, T low, T high) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\RangeAsserts.cs:line 25
   at System.Tests.GCTests.<>c.<GetGCMemoryInfo>b__29_0() in /_/src/System.Runtime/tests/System/GCTests.netcoreapp.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.RemoteExecutorHost.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutorHost/Program.cs:line 92
    System.Tests.GCTests.GetGCMemoryInfo [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.InRangeException: Assert.InRange() Failure
        Range:  (8174027653 - 9223372036854775807)
        Actual: 7840393871
        /_/src/System.Runtime/tests/System/GCTests.netcoreapp.cs(67,0): at System.Tests.GCTests.<>c.<GetGCMemoryInfo>b__29_0()
        
        Child process:
          System.Runtime.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.GCTests+<>c Void <GetGCMemoryInfo>b__29_0()
        
        
  Finished:    System.Runtime.Tests
```

**Comment by VSadov** [comment]
nice, now we know it is in `MemoryLoadBytes`

**Comment by VSadov** [comment]
I will disable just that scenario for now

**Comment by AriNuer** [comment]
Test `System.Tests.GCTests/GetGCMemoryInfo ` failed with same exception:

Message :
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
```
Stack Trace :
```

Child exception:
  Xunit.Sdk.InRangeException: Assert.InRange() Failure
Range:  (1 - 9223372036854775807)
Actual: -1844674407689672704
   at System.Tests.GCTests.<>c.<GetGCMemoryInfo>b__29_0() in /_/src/System.Runtime/tests/System/GCTests.netcoreapp.cs:line 35

Child process:
  System.Runtime.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.GCTests+<>c Void <GetGCMemoryInfo>b__29_0()
```
Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F~2F/20190722.29/workItem/System.Runtime.Tests/analysis/xunit/System.Tests.GCTests~2FGetGCMemoryInfo

**Comment by stephentoub** [comment]
cc: @VSadov

**Comment by danmosemsft** [comment]
dupe of https://github.com/dotnet/coreclr/issues/25810

ARM specific

**Comment by karelz** [comment]
Duplicate of https://github.com/dotnet/coreclr/issues/25810

**Comment by ViktorHofer** [comment]
Reopening to track the disabled test.
