### ISSUE TITLE
RsaCngTests.SignVerifyDataRoundTrip failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#37415]
https://dev.azure.com/dnceng/public/_build/results?buildId=178176&view=ms.vss-test-web.build-test-results-tab&runId=4289936&resultId=427177&paneView=debug
```
Error message
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc0000001)

Stack trace
   at Internal.Cryptography.CngCommon.SignHash(SafeNCryptKeyHandle keyHandle, ReadOnlySpan`1 hash, AsymmetricPaddingMode paddingMode, Void* pPaddingInfo, Int32 estimatedSize) in D:\a\1\s\src\Common\src\Internal\Cryptography\CngCommon.SignVerify.cs:line 30
   at System.Security.Cryptography.RSACng.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) in D:\a\1\s\src\Common\src\System\Security\Cryptography\RSACng.SignVerify.cs:line 86
   at System.Security.Cryptography.RSA.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) in D:\a\1\s\src\System.Security.Cryptography.Algorithms\src\System\Security\Cryptography\RSA.cs:line 174
   at System.Security.Cryptography.RSA.SignData(Byte[] data, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) in D:\a\1\s\src\System.Security.Cryptography.Algorithms\src\System\Security\Cryptography\RSA.cs:line 152
   at System.Security.Cryptography.Cng.Tests.RsaCngTests.TestSignVerifyDataRoundTrip(Byte[] message, HashAlgorithmName hashAlgorithm, RSASignaturePadding paddingMode, Int32 expectedSignatureLength) in D:\a\1\s\src\System.Security.Cryptography.Cng\tests\RsaCngTests.cs:line 55
   at System.Security.Cryptography.Cng.Tests.RsaCngTests.SignVerifyDataRoundTrip() in D:\a\1\s\src\System.Security.Cryptography.Cng\tests\RsaCngTests.cs:line 48
```
cc: @bartonjs

**Comment by bartonjs** [comment]
Assuming I've traced flows correctly: STATUS_UNSUCCESSFUL indicates something unexpected happened within SymCrypt.  The only obvious case is if memory allocation fails (possibly within LSASS.exe).  It's hard to act upon without a time travel trace or a working repro.

There's a possibility that the recent fix to make keys actually dispose during System.Security.Cryptography.Algorithms tests will reduce this, since it would mean the LSA spends less time tracking keys that are unreachable in-proc but not yet finalized.

**Comment by stephentoub** [comment]
Since we think a recent fix could have impacted this, closing until we see it again.
