### ISSUE TITLE
System.Net.Http.Functional.Tests crashed with Debug.Fail

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#37455]
Failed in CI on `Windows.7.Amd64.Open-x64:Debug`: https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F37454~2Fmerge/test~2Ffunctional~2Fcli~2F/20190505.14/workItem/System.Net.Http.Functional.Tests/wilogs

```
Assertion Failed
_httpStreams.Remove failed

   at System.Net.Http.Http2Connection.RemoveStream(Http2Stream http2Stream) in D:\a\1\s\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 1430
   at System.Net.Http.Http2Connection.SendHeadersAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\1\s\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 997
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 1027
   at System.Net.Http.Http2Connection.SendHeadersAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\1\s\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 1356
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 1027
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in D:\a\1\s\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 525
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 172
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 618
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\TaskContinuation.cs:line 794
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\Task.cs:line 3335
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\Future.cs:line 418
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 728
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 718
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncValueTaskMethodBuilder.cs:line 162
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\1\s\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 500
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 172
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 618
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\TaskContinuation.cs:line 794
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\Task.cs:line 3335
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\Future.cs:line 418
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 728
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 718
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncValueTaskMethodBuilder.cs:line 162
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken) in D:\a\1\s\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 646
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 172
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 618
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\TaskContinuation.cs:line 794
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\Task.cs:line 3335
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\Future.cs:line 418
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 728
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in D:\a\1\s\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\ConnectHelper.cs:line 97
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 172
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 618
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\TaskContinuation.cs:line 794
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\Task.cs:line 3335
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\Future.cs:line 418
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 728
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult() in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 273
   at System.Net.Http.ConnectHelper.ConnectEventArgs.OnCompleted(SocketAsyncEventArgs _) in D:\a\1\s\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\ConnectHelper.cs:line 120
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state) in D:\a\1\s\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.cs:line 423
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 172
   at System.Net.Sockets.SocketAsyncEventArgs.FinishWrapperConnectSuccess(Socket connectSocket, Int32 bytesTransferred, SocketFlags flags) in D:\a\1\s\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.cs:line 672
   at System.Net.Sockets.MultipleConnectAsync.Succeed() in D:\a\1\s\src\System.Net.Sockets\src\System\Net\Sockets\MultipleConnectAsync.cs:line 289
   at System.Net.Sockets.MultipleConnectAsync.InternalConnectCallback(Object sender, SocketAsyncEventArgs args) in D:\a\1\s\src\System.Net.Sockets\src\System\Net\Sockets\MultipleConnectAsync.cs:line 219
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e) in D:\a\1\s\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.cs:line 203
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state) in D:\a\1\s\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.cs:line 423
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 172
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags) in D:\a\1\s\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.cs:line 785
   at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__177_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in D:\a\1\s\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.Windows.cs:line 1254
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped) in F:\workspace\_work\1\s\src\System.Private.CoreLib\src\System\Threading\Overlapped.cs:line 65
```

cc @davidsh @wfurt

**Comment by ViktorHofer** [comment]
Happened again: https://dev.azure.com/dnceng/public/_build/results?buildId=180529&view=logs

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F37459~2Fmerge/test~2Ffunctional~2Fcli~2F/20190506.3/workItem/System.Net.Http.Functional.Tests/wilogs

**Comment by wfurt** [comment]
I'l try to reproduce it. Related to  #35466

**Comment by wfurt** [comment]
with many tries I was able to reproduce it on OSX.
