### ISSUE TITLE
System.Collections.Concurrent.Tests crashing on OSX.1013.Amd64.Open-x64:Debug

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#37452]
```
Discovering: System.Collections.Concurrent.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Collections.Concurrent.Tests (found 861 of 868 test cases)
  Starting:    System.Collections.Concurrent.Tests (parallel test collections = on, max threads = 8)
Assertion Failed

   at System.Collections.Concurrent.ConcurrentBag`1.WorkStealingQueue.get_DangerousCount() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs:line 1056
   at System.Collections.Concurrent.ConcurrentBag`1.get_DangerousCount() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs:line 521
   at System.Collections.Concurrent.ConcurrentBag`1.ToArray() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs:line 390
   at System.Collections.Concurrent.Tests.ConcurrentBagTests.<>c__DisplayClass18_0.<Clear_ConcurrentUsage_NoExceptions>b__1() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Collections.Concurrent/tests/ConcurrentBagTests.netcoreapp.cs:line 85
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 289
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2403
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 664
./RunTests.sh: line 175: 69241 Abort trap: 6           (core dumped) "$RUNTIME_PATH/dotnet" xunit.console.dll System.Collections.Concurrent.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonosxtests -notrait category=IgnoreForCI -notrait category=failing -notrait category=OuterLoop $RSP_FILE
~/dotnetbuild/work/015db5c5-3b15-4b0a-a6af-ed2ed45932f1/Work/a0939b49-993b-4198-9400-4cbb737d782f/Exec
----- end 07:14:44 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
```

Failed here: https://dev.azure.com/dnceng/public/_build/results?buildId=180191&view=logs

Repro Tool link and execution log:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F37450~2Fmerge/test~2Ffunctional~2Fcli~2F/20190505.8/workItem/System.Collections.Concurrent.Tests/wilogs

@MattGal should be able to help access the ReproTool for the dump. As Santi is out, maybe someone else with access to CorpNet can help.

cc @stephentoub @danmosemsft

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/33500
