### ISSUE TITLE
ArgumentOutOfRangeException thrown when posting Newtonsoft.Json serialized object to System.Text.Json endpoint 

### ISSUE THREAD

**Issue by Eilon** [dotnet/corefx#37502]
_From @jmezach on Tuesday, 07 May 2019 20:53:01_

### Describe the bug
I'm seeing an ArgumentOutOfRangeException being thrown when I try to POST a JSON object serialized with Newtonsoft.Json on the client to an endpoint that is using System.Text.Json (or at least the exception stacktrace seems to suggest that is the case).

### To Reproduce
1. Create new gRPC project using `dotnet new grpc`
2. Add `.AddControllers()` to the `ConfigureServices` method
3. Add an Http1AndHttp2 endpoint in `CreateHostBuilder`
4. Add a class inheriting from `Controller` with the `ApiController` attribute and an `HttpPost` method and a `FromBody` argument
5. Create a client console app using `dotnet new console`
6. Serialize an object using `JsonConvert.SerializeObject()` and post it to the service using `HttpClient.PostAsync()`
7. See the following exception being thrown in the service:

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Text.Json.Serialization.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.Serialization.WriteStackFrame.Initialize(Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializer.WriteAsyncCore(Object value, Type type, Stream utf8Json, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Expected behavior
I would expect the action on my controller to be invoked with the object I serialzied on the client as the argument.

### Screenshots
N/A

### Additional context
`dotnet --info`:

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     debian
 OS Version:  
 OS Platform: Linux
 RID:         debian-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100-preview5-011568/

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  3.0.100-preview5-011568 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

_Copied from original issue: aspnet/AspNetCore#10052_

**Comment by Eilon** [comment]
_From @rynowak on Tuesday, 07 May 2019 22:24:44_

This seems like a bug in `System.Text.Json`. Would it be possible for you to share the class definition that's causing this?

**Comment by jmezach** [comment]
I'm actually using the same types that are being used by my gRPC client as I'm trying to compare between the two. I was expecting the type definition to be rather trivial, but it turns out it is a lot more complex than I thought.

That being said, I had a look at the JSON being serialized from it by Newtonsoft.Json and it looks like this:

```json
{"Name":"GreeterClient"}
```

That doesn't look all that weird to me, so I tried to dig a little deeper and I noticed that my ASP.NET Core API controller operation isn't actually being invoked, or at least my Console.WriteLine there isn't visible in the output. Here are the logs:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST https://localhost:5000/api/greeter text/plain; charset=utf-8 24
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'AspNetCoreGRPC.Service.Controllers.GreeterController.Post (AspNetCoreGRPC.Service)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Post", controller = "Greeter"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.ActionResult`1[Greet.HelloReply] Post(Greet.HelloRequest) on controller AspNetCoreGRPC.Service.Controllers.GreeterController (AspNetCoreGRPC.Service).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value of type 'Microsoft.AspNetCore.Mvc.ProblemDetails'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action AspNetCoreGRPC.Service.Controllers.GreeterController.Post (AspNetCoreGRPC.Service) in 30.0147ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'AspNetCoreGRPC.Service.Controllers.GreeterController.Post (AspNetCoreGRPC.Service)'
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Text.Json.Serialization.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.Serialization.WriteStackFrame.Initialize(Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializer.WriteAsyncCore(Object value, Type type, Stream utf8Json, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 171.49110000000002ms 500 text/plain
```

Looking at that seems to suggest that, for some reason, it's not able to invoke my controller operation and thus returning a ProblemDetails object. That then fails to serialize. Or maybe I'm jumping to conclusions here ;).

**Comment by ahsonkhan** [comment]
>ProblemDetails

At a quick glance, it doesn't look like there's anything in that POCO that would trip up the serializer:
https://github.com/aspnet/AspNetCore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.Core/src/ProblemDetails.cs#L12

@steveharter, any ideas? I know we recently updated the object case for Dictionary support, here, but I am not sure where we would get IndexOutOfRange on the underlying `_propertyRefs` list:
https://github.com/dotnet/corefx/blob/3070e0484558aaaaf3547ede2f285544d0a3ed00/src/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.AddProperty.cs#L31-L39

**Comment by JeremyKuhne** [comment]
#37686 addresses the `Dictionary<string,object>` scenario that this issue is hitting.
