### ISSUE TITLE
System.Data.SqlClient is not supported on this platform

### ISSUE THREAD

**Issue by LaterStart** [dotnet/corefx#37528]
Hi,

My persistance layer project has these dependencies:
```
Microsoft.EntityFrameworkCore (3.0.0-preview5.19227.1)
Microsoft.EntityFrameworkCore.SqlServer (3.0.0-preview5.19227.1)
Microsoft.NETCore.Platforms (3.0.0-preview5.19224.8)
```

And I have encountered an error while trying to invoke `SaveChangesAsync(cancellationToken) `method.

Here is the connection string:
`Server=mypcname\\SQLEXPRESS;Database=testdb;Trusted_Connection=True;MultipleActiveResultSets=true;`

Context constructor:
```
 public Context(string connectionString) : base(new DbContextOptionsBuilder()
            .UseSqlServer(connectionString)
            .Options) { }
```

Stack trace:
```
System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform.
   at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Vigab.Persistence.Handlers.Commands.RegisterUserHandler.Handle(RegisterUserCommand request, CancellationToken cancellationToken) in C:\Vigab\Vigab.Persistence\Handlers\Commands\RegisterUserHandler.cs:line 36
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at Vigab.Api.Controllers.UsersController.Create(RegisterUserCommand command) in C:\Vigab\Vigab.Api\Controllers\UsersController.cs:line 18
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by David-Engel** [comment]
What platform are you running on? You should include the output from `dotnet --info`.

**Comment by LaterStart** [comment]
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>dotnet --info

.NET Core SDK (reflecting any global.json):
  Version:   3.0.100-preview5-011568
  Commit:    b487ff10aa 

Runtime Environment:
  OS Name:     Windows
  OS Version:  10.0.17763
  OS Platform: Windows
  RID:         win10-x64
  Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\ 

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23 

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  3.0.100-preview5-011568 [C:\Program Files\dotnet\sdk] 

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by LaterStart** [comment]
Here is the updated information about the error reproduction.
Error is occurred when the persistence assembly (the one containing Context class) is loaded using LoadFrom method: ` var assembly = Assembly.LoadFrom(Const.PersistencePath);` from application layer project.

Executing application (presentation layer project) references application assembly and has dependency injection for context.

**Comment by LaterStart** [comment]
**Problem solved.** 
Manually loaded `System.Data.SqlClient.dll` from the persistance assembly.

Unnecessary thread, but at least I hope it may help someone else in the future.

**Comment by LaterStart** [comment]
**After further testing and investigation, this seems like known .NET core unmanned assembly issue.**

@https://github.com/dotnet/corefx/issues/24229

**Comment by AidanTfL** [comment]
Can anyone give an update on this, and any known workarounds in the meantime?

I have the same issue in a .NET Core Service Bus Queue Triggered Azure Function with Microsoft.Data.SqlClient Version 1.0.19221.1-Preview installed.
