### ISSUE TITLE
RedirectLocation_SetDisposed_ThrowsObjectDisposedException failed in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#37562]
```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Connection refused 127.0.0.1:1316

  at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 4445
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 833
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 948
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 959
   at System.Net.Sockets.Socket.Connect(String host, Int32 port) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 903
   at System.Net.Tests.HttpListenerFactory.GetConnectedSocket() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.HttpListener/tests/HttpListenerFactory.cs:line 155
   at System.Net.Tests.HttpListenerResponseTestBase..ctor() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.HttpListener/tests/HttpListenerResponseTests.cs:line 22
   at System.Net.Tests.HttpListenerResponseHeadersTests..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Private.CoreLib/src/System/RtType.cs:line 4574
```

@davish @wfurt this is failing in the setup of the test in the base class. Any idea what could the socket to fail to open? What is your recommendation here as disabling all tests or moving all to Outerloop doesn't seem right?

cc @stephentoub

**Comment by wfurt** [comment]
could be system limits. We would need to get some logs from the server side. As @davidsh mentioned before, loopback tests _should_ be stable if OS is in reasonable condition. 
Note that some of the loopback test still depend on external services if they try to resolve "localhost". 
(probably not this case)

**Comment by wfurt** [comment]
I'll try to reproduce this locally. Is there any hint what OS flavor is failing most likely?

**Comment by ViktorHofer** [comment]
This was failing here https://dev.azure.com/dnceng/public/_build/results?buildId=184676&view=ms.vss-test-web.build-test-results-tab&runId=4448168&resultId=483305&paneView=debug on `netcoreapp-OSX-Debug-x64-OSX.1012.Amd64.Open`.

**Comment by wfurt** [comment]
ok. I did 1000+ run on Ubuntu over the weekend and I did not see any failure. I can try it on OSX as well.

**Comment by wfurt** [comment]
I did another 1000+ runs on OSX with no single failure. 
This seems to be somehow related to CI environment. 
I don't know what we do to ensure consistent environment for test runs.
