### ISSUE TITLE
[System.Text.Json] Deserializing dictionary with non-primitive types does not work

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#37569]
```C#
class Program
{
    static void Main(string[] args)
    {
        var dictionary = new Dictionary<string, object>
        {
            ["key"] = new Poco { Id = 10 },
        };

        var instance = JsonSerializer.ToString(dictionary);
        Console.WriteLine(instance);
    }
}

class Poco
{
    public int Id { get; set; }
}
```

This throws:

```C#
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Cannot bind to the target method because its signature is not compatible with that of the delegate type.
   at System.Delegate.CreateDelegate(Type type, MethodInfo method, Boolean throwOnBindFailure)
   at System.Text.Json.Serialization.JsonPropertyInfoCommon`3..ctor(Type parentClassType, Type declaredPropertyType, Type runtimePropertyType, PropertyInfo propertyInfo, Type elementType, JsonSerializerOptions options)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Text.Json.Serialization.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
```

Using Microsoft.NETCore.App 3.0.0-preview6-27709-05

**Comment by pranavkm** [comment]
@steveharter it looks like this should have been covered by https://github.com/dotnet/corefx/issues/37077. Am I missing something?

**Comment by pranavkm** [comment]
In particular with Blazor, this is going to be a fairly common scenario to run in to. I worked around this in our tests, but it would be great if we fix this soon.

**Comment by steveharter** [comment]
I assume this was handled already. System.Object is special because it used the JsonElement. @JeremyKuhne

**Comment by pranavkm** [comment]
> System.Object is special because it used the JsonElement

@steveharter this is during serialization. Shouldn't that use the reflected type and serialize the way `object` types are serialized elsewhere?
