### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.PlatformHandlerTest_AutoRedirect/GetAsync_MaxAutomaticRedirectionsNServerHops_ThrowsIfTooMany(maxHops: 3, hops: 3)

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#37620]
The test `System.Net.Http.Functional.Tests.PlatformHandlerTest_AutoRedirect/GetAsync_MaxAutomaticRedirectionsNServerHops_ThrowsIfTooMany(maxHops: 3, hops: 3)` has failed.

Failure Message:
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.CurlException : Couldn't resolve host name
```

Stack Trace:
```
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in /__w/1/s/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 496
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_AutoRedirect.GetAsync_MaxAutomaticRedirectionsNServerHops_ThrowsIfTooMany(Int32 maxHops, Int32 hops) in /__w/1/s/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.AutoRedirect.cs:line 384
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error) in /__w/1/s/src/System.Net.Http/src/System/Net/Http/CurlHandler/CurlHandler.cs:line 660
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult) in /__w/1/s/src/System.Net.Http/src/System/Net/Http/CurlHandler/CurlHandler.MultiAgent.cs:line 887
```

Build : Master - 20190512.1 (Core Tests)
Failing configurations:
- Ubuntu.1804.Amd64-x64
  - Release

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190512.1/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.PlatformHandlerTest_AutoRedirect~2FGetAsync_MaxAutomaticRedirectionsNServerHops_ThrowsIfTooMany(maxHops:%203,%20hops:%203)

**Comment by wfurt** [comment]
Seems like environmental failure. `Couldn't resolve host name`
