### ISSUE TITLE
Corefx build fails in dnu restore on windows

### ISSUE THREAD

**Issue by noahfalk** [dotnet/corefx#3766]
I am attempting to follow the instructions at: https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md

While building the corefx portion of the code in a windows enlistment I see this failure output:
```
C:\Users\noahfalk\Documents\GitHub\corefx [master]> .\build.cmd /p:OSGroup=Linux /p:SkipTests=true
  Restoring all packages...
EXEC : warning : FindPackagesById: Microsoft.Win32.Registry [C:\Users\noahfalk\Documents\GitHub\corefx\build.proj]
C:\Users\noahfalk\Documents\GitHub\corefx\build.proj(24,5): error MSB3073: The command ""C:\Users\noahfalk\Documents\Gi
tHub\corefx\packages//dnx-coreclr-win-x86.1.0.0-beta7/\bin\dnu.cmd" restore --packages "C:\Users\noahfalk\Documents\Git
Hub\corefx\packages" --source https://www.myget.org/F/dotnet-core/ --source https://www.myget.org/F/dotnet-coreclr/ --s
ource https://www.myget.org/F/dotnet-corefxtestdata/ --source https://www.myget.org/F/dotnet-buildtools/ --source https
://www.nuget.org/api/v2/ "C:\Users\noahfalk\Documents\GitHub\corefx\src" "C:\Users\noahfalk\Documents\GitHub\corefx\pac
kages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00097/lib/"" exited with code 1.
```

Running a build with more diagnostics enabled reveals this:
```
C:\Users\noahfalk\Documents\GitHub\corefx [master +0 ~22 -0]> msbuild /v:detailed /p:OSGroup=Linux /p:SkipTests=true .\b
uild.proj
Microsoft (R) Build Engine version 12.0.40629.0
[Microsoft .NET Framework, version 4.0.30319.42000]
```
... Omitting some hopefully irrelevant build ouput for brevity ...
```
Task "Exec"
  "C:\Users\noahfalk\Documents\GitHub\corefx\packages//dnx-coreclr-win-x86.1.0.0-beta7/\bin\dnu.cmd" restore --packages
   "C:\Users\noahfalk\Documents\GitHub\corefx\packages" --source https://www.myget.org/F/dotnet-core/ --source https://
  www.myget.org/F/dotnet-coreclr/ --source https://www.myget.org/F/dotnet-corefxtestdata/ --source https://www.myget.or
  g/F/dotnet-buildtools/ --source https://www.nuget.org/api/v2/ "C:\Users\noahfalk\Documents\GitHub\corefx\src" "C:\Use
  rs\noahfalk\Documents\GitHub\corefx\packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00097/lib/"
  Microsoft .NET Development Utility CoreCLR-x86-1.0.0-beta7-15532

    CACHE https://www.myget.org/F/dotnet-core/
    CACHE https://www.myget.org/F/dotnet-coreclr/
    CACHE https://www.myget.org/F/dotnet-corefxtestdata/
    CACHE https://www.myget.org/F/dotnet-buildtools/
    CACHE https://www.nuget.org/api/v2/
  Restoring packages for C:\Users\noahfalk\Documents\GitHub\corefx\src\Common\tests\project.json
  Following lock file C:\Users\noahfalk\Documents\GitHub\corefx\src\Common\tests\project.lock.json
  Restore complete, 288ms elapsed
  Restoring packages for C:\Users\noahfalk\Documents\GitHub\corefx\src\Common\tests\System\Diagnostics\RemoteExecutorCo
  nsoleApp\project.json
  Following lock file C:\Users\noahfalk\Documents\GitHub\corefx\src\Common\tests\System\Diagnostics\RemoteExecutorConso
  leApp\project.lock.json
  Restore complete, 14ms elapsed
  Restoring packages for C:\Users\noahfalk\Documents\GitHub\corefx\src\Common\tests\SystemXml\BaseLibManaged\project.js
  on
  Following lock file C:\Users\noahfalk\Documents\GitHub\corefx\src\Common\tests\SystemXml\BaseLibManaged\project.lock.
  json
  Restore complete, 5ms elapsed
  Restoring packages for C:\Users\noahfalk\Documents\GitHub\corefx\src\Common\tests\SystemXml\ModuleCore\project.json
  Following lock file C:\Users\noahfalk\Documents\GitHub\corefx\src\Common\tests\SystemXml\ModuleCore\project.lock.json
  Restore complete, 32ms elapsed
  Restoring packages for C:\Users\noahfalk\Documents\GitHub\corefx\src\Common\tests\SystemXml\XmlCoreTest\project.json
  Following lock file C:\Users\noahfalk\Documents\GitHub\corefx\src\Common\tests\SystemXml\XmlCoreTest\project.lock.jso
  n
  Restore complete, 33ms elapsed
  Restoring packages for C:\Users\noahfalk\Documents\GitHub\corefx\src\Common\tests\SystemXml\XmlDiff\project.json
  Following lock file C:\Users\noahfalk\Documents\GitHub\corefx\src\Common\tests\SystemXml\XmlDiff\project.lock.json
  Restore complete, 31ms elapsed
  Restoring packages for C:\Users\noahfalk\Documents\GitHub\corefx\src\Microsoft.CSharp\ref\project.json
  Following lock file C:\Users\noahfalk\Documents\GitHub\corefx\src\Microsoft.CSharp\ref\project.lock.json
  Restore complete, 16ms elapsed
  Restoring packages for C:\Users\noahfalk\Documents\GitHub\corefx\src\Microsoft.CSharp\src\project.json
  Following lock file C:\Users\noahfalk\Documents\GitHub\corefx\src\Microsoft.CSharp\src\project.lock.json
  Restore complete, 31ms elapsed
  Restoring packages for C:\Users\noahfalk\Documents\GitHub\corefx\src\Microsoft.VisualBasic\ref\project.json
  Following lock file C:\Users\noahfalk\Documents\GitHub\corefx\src\Microsoft.VisualBasic\ref\project.lock.json
  Restore complete, 2ms elapsed
  Restoring packages for C:\Users\noahfalk\Documents\GitHub\corefx\src\Microsoft.VisualBasic\src\project.json
  Following lock file C:\Users\noahfalk\Documents\GitHub\corefx\src\Microsoft.VisualBasic\src\project.lock.json
  ----------
  System.IO.IOException: The supplied user buffer is not valid for the requested operation
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.IO.Win32FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
     at System.IO.Win32FileStream.Read(Byte[] array, Int32 offset, Int32 count)
     at System.IO.FileStream.Read(Byte[] buffer, Int32 offset, Int32 count)
     at System.Xml.XmlTextReaderImpl.ReadData()
     at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
     at System.Xml.XmlTextReaderImpl.Read()
     at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
     at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
     at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
     at NuGet.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
     at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
     at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
     at NuGet.UnzippedPackage.EnsureManifest()
     at NuGet.UnzippedPackage..ctor(IFileSystem fileSystem, String manifestPath)
     at NuGet.PackageInfo.get_Package()
     at Microsoft.Dnx.Runtime.NuGetDependencyResolver.<GetDependencies>d__14.MoveNext()
     at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.Dnx.Tooling.RestoreCommand.<CreateGraphNode>d__62.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
     at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__61.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass60_0.<<Execute>b__2>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
     at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__60.MoveNext()
  ----------
  Restore failed
  The supplied user buffer is not valid for the requested operation
```

**Comment by jasonwilliams200OK** [comment]
Not sure if the Linux docs are out of sync here, but AFAICT, with mono v4.0.3+, it build on both Linux and FreeBSD and "build managed code on Windows" bit is not required anymore. For example on Windows 10 with Hyper-V, I used [these steps](https://gist.github.com/jasonwilliams200OK/6efa7907e66275df2d24) to build CoreFX on FreeBSD.

Nit: You can always use https://gist.github.com/ to dump the full msbuild.log and share the link (as opposed to pasting the dump in the issue). E.g. here is the [msbuild.log](https://gist.githubusercontent.com/jasonwilliams200OK/b375ce52c7b0c90e24af/raw/ca9f28aef5ac9977116b069c7caa9d70712e011c/corefx-msbuild.log) produced by compiling current master 4554758fb.

/cc @ellismg, @akoeplinger

**Comment by akoeplinger** [comment]
@jasonwilliams200OK docs update PR is pending here: https://github.com/dotnet/coreclr/pull/1601, but the error in this issue seems to be from something else.

**Comment by jasonwilliams200OK** [comment]
Commented on https://github.com/dotnet/coreclr/pull/1601/files#r41701702.

I have just built `linuxmscorlib` on Windows 10 x64 with VS2015 Community edition installed using `.\build.cmd linuxmscorlib skiptestbuild` command.

**Comment by anurse** [comment]
Is there a fix needed here? I'm not sure why I was assigned this...

**Comment by noahfalk** [comment]
Unfortunately it appears my machine is no longer reproing the failure. It was stable for several days, but now the failure has changed to something else that appears unrelated.

The callstack above appears like a bug in dnu to me, but at this point that callstack is all the info that I have. If you would like to close this or reassign, I'll leave that to you. Thanks!

**Comment by anurse** [comment]
Sounds good. It looks like it might have been a corefx problem in System.IO or something that was fixed. I'll close and we can re-open if it reoccurs.

**Comment by cshung** [comment]
I can reliably repro the issue on my computer.

**Comment by ellismg** [comment]
@cshung Are you hitting the "System.IO.IOException: The supplied user buffer is not valid for the requested operation" error or something else?

**Comment by joshfree** [comment]
moving this to "RC2" as the issue was hiding in the "RC1" milestone

**Comment by chcosta** [comment]
@cshung , is this still an issue for you?

**Comment by cshung** [comment]
It has been a while since I tried to do a build.
Let me try to build it again and see if it repros.

**Comment by mellinoe** [comment]
We aren't even using dnu to restore any longer, this issue is quite a bit out of date.

**Comment by cshung** [comment]
Let's close this for now. I cannot repro the build failure any more.
