### ISSUE TITLE
System.Net.Sockets.Tests.SendPacketsAsync.SocketDisconnected_TransmitFileOptionDisconnect(type: APM) failed in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#37776]
`System.Net.Sockets.Tests.SendPacketsAsync.SocketDisconnected_TransmitFileOptionDisconnect(type: APM)` failed on `netcoreapp-OSX-Debug-x64-OSX.1012.Amd64.Open`: https://dev.azure.com/dnceng/public/_build/results?buildId=193444&view=ms.vss-test-web.build-test-results-tab&runId=4669274&resultId=466803

```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Operation timed out [::1]:52861

   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 4445
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 833
   at System.Net.Sockets.Tests.SendPacketsAsync.SendPackets(SocketImplementationType type, SendPacketsElement element, TransmitFileOptions flags, Int32 bytesExpected) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.Sockets/tests/FunctionalTests/SendPacketsAsync.cs:line 458
   at System.Net.Sockets.Tests.SendPacketsAsync.SocketDisconnected_TransmitFileOptionDisconnect(SocketImplementationType type) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.Sockets/tests/FunctionalTests/SendPacketsAsync.cs:line 255
```

**Comment by ViktorHofer** [comment]
@davidsh @wfurt what is your recommendation here? should we move the test to outerloop, use the RetryHelper or investigate further why this timed out?

cc @stephentoub

**Comment by davidsh** [comment]
>@davidsh @wfurt what is your recommendation here? should we move the test to outerloop, use the RetryHelper or investigate further why this timed out?

We should try to understand why this timed out.  It's trying to connect to loopback address. This could be a case of too many tests running in parallel slowing down the test machine. But needs investigation.

**Comment by karelz** [comment]
Looks like one off - most likely CI flakiness. If there are more occurrences, let's reopen and investigate.
