### ISSUE TITLE
Setting Socket.SendTimeOut throws SocketException on Linux

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/corefx#3777]
The following code runs fine on Windows dnxcore50
```csharp
using System;
using System.Net.Sockets;

public class Program
{
    public static void Main()
    {
        var socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp)
        {
            SendTimeout = 200,
            ReceiveTimeout = 200
        };
    }
}
```

However on an Azure Linux VM it throws with Success!
```
System.Net.Sockets.SocketException: Success
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.set_SendTimeout(Int32 value)
   at Program.Main()
```

Here's my project.json

```javascript
{
  "commands": {
    "run": "test"
  },

  "frameworks": {
    "dnxcore50": {
      "compilationOptions": {
        "define": [ "NETCORE" ],
        "allowUnsafe": true,
        "warningsAsErrors": false
      },
      "dependencies": {
        "System.Console": "4.0.0-beta-*",
        "System.Net.Sockets": "4.1.0-beta-*",
        "System.Net.Security": "4.0.0-beta-*",
        "System.Net.NameResolution": "4.0.0-beta-*",
        "System.Net.Primitives": "4.0.11-beta-*"
      }
    }
  },
  "dependencies": {
  }
}
```

**Comment by pgavlin** [comment]
I cannot reproduce this on FC22. Trying Ubuntu now.

**Comment by jeremymeng** [comment]
oh, I am still using dnx 1.0.0-beta7.  Is it too old?

**Comment by pgavlin** [comment]
Yes, I believe so.

**Comment by jeremymeng** [comment]
This does not reproduce using dnx 1.0.0-beta8.
