### ISSUE TITLE
Crypto error on linux solus

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#37815]
Getting the following error when using HttpClient.GetAsync on Linux Solus:

I have openssl 1.0.2r installed.
Running Solus, https://getsol.us

```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.TypeInitializationException: The type initializer for 'SslMethods' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Ssl' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SslInitializer' threw an exception. ---> Interop+Crypto+OpenSslCryptographicException: error:25070067:DSO support routines:DSO_load:could not load the shared library
   at Interop.SslInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Ssl..cctor()
   --- End of inner exception stack trace ---
   at Interop.Ssl.SslV2_3Method()
   at Interop.Ssl.SslMethods..cctor()
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.AllocateSslContext(SslProtocols protocols, SafeX509Handle certHandle, SafeEvpPKeyHandle certKeyHandle, EncryptionPolicy policy, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SafeDeleteSslContext..ctor(SafeFreeSslCredentials credential, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_0(SslClientAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
```

**Comment by Priya91** [comment]
cc @henkesteen linking: https://github.com/MicrosoftDocs/live-share/issues/2105

**Comment by Priya91** [comment]
Using .NET Core 2.1.9 runtime (2.1.500 sdk)

**Comment by bartonjs** [comment]
> Interop+Crypto+OpenSslCryptographicException: error:25070067:DSO support routines:DSO_load:could not load the shared library

OpenSSL didn't load cleanly.  I've never seen that error before, so don't really have a good suggestion of where to start, but it'll probably involve native debuggers.

**Comment by henkesteen** [comment]
@bartonjs
I wrote this here already: https://github.com/MicrosoftDocs/live-share/issues/2105

But just to recap. I have Solus on 2 laptops, one is running live share perfectly, and the other one has this issue. So it's not a pure OS issue here.

**Comment by danmosemsft** [comment]
That is good because you can try comparing the machines. Maybe try LD_DEBUG (http://www.bnikolic.co.uk/blog/linux-ld-debug.html) and strace on both machines. Are they loading the same libraries and same versions?

**Comment by Arno500** [comment]
Actually I get the exact same error. I installed Solus 4 months ago, and tried quite a few things. On Solus, the version installed is OpenSSL-1.0. I tried everything I could find, like CLR_OPENSSL_VERSION_OVERRIDE (at 1.0 and 1.1), tried some strange symlinks...
I ran LD_DEBUG, and I can confirm the library is being loaded (the 1.0.0 file first if I remember correctly, the code managing the loading if available online).
Also reinstalled openSSL, but with no avail. Hope someone can come up with a solution !

**Comment by henkesteen** [comment]
Hello everyone!

I did a fresh reinstall of Solus a couple of days ago, install VSCode and Live Share, it still didn't work....

After installing the Solus system development tools, it worked.
`sudo eopkg it -c system.devel`

@Arno500 can you please try that and confirm, as I'm not 100% sure that it is the solution.

**Comment by Arno500** [comment]
For some reason, it worked ! I think this may be related to openssl-devel or libgpg-error-devel. This is still a problem with the "basic" version of OpenSSL...

**Comment by wfurt** [comment]
Is there any work left on this? If so, since 3.0 is out can somebody it give it try?
if it fails can we get output of  `strace -o trace.txt -f -s 200 -e trace=file XXX; grep ssl trace.txt  `. That should show what libraries .NET is trying to load.

**Comment by wfurt** [comment]
old issue on old product. closing. If .NET 3.x fail, please open new issue in https://github.com/dotnet/runtime  repo.
