### ISSUE TITLE
Show nested exceptions more clearly

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#37816]
We need to make output like this easier to read:
```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.TypeInitializationException: The type initializer for 'SslMethods' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Ssl' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SslInitializer' threw an exception. ---> Interop+Crypto+OpenSslCryptographicException: error:25070067:DSO support routines:DSO_load:could not load the shared library
   at Interop.SslInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Ssl..cctor()
   --- End of inner exception stack trace ---
   at Interop.Ssl.SslV2_3Method()
   at Interop.Ssl.SslMethods..cctor()
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.AllocateSslContext(SslProtocols protocols, SafeX509Handle certHandle, SafeEvpPKeyHandle certKeyHandle, EncryptionPolicy policy, SslAuthenticationOptions sslAuthenticationOptions)
  ...long trace
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
...long trace
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
...long trace
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
```

Amongst other issues the message is too hard to read since is 630 characters all on one line, with the most interesting part usually at the far end. It's hard to figure out which stack trace belongs to which message, and which is nested in which. 

In most cases the action is in Exception.ToString() but several exception subclasses have their own similar or identical scheme for handling inner exceptions and AggregateException is particularly special.

I plan to improve at least part of this, opening this issue for now.

**Comment by danmosemsft** [comment]
@stephentoub @jkotas is putting a newline with every `--->` a simple uncontroversial change I can make now?
```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.TypeInitializationException: The type initializer for 'SslMethods' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Ssl' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SslInitializer' threw an exception. ---> Interop+Crypto+OpenSslCryptographicException: error:25070067:DSO support routines:DSO_load:could not load the shared library
```
becomes
```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. 
---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. 
---> System.TypeInitializationException: The type initializer for 'SslMethods' threw an exception. 
---> System.TypeInitializationException: The type initializer for 'Ssl' threw an exception. 
---> System.TypeInitializationException: The type initializer for 'SslInitializer' threw an exception. 
---> Interop+Crypto+OpenSslCryptographicException: error:25070067:DSO support routines:DSO_load:could not load the shared library
```
If so I can make this change so we get a bit more readability, and we can think about other possible changes later.

**Comment by jkotas** [comment]
I would make the formatting for these same as formatting of `AggregateException` with a single inner exception.

**Comment by danmosemsft** [comment]
> And where would the stacktrace go?

Same as it is today, after the messages. Right now we have
```
type: message--->innertype: innermessage--->innerinnertype: innerinnermessage
innerinnerstack
--- End of inner exception stack trace ---
innerstack
--- End of inner exception stack trace ---
stack
```
this becomes
```
type: message
--->innertype: innermessage
--->innerinnertype: innerinnermessage
innerinnerstack
--- End of inner exception stack trace ---
innerstack
--- End of inner exception stack trace ---
stack
```
This can definitely be improved further (eg perhaps nesting) but that would take more discussion, I figured I would start with a small bite.

>  I would make the formatting for these as similar as possible to the formatting of AggregateException with a single inner exception.

Doesn't that have the same problem? Messages for nested exceptions are all on one line.
```
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: invalidoperation
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: invalidoperation<---
```
Doubly nested:
```
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: innerexception ---> System.Exception: innerinnerexception
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: innerexception ---> System.Exception: innerinnerexception
   --- End of inner exception stack trace ---<---
```
In general I think AggregateException formatting has even more problems!

I'm not suggesting that adding newlines makes everything great, just it's a step forward in reading test failure logs... 😸

**Comment by jkotas** [comment]
> AggregateException 

I though we have improved formatting for `AggregateException`, but that was just for the Message property: https://github.com/dotnet/coreclr/pull/2642

**Comment by GSPP** [comment]
Maybe number exceptions and separate them with an empty line?

```
#0: System.AggregateException: One or more errors occurred.

#1: ...
```

With `AggregateException` there can be a tree of exceptions. Maybe format the tree like

```
#0: System.AggregateException: One or more errors occurred.
#0.0: ...
#0.1: ...
#1: ...
```

It's great that this is being improved. The `Exception.ToString()` output is one of the most valuable debugging tools we have. What ever you do please do not remove any information. It is important that every piece of data available is shown here. `Exception.ToString()` should be the only string you need to log (no custom formatting needed).

**Comment by danmosemsft** [comment]
@GSPP note also https://github.com/dotnet/coreclr/pull/24793 which will generally add more info

**Comment by danmosemsft** [comment]
@GSPP wrt ordering do you believe the current organization - outermost message first, innermost stack first - is the correct, least confusing one?

**Comment by GSPP** [comment]
Yes, the outermost one should be first. It is the highest level piece of information. For example, all SQL errors are wrapped in `SqlException`. This is great because we can catch this single exception type and interpret it using its data properties. `SqlException` is a great example for exceptions done right.

The inner exception usually is meant to be logged and interpreted by the developer. Its contents are not contractual. It is additional uninterpretable data like the stack trace. For example, `SqlException` sometimes contains a `Win32Exception` "file not found" as its inner exception when the server cannot be reached. This is an artifact of the native API returning this particular error code. Inner exception is great for including additional error data when exceptions are wrapped.

Sometimes I see people drilling down to the innermost exception and calling this "root cause". This is complete nonsense.

**Comment by danmosemsft** [comment]
> Sometimes I see people drilling down to the innermost exception and calling this "root cause". This is complete nonsense.

In the case of the topmost example, it is actually true.  😺

**Comment by GSPP** [comment]
The "root cause" is not "the implementation detail that caused the exception to be thrown". I think *root cause* is ill defined; this wording does not mean anything concrete. That is what I mean by nonsense.

If a programmatic decision needs to be made on how to handle an error drilling to the innermost exception is very likely wrong.

**Comment by jkotas** [comment]
From Wikipedia [root cause](https://en.wikipedia.org/wiki/Root_cause) definition: initiating cause of either a condition or a causal chain . Describing the inner most exception as root cause is accurate, I think.

**Comment by gfoidl** [comment]
> the outermost one should be first

👍 

I see the term "root cause" well defined, and have the same view as @jkotas (so inner most exception = root cause).
