### ISSUE TITLE
System.Threading.Tasks.Tests.ExecutionContextFlowTest.TaskDropsExecutionContextUponCompletion failed in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#37843]
`System.Threading.Tasks.Tests.ExecutionContextFlowTest.TaskDropsExecutionContextUponCompletion` failed in CI on `netcoreapp-Windows_NT-Debug-x64-Windows.10.Amd64.ClientRS4.ES.Open`: https://dev.azure.com/dnceng/public/_build/results?buildId=195326&view=ms.vss-test-web.build-test-results-tab&runId=4726354&resultId=379881

```
System.TimeoutException : Task timed out after 00:01:00

   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter[TResult](Task`1 task, TimeSpan timeout) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 60
   at System.Threading.Tasks.Tests.ExecutionContextFlowTest.TaskDropsExecutionContextUponCompletion() in /_/src/System.Threading.Tasks/tests/Task/ExecutionContextFlowTest.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
```

cc @stephentoub

**Comment by tarekgh** [comment]
@ViktorHofer didn't you already activated https://github.com/dotnet/corefx/issues/34852? why we are opening another one?

**Comment by ViktorHofer** [comment]
That was a different issue test failure.

**Comment by tarekgh** [comment]
right but I believe it is same underlying cause as the code of both tests are similar.

**Comment by ViktorHofer** [comment]
If there's only one underlying action item feel free to close this one.

**Comment by tarekgh** [comment]
@ViktorHofer I am closing this issue but I am expecting we'll get it again. We have added some changes in the PR https://github.com/dotnet/corefx/pull/37874 to get more info and hopefully to create a dump we can use to do more diagnostics. Please, when we get it again, activate it and let me know. Thanks for your help here.
