### ISSUE TITLE
JsonSerializer throwing TargetInvocationException and IndexOutOfRangeException exceptions.

### ISSUE THREAD

**Issue by Yucked** [dotnet/corefx#37904]
When using `JsonSerializer.Parse<T>()` an `IndexOutOfRangeException` is thrown. Can't really figure out what's the cause of this.

It's throwing at [line 28](https://github.com/Yucked/Frostbyte/blob/d66727ff9107584f9812b1c04fd5a9a9e2b315be/Sources/YoutubeSource.cs#L28) and the [entity](https://github.com/Yucked/Frostbyte/blob/master/Entities/YouTubeResult.cs) that I'm trying to parse.

StackTrace:
```
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.Serialization.JsonClassInfo.GetProperty(JsonSerializerOptions options, ReadOnlySpan`1 propertyName, ReadStackFrame& frame)
   at System.Text.Json.Serialization.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.JsonSerializer.ParseCore(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializer.Parse[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
   at Frostbyte.Sources.YoutubeSource.<PrepareResponseAsync>d__3.MoveNext() in D:\Projects\Frostbyte\Sources\YoutubeSource.cs:line 29
```

Another exception that often comes up is `TargetInvocationException` when using the `JsonSerializer.ToBytes(object)` method.

```ArgumentException: Cannot bind to the target method because its signature is not compatible with that of the delegate type.```

StackTrace: 
```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Text.Json.Serialization.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.Serialization.JsonSerializer.HandleObject(JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
   at System.Text.Json.Serialization.JsonSerializer.WriteObject(JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
   at System.Text.Json.Serialization.JsonSerializer.Write(Utf8JsonWriter writer, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonSerializer.WriteCore(PooledBufferWriter`1 output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializer.WriteCoreBytes(Object value, Type type, JsonSerializerOptions options)
   at Frostbyte.Websocket.WsServer.<CollectStatsAsync>d__16.MoveNext() in D:\Projects\Frostbyte\Websocket\WSServer.cs:line 181

Inner Exception 1:
ArgumentException: Cannot bind to the target method because its signature is not compatible with that of the delegate type.
```

That class that I'm trying to serialize also includes a method, not sure if that could be the cause of that? [The class itself](https://github.com/Yucked/Frostbyte/blob/master/Entities/Packets/StatisticPacket.cs).

Let me know if there is anything else I can provide.

**Comment by vcsjones** [comment]
>ArgumentException: Cannot bind to the target method because its signature is not compatible with that of the delegate type.

Is usually the error that is currently thrown when attempting to (de)serialize something that is not supported (yet). #37545 is tracking unsupported scenarios and improving error output.

**Comment by ahsonkhan** [comment]
Looking at https://github.com/Yucked/Frostbyte/blob/d66727ff9107584f9812b1c04fd5a9a9e2b315be/Entities/YouTubeResult.cs#L6-L46, this should work. We should investigate why it isn't. Are you using the latest nightly-build of the SDK?

@steveharter, there is a class inheritance going on there with a custom ctor, is this supported?
https://github.com/Yucked/Frostbyte/blob/d66727ff9107584f9812b1c04fd5a9a9e2b315be/Entities/Packets/StatisticPacket.cs#L8-L44

**Comment by vcsjones** [comment]
@ahsonkhan one of the properties is `TimeSpan` which is a struct. Is that supported?

**Comment by Yucked** [comment]
@ahsonkhan I'm on .NET Core Preview 5 SDK and runtime.
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa```

Project also targets `netcoreapp3.0`.

**Comment by ahsonkhan** [comment]
>It's throwing at [line 28](https://github.com/Yucked/Frostbyte/blob/d66727ff9107584f9812b1c04fd5a9a9e2b315be/Sources/YoutubeSource.cs#L28) and the [entity](https://github.com/Yucked/Frostbyte/blob/master/Entities/YouTubeResult.cs) that I'm trying to parse.

I just tried from master and it is succeeding.
```C#
string json = "{\"hits\":12345, \"video\":[{\"encrypted_id\":\"foo\", \"author\":\"abcdefg\"}]}";
YouTubeResult result = JsonSerializer.Parse<YouTubeResult>(json);
Assert.Equal("abcdefg", result.Video[0].Author);
```

> I'm on .NET Core Preview 5 SDK and runtime.

Can you please try the nightly preview 6 runtime and also share a sample json payload that comes from the Youtube Search API where you were hitting this issue?
https://github.com/dotnet/core-setup#daily-builds

> Another exception that often comes up is `TargetInvocationException` when using the `JsonSerializer.ToBytes(object)` method.

Similarly here, I am not able to repro the issue anymore:
```C#
StatisticPacket temp = new StatisticPacket
{
    ConnectedPlayers = 2,
    Uptime = new TimeSpan(1234567),
    PlayingPlayers = 1,
    Memory = new MemoryEntity
    {
        Used = 123,
        Allocated = 7
    }
};

Assert.Equal(Encoding.UTF8.GetBytes("{\"pp\":1,\"cp\":2,\"mem\":{\"u\":123,\"alloc\":7},\"cpu\":null,\"upt\":{\"Ticks\":1234567,\"Days\":0," +
    "\"Hours\":0,\"Milliseconds\":123,\"Minutes\":0," +
    "\"Seconds\":0,\"TotalDays\":1.4288969907407408E-06,\"TotalHours\":3.429352777777778E-05,\"TotalMilliseconds\":123.45670000000001," +
    "\"TotalMinutes\":0.0020576116666666667,\"TotalSeconds\":0.12345669999999999}}"),
    JsonSerializer.ToBytes<StatisticPacket>(temp));
```

> one of the properties is `TimeSpan` which is a struct. Is that supported?

Struct support was added recently by @YohDeadfall, here: https://github.com/dotnet/corefx/issues/37434

**Comment by Yucked** [comment]
@ahsonkhan Prev 6 seems to have fixed both of the issues. Here is the payload from YT API:
https://pastebin.com/raw/Ma8SwjhZ

**Comment by Anipik** [comment]
This is fixed so closing this one

**Comment by ahsonkhan** [comment]
> Here is the payload from YT API:

cc @layomia
