### ISSUE TITLE
System.Data.SqlClient throws "System.InvalidOperationException : Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool. "

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#37915]
In ASP.NET Core tests, we started getting persistent errors in our tests that use SQL Server Local DB 2016, .NET Core 3, and System.Data.SqlClient.

```
Error Message:
 System.InvalidOperationException : Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
Stack Trace:
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
```

This error seemed to only affect Windows 7 and Windows 8.1.
https://mc.dot.net/#/user/aspnetcore/pr~2Faspnet~2Faspnetcore/ci/20190522.38/workItem/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test~2Fnetcoreapp3.0

This error was encountered as a result of a dependency-flow PR into AspNetCore https://github.com/aspnet/AspNetCore/pull/10434. This PR attempted to move System.Data.SqlClient from 4.7.0-preview6.19264.9 to 4.7.0-preview6.19270.12, and included these changes: https://github.com/dotnet/corefx/compare/a28176b5ec68b6da1472934fe9493790d1665cae...ef1a5aa730098b6c3350977a991232c1ff11cfe3.

cc @ajcvickers @Pilchie

**Comment by Wraith2** [comment]
I'm pretty sure there are no direct changes to SqlClient in that period, since I'm a source of a lot of SqClient changes I keep an eye on it so I don't get out of step. At the moment all work on it is stalled pending the Microsoft.Data.SqlClient move. It's worth keeping in mind that it would be related to underlying coreclr/corefx changes. Since it's on windows it's using the native implementation for network access which the same one used by desktop.

**Comment by cheenamalhotra** [comment]
Hi @natemcmaster 

Do you have a repro available by any chance or basic steps to reproduce the issue? Also does this still occur with .NET Core SDK 3.0 latest build or preview6 version?

**Comment by Pilchie** [comment]
@natemcmaster isn't around right now, but tagging @ajcvickers

**Comment by ajcvickers** [comment]
@Pilchie I doubt we will be able to reproduce this now. We moved all the ASP.NET tests to SQLite to reduce flakiness introduced by SQL Server, and I don't believe that the EF tests ever hit this. However, given our conversation yesterday, maybe we should unpin the SQLClient version we depend on and see if anything breaks. I will bring it up in the build sync this afternoon. /cc @dougbu
