### ISSUE TITLE
Test failure: ContentType_SetNullEmptyOrWhitespace_ResetsContentType

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#37962]
`System.Net.Tests.HttpListenerResponseHeadersTests.ContentType_SetNullEmptyOrWhitespace_ResetsContentType(contentType: null, expectedContentType: null)` failed on `netcoreapp-OSX-Debug-x64-OSX.1012.Amd64.Open`: https://dev.azure.com/dnceng/public/_build/results?buildId=202411&view=ms.vss-test-web.build-test-results-tab&runId=4899702&resultId=484348

```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Connection refused 127.0.0.1:1291

   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) in /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 4445
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP) in /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 833
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port) in /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 948
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port) in /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 959
   at System.Net.Sockets.Socket.Connect(String host, Int32 port) in /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 903
   at System.Net.Tests.HttpListenerFactory.GetConnectedSocket() in /_/src/System.Net.HttpListener/tests/HttpListenerFactory.cs:line 155
   at System.Net.Tests.HttpListenerResponseTestBase..ctor() in /_/src/System.Net.HttpListener/tests/HttpListenerResponseTests.cs:line 22
   at System.Net.Tests.HttpListenerResponseHeadersTests..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Private.CoreLib/src/System/RtType.cs:line 4573
```

**Comment by davidsh** [comment]
We had several loopback based tests failing on OSX during that time. Since then we haven't seen any problems.  Closing for now.
