### ISSUE TITLE
Socket.Connect(dnsname, port) throws System.ArgumentException on Linux

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/corefx#3797]
(Please see my project.json and a Program.cs template at https://github.com/dotnet/corefx/issues/3777)

The following code runs fine on Windows dnxcore50

```csharp
socket.Connect("yu-ubt2.cloudapp.net", 6379);
```

On Linux it throws
```
System.ArgumentException: The AddressFamily 117 is not valid for the System.Net.IPEndPoint end point, use InterNetwork instead.
Parameter name: socketAddress
   at System.Net.IPEndPoint.Create(SocketAddress socketAddress)
   at System.Net.Dns.TryGetAddrInfo(String name, AddressInfoHints flags, IPHostEntry& hostinfo)
   at System.Net.Dns.TryGetAddrInfo(String name, IPHostEntry& hostinfo)
   at System.Net.Dns.GetAddrInfo(String name)
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at Program.Main()
```

**Comment by jeremymeng** [comment]
This does not reproduce using dnx 1.0.0-beta8.
