### ISSUE TITLE
MonoTests.System.Runtime.Caching.MemoryCacheTest.Contains failed in CI on netfx

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#37989]
https://dev.azure.com/dnceng/public/_build/results?buildId=203415&view=ms.vss-test-web.build-test-results-tab&runId=4922022&resultId=158673&paneView=debug
netfx-Windows_NT-Release-x86-Windows.10.Amd64.ClientRS5.Open
```

Error message
Assert.True() Failure\r\nExpected: True\r\nActual: False

Stack trace
   at MonoTests.System.Runtime.Caching.MemoryCacheTest.Contains() in /_/src/System.Runtime.Caching/tests/System.Runtime.Caching/MemoryCacheTest.cs:line 274
```

**Comment by stephentoub** [comment]
Also failed on .NET Core on Windows 7:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38506~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190613.12/workItem/System.Runtime.Caching.Tests/analysis/xunit/MonoTests.System.Runtime.Caching.MemoryCacheTest~2FContains
```
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Assert.True() Failure
Expected: True
Actual:   False
Stack Trace :
   at MonoTests.System.Runtime.Caching.MemoryCacheTest.Contains() in /_/src/System.Runtime.Caching/tests/System.Runtime.Caching/MemoryCacheTest.cs:line 271
```

**Comment by stephentoub** [comment]
Failed again in https://github.com/dotnet/corefx/pull/41101

**Comment by ViktorHofer** [comment]
Failed again: https://dnceng.visualstudio.com/public/_build/results?buildId=392893&view=ms.vss-test-web.build-test-results-tab&runId=12204160&resultId=105087&paneView=debug
