### ISSUE TITLE
Socket.Connect(ipaddress, port) throws System.Net.Sockets.SocketException on Linux

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/corefx#3799]
(Please see my `project.json` at https://github.com/dotnet/corefx/issues/3777)

The following code runs fine on Windows dnxcore50

```csharp
using System;
using System.Net.Sockets;
using System.Threading;
using System.Threading.Tasks;

public class Program
{
    public static void Main()
    {
        var socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp)
        {
        };

        try
        {
            var str = "ping";
            var data = new byte[str.Length * sizeof(char)];
            System.Buffer.BlockCopy(str.ToCharArray(), 0, data, 0, data.Length);
            socket.Connect("127.0.0.1", 6379);
            socket.Send(data);
            Console.WriteLine("data sent to server");
        }
        catch (Exception ex)
        {
           System.Console.WriteLine(ex.ToString());
        }
    }
}
```

On Linux it throws
```
System.Net.Sockets.SocketException: Address family not supported by protocol 127.0.0.1:6379
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at Program.Main()
```

**Comment by pgavlin** [comment]
I cannot repro this on FC22. Trying Ubuntu now.

Which feed are you using?

**Comment by jeremymeng** [comment]
Could it be related to the Azure?
```
Feeds used:
    https://www.nuget.org/api/v2/
    /home/azureuser/nupkgs
```

**Comment by jeremymeng** [comment]
This does not reproduce using dnx 1.0.0-beta8.
