### ISSUE TITLE
Test failure:System.Net.Tests.HttpListenerContextTests/AcceptWebSocketAsync_InvalidHeaders_ThrowsWebSocketException(headers: \"Connection: Upgrade\\r\\nUpgrade: Test2\") 

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#38047]
Test `System.Net.Tests.HttpListenerContextTests/AcceptWebSocketAsync_InvalidHeaders_ThrowsWebSocketException(headers: \"Connection: Upgrade\\r\\nUpgrade: Test2\") `has failed.

Message :
```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Connection refused 127.0.0.1:1102
```
Stack Trace :
```
  at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) in /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 4445
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP) in /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 834
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port) in /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 949
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port) in /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 959
   at System.Net.Sockets.Socket.Connect(String host, Int32 port) in /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 906
   at System.Net.Tests.HttpListenerFactory.GetConnectedSocket() in /_/src/System.Net.HttpListener/tests/HttpListenerFactory.cs:line 169
   at System.Net.Tests.HttpListenerContextTests.GetSocketContext(String[] headers, Func`2 contextAction) in /_/src/System.Net.HttpListener/tests/HttpListenerContextTests.cs:line 246
   at System.Net.Tests.HttpListenerContextTests.AcceptWebSocketAsync_InvalidHeaders_ThrowsWebSocketException(String headers) in /_/src/System.Net.HttpListener/tests/HttpListenerContextTests.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
```
Build : Master - [20190529.66](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190529.66)

Failing configurations:
- OSX.1012.Amd64.Open-x64-Release

Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190529.66/workItem/System.Net.HttpListener.Tests/analysis/xunit/System.Net.Tests.HttpListenerContextTests~2FAcceptWebSocketAsync_InvalidHeaders_ThrowsWebSocketException(headers:%20%5C%22Connection:%20Upgrade%5C%5Cr%5C%5CnUpgrade:%20Test2%5C%22)

**Comment by davidsh** [comment]
Haven't seen this failure lately. Closing issue.
