### ISSUE TITLE
Test failure: System.Text.Json.Serialization.Tests.ObjectTests/Write(testObj: JsonElementClass { Array = , False = , Number = , Object = , String = , ... }) 

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#38092]
Test `System.Text.Json.Serialization.Tests.ObjectTests/Write(testObj: JsonElementClass { Array = , False = , Number = , Object = , String = , ... }) `has fail.
Message :
```
System.Text.Json.JsonException : The provided data of length 100 has remaining bytes 97.
```
Stack Trace :
```
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeDataRemaining(Int64 length, Int64 bytesRemaining) in /_/src/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs:line 70
   at System.Text.Json.Serialization.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 79
   at System.Text.Json.Serialization.JsonSerializer.Parse(String json, Type returnType, JsonSerializerOptions options) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 60
   at System.Text.Json.Serialization.Tests.ObjectTests.Write(ITestClass testObj) in /_/src/System.Text.Json/tests/Serialization/Object.WriteTests.cs:line 31
```

Build: Master - [20190530.71](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190530.71)

Failing configurations:

- Alpine.38.Arm64.Open-arm64-Release

Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190530.71/workItem/System.Text.Json.Tests/analysis/xunit/System.Text.Json.Serialization.Tests.ObjectTests~2FWrite(testObj:%20JsonElementClass%20%7B%20Array%20=%20,%20False%20=%20,%20Number%20=%20,%20Object%20=%20,%20String%20=%20,%20...%20%7D)

**Comment by MarcoRossignoli** [comment]
Again here https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38061~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190531.3/workItem/System.Text.Json.Tests/analysis/xunit/System.Text.Json.Serialization.Tests.ObjectTests~2FWrite(testObj:%20JsonElementClass%20%7B%20Array%20=%20,%20False%20=%20,%20Number%20=%20,%20Object%20=%20,%20String%20=%20,%20...%20%7D)

**Comment by stephentoub** [comment]
Again here:
https://dev.azure.com/dnceng/public/_build/results?buildId=206868&view=ms.vss-test-web.build-test-results-tab&runId=5025142&resultId=257238&paneView=debug

**Comment by steveharter** [comment]
@JeremyKuhne can you take a look please.
