### ISSUE TITLE
Issue with System.Management.ManagementClass in 3.0 Preview5

### ISSUE THREAD

**Issue by iSazonov** [dotnet/corefx#38093]
Come from https://github.com/PowerShell/PowerShell/issues/9780

Repo on PowerShell:
```
 [System.Management.ManagementClass]::new("ffdfdf")
Exception calling ".ctor" with "1" argument(s): "Cannot marshal 'parameter #3': Cannot marshal a string by-value with the [Out] attribute."
At line:1 char:1
+ [System.Management.ManagementClass]::new("ffdfdf")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : MarshalDirectiveException

PS C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\powershell-win-core\bin\Debug\netcoreapp3.0\win7-x64\publish>
PS C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\powershell-win-core\bin\Debug\netcoreapp3.0\win7-x64\publish> $error[0] | fl -Force

Exception             : System.Management.Automation.MethodInvocationException: Exception calling ".ctor" with "1" argu
                        ment(s): "Cannot marshal 'parameter #3': Cannot marshal a string by-value with the [Out] attrib
                        ute." ---> System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter
                        #3': Cannot marshal a string by-value with the [Out] attribute.
                           at System.StubHelpers.StubHelpers.ThrowInteropParamException(Int32 resID, Int32 paramIdx)
                           at System.Management.ManagementPath.GetWbemPath(IWbemPath wbemPath)
                           at System.Management.ManagementPath.GetWbemPath()
                           at System.Management.ManagementPath.get_Path()
                           at System.Management.ManagementPath.get_IsEmpty()
                           at System.Management.ManagementObject.ManagementObjectCTOR(ManagementScope scope, Management
                        Path path, ObjectGetOptions options)
                           at CallSite.Target(Closure , CallSite , Type , String )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exce
                        ption exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo) in
                        C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Automation\engine\runti
                        me\Operations\MiscOps.cs:line 2001
                           at CallSite.Target(Closure , CallSite , Type , String )
                           at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 a
                        rg1)
                           at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                         in C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Automation\engine\i
                        nterpreter\DynamicInstructions.Generated.cs:line 166
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedF
                        rame frame) in C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Automati
                        on\engine\interpreter\ControlFlowInstructions.cs:line 363
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : MarshalDirectiveException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
PSMessageDetails      :
```

I guess it is here:
https://github.com/dotnet/corefx/blob/2746a21357470e3da9e3e9222f2da350c9e5dd3a/src/System.Management/src/System/Management/ManagementPath.cs#L321

https://github.com/dotnet/corefx/blob/000aa2e0740524bdc2db690201e1b3521dd417a3/src/System.Management/src/System/Management/InteropClasses/WMIInterop.cs#L938

**Comment by jkotas** [comment]
cc @jkoritzinsky

**Comment by jkoritzinsky** [comment]
This has already been fixed in the preview 3 builds of System.Management (the second code snippet you linked is the fixed version). Since System.Management ships out-of-band, the package needs to be updated separately. Powershell 7 probably hasn't updated the package.

**Comment by danmosemsft** [comment]
Is there any work here for us? If not we should close this?

**Comment by jkoritzinsky** [comment]
There’s no work for us to do in the CoreFX repo on this.

**Comment by jkotas** [comment]
This is known issue with .NET Core 3.0 and old version of System.Management package.

For .NET Core 3.0, you need to reference latest preview version 4.6.0-preview5.19224.8 of https://www.nuget.org/packages/System.Management/ to workaround it.
