### ISSUE TITLE
JsonSerializer does not ignore or gracefully fail when serializing a class with a public indexer.

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#38131]
**Sample repro:**
```C#
public class IndexerTest
{
    int _index = 0;

    public int this[int index]
    {
        get => _index;
        set
        {
            _index = value;
        }
    }
}

[Fact]
public static void ClassWithIndexerTest()
{
    var foo = new IndexerTest();

    // Json.NET behavior:
    Assert.Equal("{}", JsonConvert.SerializeObject(foo));

    // Expected, something like the following OR a meaningful error:
    Assert.Equal("{}", JsonSerializer.ToString(foo));
}
```

**Actual behavior:**
```text
System.Text.Json.Serialization.Tests.StreamTests.ClassWithIndexerTest [FAIL]
        System.ArgumentException : Cannot bind to the target method because its signature is not compatible with that of the delegate type.
        Stack Trace:
          /_/src/System.Private.CoreLib/src/System/Delegate.CoreCLR.cs(338,0): at System.Delegate.CreateDelegate(Type type, MethodInfo method, Boolean throwOnBindFailure)
          /_/src/System.Private.CoreLib/shared/System/Delegate.cs(42,0): at System.Delegate.CreateDelegate(Type type, MethodInfo method)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\MemberAccessor.cs(72,0): at System.Text.Json.Serialization.MemberAccessor.CreateDelegate[TDelegate](MethodInfo methodInfo)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\MemberAccessor.cs(40,0): at System.Text.Json.Serialization.MemberAccessor.CreatePropertyGetter[TClass,TProperty](PropertyInfo propertyInfo)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonPropertyInfoCommon.cs(39,0): at System.Text.Json.Serialization.JsonPropertyInfoCommon`3.Initialize(Type parentClassType, Type declaredPropertyType, Type runtimePropertyType, PropertyInfo propertyInfo, Type elementType, JsonSerializerOptions options)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonClassInfo.AddProperty.cs(93,0): at System.Text.Json.Serialization.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonSerializerOptions options)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonClassInfo.AddProperty.cs(26,0): at System.Text.Json.Serialization.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonClassInfo.cs(104,0): at System.Text.Json.Serialization.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializerOptions.cs(281,0): at System.Text.Json.Serialization.JsonSerializerOptions.GetOrAddClass(Type classType)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\WriteStackFrame.cs(45,0): at System.Text.Json.Serialization.WriteStackFrame.Initialize(Type type, JsonSerializerOptions options)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Write.Helpers.cs(112,0): at System.Text.Json.Serialization.JsonSerializer.WriteCore(PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Write.Helpers.cs(86,0): at System.Text.Json.Serialization.JsonSerializer.WriteCoreString(Object value, Type type, JsonSerializerOptions options)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Write.String.cs(44,0): at System.Text.Json.Serialization.JsonSerializer.ToStringInternal(Object value, Type type, JsonSerializerOptions options)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Write.String.cs(21,0): at System.Text.Json.Serialization.JsonSerializer.ToString[TValue](TValue value, JsonSerializerOptions options)
          E:\GitHub\Fork\corefx\src\System.Text.Json\tests\Serialization\Stream.WriteTests.cs(43,0): at System.Text.Json.Serialization.Tests.StreamTests.ClassWithIndexerTest()
```

cc @JeremyKuhne, @steveharter, @buyaa-n

**Comment by MarcoRossignoli** [comment]
I grab this

**Comment by karelz** [comment]
@ahsonkhan please assign issues when someone grabs them - got contributors complaining that it is hard to use queries on unassigned work ... Thanks!
