### ISSUE TITLE
PerformanceCounter_NextValue_ProcessorCounter failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#38180]
```
Windows.10.Amd64.ClientRS4.ES.Open-x86-Release
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Assert.True() Failure
Expected: True
Actual:   False
Stack Trace :
   at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_NextValue_ProcessorCounter() in /_/src/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterTests.cs:line 156
```

**Comment by stephentoub** [comment]
Failed again:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38484~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190612.28/workItem/System.Diagnostics.PerformanceCounter.Tests/analysis/xunit/System.Diagnostics.Tests.PerformanceCounterTests~2FPerformanceCounter_NextValue_ProcessorCounter
```
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Assert.True() Failure
Expected: True
Actual:   False
Stack Trace :
   at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_NextValue_ProcessorCounter() in /_/src/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterTests.cs:line 156
```

**Comment by VincentBu** [comment]
Also seen in:
https://mc.dot.net/#/user/coreclr-corefx-jitstress2-jitstressregs/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190622.1/workItem/System.Diagnostics.PerformanceCounter.Tests/analysis/xunit/System.Diagnostics.Tests.PerformanceCounterTests~2FPerformanceCounter_NextValue_ProcessorCounter
