### ISSUE TITLE
Test failure: System.Text.RegularExpressions.Tests.RegexCultureTests/TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture 

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#38195]
Test `System.Text.RegularExpressions.Tests.RegexCultureTests/TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture ` has failed.

Message :
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
```

Stack Trace :
```
Child exception:
  Xunit.Sdk.AllException: Assert.All() Failure: 1 out of 2 items in the collection did not pass.
[1]: Item: Iıİi
     Xunit.Sdk.EqualException: Assert.Equal() Failure
     Expected: False
     Actual:   True
        at System.Text.RegularExpressions.Tests.RegexCultureTests.<>c__DisplayClass0_0.<TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture>b__5(Regex rex) in /_/src/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 40
   at System.Text.RegularExpressions.Tests.RegexCultureTests.<TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture>b__0_0() in /_/src/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 41

Child process:
  System.Text.RegularExpressions.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Text.RegularExpressions.Tests.RegexCultureTests Void <TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture>b__0_0()
```

Build: -[20190603.59](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190603.59) (Master)

Failing configurations:

- Windows.10.Amd64.ClientRS5.Open-x64-Release

Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190603.59/workItem/System.Text.RegularExpressions.Tests/analysis/xunit/System.Text.RegularExpressions.Tests.RegexCultureTests~2FTurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture

**Comment by ViktorHofer** [comment]
@stephentoub seems your change was not enough.

**Comment by stephentoub** [comment]
> seems your change was not enough.

Apparently not.  Not sure what's going on then, or what changed that it's failing now.

**Comment by danmosemsft** [comment]
I'm getting a timeout also
```
Timed out after 60000ms waiting for remote process.\n\tProcess ID: 2424\n\tHandle: 960\n

Stack trace
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutor/RemoteInvokeHandle.cs:line 131
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutor/RemoteInvokeHandle.cs:line 55
   at System.Text.RegularExpressions.Tests.RegexCultureTests.TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture() in /_/src/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 20
```
