### ISSUE TITLE
HttpClient that uses client certificate without access to private key hangs indefinitely

### ISSUE THREAD

**Issue by maciejw** [dotnet/corefx#38219]
I have a project that uses MIcrosoft.NETCore.App 2.2.0 and 2.1.0, a console app, it uses http clinet with client certificate to authenticate. 

```cs
using System;
using System.Linq;
using System.Net.Http;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;

namespace ClientCertificatesTests
{
    class Program
    {
        public static async Task Main(string[] args)
        {
            using (var handler = GetHttpHandler("some-thumbprint"))
            {
                using (var client = new HttpClient(handler))
                {
                    try
                    {
                        var response = await client.GetAsync("https://some-server/some-endpoint");

                        Console.WriteLine(response.StatusCode);

                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(ex);
                    }
                }
            }
        }

        static HttpMessageHandler GetHttpHandler(string thumbPrint)
        {
            X509Certificate2 clientCertificate = GetCertificate(thumbPrint);

            var handler = new SocketsHttpHandler
            {
                SslOptions = new SslClientAuthenticationOptions
                {
                    ClientCertificates = new X509CertificateCollection
                    {
                        clientCertificate
                    },
                }
            };

            return handler;
        }

        static X509Certificate2 GetCertificate(string thumbPrint)
        {
            using (X509Store certStore = new X509Store(StoreName.My, StoreLocation.LocalMachine))
            {
                certStore.Open(OpenFlags.ReadOnly);
                var certificateCollection = certStore.Certificates.Find(X509FindType.FindByThumbprint, thumbPrint, false);

                var certificate = certificateCollection.OfType<X509Certificate2>().FirstOrDefault();

                if (certificate == null)
                {
                    throw new Exception("Missing certificate");
                }

                return certificate;
            }
        }
    }
}

```

Certificate is located in local machine personal store. When my user does not have access to private key (run from not elevated command prompt), Win32Exception is thrown with message "The credentials supplied to the package were not recognized" from https://github.com/dotnet/corefx/blob/3c30357d51b96339021b4ee52f38445c31248bb2/src/Common/src/Interop/Windows/SspiCli/SSPIWrapper.cs#L136, but this exception is not propagated to task and there is no continuation called, my catch block is not executed, process hangs indefinitely. 
This is just an real life example, from my observation it is not specifically related to this exception, any exception thrown during that phase of ssl handshake is swallowed this way.

I can even force this behavior from my code with this with this setup:
```cs

            var i = 0;
            var handler = new SocketsHttpHandler
            {
                SslOptions = new SslClientAuthenticationOptions
                {
                    LocalCertificateSelectionCallback = (sender, targetHost, localCertificates, remoteCertificate, acceptableIssuers) =>
                    {
                        i++;
                        if (i == 2)
                            throw new Exception("This will hang forever!!!");
                        return localCertificates[0];
                    },
                    ClientCertificates = new X509CertificateCollection {
                        clientCertificate
                    },
                }
            };
```

This i variable is required because my server is trying renegotiate connection and this problem will manifest itself during second local certificate selection only.

**Comment by davidsh** [comment]
This is a known issue in .NET Core 2.1/2.2.  The hang was fixed in .NET Core 3.0.  So, the exception should propagate correctly now.

Have you tried .NET Core 3.0 latest Preview?

**Comment by davidsh** [comment]
See https://github.com/dotnet/corefx/issues/30858#issuecomment-485191640 for a similar discussion of the "hang".

**Comment by maciejw** [comment]
I'll check this discussion you mentioned, sadly I cannot run net core 3.0 preview in my production, if this is fixed in 3.0, it should be fixed in 2.1 also, if not, LTS status is completely meaningless, this is clearly a serious bug.

**Comment by davidsh** [comment]
@karelz

**Comment by wfurt** [comment]
It would be nice if you can at least verify with 3.0 @maciejw even if you cannot depend on it in production.

**Comment by maciejw** [comment]
Sure I can, I've downloaded 3.0.0-preview5-27626-15, retargeted my project and exception is propagated correctly, this one from code snippet I've provided here as well as security exception related to certificates

```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.ComponentModel.Win32Exception: The credentials supplied to the package were not recognized
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslStream.CheckOldKeyDecryptedData(Memory`1 buffer)
   at System.Net.Security.SslStream.HandleQueuedCallback(Object& queuedStateRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at DiagnosticListenerTests.Program.CallCustom(HttpClient tokenClient, String Address, String ClientId, String Scope) in C:\Source\tests\....\Program.cs:line 148

```

witch was my original problem I stumbled upon.

**Comment by davidsh** [comment]
Closing this since it is fixed in .NET Core 3.0.

**Comment by maciejw** [comment]
...so this will not end up in 2.1 LTS I guess, you are right, this is not huge bug after all... I'll tell my OPS that we are abandoning 2.1 LTS and move on with 3.0 preview5 in production they will agree with this move without any hesitations...
