### ISSUE TITLE
Lots of 1st-chance exceptions from HTTP/2 requests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#38267]
I made 100 serial HTTP/2 requests to https://www.microsoft.com:
```C#
            using (var client = new HttpClient())
            {
                client.DefaultRequestVersion = new Version(2, 0);
                for (int i = 0; i < 100; i++)
                {
                    await client.GetStringAsync("https://www.microsoft.com");
                }
            }
```
All the requests completed but incurred 28 first-chance exceptions, all of the form:
```
System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.. ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
     --- End of inner exception stack trace ---
     at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in D:\repos\corefx\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs:line 1107
     at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token) in D:\repos\corefx\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs:line 1073
     at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial) in D:\repos\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 1478
     at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer) in D:\repos\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 1356
     at System.Net.Http.Http2Connection.ReadAtLeastAsync(Stream stream, Memory`1 buffer, Int32 minReadBytes) in D:\repos\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 1520
     at System.Net.Http.Http2Connection.EnsureIncomingBytesAsync(Int32 minReadBytes) in D:\repos\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 154
     at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame) in D:\repos\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 180
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
```
cc: @geoffkizer, @wfurt

**Comment by stephentoub** [comment]
Sorry, yes, Windows.  I just added:
```C#
            int counter = 0;
            AppDomain.CurrentDomain.FirstChanceException += (s, e) => Console.WriteLine(Interlocked.Increment(ref counter) + Environment.NewLine + e.Exception.ToString() + Environment.NewLine + Environment.NewLine);
```
to see what was being thrown.

**Comment by scalablecory** [comment]
I was not able to repro this to get 995 (operation aborted), but did end up getting lots of 10053 (connection aborted) and some `ObjectDisposedException` by introducing some GC:

```c#
[Fact]
public async Task FirstChanceExceptions()
{
    int counter = 0;
    AppDomain.CurrentDomain.FirstChanceException += (s, e) => Console.WriteLine(Interlocked.Increment(ref counter) + Environment.NewLine + e.Exception.ToString() + Environment.NewLine + Environment.NewLine);

    var src = new CancellationTokenSource();
    Task t1 = Task.Run(async () =>
    {
        while (!src.IsCancellationRequested)
        {
            GC.Collect();
            await Task.Yield();
        }
    });

    using (var client = CreateHttpClient())
    {
        for (int i = 0; i < 200; i++)
        {
            await client.GetStringAsync("https://www.microsoft.com");
        }
    }

    src.Cancel();
    await t1;
}
```

May be related to #38481 which also gets the same `ObjectDisposedException`.

**Comment by stephentoub** [comment]
I can't repro this anymore.  Likely some of the fixes that went in in the interim addressed it.

**Comment by wfurt** [comment]
on a side note: didn't we have some environmental variables to cause more aggressive GC @stephentoub

**Comment by Gnbrkm41** [comment]
@wfurt `COMPlus_GCStress`?

**Comment by scalablecory** [comment]
I'm still seeing exceptions, albeit with different exceptions now:

```
  System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
   ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
     --- End of inner exception stack trace ---
     at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in C:\dev\corefx\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs:line 1107
     at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token) in C:\dev\corefx\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs:line 1073
     at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial) in C:\dev\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 1478
     at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer) in C:\dev\corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 1356
     at System.Net.Http.Http2Connection.ReadAtLeastAsync(Stream stream, Memory`1 buffer, Int32 minReadBytes) in C:\dev\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 1574
     at System.Net.Http.Http2Connection.EnsureIncomingBytesAsync(Int32 minReadBytes) in C:\dev\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 155
     at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame) in C:\dev\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 181
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
```

**Comment by karelz** [comment]
@scalablecory seems to work on this, unassigning @wfurt

**Comment by scalablecory** [comment]
Unable to repro now. Appears to be fixed.
