### ISSUE TITLE
System.Security.Cryptography does not provide a way to handle NTE_BAD_KEY_STATE

### ISSUE THREAD

**Issue by FailedShack** [dotnet/corefx#38260]
The API provided by `System.Security.Cryptography` allows you store keys in containers using `CspParameters`. However, these key containers can become inaccessible in some cases and the API does not provide a graceful way to remove them, instead throwing `CryptographicException` exceptions with unhelpful messages.

Take this very simple program, for example:
```cs
class Program
{
    static void Main(string[] args)
    {
        var cp = new CspParameters() { KeyContainerName = "TestContainer" };
        using (var rsa = new RSACryptoServiceProvider(2048, cp) { PersistKeyInCsp = true })
        {
            Console.WriteLine("Key in container: \n{0}", rsa.ToXmlString(true));
        }
    }
}
```
When you run it for the first time, a 2048-bit RSA key pair will be generated and stored in a container named `TestContainer` and print it to the console in XML form. Consecutive executions will simply load the existing key from the container.

Unfortunately, this code will throw the following exception in some special occasions:
```
System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.

   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean useDefaultKeySize)
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters)
   at CryptoBugTest.Program.Main(String[] args)
```

Now that error message is not very clear in it's meaning, and I couldn't find this exception case in the .NET documentation. After a while I found [this brilliant StackOverflow answer](https://stackoverflow.com/a/4294877/9737456).
The following is a brief adaptation of the explanation contained within it:

> These key containers are stored in `%APPDATA%\Microsoft\Crypto\DSS\[SID]`.
The cryptography classes internally use the unmanaged CryptoAPI. So the method _OpenCSP calls the native [CryptAcquireContext](http://msdn.microsoft.com/en-us/library/aa379886%28VS.85%29.aspx) function. In its documentation we can read following about the error `NTE_BAD_KEY_STATE (0x8009000BL)`: `The user password has changed since the private keys were encrypted.`
>
> The files will be encrypted with a key which depends on the user's password. In many standard cases the files will be re-encrypted after the password change. However, if the password was instead reset, not changed by the user itself, by from an administrator, the files in the old directory, `%APPDATA%\Microsoft\Crypto\DSS\[SID]`, will no longer be accessible.

You can reproduce this with the program cited above by following these steps:
1. Create a test Windows account with a password (doesn't matter what it is).
2. Log into the test account and run the sample application.
3. Log off and switch over to the Administrator account.
4. Remove the password from the test account.
5. Log off once more and switch over to the test account, run the sample application again.

The program should then crash with the above exception.

.NET leaves the entire burden of dealing with this situation to the developer. The only available solution right now is to delete the key container file manually, which also poses its own set of problems.

For the following section of the explanation I'll be referencing code from a workaround we've implemented in a personal project of mine which uses FiddlerCore, a popular library affected by this issue that makes use of key containers. This issue was initially reported [here](https://www.telerik.com/forums/fiddler-bccertmaker-failed-to-create-certificate), the commit containing the workaround can be found [here](https://github.com/FailedShack/USBHelperLauncher/commit/33d2f825e447d416b678415581fbd8bc03175182).

For starters, there is no way to detect that a key container is inaccessible other than forcing a CryptographicException by, for example, attempting to retrieve the `UniqueKeyContainerName` property from the `CspKeyContainerInfo` as such:

```cs
string keyContainerName = FiddlerApplication.Prefs.GetStringPref("fiddler.certmaker.bc.KeyContainerName", "FiddlerBCKey");
try
{
    CspParameters cspParams = new CspParameters { KeyContainerName = keyContainerName };
    var _ = new CspKeyContainerInfo(cspParams).UniqueKeyContainerName; // this will throw an exception if the container cannot be accessed
}
catch (CryptographicException) { /* Inaccessible container */ }
```

Another problem is that this exception is also ambiguous, as it can also mean that the key container is simply non-existant, so we also have to take that possibility into account.

Then we need to write code to replicate the hash used to name the key container file, after some research we came accross this [article](https://lordjeb.com/2016/06/30/deriving-unique-key-container-name-for-rsacryptoserviceprovider/), which explains how to do that.

Finally we can delete it from `%APPDATA%\Microsoft\Crypto\DSS\[SID]`, right?
Your first thought is to simply use `Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)`, to retrieve the location of `%APPDATA%`, and it will work... [until someone decides to change the location of `%APPDATA%`](https://github.com/FailedShack/USBHelperLauncher/issues/44#issuecomment-498312772).

Apparently, Windows keeps part of its `Microsoft` folder in the default `%APPDATA%` location, including the `Crypto` folder, which we need to access. So, how do we retrieve the default `%APPDATA%` path, you ask? Well, we simply can't without resorting to unmanaged APIs, as evidenced by #38253.

Seeing the lengths one has to go through to handle this case, I would say this is a shortcoming of the .NET implementation as it does not take this case into account and provides no graceful way to handle it.

**Comment by davidsh** [comment]
@bartonjs

**Comment by bartonjs** [comment]
@FailedShack Do you just want something like `CspParamters.Delete(CspParameters keyId)` to delete the key identified by the parameters?  (Similar to how CNG is modelled.  Also, all of the CSP stuff is legacy, you should really be using CNG when doing Windows-specific platform interop)

**Comment by FailedShack** [comment]
@bartonjs I honestly didn't know there was an alternate cryptographic API in .NET.
Every single resource I've seen still uses `CspParameters`. It would seem like this CNG aims to be a replacement for CSP, so why isn't CSP deprecated?

In any case, since the problem actually occurs in an external library, I have no choice but to use CSP and seeing the wide adoption it has I can't help but think many developers might once be on the same boat.
I was thinking a solution could be adding an `IsAccessible` property to `CspParameters`, which returns whether or not a key container is accessible, along with a `Delete` instance method you could use in conjunction like this:
```cs
var keyContainerName = FiddlerApplication.Prefs.GetStringPref("fiddler.certmaker.bc.KeyContainerName", "FiddlerBCKey");
var csp = new CspParameters { KeyContainerName = keyContainerName };
if (!csp.IsAccessible)
{
    csp.Delete();
}
```
Although a static method is also fine if it's preferable.

In addition, if an inaccessible key container were to be accessed, a different exception should be thrown other than `CryptographicException`, since it causes ambiguity. Perhaps `InvalidOperationException` or a new exception (`KeyContainerNotAccessibleException`?) with a descriptive message.

These changes I think would leave this matter in a much better place than it is at the moment.

**Comment by bartonjs** [comment]
> I was thinking a solution could be adding an IsAccessible property to CspParameters,

That would be a bit weird, since CspParameters lets all of its properties be rewritten.  It shouldn't really have any methods on instances, just be used as the input to other methods.

> It would seem like this CNG aims to be a replacement for CSP, so why isn't CSP deprecated?

Windows has deprecated it (e.g. the banner at https://docs.microsoft.com/en-us/windows/desktop/api/wincrypt/nf-wincrypt-cryptacquirecontexta).  In .NET we have a harder time marking something as deprecated, though we're working on new ways.  All the CSP stuff is recorded in our ApiCompat matrix, which will (or maybe does) have a Roslyn analyzer for reporting that you should change your code.  e.g. https://github.com/dotnet/corefx/wiki/ApiCompat#systemsecuritycryptographyrsacryptoserviceprovider

> a different exception should be thrown other than CryptographicException, since it causes ambiguity

Moving to `InvalidOperationException` would be a breaking change (changing which catch blocks do/don't apply).  Moving to a derived type could work... but given that we consider the CryptoServiceProvider classes as legacy now, I don't know that it's worth introducing a new public exception type for this case.

To circle back to how you're deleting the values, the answer I would recommend is trying to P/Invoke to CryptAcquireKey with the CRYPT_DELETE_KEYSET flag... that way the API that wrote the file is responsible for deleting it.

**Comment by FailedShack** [comment]
> It shouldn't really have any methods on instances, just be used as the input to other methods.

I see. Well, then they both could be static as per your initial suggestion:
```cs
var keyContainerName = FiddlerApplication.Prefs.GetStringPref("fiddler.certmaker.bc.KeyContainerName", "FiddlerBCKey");
var csp = new CspParameters { KeyContainerName = keyContainerName };
if (!CspParameters.IsAccessible(csp))
{
    CspParameters.Delete(csp);
}
```

> Moving to InvalidOperationException would be a breaking change

By "inaccessible", I don't mean as in the case in which it doesn't exist, which is already covered in the documentation as throwing a CryptographicException, but rather the case where it's thrown due to `NTE_BAD_KEY_STATE`, which is currently undocumented. So in that sense, it would not be changing but rather adding a new catch clause, which could still be considered as breaking, however, I would argue that the current undocumented behavior could also be considered as such.

![CspDocs](https://user-images.githubusercontent.com/39192928/59059261-d027f280-889e-11e9-9c32-d55bdf99d5da.PNG)

That said, I guess documenting the fact that a `CryptographicException` can also be thrown in this case would be fine, provided there's another way to determine whether a key container is not accessible, such as the proposed `IsAccessible`.

> I would recommend is trying to P/Invoke to CryptAcquireKey with the CRYPT_DELETE_KEYSET flag

Thanks for the suggestion. Since .NET didn't seem to have a binding to delete key containers I just assumed it wouldn't exist in WinAPI either, as I admittedly don't have much experience working with it. Since we were already going to have to use P/Invoke for `SHGetKnownFolderPath`, might as well use this instead. At least until a properly managed solution is implemented in .NET.
