### ISSUE TITLE
Writing large JsonElement via JsonSerializer.WriteAsync hangs

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#38294]
There's a bug in the writing loop that causes writing a JsonElement to hang forever. Here's the sample code:

```C#
var json = await new HttpClient().GetStringAsync("https://raw.githubusercontent.com/davidfowl/AspNetCoreDiagnosticScenarios/master/Scenarios/pokemon.json");
var root = JsonSerializer.Parse<JsonElement>(json);
var ms = new MemoryStream();
await JsonSerializer.WriteAsync(root, root.GetType(), ms);
```

cc @rynowak @steveharter @ahsonkhan @JeremyKuhne

**Comment by MarcoRossignoli** [comment]
Signature on master is
```
 await JsonSerializer.WriteAsync(ms, root, root.GetType());
```
I get a different error
```
 Discovering: System.Text.Json.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.Json.Tests (found 1 of 811 test case)
  Starting:    System.Text.Json.Tests (parallel test collections = off, max threads = 8)
    System.Text.Json.Serialization.Tests.ExtensionDataTests.MyTest [FAIL]
      System.InvalidOperationException : Cannot write the start of an object/array after a single JSON value or outside of an existing closed object/array. Current token type is 'EndObject'.
```
Seems related to evaluation order on value write [`finishedSerializing`](https://github.com/dotnet/corefx/blob/7626863d5a48f771513f7d22977189aab14dcd0b/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.cs#L56) is evaluated too late and serialization go on.
I'm working on a solution.

**Comment by ahsonkhan** [comment]
> I get a different error

For reference, here's the whole stack:
```text
 System.InvalidOperationException : Cannot write the start of an object/array after a single JSON value or outside of an existing closed object/array. Current token type is 'EndObject'.
        Stack Trace:
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\ThrowHelper.cs(374,0): at System.Text.Json.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource, Int32 currentDepth, Byte token, JsonTokenType tokenType)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Writer\Utf8JsonWriter.cs(515,0): at System.Text.Json.Utf8JsonWriter.ValidateStart()
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Writer\Utf8JsonWriter.cs(497,0): at System.Text.Json.Utf8JsonWriter.WriteStartSlow(Byte token)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Writer\Utf8JsonWriter.cs(454,0): at System.Text.Json.Utf8JsonWriter.WriteStart(Byte token)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Writer\Utf8JsonWriter.cs(443,0): at System.Text.Json.Utf8JsonWriter.WriteStartObject()
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Document\JsonDocument.cs(740,0): at System.Text.Json.JsonDocument.WriteElementTo(Int32 index, Utf8JsonWriter writer)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Document\JsonElement.cs(1142,0): at System.Text.Json.JsonElement.WriteValue(Utf8JsonWriter writer)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\Converters\JsonValueConverterJsonElement.cs(28,0): at System.Text.Json.Serialization.Converters.JsonValueConverterJsonElement.Write(JsonElement value, Utf8JsonWriter writer)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonPropertyInfoNotNullable.cs(96,0): at System.Text.Json.JsonPropertyInfoNotNullable`3.Write(WriteStackFrame& current, Utf8JsonWriter writer)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Write.cs(33,0): at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Write.Stream.cs(83,0): at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type type, JsonSerializerOptions options, CancellationToken cancellationToken)
          E:\GitHub\Fork\corefx\src\System.Text.Json\tests\Serialization\Value.ReadTests.cs(21,0): at System.Text.Json.Serialization.Tests.ValueTests.ReadPrimitives()
          --- End of stack trace from previous location where exception was thrown ---
```

**Comment by MarcoRossignoli** [comment]
@ahsonkhan fixed in #38308

**Comment by davidfowl** [comment]
FYI the hang exists in preview6 then?

**Comment by ahsonkhan** [comment]
> FYI the hang exists in preview6 then?

No, preview6 fails with the error shown above (not a hang). Just verified on the corefx release branch.
> System.InvalidOperationException : Cannot write the start of an object/array after a single JSON value or outside of an existing closed object/array. Current token type is 'EndObject'.

I don't know where you are getting the hang from. Can you share the `dotnet.exe --info` output and your sample repro (is it targeting 3.0?)?

**Comment by davidfowl** [comment]
`.NET Core 3.0.0-preview7-27806-02`

**Comment by davidfowl** [comment]
```
.NET Core 3.0.0-preview7-27806-02
Unhandled exception. System.IO.IOException: Stream was too long.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type type, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Samples.Program.Main(String[] args) in C:\dev\git\Web.Framework\Samples\Program.cs:line 22
   at Samples.Program.<Main>(String[] args)
```

**Comment by ahsonkhan** [comment]
> Unhandled exception. System.IO.IOException: Stream was too long.

Yep, I can repro that now. Thanks! I was trying in debug-mode earlier which is why I couldn't see the failure - we have SkipValidation off on the writer in debug.
https://github.com/dotnet/corefx/blob/20ba99aaf60ba91180f304211b096e1147564a7c/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs#L298-L307

https://github.com/dotnet/corefx/pull/38308 does fix the underlying issue.

**Comment by davidfowl** [comment]
Might be worth bubbling this up in a known issues list
