### ISSUE TITLE
Test failure : System.Diagnostics.Tests.ProcessTests/LongProcessNamesAreSupported 

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#38443]
Test `System.Diagnostics.Tests.ProcessTests/LongProcessNamesAreSupported ` has failed.

Message :
```
System.FormatException : Input string was not in a correct format.
```

Stack Trace :
```
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type) in /_/src/System.Private.CoreLib/shared/System/Number.Parsing.cs:line 1931
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info) in /_/src/System.Private.CoreLib/shared/System/Number.Parsing.cs:line 216
   at System.Int32.Parse(String s) in /_/src/System.Private.CoreLib/shared/System/Int32.cs:line 107
   at System.PlatformDetection.ToVersion(String versionString) in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 165
   at System.PlatformDetection.GetDistroInfo() in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 169
   at System.PlatformDetection.IsDistroAndVersion(Predicate`1 distroPredicate, Int32 major, Int32 minor, Int32 build, Int32 revision) in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 208
   at System.PlatformDetection.IsDistroAndVersion(String distroId, Int32 major, Int32 minor, Int32 build, Int32 revision) in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 187
   at System.PlatformDetection.get_IsAlpine() in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 32
   at System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported() in /_/src/System.Diagnostics.Process/tests/ProcessTests.cs:line 1912
```

Build: -[20190610.76](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190610.76)(Master)

Failing configurations:

- Debian.10.Amd64.Open-x64-Release

Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190610.76/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessTests~2FLongProcessNamesAreSupported

**Comment by danmosemsft** [comment]
@AriNuer can you please update this issue when you see this happen again? It should have more diagnostics.

**Comment by danmosemsft** [comment]
Never mind, I just looked in Kusto. Here you are @stephentoub . It just doesn't have ID or VERSION_ID in /etc/os-release.
```
System.FormatException : Failed to parse version string: ''\n---- System.FormatException : Input string was not in a correct format.

   at System.PlatformDetection.ToVersion(String versionString) in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 171
   at System.PlatformDetection.GetDistroInfo() in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 176
   at System.PlatformDetection.IsDistroAndVersion(Predicate`1 distroPredicate, Int32 major, Int32 minor, Int32 build, Int32 revision) in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 215
   at System.PlatformDetection.IsDistroAndVersion(String distroId, Int32 major, Int32 minor, Int32 build, Int32 revision) in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 194
   at System.PlatformDetection.get_IsAlpine() in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 32
   at System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported() in /_/src/System.Diagnostics.Process/tests/ProcessTests.cs:line 1912
----- Inner Stack Trace -----
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type) in /_/src/System.Private.CoreLib/shared/System/Number.Parsing.cs:line 1931
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info) in /_/src/System.Private.CoreLib/shared/System/Number.Parsing.cs:line 216
   at System.Int32.Parse(String s) in /_/src/System.Private.CoreLib/shared/System/Int32.cs:line 107
   at System.PlatformDetection.ToVersion(String versionString) in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 167
```
```
Jobs
| where Started > ago(5d)
| where Type startswith "test/functional/cli/"
| join kind=inner TestResults on JobId
| where Result == "Fail"
| where Method startswith "LongProcessNamesAreSupported"
```

**Comment by AriNuer** [comment]
same test `System.Diagnostics.Tests.ProcessTests/LongProcessNamesAreSupported ` has failed again with
similar exceptions.

Message :
```
System.FormatException : Failed to parse version string: ''
---- System.FormatException : Input string was not in a correct format.
```

Stack Trace :
```
at System.PlatformDetection.ToVersion(String versionString) in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 171
   at System.PlatformDetection.GetDistroInfo() in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 176
   at System.PlatformDetection.IsDistroAndVersion(Predicate`1 distroPredicate, Int32 major, Int32 minor, Int32 build, Int32 revision) in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 215
   at System.PlatformDetection.IsDistroAndVersion(String distroId, Int32 major, Int32 minor, Int32 build, Int32 revision) in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 194
   at System.PlatformDetection.get_IsAlpine() in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 32
   at System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported() in /_/src/System.Diagnostics.Process/tests/ProcessTests.cs:line 1912
----- Inner Stack Trace -----
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type) in /_/src/System.Private.CoreLib/shared/System/Number.Parsing.cs:line 1931
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info) in /_/src/System.Private.CoreLib/shared/System/Number.Parsing.cs:line 216
   at System.Int32.Parse(String s) in /_/src/System.Private.CoreLib/shared/System/Int32.cs:line 107
   at System.PlatformDetection.ToVersion(String versionString) in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 167
```
Build: -[20190612.69](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190612.69)(Master)

Failing configurations:

- Debian.10.Amd64.Open-x64-Release

Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190612.69/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessTests~2FLongProcessNamesAreSupported

**Comment by tmds** [comment]
Can someone `cat /etc/os-release` on the Debian.10 VM?

The docker image seems to have an ok VERSION_ID:
```
$ docker run debian:buster cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by tmds** [comment]
> Never mind, I just looked in Kusto. Here you are @stephentoub . It just doesn't have ID or VERSION_ID in /etc/os-release.

I had missed this comment from @danmosemsft . Since the docker image looks fine, maybe an issue with the version installed in the VM?

**Comment by danmosemsft** [comment]
I'm confused, the docker image is what the tests run on isn't it? @wfurt , thoughts?

We could easily tweak https://github.com/dotnet/corefx/pull/38463 to also include the full text of /etc/os-release in the exception it throws.

**Comment by danmosemsft** [comment]
@wfurt do you know how to pull the content of `/etc/os-version` from the debian 10 image we are testing with here?

**Comment by wfurt** [comment]
It was in #38008 
```
joshua@nova:~ϟ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Since that is rolling release, there is no version whatsoever. 
If somebody wants to experiment we can grab Docker ID from helix build prereqs.

**Comment by danmosemsft** [comment]
Thanks @wfurt, and I even replied to that comment too!

In the near term I suggest we change `ToVersion` to not throw ie (ie use TryParse). In this case, the calling code apparently does not need the version anyway. Does htat seem reasonable?

**Comment by wfurt** [comment]
yes, I think returning 0.0 or -1.-1 sounds reasonable to me.

**Comment by bartonjs** [comment]
Since the cases that we know if with no version are when the distro is too new, I'd call it `new Version(int.MaxValue, int.MaxValue)`; so that things like IsUbuntu1810OrHigher (or a mythical IsDebian9OrHigher) return true.

**Comment by joshudson** [comment]
Ah timeskew. I'm actually on buster myself and since me posting the pull request VERSION_ID got a value. The pull request will probably not be necessary now. I'm going to leave it up because the man page for os-release says a-z are allowed in those fields.

https://manpages.debian.org/testing/systemd/os-release.5.en.html

The proposal to unify requires an API review to expose a more forgiving parser for version so really should wait until after 3.0 but when it does will actually fix this.

**Comment by danmosemsft** [comment]
In that man page I also see `Applications should check for the former, and exclusively use its data if it exists, and only fall back to /usr/lib/os-release if it is missing.` which currently this code does not consult. I guess it is not a problem so far.

**Comment by joshudson** [comment]
I see

> VERSION_ID=
> 
> A lower-case string (mostly numeric, no spaces or other characters outside of 0–9, a–z, ".", "_" and "-") 

Mostly numeric is not numeric.

**Comment by danmosemsft** [comment]
Confirmed no failures since the fix
