### ISSUE TITLE
Test failure: Microsoft.CSharp.RuntimeBinder.Tests.ArrayHandling/ArrayTypeNames 

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#38442]
Test `Microsoft.CSharp.RuntimeBinder.Tests.ArrayHandling/ArrayTypeNames ` has failed.

Message :
```
System.TypeInitializationException : The type initializer for 'System.PlatformDetection' threw an exception.
---- System.FormatException : Input string was not in a correct format.
```

Stack Trace :
```
  at System.PlatformDetection.get_IsNonZeroLowerBoundArraySupported() in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.cs:line 120
   at Microsoft.CSharp.RuntimeBinder.Tests.ArrayHandling.ArrayTypeNames() in /_/src/Microsoft.CSharp/tests/ArrayHandling.cs:line 32
----- Inner Stack Trace -----
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type) in /_/src/System.Private.CoreLib/shared/System/Number.Parsing.cs:line 1931
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info) in /_/src/System.Private.CoreLib/shared/System/Number.Parsing.cs:line 216
   at System.Int32.Parse(String s) in /_/src/System.Private.CoreLib/shared/System/Int32.cs:line 107
   at System.PlatformDetection.ToVersion(String versionString) in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 165
   at System.PlatformDetection..cctor() in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 84
```

Build: -[20190610.76](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190610.76)(Master)

Failing configurations:

- Debian.10.Amd64.Open-x64-Release

Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190610.76/workItem/Microsoft.CSharp.Tests/analysis/xunit/Microsoft.CSharp.RuntimeBinder.Tests.ArrayHandling~2FArrayTypeNames

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/38443 (different failing test, but they both stem from the same PlatformDetection.ToVersion exception on Debian).
