### ISSUE TITLE
GoAwayFrame_NoPendingStreams_ConnectionClosed failing with ObjectDisposedException

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#38481]
From https://github.com/dotnet/corefx/pull/38306

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38306~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190612.4/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FGoAwayFrame_NoPendingStreams_ConnectionClosed

System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2/GoAwayFrame_NoPendingStreams_ConnectionClosed
Ubuntu.1604.Amd64.Open-x64-Release
```text
Unhandled Exception of Type System.Net.Http.HttpRequestException
Message :
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'CreditManager'.
Stack Trace :
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 1447
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 539
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 33
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in /_/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 521
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<>c__DisplayClass38_0.<<EstablishConnectionAndProcessOneRequestAsync>b__0>d.MoveNext() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 706
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 77
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.EstablishConnectionAndProcessOneRequestAsync(HttpClient client, Http2LoopbackServer server) in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 720
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.GoAwayFrame_NoPendingStreams_ConnectionClosed() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 740
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.CreditManager.RequestCreditAsync(Int32 amount, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/CreditManager.cs:line 75
   at System.Net.Http.Http2Connection.SendHeadersAsync(HttpRequestMessage request, CancellationToken cancellationToken, Boolean mustFlush) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 970
   at System.Threading.Tasks.ValueTask`1.get_Result() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/ValueTask.cs:line 763
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 1368
```

**Comment by stephentoub** [comment]
Another, on Fedora:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38476~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190612.15/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FGoAwayFrame_NoPendingStreams_ConnectionClosed
```
Unhandled Exception of Type System.Net.Http.HttpRequestException
Message :
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'CreditManager'.
Stack Trace :
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 1447
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 539
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 33
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in /_/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 521
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<>c__DisplayClass38_0.<<EstablishConnectionAndProcessOneRequestAsync>b__0>d.MoveNext() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 706
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 77
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.EstablishConnectionAndProcessOneRequestAsync(HttpClient client, Http2LoopbackServer server) in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 720
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.GoAwayFrame_NoPendingStreams_ConnectionClosed() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 740
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.CreditManager.RequestCreditAsync(Int32 amount, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/CreditManager.cs:line 75
   at System.Net.Http.Http2Connection.SendHeadersAsync(HttpRequestMessage request, CancellationToken cancellationToken, Boolean mustFlush) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 970
   at System.Threading.Tasks.ValueTask`1.get_Result() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/ValueTask.cs:line 763
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 1368
```

**Comment by safern** [comment]
Another on Alpine3.9: https://dev.azure.com/dnceng/public/_build/results?buildId=224245&view=ms.vss-test-web.build-test-results-tab&runId=5522090&resultId=436613&paneView=debug

**Comment by stephentoub** [comment]
Again:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38539~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190614.7/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FGoAwayFrame_NoPendingStreams_ConnectionClosed

**Comment by krwq** [comment]
@scalablecory I think this might be somewhat related to https://github.com/dotnet/corefx/issues/38558#issuecomment-502755544

I think GoAway should not mark connection as _disposed and instead there should be another flag telling it is terminating the connection (otherwise certain actions cause ObjectDisposedException). Note: this might be a different issue what I just described

**Comment by stephentoub** [comment]
Again
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38636~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190618.7/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FGoAwayFrame_NoPendingStreams_ConnectionClosed

**Comment by Gnbrkm41** [comment]
Happened again: https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38690~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190619.25/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FGoAwayFrame_NoPendingStreams_ConnectionClosed

**Comment by qmfrederik** [comment]
One more: https://github.com/dotnet/corefx/pull/38774/checks?check_run_id=153693227

**Comment by stephentoub** [comment]
Closing in hopes it was addressed by https://github.com/dotnet/corefx/pull/38226.  If not we'll reopen.
