### ISSUE TITLE
Debug.Fail crashes .netcoreapp2.x and 3.0 processes

### ISSUE THREAD

**Issue by AArnott** [dotnet/corefx#38497]
Create an xunit csproj test project with these targets:
```xml
 <TargetFrameworks>netcoreapp1.0;netcoreapp2.0;netcoreapp2.1;netcoreapp2.2;netcoreapp3.0</TargetFrameworks>
```

Define the following test method:
```cs
[Fact]
public void CatchTest()
{
    try
    {
        System.Diagnostics.Debug.Fail("just a test");
    }
    catch
    {
    }
}
```

Run the tests using `dotnet test` or Test Explorer.

**Expected**

All tests pass

**Actual**

The test passes on .netcoreapp1.0, but *crashes the process* for .netcoreapp2.0, 2.1, 2.2, and 3.0.

See repro project: [XUnitTestProject1.zip](https://github.com/dotnet/corefx/files/3284264/XUnitTestProject1.zip)

```
[6/12/2019 10:53:08.062 PM Error] The active test run was aborted. Reason: Test host process crashed : FailFast: just a test
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at XUnitTestProject1.UnitTest1.CatchTest() in C:\Users\andarno\source\repos\XUnitTestProject1\XUnitTestProject1\UnitTest1.cs:line 13
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 150
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 257
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<InvokeTestMethodAsync>b__1()
   at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction)
   at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext() in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code)
   at Xunit.Sdk.TestInvoker`1.<InvokeTestMethodAsync>d__48.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 239
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance)
   at Xunit.Sdk.TestInvoker`1.<<RunAsync>b__47_0>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 206
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.TestInvoker`1.<RunAsync>b__47_0()
   at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext() in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 107
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
   at Xunit.Sdk.XunitTestRunner.<InvokeTestAsync>d__4.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestRunner.cs:line 67
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator)
   at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
   at Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.TestRunner`1.RunAsync()
   at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestCaseRunner.cs:line 82
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.TestCaseRunner`1.RunAsync()
   at Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestMethodRunner.cs:line 45
   at Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestMethodRunner.cs:line 136
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()
   at Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestMethodRunner.cs:line 106
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.TestMethodRunner`1.RunAsync()
   at Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__38.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestClassRunner.cs:line 213
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()
   at Xunit.Sdk.TestClassRunner`1.<RunAsync>d__37.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestClassRunner.cs:line 171
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.TestClassRunner`1.RunAsync()
   at Xunit.Sdk.TestCollectionRunner`1.<RunTestClassesAsync>d__28.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestCollectionRunner.cs:line 130
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()
   at Xunit.Sdk.TestCollectionRunner`1.<RunAsync>d__27.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestCollectionRunner.cs:line 101
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.TestCollectionRunner`1.RunAsync()
   at Xunit.Sdk.XunitTestAssemblyRunner.<>c__DisplayClass14_2.<RunTestCollectionsAsync>b__2() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestAssemblyRunner.cs:line 184
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at System.Threading.Tasks.SynchronizationContextTaskScheduler.<>c.<.cctor>b__8_0(Object s)
   at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs:line 107
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs:line 89
   at System.Threading.Thread.ThreadMain_ParameterizedThreadStart(Object parameter)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Environment.FailFast(System.String, System.Exception)
   at XUnitTestProject1.UnitTest1.CatchTest()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at Xunit.Sdk.TestInvoker`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CallTestMethod(System.Object)
   at Xunit.Sdk.TestInvoker`1+<>c__DisplayClass48_1+<<InvokeTestMethodAsync>b__1>d[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Xunit.Sdk.TestInvoker`1+<>c__DisplayClass48_1+<<InvokeTestMethodAsync>b__1>d[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.4.0.4049, Cu
```

What's odd to me is that the output suggests an exception is thrown (which Debug.Fail isn't expected to do) and I try to catch all exceptions and fail to. So this must be a native exception or something. The exception type isn't printed for the crash so I can't see what it was.

**Comment by stephentoub** [comment]
> What's odd to me is that the output suggests an exception is thrown (which Debug.Fail isn't expected to do) and I try to catch all exceptions and fail to. So this must be a native exception or something. The exception type isn't printed for the crash so I can't see what it was.

It's Environment.FailFast.

In .NET Core 1.0, it actually did throw an exception, which as you say was unexpected. That was fixed to fall fast, the same as in netfx.

**Comment by AArnott** [comment]
> That was fixed to fail fast, the same as in netfx.

But Netfx doesn't crash in this scenario. It only crashes if the assert dialog appears and the user clicks Abort, I think.
In netcore2+, it's crashing immediately without a dialog.

Folks have used Debug.Assert for "soft" warnings and debugger launch/break assistants on Netfx for years. But netcoreapp2.1 seems to crash immediately without a VS debugger even being given a chance to attach or break. Why change a fairly benign API to one that is equivalent to FailFast?

In Netfx I would write tests that suppressed the assertion dialog and intercepted Debug.Assert fails via TraceListener so that I could fail tests if any Debug.Assert failed, and without hanging test runs with popup UI. But netcore's behavior literally crashes the test runner so that no further tests run and the one that was running isn't even reported as having failed or run in Test Explorer.

**Comment by stephentoub** [comment]
> Folks have used Debug.Assert for "soft" warnings and debugger launch/break assistants on Netfx for years.

A GUI dialog is tracked by https://github.com/dotnet/coreclr/issues/20973.

> intercepted Debug.Assert fails via TraceListener so that I could fail tests if any Debug.Assert failed

You can do that in .NET Core 3.0, e.g.
```C#
using System;
using System.Diagnostics;

class Program
{
    static void Main()
    {
        Trace.Listeners.Clear();
        Trace.Listeners.Add(new ThrowingListener());

        try
        {
            Debug.Assert(false, "my assert");
        }
        catch (Exception e)
        {
            Console.WriteLine("Caught exception " + e.Message);
        }

        Console.WriteLine("after catch");
    }

    class ThrowingListener : TraceListener
    {
        public override void Fail(string message, string detailMessage) => throw new Exception(message + ". " + detailMessage);
        public override void Write(string message) { }
        public override void WriteLine(string message) { }
    }
}
```
prints out:
```
Caught exception my assert.
after catch
```

cc: @danmosemsft, @maryamariyan, @jkotas

**Comment by AArnott** [comment]
Ooh, does that mean #16596 is fixed in .NET Core 3.0? Perhaps the issue should be re-resolved as such. That's great news!

**Comment by stephentoub** [comment]
> Ooh, does that mean #16596 is fixed in .NET Core 3.0?

Yes.  On .NET Core 3.0 that example outputs:
```
Our listener got: Traced message
Our listener got: Debug message
```

**Comment by simendsjo** [comment]
I'm having a similar issue, but when calling `System.Diagnostics.Debugger.Break()`. Locally everything works both when debugging and in Release. On the build-server (TeamCity), the testrunner crashes without a message `The active test run was aborted. Reason: Test host process crashed`. Found a workaround wrapping the call in `#if DEBUG`.

Is this somehow the same issue, or should I file a new issue?

This is using dotnet 2.2.401.

**Comment by simendsjo** [comment]
> (...)
> Is this somehow the same issue, or should I file a new issue?
> (...)

Should I file a new issue for this?

**Comment by danmosemsft** [comment]
@maryamariyan ?

**Comment by maryamariyan** [comment]
looking..

**Comment by maryamariyan** [comment]
> Is this somehow the same issue, or should I file a new issue?

yes, your issue seems unrelated to this one. The code path for Debugger.Break (which you are hitting) does not coincide with Debug.Fail. I'll close current issue as resolved, based on the conversations prior to yours.

@simendsjo could you please open a new issue on dotnet/runtime? It would be good if you could share a small code snippet that reproduces your error.

**Comment by danmosemsft** [comment]
@simendsjo note that 2.2 will go out of support in 3 weeks or so: https://github.com/dotnet/core/blob/master/microsoft-support.md

Can you please re-test with .NET Core 3.0? It is released, stable and supported and as mentioned above you will very soon need to upgrade to 3.0 or 3.1 (3.1 will release in a couple weeks or so).

**Comment by simendsjo** [comment]
> Can you please re-test with .NET Core 3.0? It is released, stable and supported and as mentioned above you will very soon need to upgrade to 3.0 or 3.1 (3.1 will release in a couple weeks or so).

I tested with 3.1, and it works, thanks! Since 2.2 isn't supported, I won't bother to add a new issue for this.
