### ISSUE TITLE
GetAsync_CancelDuringResponseBodyReceived_Unbuffered_TaskCanceledQuickly failing in UWP

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#38547]
I've seen this failure now twice today, e.g.
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38539~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190614.7/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Cancellation_Test~2FGetAsync_CancelDuringResponseBodyReceived_Unbuffered_TaskCanceledQuickly(chunkedTransfer:%20False,%20connectionClose:%20False,%20readOrCopyToAsync:%20False)
```
Windows.10.Amd64.ClientRS5.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Expected cancellation exception, got:
System.IO.IOException: The handle is invalid. (0x80070006 (E_HANDLE)) ---> System.Exception: The handle is invalid. (0x80070006 (E_HANDLE))
   at Windows.Storage.Streams.IInputStream.ReadAsync(IBuffer buffer, UInt32 count, InputStreamOptions options)
   at System.IO.WinRtToNetFxStreamAdapter.ReadAsyncInternal(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in /_/src/System.Runtime.WindowsRuntime/src/System/IO/WinRtToNetFxStreamAdapter.cs:line 799
   --- End of inner exception stack trace ---
   at System.IO.WinRtToNetFxStreamAdapter.ReadAsyncInternal(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in /_/src/System.Runtime.WindowsRuntime/src/System/IO/WinRtToNetFxStreamAdapter.cs:line 822
   at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken) in /_/src/System.Private.CoreLib/shared/System/IO/Stream.cs:line 140
   at System.IO.BufferedStream.CopyToAsyncCore(Stream destination, Int32 bufferSize, CancellationToken cancellationToken) in /_/src/System.Runtime.Extensions/src/System/IO/BufferedStream.cs:line 1361
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.<>c__DisplayClass4_3.<<GetAsync_CancelDuringResponseBodyReceived_Unbuffered_TaskCanceledQuickly>b__2>d.MoveNext() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 199
--- End of stack trace from previous location where exception was thrown ---
   at Xunit.Record.ExceptionAsync(Func`1 testCode) in C:\\projects\\xunit\\src\\xunit.core\\Record.cs:line 77
Expected: True
Actual:   False
Stack Trace :
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.ValidateClientCancellationAsync(Func`1 clientBodyAsync) in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 408
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.<>c__DisplayClass4_2.<<GetAsync_CancelDuringResponseBodyReceived_Unbuffered_TaskCanceledQuickly>b__0>d.MoveNext() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 191
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 66
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.GetAsync_CancelDuringResponseBodyReceived_Unbuffered_TaskCanceledQuickly(Boolean chunkedTransfer, Boolean connectionClose, Boolean readOrCopyToAsync) in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by ViktorHofer** [comment]
Failed again in a rolling build: https://dnceng.visualstudio.com/public/_build/results?buildId=340892&view=ms.vss-test-web.build-test-results-tab&runId=10081520&resultId=142066&paneView=debug

```
Expected cancellation exception, got:\r\nSystem.IO.IOException: The handle is invalid. (0x80070006 (E_HANDLE))\r\n ---> System.Exception: The handle is invalid. (0x80070006 (E_HANDLE))\r\n at Windows.Storage.Streams.IInputStream.ReadAsync(IBuffer buffer, UInt32 count, InputStreamOptions options)\r\n at System.IO.WinRtToNetFxStreamAdapter.ReadAsyncInternal(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in /_/src/System.Runtime.WindowsRuntime/src/System/IO/WinRtToNetFxStreamAdapter.cs:line 799\r\n --- End of inner exception stack trace ---\r\n at System.IO.WinRtToNetFxStreamAdapter.ReadAsyncInternal(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in /_/src/System.Runtime.WindowsRuntime/src/System/IO/WinRtToNetFxStreamAdapter.cs:line 822\r\n at System.IO.BufferedStream.ReadFromUnderlyingStreamAsync(Memory`1 buffer, CancellationToken cancellationToken, Int32 bytesAlreadySatisfied, Task semaphoreLockTask) in /_/src/System.Runtime.Extensions/src/System/IO/BufferedStream.cs:line 762\r\n at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.<>c__DisplayClass4_1.<<GetAsync_CancelDuringResponseBodyReceived_Unbuffered_TaskCanceledQuickly>b__2>d.MoveNext() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 215\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at Xunit.Record.ExceptionAsync(Func`1 testCode) in C:\\Dev\\xunit\\xunit\\src\\xunit.core\\Record.cs:line 76\r\nExpected: True\r\nActual: False

 at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.ValidateClientCancellationAsync(Func`1 clientBodyAsync) in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 550
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.<>c__DisplayClass4_0.<<GetAsync_CancelDuringResponseBodyReceived_Unbuffered_TaskCanceledQuickly>b__0>d.MoveNext() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 66
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.GetAsync_CancelDuringResponseBodyReceived_Unbuffered_TaskCanceledQuickly(Boolean chunkedTransfer, Boolean connectionClose, Boolean readOrCopyToAsync) in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by ViktorHofer** [comment]
Will disable the test on UAP.

**Comment by davidsh** [comment]
Disabled on UAP with PR #40875
