### ISSUE TITLE
EventLogTraceListenerTests.WriteTest failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#38548]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38538~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190614.6/workItem/System.Diagnostics.EventLog.Tests/analysis/xunit/System.Diagnostics.Tests.EventLogTraceListenerTests~2FWriteTest
```
Windows.7.Amd64.Open-x86-Release
Get Repro environment
Unhandled Exception of Type System.ComponentModel.Win32Exception
Message :
System.ComponentModel.Win32Exception : Access is denied.
Stack Trace :
   at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventLogEntryType type, String[] strings, Byte[] rawData, String currentMachineName) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs:line 1441
   at System.Diagnostics.EventLogInternal.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category, Byte[] rawData) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs:line 1359
   at System.Diagnostics.EventLog.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category, Byte[] rawData) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 993
   at System.Diagnostics.EventLog.WriteEntry(String message) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 945
   at System.Diagnostics.EventLogTraceListener.Write(String message) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogTraceListener.cs:line 77
   at System.Diagnostics.Tests.EventLogTraceListenerTests.WriteTest() in /_/src/System.Diagnostics.EventLog/tests/EventLogTraceListenerTests.cs:line 101
```

**Comment by JeremyKuhne** [comment]
[Again](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39468~2Fmerge/test~2Ffunctional~2Fcli~2F~2F/20190715.81/workItem/System.Diagnostics.EventLog.Tests/analysis/xunit/System.Diagnostics.Tests.EventLogTraceListenerTests~2FWriteTest)

```
Windows.7.Amd64.Open-x86-Release
Get Repro environment
Unhandled Exception of Type System.ComponentModel.Win32Exception
Message :
System.ComponentModel.Win32Exception : Access is denied.
Stack Trace :
   at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventLogEntryType type, String[] strings, Byte[] rawData, String currentMachineName) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs:line 1441
   at System.Diagnostics.EventLogInternal.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category, Byte[] rawData) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs:line 1359
   at System.Diagnostics.EventLog.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category, Byte[] rawData) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 1000
   at System.Diagnostics.EventLog.WriteEntry(String message) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 952
   at System.Diagnostics.EventLogTraceListener.Write(String message) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogTraceListener.cs:line 77
   at System.Diagnostics.Tests.EventLogTraceListenerTests.WriteTest() in /_/src/System.Diagnostics.EventLog/tests/EventLogTraceListenerTests.cs:line 101
```

**Comment by danmosemsft** [comment]
Always Win7.

**Comment by ViktorHofer** [comment]
Failed on Windows 10 19H1: https://dnceng.visualstudio.com/public/_build/results?buildId=379390&view=ms.vss-test-web.build-test-results-tab&runId=11701594&resultId=165080&paneView=debug

**Comment by ViktorHofer** [comment]
Retries seem to not help at all. Should we disable the all tests that invoke `EventLog.Delete` on Windows 19H1 upwards?
