### ISSUE TITLE
[System.Text.Json] Dictionary ordering with nulls bug

### ISSUE THREAD

**Issue by IvanJosipovic** [dotnet/corefx#38557]
There appears to be bug in System.Text.Json related to property ordering, IgnoreNullValues and Dictionary.

.Net Core: 3.0.100-preview6-012264
System.Text.Json: 4.6.0-preview6.19303.8

Running the code below will throw an exception:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Text.Json.Serialization.JsonSerializer.ApplyValueToEnumerable[TProperty](TProperty& value, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.JsonPropertyInfoNotNullable`3.ReadEnumerable(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.JsonPropertyInfoNotNullable`3.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.JsonSerializer.HandleValue(JsonTokenType tokenType, JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.Serialization.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializer.Parse[TValue](String json, JsonSerializerOptions options)
   at ConsoleApp1.SystemExtension.Clone[T](T source) in C:\Repos\ConsoleApp1\ConsoleApp1\Program.cs:line 10
   at ConsoleApp1.Program.Main(String[] args) in C:\Repos\ConsoleApp1\ConsoleApp1\Program.cs:line 24
```

```
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ConsoleApp1
{
    public static class SystemExtension
    {
        public static T Clone<T>(this T source)
        {
            return JsonSerializer.Parse<T>(JsonSerializer.ToString(source, new JsonSerializerOptions { IgnoreNullValues = true }));
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            new GoodOrder()
            {
                Test = "value1"
            }
            .Clone();

            new BadOrder()
            {
                Test = "value1"
            }
            .Clone(); // Throws exception!
        }

        public class GoodOrder
        {
            public string Test { get; set; }
            public Dictionary<string, string> Dict { get; set; }
        }

        public class BadOrder
        {
            public Dictionary<string, string> Dict { get; set; }
            public string Test { get; set; }
        }
    }
}

```

**Comment by ahsonkhan** [comment]
That's a good catch, @IvanJosipovic. Thanks for finding the issue.

Looks like the state is not getting constructed correctly. When processing the property name for "string Test", `state.Current.IsProcessingDictionary` is still set to true which I don't think should be.
https://github.com/dotnet/corefx/blob/1fca079ddec2aabf56e256dab03e39b31b5036c7/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.HandlePropertyName.cs#L26

cc @steveharter, @layomia
