### ISSUE TITLE
DataSet.ReadXmlSchema throws XmlSchemaException

### ISSUE THREAD

**Issue by abjbhat** [dotnet/corefx#38582]
## Problem description:

`System.Data.DataSet.ReadXmlSchema` cannot read a data set schema written by `System.Data.DataSet.ReadXmlSchema`. Doing so results in a 
`System.Xml.Schema.XmlSchemaException` being thrown.

## Steps to reproduce:

1. Create a new `System.Data.DataSet`. 
1.1 Add two `System.Data.DataTable` T1 and T2 to this `DataSet`. 
1.2 Add a relationship between T1 and T2. 
1.3 Save changes to the `DataSet`
2. Write the schema using `System.Data.DataSet.WriteXmlSchema(String)` . This overload expects a string parameter, which is a name of a file. 
3. Try to read the schema just created to create a new `System.Data.DataSet` using `System.Data.DataSet.WriteXmlSchema(String)` by passing the same filename.
4. An exception is thrown.
```csharp
System.Xml.Schema.XmlSchemaException
  HResult=0x80131941
  Message=The 'dbo:T1' element is not declared.
  Source=System.Private.Xml
  StackTrace:
   at System.Xml.Schema.XmlSchemaSet.InternalValidationCallback(Object sender, ValidationEventArgs e)
   at System.Xml.Schema.BaseProcessor.SendValidationEvent(XmlSchemaException e, XmlSeverityType severity)
   at System.Xml.Schema.BaseProcessor.SendValidationEvent(XmlSchemaException e)
   at System.Xml.Schema.Compiler.CompileElement(XmlSchemaElement xe)
   at System.Xml.Schema.Compiler.CompileParticleElements(XmlSchemaComplexType complexType, XmlSchemaParticle particle)
   at System.Xml.Schema.Compiler.CompileParticleElements(XmlSchemaComplexType complexType, XmlSchemaParticle particle)
   at System.Xml.Schema.Compiler.CompileComplexTypeElements(XmlSchemaComplexType complexType)
   at System.Xml.Schema.Compiler.Compile()
   at System.Xml.Schema.Compiler.Execute(XmlSchemaSet schemaSet, SchemaInfo schemaCompiledInfo)
   at System.Xml.Schema.XmlSchemaSet.Compile()
   at System.Data.DataSet.ReadXSDSchema(XmlReader reader, Boolean denyResolving)
   at System.Data.DataSet.ReadXmlSchema(XmlReader reader, Boolean denyResolving)
   at System.Data.DataSet.ReadXmlSchema(String fileName)
``` 

This problem can be seen in dotnet core sdk version 2.2.300 on Windows 10 64 bit

### Possibly related issues: #20263

**Comment by abjbhat** [comment]
Attaching the XSD files generated by `System.Data.DataSet.WriteXmlSchema(String)`



[schema.zip](https://github.com/dotnet/corefx/files/3293806/schema.zip)

**Comment by abjbhat** [comment]
Update: Changed the description of the issue.

If the tables have a namespace set, the exception mentioned is thrown. If the namespace is removed, the dataset can be created without any problems.

**Comment by krwq** [comment]
@abjbhat I'm marking this as Future but we can consider taking a fix for 3.0 if you're willing to send a PR.

Having a quick look at this, presumably `dbo` namespace alias is defined somewhere (namespace manager or document)?
