### ISSUE TITLE
Test PlatformDetection cctor fails on Debian 10

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#38606]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190617.8/workItem/System.Security.Cryptography.Encoding.Tests/analysis/xunit/System.Security.Cryptography.Encoding.Tests.AsnEncodedDataCollectionTests~2FCopyExceptions

```
System.TypeInitializationException : The type initializer for 'System.PlatformDetection' threw an exception.
---- System.FormatException : Failed to parse version string: ''
-------- System.FormatException : Input string was not in a correct format.
   at System.PlatformDetection.get_IsNonZeroLowerBoundArraySupported() in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.cs:line 111
   at System.Security.Cryptography.Encoding.Tests.AsnEncodedDataCollectionTests.CopyExceptions() in /_/src/System.Security.Cryptography.Encoding/tests/AsnEncodedDataCollectionTests.cs:line 127
----- Inner Stack Trace -----
   at System.PlatformDetection.ToVersion(String versionString) in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 171
   at System.PlatformDetection..cctor() in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 84
----- Inner Stack Trace -----
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type) in /_/src/System.Private.CoreLib/shared/System/Number.Parsing.cs:line 1931
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info) in /_/src/System.Private.CoreLib/shared/System/Number.Parsing.cs:line 219
   at System.Int32.Parse(String s) in /_/src/System.Private.CoreLib/shared/System/Int32.cs:line 107
   at System.PlatformDetection.ToVersion(String versionString) in /_/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 167
```

Presumably it's poorly matching the distro version.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/38443
