### ISSUE TITLE
JsonSerializer throws TypeLoadException in Parse<T> call

### ISSUE THREAD

**Issue by martincostello** [dotnet/corefx#38643]
Using 3.0.100-preview6-012264 of the .NET Core 3.0 SDK, when trying to serialize an object that contains property that is an `IDictionary<string, T>`, then the following exception is thrown:

```
System.ArgumentException : GenericArguments[2], 'System.Collections.Generic.Dictionary`2[System.String,System.String]', on 'System.Text.Json.Serialization.JsonPropertyInfoNotNullable`3[TClass,TDeclaredProperty,TRuntimeProperty]' violates the constraint of type 'TRuntimeProperty'.
---- System.TypeLoadException : GenericArguments[2], 'System.Collections.Generic.Dictionary`2[System.String,System.String]', on 'System.Text.Json.Serialization.JsonPropertyInfoNotNullable`3[TClass,TDeclaredProperty,TRuntimeProperty]' violates the constraint of type parameter 'TRuntimeProperty'.
Stack Trace:
     at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
     at System.RuntimeType.MakeGenericType(Type[] instantiation)
     at System.Text.Json.Serialization.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonSerializerOptions options)
     at System.Text.Json.Serialization.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
     at System.Text.Json.Serialization.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
     at System.Text.Json.Serialization.JsonSerializerOptions.GetOrAddClass(Type classType)
     at System.Text.Json.Serialization.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
     at System.Text.Json.Serialization.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
     at System.Text.Json.Serialization.JsonSerializer.Parse[TValue](String json, JsonSerializerOptions options)

```

This issue was found while testing out the new System.Text.Json APIs with an existing production application when trying to serialize and deserialize objects containing dictionaries.

A unit test that demonstrates this issue and the comparable working JSON .NET behaviour is below:

```csharp
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using Xunit;
using JsonConvert = Newtonsoft.Json.JsonConvert;
using JsonSerializer = System.Text.Json.Serialization.JsonSerializer;

namespace JsonSerializerTypeLoadException
{
    public static class Repro
    {
        [Fact]
        public static void Can_Deserialize_Object_With_SystemTextJson()
        {
            // Arrange
            string json = "{\"Child\":{\"1\":{\"A\":\"1\",\"B\":\"\",\"C\":[],\"D\":[],\"E\":null,\"F\":[],\"G\":null,\"H\":null,\"I\":null,\"J\":null,\"K\":[]}}}";

            var actual = JsonSerializer.Parse<Parent>(json, new JsonSerializerOptions() { PropertyNamingPolicy = JsonNamingPolicy.CamelCase });

            // Assert
            Assert.NotNull(actual);
            Assert.NotNull(actual.Child);
            Assert.Equal(1, actual.Child.Count);
            Assert.True(actual.Child.ContainsKey("1"));
            Assert.Equal("1", actual.Child["1"].A);
        }

        [Fact]
        public static void Can_Deserialize_Object_With_NewtonsoftJson()
        {
            // Arrange
            string json = "{\"Child\":{\"1\":{\"A\":\"1\",\"B\":\"\",\"C\":[],\"D\":[],\"E\":null,\"F\":[],\"G\":null,\"H\":null,\"I\":null,\"J\":null,\"K\":[]}}}";

            var actual = JsonConvert.DeserializeObject<Parent>(json);

            // Assert
            Assert.NotNull(actual);
            Assert.NotNull(actual.Child);
            Assert.Equal(1, actual.Child.Count);
            Assert.True(actual.Child.ContainsKey("1"));
            Assert.Equal("1", actual.Child["1"].A);
        }

        public class Parent
        {
            public IDictionary<string, Child> Child { get; set; }
        }

        public class Child
        {
            public string A { get; set; }
            public string B { get; set; }
            public string[] C { get; set; }
            public string[] D { get; set; }
            public bool? E { get; set; }
            public string[] F { get; set; }
            public DateTimeOffset? G { get; set; }
            public DateTimeOffset? H { get; set; }
            public int? I { get; set; }
            public int? J { get; set; }
            public string[] K { get; set; }
        }
    }
}
```

**Comment by tannergooding** [comment]
This is failing because you specified `PropertyNamingPolicy = JsonNamingPolicy.CamelCase`, but the JSON input is Pascal cased.

**Comment by martincostello** [comment]
I don’t think that’s the entire story, as I found this issue trying to _write_ the JSON, but I found I could get the same exception from doing the reverse, so I filed the issue that way around as the in/out behaviour was easier to visualise for a repro.

**Comment by martincostello** [comment]
Repro for the serialization case:

```csharp
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using Xunit;
using JsonConvert = Newtonsoft.Json.JsonConvert;
using JsonSerializer = System.Text.Json.Serialization.JsonSerializer;

namespace JsonSerializerTypeLoadException
{
    public static class Repro
    {
        [Fact]
        public static void Can_Serialize_Object_With_SystemTextJson()
        {
            // Arrange
            var value = new Parent()
            {
                Child = new Dictionary<string, Child>()
                {
                    ["1"] = new Child()
                    {
                        A = "1",
                        B = string.Empty,
                        C = Array.Empty<string>(),
                        D = Array.Empty<string>(),
                        F = Array.Empty<string>(),
                        K = Array.Empty<string>(),
                    }
                }
            };

            var actual = JsonSerializer.ToString(value, new JsonSerializerOptions() { PropertyNamingPolicy = JsonNamingPolicy.CamelCase });

            // Assert
            Assert.NotNull(actual);
            Assert.NotEmpty(actual);
        }

        [Fact]
        public static void Can_Serialize_Object_With_NewtonsoftJson()
        {
            // Arrange
            var value = new Parent()
            {
                Child = new Dictionary<string, Child>()
                {
                    ["1"] = new Child()
                    {
                        A = "1",
                        B = string.Empty,
                        C = Array.Empty<string>(),
                        D = Array.Empty<string>(),
                        F = Array.Empty<string>(),
                        K = Array.Empty<string>(),
                    }
                }
            };

            var actual = JsonConvert.SerializeObject(
                value,
                new JsonSerializerSettings() { ContractResolver = new Newtonsoft.Json.Serialization.CamelCasePropertyNamesContractResolver() });

            // Assert
            Assert.NotNull(actual);
            Assert.NotEmpty(actual);
        }

        public class Parent
        {
            public IDictionary<string, Child> Child { get; set; }
        }

        public class Child
        {
            public string A { get; set; }
            public string B { get; set; }
            public string[] C { get; set; }
            public string[] D { get; set; }
            public bool? E { get; set; }
            public string[] F { get; set; }
            public DateTimeOffset? G { get; set; }
            public DateTimeOffset? H { get; set; }
            public int? I { get; set; }
            public int? J { get; set; }
            public string[] K { get; set; }
        }
    }
}
```

```
System.ArgumentException : GenericArguments[2], 'System.Collections.Generic.Dictionary`2[System.String,System.String]', on 'System.Text.Json.Serialization.JsonPropertyInfoNotNullable`3[TClass,TDeclaredProperty,TRuntimeProperty]' violates the constraint of type 'TRuntimeProperty'.
---- System.TypeLoadException : GenericArguments[2], 'System.Collections.Generic.Dictionary`2[System.String,System.String]', on 'System.Text.Json.Serialization.JsonPropertyInfoNotNullable`3[TClass,TDeclaredProperty,TRuntimeProperty]' violates the constraint of type parameter 'TRuntimeProperty'.

at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at System.Text.Json.Serialization.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.Serialization.WriteStackFrame.Initialize(Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializer.WriteCore(PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializer.WriteCoreString(Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializer.ToString[TValue](TValue value, JsonSerializerOptions options)
   at JsonSerializerTypeLoadException.Repro.Can_Serialize_Object_With_SystemTextJson() in C:\Coding\JsonSerializerBug\Repro.cs:line 33
----- Inner Stack Trace -----
   at System.RuntimeTypeHandle.Instantiate(Type[] inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
```

**Comment by tannergooding** [comment]
I'm not able to repro the latter case either.

I've added tests to validate this explicit payload here: https://github.com/dotnet/corefx/pull/38696.
-- I made one change to the deserialization case, which was to make the `json` payload `camelCase` to match the expectation from the `JsonSerializerOptions`.

**Comment by martincostello** [comment]
Ok cool. I’ll be retesting the app when preview 7 lands.
