### ISSUE TITLE
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.InboundWindowSize_Exceeded_Throw failing on CI

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#38708]
> System.Net.Http.HttpRequestException : An error occurred while sending the request.\n---- System.Net.Http.Http2ProtocolException : The HTTP/2 request failed with protocol error 'FLOW_CONTROL_ERROR' (0x3).

```
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 1449
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 539
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 33
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in /_/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 528
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<>c__DisplayClass56_0.<<InboundWindowSize_Exceeded_Throw>b__0>d.MoveNext() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1576
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 71
   at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Int32 timeout) in /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 728
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.InboundWindowSize_Exceeded_Throw() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1572
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.Http2Connection.Http2Stream.OnResponseData(ReadOnlySpan`1 buffer, Boolean endStream) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs:line 365
   at System.Net.Http.Http2Connection.ProcessDataFrame(FrameHeader frameHeader) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 401
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync() in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 227
```

Failed on: https://github.com/dotnet/corefx/pull/38288

@scalablecory @krwq it seems this test was added today and then modified in: https://github.com/dotnet/corefx/pull/38561

cc: @ViktorHofer @stephentoub

**Comment by ahsonkhan** [comment]
Failed again: https://github.com/dotnet/corefx/pull/38566

System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2/InboundWindowSize_Exceeded_Throw
Windows.Nano.1803.Amd64.Open-x64-Debug

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38566~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190619.80/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FInboundWindowSize_Exceeded_Throw

```text
Unhandled Exception of Type System.Net.Http.HttpRequestException
Message :
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.Http2ProtocolException : The HTTP/2 request failed with protocol error 'FLOW_CONTROL_ERROR' (0x3).
Stack Trace :
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 1449
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 539
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 33
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in /_/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 528
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<>c__DisplayClass57_0.<<InboundWindowSize_Exceeded_Throw>b__0>d.MoveNext() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1609
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 71
   at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Int32 timeout) in /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 178
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.InboundWindowSize_Exceeded_Throw() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1605
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.Http2Connection.Http2Stream.OnResponseData(ReadOnlySpan`1 buffer, Boolean endStream) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs:line 365
   at System.Net.Http.Http2Connection.ProcessDataFrame(FrameHeader frameHeader) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 401
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync() in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 227
```

**Comment by AriNuer** [comment]
Failed again:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190619.88/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FInboundWindowSize_Exceeded_Throw

**Comment by MarcoRossignoli** [comment]
Also here https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38654~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190619.83/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FInboundWindowSize_Exceeded_Throw

**Comment by ericstj** [comment]
Failed in rolling build. https://dev.azure.com/dnceng/public/_build/results?buildId=231796

@krwq and @corivera can you please have a look.  It seems this is related to your changes.
https://github.com/dotnet/corefx/commit/3863ec17c8ea61e72ef2240f23e4518788a2e8ae
https://github.com/dotnet/corefx/commit/290a6e54a482ee950c4b812ad85f8de2d795932f

Please address this ASAP as it seems to be impacting CI.  Perhaps we should disable this test until it can be fixed.

**Comment by ViktorHofer** [comment]
No that one is my fault and will be fixed with https://github.com/dotnet/corefx/pull/38707

**Comment by ericstj** [comment]
That rolling build also has test failures @ViktorHofer https://dev.azure.com/dnceng/public/_build/results?buildId=231796&view=ms.vss-test-web.build-test-results-tab

I've put up a PR to disable this test. https://github.com/dotnet/corefx/pull/38722
