### ISSUE TITLE
SocketsHttpHandlerTest_Http2 PostAsyncExpect100Continue_LateForbiddenResponse_Ok CI Failure

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#38734]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38728~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190620.20/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FPostAsyncExpect100Continue_LateForbiddenResponse_Ok

```
System.IO.IOException : Unable to read data from the transport connection: Broken pipe.
---- System.Net.Sockets.SocketException : Broken pipe
   at System.Net.Security.SslStream.<WriteSingleChunk>g__CompleteAsync|210_1[TWriteAdapter](ValueTask writeTask, Byte[] bufferToReturn) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 1271
   at System.Net.Security.SslStream.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 1521
   at System.Net.Test.Common.Http2LoopbackConnection.WriteFrameAsync(Frame frame) in /_/src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 86
   at System.Net.Test.Common.Http2LoopbackConnection.SendGoAway(Int32 lastStreamId) in /_/src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 540
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<>c__DisplayClass51_0.<<PostAsyncExpect100Continue_LateForbiddenResponse_Ok>b__1>d.MoveNext() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1436
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 71
   at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Int32 timeout) in /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 178
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.PostAsyncExpect100Continue_LateForbiddenResponse_Ok() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1403
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
```

Failures on
* Ubuntu.1604.Amd64.Open-x64-Debug
* Debian.9.Amd64.Open-x64-Debug
* RedHat.7.Amd64.Open-x64-Debug
* Centos.7.Amd64.Open-x64-Debug
* Alpine.39.Amd64.Open-x64-Debug
* RedHat.6.Amd64.Open-x64-Release

Hit by https://github.com/dotnet/corefx/pull/37486#issuecomment-503904613 and https://github.com/dotnet/corefx/pull/38728#issuecomment-504123521

**Comment by davidsh** [comment]
@wfurt @scalablecory @krwq

**Comment by krwq** [comment]
@tmds I believe this might be related to the recent changes in System.Net.Socket.

I got consistent repro when I'm on latest and no repro when I revert your recent change alone:
https://github.com/dotnet/corefx/commit/3fac6ad5bc4576eb2216ccb24fbed2bf173d41f4

I'm not familiar with that code, any chance you could chime in to help determine if this is something we might be doing wrong in Http2 which could have resurfaced after your change or is this a regression caused by your fix

**Comment by wfurt** [comment]
good to know @krwq . PostAsyncExpect100Continue_LateForbiddenResponse_Ok is test I wrote recently and it is possible that the socket change simply uncovered something.

**Comment by JeremyKuhne** [comment]
Another hit:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38740~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190620.43/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FPostAsyncExpect100Continue_LateForbiddenResponse_Ok

**Comment by krwq** [comment]
@tmds https://github.com/dotnet/corefx/commit/3fac6ad5bc4576eb2216ccb24fbed2bf173d41f4#diff-eee4543f13c4d6b0c1bd8bdb53281f7aR1875

I noticed we override this assignment 3 lines later - this seems like an issue in the code (might be unrelated to this issue)
