### ISSUE TITLE
behavior change with Socket sending reset

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#38765]
This is outcome of #37486. Even if that aimed to fix Synchronous blocking calls, it also impacts  Async operations:

let say there is simple receiver app:
```c#
using System;
using System.Net;
using System.Net.Sockets;

namespace Receiver
{
    class Program
    {
        static void Main(string[] args)
        {
            Socket l = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
            l.Bind(new IPEndPoint(IPAddress.Parse("127.0.0.1"), 8888));
            l.Listen(1);

            Socket s = l.Accept();
            Console.WriteLine("got socket!");

            byte[] buffer = new byte[1000];
            int rlen = 0;
            do {
                rlen = s.Receive(buffer, SocketFlags.None);
            }
            while (rlen > 0);

            Console.WriteLine("All done");
        }
    }
```
and then sender using Async IO.

```c# 
using System;
using System.Net;
using System.Net.Sockets;
using System.Threading.Tasks;


namespace dotnet_latest
{
    class Program
    {
        static async Task reader(Socket s)
        {
            byte[] buffer = new byte[1000];
            int readLength=0;
            do
            {
                readLength = await s.ReceiveAsync(buffer, SocketFlags.None);
                Console.WriteLine("Got {0} bytes", readLength);
            }
            while (readLength > 0);
            Console.WriteLine("Reader all done");
        }

        static void Main(string[] args)
        {
            Socket s= new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
            s.Connect(new IPEndPoint(IPAddress.Parse("127.0.0.1"), 8888));
            Task.Run(() => reader(s));

            Console.WriteLine("Hello World!");
            Console.ReadLine();
            s.Close();
        }
    }
}
```

before the change the receiver would simply finish after hitting enter on sending side. 

with the latest socket call it fails:
```
Unhandled exception. System.Net.Sockets.SocketException (104): Connection reset by peer
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, SocketFlags socketFlags)
   at Receiver.Program.Main(String[] args) in /home/furt/abcd/Program.cs:line 21
```

It seems like we send reset when we should not. 

![image](https://user-images.githubusercontent.com/14356188/59953387-ac36e600-9434-11e9-9b46-c6a7d7c06ee6.png)
 
cc: @tmds @davidsh @stephentoub

**Comment by wfurt** [comment]
cc: @krwq

**Comment by davidsh** [comment]
I submitted a PR (#38764) to revert PR #37486.  So, we can address this as part of the work to redo the PR in the future.

**Comment by tmds** [comment]
What does this do on Windows?

**Comment by wfurt** [comment]
this should be closed, right @tmds?

**Comment by tmds** [comment]
Yes, this can be closed.

**Comment by GSPP** [comment]
I'm pretty sure that `Shutdown` has network consequences but unsure which.

`Close` supports various modes through `LingerState` and maybe `SetSocketOption`. All of this could be affected.

Related: https://github.com/dotnet/corefx/issues/5749

**Comment by tmds** [comment]
@GSPP improvements were made in this PR: https://github.com/dotnet/corefx/issues/38804
