### ISSUE TITLE
Test failure:System.Diagnostics.Tests.EventLogTests/DeleteLog

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#38803]
Test `System.Diagnostics.Tests.EventLogTests/DeleteLog` has failed.

Message :
```
System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
```
Stack Trace :
```
   at System.Diagnostics.EventLogInternal.Clear() in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs:line 488
   at System.Diagnostics.EventLog.Clear() in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 227
   at System.Diagnostics.EventLog.Delete(String logName, String machineName) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 403
   at System.Diagnostics.EventLog.Delete(String logName) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 367
   at System.Diagnostics.Tests.EventLogTests.<>c__DisplayClass3_0.<DeleteLog>b__0() in /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogTests.cs:line 73
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<RetryOnWin7>b__0() in /_/src/System.Diagnostics.EventLog/tests/Helpers.cs:line 23
   at System.Diagnostics.Tests.Helpers.RetryOnWin7[T](Func`1 func) in /_/src/System.Diagnostics.EventLog/tests/Helpers.cs:line 30
   at System.Diagnostics.Tests.Helpers.RetryOnWin7(Action func) in /_/src/System.Diagnostics.EventLog/tests/Helpers.cs:line 23
   at System.Diagnostics.Tests.EventLogTests.DeleteLog() in /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogTests.cs:line 73
```
Build: -[20190623.30](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190623.30)(Master)

Failing configurations:

- Windows.10.Amd64.Client19H1.Open-x86-Release

Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190623.30/workItem/System.Diagnostics.EventLog.Tests/analysis/xunit/System.Diagnostics.Tests.EventLogTests~2FDeleteLog

**Comment by AriNuer** [comment]
Test `System.Diagnostics.Tests.EventLogTraceListenerTests.TraceEventFormatAndParams` failed with same exception:
```
Error message
System.ComponentModel.Win32Exception : A device attached to the system is not functioning.

Stack trace
   at System.Diagnostics.EventLogInternal.Clear() in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs:line 483
   at System.Diagnostics.EventLog.Clear() in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 227
   at System.Diagnostics.EventLog.Delete(String logName, String machineName) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 402
   at System.Diagnostics.EventLog.Delete(String logName) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 367
   at System.Diagnostics.Tests.EventLogTraceListenerTests.<>c__DisplayClass12_0.<TraceEventFormatAndParams>b__0() in /_/src/System.Diagnostics.EventLog/tests/EventLogTraceListenerTests.cs:line 248
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<RetryOnWin7>b__0() in /_/src/System.Diagnostics.EventLog/tests/Helpers.cs:line 23
   at System.Diagnostics.Tests.Helpers.RetryOnWin7[T](Func`1 func) in /_/src/System.Diagnostics.EventLog/tests/Helpers.cs:line 33
   at System.Diagnostics.Tests.Helpers.RetryOnWin7(Action func) in /_/src/System.Diagnostics.EventLog/tests/Helpers.cs:line 24
   at System.Diagnostics.Tests.EventLogTraceListenerTests.TraceEventFormatAndParams(String format, Object[] parameters) in /_/src/System.Diagnostics.EventLog/tests/EventLogTraceListenerTests.cs:line 250
```
Build: -[20190808.93](https://dnceng.visualstudio.com/public/_build/results?buildId=302066&view=ms.vss-test-web.build-test-results-tab&runId=8594272&resultId=150623&paneView=debug)(Master)

Details:
https://dnceng.visualstudio.com/public/_build/results?buildId=302066&view=ms.vss-test-web.build-test-results-tab&runId=8594272&resultId=150623&paneView=debug

**Comment by ViktorHofer** [comment]
System.Diagnostics.Tests.EventLogTraceListenerTests.TraceDataParamsData(parameters: [\"one string + null\", null]) failed again on `netcoreapp-Windows_NT-Release-x86-Windows.10.Amd64.Client19H1.Open`: https://dnceng.visualstudio.com/public/_build/results?buildId=334260&view=ms.vss-test-web.build-test-results-tab&runId=9828314&paneView=debug&resultId=152213

```
System.ComponentModel.Win32Exception : A device attached to the system is not functioning.

 at System.Diagnostics.EventLogInternal.Clear() in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs:line 479
   at System.Diagnostics.EventLog.Clear() in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 226
   at System.Diagnostics.EventLog.Delete(String logName, String machineName) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 402
   at System.Diagnostics.EventLog.Delete(String logName) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 366
   at System.Diagnostics.Tests.EventLogTraceListenerTests.<>c__DisplayClass10_0.<TraceDataParamsData>b__0() in /_/src/System.Diagnostics.EventLog/tests/EventLogTraceListenerTests.cs:line 177
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<RetryOnWin7>b__0() in /_/src/System.Diagnostics.EventLog/tests/Helpers.cs:line 23
   at System.Diagnostics.Tests.Helpers.RetryOnWin7[T](Func`1 func) in /_/src/System.Diagnostics.EventLog/tests/Helpers.cs:line 30
   at System.Diagnostics.Tests.Helpers.RetryOnWin7(Action func) in /_/src/System.Diagnostics.EventLog/tests/Helpers.cs:line 23
   at System.Diagnostics.Tests.EventLogTraceListenerTests.TraceDataParamsData(Object[] parameters) in /_/src/System.Diagnostics.EventLog/tests/EventLogTraceListenerTests.cs:line 177
```
