### ISSUE TITLE
Test failure:System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Cancellation_Test/GetAsync_CancelPendingRequests_DoesntCancelReadAsyncOnResponseStream(mode: CancelPendingRequests, copyToAsync: False)

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#38801]
Test `System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Cancellation_Test/GetAsync_CancelPendingRequests_DoesntCancelReadAsyncOnResponseStream(mode: CancelPendingRequests, copyToAsync: False)` has failed.

Message :
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Exception : Operation aborted (0x80004004 (E_ABORT))
```
Stack Trace :
```
  at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/uap/System/Net/HttpClientHandler.cs:line 616
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in /_/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 528
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.<>c__DisplayClass5_0.<<GetAsync_CancelPendingRequests_DoesntCancelReadAsyncOnResponseStream>b__0>d.MoveNext() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 277
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 66
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.GetAsync_CancelPendingRequests_DoesntCancelReadAsyncOnResponseStream(CancellationMode mode, Boolean copyToAsync) in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 247
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.HttpHandlerToFilter.SendAsync(HttpRequestMessage request, CancellationToken cancel) in /_/src/System.Net.Http/src/uap/System/Net/HttpHandlerToFilter.cs:line 90
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/uap/System/Net/HttpClientHandler.cs:line 607
```
Build: -[20190623.30](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190623.30)(Master)

Failing configurations:

- Windows.10.Amd64.ClientRS5.Open-x86-Release

Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190623.30/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Cancellation_Test~2FGetAsync_CancelPendingRequests_DoesntCancelReadAsyncOnResponseStream(mode:%20CancelPendingRequests,%20copyToAsync:%20False)

**Comment by davidsh** [comment]
>at System.Net.Http.HttpHandlerToFilter.SendAsync(HttpRequestMessage request, CancellationToken cancel) in /_/src/System.Net.Http/src/uap/System/Net/HttpHandlerToFilter.cs:line 90
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/uap/System/Net/HttpClientHandler.cs:line 607

This is from the UWP test run.
