### ISSUE TITLE
Http2_PendingSend_SendsReset Assert.NotNull failure

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#38820]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38810~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190624.10/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FHttp2_PendingSend_SendsReset

https://github.com/dotnet/corefx/blob/cad5159981f518f455be3528d0ee8eca2e00742a/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs#L1386
```
Unhandled Exception of Type Xunit.Sdk.NotNullException
Message :
Assert.NotNull() Failure
Stack Trace :
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<>c__DisplayClass50_0.<<Http2_PendingSend_SendsReset>b__1>d.MoveNext() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1386
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 71
   at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Int32 timeout) in /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 186
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.Http2_PendingSend_SendsReset() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1363
--- End of stack trace from previous location where exception was thrown ---
```
cc: @wfurt, @davidsh, @geoffkizer

**Comment by geoffkizer** [comment]
@wfurt related to your recent changes possibly?

**Comment by wfurt** [comment]
I'll take a look. This is new test I added recently @geoffkizer. There was similar test I updated to avoid issues with timing.

**Comment by ahsonkhan** [comment]
Failed again from https://github.com/dotnet/corefx/issues/38820

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38909~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190625.76/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FHttp2_PendingSend_SendsReset

Centos.7.Amd64.Open-x64-Debug
 System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2/Http2_PendingSend_SendsReset

```text
Unhandled Exception of Type Xunit.Sdk.NotNullException
Message :
Assert.NotNull() Failure
Stack Trace :
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<>c__DisplayClass50_0.<<Http2_PendingSend_SendsReset>b__1>d.MoveNext() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1387
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 71
   at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Int32 timeout) in /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 186
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.Http2_PendingSend_SendsReset() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1364
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by stephentoub** [comment]
Again here:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38936~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190626.49/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FHttp2_PendingSend_SendsReset

**Comment by stephentoub** [comment]
Again here:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38957~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190626.72/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FHttp2_PendingSend_SendsReset

**Comment by geoffkizer** [comment]
The test doesn't seem to be deterministic. It's using SlowTestStream, which will delay sending the body, but if the test runs slowly it will still be sent, and so the cancellation may not happen, no RST_STREAM is sent, assert fires.

Seems like we should use a custom content class that just doesn't send the body. Or sends a partial body and then stops. Or ideally both. I thought we had a class like this, but can't find it at the moment. The closest I can find is ByteAtATimeContent, which is used in PostAsync_CancelDuringRequestContentSend_TaskCanceledQuickly to effectively send a slow but infinite request body, which seems like a reasonable way to test this. @wfurt, can we just use that class instead of SlowTestStream here and elsewhere?

**Comment by stephentoub** [comment]
Again here:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39073~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190701.10/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FHttp2_PendingSend_SendsReset

I'm going to temporarily disable the test.
