### ISSUE TITLE
TestCheckChildProcessUserAndGroupIdsElevated failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#38833]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38817~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190624.2/workItem/System.Diagnostics.Process.Tests/wilogs
```
    System.Diagnostics.Tests.ProcessTests.TestCheckChildProcessUserAndGroupIdsElevated(useRootGroups: True) [FAIL]
      Assert.NotNull() Failure
      Stack Trace:
        /_/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs(640,0): at System.Diagnostics.Tests.ProcessTests.GetCurrentRealUserName()
        /_/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs(615,0): at System.Diagnostics.Tests.ProcessTests.TestCheckChildProcessUserAndGroupIdsElevated(Boolean useRootGroups)

    System.Diagnostics.Tests.ProcessTests.TestCheckChildProcessUserAndGroupIdsElevated(useRootGroups: False) [FAIL]
        /_/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs(640,0): at System.Diagnostics.Tests.ProcessTests.GetCurrentRealUserName()
        /_/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs(615,0): at System.Diagnostics.Tests.ProcessTests.TestCheckChildProcessUserAndGroupIdsElevated(Boolean useRootGroups)
```
cc: @tmds

**Comment by tmds** [comment]
I've hit this one too in CI. The issue is in this code:

https://github.com/dotnet/corefx/blob/de1da50fc5f972348aba2fa40ff14e1cbadb13de/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs#L634-L644

The most likely cause is the code is running as root, without sudo.

CC @wtgodbe

**Comment by wtgodbe** [comment]
Moving to future as it's a test-only bug - that said, I'll disable for now then fix it after the code merge.

**Comment by wtgodbe** [comment]
Might be related: https://github.com/dotnet/corefx/issues/35933

**Comment by wtgodbe** [comment]
> Maybe we should add some more assets to figure out why GetCurrentRealUserName returns null.
