### ISSUE TITLE
Connection_UnderDifferentUsers_BehavesAsExpected failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#38834]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38817~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190624.2/workItem/System.IO.Pipes.Tests/wilogs
```
System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.Connection_UnderDifferentUsers_BehavesAsExpected(serverPipeOptions: CurrentUserOnly, clientPipeOptions: None) [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.UnauthorizedAccessException)
      Actual:   (No exception was thrown)
      Stack Trace:
        /_/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CurrentUserOnly.netcoreapp.Unix.cs(46,0): at System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.Connection_UnderDifferentUsers_BehavesAsExpected(PipeOptions serverPipeOptions, PipeOptions clientPipeOptions)
        --- End of stack trace from previous location where exception was thrown ---
Unhandled exception. Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.UnauthorizedAccessException)
Actual:   (No exception was thrown)
   at Xunit.Assert.Throws(Type exceptionType, Exception exception) in C:\projects\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 147
   at Xunit.Assert.Throws[T](Action testCode) in C:\projects\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 27
   at System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.ConnectClientFromRemoteInvoker(String pipeName, String isCurrentUserOnly) in /_/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CurrentUserOnly.netcoreapp.Unix.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.RemoteExecutorHost.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutorHost/Program.cs:line 92
    System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.Connection_UnderDifferentUsers_BehavesAsExpected(serverPipeOptions: CurrentUserOnly, clientPipeOptions: CurrentUserOnly) [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.ThrowsException: Assert.Throws() Failure
        Expected: typeof(System.UnauthorizedAccessException)
        Actual:   (No exception was thrown)
        /_/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CurrentUserOnly.netcoreapp.Unix.cs(58,0): at System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.ConnectClientFromRemoteInvoker(String pipeName, String isCurrentUserOnly)
        
        Child process:
          System.IO.Pipes.Tests, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix Int32 ConnectClientFromRemoteInvoker(System.String, System.String)
        
        Child arguments:
          /tmp/dj2orw31.bwl, true
```

**Comment by danmosemsft** [comment]
Fedora.29.Amd64.Open-x64:Debug

**Comment by JeremyKuhne** [comment]
https://github.com/dotnet/corefx/blob/09f4f7ed59992bc7bff6fe42bc75ef5b08c8c4e2/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CurrentUserOnly.netcoreapp.Unix.cs#L26

**Comment by stephentoub** [comment]
Again here:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38804~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190701.1/workItem/System.IO.Pipes.Tests/wilogs
```
Fedora.29.Amd64.Open-x64:Debug
Details from Job 42cb28ae-b00c-4697-bb96-37c3d38a0247
ExitCode: 1
Ran on Machine: a000AQO
Get Repro environment
Console 
Executed on a000AQO using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-29-09ca40b-20190508143249
running $HELIX_CORRELATION_PAYLOAD/scripts/0412e0690da94523a4d8a2e917cc4309/execute.sh in /datadisks/disk1/work/42cb28ae-b00c-4697-bb96-37c3d38a0247/Work/569ad590-fec1-474f-a5fa-03f0349b0fb8/Exec max 900 seconds

Output:
[BEGIN EXECUTION]
+ ./RunTests.sh --runtime-path /root/helix/work/correlation
----- start Mon Jul 1 13:47:48 UTC 2019 =============== To repro directly: =====================================================
pushd .
/root/helix/work/correlation/dotnet xunit.console.dll System.IO.Pipes.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing 
popd
===========================================================================================================
~/helix/work/workitem ~/helix/work/workitem
  Discovering: System.IO.Pipes.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.IO.Pipes.Tests (found 25 of 462 test cases)
  Starting:    System.IO.Pipes.Tests (parallel test collections = on, max threads = 2)
Unhandled exception. Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.UnauthorizedAccessException)
Actual:   (No exception was thrown)
   at Xunit.Assert.Throws(Type exceptionType, Exception exception) in C:\projects\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 147
   at Xunit.Assert.Throws[T](Action testCode) in C:\projects\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 27
   at System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.ConnectClientFromRemoteInvoker(String pipeName, String isCurrentUserOnly) in /_/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CurrentUserOnly.netcoreapp.Unix.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.RemoteExecutorHost.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutorHost/Program.cs:line 92
    System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.Connection_UnderDifferentUsers_BehavesAsExpected(serverPipeOptions: None, clientPipeOptions: CurrentUserOnly) [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.ThrowsException: Assert.Throws() Failure
        Expected: typeof(System.UnauthorizedAccessException)
        Actual:   (No exception was thrown)
        /_/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CurrentUserOnly.netcoreapp.Unix.cs(58,0): at System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.ConnectClientFromRemoteInvoker(String pipeName, String isCurrentUserOnly)
        
        Child process:
          System.IO.Pipes.Tests, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix Int32 ConnectClientFromRemoteInvoker(System.String, System.String)
        
        Child arguments:
          /tmp/4yuxkhxe.wn0, true
        
    System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.Connection_UnderDifferentUsers_BehavesAsExpected(serverPipeOptions: CurrentUserOnly, clientPipeOptions: None) [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.UnauthorizedAccessException)
      Actual:   (No exception was thrown)
      Stack Trace:
        /_/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CurrentUserOnly.netcoreapp.Unix.cs(46,0): at System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.Connection_UnderDifferentUsers_BehavesAsExpected(PipeOptions serverPipeOptions, PipeOptions clientPipeOptions)
        --- End of stack trace from previous location where exception was thrown ---
Unhandled exception. Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.UnauthorizedAccessException)
Actual:   (No exception was thrown)
   at Xunit.Assert.Throws(Type exceptionType, Exception exception) in C:\projects\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 147
   at Xunit.Assert.Throws[T](Action testCode) in C:\projects\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 27
   at System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.ConnectClientFromRemoteInvoker(String pipeName, String isCurrentUserOnly) in /_/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CurrentUserOnly.netcoreapp.Unix.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.RemoteExecutorHost.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutorHost/Program.cs:line 92
    System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.Connection_UnderDifferentUsers_BehavesAsExpected(serverPipeOptions: CurrentUserOnly, clientPipeOptions: CurrentUserOnly) [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.ThrowsException: Assert.Throws() Failure
        Expected: typeof(System.UnauthorizedAccessException)
        Actual:   (No exception was thrown)
        /_/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CurrentUserOnly.netcoreapp.Unix.cs(58,0): at System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.ConnectClientFromRemoteInvoker(String pipeName, String isCurrentUserOnly)
        
        Child process:
          System.IO.Pipes.Tests, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix Int32 ConnectClientFromRemoteInvoker(System.String, System.String)
        
        Child arguments:
          /tmp/owrywjev.ir1, true
        
  Finished:    System.IO.Pipes.Tests
=== TEST EXECUTION SUMMARY ===
   System.IO.Pipes.Tests  Total: 196, Errors: 0, Failed: 3, Skipped: 0, Time: 21.478s
~/helix/work/workitem
----- end Mon Jul 1 13:48:11 UTC 2019 ----- exit code 1 ----------------------------------------------------------
Looking around for any Linux dump...
... found no dump in /root/helix/work/workitem
+ export _commandExitCode=1
+ _commandExitCode=1
+ /bin/sh /root/helix/work/correlation/reporter/run.sh https://dev.azure.com/dnceng/ public 6179994 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJlNDI4NWM4Yy0zZmQ1LTQyNjctOWIxYy00MjE5NWM0N2E1NTMiLCJzY3AiOiJMb2NhdGlvblNlcnZpY2UuQ29ubmVjdCBSZWFkQW5kUHVibGlzaFRlc3Q6OWVlNmQ0NzgtZDI4OC00N2Y3LWFhY2MtZjZlNmQwODJhZTZkIFJlYWRBbmRVcGRhdGVCdWlsZEJ5VXJpOjllZTZkNDc4LWQyODgtNDdmNy1hYWNjLWY2ZTZkMDgyYWU2ZC9kb3RuZXQvY29yZWZ4LzMyMzpCdWlsZC9CdWlsZC8yNDU1MTciLCJhdWkiOiIzNjFlMWMwOC1hM2MwLTRjYWEtOTRhNC04NzVmZWIxMTNlMjIiLCJzaWQiOiJkY2EyMDc3My1lZjM1LTQ3ZjUtODRhOS0yNGY2NzdkZWI0NTciLCJpc3MiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tIiwiYXVkIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbXx2c286YjU1ZGU0ZWQtNGI1YS00MjE1LWE4ZTQtMGEwYTVmNzFlN2Q4IiwibmJmIjoxNTYxOTg2NDMyLCJleHAiOjE1NjE5OTg0MzJ9.EC24USiy3wtlPd-NWh2vt5YxtSygsSPE3GsHb1YRnVlcg8HFcCSAEUBdZnb_7yGhOmwAWeixhPpZEmPzHLHbYh0Ts7PUdV6j0F2tqL-vUrUlObz0EuGqIQ0mZw0P5zYxE_zvVeItXBlCADoHcA_hYe4j29aXT1lyTC53TToPCjNoM3k1-MUFkmQoqadOrBX8GUz0H-e0dAYT0UO7lA142xgKh0M2TYduSa5LAeiUF064BjOf0b7-Hxyrcdvo1cQsei-zCbFEeiTkzuGPmoAAWbPtfpLQlMfk-WhubN31AQZNV6dX0wiolR_1NTcdpFFKVIOsZpib0nkwpsTaCTS_ZA
+++ dirname -- /root/helix/work/correlation/reporter/run.sh
++ CDPATH=
++ cd -- /root/helix/work/correlation/reporter
++ pwd
+ script_path=/root/helix/work/correlation/reporter
+ ENV_PATH=/root/.vsts-env
+ date -u +%FT%TZ
2019-07-01T13:48:11Z
+ '[' '!' -f /root/.vsts-env/bin/python ']'
+ python -m virtualenv --no-site-packages /root/.vsts-env
/usr/bin/python: No module named virtualenv
+ /root/.vsts-env/bin/python -m pip install vsts==0.1.20
/root/helix/work/correlation/reporter/run.sh: line 11: /root/.vsts-env/bin/python: No such file or directory
+ /root/.vsts-env/bin/python -c 'import future'
/root/helix/work/correlation/reporter/run.sh: line 14: /root/.vsts-env/bin/python: No such file or directory
+ /root/.vsts-env/bin/python -m pip install future==0.17.1
/root/helix/work/correlation/reporter/run.sh: line 17: /root/.vsts-env/bin/python: No such file or directory
+ date -u +%FT%TZ
2019-07-01T13:48:11Z
+ /root/.vsts-env/bin/python /root/helix/work/correlation/reporter/run.py https://dev.azure.com/dnceng/ public 6179994 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJlNDI4NWM4Yy0zZmQ1LTQyNjctOWIxYy00MjE5NWM0N2E1NTMiLCJzY3AiOiJMb2NhdGlvblNlcnZpY2UuQ29ubmVjdCBSZWFkQW5kUHVibGlzaFRlc3Q6OWVlNmQ0NzgtZDI4OC00N2Y3LWFhY2MtZjZlNmQwODJhZTZkIFJlYWRBbmRVcGRhdGVCdWlsZEJ5VXJpOjllZTZkNDc4LWQyODgtNDdmNy1hYWNjLWY2ZTZkMDgyYWU2ZC9kb3RuZXQvY29yZWZ4LzMyMzpCdWlsZC9CdWlsZC8yNDU1MTciLCJhdWkiOiIzNjFlMWMwOC1hM2MwLTRjYWEtOTRhNC04NzVmZWIxMTNlMjIiLCJzaWQiOiJkY2EyMDc3My1lZjM1LTQ3ZjUtODRhOS0yNGY2NzdkZWI0NTciLCJpc3MiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tIiwiYXVkIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbXx2c286YjU1ZGU0ZWQtNGI1YS00MjE1LWE4ZTQtMGEwYTVmNzFlN2Q4IiwibmJmIjoxNTYxOTg2NDMyLCJleHAiOjE1NjE5OTg0MzJ9.EC24USiy3wtlPd-NWh2vt5YxtSygsSPE3GsHb1YRnVlcg8HFcCSAEUBdZnb_7yGhOmwAWeixhPpZEmPzHLHbYh0Ts7PUdV6j0F2tqL-vUrUlObz0EuGqIQ0mZw0P5zYxE_zvVeItXBlCADoHcA_hYe4j29aXT1lyTC53TToPCjNoM3k1-MUFkmQoqadOrBX8GUz0H-e0dAYT0UO7lA142xgKh0M2TYduSa5LAeiUF064BjOf0b7-Hxyrcdvo1cQsei-zCbFEeiTkzuGPmoAAWbPtfpLQlMfk-WhubN31AQZNV6dX0wiolR_1NTcdpFFKVIOsZpib0nkwpsTaCTS_ZA
/root/helix/work/correlation/reporter/run.sh: line 21: /root/.vsts-env/bin/python: No such file or directory
+ date -u +%FT%TZ
2019-07-01T13:48:11Z
+ python /root/helix/work/correlation/xunit-reporter.py
Traceback (most recent call last):
  File "/root/helix/work/correlation/xunit-reporter.py", line 5, in <module>
    import helix.azure_storage
  File "/root/helix/scripts/helix/__init__.py", line 1, in <module>
    import helix.depcheck
  File "/root/helix/scripts/helix/depcheck.py", line 66
    def _is_legal_module(module_name: str) -> bool:
                                    ^
SyntaxError: invalid syntax
+ exit 1

[END EXECUTION]
Exit Code:1
```

**Comment by danmosemsft** [comment]
`Fedora.29.Amd64.Open-x64:Debug` again.

**Comment by stephentoub** [comment]
Again:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39311~2Fmerge/test~2Ffunctional~2Fcli~2Fouterloop~2F/20190710.6/workItem/System.IO.Pipes.Tests/wilogs
```
Unhandled exception. Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.UnauthorizedAccessException)
Actual:   (No exception was thrown)
   at Xunit.Assert.Throws(Type exceptionType, Exception exception) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 147
   at Xunit.Assert.Throws[T](Action testCode) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 27
   at System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.ConnectClientFromRemoteInvoker(String pipeName, String isCurrentUserOnly) in /_/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CurrentUserOnly.netcoreapp.Unix.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.RemoteExecutorHost.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutorHost/Program.cs:line 92
    System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.Connection_UnderDifferentUsers_BehavesAsExpected(serverPipeOptions: None, clientPipeOptions: CurrentUserOnly) [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.ThrowsException: Assert.Throws() Failure
        Expected: typeof(System.UnauthorizedAccessException)
        Actual:   (No exception was thrown)
        /_/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CurrentUserOnly.netcoreapp.Unix.cs(58,0): at System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.ConnectClientFromRemoteInvoker(String pipeName, String isCurrentUserOnly)
        
        Child process:
          System.IO.Pipes.Tests, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix Int32 ConnectClientFromRemoteInvoker(System.String, System.String)
        
        Child arguments:
          /tmp/cb5ekmww.5y3, true
        
    System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.Connection_UnderDifferentUsers_BehavesAsExpected(serverPipeOptions: CurrentUserOnly, clientPipeOptions: None) [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.UnauthorizedAccessException)
      Actual:   (No exception was thrown)
      Stack Trace:
        /_/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CurrentUserOnly.netcoreapp.Unix.cs(46,0): at System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.Connection_UnderDifferentUsers_BehavesAsExpected(PipeOptions serverPipeOptions, PipeOptions clientPipeOptions)
        --- End of stack trace from previous location where exception was thrown ---
Unhandled exception. Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.UnauthorizedAccessException)
Actual:   (No exception was thrown)
   at Xunit.Assert.Throws(Type exceptionType, Exception exception) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 147
   at Xunit.Assert.Throws[T](Action testCode) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 27
   at System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.ConnectClientFromRemoteInvoker(String pipeName, String isCurrentUserOnly) in /_/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CurrentUserOnly.netcoreapp.Unix.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.RemoteExecutorHost.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutorHost/Program.cs:line 92
    System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.Connection_UnderDifferentUsers_BehavesAsExpected(serverPipeOptions: CurrentUserOnly, clientPipeOptions: CurrentUserOnly) [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.ThrowsException: Assert.Throws() Failure
        Expected: typeof(System.UnauthorizedAccessException)
        Actual:   (No exception was thrown)
        /_/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CurrentUserOnly.netcoreapp.Unix.cs(58,0): at System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix.ConnectClientFromRemoteInvoker(String pipeName, String isCurrentUserOnly)
        
        Child process:
          System.IO.Pipes.Tests, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Unix Int32 ConnectClientFromRemoteInvoker(System.String, System.String)
        
        Child arguments:
          /tmp/k4bhc01p.vc5, true
```

**Comment by stephentoub** [comment]
Yet again:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39352~2Fmerge/test~2Ffunctional~2Fcli~2Fouterloop~2F/20190710.5/workItem/System.IO.Pipes.Tests/wilogs

**Comment by stephentoub** [comment]
This continues to fail on Fedora, e.g.
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39471~2Fmerge/test~2Ffunctional~2Fcli~2Fouterloop~2F/20190715.3/workItem/System.IO.Pipes.Tests/wilogs

I'm going to disable it to remove the noise, but we should figure out what's going on here.  It's concerning that we should be deeming something unauthorized and aren't.

**Comment by carlossanlop** [comment]
I ran the unit test multiple times in a loop inside a Fedora Docker container, and it didn't fail.
I'm reading through the code to understand what could be causing the intermittent failure.

**Comment by carlossanlop** [comment]
Ran it again in a loop. It passed 1300 times, didn't fail once.
Santi suggested I try to imitate the CI environment as much as possible. I have an Ubuntu VM, and will create the Fedora docker container inside it, then run the test.

**Comment by stephentoub** [comment]
Are you running with sudo?

**Comment by carlossanlop** [comment]
Yes it was root. It's the default user in the Fedora Docker container, I didn't modify its configuration.
Was I supposed to use a normal user?

**Comment by stephentoub** [comment]
I'm wondering if these failures may be happening in cases where execution happens in an unexpected way, due to an infrastructure glitch or otherwise.

**Comment by carlossanlop** [comment]
Didn't hit it. Moving it to 5.0. Seems to be infrastructure related.

**Comment by wfurt** [comment]
This test will ALWAYS fail when running as `root` or elevated. Name pipe access compares EUID with EUID of the remote process. Now, we expect this to throw when running as `RunAsSudo`.  But if the current user is the same as `Sudo`, access will work and the test will fail. 
I can reproduce this easily in my Ubuntu18.04 system. 
Rather than skipping on Fedora, this test is invalid IMHO if `Interop.Sys.GetEUid == 0`
It also seems that the current Fedora image defaults to `helixbot` user. 
With that, it should be safe to enable this test again IMHO - perhaps with the caveat mentioned above.
