### ISSUE TITLE
Dispose_ProcessingResponse_OK HTTP2 test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#38859]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38844~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190624.72/workItem/System.Net.Http.Functional.Tests/wilogs
Fedora.29.Amd64.Open-x64:Debug
```
  System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Dispose_ProcessingResponse_OK [FAIL]
      Assert.Equal() Failure
      Expected: 100
      Actual:   200
      Stack Trace:
        /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs(1492,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<>c__DisplayClass52_0.<<Dispose_ProcessingResponse_OK>b__0>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(83,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(111,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(71,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs(186,0): at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Int32 timeout)
        /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs(1471,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.Dispose_ProcessingResponse_OK()
        --- End of stack trace from previous location where exception was thrown ---
```

**Comment by stephentoub** [comment]
Again here:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38880~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190625.22/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FDispose_ProcessingResponse_OK
```
Windows.81.Amd64.Open-x86-Release
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.EqualException
Message :
Assert.Equal() Failure
Expected: 100
Actual:   200
Stack Trace :
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<>c__DisplayClass52_0.<<Dispose_ProcessingResponse_OK>b__0>d.MoveNext() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1492
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 77
   at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Int32 timeout) in /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 186
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.Dispose_ProcessingResponse_OK() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1471
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by stephentoub** [comment]
Again here:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38940~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190626.35/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FDispose_ProcessingResponse_OK
