### ISSUE TITLE
Data Adapter Batch insert not working in sql client preview 7 

### ISSUE THREAD

**Issue by suthrams** [dotnet/corefx#38895]
Describe the bug
Data Adapter Update batch operation is throwing this exception below on Core 2.1 using the 4.7 Preview 6 package of System.Data.SqlClient.
System.Data.SqlClient.SqlException: Implicit conversion from data type nvarchar to varbinary is not allowed. Use the CONVERT function to run this query.
However the same batch adapter operation passes on Net 4.6.2 framework
If you are seeing an exception, include the full exceptions details (message and stack trace).
Exception message:
Stack trace:
at System.Data.Common.DbDataAdapter.UpdatedRowStatusErrors(RowUpdatedEventArgs rowUpdatedEvent, BatchCommandInfo[] batchCommands, Int32 commandCount)
   at System.Data.Common.DbDataAdapter.UpdatedRowStatus(RowUpdatedEventArgs rowUpdatedEvent, BatchCommandInfo[] batchCommands, Int32 commandCount)
   at System.Data.Common.DbDataAdapter.Update(DataRow[] dataRows, DataTableMapping tableMapping)
   at System.Data.Common.DbDataAdapter.UpdateFromDataTable(DataTable dataTable, DataTableMapping tableMapping)
   at System.Data.Common.DbDataAdapter.Update(DataTable dataTable)
   at LandisGyr.Data.DBTools.FlushUsingAdapters(String databaseKey, DataTable tbl, DbConnection con, DbCommand cmd, DbTransaction tran, Int32 commandTimeOut, Int32 adapterBatchSize) in D:\Git\NuGet_LGData\LandisGyr.Data\Foundation\DBTools.cs:line 1691
   at DAL_Generator_Test.Insnetworkdatabatch2DataSet.Flush(DbConnection con, DbTransaction tran, Int32 commandTimeOut) in D:\Git\NuGet_LGDataSqlServer\Tests\LG.Data.SqlServer.Tests\GeneratedDAL\Insnetworkdatabatch2.generated.cs:line 450
   at LandisGyr.Data.BaseDataBatch.FlushStoreNewTran(IDbDataStore store, DbConnection connection, Int32 timeout, Int32 originalTimeOut) in D:\Git\NuGet_LGData\LandisGyr.Data\Foundation\BaseDataBatch.cs:line 370
   at LandisGyr.Data.BaseDataBatch.FlushDataSeperateTrans() in D:\Git\NuGet_LGData\LandisGyr.Data\Foundation\BaseDataBatch.cs:line 328
   at LandisGyr.Data.BaseDataBatch.FlushData() in D:\Git\NuGet_LGData\LandisGyr.Data\Foundation\BaseDataBatch.cs:line 445
   at DAL_Generator_Test.SqlServerTests.TestBasicConnectivity.TestReturnTypedDataTable() in D:\Git\NuGet_LGDataSqlServer\Tests\LG.Data.SqlServer.Tests\TestBasicConnectivity.cs:line 566

### To reproduce
 1) Create table using script below
CREATE TABLE [dbo].[StgNetworkStats2](
	[insertedDate] [datetime] NOT NULL,
	[endPointId] [int] NOT NULL,
	[recordTypeID] [int] NOT NULL,
	[recordValue] [bigint] NOT NULL,
	[packetSize] [int] NOT NULL,
	[userComments] [varchar](255) NULL,
	[packetContents] [varbinary](255) NULL,
 CONSTRAINT [PKC_StgNetworkStats2_DtSnRt] PRIMARY KEY CLUSTERED 
(
	[insertedDate] ASC,
	[endPointId] ASC,
	[recordTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

2) Write Stored Procedure
 IF EXISTS (SELECT * FROM sysobjects WHERE type = 'P' AND name = 'Insnetworkdatabatch2')
	BEGIN
		PRINT 'Dropping Procedure Insnetworkdatabatch2'
		DROP Procedure Insnetworkdatabatch2
	END
GO

PRINT 'Creating Procedure Insnetworkdatabatch2'
GO

CREATE PROCEDURE [dbo].[Insnetworkdatabatch2] 
@endPointId       INT, 
@insertedDateTime DATETIME, 
@recordTypeID     INT, 
@recordValue      BIGINT, 
@packetSize       INT,
@userComments  varchar(255) null,
@packetContents varbinary(255) null

AS 
    SET nocount ON 
    SET xact_abort ON 

  BEGIN try 
      INSERT stgnetworkstats2
             (inserteddate, 
              endpointid, 
              recordtypeid, 
              recordvalue, 
              packetsize,
			  userComments, 
			  packetContents) 
      VALUES ( @insertedDateTime, 
               @endPointID, 
               @recordTypeID, 
               @recordValue, 
               @packetSize, 
			   @userComments, 
			   @packetContents ) 
  END try 

  BEGIN catch 
      IF Error_number() = 2627 -- Violates Primary Key 
        RETURN 0 
  END catch 

GO

3) Call the stored procedure in a batch using data adapters
and verify there is no exception in the insert and the records are inserted.
Here is our app code
     DBTools.ExecuteSql(key, "TRUNCATE TABLE StgNetworkStats2");
            Insnetworkdatabatch2DataBatchFactory factory = new Insnetworkdatabatch2DataBatchFactory();
            var batch = factory.GetBatch(key, 100);
            for (int i = 0; i < BULK_OP_RECORDS_SIZE; i++)
            {
                var record = batch.NewInsnetworkdatabatch2Record();

                record.EndPointId = i;
                record.InsertedDateTime = DateTime.UtcNow;
                record.RecordValue = i;
                record.RecordTypeID = 1;
                record.PacketSize = 100;
                record.UserComments = i % 2 == 0 ? $"comment {i}" : null;
                record.PacketContents = i % 2 == 0 ? Encoding.ASCII.GetBytes("comment {i}") : null;

                batch.AddInsnetworkdatabatch2Record(record);
            }
            batch.FlushData();

Here is our underlying data access code..  sample

    public static void FlushUsingAdapters(string databaseKey, DataTable tbl, DbConnection con, DbCommand cmd, DbTransaction tran, int commandTimeOut, int adapterBatchSize)
        {
            using (DbDataAdapter adapter = DatabaseHelper.GetDbDataAdapter(databaseKey))
            {
                adapter.UpdateBatchSize = adapterBatchSize;
                adapter.InsertCommand = cmd;
                adapter.InsertCommand.Connection = con;
                adapter.InsertCommand.CommandTimeout = commandTimeOut;
                adapter.InsertCommand.UpdatedRowSource = UpdateRowSource.None;
                adapter.InsertCommand.Transaction = tran;
                adapter.Update(tbl);

            }
        }

```c#
 

OS : Windows 10
Net Target : Net 4.6.2 and Net Core 2.1
SQL Server 2017 Developer Edition
OS : Windows 10
System.Data.SqlClient version: system.data.sqlclient.4.7.0-preview6.19303.8


Here is the source code 
using System;
using System.Configuration;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Text;

namespace ConsoleApp1
{
    static class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Testing data flush using data adapters");

            TestDataFlushUsingAdapters();


            Console.WriteLine("Pressing any key to continue");

        }


        /// <summary>
        /// 
        /// </summary>

        public static void TestDataFlushUsingAdapters()
        {

            using (DbConnection con = SqlClientFactory.Instance.CreateConnection())
            {
                con.ConnectionString = ConfigurationManager.ConnectionStrings["SqlTest"].ConnectionString;

                con.Open();

                DbTransaction tran = con.BeginTransaction();

                using (SqlCommand cmd = (SqlCommand)con.CreateCommand())
                {


                    SetupCommand(cmd);

                    var ds = GetDataToFlush();

                    using (SqlDataAdapter adapter = new SqlDataAdapter())
                    {

                        adapter.UpdateBatchSize = 100;
                        adapter.InsertCommand = cmd;
                        adapter.InsertCommand.Connection = (SqlConnection)con;
                        adapter.InsertCommand.CommandTimeout = 300;
                        adapter.InsertCommand.UpdatedRowSource = UpdateRowSource.None;
                        adapter.InsertCommand.Transaction = (SqlTransaction)tran;
                        adapter.Update(ds.Tables[0]);

                    }

                    tran.Commit();
                }

            }
        }

        public static void SetupCommand(SqlCommand cmd)
        {


            cmd.CommandText = "Insnetworkdatabatch2";
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            SqlParameter endpointParam = cmd.Parameters.Add("@endPointId", SqlDbType.Int, 4);
            endpointParam.Direction = ParameterDirection.Input;
            endpointParam.SourceVersion = DataRowVersion.Current;
            endpointParam.SourceColumn = "endPointId";

            SqlParameter insertedDateTime = cmd.Parameters.Add("@insertedDateTime", SqlDbType.DateTime);
            insertedDateTime.Direction = ParameterDirection.Input;
            insertedDateTime.SourceVersion = DataRowVersion.Current;
            insertedDateTime.SourceColumn = "insertedDateTime";

            SqlParameter recordTypeId = cmd.Parameters.Add("@recordTypeId", SqlDbType.Int, 4);
            recordTypeId.Direction = ParameterDirection.Input;
            recordTypeId.SourceVersion = DataRowVersion.Current;
            recordTypeId.SourceColumn = "recordTypeId";

            SqlParameter recordValue = cmd.Parameters.Add("@recordValue", SqlDbType.BigInt, 8);
            recordValue.Direction = ParameterDirection.Input;
            recordValue.SourceVersion = DataRowVersion.Current;
            recordValue.SourceColumn = "recordValue";


            SqlParameter packetSize = cmd.Parameters.Add("@packetSize", SqlDbType.Int, 4);
            packetSize.Direction = ParameterDirection.Input;
            packetSize.SourceVersion = DataRowVersion.Current;
            packetSize.SourceColumn = "packetSize";

            SqlParameter userComments = cmd.Parameters.Add("@userComments", SqlDbType.VarChar, 255);
            userComments.Direction = ParameterDirection.Input;
            userComments.SourceVersion = DataRowVersion.Current;
            userComments.SourceColumn = "userComments";

            SqlParameter packetContents = cmd.Parameters.Add("@packetContents", SqlDbType.VarBinary, 255);
            packetContents.Direction = ParameterDirection.Input;
            packetContents.SourceVersion = DataRowVersion.Current;
            packetContents.SourceColumn = "packetContents";

            SqlParameter returnParam = cmd.Parameters.Add("@RETURN_VALUE", SqlDbType.Int);
            returnParam.Direction = ParameterDirection.ReturnValue;
            endpointParam.SourceVersion = DataRowVersion.Current;
        }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="tbl"></param>
        /// <returns></returns>

        public static DataSet GetDataToFlush()
        {
            DataSet ds = new DataSet();


            DataTable dt = new DataTable();
            dt.TableName = "Insnetworkdatabatch2";

            dt.Columns.Add("endPointId", Type.GetType("System.Int32"));
            dt.Columns.Add("insertedDateTime", Type.GetType("System.DateTime"));
            dt.Columns.Add("recordTypeID", Type.GetType("System.Int32"));
            dt.Columns.Add("recordValue", Type.GetType("System.Int64"));
            dt.Columns.Add("packetSize", Type.GetType("System.Int32"));
            dt.Columns.Add("userComments", Type.GetType("System.String"));
            dt.Columns.Add("packetContents", Type.GetType("System.Byte[]"));

            for (int i = 0; i < 100; i++)
            {

                var record = dt.NewRow();
                record["endPointid"] = i;
                record["insertedDateTime"] = DateTime.UtcNow;
                record["recordTypeId"] = 1;
                record["recordValue"] = i;
                record["packetSize"] = 100;
                record["userComments"] = i % 2 == 0 ? $"comment {i}" : null;
                record["packetContents"] = i % 2 == 0 ? Encoding.ASCII.GetBytes("comment {i}") : null;

                dt.Rows.Add(record);

            }

            ds.Tables.Add(dt);
            return ds;

        }
    }
}

**Comment by kay3421** [comment]
I need assistance in putting all this in

**Comment by suthrams** [comment]
What kind of assistance ?

On Jun 25, 2019, at 4:35 PM, kay3421 <notifications@github.com<mailto:notifications@github.com>> wrote:


I need assistance in putting all this in

**Comment by suthrams** [comment]
@stephentoub  can you give us an update if you were able to repro and confirm this issue and need more info from me.

**Comment by cheenamalhotra** [comment]
Hi @suthrams 

I'm trying to run the repro code you provided and I'm getting an `System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'` error. Is that the same error you're reporting here or something else?

**Comment by cheenamalhotra** [comment]
Hi @suthrams 

Small update for you:
We addressed the same issue here: https://github.com/dotnet/SqlClient/issues/127.

The latest preview release of [Microsoft.Data.SqlClient](https://www.nuget.org/packages/Microsoft.Data.SqlClient) contains the fix for reported issue. We will port over the changes to **System.Data.SqlClient** soon.
