### ISSUE TITLE
Failing unit test locally on mac: BitmapTests.GetFrameCount_NewBitmap_ReturnsZero

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#38917]
```
        System.Runtime.InteropServices.ExternalException : A generic error occurred in GDI+.
        Stack Trace:
          /Users/hugh/Documents/GitHub/corefx/src/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(259,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
          /Users/hugh/Documents/GitHub/corefx/src/System.Drawing.Common/src/System/Drawing/Image.cs(271,0): at System.Drawing.Image.GetFrameCount(FrameDimension dimension)
          /Users/hugh/Documents/GitHub/corefx/src/System.Drawing.Common/tests/BitmapTests.cs(555,0): at System.Drawing.Tests.BitmapTests.GetFrameCount_NewBitmap_ReturnsZero()
```

**Comment by stephentoub** [comment]
What OS version?

**Comment by hughbe** [comment]
![Screenshot 2019-06-26 at 14 00 44](https://user-images.githubusercontent.com/1275900/60181751-d0bb0580-981a-11e9-9a30-6cfa0ca4d855.png)
