### ISSUE TITLE
Failures in HttpWindowsProxy thrown and eaten

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#38989]
I enabled tracing for a localhost workload, and I'm seeing a ton of these errors in the log:
```
[ErrorMessage] thisOrContextObject: HttpConnectionPoolManager#35287174, memberName: SendAsync, message: Exception from IWebProxy.GetProxy(https://localhost:5001/): System.ArgumentNullException: SafeHandle cannot be null.
Parameter name: pHandle
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.WinHttp.WinHttpGetProxyForUrl(SafeWinHttpHandle sessionHandle, String url, WINHTTP_AUTOPROXY_OPTIONS& autoProxyOptions, WINHTTP_PROXY_INFO& proxyInfo)
   at System.Net.Http.WinInetProxyHelper.GetProxyForUrl(SafeWinHttpHandle sessionHandle, Uri uri, WINHTTP_PROXY_INFO& proxyInfo) in d:\repos\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinInetProxyHelper.cs:line 123
   at System.Net.Http.HttpWindowsProxy.GetProxy(Uri uri) in d:\repos\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpWindowsProxy.cs:line 291
   at System.Net.Http.HttpConnectionPoolManager.SendAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in d:\repos\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPoolManager.cs:line 284
```
This is coming from:
https://github.com/dotnet/corefx/blob/c661db6ce2da91033671c0000afc185de1ad3fe9/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPoolManager.cs#L280-L292
and so it appears we've got a bug in our HttpWindowsProxy code.

I'll try to work up an isolated repro once I'm done what I'm currently working on.

cc: @davidsh

**Comment by stephentoub** [comment]
The problem is here:
https://github.com/dotnet/corefx/blob/c661db6ce2da91033671c0000afc185de1ad3fe9/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPoolManager.cs#L312-L315

I'm not sure why HttpConnectionPoolManager is disposing of the proxy.  @geoffkizer, it looks like you added that... do you remember why?  Seems like the fix is simply to delete these lines.

**Comment by stephentoub** [comment]
The reason I'm seeing this in the stress test from https://github.com/dotnet/corefx/issues/38911 is because of the race condition where multiple initial requests on the handler may race to configure its handler chain: only one can win and publish the chain for all requests to use, and the rest get disposed of.  Since all of the handler chains share the same proxy instance, disposing of the secondary instances is causing the main proxy instance to be disposed of as well.

**Comment by geoffkizer** [comment]
I think @wfurt added that originally, see here: 
https://github.com/dotnet/corefx/commit/468db63e2648f8a4c0c82d97e301e308b7887f7e#diff-6aab3bf374505db7cab3aca25308bafbR155

**Comment by stephentoub** [comment]
> I think @wfurt added that originally

Ugh, and it looks like he did so because I proposed doing so:
https://github.com/dotnet/corefx/pull/26878#discussion_r166244807
Obviously I didn't understand the ramifications :)

**Comment by davidsh** [comment]
>Obviously I didn't understand the ramifications :)

I miss COM and AddRef(), Release(). .NET having explicit Dispose() without care of knowing if others have references to the object is problematic. :)

**Comment by geoffkizer** [comment]
Minor issue: Seems like WinInetProxyHelper shouldn't be trying to use the handle if it's disposed...
