### ISSUE TITLE
Unhandled Exception TaskCanceledException (thrown from WhenAllOrAnyFailed)

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#39059]
Hit by `System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_NonStandardRequestHeaders_HeadersAddedWithoutValidation` test in https://github.com/dotnet/coreclr/pull/25497 on  Linux x64 checked

```
Unhandled Exception of Type System.Threading.Tasks.TaskCanceledException
Message :
System.Threading.Tasks.TaskCanceledException : A task was canceled.
Stack Trace :
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass11_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 66
   at System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_NonStandardRequestHeaders_HeadersAddedWithoutValidation() in /_/src/System.Net.WebSockets.Client/tests/ConnectTest.cs:line 237
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by davidsh** [comment]
@stephentoub

**Comment by stephentoub** [comment]
This test talks to an external server, and this is a timeout.

**Comment by davidsh** [comment]
>This test talks to an external server, and this is a timeout.

Isn't it the loopback server since it is on the callstack:
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass11_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 83
--- End of stack trace from previous location where exception was thrown ---

**Comment by stephentoub** [comment]
> Isn't it the loopback server

Yup.  Apparently I was looking at the wrong test.

**Comment by jkotas** [comment]
Another hit: https://github.com/dotnet/coreclr/pull/25563

**Comment by stephentoub** [comment]
I'll take a look. It's strange that this one test is having issues.

**Comment by jkotas** [comment]
Hit: https://github.com/dotnet/coreclr/pull/25577

**Comment by davidsh** [comment]
I don't think we've seen this fail recently. Currently this isn't actionable since we can't repro it. So, I'll close this for now.
