### ISSUE TITLE
System.IO.Packaging VeryLargePart outerloop test failing in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39075]
It's failing e.g. on all OSes here:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38804~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190701.1/workItem/System.IO.Packaging.Tests/analysis/xunit/System.IO.Packaging.Tests.Tests~2FVeryLargePart
```
Unhandled Exception of Type System.IO.InvalidDataException
Message :
System.IO.InvalidDataException : A local file header is corrupt.
Stack Trace :
   at System.IO.Compression.ZipArchiveEntry.ThrowIfNotOpenable(Boolean needToUncompress, Boolean needToLoadIntoMemory) in /_/src/System.IO.Compression/src/System/IO/Compression/ZipArchiveEntry.cs:line 597
   at System.IO.Compression.ZipArchiveEntry.OpenInReadMode(Boolean checkOpenable) in /_/src/System.IO.Compression/src/System/IO/Compression/ZipArchiveEntry.cs:line 670
   at System.IO.Compression.ZipArchiveEntry.Open() in /_/src/System.IO.Compression/src/System/IO/Compression/ZipArchiveEntry.cs:line 297
   at System.IO.Packaging.ZipStreamManager.Open(ZipArchiveEntry zipArchiveEntry, FileMode streamFileMode, FileAccess streamFileAccess) in /_/src/System.IO.Packaging/src/System/IO/Packaging/ZipStreamManager.cs:line 86
   at System.IO.Packaging.ZipPackagePart.GetStreamCore(FileMode streamFileMode, FileAccess streamFileAccess) in /_/src/System.IO.Packaging/src/System/IO/Packaging/ZipPackagePart.cs:line 38
   at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access) in /_/src/System.IO.Packaging/src/System/IO/Packaging/PackagePart.cs:line 323
   at System.IO.Packaging.PackagePart.GetStream() in /_/src/System.IO.Packaging/src/System/IO/Packaging/PackagePart.cs:line 270
   at System.IO.Packaging.Tests.Tests.VeryLargePart() in /_/src/System.IO.Packaging/tests/Tests.cs:line 3739
```
cc: @ericstj

**Comment by danmosemsft** [comment]
The "file" being opened here is an in memory stream that the test writes itself, so it's not that we downloaded corrupted test data.

If I read Kusto correctly, the last time it passed (other than on NETFX) was 2019-06-26 10:27:37.9640000 and the first time it failed was 2019-06-27 10:16:37.7610000

cc @ericstj @stevenbrix as they have recently been involved with this code. @stevenbrix last change was earlier on 6/19 though 74032a608cf39d8eaa2955cc46d0ac677e3ae12c

**Comment by ericstj** [comment]
I actually believe this is a regression caused by https://github.com/dotnet/corefx/commit/cece0df13a74d188f96b08ae5af0cd4cd60f8f76#diff-9a2a4ae4ec3cc597b970314341c22799.  /cc @buyaa-n

**Comment by buyaa-n** [comment]
Yes it is caused from my recent change :(. Found the root cause: https://github.com/dotnet/corefx/commit/cece0df13a74d188f96b08ae5af0cd4cd60f8f76#diff-f4862dd89b6a3fe07a50136fa19fa4f7R498
`bool is64bit = minimumVersion > (uint)ZipVersionNeededValues.Zip64;` this should be:
`bool is64bit = minimumVersion >= (uint)ZipVersionNeededValues.Zip64` at first it was comparing:
`bool is64bit = minimumVersion > 44` then updated 44 into ZipVersionNeededValues.Zip64 which is 45 not 44, will test and raise PR for fix

**Comment by ericstj** [comment]
Thanks @buyaa-n.  To repro you can run `dotnet msbuild /t:BuildAndTest /p:OuterLoop=true` on the System.IO.Packaging tests.

**Comment by buyaa-n** [comment]
Thank you @ericstj it took me a while to make that `[OuterLoop]` test run in VS debug, then finally was able to run it by commenting out that `[OuterLoop]` attribute 😛

**Comment by ericstj** [comment]
Here's a doc: https://github.com/dotnet/corefx/blob/ab58ff6e649852b85fdb99b15992a2fa3a7d8834/Documentation/project-docs/developer-guide.md#outerloopattribute
In VS you could modify the project file to set the OuterLoop property to true in the test CSProj, not sure if there's a trick to do something similar in the GUI /cc @ViktorHofer

**Comment by danmosemsft** [comment]
Yay for the rapid collaboration here..

**Comment by ViktorHofer** [comment]
That's a bit tricky in VS as there is no GUI to control traits AFAIK (maybe that's coming in the update).

**Comment by stephentoub** [comment]
The VeryLargePart test is still disabled against this issue:
https://github.com/dotnet/runtime/blob/0b25063ec056b0d6668bf0848d108d8c873f3fce/src/libraries/System.IO.Packaging/tests/Tests.cs#L3755-L3758
