### ISSUE TITLE
ConvertTo_DestinationType_Success test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39084]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39078~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190701.19/workItem/System.ComponentModel.TypeConverter.Tests/analysis/xunit/System.ComponentModel.Tests.DateTimeOffsetConverterTests~2FConvertTo_DestinationType_Success
```
Windows.10.Amd64.ClientRS5.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.AllException
Message :
Assert.All() Failure: 1 out of 13 items in the collection did not pass.
[3]: Item: System.ComponentModel.Tests.TypeConverterTestBase+ConvertTest
     Xunit.Sdk.EqualException: Assert.Equal() Failure
     Expected: 12/5/1998 10:30 PM +00:00
     Actual:   05/12/1998 22:30 +00:00
        at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 41
        at Xunit.Assert.Equal[T](T expected, T actual) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 25
        at System.ComponentModel.Tests.TypeConverterTestBase.AssertEqualInstanceDescriptor(Object expected, Object actual) in /_/src/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 173
        at System.ComponentModel.Tests.TypeConverterTestBase.<ConvertTo_DestinationType_Success>b__13_0(ConvertTest convertTest) in /_/src/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 42
        at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36
Stack Trace :
   at System.ComponentModel.Tests.TypeConverterTestBase.ConvertTo_DestinationType_Success() in /_/src/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 31
```

**Comment by stephentoub** [comment]
Again here:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39110~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190702.11/workItem/System.ComponentModel.TypeConverter.Tests/analysis/xunit/System.ComponentModel.Tests.DateTimeOffsetConverterTests~2FConvertTo_DestinationType_Success
```
Windows.10.Amd64.ClientRS5.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.AllException
Message :
Assert.All() Failure: 1 out of 13 items in the collection did not pass.
[3]: Item: System.ComponentModel.Tests.TypeConverterTestBase+ConvertTest
     Xunit.Sdk.EqualException: Assert.Equal() Failure
     Expected: 12/5/1998 10:30 PM +00:00
     Actual:   05/12/1998 22:30 +00:00
        at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 41
        at Xunit.Assert.Equal[T](T expected, T actual) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 25
        at System.ComponentModel.Tests.TypeConverterTestBase.AssertEqualInstanceDescriptor(Object expected, Object actual) in /_/src/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 173
        at System.ComponentModel.Tests.TypeConverterTestBase.<ConvertTo_DestinationType_Success>b__13_0(ConvertTest convertTest) in /_/src/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 42
        at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36
Stack Trace :
   at System.ComponentModel.Tests.TypeConverterTestBase.ConvertTo_DestinationType_Success() in /_/src/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 31
```

**Comment by stephentoub** [comment]
Again here:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39113~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190702.14/workItem/System.ComponentModel.TypeConverter.Tests/analysis/xunit/System.ComponentModel.Tests.DateTimeOffsetConverterTests~2FConvertTo_DestinationType_Success
```
Windows.10.Amd64.ClientRS5.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.AllException
Message :
Assert.All() Failure: 1 out of 13 items in the collection did not pass.
[3]: Item: System.ComponentModel.Tests.TypeConverterTestBase+ConvertTest
     Xunit.Sdk.EqualException: Assert.Equal() Failure
     Expected: 12/5/1998 10:30 PM +00:00
     Actual:   05/12/1998 22:30 +00:00
        at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 41
        at Xunit.Assert.Equal[T](T expected, T actual) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 25
        at System.ComponentModel.Tests.TypeConverterTestBase.AssertEqualInstanceDescriptor(Object expected, Object actual) in /_/src/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 173
        at System.ComponentModel.Tests.TypeConverterTestBase.<ConvertTo_DestinationType_Success>b__13_0(ConvertTest convertTest) in /_/src/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 42
        at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36
Stack Trace :
   at System.ComponentModel.Tests.TypeConverterTestBase.ConvertTo_DestinationType_Success() in /_/src/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 31
```

**Comment by wtgodbe** [comment]
@stephentoub this test is still failing occasionally, e.g. in https://dev.azure.com/dnceng/public/_build/results?buildId=285195

**Comment by stephentoub** [comment]
@wtgodbe, those failures are all on Nano (which I thought we disabled entirely, but maybe that was only for PRs?).  Are there any failures not on Nano?

**Comment by ericstj** [comment]
@safern is working on re-enabling nano in https://github.com/dotnet/corefx/pull/39734.  Current read is that this new build no longer exhibits this error, but some other failures are occurring due to OS changes.

@stephentoub that's correct: we still run nano in rolling builds.  Any cases of -1073740940 (STATUS_HEAP_CORRUPTION) on nano can be ignored until https://github.com/dotnet/corefx/pull/39734 goes in.
