### ISSUE TITLE
Reenable Http2_ServerSendsInvalidSettingsValue_Error test

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#39143]
This is marked as [ActiveIssue(35466)], but #35466 has been closed.

When I reenable and run this, I get: 

```
      System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_ServerSendsInvalidSettingsValue_Error(settingId: MaxFrameSize, value: 16383, expectedError: PROTOCOL_ERROR, skipForWinHttp: True) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.Net.Http.HttpRequestException)
        Actual:   typeof(System.Threading.Tasks.TaskCanceledException): The operation was canceled.
        ---- System.Threading.Tasks.TaskCanceledException : The operation was canceled.
        Stack Trace:
          C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\CancellationHelper.cs(34,0): at System.Net.Http.CancellationHelper.ThrowOperationCanceledException(Exception innerException, CancellationToken cancellationToken)
          C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\CancellationHelper.cs(42,0): at System.Net.Http.CancellationHelper.ThrowIfCancellationRequested(CancellationToken cancellationToken)
          C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Stream.cs(779,0): at System.Net.Http.Http2Connection.Http2Stream.<>c__DisplayClass51_0.<<GetWaiterTask>g__GetWaiterTaskCore|0>d.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
          C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Stream.cs(557,0): at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
          C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs(1540,0): at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
          C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs(541,0): at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
          C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\RedirectHandler.cs(33,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
          C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(496,0): at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
          ----- Inner Stack Trace -----
          C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\CancellationHelper.cs(34,0): at System.Net.Http.CancellationHelper.ThrowOperationCanceledException(Exception innerException, CancellationToken cancellationToken)
          C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\CancellationHelper.cs(42,0): at System.Net.Http.CancellationHelper.ThrowIfCancellationRequested(CancellationToken cancellationToken)
          C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Stream.cs(779,0): at System.Net.Http.Http2Connection.Http2Stream.<>c__DisplayClass51_0.<<GetWaiterTask>g__GetWaiterTaskCore|0>d.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
          C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Stream.cs(557,0): at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
          C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs(1540,0): at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
          C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs(541,0): at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
          C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\RedirectHandler.cs(33,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
          C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(496,0): at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
```

**Comment by karelz** [comment]
@geoffkizer @davidsh do you think this is must have for 3.0?

**Comment by geoffkizer** [comment]
Nope, kill it.
