### ISSUE TITLE
ClientAsyncAuthenticate_EachProtocol_Success failed in CI on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3915]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/5187/console
```
System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_EachProtocol_Success [FAIL]
        Timed Out
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Security\tests\FunctionalTests\ClientAsyncAuthenticateTest.cs(196,0): at System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncSslHelper(EncryptionPolicy encryptionPolicy, SslProtocols clientSslProtocols, SslProtocols serverSslProtocols)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Security\tests\FunctionalTests\ClientAsyncAuthenticateTest.cs(90,0): at System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_EachProtocol_Success()
```

**Comment by CIPop** [comment]
The test got changed and renamed. None of the new tests seem to be failing. 
I presume the failure was related to #5185 .
