### ISSUE TITLE
Test failed: System.Resources.Extensions.Tests.PreserializedResourceWriterTests

### ISSUE THREAD

**Issue by VincentBu** [dotnet/corefx#39290]
**Job:**
https://mc.dot.net/#/user/coreclr-corefx-jitstressregs/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190707.1/workItem/System.Resources.Extensions.Tests/analysis/xunit/System.Resources.Extensions.Tests.PreserializedResourceWriterTests~2FStreamResources

**Failed tests:**
System.Resources.Extensions.Tests.PreserializedResourceWriterTests

**Log:**
```
System.ArgumentException : Parameter is not valid.
   at System.Drawing.Graphics.DrawImage(Image image, Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Drawing.Bitmap..ctor(Image original, Int32 width, Int32 height)
   at System.Drawing.Icon.ToBitmap()
   at System.Resources.Extensions.Tests.PreserializedResourceWriterTests.ResourceValueEquals(Object expected, Object actual) in /_/src/System.Resources.Extensions/tests/BinaryResourceWriterUnitTest.cs:line 525
   at System.Resources.Extensions.Tests.PreserializedResourceWriterTests.StreamResources() in /_/src/System.Resources.Extensions/tests/BinaryResourceWriterUnitTest.cs:line 460
```

**Comment by ericstj** [comment]
This appears to be a bug in System.Drawing.Common.  https://github.com/dotnet/corefx/blob/ace61287bee166a3777f5b3832295902a58ca79a/src/System.Drawing.Common/src/System/Drawing/Graphics.Unix.cs#L760

Under GC stress a GC can happen while this method is executing and collect the Graphics object, disposing NativeGraphics.  I believe this requires a HandleRef on the NativeGraphics like is used elsewhere in this file.  /cc @safern

**Comment by safern** [comment]
Moving to 5.0. I wasn't able to repro this locally yet, I still need to try it on an arm device. However, I don't think this would meet the bar for release branch since this is the state `Graphics` class in Unix has been since this library was ported over into .NET Core.
