### ISSUE TITLE
GCNotificationTests outerloop tests consistently failing on all platforms

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39374]
![image](https://user-images.githubusercontent.com/2642209/61019724-2f2eca80-a369-11e9-9da3-6c3b429567ca.png)

e.g.
```
Unhandled Exception of Type Microsoft.DotNet.RemoteExecutor.RemoteExecutionException
Message :
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
Stack Trace :

Child exception:
  Xunit.Sdk.TrueException: (False, -1) Error - WaitForFullGCApproach result not Cancelled
Expected: True
Actual:   False
   at System.Tests.GCExtendedTests.TestWait(Boolean approach, Int32 timeout) in /_/src/System.Runtime/tests/System/GCTests.cs:line 781
   at System.Tests.GCExtendedTests.<>c.<GCNotificationTests>b__4_0(String approachString, String timeoutString) in /_/src/System.Runtime/tests/System/GCTests.cs:line 506

Child process:
  System.Runtime.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.GCExtendedTests+<>c Int32 <GCNotificationTests>b__4_0(System.String, System.String)

Child arguments:
  False, -1
```
https://github.com/dotnet/corefx/blob/b8a7f34e1b64e5c594f591aa8683f34506eb9736/src/System.Runtime/tests/System/GCTests.cs#L500

cc: @Maoni0, @andy-ms

**Comment by stephentoub** [comment]
Reopening to track re-enabling the test

**Comment by joperezr** [comment]
@stephentoub do you plan on re-enabling today, or do you want me to take care of it?

**Comment by stephentoub** [comment]
I was hoping @andy-ms would as part of validating his fix.
