### ISSUE TITLE
Test failure: System.Drawing.Printing.Tests.PrintDocumentTests/DefaultPageSettings_Null_ReturnsExpected

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#39381]
Test `System.Drawing.Printing.Tests.PrintDocumentTests/DefaultPageSettings_Null_ReturnsExpected`has failed.

Message :
```
System.DllNotFoundException : Unable to load DLL 'winspool.drv' or one of its dependencies: The specified module could not be found. (0x8007007E)
```
Stack Trace :
```
   at System.Drawing.SafeNativeMethods.DocumentProperties(HandleRef hwnd, HandleRef hPrinter, String pDeviceName, IntPtr pDevModeOutput, HandleRef pDevModeInput, Int32 fMode)
   at System.Drawing.Printing.PrinterSettings.GetHdevmodeInternal(String printer) in /_/src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.Windows.cs:line 878
   at System.Drawing.Printing.PrinterSettings.GetHdevmodeInternal() in /_/src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.Windows.cs:line 872
   at System.Drawing.Printing.PrinterSettings.GetHdevmode() in /_/src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.Windows.cs:line 863
   at System.Drawing.Printing.PageSettings.GetPaperSize(IntPtr modeHandle) in /_/src/System.Drawing.Common/src/System/Drawing/Printing/PageSettings.Windows.cs:line 426
   at System.Drawing.Printing.PageSettings.get_PaperSize() in /_/src/System.Drawing.Common/src/System/Drawing/Printing/PageSettings.Windows.cs:line 152
   at System.Drawing.Printing.Tests.PrintDocumentTests.AssertDefaultPageSettings(PageSettings pageSettings) in /_/src/System.Drawing.Common/tests/Printing/PrintDocumentTests.cs:line 249
   at System.Drawing.Printing.Tests.PrintDocumentTests.DefaultPageSettings_Null_ReturnsExpected() in /_/src/System.Drawing.Common/tests/Printing/PrintDocumentTests.cs:line 73
```
Build: -[20190710.51](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F~2F/20190710.51)(Master)

Failing configuration:

- Windows.Nano.1803.Amd64.Open-x64-Release

Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F~2F/20190710.51/workItem/System.Drawing.Common.Tests/analysis/xunit/System.Drawing.Printing.Tests.PrintDocumentTests~2FDefaultPageSettings_Null_ReturnsExpected

**Comment by danmosemsft** [comment]
Needs disabling for Nano apparently

**Comment by stephentoub** [comment]
Same test failed but not on Nano and with a different error:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39383~2Fmerge/test~2Ffunctional~2Fcli~2F~2F/20190711.7/workItem/System.Drawing.Common.Tests/analysis/xunit/System.Drawing.Printing.Tests.PrintDocumentTests~2FDefaultPageSettings_Null_ReturnsExpected
```
Windows.10.Amd64.ClientRS4.ES.Open-x86-Release
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.EqualException
Message :
Assert.Equal() Failure
Expected: {X=0,Y=0,Width=827,Height=1169}
Actual:   {X=0,Y=0,Width=0,Height=0}
Stack Trace :
   at System.Drawing.Printing.Tests.PrintDocumentTests.AssertDefaultPageSettings(PageSettings pageSettings) in /_/src/System.Drawing.Common/tests/Printing/PrintDocumentTests.cs:line 252
   at System.Drawing.Printing.Tests.PrintDocumentTests.DefaultPageSettings_Null_ReturnsExpected() in /_/src/System.Drawing.Common/tests/Printing/PrintDocumentTests.cs:line 73
```

**Comment by bartonjs** [comment]
Another different failure on RS4:

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39430~2Fmerge/test~2Ffunctional~2Fcli~2F~2F/20190712.26/workItem/System.Drawing.Common.Tests/analysis/xunit/System.Drawing.Printing.Tests.PrintDocumentTests~2FDefaultPageSettings_Null_ReturnsExpected

```
System.Drawing.Printing.InvalidPrinterException : No printers are installed.
Stack Trace :
   at System.Drawing.Printing.PrinterSettings.GetHdevmodeInternal(String printer) in /_/src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.Windows.cs:line 881
   at System.Drawing.Printing.PrinterSettings.GetHdevmodeInternal() in /_/src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.Windows.cs:line 872
   at System.Drawing.Printing.PrinterSettings.GetHdevmode() in /_/src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.Windows.cs:line 863
   at System.Drawing.Printing.PageSettings.get_Bounds() in /_/src/System.Drawing.Common/src/System/Drawing/Printing/PageSettings.Windows.cs:line 48
   at System.Drawing.Printing.Tests.PrintDocumentTests.AssertDefaultPageSettings(PageSettings pageSettings) in /_/src/System.Drawing.Common/tests/Printing/PrintDocumentTests.cs:line 252
   at System.Drawing.Printing.Tests.PrintDocumentTests.DefaultPageSettings_Null_ReturnsExpected() in /_/src/System.Drawing.Common/tests/Printing/PrintDocumentTests.cs:line 73
```

**Comment by ericstj** [comment]
And another: https://dev.azure.com/dnceng/public/_build/results?buildId=262860&view=ms.vss-test-web.build-test-results-tab&runId=7071116&resultId=100224&paneView=debug

**Comment by stephentoub** [comment]
Failed again here:
https://github.com/dotnet/corefx/pull/39587/checks?check_run_id=172037393

**Comment by stephentoub** [comment]
Again here:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39584~2Fmerge/test~2Ffunctional~2Fcli~2F~2F/20190720.5/workItem/System.Drawing.Common.Tests/analysis/xunit/System.Drawing.Printing.Tests.PrintDocumentTests~2FDefaultPageSettings_Null_ReturnsExpected

**Comment by ericstj** [comment]
Another failure, same as @stephentoub, but in release/3.0
https://dev.azure.com/dnceng/public/_build/results?buildId=316012&view=ms.vss-test-web.build-test-results-tab&runId=9142246&resultId=100242&paneView=debug
