### ISSUE TITLE
Test failure: Microsoft.VisualBasic.Tests.FinancialTests/DDB(Cost: 10000, Salvage: 4350, Life: 84, Period: 35, Factor: 2, expectedOld: 57.3268063538875, expected)

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#39380]
Test `Microsoft.VisualBasic.Tests.FinancialTests/DDB(Cost: 10000, Salvage: 4350, Life: 84, Period: 35, Factor: 2, expectedOld: 57.3268063538875, expected)` has failed.

Message :
```
Assert.Equal() Failure
Expected: 57.32680635388748
Actual:   57.32680635388746
```
Stack Trace :
```
   at Microsoft.VisualBasic.Tests.FinancialTests.AreEqual[T](T expectedOld, T expectedNew, T actual) in /_/src/Microsoft.VisualBasic.Core/tests/FinancialTests.cs:line 20
   at Microsoft.VisualBasic.Tests.FinancialTests.DDB(Double Cost, Double Salvage, Double Life, Double Period, Double Factor, Double expectedOld, Double expectedNew) in /_/src/Microsoft.VisualBasic.Core/tests/FinancialTests.cs:line 38
```
Build: -[20190710.51](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F~2F/20190710.51)(master)

Failing configuration:

- Windows.10.Arm64.Open-arm64-Release

Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F~2F/20190710.51/workItem/Microsoft.VisualBasic.Core.Tests/analysis/xunit/Microsoft.VisualBasic.Tests.FinancialTests~2FDDB(Cost:%2010000,%20Salvage:%204350,%20Life:%2084,%20Period:%2035,%20Factor:%202,%20expectedOld:%2057.3268063538875,%20expected)

**Comment by danmosemsft** [comment]
@cston another FP vagary. We either need to remove test coverage for ARM* and assume x64 protect us forever : or give tests  a little "range" (round value slightly) as we have done in done other FP validation cases.

**Comment by AriNuer** [comment]
Test `Microsoft.VisualBasic.Tests.FinancialTests/DDB_Default ` failed with similar failure:

Message :
```
Assert.Equal() Failure
Expected: 57.32680635388748
Actual:   57.32680635388746
```
Stack Trace :
```
   at Microsoft.VisualBasic.Tests.FinancialTests.AreEqual[T](T expectedOld, T expectedNew, T actual) in /_/src/Microsoft.VisualBasic.Core/tests/FinancialTests.cs:line 21
   at Microsoft.VisualBasic.Tests.FinancialTests.DDB_Default() in /_/src/Microsoft.VisualBasic.Core/tests/FinancialTests.cs:line 40
```

Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F~2F/20190721.5/workItem/Microsoft.VisualBasic.Core.Tests/analysis/xunit/Microsoft.VisualBasic.Tests.FinancialTests~2FDDB_Default
