### ISSUE TITLE
SslStream.AuthenticateAsClient hangs forever on linux-arm

### ISSUE THREAD

**Issue by NiklasANCO** [dotnet/corefx#39475]
There seems to be an issue with SslStream on arm-linux platform i have tried publish with both netcore 2.2 and the .net core 3.0 preview 6, same result.

```c#
private string Connect() {
            Console.WriteLine("Establing TCP Connection.");
            _tcpc = new TcpClient(_server, _port);
            _ssl = new SslStream(_tcpc.GetStream(), false);
            Console.WriteLine("SSL Handshake trying to validate certificate");
            System.Net.ServicePointManager.ServerCertificateValidationCallback = (sender, certificate, chain, errors) => true;
            try
            {
                _ssl.AuthenticateAsClientAsync(_server).Wait();
            }
            catch (AuthenticationException e) {
                Console.WriteLine("Exception: {0}", e.Message);
            }
            //
            //Reset State
            _lastReqPrefix = null;
            _reqCount = 1;
            //
            return ReadServerGreeting();
        }
```

The call to _ssl.AuthenticateAsClientAsync(_server).Wait(); just hangs forever, no exception is thrown.

I'm trying to run this on Raspbian GNU/Linux 9

**Comment by davidsh** [comment]
@wfurt

**Comment by wfurt** [comment]
We have tests running on Debian9 and that should be close to Raspbian and cover basic functionality. Do you connect to public server with proper CA or is that something self-signed/internal?   
Also note that ServicePointManager has no functionality on Core. Do you have same code running successfully on x64 Linux?

**Comment by NiklasANCO** [comment]
The server is publicly available, Certificate should be trusted (DigiCert) also installed the root certifcate on the Raspberry PI, Even if it was not trusted i would expect it to throw some sort of exception instead of just never returning from the call to AuthenticateAsClient.

I developed and tested the application on Win10, but no success on the pi, after adding Console.WriteLine statements all around i localized the line causing the problem and i tried to circumvent it using different overloads of SslStream constructor and AuthenticateAsClient and the Async version, also as a final desperate attempt i throwed the ServicePointManager thing in the mix.

I made a cleaner example for the sake of debugging:

`static void Main(string[] args)
        {
            Console.WriteLine("Establishing TCP Connection");
            TcpClient tcpc = new TcpClient(_server, _port);
            SslStream ssl = new SslStream(tcpc.GetStream());

            Console.WriteLine("Trying to validate certificate");
            try
            {
                ssl.AuthenticateAsClient(_server);
            }
            catch (Exception ex) {
                Console.WriteLine("Exception: {0}", ex.Message);
            }

            Console.WriteLine("Reading greeting from server:");
            ssl.Flush();
            byte[] buffer = new byte[2048];
            int readBytes = ssl.Read(buffer, 0, 2048);
            string serverGreeting = Encoding.ASCII.GetString(buffer, 0, readBytes);
            Console.WriteLine(serverGreeting);

            Console.WriteLine("Press enter to quit");
            ssl.Close();
            tcpc.Close();
        }`

I have tried publishing and running on following platforms:
Win10:
Gets to "Press enter to quit"

Linux-x64 (Ubuntu 10.04.6 LTS)
Gets to "Press enter to quit"

linux-arm (Raspbian GNU/Linux 9)
Gets to: "Trying to validate certificate"
(Kept it open for 30 minutes)

**Comment by davidsh** [comment]
@krwq Can you help with this one?

**Comment by krwq** [comment]
@davidsh yes, will see what I can do.

@NiklasANCO does the same happen when you create the other endpoint with .NET?

> ```csharp
> System.Net.ServicePointManager.ServerCertificateValidationCallback = (sender, certificate, chain, errors) => true;
> ```

could you try instead using:

`AuthenticateAsClientAsync` + `SslClientAuthenticationOptions.RemoteCertificateValidationCallback`?

I'll see if I can repro on my box once I'm done with the other issue.

**Comment by krwq** [comment]
I've tried running following test on my Raspberry PI (Raspbian) and everything is working.

Server code:

```csharp
using System;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.Security;
using System.Net.Sockets;
using System.Threading;
using System.Threading.Tasks;
using System.Security.Cryptography.X509Certificates;

namespace test_client
{
    class Program
    {
        // This is a dump of
        // https://github.com/dotnet/corefx/blob/82e49157906d6c9c1ed7013e99d50dca74e7fafc/src/Common/tests/System/Net/Configuration.Certificates.cs#L44
        static string s_cert = @"MIIQkwIBAzCCEE8GCSqGSIb3DQEHAaCCEEAEghA8MIIQODCCCi8GCSqGSIb3DQEHAaCCCiAEggocMIIKGDCCChQGCyqGSIb3DQEMCgECoIIJfjCCCXowHAYKKoZIhvcNAQwBAzAOBAjgTnSQpVh4egICB9AEgglYiL4T7OLHDcmqEVvOduj5wGl5pvin6C05nkK3nQS/KCnBKwLXCjM5u82DOTtbZdOC/q8pkmRtOJyc8qr6YCWdUsKcL79SoBYGKQAGTVNRs9cu7eXeCn+SBKn0pyIwHvwffawteU2hOibKN9FteszHHq6W7sn29pAmX/GR6lujPV6hNkTSrT0cU+qknap65KcHA+CbTCYKbMIjJO3EkaJXh9TtviUyqZVPkmi/USN1mVbL02vX2vr6DjkQA7ki2K2yrcf3WUXgbrCZ6awZ73VjMkSFhyvGmXa0alki8kQh1VVURVD7OxZqrlNv1Hx2Tx0P/Pj4AQpd/ZH2CbfDzWFO3uSWHnvU/bwqKE33PolcTmyWpnFXn4DtMBRyFDp4PkXgZbHU7CxTJzAL9ON8Tc/2vlcKfzF7Pnsxt1p2HyvFVaocDkpV9MNY7WX8sm/7ktlKhm4KvXgOd57n7w5JMsSAchc4wMh8sp2TwG4T3gKauHTJ7fYEjn4t2YfK8llDR2l5IMziMjq6PsjnxGopJoLaB2FDiGh8wG3N5DDA4UOMLzIyVGiySey0CVPrxgN7rJGeX9soyUwCvwvKurnGM++1hp5HOIXETiM2C2X1ERwAf9xwS0LvLoPhcVo8E0mHFCvohj7y1ARonBBEC5rQ5RHj76gQkiXoDFQO0Bc6dyP6KFbrZ/0YmpYamTieBn/+5RHIlyyRxrX6n9CGXligYPYdtOo0b5+Qs/hoWsUtkISJqMsDGgD6/d0xfuRSylAn5OYKtkMTOw36sNOhtbFDlAz+JPGbSO8mikLtHWuXilBYoAT2eo8gDDxrSXplwZP64T+fKd7VEKf5Rh1HYcMjkoS+yNhCadNAX+XkZ/1E5017wmjy1zrlwqJrDzuT2PWJgkkT7e3CULHnJpEICgxAMxAAco9EDe4rU1XVfBXYRdAmg9xkFf9xAtdk98Rd63pJnNyx2rR1XATyI16ajkkKKOxUz3z2TKVxhknySEJrF8lql3UXuZYUsTpbHaXNcqSD6EiINDzlRULgWJUp4zoqVhXO4dXYyecFHwV7hmt9wRUeEojmizl+omFZfDpt4q9dym34lW/oEDVaXrMLJ0w2p1iXVKUYwKbsDPq7dcQfcKpejob9XpRaRTU46rNaKJoFpoz7BPgO+P5IxeaOZG6EKFNIrP9y1w1Z8y5/JgluwOf/u7hA24Y87gTF7UzGJ9VOGOTIlAGlSr6zEKagiB92PCBOhOJx8zQyX94FH0r6s4IHYHbw1bhbJm8kmCmGx1ljopYIcdTXHMcB4VThYgljFedvQc4OW1RH1pxbTz+/I0pj8gDHWOGpurw9IMCoyzQTLZ/Uj7yRkbkt2pVHhTPwk0qHVb/SFeMfpVjParNPMkTaT/Zu5zT7zsbqDuONyVODBXEZr2/L6DmZ+Y7NIx6szG80P/x+Il67C0lH+SuX8A/8CWM5nBU943IiWYaqAcK5u/kabI8fQcmR6QG8Frmp17tyHJUzg9T3YxZ+HF5s0bKrC87DCvBt0/nCvdNUEPlsgP1pKD1Vx9axOW4XCpIY3WwF4LI1wQq+w7aOcp7Erlyr///aAbNdvsIHe4E5hb1fMk2TJVOhmhfqmbmn2UVPfbwrV15K0jZkCNEvYHrbfpGVaOn8vshRoNPgCHWA5yUUBz6GvWjG5XrlMDlRiytLBiUsiYhedvTsYy6cEX3fB0Q8RlHb3XBMGH8vtLOtlsJRGrsnTX86+JoFWErwRoh9Svt5yTgfuEwvtC5GSmvFjuxHGc3TrisXYiHTtnx4USZpfHbtsAMXAgKooBXtvaLRJo2FDM0wCkPY2zjeae7CWsizeXuyPchOQncXS0JfZqSa3LCeCnkuce7HTREJ5X0gUmwk67K1PLw67gZTxivXR9w0g0Tbv0iOSQTmjxf06omanJYVhmlQkNDvhZeZBONGZP0SlW4lXsJQXDM791jM5ifPWIbTAoV+z752fI9E6vunP8dVVfYjhm7hdMHNiFNK/L7/EL5tMWqA10sjo0LWd87as/6vH2JWpXlw/hbTG3FDi6vgLJ13yvSfDsa64LYRcf9GTxprjdkh72FsTOhsoJbUiXmZJMdpIeNtlCOZELNXv+/dmRIKL5RkxTAGUfDBxqf1VB2I8OLM70nbCcJaUkxaylduXD36tD8j7mTw8cboKwKbEDGUGgnSRZo1n8OECxE4t/OevE5FiODHHDQ0Wz2Gdo5qz0zm4YGmangSm9Tczfxg31khrm4dcFT/6GFSBaKiETW//HoNXqLtTMRvygrJTb21pGb1SQrKHf8TV7NlwVbVkBLNXF6If5dfAhv0zYBKwv6CJupkROYIimDJy2vhxIX26C1FGvQDkAPT95eKu18zAcaFMbv+dmEemSnEldN+C8zGTSObxI4qqCLIu/Rq+soE4STIGauPKWBQtW16MW8GPgv8EiETRXcY6OXgNSf6DdrRadFRhK7ICAFPbt2sHWqWeSPN32/q4xPhVrthb+7ay6lZ515bQDqm9OTjbBMYmVtzRaIMrVgm5NIwL75WMuTmCfEhr7SDY5UREi8KhTSZdvKVo/TtMPe/4xFrWUskY+o7jLpj9kXRkjBYDGjPpq0VZaWla7Ak/M7RfLgv9sWnCUc2chwQPyXp8K5Li/TDREF+rMzdYpT1a4bK4tmr117zbS8ywEMr8uY2Z0zSlNq1lUbMfAm0W/7iv2RAZFjtmkI9maNYBaobY0/ck+9cNWwCQQyjuPdEkTso8D+YylL8Q4ODeVQoPvl0f9EXXgv5nAkiKtj28u5nCkfeVvJsnG+McyshAfHQY6zv2trlMvokPMyBzlw3Q8OEx0yV7D4biHTr6yMSS/lh3jxFqqQjZBLjtpmgyXjeY4323EaDWPsxOZslGkhmvf7UxiRgwzhOyyoZlzwyhnVLAo8mOspnGzcIrHa4LnmD3RWyKDYPe2CDxMTKmELN8AJs9/mCjKZG4CN2I9K+jAYBJOUrEbyul1RcR+NILIy4xdOara+JsVQOXaaN9mrpHxQpZnl5+erN1XEEwgMei5lSwbhMeruib6pJauM6t/eL6mZ1gmwAFyFpQc7o9BP4jp9falBDViKd4y/XWOLAzxe8ysU1uumh1B3C5Xc1dHARGLL39p1lSdEEae4LeLHdDwRccYuDWM2//UVRcUZDdrrJuclMbNFVV5TPFuKfS/T3XzGBgjATBgkqhkiG9w0BCRUxBgQEAQAAADBrBgkrBgEEAYI3EQExXh5cAE0AaQBjAHIAbwBzAG8AZgB0ACAARQBuAGgAYQBuAGMAZQBkACAAQwByAHkAcAB0AG8AZwByAGEAcABoAGkAYwAgAFAAcgBvAHYAaQBkAGUAcgAgAHYAMQAuADAwggYBBgkqhkiG9w0BBwGgggXyBIIF7jCCBeowggXmBgsqhkiG9w0BDAoBA6CCBUgwggVEBgoqhkiG9w0BCRYBoIIFNASCBTAwggUsMIIDFKADAgECAhB+a2qHSPQTjEo4S1By3aAMMA0GCSqGSIb3DQEBCwUAMC4xLDAqBgNVBAMMI3Rlc3RzZWxmc2lnbmVkc2VydmVyZWt1LmNvbnRvc28uY29tMB4XDTE3MDExNzE3Mzc1N1oXDTM1MDExODAwMDAwMFowLjEsMCoGA1UEAwwjdGVzdHNlbGZzaWduZWRzZXJ2ZXJla3UuY29udG9zby5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDQZOx5gbWe6UR2XmCUS22idxjtL4IpFdZMkW+AWoeU86SLsLypsnPioT84+GMQoTm7emhWLfvY/l1cWHMPjVMVEy2TcED0bsho9DH2YYKVj/df18tsUlbGaxOfV1A2+m9DgRnojeFSIx4nzEAMuoZgWbRWfyLMtkYB7qxrjH7FIym5tzPzXfkGzR2cYEBTq+QnXN8nwhiytdHv6vTJjiIyLsGhtRVis/+l1ObxIeuhAaUWmMxUaT858CRgDyDjv+MueXh53gWPBenbZAQQArY2XWdd910z1bSZwoRqjmAiAuksFZw+gxiEoxLfCkWbrgVGgv3gdkTpX+4EpYh5nD0q8CXx2pOcarL1JyehoiCKEtr+nJ5VJ0vEgKWBSxu4DLf9pWorF/52IJqM2KL+JMeGHF7xD8PKz1dmNX0CFvXwnPJDJ2JoF+wk5K2jF+LDnvpgteZizVmEaoRq85Tp4hGIYlZShXkdoTDfHEzaBl751SOwmhvXSbc1tLfSOlwulxENhROn2LgOzh3nhFO6fIOaYUMnZakrzubnIKSCLeG3BFdTCUHA/++2PxA1egk0C9RduILK9XYcwuNdVxBL3KKQi/Ikeqtf6PQehm6w0I3YEdSHZcKWR2Mq5QvlxK2gJZsbFBc9fGpTlqvT6t2vhzLafnIz+yBZpvx04UWqQhJfUQIDAQABo0YwRDATBgNVHSUEDDAKBggrBgEFBQcDATAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0OBBYEFExAlGJXwHJx1mYqsEtvvIgWkKCMMA0GCSqGSIb3DQEBCwUAA4ICAQBhayOpCRChyLHsiPQnpP1wKGjVwrNJZHV2Hi64wm9OFOv4CzaW/k12KUZrX0i1rl5+SighndyR7tM1fudrmJBL+9+GHdGGcLTaa/EJR1dUzCsHWdRcDwMDzR3Q3YqFZ6Apyx+G1iVMZR6EXudNFA2qyHkM8jVfShbbBKMH91d9CZtLxPKyl1KireFztqEFiLP9L4gU/GnAwuL1EVhElrSeEMScKChS3yxVOtstR9C+Slte/N6WxwvfIkwQ/aqVFe2fZ3ySE6DtlcNRR6VibweAuU/ZRsAqzlcggAO12Cmultq/9kx4FyqbH9hzEETag7Zf1gUC8SPrk0/O76+VaQWBMv58aTfj48USNX9OzQQ991kgAPtPta7t58xsu8vIpmw7zLxaj/3mNvmCunKbSmN91HlvX+jlN9OwOMTzwZ+CoeO/G/fVWKFnVmHl2p0SsTYeLyFuggNW5hEogFzj6B/mWhZa40gvm0HdyhS8Yx07WjRb4Oa2Rm7YISMat8S2M3JHEVYqNngcZ/yIyAGXPJv43yTuumsQ6lD/erNF0xyJBGLYR7j2C7nRiNPOowhlH1VksSVemPiQl49snMXGsu4PLyMg6gey3J+3f20fshjq5yMfgNRDMBk79MkoO4QfEe1npbyeHXlHsQSlSnpDe9DIEypl/aPfvfavwuMpuPeM/DGBijARBgkqhkiG9w0BCRQxBB4CAAAwEwYJKoZIhvcNAQkVMQYEBAEAAAAwYAYKKwYBBAGCNxEDRzFSBFBDAFIASQBTAFAATwBQAC0ARABFAFYAMgAuAHIAZQBkAG0AbwBuAGQALgBjAG8AcgBwAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAAADA7MB8wBwYFKw4DAhoEFAk2KZWDz3et08Ho/aYILCtJb61gBBTw+JhpGihc/eneLmnEutFOP7COXAICB9A=";
        static string s_certPwd = "testcertificate";

        static void Main(string[] args)
        {
            IPAddress ip = IPAddress.Parse("127.0.0.1");
            int port = 6789;
            TcpListener listener = new TcpListener(ip, port);
            listener.Start();

            Console.WriteLine("Waiting for connection...");
            try
            {
                using (TcpClient client = listener.AcceptTcpClient())
                using (X509Certificate2 cert = new X509Certificate2(Convert.FromBase64String(s_cert), s_certPwd))
                using (var tlsStream = new SslStream(client.GetStream(), leaveInnerStreamOpen: false))
                {
                    Console.WriteLine("SSL Handshake");

                    var options = new SslServerAuthenticationOptions()
                    {
                        ServerCertificate = cert,
                    };

                    tlsStream.AuthenticateAsServerAsync(options, CancellationToken.None).Wait();

                    Console.WriteLine("Having conversation...");
                    using (var sr = new StreamReader(tlsStream, leaveOpen: true))
                    using (var sw = new StreamWriter(tlsStream, leaveOpen: true))
                    {
                        sw.WriteLine("HELLO CLIENT");
                        sw.Flush();
                        Console.WriteLine(sr.ReadLine());

                        string request = sr.ReadLine();
                        if (request == "ADD")
                        {
                            int a = int.Parse(sr.ReadLine());
                            int b = int.Parse(sr.ReadLine());
                            sw.WriteLine((a + b).ToString());
                        }
                        else
                        {
                            Console.WriteLine($"CLIENT SENT INVALID REQUEST: {request}");
                        }
                    }
                }
            }
            finally
            {
                listener.Stop();
            }

            Console.WriteLine("Everything seem to be working.");
        }
    }
}
```

Client

```csharp
using System;
using System.IO;
using System.Net.Security;
using System.Net.Sockets;
using System.Threading;

namespace test_client
{
    class Program
    {
        static void Main(string[] args)
        {
            string server = "127.0.0.1";
            int port = 6789;

            using (var client = new TcpClient(server, port))
            using (var tlsStream = new SslStream(client.GetStream(), leaveInnerStreamOpen: false))
            {
                Console.WriteLine("SSL Handshake");

                var options = new SslClientAuthenticationOptions()
                {
                    TargetHost = server,
                    RemoteCertificateValidationCallback = (sender, certificate, chain, errors) => true,
                };

                tlsStream.AuthenticateAsClientAsync(options, CancellationToken.None).Wait();

                Console.WriteLine("Having conversation...");
                using (var sr = new StreamReader(tlsStream, leaveOpen: true))
                using (var sw = new StreamWriter(tlsStream, leaveOpen: true))
                {
                    sw.WriteLine("HELLO SERV");
                    Console.WriteLine(sr.ReadLine());
                    sw.WriteLine("ADD");
                    sw.WriteLine("5");
                    sw.WriteLine("9");
                    sw.Flush();
                    string response = sr.ReadLine();
                    if (response != "14")
                    {
                        Console.WriteLine($"SERVER GAVE INCORRECT ANSWER: {response}");
                        return;
                    }
                }
            }

            Console.WriteLine("Everything seem to be working.");
        }
    }
}
```

and both client and server seem to be working correctly and do not hang.

@NiklasANCO could you try running above on your arm32?

**Comment by krwq** [comment]
Marking as Future since I don't believe this is a product issue but will leave it open until we finish troubleshooting

**Comment by davidsh** [comment]
@krwq 

What happens if you remove this code from your repro:

```c#
RemoteCertificateValidationCallback = (sender, certificate, chain, errors) => true,
```

The bug was originally behaving that way.  The use of the ServicePointManager class in the original repro was a no-op. So, I'm wondering whether we still have a product bug that results in a hang instead of getting a valid exception due to the server certificate not being trusted by the client?

**Comment by krwq** [comment]
@davidsh looks correct

server:

```
Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security.SslStream.FillBufferAsync[TReadAdapter](TReadAdapter adapter, Int32 minSize)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at test_client.Program.Main(String[] args) in /media/hdd1/mess/test/sslstream-networking/test-server/Program.cs:line 49
Aborted
```

client

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (The remote certificate is invalid according to the validation procedure.) ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at test_client.Program.Main(String[] args) in /media/hdd1/mess/test/sslstream-networking/test-client/Program.cs:line 27
---> (Inner Exception #0) System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---

Aborted
```

This line does not have any effect (still seeing error with it)

```csharp
System.Net.ServicePointManager.ServerCertificateValidationCallback = (sender, certificate, chain, errors) => true;
```

**Comment by krwq** [comment]
I was testing this with:

https://download.visualstudio.microsoft.com/download/pr/72ce4d40-9063-4a2e-a962-0bf2574f75d1/5463bb92cff4f9c76935838d1efbc757/dotnet-sdk-3.0.100-preview6-012264-linux-x64.tar.gz

**Comment by krwq** [comment]
@NiklasANCO could you do the test I pasted above and also share:

`dotnet --info` from the machine where you run or publish (if using `dotnet run` on ARM then this dotnet, if using `dotnet publish -r linux-arm` then dotnet which was publishing)

**Comment by NiklasANCO** [comment]
@krwq 
I found the issue, it was network related, 
The PI was on a separate network and there was a firewall interfering.
The TCP connection to the server was established but the client never receives a response to the client hello.

Apparently SslStream will just wait forever in this scenario, i tried confirming the same behavior on windows so it's not specific to linux-arm. 
also .Net Framework 4.6.1 has the same behavior so it's not specific to Core either.

But maybe it would be nice in the future to add some timeout exception when server is not responding to TLS/SSL client hello. ?

**Comment by krwq** [comment]
@NiklasANCO did you try passing CancellationToken to AuthenticateAsClientAsync (i.e. https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.-ctor?view=netframework-4.8#System_Threading_CancellationTokenSource__ctor_System_TimeSpan_ takes timeout and then you can get Token using https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.token?view=netframework-4.8).

Also TcpClient has SendTimeout and ReceiveTimeout properties. Could you verify if that works with you?

**Comment by NiklasANCO** [comment]
@krwq The cancellation token does'nt have any effect, it still keeps running forever.

The TcpClient timeouts doesn't work either if the timeout occurs after the call AuthenticateAsClientAsync, however if the TcpClient already timed out before making the call to AuthenticateAsClientAsync an exception is thrown.

**Comment by NiklasANCO** [comment]
@krwq Correction, The cancellation token does not work on Core 2.2
It works on 3.0 Preview 6 👍

**Comment by krwq** [comment]
@NiklasANCO glad it works on preview. Are you ok with closing this issue or do you think there is something left here?

**Comment by NiklasANCO** [comment]
@krwq 
It's fine to close the issue

**Comment by krwq** [comment]
Thanks for trying stuff out @NiklasANCO!
