### ISSUE TITLE
SendToRecvFromAsync_Datagram_UDP_UdpClient failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39492]
```
Windows.10.Amd64.ClientRS5.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Assert.True() Failure
Expected: True
Actual:   False
Stack Trace :
   at System.Net.Sockets.Tests.SendReceiveUdpClient.<>c__DisplayClass0_2.<<SendToRecvFromAsync_Datagram_UDP_UdpClient>b__1>d.MoveNext() in /_/src/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:line 1292
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 71
   at System.Net.Sockets.Tests.SendReceiveUdpClient.SendToRecvFromAsync_Datagram_UDP_UdpClient(IPAddress loopbackAddress) in /_/src/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:line 1301
--- End of stack trace from previous location where exception was thrown ---
```
cc: @wfurt

**Comment by davidsh** [comment]
Is this failure from a regular Win10 or UWP run?  It's hard to tell from this issue without the original CI link.

**Comment by stephentoub** [comment]
Forgot to paste the link:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39474~2Fmerge/test~2Ffunctional~2Fcli~2Fouterloop~2F//workItem/System.Net.Sockets.Tests

Looks like UWP:
```
C:\dotnetbuild\work\22821e78-486e-4c27-abd2-54d8c7447426\Work\7d4fa99f-fa77-4181-a6e8-7ac7b2f87636\Exec>XUnitRunnerUap System.Net.Sockets.Tests.dll -xml "C:\Users\runner\AppData\Local\Packages\5cd54353-3ed7-4a6e-a72f-db349f28867c_v52bfwc2c21ha\LocalState\System.Net.Sockets.Tests.xml" -nologo -nocolor -notrait category=nonuaptests -notrait category=nonwindowstests -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing  
```

**Comment by karelz** [comment]
UWP, closing for now. We can revisit later when we re-enable UWP runs.
