### ISSUE TITLE
"GroupsTurkish" RegEx test failing sporadically in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39497]
This test has been failing sporadically in CI, e.g.
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39491~2Fmerge/test~2Ffunctional~2Fcli~2F~2F/20190715.42/workItem/System.Text.RegularExpressions.Tests/analysis/xunit/System.Text.RegularExpressions.Tests.RegexGroupTests~2FGroupsTurkish
```
RedHat.7.Amd64.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.XunitException
Message :
Timed out after 60000ms waiting for remote process.
\tProcess ID: 7258
\tHandle: 924
Stack Trace :
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutor/RemoteInvokeHandle.cs:line 131
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutor/RemoteInvokeHandle.cs:line 55
   at System.Text.RegularExpressions.Tests.RegexGroupTests.GroupsTurkish() in /_/src/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 722
```
cc: @ViktorHofer

**Comment by ViktorHofer** [comment]
I still have no idea how this specific test could hang but the other similar Group tests don't. This might be happen when the system is on high cpu and overloaded with work? At this point I'm just guessing.

**Comment by jkotas** [comment]
Likely dup of https://github.com/dotnet/corefx/issues/41619

**Comment by stephentoub** [comment]
Closing as likely dup of https://github.com/dotnet/coreclr/issues/27128
