### ISSUE TITLE
HTTP2: 'FRAME_SIZE_ERROR' being thrown with content with more multi parts or the server just getting hang

### ISSUE THREAD

**Issue by Anipik** [dotnet/corefx#39512]
Command
```
dotnet run -n 10 -maxContentLength 4000 -http 2.0 -ops 7 -numParameters 105
```

The server or the client just hangs after sending first set of requests
```

[15-07-2019 15:56:27] Total: 3,283
        POST Multipart Data           Success: 3,273    Fail: 10

[15-07-2019 15:56:28] Total: 3,996
        POST Multipart Data           Success: 3,986    Fail: 10

[15-07-2019 15:56:29] Total: 3,996
        POST Multipart Data           Success: 3,986    Fail: 10

[15-07-2019 15:56:30] Total: 3,996
        POST Multipart Data           Success: 3,986    Fail: 10

[15-07-2019 15:56:31] Total: 3,996
        POST Multipart Data           Success: 3,986    Fail: 10

[15-07-2019 15:56:32] Total: 3,996
        POST Multipart Data           Success: 3,986    Fail: 10

[15-07-2019 15:56:33] Total: 3,996
        POST Multipart Data           Success: 3,986    Fail: 10

[15-07-2019 15:56:34] Total: 3,996
        POST Multipart Data           Success: 3,986    Fail: 10
```
whereas in 1.1

```
Starting server.
Starting 10 client workers.
[15-07-2019 15:57:01] Total: 3,175
        POST Multipart Data           Success: 3,181    Fail: 0

[15-07-2019 15:57:02] Total: 7,493
        POST Multipart Data           Success: 7,511    Fail: 0

[15-07-2019 15:57:03] Total: 11,852
        POST Multipart Data           Success: 11,863   Fail: 0

[15-07-2019 15:57:04] Total: 16,827
        POST Multipart Data           Success: 16,834   Fail: 0

[15-07-2019 15:57:05] Total: 21,892
        POST Multipart Data           Success: 21,969   Fail: 0

[15-07-2019 15:57:06] Total: 26,885
        POST Multipart Data           Success: 27,010   Fail: 0

[15-07-2019 15:57:07] Total: 31,781
        POST Multipart Data           Success: 31,800   Fail: 0

[15-07-2019 15:57:08] Total: 36,654
        POST Multipart Data           Success: 36,666   Fail: 0

[15-07-2019 15:57:09] Total: 41,844
        POST Multipart Data           Success: 41,844   Fail: 0

```

The following exception also gets thrown sometimes in 2.0
```
Error from iteration 339 (POST Multipart Data) in task 1 with 3272 successes / 10 fails:
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.Net.Http.Http2ProtocolException: The HTTP/2 request failed with protocol error 'FRAME_SIZE_ERROR' (0x6).
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Program.<>c__DisplayClass1_0.<<Run>b__9>d.MoveNext() in C:\git\corefx\src\System.Net.Http\tests\StressTests\HttpStress\Program.cs:line 269
--- End of stack trace from previous location where exception was thrown ---
   at Program.<>c__DisplayClass1_4.<<Run>b__43>d.MoveNext() in C:\git\corefx\src\System.Net.Http\tests\StressTests\HttpStress\Program.cs:line 63
```

cc @stephentoub @danmosemsft

**Comment by Anipik** [comment]
Another exception getting thrown
Command dotnet run -n 10 -maxContentLength 4000 -http 2.0 -ops 7 -numParameters 200


```
        POST Multipart Data           Success: 6,653    Fail: 1

Error from iteration 2171 (POST Multipart Data) in task 5 with 6893 successes / 2 fails:
System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: The request was aborted.
   at System.Net.Http.Http2Connection.AcquireWriteLockAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.StartWriteAsync(Int32 writeBytes, CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendStreamDataAsync(Int32 streamId, ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.Http2Stream.SendDataAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   at System.Net.Http.MultipartContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   at System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Program.<>c__DisplayClass1_0.<<Run>b__9>d.MoveNext() in C:\git\corefx\src\System.Net.Http\tests\StressTests\HttpStress\Program.cs:line 269
--- End of stack trace from previous location where exception was thrown ---
   at Program.<>c__DisplayClass1_4.<<Run>b__43>d.MoveNext() in C:\git\corefx\src\System.Net.Http\tests\StressTests\HttpStress\Program.cs:line 634
```

**Comment by Anipik** [comment]
Another Different exception 
```
Error from iteration 246 (POST Multipart Data) in task 5 with 2389 successes / 20 fails:
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely, with at least 6787 additional bytes expected.
   at System.Net.Http.Http2Connection.ReadAtLeastAsync(Stream stream, Memory`1 buffer, Int32 minReadBytes)
   at System.Net.Http.Http2Connection.EnsureIncomingBytesAsync(Int32 minReadBytes)
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Program.<>c__DisplayClass1_0.<<Run>b__9>d.MoveNext() in C:\git\corefx\src\System.Net.Http\tests\StressTests\HttpStress\Program.cs:line 269
--- End of stack trace from previous location where exception was thrown ---
   at Program.<>c__DisplayClass1_4.<<Run>b__43>d.MoveNext() in C:\git\corefx\src\System.Net.Http\tests\StressTests\HttpStress\Program.cs:line 634
```

**Comment by Anipik** [comment]
closing this issue as it no longer repros with latest sdk
