### ISSUE TITLE
Test failure : System.Net.Tests.HttpWebRequestTest/PreAuthenticate_SetAndGetBooleanResponse_ValuesMatch(remoteServer: http://corefx-net-http11.azurewebsites.net/Echo.ashx) 

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#39581]
Test `System.Net.Tests.HttpWebRequestTest/PreAuthenticate_SetAndGetBooleanResponse_ValuesMatch(remoteServer: http://corefx-net-http11.azurewebsites.net/Echo.ashx) ` has failed.

Message :
```
System.Net.WebException : The requested name is valid, but no data of the requested type was found. The requested name is valid, but no data of the requested type was found.
---- System.Net.Http.HttpRequestException : The requested name is valid, but no data of the requested type was found.
-------- System.Net.Sockets.SocketException : The requested name is valid, but no data of the requested type was found.
```
Stack Trace :
```
  at System.Net.HttpWebRequest.GetResponse() in /_/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1004
   at System.Net.Tests.HttpWebRequestTest.PreAuthenticate_SetAndGetBooleanResponse_ValuesMatch(Uri remoteServer) in /_/src/System.Net.Requests/tests/HttpWebRequestTest.cs:line 656
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 73
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 626
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 666
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 332
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 524
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 33
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in /_/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 553
   at System.Net.HttpWebRequest.SendRequest() in /_/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1217
   at System.Net.HttpWebRequest.GetResponse() in /_/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1000
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 54
```
Build: -[20190717.35](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F~2F/20190717.35)(Master)

Failing configuration:

- Windows.10.Arm64.Open-arm64-Release

Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F~2F/20190717.35/workItem/System.Net.Requests.Tests/analysis/xunit/System.Net.Tests.HttpWebRequestTest~2FPreAuthenticate_SetAndGetBooleanResponse_ValuesMatch(remoteServer:%20http:~2F~2Fcorefx-net-http11.azurewebsites.net~2FEcho.ashx)

**Comment by davidsh** [comment]
>System.Net.WebException : The requested name is valid, but no data of the requested type was found. The requested name is valid, but no data of the requested type was found.

There are currently Azure infrastructure issues with DNS right now.  It is affecting network traffic in CI.  So, this is a transient error.

**Comment by ViktorHofer** [comment]
Happened again: https://dev.azure.com/dnceng/public/_build/results?buildId=353190&view=ms.vss-test-web.build-test-results-tab&runId=10640704&resultId=157169&paneView=debug

Configuration: `netcoreapp-OSX-Debug-x64-OSX.1013.Amd64.Open`

```
System.Net.WebException : An error occurred while sending the request. Unable to read data from the transport connection: Connection reset by peer.\n---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\n-------- System.IO.IOException : Unable to read data from the transport connection: Connection reset by peer.\n------------ System.Net.Sockets.SocketException : Connection reset by peer

  at System.Net.HttpWebRequest.GetResponse() in /_/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1004
   at System.Net.Tests.HttpWebRequestTest.PreAuthenticate_SetAndGetBooleanResponse_ValuesMatch(Uri remoteServer) in /_/src/System.Net.Requests/tests/HttpWebRequestTest.cs:line 656
----- Inner Stack Trace -----
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs:line 726
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 566
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 537
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 33
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in /_/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 553
   at System.Net.HttpWebRequest.SendRequest() in /_/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1217
   at System.Net.HttpWebRequest.GetResponse() in /_/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1000
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1110
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token) in /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1076
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 1478
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 1356
   at System.Net.Http.HttpConnection.FillAsync() in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs:line 1437
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs:line 1343
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs:line 513
```

**Comment by Anipik** [comment]
failed in the rolling build. https://dev.azure.com/dnceng/public/_build/results?buildId=353186&view=ms.vss-test-web.build-test-results-tab&runId=10640812&resultId=161412&paneView=debug

**Comment by ViktorHofer** [comment]
@davidsh would loopback be sufficient for what we are testing here? (PreAuthenticate)

**Comment by davidsh** [comment]
>@davidsh would loopback be sufficient for what we are testing here? (PreAuthenticate)

Maybe. However, the loopback server might need more enhancements to support the authentication that those tests use.

**Comment by AriNuer** [comment]
similar test `System.Net.Tests.HttpWebRequestTest.PreAuthenticate_SetAndGetBooleanResponse_ValuesMatch` failed.

```

Error message
System.Net.WebException : Resource temporarily unavailable Resource temporarily unavailable
---- System.Net.Http.HttpRequestException : Resource temporarily unavailable
-------- System.Net.Sockets.SocketException : Resource temporarily unavailable

Stack trace
   at System.Net.HttpWebRequest.GetResponse() in /_/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1069
   at System.Net.Tests.HttpWebRequestTest.PreAuthenticate_SetAndGetBooleanResponse_ValuesMatch(Uri remoteServer) in /_/src/System.Net.Requests/tests/HttpWebRequestTest.cs:line 739
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 74
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 625
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 665
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 331
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 523
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 33
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in /_/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 553
   at System.Net.HttpWebRequest.SendRequest() in /_/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1221
   at System.Net.HttpWebRequest.GetResponse() in /_/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1065
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectEventArgs.OnCompleted(SocketAsyncEventArgs _) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 116
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state) in /_/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs:line 424
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 183
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 132
   at System.Net.Sockets.SocketAsyncEventArgs.FinishConnectByNameAsyncFailure(Exception exception, Int32 bytesTransferred, SocketFlags flags) in /_/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs:line 650
   at System.Net.Sockets.MultipleConnectAsync.AsyncFail(Exception e) in /_/src/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs:line 339
   at System.Net.Sockets.MultipleConnectAsync.Fail(Boolean sync, Exception e) in /_/src/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs:line 305
   at System.Net.Sockets.MultipleConnectAsync.DoDnsCallback(IAsyncResult result, Boolean sync) in /_/src/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs:line 151
   at System.Net.Sockets.MultipleConnectAsync.DnsCallback(IAsyncResult result) in /_/src/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs:line 86
   at System.Threading.Tasks.TaskToApm.TaskAsyncResult.InvokeCallback() in /_/src/Common/src/CoreLib/System/Threading/Tasks/TaskToApm.cs:line 108
   at System.Threading.Tasks.AwaitTaskContinuation.<>c.<.cctor>b__17_0(Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/TaskContinuation.cs:line 661
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 183
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/TaskContinuation.cs:line 692
   at System.Threading.Tasks.AwaitTaskContinuation.Run(Task task, Boolean canInlineContinuationTask) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/TaskContinuation.cs:line 576
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 3251
   at System.Threading.Tasks.Task.FinishContinuations() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 3213
   at System.Threading.Tasks.Task.FinishStageThree() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2103
   at System.Threading.Tasks.Task.FinishStageTwo() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2073
   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 1977
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2272
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2254
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2239
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 662
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() in /_/src/System.Private.CoreLib/src/System/Threading/ThreadPool.CoreCLR.cs:line 29
--- End of stack trace from previous location ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 55
```

**Build:**[20191017.83](https://dnceng.visualstudio.com/public/_build/results?buildId=392683)(Master)

**Queue name:**
netcoreapp-Linux-Release-arm64-(Alpine.38.Arm64.Open)Ubuntu.1604.Arm64.Docker.Open

**Details:**
https://dnceng.visualstudio.com/public/_build/results?buildId=392683&view=ms.vss-test-web.build-test-results-tab&runId=12198294&resultId=127830&paneView=debug

**Comment by ViktorHofer** [comment]
Failed again: https://dnceng.visualstudio.com/public/_build/results?buildId=392683&view=ms.vss-test-web.build-test-results-tab&runId=12198294&resultId=127830&paneView=debug
