### ISSUE TITLE
RSASSA-PSS certificates do not work with RSACertificateExtensions.GetRSAPublicKey

### ISSUE THREAD

**Issue by vcsjones** [dotnet/corefx#39628]
If a certificate has a key algorithm of RSASSA-PSS (1.2.840.113549.1.1.10) then `RSACertificateExtensions.GetRSAPublicKey` will return null.

Example certificate:

<pre>
-----BEGIN CERTIFICATE-----
MIIDyzCCAoKgAwIBAgIUTPlMx/cRPgsXnfHOd78XAfzUgeEwPgYJKoZIhvcNAQEK
MDGgDTALBglghkgBZQMEAgGhGjAYBgkqhkiG9w0BAQgwCwYJYIZIAWUDBAIBogQC
AgDeMEUxCzAJBgNVBAYTAlVTMREwDwYDVQQIDAhWaXJnaW5pYTETMBEGA1UEBwwK
QWxleGFuZHJpYTEOMAwGA1UECgwFS2V2aW4wHhcNMTkwNzE5MTk1MzQ5WhcNMTkw
ODE4MTk1MzQ5WjBFMQswCQYDVQQGEwJVUzERMA8GA1UECAwIVmlyZ2luaWExEzAR
BgNVBAcMCkFsZXhhbmRyaWExDjAMBgNVBAoMBUtldmluMIIBIDALBgkqhkiG9w0B
AQoDggEPADCCAQoCggEBANAo6q3gwu9X9otBA1FNGxEz57CGls8hL+9px+SRKMQv
fjJP6xU2r4+99/bpNFGeqiXnYkk1L4SI7OyK/WKyZLHfkJH1rI9J46LtA54Ykb1A
Lc8opMtgCM8rYNUipsKM+hnQLUoiBqm4WjWYmhocemLVVmEgudgiFW7+y2r2ey2h
XUD1Wdn3USzTMMZak86CMfD6uB3V8mT5bHg9014jqQabQuQBfeg2EEqBkgAvK0Cm
+uLHeRBnuIHPfmf5YV2TvE/7oSzl0Z2W+V+2z4HHWNHa+KDPI9dUg/9KYvD0I/iZ
YN9JV9VNG0rlYg3+FiYgtkjjyMweGYhT60QeOoOldrECAwEAAaNTMFEwHQYDVR0O
BBYEFEUdSmnSA8ddQkVOnY2NplXZ89MVMB8GA1UdIwQYMBaAFEUdSmnSA8ddQkVO
nY2NplXZ89MVMA8GA1UdEwEB/wQFMAMBAf8wPgYJKoZIhvcNAQEKMDGgDTALBglg
hkgBZQMEAgGhGjAYBgkqhkiG9w0BAQgwCwYJYIZIAWUDBAIBogQCAgDeA4IBAQBf
kYe0Ezq1ZYCEL0BSr7eXYIdDxX4//KE9BqdDMHP1Ia2PfODM1xEFsulxXiJCG4Zq
ZyDqJXgPRjaj9EtU/H8Sth66qhN+/qY0UX7T7dAWCeUUtzCJGB1EuFd2Li2+Tlkp
OftsVtXCYO5/q0dsdqHzxWjrAiwnyV+JqRR9ZqxJ7ntZKJXx+F/QRUX/saRV9kdh
bkmYxNpjCPzcHsvg7SDt7Vzw5jzfwLv3HpEFO74I+HBmtpa8Qbj7QhU8xqyGUBd2
TC/0ch3vAeWZ3gUr55oLrgb5Ml+uVng8aRUXZWI2YhFBGSBbSRvK2f4OLpcsCrNU
s5Qhn1EZQTQLfa6IecfS
-----END CERTIFICATE-----
</pre>

While these certificates are rare, they aren't entirely unheard of.

**Comment by vcsjones** [comment]
Ah, this is Linux. Not sure about Windows. Will check there later.

**Comment by bartonjs** [comment]
Presumably just an OID needs to be added to an if?

**Comment by vcsjones** [comment]
>Presumably just an OID needs to be added to an if?

Well, a few places.

Getting `GetRSAPublicKey` working is as straight forward as you suspected, but it breaks `GetRSAPrivateKey` (which used to return null). Seeing what it would take to fix, but the error is

<details>
<summary><code>Interop+Crypto+OpenSslCryptographicException : error:0607907F:digital envelope routines:EVP_PKEY_get0_RSA:expecting an rsa key</summary></code>
<pre>
Stack Trace:
/code/personal/corefx/src/System.Security.Cryptography.OpenSsl/src/System/Security/Cryptography/RSAOpenSsl.cs(69,0): at System.Security.Cryptography.RSAOpenSsl..ctor(SafeEvpPKeyHandle pkeyHandle)
/code/personal/corefx/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/OpenSslX509CertificateReader.cs(477,0): at Internal.Cryptography.Pal.OpenSslX509CertificateReader.GetRSAPrivateKey()
/code/personal/corefx/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/CertificateExtensionsCommon.cs(58,0): at Internal.Cryptography.Pal.CertificateExtensionsCommon.GetPrivateKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
/code/personal/corefx/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/RSACertificateExtensions.cs(29,0): at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.GetRSAPrivateKey(X509Certificate2 certificate)
/code/personal/corefx/src/System.Security.Cryptography.X509Certificates/tests/PfxTests.cs(411,0): at System.Security.Cryptography.X509Certificates.Tests.PfxTests.RsaPssKeyAlgorithmIdentifier_PrivateKey()
</pre></details>

**Comment by bartonjs** [comment]
Hm.  What does EVP_PKEY_base_id say? I'm guessing 19 (and a happy key is 6), meaning it returned EVP_PKEY_RSA2 (aka NID_rsa) instead of EVP_PKEY_RSA (aka NID_rsaEncryption).

```C
if (EVP_PKEY_base_id(pkey) == EVP_PKEY_RSA2)
{
    RSA* rsa = (RSA*)(void*)EVP_PKEY_get0(pkey);
    RSA_up_ref(rsa);
    return rsa;
}
```

in CryptoNative_EvpPkeyGetRsa, maybe?

**Comment by bartonjs** [comment]
Since this isn't a regression, and 3.0 is now in "ask mode", moving to 5.0.  (If the fix is straightforward it can likely make 3.1)
