### ISSUE TITLE
HTTP2: HttpClient fails streaming large amount of data with server flow control

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#39639]
Repro:
1. `git clone https://github.com/JamesNK/grpc-dotnet.git`
2. `git checkout jamesnk/client-stream-backpressure-test`
3. `dotnet test test\FunctionalTests --filter Name~ClientStream_SendLargeFileBatchedAndRecieveLargeFileBatched_Success`

Logic in the test is like:
1. Client streams 1 GB of data in 64 KB chunks to the server as fast as it can
2. Server reads chunks with 10 ms delay

The client will eventually fail, sending RST_STREAM (CANCEL) to the server.

```
    at TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
    at Http2Stream.SendDataAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
    at StreamExtensions.WriteMessageAsync[TMessage](Stream stream, ILogger logger, TMessage message, Action`2 serializer, String grpcEncoding, Nullable`1 maximumMessageSize, CancellationToken cancellationToken) in StreamExtensions.cs line: 261
    at HttpContentClientStreamWriter`2.WriteAsyncCore(TRequest message) in HttpContentClientStreamWriter.cs line: 129
    at TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in TaskExtensions.cs line: 82
    at StreamingTests.ClientStream_SendLargeFileBatchedAndRecieveLargeFileBatched_Success() in StreamingTests.cs line: 107
```

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013317
 Commit:    9cc55027f1
```

**Comment by JamesNK** [comment]
![image](https://user-images.githubusercontent.com/303201/61573934-f9c57200-ab0a-11e9-85cc-6308b1e73fdc.png)

**Comment by stephentoub** [comment]
> The client will eventually fail, sending RST_STREAM (CANCEL) to the server.

Have you changed HttpClient's default Timeout to something other than 100 seconds?  If the server is reading 1GB of data in 64K chunks, at the rate of one 64K chunk every 10ms, it's going to take the server at least 163 seconds to read the whole thing.

**Comment by JamesNK** [comment]
Yeah it's the timeout. Thanks.
