### ISSUE TITLE
[System.Globalization] TestLocaleAlternateSortOrder failed (local build)

### ISSUE THREAD

**Issue by Maxwe11** [dotnet/corefx#3968]
```
  Discovering: System.Globalization.Tests
  Discovered:  System.Globalization.Tests
  Starting:    System.Globalization.Tests
     System.Globalization.Tests.CompareInfoTest.TestLocaleAlternateSortOrder(locale: "de-DE", string1: "њ", string2: "UE", expected: -1) [FAIL]
        Assert.Equal() Failure
        Expected: -1
        Actual:   1
        Stack Trace:
           E:\Workspace\github\corefx\src\System.Globalization\tests\CompareInfo\compareinfo.cs(137,0): at System.Globalization.Tests.CompareInfoTest.TestLocaleAlternateSortOrder(String locale, String string1, String string2, Int32 expected)
     System.Globalization.Tests.CompareInfoTest.TestLocaleAlternateSortOrder(locale: "de-DE_phoneb", string1: "њ", string2: "UE", expected: 0) [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   1
        Stack Trace:
           E:\Workspace\github\corefx\src\System.Globalization\tests\CompareInfo\compareinfo.cs(137,0): at System.Globalization.Tests.CompareInfoTest.TestLocaleAlternateSortOrder(String locale, String string1, String string2, Int32 expected)
  Finished:    System.Globalization.Tests

  === TEST EXECUTION SUMMARY ===
     System.Globalization.Tests  Total: 1145, Errors: 0, Failed: 2, Skipped: 0, Time: 6,192s
```

**Comment by steveharter** [comment]
It this failing on Windows, or Linux? It is a known issue on Linux

**Comment by Maxwe11** [comment]
Win 8.1 x64

**Comment by Maxwe11** [comment]
same on Win10 x64

**Comment by karelz** [comment]
We need someone to debug it. It might be specific to machines in special Culture.

**Comment by tarekgh** [comment]
We already cleaned up the tests in the commit https://github.com/dotnet/corefx/commit/0672efd9aac88231d83dbd323cd5ceb5ad62b654 and nothing should be failing now.
