### ISSUE TITLE
MutexTests.AbandonExisting test failed in Windows release CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39694]
```
    System.Threading.Tests.MutexTests.AbandonExisting(name: "Global\\42cb77c2b3b44cdfbbd21393f3911b15", waitType: WaitAny, waitCount: 3, notAbandonedWaitIndex: 2, isNotAbandonedWaitObjectSignaled: True, abandonDuringWait: False) [FAIL]
      System.AggregateException : One or more errors occurred. (Result: 2 (Assert.Throws() Failure
      Expected: typeof(System.Threading.AbandonedMutexException)
      Actual:   (No exception was thrown)))
      ---- System.AggregateException : Result: 2 (Assert.Throws() Failure
      Expected: typeof(System.Threading.AbandonedMutexException)
      Actual:   (No exception was thrown))
      -------- Assert.Throws() Failure
      Expected: typeof(System.Threading.AbandonedMutexException)
      Actual:   (No exception was thrown)
      Stack Trace:
        /_/src/Common/tests/System/Threading/ThreadTestHelpers.cs(50,0): at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass4_0.<CreateGuardedThread>b__1()
        /_/src/Common/tests/System/Threading/ThreadTestHelpers.cs(58,0): at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass4_0.<CreateGuardedThread>b__2()
        /_/src/Common/tests/System/Threading/ThreadTestHelpers.cs(108,0): at System.Threading.Tests.ThreadTestHelpers.RunTestInBackgroundThread(Action test)
        /_/src/System.Threading/tests/MutexTests.cs(241,0): at System.Threading.Tests.MutexTests.AbandonExisting(String name, WaitHandleWaitType waitType, Int32 waitCount, Int32 notAbandonedWaitIndex, Boolean isNotAbandonedWaitObjectSignaled, Boolean abandonDuringWait)
        ----- Inner Stack Trace -----
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/AssertExtensions.cs(108,0): at System.AssertExtensions.Throws[TException,TResult](Func`1 func)
        /_/src/System.Threading/tests/MutexTests.cs(315,0): at System.Threading.Tests.MutexTests.<>c__DisplayClass13_0.<AbandonExisting>b__0()
        /_/src/Common/tests/System/Threading/ThreadTestHelpers.cs(43,0): at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass4_0.<CreateGuardedThread>b__0()
        ----- Inner Stack Trace -----
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/AssertExtensions.cs(85,0): at System.AssertExtensions.Throws[TException,TResult](Func`1 func)
```
cc: @kouvel

**Comment by stephentoub** [comment]
Failed again here:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39725~2Fmerge/test~2Ffunctional~2Fcli~2F~2F/20190724.20/workItem/System.Threading.Tests/analysis/xunit/System.Threading.Tests.MutexTests~2FAbandonExisting(name:%20null,%20waitType:%20WaitAny,%20waitCount:%203,%20notAbandonedWaitIndex:%201,%20isNotAbandonedWaitObjectSigna)

**Comment by stephentoub** [comment]
Again here:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39773~2Fmerge/test~2Ffunctional~2Fcli~2F~2F/20190725.26/workItem/System.Threading.Tests/analysis/xunit/System.Threading.Tests.MutexTests~2FAbandonExisting(name:%20%5C%22Global%5C%5C%5C%5Cbe02762bd1f34588b038d8651d574a4c%5C%22,%20waitType:%20WaitAny,%20waitCount:%203,%20notAbandonedW)
