### ISSUE TITLE
Color.NonRedirectedOutputDoesUseAnsiSequences failing

### ISSUE THREAD

**Issue by Adam-Booth** [dotnet/corefx#39721]
Not sure if this is a problem with my setup or the actual code base since I am new to corefx so I'm sorry if I've done this wrong.

When I'm trying to build and run all tests, the following test is failing and preventing any further  tests from executing:

======================================================================
  ~/Source/corefx/corefx/artifacts/bin/System.Console.Tests/netcoreapp-Debug ~/Source/corefx/corefx/src/System.Console/tests
    Discovering: System.Console.Tests (method display = ClassAndMethod, method display options = None)
    Discovered:  System.Console.Tests (found 100 of 126 test cases)
    Starting:    System.Console.Tests (parallel test collections = on, max threads = 12)
      Color.NonRedirectedOutputDoesUseAnsiSequences [FAIL]
        Assert.Equal() Failure
        Expected: 3
        Actual:   0
        Stack Trace:
          /home/adam/Source/corefx/corefx/src/System.Console/tests/Color.cs(68,0): at Color.<>c.<NonRedirectedOutputDoesUseAnsiSequences>b__3_0(MemoryStream data)
          /home/adam/Source/corefx/corefx/src/System.Console/tests/Helpers.cs(81,0): at Helpers.RunInNonRedirectedOutput(Action`1 command)
          /home/adam/Source/corefx/corefx/src/System.Console/tests/Color.cs(62,0): at Color.NonRedirectedOutputDoesUseAnsiSequences()
  24
  80
    Finished:    System.Console.Tests

I'm trying to run all tests on the framework to see code coverage for each library. I'm using Debian 9 with latest updates.

**Comment by danmosemsft** [comment]
@adam-booth someone will have to investigate, but obviously if this one test is blocking you then you can comment it out locally. Although, I would not expect to block other tests from running.

**Comment by wfurt** [comment]
What terminal do you use? (echo $TERM)
The color will be determined based on terminal and the test seems to make some assumptions about it's value.

**Comment by Adam-Booth** [comment]
xterm-256color

**Comment by tmds** [comment]
Duplicate of https://github.com/dotnet/corefx/issues/39760.
