### ISSUE TITLE
Outerloop X509StoreMutableTests_OSX tests failing on macOS

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39823]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39795~2Fmerge/test~2Ffunctional~2Fcli~2Fouterloop~2F/20190726.1/workItem/System.Security.Cryptography.X509Certificates.Tests

All of these tests are failing with errors like:
```
OSX.1013.Amd64.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type Interop+AppleCrypto+AppleCommonCryptoCryptographicException
Message :
Interop+AppleCrypto+AppleCommonCryptoCryptographicException : User interaction is not allowed.
Stack Trace :
   at Interop.AppleCrypto.X509StoreAddCertificate(SafeKeychainItemHandle certOrIdentity, SafeKeychainHandle keychain) in /_/src/Common/src/Interop/OSX/System.Security.Cryptography.Native.Apple/Interop.X509Store.cs:line 39
   at Internal.Cryptography.Pal.StorePal.AppleKeychainStore.Add(ICertificatePal cert) in /_/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/StorePal.AppleKeychainStore.cs:line 66
   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate) in /_/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Store.cs:line 161
   at System.Security.Cryptography.X509Certificates.Tests.X509StoreMutableTests_OSX.AddPrivateAfterPublic() in /_/src/System.Security.Cryptography.X509Certificates/tests/X509StoreMutableTests.OSX.cs:line 147
```
cc: @bartonjs

**Comment by karelz** [comment]
@stephentoub why is it important for 3.0? Does it have higher failure rate frequency?
@wfurt can you please check out failure rate?

**Comment by stephentoub** [comment]
> why is it important for 3.0?

Understanding it is important for 3.0 because it's a failure while interacting with certificates on macOS.

If it turns out to be just a machine misconfiguration or infrastructure, obviously it can be pushed.

And once understood it can be triaged appropriately.

@bartonjs might be able to say off the top of his head what a likely cause is.

**Comment by bartonjs** [comment]
It's mostly machine misconfiguration (the login keychain is locked because the user logged in headless, and it can't ask for a password because it's headless).

Those tests should have had a guard in place to not run if they detected the headless state, but maybe an OS change caused a mismatch between the detector code in reality.
