### ISSUE TITLE
DynamicTableSizeUpdate_Exceeds_Settings_Throws failing on all OSes in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39876]
e.g.
```
Unhandled Exception of Type Xunit.Sdk.ContainsException
Message :
Assert.Contains() Failure
Not found: Dynamic table size update
In value:  The request was aborted.
Stack Trace :
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<DynamicTableSizeUpdate_Exceeds_Settings_Throws>b__93_0(Uri uri) in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 3020
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 71
   at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Int32 timeout) in /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 186
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.DynamicTableSizeUpdate_Exceeds_Settings_Throws() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 3013
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by scalablecory** [comment]
Did we update how exceptions are thrown some time this last week? Looks like an extra layer of `InnerException` snuck in between CI running for my PR (which passed) and me merging it.
