### ISSUE TITLE
platform detections is throwing on windows.10.amd64.serverrs5.open queue

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#39906]
I bump to this while looking at #38046
It keeps failing with `System.InvalidOperationException` 

(jobid dd99f893-7693-4c2e-aef2-328a7ae8b538 for example)

```
   at System.PlatformDetection.get_IsInAppContainer() in /_/src/Common/tests/CoreFx.Private.TestUtilities/System/PlatformDetection.Windows.cs:line 238
   at System.PlatformDetection.get_IsUap() in /_/src/Common/tests/CoreFx.Private.TestUtilities/System/PlatformDetection.Windows.cs:line 25
   at System.Net.Http.Functional.Tests.HttpClientHandlerTestBase.CreateHttpClientHandler(Boolean useSocketsHttpHandler, Boolean useHttp2LoopbackServer) in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTestBase.cs:line 75
   at System.Net.Http.Functional.Tests.HttpClientHandlerTestBase.CreateHttpClientHandler() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTestBase.cs:line 59
   at System.Net.Http.Functional.Tests.HttpClientHandlerTestBase.CreateHttpClient() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTestBase.cs:line 40
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_IPv6LinkLocalAddressUri_Success() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs:line 243
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by danmosemsft** [comment]
What's the message?
"throw new InvalidOperationException($"Failed to get AppId, result was {result}.");"

**Comment by wfurt** [comment]
System.InvalidOperationException : Failed to get AppId, result was 120.

**Comment by ericstj** [comment]
@safern fixed this here: https://github.com/dotnet/corefx/pull/39734, https://github.com/dotnet/corefx/pull/39734/commits/8e0ffa8cf23c284d5e3331503fae3852b0b71d09
