### ISSUE TITLE
macOS Catalina fails in SslStream

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/corefx#39904]
Using preview7 sdk
Repro:
```
> dotnet new mvc
> dotnet run
navigate to https://localhost:5001
```

```
Failed to authenticate HTTPS connection.
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+AppleCrypto+SslException: Internal error
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
```

cc @danmosemsft @bartonjs

**Comment by davidsh** [comment]
@wfurt

**Comment by stephentoub** [comment]
cc: @bartonjs

**Comment by danmosemsft** [comment]
@buyaa-n fyi

**Comment by danmosemsft** [comment]
@bartonjs is out. Should @wfurt look first or @krwq?

**Comment by buyaa-n** [comment]
This error looks same as test failure in System.Net.Security.Tests:
```xml
<test name="System.Net.Security.Tests.SslStreamAlertsTest.SslStream_StreamToStream_DataAfterShutdown_Fail" type="System.Net.Security.Tests.SslStreamAlertsTest" method="SslStream_StreamToStream_DataAfterShutdown_Fail" time="30.2629277" result="Fail">
        <failure exception-type="System.Security.Authentication.AuthenticationException">
          <message><![CDATA[System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.\n---- Interop+AppleCrypto+SslException : Internal error]]></message>
          <stack-trace><![CDATA[   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception) in /Users/dotnet/Documents/dotnet/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 710
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) in /Users/dotnet/Documents/dotnet/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 537
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) in /Users/dotnet/Documents/dotnet/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 527
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) in /Users/dotnet/Documents/dotnet/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 696
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) in /Users/dotnet/Documents/dotnet/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 651
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest) in /Users/dotnet/Documents/dotnet/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 831
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional() in /Users/dotnet/Documents/dotnet/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 82
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult) in /Users/dotnet/Documents/dotnet/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 472
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result) in /Users/dotnet/Documents/dotnet/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 442
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult) in /Users/dotnet/Documents/dotnet/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 284
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__66_1(IAsyncResult iar) in /Users/dotnet/Documents/dotnet/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 412
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/FutureFactory.cs:line 547
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /Users/dotnet/Documents/dotnet/corefx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 38
   at System.Net.Security.Tests.SslStreamAlertsTest.SslStream_StreamToStream_DataAfterShutdown_Fail() in /Users/dotnet/Documents/dotnet/corefx/src/System.Net.Security/tests/FunctionalTests/SslStreamAlertsTest.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
]]></stack-trace>
        </failure>
      </test>
```
The full test result can be found here: https://gist.github.com/buyaa-n/e00bc70c8f004978eca8c9a1b21b27e1

**Comment by buyaa-n** [comment]
Another failure for System.Net.Requests.Tests, not sure if we need separate issue for that, please check: https://gist.github.com/buyaa-n/b9e57ef2a1e609068e64af01a977589d

**Comment by wfurt** [comment]
https://support.apple.com/en-us/HT210176 outlines some TLS differences in Catalina. I'll take closer look when I get my development set up on Catalina.

**Comment by wfurt** [comment]
I was able to build and run all tests on 10.15:
```
  === TEST EXECUTION SUMMARY ===
     System.Net.Security.Tests  Total: 4308, Errors: 0, Failed: 0, Skipped: 13, Time: 45.502s
  ~/github/corefx/src/System.Net.Security/tests/FunctionalTests
```
It is possible that 10.15 and 10.14 are not binary compatible. I'll do more testing.

**Comment by buyaa-n** [comment]
with 10.15 I had build errors, did you had any build error? Here is PR for that https://github.com/dotnet/corefx/pull/39938

**Comment by wfurt** [comment]
it build for me without much troubles after adding missing dependencies. It probably depends on XCode version. It would be great if you can confirm test works for you after building on 10.15. I'm comparing bits and I'm trying to narrow down what changed between two versions.

**Comment by buyaa-n** [comment]
> it probably depends on XCode version

XCode 11 is what i have installed (Command_Line_Tools_for_Xcode_11_Beta_4) 

> It would be great if you can confirm test works for you after building on 10.15

The test failure i mentioned above happened after building on 10.15 and running all tests, i just tried to run individual test as you did but its failing with even more test failures, i might need to clean and rebuild again

**Comment by krwq** [comment]
In the past we had to review MD5/SHA1 usages as part of security sign off so I think per case might be better since it will be obvious to see this was intentional and not accidental.

**Comment by wfurt** [comment]
I was on XCode 10.3. I installed 11, did clean rebuild and I can still pass all tests.

**Comment by buyaa-n** [comment]
Hmm strange, did you tried with @BrennanConroy's repro and was that succcessful?
> \> dotnet new mvc
> \> dotnet run
navigate to https://localhost:5001

**Comment by wfurt** [comment]
that one fails to import certificates for me. I did not take closer look as I was primarily trying to run tests.

**Comment by krwq** [comment]
Here is what I'm seeing:

OS (today's update)

```
krwq@krwqs-MBP ~/src/corefx$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.15 (19A526h)
      Kernel Version: Darwin 19.0.0
      Boot Volume: Untitled
      Boot Mode: Normal
      Computer Name: krwq's MacBook Pro
      User Name: krwq (krwq)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2:24
```

Server (`dotnet new mvc && dotnet run` on sdk version 3.0.100-preview7-012821)

```
krwq@krwqs-MBP ~/test/dotnet-new-mvc-test-2019-08-01$ dotnet run
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/Users/krwq/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/krwq/test/dotnet-new-mvc-test-2019-08-01
```

Client

```
krwq@krwqs-MBP ~/src/corefx$ openssl s_client -connect localhost:5001 -msg
CONNECTED(00000005)
>>> TLS 1.2 Handshake [length 00bf], ClientHello
    01 00 00 bb 03 03 73 d2 04 b0 5c 58 98 22 ea 2b
    9d 58 d2 f5 b4 c2 d8 50 30 86 ce d9 78 69 cc 63
    24 e7 66 a1 f7 bb 00 00 5c c0 30 c0 2c c0 28 c0
    24 c0 14 c0 0a 00 9f 00 6b 00 39 cc a9 cc a8 cc
    aa ff 85 00 c4 00 88 00 81 00 9d 00 3d 00 35 00
    c0 00 84 c0 2f c0 2b c0 27 c0 23 c0 13 c0 09 00
    9e 00 67 00 33 00 be 00 45 00 9c 00 3c 00 2f 00
    ba 00 41 c0 11 c0 07 00 05 00 04 c0 12 c0 08 00
    16 00 0a 00 ff 01 00 00 36 00 0b 00 02 01 00 00
    0a 00 08 00 06 00 1d 00 17 00 18 00 23 00 00 00
    0d 00 1c 00 1a 06 01 06 03 ef ef 05 01 05 03 04
    01 04 03 ee ee ed ed 03 01 03 03 02 01 02 03
4534599148:error:140040E5:SSL routines:CONNECT_CR_SRVR_HELLO:ssl handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47/libressl-2.8/ssl/ssl_pkt.c:585:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Start Time: 1564701106
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by wfurt** [comment]
I also got asp.net case working. What was missing for me was `dotnet dev-certs https --trust` that creates certificates and imports them top Keychain. As we talk offline with @krwq yesterday, some of it depends on history. In my case I had fresh system and keys were missing.

**Comment by buyaa-n** [comment]
After upgrade i still seeing test failures, could any of you ssh into your machines and run the test? I heard last year some tests were failing only with ssh access

**Comment by krwq** [comment]
FYI: I'm also seeing all System.Net.Security tests passing on Catalina

**Comment by BrennanConroy** [comment]
> I also got asp.net case working. What was missing for me was `dotnet dev-certs https --trust`

I also did that before posting the issue and it didn't help.

**Comment by wfurt** [comment]
your error was different @BrennanConroy . In my case it even did not start. 
```
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
```

I have one machine where generation fails:
```
dotnet@dci-mac-build-114 cert % dotnet dev-certs https
There was an error saving the HTTPS developer certificate to the current user personal certificate store.

dotnet@dci-mac-build-114 cert % sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15
BuildVersion:	19A526h
```

I'm not sure at this point if it would make sense for you to delete old certificate from KeyChain and try it again.

I assume you run this either from GUI or interactive shell? e.g. this is not background process, right?

**Comment by BrennanConroy** [comment]
I ran it from the terminal directly on the machine.

**Comment by wfurt** [comment]
as far for me:
```
dotnet@dci-mac-build-114 cert % security unlock-keychain
password to unlock default:
dotnet@dci-mac-build-114 cert % dotnet dev-certs https
The HTTPS developer certificate was generated successfully.
```

and than everything works as expected:
```
dotnet@dci-mac-build-114 ~ % curl -v https://localhost:5001/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 5001 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=localhost
*  start date: Aug  2 20:44:05 2019 GMT
*  expire date: Aug  1 20:44:05 2020 GMT
*  subjectAltName: host "localhost" matched cert's "localhost"
*  issuer: CN=localhost
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: localhost:5001
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 02 Aug 2019 20:45:48 GMT
< Content-Type: text/html; charset=utf-8
< Server: Kestrel
< Transfer-Encoding: chunked
<
```

**Comment by buyaa-n** [comment]
The System.Net.Security tests passed after upgrade and build, run with new repo. Thank you @wfurt @krwq

**Comment by karelz** [comment]
Can we close the issue then as "not a problem anymore"? Or is there a reason to keep it open?

**Comment by bartonjs** [comment]
As far as I know, we build on one version of macOS (usually the oldest supported) as a single distribution for all versions of macOS.

If we need to build on 10.15 in order for 10.15 to work, we have a release (management/distribution) problem.

We need to understand why the prebuilts from 3.0 preview 7 aren't working.

**Comment by wfurt** [comment]
I try this with current master build (3.0.0-preview8-28379-02) and it works as expected. @BrennanConroy never answer question about version of beta. It seems like updated fixed the system we had from infrastructure team. 

We can possibly also do interactive debug on his system if that works.

**Comment by BrennanConroy** [comment]
I just upgraded and tried again. Same issue.

```bash
> sw_vers
BuildVersion: 19A526h
```

**Microsoft.NETCore.App**: 3.0.0-preivew8-28379-12

**Comment by danmosemsft** [comment]
@wfurt hopefully you can get access to @BrennanConroy machine. Looks like this is the last "unknown" in the Catalina scouting left.

**Comment by wfurt** [comment]
I did but I still don't know why it does not work on his system. I cloned his simple demo and I'm at point where the server does not send back anything and there is nothing on the server. 

Same sequence works on my system. I'll keep digging today.

**Comment by danmosemsft** [comment]
Thanks @wfurt!

**Comment by BrennanConroy** [comment]
We fixed the issue by booting in recovery mode and running "csrutil disable".

Afterwards re-enabling security checks "csrutil enable" causes the failure to happen again.

**Comment by wfurt** [comment]
Just for background,  csrutil enables and disables System Integrity Protection (SIP). After finding this as root cause, I enabled it back on my system. I don't get same error  but ssl server fails in way similar when KeyChain is locked. 

sure enough, when looking for system events:
```
macos-10:test furt$ log stream
2019-08-12 17:25:12.882008-0700 0x415      Error       0x0                  161    0    sandboxd: [com.apple.sandbox.reporting:violation] Sandbox: securityd(141) deny(1) file-read-data /Users/furt/Downloads/test/bin/Debug/netcoreapp3.0/osx-x64/test
Violation:       deny(1) file-read-data /Users/furt/Downloads/test/bin/Debug/netcoreapp3.0/osx-x64/test
Process:         securityd [141]
Path:            /usr/sbin/securityd
Load Address:    0x106094000
Identifier:      securityd
Version:         ??? (???)
Code Type:       x86_64 (Native)
Parent Process:  launchd [1]
Responsible:     /usr/sbin/securityd
User ID:         0

Date/Time:       2019-08-12 17:25:12.878 PDT
OS Version:      Mac OS X 10.15 (19A526h)
Report Version:  8


MetaData: {"primary-filter":"path","pid":141,"uid":0,"hardware":"Mac","user-approval":"kTCCServiceSystemPolicyDownloadsFolder","platform-binary":true,"storage-class":"kTCCServiceSystemPolicyDownloadsFolder","vnode-type":"REGULAR-FILE","platform-policy":false,"normalized_target":["Users","furt","Downloads","test","bin","Debug","netcoreapp3.0","osx-x64","test"],"profile-in-collection":false,"apple-internal":false,"responsible-process-user-uuid":"FFFFEEEE-DDDD-CCCC-BBBB-AAAA00000000","build":"Mac OS X 10.15 (19A526h)","process-path":"\/usr\/sbin\/securityd","profile-flags":0,"target":"\/Users\/furt\/Downloads\/test\/bin\/Debug\/netcoreapp3.0\/osx-x64\/test","signing-id":"com.apple.securityd","path":"\/Users\/furt\/Downloads\/test\/bin\/Debug\/netcoreapp3.0\/osx-x64\/test","mount-rdev":16777220,"operation":"file-read-data","rdev":0,"responsible-process-path":"\/usr\/sbin\/securityd","responsible-process-uid":0,"errno":1,"file-flags":0,"summary":"deny(1) file-read-data \/Users\/furt\/Downloads\/test\/bin\/Debug\/netcoreapp3.0\/osx-x64\/test","primary-filter-value":"\/Users\/furt\/Downloads\/test\/bin\/Debug\/netcoreapp3.0\/osx-x64\/test","flags":5,"action":"deny","process":"securityd","platform_binary":"yes"}

```

`securityd` is daemon responsible for managing security contexts and access to KeyChain. 

After some experiments I found solution possible as workaround. I did publish self-contained app to simplify testing. When I move it under `/Applications` identical application works. 
This may be also related to running unsigned binaries. I don't have signing set up but it maybe possible that we would net get denied by OS if code is signed by recognized key. 


This so far does not look like .Net issue but more security policy enforced by OS. It would be great is @BrennanConroy can confirm.

**Comment by wfurt** [comment]
while continuing investigation, this does not look like something  must have for 3.0.

**Comment by BrennanConroy** [comment]
Moving the app to be under `/Applications` solves the issue

**Comment by wfurt** [comment]
As there is no action for .Net right now, I'm going to close this.

**Comment by gsacavdm** [comment]
@BrennanConroy - how did you move it to `/Applications`? Published as a self-contained app and moved that copied that single file into the Applications folder?

I want to test that as I've run many attempts and permutations of  the`dotnet dev-cert` commands yet I continue to have the `The ASP.NET Core developer certificate is in an invalid state.` error after my update to OSX Catalina.

**Comment by BrennanConroy** [comment]
Yeah I copied the publish output to a folder in `/Applications`
