### ISSUE TITLE
System.Security.Cryptography.Pkcs.Tests failed with new Mac OS

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/corefx#39924]
13 test failures found for the System.Security.Cryptography.Pkcs.Tests run with new Mac OS Catalina 
```xml
<test name="System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildFromSignerInfo" type="System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests" method="BuildFromSignerInfo" time="0.1808078" result="Fail">
        <failure exception-type="Interop+AppleCrypto+AppleCFErrorCryptographicException">
          <message><![CDATA[Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (Internal CSSM error error 100001 - Internal error #186a1 at SignTransform_block_invoke /BuildRoot/Library/Caches/com.apple.xbs/Sources/Security/Security-59296.0.0.0.2/OSX/libsecurity_transform/lib/SecSignVerifyTransform.c:324)]]></message>
          <stack-trace><![CDATA[   at Interop.AppleCrypto.TryExecuteTransform(ReadOnlySpan`1 source, Span`1 destination, Int32& bytesWritten, SecKeyTransform transform) in /Users/dotnet/Documents/dotnet/corefx/src/Common/src/Interop/OSX/System.Security.Cryptography.Native.Apple/Interop.SecKeyRef.cs:line 182
   at Interop.AppleCrypto.TryGenerateSignature(SafeSecKeyRefHandle privateKey, ReadOnlySpan`1 source, Span`1 destination, PAL_HashAlgorithm hashAlgorithm, Int32& bytesWritten) in /Users/dotnet/Documents/dotnet/corefx/src/Common/src/Interop/OSX/System.Security.Cryptography.Native.Apple/Interop.SecKeyRef.cs:line 268
   at System.Security.Cryptography.RSAImplementation.RSASecurityTransforms.TrySignHash(ReadOnlySpan`1 hash, Span`1 destination, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding, Int32& bytesWritten) in /Users/dotnet/Documents/dotnet/corefx/src/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs:line 605
   at System.Security.Cryptography.Pkcs.CmsSignature.RSAPkcs1CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, Oid& signatureAlgorithm, Byte[]& signatureValue) in /Users/dotnet/Documents/dotnet/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSignature.RSA.cs:line 157
   at System.Security.Cryptography.Pkcs.CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, Oid& oid, ReadOnlyMemory`1& signatureValue) in /Users/dotnet/Documents/dotnet/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSignature.cs:line 95
   at System.Security.Cryptography.Pkcs.CmsSigner.Sign(ReadOnlyMemory`1 data, String contentTypeOid, Boolean silent, X509Certificate2Collection& chainCerts) in /Users/dotnet/Documents/dotnet/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSigner.cs:line 233
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer, Boolean silent) in /Users/dotnet/Documents/dotnet/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignedCms.cs:line 323
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer) in /Users/dotnet/Documents/dotnet/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignedCms.cs:line 274
   at System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildFromSignerInfo() in /Users/dotnet/Documents/dotnet/corefx/src/System.Security.Cryptography.Pkcs/tests/Rfc3161/TimestampRequestTests.cs:line 136]]></stack-trace>
        </failure>
      </test>
```
Please refer: https://gist.github.com/buyaa-n/04268abbf15747ee526e974b5311e1e6 for full test result

**Comment by krwq** [comment]
@buyaa-n all of those tests are passing for me on Catalina. I suspect this is the same issue you got here: https://github.com/dotnet/corefx/issues/39904 and this is very likely related to your setup in some way

**Comment by krwq** [comment]
@buyaa-n is this passing for you after the local fixes? if yes I think we should close the issue (also please paste the resolution here for reference if someone hits this as well)

**Comment by buyaa-n** [comment]
@krwq this project test is not failing anymore. But System.Security.Cryptography.Xml.Tests is still failing could you try run that test? Thank you!

**Comment by buyaa-n** [comment]
Only one failure found:
```xml
<collection total="1" passed="0" failed="1" skipped="0" name="Test collection for System.Security.Cryptography.Xml.Tests.SigningVerifyingX509Cert" time="0.876">
      <test name="System.Security.Cryptography.Xml.Tests.SigningVerifyingX509Cert.SignedXmlHasCertificateVerifiableSignature" type="System.Security.Cryptography.Xml.Tests.SigningVerifyingX509Cert" method="SignedXmlHasCertificateVerifiableSignature" time="0.8763107" result="Fail">
        <failure exception-type="Interop+AppleCrypto+AppleCFErrorCryptographicException">
          <message><![CDATA[Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (Internal CSSM error error 100001 - Internal error #186a1 at SignTransform_block_invoke /BuildRoot/Library/Caches/com.apple.xbs/Sources/Security/Security-59306.0.3.0.4/OSX/libsecurity_transform/lib/SecSignVerifyTransform.c:324)]]></message>
          <stack-trace><![CDATA[   at Interop.AppleCrypto.ExecuteTransform(ReadOnlySpan`1 source, SecKeyTransform transform) in /Users/dotnet/furt/corefx/src/Common/src/Interop/OSX/System.Security.Cryptography.Native.Apple/Interop.SecKeyRef.cs:line 154
   at Interop.AppleCrypto.GenerateSignature(SafeSecKeyRefHandle privateKey, ReadOnlySpan`1 dataHash, PAL_HashAlgorithm hashAlgorithm) in /Users/dotnet/furt/corefx/src/Common/src/Interop/OSX/System.Security.Cryptography.Native.Apple/Interop.SecKeyRef.cs:line 247
   at System.Security.Cryptography.RSAImplementation.RSASecurityTransforms.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) in /Users/dotnet/furt/corefx/src/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs:line 528
   at System.Security.Cryptography.RSAPKCS1SignatureFormatter.CreateSignature(Byte[] rgbHash) in /Users/dotnet/furt/corefx/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RSAPKCS1SignatureFormatter.cs:line 56
   at System.Security.Cryptography.AsymmetricSignatureFormatter.CreateSignature(HashAlgorithm hash) in /Users/dotnet/furt/corefx/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/AsymmetricSignatureFormatter.cs:line 22
   at System.Security.Cryptography.Xml.SignedXml.ComputeSignature() in /Users/dotnet/furt/corefx/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/SignedXml.cs:line 422
   at System.Security.Cryptography.Xml.Tests.SigningVerifyingX509Cert.SignXml(XmlDocument doc, AsymmetricAlgorithm key) in /Users/dotnet/furt/corefx/src/System.Security.Cryptography.Xml/tests/Samples/SigningVerifyingX509Cert.cs:line 38
   at System.Security.Cryptography.Xml.Tests.SigningVerifyingX509Cert.SignedXmlHasCertificateVerifiableSignature() in /Users/dotnet/furt/corefx/src/System.Security.Cryptography.Xml/tests/Samples/SigningVerifyingX509Cert.cs:line 73]]></stack-trace>
        </failure>
      </test>
    </collection>
```

**Comment by krwq** [comment]
@buyaa-n is there a seperate issue for that?

**Comment by buyaa-n** [comment]
No issue yet

**Comment by krwq** [comment]
Please create a separate issue so that we don't mix it -  this test is passing on my Catalina

**Comment by krwq** [comment]
I'm closing this one since it works for you now. Please paste instructions on what fixed this for you

**Comment by buyaa-n** [comment]
ok, maybe i need to run the test individually again. Closing this one then, will open new one if needed

**Comment by krwq** [comment]
@buyaa-n if you are seeing different results for running in bulk vs running individually please file issue on that as this might be a product issue
