### ISSUE TITLE
Mac Catalina: SetDelegate_ConnectionSucceeds test fails with Tls1.0 and PlatformHttpHandler

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/corefx#39989]
System.Net.Http.Functional.Tests failing:
```xml
<failure exception-type="System.AggregateException">
          <message><![CDATA[System.AggregateException : One or more errors occurred. (One or more errors occurred. (Authentication failed, see inner exception.)) (One or more errors occurred. (The SSL connection could not be established, see inner exception.))\n---- System.AggregateException : One or more errors occurred. (Authentication failed, see inner exception.)\n-------- System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.\n------------ Interop+AppleCrypto+SslException : UNIX[Operation not permitted]\n---- System.AggregateException : One or more errors occurred. (The SSL connection could not be established, see inner exception.)\n-------- System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception.\n------------ System.IO.IOException : Authentication failed because the remote party has closed the transport stream.]]></message>
          <stack-trace><![CDATA[   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /Users/dotnet/furt/corefx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /Users/dotnet/furt/corefx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 71
   at System.Net.Http.Functional.Tests.HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.<>c__DisplayClass4_0.<<SetDelegate_ConnectionSucceeds>b__0>d.MoveNext() in /Users/dotnet/furt/corefx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.AcceptAllCerts.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /Users/dotnet/furt/corefx/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 66
   at System.Net.Http.Functional.Tests.HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.SetDelegate_ConnectionSucceeds(SslProtocols acceptedProtocol, Boolean requestOnlyThisProtocol) in /Users/dotnet/furt/corefx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.AcceptAllCerts.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace #1 (System.AggregateException) -----

----- Inner Stack Trace -----
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception) in /Users/dotnet/furt/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 710
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) in /Users/dotnet/furt/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 537
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) in /Users/dotnet/furt/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 527
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) in /Users/dotnet/furt/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 696
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) in /Users/dotnet/furt/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 651
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) in /Users/dotnet/furt/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 599
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest) in /Users/dotnet/furt/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 393
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken) in /Users/dotnet/furt/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 309
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState) in /Users/dotnet/furt/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 280
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState) in /Users/dotnet/furt/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 270
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__68_1(X509Certificate arg1, Boolean arg2, SslProtocols arg3, AsyncCallback callback, Object state) in /Users/dotnet/furt/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 427
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/FutureFactory.cs:line 1152
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/TaskFactory.cs:line 1135
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/TaskFactory.cs:line 1092
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation) in /Users/dotnet/furt/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 428
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in /Users/dotnet/furt/corefx/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 135
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionSendResponseAndCloseAsync(HttpStatusCode statusCode, String additionalHeaders, String content) in /Users/dotnet/furt/corefx/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 190
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /Users/dotnet/furt/corefx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
```

**Comment by buyaa-n** [comment]
Full test result: https://gist.github.com/buyaa-n/1dfd8f10a17221207b0c3e592a4feba6

**Comment by wfurt** [comment]
This test has already note about some misbehavior on OSX. When I run it on Maveric (10.14), server offers TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA from Tls1.1 but negotiation succeeds. 

On Catalina server (HttpLoopback/SslStream picks ECDHE-RSA-AES256-SHA384 from Tls1.2 and that get rejected by HttpCLient/curl. 

This conceptually looks like product/OS problem. We   should not select Tls1.1 or Tls1.2 cipher suite as response to Tls1.0 hello.  While this is probably platform bug in SecureChannel, I'm wondering if we could use new cipher policy API to explicitly filter out cipher suites incorrectly advertised. 

cc: @bartonjs @krwq 

BTW it works fine with SocketHttpHandler and SslSstream on both sides. 
[tls.zip](https://github.com/dotnet/corefx/files/3474290/tls.zip)

**Comment by wfurt** [comment]
This does not look like must fix for 3.0

cc: @karelz

**Comment by krwq** [comment]
considering it upgrades security it is not necessarily must fix. I think we should fix it in 5.0 timeline though. I can take a look at this after my current issues since there are not many 3.0 bugs left.

**Comment by bartonjs** [comment]
FWIW I reported to Apple that they use ciphers "from the future" when a lower protocol is negotiated, their response was (effectively): so what? don't pick lower TLS versions.

**Comment by karelz** [comment]
Discussion result:
We agreed to move it to 5.0.
We will disable the tests and close the issue until there are customers having problems, then we can consider work around the Apple API limitation.

**Comment by krwq** [comment]
Test disabled, per discussion closing this until there is someone complaining about this.
