### ISSUE TITLE
Accessing a resource file when SelfContained = true throws a System.MissingMethodException

### ISSUE THREAD

**Issue by Symbai** [dotnet/corefx#39980]
Accessing a resource file throws a `System.MissingMethodException: Constructor on type 'System.Byte[]' not found.` exception but only when published as selfcontained. It happens on a WPF project and a Winforms project. Console I couldn't test as it says : `Non-string resources require the System.Resources.Extensions assembly at runtime, but it was not found in this project's references.` and i have no idea how to add it.

Running the code in debug mode or release without self contained it does not throw!

### Dotnet Info:
```
.NET Core SDK (according "global.json"):
 Version:   3.0.100-preview8-013401
 Commit:    856ca550a1

Runtime environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013401\

Host (useful for support):
  Version: 3.0.0-preview8-27919-09
  Commit:  3fcf1dac55

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013401 [C:\Program Files\dotnet\sdk]
```

### Repro:
```
try
{
    using var ms = new MemoryStream(Properties.Resources.TestFile);
    MessageBox.Show("Success");
}
catch (Exception e)
{
    MessageBox.Show(e.ToString());
}
```

### Build command:
`dotnet publish -c Release -v q --self-contained -r win-x64 -f netcoreapp3.0`

### Stacktrace:
```
System.MissingMethodException: Constructor on type 'System.Byte[]' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Resources.Extensions.DeserializingResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.Extensions.DeserializingResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.DeserializingResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.DeserializingResourceReader.LoadObject(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   at System.Resources.Extensions.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture)
```

### Repro projects:
[WPF.zip](https://github.com/dotnet/corefx/files/3462060/WPF.zip)
[Winforms.zip](https://github.com/dotnet/corefx/files/3462064/Winforms.zip)

**Comment by danmosemsft** [comment]
@ericstj is this ours?

**Comment by ericstj** [comment]
@rainersigwald it looks like this may be a bug in GenerateResource.  ResX contains
```
  <data name="TestFile" type="System.Resources.ResXFileRef, System.Windows.Forms">
    <value>..\Resources\TestFile;System.Byte[], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
```

GenerateResource is treating this as an Activator resource and adding it via AddActivatorResource. 
https://github.com/microsoft/msbuild/blob/d31fdbf016616835b237d2846f3f1535560bb2d5/src/Tasks/ResourceHandling/FileStreamResource.cs#L44

Here's the relevant desktop code: https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/Resources/ResXFileRef.cs,313
```c#
if(toCreate.Equals(typeof(byte[]))) {
    created = temp;
} else {
    MemoryStream memStream = new MemoryStream(temp);
    if(toCreate.Equals(typeof(MemoryStream))) {
        return memStream;
    } else if(toCreate.Equals(typeof(System.Drawing.Bitmap)) && fileName.EndsWith(".ico")) {
        // we special case the .ico bitmaps because GDI+ destroy the alpha channel component and
        // we don't want that to happen
        Icon ico = new Icon(memStream);
        created = ico.ToBitmap();
    } else {
        created = Activator.CreateInstance(toCreate, BindingFlags.Instance | BindingFlags.Public | BindingFlags.CreateInstance, null, new Object[] {memStream}, null);
    }
}
```
It looks like we missed a special case for `byte[]`.  There is also a special case here for `MemoryStream` that is likely also relevant.

**Comment by ericstj** [comment]
Closing as this has been moved to MSBuild
