### ISSUE TITLE
Compatibility: System.IO.MemoryMappedFiles.Tests failing with new Mac OSX 10.15

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/corefx#40037]
4 tests failing with new Mac OS Catalina from System.IO.MemoryMappedFiles.Tests. Its happening with or without running as sudo. Failure similar to https://github.com/dotnet/corefx/issues/34718 but that one was for docker
```xml
<test name="System.IO.MemoryMappedFiles.Tests.MemoryMappedViewAccessorTests.ValidAccessLevelCombinations(mapAccess: ReadWriteExecute, viewAccess: ReadWriteExecute)" type="System.IO.MemoryMappedFiles.Tests.MemoryMappedViewAccessorTests" method="ValidAccessLevelCombinations" time="0.0221614" result="Fail">
        <failure exception-type="System.UnauthorizedAccessException">
          <message><![CDATA[System.UnauthorizedAccessException : Access to the path is denied.\n---- System.IO.IOException : Operation not permitted]]></message>
          <stack-trace><![CDATA[   at System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(SafeMemoryMappedFileHandle memMappedFileHandle, MemoryMappedFileAccess access, Int64 requestedOffset, Int64 requestedSize) in /Users/dotnet/Documents/dotnet/corefx/src/System.IO.MemoryMappedFiles/src/System/IO/MemoryMappedFiles/MemoryMappedView.Unix.cs:line 124
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewAccessor(Int64 offset, Int64 size, MemoryMappedFileAccess access) in /Users/dotnet/Documents/dotnet/corefx/src/System.IO.MemoryMappedFiles/src/System/IO/MemoryMappedFiles/MemoryMappedFile.cs:line 455
   at System.IO.MemoryMappedFiles.Tests.MemoryMappedViewAccessorTests.<>c__DisplayClass1_0.<ValidAccessLevelCombinations>b__0() in /Users/dotnet/Documents/dotnet/corefx/src/System.IO.MemoryMappedFiles/tests/MemoryMappedViewAccessor.Tests.cs:line 87
   at System.AssertExtensions.ThrowsIf[T](Boolean condition, Action action) in /Users/dotnet/Documents/dotnet/corefx/src/Common/tests/CoreFx.Private.TestUtilities/System/AssertExtensions.cs:line 236
   at System.IO.MemoryMappedFiles.Tests.MemoryMappedViewAccessorTests.ValidAccessLevelCombinations(MemoryMappedFileAccess mapAccess, MemoryMappedFileAccess viewAccess) in /Users/dotnet/Documents/dotnet/corefx/src/System.IO.MemoryMappedFiles/tests/MemoryMappedViewAccessor.Tests.cs:line 81
----- Inner Stack Trace -----
]]></stack-trace>
        </failure>
      </test>
```
Full test result: https://gist.github.com/buyaa-n/6cf58377ccde90703728de02e3e2ddef#file-system-io-memorymappedfiles-tests-result-xml-L415
cc @wfurt @safern

**Comment by wfurt** [comment]
seems like local environment issue. I can pass test without problem on my system.
```
  ===========================================================================================================
  ~/github/corefx/artifacts/bin/System.IO.MemoryMappedFiles.Tests/netcoreapp-Unix-Debug ~/github/corefx/src/System.IO.MemoryMappedFiles/tests
    Discovering: System.IO.MemoryMappedFiles.Tests (method display = ClassAndMethod, method display options = None)
    Discovered:  System.IO.MemoryMappedFiles.Tests (found 78 of 102 test cases)
    Starting:    System.IO.MemoryMappedFiles.Tests (parallel test collections = on, max threads = 2)
    Finished:    System.IO.MemoryMappedFiles.Tests
  === TEST EXECUTION SUMMARY ===
     System.IO.MemoryMappedFiles.Tests  Total: 343, Errors: 0, Failed: 0, Skipped: 0, Time: 1.794s
  ~/github/corefx/src/System.IO.MemoryMappedFiles/tests
```

We could figure out with `dttuss` but on your system it is not possible because of security setting
```
dotnet@dci-mac-build-114 netcoreapp-Unix-Debug % csrutil status
System Integrity Protection status: enabled.
```  

You should work it out with infrastructure team to get that disabled so we can do OS tracing.

**Comment by danmosemsft** [comment]
It is the tests requesting `mapAccess: ReadWriteExecute, viewAccess: ReadExecute` and `mapAccess: ReadWriteExecute, viewAccess: ReadWriteExecute`, and only those tests, that are failing. Looking at he results linked above, the mapAccess must have at least write+execute and the view access at least read+execute. 

If the security feature is protecting against write + execute then  `mapAccess: ReadExecute, viewAccess: ReadWriteExecute` would fail as well. @stephentoub any idea why that might pass and hte othesr above succeed?

**Comment by danmosemsft** [comment]
Oh! no doubt because the view access cannot go beyond the original access the mapped file was created with. So this feature requires a view accessor that can at least read and execute, over a mapped file that has at least read, write and execute (not having write on the map access would make no sense).

**Comment by buyaa-n** [comment]
Closding the issue as test succeeded after the security settings update. Thank you @wfurt
