### ISSUE TITLE
"Invalid Typeref token" error in app's async method when PublishTrimmed option enabled

### ISSUE THREAD

**Issue by mthalman** [dotnet/corefx#40060]
Repro Steps:
1. `git clone https://github.com/dotnet/docker-tools.git`
1. `cd docker-tools`
1. `git checkout 0034133bf2214492c2949e7bd31bf22a85ab1856`
1. `echo [] > image-info.json`
1. `dotnet build Microsoft.DotNet.ImageBuilder\Microsoft.DotNet.ImageBuilder.sln`
1. `dotnet publish .\Microsoft.DotNet.ImageBuilder\src\Microsoft.DotNet.ImageBuilder.csproj -c Release -o out -r win7-x64`
1. `out\Microsoft.DotNet.ImageBuilder.exe rebuildStaleImages "" "" "" --subscriptions-path eng/check-base-image-subscriptions.json --image-info-path image-info.json`

Result:
```
System.AggregateException: One or more errors occurred. ([C:\repos\temp\docker-tools\out\Microsoft.DotNet.ImageBuilder.dll] Invalid Typeref token.)
 ---> System.BadImageFormatException: [C:\repos\temp\docker-tools\out\Microsoft.DotNet.ImageBuilder.dll] Invalid Typeref token.
   at Microsoft.DotNet.ImageBuilder.Commands.RebuildStaleImagesCommand.GetGitRepoPath(Subscription sub)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.DotNet.ImageBuilder.Commands.RebuildStaleImagesCommand.GetGitRepoPath(Subscription sub)
   at Microsoft.DotNet.ImageBuilder.Commands.RebuildStaleImagesCommand.GetPathsToRebuildAsync(Subscription subscription, RepoData[] repos)
   at Microsoft.DotNet.ImageBuilder.Commands.RebuildStaleImagesCommand.QueueBuildForStaleImages(Subscription subscription, RepoData[] repos)
   at Microsoft.DotNet.ImageBuilder.Commands.RebuildStaleImagesCommand.ExecuteAsync()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.DotNet.ImageBuilder.ImageBuilder.Main(String[] args)
```

If you change `Microsoft.DotNet.ImageBuilder\src\Microsoft.DotNet.ImageBuilder.csproj` so that `PublishTrimmed` is set to `False`, then you will no longer get this `Invalid Typeref token` error.  Instead, you'll get an an error saying `The resource cannot be found`, which is expected because of how the project's code is written.

**Comment by mthalman** [comment]
Moved to https://github.com/mono/linker/issues/698
