### ISSUE TITLE
HTTP2: hitting debug assert in CI runs in Http2Stream.OnReset

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#40168]
https://helix.dot.net/api/2019-06-17/jobs/d47e9a92-af57-4108-876b-5dc45e7ca70c/workitems/System.Net.Http.Functional.Tests/console

This was PR for some OSX crypto and there was no HTTP change. 

```
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress_NoVersion.SingleClient_ManyGets_Async [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
Process terminated. Assertion failed.
   at System.Net.Http.Http2Connection.Http2Stream.OnReset(Exception resetException, Nullable`1 resetStreamErrorCode, Boolean canRetry) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs:line 658
   at System.Net.Http.Http2Connection.AbortStreams(Exception abortException) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 1439
   at System.Net.Http.Http2Connection.Abort(Exception abortException) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 1369
   at System.Net.Http.Http2Connection.FlushOutgoingBytesAsync() in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 186
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 1015
   at System.Net.Http.Http2Connection.FlushOutgoingBytesAsync()
   at System.Net.Http.Http2Connection.EndWrite(Boolean forceFlush) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 778
   at System.Net.Http.Http2Connection.FinishWrite(FlushTiming flush) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 751
   at System.Net.Http.Http2Connection.SendRstStreamAsync(Int32 streamId, Http2ProtocolErrorCode errorCode) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 867
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 1015
   at System.Net.Http.Http2Connection.SendRstStreamAsync(Int32 streamId, Http2ProtocolErrorCode errorCode)
   at System.Net.Http.Http2Connection.Http2Stream.Reset() in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs:line 284
   at System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync(CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs:line 173
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 580
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 172
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 617
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 595
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/TaskContinuation.cs:line 794
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 3320
   at System.Threading.Tasks.Task.FinishContinuations() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 3293
   at System.Threading.Tasks.Task.FinishStageThree() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2176
   at System.Threading.Tasks.Task.CancellationCleanupLogic() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 3151
   at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 3266
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 784
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetException(Exception exception) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 283
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask) in /_/src/System.Net.Http/src/System/Net/Http/HttpContent.cs:line 369
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 580
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 172
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 617
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 595
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/TaskContinuation.cs:line 794
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 3320
   at System.Threading.Tasks.Task.FinishContinuations() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 3293
   at System.Threading.Tasks.Task.FinishStageThree() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2176
   at System.Threading.Tasks.Task.CancellationCleanupLogic() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 3151
   at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 3266
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 784
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetException(Exception exception) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 283
   at System.Net.Http.Functional.Tests.ByteAtATimeContent.SerializeToStreamAsync(Stream stream, TransportContext context) in /_/src/System.Net.Http/tests/FunctionalTests/ByteAtATimeContent.cs:line 36
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 580
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 172
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 617
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 595
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/TaskContinuation.cs:line 794
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 3320
   at System.Threading.Tasks.Task.FinishContinuations() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 3293
   at System.Threading.Tasks.Task.TrySetResult() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 3183
   at System.Threading.Tasks.Task.DelayPromise.CompleteTimedOut() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 5529
   at System.Threading.Tasks.Task.DelayPromise.<>c.<.ctor>b__1_0(Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 5516
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool) in /_/src/System.Private.CoreLib/shared/System/Threading/Timer.cs:line 649
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool) in /_/src/System.Private.CoreLib/shared/System/Threading/Timer.cs:line 600
   at System.Threading.TimerQueueTimer.System.Threading.IThreadPoolWorkItem.Execute() in /_/src/System.Private.CoreLib/shared/System/Threading/Timer.cs:line 582
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 677
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() in /_/src/System.Private.CoreLib/src/System/Threading/ThreadPool.CoreCLR.cs:line 29
----- end Thu 08/08/2019 20:11:58.19 ----- exit code -2146232797 ----------------------------------------------------------

```
since we hit assert this will not show up in test results as failed test. 

cc: @geoffkizer

**Comment by JamesNK** [comment]
Same? https://github.com/dotnet/corefx/issues/40115

**Comment by wfurt** [comment]
I miss that one. Thansk @JamesNK

**Comment by karelz** [comment]
Duplicate #40115
