### ISSUE TITLE
Two EventLogTraceListenerTests are failing consistently on Windows.10.Amd64.Client19H1

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#40224]
https://dnceng.visualstudio.com/public/_build/results?buildId=302174&view=ms.vss-test-web.build-test-results-tab&runId=8598276&paneView=debug&resultId=150632

```
System.Diagnostics.Tests.EventLogTraceListenerTests.TraceEventFormatAndParams

System.ComponentModel.Win32Exception : A device attached to the system is not functioning.

 at System.Diagnostics.EventLogInternal.Clear() in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs:line 479
   at System.Diagnostics.EventLog.Clear() in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 226
   at System.Diagnostics.EventLog.Delete(String logName, String machineName) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 402
   at System.Diagnostics.EventLog.Delete(String logName) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 366
   at System.Diagnostics.Tests.EventLogTraceListenerTests.<>c__DisplayClass12_0.<TraceEventFormatAndParams>b__0() in /_/src/System.Diagnostics.EventLog/tests/EventLogTraceListenerTests.cs:line 248
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<RetryOnWin7>b__0() in /_/src/System.Diagnostics.EventLog/tests/Helpers.cs:line 23
   at System.Diagnostics.Tests.Helpers.RetryOnWin7[T](Func`1 func) in /_/src/System.Diagnostics.EventLog/tests/Helpers.cs:line 30
   at System.Diagnostics.Tests.Helpers.RetryOnWin7(Action func) in /_/src/System.Diagnostics.EventLog/tests/Helpers.cs:line 23
   at System.Diagnostics.Tests.EventLogTraceListenerTests.TraceEventFormatAndParams(String format, Object[] parameters)
```

```
System.Diagnostics.Tests.EventLogTraceListenerTests.TraceEventTest

System.ComponentModel.Win32Exception : A device attached to the system is not functioning.

 at System.Diagnostics.EventLogInternal.Clear() in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs:line 479
   at System.Diagnostics.EventLog.Clear() in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 226
   at System.Diagnostics.EventLog.Delete(String logName, String machineName) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 402
   at System.Diagnostics.EventLog.Delete(String logName) in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 366
   at System.Diagnostics.Tests.EventLogTraceListenerTests.<>c__DisplayClass8_0.<TraceEventTest>b__0() in /_/src/System.Diagnostics.EventLog/tests/EventLogTraceListenerTests.cs:line 144
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<RetryOnWin7>b__0() in /_/src/System.Diagnostics.EventLog/tests/Helpers.cs:line 23
   at System.Diagnostics.Tests.Helpers.RetryOnWin7[T](Func`1 func) in /_/src/System.Diagnostics.EventLog/tests/Helpers.cs:line 30
   at System.Diagnostics.Tests.Helpers.RetryOnWin7(Action func) in /_/src/System.Diagnostics.EventLog/tests/Helpers.cs:line 23
   at System.Diagnostics.Tests.EventLogTraceListenerTests.TraceEventTest(TraceEventType eventType, EventLogEntryType expectedType, Int32 id, Int32 expectedId) in /_/src/System.Diagnostics.EventLog/tests/EventLogTraceListenerTests.cs:line 144
```

cc @stephentoub

**Comment by ViktorHofer** [comment]
Still failing, even with the retry: https://dnceng.visualstudio.com/public/_build/results?buildId=340548&view=ms.vss-test-web.build-test-results-tab&runId=10067396&resultId=179008&paneView=debug
