### ISSUE TITLE
load calendar data exception

### ISSUE THREAD

**Issue by rodrigovaras** [dotnet/corefx#40286]
here is link to the original issue reported in liveshare:
https://github.com/MicrosoftDocs/live-share/issues/2666

The extracted stacktrace suggest something a problem loading the calendar:
Agent terminated with exit code: 0 and signal null: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.CalendarData.NormalizeDatePattern(String input)
   at System.Globalization.CalendarData.LoadCalendarDataFromSystem(String localeName, CalendarIdcalendarId)
   at System.Globalization.CalendarData..ctor(String localeName, CalendarId calendarId, Boolean bUseUserOverrides)
   at System.Globalization.CultureData.GetCalendar(CalendarId calendarId)
   at System.Globalization.CultureData.DateSeparator(CalendarId calendarId)
   at System.Globalization.DateTimeFormatInfo.InitializeOverridableProperties(CultureData cultureData, CalendarId calendarId)
   at System.Globalization.CultureInfo.get_DateTimeFormat()
   at System.Globalization.DateTimeFormatInfo.get_CurrentInfo()
   at System.DateTimeFormat.TryFormat(DateTime dateTime, Span`1 destination, Int32& charsWritten, ReadOnlySpan`1 format, IFormatProvider provider, TimeSpan offset)
   at System.DateTimeFormat.TryFormat(DateTime dateTime, Span`1 destination,Int32& charsWritten, ReadOnlySpan`1 format, IFormatProvider provider)
   at System.DateTime.TryFormat(Span`1 destination, Int32& charsWritten, ReadOnlySpan`1 format, IFormatProvider provider)
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at Microsoft.VisualStudio.LiveShare.Tracing.LogFileTraceListener.OpenLogFile(String logDirectory, String processName) in E:\A\_work\300\s\src\Tracing\Tracing\LogFileTraceListener.cs:line 78
   at Microsoft.VisualStudio.LiveShare.Tracing.LogFileTraceListener..ctor(IFormatProvider format, String processName, String logDirectory) in E:\A\_work\300\s\src\Tracing\Tracing\LogFileTraceListener.cs:line 39
   at Microsoft.VisualStudio.LiveShare.Tracing.TracingSourceFactory.CreateTraceSource(String name, Nullable`1 eventIdLogCreated, TraceFilter logFileTraceFilter, Nullable`1 consoleVerbosity, IReadOnlyDictionary`2 consoleSourceLevels, Assembly boostrapAssembly, String logDirectory, IEnumerable`1 unfilteredConsoleEvents, TraceOptions consoleTraceOptions) in E:\A\_work\300\s\src\Tracing\Tracing\TraceSourceFactory.cs:line 70
   at Microsoft.Cascade.Tracing.TracingConfig.CreateTraceSource(String name, Nullable`1 consoleVerbosity, IEnumerable`1 unfilteredConsoleEvents) in E:\A\_work\300\s\src\Common\Tracing\TracingConfig.cs:line 25
   at Microsoft.Cascade.Agent.Program.ExecuteAsync() in E:\A\_work\300\s\src\Agent\Program.cs:line 272

**Comment by jasongin** [comment]
Note this is on an Ubuntu server.

**Comment by stephentoub** [comment]
cc: @tarekgh

**Comment by pkeogan** [comment]
```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300/

Host (useful for support):
  Version: 2.1.12
  Commit:  ccea2e606d

.NET Core SDKs installed:
  2.1.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by tarekgh** [comment]
This is the same issue https://github.com/dotnet/corefx/issues/37630 please look at my comment https://github.com/dotnet/corefx/issues/37630#issuecomment-492417775 to work around this. You shouldn't experience this issue at all if you are using 3.0.

**Comment by tarekgh** [comment]
https://github.com/dotnet/corefx/issues/37098

**Comment by pkeogan** [comment]
thanks @tarekgh

**Comment by pkeogan** [comment]
@tarekgh is there a `apt-get` package from net-core 3-preview-7?

**Comment by jasongin** [comment]
@pkeogan Even if you install .NET Core 3 on your system, Live Share won't use it. It always uses a private copy of .NET Core, currently version 2.2. We plan to update to 3.0 or 3.1 later this fall.

**Comment by pkeogan** [comment]
@jasongin copy that - ill look forward to that update then.

**Comment by tarekgh** [comment]
I know you will have to wait the Live Share to update to 3.0, just FYI for how you can get 3.0 preview builds is from the link https://dotnet.microsoft.com/download/dotnet-core/3.0

**Comment by jasongin** [comment]
Meanwhile the workaround mentioned at https://github.com/dotnet/corefx/issues/37630#issuecomment-492417775 should enable Live Share.
