### ISSUE TITLE
HTTP2: Rare HPack decoding error on inbound headers frame

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/corefx#40315]
I came across the following error when stress testing HTTP2 against Kestrel:
```
System.Net.Http.HttpRequestException: Error while copying content to a stream.
---> System.IO.IOException: The request was aborted.
---> System.Net.Http.HPack.HPackDecodingException: Dynamic table size update received after beginning of header block.
   at System.Net.Http.HPack.HPackDecoder.Decode(ReadOnlySpan`1 data, Boolean endHeaders, HeaderCallback onHeader, Object onHeaderState)
   at System.Net.Http.Http2Connection.ProcessHeadersFrame(FrameHeader frameHeader)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1 buffer, HttpResponseMessage responseMessage, CancellationToken cancellationToken)
   at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at HttpStress.RequestContext.SendAsync(HttpRequestMessage request, HttpCompletionOption httpCompletion, Nullable`1 token) in /home/eitsarpa/devel/dotnet/corefx/src/System.Net.Http/tests/StressTests/HttpStress/ClientOperations.cs:line 93
   at HttpStress.ClientOperations.<>c.<<get_Operations>b__1_2>d.MoveNext() in /home/eitsarpa/devel/dotnet/corefx/src/System.Net.Http/tests/StressTests/HttpStress/ClientOperations.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at HttpStress.StressClient.<>c__DisplayClass11_0.<<StartCore>g__RunWorker|0>d.MoveNext() in /home/eitsarpa/devel/dotnet/corefx/src/System.Net.Http/tests/StressTests/HttpStress/StressClient.cs:line 110
```
[Relevant code](https://github.com/dotnet/corefx/blob/b7e60c9aa17fbe043318afd68af31cd3a6d61a76/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HPack/HPackDecoder.cs#L212)

It occurred when sending a GET request which echoes a large number of randomly generated headers. Issue seems to be extremely rare, I've come across it only once so far.

cc @scalablecory

**Comment by geoffkizer** [comment]
This looks like a Kestrel issue. Is there a Kestrel issue filed? Or is there some reason to believe this is actually an issue with HttpClient?

**Comment by davidsh** [comment]
@eiriktsarpalis What is the status of this? At this point, perhaps this doesn't block 3.0 release especially if it is rare to repro?

cc: @stephentoub

**Comment by eiriktsarpalis** [comment]
@davidsh I haven't seen this issue happen a second time. I think we can probably move to future.

**Comment by eiriktsarpalis** [comment]
This was a one-off error observed one month ago, and it hasn't reproduced since. Fair to close at this point?

**Comment by geoffkizer** [comment]
I'm fine to close.
