### ISSUE TITLE
Intermittent test failure in System.IO.AsWinRTStreamTests.TestRead_MemoryStream_None

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#40348]
Failed in an unrelated PR (https://github.com/dotnet/corefx/pull/40303) on `Windows Build UWP_CoreCLR_x64_Debug`, specifically `uap-Windows_NT-Debug-x64-Windows.10.Amd64.ClientRS5.Open`.

https://dev.azure.com/dnceng/public/_build/results?buildId=311061

https://helix.dot.net/api/2019-06-17/jobs/1db5a054-02e9-4229-bfbb-206058a071f9/workitems/System.Runtime.WindowsRuntime.Tests/console

```text
  Starting:    System.Runtime.WindowsRuntime.Tests (parallel test collections = on, max threads = 2)
    System.IO.AsWinRTStreamTests.TestRead_MemoryStream_None [FAIL]
      Completion callback specified to ReadAsync callback must be invoked
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Runtime.WindowsRuntime/tests/System/IO/AsWinRTStreamTests.cs(255,0): at System.IO.AsWinRTStreamTests.DoTestRead(Func`1 createStreamFunc, InputStreamOptions inputStreamOptions, Boolean mustInvokeProgressHandler, Boolean completesSynchronously)
        /_/src/System.Runtime.WindowsRuntime/tests/System/IO/AsWinRTStreamTests.cs(143,0): at System.IO.AsWinRTStreamTests.TestRead_MemoryStream_None()
  Finished:    System.Runtime.WindowsRuntime.Tests
```

Looks like there was a similar failure earlier from https://github.com/dotnet/corefx/pull/39384#issuecomment-510653596

cc @jkoritzinsky, @wtgodbe, @JeremyKuhne

**Comment by ViktorHofer** [comment]
Failed again: https://dev.azure.com/dnceng/public/_build/results?buildId=356199&view=ms.vss-test-web.build-test-results-tab&runId=10789592&resultId=146559&paneView=debug

Configuration: uap-Windows_NT-Debug-x64-Windows.10.Amd64.ClientRS5.Open

```
  at System.IO.AsWinRTStreamTests.DoTestRead(Func`1 createStreamFunc, InputStreamOptions inputStreamOptions, Boolean mustInvokeProgressHandler, Boolean completesSynchronously) in /_/src/System.Runtime.WindowsRuntime/tests/System/IO/AsWinRTStreamTests.cs:line 255
   at System.IO.AsWinRTStreamTests.TestRead_MemoryStream_None() in /_/src/System.Runtime.WindowsRuntime/tests/System/IO/AsWinRTStreamTests.cs:line 143
```

I think we should disable the test.

**Comment by jkotas** [comment]
Failed again in https://github.com/dotnet/coreclr/pull/27437

**Comment by jkotas** [comment]
Failed again in https://github.com/dotnet/coreclr/pull/27632/

**Comment by jkotas** [comment]
Failed again in https://github.com/dotnet/coreclr/pull/27775

**Comment by jkotas** [comment]
Failed in https://github.com/dotnet/runtime/pull/406
