### ISSUE TITLE
IdFormat_HierarchicalWhenDefaultIsW3CButHierarchicalParentId fails in rolling builds

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#40373]
Test: `System.Diagnostics.Tests.ActivityTests.IdFormat_HierarchicalWhenDefaultIsW3CButHierarchicalParentId`
Affected configuration: `netcoreapp-Linux-Release-x64-RedHat.6.Amd64.Open`
Build: https://dnceng.visualstudio.com/public/_build/results?buildId=312716&view=ms.vss-test-web.build-test-results-tab&runId=9028500&resultId=136965&paneView=debug

Error message:
```
Timed out after 60000ms waiting for remote process.\n\tProcess ID: 2536\n\tHandle: 1020\n\tName: dotnet\n\tMainModule: /home/helixbot/work/2e69404a-55a1-4a35-8282-0f742594bb54/Payload/dotnet\n\tStartTime: 8/16/2019 12:45:58 AM\n\tTotalProcessorTime: 00:00:00.1100000\n
```

Stack trace:
```
  at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 131
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 55
   at System.Diagnostics.Tests.ActivityTests.IdFormat_HierarchicalWhenDefaultIsW3CButHierarchicalParentId() in /_/src/System.Diagnostics.DiagnosticSource/tests/ActivityTests.cs:line 590
```

cc @lmolkova @stephentoub

**Comment by lmolkova** [comment]
does the same problem happen with other tests that use RemoteExecutor or this is unique one?

This [test](https://github.com/dotnet/corefx/blob/d3911035f2ba3eb5c44310342cc1d654e42aa316/src/System.Diagnostics.DiagnosticSource/tests/ActivityTests.cs#L578) should be very fast and there is basically nothing that can hang or take a while.

**Comment by stephentoub** [comment]
Closing as likely dup of https://github.com/dotnet/coreclr/issues/27128
