### ISSUE TITLE
System.Text.Json : Failing at JsonDocument.Parse(json: fullName)

### ISSUE THREAD

**Issue by jmroyb** [dotnet/corefx#40437]
Hi,

testing "System.Text.Json" Version="4.6.0-preview8.19405.3" in VS 2019 16.2.2, I try to load a json file (UTF8 codified) with this content:

{
  "option1": "value1"
}

with var doc = JsonDocument.Parse(json: fullName) but I receive this exception:

System.Text.Json.JsonReaderException
  HResult=0x80131500
  Message='C' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, Utf8JsonReader reader, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at ConsoleCore.Program.Main(String[] args) in C:\SRC_HOST\Protos\0300\Proto.Runtime\ConsoleCore\Program.cs:line 27

 Please can you help me?

**Comment by khellang** [comment]
Hmm. Sounds like there's a BOM (or something, don't recognize the 'C' value) in there? Might be fixed with https://github.com/dotnet/corefx/pull/38470?

**Comment by jmroyb** [comment]
Attached!
[test.zip](https://github.com/dotnet/corefx/files/3519176/test.zip)

**Comment by jmroyb** [comment]
@khellang 

I have changed from UTF8 to UTF8 with BOM using Notepad++ but same exception is raised again.

Cheers

**Comment by am11** [comment]
I think the issue is that you are passing in path, instead of content, the I/O operation would need a separate call:

```diff
- JsonDocument.Parse("C:/path/to/test.json");
+ JsonDocument.Parse(System.IO.File.ReadAllText("C:/path/to/test.json"));
```

**Comment by ahsonkhan** [comment]
Can you share the repro app, because I can't repro the issue.
```C#
string jsonString = File.ReadAllText(@"E:\test.json");
using (JsonDocument dom = JsonDocument.Parse(jsonString))
{
Assert.Equal("{\r\n  \"option1\": \"value1\"\r\n}", dom.RootElement.ToString());
}
```

> I think the issue is that you are passing in path, instead of content, the I/O operation would need a separate call

That's probably it :)
Good guess @am11

**Comment by jmroyb** [comment]
Hi @am11 

Solved. You were right. I had to pass json content instead filename. Now works:

![doc](https://user-images.githubusercontent.com/4932314/63350978-4d1f2000-c356-11e9-8f0d-3dd0dfda67ba.png)

Cheers!!!
