### ISSUE TITLE
3 Name Resolution Tests fail on OSX

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#4056]
```
   System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName [FAIL]
      Assert.Equal() Failure
      Expected: Success
      Actual:   HostNotFound
      Stack Trace:
            at System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName()
            at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
            at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
            at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_HostName [FAIL]
      System.Net.Internals.InternalSocketException : Unknown error: 11001
      Stack Trace:
            at System.Net.NameResolutionPal.GetHostByName(String hostName)
            at System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_HostName()
            at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
            at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
            at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName_TryGetNameInfo [FAIL]
      Assert.Equal() Failure
      Expected: Success
      Actual:   HostNotFound
      Stack Trace:
            at System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName_TryGetNameInfo()
            at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
            at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
            at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Seeing this on my local mac (which is connected to Corp-Net, so maybe that's an issue.  Let me know if you need help getting a repo @pgavlin),

**Comment by pgavlin** [comment]
@ellismg I cannot repro this locally. Let's chat offline.

**Comment by pgavlin** [comment]
These turned out to be a machine configuration issue: as implied by the failing tests, the machine was not able to resolve its own hostname to an address.
