### ISSUE TITLE
HTTP2: Server doesn't completely read request - The CancellationTokenSource has been disposed - V2

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#40686]
Related to https://github.com/dotnet/corefx/issues/40207

This error is occasionally showing up again when running tests on the gRPC build:

https://travis-ci.org/grpc/grpc-dotnet/builds/578263972#L424

```
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The request was aborted.
 ---> System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.Cancel()
   at System.Net.Http.Http2Connection.Http2Stream.OnReset(Exception resetException, Nullable`1 resetStreamErrorCode, Boolean canRetry)
   at System.Net.Http.Http2Connection.ProcessRstStreamFrame(FrameHeader frameHeader)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Grpc.Net.Client.Internal.GrpcCall`2.SendAsync(HttpRequestMessage request) in /home/travis/build/grpc/grpc-dotnet/src/Grpc.Net.Client/Internal/GrpcCall.cs:line 565
   at Grpc.Net.Client.Internal.GrpcCall`2.GetResponseHeadersAsync() in /home/travis/build/grpc/grpc-dotnet/src/Grpc.Net.Client/Internal/GrpcCall.cs:line 278
```

The original fix in #40207 was to not dispose of the CTS when it hasn't been created via `CreateLinkedTokenSource`. That appears to have worked most of the time, but occasionally the test still fails on the build server.

I can no longer reproduce the error locally.

**Comment by JamesNK** [comment]
Hmm, the build server is on 3.0.100-preview9-013927, which is older from the 3.0.100-rc1-014031. I don't know if that matters. I'll try updating the server source to use the latest RC and see whether the issue continues to show up.

**Comment by stephentoub** [comment]
I expect 3.0.100-preview9-013927 doesn't have https://github.com/dotnet/corefx/pull/40264.

**Comment by JamesNK** [comment]
I've updated to build to use 3.0.100-rc1-014031. Closing this.

If the error re-occurs then I'll re-open.
