### ISSUE TITLE
Few non loopback networking tests fail with 503 - (Server has been shutdown)

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#40690]
https://dev.azure.com/dnceng/public/_build/results?buildId=322522&view=ms.vss-test-web.build-test-results-tab&runId=9350278&resultId=158117&paneView=debug

```
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() in /_/src/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs:line 179
   at System.Net.Http.HttpClient.FinishGetStreamAsync(Task`1 getTask) in /_/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 296
   at System.Net.Http.Functional.Tests.HttpClientHandler_MaxResponseHeadersLength_Test.SetAfterUse_Throws() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.MaxResponseHeadersLength.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
```

@wfurt @davidsh looks like our remote networking endpoint was offline for a while. Do you think we can prevent such drops? Ie geo redundancy.

cc @stephentoub

**Comment by davidsh** [comment]
>@wfurt @davidsh looks like our remote networking endpoint was offline for a while. Do you think we can prevent such drops? Ie geo redundancy.

The remote server is running in Azure App Service. We can look into spending more money and scaling up more instances of the web app. But we don't have a lot of control in how it is geo-replicated.  To have that, we would need to move it to dedicated VMs in regions etc. And that means more infrastructure overhead etc.

There are also parts of Azure we don't control at all such as front-end load balancers and reverse proxies into Azure App Service.

How often is that happening? If it's only every once in a while, then it really is just the normal cost of having remote endpoints and we can live with some downtime.

I think we should continue to focus on moving more tests to loopback server. And I think that for non-loopback server tests, we should consider a more isolated environment for the client and server (i.e. think dedicated lab) that would remove any 'internet' latency.

**Comment by ViktorHofer** [comment]
> I think we should continue to focus on moving more tests to loopback server.

Exactly. Could you please open an issue with a list of candidates to move to loopback server? I'm sure the community is willing to help here.

**Comment by ViktorHofer** [comment]
Failed again: https://dev.azure.com/dnceng/public/_build/results?buildId=353190&view=ms.vss-test-web.build-test-results-tab&runId=10640904&paneView=debug&resultId=178143

Configuration: `netcoreapp-Windows_NT-Release-x86-Windows.10.Amd64.ClientRS4.ES.Open`

```
System.Threading.Tasks.TaskCanceledException : The operation was canceled.\r\n---- System.IO.IOException : Unable to read data from the transport connection: La operación de E/S se anuló por una salida de subproceso o por una solicitud de aplicación..\r\n-------- System.Net.Sockets.SocketException : La operación de E/S se anuló por una salida de subproceso o por una solicitud de aplicación.

 at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs:line 712
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 566
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 537
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 33
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in /_/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 553
   at System.Net.Http.HttpClient.FinishGetStreamAsync(Task`1 getTask) in /_/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 294
   at System.Net.Http.Functional.Tests.HttpClientHandler_MaxResponseHeadersLength_Test.SetAfterUse_Throws() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.MaxResponseHeadersLength.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1110
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token) in /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1076
   at System.Net.Http.HttpConnection.FillAsync() in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs:line 1446
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs:line 1343
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs:line 513
```
