### ISSUE TITLE
A few loopback server tests are timing out in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#40712]
```   System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http2.PostAsync_CancelDuringRequestContentSend_TaskCanceledQuickly(chunkedTransfer: False, mode: Token) [FAIL]
      System.TimeoutException : Task timed out after 00:01:00
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(42,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs(215,0): at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout)
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(38,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs(45,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.PostAsync_CancelDuringRequestContentSend_TaskCanceledQuickly(Boolean chunkedTransfer, CancellationMode mode)
        --- End of stack trace from previous location where exception was thrown ---
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Finalization_Http2_Test.IncompleteResponseStream_ResponseDropped_CancelsRequestToServer [FAIL]
      System.TimeoutException : Task timed out after 00:01:00
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(42,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs(215,0): at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout)
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(38,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Finalization.cs(34,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Finalization_Test.IncompleteResponseStream_ResponseDropped_CancelsRequestToServer()
        --- End of stack trace from previous location where exception was thrown ---
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ConnectionPooling_Test.Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection(timeoutPropertyName: "PooledConnectionLifetime") [FAIL]
      System.TimeoutException : Task timed out after 00:01:00
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(42,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs(207,0): at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout)
        /_/src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs(1606,0): at System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ConnectionPooling_Test.Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection(String timeoutPropertyName)
        --- End of stack trace from previous location where exception was thrown ---
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http2.GetAsync_AddMultipleCookieHeaders_CookiesSent [FAIL]
      System.TimeoutException : Task timed out after 00:01:00
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(42,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs(215,0): at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout)
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(38,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cookies.cs(150,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Cookies.GetAsync_AddMultipleCookieHeaders_CookiesSent()
        --- End of stack trace from previous location where exception was thrown ---
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http2.SendAsync_WithZeroLengthHeaderName_Throws [FAIL]
      System.TimeoutException : Task timed out after 00:01:00
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(42,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs(215,0): at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout)
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(38,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Headers.cs(272,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Headers.SendAsync_WithZeroLengthHeaderName_Throws()
        --- End of stack trace from previous location where exception was thrown ---
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.PostAsync_ManyDifferentRequestHeaders_SentCorrectly [FAIL]
      System.TimeoutException : Task timed out after 00:01:00
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(42,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs(215,0): at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout)
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(38,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs(789,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.PostAsync_ManyDifferentRequestHeaders_SentCorrectly()
        --- End of stack trace from previous location where exception was thrown ---
```

**Comment by ViktorHofer** [comment]
@davidsh, @wfurt, @scalablecory, @eiriktsarpalis, @karelz
