### ISSUE TITLE
AsymmetricEncryptionRoundtrip(useOAEP: False) test failed

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#40759]
uap-Windows_NT-Debug-x64-Windows.10.Amd64.ClientRS5.Open
https://dev.azure.com/dnceng/public/_build/results?buildId=334933&view=ms.vss-test-web.build-test-results-tab&runId=9864152&resultId=100224&paneView=attachments
```    System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric.AsymmetricEncryptionRoundtrip(useOAEP: False) [FAIL]
      System.Security.Cryptography.CryptographicException : Padding is invalid and cannot be removed.
      Stack Trace:
        /_/src/Common/src/Internal/Cryptography/UniversalCryptoDecryptor.cs(211,0): at Internal.Cryptography.UniversalCryptoDecryptor.DepadBlock(Byte[] block, Int32 offset, Int32 count)
        /_/src/Common/src/Internal/Cryptography/UniversalCryptoDecryptor.cs(104,0): at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
        /_/src/Common/src/Internal/Cryptography/UniversalCryptoTransform.cs(100,0): at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
        /_/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/EncryptedXml.cs(751,0): at System.Security.Cryptography.Xml.EncryptedXml.DecryptData(EncryptedData encryptedData, SymmetricAlgorithm symmetricAlgorithm)
        /_/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/EncryptedXml.cs(656,0): at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument()
        /_/src/System.Security.Cryptography.Xml/tests/Samples/EncryptingDecryptingAsymmetric.cs(78,0): at System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric.Decrypt(XmlDocument doc, RSA rsaKey, String keyName)
        /_/src/System.Security.Cryptography.Xml/tests/Samples/EncryptingDecryptingAsymmetric.cs(101,0): at System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric.AsymmetricEncryptionRoundtrip(Boolean useOAEP)
```

**Comment by stephentoub** [comment]
This test fails for me locally every time I run it.  Sometimes it fails with:
```
      System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric.AsymmetricEncryptionRoundtrip(useOAEP: False) [FAIL]
        System.Security.Cryptography.CryptographicException : Padding is invalid and cannot be removed.
        Stack Trace:
          D:\repos\corefx\src\Common\src\Internal\Cryptography\UniversalCryptoDecryptor.cs(211,0): at Internal.Cryptography.UniversalCryptoDecryptor.DepadBlock(Byte[] block, Int32 offset, Int32 count)
          D:\repos\corefx\src\Common\src\Internal\Cryptography\UniversalCryptoDecryptor.cs(104,0): at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
          D:\repos\corefx\src\Common\src\Internal\Cryptography\UniversalCryptoTransform.cs(100,0): at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
          D:\repos\corefx\src\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\EncryptedXml.cs(751,0): at System.Security.Cryptography.Xml.EncryptedXml.DecryptData(EncryptedData encryptedData, SymmetricAlgorithm symmetricAlgorithm)
          D:\repos\corefx\src\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\EncryptedXml.cs(656,0): at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument()
          d:\repos\corefx\src\System.Security.Cryptography.Xml\tests\Samples\EncryptingDecryptingAsymmetric.cs(78,0): at System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric.Decrypt(XmlDocument doc, RSA rsaKey, String keyName)
          d:\repos\corefx\src\System.Security.Cryptography.Xml\tests\Samples\EncryptingDecryptingAsymmetric.cs(101,0): at System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric.AsymmetricEncryptionRoundtrip(Boolean useOAEP)
```
and sometimes with:
```
      System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric.AsymmetricEncryptionRoundtrip(useOAEP: False) [FAIL]
        System.Xml.XmlException : Data at the root level is invalid. Line 1, position 1.
        Stack Trace:
          D:\repos\corefx\src\System.Private.Xml\src\System\Xml\Core\XmlTextReaderImpl.cs(2743,0): at System.Xml.XmlTextReaderImpl.Throw(Exception e)
          D:\repos\corefx\src\System.Private.Xml\src\System\Xml\Core\XmlTextReaderImpl.cs(2712,0): at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
          D:\repos\corefx\src\System.Private.Xml\src\System\Xml\Core\XmlTextReaderImpl.cs(2702,0): at System.Xml.XmlTextReaderImpl.Throw(String res)
          D:\repos\corefx\src\System.Private.Xml\src\System\Xml\Core\XmlTextReaderImpl.cs(6008,0): at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
          D:\repos\corefx\src\System.Private.Xml\src\System\Xml\Core\XmlTextReaderImpl.cs(4078,0): at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
          D:\repos\corefx\src\System.Private.Xml\src\System\Xml\Core\XmlTextReaderImpl.cs(1201,0): at System.Xml.XmlTextReaderImpl.Read()
          D:\repos\corefx\src\System.Private.Xml\src\System\Xml\Dom\XmlLoader.cs(50,0): at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
          D:\repos\corefx\src\System.Private.Xml\src\System\Xml\Dom\XmlDocument.cs(1336,0): at System.Xml.XmlDocument.Load(XmlReader reader)
          D:\repos\corefx\src\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\EncryptedXml.cs(786,0): at System.Security.Cryptography.Xml.EncryptedXml.ReplaceData(XmlElement inputElement, Byte[] decryptedData)
          D:\repos\corefx\src\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\EncryptedXml.cs(657,0): at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument()
          d:\repos\corefx\src\System.Security.Cryptography.Xml\tests\Samples\EncryptingDecryptingAsymmetric.cs(78,0): at System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric.Decrypt(XmlDocument doc, RSA rsaKey, String keyName)
          d:\repos\corefx\src\System.Security.Cryptography.Xml\tests\Samples\EncryptingDecryptingAsymmetric.cs(101,0): at System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric.AsymmetricEncryptionRoundtrip(Boolean useOAEP)
```

**Comment by bartonjs** [comment]
It's probably all the same as the other PKCS#1 padding problems, and I'm guessing doesn't repro in Retail

**Comment by bartonjs** [comment]
That is, it's probably the same OS bug as #40434

**Comment by Anipik** [comment]
Failing again in https://github.com/dotnet/corefx/pull/41294

**Comment by danmosemsft** [comment]
Still at least one failing that is not disabled in master.
Need forward port of https://github.com/dotnet/corefx/pull/41360/files#diff-8b2ba9178a4de511a959ba54abf2f6c4
```
          <test name="System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric.AsymmetricEncryptionRoundtrip(useOAEP: False)" type="System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric" method="AsymmetricEncryptionRoundtrip" time="0.1043635" result="Fail">
        <failure exception-type="System.Security.Cryptography.CryptographicException">
          <message><![CDATA[System.Security.Cryptography.CryptographicException : Padding is invalid and cannot be removed.]]></message>
          <stack-trace><![CDATA[   at Internal.Cryptography.UniversalCryptoDecryptor.DepadBlock(Byte[] block, Int32 offset, Int32 count) in C:\git\corefx\src\Common\src\Internal\Cryptography\UniversalCryptoDecryptor.cs:line 211
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount) in C:\git\corefx\src\Common\src\Internal\Cryptography\UniversalCryptoDecryptor.cs:line 104
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount) in C:\git\corefx\src\Common\src\Internal\Cryptography\UniversalCryptoTransform.cs:line 100
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptData(EncryptedData encryptedData, SymmetricAlgorithm symmetricAlgorithm) in C:\git\corefx\src\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\EncryptedXml.cs:line 751
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument() in C:\git\corefx\src\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\EncryptedXml.cs:line 656
   at System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric.Decrypt(XmlDocument doc, RSA rsaKey, String keyName) in C:\git\corefx\src\System.Security.Cryptography.Xml\tests\Samples\EncryptingDecryptingAsymmetric.cs:line 78
   at System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric.AsymmetricEncryptionRoundtrip(Boolean useOAEP) in C:\git\corefx\src\System.Security.Cryptography.Xml\tests\Samples\EncryptingDecryptingAsymmetric.cs:line 101]]></stack-trace>
        </failure>
      </test>
```
