### ISSUE TITLE
Several Outerloop System.Net.Socket tests broken by TcpClient change

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#40765]
Regressed by https://github.com/dotnet/corefx/pull/37462
```C#
      System.Net.Sockets.Tests.TcpClientTest.ExclusiveAddressUse_NullClient [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
          d:\repos\corefx\src\System.Net.Sockets\src\System\Net\Sockets\TCPClient.cs(121,0): at System.Net.Sockets.TcpClient.set_Client(Socket value)
          d:\repos\corefx\src\System.Net.Sockets\tests\FunctionalTests\TcpClientTest.cs(255,0): at System.Net.Sockets.Tests.TcpClientTest.ExclusiveAddressUse_NullClient()
      System.Net.Sockets.Tests.TcpClientTest.Dispose_CancelsConnectAsync(connectByName: False) [FAIL]
        Assert.Null() Failure
        Expected: (null)
        Actual:   Socket { AddressFamily = InterNetworkV6, Available = (throws ObjectDisposedException), Blocking = True, Connected = False, DontFragment = (throws NotSupportedException), ... }
        Stack Trace:
          d:\repos\corefx\src\System.Net.Sockets\tests\FunctionalTests\TcpClientTest.cs(440,0): at System.Net.Sockets.Tests.TcpClientTest.Dispose_CancelsConnectAsync(Boolean connectByName)
          --- End of stack trace from previous location where exception was thrown ---
      System.Net.Sockets.Tests.TcpClientTest.Dispose_CancelsConnectAsync(connectByName: True) [FAIL]
        Assert.Null() Failure
        Expected: (null)
        Actual:   Socket { AddressFamily = InterNetworkV6, Available = (throws ObjectDisposedException), Blocking = True, Connected = False, DontFragment = (throws NotSupportedException), ... }
        Stack Trace:
          d:\repos\corefx\src\System.Net.Sockets\tests\FunctionalTests\TcpClientTest.cs(440,0): at System.Net.Sockets.Tests.TcpClientTest.Dispose_CancelsConnectAsync(Boolean connectByName)
          --- End of stack trace from previous location where exception was thrown ---
      System.Net.Sockets.Tests.TcpClientTest.ConnectedAvailable_NullClient [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
          d:\repos\corefx\src\System.Net.Sockets\src\System\Net\Sockets\TCPClient.cs(121,0): at System.Net.Sockets.TcpClient.set_Client(Socket value)
          d:\repos\corefx\src\System.Net.Sockets\tests\FunctionalTests\TcpClientTest.cs(242,0): at System.Net.Sockets.Tests.TcpClientTest.ConnectedAvailable_NullClient()
      System.Net.Sockets.Tests.TcpClientTest.Connect_DnsEndPoint_Success(mode: 1) [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
          d:\repos\corefx\src\System.Net.Sockets\src\System\Net\Sockets\TCPClient.cs(121,0): at System.Net.Sockets.TcpClient.set_Client(Socket value)
          d:\repos\corefx\src\System.Net.Sockets\tests\FunctionalTests\TcpClientTest.cs(196,0): at System.Net.Sockets.Tests.TcpClientTest.Connect_DnsEndPoint_Success(Int32 mode)
```
cc: @tmds

**Comment by tmds** [comment]
The tests expect `Client` to return `null` when `TcpClient` was disposed. Now it is throwing ODE.
Is it desired to keep the existing behavior?

**Comment by stephentoub** [comment]
> Now it is throwing ODE.

In some cases it's null ref'ing now, e.g. when you set TcpClient.Client to null (without having disposed the TcpClient) and then access TcpClient.Client, it dereferences the null _clientSocket to access its AddressFamily.

> Should I change back to returning null or change the tests?

There's no good reason to break compatibility here.  The implementation should be fixed.
