### ISSUE TITLE
Test failure: System.Diagnostics.Tests.EventLogTraceListenerTests.TraceEventTest

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#40799]
Test `System.Diagnostics.Tests.EventLogTraceListenerTests.TraceEventTest` has failed.
```
System.Diagnostics.Tests.EventLogTraceListenerTests.TraceEventTest(eventType: Information, expectedType: Information, id: 65536, expectedId: 65535) [FAIL]
      System.AggregateException : One or more errors occurred. (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.)
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      Stack Trace:
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(45,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
           at System.Diagnostics.Tests.Helpers.Retry[T](Func`1 func)
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(24,0): at System.Diagnostics.Tests.Helpers.Retry(Action func)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTraceListenerTests.cs(144,0): at System.Diagnostics.Tests.EventLogTraceListenerTests.TraceEventTest(TraceEventType eventType, EventLogEntryType expectedType, Int32 id, Int32 expectedId)
        ----- Inner Stack Trace #1 (System.ComponentModel.Win32Exception) -----
```
Details:
https://dnceng.visualstudio.com/public/_build/results?buildId=336472&view=ms.vss-test-web.build-test-results-tab&runId=9915160&resultId=178996&paneView=debug

**Comment by ViktorHofer** [comment]
@danmosemsft looks like the retry isn't working on 19H1 for EventLog. We will probably want to turn off the tests again or talk with Windows to investigate further.

**Comment by danmosemsft** [comment]
Is this across many/all event log tests? If not, we can fairly liberally disable since we don't need much coverage given we're not changing the code.

What if we make the retries huge temporarily (eg., retry 500 times, but count over 100 as a failure, and log how many) - that would tell us whether it's a consistent problem once it occurs or not.

If it's a widespread problem maybe the next step is to make a repro and talk to the Windows team - although I'm not sure what they could do save give us better ways to retry things.

cc @Anipik

**Comment by ViktorHofer** [comment]
It's just two tests which I recently re-enabled. I sent a PR to disable them again (https://github.com/dotnet/corefx/pull/40876) and close this issue. If we encounter additional failing tests we can/should continue our discussion here.
