### ISSUE TITLE
ERROR: Unknown error -1 In System.Net.Sockets.Socket.DoBeginSendT

### ISSUE THREAD

**Issue by wjdavis5** [dotnet/corefx#40809]
**Setup**:
Container Image: mcr.microsoft.com/dotnet/core/aspnet:2.2.4
Docker: 19.03.1
Docker Swarm Mode
Using Ingress Routing
Host: Ubuntu 16.04

This app has been running for 2 years on various flavors of .net core, this issues just started happening in a lower level environment a few weeks ago.

I can spin this up in a container locally and it processes fine so I'm going to assume there is something smelly going on with either swarm mode ingress routing or perhaps the host itself? But I'm not sure where to go next Log wise to track this down. Is there a way I can enable verbose output in the container to try and find something? Or is this a known issue and I just dont know how to search?

**Error**
```
2019-09-04 13:55:09,483 ERROR: Unknown error -1
at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
at System.Net.Sockets.UdpClient.BeginSend(Byte[] datagram, Int32 bytes, IPEndPoint endPoint, AsyncCallback requestCallback, Object state)
at System.Net.Sockets.UdpClient.<>c.<SendAsync>b__54_0(Byte[] targetDatagram, Int32 targetBytes, IPEndPoint targetEndpoint, AsyncCallback callback, Object state)
at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
at System.Threading.Tasks.TaskFactory`1.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
at System.Net.Sockets.UdpClient.SendAsync(Byte[] datagram, Int32 bytes, IPEndPoint endPoint)
at Synovia.Core.Listener.SbssUdpServer.SendTo(Byte[] datagram, IPEndPoint remoteEndPoint) in /app/src/ListenerCore/SbssUdpServer.cs:line 47
at Synovia.Core.Listener.Processors.OutboundMessageProcessor.OnConsumerOnReceived(Object model, BasicDeliverEventArgs ea) in /app/src/ListenerCore/Processors/OutboundMessageProcessor.cs:line 113

```

**Relevant Code Paths**

```
//SbssUdpServer
private static readonly object Lock = new object();
private UdpClient UdpClient { get; set; }
....
public SbssUdpServer(ListenerHardwareInformation hardware,ILogger logging,IMessageProcessor messageProcessor, IMessageProcessor bentPipMessageProcessor = null)
        {
            UdpClient = new UdpClient(hardware.IpPort);
            Logging = logging;
            MessageProcessor = messageProcessor;
            BentPipMessageProcessor = bentPipMessageProcessor;
            _hardware = hardware;
            _hardwareType = (SbssEnumerations.HardwareTypes)_hardware.HardwareTypeId;
        }

public void SendTo(byte[] datagram,IPEndPoint remoteEndPoint)
        {
            lock (Lock)
            {
                UdpClient.SendAsync(datagram, datagram.Length, remoteEndPoint);
            }
        }
...
...
//AckMessageProcessor
 public virtual void ProcessMessage(IMessage message)
        {
            #region guards
                if(message?.MessageBytes == null || message.RemoteEndPoint == null) throw new ArgumentNullException($"Null value found sending message!");
            #endregion  
            UdpServer.SendTo(message.MessageBytes,message.RemoteEndPoint);
        }
...
...


private void OnConsumerOnReceived(object model, BasicDeliverEventArgs ea)
        {
            //msg format = Base64 json string
            //1) Convert from byte to string
            //3) Deserialize string to OutboundMessage
            try
            {
                using (DogStatsd.StartTimer("OutboundMessageProcessing"))
                {
                    var channel = (IBasicConsumer) model;
                    var strObj = Encoding.UTF8.GetString(ea.Body);
                    var msg = (OutboundMessage) JsonConvert.DeserializeObject(strObj, typeof(OutboundMessage));
                    Logger.LogDebug($"Processing Outbound Message {strObj}");

                    Logger.LogDebug(strObj);
                    if (msg.MessageBytes == null || string.IsNullOrEmpty(msg.IpAddress))
                    {
                        Logger.LogWarning("Outbound message has a null byte array ! I'm going to ack this thing.");
                        channel.Model.BasicAck(ea.DeliveryTag, false);
                        return;
                    }

                    AckMessageProcessor.ProcessMessage(msg);


                    channel.Model.BasicAck(ea.DeliveryTag, false);
                }
            }
            catch (Exception exception)
            {
                Logger.LogError("{0} \n {1}", exception.Message, exception.StackTrace);
                SetupRabbitChannel();
            }

        }
```

**Comment by stephentoub** [comment]
Can you use `strace` to see what error you're actually getting back from the OS?  My guess is it's EPERM, such that this new lower-level environment needs something special configured to allow you to do what you're trying to do.  If that's true, the bug at the .NET level was just not surfacing that error correctly, reporting it as -1 rather than as EPERM; that was issue https://github.com/dotnet/corefx/issues/35127, fixed in .NET Core 3.0 in https://github.com/dotnet/corefx/pull/35133.

**Comment by wjdavis5** [comment]
Here is the strace output:
https://gist.github.com/wjdavis5/925a0d31b5ddee576860278030fbcc75

I believe this to be the relevant output::

```
munmap(0x7ff4e8004000, 65536)           = 0
write(92, "System.Net.Internals.SocketExcep"..., 256System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 6): No such device or address
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previo) = 256
write(92, "us location where exception was "..., 256us location where exception was thrown ---
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncR) = 256
write(92, "esult)\n   at System.Threading.Ta"..., 256esult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   ) = 256
write(92, "at Synovia.Core.Listener.Program"..., 256at Synovia.Core.Listener.Program.GetIpFromAddress(String value) in /app/src/ListenerCore/Program.cs:line 342
   at Synovia.Core.Listener.Program.ConfigureRedis() in /app/src/ListenerCore/Program.cs:line 299
   at Synovia.Core.Listener.Program.Configure(Str) = 256
write(92, "ing[] args) in /app/src/Listener"..., 157ing[] args) in /app/src/ListenerCore/Program.cs:line 222
   at Synovia.Core.Listener.Program.Main(String[] args) in /app/src/ListenerCore/Program.cs:line 93
) = 157
```

**Comment by wjdavis5** [comment]
Welp when I run this manually in a container, so I can enable ptrace, (opposed to on the swarm) it doesnt throw this same error....

**Comment by wjdavis5** [comment]
Update on this - I confirmed that when I switch the docker swarm service to use HOST port publishing instead of INGRESS the issue goes away. @stephentoub  - Do you have any suggestions on how I can call strace in a swarm service? Currently you have to pass in : 
```
--security-opt=seccomp:unconfined
```

When you startup the container, and this is not supported in swarm mode:
https://github.com/moby/moby/issues/25209

**Comment by stephentoub** [comment]
@wjdavis5, would it be easier to try using .NET Core 3.0?

**Comment by wfurt** [comment]
note that you can also strace from host once you find corresponding PID. That avoids issues with reconfiguring container.

**Comment by wjdavis5** [comment]
Dang... good call didnt even consider going that direction.

**Comment by wfurt** [comment]
did you have any luck collecting the trace @wjdavis5 ?

**Comment by wjdavis5** [comment]
Ill spend some time on this tomorrow.
