### ISSUE TITLE
Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection times out on arm64

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#40878]
System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ConnectionPooling_Test.Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection

Configuration: `netcoreapp-Windows_NT-Release-arm64-Windows.10.Arm64.Open`

https://dnceng.visualstudio.com/public/_build/results?buildId=340789&view=ms.vss-test-web.build-test-results-tab&runId=10076876&paneView=debug

```
System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ConnectionPooling_Test.Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection(timeoutPropertyName: "PooledConnectionLifetime") [FAIL]
      System.TimeoutException : Task timed out after 00:01:00
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(42,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs(207,0): at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout)
        /_/src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs(1606,0): at System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ConnectionPooling_Test.Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection(String timeoutPropertyName)
        --- End of stack trace from previous location where exception was thrown ---
``´

@davidsh, @wfurt, @scalablecory, @eiriktsarpalis, @karelz

**Comment by ViktorHofer** [comment]
@davidsh, @wfurt, @scalablecory, @eiriktsarpalis, @karelz
