### ISSUE TITLE
System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_FileName(fileName: \"C:\\\\dotnetbuild\\\\work\\\\1c624edc-982b-4c35-b93c-6e0\"..., size: {Width=16, Height=16}) test failed

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#40877]
System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_FileName(fileName: \"C:\\\\dotnetbuild\\\\work\\\\1c624edc-982b-4c35-b93c-6e0\"..., size: {Width=16, Height=16})

https://dnceng.visualstudio.com/public/_build/results?buildId=340929&view=ms.vss-test-web.build-test-results-tab&runId=10083712&resultId=111257&paneView=debug

```
System.ArgumentException : Parameter is not valid.

  at System.Drawing.Image.get_Width()
   at System.Drawing.Image.get_Size()
   at System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_FileName(String fileName, Size size) in /_/src/System.Drawing.Common/tests/ToolboxBitmapAttributeTests.cs:line 61
```

@safern we should investigate and/or disable the test to protect CI.

**Comment by danmosemsft** [comment]
`netfx-Windows_NT-Release-x64-Windows.10.Amd64.ClientRS5.Open`

netfx so we just disable then ?

**Comment by safern** [comment]
Since it is netfx, let's just skip it in that framework.
