### ISSUE TITLE
Message_ShouldFormatCountOfRootCausesUsingTheCurrentCulture test failed in CI on UAP

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#40899]
```
C:\dotnetbuild\work\c71fee18-1413-44e3-abc2-d15744bffa90\Work\5e9317f6-b4e2-44b9-9be7-60b734371f6b\Exec>XUnitRunnerUap System.ComponentModel.Composition.Tests.dll -xml "C:\Users\runner\AppData\Local\Packages\5cd54353-3ed7-4a6e-a72f-db349f28867c_v52bfwc2c21ha\LocalState\System.ComponentModel.Composition.Tests.xml" -nologo -nocolor -notrait category=nonuaptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.ComponentModel.Composition.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.ComponentModel.Composition.Tests (found 1500 of 1630 test cases)
  Starting:    System.ComponentModel.Composition.Tests (parallel test collections = on, max threads = 2)
Unhandled exception. Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 96
   at Xunit.Assert.True(Boolean condition) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 63
   at System.ComponentModel.Composition.CompositionExceptionTests.AssertMessage(CompositionException exception, Int32 rootCauseCount, CultureInfo culture) in /_/src/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/CompositionExceptionTests.cs:line 420
   at System.ComponentModel.Composition.CompositionExceptionTests.<Message_ShouldFormatCountOfRootCausesUsingTheCurrentCulture>b__31_0() in /_/src/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/CompositionExceptionTests.cs:line 383
--- End of stack trace from previous location where exception was thrown ---
   at Xunit.ConsoleClient.RemoteExecutor.Execute(String[] args)
   at Xunit.ConsoleClient.ConsoleRunner.EntryPoint(String[] args)
   at Xunit.ConsoleClient.Program.Main(String[] args)
    System.ComponentModel.Composition.CompositionExceptionTests.Message_ShouldFormatCountOfRootCausesUsingTheCurrentCulture [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.TrueException: Assert.True() Failure
        Expected: True
        Actual:   False
        /_/src/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/CompositionExceptionTests.cs(420,0): at System.ComponentModel.Composition.CompositionExceptionTests.AssertMessage(CompositionException exception, Int32 rootCauseCount, CultureInfo culture)
        /_/src/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/CompositionExceptionTests.cs(383,0): at System.ComponentModel.Composition.CompositionExceptionTests.<Message_ShouldFormatCountOfRootCausesUsingTheCurrentCulture>b__31_0()
        
        Child process:
          System.ComponentModel.Composition.Tests, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.ComponentModel.Composition.CompositionExceptionTests Int32 <Message_ShouldFormatCountOfRootCausesUsingTheCurrentCulture>b__31_0()
        
        
  Finished:    System.ComponentModel.Composition.Tests
```

**Comment by stephentoub** [comment]
Ironically this failed on https://github.com/dotnet/corefx/issues/40773.
