### ISSUE TITLE
IgnoreNullValues functionality broken

### ISSUE THREAD

**Issue by findyoucef** [dotnet/corefx#40922]
Setting JsonSerializerOptions property of IgnoreNullValues to true does not work. 

When attempting to deserialize a DateTime value that is null in the json string it throws the exception below. I thought setting the option to IgnoreNullValues should ignore the property, no?

converted to System.DateTime. Path: $.value[0].deletedDateTime 
InvalidOperationException: Cannot get the value of a token type 'Null' as a string.

Thanks
Youcef

**Comment by ViktorHofer** [comment]
cc @ahsonkhan, @steveharter

**Comment by ahsonkhan** [comment]
Here's a sample repro:

```C#
[Fact]
public static void IgnoreNullValuesBug()
{
    JsonSerializer.Deserialize<Temp>("{\"Foo\": null}", new JsonSerializerOptions { IgnoreNullValues = true });
}

public class Temp
{
    public DateTime Foo { get; set; }
}
```

```text
System.Text.Json.Tests.Utf8JsonReaderTests.IgnoreNullValuesBug [FAIL]
        System.Text.Json.JsonException : The JSON value could not be converted to System.DateTime. Path: $ | LineNumber: 0 | BytePositionInLine: 12.
        ---- System.InvalidOperationException : Cannot get the value of a token type 'Null' as a string.
        Stack Trace:
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\ThrowHelper.Serialization.cs(178,0): at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.cs(118,0): at System.Text.Json.JsonSerializer.ReadCoreSync(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.Span.cs(61,0): at System.Text.Json.JsonSerializer.ParseCore(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.String.cs(68,0): at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.String.cs(31,0): at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
          E:\GitHub\Fork\corefx\src\System.Text.Json\tests\Utf8JsonReaderTests.cs(20,0): at System.Text.Json.Tests.Utf8JsonReaderTests.IgnoreNullValuesBug()
          ----- Inner Stack Trace -----
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Reader\Utf8JsonReader.TryGet.cs(820,0): at System.Text.Json.Utf8JsonReader.TryGetDateTime(DateTime& value)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Reader\Utf8JsonReader.TryGet.cs(396,0): at System.Text.Json.Utf8JsonReader.GetDateTime()
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\Converters\JsonValueConverterDateTime.cs(11,0): at System.Text.Json.Serialization.Converters.JsonConverterDateTime.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonPropertyInfoNotNullable.cs(24,0): at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonPropertyInfo.cs(352,0): at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.HandleNull.cs(62,0): at System.Text.Json.JsonSerializer.HandleNull(Utf8JsonReader& reader, ReadStack& state)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.cs(103,0): at System.Text.Json.JsonSerializer.ReadCoreSync(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
```

Note that serialization (i.e. writing) works as expected. The issue is specific to deserialization (reading).

**Comment by steveharter** [comment]
Work-arounds:
- Use a nullable type (e.g. `Nullable<DateTime>`)
- Create a custom converter for that type that can handle null

**Comment by steveharter** [comment]
There is a question here on correctness and validation. Since the value can never be null anyway, should `IgnoreNullValues` actually ignore "invalid" JSON? i.e. there can be reasons to want an exception in this case.

I compared against Json.NET (using `NullValueHandling = NullValueHandling.Ignore`) and it does ignore non-nullable values on deserialization, so perhaps compat is reason enough.

**Comment by steveharter** [comment]
Some options assuming `IgnoreNullValues=true`.
1) Keep existing semantics; the workaround is to use a nullable type such as `DateTime?` (or a custom converter if that is not desired). `IgnoreNullValues=true` means "ignore null when null is a valid value". Requiring usage of a nullable type is consistent with the original serializer design directives to support simple POCO types (not not more complicated Entity types that imply a layer of indirection).
2) Keep existing semantics but add an attribute that can be applied per property -- such as a new `JsonIgnoreNullValueAttribute` that will always ignore nulls. This feature was originally discussed but cut. It is also possible to extend the existing `JsonIgnoreAttribute`.
2) Make the change to ignore "null" on non-nullable structs. This could potentially break users that depend on the existing exception for validation reasons (since a non-nullable struct can't be null). `IgnoreNullValues=true` means "ignore null even when null is not a valid value".

4) ...

**Comment by ahsonkhan** [comment]
@rynowak, @JamesNK  - what do you think? To me, option 3 makes the most sense. When I see the `IgnoreNullValues` option from an end-user perspective, I assume it would work for both serialization and deserialization (even on value types that can't be null).

Although, I can see an argument to be made about option 1, but that requires the user to change their object model or workaround it with their own converter (maybe that's OK).

Given this is effectively by-design, moving to 5.0 for now.

**Comment by rynowak** [comment]
Option 3 makes the most sense. I don't think there's anything terrible about the JSON.NET behaviour.
