### ISSUE TITLE
Permission denied in Interop.Sys.ForkAndExecProcess (Linux)

### ISSUE THREAD

**Issue by MrM40** [dotnet/corefx#40964]
Out of the blue I suddenly can't call the program `virsh` from my .Core console app in Linux using `Process.Start` (been running fine for the last year, not aware of any system changes, e.g. didn't run any updates)

I get the following error:

     Permission denied
     at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
     at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
     at System.Diagnostics.Process.Start()
     at wconfig.Menus.MAIN.Test(Object& Obj)

 - I run my .Net Core app as root
 - I can run `virsh` fine from shell (also using root)
 - I can run `virsh` fine with `Process.Start` if I inwrap it in `bash -c` in my  Process.Start code
 - I can run other commands in my .Net Core app fine, I only see the problem with virsh (for now)
 - Can fine call `virsh` for a bash .sh script 

.Net Core code example:

    Dim PI As New ProcessStartInfo
    PI.RedirectStandardOutput = False
    PI.FileName = "virsh"
    PI.Arguments = "list --all"
    Using proc As New Process
      proc.StartInfo = PI
      proc.Start()
    End Using

Using dotnet runtime 2.2.3
Debian Buster (10)

Unfortunately I don't have deep knowledge of `virsh`. But I assume it's interacting with KVM,QEMU and libvirtd (Virtualization daemon) where some more advance permission "things" are in play?
But on the other hand if I can call `virsh` from shell as root, I expect I should be able to do that from net core when starting the app from the root user. Something funny is going on :-P

I'm pretty sure it will work fine on another server with the same versions of virsh, dotnet runtime and Linux version. But it seem it can "break" any time.
I understand the problem can be related to my Linux or virsh configuration and not dotnet. But on the other hand, I only see the problem in dotnet Process.Start.

Perhaps anyone in here have a clue or can point me in a direction to track down the problem?

**Comment by stephentoub** [comment]
You could try using `strace` to see what syscall is returning permission denied, and that might help you track down the cause.

**Comment by MrM40** [comment]
ok...I'll investigate, thanks :-)

**Comment by MrM40** [comment]
YES, I got it!
It took me some time to find the right option for strace, I had to use the `strace -f -o /tmp/strace.txt MyDotNetApp` option.
For some reason there was a virsh file in the folder /root/ at 0KB, and apparently  dotnet has another path search order than the shell, so dotnet executed `/root/virsh` whereas shell execute the real virsh in "/usr/bin/virsh".
Perhaps it would be a good idea for dotnet to have the same path search order as the shell is using?
And **@stephentoub**, thaaaaaanks for pointing me in the right direction :-)

**Comment by wfurt** [comment]
searching home folder may be compat with Windows. cc: @tmds

**Comment by wfurt** [comment]
one more thought: we should probably skip non-executable files like shell would.

**Comment by tmds** [comment]
> searching home folder may be compat with Windows. cc: @tmds

https://github.com/dotnet/corefx/blob/19b304f7815894b13cb61e87e1c9eac49a474c7e/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L685-L689
