### ISSUE TITLE
JsonSerializer.Deserialize<T> can't work out my array of dictionaries

### ISSUE THREAD

**Issue by HughPH** [dotnet/corefx#41107]
My class is designed to get the items from an Amazon DynamoDB query so that they can be converted to T with a class that implements IEnumerable<T>

```csharp
    public class DynamoQueryResult<T> where T : class, new()
    {
        public int Count;
        public Dictionary<string, DynamoValue>[] Items;
    }
```

Newtonsoft can deserialize into this class with no difficulty at all, but JsonSerializer.Deserialize just leaves the array null.

Example json:

```json
{
  "ConsumedCapacity": {
    "CapacityUnits": 1,
    "TableName": "Reply"
  },
  "Count": 2,
  "Items": [
    {
      "ReplyDateTime": {"S": "2015-02-18T20:27:36.165Z"},
      "PostedBy": {"S": "User A"},
      "Id": {"S": "Amazon DynamoDB#DynamoDB Thread 1"}
    },
    {
      "ReplyDateTime": {"S": "2015-02-25T20:27:36.165Z"},
      "PostedBy": {"S": "User B"},
      "Id": {"S": "Amazon DynamoDB#DynamoDB Thread 1"}
    }
  ],
  "ScannedCount": 2
}
```

Don't blame me for the insane JSON, blame Amazon. This example is lifted directly out of their DynamoDB documentation (and therefore forms part of my unit tests)

Changing from ```Dictionary<string, DynamoValue>[]``` to ```ExpandoObject[]``` also didn't help, and now I feel dirty.

**Comment by davidfowl** [comment]
Why is it an array of dictionaries? Which field becomes the string key? Also what's the generic argument for? I don't see it being used in your type definition?

**Comment by HughPH** [comment]
Yeah I get a null ref from there.

The generic argument is irrelevant, I just forgot to cut it from my previous issue which was about it being impossible(?) to deserialize into an IEnumerable of my own design. To widen the view: DynamoValue has several fields: S, N, BOOL, SS, NS, B, BS which are for holding data of different types. The example JSON just shows String fields. If the field contains a String, it goes into the S field. If it's a Number, it goes into the N field. If it's a Number Set (array), it goes into the NS field, and so forth. Yeah, I would probably have had a Type and a Value field, but that's not what the DynamoDB developers decided. Once I have all these multi-typed objects, keyed by their names, I then 'collapse' the Dictionary<string, DynamoValue> into a POCO where the name is the POCO's field/property, and the value is inferred from the POCO type.

**Comment by HughPH** [comment]
Ultimately my workaround has been to get the data as a JsonElement and then write my own stuff to shuffle the JSON into whatever type I've passed. I also added an implicit operator, so I can just assign a JsonElement to a DynamoQueryResult<T> which is once again IEnumerable<T>

It's not the prettiest code, I know. And there are some repeated blocks that I need to get rid of.

```csharp
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text.Json;

namespace writer_blazor
{
    public class DynamoQueryResult<T> : IEnumerable<T> where T : class, new()
    {
        public DynamoConsumedCapacity ConsumedCapacity;
        public List<Dictionary<string, DynamoValue>> Items;
        public DynamoValue LastEvaluatedKey;
        public int ScannedCount;

        public class DynamoConsumedCapacity
        {
            public int Count;
            public Dictionary<string, UnitsInfo[]> GlobalSecondaryIndexes;
            public Dictionary<string, UnitsInfo[]> LocalSecondaryIndexes;
            public int ReadCapacityUnits;
            public UnitsInfo Table;
            public string TableName;
            public int WriteCapacityUnits;

            public class UnitsInfo
            {
                public int CapacityUnits;
                public int ReadCapacityUnits;
                public int WriteCapacityUnits;
            }
        }

        public int Count;

        public static implicit operator DynamoQueryResult<T>(JsonElement j)
        {
            return new DynamoQueryResult<T>(j);
        }

        public DynamoQueryResult(in JsonElement jsonElement)
        {
            object graphPosition = this;
            ParseJsonDataIntoFields(graphPosition, jsonElement);
        }

        private void ParseJsonDataIntoFields(object graphPosition, in JsonElement jsonElement)
        {
            FieldInfo[] fields = graphPosition.GetType().GetFields();
            foreach (FieldInfo field in fields)
            {
                bool exists = jsonElement.TryGetProperty(field.Name, out JsonElement fieldElement);
                if (exists)
                {
                    object value = null;
                    switch (fieldElement.ValueKind)
                    {
                        case JsonValueKind.Object:
                            value = Activator.CreateInstance(field.FieldType);
                            ParseJsonDataIntoFields(value, fieldElement);
                            break;
                        case JsonValueKind.Array:
                            // need to figure this one out
                            if (field.FieldType.GetGenericTypeDefinition() == typeof(List<>))
                            {
                                value = Activator.CreateInstance(field.FieldType);
                                Type itemType = value.GetType().GetGenericArguments()[0];
                                JsonElement.ArrayEnumerator en = fieldElement.EnumerateArray();
                                while (en.MoveNext())
                                {
                                    object item = Activator.CreateInstance(itemType);
                                    if (itemType.GetGenericTypeDefinition() == typeof(Dictionary<,>))
                                        ParseJsonDataIntoDictionary(item, en.Current);
                                    else
                                        ParseJsonDataIntoFields(item, en.Current);

                                    ((IList) value).Add(item);
                                }
                            }

                            break;
                        case JsonValueKind.String:
                            if (field.FieldType == typeof(DateTime)) value = DateTime.Parse(fieldElement.GetString());
                            else value = fieldElement.GetString();
                            break;
                        case JsonValueKind.Number:
                        {
                            switch (field.FieldType.Name)
                            {
                                case "SByte":
                                case "Int16":
                                case "Int32":
                                case "Int64":
                                {
                                    value = Convert.ChangeType(fieldElement.GetInt64(), field.FieldType);
                                    break;
                                }
                                case "Byte":
                                case "UInt16":
                                case "UInt32":
                                case "UInt64":
                                {
                                    value = Convert.ChangeType(fieldElement.GetUInt64(), field.FieldType);
                                    break;
                                }
                                case "Single":
                                case "Double":
                                {
                                    value = Convert.ChangeType(fieldElement.GetDouble(), field.FieldType);
                                    break;
                                }
                                case "Decimal":
                                    value = Convert.ChangeType(fieldElement.GetDecimal(), field.FieldType);
                                    break;
                            }

                            break;
                        }
                        case JsonValueKind.True: // wtf
                            value = true;
                            break;
                        case JsonValueKind.False: // wtf
                            value = false;
                            break;
                        case JsonValueKind.Null:
                        case JsonValueKind.Undefined:
                            value = null;
                            break;
                        default:
                            throw new ArgumentOutOfRangeException();
                    }

                    if (value != null)
                        field.SetValue(graphPosition, value);
                }
            }
        }

        private void ParseJsonDataIntoDictionary(object item, in JsonElement enCurrent)
        {
            // item is the dictionary
            IDictionary dictionary = ((IDictionary) item);
            Type keyType = dictionary.GetType().GetGenericArguments()[0];
            if (keyType != typeof(String)) throw new NotImplementedException();
            Type valueType = dictionary.GetType().GetGenericArguments()[1];
            foreach (JsonProperty property in enCurrent.EnumerateObject())
            {
                object key = property.Name;
                object value = null;
                switch (property.Value.ValueKind)
                {
                    case JsonValueKind.Object:
                        value = Activator.CreateInstance(valueType);
                        ParseJsonDataIntoFields(value, property.Value);
                        break;
                    case JsonValueKind.Array:
                        throw new NotImplementedException();

                    case JsonValueKind.String:
                        if (valueType == typeof(DateTime)) value = DateTime.Parse(property.Value.GetString());
                        else value = property.Value.GetString();
                        break;
                    case JsonValueKind.Number:
                    {
                        switch (valueType.Name)
                        {
                            case "SByte":
                            case "Int16":
                            case "Int32":
                            case "Int64":
                            {
                                value = Convert.ChangeType(property.Value.GetInt64(), valueType);
                                break;
                            }
                            case "Byte":
                            case "UInt16":
                            case "UInt32":
                            case "UInt64":
                            {
                                value = Convert.ChangeType(property.Value.GetUInt64(), valueType);
                                break;
                            }
                            case "Single":
                            case "Double":
                            {
                                value = Convert.ChangeType(property.Value.GetDouble(), valueType);
                                break;
                            }
                            case "Decimal":
                                value = Convert.ChangeType(property.Value.GetDecimal(), valueType);
                                break;
                        }

                        break;
                    }
                    case JsonValueKind.True: // wtf
                        value = true;
                        break;
                    case JsonValueKind.False: // wtf
                        value = false;
                        break;
                    case JsonValueKind.Null:
                    case JsonValueKind.Undefined:
                        value = null;
                        break;
                    default:
                        throw new ArgumentOutOfRangeException();
                }

                dictionary.Add(key, value);
            }
        }

        public IEnumerator<T> GetEnumerator()
        {
            return new DynamoQueryResultEnumerator<T>(this);
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return new DynamoQueryResultEnumerator<T>(this);
        }
    }


    public class DynamoQueryResultEnumerator<T> : IEnumerator<T> where T : class, new()
    {
        private readonly DynamoQueryResult<T> dynamoQueryResult;
        private int index = -1;
        private FieldInfo[] fields;

        public DynamoQueryResultEnumerator(DynamoQueryResult<T> dynamoQueryResult)
        {
            this.dynamoQueryResult = dynamoQueryResult;
            fields = typeof(T).GetFields(BindingFlags.Instance | BindingFlags.Public);
        }

        public bool MoveNext()
        {
            index++;
            if (index >= dynamoQueryResult.Items.Count) return false;
            Current = PopulateCurrent(dynamoQueryResult.Items[index]);
            return true;
        }

        private T PopulateCurrent(Dictionary<string, DynamoValue> itemValues)
        {
            T item = new T();
            foreach (KeyValuePair<string, DynamoValue> value in itemValues)
            {
                FieldInfo info = fields.FirstOrDefault(p => p.Name == value.Key);
                if (info == null)
                    throw new InvalidOperationException("Serialized data contains Field " + value.Key +
                                                        " but no matching C# Field was found");

                if (value.Value.NULL.HasValue && value.Value.NULL == true) continue;

                switch (value.Value.InferType())
                {
                    case DynamoType.Number:
                        info.SetValue(item, Convert.ChangeType(value.Value.N, info.FieldType));
                        break;
                    case DynamoType.String:
                        object v = null;
                        if (info.FieldType == typeof(Guid))
                            v = Guid.Parse(value.Value.S);
                        else
                            v = Convert.ChangeType(value.Value.S, info.FieldType);
                        info.SetValue(item, v);
                        break;
                    case DynamoType.Boolean:
                        info.SetValue(item, Convert.ChangeType(value.Value.BOOL, info.FieldType));
                        break;
                    case DynamoType.ByteBuffer:
                        info.SetValue(item, Convert.ChangeType(value.Value.B, info.FieldType));
                        break;
                    case DynamoType.StringArray:
                        info.SetValue(item, Convert.ChangeType(value.Value.SS, info.FieldType));
                        break;
                    case DynamoType.NumberArray:
                        info.SetValue(item, Convert.ChangeType(value.Value.NS, info.FieldType));
                        break;
                    case DynamoType.ByteBufferArray:
                        info.SetValue(item, Convert.ChangeType(value.Value.BS, info.FieldType));
                        break;
                    default:
                        throw new ArgumentOutOfRangeException();
                }
            }

            return item;
        }

        public void Reset()
        {
            index = -1;
        }

        public T Current { get; private set; }

        object IEnumerator.Current => Current;

        public void Dispose()
        {
        }
    }


    public class DynamoValue
    {
        public byte[] B;
        public bool? BOOL;
        public byte[][] BS;
        public int? N;
        public int[] NS;
        public bool? NULL;
        public string S;
        public string[] SS;

        public DynamoType InferType()
        {
            if (BOOL.HasValue) return DynamoType.Boolean;
            if (N.HasValue) return DynamoType.Number;
            if (S != null) return DynamoType.String;
            if (SS != null) return DynamoType.StringArray;
            if (NS != null) return DynamoType.NumberArray;
            if (BS != null) return DynamoType.ByteBufferArray;
            if (B != null) return DynamoType.ByteBuffer;
            return DynamoType.Null;
        }
    }

    public enum DynamoType
    {
        Number,
        String,
        Boolean,
        ByteBuffer,
        StringArray,
        NumberArray,
        ByteBufferArray,
        Null
    }
}
```

**Comment by ahsonkhan** [comment]
> Ultimately my workaround has been to get the data as a JsonElement and then write my own stuff to shuffle the JSON into whatever type I've passed.

When deserializing, we explicitly avoid having the payload define the type to deserialize as (in this case, the DynamoValue is a union of several types and the payload tells you which type it should be returned as), which is why capturing the data as JsonElement and handling it explicitly should work. Your workaround makes sense to me.

> Yeah I get a null ref from there.

```csharp
    public class DynamoQueryResult<T> where T : class, new()
    {
        public int Count;
        public Dictionary<string, DynamoValue>[] Items;
    }
```

Fields are not supported in the current version of the JSON deserializer, which is why neither Count nor Items is being set here (and hence the `Items` array is null). But this scenario does bring up an issue with the deserializer (once the type being deserialized is changed to contain properties).

> I tried this but got a null ref

Yep, that's a bug in how we are handling array of dictionaries.

```C#
        [Fact]
        public static void DeserializeToDictionaryArrayDynamo()
        {
            string jsonStr =
@"{
  ""ConsumedCapacity"": {
    ""CapacityUnits"": 1,
    ""TableName"": ""Reply""
  },
  ""Count"": 2,
  ""Items"": [
    {
      ""ReplyDateTime"": { ""S"": ""2015-02-18T20:27:36.165Z""},
      ""PostedBy"": { ""S"": ""User A""},
      ""Id"": { ""S"": ""Amazon DynamoDB#DynamoDB Thread 1""}
    },
    {
      ""ReplyDateTime"": {""S"": ""2015-02-25T20:27:36.165Z""},
      ""PostedBy"": { ""S"": ""User B""},
      ""Id"": { ""S"": ""Amazon DynamoDB#DynamoDB Thread 1""}
    }
  ],
  ""ScannedCount"": 2
}";

            DynamoQueryResult result = JsonSerializer.Deserialize<DynamoQueryResult>(jsonStr);
            Assert.Equal(2, result.Count);
            Assert.Equal(2, result.Items.Length);
        }

        public class DynamoQueryResult
        {
            public int Count { get; set; }
            public Dictionary<string, DynamoValue>[] Items { get; set; }
        }

        public class DynamoValue
        {
            public string S { get; set; }
            public int N { get; set; }
            public int[] NS { get; set; }
            public bool BOOL { get; set; }
        }
```

```text
System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonPropertyInfoCommon.cs(96,0): at System.Text.Json.JsonPropertyInfoCommon`4.SetValueAsObject(Object obj, Object value)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.HandleDictionary.cs(86,0): at System.Text.Json.JsonSerializer.HandleStartDictionary(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.cs(73,0): at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.Helpers.cs(17,0): at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.String.cs(74,0): at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.String.cs(31,0): at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
          E:\GitHub\Fork\corefx\src\System.Text.Json\tests\Serialization\Value.ReadTests.cs(62,0): at System.Text.Json.Serialization.Tests.ValueTests.ReadPrimitives()
```

This occurs whenever we have an **array** of `Dictionary<string, TValue>` where TValue is another POCO or non-primitive type (like JsonElement). Here's a simplified repro outside of the context of `DynamoDB`:
```C#
        [Fact]
        public static void DeserializeToDictionaryArray()
        {
            string jsonStr =
@"{
  ""Items"": [
    {
      ""property1"": {""Nested"": ""value1""}
    },
    {
      ""property2"": {""Nested"": ""value2""}
    }
  ]
}";
            DictionaryArray result = JsonSerializer.Deserialize<DictionaryArray>(jsonStr);
            Assert.Equal(2, result.Items.Length);
        }

        public class DictionaryArray
        {
            public Dictionary<string, NestedType>[] Items { get; set; }
        }
        public class NestedType
        {
            public string Nested { get; set; }
        }
```

```text
System.Text.Json.Serialization.Tests.ValueTests.DeserializeToDictionaryArray [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonPropertyInfoCommon.cs(96,0): at System.Text.Json.JsonPropertyInfoCommon`4.SetValueAsObject(Object obj, Object value)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.HandleDictionary.cs(86,0): at System.Text.Json.JsonSerializer.HandleStartDictionary(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.cs(73,0): at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.Helpers.cs(17,0): at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.String.cs(74,0): at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
          E:\GitHub\Fork\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.String.cs(31,0): at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
          E:\GitHub\Fork\corefx\src\System.Text.Json\tests\Serialization\Value.ReadTests.cs(28,0): at System.Text.Json.Serialization.Tests.ValueTests.DeserializeToDictionaryArray()
```
In the following code, the Set `Action` is null. Looks like we are incorrectly identifying this case as "ProcessingDictionary" (i.e. `IsProcessingDictionary` is true) rather than processing it as an array/IEnumerable (where `IsProcessingEnumerable` would be true).
https://github.com/dotnet/corefx/blob/a308e93b1f1303be7eab5ce2b8ed11e66cc8e01e/src/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfoCommon.cs#L89-L98

cc @steveharter, @layomia 

> Changing from ```Dictionary<string, DynamoValue>[]``` to ```ExpandoObject[]``` also didn't help, and now I feel dirty.

Here's an issue for `ExpandoObject` (just as an FYI): https://github.com/dotnet/corefx/issues/38007

**Comment by HughPH** [comment]
Thanks Ahson!

My code is behind the edit in my previous reply. The real thing has been cleaned up a little, but I still need to address sets (e.g. BS, SS, NS)

Cheers

**Comment by ahsonkhan** [comment]
Here's a similar issue from https://github.com/dotnet/corefx/issues/41198 by @mmosca

> System.Text.Json fail with a NullReferenceException trying to deserialized nested objects/arrays to IEnumerable<IDictionary<>> type.
> 
> This sample program will trigger this issues on .Net Core 3.0-rc1:
> 
> ```
> using System;
> using System.Collections.Generic;
> using System.Text.Json;
> 
> namespace CustomViewSplit
> {
>     class Program
>     {
>         static void Main(string[] args)
>         {
>             string workingJson = @"[
>   {
>     ""a"": ""A"",
>     ""b"" :  ""B""
>   }
> ]";
> 
>             string brokenJson = @"[
>   {
>     ""a"": ""A"",
>     ""b"" :  {} 
>   }
> ]";
> 
> 
>             foreach (string json in new[] {workingJson, brokenJson})
>             {
>                 byte[] bytes = System.Text.Encoding.UTF8.GetBytes(json);
>                 ReadOnlySpan<byte> readonlySpan = new ReadOnlySpan<byte>(bytes);
> 
>                 // This will throw a NullReferenceException for brokenJson and alsoBroken
>                 var enumerable = JsonSerializer.Deserialize<IEnumerable<IDictionary<string, object>>>(readonlySpan);
>             }
>         }
>     }
> }
> ```
