### ISSUE TITLE
Expression interpreter - Bug in ByRefMethodInfoCallInstruction

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#4112]
Found while enabling more tests (see #3995):

```
     Tests.Compiler_Tests.CallCompiledLambdaWithTypeMissing [FAIL]
        Assert.Equal() Failure
        Expected: (null)
        Actual:   System.ArgumentException: Missing parameter does not have a default value.
        Parameter name: parameters
           at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
           at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
           at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
           at System.Linq.Expressions.Interpreter.ByRefMethodInfoCallInstruction.Run(InterpretedFrame frame) in Interpreter\CallInstruction.cs:line 499
           at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame frame) in \Interpreter\Interpreter.cs:line 106
           at System.Linq.Expressions.Interpreter.LightLambda.Run(Object[] arguments) in Interpreter\LightLambda.cs:line 264
           at Thunk(Func`2 , Object )
           at lambda_method(Closure , Object )
        Stack Trace:
           TestExtensions.cs(134,0): at TestExtensions.AssertVoid(Exception e1, Exception e2)
           TestExtensions.cs(145,0): at TestExtensions.AssertNonVoid(Object o1, Object o2, Exception e1, Exception e2)
              at lambda_method(Closure , Object )
           SequenceTests\SequenceTests.cs(2914,0): at Tests.Compiler_Tests.CallCompiledLambdaWithTypeMissing()
```

**Comment by bartdesmet** [comment]
This hits the case where we compile an expression for interpretation and pass Type.Missing to any late bound invocation, e.g.:

```csharp
Expression<Action> f = () => Console.WriteLine(Type.Missing);

// Prints
f.Compile()();

// ArgumentException
f.Compile(true)();
```

This will be tricky to get around given that MethodBase.CheckArguments can't be influenced in its behavior to check for Type.Missing reference equality with any of the specified arguments.

**Comment by bartdesmet** [comment]
CC @VSadov, what do you think?

**Comment by bartdesmet** [comment]
I've given this some more thought and it seems hard to get around without any change in mscorlib. A few possibilities are listed below...

One idea would be to add a virtual member to the Binder class in mscorlib, allowing the Type.Missing resolution behavior to be controlled by derived classes. It could be simple Boolean property or a mechanism that participates in the CheckArguments logic, e.g. to resolve missing arguments or to provide a change to rewrite arguments (so the analysis of Type.Missing can be completely omitted by a derived class). Obviously, it'd have to be a virtual and not an abstract in order to retain compatibility.

By adding this customization point to the binder, the interpreter could pass a custom binder to the reflection Invoke methods in order to suppress the Type.Missing resolution. However, it seems that the System.Linq.Expressions assembly only sees the Invoke(object, object[]) overload of the reflection API at this point.

If we can't get access to the verbose overload of Invoke, another trick could be to have another "missing" singleton object known between mscorlib's CheckArguments and the interpreter, and have the interpreter substitute Type.Missing for that alternate "missing" object (requiring a loop in CallInstruction). On its turn, CheckArguments would substitute it back for Type.Missing passed to the target method. That'd also lead to the addition of a new public (or internal if we can get friend access) API in mscorlib.

Even though the second option seems hacky, it could possibly be justified as a means for other users of reflection to truly pass Type.Missing to an object-typed parameter of the target method. Today, that edge case can't be dealt with by users.

**Comment by VSadov** [comment]
We need a way to do invocation via reflection without resolving Missing arguments.

This was a major problem with C# dynamic and omitted optional parameters. Omitted parameters are represented as Missing, and could not flow through interpreted code if there were any call boundaries between DLR and dynamic binder. We have solved that by eliminating call boundaries internal to interpreted code - i.e. when interpreter needs to call another interpreted lambda, we just interpret the body (which is likely faster too). However that is just a solution only for a special case of this issue. We need something more general.

I think the fix unavoidably requires a new API/flavor/mode for reflection invoke that does not mess with Missing.
