### ISSUE TITLE
Test Failure: System.Diagnostics.Tests.EventLogWriteEntryTests.WriteEntryWithType(sourceFlag: True)

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#41150]
Test `System.Diagnostics.Tests.EventLogWriteEntryTests.WriteEntryWithType(sourceFlag: True)` has failed.
```
System.Diagnostics.Tests.EventLogWriteEntryTests.WriteEntryWithType(sourceFlag: True) [FAIL]
      System.AggregateException : One or more errors occurred. (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.)
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      ---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
      Stack Trace:
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(45,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(30,0): at System.Diagnostics.Tests.Helpers.Retry[T](Func`1 func)
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.Retry(Action func)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogWriteEntryTests.cs(181,0): at System.Diagnostics.Tests.EventLogWriteEntryTests.WriteEntryWithType(Boolean sourceFlag)
        ----- Inner Stack Trace #1 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(479,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(402,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(366,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogWriteEntryTests.cs(181,0): at System.Diagnostics.Tests.EventLogWriteEntryTests.<>c__DisplayClass9_0.<WriteEntryWithType>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace #2 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(479,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(402,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(366,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogWriteEntryTests.cs(181,0): at System.Diagnostics.Tests.EventLogWriteEntryTests.<>c__DisplayClass9_0.<WriteEntryWithType>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace #3 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(479,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(402,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(366,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogWriteEntryTests.cs(181,0): at System.Diagnostics.Tests.EventLogWriteEntryTests.<>c__DisplayClass9_0.<WriteEntryWithType>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace #4 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(479,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(402,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(366,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogWriteEntryTests.cs(181,0): at System.Diagnostics.Tests.EventLogWriteEntryTests.<>c__DisplayClass9_0.<WriteEntryWithType>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace #5 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(479,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(402,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(366,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogWriteEntryTests.cs(181,0): at System.Diagnostics.Tests.EventLogWriteEntryTests.<>c__DisplayClass9_0.<WriteEntryWithType>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace #6 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(479,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(402,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(366,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogWriteEntryTests.cs(181,0): at System.Diagnostics.Tests.EventLogWriteEntryTests.<>c__DisplayClass9_0.<WriteEntryWithType>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace #7 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(479,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(402,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(366,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogWriteEntryTests.cs(181,0): at System.Diagnostics.Tests.EventLogWriteEntryTests.<>c__DisplayClass9_0.<WriteEntryWithType>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace #8 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(479,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(402,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(366,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogWriteEntryTests.cs(181,0): at System.Diagnostics.Tests.EventLogWriteEntryTests.<>c__DisplayClass9_0.<WriteEntryWithType>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace #9 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(479,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(402,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(366,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogWriteEntryTests.cs(181,0): at System.Diagnostics.Tests.EventLogWriteEntryTests.<>c__DisplayClass9_0.<WriteEntryWithType>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace #10 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(479,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(402,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(366,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogWriteEntryTests.cs(181,0): at System.Diagnostics.Tests.EventLogWriteEntryTests.<>c__DisplayClass9_0.<WriteEntryWithType>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
    System.Diagnostics.Tests.EventLogConfigurationTests.SetProperties_SaveChanges_NotAdmin_Throws [SKIP]
      Condition(s) not met: "NotElevatedAndSupportsEventLogs"
  Finished:    System.Diagnostics.EventLog.Tests
=== TEST EXECUTION SUMMARY ===
   System.Diagnostics.EventLog.Tests  Total: 140, Errors: 0, Failed: 1, Skipped: 1, Time: 89.388s
----- end Tue 09/17/2019  6:16:02.55 ----- exit code 1 ----------------------------------------------------------
```

Build: -[20190916.34](https://dnceng.visualstudio.com/public/_build/results?buildId=357148)(Master)

Details:
https://helix.dot.net/api/2019-06-17/jobs/96638b0b-a37a-46c3-b5f3-ba6a9807b04e/workitems/System.Diagnostics.EventLog.Tests/console

**Comment by wtgodbe** [comment]
Looks to be transient, and this appears to be the only failure in the recent history (and only on the `Windows.10.Amd64.19H1.Tiger.Perf.Open` queue). We can investigate further if we see it again
