### ISSUE TITLE
CryptographicException on .NET Core 3, Windows only "The specified RSA parameters are not valid; both Exponent and Modulus are required fields."

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#41226]
I'm getting the following error when creating RSA from RSAParameters, but only on Windows for .NET Core 3.0. This works on .NET 4.7.2, .NET Core 2.1 (Windows and macOS), and .NET Core 3.0 (macOS).

```
System.Security.Cryptography.CryptographicException: The specified RSA parameters are not valid; both Exponent and Modulus are required fields.
   at System.Security.Cryptography.RSAImplementation.RSACng.ImportParameters(RSAParameters parameters)
   at System.Security.Cryptography.RSA.Create(RSAParameters parameters)
```

## Repro
```c#
using System;
using System.Security.Cryptography;
using System.Text;

class Program
{
    static void Main(string[] args)
    {
        var parameters = new RSAParameters
        {
            Modulus = new byte[] { 0, 198, 19, 173, 163, 198, 96, 251, 190, 35, 45, 77, 159, 113, 248, 230, 172, 43, 69, 139, 187, 192, 228, 253, 66, 48, 221, 32, 243, 161, 105, 84, 113, 54, 227, 201, 142, 233, 118, 27, 2, 23, 33, 36, 83, 137, 232, 116, 109, 112, 44, 249, 73, 223, 56, 32, 51, 228, 0, 47, 185, 95, 95, 242, 143, 218, 137, 130, 124, 189, 143, 118, 193, 59, 4, 156, 29, 222, 113, 221, 130, 153, 69, 7, 197, 81, 150, 94, 86, 209, 1, 31, 209, 49, 111, 62, 132, 105, 167, 170, 241, 79, 218, 202, 179, 67, 170, 145, 169, 36, 228, 99, 6, 39, 235, 166, 189, 17, 242, 167, 217, 192, 36, 120, 209, 176, 89, 240, 248, 34, 155, 25, 130, 64, 53, 85, 50, 20, 17, 248, 59, 69, 179, 149, 74, 22, 122, 162, 191, 150, 33, 138, 157, 129, 76, 16, 0, 220, 103, 77, 183, 21, 25, 101, 121, 50, 130, 190, 208, 19, 48, 153, 62, 229, 76, 39, 204, 64, 120, 72, 244, 197, 108, 197, 127, 29, 200, 248, 161, 69, 230, 249, 175, 1, 236, 45, 231, 31, 103, 189, 85, 79, 14, 123, 137, 70, 71, 40, 137, 217, 73, 211, 206, 173, 192, 214, 175, 204, 155, 229, 70, 31, 195, 238, 206, 116, 2, 50, 238, 15, 53, 60, 35, 32, 89, 126, 233, 219, 147, 240, 39, 71, 174, 202, 206, 220, 250, 156, 80, 132, 224, 169, 146, 169, 234, 184, 127 },
            Exponent = new byte[] { 1, 0, 1 },
            D = new byte[] { 76, 191, 255, 62, 64, 117, 255, 213, 178, 231, 176, 246, 33, 65, 98, 144, 63, 204, 24, 210, 205, 113, 109, 56, 162, 154, 108, 84, 58, 173, 7, 141, 62, 201, 144, 166, 17, 140, 51, 246, 225, 99, 116, 33, 242, 131, 225, 233, 45, 216, 31, 88, 34, 104, 43, 2, 48, 76, 106, 49, 151, 229, 35, 165, 221, 245, 254, 91, 187, 79, 197, 162, 37, 238, 41, 87, 225, 131, 153, 99, 43, 100, 118, 24, 92, 254, 184, 219, 70, 236, 250, 153, 34, 96, 138, 134, 224, 49, 153, 169, 27, 90, 25, 196, 208, 105, 93, 59, 127, 18, 7, 212, 176, 207, 60, 178, 114, 43, 230, 34, 23, 179, 138, 37, 38, 2, 19, 190, 67, 117, 14, 70, 163, 166, 15, 163, 36, 228, 191, 59, 16, 177, 247, 114, 183, 114, 242, 67, 60, 41, 28, 97, 228, 156, 128, 219, 97, 234, 78, 43, 8, 77, 190, 41, 29, 13, 242, 96, 71, 249, 29, 131, 152, 28, 45, 104, 215, 29, 2, 7, 89, 83, 193, 135, 107, 229, 4, 150, 153, 108, 42, 115, 151, 145, 64, 58, 68, 73, 138, 101, 87, 104, 173, 163, 143, 193, 163, 120, 4, 60, 82, 187, 245, 143, 150, 62, 255, 130, 17, 196, 131, 214, 102, 114, 244, 137, 209, 14, 8, 66, 88, 229, 72, 74, 13, 104, 32, 236, 119, 126, 138, 128, 5, 255, 166, 15, 104, 137, 25, 79, 91, 32, 192, 224, 139, 145 },
            P = new byte[] { 0, 234, 73, 179, 109, 136, 112, 92, 137, 136, 238, 24, 124, 25, 51, 139, 96, 207, 59, 247, 2, 88, 147, 38, 158, 192, 61, 57, 101, 141, 244, 172, 214, 250, 38, 140, 75, 0, 140, 111, 154, 178, 153, 50, 168, 118, 164, 152, 48, 174, 72, 7, 51, 63, 121, 84, 213, 139, 25, 83, 199, 229, 186, 246, 55, 57, 230, 161, 221, 166, 125, 114, 157, 64, 212, 24, 178, 26, 67, 13, 154, 142, 191, 253, 248, 183, 238, 225, 232, 205, 43, 44, 101, 204, 247, 177, 91, 223, 63, 155, 219, 209, 206, 219, 18, 72, 89, 197, 212, 186, 231, 89, 175, 84, 202, 20, 53, 133, 77, 38, 8, 50, 116, 56, 123, 94, 67, 78, 19 },
            Q = new byte[] { 0, 216, 110, 230, 24, 21, 240, 176, 181, 20, 62, 150, 117, 123, 72, 166, 206, 147, 14, 232, 207, 15, 66, 157, 140, 87, 242, 188, 204, 214, 88, 44, 186, 55, 53, 81, 143, 129, 141, 79, 104, 103, 136, 134, 178, 236, 223, 90, 208, 12, 80, 15, 181, 172, 161, 146, 159, 184, 46, 246, 177, 7, 234, 0, 238, 13, 136, 87, 112, 70, 63, 218, 129, 215, 93, 204, 243, 181, 37, 195, 136, 238, 49, 33, 190, 104, 98, 247, 7, 148, 120, 7, 56, 137, 135, 113, 141, 166, 39, 0, 143, 198, 225, 230, 206, 65, 142, 18, 76, 115, 18, 61, 216, 103, 176, 6, 57, 22, 92, 134, 88, 193, 120, 255, 152, 188, 176, 201, 101 },
            DP = new byte[] { 29, 65, 198, 222, 78, 195, 121, 74, 211, 134, 168, 24, 23, 45, 144, 162, 46, 62, 214, 193, 188, 61, 227, 252, 191, 20, 230, 46, 0, 100, 37, 145, 82, 251, 173, 89, 80, 96, 57, 47, 160, 77, 241, 61, 136, 83, 85, 141, 254, 181, 143, 240, 158, 100, 144, 107, 122, 75, 87, 99, 7, 21, 41, 218, 11, 168, 249, 93, 172, 132, 205, 227, 69, 77, 55, 40, 70, 143, 73, 11, 155, 247, 237, 199, 57, 112, 227, 85, 39, 9, 213, 41, 129, 71, 13, 38, 227, 226, 21, 156, 133, 190, 199, 44, 169, 76, 76, 160, 28, 22, 247, 228, 37, 58, 118, 251, 152, 1, 226, 85, 243, 182, 255, 182, 168, 54, 207, 113 },
            DQ = new byte[] { 106, 226, 81, 149, 129, 120, 76, 252, 16, 20, 92, 159, 134, 19, 185, 244, 248, 96, 251, 142, 14, 30, 58, 201, 237, 64, 254, 6, 54, 176, 114, 222, 63, 151, 128, 64, 219, 156, 218, 163, 87, 197, 239, 167, 123, 29, 78, 174, 193, 245, 227, 220, 55, 117, 207, 128, 59, 40, 78, 65, 221, 3, 174, 19, 225, 240, 252, 37, 129, 59, 213, 128, 27, 200, 194, 7, 116, 229, 66, 108, 100, 29, 53, 105, 224, 9, 71, 175, 161, 157, 169, 11, 61, 183, 250, 215, 22, 63, 218, 162, 38, 120, 183, 80, 18, 197, 195, 185, 167, 118, 81, 190, 134, 110, 66, 148, 124, 187, 146, 201, 80, 58, 158, 23, 98, 207, 247, 149 },
            InverseQ = new byte[] { 35, 3, 31, 227, 254, 71, 57, 5, 125, 39, 137, 220, 196, 105, 22, 167, 125, 36, 211, 150, 39, 113, 235, 171, 111, 121, 231, 48, 214, 37, 226, 39, 59, 124, 0, 23, 125, 34, 147, 31, 106, 74, 117, 50, 244, 188, 42, 101, 201, 216, 225, 198, 247, 248, 78, 97, 171, 1, 49, 6, 100, 209, 214, 92, 254, 147, 34, 192, 158, 200, 17, 63, 113, 197, 148, 235, 48, 214, 121, 91, 104, 171, 14, 152, 249, 46, 153, 64, 11, 230, 27, 117, 91, 82, 85, 144, 95, 66, 157, 184, 72, 3, 122, 161, 92, 154, 208, 163, 227, 248, 154, 207, 246, 252, 184, 121, 224, 95, 162, 233, 76, 195, 56, 111, 186, 76, 39, 119 },
        };

        try
        {
            var key = RSA.Create(parameters); // this throws on .NET Core 3.0, Windows only

            var encrypted = key.Encrypt(Encoding.ASCII.GetBytes("Hello"), RSAEncryptionPadding.Pkcs1);
            Console.WriteLine($"encrypted = {BitConverter.ToString(encrypted)}");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine(ex.ToString());
        }
    }
}
```
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.1;netcoreapp3.0;net472</TargetFrameworks>
  </PropertyGroup>

</Project>
```

![image](https://user-images.githubusercontent.com/2696087/65304325-34608080-db35-11e9-8004-eec7088dc4a1.png)

**Comment by vcsjones** [comment]
First, it looks like the exception message is a bit misleading. That exception message is used if anything is believed to be incorrect about the parameters, not just the exponent or modulus.

The reason is it being thrown is because `Modulus` and `D` are different lengths, which is checked here, and was introduced in #39087.

https://github.com/dotnet/corefx/blob/aa72982dcb20c4e346e08d72dae5abbaf6bba4f9/src/Common/src/System/Security/Cryptography/RSACng.ImportExport.cs#L79

The Q and P length checks will also fail, but D is the first cause of the exception.

They are all off-by-one. Notably, all of those have 0 in them, likely because they are encoded as signed integers.

@bartonjs would probably know best what the correct solution is, but the validation that was added currently disallows something that it looks like CNG accepts.

**Comment by bartonjs** [comment]
If the key was correctly imported then `encrypted.Length` would equal `rsaParameters.Modulus.Length`.  The fact that the answer looks like a different size on netcoreapp2.1 and net472 suggests that it somewhere went sideways and generated a new key for the encryption operation, which is less than ideal.

I don't really want to count hyphens to see how many bytes were in each piece of response, but the correct parameters form is:

* Modulus: No leading 0
* Exponent: No leading 0
* D: Same Length as Modulus, leading zeros as necessary to make that happen.
* P: Length is ((Modulus.Length + 1) / 2), leading zeros as necessary.
* Q, DP, DQ, InverseQ: Same length as P, leading zeros as necessary.

**Comment by vcsjones** [comment]
@bartonjs Hm. That would be troublesome.

@natemcmaster Looking through your code, it looks like you are trying to load a PEM encoded private key. Fortunately, .NET Core 3 shipped with [`ImportSubjectPublicKeyInfo`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsa.importsubjectpublickeyinfo?view=netcore-3.0) which I believe can be used to read your PEM file without having to bother with the `RSAParameters` at all.

**Comment by natemcmaster** [comment]
Thanks for the fast response. I'm surprised that the private key import is wrong. This code has been working just fine for 18 months and I don't see any errors when

For more context, the code which led me to this problem is here: https://github.com/natemcmaster/dotnet-serve/blob/v1.4.0/src/dotnet-serve/Security/CertificateLoader.cs#L113-L165. I'm using Portable.BouncyCastle's PemReader object to read this file -- https://github.com/natemcmaster/dotnet-serve/blob/v1.4.0/test/dotnet-serve.Tests/TestAssets/Https/rsa/private.key -- and then use it to create an instance of X509Certificate2.

If the private key import is indeed wrong, then we should tap in @onovotny to see about fixing to the BouncyCastle project. 

As you mentioned @vcsjones, I was planning to update my code to use the new key import/export APIS in .NET Core 3....but the app still needs to work on .NET Core 2.1, so can't completely remove my dependency on BouncyCastle.

**Comment by bartonjs** [comment]
BouncyCastle read the key right, but you asked for data as `signed BigInteger` export.  RSAParameters needs it as `unsigned BigInteger`, and you did the translation too naively (which is really easy to do, I admit).

You also have a subtle bug where if any of the CRT parameters happen to not need all of their bytes you'd be too small.

https://github.com/natemcmaster/dotnet-serve/blob/73055da380ad1422d96a608d3d6102357654fb8a/src/dotnet-serve/Security/CertificateLoader.cs#L154-L164

https://stackoverflow.com/a/28387683/6535399 seems to have the right code (though I haven't tried running it)

**Comment by vcsjones** [comment]
>If the private key import is indeed wrong, then we should tap in @onovotny to see about fixing to the BouncyCastle project.

I don't think BouncyCastle is wrong, it's just that there are different encodings of the parameters. In a PEM file, these parameters are encoded as DER ASN.1 integers, which are signed. If I understood @bartonjs's comment correct, `RSAParameters` is not expecting ASN.1 INTEGERs.

**Comment by vcsjones** [comment]
@bartonjs 

All that said, it _looks_ like CNG does handle signed integers? Given the example:

```csharp
Modulus = new byte[] { 0, 0xC6, 0x13, 0xAD, 0xA3, 0xC6, 0x60, 0xFB, 0xBE ... };

using var rsa = new RSACng();
rsa.ImportParameters(parameters);
var newParameters = rsa.ExportParameters(true);
Console.WriteLine(BitConverter.ToString(newParameters.Modulus));
```

Output:

>C6-13-AD-A3-C6-60-FB-BE

Note the zero is trimmed off.

It looks like CNG was importing the signed integers "correctly" previously, perhaps not intentionally.

**Comment by bartonjs** [comment]
> All that said, it looks like CNG does handle signed integers?

Maybe.  But CAPI, via RSACryptoServiceProvider, really defined how the RSAParameters structure worked.  And CNG has had at least one inconsistency in handling non-standard/malformed parameters (10-RS1 vs every-other-Windows), which is what prompted the "wait a minute, we don't have the same validation logic across all the providers" change.

**Comment by vcsjones** [comment]
>"wait a minute, we don't have the same validation logic across all the providers" change.

Ah, I see. Thanks for explaining.

**Comment by natemcmaster** [comment]
@bartonjs was right (of course). This is a bug in my code, not corefx or bouncy castle. Thanks for helping me out @vcsjones @bartonjs!

I'm still going to leave this open because I think the exception message is very misleading and should say what is actually wrong, but thanks again!
