### ISSUE TITLE
[System.Text.Json] Type deriving from List<T> without parameterless constructor results in null ref

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#41242]
```C#
class Program
{
    static void Main(string[] args)
    {
        var json = "[1, 2]";
        var x = JsonSerializer.Deserialize<CustomList<int>>(json);
    }
}

public class CustomList<T> : List<T>
{
    public CustomList(int x) { }
}
```

Stack trace:

```C#
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Text.Json.ReadStackFrame.CreateEnumerableValue(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.HandleStartArray(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
```

Reproduced using `Microsoft.NETCore.App 3.0.0-rc1-19456-20`

Adding a parameterless ctor works, but the exception message likely needs to say that a parameterless ctor needs to be declared.

**Comment by ahsonkhan** [comment]
cc @steveharter, @layomia

**Comment by layomia** [comment]
This was fixed for master/5.0 in https://github.com/dotnet/corefx/pull/40654, albeit without the message specifying that a parameterless ctor. The serializer throws a `NotSupportedException` saying that the collection is not supported:

https://github.com/dotnet/corefx/blob/a308e93b1f1303be7eab5ce2b8ed11e66cc8e01e/src/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfoCommon.cs#L121-L128

https://github.com/dotnet/corefx/blob/a308e93b1f1303be7eab5ce2b8ed11e66cc8e01e/src/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfoCommon.cs#L182-L189

The task here would be to provide a more explicit failure message.

**Comment by ahsonkhan** [comment]
We should consider porting that fix to 3.1.
