### ISSUE TITLE
JSON Serialization Name Collision with hidden properties

### ISSUE THREAD

**Issue by douglasg14b** [dotnet/corefx#41338]
Take Two Classes:

```cs
public class ClassA
{
    public List<int> SomeList { get; set; }
}

public class ClassB : ClassA
{
    new public IEnumerable<int> SomeList { get; set; }
}
```

If `ClassB` is serialized an exception is thrown:

>The JSON property name for 'ClassB.SomeList' collides with another property.

This seems like unwanted behavior.

**Comment by ahsonkhan** [comment]
We don't fully support polymorphic types currently and the behavior you are seeing is a side effect of that.

Here's the issue tracking that feature: https://github.com/dotnet/corefx/issues/38650 / https://github.com/dotnet/corefx/issues/37787

cc @steveharter if you have any thoughts on this specific case, where we are seeing a property name collision.

**Comment by layomia** [comment]
From @nhuthan in https://github.com/dotnet/corefx/issues/42692:

> Here is simple code:
> 
> ```
> public class Program
> {
> 	public static void Main()
> 	{
> 		var str = "{\"P1\": 123}";
> 		var obj = JsonSerializer.Deserialize<B>(str);	//--> throw
> 		
> 	}
> }
> 
> public class A{
> 	public int P1{get;set;}	
> 	public int P2{get;set;}
> }
> 
> public class B: A{
> 	public new float P1{get;set;}
> }
> ```
> 
> And I got an error:
> 
> ```
> Unhandled exception. System.InvalidOperationException: The JSON property name for 'B.P1' collides with another property.
>    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerPropertyNameConflict(JsonClassInfo jsonClassInfo, JsonPropertyInfo jsonPropertyInfo)
>    at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
>    at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
>    at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
>    at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
>    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
>    at Program.Main()
> Command terminated by signal 6
> ```
