### ISSUE TITLE
Serialization issues with System.Text.Json in SignalR

### ISSUE THREAD

**Issue by avo-tgundhus** [dotnet/corefx#41348]
#### Original issue: 
aspnet/AspNetCore/issues/14422

Serialization of TimeZoneInfo.Local fails and results in an incorrect json when sending over SignalR.

The Client uses version 3.0.
The Server is built on .NET core 2.2. 

Client code:
`HubConnection.SendAsync("Initialize", DateTime.UtcNow, TimeZoneInfo.Local);`

Server code:
`[public async Task Initialize(DateTime clientTimeInUTC, TimeZoneInfo clientTimeZone) { .. }]`

### Expected  behavior
How the TimeZoneInfo should be parsed, and is parsed if I use NewtonSoft serializer directly.
```
{
  "id": "W. Europe Standard Time",
  "displayName": "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
  "standardName": "W. Europe Standard Time",
  "daylightName": "W. Europe Daylight Time",
  "baseUtcOffset": {
    "ticks": 36000000000,
    "days": 0,
    "hours": 1,
    "milliseconds": 0,
    "minutes": 0,
    "seconds": 0,
    "totalDays": 0.041666666666666664,
    "totalHours": 1,
    "totalMilliseconds": 3600000,
    "totalMinutes": 60,
    "totalSeconds": 3600
  },
  "supportsDaylightSavingTime": true
}
```

### Actual behavior
How it is sent via SignalR.  You can see an extra curly bracket on line 1 in the JSON. These are ONLY added if I sent through signalR. If I serialize TimeZoneInfo using NewtonSoft in either the server or the client, this works perfect and gives the json listed above. 
```
{{
  "id": "W. Europe Standard Time",
  "displayName": "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
  "standardName": "W. Europe Standard Time",
  "daylightName": "W. Europe Daylight Time",
  "baseUtcOffset": {
    "ticks": 36000000000,
    "days": 0,
    "hours": 1,
    "milliseconds": 0,
    "minutes": 0,
    "seconds": 0,
    "totalDays": 0.041666666666666664,
    "totalHours": 1,
    "totalMilliseconds": 3600000,
    "totalMinutes": 60,
    "totalSeconds": 3600
  },
  "supportsDaylightSavingTime": true
}}
```

#### Exception
Exception message: _System.Runtime.Serialization.SerializationException: Member 'Id' was not found._
```
2019-09-25 10:41:37 Failed to invoke hub method '"Initialize"'.
System.IO.InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked. ---> System.Runtime.Serialization.SerializationException: Member 'Id' was not found.
   at System.Runtime.Serialization.SerializationInfo.GetElement(String name, Type& foundType)
   at System.Runtime.Serialization.SerializationInfo.GetValue(String name, Type type)
   at System.TimeZoneInfo..ctor(SerializationInfo info, StreamingContext context)
   at lambda_method(Closure , Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(JsonReader reader, JsonISerializableContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindArguments(JsonTextReader reader, IReadOnlyList`1 paramTypes)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindArguments(JsonTextReader reader, IReadOnlyList`1 paramTypes)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.ParseMessage(Utf8BufferTextReader textReader, IInvocationBinder binder)
```

#### Workaround
We've current added NewtonSoftJson to our HubConnection builder `.AddNewtonsoftJsonProtocol()` which solved the issue and everything is now working as before the update. 
[MSDN: switch to Newtonsoftjson](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#switch-to-newtonsoftjson)

**Comment by anurse** [comment]
I'm not actually able to repro this issue in a console app serializing `TimeZoneInfo` directly. It may be in our SignalR protocol layer. We'll do a little investigation on our end first.

**Comment by anurse** [comment]
Looks like this is indeed an issue on SignalR's side. Closing here. We can always re-open it :).

**Comment by BrennanConroy** [comment]
`TimeZoneInfo` implements the `ISerializable` interface which Newtonsoft takes advantage of. What this means is that when Newtonsoft tries to deserialize the json produced by System.Text.Json it fails because the format isn't what the custom `ISerializable` `TimeZoneInfo` implementation expects.

As a side note, `TimeZoneInfo` does not round-trip in the current state with S.T.J.

@steveharter Has `ISerializable` been considered for adding to the Serializer? I didn't see any open or closed issues referencing it.

**Comment by steveharter** [comment]
> @steveharter Has ISerializable been considered for adding to the Serializer? I didn't see any open or closed issues referencing it.

No there wasn't an ask for it and thus being a minimum viable product for 3.0 we didn't add it - we did look at it however against Json.NET features.

The reason `TimeZoneInfo` doesn't round-trip is because it has no public setters. We are planning on adding support for 5.0 for immutable structs where we probe for constructors taking input, but that wouldn't work here either.

However I believe it would fairly easy to write a custom converter for this type. We could include that in 5.0.

**Comment by steveharter** [comment]
Also it should be easy to write a converter for `ISerializable` -- I'll work on a sample.

**Comment by steveharter** [comment]
Here's a sample for `ISerializable` : https://github.com/steveharter/dotnet_corefx/tree/ISerializable.

It is going to be slow if benchmarked -- I haven't optimized anything and in order to get high performance there are some loosely-typed APIs that the base converter types should add (that don't use generics) or it should be built-in and not a custom converter.

Also for primitives the JSON format is an array of a custom object type that contains the integer-based TypeCode as a property. This is necessary if we care about distinguising between Double and Decimal for example (to avoid precision loss and overflow exceptions). This JSON format is not compatible with Json.NET which just assumes Double in this case -- so if we care about JSON compat this example won't work.

Pending feedback I can add this as official example for 3.0 as we have done for other custom converters. We could also have this built-in in 5.0.

**Comment by ahsonkhan** [comment]
- TimeZoneInfo is not supported currently, and requires a converter
- We don't support ISerializable interface, and will be a feature for vNext
- SignalR seems to be emitting invalid JSON for this case (double `{`) and we need to either use a custom converter, or throw, so users know to use Newtonsoft or a custom converter.

We should validate our serializer behavior - and consider throwing NSE to be explicit.

**Comment by BrennanConroy** [comment]
~~SignalR seems to be emitting invalid JSON for this case (double {) and we need to either use a custom converter, or throw, so users know to use Newtonsoft or a custom converter.~~

This was incorrectly reported.
