### ISSUE TITLE
SslStreamStreamToStreamTest_BeginEnd tests failing due to timeout

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#41357]
Saw these failures on rolling build.

https://helix.dot.net/api/2019-06-17/jobs/e8cca62d-7a69-413d-880a-7ece3f93d213/workitems/System.Net.Security.Tests/console

<details><summary>Detail</summary>
<p>

```
    System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.SslStream_StreamToStream_LargeWrites_Success(randomizedData: True) [FAIL]
      System.AggregateException : One or more errors occurred. (One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.)) (One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.))
      ---- System.AggregateException : One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.)
      -------- System.TimeoutException : VirtualNetwork: Timeout reading the next frame.
      ---- System.AggregateException : One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.)
      -------- System.TimeoutException : VirtualNetwork: Timeout reading the next frame.
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(109,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(71,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(808,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.<>c__DisplayClass0_0.<<DoHandshake>b__0>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        /_/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(42,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.WithServerCertificate(X509Certificate serverCertificate, Func`3 func)
        /_/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(804,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.DoHandshake(SslStream clientSslStream, SslStream serverSslStream, X509Certificate serverCertificate, X509Certificate clientCertificate)
        /_/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(273,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_LargeWrites_Success(Boolean randomizedData)
        --- End of stack trace from previous location where exception was thrown ---
        ----- Inner Stack Trace #1 (System.AggregateException) -----
        
        ----- Inner Stack Trace -----
        /_/src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs(61,0): at System.Net.Test.Common.VirtualNetwork.ReadFrameCoreAsync(Boolean server, Boolean sync, CancellationToken cancellationToken)
        /_/src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs(101,0): at System.Net.Test.Common.VirtualNetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
        /_/src/System.Net.Security/src/System/Net/FixedSizeReader.cs(57,0): at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(843,0): at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|141_0(ExceptionDispatchInfo e)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(437,0): at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(407,0): at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(241,0): at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
        /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/FutureFactory.cs(546,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
        ----- Inner Stack Trace #2 (System.AggregateException) -----
        
        ----- Inner Stack Trace -----
        /_/src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs(61,0): at System.Net.Test.Common.VirtualNetwork.ReadFrameCoreAsync(Boolean server, Boolean sync, CancellationToken cancellationToken)
        /_/src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs(101,0): at System.Net.Test.Common.VirtualNetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
        /_/src/System.Net.Security/src/System/Net/FixedSizeReader.cs(57,0): at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(843,0): at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|141_0(ExceptionDispatchInfo e)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(437,0): at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(407,0): at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(288,0): at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
        /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/FutureFactory.cs(546,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
        --- End of stack trace from previous location where exception was thrown ---
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(83,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
    System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.SslStream_StreamToStream_WriteAsync_ReadByte_Success [FAIL]
      System.AggregateException : One or more errors occurred. (One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.)) (One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.))
      ---- System.AggregateException : One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.)
      -------- System.TimeoutException : VirtualNetwork: Timeout reading the next frame.
      ---- System.AggregateException : One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.)
      -------- System.TimeoutException : VirtualNetwork: Timeout reading the next frame.
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(109,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(71,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(808,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.<>c__DisplayClass0_0.<<DoHandshake>b__0>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        /_/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(42,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.WithServerCertificate(X509Certificate serverCertificate, Func`3 func)
        /_/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(804,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.DoHandshake(SslStream clientSslStream, SslStream serverSslStream, X509Certificate serverCertificate, X509Certificate clientCertificate)
        /_/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(381,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_WriteAsync_ReadByte_Success()
        --- End of stack trace from previous location where exception was thrown ---
        ----- Inner Stack Trace #1 (System.AggregateException) -----
        
        ----- Inner Stack Trace -----
        /_/src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs(61,0): at System.Net.Test.Common.VirtualNetwork.ReadFrameCoreAsync(Boolean server, Boolean sync, CancellationToken cancellationToken)
        /_/src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs(101,0): at System.Net.Test.Common.VirtualNetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
        /_/src/System.Net.Security/src/System/Net/FixedSizeReader.cs(57,0): at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(843,0): at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|141_0(ExceptionDispatchInfo e)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(437,0): at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(407,0): at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(241,0): at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
        /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/FutureFactory.cs(546,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
        ----- Inner Stack Trace #2 (System.AggregateException) -----
        
        ----- Inner Stack Trace -----
        /_/src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs(61,0): at System.Net.Test.Common.VirtualNetwork.ReadFrameCoreAsync(Boolean server, Boolean sync, CancellationToken cancellationToken)
        /_/src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs(101,0): at System.Net.Test.Common.VirtualNetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
        /_/src/System.Net.Security/src/System/Net/FixedSizeReader.cs(57,0): at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(843,0): at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|141_0(ExceptionDispatchInfo e)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(437,0): at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(407,0): at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(288,0): at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
        /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/FutureFactory.cs(546,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
        --- End of stack trace from previous location where exception was thrown ---
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(83,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
    System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.SslStream_StreamToStream_Dispose_Throws [FAIL]
      System.AggregateException : One or more errors occurred. (One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.)) (One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.))
      ---- System.AggregateException : One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.)
      -------- System.TimeoutException : VirtualNetwork: Timeout reading the next frame.
      ---- System.AggregateException : One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.)
      -------- System.TimeoutException : VirtualNetwork: Timeout reading the next frame.
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(109,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(71,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(808,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.<>c__DisplayClass0_0.<<DoHandshake>b__0>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        /_/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(42,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.WithServerCertificate(X509Certificate serverCertificate, Func`3 func)
        /_/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(804,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.DoHandshake(SslStream clientSslStream, SslStream serverSslStream, X509Certificate serverCertificate, X509Certificate clientCertificate)
        /_/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(506,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Dispose_Throws()
        --- End of stack trace from previous location where exception was thrown ---
        ----- Inner Stack Trace #1 (System.AggregateException) -----
        
        ----- Inner Stack Trace -----
        /_/src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs(61,0): at System.Net.Test.Common.VirtualNetwork.ReadFrameCoreAsync(Boolean server, Boolean sync, CancellationToken cancellationToken)
        /_/src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs(101,0): at System.Net.Test.Common.VirtualNetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
        /_/src/System.Net.Security/src/System/Net/FixedSizeReader.cs(57,0): at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(843,0): at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|141_0(ExceptionDispatchInfo e)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(437,0): at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(407,0): at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(241,0): at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
        /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/FutureFactory.cs(546,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
        ----- Inner Stack Trace #2 (System.AggregateException) -----
        
        ----- Inner Stack Trace -----
        /_/src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs(61,0): at System.Net.Test.Common.VirtualNetwork.ReadFrameCoreAsync(Boolean server, Boolean sync, CancellationToken cancellationToken)
        /_/src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs(101,0): at System.Net.Test.Common.VirtualNetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
        /_/src/System.Net.Security/src/System/Net/FixedSizeReader.cs(57,0): at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(843,0): at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|141_0(ExceptionDispatchInfo e)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(437,0): at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(407,0): at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(288,0): at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
        /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/FutureFactory.cs(546,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
        --- End of stack trace from previous location where exception was thrown ---
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(83,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
    System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.SslStream_StreamToStream_Write_ReadByte_Success [FAIL]
      System.AggregateException : One or more errors occurred. (One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.)) (One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.))
      ---- System.AggregateException : One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.)
      -------- System.TimeoutException : VirtualNetwork: Timeout reading the next frame.
      ---- System.AggregateException : One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.)
      -------- System.TimeoutException : VirtualNetwork: Timeout reading the next frame.
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(109,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(71,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(808,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.<>c__DisplayClass0_0.<<DoHandshake>b__0>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        /_/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(42,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.WithServerCertificate(X509Certificate serverCertificate, Func`3 func)
        /_/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(804,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.DoHandshake(SslStream clientSslStream, SslStream serverSslStream, X509Certificate serverCertificate, X509Certificate clientCertificate)
        /_/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(358,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Write_ReadByte_Success()
        --- End of stack trace from previous location where exception was thrown ---
        ----- Inner Stack Trace #1 (System.AggregateException) -----
        
        ----- Inner Stack Trace -----
        /_/src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs(61,0): at System.Net.Test.Common.VirtualNetwork.ReadFrameCoreAsync(Boolean server, Boolean sync, CancellationToken cancellationToken)
        /_/src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs(101,0): at System.Net.Test.Common.VirtualNetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
        /_/src/System.Net.Security/src/System/Net/FixedSizeReader.cs(57,0): at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(843,0): at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|141_0(ExceptionDispatchInfo e)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(437,0): at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(407,0): at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(241,0): at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
        /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/FutureFactory.cs(546,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
        ----- Inner Stack Trace #2 (System.AggregateException) -----
        
        ----- Inner Stack Trace -----
        /_/src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs(61,0): at System.Net.Test.Common.VirtualNetwork.ReadFrameCoreAsync(Boolean server, Boolean sync, CancellationToken cancellationToken)
        /_/src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs(101,0): at System.Net.Test.Common.VirtualNetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
        /_/src/System.Net.Security/src/System/Net/FixedSizeReader.cs(57,0): at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(843,0): at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|141_0(ExceptionDispatchInfo e)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(437,0): at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(407,0): at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(288,0): at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
        /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/FutureFactory.cs(546,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
        --- End of stack trace from previous location where exception was thrown ---
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(83,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
  Finished:    System.Net.Security.Tests
```
</p>
</details>

Looks like we could use some retry logic here.

**Comment by ViktorHofer** [comment]
cc @davidsh, @wfurt, @scalablecory, @eiriktsarpalis, @karelz

**Comment by wfurt** [comment]
I don't see any failures since https://github.com/dotnet/runtime/pull/453 was submitted. Last failure 12/13 and it was failing frequently before. 
This test does use memory stream so it should be quite predictable as long as the test machine is in a reasonable state. All failures occurred on Windows. 
I will watch it and I'll close it if there is no failure for another 30 days.
