### ISSUE TITLE
Common Language Runtime detected an invalid program

### ISSUE THREAD

**Issue by AsadCheema** [dotnet/corefx#4135]
Using Csla 4.5.701, using remote data-portal in Window 8.1 Store app. Trying to create/instantiate new Object, generating following error (i can fetch existing object from DB successfully),
System.AggregateException: One or more errors occurred. ---> Csla.Server.DataPortalException: DataPortal.Create failed on the server ---> System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
   at System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate()
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator)
   at System.Linq.Expressions.Expression`1.Compile()
   at Csla.Reflection.DynamicMethodHandlerFactory.CreateConstructor(ConstructorInfo constructor)
   at Csla.Reflection.MethodCaller.GetCachedConstructor(Type objectType)
   at Csla.Reflection.MethodCaller.CreateInstance(Type objectType)
   at Csla.Server.DefaultDataPortalActivator.CreateInstance(Type requestedType)
   at Csla.Server.SimpleDataPortal.<Create>d__0.MoveNext()
   --- End of inner exception stack trace ---
   at Csla.Server.DataPortal.NewDataPortalException(String message, Exception innerException, Object businessObject)
   at Csla.Server.SimpleDataPortal.<Create>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Csla.Server.DataPortalSelector.<Create>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Csla.Server.DataPortal.<Create>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Csla.DataPortalClient.LocalProxy.<>c__DisplayClass1_0.<Create>b__0(Object s, DoWorkEventArgs o)
   at Csla.Threading.BackgroundWorker.InternalDoWork(Object sender, DoWorkEventArgs e)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Csla.DataPortalClient.LocalProxy.<Create>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Csla.DataPortal`1.<DoCreateAsync>d__8.MoveNext()
---> (Inner Exception #0) Csla.Server.DataPortalException: DataPortal.Create failed on the server ---> System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
   at System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate()
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator)
   at System.Linq.Expressions.Expression`1.Compile()
   at Csla.Reflection.DynamicMethodHandlerFactory.CreateConstructor(ConstructorInfo constructor)
   at Csla.Reflection.MethodCaller.GetCachedConstructor(Type objectType)
   at Csla.Reflection.MethodCaller.CreateInstance(Type objectType)
   at Csla.Server.DefaultDataPortalActivator.CreateInstance(Type requestedType)
   at Csla.Server.SimpleDataPortal.<Create>d__0.MoveNext()
   --- End of inner exception stack trace ---
   at Csla.Server.DataPortal.NewDataPortalException(String message, Exception innerException, Object businessObject)
   at Csla.Server.SimpleDataPortal.<Create>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Csla.Server.DataPortalSelector.<Create>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Csla.Server.DataPortal.<Create>d__4.MoveNext()<---

**Comment by bartdesmet** [comment]
For bookkeeping purposes:

https://github.com/MarimerLLC/csla/blob/d3a2b0707f56b619d6ad46a517a572f3fdeb729d/Source/Csla.Shared/Reflection/DynamicMethodHandlerFactory.cs

contains the code that triggers the erroneous condition:

```
System.InvalidProgramException: Common Language Runtime detected an invalid program.
 at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
 at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
 at System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate()
 at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator)
 at System.Linq.Expressions.Expression 1.Compile() at Csla.Reflection.DynamicMethodHandlerFactory.CreateConstructor(ConstructorInfo constructor)
```

**Comment by bartdesmet** [comment]
@AsadCheema, thanks for reporting this. I found two interesting cases:

- The `ConstructorInfo` passed in is a static constructor. The `New` factory should throw to reject this, but it doesn't, so it gets to the compiler which generates a `newobj` against a static constructor, causing the exception you've reported.
- The `ConstructorInfo` passed in is a constructor in an abstract class. It's debatable whether the `New` factory should reject this, from a backwards-compatibility point of view. The call stack for this is shown below. It doesn't cause the same exception though.

```
Unhandled Exception: System.InvalidOperationException: Instances of abstract classes cannot be created.
   at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
   at System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate()
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator)
   at System.Linq.Expressions.Expression`1.Compile()
```

I'll prepare a PR with some fixes and we'll discuss the compatibility implications over here. Either way, Csla will have to make a change not to attempt to cache static constructor invocations. Unless there's another case triggering this condition, it seems the offending code should be in https://github.com/MarimerLLC/csla/blob/d3a2b0707f56b619d6ad46a517a572f3fdeb729d/Source/Csla.Shared/Reflection/MethodCaller.cs:

```csharp
ConstructorInfo info = objectType.GetConstructor(ctorFlags, null, new Type[] { }, null);
```

It looks like this is correct though, given that the ctorFlags exclude static members. However, I'm seeing a conditional compilation for NETFX_CORE there, so maybe the GetConstructor extension method (used for backwards compatibility with legacy reflection) is not honoring the flag. This should be investigated further.

**Comment by bartdesmet** [comment]
It looks like the issue in CSLA is in TypeExtensions.GetConstructor where it doesn't do anything with the parameters. See https://github.com/MarimerLLC/csla/blob/d3a2b0707f56b619d6ad46a517a572f3fdeb729d/Source/Csla.Shared/Reflection/TypeExtensions.cs. I've opened an issue on their side as well, see https://github.com/MarimerLLC/csla/issues/476.

**Comment by leppie** [comment]
LOL, that code is utter nonsense!

**Comment by rockfordlhotka** [comment]
True @leppie - it was written for Windows 8/WinRT back when it looked like supporting WinRT was (to be honest) a waste of effort, so I did the least work necessary to get things working at that time.

Now that Windows 10/UWP appears to be gaining traction as a viable platform and has a workable side-loading story for business apps (whew!) I think it is totally worth revisiting the code necessary to achieve backward compat for the reflection changes between UWP and the rest of the world (honestly, I was rather hoping _Microsoft_ would create a backward compat library to do this, since they are the ones that broke reflection in the first place :smile: ).

**Comment by leppie** [comment]
@rockfordlhotka I got a response it was likely to make it API compatible. So not really nonsense, but without a source comment, it looked like it :)

**Comment by weshaggard** [comment]
@rockfordlhotka We have added a large amount of the reflection extensions, see https://github.com/dotnet/corefx/tree/master/src/System.Reflection.TypeExtensions. We agree there is more to be done to help with the reflection APIs but that should be a good step. Please let us know if there are common ones you need that are missing.

**Comment by VSadov** [comment]
it looks like this has been fixed by https://github.com/dotnet/corefx/pull/4167
