### ISSUE TITLE
GetAsync_ExpectContinueTrue_NoContent_StillSendsHeader failing in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#41366]
https://dnceng.visualstudio.com/public/_build/results?buildId=366818&view=ms.vss-test-web.build-test-results-tab&runId=11098392&resultId=100001&paneView=attachments

Configuration: `netcoreapp-Windows_NT-Release-arm64-Windows.10.Arm64.Open`

```
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_ExpectContinueTrue_NoContent_StillSendsHeader [FAIL]
      System.TimeoutException : Task timed out after 00:01:00
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(44,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs(1939,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_ExpectContinueTrue_NoContent_StillSendsHeader()
        --- End of stack trace from previous location where exception was thrown ---
```

@geoffkizer, @wfurt, @davidsh, @scalablecory, @eiriktsarpalis, @karelz

**Comment by eiriktsarpalis** [comment]
[Relevant test code](https://github.com/dotnet/corefx/blob/e667c29636a622eb4f9493f75232b44e0ae90b29/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs#L1933-L1960). Not clear to me what could be causing the hang.
