### ISSUE TITLE
HttpListenerRequestUriBuilder.GetPath throw IndexOutOfRangeException

### ISSUE THREAD

**Issue by zz1231118** [dotnet/corefx#41406]
# Issue HttpListenerRequestUriBuilder.GetPath throw IndexOutOfRangeException
.net core 
System.Net.HttpListener

# General
```
AppDomain: UnhandledException:System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Net.HttpListenerRequestUriBuilder.GetPath(String uriString)
   at System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath()
   at System.Net.HttpListenerRequestUriBuilder.Build()
   at System.Net.HttpListenerRequest.FinishInitialization()
   at System.Net.HttpConnection.OnReadInternal(IAsyncResult ares)
   at System.Net.HttpConnection.OnRead(IAsyncResult ares)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback()
   at System.Net.ContextAwareResult.<>c.<Complete>b__15_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError errorCode)
   at System.Net.Sockets.OverlappedAsyncResult.CompletionCallback(Int32 numBytes, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError errorCode)
   at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.InvokeCallback(Boolean allowPooling)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.<>c.<.cctor>b__18_0(Object op)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by zz1231118** [comment]
> ```cs
> var httpListener = new HttpListener();
> httpListener.Prefixes.Add("xxx");
> httpListener.Start();
> httpListener.BeginGetContext(new AsyncCallback(ProcessAccept), null);
> ```
> 
> Is this the literal code you wrote? I'm missing something here but did you actually add the prefix "xxx"?

I'm using：http://cloud.youxi.com/

**Comment by susuchaoren** [comment]
**i have the same question.
how to fix it?**

**Comment by alnikola** [comment]
I'm trying to reproduce this issue, but the following code properly accepts a simple GET request (navigate to ```http://localhost:36123``` in a browser) on the latest .Net Core version. Could you please tell me what type of request you try to accept? Does the below code fail on you machine?
```C#
var listener = new HttpListener();
listener.Prefixes.Add($"http://*:36123/");
listener.Start();
HttpListenerContext context = await listener.GetContextAsync();
Console.WriteLine(context.Request.Url);

**Comment by karelz** [comment]
Triage: Looks like Linux only. On Linux most folks use Kestrel, which should be fine.

**Comment by ManickaP** [comment]
Tested on **.NET Core 3.1**, native Linux and WSL 2 as well, hit no exception, everything worked.
