### ISSUE TITLE
System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Uses_dictionary_linked_list_switch_does_not_throw failed on PR

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#41528]
Error Message: 
>Timed out at 10/2/2019 7:51:03 PM after 60000ms waiting for remote process.\n\tProcess ID: 5178\n\tHandle: 940\n

Stack Trace:
```
at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 131
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 55
   at System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Uses_dictionary_linked_list_switch_does_not_throw() in /_/src/System.Text.RegularExpressions/tests/Regex.Cache.Tests.cs:line 110
```

https://dev.azure.com/dnceng/public/_build/results?buildId=374243&view=ms.vss-test-web.build-test-results-tab&runId=11449956&resultId=158563&paneView=debug

cc: @ViktorHofer @maryamariyan

**Comment by danmosemsft** [comment]
This isn't doing anything that should take more than a moment. Need a dump file to diagnose this and that didn't happen because of https://github.com/dotnet/core-eng/issues/7950

**Comment by danmosemsft** [comment]
netcoreapp-Linux-Debug-x64-RedHat.7.Amd64.Open
