### ISSUE TITLE
System.Net.Tests.AuthenticationManagerTest.CustomTargetNameDictionary_ValidCollection failed in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#41619]
https://dev.azure.com/dnceng/public/_build/results?buildId=380511&view=ms.vss-test-web.build-test-results-tab&runId=11763518&paneView=debug&resultId=147963

Configuration: `netcoreapp-Windows_NT-Debug-x64-Windows.81.Amd64.Open`

```
System.Net.Tests.AuthenticationManagerTest.CustomTargetNameDictionary_ValidCollection

Timed out at 10/7/2019 8:39:55 PM after 60000ms waiting for remote process.\r\n\tProcess ID: 5404\r\n\tHandle: 1096\r\n\tName: dotnet\r\n\tMainModule: C:\\dotnetbuild\\work\\ddad0c4a-3d2b-409b-b8b2-09e253a66230\\Payload\\dotnet.exe\r\n\tStartTime: 10/7/2019 8:38:55 PM\r\n\tTotalProcessorTime: 00:00:00.1875000\r\n\tThreads:\r\n\t\tThread #1 (OS 0x152C) \r\n\t\t\t[InlinedCallFrame] (System.Environment._Exit)\r\n\t\t\t[InlinedCallFrame] (System.Environment._Exit)\r\n\t\t\tSystem.Environment.Exit(Int32)\r\n\t\t\tMicrosoft.DotNet.RemoteExecutor.Program.Main(System.String[])\r\n\t\t\t[GCFrame]\r\n\t\t\t[GCFrame]\r\n\t\tThread #2 (OS 0x1538) [Finalizer]\r\n\t\t\t[DebuggerU2MCatchHandlerFrame]\r\n\t\tThread #3 (OS 0x1528) [Thread pool worker]\r\n
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 131
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 55
   at System.Net.Tests.AuthenticationManagerTest.CustomTargetNameDictionary_ValidCollection() in /_/src/System.Net.Requests/tests/AuthenticationManagerTest.cs:line 93
```

cc @davidsh, @wfurt, @scalablecory, @eiriktsarpalis, @karelz
cc @stephentoub for another hang

**Comment by davidsh** [comment]
Test is here:
https://github.com/dotnet/corefx/blob/89b087ba5548338bb604db4e1cca0e42f8273e2b/src/System.Net.Requests/tests/AuthenticationManagerTest.cs#L86-L105

**Comment by davidsh** [comment]
This test doesn't even use any I/O!

My guess is that it is hanging due to bugs(?) with RemoteExecutor or perhaps the CI machine is way too busy for dispatch a new process to run the RemoteExecutor.

**Comment by stephentoub** [comment]
> My guess is that it is hanging due to bugs(?) with RemoteExecutor or perhaps the CI machine is way too busy for dispatch a new process to run the RemoteExecutor.

I'm fairly sure it's neither.  It looks like a hang in Environment.Exit.  This has been happening with some frequency in CI over the past week at least.
```
      		Thread #1 (OS 0x152C) 
      			[InlinedCallFrame] (System.Environment._Exit)
      			[InlinedCallFrame] (System.Environment._Exit)
      			System.Environment.Exit(Int32)
      			Microsoft.DotNet.RemoteExecutor.Program.Main(System.String[])
      			[GCFrame]
      			[GCFrame]
      		Thread #2 (OS 0x1538) [Finalizer]
      			[DebuggerU2MCatchHandlerFrame]
      		Thread #3 (OS 0x1528) [Thread pool worker]
```

**Comment by stephentoub** [comment]
@ViktorHofer, this isn't specific to this particular test.

**Comment by ViktorHofer** [comment]
Do you suggest to close the issue? Do we have a tracking issue for the Environment.Exit hang?

**Comment by stephentoub** [comment]
I don't know if we have an issue for it.  Assuming we don't, I suggest just re-appropriating this for that.

**Comment by ViktorHofer** [comment]
cc @jkotas

**Comment by danmosemsft** [comment]
@stephentoub from the stack above, it seems you have a dump?

Presumably this would be a bug in the runtime, as that's all Environment.Exit calls.

**Comment by stephentoub** [comment]
> from the stack above, it seems you have a dump?

No.  You can see the same text in the message Viktor pasted in his initial post, just not as nicely formatted.  A while back I augmented RemoteInvoke to (on Windows) use clrmd to attach to the child process and walk/print out the child stacks just before RemoteInvoke terminates it; that's what this is showing.  A dump is not getting created/uploaded for the child process.  According to the infrastructure folks, we in theory should be able to cause a dump by getting the child process to throw an unhandled exception instead of killing it, but doing that will require some work.

> Presumably this would be a bug in the runtime, as that's all Environment.Exit calls.

Yes, @jkotas thinks it's most likely an issue with EventPipe shutdown.

**Comment by jkotas** [comment]
Or we can call [MiniDumpWriteDump](https://docs.microsoft.com/en-us/windows/win32/api/minidumpapiset/nf-minidumpapiset-minidumpwritedump) to create the dump. Does RemoteExecutor have a way to get the right path to save the dump to, so that it gets included with the test results?

**Comment by ViktorHofer** [comment]
@MattGal how are uploaded dumps discovered today? (see @jkotas question above)

**Comment by stephentoub** [comment]
> Or we can call MiniDumpWriteDump to create the dump

That's a good idea.

If @MattGal can tell us where we would need to save the dump for it to be discovered, I can make the relevant change.

**Comment by MattGal** [comment]
@stephentoub simply write anything you want to be archived in the results container to $HELIX_WORKITEM_UPLOAD_ROOT / %HELIX_WORKITEM_UPLOAD_ROOT% (pick appropriate env var).

Do note we have a bug right now which I've merged but not rolled out a fix for that if you make SO many files in that directory that it takes > { the entire work item timeout + 10 minutes} to upload that things will go very, very badly (this is what happened recently on OSX 10.13).  Less of a problem on Azure VMs though.

**Comment by stephentoub** [comment]
Thanks, @MattGal.  It works.

**Comment by stephentoub** [comment]
@jkotas, didn't take long, we got a dump here:
https://helix.dot.net/api/2019-06-17/jobs/58ed3af6-a888-4c33-ad66-2a0d6ed754a3/workitems/System.Runtime.Tests/files/3492.2rf1xaxh.qwv.dmp
from https://github.com/dotnet/corefx/pull/41712 in @bartonjs' PR.
![image](https://user-images.githubusercontent.com/2642209/66591539-2cf32c80-eb61-11e9-8cb3-59691c0e1f6c.png)

**Comment by jkotas** [comment]
Yes, this is EventPipe shutdown as expected.
