### ISSUE TITLE
Test failure: System.Tests.StringTests.ToUpper_TurkishI_EnglishUSCulture

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#41699]
Test `System.Tests.StringTests.ToUpper_TurkishI_EnglishUSCulture` has failed.

```
 System.Tests.StringTests.ToUpper_TurkishI_EnglishUSCulture(s: "I", expected: "I") [FAIL]
      Timed out at 10/10/2019 12:49:19 AM after 60000ms waiting for remote process.
      	Process ID: 6716
      	Handle: 1244
      	Name: dotnet
      	MainModule: C:\dotnetbuild\work\5f1b1b2e-29d1-4e69-9a86-dd1963109f53\Payload\dotnet.exe
      	StartTime: 10/10/2019 12:48:19 AM
      	TotalProcessorTime: 00:00:00.1562500
      	Threads:
      		Thread #1 (OS 0x1A48) 
      			[InlinedCallFrame]
      			System.Environment.Exit(Int32)
      			Microsoft.DotNet.RemoteExecutor.Program.Main(System.String[])
      			[GCFrame]
      			[GCFrame]
      		Thread #2 (OS 0x1A0C) [Finalizer]
      			[DebuggerU2MCatchHandlerFrame]
      		Thread #3 (OS 0x1970) [Thread pool worker]
      
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(131,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(55,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/Common/tests/Tests/System/StringTests.cs(5647,0): at System.Tests.StringTests.ToUpper_TurkishI_EnglishUSCulture(String s, String expected)
  Finished:    System.Runtime.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.Tests  Total: 34299, Errors: 0, Failed: 1, Skipped: 19, Time: 78.532s
----- end Thu 10/10/2019  0:49:21.82 ----- exit code 1 ----------------------------------------------------------
```

Build:[20191009.59](https://dnceng.visualstudio.com/public/_build/results?buildId=383488)(Master)

Details:
https://helix.dot.net/api/2019-06-17/jobs/5f1b1b2e-29d1-4e69-9a86-dd1963109f53/workitems/System.Runtime.Tests/console

**Comment by danmosemsft** [comment]
@jkotas do you know whether anyone is looking into the Exit hang?

**Comment by stephentoub** [comment]
@danmosemsft, I added dump generation yesterday to RemoteExecutor to help with this. Looking into it can proceed when we have a dump.

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/41619
