### ISSUE TITLE
The server returned an invalid or unrecognized response

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4171]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/5650/console
```
System.Net.Http.Functional.Tests.PostScenarioTest.PostEmptyContentUsingChunkedEncoding_Success(serverUri: https://corefx-networking.azurewebsites.net/Echo.ashx) [FAIL]
        System.Net.Http.HttpRequestException : An error occurred while sending the request.
        ---- System.IO.IOException : The write operation failed, see inner exception.
        -------- System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response
        Stack Trace:
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Http\tests\FunctionalTests\PostScenarioTest.cs(152,0): at System.Net.Http.Functional.Tests.PostScenarioTest.<PostHelper>d__2b.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Http\tests\FunctionalTests\PostScenarioTest.cs(62,0): at System.Net.Http.Functional.Tests.PostScenarioTest.<PostEmptyContentUsingChunkedEncoding_Success>d__6.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           ----- Inner Stack Trace -----
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestStream.cs(160,0): at System.Net.Http.WinHttpRequestStream.<EndUploadAsync>d__0.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(1326,0): at System.Net.Http.WinHttpHandler.<InternalSendRequestBodyAsync>d__15.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(847,0): at System.Net.Http.WinHttpHandler.<StartRequest>d__5.MoveNext()
           ----- Inner Stack Trace -----
```

**Comment by davidsh** [comment]
I suspect this is a transient Azure problem.

**Comment by davidsh** [comment]
There is nothing actionable about this right now. I suspect that Azure went down or some other network connection was interrupted while this test was running (and in the process of writing data to the outbound request stream).

**Comment by CIPop** [comment]
Reopening and tracking the more generic Azure failure with this issue.

**Comment by CIPop** [comment]
This error has been seen in both `WinHttpHandler` and `ClientWebSocket` implementations when connecting to an Azure endpoint.
We have not seen this error within the internal ToF tests against lab (IIS) endpoints.

**Comment by ericeil** [comment]
Failed here: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/2297/testReport/System.Net.WebSockets.Client.Tests/SendReceiveTest/SendReceive_PartialMessage_Success_server__wss___corefx_net_cloudapp_net_WebSocket_EchoWebSocket_ashx_/

**Comment by stephentoub** [comment]
Again: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/2310/consoleText

**Comment by stephentoub** [comment]
Again: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug/686/consoleText

**Comment by stephentoub** [comment]
Again: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/73/consoleText

**Comment by stephentoub** [comment]
Again: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/2702/consoleText

**Comment by davidsh** [comment]
Mitigated with PR #11341 and future work part of issue #11345
