### ISSUE TITLE
Ensure FileStatus' Unix exception throwing behavior matches Windows

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/corefx#41719]
Initially reported by @davidfowl and discussed via email with @JeremyKuhne : we need to make sure Unix matches Windows when it comes to capturing and throwing exceptions.

David got this callstack when the Docker container got disconnected:

```
Unhandled exception. Unhandled exception. System.IO.IOException: Input/output error
   at System.IO.FileStatus.EnsureStatInitialized(ReadOnlySpan`1 path, Boolean continueOnError)
   at System.IO.FileStatus.GetLastWriteTime(ReadOnlySpan`1 path, Boolean continueOnError)
   at Microsoft.Extensions.FileProviders.Physical.PollingFileChangeToken.GetLastWriteTimeUtc()
   at Microsoft.Extensions.FileProviders.Physical.PollingFileChangeToken.get_HasChanged()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.RaiseChangeEvents(Object state)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()System.IO.IOException: Input/output error
   at System.IO.FileStatus.EnsureStatInitialized(ReadOnlySpan`1 path, Boolean continueOnError)
   at System.IO.FileStatus.GetLastWriteTime(ReadOnlySpan`1 path, Boolean continueOnError)
   at Microsoft.Extensions.FileProviders.Physical.PollingFileChangeToken.GetLastWriteTimeUtc()
   at Microsoft.Extensions.FileProviders.Physical.PollingFileChangeToken.get_HasChanged()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.RaiseChangeEvents(Object state)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

**Comment by TheAngryByrd** [comment]
I had a similar problem while using `dotnet watch run` inside a docker container.

```
 Unhandled Exception: System.IO.IOException: Input/output error
    at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
    at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
    at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.ForeachEntityInDirectory(DirectoryInfo dirInfo, Action`1 fileAction) in /_/src/dotnet-watch/Internal/FileWatcher/PollingFileWatcher.cs:line 192
    at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.ForeachEntityInDirectory(DirectoryInfo dirInfo, Action`1 fileAction) in /_/src/dotnet-watch/Internal/FileWatcher/PollingFileWatcher.cs:line 192
    at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.ForeachEntityInDirectory(DirectoryInfo dirInfo, Action`1 fileAction) in /_/src/dotnet-watch/Internal/FileWatcher/PollingFileWatcher.cs:line 192
    at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.CheckForChangedFiles() in /_/src/dotnet-watch/Internal/FileWatcher/PollingFileWatcher.cs:line 137
    at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.PollingLoop() in /_/src/dotnet-watch/Internal/FileWatcher/PollingFileWatcher.cs:line 68
    at System.Threading.Thread.ThreadMain_ThreadStart()
    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by PaigeM89** [comment]
We ran into TheAngryByrd's error with `dotnet watch` in containers. The problem gets significantly worse when multiple containers mount the same source code - 2 or more containers is enough to make all of them barely function before throwing the error. 1 container can usually run for a bit before it (nearly inevitably) pops up.

Tested on Mac OS 10.14.6 with Docker For Mac 2.1.0.3 (Docker engine 19.03.2).

It's possible that I'm running into IO limitations of hyperkit moreso than issues with dotnet watch in a container.

**Comment by fsdrw08** [comment]
Hi, I have the same issue, I use Windows 10 vscode remote development container plug-in to development asp.net core in a Linux container, when I send HTTP request to the application, this error comes out.
