### ISSUE TITLE
HttpClient connection refused on Debian

### ISSUE THREAD

**Issue by BellBellRing** [dotnet/corefx#41770]
Hi,

I'v copy pasted this code:

```
using System; using System.Net.Http; using System.Threading.Tasks; class Program { static void Main() { Task t = new Task(DownloadPageAsync); t.Start(); Console.WriteLine("Downloading page..."); Console.ReadLine(); } static async void DownloadPageAsync() {
        // ... Target page.
        string page = "http://en.wikipedia.org/";

        // ... Use HttpClient.
        using (HttpClient client = new HttpClient()) using (HttpResponseMessage response = await client.GetAsync(page)) using (HttpContent content = response.Content) {
            // ... Read the string.
            string result = await content.ReadAsStringAsync();

            // ... Display the result.
            if (result != null && result.Length >= 50) { Console.WriteLine(result.Substring(0, 50) + "..."); } } } }
```

from [here](https://www.dotnetperls.com/httpclient) and I'm getting error:

```
Unhandled exception. System.Net.Http.HttpRequestException: Connection refused
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at test.httpclient.Program.DownloadPageAsync() in /home/myuser/scripts/dotnet/scraper/scraper/test.httpclient/Program.cs:line 21
   at test.httpclient.Program.Main() in /home/myuser/scripts/dotnet/scraper/scraper/test.httpclient/Program.cs:line 11
   at test.httpclient.Program.<Main>()
```

----------

Operating System: Debian GNU/Linux 9 (stretch)
Kernel: Linux 4.9.0-11-amd64
Architecture: x86-64

dotnet --version
3.0.100

**Comment by davidsh** [comment]
I haven't tried this repro yet, but many times websites like this prevent connections that might look like a robot. Usually, you need to need to add a `User-Agent` header to the request to make it look like a browser is accessing the page.

**Comment by BellBellRing** [comment]
I've added
client.DefaultRequestHeaders.Add("User-Agent","Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2;WOW64; Trident/6.0)");
but the error remains the same.

**Comment by am11** [comment]
The dotnetperls sample seems to be working on my Debian buster box.

Can you successfully `ping en.wikipedia.org` on your computer? Maybe replacing hostname with Wikipedia's IP address help running the sample.

**Comment by BellBellRing** [comment]
I can ping from terminal normally. Changing to ip still return "connection refused".

**Comment by davidsh** [comment]
Can you try other websites?

Perhaps your DNS for that website is redirecting you someplace.  Getting a "connection refused" socket error is when you try to connect to a ipaddress/port combination that isn't listening on that port. That would be strange for the actual website and port 80.

Getting logging and/or Wireshark traces would be useful to help figure this out as well.

**Comment by BellBellRing** [comment]
I tried a couple of other websites and still connection refused. Also wireshark shows no events when capturing http and launching "dotnet run".

**Comment by davidsh** [comment]
>I tried a couple of other websites and still connection refused. 

I think it's possible that you have a system proxy set (perhaps unintended). And that the "connection refused" messages is about the networking stack trying to connect to the proxy first.

Can you modify your code to use something like this?

```c#
var handler = new HttpClientHandler();
handler.UseProxy = false;
var client = new HttpClient(handler);
```

That will make sure to configure HttpClient to not use a proxy.

**Comment by davidsh** [comment]
And if you're running .NET Core 3.0, you can also do this:

```c#
var client = new HttpClient();
HttpClient.DefaultProxy = null;
```

**Comment by BellBellRing** [comment]
Both ways I'm getting

Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.Net.Http.HttpClient.set_DefaultProxy(IWebProxy value)
   at test.httpclient.Program.DownloadPageAsync() in

**Comment by davidsh** [comment]
>Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')

Ok.  Sorry I forgot.  You can't set the `HttpClient.DefaultProxy` to be null.

But you should be able to write code like this:

```c#
var handler = new HttpClientHandler();
handler.UseProxy = false;
var client = new HttpClient(handler);
```

Is that returning an error?

**Comment by BellBellRing** [comment]
Yes, same error.

**Comment by davidsh** [comment]
>Yes, same error.

I don't understand. Please remove the code that does `HttpClient.DefaultProxy = null`. 

If you don't do that anymore, you shouldn't be getting an error with a callstack like this:
>Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
at System.Net.Http.HttpClient.set_DefaultProxy(IWebProxy value)
at test.httpclient.Program.DownloadPageAsync() in

**Comment by BellBellRing** [comment]
Sorry, I left both of those snippets before. Now this is back:

Unhandled exception. System.Net.Http.HttpRequestException: Connection refused
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at test.httpclient.Program.DownloadPageAsync()

**Comment by BellBellRing** [comment]
Hmm, I copied that dotnetperl snippet again, applied

`var handler = new HttpClientHandler();
handler.UseProxy = false;
var client = new HttpClient(handler);` and now it works. Thank you.

**Comment by davidsh** [comment]
Great!

You should check your configured proxies on your Debian machine.  For Linux machines, we discover proxy settings by looking at environment variables, like 'http_proxy', 'HTTP_PROXY', etc.  What settings do you have for those? Perhaps they are pointing to something out of date.

**Comment by BellBellRing** [comment]
I have $http_proxy as 127.0.0.1:8888. I remember having problems with nuget and unsetting that variable was helping me to do "dotnet restore".

**Comment by davidsh** [comment]
>I have $http_proxy as 127.0.0.1:8888. I remember having problems with nuget and unsetting that variable was helping me to do "dotnet restore".

Unless you have a real proxy server running on that address, you should remove that environment variable setting.

**Comment by davidsh** [comment]
Since you are now able to get things working, we'll close the issue now. Thanks!

**Comment by BellBellRing** [comment]
I don't. Thank you, I will. Same with $https_proxy?

**Comment by davidsh** [comment]
>Same with $https_proxy?

Yes. Those variables should never be set unless you have a real proxy server running.
