### ISSUE TITLE
SslStream AuthenticateAsClientAsync blocks if the current user has no access to the client cert private key (windows certificate store)

### ISSUE THREAD

**Issue by DaveSenn** [dotnet/corefx#41781]
I've tried to create a SSL connection with SslStream on top of Socket.
This works IF the current user has access to the private key of the client cert, stored in the windows certificate store.
If the current user has NO access to the private key, the call to _AuthenticateAsClientAsync_ will block forever.

I've tested with .NET Core 3 on a Windows 10 (1903 18362.388) machine. 

```

const String hostName = "hostName";
var ipHostInfo = await Dns.GetHostEntryAsync( hostName )
						  .ConfigureAwait( false );
var ipAddress = ipHostInfo.AddressList[0];
var remoteEndPoint = new IPEndPoint( ipAddress, 61000 );

var socket = new Socket( ipAddress.AddressFamily, SocketType.Stream, ProtocolType.Tcp );
await socket.ConnectAsync( remoteEndPoint )
			.ConfigureAwait( false );

var networkStream = new NetworkStream( socket, true );
var sslStream = new SslStream( 
	networkStream,
	false,
	( sender, certificate, chain, sslPolicyErrors ) => true, // Accept invalid cert...testing
	( sender, targetHost, localCertificates, remoteCertificate, acceptableIssuers ) =>
	{
	   if ( localCertificates.Count == 1 )
		   return localCertificates[0];

	   if ( localCertificates.Count <= 1 )
		   return null;

	   const String subject = "CertSubject";
	   var match = localCertificates.Cast<X509Certificate2>()
									.FirstOrDefault( certificate => String.Compare( certificate.Subject, subject, StringComparison.OrdinalIgnoreCase ) == 0 );
	   return match;
	} );

using var store = new X509Store( "My", StoreLocation.LocalMachine );
store.Open( OpenFlags.ReadOnly );
var collection = store.Certificates;

await sslStream.AuthenticateAsClientAsync( hostName, collection, SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12 | SslProtocols.Tls13, false )
                .ConfigureAwait( false );
```

**Comment by davidsh** [comment]
@wfurt

**Comment by wfurt** [comment]
How do you make it not to have access @DaveSenn ? 
cc: @bartonjs

**Comment by davidsh** [comment]
>How do you make it not to have access @DaveSenn ?

The certificate is in the LocalMachine/MY store. Only accounts with administrator access can access the private key. This differs from certificates in the Per-User/MY store.

**Comment by DaveSenn** [comment]
@wfurt As @davidsh  has mentioned only processes running with admin rights have access to the private keys in that store. But you can give any user access to a private key under “All Tasks>Manage Private Keys…”

![2019-10-15 20_23_30-Greenshot](https://user-images.githubusercontent.com/7510324/66858949-a092a080-ef8a-11e9-971f-cd7f9b9ae0c4.png)

**Comment by wfurt** [comment]
I cannot reproduce it @DaveSenn. I have server asking for client certificate (using openssl s_server). When I remove access to the key I get following exception.

```
System.ComponentModel.Win32Exception (0x8009030D): The credentials supplied to the package were not recognized
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc) in C:\Users\toweinfu\wfurt-corefx\src\Common\src\Interop\Windows\SspiCli\SSPIWrapper.cs:line 139
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStreamPal.Windows.cs:line 471
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStreamPal.Windows.cs:line 179
   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs:line 605
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs:line 800
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs:line 736
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 447
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 668
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 622
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 570
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 527
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 493
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 668
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 622
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 570
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 527
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 493
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 668
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 622
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 570
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 527
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 493
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 668
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 622
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 570
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 527
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 493
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 668
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 622
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 809
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|141_0(ExceptionDispatchInfo e) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.cs:line 843
   at System.Net.Security.SslStream.ThrowIfExceptional() in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.cs:line 829
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 438
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 408
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.cs:line 241
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_2(IAsyncResult iar) in C:\Users\toweinfu\wfurt-corefx\src\System.Net.Security\src\System\Net\Security\SslStream.cs:line 399
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at ac.Program.Ssl() in C:\Users\toweinfu\source\repos\interfaces\Program.cs:line 61
   at ac.Program.Main(String[] args) in C:\Users\toweinfu\source\repos\interfaces\Program.cs:line 70
```

**Comment by DaveSenn** [comment]
@wfurt I wrote a small command line application to reproduce the error with the intention to shar it with you. But I was not able to reproduce the error. I then double checked with my original code…which now also works correctly (System.ComponentModel.Win32Exception (0x8009030D): The credentials supplied to the package were not recognized)!?

I don’t know what to say… everything is the same as yesterday. 
Sorry for wasting your time.

**Comment by davidsh** [comment]
>@wfurt I wrote a small command line application to reproduce the error with the intention to share it with you. But I was not able to reproduce the error. 

Given that the hang doesn't occur anymore for the repro, we'll close this issue. Let us know if you are able to reproduce it reliably again.  Thanks.

**Comment by wfurt** [comment]
If you find what was different let us know @DaveSenn. As far as the error: that is coming from low-level schannel layers. I guess it just knows there was something wrong about keys but error code is generic that we loose specific details.
