### ISSUE TITLE
[Regression] in certificate store on OSX

### ISSUE THREAD

**Issue by javiercn** [dotnet/corefx#41897]
Hi,

We've run into an issue that we think it is a regression in the handling of certificates through the certificate store on Mac OS.

After installing .NET Core 3.1 preview1 on a machine, apps can't be launch from either the command line with `dotnet <<path-to-dll>>` nor the dotnet dev-certs tool is able to export existing certificates from the machine. All this works in 3.0.

This essentially blocks development from Visual Studio for Mac. More details can be found in the linked issue below.

This is the exception `dotnet dev-certs` sees when it tries to export the certificate
```console
Interop+AppleCrypto+AppleCommonCryptoCryptographicException: The user name or passphrase you entered is not correct.\n   at Interop.AppleCrypto.X509Export(X509ContentType contentType, SafeCreateHandle cfPassphrase, IntPtr[] certHandles)\n   at Interop.AppleCrypto.X509ExportPfx(IntPtr[] certHandles, SafePasswordHandle exportPassword)\n   at Internal.Cryptography.Pal.StorePal.AppleCertificateExporter.ExportPkcs12(SafePasswordHandle password)\n   at Internal.Cryptography.Pal.StorePal.AppleCertificateExporter.Export(X509ContentType contentType, SafePasswordHandle password)\n   at Internal.Cryptography.Pal.AppleCertificatePal.Export(X509ContentType contentType, SafePasswordHandle password)\n   at System.Security.Cryptography.X509Certificates.X509Certificate.Export(X509ContentType contentType, String password)\n   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.ExportCertificate(X509Certificate2 certificate, String path, Boolean includePrivateKey, String password, DiagnosticInformation diagnostics) in /Users/jacalvar/work/AspNetCore/src/Shared/CertificateGeneration/CertificateManager.cs:line 310
```

This is the exception kestrel displays in debug mode in the console
```console
dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[1]
      Failed to authenticate HTTPS connection.
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+AppleCrypto+SslException: Internal error
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HLQJPMSPDN1E" stopped.
```

https://github.com/aspnet/AspNetCore/issues/15118

**Comment by bartonjs** [comment]
There were no changes at all in the shim layer or the managed layer for certificates between 3.0 and 3.1.

Are you sure 3.0 could export the certificate?  Perhaps that's a red herring (that it was made non-exportable and the error message is bad) and this is really an SslStream change, or something of the sort.

**Comment by javiercn** [comment]
@bartonjs thanks for looking at this.

I'm able to export the certificate in 3.0 without issues.
We haven't changed this code either between 3.0 and 3.1 either.
Can this also be a combination of the upgrade to Catalina?

**Comment by bartonjs** [comment]
> Can this also be a combination of the upgrade to Catalina?

If it was exporting in 3.0 on 10.14 and failing in 3.1 on 10.15, then yeah, I'd say that the OS upgrade is the most likely delta.

**Comment by javiercn** [comment]
Yes, but it works in 3.0 and doesn't in 3.1 on 10.15

**Comment by vcsjones** [comment]
If it's of any use, I can't reproduce this on 10.14 or 10.15 from 3.1.0-preview1.19506.1.

Any chance your keychain has gotten into a weird / wedged state? Does the symptom persist after a reboot?

**Comment by wfurt** [comment]
For Catalina you can read long thread and interaction with Apple's SID here: https://github.com/dotnet/corefx/issues/39904
However, that would not explain why 3.0 would work. When we did initial testing on Catalina, SIP simple blocks access. You can try to follow notes and see if you see anything interesting in system logs.

**Comment by mrward** [comment]
This does not seem to be specific to Catalina - happens for me on Mojave (10.14)

**Comment by danmosemsft** [comment]
@wfurt is going to take a look.

**Comment by balachir** [comment]
FYI, as part of the notarized SDK validation, we found that this issue can reproduce even in cases where 3.1 is not involved at all. 

Eg: We can repro with the following configurations:
- mac OS Catalina 10.15 + VS Mac 8.3.4 (latest-released-build) + notarized SDK 2.1.802
- mac OS Mojave 10.14.6 + VS Mac 8.3.4 (latest-released-build) + notarized SDK 2.2.402

**Comment by jeffschwMSFT** [comment]
Quick update: 
- The problematic .NET Core 3.1 preview build has been updated to a working version
- We are working through the root cause of this issue and will report back with more details (once we understand)

**Comment by haf** [comment]
I'm getting this exception on Mojave;

```
[13:25:09 DBG] Failed to authenticate HTTPS connection. <Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware>
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
  at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
  at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
  at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
  at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
  at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
  at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
  at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
  at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
  at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
  at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
  at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
  at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
  at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
  at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
  at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
--- End of exception stack trace ---
Interop+AppleCrypto+SslException: Internal error
```

but contrary to previous comments, I'm on .Net Core 3.0 and not a preview. That said, I've upgraded the versions a couple of times so the installation is with a previously installed dev cert.

**Comment by jeffschwMSFT** [comment]
What version of .NET Core are you running?

**Comment by haf** [comment]
@jeffschwMSFT 3.0.100

**Comment by jeffschwMSFT** [comment]
Adding @wfurt 

Thanks @haf.  What version of the runtime?  We released a preview version of 3.1 that had an issue with certificates, but fixed it within a week.  I am just double checking that it is not that version.

**Comment by haf** [comment]
```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.403 [/usr/local/share/dotnet/sdk]
  2.1.509 [/usr/local/share/dotnet/sdk]
  2.2.103 [/usr/local/share/dotnet/sdk]
  2.2.204 [/usr/local/share/dotnet/sdk]
  2.2.300 [/usr/local/share/dotnet/sdk]
  2.2.401 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by wfurt** [comment]
As @jeffschwMSFT this issues is specific to very specific binaries and use case. IO updated title to reflect it as well as I'm probably going to close it as root cause is understood and mitigation will be put in place outside of corefx.

As far as the info, there is difference between what you have vs what you target. I would suggest following steps:
- use KeyChain app to look at your certificates. Make sure you have exactly one 'localhost' with key.
- Make sure there are no access restrictions on private key
- Check setting on Login keychain and look for any auto-close iptions.
- run `security unlock-keychain` in same session before starting app just to be sure your keychain is open. 

if tall that fails, look at linked issue and inspect log form securityd.

**Comment by haf** [comment]
Why doesn't `dotnet dev-certs https` do that? Otherwise, why doesn't it just place a certificate file in the working directory for me to trust, should I wish to? Perhaps I'm misunderstanding something again, but I don't see how it's my problem to debug, when the certificate is managed by dotnet. If you place the certificate you own its lifetime, otherwise, you'd place it next to my code and I could work with it like I normally do.

**Comment by karelz** [comment]
@wfurt 3.1 shipped already - are we considering it for servicing 3.1.x? Or just for next milestone 5.0?
