### ISSUE TITLE
System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Promote_entries fails with Timeout

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#41905]
From https://github.com/dotnet/corefx/pull/41753

netcoreapp-Windows_NT-Debug-x64-(Windows.Nano.1809.Amd64.Open)

https://dev.azure.com/dnceng/public/_build/results?buildId=393033&view=ms.vss-test-web.build-test-results-tab&runId=12213282&resultId=145033&paneView=debug

https://helix.dot.net/api/2019-06-17/jobs/421e5238-fb5c-4d4f-8d24-a8e79abd46eb/workitems/System.Text.RegularExpressions.Tests/console
```text
===========================================================================================================

C:\helix\work\workitem>"C:\helix\work\correlation\dotnet.exe" exec --runtimeconfig System.Text.RegularExpressions.Tests.runtimeconfig.json xunit.console.dll System.Text.RegularExpressions.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Text.RegularExpressions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.RegularExpressions.Tests (found 135 test cases)
  Starting:    System.Text.RegularExpressions.Tests (parallel test collections = on, max threads = 2)
    System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Promote_entries [FAIL]
      Timed out at 10/18/2019 11:24:33 AM after 60000ms waiting for remote process.
      Wrote mini dump to: C:\helix\work\workitem\uploads\4708.wrrjax4w.c3b.dmp
      	Process ID: 4708
      	Handle: 912
      
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(152,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(55,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/System.Text.RegularExpressions/tests/Regex.Cache.Tests.cs(71,0): at System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Promote_entries()
  Finished:    System.Text.RegularExpressions.Tests
=== TEST EXECUTION SUMMARY ===
   System.Text.RegularExpressions.Tests  Total: 1454, Errors: 0, Failed: 1, Skipped: 0, Time: 118.055s
----- end Fri 10/18/2019 11:25:06.32 ----- exit code 1 ----------------------------------------------------------
```

cc @ViktorHofer

**Comment by stephentoub** [comment]
@ahsonkhan, it should have uploaded a dump from the remote process.  Were you able to grab that?  It looks like you restarted the legs.

**Comment by danmosemsft** [comment]
Previously this was blocked by https://github.com/dotnet/core-eng/issues/7950 (https://github.com/dotnet/corefx/issues/41528) .. if dumps work now that's awesome.

**Comment by stephentoub** [comment]
@danmosemsft, the one with the dump is Windows.

**Comment by danmosemsft** [comment]
@stephentoub ah, I just saw the RedHat above.

**Comment by danmosemsft** [comment]
It looks like https://github.com/dotnet/core-eng/issues/7950 was recently closed, so I would hope to get a dump from that one too.

**Comment by stephentoub** [comment]
> so I would hope to get a dump from that one too.

The dump that's relevant here is from the RemoteExecutor.Invoke child process; on Windows we now explicitly P/Invoke to MiniDumpWriteDump in order to save out a dump.  That doesn't happen on Linux.
https://github.com/dotnet/arcade/pull/4085

**Comment by danmosemsft** [comment]
Should we have an issue to find a way to do it on Linux? Presumably deploying and invoking createdump?

**Comment by stephentoub** [comment]
Sure :)

**Comment by danmosemsft** [comment]
https://github.com/dotnet/arcade/issues/4153

**Comment by ahsonkhan** [comment]
> Were you able to grab that? It looks like you restarted the legs.

No, sorry. Will remember to do that next time.

**Comment by ViktorHofer** [comment]
Here's the dump: https://helix.dot.net/api/2019-06-17/jobs/421e5238-fb5c-4d4f-8d24-a8e79abd46eb/workitems/System.Text.RegularExpressions.Tests/files

**Comment by ViktorHofer** [comment]
updated link above (edited above post as the link was wrong)

**Comment by ViktorHofer** [comment]
cc @jkotas

**Comment by ViktorHofer** [comment]
And for learning purposes, to find the uploaded files (i.e. after a retry) you can use the Helix API directly: https://helix.dot.net/api/2019-06-17/jobs/421e5238-fb5c-4d4f-8d24-a8e79abd46eb/workitems/System.Text.RegularExpressions.Tests/files

This will list all uploaded files, in this case I searched for the ".dmp" file and added it to the url: "/4708.wrrjax4w.c3b.dmp".

**Comment by stephentoub** [comment]
Thanks, @ViktorHofer.

This is happening early on in the invocation of the remote process, as we're looking up the method to invoke:
![image](https://user-images.githubusercontent.com/2642209/67148621-7fbe9980-f26f-11e9-810e-07e7d6511a74.png)
