### ISSUE TITLE
End of Stream in PostAsyncExpect100Continue_NonSuccessResponse_RequestBodyNotSent test

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#41911]
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.PostAsyncExpect100Continue_NonSuccessResponse_RequestBodyNotSent
```
System.IO.IOException : End of stream

Stack trace
   at System.Net.Test.Common.Http2LoopbackConnection.ReadBodyAsync() in /_/src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 488
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<>c__DisplayClass67_0.<<PostAsyncExpect100Continue_NonSuccessResponse_RequestBodyNotSent>b__1>d.MoveNext() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1931
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 71
   at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Int32 timeout) in /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 186
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.PostAsyncExpect100Continue_NonSuccessResponse_RequestBodyNotSent() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1899
--- End of stack trace from previous location ---
```
https://dev.azure.com/dnceng/public/_build/results?buildId=393660&view=ms.vss-test-web.build-test-results-tab&runId=12233140&resultId=157765&paneView=debug

netcoreapp-Linux-Debug-x64-(Alpine.310.Amd64.Open)ubuntu.1604.amd64.Open

**Comment by davidsh** [comment]
>System.IO.IOException : End of stream

This exception is from the loopback server. Not sure if this is a test bug, perhaps with the loopback server, or a product bug with the HTTP2 client stack.

@wfurt @scalablecory

**Comment by safern** [comment]
Happened again here: https://dev.azure.com/dnceng/public/_build/results?buildId=398603&view=ms.vss-test-web.build-test-results-tab&runId=12440644&resultId=159763&paneView=debug
