### ISSUE TITLE
SignIdentifiedContent crypo test crashes on netfx

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#41930]
https://dnceng.visualstudio.com/public/_build/results?buildId=394693&view=ms.vss-test-web.build-test-results-tab&runId=12294416&resultId=115071&paneView=attachments

Configuration: `netfx-Windows_NT-Release-x86-Windows.10.Amd64.ClientRS5.Open`

Dump is available: https://helix.dot.net/api/2019-06-17/jobs/a385f258-a76d-4267-80d7-e4ff3bb7fb3f/workitems/System.Security.Cryptography.Pkcs.Tests/files/xunit.console.exe.4384.dmp

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Security.Cryptography.X509Certificates.X509Utils._LoadCertFromBlob(Byte[] rawData, IntPtr password, UInt32 dwFlags, Boolean persistKeySet, SafeCertContextHandle& pCertCtx)
   at System.Security.Cryptography.X509Certificates.X509Utils.LoadCertFromBlob(Byte[] rawData, IntPtr password, UInt32 dwFlags, Boolean persistKeySet, SafeCertContextHandle pCertCtx)
   at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromBlob(Byte[] rawData, Object password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at Test.Cryptography.CertLoader.TryGetCertificateWithPrivateKey(Boolean exportable) in /_/src/System.Security.Cryptography.Pkcs/tests/CertLoader.cs:line 86
   at System.Security.Cryptography.Pkcs.Tests.SignedCmsTests.SignIdentifiedContent(String oidValue, String contentHex, Boolean netfxProblem) in /_/src/System.Security.Cryptography.Pkcs/tests/SignedCms/SignedCmsTests.cs:line 1291
```

cc @bartonjs

**Comment by bartonjs** [comment]
Just looking at the callstack, this is going to be an RS4 machine in the ClientRS5 pool, with the same old AV initializing crypt32.dll.  I'll confirm that by inspecting the dump in the morning.

**Comment by stephentoub** [comment]
@ViktorHofer updated the queue in #41942.  Closing assuming that'll take care of it (and that it's otherwise a known issue as @bartonjs mentioned).
