### ISSUE TITLE
System.Net.Sockets.Tests.DualModeAcceptAsync.AcceptAsyncV6BoundToSpecificV4_CantConnect failed in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#41934]
https://dnceng.visualstudio.com/public/_build/results?buildId=395162&view=ms.vss-test-web.build-test-results-tab&runId=12321658&resultId=176974&paneView=debug

Configuration: `netcoreapp-Windows_NT-Release-x64-Windows.10.Amd64.Client19H1.Open`

```
Assert.Throws() Failure\r\nExpected: typeof(System.Net.Sockets.SocketException)\r\nActual: typeof(System.TimeoutException): Timed out while waiting for either of client and server connections...\r\n---- System.TimeoutException : Timed out while waiting for either of client and server connections...
  at System.Net.Sockets.Tests.DualModeAcceptAsync.DualModeConnect_AcceptAsync_Helper(IPAddress listenOn, IPAddress connectTo) in /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 976
   at System.Net.Sockets.Tests.DualModeAcceptAsync.<AcceptAsyncV6BoundToSpecificV4_CantConnect>b__4_0() in /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 915
----- Inner Stack Trace -----
   at System.Net.Sockets.Tests.DualModeAcceptAsync.DualModeConnect_AcceptAsync_Helper(IPAddress listenOn, IPAddress connectTo) in /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 976
   at System.Net.Sockets.Tests.DualModeAcceptAsync.<AcceptAsyncV6BoundToSpecificV4_CantConnect>b__4_0() in /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 915
```

@davidsh, @wfurt, @scalablecory, @eiriktsarpalis, @karelz

**Comment by ViktorHofer** [comment]
Should we wrap the `DualModeConnect_AcceptAsync_Helper` helper function inside the RetryHelper? https://github.com/dotnet/corefx/blob/73c898d40df25bbf195e8287c6e037aa036043db/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs#L944
