### ISSUE TITLE
Intermittent "System.Net.Http.HttpRequestException: No such host is known" when making high volume in-parallel calls from a single host.

### ISSUE THREAD

**Issue by veleek** [dotnet/corefx#41972]
This bug was originally filed against the Azure KeyVault client (here https://github.com/Azure/azure-sdk-for-net/issues/7873), but after some further troubleshooting it looks like it might be an issue related to the .NET framework.  Details are mostly copied from the initial bug report there, but please see that thread for more detail.  

There is a minimum repro of the issue (that I've been able to re-create) available here: https://gist.github.com/veleek/6751f70081e13d5f8bdf3f0cb09d0a4f and as mentioned below this only seems to occur with the Visual Studio debugger attached (which slows the process down).

**Describe the bug**
When making large numbers of requests to KeyVault, .NET occasionally throws 'No such host is known' errors.  Retrying with the exact same URL always succeeds 

In this case, I'm calling a KeyVault to enumerate all the secrets and then making calls in parallel to download them all.  I can consistently enumerate a few thousand secrets in a few minutes without issues, but then it starts slowing down, and then a few of these exceptions start occurring.  The KeyVault I'm testing with has 10030 secrets, and it successfully downloads ~9990 of them.  So it's a significant number of exception hits.

KeyVault requests are performed in parallel using `System.Threading.DataFlows.TransformBlock` with 25-50 requests in parallel.  

* This only seems to occur when running under the debugger in Visual Studio
* Visual Studio 2019
* .NET Core 3.0.100
* The problem doesn't reproduce 100%, it is possible to get a completely clean run but the repro rate is high. 
* When one of these errors occur, it almost always occurs a whole bunch of times for the remainder of the run.
* This is NOT related to service side throttling at all.  If that were the case then it would be more likely to occur when running without the debugger because the process completes all 10K keys MUCH faster and has never failed without the debugger.  I think the debugger may just be exposing a much more rare threading issue.

***Exception or Stack Trace***
```
[2019-10-01 15:27:26.143T-07:00 INF]{ KeyId: "589", KeySource: "KeyVaultContentKeySource" } Key is new or changed. null, "2019-09-26T22:48:06.0000000Z"
[2019-10-01 15:30:02.264T-07:00 DBG]{ KeyId: "589", KeySource: "KeyVaultContentKeySource" } Loading key vault secret https://preload-keys-test.vault.azure.net/secrets/589
[2019-10-01 15:30:17.359T-07:00 ERR]{ KeyId: "589", KeySource: "KeyVaultContentKeySource" } Failed to load key
System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretWithHttpMessagesAsync(String vaultBaseUrl, String secretName, String secretVersion, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretAsync(IKeyVaultClient operations, String secretIdentifier, CancellationToken cancellationToken)
   at ContentKey.Cli.KeyVaultContentKeySource.LoadKey(String keyId) in E:\src\ContentKey.Cli\KeyVaultContentKeySource.cs:line 70
   at ContentKey.Cli.IContentKeySource.<>c__DisplayClass2_0.<<UpdateKeys>b__0>d.MoveNext() in E:\src\ContentKey.Cli\IContentKeySource.cs:line 49
```

**Expected behavior**
No error should be thrown.

**Setup (please complete the following information):**
 - OS: Windows (.NET Core 3.0 Console App)
 - IDE : Visual Studio

**Additional context**
I'm able to reproduce this behavior pretty consistently when running with the debugger attached (no breakpoints configured or hit or anything though), but when running from the command line with no debugger it doesn't seem to fail.

**Comment by scalablecory** [comment]
Are you able to supply a repro that doesn't require the full Azure infrastructure? Something directly using `HttpClient` would be great.

A SocketException with error 11001 indicates name resolution failure, is there any chance you've got a flaky DNS setup?

**Comment by bmarder** [comment]
Having the same exact issue with .net core 3 and azure app service and amazon S3 sdk.

**Comment by JohnL404** [comment]
I'm seeing the same exception when making repeated, rapid calls to the Azure Notification Hub using .NET Core 2.2.

**Exception:**
Microsoft.Azure.NotificationHubs.Messaging.MessagingException: Unexpected exception encountered TrackingId:fd5a6991-fe3e-4d48-84b2-374b67501738,TimeStamp:2019-11-18T17:27:37.9028139Z ---> System.Net.Http.HttpRequestException: No such host is known ---> System.Net.Sockets.SocketException: No such host is known
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.NotificationHubs.NotificationHubClient.SendRequestAsync(HttpRequestMessage request, String trackingId, HttpStatusCode[] successfulResponseStatuses, CancellationToken cancellationToken)
