### ISSUE TITLE
.NET Core 2.2: Cannot access a disposed object. Object name: 'SslStream'.

### ISSUE THREAD

**Issue by samneefs** [dotnet/corefx#41986]
I have an issue with SendAsync in .NET Core 2.2.
When doing a lot of requests, I encounter the exception on some of them. 
I have gotten the error on different requests, for example on a small GET request. However I do have to mention that asynchronously I'm also doing other requests, for example SendAsync (with content smaller than 4MB).

This issue is similar to https://github.com/dotnet/corefx/issues/34033 , but not the same. Mine doesn't mention the handshake in the stacktrace and the other one should be fixed since Core 2.1 (and I use 2.2).

The operation was canceled.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at [details of own code omitted]

Inner exception:
The read operation failed, see inner exception.
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)

Inner Exception:
Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)

**Comment by scalablecory** [comment]
Is it possible your requests are timing out? Does the same issue happen on .NET Core 3.0?

**Comment by Plasma** [comment]
Are you accidentally returning from an async method without awaiting within a using block?

**Comment by samneefs** [comment]
@scalablecory 
Some sort of timeout seems likely:
 when I do another request, that is one single long running request, to the same server I get a similar error after 10min, however, this error is not the same (and strangely it stays 10min after changing the timeout to something bigger). 
However increasing the timeout on the client (to 20 min), had no effect: still got errors before the timeout. 
On the server the executionTimeout had been increased tot 1800s (30min) and it also triggered before this.
About the original calls:
When doing all calls synchronously after each other (instead of async, multiple together), then I don't encounter the problem.
Maybe I created to much load on the server when I do it async and this breaks the connection?
I did await Task.WhenAll(tasks); maybe there is a timeout on how long I can await a task?

@Plasma 
No, I receive a task for each request and await them all with await Task.WhenAll(tasks);

**Comment by samneefs** [comment]
@scalablecory 
With the long running request, the exception is a bit different. Here are the details:

An error occurred while sending the request.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at SBB.Exact.Rest.Proxy.Handwritten.BaseExactRestApiProxy.GetAsync[T](String url, String applicationId, String division)
   at SBB.Exact.Rest.Proxy.Handwritten.BaseExactRestApiProxy.GetAllAsync[T](String applicationId, String division, String[] fields, String where, Boolean withPagination, String skiptoken, Int32 numberOfPages)
   at SBB.Exact.Rest.Proxy.Handwritten.ExactRestApiProxy.GetBulkTransactionLinesAsync(String applicationId, String division, String[] fields, String where)
   at Winbooks2Exact.Core.Tests.IntegrationTests.ExactRestIntegrationTest.GetAllTransactionLines(String dossierNr, String divisionId) in C:\Workspaces\SelectProjects\Winbooks3\Winbooks2Exact\Dev\SBB.Winbooks2Exact\Winbooks2Exact.Core.Tests\IntegrationTests\ExactRestIntegrationTest.cs:line 29
      
InnerException	
   Unable to read data from the transport connection: De externe host heeft een verbinding verbroken.
      at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
     
InnerException	
{System.Net.Sockets.SocketException (10054): De externe host heeft een verbinding verbroken}

**Comment by scalablecory** [comment]
Okay, can you reduce your code into a small repro? This will help diagnose the problem.

**Comment by davidsh** [comment]
@samneefs 
I think if the only exception were this:

```
The operation was canceled.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at [details of own code omitted]
```

then this would be perceived as "normal" behavior. By "normal", I mean that the HTTP request was cancelled probably due to a timeout-related cancellation token expiring.  The cancellation token could either be one you pass into the HttpClient APIs.  Or the internal one used when HttpClient.Timeout is used. By default HttpClient.Timeout has a non-infinite timeout.

I think the "bug" here is that while cancelling the HTTP request, there are operations that get cancelled internally (such as on SslStream). And cancelling those I/O operation results in a probably bug where we are trying to reference the, now disposed, SslStream. That is probably why those other internal exceptions are occuring. 

It would probably make sense for the HTTP stack to potentially ignore some of those exceptions since they are "expected" to occur while shutting down the connection. However, I think the SslStream ObjectDisposedException is something where we can fix that so that we don't try to access the SslStream after it has been disposed.
