### ISSUE TITLE
System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Uses_dictionary_linked_list_switch_does_not_throw fails with timeout on Linux

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#41981]
From https://github.com/dotnet/corefx/pull/41933

Fails on on netcoreapp-Linux-Debug-x64-RedHat.7.Amd64.Open

https://helix.dot.net/api/2019-06-17/jobs/15bae51c-6a2d-4d34-9e22-f01a622747d8/workitems/System.Text.RegularExpressions.Tests/console

```text
   System.Text.RegularExpressions.Tests: [Long Running Test] 'System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Uses_dictionary_linked_list_switch_does_not_throw', Elapsed: 00:02:46
[Long Running Test] 'System.Text.RegularExpressions.Tests.RegexMatchTests.Match_Timeout_Loop_Throws', Elapsed: 00:02:46
    System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Uses_dictionary_linked_list_switch_does_not_throw [FAIL]
      Timed out at 10/22/2019 5:54:39 AM after 60000ms waiting for remote process.
      	Process ID: 2117
      	Handle: 892
      
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(152,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(55,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/System.Text.RegularExpressions/tests/Regex.Cache.Tests.cs(106,0): at System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Uses_dictionary_linked_list_switch_does_not_throw()
  Finished:    System.Text.RegularExpressions.Tests
=== TEST EXECUTION SUMMARY ===
   System.Text.RegularExpressions.Tests  Total: 1454, Errors: 0, Failed: 1, Skipped: 0, Time: 186.432s
~/work/15bae51c-6a2d-4d34-9e22-f01a622747d8/Work/a46ce5a8-72f4-429c-8764-4786c3af5804/Exec
----- end Tue Oct 22 05:56:13 UTC 2019 ----- exit code 1 ----------------------------------------------------------
```

cc @ViktorHofer

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/coreclr/issues/27305
