### ISSUE TITLE
System.IO.FileLoadException: Could not load file or assembly 'System.Xml.XDocument, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Operation is not supported.

### ISSUE THREAD

**Issue by johnearnshaw** [dotnet/corefx#42040]
I have a .NETCore 2.1 application which references a set of .NETCore 2.1/2,0 libraries I've developed.

In one of the libraries I load an XML file using `XElement.Load(file);`. This works fine in Windows but when I launch my application on Ubuntu running dotnet-sdk-3.0 and try and call the `XElement.Load(file);` method I get the following exception:

`System.IO.FileLoadException: Could not load file or assembly 'System.Xml.XDocument, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'System.Xml.XDocument, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
   at System.Reflection.Emit.InternalAssemblyBuilder.get_Location()
   at reblGreen.NetCore.Modules.Classes.AssemblyLoader.<>c__DisplayClass9_0.<Load>b__0(Assembly x)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at reblGreen.NetCore.Modules.Classes.AssemblyLoader.Load(String assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at OpenTextSummarizer.Dictionary.LoadFromFile(String dictionaryDirectory, String dictionaryLanguage)`

`Inner exception: System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
   at System.Reflection.Emit.InternalAssemblyBuilder.get_Location()
   at reblGreen.NetCore.Modules.Classes.AssemblyLoader.<>c__DisplayClass9_0.<Load>b__0(Assembly x)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at reblGreen.NetCore.Modules.Classes.AssemblyLoader.Load(String assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)`

The application and referenced assemblies are built with a fresh install of Visual Studio 2017 approximately 1 month old. The csproj files and solutions are clean of any legacy nodes or references.

As I said before, The application and call to `XElement.Load(file);` works perfect in Windows, this issue is in Linux environment.

**Comment by johnearnshaw** [comment]
After further investigation I found that this issue was being caused by reference dependencies in `AppDomain.CurrentDomain.GetAssemblies()`
