### ISSUE TITLE
system.text.json IformCollection not supported

### ISSUE THREAD

**Issue by KamranShahid** [dotnet/corefx#42084]
I am migrating my newtonsoft implementation to System.text.json. For some auditing purpose i am serializing Request.Form and Request.Query previously
After conversion when i tried same in System.Text.Json i am getting following exception 

```
System.NotSupportedException: The collection type 'Microsoft.AspNetCore.Http.IFormCollection' on '<>f__AnonymousType1`2[Microsoft.AspNetCore.Http.IFormCollection,Microsoft.AspNetCore.Http.IQueryCollection].Form' is not supported.
   at System.Text.Json.JsonClassInfo.GetElementType(Type propertyType, Type parentType, MemberInfo memberInfo, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, Type implementedPropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)

```

**Comment by layomia** [comment]
@KamranShahid thanks for opening this. Can you share a snippet of the code that led to this exception? Also, what version of .NET Core are you using?

**Comment by KamranShahid** [comment]
I am using .net core 3.0
At the moment i doesn't have my code. But what was happening is I am trying to save Request Form and Query String as a serialize json. When i received the request in my controller action, I pass HttpContext's Request to my certain method where i serialize the content for some audit log. It is working perfectly fine with newtonsoft json
Thanks
