### ISSUE TITLE
BinaryFormatter includes `System.Private.CoreLib` assembly name when serializing generic parameters

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#42092]
When re-enabling binary serialization on .NETCore we took a shortcut for types that lived in corlib: we didn't add the TypeForwardedFromAttribute to the assembly.  This was because BinaryFormatter, even on desktop would omit the assembly name when the type came from desktop.
https://github.com/dotnet/corefx/pull/20879
https://github.com/dotnet/corefx/blob/32d103eecf9d1e9648e6b1ed063860fed00bcc8f/src/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/Formatters/Binary/BinaryObjectWriter.cs#L987-L992
https://referencesource.microsoft.com/#mscorlib/system/runtime/serialization/formatters/binary/binaryobjectwriter.cs,1356

This works fine for the type being serialized, this doesn't work when the type with the missing attribute is a generic parameter.  In that case the assembly information is embedded in the type string.  FormatterServices builds this type string and it is missing the special case for the core assembly:
https://github.com/dotnet/corefx/blob/bd18c12df9e5dd365a8b708cc2e7e0488b8177c1/src/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/Formatters/Binary/BinaryFormatter.cs#L105-L109
https://github.com/dotnet/corefx/blob/32d103eecf9d1e9648e6b1ed063860fed00bcc8f/src/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/FormatterServices.cs#L369-L373

The result is that generics containing types located in corlib serialized from .NETCore won't be Deserializable on .NET.  Folks will see something like 
```
Unhandled Exception: System.Runtime.Serialization.SerializationException: Unable to load type System.Collections.Generic.List`1[[System.TimeSpan, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] required for deserialization.
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
```

Discovered this when working on fix for https://github.com/dotnet/corefx/issues/42091.

/cc @ViktorHofer

**Comment by ericstj** [comment]
Marking for 5.0 since this isn't a regression.
