### ISSUE TITLE
[snap][rhel7] SSL is not working

### ISSUE THREAD

**Issue by abelykh0** [dotnet/corefx#42178]
Environment:

```
#  cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.7 (Maipo)
```

Install .Net Core using `snap` (see https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0.0/3.0.0-download.md)

```
sudo snap install dotnet-sdk --classic
sudo snap alias dotnet-sdk.dotnet dotnet
```

Run the following code:

```csharp
using System;
using System.Net;
namespace ConsoleApp32
{
    class Program
    {
        static void Main(string[] args)
        {
            Uri uri = new Uri("https://www.github.com");
            HttpWebRequest req = (HttpWebRequest)WebRequest.Create(uri);
            req.Method = "GET";
            var response = req.GetResponse();
            Console.WriteLine(response.ContentType);
        }
    }
}
```

You get the following:

```
Unhandled exception. System.Net.WebException: The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
...
```

If you run the same code on the same RHEL 7 with .Net Core installed using `yum`

```
yum-config-manager --enable rhel-7-server-dotnet-rpms
yum install rh-dotnet30
scl enable rh-dotnet30 bash
```

The output is as expected:

```
text/html; charset=utf-8
```

**Comment by wfurt** [comment]
Do you have trusted CAs installed @abelykh0 ? And what is your inner exception? That should give some clue. You can also try `openssl s_client -connect www.github.com:443 -status`

**Comment by wfurt** [comment]
cc: @tmds

**Comment by abelykh0** [comment]
> Do you have trusted CAs installed?
Don't know

> And what is your inner exception? That should give some clue. 
I have both `yum` and `snap` installs at the same time. Here is the output of `yum` dotnet:
```
$ dotnet exec ConsoleApp32.dll
text/html; charset=utf-8
```
Here is the full output of `snap` dotnet:
```
$ dotnet exec ConsoleApp32.dll
text/html; charset=utf-8
[andreyb@andreyb-rhel netcoreapp3.0]$ dotnet-sdk.dotnet exec ConsoleApp32.dll
Unhandled exception. System.Net.WebException: The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at ConsoleApp32.Program.Main(String[] args) in C:\Projects\trunk\ConsoleApp32\ConsoleApp32\Program.cs:line 12
Aborted (core dumped)
```

You can also try openssl s_client -connect www.github.com:443 -status
```
$ openssl s_client -connect www.github.com:443 -status
CONNECTED(00000003)
OCSP response: no response sent
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 Extended Validation Server CA
verify return:1
depth=0 businessCategory = Private Organization, jurisdictionC = US, jurisdictionST = Delaware, serialNumber = 5157550, C = US, ST = California, L = San Francisco, O = "GitHub, Inc.", CN = github.com
verify return:1
---
Certificate chain
 0 s:/businessCategory=Private Organization/jurisdictionC=US/jurisdictionST=Delaware/serialNumber=5157550/C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=github.com
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA
 1 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIHQjCCBiqgAwIBAgIQCgYwQn9bvO1pVzllk7ZFHzANBgkqhkiG9w0BAQsFADB1
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMTQwMgYDVQQDEytEaWdpQ2VydCBTSEEyIEV4dGVuZGVk
IFZhbGlkYXRpb24gU2VydmVyIENBMB4XDTE4MDUwODAwMDAwMFoXDTIwMDYwMzEy
MDAwMFowgccxHTAbBgNVBA8MFFByaXZhdGUgT3JnYW5pemF0aW9uMRMwEQYLKwYB
BAGCNzwCAQMTAlVTMRkwFwYLKwYBBAGCNzwCAQITCERlbGF3YXJlMRAwDgYDVQQF
Ewc1MTU3NTUwMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQG
A1UEBxMNU2FuIEZyYW5jaXNjbzEVMBMGA1UEChMMR2l0SHViLCBJbmMuMRMwEQYD
VQQDEwpnaXRodWIuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
xjyq8jyXDDrBTyitcnB90865tWBzpHSbindG/XqYQkzFMBlXmqkzC+FdTRBYyneZ
w5Pz+XWQvL+74JW6LsWNc2EF0xCEqLOJuC9zjPAqbr7uroNLghGxYf13YdqbG5oj
/4x+ogEG3dF/U5YIwVr658DKyESMV6eoYV9mDVfTuJastkqcwero+5ZAKfYVMLUE
sMwFtoTDJFmVf6JlkOWwsxp1WcQ/MRQK1cyqOoUFUgYylgdh3yeCDPeF22Ax8AlQ
xbcaI+GwfQL1FB7Jy+h+KjME9lE/UpgV6Qt2R1xNSmvFCBWu+NFX6epwFP/JRbkM
fLz0beYFUvmMgLtwVpEPSwIDAQABo4IDeTCCA3UwHwYDVR0jBBgwFoAUPdNQpdag
re7zSmAKZdMh1Pj41g8wHQYDVR0OBBYEFMnCU2FmnV+rJfQmzQ84mqhJ6kipMCUG
A1UdEQQeMByCCmdpdGh1Yi5jb22CDnd3dy5naXRodWIuY29tMA4GA1UdDwEB/wQE
AwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwdQYDVR0fBG4wbDA0
oDKgMIYuaHR0cDovL2NybDMuZGlnaWNlcnQuY29tL3NoYTItZXYtc2VydmVyLWcy
LmNybDA0oDKgMIYuaHR0cDovL2NybDQuZGlnaWNlcnQuY29tL3NoYTItZXYtc2Vy
dmVyLWcyLmNybDBLBgNVHSAERDBCMDcGCWCGSAGG/WwCATAqMCgGCCsGAQUFBwIB
FhxodHRwczovL3d3dy5kaWdpY2VydC5jb20vQ1BTMAcGBWeBDAEBMIGIBggrBgEF
BQcBAQR8MHowJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBS
BggrBgEFBQcwAoZGaHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0
U0hBMkV4dGVuZGVkVmFsaWRhdGlvblNlcnZlckNBLmNydDAMBgNVHRMBAf8EAjAA
MIIBfgYKKwYBBAHWeQIEAgSCAW4EggFqAWgAdgCkuQmQtBhYFIe7E6LMZ3AKPDWY
BPkb37jjd80OyA3cEAAAAWNBYm0KAAAEAwBHMEUCIQDRZp38cTWsWH2GdBpe/uPT
Wnsu/m4BEC2+dIcvSykZYgIgCP5gGv6yzaazxBK2NwGdmmyuEFNSg2pARbMJlUFg
U5UAdgBWFAaaL9fC7NP14b1Esj7HRna5vJkRXMDvlJhV1onQ3QAAAWNBYm0tAAAE
AwBHMEUCIQCi7omUvYLm0b2LobtEeRAYnlIo7n6JxbYdrtYdmPUWJQIgVgw1AZ51
vK9ENinBg22FPxb82TvNDO05T17hxXRC2IYAdgC72d+8H4pxtZOUI5eqkntHOFeV
CqtS6BqQlmQ2jh7RhQAAAWNBYm3fAAAEAwBHMEUCIQChzdTKUU2N+XcqcK0OJYrN
8EYynloVxho4yPk6Dq3EPgIgdNH5u8rC3UcslQV4B9o0a0w204omDREGKTVuEpxG
eOQwDQYJKoZIhvcNAQELBQADggEBAHAPWpanWOW/ip2oJ5grAH8mqQfaunuCVE+v
ac+88lkDK/LVdFgl2B6kIHZiYClzKtfczG93hWvKbST4NRNHP9LiaQqdNC17e5vN
HnXVUGw+yxyjMLGqkgepOnZ2Rb14kcTOGp4i5AuJuuaMwXmCo7jUwPwfLe1NUlVB
Kqg6LK0Hcq4K0sZnxE8HFxiZ92WpV2AVWjRMEc/2z2shNoDvxvFUYyY1Oe67xINk
myQKc+ygSBZzyLnXSFVWmHr3u5dcaaQGGAR42v6Ydr4iL38Hd4dOiBma+FXsXBIq
WUjbST4VXmdaol7uzFMojA4zkxQDZAvF5XgJlAFadfySna/teik=
-----END CERTIFICATE-----
subject=/businessCategory=Private Organization/jurisdictionC=US/jurisdictionST=Delaware/serialNumber=5157550/C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=github.com
issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA
---
No client certificate CA names sent
Peer signing digest: SHA256
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 3582 bytes and written 424 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 11EBAA6396D42CAF1808DA308CD9EB8C5E49B95FFFAC8383DE1AA6F875F15B67
    Session-ID-ctx: 
    Master-Key: F6DB33F509F32A889711C874362EB7E3FE715405CB01BF9F4C6582C52CFBF08D875DA8CD2C45EA1F85134E7605AA5A75
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1572294344
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
closed
```

**Comment by wfurt** [comment]
cc also @bartonjs in case this rings a bell.

**Comment by bartonjs** [comment]
Nope, doesn't ring a bell.  Best guess is that the snap one is binding to a different libssl than the yum one is, and they have different trust root locations configured.

You could try something like

```
$ LD_DEBUG=libs dotnet exec ConsoleAll32.dll 2>&1 | grep init.*libcrypto
```

As an example:
```
$ LD_DEBUG=libs dotnet msbuild /t:BuildAndTest 2>&1 | grep init.*libcrypto
     16622:     calling init: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
     16640:     calling init: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
       16674:   calling init: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
```

**Comment by davidsh** [comment]
What happens if you use 'curl'?  I.e. `curl https;/www.github.com`

**Comment by abelykh0** [comment]
The `snap` (not working) dotnet:
```
$ LD_DEBUG=libs dotnet-sdk.dotnet exec ConsoleApp32.dll 2>&1 | grep init.*libcrypto
      4507:	calling init: /var/lib/snapd/snap/dotnet-sdk/49/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
```

The `yum` (working) dotnet:
```
$ LD_DEBUG=libs dotnet exec ConsoleApp32.dll 2>&1 | grep init.*libcrypto
      4433:	calling init: /lib64/libcrypto.so.10
```

**Comment by abelykh0** [comment]
> What happens if you use 'curl'?

```
$ curl https://www.github.com
curl: (77) error setting certificate verify locations:
  CAfile: /opt/rh/rh-dotnet30/root/etc/pki/tls/certs/ca-bundle.crt
  CApath: none
```

**Comment by abelykh0** [comment]
By the way, if you have a workaround, I would appreciate it.

**Comment by davidsh** [comment]
>$ curl https://www.github.com
curl: (77) error setting certificate verify locations:
  CAfile: /opt/rh/rh-dotnet30/root/etc/pki/tls/certs/ca-bundle.crt
  CApath: none

Since 'curl' isn't working, this clearly points out to a problem with the operating system and the pki configuration.

**Comment by wfurt** [comment]
I think one of the openssl versions may have different expectation for location of trusted certs. 
You can try to set SSL_CERT_DIR or SSL_CERT_FILE to point at system one rather than  /opt/rh/...

**Comment by abelykh0** [comment]
I guess RHEL is "special" because there's a yum package called `rh-dotnet30-lubcurl`. There's no similar package for Ubuntu 18.

Files in this package: 
```
/opt/rh/rh-dotnet30/root/usr/lib64/libcurl.so.4
/opt/rh/rh-dotnet30/root/usr/lib64/libcurl.so.4.5.0
/opt/rh/rh-dotnet30/root/usr/share/licenses/rh-dotnet30-libcurl-7.61.0/COPYING
```

**Comment by bartonjs** [comment]
```
$ openssl version -d
OPENSSLDIR: "/usr/lib/ssl"
```

Take your version of that, then try

```
export SSL_CERT_DIR=/path/from/above/certs/
export SSL_CERT_FILE=/path/from/above/cert.pem
dotnet-sdk.dotnet exec ConsoleApp32.dll
```

Alternatively, assuming the snap version is built portable you can try to get it to bind to libcrypto.so.10 and libssl.so.10 as the first binding attempt:

```
CLR_OPENSSL_VERSION_OVERRIDE=10 dotnet-sdk.dotnet exec ConsoleApp32.dll
```

**Comment by abelykh0** [comment]
OK, this workaround works:
```
$ export CLR_OPENSSL_VERSION_OVERRIDE=10 
$ dotnet-sdk.dotnet exec ConsoleApp32.dll
```

Do you know how long it will take you to fix the issue?

**Comment by bartonjs** [comment]
> Do you know how long it will take you to fix the issue?

As far as I know, the expectation on RHEL is to use the package from yum, which is build specifically for RHEL.

I assume that the snap package has OpenSSL as a dependency, which means snap pulls in some sort of "system generic" OpenSSL... and the problem is that "system generic" OpenSSL isn't working nicely on RHEL (in particular, doesn't share a source of trust data).  But, I don't really know anything about snap.  @leecow, this one seems to be for you.

**Comment by abelykh0** [comment]
> If you're running the dotnet snap, without enabling the scl, how does it behave?

It behaves the same whether scl is enabled or not (gives exception as described).

**Comment by tmds** [comment]
I guess you were running curl in the scl here https://github.com/dotnet/corefx/issues/42178#issuecomment-547220990?

It's interesting this works:

> CLR_OPENSSL_VERSION_OVERRIDE=10 dotnet-sdk.dotnet exec ConsoleApp32.dll

What versions of OpenSSL are installed on your RHEL7?

How does this behave if you use the `dotnet` from https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-linux-x64-binaries?

**Comment by leecow** [comment]
Curl will be whatever is provided by the 'host' OS (RHEL in this case) and the SDK running from the Snap will execute entirely within the context of Ubuntu Core 18 so I would expect this to repro regardless of which Distro is in use. I wonder if there needs to be a "port" opened out of the Snap sandbox? Will need to poke around and experiment.

**Comment by abelykh0** [comment]
> 
> 
> Curl will be whatever is provided by the 'host' OS (RHEL in this case) and the SDK running from the Snap will execute entirely within the context of Ubuntu Core 18 so I would expect this to repro regardless of which Distro is in use. I wonder if there needs to be a "port" opened out of the Snap sandbox? Will need to poke around and experiment.

Ubuntu 18 works fine, only RHEL has this issue,.

**Comment by abelykh0** [comment]
> 
> I guess you were running curl in the scl here [#42178 (comment)](https://github.com/dotnet/corefx/issues/42178#issuecomment-547220990)?

Yes. If not running in the scl, it outputs nothing (I guess it is working)

> 
> It's interesting this works:
> 
> > CLR_OPENSSL_VERSION_OVERRIDE=10 dotnet-sdk.dotnet exec ConsoleApp32.dll
> 
> What versions of OpenSSL are installed on your RHEL7?

1.0.2k-19.el7 (x86_64) from rhel-7-server-rpms

> 
> How does this behave if you use the `dotnet` from https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-linux-x64-binaries?

How to install it?

**Comment by abelykh0** [comment]
The default installation of RHEL 7 does that. I suppose it should be easy to replicate on your end.

**Comment by tmds** [comment]
> $ curl https://www.github.com
curl: (77) error setting certificate verify locations:
  CAfile: /opt/rh/rh-dotnet30/root/etc/pki/tls/certs/ca-bundle.crt
  CApath: none

This is an issue with curl that ships as part of `rh-dotnet30-libcurl`. See https://bugzilla.redhat.com/show_bug.cgi?id=1768029.

It's unrelated to the _snap dotnet_ issue, since that reproduces outside the scl.

cc @omajid

**Comment by tmds** [comment]
> $ export CLR_OPENSSL_VERSION_OVERRIDE=10 
$ dotnet-sdk.dotnet exec ConsoleApp32.dll

If this works, then probably the _snap dotnet_ is trying to use OpenSSL 1.1, which isn't available on RHEL7.
I'm not sure if the snap flavor is supposed to pack it's own version of OpenSSL...

> How does this behave if you use the dotnet from https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-linux-x64-binaries?
How to install it?

You can just untar this. The Microsoft binaries will dynamically detect the OpenSSL version present on the system.

> As far as I know, the expectation on RHEL is to use the package from yum, which is build specifically for RHEL.

This is the recommended way to run dotnet on RHEL.

**Comment by wfurt** [comment]
Is there anything left on this issue @abelykh0 @tmds? 
It seems like this is understood.

**Comment by abelykh0** [comment]
From my perspective, it is still an issue. Thank you for the workaround (`CLR_OPENSSL_VERSION_OVERRIDE=10`), we will use it in our installer.

**Comment by tmds** [comment]
@wfurt _snap dotnet_ seems to have an issue with OpenSSL on RHEL7, I haven't looked into it further.
RHEL packages are working. @abelykh0 did you try the Microsoft tar.gz binaries?

**Comment by abelykh0** [comment]
@abelykh0 did you try the Microsoft tar.gz binaries? No, I have a workaround now.

**Comment by wfurt** [comment]
I don't know much about snap @tmds. Why would that be any different?  
We should try to load version of OpenSSL matching version curl was linked with. 
If that is not applicable, we would load from newer to older versions. 
I'm wondering if in this case there is some leak from main OS about locations.

**Comment by tmds** [comment]
> I don't know much about snap @tmds. Why would that be any different?

Me neither.

@abelykh0 for my education, why/how are you using snap?
And, I just saw [SSL Certificate resolution with Snap installs](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md#ssl-certificate-resolution-with-snap-installs). Did you try this?

**Comment by abelykh0** [comment]
> @abelykh0 for my education, why/how are you using snap?
> And, I just saw [SSL Certificate resolution with Snap installs](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md#ssl-certificate-resolution-with-snap-installs). Did you try this?
I can try it, please update the document to say what should be used for RHEL 7.

**Comment by karelz** [comment]
@tmds what is the next step? Can we update some documentation or something?

Triage: This is not SslStream specific, it will be more in loader of OpenSsl

**Comment by wfurt** [comment]
Is there anything we should do @tmds besides verifying 3.1? Should this be a documentation issue?
