### ISSUE TITLE
Fatal, internal CLR error getting network interfaces

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#42201]
I have seen this a couple of times on my machine running dotnet/toolset tests against 5.0 runtime. I don't have a good repro or a dump yet. Posting early in case someone recognizes this and saves me the time of chasing further.

```
Fatal error. Internal CLR error. (0x80131506)
   at System.StubHelpers.MngdFixedArrayMarshaler.ConvertContentsToManaged(IntPtr, System.Object ByRef, IntPtr)
   at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr, System.Object, Boolean)
   at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr, System.Type)
   at System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr, System.Type)
   at System.Runtime.InteropServices.Marshal.PtrToStructure[[Interop+IpHlpApi+IpAdapterAddresses, System.Net.NetworkInformation, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](IntPtr)
   at System.Net.NetworkInformation.SystemNetworkInterface.GetNetworkInterfaces()
   at System.Net.NetworkInformation.SystemNetworkInterface.InternalGetIsNetworkAvailable()
   ```

**Comment by nguerrera** [comment]
This is on Windows.

**Comment by danmosemsft** [comment]
@AaronRobinsonMSFT  in case he has thoughts

**Comment by AaronRobinsonMSFT** [comment]
Boo. This is similar to both https://github.com/dotnet/coreclr/issues/27491 and https://github.com/dotnet/coreclr/issues/27496. It is probably related to https://github.com/dotnet/coreclr/pull/26340.

/cc @jkoritzinsky

**Comment by jkoritzinsky** [comment]
Yeah this is due to dotnet/coreclr#26340. When I fix the test failures, this will likely be fixed in the process.
