### ISSUE TITLE
CertificateValidationRemoteServer_EndToEnd_Ok test failing on all PRs on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#42231]
cc: @wfurt, @davidsh

**Comment by davidsh** [comment]
Can you post a link of one of the failures? What is the error message?

**Comment by stephentoub** [comment]
The last 7 PRs in the repo:
![image](https://user-images.githubusercontent.com/2642209/67889169-b83e5d00-fb24-11e9-8b15-51c1fc9a9d4a.png)
e.g.
https://dev.azure.com/dnceng/public/_build/results?buildId=407674&view=ms.vss-test-web.build-test-results-tab&runId=12743580&resultId=178362&paneView=debug
```
Error message
System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..\r\n---- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.

Stack trace
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1111
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token) in /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1077
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request) in /_/src/System.Net.Security/src/System/Net/FixedSizeReader.cs:line 57
   at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|141_0(ExceptionDispatchInfo e) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 843
   at System.Net.Security.SslStream.ThrowIfExceptional() in /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 829
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 438
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 408
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 241
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__63_1(IAsyncResult iar) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 381
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/FutureFactory.cs:line 513
--- End of stack trace from previous location ---
   at System.Net.Security.Tests.CertificateValidationRemoteServer.CertificateValidationRemoteServer_EndToEnd_Ok() in /_/src/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 27
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
```

**Comment by davidsh** [comment]
This is the test:
https://github.com/dotnet/corefx/blob/62e6ccfa09322db02d6c043226bd382debc915c4/src/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs#L16-L38

**Comment by davidsh** [comment]
The server uses the remote Azure endpoint:

https://corefx-net-http11.azurewebsites.net

The endpoint is working fine when using the browser.

**Comment by davidsh** [comment]
Can you reproduce the failures locally on your dev machine when running the System.Net.Security tests?

**Comment by stephentoub** [comment]
No.  It's possible it was transient and has already resolved itself.  Or maybe there's some kind of networking issue between the CI machines and the endpoint.

**Comment by davidsh** [comment]
Curiously, this particular test is not marked 'Outerloop' even though it connects with an external server in Azure. I think the test should be changed to Outerloop. We can also consider that this test is not needed considering everything else we already test for TLS. If so, we can delete this test.

**Comment by wfurt** [comment]
Could be also IPv4 vs IPv6 preference. But I would expect other tests using same EndPoint also failing... The "forcibly" suggest we get RST from the server or firewall/load-balancer in-between.

**Comment by carlossanlop** [comment]
In case it's helpful, my 3.1 Port CI seems to be hitting these same networking failures:
https://github.com/dotnet/corefx/issues/42231

My failure logs, in case they are helpful:
Windows x64: https://helix.dot.net/api/2019-06-17/jobs/b8e03ca9-f491-48bf-a040-92ed8532b4af/workitems/System.Net.Security.Tests/console
Windows x86: https://helix.dot.net/api/2019-06-17/jobs/430162ce-2954-49bd-af88-b506ed01618e/workitems/System.Net.Security.Tests/console

**Comment by ericstj** [comment]
Seeing this in my release/3.1 PR too.
https://dev.azure.com/dnceng/public/_build/results?buildId=407986&view=ms.vss-test-web.build-test-results-tab&runId=12754528&resultId=157383&paneView=debug

Can a change be fast-tracked to disable this test while things are investigated?

**Comment by davidsh** [comment]
@wfurt Can you submit a PR to master (and probably release/3.1) to disable the test to help unblock folks?

**Comment by ericstj** [comment]
Still failing in release/3.1.  Were you going to port your fix there?

**Comment by davidsh** [comment]
@ericstj 

>Still failing in release/3.1. Were you going to port your fix there?

@wfurt just submitted PR #42273 against release/3.1 branch

**Comment by Anipik** [comment]
We should either port the fix to 3.0 or should disable the test. The test is failing on official builds as wells as on prs.

**Comment by davidsh** [comment]
>We should either port the fix to 3.0 or should disable the test. The test is failing on official builds as wells as on prs.

There was no real fix.  The change made to release/3.1 was to move the test from Innerloop to Outerloop.

If this is blocking things in release/3.0, then the test should just be disabled in that branch.

**Comment by Anipik** [comment]
okay I will disable the test

**Comment by karelz** [comment]
@Anipik did you disable the test? Is there PR to be linked? Should we mark the issue as "test-disabled"?

**Comment by karelz** [comment]
Triage: It was failure in release/3.0 and 3.1 branches, we should check it out.
