### ISSUE TITLE
Message_ShouldFormatCountOfRootCausesUsingTheCurrentCulture failed on UAP

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#42246]
```
Unhandled exception. Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 96
   at Xunit.Assert.True(Boolean condition) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 63
   at System.ComponentModel.Composition.CompositionExceptionTests.AssertMessage(CompositionException exception, Int32 rootCauseCount, CultureInfo culture) in /_/src/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/CompositionExceptionTests.cs:line 420
   at System.ComponentModel.Composition.CompositionExceptionTests.<Message_ShouldFormatCountOfRootCausesUsingTheCurrentCulture>b__31_0() in /_/src/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/CompositionExceptionTests.cs:line 383
--- End of stack trace from previous location where exception was thrown ---
   at Xunit.ConsoleClient.RemoteExecutor.Execute(String[] args)
   at Xunit.ConsoleClient.ConsoleRunner.EntryPoint(String[] args)
   at Xunit.ConsoleClient.Program.Main(String[] args)
    System.ComponentModel.Composition.CompositionExceptionTests.Message_ShouldFormatCountOfRootCausesUsingTheCurrentCulture [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.TrueException: Assert.True() Failure
        Expected: True
        Actual:   False
        /_/src/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/CompositionExceptionTests.cs(420,0): at System.ComponentModel.Composition.CompositionExceptionTests.AssertMessage(CompositionException exception, Int32 rootCauseCount, CultureInfo culture)
        /_/src/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/CompositionExceptionTests.cs(383,0): at System.ComponentModel.Composition.CompositionExceptionTests.<Message_ShouldFormatCountOfRootCausesUsingTheCurrentCulture>b__31_0()
        
        Child process:
          System.ComponentModel.Composition.Tests, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.ComponentModel.Composition.CompositionExceptionTests Int32 <Message_ShouldFormatCountOfRootCausesUsingTheCurrentCulture>b__31_0()
        ```

**Comment by danmosemsft** [comment]
We're not running UAP test configuration anymore (this was in release/3.1) but we should log the line.
