### ISSUE TITLE
Test failed: System.Threading.Tests.ThreadingAclExtensionsTests.EventWaitHandle_Create_InvalidMode

### ISSUE THREAD

**Issue by VincentBu** [dotnet/corefx#42285]
**Job:**
[corefx-ci #20191031.66](https://dnceng.visualstudio.com/public/_build/results?buildId=410818)

**Detail:**
https://helix.dot.net/api/2019-06-17/jobs/0ae3a0ed-ee54-473f-928f-d57f7a804b47/workitems/System.Threading.AccessControl.Tests/console

**configuration:**
all Windows configurations

**Failed tests:**
System.Threading.Tests.ThreadingAclExtensionsTests.EventWaitHandle_Create_InvalidMode

**Log:**
```
System.Threading.Tests.ThreadingAclExtensionsTests.EventWaitHandle_Create_InvalidMode(mode: -2147483648) [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.ArgumentOutOfRangeException)
      Actual:   (No exception was thrown)
      Stack Trace:
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/AssertExtensions.cs(63,0): at System.AssertExtensions.Throws[T](String expectedParamName, Action action)
        /_/src/System.Threading.AccessControl/tests/ThreadingAclExtensionsTests.cs(100,0): at System.Threading.Tests.ThreadingAclExtensionsTests.EventWaitHandle_Create_InvalidMode(EventResetMode mode)
    System.Threading.Tests.ThreadingAclExtensionsTests.EventWaitHandle_Create_InvalidMode(mode: -1) [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.ArgumentOutOfRangeException)
      Actual:   (No exception was thrown)
      Stack Trace:
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/AssertExtensions.cs(63,0): at System.AssertExtensions.Throws[T](String expectedParamName, Action action)
        /_/src/System.Threading.AccessControl/tests/ThreadingAclExtensionsTests.cs(100,0): at System.Threading.Tests.ThreadingAclExtensionsTests.EventWaitHandle_Create_InvalidMode(EventResetMode mode)
    System.Threading.Tests.ThreadingAclExtensionsTests.EventWaitHandle_Create_InvalidMode(mode: 2) [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.ArgumentOutOfRangeException)
      Actual:   (No exception was thrown)
      Stack Trace:
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/AssertExtensions.cs(63,0): at System.AssertExtensions.Throws[T](String expectedParamName, Action action)
        /_/src/System.Threading.AccessControl/tests/ThreadingAclExtensionsTests.cs(100,0): at System.Threading.Tests.ThreadingAclExtensionsTests.EventWaitHandle_Create_InvalidMode(EventResetMode mode)
    System.Threading.Tests.ThreadingAclExtensionsTests.EventWaitHandle_Create_InvalidMode(mode: 2147483647) [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.ArgumentOutOfRangeException)
      Actual:   (No exception was thrown)
      Stack Trace:
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/AssertExtensions.cs(63,0): at System.AssertExtensions.Throws[T](String expectedParamName, Action action)
        /_/src/System.Threading.AccessControl/tests/ThreadingAclExtensionsTests.cs(100,0): at System.Threading.Tests.ThreadingAclExtensionsTests.EventWaitHandle_Create_InvalidMode(EventResetMode mode)
    System.Threading.Tests.ThreadingAclExtensionsTests.EventWaitHandle_Create_SpecificParameters(initialState: True, mode: AutoReset, accessControl: Deny, rights: FullControl) [FAIL]
      System.UnauthorizedAccessException : Access to the path '18672432e16f4ebcbbf9309ed5be2dc4' is denied.
      Stack Trace:
        /_/src/System.Private.CoreLib/shared/System/Threading/EventWaitHandle.Windows.cs(69,0): at System.Threading.EventWaitHandle.OpenExistingWorker(String name, EventWaitHandle& result)
        /_/src/System.Private.CoreLib/shared/System/Threading/EventWaitHandle.cs(34,0): at System.Threading.EventWaitHandle.OpenExisting(String name)
        /_/src/System.Threading.AccessControl/src/System/Threading/EventWaitHandleAcl.cs(66,0): at System.Threading.EventWaitHandleAcl.Create(Boolean initialState, EventResetMode mode, String name, Boolean& createdNew, EventWaitHandleSecurity eventSecurity)
        /_/src/System.Threading.AccessControl/tests/ThreadingAclExtensionsTests.cs(166,0): at System.Threading.Tests.ThreadingAclExtensionsTests.CreateAndVerifyEventWaitHandle(Boolean initialState, EventResetMode mode, EventWaitHandleSecurity expectedSecurity)
        /_/src/System.Threading.AccessControl/tests/ThreadingAclExtensionsTests.cs(124,0): at System.Threading.Tests.ThreadingAclExtensionsTests.EventWaitHandle_Create_SpecificParameters(Boolean initialState, EventResetMode mode, AccessControlType accessControl, EventWaitHandleRights rights)
    System.Threading.Tests.ThreadingAclExtensionsTests.EventWaitHandle_Create_SpecificParameters(initialState: True, mode: ManualReset, accessControl: Deny, rights: FullControl) [FAIL]
      System.UnauthorizedAccessException : Access to the path '55bca2e7b82246bd826b2c523b8097aa' is denied.
      Stack Trace:
        /_/src/System.Private.CoreLib/shared/System/Threading/EventWaitHandle.Windows.cs(69,0): at System.Threading.EventWaitHandle.OpenExistingWorker(String name, EventWaitHandle& result)
        /_/src/System.Private.CoreLib/shared/System/Threading/EventWaitHandle.cs(34,0): at System.Threading.EventWaitHandle.OpenExisting(String name)
        /_/src/System.Threading.AccessControl/src/System/Threading/EventWaitHandleAcl.cs(66,0): at System.Threading.EventWaitHandleAcl.Create(Boolean initialState, EventResetMode mode, String name, Boolean& createdNew, EventWaitHandleSecurity eventSecurity)
        /_/src/System.Threading.AccessControl/tests/ThreadingAclExtensionsTests.cs(166,0): at System.Threading.Tests.ThreadingAclExtensionsTests.CreateAndVerifyEventWaitHandle(Boolean initialState, EventResetMode mode, EventWaitHandleSecurity expectedSecurity)
        /_/src/System.Threading.AccessControl/tests/ThreadingAclExtensionsTests.cs(124,0): at System.Threading.Tests.ThreadingAclExtensionsTests.EventWaitHandle_Create_SpecificParameters(Boolean initialState, EventResetMode mode, AccessControlType accessControl, EventWaitHandleRights rights)
  Finished:    System.Threading.AccessControl.Tests
=== TEST EXECUTION SUMMARY ===
   System.Threading.AccessControl.Tests  Total: 15, Errors: 0, Failed: 6, Skipped: 0, Time: 0.402s
----- end Fri 11/01/2019  1:58:28.33 ----- exit code 1
```

**Comment by danmosemsft** [comment]
@carlossanlop

**Comment by danmosemsft** [comment]
@VincentBu can you please always include the configuration in issues like this that you open. For example "netcoreapp-Windows_NT-Debug-x64-(Windows.Nano.1809.Amd64.Open" or similar. It might be several, in this case you might say "all Windows configurations" eg

**Comment by carlossanlop** [comment]
@danmosemsft @VincentBu this test has not been merged yet, is part of a PR actively being reviewed, so I don't understand, wht was an issue opened against it?

**Comment by danmosemsft** [comment]
lol...I didn't notice that! Good question.

**Comment by VincentBu** [comment]
sorry, I am not sure if failed tests triggered by PR should be watched. Should i close it?

**Comment by danmosemsft** [comment]
@VincentBu please ignore tests triggered by CI.
