### ISSUE TITLE
Some networking tests failing in Outerloop on Windows 7

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#42339]
A few SslStream and WebSocket tests are always failing on Windows 7 with the same SocketException due to a likely RST being sent/received with the remote server.

>System.Net.Security.Tests.CertificateValidationRemoteServer.CertificateValidationRemoteServer_EndToEnd_Ok [FAIL]
      System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
      ---- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
      Stack Trace:
        /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(1111,0): at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
        /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(1077,0): at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
        /_/src/System.Net.Security/src/System/Net/FixedSizeReader.cs(57,0): at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(843,0): at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|141_0(ExceptionDispatchInfo e)

>System.Net.WebSockets.Tests.WebSocketTests.WebSocketProtocol_CreateFromConnectedStream_CloseAsyncClosesStream(echoUri: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx, explicitCloseAsync: False) [FAIL]
      System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
      ---- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
      Stack Trace:
        /_/src/System.Net.Security/src/System/Net/FixedSizeReader.cs(57,0): at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(843,0): at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|141_0(ExceptionDispatchInfo e)

>System.Net.WebSockets.Tests.WebSocketProtocolCreateTests.WebSocketProtocol_CreateFromConnectedStream_CloseAsyncClosesStream(echoUri: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx, explicitCloseAsync: False) [FAIL]
      System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
      ---- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
      Stack Trace:
        /_/src/System.Net.Security/src/System/Net/FixedSizeReader.cs(57,0): at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(843,0): at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|141_0(ExceptionDispatchInfo e)

**Comment by davidsh** [comment]
HttpListener test also failed on latest Windows 7 run with a crash dump

>Starting:    System.Net.HttpListener.Tests (parallel test collections = on, max threads = 2)
----- end Sun 11/03/2019 17:58:22.21 ----- exit code -1073740940 ----------------------------------------------------------
 Sun 11/03/2019-17:58:22.21
 Sun 11/03/2019-17:58:22.49
2019-11-03 17:58:22,840: INFO: 1776: run(82): main: Main thread starting 10 workers
Worker 0: starting...
Worker 1: starting...
Worker 2: starting...
Worker 3: starting...
Worker 4: starting...
Worker 5: starting...
Worker 6: starting...
Worker 7: starting...
Worker 8: starting...
Worker 9: starting...
2019-11-03 17:58:22,840: INFO: 1776: run(89): main: Beginning reading of test results.
2019-11-03 17:58:22,840: INFO: 1776: run(95): main: Uploading results in batches of size 1000
2019-11-03 17:58:22,840: INFO: 1776: run(100): main: Main thread finished queueing batches
2019-11-03 17:58:22,840: INFO: 1776: run(104): main: Main thread exiting
Searching 'C:\dotnetbuild\work\f47f5ab7-5164-4836-b7a5-c27e024c12fd\Work\60dd26bb-f0ed-4f7e-b84d-390652168886\Exec\..' for log files
Found log 'C:\dotnetbuild\work\f47f5ab7-5164-4836-b7a5-c27e024c12fd\Work\60dd26bb-f0ed-4f7e-b84d-390652168886\Exec\..\console.6b8961c1.log'
Uri 'https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-corefx-refs-pull-42322-merge-f47f5ab751644836b7/System.Net.HttpListener.Tests/console.6b8961c1.log?sv=2018-03-28&sr=c&sig=Yxz31a%2FRi0CnmIhMz1m6MBS3bzzi0UMfBBQq7jhtG7Y%3D&se=2019-11-13T17%3A45%3A24Z&sp=rl'

**Comment by karelz** [comment]
Win7 extended support ends on 2020/1/14 (in a week).
@jkotas Tomas mentioned you made some PRs that make Win7 officially unsupported in .NET 5. Do you have a link?

If that is true, we should just kick out Win7 test runs from CI.

**Comment by jkotas** [comment]
> @jkotas Tomas mentioned you made some PRs that make Win7 officially unsupported in .NET 5. Do you have a link?

That is not correct. I did not made any such PRs. As far as I know, the decision for Win7 & .NET5 was not made yet.

You may be confusing this with RedHat 6. We have dropped RedHat 6 for .NET 5. This decision was discussed with PMs and it was pretty non-controversial.

**Comment by karelz** [comment]
Thanks for clarification @jkotas!
