### ISSUE TITLE
OverflowException in ActivityTracker.ActivityInfo.AddIdToGuid 

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/corefx#42352]
I got an OverflowException from the `Microsoft.Diagnostics.Tracing.ActivityTracker.ActivityInfo.AddIdToGuid(Guid* outPtr, int whereToAddId, uint id, bool overflow)` method in the [Microsoft.Diagnostics.Tracing.EventSource.Redist 2.1.0 NuGet package](https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.EventSource.Redist/2.1.0), in a program targeting .NET Framework 4.6.1 and running on .NET Framework 4.8. That NuGet package includes version.txt with the text "4ac4c0367003fe3973a3648eb0715ddb0e3bbcea", which appears to refer to commit 4ac4c0367003fe3973a3648eb0715ddb0e3bbcea in the dotnet/corefx repository.

I am not sure where in the method the exception was thrown, but the IL code of the method includes:

```
  IL_00d6:  ldc.i4     0x599d99ad
  IL_00db:  add.ovf.un
````

and the same constant is in the source code here: <https://github.com/dotnet/corefx/blob/4ac4c0367003fe3973a3648eb0715ddb0e3bbcea/src/Common/src/CoreLib/System/Diagnostics/Tracing/ActivityTracker.cs#L523-L527>

The `add.ovf.un` opcode indicates the NuGet package was built with overflow checking enabled. Perhaps there should be `unchecked(…)` around the checksum expression.

**Comment by KalleOlaviNiemitalo** [comment]
To reproduce:

1. Expand [EventSourceRepro.zip](https://github.com/dotnet/corefx/files/3803852/EventSourceRepro.zip).
2. Build the repro program.
3. Start PerfView collecting from providers `*DemoEventSource,*Microsoft.Tasks.Nuget`.
4. Run the repro program in the Visual Studio debugger.
5. It throws System.OverflowException when `i == 165`.

```
Microsoft.Diagnostics.Tracing.EventSourceException: An error occurred when writing to a listener. ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at Microsoft.Diagnostics.Tracing.ActivityTracker.ActivityInfo.AddIdToGuid(Guid* outPtr, Int32 whereToAddId, UInt32 id, Boolean overflow)
   at Microsoft.Diagnostics.Tracing.ActivityTracker.ActivityInfo.CreateActivityPathGuid(Guid& idRet, Int32& activityPathGuidOffset)
   at Microsoft.Diagnostics.Tracing.ActivityTracker.OnStart(String providerName, String activityName, Int32 task, Guid& activityId, Guid& relatedActivityId, EventActivityOptions options)
   at Microsoft.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(Int32 eventId, Guid* relatedActivityId, Int32 eventDataCount, EventData* data)
   --- End of inner exception stack trace ---
   at Microsoft.Diagnostics.Tracing.EventSource.ThrowEventSourceException(String eventName, Exception innerEx)
   at Microsoft.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(Int32 eventId, Guid* relatedActivityId, Int32 eventDataCount, EventData* data)
   at EventSourceRepro.Program.Main(String[] args) in REDACTED\EventSourceRepro\Program.cs:line 12
```

**Comment by KalleOlaviNiemitalo** [comment]
The corresponding method in "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll" of .NET Framework 4.8 does not include the overflow checks.

**Comment by KalleOlaviNiemitalo** [comment]
I guess the overflow checks were enabled for the NuGet package here: <https://github.com/dotnet/corefx/blob/4ac4c0367003fe3973a3648eb0715ddb0e3bbcea/src/Microsoft.Diagnostics.Tracing.EventSource.Redist/src/Microsoft.Diagnostics.Tracing.EventSource.Redist.csproj#L12>

They are still present in the newest preview version, microsoft.diagnostics.tracing.eventsource.redist.2.2.0-preview2.19523.17.nupkg.
