### ISSUE TITLE
DI from Program.cs no longer working

### ISSUE THREAD

**Issue by tub5** [dotnet/corefx#42368]
Since migrating to .NET Core 3.0 we are now unable to add services in `Program.cs` to be used in `Startup.cs` through dependency injection. Having followed the [official guide](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-3.0) in the section near the bottom `Extend Startup with startup filters`.

Exception message
```
System.InvalidOperationException: 'Unable to resolve service for type 'Test.Interface' while attempting to activate 'Test.Startup'.'
```

Program.cs
```csharp
private static IHostBuilder CreateWebHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    config = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory())
                        .AddJsonFile("appsettings.json").AddJsonFile("appsettings.Production.json", true)
                        .AddEnvironmentVariables();
                    config.Build();
                })
                .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); })
                .ConfigureServices(
                    services =>
                    {
                        //Add the transient so we can use this across instances through DI
                        services.AddTransient<Test.Interface, Test.Class>();
                    });
```

Startup.cs
```csharp
private Test.Interface Interface { get; }
public Startup(IConfiguration configuration,
            Test.Interface interf)
        {
            Configuration = configuration;
            Interface = interf;
        }
```

StackTrace:
```
Exception thrown: 'System.InvalidOperationException' in Microsoft.Extensions.DependencyInjection.Abstractions.dll
An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.Extensions.DependencyInjection.Abstractions.dll: 'Unable to resolve service for type 'Test.Interface' while attempting to activate 'Test.Startup'.'
Stack trace:
 >   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
 >   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
 >   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
 >   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
 >   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
 >   at Microsoft.Extensions.Hosting.HostBuilder.Build()
 >   at Test.Program.Main(String[] args) in C:\Test\Program.cs:line 17
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.IO.MemoryMappedFiles.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'Test.Interface' while attempting to activate 'Test.Startup'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Test.Program.Main(String[] args) in C:\Test\Program.cs:line 17
The program 'dotnet' has exited with code 0 (0x0).
```

**Comment by danmosemsft** [comment]
@tub5 I think this belongs in https://github.com/aspnet/extensions. Could you please close this and reopen it there?

**Comment by tub5** [comment]
Done, thanks
