### ISSUE TITLE
System.Drawing.Bitmap.LockBits not implemented on linux

### ISSUE THREAD

**Issue by hanabi1224** [dotnet/corefx#42429]
Hello, I got below exceptions running program with docker image mcr.microsoft.com/dotnet/core/aspnet:3.0 (While it works fine on windows)  Are there any alternatives?

System.NotImplementedException: Not implemented.
   at System.Drawing.Bitmap.LockBits(Rectangle rect, ImageLockMode flags, PixelFormat format, BitmapData bitmapData)
   at System.Drawing.Bitmap.LockBits(Rectangle rect, ImageLockMode flags, PixelFormat format)

```csharp
var rect = new Rectangle(x: 0, y: 0, width: width, height: height);
var destBmpData = destBmp.LockBits(rect, ImageLockMode.ReadOnly, PixelFormat.Format16bppRgb565);
```

**Comment by am11** [comment]
Similar issue: https://github.com/dotnet/corefx/issues/34160.
