### ISSUE TITLE
File.Copy no longer respects FileShare.None on Linux/Mac in 5.0

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#42455]
Found this taking a new runtime into dotnet/sdk test run environment, as one of our tests started failing on Linux/Mac.

### Program.cs
``` C#
using System;
using System.IO;

class Program
{
    static void Main()
    { 
        File.WriteAllText("x", "x");
        File.WriteAllText("y", "y");

        using (var stream = new FileStream("y", FileMode.Open, FileAccess.Read, FileShare.None))
        {
            File.Copy("x", "y", overwrite: true);
        }
        
        Console.WriteLine("Success");
    }
}
```

### Repro.csproj
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp3.0;netcoreapp5.0</TargetFrameworks>
  </PropertyGroup>
</Project>
```

### Repro steps
* dotnet run -f netcoreapp3.0
* dotnet run -f netcoreapp5.0

### Expected result
Both 3.0 and 5.0 fail with IOExceptions

### Actual result
Only 3.0 fails, 5.0 succeeds unexpectedly

#### 3.0 (fails as expected)

```/
Unhandled exception. System.IO.IOException: The process cannot access the file '/home/nicholg/src/sdk/q/y' because it is being used by another process.
   at System.IO.FileStream.Init(FileMode mode, FileShare share, String originalPath)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)      
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Program.Main()
```

#### 5.0 (succeeds unexpectedly)
```
Success
```

@stephentoub @JeremyKuhne

**Comment by filipnavara** [comment]
Maybe I broke it in #37583? Although, it sounds weird that would affect Linux.

**Comment by filipnavara** [comment]
I guess I'll need to replicate this in the System.Native code:

https://github.com/dotnet/corefx/blob/df40a0d4b44d1666971504c8e87379abe7242610/src/Common/src/CoreLib/System/IO/FileStream.Unix.cs#L73-L88

**Comment by stephentoub** [comment]
> Maybe I broke it in #37583? Although, it sounds weird that would affect Linux.

Yeah.  Because it's not creating a destination FileStream, it's skipping all of these calls to configure it:
https://github.com/dotnet/coreclr/blob/3ef9c7b2503a84d12edbb7e8c58b8e395632e98d/src/System.Private.CoreLib/shared/System/IO/FileStream.Unix.cs#L76-L123
including the `flock` call.

**Comment by filipnavara** [comment]
It's really easy to fix for the non-clonefile code path where the file descriptor is opened but the structure of the code makes it hard to insert the check for the clonefile code path (and fallback).
