### ISSUE TITLE
ADAL.NET unable to get private key from EphemeralKeySet X509Certificate2

### ISSUE THREAD

**Issue by mmaitre314** [dotnet/corefx#42523]
We are trying to use an `EphemeralKeySet` certificate with ADAL.NET and ADAL.NET is not able to access the private key. This is on .NET 4.7.2 with ADAL.NET 3.19.8.

Simplified code snippet:

```
var clientCertificate = new X509Certificate2(File.ReadAllBytes(certFilePath), "password", X509KeyStorageFlags.EphemeralKeySet);

var accessToken = await new AuthenticationContext(authority)
	.AcquireTokenAsync("https://vault.azure.net", new ClientAssertionCertificate(clientId, clientCertificate), /*sendX5c*/true);
```

Exception:

```
System.Security.Cryptography.CryptographicException: Cannot find the certificate and private key for decryption.
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Native.X509Native.AcquireCngPrivateKey(SafeCertContextHandle certificateContext)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.CryptographyHelper.GetCngPrivateKey(X509Certificate2 certificate)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.CryptographyHelper.SignWithCertificate(String message, X509Certificate2 certificate)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.ClientCreds.JsonWebToken.Sign(IClientAssertionCertificate credential, Boolean sendX5C)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.ClientCreds.ClientKey.AddToParameters(IDictionary`2 parameters)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<CheckAndAcquireTokenUsingBrokerAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__59.MoveNext()
```

ADAL.NET code for `X509Native.AcquireCngPrivateKey()`:
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/68d7dea3643e075be85abbca1ab88ba614465541/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/net45/Native/X509Native.cs#L91

**Comment by davidsh** [comment]
>We are trying to use an EphemeralKeySet certificate with ADAL.NET and ADAL.NET is not able to access the private key. This is on .NET 4.7.2 with ADAL.NET 3.19.8.

I see you're using .NET Framework 4.7.2. We don't track issues with .NET Framework in this repo. We only track .NET Core issues. You can open up a .NET Framework issue here:
https://developercommunity.visualstudio.com/spaces/61/index.html

However, the problem you are having is due to a limitation in Windows OS. Windows OS doesn't support X509KeyStorageFlags.EphemeralKeySet.  Instead you should use X509KeyStorageFlags.DefaultKeySet.  See #24454.

**Comment by bartonjs** [comment]
@mmaitre314 You should open an issue with ADAL.NET (that library isn't part of corefx).  It looks like they're directly querying for the private key from the OS, and aren't using the lookup appropriate to an EphemeralKeySet load.  (You could help them out by suggesting they ask for the CERT_NCRYPT_KEY_HANDLE_PROP_ID property from the cert before trying CERT_KEY_PROV_INFO_PROP_ID,)
