### ISSUE TITLE
SslStream_SendReceiveOverNetworkStream_AuthenticationException test fails with NullReferenceException 

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#42583]
From https://github.com/dotnet/corefx/pull/42574

System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_SendReceiveOverNetworkStream_AuthenticationException
On netcoreapp-Linux-Debug-x64-Ubuntu.1804.Amd64.Open

https://dev.azure.com/dnceng/public/_build/results?buildId=425948&view=ms.vss-test-web.build-test-results-tab&runId=13458868&resultId=162668&paneView=debug

https://helix.dot.net/api/2019-06-17/jobs/4383885f-1ecd-48f7-aa74-8594a1c88c1a/workitems/System.Net.Security.Tests/console

```text

Error message
System.NullReferenceException : Object reference not set to an instance of an object.

Stack trace
   at Microsoft.Win32.SafeHandles.SafeBioHandle.get_IsInvalid() in /_/src/Common/src/Microsoft/Win32/SafeHandles/SafeBioHandle.Unix.cs:line 45
   at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean disposeOrFinalizeOperation) in /_/src/System.Private.CoreLib/shared/System/Runtime/InteropServices/SafeHandle.cs:line 218
   at System.Runtime.InteropServices.SafeHandle.Dispose() in /_/src/System.Private.CoreLib/shared/System/Runtime/InteropServices/SafeHandle.cs:line 91
   at Microsoft.Win32.SafeHandles.SafeSslHandle.Dispose(Boolean disposing) in /_/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.Ssl.cs:line 303
   at System.Runtime.InteropServices.SafeHandle.Dispose() in /_/src/System.Private.CoreLib/shared/System/Runtime/InteropServices/SafeHandle.cs:line 91
   at System.Net.Security.SafeDeleteSslContext.Dispose(Boolean disposing) in /_/src/Common/src/System/Net/Security/Unix/SafeDeleteSslContext.cs:line 65
   at System.Runtime.InteropServices.SafeHandle.Dispose() in /_/src/System.Private.CoreLib/shared/System/Runtime/InteropServices/SafeHandle.cs:line 91
   at System.Net.Security.SecureChannel.Close() in /_/src/System.Net.Security/src/System/Net/Security/SecureChannel.cs:line 181
   at System.Net.Security.SslStream.CloseInternal() in /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 152
   at System.Net.Security.SslStream.Dispose(Boolean disposing) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 696
   at System.IO.Stream.Close() in /_/src/System.Private.CoreLib/shared/System/IO/Stream.cs:line 203
   at System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_SendReceiveOverNetworkStream_AuthenticationException() in /_/src/System.Net.Security/tests/FunctionalTests/SslStreamNetworkStreamTest.cs:line 125
--- End of stack trace from previous location ---
```

cc @davidsh, @wfurt

**Comment by wfurt** [comment]
All the evidence is gone. SslStrem went through major rewrite. As I don't see any recent failures I will close this now. If it fails again, we should open a fresh issue in https://github.com/dotnet/runtime repo.
