### ISSUE TITLE
ODBC Arithmetic overflow error Accessing AS400 DB2 (Update, Delete, Insert)

### ISSUE THREAD

**Issue by BockTim91** [dotnet/corefx#42655]
We are trying to hit our AS400 running a DB2 instance. When we run a OdbcCommand.ExecuteNonQuery() for select, everything works no issue. However, when executing a simple update, or delete command, we encounter the below error. Our current workaround is to just squish all arithmetic errors out of our execute command, which is unacceptable.

```
Arithmetic operation resulted in an overflow.
   at System.Data.Odbc.OdbcDataReader.FirstResult()
   at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader, Object[] methodArguments, SQL_API odbcApiMethod)
   at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader)
   at System.Data.Odbc.OdbcCommand.ExecuteNonQuery()
```

We are using VS 2017 with netcore 2.2

**Comment by danmosemsft** [comment]
Is it possible to attach a debugger to figure out exactly where (what line/values) this is coming from in the code?

VS should be able to resolve symbols and sources when you debug.

**Comment by BockTim91** [comment]
In enabling full debugging, it appears the issue occurs at line 1912 and 1913 of OdbcDataReader.

```C#
            cRowsAffected = GetRowCount();              // get rowcount of the current resultset (if any)
            CalculateRecordsAffected(cRowsAffected);    // update recordsaffected
```

When running a select statement cRowsAffected gets -1 as expected, however when running a delete it appears to be overloading the int causing it to crash into SR GetResourceString.
```C#
        internal static string GetResourceString(string resourceKey, string defaultString)
        {
            string resourceString = null;
            try { resourceString = InternalGetResourceString(resourceKey); }
            catch (MissingManifestResourceException) { }

            if (defaultString != null && resourceKey.Equals(resourceString, StringComparison.Ordinal))
            {
                return defaultString;
            }

            return resourceString;
        }
```

Upon trying to add cRowsAffected into my watch and casting as an int or long it gives a, "Cannot obtain value of the local variable or argument because it is not available." when doing a delete. However when running a Select it returns a -1 as expected.

**Comment by Clockwork-Muse** [comment]
[`CalculateRecordsAffected` is takes an `int`](https://github.com/dotnet/corefx/blob/0cc22ccba707d7552159363d586262fa9c4e8a2a/src/System.Data.Odbc/src/System/Data/Odbc/OdbcDataReader.cs#L273):

```csharp
internal int CalculateRecordsAffected(int cRowsAffected)
{
    if (0 <= cRowsAffected)
    {
        if (-1 == _recordAffected)
        {
            _recordAffected = cRowsAffected;
        }
        else
        {
            _recordAffected += cRowsAffected;
        }
    }
    return _recordAffected;
}
```

this is causing `cRowsAffected` (which is a wrapper around an `IntPtr`) to [call this operator](https://github.com/dotnet/corefx/blob/b49a8a9be1d53cd9e50cb68fd8540be25c65d433/src/System.Data.Odbc/src/System/Data/Odbc/OdbcStatementHandle.cs#L43):

```csharp
public static unsafe implicit operator int(SQLLEN value)
{
#if WIN32
    return (int)value._value.ToInt32();
#else
    long l = (long)value._value.ToInt64();
    return checked((int)l);
#endif
}
```
I'm assuming it's the `return checked((int)l);` line that is actually throwing, which implies that your statement affected 2 billion+ rows.  

Which is certainly in a believable range (I'm not sure if they're all stored in the same or partitioned tables, but we definitely have cause for that many rows on an iSeries database here).  Unfortunately `DbDataReader.RowsAffected` is a strict 32-bit int...



<hr />

`GetResourceString` is almost certainly just from reporting the overflow, an not at issue.

**Comment by BockTim91** [comment]
I can safely say the table I was updating has less than 12 million records in it. The statement I am running is on the key affecting only one record.
