### ISSUE TITLE
Problems Starting dotnet (First Timer)

### ISSUE THREAD

**Issue by arosado2895** [dotnet/corefx#42669]
λ dotnet new webApp -o myWebApp --no-https cd myWebApp
Unhandled exception. System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment' threw an exception.
 ---> System.ArgumentException: External component has thrown an exception.
   at System.Globalization.CompareInfo.CompareString(ReadOnlySpan`1 string1, ReadOnlySpan`1 string2, CompareOptions options)
   at System.Globalization.CompareInfo.Compare(String string1, String string2, CompareOptions options)
   at System.Globalization.TextInfo.PopulateIsAsciiCasingSameAsInvariant()
   at System.Globalization.TextInfo.ChangeCaseCommon[TConversion](String source)
   at System.Globalization.TextInfo.ToLower(String str)
   at System.String.ToLowerInvariant()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetArch()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetRuntimeIdentifier()
   at Microsoft.DotNet.Cli.MulticoreJitProfilePathCalculator.CalculateProfileRootPath()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.StartCliProfileOptimization()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.TryActivateMulticoreJit()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

**Comment by scalablecory** [comment]
@tarekgh

**Comment by tarekgh** [comment]
@arosado2895 @krussokc could you please check in your machine if Windows compatibility mode is enabled on dotnet.exe? you can do that from Windows explorer, go to dotnet.exe folder (usually it is C:\Program Files\dotnet) and then right click on dotnet.exe, click on the compatibility tab then look if the box labeled "Run this program in compatibility mode for:" is checked.

**Comment by tarekgh** [comment]
This can be the same issue https://github.com/dotnet/coreclr/issues/15021

**Comment by tarekgh** [comment]
@krussokc does the problem occur when you try to compile from the command line? I am asking because this can be a different issue than what @arosado2895 reported. something like https://developercommunity.visualstudio.com/content/problem/288684/the-program-12828-dotnetexe-has-exited-with-code-2.html and https://github.com/aspnet/AspNetCore/issues/1719

**Comment by tarekgh** [comment]
@arosado2895 any news?

**Comment by tarekgh** [comment]
@arosado2895 I am closing this one but feel free to respond back and will be happy to assist you.
