### ISSUE TITLE
JsonSerializer throws InvalidCastException

### ISSUE THREAD

**Issue by FolkCoder** [dotnet/corefx#42693]
Using .NET Core 3.0 or 3.1.100-preview3-014645, an `ICollection<string>` property with a private backing field assigned a custom implementation fails to serialize. 

```
    public class Client
    {
        private ICollection<string> _allowedGrantTypes = new GrantTypeValidatingHashSet();

        // this works 
        // public GrantTypeValidatingHashSet AllowedGrantTypes { get; set; }

        // this works 
        // public ICollection<string> AllowedGrantTypes { get; set; } = new GrantTypeValidatingHashSet();

        // this errors
        public ICollection<string> AllowedGrantTypes
        {
            get { return _allowedGrantTypes; }
            set
            {
                _allowedGrantTypes = new GrantTypeValidatingHashSet();
            }
        }
    }
```

#### Error message
```
System.InvalidCastException: 'Unable to cast object of type 'SerializationSample.GrantTypeValidatingHashSet' to type 'System.Collections.Generic.IList`1[System.String]'.'
```

#### Stack trace
```
at System.Text.Json.JsonSerializer.ApplyValueToEnumerable[TProperty](TProperty& value, ReadStack& state)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnReadEnumerable(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.ReadEnumerable(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at SerializationSample.Program.Main() in C:\SerializationSample\SerializationSample\Program.cs:line 13
```

This was discovered while attempting to serialize a `Client` model from [IdentityServer4](https://github.com/IdentityServer/IdentityServer4/blob/master/src/Storage/src/Models/Client.cs). I've recreated a [bare-bones project](https://github.com/FolkCoder/SerializationSample/tree/master) duplicating the error. Serialization occurs correctly with Newtonsoft.Json.

**Comment by Fr1z2r** [comment]
Here is another simpler example. This code throws an exception when IgnoreNullValues=true, and doesn't throw when IgnoreNullValues=false:
```
class MyClass
{
    public HashSet<int> X { get; set; } = new HashSet<int>();
}

public static void Main()
{
    JsonSerializer.Deserialize<MyClass>(@"{""X"":[2,1]}", 
        new JsonSerializerOptions {IgnoreNullValues = true});
}
```



```
System.InvalidCastException : Unable to cast object of type 'System.Collections.Generic.HashSet`1[System.Int32]' to type 'System.Collections.IList'.
   at System.Text.Json.JsonSerializer.ApplyObjectToEnumerable(Object value, ReadStack& state, Boolean setPropertyDirectly)
   at System.Text.Json.JsonSerializer.HandleEndArray(JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
```
