### ISSUE TITLE
System.Net.Security.SslStream breaks after upgrade 2.1 -> 3.0 (Linux only)

### ISSUE THREAD

**Issue by Spaceman1861** [dotnet/corefx#42701]
Hi all!

First up, not sure if this the correct repo let me know if needs moving.

This has been discussed here(https://github.com/jstedfast/MailKit/issues/951) as well and determined that it was probably a dotnet issue.

We are hitting an issue with MailKit connecting to certain IMAP servers post upgrade to 3.0 only on the base 3.0 linux distro (debian 10). When I run locally on windows its fine.

The IMAP servers in question all have self signed certs that worked before the upgrade but now they throw this when requested from the Debain based docker image.

```
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__64_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MailKit.Net.Imap.ImapClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
```

I got around this exception by downgrading to debain 9 and manually installing the 3.0 runtime. I did this by changing my dockerfile.

From:
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.0 as build

# Make a working dir
WORKDIR /app
# Copy from local filesystem into working dir
COPY . .
# Publish
RUN dotnet publish SOMEREDACTEDPATH -c Release -o /publish

#Runtime Image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 as final

# Make a working dir
WORKDIR /app

# Copy publish output from last image
COPY --from=build /publish .
# Set Entry Point for Container
ENTRYPOINT ["dotnet", "SOMEREDACTEDPATH"]
```
To
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.0 as build

# Make a working dir
WORKDIR /app
# Copy from local filesystem into working dir
COPY . .
# Publish
RUN dotnet publish SOMEREDACTEDPATH -c Release -o /publish

#Runtime Image
FROM microsoft/dotnet:2.1-runtime AS final

# Make a working dir
WORKDIR /app

ENV ASPNETCORE_VERSION 3.0.1
RUN curl -SL --output aspnetcore.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/$ASPNETCORE_VERSION/aspnetcore-runtime-$ASPNETCORE_VERSION-linux-x64.tar.gz \
    && aspnetcore_sha512='f7f6c8e09a9faccb818c42312e77e2fd3d34a7186d611fbe9e77dfb8d02178f31a4f563a5ff8218678cd3c00e7e8e9aef10a69f32f44fdac9a616993c57d1253' \
    && echo "$aspnetcore_sha512  aspnetcore.tar.gz" | sha512sum -c - \
    && mkdir -p /usr/share/dotnet \
    && tar -zxf aspnetcore.tar.gz -C /usr/share/dotnet \
    && rm aspnetcore.tar.gz \
    && ln -sf /usr/share/dotnet/dotnet /usr/bin/dotnet

RUN dotnet --info

# Copy publish output from last image
COPY --from=build /publish .
# Set Entry Point for Container
ENTRYPOINT ["dotnet", "SOMEREDACTEDPATH"]
```
This works fine.

I'm not really sure how to proceed with this, I'm guessing that is either a bug in Debain 10 or a bug in dotnet 3.0.

**Comment by eiriktsarpalis** [comment]
I can attest that trivial applications of SslStream using self-signed certificates in .NET Core/Debian 10 have worked just fine for me, so I suspect there might be something peculiar about your set-up that triggers the issue. I appreciate this might not be easy, but would you be able to share a minimal reproduction that triggers the issue.

Also, can you confirm whether the issue occurs in other officially supported 3.0 images? See the [full tag listings here](https://hub.docker.com/_/microsoft-dotnet-core-aspnet/).

**Comment by Spaceman1861** [comment]
I'm not sure i can setup a repo beyond the code shared in the linked call.

Due to the issue occurring on connection to one of our customers Imap clients that I can't give credentials out for.

I will try some of the other images and report back.

To reiterate the current tested images results with:

microsoft/dotnet:2.1-runtime works.
mcr.microsoft.com/dotnet/core/aspnet:3.0 does not.

**Comment by Spaceman1861** [comment]
Just an update on this due to it being a server and certificate of a client I'm unable to give you a repro.

We will attempt to diagnose internally.

However due to the workaround working fine this has become a low priority high cost item for us.

I don't expect to see an traction any time soon.

**Comment by wfurt** [comment]
If downgrade to Debian9 solves this, it suggests that this is related to OpenSSL version.
As far as I know, new OpenSSL (and MacOS as well) are more strict about proper EKU and KU extensions. (for example discussion in https://github.com/dotnet/corefx/issues/37282) You can use 'openssl s_client' to see if OS trusts your certificate. .NET generally defers decision about trust to OS so if OS does not trust it, .NET will not either. 

As far as the repro, you can always provide a certificate with exactly same structure and extensions but different key pair.
