### ISSUE TITLE
NetFxToWinRtStreamAdapter.WriteAsync fails with ArgumentOutOfRangeException when buffer is empty

### ISSUE THREAD

**Issue by andriysavin** [dotnet/corefx#42708]
This bug exists since .Net Framework implementation. Basically, when a WinRT stream is an adapter around a .Net `Stream` and you attempt to write an empty **native** `IBuffer` to that stream, you get an `ArgumentOutOfRangeException`. Here is an example:

``` csharp
static async Task Main()
{
    using var fileStream = File.OpenWrite("TestFile.txt");
    using var winRtStream = fileStream.AsOutputStream();

    // This works OK.
    await fileStream.WriteAsync(ReadOnlyMemory<byte>.Empty);
    Console.WriteLine("fileStream.WriteAsync completed OK");

    var winRtbuffer = new Windows.Storage.Streams.Buffer(capacity: 0);

    // This fails!
    await winRtStream.WriteAsync(winRtbuffer);
    Console.WriteLine("winRtStream.WriteAsync completed OK");
}
```
This gives the following when running:

```
fileStream.WriteAsync completed OK
Unhandled exception. System.ArgumentOutOfRangeException: Positive number required. (Parameter 'bufferSize')
Actual value was 0.
   at System.IO.StreamHelpers.ValidateCopyToArgs(Stream source, Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.IO.StreamOperationsImplementation.<>c__DisplayClass2_0.<<WriteAsync_AbstractStream>b__1>d.MoveNext()
```
Unless I'm missing something, there is no point in not supporting empty buffer writes. Actually, if the `IBuffer` is a wrapper for managed memory, all works fine (because internally the write is done differently in this case). 

It's easy to find the root of the problem. [Here](https://github.com/dotnet/corefx/blob/a12c557a72988070b8624cc7ecc46899629895c4/src/System.Runtime.WindowsRuntime/src/System/IO/StreamOperationsImplementation.cs#L207)  `Stream.CopyAsync` method is used, which doesn't support zero buffer length and crashes. The code above that line doesn't check if `bytesToWrite` is zero and uses it as the buffer size:
```csharp
 int buffSize = 0x4000;
 if (bytesToWrite < buffSize)
      buffSize = (int)bytesToWrite;
```

While it may seem silly to try to write an empty buffer to a stream, Writer code may calculate the amount to write dynamically and not check for zero length. Actually, I have a real world scenario in which this bug affects me: i'm using UWP's `Windows.Media.Transcoding.MediaTranscoder` API to transcode audio files, passing it .Net file streams. `Transcoder` often tries to write an empty buffer, so the code almost always crashes.

**Comment by andriysavin** [comment]
In case anybody needs it, here's a workaround I created. This is just a decorator around the WinRT stream (note I use `IRandomAccessStream` here, but you can create the same for `IOutputStream`).

```csharp
internal class SkipZeroLengthWritesStreamDecorator : IRandomAccessStream
{
    private static readonly Task<uint> ZeroBytesWrittenTask = Task.FromResult(0U);
    private static readonly Func<CancellationToken, IProgress<uint>, Task<uint>>
        ZeroBytesWrittenTaskProvider = (ct, p) => ZeroBytesWrittenTask;

    private readonly IRandomAccessStream innerStream;

    public SkipZeroLengthWritesStreamDecorator(IRandomAccessStream innerStream)
    {
        this.innerStream = innerStream;
    }

    public bool CanRead => innerStream.CanRead;
    public bool CanWrite => innerStream.CanWrite;
    public ulong Position => innerStream.Position;
    public ulong Size { get => innerStream.Size; set => innerStream.Size = value; }

    public void Seek(ulong position) => innerStream.Seek(position);
    public IRandomAccessStream CloneStream() => innerStream.CloneStream();
    public IAsyncOperation<bool> FlushAsync() => innerStream.FlushAsync();
    public void Dispose() => innerStream.Dispose();

    public IInputStream GetInputStreamAt(ulong position)
        => innerStream.GetInputStreamAt(position);

    public IOutputStream GetOutputStreamAt(ulong position)
        => innerStream.GetOutputStreamAt(position);

    public IAsyncOperationWithProgress<IBuffer, uint> ReadAsync(IBuffer buffer, uint count, InputStreamOptions options)
        => innerStream.ReadAsync(buffer, count, options);

    public IAsyncOperationWithProgress<uint, uint> WriteAsync(IBuffer buffer)
    {
        if (buffer.Length == 0)
        {
            return AsyncInfo.Run<uint, uint>(ZeroBytesWrittenTaskProvider);
        }

        return innerStream.WriteAsync(buffer);
    }
}
```

To use it, just wrap an IRandomAccessStream with this decorator and pass it to the writer:

`using var winRtStream = new SkipZeroLengthWritesStreamDecorator(fileStream.AsRandomAccessStream());`

MS guys, please, review this class, as I'm not 100% sure I'm not missing any tricky resource cleanup nuances or anything else.
