### ISSUE TITLE
28% of SqlClient connections on OSX/Linux break

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#4273]
On Linux, calls to `SqlCommand.ExecuteReader` often die due to a broken connection.

Ubuntu 14.04, CoreCLR rc1
System.Data.SqlClient build 23429

These failures are nondeterministic, and do not appear on Windows.

```
Microsoft.Data.Entity.SqlServer.FunctionalTests.DataAnnotationSqlServerTest.TimestampAttribute_throws_if_value_in_database_changed [FAIL]
      Microsoft.Data.Entity.DbUpdateException : An error occurred while updating the entries. See the inner exception for details.
      ---- System.Data.SqlClient.SqlException : The connection is broken and recovery is not possible.  The connection is marked by the server as unrecoverable.  No attempt was made to restore the connection.
        ----- Inner Stack Trace -----
           at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
           at System.Data.SqlClient.SqlConnection.ValidateAndReconnect(Action beforeDisconnect, Int32 timeout)
           at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
           at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
```

Calls to `ExecuteNonQuery` often fail with this error:
```
System.Data.SqlClient.SqlException : A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - Connection was terminated)
      A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - Connection was terminated)
      Stack Trace:
           at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
           at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
           at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
           at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
           at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
           at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
           at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
           at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
           at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
           at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
           at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
```
 or with a similar variant that has this error:
```
(provider: TCP Provider, error: 0 - Unable to read data from the transport connection: Unknown error 10054.)
```

Repeated runs of one test do not always fail, but it does not take high load to produce the error. This error consistently reproduces at some point when running the all tests in EntityFramework ([code here](https://github.com/aspnet/EntityFramework/tree/release/test/EntityFramework.MicrosoftSqlServer.FunctionalTests)). I can create a simplified repro project if necessary.

Full test log here: [sqlserver-functionaltests.log](https://gist.githubusercontent.com/natemcmaster/13532755aeeee6a53ccb/raw/259802c7a4e6fd182e0e0bf5a86d04392eba8dad/sqlserver-functionaltests.log)

**Comment by saurabh500** [comment]
Few notes:
      A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - Connection was terminated)

This happens when SqlClient is expecting to get data from the Stream and there is no data available.

https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNITcpHandle.cs#L280

This will need to be looked at by Networking

**Comment by saurabh500** [comment]
@natemcmaster Do we have any results from OSX as well?

**Comment by natemcmaster** [comment]
@saurabh500 I do not have OSX results yet.

@joshfree 23430 did not resolve the errors.

**Comment by natemcmaster** [comment]
Update: OSX breaks with the same error messages (see [full osx log file here](https://gist.githubusercontent.com/natemcmaster/f36b127b2c1d2bd12d55/raw/00e24423f6b1c85cef627952907fe2365a8fc7f1/23502_osx.log)). Still breaking on ubuntu using SqlClient 23502 (see [23502_ubuntu.log](https://gist.githubusercontent.com/natemcmaster/f36b127b2c1d2bd12d55/raw/00e24423f6b1c85cef627952907fe2365a8fc7f1/23502_ubuntu.log)).

On OSX, SNI dies with this error:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.SqlClient.SNI.SNIMarsConnection.Send(SNIPacket packet)
   at System.Data.SqlClient.SNI.SNIMarsHandle.Send(SNIPacket packet)
   at System.Data.SqlClient.TdsParserStateObject.SNIWritePacket(SNIHandle handle, SNIPacket packet, UInt32& sniError, Boolean canAccumulate, Boolean callerHasConnectionLock)
   at System.Data.SqlClient.TdsParserStateObject.WriteSni(Boolean canAccumulate)
   at System.Data.SqlClient.TdsParserStateObject.WritePacket(Byte flushMode, Boolean canAccumulate)
   at System.Data.SqlClient.TdsParser.TdsExecuteTransactionManagerRequest(Byte[] buffer, TransactionManagerRequestType request, String transactionName, TransactionManagerIsolationLevel isoLevel, Int32 timeout, SqlInternalTransaction transaction, TdsParserStateObject stateObj)
   at System.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransactionYukon(TransactionRequest transactionRequest, String transactionName, IsolationLevel iso, SqlInternalTransaction internalTransaction)
   at System.Data.SqlClient.SqlInternalTransaction.CloseFromConnection()
   at System.Data.SqlClient.TdsParser.Deactivate(Boolean connectionIsDoomed)
   at System.Data.SqlClient.SqlInternalConnectionTds.InternalDeactivate()
   at System.Data.SqlClient.SqlInternalConnection.Deactivate()
   at System.Data.ProviderBase.DbConnectionInternal.DeactivateConnection()
   at System.Data.ProviderBase.DbConnectionPool.DeactivateObject(DbConnectionInternal obj)
   at System.Data.ProviderBase.DbConnectionPool.ReclaimEmancipatedObjects()
   at System.Data.ProviderBase.DbConnectionPool.Clear()
   at System.Data.ProviderBase.DbConnectionFactory.PruneConnectionPoolGroups(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
libc++abi.dylib: terminating with uncaught exception of type PAL_SEHException
```

**Comment by saurabh500** [comment]
Majority of OSX exceptions are due to the Networking failures as well. 

When SqlClient tries to retrieve data from NetworkStream, the stream returns 0 bytes eventually, not providing all the data that SqlClient needs.

**Comment by saurabh500** [comment]
On further investigation, I figured out that the failures are due to the enablement of MARS (MultipleActiveResultsSet) in the connection String. 

The implementation of MARS in the Managed Sql Client is still flaky. We will provide details after more investigations. Due to bad MARS implementation, the server is terminating the connection.

*The recommendation is to turn off MARS while connecting to SQL Server while running these tests.*

The suggested patch for the EF tests run on XPlat is 

@@ -503,9 +503,9 @@ namespace Microsoft.Data.Entity.SqlServer.FunctionalTests
         public static string CreateConnectionString(string name)
         {
             var connStrBuilder = new SqlConnectionStringBuilder
-                {
-                    //MultipleActiveResultSets = false,
-                    MultipleActiveResultSets = new Random().Next(0, 2) == 1,
+            {
+                MultipleActiveResultSets = false,
+                //MultipleActiveResultSets = new Random().Next(0, 2) == 1,
                     InitialCatalog = name
                 };
             return connStrBuilder.ApplyConfiguration().ConnectionString;

This can be verified for XPlat only after DNX packaging being tracked by https://github.com/dotnet/corefx/issues/4339 is fixed.

@natemcmaster "Repeated runs of one test do not always fail, but it does not take high load to produce the error." 
EF tests are turning on MARS *randomly* on the tests as can be seen in the above patch "MultipleActiveResultSets = new Random().Next(0, 2) == 1,"  :)
Because of this the failures were not consistent. 

Once we verify that without MARS, there are no other Xplat problems, I will look at closing the issue and track the MARS implementation with another specific issue.

**Comment by natemcmaster** [comment]
MARS is an important feature. Although flaky, let's leave MARS enabled in EF testing to dogfood any progress on this.

**Comment by saurabh500** [comment]
Yes MARS is important. I didn't mean to suggest a permanent change to EF
test. Just wanted to point out the code where MARS is enabled so that we
have it documented with this issue.

**Comment by saurabh500** [comment]
cc @corivera

**Comment by saurabh500** [comment]
The exception prevalent without MARS is 

---- System.Data.SqlClient.SqlException : The connection is broken and recovery is not possible.  The connection is marked by the server as unrecoverable.  No attempt was made to restore the connection.
      Stack Trace:
           at Microsoft.Data.Entity.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__28.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           at Microsoft.Data.Entity.Update.Internal.BatchExecutor.<ExecuteAsync>d__1.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__36.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           at Microsoft.Data.Entity.DbContext.<SaveChangesAsync>d__28.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           at Microsoft.Data.Entity.SqlServer.FunctionalTests.SequenceEndToEndTest.<AddEntitiesAsync>d__3.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           at Microsoft.Data.Entity.SqlServer.FunctionalTests.SequenceEndToEndTest.<Can_use_sequence_end_to_end_async>d__2.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        ----- Inner Stack Trace -----
           at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__112_0(Task`1 result)
           at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
           at System.Threading.Tasks.Task.Execute()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.<>c__DisplayClass18_0.<<ExecuteReaderAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.<ExecuteAsync>d__20`1.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.<ExecuteReaderAsync>d__18.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           at Microsoft.Data.Entity.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__28.MoveNext()

**Comment by saurabh500** [comment]
Exceptions reported by Nate's run after MARS disablement.

Microsoft.Data.Entity.SqlServer.FunctionalTests.NullKeysSqlServerTest.Include_with_null_FKs_and_nullable_PK
      System.Data.SqlClient.SqlException : The connection is broken and recovery is not possible.  The connection is marked by the server as unrecoverable.  No attempt was made to restore the connection.
      Stack Trace:
           at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
           at System.Data.SqlClient.SqlConnection.ValidateAndReconnect(Action beforeDisconnect, Int32 timeout)
           at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
           at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
           at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
           at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.<>c.<ExecuteNonQuery>b__13_0(DbCommand cmd, IRelationalConnection con)
           at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.Execute[T](IRelationalConnection connection, Func`3 action, String executeMethod, Boolean openConnection, Boolean closeConnection)
           at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, Boolean manageConnection)
           at Microsoft.Data.Entity.Storage.RelationalCommandExtensions.ExecuteNonQuery(IEnumerable`1 commands, IRelationalConnection connection)
           at Microsoft.Data.Entity.Storage.Internal.SqlServerDatabaseCreator.Delete()
           at Microsoft.Data.Entity.Storage.RelationalDatabaseCreator.EnsureDeleted()
           at Microsoft.Data.Entity.Infrastructure.DatabaseFacade.EnsureDeleted()
           at Microsoft.Data.Entity.SqlServer.FunctionalTests.SqlServerValueGenerationScenariosTest.TestBase`1..ctor()
           at Microsoft.Data.Entity.SqlServer.FunctionalTests.SqlServerValueGenerationScenariosTest.DoNothingButSpecifyKeys..ctor()

**Comment by saurabh500** [comment]
https://gist.github.com/saurabh500/a2b1def047b0e1cffe60

**Comment by saurabh500** [comment]
The Fix for MARS is in RC2 with the Pull Request https://github.com/dotnet/corefx/pull/4486

**Comment by saurabh500** [comment]
For the following exception  we found that the socket.Poll() in the Connection Checking of SqlClient is possibly not providing the correct information. Looking into the fix. 

System.Data.SqlClient.SqlException : The connection is broken and recovery is not possible. The connection is marked by the server as unrecoverable. No attempt was made to restore the connection.
Stack Trace:
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction) at System.Data.SqlClient.SqlConnection.ValidateAndReconnect(Action beforeDisconnect, Int32 timeout) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.<>c.b__13_0(DbCommand cmd, IRelationalConnection con)

**Comment by saurabh500** [comment]
#4499  needs to be present in RC1 for the tests to succeed.

The errors with message "The connection is broken and recovery is not possible. The connection is marked by the server as unrecoverable. No attempt was made to restore the connection." were a result of the bad Socket.Poll results on Linux.

**Comment by saurabh500** [comment]
With MARS disabled and #4499 changes this should be fixed in RC1.
For RC2 this can be completely resolved based on EF tests .
