### ISSUE TITLE
.net core 3.0 getting System.Threading.Tasks.TaskCanceledException: The operation was canceled.

### ISSUE THREAD

**Issue by KamranShahid** [dotnet/corefx#42738]
I have .net core 3.0 web api project where i am calling my .net core 3.0 service (systemd in linux) httplistener calls.
I am getting error

```
await client.PostAsync(url, content).ConfigureAwait(false)
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
```

My calling method is 

```
		public static async Task<GenerricApiResponsewithResult> ProcessWebRequestWithResponsetype<T>(string url, string friendlyName, T req)
        {
            var obj = new GenerricApiResponsewithResult();
            try
            {
                using (var client = new HttpClient())
                {
                    var jsonRequest = JsonSerializer.Serialize(req);
                    client.DefaultRequestHeaders.ExpectContinue = false;
                    var content = new StringContent(jsonRequest);
                    content.Headers.Clear();
                    content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                    
                    var response = await client.PostAsync(url, content).ConfigureAwait(false);
                    obj.HttpResponseCode = response.StatusCode;
                    if (response.StatusCode == HttpStatusCode.OK)
                    {
                        obj.Response = await response.Content.ReadAsStringAsync();
                        if (obj.Response != null && IsValidJson(obj.Response))
                        {
                            obj = JsonSerializer.Deserialize<GenerricApiResponsewithResult>(obj.Response);
                        }
                    }
                    else
                    {

                        obj.IsError = true;
                        obj.Response = response.StatusCode.ToString();
                    }
                    client.Dispose();
                }
            }
            catch (Exception ex)
            {
                obj.IsError = true;
                obj.Exception = ex;

                obj.Response = $"Error Processing a call to {friendlyName}. Please see logs";
                Logger.Fatal(obj.Response + " " + ex.Message, ex);
            }
            return obj;
        }
```

**Comment by KamranShahid** [comment]
What i further observe is the url i am trying to access was in-accessible that time. it should ideally have thrown request time out exception

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/20296

**Comment by KamranShahid** [comment]
this was not happening in .net core 2.1.
Looks like i have to update my code to

```
public static async Task<GenerricApiResponsewithResult> ProcessWebRequestWithResponsetype<T>(string url, string friendlyName, T req)
        {
            var obj = new GenerricApiResponsewithResult();
            try
            {
                using (var client = new HttpClient())
                {
                    var jsonRequest = JsonSerializer.Serialize(req);
                    client.DefaultRequestHeaders.ExpectContinue = false;
                    var content = new StringContent(jsonRequest);
                    content.Headers.Clear();
                    content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                   
                    var response = await client.PostAsync(url, content).ConfigureAwait(false);
                    obj.HttpResponseCode = response.StatusCode;
                    if (response.StatusCode == HttpStatusCode.OK)
                    {
                        if (response.Content != null)
                        {
                            obj.Response = await response.Content.ReadAsStringAsync();
                            if (obj.Response != null && IsValidJson(obj.Response))
                            {
                                obj = JsonSerializer.Deserialize<GenerricApiResponsewithResult>(obj.Response);
                            }
                        }
                        else
                        {
                            Logger.Debug("No content recevied");
                        }
                    }
                    else
                    {

                        obj.IsError = true;
                        obj.Response = response.StatusCode.ToString();
                    }
                    client.Dispose();
                }
            }

            catch (OperationCanceledException ex) when (ex.InnerException is TimeoutException)
            {
                obj.IsError = true;
                obj.Exception = ex.InnerException;

                obj.Response = $"Error Processing a call to {friendlyName}. Please see logs";
                Logger.Fatal(obj.Response + " " + ex.InnerException.Message, ex.InnerException);
            }
            catch (Exception ex)
            {
                obj.IsError = true;
                obj.Exception = ex;

                obj.Response = $"Error Processing a call to {friendlyName}. Please see logs";
                Logger.Fatal(obj.Response + " " + ex.Message, ex);
            }
            return obj;
        }

```

**Comment by stephentoub** [comment]
> this was not happening in .net core 2.1.

Timeouts with HttpClient have always manifested as cancellation exceptions, some HttpClient uses cancellation to implement its timeout mechanism.
