### ISSUE TITLE
XmlQualifiedName class not marked as Serializable

### ISSUE THREAD

**Issue by ritchxu** [dotnet/corefx#42790]
While porting code to .NET Core, it was found that [XmlQualifiedName](https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/XmlQualifiedName.cs) is not marked as `Serializable` as it was [in .NET Framework](https://referencesource.microsoft.com/#System.Xml/System/Xml/XmlQualifiedName.cs). This caused any field/property in this class becoming not serializable.

### Question:
Is this by design?

### Reproducible steps:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

</Project>

```
```
using System;
using System.IO;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;
using System.Xml;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            IFormatter formatter = new BinaryFormatter();
            Stream stream = new MemoryStream();
            formatter.Serialize(stream, new TestClass());
        }
    }

    [Serializable]
    class TestClass
    {
        public TestClass()
        {
            TestProp = new XmlQualifiedName("TestProp");
        }

        XmlQualifiedName TestProp { get; set; }
    }
}
```
### Expected behavior:
`Serialize` call works without throwing exceptions,

### Actual behavior:
```
System.Runtime.Serialization.SerializationException
  HResult=0x8013150C
  Message=Type 'System.Xml.XmlQualifiedName' in Assembly 'System.Private.Xml, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' is not marked as serializable.
  Source=System.Runtime.Serialization.Formatters
  StackTrace:
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(Type type)
   at System.Runtime.Serialization.FormatterServices.<>c.<GetSerializableMembers>b__5_0(MemberHolder mh)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, BinaryFormatterWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Boolean check)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at ConsoleApp.Program.Main(String[] args) in C:\Rui\Projects\PSCore\ConsoleApp\Program.cs:line 15

**Comment by ritchxu** [comment]
This also contradicts with the documentation https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlqualifiedname?view=netcore-3.1

```
[System.Serializable]
public class XmlQualifiedName

**Comment by danmosemsft** [comment]
Hello @ritchxu , in .NET Core many fewer types are marked for binary serialization. This is a decision made to reduce maintenance burden and security surface area. Please see
https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization#binary-serialization-in-net-core

Yes, it should not be shown in the API docs. This should be fixed in https://github.com/dotnet/dotnet-api-docs/issues/2986. Feel free to +1 that issue.

**Comment by danmosemsft** [comment]
We recommend that you use a different serialization technology (such as DataContract or JSON)
