### ISSUE TITLE
BinaryFormatter yields 'Invalid BinaryFormatter Stream' error when deserializing large files multiple times

### ISSUE THREAD

**Issue by buddhashrestha** [dotnet/corefx#42813]
I'm serializing, compresssing and encrypting C# object and save it to the file. That works fine.
Then I need to decrypt, decompress and deserialize it back again (like when opening a project). Now, this works fine for the first time when I start my application, but if I try to retry in the same session, it fails and throws me the following exception with Message: **Invalid BinaryFormatter Stream**

   ```
at System.Runtime.Serialization.Formatters.Binary.SizedArray.IncreaseCapacity(Int32 index)
   at System.Runtime.Serialization.Formatters.Binary.SizedArray.set_Item(Int32 index, Object value)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
```

**Note:** This happens only when I'm trying to deserialize a large file. (**>40MB**)

Following is the code I use:
`var rm = new AesCryptoServiceProvider();
                        rm.Key = this.CryptoKey;
                        rm.IV = this.CryptoIV;

                        using(var sourceStream = new TempFileStream(rawData))
                        using (var outStream = new TempFileStream())
                        {
                            using (CryptoStream cryptoStream = new CryptoStream(sourceStream, rm.CreateDecryptor(), CryptoStreamMode.Read))
                            {
                                using (GZipStream gzipStream = new GZipStream(cryptoStream, CompressionMode.Decompress))
                                {
                                    gzipStream.CopyTo(outStream);
                                }
                            }
                            outStream.Position = 0;
                            dataStore = (IDataStoreClient)BinaryFormatter.Deserialize(outStream);
                        }`

**Comment by GrabYourPitchforks** [comment]
What happens if you change the two _using_ statements to use `MemoryStream` instead of `TempFileStream`? Do you encounter the same issue? (I'm assuming _rawData_ is a `byte[]`.)

**Comment by buddhashrestha** [comment]
@GrabYourPitchforks yes. rawData is byte[]. When I use `MemoryStream`, I get `System.OutOfMemoryException`. That is why I use a temporary FileStream here.

**Comment by GrabYourPitchforks** [comment]
Can you provide the implementation of your `TempFileStream` class?

**Comment by buddhashrestha** [comment]
Sure. This is just to make sure we create a temporary file stream for opening up the project.
[tempFile.zip](https://github.com/dotnet/corefx/files/4048643/tempFile.zip)

**Comment by buddhashrestha** [comment]
@GrabYourPitchforks For simplicity, here is an implementation of `TempFileStream`. I've modified the implementation, but still, the behaviour is the same.

```
public class TempFileStreams
        {
            public string fileName = Path.GetTempFileName();
            public Stream FromBytes(byte[] bytes)
            {
                File.WriteAllBytes(fileName, bytes);
                FileStream fs = new FileStream(fileName,FileMode.Open);
                return fs;   
             }

            public Stream GenerateTemp()
            {                
                FileStream fs = new FileStream(fileName, FileMode.Open,FileAccess.ReadWrite);
                return fs;
            }
            ~TempFileStreams()
            {
                File.Delete(fileName);
            }
        }
```

**Comment by GrabYourPitchforks** [comment]
I have a feeling your `TempFileStream` finalizer is running in the middle of data processing, attempting to delete the file even while the code is still operating on it and causing data corruption. Consider instead calling a `FileStream` ctor which takes a `FileOptions` parameter and passing [`FileOptions.Close`](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileoptions) as the argument. Then you won't need a custom finalizable type.

Also, consider having a security reviewer take a look at your use of cryptography in this code. Protection of data at rest is a bit tricky, so you'll want a professional set of eyes on your code base to ensure you're following best practice.

**Comment by buddhashrestha** [comment]
hi @GrabYourPitchforks thank you for the feedback. I tried it that way too, but I get the same behaviour. Again, this is doesn't happen when the file is small (<20Mb). And I use this `TempFileStreams` because using `MemoryStream` throws `System.OutOfMemoryException`. So, I just wanted to know how should I approach this problem. Also, the error is occurring at `System.Runtime.Serialization.Formatters.Binary.SizedArray.IncreaseCapacity(Int32 index)
`  so is there a possibility that the exception occurred while trying to increase the size of the array?

**Comment by buddhashrestha** [comment]
I also ran a memory profiler, and it shows the following result:
![image](https://user-images.githubusercontent.com/10449218/72233167-79903e80-357a-11ea-94b4-2c9bd0af4bd0.png)
I think this is due to memory issues while deserializing the data.
