### ISSUE TITLE
Issue on Deserialisation in .Netcore 3.0 :: Getting System.InvalidCastException

### ISSUE THREAD

**Issue by AgnesAarthy** [dotnet/corefx#42846]
Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Specified cast is not valid.
   at System.Data.DataTable..ctor(SerializationInfo info, StreamingContext context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)

**Comment by vcsjones** [comment]
1. Can you provide a minimal code sample that reproduces the issue?
2. Was it working on previous versions of .NET Core, such as .NET Core 2.x, or .NET Framework?

**Comment by AgnesAarthy** [comment]
I will give the background of what I have done.
1) I ported my code base from Mono to .Netcore 3.0. 
2) There are subsystems which interact with this code base that are in .net framework.
3) The serialisation with binary formatter happens in .netcore 3.0 where the other subsystems receive my data and deserialise using the same formatter configuartions in .Netframework. The Error is thrown here.
The same code and subsytem interations works fine for .Netframework and Mono also. In .Net core alone I am facing the issue. I havent tried in lower versions of .Netcore.
I am fed up with this issue and not knowing the root cause. Kindly provide ur inputs.
