### ISSUE TITLE
Several NumberFormatInfoCurrencyNegativePattern tests failing on CentOS

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4338]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_centos71_debug_tst/133/consoleFull
```
19:01:41    System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.TestCurrencyNegativePatternLocale(locale: "fr-CD", expectedWindows: 4, expectedIcu: 8) [FAIL]
19:01:41       Assert.Equal() Failure
19:01:41       Expected: 8
19:01:41       Actual:   15
19:01:41       Stack Trace:
19:01:42 Finished:    System.Reflection.Tests
19:01:42 
19:01:42 === TEST EXECUTION SUMMARY ===
19:01:42    System.Reflection.Tests  Total: 677, Errors: 0, Failed: 0, Skipped: 0, Time: 1.694s
19:01:42             at System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.TestCurrencyNegativePatternLocale(String locale, Int32 expectedWindows, Int32 expectedIcu)
19:01:42    System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.TestCurrencyNegativePatternLocale(locale: "en-US", expectedWindows: 0, expectedIcu: 1) [FAIL]
19:01:42       Assert.Equal() Failure
19:01:42       Expected: 1
19:01:42       Actual:   0
19:01:42       Stack Trace:
19:01:42             at System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.TestCurrencyNegativePatternLocale(String locale, Int32 expectedWindows, Int32 expectedIcu)
19:01:42    System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.TestCurrencyNegativePatternLocale(locale: "fa-IR", expectedWindows: 3, expectedIcu: 1) [FAIL]
19:01:42       Assert.Equal() Failure
19:01:42       Expected: 1
19:01:42       Actual:   0
19:01:42       Stack Trace:
19:01:42             at System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.TestCurrencyNegativePatternLocale(String locale, Int32 expectedWindows, Int32 expectedIcu)
19:01:42    System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.TestCurrencyNegativePatternLocale(locale: "fr-CA", expectedWindows: 15, expectedIcu: 8) [FAIL]
19:01:42       Assert.Equal() Failure
19:01:42       Expected: 8
19:01:42       Actual:   15
19:01:42       Stack Trace:
19:01:42             at System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.TestCurrencyNegativePatternLocale(String locale, Int32 expectedWindows, Int32 expectedIcu)
19:01:42    System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.TestCurrencyNegativePatternLocale2(locale: "en-CA", expected: 1) [FAIL]
19:01:42       Assert.Equal() Failure
19:01:42       Expected: 1
19:01:42       Actual:   0
19:01:42       Stack Trace:
19:01:42             at System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.TestCurrencyNegativePatternLocale2(String locale, Int32 expected)
```
cc: @steveharter, @ellismg

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/4496
