### ISSUE TITLE
GetAsync_AllowAutoRedirectFalse_RedirectFromHttpToHttp_StatusCodeRedirect failed in CI on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4364]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/5997/console
```
System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_AllowAutoRedirectFalse_RedirectFromHttpToHttp_StatusCodeRedirect [FAIL]
        Assert.Equal() Failure
        Expected: Redirect
        Actual:   NotFound
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs(217,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<GetAsync_AllowAutoRedirectFalse_RedirectFromHttpToHttp_StatusCodeRedirect>d__45.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by davidsh** [comment]
This appears to have been a transient Azure failure getting a 404 HTTP status code in return.
