### ISSUE TITLE
"Called on completed result" assert in Socket APM tests on Linux

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4396]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/4193/console
```
16:36:36 Unhandled Exception: System.Diagnostics.Debug+DebugAssertException: LazyAsyncResult#1978366::set_Result()
16:36:36 Called on completed result.
16:36:36    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
16:36:36    at System.Environment.get_StackTrace()
16:36:36    at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
16:36:36    at System.Net.GlobalLog.Assert(String message, String detailMessage)
16:36:36    at System.Net.GlobalLog.Assert(Boolean condition, String messageFormat, Object[] data)
16:36:36    at System.Net.LazyAsyncResult.set_Result(Object value)
16:36:36    at System.Net.Sockets.BaseOverlappedAsyncResult.CheckAsyncCallOverlappedResult(SocketError errorCode)
16:36:36    at System.Net.Sockets.Socket.DoBeginAccept(Socket acceptSocket, Int32 receiveSize, AcceptOverlappedAsyncResult asyncResult)
16:36:36    at System.Net.Sockets.Socket.BeginAccept(Socket acceptSocket, Int32 receiveSize, AsyncCallback callback, Object state)
16:36:36    at System.Net.Sockets.Socket.BeginAccept(Int32 receiveSize, AsyncCallback callback, Object state)
16:36:36    at System.Net.Sockets.Socket.BeginAccept(AsyncCallback callback, Object state)
16:36:36    at System.Net.Sockets.SocketTaskExtensions.<AcceptAsync>b__0(AsyncCallback callback, Object state)
16:36:36    at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
16:36:36    at System.Net.Sockets.SocketTaskExtensions.AcceptAsync(Socket socket)
16:36:36    at System.Net.Sockets.SocketAPMExtensions.BeginAccept(Socket socket, AsyncCallback callback, Object state)
16:36:36    at System.Net.Sockets.Tests.SocketTestServerAPM.OnAccept(IAsyncResult result)
16:36:36    at System.Threading.Tasks.TaskToApm.<>c__DisplayClass1.<InvokeCallbackWhenTaskCompletes>b__0()
16:36:36    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
16:36:36    at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
16:36:36    at System.Threading.Tasks.Task.FinishContinuations()
16:36:36    at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
16:36:36    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
16:36:36    at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
16:36:36    at System.Net.ContextAwareResult.CompleteCallback(Object state)
16:36:36    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
16:36:36    at System.Net.ContextAwareResult.Complete(IntPtr userToken)
16:36:36    at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
16:36:36    at System.Net.LazyAsyncResult.InvokeCallback(Object result)
16:36:36    at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError errorCode)
16:36:36    at System.Net.Sockets.AcceptOverlappedAsyncResult.CompletionCallback(Int32 acceptedFileDescriptor, Byte[] socketAddress, Int32 socketAddressLen, SocketError errorCode)
16:36:36    at System.Net.Sockets.SocketAsyncContext.AcceptOperation.InvokeCallback()
16:36:36    at System.Net.Sockets.SocketAsyncContext.AsyncOperation.<QueueCompletionCallback>b__26(Object o)
16:36:36    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
16:36:36    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
16:36:36    at System.Threading.ThreadPoolWorkQueue.Dispatch()
16:36:36    at System.Diagnostics.Debug.UnixDebugLogger.ShowAssertDialog(String stackTrace, String message, String detailMessage)
16:36:36    at System.Net.GlobalLog.Assert(String message, String detailMessage)
16:36:36    at System.Net.GlobalLog.Assert(Boolean condition, String messageFormat, Object[] data)
16:36:36    at System.Net.LazyAsyncResult.set_Result(Object value)
16:36:36    at System.Net.Sockets.BaseOverlappedAsyncResult.CheckAsyncCallOverlappedResult(SocketError errorCode)
16:36:36    at System.Net.Sockets.Socket.DoBeginAccept(Socket acceptSocket, Int32 receiveSize, AcceptOverlappedAsyncResult asyncResult)
16:36:36    at System.Net.Sockets.Socket.BeginAccept(Socket acceptSocket, Int32 receiveSize, AsyncCallback callback, Object state)
16:36:36    at System.Net.Sockets.Socket.BeginAccept(Int32 receiveSize, AsyncCallback callback, Object state)
16:36:36    at System.Net.Sockets.Socket.BeginAccept(AsyncCallback callback, Object state)
16:36:36    at System.Net.Sockets.SocketTaskExtensions.<AcceptAsync>b__0(AsyncCallback callback, Object state)
16:36:36    at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
16:36:36    at System.Net.Sockets.SocketTaskExtensions.AcceptAsync(Socket socket)
16:36:36    at System.Net.Sockets.SocketAPMExtensions.BeginAccept(Socket socket, AsyncCallback callback, Object state)
16:36:36    at System.Net.Sockets.Tests.SocketTestServerAPM.OnAccept(IAsyncResult result)
16:36:36    at System.Threading.Tasks.TaskToApm.<>c__DisplayClass1.<InvokeCallbackWhenTaskCompletes>b__0()
16:36:36    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
16:36:36    at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
16:36:36 --- End of stack trace from previous location where exception was thrown ---
16:36:36    at System.Threading.Tasks.AwaitTaskContinuation.<>c.<ThrowAsyncIfNecessary>b__18_0(Object s)
16:36:36    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
16:36:36    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
16:36:36    at System.Threading.ThreadPoolWorkQueue.Dispatch()
16:36:36 ./run-test.sh: line 130: 61302 Aborted                 (core dumped) ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory
16:36:36 One or more tests failed while running tests from 'System.Net.Sockets.APMServer.Tests'.  Exit code 134.
```
cc: @pgavlin, @cipop, @davidsh

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/4344/console
```
11:48:41 Unhandled Exception: System.Diagnostics.Debug+DebugAssertException: LazyAsyncResult#38580585::set_Result()
11:48:41 Called on completed result.
11:48:41    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
11:48:41    at System.Environment.get_StackTrace()
11:48:41    at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
11:48:41    at System.Net.GlobalLog.Assert(String message, String detailMessage)
11:48:41    at System.Net.GlobalLog.Assert(Boolean condition, String messageFormat, Object[] data)
11:48:41    at System.Net.LazyAsyncResult.set_Result(Object value)
11:48:41    at System.Net.Sockets.BaseOverlappedAsyncResult.CheckAsyncCallOverlappedResult(SocketError errorCode)
11:48:41    at System.Net.Sockets.Socket.DoBeginAccept(Socket acceptSocket, Int32 receiveSize, AcceptOverlappedAsyncResult asyncResult)
11:48:41    at System.Net.Sockets.Socket.BeginAccept(Socket acceptSocket, Int32 receiveSize, AsyncCallback callback, Object state)
11:48:41    at System.Net.Sockets.Socket.BeginAccept(Int32 receiveSize, AsyncCallback callback, Object state)
11:48:41    at System.Net.Sockets.Socket.BeginAccept(AsyncCallback callback, Object state)
11:48:41    at System.Net.Sockets.SocketTaskExtensions.<AcceptAsync>b__0(AsyncCallback callback, Object state)
11:48:41    at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
11:48:41    at System.Net.Sockets.SocketTaskExtensions.AcceptAsync(Socket socket)
11:48:41    at System.Net.Sockets.SocketAPMExtensions.BeginAccept(Socket socket, AsyncCallback callback, Object state)
11:48:41    at System.Net.Sockets.Tests.SocketTestServerAPM.OnAccept(IAsyncResult result)
11:48:41    at System.Threading.Tasks.TaskToApm.<>c__DisplayClass1.<InvokeCallbackWhenTaskCompletes>b__0()
11:48:41    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
11:48:41    at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
11:48:41    at System.Threading.Tasks.Task.FinishContinuations()
11:48:41    at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
11:48:41    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
11:48:41    at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
11:48:41    at System.Net.ContextAwareResult.CompleteCallback(Object state)
11:48:41    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
11:48:41    at System.Net.ContextAwareResult.Complete(IntPtr userToken)
11:48:41    at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
11:48:41    at System.Net.LazyAsyncResult.InvokeCallback(Object result)
11:48:41    at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError errorCode)
11:48:41    at System.Net.Sockets.AcceptOverlappedAsyncResult.CompletionCallback(Int32 acceptedFileDescriptor, Byte[] socketAddress, Int32 socketAddressLen, SocketError errorCode)
11:48:41    at System.Net.Sockets.SocketAsyncContext.AcceptOperation.InvokeCallback()
11:48:41    at System.Net.Sockets.SocketAsyncContext.AsyncOperation.<QueueCompletionCallback>b__26(Object o)
11:48:41    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
11:48:41    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
11:48:41    at System.Threading.ThreadPoolWorkQueue.Dispatch()
11:48:41    at System.Diagnostics.Debug.UnixDebugLogger.ShowAssertDialog(String stackTrace, String message, String detailMessage)
11:48:41    at System.Net.GlobalLog.Assert(String message, String detailMessage)
11:48:41    at System.Net.GlobalLog.Assert(Boolean condition, String messageFormat, Object[] data)
11:48:41    at System.Net.LazyAsyncResult.set_Result(Object value)
11:48:41    at System.Net.Sockets.BaseOverlappedAsyncResult.CheckAsyncCallOverlappedResult(SocketError errorCode)
11:48:41    at System.Net.Sockets.Socket.DoBeginAccept(Socket acceptSocket, Int32 receiveSize, AcceptOverlappedAsyncResult asyncResult)
11:48:41    at System.Net.Sockets.Socket.BeginAccept(Socket acceptSocket, Int32 receiveSize, AsyncCallback callback, Object state)
11:48:41    at System.Net.Sockets.Socket.BeginAccept(Int32 receiveSize, AsyncCallback callback, Object state)
11:48:41    at System.Net.Sockets.Socket.BeginAccept(AsyncCallback callback, Object state)
11:48:41    at System.Net.Sockets.SocketTaskExtensions.<AcceptAsync>b__0(AsyncCallback callback, Object state)
11:48:41    at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
11:48:41    at System.Net.Sockets.SocketTaskExtensions.AcceptAsync(Socket socket)
11:48:41    at System.Net.Sockets.SocketAPMExtensions.BeginAccept(Socket socket, AsyncCallback callback, Object state)
11:48:41    at System.Net.Sockets.Tests.SocketTestServerAPM.OnAccept(IAsyncResult result)
11:48:41    at System.Threading.Tasks.TaskToApm.<>c__DisplayClass1.<InvokeCallbackWhenTaskCompletes>b__0()
11:48:41    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
11:48:41    at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
11:48:41 --- End of stack trace from previous location where exception was thrown ---
11:48:41    at System.Threading.Tasks.AwaitTaskContinuation.<>c.<ThrowAsyncIfNecessary>b__18_0(Object s)
11:48:41    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
11:48:41    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
11:48:41    at System.Threading.ThreadPoolWorkQueue.Dispatch()
11:48:41 ./run-test.sh: line 130: 59247 Aborted                 (core dumped) ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory -notrait Benchmark=true
11:48:41 One or more tests failed while running tests from 'System.Net.Sockets.APMServer.Tests'.  Exit code 134.
```

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/4367/console
```
20:42:14 Unhandled Exception: System.Diagnostics.Debug+DebugAssertException: LazyAsyncResult#61940669::set_Result()
20:42:14 Called on completed result.
20:42:14    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
20:42:14    at System.Environment.get_StackTrace()
20:42:14    at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
20:42:14    at System.Net.GlobalLog.Assert(String message, String detailMessage)
20:42:14    at System.Net.GlobalLog.Assert(Boolean condition, String messageFormat, Object[] data)
20:42:14    at System.Net.LazyAsyncResult.set_Result(Object value)
20:42:14    at System.Net.Sockets.BaseOverlappedAsyncResult.CheckAsyncCallOverlappedResult(SocketError errorCode)
20:42:14    at System.Net.Sockets.Socket.DoBeginAccept(Socket acceptSocket, Int32 receiveSize, AcceptOverlappedAsyncResult asyncResult)
20:42:14    at System.Net.Sockets.Socket.BeginAccept(Socket acceptSocket, Int32 receiveSize, AsyncCallback callback, Object state)
20:42:14    at System.Net.Sockets.Socket.BeginAccept(Int32 receiveSize, AsyncCallback callback, Object state)
20:42:14    at System.Net.Sockets.Socket.BeginAccept(AsyncCallback callback, Object state)
20:42:14    at System.Net.Sockets.SocketTaskExtensions.<AcceptAsync>b__0(AsyncCallback callback, Object state)
20:42:14    at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
20:42:14    at System.Net.Sockets.SocketTaskExtensions.AcceptAsync(Socket socket)
20:42:14    at System.Net.Sockets.SocketAPMExtensions.BeginAccept(Socket socket, AsyncCallback callback, Object state)
20:42:14    at System.Net.Sockets.Tests.SocketTestServerAPM.OnAccept(IAsyncResult result)
20:42:14    at System.Threading.Tasks.TaskToApm.<>c__DisplayClass1.<InvokeCallbackWhenTaskCompletes>b__0()
20:42:14    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
20:42:14    at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
20:42:14    at System.Threading.Tasks.Task.FinishContinuations()
20:42:14    at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
20:42:14    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
20:42:14    at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
20:42:14    at System.Net.ContextAwareResult.CompleteCallback(Object state)
20:42:14    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
20:42:14    at System.Net.ContextAwareResult.Complete(IntPtr userToken)
20:42:14    at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
20:42:14    at System.Net.LazyAsyncResult.InvokeCallback(Object result)
20:42:14    at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError errorCode)
20:42:14    at System.Net.Sockets.AcceptOverlappedAsyncResult.CompletionCallback(Int32 acceptedFileDescriptor, Byte[] socketAddress, Int32 socketAddressLen, SocketError errorCode)
20:42:14    at System.Net.Sockets.SocketAsyncContext.AcceptOperation.InvokeCallback()
20:42:14    at System.Net.Sockets.SocketAsyncContext.AsyncOperation.<QueueCompletionCallback>b__26(Object o)
20:42:14    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
20:42:14    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
20:42:14    at System.Threading.ThreadPoolWorkQueue.Dispatch()
20:42:14    at System.Diagnostics.Debug.UnixDebugLogger.ShowAssertDialog(String stackTrace, String message, String detailMessage)
20:42:14    at System.Net.GlobalLog.Assert(String message, String detailMessage)
20:42:14    at System.Net.GlobalLog.Assert(Boolean condition, String messageFormat, Object[] data)
20:42:14    at System.Net.LazyAsyncResult.set_Result(Object value)
20:42:14    at System.Net.Sockets.BaseOverlappedAsyncResult.CheckAsyncCallOverlappedResult(SocketError errorCode)
20:42:14    at System.Net.Sockets.Socket.DoBeginAccept(Socket acceptSocket, Int32 receiveSize, AcceptOverlappedAsyncResult asyncResult)
20:42:14    at System.Net.Sockets.Socket.BeginAccept(Socket acceptSocket, Int32 receiveSize, AsyncCallback callback, Object state)
20:42:14    at System.Net.Sockets.Socket.BeginAccept(Int32 receiveSize, AsyncCallback callback, Object state)
20:42:14    at System.Net.Sockets.Socket.BeginAccept(AsyncCallback callback, Object state)
20:42:14    at System.Net.Sockets.SocketTaskExtensions.<AcceptAsync>b__0(AsyncCallback callback, Object state)
20:42:14    at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
20:42:14    at System.Net.Sockets.SocketTaskExtensions.AcceptAsync(Socket socket)
20:42:14    at System.Net.Sockets.SocketAPMExtensions.BeginAccept(Socket socket, AsyncCallback callback, Object state)
20:42:14    at System.Net.Sockets.Tests.SocketTestServerAPM.OnAccept(IAsyncResult result)
20:42:14    at System.Threading.Tasks.TaskToApm.<>c__DisplayClass1.<InvokeCallbackWhenTaskCompletes>b__0()
20:42:14    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
20:42:14    at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
20:42:14 --- End of stack trace from previous location where exception was thrown ---
20:42:14    at System.Threading.Tasks.AwaitTaskContinuation.<>c.<ThrowAsyncIfNecessary>b__18_0(Object s)
20:42:14    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
20:42:14    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
20:42:14    at System.Threading.ThreadPoolWorkQueue.Dispatch()
20:42:14 ./run-test.sh: line 130: 56346 Aborted                 (core dumped) ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait 
```

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst/1484/console

@pgavlin, are you able to investigate this one?

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst/1486/console

**Comment by pgavlin** [comment]
Looking into it. I believe that I've identified the issue and have a fix.
