### ISSUE TITLE
Linux System.Threading.Tasks.Dataflow.Tests failed

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#4453]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/4273/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8

13:34:51 === TEST EXECUTION SUMMARY ===
13:34:51    System.Runtime.Extensions.Tests  Total: 503, Errors: 0, Failed: 0, Skipped: 0, Time: 4.543s
13:34:53    System.Threading.Tasks.Dataflow.Tests.DebugAttributeTests.TestDebuggerDisplaysAndTypeProxies [FAIL]
13:34:53       System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
13:34:53       Stack Trace:
13:34:53             at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
13:34:53             at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
13:34:53             at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
13:34:53             at System.Threading.Tasks.Dataflow.BroadcastBlock`1.BroadcastingSourceCore`1.DebuggingInformation.get_InputQueue()
13:34:53             at System.Threading.Tasks.Dataflow.BroadcastBlock`1.DebugView.get_InputQueue()
13:34:59 Finished:    System.Numerics.Vectors.Tests
13:34:59 
13:34:59 === TEST EXECUTION SUMMARY ===
13:34:59    System.Numerics.Vectors.Tests  Total: 1058, Errors: 0, Failed: 0, Skipped: 0, Time: 12.685s
13:35:04 Finished:    System.Threading.Tasks.Dataflow.Tests
13:35:04 
13:35:04 === TEST EXECUTION SUMMARY ===
13:35:04    System.Threading.Tasks.Dataflow.Tests  Total: 282, Errors: 0, Failed: 1, Skipped: 0, Time: 17.754s
13:35:04 One or more tests failed while running tests from 'System.Threading.Tasks.Dataflow.Tests'.  Exit code 1.

**Comment by CIPop** [comment]
Failed while testing #4452.
