### ISSUE TITLE
Interop.Ssl.SslShutdown crashes process during GC finalization

### ISSUE THREAD

**Issue by roncain** [dotnet/corefx#4480]
A WCF test that attempts to write to an SslStream(https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs) leaves SafeSslHandle in a closed state (which is correct).  But when the next GC happens its finalizer is called and tries to Dispose it, causing an ObjectDisposedException.  On Linux, this crashes the process.

Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Ssl.SslShutdown(SafeSslHandle ssl)
   at Interop.OpenSsl.Disconnect(SafeSslHandle context)
   at System.Net.Security.SafeDeleteContext.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
   at System.Runtime.InteropServices.SafeHandle.Finalize()

**Comment by vijaykota** [comment]
cc: @rajansingh10 Please review the code if handles need to be invalidated in ReleaseHandle code path

**Comment by vijaykota** [comment]
Fix needs to be along the lines of PR #4534
