### ISSUE TITLE
sni.dll can't be loaded on Win 7/2008R2

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/corefx#4503]
This issue is not the same as [this one](https://github.com/dotnet/corefx/issues/3760) because I already have the C++ runtime installed.

We're seeing the issue while running the ASP.NET MusicStore sample automation on Win 7 and Win 2008 R2 but we don't know what's the root cause. Worth mentioning that the same code works on Win 8 and Win 10.

```
        System.Reflection.TargetInvocationException: Exception has been thr
own by the target of an invocation. ---> System.AggregateException: One or more
errors occurred. ---> System.DllNotFoundException: Unable to load DLL 'C:\Users\
victorhu\.dnx\packages\runtime.win7-x86.System.Data.SqlClient.sni\4.0.0-beta-235
09\runtimes\win7-x86\native\sni.dll': The specified module could not be found. (
Exception from HRESULT: 0x8007007E)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath
(String unmanagedDllPath)
   at System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(String
unmanagedDllPath)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadUnmanagedLibraryFromPath(Stri
ng path)
   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.LoadUnmanagedLibrary(St
ring name)
   at Microsoft.Dnx.Host.LoaderContainer.LoadUnmanagedLibrary(String name)
   at Microsoft.Dnx.Host.DefaultLoadContext.LoadUnmanagedLibrary(String name)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadUnmanagedDll(String unmanaged
DllName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unman
agedDllName, IntPtr gchManagedAssemblyLoadContext)
   at System.Data.SqlClient.SNINativeMethodWrapper.UnmanagedIsTokenRestricted(In
tPtr token, Boolean& isRestricted)
   at System.Data.Win32NativeMethods.IsTokenRestrictedWrapper(IntPtr token)
   at System.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent()
   at System.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnect
ionFactory connectionFactory)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnectio
n owningObject, DbConnectionPoolGroup connectionPoolGroup)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection
owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions
, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(Db
Connection outerConnection, DbConnectionFactory connectionFactory, TaskCompletio
nSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection
outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1
retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellati
onToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.Data.Entity.Storage.RelationalConnection.<OpenAsync>d__32.MoveNe
xt()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.Data.Entity.Storage.Internal.SqlServerDatabaseCreator.<ExistsAsy
nc>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.Data.Entity.Storage.RelationalDatabaseCreator.<EnsureCreatedAsyn
c>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MusicStore.Models.SampleData.<InitializeMusicStoreDatabaseAsync>d__3.MoveN
ext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at MusicStore.Startup.Configure(IApplicationBuilder app)
   at MusicStore.Startup.ConfigureDevelopment(IApplicationBuilder app, ILoggerFa
ctory loggerFactory)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec
t[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke
Attr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNet.Hosting.Startup.ConfigureBuilder.Invoke(Object instance,
IApplicationBuilder builder)
   at Microsoft.AspNet.Hosting.Startup.ConfigureBuilder.<>c__DisplayClass4_0.<Bu
ild>b__0(IApplicationBuilder builder)
   at Microsoft.AspNet.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__Di
splayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.BuildApplication()
```

The investigation that we did so far involved looking at the dependencies of `sni.dll` but there's nothing obviously wrong. Maybe someone with more experience in this area can identify something:

```
Dump of file C:\Users\victorhu\.dnx\packages\runtime.win7-x86.System.Data.SqlClient.sni\4.0.0-beta-23509\runtimes\win7-x86\native\sni.dll

File Type: DLL

  Image has the following dependencies:

    api-ms-win-core-processenvironment-l1-1-0.dll
    api-ms-win-core-file-l1-1-0.dll
    api-ms-win-core-debug-l1-1-0.dll
    api-ms-win-core-errorhandling-l1-1-0.dll
    api-ms-win-core-synch-l1-2-0.dll
    api-ms-win-core-interlocked-l1-1-0.dll
    api-ms-win-core-memory-l1-1-0.dll
    api-ms-win-core-libraryloader-l1-1-0.dll
    api-ms-win-core-string-obsolete-l1-1-0.dll
    api-ms-win-core-kernel32-legacy-l1-1-0.dll
    api-ms-win-core-registry-l1-1-0.dll
    api-ms-win-core-sysinfo-l1-2-0.dll
    api-ms-win-core-handle-l1-1-0.dll
    api-ms-win-core-io-l1-1-0.dll
    api-ms-win-core-synch-l1-1-0.dll
    api-ms-win-core-processthreads-l1-1-0.dll
    api-ms-win-core-sysinfo-l1-1-0.dll
    api-ms-win-core-timezone-l1-1-0.dll
    api-ms-win-core-stringansi-l1-1-0.dll
    api-ms-win-core-string-l1-1-0.dll
    api-ms-win-core-localization-obsolete-l1-2-0.dll
    api-ms-win-core-localization-l1-2-0.dll
    api-ms-win-security-base-l1-1-0.dll
    api-ms-win-core-namedpipe-l1-1-0.dll
    MSVCR110.dll
    KERNEL32.dll
    ADVAPI32.dll
    RPCRT4.dll
    WS2_32.dll
    CRYPT32.dll

  Summary

        4000 .data
       16000 .rdata
        6000 .reloc
        1000 .rsrc
        3000 .sdbid
       2C000 .text
```

To reproduce clone [MusicStore](https://github.com/aspnet/musicstore/tree/release) and run `build verify`

cc @divega

**Comment by divega** [comment]
@saurabh500 FYI

**Comment by saurabh500** [comment]
@victorhurdugaci Is there a sni.dll present at 
C:\Users\victorhu\.dnx\packages\runtime.win7-x86.System.Data.SqlClient.sni\4.0.0-beta-235
09\runtimes\win7-x86\native\sni.dll ?

**Comment by divega** [comment]
I can answer because I asked the same question: sni.dll is in the right place. It seems that there is a missing dependency that prevents sni.dll from being loaded, but the issue also seems to be different from #3760, i.e. we already tried installing the Visual C++ Redistributable for Visual Studio 2012 and it didn't help.

**Comment by ellismg** [comment]
@victorhurdugaci How exactly is this expected to fail?  When doing build.cmd verify on the dev branch (at aspnet/musicstore@5ddab1ffc8e89e34cd306b37887b85e03c7fdc76) I get five test failures, which all appear to be due to the server giving back an internal server error.

How I can see the break you are describing?  Do I just need to attach to some invocation of DNX?  If so, which one and what's the best way to run it?
