### ISSUE TITLE
"Unknown error 10058" caused crash in Sockets tests on OS X

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4563]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_mac_debug_tst/128/console
```
Unhandled Exception: System.Net.Sockets.SocketException: Unknown error: 10058
11:40:37    at System.Net.Sockets.Socket.Receive(IList`1 buffers, SocketFlags socketFlags)
11:40:37    at System.Net.Sockets.Tests.SendReceive.<>c__DisplayClassa.<SendRecv_Stream_TCP>b__9()
11:40:37    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
11:40:40 ./run-test.sh: line 130: 95631 Abort trap: 6           ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory -notrait Benchmark=true
11:40:40 One or more tests failed while running tests from 'System.Net.Sockets.APMServer.Tests'.  Exit code 134.
```

**Comment by stephentoub** [comment]
Same test failed here but with a different error:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/224/console
```
23:05:41 Unhandled Exception: System.Net.Sockets.SocketException: Unknown error: 10004
23:05:41    at System.Net.Sockets.Socket.Receive(IList`1 buffers, SocketFlags socketFlags)
23:05:41    at System.Net.Sockets.Tests.SendReceive.<>c__DisplayClass4_0.<SendRecv_Stream_TCP>b__0()
23:05:41    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
23:05:41 ./run-test.sh: line 130: 75419 Abort trap: 6           ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory -notrait Benchmark=true
```
