### ISSUE TITLE
Investigate why InnerExceptions for SNI SqlExceptions only have top line in stack trace

### ISSUE THREAD

**Issue by corivera** [dotnet/corefx#4622]

**Comment by corivera** [comment]
Example:

Caught Unexpected exception:System.Data.SqlClient.SqlException: A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught) ---
> System.InvalidOperationException: DEBUG TEST MESSAGE
   at System.Data.SqlClient.SNI.SNITCPHandle.EnableSsl(UInt32 options) in D:\gitDD\src\System.Data.SqlClient\src\System\Data\SqlClient\SNI\SNITcpHandle.cs:line 176
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) in D:\gitDD\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlInternalConnection.cs:line 247
...

**Comment by corivera** [comment]
@saurabh500

**Comment by corivera** [comment]
Seems like this is just default behavior with C#. The exception stack trace only includes data up to the catch point, since the stack trace string is built using local context. The final SqlExceptions are propagated up to the user, so they include the whole callstack.

I'll see if I can add in a manually created callstack to the exceptions.
