### ISSUE TITLE
System.Net.Sockets.Tests.ConnectExTest.Success failure on Linux

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#4628]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/4500/testReport/

Hit a failure in this test:
[System.Net.Sockets.Tests.ConnectExTest.Success](http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/4500/testReport/System.Net.Sockets.Tests/ConnectExTest/Success/)

Exception in question:
`System.Net.Sockets.SocketException : Unknown error 10048`
Seems to indicate a "Address In Use" error, so perhaps this is a timing issue from multiple tests trying to open the same socket, or something of the sort. I didn't see any other issues mentioning this so it may be very rare.

**Comment by nguerrera** [comment]
hitCount++ 

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/centos7.1_debug_tst_prtest/582/consoleFull#-1830000039a82fefab-f698-416f-8fca-58544c94cd4e

**Comment by ericeil** [comment]
Probably just an intermittent test issue; moving to RTM.

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_release_tst_prtest/1581/console
```
05:07:03    System.Net.Sockets.Tests.ConnectExTest.Success [FAIL]
05:07:03 
      System.Net.Sockets.SocketException : Unknown error 10048
05:07:03       Stack Trace:
05:07:04             at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
05:07:04             at System.Net.Sockets.Socket.Bind(EndPoint localEP)
05:07:04             at System.Net.Sockets.Tests.SocketTestServerAsync.Start(EndPoint localEndPoint)
05:07:04             at System.Net.Sockets.Tests.SocketTestServer.SocketTestServerFactory(SocketImplementationType type, Int32 numConnections, Int32 receiveBufferSize, EndPoint localEndPoint, ProtocolType protocolType)
05:07:04             at System.Net.Sockets.Tests.ConnectExTest.Success()
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_debug_tst/825/console
```
04:17:01    System.Net.Sockets.Tests.ConnectExTest.Success [FAIL]
04:17:01       System.Net.Sockets.SocketException : Address already in use
04:17:01       Stack Trace:
04:17:02             at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
04:17:02             at System.Net.Sockets.Socket.Bind(EndPoint localEP)
04:17:02             at System.Net.Sockets.Tests.SocketTestServerAsync.Start(EndPoint localEndPoint)
04:17:02             at System.Net.Sockets.Tests.SocketTestServerAsync..ctor(Int32 numConnections, Int32 receiveBufferSize, EndPoint localEndPoint, ProtocolType protocolType)
04:17:02             at System.Net.Sockets.Tests.SocketTestServer.SocketTestServerFactory(SocketImplementationType type, Int32 numConnections, Int32 receiveBufferSize, EndPoint localEndPoint, ProtocolType protocolType)
04:17:02             at System.Net.Sockets.Tests.SocketTestServer.SocketTestServerFactory(Int32 numConnections, Int32 receiveBufferSize, EndPoint localEndPoint, ProtocolType protocolType)
04:17:02             at System.Net.Sockets.Tests.SocketTestServer.SocketTestServerFactory(EndPoint endpoint, ProtocolType protocolType)
04:17:02             at System.Net.Sockets.Tests.ConnectExTest.Success()
```
(Now at least with a nicer error message after recent error handling changes :smile:)

**Comment by ericeil** [comment]
I'll take a look at this.
