### ISSUE TITLE
New Socket select tests failing on OS X, CentOS, openSUSE

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4665]
CentOS:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_centos71_debug_tst/157/console
```
20:09:40 terminate called after throwing an instance of 'PAL_SEHException'
20:09:40 ./run-test.sh: line 130: 59310 Aborted                 ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory -notrait Benchmark=true
20:09:40 One or more tests failed while running tests from 'System.Net.Sockets.APMServer.Tests'.  Exit code 134.
20:09:41    System.Net.Sockets.Tests.SelectAndPollTests.SelectWrite_Multiple_Mixed [FAIL]
20:09:41       Assert.Equal() Failure
20:09:41       Expected: 1
20:09:41       Actual:   0
20:09:41 terminate called after throwing an instance of 'PAL_SEHException'
20:09:41 ./run-test.sh: line 130: 59318 Aborted                 ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory -notrait Benchmark=true
20:09:41 One or more tests failed while running tests from 'System.Net.Sockets.AsyncServer.Tests'.  Exit code 134.
```

openSUSE
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_opensuse132_debug_tst/188/console
```
20:15:57 terminate called after throwing an instance of 'PAL_SEHException'
20:15:57 ./run-test.sh: line 130:  2689 Aborted                 ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory -notrait Benchmark=true
20:15:57 One or more tests failed while running tests from 'System.Net.Sockets.APMServer.Tests'.  Exit code 134.
20:15:57    System.Net.Sockets.Tests.SelectAndPollTests.SelectWrite_Multiple_Mixed [FAIL]
20:15:57       System.Net.Sockets.SocketException : Unknown error -1
20:15:57 terminate called after throwing an instance of 'PAL_SEHException'
20:15:57 ./run-test.sh: line 130:  2688 Aborted                 ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory -notrait Benchmark=true
20:15:57 One or more tests failed while running tests from 'System.Net.Sockets.AsyncServer.Tests'.  Exit code 134.
```

**Comment by stephentoub** [comment]
Also on OS X:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_mac_debug_tst/138/console
```
20:37:51    System.Net.Sockets.Tests.SelectAndPollTests.SelectRead_Multiple_Mixed [FAIL]
20:37:51       Assert.Equal() Failure
20:37:51       Expected: 1
20:37:51       Actual:   0
20:37:51       Stack Trace:
20:37:51             at System.Net.Sockets.Tests.SelectAndPollTests.SelectRead_Multiple_Mixed()
20:37:51    System.Net.Sockets.Tests.SelectAndPollTests.SelectRead_Single_Success [FAIL]
20:37:51       Assert.Equal() Failure
20:37:51       Expected: 1
20:37:51       Actual:   0
20:37:51       Stack Trace:
20:37:51             at System.Net.Sockets.Tests.SelectAndPollTests.SelectRead_Single_Success()
20:37:51    System.Net.Sockets.Tests.SelectAndPollTests.SelectWrite_Multiple_Mixed [FAIL]
20:37:51       Assert.Equal() Failure
20:37:51       Expected: 1
20:37:51       Actual:   0
20:37:51       Stack Trace:
20:37:51             at System.Net.Sockets.Tests.SelectAndPollTests.SelectWrite_Multiple_Mixed()
```
