### ISSUE TITLE
SignatureDecoder.DecodeMethodSignature throws `BadImageFormatException` when decoding method with `int, __arglist` parameters

### ISSUE THREAD

**Issue by conniey** [dotnet/corefx#4671]
A BadImageFormatException is thrown when using System.Reflection.Metadata to get method signature for `public static void ArglistMethod(int i, __arglist)`.

This behaviour worked in "1.1.0-alpha-00008".

## Version
__Branch__: `dev/metadata`
__Affected Package/Version__: "System.Reflection.Metadata": "1.2.0-alpha-00016"
## Repro Steps
1. Create library with the following code below.
2. Try to decode the method with: `SignatureDecoder.DecodeMethodSignature(memberReference.Signature, this)`
```csharp
public class TestClass
{
    public static void ArglistMethod(int i, __arglist)
    {
    }

    public static void Main(string[] args)
    {
        ArglistMethod(5, __arglist(1, 2, 3));
    }
}
```
## Expected
"M:TestClass.ArglistMethod(System.Int32,__arglist)"
## Actual
```
System.BadImageFormatException occurred
  HResult=-2147024885
  Message=Format of the executable (.exe) or library (.dll) is invalid.
  Source=System.Reflection.Metadata
  StackTrace:
       at System.Reflection.Metadata.Decoding.SignatureDecoder.DecodeType[TType](BlobReader& blobReader, Int32 typeCode, ISignatureTypeProvider`1 provider)
       at System.Reflection.Metadata.Decoding.SignatureDecoder.DecodeType[TType](BlobReader& blobReader, ISignatureTypeProvider`1 provider)
       at System.Reflection.Metadata.Decoding.SignatureDecoder.DecodeMethodSignature[TType](BlobReader& blobReader, ISignatureTypeProvider`1 provider)
       at System.Reflection.Metadata.Decoding.SignatureDecoder.DecodeMethodSignature[TType](BlobHandle handle, ISignatureTypeProvider`1 provider)
       at Microsoft.Fx.Portability.Analyzer.MemberMetadataInfoTypeProvider.GetMemberRefInfo(MemberReference memberReference) in E:\dotnet-apiport\src\Microsoft.Fx.Portability.MetadataReader\MemberMetadataInfoTypeProvider.cs:line 43
  InnerException: 
```

**Comment by conniey** [comment]
@nguerrera
