### ISSUE TITLE
SqlDataReader throws invalid operation exception

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#4676]
`System.Data.SqlDataReader` throws when it attempts to dispose

Using System.Data.SqlClient 4.0.0-rc2-23525 on OSX and Linux.

```
System.InvalidOperationException : Internal connection fatal error.
      Stack Trace:
           at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
           at System.Data.SqlClient.SqlDataReader.TryCloseInternal(Boolean closeReader)
           at System.Data.SqlClient.SqlDataReader.Close()
           at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
           at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
           at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
           at System.Data.SqlClient.SqlCommand.ExecuteReader()
```

Reproduces consistently when running [SqlServerDatabaseModelFactoryTest](https://github.com/aspnet/EntityFramework/blob/48e365d3433eef53b210a3f132676f1f1a1f1c4c/test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/SqlServerDatabaseModelFactoryTest.cs#L16) from Entity Framework against SQL 2014.

**Comment by natemcmaster** [comment]
cc @saurabh500

**Comment by saurabh500** [comment]
Cc @corivera

**Comment by corivera** [comment]
The Close() error here is due to packet data processing issues in a graceful close that was caused by a caught load-DLL exception (see PR above). Basically, the localization DLL issues throw an Exception, and when we catch this exception we try to do some cleanup & close on a DataReader. This throws another exception due to invalid packet data caused by the original DLL exception. Thus the true cause was being masked by this new "connection error" exception in SqlDataReader.Close().

**Comment by rohitshrivastava04** [comment]
@corivera could you please tell me is there any workaround for this issue, I am getting the same issue and I am using  "System.Data.SqlClient": "4.0.0-beta-23516".

My error log is 

    System.InvalidOperationException: Internal connection fatal error.
    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
    at System.Data.SqlClient.SqlDataReader.TryCloseInternal(Boolean closeReader)
    at System.Data.SqlClient.SqlDataReader.Close()
    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
    at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
    at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.<>c__DisplayClass17_0.<ExecuteReader>b__0(DbCommand cmd, IRelationalConnection con)
    at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.Execute[T](IRelationalConnection connection, Func`3 action, String executeMethod, Boolean openConnection, Boolean closeConnection)
    at Microsoft.Data.Entity.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
    at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    at Microsoft.Data.Entity.EnumerableExtensions.<Finally>d__0`1.MoveNext()
    at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    at Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
    at tesla.dataservice.Controllers.CurrencyController.Get()

**Comment by natemcmaster** [comment]
Thanks @corivera . The Entity Framework tests are now passing from OSX/Linux.

**Comment by yosigolan** [comment]
Hey.
until next milestone is released, is there any workaround currently?

Thanks Yosi
