### ISSUE TITLE
SelectRead_Multiple_Success failing in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4686]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_mac_debug_tst/140/console
```
04:51:52    System.Net.Sockets.Tests.SelectAndPollTests.SelectRead_Multiple_Success [FAIL]
04:51:52       Assert.Equal() Failure
04:51:52       Expected: 2
04:51:52       Actual:   1
04:51:52       Stack Trace:
04:51:52             at System.Net.Sockets.Tests.SelectAndPollTests.SelectRead_Multiple_Success()
```

**Comment by justinvp** [comment]
Also failed on Windows

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/6480/console

```
     System.Net.Sockets.Tests.SelectAndPollTests.SelectRead_Multiple_Success [FAIL]
        Assert.Equal() Failure
        Expected: 2
        Actual:   1
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets.Legacy\tests\FunctionalTests\SelectAndPollTests.cs(86,0): at System.Net.Sockets.Tests.SelectAndPollTests.SelectRead_Multiple_Success()
```

**Comment by justinvp** [comment]
This test is currently disabled on OS X. Does it need to be disabled on Windows as well?

**Comment by stephentoub** [comment]
It was failing consistently on OS X. If it fails again soon on Windows, we should disable it there as well.

**Comment by stephentoub** [comment]
Failed again on Windows:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release/1865/console
```
System.Net.Sockets.Tests.SelectAndPollTests.SelectRead_Multiple_Success [FAIL]
        Assert.Equal() Failure
        Expected: 2
        Actual:   1
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Net.Sockets.Legacy\tests\FunctionalTests\SelectAndPollTests.cs(87,0): at System.Net.Sockets.Tests.SelectAndPollTests.SelectRead_Multiple_Success()
```

cc: @CIPop, @davidsh, @pgavlin
