### ISSUE TITLE
GetAsync_ResponseHeadersRead_ReadFromEachIterativelyDoesntDeadlock failed on CentOS in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4801]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_centos71_debug_tst/166/console
```
07:38:26    System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_ResponseHeadersRead_ReadFromEachIterativelyDoesntDeadlock [FAIL]
07:38:26       System.Threading.Tasks.TaskCanceledException : A task was canceled.
07:38:26       Stack Trace:
07:38:27             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
07:38:27             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
07:38:27             at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
07:38:27             at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<GetAsync_ResponseHeadersRead_ReadFromEachIterativelyDoesntDeadlock>d__94.MoveNext()
07:38:27          --- End of stack trace from previous location where exception was thrown ---
07:38:27             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
07:38:27             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
07:38:27          --- End of stack trace from previous location where exception was thrown ---
07:38:27             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
07:38:27             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
07:38:27          --- End of stack trace from previous location where exception was thrown ---
07:38:27             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
07:38:27             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by stephentoub** [comment]
Same failure again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_centos71_debug_tst/167/console
```
09:10:48    System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_ResponseHeadersRead_ReadFromEachIterativelyDoesntDeadlock [FAIL]
09:10:48       System.Threading.Tasks.TaskCanceledException : A task was canceled.
09:10:48       Stack Trace:
09:10:48             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:10:48             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:10:48             at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
09:10:48             at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<GetAsync_ResponseHeadersRead_ReadFromEachIterativelyDoesntDeadlock>d__94.MoveNext()
09:10:48          --- End of stack trace from previous location where exception was thrown ---
09:10:48             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:10:48             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:10:48          --- End of stack trace from previous location where exception was thrown ---
09:10:48             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:10:48             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:10:48          --- End of stack trace from previous location where exception was thrown ---
09:10:48             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:10:48             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
