### ISSUE TITLE
SendToRecvFrom_Single_Datagram_UDP_IPv6 failed in CI on OS X

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4817]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/3/console
```
16:32:02    System.Net.Sockets.Tests.SendReceive.SendToRecvFrom_Single_Datagram_UDP_IPv6 [FAIL]
16:32:02       Assert.True() Failure
16:32:02       Expected: True
16:32:02       Actual:   False
16:32:02       Stack Trace:
16:32:02             at System.Net.Sockets.Tests.SendReceive.SendToRecvFrom_Datagram_UDP(IPAddress leftAddress, IPAddress rightAddress)
```

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/68/console
```
14:12:03    System.Net.Sockets.Tests.SendReceive.SendToRecvFrom_Single_Datagram_UDP_IPv6 [FAIL]
14:12:03       Assert.True() Failure
14:12:03       Expected: True
14:12:03       Actual:   False
14:12:03       Stack Trace:
14:12:03             at System.Net.Sockets.Tests.SendReceive.SendToRecvFrom_Datagram_UDP(IPAddress leftAddress, IPAddress rightAddress)
```
