### ISSUE TITLE
NameResolutionPalTests.GetHostByName_HostName failed on OS X in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4824]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/10/console
```
20:10:25    System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_HostName [FAIL]
20:10:25 
      System.Net.Internals.InternalSocketException : Unknown error: 11001
20:10:25       Stack Trace:
20:10:25             at System.Net.NameResolutionPal.GetHostByName(String hostName)
20:10:25             at System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_HostName()
```

**Comment by ericeil** [comment]
Looks like a simple DNS failure, probably due to infrastructure issues at the time.  Hasn't repro'd for a while, so I'll close this for now.
