### ISSUE TITLE
WatcherDoesntFollowSymLinkToFolder failed on OSX in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4856]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/50/console
```
11:48:22    CreatedTests.FileSystemWatcher_Created_WatcherDoesntFollowSymLinkToFolder [FAIL]
11:48:22       Didn't observe a symlink created event within 30000ms
11:48:22       Expected: True
11:48:22       Actual:   False
11:48:22       Stack Trace:
11:48:22             at Utility.ExpectEvent(WaitHandle eventOccurred, String eventName, Int32 timeout)
11:48:22             at CreatedTests.FileSystemWatcher_Created_WatcherDoesntFollowSymLinkToFolder()
```

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/6241
