### ISSUE TITLE
Process.Start throws weird error when command not found on Unix

### ISSUE THREAD

**Issue by anurse** [dotnet/corefx#4944]
I'm working on getting a narrower repro, but we're seeing strange behavior using Process.Start on Unix in dotnet-cli. As long as the command being launched exists, everything is fine, but when the executable cannot be found we get a strange error:

```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-localization-l1-2-0.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   at Interop.mincore.TryGetErrorMessage(Int32 errorCode, StringBuilder sb, String& errorMsg)
   at Interop.mincore.GetMessage(Int32 errorCode)
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

Part of narrowing down the repro will be making sure that this is not just a misconfiguration of dotnet-cli, but I'm pretty sure we're getting the right implementation of Process because it does correctly launch the process if the command exists.

Maybe this just didn't get abstracted properly?

/cc @piotrpMSFT @blackdwarf @davidfowl 

Related: dotnet/cli#118

**Comment by stephentoub** [comment]
> Maybe this just didn't get abstracted properly?

This isn't a problem with the Unix implementation.  If you look at the binary, e.g. http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug/lastSuccessfulBuild/artifact/bin/Linux.AnyCPU.Debug/System.Diagnostics.Process/ , ```mincore``` and these methods don't exist:
```
   at Interop.mincore.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   at Interop.mincore.TryGetErrorMessage(Int32 errorCode, StringBuilder sb, String& errorMsg)
   at Interop.mincore.GetMessage(Int32 errorCode)
```

**Comment by anurse** [comment]
Yeah, something seems strange here. I see the same with the version we're publishing. Maybe we're loading the wrong one... but that's the only file in the directory with the name System.Diagnostics.Process. I'll take a look at our config and see if I can nail this down.

**Comment by anurse** [comment]
Looks like we were on an old build or something. It's working now.
