### ISSUE TITLE
System.Net.Security.Unit.Tests:  Test failures with System.NotImplementedException : The method or operation is not implemented.

### ISSUE THREAD

**Issue by sejongoh** [dotnet/corefx#5037]
**Configuration**

 Debug CoreCLR runtime: coreclr.dll, corerun.exe and mscorlib.dll
 CoreFX assemblies and CoreFX tests: release

**Linux environment**

 Ubuntu 14.04 LTS on Hyper-V

 Run .run-test.sh **with sudo** to avoid a hang issue in #5025 

**Test names**
```
./bin/tests/Linux.AnyCPU.Release/System.Net.Security.Unit.Tests/dnxcore50/testResults.xml:      <test name="System.Net.Security.Tests.SslStreamAllowedProtocolsTest.SslStream_AuthenticateAsClient_None_Success" type="System.Net.Security.Tests.SslStreamAllowedProtocolsTest" method="SslStream_AuthenticateAsClient_None_Success" time="0.3541919" result="Fail">
./bin/tests/Linux.AnyCPU.Release/System.Net.Security.Unit.Tests/dnxcore50/testResults.xml:      <test name="System.Net.Security.Tests.SslStreamAllowedProtocolsTest.SslStream_AuthenticateAsClient_AllSupported_Success" type="System.Net.Security.Tests.SslStreamAllowedProtocolsTest" method="SslStream_AuthenticateAsClient_AllSupported_Success" time="0.0226192" result="Fail">
./bin/tests/Linux.AnyCPU.Release/System.Net.Security.Unit.Tests/dnxcore50/testResults.xml:      <test name="System.Net.Security.Tests.SslStreamAllowedProtocolsTest.SslStream_AuthenticateAsClient_Supported_Success(protocol: Tls)" type="System.Net.Security.Tests.SslStreamAllowedProtocolsTest" method="SslStream_AuthenticateAsClient_Supported_Success" time="0.0367535" result="Fail">
./bin/tests/Linux.AnyCPU.Release/System.Net.Security.Unit.Tests/dnxcore50/testResults.xml:      <test name="System.Net.Security.Tests.SslStreamAllowedProtocolsTest.SslStream_AuthenticateAsClient_Supported_Success(protocol: Tls11)" type="System.Net.Security.Tests.SslStreamAllowedProtocolsTest" method="SslStream_AuthenticateAsClient_Supported_Success" time="0.0204906" result="Fail">
./bin/tests/Linux.AnyCPU.Release/System.Net.Security.Unit.Tests/dnxcore50/testResults.xml:      <test name="System.Net.Security.Tests.SslStreamAllowedProtocolsTest.SslStream_AuthenticateAsClient_Supported_Success(protocol: Tls12)" type="System.Net.Security.Tests.SslStreamAllowedProtocolsTest" method="SslStream_AuthenticateAsClient_Supported_Success" time="0.0042644" result="Fail">
./bin/tests/Linux.AnyCPU.Release/System.Net.Security.Unit.Tests/dnxcore50/testResults.xml:      <test name="System.Net.Security.Tests.SslStreamAllowedProtocolsTest.SslStream_AuthenticateAsClient_Default_Success" type="System.Net.Security.Tests.SslStreamAllowedProtocolsTest" method="SslStream_AuthenticateAsClient_Default_Success" time="0.0217441" result="Fail">
```

**Stack trace**

```
<test name="System.Net.Security.Tests.SslStreamAllowedProtocolsTest.SslStream_AuthenticateAsClient_Supported_Success(protocol: Tls11)" type="System.Net.Security.Tests.SslStreamAllowedProtocolsTest" method="SslStream_AuthenticateAsClient_Supported_Success" time="0.0204906" result="Fail">
<failure exception-type="System.NotImplementedException">
  <message><![CDATA[System.NotImplementedException : The method or operation is not implemented.]]></message>
  <stack-trace><![CDATA[   at System.Net.Security.LazyAsyncResult.get_IsCompleted()
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at System.Net.Security.Tests.SslStreamAllowedProtocolsTest.<SslStream_AuthenticateAsClient_Supported_Success>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)]]></stack-trace>
</failure>
</test>
```

**Comment by davidsh** [comment]
cc: @CIPop @pgavlin

**Comment by CIPop** [comment]
@bartonjs @vijaykota @shrutigarg

**Comment by vijaykota** [comment]
cc: @shrutigarg , please look into this.

**Comment by vijaykota** [comment]
@eerhardt, have you seen any recent shimming related issues when running ./run-test.sh or using dnx for xplat HttpClient/SslStream?

**Comment by shrutigarg** [comment]
@sejongoh  @CIPop  Did you guys try to run these tests on windows too? I see the issue is not related to *NIX but the FakeLazyAsyncResult.cs implementation. I see the same failure when run on windows . I have a fix. Will send the PR .
