### ISSUE TITLE
System.Security.Cryptography.Algorithms.Tests:  Test failures with System.EntryPointNotFoundException : Unable to find an entry point named 'EvpDes3Cbc' in DLL 'System.Security.Cryptography.Native'

### ISSUE THREAD

**Issue by sejongoh** [dotnet/corefx#5038]
**Configuration**

 Debug CoreCLR runtime: coreclr.dll, corerun.exe and mscorlib.dll
 CoreFX assemblies and CoreFX tests: release

**Linux environment**

 Ubuntu 14.04 LTS on Hyper-V

 Run .run-test.sh **with sudo** to avoid a hang issue in #5025 

**Test names**
```
./bin/tests/Linux.AnyCPU.Release/System.Security.Cryptography.Algorithms.Tests/dnxcore50/testResults.xml:      <test name="System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDesTests.TripleDesCreate" type="System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDesTests" method="TripleDesCreate" time="0.3054654" result="Fail">
./bin/tests/Linux.AnyCPU.Release/System.Security.Cryptography.Algorithms.Tests/dnxcore50/testResults.xml:      <test name="System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESReusabilityTests.TripleDESReuseEncryptorDecryptor" type="System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESReusabilityTests" method="TripleDESReuseEncryptorDecryptor" time="0.7361716" result="Fail">
./bin/tests/Linux.AnyCPU.Release/System.Security.Cryptography.Algorithms.Tests/dnxcore50/testResults.xml:      <test name="System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESCipherTests.TripleDESRoundTrip192BitsPKCS7ECB" type="System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESCipherTests" method="TripleDESRoundTrip192BitsPKCS7ECB" time="0.0327606" result="Fail">
./bin/tests/Linux.AnyCPU.Release/System.Security.Cryptography.Algorithms.Tests/dnxcore50/testResults.xml:      <test name="System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESCipherTests.TripleDESRoundTrip192BitsZerosCBC" type="System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESCipherTests" method="TripleDESRoundTrip192BitsZerosCBC" time="0.0289695" result="Fail">
./bin/tests/Linux.AnyCPU.Release/System.Security.Cryptography.Algorithms.Tests/dnxcore50/testResults.xml:      <test name="System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESCipherTests.TripleDESRoundTrip192BitsNoneCBC" type="System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESCipherTests" method="TripleDESRoundTrip192BitsNoneCBC" time="0.0508849" result="Fail">
./bin/tests/Linux.AnyCPU.Release/System.Security.Cryptography.Algorithms.Tests/dnxcore50/testResults.xml:      <test name="System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESCipherTests.TripleDESRoundTrip192BitsZerosECB" type="System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESCipherTests" method="TripleDESRoundTrip192BitsZerosECB" time="0.0506205" result="Fail">
./bin/tests/Linux.AnyCPU.Release/System.Security.Cryptography.Algorithms.Tests/dnxcore50/testResults.xml:      <test name="System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESCipherTests.TripleDESRoundTrip192BitsPKCS7CBC" type="System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESCipherTests" method="TripleDESRoundTrip192BitsPKCS7CBC" time="0.0390693" result="Fail">
./bin/tests/Linux.AnyCPU.Release/System.Security.Cryptography.Algorithms.Tests/dnxcore50/testResults.xml:      <test name="System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESCipherTests.TripleDESRoundTrip192BitsNoneECB" type="System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESCipherTests" method="TripleDESRoundTrip192BitsNoneECB" time="0.0405184" result="Fail">	  
```	  

**Stack trace**

```
<test name="System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDesTests.TripleDesCreate" type="System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDesTests" method="TripleDesCreate" time="0.3054654" result="Fail">
<failure exception-type="System.EntryPointNotFoundException">
  <message><![CDATA[System.EntryPointNotFoundException : Unable to find an entry point named 'EvpDes3Cbc' in DLL 'System.Security.Cryptography.Native'.]]></message>
  <stack-trace><![CDATA[   at Interop.Crypto.EvpDes3Cbc()
    at Internal.Cryptography.TripleDesOpenSslCipher.OpenKey(CipherMode cipherMode, Byte[] key)
    at Internal.Cryptography.TripleDesImplementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)
    at System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDesTests.TripleDesCreate()]]></stack-trace>
</failure>
</test>
```

**Comment by bartonjs** [comment]
@sejongoh It sounds like you didn't copy ./bin/Linux.x64.Release/Native/System.Security.Cryptography.Native.so to the same location(s) as libcoreclr.so, and so you're running with an older native shim.

**Comment by bartonjs** [comment]
@sejongoh Since this sounds like you just have an inconsistent local state, I'm going to go ahead and close this.  If `./build.sh native` and copying the updated Native binaries doesn't solve your problem (or you run into further complications) please re-activate and let us know what's going on.

**Comment by sejongoh** [comment]
Thank you for the update. The test passes after updating System.Security.Cryptography.Native.so.
