### ISSUE TITLE
Timeout Error on Conn.Open() for TDS Version 7.3 and below

### ISSUE THREAD

**Issue by kkurni** [dotnet/corefx#5058]
Timeout Error on Conn.Open() for 
TDS Version 7.3 and below
or 
SQL Server 2008 and below

Here error message 
==================

      System.Data.SqlClient.SqlException : Connection Timeout Expired.  The timeout period elapsed during the post-login phase.  The connection could have timed out while waiting for server to complete the login process and respond; Or it could have timed out while attempting to create multiple active connections.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=33; handshake=433; [Login] initialization=0; authentication=0; [Post-Login] complete=29018;
      ---- System.ComponentModel.Win32Exception : Unknown error 258
      Stack Trace:
            at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
            at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
            at System.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
            at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
            at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
            at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
            at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
            at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
            at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
            at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
            at System.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
            at System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
            at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, TimeoutTimer timeout)
            at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, Boolean redirectedUserInstance)
            at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData)
            at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
            at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
            at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
            at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
            at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
            at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
            at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
            at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
            at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
            at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
            at System.Data.SqlClient.SqlConnection.Open()
            at Suites.Data.Test.ExceptionTest.TestConnectionString(String connstr)
            at Suites.Data.Test.ExceptionTest.TestConnectionString()
         ----- Inner Stack Trace -----

**Comment by kkurni** [comment]
cc @saurabh500 @corivera

**Comment by kkurni** [comment]
This Happen, when Client send Login7 Package with SSL Stream and The server just didn't response.
(Complete Login - Timeout)

- Switch the port to check whether this is a firewall issue. Still doesn't work for TDS 7.3 in Unix
- Checked all data packet and all are exactly the same as windows

- The only suspicious is the TLS, But I do check it seems TLS Stream works If I have another listener on windows and communicate through UNIX
In Unix, it send as TLS Rec Layer 2, which seems to be different than in Windows.
But for TDS 7.4 this works fine in UNIX.

**Comment by kkurni** [comment]
If I send Login7 Without TLS, this will not be an issue anymore. But we still do need to send login7 packet with TLS protocol.

So this is conclude that there is a problem with TLS protocol in UNIX specifically version 1.0.

I do notice there are couple different than windows the way how it send data in TLS 1.0 for unix.
- Send with additional 32 bytes of application data.
https://github.com/dotnet/corefx/issues/5187

- Client Hello - send with different version between outer and inner data which may violate the protocol
https://github.com/dotnet/corefx/issues/5178

**Comment by kkurni** [comment]
I am closing this as this is expected behavior as as TLS 1.0 in Unix send a split bytes to mitigate Beast Security Vulnerability. http://blogs.msdn.com/b/kaushal/archive/2012/01/21/fixing-the-beast.aspx

Workaround: 
Install a patch on  SQL Server 2008 by https://support.microsoft.com/en-us/kb/2653857. 

Refer to https://github.com/dotnet/corefx/issues/5187 for more detail.


Thanks to @ericl85 for finding this information.
