### ISSUE TITLE
System.Collections.Generic: HashSet constructor throwing when passed another HashSet

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#5130]
The constructor for HashSet that takes an IEnumerable is throwing an unexpected exception when passed another HashSet.

repro test added to System.Collections test proj:
```
[Fact]
public void CopyConstructor()
{
    HashSet<T> set = new HashSet<T>();
    HashSet<T> set2 = new HashSet<T>(set); // throws NullReferenceException
}
```

Stack trace:
```
    System.Collections.Tests.HashSet_Generic_Tests_int.CopyConstructor [FAIL]
       System.NullReferenceException : Object reference not set to an instance of an object.
       Stack Trace:
          D:\git\corefx\src\system.collections\src\System\Collections\Generic\HashSet.cs(118,0): at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
          D:\git\corefx\src\system.collections\src\System\Collections\Generic\HashSet.cs(96,0): at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection)
          D:\git\corefx\src\system.collections\tests\Generic\HashSet\HashSet.Generic.Tests.cs(39,0): at System.Collections.Tests.HashSet_Generic_Tests`1.CopyConstructor()
```

The throwing code was introduced in #4349 by Toni Petrina and is snippeted here:
```
...
 var otherAsHashSet = collection as HashSet<T>;
            if (otherAsHashSet != null && AreEqualityComparersEqual(this, otherAsHashSet))
            {
                _buckets = (int[])otherAsHashSet._buckets.Clone(); // THROWS
                _slots = (Slot[])otherAsHashSet._slots.Clone();
...
```

Note that it doesn't fail when using the System.Collections.dll in 4.0.11-rc2-23616.

**Comment by i3arnon** [comment]
It only throws when it's passed an empty `HashSet` that didn't initialize its buckets yet, right?

**Comment by JonHanna** [comment]
Yes, it's only happening when the source is freshly minted, as it treats the memoised buckets and slots as invariantly non-null.
