### ISSUE TITLE
UDP tests fail with invalid checksum

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#5234]
```
System.Net.Sockets.Tests.SendReceive.SendToRecvFromAsync_Single_Datagram_UDP_IPv4 [FAIL]
11:27:58         Assert.Equal() Failure
11:27:58         Expected: 0
11:27:58         Actual:   1161193313
11:27:58         Stack Trace:
11:27:58            d:\j\workspace\dotnet_corefx\windows_nt_release_prtest\src\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs(121,0): at System.Net.Sockets.Tests.SendReceive.SendToRecvFromAsync_Datagram_UDP(IPAddress leftAddress, IPAddress rightAddress)
```

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_release_prtest/682/console

**Comment by nguerrera** [comment]
Again, this time in IPv6 

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_release_prtest/688/console

```
System.Net.Sockets.Tests.SendReceive.SendToRecvFromAsync_Single_Datagram_UDP_IPv6 [FAIL]
13:33:14         Assert.Equal() Failure
13:33:14         Expected: 0
13:33:14         Actual:   1115617513
```

**Comment by SidharthNabar** [comment]
Need to investigate this test - this seems to be a test setup/infra issue, hence moving to RTM milestone.

**Comment by CIPop** [comment]
The expected check-sum (0) is most likely invalid which could indicate a race condition or index mismatch within `SendToRecvFromAsync_Datagram_UDP`.
Tentatively setting the test-bug label.

**Comment by stephentoub** [comment]
Again here: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/opensuse13.2_debug_tst_prtest/584/console
```
09:50:54    System.Net.Sockets.Tests.SendReceive.SendToRecvFromAsync_Single_Datagram_UDP_IPv6 [FAIL]
09:50:54       Assert.Equal() Failure
09:50:54       Expected: 0
09:50:54       Actual:   424122691
09:50:54       Stack Trace:
09:50:55             at System.Net.Sockets.Tests.SendReceive.SendToRecvFromAsync_Datagram_UDP(IPAddress leftAddress, IPAddress rightAddress)
09:50:55             at System.Net.Sockets.Tests.SendReceive.SendToRecvFromAsync_Single_Datagram_UDP_IPv6()
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/opensuse13.2_debug_tst_prtest/804/console
```
11:43:03    System.Net.Sockets.Tests.SendReceive.SendToRecvFromAsync_Single_Datagram_UDP_IPv6 [FAIL]
11:43:03       Assert.Equal() Failure
11:43:03       Expected: 0
11:43:03       Actual:   1669125329
11:43:03       Stack Trace:
11:43:04             at System.Net.Sockets.Tests.SendReceive.SendToRecvFromAsync_Datagram_UDP(IPAddress leftAddress, IPAddress rightAddress)
11:43:04             at System.Net.Sockets.Tests.SendReceive.SendToRecvFromAsync_Single_Datagram_UDP_IPv6()
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_debug_tst_prtest/2063/console
