### ISSUE TITLE
SendReceive.SendRecvAsync_TcpListener_TcpClient_IPv4 failed in CI on CentOS

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5246]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/centos7.1_debug_tst_prtest/608/console
```
05:24:14    System.Net.Sockets.Tests.SendReceive.SendRecvAsync_TcpListener_TcpClient_IPv4 [FAIL]
05:24:14       Assert.True() Failure
05:24:14       Expected: True
05:24:14       Actual:   False
05:24:14       Stack Trace:
05:24:14             at System.Net.Sockets.Tests.SendReceive.SendRecvAsync_TcpListener_TcpClient(IPAddress listenAt)
05:24:14             at System.Net.Sockets.Tests.SendReceive.SendRecvAsync_TcpListener_TcpClient_IPv4()
05:24:15 
05:24:15 Unhandled Exception: Xunit.Sdk.TrueException: Assert.True() Failure
05:24:15 Expected: True
05:24:15 Actual:   False
05:24:15    at Xunit.Assert.True(Nullable`1 condition, String userMessage)
05:24:15    at System.Net.Sockets.Tests.SendReceive.<>c__DisplayClass2_0.<SendToRecvFromAsync_Datagram_UDP>b__1(Int32 sent)
05:24:15    at System.Net.Sockets.Tests.SocketAsyncExtensions.<>c__DisplayClass7_0.<SendToAsync>b__0(Object _, SocketAsyncEventArgs args)
05:24:15    at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
05:24:15    at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object ignored)
05:24:15    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
05:24:15    at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
05:24:15    at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketError socketError)
05:24:15    at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallback(Int32 bytesTransferred, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError socketError)
05:24:15    at System.Net.Sockets.SocketAsyncContext.<>c.<SendToAsync>b__48_0(Object args)
05:24:15    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
05:24:15    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
05:24:15    at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
cc: @pgavlin, @ericeil, @cipop

**Comment by stephentoub** [comment]
Failed again here:
```
13:26:22 Unhandled Exception: Xunit.Sdk.TrueException: Assert.True() Failure
13:26:22 Expected: True
13:26:22 Actual:   False
13:26:22    at Xunit.Assert.True(Nullable`1 condition, String userMessage)
13:26:22    at System.Net.Sockets.Tests.SendReceive.<>c__DisplayClass2_0.<SendToRecvFromAsync_Datagram_UDP>b__1(Int32 sent)
13:26:22    at System.Net.Sockets.Tests.SocketAsyncExtensions.<>c__DisplayClass7_0.<SendToAsync>b__0(Object _, SocketAsyncEventArgs args)
13:26:22    at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
13:26:22    at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
13:26:22    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
13:26:22    at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
13:26:22    at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketError socketError)
13:26:22    at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallback(Int32 bytesTransferred, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError socketError)
13:26:22    at System.Net.Sockets.SocketAsyncContext.<>c.<SendToAsync>b__48_0(Object args)
13:26:22    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
13:26:22    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
13:26:22    at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by ericeil** [comment]
This looks like a datagram got lost, which is perfectly legal, but should be rare on loopback.  Making the test robust to this will take some doing.  I'm going to postpone this to "future;" if this comes up a lot, we can fix it sooner.

**Comment by ericeil** [comment]
This is covered by #5185
