### ISSUE TITLE
NegotiateStream tests: Unable to read data from the transport connection: Queue empty

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5284]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/772/consoleFull
```
06:00:09      System.Net.Security.Tests.NegotiateStreamStreamToStreamTest.NegotiateStream_StreamToStream_Successive_ClientWrite_Async_Success [FAIL]
06:00:09         System.AggregateException : One or more errors occurred.
06:00:09         ---- System.IO.IOException : Unable to read data from the transport connection: Queue empty..
06:00:09         -------- System.InvalidOperationException : Queue empty.
06:00:09         Stack Trace:
06:00:09               at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
06:00:09               at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
06:00:09            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Security\tests\FunctionalTests\NegotiateStreamStreamToStreamTest.cs(240,0): at System.Net.Security.Tests.NegotiateStreamStreamToStreamTest.NegotiateStream_StreamToStream_Successive_ClientWrite_Async_Success()
06:00:09            ----- Inner Stack Trace -----
06:00:09            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Security\src\System\Net\SecureProtocols\NegoState.Windows.cs(447,0): at System.Net.Security.NegoState.EndProcessAuthentication(IAsyncResult result)
06:00:09            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Security\src\System\Net\SecureProtocols\NegotiateStream.cs(114,0): at System.Net.Security.NegotiateStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
06:00:09               at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
06:00:09            ----- Inner Stack Trace -----
06:00:09               at System.Collections.Generic.Queue`1.Dequeue()
06:00:09            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Security\tests\FunctionalTests\MockNetwork.cs(34,0): at System.Net.Security.Tests.MockNetwork.ReadFrame(Boolean server, Byte[]& buffer)
06:00:09            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Security\tests\FunctionalTests\FakeNetworkStream.cs(102,0): at System.Net.Security.Tests.FakeNetworkStream.UpdateReadStream()
06:00:09            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Security\tests\FunctionalTests\FakeNetworkStream.cs(82,0): at System.Net.Security.Tests.FakeNetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
06:00:09            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\Common\src\System\IO\StreamAsyncHelper.cs(74,0): at System.IO.StreamAsyncHelper.<>c.<BeginReadWrite>b__7_0(Object obj)
06:00:09               at System.Threading.Tasks.Task`1.InnerInvoke()
06:00:09   System.Numerics.Vectors.Tests -> d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\bin\Windows_NT.AnyCPU.Debug\System.Numerics.Vectors.Tests\System.Numerics.Vectors.Tests.dll
06:00:09               at System.Threading.Tasks.Task.Execute()
06:00:09            --- End of stack trace from previous location where exception was thrown ---
06:00:09               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
06:00:09               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
06:00:09               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
06:00:09            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\Common\src\System\IO\StreamAsyncHelper.cs(133,0): at System.IO.StreamAsyncHelper.EndRead(IAsyncResult asyncResult)
06:00:09            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Security\src\System\Net\StreamFramer.cs(205,0): at System.Net.StreamFramer.ReadFrameComplete(IAsyncResult transportResult)
06:00:09            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Security\src\System\Net\StreamFramer.cs(169,0): at System.Net.StreamFramer.ReadFrameCallback(IAsyncResult transportResult)
```

**Comment by CIPop** [comment]
See #4467 for details of this investigation and fix.
