### ISSUE TITLE
CertificateValidationRemoteServer_EndToEnd_Ok failed in CI on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5297]
A bunch of occurrences of this over the past day:
```
04:09:01      System.Net.Security.Tests.CertificateValidationRemoteServer.CertificateValidationRemoteServer_EndToEnd_Ok [FAIL]
04:09:01         System.Net.Internals.InternalSocketException : No such host is known
04:09:01         Stack Trace:
04:09:01               at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
04:09:01               at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
04:09:01               at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
04:09:01            --- End of stack trace from previous location where exception was thrown ---
04:09:01               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
04:09:01               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
04:09:01               at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
04:09:01            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Security\tests\FunctionalTests\CertificateValidationRemoteServer.cs(19,0): at System.Net.Security.Tests.CertificateValidationRemoteServer.<CertificateValidationRemoteServer_EndToEnd_Ok>d__0.MoveNext()
04:09:01            --- End of stack trace from previous location where exception was thrown ---
04:09:01               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
04:09:01               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
04:09:01            --- End of stack trace from previous location where exception was thrown ---
04:09:01               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
04:09:01               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
04:09:01            --- End of stack trace from previous location where exception was thrown ---
04:09:01               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
04:09:01               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/791/consoleFull
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/787/consoleFull
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_release_prtest/790/consoleFull

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/793/consoleFull
and here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_release_prtest/798/consoleFull
