### ISSUE TITLE
FileSystemWatcher_Moved_NestedDirectoryRootWithoutSubdirectoriesFlag failed with UnauthorizedAccessException on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5306]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_release/222/consoleFull
```
08:50:59      RenamedTests.FileSystemWatcher_Moved_NestedDirectoryRootWithoutSubdirectoriesFlag [FAIL]
08:50:59         System.UnauthorizedAccessException : Access to the path '\\?\d:\j\workspace\dotnet_corefx\windows_nt_release\bin\tests\Windows_NT.AnyCPU.Release\System.IO.FileSystem.Watcher.Tests\dnxcore50\FileSystemWatcher_Moved_NestedDirectoryRootWithoutSubdirectoriesFlag\test_root' is denied.
08:50:59         Stack Trace:
08:51:00            d:\j\workspace\dotnet_corefx\windows_nt_release\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs(627,0): at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
08:51:00            d:\j\workspace\dotnet_corefx\windows_nt_release\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs(493,0): at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
08:51:00            d:\j\workspace\dotnet_corefx\windows_nt_release\src\System.IO.FileSystem.Watcher\tests\Utility\TemporaryTestDirectory.cs(32,0): at TemporaryTestDirectory.Dispose()
08:51:00            d:\j\workspace\dotnet_corefx\windows_nt_release\src\System.IO.FileSystem.Watcher\tests\FileSystemWatcher.Renamed.cs(166,0): at RenamedTests.FileSystemWatcher_Moved_NestedDirectoryRootWithoutSubdirectoriesFlag()
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/809/consoleFull

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_release_prtest/3040/consoleFull
```
09:28:26      RenamedTests.FileSystemWatcher_Moved_NestedDirectoryRootWithoutSubdirectoriesFlag [FAIL]
09:28:26         System.UnauthorizedAccessException : Access to the path '\\?\d:\j\workspace\windows_nt_re---5067c899\bin\tests\Windows_NT.AnyCPU.Release\System.IO.FileSystem.Watcher.Tests\dnxcore50\FileSystemWatcher_Moved_NestedDirectoryRootWithoutSubdirectoriesFlag\test_root' is denied.
09:28:26         Stack Trace:
09:28:26               at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
09:28:26               at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
09:28:26            d:\j\workspace\windows_nt_re---5067c899\src\System.IO.FileSystem.Watcher\tests\Utility\TemporaryTestDirectory.cs(33,0): at TemporaryTestDirectory.Dispose()
09:28:26            d:\j\workspace\windows_nt_re---5067c899\src\System.IO.FileSystem.Watcher\tests\FileSystemWatcher.Renamed.cs(167,0): at RenamedTests.FileSystemWatcher_Moved_NestedDirectoryRootWithoutSubdirectoriesFlag()
```

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_release_prtest/3218/consoleFull
```
04:52:25      RenamedTests.FileSystemWatcher_Moved_NestedDirectoryRootWithoutSubdirectoriesFlag [FAIL]
04:52:25         System.UnauthorizedAccessException : Access to the path '\\?\d:\j\workspace\windows_nt_re---5067c899\bin\tests\Windows_NT.AnyCPU.Release\System.IO.FileSystem.Watcher.Tests\dnxcore50\FileSystemWatcher_Moved_NestedDirectoryRootWithoutSubdirectoriesFlag\test_root' is denied.
04:52:25         Stack Trace:
04:52:25               at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
04:52:25               at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
04:52:25            d:\j\workspace\windows_nt_re---5067c899\src\System.IO.FileSystem.Watcher\tests\Utility\TemporaryTestDirectory.cs(33,0): at TemporaryTestDirectory.Dispose()
04:52:25            d:\j\workspace\windows_nt_re---5067c899\src\System.IO.FileSystem.Watcher\tests\FileSystemWatcher.Renamed.cs(167,0): at RenamedTests.FileSystemWatcher_Moved_NestedDirectoryRootWithoutSubdirectoriesFlag()
```

**Comment by jasonwilliams200OK** [comment]
For force deletion; will it be a good idea to implement a fallback functionality which would release all handles (help by any process), in case files/folders in question are in use, and retry deletion? Something like this solution: http://stackoverflow.com/a/4597225. Windows users have been using file/directory unlocker utilities for a long time to workaround "can't force delete the files" problem, which probably use similar kind of low-level implementation. IMO, it would be a nice API addition. :)

**Comment by ianhays** [comment]
I haven't looked into detail on this test failure yet but one thing that strikes me is that the test file isn't in the temp folder. If that's the case for multiple FSWatcher test then it's likely they're interfering with each other's execution.

>For force deletion; will it be a good idea to implement a fallback functionality which would release all handles (help by any process), in case files/folders in question are in use, and retry deletion
>IMO, it would be a nice API addition. :)

[Propose an API for it :)](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/Documentation/project-docs/api-review-process.md) It would have to be separate from the existing deletions of course but I could definitely see the use for a <i>yes-i-really-mean-delete</i>. One of my most frequent frustrations with Windows is working around the file-in-use problem
