### ISSUE TITLE
Circular reference for System.Security.Cryptography.X509Certificates

### ISSUE THREAD

**Issue by andschwa** [dotnet/corefx#5317]
My `project.json`

```json
{
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": {
        "System.Security.Cryptography.X509Certificates": "4.0.0-rc2-23707",
    },

    "frameworks": { "dnxcore50": { } }
}
```

```
$ dotnet restore --no-cache

Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16231

  GET https://www.myget.org/F/dotnet-core/
  OK https://www.myget.org/F/dotnet-core/ 1058ms
  GET https://www.nuget.org/api/v2/
  OK https://www.nuget.org/api/v2/ 302ms
Restoring packages for /home/andrew/algorithm-repro/project.json
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Security.Cryptography.X509Certificates'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Security.Cryptography.X509Certificates'
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Security.Cryptography.X509Certificates' 341ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Security.Cryptography.X509Certificates' 1200ms
  GET https://www.myget.org/F/dotnet-core/api/v2/package/System.Security.Cryptography.X509Certificates/4.0.0-rc2-23707
  OK https://www.myget.org/F/dotnet-core/api/v2/package/System.Security.Cryptography.X509Certificates/4.0.0-rc2-23707 2791ms
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Runtime'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Runtime.Handles'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Handles'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Security.Cryptography.Algorithms'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Security.Cryptography.Algorithms'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Security.Cryptography.Encoding'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Security.Cryptography.Encoding'
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Security.Cryptography.Encoding' 298ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Security.Cryptography.Algorithms' 300ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Handles' 308ms
  GET https://www.nuget.org/api/v2/package/System.Runtime.Handles/4.0.0
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime' 322ms
  GET https://www.nuget.org/api/v2/package/System.Runtime/4.0.0
  OK https://www.nuget.org/api/v2/package/System.Runtime.Handles/4.0.0 106ms
  OK https://www.nuget.org/api/v2/package/System.Runtime/4.0.0 148ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Runtime' 728ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Security.Cryptography.Encoding' 1271ms
  GET https://www.myget.org/F/dotnet-core/api/v2/package/System.Security.Cryptography.Encoding/4.0.0-rc2-23707
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Security.Cryptography.Algorithms' 1340ms
  GET https://www.myget.org/F/dotnet-core/api/v2/package/System.Security.Cryptography.Algorithms/4.0.0-rc2-23707
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Runtime.Handles' 1423ms
  OK https://www.myget.org/F/dotnet-core/api/v2/package/System.Security.Cryptography.Algorithms/4.0.0-rc2-23707 1185ms
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.IO'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Security.Cryptography.Primitives'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Security.Cryptography.Primitives'
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Security.Cryptography.Primitives' 277ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO' 292ms
  GET https://www.nuget.org/api/v2/package/System.IO/4.0.0
  OK https://www.nuget.org/api/v2/package/System.IO/4.0.0 137ms
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Text.Encoding'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Text.Encoding'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Threading.Tasks'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Threading.Tasks'
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Text.Encoding' 83ms
  GET https://www.nuget.org/api/v2/package/System.Text.Encoding/4.0.0
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Threading.Tasks' 92ms
  GET https://www.nuget.org/api/v2/package/System.Threading.Tasks/4.0.0
  OK https://www.nuget.org/api/v2/package/System.Text.Encoding/4.0.0 100ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Security.Cryptography.Primitives' 625ms
  OK https://www.nuget.org/api/v2/package/System.Threading.Tasks/4.0.0 111ms
  GET https://www.myget.org/F/dotnet-core/api/v2/package/System.Security.Cryptography.Primitives/4.0.0-rc2-23707
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.IO' 803ms
  OK https://www.myget.org/F/dotnet-core/api/v2/package/System.Security.Cryptography.Encoding/4.0.0-rc2-23707 2073ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Threading.Tasks' 621ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Text.Encoding' 626ms
  OK https://www.myget.org/F/dotnet-core/api/v2/package/System.Security.Cryptography.Primitives/4.0.0-rc2-23707 2312ms
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Diagnostics.Debug'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Diagnostics.Debug'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Globalization'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Globalization'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Resources.ResourceManager'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Resources.ResourceManager'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Threading'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Threading'
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Resources.ResourceManager' 288ms
  GET https://www.nuget.org/api/v2/package/System.Resources.ResourceManager/4.0.0
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Diagnostics.Debug' 298ms
  GET https://www.nuget.org/api/v2/package/System.Diagnostics.Debug/4.0.0
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Threading' 299ms
  GET https://www.nuget.org/api/v2/package/System.Threading/4.0.0
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Globalization' 334ms
  GET https://www.nuget.org/api/v2/package/System.Globalization/4.0.0
  OK https://www.nuget.org/api/v2/package/System.Resources.ResourceManager/4.0.0 113ms
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Reflection'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Reflection'
  OK https://www.nuget.org/api/v2/package/System.Diagnostics.Debug/4.0.0 113ms
  OK https://www.nuget.org/api/v2/package/System.Threading/4.0.0 116ms
  OK https://www.nuget.org/api/v2/package/System.Globalization/4.0.0 89ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Reflection' 91ms
  GET https://www.nuget.org/api/v2/package/System.Reflection/4.0.0
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Threading' 515ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Diagnostics.Debug' 522ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Resources.ResourceManager' 566ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Globalization' 576ms
  OK https://www.nuget.org/api/v2/package/System.Reflection/4.0.0 94ms
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Reflection.Primitives'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Reflection.Primitives'
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Reflection.Primitives' 85ms
  GET https://www.nuget.org/api/v2/package/System.Reflection.Primitives/4.0.0
  OK https://www.nuget.org/api/v2/package/System.Reflection.Primitives/4.0.0 87ms
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='runtime.unix.System.Security.Cryptography.X509Certificates'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.unix.System.Security.Cryptography.X509Certificates'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='runtime.unix.System.Security.Cryptography.Algorithms'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.unix.System.Security.Cryptography.Algorithms'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='runtime.unix.System.Security.Cryptography.Encoding'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.unix.System.Security.Cryptography.Encoding'
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.unix.System.Security.Cryptography.Algorithms' 80ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.unix.System.Security.Cryptography.X509Certificates' 83ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.unix.System.Security.Cryptography.Encoding' 77ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='runtime.unix.System.Security.Cryptography.Algorithms' 239ms
  GET https://www.myget.org/F/dotnet-core/api/v2/package/runtime.unix.System.Security.Cryptography.Algorithms/4.0.0-rc2-23707
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Reflection.Primitives' 575ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='runtime.unix.System.Security.Cryptography.X509Certificates' 336ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='runtime.unix.System.Security.Cryptography.Encoding' 331ms
  GET https://www.myget.org/F/dotnet-core/api/v2/package/runtime.unix.System.Security.Cryptography.X509Certificates/4.0.0-rc2-23707
  GET https://www.myget.org/F/dotnet-core/api/v2/package/runtime.unix.System.Security.Cryptography.Encoding/4.0.0-rc2-23707
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Reflection' 1212ms
  OK https://www.myget.org/F/dotnet-core/api/v2/package/runtime.unix.System.Security.Cryptography.X509Certificates/4.0.0-rc2-23707 1388ms
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='runtime.native.System'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.native.System'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='runtime.native.System.Net.Http'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.native.System.Net.Http'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='runtime.native.System.Security.Cryptography'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.native.System.Security.Cryptography'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Collections'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Collections'
  GET https://www.nuget.org/api/v2/package/System.Globalization/4.0.10
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Globalization.Calendars'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Globalization.Calendars'
  GET https://www.nuget.org/api/v2/package/System.IO/4.0.10
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.IO.FileSystem'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO.FileSystem'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.IO.FileSystem.Primitives'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO.FileSystem.Primitives'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.IO.FileSystem.Watcher'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO.FileSystem.Watcher'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Runtime.Extensions'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Extensions'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Runtime.InteropServices'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.InteropServices'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Runtime.Numerics'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Numerics'
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Security.Cryptography.OpenSsl'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Security.Cryptography.OpenSsl'
  GET https://www.nuget.org/api/v2/package/System.Text.Encoding/4.0.10
  GET https://www.nuget.org/api/v2/package/System.Threading/4.0.10
  OK https://www.myget.org/F/dotnet-core/api/v2/package/runtime.unix.System.Security.Cryptography.Algorithms/4.0.0-rc2-23707 1550ms
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Text.Encoding.Extensions'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Text.Encoding.Extensions'
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='runtime.native.System.Net.Http' 229ms
  GET https://www.myget.org/F/dotnet-core/api/v2/package/runtime.native.System.Net.Http/4.0.1-rc2-23707
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='runtime.native.System.Security.Cryptography' 267ms
  GET https://www.myget.org/F/dotnet-core/api/v2/package/runtime.native.System.Security.Cryptography/4.0.0-rc2-23707
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='runtime.native.System' 275ms
  GET https://www.myget.org/F/dotnet-core/api/v2/package/runtime.native.System/4.0.0-rc2-23707
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Security.Cryptography.OpenSsl' 272ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Collections' 278ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.native.System' 282ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.native.System.Net.Http' 282ms
  GET https://www.nuget.org/api/v2/package/System.Collections/4.0.10
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO.FileSystem.Primitives' 286ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Globalization.Calendars' 288ms
  GET https://www.nuget.org/api/v2/package/System.Globalization.Calendars/4.0.0
  GET https://www.nuget.org/api/v2/package/System.IO.FileSystem.Primitives/4.0.0
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO.FileSystem' 295ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO.FileSystem.Watcher' 294ms
  GET https://www.nuget.org/api/v2/package/System.IO.FileSystem/4.0.0
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Numerics' 295ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Extensions' 296ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.InteropServices' 296ms
  GET https://www.nuget.org/api/v2/package/System.Runtime.Numerics/4.0.0
  GET https://www.nuget.org/api/v2/package/System.Runtime.InteropServices/4.0.20
  GET https://www.nuget.org/api/v2/package/System.Runtime.Extensions/4.0.10
  OK https://www.nuget.org/api/v2/package/System.Globalization/4.0.10 305ms
  OK https://www.nuget.org/api/v2/package/System.Text.Encoding/4.0.10 310ms
  OK https://www.nuget.org/api/v2/package/System.IO/4.0.10 315ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Collections' 324ms
  OK https://www.nuget.org/api/v2/package/System.Threading/4.0.10 316ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.native.System.Security.Cryptography' 333ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Globalization.Calendars' 333ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Text.Encoding.Extensions' 274ms
  GET https://www.nuget.org/api/v2/package/System.Text.Encoding.Extensions/4.0.0
  OK https://www.nuget.org/api/v2/package/System.Collections/4.0.10 87ms
  OK https://www.nuget.org/api/v2/package/System.IO.FileSystem.Primitives/4.0.0 81ms
  OK https://www.nuget.org/api/v2/package/System.Globalization.Calendars/4.0.0 86ms
  OK https://www.nuget.org/api/v2/package/System.Runtime.Numerics/4.0.0 87ms
  OK https://www.nuget.org/api/v2/package/System.IO.FileSystem/4.0.0 92ms
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Threading.Overlapped'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Threading.Overlapped'
  GET https://www.nuget.org/api/v2/package/System.Threading.Tasks/4.0.10
  GET https://www.nuget.org/api/v2/package/System.Text.Encoding.Extensions/4.0.10
  OK https://www.nuget.org/api/v2/package/System.Runtime.Extensions/4.0.10 98ms
  OK https://www.nuget.org/api/v2/package/System.Runtime.InteropServices/4.0.20 104ms
  OK https://www.nuget.org/api/v2/package/System.Text.Encoding.Extensions/4.0.0 79ms
  OK https://www.myget.org/F/dotnet-core/api/v2/package/runtime.unix.System.Security.Cryptography.Encoding/4.0.0-rc2-23707 1837ms
  GET https://www.nuget.org/api/v2/package/System.Collections/4.0.0
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Collections.Concurrent'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Collections.Concurrent'
  GET https://www.nuget.org/api/v2/package/System.Diagnostics.Debug/4.0.10
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Linq'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Linq'
  OK https://www.nuget.org/api/v2/package/System.Threading.Tasks/4.0.10 79ms
  OK https://www.nuget.org/api/v2/package/System.Text.Encoding.Extensions/4.0.10 88ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Threading.Overlapped' 89ms
  GET https://www.nuget.org/api/v2/package/System.Threading.Overlapped/4.0.0
  OK https://www.nuget.org/api/v2/package/System.Collections/4.0.0 88ms
  OK https://www.nuget.org/api/v2/package/System.Diagnostics.Debug/4.0.10 87ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Collections.Concurrent' 94ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Linq' 94ms
  GET https://www.nuget.org/api/v2/package/System.Linq/4.0.0
  GET https://www.nuget.org/api/v2/package/System.Collections.Concurrent/4.0.0
  OK https://www.nuget.org/api/v2/package/System.Threading.Overlapped/4.0.0 77ms
  OK https://www.nuget.org/api/v2/package/System.Collections.Concurrent/4.0.0 77ms
  OK https://www.nuget.org/api/v2/package/System.Linq/4.0.0 84ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Threading.Overlapped' 536ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Linq' 527ms
  OK https://www.myget.org/F/dotnet-core/api/v2/package/runtime.native.System.Security.Cryptography/4.0.0-rc2-23707 847ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Collections.Concurrent' 692ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.IO.FileSystem.Primitives' 1315ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Runtime.Extensions' 1386ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Security.Cryptography.OpenSsl' 1397ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.IO.FileSystem' 1407ms
  GET https://www.myget.org/F/dotnet-core/api/v2/package/System.Security.Cryptography.OpenSsl/4.0.0-rc2-23707
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.IO.FileSystem.Watcher' 1430ms
  GET https://www.myget.org/F/dotnet-core/api/v2/package/System.IO.FileSystem.Watcher/4.0.0-rc2-23707
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Text.Encoding.Extensions' 1407ms
  OK https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Runtime.InteropServices' 1506ms
  OK https://www.myget.org/F/dotnet-core/api/v2/package/runtime.native.System.Net.Http/4.0.1-rc2-23707 1303ms
  OK https://www.myget.org/F/dotnet-core/api/v2/package/runtime.native.System/4.0.0-rc2-23707 1355ms
  OK https://www.myget.org/F/dotnet-core/api/v2/package/System.Security.Cryptography.OpenSsl/4.0.0-rc2-23707 1123ms
----------
System.InvalidOperationException: A circular reference to 'System.Security.Cryptography.Algorithms' was detected.
   at Microsoft.Dnx.Tooling.RestoreOperations.<>c__DisplayClass3_0.<ChainPredicate>b__0(String name)
   at Microsoft.Dnx.Tooling.RestoreOperations.<>c__DisplayClass3_0.<ChainPredicate>b__0(String name)
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RestoreCommand.<CreateGraphNode>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
A circular reference to 'System.Security.Cryptography.Algorithms' was detected.

NuGet Config files used:
    /home/andrew/.config/NuGet/NuGet.config
    /home/andrew/algorithm-repro/nuget.config

Feeds used:
    https://www.myget.org/F/dotnet-core/
    https://www.nuget.org/api/v2/
```

Trying to use latest [System.Security.Cryptography.X509Certificates](https://www.myget.org/feed/dotnet-core/package/nuget/System.Security.Cryptography.X509Certificates) on Ubuntu 14.04 with dotnet-cli version: 1.0.0.1451415522-1.

**Comment by bartonjs** [comment]
@weshaggard When we republished the packages on Wednesday to remove my circular reference, did we remove the runtime.unix.System.Security.Cryptography.Algorithms dependency on System.Security.Cryptography.OpenSsl?

@andschwa I was able to repro your failure, and I was further able to make the problem go away by bumping to the next available version (23712)

**Comment by andschwa** [comment]
Yay thank you @bartonjs! This no longer repros. Will try bumping our packages in the real project again today.

**Comment by andschwa** [comment]
Just an update: all is good in the much more complicated setup.
