### ISSUE TITLE
NegotiateStream_StreamToStream_Authentication_Success failed in CI on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5326]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_release_prtest/854/consoleFull
```
19:42:31      System.Net.Security.Tests.NegotiateStreamStreamToStreamTest.NegotiateStream_StreamToStream_Authentication_Success [FAIL]
19:42:31         System.AggregateException : One or more errors occurred.
19:42:31         ---- System.IO.IOException : Unable to read data from the transport connection: Queue empty..
19:42:31         -------- System.InvalidOperationException : Queue empty.
19:42:31         Stack Trace:
19:42:31               at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
19:42:31            d:\j\workspace\dotnet_corefx\windows_nt_release_prtest\src\System.Net.Security\tests\FunctionalTests\NegotiateStreamStreamToStreamTest.cs(36,0): at System.Net.Security.Tests.NegotiateStreamStreamToStreamTest.NegotiateStream_StreamToStream_Authentication_Success()
19:42:31            ----- Inner Stack Trace -----
19:42:31            d:\j\workspace\dotnet_corefx\windows_nt_release_prtest\src\System.Net.Security\src\System\Net\SecureProtocols\NegoState.Windows.cs(445,0): at System.Net.Security.NegoState.EndProcessAuthentication(IAsyncResult result)
19:42:31               at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
19:42:31            ----- Inner Stack Trace -----
19:42:31               at System.Collections.Generic.Queue`1.Dequeue()
19:42:31            d:\j\workspace\dotnet_corefx\windows_nt_release_prtest\src\System.Net.Security\tests\FunctionalTests\MockNetwork.cs(34,0): at System.Net.Security.Tests.MockNetwork.ReadFrame(Boolean server, Byte[]& buffer)
19:42:31            d:\j\workspace\dotnet_corefx\windows_nt_release_prtest\src\System.Net.Security\tests\FunctionalTests\FakeNetworkStream.cs(103,0): at System.Net.Security.Tests.FakeNetworkStream.UpdateReadStream()
19:42:31            d:\j\workspace\dotnet_corefx\windows_nt_release_prtest\src\System.Net.Security\tests\FunctionalTests\FakeNetworkStream.cs(83,0): at System.Net.Security.Tests.FakeNetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
19:42:31               at System.Threading.Tasks.Task`1.InnerInvoke()
19:42:31               at System.Threading.Tasks.Task.Execute()
19:42:31            --- End of stack trace from previous location where exception was thrown ---
19:42:31               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
19:42:31               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
19:42:31            d:\j\workspace\dotnet_corefx\windows_nt_release_prtest\src\Common\src\System\IO\StreamAsyncHelper.cs(105,0): at System.IO.StreamAsyncHelper.EndRead(IAsyncResult asyncResult)
19:42:31            d:\j\workspace\dotnet_corefx\windows_nt_release_prtest\src\System.Net.Security\src\System\Net\StreamFramer.cs(205,0): at System.Net.StreamFramer.ReadFrameComplete(IAsyncResult transportResult)
19:42:31            d:\j\workspace\dotnet_corefx\windows_nt_release_prtest\src\System.Net.Security\src\System\Net\StreamFramer.cs(169,0): at System.Net.StreamFramer.ReadFrameCallback(IAsyncResult transportResult)
```

**Comment by CIPop** [comment]
This is a duplicate of #5284, although a different test is failing here.
