### ISSUE TITLE
DriveInfo tests fail if current user uses SUBST

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#549]
On my machine I'm using SUBST to map folders as drives. This causes the the drive info tests to fail:

```
System.IO.FileSystem.DriveInfoTests.Get_VolumeLabel.Test01 [FAIL]
   System.IO.IOException : The directory is not a subdirectory of the root directory.

   Stack Trace:
      p:\oss\corefx\src\System.IO.FileSystem.DriveInfo\src\System\IO\DriveInfo.Windows.cs(235,0): at System.IO.DriveInfo.set_VolumeLabel(String value)
      p:\oss\corefx\src\System.IO.FileSystem.DriveInfo\tests\GetVolumeLabelTests.cs(74,0): at System.IO.FileSystem.DriveInfoTests.Get_VolumeLabel.Test01()

System.IO.FileSystem.DriveInfoTests.Set_VolumeLabel.Test01 [FAIL]
   System.IO.IOException : The directory is not a subdirectory of the root directory.

   Stack Trace:
      p:\oss\corefx\src\System.IO.FileSystem.DriveInfo\src\System\IO\DriveInfo.Windows.cs(235,0): at System.IO.DriveInfo.set_VolumeLabel(String value)
      p:\oss\corefx\src\System.IO.FileSystem.DriveInfo\tests\SetVolumeLabelTests.cs(75,0): at System.IO.FileSystem.DriveInfoTests.Set_VolumeLabel.Test01()
```

I would expect the drive info tests to be resilient to this.

**Comment by terrajobst** [comment]
@Priya91, can you take a look?

**Comment by Priya91** [comment]
@terrajobst yes, working on this.

**Comment by Yomodo** [comment]
According to MSDN, a SUBST.EXE created mapping should NOT be considered a valid mapped drive.

We follow the same in our project, https://github.com/alphaleonis/AlphaFS

**Comment by JeremyKuhne** [comment]
Triage: Rare case, but disabled test. We should fix.

**Comment by JeremyKuhne** [comment]
As mentioned above https://github.com/dotnet/corefx/issues/549#issuecomment-72322352 this type of drive shouldn't be considered. Need to look deeper at expected behavior in this case and update tests to either skip in this case or handle appropriately.
