### ISSUE TITLE
Registry tests fail intermittently 

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#553]
Seems like this might be due to cross-talk between tests running at the same time.  I see shared state between tests.

     Microsoft.Win32.RegistryTests.RegistryKey_OpenSubKey_str_rkpc.Test03 [FAIL]
        ErrorUnexpected Exception: Xunit.Sdk.FalseException: Error Value not correctly created.
           at Xunit.Assert.False(Boolean condition, String userMessage)
           at Microsoft.Win32.RegistryTests.RegistryKey_OpenSubKey_str_rkpc.Test03() in c:\jenkins\workspace\dotnet_corefx_windows_prtest\src\Microsoft.Win32.Registry\tests\RegistryKey\RegistryKey_OpenSubKey_str_rkpc.cs:line 123
        Stack Trace:
           c:\jenkins\workspace\dotnet_corefx_windows_prtest\src\Microsoft.Win32.Registry\tests\RegistryKey\RegistryKey_OpenSubKey_str_rkpc.cs(129,0): at Microsoft.Win32.RegistryTests.RegistryKey_OpenSubKey_str_rkpc.Test03()

**Comment by stephentoub** [comment]
Disabled parallelization in #595
