### ISSUE TITLE
System.Net.Http.Unit.Tests intermittently fails with AV on Ubuntu

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#5536]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_debug_tst_prtest/950/console

```
=== TEST EXECUTION SUMMARY ===
10:18:22    System.Net.Http.Unit.Tests  Total: 989, Errors: 0, Failed: 0, Skipped: 0, Time: 5.949s
10:18:25 
10:18:25 Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
10:18:25    at System.Runtime.CompilerServices.TaskAwaiter.OnCompletedInternal(Task task, Action continuation, Boolean continueOnCapturedContext, Boolean flowExecutionContext)
10:18:25    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.UnsafeOnCompleted(Action continuation)
10:18:25    at System.Threading.Tasks.TaskExtensions.TransferAsynchronously[TResult,TInner](TaskCompletionSource`1 completionSource, Task`1 outer)
10:18:25    at System.Threading.Tasks.TaskExtensions.Unwrap[TResult](Task`1 task)
10:18:25    at System.Threading.Tasks.Tests.UnwrapTests.<>c__DisplayClass15_0.<RunStackGuardTests>b__0(Int32 count)
10:18:25    at System.Threading.Tasks.Tests.UnwrapTests.<>c__DisplayClass15_1.<RunStackGuardTests>b__1()
10:18:25    at System.Threading.Tasks.Task`1.InnerInvoke()
10:18:25    at System.Threading.Tasks.Task.Execute()
10:18:25    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
10:18:25    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
10:18:25    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
10:18:25    at System.Threading.ThreadPoolWorkQueue.Dispatch()
10:18:25 Finished:    System.Net.Http.Functional.Tests
```

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by stephentoub** [comment]
This isn't actually a System.Net test... the tests are running concurrently, though, so it looks like it's coming from System.Net.  If you scour the call stack, though, you can see that it's actually coming from the RunStackGuardTests, which is part of the System.Threading.Tasks tests.

Dup of https://github.com/dotnet/corefx/issues/5531
