### ISSUE TITLE
System.Net.Security "no encryption" tests failing on OpenSUSE

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5557]
```
09:37:45    System.Net.Security.Tests.ServerAllowNoEncryptionTest.ServerAllowNoEncryption_ClientNoEncryption_ConnectWithNoEncryption [FAIL]
09:37:45       System.Security.Authentication.AuthenticationException : A call to SSPI failed, see inner exception.
09:37:45 
      ---- Interop+OpenSsl+SslException : Operation failed with error - 12.
09:37:45       Stack Trace:
09:37:46             at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
09:37:46             at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
09:37:46             at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
09:37:46             at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
09:37:46             at System.Net.Security.SslStream.<>c__DisplayClass21_0.<AuthenticateAsClientAsync>b__0(AsyncCallback callback, Object state)
09:37:46             at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
09:37:46             at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
09:37:46             at System.Net.Security.Tests.ServerAllowNoEncryptionTest.<ServerAllowNoEncryption_ClientNoEncryption_ConnectWithNoEncryption>d__5.MoveNext()
09:37:46          --- End of stack trace from previous location where exception was thrown ---
09:37:46             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:37:46             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:37:46          --- End of stack trace from previous location where exception was thrown ---
09:37:46             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:37:46             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:37:46          --- End of stack trace from previous location where exception was thrown ---
09:37:46             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:37:46             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:37:46          ----- Inner Stack Trace -----
09:37:46          
09:37:47    System.Net.Security.Tests.ServerNoEncryptionTest.ServerNoEncryption_ClientAllowNoEncryption_ConnectWithNoEncryption [FAIL]
09:37:47       System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
09:37:47       Stack Trace:
09:37:47             at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
09:37:47             at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
09:37:47             at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
09:37:47          --- End of stack trace from previous location where exception was thrown ---
09:37:47             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:37:47             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:37:47             at System.Net.Security.Tests.ServerNoEncryptionTest.<ServerNoEncryption_ClientAllowNoEncryption_ConnectWithNoEncryption>d__4.MoveNext()
09:37:47          --- End of stack trace from previous location where exception was thrown ---
09:37:47             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:37:47             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:37:47          --- End of stack trace from previous location where exception was thrown ---
09:37:47             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:37:47             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:37:47          --- End of stack trace from previous location where exception was thrown ---
09:37:47             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:37:47             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:37:48 Finished:    System.Reflection.Metadata.Tests
09:37:48 
09:37:48 === TEST EXECUTION SUMMARY ===
09:37:48    System.Reflection.Metadata.Tests  Total: 146, Errors: 0, Failed: 0, Skipped: 0, Time: 5.368s
09:37:48    System.Net.Security.Tests.ServerNoEncryptionTest.ServerNoEncryption_ClientNoEncryption_ConnectWithNoEncryption [FAIL]
09:37:48       System.Security.Authentication.AuthenticationException : A call to SSPI failed, see inner exception.
09:37:48 
      ---- Interop+OpenSsl+SslException : Operation failed with error - 12.
09:37:48       Stack Trace:
09:37:48             at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
09:37:48             at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
09:37:48             at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
09:37:48             at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
09:37:48             at System.Net.Security.SslStream.<>c__DisplayClass21_0.<AuthenticateAsClientAsync>b__0(AsyncCallback callback, Object state)
09:37:48             at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
09:37:48             at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
09:37:48             at System.Net.Security.Tests.ServerNoEncryptionTest.<ServerNoEncryption_ClientNoEncryption_ConnectWithNoEncryption>d__5.MoveNext()
09:37:48          --- End of stack trace from previous location where exception was thrown ---
09:37:48             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:37:48             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:37:48          --- End of stack trace from previous location where exception was thrown ---
09:37:48             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:37:48             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:37:48          --- End of stack trace from previous location where exception was thrown ---
09:37:48             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:37:48             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:37:48          ----- Inner Stack Trace -----
09:37:48          
09:37:48    System.Net.Security.Tests.ServerRequireEncryptionTest.ServerRequireEncryption_ClientNoEncryption_NoConnect [FAIL]
09:37:48       Assert.Throws() Failure
09:37:48       Expected: typeof(System.IO.IOException)
09:37:48       Actual:   typeof(System.Security.Authentication.AuthenticationException): A call to SSPI failed, see inner exception.
09:37:48       Stack Trace:
09:37:48             at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
09:37:48             at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
09:37:48             at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
09:37:48             at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
09:37:48             at System.Net.Security.SslStream.<>c__DisplayClass21_0.<AuthenticateAsClientAsync>b__0(AsyncCallback callback, Object state)
09:37:48             at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
09:37:48             at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
```
These pass on Windows, Ubuntu, and CentOS.

**Comment by stephentoub** [comment]
With https://github.com/dotnet/corefx/pull/6750, we now have better error information for these failures:
```
10:23:38    System.Net.Security.Tests.ServerAllowNoEncryptionTest.ServerAllowNoEncryption_ClientNoEncryption_ConnectWithNoEncryption [FAIL]
10:23:38       System.Security.Authentication.AuthenticationException : A call to SSPI failed, see inner exception.
10:23:38       ---- Interop+OpenSsl+SslException : SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
10:23:38       -------- Interop+Crypto+OpenSslCryptographicException : error:140740B5:SSL routines:SSL23_CLIENT_HELLO:no ciphers available
10:23:38       Stack Trace:
10:23:39             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
10:23:39             at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
10:23:39             at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
10:23:39             at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
10:23:39             at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
10:23:39             at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
10:23:39             at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
10:23:39             at System.Net.Security.SslStream.<>c__DisplayClass21_0.<AuthenticateAsClientAsync>b__0(AsyncCallback callback, Object state)
10:23:39             at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
10:23:39             at System.Threading.Tasks.TaskFactory.FromAsync(Func`3 beginMethod, Action`1 endMethod, Object state)
10:23:39             at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
10:23:39             at System.Net.Security.Tests.ServerAllowNoEncryptionTest.<ServerAllowNoEncryption_ClientNoEncryption_ConnectWithNoEncryption>d__5.MoveNext()
10:23:39          --- End of stack trace from previous location where exception was thrown ---
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
10:23:39          --- End of stack trace from previous location where exception was thrown ---
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
10:23:39          --- End of stack trace from previous location where exception was thrown ---
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
10:23:39          ----- Inner Stack Trace -----
10:23:39             at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
10:23:39             at System.Net.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, Boolean isServer, Boolean remoteCertRequired)
10:23:39          ----- Inner Stack Trace -----
10:23:39          
10:23:39    System.Net.Security.Tests.ServerNoEncryptionTest.ServerNoEncryption_ClientAllowNoEncryption_ConnectWithNoEncryption [FAIL]
10:23:39       System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
10:23:39       Stack Trace:
10:23:39             at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
10:23:39             at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
10:23:39          --- End of stack trace from previous location where exception was thrown ---
10:23:39             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
10:23:39             at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
10:23:39             at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
10:23:39             at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
10:23:39             at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
10:23:39          --- End of stack trace from previous location where exception was thrown ---
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
10:23:39             at System.Net.Security.Tests.ServerNoEncryptionTest.<ServerNoEncryption_ClientAllowNoEncryption_ConnectWithNoEncryption>d__4.MoveNext()
10:23:39          --- End of stack trace from previous location where exception was thrown ---
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
10:23:39          --- End of stack trace from previous location where exception was thrown ---
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
10:23:39          --- End of stack trace from previous location where exception was thrown ---
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
10:23:39    System.Net.Security.Tests.ServerNoEncryptionTest.ServerNoEncryption_ClientNoEncryption_ConnectWithNoEncryption [FAIL]
10:23:39       System.Security.Authentication.AuthenticationException : A call to SSPI failed, see inner exception.
10:23:39       ---- Interop+OpenSsl+SslException : SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
10:23:39       -------- Interop+Crypto+OpenSslCryptographicException : error:140740B5:SSL routines:SSL23_CLIENT_HELLO:no ciphers available
10:23:39       Stack Trace:
10:23:39             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
10:23:39             at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
10:23:39             at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
10:23:39             at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
10:23:39             at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
10:23:39             at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
10:23:39             at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
10:23:39             at System.Net.Security.SslStream.<>c__DisplayClass21_0.<AuthenticateAsClientAsync>b__0(AsyncCallback callback, Object state)
10:23:39             at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
10:23:39             at System.Threading.Tasks.TaskFactory.FromAsync(Func`3 beginMethod, Action`1 endMethod, Object state)
10:23:39             at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
10:23:39             at System.Net.Security.Tests.ServerNoEncryptionTest.<ServerNoEncryption_ClientNoEncryption_ConnectWithNoEncryption>d__5.MoveNext()
10:23:39          --- End of stack trace from previous location where exception was thrown ---
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
10:23:39          --- End of stack trace from previous location where exception was thrown ---
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
10:23:39          --- End of stack trace from previous location where exception was thrown ---
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
10:23:39             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
10:23:39          ----- Inner Stack Trace -----
10:23:39             at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
10:23:39             at System.Net.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, Boolean isServer, Boolean remoteCertRequired)
10:23:39          ----- Inner Stack Trace -----
10:23:39          
10:23:40    System.Net.Security.Tests.ServerRequireEncryptionTest.ServerRequireEncryption_ClientNoEncryption_NoConnect [FAIL]
10:23:40       Assert.Throws() Failure
10:23:40       Expected: typeof(System.IO.IOException)
10:23:40       Actual:   typeof(System.Security.Authentication.AuthenticationException): A call to SSPI failed, see inner exception.
10:23:40       Stack Trace:
10:23:40             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
10:23:40             at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
10:23:40             at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
10:23:40             at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
10:23:40             at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
10:23:40             at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
10:23:40             at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
10:23:40             at System.Net.Security.SslStream.<>c__DisplayClass21_0.<AuthenticateAsClientAsync>b__0(AsyncCallback callback, Object state)
10:23:40             at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
10:23:40             at System.Threading.Tasks.TaskFactory.FromAsync(Func`3 beginMethod, Action`1 endMethod, Object state)
10:23:40             at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
10:23:40             at System.Net.Security.Tests.ServerRequireEncryptionTest.<>c__DisplayClass5_0.<ServerRequireEncryption_ClientNoEncryption_NoConnect>b__0()
```

**Comment by stephentoub** [comment]
Running:
```
openssl ciphers -v ALL:eNULL
```
on the OpenSUSE CI machine and comparing that to the output of the same on an Ubuntu CI machine, the following are all present on the Ubuntu machine, and no "null" ciphers are present on the OpenSUSE one:
```
ECDHE-RSA-NULL-SHA      SSLv3 Kx=ECDH     Au=RSA  Enc=None      Mac=SHA1
ECDHE-ECDSA-NULL-SHA    SSLv3 Kx=ECDH     Au=ECDSA Enc=None      Mac=SHA1
AECDH-NULL-SHA          SSLv3 Kx=ECDH     Au=None Enc=None      Mac=SHA1
ECDH-RSA-NULL-SHA       SSLv3 Kx=ECDH/RSA Au=ECDH Enc=None      Mac=SHA1
ECDH-ECDSA-NULL-SHA     SSLv3 Kx=ECDH/ECDSA Au=ECDH Enc=None      Mac=SHA1
NULL-SHA256             TLSv1.2 Kx=RSA      Au=RSA  Enc=None      Mac=SHA256
NULL-SHA                SSLv3 Kx=RSA      Au=RSA  Enc=None      Mac=SHA1
NULL-MD5                SSLv3 Kx=RSA      Au=RSA  Enc=None      Mac=MD5 
```

**Comment by stephentoub** [comment]
And, indeed, I see the following in the changelog for the OpenSUSE package:
```
Sat Oct 08 2011 opensuse.org
  - Build with -DSSL_FORBID_ENULL so servers are not
    able to use the NULL encryption ciphers (Those offering no
    encryption whatsoever).
```

**Comment by bartonjs** [comment]
Nice digging, Steve.  Now if only that had shown up in `opensslconf.h`...
