### ISSUE TITLE
RC2 - A connection was successfully established with the server, but then an error occurred during the pre-login handshake

### ISSUE THREAD

**Issue by jamesgibbs100** [dotnet/corefx#5657]
Platform : Linux Ubuntu
Runtime  : 1.0.0-rc2-16357,coreclr,x64,linux
System.Data.SqlClient : 4.0.0-rc2-23623

ConnectionString : Data Source=XXXXXXXX,60606;Initial Catalog=XXXXXXXX;Integrated Security=False;User ID=sa;Password=XXXX;Connect Timeout=10;Encrypt=False;Application Name="vNEXT"

Works perfectly on Windows using same runtime as above.
Perform a dnu restore --no-cache before running console application.

First SqlClient.Open connection results in below stack trace

**A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Interop+OpenSsl+SslException: Operation failed with error - 12**

```
fail: XXX.Ims.Common.Data.TenantDbConnectionStringBuilder[0]
      System.Data.SqlClient.SqlException: A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Interop+OpenSsl+SslException: Operation failed with error - 12.
         --- End of inner exception stack trace ---
         at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
         at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
         at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
         at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
         at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, AsyncCallback asyncCallback, Object asyncState)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1](Func`4 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, Object state, TaskCreationOptions creationOptions)
         at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost)
         at System.Data.SqlClient.SNI.SNITCPHandle.EnableSsl(UInt32 options)
         --- End of inner exception stack trace ---
         at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
         at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
         at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
         at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
         at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
         at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
         at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
         at System.Data.SqlClient.SqlConnection.Open()
         at XXX.Ims.Common.Data.TenantDbConnectionStringBuilder.Build(Int32 tenantId)
      ClientConnectionId:c185aa23-7668-46f1-9a83-ad3018d65229
```

**Comment by jamesgibbs100** [comment]
Reference : #4593

**Comment by jamesgibbs100** [comment]
Just a quick update - I created a much simpler console application and ran that. This time it came back with a missing System.Net.Security exception.

Adding "System.Net.Security": "4.0.0-rc2-23513" dependency to the project.json of host console application resolved the problem.

**Comment by corivera** [comment]
@jamesgibbs100 Are you still seeing this problem? It doesn't repro for me on SqlClient build 4.0.0-rc3-23726.
