### ISSUE TITLE
Microsoft.Win32.Registry.Tests fail when run build.cmd

### ISSUE THREAD

**Issue by cnblogs-dudu** [dotnet/corefx#566]
Error log:
```
  Starting:    System.Globalization.Extensions.Tests
  Discovering: Microsoft.Win32.Registry.Tests
  Discovered:  System.ComponentModel.Annotations.Tests
  Starting:    System.ComponentModel.Annotations.Tests
  Discovered:  Microsoft.Win32.Registry.Tests
  Starting:    Microsoft.Win32.Registry.Tests
     Microsoft.Win32.RegistryTests.RegistryKey_GetValue_str_obj_regvalopt.Test01 [FAIL]
        Error Unexpected exception occured , got exc==Xunit.Sdk.FalseException: Error Key value is incorrect...
           at Xunit.Assert.False(Boolean condition, String userMessage)
           at Microsoft.Win32.RegistryTests.RegistryKey_GetValue_str_obj_regvalopt.Test01() in e:\Dev\GitHub\DotNet\corefx\src\Microsoft.Win32.Registry\tests\RegistryKey\RegistryKey_GetValue_str_obj_regvalopt.cs:line 43
        Stack Trace:
           e:\Dev\GitHub\DotNet\corefx\src\Microsoft.Win32.Registry\tests\RegistryKey\RegistryKey_GetValue_str_obj_regvalopt.cs(48,0): at Microsoft.Win32.RegistryTests.RegistryKey_GetValue_str_obj_regvalopt.Test01()
     Microsoft.Win32.RegistryTests.RegistryKey_GetValue_str_obj_regvalopt.Test05 [FAIL]
        Error Unexpected exception occured.... exception message...:Xunit.Sdk.FalseException: Error null return expected
           at Xunit.Assert.False(Boolean condition, String userMessage)
           at Microsoft.Win32.RegistryTests.RegistryKey_GetValue_str_obj_regvalopt.Test05() in e:\Dev\GitHub\DotNet\corefx\src\Microsoft.Win32.Registry\tests\RegistryKey\RegistryKey_GetValue_str_obj_regvalopt.cs:line 94
        Stack Trace:
           e:\Dev\GitHub\DotNet\corefx\src\Microsoft.Win32.Registry\tests\RegistryKey\RegistryKey_GetValue_str_obj_regvalopt.cs(99,0): at Microsoft.Win32.RegistryTests.RegistryKey_GetValue_str_obj_regvalopt.Test05()
     Microsoft.Win32.RegistryTests.RegistryKey_GetValue_str_obj_b.Test01 [FAIL]
        Error Unexpected exception occured , got exc==Xunit.Sdk.FalseException: Error Key value is incorrect...
           at Xunit.Assert.False(Boolean condition, String userMessage)
           at Microsoft.Win32.RegistryTests.RegistryKey_GetValue_str_obj_b.Test01() in e:\Dev\GitHub\DotNet\corefx\src\Microsoft.Win32.Registry\tests\RegistryKey\RegistryKey_GetValue_str_obj_b.cs:line 47
        Stack Trace:
           e:\Dev\GitHub\DotNet\corefx\src\Microsoft.Win32.Registry\tests\RegistryKey\RegistryKey_GetValue_str_obj_b.cs(52,0): at Microsoft.Win32.RegistryTests.RegistryKey_GetValue_str_obj_b.Test01()
     Microsoft.Win32.RegistryTests.RegistryKey_GetValue_str_obj_b.Test03 [FAIL]
        Error Unexpected exception occured.... exception message...:Xunit.Sdk.FalseException: Error null return expected
           at Xunit.Assert.False(Boolean condition, String userMessage)
           at Microsoft.Win32.RegistryTests.RegistryKey_GetValue_str_obj_b.Test03() in e:\Dev\GitHub\DotNet\corefx\src\Microsoft.Win32.Registry\tests\RegistryKey\RegistryKey_GetValue_str_obj_b.cs:line 86
        Stack Trace:
           e:\Dev\GitHub\DotNet\corefx\src\Microsoft.Win32.Registry\tests\RegistryKey\RegistryKey_GetValue_str_obj_b.cs(91,0): at Microsoft.Win32.RegistryTests.RegistryKey_GetValue_str_obj_b.Test03()
  xUnit.net console test runner (32-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.
  
  Finished:    System.ComponentModel.Annotations.Tests
```

**Comment by krwq** [comment]
@pallavit, is it known issue? On the first glance it looks like a product bug or some concurrency problem.

@cnblogs-dudu, does it repro all the time?

**Comment by cnblogs-dudu** [comment]
@krwq
all the time

**Comment by cnblogs-dudu** [comment]
@krwq 
```charp
Object obj = _rk1.GetValue(null, null, RegistryValueOptions.DoNotExpandEnvironmentNames);
if (obj != null)
{
    Assert.False(true, "Error Key value is incorrect...");
}
```
obj value is 0.

**Comment by stephentoub** [comment]
@cnblogs-dudu, if you open regedit and click on HKEY_CURRENT_USER, in the right pane you should see an entry for "(DEFAULT)".  For that row, under the Data column, do you see "(value not set)" or do you see something else, like "0"?

I ask because the four tests you're seeing fail are verifying that no default value is set for HKEY_CURRENT_USER.  Doesn't seem like a valid assumption for the test to be making, but nevertheless...

**Comment by cnblogs-dudu** [comment]
@stephentoub 
Yes, found "0".
![screen shot 2015-02-01 at 22 50 58](https://cloud.githubusercontent.com/assets/3196961/5992435/2ca053ee-aa65-11e4-960f-ae0671063a2f.png)
After deleted the "(Default)" entry, the tests were passed.

**Comment by cnblogs-dudu** [comment]
@stephentoub 
"(Default)=0" appeared again.
![screen shot 2015-02-02 at 12 50 40](https://cloud.githubusercontent.com/assets/3196961/5996054/7f584094-aadb-11e4-96df-e78647010c9b.png)

**Comment by stephentoub** [comment]
Thanks, @cnblogs-dudu. And yeah, this is why I said "Doesn't seem like a valid assumption for the test to be making"... something else on your machine seems to be setting that value to 0, which is then causing a subsequent execution of the tests to fail.  The tests should really be fixed to not assume that HKEY_CURRENT_USER's (Default) value is unspecified.
