### ISSUE TITLE
Two System.Net.Security tests timing out on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5663]
I've seen this happen a couple of times now:
```
05:07:44      System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_ServerNoEncryption_NoConnect [FAIL]
05:07:44         Assert.Throws() Failure
05:07:44         Expected: typeof(System.IO.IOException)
05:07:44         Actual:   typeof(Xunit.Sdk.TrueException): Timed Out
05:07:44         Expected: True
05:07:44         Actual:   False
05:07:45         Stack Trace:
05:07:45            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Security\tests\FunctionalTests\ClientAsyncAuthenticateTest.cs(172,0): at System.Net.Security.Tests.ClientAsyncAuthenticateTest.<ClientAsyncSslHelper>d__18.MoveNext()
05:07:45            --- End of stack trace from previous location where exception was thrown ---
05:07:45               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
05:07:45               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
and
```
05:07:45      System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Successive_ClientWrite_Sync_Success [FAIL]
05:07:45         Handshake completed.
05:07:45         Expected: True
05:07:45         Actual:   False
05:07:45         Stack Trace:
05:07:45            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Security\tests\FunctionalTests\SslStreamStreamToStreamTest.cs(76,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Successive_ClientWrite_Sync_Success()
```
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/1381/consoleFull

**Comment by CIPop** [comment]
Thanks @stephentoub. I've added an assert in my last commit - I believe we're now seeing that test failing intermittently as well.

Duplicate of #4467
