### ISSUE TITLE
RC2 Test failed: DeletedTests.FileSystemWatcher_Deleted_Negative: "Should not observe a deleted event within 500ms"

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#5700]
In #5690: 
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/151/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8

@stephentoub @nguerrera PTAL

```
00:16:53 === TEST EXECUTION SUMMARY ===
00:16:53    System.IO.MemoryMappedFiles.Tests  Total: 342, Errors: 0, Failed: 0, Skipped: 0, Time: 7.944s
00:16:56    DeletedTests.FileSystemWatcher_Deleted_Negative [FAIL]
00:16:56       Should not observe a deleted event within 500ms
00:16:56       Expected: False
00:16:56       Actual:   True
00:16:56       Stack Trace:
00:16:57             at Utility.ExpectNoEvent(WaitHandle eventOccurred, String eventName, Int32 timeout)
00:16:57             at DeletedTests.FileSystemWatcher_Deleted_Negative()
00:16:59 Finished:    System.IO.FileSystem.Tests
00:16:59 
00:16:59 === TEST EXECUTION SUMMARY ===
00:16:59    System.IO.FileSystem.Tests  Total: 2029, Errors: 0, Failed: 0, Skipped: 0, Time: 7.687s
00:17:03 Finished:    System.IO.FileSystem.Watcher.Tests
00:17:03 
00:17:03 === TEST EXECUTION SUMMARY ===
00:17:03    System.IO.FileSystem.Watcher.Tests  Total: 58, Errors: 0, Failed: 1, Skipped: 0, Time: 17.725s
00:17:04 error: One or more tests failed while running tests from 'System.IO.FileSystem.Watcher.Tests'.  Exit code 1.
```

**Comment by ellismg** [comment]
Another instance here:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/680/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8
