### ISSUE TITLE
OutOfMemoryException in System.Diagnostics.Process.WaitForExit on Darwin

### ISSUE THREAD

**Issue by pakrym** [dotnet/corefx#5705]
Coreclr version: 23722

This happens in our ci test run. I'll try to create a dedicated repro.

```
Stack trace:
System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.UnixFileStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.FileStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Diagnostics.AsyncStreamReader.<ReadBufferAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Diagnostics.AsyncStreamReader.WaitUtilEOF()
   at System.Diagnostics.Process.WaitForExitCore(Int32 milliseconds)
   at System.Diagnostics.Process.WaitForExit()
```

**Comment by pakrym** [comment]
And it fixed itself, closing for now.
