### ISSUE TITLE
TestMachineNameProperty failing on OS X

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5732]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/197/console
```
08:56:40    System.Runtime.Extensions.Tests.Environment_MachineName.TestMachineNameProperty [FAIL]
08:56:40       Assert+WrapperXunitException : File path: d:\j\workspace\dotnet_corefx\osx_release_bld_prtest\src\System.Runtime.Extensions\tests\System\Environment.MachineName.cs. Line: 17
08:56:40       ---- Assert.Equal() Failure
08:56:40                              ↓ (pos 13)
08:56:40       Expected: dci-mac-bld-5.local
08:56:40       Actual:   dci-mac-bld-5
08:56:40                              ↑ (pos 13)
08:56:40       Stack Trace:
08:56:41             at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
08:56:41             at Assert.Equal(String expected, String actual, String path, Int32 line)
08:56:41          ----- Inner Stack Trace -----
08:56:41             at Assert.Equal(String expected, String actual, String path, Int32 line)
```

**Comment by Priya91** [comment]
Haha :), uname -n should be trimmed, to remove domain. Will fix this..

**Comment by Priya91** [comment]
#5736
