### ISSUE TITLE
SendRecvAsync_Stream_TCP test failed on OS X

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5750]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst/306/console
```
09:48:08 Unhandled Exception: Xunit.Sdk.EqualException: Assert.Equal() Failure
09:48:08 Expected: Success
09:48:08 Actual:   OperationAborted
09:48:08    at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
09:48:08    at System.Net.Sockets.Tests.SocketAsyncExtensions.<>c__DisplayClass3_0.<ReceiveAsync>b__0(Object _, SocketAsyncEventArgs args)
09:48:08    at System.Net.Sockets.Tests.SocketAsyncExtensions.ReceiveAsync(Socket socket, SocketAsyncEventArgs eventArgs, IList`1 buffers, SocketFlags flags, Action`1 handler)
09:48:08    at System.Net.Sockets.Tests.SendReceive.<>c__DisplayClass4_3.<SendRecvAsync_Stream_TCP>b__2(Int32 received)
09:48:08    at System.Net.Sockets.Tests.SocketAsyncExtensions.<>c__DisplayClass3_0.<ReceiveAsync>b__0(Object _, SocketAsyncEventArgs args)
09:48:08    at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
09:48:08    at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
09:48:08    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
09:48:08    at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
09:48:08    at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketError socketError)
09:48:08    at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallback(Int32 bytesTransferred, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError socketError)
09:48:08    at System.Net.Sockets.SocketAsyncContext.<>c.<ReceiveFromAsync>b__42_0(Object args)
09:48:08    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
09:48:08    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
09:48:08    at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/548/console
```
19:15:43 Unhandled Exception: Xunit.Sdk.EqualException: Assert.Equal() Failure
19:15:43 Expected: Success
19:15:43 Actual:   OperationAborted
19:15:43    at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
19:15:43    at System.Net.Sockets.Tests.SocketAsyncExtensions.<>c__DisplayClass3_0.<ReceiveAsync>b__0(Object _, SocketAsyncEventArgs args)
19:15:43    at System.Net.Sockets.Tests.SocketAsyncExtensions.ReceiveAsync(Socket socket, SocketAsyncEventArgs eventArgs, IList`1 buffers, SocketFlags flags, Action`1 handler)
19:15:43    at System.Net.Sockets.Tests.SendReceive.<>c__DisplayClass4_3.<SendRecvAsync_Stream_TCP>b__2(Int32 received)
19:15:43    at System.Net.Sockets.Tests.SocketAsyncExtensions.<>c__DisplayClass3_0.<ReceiveAsync>b__0(Object _, SocketAsyncEventArgs args)
19:15:43    at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
19:15:43    at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
19:15:43    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
19:15:43    at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
19:15:43    at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketError socketError)
19:15:43    at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallback(Int32 bytesTransferred, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError socketError)
19:15:43    at System.Net.Sockets.SocketAsyncContext.<>c.<ReceiveFromAsync>b__44_0(Object args)
19:15:43    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
19:15:43    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
19:15:43    at System.Threading.ThreadPoolWorkQueue.Dispatch()
19:15:43 ./run-test.sh: line 130: 48890 Abort trap: 6           ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory -notrait Benchmark=true
```

**Comment by stephentoub** [comment]
Just happened again:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/1362/console
```
05:53:56 Expected: Success
05:53:56 Actual:   OperationAborted
05:53:56    at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
05:53:56    at System.Net.Sockets.Tests.SocketAsyncExtensions.<>c__DisplayClass3_0.<ReceiveAsync>b__0(Object _, SocketAsyncEventArgs args)
05:53:56    at System.Net.Sockets.Tests.SocketAsyncExtensions.ReceiveAsync(Socket socket, SocketAsyncEventArgs eventArgs, IList`1 buffers, SocketFlags flags, Action`1 handler)
05:53:56    at System.Net.Sockets.Tests.SendReceive.<>c__DisplayClass3_3.<SendRecvAsync_Stream_TCP>b__2(Int32 received)
05:53:56    at System.Net.Sockets.Tests.SocketAsyncExtensions.<>c__DisplayClass3_0.<ReceiveAsync>b__0(Object _, SocketAsyncEventArgs args)
05:53:56    at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
05:53:56    at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
05:53:56    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
05:53:56    at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
05:53:56    at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketError socketError)
05:53:56    at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallback(Int32 bytesTransferred, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError socketError)
05:53:56    at System.Net.Sockets.SocketAsyncContext.<>c.<ReceiveFromAsync>b__39_0(Object args)
05:53:56    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
05:53:56    at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
05:53:56    at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by stephentoub** [comment]
Just failed again (OS X Debug):
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/1441/console
```
15:06:30 Unhandled Exception: Xunit.Sdk.EqualException: Assert.Equal() Failure
15:06:30 Expected: Success
15:06:30 Actual:   OperationAborted
15:06:30    at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
15:06:30    at System.Net.Sockets.Tests.SocketAsyncExtensions.<>c__DisplayClass3_0.<ReceiveAsync>b__0(Object _, SocketAsyncEventArgs args)
15:06:30    at System.Net.Sockets.Tests.SocketAsyncExtensions.ReceiveAsync(Socket socket, SocketAsyncEventArgs eventArgs, IList`1 buffers, SocketFlags flags, Action`1 handler)
15:06:30    at System.Net.Sockets.Tests.SendReceive.<>c__DisplayClass3_3.<SendRecvAsync_Stream_TCP>b__2(Int32 received)
15:06:30    at System.Net.Sockets.Tests.SocketAsyncExtensions.<>c__DisplayClass3_0.<ReceiveAsync>b__0(Object _, SocketAsyncEventArgs args)
15:06:30    at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
15:06:30    at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
15:06:30    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
15:06:30    at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
15:06:30    at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketError socketError)
15:06:30    at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallback(Int32 bytesTransferred, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError socketError)
15:06:30    at System.Net.Sockets.SocketAsyncContext.<>c.<ReceiveFromAsync>b__39_0(Object args)
15:06:30    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
15:06:30    at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
15:06:30    at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/1414/console

And slightly different but similar here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/1480/console

**Comment by stephentoub** [comment]
Same issue here (but with SendRecvApm_Stream_TCP):
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/1523/consoleFull
