### ISSUE TITLE
BeginSendToV4IPEndPointToDualHost_Success failed on Windows in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5894]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/1768/consoleFull

```
05:13:45      System.Net.Sockets.Tests.DualMode.BeginSendToV4IPEndPointToDualHost_Success [FAIL]
05:13:45         System.Net.Sockets.SocketException : An address incompatible with the requested protocol was used
05:13:45         Stack Trace:
05:13:45   xUnit.net console test runner (64-bit .NET Core)
05:13:45            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(3077,0): at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
05:13:45            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(3015,0): at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
05:13:45            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\SocketTaskExtensions.cs(235,0): at System.Net.Sockets.SocketTaskExtensions.<>c.<SendToAsync>b__12_0(ArraySegment`1 targetBuffer, SocketFlags flags, EndPoint endPoint, AsyncCallback callback, Object state)
05:13:45               at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
05:13:45               at System.Threading.Tasks.TaskFactory`1.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
05:13:45            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\SocketTaskExtensions.cs(234,0): at System.Net.Sockets.SocketTaskExtensions.SendToAsync(Socket socket, ArraySegment`1 buffer, SocketFlags socketFlags, EndPoint remoteEndPoint)
05:13:45            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\Common\src\System\Net\Sockets\SocketAPMExtensions.cs(565,0): at System.Net.Sockets.SocketAPMExtensions.BeginSendTo(Socket socket, Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
05:13:45            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Sockets.Legacy\tests\FunctionalTests\DualModeSocketTest.cs(1393,0): at System.Net.Sockets.Tests.DualMode.DualModeBeginSendTo_EndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout)
05:13:45            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Sockets.Legacy\tests\FunctionalTests\DualModeSocketTest.cs(1378,0): at System.Net.Sockets.Tests.DualMode.BeginSendToV4IPEndPointToDualHost_Success()
```

**Comment by stephentoub** [comment]
Failed again here:
```
16:06:34      System.Net.Sockets.Tests.DualMode.BeginSendToV4IPEndPointToDualHost_Success [FAIL]
16:06:34         System.Net.Sockets.SocketException : An address incompatible with the requested protocol was used
16:06:34         Stack Trace:
16:06:34            d:\j\workspace\windows_nt_re---5067c899\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(3025,0): at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
16:06:34            d:\j\workspace\windows_nt_re---5067c899\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(2969,0): at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
16:06:34            d:\j\workspace\windows_nt_re---5067c899\src\System.Net.Sockets\src\System\Net\Sockets\SocketTaskExtensions.cs(235,0): at System.Net.Sockets.SocketTaskExtensions.<>c.<SendToAsync>b__12_0(ArraySegment`1 targetBuffer, SocketFlags flags, EndPoint endPoint, AsyncCallback callback, Object state)
16:06:34               at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
16:06:34            d:\j\workspace\windows_nt_re---5067c899\src\System.Net.Sockets\src\System\Net\Sockets\SocketTaskExtensions.cs(234,0): at System.Net.Sockets.SocketTaskExtensions.SendToAsync(Socket socket, ArraySegment`1 buffer, SocketFlags socketFlags, EndPoint remoteEndPoint)
16:06:34            d:\j\workspace\windows_nt_re---5067c899\src\System.Net.Sockets.Legacy\tests\FunctionalTests\DualModeSocketTest.cs(1190,0): at System.Net.Sockets.Tests.DualMode.DualModeBeginSendTo_EndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout)
16:06:34            d:\j\workspace\windows_nt_re---5067c899\src\System.Net.Sockets.Legacy\tests\FunctionalTests\DualModeSocketTest.cs(1176,0): at System.Net.Sockets.Tests.DualMode.BeginSendToV4IPEndPointToDualHost_Success()
```

**Comment by CIPop** [comment]
Thanks @stephentoub for reporting this.

Reviewing the test code I can't find an obvious reason for this to intermittently fail: the client should be a dual-mode socket (automatic v4/v6 selection) while the server is listening to v6 Any.
This doesn't always repro so it could be some sort of race condition in the dual-mode `Socket` implementation. I'll try to see if I can get a repro in a controlled stress-test environment and get more Net as well as Winsock logs.

**Comment by karelz** [comment]
Tracked as part of #14519.
