### ISSUE TITLE
Failure in MemoryMappedFile tests due to naming conflict

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#600]
#543 fixed related issues, but this just happened in a CI build for #577...

Starting:    MemoryMappedFile.Tests
  ERROR, Loc411: Unexpected exception, System.IO.IOException: Cannot create a file when that file already exists.  
     at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateCore(SafeFileHandle fileHandle, String mapName, HandleInheritability inheritability, MemoryMappedFileAccess access, MemoryMappedFileOptions options, Int64 capacity) in d:\j\workspace\dotnet_corefx_prtest\Config\Release\OS\Windows_NT\Tests\false\label\windows\src\System.IO.MemoryMappedFiles\src\System\IO\MemoryMappedFiles\MemoryMappedFile.cs:line 400
     at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateNew(String mapName, Int64 capacity, MemoryMappedFileAccess access, MemoryMappedFileOptions options, HandleInheritability inheritability) in d:\j\workspace\dotnet_corefx_prtest\Config\Release\OS\Windows_NT\Tests\false\label\windows\src\System.IO.MemoryMappedFiles\src\System\IO\MemoryMappedFiles\MemoryMappedFile.cs:line 313
     at CreateNew.VerifyCreateNew(String strLoc, String mapName, Int64 capacity, MemoryMappedFileAccess access, MemoryMappedFileOptions options, HandleInheritability inheritability) in d:\j\workspace\dotnet_corefx_prtest\Config\Release\OS\Windows_NT\Tests\false\label\windows\src\System.IO.MemoryMappedFiles\tests\MemoryMappedFile\CreateNew.cs:line 325
  Fail: iCountErrors==1
     CreateNew.CreateNewTestCases [FAIL]
        One or more test cases failed.
        Stack Trace:
d:\j\workspace\dotnet_corefx_prtest\Config\Release\OS\Windows_NT\Tests\false\label\windows\src\System.IO.MemoryMappedFiles\tests\MemoryMappedFile\CreateNew.cs(28,0): at CreateNew.CreateNewTestCases()
  Finished:    MemoryMappedFile.Tests
  
  === TEST EXECUTION SUMMARY ===
     MemoryMappedFile.Tests  Total: 7, Errors: 0, Failed: 1, Skipped: 0, Time: 0.345s

**Comment by nslottow** [comment]
More hits in Win32 Release CI builds for #627 and #656

**Comment by stephentoub** [comment]
Fixed in #672
