### ISSUE TITLE
CurlException during 'dotnet restore' in Ubuntu when redirected to certain CDN servers

### ISSUE THREAD

**Issue by DavidObando** [dotnet/corefx#6079]
Ubuntu 14.04 LTS. Reproduced in the Performance repository for ASP.NET. **The exact same scenario succeeds in Windows**.

Repro code:
```C#
using System;
using System.Diagnostics;
using System.IO;
using System.Net.Http;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var url1 = @"https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/runtime.ubuntu.14.04-x64.runtime.native.system.security.cryptography/1.0.1-rc2-23805/runtime.ubuntu.14.04-x64.runtime.native.system.security.cryptography.1.0.1-rc2-23805.nupkg";
            var url2 = @"https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.server.kestrel/1.0.0-rc2-16391/microsoft.aspnetcore.server.kestrel.1.0.0-rc2-16391.nupkg";
            
            //this one succeeds always
            Test(url1);
            
            //this one fails in Linux, succeeds in Windows
            Test(url2);
        }
        
        public static void Test(string url)
        {
            Console.WriteLine(url);
            var client = new HttpClient();
            
            var webstask = client.GetAsync(url);
            var result = webstask.Result;
            if(result.IsSuccessStatusCode)
            {
                Console.WriteLine("Success");
                var readtask = result.Content.ReadAsByteArrayAsync();
                var bytes = readtask.Result;
                Console.WriteLine("Read {0} bytes", bytes.Length);
            }
            else
            {
                Console.Write("Failed with status code {0}", result.StatusCode);
            }
        }
    }
}
```

This program will succeed to run in Windows but fail in Linux with the following exception:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Peer certificate cannot be authenticated with given CA certificates
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(EasyRequest completedOperation, CURLcode messageResult)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ConsoleApplication.Program.Test(String url)
   at ConsoleApplication.Program.Main(String[] args)
```

We found this by getting [HelloWorldMvc](https://github.com/aspnet/Performance/tree/dev/testapp/HelloWorldMvc) and trying to `dotnet restore -s https://myget.org/f/dotnet-core -s https://myget.org/f/aspnetcidev -s https://api.nuget.org/v3/index.json`.   The result is a number of messages indicating `An error occurred while sending the request.` and failure to load one or multiple packages. Note however that some packages will actually succeed.

We identified that when requesting for nuget packages we get 302 redirected to CDN nodes. In the repro code above, the first URL will 302 redirect to a blob file under a `windows.net` domain. The second URL 302 redirects to a `kxcdn.com`. The certificate for this CDN node was issued by COMODO RSA Domain Validation Secure Server CA.

I took Fiddler traces on Windows to see if anything was suspicious about the requests or responses, but so far I haven't identified anything. Here's a copy of the response headers I saw.

Success case:
```
GET https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/runtime.ubuntu.14.04-x64.runtime.native.system.security.cryptography/1.0.1-rc2-23805/runtime.ubuntu.14.04-x64.runtime.native.system.security.cryptography.1.0.1-rc2-23805.nupkg

HTTP/1.1 302 Found
Cache-Control: private, s-maxage=0
Content-Type: text/html; charset=utf-8
Location: https://dotnetmyget.blob.core.windows.net/privatefeeddotnet0core/runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography-1.0.1-rc2-23805?sv=2014-02-14&sr=b&sig=hTjHAsbpKJ2DujU2qrQH%2FNYlRRV4suZQLwi4A6RFHXI%3D&st=2016-02-12T18:55:00Z&se=2016-02-12T20:05:00Z&sp=r&rscc=max-age%3D3600&rsct=binary%2Foctet-stream&rscd=filename%3Druntime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.1.0.1-rc2-23805.nupkg
Server: Microsoft-IIS/8.5
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Date: Fri, 12 Feb 2016 19:20:50 GMT
Content-Length: 577

----------->

GET https://dotnetmyget.blob.core.windows.net/privatefeeddotnet0core/runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography-1.0.1-rc2-23805?sv=2014-02-14&sr=b&sig=hTjHAsbpKJ2DujU2qrQH%2FNYlRRV4suZQLwi4A6RFHXI%3D&st=2016-02-12T18:55:00Z&se=2016-02-12T20:05:00Z&sp=r&rscc=max-age%3D3600&rsct=binary%2Foctet-stream&rscd=filename%3Druntime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.1.0.1-rc2-23805.nupkg

HTTP/1.1 200 OK
Cache-Control: max-age=3600
Content-Length: 37506
Content-Type: binary/octet-stream
Content-MD5: AqSICrowLpVQZrsGBsbipQ==
Last-Modified: Fri, 05 Feb 2016 07:22:40 GMT
Accept-Ranges: bytes
ETag: "0x8D32DFD220326C7"
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 065fa41c-0001-000a-37ca-657f0c000000
x-ms-version: 2014-02-14
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
Content-Disposition: filename=runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.1.0.1-rc2-23805.nupkg
Date: Fri, 12 Feb 2016 19:20:52 GMT
```

Fail case:
```
GET https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.server.kestrel/1.0.0-rc2-16391/microsoft.aspnetcore.server.kestrel.1.0.0-rc2-16391.nupkg

HTTP/1.1 302 Found
Cache-Control: private, s-maxage=0
Content-Type: text/html; charset=utf-8
Location: https://myget-2e16.kxcdn.com/privatefeedaspnetcidev/Microsoft.AspNetCore.Server.Kestrel-1.0.0-rc2-16391?sv=2014-02-14&sr=b&sig=OfWatRJb4qdl29OJDx9PmotBAeNZeyhx3nqHqqJ0260%3D&st=2016-02-12T18%3A55%3A00Z&se=2016-02-12T20%3A05%3A00Z&sp=r&rscc=max-age%3D3600&rsct=binary%2Foctet-stream&rscd=filename%3DMicrosoft.AspNetCore.Server.Kestrel.1.0.0-rc2-16391.nupkg
Server: Microsoft-IIS/8.5
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Date: Fri, 12 Feb 2016 19:21:01 GMT
Content-Length: 504

----------->

GET https://myget-2e16.kxcdn.com/privatefeedaspnetcidev/Microsoft.AspNetCore.Server.Kestrel-1.0.0-rc2-16391?sv=2014-02-14&sr=b&sig=OfWatRJb4qdl29OJDx9PmotBAeNZeyhx3nqHqqJ0260%3D&st=2016-02-12T18%3A55%3A00Z&se=2016-02-12T20%3A05%3A00Z&sp=r&rscc=max-age%3D3600&rsct=binary%2Foctet-stream&rscd=filename%3DMicrosoft.AspNetCore.Server.Kestrel.1.0.0-rc2-16391.nupkg

HTTP/1.1 200 OK
Server: keycdn-engine
Date: Fri, 12 Feb 2016 19:21:01 GMT
Content-Type: binary/octet-stream
Content-Length: 698348
Connection: keep-alive
Cache-Control: max-age=3600
Content-MD5: IOWe07QD6QTPyvhA0dSGpQ==
Last-Modified: Tue, 09 Feb 2016 07:00:20 GMT
ETag: "0x8D3311EACA7E862"
x-ms-request-id: f4df10d2-0001-0010-1cc9-65c4fc000000
x-ms-version: 2014-02-14
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
Content-Disposition: filename=Microsoft.AspNetCore.Server.Kestrel.1.0.0-rc2-16391.nupkg
X-Cache: HIT
X-Edge-Location: usse
Access-Control-Allow-Origin: *
Accept-Ranges: bytes
```

**Note** we can still restore the packages by using `dnu restore` instead. For some reason `dnu` isn't affected by this issue.

**Comment by davidsh** [comment]
cc: @stephentoub @joshfree

**Comment by stephentoub** [comment]
I just ran your repro on Ubuntu and see:
```
https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/runtime.ubuntu.14.04-x64.runtime.native.system.security.cryptography/1.0.1-rc2-23805/runtime.ubuntu.14.04-x64.runtime.native.system.security.cryptography.1.0.1-rc2-23805.nupkg
Success
Read 37506 bytes
https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.server.kestrel/1.0.0-rc2-16391/microsoft.aspnetcore.server.kestrel.1.0.0-rc2-16391.nupkg
Success
Read 698348 bytes
```
What build of System.Net.Http.dll is this?  From what package did System.Net.Http.Native.so come?

**Comment by stephentoub** [comment]
cc: @bartonjs

**Comment by DavidObando** [comment]
@stephentoub My project.json.lock file indicates 1.0.1-rc2-23805. Let me know if you need any additional data.

**Comment by stephentoub** [comment]
Can you try 1.0.1-rc3-23808?

**Comment by stephentoub** [comment]
I actually don't know where 1.0.1-rc2-23805 would even come from; our dotnet-core feed uses the rc3 moniker now, and our dotnet-core-rel feed which still uses the rc2 moniker doesn't appear to have that new packages yet.

What package is that the version number for?

**Comment by DavidObando** [comment]
Same result with 1.0.1-rc3-23808. To your other question, package.lock.json indicates native comes from `/home/davidobando/.nuget/packages/runtime.ubuntu.14.04-x64.runtime.native.System.Net.Http/1.0.1-rc2-23808/runtimes/ubuntu.14.04-x64/native/`.

The project.json I'm using for the repro code looks like this now:
```
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": {
        "NETStandard.Library": "1.0.0-rc2-23808",
        "System.Net.Http": "4.0.0-*"
    },

    "frameworks": {
        "dnxcore50": { }
    }
}
```

**Comment by NTaylorMullen** [comment]
Note: we're also seeing this failure in all of our (asp.net) [travis CI builds](https://travis-ci.org/aspnet).

**Comment by stephentoub** [comment]
I believe the problem is that you have an old System.Net.Http.Native.so that's built against the wrong version of libcurl.  I was able to repro this by replacing my good .Native.so with the one David sent me, and the one he sent me is linked to the wrong lib.  He's verifying that switching to a different .Native.so fixes things...

**Comment by bartonjs** [comment]
@stephentoub 23809 was the first build where we had fixed all the build machines to build that library correctly.

**Comment by DavidObando** [comment]
Verified that the issue is fixed starting with build 23809, both r2 and r3.
