### ISSUE TITLE
HTTP response Stream.ReadAsync acts differently from .NET Framework

### ISSUE THREAD

**Issue by joelverhagen** [dotnet/corefx#6231]
When an HTTP server closes the connection before sending all of the content, `HttpClient` in the .NET Framework throws a `System.IO.IOException`. .NET Core treats this as an acceptable end of content and throws no exception. This occurs when the server sends `Content-Length`. When using `Transfer-Encoding: chunked`, both .NET Framework and .NET Core throw a `System.IO.IOException` but the inner exceptions seem like the error is being handled differently.

Oddly, when using HTTP response `Stream.Read` (not `async`), `Content-Length` works just fine in both .NET Core and .NET Framework and `Transfer-Encoding: chunked` throws in both cases.

I tested .NET Core with `dnx run` and `dotnet run` and tested .NET Framework with Visual Studio 2015's F5 experience in a .csproj as well as `dnx run`. I have not tested this on any other operating system.

Library versions and a minimal repro are available in this project.
[CloseTooEarly.zip](https://github.com/dotnet/corefx/files/137222/CloseTooEarly.zip)

This is concerning because it seems that the .NET Core HTTP client is less strict about the `Content-Length` header, which is (as far as I know) is strong assertion by the server of how much it will sent and should therefore throw to not risk data corruption. Also, there seems to be inconsistency between the `async` and non-`async` cases.

**Comment by joelverhagen** [comment]
The output with .NET Framework, with `Content-Length` and `ReadAsync` is:

<pre>
dnu restore && dnx run

Microsoft .NET Development Utility <b>Clr-x86-1.0.0-rc1-16231</b>

  CACHE https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
  CACHE https://api.nuget.org/v3/index.json
Restoring packages for C:\trash\2016-02-18\EarlyCloseCoreclr\CloseTooEarly\CloseTooEarlyCore\project.json
Writing lock file C:\trash\2016-02-18\EarlyCloseCoreclr\CloseTooEarly\CloseTooEarlyCore\project.lock.json
Restore complete, 637ms elapsed

NuGet Config files used:
    C:\Users\jver\AppData\Roaming\NuGet\nuget.config
    C:\trash\2016-02-18\EarlyCloseCoreclr\CloseTooEarly\CloseTooEarlyCore\nuget.config

Feeds used:
    https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/
    https://api.nuget.org/v3-flatcontainer/
CLIENT: Starting the request...
SERVER: RECV: GET / HTTP/1.1
SERVER: RECV: Host: localhost:1337
SERVER: RECV: Connection: Keep-Alive
CLIENT: Got the response.
CLIENT: Got the stream.
<b>System.IO.IOException: Unable to read data from the transport connection: The connection was closed.</b>
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.<ReadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CloseTooEarly.Program.<ExecuteAsync>d__2.MoveNext() in C:\trash\2016-02-18\EarlyCloseCoreclr\CloseTooEarly\CloseTooEarlyCore\Program.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at CloseTooEarly.Program.<MainAsync>d__1.MoveNext() in C:\trash\2016-02-18\EarlyCloseCoreclr\CloseTooEarly\CloseTooEarlyCore\Program.cs:line 22
</pre>

**Comment by joelverhagen** [comment]
The output with .NET Core, with `Content-Length` and `ReadAsync` is:

<pre>
dotnet restore && dotnet run

log  : Restoring packages for C:\trash\2016-02-18\EarlyCloseCoreclr\CloseTooEarly\CloseTooEarlyCore\project.json...
info : Committing restore...
log  : Restore completed in 1815ms.
NuGet Config files used:
    C:\trash\2016-02-18\EarlyCloseCoreclr\CloseTooEarly\CloseTooEarlyCore\NuGet.Config
    C:\Users\jver\AppData\Roaming\NuGet\NuGet.Config
Feeds used:
    https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
    https://api.nuget.org/v3/index.json
Project CloseTooEarlyCore (<b>DNXCore,Version=v5.0</b>) will be compiled because some of its inputs were newer than its oldest output.
Compiling CloseTooEarlyCore for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:02.3505584


CLIENT: Starting the request...
SERVER: RECV: GET / HTTP/1.1
SERVER: RECV: Connection: Keep-Alive
SERVER: RECV: Accept-Encoding: gzip, deflate
SERVER: RECV: Host: localhost:1337
CLIENT: Got the response.
CLIENT: Got the stream.
CLIENT: Got the content.
CLIENT: Foo. 2d4d79a1-e8c7-41b6-9666-3514c48898e5.
</pre>

No exception is thrown.
