### ISSUE TITLE
Commit edbd7ba / PR 6147 is causing test failures in internal TFS builds 

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/corefx#6239]
Regarding: 

https://github.com/dotnet/corefx/commit/edbd7ba720699bbe20753872ac430f0b3fdaf3a9 (PR #6147) 

This commit seems to be causing a lot of failures in the internal TFS runs with the exception of this sort: 

CoreCLR: 

```
Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
  File name: 'System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
     at System.Net.Http.WinHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
     at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

<snipped>
```

Net Native: 
``` 
but encountered exception net_http_client_execution_error ---> System.Net.Http.HttpRequestException: net_http_client_execution_error ---> System.TypeInitializationException: TypeInitialization_Type_NoTypeAvailable ---> System.Exception: Method 'DiagnosticListener..ctor(string)' was not included in compilation, but was referenced in HttpHandlerToFilter..cctor(). There may have been a missing assembly.
     at System.Net.Http.HttpHandlerToFilter..cctor()
     at System.Runtime.CompilerServices.ClassConstructorRunner.Call(IntPtr pfn)
     at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(Void* returnValue, StaticClassConstructionContext* pContext, IntPtr pfnCctor) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\ClassConstructorRunner.cs:line 72
     Exception_EndOfInnerExceptionStack

<snipped> 
```

These are failing from run numbers 23818.00 (ProjectK branch), and private runs (N from K)
Exception in more detail: https://gist.github.com/iamjasonp/4f47c687c0a62ff16261

/cc: @davidsh @stephentoub

**Comment by stephentoub** [comment]
I think David fixed this yesterday.

**Comment by davidsh** [comment]
Yes, I fixed this already.

**Comment by iamjasonp** [comment]
Thanks for the quick response - I'll wait for the next nightly to verify this then.
