### ISSUE TITLE
FileSystemWatcher_Created_WatcherDoesntFollowSymLinkToFolder failed on OS X and Win10

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#6241]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/1052/console
```
23:01:41    CreatedTests.FileSystemWatcher_Created_WatcherDoesntFollowSymLinkToFolder [FAIL]
23:01:41       Didn't observe a symlink created event within 30000ms
23:01:41       Expected: True
23:01:41       Actual:   False
23:01:41       Stack Trace:
23:01:42             at Utility.ExpectEvent(WaitHandle eventOccurred, String eventName, Int32 timeout)
23:01:42             at CreatedTests.FileSystemWatcher_Created_WatcherDoesntFollowSymLinkToFolder()
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/1914/console

**Comment by Priya91** [comment]
failed here:
```
Assert.True() Failure\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.IO.Tests.CreatedTests.FileSystemWatcher_Created_WatcherDoesntFollowSymLinkToFolder() in d:\j\workspace\outerloop_win---097a300f\src\System.IO.FileSystem.Watcher\tests\FileSystemWatcher.Created.cs:line 241
```

**Comment by joshfree** [comment]
moving up to 1.0.0-rtm
