### ISSUE TITLE
Ubuntu builds failing in CI (lack of diskspace?)

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#6242]
e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/nativecomp_ubuntu_debug/628/console
```
04:24:23 Building remotely on Azure0216060553 (auto-ubuntu1404-20160211) in workspace /mnt/j/workspace/dotnet_corefx/nativecomp_ubuntu_debug
04:24:23 [WS-CLEANUP] Deleting project workspace...
04:24:23 java.io.IOException: Failed to mkdirs: /mnt/j/workspace/dotnet_corefx/nativecomp_ubuntu_debug
04:24:23 	at hudson.FilePath.mkdirs(FilePath.java:1163)
04:24:23 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
04:24:23 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
04:24:23 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
04:24:23 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
04:24:23 	at hudson.model.Run.execute(Run.java:1738)
04:24:23 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
04:24:23 	at hudson.model.ResourceController.execute(ResourceController.java:98)
04:24:23 	at hudson.model.Executor.run(Executor.java:410)
```
cc: @mmitche, @Priya91

**Comment by stephentoub** [comment]
@mmitche deleted the offending VMs.
