### ISSUE TITLE
FSW.EnableRaisingEvents test failed due to too many inotify handles

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#6314]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/rhel7.2_release_tst/39/console
```
09:59:06    FileSystemWatcherTests.FileSystemWatcher_EnableRaisingEvents [FAIL]
09:59:06       System.IO.IOException : The configured user limit (128) on the number of inotify instances has been reached.
09:59:06       Stack Trace:
09:59:07             at System.IO.FileSystemWatcher.StartRaisingEvents()
09:59:07             at FileSystemWatcherTests.FileSystemWatcher_EnableRaisingEvents()
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/centos7.1_debug_tst_prtest/2292/console

**Comment by mellinoe** [comment]
Different test, seems to be same issue:

````
11:36:37    FileSystemWatcherTests.FileSystemWatcher_WatchingAliasedFolderResolvesToRealPathWhenWatching [FAIL]
11:36:37       System.IO.IOException : The configured user limit (128) on the number of inotify instances has been reached.
````
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/centos7.1_debug_tst_prtest/3047/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/5660
