### ISSUE TITLE
XmlWriterApi TCEOFHandling test failing on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#6331]
It's not handling new lines properly.

**Comment by sepidehMS** [comment]
@stephentoub I could not repro this. Is this still an issue?

**Comment by stephentoub** [comment]
Yes, it still repros.  After I removed the [ActiveIssue] attribute that was on it, running it on Ubuntu gives:
```
Expected: True
Actual  : False
	Check for combinations of NewLine characters in element with 'Replace'
unexpected exception happened:Expected and actual output differ!
   at OLEDB.Test.ModuleCore.CError.Compare(Object actual, Object expected, String message)
   at OLEDB.Test.ModuleCore.CError.Compare(Boolean equal, String message)
   at System.Xml.Tests.TCEOFHandling.VerifyOutput(String expected)
   at System.Xml.Tests.TCEOFHandling.EOF_Handling_03()
   at OLEDB.Test.ModuleCore.CVariation.Execute()
   at OLEDB.Test.ModuleCore.CTestCase.Execute()
	 FAILED
ERROR: Expected and actual output differ!
Expected: True
Actual  : False
	Check for combinations of NewLine characters and entities in element with 'Replace'
unexpected exception happened:Expected and actual output differ!
   at OLEDB.Test.ModuleCore.CError.Compare(Object actual, Object expected, String message)
   at OLEDB.Test.ModuleCore.CError.Compare(Boolean equal, String message)
   at System.Xml.Tests.TCEOFHandling.VerifyOutput(String expected)
   at System.Xml.Tests.TCEOFHandling.EOF_Handling_05()
   at OLEDB.Test.ModuleCore.CVariation.Execute()
   at OLEDB.Test.ModuleCore.CTestCase.Execute()
	 FAILED
ERROR: Expected and actual output differ!
Expected: True
Actual  : False
	Check for tab character in element with 'Replace'
unexpected exception happened:Expected and actual output differ!
   at OLEDB.Test.ModuleCore.CError.Compare(Object actual, Object expected, String message)
   at OLEDB.Test.ModuleCore.CError.Compare(Boolean equal, String message)
   at System.Xml.Tests.TCEOFHandling.VerifyOutput(String expected)
   at System.Xml.Tests.TCEOFHandling.EOF_Handling_06()
   at OLEDB.Test.ModuleCore.CVariation.Execute()
   at OLEDB.Test.ModuleCore.CTestCase.Execute()
	 FAILED
ERROR: Incorect default value for XmlWriter.Settings.NewLineChars
Expected: 

Actual  : 

	NewLineChars and IndentChars Default values and test for proper indentation, Entitize
unexpected exception happened:Incorect default value for XmlWriter.Settings.NewLineChars
   at OLEDB.Test.ModuleCore.CError.Compare(Object actual, Object expected, String message)
   at System.Xml.Tests.TCEOFHandling.EOF_Handling_11()
   at OLEDB.Test.ModuleCore.CVariation.Execute()
   at OLEDB.Test.ModuleCore.CTestCase.Execute()
	 FAILED
ERROR: Incorect default value for XmlWriter.Settings.NewLineChars
Expected: 

Actual  : 

	NewLineChars and IndentChars Default values and test for proper indentation, None
unexpected exception happened:Incorect default value for XmlWriter.Settings.NewLineChars
   at OLEDB.Test.ModuleCore.CError.Compare(Object actual, Object expected, String message)
   at System.Xml.Tests.TCEOFHandling.EOF_Handling_11()
   at OLEDB.Test.ModuleCore.CVariation.Execute()
   at OLEDB.Test.ModuleCore.CTestCase.Execute()
	 FAILED
ERROR: Incorect default value for XmlWriter.Settings.NewLineChars
Expected: 

Actual  : 

	NewLineChars and IndentChars Default values and test for proper indentation, Replace
unexpected exception happened:Incorect default value for XmlWriter.Settings.NewLineChars
   at OLEDB.Test.ModuleCore.CError.Compare(Object actual, Object expected, String message)
   at System.Xml.Tests.TCEOFHandling.EOF_Handling_11()
   at OLEDB.Test.ModuleCore.CVariation.Execute()
   at OLEDB.Test.ModuleCore.CTestCase.Execute()
	 FAILED
ERROR: Expected and actual output differ!
Expected: True
Actual  : False
	Sanity tests for various types of nodes with 'Replace'
unexpected exception happened:Expected and actual output differ!
   at OLEDB.Test.ModuleCore.CError.Compare(Object actual, Object expected, String message)
   at OLEDB.Test.ModuleCore.CError.Compare(Boolean equal, String message)
   at System.Xml.Tests.TCEOFHandling.VerifyOutput(String expected)
   at System.Xml.Tests.TCEOFHandling.EOF_Handling_17()
   at OLEDB.Test.ModuleCore.CVariation.Execute()
   at OLEDB.Test.ModuleCore.CTestCase.Execute()
	 FAILED
ERROR: Expected and actual output differ!
Expected: True
Actual  : False
	Wrapped writer tests for various types of nodes with 'Replace'
unexpected exception happened:Expected and actual output differ!
   at OLEDB.Test.ModuleCore.CError.Compare(Object actual, Object expected, String message)
   at OLEDB.Test.ModuleCore.CError.Compare(Boolean equal, String message)
   at System.Xml.Tests.TCEOFHandling.VerifyOutput(String expected)
   at System.Xml.Tests.TCEOFHandling.EOF_Handling_19()
   at OLEDB.Test.ModuleCore.CVariation.Execute()
   at OLEDB.Test.ModuleCore.CTestCase.Execute()
	 FAILED
ERROR: Expected and actual output differ!
Expected: True
Actual  : False
	Wrapped writer tests for various types of nodes with 'None'
unexpected exception happened:Expected and actual output differ!
   at OLEDB.Test.ModuleCore.CError.Compare(Object actual, Object expected, String message)
   at OLEDB.Test.ModuleCore.CError.Compare(Boolean equal, String message)
   at System.Xml.Tests.TCEOFHandling.VerifyOutput(String expected)
   at System.Xml.Tests.TCEOFHandling.EOF_Handling_19()
   at OLEDB.Test.ModuleCore.CVariation.Execute()
   at OLEDB.Test.ModuleCore.CTestCase.Execute()
	 FAILED
Pass:94, Fail:9, Skip:0
   System.Xml.Tests.XmlWriterTestModule.TCEOFHandling [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   9
```
and to confirm it's not just my box, I did a run in Jenkins and it fails in the same way:
https://github.com/stephentoub/corefx/commit/84b5cfeaabcd60e9ee00facce7e1b5591196e5ca
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu14.04_debug_prtest/16/
