### ISSUE TITLE
Failing test with Japanese characters in SqlTypeTest.SqlStringValidComparisonTest on Linux

### ISSUE THREAD

**Issue by corivera** [dotnet/corefx#6375]
System.Data.SqlClient.ManualTesting.Tests.SqlTypeTest.SqlStringValidComparisonTest [FAIL]
        Error (Default Comparison Option with Operator): ﾌｧｽﾞ･ｷﾞﾀｰ and ファズ・ギター should be equal
        Expected: True
        Actual:   False
        Stack Trace:
              at System.Data.SqlClient.ManualTesting.Tests.SqlTypeTest.SqlStringDefaultCompareOptionTest(Int32 localeID)
              at System.Data.SqlClient.ManualTesting.Tests.SqlTypeTest.SqlStringValidComparisonTest()

**Comment by kkurni** [comment]
Related issue which seems out of our control. https://github.com/dotnet/corefx/issues/5022
