### ISSUE TITLE
Incorrect number of pools in ConnectionPool.ClearAllPoolsTest

### ISSUE THREAD

**Issue by corivera** [dotnet/corefx#6381]
System.Data.SqlClient.ManualTesting.Tests.ConnectionPool.ConnectionPool_Nwnd9Mars [FAIL]
        Incorrect number of pools exist
        Expected: True
        Actual:   False
        Stack Trace:
              at System.Data.SqlClient.ManualTesting.Tests.ConnectionPool.ClearAllPoolsTest(String connectionString)
              at System.Data.SqlClient.ManualTesting.Tests.ConnectionPool.RunDataTestForSingleConnString(String tcpConnectionString, String npConnectionString, Boolean serverIsKatmaiOrLater)
              at System.Data.SqlClient.ManualTesting.Tests.ConnectionPool.ConnectionPool_Nwnd9Mars()

**Comment by corivera** [comment]
CC @saurabh500 @kkurni

**Comment by corivera** [comment]
Doesn't repro when running ConnectionPoolTest by itself, but occurs frequently when running the whole test suite. This might be caused by XUnit parallel test execution (but still merits bug investigation)
