### ISSUE TITLE
Exception caused by connection closed in DDAsyncTest on Linux

### ISSUE THREAD

**Issue by corivera** [dotnet/corefx#6382]
System.Data.SqlClient.ManualTesting.Tests.DDAsyncTest.ExecuteCommand_WithSharedConnection_ShouldPerformAsyncByDefault [FAIL]
        System.AggregateException : One or more errors occurred. (Invalid operation. The connection is closed.)
        ---- System.InvalidOperationException : Invalid operation. The connection is closed.
        Stack Trace:
              at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
              at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
              at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
              at System.Data.SqlClient.ManualTesting.Tests.DDAsyncTest.ExecuteCommand_WithSharedConnection_ShouldPerformAsyncByDefault()
           ----- Inner Stack Trace -----
              at System.Data.SqlClient.SqlConnection.GetOpenTdsConnection()
              at System.Data.SqlClient.SqlCommand.WaitForAsyncResults(IAsyncResult asyncResult)
              at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod)
              at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
              at System.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

**Comment by corivera** [comment]
CC @saurabh500 @kkurni

**Comment by corivera** [comment]
Doesn't repro when running DDAsyncTest by itself. Might be a race condition caused by XUnit parallel test execution.

**Comment by corivera** [comment]
Possibly related to https://github.com/dotnet/corefx/issues/6571

**Comment by corivera** [comment]
Fixed by https://github.com/dotnet/corefx/commit/a7b286cee2cd8f2bcb9779923feee3af46f84ab5
