### ISSUE TITLE
StateObj still has outstanding writes in AsyncTest.FailureTest

### ISSUE THREAD

**Issue by corivera** [dotnet/corefx#6383]
System.Data.SqlClient.ManualTesting.Tests.AsyncTest.FailureTest [FAIL]
        FAILED: Thrown exception for ExecuteReaderAsync was not an InvalidOperationException: System.Diagnostics.Debug+DebugAssertException: StateObj still has outstanding async writes

           at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
           at System.Environment.get_StackTrace()
           at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
           at System.Data.SqlClient.TdsParserStateObject.AssertStateIsClean()
           at System.Data.SqlClient.TdsParser.PutSession(TdsParserStateObject session)
           at System.Data.SqlClient.TdsParserStateObject.CloseSession()
           at System.Data.SqlClient.SqlCommand.PutStateObject()
           at System.Data.SqlClient.SqlCommand.ReliablePutStateObject()
           at System.Data.SqlClient.SqlCommand.BeginExecuteReaderInternal(CommandBehavior behavior, AsyncCallback callback, Object stateObject, Int32 timeout, Boolean asyncWrite)
           at System.Data.SqlClient.SqlCommand.BeginExecuteReaderAsync(CommandBehavior behavior, AsyncCallback callback, Object stateObject)
           at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1](Func`4 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, Object state, TaskCreationOptions creationOptions)
           at System.Threading.Tasks.TaskFactory`1.FromAsync[TArg1](Func`4 beginMethod, Func`2 endMethod, TArg1 arg1, Object state)
           at System.Data.SqlClient.SqlCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
           at System.Data.SqlClient.SqlCommand.ExecuteReaderAsync()
           at System.Data.SqlClient.ManualTesting.Tests.AsyncTest.FailureTest()

**Comment by corivera** [comment]
CC @saurabh500 @kkurni

**Comment by corivera** [comment]
Seems to have been fixed by: https://github.com/dotnet/corefx/commit/90db831debbd5da3f07faf9f6c9c5e2b3345aed8

**Comment by corivera** [comment]
Possibly related to https://github.com/dotnet/corefx/issues/6383
