### ISSUE TITLE
System.ObjectDisposedException thrown while trying to compose very large multipart form

### ISSUE THREAD

**Issue by DavidObando** [dotnet/corefx#6479]
I'm not sure if this is by-design, an actual issue, or something else. I'm trying to upload a **very large** file (or set of files) using a multipart form via a POST message, up to 4 GB total message size.

The client that's going to send this very large message is not able to finish creating the data stream before I get a `System.ObjectDisposedException` indicating: `"Safe handle has been closed"`.

The exception is thrown during the execution of the line that reads `stream.Write(buffer, 0, length);` in the repro below. It appears as if the safe handle to the stream has been disposed but I'm still writing to it.

# Affected platforms

I don't have access to OSX. I've repro'ed it under both Windows 10 and Ubuntu 14.04.

# Repro steps

Use this project.json
```JSON
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "NETStandard.Library": "1.0.0-*",
    "System.Net.Http": "4.0.1-*",
    "System.Console": "4.0.0-*"
  },

  "frameworks": {
    "dnxcore50": {
      "imports": "portable-net451+win8"
    }
  },
  "commands": {
    "run": "LargeFileUpload"
  }
}
```

Use this Program.cs
```C#
using System;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace ConsoleApplication
{
    public class RandomDataStreamContent : HttpContent
    {
        private const int DefaultBufferSize = 4096;

        private readonly int _bufferSize;
        private readonly long _desiredLength;

        private readonly Random _random = new Random(DateTime.UtcNow.Millisecond);

        private static long _globalWrittenBytes = 0;

        public RandomDataStreamContent(long desiredLength) :
            this(desiredLength, DefaultBufferSize)
        { }

        public RandomDataStreamContent(long desiredLength, int bufferSize)
        {
            if (bufferSize <= 0)
            {
                throw new ArgumentOutOfRangeException(nameof(bufferSize));
            }

            _bufferSize = bufferSize;
            _desiredLength = desiredLength;
        }

        protected override Task SerializeToStreamAsync(Stream stream, TransportContext context)
        {
            return Task.Run(() =>
            {
                var buffer = new byte[_bufferSize];
                var uploaded = 0;

                while (uploaded < _desiredLength)
                {
                    _random.NextBytes(buffer);
                    var length = buffer.Length;
                    uploaded += length;

                    if (uploaded > _desiredLength)
                    {
                        var delta = (int)(uploaded - _desiredLength);
                        uploaded -= delta;
                        length -= delta;
                    }
                    try
                    {
                        _globalWrittenBytes += length;
                        stream.Write(buffer, 0, length);
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine($"Bytes written to buffer before exception: { _globalWrittenBytes }");
                        Console.WriteLine($"Exception thrown: { e.Message }");
                        throw;
                    }
                }
            });
        }

        protected override bool TryComputeLength(out long length)
        {
            length = _desiredLength;
            return true;
        }
    }

    public class Program
    {
        // this endpoint doesn't matter as we'll not make it to hit the actual endpoint with the payload,
        // we just need a URI that's valid so we can establish a connection
        private const string ApiEndpoint = "http://www.httpbin.org/";
        public static void Main(string[] args)
        {
            const long oneGigabyte = 1024 * 1024 * 1024;
            const int filesToAdd = 4;

            using (var client = new HttpClient())
            {
                using (var form = new MultipartFormDataContent())
                {
                    form.Add(new StringContent("{\"section\" : \"This is a simple JSON content fragment\"}"), "metadata");
                    for (var iter = 0; iter < filesToAdd; ++iter)
                    {
                        var fileName = Guid.NewGuid().ToString().ToLower();
                        var fileContent = GenerateFileContent(fileName, oneGigabyte);
                        form.Add(fileContent, "file", fileName);
                    }

                    var response = client.PostAsync(ApiEndpoint + "api/upload", form).Result;
                    if (!response.IsSuccessStatusCode)
                    {
                        var errorMessage = "Upload failed: " + (int)response.StatusCode + " " + response.ReasonPhrase;
                        throw new Exception(errorMessage + Environment.NewLine + response.Content.ReadAsStringAsync().Result);
                    }
                }
            }
        }

        private static RandomDataStreamContent GenerateFileContent(string fileName, long fileSize)
        {
            var fileContent = new RandomDataStreamContent(fileSize);
            fileContent.Headers.ContentDisposition = new ContentDispositionHeaderValue("form-data")
            {
                Name = "\"files\"",
                FileName = "\"" + fileName + "\""
            };
            fileContent.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
            return fileContent;
        }
    }
}
```
# Expected behavior

The code as it stands should 404 (Not Found) since we're trying to hit an endpoint that doesn't exist. In case you have a WebAPI endpoint where you can upload the large file, it should 200 (OK).

# Actual behavior

The console prints:
```
Bytes written to buffer before exception: 22691840
Exception thrown: A task was canceled.
Unhandled Exception: System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ConsoleApplication.Program.Main(String[] args)
```
And crashes.

**Comment by stephentoub** [comment]
@DavidObando, I think the large size may actually be a red herring, and the real issue is that because it's so large, it's taking a very long time to upload, and you end up hitting the default timeout of 100 seconds set on HttpClient, hence the task getting canceled.  When I add the line:
```C#
client.Timeout = TimeSpan.FromMilliseconds(int.MaxValue);
```
to your repro, that particular error goes away.

**Comment by DavidObando** [comment]
@stephentoub makes sense.  Thanks for taking a look.

**Comment by DavidObando** [comment]
@stephentoub I have a couple of follow-up questions:
1. In the spirit of user friendliness, can we get a more descriptive inner exception in the task cancelled exception? Something indicating the connection timed out?
2. The clock is ticking for this timeout event even though the app is still building the message that's going to be sent. Is this by design?

**Comment by stephentoub** [comment]
@davidsh, can you answer these questions?
