### ISSUE TITLE
SocketAsyncEngine event loop FailFast on OSX

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#6506]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/1447/console
```
16:35:47 CLR: Managed code called FailFast, saying "Exception thrown from SocketAsyncEngine event loop: System.Diagnostics.Debug+DebugAssertException: 
16:35:47 
16:35:47    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
16:35:47    at System.Environment.get_StackTrace()
16:35:47    at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
16:35:47    at System.Net.Sockets.SocketAsyncContext.UnregisterRead()
16:35:47    at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
16:35:47    at System.Net.Sockets.SocketAsyncEngine.EventLoop()
16:35:47    at System.Threading.Tasks.Task.Execute()
16:35:47    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
16:35:47    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
16:35:47    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
16:35:47    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
16:35:47    at System.Diagnostics.Debug.UnixDebugLogger.ShowAssertDialog(String stackTrace, String message, String detailMessage)
16:35:47    at System.Net.Sockets.SocketAsyncContext.UnregisterRead()
16:35:47    at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
16:35:47    at System.Net.Sockets.SocketAsyncEngine.EventLoop()"
16:35:47 ./run-test.sh: line 135: 55204 Abort trap: 6           ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory -notrait Benchmark=true
16:35:47 error: One or more tests failed while running tests from 'System.Net.Sockets.Tests'.  Exit code 134.
```
cc: @ericeil, @pgavlin

**Comment by stephentoub** [comment]
Just hit this again, this time with the added debug assert message: "Unexpected _registeredEvents: None"
```
13:25:46 CLR: Managed code called FailFast, saying "Exception thrown from SocketAsyncEngine event loop: System.Diagnostics.Debug+DebugAssertException: Unexpected _registeredEvents: None
13:25:46 
13:25:46    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
13:25:46    at System.Environment.get_StackTrace()
13:25:46    at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
13:25:46    at System.Net.Sockets.SocketAsyncContext.UnregisterRead()
13:25:46    at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
13:25:46    at System.Net.Sockets.SocketAsyncEngine.EventLoop()
13:25:46    at System.Threading.Tasks.Task.Execute()
13:25:46    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
13:25:46    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
13:25:46    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
13:25:46    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
13:25:46    at System.Diagnostics.Debug.UnixDebugLogger.ShowAssertDialog(String stackTrace, String message, String detailMessage)
13:25:46    at System.Net.Sockets.SocketAsyncContext.UnregisterRead()
13:25:46    at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
13:25:46    at System.Net.Sockets.SocketAsyncEngine.EventLoop()"
```

**Comment by stephentoub** [comment]
Failed again here: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/1515/consoleFull
```
00:50:07 Unexpected _registeredEvents: None
00:50:07 
00:50:07    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
00:50:07    at System.Environment.get_StackTrace()
00:50:07    at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
00:50:07    at System.Net.Sockets.SocketAsyncContext.UnregisterRead()
00:50:07    at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
00:50:07    at System.Net.Sockets.SocketAsyncEngine.EventLoop()
00:50:07    at System.Threading.Tasks.Task.Execute()
00:50:07    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
00:50:07    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
00:50:07    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
00:50:07    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)CLR: Managed code called FailFast, saying "Exception thrown from SocketAsyncEngine event loop: System.Diagnostics.Debug+DebugAssertException: Unexpected _registeredEvents: None
00:50:07 
00:50:07    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
00:50:07    at System.Environment.get_StackTrace()
00:50:07    at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
00:50:07    at System.Net.Sockets.SocketAsyncContext.UnregisterRead()
00:50:07    at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
00:50:07    at System.Net.Sockets.SocketAsyncEngine.EventLoop()
00:50:07    at System.Threading.Tasks.Task.Execute()
00:50:07    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
00:50:07    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
00:50:07    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
00:50:07    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
00:50:07    at System.Diagnostics.Debug.UnixDebugLogger.ShowAssertDialog(String stackTrace, String message, String detailMessage)
00:50:07    at System.Net.Sockets.SocketAsyncContext.UnregisterRead()
00:50:07    at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
00:50:07    at System.Net.Sockets.SocketAsyncEngine.EventLoop()"
00:50:07 ./run-test.sh: line 135: 33837 Abort trap: 6           ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory -notrait Benchmark=true
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/1520/consoleFull
