### ISSUE TITLE
NullReferenceException when calling Socket.SetMulticastOption on ubuntu 14.04

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#6513]
Calling Socket.SetMulticastOption throws a NullReferenceException on ubuntu 14.04.

Example program:
```
using System;
using System.Net;
using System.Net.Sockets;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            int interfaceIndex = 0;
            IPAddress ip = IPAddress.Parse("239.1.2.3");
            int port = 54321;

            Console.WriteLine("Creating socket");
            Socket socket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
            Console.WriteLine("Binding socket");
            socket.Bind(new IPEndPoint(IPAddress.Any, 54321));
            Console.WriteLine("Adding membership");
            socket.SetSocketOption(SocketOptionLevel.IP, SocketOptionName.AddMembership, new MulticastOption(ip, interfaceIndex));
            Console.WriteLine("Done!");
            Console.Read();
        }
    }
}
```
```
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": {
        "NETStandard.Library": "1.0.0-rc2-23728"
    },

    "frameworks": {
        "dnxcore50": { }
    }
}
```

Output:
```
Creating socket
Binding socket
Adding membership

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Sockets.SocketPal.SetMulticastOption(SafeCloseSocket handle, SocketOptionName optionName, MulticastOption optionValue)
   at System.Net.Sockets.Socket.SetMulticastOption(SocketOptionName optionName, MulticastOption MR)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Object optionValue)
   at ConsoleApplication.Program.Main(String[] args)
```

**Comment by stephentoub** [comment]
Thanks for the repro.  I'll take a look...
