### ISSUE TITLE
System.Runtime tests fail on Win10, non en-US culture

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#657]
The code for the Single and Double.TryParse and ToString tests seem to assume OS < Win10 and CultureInfo = en-US.

Here's a failure running on Win10 due to the same infinity issue as #136 

```
DoubleTests.TestToString [FAIL]
        Assert.Equal() Failure
                  Γåô (pos 0)
        Expected: Infinity
        Actual:   Γê₧
                  Γåæ (pos 0)
        Stack Trace:
           D:\Src\corefx\src\System.Runtime\tests\System\Double.cs(181,0): 
                at DoubleTests.TestToString()
     DoubleTests.TestTryParse [FAIL]
        Assert.True() Failure
  Finished:    System.Runtime.Tests
       Stack Trace:
           D:\Src\corefx\src\System.Runtime\tests\System\Double.cs(294,0): 
                 at DoubleTests.TestTryParse()

SingleTests.TestToString [FAIL]
        Assert.Equal() Failure
                  Γåô (pos 0)
        Expected: Infinity
        Actual:   Γê₧
                  Γåæ (pos 0)
        Stack Trace:
           D:\Src\corefx\src\System.Runtime\tests\System\Single.cs(181,0): 
                     at SingleTests.TestToString()
     
SingleTests.TestTryParse [FAIL]
        Assert.True() Failure
        Stack Trace:
           D:\Src\corefx\src\System.Runtime\tests\System\Single.cs(294,0): 
                 at SingleTests.TestTryParse()
```

I did not repro similar issues with non en-US culture, but I think from code inspection it won't work there either (even on Win7 or Win8)...

**Comment by nslottow** [comment]
Closed by #667
