### ISSUE TITLE
Null Argument Exception in AsyncTest.FailureTest on Linux

### ISSUE THREAD

**Issue by corivera** [dotnet/corefx#6571]
System.Data.SqlClient.ManualTesting.Tests.AsyncTest.FailureTest [FAIL]
        System.AggregateException : One or more errors occurred. (Value cannot be null.)
        ---- System.ArgumentNullException : Value cannot be null.
        Stack Trace:
              at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
              at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
              at System.Data.SqlClient.ManualTesting.Tests.AsyncTest.FailureTest()

**Comment by corivera** [comment]
CC @saurabh500 @kkurni
