### ISSUE TITLE
ActionBlockTests.TestFaulting failed (ironically) in lab

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#661]
Starting:    System.Threading.Tasks.Dataflow.Tests
     System.Threading.Tasks.Dataflow.Tests.ActionBlockTests.TestFaulting [FAIL]
        Assert.True() Failure
        Stack Trace:
           d:\j\workspace\dotnet_corefx_prtest\Config\Release\OS\Windows_NT\Tests\false\label\windows\src\System.Threading.Tasks.Dataflow\tests\Dataflow\DataflowTestHelper.cs(22,0): at System.Threading.Tasks.Dataflow.Tests.DataflowTestHelpers.PostRange[T](ITargetBlock`1 target, Int32 lowerBoundInclusive, Int32 upperBoundExclusive, Func`2 selector)
           d:\j\workspace\dotnet_corefx_prtest\Config\Release\OS\Windows_NT\Tests\false\label\windows\src\System.Threading.Tasks.Dataflow\tests\Dataflow\ActionBlockTests.cs(383,0): at System.Threading.Tasks.Dataflow.Tests.ActionBlockTests.<TestFaulting>d__fd.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Finished:    System.Threading.Tasks.Dataflow.Tests
  
  === TEST EXECUTION SUMMARY ===
     System.Threading.Tasks.Dataflow.Tests  Total: 268, Errors: 0, Failed: 1, Skipped: 0, Time: 1.131s

**Comment by stephentoub** [comment]
Addressed with #662
