### ISSUE TITLE
System.Globalization.Tests.NormalizationAll.NormalizeTest fails with OOM on Windows Nano

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#6621]
```
Discovering: System.Globalization.Extensions.Tests
14:12:40 Discovered:  System.Globalization.Extensions.Tests
14:12:40 Starting:    System.Globalization.Extensions.Tests
14:12:40    System.Globalization.Tests.NormalizationAll.NormalizeTest [FAIL]
14:12:40       System.TypeInitializationException : The type initializer for 'System.Globalization.Tests.NormalizationAll' threw an exception.
14:12:40       ---- System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
14:12:40       Stack Trace:
14:12:40             at System.Globalization.Tests.NormalizationAll.NormalizeTest()
14:12:40          ----- Inner Stack Trace -----
14:12:40             at System.Globalization.Tests.NormalizationAll..cctor()
14:12:40 Finished:    System.Globalization.Extensions.Tests
```

Test result [here](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_winnano_debug_tst/6/console)

**Comment by Priya91** [comment]
doesn't repro now.
