### ISSUE TITLE
OOM exceptions from System.Collections Tests on Windows Nano

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#6624]
```
14:10:54 Discovering: System.Collections.Tests
14:10:54 Discovered:  System.Collections.Tests
14:10:55 Starting:    System.Collections.Tests
14:10:58    System.Collections.Tests.InternalHashCodeTests.OutOfBoundsRegression [FAIL]
14:10:58       System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
14:10:58       Stack Trace:
14:10:58             at System.Collections.Tests.TestData.<GetData>d__0.MoveNext()
14:10:58             at System.Collections.Tests.InternalHashCodeTests.OutOfBoundsRegression()
14:11:30    System.Collections.Tests.Perf_List.Clear(size: 10000) [FAIL]
14:11:30       System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
14:11:30       Stack Trace:
14:11:30             at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
14:11:30             at System.Collections.Tests.Perf_List.Clear(Int32 size)
14:11:30    System.Collections.Tests.Perf_List.Clear(size: 100000) [FAIL]
14:11:30       System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
14:11:30       Stack Trace:
14:11:30             at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
14:11:30             at System.Collections.Tests.Perf_List.Clear(Int32 size)
14:11:30 Finished:    System.Collections.Tests
14:11:30 
14:11:30 === TEST EXECUTION SUMMARY ===
```
**System.Collections.Tests  Total: 36399, Errors: 0, Failed: 3, Skipped: 0, Time: 34.902s**

**Comment by Priya91** [comment]
doesn't repro now.
