### ISSUE TITLE
System.Console test failure on Windows Nano

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#6625]
```
14:11:37    WindowAndCursorProps.Title [FAIL]
14:11:37       Assert+WrapperXunitException : File path: d:\j\workspace\outerloop_win---ce410c48\src\System.Console\tests\WindowAndCursorProps.cs. Line: 124
14:11:37       ---- Assert.Equal() Failure
14:11:37                 â†“ (pos 0)
14:11:37       Expected: Title set by unit test
14:11:37       Actual:   
14:11:37                 â†‘ (pos 0)
14:11:37       Stack Trace:
14:11:37             at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
14:11:37             at Assert.Equal(String expected, String actual, String path, Int32 line)
14:11:37             at WindowAndCursorProps.Title()
14:11:37          ----- Inner Stack Trace -----
14:11:37             at Assert.Equal(String expected, String actual, String path, Int32 line)
14:11:37 Finished:    System.Console.Tests
14:11:37 
14:11:37 === TEST EXECUTION SUMMARY ===
14:11:37    System.Console.Tests  Total: 80, Errors: 0, Failed: 1, Skipped: 0, Time: 0.892s
```

Test result [here](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_winnano_debug_tst/6/console)

**Comment by Priya91** [comment]
doesnt repro now.
