### ISSUE TITLE
System.IO.MemoryMappedFiles.Tests fails on Windows Nano

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#6627]
```
14:13:57 Discovering: System.IO.MemoryMappedFiles.Tests
14:13:57 Discovered:  System.IO.MemoryMappedFiles.Tests
14:13:57 Starting:    System.IO.MemoryMappedFiles.Tests
14:13:58    System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_OpenExisting.OpenCreatedFromFile(name: "3b0efb0bc51d4b439626bb3458d74042", rights: CopyOnWrite, inheritability: None) [FAIL]
14:13:58       Assert.Throws() Failure
14:13:58       Expected: typeof(System.IO.IOException)
14:13:58       Actual:   (No exception was thrown)
14:13:58       Stack Trace:
14:13:58             at System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_OpenExisting.OpenCreatedFromFile(String name, MemoryMappedFileRights rights, HandleInheritability inheritability)
14:13:58    System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_OpenExisting.OpenCreatedFromFile(name: "3b0efb0bc51d4b439626bb3458d74042", rights: CopyOnWrite, inheritability: Inheritable) [FAIL]
14:13:58       System.IO.IOException : Cannot create a file when that file already exists
14:13:58       Stack Trace:
14:13:58             at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateCore(FileStream fileStream, String mapName, HandleInheritability inheritability, MemoryMappedFileAccess access, MemoryMappedFileOptions options, Int64 capacity)
14:13:58             at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile(FileStream fileStream, String mapName, Int64 capacity, MemoryMappedFileAccess access, HandleInheritability inheritability, Boolean leaveOpen)
14:13:58             at System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_OpenExisting.OpenCreatedFromFile(String name, MemoryMappedFileRights rights, HandleInheritability inheritability)
```

Test result [here](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_winnano_debug_tst/6/console)

**Comment by Priya91** [comment]
didnt repro in the latest run.
