### ISSUE TITLE
TCWriteValue.writeValue_2 test failing outer loop on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#6692]
e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_rhel7.2_debug_tst/3/consoleFull
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_centos7.1_debug_tst/3/consoleFull
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_opensuse13.2_debug_tst/2/consoleFull
```
16:42:15 Mismatch : expected: <Root>2002-04-03T00:00:00-08:00</Root>
16:42:15  actual: <Root>2002-04-03T00:00:00Z</Root>
16:42:15 	WriteValue(DateTime)
16:42:15 Expected: True (System.Boolean)
16:42:15 Actual  : False (System.Boolean)
16:42:15 
16:42:15 Microsoft.Test.ModuleCore.TestException
16:42:15    at CoreXml.Test.XLinq.FunctionalTests.XNodeBuilderTests.TCWriteValue.writeValue_2()
16:42:15    at Microsoft.Test.ModuleCore.TestVariation.Execute()
16:42:15    at Microsoft.Test.ModuleCore.TestCase.Execute()
16:42:15 	 FAILED
16:42:15 Pass:699, Fail:1, Skip:9
```

**Comment by stephentoub** [comment]
Caused by #6693
