### ISSUE TITLE
Clean build of repo fails on Windows

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/corefx#6786]
I just updated my repo and cleaned everything (with `git clean -xfd`) and when I run `build`, I get the following output:

```
C:\dev\corefx>build
Installing dotnet cli...
Restoring BuildTools version 1.0.25-prerelease-00193...
Unhandled Exception: System.TypeInitializationException: The type initializer for 'NuGet.CommandLine.XPlat.Program' threw an exception. ---> System.NotSupportedException: Specified method is not supported.
   at NuGet.Configuration.EncryptionUtility.DecryptString(String encryptedString)
   at NuGet.Configuration.PackageSourceProvider.ReadCredential(String sourceName)
   at NuGet.Configuration.PackageSourceProvider.ReadPackageSource(SettingValue setting, Boolean isEnabled)
   at NuGet.Configuration.PackageSourceProvider.LoadPackageSources()
   at NuGet.Protocol.Core.v3.CachingSourceProvider..ctor(IPackageSourceProvider packageSourceProvider)
   at NuGet.CommandLine.XPlat.Program..cctor()
   --- End of inner exception stack trace ---
   at NuGet.CommandLine.XPlat.Program.EnsureLog(LogLevel logLevel)
   at NuGet.CommandLine.XPlat.Program.Main(String[] args)
ERROR: Could not restore build tools correctly. See 'C:\dev\corefx\init-tools.log' for more details.
[15:02:01.73] Building Native Libraries...
CMake is a pre-requisite to build this repository but it was not found on the path. Please install CMake from http://www.cmake.org/download/ and ensure it is on your path.
Native component build failed see nativebuild.log for more details.
[15:02:04.10] Building Managed Libraries...
MSBUILD : error MSB1021: Cannot create an instance of the logger. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
Switch: BinClashLogger,C:\dev\corefx\Tools\net45\Microsoft.DotNet.Build.Tasks.dll;LogFile=C:\dev\corefx\binclash.log

[15:02:04.25] Build Exit Code = 1
```

**Comment by akoeplinger** [comment]
Seems to be the same issue as https://github.com/dotnet/cli/issues/1286.

**Comment by twsouthwick** [comment]
Yup, you're right. I removed a feed I had that requires credentials and it worked. I'll close this issue
