### ISSUE TITLE
NullRef Exceptions in Release DataStreamTest

### ISSUE THREAD

**Issue by corivera** [dotnet/corefx#6877]
Starting:    System.Data.SqlClient.ManualTesting.Tests
     System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.RunAllTestsForSingleServer_nwnd9SqlClient_NP [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
           D:\CoreFX\src\System.Data.SqlClient\tests\ManualTests\SQL\DataStreamTest\DataStreamTest.cs(1162,0): at System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.GetStream(String connectionString)
           D:\CoreFX\src\System.Data.SqlClient\tests\ManualTests\SQL\DataStreamTest\DataStreamTest.cs(88,0): at System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.RunAllTestsForSingleServer(String connectionString, Boolean usingNamePipes)
           D:\CoreFX\src\System.Data.SqlClient\tests\ManualTests\SQL\DataStreamTest\DataStreamTest.cs(29,0): at System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.RunAllTestsForSingleServer_nwnd9SqlClient_NP()
     System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.RunAllTestsForSingleServer_nwnd11SqlClient_NP [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
           D:\CoreFX\src\System.Data.SqlClient\tests\ManualTests\SQL\DataStreamTest\DataStreamTest.cs(1162,0): at System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.GetStream(String connectionString)
           D:\CoreFX\src\System.Data.SqlClient\tests\ManualTests\SQL\DataStreamTest\DataStreamTest.cs(88,0): at System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.RunAllTestsForSingleServer(String connectionString, Boolean usingNamePipes)
           D:\CoreFX\src\System.Data.SqlClient\tests\ManualTests\SQL\DataStreamTest\DataStreamTest.cs(55,0): at System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.RunAllTestsForSingleServer_nwnd11SqlClient_NP()
     System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.RunAllTestsForSingleServer_nwnd10SqlClient [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
           D:\CoreFX\src\System.Data.SqlClient\tests\ManualTests\SQL\DataStreamTest\DataStreamTest.cs(1162,0): at System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.GetStream(String connectionString)
           D:\CoreFX\src\System.Data.SqlClient\tests\ManualTests\SQL\DataStreamTest\DataStreamTest.cs(88,0): at System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.RunAllTestsForSingleServer(String connectionString, Boolean usingNamePipes)
     System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.RunAllTestsForSingleServer_nwnd10SqlClient_NP [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
           D:\CoreFX\src\System.Data.SqlClient\tests\ManualTests\SQL\DataStreamTest\DataStreamTest.cs(1162,0): at System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.GetStream(String connectionString)
           D:\CoreFX\src\System.Data.SqlClient\tests\ManualTests\SQL\DataStreamTest\DataStreamTest.cs(88,0): at System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.RunAllTestsForSingleServer(String connectionString, Boolean usingNamePipes)
           D:\CoreFX\src\System.Data.SqlClient\tests\ManualTests\SQL\DataStreamTest\DataStreamTest.cs(42,0): at System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.RunAllTestsForSingleServer_nwnd10SqlClient_NP()
     System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.RunAllTestsForSingleServer_nwnd9SqlClient [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
           D:\CoreFX\src\System.Data.SqlClient\tests\ManualTests\SQL\DataStreamTest\DataStreamTest.cs(1162,0): at System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.GetStream(String connectionString)
           D:\CoreFX\src\System.Data.SqlClient\tests\ManualTests\SQL\DataStreamTest\DataStreamTest.cs(88,0): at System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.RunAllTestsForSingleServer(String connectionString, Boolean usingNamePipes)
  Finished:    System.Data.SqlClient.ManualTesting.Tests
  
  === TEST EXECUTION SUMMARY ===
     System.Data.SqlClient.ManualTesting.Tests  Total: 5, Errors: 0, Failed: 5, Skipped: 0, Time: 7.038s

**Comment by corivera** [comment]
CC @saurabh500 @kkurni
