### ISSUE TITLE
System.Data.SqlClient.Tests.ExceptionTest  fails with updated package

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#6930]
On updating to latest package rc3-23915 this test fails
```
System.Data.SqlClient.Tests.ExceptionTest.IndependentConnectionExceptionTestOpenConnection [FAIL]
               Assert.Throws() Failure
               Expected: typeof(System.Data.SqlClient.SqlException)
               Actual:   typeof(System.TypeInitializationException): The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.
               Stack Trace:
                  E:\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\TdsParser.cs(54,0): at System.Data.SqlClient.TdsParser..ctor(Boolean MARS, Boolean fAsynchronous)
                  E:\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlInternalConnectionTds.cs(1100,0): at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, TimeoutTimer timeout)
```
```
System.Data.SqlClient.Tests.ExceptionTest.ExceptionTests [FAIL]
               Assert.Throws() Failure
               Expected: typeof(System.Data.SqlClient.SqlException)
               Actual:   typeof(System.TypeInitializationException): The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.
               Stack Trace:
                  E:\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\TdsParser.cs(54,0): at System.Data.SqlClient.TdsParser..ctor(Boolean MARS, Boolean fAsynchronous)
                  E:\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlInternalConnectionTds.cs(1100,0): at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, Boolean redirectedUserInstance
         , SqlConnectionString connectionOptions, TimeoutTimer timeout)
                  E:\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlInternalConnectionTds.cs(1014,0): at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionO
         ptions, Boolean redirectedUserInstance)
                  E:\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlInternalConnectionTds.cs(358,0): at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectio
         nOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
                  E:\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlConnectionFactory.cs(133,0): at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Obj
         ect poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
                  E:\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionFactory.cs(114,0): at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, D
         bConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
                  E:\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs(476,0): at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConne
         ctionInternal oldConnection)
                  E:\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs(1187,0): at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, D
         bConnectionInternal oldConnection)
                  E:\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs(792,0): at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout
         , Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                  E:\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs(712,0): at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConn
         ectionOptions userOptions, DbConnectionInternal& connection)
                  E:\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionFactory.cs(287,0): at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 ret
         ry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                  E:\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionInternal.cs(452,0): at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFact
         ory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                  E:\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionClosed.cs(64,0): at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectio
         nFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                  E:\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlConnection.cs(911,0): at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                  E:\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlConnection.cs(541,0): at System.Data.SqlClient.SqlConnection.Open()
                  E:\corefx\src\System.Data.SqlClient\tests\FunctionalTests\ExceptionTest.cs(81,0): at System.Data.SqlClient.Tests.ExceptionTest.GenerateConnectionException(String connectionString)
                  E:\corefx\src\System.Data.SqlClient\tests\FunctionalTests\ExceptionTest.cs(28,0): at System.Data.SqlClient.Tests.ExceptionTest.<>c__DisplayClass5_0.<ExceptionTests>b__0()
```

**Comment by joshfree** [comment]
@saurabh500 can you take a look and determine if this is needed for RC2?

**Comment by saurabh500** [comment]
@corivera, PTAL

**Comment by corivera** [comment]
Doesn't repro for me on rc3-23923
