### ISSUE TITLE
System.IO.Filesystem.Tests fail with package update to rc3-23915

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#6931]
```
**System.IO.Tests.FileInfo_MoveTo.PathWithIllegalCharacters** [FAIL]
               Assert.All() Failure: 3 out of 44 items in the collection did not pass.
               [5]: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
                    Expected: typeof(System.ArgumentException)
                    Actual:   typeof(System.IO.IOException): The specified path is invalid
                       at System.IO.Win32FileSystem.MoveFile(String sourceFullPath, String destFullPath) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 430
                       at System.IO.FileInfo.MoveTo(String destFileName) in E:\corefx\src\System.IO.FileSystem\src\System\IO\FileInfo.cs:line 284
                       at System.IO.Tests.FileInfo_MoveTo.Move(String sourceFile, String destFile) in E:\corefx\src\System.IO.FileSystem\tests\FileInfo\MoveTo.cs:line 13
                       at System.IO.Tests.File_Move.<>c__DisplayClass4_1.<PathWithIllegalCharacters>b__1() in E:\corefx\src\System.IO.FileSystem\tests\File\Move.cs:line 53
                       at Xunit.Assert.RecordException(Action testCode)
```
```
**System.IO.Tests.Directory_CreateDirectory.PathWithInvalidCharactersAsPath_ThrowsArgumentException** [FAIL]
               Assert.All() Failure: 3 out of 44 items in the collection did not pass.
               [5]: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
                    Expected: typeof(System.ArgumentException)
                    Actual:   typeof(System.IO.DirectoryNotFoundException): Could not find a part of the path '\\?\UNC\LOCALHOST'.
                       at System.IO.Win32FileSystem.CreateDirectory(String fullPath) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 147
                       at System.IO.Directory.CreateDirectory(String path) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Directory.cs:line 50
                       at System.IO.Tests.Directory_CreateDirectory.Create(String path) in E:\corefx\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs:line 16
                       at System.IO.Tests.Directory_CreateDirectory.<>c__DisplayClass3_0.<PathWithInvalidCharactersAsPath_ThrowsArgumentException>b__1() in E:\corefx\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs:line 41
                       at Xunit.Assert.RecordException(Func`1 testCode)
```
```
**System.IO.Tests.File_Move.PathWithIllegalCharacters** [FAIL]
               Assert.All() Failure: 3 out of 44 items in the collection did not pass.
               [5]: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
                    Expected: typeof(System.ArgumentException)
                    Actual:   typeof(System.IO.IOException): The specified path is invalid
                       at System.IO.Win32FileSystem.MoveFile(String sourceFullPath, String destFullPath) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 430
                       at System.IO.File.Move(String sourceFileName, String destFileName) in E:\corefx\src\System.IO.FileSystem\src\System\IO\File.cs:line 698
                       at System.IO.Tests.File_Move.Move(String sourceFile, String destFile) in E:\corefx\src\System.IO.FileSystem\tests\File\Move.cs:line 15
                       at System.IO.Tests.File_Move.<>c__DisplayClass4_1.<PathWithIllegalCharacters>b__1() in E:\corefx\src\System.IO.FileSystem\tests\File\Move.cs:line 53
                       at Xunit.Assert.RecordException(Action testCode)
```
```
**System.IO.Tests.DirectoryInfo_Create.PathWithInvalidCharactersAsPath_ThrowsArgumentException** [FAIL]
               Assert.All() Failure: 3 out of 44 items in the collection did not pass.
               [5]: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
                    Expected: typeof(System.ArgumentException)
                    Actual:   typeof(System.IO.DirectoryNotFoundException): Could not find a part of the path '\\?\UNC\LOCALHOST'.
                       at System.IO.Win32FileSystem.CreateDirectory(String fullPath) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 147
                       at System.IO.DirectoryInfo.Create() in E:\corefx\src\System.IO.FileSystem\src\System\IO\DirectoryInfo.cs:line 102
                       at System.IO.Tests.DirectoryInfo_Create.Create(String path) in E:\corefx\src\System.IO.FileSystem\tests\DirectoryInfo\Create.cs:line 16
                       at System.IO.Tests.Directory_CreateDirectory.<>c__DisplayClass3_0.<PathWithInvalidCharactersAsPath_ThrowsArgumentException>b__1() in E:\corefx\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs:line 41
                       at Xunit.Assert.RecordException(Func`1 testCode)
```

**Comment by JeremyKuhne** [comment]
These are by design. We don't do any prevalidation with `\\?\` now as it is near impossible to get right. We let the OS do whatever it will do with the paths. The tests need to be updated to check for `\\?\` and catch the exceptions seen above if present.

**Comment by JeremyKuhne** [comment]
To be more explicit- they should be checking the way PathInternal.IsExtended() does.
