### ISSUE TITLE
FileSystem tests broken with recent Path changes

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#7058]
/cc @JeremyKuhne your change https://github.com/dotnet/corefx/commit/b37b8035c1d693f491545a53b701fe7a01df312e has caused a number of failures in the FileSystem tests.  I hit these when upgrading the packages and was able to isolate it to System.Runtime.Extensions.dll by patching the assembly back to the old version to fix the errors:
```
     System.IO.Tests.DirectoryInfo_Create.PathWithInvalidCharactersAsPath_ThrowsArgumentException [FAIL]
        Assert.All() Failure: 3 out of 44 items in the collection did not pass.
        [5]: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
             Expected: typeof(System.ArgumentException)
             Actual:   typeof(System.IO.DirectoryNotFoundException): Could not find a part of the path '\\?\UNC\LOCALHOST'.
                at System.IO.Win32FileSystem.CreateDirectory(String fullPath) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 147
                at System.IO.DirectoryInfo.Create() in E:\corefx\src\System.IO.FileSystem\src\System\IO\DirectoryInfo.cs:line 102
                at System.IO.Tests.DirectoryInfo_Create.Create(String path) in E:\corefx\src\System.IO.FileSystem\tests\DirectoryInfo\Create.cs:line 16
                at System.IO.Tests.Directory_CreateDirectory.<>c__DisplayClass3_0.<PathWithInvalidCharactersAsPath_ThrowsArgumentException>b__1() in E:\corefx\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs:line 41
                at Xunit.Assert.RecordException(Func`1 testCode)
        [4]: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
             Expected: typeof(System.ArgumentException)
             Actual:   typeof(System.IO.DirectoryNotFoundException): Could not find a part of the path '\\?\UNC\'.
                at System.IO.Win32FileSystem.CreateDirectory(String fullPath) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 147
                at System.IO.DirectoryInfo.Create() in E:\corefx\src\System.IO.FileSystem\src\System\IO\DirectoryInfo.cs:line 102
                at System.IO.Tests.DirectoryInfo_Create.Create(String path) in E:\corefx\src\System.IO.FileSystem\tests\DirectoryInfo\Create.cs:line 16
                at System.IO.Tests.Directory_CreateDirectory.<>c__DisplayClass3_0.<PathWithInvalidCharactersAsPath_ThrowsArgumentException>b__1() in E:\corefx\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs:line 41
                at Xunit.Assert.RecordException(Func`1 testCode)
        [3]: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
             Expected: typeof(System.ArgumentException)
             Actual:   typeof(System.IO.IOException): The specified path is invalid
                at System.IO.Win32FileSystem.CreateDirectory(String fullPath) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 154
                at System.IO.DirectoryInfo.Create() in E:\corefx\src\System.IO.FileSystem\src\System\IO\DirectoryInfo.cs:line 102
                at System.IO.Tests.DirectoryInfo_Create.Create(String path) in E:\corefx\src\System.IO.FileSystem\tests\DirectoryInfo\Create.cs:line 16
                at System.IO.Tests.Directory_CreateDirectory.<>c__DisplayClass3_0.<PathWithInvalidCharactersAsPath_ThrowsArgumentException>b__1() in E:\corefx\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs:line 41
                at Xunit.Assert.RecordException(Func`1 testCode)
        Stack Trace:
           E:\corefx\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs(39,0): at System.IO.Tests.Directory_CreateDirectory.PathWithInvalidCharactersAsPath_ThrowsArgumentException()

     System.IO.Tests.FileInfo_MoveTo.PathWithIllegalCharacters [FAIL]
        Assert.All() Failure: 3 out of 44 items in the collection did not pass.
        [5]: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
             Expected: typeof(System.ArgumentException)
             Actual:   typeof(System.IO.IOException): The specified path is invalid
                at System.IO.Win32FileSystem.MoveFile(String sourceFullPath, String destFullPath) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 430
                at System.IO.FileInfo.MoveTo(String destFileName) in E:\corefx\src\System.IO.FileSystem\src\System\IO\FileInfo.cs:line 284
                at System.IO.Tests.FileInfo_MoveTo.Move(String sourceFile, String destFile) in E:\corefx\src\System.IO.FileSystem\tests\FileInfo\MoveTo.cs:line 13
                at System.IO.Tests.File_Move.<>c__DisplayClass4_1.<PathWithIllegalCharacters>b__1() in E:\corefx\src\System.IO.FileSystem\tests\File\Move.cs:line 53
                at Xunit.Assert.RecordException(Action testCode)
        [4]: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
             Expected: typeof(System.ArgumentException)
             Actual:   typeof(System.IO.IOException): The filename, directory name, or volume label syntax is incorrect
                at System.IO.Win32FileSystem.MoveFile(String sourceFullPath, String destFullPath) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 430
                at System.IO.FileInfo.MoveTo(String destFileName) in E:\corefx\src\System.IO.FileSystem\src\System\IO\FileInfo.cs:line 284
                at System.IO.Tests.FileInfo_MoveTo.Move(String sourceFile, String destFile) in E:\corefx\src\System.IO.FileSystem\tests\FileInfo\MoveTo.cs:line 13
                at System.IO.Tests.File_Move.<>c__DisplayClass4_1.<PathWithIllegalCharacters>b__1() in E:\corefx\src\System.IO.FileSystem\tests\File\Move.cs:line 53
                at Xunit.Assert.RecordException(Action testCode)
        [3]: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
             Expected: typeof(System.ArgumentException)
             Actual:   typeof(System.IO.IOException): The filename, directory name, or volume label syntax is incorrect
                at System.IO.Win32FileSystem.MoveFile(String sourceFullPath, String destFullPath) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 430
                at System.IO.FileInfo.MoveTo(String destFileName) in E:\corefx\src\System.IO.FileSystem\src\System\IO\FileInfo.cs:line 284
                at System.IO.Tests.FileInfo_MoveTo.Move(String sourceFile, String destFile) in E:\corefx\src\System.IO.FileSystem\tests\FileInfo\MoveTo.cs:line 13
                at System.IO.Tests.File_Move.<>c__DisplayClass4_1.<PathWithIllegalCharacters>b__1() in E:\corefx\src\System.IO.FileSystem\tests\File\Move.cs:line 53
                at Xunit.Assert.RecordException(Action testCode)
        Stack Trace:
           E:\corefx\src\System.IO.FileSystem\tests\File\Move.cs(51,0): at System.IO.Tests.File_Move.PathWithIllegalCharacters()

     System.IO.Tests.File_Move.PathWithIllegalCharacters [FAIL]
        Assert.All() Failure: 3 out of 44 items in the collection did not pass.
        [5]: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
             Expected: typeof(System.ArgumentException)
             Actual:   typeof(System.IO.IOException): The specified path is invalid
                at System.IO.Win32FileSystem.MoveFile(String sourceFullPath, String destFullPath) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 430
                at System.IO.File.Move(String sourceFileName, String destFileName) in E:\corefx\src\System.IO.FileSystem\src\System\IO\File.cs:line 698
                at System.IO.Tests.File_Move.Move(String sourceFile, String destFile) in E:\corefx\src\System.IO.FileSystem\tests\File\Move.cs:line 15
                at System.IO.Tests.File_Move.<>c__DisplayClass4_1.<PathWithIllegalCharacters>b__1() in E:\corefx\src\System.IO.FileSystem\tests\File\Move.cs:line 53
                at Xunit.Assert.RecordException(Action testCode)
        [4]: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
             Expected: typeof(System.ArgumentException)
             Actual:   typeof(System.IO.IOException): The filename, directory name, or volume label syntax is incorrect
                at System.IO.Win32FileSystem.MoveFile(String sourceFullPath, String destFullPath) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 430
                at System.IO.File.Move(String sourceFileName, String destFileName) in E:\corefx\src\System.IO.FileSystem\src\System\IO\File.cs:line 698
                at System.IO.Tests.File_Move.Move(String sourceFile, String destFile) in E:\corefx\src\System.IO.FileSystem\tests\File\Move.cs:line 15
                at System.IO.Tests.File_Move.<>c__DisplayClass4_1.<PathWithIllegalCharacters>b__1() in E:\corefx\src\System.IO.FileSystem\tests\File\Move.cs:line 53
                at Xunit.Assert.RecordException(Action testCode)
        [3]: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
             Expected: typeof(System.ArgumentException)
             Actual:   typeof(System.IO.IOException): The filename, directory name, or volume label syntax is incorrect
                at System.IO.Win32FileSystem.MoveFile(String sourceFullPath, String destFullPath) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 430
                at System.IO.File.Move(String sourceFileName, String destFileName) in E:\corefx\src\System.IO.FileSystem\src\System\IO\File.cs:line 698
                at System.IO.Tests.File_Move.Move(String sourceFile, String destFile) in E:\corefx\src\System.IO.FileSystem\tests\File\Move.cs:line 15
                at System.IO.Tests.File_Move.<>c__DisplayClass4_1.<PathWithIllegalCharacters>b__1() in E:\corefx\src\System.IO.FileSystem\tests\File\Move.cs:line 53
                at Xunit.Assert.RecordException(Action testCode)
        Stack Trace:
           E:\corefx\src\System.IO.FileSystem\tests\File\Move.cs(51,0): at System.IO.Tests.File_Move.PathWithIllegalCharacters()

     System.IO.Tests.Directory_CreateDirectory.PathWithInvalidCharactersAsPath_ThrowsArgumentException [FAIL]
        Assert.All() Failure: 3 out of 44 items in the collection did not pass.
        [5]: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
             Expected: typeof(System.ArgumentException)
             Actual:   typeof(System.IO.DirectoryNotFoundException): Could not find a part of the path '\\?\UNC\LOCALHOST'.
                at System.IO.Win32FileSystem.CreateDirectory(String fullPath) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 147
                at System.IO.Directory.CreateDirectory(String path) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Directory.cs:line 50
                at System.IO.Tests.Directory_CreateDirectory.Create(String path) in E:\corefx\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs:line 16
                at System.IO.Tests.Directory_CreateDirectory.<>c__DisplayClass3_0.<PathWithInvalidCharactersAsPath_ThrowsArgumentException>b__1() in E:\corefx\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs:line 41
                at Xunit.Assert.RecordException(Func`1 testCode)
        [4]: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
             Expected: typeof(System.ArgumentException)
             Actual:   typeof(System.IO.DirectoryNotFoundException): Could not find a part of the path '\\?\UNC\'.
                at System.IO.Win32FileSystem.CreateDirectory(String fullPath) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 147
                at System.IO.Directory.CreateDirectory(String path) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Directory.cs:line 50
                at System.IO.Tests.Directory_CreateDirectory.Create(String path) in E:\corefx\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs:line 16
                at System.IO.Tests.Directory_CreateDirectory.<>c__DisplayClass3_0.<PathWithInvalidCharactersAsPath_ThrowsArgumentException>b__1() in E:\corefx\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs:line 41
                at Xunit.Assert.RecordException(Func`1 testCode)
        [3]: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
             Expected: typeof(System.ArgumentException)
             Actual:   typeof(System.IO.IOException): The specified path is invalid
                at System.IO.Win32FileSystem.CreateDirectory(String fullPath) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs:line 154
                at System.IO.Directory.CreateDirectory(String path) in E:\corefx\src\System.IO.FileSystem\src\System\IO\Directory.cs:line 50
                at System.IO.Tests.Directory_CreateDirectory.Create(String path) in E:\corefx\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs:line 16
                at System.IO.Tests.Directory_CreateDirectory.<>c__DisplayClass3_0.<PathWithInvalidCharactersAsPath_ThrowsArgumentException>b__1() in E:\corefx\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs:line 41
                at Xunit.Assert.RecordException(Func`1 testCode)
        Stack Trace:
           E:\corefx\src\System.IO.FileSystem\tests\Directory\CreateDirectory.cs(39,0): at System.IO.Tests.Directory_CreateDirectory.PathWithInvalidCharactersAsPath_ThrowsArgumentException()
```

**Comment by ericstj** [comment]
Duplicate of https://github.com/dotnet/corefx/issues/6931
