### ISSUE TITLE
Ping tests failing in outerloop on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7064]
In several outer loop runs, e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_rhel7.2_release_tst/19/console
many of the ping tests are failing with errors like:
```
11:53:26    System.Net.NetworkInformation.Tests.PingTest.SendPingAsyncWithIPAddressAndTimeoutAndBufferAndPingOptions_Unix [FAIL]
11:53:26       System.Net.Sockets.SocketException : Invalid argument
11:53:26       Stack Trace:
11:53:26             at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
11:53:26             at System.Net.NetworkInformation.Ping.<SendIcmpEchoRequestOverRawSocket>d__34.MoveNext()
11:53:26          --- End of stack trace from previous location where exception was thrown ---
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
11:53:26             at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
11:53:26             at System.Net.NetworkInformation.Ping.<SendPingAsyncCore>d__33.MoveNext()
11:53:26          --- End of stack trace from previous location where exception was thrown ---
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
11:53:26             at System.Net.NetworkInformation.Tests.PingTest.<SendPingAsync>d__21.MoveNext()
11:53:26          --- End of stack trace from previous location where exception was thrown ---
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
11:53:26             at System.Net.NetworkInformation.Tests.PingTest.<SendPingAsyncWithIPAddressAndTimeoutAndBufferAndPingOptions_Unix>d__8.MoveNext()
11:53:26          --- End of stack trace from previous location where exception was thrown ---
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
11:53:26          --- End of stack trace from previous location where exception was thrown ---
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
11:53:26          --- End of stack trace from previous location where exception was thrown ---
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
11:53:26    System.Net.NetworkInformation.Tests.PingTest.Ping_DisposeAfterSend_Success [FAIL]
11:53:26       System.Diagnostics.Debug+DebugAssertException : Invalid status: 0
11:53:26       
11:53:26          at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
11:53:26          at System.Environment.get_StackTrace()
11:53:26          at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
11:53:26          at System.Net.NetworkInformation.Ping.Finish()
11:53:26          at System.Net.NetworkInformation.Ping.<GetAddressAndSendAsync>d__25.MoveNext()
11:53:26          at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
11:53:26          at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
11:53:26          at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
11:53:26          at System.Threading.Tasks.Task.FinishContinuations()
11:53:26          at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
11:53:26          at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
11:53:26          at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
11:53:26          at System.Net.ContextAwareResult.CompleteCallback()
11:53:26          at System.Net.ContextAwareResult.<>c.<Complete>b__17_0(Object s)
11:53:26          at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
11:53:26          at System.Net.ContextAwareResult.Complete(IntPtr userToken)
11:53:26          at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
11:53:26          at System.Net.LazyAsyncResult.InvokeCallback(Object result)
11:53:26          at System.Net.Dns.ResolveCallback(Object context)
11:53:26          at System.Net.Dns.<>c.<HostResolutionBeginHelper>b__6_0(Object s)
11:53:26          at System.Threading.Tasks.Task.Execute()
11:53:26          at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
11:53:26          at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
11:53:26          at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
11:53:26          at System.Threading.ThreadPoolWorkQueue.Dispatch()
11:53:26       Stack Trace:
11:53:26             at System.Diagnostics.Debug.UnixDebugLogger.ShowAssertDialog(String stackTrace, String message, String detailMessage)
11:53:26             at System.Net.NetworkInformation.Ping.Finish()
11:53:26             at System.Net.NetworkInformation.Ping.<GetAddressAndSendAsync>d__25.MoveNext()
11:53:26          --- End of stack trace from previous location where exception was thrown ---
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
11:53:26             at System.Net.NetworkInformation.Tests.PingTest.<Ping_DisposeAfterSend_Success>d__16.MoveNext()
11:53:26          --- End of stack trace from previous location where exception was thrown ---
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
11:53:26          --- End of stack trace from previous location where exception was thrown ---
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
11:53:26          --- End of stack trace from previous location where exception was thrown ---
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
11:53:26             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by mellinoe** [comment]
This is just a call to `new Socket(AddressFamily.InterNetwork, SocketType.Raw, ProtocolType.Icmp)` (or the equivalents for IPv6). Is there anything obvious that has changed to prevent this from working lately, before I start digging around the sockets code? @ericeil

**Comment by stephentoub** [comment]
I'm testing a fix now.
