### ISSUE TITLE
WindowAndCursorProps.Title test fails on Win7

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7082]
```
14:19:45      WindowAndCursorProps.Title [FAIL]
14:19:45         Assert+WrapperXunitException : File path: d:\j\workspace\outerloop_win---9c9e7d59\src\System.Console\tests\WindowAndCursorProps.cs. Line: 121
14:19:45         ---- Assert.Equal() Failure
14:19:45                                           (pos 511)
14:19:45         Expected: úúúaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaúúú
14:19:45         Actual:   úúúaaaaaaaaaaaaaaaaaaaa
14:19:45                                           (pos 511)
14:19:45         Stack Trace:
14:19:45               at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
14:19:45               at Assert.Equal(String expected, String actual, String path, Int32 line)
14:19:45               at WindowAndCursorProps.Title()
14:19:45            ----- Inner Stack Trace -----
14:19:45               at Assert.Equal(String expected, String actual, String path, Int32 line)
```

**Comment by pallavit** [comment]
Interesting...I can't still repro this. Could this be something to do with the way we are running this test in our tree? The code does not seem to be doing anything special at all and I can't think of a way to add logging here either since the work is mostly been done by the OS here.

**Comment by pallavit** [comment]
My bad. Missed the win7 tag on this. Will run the test on win7 and see :).
