### ISSUE TITLE
11 globalization tests failing on Win 7

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7084]
```
14:20:11   Starting:    System.Globalization.Tests
14:20:12      System.Globalization.Tests.DateTimeFormatInfoCalendarWeekRule.CalendarWeekRuleTest(format: DateTimeFormatInfo { AbbreviatedDayNames = ["Sul", "Lun", "Meu.", "Mer.", "Yaou", ...], AbbreviatedMonthGenitiveNames = ["Gen.", "C'hwe.", "Meur.", "Ebr.", "Mae", ...], AbbreviatedMonthNames = ["Gen.", "C'hwe.", "Meur.", "Ebr.", "Mae", ...], AMDesignator = "", Calendar = GregorianCalendar { AlgorithmType = SolarCalendar, CalendarType = Localized, Eras = [...], IsReadOnly = False, MaxSupportedDateTime = 9999-12-31T23:59:59.9999999, ... }, ... }, expected: FirstFullWeek) [FAIL]
14:20:13         Assert.Equal() Failure
14:20:13         Expected: FirstFullWeek
14:20:13         Actual:   FirstDay
14:20:13         Stack Trace:
14:20:13               at System.Globalization.Tests.DateTimeFormatInfoCalendarWeekRule.CalendarWeekRuleTest(DateTimeFormatInfo format, CalendarWeekRule expected)
14:20:13      TextInfoTests.ToUpper(localeName: "") [FAIL]
14:20:14   System.Globalization.Extensions.Tests -> d:\j\workspace\outerloop_win---9c9e7d59\bin\Windows_NT.AnyCPU.Debug\System.Globalization.Extensions.Tests\System.Globalization.Extensions.Tests.dll
14:20:14         Assert.Equal() Failure
14:20:14                     (pos 1)
14:20:14         Expected: ??
14:20:14         Actual:   ??
14:20:14                     (pos 1)
14:20:14         Stack Trace:
14:20:14               at TextInfoTests.ToUpper(String localeName)
14:20:14      TextInfoTests.ToUpper(localeName: "en-US") [FAIL]
14:20:14         Assert.Equal() Failure
14:20:14                     (pos 1)
14:20:14         Expected: ??
14:20:14         Actual:   ??
14:20:14                     (pos 1)
14:20:14         Stack Trace:
14:20:14               at TextInfoTests.ToUpper(String localeName)
14:20:14      TextInfoTests.ToUpper(localeName: "fr") [FAIL]
14:20:14         Assert.Equal() Failure
14:20:14                     (pos 1)
14:20:14         Expected: ??
14:20:14         Actual:   ??
14:20:14                     (pos 1)
14:20:14         Stack Trace:
14:20:14               at TextInfoTests.ToUpper(String localeName)
14:20:14      TextInfoTests.ToLower(localeName: "") [FAIL]
14:20:14         Assert.Equal() Failure
14:20:14                     (pos 1)
14:20:14         Expected: ??
14:20:14         Actual:   ??
14:20:14                     (pos 1)
14:20:14         Stack Trace:
14:20:14               at TextInfoTests.ToLower(String localeName)
14:20:14      TextInfoTests.ToLower(localeName: "en-US") [FAIL]
14:20:14         Assert.Equal() Failure
14:20:14                     (pos 1)
14:20:14         Expected: ??
14:20:14         Actual:   ??
14:20:14                     (pos 1)
14:20:14         Stack Trace:
14:20:14               at TextInfoTests.ToLower(String localeName)
14:20:14      TextInfoTests.ToLower(localeName: "fr") [FAIL]
14:20:14         Assert.Equal() Failure
14:20:14                     (pos 1)
14:20:14         Expected: ??
14:20:14         Actual:   ??
14:20:14                     (pos 1)
14:20:14         Stack Trace:
14:20:14               at TextInfoTests.ToLower(String localeName)
14:20:14      System.Globalization.Tests.NumberFormatInfoCurrencyGroupSizes.TestCurrencyGroupSizesLocale(locale: "ur-IN", primaryGroupSize: 3, secondaryGroupSize: 2) [FAIL]
14:20:14         System.Globalization.CultureNotFoundException : Culture is not supported.
14:20:14         Parameter name: name
14:20:14         ur-IN is an invalid culture identifier.
14:20:14         Stack Trace:
14:20:14               at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
14:20:14               at System.Globalization.Tests.NumberFormatInfoCurrencyGroupSizes.TestCurrencyGroupSizesLocale(String locale, Int32 primaryGroupSize, Int32 secondaryGroupSize)
14:20:14      System.Globalization.Tests.NumberFormatInfoNumberGroupSizes.TestNumberGroupSizesLocale(locale: "ur-IN") [FAIL]
14:20:14         System.Globalization.CultureNotFoundException : Culture is not supported.
14:20:14         Parameter name: name
14:20:14         ur-IN is an invalid culture identifier.
14:20:14         Stack Trace:
14:20:14               at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
14:20:14               at System.Globalization.Tests.NumberFormatInfoNumberGroupSizes.TestNumberGroupSizesLocale(String locale)
14:20:14      System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.TestCurrencyNegativePatternLocale(locale: "fr-CD") [FAIL]
14:20:14         System.Globalization.CultureNotFoundException : Culture is not supported.
14:20:14         Parameter name: name
14:20:14         fr-CD is an invalid culture identifier.
14:20:14         Stack Trace:
14:20:14               at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
14:20:14               at System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.TestCurrencyNegativePatternLocale(String locale)
14:20:14      CompareInfoTests.Compare(localeName: "", left: "ABCDE", right: "aBCDE", expected: -1, options: None) [FAIL]
14:20:14         Assert.Equal() Failure
14:20:14         Expected: -1
14:20:14         Actual:   1
14:20:14         Stack Trace:
14:20:14               at CompareInfoTests.Compare(String localeName, String left, String right, Int32 expected, CompareOptions options)
14:20:14   Finished:    System.Globalization.Tests
14:20:14   
14:20:14   === TEST EXECUTION SUMMARY ===
14:20:14      System.Globalization.Tests  Total: 5520, Errors: 0, Failed: 11, Skipped: 0, Time: 2.953s
```

**Comment by tarekgh** [comment]
this is fixed by the change https://github.com/dotnet/corefx/pull/7139
