### ISSUE TITLE
Four System.Globalization.Extensions tests failing on Win 7

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7087]
```
14:20:15      System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Success [FAIL]
14:20:15         System.ArgumentException : Decoded string is not a valid IDN name.
14:20:15         Parameter name: unicode
14:20:15         Stack Trace:
14:20:15               at System.Globalization.IdnMapping.ThrowForZeroLength(String paramName, String invalidNameString, String otherString)
14:20:15               at System.Globalization.IdnMapping.GetAsciiCore(String unicode)
14:20:15               at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index, Int32 count)
14:20:15               at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index)
14:20:15               at System.Globalization.IdnMapping.GetAscii(String unicode)
14:20:15               at System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Success()
14:20:15      System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetUnicode_Succes [FAIL]
14:20:15         Assert.Equal() Failure
14:20:15         Expected: ….?"
14:20:15         Actual:   xn--0ca.xn--ssa73l
14:20:15         Stack Trace:
14:20:15               at System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetUnicode_Succes()
14:20:15      System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Invalid [FAIL]
14:20:15         Assert.Throws() Failure
14:20:15         Expected: typeof(System.ArgumentException)
14:20:15         Actual:   (No exception was thrown)
14:20:15         Stack Trace:
14:20:15               at System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Invalid()
14:20:18      System.Globalization.Tests.StringNormalizationAllTests.Normalize [FAIL]
14:20:18         '\x0068' is not matched with the normalized form '\x2095 with ? normalization
14:20:18         Expected: True
14:20:18         Actual:   False
14:20:18         Stack Trace:
14:20:18               at System.Globalization.Tests.StringNormalizationAllTests.AssertEqualsForm(String c, String cForm)
14:20:18               at System.Globalization.Tests.StringNormalizationAllTests.VerifyConformanceInvariant(NormalizationForm normForm, String c1, String c2, String c3, String c4, String c5)
14:20:18               at System.Globalization.Tests.StringNormalizationAllTests.Normalize()
```

**Comment by tarekgh** [comment]
fixed with the change https://github.com/dotnet/corefx/pull/7139
