### ISSUE TITLE
ProcessTests.TestExitTime failed on OSX

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7105]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/2237/console
```
11:35:29    System.Diagnostics.Tests.ProcessTests.TestExitTime [FAIL]
11:35:29       Assert+WrapperXunitException : File path: d:\j\workspace\osx_debug_bld---2f4069d6\src\System.Diagnostics.Process\tests\ProcessTests.cs. Line: 164
11:35:29       ---- Assert.True() Failure
11:35:29       Expected: True
11:35:29       Actual:   False
11:35:29       Stack Trace:
11:35:29             at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
11:35:29             at Assert.True(Boolean condition, String userMessage, String path, Int32 line)
11:35:29             at System.Diagnostics.Tests.ProcessTests.TestExitTime()
11:35:29          ----- Inner Stack Trace -----
11:35:29             at Assert.True(Boolean condition, String userMessage, String path, Int32 line)
```

**Comment by Priya91** [comment]
Not able to repro this. Closing, please reopen if seen again.
