### ISSUE TITLE
Several MetadataReaderTests failing with NullReferenceException on OSX

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7125]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_osx_debug/49/consoleFull
```
12:42:12      System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateMethodImplTable [FAIL]
12:42:12         System.TypeInitializationException : The type initializer for 'System.Reflection.Metadata.Tests.Interop' threw an exception.
12:42:12         ---- System.NullReferenceException : Object reference not set to an instance of an object.
12:42:12         Stack Trace:
12:42:12               at System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateMethodImplTable()
12:42:12            ----- Inner Stack Trace -----
12:42:12               at System.Reflection.Metadata.Tests.ResourceHelper.GetResource(String name)
12:42:12               at System.Reflection.Metadata.Tests.Interop..cctor()
12:42:12      System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateSignature [FAIL]
12:42:12         System.TypeInitializationException : The type initializer for 'System.Reflection.Metadata.Tests.Interop' threw an exception.
12:42:12         ---- System.NullReferenceException : Object reference not set to an instance of an object.
12:42:12         Stack Trace:
12:42:12               at System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateSignature()
12:42:12            ----- Inner Stack Trace -----
12:42:12               at System.Reflection.Metadata.Tests.ResourceHelper.GetResource(String name)
12:42:12               at System.Reflection.Metadata.Tests.Interop..cctor()
12:42:12      System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateInterfaceImplTable [FAIL]
12:42:12         System.TypeInitializationException : The type initializer for 'System.Reflection.Metadata.Tests.Interop' threw an exception.
12:42:12         ---- System.NullReferenceException : Object reference not set to an instance of an object.
12:42:12         Stack Trace:
12:42:12               at System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateInterfaceImplTable()
12:42:12            ----- Inner Stack Trace -----
12:42:12               at System.Reflection.Metadata.Tests.ResourceHelper.GetResource(String name)
12:42:12               at System.Reflection.Metadata.Tests.Interop..cctor()
12:42:12      System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateFieldLayoutTable [FAIL]
12:42:12         System.TypeInitializationException : The type initializer for 'System.Reflection.Metadata.Tests.Interop' threw an exception.
12:42:12         ---- System.NullReferenceException : Object reference not set to an instance of an object.
12:42:12         Stack Trace:
12:42:12               at System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateFieldLayoutTable()
12:42:12            ----- Inner Stack Trace -----
12:42:12               at System.Reflection.Metadata.Tests.ResourceHelper.GetResource(String name)
12:42:12               at System.Reflection.Metadata.Tests.Interop..cctor()
12:42:12      System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateCustomAttribute [FAIL]
12:42:12         System.TypeInitializationException : The type initializer for 'System.Reflection.Metadata.Tests.Interop' threw an exception.
12:42:12         ---- System.NullReferenceException : Object reference not set to an instance of an object.
12:42:12         Stack Trace:
12:42:12               at System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateCustomAttribute()
12:42:12            ----- Inner Stack Trace -----
12:42:12               at System.Reflection.Metadata.Tests.ResourceHelper.GetResource(String name)
12:42:12               at System.Reflection.Metadata.Tests.Interop..cctor()
12:42:12      System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateFieldMarshal [FAIL]
12:42:12         System.TypeInitializationException : The type initializer for 'System.Reflection.Metadata.Tests.Interop' threw an exception.
12:42:12         ---- System.NullReferenceException : Object reference not set to an instance of an object.
12:42:12         Stack Trace:
12:42:12               at System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateFieldMarshal()
12:42:12            ----- Inner Stack Trace -----
12:42:12               at System.Reflection.Metadata.Tests.ResourceHelper.GetResource(String name)
12:42:12               at System.Reflection.Metadata.Tests.Interop..cctor()
12:42:12      System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateClassLayoutTable [FAIL]
12:42:12         System.TypeInitializationException : The type initializer for 'System.Reflection.Metadata.Tests.Interop' threw an exception.
12:42:12         ---- System.NullReferenceException : Object reference not set to an instance of an object.
12:42:12         Stack Trace:
12:42:12               at System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateClassLayoutTable()
12:42:12            ----- Inner Stack Trace -----
12:42:12               at System.Reflection.Metadata.Tests.ResourceHelper.GetResource(String name)
12:42:12               at System.Reflection.Metadata.Tests.Interop..cctor()
12:42:12   Finished:    System.Reflection.Metadata.Tests
12:42:12   
12:42:12   === TEST EXECUTION SUMMARY ===
12:42:12      System.Reflection.Metadata.Tests  Total: 153, Errors: 0, Failed: 7, Skipped: 0, Time: 0.512s
```

**Comment by mellinoe** [comment]
This seems to be caused by two of the embedded resource assemblies, `Interop.Mock01.dll` and `Interop.Mock01.Impl.dll` not being passed to csc.exe as resources. The resulting assembly does not have those dll's embedded, and the tests eventually try to load them by name, which fails with a null reference exception. It has something to do with the fact that they have periods in their names. If the files are renamed without periods (and the tests updated to match), then the tests succeed.

I'm not familiar with how the EmbeddedResource ItemGroup is passed around and through to csc.exe. Anyone have more expertise in the area to know why this would be going wrong if there is a period in the file name?

**Comment by stephentoub** [comment]
(In which case that's likely the same problem as with #7126, which is also experiencing NullReferenceExceptions related to a resource that contains periods in the name. cc: @KrzysztofCwalina )

**Comment by KrzysztofCwalina** [comment]
Yeah, I noticed yesterday that some packages work fine when loading resources. I looked at the difference and the only difference was dots in names. I am running a job now with dots removed.

**Comment by mellinoe** [comment]
I've looked through the Windows/OSX MSBuild logs to try to find any differences. One that jumped out at me was that, on OSX, the `AssignCulture` task finds that these resources with periods in their file names have some culture associated with them:

OSX:
````
Task "AssignCulture" (TaskId:77)
...
  Culture of "Mock01" was assigned to file "Resources/Interop/Interop.Mock01.dll". (TaskId:77)
  Culture of "Impl" was assigned to file "Resources/Interop/Interop.Mock01.Impl.dll". (TaskId:77)
````

Windows:
````
Task "AssignCulture" (TaskId:109)
...
  Culture of "" was assigned to file "Resources\Interop\Interop.Mock01.dll". (TaskId:109)
  Culture of "" was assigned to file "Resources\Interop\Interop.Mock01.Impl.dll". (TaskId:109)

````
I still don't fully understand how these items are actually passed around, but perhaps this difference results in them being omitted from the csc args. @tarekgh Are you familiar with this at all?

The .NET Core and .NET Framework versions of this method (`AssignCulture`) seem to be the same to me, so there may be some difference in the methods it calls.

**Comment by KrzysztofCwalina** [comment]
@tarekgh, would you know anything about it?

**Comment by mellinoe** [comment]
Line 245 of Microsoft.CSharp.CurrentVersion.Targets:

````
<!-- Condition is to filter out the _CoreCompileResourceInputs so that it doesn't pass in culture resources to the compiler -->
<Csc  Condition=" '%(_CoreCompileResourceInputs.WithCulture)' != 'true' "
              AdditionalLibPaths="$(AdditionalLibPaths)"
...
````

So the real key is figuring out why the `AssignCulture` method is assigning cultures to these assemblies on .NET Core, but not on .NET Framework. Or rather, only on OSX (?)

https://github.com/Microsoft/msbuild/blob/a4e0dd5f4b31a6c9acb1bab25ac401c438c3dfac/src/XMakeTasks/AssignCulture.cs

**Comment by stephentoub** [comment]
> Or rather, only on OSX

It's not just OSX, e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_ubuntu14.04_debug/45/#showFailuresLink
I saw it initially on OSX, but after we fixed some other issues, it became apparent it was also happening on Ubuntu.  And I believe OSX and Ubuntu outerloop are the only two runs currently using msbuild on Unix to do the build, rather than building on Windows and copying over.

**Comment by mellinoe** [comment]
> It's not just OSX

Thanks, I had a suspicion this was true.

I'm pretty sure the issue is due do differences in code in [Culture.cs, line 74](https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeTasks/Culture.cs#L74).

````CSharp
if ((cultureName != null) && (cultureName.Length > 1))
                {
                    // ... strip the "." to make "en-US"
                    cultureName = cultureName.Substring(1);
                    validCulture = CultureInfoCache.IsValidCultureString(cultureName);
                }
````

This is different from the [desktop code](https://github.com/Microsoft/msbuild/blob/master/src/XMakeTasks/Culture.cs#L74):

````CSharp
		if (text != null && text.Length > 1)
		{
		    // ... strip the "." to make "en-US"
                    cultureName = cultureName.Substring(1);
                    validCulture = CultureStringUtilities.IsValidCultureString(cultureName);
		}
````

I'm pretty sure this is causing us to consider culture strings that are actually invalid (i.e. "Mock01" and "Impl") as valid.

I'm going to file an issue on the MSBuild repo and, in the meantime, we should just work around this by removing the periods from the embedded resource filenames.

**Comment by mellinoe** [comment]
https://github.com/Microsoft/msbuild/issues/541
