### ISSUE TITLE
New BufferBlock negative test case failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#717]
This is one of the new negative test cases recently added.  Will fix.

Discovering: System.Threading.Tasks.Dataflow.Tests
  Discovered:  System.Threading.Tasks.Dataflow.Tests
  Starting:    System.Threading.Tasks.Dataflow.Tests
     System.Threading.Tasks.Dataflow.Tests.BufferBlockTests.TestReleasingFailsAtCompletion [FAIL]
        System.InvalidOperationException : The source completed without providing data to receive.
        Stack Trace:
           d:\j\workspace\dotnet_corefx\Configuration\Debug\OS\Windows_NT\SkipTests\false\label\windows\src\System.Threading.Tasks.Dataflow\src\Internal\Common.cs(212,0): at System.Threading.Tasks.Dataflow.Internal.Common.InitializeStackTrace(Exception exception)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           d:\j\workspace\dotnet_corefx\Configuration\Debug\OS\Windows_NT\SkipTests\false\label\windows\src\System.Threading.Tasks.Dataflow\src\Base\DataflowBlock.cs(1007,0): at System.Threading.Tasks.Dataflow.DataflowBlock.Receive[TOutput](ISourceBlock`1 source, TimeSpan timeout, CancellationToken cancellationToken)
           d:\j\workspace\dotnet_corefx\Configuration\Debug\OS\Windows_NT\SkipTests\false\label\windows\src\System.Threading.Tasks.Dataflow\src\Base\DataflowBlock.cs(915,0): at System.Threading.Tasks.Dataflow.DataflowBlock.Receive[TOutput](ISourceBlock`1 source)
           d:\j\workspace\dotnet_corefx\Configuration\Debug\OS\Windows_NT\SkipTests\false\label\windows\src\System.Threading.Tasks.Dataflow\tests\Dataflow\BufferBlockTests.cs(565,0): at System.Threading.Tasks.Dataflow.Tests.BufferBlockTests.<TestReleasingFailsAtCompletion>d__100.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Finished:    System.Threading.Tasks.Dataflow.Tests

**Comment by stephentoub** [comment]
Fixed with #719
