### ISSUE TITLE
GetAsync_ResponseWithSetCookieHeaders_AllCookiesRead failed in CI

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#7234]
See http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_release_tst_prtest/3294/consoleFull

```
14:06:32    System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_ResponseWithSetCookieHeaders_AllCookiesRead(cookie1: [foo, aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa]) [FAIL]
14:06:32       Assert.Equal() Failure
14:06:32       Expected: 3
14:06:32       Actual:   0
14:06:32       Stack Trace:
14:06:33             at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<GetAsync_ResponseWithSetCookieHeaders_AllCookiesRead>d__40.MoveNext()
14:06:33          --- End of stack trace from previous location where exception was thrown ---
14:06:33             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:06:33             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:06:33          --- End of stack trace from previous location where exception was thrown ---
14:06:33             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:06:33             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:06:33          --- End of stack trace from previous location where exception was thrown ---
14:06:33             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:06:33             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:06:43    System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_ResponseWithSetCookieHeaders_AllCookiesRead(cookie1: [foo, aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa]) [FAIL]
14:06:43       Assert.Equal() Failure
14:06:43       Expected: 3
14:06:43       Actual:   0
14:06:43       Stack Trace:
14:06:43             at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<GetAsync_ResponseWithSetCookieHeaders_AllCookiesRead>d__40.MoveNext()
14:06:43          --- End of stack trace from previous location where exception was thrown ---
14:06:43             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:06:43             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:06:43          --- End of stack trace from previous location where exception was thrown ---
14:06:43             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:06:43             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:06:43          --- End of stack trace from previous location where exception was thrown ---
14:06:43             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:06:43             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:06:51    System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_ResponseWithSetCookieHeaders_AllCookiesRead(cookie1: [foo, aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa]) [FAIL]
14:06:51       Assert.Equal() Failure
14:06:51       Expected: 3
14:06:51       Actual:   0
14:06:51       Stack Trace:
14:06:51             at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<GetAsync_ResponseWithSetCookieHeaders_AllCookiesRead>d__40.MoveNext()
14:06:51          --- End of stack trace from previous location where exception was thrown ---
14:06:51             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:06:51             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:06:51          --- End of stack trace from previous location where exception was thrown ---
14:06:51             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:06:51             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:06:51          --- End of stack trace from previous location where exception was thrown ---
14:06:51             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:06:51             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by ericstj** [comment]
Just hit this issue
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/118/consoleFull

```
System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_ResponseWithSetCookieHeaders_AllCookiesRead(cookie1: [foo, aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa]) [FAIL]
        Assert.Equal() Failure
        Expected: Redirect
        Actual:   GatewayTimeout
        Stack Trace:
              at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<GetAsync_ResponseWithSetCookieHeaders_AllCookiesRead>d__41.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by stephentoub** [comment]
Are we having networking problems in the lab?  That's what GatewayTimeout implies.  I closed this previously to add an assert on the status, which is what fired this time and which I believe confirms this is a lab infrastructure issue rather than anything in the product or test itself.

**Comment by ericstj** [comment]
Maybe we shouldn't have tests in the innerloop CI which depend on lab infrastructure?

**Comment by stephentoub** [comment]
> Maybe we shouldn't have tests in the innerloop CI which depend on lab infrastructure?

Don't we download NuGet packages as part of innerloop? ;)

**Comment by ericstj** [comment]
Yeah, nuget and myget have higher-9's than our lab infrastructure.  If we started hitting more restore failures then we'd file issues on getting off of NuGet in the CI as well.  Just this week I feel like half of my PRs have failed at least one leg due to network tests failing.

**Comment by stephentoub** [comment]
So what are you recommending be done here?  How do you propose this be addressed?  FWIW, I have more legs fail in general due to disk errors, Jenkins errors, package restore failures, and other such things than I do networking test failures, though I do of course hit those here and there.  I actually don't think all of the failures you hit are infrastructure, though; I expect there's at least a product or test bug or two in there. I believe this one specifically is a networking hiccup.

**Comment by ericstj** [comment]
Can this same thing be tested without an external network call?  Could it retry if it encounters a hiccup if a hiccup is recognizable as such?

**Comment by stephentoub** [comment]
> Can this same thing be tested without an external network call?

There are two projects in System.Net.Http's tests: unit tests and functional tests.  The unit tests project is all stuff that doesn't actually hit the network.  The functional tests project are ones that mostly do need to hit the network.  This particular one is in the latter category.

> Could it retry if it encounters a hiccup if a hiccup is recognizable as such?

Yes, we've talked in the past about adding a retry capability to xunit, e.g. a [RetryableFact] that would let you configure number of retries, delays between retries, etc., and then using it on such tests.  We've not done that yet.

**Comment by stephentoub** [comment]
Retry support in tests is tracked by https://github.com/dotnet/buildtools/issues/654

**Comment by ericstj** [comment]
Failed again with GatewayTimeout: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/523/testReport/junit/System.Net.Http.Functional.Tests/HttpClientHandlerTest/GetAsync_ResponseWithSetCookieHeaders_AllCookiesRead_cookie1___foo__aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa__/
