### ISSUE TITLE
Inconsistent bounds checking for CopyTo operations (Standard collections, Generics and Specialized)

### ISSUE THREAD

**Issue by nettsundere** [dotnet/corefx#7280]
Consider the following example (trying to copy an empty dictionary to 1-sized buffer starting from index 1, 1 is out of bounds, no exceptions been thrown)

```C#
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace TestX
{
    class Program
    {
        static void Main(string[] args)
        {
            var dictionary = new Dictionary<string, string>();
            var dictionaryAsCollection = dictionary as ICollection;
            var buffer = new KeyValuePair<string, string>[1];
            dictionaryAsCollection.CopyTo(buffer, 1); // 1 is out of bounds for buffer
            Console.WriteLine(buffer.First());
        }
    }
}
```

Now we change CopyTo arguments (1 -> 2), this code will throw an exception (ArgumentOutOfRangeException)

```C#
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace TestX
{
    class Program
    {
        static void Main(string[] args)
        {
            var dictionary = new Dictionary<string, string>();
            var dictionaryAsCollection = dictionary as ICollection;
            var buffer = new KeyValuePair<string, string>[1];
            dictionaryAsCollection.CopyTo(buffer, 2); // 2 is out of bounds for buffer
            Console.WriteLine(buffer.First());
        }
    }
}
```
Now, instead of changing CopyTo arguments, add an element to the dictionary. We will receive an exception of type ArgumentException
```C#
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace TestX
{
    class Program
    {
        static void Main(string[] args)
        {
            var dictionary = new Dictionary<string, string>();
            dictionary.Add("Test", "Ok"); // new dictionary element
            var dictionaryAsCollection = dictionary as ICollection;
            var buffer = new KeyValuePair<string, string>[1];
            dictionaryAsCollection.CopyTo(buffer, 1); // 1 is out of bounds for buffer
            Console.WriteLine(buffer.First());
        }
    }
}
```

For (almost) all the standard collections there are an issue: when CopyTo starting index is equal to destination buffer length, no ArgumentOutOfRangeException is thrown. For me it seems inconsistent: CopyTo(buffer, 1) should throw ArgumentOutOfRangeException in all cases except CopyTo(buffer, 0), because this time it is only valid argument value. 

I've created a small project in order to demonstrate this issue: https://github.com/nettsundere/CollectionsCopyTo

And the output is:
```
Trying to copy to buffer having size of 1 starting with index=1
--------------------------------------------------
Array
No exceptions
--------------------------------------------------
ArrayList
No exceptions
--------------------------------------------------
BitArray
No exceptions
--------------------------------------------------
ConcurrentBag
No exceptions
--------------------------------------------------
ConcurrentDictionary
No exceptions
--------------------------------------------------
ConcurrentQueue
No exceptions
--------------------------------------------------
ConcurrentStack
No exceptions
--------------------------------------------------
Dictionary
No exceptions
--------------------------------------------------
HashSet
No exceptions
--------------------------------------------------
Hashtable
No exceptions
--------------------------------------------------
HybridDictionary
No exceptions
--------------------------------------------------
List
No exceptions
--------------------------------------------------
LinkedList
No exceptions
--------------------------------------------------
ListDictionary
No exceptions
--------------------------------------------------
NameValueCollection
No exceptions
--------------------------------------------------
Queue
No exceptions
--------------------------------------------------
Queue (Generic)
No exceptions
--------------------------------------------------
Readonly collection
No exceptions
--------------------------------------------------
SortedDictionary
No exceptions
--------------------------------------------------
SortedList
No exceptions
--------------------------------------------------
SortedList (Generic)
No exceptions
--------------------------------------------------
Sorted set
No exceptions
--------------------------------------------------
Stack
No exceptions
--------------------------------------------------
Stack (Generic)
No exceptions
--------------------------------------------------
StringDictionary
No exceptions
-
-
-
Trying to copy to buffer having size of 1 starting with index=2
--------------------------------------------------
Array
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.CopyTo(Array array, Int32 index)
   at CollectionsCopyTo.CopyToExample.ArrayCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 16
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__0() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 22
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
ArrayList
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.ArrayList.CopyTo(Array array, Int32 arrayIndex)
   at CollectionsCopyTo.CopyToExample.ArrayListCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 28
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__1() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 23
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
BitArray
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Collections.BitArray.CopyTo(Array array, Int32 index)
   at CollectionsCopyTo.CopyToExample.BitArrayCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 42
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__2() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 24
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
ConcurrentBag
No exceptions
--------------------------------------------------
ConcurrentDictionary
System.ArgumentException: The index is equal to or greater than the length of the array, or the number of elements in the dictionary is greater than the available space from index to the end
ination array.
   at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.ICollection.CopyTo(Array array, Int32 index)
   at CollectionsCopyTo.CopyToExample.ConcurrentDictionaryCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 71
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__4() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 26
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
ConcurrentQueue
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Concurrent.ConcurrentQueue`1.CopyTo(T[] array, Int32 index)
   at CollectionsCopyTo.CopyToExample.ConcurrentQueueCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 99
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__5() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 27
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
ConcurrentStack
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Concurrent.ConcurrentStack`1.CopyTo(T[] array, Int32 index)
   at CollectionsCopyTo.CopyToExample.ConcurrentStackCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 85
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__6() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 28
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
Dictionary
System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.System.Collections.ICollection.CopyTo(Array array, Int32 index)
   at CollectionsCopyTo.CopyToExample.DictionaryCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 114
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__7() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 29
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
HashSet
System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length.
   at System.Collections.Generic.HashSet`1.CopyTo(T[] array, Int32 arrayIndex, Int32 count)
   at CollectionsCopyTo.CopyToExample.HashSetCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 128
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__8() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 30
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
Hashtable
System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length.
   at System.Collections.Hashtable.CopyTo(Array array, Int32 arrayIndex)
   at CollectionsCopyTo.CopyToExample.HashtableCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 143
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__9() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 31
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
HybridDictionary
System.ArgumentException: Insufficient space in the target location to copy the information.
   at System.Collections.Specialized.ListDictionary.CopyTo(Array array, Int32 index)
   at CollectionsCopyTo.CopyToExample.HybridDictionaryCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 158
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__10() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 32
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
List
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at CollectionsCopyTo.CopyToExample.ListCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 172
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__11() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 33
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
LinkedList
System.ArgumentOutOfRangeException: Must be less than or equal to the size of the collection.
Parameter name: index
Actual value was 2.
   at System.Collections.Generic.LinkedList`1.CopyTo(T[] array, Int32 index)
   at CollectionsCopyTo.CopyToExample.LinkedListCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 186
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__12() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 34
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
ListDictionary
System.ArgumentException: Insufficient space in the target location to copy the information.
   at System.Collections.Specialized.ListDictionary.CopyTo(Array array, Int32 index)
   at CollectionsCopyTo.CopyToExample.ListDictionaryCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 200
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__13() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 35
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
NameValueCollection
System.ArgumentException: Insufficient space in the target location to copy the information.
   at System.Collections.Specialized.NameValueCollection.CopyTo(Array dest, Int32 index)
   at CollectionsCopyTo.CopyToExample.NameValueCollectionCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 214
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__14() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 36
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
Queue
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Collections.Queue.CopyTo(Array array, Int32 index)
   at CollectionsCopyTo.CopyToExample.QueueCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 242
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__15() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 37
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
Queue (Generic)
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: arrayIndex
Actual value was 2.
   at System.Collections.Generic.Queue`1.CopyTo(T[] array, Int32 arrayIndex)
   at CollectionsCopyTo.CopyToExample.QueueGenericCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 228
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__16() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 38
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
Readonly collection
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at CollectionsCopyTo.CopyToExample.ReadOnlyCollectionCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 256
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__17() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 39
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
SortedDictionary
System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length.
   at System.Collections.Generic.SortedSet`1.System.Collections.ICollection.CopyTo(Array array, Int32 index)
   at CollectionsCopyTo.CopyToExample.SortedDictionaryCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 271
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__18() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 40
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
SortedList
System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length.
   at System.Collections.SortedList.CopyTo(Array array, Int32 arrayIndex)
   at CollectionsCopyTo.CopyToExample.SortedListCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 301
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__19() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 41
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
SortedList (Generic)
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Actual value was 2.
   at System.Collections.Generic.SortedList`2.System.Collections.ICollection.CopyTo(Array array, Int32 index)
   at CollectionsCopyTo.CopyToExample.SortedListGenericCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 286
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__20() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 42
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
Sorted set
System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length.
   at System.Collections.Generic.SortedSet`1.CopyTo(T[] array, Int32 index, Int32 count)
   at CollectionsCopyTo.CopyToExample.SortedSetCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 315
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__21() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 43
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
Stack
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Collections.Stack.CopyTo(Array array, Int32 index)
   at CollectionsCopyTo.CopyToExample.StackCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 343
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__22() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 44
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
Stack (Generic)
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: arrayIndex
Actual value was 2.
   at System.Collections.Generic.Stack`1.CopyTo(T[] array, Int32 arrayIndex)
   at CollectionsCopyTo.CopyToExample.StackGenericCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 329
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__23() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 45
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
--------------------------------------------------
StringDictionary
System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length.
   at System.Collections.Hashtable.CopyTo(Array array, Int32 arrayIndex)
   at CollectionsCopyTo.CopyToExample.StringDictionaryCopyTo(Boolean greaterIndex) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\CopyToExample.cs:line 357
   at CollectionsCopyTo.Program.<>c__DisplayClass1_0.<TestCollections>b__24() in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 46
   at CollectionsCopyTo.Program.FormatExceptionDetails(String header, Action exampleAction) in C:\Users\nettsundere\Documents\Visual Studio 2015\Projects\collectionsCopyTo\Program.cs:line 55
```
upd: Fixed BitArray result
upd2: Updated dependencies, new output

This is obviously a breaking change, so I'm not changing anything, just trying to report / discuss an issue.

**Comment by JonHanna** [comment]
This is treating the array as a half-open range, in which case it's valid to refer to one more than the last index, as long as one doesn't read from or write to said index. As such copying zero elements to that index is correct.
This would be very common in C++, including with the STL, and C++ is one of the first languages to (through a variant) support creation of assemblies, so being consistent with that makes sense.

**Comment by GSPP** [comment]
`string` operations normally allow referring to one past the end of the string if the size is zero.

**Comment by JonHanna** [comment]
There are popular algorithms that would have to be rewritten if it didn't.

**Comment by nettsundere** [comment]
@JonHanna, do you mean this case in C++?
```C++
#include "stdafx.h"
#define _SCL_SECURE_NO_WARNINGS

#include <vector>

int main()
{
	std::vector<int> vector = { }; // Empty vector
	std::vector<int> buffer(1);
	std::copy(vector.begin(), vector.end(), buffer.begin() + 1);

	// Debug assertion on begin() + N, N > 1, fails
	// std::copy(vector.begin(), vector.end(), buffer.begin() + 3);

	int nonVectorBuffer[1];
	std::copy(vector.begin(), vector.end(), nonVectorBuffer + 2); // Doing nothing

	system("pause");

    return 0;
}
```
I think that is a complete different approach - using iterators, and iterator.begin() + 1 is equal to interator.end(), so it's a valid value for the iterator. If we try to add more than one element, this will result in an assertion violation inside iterator + method, not inside the copy function. In second example, using nonVectorBuffer, nothing happens because address is not being dereferenced. I can pass any pointer, first off bounds or any other pointer.
In C# we pass an index, and therefore that behavior seems little bit confusing. Its like, library allows me to implement a buggy algorithm, but that one will reveal itself later (when collection receives an item). Anyway, if it is a common idiom and cannot be changed... there are still two confusing points:
___
- Why do the ConcurrentBag never throws an exception for any index greater than the destination length? Is it possible for [ me | not me ] to change this?
```C#
            var concurrentBag = new ConcurrentBag<string>();
            var buffer = new string[1];
            concurrentBag.CopyTo(buffer, 3);
            concurrentBag.CopyTo(buffer, 2);
            concurrentBag.CopyTo(buffer, 1);
```
- Why the exception type can be different (ArgumentOutOfRangeException or ArgumentException)? Is it possible to change this? I think that should be an ArgumentOutOfRangeException all the time (in this corner case at least).

At this moment, writing custom ICollection implementation replacement is little bit harder than it can be (due to lack of some predictable public contract for CopyTo).

p.s. @GSPP, @JonHanna,  thanks for the replies

**Comment by JonHanna** [comment]
Yes, I mean cases like that, or the case it's a generalisation of, which is that one is allowed to have a pointer point to one pass the end of an array.

One example of using this behaviour is:

```C#
if (arr.length - index <= source.Count)
    source.CopyTo(arr, index);
else
    // some logic that moves around buffers or resizes, etc.
```

Which is cleaner than having to also special-case when `source.Count` is zero and `arr.length == index`.

The `ConcurrentBag` case looks like a short-circuiting applied too early. It's probably not worth the breaking change of fixing that.

There are several cases where `CopyTo` implementations throw `ArgumentException` when they could usefully throw `ArgumentOutOfRangeException`. Another example came up recently here when something couldn't just delegate fully to `List<T>`'s implementation because of this. I'd like to see that changed, though while it shouldn't break much (moving from a given exception to one derived from it) it would have an impact.

**Comment by ianhays** [comment]
Thanks @nettsundere, you're right that these are inconsistent.

We're in a somewhat unfortunate place that is the result of poor/inadequate testing of the full framework and since our current goal is compat with the full framework, these inconsistencies have to come along as well.  It's not ideal, but it's not a big enough issue to justify introducing the breaking change. I actually already fixed a few of these but ended up having to revert/undo the change to get back to desktop compat, so at least for now we'll have to live with the inconsistency.
