### ISSUE TITLE
System.Diagnostics.Tracing.Tests fails on outerloop Unix.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#7339]
```
02:01:36   Discovering: System.Diagnostics.Tracing.Tests
02:01:37   Discovered:  System.Diagnostics.Tracing.Tests
02:01:37   Starting:    System.Diagnostics.Tracing.Tests
02:01:37      BasicEventSourceTests.FuzzyTests.Test_Write_Fuzzy [FAIL]
02:01:37         System.Diagnostics.Tracing.EventSourceException : An error occurred when writing to a listener.
02:01:37         ---- Assert.Equal() Failure
02:01:37                   ↓ (pos 0)
02:01:37         Expected: WJUYBHDKQB
02:01:37         Actual:   EventSourceMessage
02:01:37                   ↑ (pos 0)
02:01:37         Stack Trace:
02:01:37               at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
02:01:37               at System.Diagnostics.Tracing.EventSource.WriteToAllListeners(Int32 eventId, Guid* childActivityID, Int32 eventDataCount, EventData* data)
02:01:37               at System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(Int32 eventId, Guid* relatedActivityId, Int32 eventDataCount, EventData* data)
02:01:37               at System.Diagnostics.Tracing.EventSource.WriteEvent(Int32 eventId, String arg1, Int32 arg2)
02:01:37               at BasicEventSourceTests.EventTestHarness.TestHarnessEventSource.StartTest(String name, Int32 testNumber)
02:01:37               at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options)
02:01:37               at BasicEventSourceTests.FuzzyTests.Test_Write_Fuzzy()
02:01:37            ----- Inner Stack Trace -----
02:01:37               at BasicEventSourceTests.FuzzyTests.<>c__DisplayClass0_0.<Test_Write_Fuzzy>b__1(Event evt)
02:01:37               at BasicEventSourceTests.EventTestHarness.<>c__DisplayClass0_0.<RunTests>b__0(Event data)
02:01:37               at BasicEventSourceTests.EventListenerListener.HelperEventListener.OnEventWritten(EventWrittenEventArgs eventData)
02:01:37               at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
02:01:37      BasicEventSourceTests.TestsEventSourceLifetime.Test_EventSource_Lifetime [FAIL]
02:01:37         System.NullReferenceException : Object reference not set to an instance of an object.
02:01:37         Stack Trace:
02:01:37               at BasicEventSourceTests.TestsEventSourceLifetime.ExerciseEventSource(WeakReference wrProvider, WeakReference wrEventSource)
02:01:37               at BasicEventSourceTests.TestsEventSourceLifetime.Test_EventSource_Lifetime()
02:01:37      BasicEventSourceTests.TestsWrite.Test_Write_T_EventListener [FAIL]
02:01:37         System.Diagnostics.Tracing.EventSourceException : An error occurred when writing to a listener.
02:01:37         ---- Assert.Equal() Failure
02:01:37                   ↓ (pos 0)
02:01:37         Expected: Greeting
02:01:37         Actual:   EventSourceMessage
02:01:37                   ↑ (pos 0)
02:01:37         Stack Trace:
02:01:37               at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
02:01:37               at System.Diagnostics.Tracing.EventSource.WriteToAllListeners(Int32 eventId, Guid* childActivityID, Int32 eventDataCount, EventData* data)
02:01:37               at System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(Int32 eventId, Guid* relatedActivityId, Int32 eventDataCount, EventData* data)
02:01:37               at System.Diagnostics.Tracing.EventSource.WriteEvent(Int32 eventId, String arg1, Int32 arg2)
02:01:37               at BasicEventSourceTests.EventTestHarness.TestHarnessEventSource.StartTest(String name, Int32 testNumber)
02:01:37               at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options)
02:01:37               at BasicEventSourceTests.TestsWrite.Test_Write_T(Listener listener)
02:01:37               at BasicEventSourceTests.TestsWrite.Test_Write_T_EventListener()
02:01:37            ----- Inner Stack Trace -----
02:01:37               at BasicEventSourceTests.TestsWrite.<>c__DisplayClass3_0.<Test_Write_T>b__1(Event evt)
02:01:37               at BasicEventSourceTests.EventTestHarness.<>c__DisplayClass0_0.<RunTests>b__0(Event data)
02:01:37               at BasicEventSourceTests.EventListenerListener.HelperEventListener.OnEventWritten(EventWrittenEventArgs eventData)
02:01:37               at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
02:01:37      BasicEventSourceTests.TestsWrite.Test_Write_T_In_Manifest_Serialization [FAIL]
02:01:37         System.Diagnostics.Tracing.EventSourceException : An error occurred when writing to a listener.
02:01:37         ---- System.NullReferenceException : Object reference not set to an instance of an object.
02:01:37         Stack Trace:
02:01:37               at System.Diagnostics.Tracing.EventSource.ThrowEventSourceException(String eventName, Exception innerEx)
02:01:37               at System.Diagnostics.Tracing.EventSource.WriteImpl(String eventName, EventSourceOptions& options, Object data, Guid* pActivityId, Guid* pRelatedActivityId, TraceLoggingEventTypes eventTypes)
02:01:37               at System.Diagnostics.Tracing.EventSource.Write[T](String eventName, T data)
02:01:37               at BasicEventSourceTests.TestsWrite.Test_Write_T_In_Manifest_Serialization()
02:01:37            ----- Inner Stack Trace -----
02:01:37               at System.Diagnostics.Tracing.EventSource.WriteImpl(String eventName, EventSourceOptions& options, Object data, Guid* pActivityId, Guid* pRelatedActivityId, TraceLoggingEventTypes eventTypes)
02:01:37      BasicEventSourceTests.TestsWrite.Test_Write_T_EventListener_UseEvents [FAIL]
02:01:37         System.Diagnostics.Tracing.EventSourceException : An error occurred when writing to a listener.
02:01:37         ---- Assert.Equal() Failure
02:01:37                   ↓ (pos 0)
02:01:37         Expected: Greeting
02:01:37         Actual:   EventSourceMessage
02:01:37                   ↑ (pos 0)
02:01:37         Stack Trace:
02:01:37               at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
02:01:37               at System.Diagnostics.Tracing.EventSource.WriteToAllListeners(Int32 eventId, Guid* childActivityID, Int32 eventDataCount, EventData* data)
02:01:37               at System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(Int32 eventId, Guid* relatedActivityId, Int32 eventDataCount, EventData* data)
02:01:37               at System.Diagnostics.Tracing.EventSource.WriteEvent(Int32 eventId, String arg1, Int32 arg2)
02:01:37               at BasicEventSourceTests.EventTestHarness.TestHarnessEventSource.StartTest(String name, Int32 testNumber)
02:01:37               at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options)
02:01:37               at BasicEventSourceTests.TestsWrite.Test_Write_T(Listener listener)
02:01:37               at BasicEventSourceTests.TestsWrite.Test_Write_T_EventListener_UseEvents()
02:01:37            ----- Inner Stack Trace -----
02:01:37               at BasicEventSourceTests.TestsWrite.<>c__DisplayClass3_0.<Test_Write_T>b__1(Event evt)
02:01:37               at BasicEventSourceTests.EventTestHarness.<>c__DisplayClass0_0.<RunTests>b__0(Event data)
02:01:37               at BasicEventSourceTests.EventListenerListener.HelperEventListener.OnEventWritten(EventWrittenEventArgs eventData)
02:01:37               at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
02:01:37   Finished:    System.Diagnostics.Tracing.Tests
02:01:37   
02:01:37   === TEST EXECUTION SUMMARY ===
02:01:37      System.Diagnostics.Tracing.Tests  Total: 26, Errors: 0, Failed: 5, Skipped: 0, Time: 0.564s
```
Test run log [here](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_ubuntu14.04_debug/lastCompletedBuild/consoleFull)

**Comment by stephentoub** [comment]
@Priya91, these tests are marked as ActiveIssue on Unix, e.g.
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Tracing/tests/BasicEventSourceTest/FuzzyTests.cs#L24
and there's already an issue open tracking getting them fixed:
https://github.com/dotnet/corefx/issues/4871
If they're running in the lab, the bug is that ActiveIssue is being ignored.

**Comment by Priya91** [comment]
This should be fixed with the extensions update.
