### ISSUE TITLE
DnsTests.GetHostEntryAsyncWithAddress failed on outerloop ubuntu14.04, ipaddress is null.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#7340]
```
Discovering: System.Net.NameResolution.Functional.Tests
02:06:51   Discovered:  System.Net.NameResolution.Functional.Tests
02:06:51   Starting:    System.Net.NameResolution.Functional.Tests
02:06:51      System.Net.NameResolution.Tests.DnsTests.GetHostEntryAsyncWithAddress [FAIL]
02:06:51         System.ArgumentNullException : Value cannot be null.
02:06:51         Parameter name: address
02:06:51         Stack Trace:
02:06:51               at System.Net.Dns.HostResolutionBeginHelper(IPAddress address, Boolean flowContext, Boolean includeIPv6, AsyncCallback requestCallback, Object state)
02:06:51               at System.Net.Dns.BeginGetHostEntry(IPAddress address, AsyncCallback requestCallback, Object stateObject)
02:06:51               at System.Net.Dns.<>c.<GetHostEntryAsync>b__15_0(IPAddress arg, AsyncCallback requestCallback, Object stateObject)
02:06:51               at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1](Func`4 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, Object state, TaskCreationOptions creationOptions)
02:06:51               at System.Threading.Tasks.TaskFactory`1.FromAsync[TArg1](Func`4 beginMethod, Func`2 endMethod, TArg1 arg1, Object state)
02:06:51               at System.Net.Dns.GetHostEntryAsync(IPAddress address)
02:06:51               at System.Net.NameResolution.Tests.DnsTests.<>c__DisplayClass1_0.<GetHostEntryAsyncWithAddress>b__0()
02:06:51               at System.Net.NameResolution.Tests.DnsTests.GetHostEntryAsync(Func`1 getHostEntryFunc)
02:06:51               at System.Net.NameResolution.Tests.DnsTests.<GetHostEntryAsyncWithAddress>d__1.MoveNext()
02:06:51            --- End of stack trace from previous location where exception was thrown ---
02:06:51               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
02:06:51               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
02:06:51            --- End of stack trace from previous location where exception was thrown ---
02:06:51               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
02:06:51               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
02:06:51            --- End of stack trace from previous location where exception was thrown ---
02:06:51               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
02:06:51               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
02:06:51   Finished:    System.Net.NameResolution.Functional.Tests
```

**Comment by stephentoub** [comment]
@Priya91, you marked this as blocking-clean-ci.  Did this just happen once, or are you seeing it on most runs?

**Comment by Priya91** [comment]
@stephentoub I saw this once

**Comment by shrutigarg** [comment]
is this recurring? DO we need to investigate?

**Comment by karelz** [comment]
We are tracking all Networking test failures in specific effort - cc @steveharter @Priya91 @ianhays - guys, can you please link the master issue?

**Comment by ianhays** [comment]
https://github.com/dotnet/corefx/issues/14519

**Comment by steveharter** [comment]
Note GetHostEntryAsyncWithAddress no longer exists
