### ISSUE TITLE
2 HttpClientHandler_ServerCertificates_Test failed in CI

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#7364]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/debian8.2_debug_tst/763/console

````
14:24:52    System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.NoCallback_RevokedCertificate_RevocationChecking_Fails [FAIL]
14:24:52       Assert.Throws() Failure
14:24:52       Expected: typeof(System.Net.Http.HttpRequestException)
14:24:52       Actual:   typeof(System.Threading.Tasks.TaskCanceledException): A task was canceled.
14:24:52       Stack Trace:
14:24:52             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:24:52             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:24:52             at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
14:24:52             at System.Net.Http.HttpClient.<FinishSendAsync>d__59.MoveNext()
14:24:52          --- End of stack trace from previous location where exception was thrown ---
14:24:52             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:24:52             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
````

````
14:26:32    System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds [FAIL]
14:26:32       System.Threading.Tasks.TaskCanceledException : A task was canceled.
14:26:32       Stack Trace:
14:26:32             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:26:32             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:26:32             at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
14:26:32             at System.Net.Http.HttpClient.<FinishSendAsync>d__59.MoveNext()
14:26:32          --- End of stack trace from previous location where exception was thrown ---
14:26:32             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:26:32             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:26:32             at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
14:26:32             at System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.<NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds>d__7.MoveNext()
14:26:32          --- End of stack trace from previous location where exception was thrown ---
14:26:32             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:26:32             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:26:32          --- End of stack trace from previous location where exception was thrown ---
14:26:32             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:26:32             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:26:32          --- End of stack trace from previous location where exception was thrown ---
14:26:32             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:26:32             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
````

Both tests failed because a TaskCanceledException was thrown. These do not seem to be recurring failures. @davidsh , @CIPop

**Comment by davidsh** [comment]
cc: @stephentoub for cross-plat issues.

**Comment by stephentoub** [comment]
Sounds like they timed out.

**Comment by stephentoub** [comment]
These occurred at the same time we were having massive networking issues in CI.  I'm going to close this for now.  If they happen again, we can take another look.
