### ISSUE TITLE
System.Net.Sockets.Socket.SetLingerOption() throws exception on OS X

### ISSUE THREAD

**Issue by roncain** [dotnet/corefx#7403]
16 WCF OuterLoop tests fail in nightly Helix runs on OS X, all with the same stack trace.  These tests pass on Ubuntu.  It looks like SetLingerOption() is not properly hooked up in OS X.

Here is the Helix log for one such test:
```
Path  FunctionalTest.Client.ClientBase.Tests#DuplexClientBaseTests.DuplexClientBaseOfT_OverNetTcp_Synchronous_Call  
Run On  Wednesday, March 30, 2016 12:57 PM  
Architecture  AnyCpu  
Configuration  CHK  
OperatingSystem  OSX.1011  

Test Output

Test Failed 
 Unhandled exception of type 'System.Net.Sockets.SocketException': System.Net.Sockets.SocketException : Invalid argument 
 at System.Net.Sockets.Socket.SetLingerOption(LingerOption lref) 
 at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Object optionValue) 
 at System.ServiceModel.Channels.CoreClrSocketConnection.Abort(Int32 traceEventType, String timeoutErrorString, TransferOperation transferOperation) 
 at System.ServiceModel.Channels.SocketConnection.Abort(String timeoutErrorString, TransferOperation transferOperation) 
 at System.ServiceModel.Channels.SocketConnection.Abort() 
 at System.ServiceModel.Channels.DelegatingConnection.Abort() 
 at System.ServiceModel.Channels.ConnectionPool.AbortItem(IConnection item) 
 at System.ServiceModel.Channels.CommunicationPool`2.EndpointConnectionPool.AbortItem(TItem item) 
 at System.ServiceModel.Channels.IdlingCommunicationPool`2.IdleTimeoutEndpointConnectionPool.AbortItem(TItem item) 
 at System.ServiceModel.Channels.CommunicationPool`2.EndpointConnectionPool.AbortConnections(List`1 idleItemsToClose) 
 at System.ServiceModel.Channels.CommunicationPool`2.EndpointConnectionPool.Close(TimeSpan timeout) 
 at System.ServiceModel.Channels.CommunicationPool`2.OnClose(TimeSpan timeout) 
 at System.ServiceModel.Channels.CommunicationPool`2.Close(TimeSpan timeout) 
 at System.ServiceModel.Channels.ConnectionPoolRegistry.Release(ConnectionPool pool, TimeSpan timeout) 
 at System.ServiceModel.Channels.TcpChannelFactory`1.ReleaseConnectionPool(ConnectionPool pool, TimeSpan timeout) 
 at System.ServiceModel.Channels.ConnectionOrientedTransportChannelFactory`1.<OnCloseAsync>d__52.MoveNext() 
. . .
at System.ServiceModel.Channels.CommunicationObject.Close(TimeSpan timeout) 
 at System.ServiceModel.ClientBase`1.System.ServiceModel.ICommunicationObject.Close(TimeSpan timeout) 
 at System.ServiceModel.ClientBase`1.Close() 
 at DuplexClientBaseTests.DuplexClientBaseOfT_OverNetTcp_Synchronous_Call() 

```

See WCF issue https://github.com/dotnet/wcf/issues/951

**Comment by joshfree** [comment]
@ericeil PTAL

**Comment by stephentoub** [comment]
@roncain, what value are you passing for the linger time?

**Comment by stephentoub** [comment]
To be more specific, IIRC the limit on OSX is something like 5.5 minutes.  If you go above that, the OS ends up wrapping/truncating the value, resulting in odd behaviors.  So we check if you're exceeding the max value for the platform and return EINVAL in that case.  The other option we considered was capping the value to the max, which would potentially cause you to get a lower linger time than you requested.

**Comment by ericeil** [comment]
Looks like this is the [relevant code](https://github.com/dotnet/wcf/blob/9d14d7d0d9fec62c3e7e1bfd320a360e9d38c9e0/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/CoreClrSocketConnection.cs#L191):

```csharp
_socket.LingerState = new LingerOption(true, 0);
```

**Comment by stephentoub** [comment]
Hmm, 0 should work fine... we even have a test for that:
https://github.com/dotnet/corefx/blob/898d0a21e149c6f9e271bae28d840b8f9659faee/src/System.Net.Sockets/tests/FunctionalTests/LingerStateTest.cs#L37

I'd have expected it to be this code:
https://github.com/dotnet/wcf/blob/9d14d7d0d9fec62c3e7e1bfd320a360e9d38c9e0/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/CoreClrSocketConnection.cs#L312
which is passing in an arbitrary value.  Which I expect could easily exceed the 327 second max for OS X.

Assuming that is the problem, I think our three options stand:
1. No checking in the implementation, and allow the OS to wrap, leading to strange behaviors.
2. Checking in the implementation, and throwing if it exceeds the max and would wrap.  This is what we do today.
3. Checking in the implementation, and capping to the max if it's exceeded.

Maybe we should consider switching to (3) instead of (2)?

Or maybe I'm completely off-base as to the issue :)

**Comment by ericeil** [comment]
Looks like this can fail if the other end of the socket is closed.  All three of the cases in the following test fail consistently for me, with an "Invalid argument" `SocketException`:

```csharp
        [Theory]
        [InlineData(false, 0)]
        [InlineData(true, 0)]
        [InlineData(true, 1)]
        public void SetLingerAfterServerClosed(bool linger, int timeout)
        {
            using (var server = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
            {
                int port = server.BindToAnonymousPort(IPAddress.Loopback);
                server.Listen(1);

                var client = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
                {
                    client.Connect(IPAddress.Loopback, port);

                    server.Dispose();
                    Thread.Sleep(100);

                    client.LingerState = new LingerOption(linger, timeout);
                }
            }
        }
```

(This passes consistently on Windows)

**Comment by joshfree** [comment]
@ericeil can you please get a blurb on this added to the rc2 known issues (for the release notes)?  email @leecow offline

**Comment by jchannon** [comment]
I get this exception on OSX.

SDK : 2.1.3

Code:

```
            this.client = new TcpClient
            {
                SendTimeout = this.settings.TCPSendTimeout,
                LingerState = new LingerOption(true, this.settings.LingerTime)
            };
            await this.client.ConnectAsync(this.settings.Host, this.settings.Port);
```

Exception:
```
   at System.Net.Sockets.Socket.SetLingerOption(LingerOption lref)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Object optionValue)
   at System.Net.Sockets.TcpClient.SetOption[T](T& location, Boolean& initialized, SocketOptionLevel level, SocketOptionName name, T value)
   at System.Net.Sockets.TcpClient.set_LingerState(LingerOption value)
   at Serilog.Sinks.Fluentd.Core.Sinks.FluentdSink.<Connect>d__5.MoveNext() in /Users/jonathan/Projects/Serilog.Sinks.Fluentd.Core/src/Sinks/FluentdSink.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Serilog.Sinks.Fluentd.Core.Sinks.FluentdSink.<Send>d__6.MoveNext() in /Users/jonathan/Projects/Serilog.Sinks.Fluentd.Core/src/Sinks/FluentdSink.cs:line 82
```
