### ISSUE TITLE
Filestream with  FileOptions.Encrypted | FileOptions.WriteThrough fails to write on Nano

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#7434]
```
19:39:16    System.IO.Tests.FileStream_ctor_str_fm_fa_fs_buffer_fo.ValidFileOptions(option: Encrypted) [FAIL]
19:39:16       System.UnauthorizedAccessException : Access to the path 'C:\Windows\TEMP\FileStream_ctor_str_fm_fa_fs_buffer_fo_3qffgkdi.mfj\ValidFileOptions_50' is denied.
19:39:16       Stack Trace:
19:39:17             at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
19:39:17             at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
19:39:17             at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
19:39:17             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
19:39:17             at System.IO.Tests.FileStream_ctor_str_fm_fa_fs_buffer_fo.CreateFileStream(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
19:39:17             at System.IO.Tests.FileStream_ctor_str_fm_fa_fs_buffer_fo.ValidFileOptions(FileOptions option)
19:39:37    System.IO.Tests.FileStream_ctor_str_fm_fa_fs_buffer_fo.ValidFileOptions(option: Encrypted, Asynchronous) [FAIL]
19:39:37       System.UnauthorizedAccessException : Access to the path 'C:\Windows\TEMP\FileStream_ctor_str_fm_fa_fs_buffer_fo_ts5rrahw.xkr\ValidFileOptions_50' is denied.
19:39:37       Stack Trace:
19:39:37             at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
19:39:37             at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
19:39:37             at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
19:39:37             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
19:39:37             at System.IO.Tests.FileStream_ctor_str_fm_fa_fs_buffer_fo.CreateFileStream(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
19:39:37             at System.IO.Tests.FileStream_ctor_str_fm_fa_fs_buffer_fo.ValidFileOptions(FileOptions option)
19:39:57    System.IO.Tests.FileStream_ctor_str_fm_fa_fs_buffer_fo.ValidFileOptions(option: Encrypted, DeleteOnClose, SequentialScan, RandomAccess, Asynchronous, WriteThrough) [FAIL]
19:39:57       System.UnauthorizedAccessException : Access to the path 'C:\Windows\TEMP\FileStream_ctor_str_fm_fa_fs_buffer_fo_1doetiwe.nbk\ValidFileOptions_50' is denied.
19:39:57       Stack Trace:
19:39:57             at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
19:39:57             at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
19:39:57             at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
19:39:57             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
19:39:57             at System.IO.Tests.FileStream_ctor_str_fm_fa_fs_buffer_fo.CreateFileStream(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
19:39:57             at System.IO.Tests.FileStream_ctor_str_fm_fa_fs_buffer_fo.ValidFileOptions(FileOptions option)
19:39:57 Finished:    System.IO.FileSystem.Tests
```

**Comment by Priya91** [comment]
@ianhays Can you take a look ?

**Comment by ianhays** [comment]
Sure. Was this a recurring issue or an intermittent one?

Do you have a spare winnano machine I can use to test this and https://github.com/dotnet/corefx/issues/7433?

**Comment by Priya91** [comment]
> Do you have a spare winnano machine I can use to test this and #7433?

Yes, refer to the dotnet-ci repo scripts..

**Comment by danmosemsft** [comment]
This code works on regular Windows, fails on Nano:

```C#
    class Program
    {
        static void Main(string[] args)
        {
            FileOptions option = FileOptions.Encrypted | FileOptions.WriteThrough;
            byte[] data = new byte[4096];
            new Random(1).NextBytes(data);

            string path = Path.Combine(Path.GetTempPath(), DateTime.Now.Ticks.ToString());
            Console.WriteLine(option.ToString());
            Console.WriteLine(path);

            using (FileStream fs = new FileStream(path, FileMode.Create, FileAccess.ReadWrite, FileShare.Read, 4096, option))
            {
                Console.WriteLine("opened");
                fs.Write(data, 0, data.Length);
            }
        }
```

with

```
System.IO.IOException: The read or write operation to an encrypted file could not be completed because the file has not been opened for data access
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at _1.Program.Main(String[] args)
```

With just `FileOptions.Encrypted` it does not seem to fail - only with ` FileOptions.Encrypted | FileOptions.WriteThrough`. In the test case above, it's failing even with just ` FileOptions.Encrypted` though.

Some OS difference relating to encrypted files.

@ianhays fyi.

**Comment by stephentoub** [comment]
> in case the reason is obvious to you

It's not.  In your example, Encrypted works, WriteThrough works, but Encrypted | WriteThrough fails on Nano; not sure why.  Probably worth asking someone more familiar with Nano Server.  I suggest verifying similar code written in C against CreateFile fails, and then disable the tests / punt for now as at that point it's not a .NET product source issue.

**Comment by JeremyKuhne** [comment]
Triage: closing as this is external.
