### ISSUE TITLE
EventListener.DisposeOnShutdown crash due to collection modified during enumeration

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7630]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug/1206/consoleFull
```
10:51:06   System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
10:51:06      at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
10:51:06      at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
10:51:06      at System.Diagnostics.Tracing.EventListener.DisposeOnShutdown(Object sender, EventArgs e)
10:51:06 d:\j\workspace\windows_nt_debuge57bf35e\Tools\tests.targets(147,5): warning MSB3073: The command "xunit.console.exe System.Globalization.Calendars.Tests.dll  -xml testResults.xml -notrait Benchmark=true  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests " exited with code 1. 
```

**Comment by davmason** [comment]
This seems like a dupe of #3793, I believe the issue here is that xunit is running on desktop and although I have fixed it in the next release of desktop it takes a while for it to ship.

If you're seeing this with xunit running on the latest coreclr, then I do not expect that and it is a different issue.

**Comment by stephentoub** [comment]
It looks like this occurrence was when running on desktop.  Thanks.
