### ISSUE TITLE
NegotiateStream_StreamToStream_AuthToHttpTarget_Success test failing on RHEL

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7707]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_rhel7.2_release_tst/47/consoleFull

```
08:18:40    System.Net.Security.Tests.KerberosTest.NegotiateStream_StreamToStream_AuthToHttpTarget_Success [FAIL]
08:18:40       System.AggregateException : One or more errors occurred. (A call to SSPI failed, see inner exception.)
08:18:40       ---- System.Security.Authentication.AuthenticationException : A call to SSPI failed, see inner exception.
08:18:40       -------- System.ComponentModel.Win32Exception : ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (Server not found in Kerberos database).
08:18:40          at Interop.GssApi.EstablishSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags)
08:18:40          at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, Boolean isNtlm, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)
08:18:40       Stack Trace:
08:18:40             at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
08:18:40             at System.Net.Security.Tests.KerberosTest.NegotiateStream_StreamToStream_AuthToHttpTarget_Success()
08:18:40          ----- Inner Stack Trace -----
08:18:40             at System.Net.Security.NegoState.EndProcessAuthentication(IAsyncResult result)
08:18:40             at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
08:18:40          ----- Inner Stack Trace -----
```

**Comment by joshfree** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_rhel7.2_debug_tst/52/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8
```
20:32:23 === TEST EXECUTION SUMMARY ===
20:32:23    System.Net.Primitives.Functional.Tests  Total: 260, Errors: 0, Failed: 0, Skipped: 0, Time: 4.985s
20:32:34    System.Net.Security.Tests.KerberosTest.NegotiateStream_StreamToStream_AuthToHttpTarget_Success [FAIL]
20:32:34       System.AggregateException : One or more errors occurred. (A call to SSPI failed, see inner exception.)
20:32:34       ---- System.Security.Authentication.AuthenticationException : A call to SSPI failed, see inner exception.
20:32:34       -------- System.ComponentModel.Win32Exception : ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (Server not found in Kerberos database).
20:32:34          at Interop.GssApi.EstablishSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags)
20:32:34          at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, Boolean isNtlm, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)
20:32:34       Stack Trace:
20:32:34             at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
20:32:34             at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
20:32:34             at System.Net.Security.Tests.KerberosTest.NegotiateStream_StreamToStream_AuthToHttpTarget_Success()
20:32:34          ----- Inner Stack Trace -----
20:32:34             at System.Net.Security.NegoState.EndProcessAuthentication(IAsyncResult result)
20:32:34             at System.Net.Security.NegotiateStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
20:32:34             at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
20:32:34          ----- Inner Stack Trace -----
20:32:34          
20:32:34 Finished:    System.Net.Security.Tests
20:32:34 
20:32:34 === TEST EXECUTION SUMMARY ===
20:32:34    System.Net.Security.Tests  Total: 106, Errors: 0, Failed: 1, Skipped: 0, Time: 15.171s
20:32:34 error: One or more tests failed while running tests from ''.  Exit code 1.
```

**Comment by shrutigarg** [comment]
#7739 merged. Closing this issue now.

**Comment by shrutigarg** [comment]
fixed and merged

**Comment by ianhays** [comment]
I'm re-opening this issue. We've been seeing several failures of this test in the past month in the Rhel7.2 Outerloop runs for both Debug and Release.

It fails in one of two ways:

```
System.Net.Security.Tests.NegotiateStreamTest.NegotiateStream_StreamToStream_AuthToHttpTarget_Success
11:41:55         client.IsMutuallyAuthenticated
11:41:55         Expected: True
11:41:55         Actual:   False
11:41:55         Stack Trace:
11:41:55            /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_rhel7.2_debug/src/System.Net.Security/tests/FunctionalTests/NegotiateStreamTestForUnix.cs(139,0): at System.Net.Security.Tests.NegotiateStreamTest.AssertClientPropertiesForTarget(NegotiateStream client, String target)
11:41:55            /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_rhel7.2_debug/src/System.Net.Security/tests/FunctionalTests/NegotiateStreamTestForUnix.cs(220,0): at System.Net.Security.Tests.NegotiateStreamTest.NegotiateStream_StreamToStream_AuthToHttpTarget_Success()
```

or

```
System.AggregateException : One or more errors occurred. (A call to SSPI failed, see inner exception.)
---- System.Security.Authentication.AuthenticationException : A call to SSPI failed, see inner exception.
-------- System.ComponentModel.Win32Exception : GSSAPI operation failed with error - An invalid status code was supplied (Invalid value in argument).
+++++++++++++++++++
STACK TRACE:
at System.ThrowHelper.ThrowAggregateException(List`1 exceptions) 
at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken) 
at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout) at System.Net.Security.Tests.NegotiateStreamTest.NegotiateStream_StreamToStream_KerberosAuthDefaultCredentials_Success() 
in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_rhel7.2_debug/src/System.Net.Security/tests/FunctionalTests/NegotiateStreamTestForUnix.cs:line 284
----- Inner Stack Trace ----- 
at System.Net.Security.NegoState.EndProcessAuthentication(IAsyncResult result) 
at System.Net.Security.NegotiateStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
----- Inner Stack Trace -----endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
----- Inner Stack Trace -----
```

When it fails in the first manner, it is the only test in the run to fail that way. When it fails in the second manner, these tests all fail the same way:
```
System.Net.Security.Tests.NegotiateStreamTest.NegotiateStream_StreamToStream_KerberosAuthDefaultCredentials_Success
System.Net.Security.Tests.NegotiateStreamTest.NegotiateStream_StreamToStream_AuthToHttpTarget_Success
System.Net.Security.Tests.NegotiateStreamTest.NegotiateStream_EchoServer_ClientWriteRead_Successive_Async_Success
System.Net.Security.Tests.NegotiateStreamTest.NegotiateStream_EchoServer_ClientWriteRead_Successive_Sync_Success
```

**Comment by ianhays** [comment]
These tests are no longer failing. The recent failures were caused by us running the test library multiple times concurrently which has been fixed with the recent engineering changes.
