### ISSUE TITLE
ARM64: System.Net.WebSockets.Client.Tests failing 

### ISSUE THREAD

**Issue by ramarag** [dotnet/corefx#7735]
```
<test name="System.Net.WebSockets.Client.Tests.ClientWebSocketTest.Abort_CloseAndAbort_Success(server: ws://corefx-net.cloudapp.net/WebSocket/EchoWebSocket.ashx)" type="System.Net.WebSockets.Client.Tests.ClientWebSocketTest" method="Abort_CloseAndAbort_Success" time="10.0437332" result="Fail">
        <output><![CDATA[GetConnectedWebSocket: ConnectAsync starting.
]]></output>
        <failure exception-type="System.Net.WebSockets.WebSocketException">
          <message><![CDATA[System.Net.WebSockets.WebSocketException : Unable to connect to the remote server\r\n---- System.Net.WebSockets.WebSocketException : Unable to connect to the remote server\r\n-------- System.Net.Http.WinHttpException : The operation has been canceled]]></message>
          <stack-trace><![CDATA[   at System.Net.WebSockets.WebSocketHandle.<ConnectAsyncCore>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at System.Net.WebSockets.Client.Tests.WebSocketHelper.<GetConnectedWebSocket>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Net.WebSockets.Client.Tests.ClientWebSocketTest.<TestCancellation>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at System.Net.WebSockets.Client.Tests.ClientWebSocketTest.<Abort_CloseAndAbort_Success>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WinHttpWebSocket.<ConnectAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WebSocketHandle.<ConnectAsyncCore>d__21.MoveNext()
----- Inner Stack Trace -----
]]></stack-trace>
        </failure>
      </test>
```

**Comment by CIPop** [comment]
@ramarag This looks like an environment issue. Please ensure that the test machine has Internet access. 
From that machine, can you navigate to http://corefx-net.cloudapp.net ?

**Comment by ramarag** [comment]
the message i see is, so i assuming there is access

NetworkingTestServer

Networking test server in Azure. Used by dotnet/corefx repo.

**Comment by CIPop** [comment]
@ramarag Is there any way I can get access to the machine to investigate this issue?

**Comment by CIPop** [comment]
@ramarag Assigning this to you based on our offline conversation.

Please assign back if you have instructions on how to access the environment or repro in a different environment. At this moment I don't have access to an arm64.

**Comment by ianhays** [comment]
I ran these tests again with the latest sources on our arm64 CI machine and did not see any failures:

```
Using C:\Users\DDJOIN\CoreFXTests\\Packages\ as folder for resolving package dependencies.
Executing in C:\Users\DDJOIN\CoreFXTests\System.Net.WebSockets.Client.Tests\ 
Hard linking dependent files... 
Finished linking needed files, moving to running tests.
Running tests... Start time: 15:51:56.16
Command(s):
call CoreRun.exe xunit.console.netcore.exe System.Net.WebSockets.Client.Tests.dll  -xml testResults.xml -notrait Benchmark=true  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Net.WebSockets.Client.Tests
Discovered:  System.Net.WebSockets.Client.Tests
Starting:    System.Net.WebSockets.Client.Tests
Finished:    System.Net.WebSockets.Client.Tests

=== TEST EXECUTION SUMMARY ===
   System.Net.WebSockets.Client.Tests  Total: 87, Errors: 0, Failed: 0, Skipped: 0, Time: 4.855s
```
