### ISSUE TITLE
DLLNotFoundException thrown when parsing a uri with unicode/unecessary escaping in the string on non-Windows platforms

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#7791]
## Problem
- Discovered in #6370

### Invalid Unicode (expects `UriFormatException`)
```csharp
new Uri("http://\uD800"); // Lone high surrogate
new Uri("http://\uDC00"); // Lone low surrogate
```

### Valid Unicode (expected no exception)
```csharp
new Uri("http://\u1234\u2345/\u1234\u2345?\u1234\u2345#\u1234\u2345");
new Uri("http://host/\u1234\u2345\u3456");
new Uri("http://host/abc\u1234\u2345\u3456");
new Uri("http://host/\u1234abc\u2345\u3456");
new Uri("http://host/\u1234\u2345\u3456abc");
new Uri("http://host/?abc\u1234\u2345\u3456");
new Uri("http://host/?\u1234abc\u2345\u3456");
new Uri("http://host/?\u1234\u2345\u3456abc");
new Uri("http://host/#abc\u1234\u2345\u3456");
new Uri("http://host/#\u1234abc\u2345\u3456");
new Uri("http://host/#\u1234\u2345\u3456abc");
// Unnecessarily escaped (upper case hex letters)
new Uri("http://host/%68%65%6C%6C%6F");
new Uri("http://host/?%68%65%6C%6C%6F");
new Uri("http://host/#%68%65%6C%6C%6F");
// Unnecessarily escaped (lower case hex letters)
new Uri("http://host/%68%65%6c%6c%6f");
new Uri("http://host/?%68%65%6c%6c%6f");
new Uri("http://host/#%68%65%6c%6c%6f");
// Compressed, but escaped
new Uri("http://host/%2E%2E/%2E%2E");
// Invalid punycode
new Uri("http://xn--abc");
// We allow any non-unreserved, percent encoding or sub-delimeter in the userinfo
new Uri("http://abc\u1234\u2345\u3456@host/");
new Uri("http://\u1234abc\u2345\u3456@host/");
new Uri("http://\u1234\u2345\u3456abc@host/");
new Uri("http://%68%65%6C%6C%6F@host/");
new Uri("http://\u1234@host/");
new Uri("http://userinfo%%%2F%3F%23%5B%5D%40%3B%26%2B%2C%5C%2g%2G@host");
new Uri("http://привет/");
new Uri("http://привет.ascii/");
new Uri("http://ascii.привет/");
new Uri("http://привет.βέλασμα/");
new Uri("http://\u1234\u2345\u3456/");
```

## Example stack trace
```
System.Tests.UriCreateStringTests.Create_String_InvalidUnicode [FAIL]
10:59:08       Assert.Throws() Failure
10:59:08       Expected: typeof(System.UriFormatException)
10:59:08       Actual:   typeof(System.DllNotFoundException): Unable to load DLL 'api-ms-win-core-errorhandling-l1-1-0.dll': The specified module could not be found.
10:59:08        (Exception from HRESULT: 0x8007007E)
10:59:08       Stack Trace:
10:59:08             at Interop.mincore.SetLastError(UInt32 dwErrCode)
10:59:08             at System.StringNormalizationExtensions.Normalize(String value, NormalizationForm normalizationForm)
10:59:08             at System.Uri.CheckAuthorityHelperHandleDnsIri(Char* pString, UInt16 start, Int32 end, Int32 startInput, Boolean iriParsing, Boolean hasUnicode, UriParser syntax, String userInfoString, Flags& flags, Boolean& justNormalized, String& newHost, ParsingError& err)
10:59:08             at System.Uri.CheckAuthorityHelper(Char* pString, UInt16 idx, UInt16 length, ParsingError& err, Flags& flags, UriParser syntax, String& newHost)
10:59:08             at System.Uri.PrivateParseMinimal()
10:59:08             at System.Uri.InitializeUri(ParsingError err, UriKind uriKind, UriFormatException& e)
10:59:08             at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
10:59:08             at System.Tests.UriCreateStringTests.<>c__DisplayClass16_0.<Create_String_Invalid>b__0()
```

## Investigation
- It seems that on non-Windows platforms, a windows native method is called - `interop.mincore.SetLastError(UInt32 dwErrCode)`
- All the failures have the same stack trace - fixing one of them is likely to fix them all

/cc @davidsh @stephentoub

**Comment by stephentoub** [comment]
This looks like some kind of deployment problem.  I've not looked deeply enough yet to know whether it's related to how binaries are copied around in CI or whether it's related to NuGet or something else, but when I build the System.Private.Uri.dll for unix, it does not contain any Windows-specific P/Invokes, and all of the tests run fine for me locally on Linux.

cc: @ellismg, @ericstj, @mmitche

**Comment by ericstj** [comment]
As far as I can tell this has nothing to do with packaging.  I've confirmed both the RC2 and RC3 packages *do not* have this problem.

This is happening because the System.Runtime tests hardcode "Windows_NT" as the OSGroup for the System.Private.Uri project reference: https://github.com/dotnet/corefx/blob/6d6c449199b67ecac7c59abc28f4c7b090f0c7a6/src/System.Runtime/tests/System.Runtime.Tests.csproj#L134

/cc @sokket

**Comment by stephentoub** [comment]
Thanks, Eric.
