### ISSUE TITLE
SendToRecvFromAPM_Single_Datagram_UDP_IPv4 failed on Windows in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7824]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_release/4/consoleFull

```
03:23:09      System.Net.Sockets.Tests.SendReceive.SendToRecvFromAPM_Single_Datagram_UDP_IPv4 [FAIL]
03:23:09         Assert.True() Failure
03:23:09         Expected: True
03:23:09         Actual:   False
03:23:09         Stack Trace:
03:23:09            D:\j\workspace\outerloop_win---65ef7d78\src\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs(211,0): at System.Net.Sockets.Tests.SendReceive.SendToRecvFromAPM_Datagram_UDP(IPAddress leftAddress, IPAddress rightAddress)
```

**Comment by CIPop** [comment]
According to the comment within the code, this is a duplicate to #5185.

**Comment by Priya91** [comment]
this failed again here

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/811/

**Comment by danmosemsft** [comment]
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/windows_nt_release_prtest/232/testReport/junit/System.Net.Sockets.Tests/SendReceive/SendToRecvFromAPM_Single_Datagram_UDP_IPv4/ 

```
MESSAGE:
Assert.True() Failure\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.Net.Sockets.Tests.SendReceive.SendToRecvFromAPM_Datagram_UDP(IPAddress leftAddress, IPAddress rightAddress) in D:\j\workspace\windows_nt_re---9f6acdf7\src\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs:line 211
```

**Comment by stephentoub** [comment]
@danmosemsft, you reopened the issue, but the link you shared is from the 1.0 branch.  Is that intentional?

**Comment by danmosemsft** [comment]
No.
