### ISSUE TITLE
[Mac OS X] System.Net.Http.WinHttpHandler throwing FileNotFoundException for 'winhttp.dll' 

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/corefx#7835]
I have a portable application that has a reference to the beta version (I think that is the latest) of System.Net.Http.dll.

project.json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002394"
    },
    "System.Net.Http": "4.0.0-beta-*"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports" : ["dnxcore50", "portable-net45+win8"]
    }
  }
}

The app restores and builds successfully.  But when it is run it fails with the following:

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'winhttp.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at System.Net.Http.Interop.WinHttpSetStatusCallback(SafeInternetHandle handle, WINHTTP_STATUS_CALLBACK callback, UInt32 notificationFlags, IntPtr reserved)
   at System.Net.Http.WinHttpHandler.SetStatusCallback(SafeInternetHandle requestHandle, WINHTTP_STATUS_CALLBACK callback)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

This feels like an issue with sharedfx and not inferring the runtime correctly.  (Note I did not run with restore --infer-runtimes b/c I think that is a workaround not a fix).  
[curl.tar.gz](https://github.com/dotnet/corefx/files/224499/curl.tar.gz)

**Comment by jeffschwMSFT** [comment]
Ported to https://github.com/dotnet/cli/issues/2585

**Comment by jeffschwMSFT** [comment]
Move to dotnet/cli
