### ISSUE TITLE
Is the Content-Type header produced by StringContent() correct?

### ISSUE THREAD

**Issue by GuardRex** [dotnet/corefx#7864]
Consider the following code ...
```c#
string contentType = "application/atom+xml";
string requestPayload = "some data";
var stringContent = new StringContent(requestPayload, Encoding.UTF8, contentType);
```
According to Wireshark, I'm seeing a POST using `HttpClient` with this ...
```
Content-Type: application/atom+xml; charset=utf-8
```
![capture](https://cloud.githubusercontent.com/assets/1622880/14647964/a1396782-0625-11e6-9c7a-3cdc1b92e4a2.PNG)

Shouldn't that `Content-Type` value just be ...
```
Content-Type: application/atom+xml
```
?? Confused, because something is choking my Azure Table Storage requests with ...
```
string stringToSign = 
    $"{requestMethod}\n\n{contentType}\n{dateInRfc1123Format}\n{canonicalizedResource}";
```
... and since `SharedKeyLite`, which only requires the date and resource, **works** with my `dateInRfc1123Format` and `canonicalizedResource`, I've sort of narrowed it down to the `contentType` of the request (shown above) not matching what I'm putting into the signature sting, namely just `application/atom+xml`.

**Comment by benaadams** [comment]
Looks like it will always put something out https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Net.Http/src/System/Net/Http/StringContent.cs#L29

**Comment by davidsh** [comment]
The `StringContent` constructor follows the same behavior as .NET Framework (Desktop).

You can always replace the `Content-Type` (or any header) with something else if the default behavior isn't what you want.

**Comment by JonHanna** [comment]
It's certainly invalid. RFC 2046 (RFC 6657 is also relevant) allows for the charset parameter as part of content-types only if it's `text/plain` or a `text/*` type that specifies it too allows.

**Comment by GuardRex** [comment]
@benaadams @JonHanna Thanks for finding the references to both. Even if it were valid (e.g., `text/plain` or `text/*`), I think if you supply the value explicitly, the value should be honored when the header is created IMHO.

I don't know if this is what is choking my ATS REST service calls, but it's possible, since `SharedKeyLite` works with my date and resource. This is certainly a suspect for my failing `SharedKey` request failures.

@davidsh How? I get an exception if I try to mod the header by adding ...
```c#
client.DefaultRequestHeaders.Add("Content-Type", contentType);
```
... throws ...
```
System.InvalidOperationException: Misused header name. Make sure request headers are used 
with HttpRequestMessage, response headers with HttpResponseMessage, and content headers 
with HttpContent objects.
 at System.Net.Http.Headers.HttpHeaders.CheckHeaderName(String name)
 at teststandalone.HomeController.DoIt()
```
Here's the hacked code I'm playing with (i.e., not for production ... I'm just hacking around to get the requests working). How would I set the `Content-Type` explicitly to override the `StringContent` one  given this code ..
```c#
using (var client = new HttpClient())
{
    DateTime requestDT = DateTime.UtcNow;
    UTF8Encoding utf8Encoding = new UTF8Encoding();
    string storageAccountName = "<STORAGE_ACCOUNT_NAME>";
    string tableName = "<TABLE_NAME>";
    //string requestMethod = "POST";
    string dateInRfc1123Format = requestDT.ToString("R", CultureInfo.InvariantCulture);
    string storageServiceVersion = "2015-04-05";
    string storageAccountKey = "<STORAGE_ACCOUNT_KEY>";
    string canonicalizedResource = $"/{storageAccountName}/{tableName}";
    string contentType = "application/atom+xml";
    
    // Content
    string requestPayload = GetRequestContentInsertXml(requestDT, "PKEY", "RKEY");
    var stringContent = new StringContent(requestPayload, Encoding.UTF8, contentType);

    // Will not authorize against the service:
    // string stringToSign = $"{requestMethod}\n\n{contentType}\n{dateInRfc1123Format}\n{canonicalizedResource}";
    // SharedKeyLite works:
    string stringToSign = $"{dateInRfc1123Format}\n{canonicalizedResource}";
    string authorizationHeader = CreateAuthorizationParameter(stringToSign, storageAccountName, storageAccountKey);
    AuthenticationHeaderValue myAuthHeaderValue = new AuthenticationHeaderValue("SharedKeyLite", authorizationHeader);
    
    // Headers
    client.DefaultRequestHeaders.Authorization = myAuthHeaderValue;
    client.DefaultRequestHeaders.Add("x-ms-date", dateInRfc1123Format);
    client.DefaultRequestHeaders.Add("x-ms-version", storageServiceVersion);
    client.DefaultRequestHeaders.Add("DataServiceVersion", "3.0;NetFx");
    client.DefaultRequestHeaders.Add("MaxDataServiceVersion", "3.0;NetFx");
    
    var responseMessage = client.PostAsync($"https://{storageAccountName}.table.core.windows.net/{tableName}", stringContent).Result;
    
    responseResult.Append("StatusCode: " + responseMessage.StatusCode.ToString() + " ");
    
}
```

**Comment by davidsh** [comment]
When modifying "known" headers, you need to use the properties and not the 'DefaultRequestHeaders' method.  For request entity-body headers (content), you need to modify the `HttpRequestMessage.Content.Headers1 collection.  You are getting an exception telling you that basically.

So, you need code like this:

```c#
var content = new StringContent(...);
content.Headers.ContentType = ...;
```

You can also use methods like this as well:

```c#
var content = new StringContent(...);
content.Headers.Remove(...);
content.Headers.Add(...);
```

**Comment by GuardRex** [comment]
@davidsh Ah ... ok ... thx ... that got the header squared away ...
```c#
stringContent.Headers.ContentType = 
    new System.Net.Http.Headers.MediaTypeHeaderValue(contentType);
```
![capture](https://cloud.githubusercontent.com/assets/1622880/14649859/8e381da0-062e-11e6-90ce-7c04560a2f9c.PNG)

And :tada: **YES!** :tada: ... that cleared up the problem with ATS REST API: `SharedKey` works now! :smile: :+1: :beers:

My issue is solved, but do you want to leave this open given what @JonHanna reported?

**Comment by davidsh** [comment]
>My issue is solved, but do you want to leave this open given what @JonHanna reported?

We will research this to determine if there are RFC issues.  This code has existed for 5+ years and was previously reviewed by our RFC compliance experts. I'll leave this open for now.

**Comment by JonHanna** [comment]
I was incorrect.

While `charset` was originally defined only for use with `text/*` types, there's nothing to stop some particular type in another group using a copy of it, and RFC 3023 did exactly that with it **strongly recommended** to be used along with `application/xml` and suggested, and then RFC 4287 references that in turn in allowing `charset` with `application/atom+xml`. So it's not in the slightest invalid to have that parameter with that content type, sorry for my misleading comment.

**Comment by GuardRex** [comment]
My concern about it remains: If the dev sets a value explicitly on `new StringContent()`, they will not be aware that `charset` is being added.

In any case where the header is part of a service-generated hash that will be checked against a supplied signature (without the `charset`, since the dev didn't know it was added to the request header), as is the case with Azure Storage REST Service, ... :boom: ... and lost time having to check a lot of little things partially because the Azure REST docs and exception messages are so poor. All the service comes back with is 'your auth header is hosed! ... check the signature.'

If the dev sets an explicit value, seems like it should be honored. At least mod the description to note that `charset` will be added automatically. It's possible that if I saw that pop-up in VS when I was laying down the code, it might have triggered more immediate interest in trying `MediaTypeHeaderValue()`.

**Comment by GuardRex** [comment]
Just for completeness, I checked the Azure Service REST Service using the default ...
```c#
StringContent("<data>", Encoding.UTF8, "application/atom+xml");
```
... but supplying the content type to the signature string as ...
```c#
string contentType = "application/atom+xml; charset=utf-8";
string stringToSign = 
    $"{requestMethod}\n\n{contentType}\n{dateInRfc1123Format}\n{canonicalizedResource}";
```
That works. It's still awfully cryptic tho without a little help.

**Comment by darrelmiller** [comment]
@JonHanna Usually it is the media type registration document that defines what parameters are allowed.  In the application/atom+xml the [registration](http://www.iana.org/assignments/media-types/application/atom+xml) refers explicitly back RFC3023 for the rules, as you stated.  

Interestingly, the .net stack loves adding charset onto `application/json` but in that case charset is not defined by the [media type registration](http://www.iana.org/assignments/media-types/application/json).   In fact [RFC 7158](https://tools.ietf.org/html/rfc7158) goes on to say,

>  Note:  No "charset" parameter is defined for this registration.
>       Adding one really has no effect on compliant recipients.
>
It would be awesome if this could be fixed.

**Comment by davidsh** [comment]
We plan to fix this in CoreFx. We need to study if porting this to .NET Framework (Desktop) will have any app-compat issues.

**Comment by davidsh** [comment]
This will require a new overload to the StringContent constructor so that the charset isn't specified by default on the `Content-Type` request header.  So, we'll need an API proposal for that.

**Comment by tknuts** [comment]
Hi
I have a simular problem with json post to Azure Table Storage, here is my code:

            var content = "{\"PartitionKey\":\"MemberSyncDto_4-2018\",\"RowKey\":\"1218\",\"SType\":\"3\"}"; // ,\n
            var updateContent = new StringContent(content, Encoding.UTF8, "application/json");
            updateContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");

            using (var client = new HttpClient())
            {
                // Add the request headers for x-ms-date and x-ms-version.
                DateTime now = DateTime.UtcNow;
                var dateHeader = now.ToString("R", CultureInfo.InvariantCulture);

                client.DefaultRequestHeaders.Authorization = AzureStorageAuthenticationHelper.GetAuthorization(
                    storageAccountName, storageAccountKey, now, new Uri(uri));
                client.DefaultRequestHeaders.Add("x-ms-date", dateHeader);
                client.DefaultRequestHeaders.Add("x-ms-version", "2018-03-28");
                client.DefaultRequestHeaders.Add("DataServiceVersion", "3.0;NetFx");
                client.DefaultRequestHeaders.Add("MaxDataServiceVersion", "3.0;NetFx");

                Console.WriteLine("x-ms-date: {0}", dateHeader);
                Console.WriteLine("Content: {0}", content);
                Console.WriteLine("Auth: {0}", client.DefaultRequestHeaders.Authorization);
                Console.WriteLine("ContentLength: {0}", content.Length);

                var responseMessage = await client.PostAsync(uri, updateContent, cancellationToken);
                Console.WriteLine("Result: {0}", responseMessage.StatusCode);
            }
        }

Quite simpel..... If I do this in Postman it works, but i keep getting 415 error "Unsupported Media Type" :-(

Why?

Desperate now, tried everything..... Can do GET requests, but not POST. I can get the same error in Postman by removing the Content-Type header...

**Comment by tknuts** [comment]
`client.DefaultRequestHeaders.Add("Accept", "*/*");`

Did the trick :-)

**Comment by stephentoub** [comment]
> This will require a new overload to the StringContent constructor so that the charset isn't specified by default on the Content-Type request header. So, we'll need an API proposal for that.

@davidsh, can you elaborate on why this would require a new API?

**Comment by davidsh** [comment]
This is the current API:

```c#
    public partial class StringContent : System.Net.Http.ByteArrayContent
    {
        public StringContent(string content) : base (default(byte[])) { }
        public StringContent(string content, System.Text.Encoding encoding) : base (default(byte[])) { }
        public StringContent(string content, System.Text.Encoding encoding, string mediaType) : base (default(byte[])) { }
    }
```

None of the overloads take any 'charset' parameter.  But they all create one anyways.  See `headerValue.CharSet`.

```c#
        public StringContent(string content, Encoding encoding, string mediaType)
            : base(GetContentByteArray(content, encoding))
        {
            // Initialize the 'Content-Type' header with information provided by parameters. 
            MediaTypeHeaderValue headerValue = new MediaTypeHeaderValue((mediaType == null) ? DefaultMediaType : mediaType);
            headerValue.CharSet = (encoding == null) ? HttpContent.DefaultStringEncoding.WebName : encoding.WebName;

            Headers.ContentType = headerValue;
        }
```

So, we would need a new overload that could explicitly take a charset parameter (or null) etc.

**Comment by karelz** [comment]
Triage: We need to finish the API proposal.
cc @scalablecory

**Comment by darrelmiller** [comment]
@karelz What if a new overload used a MediaTypeHeaderValue as the parameter?  That would seem like the simplest solution.  Am I missing something?

**Comment by stephentoub** [comment]
> What if a new overload used a MediaTypeHeaderValue as the parameter?

That sounds good to me:
```C#
public StringContent(string content, MediaTypeHeaderValue mediaType)
```
In addition to being simple, it has the added benefit that it lets you avoid a MediaTypeHeaderValue allocation per StringContent, if you want to just use the same instance over and over.

**Comment by terrajobst** [comment]
We believe the correct API is this:

```C#
public StringContent(string content, MediaTypeHeaderValue mediaType)
```
