### ISSUE TITLE
System.Net.Internals.InternalSocketException on OSX/Linux (Debian)

### ISSUE THREAD

**Issue by Edu115** [dotnet/corefx#8086]
Hi guys,

I have been struggling with this error for a few days, on an asp.net core application.
I've created a simpler application that just does a select query, and while it works fine in Windows, it doesn't work on both OS X and Linux (under docker with a debian image).
Although the Exception is the same on both environments, the message is slightly different:

OS X:

Environment details:
<pre>
Unhandled Exception: System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.AggregateException: One or more errors occurred. (Device not configured) ---> 
<b>System.Net.Internals.InternalSocketException: Device not configured</b>
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.SqlClient.SNI.SNITCPHandle.<ConnectAsync>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at SqlClientTest.Program.Main(String[] args)
</pre>

The message on Linux:
<pre>
Unhandled Exception: System.Data.SqlClient.SqlException: A network-related or in
stance-specific error occurred while establishing a connection to SQL Server. Th
e server was not found or was not accessible. Verify that the instance name is c
orrect and that SQL Server is configured to allow remote connections. (provider:
 TCP Provider, error: 35 - An internal exception was caught) ---> System.Aggrega
teException: One or more errors occurred. (No such device or address) ---> <b> Syste
m.Net.Internals.InternalSocketException: No such device or address</b>
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,
Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchron
ization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Data.SqlClient.SNI.SNITCPHandle.<ConnectAsync>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port
, Int64 timerExpire, Object callbackObject, Boolean parallel)
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdent
ity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolea
n redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData
 reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOp
tions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConn
ectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConn
ectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConne
ctionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owning
Object, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection o
wningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection
)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection ow
ningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean o
nlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& co
nnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection ow
ningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbCon
nectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection
 owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions
, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(Db
Connection outerConnection, DbConnectionFactory connectionFactory, TaskCompletio
nSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at SqlClientTest.Program.Main(String[] args)
</pre>

Environment settings:
* dotnet cli version : 1.0.0-rc2-002422
* nuget feed: https://www.myget.org/F/aspnetvnext
* database version: Sql Server 2012 SP1 (11.00.3412)

The application is just this Program.cs

```
using System;
using System.Data.SqlClient;
using System.Collections.Generic;

namespace SqlClientTest
{
    public static class Program
    {
        public static void Main(string[] args)
        {
            string connectionString = "Data Source=[OUR_DB_SERVER_IP]\\MASTER;Initial Catalog=[OUR_DB_NAME];MultipleActiveResultSets=False;User Id=[USER_ID]; Password=[OUR_PASSWORD];";

            string sql = "select TOP 10 id, vestigingNummer, kantoorNaam1 from NVM_Vestiging where idIsActive = 1";

            List<Makelaar> makelaars = new List<Makelaar>();

            using (var conn = new SqlConnection(connectionString))
            {
                conn.Open();

                using (var command = new SqlCommand(sql, conn))
                {
                    var reader = command.ExecuteReader();
                    while (reader.Read())
                    {
						int id = reader.GetInt32(0);
						int vestigingNummer = reader.GetInt32(1);
						string kantoorNaam = reader.GetString(2);

                        makelaars.Add(new Makelaar(id, vestigingNummer, kantoorNaam));
                    }
                }
            }

            foreach (var makelaar in makelaars)
            {
				Console.WriteLine($"{makelaar.VestigingNummer}: {makelaar.KantoorNaam}");
            }
        }
    }

    public class Makelaar
    {
        public Makelaar(int id, int vestigingNummer, string kantoorNaam)
        {
            Id = id;
            VestigingNummer = vestigingNummer;
            KantoorNaam = kantoorNaam;
        }

        public int Id { get; set; }
        public int VestigingNummer { get; set; }
        public string KantoorNaam { get; set; }
    }
}
```

and the project.json:
```
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-*"
    },
	"System.Runtime": "4.0.0-rc2-24018",
	"System.Data.SqlClient": "4.1.0-rc2-24018",
	"System.Collections":"4.0.0-rc2-24018",
	"System.Console": "4.0.0-rc2-24018"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
```

Running a python client using the FreeTDS driver works fine, so this seems specific to System.Data.SqlClient, and not to our database.

**Comment by Edu115** [comment]
From what I understand, the error seems to be the same, but the message is probably an internal error, that I guess is different depending on the OS.

**Comment by joshfree** [comment]
@saurabh500 @ericeil could you please take a look?

**Comment by joshfree** [comment]
@Edu115 does this repro only inside of a docker container?

**Comment by Edu115** [comment]
@joshfree No, in OS X I am running it directly without docker.
The error message is different, but I believe it is a OS specific message, the error is probably the same.

**Comment by saurabh500** [comment]
@Edu115 In your connection string you have [OUR_DB_SERVER_IP]\\MASTER
Can you try connecting with the port of the instance instead of the instance name? 

Data Source=Our_Db_server,IntegerPort   
E.g. Data Source=mydb.example.com,1433

**Comment by Edu115** [comment]
@saurabh500 oh, I was so close :) ! My last connection string had something like [OUR_DB_SERVER_IP]\[INSTANCE],[PORT], but I had no idea you could just skip the instance if you use the port.

Long story short: it works with the port and removing the instance name!  

We are, however, using dynamic ports, so referring directly to the port of the instance is problematic, right?

**Comment by saurabh500** [comment]
@Edu115 Thanks for the confirmation.

Unfortunately System.Data.SqlClient doesn't yet support instance name in the connection strings. To connect from Linux and OSX you will have to rely on specifying the server port right now.

**Comment by saurabh500** [comment]
> but I had no idea you could just skip the instance if you use the port.

A few notes on how the instance name resolution works. 
The Sql Server host machine has a Sql Browser service that runs. Once you configure an instance of the SqlServer, it is assigned a port. You can also specify the name for the instance which can be used for connecting to the server.

When you specify the name of the Sql Server instance, the browser service is queried for the port of the Sql Server. If you specify sqlhost.example.com\master, the browser service first needs to be queried for the port on which the `master` instance is running and then the port is used for connectivity. More information here https://technet.microsoft.com/en-us/library/ms181087(v=sql.105).aspx

**Comment by saurabh500** [comment]
Duplicate of https://github.com/dotnet/corefx/issues/4346

**Comment by Edu115** [comment]
Thanks @saurabh500 for the quick feedback and explanation.

Hopefully, using instance names will be possible by RC3.

Since this is a duplicate, I'll close it.

**Comment by joshfree** [comment]
@saurabh500 would it be possible to improve the exception message(s) here to make the instance name resolution issue / platform parity edge cases more discoverable and actionable?

**Comment by doublnt** [comment]
I have the same question and Error with you @Edu115 ,and how did you solve it ?

**Comment by Edu115** [comment]
@doublnt I solved it as @saurabh500 described, by using the server port.

**Comment by mika76** [comment]
Just tried and RC3 is throwing the same error...
