### ISSUE TITLE
SendAsync - System.Net.Http.HttpRequestException: Error while copying content to a stream

### ISSUE THREAD

**Issue by attilalaszlo** [dotnet/corefx#8113]
I have a quite critical issue with HttpContent disposing _just_ on linux. (under IIS 8.5 it's working fine)
Tried with: coreclr 1.0.0-rc1-update1 and 1.0.0-rc1-update2

I made an action in an asp.net web api, and in that:
```
                var uri = "http://....";
                content = new ByteArrayContent(new byte[0]);
                var requestMsg = new HttpRequestMessage(System.Net.Http.HttpMethod.Post, uri);
                requestMsg.Content = content;
                var client = new HttpClient();
                var response = client.SendAsync(requestMsg, HttpCompletionOption.ResponseContentRead, System.Threading.CancellationToken.None).GetAwaiter().GetResult();
                return Json(string.Empty);
```

If I start a load test on thin, then randomly get this error message:
```
Microsoft.AspNet.Server.Kestrel[13]
      An unhandled exception was thrown by the application.
      System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'System.Net.Http.ByteArrayContent'.
         at System.Net.Http.HttpContent.CheckDisposed()
         at System.Net.Http.HttpContent.CopyToAsync(Stream stream, TransportContext context)
         at System.Net.Http.CurlHandler.HttpContentAsyncStream.<Run>b__26_0()
         at System.Threading.Tasks.Task`1.InnerInvoke()
         at System.Threading.Tasks.Task.Execute()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Net.Http.CurlHandler.MultiAgent.TransferDataFromRequestStream(IntPtr buffer, Int32 length, EasyRequest easy)
         at System.Net.Http.CurlHandler.MultiAgent.CurlSendCallback(IntPtr buffer, UInt64 size, UInt64 nitems, IntPtr context)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Net.Http.StreamToStreamCopy.<CopyAsync>d__0.MoveNext()
         --- End of inner exception stack trace ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at httptest.Controllers.ValuesController.Get()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at Microsoft.AspNet.Mvc.Controllers.ControllerActionExecutor.ExecuteAsync(MethodInfo actionMethodInfo, Object instance, Object[] orderedActionArguments)
         at Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeActionFilterAsync>d__53.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__44.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at Microsoft.AspNet.Mvc.Routing.InnerAttributeRoute.<RouteAsync>d__10.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__8.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass32_0.<<Start>b__0>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at Microsoft.AspNet.Server.Kestrel.Http.Frame.<RequestProcessingAsync>d__79.MoveNext()
```

I investigated it for several days. Finally I make a wrapper class for the ByteArrayContent:

```
    public class SlambyByteArrayContent : ByteArrayContent
    {
        public SlambyByteArrayContent(byte[] content):base(content) { }


        protected override void Dispose(bool disposing)
        {
            //do nothing
        }

        public void DisposeManually(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
```

And change my code to:

```
            SlambyByteArrayContent content = null;
            try
            {
                var uri = "http://....";
                content = new SlambyByteArrayContent(new byte[0]);
                var requestMsg = new HttpRequestMessage(System.Net.Http.HttpMethod.Get, uri + "_stats");
                requestMsg.Content = content;
                var client = new HttpClient();
                var response = client.SendAsync(requestMsg, HttpCompletionOption.ResponseContentRead, System.Threading.CancellationToken.None).GetAwaiter().GetResult();
                return Json(string.Empty);
            }finally
            {
                if (content != null) content.DisposeManually(true);
            }

```

Now it's working for my case but I think there must be some evil around the HttpContent disposing.

**Comment by stephentoub** [comment]
@attilalaszlo, thanks for reporting this.  When you say that preventing the disposal of the HttpContent addressed the problem, can you clarify what the behavior then is?  In looking at the code this morning, I see how this issue could arise, and I'll be looking into a fix for it, but I'd have expected it to only occur in a situation where the request was already failing or being canceled... when you prevented the HttpContent disposal, are you then just getting an expected error, or did preventing the HttpContent disposal actually allow all of your requests to succeed?

**Comment by attilalaszlo** [comment]
@stephentoub After I made the quoted modification (preventing the HttpContent disposal), my requests are succeed.
So I expected all my requests to succeed, but the HttpContent was disposed (as I guess before it reached the requested server itself). After I was preventing the dispose (and do it manually) all my requests were succeed.

**Comment by stephentoub** [comment]
Thanks, @attilalaszlo.  Have you tried on something more recent than rc1?  Could I ask you to try with a recent rc2 build?  (System.Net.Http didn't actually change in any of the rc1 updates, so the bits have evolved quite a bit since the build you're using.)  In the meantime I'll look into it further.

**Comment by stephentoub** [comment]
One more question:
In your repro you have:
```C#
new ByteArrayContent(new byte[0]);
```
Does this repro if you use a non-empty content? e.g. if you use ```new byte[100]``` instead of ```new byte[0]```?

**Comment by attilalaszlo** [comment]
@stephentoub I'll check with rc2 on the weekend.
I didn't checked with `new byte[100]` but I checked with `StreamContent` and `StringContent` and did the same random error.
It can be important that I can't repro it under IIS.

**Comment by stephentoub** [comment]
Thanks, @attilalaszlo.  When you say "but I checked with  StreamContent  and  StringContent  and did the same random error", were they empty (0-length) or did they have data to send?

**Comment by attilalaszlo** [comment]
@stephentoub empty and data included requests also can do the same (and also tried with various httpmethod (get, post, put, delete))

**Comment by stephentoub** [comment]
@attilalaszlo, is it possible for you to share a standalone repro of the issue?

I can't repro what you're seeing using the latest code.  I can see from the code how this could happen if either the request was failing/being canceled, or potentially if the content length was 0, but I don't see how it could happen with positive content length on a request that was otherwise succeeding.  Hence if you're able to provide a repro, that'd be quite helpful.

We could also wait until you've updated to recent rc2 bits to see if it still repros there.

Separately, in your repro I see that on each request you're creating a new HttpClient instance.  That's not the recommended approach.  HttpClient is optimized for scenarios where it's created once and then reused many times.  And it can be used concurrently, so it'd be better to create one instance of it and then reuse that instance for all requests.

With regards to your comments about IIS, I'm assuming you just mean you don't see this on Windows but you do on Linux, rather than it being about a specific server on Windows, right?
