### ISSUE TITLE
Console.Readline throws null reference exception

### ISSUE THREAD

**Issue by AshwiniReddyChalla** [dotnet/corefx#8162]
following is the stack trace
System.NullReferenceException: Object reference not set to an instance of an object.
at System.ConsolePal.TryGetSpecialConsoleKey(Char[] givenChars, Int32 startIndex, Int32 endIndex, ConsoleKeyInfo& key, Int32& keyLength)
at System.IO.StdInStreamReader.MapBufferToConsoleKey(ConsoleKey& key, Char& ch, Boolean& isShift, Boolean& isAlt, Boolean& isCtrl)
at System.IO.StdInStreamReader.ReadKey(Boolean& previouslyProcessed)
at System.IO.StdInStreamReader.ReadLine(Boolean consumeKeys)
at System.IO.SyncTextReader.ReadLine()
at System.Console.ReadLine()

My scenario is following
My command takes inputs from user interactively.
When I give inputs interactively it works fine.
But when I used expect,send to give inputs remotely, I got a null ref exception.
from the diag logs of expect, I can see that send sends the input properly. Yet I got this exception.
Can someone throw light what can be wrong?

**Comment by svick** [comment]
Could you give more information so that the error can be reproduced? How does your code look like? What is your `project.json`? How exactly do you run the program? What is your OS? What are the versions of the applications involved?

**Comment by ellismg** [comment]
My guess is this is a Unix specific issue and Expect refers to the [Tcl based program](https://en.wikipedia.org/wiki/Expect).  Is this correct?
