### ISSUE TITLE
System.Globalization.Tests failed on Ubuntu16.04

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#8180]
```
12:19:16    System.Globalization.Tests.DateTimeFormatInfoGetDayName.GetDayName(format: DateTimeFormatInfo { AbbreviatedDayNames = ["Dim.", "Lun.", "Mar.", "Mer.", "Jeu.", ...], AbbreviatedMonthGenitiveNames = ["janv.", "févr.", "mars", "avr.", "mai", ...], AbbreviatedMonthNames = ["Janv.", "Févr.", "Mars", "Avr.", "Mai", ...], AMDesignator = "AM", Calendar = GregorianCalendar { CalendarType = Localized, Eras = [...], IsReadOnly = False, MaxSupportedDateTime = 9999-12-31T23:59:59.9999999, MinSupportedDateTime = 0001-01-01T00:00:00.0000000, ... }, ... }, expected: ["dimanche", "lundi", "mardi", "mercredi", "jeudi", ...]) [FAIL]
12:19:16       Assert.Equal() Failure
12:19:16                 ↓ (pos 0)
12:19:16       Expected: dimanche
12:19:16       Actual:   Dimanche
12:19:16                 ↑ (pos 0)
12:19:16       Stack Trace:
12:19:16             at System.Globalization.Tests.DateTimeFormatInfoGetDayName.GetDayName(DateTimeFormatInfo format, String[] expected)
12:19:16    System.Globalization.Tests.DateTimeFormatInfoGetMonthName.GetMonthName(format: DateTimeFormatInfo { AbbreviatedDayNames = ["Dim.", "Lun.", "Mar.", "Mer.", "Jeu.", ...], AbbreviatedMonthGenitiveNames = ["janv.", "févr.", "mars", "avr.", "mai", ...], AbbreviatedMonthNames = ["Janv.", "Févr.", "Mars", "Avr.", "Mai", ...], AMDesignator = "AM", Calendar = GregorianCalendar { CalendarType = Localized, Eras = [...], IsReadOnly = False, MaxSupportedDateTime = 9999-12-31T23:59:59.9999999, MinSupportedDateTime = 0001-01-01T00:00:00.0000000, ... }, ... }, expected: ["", "janvier", "février", "mars", "avril", ...]) [FAIL]
12:19:16       Assert.Equal() Failure
12:19:16                 ↓ (pos 0)
12:19:16       Expected: janvier
12:19:16       Actual:   Janvier
12:19:16                 ↑ (pos 0)
12:19:16       Stack Trace:
12:19:16             at System.Globalization.Tests.DateTimeFormatInfoGetMonthName.GetMonthName(DateTimeFormatInfo format, String[] expected)
12:19:16    System.Globalization.Tests.NumberFormatInfoNumberGroupSizes.NumberGroupSizes_Get(format: NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = ".", CurrencyGroupSeparator = ",", CurrencyGroupSizes = [3, 2], CurrencyNegativePattern = 9, ... }, expected: [3, 2]) [FAIL]
12:19:16       Assert.Equal() Failure
12:19:16       Expected: Int32[] [3, 2]
12:19:16       Actual:   Int32[] [3]
12:19:16       Stack Trace:
12:19:16             at System.Globalization.Tests.NumberFormatInfoNumberGroupSizes.NumberGroupSizes_Get(NumberFormatInfo format, Int32[] expected)
12:19:17 Finished:    System.IO.Compression.ZipFile.Tests
12:19:17 
12:19:17 === TEST EXECUTION SUMMARY ===
12:19:17    System.IO.Compression.ZipFile.Tests  Total: 24, Errors: 0, Failed: 0, Skipped: 0, Time: 2.360s
12:19:17 Finished:    System.Globalization.Calendars.Tests
12:19:17 
12:19:17 === TEST EXECUTION SUMMARY ===
12:19:17    System.Globalization.Calendars.Tests  Total: 2086, Errors: 0, Failed: 0, Skipped: 0, Time: 2.121s
12:19:17    System.Globalization.Tests.DateTimeFormatInfoGetAbbreviatedDayName.GetAbbreviatedDayName(info: DateTimeFormatInfo { AbbreviatedDayNames = ["Dim.", "Lun.", "Mar.", "Mer.", "Jeu.", ...], AbbreviatedMonthGenitiveNames = ["janv.", "févr.", "mars", "avr.", "mai", ...], AbbreviatedMonthNames = ["Janv.", "Févr.", "Mars", "Avr.", "Mai", ...], AMDesignator = "AM", Calendar = GregorianCalendar { CalendarType = Localized, Eras = [...], IsReadOnly = False, MaxSupportedDateTime = 9999-12-31T23:59:59.9999999, MinSupportedDateTime = 0001-01-01T00:00:00.0000000, ... }, ... }, expected: ["dim.", "lun.", "mar.", "mer.", "jeu.", ...]) [FAIL]
12:19:17       Assert.Equal() Failure
12:19:17                 ↓ (pos 0)
12:19:17       Expected: dim.
12:19:17       Actual:   Dim.
12:19:17                 ↑ (pos 0)
12:19:17       Stack Trace:
12:19:17             at System.Globalization.Tests.DateTimeFormatInfoGetAbbreviatedDayName.GetAbbreviatedDayName(DateTimeFormatInfo info, String[] expected)
12:19:17    System.Globalization.Tests.DateTimeFormatInfoGetAbbreviatedMonthName.GetAbbreviatedMonthName(info: DateTimeFormatInfo { AbbreviatedDayNames = ["Dim.", "Lun.", "Mar.", "Mer.", "Jeu.", ...], AbbreviatedMonthGenitiveNames = ["janv.", "févr.", "mars", "avr.", "mai", ...], AbbreviatedMonthNames = ["Janv.", "Févr.", "Mars", "Avr.", "Mai", ...], AMDesignator = "AM", Calendar = GregorianCalendar { CalendarType = Localized, Eras = [...], IsReadOnly = False, MaxSupportedDateTime = 9999-12-31T23:59:59.9999999, MinSupportedDateTime = 0001-01-01T00:00:00.0000000, ... }, ... }, expected: ["", "janv.", "févr.", "mars", "avr.", ...]) [FAIL]
12:19:17       Assert.Equal() Failure
12:19:17                 ↓ (pos 0)
12:19:17       Expected: janv.
12:19:17       Actual:   Janv.
12:19:17                 ↑ (pos 0)
12:19:17       Stack Trace:
12:19:17             at System.Globalization.Tests.DateTimeFormatInfoGetAbbreviatedMonthName.GetAbbreviatedMonthName(DateTimeFormatInfo info, String[] expected)
12:19:19 Discovered:  System.Dynamic.Runtime.Tests
12:19:19 Starting:    System.Dynamic.Runtime.Tests
12:19:20 Finished:    System.Globalization.Tests
```

**Comment by ellismg** [comment]
We had disabled the tests for Ubuntu 15.10 when we had run them previously.

```
> git grep PlatformDetection.IsUbuntu1510
System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoGetAbbreviatedDayName.cs:            if (!PlatformDetection.IsUbuntu1510)
System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoGetAbbreviatedMonthName.cs:            if (!PlatformDetection.IsUbuntu1510)
System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoGetDayName.cs:            if (!PlatformDetection.IsUbuntu1510)
System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoGetMonthName.cs:            if (!PlatformDetection.IsUbuntu1510)
System.Globalization/tests/NumberFormatInfo/NumberFormatInfoNumberGroupSizes.cs:            if (!PlatformDetection.IsUbuntu1510 && !PlatformDetection.IsWindows7)
```

We should probably just expand the check to also disable them on Ubuntu 16.04.

**Comment by tarekgh** [comment]
@ellismg will do. I just need to setup 16.04 to make sure my changes will address this issue.

**Comment by tarekgh** [comment]
@ellismg is there a new instructions how to get corefx build on Ubuntu 16.04? 
I am able to get coreclr build there but I am not able to get corefx build. I have installed all needed Linux packages according to the doc of building corefx on Linux. 

when running ./build.sh (on clean cloned corefx), I am getting the following errors:
```
CMakeFiles/Makefile2:85: recipe for target 'System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native.dir/all' failed
make[1]: *** [System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

I tried to build native components only using ```./build.sh native``` and this surprisely  succeeded. then I tried to run ```./build.sh``` again but this time I got the following errors:

```
Tools are already initialized
./build.sh: line 105: /home/tarek/oss/corefx/Tools/corerun: No such file or directory

tail: cannot open '/home/tarek/oss/corefx/msbuild.log' for reading: No such file or director
```

looks to me the tool package is not installed correctly.
any idea what I am missing here?

**Comment by ellismg** [comment]
@tarekgh We don't support building managed code on Ubuntu 16.04 yet (because we don't have a CLI that works on that platform, so we can restore a tool runtime).

https://github.com/dotnet/corefx/blob/master/Documentation/building/cross-platform-testing.md outlines how we do cross platform builds in CI for platforms where we can't do local builds.  I believe these instructions will work for you.

The other option is to just make the change locally, submit a PR and then "@dotnet-bot test Ubuntu16.04 please".  That should trigger builds for the PR, I believe.

**Comment by tarekgh** [comment]
merged the linked PR.
