### ISSUE TITLE
System.Net.Http.Functional.Tests.HttpClientHandler test failed on Ubuntu16.04

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#8181]
```
12:38:02    System.Net.Http.Functional.Tests.HttpClientHandler_Timeouts_Test.ConnectTimeout_TimesOut_Throws [FAIL]
12:38:02       Assert.InRange() Failure
12:38:02       Range:  (1 - 10000)
12:38:02       Actual: 100003
12:38:02       Stack Trace:
12:38:02             at System.Net.Http.Functional.Tests.HttpClientHandler_Timeouts_Test.<>c.<<ConnectTimeout_TimesOut_Throws>b__4_0>d.MoveNext()
12:38:02          --- End of stack trace from previous location where exception was thrown ---
12:38:02             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:38:02             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:38:02             at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
12:38:02             at System.Net.Http.Functional.Tests.LoopbackServer.<>c__DisplayClass0_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
12:38:02          --- End of stack trace from previous location where exception was thrown ---
12:38:02             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:38:02             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:38:02             at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
12:38:02             at System.Net.Http.Functional.Tests.LoopbackServer.<>c__DisplayClass2_0.<CreateServerAsync>b__0(Task t)
12:38:02             at System.Threading.Tasks.Task.Execute()
12:38:02          --- End of stack trace from previous location where exception was thrown ---
12:38:02             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:38:02             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:38:02             at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
12:38:02             at System.Net.Http.Functional.Tests.HttpClientHandler_Timeouts_Test.<ConnectTimeout_TimesOut_Throws>d__4.MoveNext()
12:38:02          --- End of stack trace from previous location where exception was thrown ---
12:38:02             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:38:02             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:38:02          --- End of stack trace from previous location where exception was thrown ---
12:38:02             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:38:02             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:38:02          --- End of stack trace from previous location where exception was thrown ---
12:38:02             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:38:02             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:38:02 Finished:    System.Net.Http.Functional.Tests
```

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by stephentoub** [comment]
@priya91, this failure is on every run? What's the output of "curl --version" on the relevant machine?

**Comment by Priya91** [comment]
> this failure is on every run?

Yes, happened on the last 2 consecutive runs..

This is the curl output
```
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
```

**Comment by stephentoub** [comment]
It looks like the wrong libcurl dev package is installed on whatever machine is building the corefx native nineties. We should be installing the one based on OpenSSL, not the one based on GnuTLS. I don't know if that's THE problem, but it is A problem.

cc: @bartonjs

**Comment by Priya91** [comment]
From one of the Ubuntu16.04 machines, 
```
sudo apt-get install libcurl4-openssl-dev
Reading package lists...
Building dependency tree...
Reading state information...
libcurl4-openssl-dev is already the newest version (7.47.0-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```
> We should be installing the one based on OpenSSL, not the one based on GnuTLS. I don't know if that's THE problem, but it is A problem.

The openssl headers are installed with dev package, not sure how to make packages use OpenSSL..

**Comment by joshfree** [comment]
cc: @terlochan

**Comment by stephentoub** [comment]
Are any other libcurl packages being installed as part of our configuration of the machine or its image?  I know there was previously a problem with another image where the libcurl4-gnutls-dev package was being installed unintentionally.  I don't see any libcurl dev package listed at http://releases.ubuntu.com/16.04/ubuntu-16.04-desktop-amd64.manifest, which leads me to believe it's something we've added in, but I could be wrong.

**Comment by bartonjs** [comment]
On my 15.10 machine:

```
jbarton@jsb-ubuntu2:~/git/openssl/openssl/apps$ dpkg -l *curl* | grep ^ii
ii  curl                       7.38.0-3ubuntu2.3 amd64        command line tool for transferring data with URL syntax
ii  libcurl3:amd64             7.38.0-3ubuntu2.3 amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  libcurl3-gnutls:amd64      7.38.0-3ubuntu2.3 amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
ii  libcurl4-openssl-dev:amd64 7.38.0-3ubuntu2.3 amd64        development files and documentation for libcurl (OpenSSL flavour)
ii  python3-pycurl             7.19.5-3ubuntu1   amd64        Python bindings to libcurl (Python 3)
```

And

```
jbarton@jsb-ubuntu2:~/git/openssl/openssl/apps$ ldd /usr/bin/curl | grep curl
        libcurl.so.4 => /usr/lib/x86_64-linux-gnu/libcurl.so.4 (0x00007f52f742c000)
jbarton@jsb-ubuntu2:~/git/openssl/openssl/apps$ dpkg-query -S /usr/lib/x86_64-linux-gnu/libcurl.so.4
libcurl3:amd64: /usr/lib/x86_64-linux-gnu/libcurl.so.4
```

And, the last diagnostic I can think of:

```
jbarton@jsb-ubuntu2:~/git/openssl/openssl/apps$ locate libcurl.so | xargs ls -al
lrwxrwxrwx 1 root    root        16 Jan 26 10:59 /usr/lib/x86_64-linux-gnu/libcurl.so -> libcurl.so.4.3.0
lrwxrwxrwx 1 root    root        12 Jan 26 10:59 /usr/lib/x86_64-linux-gnu/libcurl.so.3 -> libcurl.so.4
lrwxrwxrwx 1 root    root        16 Jan 26 10:59 /usr/lib/x86_64-linux-gnu/libcurl.so.4 -> libcurl.so.4.3.0
-rw-r--r-- 1 root    root    436640 Jan 26 10:59 /usr/lib/x86_64-linux-gnu/libcurl.so.4.3.0
```

**Comment by Priya91** [comment]
From 16.04 machine:

```
dotnet-bot@Azure0503095601:~$ dpkg -l *curl* | grep ^ii
ii  curl                       7.47.0-1ubuntu2 amd64        command line tool for transferring data with URL syntax
ii  libcurl3:amd64             7.47.0-1ubuntu2 amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  libcurl3-gnutls:amd64      7.47.0-1ubuntu2 amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
ii  libcurl4-openssl-dev:amd64 7.47.0-1ubuntu2 amd64        development files and documentation for libcurl (OpenSSL flavour)
ii  python3-pycurl             7.43.0-1ubuntu1 amd64        Python bindings to libcurl (Python 3)
```
And
```
dotnet-bot@Azure0503095601:~$ ldd /usr/bin/curl | grep curl
        libcurl-gnutls.so.4 => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007fc574b4b000)
dotnet-bot@Azure0503095601:~$ dpkg-query -S /usr/lib/x86_64-linux-gnu/libcurl.so.4
libcurl3:amd64: /usr/lib/x86_64-linux-gnu/libcurl.so.4
```

**Comment by stephentoub** [comment]
I'm fairly certain the issue here is that it's binding to the wrong libcurl implementation.  The box on which the native binaries are being built has both packages installed, and the log shows:
```
05:14:04 -- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.47.0") 
```
Further, the OpenSSL implementation supports non-blocking connects, which is what allows them to be timed out, and which is why using a different backend is causing this test to fail.  Seems like we just need to figure out how to get cmake to prefer the OpenSSL one if it's installed.

**Comment by stephentoub** [comment]
Actually, hmm, I take part of that back.  That libcurl.so on the build machine is a symlink to the right one...

**Comment by stephentoub** [comment]
Looks like I was entirely wrong.  The right libcurl is being used while running the tests...
