### ISSUE TITLE
PostSyncBlockingContentUsingChunkedEncoding_Success failed on Windows in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8389]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug/247/consoleText
```
System.Net.Http.Functional.Tests.PostScenarioTest.PostSyncBlockingContentUsingChunkedEncoding_Success(serverUri: https://corefx-net.cloudapp.net/Echo.ashx) [FAIL]
        System.Threading.Tasks.TaskCanceledException : A task was canceled.
        Stack Trace:
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
           D:\j\workspace\windows_nt_debug88592b53\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(850,0): at System.Net.Http.WinHttpHandler.<StartRequest>d__102.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
           D:\j\workspace\windows_nt_debug88592b53\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(392,0): at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           D:\j\workspace\windows_nt_debug88592b53\src\System.Net.Http\tests\FunctionalTests\PostScenarioTest.cs(171,0): at System.Net.Http.Functional.Tests.PostScenarioTest.<PostHelper>d__22.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           D:\j\workspace\windows_nt_debug88592b53\src\System.Net.Http\tests\FunctionalTests\PostScenarioTest.cs(85,0): at System.Net.Http.Functional.Tests.PostScenarioTest.<PostSyncBlockingContentUsingChunkedEncoding_Success>d__14.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/1141/

**Comment by davidsh** [comment]
This is probably due to timeouts due to network congestion accessing the Azure test server.

We need to change more of the tests to use Loopback server or possibly an alternate test server that would be in CI's system LAN network (to reduce latency, etc.).

**Comment by davidsh** [comment]
closing this for now since this is an external Azure issue that only happens occasionally
