### ISSUE TITLE
Several EnvelopedCms test failures on Windows 7 and Windows 8.1

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#8393]
**Windows 7**

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_win7_release/lastCompletedBuild/testReport/System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests/StateTests/PostDecrypt_Encode/

Stacktrace
MESSAGE:
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Cannot find the certificate and private key for decryption
+++++++++++++++++++
STACK TRACE:
at System.Security.Cryptography.Pkcs.EnvelopedCms.DecryptContent(RecipientInfoCollection recipientInfos, X509Certificate2Collection extraStore) at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.StateTests.PostDecrypt_Encode()

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_win7_release/lastCompletedBuild/testReport/System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests/EdgeCasesTests/ImportEdgeCaseSki/

Stacktrace
MESSAGE:
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Cannot find the certificate and private key for decryption
+++++++++++++++++++
STACK TRACE:
at System.Security.Cryptography.Pkcs.EnvelopedCms.DecryptContent(RecipientInfoCollection recipientInfos, X509Certificate2Collection extraStore) at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.EdgeCasesTests.ImportEdgeCaseSki()

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/lastCompletedBuild/testReport/System.Net.Security.Tests/CertificateValidationClientServer/CertificateValidationClientServer_EndToEnd_Ok_useClientSelectionCallback__False_/

System.Net.Security.Tests.CertificateValidationClientServer.CertificateValidationClientServer_EndToEnd_Ok(useClientSelectionCallback: False) (from (empty))

MESSAGE:
System.AggregateException : One or more errors occurred. (Assert.Equal() Failure\r\nExpected: RemoteCertificateChainErrors\r\nActual: RemoteCertificateNotAvailable)\r\n---- Assert.Equal() Failure\r\nExpected: RemoteCertificateChainErrors\r\nActual: RemoteCertificateNotAvailable
+++++++++++++++++++
STACK TRACE:
at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken) at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout) at System.Net.Security.Tests.CertificateValidationClientServer.<CertificateValidationClientServer_EndToEnd_Ok>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) ----- Inner Stack Trace ----- at System.Net.Security.Tests.CertificateValidationClientServer.ServerSideRemoteClientCertificateValidation(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) at System.Net.Security.SslStream.UserCertValidationCallbackWrapper(String hostName, X509Certificate2 certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback) at System.Net.Security.SslState.CompleteHandshake() at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.WriteCallback(IAsyncResult transportResult) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult) at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result) at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult) at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

**Windows 8.1**

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/lastCompletedBuild/testReport/System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests/DecryptTests/Decrypt_IssuerAndSerial/

Stacktrace
MESSAGE:
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Keyset does not exist
+++++++++++++++++++
STACK TRACE:
at System.Security.Cryptography.Pkcs.EnvelopedCms.DecryptContent(RecipientInfoCollection recipientInfos, X509Certificate2Collection extraStore) in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Security.Cryptography.Pkcs\src\System\Security\Cryptography\Pkcs\EnvelopedCms.cs:line 240 at System.Security.Cryptography.Pkcs.EnvelopedCms.Decrypt(X509Certificate2Collection extraStore) in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Security.Cryptography.Pkcs\src\System\Security\Cryptography\Pkcs\EnvelopedCms.cs:line 188 at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.DecryptTests.VerifySimpleDecrypt(Byte[] encodedMessage, CertLoader certLoader, ContentInfo expectedContent) in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Security.Cryptography.Pkcs\tests\EnvelopedCms\DecryptTests.cs:line 210 at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.DecryptTests.TestSimpleDecrypt_RoundTrip(CertLoader certLoader, ContentInfo contentInfo, String algorithmOidValue, SubjectIdentifierType type) in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Security.Cryptography.Pkcs\tests\EnvelopedCms\DecryptTests.cs:line 196 at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.DecryptTests.Decrypt_IssuerAndSerial() in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Security.Cryptography.Pkcs\tests\EnvelopedCms\DecryptTests.cs:line 30

**Comment by AtsushiKan** [comment]
Looks like same intermittent errors that have been plaguing the X509CertificateTests. I believe you were already planning on using your PFX-fixer tool to de-bag the PFX's so here's another test case for you.

**Comment by bartonjs** [comment]
Yep, certainly sounds like it.  I've got three PFX blobs that somehow are generating an invalid MAC on repack (gen_mac, set_mac, verify_mac fails), once that's done there'll be a PR in testdata, then one here.

**Comment by bartonjs** [comment]
(turns out, hard-coding `size_t passlen = 5;` is a good way to make non-5-character MACs poorly generate)

**Comment by joshfree** [comment]
Related https://github.com/dotnet/corefx/issues/2885
