### ISSUE TITLE
Unhandled exception from SslStream in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8472]
I'm not sure what test this is from, but it's from something in System.Net.Security.Tests
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_tst_prtest/1004/consoleText
```
Unhandled Exception: System.InvalidOperationException: This operation is only allowed using a successfully authenticated context.
   at System.Net.Security.SslState.CheckThrow(Boolean authSucessCheck)
   at System.Net.Security.SslState.get_SecureStream()
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.<>c.<BeginReadInternal>b__38_0(Object <arg>)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.Stream.EndRead(IAsyncResult asyncResult)
   at System.Net.Security.Tests.DummyTcpServer.OnReceive(IAsyncResult result)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
./RunTests.sh: line 198: 61827 Aborted                 ./corerun xunit.console.netcore.exe System.Net.Security.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
```

**Comment by davidsh** [comment]
cc: @CIPop 

I saw this fail today on Windows on my dev box.  If you run the System.Net.Security tests several times, it will fail once or twice with this error.  I don't remember which test but I'll try again to find it.

**Comment by davidsh** [comment]
Not sure which test because this failure blows up in a threadpool thread.  I suspect this is a test bug but we'll need to investigate to be sure.  Since I saw this on Windows, I will remove the X-Plat tag.

**Comment by stephentoub** [comment]
Actually, I have an inkling of what's going on here.  I believe my change to add Begin/EndRead/Write to the contract changed how some test code was binding, preferring to bind to instance methods instead of extension methods in the tests, thereby changing some code to use Read/Write asynchronously vs using Read/Write.  I'll see what I can do to fix it.

**Comment by stephentoub** [comment]
This will be fixed once we update to newer packages.

**Comment by ericstj** [comment]
CI just hit again: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_debug_tst_prtest/1050/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8

**Comment by stephentoub** [comment]
> CI just hit again

Yeah, I've seen it a few times today.  This will be fixed when we update to the next set of packages that includes https://github.com/dotnet/corefx/pull/8486.

**Comment by stephentoub** [comment]
Should be fixed by https://github.com/dotnet/corefx/pull/8620
