### ISSUE TITLE
FileSystemWatcher Test failure: FileSystemWatcher_InternalBufferSize

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8569]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/1309/consoleText
```
System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize(setToHigherCapacity: False) [FAIL]
        Did not observe an error event within 50ms and 3 attempts.
        Expected: True
        Actual:   False
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.IO.FileSystem.Watcher\tests\Utility\FileSystemWatcherTest.cs(253,0): at System.IO.Tests.FileSystemWatcherTest.ExpectError(FileSystemWatcher watcher, Action action, Action cleanup, Int32 attempts)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.IO.FileSystem.Watcher\tests\FileSystemWatcher.InternalBufferSize.cs(79,0): at System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize(Boolean setToHigherCapacity)
```

**Comment by ianhays** [comment]
Must be an issue with how we're calculating the buffer operation capacity.  This test shouldn't be prone to intermittent failure any other way.. I'll up the value to be safe.
