### ISSUE TITLE
System.Resources.Reader.Tests failing in Linux builds

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#8632]
```
System.Resources.ResourceWriterTests.ResourceReaderTests.ReadV1Resources [FAIL]
16:51:26       System.FormatException : Corrupt .resources file. The Invalid offset into name section is .:544765272
16:51:26       Stack Trace:
16:51:26 Finished running tests. End time=23:51:40. Return value was 0
16:51:26 Starting:    System.Reflection.TypeExtensions.Tests
16:51:26             at System.Resources.ResourceReader.GetNamePosition(Int32 index)
16:51:26             at System.Resources.ResourceReader.GetKeyForNameIndex(Int32 index)
16:51:26             at System.Resources.ResourceReader.ResourceEnumerator.get_Entry()
16:51:26             at System.Resources.ResourceReader.ResourceEnumerator.get_Current()
16:51:26             at System.Resources.ResourceWriterTests.ResourceReaderTests.ReadV1Resources()
16:51:26 Finished:    System.Resources.Reader.Tests
16:51:26 
16:51:26 === TEST EXECUTION SUMMARY ===
16:51:26    System.Resources.Reader.Tests  Total: 25, Errors: 0, Failed: 1, Skipped: 0, Time: 1.013s
```
Test log [here](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu16.04_debug_tst/202/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8)

**Comment by Priya91** [comment]
@KrzysztofCwalina Is this the same as the resources file error bug before?

**Comment by ellismg** [comment]
Looks like we raced, this is a dupe of #8633

**Comment by Priya91** [comment]
ok closing this.
