### ISSUE TITLE
SendToV4IPEndPointToV6Host_NotReceived failed in CI on OSX

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8636]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_release_prtest/1297/consoleText
```
System.Net.Sockets.Tests.DualMode.SendToV4IPEndPointToV6Host_NotReceived [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.TimeoutException)
        Actual:   typeof(System.Net.Sockets.SocketException): Connection refused
        Stack Trace:
              at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
              at System.Net.Sockets.Tests.DualMode.DualModeSendTo_IPEndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout)
```

**Comment by ericeil** [comment]
Looks like ECONNREFUSED is possible from `sendmsg` on BSD-based systems.  From http://www.unix.com/man-page/FreeBSD/2/sendmsg/:

```
     [ECONNREFUSED]	The socket received an ICMP destination unreachable message from the last
			message sent.  This typically means that the receiver is not listening on
			the remote port.
```

This is probably due to the retry loop in the test.

**Comment by ericeil** [comment]
Since this is a rare test bug, moving out of RTM.

**Comment by ericeil** [comment]
We hit this again:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/osx_release_prtest/24/testReport/junit/System.Net.Sockets.Tests/DualMode/SendToV4IPEndPointToV6Host_NotReceived/

Stacktrace

MESSAGE:
Assert.Throws() Failure\nExpected: typeof(System.TimeoutException)\nActual: typeof(System.Net.Sockets.SocketException): Connection refused
+++++++++++++++++++
STACK TRACE:
at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP) at System.Net.Sockets.Tests.DualMode.DualModeSendTo_IPEndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout)


Test failure in PR https://github.com/dotnet/corefx/pull/8863

**Comment by ellismg** [comment]
And again in #8972:

```
MESSAGE:
Assert.Throws() Failure\nExpected: typeof(System.TimeoutException)\nActual: typeof(System.Net.Sockets.SocketException): Connection refused
+++++++++++++++++++
STACK TRACE:
at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 3004 
at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 2942
at System.Net.Sockets.SocketTaskExtensions.<>c.<SendToAsync>b__12_0(ArraySegment`1 targetBuffer, SocketFlags flags, EndPoint endPoint, AsyncCallback callback, Object state) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/src/System/Net/Sockets/SocketTaskExtensions.cs:line 235
at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
at System.Threading.Tasks.TaskFactory`1.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
at System.Net.Sockets.SocketTaskExtensions.SendToAsync(Socket socket, ArraySegment`1 buffer, SocketFlags socketFlags, EndPoint remoteEndPoint) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/src/System/Net/Sockets/SocketTaskExtensions.cs:line 234
at System.Net.Sockets.SocketAPMExtensions.BeginSendTo(Socket socket, Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs:line 565
at System.Net.Sockets.Tests.DualMode.DualModeBeginSendTo_EndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 1234
at System.Net.Sockets.Tests.DualMode.<BeginSendToV4IPEndPointToV6Host_NotReceived>b__110_0() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 1200
```

 [Logs Here](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/1696/testReport/junit/System.Net.Sockets.Tests/DualMode/BeginSendToV4IPEndPointToV6Host_NotReceived/)

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/1702/

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/1703/consoleText
```
System.Net.Sockets.Tests.DualMode.BeginSendToV4IPEndPointToV6Host_NotReceived [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.TimeoutException)
        Actual:   typeof(System.Net.Sockets.SocketException): Connection refused
        Stack Trace:
  Starting:    System.Threading.Tasks.Extensions.Tests
  Using /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/packages/ as folder for resolving package dependencies.
  Executing in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/bin/tests/AnyOS.AnyCPU.Debug/System.Xml.RW.XmlWriter.Tests/netcoreapp1.0
  Executing in unpack directory, do not have to copy files
  Hard linking dependent files...
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(3004,0): at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(2942,0): at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/src/System/Net/Sockets/SocketTaskExtensions.cs(235,0): at System.Net.Sockets.SocketTaskExtensions.<>c.<SendToAsync>b__12_0(ArraySegment`1 targetBuffer, SocketFlags flags, EndPoint endPoint, AsyncCallback callback, Object state)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
              at System.Threading.Tasks.TaskFactory`1.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/src/System/Net/Sockets/SocketTaskExtensions.cs(234,0): at System.Net.Sockets.SocketTaskExtensions.SendToAsync(Socket socket, ArraySegment`1 buffer, SocketFlags socketFlags, EndPoint remoteEndPoint)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs(565,0): at System.Net.Sockets.SocketAPMExtensions.BeginSendTo(Socket socket, Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(1234,0): at System.Net.Sockets.Tests.DualMode.DualModeBeginSendTo_EndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(1200,0): at System.Net.Sockets.Tests.DualMode.<BeginSendToV4IPEndPointToV6Host_NotReceived>b__110_0()
     System.Net.Sockets.Tests.DualMode.SendToV4IPEndPointToV6Host_NotReceived [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.TimeoutException)
        Actual:   typeof(System.Net.Sockets.SocketException): Connection refused
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(1395,0): at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(1439,0): at System.Net.Sockets.Socket.SendTo(Byte[] buffer, EndPoint remoteEP)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(1142,0): at System.Net.Sockets.Tests.DualMode.DualModeSendTo_IPEndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(1108,0): at System.Net.Sockets.Tests.DualMode.<SendToV4IPEndPointToV6Host_NotReceived>b__101_0()
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/1707/

**Comment by jhendrixMSFT** [comment]
Another hit: https://github.com/dotnet/corefx/pull/8994

**Comment by stephentoub** [comment]
Again: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/1723/
