### ISSUE TITLE
LoadFromAssemblyName_ValidTrustedPlatformAssembly failing in all CentOS runs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8643]
I assume we're only seeing this on CentOS because we're pulling the latest CoreCLR artifacts on CentOS and not in the other PR legs.

e.g. http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_debug_tst_prtest/1247/consoleText
```
System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadFromAssemblyName_ValidTrustedPlatformAssembly [FAIL]
      System.IO.FileLoadException : Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
      Stack Trace:
Discovered:  System.Runtime.Serialization.Json.Tests
            at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
            at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
            at System.Runtime.Loader.Tests.CustomTPALoadContext.Load(AssemblyName assemblyName)
            at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
            at System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadFromAssemblyName_ValidTrustedPlatformAssembly()
```

**Comment by gkhanna79** [comment]
Reopening to port the change to release branch

**Comment by gkhanna79** [comment]
Fixed with https://github.com/dotnet/corefx/pull/9038 in release branch
