### ISSUE TITLE
Slave went offline (OSX Release Build and Test)

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#8671]
```
Slave went offline during the build
14:40:45 ERROR: Connection was broken: java.io.IOException: Connection aborted: org.jenkinsci.remoting.nio.NioChannelHub$MonoNioTransport@6cd7293e[name=dci-macpro-04]
14:40:45    at org.jenkinsci.remoting.nio.NioChannelHub$NioTransport.abort(NioChannelHub.java:208)
14:40:45    at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:628)
14:40:45    at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
14:40:45    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
14:40:45    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
14:40:45    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
14:40:45    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
14:40:45    at java.lang.Thread.run(Thread.java:745)
14:40:45 Caused by: java.io.IOException: Connection reset by peer
14:40:45    at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
14:40:45    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
14:40:45    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
14:40:45    at sun.nio.ch.IOUtil.read(IOUtil.java:197)
14:40:45    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:384)
14:40:45    at org.jenkinsci.remoting.nio.FifoBuffer$Pointer.receive(FifoBuffer.java:136)
14:40:45    at org.jenkinsci.remoting.nio.FifoBuffer.receive(FifoBuffer.java:306)
14:40:45    at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:561)
14:40:45    ... 6 more
```

Found in #8631: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_release_prtest/1337/consoleFull#-1250096032a6fc86e9-18e8-40d3-a876-f39e33df2c41

**Comment by joshfree** [comment]
@mmitche @Priya91

**Comment by karelz** [comment]
Not quite actionable now. If there are more repros, we can reopen.
