### ISSUE TITLE
System.Tests.StringTests.{Starts|Ends}With_NullInStrings failures on CentOS

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#8708]
```
18:23:43    System.Tests.StringTests.StartsWith_NullInStrings(comparison: CurrentCulture) [FAIL]
18:23:43       Assert.False() Failure
18:23:43       Expected: False
18:23:43       Actual:   True
18:23:43       Stack Trace:
18:23:43             at System.Tests.StringTests.StartsWith_NullInStrings(StringComparison comparison)
18:23:43    System.Tests.StringTests.StartsWith_NullInStrings(comparison: CurrentCultureIgnoreCase) [FAIL]
18:23:43       Assert.False() Failure
18:23:43       Expected: False
18:23:43       Actual:   True
18:23:43       Stack Trace:
18:23:43             at System.Tests.StringTests.StartsWith_NullInStrings(StringComparison comparison)
18:23:43    System.Tests.StringTests.EndsWith_NullInStrings(comparison: CurrentCulture) [FAIL]
18:23:43       Assert.False() Failure
18:23:43       Expected: False
18:23:43       Actual:   True
18:23:43       Stack Trace:
18:23:43             at System.Tests.StringTests.EndsWith_NullInStrings(StringComparison comparison)
18:23:43    System.Tests.StringTests.EndsWith_NullInStrings(comparison: CurrentCultureIgnoreCase) [FAIL]
18:23:43       Assert.False() Failure
18:23:43       Expected: False
18:23:43       Actual:   True
18:23:43       Stack Trace:
18:23:43             at System.Tests.StringTests.EndsWith_NullInStrings(StringComparison comparison)
18:23:43 Finished:    System.Runtime.Tests
18:23:43 
18:23:43 === TEST EXECUTION SUMMARY ===
18:23:43    System.Runtime.Tests  Total: 5781, Errors: 0, Failed: 4, Skipped: 0, Time: 3.193s
```

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_tst_prtest/1303/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8

**Comment by tarekgh** [comment]
@bartonjs I have installed Centos 7 and compiled and ran the corefx tests locally and I couldn't get to repro this issue. can you repro it? or at least can we get hold on the binaries that repro this? any help is appreciated here.

**Comment by bartonjs** [comment]
@tarekgh I've only seen it on the one run.

Looking at the commit history for that time I see https://github.com/dotnet/corefx/commit/a587b95f96f2eb44162623207a6b26d0a58e85ac, which is Matt turning off these particular tests because of https://github.com/dotnet/coreclr/issues/2051.

Given that the coreclr issue was opened in November I wonder how the tests were enabled.  Maybe someone accidentally fixed it, then accidentally broke it again?
