### ISSUE TITLE
JwtBearer validation failes on osx but works on windows

### ISSUE THREAD

**Issue by Tratcher** [dotnet/corefx#8712]
_From @hsorbo on May 20, 2016 14:16_

Been struggeling with exceptions porting from rc1 to rc2 on os x. On windows it seems to work, but failes with this on os x. Im using RS256.

Am i missing something?

```
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware[7]
      auth0 was not authenticated. Failure message: IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey , KeyId: RkUxNDU0QTg0RTNCRTNEQjk5ODg5MDBGRjIxQTJFQkM0NThBODgwQg
      '.
      Exceptions caught:
       'System.ArgumentNullException: Value cannot be null.
      Parameter name: SafeHandle cannot be null.
         at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
         at Interop.Crypto.RsaVerify(Int32 type, Byte[] m, Int32 m_len, Byte[] sigbuf, Int32 siglen, SafeRsaHandle rsa)
         at System.Security.Cryptography.RSAOpenSsl.VerifyHash(Byte[] hash, Byte[] signature, HashAlgorithmName hashAlgorithmName)
         at System.Security.Cryptography.RSAOpenSsl.VerifyHash(Byte[] hash, Byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
         at System.Security.Cryptography.RSA.VerifyData(Byte[] data, Int32 offset, Int32 count, Byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
         at System.Security.Cryptography.RSA.VerifyData(Byte[] data, Byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
         at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature)
         at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm)
         at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
```

The setup code is fairly trivial:
```
app.UseJwtBearerAuthentication(new JwtBearerOptions
            {
                AuthenticationScheme = "auth0",
                Audience = Configuration["Auth0:Audience"],
                Authority = Configuration["Auth0:Authority"],
                AutomaticAuthenticate = true,
                AutomaticChallenge = true,
            });
```

```
brew info openssl
openssl: stable 1.0.2h (bottled) [keg-only]
```

```
dotnet --version
1.0.0-preview1-002702`
```
```
uname -a
Darwin Macarena.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64`
```

_Copied from original issue: aspnet/Security#826_

**Comment by hsorbo** [comment]
```
'System.InvalidOperationException: ValueFactory attempted to access the Value property of this instance.
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Security.Cryptography.RSAOpenSsl.VerifyHash(Byte[] hash, Byte[] signature, HashAlgorithmName hashAlgorithmName)
   at System.Security.Cryptography.RSAOpenSsl.VerifyHash(Byte[] hash, Byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at System.Security.Cryptography.RSA.VerifyData(Byte[] data, Int32 offset, Int32 count, Byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at System.Security.Cryptography.RSA.VerifyData(Byte[] data, Byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
'.
```

Also seems to pop up, im not sure if they are related

**Comment by hsorbo** [comment]
It works fine with https://hub.docker.com/r/microsoft/dotnet/ 1.0.0-preview1-onbuild so it seems more like a darwin problem and not a posix problem

**Comment by bartonjs** [comment]
@hsorbo I don't suppose you have a static repro?  I'm not sure how to go about making use of any of the stuff from IdentityModel, so it'd help speed things up if I could jump straight into figuring out the failure.

**Comment by hsorbo** [comment]
@bartonjs Ill try to reduce it to a test or small sample app.

**Comment by hsorbo** [comment]
@bartonjs i have pinned it down to a integration test. Its a timing issue (as you can see I need to fire a few requests concurrently). Code here: https://github.com/hsorbo/corefx8712
I had to strip out the keys as they are private. If need be I can see if i can generate som sample keys, but it will take som time.

**Comment by hsorbo** [comment]
I stole some creds from here https://github.com/aspnet/Security/blob/dev/test/Microsoft.AspNetCore.Authentication.Test/JwtBearer/JwtBearerMiddlewareTests.cs

With the latest revision you should be able to get  System.ArgumentNullException in the console on mac.

The token is too old to work properly on any system, but at least you'll get different log for windows/mac

Hope this helps.

**Comment by bartonjs** [comment]
Okay... so I made a new project, copied in those two files... and... nothing happened.  What am I supposed to do to see the exception? :)

**Comment by hsorbo** [comment]
`dotnet restore && dotnet` test in the same folder as project.json. The exception should appear in the log-output og the test

**Comment by hsorbo** [comment]
`dotnet restore && dotnet test`

**Comment by bartonjs** [comment]
@hsorbo Thanks.  I've been able to consistently repro this on my mac.  My current suspicion is that there's a bug in the release build of Lazy\<T\> for RC2 on OSX.  This doesn't repro on RTM (which should be releasing on Monday), nor on Linux RC2 (which has the same System.Security.Cryptography.OpenSsl.dll).

I'm going to keep poking around a bit, but I think that this is a solved problem.  Definitely thanks for reporting it, and sorry that you're having to experience it.

**Comment by hsorbo** [comment]
Upgraded my test-repo and dotnet to RTM. The Lazy<T> issues seems to be gone on my machine but i still get the null-exception on my machine.
```
 'System.ArgumentNullException: SafeHandle cannot be null.
Parameter name: pHandle
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Crypto.RsaVerify(Int32 type, Byte[] m, Int32 m_len, Byte[] sigbuf, Int32 siglen, SafeRsaHandle rsa)
```

**Comment by bartonjs** [comment]
@JohnChen0 Saw an issue at RC2, it seemed to be gone in the road to RTM, but it's back with RTM... my leading suspicion is a crossgen issue; any tips on debugging it?

**Comment by JohnChen0** [comment]
Please set environment variable `export COMPlus_ReadyToRun=0` to disable loading Ready to Run images. Then run the test again. If the issue no longer repros, it's likely to be a CrossGen issue.

**Comment by bartonjs** [comment]
@JohnChen0 False alarm.  While it seems to only ever happen on a mac, it didn't repro under ReadyToRun=0.

Something in this test is using an RSA object across multiple threads.  Specifically, the first usage of the key is happening on 3 threads concurrently, and they're racing through the lazy initializer (which I made not lock because the callback is just "return precomputed").

MSDN describes the instance members as not thread-safe (using our default stance); so this is slightly a problem of unsupported re-use. But since RSACryptoServiceProvider's implementation is immune to this particular problem and it's a very easy fix 

@hsorbo Until a fix can be released, the workaround would be to not use the same client object for multiple parallel requests.

**Comment by hsorbo** [comment]
@bartonjs thanks!

**Comment by roterdam** [comment]
Can someone explain why COMPlus_ReadyToRun has anything to do with this? What is the possible bug in CrossGen here? I thought it just calls the Jit Compiler and nothing else.

**Comment by JohnChen0** [comment]
Setting `COMPlus_ReadyToRun=0` forces the runtime to ignore native code inside Ready-to-Run images, so that IL code in framework assemblies (except `System.Private.CoreLib`) are JIT compiled. If a bug repros both with or without `COMPlus_ReadyToRun=0`, then it is unlikely to be related to CrossGen. If a bug only repros without `COMPlus_ReadyToRun=0`, then there is a good chance that is related to CrossGen, since only CrossGen-generated code has problems. It is still not definitive, since there could be other factors such as timing in play.
