### ISSUE TITLE
failure in ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#8744]
Details in http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/1552/console  
on a [PR](https://github.com/dotnet/corefx/pull/8707) that could not possibly cause the issue
 System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success(serverProtocol: Tls11) [FAIL]
        System.ComponentModel.Win32Exception : The credentials supplied to the package were not recognized
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\Common\src\Interop\Windows\sspicli\SSPIWrapper.cs(232,0): at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SecureCredential scc)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SslStreamPal.Windows.cs(330,0): at System.Net.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential secureCredential)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SslStreamPal.Windows.cs(126,0): at System.Net.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureChannel.cs(769,0): at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureChannel.cs(901,0): at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureChannel.cs(805,0): at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs(749,0): at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs(955,0): at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs(1131,0): at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
           --- End of stack trace from previous location where exception was thrown ---
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs(742,0): at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs(710,0): at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
           --- End of stack trace from previous location where exception was thrown ---

**Comment by CIPop** [comment]
@danmosemsft do you know what OS SKU failed in this case? 
Were there changes in the machine type that runs the tests? How can I find out what OS SKU was used?

System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success(serverProtocol: Tls11) [FAIL]
15:03:08         System.ComponentModel.Win32Exception : The credentials supplied to the package were not recognized
15:03:08         Stack Trace:
15:03:08            D:\j\workspace\windows_nt_re---37265eab\src\Common\src\Interop\Windows\sspicli\SSPIWrapper.cs(232,0): at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SecureCredential scc)
15:03:08            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SslStreamPal.Windows.cs(330,0): at System.Net.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential secureCredential)
15:03:08            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SslStreamPal.Windows.cs(126,0): at System.Net.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
15:03:08            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureChannel.cs(769,0): at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
15:03:08            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureChannel.cs(901,0): at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
15:03:08            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureChannel.cs(805,0): at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
15:03:08            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs(749,0): at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
15:03:08            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs(955,0): at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
15:03:08            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs(1131,0): at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
15:03:08            --- End of stack trace from previous location where exception was thrown ---
15:03:08            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs(742,0): at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
15:03:08            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\SecureProtocols\SslState.cs(710,0): at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
15:03:08               at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
15:03:08            --- End of stack trace from previous location where exception was thrown ---
15:03:08               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
15:03:08               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:03:08            D:\j\workspace\windows_nt_re---37265eab\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(19,0): at System.Threading.Tasks.TaskTimeoutExtensions.<TimeoutAfter>d__0.MoveNext()
15:03:08            --- End of stack trace from previous location where exception was thrown ---
15:03:08               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
15:03:08               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:03:08            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\ServerAsyncAuthenticateTest.cs(168,0): at System.Net.Security.Tests.ServerAsyncAuthenticateTest.<ServerAsyncSslHelper>d__11.MoveNext()
15:03:08            --- End of stack trace from previous location where exception was thrown ---
15:03:08               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
15:03:08               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:03:08            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\ServerAsyncAuthenticateTest.cs(92,0): at System.Net.Security.Tests.ServerAsyncAuthenticateTest.<ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success>d__9.MoveNext()
15:03:08            --- End of stack trace from previous location where exception was thrown ---
15:03:08               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
15:03:08               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:03:08            --- End of stack trace from previous location where exception was thrown ---
15:03:08               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
15:03:08               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:03:08            --- End of stack trace from previous location where exception was thrown ---
15:03:08               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
15:03:08               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:03:11   Finished:    System.Net.Security.Tests
15:03:11   
15:03:11   === TEST EXECUTION SUMMARY ===
15:03:11 D:\j\workspace\windows_nt_re---37265eab\Tools\tests.targets(202,5): warning :    System.Net.Security.Tests  Total: 102, Errors: 0, Failed: 1, Skipped: 0, Time: 63.065s [D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\System.Net.Security.Tests.csproj]
15:03:11   Finished running tests.  End time=15:03:35.26, Exit code = 1
```

**Comment by danmosemsft** [comment]
I don't - I just triggered the bot to run the tests on my PR in the normal way. Perhaps someone familiar with the infrastructure can help.
________________________________

**Comment by danmosemsft** [comment]
@CIPop could you please take a look or else disable this test?

It failed in several OS (Ubuntu 1604 debug, windows 10, windows 8) on last night's test build.
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161101.01/workItem/System.Net.Security.Tests

Example log
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161101.01/workItem/System.Net.Security.Tests/details/753fec58-dd21-4fb7-aacf-b76455205f63

```
2016-11-01 01:50:34,812: INFO: proc(65): run_and_log_output: Output: Starting:    System.Net.Security.Tests
2016-11-01 01:50:35,329: INFO: proc(65): run_and_log_output: Output:    System.Net.Security.Tests.NegotiateStreamKerberosTest.NegotiateStream_AuthenticationRemote_Fails [SKIP]
2016-11-01 01:50:35,329: INFO: proc(65): run_and_log_output: Output:       Condition(s) not met: \"IsServerAndDomainAvailable\"
2016-11-01 01:50:35,331: INFO: proc(65): run_and_log_output: Output:    System.Net.Security.Tests.NegotiateStreamKerberosTest.NegotiateStream_AuthenticationRemote_Success [SKIP]
2016-11-01 01:50:35,331: INFO: proc(65): run_and_log_output: Output:       Condition(s) not met: \"IsServerAndDomainAvailable\"
2016-11-01 01:50:36,595: INFO: proc(65): run_and_log_output: Output:    System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success(serverProtocol: Tls11) [FAIL]
2016-11-01 01:50:36,596: INFO: proc(65): run_and_log_output: Output:       System.ComponentModel.Win32Exception : The credentials supplied to the package were not recognized
2016-11-01 01:50:36,601: INFO: proc(65): run_and_log_output: Output:       Stack Trace:
2016-11-01 01:50:36,693: INFO: proc(65): run_and_log_output: Output:             at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)
2016-11-01 01:50:36,693: INFO: proc(65): run_and_log_output: Output:             at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential)
2016-11-01 01:50:36,694: INFO: proc(65): run_and_log_output: Output:             at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
2016-11-01 01:50:36,694: INFO: proc(65): run_and_log_output: Output:             at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
2016-11-01 01:50:36,694: INFO: proc(65): run_and_log_output: Output:             at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
2016-11-01 01:50:36,694: INFO: proc(65): run_and_log_output: Output:             at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
2016-11-01 01:50:36,694: INFO: proc(65): run_and_log_output: Output:             at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
2016-11-01 01:50:36,694: INFO: proc(65): run_and_log_output: Output:             at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
2016-11-01 01:50:36,694: INFO: proc(65): run_and_log_output: Output:             at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
2016-11-01 01:50:36,694: INFO: proc(65): run_and_log_output: Output:             at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
2016-11-01 01:50:36,694: INFO: proc(65): run_and_log_output: Output:             at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
2016-11-01 01:50:36,694: INFO: proc(65): run_and_log_output: Output:             at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
2016-11-01 01:50:36,696: INFO: proc(65): run_and_log_output: Output:             at System.Net.Security.SslStream.BeginAuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
2016-11-01 01:50:36,696: INFO: proc(65): run_and_log_output: Output:             at System.Net.Security.SslStream.<>c__DisplayClass29_0.<AuthenticateAsServerAsync>b__0(AsyncCallback callback, Object state)
```

**Comment by stephentoub** [comment]
Related failure here on Windows 7:
http://dotnet-ci1.westus.cloudapp.azure.com/job/dotnet_corefx/job/master/job/outerloop_win7_release/1/consoleText
```
System.ComponentModel.Win32Exception : The credentials supplied to the package were not recognized
        Stack Trace:
  Finished running tests.  End time=11:03:31.84, Exit code = 0
              at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)
              at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential)
              at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
              at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
              at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
              at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
              at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
              at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
              at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
           --- End of stack trace from previous location where exception was thrown ---
  Using D:\j\workspace\outerloop_win---75d58f69\packages\ as folder for resolving package dependencies.
  Executing in D:\j\workspace\outerloop_win---75d58f69\bin\tests\AnyOS.AnyCPU.Release\System.Linq.Performance.Tests\default.netcoreapp1.1\ 
  Hard linking dependent files... 
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           D:\j\workspace\outerloop_win---75d58f69\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(19,0): at System.Threading.Tasks.TaskTimeoutExtensions.<TimeoutAfter>d__0.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           D:\j\workspace\outerloop_win---75d58f69\src\System.Net.Security\tests\FunctionalTests\ServerAsyncAuthenticateTest.cs(176,0): at System.Net.Security.Tests.ServerAsyncAuthenticateTest.<ServerAsyncSslHelper>d__11.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           D:\j\workspace\outerloop_win---75d58f69\src\System.Net.Security\tests\FunctionalTests\ServerAsyncAuthenticateTest.cs(43,0): at System.Net.Security.Tests.ServerAsyncAuthenticateTest.<ServerAsyncAuthenticate_EachSupportedProtocol_Success>d__5.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by jiangzeng** [comment]
Latest failure on windows 7 in build 20161123.03
Test: System.Net.Security.Tests.ServerAsyncAuthenticateTest/ServerAsyncAuthenticate_EachSupportedProtocol_Success

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161123.03/workItem/System.Net.Security.Tests/analysis/xunit/System.Net.Security.Tests.ServerAsyncAuthenticateTest~2FServerAsyncAuthenticate_EachSupportedProtocol_Success(protocol:%20Tls11)

**Comment by Jiayili1** [comment]
Same failure on windows 8.1 in latest build 20161227.01, 
Test:
System.Net.Security.Tests.SslStreamNetworkStreamTest/SslStream_SendReceiveOverNetworkStream_Ok 
 
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161227.01/workItem/System.Net.Security.Tests/analysis/xunit/System.Net.Security.Tests.SslStreamNetworkStreamTest~2FSslStream_SendReceiveOverNetworkStream_Ok

**Comment by danmosemsft** [comment]
@davidsh looks like more to disable as you did with the one at the top.

**Comment by CIPop** [comment]
@danmosemsft we're aware of many System.Net intermittent issues. We've decided to track all of these with #14519.

**Comment by danmosemsft** [comment]
@CIPop fair enough. Many of the other CI/test run issues look like System.Net intermittent failures. Do you want to go through those and dupe them out?

Maybe 10 or so of these: https://github.com/dotnet/corefx/labels/test-run-core

**Comment by CIPop** [comment]
@danmosemsft I'll leave that decision/work to @karelz and @steveharter who are actively triaging and investigating the test failures.

**Comment by ianhays** [comment]
Tracking this failure in https://github.com/dotnet/corefx/issues/16516. Please comment there with any failure reports instead of re-opening this issue.
