### ISSUE TITLE
SendToAsyncV4IPEndPointToDualHost_Success timeout on OSX in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8877]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/1605/consoleText
```
System.Net.Sockets.Tests.DualMode.SendToAsyncV4IPEndPointToDualHost_Success [FAIL]
        System.TimeoutException : The operation has timed out.
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest@2/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(1372,0): at System.Net.Sockets.Tests.DualMode.DualModeSendToAsync_IPEndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest@2/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(1327,0): at System.Net.Sockets.Tests.DualMode.SendToAsyncV4IPEndPointToDualHost_Success()
  ```

**Comment by ericeil** [comment]
Looks like this has only failed once in the last two months; this was probably just the machine running slow at the time.
