### ISSUE TITLE
Parsing /etc/resolv.conf throws exception when iterating network interfaces

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#8890]
The default generated /etc/resolve.conf for a docker container causes enumeration of network interfaces to throw because the file does not end with a newline.

```
hexdump -C /etc/resolv.conf
00000000  0a 6e 61 6d 65 73 65 72  76 65 72 20 38 2e 38 2e  |.nameserver 8.8.|
00000010  38 2e 38 0a 6e 61 6d 65  73 65 72 76 65 72 20 38  |8.8.nameserver 8|
00000020  2e 38 2e 34 2e 34                                 |.8.4.4|
00000026
```

stacktrace

```
Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.String.LastIndexOf(Char value, Int32 startIndex, Int32 count)
   at System.IO.RowConfigReader.TryGetNextValue(String key, String& value)
   at System.Net.NetworkInformation.StringParsingHelpers.ParseDnsAddressesFromResolvConfFile(String filePath)
   at System.Net.NetworkInformation.UnixIPInterfaceProperties.GetDnsAddresses()
   at System.Net.NetworkInformation.UnixIPInterfaceProperties..ctor(UnixNetworkInterface uni)
   at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
   at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__2(String name, LinkLayerAddressInfo* llAddr)
   at Interop.Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback ipv4Found, IPv6AddressDiscoveredCallback ipv6Found, LinkLayerAddressDiscoveredCallback linkLayerFound)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()

```
/cc @mellinoe

**Comment by mellinoe** [comment]
Thanks for the bug report, @tmds. I should have a fix for this shortly. We're simply not handling that case right now:

https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/Common/src/System/IO/RowConfigReader.cs#L85

**Comment by mellinoe** [comment]
Should be fixed by https://github.com/dotnet/corefx/pull/8891

**Comment by tmds** [comment]
A bit lower in the code there is also the case where no space/tab is found. It looks like the whole file is returned then.
Instead it should ignore the line and try to parse the next.

**Comment by tmds** [comment]
Looking at the code a bit more, it looks like the key is matched anywhere in the file. If the line is commented out or the key is part of a larger string it will also be matched.

The resolv.conf format is well described in [man resolv.conf](http://man7.org/linux/man-pages/man5/resolv.conf.5.html).

**Comment by tmds** [comment]
@mellinoe I am happy the code no longer throws, let me know what you still want to tackle as part of this issue.

**Comment by mellinoe** [comment]
I fixed the other issues, except for this one:

> A bit lower in the code there is also the case where no space/tab is found. It looks like the whole file is returned then.
Instead it should ignore the line and try to parse the next.

Are you referring to a situation like this?

````
key1
key1
key1 value1
````

I'm inclined to just bail out on strings like that. They don't seem to be valid resolv.conf files based on the description. The revised version of the code will just return `false` from TryGetNextValue.

**Comment by mellinoe** [comment]
Another thing I noticed: Some examples for `/etc/resolv.conf` contain comments at the end of lines, after a key-value pair, like this:

````
nameserver 77.88.8.8              # Preferred IPv4 DNS
````

 I don't think this is allowed according to the man page, so I'm not handling that right now.

**Comment by tmds** [comment]
> I'm inclined to just bail out on strings like that. They don't seem to be valid resolv.conf files based on the description. The revised version of the code will just return false from TryGetNextValue.

The code calling TryGetNextValue will call it until it returns false. If it returns false on an invalid row, valid rows below it will no longer be read. Since this is a reader for row configs each row should get a fair chance.
