### ISSUE TITLE
DataContractSerializer exception when deserializing exceptions with async stack traces

### ISSUE THREAD

**Issue by aelij** [dotnet/corefx#8968]
This used to work on RC1, and also works when targeting `net46`.

Repro (only happens if `Run` is an `async` method):

```csharp
using System;
using System.IO;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace ConsoleApp5
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Run().GetAwaiter().GetResult();
        }

        public static async Task Run()
        {
            try
            {
                throw new Exception("Foo");
            }
            catch (Exception e)
            {
                SerializeAndDeserializeException(e);
            }
        }

        private static void SerializeAndDeserializeException(Exception e)
        {
            using (var stream = new MemoryStream())
            {
                var serializer = new DataContractSerializer(e.GetType());
                serializer.WriteObject(stream, e);
                Console.WriteLine("Serialized!");
                stream.Position = 0;
                var ex = (Exception)serializer.ReadObject(stream);
                Console.WriteLine("Deserialized! Message = " + ex.Message);
            }
        }
    }
}
```

`ReadObject` throws the following exception:

```
Unhandled Exception: System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type System.Exception. End element '_stackTraceString' from namespace 'http://schemas.datacontract.org/2004/07/System' expected. Found element 'Run' from namespace 'http://schemas.datacontract.org/2004/07/System'. Line 1, position 259. ---> System.Xml.XmlException: End element '_stackTraceString' from namespace 'http://schemas.datacontract.org/2004/07/System' expected. Found element 'Run' from namespace 'http://schemas.datacontract.org/2004/07/System'. Line 1, position 259.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, String res, String arg1, String arg2, String arg3)
   at System.Xml.XmlBaseReader.ReadEndElement()
   at System.Xml.XmlBaseReader.ReadElementContentAsString()
   at ReadExceptionFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] )
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.ExceptionDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlDictionaryReader reader)
   at ConsoleApp5.Program.SerializeAndDeserializeException(Exception e)
   at ConsoleApp5.Program.<Run>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApp5.Program.Main(String[] args)
```

**Comment by joshfree** [comment]
@zhenlan

**Comment by khdang** [comment]
So far I haven't been able to confirm that this work in RC1.
@aelij Could you share the package versions that works for you?

**Comment by aelij** [comment]
@khdang Check out this project.json
https://github.com/aelij/AsyncFriendlyStackTrace/blob/master/src/AsyncFriendlyStackTrace.Test/project.json

**Comment by khdang** [comment]
For NetCore, the version of System.Runtime.Serialization.Xml you mentioned is 4.1.0-beta-23516.

I've tried with some earlier and later versions including 4.0.10, 4.1.0-beta-23419, 4.0.11 and all of them have this issue. So if this works in RC1 it could be due to issue other than serialization.

**Comment by aelij** [comment]
That's weird, because the project I linked to definitely worked. Maybe I'm wrong and it was a beta rather than RC1.

Even so, is there no chance of fixing this? It's definitely a regression from the desktop framework.

It looks like that it's ignoring ISerializable during deserialization, but using it during serialization. Does that make sense?

**Comment by khdang** [comment]
@zhenlan and I verified that this doesn't work on RC1 with serialization package version 4.1.0-beta-23516. On NetCore ISerializable is not in the contract so we handled exception a bit different compared to Desktop. That may be the reason of this issue.
