### ISSUE TITLE
TestUserCredentialsPropertiesOnWindows failed on Win10 in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8984]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_win10_release/51/consoleText
```
    System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows [FAIL]
        System.ComponentModel.Win32Exception : The user name or password is incorrect
        Stack Trace:
           d:\j\workspace\outerloop_win---6835b088\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Windows.cs(619,0): at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
           d:\j\workspace\outerloop_win---6835b088\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(375,0): at System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows()
```

**Comment by Priya91** [comment]
This hasn't failed again, and not able to repro. Please reopen if issue repros again.

**Comment by stephentoub** [comment]
Failed here (albeit with a different assert):
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/72/consoleText
```
System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows [FAIL]
        Assert+WrapperXunitException : File path: D:\j\workspace\outerloop_win---bf7c4efa\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs. Line: 396
        ---- Assert.Equal() Failure
        Expected: 0
        Actual:   2221
        Stack Trace:
           D:\j\workspace\outerloop_win---bf7c4efa\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(583,0): at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
           D:\j\workspace\outerloop_win---bf7c4efa\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(172,0): at Assert.Equal[T](T expected, T actual, String path, Int32 line)
           D:\j\workspace\outerloop_win---bf7c4efa\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(396,0): at System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows()
           ----- Inner Stack Trace -----
           D:\j\workspace\outerloop_win---bf7c4efa\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(171,0): at Assert.Equal[T](T expected, T actual, String path, Int32 line)
```

**Comment by Priya91** [comment]
This is failing on netuserdel with 2221, which is code for user not found. Investigating..
