### ISSUE TITLE
SendAsync_ExpectedDiagnosticSourceLogging tests failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#9027]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/1863/consoleText
```
System.Net.Http.Functional.Tests.HttpClientTest.SendAsync_ExpectedDiagnosticSourceNoLogging [FAIL]
        Request was logged while logging disabled.
        Expected: False
        Actual:   True
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http\tests\FunctionalTests\HttpClientTest.cs(476,0): at System.Net.Http.Functional.Tests.HttpClientTest.SendAsync_ExpectedDiagnosticSourceNoLogging()
```
and
```
System.Net.Http.Functional.Tests.HttpClientTest.SendAsync_ExpectedDiagnosticSourceLogging [FAIL]
        System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)
  Finished:    System.Resources.Writer.Tests
        ---- System.Net.Http.HttpRequestException : An error occurred while sending the request.
        -------- System.Net.Http.WinHttpException : The operation has been canceled
        Stack Trace:
              at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http\tests\FunctionalTests\HttpClientTest.cs(435,0): at System.Net.Http.Functional.Tests.HttpClientTest.SendAsync_ExpectedDiagnosticSourceLogging()
           ----- Inner Stack Trace -----
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(381,0): at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
           ----- Inner Stack Trace -----
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(838,0): at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
```

**Comment by davidsh** [comment]
>        ---- System.Net.Http.HttpRequestException : An error occurred while sending the request.
        -------- System.Net.Http.WinHttpException : The operation has been canceled

This is probably due to a timeout trying to access the Azure test server endpoint.

**Comment by davidsh** [comment]
closing this for now since this is an external Azure issue that only happens occasionally

**Comment by CIPop** [comment]
Related to #19701
