### ISSUE TITLE
[release/1.0.0] OS X ProcessTests.TestPriorityClassUnix permission denied

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#9167]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_osx_debug/lastCompletedBuild/testReport/System.Diagnostics.Tests/ProcessTests/TestPriorityClassUnix/

System.Diagnostics.Tests.ProcessTests.TestPriorityClassUnix (from (empty))

MESSAGE:
System.ComponentModel.Win32Exception : Permission denied
+++++++++++++++++++
STACK TRACE:
at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value) at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value) at System.Diagnostics.Tests.ProcessTests.TestPriorityClassUnix()

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_osx_debug/lastCompletedBuild/testReport/System.Diagnostics.Tests/ProcessTests/TestBasePriorityOnUnix/

System.Diagnostics.Tests.ProcessTests.TestBasePriorityOnUnix (from (empty))

MESSAGE:
System.ComponentModel.Win32Exception : Permission denied
+++++++++++++++++++
STACK TRACE:
at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value) at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value) at System.Diagnostics.Tests.ProcessTests.SetAndCheckBasePriority(ProcessPriorityClass exPriorityClass, Int32 priority) at System.Diagnostics.Tests.ProcessTests.TestBasePriorityOnUnix()

**Comment by stephentoub** [comment]
This is a dup of https://github.com/dotnet/corefx/issues/9068.  These tests require elevated privileges to run, and they'r enot being run as such.

**Comment by joshfree** [comment]
thanks @stephentoub
