### ISSUE TITLE
Socket.Connect fails for connection-less and single IP-address remote endpoints on Unix

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#9189]
Ref: #9137, #4968 

[System.Net.Sockets.Tests.UdpClientTest.Connect_Success (from (empty))](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/1814/testReport/junit/System.Net.Sockets.Tests/UdpClientTest/Connect_Success/)

```
Stacktrace

MESSAGE:
System.PlatformNotSupportedException : Sockets on this platform are invalid for use after a failed connection attempt, and as a result do not support attempts to connect to multiple endpoints.
+++++++++++++++++++
STACK TRACE:
at System.Net.Sockets.Socket.ThrowIfNotSupportsMultipleConnectAttempts() at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port) at System.Net.Sockets.Socket.Connect(String host, Int32 port) at System.Net.Sockets.Tests.UdpClientTest.Connect_Success()
```

[System.Net.Sockets.Tests.UdpClientTest.ConnectAsync_Success (from (empty))](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/1814/testReport/junit/System.Net.Sockets.Tests/UdpClientTest/ConnectAsync_Success/)

```
Stacktrace

MESSAGE:
System.PlatformNotSupportedException : Sockets on this platform are invalid for use after a failed connection attempt, and as a result do not support attempts to connect to multiple endpoints.
+++++++++++++++++++
STACK TRACE:
at System.Net.Sockets.Socket.ThrowIfNotSupportsMultipleConnectAttempts() at System.Net.Sockets.Socket.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state) at System.Net.Sockets.SocketTaskExtensions.<>c.<ConnectAsync>b__5_0(String targetHost, Int32 targetPort, AsyncCallback callback, Object state) at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions) at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state) at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, String host, Int32 port) at System.Net.Sockets.Tests.UdpClientTest.<ConnectAsync_Success>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by CIPop** [comment]
Same errors within the SocketPerformance tests for Unix:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu14.04_debug_prtest/14/

System.Net.Sockets.Performance.Tests.SocketPerformanceAsyncTests.SocketPerformance_SingleSocketClientAsync_LocalHostServerAsync (from (empty))

```
Failing for the past 1 build (Since Failed#14 )
Took 0.12 sec.
Stacktrace

MESSAGE:
System.AggregateException : One or more errors occurred. (Sockets on this platform are invalid for use after a failed connection attempt, and as a result do not support attempts to connect to multiple endpoints.)\n---- System.PlatformNotSupportedException : Sockets on this platform are invalid for use after a failed connection attempt, and as a result do not support attempts to connect to multiple endpoints.
+++++++++++++++++++
STACK TRACE:
at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure) at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException) at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally) at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body) at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.RunClient(SocketImplementationType testType, String server, Int32 port, Int32 iterations, Int32 bufferSize, Int32 socketInstances) at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.ClientServerTest(Int32 port, SocketImplementationType serverType, SocketImplementationType clientType, Int32 iterations, Int32 bufferSize, Int32 socketInstances, Int64 expectedMilliseconds) at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.ClientServerTest(SocketImplementationType serverType, SocketImplementationType clientType, Int32 iterations, Int32 bufferSize, Int32 socketInstances, Int64 expectedMilliseconds) at System.Net.Sockets.Performance.Tests.SocketPerformanceAsyncTests.SocketPerformance_SingleSocketClientAsync_LocalHostServerAsync() ----- Inner Stack Trace ----- at System.Net.Sockets.Socket.ThrowIfNotSupportsMultipleConnectAttempts() at System.Net.Sockets.Socket.ConnectAsync(SocketAsyncEventArgs e) at System.Net.Sockets.Performance.Tests.SocketTestClientAsync.Connect(Action`1 onConnectCallback) at System.Net.Sockets.Performance.Tests.SocketTestClient.RunTest() at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.<>c__DisplayClass5_0.<RunClient>b__0(Int32 i) at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

System.Net.Sockets.Performance.Tests.SocketPerformanceAsyncTests.SocketPerformance_MultipleSocketClientAsync_LocalHostServerAsync (from (empty))

```
Failing for the past 1 build (Since Failed#14 )
Took 3 ms.
Stacktrace

MESSAGE:
System.AggregateException : One or more errors occurred. (Sockets on this platform are invalid for use after a failed connection attempt, and as a result do not support attempts to connect to multiple endpoints.) (Sockets on this platform are invalid for use after a failed connection attempt, and as a result do not support attempts to connect to multiple endpoints.) (Sockets on this platform are invalid for use after a failed connection attempt, and as a result do not support attempts to connect to multiple endpoints.)\n---- System.PlatformNotSupportedException : Sockets on this platform are invalid for use after a failed connection attempt, and as a result do not support attempts to connect to multiple endpoints.\n---- System.PlatformNotSupportedException : Sockets on this platform are invalid for use after a failed connection attempt, and as a result do not support attempts to connect to multiple endpoints.\n---- System.PlatformNotSupportedException : Sockets on this platform are invalid for use after a failed connection attempt, and as a result do not support attempts to connect to multiple endpoints.
+++++++++++++++++++
STACK TRACE:
at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure) at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException) at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally) at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body) at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.RunClient(SocketImplementationType testType, String server, Int32 port, Int32 iterations, Int32 bufferSize, Int32 socketInstances) at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.ClientServerTest(Int32 port, SocketImplementationType serverType, SocketImplementationType clientType, Int32 iterations, Int32 bufferSize, Int32 socketInstances, Int64 expectedMilliseconds) at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.ClientServerTest(SocketImplementationType serverType, SocketImplementationType clientType, Int32 iterations, Int32 bufferSize, Int32 socketInstances, Int64 expectedMilliseconds) at System.Net.Sockets.Performance.Tests.SocketPerformanceAsyncTests.SocketPerformance_MultipleSocketClientAsync_LocalHostServerAsync() ----- Inner Stack Trace #1 (System.PlatformNotSupportedException) ----- at System.Net.Sockets.Socket.ThrowIfNotSupportsMultipleConnectAttempts() at System.Net.Sockets.Socket.ConnectAsync(SocketAsyncEventArgs e) at System.Net.Sockets.Performance.Tests.SocketTestClientAsync.Connect(Action`1 onConnectCallback) at System.Net.Sockets.Performance.Tests.SocketTestClient.RunTest() at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.<>c__DisplayClass5_0.<RunClient>b__0(Int32 i) at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) at System.Threading.Tasks.TaskReplicator.Replica.Execute() ----- Inner Stack Trace #2 (System.PlatformNotSupportedException) ----- at System.Net.Sockets.Socket.ThrowIfNotSupportsMultipleConnectAttempts() at System.Net.Sockets.Socket.ConnectAsync(SocketAsyncEventArgs e) at System.Net.Sockets.Performance.Tests.SocketTestClientAsync.Connect(Action`1 onConnectCallback) at System.Net.Sockets.Performance.Tests.SocketTestClient.RunTest() at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.<>c__DisplayClass5_0.<RunClient>b__0(Int32 i) at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) at System.Threading.Tasks.TaskReplicator.Replica.Execute() ----- Inner Stack Trace #3 (System.PlatformNotSupportedException) ----- at System.Net.Sockets.Socket.ThrowIfNotSupportsMultipleConnectAttempts() at System.Net.Sockets.Socket.ConnectAsync(SocketAsyncEventArgs e) at System.Net.Sockets.Performance.Tests.SocketTestClientAsync.Connect(Action`1 onConnectCallback) at System.Net.Sockets.Performance.Tests.SocketTestClient.RunTest() at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.<>c__DisplayClass5_0.<RunClient>b__0(Int32 i) at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

Also on OSX:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_osx_debug_prtest/3/
