### ISSUE TITLE
"Expected !isStopped" assert in sockets on Fedora

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#9320]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_fedora23_debug_prtest/1/consoleText
```
Expected !IsStopped
  
     at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
     at System.Environment.get_StackTrace()
     at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
     at System.Diagnostics.Debug.Assert(Boolean condition, String message)
     at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.Enqueue(TOperation operation)
     at System.Net.Sockets.SocketAsyncContext.TryBeginOperation[TOperation](OperationQueue`1& queue, TOperation operation, SocketEvents events, Boolean maintainOrder, Boolean& isStopped)
     at System.Net.Sockets.SocketAsyncContext.ReceiveFromAsync(Byte[] buffer, Int32 offset, Int32 count, SocketFlags flags, Byte[] socketAddress, Int32 socketAddressLen, Action`5 callback)
     at System.Net.Sockets.SocketAsyncContext.ReceiveAsync(Byte[] buffer, Int32 offset, Int32 count, SocketFlags flags, Action`5 callback)
     at System.Net.Sockets.SocketPal.ReceiveAsync(SafeCloseSocket handle, Byte[] buffer, Int32 offset, Int32 count, SocketFlags socketFlags, OverlappedAsyncResult asyncResult)
     at System.Net.Sockets.Socket.DoBeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, OverlappedAsyncResult asyncResult)
     at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
     at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
     at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
     at System.Net.Sockets.NetworkStream.<>c.<ReadAsync>b__58_0(Byte[] bufferArg, Int32 offsetArg, Int32 sizeArg, AsyncCallback callback, Object state)
     at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
     at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3,TResult](Func`6 beginMethod, Func`2 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
     at System.Net.Sockets.NetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 size, CancellationToken cancellationToken)
     at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
     at System.IO.StreamApmExtensions.BeginRead(Stream stream, Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
     at System.Net.FixedSizeReader.StartReading()
     at System.Net.FixedSizeReader.AsyncReadPacket(AsyncProtocolRequest request)
     at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
     at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
     at System.Net.Security.SslState.WriteCallback(IAsyncResult transportResult)
     at System.Threading.Tasks.TaskToApm.<>c__DisplayClass3_0.<InvokeCallbackWhenTaskCompletes>b__0()
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
     at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
     at System.Net.ContextAwareResult.CompleteCallback()
     at System.Net.ContextAwareResult.<>c.<Complete>b__17_0(Object s)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Net.ContextAwareResult.Complete(IntPtr userToken)
     at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
     at System.Net.LazyAsyncResult.InvokeCallback(Object result)
     at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError errorCode)
     at System.Net.Sockets.OverlappedAsyncResult.CompletionCallback(Int32 numBytes, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError errorCode)
     at System.Net.Sockets.SocketAsyncContext.<>c.<SendToAsync>b__46_0(Object args)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
```

**Comment by joshfree** [comment]
Moving to 1.1.  @ericeil please investigate the assert

**Comment by ericeil** [comment]
This looks to have only happened once, and unfortunately there's not enough info here for me to find the problem.  I've tried running the tests in a loop, to no avail, and code inspection hasn't panned out either.  I'll look into whether we can get better stress testing of this code, but for now there's not much I can do here.
