### ISSUE TITLE
[release/1.0.0] Many networking tests fail with ---- System.ComponentModel.Win32Exception : Unable to load DLL 'System.Net.Security.Native': The specified module could not be found.

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#9337]
One example failure:

```
Starting KDC..
   System.Net.Security.Tests.NegotiateStreamTest.NegotiateStream_EchoServer_ClientWriteRead_Successive_Async_Success [FAIL]
      System.Security.Authentication.AuthenticationException : A call to SSPI failed, see inner exception.
      ---- System.ComponentModel.Win32Exception : Unable to load DLL 'System.Net.Security.Native': The specified module could not be found.
       (Exception from HRESULT: 0x8007007E)
      Stack Trace:
            at System.Net.Security.NegoState.ValidateCreateContext(String package, Boolean isServer, NetworkCredential credential, String servicePrincipalName, ChannelBinding channelBinding, ProtectionLevel protectionLevel, TokenImpersonationLevel impersonationLevel)
            at System.Net.Security.NegotiateStream.BeginAuthenticateAsClient(NetworkCredential credential, ChannelBinding binding, String targetName, ProtectionLevel requiredProtectionLevel, TokenImpersonationLevel allowedImpersonationLevel, AsyncCallback asyncCallback, Object asyncState)
            at System.Net.Security.NegotiateStream.BeginAuthenticateAsClient(NetworkCredential credential, String targetName, AsyncCallback asyncCallback, Object asyncState)
            at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
            at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
            at System.Net.Security.NegotiateStream.AuthenticateAsClientAsync(NetworkCredential credential, String targetName)
            at System.Net.Security.Tests.NegotiateStreamTest.NegotiateStream_EchoServer_ClientWriteRead_Successive_Async_Success()
         ----- Inner Stack Trace -----
            at System.Net.Security.NegotiateStreamPal.AcquireCredentialsHandle(String package, Boolean isServer, NetworkCredential credential)
            at System.Net.NTAuthentication.Initialize(Boolean isServer, String package, NetworkCredential credential, String spn, ContextFlagsPal requestedContextFlags, ChannelBinding channelBinding)
            at System.Net.NTAuthentication..ctor(Boolean isServer, String package, NetworkCredential credential, String spn, ContextFlagsPal requestedContextFlags, ChannelBinding channelBinding)
            at System.Net.Security.NegoState.ValidateCreateContext(String package, Boolean isServer, NetworkCredential credential, String servicePrincipalName, ChannelBinding channelBinding, ProtectionLevel protectionLevel, TokenImpersonationLevel impersonationLevel)
```

**Comment by bartonjs** [comment]
These failures were seen in Helix.  Right now we're suspecting a packaging problem (since Jenkins passes), but that's a pretty vague place to have landed.

**Comment by ellismg** [comment]
> These failures were seen in Helix

Are they specific to an OS?  It possible we don't have a dependency for System.Net.Security.Native installed?

**Comment by bartonjs** [comment]
It looks like the Windowses passed and OSX passed; and everything else failed { Ubuntu 14, Ubuntu 16, OpenSUSE, Fedora, CentOS, Debian, Redhat }.

But a missing system dependency on our test machines is definitely an angle I'm investigating.

**Comment by joshfree** [comment]
@ericstj @weshaggard PTAL

**Comment by ericstj** [comment]
Share a lock file for a failing test please.

**Comment by ellismg** [comment]
@bartonjs and I looked into this a little.  A problem is that the native assembly (System.Net.Security.Native.so) is not being deployed to the test machine at all.  Furthermore, it's not even in the RunTest.sh file that's generated by the build which hard links all the files into their locations before running the tests.  Jeremy and I believe that's happening because the test project has a P2P reference for to implementation assembly, but there's no way for it to infer that it also means a native shim needs to be picked up.

Unlike other projects which have shims, System.Net.Security is not listed in NETStandard.Library, so the dependency is not making it's way into the lock file for the tests, so our scripts don't include it as an asset that needs to be included.

I tried adding a reference to `runtime.native.System.Net.Security` to the project.json file for the unix tests and we saw that the newly generated RunTest.sh file now deployed the asset as we wanted.  I'm submitting a helix job with this change to validate that it will actually start working on the machine in question.

**Comment by ericstj** [comment]
This is more fallout from the change from using MS.NETCore.Console to using NETStandard.Library.  One pattern we've followed for other tests is to have the test reference *both* the package and the project for the library under test.   The package brings in all the dependencies, project will take precedence for the binary.
This is all a side effect of the uber problem that our build system doesn't flow packages across project references due to it using MSBuild ProjectReferences with X-plat NuGet.  X-plat NuGet only does project.json projectrefs today, and only windows-nuget.exe knows how to get projectrefs from msbuild.

**Comment by ellismg** [comment]
> The package brings in all the dependencies, project will take precedence for the binary.

Is there additional metadata that would need to be added to the [project reference](https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/tests/FunctionalTests/System.Net.Security.Tests.csproj#L142) in this or does the system figure everything out automatically?

**Comment by weshaggard** [comment]
As @ericstj hinted at I think you can just add System.Net.Security package reference to https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/tests/FunctionalTests/unix/project.json and it should pick-up the dependencies. There isn't any support right now that for flowing it through project references.

**Comment by joshfree** [comment]
switching to a test bug now that the root cause is understood

**Comment by bartonjs** [comment]
Since the infrastructure has changed many a time, `NegotiateStream_EchoServer_ClientWriteRead_Successive_Async_Success` seems to be enabled, and that test is not failing in Helix, this seems to be a resolved problem.
