### ISSUE TITLE
X509Certificates cannot be used in Mac?

### ISSUE THREAD

**Issue by xyting** [dotnet/corefx#9402]
I can `dotnet build` my Asp.Net Core RC2 code in OS X, but `dotnet run` throw following exception

(.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file
   at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
   at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
   at mycode.Startup.ConfigureServices(IServiceCollection services)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Startup.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection exportServices)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()

**Comment by bartonjs** [comment]
This looks just like a file not found situation.... `mycode.Startup.ConfigureServices` is opening a PFX that doesn't exist.

* Did your PFX get deployed with the rest of the application?
* Is it actually at the path (presumably relative) that you expect?
* Did you use Path.Combine to get the correct directory separator, or did you use Windows backslashes?

**Comment by bartonjs** [comment]
Since we have an awful lot of tests for loading certs from files, and the message from OpenSSL is `BIO_new_file:no such file`; this just sounds like the file is actually missing.  Since we haven't heard anything new in several days I'm closing the issue (but you can still add comments if you have additional feedback)

**Comment by xyting** [comment]
@bartonjs thanks, OK, the file is missing.
