### ISSUE TITLE
ClientWebSocket_Abort_CloseOutputAsync failed in CI on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#9407]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/2082/consoleText
```
System.Net.WebSockets.Client.Tests.ClientWebSocketTest.ClientWebSocket_Abort_CloseOutputAsync(server: wss://corefx-net.cloudapp.net/WebSocket/EchoWebSocket.ashx) [FAIL]
        System.InvalidOperationException : This operation is only allowed using a successfully authenticated context.
        Stack Trace:
  Using /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest@2/packages/ as folder for resolving package dependencies.
  Executing in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest@2/bin/tests/AnyOS.AnyCPU.Debug/System.Composition.Tests/netcoreapp1.0
  Executing in unpack directory, do not have to copy files
  Hard linking dependent files...
              at System.Net.Security.SslState.CheckThrow(Boolean authSucessCheck)
              at System.Net.Security.SslState.get_SecureStream()
              at System.Net.Security.SslStream.EndWrite(IAsyncResult asyncResult)
              at System.Net.Security.SslStream.<>c.<WriteAsync>b__86_1(IAsyncResult iar)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
              at System.Net.WebSockets.WebSocketHandle.ManagedClientWebSocket.<SendFrameAsync>d__59.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
              at System.Net.WebSockets.WebSocketHandle.ManagedClientWebSocket.<SendCloseFrameAsync>d__69.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
              at System.Net.WebSockets.Client.Tests.ClientWebSocketTest.<>c.<<ClientWebSocket_Abort_CloseOutputAsync>b__37_0>d.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
              at System.Net.WebSockets.Client.Tests.ClientWebSocketTest.<TestCancellation>d__44.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
              at System.Net.WebSockets.Client.Tests.ClientWebSocketTest.<ClientWebSocket_Abort_CloseOutputAsync>d__37.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by stephentoub** [comment]
Related but different test, same issue here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_release/502/consoleText
```
 System.Net.WebSockets.Client.Tests.ClientWebSocketTest.Abort_SendAndAbort_Success(server: wss://corefx-net.cloudapp.net/WebSocket/EchoWebSocket.ashx) [FAIL]
        System.InvalidOperationException : This operation is only allowed using a successfully authenticated context.
        Stack Trace:
              at System.Net.Security.SslState.CheckThrow(Boolean authSucessCheck)
              at System.Net.Security.SslState.get_SecureStream()
              at System.Net.Security.SslStream.<>c.<WriteAsync>b__86_1(IAsyncResult iar)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Net.WebSockets.WebSocketHandle.ManagedClientWebSocket.<SendFrameAsync>d__59.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Net.WebSockets.Client.Tests.ClientWebSocketTest.<>c.<<Abort_SendAndAbort_Success>b__34_0>d.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Net.WebSockets.Client.Tests.ClientWebSocketTest.<TestCancellation>d__44.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Net.WebSockets.Client.Tests.ClientWebSocketTest.<Abort_SendAndAbort_Success>d__34.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by bartonjs** [comment]
This was seen in the wild (or, rather, CI) again :(.

**Comment by stephentoub** [comment]
Re-closing.  The occurrence seen was not run with the fix.
