### ISSUE TITLE
RC2: Connecting to SQL Server from Linux Docker Container throws OpenSSL exception

### ISSUE THREAD

**Issue by iSynaptic** [dotnet/corefx#9439]
When connecting to SQL Server from .NET Core 1.0 RC2 running within a Linux container, the System.Data.SqlClient library throws an exception citing issues with the OpenSSL handshake.  Code/steps to reproduce can be found here: https://github.com/iSynaptic/LinuxSqlServer

**Comment by saurabh500** [comment]
@isynaptic can we have the stack trace?

**Comment by iSynaptic** [comment]
`Unhandled Exception: System.Data.SqlClient.SqlException: A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, Boolean isServer, Boolean remoteCertRequired)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.SqlClient.SNI.SNITCPHandle.EnableSsl(UInt32 options)
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at LinuxSqlServer.Program.Main(String[] args)`

**Comment by saurabh500** [comment]
Also what is the SQL server version and  is the issue reproducible  without docker on Linux?

**Comment by iSynaptic** [comment]
SQL version is `10.50.1720.0`. I haven't tried reproducing outside of the container - I will now and report back.

**Comment by iSynaptic** [comment]
Yes, I can reproduce outside of the container. Running on Ubuntu 14.04.4 LTS...

**Comment by saurabh500** [comment]
@iSynaptic It seems like you are using Sql Server 2008. Is your server patched? 
We have faced similar issues with Sql Server 2008 (e.g. https://github.com/dotnet/corefx/issues/5187  ) where installing the patch from https://support.microsoft.com/en-us/kb/2653857 has mitigated the issue. 

Can you patch the server and try this?

**Comment by iSynaptic** [comment]
@saurabh500 I just reproduced the error using Sql Server 2012 Service Pack 1 (version 11.0.3000.0)...

**Comment by saurabh500** [comment]
@iSynaptic Thanks for the update, can I look at your connection string without the credentials?

**Comment by iSynaptic** [comment]
Server=MYSERVER.DOMAIN.COM;Initial Catalog=MyDatabase; user id=myusername;password=*********;Application Name=MyApp

(heavily sanitized)

**Comment by saurabh500** [comment]
@bartonjs Looking at the stack trace, this is an unsupported protocol issue.

`System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol` 

This has failed for 2 different versions of SqlServer. 
Any thoughts about troubleshooting the issue from SSL perspective?

**Comment by stephentoub** [comment]
SSL2 and SSL3 are explicitly disabled; only TLS 1.0, 1.1, and 1.2 are supported.  Is SQL Server unable to use TLS 1.* for some reason?  Is there configuration that might be set on the server preventing those protocols?

**Comment by saurabh500** [comment]
Sql Server starting 2008 and above supports TLS 1.0 - 1.2
An installation of Sql Server will have one or the other version of TLS enabled which is needed during (at least) PreLogin phase of Sql Server login.

**Comment by saurabh500** [comment]
So far I have tried this repro code with Sql Server 2008, 2012 and 2014 from Ubuntu 14.04.
I couldn't get any failures.
I tried this after removing any .Net core installation and then reinstalling .Net core followed by the repro execution.

The installations of Sql Server are default installations with Service packs installed on them. 
@iSynaptic Have you changed anything on the Server side wrt to the TLS versions on the server?

**Comment by iSynaptic** [comment]
@saurabh500 I haven't, but that's not to say someone else hasn't either. What should I look for?

**Comment by bartonjs** [comment]
One thing that could be useful is a network packet capture.  Specifically, seeing what the TLS ClientHello and ServerHello messages were, to find out what TLS version the SQL Server uh.. server.. is trying to negotiate.  For example, `openssl s_client -connect www.microsoft.com:443 -msg` gives:

```
CONNECTED(00000003)
>>> TLS 1.2 Handshake [length 0122], ClientHello
    01 00 01 1e 03 03 ce 8a 06 5d 56 c4 bd 70 bd b1
    d2 60 a6 19 0e 81 66 b8 5c 27 b2 f8 be 7a e3 d4
    a8 4f 13 96 b3 4d 00 00 88 c0 30 c0 2c c0 28 c0
    24 c0 14 c0 0a 00 a3 00 9f 00 6b 00 6a 00 39 00
    38 00 88 00 87 c0 32 c0 2e c0 2a c0 26 c0 0f c0
    05 00 9d 00 3d 00 35 00 84 c0 12 c0 08 00 16 00
    13 c0 0d c0 03 00 0a c0 2f c0 2b c0 27 c0 23 c0
    13 c0 09 00 a2 00 9e 00 67 00 40 00 33 00 32 00
    9a 00 99 00 45 00 44 c0 31 c0 2d c0 29 c0 25 c0
    0e c0 04 00 9c 00 3c 00 2f 00 96 00 41 c0 11 c0
    07 c0 0c c0 02 00 05 00 04 00 15 00 12 00 09 00
    ff 01 00 00 6d 00 0b 00 04 03 00 01 02 00 0a 00
    34 00 32 00 0e 00 0d 00 19 00 0b 00 0c 00 18 00
    09 00 0a 00 16 00 17 00 08 00 06 00 07 00 14 00
    15 00 04 00 05 00 12 00 13 00 01 00 02 00 03 00
    0f 00 10 00 11 00 23 00 00 00 0d 00 20 00 1e 06
    01 06 02 06 03 05 01 05 02 05 03 04 01 04 02 04
    03 03 01 03 02 03 03 02 01 02 02 02 03 00 0f 00
    01 01
<<< TLS 1.2 Handshake [length 003d], ServerHello
    02 00 00 39 03 03 d5 b0 4c 9a 63 ae ba 1b 16 98
    c9 33 28 51 56 71 7f 98 36 9b a0 c7 6e ba b7 53
    6a b8 da 01 8c 31 00 c0 30 00 00 11 ff 01 00 01
    00 00 0b 00 04 03 00 01 02 00 23 00 00
...
```
msgBytes[4] and msgBytes[5] in these messages represent the protocol version (in this case, `03 03` for both messages, representing TLS 1.2)

**Comment by iSynaptic** [comment]
`openssl s_client -connect MYSERVER.DOMAIN.COM:1433 -msg'

yields:

`CONNECTED(00000003)
>>> TLS 1.2 Handshake [length 0122], ClientHello
    01 00 01 1e 03 03 c8 8b cf cf a6 f4 42 43 ca f2
    b3 fe cf 50 c4 c3 ac 4e 69 73 69 eb 00 a5 2a cf
    b8 3f 24 5a 2a 51 00 00 88 c0 30 c0 2c c0 28 c0
    24 c0 14 c0 0a 00 a3 00 9f 00 6b 00 6a 00 39 00
    38 00 88 00 87 c0 32 c0 2e c0 2a c0 26 c0 0f c0
    05 00 9d 00 3d 00 35 00 84 c0 12 c0 08 00 16 00
    13 c0 0d c0 03 00 0a c0 2f c0 2b c0 27 c0 23 c0
    13 c0 09 00 a2 00 9e 00 67 00 40 00 33 00 32 00
    9a 00 99 00 45 00 44 c0 31 c0 2d c0 29 c0 25 c0
    0e c0 04 00 9c 00 3c 00 2f 00 96 00 41 c0 11 c0
    07 c0 0c c0 02 00 05 00 04 00 15 00 12 00 09 00
    ff 01 00 00 6d 00 0b 00 04 03 00 01 02 00 0a 00
    34 00 32 00 0e 00 0d 00 19 00 0b 00 0c 00 18 00
    09 00 0a 00 16 00 17 00 08 00 06 00 07 00 14 00
    15 00 04 00 05 00 12 00 13 00 01 00 02 00 03 00
    0f 00 10 00 11 00 23 00 00 00 0d 00 20 00 1e 06
    01 06 02 06 03 05 01 05 02 05 03 04 01 04 02 04
    03 03 01 03 02 03 03 02 01 02 02 02 03 00 0f 00
    01 01
140223289046688:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:s23_lib.c:177:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 295 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---`

**Comment by bartonjs** [comment]
IIRC SQL doesn't start off on a TLS connection, but rather negotiates it after the connection is established; so you'll need to do something like Wireshark to capture when the real TLS ClientHello/ServerHello happened.   (@saurabh500, am I remembering correctly?)

**Comment by saurabh500** [comment]
@bartonjs That is correct. 
`tcpdump` or `wireshark` captures would give us a better idea.

**Comment by iSynaptic** [comment]
Not sure if this is what you are looking for, but using tcpdump: `tcpdump -s 0 -n dst host {ip address here} -w linux-sql.pcap`

[linux-sql.pcap.zip](https://github.com/dotnet/corefx/files/317167/linux-sql.pcap.zip)

**Comment by saurabh500** [comment]
@iSynaptic the capture contains only Client to Server interactions and not vice versa. Can you modify your capture to have both interactions?  I think dropping `dst ` from `tcpdump -s 0 -n dst host {ip address here} -w linux-sql.pcap` should allow `tcpdump` to consider the host as both src and dst host.

**Comment by iSynaptic** [comment]
@saurabh500 Whoops! Rookie mistake. See new attached file...

[linux-sql.zip](https://github.com/dotnet/corefx/files/317247/linux-sql.zip)

**Comment by saurabh500** [comment]
@iSynaptic from the packet capture it looks like the Server is using SSL3.0 and the client is using TLS 1.0

Can you disable SSL 3.0 on the server side and enabled TLS 1.0 or above? 
Some more details here.  https://support.microsoft.com/en-us/kb/3135244

I suspect this has to do with Server side security provider selection.
As mentioned by @stephentoub on Linux TLS 1.0 - 1.2 are supported.

**Comment by iSynaptic** [comment]
@saurabh500 Unfortunately, this database server provides data for multiple applications. Disabling SSL 3.0 would require reviewing a number of applications to see if it's possible and even then we couldn't be sure we would still support all existing clients.  Is there anyway to force TLS 1.x during the handshake - perhaps a connection string flag?

**Comment by stephentoub** [comment]
Is it possible TLS 1.x is somehow disabled on the server?  You shouldn't need to disable SSL 3.0, but it seems like it's unable to negotiate anything better.

**Comment by iSynaptic** [comment]
I reach out to the DB admins to find out.

**Comment by iSynaptic** [comment]
@stephentoub @saurabh500  Which underlying driver is System.Data.SqlClient using on Linux? Is it a JDBC driver?

**Comment by stephentoub** [comment]
> Which underlying driver is System.Data.SqlClient using on Linux? Is it a JDBC driver?

It's using System.Net.Sockets and System.Net.Security:
https://github.com/dotnet/corefx/tree/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI

**Comment by iSynaptic** [comment]
@stephentoub Either TLS 1.x is disabled or the version of SQL installed doesn't support it.  These are "mission critical" database servers so changes happen slowly - not sure if TLS could be enabled or the software patched to enable it - not just yet.

As I understand it, there shouldn't be any certificates installed and encryption isn't enforced (internal systems on isolated network with high performance requirements <- why no encryption). Are there any connection string flags I can provide to stop the client from trying to initiate an encrypted connection?  I've tried "Encrypt=false" and "encrypt=false", but neither has any affect.

Thanks for your help!

**Comment by stephentoub** [comment]
cc: @davidsh, @cipop: fallout from disabling SSL2/3 in SslStream

**Comment by CIPop** [comment]
@stephentoub It appears that the server side configuration has been changed so that it only allows SSL3.0 connections which are not secure and come with perf overheads.

@iSynaptic You should be able to enable TLS1.2 | TLS1.1 | TLS1.0 | SSL3.0 on the server side without affecting RFC-compliant clients. Higher version TLS protocols are designed to automatically downgrade the connection if the client-side requires it.

**Comment by saurabh500** [comment]
@iSynaptic The TDS protocol needs a part of the login to be encrypted. This behavior cannot be modified by changing the Connection String.

**Comment by iSynaptic** [comment]
Working through turning TLS support on to see if it solves this problem...

**Comment by iSynaptic** [comment]
Seeing a different, but similar error message when trying to connect to a different SQL server (tcpdump capture attached).

[linux-sql-capture.zip](https://github.com/dotnet/corefx/files/326019/linux-sql-capture.zip)

`Unhandled Exception: System.Data.SqlClient.SqlException: Connection Timeout Expired.  The timeout period elapsed during the post-login phase.  The connection could have timed out while waiting for server to complete the login process and respond; Or it could have timed out while attempting to create multiple active connections.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=163; handshake=437; [Login] initialization=5; authentication=23; [Post-Login] complete=14050;  ---> System.ComponentModel.Win32Exception: Unknown error 258
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource'1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource'1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource'1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource'1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at LinuxSqlServer.Program.Main(String[] args)`

**Comment by saurabh500** [comment]
@iSynaptic The Post Login is what is failing right now. The SSL Handshake was successful.
Is this happening for both 2012 and 2008?
Can you provide the output of `select @@VERSION` ? This may be similar to https://github.com/dotnet/corefx/issues/6467 but need to sure.

**Comment by iSynaptic** [comment]
@saurabh500 Here is the output:

`Microsoft SQL Server 2008 R2 (SP1) - 10.50.2500.0 (X64) 
	Jun 17 2011 00:54:03 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)
`

**Comment by saurabh500** [comment]
@iSynaptic Is it possible to upgrade the server to SP3 and try out the scenario? 
https://www.microsoft.com/en-us/download/details.aspx?id=27594

**Comment by saurabh500** [comment]
We won't be working on supporting SP1 connectivity from Linux right now. The current supported version for 2008 R2 is with SP3 service pack
https://support.microsoft.com/en-us/lifecycle?C2=1044

The recommendation is to upgrade to SP3 and which will allow connectivity on higher version of the TLS protocol.
