### ISSUE TITLE
CloseAsync_Cancel_Success failed in CI on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#9472]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/2252/consoleText

```
System.Net.WebSockets.Client.Tests.CancelTest.CloseAsync_Cancel_Success(server: ws://corefx-net.cloudapp.net/WebSocket/EchoWebSocket.ashx) [FAIL]
        Assert.Equal() Failure
                       (pos 4)
        Expected: The 'System.Net.WebSockets.InternalClientWebS���
        Actual:   The WebSocket is in an invalid state ('Aborte���
                       (pos 4)
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.WebSockets.Client\tests\ClientWebSocketTestBase.cs(81,0): at System.Net.WebSockets.Client.Tests.ClientWebSocketTestBase.<TestCancellation>d__8.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.WebSockets.Client\tests\CancelTest.cs(77,0): at System.Net.WebSockets.Client.Tests.CancelTest.<CloseAsync_Cancel_Success>d__4.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/2430/consoleText
```
System.Net.WebSockets.Client.Tests.CancelTest.CloseAsync_Cancel_Success(server: ws://corefx-net.cloudapp.net/WebSocket/EchoWebSocket.ashx) [FAIL]
        Assert.Equal() Failure
                       (pos 4)
        Expected: The 'System.Net.WebSockets.InternalClientWebS���
        Actual:   The WebSocket is in an invalid state ('Aborte���
  
                       (pos 4)
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.WebSockets.Client\tests\ClientWebSocketTestBase.cs(81,0): at System.Net.WebSockets.Client.Tests.ClientWebSocketTestBase.<TestCancellation>d__8.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.WebSockets.Client\tests\CancelTest.cs(77,0): at System.Net.WebSockets.Client.Tests.CancelTest.<CloseAsync_Cancel_Success>d__4.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by steveharter** [comment]
Tracking intermittent failures in #14519 (Make System.Net tests reliable)
