### ISSUE TITLE
DocumentXPathNavigator test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#949]
This happened in a Release build in the lab (http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release/70/):

```
Discovering: System.Xml.XPath.XDocument.Tests
  Discovered:  System.Xml.XPath.XDocument.Tests
  Starting:    System.Xml.XPath.XDocument.Tests
     XPathTests.FunctionalTests.MiscellaneousCases.RegressionTestsTests.RegressionTestsTest557 [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
              at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
              at System.Xml.XmlDocumentEx.GetNamespaceXml(XmlDocument xmlDocument)
              at System.Xml.DocumentXPathNavigator.MoveToFirstNamespace(XPathNamespaceScope scope)
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Xml.XPath.XDocument\tests\XDocument\NavigatorComparer.cs(394,0): at System.Xml.XPath.XDocument.Tests.XDocument.NavigatorComparer.MoveToFirstNamespace(XPathNamespaceScope value)
              at MS.Internal.Xml.XPath.NamespaceQuery.Advance()
              at MS.Internal.Xml.XPath.Query.MoveNext()
              at MS.Internal.Xml.XPath.Query.get_Count()
              at MS.Internal.Xml.XPath.XPathSelectionIterator.get_Count()
           d:\j\workspace\dotnet_corefx_windows_release\src\Common\tests\System.Xml.XPath\Common\Utils.cs(128,0): at XPathTests.Common.Utils.XPathNodesetTest(String xml, String testExpression, XPathResult expected, XmlNamespaceManager namespaceManager, String startingNodePath)
           d:\j\workspace\dotnet_corefx_windows_release\src\Common\tests\System.Xml.XPath\MiscellaneousCases\RegressionTestsTests.cs(151,0): at XPathTests.FunctionalTests.MiscellaneousCases.RegressionTestsTests.RegressionTestsTest557()
  Finished:    System.Xml.XPath.XDocument.Tests
  
  === TEST EXECUTION SUMMARY ===
     System.Xml.XPath.XDocument.Tests  Total: 1451, Errors: 0, Failed: 1, Skipped: 0, Time: 1.717s
```

**Comment by krwq** [comment]
Fix pending: https://github.com/dotnet/corefx/pull/954

**Comment by krwq** [comment]
This should've fixed it https://github.com/dotnet/corefx/pull/954
