### ISSUE TITLE
Uri.TryCreate method throws NullReferenceException

### ISSUE THREAD

**Issue by krk** [dotnet/corefx#9541]
NullReferenceException is thrown at the line https://github.com/dotnet/corefx/blob/master/src/System.Private.Uri/src/System/Uri.cs#L2042 (_syntax is null) for the following call:

```
System.Uri url;
System.Uri.TryCreate("http:Ç", System.UriKind.RelativeOrAbsolute, out url);
```

with the stack trace

```
   at System.Uri.CreateUriInfo(Flags cF)
   at System.Uri.EnsureUriInfo()
   at System.Uri.ParseRemaining()
   at System.Uri.EnsureParseRemaining()
   at System.Uri.InitializeUri(ParsingError err, UriKind uriKind, UriFormatException& e)
   at System.Uri.CreateHelper(String uriString, Boolean dontEscape, UriKind uriKind, UriFormatException& e)
   at System.Uri.TryCreate(String uriString, UriKind uriKind, Uri& result)
   at ConsoleApplication36.Program.Main(String[] args)
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

https://connect.microsoft.com/VisualStudio/feedback/details/2826777/uri-trycreate-method-throws-nullreferenceexception

**Comment by CIPop** [comment]
Thanks for reporting @krk!
