### ISSUE TITLE
HttpClientHandler_ServerCertificates_Test.NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds failing PR runs

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#9558]
```
ystem.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds [FAIL]
14:47:18         System.Threading.Tasks.TaskCanceledException : A task was canceled.
14:47:18         Stack Trace:
14:47:18               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:47:18               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:47:18               at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
14:47:18               at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
14:47:18            --- End of stack trace from previous location where exception was thrown ---
14:47:18               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:47:18               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:47:18               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
14:47:18               at System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.<NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds>d__7.MoveNext()
14:47:18            --- End of stack trace from previous location where exception was thrown ---
14:47:18               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:47:18               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:47:18            --- End of stack trace from previous location where exception was thrown ---
14:47:18               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:47:18               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:47:18            --- End of stack trace from previous location where exception was thrown ---
14:47:18               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:47:18               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_debug_prtest/346/consoleFull

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/2250/consoleFull

**Comment by Priya91** [comment]
@CIPop Can you help triage.. Thanks!

**Comment by CIPop** [comment]
@davidsh PTAL

**Comment by davidsh** [comment]
>System.Threading.Tasks.TaskCanceledException : A task was canceled.

This error means a timeout.  Probably due to an external network communication issue with Azure.  HttpClient's default .Timeout property is 100 seconds.  So, if the HTTP request takes more than that, then HttpClient will "cancel" the request.

We have seen this before.  Unless this is happening all the time, there is nothing we can do about this other than to modify our tests to do retries, etc.

cc: @stephentoub

**Comment by stephentoub** [comment]
@Priya91, is this still failing?  I expect, as David suggests, that it was a temporary outage of the external server we were trying to contact.

**Comment by Priya91** [comment]
@stephentoub Haven't seen them today..

**Comment by davidsh** [comment]
closing this for now since this is an external Azure issue that only happens occasionally
