### ISSUE TITLE
Asp.net stress app crash due to memory corruption on Linux

### ISSUE THREAD

**Issue by yuwaMSFT** [dotnet/corefx#9574]
Saw two crashes on Linux with an Asp.net stress app after ~10 hours.

**1. Seems around invalid curlhandler**
```
Native stack:
* thread #1: tid = 0, 0x00007ffd544271b9 libcurl.so.4`??? + 41, name = 'dotnet', stop reason = signal SIGSEGV
  * frame #0: 0x00007ffd544271b9 libcurl.so.4`??? + 41
    frame #1: 0x00007ffd5442747d libcurl.so.4`??? + 29
    frame #2: 0x00007ffd543fc4ff libcurl.so.4`??? + 223
    frame #3: 0x00007ffd543fff72 libcurl.so.4`??? + 322
    frame #4: 0x00007ffd5440efa4 libcurl.so.4`curl_multi_remove_handle + 260
    frame #5: 0x00007fff7fa1a155
    frame #6: 0x00007fff7ddeee6b
    frame #7: 0x00007fff7ddef16b
    frame #8: 0x00007fff7ddee275
    frame #9: 0x00007fff7ddede74
    frame #10: 0x00007fff7ddedbb3
    frame #11: 0x00007fff7ddf3e29
    frame #12: 0x00007fff7c96e691
    frame #13: 0x00007fff7c9cdfc1
    frame #14: 0x00007fff7c9cdd28
    frame #15: 0x00007fff7c96e691
    frame #16: 0x00007ffff6210ec7 libcoreclr.so`CallDescrWorkerInternal + 124
    frame #17: 0x00007ffff612aaee libcoreclr.so`MethodDescCallSite::CallTargetWorker(unsigned long const*) + 862
    frame #18: 0x00007ffff6135a8a libcoreclr.so`ThreadNative::KickOffThread_Worker(void*) + 474
    frame #19: 0x00007ffff60fb0ee libcoreclr.so`ManagedThreadBase_DispatchOuter(ManagedThreadCallState*) + 430
    frame #20: 0x00007ffff60fb846 libcoreclr.so`ManagedThreadBase::KickOff(ADID, void (*)(void*), void*) + 70
    frame #21: 0x00007ffff6135c9b libcoreclr.so`ThreadNative::KickOffThread(void*) + 331
    frame #22: 0x00007ffff6494129 libcoreclr.so`CorUnix::CPalThread::ThreadEntry(void*) + 297
    frame #23: 0x00007ffff79c0182 libpthread.so.0`start_thread + 194
    frame #24: 0x00007ffff6ecd47d libc.so.6`clone + 109

Managed stack:
        Child SP               IP Call Site
00007FFD5C3B7428 00007ffd544271b9 [InlinedCallFrame: 00007ffd5c3b7428] Interop+Http.MultiRemoveHandle(SafeCurlMultiHandle, SafeCurlHandle)
00007FFD5C3B7428 00007fff7fa1a155 [InlinedCallFrame: 00007ffd5c3b7428] Interop+Http.MultiRemoveHandle(SafeCurlMultiHandle, SafeCurlHandle)
00007FFD5C3B7410 00007FFF7FA1A155 DomainBoundILStubClass.(SafeCurlMultiHandle, SafeCurlHandle)
00007FFD5C3B74D0 00007FFF7DDEEE6B System.Net.Http.CurlHandler+MultiAgent.DeactivateActiveRequest(ActiveRequest, IntPtr)
00007FFD5C3B7500 00007FFF7DDEF16B System.Net.Http.CurlHandler+MultiAgent.FindFailAndCleanupActiveRequest(EasyRequest, System.Exception)
00007FFD5C3B75C0 00007FFF7DDEE275 System.Net.Http.CurlHandler+MultiAgent.HandleIncomingRequests()
00007FFD5C3B7640 00007FFF7DDEDE74 System.Net.Http.CurlHandler+MultiAgent.WorkerBodyLoop()
00007FFD5C3B7720 00007FFF7DDEDBB3 System.Net.Http.CurlHandler+MultiAgent.WorkerBody()
00007FFD5C3B7780 00007FFF7DDF3E29 System.Net.Http.CurlHandler+MultiAgent+<>c.<EnsureWorkerIsRunning>b__19_0(System.Object)
00007FFD5C3B7790 00007FFF7C9CDA06 System.Threading.Tasks.Task.Execute()
00007FFD5C3B77C0 00007FFF7C96E691 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
00007FFD5C3B7810 00007FFF7C9CDFC1 System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
00007FFD5C3B78C0 00007FFF7C9CDD28 System.Threading.Tasks.Task.ExecuteEntry(Boolean)
00007FFD5C3B78E0 00007FFF7C96E691 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
00007FFD5C3B7B10 00007ffff6210ec7 [GCFrame: 00007ffd5c3b7b10]
00007FFD5C3B7CF0 00007ffff6210ec7 [DebuggerU2MCatchHandlerFrame: 00007ffd5c3b7cf0]

(lldb) sos DumpObj 00007ffe5c6c6570
Name:        Interop+Http+SafeCurlMultiHandle
MethodTable: 00007fff7fbfd700
EEClass:     00007fff7fbeced0
Size:        32(0x20) bytes
File:        /home/azureuser/.dotnet/shared/Microsoft.NETCore.App/1.0.0/System.Net.Http.dll
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007fff7cc80428  40002a4        8        System.IntPtr  1 instance 0000000000A506C0 handle
00007fff7cc705f8  40002a5       10         System.Int32  1 instance               12 _state
00007fff7cc58240  40002a6       14       System.Boolean  1 instance                1 _ownsHandle
00007fff7cc58240  40002a7       15       System.Boolean  1 instance                1 _fullyInitialized

(lldb) sos DumpVC 00007fff7cc80428 0000000000A506C0
Name:        System.IntPtr
MethodTable: 00007fff7cc80428
EEClass:     00007fff7c5a9528
Size:        24(0x18) bytes
File:        /home/azureuser/.dotnet/shared/Microsoft.NETCore.App/1.0.0/System.Private.CoreLib.ni.dll
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007fff7cc8d060  4000950        0                  PTR  0 instance 00000000000bab1e m_value
00007fff7cc80428  4000951      710        System.IntPtr  1   shared           static Zero

(lldb) sos DumpVC 00007fff7cc8d060 00000000000bab1e
Name:        System.UIntPtr
MethodTable: 00007fff7cc8d060
EEClass:     00007fff7c5ad8c0
Size:        24(0x18) bytes
File:        /home/azureuser/.dotnet/shared/Microsoft.NETCore.App/1.0.0/System.Private.CoreLib.ni.dll
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007fff7cc8d060  400120e        0                  PTR  0 instance  m_value
00007fff7cc8d060  400120f      730       System.UIntPtr  1   shared           static Zero
````

**2. Seems about invalid handle on SSL cleanup:**
```
Native stack:
(gdb) bt
#0  0x00007ffff71a92e6 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#1  0x00007ffff6f08c1c in __GI___dl_iterate_phdr (callback=0x7ffff71a8ec0, data=0x7ffd48becbb0) at dl-iteratephdr.c:76
#2  0x00007ffff71aa253 in _Unwind_Find_FDE () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#3  0x00007ffff71a7507 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#4  0x00007ffff71a86d8 in _Unwind_Backtrace () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#5  0x00007ffff6edde26 in __GI___backtrace (array=<optimized out>, size=64) at ../sysdeps/x86_64/backtrace.c:109
#6  0x00007ffff6df2e56 in backtrace_and_maps (do_abort=-152183259, do_abort@entry=3, written=117, fd=261) at ../sysdeps/unix/sysv/linux/libc_fatal.c:49
#7  0x00007ffff6e4638f in __libc_message (do_abort=do_abort@entry=3, fmt=fmt@entry=0x7ffff6f54b28 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:172
#8  0x00007ffff6e51c12 in malloc_printerr (ptr=0x100d840, str=0x7ffff6f50bfc "corrupted double-linked list", action=3) at malloc.c:4996
#9  malloc_consolidate (av=av@entry=0x7ffff7191760 <main_arena>) at malloc.c:4157
#10 0x00007ffff6e54f36 in _int_free (have_lock=1, p=0x6feeb30, av=0x7ffff7191760 <main_arena>) at malloc.c:4057
#11 free_check (mem=<optimized out>, caller=<optimized out>) at hooks.c:307
#12 0x00007ffd54be9fcd in CRYPTO_free () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#13 0x00007ffd5496246a in SSL_CTX_free () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
#14 0x00007ffd5496505c in SSL_free () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
#15 0x00007fff7d4e971a in ?? ()
#16 0x00000000c127e842 in ?? ()
#17 0x00007ffff68466b0 in vtable for InlinedCallFrame () from /home/azureuser/.dotnet/shared/Microsoft.NETCore.App/1.0.0/libcoreclr.so
#18 0x00007ffd48bedab8 in ?? ()
#19 0x00007fff7feb9608 in ?? ()
#20 0x00007fff7feb9608 in ?? ()
#21 0x00007ffd48bed960 in ?? ()
#22 0x00007fff7d4e971a in ?? ()
#23 0x00007ffd48bed9d0 in ?? ()
#24 0x00007fff7feb9608 in ?? ()
#25 0x00007ffe640f4ba8 in ?? ()
#26 0x0000000000000000 in ?? ()

Managed stack:
OS Thread Id: 0xd782 (68)
        Child SP               IP Call Site
00007FFD48BED968 00007ffff71a92e6 [InlinedCallFrame: 00007ffd48bed968] Interop+Ssl.SslDestroy(IntPtr)
00007FFD48BED968 00007fff7d4e971a [InlinedCallFrame: 00007ffd48bed968] Interop+Ssl.SslDestroy(IntPtr)
00007FFD48BED960 00007FFF7D4E971A DomainBoundILStubClass.(IntPtr)
00007FFD48BED9E0 00007FFF7E1201BE Microsoft.Win32.SafeHandles.SafeSslHandle.ReleaseHandle()
00007FFD48BEDAB8 00007ffff6210ec7 [GCFrame: 00007ffd48bedab8]
00007FFD48BEE1D0 00007ffff6210ec7 [HelperMethodFrame_1OBJ: 00007ffd48bee1d0] System.Runtime.InteropServices.SafeHandle.DangerousRelease()

Name:        Microsoft.Win32.SafeHandles.SafeSslHandle
MethodTable: 00007fff7febabb8
EEClass:     00007fff7fec48d8
Size:        56(0x38) bytes
File:        /home/azureuser/.dotnet/shared/Microsoft.NETCore.App/1.0.0/System.Net.Security.dll
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007fff7cc6b428  40002a4        8        System.IntPtr  1 instance 0000000014ED03C0 handle
00007fff7cc5b5f8  40002a5       10         System.Int32  1 instance                3 _state        --------------------------------- we set as closed and disposed
00007fff7cc43240  40002a6       14       System.Boolean  1 instance                1 _ownsHandle
00007fff7cc43240  40002a7       15       System.Boolean  1 instance                1 _fullyInitialized
00007fff7febac98  4000001       18 ...les.SafeBioHandle  0 instance 00007ffe640f4b68 _readBio
00007fff7febac98  4000002       20 ...les.SafeBioHandle  0 instance 00007ffe640f4b88 _writeBio
00007fff7cc43240  4000003       28       System.Boolean  1 instance                1 _isServer------------------------------------this is server side
00007fff7cc43240  4000004       29       System.Boolean  1 instance                1 _handshakeCompleted

(lldb) sos DumpVC 00007fff7cc6b428 0000000014ED03C0
Name:        System.IntPtr
MethodTable: 00007fff7cc6b428
EEClass:     00007fff7c594528
Size:        24(0x18) bytes
File:        /home/azureuser/.dotnet/shared/Microsoft.NETCore.App/1.0.0/System.Private.CoreLib.ni.dll
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007fff7cc78060  4000950        0                  PTR  0 instance 0000200000000303 m_value
00007fff7cc6b428  4000951      710        System.IntPtr  1   shared           static Zero
                                 >> Domain:Value  00000000006549e0:NotInit  <<

(lldb) memory read 0x0000200000000303
error: core file does not contain 0x200000000303

```

**Comment by ellismg** [comment]
Do you have coredumps somewhere?

**Comment by yuwaMSFT** [comment]
Yes…shared with Stephen…

**Comment by stephentoub** [comment]
@bartonjs, both of these actually look like they may be SslStream issues.

I was having trouble loading symbols with the core dump so as to make meaningful progress, and @janvorli was very helpful in assisting me.  The cited thread does appear to be the source of the seg fault, but it doesn't appear to be related to a bad SafeCurlMultiHandle... the commands shown using DumpVC are actually passing the wrong addresses... the handle value in the SafeCurlMultiHandle appears to be non-zero and fine.

The actual issue appears to be that there's a corrupted linked list in the bowels of libcurl, having to do with its connection pool, but we suspect that this corruption was actually caused by elsewhere, related to what's going on with another thread.  One of the other threads shows this:
```
(lldb) clrstack -f
OS Thread Id: 0xaad9 (8)
        Child SP               IP Call Site
00007FFD5930A2E8 00007FFFF6F24A63 libc.so.6!__memmove_ssse3_back + 6611 at /build/eglibc-3GlaMS/eglibc-2.19/string/../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:1545
00007FFD5930A2F0 00007FFD54C67FEE libcrypto.so.1.0.0!??? + 190
00007FFD5930A320 00007FFD54C6716B libcrypto.so.1.0.0!BIO_read + 107
00007FFD5930A350 00007FFF7EE771F3
00007FFD5930A360                  [InlinedCallFrame: 00007ffd5930a360] System.Net.Security.dll!Interop+Crypto.BioRead(Microsoft.Win32.SafeHandles.SafeBioHandle, Byte[], Int32)
00007FFD5930A360                  [InlinedCallFrame: 00007ffd5930a360] System.Net.Security.dll!Interop+Crypto.BioRead(Microsoft.Win32.SafeHandles.SafeBioHandle, Byte[], Int32)
00007FFD5930A350 00007FFF7EE771F3 System.Runtime.Extensions.dll!DomainBoundILStubClass.(Microsoft.Win32.SafeHandles.SafeBioHandle, Byte[], Int32) + 179
00007FFD5930A400 00007FFF7E154F72 System.Net.Security.dll!Interop+OpenSsl.BioRead(Microsoft.Win32.SafeHandles.SafeBioHandle, Byte[], Int32) + 18
00007FFD5930A420 00007FFF7E154694 System.Net.Security.dll!Interop+OpenSsl.Encrypt(Microsoft.Win32.SafeHandles.SafeSslHandle, Byte[], Int32, Int32, Byte[] ByRef, SslErrorCode ByRef) + 244
00007FFD5930A460 00007FFF7E14209C System.Net.Security.dll!System.Net.SslStreamPal.EncryptDecryptHelper(System.Net.Security.SafeDeleteContext, Byte[], Int32, Int32, Boolean, Byte[] ByRef, Int32 ByRef) + 124
00007FFD5930A4D0 00007FFF7E145497 System.Net.Security.dll!System.Net.Security.SecureChannel.Encrypt(Byte[], Int32, Int32, Byte[] ByRef, Int32 ByRef) + 695
00007FFD5930A560 00007FFF7E14C334 System.Net.Security.dll!System.Net.Security.SslStreamInternal.StartWriting(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest) + 564 
```
Jan dumped the SafeBioHandle being passed to the P/Invoke:
```
(lldb) dumpobj 0x00007ffe5fe85a20
Name:        Microsoft.Win32.SafeHandles.SafeBioHandle
MethodTable: 00007fff7eebd7f0
EEClass:     00007fff7ee674f0
Size:        32(0x20) bytes
File:        /home/azureuser/.dotnet/shared/Microsoft.NETCore.App/1.0.0/System.Net.Security.dll
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007fff7cc80428  40002a4        8        System.IntPtr  1 instance 0000000005EAB9D0 handle
00007fff7cc705f8  40002a5       10         System.Int32  1 instance               13 _state
00007fff7cc58240  40002a6       14       System.Boolean  1 instance                1 _ownsHandle
00007fff7cc58240  40002a7       15       System.Boolean  1 instance                1 _fullyInitialized
```
and I note that the _state value is strange. ```13``` suggests to me that we're dealing with a SafeHandle that's been add-ref'd several times (e.g. once manually and once as part of the P/Invoke) but that's also been marked as invalid (SetHandleAsInvalid).  I see that here:
https://github.com/dotnet/corefx/blob/release/1.0.0/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.Ssl.cs#L269-L276
we do in fact have two SafeBioHandles that we mark with SetHandleAsInvalid, and that we also use DangerousAddRef on these:
https://github.com/dotnet/corefx/blob/release/1.0.0/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.Ssl.cs#L226-L230
and these are exposed out:
https://github.com/dotnet/corefx/blob/release/1.0.0/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.Ssl.cs#L177-L185
A P/Invoke with a SafeHandle that's been marked as invalid will fail, but only if it was marked as invalid before the call... if it's marked concurrently with the call, we could end up in exactly this situation: a _state of 13 on a SafeHandle being used currently in a P/Invoke.

Is it possible that the parent SafeSslHandle is getting freed (https://github.com/dotnet/corefx/blob/release/1.0.0/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.Ssl.cs#L261) concurrently with the usage highlighted in the above stack?  That ReleaseHandle would be calling SslDestroy while these were being used elsewhere.

And that then fits in almost exactly with the second crash highlighted here.

**Comment by stephentoub** [comment]
Courtesy of Jan, here's the full stack for the second crash:
```
(lldb) clrstack -f
OS Thread Id: 0xd782 (68)
        Child SP               IP Call Site
00007FFD48BECA80 00007FFFF71A92E6 libgcc_s.so.1!??? + 1062
00007FFD48BECB10 00007FFFF6F08C1C libc.so.6!__dl_iterate_phdr + 236 at /build/eglibc-3GlaMS/eglibc-2.19/elf/dl-iteratephdr.c:77
00007FFD48BECBB0 00007FFFF71AA253 libgcc_s.so.1!_Unwind_Find_FDE + 419
00007FFD48BECC10 00007FFFF71A7507 libgcc_s.so.1!??? + 135
00007FFD48BECCA0 00007FFFF71A86D8 libgcc_s.so.1!_Unwind_Backtrace + 104
00007FFD48BECF50 00007FFFF6EDDE26 libc.so.6!__GI___backtrace + 86 at /build/eglibc-3GlaMS/eglibc-2.19/debug/../sysdeps/x86_64/backtrace.c:113
00007FFD48BECF90 00007FFFF6DF2E56 libc.so.6!backtrace_and_maps + 46 at /build/eglibc-3GlaMS/eglibc-2.19/libio/../sysdeps/unix/sysv/linux/libc_fatal.c:50
00007FFD48BED5C0 00007FFFF6E4638F libc.so.6!__libc_message + 703 at /build/eglibc-3GlaMS/eglibc-2.19/libio/../sysdeps/posix/libc_fatal.c:175
00007FFD48BED830 00007FFFF6E51C12 libc.so.6!malloc_consolidate + 1106 at /build/eglibc-3GlaMS/eglibc-2.19/malloc/malloc.c:4996
00007FFD48BED830 00007FFFF6E51B30 libc.so.6!malloc_consolidate + 880 at /build/eglibc-3GlaMS/eglibc-2.19/malloc/malloc.c:4990
00007FFD48BED8E0 00007FFFF6E54F36 libc.so.6!free_check + 1222 at /build/eglibc-3GlaMS/eglibc-2.19/malloc/malloc.c:4057
00007FFD48BED8E0 00007FFFF6E54F10 libc.so.6!free_check + 1184 at /build/eglibc-3GlaMS/eglibc-2.19/malloc/malloc.c:4036
00007FFD48BED930 00007FFD54BE9FCD libcrypto.so.1.0.0!CRYPTO_free + 29
00007FFD48BED940 00007FFD5496246A libssl.so.1.0.0!SSL_CTX_free + 138
00007FFD48BED950 00007FFD5496505C libssl.so.1.0.0!SSL_free + 492
00007FFD48BED960 00007FFF7D4E971A
00007FFD48BED968                  [InlinedCallFrame: 00007ffd48bed968] System.Net.Security.dll!Interop+Ssl.SslDestroy(IntPtr)
00007FFD48BED968                  [InlinedCallFrame: 00007ffd48bed968] System.Net.Security.dll!Interop+Ssl.SslDestroy(IntPtr)
00007FFD48BED960 00007FFF7D4E971A System.Runtime.Extensions.dll!DomainBoundILStubClass.(IntPtr) + 106
00007FFD48BED9E0 00007FFF7E1201BE System.Net.Security.dll!Microsoft.Win32.SafeHandles.SafeSslHandle.ReleaseHandle() + 62
00007FFD48BEDA00 00007FFFF6210EC7 libcoreclr.so!CallDescrWorkerInternal + 124
00007FFD48BEDA20 00007FFFF612A420 libcoreclr.so!DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 256
00007FFD48BEDAB0 00007FFFF61BEEC0 libcoreclr.so!SafeHandle::RunReleaseMethod(SafeHandle*) + 144
00007FFD48BEDAB8                  [GCFrame: 00007ffd48bedab8]
00007FFD48BEDB50 00007FFFF61BED73 libcoreclr.so!SafeHandle::Release(bool) + 691
00007FFD48BEDC20 00007FFFF61BFD8C libcoreclr.so!SafeHandle::DangerousRelease(SafeHandle*) + 380
00007FFD48BEE1D0                  [HelperMethodFrame_1OBJ: 00007ffd48bee1d0] System.Private.CoreLib.ni.dll!System.Runtime.InteropServices.SafeHandle.DangerousRelease()
00007FFD48BEE300 00007FFF7C99CFEB System.Private.CoreLib.ni.dll!System.StubHelpers.StubHelpers.SafeHandleRelease(System.Runtime.InteropServices.SafeHandle) + 27
00007FFD48BEE330 00007FFF7FED5A52 System.Runtime.Extensions.dll!DomainBoundILStubClass.(Microsoft.Win32.SafeHandles.SafeSslHandle, Byte*, Int32) + 290
00007FFD48BEE388                  [InlinedCallFrame: 00007ffd48bee388] System.Net.Security.dll!Interop+Ssl.SslWrite(Microsoft.Win32.SafeHandles.SafeSslHandle, Byte*, Int32)
00007FFD48BEE370 00007FFF7FED59FF System.Runtime.Extensions.dll!DomainBoundILStubClass.(Microsoft.Win32.SafeHandles.SafeSslHandle, Byte*, Int32) + 207
00007FFD48BEE420 00007FFF7E13F60A System.Net.Security.dll!Interop+OpenSsl.Encrypt(Microsoft.Win32.SafeHandles.SafeSslHandle, Byte[], Int32, Int32, Byte[] ByRef, SslErrorCode ByRef) + 106
00007FFD48BEE460 00007FFF7E12D09C System.Net.Security.dll!System.Net.SslStreamPal.EncryptDecryptHelper(System.Net.Security.SafeDeleteContext, Byte[], Int32, Int32, Boolean, Byte[] ByRef, Int32 ByRef) + 124
00007FFD48BEE4D0 00007FFF7E130497 System.Net.Security.dll!System.Net.Security.SecureChannel.Encrypt(Byte[], Int32, Int32, Byte[] ByRef, Int32 ByRef) + 695
00007FFD48BEE560 00007FFF7E137334 System.Net.Security.dll!System.Net.Security.SslStreamInternal.StartWriting(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest) + 564
00007FFD48BEE640 00007FFF7E138097 System.Net.Security.dll!System.Net.Security.SslStreamInternal.WriteCallback(System.IAsyncResult) + 279
00007FFD48BEE680 00007FFF7E14086C System.Net.Security.dll!System.Threading.Tasks.TaskToApm+<>c__DisplayClass3_0.<InvokeCallbackWhenTaskCompletes>b__0() + 28
00007FFD48BEE690 00007FFF7C959691 System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) + 113
00007FFD48BEE6E0 00007FFF7C9F0DB8 System.Private.CoreLib.ni.dll!System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback, System.Object, System.Threading.Tasks.Task ByRef) + 88
00007FFD48BEE720 00007FFF7C9BA231 System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.FinishContinuations() + 513
00007FFD48BEE7A0 00007FFF7C9C0124 System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon) + 116
00007FFD48BEE7C0 00007FFF7CABFD67 System.Private.CoreLib.ni.dll!System.Threading.Tasks.TaskCompletionSource`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon) + 23
00007FFD48BEE7E0 00007FFF7FA474D7 Microsoft.AspNetCore.Server.Kestrel.dll!Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.LoggingThreadPool.<.ctor>b__4_1(System.Object) + 87
00007FFD48BEE840 00007FFF7C959691 System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) + 113
00007FFD48BEE890 00007FFF7CAC05D2 System.Private.CoreLib.ni.dll!System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() + 66
00007FFD48BEE8B0 00007FFF7C9D59D9 System.Private.CoreLib.ni.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() + 425
00007FFD48BEE910 00007FFFF6210EC7 libcoreclr.so!CallDescrWorkerInternal + 124
00007FFD48BEE930 00007FFFF612AAEE libcoreclr.so!MethodDescCallSite::CallTargetWorker(unsigned long const*) + 862
00007FFD48BEEAE0 00007FFFF631F37A libcoreclr.so!QueueUserWorkItemManagedCallback(void*) + 186
00007FFD48BEEBF0 00007FFFF60FB0EE libcoreclr.so!ManagedThreadBase_DispatchOuter(ManagedThreadCallState*) + 430
00007FFD48BEEC40                  [DebuggerU2MCatchHandlerFrame: 00007ffd48beec40]
00007FFD48BEED10 00007FFFF60FB8A6 libcoreclr.so!ManagedThreadBase::ThreadPool(ADID, void (*)(void*), void*) + 70
00007FFD48BEED60 00007FFFF6302EC7 libcoreclr.so!ManagedPerAppDomainTPCount::DispatchWorkItem(bool*, bool*) + 295
00007FFD48BEEE50 00007FFFF611B10C libcoreclr.so!ThreadpoolMgr::WorkerThreadStart(void*) + 1228
00007FFD48BEEEC0 00007FFFF6494129 libcoreclr.so!CorUnix::CPalThread::ThreadEntry(void*) + 297
00007FFD48BEEEE0 00007FFFF79C0182 libpthread.so.0!start_thread + 194 at /build/eglibc-3GlaMS/eglibc-2.19/nptl/pthread_create.c:312
00007FFD48BEEF80 00007FFFF6ECD47D libc.so.6!__clone + 109 at /build/eglibc-3GlaMS/eglibc-2.19/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```
It appears something somewhere is disposing of the SafeSslHandle while it's being used in a P/Invoke.  When the P/Invoke completes, the ref count that was incremented when the call was made is decremented, and we end up releasing the SafeSslHandle due to the pending disposal. That does the SslDestroy, at which point it seems we're double-freeing or some other such bug.

**Comment by stephentoub** [comment]
@bartonjs, the lifetime management of the SafeBioHandles with regards to the SafeSslHandle seems wrong to me.

The SafeSslHandle.Create method creates to SafeBioHandles, transfers ownership of their handles to the SafeSslHandle, and addrefs them to prevent them from being disposed of until the SafeSslHandle is released.  But this means the SafeSslHandle can be disposed of, destroying the SSL context, while the SafeBioHandles remain "alive" and referencing already disposed state.  It seems we have this backwards.  Essentially these SafeBioHandles are like the "SafeInteriorHandles", non-owning SafeHandles we use elsewhere.  It seems that they should be add-ref'ing the "parent" SafeSslHandle, rather than it add-ref'ing them, so that it can't be torn down while the SafeBioHandles are in use.  The parent stores the children in fields, so they'll be kept from finalization for as long as it is, but even if they weren't they wouldn't own the underlying handle, so their Dispose/finalization would be a nop other than decrementing the ref count on the parent.

Right? Wrong?

**Comment by bartonjs** [comment]
Yep, sounds right to me.  But, as the person who added the SafeInteriorHandle class, I might be biased toward it always being the right answer :)

**Comment by bartonjs** [comment]
This one *does* sound a little different, because we need to change the state from Owner to SharedOwner, which I don't think we've done before.  But I agree that the current model is backwards compared to how the rest of the libcrypto/libssl interop memory management works.

**Comment by stephentoub** [comment]
> because we need to change the state from Owner to SharedOwner, which I don't think we've done before

Without thread aborts, we can just create them as "SharedOwner" and dispose of them in a finally if an error occurs before we've transferred ownership.
