### ISSUE TITLE
System.Globalization.Extensions::IdnaConformanceTests::TestAsciiPositive failure

### ISSUE THREAD

**Issue by arbsmith** [dotnet/corefx#959]
On a local build I am hitting this failure:

Message:
Decoded string is not a valid IDN name.
Parameter name: unicode

Stack Trace:
   at System.Globalization.IdnMapping.ThrowForZeroLength(String paramName, String invalidNameString, String otherString)
   at System.Globalization.IdnMapping.GetAsciiCore(String unicode)
   at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index, Int32 count)
   at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index)
   at System.Globalization.IdnMapping.GetAscii(String unicode)
   at System.Globalization.Extensions.Tests.IdnaConformanceTests.TestAsciiPositive()

**Comment by arbsmith** [comment]
This is a dupe of #579
