### ISSUE TITLE
ARM64: System.Console.Tests

### ISSUE THREAD

**Issue by kyulee1** [dotnet/corefx#9626]
```
WindowAndCursorProps.SetWindowSize [FAIL]
      System.ArgumentOutOfRangeException : The new console window size would force the console buffer size to be too large.
      Parameter name: width
      Actual value was 241.
      Stack Trace:
            at System.ConsolePal.SetWindowSize(Int32 width, Int32 height)
            at System.Console.set_WindowWidth(Int32 value)
            at WindowAndCursorProps.SetWindowSize()
Finished:    System.Console.Tests

=== TEST EXECUTION SUMMARY ===
   System.Console.Tests  Total: 75, Errors: 0, Failed: 1, Skipped: 0, Time: 15.235s
Finished running tests.  End time= 8:33:55.37, Exit code = 1
```

**Comment by ianhays** [comment]
This didn't fail for me with the recent sources.
