### ISSUE TITLE
ARM64: System.Data.SqlClient.Tests

### ISSUE THREAD

**Issue by kyulee1** [dotnet/corefx#9627]
```
   System.Data.SqlClient.Tests.SqlErrorCollectionTest.Indexer_Success [FAIL]
      System.TypeInitializationException : The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.
      ---- System.TypeInitializationException : The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception.
      -------- System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B (COR_E_BADIMAGEFORMAT))
      Stack Trace:
            at System.Data.SqlClient.TdsParser..ctor(Boolean MARS, Boolean fAsynchronous)
            at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, TimeoutTimer timeout)
            at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, Boolean redirectedUserInstance)
            at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
            at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
            at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
            at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
            at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
            at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
            at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
            at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
            at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
            at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
            at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
            at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
            at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
            at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
            at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
            at System.Data.SqlClient.Tests.SqlErrorCollectionTest.Indexer_Success()
            at System.Data.SqlClient.SqlConnection.Open()
            at System.Data.SqlClient.Tests.ExceptionTest.GenerateConnectionException(String connectionString)
            at System.Data.SqlClient.Tests.ExceptionTest.<>c__DisplayClass5_0.<ExceptionTests>b__0()
         ----- Inner Stack Trace -----
            at System.Data.SqlClient.TdsParser..cctor()
         ----- Inner Stack Trace -----
            at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize(IntPtr pmo)
            at System.Data.SqlClient.SNILoadHandle..ctor()
            at System.Data.SqlClient.SNILoadHandle..cctor()
   System.Data.SqlClient.Tests.ExceptionTest.ExceptionTests [FAIL]
   System.Data.SqlClient.Tests.ExceptionTest.IndependentConnectionExceptionTestOpenConnection [FAIL]
   System.Data.SqlClient.Tests.SqlErrorCollectionTest.CopyTo_NonGeneric_Success [FAIL]
   System.Data.SqlClient.Tests.SqlErrorCollectionTest.CopyTo_Throws [FAIL]
   System.Data.SqlClient.Tests.SqlErrorCollectionTest.IsSynchronized_Success [FAIL]
   System.Data.SqlClient.Tests.SqlErrorCollectionTest.SyncRoot_Success [FAIL]
   System.Data.SqlClient.Tests.SqlErrorCollectionTest.CopyTo_Success [FAIL]
   System.Data.SqlClient.Tests.SqlErrorCollectionTest.CopyTo_NonGeneric_Throws [FAIL]
   System.Data.SqlClient.Tests.SqlErrorCollectionTest.GetEnumerator_Success [FAIL]
   System.Data.SqlClient.Tests.SqlErrorCollectionTest.Indexer_Throws [FAIL]
...

Finished:    System.Data.SqlClient.Tests

=== TEST EXECUTION SUMMARY ===
   System.Data.SqlClient.Tests  Total: 82, Errors: 0, Failed: 11, Skipped: 0, Time: 8.406s
```

**Comment by ianhays** [comment]
Confirmed that with the SNI ARM64 produced after my internal Codeflow change (along with #10043), all of the Sqlclient tests pass.

**Comment by ianhays** [comment]
There was a snag with the win10-arm64 package (we weren't publishing it) that should be fixed now. These tests will be passing after we publish the package (tomorrow/tonight) and update the version of Microsoft.NetCore.Targets being used in test-runtime.

**Comment by saurabh500** [comment]
@ianhays Can this be closed now ?
