### ISSUE TITLE
ARM64: System.Diagnostics.Process.Tests

### ISSUE THREAD

**Issue by kyulee1** [dotnet/corefx#9628]
```
   System.Diagnostics.Tests.ProcessTests.TestProcessOnRemoteMachineWindows [FAIL]
      System.InvalidOperationException : Couldn't connect to remote machine.
      ---- System.InvalidOperationException : Couldn't get process information from performance counter.
      -------- System.InvalidOperationException : Cannot load Counter Name data because an invalid index '' was read from the registry.
      Stack Trace:
            at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
            at System.Diagnostics.NtProcessManager.GetProcessIds(String machineName, Boolean isRemoteMachine)
            at System.Diagnostics.ProcessManager.GetProcessIds(String machineName)
            at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
            at System.Diagnostics.Tests.ProcessTests.<GetTestProcess>d__39.MoveNext()
            at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
         ----- Inner Stack Trace -----
            at System.Diagnostics.NtProcessManager.GetProcessInfos(PerformanceCounterLib library)
            at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
         ----- Inner Stack Trace -----
            at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
            at System.Diagnostics.PerformanceCounterLib.get_NameTable()
            at System.Diagnostics.PerformanceCounterLib.GetCounterName(Int32 index)
            at System.Diagnostics.NtProcessManager.GetProcessInfos(PerformanceCounterLib library, Int32 processIndex, Int32 threadIndex, Byte[] data)
            at System.Diagnostics.NtProcessManager.GetProcessInfos(PerformanceCounterLib library)
Finished:    System.Diagnostics.Process.Tests

=== TEST EXECUTION SUMMARY ===
   System.Diagnostics.Process.Tests  Total: 88, Errors: 0, Failed: 1, Skipped: 0, Time: 42.874s
```

**Comment by ianhays** [comment]
These aren't failing anymore.

**Comment by sandreenko** [comment]
I see that the same tests fails on arm64 with the same error in CoreCLR testing, 

```
Z:\_\fx\artifacts\bin\tests\System.Diagnostics.Process.Tests\netcoreapp-Windows_NT-Release-arm64>call Z:\_\fx\artifacts\bin\testhost\netcoreapp-Windows_NT-Release-arm64\dotnet.exe xunit.console.dll System.Diagnostics.Process.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing   -parallel none -method System.Diagnostics.Tests.ProcessTests.GetProcesses_RemoteMachinePath_ReturnsExpected
xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 4.6.27414.0)
  Discovering: System.Diagnostics.Process.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Diagnostics.Process.Tests (found 1 of 237 test case)
  Starting:    System.Diagnostics.Process.Tests (parallel test collections = off, max threads = 8)
    System.Diagnostics.Tests.ProcessTests.GetProcesses_RemoteMachinePath_ReturnsExpected [FAIL]
      System.InvalidOperationException : Couldn't connect to remote machine.
      ---- System.InvalidOperationException : Couldn't get process information from performance counter.
      -------- System.IO.IOException : The network path was not found.
      Stack Trace:
        F:\git\coreclr\_\fx\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(343,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
        F:\git\coreclr\_\fx\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(54,0): at System.Diagnostics.ProcessManager.GetProcessInfos(String machineName)
        F:\git\coreclr\_\fx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(1051,0): at System.Diagnostics.Process.GetProcesses(String machineName)
        F:\git\coreclr\_\fx\src\System.Diagnostics.Process\tests\ProcessTests.cs(1049,0): at System.Diagnostics.Tests.ProcessTests.GetProcesses_RemoteMachinePath_ReturnsExpected()
        ----- Inner Stack Trace -----
        F:\git\coreclr\_\fx\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(368,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(PerformanceCounterLib library)
        F:\git\coreclr\_\fx\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(337,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
        ----- Inner Stack Trace -----
        F:\git\coreclr\_\fx\src\Microsoft.Win32.Registry\src\Microsoft\Win32\RegistryKey.Windows.cs(969,0): at Microsoft.Win32.RegistryKey.Win32ErrorStatic(Int32 errorCode, String str)
        F:\git\coreclr\_\fx\src\Microsoft.Win32.Registry\src\Microsoft\Win32\RegistryKey.Windows.cs(234,0): at Microsoft.Win32.RegistryKey.OpenRemoteBaseKeyCore(RegistryHive hKey, String machineName, RegistryView view)
        F:\git\coreclr\_\fx\src\Microsoft.Win32.Registry\src\Microsoft\Win32\RegistryKey.cs(336,0): at Microsoft.Win32.RegistryKey.OpenRemoteBaseKey(RegistryHive hKey, String machineName, RegistryView view)
        F:\git\coreclr\_\fx\src\Microsoft.Win32.Registry\src\Microsoft\Win32\RegistryKey.cs(325,0): at Microsoft.Win32.RegistryKey.OpenRemoteBaseKey(RegistryHive hKey, String machineName)
        F:\git\coreclr\_\fx\src\System.Diagnostics.Process\src\System\Diagnostics\PerformanceCounterLib.cs(210,0): at System.Diagnostics.PerformanceCounterLib.PerformanceMonitor.Init()
        F:\git\coreclr\_\fx\src\System.Diagnostics.Process\src\System\Diagnostics\PerformanceCounterLib.cs(202,0): at System.Diagnostics.PerformanceCounterLib.PerformanceMonitor..ctor(String machineName)
        F:\git\coreclr\_\fx\src\System.Diagnostics.Process\src\System\Diagnostics\PerformanceCounterLib.cs(84,0): at System.Diagnostics.PerformanceCounterLib.GetPerformanceData(String item)
        F:\git\coreclr\_\fx\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(363,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(PerformanceCounterLib library)
  Finished:    System.Diagnostics.Process.Tests
=== TEST EXECUTION SUMMARY ===
   System.Diagnostics.Process.Tests  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 1.617s
```

Maybe it was not fixed but excluded? @ianhays
