### ISSUE TITLE
ARM64: System.IO.FileSystem.Tests fail

### ISSUE THREAD

**Issue by kyulee1** [dotnet/corefx#9634]
```
You do not have sufficient privilege to perform this operation.
Discovered:  System.IO.FileSystem.Tests
Starting:    System.IO.FileSystem.Tests
...
   System.IO.Tests.Directory_EnumFiles_str_str.WindowsSearchPatternInvalid [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.IO.IOException)
      Actual:   (No exception was thrown)
      Stack Trace:
            at System.IO.Tests.Directory_GetFileSystemEntries_str_str.WindowsSearchPatternInvalid()

...
   System.IO.Tests.File_Create_str_i_fo.CreateCurrentDirectory [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.UnauthorizedAccessException)
      Actual:   typeof(System.IO.IOException): The process cannot access the file 'E:\Github\corefx\bin\tests\Windows_NT.AnyCPU.Release\System.IO.FileSystem.Tests\netcoreapp1.0' because it is being used by another process.
      Stack Trace:
            at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
            at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
            at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
            at System.IO.Tests.File_Create_str_i_fo.Create(String path)
            at System.IO.Tests.File_Create_str.<CreateCurrentDirectory>b__4_0()

...
   System.IO.Tests.Directory_CreateDirectory.PathWithReservedDeviceNameAsExtendedPath [FAIL]
      Assert.All() Failure: 22 out of 22 items in the collection did not pass.
      [21]: System.UnauthorizedAccessException: Access to the path '\\?\E:\Github\corefx\bin\tests\Windows_NT.AnyCPU.Release\System.IO.FileSystem.Tests\netcoreapp1.0\ei4v2v0y.ww1\LPT9' is denied.
               at System.IO.Win32FileSystem.CreateDirectory(String fullPath)
               at System.IO.Directory.CreateDirectory(String path)
               at System.IO.Tests.Directory_CreateDirectory.Create(String path)
               at System.IO.Tests.Directory_CreateDirectory.<>c__DisplayClass33_0.<PathWithReservedDeviceNameAsExtendedPath>b__0(String path)
               at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 act
...

=== TEST EXECUTION SUMMARY ===
   System.IO.FileSystem.Tests  Total: 2276, Errors: 0, Failed: 32, Skipped: 26, Time: 3924.654s
```

**Comment by ianhays** [comment]
cc: @rahku

**Comment by ramarag** [comment]
cc @gkhanna79 

System.IO.Tests.FileStream_ctor_str_fm_fa_fs_buffer_fo.ValidFileOptions:
ARM64 currently does not support FileOptions.Encrypted when creating a file just like on ARM
So i believe the xunit theory generator should not get this value

**Comment by gkhanna79** [comment]
@ianhays PTAL when you are back.

**Comment by karelz** [comment]
@wfurt do you know if this is still failing?

**Comment by wfurt** [comment]
seems like some limitation per @ramarag comment. However I did check and the test is not disabled and not failing last 90 days. This is very old and we have updated versions of windows now. 

closing now, we can reopen if this fails ever again. 
cc: @carlossanlop

**Comment by karelz** [comment]
Thanks @wfurt for confirmation!
