### ISSUE TITLE
String.Normalize() throws SEHException on Windows Server 2016 TP5

### ISSUE THREAD

**Issue by mikeharder** [dotnet/corefx#9650]
# Repro Steps
1. Install CLI 1.0.0-preview2-003121
2. `dotnet new& dotnet restore& dotnet run`
3. Edit `Program.cs`, and change the code to `Console.WriteLine("Hello World!".Normalize());`
4. `dotnet run`

# Expected
Prints `Hello World!`

# Actual
On Windows Server 2012 R2, it works fine.  On Windows Server 2016 TP5, it fails with the following exception:

```
Unhandled Exception: System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at Interop.mincore.NormalizeString(Int32 normForm, String source, Int32 sourceLength, Char[] destenation, Int32 destenationLength)
   at System.StringNormalizationExtensions.Normalize(String strInput, NormalizationForm normalizationForm)
   at System.StringNormalizationExtensions.Normalize(String strInput)
   at ConsoleApplication.Program.Main(String[] args)
```

I'm not sure if this is a bug in CoreFx or Windows Server 2016 TP5.

**Comment by joshfree** [comment]
@tarekgh PTAL

**Comment by tarekgh** [comment]
this is Windows bug:


```
From: Patrick Lang 
Sent: Thursday, June 23, 2016 4:21 PM
To: Mike Harder <mharder@microsoft.com>; Chris Ross (WEB TOOLS) <chrross@microsoft.com>; Rich Wolcott <rwolcott@microsoft.com>; David So <David.So@microsoft.com>; Hao Kung <haok@microsoft.com>; Diego Vega <Diego.Vega@microsoft.com>; Rohit Jaini <rjaini@microsoft.com>; Erick Smith <Erick.Smith@microsoft.com>
Cc: Perry Skountrianos <Perry.Skountrianos@microsoft.com>; Tarek Mahmoud Sayed <Tarek.Mahmoud.Sayed@microsoft.com>; Josh Free <jfree@microsoft.com>
Subject: RE: Regression on latest builds? got a repro for Bug 5681693 re: NormalizeString

It’s not fixed in a new build. I walked Rich through the minimal repro and he’s getting it handed off to the NLS team.

The code will work once after a host reboot. It will crash the 2nd and subsequent containers.

Here’s the current bug with link to a really easy repro:
Bug 7845692:Win32 NormalizeString fails in 2nd to nth Server Core instances - breaks Asp.net
```

**Comment by tarekgh** [comment]
I'll keep this issue open till we reach some conclusion

**Comment by tarekgh** [comment]
talked offline to Rich Wolcott and looks it is Windows issues and not the .Net issue. I am closing this issue and I am following anyway with the mail thread.
