### ISSUE TITLE
Line number is incorrect in the stack trace of the exception thrown in middleware on x64 machines

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/corefx#9670]
I have created a repro for this issue at https://github.com/JunTaoLuo/TestHost/tree/johluo/stack-trace-zip for incorrect line numbers in the stack trace of exceptions thrown. 

Run the sample at `/samples/TestMiddlewareSample` with `dotnet run` after restoring packages. Then navigate to `http://localhost:5000/MiddlewareException` to trigger an exception at https://github.com/JunTaoLuo/TestHost/blob/johluo/stack-trace-zip/src/TestMiddleware/TestMiddleware.cs#L24. In the console of a x64 machine (Windows, Linux and Mac), however, I see the following stack trace report that the exception is thrown on line 27 instead:

```
== Test Middleware ==
Request Path: /MiddlewareException

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HKSSBS4L43JJ": An unhandled exception was thrown by the application.
System.Exception: Middleware Exception
   at TestHost.TestMiddleware.<Invoke>d__2.MoveNext() in C:\gh\tp\TestHost\src\TestMiddleware\TestMiddleware.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

The incorrect line number doesn't affect all exceptions though. In the repro, navigating to `http://localhost:5000` will trigger an exception at https://github.com/JunTaoLuo/TestHost/blob/johluo/stack-trace-zip/sample/TestMiddlewareSample/Startup.cs#L16. This exception is reported correctly:

```
== Test Middleware ==
Request Path: /

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HKSSBS4L43JJ": An unhandled exception was thrown by the application.
System.Exception: Application Exception
   at TestHost.Sample.Startup.<>c.<Configure>b__0_0(HttpContext context) in C:\gh\tp\TestHost\sample\TestMiddlewareSample\Startup.cs:line 16
   at TestHost.TestMiddleware.<Invoke>d__2.MoveNext() in C:\gh\tp\TestHost\src\TestMiddleware\TestMiddleware.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

I also see that this problem seems to only affect x64 machines. On a Windows x86 machine I see that the exceptions contain the correct line numbers:

```
== Test Middleware ==
Request Path: /

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HKSSB81Q7FVP": An unhandled exception was thrown by the application.
System.Exception: Application Exception
   at TestHost.Sample.Startup.<>c.<Configure>b__0_0(HttpContext context) in C:\gh\tp\TestHost\sample\TestMiddlewareSample\Startup.cs:line 16
   at TestHost.TestMiddleware.<Invoke>d__2.MoveNext() in C:\gh\tp\TestHost\src\TestMiddleware\TestMiddleware.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
== Test Middleware ==
Request Path: /MiddlewareException

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HKSSB81Q7FVP": An unhandled exception was thrown by the application.
System.Exception: Middleware Exception
   at TestHost.TestMiddleware.<Invoke>d__2.MoveNext() in C:\gh\tp\TestHost\src\TestMiddleware\TestMiddleware.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
C:\gh\tp\TestHost\sample\TestMiddlewareSamplePS>
```

I have attached the zip files of the repro project and its build outputs (`.dll`s, `.pdb`s, ...) in the root of the repro as `.zip` files.

cc @pakrym @davidfowl

**Comment by tmat** [comment]
@mikem8361

**Comment by joperezr** [comment]
@mikem8361 any updates on this issue? Were you able to repro?

**Comment by mikem8361** [comment]
I haven’t repro this one yet.

**Comment by karelz** [comment]
No repro, closing. Please reopen if you think we made wrong decision.

**Comment by JunTaoLuo** [comment]
I have tried with 1.0.0 packages and the latest 1.1.0 packages and I still see the same issue following my initial repro steps? How did you run the repro?

**Comment by karelz** [comment]
@JunTaoLuo did you try master branch? @mikem8361 which version did you use?

**Comment by JunTaoLuo** [comment]
Ah, I see. You should be using the johluo/stack-trace-zip branch I linked to in the original comment. I have also created a new branch johluo/stack-trace-110-zip using 1.1.0 dependencies.

**Comment by karelz** [comment]
I meant, did you try master branch of corefx?

**Comment by mikem8361** [comment]
I'm sorry. I should have said something sooner. I meant to say to Karel that I have had a chance to repro this issue yet.  Not that it didn't repro for me.

**Comment by davidfowl** [comment]
@JunTaoLuo does this still repro? If not can we close this?

**Comment by JunTaoLuo** [comment]
I have updated the repro with the latest packages for LTS and FTS and I still see the same issue. I have not yet tried this with 2.0 packages though.

**Comment by stephentoub** [comment]
@JunTaoLuo, I'm going through old issues.  Can this be closed?  If not, can you work with @mikem8361 to get a repro?

**Comment by JunTaoLuo** [comment]
Still happening. Created a new repro since the old one is 1.0: https://github.com/JunTaoLuo/TestExceptions. 
```
(AspNetCore) C:\gh\tp\TestExceptions\TestExceptions\Sample> dotnet run
Startup.cs(21,56): warning CS0618: 'IHostingEnvironment' is obsolete: 'Use IWebHostEnvironment instead.' [C:\gh\tp\TestExceptions\TestExceptions\Sample\Sample.csproj]
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\gh\tp\TestExceptions\TestExceptions\Sample
info: Microsoft.AspNetCore.Hosting.Internal.GenericWebHostService[1]
      Request starting HTTP/2 GET https://localhost:5001/MiddlewareException
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLL78QCDSPJ8", Request id "0HLL78QCDSPJ8:00000001": An unhandled exception was thrown by the application.
System.Exception: Middleware Exception
   at Middleware.Middleware.Invoke(HttpContext context) in C:\gh\tp\TestExceptions\TestExceptions\Middleware\Middleware.cs:line 23
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Internal.GenericWebHostService[2]
      Request finished in 33.135200000000005ms 500
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
```

Correct line number should be 20.

**Comment by stephentoub** [comment]
> Correct line number should be 20.

Your concern is that in the code:
```C#
        public async Task Invoke(HttpContext context)
        {
            if (context.Request.Path.Value.EndsWith("MiddlewareException"))
                throw new Exception("Middleware Exception");
            Console.WriteLine("No error");
            await _next(context);
        }
```
the line number is for the `Console.WriteLine("No error");` rather than for the `throw new Exception("Middleware Exception");`?

**Comment by JunTaoLuo** [comment]
Yes.

**Comment by omajid** [comment]
I just ran into something similar and I noticed that the build configuration (`Release` vs `Debug`) makes a difference. I get completely impossible stack traces in `Release`, but the stack trace (including line numbers) looks quite sane in `Debug` mode.

**Comment by mikem8361** [comment]
This may be fixed by PR https://github.com/dotnet/runtime/pull/2269
