### ISSUE TITLE
TcpListener fails to re-bind under Unix for 2 minutes after Stop.

### ISSUE THREAD

**Issue by sichbo** [dotnet/corefx#9780]
Have created a gist to reproduce the behaviour:

https://gist.github.com/sichbo/77615b5c0a6ef7f0fab367862bffb1bd

Basically what's happening is I have a console app which when re-started will always crash on second run because a socket re-bind fails with:

> Unhandled Exception: System.Net.Sockets.SocketException: Address already in use
> at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
> at System.Net.Sockets.Socket.Bind(EndPoint localEP)
> at System.Net.Sockets.TcpListener.Start(Int32 backlog)
> at System.Net.Sockets.TcpListener.Start()
> at TcpListenerTest.Program.<RunServer> d__1.MoveNext()

After about 2 minutes, the application starts normally. It's as if there's a clean-up taking place at OS level some time after the dotnet process quits.

Under Windows there is no such issue and you can `Start/AcceptTcpClient/Stop` and repeat the procedure without any problem.

**Comment by sichbo** [comment]
Attempting to look into why this is happening this evening, I'm having some trouble even convincing a tester project to reference a custom build of System.Net.Sockets.dll. Yesterday I was able to eventually get a different dll (System.Net.Security) to compile against a project, with much thanks to mellinoe's https://github.com/mellinoe/coretemplate -- simply doing a bog standard "Add reference" > "browse.." in VS did the trick using his setup. But when I try it again with the Sockets.dll I get a complaint that the framework is already including such a library. So then I tried in vein to shoehorn it into .proj file anyway and got:

```
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3243: No way to resolve conflict between "System.Net.Sockets, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Net.Sockets, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Choosing "System.Net.Sockets, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily.
1>  Consider app.config remapping of assembly "System.Net.Sockets, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "4.1.0.0" [C:\Users\sichb\.nuget\packages\System.Net.Sockets\4.1.0\ref\netstandard1.3\System.Net.Sockets.dll] to Version "4.1.1.0" [D:\corefx\sichbo\bin\Unix.AnyCPU.Debug\System.Net.Sockets\System.Net.Sockets.dll] to solve conflict and get rid of warning.
1>D:\dotnet-test2\src\SampleExe\Program.cs(41,33,41,44): error CS0433: The type 'TcpListener' exists in both 'System.Net.Sockets, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Net.Sockets, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
1>D:\dotnet-test2\src\SampleExe\Program.cs(56,37,56,46): error CS0433: The type 'TcpClient' exists in both 'System.Net.Sockets, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Net.Sockets, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

Tried its suggestion to redirect using a config file, but I fear that's just a default build statement for old .NET stuff, which is not applicable for anything .netcore related. The whole nuget package thing is a step in the wrong direction in my opinion, but perhaps I'm not representative of a more "cookie cutter" programming audience. 

Any pointers on shoehorning custom built corefx .dlls into projects for actual use would be super helpful.  Ideally I'd like to be able to side-by-side deploy without doing a massive 40MB deployment. Also none of the "Test" projects work for me in the corefx solution FYI. They always error out with:

```
------ Discover test started ------
Dependency '"test-runtime": {
  "target": "project",
  "exclude": "compile"
}' has invalid version specification.
```

.. even though the actual .dll build succeeds, but that also leads me to sometimes not notice when it hasn't because I'm ignoring the lack of "build succeeded" in the output windows.

Having only been using .NETCore since last weekend, it's been a pleasure converting my "Full .NET Framework" distributed hash table server project to using it, as opposed to the week prior trying to work around bugs in Mono getting ready for a release on a few low-end linux servers. You guys have done a lot of amazing work here and with impeccable attention to detail -- many thanks.

**Comment by daviwil** [comment]
Was having the same problem until I found this issue.  Thanks a lot for listing the workarounds, saved me from pulling my hair out!

**Comment by JohnRusk** [comment]
@ericeil  Is there any workaround that I can apply only at the time I'm shutting down the TcpListener, or do all workarounds require me to change options _before_ it starts listening (and thereby change semantics of my app)?

If there _is_ code that can be applied only at the time of shutdown, could you share it please?  I've tried everything I can think of, without success. 

cc @daviwil
