### ISSUE TITLE
Compression.ZipFile Unicode tests failing on OSX in Helix

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#9867]
Failing tests:
```
System.IO.Compression.Tests.ZipFileTest_ConvenienceMethods
CreateFromDirectoryUnicodel
ExtractToDirectoryTest_Unicode
ExtractToDirectoryUnicode
```

Error:
```
Unhandled Exception of type System.NullReferenceException
Message:
System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
   at System.IO.Compression.Tests.ZipFileTestBase.ItemEqual(String[] actualList, List`1 expectedList, Boolean isFile)
   at System.IO.Compression.Tests.ZipFileTestBase.DirsEqual(String actual, String expected)
   at System.IO.Compression.Tests.ZipFileTest_ConvenienceMethods.ExtractToDirectoryTest_Unicode()
```

**Comment by ianhays** [comment]
resolved in https://github.com/dotnet/corefx/pull/11518
