### ISSUE TITLE
Failed tests in System.Threading.Tasks.Channels.Tests.ValueTaskTests on Ubuntu

### ISSUE THREAD

**Issue by svick** [dotnet/corefx#9887]
When running `./build.sh` on an Ubuntu 16.04 VM, I get the following failure in System.Threading.Tasks.Extensions.Tests:

```
/home/osboxes/corefx/Tools/Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [/home/osboxes/corefx/src/System.Threading.Tasks.Extensions/tests/System.Threading.Tasks.Extensions.Tests.csproj]
  System.Threading.Tasks.Extensions.Tests -> /home/osboxes/corefx/bin/AnyOS.AnyCPU.Debug/System.Threading.Tasks.Extensions.Tests/System.Threading.Tasks.Extensions.Tests.dll
  Using /home/osboxes/corefx/packages/ as folder for resolving package dependencies.
  Executing in /home/osboxes/corefx/bin/tests/AnyOS.AnyCPU.Debug/System.Threading.Tasks.Extensions.Tests/netcoreapp1.0
  Executing in unpack directory, do not have to copy files
  Hard linking dependent files...
  /home/osboxes/corefx/bin/tests/AnyOS.AnyCPU.Debug/System.Threading.Tasks.Extensions.Tests/netcoreapp1.0/System.Threading.Tasks.Extensions.dll already exists, not copying.
  Finished linking needed files, moving to running tests.
  Running tests... Start time: 01:46:16
  Commands:
  ./corerun xunit.console.netcore.exe System.Threading.Tasks.Extensions.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.
  
  Discovering: System.Threading.Tasks.Extensions.Tests
  Discovered:  System.Threading.Tasks.Extensions.Tests
  Starting:    System.Threading.Tasks.Extensions.Tests
     System.Threading.Tasks.Channels.Tests.ValueTaskTests.Awaiter_OnCompleted [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
              at System.Threading.Tasks.Channels.Tests.ValueTaskTests.Awaiter_OnCompleted()
     System.Threading.Tasks.Channels.Tests.ValueTaskTests.ConfiguredAwaiter_OnCompleted(continueOnCapturedContext: True) [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
              at System.Threading.Tasks.Channels.Tests.ValueTaskTests.ConfiguredAwaiter_OnCompleted(Boolean continueOnCapturedContext)
  Finished:    System.Threading.Tasks.Extensions.Tests
  
  === TEST EXECUTION SUMMARY ===
/home/osboxes/corefx/Tools/tests.targets(217,5): warning :    System.Threading.Tasks.Extensions.Tests  Total: 25, Errors: 0, Failed: 2, Skipped: 0, Time: 21.718s [/home/osboxes/corefx/src/System.Threading.Tasks.Extensions/tests/System.Threading.Tasks.Extensions.Tests.csproj]
  Finished running tests. End time=01:46:39. Return value was 2
/home/osboxes/corefx/Tools/tests.targets(217,5): warning MSB3073: The command "/home/osboxes/corefx/bin/tests/AnyOS.AnyCPU.Debug/System.Threading.Tasks.Extensions.Tests/netcoreapp1.0/RunTests.sh /home/osboxes/corefx/packages/" exited with code 2. [/home/osboxes/corefx/src/System.Threading.Tasks.Extensions/tests/System.Threading.Tasks.Extensions.Tests.csproj]
/home/osboxes/corefx/Tools/tests.targets(226,5): error : One or more tests failed while running tests from 'System.Threading.Tasks.Extensions.Tests' please check log for details! [/home/osboxes/corefx/src/System.Threading.Tasks.Extensions/tests/System.Threading.Tasks.Extensions.Tests.csproj]
```

**Comment by stephentoub** [comment]
Those tests don't exist anymore in this repo.

**Comment by stephentoub** [comment]
Oh, sorry, I got confused by the "Channels" in there and thought this was the corefxlabs repo.  I'll take a look.

**Comment by stephentoub** [comment]
@svick, was a ton of other work happening on your box when you ran these tests?  These failures imply that some work items queued to the thread pool didn't complete within 10 seconds of being queued.

**Comment by stephentoub** [comment]
Oh, actually, I may know what's happening.  Does your Ubuntu machine have a single core?

**Comment by svick** [comment]
@stephentoub No, there's pretty much nothing else happening on the VM or the host machine.

Considering that in `ValueTaskTests.Awaiter_OnCompleted`, the callback is called 20 seconds after `OnCompleted()`, and it only affects the second test when `continueOnCapturedContext: True`, I suspect it's related to `SynchronizationContext`.

**Comment by svick** [comment]
@stephentoub Yes, it's a singlecore VM.

**Comment by stephentoub** [comment]
> I suspect it's related to  SynchronizationContext .

Yes, it is.  That's why I asked about if this is a single-core.  It's a deadlock due to blocking waiting for the queued callback.  On a single-core VM, xunit by default will only allow a single thread to handle running test work at a time, and that thread is blocking waiting for the queued work that can only be processed by that one thread.

**Comment by stephentoub** [comment]
Thanks for reporting the issue.  I put up a fix for the tests.
