### ISSUE TITLE
[dev/xml] Intermittent failures in random System.Xml.XmlDocument tests related to attributes

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#9894]
Some threading issue in XmlDoc tests.

I'm leaving them not marked as Active issue so it's easier to track it down by finding some common traits. (+ not really sure which ones to disable)
Not sure if this is test or product issue. This might be already fixed - need to be re-verified after merging corefx changes to System.Xml.

Failures catched so far:
```
  Discovering: System.Xml.XmlDocument.Tests
  System.Xml.XPath.Tests -> E:\src\oss\xml\bin\AnyOS.AnyCPU.Debug\System.Xml.XPath.Tests\System.Xml.XPath.Tests.dll
  Using E:\src\oss\xml\packages/ as folder for resolving package dependencies.
  Executing in E:\src\oss\xml\bin\tests\AnyOS.AnyCPU.Debug\System.Xml.XPath.Tests\netcoreapp1.0\
  Hard linking dependent files...
  Discovered:  System.Xml.XmlDocument.Tests
  Starting:    System.Xml.XmlDocument.Tests
     System.Xml.Tests.CopyToTests.CopyToCopiesClonedAttributesAtSpecifiedLocation [FAIL]
        System.Xml.XmlException : The 'r' character, hexadecimal value 0x72, cannot be included in a name.
        Stack Trace:
           E:\src\oss\xml\src\System.Xml\src\System\Xml\Dom\XmlDocument.cs(135,0): at System.Xml.XmlDocument.CheckName(String name)
           E:\src\oss\xml\src\System.Xml\src\System\Xml\Dom\XmlElement.cs(28,0): at System.Xml.XmlElement..ctor(XmlName name, Boolean empty, XmlDocument doc)
           E:\src\oss\xml\src\System.Xml\src\System\Xml\Dom\XmlDocument.cs(1014,0): at System.Xml.XmlDocument.CreateElement(String prefix, String localName, String namespaceURI)
           E:\src\oss\xml\src\System.Xml\src\System\Xml\Dom\XmlDocument.cs(599,0): at System.Xml.XmlDocument.CreateElement(String name)
           E:\src\oss\xml\src\System.Xml\tests\XmlDocument\XmlAttributeCollectionTests\CopyToTests.cs(14,0): at System.Xml.Tests.CopyToTests.CreateDocumentWithElement()
           E:\src\oss\xml\src\System.Xml\tests\XmlDocument\XmlAttributeCollectionTests\CopyToTests.cs(44,0): at System.Xml.Tests.CopyToTests.CopyToCopiesClonedAttributesAtSpecifiedLocation()
  Finished:    System.Xml.XmlDocument.Tests

(this might be related to Globalization tests too so leaving these here)
  Discovering: System.Globalization.Extensions.Tests
  Discovered:  System.Globalization.Extensions.Tests
  Discovered:  System.Xml.XmlDocument.Tests
  Starting:    System.Globalization.Extensions.Tests
  Starting:    System.Xml.XmlDocument.Tests
     System.Xml.Tests.LocalNameTests.ElementWithPrefix [FAIL]
        System.Xml.XmlException : The 'e' character, hexadecimal value 0x65, cannot be included in a name.
        Stack Trace:
           E:\src\oss\xml\src\System.Xml\src\System\Xml\Dom\XmlDocument.cs(135,0): at System.Xml.XmlDocument.CheckName(String name)
           E:\src\oss\xml\src\System.Xml\src\System\Xml\Dom\XmlElement.cs(28,0): at System.Xml.XmlElement..ctor(XmlName name, Boolean empty, XmlDocument doc)
           E:\src\oss\xml\src\System.Xml\src\System\Xml\Dom\XmlDocument.cs(1014,0): at System.Xml.XmlDocument.CreateElement(String prefix, String localName, String namespaceURI)
           E:\src\oss\xml\src\System.Xml\src\System\Xml\Dom\XmlDocument.cs(599,0): at System.Xml.XmlDocument.CreateElement(String name)
           E:\src\oss\xml\src\System.Xml\tests\XmlDocument\XmlNodeTests\LocalNameTests.cs(30,0): at System.Xml.Tests.LocalNameTests.ElementWithPrefix()
     System.Xml.Tests.CreateAttributeTests.CreateBasicAttributeTest [FAIL]
        System.Xml.XmlException : The 'a' character, hexadecimal value 0x61, cannot be included in a name.
        Stack Trace:
           E:\src\oss\xml\src\System.Xml\src\System\Xml\Dom\XmlDocument.cs(135,0): at System.Xml.XmlDocument.CheckName(String name)
           E:\src\oss\xml\src\System.Xml\src\System\Xml\Dom\XmlAttribute.cs(27,0): at System.Xml.XmlAttribute..ctor(XmlName name, XmlDocument doc)
           E:\src\oss\xml\src\System.Xml\src\System\Xml\Dom\XmlDocument.cs(1004,0): at System.Xml.XmlDocument.CreateAttribute(String prefix, String localName, String namespaceURI)
           E:\src\oss\xml\src\System.Xml\src\System\Xml\Dom\XmlDocument.cs(553,0): at System.Xml.XmlDocument.CreateAttribute(String name)
           E:\src\oss\xml\src\System.Xml\tests\XmlDocument\XmlDocumentTests\CreateAttributeTests.cs(15,0): at System.Xml.Tests.CreateAttributeTests.CreateBasicAttributeTest()
     System.Xml.Tests.AppendTests.AppendRemovesExistingAttribute [FAIL]
        System.Xml.XmlException : The 'r' character, hexadecimal value 0x72, cannot be included in a name.
        Stack Trace:
           E:\src\oss\xml\src\System.Xml\src\System\Xml\Dom\XmlDocument.cs(135,0): at System.Xml.XmlDocument.CheckName(String name)
           E:\src\oss\xml\src\System.Xml\src\System\Xml\Dom\XmlElement.cs(21,0): at System.Xml.XmlElement..ctor(XmlName name, Boolean empty, XmlDocument doc)
           E:\src\oss\xml\src\System.Xml\src\System\Xml\Dom\XmlDocument.cs(1014,0): at System.Xml.XmlDocument.CreateElement(String prefix, String localName, String namespaceURI)
           E:\src\oss\xml\src\System.Xml\src\System\Xml\Dom\XmlDocument.cs(595,0): at System.Xml.XmlDocument.CreateElement(String name)
           E:\src\oss\xml\src\System.Xml\tests\XmlDocument\XmlAttributeCollectionTests\AppendTests.cs(14,0): at System.Xml.Tests.AppendTests.CreateDocumentWithElement()
           E:\src\oss\xml\src\System.Xml\tests\XmlDocument\XmlAttributeCollectionTests\AppendTests.cs(48,0): at System.Xml.Tests.AppendTests.AppendRemovesExistingAttribute()
  Finished:    System.Xml.XmlDocument.Tests
```

**Comment by krwq** [comment]
this is possibly already fixed

**Comment by danmosemsft** [comment]
Reopen if you see this again.
